### ISSUE TITLE
Love for TypeScript

### ISSUE THREAD

**Issue by deiangi** [Microsoft/TypeScript#10011]
@ahejlsberg 

I love what you've done with VS Code and TypeScript - that's dream come true for me! Thank you!

I am sure there are other people who contributed to that but for me you Mr. Anders represent all awesome coding tools like Delphi, C# and now TypeScript. 

Thank you for existing!

@GitHub How come there is  but no  tag !?

**Comment by aleksey-bykov** [comment]
you guys are so you

**Comment by ahejlsberg** [comment]
On behalf of the TypeScript team, thanks for the kind words!

**Comment by irwansyahwii** [comment]
As the past user of CoffeeScript and ES6 I want to thank you to all TypeScript team for giving us a language that allow us to apply SOLID principles in JavaScript world. Now, I don't have to scratch my head to find many errors that easily catched by TypeScript compiler. I also feel more confident again with my code since I can write unit tests for my classes and I've spent less time maintaining the test codes. For me TypeScript is the best language in the world because it brings more fun to JavaScript world. 

Oh yeah, specially for @ahejlsberg  I am a long time Delphi fans and C# users thank you so much for your contribution in Software Engineering field.

**Comment by l2dy** [comment]
@GitHub I want to +1 for the "By Design" label.

**Comment by Davidhanson90** [comment]
❤ ❤ ❤ TypeScript

**Comment by ertyseidohl** [comment]
I wrote [a game](http://love.erty.me) about Love in Typescript recently :)

**Comment by aldrinleal** [comment]
I'd also like to thank for Turbo Pascal as well! <3

**Comment by chancancode** [comment]
+1, I can reproduce this issue in http://github.com/tildeio/glimmer

**Comment by danielearwicker** [comment]
Anyone else enjoy visiting the TS blog page every few days, just to see if there's a new version out? Each time there is, It's like childhood xmas.

**Comment by ichpuchtli** [comment]
Thanks anders and the typescript team for making javascript great again. :us:

**Comment by eDameXxX** [comment]
I didn't learn TypeScript yet but enthusiasm here is amazing :grinning:  Keep up the good work.

**Comment by BardurArantsson** [comment]
> I didn't learn TypeScript yet but enthusiasm here is amazing 😀 Keep up the good work.

Learn it. It's amazeballs!

**Comment by 0xmohit** [comment]
I guess that this needs the [cla-not-required](https://github.com/Microsoft/TypeScript/labels/cla-already-signed) label.

**Comment by dmly** [comment]
Let's vote @ahejlsberg for the Jolt award this year!

**Comment by pleerock** [comment]
I have tried over 10 programming languages in last 10 years, and my primary languages were java and php. I loved java for its object oriented style and strong typings and rules, and php for its dynamic nature and open source community. Now Im primary TypeScript developer and I love this language because it has everything I wanted to see in a single language.

**Comment by maxfridbe** [comment]
I've used TS in our organization since v .4 that and we are on latest now.  I even open sourced a c#=>.d.ts generator. Thank you!  Without ts we could never have used js in 100 sln's not with this many devs.

**Comment by jo-lee** [comment]
Love it! Really love it!

**Comment by FagnerMartinsBrack** [comment]
Nice! I've got a similar thanks a few months ago too: https://github.com/js-cookie/js-cookie/issues/137#issuecomment-183552245.

Only those that work with Open-Source will understand why this matters. It shows that our hobby makes a difference.

As Kevin Kruse said:

> Life is about making an **impact**, not making an **income**.

**Comment by evanx** [comment]
Yes, thank you sir and your team, especially for your opensource, platform neutrality and convergence to standard javascript

Never thought I'd EVER hear myself say this: Keep up your brilliant work Microsoft, doing "embracing and extending" in an commendable way

**Comment by branc116** [comment]
@ahejlsberg for presidente !! :)

**Comment by lukedupin** [comment]
I also LOVE typescript.  Its all I use for JS work these days.  Now I just wish MS would release VS for OSX and Linux, I'd switch my toolchain over tomorrow!  Thanks again, great work!

**Comment by vivainio** [comment]
@danielearwicker I'm pretty sure I get notified of new TS releases with few min delay on twitter, but I do admit checking on https://github.com/Microsoft/TypeScript/wiki/Roadmap weekly to see what kind of future the overlords are planning for us ;)

**Comment by NoelAbrahams** [comment]
TypeScript from our perspective has been the great leveler. It has levelled the playing field for JavaScript web/mobile development, by providing a powerful tool for developing scalable applications - available to everyone for absolutely free.

For a startup like ours, this means its possible to develop sophisticated applications with [modern UIs](https://cloud.githubusercontent.com/assets/1106823/17285830/43bca530-57bd-11e6-9086-54101cdb6081.png) and behaviour with limited resources so that we can compete with the big players like Twitter, Pinterest and Facebook.

@ahejlsberg's experience has definitely been the key factor in making TypeScript useful for real-world applications, but the rest of the team is not too bad either! :smile:

**Comment by glor** [comment]
Although my primary languages are C and COBOL I recently took a look into this new Javascript thing and I must say that I find it equally fascinating and confusing.
Firstly I just cannot get pointers working. The compiler refuses everything and even more strange is that I can't find anything on the internet. And secondly: Is there something like a Makefile in TypeScript?

**Comment by branc116** [comment]
@glor 
![bda068f44fe03f66b8f4a5d15492b6d44517fae950909c7323f763bf4dc52da1](https://cloud.githubusercontent.com/assets/16038323/17311565/9a56bc0c-584c-11e6-9047-db394aa40d91.jpg)

**Comment by johnfn** [comment]
@lukedupin have you heard about visual studio code?

**Comment by lukedupin** [comment]
Sorry for the thread hi-jack, I wont continue this tangent.
@johnfn I have heard about VS code.  I downloaded it and tried it, but found jetbrains was superior.  VS code is a great step, and I was very happy to see MS even considered such a thing, but I am happy with jetbrains until VS full is released for linux in my case.  Thanks for the tip!

In the mean time, back to Typescript praise.

**Comment by johnfn** [comment]
Back on topic, TypeScript is amazing. I can't think of another product which took something so painful to use and made it so simple and enjoyable.

**Comment by glor** [comment]
@johnfn I think the invention of c would fall in that category...

**Comment by Ziriax** [comment]
Yes indeed, thanks a lot for Delphi, C# and Typescript! And slowly but surely the strongly typed Haskell virus spreads in mainstream languages :)

**Comment by gavinpc-mindgrub** [comment]
https://news.ycombinator.com/item?id=15268096

> In twenty-five years as a working programmer, I have fallen in love with a piece of technology four times: Emacs (on my third attempt), Tup (the build system by Mike Shal), React... and now TypeScript. I've been using it full-time for a few weeks now, and I can't imagine going back.

That was five months ago, and the love for TypeScript has slowly begun to spread at my workplace.  Thanks, all!

**Comment by aleksey-bykov** [comment]
@RyanCavanaugh sticking labels is nice, but code formatting is still not working

**Comment by RyanCavanaugh** [comment]
Bad bots, what are we doing here

**Comment by FagnerMartinsBrack** [comment]
@RyanCavanaugh BOTs can't love, so they don't see a reason for one's existence =(

**Comment by johnnyreilly** [comment]
Nooooooooo
