### ISSUE TITLE
proposal: add ' min-tsc-version' config on d.ts file and tsconfig.json

### ISSUE THREAD

**Issue by WanderWang** [Microsoft/TypeScript#10022]
consider this code : 

```
//some-lib.d.ts
declare function foo():number | undefined
```

```
//a.ts
foo();
```

when somebody use `some-lib.d.ts` with tsc1.8 , they will got a exception `some-lib.d.ts(1,33): error TS2304: Cannot find name 'undefined'.` . And they will be confused because  they may not know about strict-null features in TypeScript 2.0 

So I think we should add a 'min-tsc-version' on d.ts file , for example : 

```
//some-lib.d.ts


/// min-tsc-version : 2.0.0
declare function foo():number | undefined
```

```
//tsconfig.json
{
    “compileOption": {
        "min-tsc-version":2.0.0
    }
}
```

**Comment by WanderWang** [comment]
Another user story : 

We write some typescript code with ts2.0 features , and VSCode .

becauseof vscode use TypeScript 1.8.10 now , so my code will got some error message from tss 1.8 ( including in vscode ) . 

If here is a " min-tsc-version " in tsconfig.json , VSCode could report a friendly error message to let developers set custom typescript-sdk path in VSCode

**Comment by mhegazy** [comment]
the problem is it is not guaranteed to fail. so in most cases you will get the warning and will find it annoying. 

you can see similar discussion in https://github.com/Microsoft/TypeScript/issues/10412,  https://github.com/Microsoft/TypeScript/pull/6702#issuecomment-213627081 and in https://github.com/Microsoft/TypeScript/issues/7573.
