### ISSUE TITLE
RegExpMatchArray has lost some compatibility with Array since 2.1.0-dev.20160729

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#10041]
**TypeScript Version:**  master

**Code**

```ts
(''.match(/ /) || []).map(s => s.toLowerCase());
```

**Expected behavior:**

```
$ node built/local/tsc.js --lib es6 --strictNullChecks index.ts
```

**Actual behavior:** 

```
$ node built/local/tsc.js --lib es6 --strictNullChecks index.ts
index.ts(1,1): error TS2349: Cannot invoke an expression whose type lacks a call signature.
```

**Comment by RyanCavanaugh** [comment]
Same root cause as #10025 but it's much less clear how to fix this example

**Comment by falsandtru** [comment]
I understand as a breaking change, not a bug. Thanks @RyanCavanaugh .

**Comment by ahejlsberg** [comment]
Several subtle issues at play here. With #9407 we still perform subtype reduction for the operands of the `||` and `?:` operators. However, even after subtype reduction the expression `(''.match(/ /) || [])` has type `RegExpMatchArray | never[]` because there are extra optional properties introduced by `RegExpMatchArray`. In the property access for the `map` property we would previously perform subtype reduction *again*, and that would reduce the union function type of `map` down to a single type. This step we now omit because of #9407.

I think the real issue here is that we produce the union type `RegExpMatchArray | []` instead of just `RegExpMatchArray` (and this issue was there all along). It may be that for `||` and `?:` we should say that if neither operand is a *subtype* of the other, but one is *assignable* to the other, we pick the type of the one to which the other is assignable.

**Comment by falsandtru** [comment]
Thanks for the fix!
