### ISSUE TITLE
Index signature impacting properties it does not match

### ISSUE THREAD

**Issue by sk1981** [Microsoft/TypeScript#10043]
**TypeScript Version:**  1.8.10 / Playground

**Code**
```ts
interface StringArray {
	len?: number;
}

interface StringArray2 {
    [propName: number]: string;
    len?: number;
}

var myArray: StringArray = {
	length: [], // FAILS - as expected
}

var myArray2: StringArray2 = {
	length: [], //  OK - Unexpected ?
}
```

**Expected behavior:**
Use of length property in myArray2 should fail as that property is not defined for StringArray2 and it does not matches the type index type signature present in the interface.

**Actual behavior:** 
While use of length property fails for myArray (as expected), it does not fail for StringArray2 which is unexpected i think due to the reason listed above.

**Comment by RyanCavanaugh** [comment]
Some confusion here I think.

The first example fails because `length` is not a known property in `StringArray` and there is no index signature in `StringArray`.

The second example doesn't fail because `length` is not a number, so it's not subject to the numeric index signature. Additionally, the fact that `length` isn't a known property in `StringArray2` is allowed because of the existence of some index signature.

**Comment by sk1981** [comment]
oh, sorry, i didn't knew this was as intended and don't want to convert this to QnA but one last confirmation question:-
So, the presence of index signature whose type is `number` and value is `string` (propName in StringArray) will allow the object to also accept any `non-numeric` property ?

**Comment by RyanCavanaugh** [comment]
That's basically correct, yes

**Comment by sk1981** [comment]
Got it, thanks a lot for promptly handling so many issues !. 

It was a bit unexpected for me, as I was expecting the stringarray to be restricted to `[propName: number]: string` and `len?: number`. 

Will try to investigate or ask on stackoverflow how to achieve what that above.
