### ISSUE TITLE
enable generating Flow declarations from TypeScript

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#10075]
now that flow is here (for Windows) please consider an option to generate Flow-style declarations on emit

https://flowtype.org/blog/2016/08/01/Windows-Support.html

**Comment by aleksey-bykov** [comment]
there are some friction points like `bool` in Flow and `boolean` in TypeScript, other  than that they are very similar:

https://flowtype.org/docs/declarations.html

**Comment by aleksey-bykov** [comment]
unless we are talking politics

**Comment by yahiko00** [comment]
One should ask Flow to emit TS declarations instead.

**Comment by aleksey-bykov** [comment]
it's hard to ask for that since Flow doesn't generate anything, it's a just a type checker over what you put in it

**Comment by DanielRosenwasser** [comment]
It isn't politics as much as it is a labor burden (it's not easy, as we'd have to keep close track of what Flow supports and occasionally try to retrofit what we support). Since this would be another thing for us to maintain, and we're considering adopting a pluggable transform-based emitted, I'd imagine this as something others could do if so inclined.

**Comment by aleksey-bykov** [comment]
on the other hand it might be yet another selling point for typescript in its conquest of the world, might be worth it
