### ISSUE TITLE
Why does tsc not pick up definition files with the same name as implementation files?

### ISSUE THREAD

**Issue by Ptival** [Microsoft/TypeScript#10149]
**TypeScript Version:**  1.9.0

**Code**

``` ts
// foo.ts
class Foo implements IFoo {}
// foo.d.ts
interface IFoo {}
// bar.ts
class Bar implements IBar {}
// bar-interface.d.ts
interface IBar {}
// baz.ts
function f(foo: IFoo, bar: IBar) {}
// tsconfig.json
// [...]
  "filesGlob": [ "*.ts" ]
```

**Expected behavior:**
Everything compiles when running `tsc -p .`

**Actual behavior:** 
Running `tsc -p . --listFiles`, one can see that the picked up files are:

```
bar-interface.d.ts
bar.ts
baz.ts
foo.ts
```

Notably, `foo.d.ts` is not picked up, because it has the same name as `foo.ts` and lives in the same directory.

Is this intentional? What is the rationale for this?

Many languages allow putting interface files right next to their implementation, with just the extension changing. In TypeScript, it seems one has to either put definitions in a subdirectory or give the definition file a different name.

**Comment by mhegazy** [comment]
first `fileGlob` is not a supported property in tsconfig.json, see http://www.typescriptlang.org/docs/handbook/tsconfig-json.html for more details.
 
The compiler does not pick up files that are considered outputs on its inputs.  if you really want to add them. then list them explicitly in `"files": ["foo.ts", "foo.d.ts"]`.

in general it is not a good idea to have two files with the same name, since the  compiler makes assumptions about file names for importing.
