### ISSUE TITLE
Generator's return "any" type when yielded 

### ISSUE THREAD

**Issue by rylev** [Microsoft/TypeScript#10148]
**TypeScript Version:**  1.8, 2.0, and nightly

**Code**
The following code compiles even though it would appear that `result` should have type `string`: 

```ts
function* myGenerator() {
  yield "hello"
}

function* myOtherGenerator() {
  const result = yield myGenerator()
  result.methodNotAvailableOnString()
}
```

**Expected behavior:**
When a generator is yielded I expected that the type of the subsequent variable to be whatever `T` is in `myGenerator`'s return type `IterableIterator<T>`

**Actual behavior:** 
This is however not the case. `result` has type `any`. Should the TypeScript compiler be able to infer that that type of `result` should be `string`?

**Comment by DanielRosenwasser** [comment]
Unlike the `await` keyword that "grabs" the `Promise`d value from an `async` function, `yield` **does not** grab the yielded value of a generator. It instead makes it available for anyone consuming the current generator. In that case, you are yielding an iterator, meaning any callers will have an iterable of iterables of strings.

The value produced by `yield` within a generator is the argument that you pass in to `next()`. This value can be anything, but can't be inferred by the structure of the generator.

```ts
function *g() {
    console.log("AAA");
    let x = yield "Hello";
    console.log("BBB");
    console.log(x);
    console.log("CCC");
}

var iter = g();
var rr = iter.next("unwitnessed"); // first call's value is 
console.log(rr.value);
iter.next("World");
```

Outputs:

```text
AAA
Hello
BBB
World
CCC
```

If we had default type parameters, we could say that the type passed into `next` defaults to `any`, but if you want extra strictness, you could enforce it otherwise.
