### ISSUE TITLE
Disallowing certain operators on a custom type

### ISSUE THREAD

**Issue by d180cf** [Microsoft/TypeScript#10155]
In general, tsc allows all the operators on any types, except certain specific cases, like `a + b` where `a` and `b` are boolean values. There are cases when disabling certain operators the same way would be useful:

```ts
// js doesn't have 64 bit numbers,
// so here is a clumsy workaround
interface int64 {
  [0]: number;
  [1]: number;
}

const a: int64 = ...;
const b: int64 = ...;

if (a == b) {
  ...
}
```

The `a == b` check is a mistake that will be hard to catch later. It would be nice to disable the `==` operator (as well as others) for this `int64` type.

**Comment by RyanCavanaugh** [comment]
This is somewhat hard to reason about since `===` between 2 objects is always going to be a meaningful operation. I'm not sure if this is common enough to justify a language feature, but TSLint is supporting type-based rules that would let you disallow this.

**Comment by d180cf** [comment]
Between two objects yes, but with primitive types it's a different story: `===` means "compare without coercion"  and the problem is that `===` is often used to compare with `0` and is even recommended to use by many. Now the problem is that if in the example above I decided to switch from `number` to `int64` in some cases, I will miss those `==` and `===` that were valid for `number` but have a different meaning for `int64`, so I'll have to find all places where those variables are used and check if there are some `==` left.

Perhaps a reasonable thing to do would be to mark some types as "value types" so that tsc will know the intent of using `==`?

**Comment by kitsonk** [comment]
Still the domain of a linter in my opinion.  Both `==` and `===` can have useful meanings and distinctions irrespective of the type.

**Comment by d180cf** [comment]
Ok, then why does tsc disallow `b1 + b2` when `b1` and `b2` are booleans?

**Comment by kitsonk** [comment]
Fair point, I would somewhat argue that is a linter rule, but I can see why the TypeScript team choose to error on that, because that is almost invariable an error.  The `+` operator is a particularly nasty piece of ECMAScript in how it behaves at runtime.  While `==` and `===` can have confusing and surprising behaviours, they can still have legitimate meaning, even when mixing primitive and non-primitive values, though some/many developers don't understand the ramifications of using it.

Where as `false + true` is run-time valid, the resulting value is non-sensical (`1`) and is statically identifiable as an error given a static typing system.  While `==` and `===` could result in some "surprising" results, in certain situations they can result in what the developer intended.  While I personally hate relying upon loose comparison, I have seen plenty of code that does and is intended that way.

**Comment by mhegazy** [comment]
Just like @kitsonk mentioned, `a == b` could be correct. but `true + false` is never correct.
