### ISSUE TITLE
The type keyword, compiler errors and and editor messages

### ISSUE THREAD

**Issue by wkrueger** [Microsoft/TypeScript#10217]
So, since it was born I really like the `type` keyword. It seems more idiomatic than `interface`. Declare a variable in the type realm. Compose them with & and |. I thought I would be able to even ban the `interface` keyword usage.

Unfortunately I had to jump back a bit to `interface` because declaring structures using `type x =` generates really verbose error messages (and VS code tooltips) containing the whole type definition -- with all of the properties. On the other hand when I use `interface` the structure gets "aliased" to the interface name in those messages, making them not that lengthy.

Is it feasible that types declared with `type` also get aliased in compiler errors and editor assistance?

**Comment by RyanCavanaugh** [comment]
This is actually happening in 2.0 already as part of some other work.
```ts
type MyType = (number | string) & { n: any };
const m: MyType = false;
```
now produces
> error TS2322: Type 'boolean' is not assignable to type 'MyType'.

One caveat on this behavior is that you'll only see the alias when the alias declaration was the *first* time the compiler saw that type. For example, you won't see the alias used when the type is `number | string` because `lib.d.ts` uses `number | string` in a non-aliased way (and is processed before any other file).

**Comment by wkrueger** [comment]
Thank you for your great work guys!
