### ISSUE TITLE
import JS lib error

### ISSUE THREAD

**Issue by g3r4n** [Microsoft/TypeScript#10246]
I have search a lot but i haven't find a solution.
How import a JS library in typescript ?
When i'm doing : 
`import Store from 'store';`
I have the following error : 
`Cannot find the module 'store'`
But my code is working fine.

**Comment by DanielRosenwasser** [comment]
Hey @g3r4n, in the future please ask on StackOverflow. This is not a support forum.

You'll need to use a declaration file to describe the module `store`. Declaration files are basically a description of your JavaScript file's API so that TypeScript can understand how to consume it. If `store` is something you've written, you'll have to write a `.d.ts` file in the same place as your `.js` file

 [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) is a repo of many different 3rd party libraries and might have the `.d.ts` for the library that you're looking for.

If you're using TypeScript 2.0 beta, then you can use npm to install those files [as I describe here](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/). You would run:

```shell
npm install -s @types/store
```

If not, you'll have to use a package manager called [Typings](https://github.com/typings/typings):

```shell
npm install -g typings
```

and run the following to get the package declaration files

``` 
typings install --global dt~store

**Comment by g3r4n** [comment]
Thx !

**Comment by aikssen** [comment]
Actually the complete solution is:

From [DefinitelyTyped/@storejs](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/storejs) install the declaration
**Notice the suffix `js` at the end.**

`npm i -D @types/storejs`

Use in this way:

```
import * as store from 'store';

store.set('user', { name:'Marcus' })
console.log(store.get('user').name);
```

And in the `tsconfig.json` put the reference:
```
{
  "compilerOptions": {
    ...
    "typeRoots": [
      "./node_modules/@types/"
    ]
  }
}
```
