### ISSUE TITLE
CI: Configure appveyor for testing on Windows

### ISSUE THREAD

**Issue by am11** [Microsoft/TypeScript#1034]
The intent is to:

- Test it in both cmd and ps (sequentially) on Win86 and Win64 (parallelly). This way; four jobs would run in parallel with testing on both; cmd and ps.
- Make it easy for the contributors (forked repos folks; who are not using Windows) to test on Windows before sending PR.

The CI builds would be accessible at: https://ci.appveyor.com/project/microsoft/typescript. The status badge can be obtained from http://www.appveyor.com/docs/status-badges.

For `appveyor.yml` references, see:

* http://www.appveyor.com/docs/appveyor-yml
* http://www.appveyor.com/docs/build-configuration
* https://github.com/gruntjs/grunt/blob/master/appveyor.yml
* https://github.com/paed01/catbox-azure-table/blob/master/appveyor.yml

The setup is pretty straight-forward:

* Add the appveyor.yml in repo's root.
* Sign in with GitHub on http://appveyor.com and select typescript repo under projects.

**Comment by am11** [comment]
With mocha v2.2.1 (latest), seems like those issue are fixed. All tests are passing for node.js v0.10.x (old stable branch) and v0.12.x (current stable branch). Also passing for io.js v1.5.x.

CI URL: https://ci.appveyor.com/project/am11/typescript/build/1.0.8
(corresponds to: https://github.com/am11/TypeScript/commit/d1e29a6912924ad7bac2b8724a168e35ca7b14a4)

@danquirk, 

There must be a good reason why others have configured AppVeyor in addition to TravisCI. :sunglasses: 

IMO, this comes handy for contributors who are committing from Unix-like OSes and want to make sure the cross-platform compatibility. Path related issue, linefeeds inconsistencies and since so forth.

**Comment by danquirk** [comment]
_IMO, this comes handy for contributors who are committing from Unix-like OSes and want to make sure the cross-platform compatibility. Path related issue, linefeeds inconsistencies and since so forth._

I get the desire here but in practice this hasn't been much of an issue for us. That is, we actually are in the opposite situation right now and have had very few issues after a few early hiccups when first adding Travis support. The vast majority of our team develops TypeScript on Windows with Visual Studio and then submits to a CI server that runs tests on *nix. 

That said, I'll try to poke around again and see if there're enough useful features to justify the costs. If any of you folks submitting PRs regularly really do like AppVeyor for some specific features that's also worth knowing.

**Comment by mhegazy** [comment]
We have not seen much platform-specific issues around this. we also have an internal Windows CI server that would catch such things if they slip by. do not think it is worth the complexity.
