### ISSUE TITLE
2.0: window.opener declared as readonly

### ISSUE THREAD

**Issue by jeffreymorlan** [Microsoft/TypeScript#10379]
When you open a popup window of a page on a different domain, [for security reasons you might want to set its window.opener to null](https://medium.com/@jitbit/target-blank-the-most-underestimated-vulnerability-ever-96e328301f4c). This is a type error in 2.0 because the `opener` property is incorrectly declared read-only:

```ts
var newWnd = window.open(...);
newWnd.opener = null;
// Left-hand side of assignment expression cannot be a constant or a read-only property.
```

**Comment by kitsonk** [comment]
It is doing this because the Microsoft Edge IDL has it as [read only](https://developer.microsoft.com/en-us/microsoft-edge/platform/documentation/apireference/interfaces/window/).  Chromium as a [special getter](https://chromium.googlesource.com/chromium/blink/+/master/Source/core/frame/Window.idl#61).  The [W3C IDL states](https://w3c.github.io/html/browsers.html#the-window-object) that it is read/write and describes the behaviour of when setting it to `null`.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by cwmacdon** [comment]
@mhegazy This happens again in TS 2.8.1

**Comment by mhegazy** [comment]
Fix up in https://github.com/Microsoft/TSJS-lib-generator/pull/397

**Comment by cwmacdon** [comment]
I imagine this will be in some upcoming 2.8.2 patch release?

**Comment by mhegazy** [comment]
should be in 2.8.2
