### ISSUE TITLE
Narrowing from "any" using instanceOf will overwrite another narrowing expression in "||"

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#10398]
TypeScript Version: build from master 8/17

```typescript
function foo(x: any) {
    if (typeof (x) === 'number' || x instanceof Number) {
        isNaN(x)  // error x has type Number
    }
}
```

Note: this doesn't happen if parameter `x` has type `number | Number`

**Comment by RyanCavanaugh** [comment]
But this is still an error if we correctly narrow to `number | Number` -- `isNaN(new Number(3))` is not permitted (though maybe it should? Hard to say)

**Comment by yuit** [comment]
@RyanCavanaugh true; Though the error message is confusing then since you will be like why the type is only `number`

**Comment by weswigham** [comment]
`isNaN` coerces to a number with `valueOf` before checking (`isNaN({}) === true`), so it's conceivable that it should just have a wider argument type, rather than strictly `number`.

**Comment by DanielRosenwasser** [comment]
@weswigham see #4002 and #3947.

**Comment by ahejlsberg** [comment]
Since `number` is a subtype of `Number`, there's really no difference between `number | Number` and `Number`. In control flow analysis we perform subtype reduction at junction points only when the control flow type includes "foreign" types, i.e. types that don't occur in the declared type. The type guards in the `if` statement in combination produce the type `number | Number`, which then gets subtype reduced to `Number` if the body of the `if` statement. But this subtype reduction doesn't happen when the declared type itself is `number | Number` because the types aren't considered foreign.
