### ISSUE TITLE
InstanceOf incorrectly narrow when two type extends same base class

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#10422]
Version: master

``` typescript
class B { name: string }
class A { }
class C { name: string; }
var a: A | C;
if (!(a instanceof A)) {
    a;  // a has "never" type 
}
```

The change is a result of the PR #10216. It is followed the specification in that PR. Though I wonder whether this should get treated differently.

**Comment by yortus** [comment]
You can remove `extends B` from both the `A` and `C` classes and see the same behaviour, so extending the same base class doesn't seem important here.
 
Isn't this because `C` is *structurally* a subtype of `A`? So when the type guard removes `A`, it also removes `C` which it considers a subtype, leaving `never` as the narrowed type.

The PR #10216 addressed a very similar situation raised in #7271, but the problem and the fix addressed the situation where unrelated classes were structurally identical. This is a case where unrelated classes have a structural subtype-supertype relationship.

You can see the same behaviour with the first example in https://github.com/Microsoft/TypeScript/issues/7271#issuecomment-189619971.

**Comment by yuit** [comment]
@yortus  thanks for correcting my example! Yes, it is because `C` is subtype of `A` but structurally not identical to `A` which according to PR #10216, then type `C` is instance of type `A`. 

This example is slight different from the example in your comment [comment](https://github.com/Microsoft/TypeScript/issues/7271#issuecomment-189619971) in that we will treat user-defined typeguard and `instanceof` slightly different as @mhegazy  pointed out [here](https://github.com/Microsoft/TypeScript/issues/7271#issuecomment-217544757)

**Comment by yortus** [comment]
@yuit this behaviour was the same before #10216 was merged - you can see it for example using `typescript@2.1.0-dev.20160807`. #10216 tweaked the existing narrowing behaviour for structurally identical types, but did not affect this scenario.

**Comment by mhegazy** [comment]
That is a current design limitation with structural comparison.

**Comment by ericmorand** [comment]
So when will this bug be fixed?
