### ISSUE TITLE
Optional property treated as required in function return value of inferred type

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#10437]
**TypeScript Version:**  nightly

**Code**

```ts
interface PartialPoint {
  x?: number;
  y?: number;
}

function f<T>(a: T, b: () => T) {}

const p: PartialPoint = { x: 0 };
f(p, () => ({ x: 0 }));
```

**Expected behavior:**

No error.

**Actual behavior:** 

    a.ts(9,1): error TS2453: The type argument for type parameter 'T' cannot be inferred from the usage. Consider specifying the type arguments explicitly.
      Type argument candidate 'PartialPoint' is not a valid type argument because it is not a supertype of candidate '{ x: number; }'.
        Property 'y' is missing in type '{ x: number; }'.

The error is fixed if we make `x` non-optional, explicitly call f<PartialPoint>, or make the second parameter just `T` instead of `() => T`.

**Comment by RyanCavanaugh** [comment]
Is this different from #9205?

**Comment by RyanCavanaugh** [comment]
@JsonFreeman can you explain why in this example

```ts
interface PartialPoint {
  x?: number;
  y?: number;
}

function f<T>(a: T, b: T) {}
declare function id<T>(x: T): T;

const p: PartialPoint = { x: 0 };
f(p, { x: 0 });
```
we contextually type the object literal and the call succeeds, but in the example as written the return value *isn't* contextually typed?

**Comment by JsonFreeman** [comment]
I think it is contextually typed in both cases. But in a return expression, the object literal gets widened. This causes the type to lose its `TypeFlags.ObjectLiteral` flag. As a result, when we get to `propertiesRelatedTo`, the value of `requireOptionalProperties` is true. This has the effect of making PartialPoint not a supertype because of the optional property `y`. I'm not sure if something else has changed that also affects this, but that much still appears to be true.

**Comment by JsonFreeman** [comment]
Basically I blame it on widening of return expressions.

**Comment by andy-ms** [comment]
Closing as duplicate of #9205. Thanks for the explanation.

**Comment by RyanCavanaugh** [comment]
Every few months
![image](https://cloud.githubusercontent.com/assets/6685088/17825036/44d60c84-661a-11e6-8826-9cd1e6df6ea7.png)
