### ISSUE TITLE
potential bug: should this compile?

### ISSUE THREAD

**Issue by opensrcken** [Microsoft/TypeScript#10456]
**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)

**Code**

```ts
const numbers: Array<number> = [1];

const mixed: Array<number|string> = [1, 'two'];

function test(someArray: Array<number|string>) {
  // XXX: THIS LINE SEEMS UNSAFE
  someArray.push('asdf');
}

test(numbers);
```

**Expected behavior:**
This should probably not compile.

**Actual behavior:** 
It compiles.

I realize this limits some other things you can do if you want a function to be able to operate on both arrays of numbers or arrays of number|string, but hopefully there is, or will be, some way to discriminate between arrays of different types.

**Comment by DanielRosenwasser** [comment]
Yes, this is working as intended. Types are *covariant* over their element types. Since `number` is a subtype of `number | string`, `Array<number>` is considered a subtype of `Array<string>`. The rationale is that this approach matches people's intuition fairly well.

Another surprise for people is that functions are related in a *bivariant* manner over their parameters (rather than contravariant), which is actually pretty closely related to this issue. I'd suggest you read through [this entry in the FAQ](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant).
