### ISSUE TITLE
TS2307: Cannot find module 

### ISSUE THREAD

**Issue by dherges** [Microsoft/TypeScript#10463]
```
$ tsc --version
Version 2.0.0
```

**Code**

see https://gist.github.com/dherges/701e5965dd5708529410ee47e4b0c798

```ts
/// <reference path="./halfred.d.ts" />

import halfred = require('halfred');
let resource = halfred.parse({foo: "bar"});
console.log(resource);
```

**Expected behavior:**

Compilation should be ok, runtime should be ok.

**Actual behavior:** 

Compilation throws error "TS2307: Cannot find module ". Then running the generated .js (on node) works as expected. Module is resolved (through ``require()``) and produces expected output.

Custom typings are in place. Visual Studio Code actually recognizes the typings. However, compilation fails.

Usage error? Is this a mis-understanding or a ``tsc`` bug?

**Comment by DanielRosenwasser** [comment]
You want to write `declare module "halfred"` (notice the quotes, which implies an import path).

**Comment by DanielRosenwasser** [comment]
As a heads up, I opened up this bug for you: #10464

The TL;DR is that
* TypeScript used to have "internal" and "external" modules.
* "external" modules are the same concept as what ES2015 introduced.
* "internal" modules became confusing, so we renamed them namespaces

This

```ts
declare module "foo" {
    // ...
}
```

declares a module that you can import as `"foo"`.

While these

```ts
declare namespace foo {
    // ...
}

declare module bar {
    // ...
}
```

create namespaces named `foo` and `bar` respectively. But we couldn't remove the `declare module bar` syntax because it was a breaking change, so now it just continues to confuse users.

**Comment by dherges** [comment]
Thanks a lot for your help! 👍

**Comment by DanielRosenwasser** [comment]
You're welcome!
