### ISSUE TITLE
Thin Arrow Functions

### ISSUE THREAD

**Issue by FriOne** [Microsoft/TypeScript#10520]
We have short form of `function` with context binding, but doesn't have without it.
```ts
// This is just the synonym of `function`.
() -> {

}
// Compiles to:
function () {

}
```
I guess the only reason, why we don't have this is because people want to be sure at first sight, that they have one context. But normally you dont't have many closure levels and actually in case of functions as arguments it is simplier to look at the end of line with `-> {` rather than search for the `function` word in a middle of a code.
```ts
let object;

object.set(() -> {
    object.set(() => {
        var blaBla: number = 100;
        let s: string = blaBlaaaaaaaaaaaaaaa.toString();
        object.set((someVariable: string) -> {
            var blaBlaaaaaaaaaaaaaaa: number = 100;
            let s: string = blaBla.toString();
            object.set(() => {

            });
        });
    });
});

object.set(function () {
    object.set(() => {
        var blaBla: number = 100;
        let s: string = blaBlaaaaaaaaaaaaaaa.toString();
        object.set(function (someVariable: string) {
            var blaBlaaaaaaaaaaaaaaa: number = 100;
            let s: string = blaBla.toString();
            object.set(() => {

            });
        });
    });
});
```

**Comment by mhegazy** [comment]
There is a previous discussion for https://github.com/Microsoft/TypeScript/issues/4551.

The ECMAScript committee discussed the proposal for thin arrow functions a while back while working on the ES6 spec, and decided to not do it. there are relevant discussions in https://esdiscuss.org/topic/arrow-function-syntax-simplified.

Since this is not likely to be included in a future ES standard, it does not make much sense to add it to the TS language. it also adds potential ambiguity with future uses of the `->` as an operator in ES in the future.

Personally, i do agree with the committee discussions that having two arrow syntax a la coffeescript is rather confusing. also the language has an existing construct (i.e. "function"), so do not see the need for a new syntax.
