### ISSUE TITLE
Test harness doesn't correctly exclude d.ts from an included tsconfig

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#10539]
**Code**

``` ts
// @module: commonjs
// @moduleResolution: node
// @allowJs: true
// @noEmit: true
// @traceResolution: true

// @filename: c:/root/tsconfig.json
{
    "compileOnSave": true,
    "compilerOptions": {
        "module": "commonjs",
        "moduleResolution": "node",
        "outDir": "bin"
    },
    "exclude": [ "bah" ]
}

// @filename: c:/root/node_modules/shortid/index.js
module.exports = { fromNodeModules: 'foo' };

// @filename: c:/root/bah/index.d.ts
declare module "shortid" {
    export var fromTypings: number;
}

// @filename: c:/root/index.ts
// no triple-slash reference means that index.d.ts is not used
import * as foo from "shortid";
foo.fromTypings     // ignored
foo.fromNodeModules // found
```

**Expected behavior:**

Error at `foo.fromTypings`

**Actual behavior:** 

Error at `foo.fromNodeModules`

**Comment by weswigham** [comment]
There's an `assert` in the runner reminding test authors that `include` and `files` in a `tsconfig` in a test are not respected (since a test program is not assembled via `tsconfig` today), however there's no check for just an `exclude` (and if you don't want all provided files included, you're meant to use `@noImplicitReferences`). Tis a simple addition to the existing assertion to make the limitation more obvious.
