### ISSUE TITLE
XOR in union allows both

### ISSUE THREAD

**Issue by jakobrosenberg** [Microsoft/TypeScript#10575]
**TypeScript Version:**  2.0.0

**Code**

```ts
interface Project { projectId: string }
interface Organization { organizationId: string }

type ProjectOrOrganization = Project | Organization

function findTask(query: ProjectOrOrganization) {
	// Tasks.find(query)
}

findTask({ projectId: 'foo' })
// should work

findTask({ organizationId: 'bar' })
// should work

findTask({ projectId: 'foo', organizationId: 'bar' })
// should not work, but does

findTask()
// should not work
```

**Expected behavior:**
``findTask({ projectId: 'foo', organizationId: 'bar' })`` should not work
Expected behavior based on a [post](http://stackoverflow.com/questions/37688318/typescript-interface-possible-to-make-one-or-the-other-properties-required#) by @RyanCavanaugh 

**Actual behavior:** 
``findTask({ projectId: 'foo', organizationId: 'bar' })`` works

@RyanCavanaugh wrote a reply [here](http://stackoverflow.com/questions/37688318/typescript-interface-possible-to-make-one-or-the-other-properties-required#) which implies that or-unions work as XOR.

**Comment by ahejlsberg** [comment]
A type T is assignable to a union type U if T is assignable to at least one of the constituents of U. In your example, the type `{ projectId: string, organizationId: string }` is assignable to *both* of the constituents and therefore assignable to the union type. Unions don't imply exclusivity among the types, but if you really want to ensure that a type *doesn't* have a specific member, you can define that member as an optional property of some marker type that never occurs in the wild:

```ts
interface Missing { __missing__: void }
interface Project { projectId: string, organizationId?: Missing }
interface Organization { organizationId: string, projectId?: Missing }
```

In 2.0 you could use type `undefined` instead of the marker type (before 2.0 it wasn't possible to explicitly reference the `undefined` type).
