### ISSUE TITLE
Doesn't compile when "outDir": "./"

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/TypeScript#10585]
**TypeScript Version: 2.0.0

**Code**
Have a follwing structure, need to get compiled (out) files in the root
```
/src
  index.ts
/tsconfig.json
```
tsconfig.json:
```json
{
  "compilerOptions": {
    "outDir": "./"
  }
```
run:
```bash
> tsc
```
or
```bash
> tsc --outDir .
```

**Expected behavior:**
compiled files in the root
**Actual behavior:** 
nothing is compiled

**Can be worked around**
Replace outDir with some other folder
```json
{
  "compilerOptions": {
    "outDir": "./lib"
  }
```
then use `--outDir .` in cli
```bash
> tsc --outDir .
```

**Comment by mhegazy** [comment]
oh... I see the issue now. it is not really a bug, it is just a result of applying a few rules. let me try to explain.

- if you do not specify an explicit list of `"files"`, or `"include"` then the compiler picks up all files in the folder
- if you do not specify an explicit list for `"exclude"`, one is inferred to be:  ["node_modules", <outDir>, "bower_components", "jspm_packages"]

in the example above, you do not have a  `"files"`, `"include"` or `"exclude"`. if the output folder is the same as the current folder, then all inputs will be excluded. 

as a fix, either make the outDir another folder, specify a list of  `"files"`, `"include"` or `"exclude"`

**Comment by whitecolor** [comment]
@mhegazy 
What if I need `outDir` to be exactly `./` (or `.`)? Why to have that I need to use `--outDir .` flag why it is not working via `tsconfig.json`?

**Comment by mhegazy** [comment]
that is the default. so do not specify `outDir` at all.

**Comment by whitecolor** [comment]
@mhegazy 
> that is the default. so do not specify outDir at all.

I thought the default would be to build `js` near corresponding `ts` file. What is mean by `./` is a cwd where tsc is run.

Again my case with some addition:
```
/src
  index.ts
/tsconfig.json
```
I I need to get compiled `index.js` in the root:
```
/src
  index.ts
/tsconfig.json
/index.js
```
tsconfig.json: 
```json
{
  "compilerOptions": {  
  },
  "include": ["src/*"]
}
```
If I run just `tsc` I will get `index.js` near `index.ts`:
```
/src
  index.js
  index.ts
/tsconfig.json
```
If I run just `tsc --outDir ./` I will get what I need (`index.js` will be in the root near config.json)

But if I add `outDir` to `tsconfig`
tsconfig.json: 
```json
{
  "compilerOptions": {  
    "outDir": "./"
  },
  "include": ["src/*"]
}
```
It just will compile nothing in any case.

**Comment by mhegazy** [comment]
I see.

**Comment by mhegazy** [comment]
So the issue here is that an **explicit** include of a subfolder does not override the **implicit** exclude of the outDir.

**Comment by riknoll** [comment]
I'm inclined to just make the `outDir` exclude work like the other default excludes ( `"node_modules", , "bower_components", "jspm_packages"`). If the user specifies an `"exclude"` array, `outDir` should not be excluded automatically. That might be a breaking change for some though, if they have already have `"exclude"` arrays without `outDir` included.

The other option of keeping the implicit exclusion and allowing `"include"` to explicitly override it is much more difficult given how we currently have the API set up. Excludes always override includes, so we would have to either change the host API to take in some second tier of implicit excludes or do something to the regex we generate. I have reservations about the regex approach, because it would probably involve a lot of lookahead and have an impact on performance.

The `"files"` array overrides `"exclude"`, so a workaround in the meantime is to use that for files in the `outDir`.

**Comment by mhegazy** [comment]
> I'm inclined to just make the outDir exclude work like the other default excludes

that is fine by me.

**Comment by whitecolor** [comment]
I checked with the latest `typescript@next` but my case works the same way (no emit if `"outDir": "./"` in tsconfig), how does it supposed to be working?

**Comment by mhegazy** [comment]
> I checked with the latest typescript@next but my case works the same way (no emit if "outDir": "./" in tsconfig), how is it supposed to be working?

did you specify an empty `"exclude" : []` array?

**Comment by whitecolor** [comment]
with `exclude []` it seem to work, thanks)
