### ISSUE TITLE
Not producing relative sourceMappingUrl's with mapRoot

### ISSUE THREAD

**Issue by agubler** [Microsoft/TypeScript#10612]
**TypeScript Version(s):** 2.1.0-dev.20160830 / 2.0.0 / 2.0.2

**Code**

``` json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": false,
        "mapRoot": "./_debug",
        "sourceMap": true
    }
}
```

``` ts
const example = function(options: { option1: string, options2: any }) {
        //noop
}

export default example;
```

Running `tsc -p .` 

**Expected behavior:**

``` js
"use strict";
var example = function (options) {
    //noop
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = example;
//# sourceMappingURL=_debug/main.js.map
```

**Actual behavior:** 

``` js
"use strict";
var example = function (options) {
    //noop
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = example;
//# sourceMappingURL=/Users/user1/ts-rel-root/_debug/main.js.map
```

**Comment by matt-gadd** [comment]
This seems to affect `sourceRoot` also unfortunately.

**Comment by saulshanabrook** [comment]
I would like to be able to use the `mapRoot` to change the `sources` field in the sourcemap, without making the `sourceMappingURL` absolute. This is an issue for us, because we build the typescript files in one place and then copy them to another before importing them. When we copy them, relative path in the `sources` field no longer correctly points to the source file. We can mitigate this by using the `mapRoot`, but then this changes the `sourceMappingURL` to be absolute, and points to the previous location, so then it is not picked up.

**Comment by mhegazy** [comment]
Should be fixed by https://github.com/Microsoft/TypeScript/pull/23989
