### ISSUE TITLE
Unexpected type reference between divided modules

### ISSUE THREAD

**Issue by vvakame** [Microsoft/TypeScript#10625]
**TypeScript Version:**  2.0.2

**Code**

sampleA.ts
```ts
{
    // local types
    type Data = string | boolean;
    let obj: Data = true;
    console.log(obj);
}
export { }
```

sampleB.ts
```
let v = "str" || true;

export { v }
```

tsconfig.json
```
{
    "compilerOptions": {
        "declaration": true,
        "skipDefaultLibCheck": true
    },
    "include": [
        "sample*.ts"
    ]
}
```
This is minimal settings.
When `"declaration": true` and `"skipDefaultLibCheck": true`, this issue is occured.

**Expected behavior:**

We can compile this code.

**Actual behavior:** 

```
$ tsc -v
Version 2.0.2
$ tsc -p ./
sampleB.ts(1,5): error TS4023: Exported variable 'v' has or is using name 'Data' from external module "/private/tmp/hogehogehoge/sampleA" but cannot be named.
```

**Comment by vladima** [comment]
at glance root cause of the issue is caching of union types: type of `Data` in `sampleA.ts` is `string | boolean` and it is the same with type of `v` in `sampleB.ts`. However type in the first case has associated alias which is not visible if the same type is reused in different context. 

Why error does not repro without `skipDefaultLibCheck` - I guess some declaration in `lib.d.ts` has the same type. This type will be put in the cache and used for both `sampleA.ts` and `sampleB.ts` will 

// CC @ahejlsberg
