### ISSUE TITLE
Comparability of Enum values

### ISSUE THREAD

**Issue by m1gu3l** [Microsoft/TypeScript#10631]
**TypeScript Version:**  2.0.2 Release Candidate

**Code**
```ts
enum Place {
	Bottom,
	Left,
	Right,
	Top
}

let p: Place = Place.Left;
console.log(p === Place.Left);
console.log(p === Place.Right);
```

**Expected behavior:**
true
false

**Actual behavior:** 
 error TS2365: Operator '===' cannot be applied to types 'Place.Left' and 'Place.Right'.

**Comment by m1gu3l** [comment]
#10119 and #10120 might be related

**Comment by ahejlsberg** [comment]
This is working as intended. The compiler performs control flow analysis and knows that `p` has the actual value `Place.Left` where you're performing the `===` operations, and it is calling out that it makes no sense to compare a value that is known to be `Place.Left` to a value that is known to be `Place.Right`. It's effectively like writing `Place.Left === Place.Right` or `1 === 2`, both of which would also produce errors.

**Comment by m1gu3l** [comment]
Oh, thanks for clarifying that. It still feels a bit weird.

>  It's effectively like writing Place.Left === Place.Right or 1 === 2, both of which would also produce errors.

Well no, it's like writing `let p = 0` and then checking `p === 1`, which would produce _false_.

**Comment by ahejlsberg** [comment]
The thing that triggers the stricter behavior is that the variable is constrained to a finite set of choices through a type annotation (i.e. a type annotation of a union type or an enum type). For example, the following is also an error

```ts
let p: 0 | 1 = 0;
console.log(p === 1);  // Error, comparing 0 to 1
```

**Comment by m1gu3l** [comment]
I understand. 
It seems to be an overkill though. Sometimes developer might want to do check like that. And what about generated code?

**Comment by RyanCavanaugh** [comment]
You can write `let p: Place = <Place>Place.Left;` if you want to "erase" the known value of the variable.

In reality this check actually found a lot of bugs when it was created. People would check for an enum value and `return`, then check for it *again* (creating an unreachable block), etc.

Generated code should *never* be in a bad state due to this since the generator itself can know when it would emit unreachable blocks. And usually you wouldn't typecheck generated code anyway (since it ought to be correct).

**Comment by m1gu3l** [comment]
In ideal world there would be a flag to disable this globally, but I've noted my position is in the minority.
