### ISSUE TITLE
Implicit Referencing - opting in and opting out

### ISSUE THREAD

**Issue by johnnyreilly** [microsoft/TypeScript#1066]
Hi,

I've a question about Visual Studio's Implicit Referencing.  I've looked around in vain for a definitive answer and so I thought it might make sense to raise the question here.

> Previously, all TypeScript files in a project had to reference each other explicitly. With 0.9.1, they now implicitly reference all other TypeScript files in the project.

Since 0.9.1 I've used this feature pretty happily and purged my files of the mass of `/// <reference path=` entries.  

I've recently been wondering if there are any hidden "gotchas" to using `/// <reference path=` in a Visual Studio context?  My understanding is that if there are any `/// <reference path=` instances in a file then implicit referencing goes out the window and only the specified references are used.  Is that correct?  (So use of _**any**_ references in the head of a `ts` file is effectively the same as opting that file out of Implicit Referencing for Visual Studio.)

@mhegazy - this might be a question for you? Similar ground was covered [here](https://github.com/Microsoft/TypeScript/issues/673).

**Comment by Gitgiddy** [comment]
A good counter example is GitHub-Electon or similar background-worker script/dom-script situations where definintions might only be available in certain contexts.  For Electron, there are two modules called 'ipc' that are loaded in different contexts only ("renderer" vs "main" contexts).  With Typescript automatically including ALL available files in the project, I cannot be selective about which d.ts contexts to include for a particular script.  Instead I have to split it into multiple projects - maybe not a bad thing, I'm not sure.  (also, the 'ipc' conflict doesn't appear in the GitHub-Electon*.d.ts files in their current release, but would once those definitions mature)

**Comment by mhegazy** [comment]
@Gitgiddy tsconfig.json (with full support in next VS2015 public release) should solve this issue for you.

**Comment by agoodwin** [comment]
> **Problem:** The compiler will generate outputs in the order of occurrence in the dependency graph. The dependency graph is built using the logic stated earlier. In the batch compiler case, you can change your order on the command line, but in VS, manually editing the project file to enforce order is neither convenient nor productive.
> **Solution:** There is support to a special file "_references.ts" at the root of your project (has to be at the root, if anywhere else it will be treated like a normal file). If this file exists, the file is guaranteed to be passed as the first file in the list, both in VS and in the MSBuild task. that allows you to specify order through adding /// references in _references.ts. Remember that the graph is built in order, and following /// references in order, so the order of /// references in _references.ts will dictate the order of files in the output, in absence of any circular references.

@mhegazy I've just come across this problem, and after finding multiple issues on the subject this seems to be the most appropriate place to get some clarification.

First let me explain my situation a bit:

I've got a Visual Studio project, with its TypeScript properties set to combine the compiled TypeScript into a single .js file, and among many other .ts files it has a base class in one .ts file and a child class in another .ts file. Until I added the base class I had assumed that I didn't need to use /// references at all while using a Visual Studio project, because I thought Visual Studio was figuring out TypeScript dependencies on its own. After reading this issue I now realise that it's not, and in my case my output .js file has the base class declared after the child class, resulting in the "TypeError: b is undefined in __extends" error (#4341).

So, based on your responses to this and other issues, it sounds like I should use a _references.ts file or just use /// reference directives in my source files.

The problem I have with these options is that they're manual processes, but the overall issue seems to be something that could have an automated solution. For example, when you described this process (regarding how files are passed to the TypeScript compiler by Visual Studio):

> **2. Visual Studio, with a project referencing the file**
> 
>   - **Start with all files in the project with build action === "TypeScriptCompile", in order of reference in the project file**
>   - For each file, examine its /// references and import = require() statements
>     -     If the file has not been seen before add it to the list, and recursively examine its references

Wouldn't it be possible for an extra step to be added here so that, instead of initially ordering the files based on their order within the project file, the initial ordering of the files is based on their dependencies?

I mean, doesn't Visual Studio already have this information at hand? (I assume this because IntelliSense and Go To Definition work in TypeScript, so it must surely be quite easy to figure out that a file containing a base class needs to be compiled before files containing child classes).

Having said that though, I realise that in reality there's probably a huge amount of work involved in implementing this dependency checking and ordering functionality – and if it were to be implemented it would probably belong in the TypeScript compiler itself, not in Visual Studio.

So I guess my only real point of confusion is, why does Visual Studio do anything around a "compilation context" at all? I guess I'm with @johnnyreilly when he says:

> For that reason I thought it might be simpler to abandon the project file approach entirely. That way the only maintenance is just the /// references and all developers (regardless of IDE) should need to do the same maintenance to keep the code compiling. No danger that a Visual Studio user might add a file to the project but forget to add the appropriate /// reference if you see what I mean.

The current behaviour just seems a bit misleading to me. The way that Visual Studio figures out the TypeScript references without explicitly having any /// directives, and then enables IntelliSense etc, makes it appear as though your code will run when it won't necessarily. This mainly seems to be an issue around inheritance, because of how `extends` compiles to JavaScript that is run at the point in time when a child class is declared. I'm not aware of many other situations where you get this out-of-order compilation happening.

I realise this whole comment probably seems a bit aimless, so I guess my actual point can be boiled down to this:

If you are working in a project within Visual Studio, and:
- You are compiling your TypeScript files into a single JavaScript file
- You are making use of inheritance

Then there is a high likelihood that you will still need to use /// reference directives or a _references.ts file in order to have your output JavaScript run without errors. With that being the case, wouldn't it be better to **require** developers to use /// reference directives within Visual Studio (like they have to when using other IDEs) rather than giving the appearance of handling this automatically? I realise I'm simply repeating @johnnyreilly's point, and like him I understand that it might seem like a small thing to be fussing about, but I do think it's misleading the way things are.

**Comment by mhegazy** [comment]
It is a design choice not to reorder output. the compiler will generate code that looks like your input. The compiler can not generate code that will always work in all cases, e.g. if you have a cyclic dependency between files.

The solution we believe is correct is to issue an error when you have your base before your derived, see https://github.com/Microsoft/TypeScript/issues/5207, the PR for it is in, https://github.com/Microsoft/TypeScript/pull/4343, we need to update the PR though.

**Comment by agoodwin** [comment]
Thanks for the quick reply,

I don't want to keep bothering you about this for too long, but if it's a design choice to not reorder the output, what was behind the design choice to have all of a project's .ts files automatically passed to the TypeScript compiler (in project reference order) in the first place?

Would I be right in saying that this was because there used to be no support for a tsconfig.json file (before TypeScript 1.5)? So it was the only way to have Visual Studio compile TypeScript files in a project automatically? I guess the alternative would have been for the user to add a pre or post build step to run tsc.exe, which wouldn't have been very nice.

If that's the case, will things be moving more towards tsconfig.json in the future (even when using a project file)? I've been reading through #3983 and its related issues. It kind of sounds to me like the TypeScript properties in a *proj file are on their way out, and instead we will always be using tsconfig.json in future. This is certainly already the case for ASP.NET 5 projects, so is this the intent for other kinds of projects as well?

**Comment by mhegazy** [comment]
>  what was behind the design choice to have all of a project's .ts files automatically passed to the TypeScript compiler (in project reference order) in the first place?

Well. the ts files need to be compiled to js files to be able to run, we would assume you want to compile all the files in your project, so we pass them all to the compiler. this is the same behavior as C#, VB, etc..
Now, for the order, it is the order that MSBuild decides when we ask for `TypeScriptCompile` items in the file. no special sorting or ordering is going on.

> If that's the case, will things be moving more towards tsconfig.json in the future (even when using a project file)?

yes. this is the intention. tsconfig.json has been easier for developers to reason about than the xml project file, and fits with other JS tooling patterns.

> This is certainly already the case for ASP.NET 5 projects, so is this the intent for other kinds of projects as well?

Starting with TS 1.8, if you have a tsconfig.json in your project file it will be used as the source of configurations for *all* project types. see https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#improved-support-for-tsconfigjson-in-visual-studio-2015

**Comment by johnnyreilly** [comment]
I can confirm that `tsconfig.json` rocks and will improve your life by at least 23%. It's that good. :smile:

**Comment by agoodwin** [comment]
Excellent, thanks for clearing that up. I didn't realise that tsconfig.json was already supported for all project types - I should have just tried it.

I'm already using TypeScript 1.8, so I'll switch to using tsconfig.json right away. Thanks for your help.

**Comment by whitecolor** [comment]
@mhegazy 
Could you please elaborate what is current (or upcoming due to TS 2.0) state of need of triple slash reference API for types dependency management? When/where it still should be used and should be be avoided if possible?
