### ISSUE TITLE
duplicate identifier when using @types

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/TypeScript#10664]
**TypeScript Version:**  2.0.2

**Code**

```ts
// index.ts
// empty
```

```json
// package.json
{
  "name": "test",
  "version": "1.0.0",
  "scripts": {
    "build": "tsc index.ts --outFile build.js"
  },
  "dependencies": {
    "@types/fs-extra-promise": "0.0.28",
    "@types/karma": "^0.13.32",
    "typescript": "^2.0.2"
  }
}
```

```json
// tsconfig.json
{
  "compilerOptions": {
    "target": "es6",
    "moduleResolution": "node"
  },
  "exclude": [
    "node_modules"
  ]
}
```

- `$ npm -v` // 3.10.6
- `$ npm i`
- `$ npm run build`

**Expected behavior:**

Based on [this tweet](https://twitter.com/drosenwasser/status/770308562463580160) I think no error should happen.

If I understand this tweet wrong, I still think no error should happen, because it should be fine for Karma and fs-extra-promise to use different versions of bluebird. If this works with Node, it should work with TypeScript, too.

**Actual behavior:** 

Errors:
```
node_modules/@types/bluebird/index.d.ts(772,5): error TS2300: Duplicate identifier 'export='.
node_modules/@types/karma/node_modules/@types/bluebird/index.d.ts(772,1): error TS2300: Duplicate identifier 'export='.
```

**Comment by mhegazy** [comment]
@andy-ms we talked about this before. We need to make all package dependencies `latest` unless specified explicitly in package.json.

**Comment by donaldpipowitch** [comment]
If karma and fs-extra-promise would specify different versions (of what? bluebird or @types/bluebird?) what would happen? Would `duplicate identifier` be thrown? If yes, why? It should be fine for Node to use different versions, right?

**Comment by mhegazy** [comment]
two issues:
- different versions of bluebird, `@types/fs-extra-promise` needs `2.0.*`, while `@types/karma` needs `3.0.*`.
- definition of bluebird is written as global declarations and not modules. The compiler has no way to resolve conflicts of a global symbol. if you say i expect a module to always declare `$` in the global scope, so importing two or more versions would stomp on one another. so all have to be the same version. the issue here is not that bluebird is global, but that the declaration file is written this way. so the fix should be on the bluebird.d.ts side.

The fix in https://github.com/Microsoft/types-publisher/pull/134 is to make all packages depend on latest bluebird, and thus avoiding the conflict.

**Comment by donaldpipowitch** [comment]
Okay, so the main problem is that the .d.ts for bluebird v2 is written in a wrong style. Thanks.

**Comment by geoffreak** [comment]
I had this same issue and ended up switching to `fs-extra-promise-es6`. The typings from `@types/fs-extra-promise` can be used after removing the Bluebird import line.
