### ISSUE TITLE
Regressions of lib.d.ts

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#10695]
Must fix regressions such as #6500. We need to get other regressions investigated. #6500 is regressed now.

**Comment by kitsonk** [comment]
I suspect that some manual adjustments to the `lib.d.ts` were overwritten when migrating to/refreshing the ChakraCore interfaces, because for some reason [`.clear()`](https://github.com/Microsoft/ChakraCore/blob/1f1164cd1bd38f91c2c42b1d10e16f8b9aa6a5b4/lib/Runtime/Library/JavascriptWeakMap.h#L66) is still there.

I raised an issue in Microsoft/ChakraCore#1539 to question why it was still in there.

**Comment by kitsonk** [comment]
It was stated that in the referenced ticket that `.clear()` is not exposed into the runtime, so I am not sure how the TSJS-lib-generator is picking it up (see: Microsoft/TSJS-lib-generator#145)

**Comment by falsandtru** [comment]
It is certainly suspicious. Thanks for letting me know.

@zhengbli @DanielRosenwasser @mhegazy can you fix these regressions?

**Comment by mhegazy** [comment]
A PR would be appreciated.
