### ISSUE TITLE
Emitting default imports for commonjs.

### ISSUE THREAD

**Issue by tomitrescak** [Microsoft/TypeScript#10806]
This is just a suggestion.
Currently default imports from commonjs are handled as following:

```js
import * as X from 'module';
```

This brings issues when package exports a default constructor or class when you have to write this monstrosity in order to use it:

```js
import A = require('module');
```

Why not emit default imports when targeting commonjs modules as following?

If I write:

```js
import A from 'module'
```

emit to 

```js
const A = require('module').default || require('module');
```

Solves myriads of issues. What do you think?

**Comment by kitsonk** [comment]
Changing the emit behaviour would be a breaking change right?

How do you see this interacting with `--allowSyntheticDefaultImports`?

**Comment by tomitrescak** [comment]
In my opinion it would not break anything.
I'm not sure what do you mean with interaction wiht "allowSyntheticDefaultImports". How does it relate?

**Comment by RyanCavanaugh** [comment]
>     ` import * as X from 'module'; ` 
This brings issues when package exports a default constructor or class when you have to write this monstrosity in order to use it:

You'll have to take this to the ECMAScript committee, unfortunately. This has a very specific meaning and this meaning excludes the possibility of importing classes / functions into `X`.

The proposed emit is different from the ES6 behavior in about six different ways, none of which we could reasonably claim to be an allowable divergence for the sake of convenience / interoperability.

**Comment by RyanCavanaugh** [comment]
For future finders: http://stackoverflow.com/questions/39415661/why-cant-i-import-a-class-or-function-with-import-as-x-from-y
