### ISSUE TITLE
Simultaneous use of export equals and export default in a module

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#10854]
I have some NPM modules written that uses the old default export syntax:
```ts
declare module 'my-module' {
    function test(): string;
    export = test;
}
```
To promote ES import syntax but still keep the old one, I wanted to add both the new and old default export syntax:
```ts
declare module 'my-module' {
    function test(): string;
    export default test;
    export = test; // An export assignment cannot be used in a module with other exported element
}
```
Though it complains that it cannot use an export assignment with other export statements.

I think it is reasonable to support both syntax simultaneously in a module. Because choosing between both syntax. I would choose `export =` before `export default`, simply because of no API breakage.

**Comment by kitsonk** [comment]
No it isn't really practical at all, because it isn't "magic" that produces the default export.  It is added as a property on the export of the module.  What is provided above is trying to export something as `my-module.default` and then overwriting it with a function named `test` and TypeScript is preventing you from describing something that contradicts itself.

I think what you might want to consider the solution to #5285 (`--allowSyntheticDefaultImports`), which allows you to import a module as if it were the shape you denoted.

**Comment by tinganho** [comment]
>I think what you might want to consider the solution to #5285 (--allowSyntheticDefaultImports), which allows you to import a module as if it were the shape you denoted.

@kitsonk thanks that was what I wanted.

**Comment by tinganho** [comment]
There could be a problem. I'm currently doing the magic on the module itself and not relying on any module loader doing the magic for me. There could possibly be people that are not using `--allowSyntheticDefaultImports` so they cannot use one of my modules, unless they want to use the old import syntax. Telling all users that they need to add a flag just to use a module is little bit harsh also.

FYI. This is the magic I do:
```ts
declare var module: any;
module.exports = create();
module.exports.default = create();
```

**Comment by kitsonk** [comment]
```typescript
declare module 'my-module' {
    const test: () => string & { default: () => string };
    export = test;
}
```

**Comment by tinganho** [comment]
Very neat trick!
