### ISSUE TITLE
Using "instanceOf" seems to change the type of something to "never"

### ISSUE THREAD

**Issue by dzearing** [Microsoft/TypeScript#10966]
**TypeScript Version:**  2.0.2

**Code**

This works:
```ts
let foo: boolean[] = [];
return !!(foo.splice);
```

The following fails on referring to "splice" because after the instanceof evaluation, the "foo" object changes from type `boolean[]` to type `never`, which doesn't have splice defined:

```ts
let foo: boolean[] = [];
return (foo instanceof Array) || !!(foo.splice);
```

Strangely, if I change the condition to AND instead of OR, we don't have any issues:

```ts
let foo: boolean[] = [];
return (foo instanceof Array) && !!(foo.splice);
```

Or, if I change the order of evaluation, that works as well:

```ts
let foo: boolean[] = [];
return !!(foo.splice) || (foo instanceof Array);
```

Note, this isn't something specific to arrays. You can change the `boolean[]` to `HTMLElement`, same sort of problem.

**Expected behavior:**
No errors in this case.

**Actual behavior:** 
Property 'splice' does not exist on type 'never'.

**Comment by dzearing** [comment]
This seems very related to https://github.com/Microsoft/TypeScript/issues/10934

However I'm not sure completely. This seems very buggy and unexpected because I do not expect `foo` to change typings after a comparison. Code that was previously compiling fine is no longer compiling.

**Comment by ahejlsberg** [comment]
@dzearing This is effectively the type checker telling you that the particular expression will never execute.

```ts
let foo: boolean[] = [];
return (foo instanceof Array) || !!(foo.splice);
```

In the `foo instanceof Array` check, the type checker narrows the type of `foo` to only the subset that are arrays. That turns out to be all possible values of `foo`, so `foo` has type `boolean[]` in the true branch. But in the false branch the type checker narrows to the subset that *aren't* arrays. That turns out to be nothing, so `foo` has type `never` in the false branch.

**Comment by dzearing** [comment]
Oh man, awesome! I see it now! It really is "never". :) Thanks Anders.
