### ISSUE TITLE
[Bug] Block Scoped variables not renamed when concating to file

### ISSUE THREAD

**Issue by subhaze** [Microsoft/TypeScript#11018]
**TypeScript Version:**  1.8.10 and 2.1.0-dev.20160920

**Code**

```ts
// one.js
{
	let one = 1;
	let two = 2;
}

{
	let one = 1;
	let two = 2;
}
```

```ts
// two.js
{
	let one = 1;
	let two = 2;
}

{
	let one = 1;
	let two = 2;
}
```

`tsc --allowJs one.js two.js --outFile out.js --target es5`

**Expected behavior:**
```ts
// out.js
{
    var one_1 = 1;
    var two_1 = 2;
}
{
    var one_2 = 1;
    var two_2 = 2;
}
{
    var one_3 = 1;
    var two_3 = 2;
}
{
    var one_4 = 1;
    var two_4 = 2;
}
```
**Actual behavior:** 
```ts
// out.js
{
    var one = 1;
    var two = 2;
}
{
    var one = 1;
    var two = 2;
}
{
    var one = 1;
    var two = 2;
}
{
    var one = 1;
    var two = 2;
}
```

**Comment by subhaze** [comment]
This does work, however, if you do something like:
```ts
// two.js
{
    let one = 1;
    let two = 2;
}

{
    let one = 1;
    let two = 2;
}
let one = 1;
let two = 2;
```

**Comment by subhaze** [comment]
So... Official response from Babel.

> Using the CLI's concat logic is not a good idea, I honestly don't know why we even support it. We're unlikely to fix this, you'd be much better off using a module bundler to give each file a wrapper function.

**Comment by mhegazy** [comment]
creating a temporary name should check all files for the new name being in use. this is not a simple fix. I do agree that the utility of fixing it is not worth the effort.

**Comment by subhaze** [comment]
Commented above on wrong ticket so deleted :) #toomanytabs

**Comment by vladima** [comment]
I don't think this is bug: we try not to aggressively rename variables to preserve nice debugging experience.
Basically the set of rules that we use is following:

If we can detect that block scoped variable has the same name as another variable in enclosing scope we'll rename it
```ts
// TypeScript
let x = 1;
{
    let x = "123";
}
```
```js
// JavaScript
var x = 1;
{
    var x_1 = "123";
}

```
In all other cases when we don't know for sure if these is a conflicting name in the enclosing scope we might choose one of three options: 
- If block scoped variable in nested scope and has initializer we don't rename it because initializer will overwrite old value so the fact that `let` was transformed into the `var` and thus hoisted should be non-observable:

```ts
// TypeScript
{
    let x = 1
}
{
    let x = 1;
}
```
```js
// JavaScript
{
    var x = 1;
}
{
    var x = 1;
}
``` 

- If block scoped variable in nested scope does not have initializer we'll zero initialize it to wipe out old value
```ts
// TypeScript
{
    let x = 1;
}
{
    let x;
}
```
```js
/// JavaScript
{
    var x = 1;
}
{
    var x = void 0;
}
``` 
- if block scoped variable in nested scope is captured in closure - we'll always rename it
```ts
// TypeScript
{
    let x = 1;
    () => x;
}
// or
{
    let y;
    ({ f() { return y} })
}

```
```js
/// JavaScript
{
    var x_1 = 1;
    (function () { return x_1; });
}
// or
{
    var y_1;
    ({ f: function () { return y_1; } });
}

```

**Comment by mhegazy** [comment]
Thanks @vladima. Closing.

**Comment by subhaze** [comment]
@vladima thanks for breaking it down. Makes a bit more sense now, in my head I was just seeing this as "wrong" but after reading through your comment and experimenting with doing more than just initializing variables it appears things are usually renamed when they should be.
