### ISSUE TITLE
Doesn't work type checking for function arguments

### ISSUE THREAD

**Issue by iKBAHT** [Microsoft/TypeScript#11058]
**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)

**Code**

```ts
function fn(options: { a?: number, b?: boolean }) {
	return options.a || 1; 	
}

fn('foo');
```

**Expected behavior:**
Must be an error in
```ts
fn('foo');
```
**Actual behavior:** 
No errors, TS compiler say "OK".

**Comment by nippur72** [comment]
I guess what's happening here: since `a` and `b` are optional, the resulting type is similar to `{}`. Now `{}` in TypeScript is a type with no members whatsoever, so anything will cast to it. 

Indeed it's possible to write:
```ts
'foo' as {}; // ok
```

**Comment by yortus** [comment]
As @nippur72 points out, this is a consequence of [function argument bivariance](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant).

In this case, the type `string` satisfies the requirements of `{a?: number, b?: boolean}`, since no particular properties are required to do so. Thus due to bivariance, it's valid to pass a string as the `options` argument.

There are issues out there where this is being discussed, such as #1394 and #10717.

**Comment by mhegazy** [comment]
An interface with all optional arguments is just like one that is empty. an empty interface matches anything, including strings. see https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-all-types-assignable-to-empty-interfaces for details.

**Comment by holiber** [comment]
It is not intuitive behavior. Flowjs works as expected https://flowtype.org/try/#0GYVwdgxgLglg9mABMMAKOAHWCDOAuRAb0QEMB+AsEAWwCMBTAJwBpFaK244AbekpAL4BKIgChG9KCEZJM2MDgB0JRAB9ViAIwBuRKIGjRKVAHJgXE0O1A

**Comment by Igorbek** [comment]
@mhegazy you right, however at the same time TS disallows "extra" properties:
```ts
function fn(options: { a?: number, b?: boolean }) {
    return options.a || 1;  
}

fn('foo'); // ok
fn({ c: 1; }); // error even though { c: number; } is assignable to { a?: number; b?: boolean; }
```

the reason you do this is to catch common errors, right? so must be done here.
