### ISSUE TITLE
JSDoc removed from '.d.ts' when removeComments: true

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/TypeScript#11129]
**TypeScript Version:**  2.0.3

**.vscode/settings.json**

``` json
{
    "typescript.tsdk": "./node_modules/typescript/lib"
}
```

**./tsconfig.json**

``` json
{
    "compilerOptions": {
        "target": "es6",
        "module": "system",
        "removeComments": true,
        "out": "./root/dist/javascript.js",
        "watch": true,
        "declaration": true
    }
}
```

**Expected behavior:**

When `declaration: true` and `removeComments: true`, I would expect comments to be removed from the javascript file(s), and leave the JSDoc in the `.d.ts` file(s).

**Actual behavior:** 

All comments are removed from all files.

When `declaration: true` and `removeComments: false` comments don't get removed from the javascript file(s) but they do get removed from the `.d.ts` file(s) unless it is JSDoc.

**Comment by nickpape-msft** [comment]
@mhegazy we (SPFx) would definitely like to have this feature. Our issue is that we want the comments to appear in .d.ts files (presumably JSDoc), but for no comments to appear in compiled JS file. However, if we remove the comments _after_ compilation using something like [decomment](https://github.com/vitaly-t/decomment), they still exist in our sourcemaps.

Ideally, `removeComments: true` would leave JSDoc style comments in the output of .d.ts files in order to get intellisense, but would remove them from the JS/Sourcemaps.

**Comment by mhegazy** [comment]
looks like the same issue as https://github.com/Microsoft/TypeScript/issues/11774
