### ISSUE TITLE
Logical operator type omits types of LHS, despite short-circuit evaluation

### ISSUE THREAD

**Issue by cspotcode** [Microsoft/TypeScript#11127]
**TypeScript Version:**  2.0.3 and nightly (2.1.0-dev.20160924)

**Code**

```ts
let a: boolean;
let b: string;
let c = a && b;
```

**Expected behavior:**
Type of `c` is inferred to be `boolean | string`.

**Actual behavior:** 
Type of `c` is inferred to be `string`.

In general, for `&&` I would expect that `c` has a union type including any possible types of `a` that can be falsey.  For `||` I would expect `c` to have a union type including any possible types of `a` that can be truthy.

```ts
// strictNullChecks is on
let a: boolean | null | undefined | string;
let b: number;
let c = a && b; // c: boolean | null | undefined | string | number;
let d = a || b; // d: boolean | string | number;
```

Apologies if I mixed up any of the type theory vocabulary.

**Comment by ahejlsberg** [comment]
We produce the expected result in `--strictNullChecks` mode. However, for reasons of backward compatibility, in classic type checking mode we simply return the type of the right hand operand (even through the type should technically include the falsy possibilities of the left hand operand). It's been that way since 0.8 and there's a fair amount code code out there that would break if we tighten the rules.

**Comment by cspotcode** [comment]
Oops, I see that now.  I didn't know it was a backwards-compatibility thing.  Thanks!
