### ISSUE TITLE
Updating compiler options for Visual Studio

### ISSUE THREAD

**Issue by HolgerJeromin** [Microsoft/TypeScript#11148]
Is there a policy what option gets an option in VisualStudio 2015 Plugin? 
Right now there is only `--noImplicitAny`.

![image](https://cloud.githubusercontent.com/assets/2410353/18840749/ec28cb08-840f-11e6-8143-6a3f210ea880.png)

The really nice new stuff can only be activated by 

1. "closing project", 
2. "edit project.csproj", 
3. crafting some xml stuff in a text editor where even `<TypeScriptToolsVersion>` gets a Schema warning, 
4. reopening the project, 
5. rebuild. 

If the legacy code does not work with the new stuff i have to do the same again.

**Comment by cwebster2** [comment]
If you have a tsconfig.json file in your project, that will be used instead of the "Typescript build" option pane in the project properties.  Not quite what you want, but editing that file is a lot easier then editing the csproj file.

**Comment by mhegazy** [comment]
It is not possible to include all options in the UI. So we have picked the most used ones and included them. There are no plans to add more to the UI. My recommendation would be to use `tsconfig.json` file instead.

**Comment by HolgerJeromin** [comment]
Thanks for your quick answer!

While tslint.json is very nice i cannot set different options with different build configurations.
We had generation of sourcemaps only in debug and not in the release build on our build server.

Is there a better option than manipulating the JSON with a grunt prebuild task?

**Comment by mhegazy** [comment]
Almost all options are available as MSBuild properties (see http://www.typescriptlang.org/docs/handbook/compiler-options-in-msbuild.html). I do not think we will be showing them all in the UI. so your options are use the project file to update these manually, or to use a tsconfig.json.

Also please note, that you can have multiple tsconfig.json files, each with different configuration. you will need to author an invocation to tsc with `--p <path to tsconfig.json>` in your MSBuild project instead of relying on the default behavior.
