### ISSUE TITLE
Intellisense is not able to infer types for function parameters

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#11155]
_From @LasTshaMAN on September 24, 2016 22:53_
- VSCode Version: 1.5.3
- OS Version: Windows 8.1 x64

Steps to Reproduce:
1. When I register a request handler with express (without specifying the types of handler function parameters), VS Code can't get me Intellisense to work with these parameters.
   Take a look at the screenshot:

![image](https://cloud.githubusercontent.com/assets/7031569/18811724/01924108-82c2-11e6-8850-c4bef79bebe2.png)

Once you add types for "req" and "res" parameters explicitly Intellisense works just fine.

Here is [Github link](https://github.com/LasTshaMAN/PoC/blob/master/src/RestServer.ts) for my project, if you want to reproduce this behavior fast.

By the way, enjoying working with VS Code, you did a great job, guys!

_Copied from original issue: Microsoft/vscode#12565_

**Comment by waderyan** [comment]
@LasTshaMAN thank you for opening this issue and for sharing your code. I have reproduced this issue with the latest VS Code version and the TS 2.0.5. 

Because this functionality is provided by TypeScript language service I am migrating the issue to their repository.

**Comment by mhegazy** [comment]
@LasTshaMAN what makes you believe this is a compiler or tools bugs rather than an issue with the express declaration file?

**Comment by LasTshaMAN** [comment]
@mhegazy, I believe this is the issue with VS Code and not with the compiler or the express file declaration, because I get reasonable hints in Webstorm IDE as shown at the screen below:

![image](https://cloud.githubusercontent.com/assets/7031569/18894280/b5dc9e92-851a-11e6-8e17-067f0ecbf7ec.png)

I guess I should have attached such a screen to my original post.

**Comment by mhegazy** [comment]
WebStorm uses a different implementation to get you hints. i really have no insight into what they do. VSCode uses the ts compiler and services. if VSCode things this `req` is `any`, then this is what the TS compiler thinks of it.

now the type of `req` is a contextual type comming from express. so looks like express declaration file needs updates.

**Comment by LasTshaMAN** [comment]
Here are express type definitions as downloaded by typings tool.
[download link](http://www.filehosting.org/file/details/604912/express.zip) - sorry, but I didn't manage to upload .zip right in the comment for some reason.

I believe that express type definitions file is Ok, I can trace my "req" and "res" params to the definition of RequestHandler:

![image](https://cloud.githubusercontent.com/assets/7031569/18894999/ff8019f8-851e-11e6-86eb-4933f905b157.png)

Although, I'm quite new to Typescript and don't quite get why I'm able to leave out non-optional "next" parameter here.

**Comment by LasTshaMAN** [comment]
Although such a type inference (we are talking about here) works in case of another library in VS Code, say "request" library. By the way, the situation described above is reproducible even on the latest version of "express" typescript.

![image](https://cloud.githubusercontent.com/assets/7031569/18906987/7c98c2b6-8572-11e6-86f5-b21b824614a1.png)

Which leads me to think that the problem is either with typescript definition file or it is with the tooling VS Code uses to infer types (may be it is not powerful enough to trace 3-4 references).

**Comment by mhegazy** [comment]
this looks to be the same underlying issue as in https://github.com/Microsoft/TypeScript/issues/11875. the overload resolution algorithm does not really support overload on arity, which seems to be what express is using here.
