### ISSUE TITLE
Import namespace object fails typechecking

### ISSUE THREAD

**Issue by Ignasimg** [Microsoft/TypeScript#11174]
**TypeScript Version:**  Version 2.0.3

**Code**

ns.ts
```ts
var ns = ns || {};
export = ns;
```

class_1.ts
```ts
import ns = require("ns");
class class_1 {
  constructor() { ... }
}
ns.class_1 = class_1;
export = class_1;
```

class_2.ts
```ts
import ns = require("ns");
import class_1 = require("class_1");
class class_2 {
  private c_1:class_1; // Fine
  private c_2:ns.class_1; // NOT fine
  constructor () {
    this.c_1 = new class_1(); // Fine
    this.c_2 = new ns.class_1(); // Fine
  }
}
```

**Expected behavior:**
The behaviour I'd expect is for it to compile just fine.

**Actual behavior:** 
The compiler complains with:

> class_2.ts(5,15): error TS2503: Cannot find namespace 'ns'.

**Comment by aluanhaddad** [comment]
That syntax only binds `ns.class_1` to the value `class_1` not the type `class_1`, so it is not available in type position. Why not use declarative namespace syntax though?

**Comment by Ignasimg** [comment]
Thank you for your quick answer, however I'm unable to guess what do you mean by declarative namespace syntax. Could you expand your explanation maybe with a sample?

Thank you.

**Comment by RyanCavanaugh** [comment]
This isn't a bug because there's nothing creating a type named class_1 in ns. Please use Stack Overflow if you have further questions. Thanks!

**Comment by Ignasimg** [comment]
The compiler says A.
@RyanCavanaugh says B.
@aluanhaddad says C.
@tinganho at #3705 said D.

Well... maybe it's not a bug. But the consensus on this project is something you must be really proud about.

Or maybe it's me, who can't understand that "Cannot find namespace ns" is an alias for "there's nothing creating a type named class_1"; Similar to "namespace" being an alias of "module".

But anyway and back to the point, maybe it's not a bug, I never said it is. But my feeling is, if it's not, it really needs some clarification, since: 

- It works when you are not using a dotted identifier.
- There's no sample regarding to it at typescript handbook.
- The most similar sample I found on StackOverflow, is trolled by @RyanCavanaugh http://stackoverflow.com/a/30357635

Btw Ryan, in your post comments, you said: "No matter how much one might want it, it's still _not possible._" is it you?, or is it yet another alias that I'm unable to understand?

Btw2 Ryan, thank you to make me lose my time. Now, it depends on you whether you want to put some light into the topic, or you want to let other people having the same problem as I do, lose their time by reading your non-answers.

**Comment by mhegazy** [comment]
@Ignasimg, please refrain from personal attacks on this forum. Let's keep the discussion here technical and professional. Also we have to ask you to be cognizant of the time the core team spends responding to issues. This issue tracker is mainly for language/compiler bugs and design discussions; and due to the high volume of issues we have to look at every day, we ask that you direct any questions to StackOverflow.

As for the OP, what you are looking for is module augmentation. Please see the handbook at: http://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation. 

As for the error message, I agree it can be better. we have an issue tracking this in https://github.com/Microsoft/TypeScript/issues/102. 

The concepts of namespace, type and value spaces, are core to TypeScript. These will come up often in error messages. I would recommend looking them up in the handbook: http://www.typescriptlang.org/docs/handbook/declaration-merging.html

As for what meant with @aluanhaddad namespace declaration, your files should look as:

```ts
// ns.ts
// Declare your namespace
declare namespace ns {
    // needs to be instantiated, i.e. have some value to be
    // augmentble with other value
    const someValue = 0;
}
export = ns;
```

```ts
// class_1.ts
import ns = require("./ns");


// Declare your augmentation to the module "ns"
declare module "./ns" {
    // declare that you are adding a class called class_1
    class class_1 {
        constructor();
    }
}

class class_1 {
    constructor() { }
}

// now really add the class to the module
ns.class_1 = class_1;


// export your class
export = class_1;
```

Hope this helps.

**Comment by Ignasimg** [comment]
Ok, 
I had to take out the "declare" on ns.ts but besides that now it works.
Thank you for the references, and thank you very much for the sample.

Now that I know what I'm doing is possible, what I really wonder is why is it so complicated?
What I mean is, esentially what I feel is the stupid part is declaring the module augmentation.

The typescript compiler is certainly capable of making the proper ambient declaration for whatever property you want to export through an imported object... so I really feel like I'm doing a monkey job by writting it on every file.

So rephrasing the question... how comes it doesn't do it automatically?

**Comment by mhegazy** [comment]
module augmentation is really a hack. ES6 modules does not allow this form of changing the module shape that was common in node. TS originally did not support any module side effects declarations. the rational was to deter ppl from doing it. Later on multiple scenarios seem to require this form of augmentation. since there are different ways you could augment construcuts, e.g. namespaces, vs class prototype, and sometimes this is only done in specific module systems, but not the others, e.g. umd; the augmentation was added as a "declaration". more of telling other parts of the application what you intend to do with this module. this way you have the freedom to do that. 
I am not sure this explains why it is not simpler, but at least it should explain why it is the way it is.
