### ISSUE TITLE
Type inference of return type changes when function arity changes

### ISSUE THREAD

**Issue by asgerhallas** [Microsoft/TypeScript#11183]
**TypeScript Version:**  2.0.3 (and 1.8.10)

**Code**

```ts
class Greeter<TData> {
    constructor(options: {
        a: (x: any) => TData,
        b: (y: TData) => any
    }) { }
}

let greeter = new Greeter({ 
    a: () => ({ asger: 'hej' }),  // no parameter
    b: (y) => y.asger // TData is of type { asger: string } and this line compiles
});

let greeter = new Greeter({ 
    a: (x) => ({ asger: 'hej' }), // with parameter
    b: (y) => y.asger // TData is of type {  } and this line does not compile
});

```

**Expected behavior:**

I expected type inference to be the same regardless of number of parameters on the function assigned to a.

**Actual behavior:** 

A function with one parameter makes type inference fail and type of TData be {}.

**Comment by ahejlsberg** [comment]
This behavior is an artifact of which parts of an expression we consider *producers* of inferences and which we consider *consumers* of inference (because they may need to know the results of previous inferences to give type to their parameters). In the first example, we classify the first lambda as a producer of inferences because it has no parameters that need contextual types. For that reason we can make an inference for `TData` from its return value and then apply that inference as a contextual parameter type in the second lambda. However, in the second example, we classify both lambdas as consumers of inferences because they both have contextually typed parameters. Thus we fail to make any inferences for `TData` before we consume it in the second lambda.

It is *possible* to fix this, e.g. by realizing that a contextually typed lambda only consumes types that don't reference type parameters, but it isn't simple. Meanwhile, a possible workaround is to explicitly type the `x` parameter in the second example:

```ts
let greeter = new Greeter({ 
    a: (x: any) => ({ asger: 'hej' }),
    b: (y) => y.asger
});
```

**Comment by ahejlsberg** [comment]
I should mention that another possible workaround is to separate the functions into separate parameters:

```ts
class Greeter<TData> {
    constructor(a: (x: any) => TData, b: (y: TData) => any) { }
}

let greeter = new Greeter(
    x => ({ asger: 'hej' }),
    y => y.asger
);
```

This works because we finish inferring from the first constructor parameter before we consume the inference as a contextual parameter type for `y`.

**Comment by asgerhallas** [comment]
@ahejlsberg Thanks a lot for this thorough explanation! The second workaround will work for me. 

I wonder if it any way would be possible to emit an error message saying why inference failed? If this actually counts as failed?

**Comment by asgerhallas** [comment]
On another note: should I close this issue if I feel sufficiently enlightened?

**Comment by ahejlsberg** [comment]
@asgerhallas It's tough to improve inference error messages, particularly because inference is just supposed to *infer* but not to *error*. But we'll continue to think about it.

Yes, feel free to close this issue.
