### ISSUE TITLE
enums are not compiled as numbers when declaration flag is false in tsconfig.json

### ISSUE THREAD

**Issue by akosbordas** [Microsoft/TypeScript#11202]
**TypeScript Version:**  2.02

**Expected behavior:**

I have a const enum in typescript:

```ts
const enum LogLevel {
    TRACE = 0,
    DEBUG = 1,
    INFO = 2,
    WARN = 3,
    ERROR = 4,
    SILENT = 5
}
```
Based on the typescript spec the following field:
```ts
private foo: number = LogLevel.DEBUG;
```
should be compiled as:
```ts
this.foo = 1 /* DEBUG */;
```
**Actual behavior:** 

When I use tsc from the command line (Windows) it works as expected. But when it is compiled with awesome-typescript-loader in a webpack project (which uses the typescript.js from node_modules as opposed to the tsc.js which is used by tsc), then the enum constant is not getting inlined:
```ts
this.foo = LogLevel.DEBUG;
```
It turned out it was caused by the `declaration` option in tsconfig.json. If it is set to false, the two compilations produce the above inconsistent result. But when it is set to true, it works as expected. Not sure why this flag has such an effect on the outcome.

I created a github project where the problem is reproducible. 

[https://github.com/akosbordas/typescript-enum-issue](https://github.com/akosbordas/typescript-enum-issue)

After you changed the `declaration` flag you just have to run `ng build` and check the main.bundle.js in dist folder.

**Comment by RyanCavanaugh** [comment]
This is an issue with how awesome-typescript-loader is using the compiler API.

awesome-typescript-loader uses the TypeScript `transpileModule` function in "fast mode"; "fast mode" is enabled when the declaration flag is not set. `transpileModule` does a pure syntactic transform of each file; in this mode, const enums are not resolved (because its a per-file transform) and their values are not inlined.

`transpileModule` *should not be used* unless an error-free compilation of the same sources has occurred under the `--isolatedModules` flag, which verifies that it is safe to use `transpileModule` on a particular compilation.

I would log a bug with awesome-typescript-loader -- their behavior here is not sound. Hopefully there's some way to configure it to not use `transpileModule`?

**Comment by akosbordas** [comment]
Thank you for your answer! I created an issue for awesome-typescript-loader as well. [#245](https://github.com/s-panferov/awesome-typescript-loader/issues/245)
