### ISSUE TITLE
Control flow check improvement for RegEx

### ISSUE THREAD

**Issue by NicoB1981** [Microsoft/TypeScript#11201]
**TypeScript Version:**  2.0.0 

With the strict null check option enabled the control flow does not realize that a regular expression will always return a result array if calling the 'test' method returns true. Hence, control flow check marks the call to exec(s)[0] as error because it believes it could return null as a result.

**Code**

```ts
var regEx = new RegExp('some regular expression');
var s= 'test string';

if (regEx.test(s)) {
     var t = regEx.exec(s)[0];
 }

```

**Expected behavior:**

var t should be typed as string|undefined

**Actual behavior:** 

error Object is possibly 'null'

**Comment by kitsonk** [comment]
These sort of co-dependent methods aren't tracked by CFA since there is no way currently of expressing that `.test()` has some effect on `.exec()`.  This is covered by #11117.

Also, that is inefficient code, where you are running the RegEx twice.  Something that would work with CFA and avoids running the RegEx twice:

```typescript
var regEx = new RegExp('some regular expression');
var s= 'test string';

const result = regEx.exec(s);

if (result) {
     var t = result[0];
 }
```

**Comment by mhegazy** [comment]
thanks @kitsonk
