### ISSUE TITLE
Extraneous <global> symbol from Salsa

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#11230]
_From @mousetraps on September 28, 2016 20:40_

Testing #12598 

![image](https://cloud.githubusercontent.com/assets/762848/18931439/088f3a1c-8581-11e6-8a79-17b54f6a4aeb.png)

_Copied from original issue: Microsoft/vscode#12936_

**Comment by mhegazy** [comment]
The top level entry in `NavBar` call will always be `<global>` or `<module name>`. if VSCode does not want to show that, then the top entry should be filtered out.

I do not think this is a change on the server side, but on VSCode side. closing.

**Comment by dbaeumer** [comment]
@mhegazy what is the reason to have that in in the first place. This is requesting symbols for a specific document. So why do we have an extra root element.

**Comment by dbaeumer** [comment]
I debugged it a little and the returned structure is as follows;

Response.body:
   - function foo
   - <global>
      - function foo

So there is no single <global> entry :-)

**Comment by dbaeumer** [comment]
There is more wiredness:

```js
function foo() {
	function bar() {
		function faz() {
			
		}	
	}
}
```

Produces the following Nav item tree
```
body
   - <global>
   - foo
        - bar (with no children which is wrong as well)
   - bar <== this is wrong
        - faz
```

**Comment by mhegazy** [comment]
The issue here is that `NavBar` really returns output suitable for two-drop-down list format that VS uses. 

I think the best solution here is to add a new command to the server, `getLexicalStrucutre`, or `getNavigationTree`, that has the tree form. this should be fairly simple for us, since we already generate the output as a tree, then serialize it in the two-drop-down-list format for VS.

I have logged https://github.com/Microsoft/TypeScript/issues/11250 to track adding the new command.

If you are interested in reverse-serializing the output of navBar, here is the algorithm:

- Remember all top-level entries in a dictionary, keyed by `name` + `indent`.
- Start by the first top-level item (this is going to be `<global>` or a module)
  - walk its `childItems`, and serialize them recursively
    - For each item, check your top level dictionary first, if an entry was found at the top level use it, if not then use this one.

**Comment by dbaeumer** [comment]
@mhegazy thanks for the clarification. Could be prioritize #11250 for 2.0.5. Sounds easy on your end. Easier than use added the reverse-serializing code.
