### ISSUE TITLE
[Suggestion] should Overloads not differ only by return type?

### ISSUE THREAD

**Issue by HerringtonDarkholme** [Microsoft/TypeScript#11281]
I wonder if this is a bug. But at least this is a discrepancy between specification and implementation.

 It appears in TS 1.03 function overloading cannot differ only by return type, but in TS1.1 this restriction was lifted. 

``` typescript
function a(): number
function a(): string
function a(): any { return null as any}
```

SO question: http://stackoverflow.com/questions/25022331/overloads-cannot-differ-only-by-return-type

Source: https://github.com/Microsoft/TypeScript/blob/release-1.0.3/src/compiler/resources/diagnosticMessages.json#L1024

Spec: https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#1212-ambient-function-declarations

This should also impact call signatures in intersection types.

**Comment by isiahmeadows** [comment]
TS is at 2.1 now...I'd advise checking it out. It's got some pretty cool features. :wink:

**Comment by RyanCavanaugh** [comment]
Three options on the table:
 * Correctly detect all unreachable signatures
 * Detect some unreachable signatures but not others
 * You're on your own, good luck

The first option is expensive (`O(n^2)` and we have large `n` in many places) and for the sake of checking code that is very rarely wrong. The second option is hard to explain, still expensive, and ends up confusing people because sometimes they get an error and sometimes they don't. The third is undesirable for obvious reasons, but is at least "free" in certain sense of the word and can be mostly covered with TSLint rules in places where there's some danger of getting it wrong.

**Comment by HerringtonDarkholme** [comment]
Thanks for your explanation!
