### ISSUE TITLE
Tsc complains about files outside rootDir but compiles them anyway

### ISSUE THREAD

**Issue by Rhobal** [Microsoft/TypeScript#11299]
**TypeScript Version:**  2.0.3

My `tsconfig.json` is in the root directory of a maven project. `rootDir` is `/src/main/ts`
The `.ts` files are under `/src/main/ts`, but maven produces copies in `/target/classes`

**Expected behavior:**
When compiling, files outside `rootDir` should be ignored silently, perhaps unless referenced.

**Actual behavior:** 
`tsc` complains about files outside `rootDir` but compiles them anyway, resulting in duplicate JS code.

**Comment by a-shark** [comment]
Similar behavior under 2.1.6. All the "use typescript with react-native!" `tsconfig.json` files I can find don't work properly for me. Tries to compile existing output files(!!!), files outside the rootDir, _et c._, respecting neither rootDir nor `exclude`, _unless_ I switch `filesGlob` to `include`, at which point it stops being able to see definitions contained in node modules but otherwise seems to work (so, still not at all, but for different reasons).

**Comment by mhegazy** [comment]
>  unless I switch filesGlob to include, 

`fileGlob` is not a regonized typescript property. The compiler never reads it. please see http://www.typescriptlang.org/docs/handbook/tsconfig-json.html for supported properties.

> at which point it stops being able to see definitions contained in node modules but otherwise seems to work (so, still not at all, but for different reasons).

Please share a self contained repro.

**Comment by mhegazy** [comment]
> tsc complains about files outside rootDir but compiles them anyway, resulting in duplicate JS code.

@Rhobal, I can not piece together a repro from your description. please provide a self-contained repro, ideally a project and a config file i can pass to `tsc`.
