### ISSUE TITLE
Issue when using export as namespace in type definitions

### ISSUE THREAD

**Issue by subash-a** [Microsoft/TypeScript#11316]
TS Version 2.1.0-dev.20160915
We use `JSPM` as our module loader and using npm-based installation of type defintions (i.e. @types)

An issue when referring to React namespace when it is not imported.

**Actual Behaviour**
We get the error message:
`Identifier 'React' must be imported from a module`

**Expected Behaviour** 
get the error message
`Cannot find namespace 'React'`

Seems like this is related to:
`export as namespace React;` statement in the [React type definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/04b427297486d599eca173d464bed41c10b5440d/react/index.d.ts#L7)

The `export as namespace..` appears to make the React namespace available globally, i.e. it pollutes the global namespace, and also gives rise to the message `Identifier 'React' must be imported from a module`, when we comment out the `export as namespace...` everything works as expected, but suspect this was included for some reason by @RyanCavanaugh ?

**Comment by aluanhaddad** [comment]
I assume you are loading React via JSPM at runtime which means you should be importing it as an external module where ever you use it. If you do that in even one file you can no longer use the global `React` because the `export as namespace` syntax is there to allow use as a global variable or use an external module, but not a mixture. It is intentionally mutually exclusive.

**Comment by myitcv** [comment]
@aluanhaddad thanks for the response. I work with @subash-a so will chime in here too.

Yes, we are loading React via JSPM, hence we will never use the global `React`; this is why we expect any use of `React` (without an import) to give the error message:

```
Cannot find namespace 'React'
```

So is it the case that the `export as namespace` line is included to support those people who do use `React` globally, and the error message:

```
Identifier 'React' must be imported from a module
``` 

is there to help people _not_ using the global `React` to remember to `import` wherever `React` is used?

Will this not fail in the situation where I'm starting a new project, decide to use JSPM (a decision I take up front), create my first `*.{ts,tsx}` file which references `React` (accidentally forgetting to `import`), which then compiles just fine but then fails at runtime?

**Comment by aluanhaddad** [comment]
@myitcv you are exactly correct. This is precisely to prevent accidental usage of the global by those using modules but to allow the type declaration to be shared with others using it as a global.



> Will this not fail in the situation where I'm starting a new project, decide to use JSPM (a decision I take up front), create my first *.{ts,tsx} file which references React (accidentally forgetting to import), which then compiles just fine but then fails at runtime?

I will try to find out.

**Comment by aluanhaddad** [comment]
OK, so that case is also guarded against. So long as you are using react from a module, you must import it.
Module with error
![image](https://cloud.githubusercontent.com/assets/5034656/19038711/c7c3d380-894a-11e6-86b3-faa62886c1cd.png)

Corrected Mudule
![image](https://cloud.githubusercontent.com/assets/5034656/19038759/060a1f1e-894b-11e6-8f2a-d452eed83cd0.png)

Script
![image](https://cloud.githubusercontent.com/assets/5034656/19038735/e5fa8484-894a-11e6-8150-df23e472d0ca.png)

**Comment by myitcv** [comment]
@aluanhaddad thanks very much for checking that out.

So my next question is: how does the compiler know that `React` must be imported (when there are no `imports` to tell it one way or the other)?

Does it use `compilerOptions.module` from `tsconfig.json` in some way? (I'm guessing it does)

**Comment by aluanhaddad** [comment]
If there are no imports or exports as in the last example, you are writing a global script. 
A file is only a module if it has at least one top level import or export.

That is how it will be compiled and so it assumes you are looking for `React` in the global namespace. Since it finds `React` there. It successfully typechecks.

**Comment by myitcv** [comment]
> If there are no imports or exports as in the last example, you are writing a global script. 
A file is only a module if it has at least one top level import or export.

Sorry, but I'm missing something. We're talking about a TypeScript project here that declares a `tsconfig.json` similar to what follows (which is ours):

```json
{
  "compilerOptions": {
    "declaration": false,
    "jsx": "react",
    "module": "system",
    "moduleResolution": "node",
    "newLine": "LF",
    "noEmitOnError": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noLib": true,
    "removeComments": false,
    "rootDir": ".",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types/",
      "../src/typings/"
    ]
  }
}
```

Are you saying that global scripts can be written in this context? Assuming there is just one `.ts` file in this project and it doesn't declare any dependencies via imports, it is effectively a global script? 

Then doesn't this fail the test that I described above? Namely that it's possible to write code (as you did, your global script) that uses `React`, compiles, but then fails at runtime?

**Comment by RyanCavanaugh** [comment]
Some example code that reproduces this in a place that is unexpected would be appreciated

**Comment by myitcv** [comment]
@RyanCavanaugh hopefully this helps to demonstrate the issue: https://github.com/myitcv/ts_react_node_types_repro

**Comment by aluanhaddad** [comment]
>Are you saying that global scripts can be written in this context? Assuming there is just one .ts file in this project and it doesn't declare any dependencies via imports, it is effectively a global script?

That is indeed what I'm saying.

>Then doesn't this fail the test that I described above? Namely that it's possible to write code (as you did, your global script) that uses React, compiles, but then fails at runtime?

Yes it is definitely possible. The issue here is that the ECMAScript module specification defines what is or is not a module by the presence of at least one top-level import or export. But given how you have configured the loader, the lack of an export in that file is almost certainly a bug anyway.

**Comment by myitcv** [comment]
@aluanhaddad just to be clear, you think the bug here is that we've "written" a global script when we intended to "write" a module?

**Comment by aluanhaddad** [comment]
@myitcv
I just saw that you posted a repo, based on the code there, you have indeed written a global script.

Here are 3 deltas on your `index.ts` file that I think will be helpful.
_**global**_ --> no `import` or `export` statements (valid code)
```ts
var Hello = React.createClass({
  displayName: 'Hello',
  render: function() {
    return React.createElement("div", null, "Hello ", this.props.name);
  }
});
console.log(Hello);
```


_**module**_ --> contains an `import` statement (valid code)
```ts
import * as React from "react";

var Hello = React.createClass({
  displayName: 'Hello',
  render: function() {
    return React.createElement("div", null, "Hello ", this.props.name);
  }
});
console.log(Hello);
```


_**module**_ --> contains an `export` statement (incorrect code due to missing import)
```ts
export var Hello = React.createClass({
  displayName: 'Hello',
  render: function() {
    return React.createElement("div", null, "Hello ", this.props.name);
  }
});
console.log(Hello);
```
This last example fails with 
`Identifier 'React' must be imported from a module` 
and in the latest nightly with the more descriptive 
`'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.'`
