### ISSUE TITLE
No ability to break on caught exceptions when Salsa is enabled (UWP app)

### ISSUE THREAD

**Issue by fmpublic** [Microsoft/TypeScript#11372]
**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)

**Code**

```ts
// A *self-contained* demonstration of the problem follows...

```

**Expected behavior:**

**Actual behavior:**

**Comment by forty2** [comment]
I'm experiencing this problem as well, and it makes for a very frustrating development experience.

To demonstrate the problem:

1. create a brand new Blank App (Universal Windows) from the File | New | Project menu.
2. Insert this code in the newly created main.js: `window.onload = () => { throw new Error("foo") };`
3. Make sure all exceptions are enabled in Exception Settings: 
![image](https://cloud.githubusercontent.com/assets/1472096/19370671/0a2bad46-9162-11e6-89e5-ba6444ea22b1.png)
4. Launch the app.

This will crash due to the thrown exception, but the debugger will not break on the throw line.

Likewise, if you put a `try`/`catch` around the throw:
```javascript
window.onload = () => {
    try {
        throw new Error("foo")
    } catch (e) { }
};
```

the crash goes away because the exception is caught, but the debugger still will not break on the exception (even though it clearly says "break when thrown" in the Exception Settings).

Is no one else seeing this behavior?  Unfortunately, it pretty much prevents me from using VS15 (and the otherwise excellent new Salsa engine) for JS development because I have no good way of figuring out why or even where an exception got thrown.  I used to be able to turn Salsa off when I knew there was an exception to debug, but of course with Preview 5 I can't do that anymore.

**Comment by mhegazy** [comment]
@minestarks thoughts?

**Comment by forty2** [comment]
Just for grins, I tried it with a TypeScript file, with a blank WinJS app, and with a blank Node.js console application and had the same experience in all cases: it just won't stop on exceptions.

Incidentally, it's just occurred to me that after this gets resolved, the next thing I'm going to want to be able to do is toggle between breaking on all exceptions and breaking just on uncaught exceptions, but I don't see an obvious way to set that up in Exception Settings.  I don't want to get too far ahead of myself, but am I missing something?

**Comment by minestarks** [comment]
@forty2 - 
- If you set a breakpoint in a TS file do those work?
- Do you have the same issue with not breaking on exceptions on JS files? Or is it just TS files?

**Comment by minestarks** [comment]
@fmpublic which version of Visual Studio?

**Comment by forty2** [comment]
@minestarks: yes, breakpoints work fine in both TS and JS files (in fact, they work better than ever before in JS files).  Not breaking on exceptions happens both for JS and TS -- I first discovered the issue in a plain JS file, but I have since confirmed that it affects TS files as well.

**Comment by fmpublic** [comment]
@minestarks 
Microsoft Visual Studio Enterprise 15 Preview 4
and
Microsoft Visual Studio Enterprise 15 Preview 5

**Comment by forty2** [comment]
@minestarks Were you able to repro this with my steps?  Is there a known workaround until this gets fixed?  Thanks!

**Comment by minestarks** [comment]
@forty2 sorry forgot to respond. Yes I saw the same behavior in VS15 Preview 5. Seems like a script debugger issue (both in Node.js and UWP, curiously). I don't know of a workaround currently. 

@mhegazy given that this isn't strictly TypeScript what's the right way to engage the right people?

**Comment by mhegazy** [comment]
@andysterland any recommendations here?

**Comment by fmpublic** [comment]
@mhegazy  Could you provide some guidance on what 2.1RC mean in terms of targer release schedule? Thanks so much.

**Comment by mhegazy** [comment]
We are targeting to release TypeScript 2.1 in [November](https://github.com/Microsoft/TypeScript/wiki/Roadmap#21-november-2016), with an RC drop some time next week. the RC date is tentative at this point. 

Just for full disclosure, we still do not understand the root cause of this issue, so we do not have a fix nor a concentrate release date. Also this is a VS "15"-specific change, so you would get it as part of the next public release of VS; which is not something I have control over, or can share dates for.

**Comment by sheetalkamat** [comment]
Work around for this issue is to disable "Enable Just My Code" and the debugger should break at the exception.

**Comment by mhegazy** [comment]
Fix should be available in the next public release of Visual Studio "15".

**Comment by forty2** [comment]
Just to confirm, the workaround from @sheetalkamat works great.  Thanks!
