### ISSUE TITLE
Range/interval comprehension in 'for/while' loops

### ISSUE THREAD

**Issue by adrianvoica** [Microsoft/TypeScript#11381]
We could benefit from range/interval comprehension in 'for/while' loops:
	`for (i in 1..10) { someCodeHere(); }`
could be optimized by the compiler using the classical for loop construct:
	`for (i=1; i<=10; i++) { someCodeHere(); }`

or, with the 'while' construct:
	`while (i in min..max) { ... }`
could be comprehended as
	`while (i >= min && i <= max) { ... }`

*might also work for other iteration-based constructs and for array/tuple construction, but this is a different story.

**Comment by adrianvoica** [comment]
I might go as far as to suggest: 
`for (1..10) { someCodeToBeExecutetEveryIteration(); }`
when we don't need to know the iterated object - taken care of behind the scenes by the compiler using a a variable, translated to something like:
`for (_aRandomVarName = 1; _aRandomVarName <= 10; _aRandomVarName++) { ... }`

**Comment by yortus** [comment]
[ES Discuss](https://esdiscuss.org/) is probably a better place to suggest this. TypeScript aims to be a superset of ECMAScript with static typing added. What you are proposing is new language syntax, rather than something related to static typing specifically.

TypeScript would likely only consider this if it was already a fairly advanced proposal for ECMAScript. OTOH, if this gets picked up for a future version of ECMAScript, it will eventually make its way into TypeScript.
