### ISSUE TITLE
TypeScript's __decorate function should not use strings for symbols

### ISSUE THREAD

**Issue by btraut** [Microsoft/TypeScript#11435]
Method decorators work, and they're awesome. Unfortunately, when they're used, the emitted JS specifies symbol names in strings rather than using references to the actual function prototypes. This causes minification to fail pretty horribly because it can't associate the actual functions with the values in the strings.

**TypeScript Version:**  2.x

**Code**

I have an `AuthStore` class that declares a `getUser` method that has an `@autoSubscribe` decorator. TypeScript compiles this by adding this after the class definition:

``` ts
__decorate([
       resub_1.autoSubscribe
], AuthStore.prototype, "getUser", null);
```

After minification via Closure Compiler, my `getUser` is named `d`, but the call to `__decorate` still contains `"getUser"`.

**Expected behavior:**

Is it possible to use the function prototype in the `__decorate` call, such as this?

``` ts
__decorate([
       resub_1.autoSubscribe
], AuthStore.prototype.getUser, null);
```

**Comment by btraut** [comment]
Also, see discussion on https://github.com/google/closure-compiler/issues/2065#issuecomment-252112770

**Comment by aluanhaddad** [comment]
in https://github.com/google/closure-compiler/issues/2065#issuecomment-252115856 you concluded the was not possible due to the need to call `Object.defineProperty`

**Comment by ChadKillingsworth** [comment]
It can be done without quotes by using `Object.defineProperties` (plural).

**Comment by deregtd** [comment]
I've implemented a workaround for this on our project (same project btraut is referencing).  It's an ugly sketchy regex, but it does make everything work, at least in our project.  Just run this script on the final webpacked js file before running it through CC and it'll do all the replacements.

The two replacements are:
1. Change calls to __decorate to, instead of passing the method name as a string in the third parameter, instead pass the prototype function pointer itself.
2. Add a line of code to the __decorate function that, if you passed a function pointer as the third parameter, convert it back into a string key by walking the prototype chain and finding the key for the passed function pointer:
`var key = protoMethod; for (var k in target) { if (target[k] === protoMethod) { key = k; break; } }`

Here's the script in full:
```
var fs = require('fs');

var appFile = fs.readFileSync('js/app.js', 'utf8');

// The goal is to stop calling prototype methods by string names, and instead call them directly.
// Back calculate the key from the prototype method itself by iterating over the prototype list and matching up the key to the method signature
// after CC minifies it. 

var decorateFuncFinder = new RegExp('var __decorate = \\(this && this.__decorate\\) \\|\\| function \\(decorators, target, key, desc\\) {', 'g');
var newDecorateFuncHeader =  'var __decorate = (this && this.__decorate) || function (decorators, target, protoMethod, desc) {\r\n' + 
    '        var key = protoMethod; for (var k in target) { if (target[k] === protoMethod) { key = k; break; } }';

var decoratorFinder = new RegExp('__decorate\\((\\[[^\\]]+\]), ([^.]*.prototype), \\"([^\\"]+)\\", null\\)\\;', 'g');
var newDecoratorCall = '__decorate($1, $2, $2.$3, null);';

var appFileReplaced = appFile.replace(decorateFuncFinder, newDecorateFuncHeader);
appFileReplaced = appFileReplaced.replace(decoratorFinder, newDecoratorCall);

fs.writeFileSync('js/app.rep.js', appFileReplaced);
```

**Comment by mhegazy** [comment]
I do not think there are changes we can do in the short term to address this issue without breaking current users of decorators. The decorator proposal has changes since TS has first implemented it, so I would expect us making breaking changes in the future for how decorators are implemented, and we can take this issue into consideration to ensure that the new implementation does not exhibit the same behavior.

**Comment by RyanCavanaugh** [comment]
We're dependent on the TC39 decorator proposal for this emit. If that lands differently we can change our emit accordingly if needed, but there doesn't seem to be a lot of traction here
