### ISSUE TITLE
Typings nightmare with @types/xxx

### ISSUE THREAD

**Issue by tomitrescak** [Microsoft/TypeScript#11437]
This is not a bug, rather call for help.
Since recently packages started to install dependencies from **@types** repo.

From this moment on none of my projects is compilable as I am using `Mocha` for my tests, yet one of the packages uses `Jest`. Both of these packages declare "`describe. it ...`" in the global space.

So, I have @types/jest and @types/mocha installed in the node_modules folder.

As a result, no project will compile and my CI is out of order.

The only possibility that comes to my mind is to roll back to "classic" module resolution and copy the definitions into my project manually.

Is this true? Is there anything else I can do?

[EDIT]

**I put moduleResolution to "classic" and it is still compiling stuff in the @types folder!!! WHY?**

**Comment by yortus** [comment]
> I am using `Mocha` for my tests, yet one of the packages uses `Jest`

Shouldn't that package have `@types/jest` as a `devDependency` rather than as a `dependency`? Then `@types/jest` won't be installed when you `npm install` your own module.

Generally the packages you depend on should not bring in their development dependencies (built/test infrastucture), just their executable code.  But I can't really tell if this is the situation from the description above.

**Comment by tomitrescak** [comment]
Well, I am not that package developer and this is what happens. Installing that package "Jest" appears in my typings folder.

**Comment by yortus** [comment]
Can I ask what the package is? If it is a `deps` vs `devDeps` issue in their package, then the fix is simple for them to make and the problem will go away for you.

**Comment by tomitrescak** [comment]
Hi, I already created an issue with this. But I guess, the problem is not so isolated. Is there any other mean of protection from this apart from waiting for package developer to update and release a new version? Thanks.

**Comment by yortus** [comment]
Hopefully someone else can answer if there's a workaround for this.

In the mean time it would be helpful if the team promoted the proper use of `depDependencies` with @types typings. In the last few blog posts (e.g. [here](https://blogs.msdn.microsoft.com/typescript/2016/09/22/announcing-typescript-2-0/#user-content-simplified-declaration-file-dts-acquisition)) they show installing @types as normal dependencies, which means all clients of such packages will also needlessly get those types installed, even though they are *not* needed to run the package code.

At best it's a useless dependency for clients, but sometimes it may lead to clashes/errors such as the one you've reported here.

**Comment by weswigham** [comment]
If you want a complex workaround, you _should_ be able to manually remove the unwanted folder from your transitive @types by running [`npm shrinkwrap`](https://docs.npmjs.com/cli/shrinkwrap) to pickle your dependencies, then edit the generates `npm-shrinkwrap.json` to remove the `@types` package you do not want to include. Then just delete it from disk and the shrinkwrap should prevent it from being installed for anyone else.

It's a bit of a kludge, but it can workaround packaging dependency conflicts like this.

**Comment by tomitrescak** [comment]
I was really hoping that `skipDefaultLibCheck` will do good here as it its said to skip validation of .d.ts files, but it seems to do nothing as .d.ts files are still validated :/

**Comment by mhegazy** [comment]
@tomitrescak, just to make sure i understand, there are two projects, one depend on `mocha`, while the other use `Jest`? or is it that you have projects that depend on both?


if it is the earlier, then the fix is to use `"types" : ["mocha"]` in your tsconfig.json; this will instruct the compiler to **only** load `@types/mocha` in this project, then for the other project  `"types" : ["jest"]` .

if it is the later. then what you need is to "break the tie" between the two declarations in some way. so options, consider creating a new folder: "overrides" , and add `"overrides\jest\index.d.ts" to be what you think `jest` should be. then update your tsconfig.json to include  `"typeRoots": [".\overrides", ".\node_modules\@types"]`. What this does it tells the compiler to look for types first in `".\overrides\jest"` and if it did not find it to look in `".\node_modules\@types\jest"`.

Ultimately the fix is on the declaration file side, and i would recommend you send a PR to DT with a fix that removes the declaration of `it`, `declare` etc.. to a different package that both `jest` and `mocha` depend on.

See http://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types for more details on this.

**Comment by tomitrescak** [comment]
@mhegazy thanks for the explanation. That link really helped. My problem was the first one, where a project I'm depending on was installing "jest" into @types folder, while I am using mocha. They bothe depend on global variables which were clashing.

Would be great to point to that page in the list of the compiler options.

**Comment by mhegazy** [comment]
Added links to docs in https://github.com/Microsoft/TypeScript-Handbook/commit/a83f002e6fefe9d15059beeada6cc744310444c2

**Comment by tomitrescak** [comment]
Fantastic, thanks!
