### ISSUE TITLE
Not narrowing on boolean literal

### ISSUE THREAD

**Issue by edevine** [Microsoft/TypeScript#11450]
**TypeScript Version:**   2.1.0-dev.20161007

Compiler is not narrowing via `true | false` when used without equality operator.

**Code**

```ts
interface Done {
    done: true;
}
interface NotDone<V> {
    done: false;
    value: V;
}

type Iteration<V> = NotDone<V> | Done;

var it: Iteration<string>;

if (it.done == true) {
    it.value; // Error
}
else {
    it.value;
}

if (it.done) {
    it.value; // Error
}
else {
    it.value; // Error
}
```

**Expected behavior:**
```ts
if (it.done) {
    it.value; // Error
}
else {
    it.value;
}
```
**Actual behavior:** 
```ts
if (it.done) {
    it.value; // Error
}
else {
    it.value; // Error
}
```

**Comment by ahejlsberg** [comment]
It works as expected in `--strictNullChecks` mode. In classic type checking mode, `null` and `undefined` are possible values of *every* type, including `true` and `false`. So, in the example above, we can't narrow in the `else` part because `it.done` might still be `null` or `undefined` which is a valid value for `done` in both `Done` and `NotDone<V>`.

Strictly speaking we should actually error in all cases in classic type checking mode, but that would make the comparison operators behave very illogically, so for those we don't consider the possible effects of `undefined` and `null`.

 It's rather subtle and `--strictNullChecks` mode is definitely a lot more consistent.
