### ISSUE TITLE
TypeScript: Importing file from parent directory ("../") causes invalid autocomplete

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#11457]
_From @andy-hanson on October 6, 2016 23:28_
- VSCode Version: 1.5.3
- OS Version: Linux Mint 17.3

Steps to Reproduce:
1. Open a TypeScript file
2. Type `import {} from ".`
3. Type `.` again

**Expected:**
I can import modules from a parent directory with no hassle.

**Actual:**
It is filled in automatically to be come `import {} from ".tslint.`, with "tslint" possibly replaced by some other package that happens to be in my `package.json`.

_Copied from original issue: Microsoft/vscode#13319_

**Comment by waderyan** [comment]
@andy-hanson thank you for opening this issue. What extensions do you have installed? This is not a feature that is available without an extension.

**Comment by waderyan** [comment]
_From @andy-hanson on October 7, 2016 22:24_

I don't have any extensions installed, but I do have the setting `"typescript.tsdk": "/home/andy/.nvm/versions/node/v6.7.0/lib/node_modules/typescript/lib"`, without which the problem doesn't happen.

**Comment by waderyan** [comment]
What is the version of TS?

**Comment by waderyan** [comment]
_From @andy-hanson on October 7, 2016 23:10_

`2.1.0-dev.20161007`

**Comment by waderyan** [comment]
@andy-hanson you are the bleeding edge! Ok this issue falls onto the TS server team. Sending their way...

**Comment by wallverb** [comment]
Looks like related:
https://github.com/Microsoft/vscode/issues/12667 
https://github.com/Microsoft/TypeScript/issues/11232 
https://github.com/Microsoft/TypeScript/issues/11044

**Comment by waderyan** [comment]
Duplicated of #11044

**Comment by andy-ms** [comment]
Looks like this is an issue now in vscode 1.8.0. When I import `"..` it autocompletes with `".git.`.

**Comment by thomasboyt** [comment]
Can also confirm that I've seen this issue on the current stable version of VSCode (1.8.1) and TypeScript 2.1.4. It popped up when I added `normalize.css` to my project, meaning that I now see this when I type a `.`:

![screen shot 2016-12-19 at 6 46 07 pm](https://cloud.githubusercontent.com/assets/579628/21333192/15ceabfa-c61c-11e6-9fea-9cc94d3036bc.png)

Annoyingly, it seems that TypeScript also enables `.` as an autocomplete-suggestion-accepting key, meaning that _every time I open an import path with `..`_ it automatically turns into `normalize.css.`. 

I've currently worked around this problem by disabling `.` as a suggestion-accepting key in my `keybindings.json`:

```
[
  { "key": ".",                     "command": "-acceptSelectedSuggestion"}
]
```

The issue here is actually really subtle and kind of interesting:

* TypeScript tries to match imports by using certain characters as word separators. This way, I can import `whatwg-fetch` by typing `fetch` and accepting a `whatwg-fetch` suggestion.
* `.` is considered a "word" in this context.
* `.` is also considered a key that will cause an accepted suggestion to be selected.
* Thus, when I type `.`, it matches `normalize.css`. Then, when I type a second `.` to try to get a relative import from the parent directory, it instead accepts the suggestion of `normalize.css` and inserts a second period, resulting in `import Foo from "normalize.css."`

**Comment by aozgaa** [comment]
@mjbvz , we would like to inform the editor that we are in a string literal where `.` shouldn't be used as a completion character. To pass back this additional info, we would need to make a new request, say `completions-full` that would return the completions and metadata about the context for how completions should be applied/filtered/augmented.

Is this a plausible plan of attack?

Additionally, I see that there is another issue with `.` completions in https://github.com/Microsoft/TypeScript/issues/13456. @mhegazy perhaps we should create a flag called `dotCompletable`? Or would a less prescriptive flag like `isStringCompletion` (which would settle the current issue but not the linked one) be preferable?

**Comment by mjbvz** [comment]
@aozgaa Our current approach uses a specific set of commit characters for completion items: https://github.com/Microsoft/vscode/pull/18380/files

This allows us to trigger completion on `/` for module paths for example. Maybe something like this would also work here? We could use the standard completion characters for a completion item, unless TS returns a special set which would override these?

**Comment by mjbvz** [comment]
I believe this was fixed on the VS Code side. `.` should no longer be commit character for paths
