### ISSUE TITLE
Format typescript code does not work properly with comment

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#11456]
_From @osechet on October 7, 2016 5:36_

- VSCode Version: 1.5.3
- OS Version: Windows 10 / Ubuntu 16.04

Steps to Reproduce:

1. Open this [file](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/80060c94ef549c077a011977c2b5461bd0fd8947/openlayers/index.d.ts)
2. Call the format code command.
3. Some comments are not formatted as expected. For example, around line 62 or 149. The indent is wrong.

_Copied from original issue: Microsoft/vscode#13327_

**Comment by waderyan** [comment]
@osechet thank you for opening this issue. This is a good find and easy to follow recreation steps. 

The format code command is dependent on the TypeScript language service. I will send this issue to their repo. 

Here are images of the problem. 

![image](https://cloud.githubusercontent.com/assets/2449568/19206882/eea2928a-8ca0-11e6-9a18-fd08e115df96.png)

![image](https://cloud.githubusercontent.com/assets/2449568/19206890/fadbcfda-8ca0-11e6-841b-600652076234.png)

**Comment by SaschaNaz** [comment]
Interesting.

Input:
```ts
   /**
 * Comment
 */
declare namespace ol {
/**
     * Comment
     */
    namespace animation {
    }
}
```

Result:
```ts
/**
* Comment
*/
declare namespace ol {
    /**
         * Comment
         */
    namespace animation {
    }
}
```

**Comment by mhegazy** [comment]
This is working as intended. the formatter does not format comments. it will try to keep the relative indentation between lines in comments, to ensure that they move as a block. 

the first block is moved all tot he left a by 4 spaces, The formatter attempts to move the second and third lines by 4 as well, but since they are at column 1, they only get moved by 1.

What we need is JSDoc formatting support, which is a feature that is not supported today.

**Comment by mhegazy** [comment]
Logged https://github.com/Microsoft/TypeScript/issues/11500 to track this suggestion.
