### ISSUE TITLE
Support passing typeof T as parameter in generic methods

### ISSUE THREAD

**Issue by MeirionHughes** [Microsoft/TypeScript#11490]
**TypeScript Version:**  2.0.3

linq.d.ts:
```
interface Array<T> {
  ofType<TResult>(type:typeof TResult):TResult[]
}
```
**Expected behavior:** 
No errors. 

**Actual behavior:** 
produces error:
>[ts] Cannot find name 'TResult'.

**Comment by aluanhaddad** [comment]
@MeirionHughes If you are after behavior analogous to C#'
`IEnumerable<TResult> Enumerable.OfType<TResult>(this IEnumerable<T>);`
you can simply write
```ts
interface Array<T> {
  ofType<TResult>():TResult[];
}
```
The reason you get the error
> [ts] Cannot find name 'TResult'.

Is because `typeof` expects a value and `TResult` is a type. For example, when acting upon a `class`, the case where it is most commonly used, it is the `class`'s value that is the operand.

**Comment by HerringtonDarkholme** [comment]
@aluanhaddad I think @MeirionHughes probably want something like this, if I read the C# [counterpart](https://msdn.microsoft.com/en-us/library/bb360913(v=vs.110).aspx) correctly.

```typescript
interface Array<T> {
  ofType<R extends T>(RType: { new(...args: any[]): R}): R[] 
 // probably you also need overloading for builtin Number, String, Boolean
}

//usage
var animals: Animal[] = [new Cat, new Dog, new Fish]
var cats: Cat[] = animals.ofType(Cat)
```

Please first checkout [FAQ](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-cant-i-write-typeof-t-new-t-or-instanceof-t-in-my-generic-function) before submitting issues. You probably want to pass a constructor to `ofType` so that array values can be filtered at runtime.

@aluanhaddad I think your approach can only make `Array<TResult>` but not runtime. C#'s generic is reified at runtime, but TypeScript's is erased. So users must have a value to figure out which type should be used as filter criteria.

**Comment by MeirionHughes** [comment]
@HerringtonDarkholme yes, that `{ new(...args: any[]): R` works perfectly.

>is because typeof expects a value and TResult is a type. For example, when acting upon a class, the case where it is most commonly used, it is the class's value that is the operand.

Okay thx, I'll close this then.

**Comment by aluanhaddad** [comment]
@HerringtonDarkholme great point, I was being overly literal. I another, perhaps more flexible approach would be to pass to take a typeguard as the argument.

```ts
interface Array<T> {
  ofType<TResult extends T>(guard: (x: T) => x is TResult): TResult[];
}
```
