### ISSUE TITLE
In JS, @template doesn't work on prototype methods

### ISSUE THREAD

**Issue by waderyan** [microsoft/TypeScript#11492]
_From @benjaminmillhouse on October 6, 2016 19:18_
- VSCode Version: 1.5.3
- OS Version: macOS 10.12

@template JSDoc comments are not recognized if applied directly to a prototype function definition.

```js
/** @constructor */
function Foo() { }
/**
* @template T
* @param {T} bar
* @returns {T}
*/
Foo.prototype.foo = function (bar) {
};
new Foo().foo({id: 1234}). // Intellisense will not provide any recommendations in this example
```

Edit from @waderyan: added syntax specifier to code block

_Copied from original issue: Microsoft/vscode#13307_

**Comment by waderyan** [comment]
@benjaminmillhouse thank you for opening this issue. I have recreated on my own machine and will send this across to the TS repo.

**Comment by Andarist** [comment]
This issue is already fixed, the completions are nicely provided: [TS playground](https://www.typescriptlang.org/play?ts=5.3.0-dev.20230825&filetype=js#code/PQKhAIAEGMHsDsDOAXATgV2s2rwmAFABm68WAlguAGKywAUAlOAN7gC+BoIBEkyAUwC2ABwA2AQ0HgAKrygiJqCUNYz24AEZL5kVAOTpUSNZ3wFasAHQjUsbMgCeIgVaJ1wAXnAkyySvDg9NqozCwE7ADcBPACAO40dExuSSzkACYAXOAAjABMAMwALOyMVkA), cc @jakebailey

**Comment by jakebailey** [comment]
This was fixed in https://github.com/microsoft/TypeScript/commit/5a05b94fb5e03eed15f6b687f6ec490c5d685aa5 in #12335; probably unintentional so deserves a quick fourslash test.
