### ISSUE TITLE
Method inferred as property for inheritance and method overrides

### ISSUE THREAD

**Issue by panthus** [Microsoft/TypeScript#11512]
**TypeScript Version:**  2.0.3

**Code**

``` ts
class Animal {
    public getA(a: Animal) { }
}

class Cat extends Animal {
    public x: Cat[];
    public getA(a: Cat) { }
}

class Dog extends Animal {
    public getA(a: Dog) {}
}

let x: Cat | Dog;
// Inferred type: (property) getA: ((a: Cat) => void) | ((a: Dog) => void)
x.getA(new Animal()); // Error
```

**Expected behavior:**
Matching method overload is selected.

**Actual behavior:** 
The method is inferred to be a property if subclasses have a different signature.

**Comment by isiahmeadows** [comment]
Seems working as intended. It's unsafe to elevate those, because `((a: Cat) => void) | ((a: Dog) => void)` are two incompatible types. If `x` is in fact a `Cat`, you would want `x.getA(dog)` to be a compile-time error, and similarly, if `x` is a `Dog`, you'd expect the same with `x.getA(cat)`. The function incompatibility is why you need to narrow it first (there's no overload here because the types don't intersect).

**Comment by RyanCavanaugh** [comment]
Duplicate #7294
