### ISSUE TITLE
Optimizing Compiler

### ISSUE THREAD

**Issue by lbguilherme** [microsoft/TypeScript#1151]
See: https://typescript.codeplex.com/workitem/1542 by [danieljsinclair](https://www.codeplex.com/site/users/view/danieljsinclair)

> I would like to see TypeScript become a fully fledged optimizing compiler producing minified, but optimized JavaScript code similar to what the Google Closure compiler does. 
> 
> See [discussion thread](https://typescript.codeplex.com/discussions/445557)
> 
> In the same way we don't write ASM anymore, and we don't care if it's readable, we just want the smallest, fastest, most efficient JS code without optimizing coding practices at editing time. The compiler should take care of that. 
> 
> I'm like with the near 1:1 JS output in developer mode, but as we have .map files now, and we minify for production anyway I don't think it's that important. I want to stop worrying about writing small functions and using var instead of const (where the compiler could introduce a literal in the output). I want it to optimise my const string 'tables' and concatenation. I want it to remove unnecessary/unused code, etc. 
> 
> I'd like to see all this from the TypeScript compiler, without stringing together all the other technologies in my build.

---

> I think the main issue is that true JavaScript doesn't have enough type information even by way of inference for a post-build step to achieve suitable optimization. I know that Java and .Net optimize at run time but C++ doesn't. C and C++ compilers like many others that don't produce type information need to optimize and compile time because that's where it's best.
> 
> I think TypeScript in this case falls into the C++ category because most of the type information is lost when it's turned into JavaScript and therefore true optimization can only be done well by the TS compiler.
> 
> Furthermore, a TypeScript project can be compiled as a unit rather than as an individual set of JS files. As such even things like removal of unused code is possible. Others have commented on the discussion thread that this is difficult for shared libraries which simply isn't true since the TypeScript project can consider and compile a series of TS files and produce a single output containing just the code it needs, whether one or multiple outputs.
> 
> The C++ compiler can optimize the output binary if it's working with the source files directly, but you wouldn't expect the same level of optimization of you only called into DLLs. Similarly, if you only consider the post-typed JavaScript for optimization you can't achieve optimal results.

**Comment by jslegers** [comment]
Why was this issue closed?

Personally, I don't see much of a benefit of using TypeScript instead of JavaScript. Especially now that the ES6 standard also added class-based object-oriented programming to the language, all you'd really get from adopting TypeScript today would be the addition of static typing... and interfaces. Besides making your code look more like eg. Java code, I really don't see the benefit at all... except when using static typing to optimize the JavaScript code it produces... which is where asm.js comes in.

In environments where high performance is essential (eg. 3D rendering in the browser for browser games or GIS web apps), the current approach is to write the core code (that does the heavy lifting) in C/C++ (compiled to asm.js) and everything else in JavaScript. That means you need a really good understanding of both JavaScript (which I do) and C/C++ (which I don't) to be able to write proper code or maintain existing code for such apps.

How great would it be to be able to use one - TypeScript - codebase for such projects and compile to asm where possible and to regular JavaScript where not possible? Or to put it differently : how great would it be for a JavaScript programmer to be able to program in highly readable superset of JavaScript and have it compiled - where possible - to a highly optimized subset of JavaScript?

It seems like a win-win for everyone, really, especially if you leave it optional whether or not to compile to asm.js for developers who don't work in high performance environments and prefer readability to performance.

IMO, compilation of (a subset of) TypeScript to asm.js would be **major** improvement over TypeScript as it exists today. For me, it would totally be a game changer and make the difference between supporting and not supporting the adoptation of TypeScript at the company I work for...

**Comment by kitsonk** [comment]
> Why was this issue closed?

The person who raised it, closed it almost 3 years ago.  That is why it is closed.

**Comment by jslegers** [comment]
@kitsonk I noticed. That question was actually specifically directed toward @lbguilherme, although I guess that wasn't obvious.

Either way, those also interested in converting staticly typed variations of JavaScript to asm.js, WebAssembly or C might want to take a look at [ThinScript](https://github.com/evanw/thinscript) or [TurboScript](https://github.com/01alchemist/TurboScript). 

ThinScript compiles to JavaScript, WebAssembly, and C. TurboScript compiles only to JavaScript and WebAssembly.

Both languages have been inspired by TypeScript.

I'd like to thank @RReverser for pointing me in the direction of these two languages.
