### ISSUE TITLE
Self import compilation check

### ISSUE THREAD

**Issue by Alx101** [Microsoft/TypeScript#11552]
**TypeScript Version:**  1.8.10
Create two classes. Import class a in class b, and class b in class a.

**Expected behavior:**
Compilation error, import loop.

**Actual behavior:** 
No compilation error. Runtime error about missing classes.

**Comment by kitsonk** [comment]
Most loaders (including the specification for the [ES Module loader](https://whatwg.github.io/loader/)) can handle circular dependencies like this.  Because you can do two pass static analysis of these modules, the shape of the module can be determined before the factory.

My opinion of trying to bake all that logic into TypeScript is challenging and this type of issue is actually hard to determine if it would be a runtime issue statically, therefore I think TypeScript should not error in these situations.

**Comment by Alx101** [comment]
Perhaps a warning or something similar? Because obviously from my tests it generates code that will crash.

**Comment by kitsonk** [comment]
> Perhaps a warning or something similar?

There are no such things at warnings in TypeScript.  There are either errors or errors and depending on the module loader used, it may or may not be an error.  That is why we test our code!

**Comment by Alx101** [comment]
Alright. Consider this closed then.
