### ISSUE TITLE
Find references doesn't work with default exports when importing with a different name

### ISSUE THREAD

**Issue by use-strict** [Microsoft/TypeScript#11551]
**TypeScript Version:**  2.0.3

**Code**

``` ts
// A.ts
export default class A {
}

// B.ts
import AA from './A'; // <----Imported as AA instead of A

```

**Expected behavior:**
Find all references on class A finds the usage in B.ts
**Actual behavior:** 
No references are found

**Comment by mjbvz** [comment]
This limitation is going to being especially noticeable when using the new VSCode references code lens: https://github.com/Microsoft/vscode/pull/18205 

@waderyan FYI, we probably need to prioritize a fix for this, so let's make sure we talk about this at our next meeting

**Comment by waderyan** [comment]
Noted.

**Comment by aluanhaddad** [comment]
I have an additional suggestion. If it happens to be a locally anonymous `default` class or function it would be great to have find all references be a valid action to perform on the `default` keyword itself. Right now I sometimes add names to `default` exports when I otherwise wouldn't just in order to make find references work. This doesn't feel right because the identity should come from the module, not the name.
