### ISSUE TITLE
TSServer: compilerOptionsForInferredProjects doesn't support specifying include and exclude rules

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/TypeScript#11554]
**TypeScript Version:**  2.0.6-insider

The request should allow specifying all valid attributes of a tsconfig.json / jsconfig.json. Especially exclude is usefully to exclude node_modules and other folders by default.

**Comment by mhegazy** [comment]
Inferred projects do not include all files in a folder. The files in an infered project are "infered" from imports and triple-slash references. And since there is no way to infer compiler options, you get this command.

I would say what you are looking for is openfolder command, this is something we have now, and I would like to know if openextetnalptoject is sufficient for your use cases or not before exploring this.

**Comment by dbaeumer** [comment]
Actually, I would like to avoid manage external projects for that case since my understanding is that I have to manage everything myself then. Especially it is unclear to me what will happen if the user later on adds a tsconfig.json file. Will that be ignore. Do I have to close the external project and the reopen all files.

What I would like to have is the following: if we open a folder without a tsconfig.json file the folder is treated as one project with a 'virtual' tsconfig.json file at its root for which we provide the settings. So the tsserver should load all ts files in the workspace.

**Comment by mhegazy** [comment]
>  Especially it is unclear to me what will happen if the user later on adds a tsconfig.json file. Will that be ignore. Do I have to close the external project and the reopen all files.

tsconfig.json files should take precedence.


> What I would like to have is the following: if we open a folder without a tsconfig.json file the folder is treated as one project with a 'virtual' tsconfig.json file at its root for which we provide the settings. So the tsserver should load all ts files in the work space.

that is what the external project does, except that you have to tell the server which files should be included explicitly as well.

**Comment by dbaeumer** [comment]
>that is what the external project does, except that you have to tell the server which files should be included explicitly as well.

But that requires that we fully manage the project which is IMO not the business VS Code should do since we will end up in a catchup game with the server. For example if new tsocnfig.json settings are added.

**Comment by RyanCavanaugh** [comment]
Seems like you guys should have a Skype meeting?

**Comment by mhegazy** [comment]
we should add a new command to `openFolder` then.

**Comment by mhegazy** [comment]
After talking to @kieferrm  about this, openFolder does not seem to be what is needed. A proposal is to add a `workspaceRoot` in the openfile command. when the server opens the file, it will do its normal walk to find a tsconfig.json/jsconfig.json, if one was found, then a configured project is created as normal. if none was found, then create a pseudo-configured project with root at the `workspaceRoot`. The default options would be that of the infered project; if the user wants to set different options they need to define a jsconfig.json/tsconfig.json

@vladima and @zhengbli what do you think?

**Comment by zhengbli** [comment]
Previously if you open two files in a folder, two separate projects will be created so that they won't conflict in the global namespace. Now with the new "pseudo-project", I suppose only one project will be created? Then each file will see the other file by default, which is a breaking change in behavior, though it might be more intuitive IMO.
