### ISSUE TITLE
ES6 methods don't work with typescript syntax check

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#11621]
_From @m3l7 on October 11, 2016 14:36_

- VSCode Version: 1.6
- OS Version: fedora 23

my current tsconfig.json is

      {
          "compilerOptions": {
              "target": "es6",
              "module": "commonjs",
              "sourceMap": true,
              "outDir": "src",
              "typeRoots": ["./typings/modules", "./typings/globals"]
          },
          "include":[
              "src/**/*"
          ]
      }

let's say I have this:

      Object.assign({});

if I compile the project with tsc --lib es6 or with a gulp task, it works correctly. However, vscode syntax check gives: 

      [ts] Property 'assign' does not exist on type 'ObjectConstructor'

_Copied from original issue: Microsoft/vscode#13514_

**Comment by waderyan** [comment]
_From @m3l7 on October 13, 2016 11:27_

the same happens with Promise

**Comment by waderyan** [comment]
@m3l7 thank you for opening this issue. I have confirmed this happens with the latest bits. This is a language service issue. Moving to that repo. 

![image](https://cloud.githubusercontent.com/assets/2449568/19390403/d40f6d80-91dc-11e6-9a63-dbcb89b17977.png)

**Comment by mhegazy** [comment]
The issue here is that the tsconfig.json as listed above includes no files. The include list includes `"src"`, but then the output directory is `"src"` as well. the compiler does not want to recompile the files it outputted last cycle, so it excludes the output directory by default. so the net results is no files to compile..


To solve this either:
- use a different outDir 
- Do not set `outDir` at all, by default a `.js` file is emitted next to its source `.ts` file
- add an empty `"exclude": []`

**Comment by mhegazy** [comment]
I have logged https://github.com/Microsoft/TypeScript/issues/11650 to track showing an error message if the compilation included no files.

**Comment by m3l7** [comment]
sorry for the late reply.
not setting an outDir seems to fix. However, setting an outDir different from include array results in the debugger failing to start. (Cannot launch program 'api.ts'; setting the 'outFiles' attribute might help.')
But this seems like a different issue
