### ISSUE TITLE
number & { __brand } is not working with the comparison operator in nightly build

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#11643]
```typescript
declare var x: number & { __brand: any };
x > 0 // <-- [ts] Operator '>' cannot be applied to types 'number & { __brand: any; }' and '0'.
```

**Comment by aozgaa** [comment]
The error first appeared in a63a0d89817dec90d06fd233b2a9ef11699ce442.

**Comment by aozgaa** [comment]
Hey Aleksey,

This ties into an ongoing discussion about what we think about the use/addition of nominal types in our type system. There is a [long list of issues](https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=is%3Aissue%20nominal) related to nominal types.

It looks like this feature is actually working as designed, though the behavior is admittedly a bit counter-intuitive at first glance. Based on the recent addition of the comparability relation (issue #5517), specifically [here,](https://github.com/Microsoft/TypeScript/pull/5517/files#diff-c3ed224e4daa84352f7f1abcd23e8ccaL5690) x isn't comparable to '0' because '0' is a numeric literal, and thus a subtype of 'number'. Here are two workarounds (inspired by your comment [here](https://github.com/Microsoft/TypeScript/issues/202#issuecomment-50199713) :) ):

```
type BrandedNum = number & { __numberBrand: any };

declare var x : BrandedNum;
x > 0; // error: 0 is of numeric literal '0', a subtype of number
x > <number>0; // okay
x > <BrandedNum>0; // okay, in my opinion the clearest
```

In fact, this should be a general solution for dealing with "nominal typing" via brands: upcasting the *other* argument to a comparison operation to that of the two types' common ancestor will make the comparison pass our type check.

**Comment by aleksey-bykov** [comment]
interesting, i will consider that
