### ISSUE TITLE
Typescript tools for Visual Studio 2015 - requires restart.

### ISSUE THREAD

**Issue by MrChriZ** [Microsoft/TypeScript#11747]
**Expected behavior:**
I've just installed TypeScript for Visual Studio 2015.  On completion it tells me it needs to restart the entire system.  What ever for?!

**Actual behavior:** 
![system restart](https://cloud.githubusercontent.com/assets/3593276/19553357/d2948994-96ab-11e6-84ef-c34f4cbf23c4.png)

**Comment by paulvanbrenk** [comment]
Can you upload all the `*typescript*` log files in `%temp%`

**Comment by tylerjgarland** [comment]
This is the beta correct? Try 2.0.3.

**Comment by MrChriZ** [comment]
[dd_TypeScript_Dev14_20161020095157_000_TypeScript_Dev14.msi.zip](https://github.com/Microsoft/TypeScript/files/545315/dd_TypeScript_Dev14_20161020095157_000_TypeScript_Dev14.msi.zip)

So the Beta restarted my machine.  I found the release 2.0.3 version about 10 minutes later and that didn't require a restart but I don't know if that was just because my machine had been restarted 10 minutes earlier.

**Comment by paulvanbrenk** [comment]
Thanks, looking at the logs it looks like there was still an instance of either VS or MSBuild running, which required the reboot. (This could be an orphaned instance due to a crash). We try to kill them, but that doesn't always work.

If we don't reboot in that case you could end-up with a mix of TypeScript versions, which would be a bad experience.
