### ISSUE TITLE
Querying Enums with a variable of type string throws error TS7015

### ISSUE THREAD

**Issue by Thinkscape** [microsoft/TypeScript#11773]
**TypeScript Version:** 2.1.0-dev.20161010
**Code**

``` ts
enum Fruit {
  Banana,
  Apple
}

console.log( Fruit[Fruit.Banana] );  // this works fine
console.log( Fruit["Banana"] );      // this too

const nameOfApple : string = 'Apple';
console.log( Fruit[ nameOfApple ] );
// error TS7015: Element implicitly has an 'any' type because index expression is not of type 'number'.

console.log( Fruit[ nameOfApple as string ] );  
// error TS7015: Element implicitly has an 'any' type because index expression is not of type 'number'.
```

**Expected behavior:**
From the docs:

> In generated code an enum is compiled into an object that stores both forward (name -> value) and reverse (value -> name) mappings. References to enum members are always emitted as property accesses and never inlined.

There should be no error message.

**Actual behavior:** 

> error TS7015: Element implicitly has an 'any' type because index expression is not of type 'number'.

**Comment by mhegazy** [comment]
Here is how this enum would be emitted:

```js
var Fruit;
(function (Fruit) {
    Fruit[Fruit["Banana"] = 0] = "Banana";
    Fruit[Fruit["Apple"] = 1] = "Apple";
})(Fruit || (Fruit = {}));
```
Enum names can not be numeric constants. as a result indexing into an enum with a numeric value, or enum, is guaranteed to return a string.

However, indexing with a string can either result in a number, e.g. `Fruit["Apple"]` but it can also result in a string, if the string has a numeric value, e.g. `Fruit["0"]`. 

You can argue that it should be `number | string | undefined` instead of `any`. but this was the behavior before TS 1.5 when union types were added.
