### ISSUE TITLE
spread operator as arguments and optionals + REST in function parameters throws error

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#11780]
**TypeScript Version:**  2.0.3 

**Code**

``` ts
function foo(a?: number, ...args: number[]) {}
foo(...[1,2,3]); // error

var args = [1, 2, 3];
console.log(...args); //error 

```

**Comment by aluanhaddad** [comment]
Your program has an error, it is calling `foo` with arguments that literally do not match the signature. The same is true about the call to `console.log`.  An optional argument does not merge with a rest argument of a compatible element type because it is a syntactic feature and the parameters are passed by position. How can we distinguish the arguments and refer to them in the body of foo without this behavior?

The correct way to call foo by spreading `...args` into the second parameter is
```TypeScript
foo(undefined, ...args);
console.log(undefined, ...args);
```

**Comment by Draccoz** [comment]
I've got a bit similar issue, basically, spread arguments do not translate to multiple arguments.
```
function test(reg: RegExp, str: string) {
  console.log("abc".replace(reg, str));
}
test(...[ /b/, "d" ]); // TS2346:Supplied parameters do not match any signature of call target.
```
```
function test(...args);
function test(reg: RegExp, str: string) {
  console.log("abc".replace(reg, str));
}
test(...[ /b/, "d" ]); // works fine
```

Pretty annoying, as in pure ES6 it works perfectly :(.

**Comment by FremyCompany** [comment]
I had the same issue when trying to wrap console.log(). 

```
log = function(...args) { console.log(...args) } // typing error here :(
```
for reference console.log is defined as
```
Console.log(message?: any, ...optionalParams: any[])
```
So my code is correct from the type point of view.

**Comment by FremyCompany** [comment]
How is that a question? Perfectly valid ES6 code throws an error in TypeScript. That's a bug, no a feature.

**Comment by mhegazy** [comment]
your correct, relabeling. the issue is tracked by https://github.com/Microsoft/TypeScript/issues/5296

**Comment by FremyCompany** [comment]
:+1:
