### ISSUE TITLE
Changes to tsconfig.json not picked up 

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#11803]
``` ts
// a.ts
Symbol.iterator;
```

``` json
{
    "compilerOptions": {
        "lib": [
            "es5",
            "dom"
        ]
    }
}
```
1. open 'a.ts', there should be an error for missing `Symbol` definition
2. change `lib` in tsconfig.json to include `es6`, and save
3. make an edit in `a.ts`. expect the error to go away

Actual:

Error does not go away, closing and reopening the file does.

Expected:

Error goes away on next refresh.

**Comment by mhegazy** [comment]
@vladima can you take a look.

**Comment by vladima** [comment]
cannot repro on the latest master, is there anything else I need to do?

**Comment by mhegazy** [comment]
nope. i repro'ed this on 2.0.6

**Comment by stijnherreman** [comment]
@mhegazy Were you able to verify yourself that the issue was fixed?

I can repro this with VS 2017 Update 2. Changes to `tsconfig.json` are not picked up until I close and reopen `main.ts`.

**tsconfig.json**
```json
{
  "compileOnSave": true,
  "compilerOptions": {
    "outDir": "../../wwwroot/js",
    "removeComments": false
  }
}
```

**main.ts**
```ts
export class Main
{
    // test comment
    constructor() {
        console.log("inside constructor");
    }

    foo(): void {
        console.log("inside foo");
    }
}
```

Changing the value of `"removeComments"` doesn't have any effect on the output until I've closed, reopened and re-saved the source file.

**Comment by mhegazy** [comment]
Looks fixed in Update 3. give it a try.
![animation](https://user-images.githubusercontent.com/8000722/26896661-71437432-4b7a-11e7-9eb7-0979c3d3839b.gif)
