### ISSUE TITLE
'Point' only refers to a type, but is being used as a value here.

### ISSUE THREAD

**Issue by gorshkov-leonid** [Microsoft/TypeScript#11807]
**TypeScript Version:**  2.0.3 / nightly (2.1.0-dev.201xxxxx)

**Code**
```ts
//first.d.ts
declare module 'leaflet' { 
   export type Point = { //same result will be with    "export interface Point { constructor()..." too

        new(lat:Number, lng:Number):Point;
        clone(): Point;
  }
}
//second.ts
import {Point} from "leaflet" //i check constants from this module are visible but exist error with usage of imported type

new Point(1,2)
```
**AR:**
error with ts 2.0.3: Cannot find name 'Point'.
error with ts 2.1.0-dev.20161023: 'Point' only refers to a type, but is being used as a value here.

**Comment by DanielRosenwasser** [comment]
You need to have something to actually *make* a point. A type on its own just refers to the shape of a value. What you probably meant to write was something like this

```ts
export interface Point {
    // ...
}

export interface PointConstructor {
    new (lat: number, lng: number): Point;
    clone(): Point;
}

export var Point: PointConstructor;
```

or simpler:

```ts
export class Point {
    // members

    constructor(lat: number, lng: number);
    clone(): Point;
}
```

Also, notice I used lowercase `number` instead of `Number`, which is a common gotcha for beginners.

**Comment by gorshkov-leonid** [comment]
Thank you, it is work and thank you for advice about Number!  Now the idea is clear.  
I could not find explained information about typings in official documentation: case with obtained read-only object(interface),  object construction(class),  static methods, 'type' usage, may be best practises.  And probably it is primitively but message is confusing... 
May be do you have some links?

And can you validate it can be simplified?:
```ts
declare module 'leaflet' {
    export type Leaflet = {
        Point: PointStatics, //i want to describe type Point : Class<Point>(as in java) as factory of objects
   }

   type PointStatics =       {
        new(lat:Number, lng:Number):Point;
   };

   export class Point {
        constructor(lat:Number, lng:Number); //PointStatics can be mixed in?
        clone(): Point;
        ....
   }
}

require(['leaflet'], function (L:Leaflet) {
    new L.Point(1,2)
}
```

**Comment by aluanhaddad** [comment]
@gorshkov-leonid what you have is not correct

You can read about authoring declaration files from the [TypeScript Handbook](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html)

But are you trying to write declarations for Leaflet as an exercise because if definitely-typed has a number of declaration files for Leaflet. You could `npm i @types/leaflet` or user another package manager or simply download the files manually as needed.

I will say that when I last worked with leaflet, around 6 months ago, the available typings left a lot to be desired. Leaflet is also interesting as it offers both [factory](https://github.com/Leaflet/Leaflet/blob/master/src/geometry/Point.js#L184) and [class](https://github.com/Leaflet/Leaflet/blob/master/src/geometry/Point.js#L21) style APIs, but typing them is still quite doable and a good exercise.

Assuming you want to write these yourself here are a few pointers.

```typescript
export class Point {
        constructor(lat:Number, lng:Number);
        clone(): Point;
}
```
as @DanielRosenwasser noted you absolutely should _not_ use `Number` as a type annotation you must use `number` instead. That is
```ts
  constructor(lat: number, lng: number);
```
Moving on,
```ts
export type Leaflet = {
  Point: PointStatics
```
it looks like you are trying to describe the shape of the leaflet module. For this you should use a `namespace` and a UMD style declaration.
```ts
// for consumers of Leaflet via it's global.
export as namspace L;

// for consumers of Leaflet using modules
declare module 'leaflet' { export = L; }
// This could be called anything, it is exported under a different name.
namespace L {
  export class Point {
      constructor(lat: number, lng: number, round?: number);
      clone(): Point;
      // add, destory, scale etc...
  }
  // factory function providing flexible options for creating a Point.
  // arguments may be either an x and a y coordinate followed by an optional rounding value 
  // or an array of two numbers, [x, y] followed by an optional rounding value
  // or an object containing an x and y properties followed by an optional rounding value.
  // or an existing Point which will be returned as is.
  export function point(x, y, round?: number): Point;
  export function point(coords: [number, number] | {x: number, y: number}, round?:number): Point;
  export function point(point: Point): Point;
}
```
Not that I have omitted JSDoc comments for brevity and that I wrote these type declarations based on reading the Leaflet's source code for Point which you can find at https://github.com/Leaflet/Leaflet/blob/master/src/geometry/Point.js.

**Comment by gorshkov-leonid** [comment]
@aluanhaddad thank you for the many ways. But closer to my case I do not understand how to merge declaration  http://leafletjs.com/reference-1.0.0.html#class into @types/leaflet. How to create reference to inherited static context (Marker -|>-Class{static addInitHook}) and use it as `Marker.addInitHook(...)`? It is impossible override 'interface' declaraton to 'class' without duplicates?

**Comment by aluanhaddad** [comment]
Are you saying you want to override the static side of a class using a derived class?

**Comment by gorshkov-leonid** [comment]
oops! I think classes and what I want - different things. Plugin in leaflet use feature with inject functionality to constructor. 
```
MyClass.addInitHook(function () {
    // ... do something in constructor additionally
    // e.g. add event listeners, set custom properties etc.
});
```
I just wanted to make this code look similar in typescript.

**Comment by mazorvanunu** [comment]
this is so icky, clearly a "constructor" is a reference and at best - its a function reference
please stop this React style of adding a bunch of stuff people do not like and find very confusing (and at distant times amusing)
what if i wanted to use it as a value? (which its clearly is, even by strictly looking at typescript instance\reference model...)
guys you are doing great work, honestly, amazing but this is a nuance which only gives more complexity for the code and at the same time does not help (at all) for your fantastic meta-documentation style of scripting

its simply nonsense

**Comment by shihua-guo** [comment]
In my case.It seem is the file name cause the error. So I change the file name.
example:I change "legend" to "command-legend".  It works!

**Comment by d-damien** [comment]
Then how does one make those proper type checks as in @DanielRosenwasser answer, but with multi types ?

``` js
type Geometry = Point | Shape
```
