### ISSUE TITLE
Debug Failure. False expression: start must be non-negative, is undefined

### ISSUE THREAD

**Issue by nmehlei** [microsoft/TypeScript#1182]
Out of nowhere, this error message started to appear constantly in my TS-heavy solution:

Debug Failure. False expression: start must be non-negative, is undefined
from File VSTSC

Invoking msbuild from the command line, I got a bit more, but not that helpful either:

VSTSC : tsc.js(2426, 17) JavaScript runtime error : Debug Failure. False expression: start must be non-negative, is undefined [C:\MyProject.csproj]
VSTSC : tsc.js(2426, 17) JavaScript runtime error : Debug Failure. False expression: start must be non-negative, is undefined [C:\MyProject.csproj]

It won't give my any more details than that. I can't be sure, but it doesn't really seem to be related to a specific code change either, since I tried to isolate it by going back in my version control system (VS Online) which sometimes worked but the error always returned after making (even trivial) changes.

I am using VS 2013 with Update 4 and TS 1.3 successfully for days and did not install or change anything today which could explain this. If I understood the code correctly, the part of tsc.js that could result in those errors seems to be related to file diagnostics, so that could explain why it doesn't seem to be directly related to code changes from my side.

This issue is very critical for us as it's effectively blocking further development.

**Comment by rasmuffin** [comment]
Just as a follow up on this issue.  I received this error after installing the jquery.TypeScript.DefinitelyTyped nugget package (v2.1.9).  Turns out that the jquery.d.ts file is encoded in 'Western European (Windows) - Codepage 1252'.  After updating the file to UTF-8 the error message disappeared.  I also uninstalled the package, re-installed it and even though the encoding reverted back to the 'Western European (Windows) - Codepage 1252' encoding I am no longer receiving the error.  Weird.

**Comment by DanielRosenwasser** [comment]
@rasmuffin you may want to file a separate issue since that sounds unrelated. Sorry about the delay, it's easy for comments on closed issues to fall off our radar.

**Comment by aleks091** [comment]
The solution of changing the file Encoding to UTF-8 fixed this issue for me as well. Thank you very much @nmehlei

**Comment by CedricOrcellet** [comment]
As a work around for those who have this problem (VS2013 TS 1.4) modifying a file of the project and using "Build" instead of "Rebuild" did allowed us to avoid this error message. It's a hack but it work for us until we find the real origin.

**Comment by AdamTReineke** [comment]
Since I'm stuck on 1.4, saving the file as UTF-8 fixed this for me. Attached screenshots from Visual Studio for using Save As to change the encoding for those who need them (since this bug is the first result on search results for the error string).

![save-with-encoding](https://cloud.githubusercontent.com/assets/518655/10204248/81377ef6-676f-11e5-9229-9bd63e32d1d8.png)
![save-with-encoding-2](https://cloud.githubusercontent.com/assets/518655/10204247/81366b2e-676f-11e5-8155-9e1c81d5d5ee.png)
