### ISSUE TITLE
Writing Definition Files for existing JS Files 

### ISSUE THREAD

**Issue by raybooysen** [Microsoft/TypeScript#11824]
**TypeScript Version:**  2.0.3

Consider the following:

```
//  ./lib/core/file1.js
export class Foo {}
```

```
// file2.ts 
let foo = require('./lib/core/file1');
```

In the code above, consider the case where we are migrating a large code base from JS to TS.  File1.js may be very large and easier to write a definition file than convert it.  

If I write the definition file, where do I put it?  How do I tell tsc that the file1.d.ts is the definition file for file1.js?

**Comment by mhegazy** [comment]
Whenever possible, keep the defalcation file close to the corresponding `.js` file. for instance, if this is a node module, make sure the package has both. if this is a local file, put them next to each other.

For modules names, the TS compiler tries to follow the node resolution logic to find the module, then it looks for `.ts` or `.tsx` or `.d.ts` in the same location.

So for this example:

```ts
//  ./lib/core/file1.d.ts
export declare class Foo {}
```

The only change on the usage is to use `import` instead of `var`:

```ts
// file2.ts 
import foo = require('./lib/core/file1');
```

or 

```ts
// file2.ts 
import {foo} from './lib/core/file1';
```

More details about declaration file authoring is available in http://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html. Hope this helps.

**Comment by raybooysen** [comment]
Thanks @mhegazy, much appreciated.
