### ISSUE TITLE
Typescript version 2.1.0-dev.20161025 has require regression

### ISSUE THREAD

**Issue by johnnyreilly** [Microsoft/TypeScript#11834]
Hi,

I'm a maintainer of [ts-loader for Webpack](https://github.com/TypeStrong/ts-loader/).  We've just noticed that out [simpleDependency test](https://github.com/TypeStrong/ts-loader/tree/master/test/execution-tests/simpleDependency) has started failing consistently on [Windows](https://ci.appveyor.com/project/jbrantly/ts-loader/build/1.0.764) and [Linux](https://travis-ci.org/TypeStrong/ts-loader/builds/170457020) 

**TypeScript Version:**  2.0.3 / nightly (2.1.0-dev.20161025)

**Code**

Take a look here for the PR on which I noticed the issue: https://github.com/TypeStrong/ts-loader/pull/337

And look here for the Karma test that demostrates the issue: https://github.com/TypeStrong/ts-loader/tree/master/test/execution-tests/simpleDependency

**Expected behavior:**

Test passes with TypeScript@latest (as with TS 1.6 - 2.0)

**Actual behavior:** 

Test fails with TypeScript@latest (despite passing for other versions of TS)

**Comment by mhegazy** [comment]
In https://github.com/TypeStrong/ts-loader/blob/master/test/execution-tests/simpleDependency/tsconfig.json#L4 the `files` list is empty. this means no files are consumed by the compiler. 

In past versions the compiler silently finished with a non-error return code (as there is no work to be done). This has been confusing to users who wounder why output files were not generated (see https://github.com/Microsoft/TypeScript/issues/11621 and https://github.com/Microsoft/TypeScript/issues/11156).

In https://github.com/Microsoft/TypeScript/pull/11743 we made this an error, so that users are aware that the compilation they ran was a no op.

**Comment by johnnyreilly** [comment]
Ah - I see. Thanks. I'll fix up our test pack to cater for that.  I've just realised that this creates a small problem for ts-loader with regards our [instance test](https://github.com/TypeStrong/ts-loader/tree/master/test/comparison-tests/instance).  i.e. ts-loader was relying on the noop to not error.  Now it will; I think we already have an issue raised around this:

https://github.com/TypeStrong/ts-loader/issues/268

and possibly related: 

https://github.com/TypeStrong/ts-loader/issues/267
