### ISSUE TITLE
Do not emit `/// <reference types=".." />` for augmented declarations in dependencies

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#11849]
```ts
/// <reference types="node" />
interface I {
    e: Error;
}
```

```sh
> npm install @types/node

> tsc --d a.ts

> type a.ts

/// <reference types="node" />
interface I {
    e: Error;
}
```

`Error` should not be cause a type dependency as it partially came from `lib.d.ts`

**Comment by jayphelps** [comment]
RxJS member here, any ideas how we can work around this as a library author, so our users don't have to? (we we wait for 2.1.1) https://github.com/ReactiveX/rxjs/issues/2112 It looks like we misunderstand what the real problem is--we thought we fixed it in https://github.com/ReactiveX/rxjs/pull/2120 but turns out we didn't.

**Comment by mhegazy** [comment]
you can strip out the `/// <reference types ... />` from the resulting .d.ts files, wouldn't this be sufficient?

**Comment by jayphelps** [comment]
@mhegazy oo just go in by hand and remove them from the artifacts, before we publish? A crude but hilariously effective solution.

**Comment by mhegazy** [comment]
you just need a regex.

**Comment by mhegazy** [comment]
alternatively 2.1 RC should have the fix for the issue.

**Comment by rightisleft** [comment]
Sadly using @jayphelps approach to fixing this bug until next RC ....
