### ISSUE TITLE
Typescript compiler not detecting Immutable.js iterator in for of loop

### ISSUE THREAD

**Issue by linusnorton** [Microsoft/TypeScript#11921]
**TypeScript Version:**  2.0.3

**Code**

```ts
import {Map} from "immutable";

const m = Map({ a: 1 });

for (const [key, value] of m) {
    console.log(key, value);
}
```

**Expected behavior:**

`a 1`

**Actual behavior:** 

```
TSError: ⨯ Unable to compile TypeScript
src/test.ts (6,28): Type must have a '[Symbol.iterator]()' method that returns an iterator. (2488)
```

**ES6 example:**

```
const Immutable = require( "immutable");

const m = Immutable.Map({ a: 1 });

for (const [key, value] of m) {
    console.log(key, value);
}
```

**Output:**

`a 1`

**Extra notes:**

I have also tried `m.entries()` and `m.entrySeq()` all produce the same error.

**Comment by kitsonk** [comment]
This isn't a TypeScript issue.

The interfaces for [ImmutableJS](https://github.com/facebook/immutable-js/blob/master/dist/immutable.d.ts#L1707) do not specify a `[Symbol.iterator]()` that returns an iterator.  This is likely because the definitions are only designed to work when ES5 is targeted.  ImmutableJS would need to provide additional typings that add the appropriate interfaces to properly represent the library when running under ES6 and targeting ES6.
