### ISSUE TITLE
Resolve conflict during rename

### ISSUE THREAD

**Issue by Peter-Juhasz** [microsoft/TypeScript#1196]
Resolve name resolution conflicts during a rename session just like Roslyn for C#/VB does. Identifiers can have a different meaning before and after a rename refactor. And in some very special cases the errors can not be identified instantaneously, only at runtime.

By the way, the new rewritten language service is really cool, using Roslyn was an excellent choice, very well done!

**Comment by fantaclaus** [comment]
Could you please schedule this issue to a milestone as soon as possible?

This issue is really critical because it makes the `rename` feature insecure and risky. We already had troubles with it in the production code (see issue #17670).

Also I think it should have the `bug` label as well.

Thanks in advance.

**Comment by RyanCavanaugh** [comment]
We're transitioning to LSP so this functionality can be provided in a language-agnostic way
