### ISSUE TITLE
Lambda syntax different between returning primitive and returning object

### ISSUE THREAD

**Issue by Jameskmonger** [Microsoft/TypeScript#11964]
**TypeScript Version:**  2.0.3 / nightly (2.1.0-dev.201xxxxx)

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
const fn_prim = () => 3;
const fn_obj = () => {
    val: 3
};
```

**Expected behavior:**
I expect it to compile fine. `fn_prim` should return 3 when called, `fn_obj` should return `{ val: 3 }` when called.

**Actual behavior:** 
"Unused label" error on `val:`

**Comment by vladima** [comment]
TypeScript follows ES spec and per [spec](https://tc39.github.io/ecma262/#sec-arrow-function-definitions) your second example is an arrow function where body is a [function body](https://tc39.github.io/ecma262/#prod-FunctionBody) wrapped in `{` `}`. In order to make it an arrow function that returns an object literal you'll need to wrap it in parens:
```js
const fn_obj = () => ({
    val: 3
});
```
