### ISSUE TITLE
No error when using uninitialized value in noImplicitAny & strictNullChecks mode

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#12002]
From `master` as of right now (`7b34b612beda66b0812462a3feeabc63852cd842`)

```ts
var x;
var y = 100 + x;
```

Compile with `strictNullChecks` and `noImplicitAny`

Expected: ***Some*** sort of error for using `x`.
Actual: No error at all?

**Comment by ahejlsberg** [comment]
This is actually by design. Your `var x` is an implicit any variable that is tracked by control flow analysis (#11263). Because it hasn't been initialized, its control flow type in the `100 + x` expression is `undefined`, and the `+` operator permits `undefined` as an operand value. If anything, we should discuss whether the numeric operators should be stricter with respect to `undefined` and `null`, but that's a different discussion.

**Comment by DanielRosenwasser** [comment]
Sure, that issue definitely sounds like something we should look into; is the type of `x` still going to be `undefined` under `noImplicitAny`?
