### ISSUE TITLE
Directives classified as comments

### ISSUE THREAD

**Issue by nicot** [Microsoft/TypeScript#12036]
**TypeScript Version:**  2.0.3

**Code:**

```ts
/// <reference path="core.ts"/>
/// <reference path="diagnosticInformationMap.generated.ts"/>
```

**Expected behavior:**
Directives should be syntax highlighted differently than normal comments.

**Actual behavior:** 
Directives are syntax highlighted as normal comments.

**Justification:**
[Directives](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html) are sufficiently different from normal comments that they should have additional syntax information.
- They have structure (XML)
- They have specific rules
- They can be used to jump to declaration files

I think this would require a change in the [scanner](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/scanner.ts), as opposed to a change in VSCode or the textmate grammar, but I could be wrong.

**Comment by aluanhaddad** [comment]
Try to avoid writing code using these directives unless it is your only option. If you are using modules `core.ts` should be imported as
```ts
import 'core.ts';
```
Otherwise consider maintaining them in a single place like a `references.ts` file or `tsconfig.json`.

This is just my opinion after having migrated a large amount of AMD code that was unnecessarily using the comment syntax /endrant

**Comment by mhegazy** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#348

**Comment by mhegazy** [comment]
seems like a good thing to have. the colorization is driven off the tm grammar in https://github.com/Microsoft/TypeScript-TmLanguage. moving the issue.
