### ISSUE TITLE
Prototype store "this" in a variable problems in lamdas

### ISSUE THREAD

**Issue by biqas** [Microsoft/TypeScript#12072]
**TypeScript Version:**  2.0.7

**Code**

```ts
Array.prototype.someFunction = () =>
    {
        var that = this;
        // that is undefined?!?!
        // do something
    };

Array.prototype.someFunction = function()
    {
        var that = this;
        // that is now correct assigned!
        // do something
    };

```

**Expected behavior:**
The assignment statement should store in "that" variable "this" reference.

**Actual behavior:** 
Variable "that" is undefined.
Lambda function have problems but normal function work fine why?

**Comment by blakeembrey** [comment]
@biqas You can read about arrow functions in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions. Arrow functions use the lexical `this`, which here would be the global. What did you expect it should be? I can't tell from the above snippet why it'd be `undefined` though, unless this is inside another function call under `use strict`.

**Comment by biqas** [comment]
@blakeembrey Actually the problem is not about what the "this" would be, t is more, that you are not to able to store the this in an variable.

**Comment by blakeembrey** [comment]
It works as expected for me. Can you provide more information, especially to the question I asked? What are you expecting to happen? Can you provide a demo or more information to reproduce what you're seeing?

**Comment by biqas** [comment]
I would have expected an instance of an array for "this". What I'm seeing is that the assignment statement is not working. `var that = this;` the value of "that" is "undefined". I forgot to mention that I was debugging in VSCode v1.7.1 with node v4.2.4 and in the node environment im experiencing this.
So giving a second thought it could be that it is a node problem ;)

**Comment by aluanhaddad** [comment]
This is behaving exactly how it's supposed to. Given
```ts
'use strict'; // implicit in modules
Array.prototype.someFunction = () =>
    {
        var that = this;
        // that is undefined?!?!
        // do something
    };
```
The value of `this` is the lexical `this` which is the `this` _outside_ of the function valued property being defined. If this code is at top-level, `this` will be `undefined` under strict mode and otherwise it will be be the global object.

So it makes sense that `that` and hence `that` is `undefined`. 

JavaScript uses dynamically scoped, not lexically scoped, `this` values to allow functions to serve the dual role of methods and free functions. Because you're defining a prototype method it is meant to be bound to the object on which the method is ultimately called and this we need the dynamically scoped `this` and to obtain that we need to use the `function` keyword.

**Comment by blakeembrey** [comment]
As @aluanhaddad said, I'd recommend reading through https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions quickly. Arrow functions are not the same thing as `function` just with a different syntax, they have a different set of features (`this`, `arguments`). That's why I wanted to figure out what you expected `this` to be (maybe you rationally wanted `this === module.exports` in node). In this case, you should be using `function` as it doesn't bind `this` until call time (JavaScript works that "what's to the left of a function at call time is `this`" - unless you previously bound it). That's why things like `var x = [].some; x()` fail in JavaScript.

**Comment by biqas** [comment]
@aluanhaddad The courious thing is, that "this" is exactly not undefined at least in the debugger, the only thing which is not working is the assignment statement. But reading the arrow function docs was also help full thanks @blakeembrey.

**Comment by aluanhaddad** [comment]
@biqas This can be many things depending on context in which the closure is created. 
  
```ts
class C {
  constructor(readonly val: number); 
  // this is, and will always be the instance of `C`.
  fn = x => x * this.val;
}

const c = new C(4);

console.log(c.fn(2)); // prints 8
```
```ts
```ts
'use strict';
var fn = (function (val: number) {
  this.val = val;

  return function (x) {
    return this.val * x;
  };
}(4)); // throws **TypeError: Cannot set property 'val' of undefined**
```
```ts
var fn = (function (val: number) {
  this.val = val;

  return function (x) {
    return this.val * x;
  };
}(4));
console.log(fn(2)); // prints NaN
```

**Comment by yortus** [comment]
@biqas I think I've seen the problem you mention with the V8 debugger, which sometimes shows an incorrect value for `this` when stepping through code. I haven't investigated it further so far, but I do believe you may have been mislead by the debugger, even though the runtime behaviour of V8 is exactly as described by the other comments here.
