### ISSUE TITLE
Incorrect type narrowing when treating a union type as an array

### ISSUE THREAD

**Issue by DavidKDeutsch** [Microsoft/TypeScript#12073]
**TypeScript Version:**  2.0.3 

In the below code, the variable `shouldBeAString` has an implied type of `string | Date`, whereas `isAString` always has the type `string`. The latter behavior seems to me to be correct; am I missing something? It seems like the compiler "forgets" that the constant `1` is being used as the index in the first case, and just treats it as if it could be any number.

```ts
    type index = [Date, string];
    let foo: index | string;
    let shouldBeAString = foo[1]; // type is Date | string
    if (typeof foo === 'string') {
        let isAString = foo[1]; //type is string
    } else {
        let isAString = foo[1]; //type is string
    }
```

**Comment by ahejlsberg** [comment]
This one is rather subtle. When accessing a property through a union type, as is the case in `foo[1]`, we attempt to find the property in each constituent type. A property named `1` exists in the tuple, but there isn't a *declared* property `1` in type `string`. Since we can't find a declared property in each type, we fall back to looking for an appropriate index signature in each type. That succeeds, but we've now lost track of the specific index on the tuple side, and we end up with `Date | string`.

Strictly speaking this is working as intended, but you could make an argument for allowing matches for a declared property to come from index signatures in other types when forming union type properties.
