### ISSUE TITLE
Object is incorrectly typed as 'possibly null' inside closure

### ISSUE THREAD

**Issue by tjhance** [Microsoft/TypeScript#12113]
**TypeScript Version:**  2.0.3 (also the 2.1 RC)

**Code**

With --strictNullChecks,

```ts
class A {
  constructor() { }
  method() { }
}

function f(a: A | null) {
  a = a || new A();
  if (!a) {
    return;
  } 
  
  [1,2,3].forEach((item) => {
    a.method();
  });
} 

```

**Expected behavior:**

I expect this to compile

**Actual behavior:** 

I get an error,

`closure.ts(13,5): error TS2531: Object is possibly 'null'.`

If I remove the forEach loop and just write `a.method()`, it compiles. Also, if I remove the line `a = a || new A()`, it compiles. Both things together seem to confuse TypeScript.

If I remove the `if (!a) { return; }` it fails with the same error, which seems like a bug as well.

I understand how this closures in general could be difficult to reason about, but in this case, I think TypeScript should be able to figure it out, since the closure function cannot be called until after the `  if (!a) { return; }`, after which point `a` is never assigned.

**Comment by gcnew** [comment]
TypeScript resets type narrowings when a variable is used inside a closure. This is done because the reference may be of different type if the closure is not immidiately executed (i.e. subsequent code can change the type). Because TypeScript does not have a mechanism to tell whether a function is immidiately invoked or not, it applies the following two rules:
 - if the variable is declared as const, it preserves its type (as const variables cannot be reassigned)
 - if a variable is not reassigned in functions body its treated as if itwas const

So to fix your issue either assign the new value to `const a2` instead or omit the assignment as it seems redundant.
