### ISSUE TITLE
Increase flexibility of --noUnusedParameters

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/TypeScript#12149]
As per https://github.com/Microsoft/TypeScript/issues/9458#issuecomment-234230702: relying on `_` prefixes as a naming convention can be suboptimal for a few reasons:
* Libraries such as jQuery and Knockout often provide function interfaces whose first parameter(s) aren't necessary for all usages
* We're binding compiler logic to the variable name
* It's easy to forget to remove the prefix, such as during refactoring
* Prefixed names clash with some existing coding styles

I jumped the gun a bit and sent PR #12139 :) that blindly allows unused parameters before used ones. Perhaps a more complete design would be to provide configurations for `--noUnusedParameters`?

* No unused parameters in any situation: `tsc --noUnusedParameters`
* "---" excluding `_` prefixes: `tsc --noUnusedParameters allow-prefixed`
* "---" excluding those before used ones: `tsc --noUnusedParameters allow-before-used`
* "---" excluding both `_` prefixes and those before used ones: `tsc --noUnusedParameters allow-prefixed --noUnusedParameters allow-before-used`

**Comment by mhegazy** [comment]
> We're binding compiler logic to the variable name

Binding the order of parameters to which own is allowed to be unused seems equally troubling.

> Libraries such as jQuery and Knockout often provide function interfaces whose first parameter(s) aren't necessary for all usages

This is true in cases where you are using a library, but not so in cases where these are your own functions. you want to know that they are unused, so that you can refactor your code, and change the call sites.

> Perhaps a more complete design would be to provide configurations for 

I do not think adding new options/configurations is a good solution in general. we have too many of them already. ideally we would reduce them or at least keep them the same.

I should add that this feature crosses the line between the checking (type system, assignment comparability, etc) and linting. I understand that for linter features, there is more room to style choices, where as this does not fit with the rest of the compiler behavior. I would recommend considering tslint for scenarios like these where you want to customize reporting.

**Comment by JoshuaKGoldberg** [comment]
That makes sense. Thanks!
