### ISSUE TITLE
False "Property does not exist on type 'never'" when changing value inside callback with strictNullChecks

### ISSUE THREAD

**Issue by dphilipson** [Microsoft/TypeScript#12176]
**TypeScript Version:** 2.0.8
**Code**

```ts
function call(f: () => void) {
    f();
}

let x: string | null = null;
call(() => x = 'Hello');
if (x !== null) {
    console.log(x.length);
}
```

**Expected behavior:**

`tsc test.ts --strictNullChecks` should succeed. The if-block is a valid case and in fact executes (printing `5`) when compiled without `strictNullChecks`.

**Actual behavior:** 

```
$ tsc --strictNullChecks test.ts
test.ts(8,19): error TS2339: Property 'length' does not exist on type 'never'.
```
TypeScript seems to think that since `x` is set to `null` at its definition, its type is therefore `null` even after running the callback and so the if-body will never run.

**Comment by Kovensky** [comment]
TypeScript ignores refinements from callbacks as you could have been giving it to, say, `setTimeout` or `Promise.resolve().then`, which would only run the callback _after_ the rest of the current scope.

However, `x !== null` should definitely refine `x` to `x: string` instead of `x: never`, even if the compiler might (incorrectly) think `x.length` is unreachable.

**Comment by RyanCavanaugh** [comment]
See #9998

**Comment by RyanCavanaugh** [comment]
See #11498
