### ISSUE TITLE
Unable to use super method when extending a class that has the method implemented via an interface

### ISSUE THREAD

**Issue by kylenicola** [Microsoft/TypeScript#12282]
**TypeScript Version:**  2.0.9 

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
interface Inter {
  Foo?(): void;
}

class Bar implements Inter {
}

interface BarClass {
  new(): Bar;
}

const Fun = (barClass: BarClass) => {
  return class extends barClass {
    public Foo(): void {
      super.Foo();
    }
  }
}

```

**Expected behavior:**

Able to call super.Foo() within Foo method.

**Actual behavior:** 

Typescript error, "Property 'Foo' does not exist on type 'Bar'".  If I add the Foo method directly on Bar then it passes fine.  

I'm trying to have a method that takes a react class, extends it, then extends a componentWillMount() method, but I'm unable to call super within that method since the definitions files follows the pattern above.

**Comment by mhegazy** [comment]
An implements clause does not cause a class to "inherit" properties from an interface. it is just a request for the compiler to check that the class does indeed "implement" the interface. in your case it happens that class `Bar` implements `Inter` correctly, since the only property on `Inter` is optional. so `var i: Inter = { };` is a valid assignment. At runtime class `Bar` does not have any `Foo` methods on it.

you can define the method on class `Bar`, this way you would have access to it in the extending class.

Please note that starting with TS 2.0, you can define optional methods on classes as well as interfaces. e.g.:

```ts
class Bar {
     Foo?(): void;
}

interface BarClass {
  new(): Bar;
}

const Fun = (barClass: BarClass) => {
  return class extends barClass {
    public Foo(): void {
      super.Foo();  // OK
    }
  }
}
```

**Comment by kylenicola** [comment]
@mhegazy Thanks for your speedy response!
