### ISSUE TITLE
Array.filter condition wasn't recognized by Flow Analyzation when strictNullChecks be true

### ISSUE THREAD

**Issue by twoeo** [Microsoft/TypeScript#12294]
**TypeScript Version:**  2.0.3 / nightly (2.1.0-dev.201xxxxx)
2.1.1

**Code**

```ts
interface Test{
  value?: {
    a: string;
    b: string;
  }
}

var tests:Test[] = [];
tests.push({
  value:{
    a:'a',
    b:'b'
  }
})

tests.filter(v=>v.value).forEach(v=>{console.log(v.value.a)})
```

**tsconfig.json**
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "noImplicitAny": false,
    "sourceMap": false,
    "strictNullChecks": true
  }
}
```

**Expected behavior:**
Compile successfully

**Actual behavior:** 
test.ts(16,50): error TS2532: Object is possibly 'undefined'.

**Comment by kitsonk** [comment]
Currently CFA cannot perform that type of anyalysis, and I suspect it would be very hard to accomplish, because `Array.prototype.filter` is functional not syntactical and there is no way to easily express you are mutating the types in that function.

In theory with the new [mapped types](https://github.com/Microsoft/TypeScript/pull/12114) you could create a custom function that would turn that into a non optional type before passing it into a forEach, but it is unlikely there would be a one size fits all map type expression that would work for filter.

**Comment by twoeo** [comment]
Yes, CFA can not always do every thing.
So it need a easy way to mark up some field.
Mapped Types is useful, especially for those interface which have the same structure but different requirement .
