### ISSUE TITLE
noImplicitAny regression in 1.3

### ISSUE THREAD

**Issue by jseanxu** [Microsoft/TypeScript#1232]
Pre 1.3, with `--noImplicitAny` flag on, having the following:
```ts
interface Object {
  [key: string]: any;
}
```
would enable this type of scenario:
```ts
var element = document.querySelector("#something");
element["foo"] = { ... };
```

However, now this results in an implicit-any error. The [winjs/winjs](http://github.com/winjs/winjs) team uses this pattern a lot to add and access members on various objects and this is blocking us from moving to 1.3.

**Comment by webia1** [comment]
I've an Angular2 related Issue:

myData is defined as: `myData:any = {'foo': 'bar'};` in the component and I've the following method:

```
private whatever (param:string) {
  console.log (this[param]); // param = 'myData'    
}
```
It actually works properly but the TypeScript-Compiler outputs an error:

`TS7017:Index signature of object type implicitly has an 'any' type.`

I've tried to suppress this error by switching off the following flags in the tsconfig.json (compilerOptions):

```
"noImplicitAny": false,
"noImplicitThis": false,
"suppressImplicitAnyIndexErrors": true,
```
It did not work. Can someone help me further?

**Second question:**

Is it possible to suppress certain errors (e.g. TS7017) in tsconfig.json? If yes, how? I would like to achieve something like (e.g. in the `compilerOptions` in `tsconfig.json`):

```
    // ATTENTION PSEUDO CODE
    suppressErrors: ['TS7017', ....]
```

p.s. `TS7017: Index signature of object type implicitly has an 'any' type.`

thank you very much!

**Comment by mhegazy** [comment]
@webia1, this is a year old issue. it is not related to the question you posted. In the future we would appreciate it if you can start new tickets instead of commenting on closed issues. also SO or the ts gitter room would be better venues for such questions. this issue tracker is mainly for TS compiler and tools bugs.

As for your question. The containing class (refereed to in this context using `this`) does not have an index signature, so indexing into it results into the `any` type. i.e. the compiler does not know statically what value `param` can have, it can be `toString` and get you a function, or it can be a property, and get you a number or string for instance. Since indexing with strings is allowed in JS, the compiler let's it pass, but gives you the error in `noImplicitAny` errors.

Setting `noImplicitAny` to false should suppress the error. the fact that it did not suggests that you have an issue in your project setup or how you call the compiler. to be able to help you further i will need to look at your setup and how you are invoking the compiler. The most common issue ppl run into is calling the compiler with no configuration and assuming it will pick up the tsconfig.json. if you have a tsconfig.json call the compiler as `tsc --p <path to tsconfig.json>` and not just `tsc file.ts`. 

see http://www.typescriptlang.org/docs/handbook/interfaces.html#indexable-types for more details.

**Comment by webia1** [comment]
Thank you, that helps completely,..
