### ISSUE TITLE
IDL/winmd d.ts generation

### ISSUE THREAD

**Issue by joelday** [microsoft/TypeScript#1242]
Would be nice for an officially supported solution that matches WinRT's JavaScript transformation.

**Comment by staxmanade** [comment]
just stumbled on this issue. I wouldn't say "Too Complex", maybe the Out of Scope label is fitting.

The most complex thing about this is the in-ability for a project like this to sit as long as it has and keep working with how the tooling keeps breaking things...

https://github.com/ToTypeScriptD/ToTypeScriptD/

Any help getting it rebooted with the latest versions of things since MSFT keeps moving forward and breaking the tooling would be appreciated.

It's totally do-able - it worked great back then, I think with some ❤️ it could work again...
