### ISSUE TITLE
Property decorator not recognizing classes as types

### ISSUE THREAD

**Issue by yesman85** [Microsoft/TypeScript#12459]
I have read upon this a few times but couldn't get a satisfying answer.

Considering this code:

```ts

export class Main {
    @decorator
    public prop: Test;
}

export class Test {
    public static name: string = 'test';
}

export function decorator(target: Object, property: string) {
    console.log(target);
    console.log(property);

    let typeName: string = Reflect.getOwnMetadata("design:type", target, property);
    console.log(typeName);
}
```

**Expected behavior:**
typeName should return me "Test", instead it's undefined.

The generates JS seems OK:
```js
    __decorate([
        module_1.decorator,
        __metadata('design:type', Test)
    ], Main.prototype, 'prop', void 0);
```

Is there a limitation on decorators that only non-complex types work?

**Comment by aluanhaddad** [comment]
Your program has several bugs which prevent it from working correctly.

1. Test is not defined when the decorator is called. Because classes are not hoisted like function definitions. If you are compiling with `--target es2015` or later, this will throw immediately. 
If you are compiling with `--target es5`, the class definition is translated into a `var` statement which hoists the binding `Test`, but not its assignment, to the top of the enclosing function or file In this case it will not throw but will have the value undefined.

After fixing this, we have
```ts
export class Test {
  public static name: string = 'test';
}

export class Main {
  @decorator prop: Test;
}
```
 2. Defining `Test` throws an error under strict mode (ES Modules are implicitly in strict mode), and fails silently in sloppy mode. Do not set Function.name!
After we correct this we can run the program which then prints
```bash
Main
prop
[Function: Test]
```
It prints `[Function: Test]` because `typeName` references Test, not Test.name as its name suggests. Fix this and you get the expected
```bash
Main
prop
"Test"
```

**Comment by yesman85** [comment]
That makes sense yes, thanks.

In my cast I just wanted to get the name of the class instead of the actual instance / definition, and thought I could solve it with Reflection in the decorator function.

**Comment by yesman85** [comment]
@aluanhaddad  I assume that this is the same case as for parameters in decorators (@decorator(Test)) ?
