### ISSUE TITLE
Unreasonable time/memory consumption when mapped type and type alias combined

### ISSUE THREAD

**Issue by HerringtonDarkholme** [Microsoft/TypeScript#12487]
**TypeScript Version:**  nightly

**Code**

```ts
type Id<T> = T

type A<Parent> = Id<
  { [K in 'a' | 'b' | 'c']: A<A<Parent>> } &
  { [K in 'd' | 'e' | 'f']: Parent } 
>

declare var k: A<{test: number}>
k = k.a.c
```

**Expected behavior:**

The above code should compile relatively fast.

**Actual behavior:**
High memory usage. Check time is almost 1min. Many types created.

```
Files:              2
Lines:          18227
Nodes:          73370
Identifiers:    24838
Symbols:       564209
Types:        2208525
Memory used: 1305947K
I/O read:       0.00s
I/O write:      0.07s
Parse time:     0.30s
Bind time:      0.16s
Check time:    48.37s
Emit time:      0.31s
Total time:    49.15s
```

As a comparison, if `Id` type alias is removed.

```
Files:            2
Lines:        18225
Nodes:        73368
Identifiers:  24837
Symbols:      19038
Types:         4651
Memory used: 61409K
I/O read:     0.00s
I/O write:    0.00s
Parse time:   0.29s
Bind time:    0.16s
Check time:   0.54s
Emit time:    0.03s
Total time:   1.03s
```

**Comment by ahejlsberg** [comment]
This is an instantiation caching issue--or rather, an issue of lack of instantiation caching. You can force more caching by introducing an intermediate type alias:

```ts
type Id<T> = T;

type A<Parent> = Id<AA<Parent>>;

type AA<Parent> =
  { [K in 'a' | 'b' | 'c']: A<A<Parent>> } &
  { [K in 'd' | 'e' | 'f']: Parent };
```

This causes the example to compile, but produces an error--which I think is expected. Still, a word of warning. These types of self-referential declarations produce infinitely expanding types that can't be exhaustively analyzed. For that reason it is possible that results of relating such types to each other (as happens when validating the assignment `k = k.a.c`)  appear inconsistent when the compiler's infinite recursion protection kicks in and terminates early.

**Comment by HerringtonDarkholme** [comment]
Thanks for the detailed explanation!

> the compiler's infinite recursion protection kicks in and terminates early

Thanks for the suggestion. I'm exploring TypeScript's bound of expressiveness in a hobby project. Your suggestion is very helpful!

> an issue of lack of instantiation caching

My remaining question s whether this is expected behavior?
