### ISSUE TITLE
Contextual typing doesn't seem to work correctly with union types

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#12489]
This is [something that comes up trying to use `app.use` from Express](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/dc6cc8dcb97aef9e8c107703de4c5d3d47d2826e/express/express-tests.ts#L22-L25).

```ts
interface CallbackA {
    (a: string, b: string, c: string): void;
}
interface CallbackB {
    (a: boolean, b: boolean, c: boolean, d: boolean): void;
}

interface Handler {
    (path: string, ...callbacks: (CallbackB | CallbackA)[]): void;
}

declare var handler: Handler;

handler("hello", (a, b, c) => {
});

handler("hello", (d, e, f, g) => {
});
```

**Expected**: `a`, `b`, `c` have types `string`; `d`, `e`, `f`, `g` have type `boolean`

**Actual**: `a`, `b`, `c` implicitly have types `any`; `d`, `e`, `f`, `g` have type `boolean`

**Comment by ahejlsberg** [comment]
In the second call to `handler` only `CallbackB` is applicable because it is the only one that supplies four arguments. In the first call both `CallbackA` and `CallbackB` are applicable, and since they don't agree in their argument types it starts to be guesswork to provide a contextual types, so we don't. Here's the relevant comment from `getContextualSignature` in the compiler:

> Return the contextual signature for a given expression node. A contextual type provides a contextual signature if it has a single call signature and if that call signature is non-generic. If the contextual type is a union type, get the signature from each type possible and if they are all identical ignoring their return type, the result is same signature but with return type as union type of return types from these signatures.
