### ISSUE TITLE
how to use the prototype of PromiseConstructorLike instance in interface declaration?

### ISSUE THREAD

**Issue by pocesar** [microsoft/TypeScript#12497]
**TypeScript Version:**  2.1.1

http://stackoverflow.com/questions/40481641/how-to-use-the-prototype-of-promiseconstructorlike-instance-in-interface-declara

Since I already used 150 of my rep in bounties and had no response, I'm posting it here, for an official answer

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
