### ISSUE TITLE
why is type T = (x: T) => void valid whereas T = T isnt?

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#12525]
nightly build Nov 27, 2016:
```
type U = U; // problem: Type alias 'U' circularly references itself.
type T = (value: T) => void; // ok, but why?
```

**Comment by HerringtonDarkholme** [comment]
https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#310-type-aliases

> Note that object type literals, function type literals, and constructor type literals do not depend on types referenced within them and are therefore permitted to circularly reference themselves through type aliases.

**Comment by DanielRosenwasser** [comment]
The restriction that a type alias can't be referenced by itself at the top level has been the behavior since type aliases existed; however, you might recall that a while back, we started allowing type aliases to be referenced from within an object type.

If we desugar `T`'s declaration to use object type, we can that under the current rules, it's allowed.

```ts
type T = {
    (value: T) => void
};
```

Overall this is actually pretty reasonable - even Haskell can't express something like this:

```hs
type Wat = Wat
```

```
<interactive>:1:1: error:
    Cycle in type synonym declarations:
      <interactive>:1:1-14: type Wat = Wat
```

However, it has no problem provided that the type can be expanded, or "unrolled" one level at a time. In other words, as long as you have some sort of *box*-y thing containing the type:

```hs
newtype Box a = Box a
```

the type system will be okay.

**Comment by aleksey-bykov** [comment]
is there any chance for recursive types in unions?

```
type Expression = Binary <Expression> | Unary <Expression>
```

**Comment by mhegazy** [comment]
> is there any chance for recursive types in unions?

tracked by https://github.com/Microsoft/TypeScript/issues/6230
