### ISSUE TITLE
Method and accessor decorators should modify type based on returned descriptor

### ISSUE THREAD

**Issue by spion** [Microsoft/TypeScript#12585]
Method and accessor decorators should modify the type of the method/accessor based on the return type of the property descriptor.

Additionally, property descriptors should be parameterised based on the type of the property they're describing, with the appropriate types for `get`/`set` and `value`

**TypeScript Version:**  2.1.1

**Code**

```ts
function stringified(target:any, property:string, descriptor:PropertyDescriptor) {
    let oldGetter = descriptor.get
    return {
        get: function () {
            return oldGetter().toString()
        }
    }
}

class Test {
    @stringified get getter() {
        return 5;
    }
}

let x = new Test().getter
x.startsWith('5')

```

**Expected behavior:**

The return type of the getter is `string` and the code compiles without errors.

**Actual behavior:**

The type of `x` is still `number`

**Comment by mhegazy** [comment]
Decorators are not allowed to change the type of declaration. allowing this is tracked by https://github.com/Microsoft/TypeScript/issues/4881.

You should get an error if you try to change the type. The reason you did not get this error is your decorator function is typed to return `any` for all properties. since `any` is a subtype of number, you do not get an error. if it however was typed as:

```ts
function stringified<T>(target:any, property:string, descriptor:TypedPropertyDescriptor<T>) ...
```

you should get an error on the application of the decorator.
