### ISSUE TITLE
alphabetical order set by the names of *.d.ts files matters to the outcome of the build

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#12617]
so i am augmenting the "standard" `Array` interface with methods of specific signatures, these signatures (`filter` for example) compete with the overloads of the standard `lib.d.ts`, depending on how i name the declaration file with my next overload i might or might now have precedence over the standard overloads, which is well... funny, please document it

**Comment by mhegazy** [comment]
Overload resolution is order-dependent. the order of the overloads within the same declaration matter, and is the order of the containing declarations if they are merged.

**Comment by aleksey-bykov** [comment]
i am specifically talking about the names of the *.d.ts files

**Comment by mhegazy** [comment]
does your tsconfig.json has `"include"` in it or `"files"`?

The compiler process files in order, so the order of the declarations should be the same as the order of the input files.
the input file order is decided by order of files on the command-line, the order of the "files" list in tsconfig, or through resolving imports and `/// <references .. />` tags.
`"include"` should specify order, but this is not working, https://github.com/Microsoft/TypeScript/issues/11461 is tracking fixing it.
Otherwise, the order of the input is whatever the OS returns when the files in the directory are listed.

**Comment by aleksey-bykov** [comment]
i use include

**Comment by mhegazy** [comment]
then looks like you are running into #11461.
