### ISSUE TITLE
Comparison with Facebook Flow Type System

### ISSUE THREAD

**Issue by fdecampredon** [Microsoft/TypeScript#1265]
> Disclaimer: This issue has not for purpose to prove that flow is better or worse than TypeScript, I don't want to criticize the amazing works of both team, but to list the differences in Flow and TypeScript **type system** and try to evaluate which feature could improve TypeScript. 

Also I won't speak about missing features in Flow since the purpose is as stated to improve TypeScript.
Finally this topic is only about **type system** and not about supported es6/es7 features.
## `mixed` and `any`

From the flow doc : 

> - mixed: the "supertype" of all types. Any type can flow into a mixed.
> - any: the "dynamic" type. Any type can flow into any, and vice-versa 

Basically that's mean that with flow `any` is the equivalent of TypeScript `any` and `mixed` is the equivalent of TypeScript `{}`.
## The `Object` type with flow

From flow doc : 

> Use mixed to annotate a location that can take anything, but do not use Object instead! It is confusing to view everything as an object, and if by any chance you do mean "any object", there is a better way to specify that, just as there is a way to specify "any function". 

With  TypeScript `Object` is the equivalent of `{}` and accept any type, with Flow `Object` is the equivalent of `{}` but is different than  `mixed`, it will only accepts Object (and not other primitive types like `string`, `number`, `boolean`, or `function`).

``` typescript
function logObjectKeys(object: Object): void {
  Object.keys(object).forEach(function (key) {
    console.log(key);
  });
}
logObjectKeys({ foo: 'bar' }); // valid with TypeScript and Flow
logObjectKeys(3); // valid with TypeScript, Error with flow
```

In this example the parameter of `logObjectKeys` is tagged with type `Object`, for TypeScript that is the equivalent of `{}` and so it will accept any type, like a `number` in the case of the second call `logObjectKeys(3)`.
With Flow other primitive types are not compatible with `Object` and so the type-checker will report and error with the second call `logObjectKeys(3)` :  _number is incompatible with Object_.
## Type are non-null

From flow doc : 

> In JavaScript, null implicitly converts to all the primitive types; it is also a valid inhabitant of any object type.
> In contrast, Flow considers null to be a distinct value that is not part of any other type. 

see [Flow doc section](http://flowtype.org/docs/nullable-types.html)

Since the flow doc is pretty complete I won't describe this feature in details, just keep in mind that it's forcing developer to have every variables to be initialized, or marked as nullable, examples :

``` typescript
var test: string; // error undefined is not compatible with `string`
```

``` typescript
var test: ?string;
function getLength() {
  return test.length // error Property length cannot be initialized possibly null or undefined value
}
```

However like for TypeScript type guard feature, flow understand non-null check:

``` typescript
var test: ?string;
function getLength() {
  if (test == null) {
    return 0;
  } else {
    return test.length; // no error
  }
}

function getLength2() {
  if (test == null) {
    test = '';
  }
  return test.length; // no error
}
```
## Intersection Type

see [Flow doc section](http://flowtype.org/docs/union-intersection-types.html#intersection-example)
see Correspondin TypeScript issue #1256 

Like TypeScript flow support union types, it also support a new way of combining types : Intersection Types.
With object, intersection types is like declaring a mixins : 

``` typescript
type A = { foo: string; };
type B = { bar : string; };
type AB = A & B;
```

AB has for type `{ foo: string; bar : string;}`;

For functions it is equivalent of declaring overload : 

``` typescript
type A = () => void & (t: string) => void
var func : A;
```

is equivalent to : 

``` typescript
interface A {
  (): void;
  (t: string): void;
}
var func: A
```
## Generic resolution capture

Consider the following TypeScript example: 

``` typescript
declare function promisify<A,B>(func: (a: A) => B):   (a: A) => Promise<B>;
declare function identity<A>(a: A):  A;

var promisifiedIdentity = promisify(identity);
```

With TypeScript `promisifiedIdentity` will have for type:

``` typescript
(a: {}) => Promise<{}>`.
```

With flow `promisifiedIdentity` will have for type: 

``` typescript
<A>(a: A) => Promise<A>
```
## Type inference

Flow in general try to infer more type than TypeScript.
### Inference of parameters

Let's give a look at this example : 

``` typescript
function logLength(obj) {
  console.log(obj.length);
}
logLength({length: 'hello'});
logLength([]);
logLength("hey");
logLength(3);
```

With TypeScript, no errors are reported, with flow the last call of `logLength` will result in an error because `number` does not have a `length` property.
### Inferred type changes with usage

With flow unless you expressly type your variable, the type of this variable will change with the usage of this variable : 

```
var x = "5"; // x is inferred as string
console.log(x.length); // ok x is a string and so has a length property
x = 5; // Inferred type is updated to `number`
x *= 5; // valid since x is now a number
```

In this example x has initially `string` type, but when assigned to a number the type has been changed to `number`.
With typescript the assignation `x = 5` would result in an error since `x` was previously assigned to `string` and its type cannot change.
### Inference of Union types

Another difference is that Flow propagates type inference backwards to broaden the inferred type into a type union. This example is from facebook/flow#67 (comment)

``` typescript
class A { x: string; }
class B extends A { y: number; }
class C extends A { z: number; }

function foo() {
    var a = new B();
    if (true) a = new C(); // TypeScript reports an error, because a's type is already too narrow
    a.x; // Flow reports no error, because a's type is correctly inferred to be B | C
}
```

("correctly" is from the original post.)
Since flow detected that the `a` variable could have `B` type or `C` type depending of a conditional statement, it is now inferred to `B | C`, and so the statement `a.x` does not result in an error since both types has an `x` property, if we would have tried to access the `z` property and error would have been raised.

This means the following will compile too.

``` typescript
var x = "5"; // x is inferred as string
if ( true) { x = 5; } // Inferred type is updated to string | number
x.toString(); // Compiles
x += 5; // Compiles. Addition is defined for both string and number after all, although the result is very different
```
## Edit
- Updated the `mixed` and `any` section, since `mixed` is the equivalent of `{}` there is no need for example.
- Added section for the `Object` type.
- Added section on type inference

_Feel free to notify if I forgot something I'll try to update the issue._

**Comment by jods4** [comment]
A lot of the comments have focused on the automatic broadening of types in Flow. In both cases you can have the behavior you want by adding an annotation. In TS you would broaden explicitely at declaration: `var x: number|string = 5;` and in Flow you would restrict at declaration: `var x: number = 5;`. I think the case that doesn't require a type declaration should be the one people use most often. In my projects I would expect `var x = 5; x = 'five';` to be an error more often than a union type. So I'd say TS got the inference right on this one.

As for the Flow features that I think are the most valuable?

1. **Non-null types**
I think this one has a very high potential of reducing bugs. For compatibility with existing TS definitions, I imagine it more as a non-null modifier `string!` rather than Flow's nullable modifier `?string`. I see three issues with this: 
How to handle class members initialization? *(probably they have to be assigned in the ctor and if they can escape the ctor before assignment they are considered nullable)*
How to handle `undefined`? *(Flow side-steps this issue)*
Can it work without lots of explicit type declarations?

2. **Difference between `mixed` and `Object`.**
Because unlike C# primitive types can't be used everywhere an object can. Try `Object.keys(3)` in your browser and you'll get an error. But this is not critical as I think edge cases are few.

3. **Generic resolution capture**
The example just makes sense. But I can't say that I'm writing a lot of code that would benefit from that. Maybe it'll help with functional libraries such as Underscore?

**Comment by hraban** [comment]
On the automatic union type inference: I assume "type inference" to be restricted to the type declaration. A mechanism that implicitly infers an omitted type declaration. Like `:=` in Go. I'm no type theorist, but as far as I understand, type inference is a compiler pass that adds an explicit type annotation to every implicit variable declaration (or function argument), inferred from the type of the expression it is being assigned from. As far as I know, this is how it works for.. well.. every other type inference mechanism out there. C#, Haskell, Go, they all work this way. Or not?

I understand the argument about letting real-life JS use dictate TS semantics, but this is perhaps a good point to follow other languages on, instead. Types are the one single defining difference between JS and TS, after all.

I like a lot of the Flux ideas, but this one, well, if it's actually done this way... that's just weird.

**Comment by AlexGalays** [comment]
Non-null types seem like a mandatory feature for a modern type system. Would it be easy to add to ts?

**Comment by danquirk** [comment]
If you want some light reading on the complexities of adding non-nullable types to TS see https://github.com/Microsoft/TypeScript/issues/185

Suffice to say, as nice as non-nullable types are the vast majority of popular languages today do not have non-nullable types by default (which is where the feature truly shines) or any generalized non-nullability feature at all. And few, if any, have attempted to add it (or successfully added it) after the fact due to the complexity and the fact that so much of the value of non-nullability lies in it being the default (similar to immutability). This is not to say we aren't considering the possibilities here, but I wouldn't call it a mandatory feature either.

**Comment by fdecampredon** [comment]
Actually as much as I miss non-null type, the real feature I miss from flow are generic capture, the fact that ts resolve every generic to `{}` makes it really hard to use with some functional construct, especially currying.

**Comment by tel** [comment]
Personally, generic capture and non-nullability are *high* value targets from Flow. I'll read the other thread, but I wanted to throw my 2c in here as well.

I sometimes feel that the benefit of adding non-nullability by default is worth nearly any cost. It is such a high likelihood error condition and having default nullability weakens the ability to discuss nullability anywhere to practically zero.

**Comment by HerringtonDarkholme** [comment]
There are quite a lot hidden features in flow, not documented in flow's site. Including SuperType bound and existential type

http://sitr.us/2015/05/31/advanced-features-in-flow.html
