### ISSUE TITLE
Explicit type parameter breaks Index signature "inference"

### ISSUE THREAD

**Issue by AlexGalays** [Microsoft/TypeScript#12662]
**TypeScript Version:**  2.0.6 or nightly (2.2.0-dev.20161205)

**Code**

```ts
interface Obj<V> { [key: string]: V }

interface Bla {
  iAmABla: string
}

function doSomething(obj: Obj<Bla>) {
  return true
}

function doSomethingElse<T extends Obj<Bla>>(obj: T) {
  return true
}

interface ObjBla {
  a: { iAmABla: 'abc' },
  b: { iAmABla: 'def' }
}

const input = { a: { iAmABla: '' }, b: { iAmABla: '' } }

doSomething(input)
doSomethingElse<ObjBla>(input)
```

**Expected behavior:**

doSomethingElse should compile, as the passed input's type verifies the constraint.
In fact, both doSomething and doSomethingElse compile if the type parameter is not explicitely written by the developer (I need it in a more complex scenario where there are two other type parameters and requires me to provide them to lift ambiguities)

**Actual behavior:**

error TS2344: Type 'ObjBla' does not satisfy the constraint 'Obj<Bla>'. Index signature is missing in type 'ObjBla'.

Of course there is the workaround of adding an index signature, but it's very annoying in my case as this function is used a lot. I think index signature inference was improved recently, looks like a corner case when a type parameter is explicit.

**Comment by RyanCavanaugh** [comment]
The index signature is exclusionary here because it implies the non-existence of other explicit properties. Consider something like this
```ts
interface Obj<V> { [key: string]: V }

interface Bla {
  iAmABla: string
}

function doSomething(obj: Obj<Bla>) {
  return true
}

function doSomethingElse<T extends Obj<Bla>>(obj: T) {
  return true
}

interface ObjBla {
  a: { iAmABla: 'abc' },
  b: { iAmABla: 'def' }
}
interface BetterObjBla extends ObjBla {
    somethingElse: string;
    anotherThing: number;
}

const input = { a: { iAmABla: '' }, b: { iAmABla: '' } }
const myBetterObj: BetterObjBla = { a: { iAmABla: 'abc' }, b: { iAmABla: 'def' }, somethingElse: 'oops', anotherThing: 34 };

let x: typeof input = myBetterObj

doSomething(input)
doSomethingElse<ObjBla>(x)
```

If `doSomethingElse`'s implementation loops through the keys of its input (as would be expected based on its signature) and does things assuming the values from those keys conform to `ObjBla`, it's going to fail.

Index signatures get inferred in places where we can be reasonably sure that there aren't extra properties coming out of nowhere (e.g. object literals). For an arbitrary object reference, that's not a safe assumption.

**Comment by AlexGalays** [comment]
I see!
