### ISSUE TITLE
outDir shape is wrong if dependency uses types:src/index.ts in package.json

### ISSUE THREAD

**Issue by appsforartists** [Microsoft/TypeScript#12698]
**TypeScript Version:**  2.1.1

**tsconfig**

```
{
  "include": ["./src/**/*"],
  "exclude": ["**/*.test.*"],
  "compilerOptions": {
    "declaration": true,
    "lib": [
      "es2015",
      "dom"
    ],
    "module": "commonjs",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "noImplicitThis": true,
    "outDir": "dist",
    "sourceMap": true,
    "strictNullChecks": true,
    "target": "es6"
  }
}
```

**Files**

- `/src/index.ts`

**Expected behavior:**

Generated files are output here:

- `/dist/index.js`

**Actual behavior:**

If a dependency uses this package.json:

```
"types": "./dist/index.d.js",
```

the `dist` folder has the expected shape; however, if it the dependency has this package.json:

```
"types": "./src/index.ts",
```

then the output will be:

- `./dist/src/index.js`

You can test this for yourself by including this line in an otherwise working TypeScript project:

```
import anything from 'indefinite-observable';
```

Because `indefinite-observable@0.0.0` has `types: "./src/index.ts"`, everything in `dist` will be wrapped in a superfluous `src` folder.

**Comment by mhegazy** [comment]
use `rootDir` to guarantee consistent behavior of the generated output directory structure. otherwise the compiler will try to guess that from the input files, and will change as it picks up more files.

also `types` should not be `.ts` file as this will force you, as a user, to build it along with your other sources; this should be fixed on the package author side.

**Comment by appsforartists** [comment]
Thanks.
