### ISSUE TITLE
static toString with incorrect type breaks instanceof

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/TypeScript#12709]
See https://github.com/Microsoft/vscode/issues/16819

**TypeScript Version:**  typescript@2.1.4-insiders.20161206
- VSCode Version: Code - Insiders 1.8.0-insider (0d65ced0fa7398dc9d50c39a23a2a8cc8406ff18, 2016-12-07T07:05:09.124Z)
- OS Version: Darwin x64 15.6.0

**Code**

```ts
export abstract class Marker {
	static toString(markers: Marker[]): string {
		return '';
	}
}

export class Placeholder extends Marker {
	constructor(public name: string = '', public defaultValue: Marker[]) {
		super();
	}
}

function foo(marker: Marker) {
	if (marker instanceof Placeholder) {
		console.log(marker.name);
		console.log(marker.defaultValue);
	}
}

foo(null);
```

**Expected behavior:**
No erros are shown in the vscode editor

**Actual behavior:**
![screen shot 2016-12-07 at 8 55 21 am](https://cloud.githubusercontent.com/assets/4674940/20977802/7f707572-bc5b-11e6-956c-c6a9a8a94805.png)

When the static toString is removed or renamed the problem goes away.

**Comment by sandersn** [comment]
1. The type of `toString` is incorrect. `markers` is required and should be optional, because toString might get called on the class (not its instance). You can make `markers` optional as a workaround.
2. We should probably relax the instance rhs requirement to just be a type that has a call or construct signature. It doesn't *actually* need to be assignable to `Function`.

-- OR --
2. Give an error when the instance or static side of a class incorrectly extends Object. But we don't do this today, and it would breaks tons of code. And people must not care too much, because I don't know of an existing bug for this.

**Comment by sandersn** [comment]
Fix is up at #12728

**Comment by about-code** [comment]
> Give an error when the instance or static side of a class incorrectly extends Object. But we don't do this today, and it would breaks tons of code. And people must not care too much, because I don't know of an existing bug for this.

Maybe there is: #442

**Comment by sandersn** [comment]
As far as I can tell, #442 is essentially about using built-in names that are readonly, not incorrectly overriding a name that is meant to be overridden.

However, your PR to fix it looks undeservedly ignored. I'll take a look.

**Comment by about-code** [comment]
> As far as I can tell, #442 is essentially about using built-in names that are readonly, not incorrectly overriding a name that is meant to be overridden.

@sandersn indeed, you're right. I think I got this mixed up. Thank you very much for your encouraging review.
