### ISSUE TITLE
freezing indexed objects causes compile error

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/TypeScript#12712]
See https://github.com/Microsoft/vscode/issues/16819

**TypeScript Version:**  typescript@2.1.4-insiders.20161206
- VSCode Version: Code - Insiders 1.8.0-insider (0d65ced0fa7398dc9d50c39a23a2a8cc8406ff18, 2016-12-07T07:05:09.124Z)
- OS Version: Darwin x64 15.6.0

**Code**

```ts
export interface Foo {
	property: boolean;
	[key: string]: any;
}

function freezer(bar: Foo): Foo {
	return Object.freeze(bar);
}

freezer(null);
```

**Expected behavior:**
No erros are shown in the vscode editor

**Actual behavior:**
![screen shot 2016-12-07 at 9 36 11 am](https://cloud.githubusercontent.com/assets/4674940/20979185/a9d68680-bc60-11e6-85d5-d792c5a9926e.png)

The error goes away if property or the index is removed from Foo.

**Comment by mhegazy** [comment]
The issue is that `keyof Foo`  in the exampe above is `string` and no`"property" | string`. we would like to try changing this behavior.

**Comment by kieferrm** [comment]
@mhegazy I'm not sure I understand if that implies that the code example is incorrect. If so, can you point out how the code should be changed to avoid the error?

**Comment by mhegazy** [comment]
`freeze` is defined to use a mapped `Readonly`. Mapped types generate a copy of the type using known keys (i.e. `keyof Foo` in this example). Since it is `"property" | string` and `string` is a super type of `"property"`, `"property"` gets lost, and the new type created is missing the known property..

so long story short, this behaves as designed, but we need to revisit the design. 

for now, you can cast the result to `Foo`, e.g. 

```ts
function freezer(bar: Foo): Foo {
	return <Foo>Object.freeze(bar);
}
```
