### ISSUE TITLE
TypeError: ResizeSensor is not a constructor (Angular AOT external .js files)

### ISSUE THREAD

**Issue by quiringk** [Microsoft/TypeScript#12746]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)
version 2.0.9
**Code**
Angular 2.2.3 
```ts
// A *self-contained* demonstration of the problem follows...

I have an Angular 2 App and am using the external javascript library "css-element-queries". This library consists of two .js files (ElementQueries.js and ResizeSensor.js.) When I run my Angular 2 app in development mode (JIT), everything works fine. When I run my app in (AOT) mode for production, I get "TypeError: ResizeSensor is not a constructor" error which stops the css-element-queries from working. 

The error occurs on this line in ElementQueries.js: (line 157) 

`element.elementQueriesSensor = new ResizeSensor(element, function() { element.elementQueriesSetupInformation.call();`

Once again, the scripts work fine in development mode, its in production AOT mode that I get the constructor error.

Also, I have other external .js files that are all working fine with Angular AOT. The only difference with this library is that there are two separate files and one is making a call to the other.


```

**Expected behavior:**

works, just like in angular JIT

**Actual behavior:**

Library doesnt work, errors out

**Comment by aluanhaddad** [comment]
Without more specific information it's not possible to to make a diagnosis but it is worth noting that Angular 2’s AOT compiler does not have the same semantics as TypeScript in a significant number of cases. It outputs TypeScript which you did not write which is then in turn compiled by TypeScript.

This causes errors.

For example, a private field declared in a component will be accessible to that component's Angular markup when it is JIT compiled but will generate an error when it is AOT compiled. This happens because, while typescript elides the `private` modifier naturally in the process of emitting valid ECMAScript, AOT generates Hera because the intermediate TypeScript that accesses the field is placed outside the scope of the class and is then compiled with TypeScript which reports a semantic error.

As far as I can tell this behavior is not well documented anywhere and my request for a formal specification was declined.

**Comment by quiringk** [comment]
I created a public repo for you to look at with all the details you need to see the issue.

https://github.com/quiringk/ConstructorError.git

This repo consists of Angular Quickstart with angular AOT added. I removed the angular quickstart template and replaced it with the first example from "css-element-queries". Go ahead and clone the repo, run "npm install", and then "npm start", and witness the example working perfectly (Adjust the screen size and see the header change color and sizes). If you run "npm run build:aot && npm run lite:aot" you will see the example does not work and you will see the errors I have been describing. Thanks for looking at this.

**Comment by quiringk** [comment]
I figured it out with help from angular guy. If anyone has similar issue check out:

https://github.com/angular/angular/issues/13283

**Comment by aluanhaddad** [comment]
@quiringk thanks for posting the fix. I guess it wasn't about AOT, but at least I got to rant about it 😜
