### ISSUE TITLE
No excess property checks when dealing with tagged unions

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#12745]
Version: 2.1.4

```ts
interface None {
    hasValue: false;
}

interface Some {
    hasValue: true;
    value: any;
}

var x: None | Some = {
    hasValue: false,
    value: [],
}
```

**Expected:** Excess property error on `value` in the object literal.
**Actual:** No error.

**Comment by mhegazy** [comment]
We will need a proposal for this, since this has to take into consideration the discriminant property in the union and filter on this.

**Comment by andy-ms** [comment]
Just ran into this.
```ts
interface A {
    type: "A";
    data: { b: boolean };
}

interface B {
    type: "B";
    data: { n: number };
};

const x: A | B = {
    type: "B",
    data: { n: 1, excess: 2 }
};
```

**Comment by sandersn** [comment]
Fix is up at #16363

**Comment by DanielRosenwasser** [comment]
Is the following also related to this? In other words, is this present regardless of the union being tagged?

```ts
type Props<T> = PropsBase | PropsWithConvert;

interface PropsBase {
    data: string;
}

interface PropsWithConvert extends PropsBase {
    convert: (t: number) => string;
}

function doIt<T>(props: Props<T>) {
}

doIt({
  data: "",
  convert(x) {
    return 10;
  }
})
```

**Comment by lukescott** [comment]
I'm not sure if this is completely fixed. I have code that looks like this:

```typescript
export type Condition = And | Or | Not | {
	[type: string]: {
		target: string
	}
}

export interface And {
	and: Condition[]
}

export interface Or {
	or: Condition[]
}

export interface Not {
	not: Condition
}

const c: Condition = {
	and: [],
	not: {
		equals: {
			target: "name",
			value: "foo"
		},
	},
}
```

And there are no errors. Also if I do this there are no errors as well:

```typescript

const c: Condition = {
	foo: "bar",
	not: {
		equals: {
			target: "name",
			value: "foo"
		},
	},
}
```

**Comment by RyanCavanaugh** [comment]
@lukescott that's the intended behavior - a property isn't excess if it appears in any of the target types

**Comment by lukescott** [comment]
@RyanCavanaugh where is `foo: "bar"` defined?

**Comment by lukescott** [comment]
Ah - I missed `hasValue` was defined on both.

**Comment by lukescott** [comment]
@RyanCavanaugh ok I get how `and` and `or` are allowed on the same object with `|`. I misunderstood what the fix was about. However, why is `foo: "bar"` not emitting an error?

**Comment by sandersn** [comment]
Your `foo: "bar"` example looks like a bug, but not one with excess property checks; it's not doing type checking, just properties. With respect to excess properties, `foo` is not *excess* because `Misc` has a string index signature.

However, you should see a type error because `"bar"` is missing the property `target`.

**Comment by sandersn** [comment]
oh, never mind. You're falling between two checks.

1. The excess property check is satisfied by `Misc`, which has a string indexer. No property will be marked as excess.
2. Structural assignability is satisfied by `Not`, since the object literal has the property `not`, but also an extra (excess!) property `foo`. But this is fine according to the rules of structural assignability.

The basic problem is that excess property checks happen *before* structural assignability finds the "best match" of the union; it uses a faster, heuristic check that doesn't perfectly match the exhaustive search used by structural assignability.

**Comment by sandersn** [comment]
@lukescott I opened a bug #20060 to track your repro. I can't promise we'll do anything about it because we rely on the early-fail property of excess property checking for some speed in `isRelatedTo`.

**Comment by lukescott** [comment]
@sandersn Awesome, thank you!
