### ISSUE TITLE
[Question] How to debug tsc.js

### ISSUE THREAD

**Issue by gcnew** [Microsoft/TypeScript#12802]
I'm trying to play around with the code of the compiler and I'm using debugging both as a means to understand the internals and also to debug my own experiments. The problem I'm facing is that debugging via VS Code is extremely slow - stepping over takes about a second, hovering variables to display their current value takes ages. I tried Node Inspector as well, but it's not better. `console.log` works fine but it's a mediocre debugging facility.

Because of the above I decided to ask the source: what do you use for debugging?

PS: I'm not on Windows currently, thus I haven't tried Chakra Core. Does it offer a better experience?

**Comment by vladima** [comment]
`node --inspect --debug-brk` is my weapon of choice :).

**Comment by gcnew** [comment]
OK, closing for now, if I have further questions I might reopen to save clutter.

**Comment by sandersn** [comment]
`$ gulp runtests-browser --t=specificTest --browser=chrome` gives you source maps, which is nice when you're investigating a *specific* feature with a *specific* test. Instead of showing the entire compiler, Chome will show just the contents of `transformers/esnext.ts`, for example.

For other purposes I agree with @vladima. Debugging is similar with and without source maps -- perhaps a little faster without?

**Comment by gcnew** [comment]
@sandersn Thanks!
