### ISSUE TITLE
Generic function does not determine type with strictNullChecks 

### ISSUE THREAD

**Issue by anvish** [Microsoft/TypeScript#12847]
**TypeScript Version:**  2.1.4

**Code**
```ts
type I = { kind: 'I1' }

type A<T> = [undefined, I] | [T, I]

function works<T>(): A<T> {
    return [undefined, { kind: 'I1' }]
}

function doesNotWork<T>(): A<T> {
    const i = { kind: 'I1' }
    return [undefined, i]
    // [ts] Type '[undefined, { kind: string; }]' is not assignable to type 'A<T>'.
    //     Type '[undefined, { kind: string; }]' is not assignable to type '[T, I]'.
    //         Type 'undefined' is not assignable to type 'T'.
}
```
**Expected behavior:**
Both functions compile
**Actual behavior:**
Extracting variable breaks type detection

**Comment by ahejlsberg** [comment]
You need a type annotation

```ts
const i: I = { kind: 'I1' }`
```

to tell the compiler that you want something of type `I` and therefore a literal type for the `kind` property. Otherwise, since there is no indication to the contrary and since `kind` is a mutable location, the compiler widens the literal `I1` to `string`. That in turn is what causes the error.
