### ISSUE TITLE
Incorrect instanceof behavior when extending native Error

### ISSUE THREAD

**Issue by johnsoft** [Microsoft/TypeScript#12853]
**TypeScript Version:**  2.1.4

**Code**

```ts
class TestError extends Error { }
const works = (new TestError()) instanceof TestError;
console.log(works);
```

**Expected behavior:** (and behavior in Node.js 6.2.1)

works is `true`

**Actual behavior:**

works is `false`

**Comment by DanielRosenwasser** [comment]
Sorry about this - it was an intentional breaking change and [documented here](https://github.com/Microsoft/TypeScript-wiki/blob/master/Breaking-Changes.md#extending-built-ins-like-error-array-and-map-may-no-longer-work). Sorry about the inconveniences you may have encountered.

Marking this issue as a duplicate of #12123.

**Comment by johnsoft** [comment]
That's what I get for not reading the release notes! Thanks for the link.
