### ISSUE TITLE
Type false is not assignable to type this[keyof this] (in 2.1.4)

### ISSUE THREAD

**Issue by newapx** [Microsoft/TypeScript#12878]
**TypeScript Version:**  2.1.4

**Code**
```ts
// A *self-contained* demonstration of the problem follows...
export class ClassA {
  public clean() {
    for (let prop in this) {
      if (typeof this[prop] === "boolean")  this[prop] = false;
    }
  }
}
```

**Expected behavior:**
Compiled without error

**Actual behavior:**
Error `Type false is not assignable to type this[keyof this]`

**Comment by isiahmeadows** [comment]
Try adding `interface BoolMap { [key: string]: boolean; }` and change the initial class declaration to `class ClassA implements BoolMap`. TypeScript doesn't know that `ClassA`, or subclasses thereof, could even have any dynamic boolean properties, because it can only infer so much. Alternatively, you could use a temporary reference and cast the stored value to `{[key: string]: boolean} & this`.

(Oh, and you're iterating the prototype chain with that; might be a good idea to guard that with `hasOwnProperty`.)

**Comment by RyanCavanaugh** [comment]
Should be narrowing `this[prop]` in the body of the `if`

**Comment by mhegazy** [comment]
this is a duplicate of https://github.com/Microsoft/TypeScript/issues/10530. element access expressions are not narrowed.

**Comment by newapx** [comment]
Thank you for the recommendation, but I'm such solutions are not suitable. 
I used  `(<any>this)[prop] = false; `
