### ISSUE TITLE
__assign polyfill is emitted even when targeting ES6

### ISSUE THREAD

**Issue by billti** [Microsoft/TypeScript#12901]
Using the `release-2.1` branch, with `target: "es6"`, this code:

```typescript
const init = {a: 10, b: true};
let newObj = {...init, c: null};
```

Generates the below emit, which contains the unnecessary helper `__assign`, as `Object.assign` is part of ES6 (see http://www.ecma-international.org/ecma-262/6.0/#sec-object.assign ).

```javascript
var __assign = (this && this.__assign) || Object.assign || function(t) {
    for (var s, i = 1, n = arguments.length; i < n; i++) {
        s = arguments[i];
        for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
            t[p] = s[p];
    }
    return t;
};
const init = { a: 10, b: true };
let newObj = __assign({}, init, { c: null });
```

**Comment by sandersn** [comment]
What emit would you like to see? I think it's best to keep the expression emit as `__assign({}, init, { c: null })` instead of `Object.assign({}, init, { c: null })`, which means that some kind of helper emit is needed. @rbuckton, can you provide an opinion on how the ES6 emit should look for spread?

**Comment by mhegazy** [comment]
why not just call `Object.assign`, like we do with `Math.pow` for instance?

**Comment by rbuckton** [comment]
I concur with @mhegazy, we can special case `Object.assign` if we know we aren't further transforming the file to ES5/3.
