### ISSUE TITLE
AllowJS breaks module imports

### ISSUE THREAD

**Issue by servermeta** [Microsoft/TypeScript#12917]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
import * as google from 'googleapis';
```

**Expected behavior:** Without allowjs everything is fine. With allowjs as true, it should behave the same.

**Actual behavior:**
When allowjs is set to true, module import breaks. 

```
src/index.ts(41,36): error TS2339: Property 'auth' does not exist on type 'Function'.
src/index.ts(247,34): error TS2339: Property 'sheets' does not exist on type 'Function'.
```

I tried to declare the module, but it doesn't prevent from breaking.

**Comment by mhegazy** [comment]
A few notes:

- why are you using `--allowjs` if i may ask? do you have `.js` files in your project or is it for the import?
- i can not really tell what the errors mean without having the file, so please include a *self-contained* sample for us to debug against
- the error for a missing module should not be shown in TS 2.1, but it is because the `package.json`::`main` field points to a file with no extension `'./lib/googleapis'`, and the compiler can not find this file on disk. this is a bug and should be fixed, this would make the error go away.
- in general the recommendation for cases like these is to declare the module yourself, since there is no declaration file available at Definitely Typed. the simplest declaration file would look like:

```ts
// modules.d.ts

declare module "googleapis";
```

**Comment by servermeta** [comment]
Ok the problem was that I was declaring the module in index.d.ts instead of module.d.ts . Sorry, my bad. 

I was using allowjs because the tests are run as javascript, and tests require some credentials, which were stored in /private/credentials.js, which I didn't want to replicate as TS file for security and simplicity reasons.

I attached a sample anyhow, for future reference.



[test.tar.gz](https://github.com/Microsoft/TypeScript/files/653302/test.tar.gz)
