### ISSUE TITLE
Can I disable noUnusedLocals, noUnusedParameters per file

### ISSUE THREAD

**Issue by sgwatgit** [Microsoft/TypeScript#12913]
**TypeScript Version:**  2.0.10

After reading about the deprecation of `no-unused-variable` in [tslint v4](https://github.com/palantir/tslint/issues/1481) I started using `noUnusedLocals` and `noUnusedParameters` in my `tsconfig.json`.

With tslint I can disable a rule for a file or line

```
/* tslint:disable:no-unused-variable */
// tslint:disable-next-line
```

Is this disabling possible if Typescript is performing the checks?

Here is a stackoverflow question related to this http://stackoverflow.com/questions/38237594/pragma-disable-for-nounusedlocals

Thanks

**Comment by RyanCavanaugh** [comment]
No. See also #11051

**Comment by thw0rted** [comment]
So uh, would a feature request for this capability be a new ticket then?  As I just commented on #11051, I'm working with *generated* TS (transpiled from Java with `jsweet`) and I'm not sure they will be able to totally avoid generating unused / unreferenced vars.

**Comment by tomfumb** [comment]
@thw0rted I'm in a similar situation with [another TypeScript generator](https://github.com/vojtechhabarta/typescript-generator) but I think [#11051](https://github.com/Microsoft/TypeScript/issues/11051) has the solution. If I rename the generated type file to *.d.ts it is ignored during noUnusedLocals and noUnusedParameters. Unfortunately the generator refuses to generate anything other than a .ts extension, so I have to rename at another point in my build process, but it works.

**Comment by thw0rted** [comment]
I don't think that's going to help me, I'm not generating typings but actual implementations, and `.d.ts` is always an ambient context (right?).

This is a frustrating issue, because it's a basic feature that just about every other tool I can think of includes. If you're going to warn me about something that doesn't impact program execution (like `noUnusedParameters` etc) then, on a case-by-case basis, I need to be able to tell the tool that *I know better* and in this one specific instance, it's correct, even though you think it might be a problem.

**Comment by thw0rted** [comment]
That's a good point -- if it's too much to ask the generator to never create an unused local, maybe we can at least identify the cases where the local *might* be unused and give them an ignore directive preemptively.
