### ISSUE TITLE
Support some level of implicit boolean conversion

### ISSUE THREAD

**Issue by Eyas** [microsoft/TypeScript#1296]
This one has potential for issues, but for certain type implementations, overriding the default implicit boolean conversion for Object types might be useful. There are a few cases. Let's use a type `Maybe<T>` as our canonical example, we want the `Some<T>` subtype to be truthy, and the `Nothing` subtype to be fasly.
## Expressions of (implicit) boolean type (if, while, until, and for statements):

```
// var x: Maybe<T>
if (x)
```

becomes:

```
if (x.toBoolean())
```

```
if (x && x.value().foo())
```

becomes:

```
if (x.toBoolean() && x.value().foo())
```
## Expressions of explicit boolean type

Are practically the same,

```
var b: boolean = x;
```

becomes

```
var b = x.toBoolean();
```

And:

```
var b: boolean = x && x.value().foo();
```

Either works, or complains of a type error if the return type of `foo()` has no implicit boolean conversion (?).
## Binary expressions of non-boolean types

The `x || default` is a common JS pattern. How would that interplay with here:

```
var some: Maybe<T> = x || new Some(5);
```

becomes:

```
var some = x.toBoolean() ? x : new Some(5);
```

For `&&` expressions:

```
// x: Maybe<T>, x.value().y: Maybe<T>
var some: Maybe<T> = x && x.value().y;
```

becomes:

```
var some = x.toBoolean() ? x.value().y : x;
```

Chaining these,

```
// x: Maybe<T>, x.value().y: Maybe<T>
var some: Maybe<T> = (x && x.value().y) || new Some(5);
```

becomes:

```
var some = (var temp = (x.toBoolean() ? x.value().y : x)).toBoolean() ? temp : new Some(5);
```

etc.

The main hope is to be able to use the very useful `if (x)` pattern in more code where `Object` is used.

**Comment by wizofaus** [comment]
For me it's the opposite - I just wasted a full 30 minutes trying to figure out why something wasn't working, and it was due to an implicit conversion from a *function* to boolean, i.e. I had

var x = y.z ? "a" : "b"

y.z is actually a function and it should have been var x = y.z() ? "a" : "b".
C# wouldn't let you write that, so I wouldn't expect TypeScript too either.

**Comment by RyanCavanaugh** [comment]
The problem is that people do this kind of thing all the time:
```ts
function doThing(f?: () => any) {
  var v = f ? f() : some_default;
  ...
}
```
and forcing use of `!!` to coerce to boolean looks really ugly.

**Comment by wizofaus** [comment]
I don't even think you should be able to use !! - a function type isn't a boolean.
doThing(f?: () => any) {
  var v = f == undefined ? f() : some_default;
  ...
}

**Comment by danquirk** [comment]
TypeScript is a typed superset of JavaScript. This means that for the most part we intend to support (ie  provide type information and not report errors) common JavaScript patterns that exist in already working code. This pattern is in use all over the place in JavaScript. It's useful and people rely on it. We cannot break it. If you want to disallow this sort of pattern then that's a good place to apply a linter rule to your codebase but it's not something we're going to make an error by default in TypeScript.

**Comment by wizofaus** [comment]
Hmm, well lots of type-unsafe patterns exist all over the place in JavaScript and the main reason I've started using TypeScript is to stop us from using them!  At the very least it'd be good to see an intellisense warning.

**Comment by danquirk** [comment]
There is a balance in what we allow and don't allow by default. There are implicit conversions between types in many static languages. JavaScript has chosen to support this one and people generally like it and want to take advantage of it. It would be a little disingenuous of us to claim TS is a superset of JS but you should stop using the patterns you're used to because they're errors now. There are situations where we give an error on JS until you provide some type information but there are not (m)any times we take a common expression level pattern and forever forbid it or always require a type assertion. Using a linter to disallow this seems a pretty reasonable alternative.

**Comment by Marais** [comment]
Where can I find this lint rule?

**Comment by kitsonk** [comment]
> Where can I find this lint rule?

@Marais, that would be a question for the linting tool you are using.
