### ISSUE TITLE
Problem with type guards

### ISSUE THREAD

**Issue by johnfn** [Microsoft/TypeScript#13104]
How come this is a bug:

```
function isBuffer(x: any): x is Buffer {
  return x instanceof Buffer;
}

function clone<T extends number | Buffer>(x: T): T {
  if (isBuffer(x)) {
    return x; // Error: Buffer is not assignable to type T.
  }
}
```

But this is fine?
 
```
function clone<T extends number | string>(x: T): T {
  if (typeof x === "string") {
    return x; // Totally fine
  }
}
```

**Comment by RyanCavanaugh** [comment]
So clearly returning `x` from this function ought to always be OK, but it's hard for us to prove that.

The problem here is that `isBuffer` only proves that `x` is `Buffer`, but the instantiation  of `T` *could* be something more specific like `number | SuperBuffer`, at which point it's not safe for us to allow you to return a mere `Buffer` when a `number | SuperBuffer` is required. Of course, if `x` wasn't `SuperBuffer` it would *have* to be `number` in order to be in there in the first place, but this sort of counterfactual reasoning isn't something we're equipped to do.

**Comment by RyanCavanaugh** [comment]
I should add that the primitive case `typeof x === "string"` is different because we consider the primitive types to be effectively `final` (i.e. there is no `SuperString`, c.f. there *could* be a `SuperBuffer`)

**Comment by aleksey-bykov** [comment]
It's not a design limitation, it's just common sense, replace `Buffer` with `Animal` and `T` with `Cat`

```typescript
function isAnimal(x: any): x is Animal {
  return x instanceof Animal;
}

function clone<Cat extends number | Animal>(x: Cat): Cat {
  if (isAnimal(x)) {
    return x; // Error: Animal is not assignable to type Cat.
  }
}
```

Should be clearer now?

**Comment by johnfn** [comment]
Yes, that does make more sense. Thanks @aleksey-bykov.

It appears the problem here is that `extends` says "you can extend from anything in this union" rather than what I want, which is to say "you must be exactly one of the things in this union". 

Thoughts on how to say something like "the input and output of this must both be from this union and both be the same type"?

**Comment by unional** [comment]
> but that seems quite silly.

IMO it is not silly. If the function indeed takes a different type (while returning the same type), they should be overloads.
Think about how do you document this function. You will be ended up having the same wording that describes it is an overload scenario.
