### ISSUE TITLE
CodeFix for missing import should take into account main in package.json

### ISSUE THREAD

**Issue by normalser** [Microsoft/TypeScript#13130]
![image](https://cloud.githubusercontent.com/assets/1723815/21434251/7a2278bc-c841-11e6-9e2e-5c2d50363a18.png)

`package.json` of `antd` module:
```json
  {//...
  "main": "lib/index.js",
   //...
  }
```

Files inside `antd` module:
```sh
...
antd/lib/index.js 
antd/lib/index.d.js
...
```

Ideally if import would be `Import Button from "antd"`

**Comment by mhegazy** [comment]
We try not to do disk lockups here. disk access in general is expensive. given a module, we do not know if it is referenced in package.json higher on or not. so we have to keep walking up and probing.

**Comment by wallverb** [comment]
Right regarding 'disk lookups'

Although it seems like TS already knows that information:
![image](https://cloud.githubusercontent.com/assets/1723815/21435166/40b59fdc-c846-11e6-9710-64dcfec138f9.png)

I was hoping it could be reused in this case (maybe its not about `main` in package.json but the special case for `index.d.ts` and/or `lib/index.d.ts`

**Comment by mhegazy** [comment]
the module resolution is a different process. let me explain.

the compiler looks at imports in your file, and resolves them to files. this involves disk probing, etc.. it reads package.json, it looks up folders, etc.. you can see what is going on using `--traceResolution`.

the quickfix is trying to add an import that does not exist. so the information the compiler built during resolution is not useful here, as the import was not there.

the issue is to compute the quickfix you could have the same name coming from multiple modules. and modules could be imported through multiple names, so the only option is to repeat the process of resolution for each proposed quickfix. and we would rather not do that.

**Comment by wallverb** [comment]
Oh i see, thank you so much for the explanation

**Comment by mhegazy** [comment]
Tracking under https://github.com/Microsoft/TypeScript/issues/15223
