### ISSUE TITLE
CodeFix for remove unused identifiers removes only one identifier

### ISSUE THREAD

**Issue by wallverb** [Microsoft/TypeScript#13131]
![image](https://cloud.githubusercontent.com/assets/1723815/21434679/d4e899b4-c843-11e6-92f3-0299b71088c0.png)

Pressing `Cmd+.` on `Button` presents:

![image](https://cloud.githubusercontent.com/assets/1723815/21434700/f02504d8-c843-11e6-8524-3c15a23c0092.png)

But clicking 'remove unused identifiers' remove only `Button`

I guess ideally if there were 2 options

`Remove unused identifier: Button`
`Remove all unused identifiers`

**Comment by mhegazy** [comment]
quick fixes are limited in scope to one error. so this is a design limitation at the moment.

**Comment by wallverb** [comment]
I see, then maybe just to change text 'Remove unused identifier?' so it's not misleading ?

**Comment by mhegazy** [comment]
sounds reasonable.

**Comment by aleksey-bykov** [comment]
as i mentioned this codefix isn't helping much because it takes as many keystrokes as deleting by hands, it would be of better value if deleted **all unused imports**

**Comment by aluanhaddad** [comment]
@aleksey-bykov I think this would be best served by having an option to autofix all occurrences of the error
![image](https://cloud.githubusercontent.com/assets/5034656/21471404/0342085c-ca80-11e6-9071-aa1d9e32ceae.png)

**Comment by aleksey-bykov** [comment]
I am not a big fan of removing all unused identifiers, because I might
still need them, say, I wrote a non-exported function that haven't had a
chance to use yet, it will be removed too. Imports on the other hand are
easy to restore (thank to import codefix), so not a big deal if the are
removed.

So I suggest to separate all imports removal from all unused locals removal
(not sure if it is a good idea to begin with).

**Comment by aluanhaddad** [comment]
@aleksey-bykov That is a good point. I think a distinction should be made at least for aggregate operations.
