### ISSUE TITLE
Cannot use HTML<Type>Element types

### ISSUE THREAD

**Issue by ktalebian** [Microsoft/TypeScript#13171]
I cannot ever use type `HTML<Type>Element` for type definitions without warnings.

Here are a few examples, and the errors I get with them:

```
let elem: HTMLSpanElement = (
    <span>Hello World</span>
);
```

Gives me: `Type 'Element' is not assignable to type 'HTMLSpanElement'. Property 'addEventListener' is missing in type 'Element'`

```
let elem: HTMLElement = (
    <span>Hello World</span>
);
```

Gives me: `Type 'Element' is not assignable to type 'HTMLElement'. Property 'accessKey' is missing in type 'Element'.`

What am I missing?

**TypeScript Version:**  2.1.4

**Comment by aluanhaddad** [comment]
This happens I use `"jsx": "preserve"` and have the React declarations installed. Otherwise it doesn't happen. What are you trying to do?

**Comment by rossipedia** [comment]
The problem you're running into is that JSX is not HTML (even though it looks like it).

```jsx
<span>Hello, World</span>
```
gets converted to
```javascript
React.createElement('span', {}, "Hello, World")
```
`React.createElement` returns a `React.DOMElement`, as you can see (using Visual Studio Code):
![image](https://cloud.githubusercontent.com/assets/96213/21492446/2705d492-cbc2-11e6-8673-66fcb35e94eb.png)

This is a _completely_ different object than a `HTMLSpanElement`, and it's due to the fact that React creates a [virtual dom](https://facebook.github.io/react/docs/reconciliation.html), which is a bunch of Javascript objects that _describe_ a DOM, but aren't actual DOM elements. React uses that description to make updates to the real DOM.

Hope that clears things up.

**Comment by ktalebian** [comment]
@rossipedia Ah, I see. So if I want to type define the HTML tags in React, what type should I use?

**Comment by rossipedia** [comment]
All jsx elements appear to be typed `JSX.Element`. Indeed, using that as the explicit type of the variable in your example seems to work fine:

![image](https://cloud.githubusercontent.com/assets/96213/21514010/9abf40e8-cc7c-11e6-837a-739f778ef443.png)
