### ISSUE TITLE
Feature Request. Allow omitting parentheses on decorators with optional parameters 

### ISSUE THREAD

**Issue by snytkine** [Microsoft/TypeScript#13173]
If annotation function has optional parameter(s) allow using annotation without a function call signature

**TypeScript Version:**  2.1.4

**Code**
Example:

```ts

export function Component(name?: string) {

  return function (target: any, propertyKey?: string) {
    
    name = name || target.name
    // implementation
  }

}

```

**Expected behavior:**

In cases like this where argument(s) are optional, allow adding annotation without a function call

```

@Component
export class MyDatabase {

  // implementation
}

```

Parameter can still be passed if desired, in which case use the function call signature

```

@Component('db')
export class MyDatabase {

  // implementation
}

```

**Actual behavior:**
Currently we have to add @Component()

It would be a much cleaner looking to omit () in cases where arguments are optional

**Comment by mhegazy** [comment]
You can have a decorator with no parentheses, e.g.:

```ts
function Component (target: any, propertyKey?: string) {
    // implementation
}

@Component
export class MyDatabase {
  // implementation
}
```

It does mean something different, i do not think we can change that.

**Comment by aluanhaddad** [comment]
From your request, I believe you may be misunderstanding a few things.
  1. There is no such thing as an annotation, these are decorators. (Annotations, if you are interested are a dead ES proposal).
  2. You can achieve what you want but it is not something the language will do for you because the semantics are very different.

To elaborate on point 2. Here is an example of a decorator in TypeScript.
```ts
function decorated(target: {name: string}) {
  console.log(target.name, ' is now decorated');
}

@decorated
class MyClass { }
```
The `Component` function in your example is not a decorator at all it is a _decorator factory_. That is to say it is simply a function which you call, perhaps passing an argument, which _returns_ the decorator that is applied to the target by the `@` syntax.

Since name is optional, and you want to omit the parentheses when it is not provided, you can define a function which serves as a decorator or a decorator factory depending on how it is used.
For example:
```ts
export function Component(nameOrTarget?: string| Function) {
  if (typeof nameOrTarget !== 'string') { 
    console.log(nameOrTarget.name, ' is now decorated');
  } else {
    return function (target: {name: string}) {
    
    name = nameOrTarget || target.name
  }
}

@Component
class MyDatabase { }

@Component('Hello Db')
class MyHelloDatabase {}
```

**Comment by snytkine** [comment]
Interesting idea, unfortunately does not work without Typescript errors. It compiles and resulting JavaScript runs but I am getting typescript errors. I tried to modify it but was unable to make this idea work without compiler errors.

**Comment by aluanhaddad** [comment]
@snytkine Sorry, I didn't bother to typecheck it, just wrote it in the GitHub comment box.
Here it is fully working, fully type-checked under the strictest settings:

```ts
export type Target = {
  new (...args: any[]): any,
  name: string
};

export function Component(target: Target): void;
export function Component(name: string): (target: Target) => void;
export function Component(nameOrTarget: string | Target) {
  if (typeof nameOrTarget !== 'string') {
    console.log(nameOrTarget.name, ' is now decorated');
  } else {
    return function (target: { name: string }) {
      const name = nameOrTarget || target.name;
      console.log(name, ' is now decorated');
    };
  }
}

@Component
export class MyDatabase { }

@Component('Hello Db')
export class MyHelloDatabase { }
```

**Comment by snytkine** [comment]
Great stuff. I did not know you could do function overloading in TypeScript.
It works without errors now.
Thank you.

**Comment by aluanhaddad** [comment]
@snytkine glad to help.

**Comment by dgoldstein0** [comment]
perhaps this should be closed?
