### ISSUE TITLE
Adding identical overload introduces implicit any error

### ISSUE THREAD

**Issue by evmar** [Microsoft/TypeScript#13204]
**TypeScript Version:**  2.1.4 and 2.0 at least

**Code**

```ts
interface Console {
  // uncomment this:
  // error(message?: any, ...optionalParams: any[]): void;
}

console.error = function(message) {};
```

**Expected behavior:**
Code is either legal or illegal, regardless of whether the marked line is uncommented.

**Actual behavior:**
With `--noImplicitAny`, the code is accepted before and rejected after uncommenting the line:

```
foo.ts(2,26): error TS7006: Parameter 'message' implicitly has an 'any' type.
```

The overload of `console.error` here appears to have an identical type signature to the one in the TS standard library.

(This came up in a larger program, where @types/node brings in this additional Console definition.)

**Comment by mhegazy** [comment]
the code is legal. the parameter implicitly gets an `any` as it is type. the issue is if there are more than one overload that are applicable, the compiler does not know which one to use for contextual type. since the function has no type annotations on the parameters, the compiler gives it an implicit `any`. the flag `--noImplicitAny` requires the compiler to warn every time it does that.

**Comment by mhegazy** [comment]
more info at https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#implicit-any-error-raised-for-un-annotated-callback-arguments-with-no-matching-overload-arguments

**Comment by evmar** [comment]
I think I understand.  But the intention of the node d.ts is to define the function if it's not already present.  Maybe the true bug is that the identical signatures are treated as separate overloads?
