### ISSUE TITLE
Decorator should be able to be declared before overloads

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#13210]
Today, TS requires the decorator to be declared at the function implementation, which seems correct. Though, I think it is quite unpleasant to my eyes to have the `autobind` decorator at the positions below:
```ts
public remove(): void
public remove(clause: any): void
public remove(id: string): void
@autobind
public remove(idOrClause?: string | number | any): void {

// or

public remove(): void
public remove(clause: any): void
public remove(id: string): void
@autobind public remove(idOrClause?: string | number | any): void {
```
And it becomes even more unpleasent when we have more than one decorator. The ugly part is that it breaks symmetry. Overloads are either not beginning in the same column as the implementation or there is a newline separating the overloads with implementation.

Is it possible to just place the decorators at the top or before the overloads?: 
```ts
@autobind
public remove(): void
public remove(clause: any): void
public remove(id: string): void
public remove(idOrClause?: string | number | any): void {
```

**Comment by DanielRosenwasser** [comment]
This may be a little bit complex because it opens up a few questions:

1. Are decorators only allowed on the first overload, or all overloads? I'd argue only the first.
2. Are decorators allowed on both the first overload as well as the implementation, or just one?

**Comment by tinganho** [comment]
>Are decorators only allowed on the first overload, or all overloads? I'd argue only the first.

only the first too.
>Are decorators allowed on both the first overload as well as the implementation, or just one?

I would argue on both, since only the first would be a breaking change.

**Comment by DanielRosenwasser** [comment]
I don't think it'd be a breaking change. What I mean to ask is: is the following allowed?

```ts
@foo
public remove(): void
public remove(clause: any): void
public remove(id: string): void
@autobind
public remove(idOrClause?: string | number | any): void {
```

**Comment by aluanhaddad** [comment]
Reading
```ts
@foo @autobind public remove(idOrClause?: string | number | any): void;
```
Linguistically, I think a decorator reads the best, when its name is a descriptive modifier such as an adjective or participle. So I would want to name `autobind` something like `autobound`, `autobinding`, or `autobindable` depending on what it does. Another descriptive modifier used in the example is the visibility modifier `public`. Since I can repeat public, if I am given the ability to place `autobind` on an overload declaration, I would feel like I shoul be able to write it on all of them.
```ts
@fooing @autobound public remove(): void
@fooing @autobound public remove(clause: any): void
@fooing @autobound public remove(id: string): void
@fooing @autobound public remove(idOrClause?: string | number | any): void {
```
Obviously, this makes things more complicated in some respects, and I am probably being pedantic, but it would resolve the ordering issue to say that all decorators must appear on all overloads and all in the same order.

**Comment by mhegazy** [comment]
this behavior is intentional. decorators do not decorate overloads, they decorate implementation. Decorators in general are runtime mappings on functions; they have the ability to change the function implementation they are decorating at definition time.

putting them on overloads is misleading, 1. since they do not change the type, 2. they do not persist on the declaration (e.g. not going to be emitted to the declaration file, etc..), and 3. gives you the impression that you can have multiple of them on one set of overloads. 

moreover, we wanted to reserve this location for future uses of [desing-time decorators](https://github.com/Microsoft/TypeScript/issues/2900).

Implementation signature in TS is treated specially, and decorators only belong on them.

**Comment by aluanhaddad** [comment]
@mhegazy 
> moreover, we wanted to reserve this location for future uses of desing-time decorators.

I was actually thinking of design time decorators when I read this issue. 

> putting them on overloads is misleading, 1. since they do not change the type, 2. they do not persist on the declaration (e.g. not going to be emitted to the declaration file, etc..)

I agree that it doesn't make sense which is what made me think of design time decorators. Design time decorators obviously have a different intention, but currently code that uses (abuses?) decorators looses any conferred semantics because they cannot remain manifest in declaration files. 
For example, take this declaration `toastr.module.d.ts` file from the ng2-toastr library
```ts
export declare class ToastModule {
}
```
Perhaps ambient decorators could help here, or perhaps people should stop using decorators when what they want are actually object literals 🙉
