### ISSUE TITLE
Support a 'vue' option for JSX in .tsx files

### ISSUE THREAD

**Issue by yeluoqiuzhi** [Microsoft/TypeScript#13260]
[feature] Will typescript support compile tsx for vue.js?

**Comment by aluanhaddad** [comment]
It would be nice. https://github.com/vuejs/vue/issues/478

**Comment by yeluoqiuzhi** [comment]
@aluanhaddad That is about using typescript with vue.js. However, we want something that  can compile tsx to js for vue.js.


It would look like this in tsconfig.json.

```js
"jsx": "react",
```

When use with vue.js, we also should use by changing react to vue.

```js
"jsx": "vue"
```

**Comment by davidmoshal** [comment]
+1

**Comment by aluanhaddad** [comment]
@yeluoqiuzhi I understand. The linked issue was also about using TypeScript with vue.js. I linked it to illustrate that there has been interest in this for a several years, and because it is in interesting discussion.
I think it would be great to see TypeScript's `.jsx` support leveraged by another framework.

**Comment by DanielRosenwasser** [comment]
Right now the emit is pretty different between React and Vue's JSX emit. [See the documentation here](https://github.com/vuejs/babel-plugin-transform-vue-jsx#difference-from-react-jsx) that shows what Vue JSX is transformed to.

Vue *does*  support HyperScript, and from my understanding, you can use our `reactNamespace` option to target that. Does this solve your use-case?

**Comment by DanielRosenwasser** [comment]
For the record, you can use `--jsxFactory` and combine with Babel to get around this.

**Comment by yeluoqiuzhi** [comment]
Thanks. We would wait for typescript to support it, rather than use babel.

**Comment by HerringtonDarkholme** [comment]
IMHO, the most significant difference is type checking.  We can already use Babel + TS to transform code, so that would not be hard part for users. Yet type checking part is much more convoluted. 

There are many libraries in wild to support Vue's type checking before official solution. Adopting which model needs proposal. @yeluoqiuzhi should know.

Even if we do only accept official library, type checking `props` and `emit`, two main interface in Vue, requires many changes. Unlike React, Vue's props is declared on the class as properties. There is no such thing like `reactComponent.props` where TypeScript can use to checking JSX. Currently official library uses decorators to annotate `props`.

For custom event, Vue's JSX requires additional `onEvent` prefix for camelCase or `on-event` prefix for kebab-case, while React has none such event handler: every thing is prop.  TS checker needs additional check here. Other things like `ref`, `slot` should also be checked since they are components' API as well.

Finally, I would like to see Vue support can be done by https://github.com/Microsoft/TypeScript/pull/10159. I would expect Vue will be hot in 2017, but what about 2018? 2019? As a language,supporting only some specified libraries feels partisan.

**Comment by DanielRosenwasser** [comment]
@HerringtonDarkholme see #12846 for general support of typing the Vue instance based on its input properties.

**Comment by andrei-markeev** [comment]
Would a PR be accepted that implements this?

**Comment by yeluoqiuzhi** [comment]
I have move to react stack for a year...

**Comment by andrei-markeev** [comment]
I've created a PoC and it seems to work pretty well. Successfully used it for compiling a medium sized application (~2000 lines of Vue.js templates).

Can someone from the core team decide if a PR will be considered for this feature, i.e. `--jsx vue` mode? Affects small part of code, doesn't affect language design. Should I finalize the work?

Screenshot of a basic test:
![image](https://user-images.githubusercontent.com/5181724/42130731-f74c44c0-7cf5-11e8-9921-1369a4758e4b.png)

In case anyone wants to peek at the code (work in progress):
https://github.com/andrei-markeev/TypeScript/commit/56b951f5ae62e0eb06c0bf6d1459c3ec81752720

**Comment by wanton7** [comment]
Any news on this? Our company uses Vue components and TypeScript in Visual Studio 2017 without build pipeline. Meaning we just have Vue included in with script tag in our HTML. Having support for tsx would really help us.

**Comment by david50407** [comment]
Although this issue is closed by author, I think there is still a good benefit to TypeScript and Vue.

How about re-open this issue? @aluanhaddad @DanielRosenwasser

**Comment by skyrpex** [comment]
Maybe we should open a new issue?

**Comment by wartmanm** [comment]
I rebased and updated @andrei-markeev's PoC: [wartmanm@vue-jsx](https://github.com/wartmanm/TypeScript/tree/vue-jsx).
I haven't used it extensively yet, but it passes all of Vue's tests in [babel-plugin-transform-vue-jsx](https://github.com/vuejs/babel-plugin-transform-vue-jsx/blob/master/test/test.js).
