### ISSUE TITLE
Hover for method signatures too aggressive 

### ISSUE THREAD

**Issue by isidorn** [Microsoft/TypeScript#13268]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**
Clonse vscode repository, open 
1. debugViews.ts: 316, start typing the following line

 ```javascript	
this.toDispose.push(this.debugService.getViewModel
```

Notice how the hover help appears for push and never goes away. I understand that I am still in the arguments of the push method but for me as a user this is very irritiating - especially since I know how to use the push method of an array.
Not sure how to best improve this - but I would be happy if I could at least disable this hover help which never helps me but alwasy gets in my way.

From https://github.com/Microsoft/vscode/issues/17765

![screen shot 2016-12-23 at 10 44 18](https://cloud.githubusercontent.com/assets/1926584/21451165/2df78844-c8fd-11e6-9a52-555f46301ab1.png)

**Comment by mhegazy** [comment]
This is intentional, to make it easy to write object literals, or lambdas, or other function calls. 

Completion list takes precedence over signature help. so even if you are in the middle of a signature help session, once you hit `.` you will see the completion list.

Also at any point you can dismiss the signature help by hitting the `Esc` button.
