### ISSUE TITLE
Inferred functions returning union with `void` require explicit return statement

### ISSUE THREAD

**Issue by gcnew** [Microsoft/TypeScript#13284]
**TypeScript Version:** nightly (2.2.0-dev.20170104)

**Code**

Flags: all safety flags including `noImplicitReturns` and `strictNullChecks`

```ts
function test(x: any): false | void {
    if (x === false) {
        return false;
    }

    // OK, no error
}

const testInferred: (x: any) => false | void = (x) => {
    if (x === false) {
        return false;
    }

    // Error: `Not all code path return a value`
}
```

**Expected behavior:**
Inferred and directly annotated functions should work the same way.

**Actual behavior:**
The lambda function of `testInferred` requires an explicit return statement.

Edit: updated the code samples / error as I explored the options.

**Comment by gcnew** [comment]
Works fine with `void`

```ts
function test(x: any): false | void {
    if (x === false) {
        return false;
    }

    // no errors :)
}
```

**Comment by gcnew** [comment]
Reopening with updated info

**Comment by mhegazy** [comment]
Not sure i see why this should not error. the lambda does not have a declared return type, so one is inferred as per the [spec](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#63-function-implementations) namely:
> Otherwise, if f is a contextually typed function expression (section 4.10), the inferred return type is the union type (section 3.4) of the types of the return statement expressions in the function body, ignoring return statements with no expressions.

That is when the error is reported.

The result then undergoes an assignment compatibility check with the left handsisde, and it passes since `(x:any) => false` is assignable to `(x: any) => false | void`.

**Comment by mhegazy** [comment]
lambdas could have return type annotations as well..
```ts
const testInferred = (x: any): false | void => {
    if (x === false) {
        return false;
    }
}
```
