### ISSUE TITLE
Support @this in Salsa

### ISSUE THREAD

**Issue by Kovensky** [Microsoft/TypeScript#13308]
**TypeScript Version:**  2.2.0-dev.20170102 (--strictNullChecks)

**Code**

```js
/**
 * @param {Event} e
 * @this Element
 */
function eventHandler (e) {
  this.nodeName // type is 'any'
  e // type is 'Event'
}
```

**Expected behavior:**

The `@this` comment to work like the `this:` parameter given on typescript functions.

```ts
// typescript version of the above
function eventHandler(this: Element, e: Event) {
  this.nodeName // type is 'string'
  e // type is 'Event'
}
```

See http://usejsdoc.org/tags-this.html

**Comment by aluanhaddad** [comment]
I've been meaning to ask this for a while and since you provided a link to http://usejsdoc.org, I will use this as an opportunity. As the TypeScript team has stated, JSDoc types have multiple interpretations. Is TypeScript trying to understand all of them and, if so how does it determine the boundaries between a [JSDoc 3](https://github.com/jsdoc3/jsdoc3.github.com) type and a [Closure-Type-System](https://github.com/google/closure-compiler/wiki/Types-in-the-Closure-Type-System) type?

**Comment by Kovensky** [comment]
I actually did not know of closure-type-system :(

I have been using `@this` as a requirement of the http://eslint.org/docs/rules/no-invalid-this eslint rule.

**Comment by Cow258** [comment]
When will it support for Salsa?
