### ISSUE TITLE
Using switch on discriminated unions with an unrecognized discriminant

### ISSUE THREAD

**Issue by jinder** [Microsoft/TypeScript#13467]
**TypeScript Version:**  2.1.5

**Code**
```
class ActionTypes {
    public static readonly TypeA = "TypeA";
    public static readonly TypeB = "TypeB";
}

interface Action {
    type: string;
    payload?: any;
}

class ActionA implements Action {
    public readonly type = ActionTypes.TypeA;
    constructor(public payload: {}) { }
}

class ActionB implements Action {
    public readonly type = ActionTypes.TypeB;
}

declare type Actions = ActionA | ActionB;

let otherType = "something-else";

function test(action: Actions | Action) {
    switch (action.type) {
        case otherType:
            console.log("Something Else");
            break; 

        case ActionTypes.TypeB:
            console.log("ActionB");
            break;

        case ActionTypes.TypeA:
            console.log("ActionA", action.payload);
            break;  
    }
}

```

**Expected behaviour:**

The last switch statement should narrow to TypeA.  It doesn't when the input parameter is of type "Actions | Action" or the otherType switch statement is there.

**Actual behaviour:**

Property 'payload' does not exist on type Action | ActionA | ActionB.  Property payload does not exist on type ActionB.

**Comment by aluanhaddad** [comment]
This is expected.
```ts
Actions | Action
```
is equivalent to
```ts
type A = { type: string, payload? };
```
The `type: string` in the interface subsumes the rest of the union, making it impossible for the type guards to narrow from it.

Consider using this pattern instead
```ts
namespace ActionTypes {
  export const TypeA = "TypeA";
  export const TypeB = "TypeB";
}

class ActionA {
  readonly type = ActionTypes.TypeA;
  constructor(public payload: {}) { }
}

class ActionB {
  readonly type = ActionTypes.TypeB;
}

type Actions = ActionA | ActionB;

function test(action: Actions) {
  switch (action.type) {

    case ActionTypes.TypeB:
      console.log("ActionB");
      break;

    case ActionTypes.TypeA:
      console.log("ActionA", action.payload);
      break;
    default:
      console.log("Something Else");
      break;
  }
}
```

**Comment by jinder** [comment]
@aluanhaddad I see, thank you.  I guess I don't see quite why it would subsume like that. 

Closing as this seems to be expected behaviour.

**Comment by aluanhaddad** [comment]
@jinder The reason is basically that if we say that a type `T` represents _either_ any `string` _or_ respresents some specific `string` `S` we are saying that `T` represents any `string` since the specific `string` `S` is one of a `string` that can be represented by `T`. This makes the union "collapse". Does this sound right?

**Comment by rkrisztian** [comment]
This solution is not good enough for actions in general because we need the {{Action}} interface. 

For example, [find-book-page.ts](https://github.com/ngrx/example-app/blob/master/src/app/containers/find-book-page.ts) dispatches an action:

`this.store.dispatch(new book.SearchAction(query));`

And [book.ts](https://github.com/ngrx/example-app/blob/master/src/app/effects/book.ts) needs to define an `Observable<Action>`.

I guess casting would be a workaround, but having to do that everytime an `Action` object is needed, would be cumbersome.
