### ISSUE TITLE
strictNullChecks and Object.create(null)

### ISSUE THREAD

**Issue by anilanar** [Microsoft/TypeScript#13524]
**TypeScript Version:**  2.1.5

**strictNullChecks: true**

**Code**

```ts
type Foo = {
    bar: {[key: string]: number} | undefined; 
};

function fn(foo: Foo) {
    foo.bar = foo.bar === undefined
        ? Object.create(null)
        : foo.bar;

    foo.bar['quu'] = 5; // error on this line
}
```

**Expected behavior:**

No errors from tsc

**Actual behavior:**

`foo.bar - error TS2532: Object is possibly 'undefined'.`

If `Object.create(null)` is replaced with `{}`, no errors from tsc. I guess this has something to do with return type of `Object.create` being `any`?

**Workaround:**
`Object.create(null) as {}`

**Comment by aluanhaddad** [comment]
This happens because control flow analysis does  not inherently affect the types of members.
Consider
```ts
type Foo = {
    bar: {[key: string]: number} | undefined; 
};
const foo = {
  get bar() { return Math.floor(Math.random() * 2) === 0 ? { quu: 5 } : undefined;
};
```

**Comment by ahejlsberg** [comment]
The issue here is that `Object.create(null)` is declared to return type `any`, which means the result of the conditional expression becomes `any`. When you assign `any` to `foo.bar`, the control flow analyzer reverts to the declared type (i.e. `{ [key: string]: number } | undefined`) and therefore complains that the value might be undefined. You can fix the issue by coercing the result of `Object.create(null)` to a type that is known not to be `undefined`. For example, this works:

```ts
function fn(foo: Foo) {
    foo.bar = foo.bar === undefined
        ? Object.create(null) as {}
        : foo.bar;

    foo.bar['quu'] = 5; // Ok
}
```

**Comment by anilanar** [comment]
Then I guess there is nothing `strictNullChecks` can do here.
