### ISSUE TITLE
declaration: Namespace which exports class can't be merged with variable

### ISSUE THREAD

**Issue by ikokostya** [Microsoft/TypeScript#13536]
**TypeScript Version:** 2.2.0-dev.20170117

I try to write declaration for [got](https://github.com/sindresorhus/got) module.

**Code**

```ts
// Use interface, because `got` function has `delete` property.
interface GotApi {
    (): any;
    delete(): any;
}

declare var got: GotApi;

declare namespace got {
    export class HTTPError extends Error {}
}

export = got;
```

**Expected behavior:**

No errors. `HttpError` class is available using `got` exported variable:

```ts
import * as got from 'got';

// let error = ...
if (error instanceof got.HTTPError) {
}
```

**Actual behavior:**

I get compiler errors for declaration file:

```
index.d.ts(6,13): error TS2300: Duplicate identifier 'got'.
index.d.ts(8,19): error TS2300: Duplicate identifier 'got'.
```

Used tsconfig.json:

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "moduleResolution": "node",
        "target": "es2015",
        "noImplicitAny": true,
        "strictNullChecks": true,
        "outDir": "build"
    }
}
```

Related issue: https://github.com/Microsoft/TypeScript/issues/1784

**Comment by aluanhaddad** [comment]
Note that the GotApi interface is not exported

**Comment by ikokostya** [comment]
> Note that the GotApi interface is not exported

How interface should be exported? This code (similar to [request](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/request/index.d.ts) declaration) also isn't compiled with the same error:

```ts
declare namespace got {
    export interface GotApi {
        (): any;
        delete(): any;
    }

    export class HTTPError {}
}

declare var got: got.GotApi;
export = got;
```

If remove class export from namespace, compilation is completed:

```ts
interface GotApi {
    (): any;
    delete(): any;
}

declare var got: GotApi;

declare namespace got {
    // export class HTTPError extends Error {} <--- Comment this line
}

export = got;
```

**Comment by mhegazy** [comment]
Ideally this would be rewitten as function+namespace but it can not, https://github.com/Microsoft/TypeScript/issues/1784 (and https://github.com/Microsoft/TypeScript/issues/9846) track that.

Instantiated namespaces (i.e. ones that has a value in them) can not merge with variables, since one of them will override the other at run-time.

you can write your declaration as such:

```ts
declare class HTTPError { }

interface GotApi {
    (): any;
    delete(): any;
    HTTPError: typeof HTTPError;
}

declare var got: GotApi;
export = got;
```

**Comment by ikokostya** [comment]
> Instantiated namespaces (i.e. ones that has a value in them) can not merge with variables, since one of them will override the other at run-time.

As I understand from [documentation about declaration merging](http://www.typescriptlang.org/docs/handbook/declaration-merging.html) function and variable are value creating declarations, i.e. 

```ts
interface GotApi {
    (): any;
}
declare var got: GotApi;
declare namespace got {
    export class HTTPError {}
}
export = got;
```
and

```ts
interface GotApi {
    (): any;
}
declare var got: GotApi;
declare namespace got {
    export class HTTPError {}
}
export = got;
```

both fails to compile. But function *declaration* compiles:

```ts
declare function got(): any;
declare namespace got {
    export class HTTPError {}
}
export = got;
```

Why this happen?

Also, I propose to make error message is more detailed, because current message `error TS2300: Duplicate identifier 'got'.` is cryptic at first glance. For example, `namespace and variable declaration can't be merged'.

**Comment by mhegazy** [comment]
`var got: ()=> any` is treated as a variable, and not as a function declaration. the reason is a variable can be assigned to later on where as a function can not.

**Comment by ikokostya** [comment]
@mhegazy Thanks for explanation.

**Comment by BendingBender** [comment]
@mhegazy So why is it then not allowed to merge a `declare const` with a `declare namespace`? AFAIK, `const` is also not assignable more than once.

**Comment by thorn0** [comment]
Merging `const`s with namespaces really makes sense. Please consider reopening this issue. It's not a duplicate #1784.

For example, let's take TinyMCE writing proper type definitions for which require this feature. Namespaces are really convenient for describing types for this library because all the classes from the [API](https://www.tinymce.com/docs/api/) are attached to the `tinymce` namespace object or to its subnamespaces. In the API, there are normal classes like `tinymce.Editor` and so called 'static classes' like `tinymce.EditorManager` which are just a type (interface) and an object value of this type attached to the namespace:
```ts
declare namespace tinymce {
  // normal class
  class Editor {
    show(): void;
    // ...
  }
  // "static class"
  interface EditorManager {
    activeEditor: Editor;
    // ...
  }
  const EditorManager: EditorManager;
  // ...
}
```
Nothing unusual so far, but there is a plot twist. The namespace object `tinymce` itself implements the `EditorManager` interface. It could be easily solved by merging a `const` with the namespace:
```ts
declare const tinymce: tinymce.EditorManager;
```
But unfortunately this isn't allowed.
