### ISSUE TITLE
Union of string and literal type results in error

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#13580]
tsc: 2.2.0-dev.20170119 and 2.1.5

```ts
interface B {
    p: string
    q: string
}
interface C {
    p: 's'
    r: number
}

type X = B | C

let x: X = {  // <-- error
    p: 's',
    r: 1
}
```

Error message:
```
Type '{ p: string; r: number; }' is not assignable to type 'X'.
  Type '{ p: string; r: number; }' is not assignable to type 'C'.
    Types of property 'p' are incompatible.
      Type 'string' is not assignable to type '"s"'.
```

Playground repro:
http://www.typescriptlang.org/play/index.html#src=interface%20B%20%7B%0D%0A%20%20%20%20p%3A%20string%0D%0A%20%20%20%20q%3A%20string%0D%0A%7D%0D%0Ainterface%20C%20%7B%0D%0A%20%20%20%20p%3A%20's'%0D%0A%20%20%20%20r%3A%20number%0D%0A%7D%0D%0A%0D%0Atype%20X%20%3D%20B%20%7C%20C%0D%0A%0D%0Alet%20x%3A%20X%20%3D%20%7B%0D%0A%20%20%20%20p%3A%20's'%2C%0D%0A%20%20%20%20r%3A%201%0D%0A%7D%0D%0A%0D%0A

**Comment by mhegazy** [comment]
In `B|C` property `p` has the type `string | 's'` which is essentially a `string`. the type of `p` in the object literal then is inferred as `string` because of the contextual type. but then the assignment compact fails, since it is not assignable to `B`, nor to `C`.

so we can either disable the optimization to remove literal types if its base type exists in a union, leaving `(B|C).p` stay `string | 's'`, or infer a literal type if the contextual type is the base liteal type

**Comment by mhegazy** [comment]
Same issue reported in https://github.com/Microsoft/TypeScript/issues/13628

**Comment by RyanCavanaugh** [comment]
Proposed fix is to retain literal types when a primitive contextual type is present

**Comment by mhegazy** [comment]
Seems fixed in latest.
