### ISSUE TITLE
lib.es5.d.ts: Date#toGMTString declaration is missing

### ISSUE THREAD

**Issue by ikokostya** [microsoft/TypeScript#13622]
**TypeScript Version:**  2.2.0-dev.20170117 

**Code**

```ts
(new Date()).toGMTString();
```

**Expected behavior:**

No errors.

**Actual behavior:**

Error: `Property 'toGMTString' does not exist on type 'Date'.`

MDN link https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toGMTString

This method is deprecated, but still available in browsers and Node.js.

**Comment by blakeembrey** [comment]
> Note: toGMTString() is deprecated and should no longer be used. It remains implemented only for backward compatibility; please use toUTCString() instead.

Why not just use the non-deprecated method instead?

**Comment by ikokostya** [comment]
> Why not just use the non-deprecated method instead?

I use. But, anyway I think, that this method should be declared, because it's available from JavaScript.

**Comment by SaschaNaz** [comment]
You can manually do:

```ts
interface Date {
  toGMTString(): string;
}
```

**Comment by ikokostya** [comment]
@SaschaNaz Issue about missing declaration in `lib.es5.d.ts`. I known how it may be fixed locally.

**Comment by mhegazy** [comment]
The method is intentionally redacted from the declaration file as it has since been removed from the standard. The lib files are commutative, i.e. `lib.es2015.d.ts` includes `lib.es5.d.t.s`, s 

From a correctness point of view, the API should be included, but marked as deprecated. We can revisit this after https://github.com/Microsoft/TypeScript/issues/390 is supported.

**Comment by RyanCavanaugh** [comment]
Declining due to lack of other feedback
