### ISSUE TITLE
does Typescript address global package for module resolution in compiling

### ISSUE THREAD

**Issue by vincedan** [Microsoft/TypeScript#13659]
it seems that typescript only support local npm package...  why not support addressing global package in compiling?  I have posted [this question](http://stackoverflow.com/questions/41662098/does-typescript-address-global-package-for-module-resolution-in-compiling) on stackoverflow..

**Comment by blakeembrey** [comment]
@vincedan That's not really how node.js works, that's why. You should always install your modules locally, `-g` is typically only used when you want to install a CLI application. It is **not** to make all your projects use the same `bluebird`. You can read the docs for NPM here: https://docs.npmjs.com/getting-started/installing-npm-packages-globally.

It might be easier if you explain what you want to do, because you have a few different things mixed up here.

**Comment by vincedan** [comment]
@blakeembrey , thanks you for your quick answer. I am new in this domain. . and short of basic knowledge here..  
let me try to clarify my question again:  
for instance, I have a lot of projects....need the same package. right now,, I need to install (or place) that package in each project folder -"node_modules".    by typescript handbook I know there are some trick s(for example:  all projects have the same parent folder ... and put package only once here) ,  I guess if typescript can address this package that I install it in global.....

for version controlling on NPM, it seems there are some switch to specify the version  of package you want to get... 
 
actually you have answered my question... global package is only for CLI application at least at this time point. 
thanks again. I close this question.

**Comment by blakeembrey** [comment]
@vincedan No problem 😄  I suspected that may have been what you expected. Node doesn't work like some other languages in that regard - packages are _always_ installed locally so you'd need to install it as different dependencies on different projects. This makes development of node packages much simpler, as the dependencies aren't shared anywhere else and won't cause odd conflicts if you're working on two different projects.
