### ISSUE TITLE
allow lower-case functions be stateless JSX components 

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#13667]
```
declare function fn(): JSX.Element;
console.log(<div><fn /></div>); // <-- doesn't work
```

```
declare function Fn(): JSX.Element;
console.log(<div><Fn /></div>); // <-- works, huh?
```

Can I ignore case in TypeScript?

![giphy](https://cloud.githubusercontent.com/assets/937933/22276127/8c7a23c2-e27f-11e6-9864-23691d8fd62d.gif)

**Comment by basarat** [comment]
Workaround: 

```tsx
declare function fn(): JSX.Element;
const Fn = fn;
console.log(<div><Fn /></div>);
```

I am sure you know that `<fn/>` will not work with react transformer right?

**Comment by jesseschalken** [comment]
IIRC it's part of how JSX works - case of the first letter determines how the tag gets transpiled.

**Comment by aleksey-bykov** [comment]
> I am sure you know that <fn/> will not work with react transformer right?

i am not using react, i only need jsx to work

> IIRC it's part of how JSX works - case of the first letter determines how the tag gets transpiled.

a spec?

**Comment by jesseschalken** [comment]
@aleksey-bykov You can look for a spec just as well as I can, but it is that way because JSX transpilation has to be possible without knowing what symbols exist and which ones don't. If `<fn />` refers to the variable `fn`, `div` could just as well refer to some global variable called `div` that the transformer doesn't know about. The transpiler needs to distinguish components from builtins to know what to emit, and without knowing all the symbols and/or all the builtins that exist.

**Comment by basarat** [comment]
> case of the first letter determines how the tag gets transpiled.

JSX spec is ignostic about it : https://facebook.github.io/jsx/

However it matters when transpiling it for *react* https://facebook.github.io/react/docs/jsx-in-depth.html#user-defined-components-must-be-capitalized. Hence `I am sure you know that <fn/> will not work with react transformer right?` :rose: I can be wrong of course :heart: @aleksey-bykov which framework are you using? (CycleJS / InfernoJS follow the same React convention)

**Comment by aleksey-bykov** [comment]
@jesseschalken 
not sure why react or anything else matters, if you think about it JSX came first and thus has nothing to do with react, react has everything to do with JSX

as far as typescript goes, there is no problem to map lower-case functions to components, because it's either a function or a class or a element declared in `IntrinsicElements`, so no ambiguity 

now back to the react agument, if for some reason react isn't happy with lower-case functions, then do not use them if you work with react

a limitation of react should not be a limitation of a technology that react is built upon, should it?


@basarat 

i don't use any frameworks, i do `--jsxFactory` with my custom function

**Comment by jesseschalken** [comment]
> as far as typescript goes, there is no problem to map lower-case functions to components, because it's either a function or a class or a element declared in IntrinsicElements, so no ambiguity

So say I define a toplevel symbol called `div` with type `any`. Should all occurrences of `<div>` now transpile to `jsxFactory.createElement(div, ...)` instead of `jsxFactory.createElement('div', ...)`? Or say your JSX factory now supports a `<fn>` element, should all `<fn ..>` now transpile to `jsxFactory.createElement('fn', ...)` instead of `jsxFactory(fn, ..)`?

Even if the ambiguity resultied in an error which you must resolve, I can cause your code not to compile by defining `div` at the toplevel, and the `div` intrinsic becomes inaccessible. Not to mention you then have a situation where the addition of toplevel symbols or new intrinsic elements, which _should_ be a backwards compatible change, can break the compilation of existing code.

That's why intrinsics and JSX components are in different namespaces.

**Comment by aleksey-bykov** [comment]
according to https://github.com/Microsoft/TypeScript/issues/5478#issuecomment-154583485
> stateless functional component: A function of at most three parameters that returns a JSX.Element.
> Example: SimpleGreeter

so no, `div: any` won't result into `jsxFactory.createElement(div, ...)` it might result to `jsxFactory.createElement('div', ...)` if there is a `div` entry in `IntrinsicElements`

if you have `function div(): JSX.Element` and `interface IntrinsicElements { div: JSX.Element; }` then the emit should be `jsxFactory.createElement(div, ...)`

no ambiguity as far as i see it

breaking change? very unlikely unless you use `function a(): JSX.Element` and `function div(): JSX.Element` all over your code... now do you? why?

**Comment by RyanCavanaugh** [comment]
It's extremely likely that people write things like
```ts
let div = <div ... />;
```
which we would then dutifully emit incorrectly.

If you want different semantics about intrinsic vs class emit than React, that's what `--jsx preserve` and your own transformer are for.

**Comment by aleksey-bykov** [comment]
@RyanCavanaugh 
```
let div = <div .../>
```
will emit correctly, because as you said in the comment https://github.com/Microsoft/TypeScript/issues/5478#issuecomment-154583485

it can only be a problem when `div` is a **function signature with the return type `JSX.Element`**

yes i want JSX semantic that is agnostic of any framework specifically react

**Comment by RyanCavanaugh** [comment]
I know that you know about not doing type-directed emit

**Comment by aleksey-bykov** [comment]
you got me, crap
