### ISSUE TITLE
Find-all-refs for mapped type does not work on access

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#13690]
**TypeScript Version:**   nightly (2.2.0-dev.20170125)

```ts
/// <reference path='fourslash.ts'/>

////interface T { [|a|]: number; }
////type U = { [K in keyof T]: string };
////declare const t: T;
////t.[|a|];
////declare const u: U;
////u.[|a|];

const [r0, r1, r2] = test.ranges();
verify.referencesOf(r2, [r0, r1, r2]);
```

**Comment by use-strict** [comment]
@mhegazy , got the same problem with `Readonly` and the latest React typings. Basically, React props are defined as Readonly and it breaks highlighting/go-to/find references/rename. Of course I could use the pre-2.1 typings for React, but that only solves part of the problem. In reality we're back to the stone age using string-based search and I'd really hate to have to wait till May for a fix. Is there any chance this could be fixed with 2.2? Thank you.

And here is an example to reproduce the issue:
```
interface TestProps {
    foo: string;
}
class Test<T extends TestProps> {
    props: Readonly<T>;
    constructor() {
        let x = this.props.foo;
    }
}
```
