### ISSUE TITLE
pop on non empty string[] should return string type

### ISSUE THREAD

**Issue by bertyhell** [Microsoft/TypeScript#13693]
**TypeScript Version:**  2.2

When i split a string and then pop, typescript warns about a possible undefined value. Isn't there a way to know that the value will never be null using flow control analysis?

![image](https://cloud.githubusercontent.com/assets/1710840/22312900/513e60ee-e35a-11e6-9752-15956877f2b6.png)

I have strictNullChecks enabled.
My **input: string** variable is not **null,** since it check that.
So when i call **split('.')** it will return a non empty array.
Then calling pop() should return a **string** value and not a **string | undefined** value.

Or doesn't the flow control analysis keep track of empty/non empty arrays?

**Code**
```ts
function getExtension(input: string | undefined | null) {
  if (!input) {
    return input;
  }
  let extensionCandidate: string = input.split('.').pop();
  // Type 'string | undefined' is not assignable to type 'string'. Type 'undefined' is not assignable to type 'string'.
  return extensionCandidate;
}

console.log('first:' + getExtension('my-video-file.mp4'));
console.log('second: ' + getExtension('my-video-file'));
```

**Expected behavior:**
The analysed type of **input.split('.').pop()** should be **string**

**Actual behavior:**
The analysed type of **input.split('.').pop()** is **string | undefined**

**Comment by RyanCavanaugh** [comment]
This would take a huge amount of special casing:
 * The argument to `split` can't be the empty string (`"".split("") === []`)
 * We have to know that the *first* call to `pop` is not-undefined but any subsequent calls *might* be undefined
 * We have to know the array isn't modified via some other callback in the meantime (i.e. if you were to assign the result to a local first)

Whereas
 * You could just write `arr[0]` instead of `arr.pop()`

**Comment by bertyhell** [comment]
Ok, thx for the explanation
