### ISSUE TITLE
Control flow analysis for implicit any and array initialization works only when --noImplicitAny is on

### ISSUE THREAD

**Issue by zhuravlik** [Microsoft/TypeScript#13779]
**TypeScript Version:**  2.1.1 / 2.2.0 nightly (current master)

As far as I understood from both [#11263](https://github.com/Microsoft/TypeScript/pull/11263) and [#11432](https://github.com/Microsoft/TypeScript/pull/11432), control flow analysis for implicit any and array initialization shouldn't be limited to the case when _--noImplicitAny_ is enabled.

But currently it works _only_ if _--noImplicitAny_ is on.
If _--noImplicitAny_ is off, variables are treated as 'any', and arrays are treated as 'any[]', after all the initializations.

```ts
function foo(flag: boolean) {
let a;
if (flag)
   a = 5;
else
  a = true;

a; // if --noImplicitAny is on, it is 'number | boolean', otherwise, it is 'any'
}
```

Is it an expected behavior, or should CFA for implicit any and array initialization work regardless of the state of _--noImplicitAny_ flag?

**Comment by mhegazy** [comment]
> Is it an expected behavior, or should CFA for implicit any and array initialization work regardless of the state of --noImplicitAny flag?

this is an intentional decision to limit the analysis to --noImplicitAny flag users. the rational is it is not a breaking change for `--noImplicitAny` users, who were getting errors on the original declaration, it is rather an enhancement to the the experience, i.e. less errors if the compiler can figure it out. Doing it for all users would have been a breaking change.

**Comment by zhuravlik** [comment]
Thanks a lot for the explanation!
