### ISSUE TITLE
instanceof operator doesn't work properly since 2.1.4

### ISSUE THREAD

**Issue by dvabuzyarov** [Microsoft/TypeScript#13896]
**TypeScript Version:**  2.1.5

**Code**

```ts
export class HttpError extends Error {
    constructor() {
        super();
    }
}

export class HttpLoginError extends HttpError {
    constructor() {
        super();
    }
}

const error = new HttpLoginError();
```

**Expected behavior:**
(error instanceof HttpLoginError); //returns true
(error instanceof HttpError); //returns true
(error instanceof Error); //returns true

**Actual behavior:**
(error instanceof HttpLoginError); //returns false
(error instanceof HttpError); //returns false
(error instanceof Error); //returns true

**Comment by DanielRosenwasser** [comment]
This was an intentional change in 2.2 (see #12123 and [the section on our wiki](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#extending-built-ins-like-error-array-and-map-may-no-longer-work)), but is difficult to overcome through compilation. I believe there's some conversation in #12790 for workarounds.

A workaround you can take now is create an intermediate class that you can extend from.

```ts
export interface MyErrorStatic {
    new (message?: string): RxError;
}
export interface MyError extends Error {}

export const MyError: MyErrorStatic = function MyError(this: Error, message: string) {
    const err = Error.call(this, message);
    this.message = message;
    this.stack = err.stack;
    return err;
} as any;

export class HttpError extends MyError {
    // ...
}

```

In TypeScript 2.2, you'll be able to set the prototype on your own.

```ts
// Use this class to correct the prototype chain.
export class MyError extends Error {
    __proto__: Error;
    constructor(message?: string) {
        const trueProto = new.target.prototype;
        super(message);

        // Alternatively use Object.setPrototypeOf if you have an ES6 environment.
        this.__proto__ = trueProto;
    }
}
```
