### ISSUE TITLE
semver guidelines for libraries with typings

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#13892]
This is a discussion tailor to JavaScript libraries distributing their own typings.

Changing typings can easily break builds, even if the underlying JavaScript code doesn't change.

We should have a guideline to describe when should it be considered a minor/major version bump.

On the other hand, since the JavaScript code doesn't change (or only worth a patch version bump), if we recommend to bump minor/major version when the typings changes, the consumer who consumes the library in JavaScript project could be confused by these version changes because there are no code changes to them.

**Comment by mhegazy** [comment]
If you own the package, and you include the declaration files with your package, then you should follow semver for your .d.ts files just like you do for your .js files. 

if the declaration file change is breaking, then it should be under a major version, otherwise use a minor version. 

This means that you can be shipping new versions the package that differ only in .d.ts content, but that is no different from any other non-js resources that your package can carry, e.g. package.json or .css files.

**Comment by unional** [comment]
Agree to what you say, but may not fly for the package authors because they may think typings (and flow definitions) are additional and have a different point of view.

Is education the only option?

**Comment by mhegazy** [comment]
The other option is to build a while different system for getting definitions. we believe npm is a good system to use, it saves the users from learning about a new system altogether.
