### ISSUE TITLE
Generic types wrapped with Partial cannot be assigned to empty objects

### ISSUE THREAD

**Issue by JustASquid** [Microsoft/TypeScript#13908]
**TypeScript Version:**  2.1.4

**Code**

```ts

interface I {
	a: string;
}

function f1<T extends Partial<I>>() {
	// Error TS2322
	let i: T = {};
}

function f2<T extends I>() {
	// Error TS2322
	let i: Partial<T> = {};
}

```

**Expected behavior:**
No errors

**Actual behavior:**
Error TS2322: Type '{}' is not assignable to type 'T' / 'Partial<T>'

Forgive me if this is simply a limitation of the Typescript engine and the implementation of Partial, but I don't know enough about the internals to make a judgement there.

**Comment by RyanCavanaugh** [comment]
The first example is not a bug. Being constrained by a partial type does not mean that you don't have additional required properties. Remember that a constraint is an *upper* bound on a type, not a *lower* bound - the concrete type of `T` at any call site may have additional properties and those properties may be required; the `Partial<I>` constraint only means that any properties in `T` which match those of `I` must have types which are assignable to the corresponding types in `I`

The second example is fixed in `master`.

**Comment by JustASquid** [comment]
Thanks Ryan, you're totally right about the first case.
