### ISSUE TITLE
lib.ie.d.ts

### ISSUE THREAD

**Issue by NN---** [Microsoft/TypeScript#13919]
IE specific functions have been removed from lib.d.ts, see #3953.
Can we have lib.ie.d.ts with IE specific functions which will be manually added if someone needs old IE suppor t?

**Comment by mhegazy** [comment]
For context, we generate the DOM types automatically from the Edge (previously IE) webidl files. This makes it much easier for us to keep the file update, and gives us fairly accurate declarations. you can find more information about how this is done in https://github.com/Microsoft/TSJS-lib-generator. The main reason IE-specific declarations were removed, is that Edge decided to remove them, and become more standard-compliant. 

Similar to https://github.com/Microsoft/TSJS-lib-generator/issues/101, we have no plans to go add additional files to the library (primarily because of the cost of creation and maintenance); but if some one is instead in automatically building these files from web idl, or any other consistent source, we would be happy to host them as variant library, or on Definitely typed.

**Comment by NN---** [comment]
I can add @types/ie you package, it is not a problem.
Just wondered if you wanted to have it out of the box.
