### ISSUE TITLE
Comma Separated Properties

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/TypeScript#13998]
**TypeScript Version:**  2.1.6

It would be nice/handy if TypeScript supported comma separated properties where properties could be grouped by a type. Below is some pseudo code.

**Code**

```ts
class TestClass {
    public -> (a = 1, b = 2, c = 3, d = null, e, f, g): number;
}
```

**Comment by krryan** [comment]
What's with the `->` operator there? What is it supposed to signify? Just the beginning of the group (if so, why do we need it?)?

**Comment by DanielRosenwasser** [comment]
Access modifiers are already a bit of a divergence from the property declarations proposal for ECMAScript. While the shorthand would be nice, `public`-by default and inference already saves you from a lot of the typing you'd have to do otherwise.

```ts
class TestClass {
    a = 1;
    b = 2;
    c = 3;
    d: number = null;
    e: number;
    f: number;
    g: number;
}
```

Unfortunately to avoid conflicting with ECMAScript itself, I think we'll have to rule something like this as out of scope.
