### ISSUE TITLE
Observe @private and @protected in JSDocs for Property Suggestions

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#14009]
From: https://github.com/Microsoft/vscode/issues/5163

**TypeScript Version:**  2.2.0- 20170210

**Code**

```js
class Foo {
    /**
     * abc docs 
     * 
     * @private
    */
    abc;

    /**
     * xyz docs
     * 
     * @public
     */
    xyz;

}

(new Foo()).|
```

**Expected behavior:**
When triggering suggestions on instances of `Foo`, an entry for `abc` is not returned.

**Actual behavior:**
All members of `Foo` are returned. The `@private` annotation seems to be ignored.

**Comment by s-bauer** [comment]
Any update on this?

**Comment by Samlv9** [comment]
the `@internel` also does not work.
![image](https://user-images.githubusercontent.com/6926770/50685046-b4e85b00-1052-11e9-9aa4-f414860c462f.png)

**Comment by vschoener** [comment]
Hello,

Any news about this one? I got the same issue working with last TypeScript version (3.3333) I can access my protected property from the instance.

**Comment by dschnare** [comment]
This seems to keep getting punted. Now that TS 3.4.5 is out I expect this to be punted to 3.5.0?

Granted this is not a massive pain right now, but it would be a really great feature to have supported by TS out of the box.

**Comment by ulrichb** [comment]
* Is it planned that the `@private`/ `@protected` JSDoc only affects the IDE completion, or also the compilation (like the `private`/`protected` _modifier_)?
* Is it planned to respect the current scope for the invocation of the completion (like the `private`/`protected` _modifier_)?

**Comment by sandersn** [comment]
So, no completions, but also no errors when you use it? It sounds like you want `allowJs` without `checkJs`, which is the default for JS files in VS Code.

**Comment by sandersn** [comment]
Here's some documentation for future me to explain why this is surprisingly hard to do well.

There are four solutions I've come up with:

1. The obvious way: All places that handle private and protected ModifierFlags now also need to check for `@private` or `@protected` flags. You have to write code to handle errors, declaration emit and completions separately.
2. The right way: Make getModifierFlags check for JSDoc as well. Unfortunately, getModifierFlags caches, and is first called during parsing when node flags and parents haven't been set. Retrieval of JSDoc relies on both.
3. The fragile right way: Remove all calls to getModifierFlags in the parser so that it *can* retrieve JSDoc. Unfortunately, all calls are indirect, so it's quite difficult to make sure getModifierFlags calls don't sneak back in. It really needs to assert that the compilation phase is post-parsing, or that parent pointers are set, or something.
4. Change node construction so that flags and parent pointers are set on construction. I'm not sure why they're set at the end of their respective parsing functions right now, but changing this naively Broke Every Test, so I suspect this design has an important architectural reason.

(2) doesn't work. (3) might be worth trying if I can find an appropriate assert to prevent mistakes. (1) is a good fallback. (4) is probably not worth it (and may be practically impossible).

**Comment by panoply** [comment]
Additionally it would great if JavaScript proposal class properties (which is at stage 3) could handled correctly as well, eg:

```js
class  Something {
   #private =  'foo'
}
```

**Comment by ekr3peeK** [comment]
Was this feature implemented already, or will it be in the near future?

**Comment by sandersn** [comment]
Looks like https://github.com/microsoft/TypeScript/commit/3c5ecc2a60068139a7cb835b2ade22d6e5a53e39 is in 3.8 and above.

**Comment by ekr3peeK** [comment]
Hmm.. does that mean that if my VsCode uses TypeScript 3.9.4, I should have access to this feature? Cause I don't:)

**Comment by panoply** [comment]
Install JavaScript and TypeScript Nightly:

https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next

**Comment by leosdad** [comment]
> Install JavaScript and TypeScript Nightly:
> 
> https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next

I've just done it, but e.g. `@private` does nothing, at least for JS files. My TypeScript version is 4.0.0-dev.20200708, i.e. yesterday. Any clues?

**Comment by panoply** [comment]
Double check your `jsconfig.json` or `tsconfig.json` and make sure to `"allowJs": true`

**Comment by ekr3peeK** [comment]
For me, this works ok with `TypeScript 4.0.0-dev.20200708`, but it wasn't working with `3.9.4`

**Comment by leosdad** [comment]
> Double check your `jsconfig.json` or `tsconfig.json` and make sure to `"allowJs": true`

Thanks. Did that in my `tsconfig.json`, updated to `dev.20200709`, restarted VS Code twice, but nothing changes. Methods marked as `@private` still appear nonetheless. Any other conditions I should check?
