### ISSUE TITLE
Type of condition expression of a while loop inferred as nullable in the loop body

### ISSUE THREAD

**Issue by dmikis** [Microsoft/TypeScript#14019]
**TypeScript Version:**  2.1.6

**Code**

```ts
interface Node {
    left: Node | null;
    right: Node | null;
}

function findLeaf(root: Node): Node {
    let leaf = root;
    while (leaf.left || leaf.right) {
        leaf = leaf.left || leaf.right; // error here
    }
    return leaf;
}
```

**Expected behavior:**

Code compiles OK with `strictNullChecks` on. Type of `leaf.left || leaf.right` in the loop body is `Node`.

**Actual behavior:**

Compilation error: `Type 'Node | null' is not assignable to type 'Node'. Type 'null' is not assignable to type 'Node'` on commented line.

**Comment by ahejlsberg** [comment]
You're hitting the limit of what the control flow analyzer understands. It tracks the control flow type of individual variables and properties, but not full expressions. In your example, not enough is known about the *invidivual* states of `left.left` and `leaf.right` to remove `null` from the type within the guarded block. However, it works if you introduce a temporary variable because the individual state of *that* variable is then known not to be `null`:

```ts
function findLeaf(root: Node): Node {
    let leaf = root;
    let next;
    while (next = leaf.left || leaf.right) {
        leaf = next;
    }
    return leaf;
}
```

This might even be slightly more efficient because you're not computing the same value twice.

**Comment by dmikis** [comment]
Thanks for the answer. I've used additional variable in the end.
