### ISSUE TITLE
After parsing identifiers that start with two underscore another underscore is prepended

### ISSUE THREAD

**Issue by soda0289** [Microsoft/TypeScript#14013]
**TypeScript Version:**  2.1.5

**Code**

```ts
console.log(__dirname);
```

**Expected behavior:**
When the above typescript is parsed into an AST I would expect the Identifier of the function argument `__dirname` to start with two underscores.

**Actual behavior:**

AST Example here:
https://astexplorer.net/#/gist/7b4386c740b3ba88a996a6f644a215c8/857121c5ac1b3cba6edb0ee8c499cb66e9919772

Identifiers prefixed with one underscore are parsed correctly, so are identifiers prefixed with three underscores.

These bugs are probably related:
https://github.com/Microsoft/TypeScript/issues/11902
https://github.com/Microsoft/TypeScript/issues/3268

**Comment by mhegazy** [comment]
The internal symbol tables were represented as regular objects (though we mostlly use ES6 maps now, we still support systems with no native Map implementation).  The compiler adds an extra underscore, to avoid the `__proto__` being considered as a user-defined entry. The expectation is that the user will use [`unescapeIdentifier`](https://github.com/Microsoft/TypeScript/blob/d24b6891d870dbaa6bbc358ab787da935f471186/src/compiler/utilities.ts#L402-L404) function when getting the name of the identifier. APIs for dealing with symbols/node already do this conversion.

**Comment by soda0289** [comment]
@mhegazy Thanks for the information. I will use that call when retrieving the identifier name.

**Comment by ajafff** [comment]
@mhegazy How are developers supposed to use `unescapeIdentifier`? There seems to be no declaration for this funcion in both versions 2.1.6 and 2.2.0.

**Comment by soda0289** [comment]
I also wish this was documented somewhere.

**Comment by mhegazy** [comment]
> @mhegazy How are developers supposed to use unescapeIdentifier? There seems to be no declaration for this funcion in both versions 2.1.6 and 2.2.0.

The assumption is that users will not need to do that. Can you elaborate on what you are trying to do?

We can expose the helper function on the `ts` namespace like other helpers.

**Comment by soda0289** [comment]
@mhegazy I'd like the function to be exposed. I use the typescript-eslint-parser and it marks variables that start with two underscores as undefined since they are not matched to globals correctly.

**Comment by mhegazy** [comment]
sure.. feel free to send a PR to remove the `/** @internal */` comment from its declaration.

**Comment by JamesHenry** [comment]
Thanks for following up on this @soda0289!

And thanks for your support as always @mhegazy 😄  was great to have the chance to chat with you the other week.

Just to be 100% clear on what @soda0289 is saying - the `typescript-eslint-parser` will be the consumer of this API, because we need to make sure that all identifiers in the final ESTree AST that it outputs match up with the original source.

The behaviour he describes around actually marking variables as undefined is separate (performed within relevant ESLint rules, core or otherwise), but naturally it is all based off the ESTree AST as the source of truth, so the underlying point is valid.

I will submit a PR to make `unescapeIdentifier` public shortly!

**Comment by JamesHenry** [comment]
Here is the PR https://github.com/Microsoft/TypeScript/pull/14076. I used https://github.com/Microsoft/TypeScript/commit/a72abc8ebc5c4c76122126b2212449fafa1277db as an example

**Comment by soda0289** [comment]
Nice! Thanks @JamesHenry
