### ISSUE TITLE
Rename of import should be a local rename

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#14039]
**TypeScript Version:**  nightly (2.2.0-dev.20170213)

**Code**

```ts
import { readFileSync } from "fs";
readFileSync("a.txt");
```

Rename `readFileSync` to `read`.

**Expected behavior:**

```ts
import { readFileSync as read } from "fs";
read("a.txt");
```

**Actual behavior:**

```ts
import { read } from "fs";
read("a.txt");
```

And `@types/node/index.d.ts` is modified too!

**Comment by krryan** [comment]
The current behavior is exactly what I expect and want.

To rename all instances of something in a given file, `Ctrl`+`D` is really useful.

**Comment by andy-ms** [comment]
What editor are you using? What does `Ctrl+D` do?

**Comment by normalser** [comment]
I think it would be better to leave the current way as it is, and use this trick to do the alias rename only

1. Initial
`import { readFileSync } from "fs"`

2. Use alias
`import { readFileSync as readFileSync } from "fs"`

3. Rename alias (right `readFileSync` to `read`)

Unfortunately there is related bug: https://github.com/Microsoft/TypeScript/issues/10894

**Comment by krryan** [comment]
@andy-ms Ah, sorry; I was actually thinking of this as an editor feature/tool, rather than a language one (kind of surprises me that the language itself controls this). I use VS Code. `Ctrl`+`D` selects other strings of text matching the one you have highlighted. This is multi-line selecting, so you can edit all of them at once. Exceedingly useful feature.

**Comment by Kovensky** [comment]
I think the behavior should depend on the context, but I am not sure it is possible.

Say, given

```ts
import { readFileSync } from "fs";
readFileSync("a.txt");
```

If the cursor is in the `readFileSync` _call_, I'd expect renaming it to create an alias; while if I either go to the definition, or rename it from the import specifier itself, to rename the symbol definition.

A similar issue exists with object shorthand notation (renaming a symbol that's used in shorthand also renames its object key, instead of separating the key/value).

**Comment by mhegazy** [comment]
Related to #19173 and #15787

**Comment by pelotom** [comment]
@krryan

> Ah, sorry; I was actually thinking of this as an editor feature/tool, rather than a language one (kind of surprises me that the language itself controls this).

It makes a lot of sense for the language to control this; correct refactorings require deep knowledge of the semantics of the language being edited.

> I use VS Code. Ctrl+D selects other strings of text matching the one you have highlighted. This is multi-line selecting, so you can edit all of them at once. Exceedingly useful feature.

It is a useful approximation when you don't have better tools for the job, i.e. semantically-aware refactorings.

I think this change is needed, _at least_ in the case where a refactor would end up editing a file under `node_modules`; that's _never_ what you meant to do.
