### ISSUE TITLE
ts.VariableDeclaration#parent has wrong type

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#14079]
**TypeScript Version:**  2.1.6 / master

The definition of the `parent` property of `ts.VariableDeclaration` is missing `ts.CatchClause`.
https://github.com/Microsoft/TypeScript/blob/master/src/compiler/types.ts#L652

Before I send a PR to fix this, I wanted to get some feedback for the following questions:
* Why is this the only interface that has a specific type for `parent`?
* Should the other `Node` interfaces also have specific types for their parent property where possible?
* Is there a need for the parent property to remain optional? AFAIK `SourceFile` is the only Node without a `parent`, so all other Nodes don't need `undefined` in the union type.

**Expected behavior:**
```ts
export interface VariableDeclaration extends Declaration {
    kind: SyntaxKind.VariableDeclaration;
    parent?: VariableDeclarationList | CatchClause;
    name: BindingName;
    type?: TypeNode;
    initializer?: Expression;
}
```

**Actual behavior:**
```ts
export interface VariableDeclaration extends Declaration {
    kind: SyntaxKind.VariableDeclaration;
    parent?: VariableDeclarationList;
    name: BindingName;
    type?: TypeNode;
    initializer?: Expression;
}
```

**Comment by mhegazy** [comment]
PRs welcomed.

**Comment by DanielRosenwasser** [comment]
> Why is this the only interface that has a specific type for `parent`?

I suspect it was something done at the time to make checking the parent slightly more ergonomic (because being able to perform reduce down from a union type makes things a little easier than explicitly casting)

> Should the other `Node` interfaces also have specific types for their parent property where possible?

I think this would be ideal; however, I'd prefer a change like that be separated (and potentially not even done because these large-wave changes tend to be difficult to review).

> Is there a need for the parent property to remain optional? AFAIK `SourceFile` is the only Node without a `parent`, so all other Nodes don't need `undefined` in the union type.

It actually depends on the point at which you got a `Node`. Before bind-time (or depending on the options you pass into `createSourceFile`), you won't have parent pointers set up for you.
