### ISSUE TITLE
parameters: presume generics over `any`

### ISSUE THREAD

**Issue by tycho01** [Microsoft/TypeScript#14078]
**TypeScript Version:**  any

**Code**

```ts
let identity = (x) => x; // degenerates to `(x: any) => any` instead of <T>(x: T) => T
let wrong: number = identity('foo'); // type-checks, while TS should have enough info to infer it's wrong
```

**Expected behavior:**
TS should be able to save parameter types (where unspecified) into generics so as to improve inference.

**Actual behavior:**
Things type-check while TS should have enough info to conclude they shouldn't.

Perhaps this could make for a compiler flag?

**Comment by masaeedu** [comment]
This is similar to what F# does (where it is known as [automatic generalization](https://docs.microsoft.com/en-us/dotnet/articles/fsharp/language-reference/generics/automatic-generalization)).

**Comment by RyanCavanaugh** [comment]
Assuming this isn't just "Recognize the identity function", this needs a description of how it might plausibly work

**Comment by masaeedu** [comment]
@RyanCavanaugh The goal is to ensure that the types of function arguments (which will be available at the call site) can participate in inference of the return type. Here's a rough gist of the idea. 

Contextual type inference for functions needs to change so that the type inferred for `result`:

```ts
function f(a, b, c) {
    if (10 > 11) {
        return a;
    }
    if (192 - 7 < 11) {
        return b;
    }
    return c;
}

const { s, n, d } = { s: "Hello", n: 10, d: new Date() };
const result = f(s, n, d); // any
```

Is identical to what is inferred in the following snippet:

```ts
function f<T1, T2, T3>(a: T1, b: T2, c: T3) {
    if (10 > 11) {
        return a;
    }
    if (192 - 7 < 11) {
        return b;
    }
    return c;
}

const { s, n, d } = { s: "Hello", n: 10, d: new Date() };
const result = f(s, n, d); // string | number | Date
```

As a starting point, let's say we simply desugar all function declarations so that every parameter without an explicit type annotation corresponds to a generic type parameter in the final type signature of the function.

```ts
// The following:
function foo(a: number, b: string, c) { }

// Is now equivalent from a type system perspective to:
function foo<T1>(a: number, b: string, c: T3) { }
```

When called without type arguments, this behaves the same as `any` inference for `c`. When called with an argument of a known type for `c` (or an explicit type argument), you will get a more accurate return type instead of `any`.

The tricky part is figuring out how this interacts with explicitly generic functions. Because we don't have HKTs, and type signatures can't be partially applied, it is hard to figure out what type signature should be constructed for this function:

```ts
function prop<V>(object, key): V { /* ... */ }
```

Do the inferred generic arguments simply get appended to the function's type signature? Because you can't partially supply generic type arguments, this results in incovenience at the call site:

```ts
// If the type system treats the above as:
function prop<V, T1, T2>(object: T1, key: T2): V { /* ... */ }
// Calling the function becomes annoying:
const val1 = foo({ h: "ello" }, "h"); // Inferred as any
const val2 = foo<string>({ h: "ello" }, "h"); // Can't do this, passing type args is all-or-nothing
const val3 = foo<string, {}, string>({ h: "ello" }, "h"); // You have to pass type arguments you never declared
```

Ideally we'd solve this by solving the problem of allowing parametrized type signatures to be applied partially (I know there's an issue for that somewhere). An uglier approach might be to hide the implicit type parameters from the user and use them internally in the type checker during inference, although this would result in surprising return types. Can't really think of any good ideas on this front.

I'm probably missing a bajillion edge cases and interactions with other language features, but that's the rough idea.

Some other thoughts:
 - An important consideration here is that this hypothetical `implicitGenerics` flag would not play well with `noImplicitAny`, since the type parameters being generated are unconstrained
 - This is a very general way to represent function signatures, and in fact even parameters with explicit annotations can simply be represented as constraints on a type parameter (e.g. `function foo(s: string) { ... }` is equivalent to `function foo<T1 extends string>(s: T1) { ... }`
 - Something like this would allow for a great deal of extensibility in other areas of inference in the future, since you can express things like #15114 as constraints on the generated type parameters

**Comment by tycho01** [comment]
Thanks for helping elaborate, @masaeedu. :)

To add to your post a bit:

> we don't have HKTs, and type signatures can't be partially applied

> Allow parametrized type signatures to be applied partially (I know there's an issue for that somewhere)

Partial application of generics sounds like #14400, while HKTs seemed the topic of #1213.

**Comment by tycho01** [comment]
Closing in favor of #17428.
