### ISSUE TITLE
Allow inheritance from intersections

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#14075]
Based on #14017, when exporting a class that extends from a mixin, the emitted type contains an intersection. Inheriting from an intersection is not allowed, even though it should be.

Note that inheriting from a type alias of an intersection already works:

```ts
// A *self-contained* demonstration of the problem follows...
class A { a = 1 } 
class B { b = 2 }
type Both = A & B
class C extends A & B { } // error
class D extends Both { } // ok
```

**Expected behavior:**
No error for C *or* D.

**Actual behavior:**
Error for C.

**Comment by ahejlsberg** [comment]
You're confusing types and expressions in your example. The `extends` clause of a class requires an *expression*, not a type, so `C` and `D` are both errors. The right way to write the example is

```ts
class A { a = 1 } 
class B { b = 2 }
declare const Both: new () => A & B;
class D extends Both { }
```

This of course omits the details of how `A` and `B` are actually intersected.

The declaration file emitter currently depends on the fact that a class declares both a type and a value. It actually emits the `extends` clause as a *type*, even though a value is required in that position. We've gotten away with it so far because classes typically inherit from entities that share the same name for a type and a value, but that's no longer the case with mixins.

**Comment by mhegazy** [comment]
Allowing a type in an ambient declaration should be fine though.

**Comment by ahejlsberg** [comment]
Not sure how that would work. First, it would be ambiguous how to parse it. Second, we require an expression of a *constructor type*, not an *instance type*, so you couldn't just write `A & B` as those are instance types.

**Comment by mhegazy** [comment]
Either we allow inheriting from types in ambient declarations, or we need to write a `declare const` before a class with a type that has no name.
