### ISSUE TITLE
Problem with packages which have no default export

### ISSUE THREAD

**Issue by lexon0011** [Microsoft/TypeScript#14083]
I have problems with importing some libraries to my typescript app. For example: `import  Immutable  from "immutable";` Then I write following statements: `Immutable.fromJS(...)`, ...

-> compiling works, but I get at runtime the following error: `TypeError: Cannot read property 'fromJS' of undefined`

The problem is, that typescript create the following js code: `immutable_1.default.fromJS(...)` But the immutable package has no default export. So this should be `immutable_1.fromJS(...)`

I could resolve this problem with the following import statement: `import  * as Immutable  from "immutable";` But I could not use namespaces, because this make problemes with angular AOT compilation.

Is there a way to resolve this problem?

Here is my tsconfig.json
[tsconfig.zip](https://github.com/Microsoft/TypeScript/files/776779/tsconfig.zip)

**Comment by blakeembrey** [comment]
@lexon0011 It doesn't error in the compiler because you enabled `allowSyntheticDefaultImports`, which tells the TypeScript compiler you're doing something yourself to map regular `module.exports =` to the `.default` imports. If you remove that flag, you'll see the compiler error. As for how you should be importing these modules without that flag, you should do either `import x = require('x')` or `import * as x from 'x'`.
