### ISSUE TITLE
keyof Enum

### ISSUE THREAD

**Issue by sebdoucet** [Microsoft/TypeScript#14106]
Hi,

I ve seen a post over this particular suggestion, but I did not understant why (in typescript, not in js)

why this kind of behavior is not expected on keyof over enum:
``` typescript
enum Kind {
   none,
   bob
}

interface SomeJsonData {
    kind: keyof Kind;
    insteadOfKind: "none" | "bob";
}
```

Just saying that because it was my first reflex trying keyof over enums out of Partial or Readonly's.
Enum are not part of ecmascript (as I know) so keyof applyed to typescript should have a typescript specific behavior.

I also did not expect keyof returns number values, but if it does, still make more sense than current behavior.

Cheers.

**Comment by DanielRosenwasser** [comment]
Just to clarify, I think that the question is "Why do I get a bunch of string literals named after the methods on numbers instead of `"none" | "bob"`. Phrasing the question that way might clarify things a little.

An enum declaration actually declares two types:

* The type of enum members (e.g. `Kind.none`, `Kind.bob`)
* The type of the enum container itself (i.e. `Kind`)

`Kind.none` and `Kind.bob` each have a base type of `Kind`, which is really just subtypes of the `number` type, which has members of the `Number` type.

`Kind` on the other hand, is *more or less* an object with two members on it at runtime. Its type doesn't have a name, but you can still reference it by using the `typeof` operator (i.e. `typeof Kind`).

So if you're looking for `"none" | "bob"`, you unfortunately want `keyof typeof Kind`.

**Comment by sebdoucet** [comment]
Very interesting that you use this:

> The type of enum members 

I mean, keyof is not for enumerating numbers ?

Actually, in my opinion, enums are just a hack over javacript.
Result with that is typeof Enum give you "object".
Result with that is you have access to it enum[string] and enum[number].

> The type of the enum container itself

Actually... that something that is very weird, because... not really. typeof or instanceof like that does not work....

Following the behavior you say with keyof, we may have this :
```
typeof Kind  === 'number'
typeof Kind.none === 'number'
```
but not!

That is legit typescript and returns a number :
```
Kind["none"];
Kind["bob"];
```
So, the definition of keyof is not clear... because "none" and "bob" are keys of the enum that make me enable access to its numbers values.

You actually try to explain me a non sense make sense because of non sense... yep, this sentence does not mean anything to me, like your explaination.

**Comment by sebdoucet** [comment]
This post tell me:
Keyof is a way to enumerate javascript object members but even if enums are object instances, you will not be able to enumerate them that way. Instead of that, has you expected, it will returns the prototype of number, because its making more sense.

**Comment by styfle** [comment]
@DanielRosenwasser Your answer was very helpful!

However, I get an error using a `const enum` declaration with your solution.

Is there a workaround for this problem or do I need to submit a feature request?
