### ISSUE TITLE
as cannot be moved to a new line

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#14130]
```
type foo = string;
const anything: any = undefined;
anything as foo; // <-- works, duh
anything as
   foo; // <-- still works
anything
   as foo; // <-- breaks
```

**Comment by DanielRosenwasser** [comment]
This is an intentional part of our grammar (see https://github.com/Microsoft/TypeScript/pull/3201#issuecomment-109068104) because of the ambiguity caused by parenthesized types.

For example:

```ts
x
as (Foo)
```

This example is valid JS code consisting of

* a statement expression with an identifier: `x`
* followed by a call expression: `as(Foo)`
