### ISSUE TITLE
String enum too verbose to use

### ISSUE THREAD

**Issue by Dominator008** [Microsoft/TypeScript#14142]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
type Axes = "x" | "y" | "z";
const Axes = {
  X: "x", // Not X: "x" as Axes
  Y: "y",
  Z: "z"
}

function test(axes: Axes) {}

test(Axes.X); // Argument of type 'string' is not assignable to parameter of type 'Axes'.
```

**Expected behavior:**
No error
**Actual behavior:**
Assignability error

Since `Axes` is declared as a `const`, I expect the type inference to resolve `Axes.X` to `"x"` without the need for "as Axes".

**Comment by jesseschalken** [comment]
`Axes` is `const`, so someone can't do `Axes = ..`, but the properties of the object referred to be `Axes` are still mutable, so someone could do `Axes.X = "foo"`, which is allowed since TypeScript inferred the `X` property to be of type `string`, not `"x"`.

There's probably a few ways to do what you want. Here's one:

```ts
type Axes = "x" | "y" | "z";
namespace Axes {
  export const
    X = "x",
    Y = "y",
    Z = "z"
}

function test(axes: Axes) {}

test(Axes.X);
```

You could also use an `enum`, but the values have to be numbers then.

**Comment by Dominator008** [comment]
Thanks. Hmm. I think I used `"x" as Axes` when I tried to reassign a random string to `Axes.X`, so it is indeed working as intended.

Using `namespace` is not always ideal as it compiles to an IIFE and bloats code size. I came up with the following:
```ts
type Axes = {
  readonly X: "x"
}
const Axes: Axes = {
  X: "x"
}

function test(axes: Axes[keyof Axes]) {}

test(Axes.X);
```
Still verbose but you get the real const check.

**Comment by mhegazy** [comment]
String enums is tracked by https://github.com/Microsoft/TypeScript/issues/1206
