### ISSUE TITLE
[Suggestion] Discriminated (tagged) interface types

### ISSUE THREAD

**Issue by BalassaMarton** [Microsoft/TypeScript#14166]
Discriminated union types are handy when the possible subtypes are known. However, in larger projects, interfaces are more often used, because the subtypes (derived interface types) are unknown at compile time. It would be a useful compiler feature to allow interface types to be tagged and narrowed just like union types:

```ts
export interface Message {
    type: string;
}

export const MSG_HELLO = "hello";
export interface HelloMessage extends Message {
    type: MSG_HELLO;
    sender: string;
}

export const MSG_LOGIN = "login";
export interface LoginMessage {
    type: MSG_LOGIN;
    userName: string;
    password: string;
}
```
```ts
function processMessage(message: Message) {
    switch (message.type) {
        case MSG_HELLO: {
            // message is HelloMessage
            console.log(`${message.sender} says hello`)
            break;
        }
        case MSG_LOGIN: {
            // message is LoginMessage
            app.login(message.userName, message.password);
            break;
        }
        default: {
            console.log(`Unknown message type: ${message.type}`)
        }
    }
}
```

**Comment by DanielRosenwasser** [comment]
We have discussed this a bit, but I think it's just a bit too complex.

The problem is that interfaces on their own are open to extension. That means anyone could eventually add another interface that uses the same tag for a different purpose.

This also gets tricky with structural type equivalence - is something with the same shape as `Message` still narrowed down by the same checks? We'd also have to account for every type in your program and construct the full hierarchy so that you could narrow appropriately. Even then, this behavior isn't desirable.

The general pattern I've taken advantage of is

```ts
interface BaseMessage {
    // Common properties
}

interface MessageA extends MessageBase {
    kind: "A";
}

interface MessageB extends MessageBase {
    kind: "B";
}

type Message = MessageA | MessageB;
```

**Comment by sampsyo** [comment]
I know this issue is closed, and I agree it's too complex, but I thought I'd add my thoughts here after searching around for a reasonable solution for posterity. I'm using the pattern @DanielRosenwasser suggested above, and I was hunting for a way to avoid the need to type the list of types twice—once in the sub-interface declarations, and once in the union at the bottom. In other words, I want to get the type `MessageA | MessageB` without writing it out explicitly.

Clearly, the type `BaseMessage` itself is not equivalent to this type. There are three reasons:

1. Interface typing is structural, so lots of types (infinitely many!) are subtypes of `BaseMessage`.
2. Even if subtyping were nominal, values of the "unextended" type belong to this type. That is, objects with *just* the common properties have the type `BaseMessage`. The union type we're interested in is all the *children* of `BaseMessage` but not `BaseMessage` itself.
3. Even if subtyping were nominal *and* we could exclude the base type, TypeScript is an "open world" system, so anyone can come along and create a new interface that `extends BaseMessage`.

So I think you'd need to do three things to get the desired type:

1. Use nominal subtyping. That means either switching to classes instead of interfaces or hoping for some magical solution to #202.
2. Get the (strict) subtypes of a given type. If you're using classes, you could accomplish this by making the base class `abstract`, meaning that all values could only be of classes that `extend` the base class. Alternatively, you can imagine a `childrenof` type operator or something.
3. "Seal" the base type so that other modules cannot extend it. Imagine a new `closed` keyword, the opposite of [Swift's `open`](https://stackoverflow.com/questions/38979371/cannot-inherit-from-non-open-class-swift), that prohibits subclassing of a given class *outside of the module where it is declared*.

With those three pieces in place, you could obtain a type that is precisely equivalent to the union of all the types that are locally declared as `extends BaseMessage`.

Anyway, this is indeed probably too complex to be worth it, but I thought it was interesting to enumerate the independent type system features that would be needed to accomplish it.
