### ISSUE TITLE
Error when applying class mixins in 2.3-dev

### ISSUE THREAD

**Issue by justinfagnani** [Microsoft/TypeScript#14209]
**TypeScript Version:**  2.3.0-dev.20170221

**Code**

```ts
export interface Foo { foo(): string; }

export type Constructor<T extends object> = new (...args: any[]) => T;

export const Foo =
    <T extends Constructor<{}>>(superclass: T): Constructor<Foo>& T =>
        class extends superclass implements Foo {
  foo() {
    return 'baz';
  }
}

export class Bar extends Foo(Object) {
}
```

**Expected behavior:**
no errors

**Actual behavior:**
```
[ts] 'extends' clause of exported class 'Bar' refers to a type whose name cannot be referenced.
```

**Comment by DanielRosenwasser** [comment]
To note, this shows up because you have `--declaration` set. Unfortunately you'll need to write out the exact type to get rid of the error.

I think there are two issues:

1. This error doesn't signal that `--declaration` is part of the cause.
2. This makes using mixin classes cumbersome.

(2) is something I've definitely noticed, but I don't know how much of a problem it will tend to be,.

**Comment by mhegazy** [comment]
Here is the issue tracking @DanielRosenwasser's point (2)
