### ISSUE TITLE
[Suggestion] Sugar for using declare global [interface|var|...] on actual declarations please

### ISSUE THREAD

**Issue by SMotaal** [microsoft/TypeScript#14227]
This is more of a convenience feature that may or may not be very simple to do on your end. But as I explore working with the global JSX namespace to use it with native custom elements, I keep running into scenarios where there is repeated `declare global {}` blocks scattered around different modules.

While I have not encountered the use of `declare global` in other use cases over the past few years, I wonder if others may have repeated use for it.

Instead of using the block format to declare what I believe is mostly non-emitted code that is only used for the type system, I would like to propose using something like `declare global interface ...` which would be synonymous to `declare global { interface .... }`.

**TypeScript Version:**  2.2.0

**Code**

*Here is an example from my current experiment before sugaring:*

```tsx
class E extends Element {
    public propA: string;
}

declare global {
    interface CustomElementAttributes {
        'my-e': Attributes<E>,
    }
}

const myE = <my-e prop-a='abc'></my-e>
```

*Here is the proposed syntax change for the global interface declaration:*

```tsx
declare global interface CustomElementAttributes {
    'my-e': Attributes<E>,
}
```

**Expected behavior:**

I am using the global CustomElementAttributes interface to define the attributes for custom tags and this interface is then consumed in the global JSX's IntrinsicElements.

I was inclined to try simplifying the code as shown in the proposed syntax and of course this is not currently valid syntax, but it might be a welcome addition.

**Checklist:**

**Syntactic**: I assume there are no syntactic concerns.

**Semantic**: I assume anything that is not valid inside a declare global block remains invalid when using the short hand form. Also, since it is a declaration, it cannot be in the form of an assignment statement or RHS.

**Emit**: While this does not affect js emit, it does factor in declarations, which I would argue does not require any change expect in the tokenization process. When a `declare global` is not followed by a `{`, then it should be followed by a declaration that starts with `interface|var|type|...` and at the end of this block, that declaration should be wrapped into a block to produce `declare global { [declaration] }`.

**Compatibility:** I don't see any potential conflicts. I would venture that error checking might introduce some hard-to-predict challenges (especially for someone on the outside like myself) and the same with tooling that is hard-bound to the current syntax.

**Other:** I think performance is not an issue, as long as you guys figure out how this impacts error checking. I do imagine this will be a breaking change from a tooling standpoint for tools that do AST-based operations and error checking (linting... etc).

**Comment by mhegazy** [comment]
Why not declare all your augmentations in a single .d.ts file, call it `globals.d.ts`?

**Comment by daflair** [comment]
True... one potential way could be `globals.d.ts` and whenever we define a custom element then this file must be edited. Of course the advantage would be that there is one central location where tags are associated with custom element classes, and essentially that is good since elements must use unique tags.

So this suggestion is really not a solution to my actual problem, but something that felt more natural form a coding standpoint and I was inclined to think that other people might have a similar need, which is to be make a single inline global declaration that does feels more natural like when using private, public... etc.

Surely `declare global interface ...` as a single global declaration feels more natural than having a `declare global {...}` block for a single member.

Here is the longer version of the actual situation as an example why I needed to use a single global declaration:

I'm trying to get TypeScript's JSX typing mechanism to work nicely with authoring native Web Components, or at least non-React components. My challenge was to be able to use TSX to define an HTMLTemplate that can include custom elements using tags. So for a custom element to an encapsulated web component module that handles it's own CusomElementRegistry#define, the basic assumption should be that the tag name is the only reference that can be imported into scope by the consuming HTMLTemplate.

This means that we need to augment the IntrinsicElements interface of the global JSX namespace as a side effect of importing the component, and the most preferable mechanism in my opinion will be to automatically augment the IntrinsicElements interface whenever an element is being defined in the CusomElementRegistry.

At this point, it seems that every component will only need to use one global declaration statement with no exports, contamination or side effects (to be v1 compliant) which currently looks like this:

```ts
declare type MyCustomElementAttributes = Partial<{[attributes: string]: any}>;

declare global {
    interface CustomElementAttributes {
        'my-custom-element': MyCustomElementAttributes
    }
}
```

Then I wondered if instead they could have this:
```ts
declare type MyCustomElementAttributes = Partial<{[attributes: string]: any}>;

declare global interface CustomElementAttributes { 
    'my-custom-element': MyCustomElementAttributes;
}
```

**Comment by mhegazy** [comment]
I am not sure i understand the original reason why this interface is defined in the global scope in the first place. can you elaborate?

**Comment by daflair** [comment]
Oh, that's a requirement for TypeScript's JSX type system, when I looked it up on various threads it was always global... but you make a good point, because the handbook does not specify global anywhere! Thanks a lot for pointing that out, I think that helps a lot!

> [Intrinsic elements are looked up on the special interface JSX.IntrinsicElements. By default, if this interface is not specified, then anything goes and intrinsic elements will not be type checked. However, if interface is present, then the name of the intrinsic element is looked up as a property on the JSX.IntrinsicElements interface.](http://www.typescriptlang.org/docs/handbook/jsx.html)

So, this is different from the title of the issue at this point, I now have some more research work ahead of me...

But I will, have to ask, generally speaking, don't u feel that a statement like `declare global type ...` is much more intuitive then the block having only 1 statement, just like when declaring a member public or private?

**Comment by mhegazy** [comment]
Global side-effects of modules is not a great practice in general. TS did not have support for it, intentionally, for a long time. Now that we have `declare global` (meant to match `declare module` btw), we can not take that back and break existing users; I do not think we should add yet another syntactic form to express the same semantic meaning (one is too many already if you ask me).

**Comment by RyanCavanaugh** [comment]
These kinds of lone declarations aren't really common enough to warrant an additional syntax for writing them.
