### ISSUE TITLE
Extending a namespace in `.d.ts` file vs in `.ts` file

### ISSUE THREAD

**Issue by realyze** [Microsoft/TypeScript#14325]
Typescript@2.1.6

Using `"@types/react": "^0.14.41",` and `"@types/react-dom": "^0.14.18"` (installed via npm).

When I write
```
declare module 'react' {
    interface HTMLProps<T> {
        onTouchTap?: React.EventHandler<React.TouchEvent<T>>;
    }
}
```
in a `customTypings/react-tap-touch.d.ts` file, it seems to cause tsc to report a lot of errors (error `TS2604: JSX element type 'Router' does not have any construct or call signatures` and similar). Looks like `react` namespace is overriden rather than extended.

Using the same snippet in a `startup.ts` file works fine (i.e., extends `react` and doesn't override it).

What's the difference between extending a namespace from `.d.ts` vs `.ts` file? Shouldn't `.d.ts` be the right place to do this sort of thing?

The issue is summed up by this comment:
https://github.com/zilverline/react-tap-event-plugin/issues/58#issuecomment-282543479

**Comment by blakeembrey** [comment]
They should be the same. However, they are different depending on if you have `import` or `export` at the top-level. With `import` and `export`, you're writing a module augmentation (because the file is in "module mode"). Without them, you're writing a module declaration (because the file is in "global mode").

**Comment by realyze** [comment]
@blakeembrey Thanks a lot!
