### ISSUE TITLE
Type returned not being checked in a function returning an union type

### ISSUE THREAD

**Issue by vintem** [Microsoft/TypeScript#14392]
**TypeScript Version:**  2.2.1

**Code**

```ts
interface ISomeType { 
    value: string;
}

interface ISomeOtherType { 
    value2?: string;
}

interface IStillSomeOtherType { 
    value3?: string;
}

type TypeOptions = ISomeType | ISomeOtherType | IStillSomeOtherType;

function fn(x: number): TypeOptions {
    if (x % 2 === 0) {
        return {
            value: "even"
        };
    } else if(x % 2 === 1) {
        return "odd";
    }

    return 123;
}
```

**Expected behavior:**
TypeScript should check that the returned value is of the three types defined in the type alias TypeOptions

**Actual behavior:**
Values of a type different from the specified can be returned, such as strings and numbers.

[Link to playground](http://www.typescriptlang.org/play/index.html#src=interface%20ISomeType%20%7B%20%0D%0A%20%20%20%20value%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20ISomeOtherType%20%7B%20%0D%0A%20%20%20%20value2%3F%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20IStillSomeOtherType%20%7B%20%0D%0A%20%20%20%20value3%3F%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Atype%20TypeOptions%20%3D%20ISomeType%20%7C%20ISomeOtherType%20%7C%20IStillSomeOtherType%3B%0D%0A%0D%0Afunction%20fn(x%3A%20number)%3A%20TypeOptions%20%7B%0D%0A%20%20%20%20if%20(x%20%25%202%20%3D%3D%3D%200)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20value%3A%20%22even%22%0D%0A%20%20%20%20%20%20%20%20%7D%3B%0D%0A%20%20%20%20%7D%20else%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20%22odd%22%3B%0D%0A%20%20%20%20%7D%0D%0A%7D)

**Comment by krryan** [comment]
Unfortunately, this isn't a bug: you *are* returning valid values `TypeOptions` here. Because `ISomeOtherType` and `IStillSomeOtherType` have only optional parameters, the empty object `{}` is a valid value for those interfaces. And since any extension of those interfaces is also valid as a value for those interfaces, that means *anything* is a valid value here.

You might consider giving those interface some unique string literal identifier property. On our project, we call this property `kind`. So for example you could have:

```ts
interface ISomeType { 
    kind: 'some-type';
    value: string;
}

interface ISomeOtherType { 
    kind: 'some-other-type';
    value2?: string;
}

interface IStillSomeOtherType { 
    kind: 'still-some-other-type';
    value3?: string;
}

type TypeOptions = ISomeType | ISomeOtherType | IStillSomeOtherType;

function fn(x: number): TypeOptions {
    if (x % 2 === 0) {
        return {
            kind: 'some-type',
            value: "even"
        };
    } else if(x % 2 === 1) {
        return "odd";
    }

    return 123;
}
```

Now `"odd"` and `123` are not valid return values for the function, since they lack a valid `kind` property.

**Comment by vintem** [comment]
I understand, I thought it was possible to check that at least an empty object was being returned. But I'll use your recommendation with the kind pattern. 
Thanks
