### ISSUE TITLE
Partial loss of Syntax highlighting when updating to Visual Studio 2017 RC

### ISSUE THREAD

**Issue by JohnWeisz** [Microsoft/TypeScript#14422]
**TypeScript Version:**  2.1.5

**Code**

```ts
import * as React from "react";
export var t = new Date();
```

**Expected behavior:**

Keywords `import`, `as`, `from`, `export`, `var` and `new` should be highlighted (by default, blue).

**Actual behavior:**

Only `var` is highlighted, as shown on this screenshot:

![2017-03-02](https://cloud.githubusercontent.com/assets/13468659/23522605/edb1a84c-ff83-11e6-98d8-ca86996a620d.png)

**Additional notes**

 - TypeScript build succeeds
 - All project types are affected
 - VS 2017 RC was installed next to a VS 2015 installation
 - Both VS 2015 and 2017 are Community edition
 - The new installation of VS 2017 did _not_ affect the earlier VS 2015 one
 - JSX/TSX syntax highlighting is gone too

**Comment by JohnWeisz** [comment]
Something is clearly wrong:

![wat](https://cloud.githubusercontent.com/assets/13468659/23524259/1a452568-ff8a-11e6-81b4-83c7afc6a9c8.png)

**Comment by mhegazy** [comment]
is this only for a single project? are all files showing the same behavior? if so where is the second screenshot from? what happens if you open a new .ts file in a new session of VS?

**Comment by JohnWeisz** [comment]
Multiple projects, thousands of files, all display the exact same behavior. I restarted VS multiple times (also, as I said, in VS2015 the syntax highlighting works flawlessly), and, among other things, tried:

 - Running VS 2017 RC as admin
 - Disabling/enabling TextMate extension (disabling it completely eliminated all syntax highlighting, except for class names)
 - Installing TS 2.2 (although it had no effect regarding the displayed version in the About window of VS)
 - Running `devenv /setup`

This is how it looks in a larger scope:

![wat](https://cloud.githubusercontent.com/assets/13468659/23525782/e67c6ae2-ff8f-11e6-9607-fdecd05fc935.png)

As you can see, it's "mostly" intact, but it seems as if the keyword recognition was leaking between tokens.

**Comment by JohnWeisz** [comment]
Interestingly enough, the same happens with plain `.js` files (which I believe are now using the Typescript language service for autocompletion as well).

**Comment by JohnWeisz** [comment]
Alright. Visual Studio 2017 RC is recognizing `new`, `import`, `export`, `from`, `as` keywords as _Operator_, and changing the color of operators in the Fonts & Colors settings will once again highlight these, while also highlighting regular operators and brackets around function parameters.

I believe something's not quite right in the TS language service.

**Comment by Tragetaschen** [comment]
I have the very same problem.

I started with VS2015 Professional this morning (TS 2.2) and installed VS2017 Professional RTM (TS 2.1) and the syntax highlighting is broken in exactly the same way as @JohnWeisz describes.

**Comment by Tragetaschen** [comment]
For example, I clone https://github.com/tragetaschen/angular-issue-n14513 and choose from the context menu of the `src` folder to "Open in Visual Studio". I then open `main.ts` and get this:

![image](https://cloud.githubusercontent.com/assets/1947968/23701940/54c13786-03f9-11e7-95bb-ebd8d60a557c.png)

**Comment by Xcalllibur** [comment]
Looks like someone fundamentally broke the Typescript IClassifier!  Below is an example where the **public** keyword changes its colouring depending on on the code:

![before](https://cloud.githubusercontent.com/assets/8317246/23782123/eb2554ac-058c-11e7-87ab-0a5fe6bec3f5.PNG)

Notice how the second **public** keyword is not coloured blue.  If i remove the contents of the first array, then the second **public** keyword becomes correctly coloured:

![after](https://cloud.githubusercontent.com/assets/8317246/23782122/eb2473f2-058c-11e7-92af-fbffa203370f.PNG)

This would also explain why the keywords are being incorrectly classified as **Operators** in the example that @JohnWeisz posted.

**Comment by billti** [comment]
Hmmmm.... trying the snippet from @Xcalllibur and the repro from @Tragetaschen , I don't see any problems. Screen clippings below. I even messed around with the default theme to see if this might have an impact, but all looked good.

That said, there's definitely something up here. This has been reported in #14523 also. Can you take a look at the questions I just posted there and see if anything here might apply to your environments? 

Thanks, and sorry for the inconvenience.

![syntax1](https://cloud.githubusercontent.com/assets/993909/23785774/34f459d0-051e-11e7-95cd-9005ff8f162a.png)

![syntax2](https://cloud.githubusercontent.com/assets/993909/23785777/37d3d374-051e-11e7-846f-440deaf5d241.png)

**Comment by jramsay** [comment]
@Xcalllibur, @JohnWeisz :  Thanks for helping us with this issue! TypeScript & JavaScript now use TextMate language files to inform classification. Some additional things to try that might help isolate the problem here:

1. Can you confirm that other TSLS features are working correctly on your installation?  (formatting, completions, etc).  

2 .There is a known issue with TextMate support in VS where sometimes there are missing colors. To make sure this isn’t the case here can you try running the following from a VS Developer cmd prompt to see if it resolves the issue:
• devenv.exe /updateconfiguration
• devenv.exe /setup


3.What is your VS installation directory?
 Ex: C:\Program Files[ (x86)]\Microsoft Visual Studio 15.0\Common7\IDE


4.Does the tmLanguage folder exist under the TypeScript installation path?
   Ex: C:\Program Files\Microsoft Visual Studio 15.0\Common\IDE\CommonExtensions\Microsoft\TypeScript\tmLanguage


5.Do you have any custom grammar files (.tmLanguage, .tmTheme) located in your user profile?
   Ex: %userprofile%.vs\Extensions


6. Can you verify this isn’t a TM language caching issue:
 - Close VS
 - Go to the TexMateCache location:
 - %localappdata%\Microsoft\VisualStudio[15.0XXXXX]\TextMateCache
 - Delete all the .cache files in this directory
 - Reopen VS and try to repro
 Does this resolve the issue?



7.Do you have the TypeScript TextMate registry key set correctly?
◦Close VS
◦Open regedit
◦Select HKLM
◦File > Load Hive …
◦Open %localappdata%\Microsoft\VisualStudio\15.0_xxx\privateregistry.bin (you can name the hive VS)
◦Now navigate to:
 Computer\HKEY_LOCAL_MACHINE\VS\Software\Microsoft\VisualStudio\15[XXXXX]_Config\TextMate\Repositories


Does the TypeScript reg key exist? The directory should match the tmLanguage folder path from question #2 – is it the same?

Note: you'll need to unload the hive (File > Unload Hive) before you can open VS again.

**Comment by Xcalllibur** [comment]
@billti @jramsay I can confirm that the fix provided by **Peter-Juhasz** in the thread you linked solved my issue, namely:

> Overwrite files in "%userprofile%.vs\Extensions\typescript\syntaxes" with the ones from Visual Studio's "CommonExtensions\Microsoft\TypeScript\tmLanguage".

I then had to close all my files and reopen them to get the syntax highlighting to work (that is after restarting Visual Studio).  Interestingly, before updating these files I tried deleting what was in my %userprofile% typescript folder and the syntax highlighting was still broken.

I think it is relevant to mention that i also had Visual Studio 2015 installed on this machine with the latest Web Essentials extension installed.

@jramsay I ran through your questions (1- 7) before trying this fix and none of them helped unfortunately.  I don't have time to post detailed answers but i can confirm there was nothing out of the ordinary with my registry settings, etc.

**Comment by Tragetaschen** [comment]
@jramsay 

1. Yes, formatting, completions, etc. work correctly
2. No, after running those two commands (the second one needs elevation), the issue still persists
3. C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE
4. Yes, this folder exists (Common*7*, though)
5. (see 6)
6. Yes, there's a whole list. I tried uninstalling @madskristensen Syntax Highlighting Pack extension, but the entire folder remained available (uninstall issue?). When I manually removed its `typescript` folder, syntax highlighting was entirely gone. I then deleted %localappdata%'s TextMateCache folder and syntax highlighting went back to normal.
7. Didn't do that

**Comment by Tragetaschen** [comment]
I just repeated the entire process:
- Install Syntax Highlighting Pack
- Note that syntax highlighting of TypeScript files is broken
- Remove the Syntax Highlighting Pack
  - Uninstall the extension
  - Clear the user's `.vs/Extensions` folder
  - Remove the TextMateCache folder
- Note that syntax highlighting of TypeScript files works

**Comment by madskristensen** [comment]
I just released version 2.7 of the Syntax Highlighting Pack with a fix. The fix was to remove both the JavaScript and the TypeScript Textmate bundles.

**Comment by Tragetaschen** [comment]
I can confirm that. Thanks @madskristensen!

**Comment by nuander** [comment]
I had to remove the syntax highlighting pack 2.7 in order to get code coloring back in my ts files
