### ISSUE TITLE
Weird 'referenced directly or indirectly in its own initializer' error

### ISSUE THREAD

**Issue by vilic** [Microsoft/TypeScript#14428]
**TypeScript Version:**  2.2.1

**Code**

```ts
(async () => {
    function foo(p: string[]): string[] {
        return [];
    }

    function bar(p: string[]): string[] {
        return [];
    }

    let a1: string[] | undefined = [];

    while (true) {
        let a2 = foo(a1!);
        a1 = await bar(a2);
    }
});
```

With `noImplicitAny` and `strictNullChecks` turned on, this gives error:

```text
'a2' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
```

**Comment by ahejlsberg** [comment]
When inferring the type of a variable from its initializer we're performing a full type check of the initializer instead of just doing the minimal work to obtain its type (i.e. we're using `checkExpression` instead of `getTypeOfExpression`). This full type check causes a circularity to surface. We just need to be a little less eager.

**Comment by andy-ms** [comment]
A possibly related case:

```ts
type AB = A | B;
class A { _a: any; }
class B { _b: any; }

declare function create<T>(b: boolean): T;

function f() {
    let ab: AB = new B();
    while (true) {
        const b = create<B>(ab !== undefined);
        ab = b;
    }
}
```

`src/a.ts(10,15): error TS7022: 'b' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.`
