### ISSUE TITLE
Feature request: Bundling code

### ISSUE THREAD

**Issue by alexcorvi** [Microsoft/TypeScript#14552]
I see typescript as a great solution to the mess of modern day front-end web development, where you have to use a module bundler, transpiler, other loaders ... etc.

Webpack is a great tool, but sometimes it's just an overkill and adds it's own runtime overhead.

TypeScript does a great job of compiling modern ES6 all the way down to ES3 thus eliminating the need for Babel and such. However, I still need to use `rollup` or `webpack` to bundle my _compiled_ TypeScript code!

It would be great if there's a feature where my whole TypeScript project gets bundled into a single file without the need for `require.js` or `system.js`, much like what [rollup](http://rollupjs.org/) does.

**Comment by kitsonk** [comment]
This has been discussed many many many times before. (see #8918 for example) and TypeScript already supports a limited set of bundling (see #6261).

Also, it is contrary to the [non-goal of TypeScript](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#non-goals):

> 4) Provide an end-to-end build pipeline. Instead, make the system extensible so that external tools can use the compiler for more complex build workflows.

Module resolution is complex, especially when you have to be able to support circular module references, which for various reasons AMD and ESM both support.  Also, things like WebPack and Rollup deal with other resources too.  Almost any decisions other than the basic bundling already support will likely work for no-one instead of being useful to anyone.

**Comment by RyanCavanaugh** [comment]
As noted, this has been brought up before. There's really no reason for us to re-implement webpack / rollup / whatever bundler comes next.

> Almost any decisions other than the basic bundling already support will likely work for no-one instead of being useful to anyone.

🏆 ❤️  ⭐️
