### ISSUE TITLE
bugs:strange primitive types

### ISSUE THREAD

**Issue by holi-java** [Microsoft/TypeScript#14643]
Hi,when I use `reflect-metadata` module the primitive is horrifying.if compile the .ts into .js,that every thing run fine and fetch the variable types correctly except Foo,but I runs tests in typescript with different result.they are `Object` instead.I could use `string`,`boolean`,`number`,but there is not a `Date` primitive type.

```ts
function Test(matcher: Matcher<any>) {
    return function (target: any, key: string): void {
        let type = Reflect.getOwnMetadata('design:type', target, key);

        test(`${target.constructor.name} ${key}'s type should ${matcher.description}!`, () => {
            expect(matcher.test(type)).toBe(true);
        });
    }
}

class ReflectMetadataTest {
    // this test always false even if you compile .ts it into .js file
    @Test(DeclaredType.not.is(Foo/*ref function*/)) foo: Foo/*ref interface*/;

    //this test is true when you c om pile .ts it into .js file
    @Test(DeclaredType.not.is(Date)) Date: Date;
    @Test(DeclaredType.not.is(String)) String: String;
    @Test(DeclaredType.not.is(Number)) Number: Number;
    @Test(DeclaredType.not.is(Boolean)) Boolean: Boolean;

    //this test is always true both in .ts & .js
    @Test(DeclaredType.is(String)) string: string;
    @Test(DeclaredType.is(Number)) number: number;
    @Test(DeclaredType.is(Boolean)) boolean: boolean;
    @Test(DeclaredType.is(MyDate)) myDate: MyDate;
    @Test(DeclaredType.is(ReflectMetadataTest)) test: ReflectMetadataTest;
}
```

**Comment by mhegazy** [comment]
The reflect metadata tries to represent types at design time at runtime. This is a lossy processes by definition, since there are types that only exist in design time (e.g. interfaces, type aliases, etc..).

The way this works is for primitives, the boxed values are uses to serialize them:
* `number` => `Number`
* `string` => `String`
* `boolean` => `Boolean`
* `object` => `Object`
* Arrays are always serialized to `Array`
* Classes will be serialized as themselves, since they do exist at run time
* function types will be serialized as `Function`
* Everything else will be serialized as `Object`

Hope this answers your question.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
