### ISSUE TITLE
Narrowing/inference does not work when using generics, but works using inline types

### ISSUE THREAD

**Issue by niieani** [Microsoft/TypeScript#14691]
**TypeScript Version:**  nightly (2.3.0-dev.20170302)

**Code**

```ts
type ObjA = {a: 'a', tag: 'a'}
type ObjB = {b: 'b', tag: 'b'}
type ObjAorB = ObjA | ObjB
type ObjWithSomeB = {b: any}

// just a helper to make the point, ignore:
function itIs<T>(param : any): param is T {
  return true
}

function infer(a: ObjAorB) {
  if (itIs<ObjWithSomeB>(a)) {
    return a
  }
  throw new Error()
}

function inferParametrizedIs<T>(a: ObjAorB) {
  if (itIs<T>(a)) {
    return a
  }
  throw new Error()
}

function inferParametrizedParam<T>(a: T) {
  if (itIs<ObjWithSomeB>(a)) {
    return a
  }
  throw new Error()
}

function inferParametrizedBoth<T, Y>(a : T) {
  if (itIs<Y>(a)) {
    return a
  }
  throw new Error()
}

const obj = {a: 'a', tag: 'a'} as ObjAorB

// narrowed down correctly to 'ObjB':
infer(obj)

// narrowed down incorrectly to (ObjA & ObjWithSomeB) | (ObjB & ObjWithSomeB)
// which is equivalent to {b: any, tag: "a" | "b"}:
inferParametrizedIs<ObjWithSomeB>(obj)

// narrowed down incorrectly to 'ObjWithSomeB':
inferParametrizedParam<ObjAorB>(obj)

// narrowed down incorrectly to 'ObjWithSomeB':
inferParametrizedBoth<ObjAorB, ObjWithSomeB>(obj)
```

**Actual behavior:**
In all 4 cases the types are exactly the same. The only thing that differs is the placement of those types -- either inline or parametrized via generics.

**Expected behavior:**
I would expect TypeScript to behave consistently in all 4 cases, i.e. correctly narrow down the type to `ObjB` in all presented cases.

**Comment by mhegazy** [comment]
Narrowing in general is done on weeding out types from a union that are structurally compatible to the condition being used to narrow. This can not be done in the case of generic types, since the type that will be used at instantiation is not known yet. 

for instance in 

```ts
function infer(a: ObjAorB) {
  if (itIs<ObjWithSomeB>(a)) {
    return a
  }
  throw new Error()
}
```
The compiler can attest here that a has to be `ObjB`, and not anything else, since the input was limited to `ObjA` or `ObjB`, and the only one of both that is assignable to `ObjWithSomeB` is `ObjB`.

Now for the generic ones, which are all the result of the same behavior:

```ts
function inferParametrizedIs<T>(a: ObjAorB) {
    if (itIs<T>(a)) {
        return a
    }
    throw new Error()
}
```

The compiler does not know what `T` is, and hence can not do the narrowing the way it did before. the best approximation here is to say well, it gotta be a `T` since you are in the true branch of the if statement, but it also might still be `ObjA | ObjB`, and that gives you `(ObjA | ObjB) & T` which is the same as the distributed version `(ObjA & T) | (ObjB & T)`.

it is also worth nothing that the calls below are not contributing to the issue, the type comes from the function. this is different from Hindley–Milner-based type systems that will flow constraints from call sites, so the behavior will depend on how you call it. in TS type system the behavior will be the same regardless of the calls.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
