### ISSUE TITLE
static types checking not working properly when retrieving values from the array

### ISSUE THREAD

**Issue by abdooay** [Microsoft/TypeScript#14705]
**TypeScript Version:**  2.2.1 

**Code**

```ts
var values :any[] =["a", "b", 1 ,2, true, false];

var fname :number =values[0];

console.log(typeof(fname));
```

**Expected behavior:**

fname reports compile error as value[0] is a string and variable fname should has only numbers

**Actual behavior:**
fname set string value to number variable

**Comment by aluanhaddad** [comment]
> values[0] is a string

No it is not, it is `any` because you said it was.

So firstly, avoid writing `any`, secondly don't annotate everything, and lastly the Angular 2 tutorials/examples or not a good way to learn TypeScript as a language.

I mention the Angular 2 tutorials/examples because I don't see this kind of code coming from anywhere else, but I do so see it used there and hence on every stack overflow question about Angular 2. This awful style.
