### ISSUE TITLE
Confusing error message when using `as`

### ISSUE THREAD

**Issue by altschuler** [Microsoft/TypeScript#14739]
**TypeScript Version:**  2.2.1

**Code**

```ts
interface Person {
    age: number;
    name: string;
}

const bob = { height: 1.9, name: 'bob' } as Person;
```

**Expected behavior:**
An error saying that `height` is not a valid property for `Person`. Or even better an error saying "Either remove `height` or add `age`".

**Actual behavior:**
An error saying:
```
Type '{ height: number; name: string; }' cannot be converted to type 'Person'.
  Property 'age' is missing in type '{ height: number; name: string; }'.
```

Which is correct, but confusing because removing `height` avoids the error.

**Comment by RyanCavanaugh** [comment]
Assertions require assignability in one direction or the other; in this case that process produces two different errors - either error might be the "better" one and we don't have any idea which the user might prefer to see. Showing both tends to be bad because it makes it look like you need to make *two* program edits instead of one.

**Comment by DanielRosenwasser** [comment]
To be pedantic, they require *comparability* in either direction. You need to cast "up" and then "down". Alternatively, declare `height` as an optional member.

**Comment by altschuler** [comment]
Thanks guys, what you're saying makes sense. I still find it to be a less informative error message, but I can't think of a better solution, so closing.
