### ISSUE TITLE
Number literal type allows increment

### ISSUE THREAD

**Issue by mihailik** [Microsoft/TypeScript#14745]
**TypeScript Version:**  2.2.1 / Playground

**Code**

```ts
var s10: 10 = 10;
s10++;
s10 += 1;
s10 = s10 + 1; // Type 'number' is not assignable to type '10'.
```

**Expected behavior:**
Compiler errors on all three lines

**Actual behavior:**
Only errors on the last line.

This looks like a clear bug. A bit more subtle case is a [union of literals](https://github.com/Microsoft/TypeScript/issues/4639#issuecomment-287712552) where increment may or may not lead to the correct type. That subtlety should probably be folded into integer types, and ignored for now. Increments and `+=` on literal type should error.

**Comment by RyanCavanaugh** [comment]
This is somewhat tricky. What's your take on this?
```ts
var n: number = ...;
var s: 10 | 11 | 12 = 10;
s += n;
```

**Comment by typeversity** [comment]
Hello, I had intended to create an issue for this exact same bug today. I'm happy to have done the due diligence & found it's an open issue already.

@mhegazy I would be willing to help out if someone with compiler internals knowledge would be kind enough to give me a few pointers on what source files may need to be attacked. I have a basic feel for getting around the compiler code having contributed a tiny PR a year or two ago. Thanks for any tips on getting started!

**Comment by indiescripter** [comment]
(Resubmitting comment as had initially submitted under a different github account name)

I happened on precisely this bug today & am pleased to find it's a known problem.

@mhegazy I would be willing to help out on this issue if someone with compiler internals knowledge would be kind enough to give me a few pointers on what source files need to be addressed. I have a basic feel for getting around the compiler code having contributed a tiny PR a year or two ago. Thanks for any tips on getting started!

**Comment by DanielRosenwasser** [comment]
@indiescripter go for it! Everything you need should be in `checker.ts` where we check against binary and unary expressions.

We also need a new error message like

```
The literal type '{0}' cannot be modified.
```

So go ahead and add that into `diagnosticMessages.json` and run `jake generate-diagnostics`.

**Comment by indiescripter** [comment]
Thanks @DanielRosenwasser for the heads up. I'll give it a go in slow time, in-between other commitments.

**Comment by weswigham** [comment]
FYI, 
```ts
var s10: 10 | 11 = 10;
s10++;
```
could be construed as probably valid code. We just don't do any similar analysis right now (and made a design choice not to).

**Comment by collin5** [comment]
@indiescripter Are you still working on this? Would love to give this a try if otherwise.

**Comment by collin5** [comment]
Sorry about that. Will be starting on this soon. Thank you!

**Comment by collin5** [comment]
I've created a Pull request to resolve this #28344

**Comment by ahejlsberg** [comment]
Some thoughts on this issue...

While it doesn't seem unreasonable to disallow increment, decrement, and compound assignment operators on variables of unit types, it also doesn't seem particularly useful. It just isn't meaningful or common to declare _mutable_ variables of unit types (what would be the point?) so we wouldn't be solving a real world problem.

The _real_ scenario is the semantics of applying those operators to variables of literal union types, i.e. unions of unit types. I don't think it is feasible to just error here--after all, it is perfectly fine to increment a value of type `0 | 1 | 2`. Rather, in order to do better we would have to support "type math", i.e. reflecting the effects of the built-in operators on sets of possible values. For example, incrementing a value of type `0 | 1 | 2` should yield a value of type `1 | 2 | 3`. However, this quickly gets unwieldy when both operands are union types. For example, multiplication of two values of literal union types with n and m possible values would produce a literal union type with n * m possible values.

We have previously decided not to do this because the added complexity (conceptual and in implementation) doesn't justify the marginal gains in type checking. I think this decision still holds, so I'm not sure we really want to do anything here.

**Comment by mihailik** [comment]
Better suggestion.

NO MUTATING operators on ANY literal types.
Fine to have mutating operators on unions, those have funky use cases.
