### ISSUE TITLE
"getter" parser bugs

### ISSUE THREAD

**Issue by nowindowsowrking** [Microsoft/TypeScript#14742]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**
({ get a() { return b } })
({ get a() {} })
({ get if() {} })
({ get true() {} })
({ get false() {} })
({ get "a"() {} })
```ts

Tested in the playground.

```

**Expected behavior:**

Should parse

**Actual behavior:**

Throws an error

**Comment by cevek** [comment]
There are errors only concerning the return void values in the getters
```ts
({ get a() { return b } });
({ get a() { } });
({ get if() { } });
({ get true() { } });
({ get false() { } });
({ get "a"() { } });
```

**Comment by nowindowsowrking** [comment]
@RyanCavanaugh According to TC39 this should all parse. And this combos are from TC39-parser tests. So if this works as intended, it means that TypeScript does not follow the  ECMA standards?

**Comment by blakeembrey** [comment]
@nowindowsowrking I just looked at it in the playground and they all parse (http://www.typescriptlang.org/play/#src=(%7B%20get%20a()%20%7B%20return%20b%20%7D%20%7D)%3B%0A(%7B%20get%20a()%20%7B%20%7D%20%7D)%3B%0A(%7B%20get%20if()%20%7B%20%7D%20%7D)%3B%0A(%7B%20get%20true()%20%7B%20%7D%20%7D)%3B%0A(%7B%20get%20false()%20%7B%20%7D%20%7D)%3B%0A(%7B%20get%20%22a%22()%20%7B%20%7D%20%7D)%3B#src=(%7B%20get%20a()%20%7B%20return%20b%20%7D%20%7D)%3B%0A(%7B%20get%20a()%20%7B%20%7D%20%7D)%3B%0A(%7B%20get%20if()%20%7B%20%7D%20%7D)%3B%0A(%7B%20get%20true()%20%7B%20%7D%20%7D)%3B%0A(%7B%20get%20false()%20%7B%20%7D%20%7D)%3B%0A(%7B%20get%20%22a%22()%20%7B%20%7D%20%7D)%3B). Perhaps you have an issue with it erroring on `void`? That error seems reasonable, since it's trying to tell you your getter needs to return a value - do you feel that needs to be relaxed?

**Comment by RyanCavanaugh** [comment]
As Blake said, these all pass according to the *parser*. They generate type warnings but that is intentional (see http://stackoverflow.com/questions/41750390/what-does-all-legal-javascript-is-legal-typescript-mean)
