### ISSUE TITLE
Differentiating Type Guards fail with unions of interfaces and types.

### ISSUE THREAD

**Issue by robmcm** [Microsoft/TypeScript#14835]
**TypeScript Version:**  2.2.1 (what ever is in the playground)

**Code**

```ts
interface Fish { type: 'fish', colour: string, swim: () => void };
interface Bird { type: 'bird', colour: string, fly:  () => void};
type FlyingFish = Fish & Bird;

function isFlyingFish(value: Fish | Bird | FlyingFish): value is FlyingFish {
    return value.hasOwnProperty('fly') && value.type === 'fish';
}

let birdOrFish: Fish | Bird;
if (birdOrFish.type === 'fish') {
    birdOrFish.swim(); // No error, cast as fish
} else {
    birdOrFish.fly(); // No error, cast as bird
}

let birdFishOrFlyingFish: Fish | Bird | FlyingFish;
if (isFlyingFish(birdFishOrFlyingFish)) {
    birdFishOrFlyingFish.swim();  // No error cast as FlyingFish
    birdFishOrFlyingFish.fly();
} else if (birdFishOrFlyingFish.type === 'fish') {
    birdFishOrFlyingFish.swim(); // Error, Property 'swim' does not exist on type 'Fish | Bird'. Property 'swim' does not exist on type 'Bird'.
} else {
    birdFishOrFlyingFish.fly(); // Error, Property 'fly' does not exist on type 'Fish | Bird'. Property 'fly' does not exist on type 'Bird'.
}

```

**Expected behavior:**
Flow analysis should be able to cast to a type or an interface when using a differentiating type guard.

**Actual behavior:**
Once a type is added alongside an interface as part of a union, the flow analysis doesn't cast with differentiating type guards (but does with user defined type guards).

**Work around:**
Don't use types and interfaces for similar things, not sure of the full limitations of each. (I assume you can't use types with classes, but you can't use some features like partials with interfaces?)

**Comment by dardino** [comment]
one more simplier case:
```typescript
interface Type1 { 
    PropA: string;
}
interface Type2 { 
    PropB: string;
}

var a: Type1 | Type2;

if (typeof a === "string") {
    a // a: never  OK correct!
}

function IsString(v: any): v is string {
    return typeof v === "string";
}

if (IsString(a)) {
    a // a: (Type1 & string) | (Type2 & string)      ??? WHY ??? 
}
```

**Comment by RyanCavanaugh** [comment]
Issue in the OP has been fixed.

@dardino we intentionally don't reduce "impossible" types to `never` unless it's in a position where there's a bare contradiction with a primitive or unit type. Instatiation, especially of tagged types, can reasonably produce types which appear to have contradictory members but are still totally usable in their non-contradictory parts. Allowing those types to exist is generally better because they're still useful and actually allow some level of "debugging", whereas simply always producing `never` when some 4-deep property has a contradictory type would be extremely frustrating.

**Comment by robmcm** [comment]
Thanks!
