### ISSUE TITLE
Visual Studio: Support "Automatic brace completion"

### ISSUE THREAD

**Issue by Noah-Huppert** [Microsoft/TypeScript#1484]
In Visual Studio if you go into the options for TypeScript(Tools > Options > Text Editor > TypeScript > General) the "Automatic brace completion" option is grayed out.

![Automatic brace completion options grayed out](http://i.imgur.com/rI6M1Q6.png)  

I was wondering why this is and if there is any way to turn this on. 
  
  
**Visual Studio Version**: *Visual Studio Express 2013 for Web v12.0.31101.00 Update 4*  
**OS**: **Windows 8.1*

**Comment by nheinbaugh** [comment]
Any updates on this?

**Comment by mhegazy** [comment]
This is still on our backlog at the moment.

**Comment by superactro** [comment]
I need this feature wow.

**Comment by DmitryEfimenko** [comment]
+1

**Comment by gabguy** [comment]
+1

**Comment by BKaraargirov** [comment]
Tho resharper adds the feature, I would preffer using vanilla studio when using pure JS code.
+1

**Comment by kaotik4266** [comment]
+1

**Comment by CyrusNajmabadi** [comment]
For those talking about resharper, could you let me know what they do with something like this:

```ts
var foo = 0;
var v = foo<
```

as well as

```ts
function foo<T>(t: T) { }
var v = foo<
```

In the first example, you should not get automatic completion as you are typing an arithmetic expression.  in the latter, you should, because you're typing generic type arguments.

However, to do this properly, you need both your syntax tree up to date, and you need your semantics to be accurate as well (so you can tell what 'foo' means).

Of course, we could just not have auto-completion on ```<```.  However, even for the other cases, i.e.:

1. /
2. "
3. '
4. (
5. {
6. [

We'd still need fairly accurate syntactic understanding of your file to ensure that we didn't, for example, autocomplete these guys inside a comment or a string.

@mhegazy If you did this, i'd actually recommend a dedicated thread just for this feature.  Because it needs to be synchronous, but is also involved with typing it really needs to be uninterrupted when it runs.  If you avoid completion on ```<``` then you don't need semantics and you can just have *another* syntactic thread.

**Comment by mhegazy** [comment]
> @mhegazy If you did this, i'd actually recommend a dedicated thread just for this feature. Because it needs to be synchronous, but is also involved with typing it really needs to be uninterrupted when it runs. If you avoid completion on < then you don't need semantics and you can just have another syntactic thread.

how about using the formatting thread? all these trigger characters are not formatting trigger characters, so we know the thread will be likely idle.

**Comment by CyrusNajmabadi** [comment]
@mhegazy Ah, I think you're right.  None of the characters should overlap.  And because they're all synchronous, we'll essentially only ever have one in the queue at a time, so we don't have to worry about bottlenecks.  So that thread should be a good choice here.

**Comment by danquirk** [comment]
Many requests for this feature are coming from folks who use text editors that have nowhere near enough understanding of the code to be 100% correct in their completion behavior. Let's not let the perfect be the enemy of the good.

In Sublime < is not completed. Most of the others characters are completed in any non-string context. The closing element is skipped over when you type the closing element. It's immensely useful and the kind of feature that seems like a 'nice to have' for those who aren't used to it but an actual adoption blocker for people who are used to it.
![bracecompletion](https://cloud.githubusercontent.com/assets/7121557/10179118/c502e510-66b8-11e5-92b3-bee685704eab.gif)

**Comment by DanielRosenwasser** [comment]
See https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/95

I think we can just forget about `<` for now.

**Comment by jimior2** [comment]
This is really a great feature, nice to have it. It could improvement productivity.

**Comment by jimior2** [comment]
As I install visual studio code, and vs code have typescript auto brace, why didn't VS2015 didin't have...

**Comment by jonathansotoan** [comment]
:+1: 
Any update on this issue? it's a little annoying having to close every brace manually

**Comment by Anjmao** [comment]
+1. Currently it event better to write Typescript on visual studio code which is free, and we pay a lot of money for our visual studio licences and we have this annoying braces problem.

**Comment by CBuntrock** [comment]
+1 But guys please don't shout like "I pay money give me what I want". Still a young product, many features are requested...

**Comment by arangil** [comment]
+1

**Comment by TomMikinley** [comment]
+1

**Comment by eijoac** [comment]
+1

**Comment by mhegazy** [comment]
With new [reactions added to github issues](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) I suggest adding the "+1" to the the main issue to indicate an "up vote"

**Comment by anmolg26** [comment]
+1

**Comment by pgorbas** [comment]
+1
Also I still do not see split window support  ( for ts => js )returned, despite several post saying it was...

**Comment by paulvanbrenk** [comment]
@pgorbas were did you see the split window support mentioned? It never was a feature of TypeScript, but part of [Web Essentials](http://vswebessentials.com/).

**Comment by Noah-Huppert** [comment]
# Dear anyone who is going to post "+1" in the future! 
Please note that Github recently added reactions. Just scroll up to the top and click the little smiley button

![Add a reaction](https://cloud.githubusercontent.com/assets/25792/13683303/d55b8b7e-e6ba-11e5-9b31-59a8db92e456.gif)

**Comment by abdu292** [comment]
Wondering if there is an update?

Started with Angular 2 + TypeScript, and really looking for this feature (along with many others on TypeScript).

Please update us. Thanks!

**Comment by paulvanbrenk** [comment]
@abdu292 I checked in the script side changes, but there needs to be Visual Studio support to make this work, that should be in the next release for TypeScript.

**Comment by brendon-colburn** [comment]
Yeah kind of crazy that this is in code but not enterprise, vs 2015 update 2 just came out and this still isn't there after being in the backlog for almost 2 years.

**Comment by paulvanbrenk** [comment]
@brendon-colburn  I feel your pain, and that's the reason I stick to pure VS. We're getting some breathing room to spend more time on features, by making improvements to our infrastructure. And hopefully we can publish nightly drops of the VS tools soon.

**Comment by brendon-colburn** [comment]
Interesting.  Could you define "pure VS" for me?  It's just a nuisance
really, but I felt a need to say something due to the length of time this
has been in backlog status.  Not trying to be a nag, I understand that
certain development tasks take priority.

Thanks,

Brendon

**Comment by paulvanbrenk** [comment]
"pure vs" == no extensions like ReSharper etc.

**Comment by VSG24** [comment]
This is nonsense. When are we going to get this?? How hard could it be to implement this???

**Comment by DanielRosenwasser** [comment]
@VSG24 it's not the work itself, it's just that this will be part of a release. we should have it in TypeScript 2.0, but you'll have to be patient in the mean time.

**Comment by trollcop** [comment]
This is the first feature I turn OFF immediately if the editor does it.  I know EXACTLY when and why I will add a closing brace to my code, and I don't need some dumb software appending it for me.

Hopefully this stays WONTFIX forever

**Comment by mhegazy** [comment]
Automatic brace completion should be supported with TS 2.0 RC and later. The feature can be enabled/disabled from tools options (as noted in the OP).

**Comment by pgorbas** [comment]
Instead of saying won't fix for all the people that want it, wouldnt making it a toggle option be better?


Sent from my Sprint Samsung Galaxy S7 edge.
-------- Original message --------From: dongie <notifications@github.com> Date: 9/7/16  2:06 AM  (GMT-06:00) To: Microsoft/TypeScript <TypeScript@noreply.github.com> Cc: fubar <pgorbas@yahoo.com>, Mention <mention@noreply.github.com> Subject: Re: [Microsoft/TypeScript] Visual Studio: Support "Automatic brace
  completion" (#1484) 
This is the first feature I turn OFF immediately if the editor does it.  I know EXACTLY when and why I will add a closing brace to my code, and I don't need some dumb software appending it for me.

Hopefully this stays WONTFIX forever

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Microsoft/TypeScript","title":"Microsoft/TypeScript","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Microsoft/TypeScript"}},"updates":{"snippets":[{"icon":"PERSON","message":"@trollcop in #1484: This is the first feature I turn OFF immediately if the editor does it.  I know EXACTLY when and why I will add a closing brace to my code, and I don't need some dumb software appending it for me.\r\n\r\nHopefully this stays WONTFIX forever"}],"action":{"name":"View Issue","url":"https://github.com/Microsoft/TypeScript/issues/1484#issuecomment-245193674"}}}
