### ISSUE TITLE
Import Sqlite3 module not found 

### ISSUE THREAD

**Issue by samarulrajt** [Microsoft/TypeScript#14857]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
import { Sqlite3 } from "sqlite3";


```

**Expected behavior:**
i need to use Sqlite object from the import.
steps for importing Sqlite3
**Actual behavior:**
WARNING in ./~/sqlite3/lib/sqlite3.js
4:14-35 Critical dependency: the request of a dependency is an expression

ERROR in ./~/sqlite3/lib/sqlite3.js
Module not found: Error: Can't resolve 'node-pre-gyp' in 'C:\xampp\htdocs\dwfootest\node_modules\sqlite3\lib'
 @ ./~/sqlite3/lib/sqlite3.js 1:13-36
 @ ./src/app/currency/currency.component.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
webpack: Failed to compile.

**Comment by mhegazy** [comment]
looks like a webpack ts loader issue. what loader are you using?

do you see any errors if you just call `tsc --p <path to your tsconfig.json>`?

**Comment by blakeembrey** [comment]
It's purely webpack, not related to TypeScript. See https://github.com/mapbox/node-sqlite3/blob/f1456b1cc96e89b82ac37b1896f23ef14aff80b6/lib/sqlite3.js#L4, which is where the error is mentioning. The issue is "the request of a dependency is an expression", which I imagine makes it hard for Webpack to bundle properly. There's even an issue already logged: https://github.com/mapbox/node-sqlite3/issues/698. Not sure why you'd be using Webpack with a native module, but you should note that it's not possible to bundle native node additions for the browser.

**Comment by samarulrajt** [comment]
@mhegazy  how to check the default loader ? and what is the loader do i need to point?

**Comment by mhegazy** [comment]
looks like @blakeembrey has better information about this issue above.

**Comment by samarulrajt** [comment]
@blakeembrey , @mhegazy  Thanks for your time!
