### ISSUE TITLE
Excess property checking broken when using ThisType

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#14910]
Found in the TypeScript 2.3 nightly

Repro 1:

```ts
Object.defineProperty(window, "prop", { value: "v1.0.0", readonly: false });
```

Repro 2:

```ts
interface A { x?: string }
let a: A & ThisType<any> = { y: 10 }
```

Expected: Error on the `readonly` and `y` properties in the examples above.
Actual: No error!

**Comment by mhegazy** [comment]
this type is an empty interface, this is not any different from `let a: {} = { y : 10 };`

**Comment by DanielRosenwasser** [comment]
Yes, I understand the what is occurring, but I think that this behavior is undesirable.

**Comment by ahejlsberg** [comment]
The issue here is that we suppress excess property checks in assignments to intersection types that contain an empty object type--even when the full type isn't empty. For example, the following should be an error but isn't:

```ts
let x: {} & { x: number } = { y: "hello" };
```

The issue shows up with `ThisType` simply because it is an empty object type.
