### ISSUE TITLE
Strange check usage behaviour of undefined union type 

### ISSUE THREAD

**Issue by cevek** [microsoft/TypeScript#14929]
**TypeScript Version:**  2.3.0-dev.20170321

**Code**

```ts
class Foo {
    bar: string | undefined = undefined;
}
var foo = new Foo();
var x = foo.bar;
x += 'abc'; // no error, but should be

var y: string | undefined;
y += 'abc'; // no error, but should be

var z: string | undefined = undefined;
z += 'abc'; // error

var u;
u += 'abc'; // error
```

**Comment by DanielRosenwasser** [comment]
I believe the issue is that `+` and `+=` are permissive if one of their arguments is a `string`. If you try the following:

```ts
class Foo {
    bar: number | undefined = undefined;
}
var foo = new Foo();
var x = foo.bar;
x += 1;
```

You actually will get an error.

**Comment by cevek** [comment]
So, but why it is not permissive for that case:
```ts
var z: string | undefined = undefined;
z += 'abc'; // error
```

**Comment by aluanhaddad** [comment]
@cevek because you are in a local CFA (Control Flow Analysis) scope. The compiler knows that `z` is actually exactly `undefined` and not possibly a `string` in that fragment of code. The type of the variable is sort of misleading in that case.

Consider
```ts
let z: string | undefined = '';
z += 'abc'; // no error
```
Personally, I would remove such a type declaration. It actually contradicts the compilers knowledge, although in the CFA context, the compiler's knowledge fortunately takes priority.

In a class such as your opening example, the compiler does not know, just like it does not know inside of a function (classes are functions anyway).

**Comment by cevek** [comment]
Thank you for detailed explanation.
Can you also explain, what the point of permissive concat string with `null` and `undefined` types?
```ts
var x = '' + undefined + null; // no error
```

**Comment by aluanhaddad** [comment]
Thats a more philosophical question. I believe it's because it's fairly safe to do as long as one of the operands is a `string` you'll get a `string` back. It's permitted in many statically typed languages although that in itself is not a good reason, it's fairly handy to be able to coalesce like that. This pattern is fairly common in JavaScript and I believe it used to actually result in a TypeScript error, but was later relaxed.

**Comment by ethanresnick** [comment]
Wait... why are the `y` and `z` cases in the OP treated differently? If CFA recognizes that `z` is exactly undefined at the time of the `+=`, shouldn't it do the same for `y`?

**Comment by cevek** [comment]
@aluanhaddad I still can't imagine who needs a string `undefinedFooBar`
```ts
var s: undefined | string;
s += 'Foo';
s += 'Bar';
```

**Comment by aluanhaddad** [comment]
@cevek yeah, it doesn't behave the way it does in other languages so my point above is moot. I think it is likely a source of bugs and perhaps should be reconsidered.

**Comment by DanielRosenwasser** [comment]
> Can you also explain, what the point of permissive concat string with `null` and `undefined` types?

If we didn't allow this, it'd be painful to print-debug your applications. You could still argue that we could catch more bugs by disallowing it though.

>So, but why it is not permissive for that case:
>```ts
>var z: string | undefined = undefined;
>z += 'abc'; // error
>```

I'd say that `+=` with a `null | string` LHS should probably be allowed for consistency.

**Comment by cevek** [comment]
> it'd be painful to print-debug your applications

Why it should be painful? You just can set force type by `!`
```ts
function debug(s: string | undefined) {
   console.log('Variable value is: ' + s!);
}
```

I see, that strings concatenation very kindly for everyone :)
```ts
var s = 'foo' + true + undefined + null + 0 + function(){}; 
```

Concat non null types is normally, but I think for `null` and `undefined` types you must check the value, because it hasn't any sense to concat undefined to string.

**Comment by RyanCavanaugh** [comment]
The gained consistency doesn't seem worth making people deal with another breaking change here.
