### ISSUE TITLE
Show fixes (tool tip issue)

### ISSUE THREAD

**Issue by DuncanFaulkner** [Microsoft/TypeScript#14933]
This started appearing when I've migrated a project to Angular 4 (not sure if its related)
When clicking on the "light bulb" to fix issues I see "Import from @angular/core/core" which doesn't exist as far as I can tell. Not sure if this is a bug or not, just wanted to highlight the issue 
 
![typescript-issue](https://cloud.githubusercontent.com/assets/1952116/24507450/64acf534-1558-11e7-9f6b-a8b51b99e193.png)

OS: unbuntu 16.04 LTS
TypeScript Version:**  2.2.2

**Comment by billti** [comment]
Which editor are you using? + @zhengbli

**Comment by zhengbli** [comment]
I assume you are using VSCode, are you using other extensions that provides importing fixes? Because as far as I know we don't provide "add all missing imports". 

Also, when you say "doesn't exist", do you mean the file (@angular/core/core) does not exist? Would it give you an error if you add the import?

**Comment by DuncanFaulkner** [comment]
Hi, 
Yes sorry using VSCode, and meant to say that this '@angular/core/core' generates an error in the code as you would expect. Just checked installed extensions and didn't realise I had Typescript hero installed I will remove/reinstall this and see if it makes any difference.

Apologises
