### ISSUE TITLE
Add missing import use package.json "typings" property

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#15020]
_From @kukjevov on April 4, 2017 18:30_

- VSCode Version: 1.10.2
- OS Version: Windows 10

Add missing import is great feature but it does not work best way. 

Lets say i have module `@ng/common`
in module i have `package.json` in root directory and `index.d.ts` in dist directory.

In package.json i have `"typings": "dist/index.d.ts"`. 

When i want to use this module i want to write `import {Utils} from '@ng/common';` but vscode quick fix import missing import offers me different imports like this `import {Utils} from '@ng/common/dist';` which is not what i want. Is it possible to make it look into package.json for obtaining these information about import? Also when i use `@angular` it is same. Sometimes it even offers me more options. Same things reexported from multiple files, but none exported using package.json. 

Also nice thing would be if it uses shortest "path" export if some type is reexported.

I dont know if this is thing for vscode, or typescript directly.

Thank you for any help :).

_Copied from original issue: Microsoft/vscode#23898_

**Comment by mjbvz** [comment]
@kukjevov  Can you please provide a small example project that demonstrates this issue?

**Comment by kukjevov** [comment]
Hello :). 

Thx for quick reaction. Here is example that illustrates what i described.

https://github.com/kukjevov/typescript-import

if you clone it and run `npm install` then open it in vscode you can see problem in example.ts.

<img src="https://4imnxg-sn3301.files.1drv.com/y4mTNwlwZj2u-IksovPMP0pByfVyPRIZtTRqMdC25V2NaBRVcmCC_QFLBPjaeHtrLYR_hcqgM_xdBdGJPOQLIRH13j53qaMN14sTpWS-ZIXbnYEVTiRh3hLs8VNNDj_P1U7VXnNavpVAyutNBBfthm49BUllhUVyzEt7K6Wjn9Cz3pGdbSUpzsO9fxCov3SSvxOp7fyR0HRQgcySUOTR4X6kA?width=615&height=172&cropmode=none"></img>

In index.ts you can see what i want and how imports should look like. But for `'@ng/common'` in `example.ts` it offers me path to `index.d.ts` (`'@ng/common/dist'`) even if i specified `"typings"` property in `package.json` for `@ng/common` module which is correctly used by typescript compiler but not by typescript import helper.

Same thing happens for `'@angular/core'` where they have `core.d.ts` in root directory, which is pointed to from `package.json` by `"typings"` property, but it is not used. In this case it is even worse, because same type is offered 4 times, but all from wrong file.

Also interesting thing that i found out, that if i dont have at least one import from `'@angular/core'` in some file (this time in `index.ts`) it does not offer me anything, not even bad import. How does it work? Does is it scan node_modules?

Just one note to this, is there going to be option to set if i want spaces around brackets in import statements?

Anyway thx for great job and any help :)

**Comment by aluanhaddad** [comment]
I've had similar issues where package.json `typings` points to a top level file but the quick-fix always grabs the file from src/index because I distribute the source as part of my npm package.

**Comment by kukjevov** [comment]
@mjbvz Have you looked at this :)? Thank you for any help :).

**Comment by mjbvz** [comment]
@kukjevov I took a look at this issue on the VSCode side but the problem seems to lie with the TypeScript server itself. That's why I moved the issue to the TypeScript repo.

A TypeScript contributor should be able to help investigate this issue

**Comment by kukjevov** [comment]
Hello can some of Typescript team look at this, it would be nice feature :).

ping @sandersn @ahejlsberg @yuit @RyanCavanaugh 

Thank you :)

**Comment by mhegazy** [comment]
tracked by https://github.com/Microsoft/TypeScript/issues/15223
