### ISSUE TITLE
[IntelliSense] [JavaScript] Go to Definition Doesn't Use Source Map

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#15063]
_From @niedzielski on February 26, 2017 3:50_

- VSCode Version: v1.9.1
- OS Version: Ubuntu v16.10

Steps to Reproduce:

1. Bundle a collection of JavaScript files local to the project and generate a source mapping.
2. Import the bundle.
3. Go to definition on any symbol present in the bundle.

The expected result is to go to the definition in the local JavaScript files. The actual result is to go to the definition in the bundle.

## [Example 1](https://github.com/niedzielski/vscode-map-go-to-def) (very tiny)

1. Open test/index.js.
2. Control-click the `foo` import.

The expected result is to go to the definition of foo in src/index.js. The actual result is to go to the definition in the build product, build/index.js.

## [Example 2](https://github.com/wikimedia/applib/blob/c6b0866/test/CollapseElement.js#L7)
We transpile and bundle our code to applib.js and a corresponding map, applib.js.map. The code that is exercised by our unit tests comes from this bundle directly. This is partially due to the suggested Rollup configuration but also means the same code exercised is the same code distributed. Unfortunately, go to defintion of `applib.CollapseElement.getTableHeader` goes to the bundled code instead of the original sources under `src/`.

_Copied from original issue: Microsoft/vscode#21433_

**Comment by mjbvz** [comment]
Moving over to TypeScript since this does not seem like an issue with VSCode itself. I'm not sure if a `jsconfig.json` can be configured so that `Go To Definition` behaves as @niedzielski would like in this case

**Comment by RyanCavanaugh** [comment]
Doesn't seem to be much demand for this. We can revive if needed since we now have sourcemap reading support

**Comment by mherodev** [comment]
I would REALLY like support for this. All of the shared React-adjacent libraries within our company are transpiled, so Go to Definition is essentially broken for all of them.

I'm not sure if there's a better pattern to follow (can I have webpack transpile imports instead of pre-transpiling when publishing, perhaps?), but it's a missing feature that introduces a decent amount for friction for developers when they want to trace behavior back to the source.

**Comment by Amonith** [comment]
Same. The case is simple. We have our own library which is transpiled to ES5 (has to be, because it uses different JS standard, different babel config) and linked to our project through `npm link`. We simply want 
"Go to Definition" to go to the source of the component rather than the transpiled version.

**Comment by sibbl** [comment]
I'd also love to see such a feature being implemented. Especially for monorepos (lerna or yarn workspaces) this totally would make sense.

Currently I'm using the following VS Code extension as a workaround: https://marketplace.visualstudio.com/items?itemName=vlkoti.vscode-sourcemaps-navigator

**Comment by philipbordallo** [comment]
With the addition of the `bundler` option for `moduleResolution` this definitely seems like a helpful thing to have if the assumption is you will be using a bundler to compile the code.

**Comment by philipbordallo** [comment]
Ah, I found the solution for this: enable [`declarationMap`](https://www.typescriptlang.org/tsconfig/#declarationMap) in your tsconfig and things like **go to definition** should correctly go to the original source.
