### ISSUE TITLE
Intellisense shows "mousewheel" as an applicable event 

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/TypeScript#15073]
_From @ajbogh on April 7, 2017 7:36_

mousewheel should be removed from Javascript's intellisense as it is deprecated and only supported in IE6, Chrome 1, Opera 10, Safari 3, and surprisingly IE Edge. If not removed then it should have "(deprecated)" next to it so people don't accidentally use it instead of "wheel".

- VSCode Version: 1.10.2
- OS Version: Ubuntu 16.10

Steps to Reproduce:

1. type "window.addEventListener('mouse..." and notice "mousewheel" as an available option.

https://developer.mozilla.org/en-US/docs/Web/Events/mousewheel

_Copied from original issue: Microsoft/vscode#24184_

**Comment by chrmarti** [comment]
I read the compatibility table as "supported by all major browsers except Firefox".

**Comment by RyanCavanaugh** [comment]
I don't see how removing this helps anyone if it's so widely supported.

**Comment by ajbogh** [comment]
The alternate choice besides removing it was to add a "(deprecated)" notice so that people don't use it instead of "wheel". I understand that perhaps it's not in the best interest to remove it completely, however there's a more standardized approach that's accepted by modern browsers.

This is only a suggestion since the same could also be said about other deprecated features and changing them all would be difficult.

https://developer.mozilla.org/en-US/docs/Web/Events/wheel

**Comment by aluanhaddad** [comment]
There is a definite gap in support between the set of browsers that implement the new `wheelevent` and those that only implement `mousewheel`, but what makes this interesting is that, naturally, neither event has solid mobile support 😁
