### ISSUE TITLE
Don't emit files used to import only for types and interfaces

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#15097]
Folder structure:
```
project
    a
       A.ts
       tsconfig.json 

    b
       B.ts 
```
/a/tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es6",
    "module": "es2015",  
    "outDir": "dist"
  }
}
```

/a/A.ts
```ts
import {B} from '../b/B';
let b:B;
```

/b/B.ts
```ts
export interface B {
    b: number;
}
```

If compile project/a it creates dist folder which contains b folder with empty B.js

It's terrible that it creates folder depth in dist folder

**Comment by RyanCavanaugh** [comment]
Not changing emit structure based on file content is an extremely intentional decision. It'd be crazy if e.g. removing a variable declaration from a file caused some other file to start appearing in a different place. A typical scenario is "I want to comment out all the code in this file" for testing purposes; making an "empty" file like this not emit, or emit in a different place, would totally wreck that.
