### ISSUE TITLE
Weird behaviour with type guards

### ISSUE THREAD

**Issue by tomcumming** [Microsoft/TypeScript#15126]
**TypeScript Version:**  2.2.2

**Code**

```ts
// see my amended example below
```
**Expected behavior:**
`a` should have type `Either<number, string>`
**Actual behavior:**
`a` has the type `{ type: 'left', left: number }`

**Comment by MrAndersen1** [comment]
So, slightly reduced, you're saying that after you have called your typeguard then
`a: { left: number } | { right: number | string }` is `{ left: number } | { right: string }`
Then, I assume, it reduces it further for you since the only thing it can be is { left: number }.

If you change a to be: `const a: Either<number, string>` you will get the type you want.

**Comment by tomcumming** [comment]
@MrAndersen1 updated my example, I thought `a` could be left or right inside the if braces?

**Comment by MrAndersen1** [comment]
You are still telling typescript that "a" will be Either<number, number | string>. If we simplify this to:
`
type Either<A, B> = { left: A } | { right: B };

function foo(a: Either<number, number | string>): a is Either<number, string> {
    return;
} 

let a: Either<number, number | string>;
if (foo(a)) {
    // typescript thinks `a` has the type of { left: number }
    a
}
`
(note that this simplification is just to demonstrate that "type" does not matter since both objects have that property and the value of "a" will not reduce the type if you have explicitly set the type)
And expand "a" to be: { left: number } | { right: number | string }
Then expand your typeguard that says: "a" is { left: number } | { right: string }
Typescript then looks at "a" and sees it cannot be { right: string } either because your declaration of "a" does not fit it. So the only thing it can be is { left: number }

Hope this helps :)

**Comment by tomcumming** [comment]
@MrAndersen1 
Ok just to clarify my example one last time: 
```ts
type Either<A, B> = { type: 'left', left: A } | { type: 'right', right: B };

function foo(a: Either<number, number | string>): a is Either<number, string> {
    return a.type === 'left' || typeof a.right === 'string';
} 

const condition = true; 

const a: Either<number, number | string> = condition
    ? { type: 'right', right: condition ? '123' : 123 }
    : { type: 'left', left: 123 };

if (foo(a)) {
    console.log('wtf', a.left); // undefined
}
```

If the `foo` guard returns true, should we not be rewriting the type for `a` (inside the if body) to `Either<number, string>`? `Either<number, string>` is a valid subset of the type `Either<number, string | number>`, right? (Please point out any typing mistakes in the above example, if they exist).

Run this code and you will log undefined to the console. I think this is incorrect behavior.

**Comment by tomcumming** [comment]
@RyanCavanaugh could you chime in, please?

**Comment by tomcumming** [comment]
one less type variable:
```ts
type Maybe<T> = undefined | { just: T };

function isMaybeString(x: Maybe<number | string>): x is Maybe<string> {
    return x === undefined || typeof (x.just) === 'string';
}

const a: Maybe<string> = { just: '123' };
const b: Maybe<number> = { just: 123 };
const c: Maybe<string | number> = Math.random() < 0.5
    ? undefined
    : (Math.random() < 0.5 ? a : b); 

if (isMaybeString(c)) {
    console.log('why do i have the type undefined', c);
}

```
