### ISSUE TITLE
Control flow analysis for indexers

### ISSUE THREAD

**Issue by dmichon-msft** [Microsoft/TypeScript#15145]
**TypeScript Version:**  2.1.4

I'm assuming this is a general limitation of the control flow type analysis, but it's rather odd that, of the following two semantically identical functions, one has a compilation error and one does not.

**Code**
```ts
// A *self-contained* demonstration of the problem follows...
interface A { type: 'a' }
interface B { type: 'b' }
type Item = A | B;
interface Box {
    a: A[];
    b: B[];
}

function addToBox(box: Box, item: Item) {
    box[item.type].push(item);
}

function addToBox2(box: Box, item: Item) {
    switch (item.type) {
        case 'a':
            box[item.type].push(item);
            break;
        case 'b':
            box[item.type].push(item);
            break;
    }
}
```

**Expected behavior:**
As both functions have the same behavior within the allowed domain (assuming strict null checks), both should compile successfully.

**Actual behavior:**
`addToBox` gives a compiler error 'Cannot invoke an expression whose type lacks a call signature', while `addToBox2` compiles without error.

**Comment by HerringtonDarkholme** [comment]
I would rather argue this might be out of the current scope of TypeScript.

> the following two semantically identical functions

This is apparent to human reader but is hard for compiler to know. 

Control flow analysis is based on AST node. `switch/if`'s ASTs are natural branching. We can narrow a union type to a concrete type in the children AST, and apply stronger type checking constraints on one code path. For example, you cannot re assign item's type.

```ts
    switch (item.type) {
        case 'a':
            item.type = 'b'  // error
            box[item.type].push(item);
            break;
}
```

But indexer's AST does not have branching. `box[item.type]` is resolved to `A[] | B[]`, which is a good expedient. If we would like to support narrowing type on indexer AST node,  I suspect it would be an architectural change because one flow node need to hold multiple separated types (might also incur exponential checking time, say `box[item.type][subitem.type]`). Also, evil mutation will add more complexity. Consider the reassign example above

```ts
var a = box[item.type]
item.type = 'b' // no compile error now, should it be an error in new check?
a.push(item) // compile error now, should it pass new check?
```

**Comment by mhegazy** [comment]
Just to clarify, this is not narrowing. In `box[item.type].push(item);` you want to assert that for every possible type of `item.type`, the call to `push` is correct. The compiler does not do this holistic analysis at the time being. 

Narrowing on the other hand, is a statement removing one or more possible types from the set of types for a value. e.g. the switch statement.

The desired behavior is something that is not doable at the time being.
