### ISSUE TITLE
TypeScript Not Recognizing JavaScript Prototype Class Unless `this` is used

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#15162]
From: http://stackoverflow.com/questions/43354977/how-can-i-make-intellisense-reference-a-js-file-in-another-folder/43356599

**TypeScript Version:**  2.2.2

**Code**

```js
/**
 * @class
 */
function MyClass() { }
const x = new MyClass();
```

**Expected**
Type of `x` is `MyClass`

**Actual**
Type of `x` is `any`

Changing the code to:

```js
/**
 * @class
 */
function MyClass() { this.z = 1 }
const x = new MyClass();
```

Then `x` has a type of `{ z: number }`

**Comment by TheJim01** [comment]
Using the example code above, I'm still seeing `x` resolve as: `const x: {}`

With the second example code, `x` resolves as:
```javascript
const x: {
    z: number;
}
```
While it's technically correct that `x` is an object, it's not saying it's an object of any particular "class" (`MyClass`). Is this the intended behavior (since JavaScript is not strongly-typed?

VSCode 1.20.1 (x64 if that matters)
TS 2.7.1

**Comment by mhegazy** [comment]
> While it's technically correct that x is an object, it's not saying it's an object of any particular "class" (MyClass). Is this the intended behavior (since JavaScript is not strongly-typed)?

yes. ES6 classes have a well defined meaning. while the type system understands the function pattern above as a class-equivalent, it will not use the term `class` for it since it is not.
