### ISSUE TITLE
Type inference issue in subclasses

### ISSUE THREAD

**Issue by tommytroylin** [Microsoft/TypeScript#15191]
**TypeScript Version:**  2.2.2 

**Code**

```ts
class A<T> {
  foo: T;
}

class B extends A<'bar'> {
  foo = 'bar';
}

```
workaround:
```ts
class A<T> {
  foo: T;
}

class B extends A<'bar'> {
  foo = 'bar' as 'bar';
}
```
**Expected behavior:**
No Error;
**Actual behavior:**
Type string is not assignable to type 'bar';

I don't know if this behavior is intended.
I think type inference should be more accurate in this case to make programmers not to write `as sometype` once again.

**Comment by aluanhaddad** [comment]
The problem is that `foo` "overrides" (not really but in OO speak) the base property and is allowed to declare a less specific return type.

Improved workaround:
```ts
class A<T> {
  foo: T;
}

class B extends A<'bar'> {
  readonly foo = 'bar';
}
```
Note there have been dozens of issues about inheriting exact signatures, and @sandersn worked very hard on multiple potential implementations. See #6118 and #10570 where this is discussed in detail.

Personally, the compile time checked immutability in the above workaround is a nice side-effect at least.
