### ISSUE TITLE
Control flow analysis based on operators applied to an argument

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/TypeScript#15196]
**TypeScript Version:**  2.2.1 /

**Code**

```ts
function foo(a) {
  return a * 2
}

foo(''); // Flow throws an error but TypeScript marked foo as foo(a:a ny): number;
```

**Expected behavior:**
`a` is type `number`
**Actual behavior:**
`a` is type `any`

[Try in Flow REPL](https://flow.org/try/#0GYVwdgxgLglg9mABMOcAUBDAlIg3gKEUQCcBTKEYpDRAKkQCZ8BfffFdAck6yA)

[Try in TypeScript REPLE](http://www.typescriptlang.org/play/index.html#src=function%20foo(a)%20%7B%20return%20a%20*%202%20%7D%0A%0Afoo(''))

**Comment by aluanhaddad** [comment]
discussion and rational
#1265
related
#15114
#11440

**Comment by mhegazy** [comment]
I have a PR to add a quick fix to infer the type as `number` from such cases in https://github.com/Microsoft/TypeScript/pull/14786.

Inferring from call sites is something we have decided not to pursue for the TS compiler since its inception, and there are multiple reasons. For example, what if the function is not called? What if the use is in another compilation? What if the call is the error, and not the function declaration? What if the calls in your tests, are not exhaustive? 

Moreover, this approach really works for a small snippets of code but does not scale specially with IDE scenarios and you want to know what changing one name mean for the whole compilations. Systems we have seen that take this approach either limit the inference to one file to make it more manageable, or do not care about accuracy.

We believe that type annotations serve better when added to declarations rather than non-local use sites for inference; they help readability and allow tools to correctly check for the user-intended behaviors. Using `noImplicitAny` to mark locations TypeScript *could not* figure out types in other locations helps ensure the experience stays consistent and prescriptive.

**Comment by rauschma** [comment]
I buy the arguments when it comes to inferring the type of a parameter from the call sites of the function.

However, inferring the type of a parameter from the body of a function seems reasonable to me.

An example where I’d expect `a` to get the inferred type `number`:

```js
function foo(a) {
    return bar(a);
}
function bar(x: number) {
}
foo(''); // should be an error
```
