### ISSUE TITLE
Async generator function does not flatten yielded promises

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#15205]
TS 2.3 RC

``` ts
declare const console: any;
{
    (Symbol as any).asyncIterator = Symbol.asyncIterator || "__@@asyncIterator__";

    const gen = async function* () {
        yield Promise.resolve(10)
        yield Promise.resolve(20)
    }

    const main = async () => {
        for await (const y of gen()) {
            console.log(y)
        }
    }

    main();
}
```

This outputs:

```
❯ tsc && node ./target/AsyncIterable.js
Promise { 10 }
Promise { 20 }
```

I expected it to output (promises are flattened):

```
10
20
```

**Comment by masaeedu** [comment]
@OliverJAsh Not super familiar with this, but I think you might want to be `yield await`-ing stuff inside `gen`. Does this work?

```ts
declare const console: any;
{
    (Symbol as any).asyncIterator = Symbol.asyncIterator || "__@@asyncIterator__";

    const gen = async function* () {
        yield await Promise.resolve(10)
        yield await Promise.resolve(20)
    }

    const main = async () => {
        for await (const y of gen()) {
            console.log(y)
        }
    }

    main();
}
```

I think the point of marking a function with async is so that you can write your code inside as if it was synchronous, `await`-ing at any points where you have to interact with asynchronous code. The transpiler machinery wraps all this appropriately so that your function obeys the async-iterator interface and returns promises from `next`.

**Comment by OliverJAsh** [comment]
Ah, interesting.

I can confirm this does fix the issue, although I have a feeling the flattening should work without the `await`. I don't know if it's anything to go by, but this works in Babel.

**Comment by masaeedu** [comment]
@OliverJAsh I did some digging and it looks like there was an issue filed in the proposal repo to make it behave as you are describing: tc39/proposal-async-iteration#8. This means TypeScript isn't following the spec, and should be unwrapping as you expected.
