### ISSUE TITLE
Dump the effective config file

### ISSUE THREAD

**Issue by userpixel** [Microsoft/TypeScript#15213]
# Suggestion

I'm using Typedoc which has very similar options to `tsc` and book keeping and converting these options is tedious and error prone. It would be nice if `tsc` could dump its effective compiler options (considering the default values, `extends` rules, etc.) as a json file. This can be particularly useful when debugging the configurations to see what config is effectively being used for the compilation process.

See: https://github.com/TypeStrong/typedoc/issues/480

**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Expected behavior:**

```bash
tsc --effectiveConfig
# Prints out a json object on STDOUT that is ready to be redirected to a JSON file
{
    "compilerOptions": {
        "module": "commonjs",
        "sourceMap": true,
        "target": "es2016",
        "noEmitOnError": true,
        "alwaysStrict": true,
        "importHelpers": true,
        "lib": [
            "es2015"
        ]
        ...
    }
}
```

**Comment by huafu** [comment]
I was looking for an option on how to output the effective config when I found this. I'm stuck since an hour trying to find out how `extends` actually extends stuff. I could only find in the docs:
> `files`, `include` and `exclude` from the inheriting config file overwrite those from the base config file.
> 
> All relative paths found in the configuration file will be resolved relative to the configuration file they originated in.

But nothing about what happens to deeper arrays such as `types` or `typeRoots`, ... are they merged? how?

This is why I'm totally 👍 for something like Jest has with `jest --showConfig`, but for `tsc`.
