### ISSUE TITLE
Inconsistent handling of extra properties in generic index signatures

### ISSUE THREAD

**Issue by asmundg** [Microsoft/TypeScript#15245]
**TypeScript Version:**  2.3.0

**Code**

```ts
interface I {
    a: number;
    b: number;
}

function f<K extends keyof I>(o: {[key in K]: I[K]}) {
}

const a = {a: 1}
const ac = {a: 1, c: 1}
const abc = {a: 1, b: 1, c: 1}

// A partial object matches
f(a);

// A partial object with an extra property does not match
f(ac); // ERROR: not assignable to parameter of type { a: number; b: number; }

// A complete object with an extra property matches
f(abc);
```

**Expected behavior:**

It seems like f(a), f(ac) and f(abc) should all behave the same way, either all failing or all succeeding. The presence of c being an error should not be dependent on the rest of the parameter object.

**Actual behavior:**

f(ac) causes an error, since it's not assignable to {a: number, b: number}, while f(a) and f(abc) both appear to be assignable to the same.

**Comment by gcnew** [comment]
The problem is that `K extends keyof I` means that `K` may be any subset of the properties of `I`.

The following definitions are all valid, except for the one with featuring literal with excess properties:
```ts
f({});             // K = never
f({ a: 1 });       // K = "a"
f({ b: 1 });       // K = "b"
f({ a: 1, b: 2 }); // K = "a"|"b"

f({ a: 1, b: 2, c: 3 }); // error on "c" because when passing a literal,
                         // "c" is known to never be used, hence an error

const abc = { a: 1, b: 2, c: 3 };
f(abc);  // K = "a"|"b"
         // OK, because this object can be used in other contexts where "c" makes sense
```

TypeScript uses structural typing, thats why `f(abc)` is valid. For more information see [Type Compatibility](https://basarat.gitbooks.io/typescript/docs/types/type-compatibility.html).

**Comment by gcnew** [comment]
To require all keys (not a subset of them) use

```ts
function f(o: {[key in keyof I]: I[key]}) {
}

f(a);   // Error
f(ac);  // Error
f(abc); // OK
```

**Comment by ahejlsberg** [comment]
This is working as intended. In the call `f(abc)` inference initially infers the type `'a' | 'b' | 'c'` for `K`. That fails to meet the constraint `keyof I` (which is equivalent to `'a' | 'b'`) and therefore inference simply picks the constraint `'a' | 'b'` as the type inferred for `K`. Once `'a' | 'b'` is substituted for `K` you end up with a signature where `o` has type `{ a: number, b: number }`, and since `abc` is assignable to that type the call successfully checks.

**Comment by asmundg** [comment]
Ok, thanks for the explanation!
