### ISSUE TITLE
The return type of an async function or method must be the global Promise<T> type.

### ISSUE THREAD

**Issue by pierre-H** [Microsoft/TypeScript#15292]
**TypeScript Version:**  2.2.2

**Code**

```ts
async getUsername(): string{
    try{
        // I use AsyncStorage from React Native and ReactXP Storage
        let value = await AsyncStorage.getItem('username');
        return value;
    }
    catch(e){
        console.log('caught error', e);
        // Handle exceptions
    }

}

```

**Expected behavior:**
getCache return the item
**Actual behavior:**
This error : 
> The return type of an async function or method must be the global Promise<T> type.

**Comment by blakeembrey** [comment]
This is the correct behaviour, the return type of an async function is a promise. Use `Promise<string>` instead of `string` to indicate that.

**Comment by pierre-H** [comment]
@blakeembrey 
Thank you for your answer but if then, I can't create a function which return the username and wait for it execution.

**Comment by RyanCavanaugh** [comment]
You can. Try it! :wink:

**Comment by pierre-H** [comment]
@RyanCavanaugh I did and TypeScript isn't happy because I want that my function return a string but TypeScript wants Promise<string>

**Comment by blakeembrey** [comment]
@pierre-H I'd recommend checking out some JavaScript documentation to better understand how `async` and promises work. Here's a good place to start: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function. You can't _make_ your function return a string unless all your code is synchronous, in which case you don't need an async function anymore.

**Comment by fatcerberus** [comment]
@pierre-H You don't actually have to change any of the code *in* the function, just change its return type in the declaration to `Promise<string>`.  It's like how async functions in .NET need be declared as returning a `Task<T>` but the actual code is written as though it returns `T` directly.  The `async` and `await` keywords are just sugar for automatic promise wrapping/unwrapping.

**Comment by rajkanase** [comment]
what is the alternative for async await

**Comment by windhandel** [comment]
@RyanCavanaugh, nicely Socractic of you.  It's a gift, when understood and well received.

**Comment by bluelovers** [comment]
any options for disable this warning?

**Comment by marcj** [comment]
To make things clear for anyone looking simply for a solution and are not satisfied by the overly didactic answers:

To make your example workable, change the return type to `Promise<string>`.

```typescript

async getUsername(): Promise<string> {
        let value = await AsyncStorage.getItem('username');
        console.log("done", value); //for explaining the following
        return value;
}
```

However, when calling `getUsername()` it won't block the execution. So

```typescript
console.log('1');
console.log(getUsername());
console.log('2');
```

returns 

```
> "1"
> [object Promise]
> "2"
> "done" "Donald"
```

As you can see, `getUsername()` returns now a Promise - always, even tho you returned a string. Javascript will automatically convert it into a Promise, if a non-promise value is returned. Also "2" is printed, although `getUsername()` might not be executed yet completely, as in the nature of asynchronous javascript.

To make the call "blocking", you need to use `await` again.


```typescript
console.log('1');
console.log(await getUsername());
console.log('2');
```

The result is the same as if you'd use the promise directly via `getUsername().then(callback)`, meaning the execution tree down to the call of getUsername() is asynchronous and you need to call either on every parent method execution `await` or work with the Promise directly.

The implication is: **There is no way** to make asynchronous code synchronous with `await`. Every method calling your `async getUsername` directly or indirectly becomes automatically async as well.

I mean, I also come from a non-asynchronous programming language and back in the days developed in Javascript like there're no asynchronous operations. However, since the language goes heavily in that direction we need to accept that asynchronous behaviour is here and we need to follow its principles and should not work around that by trying to make code blocking/synchronous again.


> what is the alternative for async await 

There are 2.

1. Work with the promise directly, like

```typescript
getUsername(): Promise<string> {
  return new Promise((resolve, reject) => {
    AsyncStorage.getItem('username').then((username) => {
      resolve(username);
    })
  });
}
```

However that makes the function still asynchronous.

2. Make all calls inside `getUsername()` synchronous.


```typescript
getUsername(): string {
  return syncStorage.getItem('username');
}
```

However, that requires that you have a implementation of `syncStorage` that is truly synchronous.

> any options for disable this warning?

Now, as this would totally makes no sense at all.

**Comment by Matthijs-Wessels** [comment]
Why doesn't putting `async` in front of the function implicitly convert `string` to `Promise<string>`?

This is what I would expect.

**Comment by fazelmk** [comment]
I still don't get why in hell it's a promise.  This function should be synchronous 
```
async getUsername(): string{
    try{
        // I use AsyncStorage from React Native and ReactXP Storage
        let value = await AsyncStorage.getItem('username');
        return value;
    }
    catch(e){
        console.log('caught error', e);
        // Handle exceptions
    }

}
```
The only asynchronous method in it should be blocking the execution because of the await.
This is just stupid. If I want to make an async func sync I must put async/await in all function till the top of calling chain.

it's just STUPID. there is no point in using that shit besides not making promises inside promises.

**Comment by fatcerberus** [comment]
`await` does *not* make a function synchronous.  From the point of view of the topmost (non-awaiting) caller it behaves like a return and the function resumes “in the background”, controlled by the event loop.

**Comment by sbmthakur** [comment]
From MDN:

> The async function declaration defines an asynchronous function, which returns an AsyncFunction object. An asynchronous function is a function which operates asynchronously via the event loop, using an **implicit** Promise to return its result. But the syntax and structure of your code using async functions is much more like using standard synchronous functions.

Notice the word *implicit*? If you don't return a promise, the value you return will automatically be wrapped in a promise. The above-mentioned explanation given by @marcj is pretty much perfect. You may go through this [Stack Overflow question](https://stackoverflow.com/questions/35302431/async-await-implicitly-returns-promise) if you are still scratching your head.

**Comment by AICDEV** [comment]
We all agree that Async/Await allows us to write asynchronous javascript that looks synchronous but not blocking the loop.And you want async code =) 

`async function make(): Promise<string> {
    const value = await stuff();
    return value;
}

function stuff(): Promise<string> {
    return new Promise((resolve, reject) => {
        resolve("test");
    });
}

console.log(make());

make().then((data) => {
    console.log(data);
});
`

Output:
`Promise { <pending> }
test`
