### ISSUE TITLE
Assigning string values to string literal type class properties raises type error

### ISSUE THREAD

**Issue by tills13** [Microsoft/TypeScript#15311]
**TypeScript Version:**  2.2.2

**Code**

```ts
interface SomeInterface {
    mProperty: "property" | "anotherProperty";
}

class Test implements SomeInterface {
    mProperty = "property";
}
```

I initially ran into this issue when writing something in React:

```ts
interface ComponentState {
    selectedOption: "option1" | "option2" | "option3";
}

class SomeComponent extends React.Component<any, ComponentState> {
    state = {
        selectedOption: "option1"
    };
}
```
both the above raise the same error.

**Expected behavior:**
I'm not actually sure if this is intended behaviour or not, but, in my mind, TS should infer that string literal "property" can be either type `string` or type string literal `"property"`.

**Actual behavior:**
```
Types of property 'property' are incompatible.
Type 'string' is not assignable to type '"property" | "anotherProperty"'.
```

**Comment by DanielRosenwasser** [comment]
#3667 and #1373 seem like the root cause. You basically want the base property declarations to "bless" the derived properties with a contextual type, *or*, you want to use the base type declaration here. However, what happens is that the derived declarations are inferred independent of the base declarations.

The problem is that when you do this you have a non-trivial amount of code that breaks because

1. If you take the base type declaration as it is, then you make it harder for derived classes to specialize fields to a more specific type.
2. If you use contextual typing, then the type of `mProperty` is inferred  to be `"property"` instead of `"property" | "anotherProperty"` , which may be too limited.

**Comment by tills13** [comment]
For the React example specifically, I discovered that directly typing the property (`state`, in this case) solves the issue:

```
interface ComponentState {
    selectedOption: "option1" | "option2" | "option3";
}

class SomeComponent extends React.Component<any, ComponentState> {
    state: ComponentState = {
        selectedOption: "option1"
    };
}
```

**Comment by wilg** [comment]
I came across the same problem with this repro:

```ts
export type Kinds = "a" | "b" | "c";

abstract class Classy {
  abstract hotProperty: Kinds[] = [];
}

class Instance extends Classy {
  hotProperty = ["a"];
}

let inst = new Instance();
console.log(inst.hotProperty);
```

It's a worse repro of this one: https://github.com/Microsoft/TypeScript/pull/6118#issuecomment-212579939

Is the problem with #6118 totally intractable? I mostly just want to avoid requiring my subclasses to declare a complex type signature. I'm surprised there's ever a use case for wanting a subclass to change the type of a property.

Out of my league here, but if the problem is really what's described in this other comment https://github.com/Microsoft/TypeScript/pull/6118#issuecomment-216595207 couldn't something like [Objective-C's `instancetype`](http://nshipster.com/instancetype/) be used to solve _that_ problem while allowing proper inference in my case?

Or perhaps there's a clever way to just fix the string literal case without going whole-hog?

**Comment by RyanCavanaugh** [comment]
@wilg the problem is mainly that it's a breaking change to do anything else at this point (mostly due to people having derived class with overriding properties of a more-specific type). In general we agree that changing the type of a property in a subclass should be something you need to "opt in to".

**Comment by wilg** [comment]
Is there the possibility of some sort of compiler flag that could be looped into "strict" mode or whatnot?

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
