### ISSUE TITLE
Implicit cast from any-object

### ISSUE THREAD

**Issue by tonn** [Microsoft/TypeScript#15335]
**TypeScript Version:**  2.2.2 / test also in www.typescriptlang.org/play

**Code**

```ts
// There is code in 3rd party js-source:
//
// ThirdPartyType = function () {};
// ThirdPartyType.prototype.method1 = function() {};
// function ThirdPartyGlobalFunction(thirdPartyTypeVariable) { 
//    thirdPartyTypeVariable.method1(); 
// }
//

declare class ThirdPartyType { }

declare function ThirdPartyGlobalFunction(p: ThirdPartyType);

class MyType extends ThirdPartyType { 
    field1: number;
}

function foo(bar: MyType) { 
    ThirdPartyGlobalFunction(bar); // There will be error because bar is not ThirdPartyType and do not have "method1"
}

function fooOverride(a: number) { 
    foo({ field1: a });
}
```

**Expected behavior:**
**Actual behavior:**

function fooOverride compiles into:

```ts
function fooOverride(a) {
    foo({ field1: a }); // There is should be implicit cast to MyType
}
```

**Comment by HerringtonDarkholme** [comment]
https://github.com/Microsoft/TypeScript/wiki/FAQ#what-is-structural-typing

**Comment by DanielRosenwasser** [comment]
I'm not entirely sure what you were expecting here, but the actual code you wrote is passing an object literal to `foo`. That works because as far as TypeScript is concerned, it's looking for something with the same shape as a `MyType`, which is anything that has a `field1` property of type `number`. For more details, look at @HerringtonDarkholme's link.

If you were expecting TypeScript would instantiate a `MyType` for you and initialize `field1` with `a`, that's actually not something that TypeScript does. Specifically, TypeScript avoids type-driven emit. You may need to familiarize yourself with JavaScript classes to get a better handle on this as well.

**Comment by tonn** [comment]
I write more simple example
```ts
class MyType { 
    field1: number = 0;
}

function foo(bar: MyType) { 
    console.dir(bar);
}

foo(new MyType());
foo({ field1: 1 });
```
Console output: https://i.imgur.com/E1t3kGv.png

I understand about "structural typing" in TypeScript. But what is the point talk that "new MyType()" and "{ field1: 1}" is the same type in TypeScript if after compilation in JS second object lost relation to MyType?
It's "succesfull compilation"-trap.
