### ISSUE TITLE
Regression on Promise Type Checking in Latest Insiders

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#15352]
From: https://github.com/Microsoft/vscode/issues/25215

**TypeScript Version:**  2.3.1-insiders0420

**Code**

Using `es2015.lib.d.ts`:

```ts
function foo(x: Promise<boolean>) {}

foo(new Promise(() => true))
```

**Expected behavior:**
This compiles fine with TS 2.2.2 and with the older insiders 2.3.1 release.

**Actual behavior:**
With the current insiders, we get: `message: 'Argument of type 'Promise<{}>' is not assignable to parameter of type 'Promise<boolean>'.
  Type '{}' is not assignable to type 'boolean'.'`

This is causing upwards of 230 compiler errors in the vscode codebase

Possible related to #15104

**Comment by mhegazy** [comment]
This is an [intentional change](https://github.com/Microsoft/TypeScript/pull/15104) to tighten the promise compatibility checking. in your call back, inference fails, and the result is `{}`; previously it was allowed to assign `Promise<{}>` to a `Promise<boolean>`, which is unsafe.

See https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#covariance-in-callback-parameters for more details

**Comment by mjbvz** [comment]
Thanks. This change seems to make sense even though it will be a little painful to update our codebase for it. It was not entirely clear to me why the code was compiling in ts 2.2.2 case when I looked at the types and thought more about the problem. 

// cc @bpasero
