### ISSUE TITLE
Enum needs rename in inner scope under `--target es6`

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#15401]
**TypeScript Version:**  nightly (2.3.0-dev.20170426)

**Code**

```ts
const E = 2.718;

function f(): number {
    {
        enum E {}
    }
    return E;
}

console.log(f());
```

**Expected behavior:**

Just do what we do with `--target es5`:

```js
var E = 2.718;
function f() {
    {
        var E_1;
        (function (E) {
        })(E_1 || (E_1 = {}));
    }
    return E;
}
console.log(f());
```

**Actual behavior:**

Under `--target es6`:

```js
const E = 2.718;
function f() {
    {
        var E;
        (function (E) {
        })(E || (E = {}));
    }
    return E;
}
console.log(f());
```

At the `return E;` `E` has been overwritten and doesn't refer to the outer `E` any more.
Another option would be to transpile to a `const`, but watch out for multiple declarations of the same enum.

**Comment by rbuckton** [comment]
We have two directions to go with this:
1. Enum and Const Enum declarations are hoisted (similar to var)
    * Current runtime behavior
    * Conflicts with design-time behavior
2. Enum and Const Enum declarations are block scoped
    * Changes runtime behavior
    * Aligns with design-time behavior

For `--target ES6` we can fix this by using `let` instead of `var` for anything other than the top-level of a global script (e.g. not a module).

For `--target ES5` we would have to make changes to treat it as a block-scoped declaration.

**Comment by mhegazy** [comment]
+1 for treating them as block scoped. I do not think this breaks any users as this is how we treat them for lookup purposes.
