### ISSUE TITLE
Order of union in inferred type in declaration file is unintuitive.

### ISSUE THREAD

**Issue by Chacha-26** [Microsoft/TypeScript#15418]
**TypeScript Version:**  2.0.2 and above including nightly (2.4.0-dev.20170427)

**Code**
Generate a declaration file for the following:
```ts
export let AE: 'A' | 'E';
export let DC: 'D' | 'C';
export let ABCDEF: 'A' | 'B' | 'C' | 'D' | 'E' | 'F';
export let FB: 'F' | 'B';
export let ABCDEF2 = ABCDEF;
```

**Expected behavior:**
The types of `ABCDEF` and `ABCDEF2` should be in the same order:
```ts
export declare let AE: 'A' | 'E';
export declare let DC: 'D' | 'C';
export declare let ABCDEF: 'A' | 'B' | 'C' | 'D' | 'E' | 'F';
export declare let FB: 'F' | 'B';
export declare let ABCDEF2: "A" | "B" | "C" | "D" | "E" | "F";
```
This was the case in version 2.0.0 and prior.

**Actual behavior:**
The order of types depends on the order in which they are first seen.
```ts
export declare let AE: 'A' | 'E';
export declare let DC: 'D' | 'C';
export declare let ABCDEF: 'A' | 'B' | 'C' | 'D' | 'E' | 'F';
export declare let FB: 'F' | 'B';
export declare let ABCDEF2: "A" | "E" | "D" | "C" | "B" | "F";
```
This happens for all types, not just string literal types.

-----
This is especially unintuitive with lowercase letters, since it seems as though some letters are already used:
**Code:**
```ts
export let LC: 'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z';
export let LC2 = LC;
```
**Expected:**
```ts
export declare let LC: 'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z';
export declare let LC2: "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z";
```
**Actual:**
```ts
export declare let LC: 'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z';
export declare let LC2: "a" | "p" | "q" | "g" | "b" | "i" | "s" | "u" | "c" | "d" | "e" | "f" | "h" | "j" | "k" | "l" | "m" | "n" | "o" | "r" | "t" | "v" | "w" | "x" | "y" | "z";
```

**Comment by RyanCavanaugh** [comment]
Internally unions are stored as a sorted list of types, where the type ID is the sort key (and type IDs are issued sequentially). This allows for fast comparisons and binary searches by identity.

When we write the .d.ts file, if there's an existing type annotation we can just emit as-is, we do (this is the `LC` case). But if we have to fetch the type (the `LC2` case), then we have to create a new string representation of the type. Since order of the constituents of unions doesn't ever affect their type, we just print them in the same order as the internal representation.

Without any observable bad type behavior I don't see a good reason to mess with this code

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
