### ISSUE TITLE
Consider allowing the reference types="dependency" directive to be resolved via --paths

### ISSUE THREAD

**Issue by aluanhaddad** [Microsoft/TypeScript#15559]
Currently the triple slash directive
```ts
/// <reference types="dependency" />
```
only resolves `"dependency"` when there exists a physical directory that has the exact name of the referenced package.

This approach breaks down when using paths.

Consider
**tsconfig.json**
```json
{
  "compilerOptions": {
    "baseUrl" : ".",
    "paths" : {
      "jquery": [
        "custom-typings/jquery-3.0.1/index"
      ],
      "bootstrap": [
        "node_modules/@types/bootstrap/index"
      ]
    }
  }
}
```

If **node_modules/@types/bootstrap/index.d.ts** looks like
```ts
/// <reference types="jquery" />
```
Then the reference is not resolved.

It would be great if the reference were resolved in the same manner as non-relative imports such as 
```ts
import $ from "jquery";
```

**Comment by mhegazy** [comment]
`/// <references types=.. />` are not imports. they are global references. the assumption is these packages exist in the global scope, e.g. `node`. At any given time, there can be at most one version of these package. The lookup process here starts from your project root to allow you to override it with other declaration.

This is different from module imports. Modules have their own scope, and you can safely include multiple versions of the same module in your compilation.

So if this is a truly global, then the fix is to is to set your `typesRoot` to point to your `custom-typings` folder in addition to `node_modules\@types`. If however it is not, which is the case with `jquery`, then the fix is to rewrite `jqurey` declaration to be a module and using the UMD pattern, and replace the `/// <reference types="jquery" />` in its dependencies with `import ... from "jquery"`. 

We have tried to update as many of the DT packages as we could, but there are a lot of them that needs updating still. but the fix would be on the DT side and not the compiler.

**Comment by aluanhaddad** [comment]
@mhegazy thank you for the thorough explanation. I realize that they are not modules but I thought `paths` might be useful in resolving varying folder names, but now that you explain it it seems silly to alias them since there can be only one. Also since, as you point out, they are not modules, then it would be confusing or downright erroneous to use `paths`.
