### ISSUE TITLE
Proposal: Annotations (alignment with Traceur/AtScript)

### ISSUE THREAD

**Issue by JeroMiya** [Microsoft/TypeScript#1557]
### Summary
* Implement annotations in TypeScript.
* Align with Traceur and AtScript on syntax and ES5 representation.
* Implement feature similarly to modules, with the following settings for output representation:
 - -annotations=none (default) - Annotations not supported by default. Produce compiler errors when used.
 - -annotations=atscript - Annotations encoded in the style of traceur/atscript (this proposal)
 - (future) -annotations=ecmascript - Hypothetically, if ES.Vnext were to adopt annotations, this would represent them using the approved ES7 annotation syntax, whatever that would be, as a bridge while TypeScript aligns with the official syntax (similar to how TS modules will transition).
* In the long term, align with ECMAScript, if an annotation proposal is accepted.

### Prior Art/Reference
* Traceur and by extension AtScript (this proposal)
 - https://docs.google.com/document/d/11YUzC-1d0V1-Q3V0fQ7KSit97HnZoKVygDxpWzEYW0U/mobilebasic?viewopt=127
* Ember decorators
 - Uses "- decoratorName(decoratorArgs, ...) decoratorTarget"
 - Decorators can mutate the target class/field/argument(?). This proposal involves only inert metadata.
* tc-39 April 10 2014 Meeting Notes
 - https://github.com/rwaldron/tc39-notes/blob/master/es6/2014-04/apr-10.md#decorators-for-es7

### Motivation
* This proposal improves alignment between TypeScript and AtScript (and Traceur), improving interoperability between TypeScript code and code using these features of those compilers.
* Annotations are useful in certain scenarios like dependency injection, domain driven design, decorator pattern, and more.

### Differences from AtScript/Traceur
* Run-time type metadata, runtime type checking, etc... is beyond the scope of this proposal.

### Syntax and ES6 Representation

I am proposing the AtScript/Traceur syntax and ES6 representations, necessarily verbatim (minus the type annotations). An annotation can be applied to a function, a class, the constructor of a class, a field of a class, or a function argument:

####  function:

```javascript
@MyAnnotation('argument')
function func() {}

// ES6 representation
function func() {}
func.annotate = [ new MyAnnotation('argument')];
```

#### A class:
* Same representation as a function, of course.

```javascript
@MyAnnotation('argument')
class MyClass {}

// ES6 representation
class MyClass {}
MyClass.annotate = [ new MyAnnotation('argument') ];
```
#### A constructor of a class:
* Note: exactly the same as annotations on the class. Constructors are listed last in the list in the ES6 representation, after class annotations.

```javascript
@MyClassAnnotation('argument')
class MyClass {
   @MyConstructorAnnotation('argument')
   constructor() {}
}

// ES6 representation
class MyClass {
  constructor() {}
}
MyClass.annotate = [ new MyClassAnnotation('argument'), new MyConstructorAnnotation('argument') ];
```

#### A field of a class:
* Note: in AtScript/Traceur, the objects to the right of the field name also have an 'is' field at the same level as the 'annotate' field. I have omitted the 'is' fields below (RTTI is out-of-scope for this proposal).
```javascript
class MyClass<T> {
  @MyFieldAnnotation('argument')
  field: T = null;
}

// ES6 representation:
class MyClass {
  field = null;
}
MyClass.properties = {
  'field': { annotate: [ new MyFieldAnnotation('argument') ] }
};
```

#### Arguments to a function:
* Including arguments to constructors.
* Note: In Traceur/AtScript, objects in the parameters array also have an 'is' field which is a reference to the type of the argument. That is omitted from the following examples (RTTI is out-of-scope for this proposal).

```javascript
function func<T>(@MyFuncArgumentAnnotation('argument') arg: T): void {}

class MyClass<T> {
  constructor(@MyConstructorArgumentAnnotation('argument') arg: T) {}
}

// ES6 representation
function func(arg) {}
func.parameters = [ { annotate: [ new MyFuncArgumentAnnotation('argument') ] }];

class MyClass {
  constructor(arg) {}
}
MyClass.parameters = [ { annotate: [ new MyConstructorArgumentAnnotation('argument') ] }];
```

#### Extensions to lib.d.ts to support typing of annotations
* e.g. adding 'properties', 'annotate', and 'parameters' field typings to Function interface.
* Can be done by a third party/DT/etc... without changes to the compiler.

**Comment by EisenbergEffect** [comment]
It should be noted that there is broad experience with annotations. This feature is based on Java annotations and C# attributes and the use cases are similar. Additionally, the Angular and Aurelia teams have been using them successfully for at least a year now and the usage patterns are pretty well known. Aurelia has a metadata abstraction library that handles location of annotations and manipulation including inheritance chains.

I don't see composition as being essential. It's not something people did on other platforms and the Angular and Aurelia teams haven't needed that. Adding and reusing massive amounts of annotations doesn't seem like something common. I think the spread operator can handle this nicely in the very few number of cases where it comes up.

I see decorators as a fundamentally different concept. Annotations are about having a standard way to associate metadata with functions and class members, that's pretty much it.

> Note: I'm not sure if AtScript/Tracuer is up to date with the current spec they have published. If you try it out on the online REPL it generates the older syntax. Probably should check with them to see what the status of that is and why it doesn't match their proposal.

**Comment by spion** [comment]
@EisenbergEffect As long as a single library is the consumer, I agree. FWIW the example I linked contains the following code:

```java
@XmlElementWrapper(name="orders")
@XmlJavaTypeAdapter(OrderJaxbAdapter.class)
@XmlElements({
   @XmlElement(name="order_2",type=Order2.class),
   @XmlElement(name="old_order",type=OldOrder.class)
})
@JsonIgnore
@JsonProperty
@NotNull
@ManyToMany
@Fetch(FetchMode.SUBSELECT)
@JoinTable(
    name = "customer_order",
    joinColumns = {
        @JoinColumn(name = "customer_id", referencedColumnName = "id")
    },
    inverseJoinColumns = {
        @JoinColumn(name = "order_id", referencedColumnName = "id")
    }
)
private List orders;
```

and composition is important because it would be great if it was possible to reduce it to something at the same level of abstraction e.g.

```ts
@SerializableTo(name="orders");
@BelongsTo('customer')
private List orders;
```

**Comment by EisenbergEffect** [comment]
@spion I agree that we don't want to see that. Personally, I would choose to solve this issue at the framework level by making something like `@SerializableTo` internally aggregate the other annotations. Something like @JeroMiya shows would also be interesting, especially since Mixins would be a nice feature in their own right.

That said, I would be willing to concede to the decorator approach, especially if that looked like the direction that TC39 was going to move in. Since I'm still interested in metadata mostly, it would be pretty easy for me to author a set of decorators that simply put data in a location that my framework knows to look. I could publish that library as a simple ES6 module and then developers working with languages that support it could simply import the library and use them. The more I think about it....I'm liking this decorator approach. It would provide a lot more flexibility in the end.

**Comment by EisenbergEffect** [comment]
@spion How would the decorator proposal handle constructor parameters and class fields? It seems that it breaks down in those scenarios... (I don't personally have an interest in that...mostly methods and accessors, but just curious.)

**Comment by domenic** [comment]
It's important to note that annotations have never been proposed to TC39 and should not be considered in any way standards-track. In contrast, decorators have been, and are accepted as a proposal that is now dependent on their champion to move forward.

**Comment by wycats** [comment]
> That said, I would be willing to concede to the decorator approach, especially if that looked like the direction that TC39 was going to move in. Since I'm still interested in metadata mostly, it would be pretty easy for me to author a set of decorators that simply put data in a location that my framework knows to look.

Yes, exactly. Decorators provide a strict superset of the capabilities of metadata annotations.

**Comment by wycats** [comment]
> How would the decorator proposal handle constructor parameters and class fields? It seems that it breaks down in those scenarios...

Can you say more about what specific use-case you have in mind? It sounds like class-level annotations would do the trick?

Can you show me some ES6 boilerplate you would want to sugar up using decorators?

**Comment by Arnavion** [comment]
1. Should annotations be allowed on interfaces?

1. If (1) is yes, are they applied to a class that implements the interface? Are annotations on a member of the interface applied to the corresponding member of the class that implements the interface?

1. If (2) is yes, What happens if there are two interfaces with different annotations, or two interfaces with the same member but different annotations on that member? Specifically, which order are the annotations applied in? (Order of discovery / undefined)

1. If (2) is yes, a class instance is assignable to an interface even if it doesn't explicitly implement it, because of structural typing. However the actual class emit won't have this annotation. An object literal with the same members is also assignable for the same reason. Will this be a problem? One should not expect to find interface annotations on any object that satisfies the interface, but the answer depends on the expectations of people who annotated the interface.

**Comment by EisenbergEffect** [comment]
@wycats Actually, I think you are correct. Class-level decorators could easily add constructor parameter metadata and property metadata to a known location like anything else.

Are you championing this feature for ES7? What is the status of that work? Do you need/want any help with that?

**Comment by JeroMiya** [comment]
It was not my intent to allow annotations on interfaces. For this use case, I envisioned inheritance and perhaps mixins would provide the necessary attribute inheritance. Attributes would be aggregated starting with the base class and traveling down the inheritance chain. Since there isn't yet a formal mixin proposal, I'd have to guess that they'd roughly follow Scala traits in the algorithm for 'stacking' the mixins linearly. In that case, the final order of the aggregated attributes would be determined from the stack order (highest base to lowest).

Also, attributes would not modify the structural type of the class or function. The 'properties', 'annotate', and 'parameters' fields would be added to the base Function interface as optional fields. Annotations are applied to Functions and modify those specific fields. They don't have any effect on instances of the class or the return value of the function, though you can read the attributes through the instance object's constructor field.

Finally, just wanted to point out that it might be somewhat awkward to replicate attribute inheritance using decorators, given that the best place to do that would be within __extends. Decorator functions would need access to _super at the very least. Though, perhaps a single decorator, say 'Annotate' could replicate annotations:

```typescript
// using decorator syntax from TC-39 discussion
class A {
 + annotate([new AnnotationA(), new AnnotationB()])
}

class B extends A {
 + annotate([new AnnotationC(), new AnnotationD()]) // how does annotate know about A?
}
```

It might work, I suppose, but it seems a little awkward for an important use case. Is there any reason why we couldn't adopt both annotations and decorators (using for example @ for annotations and - or + for decorators)? Annotations could be type-aware syntax sugar for an 'annotate' decorator.

**Comment by EisenbergEffect** [comment]
Why does inheritance of annotations need to be "implemented"? This seems like a library concern. For example, it's common that the consumer of the metadata will want to decide whether or not to search the base class or not. Sometimes you do, sometimes you don't.

**Comment by wycats** [comment]
@EisenbergEffect Yes I am championing this feature for ES7 and would **love** help. Email me? (wycats@gmail.com)

**Comment by JeroMiya** [comment]
@EisenbergEffect Good point. If we're talking about annotations and not decorators, I would think it's the class itself that should decide how it inherits annotations, with it inheriting by default (it seems to me the most sensible default, or at least the least likely to surprise). In C#, the inheritance is specified at the annotation level, as I think you are proposing, but in this proposal there are no restrictions or specifications on what an annotation *is* - any constructor function works, so there's no metadata on the annotation for specifying whether it should be inherited or not. 

If we're talking about decorators, then of course these are only 'executed' on the base class, and any modifications are inherited by sub-classes in the normal way, though as I said earlier it would be difficult to impossible to represent decorator type modifications in the type system automatically.

Maybe we can re-use the 'declare' keyword in the context of member variables (in classes and interfaces) to declare that some field exists without actually implementing it. Then we could add type information for modifications made by the decorator without using placeholders that presumably would be overwritten by the decorator:

```typescript
interface IDeclaredA {
  // currently a syntax error, unexpected token
  declare var a: string; 
}
class A implements IAbstractA {
  // declared members are not enforced in the implementation and no
  // code is generated for them
  + addAFieldDecorator('a', 'string', 'initialValue') // this decorator adds a field to the prototype
}
var x = new A();
alert(x.a);
```

**Comment by wycats** [comment]
> If we're talking about decorators, then of course these are only 'executed' on the base class, and any modifications are inherited by sub-classes in the normal way, though as I said earlier it would be difficult to impossible to represent decorator type modifications in the type system automatically

As I said to the TypeScript team, I think the exact opposite of this is true.

1. In practice, some people will use either kind of annotation ("data-only" or "decorators") to mutate the class and its properties. With data-only decorators, a dependency injection system or simple functions can be used to do the modifications.
2. When using data-only annotations, the nature of the modification is completely opaque to the type system. From the perspective of the type system, no changes have been made (only data has been added) so any mutation would be invisible.
3. When using decorator annotations (which take in a property descriptor and return a new property descriptor), it is at least POSSIBLE to describe the transformation in terms of a type transformation.
4. In short, because data-only annotations lie about their intentions ("don't worry... I'm just adding data ;) ;)"), they at first **appear** to be nicer for type systems, but actually hide mutations in JavaScript code that would be incredibly difficult to type.

For example, consider a hypothetical `readonly` annotation:

```js
function nonconfigurable(prototype, name, descriptor) {
  descriptor.configurable = false;
  return descriptor;
}
```

And this usage:

```js
class Article {
  @nonconfigurable
  length() { /* implementation */ }
}
```

In this case, the `@nonconfigurable` annotation is indeed changing the nature of the `length` method, but it's doing so in a very specific, very structured way.

You could imagine TypeScript providing a way for the `nonconfigurable` annotation to express this change (and the type system would propagate those changes through a stack of annotations). It's much harder to imagine TypeScript being able to handle "data-only" annotations that were actually being used by an external system to execute those same changes.

And just to be clear, whichever kind of annotation ends up landing, Ember intends to use the mechanism to do precisely these kinds of mutations. The only question is whether a library that does so has a prayer of eventually being compatible with TypeScript or not. I want the answer to be yes.

**Comment by EisenbergEffect** [comment]
I tend to agree with @wycats on this. One of the big uses for annotations is to provide metadata to a runtime system that ends up doing some sort of metaprogramming based on that data. But the alterations being made to the annotated objects are in no way discoverable by the TypeScript compiler. However, by using decorators, the metaprogramming can be moved out of the framework proper and into the decorator itself...and defined in such a way that TypeScript can understand the transformation. For non-metaprogramming use cases, the decorator can still add meta-data to a known location on the object.  This could also be declared as part of the TS decorator definition also.

**Comment by JeroMiya** [comment]
We are assuming that there is a reliable way to model type transformations done by arbitrary decorators in the first place. Consider that some decorators may be implemented in a stateful way, or take some framework-specific config object and make dynamic modifications based on that object. I don't have high confidence that any but the simplest transformations could be modeled.

Even assuming it were possible to model complex transformations based on dynamic and possibly stateful data - why wouldn't we also be able to model type transformations from arbitrary framework functions acting on annotated types? If you can handle type transformations based on a config object, for example, you can handle type transformations based off of annotations.

Finally, many (I might hazard a guess and say "most") use cases for annotations do not make any type transformations at all. For example, in the dependency injection use case, the annotations are used to inject values into constructor arguments or to set field values after object construction, leaving the annotated type unchanged. For the serialization or database mapping use case, they affect how instances of the type are serialized, or how fields from the type are mapped to a database, etc... In an MVC framework they could be used for specifying routing, or how to map HTTP headers or URI parameters to action methods in a controller. If you take a look at annotations in other languages like C# or Java, it is very rare that these annotations actually cause a change in the types they are applied to. Even when some IL rewriting happens as a post build step, the type is usually left unchanged - e.g. injecting some code into a method or property but leaving its signature alone.

**Comment by EisenbergEffect** [comment]
@JeroMiya You are looking at this from the perspective of C#. Those are valid use cases, but you need to consider how similar techniques were used elsewhere, like in Ruby for example. In this case similar ideas are being used to do metaprogramming which absolutely changed the definition of the object and I would argue is a key aspect of the success of the language and of frameworks like RoR.

I see a couple of important points that need to be considered for the language design:

1. Decorators can accomplish everything that annotations can, but annotations cannot accomplish everything that decorators can (at least not without framework-specific runtime support). So, implementing decorators provides you with a more general purpose solution capable of handling much more and lessens the possibility of needing to add additional language features for new scenarios down the road.
2. Decorators will likely become part of JavaScript rather than Annotations, which means that TypeScript, in order to remain relevant, will need to have a solution for that eventually.
3. Decorators are more-reusable in a cross-library or cross-framework way. For example, I can write a decorator that generates all the Object.observe notifier api boilerplate for computed properties and that will be reusable across any project. But, if I had to do this with simply data annotations, I would then need an additional runtime  capable  of instantiating all the objects, reading the metadata and configuring the objects.

Yes, decorators is a more involved language feature to design, especially for TypeScript. But, it's probably better in the long run.

**Comment by JeroMiya** [comment]
As a clarification, I would say that I am not arguing against decorators, even if I have reservations about them. I am instead proposing annotations independently. You can consider them to be sugaring for a very common family of decorator use cases, a way to nudge frameworks towards a common standard for those use cases, and as a way to align with traceur/atscript. You could conceivably have both in the language, so long as you used a different sigil for each (@ for annotations, -/+ for decorators, for example).

Also, while you can implement annotations using decorators, the result is not as clean. For example, you can implement them one of two ways that I can think of: via an 'annotate' decorator that takes an annotation list as input:

```typescript
// with annotations:
@Annotation1('arguments')
class MyClass {}

// with an +annotate decorator:
class MyClass {
 + annotate([new Annotation1('arguments')])
}
```
The drawback to this approach is that the syntax is painful. At this point, you might as well just use a static:

```typescript
class MyClass {
  static annotate = [new Annotation1('arguments')]);
}
```

Alternatively, each decorator could add the annotate field internally, so you could get roughly back to the same clean declarative syntax:

```typescript
class MyClass {
  + annotation1('arguments')
}
```

The drawback to this approach is that each decorator would need boilerplate code for adding itself to the annotate array of the constructor function, if it doesn't exist, else creating it. That is somewhat brittle, as any decorator which forgets to check if the array already exists would end up overwriting the existing one.

Using decorators to implement member and parameter annotations, however, is troublesome:

```typescript
// with annotations
class MyClass {
    constructor(@ArgumentAnnotation() arg: any) {}
    
    @FieldAnnotation1()
    @FieldAnnotation2()
    - fieldDecorator()
    var field1: string;
}

// with just decorators
class MyClass {
    // can't use a member decorator to annotate a member,
    // because we're modifying the 'properties' field of MyClass, not the member itself
    +annotateMember('field1', [new FieldAnnotation1(), new FieldAnnotation2()])
    +annotateArguments([{annotate: [new ArgumentAnnotation()]}])
    constructor(arg: any) {}
    
    // note how member decorators have to be split up, with annotations being next
    // to the class decorators, and field decorators next to the field.
    -fieldDecorator()
    var field1: string;
}
```

**Comment by meirgottlieb** [comment]
Here is another approach for data-only annotations: https://github.com/artifacthealth/tsreflect-compiler.

**Comment by RichiCoder1** [comment]
So I take it this is becoming a thing in 1.5 ala. AtScript merge announcement?

**Comment by MgSam** [comment]
@msft Are you guys going to post the actual spec that you ended up implementing for this feature?

**Comment by RyanCavanaugh** [comment]
The spec will be updated, same as we do for everything else. Not sure exactly when that will be (usually the spec gets updated right before a feature starts getting implemented, i.e. early, or after the feature is implemented and we've worked out the kinks, i.e. late).

**Comment by jonathandturner** [comment]
Not sure if it got linked already, but the draft spec @rbuckton used was here: https://github.com/jonathandturner/brainstorming  

We should probably revise and post it to a more official place.

**Comment by wycats** [comment]
I'm planning on extracting the salient parts into a concrete TC39 proposal this weekend and present it at the next TC39 in a few weeks.

**Comment by mhegazy** [comment]
This is now tracked in #2249

**Comment by lee-elenbaas** [comment]
Just a quick reminder for annotations that does cause functionality change - aspect programming, both in java and C# rely heavily on annotations, and on building annotations that deal with the aspect, and have that aspect triggered using annotations
