### ISSUE TITLE
Cannot Easily Ignore checkJS Errors in JSDocs

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#15621]
From https://github.com/Microsoft/vscode/issues/26009

**TypeScript Version:**  2.3.2

**Bug**
For the JavaScript:

```js
// @ts-check

/**
 * @param {float} x
 */
function foo(x) { }
```

There is currently no easy way to suppress the error in the jsdoc:

<img width="473" alt="screen shot 2017-05-05 at 4 20 32 pm" src="https://cloud.githubusercontent.com/assets/12821956/25767509/c8971350-31ae-11e7-806a-c6a148397096.png">

None of the following worked:

```js
// @ts-check

/**
 * @ts-ignore
 * @param {float} x
 */
function foo(x) { }
```

```js
// @ts-check

/**
 * @ts-ignore @param {float} x
 */
function foo(x) { }
```

```js
// @ts-check

/**
 * @param {float} x
 */
// @ts-ignore 
function foo(x) { }
```

```js
// @ts-check

// @ts-ignore 
/**
 * @param {float} x
 */
function foo(x) { }
```

The following does seem to work:

```js
// @ts-check

/**
    // @ts-ignore
    @param {float} x
 */
function foo(x) { }
```

**Comment by mhegazy** [comment]
This really where the type system gets type info from. and you are asking it to check the file for you.. so ignoring this is a bit strange.

the fix for this issue is to tell the compiler what `float` is, you can either use JSDoc:

```ts
/** @typedef {number} float */
```

or add a .d.ts file in your project and add a type alias declaration as such:

```ts
type float = numebr;
```
