### ISSUE TITLE
Import destructuring

### ISSUE THREAD

**Issue by spion** [Microsoft/TypeScript#1563]
Support for import destructuring

```typescript
import { Query, Database, Pool, Transaction } = require('db');
```

vs

```typescript
import db = require('db');
import Query = db.Query;
import Database = db.Database;
import Transaction = db.Transaction;
import Pool = db.Pool; // half of my screen is imports already. need to buy larger screen.
```

**Comment by danquirk** [comment]
This is just valid ES6 module importing syntax that we have to support is it not?

**Comment by spion** [comment]
No, this is a lot simpler than ES6 modules. ES6 modules do something quite different. For example - importing references using ES6 import syntax allows for mutation:

```ts
import {test, other} from "some-module"
test = 42; // mutates the original `test` reference aswell
```

ES6 doesn't allow for actual destructuring of the default export

```ts
import defaultExport from "some-module"
```

This really depends, of course, on how TypeScript intends to support ES6 modules.

**Comment by danquirk** [comment]
_This really depends, of course, on how TypeScript intends to support ES6 modules - but their behavior is definitely very different than this proposal._

TypeScript intends to fully support ES6 modules and syntax with the same kind of fidelity as we support other ES features, that is, making TypeScript a superset of JavaScript. What I was alluding to with my previous comment is that the destructuring syntax in your original proposal is used by ES6 and so we'll need the semantics of that syntax in TS to align directly with how you'd expect it to work in ES6, along with all the other forms of import/export syntax that ES6 allows.

**Comment by spion** [comment]
@danquirk TypeScript import syntax isn't valid ES6 import syntax. There is no "=" for example. Supporting ES6 modules is an entirely different feature. And even if destructuring is implemented for ES6 modules, it would work entirely different from AMD and CommonJS modules. 

I guess you'd rather implement this together with ES6 module support?

**Comment by Arnavion** [comment]
@danquirk As @spion said, the emit would look different for ES6 imports vs the destructuring of require() that @spion is asking for.

The renaming destructuring syntax is also different: `import { foo as bar } from ...` instead of (potentially) `import { foo: bar } = require(...);` ("as" instead of colon). This was a deliberate decision made by the committee to disassociate ES6 import from require.

For ES6 import, the only possible downlevel emit (assuming it still piggy-backs on `require()`) is something that uses a getter and setter:

```javascript
import { foo, bar as baz } from "my-module"
```

```javascript
var a = require("my-module");
Object.defineProperties(global, {
    foo: { get: function () { return a.foo; }, set: function (value) { a.foo = value; } },
    baz: { get: function () { return a.bar; }, set: function (value) { a.bar = value; } }
});
```

(and similar for AMD.)

This is not required for destructuring CJS and AMD modules that @spion is asking for. That emit can be a combination of the current emit for import and the current emit for destructuring.

**Comment by mhegazy** [comment]
The ES6 modules are tracked in #2242 now.
