### ISSUE TITLE
Type implementing indexer interface has no index signature?

### ISSUE THREAD

**Issue by impworks** [Microsoft/TypeScript#15762]
**TypeScript Version:**  2.3

**Code**

```ts
interface ILookup<T> {
    [key: string]: T;
}

class Test implements ILookup<any> {
    a: string;
}

var ptyName = "a";
new Test()[ptyName] = "test";
```

**Expected behavior:**
The source compiles.

**Actual behavior:**
Error TS7017: Element implicitly has an 'any' type because type 'Test' has no index signature.

Strangely it works when explicitly casting the object to interface that it implements:
```
(new Test() as ILookup<any>)[ptyName] = "test";
```

**Comment by impworks** [comment]
Then shouldn't there be an error saying that `Test` does not fully implement `ILookup` because I have not defined the indexer?

**Comment by ahejlsberg** [comment]
No. We have a rule that says *anything* is assignable to a type with an index signature of type `any` (because every type satisfies this constraint), so the class you're declaring doesn't itself need to have an index signature. But this is true only for index signatures of type `any`. If you change your `implements` clause to `ILookup<string>` you will indeed see an error.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
