### ISSUE TITLE
Integrate prepack.io into the compilation process

### ISSUE THREAD

**Issue by michaelaird** [Microsoft/TypeScript#15761]
It would be amazing if TypeScript could incorporate the functionality of 
[prepack.io](https://github.com/facebook/prepack) into the compilation process to optimize runtime performance.

**Comment by kitsonk** [comment]
My feeling is that prepack is just another (slightly dangerous) post processor like uglify.  Because of that, it would contradict the [TypeScript design non-gloal](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#non-goals):

> 4) Provide an end-to-end build pipeline. Instead, make the system extensible so that external tools can use the compiler for more complex build workflows.

A tool like prepack could benefit from type information of code, of which the compiler services are available for that, though it would require significant changes to prepack to take advantage of those services.

Actually transforming the code from what was written, outside is required for down emits, would feel like it would contravene design goal #7:

> 7) Preserve runtime behavior of all JavaScript code.

**Comment by michaelaird** [comment]
I suppose it would also contravene:

> 2. Aggressively optimize the runtime performance of programs. Instead, emit idiomatic JavaScript code that plays well with the performance characteristics of runtime platforms.

It seemed like a natural fit but maybe it's actually the other way around where people who want that optimization could hook prepack.io into some kind of "pre-emit" step that would leverage the TypeScript AST/type information.

**Comment by kitsonk** [comment]
The TypeScript language services are there and with the new emitter architecture.  Someone could write an integrated sort of compiler.  The challenge is that prepack uses Babel for its AST information.  Whatever took advantage of the compiler services would either need to abstract prepack from the Babel AST or be a "TypeScript prepack" variant.  Likely both outside of the scope of the main TypeScript compiler though.

**Comment by michaelaird** [comment]
Ok. I'm going to go ahead and close this suggestion as outside the design goals of TypeScript, but it would be interesting if there was a workflow leverage this kind of optimization.
