### ISSUE TITLE
Literal Type and function overloads

### ISSUE THREAD

**Issue by yysun** [Microsoft/TypeScript#15823]
Is it possible to allow function overload based on literal type like below?

```TypeScript
function getArea(shape: { kind: "circle", radius: number }): number {
    return Math.PI * shape.radius ** 2;
}

function getArea(shape: { kind: "square", size: number }): number {
    return shape.size ** 2;
}

const a = getArea({ kind: "circle", radius: 5 });
const b = getArea({ kind: "square", size: 5 });
```

**Comment by DanielRosenwasser** [comment]
Since overloads only have one implementation signature, you'll want this:

```ts
function getArea(shape: { kind: "circle", radius: number }): number;
function getArea(shape: { kind: "square", size: number }): number;
function getArea(shape: { kind: "circle", radius: number } | { kind: "square", size: number }): number {
    if (shape.kind === "circle") {
        return Math.PI * shape.radius ** 2;
    }
    return shape.size ** 2;
}
```

But really, overloads aren't useful here. You should prefer to use a union type when two overloads only differ by parameters and return the same type (i.e. `number` in this case)

Also, since our repo gets a lot of issues, we encourage questions to be directed to StackOverflow or [our Gitter channel](https://gitter.im/Microsoft/TypeScript).

**Comment by yysun** [comment]
Thank you @DanielRosenwasser for quick reply although we haven't met.

I am actually suggesting this as a TypeScript language feature to allow function overload based on literal type. It will allow us add a function for rectangle and so on without modifying the _if/switch_ structure. And it likes the pattern matching in Elixir.

```TypeScript
function getArea(shape: { kind: "rectangle", width: number, height: number }): number {
    return shape.width * shape.height;
}
```

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
