### ISSUE TITLE
JSDoc `function` type does not accept parameters

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#15824]
**TypeScript Version:**  nightly (2.4.0-dev.20170513)

**Code**

```ts
// @ts-check
/** @type {function} */
const x = (a) => a + 1;
x(1);
```

**Expected behavior:**

No error.

**Actual behavior:**

`src/a.js(4,11): error TS2346: Supplied parameters do not match any signature of call target.`

It works with `Function`, but see #15825.

**Comment by yuit** [comment]
So the lower case function is used at the moment to denote the following style according to our wiki : https://github.com/Microsoft/TypeScript/wiki/JSDoc-support-in-JavaScript
```
/** @type {function(string, boolean): number} */
```

hence the error assume no parameters. I don' think this is a bug. but @mhegazy  and @rbuckton let me know if you think otherwise

**Comment by mhegazy** [comment]
People use `function` and `Function` interchangeably to mean the same thing, just like they do with `number` and `Number`. We do handle the later correctly, and I think we should do the same for the earlier as well.
