### ISSUE TITLE
error TS4020: 'extends' clause of exported class 'SampleNewClass' has or is using private name 'SampleMixin'

### ISSUE THREAD

**Issue by khusamov** [Microsoft/TypeScript#15870]
**TypeScript Version:**   2.3.2

**Code**

File `SampleMixin.ts` with mixin class:

```ts
export type Constructor<T = object> = new(...args: any[]) => T;

export interface SampleMixin {
    pluginManager: string[];
}

export default <S extends Constructor>(Superclass: S): Constructor<SampleMixin> & S => class extends Superclass {
    
    private _pluginManager: string[];
    
    get pluginManager(): string[] {
		return this._pluginManager ? this._pluginManager : this._pluginManager = [];
	}
	
}
```

The file `index.ts` where this mixin is used:

```ts

import SampleMixin from './SampleMixin';

class SampleSuperClass {}

export default class SampleNewClass extends SampleMixin(SampleSuperClass) {}
```

**Expected behavior:**

`Compilation complete. Watching for file changes.`

**Actual behavior:**
```
index.ts(6,22): error TS4093: 'extends' clause of exported class 'SampleNewClass' refers to a type whose name cannot be referenced.
index.ts(6,45): error TS4020: 'extends' clause of exported class 'SampleNewClass' has or is using private name 'SampleMixin'.
```

**Comment by mhegazy** [comment]
This looks like the same underling issue as https://github.com/Microsoft/TypeScript/issues/9944. the rule is if the compiler tries to write the type, and it needs an import from another module, and it was not already available, then error.. 

if you were to write the type manually for this class, you would have needed something like:
```ts
import SampleMixin, { SampleMixin as SampleMixinType, Constructor } from './b'; 

class SampleSuperClass { }

const base: Constructor<SampleMixinType> & typeof SampleSuperClass = SampleMixin(SampleSuperClass);

export default class SampleNewClass extends base { }
```

since both `SampleMixinType` and `Constructor` are not already imported, the compiler is giving you this error. the fix is to ensure they are imported, and/or you write an explicit type annotation for the base.

https://github.com/Microsoft/TypeScript/issues/9944 tracks adding imports automatically in such cases.

**Comment by rohmanhm** [comment]
https://github.com/styled-components/styled-components/issues/973

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
