### ISSUE TITLE
Specifying --outDir on the CLI causes error TS5055 with declarations

### ISSUE THREAD

**Issue by slikts** [microsoft/TypeScript#15899]
**TypeScript Version:**  2.4.0-dev.20170517, 2.3.2

Files to reproduce: https://gist.github.com/slikts/7a35d205e01b54f169c7d13dfe248a69 (just an empty .ts file and an empty tsconfig.json file)

```sh
$ tsc --outDir dist --declaration true
$ tsc --outDir dist --declaration true
error TS5055: Cannot write file 'dist/Foo.d.ts' because it would overwrite input file.
```

This error does not occur if the `outDir` option is set in tsconfig.json.

**Comment by mhegazy** [comment]
:D this is a fun one. so here is what is going on, if no `exclude` (or `include`) is specified explicitly in the tsconfig, one is created. by default, that is `["node_modules" , "<otutDir>"]`, but since the `outDir` is specified on the commend line, it is not taken into account when the tsconfig.json is parsed.

the result is a including the .d.ts that was generated the previous time, and hence the error, that hte output of `foo.ts` would overwrite an input `dist/foo.d.ts`.

A workaround would be to add `include`, or `exclude` with `dist` in your tsconfig.json, or just set the `outDir` in the tsconfig.json as you noted.
