### ISSUE TITLE
No valid value for string literal intersection. ('a' & 'b')

### ISSUE THREAD

**Issue by rokoroku** [Microsoft/TypeScript#15923]
**TypeScript Version:**  2.3.2

**Code**

```ts
// A *self-contained* demonstration of the problem follows...

let stringIntersection: '1' & '2';
stringIntersection = '1'; // ts: Type '"1"' is not assignable to type '"1" & "2". 
stringIntersection = '2'; // ts: Type '"2"' is not assignable to type '"1" & "2". 
stringIntersection = '12'; // ts: Type '"12"' is not assignable to type '"1" & "2".
stringIntersection = '1' || '2'; // ts: Type '"1" | "2"' is not assignable to type '"1" & "2".

```

**Description**

There is **no valid value** for given string literal intersection. it'd be better to treat them as `union type` or just `string`.

The problem occurs in below usage:
```ts

type Type = 'type1' | 'type2';
interface Base {
  type: Type;
}
interface DataType1 extends Base {
  type: 'type1';
  dataA: {
    a: number;
  };
}
interface DataType2 extends Base {
  type: 'type2';
  dataB: {
    b: string;
  };
}

type PossibleData = DataType1 & DataType2; // no valid value for PossibleData['type']

```

If this is intended behavior, what is the string literal intersection stands for?

**Comment by RyanCavanaugh** [comment]
`"x" & "y"` "stands for" the same thing as any other `T & U`. It just happens that this combination of types has zero overlap in its constituents' domains.

It's always going to be possible to create an intersection type that has no valid values. Detecting these outside of the trivial case would require the compiler to exercise some kind of constraint solving algorithm, which is obviously not worth the computational effort.

Due to how generic instantiation works, there's just not a clear way to detect and flag this as an error, and it's arguable that it would be undesirable to do so even if it were possible.

**Comment by rokoroku** [comment]
OK, so I need to wait for #4183 to achieve above scenario. Thanks.
