### ISSUE TITLE
String enum and matching string literal types

### ISSUE THREAD

**Issue by normalser** [Microsoft/TypeScript#15930]
Would it be possible to make all these cases work (not throw an error) ?

```ts
enum StringEnum {
    a = 'a',
    b = 'b',
    c = 'c'
}

const a1 = StringEnum.a
const a2 : 'a' = 'a'
const a3 = 'a'

function test(e:StringEnum) {}

test(a1)
test(a2)  // Error
test(a3)  // Error
test('a')  // Error
```

**Comment by mhegazy** [comment]
This is the intended design. A string enum creates a subtype of the literal types. so the enum literal is assignable to the string literal but not the other way around. The rational here is if you use string enums, you should use them all the way to ensure safe refactoring, otherwise stick with literal types.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by sebilasse** [comment]
@normalser If you would also need the Enum at runtime you can create an according type like so :
```TypeScript
type StringEnumType = keyof typeof StringEnum;
```
