### ISSUE TITLE
Export a module with `require()`

### ISSUE THREAD

**Issue by tmcw** [Microsoft/TypeScript#1598]
Sorry if this is a duplicate - I'd imagine someone else has asked the same thing - but the absence of a node-facing require'able API has [other tools like tern](https://github.com/marijnh/tern/blob/master/lib/typescript.js#L9-L12) requiring files within typescript, and these [files predictably move](https://github.com/marijnh/tern/issues/468) and break those tools.

**Comment by xealot** [comment]
You may want to check this thread. This sounds like it's related to a lot of the packaging woes that Typescript has right now

https://github.com/Microsoft/TypeScript/issues/17

**Comment by tmcw** [comment]
So it looks like this is committed to master - `require('typescript')` gives useful methods - but there hasn't been a release since.

**Comment by danquirk** [comment]
Right, this was first added with https://github.com/Microsoft/TypeScript/pull/1417. See #372 for original issue/discussion and related items. Does that cover everything you need for now?

**Comment by tmcw** [comment]
It doesn't look like 1.4 is released, so the changes aren't usable in npm yet?

**Comment by tmcw** [comment]
Also it doesn't look like the node interface is documented?

**Comment by danquirk** [comment]
Correct, we have not done a new release since this change was checked in. Richer documentation can come online in the future (particularly based on what bits/concepts people find most confusing), the code itself should be relatively well commented. We've had enough people asking for this API for long enough that we're not going to block releasing the API due to documentation quality (especially since as you note people are already successfully using the compiler internals with the current level of documentation).

**Comment by tmcw** [comment]
As far as I can see, [the exported typescriptServices.js](https://github.com/Microsoft/TypeScript/blob/master/bin/typescriptServices.js) has no comments?

**Comment by danquirk** [comment]
Comments will be in the .d.ts that the language service consumes https://github.com/Microsoft/TypeScript/blob/master/bin/typescriptServices.d.ts

PRs are obviously welcome if people want to add additional comments/documentation as they find it useful.

**Comment by tmcw** [comment]
Okay, thanks for the help.
