### ISSUE TITLE
Class Inheritance is Not ES6 Spec Compliant

### ISSUE THREAD

**Issue by EisenbergEffect** [Microsoft/TypeScript#1601]
The following should log `true` but logs `false` instead:

```javascript
class Foo {}
class Bar extends Foo {}

console.log(Object.getPrototypeOf(Bar) === Foo);
```

This is due to how the __extends helper is implemented. It generates this:

```javascript
var __extends = this.__extends || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    __.prototype = b.prototype;
    d.prototype = new __();
};
```

An example of a correctly functioning extends implementation can be found in the 6to5 compiler. Here is their implementation:

```javascript
var _extends = function (child, parent) {
    child.prototype = Object.create(parent.prototype, {
      constructor: {
        value: child,
        enumerable: false,
        writable: true,
        configurable: true
      }
    });
    child.__proto__ = parent;
  };
```

**Comment by basarat** [comment]
> (Object.getPrototypeOf(Bar) === Foo);

If this is indeed the case (I'll need to check the spec) all that's really missing is `child.__proto__ = parent;`, so I would recommend:

```ts
var __extends = this.__extends || function (d, b) {
    d.prototype.__proto__ = b.prototype;
    d.__proto__ = b;
};
```

----------------

Notes: 

* ` for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];` was needed for statics. This is overcome by `d.__proto__` pointing to the base. 
* `    d.prototype.__proto__ = b;` if you are using `__proto__` why not go all the (unsafe) way. 
* `Object.create` the team didn't use this to support ES3.

**Comment by basarat** [comment]
Verified that it *should* indeed be `true` by the following code run on the console of an ES6 enabled browser (e.g. chrome://flags/#enable-javascript-harmony) :
```js
(function (){"use strict"; class Foo{}; class Bar extends Foo{}; console.log(Object.getPrototypeOf(Bar) === Foo);})() 
```
prints `true`

**Comment by Arnavion** [comment]
`__proto__` was not standardized until ES6. IE, V8 and JavaScriptCore atleast support it but maybe there are some ES5 browsers out there that don't?

**Comment by basarat** [comment]
I am not so sure about IE (note IE10): 

![image](https://cloud.githubusercontent.com/assets/874898/5623110/fe7b591e-95a1-11e4-9dda-d30f8b297d98.png)

**Comment by Arnavion** [comment]
Hmm, indeed. Only IE11 supports setting `__proto__`.

**Comment by Arnavion** [comment]
I guess we could take 6to5's shim and add TS's static-copying code to it? Then it would start giving the correct answer for `Object.getPrototypeOf(Derived)` on browsers which do support `__proto__`, and statics will continue to be copied on browsers which don't.

```javascript
var __extends = function (d, b) {
	d.prototype = Object.create(b.prototype, {
		constructor: {
			value: d,
			enumerable: false,
			writable: true,
			configurable: true
		}
	});

	d.__proto__ = b;

	for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
};
```

Setting `__proto__` is still bad for performance though - getting standardized didn't change that.

---

I would say that requiring `Object.getPrototypeOf(Derived) === Base` is a relatively uncommon operation to require this change in the default emit. If user desires it, they can provide their own implementation to override the default one.

**Comment by basarat** [comment]
to support all browsers perhaps we should use `inherits` (https://github.com/isaacs/inherits/blob/master/inherits_browser.js same as the core node.js `util` module). 

Nevertheless just a suggestion as a meantime thing @EisenbergEffect you might use this `inherits` instead of `extends` and use `super_` to walk up the chain.

**Comment by Arnavion** [comment]
@basarat I think @EisenbergEffect could just use the 6to5 shim he provided if he wanted to override __extends.

Also, utils.inherit() (and that browser version) doesn't inherit statics, so it's not a drop-in replacement for __extends. If you added static-copying to it, it would basically become `if (Object.create) { /* 6to5 shim code */ } else { /* TS shim code */ }` which would still break on old IE.

**Comment by EisenbergEffect** [comment]
Is there currently a way to plug in a custom `__extends` implementation for the TypeScript compiler? I don't need it myself but I'd like to be able to tell developers using my framework how best to get the standard behavior when using TypeScript if they need it.

**Comment by Arnavion** [comment]
Since the default emit is `var __extends = this.__extends || ...`, if you provide a function named __extends on the global object before the TS-emitted __extends, your function will be used instead. This is a deliberate escape hatch to let users plug in their own implementation.

If you want to do it in TS itself along with the original code, then put a `var __extends = function (d, b) { }`, that is, without the `this.__extends` part, to forcibly override. [Example](http://www.typescriptlang.org/Playground#src=var%20__extends%20%3D%20function%20(d%2C%20b)%20%7B%0D%0A%09%2F%2F%20My%20own%20implementation%0D%0A%7D%0D%0A%0D%0Aclass%20Foo%20%7B%0D%0A%09%0D%0A%7D%0D%0A%0D%0Aclass%20Bar%20extends%20Foo%20%7B%0D%0A%09%0D%0A%7D)

**Comment by basarat** [comment]
> Is there currently a way to plug in a custom __extends implementation for the TypeScript compiler

A hacky *almost working* suggestion perhaps in an npm `es6-extend`:
```js
var root = global || window; 
root.__extends = function(d,b){/*your code*/}
```
Now `require('es6-extend')` at the root of your project just once will fix it for *all* files. 

Note: I haven't tested the code but I say *almost* because the default `__extends` uses `this.__extends` and `this` in node isn't `global`, its the current module. Perhaps I should open a bug to get the team to not have `this.__extends` and instead just use `__extends` (which will look at `global` on node and `window` on browser). Perhaps they added `this` to support code validation tools, but I think its causing an undue hurdle.

**Comment by Arnavion** [comment]
>Perhaps I should open a bug to get the team to not have this.__extends and instead just use __extends (which will look at global on node and window on browser).

`var __extends = __extends || ...` will not work. It will just get undefined, even if there's already a global __extends, since its own (uninitialized) definition is in scope. Even `global || window` will not work if `global` is undeclared, since it's a TypeError to refer to undeclared variables.

You could ask for the TS emit to become `var __root = typeof global !== "undefined" && global || typeof window !== "undefined" && window || this; var __extends = __root.__extends || ...`

Unfortunately the only real solution to get the global object instead of hard-coding a list of possible globals is via eval `var __root = (1, eval("this"));`. Maybe this isn't a big deal though.

**Comment by basarat** [comment]
@Arnavion how about the following:

```js
var root = (function(){return this})(); 
root.__extends = function(d,b){/*your code*/}
```
Which would work if the TS emit was: 
```js
var __extends = (function () {
    return this.__extends || function (d, b) {
        for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
        function __() { this.constructor = d; }
        __.prototype = b.prototype;
        d.prototype = new __();
    }
})();
```
getting a consistent `this` (`window` or `global`) in *every* file in your project.

**Comment by Arnavion** [comment]
@basarat The IIFE technique for getting the global doesn't work in strict mode. The eval technique does.

**Comment by basarat** [comment]
> The IIFE technique for getting the global doesn't work in strict mode. The eval technique does.

My bad. Thanks.

**Comment by basarat** [comment]
@Arnavion making your suggestion more concrete:

`fix.js`:
```js
var __root = typeof global !== "undefined" && global || typeof window !== "undefined" && window || this;
__root.__extends = function(d,b){/*your code*/}
```
would work if ts emit for `__extends` was (which is backward compatible): 
```js
var __root = typeof global !== "undefined" && global || typeof window !== "undefined" && window || this;
var __extends = __root.__extends = __root.__extends || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    __.prototype = b.prototype;
    d.prototype = new __();
}
```

**Comment by Arnavion** [comment]
Yes.

To be honest, we could still use your `require("es6-extend")` idea in this way:

```javascript
var __extends = require("es6-extend"); // if at global scope, var becomes a property of `this`
// or
this.__extends = require("es6-extend"); // if not at global scope, explicitly add it to `this`
```

es6-extend would export the new function instead of assigning it anywhere. Then we can leave the current emit unchanged. The downside is that the user of the module has to remember to call the variable __extends and nothing else.

**Comment by Arnavion** [comment]
BTW [this](https://github.com/substack/insert-module-globals/blob/d8a44fb/index.js#L14) is what browserify uses to shim `global`. You could use that for __root.

The evolution of that shim is interesting. It started as just returning 'self' unconditionally, then [added the typeof-check for self and returned window or `{}` otherwise](https://github.com/substack/insert-module-globals/commit/538ef4), then finally [updated to check for global too.](https://github.com/substack/insert-module-globals/commit/60ed498)

**Comment by RyanCavanaugh** [comment]
We'll have to discuss what exactly to do here. I know there's a lot of hesitation to make `__extends` any more complex than it absolutely has to be, but this might be important enough to change it.

**Comment by Arnavion** [comment]
@RyanCavanaugh To summarize

- `this`, `self` and `window` in a script loaded in a browser refers to the global object.
- `this` on node can either be the global object (when a file or script is run as the main module) or a module object (when a file is require'd). However `global` refers to the global object in both cases.
- Because `this` is a module-specific object in a require'd piece of code, it is not possible for a require'd module to override the TS-emitted __extends implementation in the module it's being require'd into. It has to be necessarily overriden in the same file that contains it, and this has to be done in every file that has the emit.

Because of this, @basarat is proposing the default emit try to place __extends on the global object instead of `this`. The new emit is the second code block in https://github.com/Microsoft/TypeScript/issues/1601#issuecomment-68984374 This new emit tries to find a few well-known globals (node and browser) and falls back to `this` if it can't. It checks for and attaches the __extends function to this object. This way, a module can be written to override __extends (like the first block in that comment), and any module which wishes to use it can simply require() it.

The only user-visible difference from the current emit that I can think of is that, if the user is on node and already has a different __extends registered on the global object, it will now be clobbered. However users should not expect names prefixed with two underscores to be available to them, so I think this is acceptable. Also, if they already have a variable named __root in scope it will be clobbered. The same reasoning applies there. TS could complain about __root being used by user code, like it complains about user-defined `_this`, `_i`, etc. (TS2397-2402).

Alternatively, it could be done in an IIFE that only exposes __extends:

```javascript
var __extends = (function (root) {
    return root.__extends = root.__extends || function (d, b) {
        for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
        function __() { this.constructor = d; }
        __.prototype = b.prototype;
        d.prototype = new __();
    };
})(typeof global !== "undefined" && global || typeof window !== "undefined" && window || this);
```

Then no new variable is introduced and no new diagnostic is needed from TS.

I think this is not much more complicated than the current __extends. In particular, it should have no difference from the current emit in terms of performance, because the actual __extends implementation is still the same - it does not hold on to anything new from its closure.

**Comment by RyanCavanaugh** [comment]
Can we please not have two completely different conversations here?
 * How `__extends` interacts with the global object
 * Whether `__extends` sets up the prototype chain the same as ES6

**Comment by RyanCavanaugh** [comment]
Please see Ron's comments in #1622 for a proposed change to emit to better work with the global object.

For the actual bug in the original report, we've decided to keep things the way they are. The reasoning is that `__proto__` is an ES6 construct, as is `Object.setPrototypeOf`, and without either of those, we can't emulate the ES6 prototype chain in the first place.

While some runtimes support these things, we can't make meaningful calls based on vendor-specific supported subsets of of ES6 behavior. In other words, if you want the ES6 prototype chain behavior, you'll need to target ES6. If you target ES5, the functions we would need to set the correct prototypes are not available *as defined by the standard*, so we're not going to try to match that behavior in only some subset of runtimes.

With the changes proposed in #1622, it should be meaningfully easier to substitute in your own "ES5.5"-compliant version of `__extends` that does set the prototype chain in runtimes that support it.

**Comment by calebboyd** [comment]
@RyanCavanaugh 
>we've decided to keep things the way they are

Is this still true?

This makes reflecting on hierarchies quite difficult...

Correctly compiled es2015 -> es5 with [babel](https://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&code=class%20One%20%7B%20%0D%0A%20%20a()%20%7B%7D%0D%0A%7D%0D%0A%0D%0Aclass%20Two%20extends%20One%20%7B%0D%0A%20%20b()%20%7B%7D%0D%0A%20%20c()%20%7B%7D%0D%0A%7D%0D%0A%0D%0Aclass%20Three%20extends%20Two%20%7B%0D%0A%20%20d()%20%7B%7D%0D%0A%20%20e()%20%7B%7D%0D%0A%7D%0D%0A%0D%0Afunction%20uniqueNotConstructor%20(names%2C%20name)%20%7B%0D%0A%20%20~names.indexOf(name)%20%7C%7C%20name%20!%3D%3D%20'constructor'%20%26%26%20names.push(name)%0D%0A%20%20return%20names%0D%0A%7D%0D%0A%0D%0Afunction%20reflectClassProperties%20(source%3A%20Function)%20%7B%0D%0A%20%20const%20properties%3A%20Array%3Cstring%3E%20%3D%20%5B%5D%2C%0D%0A%20%20%20%20constructors%3A%20Array%3CFunction%3E%20%3D%20%5B%5D%0D%0A%0D%0A%20%20let%20current%20%3D%20source%0D%0A%0D%0A%20%20while%20(current%20%26%26%20current.prototype%20%26%26%20current%20!%3D%3D%20Function.prototype)%20%7B%0D%0A%20%20%20%20Object.getOwnPropertyNames(current.prototype)%0D%0A%20%20%20%20%20%20.reduce(uniqueNotConstructor%2C%20properties)%0D%0A%20%20%20%20constructors.push(current)%0D%0A%20%20%20%20current%20%3D%20Object.getPrototypeOf(current)%0D%0A%20%20%7D%0D%0A%0D%0A%20%20return%20%7B%0D%0A%20%20%20%20source%2C%0D%0A%20%20%20%20properties%2C%0D%0A%20%20%20%20constructors%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconsole.log(reflectClassProperties(Three))%0D%0A%0D%0A)

The same compiled function in TS fails to produce the correct results

**Comment by calebboyd** [comment]
Is it safe to say class semantics will continue to be incorrect when targeting es5?
