### ISSUE TITLE
can't return object constructor from arrow function

### ISSUE THREAD

**Issue by abe-winter** [Microsoft/TypeScript#1607]
Issues in TS 1.3.0.0 with arrow functions that return objects.

```javascript
var f1=(arg)=>{key:arg}; // this compiles but generates garbage
var f2=(arg)=>{key:arg,key2:'whatever'}; // this won't compile
var f3=(arg)=>{"key":arg}; // this won't compile
```

**Comment by stkb** [comment]
When returning an object literal from an arrow function you need to enclose it in parentheses, otherwise the compiler assumes you're using the braces to denote a multi-line function. So your examples need to be:
``` javascript
var f1=(arg)=>({key:arg});
var f2=(arg)=>({key:arg,key2:'whatever'});
var f3=(arg)=>({"key":arg});
```

**Comment by danquirk** [comment]
This is working as intended, your curly braces are denoting the start and end of the body of the arrow function, not the start of an object literal. Your first example is actually a fat arrow with a body that is a labeled statement. The second is invalid because you can't have a comma separated list of labeled statements. The third is an error because a label can't be a string literal. 

This works:

```ts
var f1 = (arg) => { return { key: arg }; } 
var f2 = (arg) => { return { key: arg, key2: 'whatever' }; } 
var f3 = (arg) => { return { "key": arg }; } 
```

**Comment by abe-winter** [comment]
Fair enough, thanks.
