### ISSUE TITLE
[JSDoc] Missing support of JSdoc @type

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#16199]
- [ ] `{Object}` has type `any`, it should be `{}`
```js
// @ts-check
/**
 * @type {Object}
 */
var bar;
```

- [ ]  `Object.<type1, type2>` has type `any`  (#15105)
```js
// @ts-check
/**
 * @type {Object.<string, number>} obj
 */
var bar;
```

- [ ] Specify property in object type
```js
// @ts-check
/**
 * @type {Object} myObj
 * @type {number} myObj.a
 */
var bar;
```

- [ ] Using with `@callback`
```js
// @ts-check
/**
 * @callback myCallback
 * @param {number} x - ...
 */

/** @type {myCallback} */
var cb;
```

**Comment by mhegazy** [comment]
>{Object} has type any, it should be {} 

this is intentional. ppl use `Object` both in input and output locations. in input locations `{}` is fine, but in output locations it is not. they really mean `any`. see https://github.com/Microsoft/TypeScript/pull/14284 for more details.

> Object.<type1, type2> has type any

tracked by #15105

>  Specify property in object type

tracked by https://github.com/Microsoft/TypeScript/issues/11597

>  Using with @callback

tracked by https://github.com/Microsoft/TypeScript/issues/7515

**Comment by yuit** [comment]
For this 

> {Object} has type any, it should be {}
this is intentional. ppl use Object both in input and output locations. in input locations {} is fine, but in output locations it is not. they really mean any. see #14284 for more details.

You can then use `{*}` for any....I guess it may not be intuitive ?

**Comment by mhegazy** [comment]
yes. but users use them interchangabley. just like `function`, `Function` to mean any function

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
