### ISSUE TITLE
Change the emit for `__extends` to support easy global override

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#1622]
Change the emit for `__extends` to be : 

```js
var __root = typeof global !== "undefined" && global || typeof window !== "undefined" && window || this;
var __extends = __root.__extends = __root.__extends || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    __.prototype = b.prototype;
    d.prototype = new __();
}
```
# Reason:
It will allow you to override `__extends` globally with a single `require` call to a file that contains the following: 
```js
var __root = typeof global !== "undefined" && global || typeof window !== "undefined" && window || this;
__root.__extends = function(d,b){/*custom __extends implementation*/}
```
Note: all AMD / CommonJS / internal modules will work

More : https://github.com/Microsoft/TypeScript/issues/1601#issuecomment-69235352

**Comment by pspeter3** [comment]
Another option seems to be generating an extends module and having it be imported by all modules that use extends

**Comment by whitneyit** [comment]
@pspeter3 +1 Similar to the issue I raised in #1350

**Comment by rbuckton** [comment]
We are considering the following change, which would only be observably different in CommonJS (details below):

```js
if (typeof __extends !== "function") __extends = function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    __.prototype = b.prototype;
    d.prototype = new __();
};
```

Here are some additional details on this proposal:
1. We do not emit a `var` for `__extends`. This means that a variable declaration for __extends will not be hoisted in the current scope and will force `__extends` to refer to the global scope.
2. If a global `__extends` exists, it will not be overwritten.
3. There is no need to capture a direct reference to the global environment (via `window`, `self, `global`, or `this`), so this should work on all platforms (Web Browser, Web Worker, nodejs, iojs, cscript, etc.).

In general, this would not be observably different for scripts or `--module amd`. However, there would be an observable change to `--module commonjs`. The current approach that uses `this` has unspecified behavior in CommonJS, based on the execution context as @Arnavion mentioned above. This change would bring the CommonJS runtime behavior in line with the AMD behavior.  In addition, this change would help with some of our other helpers we are emitting for decorators in ES6, where `this` is guaranteed to be `undefined` in a module body.

The downside is that this change would introduce a global identifier in CommonJS (and also eventually in ES6 modules) that would not have previously been defined. Also, running a linter against the output may result in a warning or error due to introducing a global identifier.

We would like to get some feedback on this approach, and are considering this change for 1.5 beta. If you are aware of any existing behavior that would be negatively impacted by this change, please let us know.

**Comment by danquirk** [comment]
As recently noted, does #2901 cover everything folks wanted here?

**Comment by mhegazy** [comment]
#2901 should address the underlying issue.
