### ISSUE TITLE
inferred parametric types are not checked by the compiler

### ISSUE THREAD

**Issue by vujevits** [Microsoft/TypeScript#1624]
This compiles on the online playground, and tsc version 1.3.0 as well:

```ts
function foo():()=>Bar<string> {
    return ()=>{ return new Bar<number>(); };
}
```
update: a more simple example which should fail at compile time as well:
```ts
function foo():Bar<string> {
	return  new Bar<number>();
}
```

http://www.typescriptlang.org/Playground#src=class%20Bar%3CA%3E%0A{%0A}%0A%0Afunction%20foo%28%29%3A%28%29%3D%3EBar%3Cstring%3E%20{%0A%09return%20%28%29%3D%3E{%20return%20new%20Bar%3Cnumber%3E%28%29%3B%20}%3B%0A}%0A%0A

**Comment by ahejlsberg** [comment]
This is by design and an effect of TypeScript's structural type system. See #468.

In your example you declare the `Bar` as an empty class that never references its type parameter:
```typescript
class Bar<T> { }
```
When a type parameter is never referenced, it doesn't matter what type you pass as a type argument--all generic instantiations of the class are *structurally* equivalent. If you change your declaration to
```typescript
class Bar<T> {
    x: T;
}
```
the instantiations now differ by structure and you will see the expected errors.

**Comment by vujevits** [comment]
and this is true for arrays as well, 

```ts
function foo():Array<string> {
	var arr = [];
	arr.push(5);
	return  arr;
}
```
is there a best practice, apart from being explicit when instantiating a variable?

**Comment by ahejlsberg** [comment]
The array example is different. The type of `arr` is inferred as `any[]` because there is no type annotation on the declaration and  no elements in the array literal from which to infer an element type. And since an `any[]` is assignment compatible with any array type, including `string[]`, there is no error.

If you compile with the `-noImplicitAny` flag (which disallows inferences of type `any`, requiring explicit type annotations in those cases) you will get an error on the declaration of `arr` because `any[]` was implicitly inferred.

The best way to write this particular example would be:
```typescript
function foo() {
    var arr: string[] = [];
    arr.push(5);  // Error here
    return arr;
}
```
With or without `-noImplicitAny` this will give you an error.

**Comment by vujevits** [comment]
Thanks.
