### ISSUE TITLE
use a exported union type from some other file, get a warning

### ISSUE THREAD

**Issue by rdkmaster** [Microsoft/TypeScript#16261]
**TypeScript Version:**  2.3.2

**time-type.ts**

```ts
export type Time = Date | string ;

export class TimeTest {
//this class defination here is the key to reproduce this issue
}
```

**time.ts**

```ts
import {Time} from "time.type";
import {Input} from "@angular/core";

export class MyTime {
    @Input('theTime') //this is another key to reproduce this issue
    public _theTime:Time;
}
```

**Expected behavior:**
compile success, without warnings, page shows normally

**Actual behavior:**
the compiler give me a warning:
```
WARNING in ./src/time.ts
226:50-54 "export 'Time' was not found in './src/time-type'
```

the angular page won't show

----
updated 20170606, add more info

@ice0526

**Comment by aluanhaddad** [comment]
Sounds like a loader issue.

**Comment by DanielRosenwasser** [comment]
Is that really the full example, or are you actually using `Time` in some way in the file as well?

A common issue I've seen come up is when someone tries to decorate a member whose annotation is purely a type (as opposed to something like a class which has both a type and a runtime value).

Because decorator metadata is emitted, `Time`  will sometimes be emitted as a value even though it doesn't exist at runtime.

**Comment by rdkmaster** [comment]
@DanielRosenwasser I've updated the issue, add more info enough to reproduce the issue

**Comment by mhegazy** [comment]
Is the difference between the module name and file name intentional?

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
