### ISSUE TITLE
[1.8.34] Incorrect function hoisting for "let" variables within single statement scopes

### ISSUE THREAD

**Issue by MaulingMonkey** [Microsoft/TypeScript#16347]
Not sure from CONTRIBUTING.md if you're taking bug reports for older versions.  If you're not, close with my apologies - this has already been fixed in whatever version is on http://www.typescriptlang.org/play/ .

**TypeScript Version:**  1.8.34

**Code**
```ts
function test(a: any[]) {
	if (a === undefined) {}
	else for (let i=0; i<a.length; ++i) {
		let f = function(){ i; };
	}
}

test(undefined);
test([1,2,3]);
```

**Expected behavior:**
Generated code should only execute the for loop if the argument is not undefined.

**Actual behavior:**
The compiler tries to add another statement to the else clause to create/initialize "_loop_1" but fails to add any curly braces, causing the loop to be unconditionally executed - resulting in `Uncaught TypeError: Cannot read property 'length' of undefined`

```js
function test(a) {
    if (a === undefined) { }
    else
        var _loop_1 = function(i) {
            var f = function () { i; };
        };
        for (var i = 0; i < a.length; ++i) {
            _loop_1(i);
        }
}
test(undefined);
test([1, 2, 3]);
//# sourceMappingURL=app.js.map
```

**Comment by mhegazy** [comment]
looks like it is fixed in [latest](http://www.typescriptlang.org/play/index.html#src=function%20test(a%3A%20any%5B%5D)%20%7B%0D%0A%09if%20(a%20%3D%3D%3D%20undefined)%20%7B%7D%0D%0A%09else%20for%20(let%20i%3D0%3B%20i%3Ca.length%3B%20%2B%2Bi)%20%7B%0D%0A%09%09let%20f%20%3D%20function()%7B%20i%3B%20%7D%3B%0D%0A%09%7D%0D%0A%7D%0D%0A%0D%0Atest(undefined)%3B%0D%0Atest(%5B1%2C2%2C3%5D)%3B)
