### ISSUE TITLE
how to enforce "this interface A should be a descendent of an empty interface B"?

### ISSUE THREAD

**Issue by devdoomari** [Microsoft/TypeScript#16451]
I'm trying to enforce "IContext should be a descendent of IContextBase", even though IContextBase is empty.

With current set-up, I can only do:

```typescript
interface IContextBase {
  __EXTENDS_ICONTEXT_BASE: null;
}
interface IPropsBase {
  __EXTENDS_IPROPS_BASE: null;
}
interface ITestContext extends IContextBase { ... }
class Test1<
   IContext extends IContextBase
   , IProps extends IPropsBase
> { ... }
```

but this method is quite cumbersome because I have to keep making variables with '__EXTENDS_IPROPS_BASE' in it:

```typescript
const textContext: ITestContext = {
   __EXTENDS_CONTEXT_BASE: null,
   // ...other fields for ITestContext
}
```

Is there a better way?

ps: my question on stackoverflow might be relevant: https://stackoverflow.com/questions/44455020/tricking-typescript-compiler-to-assign-wrong-interface-to-a-variable

**Comment by andy-ms** [comment]
Related: #202

**Comment by mhegazy** [comment]
also see https://github.com/Microsoft/TypeScript/issues/4895

**Comment by devdoomari** [comment]
@andy-ms are you refering to https://github.com/Microsoft/TypeScript/issues/202#issuecomment-302402671 ?

In that case, the following snippet fails :( 

@aleksey-bykov but that doesn't work for interfaces / etc:

```ts
declare class As<S extends string> { 
   private as: S;
}
type Basket = {
   a?: number
} & As<'basket'>

const testBasket: Basket = {} // error: no 'as' in {}
```

**Comment by andy-ms** [comment]
#202 is the issue for nominal types, which seems to be what you want. I don't think there's any solution that would allow you to use an object literal as a nominal type without a cast.
#4895 is related to nominal types since it would allow you to have additional information about an object without actually adding any additional properties to that object.

If you want to enforce that you only accept objects explicitly declared as an `IPropsBase`, you could always use a function like `function createProps<T>(props: T): T & IPropsBase { return props as T & IPropsBase; }`, but you would have to call it everywhere you use props.
You could also just use an abstract base class for `PropsBase` with an unused private member and have everything else inherit from it.

**Comment by svieira** [comment]
@devdoomari - as @aleksey-bykov pointed out in https://github.com/Microsoft/TypeScript/issues/202#issuecomment-308387009, but in case you didn't see it, all you need is a cast:

```typescript
declare class As<S extends string> { 
   private as: S;
}
type Basket = {
   a?: number
} & As<'basket'>

// Casts are always necessary
const testBasket: Basket = {} as Basket
```

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
