### ISSUE TITLE
define getter and setter on modules or namespaces

### ISSUE THREAD

**Issue by DianeMa** [Microsoft/TypeScript#16478]
Summary :

I need to be able to define getter / setter properties on modules and namespaces.
It could use the **get** and **set** keywords  like currently on classes.

I'd like to be able to do that:

**Code**

```ts

type TType = { a: number; b: string;  }

export var DirectAccess: TType = { a: 1, b: 'name' };

//currently doesn't work
var _hiddenVar: TType = null;
export get IndirectAccess(){ return _hiddenVar; }
export set IndirectAccess(val :TType) { _hiddenVar = val; }

```
which would then compile (in amd) to that

```ts
define(["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
   
    var _hiddenVar = null;
    exports.DirectAccess = { a: 1, b: 'name' };

    //exported accessors
    Object.defineProperty(exports, "IndirectAccess", { get: function () { return _hiddenVar; }, set: function (val) { _hiddenVar = val; }   });

});

```

Scenario / Motivation:

I have some modules that act as Singletons (I think "revealing module pattern")
I like to prefix the module internal state variables (usually by "_") so that in functions I differentiate these variables from the function's input variables.
But I also want to export these variables as properties to the outside WITHOUT the _ prefix

In a class I would use get and set to do that, however the get and set syntax is not supported on modules (or it's not properly documented :/ )   

I also don't want to convert my module into a class, because then I'd have to rely on the facetious "this"

**Comment by DanielRosenwasser** [comment]
Since this is a change to how ECMAScript modules work, I think this should probably be submitted as a suggestion to ECMAScript itself. Keep in mind that right now ECMAScript modules are specified to have immutable import bindings.

Given that I'd have to say this is out of the scope of TypeScript at the moment.

You could consider default-exporting a closure-created object if you're really intent on avoiding `this` references, but I'll admit it's not exactly what you were looking for.
