### ISSUE TITLE
Circular inference failure (regression)

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#16512]
**TypeScript Version:**  2.5.0-dev.20170613

**Code**

I tried to make a simple repro but it failed. I had to add the annotation as follows. The previous code was working until 2.4.0-dev.20170606.

https://github.com/falsandtru/pjax-api/commit/f5dbc6d70a7f5c1ddf5cfe97d7130e5640c5e687

```diff
-  .extract(parser => (html: string) => Just(parser(html)));
+  .extract(parser => (html: string): Maybe<Document> => Just(parser(html)));
```

**Expected behavior:**

no error

**Actual behavior:**

```
TypeScript error: src/lib/html.ts(9,22): Error TS7024: Function implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.
```

**Comment by ahejlsberg** [comment]
I'm quite certain this relates to #16072 and #16305. Since we now make inferences from the return types of generic functions we will at times more eagerly resolve return statements and return expressions of lambdas. That appears to be what is happening here and I'm not sure there's much we can do about it.

**Comment by falsandtru** [comment]
Hm, okay thanks!
