### ISSUE TITLE
Union types could be reduced to their 'minimum valid' definitions

### ISSUE THREAD

**Issue by kujon** [Microsoft/TypeScript#16644]
**TypeScript Version:**  2.4.0

**Code**

```ts
// The following works no problem
type ExhaustiveType = Array<number | undefined>;

const test1 = (value: ExhaustiveType) => value.filter(v => v === 2);

/** Cannot invoke an expression whose type lacks a call signature. Type '{ (callbackfn: (this: void, value: number | undefined, index: number, array: (number | undefined)...' has no compatible call signatures. */
type ExcessiveType = number[] | Array<number | undefined>;

const test2 = (value: ExcessiveType) => value.filter(v => v === 2);

```

**Expected behavior:**
Both examples compile.

**Actual behavior:**
The latter example fails with `Cannot invoke an expression whose type lacks a call signature. Type '{ (callbackfn: (this: void, value: number | undefined, index: number, array: (number | undefined)...' has no compatible call signatures.`

**Explanation**
`ExhaustiveType` and `ExcessiveType` both represent exactly the same types. The latter is more explicit, and while in this particular example it might look silly, w/ more complex types and type aliases, being more explicit allows for more expressivity. IMHO TypeScript could at the time of defining `ExcessiveType`, 'reduce it down' to the `ExhaustiveType`. Alternatively (to preserve expressiveness e.g. in the IDE), the compiler could internally treat them as equivalent.

**Comment by michaeljota** [comment]
I'm sorry, I don't work here or anything, just wanted to test your code, cause it seems to me like `Array<number | undefined> !== number[]`. 
So I test it [here](http://www.typescriptlang.org/play/#src=%2F%2F%20The%20following%20works%20no%20problem%0D%0Atype%20ExhaustiveType%20%3D%20Array%3Cnumber%20%7C%20undefined%3E%3B%0D%0A%0D%0Aconst%20test1%20%3D%20(value%3A%20ExhaustiveType)%20%3D%3E%20value.filter(v%20%3D%3E%20v%20%3D%3D%3D%202)%3B%0D%0A%0D%0A%2F**%20Cannot%20invoke%20an%20expression%20whose%20type%20lacks%20a%20call%20signature.%20Type%20'%7B%20(callbackfn%3A%20(this%3A%20void%2C%20value%3A%20number%20%7C%20undefined%2C%20index%3A%20number%2C%20array%3A%20(number%20%7C%20undefined)...'%20has%20no%20compatible%20call%20signatures.%20*%2F%0D%0Atype%20ExcessiveType%20%3D%20number%5B%5D%20%7C%20Array%3Cnumber%20%7C%20undefined%3E%3B%0D%0A%0D%0Aconst%20test2%20%3D%20(value%3A%20ExcessiveType)%20%3D%3E%20value.filter(v%20%3D%3E%20v%20%3D%3D%3D%202)%3B )

However, I can't reproduce that issue you mention. It compiles both types as number[] (witch for me it's an unexpected behavior cause you explicit said that could be `undefined`).

Moreover, if you set `strictNullCheck` the error you said are getting threw, so that's a necessary thing to know.

**Comment by RyanCavanaugh** [comment]
The reduction of union types to a constituent that is a common supertype already happens. Perhaps something is missing in your example?

**Comment by kujon** [comment]
@RyanCavanaugh - Typescript is treating both of the types in my example differently (one's blowing up, another one doesn't). So it seems like I've managed to find some edge case maybe?

**Comment by jcalz** [comment]
Since `Array<number | undefined>` is not the same as `number[]`, then isn't this issue an instance of #1805?    
(If OP switches to `number[]` to `(number | undefined)[]` then the union is reduced and everything works.)

**Comment by kujon** [comment]
@jcalz - sure, but `number[] | Array<number | undefined>` is the same type as `Array<number | undefined>`

**Comment by jcalz** [comment]
No, not with `strictNullChecks` it isn't:
```ts
var x: number[] | Array<number | undefined>;
var x: Array<number | undefined>; // error: 
// Subsequent variable declarations must have the same type.  
// Variable 'x' must be of type '(number | undefined)[] | number[]', 
// but here has type '(number | undefined)[]'.
```

**Comment by jcalz** [comment]
Okay, so you're saying that `number[]` is a subtype of `(number | undefined)[]` and that the union should absorb the subtype.  I don't know that subtype collapsing is actually happening (I put this in #16386 but it's kind of languishing there).  Anyway, yeah, I think I get your point now @kujon.

**Comment by kujon** [comment]
@jcalz - precisely this. `(number | undefined)[]` is a super type of `number[]` so by definition, `super_type union sub_type == super_type`

**Comment by michaeljota** [comment]
This error only happens if you set `strictNullCheck`, so I don't think this is an error at all, cause it is checking that `(number | undefined) !== number` because, they are not the same if you are checking for null and undefined types.

However, this works as expected if the compiler is not in `strict` mode.

**Comment by jcalz** [comment]
@michaeljota no, this has nothing to do with undefined.  Let's try a different one:
```ts
var k = [1, 2, 3];
(k as number[]).filter(x => typeof x === 'string'); // fine
(k as (number | string)[]).filter(x => typeof x === 'string'); // fine
(k as number[] | (number | string)[]).filter(x => typeof x === 'string'); //same error
```

The typechecker is not absorbing `number[]` into `(number | string)[]`, even though all values of type `number[]` are also values of type `(number | string)[]`.

**Comment by kujon** [comment]
> however, arrays are mutable... so therefore number[] might not be a subtype of (number | string)[] if you intend to mutate anything.

If I understand the last message correctly, that would also mean that `number[]` is not `number[]` anymore, right?

**Comment by jcalz** [comment]
Maybe?  Since typescript is perfectly fine assigning a value of type `number[]` to a variable of type `(number|string)[]` but not vice versa, then I guess there is a subtype relationship there, even though you can do horrible things like
```ts
var a: number[] = [1,2,3];
var b: (number | string)[] = a;
b[0] = 'boom';
console.log(a[0]);
```

So forget my previous edit, I guess.

**Comment by masaeedu** [comment]
This is somewhat irrelevant to the issue at hand, but technically an `number[]` is not a subtype of `(number | undefined)[]`, because the latter supports inserting `undefined` members and the former doesn't. `Array<T>` is not covariant wrt `T`, although something like `ReadOnlyArray<T>` should be.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
