### ISSUE TITLE
Unable to use boolean valued promise as thenable construct in Typescript

### ISSUE THREAD

**Issue by adityagautam** [Microsoft/TypeScript#16669]
For some reason, I am unable to use a boolean valued promise as a thenable construct and I can't figure out why. The error message is _**TS2345value Argument of type '(value: boolean) => Promise<{}> | undefined' is not assignable to parameter of type '((value: boolean) => {} | IThenable<{}> | undefined'**_.

The source code is below with comment showing where the compile error occurs.

I have used this sort of mechanism in the pure JavaScript version of the framework I'm converting to Typescript without issues. It's only in Typescript that I have this problem.
 
```
public static refreshUntilElementIsPresent(element: ElementFinder, numberOfSeconds: number = 30000,
        refreshInterval: number = 5000): void {
    this.refreshElement(element, numberOfSeconds, refreshInterval);
}

protected static refreshElement(element: ElementFinder, numberOfSeconds: number = 30000, refreshInterval:
        number = 5000) {


    //This line throws the compile error
    element.isPresent().then(value => {
        if (!value) {
            if (numberOfSeconds <= 0) {
                return new wd.promise.Promise(function (resolve, reject) {
                    reject('Element cannot be found after expected retry numbers');
                })
            }
            browser.sleep(refreshInterval).then(() => {
                browser.refresh().then(() => this.refreshUntilElementIsPresent(element, numberOfSeconds -
                    (refreshInterval / 1000)));
            });
        }
    });
}
```

**Comment by DanielRosenwasser** [comment]
I don't know what the fix is because I don't have an isolated repro for the issue, and I don't know where you're getting the error, but I can guess.

Because TypeScript can't immediately figure out the type of the `Promise` you're constructing from its arguments, you'll need to add an explicit type argument to `new wd.promise.Promise`. Alternatively in 2.4 you'll be able to explicitly annotate the return type of `refreshElement`.

As a heads up, please use StackOverflow for "why isn't this working?" questions in the future.
