### ISSUE TITLE
Array<"foo"> inferred to ReadonlyArray<T> gives T=string, not T="foo"

### ISSUE THREAD

**Issue by r00ger** [Microsoft/TypeScript#16709]
**TypeScript Version:**  2.3.4 

**Code**

```ts
declare function id<T extends string>(list: Array<T>): Array<T>;
declare function readonlyId<T extends string>(list: ReadonlyArray<T>): ReadonlyArray<T>;

type LiteralType = "foo" | "bar";

const array: Array<LiteralType> = [];
const readonlyArray: ReadonlyArray<LiteralType> = [];

const foo: ReadonlyArray<LiteralType> = id(array);
const bar: ReadonlyArray<LiteralType> = readonlyId(array);
//    ~~~
// Type 'ReadonlyArray<string>' is not assignable to type 'ReadonlyArray<LiteralType>'.
//  Type 'string' is not assignable to type 'LiteralType'.const bar: ReadonlyArray<LiteralType>
const baz: ReadonlyArray<LiteralType> = readonlyId(readonlyArray);

```

**Expected behavior:**
`readonlyId(array)` returns `ReadonlyArray<LiteralType>`

**Actual behavior:**
`readonlyId(array)` returns `ReadonlyArray<string>`

**Comment by DanielRosenwasser** [comment]
Definitely seems questionable.

**Comment by andy-ms** [comment]
Just ran into this with string enums.
```ts
function first<T>(arr: ReadonlyArray<T>): T { return arr[0]; }
const enum E { A = "A" }
const es: E[] = [E.A];
const e: E = first(es); // Error, string not assignable to E
```

**Comment by sandersn** [comment]
This is a consequence of the weird type that `concat` has in Javascript, and how Typescript tries to infer type parameters for it. The type constraint `T extends string` obscures the problem because of an obscure fallback in the case that the inferred type isn't assignable to the type constraint.

Here's a smaller repro that shows the exact problem without the type constraint:

```ts
type A<T> = { concat(items: T | A<T>): void; }
type B<T> = { concat(items: T | B<T>): void; }
declare function deat<T>(at: A<T>): T;
type LiteralType = "foo" | "bar";
declare var blt: B<LiteralType>;

let foo: LiteralType = deat(blt);
//  ~~~
//  Type '"foo" | "bar" | B<LiteralType>' is not assignable to type 'LiteralType'.
```

Previously, since `"foo" | "bar" | B<LiteralType>` isn't assignable to `string`, type inference just used `string` instead since `T extends string`. Now we can see that inference got `T="foo" | "bar" | B<LiteralType>`.

Inference proceeds like this:

1. Look for candidates `B<LiteralType> ==> A<T>`. You might think this would trivially find `T=LiteralType`, but instead the inference proceeds structurally.
2. Look for inferences in the methods `concat(items: LiteralType | B<LiteralType>): void ==> concat(items: T | A<T>)`
3. Look for inferences in the parameters `LiteralType | B<LiteralType> ==> T | A<T>`
4. Look for inferences in the first half of the union: `LiteralType | B<LiteralType> ==> T`. This finds `T = LiteralType | B<LiteralType>`. :cry: 
5. Look for inferences in the second half of the union: `LiteralType | B<LiteralType> ==> A<T>`. But no inferences result from this.

Done. We got the incorrect inference `"foo" | "bar" | B<"foo" | "bar">` because of the way unions are inferred.

I'll think about whether pairwise comparison would be possible, since it's what most people expect to happen, but I'm not confident of success.

**Comment by sandersn** [comment]
After poking around about, @ahejlsberg and I found that my repro oversimplifies the problem. Because the real concat in both Array and ReadonlyArray take arrays, step 5 *is* able to find some inferences (also, step 5 happens before step 4, but this makes no difference). Problem is, they're bad ones.  

The structural comparison of "foo" to ReadonlyArray<T> finds a lot of methods that match, but instead of having parameters of type T, they have parameters of type string. Since string is a superclass of both "foo" and "bar", the resulting inference is T=string. 

We think that structural inference can be improved by skipping inference for any source type that doesn't have all the members of the target type. This source wouldn't be assignable anyway, so it's probably a low-quality source of inferences. This would rule out String as an inference source for ReadonlyArray specifically. 

I'll try it out tomorrow and see if it breaks anything else. 

Note that this would fix the repros posted originally but not the small one I just posted.

**Comment by DanielRosenwasser** [comment]
Is this not at least in part related to problems you found with `Promise` as well?

**Comment by sandersn** [comment]
@DanielRosenwasser which problems? The ones in definitely typed with `T | Promise<T>`?

Yes, specifically my repro highlights this problem. But the fix that @ahejlsberg and I came up with only fixes the original repro since it fails because of structural inference of `String ==> ReadonlyArray<T>`, not because of inference of `"foo" | "bar" | B<"foo" | "bar"> ==> T`. 

It *might* fix the promise problems too, but I'm going to run the fix on RWC/DT to find out.

**Comment by sandersn** [comment]
This fix is now in master. I merged manually after we reviewed the change offline.
