### ISSUE TITLE
Error when using Iterator with generic class

### ISSUE THREAD

**Issue by Pauan** [Microsoft/TypeScript#16730]
**TypeScript Version:**  2.5.0-dev.20170624

**Code**

```ts
class Foo<A> {
    public iter: Iterator<A>;
}

type BarString = "bar";

class Bar {
    public foo: Foo<BarString>;
}

type QuxString = BarString | "qux";

class Qux extends Bar {
    public foo: Foo<QuxString>;
}
```

**Expected behavior:**

No error.

**Actual behavior:**

I get this error:

```
foo.ts(13,7): error TS2415: Class 'Qux' incorrectly extends base class 'Bar'.
  Types of property 'foo' are incompatible.
    Type 'Foo<QuxString>' is not assignable to type 'Foo<"bar">'.
      Type 'QuxString' is not assignable to type '"bar"'.
        Type '"qux"' is not assignable to type '"bar"'.
```

If you remove `public iter: Iterator<A>;` then it compiles without any errors.

So it seems like `Iterator` is causing `Foo` to become covariant, even though normally it is bivariant.

I have some existing TypeScript code which uses a custom ad-hoc iteration system (which works fine). I ran into this error when trying to convert it to use ES6 Iterators.

**Comment by olegdunkan** [comment]
From spec:
_The type of an overriding property member must be assignable (section 3.11.4) to the type of the overridden property member, or otherwise a compile-time error occurs._

When there is no `iter` member in `Foo<A>` then `Foo<BarString>` and `Foo<QuxString>` are assignable because of `{}` (they are empty). If `iter` is defined in `Foo<A>` then property `foo` makes sense, overriding property member `foo` in `Qux` that is not assignable to overridden property member `foo` in `Bar`.
`QuxString` is not assignable to `BarString`.

```ts
var a: BarString;
var b: QuxString;
var y: Foo<BarString>;
var x: Foo<QuxString>;

a = b; //error
b = a;


y = x; //error
x = y;
```

**Comment by Pauan** [comment]
@olegdunkan You're right, this isn't specific to `Iterator`.

I need to do some more investigation on why it works fine with our custom iteration system.

**Comment by Pauan** [comment]
I did more investigation into this.

I have been unable to reproduce why our old iterator code works fine, but the new iterator code breaks.

In any case, it seems this isn't a bug in TypeScript, so I'm going to close this. Sorry about the noise.
