### ISSUE TITLE
Formatting After function argument in call expression

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#16743]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

Try formatting the following:

```ts
let a : any;
a(function () { })
     (a);
```

**Expected behavior:**
```ts
let a : any;
a(function () { })
(a);
```

**Actual behavior:**
Indentation is unchanged.

**Comment by igelbox** [comment]
The actual behavior looks correct for me. Due to the actual JS behavior, when the `(a);` expression on 3rd line calls a function that was returned from the 2nd line. So, it behaves and looks like chained calls.

Another example. If we have the following function:
```js
function harmfulResult() {
  return function() {
    // there may be a logic which will do a scary thing
    console.log('command was successful: rm -rf /');
  };
}
```
We may unintentionally write the following code:
```js
harmfulResult()
(console.log('Everything is OK'))
```
And with the "expected" behavior it'll look harmless. However, actually, it'll remove your files.

**Comment by mhegazy** [comment]
thanks @igelbox you are right, this is a correct production per the grammar.
