### ISSUE TITLE
interface stubbing for anonymous implementations

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#16755]
_From @tvald on June 23, 2017 22:31_

Similar to https://github.com/Microsoft/vscode/issues/7073, provide a code action to create stubs for an anonymous implementation of a type:

```ts
interface Foo {
  field: string,
  func(): void
}

const bar: Foo = {}
// expand above line into...
const bar: Foo = {
  field: 'string',
  func(): void {
    throw new Error('not yet implemented')
  },
}
```

Ideally, this would also be able to stub in the anonymous implementation of a function argument, but that would require inference of the interface being targeted for implementation:

```ts
function example(arg: Foo): void { }

example({})
// expand above line into...
example({
  field: string,
  func(): void {
    throw new Error('not yet implemented')
  },
}
```

_Copied from original issue: Microsoft/vscode#29363_

**Comment by bigaru** [comment]
I'd like to implement this issue. I estimate that it'll take about 2 weeks, at most 4 weeks. 

Can I use existing error code `Type '{}' is not assignable to type 'interfaceName'`?
Or should I rather create a new error code with more appropriate message? 
The last one will probably take more effort because the checker must be adapted accordingly, in order to show the new error message.
