### ISSUE TITLE
document meaning of trivia

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#1678]
Really for @DanielRosenwasser : https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API

I suspect its very similar to that of Roslyn compiler, if so the following might be helpful beginning of copy paste:

-----
Syntax trivia represent the parts of the source text that are largely insignificant for normal understanding of the code, such as whitespace, comments, and preprocessor directives.

Because trivia are not part of the normal language syntax and can appear anywhere between any two tokens, they are not included in the syntax tree as a child of a node. Yet, because they are important when implementing a feature like refactoring and to maintain full fidelity with the source text, they do exist as part of the syntax tree.

You can access trivia by inspecting a token’s LeadingTrivia or TrailingTrivia collections. When source text is parsed, sequences of trivia are associated with tokens. In general, a token owns any trivia after it on the same line up to the next token. Any trivia after that line is associated with the following token. The first token in the source file gets all the initial trivia, and the last sequence of trivia in the file is tacked onto the end-of-file token, which otherwise has zero width.

Unlike syntax nodes and tokens, syntax trivia do not have parents. Yet, because they are part of the tree and each is associated with a single token, you may access the token it is associated with using the Token property.

Like syntax tokens, trivia are value types. The single SyntaxTrivia type is used to describe all kinds of trivia.

**Comment by DanielRosenwasser** [comment]
Let me know what you think, pinging @mhegaz, @CyrusNajmabadi.

## Terminology

##### **Full Start/Token Start**

Tokens themselves have what we call a "full start" and a "token start". The "token start" is the more natural version, which is the position in file where the text of a token begins. The "full start" is the point at which the scanner began scanning since the last significant token. When concerned with trivia, we are often more concerned with the full start.

Function | Description
---------|------------
`ts.Node.getStart` | Gets the position in text where the first token of a node started.
`ts.Node.getFullStart` | Gets the position of the "full start" of the first token owned by the node.

#### **Trivia**

Syntax trivia represent the parts of the source text that are largely insignificant for normal understanding of the code, such as whitespace, comments, and even conflict markers.

Because trivia are not part of the normal language syntax (barring ECMAScript ASI rules) and can appear anywhere between any two tokens, they are not included in the syntax tree. Yet, because they are important when implementing a feature like refactoring and to maintain full fidelity with the source text, they are still accessible through our APIs on demand.

In general, a token owns any trivia after it on the same line up to the next token. Any trivia after that line is associated with the following token. The first token in the source file gets all the initial trivia, and the last sequence of trivia in the file is tacked onto the end-of-file token, which otherwise has zero width.

For most basic uses, comments are the "interesting" trivia, which can be fetched through the following functions:

Function | Description
---------|------------
`ts.getLeadingCommentRanges` | Returns ranges of comments between the first line break following the given position and the token itself.
`ts.getTrailingCommentRanges` | Returns ranges of comments until the first line break following the given position.

In the event that you are concerned with richer information of the token stream, `createScanner` also has a `skipTrivia` flag which you can set to `false`, and use `setText`/`setTextPos` to scan at different points in a file.

**Comment by danquirk** [comment]
Let's get content like this into a wiki page. We can add some more content under the Building Tools for Typescript header.

**Comment by DanielRosenwasser** [comment]
I've put it into the wiki page, still need some review on this content.

**Comment by mhegazy** [comment]
looks good. thanks @DanielRosenwasser. one thing that is different from the Roslyn notion of trivia, is we do not have trailing trivia. all triva in TypeScript is leading. so for instance
```TypeScript
var a; // comment
b;
```
The trivia list [" ", "//comment", "\n"] the leading trivia for the expression statement "b;".

**Comment by basarat** [comment]
Thanks! https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#full-starttoken-start closing
