### ISSUE TITLE
Bug: nested object lose intellisense when defined in union type

### ISSUE THREAD

**Issue by AlgusDark** [Microsoft/TypeScript#16781]
**TypeScript Version:**  2.4.1

**Code**

```ts
interface DisplayObject{
	flex?: boolean;
}

interface Show {
	isDisplay?: string | string | DisplayObject
}

var a: Show = {isDisplay: { /* toString and valueOf */ }}
```

**Expected behavior:**
```ts
interface DisplayObject{
	flex?: boolean;
}

interface Show {
	isDisplay?: string | string | DisplayObject
}

var a: Show = {isDisplay: { /* should show flex in the intellisense as key for the object */ }}
```

**Actual behavior:**
If we remove `string|string[]` (leaving only `isDisplay?: DisplayObject`), the intellisense is working as expected.

[Playground](http://www.typescriptlang.org/play/index.html#src=interface%20DisplayObject%7B%0D%0A%09flex%3F%3A%20boolean%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20Show%20%7B%0D%0A%09isDisplay%3F%3A%20DisplayObject%20%7C%20string%20%7C%20string%5B%5D%0D%0A%7D%0D%0A%0D%0Avar%20a%3A%20Show%20%3D%20%7BisDisplay%3A%20%7B%7D%7D)

**Comment by andy-ms** [comment]
Should have been fixed by #15541. It's working for me after installing `typescript@2.4.1`. Are you sure your editor services are using the latest TypeScript? The editor version may be different from what you have in your local `node_modules`. ([vscode](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions) instructions)

**Comment by AlgusDark** [comment]
@andy-ms it's working the example, thanks, I was using the built-in tsc from vscode.

But it's not working as I wanted on my project. I'm going to do some research on these, meanwhile, I'm going to close this.
![image](https://user-images.githubusercontent.com/818856/27619507-807a2284-5b88-11e7-98e2-10303ca47ce1.png)
*I don't want to get all those methods, and I know is possible, because it's working with react.d.ts, for example with `style={{/* intellisense show only the keys */}}`*

For reference, this is my project:
* [types](https://github.com/AlgusDark/bloomer/blob/master/src/bulma.tsx#L66)
* [ObjectInterface](https://github.com/AlgusDark/bloomer/blob/master/src/bulma.tsx#L73)
* [Interface that implements types | types[] |ObjectInterface](https://github.com/AlgusDark/bloomer/blob/master/src/bulma.tsx#L81)

**Comment by andy-ms** [comment]
In that case we are showing you the properties of `Array`. Since we have a structural type system, we can't tell just by looking at an interface whether it's meant to be implemented by an object literal.
It's possible that we could use some heuristic, such as putting types with the fewest properties first (as they are the easiest to implement with an object literal).

**Comment by AlgusDark** [comment]
Cool, that way it could be easier to know what are the types that you want people use.
Thanks!
