### ISSUE TITLE
SpreadElementExpression can introduce unexpected results in ES5/3

### ISSUE THREAD

**Issue by rbuckton** [Microsoft/TypeScript#1679]
There is a difference in behavior in spread element between ES6 and ES5/3. Given the following:
```TypeScript
var a: number[] = undefined;
var b = [1, ...a, 2];
```

In ES6 hosts, you get an error when `a` is spread into the array. FF Nightly throws a TypeError: "undefined has no properties".

In ES5/3 hosts you do not get an error, and instead get an unintended result:
```js
var a;
var b = [1].concat(a, [2]); // [1, undefined, 2];
```

I would expect our runtime behavior to roughly match the ES6 behavior.

**Comment by rbuckton** [comment]
We could emulate this behavior by changing the emit to instead be something like the following:
```js
var a = undefined;
var b = [1].concat(a.concat && a, [2]); // throws "TypeError: undefined has no properties" in FF Nightly
```

**Comment by ahejlsberg** [comment]
I wonder how much we care about preserving error behavior in down level code. I'd hate to generate cryptic code just to preserve an exception that likely isn't important.

**Comment by rbuckton** [comment]
It's less that we need to preserve specific error cases, but that the runtime semantics of our emit don't behave as expected. If we don't care about errors, we could instead emit the following, which doesn't introduce `undefined` in a spread:

```
var b = [1].concat(a || [], [2]);
```

If we do want equivalent runtime semantics to ES6, we need to emit something similar to the above, though I spoke with @DanielRosenwasser last week and a better emit (that throws if `a` is undefined) might be:
```
var b = [1].concat(typeof a.length && a, [2]);
```

**Comment by RyanCavanaugh** [comment]
This seems very hittable with optional parameters, e.g.:

```ts
function f(x?: any[]) {
  var g = [0, ...x];
  // ...
}

f();
```

This is extra subtle because `[...x, 0]` *would* throw in ES3/5, which might lull people into a false sense of security. Emitting code that would break at runtime if emitted in ES6 is really bad -- it means it's not safe to move code between projects that have different emit targets.

**Comment by rbuckton** [comment]
If you want to avoid cryptic emit, you might need to instead do something like:
```
if (a === void 0) throw new TypeError();
var b = [1].concat(a, [2]);
```

**Comment by ahejlsberg** [comment]
@rbuckton That won't work in an arbitrary expression context (at least not without a lot of complications).

One possibility is
```typescript
var b = [1].concat(a.slice(), [2]);
```
The slice method appears to be quite efficient on most VMs when returning the full array. Probably because the VMs implement copy-on-write semantics for arrays.

http://jsperf.com/new-array-vs-splice-vs-slice/63

Yet another possibility is
```typescript
var b = [1].concat((a[0], a), [2]);
```
They all do look cryptic though.

**Comment by rbuckton** [comment]
@ahejlsberg I think I prefer the `slice` implementation, I had considered it as well but was wary of the allocation cost. If it is efficient, it looks cleaner than the other approaches.

**Comment by DanielRosenwasser** [comment]
I like the `slice` idea. It's [definitely not as fast](http://jsperf.com/spread-emit-for-ts), but I don't really care since there's a clear workaround (just code the downlevel emit yourself instead of using a spread operator).

**Comment by ahejlsberg** [comment]
A better option is
```typescript
var b = [1].concat(a || null.concat, [2]);
```
This throws an exception when a is null or undefined and ensures that the exception message is the same as if a had been the first operand (i.e. the object on which concat was invoked).

**However...** the problem with this and any of the other solutions is that we're not checking whether `a` is actually an array (we only check for falsy). It may be reasonable not to do so if the static type of a is an array type (i.e. it's reasonable to trust the type system), but it isn't when `a` is of type any.

This takes us right down the rabbit hole of downlevel testing for array types--there basically is no correct _and_ efficient way to do so on ES3.

http://perfectionkills.com/instanceof-considered-harmful-or-how-to-write-a-robust-isarray/

I think this leaves us with the following options, none of which are great:

* Ignore the problem completely and simply state that when the operand of spread is not an array, the behavior differs from ES6. Properly written code will have to guard against non-arrays anyway as they throw exceptions on ES6.
* Throw on null or undefined, but otherwise trust the operand is an array (and differ from ES6 if it isn't). That's the middle ground of the solution above, but it seems like an odd place to land.
* Emit an even more thorough (and costlier) check.

Given that we care at least a little bit about performance, the best check we could emit that works for both ES3 and ES5 is
```typescript
var b = [1].concat(a.concat && a.splice ? a : null.concat, [2]);
```
This throws an exception if `a` is not an object that has a `concat` and `splice` method. Beyond that, we'd trust it is an array.

We could possibly emit
```typescript
var b = [1].concat(Array.isArray(a) ? a : null.concat, [2]);
```
when the emit target is ES5, but we'd still need the other check for ES3.

Of course we could turn this into some `__checkArray` helper function we inject, but I'm just not a fan of those.

My personal preference is to either do nothing or go with inlining the full check (including use of Array.isArray on ES5 targets).

**Comment by DanielRosenwasser** [comment]
> Ignore the problem completely

:+1: - I care about us erroring in the null-ish cases, but we don't provide guarantees about `any` anyway.  I don't think vexing over whether the user has provided us with an `any` typed `concat`-able is worth the worry or effort.

**Comment by ahejlsberg** [comment]
Just to be clear, I meant ignore the problem *for any type* of a spread expression (whether type any or an array type). I definitely don't want us to be in the type-directed emit business where we emit different patterns based on the static type. The emit should be the same no matter what the static type is or otherwise incremental scenarios like emit-on-save become very hard.

**Comment by ahejlsberg** [comment]
I suggest we close this one. I'm not sure how much of a real world problem this is and the suggested fixes seem worse than the problem itself.
