### ISSUE TITLE
Union type conflicts with overloaded function

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/TypeScript#16816]
**TypeScript Version:**  2.4.1

**Code**

```ts
type Foo = { bar: string };

declare function foos(f: Foo);
declare function foos(f: Foo[]);

function foos2(f: Foo | Foo[]) {
  foos(f);
  // Argument of type 'Foo | Foo[]' is not assignable to parameter of type 'Foo[]'.
  //  Type 'Foo' is not assignable to type 'Foo[]'.
  //    Property 'length' is missing in type 'Foo'.
}
```

**Expected behavior:**

`foos` accepts `Foo` and `Foo[]`. `foos2` accepts `Foo | Foo[]`. I think `foos2` can just pass its argument to `foos` without problems.

**Actual behavior:**

```
Argument of type 'Foo | Foo[]' is not assignable to parameter of type 'Foo[]'.
  Type 'Foo' is not assignable to type 'Foo[]'.
    Property 'length' is missing in type 'Foo'.
```

**Comment by jcalz** [comment]
I've [wondered](https://github.com/Microsoft/TypeScript/issues/16756#issuecomment-311453499) about unions/intersections of parameters to overloaded/generic functions before.  My guess is that it's a good thing to want but might be too expensive for the type checker to do this.  Can anyone link to a canonical issue for this type of thing?

Of course in your case you can work around this in any number of ways.  The best way is probably to declare the function to take `Foo | Foo[]` in the first place instead of overloading it.  

If you are trying to fix without redeclaring the function, you can of course cast it:
```ts
function foos2(f: Foo | Foo[]) {
  (foos as (f: Foo | Foo[]) => any)(f); // success
}
```

And in general, you can force TypeScript to notice that an overloaded or generic function can take a union:
```ts
var intersectFunction:
  <A1, R1, A2, R2> (func: ((a: A1) => R1) & ((a: A2) => R2)) => ((a: A1 | A2) => R1 | R2)
  = (func => func);

function foos2(f: Foo | Foo[]) {
  intersectFunction<Foo,any,Foo[],any>(foos)(f); // success
};
```

I agree it would be nice if TypeScript just noticed without being forced to.  It doesn't, because _________________________ (someone fill in the blank pls, thx!)

**Comment by RyanCavanaugh** [comment]
Tracked at #14107 and #1805.

What search terms did you use? I'd like to edit their titles so people can find them more easily

**Comment by jcalz** [comment]
If I search for "generic", "overload", "union", and "intersection", issue #14107 is in the top several results, so it was probably just myopia on my part.  Thanks!

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
