### ISSUE TITLE
Why isn't excess property checking occurring in the website's example?

### ISSUE THREAD

**Issue by softwhygo** [Microsoft/TypeScript#16814]
There is a question confusing me so much。
The tutorial on the site（http://www.typescriptlang.org）introduces the grammar  as follows:
`let x = () => ({name: "Alice"});
let y = () => ({name: "Alice", location: "Seattle"});

x = y; // OK
y = x; // Error because x() lacks a location property`
and there is a sentence explaining the above code：“The type system enforces that the source function’s return type be a subtype of the target type’s return type.”。It means that {name:”Alice”} is the subtype of {name:”Alice”,location:”seattle”}( obviously,has excess property)，but the typescript document tells us as follow:
"S is a subtype of a type T, and T is a supertype of S, if S has no excess properties with respect to T"
https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#3.11.3

**Comment by DanielRosenwasser** [comment]
If you check the spec, it links to [section 3.11.5: Excess Properties](https://github.com/Microsoft/TypeScript/blob/22f38b720cf7b56e766ac168617e744646fdcb6e/doc/spec.md#3115-excess-properties).

> A source type *S* is considered to have excess properties with respect to a target type *T* if
> 
> * ***S* is a fresh object literal type**, as defined below, and
> * *S* has one or more properties that aren't expected in *T*.
>
> ...
>
> The type inferred for an object literal (as described in section [4.5](#4.5)) is considered a ***fresh object literal type***. The freshness disappears when an object literal type is widened ([3.12](#3.12)) or is the type of the expression in a type assertion ([4.16](#4.16)).

So in the example, that object literal is widened when checking the type of the arrow function. That means that it loses "freshness".

The easy way to think about this is that excess property checks only occur when passing an object literal to something of a known type like the following:

```ts
let x = () => ({name: "Alice"});
let obj = x();
x = {name: "Alice", location: "Seattle"};
```

Here `x` has a known type, and the object literal starts off with a fresh type. Since `x` isn't a declaration site, we check if it's assignable to the type of `x` (which is `{ name: string }`) without any widening. Since the type is fresh, excess property checking occurs.

**Comment by softwhygo** [comment]
@DanielRosenwasser  thank you very much

**Comment by DanielRosenwasser** [comment]
You're welcome!
