### ISSUE TITLE
Type inference chooses incorrectly between overloads

### ISSUE THREAD

**Issue by DylanRJohnston** [Microsoft/TypeScript#16867]
Example

```
import * as SQS from 'aws-sdk/clients/sqs'

const _SQS = new SQS()

type Callback<E, R> = (e: E, r: R) => void
type NodeBack<A, E, R> = (a: A, c: Callback<E, R>) => any

function promisify<A, E, R>(f: NodeBack<A, E, R>): (a: A) => Promise<R> {
    return a => new Promise<R>((resolve, reject) => {
        f(a, (e, r) => e ? reject(e) : resolve(r))
    })
}


const foo = promisify(_SQS.receiveMessage)
```

Expected type of foo
```
(a: SQS.ReceiveMessageRequest) => Promise<SQS.ReceiveMessageResult>
```

Actual
```
(a: ((err: AWSError, data: SQS.ReceiveMessageResult) => void) | undefined) => Promise<{}>
```

The AWS SDK has two overloads from the recieveMessage function

```
receiveMessage(params: SQS.Types.ReceiveMessageRequest, callback?: (err: AWSError, data: SQS.Types.ReceiveMessageResult) => void): Request<SQS.Types.ReceiveMessageResult, AWSError>;

receiveMessage(callback?: (err: AWSError, data: SQS.Types.ReceiveMessageResult) => void): Request<SQS.Types.ReceiveMessageResult, AWSError>;
  /**
```

So when the generic types are being resolved, Typescript chooses the second overload assigning A to the callback type and assigning {} to E and R. Instead of using the overload that actually matches the `NodeBack<A, E, R>` type signature.

**Comment by DylanRJohnston** [comment]
Reordering the library definitions gives the desired result. Which is strange, I thought the overloads were checked in order?

**Comment by RyanCavanaugh** [comment]
Can you make the example self-contained, as is described in the issue template?

**Comment by DylanRJohnston** [comment]
Yeah sure, sorry.

```

interface Param {__brand: 'Param'}
interface Err {__brand: 'Err'}
interface Result {__brand: 'Result'}

declare class Foo {
    method(param: Param, callback?: (err: Err, data: Result) => void): void
    method(callback?: (err: Err, data: Result) => void): void
}


type Callback<E, R> = (e: E, r: R) => void
type NodeBack<A, E, R> = (a: A, c: Callback<E, R>) => any

function promisify<A, E, R>(f: NodeBack<A, E, R>): (a: A) => Promise<R> {
    return a => new Promise<R>((resolve, reject) => {
        f(a, (e, r) => e ? reject(e) : resolve(r))
    })
}

const foo = new Foo()

const fooMethodPromise = promisify(foo.method)
```
Expected inference for fooMethodPromise
```
const fooMethodPromise: (a: Param) => Promise<Result>
```
Actual
```
const fooMethodPromise: (a: ((err: Err, data: Result) => void) | undefined) => Promise<{}>
```

**Comment by DylanRJohnston** [comment]
Declaring the overloads for `Foo.method` in the opposite order gives the desired inference, but this seems to run counter to the logic of how overloads are chosen.

**Comment by ahejlsberg** [comment]
This is an effect of how type inference works. When inferring from the type of `foo.method` to the type `Nodeback<A, E, R>` the compiler has to relate two overloaded signatures in the source to a single overloaded signature in the target. The compiler can't perform overload resolution during inference (because inference is supposed to infer the types that overload resolution is subsequently based on), so it simply infers types by pairwise relating source and target signatures. When the lengths of the source and target signature lists are unequal, the excess *first* signatures of the longest list are ignored. So, in the example, the *last* overload in the source is related to the target signature. We favor the last signatures for inference because they are generally the *least* specific and therefore the *most* inclusive for inference.

Generally speaking, the business of inferring from overloaded signatures is quite speculative, so you're effectively running into the limit of what's possible here.

**Comment by DylanRJohnston** [comment]
Thanks for the explanation, the interaction between overloads and type inference makes sense. Though I'm not sure I follow "The length of the source and target signature lists", do you mean the number of function arguments or the number of generics?

**Comment by ahejlsberg** [comment]
@DylanRJohnston I mean the number of overloads in each function type.

**Comment by DylanRJohnston** [comment]
Right ok, so the only way to change the behaviour would be to change the overloading definition order in the library. Thank you for taking the time to look at this.
