### ISSUE TITLE
 Func with param of type 'keyof this' doesn't  resolve property of inherited class

### ISSUE THREAD

**Issue by aiiak** [Microsoft/TypeScript#16930]
**TypeScript Version:**  2.4.0 

**Code**

```ts
class base {
  public baseProp;
    check<TProp extends keyof this>(prop: TProp): boolean {
        return true;
    }
}

class test extends base {
    public inherited: string;

    constructor() {
      super();
        this.check('baseProp'); //ok
        this.check('inherited'); // error 'inherited' is not assignable to parameter of type keyof this
    }    
}

```

**Expected behavior:**
no error

**Comment by rbuckton** [comment]
@sandersn can you take a look?

**Comment by sandersn** [comment]
`checkTypeArguments` calls `getTypeWithThisArgument` on `TProp`'s constraint after instantiating it, but neither the instantiation nor adding the `this` argument correctly update `keyof this` to have `this=Test` instead of `this=Base`. The instantiation should maybe take place somewhere else, I'm not sure. Fixing it just for `checkTypeArguments` does fix this particular bug, though.

**Comment by sandersn** [comment]
Turns out that the check for usage of `this` didn't account for type parameters, meaning that the compiler just re-used `Base.check` for `Test.check`, which is incorrect.

**Comment by sandersn** [comment]
In the meantime, `<TProp extends keyof this>(prop: TProp)` is equivalent to `(prop: keyof this)` (which is probably why this bug wasn't found in the two years since `this` was added).
