### ISSUE TITLE
Changes in Angular component is not transpiled to js

### ISSUE THREAD

**Issue by dobrinsky** [Microsoft/TypeScript#16948]
I am developing my first ASP.NET Core application with Angular 2.

The application must have individual user access. Since there is no template in Visual Studio 2017 for Angular applications I generated an Angular project in Powershell with Yoman, opened it in another Visual Studio and copied all the Angular files and folders into my normal Visual Studio project which has the individual user access template generated.

I was able to make Angular work in my project. The three default pages generated by Yoman appear and work. The second one is a page with an increment button and variable. The problem is that if I change the increment in the "counter.component.ts" from this.currentCount++; to this.currentCount+=3; for example, the change is not reflected in the main-client.js file in the dist folder.

I have added the Target lines in the .csproj file and I do not know how to proceed.

What other options are there?

This is what I have https://1drv.ms/u/s!AvPiv6aM2fzRepKV9J_F0-387Zc

I have added "compileOnSave": true and it still doesn't work

Thank you very much for your help!

**Comment by mhegazy** [comment]
it is not clear from the description what is going on here. i can not seem to access the repro project. if the edit you mention is in a non-ts file, then what you are seeing is expected, since the compile-on-save feature  is only aware of TS files. in this case you would need to use some other build/watch tool that can trigger your angular project build on edits.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
