### ISSUE TITLE
Type inference for anonymous callback function arguments

### ISSUE THREAD

**Issue by ssynix** [Microsoft/TypeScript#16950]
**TypeScript Version:**  2.4.1

Demonstration in [TypeScript playground](http://tinyurl.com/y7aexy2t) (with `noImplicitAny`):
```typescript
type Func<T1> = (arg1: T1) => void;

function executor<T1>(func: Func<T1>, arg1: T1) { func(arg1); };


function works(num: number) { }

executor(works, 3); // ✅
executor(works, 'sds'); // ✅


function nope(callback: (num: number) => void) { }

executor(nope, 3); // ✅
executor(nope, (num) => { }); // ❌ (num: any)

const callback: Func<number> = (num) => { }; // ✅
```

**Expected behavior:**
TypeScript should infer the lambda argument type from the type of the callback parameter (as it does in the last line).

**Actual behavior:**
I have to manually specify the types of the lambda function arguments. I ran into a more complicated version of this error using `redux-saga`, and the code is much more verbose than it should be when one of the arguments is a callback function.

**Comment by yuit** [comment]
After some investigation  I think this may be the language service issue because when parameter type is specify as `string`, we get an error message
```ts
executor(nope, (num: string) => { });
```

[Playground ](https://www.typescriptlang.org/play/#src=type%20Func%3CT1%3E%20%3D%20(arg1%3A%20T1)%20%3D%3E%20void%3B%0D%0A%0D%0Afunction%20executor%3CT1%3E(func%3A%20Func%3CT1%3E%2C%20arg1%3A%20T1)%20%7B%20func(arg1)%3B%20%7D%3B%0D%0A%0D%0A%0D%0A%0D%0Afunction%20works(num%3A%20number)%20%7B%20%7D%0D%0A%0D%0Aexecutor(works%2C%203)%3B%20%2F%2F%20%E2%9C%85%0D%0Aexecutor(works%2C%20'sds')%3B%20%2F%2F%20%E2%9C%85%0D%0A%0D%0A%0D%0A%0D%0A%0D%0Afunction%20nope(callback%3A%20(num%3A%20number)%20%3D%3E%20void)%20%7B%20%7D%0D%0A%0D%0Aexecutor(nope%2C%203)%3B%20%2F%2F%20%E2%9C%85%0D%0Aexecutor(nope%2C%20(num)%20%3D%3E%20%7B%20%7D)%3B%20%2F%2F%20%E2%9D%8C%0D%0A%0D%0Aconst%20callback%3A%20Func%3Cnumber%3E%20%3D%20(num)%20%3D%3E%20%7B%20%7D%3B%20%2F%2F%20%E2%9C%85#src=type%20Func%3CT1%3E%20%3D%20(arg1%3A%20T1)%20%3D%3E%20void%3B%0D%0A%0D%0Afunction%20executor%3CT1%3E(func%3A%20Func%3CT1%3E%2C%20arg1%3A%20T1)%20%7B%20func(arg1)%3B%20%7D%3B%0D%0A%0D%0A%0D%0A%0D%0Afunction%20works(num%3A%20number)%20%7B%20%7D%0D%0A%0D%0Aexecutor(works%2C%203)%3B%20%2F%2F%20%E2%9C%85%0D%0Aexecutor(works%2C%20'sds')%3B%20%2F%2F%20%E2%9C%85%0D%0A%0D%0A%0D%0A%0D%0A%0D%0Afunction%20nope(callback%3A%20(num%3A%20number)%20%3D%3E%20void)%20%7B%20%7D%0D%0A%0D%0Aexecutor(nope%2C%203)%3B%20%2F%2F%20%E2%9C%85%0D%0Aexecutor(nope%2C%20(num%3A%20string)%20%3D%3E%20%7B%20%7D)%3B%20%2F%2F%20%E2%9D%8C%0D%0A%0D%0Aconst%20callback%3A%20Func%3Cnumber%3E%20%3D%20(num)%20%3D%3E%20%7B%20%7D%3B%20%2F%2F%20%E2%9C%85#src=type%20Func%3CT1%3E%20%3D%20(arg1%3A%20T1)%20%3D%3E%20void%3B%0D%0A%0D%0Afunction%20executor%3CT1%3E(func%3A%20Func%3CT1%3E%2C%20arg1%3A%20T1)%20%7B%20func(arg1)%3B%20%7D%3B%0D%0A%0D%0A%0D%0A%0D%0Afunction%20works(num%3A%20number)%20%7B%20%7D%0D%0A%0D%0Aexecutor(works%2C%203)%3B%20%2F%2F%20%E2%9C%85%0D%0Aexecutor(works%2C%20'sds')%3B%20%2F%2F%20%E2%9C%85%0D%0A%0D%0A%0D%0A%0D%0A%0D%0Afunction%20nope(callback%3A%20(num%3A%20number)%20%3D%3E%20void)%20%7B%20%7D%0D%0A%0D%0Aexecutor(nope%2C%203)%3B%20%2F%2F%20%E2%9C%85%0D%0Aexecutor(nope%2C%20(num%3A%20string)%20%3D%3E%20%7B%20%7D)%3B%20%2F%2F%20%E2%9D%8C%0D%0A%0D%0Aconst%20callback%3A%20Func%3Cnumber%3E%20%3D%20(num)%20%3D%3E%20%7B%20%7D%3B%20%2F%2F%20%E2%9C%85#src=type%20Func%3CT1%3E%20%3D%20(arg1%3A%20T1)%20%3D%3E%20void%3B%0D%0A%0D%0Afunction%20executor%3CT1%3E(func%3A%20Func%3CT1%3E%2C%20arg1%3A%20T1)%20%7B%20func(arg1)%3B%20%7D%3B%0D%0A%0D%0A%0D%0A%0D%0Afunction%20works(num%3A%20number)%20%7B%20%7D%0D%0A%0D%0Aexecutor(works%2C%203)%3B%20%2F%2F%20%E2%9C%85%0D%0Aexecutor(works%2C%20'sds')%3B%20%2F%2F%20%E2%9C%85%0D%0A%0D%0A%0D%0A%0D%0A%0D%0Afunction%20nope(callback%3A%20(num%3A%20number)%20%3D%3E%20void)%20%7B%20%7D%0D%0A%0D%0Aexecutor(nope%2C%203)%3B%20%2F%2F%20%E2%9C%85%0D%0Aexecutor(nope%2C%20(num%3A%20string)%20%3D%3E%20%7B%20%7D)%3B%20%2F%2F%20%E2%9D%8C%0D%0A%0D%0Aconst%20callback%3A%20Func%3Cnumber%3E%20%3D%20(num)%20%3D%3E%20%7B%20%7D%3B%20%2F%2F%20%E2%9C%85#src=type%20Func%3CT1%3E%20%3D%20(arg1%3A%20T1)%20%3D%3E%20void%3B%0D%0A%0D%0Afunction%20executor%3CT1%3E(func%3A%20Func%3CT1%3E%2C%20arg1%3A%20T1)%20%7B%20func(arg1)%3B%20%7D%3B%0D%0A%0D%0A%0D%0A%0D%0Afunction%20works(num%3A%20number)%20%7B%20%7D%0D%0A%0D%0Aexecutor(works%2C%203)%3B%20%2F%2F%20%E2%9C%85%0D%0Aexecutor(works%2C%20'sds')%3B%20%2F%2F%20%E2%9C%85%0D%0A%0D%0A%0D%0A%0D%0A%0D%0Afunction%20nope(callback%3A%20(num%3A%20number)%20%3D%3E%20void)%20%7B%20%7D%0D%0A%0D%0Aexecutor(nope%2C%203)%3B%20%2F%2F%20%E2%9C%85%0D%0Aexecutor(nope%2C%20(num%3A%20string)%20%3D%3E%20%7B%20%7D)%3B%20%2F%2F%20%E2%9D%8C%0D%0A%0D%0Aconst%20callback%3A%20Func%3Cnumber%3E%20%3D%20(num)%20%3D%3E%20%7B%20%7D%3B%20%2F%2F%20%E2%9C%85#src=type%20Func%3CT1%3E%20%3D%20(arg1%3A%20T1)%20%3D%3E%20void%3B%0D%0A%0D%0Afunction%20executor%3CT1%3E(func%3A%20Func%3CT1%3E%2C%20arg1%3A%20T1)%20%7B%20func(arg1)%3B%20%7D%3B%0D%0A%0D%0A%0D%0A%0D%0Afunction%20works(num%3A%20number)%20%7B%20%7D%0D%0A%0D%0Aexecutor(works%2C%203)%3B%20%2F%2F%20%E2%9C%85%0D%0Aexecutor(works%2C%20'sds')%3B%20%2F%2F%20%E2%9C%85%0D%0A%0D%0A%0D%0A%0D%0A%0D%0Afunction%20nope(callback%3A%20(num%3A%20number)%20%3D%3E%20void)%20%7B%20%7D%0D%0A%0D%0Aexecutor(nope%2C%203)%3B%20%2F%2F%20%E2%9C%85%0D%0Aexecutor(nope%2C%20(num%3A%20string)%20%3D%3E%20%7B%20%7D)%3B%20%2F%2F%20%E2%9D%8C%0D%0A%0D%0Aconst%20callback%3A%20Func%3Cnumber%3E%20%3D%20(num)%20%3D%3E%20%7B%20%7D%3B%20%2F%2F%20%E2%9C%85): note modificataion on line18

**Comment by ahejlsberg** [comment]
This is working as intended. In the example marked ❌ above, the *declared* type of the `arg1` parameter isn't a function type and therefore we don't perform contextual typing of the arrow function argument. It isn't until *after* we've performed type inference that we learn that `T1` is a function type, but at that point contextual typing has already taken place.

**Comment by JsonFreeman** [comment]
See #1449, I think it's the same issue.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
