### ISSUE TITLE
Method overloading in interfaces using constraints not working with inheritance

### ISSUE THREAD

**Issue by 6ruce** [Microsoft/TypeScript#16951]
**TypeScript Version:**  2.3.3

Apparently, I'm trying to overload same interface method in child interface, and expect to get the same overloading as in the range of the same interface. But it seems like all overloads from parent interface are hidden by child overload.
Also, I've tried to reproduce this in TS Playground so I believe this is not version dependent.

**Code**

```ts
type AConstraint = { fieldA: number };
type BConstraint = { fieldB: number };

interface A {
    method<T>(map: (a: number) => T): T;
    method<T extends AConstraint>(map: (a: number) => T): T;
}

interface B {
    method<T extends BConstraint>(map: (a: number) => T): T;
}

(a: A, b: B) => {
    a.method((p) => { return 3; });
    a.method((p) => { return { fieldA: 3 } });

    b.method((p) => { return 3; }); // Error 1
    b.method((p) => { return { fieldA: 3 } }); // Error 2
    b.method((p) => { return { fieldB: 3 } });
};
```

**Expected behavior:**
Compiler resolves overloads from parent interface

**Actual behavior:**
First two ```b.method``` calls throws errors

> (1) Argument of type ```(p: number) => number``` is not assignable to parameter of type ```(a: number) => BConstraint```. Type ```number``` is not assignable to type ```BConstraint```
> (2) Argument of type ```(p: number) => {fieldA: number;}``` is not assignable to parameter of type ```(a: number) => BConstraint```. Type ```{fieldA: number;}``` is not assignable to type ```BConstraint```

**Comment by RyanCavanaugh** [comment]
Are you missing an `extends A` clause in this example?

See #10229 and other similar issues. If you redeclare a method in a derived type, the parent signatures aren't copied down automatically.

**Comment by 6ruce** [comment]
Yes, I forgot to add extents in the example but the result is the same.
It's pity that there is no `fast` solution as far as I understand.

**Comment by nomaed** [comment]
Is this the same issue as what I'm experiencing?

```ts
interface IBaseService {
  doSomething(action: 'start', callback: () => void);
  doSomething(action: 'end', callback: () => void);
}

// Error for this interface due to type mismatching of 'start' and 'end'
interface ISpecificService extends IBaseService {
  doSomething(action: 'start', callback: (time: number) => void);
}
```
See in [Playground](https://www.typescriptlang.org/play/#src=interface%20IBaseService%20%7B%0D%0A%20%20doSomething(action%3A%20'start'%2C%20callback%3A%20()%20%3D%3E%20void)%3B%0D%0A%20%20doSomething(action%3A%20'end'%2C%20callback%3A%20()%20%3D%3E%20void)%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20ISpecificService%20extends%20IBaseService%20%7B%0D%0A%20%20doSomething(action%3A%20'start'%2C%20callback%3A%20(time%3A%20number)%20%3D%3E%20void)%3B%0D%0A%7D%0D%0A)

Using a new argument type results in pretty much the same error, also if I provide a wider option with the `action` argument as `string`, it still errors out.
```ts
interface IBaseService {
  doSomething(action: 'start', callback: () => void);
  doSomething(action: 'end', callback: () => void);
  // doSomething(action: Function, callback: Function);
}

interface ISpecificService extends IBaseService {
  doSomething(action: 'something-else', callback: (time: number) => void);
}
```
See in [Playground](https://www.typescriptlang.org/play/#src=interface%20IBaseService%20%7B%0D%0A%20%20doSomething(action%3A%20'start'%2C%20callback%3A%20()%20%3D%3E%20void)%3B%0D%0A%20%20doSomething(action%3A%20'end'%2C%20callback%3A%20()%20%3D%3E%20void)%3B%0D%0A%20%20%2F%2F%20doSomething(action%3A%20Function%2C%20callback%3A%20Function)%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20ISpecificService%20extends%20IBaseService%20%7B%0D%0A%20%20doSomething(action%3A%20'something-else'%2C%20callback%3A%20(time%3A%20number)%20%3D%3E%20void)%3B%0D%0A%7D%0D%0A)

Is there no way to achieve what I'm trying to do?
In my case, I have an EventEmitter with a method `on(event: string, callback: Function): Function;` and I want to implement this emitter in a certain class that has specific events, for which I want to specify type hints for the callback format instead of just `Function`.
