### ISSUE TITLE
Function with empty object type parameter assignable to functions accepting more specific type

### ISSUE THREAD

**Issue by RocketSwine** [Microsoft/TypeScript#16971]
TypeScript Version:  2.4.1

This code shows the error that isn't picked up:
```
var numToString: ( x: number ) => string
var objToString = ( x: {} ) => x.toString();
numToString = objToString; // No compiler error, but should be: Type '{}' is not assignable to type 'number'
```

**Comment by kitsonk** [comment]
Event with weak type detection in 2.4.1 an empty object `{}` in a argument position essentially equates to `any`.  You would need something else, like `object` or `{ [key: string]: value; }` to make it not assignable.  I am not 100% sure of the inner workings of why this is with the type system, but it has to do with arguments being checked in a co-variant manner, I believe.

**Comment by andy-ms** [comment]
`{}` is the type of all values except `null` and `undefined`. So, `const x: {} = 0;` is valid.
Since `objToString` will accept a number, it's valid to use `objToString` where a `numToString` is expected.
Unfortunately, it's *not* valid to assign `objToString = numToString`, since `numToString` can't accept non-numbers but `objToString` is supposed to; but TypeScript will allow it because functions are checked bivariantly.
See also: #10717, #12498, #9825, #16735, #14973
