### ISSUE TITLE
Suggestion: multi-file external modules

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#17]
Support compiling multiple input .ts files into one external module.

Need to determine exactly how the module boundaries are defined when doing this.

**Comment by csnover** [comment]
@xealot I agree that “option 1” doesn’t make sense. In the context of how all the module loaders work today and how the default [Web loader](http://whatwg.github.io/loader/) ([not ES6 any more!](https://github.com/rwaldron/tc39-notes/blob/master/es6/2014-09/sept-25.md#loader-pipeline)) is planned to work, external modules aren’t combined that way for consumption. You’re also right there needs to be a way to change what default library/libraries are loaded when compiling, as lib.d.ts doesn’t set up an appropriate environment for a lot of development.

**Comment by marcuswhit** [comment]
+1 This is a huge issue for large modular projects, only currently solvable with a lot of plumbing and hacks.  Is this anywhere on the TS team's radar?

**Comment by csnover** [comment]
@marcuswhit I am not on the TS team but I am working on a prototype using the new language services in TS 1.4.

**Comment by fdecampredon** [comment]
For the purpose of generating a declaration for an entire commonjs module composed of multiple one I created a (little script)[https://github.com/fdecampredon/typescript-project-services/blob/master/scripts/concat-declaration.js] that does the job, hope it can helps

**Comment by csnover** [comment]
Per my previous comment, a prototype is available at https://github.com/sitepen/dts-generator for bundling multiple modules from a package together into a single d.ts for distribution using the language services. There are a few known issues, particularly in the requirements for compiling and running (the services in 1.4 don’t expose some important APIs), but I didn’t correct those yet since it’s just intended to be a proof of concept that the TS team can look at for this proposal. However, if it is useful to you, please feel free to use it and submit patches.

**Comment by mtraynham** [comment]
@csnover I tried your generator.  Seems to be very similar to https://github.com/TypeStrong/dts-bundle (might be some obvious differences that I missed).

The TypeScript compiler seems to work correctly for both of these projects.  Webstorm on the other hand, not so much.  It doesn't resolve class properties on import/export of external modules.  I havn't tried this with Visual Studio.

Driver:
```
import module = require('test-module');
var x: module.Foo = new module.Foo();
console.log(x.name);
```

Doesn't work:
```
declare module 'test-module/Foo' {
    class Foo {
        public name: string;
    }
    export = Foo;
}
declare module 'test-module' {
    export import Foo = require('module/Foo');
}
```

Works:
```
declare module 'test-module' {
    class Foo {
        public name: string;
    }
    export = Foo;
}
```

**Comment by csnover** [comment]
@mtraynham Yes, primarily the difference is that dts-bundle doesn’t use the language services; instead, it does a bunch of regexp stuff, which is bad. I would have just submitted dts-generator as a replacement to that project but there are a variety of reasons why that wasn’t possible.

However I do want to note that the code you wrote there isn’t the same; the “works” code couldn’t possibly work with that “driver” code unless WebStorm is terminally broken as it’s exporting `Foo` as the value of 'test-module', not as a property of the module.

**Comment by mtraynham** [comment]
@csnover awww, you know, you are right...

**Comment by csnover** [comment]
`export import Foo = require('Foo');` is equivalent to this in CommonJS:

```js
var Foo = require('Foo');
exports.Foo = Foo;
```

`import Foo = require('Foo'); export = Foo;` is equivalent to this in CommonJS:

```js
var Foo = require('Foo');
module.exports = Foo;
```

**Comment by mtraynham** [comment]
Thanks, that clears up a few things... I think I was getting confused with the `grunt-ts` export transformer, which generates exports for you in the form:
```
import Foo_file = require('Foo');
export var Foo = Foo_file;
```
The .d.ts generation for this (generated by TypeScript) then looks like:
```
import Foo_file = require('Foo');
export declare var Foo: typeof Foo_file;
```
I think this has some weird consequences down the line when you use it with `dts-bundle` or your own `dts-generator`.

**Comment by csnover** [comment]
In bb307f81639b2bc29a86aef5f92492e38e88ba67 the functionality that dts-generator used to get access to emit files was removed. What is the intended replacement functionality?

**Comment by mhegazy** [comment]
@csnover yes, we moved emit to program.emit. that is not going to help you though. we should expose emitFile, getEmitResolver, and possibly getEmitHostFromProgram in the .d.ts. that should be fairlly simple, just a change to the jake file. i have logged  #2217 to track it.

**Comment by csnover** [comment]
@mhegazy I seem to be able to do what I need to do with just `program.emit` and don’t need those others. https://github.com/SitePen/dts-generator/commit/0be96b6f064cfb88558ba93d18d42f9e235c232f

I do need #2139 to land sooner than later though since declaration emits are broken right now with ES6 imports. :)

**Comment by ToddThomson** [comment]
https://github.com/ToddThomson/tsproject/commit/4979240232f0237e1a321e90a1e3c22debaa650e

Still testing, but the build directory in the provided sample shows single file declaration.

**Comment by niemyjski** [comment]
+1, 1.5 cannot ship without this

**Comment by niemyjski** [comment]
I was able to get bundling working on my [project](https://github.com/exceptionless/Exceptionless.javascript)! It use ES6 Modules and bundles using [TSProject](https://github.com/ToddThomson/tsproject)!!!

**Comment by lazutkin** [comment]
:+1:

**Comment by comdiv** [comment]
My suggestion is that this scenario is available if you build your solution in single file:
1) Pure typescript modules as source (they allow simple merging)
2) Using --out MODULENAME.js --module AMD
For now it generates something like this:
var MODULENAME;
(function (MODULENAME) {
   //BODY OF FILE 1
})(newthe || (newthe = {}));
var MODULENAME;
(function (MODULENAME) {
   //BODY OF FILE 2
})(newthe || (newthe = {}));

So as u see - we got valid single JS module that can be used with AMD with shim:{MODULENAME:{exports:"MODULENAME"}}

My suggestion to allow TS generate fully complicated AMD/UMD modules:

file A:
///<reference path="lib1.d.ts"/>
module X {
  export class A{}
}
file B:
///<reference path="lib2.d.ts"/>
module X {
   export class B{}
}
file C:
///<amd-dependency path="lib1"/>
///<amd-dependency path="lib2"/>
export module X;

1 Compiler should fail if TWO export module with same name exist
2 Compiler should add export module definition in tail of --out FILE :
define("X",["require","exports","lib1","lib2"],function(){
      exports.X = X;
});

What is the result:
1) Sources of module are TypeScript-style - no order, no dependency - simple merging
2) Export AMD module as result of compilation

It can be cause some issues to provide "lib1","lib2" instances to internal module, but i think it can be solved with "export initializer" something like that:
///<amd-dependency path="lib1"/>
///<amd-dependency path="lib2"/>
export module X(lib1, lib2) {
      A.setServices(lib1,lib2);
}
So in result it must generate something like that:
define("X",["require","exports","lib1","lib2"],function(require,exports,lib1,lib2){
       X.A.setServices(lib1,lib2);
       exports.X = X;
});
So we can provide any module-level initialization module on real phisical module binding.

For now i do it manually and then minimize.

**Comment by AsherBarak** [comment]
Why not consider tooling? Group .ts files into modules using directory structure or comments or whatever code-indifferent mechanism, and have the tool rewrite the imports and the exports into a new .ts file to keep everything going. In case of conflicts, emit errors.
Tooling should also emit source maps. 
This eliminates the need for braking changes in the code and allows room for errors in the merging process.
 As all current and proposed modules loading relies on files location, and loading files is something you might want to manage to balance files sized with number of calls, this will keep with same principal while separating the development directory structure from the delivered modules structure.

**Comment by kripod** [comment]
# Proposal suggestion
(Based on #5085)

_Inspired by the ```@import``` function of SASS._

I would like to propose a mechanism for creating partial files, which are not compiled by default, but embedded into files which reference them. It's just like bundling, but with less hassle and in a more unified approach.

As a brief example, suppose that we have 4 files:

- index.ts
- user.ts
- _auth.ts
- _position.ts

The ```index.ts``` and ```user.ts``` files can reference contents of a partial file by using simple imports. For example, if we want ```index.ts``` to reference ```_auth.ts``` and ```_position.ts```, use the following code in the non-partial ```index.ts``` file:

```
import auth = require('auth');
import position = require('position');
```

The content of partial files should be copied and instantly evaluated in their container file. For instance, whether we would also like to use the ```_position.ts``` partial file in ```user.ts```, use an import just like above:

```
import position = require('position');
```

Although this may seem like a regular import, it's basically an include function which copies the partial file's full content at the place desired. That means, partial files should not be reused in multiple containers, but should be used for code organisation purposes. When both ```index.ts``` and ```user.ts``` are referenced in a HTML file, the content of ```_position.ts``` will be duplicated and inserted into the 2 containers separately.

Last but not least, in order to keep backwards compatibility, there should be a tsconfig setting (```compilerOptions.ignorePartialFiles```) which could be set to true in order to keep compiling files which start with a ```_```.

**Comment by ToddThomson** [comment]
@kripod https://github.com/toddthomson/tsproect already does this. It adds bundling to the tsconfig.json file and will build a bundle from modules using ES6 syntax.

**Comment by kripod** [comment]
@ToddThomson I have seen that project before proposing my specification, but bundling from a single file seems to be overcomplicated for such a little effect.

**Comment by ToddThomson** [comment]
@kripod No that is not how it works. Your Typescript ES6 exported files are defined in separate files. When you specify a bundle it works out all the dependencies and build a single bundled ts, js and d.ts. Take a look at the sample on the github tsproject repository.

**Comment by mironx** [comment]
I am in the same situation as @park9140 and I am little tried. 
I trayed the same solution (and also others). 
I have more experience in C# and Java and probably my notation about how it could works has influence of it. 

But I dream about something similar to .net assembly which could have multiple files and I could load it.

Thant means would be good have that java script external module be like assembly.
Even I our external module is big we could use in it namespaces [Namespace in module]. 
All files "are compiled" to one file. We could tell compilator: 
ok: it is my new super external module and it consists these 350 files. [Tell that this files build module]
And these elements please make available see by other modules [Export Items]
Between files should be possibility to have references [Reference inside module].  
And supporting compilation exception when e.g. in one module would define
two classes with the same name [Supporting Compilation Exception].

That meas we could indemnify 4 issues: 
*Namespace in module
*Tell that this files build module
*Export Items
*Reference inside module
*Supporting Compilation Exception


Generally I would like to focus on developing business logic, provide solution than
focus on compilation process.

**Comment by mhegazy** [comment]
@mironx have you looked at [browserify](http://browserify.org/) or [webpack](https://webpack.github.io/)?

**Comment by mironx** [comment]
@mhegazy 
Thank your encouragement. I had know this tool and I had afraid bit of configuration - that it could be to complicated.

Thanks your encouragement I the ice has broken up :-) and
I have spend several weeks with webpack and also systemjs. 

# What I would like to achieve?
But first what I would describe what I need to achieve.

I would like to create my suite of component which would exists in java script file.
E.g.:
* lib1.js, lib.d.ts
* lib2.js, lib.d.ts
* lib3.js, lib.d.ts
     this library could be depend on angular, reactjs, kendo and others. 

apps
and apps which could consume this libraries and could have own libraries.

* app1.js 
      libapp1.js
      libapp2.js
     and dependencies:  lib1.js with lib1.d.ts, angular etc....
* app2.js ... silimar like app1

It would be like: software suite, framework or components.

1. One library could contain many external modules.
2. app  it is just main js file 

# My adventure with webpack
I have tested webpack with grunt.  I create GruntFile.js which could be use by each project.
This GruntFile.js use project.json which indicate how to process structure of project (solution line in Visual Studio)

## Problems
* a) I could join js files (after compilation of typescript) but I have problem with generated one
  type script date type file **d.ts** for library
 As I wrote I would like to have references between libraries - I need also **d.ts**
* b) I have problem to dynamic loading js to achieve the same as in systemjs.
  That mean to have one file in html. 
* c) And with references. because I had to use external  -   I don't wont bundle vendors and library to    one file.

# Summarization
It this moment the biggest problem for me is  point "a". 

**Main requriment**
I could compile whole libraries for each app but I need that my library work as plugin.
Thant means for existing application someone else could provide library as plugin
which extend functionality. This library would implement app interfaces to extend functionality.

## New version of typescript compilator
I looked on roadmap of typescript compilator and I noticed interesting issues:
* **2.1** Support for project references
* **2.0** Improve lib.d.ts modularity
* **1.8** Concatenate module output with --outFile (only for amd and commonjs)

## Conclusion
* Maybe in this moment it is difficult to achieve this structure which I was described.
* Maybe I am on wrong path because I have habit e.g form .NET or java and I would 
  like transfer "assembly" to java script world
  But maybe no - typescript roadmap looks like small steps in this direction.

### Maybe crazy idea for typescript compilator

   What do you think to put to to output java script file declaration?
   As metadata in comments. It would transparent for java script. 
   But js could be add as reference to typescript project - similar to assembly or jar file
   which has own metadata. 
 

# Architecture for enterprise, long term solution
In new year I and my team I will have make some architect decision - 
and I ma responsible of consequences. 

I really appreciate you for each comments and criticism in this topic.
Typescript architecture for applications and libraries. Thant means how to organize compilation process to achieve these goals. 

I think thant others have similar problems with typescript projects - how to organize it
when structure is more complicate, e.g.:  #909 , #557 


*Thank you and sorry that I extended this issue of details
which could be out of scope*

**Comment by mhegazy** [comment]
@mironx, would not https://github.com/Microsoft/TypeScript/pull/5090 be sufficient for your needs?

**Comment by mhegazy** [comment]
ES6 modules provide the ability to build modules from smaller ones using `export * from "mod"` and `export { a as b } from "mod"`. This allows for having the multiple modules for implementation purposes, but then exposing a single "entry point" module that collates all of the smaller ones into a complete unit. This would be the recommended route for this scenario.

A follow up feature for the TS compiler is https://github.com/Microsoft/TypeScript/issues/4433, to enable publishing a single .d.ts file that has the "shape" of the "entry point" module, and thus completely hide the internal modules from consumers.

**Comment by Clark159** [comment]
This is my solution uses TypeScript 1.8, The solution build multi-Class in a module.

- sample : https://github.com/Clark159/clark159.github.io/raw/master/_posts/%5BTypeScript%5D/%5BTypeScript%5D%20%E5%BB%BA%E7%AB%8B%E8%88%87%E4%BD%BF%E7%94%A8AMD%20Library/Lab.zip

- document : https://dotblogs.com.tw/clark/2016/04/25/124833

**Comment by BSick7** [comment]
@mhegazy can you elaborate on this approach more of using modules for implementation, but smashing into 1 file with 1 entry point?

**Comment by mhegazy** [comment]
> @mhegazy can you elaborate on this approach more of using modules for implementation, but smashing into 1 file with 1 entry point?

there is no "smashing" happening. Each file is emitted as a module, but you have one entry point.

e.g.:

```ts
// a.ts
export var a = 0;
```

```ts
// b.ts
export var b = 0;
```

```ts
// index.ts
export * from "./a";
export * from "./b";
```

compiling with `--module amd` and  `--outFile`.:

```js
define("a", ["require", "exports"], function (require, exports) {
    "use strict";
    exports.a = 0;
});
define("b", ["require", "exports"], function (require, exports) {
    "use strict";
    exports.b = 0;
});
define("index", ["require", "exports", "a", "b"], function (require, exports, a_1, b_1) {
    "use strict";
    function __export(m) {
        for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
    }
    __export(a_1);
    __export(b_1);
});
```

your users would import `index` and not `a` or `b`.

**Comment by BSick7** [comment]
Doesn't this force me to use amd module loading?
Wouldn't UMD be an alternative that allows choice of module loading?

**Comment by mhegazy** [comment]
if you are using Node, then there is no need to bundle i would say. the issue with UMD is that it needs to work the same way on node and amd. since the way you can require an internal module is different from amd to node, we can not grantee that the transformation would work.
if you want to have a bundle that works in both amd and node, i would recommend looking at browserify or webpack.

**Comment by MortenHoustonLudvigsen** [comment]
I think [rollup.js](http://rollupjs.org/) looks very promising as well. I haven't tried it yet though.

**Comment by BSick7** [comment]
Those work well for applications, but I am looking to build a library that works with amd and vanilla js.

Isn't the whole purpose of UMD to be agnostic between commonjs and amd?

I imagine that UMD would work like `module: none` with the whole thing wrapped with boilerplate umd.
