### ISSUE TITLE
Boolean literals not working for static class props

### ISSUE THREAD

**Issue by MarcusLongmuir** [Microsoft/TypeScript#17102]
**TypeScript Version:**  2.4.1

**Code**

```ts
type MyType = {
  myProp: false
}

class MyClass {
  static myProp = false;
}

const myVar: MyType = {
  myProp: false
};

const myStatic: MyType = MyClass;
```

**Expected behavior:**
Both myVar and myStatic are valid assignments

**Actual behavior:**
myStatic is not a valid assignment:
```
(13,7): error TS2322: Type 'typeof MyClass' is not assignable to type 'MyType'.
  Types of property 'myProp' are incompatible.
   Type 'boolean' is not assignable to type 'false'.
```

**Comment by Nathan-Fenner** [comment]
`myStatic` has inferred type `boolean`, not the narrowed type `false`.

If you define it as

```ts
class MyClass {
  static myProp: false = false;
}
```

then you shouldn't have any problem.

It can't infer the type of `false` for the static, because then you wouldn't be able to assign it to *another* boolean (e.g. `true`). This would be a breaking change for existing code that initializes static variables to boolean values without explicit annotating types.

**Comment by MarcusLongmuir** [comment]
Thanks for the suggestion, @Nathan-Fenner.

I actually found the most appropriate solution is to define the prop in the class as `static readonly`:

```ts
class MyClass {
  static readonly myProp = false;
}
```
