### ISSUE TITLE
Autocomplete/Intellisense Does Not Show All Options For Object Value

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#17127]
_From @JonnyBoy333 on July 12, 2017 15:31_

- VSCode Version: 1.14.0
- OS Version: macOS 10.12.5

Autocomplete/intellisense is not showing all the options for an object that goes into a function parameter even though it is defined in a typescript interface.

Example:
```
interface Fruit {
    /** Returns a fruit color. */
    getFruitColor(options: { fruit: 'apple' | 'orange' }): string;
    getFruitColor(options: { fruit: 'banana' }): boolean;
}

function testFunction (fruit: Fruit) {
    let color = fruit.getFruitColor({ fruit: '' }); // <-- Autocomplete only shows apple and orange as options and not banana
}
```
![screen shot 2017-07-12 at 10 27 36 am](https://user-images.githubusercontent.com/15164008/28125639-cae175a6-66ec-11e7-813c-22a579c65554.png)

It appears that only the first method's options object is getting indexed by VS autocomplete but not the second one.

Reproduces without extensions: Yes

_Copied from original issue: Microsoft/vscode#30526_

**Comment by mjbvz** [comment]
Here's the tsserver completions response:

```
[Trace  - 10:28:51 AM] Response received: completions (53). Request took 1 ms. Success: true 
Result: [
    {
        "name": "apple",
        "kind": "var",
        "kindModifiers": "",
        "sortText": "0"
    },
    {
        "name": "orange",
        "kind": "var",
        "kindModifiers": "",
        "sortText": "0"
    }
]
```

**Comment by JonnyBoy333** [comment]
@mjbvz Got it. Thanks for confirming this is Typescript related.

**Comment by andy-ms** [comment]
Unfortunately, this would be pretty hard to fix in general.
When we get completions for a string literal directly inside a call expression, we have specialized code to iterate over every possible overload and get all string literals.

But when we get completions inside a string literal at an arbitrary location, we just call `getContextualType` and look for string literals in there.

`getContextualType` will climb up to the signature, see that overload resolution failed (since `{ fruit: "" }` is assignable to neither `{ fruit: "apple" | "orange" }` nor `{ fruit: "banana" }`), and arbitrarily pick the first signature to get the contextual type.

To fix this in general would seem to require writing a `getContextualTypes` function that handled all overloads, returning all contextual types.

**Comment by JonnyBoy333** [comment]
@andy-ms Thanks for taking a look at this. If this isn't something that's going to be looked at in the near future is there an approach you could recommend as a work around? 

Right now I am having to choose between putting all the fruit types in the one `getFruitColor` method so that I can have autocomplete, but that is at the cost of having type safety on the return values. Or keeping it the way it is and having type safety, but only autocomplete on the arbitrary first signature. Obviously in my real use case there are quite a few more than three fruits and two return types, they are actually different fields on a form that can return different data types.

**Comment by andy-ms** [comment]
@JonnyBoy333 I would recommend preferring correct types and no autocomplete over autocomplete and incorrect types, but that's just my opinion :P
You could also define a separate interface for each case and get autocomplete by explicitly annotating the type of the options:
```ts
interface RoundFruit {
    fruit: "apple" | "orange"
}
interface CurvedFruit {
    fruit: "banana"
}

function getFruitColor(fruit: RoundFruit): string;
function getFruitColor(fruit: CurvedFruit): boolean;

const options: RoundFruit = { fruit: "/*completions!*/" };
getFruitColor(options);
```

**Comment by wehrstedt** [comment]
I think this belongs to the same problem @andy-ms described above:

```
declare interface xyz {
     myVar: "value1" | "value2" | "value3"
}
```

And for this, you don't get any suggestions:
```
let y = getMyInterfaceObject(): xyz;
y.myVar  = "/*no completions*/";
```

Do you have any suggestions how to fix this or do I have to live with that for now?

**Comment by andy-ms** [comment]
@wehrstedt You should be getting syntax errors there. You probably meant `let y: xyz = getMyInterfaceObject()`.

**Comment by wehrstedt** [comment]
Yep, sorry. I worte this piece of code in the comment field. But the issue is still the same. Any suggestions?

**Comment by andy-ms** [comment]
It's working for me if `y` is really of type `xyz`. Could you share a complete example?

**Comment by wehrstedt** [comment]
unfortunately not.But I will try to complete the example:

This is my dts file:
```
declare namespace myNamespace {
	export interface myInterface {
		myVar: "value1" | "value2";
	}
}

declare var myInterface: myNamespace.myInterface;
```

I found out something interesting:
When I type
```
myInterface.myVar = "";
```

and hit CTRL + Space between the quotation marks in a **typescript file**, the code completion works. When I try the same in a **js** file, the code completion doesn't work.

This is probably the reason why the example above works for you. I'm developing javascript, not typescript. And for code completion I write some typescript definition files.

Is this behaviour correct?

**Comment by andy-ms** [comment]
@wehrstedt You probably don't have both files included in the same project. If I use this tsconfig.json:
```ts
{
    "compilerOptions": {
        "module": "commonjs",
        "noEmit": true,
        "allowJs": true,
        "checkJs": true
    }
}
```

Then I can get types from a `.d.ts` file applied to a `.js` file. But it looks like if we just see them side-by-side with no `tsconfig.json`, we don't give you good autocomplete.
