### ISSUE TITLE
Overload Signature Is Not Compatible For Inherited Type Function Parameter

### ISSUE THREAD

**Issue by daryllabar** [Microsoft/TypeScript#17162]
**TypeScript Version:**  2.4.1

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
class Animal {
    a: string;
}

class Dog extends Animal {
    b: string;
}

function test(func: (p: Dog) => any): any;
function test(func: (p: Animal) => any): any;
function test(func: (p: Animal) => any): any {

    return undefined;
}
```

**Expected behavior:**
No TS2394 Compiler error

**Actual behavior:**
a TS2394 Compiler error for this line:
```ts
function test(func: (p: Dog) => any): any;
```
Changing function definition the below resolves the compile error:
```ts
function test(func: (p: any) => any): any {
```

**Comment by jcalz** [comment]
This looks like intended behavior.

Since the `func` parameter is a callback, TS 2.4 is checking it [more strictly](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-4.html#strict-contravariance-for-callback-parameters) than earlier versions.  

The type of `func` in each overload needs to be assignable to the type of the `func` in the implementation.  Or, from the other direction: the type of `func` in the implementation should be a supertype of all the types declared for `func` in the overloads.  

Let's call `(p: Dog) => any`  a `Dog`-consumer, and `(p: Animal) => any` an `Animal`-consumer.  Note that every `Animal`-consumer is a `Dog`-consumer (because something that consumes animals will accept a dog), but not every `Dog`-consumer is an `Animal`-consumer (because something that consumes dogs might not accept, say, a cat).  That means that `Dog`-consumer is a supertype of `Animal`-consumer.  Since one overload takes a `Dog`-consumer, and the other takes an `Animal`-consumer, the implementation should take a supertype of these: `Dog`-consumer.  

That is:
```ts
function test(func: (p: Dog) => any): any;
function test(func: (p: Animal) => any): any;
function test(func: (p: Dog) => any): any {  // no error now
```

**Comment by daryllabar** [comment]
Ahh, so I confused a "callback parameter" with the return type.  Since func is a call back function, it's type is a call back parameter?

I would expect this to be valid but it's not, why?

```ts
function test(func: (p: Dog) => any): any;
function test(func: (p: Animal) => any): any;
function test(func: (p: Animal|Dog) => any): any {
```

**Comment by jcalz** [comment]
Note that `func: ((p: Animal) => any) | ((p:Dog) => any)` is essentially equivalent to `func: ((p:Dog) => any)`.  If you use the union, you'll find that you can't actually call `func()` on anything directly (see #14107), so the latter is probably preferable.

**Comment by daryllabar** [comment]
@jcalz I noticed that.  Ended up with something like this:

```TS
function test<T,A extends Dog   >(animal:A, func: (p: A) => T): T;
function test<T,A extends Animal>(animal:A, func: (p: A) => Foo<T>): Foo<T>;
function test<T,A extends Animal>(animal:A, func: (p: A) => T|Foo<T>): T|Foo<T> {
    return func(animal);
}
```

I've included `Foo<T>` just so it would make sense as to why the overload would be defined

I'm guessing that is the best way?

**Comment by RyanCavanaugh** [comment]
Crosspost reference https://stackoverflow.com/questions/45087264/how-to-cleanly-write-a-typescript-function-with-different-callback-overload-para for anyone who ends up here
