### ISSUE TITLE
Local Meaning of Union Types (safe assignments)  

### ISSUE THREAD

**Issue by olegdunkan** [Microsoft/TypeScript#17188]
**TypeScript Version:**  Playground

**Code**

```ts
class A {
    x: number;
}

class B extends A {
    y: number;
}

class C extends A {
    z: number;
}

declare function process(c:C);
function f(x:  B | C) {
    
    if (x instanceof C) {
        //we memorize x in c
        let c = x; //here x of type C        
      
        //restore x
        x = c;  //here x loses the narrowed type and x is now B | C again and is's by design    
        x.z = 1; //no error, what? 
        process(x);  //it have to be an error, what?
    }
}
```
Preamble:
[A type guard for a variable x has no effect if the statements or expressions it guards contain assignments to x.](https://github.com/Microsoft/TypeScript/pull/824#issuecomment-58273237) 

If compiler knows that the type of right hand expression is the same as narrowed type of parameter (in my case) why does compiler expand type of x to the initial type? Maybe it is possible to check for this type of assignments?

**Comment by kitsonk** [comment]
I assume, because tracking all those assignments are overhead for the compiler.  While in abstract, it is clear that `x` is narrowed, but in real world applications, a re-assignment like that is unlikely to be that straight forward and trivial.  Do you have a real world practical pattern that would demonstrate how this sort of makes it practical to track that sort of narrowing where re-assignment doesn't potentially re-widen the type?

Having built lots of TypeScript code over the last 2 years, I can't say I have ever run across a pattern where that would be valid.

**Comment by olegdunkan** [comment]
@kitsonk  Thanks for feedback, maybe I don't understand exactly what do you mean "tracking all those assignments". When compiler meets `x=c` it makes a decision to widen previously narrowed type, and from that line of code `x` will be of initial type. I can guess that all other assignments to `x` will be ignored by the compiler. If so then you are likely right. Do you think that the TS team the same view as yours on this question?   If so I will close the issue.

**Comment by kitsonk** [comment]
Take for example this:

```ts
declare function process(c: B | C);

function f(x:  B | C) {
    
    if (x instanceof C) {
        let c = x;

        process(c);  // c is a reference, what happens in see cannot be easily tracked via CFA

        x = c;  // what is `x` here? not sure, so re-widen...
    }
}
```

There are all sorts of structural things that can occur at run-time which CFA has to sort of try to treat in the most reasonably type safe way.  It is always easier to reset a narrowed type than to do complex tracking of narrowed types, and there will always be trade off of how far it can go.

> Do you think that the TS team has the same view as yours on this question?

My opinions are mine.  I would assume if you had a pattern that was a realistic and common real world pattern where the re-widening was causing usability issues with TypeScript, the team feel that there is a case.  At the moment `let x = c; c = x;` does not seem like a practical real world use case to me, but again, that is my opinion.  My personal champion though is the widening of types in callback functions because CFA cannot determine if they are immediately invoked or not (see: #11498).  That seems like a much more real world use case that effects pratical type usage. 😉

**Comment by olegdunkan** [comment]
@kitsonk things are getting more complicated )
Check this in playground:
```ts
class A {
    x: number;
}

class B extends A {
    y: number;
}

class C extends A {
    z: number;
}

declare function process(c:C);
function f(x:  B | C) {
     if (x instanceof C) {
        let c = x;       
      
        x = c; //hover on x it will be of type B | C
        x.z = 1; //hover on x it will be of type C and no error
         
    }
}
````
What is that? Now it seems to me that some bug exists.

**Comment by kitsonk** [comment]
Actually going back to your original code:

```ts
class A {
    x: number;
}

class B extends A {
    y: number;
}

class C extends A {
    z: number;
}

declare function process(c: C);

function f(x:  B | C) {
     if (x instanceof C) {
        let c = x;       
      
        x = c; //hover on x it will be of type B | C
        process(x); //no error 
    }
}
```

It was never an error [anyways](http://www.typescriptlang.org/play/#src=class%20A%20%7B%0D%0A%20%20%20%20x%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Aclass%20B%20extends%20A%20%7B%0D%0A%20%20%20%20y%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Aclass%20C%20extends%20A%20%7B%0D%0A%20%20%20%20z%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Adeclare%20function%20process(c%3A%20C)%3B%0D%0A%0D%0Afunction%20f(x%3A%20%20B%20%7C%20C)%20%7B%0D%0A%20%20%20%20%20if%20(x%20instanceof%20C)%20%7B%0D%0A%20%20%20%20%20%20%20%20let%20c%20%3D%20x%3B%20%20%20%20%20%20%20%0D%0A%20%20%20%20%20%20%20%20x%3B%0D%0A%20%20%20%20%20%20%20%20x%20%3D%20c%3B%20%2F%2Fhover%20on%20x%20it%20will%20be%20of%20type%20B%20%7C%20C%0D%0A%20%20%20%20%20%20%20%20x%3B%0D%0A%20%20%20%20%20%20%20%20process(x)%3B%20%2F%2Fno%20error%20%0D%0A%20%20%20%20%7D%0D%0A%7D)... the left hand assignment quick info was `B | C` but before and after the CFA tracked the assignment properly.  Which makes sense, because `x` can _always_ be assigned a value of `B | C`...

This examples shows that CFA tracks it [perfectly fine](http://www.typescriptlang.org/play/#src=class%20A%20%7B%0D%0A%20%20%20%20x%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Aclass%20B%20extends%20A%20%7B%0D%0A%20%20%20%20y%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Aclass%20C%20extends%20A%20%7B%0D%0A%20%20%20%20z%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Adeclare%20function%20process(c%3A%20C)%3B%0D%0A%0D%0Adeclare%20const%20d%3A%20B%3B%0D%0A%0D%0Afunction%20f(x%3A%20%20B%20%7C%20C)%20%7B%0D%0A%20%20%20%20%20if%20(x%20instanceof%20C)%20%7B%0D%0A%20%20%20%20%20%20%20%20let%20c%20%3D%20x%3B%20%20%20%20%20%20%20%0D%0A%20%20%20%20%20%20%20%20x%3B%0D%0A%20%20%20%20%20%20%20%20x%20%3D%20c%3B%20%2F%2Fhover%20on%20x%20it%20will%20be%20of%20type%20B%20%7C%20C%0D%0A%20%20%20%20%20%20%20%20x%3B%0D%0A%20%20%20%20%20%20%20%20process(x)%3B%20%2F%2Fno%20error%20%0D%0A%0D%0A%20%20%20%20%20%20%20%20x%20%3D%20d%3B%0D%0A%20%20%20%20%20%20%20%20x%3B%20%2F%2F%20type%20%3D%20D%0D%0A%20%20%20%20%7D%0D%0A%7D):

```ts
class A {
    x: number;
}

class B extends A {
    y: number;
}

class C extends A {
    z: number;
}

declare function process(c: C);

declare const d: B;

function f(x:  B | C) {
     if (x instanceof C) {
        let c = x;       
        x;
        x = c; //hover on x it will be of type B | C
        x;
        process(x); //no error 

        x = d;
        x; // type = D
    }
}
```

**Comment by RyanCavanaugh** [comment]
> A type guard for a variable x has no effect if the statements or expressions it guards contain assignments to x.

This statement stopped being true when we added control flow analysis.

A complicating factor here is that a variable has two types at any point -- its declared type (for `x` that's `B | C`) and its control flow type (for `x` that's `C` everywhere inside the `if`). I'm not 100% clear on the rules for which gets shown in Quick Info, but the gold standard for figuring out the control flow type is trying to treat `x` as a `C` (e.g. as a function argument or use a `C`-specific method), not hovering in the editor.

**Comment by olegdunkan** [comment]
@RyanCavanaugh thanks for notes, now I see.
Does TS team have any plans to update the specification with CFA description and more other latest issues? 
I think a lot of questions and issues will disappear.  

@kitsonk

> This examples shows that CFA tracks it perfectly fine 

Yes, my question was solved by CFA)

**Comment by RyanCavanaugh** [comment]
We're pretty far behind on spec updates and I will admit that I don't expect that to change any time soon. A formal specification of CFA behavior is exceptionally difficult to write in prose; it's cliche but "the code is the spec" in terms of that feature. I expect when CFA does make it into the spec it will be a succinct but nonspecific description like "Conforming implementations may temporarily type an expression or declared property to a subtype of its declared type when a reachability analysis deduces that a type guard or type guard expression is in effect"

**Comment by olegdunkan** [comment]
@RyanCavanaugh I understand that the main priority of development of TypeScript is new features rather then routine descriptions of it. And of course I don't expect that CFA requires a formal description in the specification but the notion of flow containers would be 👍 .  
And it is really difficult to follow evolving of TypeScript by explore all PR and issues in this repo.  
Thanks for support.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
