### ISSUE TITLE
Branch type inference not correct

### ISSUE THREAD

**Issue by Volox** [Microsoft/TypeScript#17260]
**TypeScript Version:**  nightly (2.5.0-dev.20170712)

**Code**

```js
/** @type {any} */
let currentNS = {};
const string = 'this.is.a.namespace';
const parts = string.split('.');
while (parts.length > 0) {
	const currentPart = parts.shift(); // `currentPart` type is `string|undefined`
	currentNS[currentPart] = currentNS[currentPart] || {}; // Error here
	currentNS = currentNS[currentPart]; // ... and here
}
```

**Expected behavior:**
Since `parts.length>0` is checked `currentPart` can only be `string`

**Actual behavior:**
[js] Type 'undefined' cannot be used as an index type.

**Comment by ikatyang** [comment]
`parts.length > 0` is not a type guard, control flow analysis does nothing to `parts`.

And also `Array` allowed `undefined` as empty element implicitly, e.g.

```ts
const array = new Array(5); //=> [undefined × 5]
while (array.length > 0) {
  array.shift(); //=> undefined
}
```

So that `Array<T>#shift(): T | undefined` is the most type-safe way, if you're in a `ts` file you can use non-null-assertion (`!`), e.g. `const currentPart = parts.shift()!`, but I have no idea how to use something like non-null-assertion in a `js` file simply.

**Comment by Volox** [comment]
Sorry, just a question to understand better.

Right now is not possible to have this kind of behaviour:

```ts
const arr: string[] = [];

// Type error in the next line, cannot push 'undefined', so we cannot have
// 'undefined' values in the array
arr.push(undefined);


const value = arr.pop(); // 'string|undefined', ok in this branch, no type guard
if (arr.length>0) { // Type guard here?
    // Can only be 'string' in this code branch, due to type guard
    const value = arr.pop();
}
```

**Comment by kitsonk** [comment]
The point is that TypeScript does not currently have a way of expressing the relationship between co-dependent members of an instance.  It is a current limitation of code flow analysis and solving it is a complex problem, because you would have to be able to generically express that a constraint of a value in one property effects the types of other functions.

Because of this complexity, this is why TypeScript introduced the non-null assertion operator, knowing that there were these limitations.

```ts
const arr: string[] = [];

if (arr.length > 0) {
    const value = arr.pop()!; // value is `string`
}
```

The `!` asserts that you know something that the CFA doesn't.

**Comment by Volox** [comment]
Ohhh now i got the problem, thanks!
