### ISSUE TITLE
VS2017 typescript 2.4 uninstalls 2.3, can I have both?

### ISSUE THREAD

**Issue by stasberkov** [Microsoft/TypeScript#17265]
**Expected behavior:**
Having typescript 2.3 installed I install typescript 2.4 for vs2017. v2.4 installer installs 2.4 without removing 2.3.

**Actual behavior:**
2.4 installer removes 2.3 version

**Comment by Anton2478** [comment]
+1
I can have both 2.1 and 2.4, but not 2.3 and 2.4.

**Comment by VitalyVoroshilov** [comment]
+1

**Comment by minestarks** [comment]
Agreed this shouldn't happen. One workaround is to upgrade to VS 2017 15.3 (now in [Preview](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-preview-relnotes)) and make sure TypeScript 2.3 is selected in setup -- it will "anchor" 2.3 and keep it from being uninstalled. 

But yes we need to fix this for 2.5.

**Comment by odrozd** [comment]
I have no issues with TS 2.4 and 2.3 on VS release version, I've used regular TS 2.4 installer
![image](https://user-images.githubusercontent.com/16099116/28489549-2f4bcdf0-6ece-11e7-8fb6-4b93bc018629.png)

But for latest "Preview" version I don't see TS version selector at all
![image](https://user-images.githubusercontent.com/16099116/28489561-6b12d54a-6ece-11e7-9d95-10e8971691f6.png)

**Comment by minestarks** [comment]
@odrozd this is expected.
https://github.com/Microsoft/TypeScript/wiki/Updating-TypeScript-in-Visual-Studio-2017#setting-typescript-versions-in-visual-studio-2017-version-153

**Comment by minestarks** [comment]
Bug is fixed for 2.5 onwards.

**Comment by markhewett** [comment]
@minestarks How is this "fixed"?  We still can't have 2.3 and 2.4 installed at the same time.  Shouldn't the fix be to publish 2.4.2 that doesn't uninstall 2.3.x?  Is there any way to force 2.3.3 to install when 2.4.1 is installed (gives error 0x80070666 - Another version of this product is already installed...)?

**Comment by minestarks** [comment]
@markhewett you make a good point. The reason for not fixing 2.4 now is that if we do, then we'll be creating a new bug where you end up with duplicate installs of 2.4 on the system (one with the old ID, one with the new ID).

Have you given [this workaround](https://github.com/Microsoft/TypeScript/issues/17265#issuecomment-317074454) a try?

**Comment by markhewett** [comment]
@minestarks  Thanks for the reply - I deleted my comment just after posting (which will confuse other readers), but you probably got the notification.  What I discovered was that if I uninstalled the 2.4 SDK, "C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.4" was left on my system, I am guessing because I also have "TypeScript Tools for Microsoft Visual Studio 2015 2.4.1.0" installed.  Anyway, this allowed me to install the 2.3.3 SDK, and now VS2017 lists both 2.3 and 2.4 in the project settings (although I haven't tested to make sure that removing the 2.4 SDK didn't break something else, since I am still on 2.3 for this project anyway).  A bit of a hack, but I'll probably upgrade my projects that are still on 2.3 soon anyway.

OK, I also just tried the workaround (only 2.1 was checked in setup before, so I checked them all), and installing 2.4 removed 2.3 from Programs and Features, but left the folder in Program Files, so that works too.  Thanks! :-)
