### ISSUE TITLE
importHelpers by default?

### ISSUE THREAD

**Issue by testerez** [Microsoft/TypeScript#17292]
I was wondering why `importHelpers` is not activated by default when in project mode. Or at least activated in the default `tsc --init` config. I've been using typescript for a little while now and I just discovered this compilation flag.
I guess most users don't use `importHelpers` and end-up having a lot of duplication in there bundles.

But maybe I'm missing something?

**Comment by aluanhaddad** [comment]
It requires the use of a module system and also takes a dependency on an additional package, `npm:tslib`. Since using it is an optimization it makes sense for it to be off by default. Perhaps it should be better highlighted in the documentation as it is indeed a very useful feature.

For reference, Babel has a similar option which if also off by default.

**Comment by testerez** [comment]
Ok makes sense. Thanks for the answer.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
