### ISSUE TITLE
for-of has different behaviour when compiled to ES5 vs ESNext

### ISSUE THREAD

**Issue by spion** [Microsoft/TypeScript#17298]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
var r = ''
for (const x of '😀') {
  r += x + '!'
}
console.log('😀!' === r)
```

**Expected behavior:**

prints `true` regardless of the target

**Actual behavior:**

only prints `true` when target is ESNext due to different for-of semantics

**Comment by sccolbert** [comment]
I think turning on `--downlevelIteration` will fix this if you're in a runtime which supports ES6 string iteration (i.e. `Symbol.iterator`).

**Comment by RyanCavanaugh** [comment]
So the problem here is that `'😀'.length` is `2` (you would really expect `1`) and `'😀'[0]` is `�` (rather than `😀`). There's a nice long blog post going into this http://blog.jonnew.com/posts/poo-dot-length-equals-two

To properly iterate this string in an pre-`Symbol.iterator` environment, we'd have to emit something like this file https://github.com/orling/grapheme-splitter/blob/master/index.js (which is 1,700 lines of code and probably will need updates when the Unicode spec changes) whenever there was a `for / of` on a string *or* a value of type `any` (since it might be a string).

**Comment by jcalz** [comment]
@RyanCavanaugh that's a bit overstating it, isn't it?  Decoding a UTF-16-encoded string into code points is a little more complicated than in UCS-2 but it is nowhere near as crazy as you're describing.

**Comment by RyanCavanaugh** [comment]
You're right that it's codepoint enumeration rather than grapheme enumeration (I stand corrected). Not as bad... but still bad 😉 . So I guess would-be `Z͑ͫ̓ͪ̂ͫ̽͏̴̙̤̞͉͚̯̞̠͍A̴̵̜̰͔ͫ͗͢L̠ͨͧͩ͘G̴̻͈͍͔̹̑͗̎̅͛́Ǫ̵̹̻̝̳͂̌̌͘` enumerators will be in for a variety of surprises

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
