### ISSUE TITLE
Partialy broken intellisense in Visual Studio 2017 and TypeScript 2.4

### ISSUE THREAD

**Issue by odrozd** [Microsoft/TypeScript#17351]
**TypeScript Version:**  2.4
**Visual Studio Version:** 2017 15.2 (26430.16)
**TypeScript Intelisense Version:** version 2.4 is selected in "JavaScript/TypeScript => Intellisense"

**Problem:**
After upgrading to TypeScript 2.4 - code completion for specifying type of variable or expression stopped working, but if manually specify correct type name then type will be highlighted and compile successful. 
Problem with Intellisense suggestion box it just don't show up at all in this case.

**Possible workaround:**
If change TypeScript intellisense version back to 2.3 and restart VS problem go away.

**Update:** Problem still persists in VS 15.3.0(Release)
**Update 1:** Looks like this is issue is fixed on TS 2.5 RC

**Comment by mhegazy** [comment]
Can you please file this issue using [VS 2017 Report a problem tool](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017). The tool captures additional debugging information that allows us to further debug the issue.

**Comment by odrozd** [comment]
Adding link to VS issue tracking: [https://developercommunity.visualstudio.com/content/problem/102062/intellisense-for-typing-not-working-after-typescri.html](url)

**Comment by mahesh-it** [comment]
I am facing similar problem after upgrading to TS 2.4
VS version : 15.3.3

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by NoelAbrahams** [comment]
@odrozd, did you raise this issue with VS? The link posted above does not work.

@mhegazy, I'm having problems with the Language Service crashing intermittently in **VS 2017 v15.4** and **TypeScript 2.5.3**. The red error squiggly lines disappear + errors appear on types when I open a file (presumably because intellisense cannot find type information). I keep having to restart VS. Things work normally after a restart.

There is no easy way for me to reproduce the crash. The problem with "Report a problem" is they just close the issue after a few days if it cannot be reliably reproduced. This is what they did with the last issue I posted - in spite of providing a stack trace.

I cannot provide my VS Solution but I am happy to work one-to-one with someone in order to get to the bottom of this. 

I am pretty sure you have lots of other priorities for your developers, but I am beginning to lose the fun side of TypeScript because the IDE is not working most of the time.

**Comment by odrozd** [comment]
@NoelAbrahams, I've fixed link url to VS issue, but those issue is closed as not a bug. Personally I've moved to TS 2.5 and it solves this issue.

P.S. I am using Visual Studio 15.4.0 and TypeScript 2.5.3 and it works fine

**Comment by NoelAbrahams** [comment]
@odrozd, thanks for fixing the link. I do understand TypeScript well enough to know that the problem I'm having is not with configuration or definition files.

**Comment by NoelAbrahams** [comment]
Example of a crash (just occurred):

![image](https://user-images.githubusercontent.com/1106823/31770294-14ea13bc-b4cf-11e7-90b2-02b292b98ed6.png)

* A spurious red squiggly under valid type `GeoFeature`. This is a remnant after the earlier type was corrected.
* Sticky red squigglies in the comments. 

There is absolutely no reason for there to be errors in comments.

(This is all still there while I complete writing this. The itellisense has basically crashed)

**Comment by NoelAbrahams** [comment]
Just opened a file. Spurious red squiggles all over. The project itself builds fine.
![image](https://user-images.githubusercontent.com/1106823/31784017-3009a774-b4f8-11e7-91c0-5aacba22a576.png)

**Comment by mhegazy** [comment]
@NoelAbrahams can you share additional information.. like when did these symptoms start? is it specific to a project? do you see it on other machines?

**Comment by NoelAbrahams** [comment]
@mhegazy,

> When did these symptoms start
I believe these problems started around TypeScript 2.4.1 back in June. I had just downloaded a preview version of Visual Studio 2017 at that time. I didn't report the issue earlier because I assumed it might be something to do with VS being in preview mode. However, this week I updated to VS 2017 15.4 RTM and TypeScript 2.5.3. The problems are still there.

> Is it specific to a project or machine?
It is almost certainly to do with the size of the project. When I say project it's a VS solution with a number of TypeScript projects. There are over 1000 .ts files involved. Judging by the nature of the problem, I don't think this will happen in a small project. The code itself is relatively self-contained. There are few external declaration files - less than 5 I'd say.

I'm not sure how to tackle the problem because it just happens randomly. Should I enable logging or similar?

Thanks for the response - much appreciated.

**Comment by NoelAbrahams** [comment]
@mhegazy,

The problem as I see it is down to a significant slowing down of the compiler as of version 2.4.1.

This is pretty much all I see on the status bar most of the time:

![ff](https://user-images.githubusercontent.com/1106823/31901964-28afc5fa-b81b-11e7-83fc-4379c4a240ab.gif)

When there are changes to "root" code files (i.e. files on which a number of other files depend) the compiler just keeps running like this. Obviously, one cannot wait for the compiler to finish, so we proceed to make further changes. But since the compilation is not complete there is red everywhere.

**Comment by mhegazy** [comment]
> The problem as I see it is down to a significant slowing down of the compiler as of version 2.4.1.

We have made some changes to make compile on save faster during the 2.2 time frame. i am wondering why that did not help here.. are you using modules, or are they scripts? 

> When there are changes to "root" code files (i.e. files on which a number of other files depend) the compiler just keeps running like this

The compiler is generating all the outputs, one at a time using your VS process. if you have a lot of files, then it is gonna take long time. 

> But since the compilation is not complete there is red everywhere.

are some of these files used as inputs to other projects?

**Comment by NoelAbrahams** [comment]
> We have made some changes to make compile on save faster during the 2.2 time frame

In my experience the compile-on-save has been a bit problematic around 2.4. It used to simply report success even when there were errors. It looks like some of the problems have been fixed as of 2.5.3.

>  if you have a lot of files, then it is gonna take long time.

But things were working fine before. Of course the number of files have been growing gradually, but there has been no "jump" in the number of files as such.

> are some of these files used as inputs to other projects?

Yes, precisely. "Project A" would generate declaration files that are consumed by "Project B". It's not possible to turn the output of Project A into static files (i.e. read-only) because there are always changes being made.

The point I'm trying to make is that this was always the setup for a number of years. Something around 2.4 has caused things to slow down.

**Comment by NoelAbrahams** [comment]
I currently see the compiler compiling a large number of files that are unchanged when a "root" file is changed.

I believe solving this problem, i.e. building in optimisations, would definitely benefit other areas of TypeScript.

**Comment by mhegazy** [comment]
> I currently see the compiler compiling a large number of files that are unchanged when a "root" file is changed.

given the language semantics for certain features, e.g. `const enums` or `namespaces`, the compiler has to emit all files that "depend" on the changed file to grantee correct and consistent output.

> I believe solving this problem, i.e. building in optimisations, would definitely benefit other areas of TypeScript.

That is what we have been doing, but for some reason the perf gains did not materialize for you.
I would love to get access to your sources to see what is going on and if there are any additional optimizations we can put in place. we would be happy to sign any required NDAs.

**Comment by NoelAbrahams** [comment]
@mhegazy, I've sent you an email to see if we can send you the information that you want.

**Comment by nguoihocnghe** [comment]
Hi,

I got the same issue here. It happened after I had upgraded VS from 15.3.x to 15.4.3 and TypeScript from 2.1.x to 2.3.x. Everything was fine before I applied that update.
![image](https://user-images.githubusercontent.com/4471670/32711864-364e08ae-c87c-11e7-8705-9b025fcb084b.png)

I can still build the project as usual using NodeJS, but coding with this issue is a nightmare with no supports from Intellisense.
![image](https://user-images.githubusercontent.com/4471670/32711086-1e53602c-c878-11e7-9b9f-073aeb752c4b.png)
The modules that Intellisense cannot find are the ones defined in package.json without `@types`.
You can see it has no issues with lodash because there is `@types/lodash`, but `@angular/core` and `@ngrx/store` use their own built-in types, and Intellisense seems to not understand.
![image](https://user-images.githubusercontent.com/4471670/32711230-ea361c5c-c878-11e7-9afc-dbfee8dbb5b2.png)
I even uninstalled and reinstalled VS, removed global typescript, and cleared npm-cache to reset it to TypeScript 2.1, but I'm not sure why TypeScript 2.3 and 2.6 is still there in the Project Properties and I have no ways to get rid of it.
![image](https://user-images.githubusercontent.com/4471670/32711572-972e7ea8-c87a-11e7-8f0b-9d226f3b3e46.png)
This is my tsconfig.json
![image](https://user-images.githubusercontent.com/4471670/32711643-f2fd5d4e-c87a-11e7-82bc-86766398c4ad.png)
Regarding the message "One or more tsconfig.json files detected", here is the list of `tsconfig.json` files in the project. Except my own file, the others come from node_modules.
![image](https://user-images.githubusercontent.com/4471670/32711664-05d415fc-c87b-11e7-88c0-b49cfbc1e6f8.png)

I hope this problem will be fixed asap, since I feel like I'm coding with a text editor, not an IDE anymore.
Thanks!

**Comment by NoelAbrahams** [comment]
@nguoihocnghe, did you get to the bottom of your problem? If not (out of curiosity - not sure that I can help you) what extensions to you have installed? I.e. under Tools => Extensions and Updates.

**Comment by nguoihocnghe** [comment]
Hi @NoelAbrahams, my extensions are the default ones from VS2017. I haven't install anything else.
![image](https://user-images.githubusercontent.com/4471670/32756781-ca6dc80e-c916-11e7-84ca-765cd37078d7.png)
![image](https://user-images.githubusercontent.com/4471670/32756792-db79b694-c916-11e7-9073-20ba66f92f00.png)
![image](https://user-images.githubusercontent.com/4471670/32756798-eb67e03a-c916-11e7-9174-41044772d696.png)

**Comment by NoelAbrahams** [comment]
@nguoihocnghe, sorry I can't help. I suggest opening a new issue as this one is closed.

**Comment by nguoihocnghe** [comment]
@NoelAbrahams, no worries. Actually, I think it's a problem of Intellisense and Visual Studio, not TypeScript. Anyway, I will find an appropriate place to post my question. Thanks!

**Comment by pvujic** [comment]
@nguoihocnghe Have you found the solution maybe? I'm experiencing the same issue.

**Comment by nguoihocnghe** [comment]
@pvujic I stopped working in my old company so I stopped looking for the solution for that issue. Sorry about that!
