### ISSUE TITLE
how to uninstall 1.4

### ISSUE THREAD

**Issue by v-vairam** [Microsoft/TypeScript#1739]

**Comment by DavidRigglemanININ** [comment]
I may be able to provide some help here since I had to do the same thing after encountering a bug in 1.4 that forced me to uninstall that version. You can uninstall version 1.4 from the Remove Programs functionality in the Control Panel. In my case, I then also had to right click on version 1.3 in the Control Panel, click Modify, and then select Repair in order to restore TypeScript integration back into Visual Studio for 1.3

**Comment by danquirk** [comment]
As mentioned, if you've installed it on VS2013 then there should be a normal Add/Remove Programs entry you can uninstall it from.

**Comment by v-vairam** [comment]
thanks. :) it helped.
