### ISSUE TITLE
instance and literal object as value

### ISSUE THREAD

**Issue by acopalipsis** [Microsoft/TypeScript#17409]
```
interface IValueObject {
    a: number;
    b: string;
}

class ValueObject implements IValueObject {
    a: number = 0;
    b: string = '';
    c: boolean = true;
}


var value: IValueObject = new ValueObject(); // Ok
var value: IValueObject = { a: 0, b: '', c: true }; // Error ?
```
Bug? What's the matter?

**Comment by jcalz** [comment]
This is intended behavior.  In your second case you are using an object literal, which is [checked for excess properties](https://www.typescriptlang.org/docs/handbook/interfaces.html#excess-property-checks).

**Comment by acopalipsis** [comment]
@jcalz is that logical?

```
let a: {p1: number} = {p1:0, p2: ''}; // Error
let b: {} = {p1:0, p2: ''}; // Ok
```

**Comment by jcalz** [comment]
I don't know if the empty object type is special cased not to trigger excess property checks.  Maybe someone else (@DanielRosenwasser?) knows...

**Comment by kitsonk** [comment]
It is a special case... `{}` is essentially equivalent to `object`.  I believe it is a mostly legacy thing as `{}` used to be used in place of `object` in the past and if it were to be enforced now as a proper type, it would cause a lot of breakage in code which is likely to be more chaotic as an edge case.  Essentially `{}` is the same as `any` in most cases, and prior to 2.4, all weak types like `{ foo?: string }` were equal to `{}`, but that has changed and now weak types are detected and follow the type system.

You can do really strange stuff like:

```ts
let a: object = 'foo'; // error
let b: {} = 'foo'; // no error
let c: { d?: string } = 'foo'; // previously no error, now error in 2.4+
```

But again, if `{}` were properly enforced, it would get ugly very quickly, which is why it is a special case.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
