### ISSUE TITLE
Default to 'any' for unsupplied generics in JavaScript

### ISSUE THREAD

**Issue by neekibo** [Microsoft/TypeScript#17524]
**TypeScript Version:**  2.4.0 
**VSCode Version:** 1.14.2

I am using TS to check my Javascript-React-JSX-files (.jsx). 
**Code**

```js
import React from 'react'

class MyComponent extends React.Component {

  render() {
    return this.props.simpleProp
  }
}
```

**Expected behavior:**
As stated [here](https://github.com/Microsoft/TypeScript/wiki/Type-Checking-JavaScript-Files#unspecified-type-parameters-default-to-any) TS compiler should default to `any` for unspecified generic type parameter. 
**Actual behavior:**
It shows me an error:
> [js] Property 'simpleProp' does not exist on type 'Readonly<{ children?: ReactNode; }> & Readonly<{}>'.

Is there any way to prevent this without specifying all props via `@augments` comment?

Thanks

**Comment by talbenari1** [comment]
That's because `@types/react` has been updated and now has defaults. This commit is where it changed: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/b0c9072f430eb3304fb79011a36b522d54c2be9c. Note the date, Jun 21, which is 11 days after the latest revision to the page you referenced. So for now I'm pretty sure you'll have to use `@augments` (or use TypeScript, or open an issue on DefinitelyTyped about the defaults).

Also someone should probably update the wiki.

**Comment by neekibo** [comment]
I opened an issue on DefinitelyTyped repo: [issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/18606)
