### ISSUE TITLE
Keep leadingComments of CallExpression

### ISSUE THREAD

**Issue by morlay** [Microsoft/TypeScript#17606]
**TypeScript Version:**  2.3.3 +

**Code**
```ts
export const a = /*#__PURE__*/create("a")
```

**Expected behavior:**
CallExpression.leadingComments should have comments

**Actual behavior:**
in https://astexplorer.net/
![image](https://user-images.githubusercontent.com/1667873/28950992-aa78c9ca-78fa-11e7-863c-fee3a7918465.png)

**Comment by weswigham** [comment]
This will likely continue to replicate in AST explorer as an artifact of [how ast explorer looks for comments](https://github.com/fkling/astexplorer/blob/master/website/src/parsers/js/typescript.js#L75), because we do not directly expose them on nodes. Specifically, The leading comments of a node never include single-line multiline comments, as it is expected those will be picked up as the trailing comments of the previous node. In this case, however, the "previous node" is the identifier on the LHS of the assignment, which, when you go the get the trailing comments for, see the `=` sign, then stop. There are _piles_ of cases like this, where a comment actually falls "inside" a node, and so is not picked up by the simple-thing-to-do without knowing that, say, a token was omitted from the AST at that point and that you need to collect any comments which would be considered attached to it.

But this _was_ actually a bug until recently as well, and was fixed by #16584 - as an assignment is just a `BinaryExpression`.

**Comment by mhegazy** [comment]
@filipesilva mentioned he has been running into this issue as well.
