### ISSUE TITLE
Only optional properties of generic parameter are inferred

### ISSUE THREAD

**Issue by ownerer** [Microsoft/TypeScript#17654]
**TypeScript Version:**  2.4.0

**Code**

```ts
abstract class Base<TParams> {
    private params: TParams; //cfr https://github.com/Microsoft/TypeScript/issues/1396
}
interface IParams {
    optional?: number;
}
interface IParams2 {
    required: number;
}
class Component extends Base<IParams> {

}
class Component2 extends Base<IParams2> {

}

function test<TParams>(component: Base<TParams>, params: TParams) {
}

var component = new Component();
var component2 = new Component2();

test(component, {  }); //<-- property "optional" of interface "IParams" is inferred correctly (run this in Playground and press ctrl+space with the cursor in the brackets)
test(component2, {  }); //<-- property "required" of interface "IParams2" is NOT inferred at all. It IS inferred when you make optional as well!
```

**Expected behavior:**
see comments in the code snippet!

**Comment by ownerer** [comment]
As mentioned in #17655: changing
```
function test<TParams>(component: Base<TParams>, params: TParams) {
}
```

To
```
function test<TParams>(component: Base<TParams>, params: TParams & {}) {
}
```

Makes the compiler throw an error on the missing "required" property of interface "IParams2".
So as far as enforcing types is concerned, this works.
However, intellisense still does not suggest the property "required" when pressing ctrl+space in the object literal!
It DOES when that property is made optional.

**Comment by mhegazy** [comment]
This is the same underlying issue that https://github.com/Microsoft/TypeScript/issues/14829 is addressing. All references to a generic type parameters are used to infer a type from the invocation; in some cases, you want to infer from one, and just check in another. the `& {}` trick makes it so that you have a lower priority inference and thus use the inference from the other reference only. 
another way of doing this is using two type parameters, e.g.:
```ts
function test<T, U extends T>(component: Base<T>, params: U) {
}
```

closing in favor of #14829
