### ISSUE TITLE
inherited protected property not accessible

### ISSUE THREAD

**Issue by npenin** [Microsoft/TypeScript#17759]
Please find below the example causing the issue.

**TypeScript Version:**  2.4.0

**Code**

```ts

class A
{
    protected p: string;
}

class B extends A
{
    constructor(a: A)
    {
        super()
        this.p = a.p;
    }
}
```

**Expected behavior:**
no compliation error

**Actual behavior:**
[ts] Property 'p' is protected and only accessible through an instance of class 'B'.

**Comment by aluanhaddad** [comment]
Just a guess but it looks like the assignment to `this.p` is being interpreted as shadowing the base class property even though it isn't declared

**Comment by npenin** [comment]
The compilation error is on `a.p`, not `this.p` ;)

**Comment by kitsonk** [comment]
This is an error in C# as well (and maybe other languages), therefore I suspect it is intentional.

```csharp
class A {
    protected int x = 123;
}

class B : A {
    public void process(A a) {
        this.x = a.x; // Error on accessing a.x
    }
}
```

Even though `B` inherits from `A`, cross instance access to non-public members can only be generally achieved by instances of the class or descendents.  I suspect this is _more_ sound as while something may look like `A`, it doesn't actually have to be `A` (it could be a `C` for example) and therefore doesn't share the same contract, therefore other ancestor instances cannot be safely interfaces with on their non-public shape.

As you can [see](http://www.typescriptlang.org/play/#src=class%20A%20%7B%0A%20%20%20%20protected%20p%3A%20string%3B%0A%7D%0A%0Aclass%20B%20extends%20A%20%7B%0A%20%20%20%20constructor(a%3A%20A%2C%20b%3A%20B%2C%20c%3A%20C)%20%7B%0A%20%20%20%20%20%20%20%20super()%0A%20%20%20%20%20%20%20%20this.p%20%3D%20a.p%3B%20%2F%2F%20Error%0A%20%20%20%20%20%20%20%20this.p%20%3D%20b.p%3B%20%2F%2F%20Ok%0A%20%20%20%20%20%20%20%20this.p%20%3D%20c.p%3B%20%2F%2F%20Ok%0A%20%20%20%20%7D%0A%7D%0A%0Aclass%20C%20extends%20B%20%7B%0A%20%20%20%20public%20a%3A%20number%3B%0A%7D), anything that is a `B` or descendent, the members are accessible:

```ts
class A {
    protected p: string;
}

class B extends A {
    constructor(a: A, b: B, c: C) {
        super()
        this.p = a.p; // Error
        this.p = b.p; // Ok
        this.p = c.p; // Ok
    }
}

class C extends B {
    public a: number;
}
```

**Comment by npenin** [comment]
Ok, fair enough. Thanks.

**Comment by RyanCavanaugh** [comment]
Duplicate of #10637; please search for the error message before logging new issues
