### ISSUE TITLE
'type' aliases of string can not be used as object index signature.

### ISSUE THREAD

**Issue by jlennox** [Microsoft/TypeScript#1778]
type Guid = string;
    var foo: { [deviceId: Guid]: DateTime } = {};

Generates the error:

> An index signature parameter type must be 'string' or 'number'.

It would be nice to be able to type indexes using string-aliases.

**Comment by aelr** [comment]
+1

**Comment by Zoltu** [comment]
This includes the alias `String`.

```ts
class Map<T> {
	[key: String]: T
}
```

**Comment by Zoltu** [comment]
It would seem you also can't pass aliased types to an indexer either:
```ts
class Map<T> {
	[key: string]: T
}

let map: Map<number> = ...
let key: String = ...
let value = map[key]; // error
```

`An index expression argument must be of type 'string', 'number', 'symbol, or 'any'`

And yes, there is a missing `'` in the error message.

**Comment by RyanCavanaugh** [comment]
`String` is not an alias for `string`. It refers to the non-primitive type `String` in JavaScript.

**Comment by Zoltu** [comment]
Ah I didn't know that, thanks!  I suppose this means I should be using `string`, `number` and `boolean` (lowercase) everywhere in my code rather than `String`, `Number` and `Boolean`.  Most unfortunate.

**Comment by aleksey-bykov** [comment]
what is the point in aliasing `string`?

**Comment by RyanCavanaugh** [comment]
aleksey's question is probably the most relevant.

This falls under the category of not appearing to do something you don't. Specifically, all type aliases of a type are equivalent, so you could still index `foo` by a `CustomerName`.

There's already a place to write the intended index semantics (`deviceId` should probably be `deviceGuid` ?). Adding a second place doesn't help because it makes it look like the compiler will enforce the specific indexing type when it won't.

One nascent proposal at the moment is "Fresh types" which *would* allow an enforcement of the indexing type. If that ends up happening, we'd definitely revisit this.

**Comment by aleksey-bykov** [comment]
didn't mean to play a devil's advocate, aliasing a string might be helpful
at early prototyping stages where, say, ID isn't yet clear to be a string
or a number, using an alias to either can reduce refactoring effort, but
this use case is too dubious to get enough justification

if people think that aliasing would create a new type incompatible with the
original one, so they can benefit from such distinction, it's a dangerous
fallacy and illusion (need nominate types to do so)

**Comment by jlennox** [comment]
>> One nascent proposal at the moment is "Fresh types" which would allow an enforcement of the indexing type. If that ends up happening, we'd definitely revisit this.

That would indeed be more inline with what I'm after.

**Comment by Yona-Appletree** [comment]
I use aliases to the string type to differentiate between different string types. I know they aren't compile time enforced, but they act as useful documentation. Not being able to use them as object keys seems quite arbitrary and not in line with what a type alias is. Should I not be able to use an alias anywhere I could use the aliased type? If that is the design intent, I'd love to know what those situations are and why they were chosen. Thanks.

**Comment by niedzielski** [comment]
Until a better solution is available, one alternative is to use JSDocs:

```ts
type Guid = string;
/** @type {Object.<Guid, DateTime>} */
var foo: { [deviceId: string]: DateTime } = {};
```

This will at least favor your future greps and offer a hint in your JSDocs / VSCode definition popups. You _could_ also use the following syntax but I believe it only happens to work and is incorrect:

```ts
type Guid = string;
var foo: { [deviceId in Guid]: DateTime } = {};
foo.bar = new DateTime();
```

**Comment by ehberger** [comment]
There's a work-around that we've been using to have type enforcement for different kinds of strings used as indices, which is to falsely declare them as different types of string literals.  As an example:

**Comment by ehberger** [comment]
There is a work-around we're thinking about using to get type-enforcement of difference categories of strings (e.g. ids for different types of objects), and to track those properly through being used as object keys, which is to declare them (inaccurately) as string literals, since those are the only types that can be used productively as index types in an object.
```
 //nothing actually takes these runtime values, but they allow the type system to reason about categories of strings (including unions of id types)
type StudentId = 'any_student_id_value'
type ClassId = 'any_class_id_value'
```
to create them, you just need to cast a string (either directly, or wrapped in a constructor-like function:
```
const studentId = 'abc' as StudentId
const classId = 'abc' as ClassId
```
The type system behavior is quite sane for this use case, and you can do things like:
```
const studentToClass:{[id:StudentId]?:ClassId}
```
and get type safety against accidental switches for both reads and writes for keys and values, including fairly readable error messages (checking is the best with noImplicitAny enabled).

And they can also be used directly as strings, so it has no impact on interpolation, serialization, etc.

I'd be very interested in knowing if anyone else has tried this approach and knows if this is a sane path, or if there is some reason this will be a bad idea (Other than the obvious, that this isn't safe against use of constant strings which happen to match the specific strings, which we've decided is less of a problem than the problem this is solving).

**Comment by ondratra** [comment]
I sometimes use aliases the same way as @Yona-Appletree does. When I work with Ethereum's addresses I create alias `export type Address = string`. I understand @aleksey-bykov's point, but why should the case of object's index differ from using an alias in for example function's parameter? e.g `(myParam: Address) => myParam` is completely fine. I don't see the point of explicitly forbidding of using aliases in object's index.

Could we mb reopen this issue, please?

**Comment by ducin** [comment]
Using type aliases over raw primitive types is useful especially in big systems with heavy domain logic. 

*Example usecase*: a bookkeeping system or e-commerce system. First you start with a local currency with `number`. But after the system grows big and have lots of customers and you need to replace `number` with `{ amount: number, currency: Currency }` in _few hundred places_, then good luck. Instead, you start with `type Money = number`, use `Money` everywhere. And when you need to change the entity, you'll get precise list of all places where compiler finds an error, the ones that you need to update (with primitive `number` you would get errors as well, but not in the places you need to update, less convenient).

It's basically a Value Object in DDD. TS Aliases are superb with it.

**Comment by ondratra** [comment]
@ducin That's an excellent point!

**Comment by aleksey-bykov** [comment]
@ducin there is a better idea to that called units of measure, with a couple of implementations (near the bottom): https://github.com/Microsoft/TypeScript/issues/364

**Comment by ducin** [comment]
@aleksey-bykov why "better" if DDD is a well-established and commonly used approach?

**Comment by ducin** [comment]
Not sure if I understand your point. I don't want to recalculate anything. I want to extend (==update) my model all along my codebase. I don't want to keep the old model. And I want TS to show me all the places I need to update. But let me give another examples...

----

Extending a number into number X currency is only one example. You might have lots of examples that do not fall into "units of measures" which is more narrow (comparing to Value Objects).

Example: how do you define identity (of a user, of a tenant, whatever). It can be a number (id), a guid (string) or a whole combination. Can't see how you apply "units of measures" into identity (you don't recalculate anything here).

Example: you've got a HR system where employees / candidates have _Skills_. _Skill_ is something meaningful in your app, lets you search, aggregate data, analyse, etc. You can start with a string, `type Skill = string` and then use Skill throughout your codebase. Then, if you need it, you extend a _Skill_ to be `{ Skill: string, level: string }`. And you want to have more convenient refactors.

And, basically, type aliases would be useful to be used within index signatures in this strategy (when you want to have a VO as an index). Also, using type aliases throughout your codebase increases readability. I'd prefer to have _Skill_ type where skills apply instead of _string_.

**Comment by aleksey-bykov** [comment]
jfc, i was just talking about your example with Currency and Money, didn't say or mean it can/should be used anywhere

**Comment by AndreasBackx** [comment]
@RyanCavanaugh could this be revisited and can there be a proper discussion on the topic? I feel like the amount of people voting for this feature proposal are in the majority and no chance has been given to us to express these reasons why we'd want these. Even if there is no enforcement yet, is there any chance for limited support for this and not errors generated by the compiler. Because in your own words:

> Specifically, all type aliases of a type are equivalent, so you could still index foo by a CustomerName.

Then why is it disallowed? What would in your opinion be the downsides of still implementing this behaviour? Does it outweigh the features it offers? Are these restrictions of Javascript even possible to be worked around? And if not, shouldn't we accept these restrictions and still move forward with these limited features?

**Comment by RyanCavanaugh** [comment]
> I feel like the amount of people voting for this feature proposal are in the majority and no chance has been given to us to express why we'd want this

You wrote this comment and I'm reading it, same as we read all the other comments. What specific behavior are you looking for (in the context that we still believe this isn't a good fit for the language)?

> Does it outweigh the features it offers?

It doesn't offer any features at all - that's the problem!

**Comment by jlennox** [comment]
> There's already a place to write the intended index semantics (deviceId should probably be deviceGuid ?). 

This isn't very convincing to me because it feels like arguing for Hungarian notation.

It seems rational that indexes wouldn't be compiler enforced because anything type aliased isn't enforced. That is, my original example with Guid is as strongly typed as this follow valid code is:
```TypeScript
    type SomeNewType = string;

    class SomeClass
    {
        methodOne()
        {
            this.methodTwo("This is of string type.");
        }

        methodTwo(ourNewType: SomeNewType)
        {
        }
    }
```

**Comment by nwshane** [comment]
I want to lend my support for this feature as well. My company has a lot of interfaces representing domain objects that are loaded in from the backend. Sometimes we need to create other data structures that use the data from those domain objects in various ways, including as the keys of objects. Here's a somewhat silly example: an object in which the keys are student IDs and the value is the status of the student's homework.

```
type studentHomeworkStatuses = {
  // the index is a student ID
  [index: number]: 'incomplete' | 'finished' | 'graded';
}
```

It would be really nice to be able to rewrite this without the comment and leverage the student interface we already have:

```
interface Student = {
  id: number;
  ...other properties
}

type studentHomeworkStatuses = {
  [index: Student['id']]: 'incomplete' | 'finished' | 'graded';
}
```

Why is this better?
- We've built the documentation into our code, instead of having to write an extra comment to explain it.
- We can more easily change the type of a Student['id'] from a number to a string in the future (if for some reason that becomes necessary), and have the type update throughout our codebase.

@RyanCavanaugh What do you (and other TS folk) think about these two benefits?

**Comment by burtonator** [comment]
@RyanCavanaugh @nwshane this is a huge issue for us too but I've been writing FooDict objects and hiding the underlying storage with a toKey() mechanism.  It's definitely not perfect but better than having to expose the ugliness to outside callers.

**Comment by nwshane** [comment]
@burtonator I'm not sure I understand—can you give an example of how you're doing that?

**Comment by burtonator** [comment]
it's just a facade hiding the ugly /internal data structure.

```typescript
class CarDict {

   private backing: {[id: string]: Accidents} = {};

  private string toKey(car: Car) {
    return car.name;
  }
  
  public get(car: Car): Accidents {
     return this.backing[this.toKey(car)];
  }
  public set(car: Car, accidents: Accidents) {
    this.backing[this.toKey(car)] = accidents;
  } 
}
```

you could also make it extend an abstract interface using generics and then force the new class to implement toKey

**Comment by arilotter** [comment]
Like @niedzielski mentionde, the following syntax
```typescript
type NumberAlias = number
type Foo = {[K in NumberAlias}: any}
```
actually works, and `Foo` gets resolved to `{[x: number]: any}` as expected!
I also believe this is just a happenstance of how mapped types work, since `{[K in number}: any}` is also valid.
However, doesn't mean we can't use it! :wink:

**Comment by alowaniak** [comment]
> Like @niedzielski mentionde, the following syntax
> 
> ```ts
> type NumberAlias = number
> type Foo = {[K in NumberAlias}: any}
> ```
> 
> actually works, and `Foo` gets resolved to `{[x: number]: any}` as expected!
> I also believe this is just a happenstance of how mapped types work, since `{[K in number}: any}` is also valid.
> However, doesn't mean we can't use it! 😉

This won't work for interfaces though.

ps. You have some typo's I think; using a curly brace instead of square bracket for closing.

**Comment by neryortez** [comment]
@nwshane  It works :smile: 

You just have to use `in` in the declaration of the index signature:
```
interface Student {
  id: number;
  // ...other properties
}

type studentHomeworkStatuses = {
  [index in Student['id']]: 'incomplete' | 'finished' | 'graded';
}

const hws: studentHomeworkStatuses = {
    1254815515: "finished",
    7841818115: "graded",
    7841518113: "graded",
}
```

It even gives you code completition
[See here](http://www.typescriptlang.org/play/index.html#code/JYOwLgpgTgZghgYwgAgMpgK4BMLmQbwChllgsAuZEDAWwCNoBuY5AeleQDpuB7MAC2jIADlB7DoYYBADOhAL6FCYAJ4TkMzDnAAJHjQgB3HlADW6OJhmzkAXgIsA2qBwAPUiDRbcYRwHIyPwBdIMoAkAR9YQAbCEg-ZAAfZD8YUGAZQSwE5L8Acyg4HGzmRUJIkE1kfkMZSk1sHz0DYzMLKxt7IhISAEYAJgBWABYADl7BwYnKACI0kAysmYAaFhIAdlHh3vHx6eQZgqKILBW15E3tqb2AZlmj4rP5IA)

**Comment by jpike88** [comment]
I don't get it, there's a clear benefit here. 

>It doesn't offer any features at all - that's the problem!

@RyanCavanaugh The feature is that context can be given to what that index is supposed to be used for. To me it seems arbitrary to prevent this from happening, you're restricting the amount of self-documenting code that can be written, with zero apparent drawbacks.

People are now coming up with weird workarounds to emulate this, so it has a clear need.

Restricting what types the type alias must conform to is a perfectly fine caveat.

**Comment by burtonator** [comment]
I agree with @jpike88 ... for me the main use case is 'typed' string.  I often have strings like URLStr, RegexStr, PathStr, etc.  Each is a strict subset of all strings.  URLStr is a URL for example.

it's MUCH clearer to have a map of URLStr as a key or PathStr as a key. 

I guess I can name the key 'path' but that take away a bit of semantics because with PathStr I can jump to that declaration and read the semantics of PathStr

**Comment by matthew-dean** [comment]
Another reason for this is to define keys as not belonging to other keys, like:
```ts
type Foo = {
  known1: string
  known2: string
}
type Bar = {
  [key: keysNotInFoo]: number
}
type FooBar = Foo & Bar
```

**Comment by nick-michael** [comment]
I would also like to add my support for this feature. The arguments seem to be that this doesn't add any features, and there doesn't seem to be any reason to type alias to primitives because it makes no different to compiler. **However** given that there already is support for type aliasing primitives, it seems like there should be consistency as to where these aliases could be used. Type aliases for strings can and are used to make code far more self documenting, take the (exaggerated) example:
```
type AlphaId = string;
type Alpha = { [key: AlphaId]: { ... } }

type BravoId = string;
type Bravo = { [key: BravoId]: { ... } };

type CharlieId = string;
type Charlie = { [key: CharlieId]: { ... } };

type State = {
    alpha: AlphaId;
    bravo: BravoId;
    charlie: CharlieId;
};
```

vs

```
type Alpha = { [key: string]: { ... } }

type Bravo = { [key: string]: { ... } };

type Charlie = { [key: string]: { ... } };

type State = {
    alpha: string;
    bravo: string;
    charlie: string;
};
```

I think there's a stark difference between the clarity of typing, despite both being equal at compile time. Ironically, TS currently allows for an "in-between" solution, where you can type alias to strings but can't use those type aliases to define key types.

**Comment by jpike88** [comment]
I'll respectfully ask the Typescript team to give this issue attention instead of ignoring users.

@orta, @DanielRosenwasser, @rbuckton, @sandersn, @sheetalkamat 

I'm cc'ing in recent contributors.

Please read this issue carefully and consider the facts:

- strong arguments were made for implementing this feature
- a poor, almost non-existent justification was given for ignoring this feature
- the above justification have been downvoted _**exclusively**_ by users of Typescript
- this feature can been closed anyway

I'd like due diligence to be applied to this feature. It's a no brainer. There is a clear need for it, with no design pattern or workaround to compensate.

**Comment by matthew-dean** [comment]
Just to give another real life example, where TypeScript fails to type a JS object, I'm using this pattern often in the next version of Less.
```ts
type Props = { 
  value: string | number
  text: string
}

type IProps = Props & { [key: ?(not defined keys)]: Node[] } 

...
constructor(props: IProps) {
  // The API here is that any key not explicitly defined is
  // an arbitrary node collection
  // The following deconstruction is very common in JS, but
  // TypeScript currently has no way to strongly type `children`, if the keys
  // can be any string value
  const { value, text, ...children } = props
 ...
}
```

**Comment by Peeja** [comment]
I'm hitting the same problem in JXA (JavaScript for Automation, in macOS), when a collection is of named objects. Consider,

```js
// This gets the Finder window with the name "Documents".
Application("Finder").windows.byName('Documents');

// This does the same thing.
Application("Finder").windows['Documents'];

// So does this, for the record, although it's not how the API is expected to be used.
Application("Finder").windows.Documents;
```

In other words, `Application("Finder").windows` is an object where every string key is a Window, except specifically for `byName`—and similarly `byId` and `at`—which are all functions. There appears to be no way to type this object in TypeScript.

**Comment by AnyhowStep** [comment]
I was playing around with branded strings for extra type safety.
I've never played with branded types much before.

Then, I noticed this annoying thing,
```ts
type MyKey = string & { someBrand: void };
type MyMap = Record<MyKey, number>;

declare const myMap: MyMap;
//const myKey: MyKey
declare const myKey: keyof MyMap;

/*
    Expected: OK
    
    Actual  :
    Element implicitly has an 'any' type because
    expression of type 'MyKey'
    can't be used to index type 'Record<MyKey, number>'
*/
console.log(myMap[myKey]);

```

So, I made a workaround,
```ts

function getWorkaround<K extends PropertyKey, V>(record : Record<K, V>, key : K) : V {
    return record[key];
}
/*
    Expected: OK
    Actual  : OK
*/
getWorkaround(myMap, myKey);
```
[Playground](http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=25&pc=29#code/C4TwDgpgBAsiDSERQLxQM7AE4EsB2A5lAGRQDeGA9gLYQBCWAhngCYBcUAbpTi1AL4BuAFChIsEDEZhUUAEoQAxpSwsAPHEQgANFDwBXagCMIWAHwjhLJQBtGWaMryYo1SdI5wpYEQHpfTi5uWp4ISFa29o6UzsCuYSAcANZIlABmEt6WvgBUwlAFUACiAB6QisAQ7FAA8vD5hQ0FAIIV+ow2BWxNxTYQtHhxONRgNjiKOMA2yAAWjOhQzFAA5Mwgy1Bi0CaKjProED0QZQ7o6DgxUOmb4NDLmkjLPbt4y3EmUPtVm5RQ+NYlG7iZYKZSqDQJXQGYymMxPHK+YSBSh9AB0NkoBAAFG5vABtYJIAC6AEpLGl9HgKhc8FACBBgAB1FRJeyUSnqeBQY6VVgLAAKWEokCwoC0ugAamYsQ4wXwOKCVJzJWZdClkBx4CSoBwJeQeg5gPosLTZUq8eqiSJ+MJcj1SuVKtU6j1WkaOl1avUEcJ6UyWWyOTj3GBdISQGSgA)

I really with branded strings could be used to index objects. But I'll take this workaround.

**Comment by jamesgpearce** [comment]
Seems like a legit requirement. Flow handles this just fine.

**Comment by noahbjohnson** [comment]
Can we get some input from maintainers on this? It's sorely missed and difficult to find an open source solution without it.

**Comment by AlexGalays** [comment]
I cry every time I hit this arbitrary limitation.

Also see https://github.com/microsoft/TypeScript/issues/15746 which got closed.

**Comment by RyanCavanaugh** [comment]
All the prior input we've provided is still true

**Comment by jlennox** [comment]
@RyanCavanaugh The last input you provided was to use mock Hungarian notation.

**Comment by AnyhowStep** [comment]
Branded strings are about the only reason I can see for this. And there's a workaround for branded strings as keys, even if not the best experience.

**Comment by RyanCavanaugh** [comment]
I don't know what I can do that will make people happy except to implement a feature we think is a bad idea. We've read the feedback, we understand it, we see why people might want it, but we think the feature is a bad idea to add to the language at this time and are thus choosing not to do so. Someone not agreeing with you is not the same as them not listening to you.

It all boils down to:

> This falls under the category of not appearing to do something you don't.

We think allowing you to write type aliases here creates the implication that you're making different kinds of index signature, but you're not. It's actively confusing and doesn't create **any** new functionality. Why would we add new syntax for doing something you can already do with **perfect** clarity? It's harmful.

**Comment by matthew-dean** [comment]
> It's actively confusing and doesn't create any new functionality. 

IMO that's false, in that if you can limit keys to a particular set of strings, you can do union types in which the types aren't in conflict. e.g. if you do `[key: string]: number` then all other keys / types must conform to a number. But if you do `[key: Foo]: number`, then ONLY keys conforming to `Foo` must be a type of `number` (or a compatible type such as `any`).

AFAIK, there's no way to specify "defined keys are these types, any extra keys are of this specific type" using current syntax. A simple solution would be to limit extra keys to a specific set of strings.

**Comment by aelr** [comment]
Is there any other place where type aliases can't be used? That is what has always confused me. This has never seemed like a new feature but a missing application of the existing feature: type aliases. The very first line of the code example for type aliases in the handbook is an example of [branded strings](https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-aliases), so there's no indication that their use is discouraged. Of anywhere, branded strings for index signatures is the place where that makes the _most_ sense to expect that people will careful about whether they are really just strings, rather than aliases used in function signatures or property types. Why are you less concerned about people expecting compile-time safety with branded strings when used anywhere else?

I'm honestly looking for an example. It has been a head-scratcher while periodically getting updates on this ticket for the last, wow, _5 years_. I can't think of a reason besides something like believing that aliases for primitives should have never been implemented altogether, and you're pushing back on this as damage control.

________________________________

**Comment by dragomirtitian** [comment]
@matthew-dean  But this issue is ONLY about allowing an alias instead of `string` (or presumably `number`). Is specifically not about allowing index signatures with unions. 

Allowing unions would be a different matter and is the subject of this (presumably on the back burner) PR #26797. Without the abilities in #26797 I don't think allowing aliases in that position really brings much value.

**Comment by jpike88** [comment]
I've returned to this issue because I've run into this problem again and again and it's driving me nuts.

@RyanCavanaugh 
> It's actively confusing and doesn't create any new functionality.

Whether it's confusing is a matter of opinion (I personally don't see how this would be any more confusing than the existing myriad of TypeScript functionalities), but it absolutely does lend a clear and useful function that to this day is sorely missing. Especially in a language like Javascript where it's common to fire up objects and use them as key-value maps.

```
public repeatableSections: { [s: string]: TemplateElement } = {};
public sectionHashMap: { [s: string]: TemplateElement } = {};
public fieldsThatHaveCrossElementChildren: { [s: string]: FormField } = {};
public elementHashMap: { [s: string]: FormElement } = {};
```
 I have plenty of the above in my application. I use hashmap-like structures for performance and caching reasons. Each of those string indexes correspond to a particular property of another interface which I populate during initialization. I have no way of clearly indicating and tracing where those indexes would originate from. Other than having to write a clumsy comment which serves to bloat the code, or just having to remember what's going on.

```
public repeatableSections: { [ s: SomeInterface['someStringProperty'] ]: TemplateElement } = {};
public sectionHashMap: { [ s: SomeInterface['someStringProperty'] ]: TemplateElement } = {};
public fieldsThatHaveCrossElementChildren: { [ s: SomeInterface['someStringProperty'] ]: FormField } = {};
public elementHashMap: { [ s: SomeInterface['someStringProperty'] ]: FormElement } = {};
```

Notice how that is self-documenting, and how it objectively _reduces_ confusion in this case by providing context? A person reading that not only understands that the index derives from a particular data structure, but they enjoy the fast-travel functionality in VSCode to speed up their workflow.

Why bring types to a language if you're not going to properly leverage them?

**Comment by cyberixae** [comment]
For what it's worth, I've started writing object key name and key type backwards. Obviously this is not safe if the definitions change but at least it let's you document the intended type of the key.

```typescript
type CustomerId = string;
type Customer = {
  id: CustomerId;
  name: string;
};
type CustomerRecord = { [CustomerId: string]: Customer };
```

**Comment by gravitypersists** [comment]
From the [TS documentation](https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-aliases):

>Aliasing doesn’t actually create a new type - it creates a new name to refer to that type. Aliasing a primitive is not terribly useful, though it can be used as a form of documentation.

From the argument here:

>We think allowing you to write type aliases here creates the implication that you're making different kinds of index signature, but you're not. It's actively confusing and doesn't create any new functionality. Why would we add new syntax for doing something you can already do with perfect clarity? 

I'm getting very mixed messages here. Why offer type aliases at all, then? Either you accept they're a part of the language and their rules are implemented unilaterally throughout the language (that is, accept that type aliases are a feature), or you don't. 

The minute you do a bit of both is the minute you add a bunch of minefields to your software, minefields where I need to go, yet again, *"why isn't this rational thing I'd expect would work in TS not work for me in this instance but does in this instance?"*

**Comment by matthew-dean** [comment]
> The minute you do a bit of both is the minute you add a bunch of minefields to your software, minefields where I need to go, yet again, "why isn't this rational thing I'd expect would work in TS not work for me in this instance but does in this instance?"

This +1000. Either types can be aliased or they can't. Either `'foo' | 'bar'` are a limited set of strings or they aren't.

**Comment by jpike88** [comment]
@RyanCavanaugh this is an issue of ergonomics and there is clearly an issue. What do you propose to offset the workarounds we’ve been doing?

**Comment by jpike88** [comment]
@RyanCavanaugh I request that this issue is reopened, because I’m still running into this issue, you haven’t suggested any workarounds to this issue, and have offered a rather unconvincing justification that seems to be skirting the reality of the problem.

Please clearly read this:

https://github.com/microsoft/TypeScript/issues/1778#issuecomment-586419491

And tell me how I’m supposed to be handling this scenario beyond an argument like ‘you’re holding it wrong’.

I know I’m not writing your paycheck but this is clearly an ongoing issue and I get the impression your team is sweeping it under the rug favouring semantics over actually developer concerns, and this is becoming immensely frustrating to read. 

Please at least do me the service of responding to what is being said here. If I (among others) are just shouting into the wind, let us know your decision is final and not for any more debate, and I will divest myself and move on.

**Comment by jpike88** [comment]
Due to unresponsiveness on this issue, I'm raising another one:

https://github.com/microsoft/TypeScript/issues/37448

**Comment by phoenixeliot** [comment]
I was also trying to use this as self-documenting code and found I couldn't. As others, I had to introduce awkward comments to describe what the key is, instead. Not ideal.

**Comment by stevethedev** [comment]
One workaround is to use the `Record<K, V>` type.

I have a use-case that looks something like this:

```
interface User {
  id: string;
  /* ... other properties */
}

interface Users {
  [id: User['id']]: User;
}
```

If I replace the `interface Users` with `type Users = Record<User['id'], User>` then it works fine.

**Comment by jamesgpearce** [comment]
As a complete surprise, this just started working.

```ts
type CellId = string;
type Row = {[cellId: CellId]: string}; // \o/
const row: Row = {'cell1': 'a'}
```

Digging deeper, the new index signature features are in the [4.4 release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html).

**Comment by sergii-zhuravel** [comment]
For me it was a surprise that it doesn't work in the old versions of the TS. To support old TS versions I had to change my Guid type alias to string. Many thanks to all those people who requested this feature for so many years!

**Comment by acdoussan** [comment]
If you're using an older version of Typescript I have had success with a mapped object type instead.

Arbitrary example, not tested:
```
export type PersonName = string;
interface Person {
  name: string;
};

type NameToPerson = {
  [personName in PersonName]: Person;
};
```
