### ISSUE TITLE
about typecript's type assertion

### ISSUE THREAD

**Issue by JLBear** [Microsoft/TypeScript#17821]
var someValue :any = false;
var strLength   :  number =(<string>someValue).length;
console.log(strLength);//undefined

var someValue :any = 12324;
var strLength   :  number =(<string>someValue).length;
console.log(strLength);//undefined

var a:number = 12345;
var b:string = <string>a;
//error

var a:number = 12345;
var b:string = <string><any>a;
console.log(b.length) //undefined

why？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？

**Comment by aluanhaddad** [comment]
Type annotations do not change the emitted JavaScript. They are solely for conveying information to the compiler. That means that `b` is a `number`on the second to last line of the example above.

Instead of annotating `b` with the _type_ `string`, use the JavaScript runtime global function `String` to convert the `a` to a `string` like so
```ts
var a = 12345;
var b = String(a);
console.log(b.length); // 5
```

**Comment by JLBear** [comment]
thank you
