### ISSUE TITLE
TS 2.4 regression in --declaration in the presence of optional field

### ISSUE THREAD

**Issue by evmar** [Microsoft/TypeScript#17850]
TypeScript: 2.4.2

```ts
// result.d.ts
export declare class VideoResult {}
export declare type Result = VideoResult;

// user.ts
import {Result} from './result';
export class X {
  constructor(private x?: Result) {}
}
```
Compile fails with:

"Parameter 'x' of constructor from exported class has or is using name 'VideoResult' from external module ".../result" but cannot be named."

Changing the `x?` to just `x` makes it work.  But then the generated `.d.ts` is also wrong:

```ts
  constructor(private x?: number) {}
```

generates

```ts
    private x;
    constructor(x?: number | undefined);
```

Both of these scenarios are correct in TS 2.3.

**Comment by weswigham** [comment]
@mhegazy The first issue,
> "Parameter 'x' of constructor from exported class has or is using name 'VideoResult' from external module ".../result" but cannot be named."
happens under strict null checks mode as when we resolve the type within the union with undefined, we follow the alias symbol to its target when creating the union type in the checker, and since it is a class type (and not a union, intersection, mapped type, etc) it has no alias symbol registered to attempt as a secondary target for writing its name. Recording a single alias symbol for the type isn't even technically a full fix, as it would be defeated simply by having two aliases and only importing the one which was not recorded.

**Comment by mhegazy** [comment]
looks like we can lump this under https://github.com/Microsoft/TypeScript/issues/9944. if the emitter generates module imports for missing types, it would write something like `import {VideoResult} from './result';` and avoid the whole issue.

**Comment by mhegazy** [comment]
closing in favor of #9944.
