### ISSUE TITLE
number data type implements or not a Number type?

### ISSUE THREAD

**Issue by isoftninja** [Microsoft/TypeScript#17927]
For its language segment I'm writing a detailed tutorial for TypeScript.
But there is one thing that I cannot understand. The data type t implements the data type T?
Or the data type of t compatible with the data type T?
(t === number, string, boolean, symbol, object)
(T === Number, String, Boolean, Symbol, Object)

**Comment by aluanhaddad** [comment]
The types `number`, `string`, `boolean`, and `symbol` are the types of values of literals of each of their respective types as well as operators on those types and various conversions.
For example:
```ts
"hello world" // literal -> type of expression is string
var s = "hello world"; // -> type of s is string
```
These types also arise from operations that perform conversions
For example:
```ts
+"12" //  literal (type string) converted via `+`-> expression has type number
```
Another way to write the above is to invoke the JavaScript built in function object `Number`
```ts
Numer("12") // literal (type string) converted by calling `Number`-> expression has type number
```
All of these uses are fine and all produce values of types corresponding to the lowercase variants.

However, where the uppercase variants come into play is when certain JavaScript built in function objects such as the above `Number`, are invoked with `new`.
For example:
```ts
new Number("12") // literal (type string) as ctor arg of `Number`-> expression has type Number
```
These create wrapper objects that have reference identity. They are different types than their literal counterparts.
For example:
```ts
1 === 1
new Number(1) !== 1
new Number(1) !== new Number(1)
```
In typescript, the name of the type of a value created by "newing" a function or class is the name of that function or class.

The uppercase `Number` type exists to represent the objects created by invoking `Number` as a constructor. These objects have different, and in general highly undesirable behavior such as the equality relation shown above.

In practice, the uppercase types should _never_ be used because they represent the values produced by by invoking objects like `Number` as constructors and this should not be done.

**Comment by DanielRosenwasser** [comment]
To add to this, these are also called "wrapper objects", and are used to provide the methods and properties on each primitive.

So for instance, to evaluate `"Hello!".toLowerCase()`, ECMAScript will first try to convert `"Hello!"` to an object (`String`) before fetching a property named `toLowerCase`.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
