### ISSUE TITLE
NPM update installs typescript@2.5.1

### ISSUE THREAD

**Issue by larsenwork** [Microsoft/TypeScript#17939]
Doing an `npm update` with `"typescript": "^2.4.1"` in package.json installs `typescript@2.5.1`

**Comment by houfio** [comment]
Use `~` if you only want to update the patch version

**Comment by kitsonk** [comment]
TypeScript is publishing to NPM just like it always has.  While the RC is published it isn't tagged as latest, so `npm install typescript` will only install latest.

```
'dist-tags': 
   { latest: '2.4.2',
     next: '2.6.0-dev.20170819',
     beta: '2.0.0',
     rc: '2.5.1',
     insiders: '2.5.1-insiders.20170818' },
```

The [NPM](https://docs.npmjs.com/cli/update) documentation isn't clear as to why it is going to 2.5.1 because it isn't tagged as `latest`, but as @houfio pointed out, `~2.4.1` is a safe semver because even when 2.5.X gets its full release, you will suddenly elevate to that on `npm install` anyways.

**Comment by aluanhaddad** [comment]
Other package managers that follow semver should exhibit the same behavior. JSPM also installs 2.5.1 in the same scenario. I imagine that yarn behaves similarly but I haven't tested it.

**Comment by mhegazy** [comment]
In future releases will use `-rc` in the version of the rc to avoid such cases.
