### ISSUE TITLE
this in signature function

### ISSUE THREAD

**Issue by acopalipsis** [Microsoft/TypeScript#17933]
```
class A {
    a: number;

    handler( this: A, event: Event ): void {
        this.a = 0;
    }
}

class B {
    b: string;
}

class C {
    c: boolean;

    on( handler: (this: C, event: Event) => void ): void {}
}

let a = new A();
let c = new C();

c.on(() => a.handler); // Ok, bag? this: A !== this: C
```

```
class Z {
    z: object;
}

class A {
    a: number;

    handler( this: Z, event: Event ): void {
        this.z = {};
    }
}

class B {
    b: string;
}

class C {
    c: boolean;

    on( handler: (this: C, event: Event) => void ): void {}
}

let a = new A();
let c = new C();

c.on(a.handler); // Error is not 
c.on(() => a.handler); // Ok, bag? this: Z !== this: A && this: Z !== this: C
```

**Comment by ahejlsberg** [comment]
This is all working as intended. In the first call to `c.on(() => a.handler)` you're passing a value of type `() => (this: A, event: Event) => void` to a parameter of type `(this: C, event: Event) => void`. It succeeds because the callback function ignores the extra parameters, and the result of the callback is ignored because `void` is expected. In other words, it is safe to pass the parameter list `(this: C, event: Event)` to a function expecting no parameters, and it is safe to return a `(this: A, event: Event) => void` to something that expects no result.
