### ISSUE TITLE
UintArray doesn't accept union of types

### ISSUE THREAD

**Issue by ThomasdenH** [Microsoft/TypeScript#17962]
**TypeScript Version:** 2.5.1

**Code**

```ts
// Create an object that can be ArrayLike<number> or an ArrayBuffer
const arr = [0, 0, 0] as ArrayLike<number> | ArrayBuffer;
// Try to create a new Uint8Array
const uint8array = new Uint8Array(arr);
```

**Expected behavior:**
The code compiles since the possible supplied types are all valid. The constructor for a ```Uint8Array``` accepts both ```ArrayLike<number>``` and ```ArrayBuffer``` as its argument.

**Actual behavior:**
The code won't compile.
```
error TS2345: Argument of type 'ArrayBuffer | ArrayLike<number>' is not assignable to parameter of type 'ArrayBuffer'.
  Type 'ArrayLike<number>' is not assignable to type 'ArrayBuffer'.
```
It seems one of the constructor variants is chosen meaning the other type is not recognized.

**Comment by kitsonk** [comment]
The `lib.es5` is using not using a union in the overloads for the constructor (e.g. old style):

https://github.com/Microsoft/TypeScript/blob/54af8aa945f60dcf42fda1b94c3b637a3251c9af/src/lib/es5.d.ts#L2015-L2016

Because the of the co-variance limitations of TypeScript, this is not allowing the argument to be assigned to either of the overloads.

**Comment by RyanCavanaugh** [comment]
Correct declaration would be
```
     new(arrayOrBuffer: ArrayLike<number> | ArrayBufferLike): Uint8Array; 
     new(buffer: ArrayBufferLike, byteOffset: number, length?: number): Uint8Array; 
```

**Comment by mhegazy** [comment]
thanks @ThomasdenH!
