### ISSUE TITLE
Suggestion: The `object` primitive type

### ISSUE THREAD

**Issue by fdecampredon** [Microsoft/TypeScript#1809]
# The `object` primitive type

This proposal describe a new primitive type for typescript `object`. 
## Use case

JavaScript core api contains some functions that takes `object` as parameter : 
- `Object.getPrototypeOf`
- `Object.getOwnPropertyDescriptor`
- `Object.create`
- ...etc

Currently there is no way in typescript to prevent passing other primitive type (`string`, `number`, etc ...) to those functions.
For example  `Object.create('string')` is a perfectly valid typescript statement, even if it will ends up with an error.
Creating a new `object` primitive type would allows to model more correctly the signature of those function, and every function that share similar constraint.
### Assignability

The `object` type is the equivalent of `{}` minus the assignability of other basic type, that means that : 
- any other basic types are not assignable to `object`
- any non-basic type is assignable to `object`
- object is only assignable to `{}` and `any`

This behavior is coherant to how javascript works, the type represent every value that respect the constraint `typeof value === 'object'` plus `undefined`.
### Type guard

A new type guard has to be introduced for `object` : `typeof value === 'object'`.
Optionally the compiler could also accept comparaison with the `Object` function cast : `Object(value) === value`.

**Comment by RyanCavanaugh** [comment]
It'd be useful to list some APIs other than the `Object.` functions which would benefit from this.

**Comment by fdecampredon** [comment]
In the javascript core api except from `Object` only perhaps some es6 constructs will benefit from this (WeakMap, Proxy etc).
But for example every [underscore collections](http://underscorejs.org/#collections) function would also gain better typing, framework like React use a 'setState' method that accept only object or `null`, ImmutableJS, Mori etc etc.

**Comment by RyanCavanaugh** [comment]
Discussed at suggestion review meeting. This all makes sense, but we need to justify the complexity of a new primitive type with the number of errors / richness of description it is able to provide. Basically, more examples of APIs that can't operate on primitives, especially ones that aren't "expert" APIs (e.g. Proxies)

**Comment by RyanCavanaugh** [comment]
Posting more as reference than recommendation :wink:
```ts
interface String { _primitiveBrand?: string; }
interface Boolean { _primitiveBrand?: boolean; }
interface Number { _primitiveBrand?: number; }

interface ObjectOnly {	_primitiveBrand?: void; }

function fn(x: ObjectOnly) { }

// Error
fn(43);
// Error
fn('foo');
// OK
fn({});
// OK
fn(window);
```

**Comment by sccolbert** [comment]
+1 on this proposal. I wouldn't consider `WeakMap` an "expert" API, but I do consider it reason enough alone to implement this. Since the runtime makes a distinction between object types and primitive types, it only makes sense to have a facility in TypeScript to make the distinction as well. 

This proposal will also solve the problem of typing "object bags" where each property is optional, but other primitive types should be disallowed.

**Comment by sccolbert** [comment]
`Object.observe` requires a non-primitive target as well: http://arv.github.io/ecmascript-object-observe/#Object.observe

**Comment by rotemdan** [comment]
I think the title is a bit confusing since it mentions the word "primitive". This could alternatively be called the _"ECMAScript object type"_ or the _"Runtime object type"_. Which would be assignable from anything other than primitive types (including `undefined` type and symbols), function or constructor types. The criteria for what is a legal `object` type should be based on the following guard:
```ts
let isObject (x) => typeof x === "object";
```
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof), this is the output of `typeof`:

**Undefined**: "undefined"
**Null**: "object" (see below)
**Boolean**: "boolean"
**Number**: "number"
**String**: "string"
**Symbol (new in ECMAScript 2015)**: "symbol"
**Host object (provided by the JS environment)**: Implementation-dependent
**Function object (implements [[Call]] in ECMA-262 terms)**: "function"
**Any other object**: "object"

Without this type, there is no to correctly match a precise type for the above mentioned guard, not even as a user-defined guard. This is also essential for use with any function that strictly requires an object that has properties and allows `for in` loops and calls to the `Object` prototype, and for implementing generic constraints like `T extends object` and then safely referencing properties or using the prototype functions.

Having functions and constructors excluded, though, would be a bit limiting in some cases, so there could be another type that would include them as well and called the _"non-primitive object type"_. A partial workaround could be the union `Function | object` though casts or additional guards would be needed to handle it correctly.

**Comment by RyanCavanaugh** [comment]
Accepting PRs. This seems to be a common problem; this will be a breaking change for anyone brave enough to have written `interface object { ... }`. Implementation should be straightforward and follows the rules outlined above.

Side note: We're all wondering where @fdecampredon has been!

**Comment by fdecampredon** [comment]
@RyanCavanaugh Change of town of work, and unfortunately not a lot of typescript in my new job :D

**Comment by falsandtru** [comment]
Great. I want to use this type in TS1.8.

**Comment by akim-mcmath** [comment]
I would also like to see something like an `object` type. However, I question whether it should conform to `typeof value === 'object'`, as this would exclude functions. Instead, it seems to me that the prospective `object` type should reflect the Object [language type][1], which includes functions. There are a few reasons for this:

- APIs that accept plain objects always, as far as I know, also accept functions.
- [Functions][2] inherit from the [`Object`][3] constructor.

I'll take these in order.

#### APIs

APIs such as [`WeakMap`][4] that only take objects accept the Object language type, not just plain objects. The following is ok:

```js
function theAnswer() {}

let map = new WeakMap();

map.set(theAnswer, 42);
console.log(map.get(theAnswer)); // 42
```

This is as true for custom APIs as it is for built-in APIs. If I expect an object, I usually just want a bundle of properties. Functions are just callable bundles of properties.

#### Inheritance

Since `Function` extends the `Object` constructor, we can use the static and instance methods available on `Object` on functions as well. For example, the following is possible:

```js
class DeepThought {
  static getAnswer() {
    return 42;
  }
}

let computer = Object.create(DeepThought);

console.log(computer.getAnswer()); // 42
console.log(Object.getPrototypeOf(computer)); // [Function: DeepThought]
```

While the example above is a bit silly, it just illustrates that APIs that use the `Object` methods internally could just as well accept functions.

So I would suggest that the `object` type conform to the following, which corresponds to the Object language type (except that it includes [`null`][5], but there's no guarding against `null` in TypeScript in any case).

```js
function isObject(value) {
  return typeof value === 'object' || typeof value === 'function';
}
```

## Use Case

I have a project called [Deep Map][6] that recurses through the key-value pairs of nested objects and transforms primitive values along the way. As such, it distinguishes between primitive and non-primitive types. I had to define a custom [`NonPrimitive`][7] interface, as follows:

```js
interface NonPrimitive {
  [key: string]: any;
  [index: number]: any;
}

export class DeepMap {
  // ...
  private mapObject(obj: NonPrimitive): NonPrimitive { /* ... */ }
}
```

This is not the first time I've had to define the `NonPrimitive` interface. It would be nice if I could just do this:

```js
export class DeepMap {
  // ...
  private mapObject(obj: object): object { /* ... */ }
}
```

As I suggested above, I don't really care whether the `obj` parameter is callable or not. All that matters is that it is of the `Object` *language type*, i.e., that it is a bundle of properties whose key-value pairs I can iterate through.

[1]: http://www.ecma-international.org/ecma-262/6.0/#sec-object-type
[2]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function
[3]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object 
[4]: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/WeakMap
[5]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof#null
[6]: https://github.com/akim-mcmath/deep-map
[7]: https://github.com/akim-mcmath/deep-map/blob/e825ebdb87cef370dab8348c3985902eab86bf4b/src/deep-map.ts#L4-L7

**Comment by RyanCavanaugh** [comment]
I would agree that functions are `object`s. The intent is to exclude primitives.

**Comment by akim-mcmath** [comment]
Ok, I thought that must have been the intent. I just thought maybe I was missing something with all this talk of `typeof value === 'object'`.

**Comment by jdanyow** [comment]
would this `object` type allow ad-hoc property assignment (like `any`)?  For example:

```ts
const foo: object = {};

foo.bar = 'baz';
```

**Comment by RyanCavanaugh** [comment]
No

**Comment by trusktr** [comment]
What's the practical difference between 

```ts
export class DeepMap {
  // ...
  private mapObject(obj: object): object { /* ... */ }
}
```

and

```ts
export class DeepMap {
  // ...
  private mapObject(obj: Object): Object { /* ... */ }
}
```

? (Using `object` vs `Object`). It seems to me that a `Function` extends from `Object`, so I don't see why we can't already do that. Can you explain?

**Comment by akim-mcmath** [comment]
[@trusktr](https://github.com/Microsoft/TypeScript/issues/1809#issuecomment-276006263) All values other than `null` and `undefined` are assignable to the `Object` type; a function that accepts an `Object` will take a string, number, boolean, or symbol. Only non-primitive values are assignable to `object`; passing a string, etc, will produce a compile-time error. The `object` type is useful where we expect a non-primitive value, but where we don't care what its properties are.
