### ISSUE TITLE
Operator '!=' cannot be applied to types x and y but accepting when Y is assigned

### ISSUE THREAD

**Issue by kieykouch** [Microsoft/TypeScript#18114]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**
I just want to alert the community over this OR operation. 
Basically, I understand that my logic is wrong, it is right to have a compile error for my 1st statement. 
But for the 2nd if statement, I'm not sure why it passes. I would expect the consistent behavior.  
```ts
public trying(): void {
    const fakenow: string = "1234";
    // Operator '!=' cannot be applied to types '"12345"' and '"112"'.
    if (fakenow != "12345" || fakenow != "112") {
      console.log("HA");
    }
   // consider normal.
  const fakestring: string = "5";
   if (fakenow != "12345" || fakenow != fakestring) {
      console.log("HA");
    }
}
```

**Expected behavior:**
2nd IF statement doest alert any error.

**Actual behavior:**
Compile error with Operator '!=' cannot be applied to types

**Comment by mhegazy** [comment]
In the first if statement, `fakenow != "12345"` narrows the type of `fakenow` to `"12345"` in the next portion of the `||` operator, so the compiler can say that `fakenow != "112"` is an invalid check, since `"12345"` and `"112"` are not comparable.

in the second if statement, same happens, except that in the second operand of `||`, you used `fakestring` which has the explicit type annotation `string`. `"12345"`  and `string` are comparable, since `string` has `"12345"` as one of its possible values.

Note that if you remove the explicit `string` annotation, you will get the expected errors in all four checks.

**Comment by kieykouch** [comment]
thank you mhegazy
