### ISSUE TITLE
Extract function should compute minimal set of args and return values

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#18138]
```ts
function foo() {
	let x = 10;

	x = 20;
	let y = x;
}
```

- select `x= 20; let y = x;`
- extract function

```ts
function newFunction(x: number) {
    x = 20;
    let y = x;
    return x;
}
```

The function neither needs to take a parameter nor return a value.

**Comment by mhegazy** [comment]
to do this correctly we need some sort of liveness analysis. i would say this is something we can get to in the future.

**Comment by RyanCavanaugh** [comment]
I would much rather preserve the *intent* of the extracted code than to try to reason about what its *semantics* are (which are very much in flux when someone is writing code). Maybe the author is about to replace `20` with a more complex expression involving `x`?

We shouldn't see extract method as a runtime machine code transform involving the exact behavior of the code as written - it's a "please move this code for me" feature that should preserve as much of the intent of the original code as possible, even if that intent is temporarily nonsense.

**Comment by dbaeumer** [comment]
I partly disagree. It is quite common to extract the end of a method into something new. It simply makes more work if I then have to remove parameters and return values by hand. I used extract method in quite some tools so far (Eclipse and Visual Studio) and they both compute a minimal signature.

**Comment by kitsonk** [comment]
It is arguable though that you are going to _have_ to do something with that code, as extracted it is simply a no-op.  One persons reduction is another person productivity gain.

Even extracting it requires some sort of _guessing_ at intent, because:

```js
x = 20;
let y = x;
```

Needs to be written as:

```js
function newFunction() {
    let x;
    x = 20;
    let y = x;
}
```

...or...

```js
function newFunction() {
    const x = 20;
    let y = x;
}
```

...or...


```js
function newFunction() {
    var x;
    x = 20;
    let y = x;
}
```

...or this, which would be dangerous and disallowed in strict mode...

```js
function newFunction() {
    x = 20;
    let y = x;
}
```

So which one would be your ideal?

I would say that as it is now is the most _authentic_ extraction.  It would have the least collateral effects too when dealing with primitive and non-primitive values.

**Comment by RyanCavanaugh** [comment]
Haven't heard this feedback from anyone else
