### ISSUE TITLE
logic '&&' operator breaks type safety

### ISSUE THREAD

**Issue by johnemau** [Microsoft/TypeScript#18190]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

I can use the logic '&&' operator combined with an assignment to break type safety.

**Code**

```ts
const emptyString: string = "";
const bool: boolean = emptyString && true; // type should be `string | boolean`

console.log(bool);        // expected: false,     actual: ""
console.log(typeof bool); // expected: "boolean", actual: "string"
```
--> [Playground](http://www.typescriptlang.org/play/index.html#src=const%20emptyString%3A%20string%20%3D%20%22%22%3B%0D%0Aconst%20bool%3A%20boolean%20%3D%20emptyString%20%26%26%20true%3B%20%2F%2F%20type%20should%20be%20%60string%20%7C%20boolean%60%0D%0A%0D%0Aconsole.log(bool)%3B%20%20%20%20%20%20%20%20%2F%2F%20expected%3A%20false%2C%20%20%20%20%20actual%3A%20%22%22%0D%0Aconsole.log(typeof%20bool)%3B%20%2F%2F%20expected%3A%20%22boolean%22%2C%20actual%3A%20%22string%22) <--

**Expected behavior:**
Typescript error: `Type 'string' is not assignable to type 'boolean'.`
The fix would be to make it a union type `string | boolean`.

**Actual behavior:**
No error.

**Comment by ognjenjevremovic** [comment]
@johnemau This is actually an intended feature of Typescript.
Hence that's how _JavaScript_ works.

Here's whats actually happening :
 * You define a variable `emptyString` (in your case) and assign it to an empty string,
 * You define a variable `bool` which is of type `boolean` and assign it a value, using a logical `&&` (and) operator - the value you assigned is a `falsey` value (empty string),
 * The output of the logical operator is stored as the value of your `bool` variable.
The actual output of your logical `&&` (and) operator is the `falsey` value stored in your `emptyString` variable.

This is the intended feature, as of how the logical `&&` (and) operator works in _JavaScript_:
```text
Logical AND (&&) | expr1&&expr2 | Returns expr1 if it can be converted to false; otherwise, returns expr2. Thus, when used with Boolean values, && returns true if both operands are true; otherwise, returns false.
```
taken from the [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_Operators) documenation.

On the other hand, if you want to make a union type, you need to do it on the variable definition.
Taken from your example, this is how you would define a union type:
```typescript
const bool: boolean | string = false && 'not empty string';
```
_the given example will store a boolean type of `false` to the variable `bool`._

Also, as you've noticed, I altered your example a little to better outline the nature of logiacl `&&` (and) operator.
You can run the example on your own and see the output; maybe it would help you understand it a bit better.

To further improve on the example on the logical operators, if you did switch the places of values in the logical `&&` (and) operator and set your first of two to a `truthy` value, you'd get an error from TypeScript, stating that you can't assign a value of type boolean to a variable of type string :
```typescript
const nonEmptryString = 'non empty string value';
const str: string = 'not empty string' && true;
```
as the first of expressions in the logical `&&` (and) operator evaluates to `truthy` value and the value of the expression2 (`true`) is return and stored in your variable `str`.

And that's why you got an output of `""` when you logging the value of variable bool and the `string` type of your variable `bool` when logging its' type.

Hope this clears it out for you!
If not, feel free to post your doubts again and I'll be sure to check them out.  :)

ognjen

**Comment by johnemau** [comment]
@ognjenjevremovic thank you for the prompt and thorough response!

I see your reasoning that this is working at intended. I also can not think of a way this could introduce any programming bugs because any use of the `bool` variable from my example will be type-coerced into `falsey` by the JavaScript run time (as you pointed out).

Thanks for your time!

**Comment by jwbay** [comment]
Also note that with the `--strictNullChecks` option, you'll get an error on this line.
```ts
const bool: boolean = emptyString && true;
```

**Comment by johnemau** [comment]
Thank you @jwbay, that is exactly the behavior I wanted!
