### ISSUE TITLE
Use static interfaces for Ambient declarations in lib.d.ts

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#182]
Ported from : https://typescript.codeplex.com/workitem/1085

Some core ambient `var`s already do this when the *only* interface is the static one e.g. `JSON` : https://github.com/Microsoft/TypeScript/blob/master/src/lib/core.d.ts#L916-L959

Would be nice to do the name for others like `String`, `Date` perhaps calling them `StringStatic` and `DateStatic`. It is need for definitions for quite a few JavaScript libraries.

**Comment by DanielRosenwasser** [comment]
It looks like this is closed.

**Comment by basarat** [comment]
> StringConstructor be implemented as part of a class or does it contain special functions that can't be implemented

@series0ne  Can't be implemented by a `class`. But stuff like this can be *provided* by a function : http://stackoverflow.com/questions/25340601/typescript-hybrid-type-implementation

:+1: For closing. Haven't had any issues lately :rose:

**Comment by andrewvarga** [comment]
This looks like fixed, but how do I go about adding a custom static property on an inbuilt class?
The concrete example would be to add type info to be able to use this:
Element.ALLOW_KEYBOARD_INPUT

While I've decided not to use this any more (only worked in safari, seemingly doesn't even work there any more), it's a good example because Element doesn't have this defined in lib.d.ts.

**Comment by Draccoz** [comment]
Hey there. I know this issue is long closed now, but don't know if I should open a new issue for that or maybe I'm just missing something.
I wanted to extend `CustomEvent` constructor, to add a custom interface for `detail` when given specific event name (need to do that for `addEventListener` too). For example:
```
interface CustomEvent {
  new(typeArg: 'my-event', eventInitDict?: CustomEventInit & { detail: MyEventDetail }): CustomEvent;
}
interface GlobalEventHandlersEventMap {
  "my-event": Event & { detail: MyEventDetail };
}
```

Is there a chance to achieve that? As far as I can see `CustomEvent` is declared as *var*:
```
declare var CustomEvent: {
    prototype: CustomEvent;
    new(typeArg: string, eventInitDict?: CustomEventInit): CustomEvent;
};
```

So far I have played around but couldn't make it to work :(.
