### ISSUE TITLE
How to build a project webpack with namespaces?

### ISSUE THREAD

**Issue by acopalipsis** [Microsoft/TypeScript#18240]
**Batman.ts**

```
namespace hero {
    export class Batman {}
}
```

**Superman.ts**

```
namespace hero {
    export class Superman {}
}
```

**hero.ts**

```
export const Batman = hero.Batman;
export const Superman = hero.Superman;
```

webpack compile 

```
... webpack helpers

/* 0 */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
Object.defineProperty(__webpack_exports__, "__esModule", { value: true });
const Batman = hero.Batman;
/* harmony export (immutable) */ __webpack_exports__["Batman"] = Batman;

const Superman = hero.Superman;
/* harmony export (immutable) */ __webpack_exports__["Superman"] = Superman;



/***/ })
/******/ ]);
});
```

If you remove the namespaces, then the project compiles as expected. But with namespaces is compiled only hero.ts. What's the matter?

I need the Declaration of the wrapped contents into namespaces. And important condition is to collect project webpack.

**Comment by DanielRosenwasser** [comment]
Hey there, this issue tracker isn't meant to work as a support forum. These questions tend to be better suited for StackOverflow. You may want to open a question up there instead. Thanks!

For the record, you have namespaces that are in global files (i.e. files that have no `import`/`export`), but Webpack operates on modules. Namespaces don't merge across module boundaries, so you'll just get funky behavior. Our advice is just not to use namespaces; use modules.

**Comment by acopalipsis** [comment]
@DanielRosenwasser The fact that I'm writing a library which has only one entry point. That is, in order for it to work correctly, the Declaration must export only one module, and the description must be in a namespace. But generators .d.ts declare module for each module. But this is not correct. To rewrite by hand the modules namespace is not very desirable. What to do in such cases?

On so on complex issues-rare issues quoting the documentation, which I know by heart. And the answer You gave me, I already know. I thought that there is something not documented, especially for such cases.

**Comment by kitsonk** [comment]
Typically when people have a single entry point, the import the sub-modules into the main module which provides the single entry point.  Again this isn't TypeScript _thing_, it is more how to properly structure web application code.

**Comment by acopalipsis** [comment]
@kimamula I understand it! But the Declaration is generated for each module at a time as you need only one, which is the entry point. hide other modules by using namespace. But namespace doesn't work with modules. I do not understand why typescript is not provided.

**Comment by kitsonk** [comment]
I don't think you understand _modular/UMD_ declarations and instead of trying to force _ambient/global_ declarations where they are not required or needed.

[UMD declarations](https://github.com/Microsoft/TypeScript/issues/7125) were introduced in TypeScript 2.0 and are the best way to deal with distributing modular code as a library.  When you emit modules with the `--declaration` flag, TypeScript will emit a single declaration file per module.  When you are authoring TypeScript downstream, when you attempt to import the module, using something like node resolution, TypeScript will resolve the `.d.ts` file the corresponds with the import and handle the appropriate name-spacing without you having to be explicit about it.

You keep saying "we aren't listening" or "don't understand" but honestly, I am the project lead for a large library built on TypeScript with hundreds of modules in 20+ packages (@dojo).  I _might_ actually know what I am talking about.

**Comment by acopalipsis** [comment]
`I don't think you understand modular/UMD declarations and instead of trying to force ambient/global declarations where they are not required or needed.`

I began to write in js, even when es5 was not and went through the entire evolution of the modules until today. But I don't understand why typescript perverted es6 modules. why was it necessary to introduce a namespace and others? I would be very grateful if You would my code showed how to do that in typescript.

**Comment by kitsonk** [comment]
> But I don't understand why typescript perverted es6 modules.

The namespace syntax was a solution to an early spec solution of ES Modules.  TypeScript continued to adapt as the standard evolved, but to avoid breaking syntax backwards compatibility was preserved.  That is not the way to structure your code these days as both I and Daniel have indicated.

You ask for help and then suggest that I am not capable of helping you (and essentially insult me).  Clearly I am not capable of helping you.  Good luck in your endeavours.

**Comment by acopalipsis** [comment]
@kitsonk I'm sorry that You are offended by the words of the school code. But it's true.You have to config the build I saw nothing special, except for obsolete grunt. So Your words about denial of care seem to me to be a whimsical attempt to hurt me. nevertheless, the problem exists, but I guess You really don't realize it. I spent the whole day reading github and so, but on similar issues, I see only links to very different topics.

**Comment by AnimaMundi** [comment]
😄

**Comment by Samoji** [comment]
@acopalipsis the most efficient way I found is this one:
```
// Batman.ts
namespace hero {
    export class Batman {}
}

// this will expose to global scope everything you exported in the namespace
window.hero = { ...window.hero, ...hero } 
```

same for Superman
```
// Superman.ts
namespace hero {
    export class Superman {}
}

window.hero = { ...window.hero, ...hero };
```

**Comment by aminnairi** [comment]
I have exactly the same problem as OP described. I even got further by setting the `compilerOptions.stripInternal` to `true` in the hope that `/** @internal */` annotations were recognized. But they were not.

I finally decided to not use namespace and modules at all and just use TypeScript as a typechecker more than a module resolver. It's just so frustrating that these little annotations do not work. I think it would be perfect to have something like that:

```typescript
// internalLogic1.ts
/** @internal */
export function internalLogic1() {
}
```

```typescript
// internalLogic2.ts
/** @internal */
export function internalLogic2() {
}
```

```typescript
// awesomeHelper.ts
import { internalLogic1 } from './internalLogic1'
import { internalLogic2 } from './internalLogic2'

export function awesomeHelper() {
  internalLogic1()
  internalLogic2()
}
```

And only have the following output (with ts-loader):

```shell
$ ls dist
awesomeHelper.js
awesomeHelper.d.ts
```

What is currently happening is that the bundle get compiled correctly, but we end up with that structure:

```shell
$ ls dist
awesomeHelper.js
awesomeHelper.d.ts
internalLogic1.d.ts
internalLogic2.d.ts
```

Which is not the expected behavior for someone who want to make a library for Node & Web targets. Which is why Webpack is helping in this way with the `umd` target. But TypeScript keeps generating those definition for **all** modules, whether they are part of the `/** @internal */` or not.
