### ISSUE TITLE
Error when loading modules without export using AMD and outFile options

### ISSUE THREAD

**Issue by micnic** [Microsoft/TypeScript#18251]
**TypeScript Version:**  2.5.2

**Code**

```ts
// a.ts
console.log('A');

// main.ts
import './a';

// main.js (output file of the command "tsc -m amd --outFile main.js main.ts")
console.log('A');
define("main", ["require", "exports", "./a"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
});

// When running the following error appear:
// Uncaught Error: Script error for "a", needed by: main
```
gist attached: https://gist.github.com/micnic/eea64a938858e9450bc6a2992cb0105c

**Expected behavior:**
It is expected that the content of the files which are imported without export statement is concatenated without being wrapped in a closure and they are not required anymore in the output file.

**Actual behavior:**
When running the code I get the error that the file `./a` can not be found. This happens because these files are still required in the context of `main.ts` closure in the output file.

**Comment by kitsonk** [comment]
Duplicate of #18232

**Comment by micnic** [comment]
@kitsonk it is not really the same, the problem is that the `a.ts` is concatenated and after, when it is no more "visible", it is required like a normal module

**Comment by kitsonk** [comment]
It is the same, you are trying to load it as a module, but it is being emitted as global JavaScript, and thereby cannot be loaded as a module.  Just because you are concatenating to a single file is immaterial.

**Comment by micnic** [comment]
Sorry, but you did not get my point, I created a gist in this use case: https://gist.github.com/micnic/eea64a938858e9450bc6a2992cb0105c

please download it as zip, unpack it, run `tsc` in the terminal in the directory, open the browser and check the browser console

**Comment by kitsonk** [comment]
I did get your point.

`a.ts` is being emitted as global/plain JavaScript, instead of a module that can be loaded.  This is because TypeScript considers any TypeScript file without imports or exports as a global JavaScript file, not a module that can be loaded.

The `outFile` and the `AMD` target are red herrings to the root problem.  Your problem would go away if you added:

```ts
console.log('A');

export let undefined;
```

to `a.ts`.  Try it, you will notice it fixes your problem.  But it is a workaround versus a solution.

**Comment by aluanhaddad** [comment]
@kitsonk The linked code works fine when `tsc` emits individual files but fails when `outFile` is used. This behavior differs from tools such as [r.js](https://github.com/requirejs/r.js) which emits a named define for `a`'.

**Comment by kitsonk** [comment]
@aluanhaddad depends on what the behaviour is though.  Obviously `console.log('A');` is a non-sensical construct.  The transpiler is not emitting it as a module and that could cause problems depending on the use case.  But yes, I can see how the behaviour changes between the `outFile` or not, but the root cause is still that it isn't being emitted as a module, which only exhibits itself when the files are concatenated.

**Comment by micnic** [comment]
ok, thanks for the explanation, I think this issue can be closed
