### ISSUE TITLE
allow typeof expressions in extends and implements list

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#18271]
```
const Y = { z: 7 };
class X implements typeof Y {} // <-- bummer
```

**Comment by aluanhaddad** [comment]
Yes please, this would be exceedingly convenient.

perhaps this is out of scope but would it be a reasonable to extend this proposal to allow for an implements clause to list any valid type expression such as `T & U`?

**Comment by mhegazy** [comment]
In order to implement this we will have to split parsing for extends and implements into two separate paths, allow only valid expressions/expressions with type parameters in extends, and allow all types in implements.. which is doable..

but then you can write things like:
```ts
class C implements ()=>number { 
  ....
}
```

which looks confusing at best, and frankly ugly...

The scenarios we see here are either the `T & U`, and for that we believe `implement T, U` is more expressive and semantically better aligned with the implements clause needs.

the other is `typeof x`; but it is strange to allow this one and not allow others... and for that using a type alias is not that bad..  

Though the current approach does not support all scenarios, we believe it is at least we are cutting off what can be specified in an implements clause in a consistent and meaningful way.
