### ISSUE TITLE
Promises don't work. An issue with callback overloading, maybe?

### ISSUE THREAD

**Issue by ntrrgc** [Microsoft/TypeScript#1834]
I tried without success to use promises with TypeScript, both with [bluebird](https://github.com/petkaantonov/bluebird) and with es6-promise, using in both cases the definition files of DefinitelyTyped.

These two promise definitions should work:

    new Promise<number>(function (resolve, reject) {
        resolve(3);
    });

    new Promise<number>(function (resolve, reject) {
        var otherPromise = Promise.resolve(3);
        resolve(otherPromise);
    });

In one case `resolve()` is called with a value of type T, and in the other case it is called with a value of type Promise<T>. Both are valid, but it seems both can't work in TypeScript as of 1.4.1.0.

The code of the TypeScript definitions looks like this:

    declare class Promise<R> implements Thenable<R> {
        constructor(callback:(resolve:(result?:R) => void, reject:(error:any) => void) => void);
        constructor(callback:(resolve:(thenable?:Thenable<R>) => void, reject:(error:any) => void) => void);
    }

It seems only the first constructor match is used as long as the first argument is a callback. So in that code only calling `resolve(3)` would work, whilst if you swap the constructor declarations only `resolve(otherPromise)` would.

Stripping parts I found this is the case with other data types. Here is a simpler test case:

    declare class TestCase {
        static test(callback: (resolve: (value : number) => void) => void);
        static test(callback: (resolve: (value : Array<number>) => void) => void);
    }
    
    TestCase.test(function (resolve) {
        resolve([3, 4]);
    });

**Comment by RyanCavanaugh** [comment]
`TestCase` should be written this way:

```ts
interface callback<T> {
	(resolve: T): void;
	(resolve: Array<T>): void;
}

declare class TestCase {
    static test(callback: callback<number>);
}

TestCase.test(function (resolve) {
    resolve([3, 4]);
    resolve(20);
});
```

The same transform applies to `Promise`.

The type system assumes that overloads are "separate" things that have different logic. For example, `$(...)` behaves differently depending on whether you pass it a `string` or an `HTMLElement`. A further assumption on this is that the code implementing a function can't plausibly depend on *what's inside that function* to determine which behavior to take.

So, in this example, `test` cannot meaningfully have two overloads that depend on the type of the function argument of the resolver, because there's no way for it to figure out which you passed it. What you actually have is a *single* overload that (indiscriminately) passes in a resolver with two overloads.

**Comment by ntrrgc** [comment]
Has this changed recently? Note that the non-working code was extracted from original DefinitelyTyped code: https://github.com/borisyankov/DefinitelyTyped/blob/67469b12e480f8e1df580dd82c993f14e0c087ac/es6-promise/es6-promise.d.ts

The above code changed in https://github.com/borisyankov/DefinitelyTyped/commit/c95561be3526f90f0e717734a659d1c01d0492d4, just the same day I opened this issue.

**Comment by RyanCavanaugh** [comment]
The file you just linked appears to be incorrect for the reason I explained in my comment.

**Comment by ntrrgc** [comment]
So it was broken from the beginning (June 2014)...

Anyway, thanks for the explanation. Good to know that now it is fixed.
