### ISSUE TITLE
JSDoc documentation for interface members does not show in tooltips for properties on anonymous objects that are typed to those interfaces

### ISSUE THREAD

**Issue by liviuu** [Microsoft/TypeScript#18358]
**TypeScript Version:**  2.5.2 

**Code**

```ts
interface IMyInterface
{
    /**
     * my property a
     */
    a: string;
}

let o: IMyInterface = { a: "xyz" }; 
```

**Expected behavior:**

When hovering over the property a in the anonymous object, I would expect to see the documentation
for interface IMyInterface property a.

**Actual behavior:**
tooltip shows only "(property) a : string"

**Comment by trendy-weshy** [comment]
Is it this an issue with the editor you're using ? not typescript itself

**Comment by mhegazy** [comment]
Should be fixed in latest. 

If you are using VSCode, it ships with an older version of TypeScript. Please see [Using Newer TypeScript Versions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) documentation for more details on updating your VSCode to use a different version of TypeScript.

**Comment by mhegazy** [comment]
![animation](https://user-images.githubusercontent.com/8000722/30286040-0ec1e90a-96d5-11e7-91ab-54ee89342d2e.gif)
