### ISSUE TITLE
Return type inference or CFA fails by `return void` of conditional clause

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#18366]
**TypeScript Version:**  master

**Code**

```ts
function f() {
  if (0) return void 0;
}
```

**Expected behavior:**

no error

**Actual behavior:**

```
$ node built/local/tsc.js --noImplicitReturns --strictNullChecks index.ts
index.ts(1,10): error TS7030: Not all code paths return a value.
```

**Comment by ahejlsberg** [comment]
This is working as intended. The heuristic we use is that the inferred return type of a function is `void` only when no `return` statement within the function specifies an expression. If one or more `return` statements specify expressions, we require that all code paths end in a `return` statement and we infer a union of the types of those expressions as the return type. Your example falls into the latter category (because you are explicitly returning a value of type `undefined`). You can fix the issue by removing the `void 0` from your return statement.

**Comment by falsandtru** [comment]
Hm, I see. Thanks for your explanation.
