### ISSUE TITLE
type 'never' wrongly infered

### ISSUE THREAD

**Issue by RaduW** [Microsoft/TypeScript#18371]
Typescript Version 2.4.2 

Typescript appears to wrongly infer the type in the following code:
```ts
interface IAction {
    type: string;
}

class Action1 implements IAction{
    type = 'action1';
    //payload: string;
}

class Action2 implements IAction{
    type = 'action2';
    payload: number;
}

type Action = Action1 | Action2;

class ActionTypes {
    static isAction1(action: Action): action is Action1{
        return action.type === 'action1';
    }
    static isAction2(action: Action): action is Action2{
        return action.type === 'action2';
    }
}

function reducer(state: any, action: Action) {
    if (ActionTypes.isAction1(action)){
        return 1; //whatever
    }
    else if (ActionTypes.isAction2(action)) {
        return action.payload; // ERROR !! Property 'payload' does not exist on type 'never'.
    }
}
```

**Code**
the self contained code above will generate the error when compiled with tsc 2.4.2

**Expected behavior:**
after testing for Action1 (with isAction1 ) the inferred type on the else branch (in the reducer function)
should be Action2 ( not never).

**Note** the error happens in the above case and also if there is no type check on the else branch
i.e. if the line
` else if ( actionTypes.isAction2(action)){ `
is replaced with:
` else { `

In my opinion both versions above should be correct.

**Actual behavior:**
When passing the above code to tsc 2.4.2

`tsc checkTs.ts`
the follwoing error output is returned:
`checkTs.ts(31,23): error TS2339: Property 'payload' does not exist on type 'never'. `

When adding a payload to Action 1 (by removing the comment) the error goes away 
( **but only if the payload type is not number**) or if a property with a different name (i.e. not payload)  is added.

**Comment by ahejlsberg** [comment]
This is working as intended, but it is a bit subtle.

In your example, the `type` properties in `Action1` and `Action2` are inferred to be of type `string` (as opposed to a literal type) because they are mutable locations. This means that `Action2` is assignable to `Action1` (i.e. it is just a specialized `Action1`). Thus, when `isAction1` returns true, we eliminate both `Action1` and `Action2` from the type, and you're left with `never`.

The easiest fix is to add a `readonly` modifier to the `type` propeties (presumably they are readonly). The compiler will then infer the string literal types `"action1"` and `"action2"` and things will work the way you expect because `Action1` and `Action2` aren't assignable to each other.

```ts
class Action1 implements IAction{
    readonly type = 'action1';  // Now of type "action1"
    //payload: string;
}

class Action2 implements IAction{
    readonly type = 'action2';  // Now of type "action2"
    payload: number;
}
```

**Comment by RaduW** [comment]
Great, thank you !
