### ISSUE TITLE
Don't return suggestions immediately after literal

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#18399]
**TypeScript Version:**  2.5.2
**Code**

```js
'abc'|
```
Trigger a `completions` request at the `|`

**Expected behavior:**
No suggestions are returned since this is not a valid context.

**Actual behavior:**
The standard global suggestions are returned.

![screen shot 2017-09-11 at 4 34 44 pm](https://user-images.githubusercontent.com/12821956/30301361-24610e1e-970f-11e7-9e17-93b2b4bbc6d3.png)

Other cases:

```
1 |
null |
a |
```

**Comment by mhegazy** [comment]
we have been intentionally lenient here. the reason is at many instances the code is not correct. so the context, or what the parser thinks is a context is not usually what the user wants.. an example of this something like:

```ts
var x:  |
Object;
```

The rule is really to limit the list when it is more of a distraction, e.g. in an identifier definition locaiton, like variable name, or in a class method body..

For these case here, these are only enabled when completion is requested explicitly, (Ctrl + Space), so i am not sure i feel the need to restrict completions and possible hinder some valid scenarios just to avoid a completion list when users explicitly ask for it.
