### ISSUE TITLE
What works in `require` results in module not found when using `import`

### ISSUE THREAD

**Issue by RevealedFrom** [Microsoft/TypeScript#18431]
**TypeScript Version:**  2.3

**Visual Studio 2017 15.3.3 Basic Node.js Express Application project**

I have the module `emailjs` (https://github.com/eleith/emailjs) installed globally.  It is located in C:\Users\xxx\AppData\Roaming\npm\node_modules.  This path is set in the project properties.

If I use `var email = require("emailjs/email")`, it works fine.

But if I use `import * as email from "emailjs/email"`, it will fail with:

> Build: Cannot find module 'emailjs/email'.

**Comment by RevealedFrom** [comment]
Same build error with:

    import * as config from "../config.json"

But following is fine:

    var config = require("../config.json")

**Comment by mhegazy** [comment]
`var config = require("../config.json")` "works" because you have a function declaration for `require` somewhere in your project that looks like `declare function require(a: string): any`. The compiler was not doing any module resolution in this case.

For importing .json files in node, please see https://github.com/Microsoft/TypeScript/issues/7071.

See https://www.typescriptlang.org/docs/handbook/module-resolution.html for more information about how the compiler resolves modules.

**Comment by RevealedFrom** [comment]
Does it mean that, for the two examples listed, the modules are actually resolvable by the run time, but it is just the compiler blocking the build?

**Comment by kitsonk** [comment]
It means that the compiler does not have sufficient information to know they are resolvable at runtime.  TypeScript cannot predict the future, it can only interpret the information you provide it.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
