### ISSUE TITLE
The operand of an increment or decrement operator must be a variable or a property access.

### ISSUE THREAD

**Issue by acopalipsis** [Microsoft/TypeScript#18463]
```
class Test {
    a(i: number): number {
        return i;
    }
    b(i: number): number {
        return this.a( i ) ++; // Error. Bug?
    }
}
```

**Comment by kitsonk** [comment]
TypeScript is protecting you from doing something that is non-sensical, because the increment operator is intended to increment a value of a variable or property.  In this case it isn't.  While it is valid runtime syntax, a big part of the operators behaviour is missing, trying to point out you are making a logic error.  Because if you are not trying to increment a variable or property, it would be much clear to just write:

```ts
class Test {
    a(i: number): number {
        return i;
    }
    b(i: number): number {
        return this.a( i ) + 1;
    }
}
```
