### ISSUE TITLE
User-defined type guard narrows variables weirdly.

### ISSUE THREAD

**Issue by bowenni** [Microsoft/TypeScript#18560]
**TypeScript Version:**  2.4.2

**Code**
With "--strictNullChecks" turned on:
```ts
class C {};
class A {};
const ac: A|C = Math.random() ? new A() : new C();
ac; // Type of ac is A|C, OK.
if (ac instanceof A) {}
ac; // Type of ac is A|C, OK
```
```ts
class C {};
class A {};
const ac: A|C = Math.random() ? new A() : new C();
declare function isA(x: any): x is A;
ac; // Type of ac is A|C, OK
if (isA(ac)) {}
ac; // Type of ac is A, Why?
```

**Expected behavior:**
I'm expecting:
(1). the built-in type guards to be consistent with user-defined type guards when narrowing variables.
(2). to understand why the last ac is type narrowed to type A.

**Actual behavior:**
Inconsistency between built-in type guards and user-defined type guards.

**Comment by mhegazy** [comment]
I think your sample comments are not accurate. here is what i expect (and see on latest):

```ts
class C { };
class A { };

declare function isA(x: any): x is A;

const ac: A | C = Math.random() ? new A() : new C();

function g() {
	ac; // A | C
	if (ac instanceof A) {
		ac; // A
	}
	else {
		ac; // C
	}
	ac; // A | C
}

function f() {
	ac; // A | C
	if (isA(ac)) {
		ac; // A | C
	}
	else {
		ac; // never
	}
	ac; // A | C
}
```

Both will try to remove some types from the union to narrow. there is a subtle difference in the behavior of `instanceof` to account for its nominal nature. 

user defined type guards behave like the rest of the system. in a sense the assumption here is you are writing these structural type check, by checking some properties on the object in question.
since the two types are structurally equivalent, in the true branch it is `A`, in the false branch it is `never` since `C` is also removed from the union.


`instanceof` on the other hand adds a check for identity of the type, and will only remove the type in the false branch if it was explicitly listed in the union. 

really the `instanceof` is the odd one here. everything else is structural.

**Comment by rjamet** [comment]
Thanks ! Your example makes sense to me, and that helped a lot understand some weird behaviors. I don't see inconsistencies in yours, but mine still does (in my 2.4.2 at least: do you think latest behaves differently?). If I mix both of our examples, I still see a bug

```
class C {};
class A {};
const ac: A|C = Math.random() ? new A() : new C();
declare function isA(x: any): x is A;

function f() {
  ac;  
  if (isA(ac)) {
    ac;
  }
  ac; 
  if (!(ac instanceof A)) {
    ac; // C, ok
  }
}

ac; 
if (isA(ac)) {
  ac; 
}
ac;  // Type of ac is A, Why?
if (!(ac instanceof A)) {
  ac; // ac is Never, should be C?
}

function g() {
  ac; 
  if (isA(ac)) {
    ac;
  }
  ac; 
  if (!(ac instanceof A)) {
    ac; // C, ok
  }
}
```

That ac narrowing to A isn't wrong from a structural typing point of view (and when I make those two classes explicitly incompatible with private fields, everything behaves right). But that retyping-at-a-distance makes things weird, and the typechecker understands the instanceof is always false, while it shouldn't.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by rjamet** [comment]
I still suspect something is fishy in the previous example, but the behavior could be justified in some way by static typing. Would you say that's WAI ?
