### ISSUE TITLE
Mutually exclusive type guards on union types when using arrays won't compile in strictNullChecks mode

### ISSUE THREAD

**Issue by Ajk4** [Microsoft/TypeScript#18592]
**TypeScript Version:** 2.5.2

**Code**

```ts
type A = {
  field_num: number,
}
type B = {
  field_string: string
}

type A_OR_B = A | B

function isA(a_or_b: A_OR_B, type: string): a_or_b is A
function isA(a_or_b: A_OR_B[], type: string): a_or_b is A[]

function isA(a_or_b: A_OR_B | A_OR_B[], type: string): any {
  return type == "A";
}

function isB(a_or_b: A_OR_B, type: string): a_or_b is B
function isB(a_or_b: A_OR_B[], type: string): a_or_b is B[]

function isB(a_or_b: A_OR_B | A_OR_B[], type: string): any {
  return type == "B";
}

const type = "A";

const oneElement = {
  field_num: 5
} as A_OR_B;

if (isA(oneElement, type)) {
  oneElement.field_num
} else if(isB(oneElement, type)){
  oneElement.field_string
} else {
  // OKAY - it's proven that a_or_b is neither A or B, so it's never.
  const ex: never = oneElement
}

const list = [
  {
    field_num: 5
  }
] as A_OR_B[];

if (isA(list, type)) {
  // OKAY - compiles A field
  list[0].field_num
} else if(isB(list, type)){
  // OKAY - compiles with B field
  list[0].field_string
} else {
  // NOT COMPILES, no exhaustive check
  const ex: never = list
  // Also won't work
  const ex: never = list[0]
}
```

**Expected behavior:**

List assigment to never type should compile. Note that it works properly for single element.

**Actual behavior:**

It doesn't compile and return error.

```
error TS2322: Type 'A_OR_B[]' is not assignable to type 'never'.
```

**Comment by ahejlsberg** [comment]
This is working as intended. To get the expected behavior you need to change the `isA` declaration to something involving a union of distinct choices that can be conclusively eliminated by the type guards:

```ts
function isA(a_array_or_b_array: A[] | B[], type: string): a_array_or_b_array is A[];
```

Another way to think of it is that an `(A | B)[]` can contain a mix of As and Bs, whereas an `A[] | B[]` is either an array of all As or an array of all Bs. Your user defined type guards are checking for the cases of pure arrays, but in your original code the array *could* still be a mix in the `else` case.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
