### ISSUE TITLE
noUnusedParameters and rest parameters

### ISSUE THREAD

**Issue by jamiewinder** [Microsoft/TypeScript#18653]
**TypeScript Version:**  2.5.2

There are some situations where you need to destructure a property from an object in order to exclude it from the rest:

**Code**

```ts
function test(
    { a, ...rest }: { a: number, b: number, c: number},
    fn: (params: { b: number, c: number}) => void
) {
    fn(rest);
}
```
(Real life example: extract a prop in React so you can forward the rest to the inner component)

However, if I do this with noUnusedParameters, I get an error ('a' is unused). I'd argue that in this particular scenario, it's not unused as such because it's necessary to isolate it from the rest of the parameters.

I can do the following to workaround the problem:
```ts
function test(
    { a: _, ...rest }: { a: number, b: number, c: number},
    fn: (params: { b: number, c: number}) => void
) {
    fn(rest);
}
```
But I thought I'd raise this regardless.

**Comment by andy-ms** [comment]
IMO the workaround makes for better code, because with `--noUnusedParameters` on you can assume that any identifier gets used unless intentionally marked otherwise.
You should also just be able to do `function test(x: { a, b, c }, fn: (params: {b, c}) => void) { fn(x) }` in the usual case due to subtyping.

**Comment by DanielRosenwasser** [comment]
Related is #12766.
