### ISSUE TITLE
keyof operator corrupted if object which contains call signature passed to generic function.

### ISSUE THREAD

**Issue by brn** [Microsoft/TypeScript#18715]
**TypeScript Version:**  2.6.0-dev.20170922

**Code**

```typescript
function test<T>(target: T, name: keyof T) {}

test({ a: 1, b: 2, c: 3, d() {} }, "d");
```

but below code worked.

```typescript
function test<T>(target: T, name: keyof T) {}

test({ a: 1, b: 2, c: 3, d: () => {} }, "d");
```

Probably keyof operator can't iterate over properties if object contains method signature passed as function arguments.
And then, below code worked expectedly.

```typescript
function test<T>(target: T): keyof T {
  return "a" as any;
}

const k = test({ a: 1, b: 2, c: 3, d() {} });
// typeof k = 'a' | 'b' | 'c' | 'd'
```

**Expected behavior:**

Compiled

**Actual behavior:**

Error occured.
`error TS2345: Argument of type '"d"' is not assignable to parameter of type 'never'.`

I think this issue caused by `getPropertiesOfObjectType` of `checker.ts` not return callSignatures.

**Comment by sandersn** [comment]
The root problem is that contextual typing is interfering with type inference. During type inference, the compiler sees that the object literal contains a method `d() { }` that is contextually typed, so it might be affected by other arguments. Consider the functional-like example below:

```ts
declare function f(n: number): number;
declare function two<T>(first: T, second: T): void;
two(n => n + 1, f);
```

This example is silly but it's similar in structure to things like `pipe` or `apply` or `compose`. The type inference algorithm notices that `n => n + 1` is contextually typed, so it defers inference to a second round. Then it picks up a good inference from `f`, and can successfully fix the type of `n: number` and look for inferences from `n => n + 1`. (In this example it won't find anything new since it's just trying to infer to `T`, but it might if you were inferring to `(t: T) => U` or something.)

The problem is that the next inference is to `keyof T`, which only produces inferences for things like `keyof U ==> keyof T`. `"d" ==> keyof T` just does nothing. So the inferred type argument is `{}`, `keyof {}` is `never` (the empty string literal union), and `"d"` is not assignable to `never`.

The next question is why your last example succeeds. I'll go look at that next, and maybe it will give me some ideas for how to work around the contextual typing problem in the first example.

**Comment by sandersn** [comment]
The reason that the last example works while the first does not is that type inference has a loop that progressively tries to infer from more and more contextually typed arguments. The catch is that the loop stop whenever an error occurs. So the last example looks like this:

```ts
badInference({ a: 1, b: 2, c: 3, d(n) { return n } });
```

1. Skip the first (and only) argument. Infer `T={}`.
2. Is `{ a: 1, b: 2, ...}` assignable to `{}`? Yes.
2. Are there skipped arguments? Yes.
3. Reinstate the first argument. Infer `T={ a: number, b: number, c: number, d: (n: any) => any }`
4. Is `{ a: 1, b: 2, ...}` assignable to `{ a: number, b: number, c: number, d: (n: any) => any }`? Yes.
5. Succeed.

The first example goes like this:

1. Skip the first argument.
2. Infer from the second argument `"d"` to `keyof T`. No inferences, so infer `T={}` again.
3. Is `{ a: 1, b: 2, ...}` assignable to `{}`? Yes. Is `"d"` assignable to `keyof {}`. No.
4. Fail and report error.

This is a design limitation of the inference algorithm combined with contextual typing. I'll think about whether it's possible to fix it.

**Comment by sandersn** [comment]
I found a small ad-hoc fix. It's up at #19159, but I need @ahejlsberg to look at it since overload resolution and type inference are very complicated. :)
