### ISSUE TITLE
Error TS2304: Cannot find name 'Record'

### ISSUE THREAD

**Issue by MateoRJ96** [Microsoft/TypeScript#18724]
I just install Bootstrap 4 latest from the 'Package Manager Console' in VS. When I compile the project show some errors about file index.d.ts.

Note: I am working with ASP.net MVC 5

Errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Build:Cannot find name 'Record'.	MyFirstWebSiteASPNetMVC5	C:\Users\Mateo\documents\visual studio 2015\Projects\ProbandoASPnet_MVC5\MyFirstWebSiteASPNetMVC5\Scripts\index.d.ts	68	

Severity	Code	Description	Project	File	Line	Suppression State
Error	TS2304	Cannot find name 'Record'.	MyFirstWebSiteASPNetMVC5	C:\Users\Mateo\documents\visual studio 2015\Projects\ProbandoASPnet_MVC5\MyFirstWebSiteASPNetMVC5\Scripts\index.d.ts	68	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error		Build:Cannot find name 'undefined'.	MyFirstWebSiteASPNetMVC5	C:\Users\Mateo\documents\visual studio 2015\Projects\ProbandoASPnet_MVC5\MyFirstWebSiteASPNetMVC5\Scripts\index.d.ts	68	

Severity	Code	Description	Project	File	Line	Suppression State
Error	TS2304	Cannot find name 'undefined'.	MyFirstWebSiteASPNetMVC5	C:\Users\Mateo\documents\visual studio 2015\Projects\ProbandoASPnet_MVC5\MyFirstWebSiteASPNetMVC5\Scripts\index.d.ts	68	Active

**Comment by DanielRosenwasser** [comment]
Hi there. Could you please provide [the information that our issue template requested](https://raw.githubusercontent.com/Microsoft/TypeScript/master/issue_template.md) (e.g. version numbers etc.) so that we can appropriately diagnose the issue? Thanks!

It sounds like you might just be working with an outdated version of TypeScript and you'll need to get an older version of Bootstrap's `.d.ts` files.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
