### ISSUE TITLE
combinatorial explosion of recursive unions definitions.

### ISSUE THREAD

**Issue by sledorze** [Microsoft/TypeScript#18754]
**TypeScript Version:**  2.5.2

**Code**

```ts
type A = { tag: 'a', pa: ALL}
type B = { tag: 'b', pb: ALL}
type C = { tag: 'c', pc: ALL}
type D = { tag: 'd', pd: ALL}
type E = { tag: 'e', pe: ALL}
type ALL = A | B | C | D | E
```

**Expected behavior:**

When hovering on pa ... pe members, we see a few types, ideally just 'ALL'.

**Actual behavior:**

When hovering on pa ... pe members, we see an explosion of types.

**Comment by DanielRosenwasser** [comment]
I'm not seeing this in the playground or the nightlies.

**Comment by sledorze** [comment]
@DanielRosenwasser I've seen that in VSCode, can you try in it?

I have two concerns:
- It lags terribly when editing.
- I'm afraid this pattern could lead to some OOM when compiling.
for information, in VSCode, the class version does not exhibit the issue.

```typescript
class CA { tag: 'a'; pa: CALL }
class CB { tag: 'b'; pb: CALL }
class CC { tag: 'c'; pc: CALL }
class CD { tag: 'd'; pc: CALL }
class CE { tag: 'e'; pc: CALL }
type CALL = CA | CB | CC | CD | CE
```

**Comment by mhegazy** [comment]
Can you share some more context. like a bigger code sample?

**Comment by sledorze** [comment]
@mhegazy @DanielRosenwasser oh that's strange!

It appears, it happens when I do an import like this at the top of the file:

```typescript
import * as t from 'io-ts' 

type A = { tag: 'a', pa: ALL}
type B = { tag: 'b', pb: ALL}
type C = { tag: 'c', pc: ALL}
type D = { tag: 'd', pd: ALL}
type E = { tag: 'e', pe: ALL}
type ALL = A | B | C | D | E
```

Here's a repo exhibiting the issue, this one with latest TS 2.6.0-dev.20170926 ( happens on both that version and 2.5.2, I've not checked others ) :
https://github.com/sledorze/tsInferenceIssue

**Comment by sledorze** [comment]
Actually, I'm even not requiring io-ts, I've updated the repo with a version that just tries to import an empty module.

**Comment by sledorze** [comment]
Another variations happens with just 

```typescript

export { }

type ZA = { tag: 'a', pa: ALL }
type ZB = { tag: 'b', pb: ALL }
type ZC = { tag: 'c', pc: ALL }
type ZD = { tag: 'd', pc: ALL }
type ZE = { tag: 'e', pc: ALL }
type ALL = ZA | ZB | ZC | ZD | ZE

```

Here's a playground link to it:
https://www.typescriptlang.org/play/#src=export%20%7B%7D%0D%0A%0D%0Atype%20A%20%3D%20%7B%20tag%3A%20'a'%2C%20pa%3A%20ALL%20%7D%0D%0Atype%20B%20%3D%20%7B%20tag%3A%20'b'%2C%20pb%3A%20ALL%7D%0D%0Atype%20C%20%3D%20%7B%20tag%3A%20'c'%2C%20pc%3A%20ALL%7D%0D%0Atype%20D%20%3D%20%7B%20tag%3A%20'd'%2C%20pd%3A%20ALL%7D%0D%0Atype%20E%20%3D%20%7B%20tag%3A%20'e'%2C%20pe%3A%20ALL%7D%0D%0Atype%20ALL%20%3D%20A%20%7C%20B%20%7C%20C%20%7C%20D%20%7C%20E%0D%0A

**Comment by sledorze** [comment]
Also this one exhibit the error

```typescript
type ZA = { tag: 'a', pa: ALL }
type ZB = { tag: 'b', pb: ALL }
type ZC = { tag: 'c', pc: ALL }
type ZD = { tag: 'd', pc: ALL }
type ZE = { tag: 'e', pc: ALL }
type ALL = ZA | ZB | ZC | ZD | ZE
export {  ALL }
```

whereas this one not

```typescript
type ZA = { tag: 'a', pa: ALL }
type ZB = { tag: 'b', pb: ALL }
type ZC = { tag: 'c', pc: ALL }
type ZD = { tag: 'd', pc: ALL }
type ZE = { tag: 'e', pc: ALL }
export type ALL = ZA | ZB | ZC | ZD | ZE
```

So there's a kind of 'workaround' so far..

**Comment by sledorze** [comment]
@mhegazy @DanielRosenwasser enough information to emit a judgment if either this is a bug or a by design limitation?

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by DanielRosenwasser** [comment]
This is definitely undesirable behavior, but can you give us more context on how you're running into this in the first place? Specifically, what is the motivating use-case?

**Comment by mhegazy** [comment]
I am unable to get a repro for the issue described in this thread. @sledorze can you share a self-contained repro for the issue.

**Comment by sledorze** [comment]
@mhegazy here's a playground link that reproduce the issue:
https://www.typescriptlang.org/play/#src=export%20%7B%7D%0D%0A%0D%0Atype%20A%20%3D%20%7B%20tag%3A%20'a'%2C%20pa%3A%20ALL%20%7D%0D%0Atype%20B%20%3D%20%7B%20tag%3A%20'b'%2C%20pb%3A%20ALL%7D%0D%0Atype%20C%20%3D%20%7B%20tag%3A%20'c'%2C%20pc%3A%20ALL%7D%0D%0Atype%20D%20%3D%20%7B%20tag%3A%20'd'%2C%20pd%3A%20ALL%7D%0D%0Atype%20E%20%3D%20%7B%20tag%3A%20'e'%2C%20pe%3A%20ALL%7D%0D%0Atype%20ALL%20%3D%20A%20%7C%20B%20%7C%20C%20%7C%20D%20%7C%20E%0D%0A

just hover over the ALL definition to see the types..

@DanielRosenwasser the use case is implementing a recursive algebra (a Query AST); the obvious work around is using interfaces instead of types but I found that pretty counter intuitive and unhandy that adding an export changes the type inference.

**Comment by gcnew** [comment]
I've been experiencing the same problem. I've converted all of [minijs](https://github.com/gcnew/parakeet/blob/master/tests/cases/minijs.ts#L41-L69)' AST types to interfaces, because IntelliSense was stopping to show up and after a considerable wait, tsserver was crashing.

Here's a [playground link](https://www.typescriptlang.org/play/#src=export%20%7B%20%7D%0D%0A%0D%0A%2F*%20Statement%20types%20*%2F%0D%0Atype%20ExprStatement%20%3D%20%20%20%7B%20kind%3A%20'expr_statement'%2C%20%20%20expr%3A%20%20%20%20%20%20%20Expr%20%20%20%20%20%20%20%20%7D%0D%0Atype%20ReturnStatement%20%3D%20%7B%20kind%3A%20'return_statement'%2C%20expr%3A%20%20%20%20%20%20%20Expr%20%20%20%20%20%20%20%20%7D%0D%0Atype%20BlockStatement%20%3D%20%20%7B%20kind%3A%20'block_statement'%2C%20%20statements%3A%20Statement%5B%5D%20%7D%0D%0A%0D%0Atype%20ConstDecl%20%3D%20%20%20%20%7B%20kind%3A%20'const_decl'%2C%20%20%20%20name%3A%20string%2C%20expr%3A%20%20%20Expr%20%7D%0D%0Atype%20FunctionDecl%20%3D%20%7B%20kind%3A%20'function_decl'%2C%20name%3A%20string%2C%20params%3A%20string%5B%5D%2C%20%20%20%20%20%20%20body%3A%20%20%20%20%20BlockStatement%20%7D%0D%0Atype%20IfStatement%20%3D%20%20%7B%20kind%3A%20'if_statement'%2C%20%20cond%3A%20Expr%2C%20%20%20ifTrue%3A%20BlockStatement%2C%20ifFalse%3F%3A%20BlockStatement%20%7D%0D%0A%0D%0A%0D%0A%2F*%20Expression%20types%20*%2F%0D%0Atype%20MemberExpr%20%3D%20%20%7B%20kind%3A%20'member_expr'%2C%20obj%3A%20Expr%2C%20%20%20%20%20%20%20%20prop%3A%20%20string%20%7D%0D%0Atype%20IndexExpr%20%3D%20%20%20%7B%20kind%3A%20'index_expr'%2C%20%20obj%3A%20Expr%2C%20%20%20%20%20%20%20%20index%3A%20Expr%20%20%20%7D%0D%0Atype%20CallExpr%20%3D%20%20%20%20%7B%20kind%3A%20'call_expr'%2C%20%20%20fn%3A%20%20%20Expr%2C%20%20%20%20%20%20%20args%3A%20%20Expr%5B%5D%20%7D%0D%0Atype%20LambdaExpr%20%3D%20%20%7B%20kind%3A%20'lambda_expr'%2C%20params%3A%20string%5B%5D%2C%20body%3A%20%20Expr%20%20%20%7D%0D%0A%0D%0Atype%20UnaryExpr%20%3D%20%20%20%7B%20kind%3A%20'unary_expr'%2C%20%20%20op%3A%20%20%20string%2C%20expr%3A%20%20%20Expr%20%7D%0D%0Atype%20BinaryExpr%20%3D%20%20%7B%20kind%3A%20'binary_expr'%2C%20%20op%3A%20%20%20string%2C%20left%3A%20%20%20Expr%2C%20right%3A%20%20%20Expr%20%7D%0D%0Atype%20TernaryExpr%20%3D%20%7B%20kind%3A%20'ternary_expr'%2C%20cond%3A%20Expr%2C%20%20%20ifTrue%3A%20Expr%2C%20ifFalse%3A%20Expr%20%7D%0D%0A%0D%0Atype%20VarExpr%20%3D%20%20%20%20%20%7B%20kind%3A%20'var_expr'%2C%20%20%20%20%20name%3A%20%20string%20%20%20%20%20%20%20%20%20%20%20%7D%0D%0A%0D%0A%2F*%20Literals%20*%2F%0D%0Atype%20NumExpr%20%3D%20%20%20%20%20%7B%20kind%3A%20'num_expr'%2C%20%20%20%20%20value%3A%20number%20%20%20%20%20%20%20%20%20%20%20%7D%0D%0Atype%20StrExpr%20%3D%20%20%20%20%20%7B%20kind%3A%20'str_expr'%2C%20%20%20%20%20value%3A%20string%20%20%20%20%20%20%20%20%20%20%20%7D%0D%0Atype%20BoolExpr%20%3D%20%20%20%20%7B%20kind%3A%20'bool_expr'%2C%20%20%20%20value%3A%20boolean%20%20%20%20%20%20%20%20%20%20%7D%0D%0Atype%20ArrayExpr%20%3D%20%20%20%7B%20kind%3A%20'array_expr'%2C%20%20%20value%3A%20Expr%5B%5D%20%20%20%20%20%20%20%20%20%20%20%7D%0D%0Atype%20ObjectExpr%20%3D%20%20%7B%20kind%3A%20'object_expr'%2C%20%20value%3A%20%5Bstring%2C%20Expr%5D%5B%5D%20%7D%0D%0A%0D%0Atype%20RegExpExpr%20%3D%20%20%7B%20kind%3A%20'reg_exp_expr'%2C%20pattern%3A%20string%2C%20flags%3A%20string%20%7D%0D%0A%0D%0A%0D%0A%2F*%20Unions%20*%2F%0D%0Atype%20Literal%20%3D%20NumExpr%20%7C%20StrExpr%20%7C%20BoolExpr%20%7C%20ArrayExpr%20%7C%20ObjectExpr%20%7C%20RegExpExpr%0D%0A%0D%0Atype%20Statement%20%3D%20FunctionDecl%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20ConstDecl%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20IfStatement%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20ExprStatement%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20BlockStatement%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20ReturnStatement%0D%0A%0D%0Atype%20Expr%20%20%20%20%20%20%3D%20Literal%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20VarExpr%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20LambdaExpr%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20MemberExpr%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20IndexExpr%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20CallExpr%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20UnaryExpr%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20BinaryExpr%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20TernaryExpr%0D%0A%0D%0Atype%20Program%20%3D%20Statement%5B%5D) demonstrating the problem when using `type` instead of `interface` (types copied from `minijs`). Hover over `Expr` or any other complex type. Note: if you remove `export {}` aliases are no longer expanded and the issue does not surface.

**Comment by DanielRosenwasser** [comment]
>  I've converted all of minijs' AST types to interfaces

I think that this has been the guidance we've had for users for a while.

Still, I know this is unexpected. @ahejlsberg had an explanation of why we reuse type alias names in global contexts as opposed to within a module.

**Comment by sledorze** [comment]
There's a lot of difference going on now when switching from types to interfaces, I'm referring specifically to variance and type safety.
It is highly desirable not to have to choose between recursivity and type safety (co/contra-variance).

**Comment by mhegazy** [comment]
Should be fixed in latest.
