### ISSUE TITLE
Can't access potential member on union type

### ISSUE THREAD

**Issue by testerez** [Microsoft/TypeScript#18750]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
interface Foo {
  foo: string;
}

interface Bar {
  bar: string;
}

function test(item: Foo | Bar) {
  console.log(item.foo || item.bar)
}
```

**Expected behavior:**
This pattern is very common in javascript, that would be great to make it valid in typescript.

**Actual behavior:**
```
Property 'foo' does not exist on type 'Foo | Bar'.
  Property 'foo' does not exist on type 'Bar'.
Property 'bar' does not exist on type 'Foo | Bar'.
  Property 'bar' does not exist on type 'Foo'.
```

**Comment by kitsonk** [comment]
That would make the type system unsound.  Doing so would cause all sorts of bad code.

You need to understand better how the typing system works.  When you have a Schrödinger's cat type like that, TypeScript will only allow you to access the properties it knows are in common.  If you wanted it to work, you could [change the type](https://www.typescriptlang.org/play/#src=interface%20Foo%20%7B%0D%0A%20%20foo%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20Bar%20%7B%0D%0A%20%20bar%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Afunction%20test(item%3A%20Foo%20%26%20Bar)%20%7B%0D%0A%20%20console.log(item.foo%20%7C%7C%20item.bar)%0D%0A%7D%0D%0A):

```ts
interface Foo {
  foo: string;
}

interface Bar {
  bar: string;
}

function test(item: Foo & Bar) {
  console.log(item.foo || item.bar)
}
```

But it depends on what you are trying to do and represent properly, because you could [narrow the type as well](https://www.typescriptlang.org/play/#src=interface%20Foo%20%7B%0D%0A%20%20foo%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20Bar%20%7B%0D%0A%20%20bar%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Afunction%20isFoo(value%3A%20any)%3A%20value%20is%20Foo%20%7B%0D%0A%20%20return%20'foo'%20in%20value%3B%0D%0A%7D%0D%0A%0D%0Afunction%20test(item%3A%20Foo%20%7C%20Bar)%20%7B%0D%0A%20%20console.log(isFoo(item)%20%3F%20item.foo%20%3A%20item.bar)%0D%0A%7D%0D%0A):

```ts
interface Foo {
  foo: string;
}

interface Bar {
  bar: string;
}

function isFoo(value: any): value is Foo {
  return 'foo' in value;
}

function test(item: Foo | Bar) {
  console.log(isFoo(item) ? item.foo : item.bar)
}
```

**Comment by RyanCavanaugh** [comment]
This has been the behavior forever and is not a bug. See #805

**Comment by testerez** [comment]
But what about stating that type of `(Foo | Bar).foo` is `string | undefined`. It seams pretty reasonable no?

**Comment by kitsonk** [comment]
No.

If you want `Bar` to possibly have `foo` then you can write it that way.

```ts
interface Bar {
  bar: string;
  foo?: string;
}
```

The typing system is designed to be sound.  It isn't designed to be abused.
