### ISSUE TITLE
imports resolve differently from osx to linux

### ISSUE THREAD

**Issue by sebirdman** [Microsoft/TypeScript#18802]
**TypeScript Version:**  2.5.2 (may have happened in older versions as well)

**Code**

`import * as React from 'React';`

on osx resolves fine, typescript finds the import happily
however on linux we get:

`X: error TS2307: Cannot find module 'React'.`

if i change React to react, this resolves properly on both environments.

feels like either typescript should require both to be case sensitive or none of them to be. I don't have a windows environment with me or i'd test that.

**Expected behavior:**
both environments error or work

**Actual behavior:**
linux differs from osx

**Comment by RyanCavanaugh** [comment]
We don't have a flag right now to pretend that file systems are case sensitive when they're not -- this turns out to be quite difficult to reason about and many FS APIs are actively unhelpful in this regard (especially on Windows).

You can enable the `--forceConsistentCasingInFileNames` switch/setting to make sure all of your imports are internally consistent, which helps with the more common problem of having 10 of your imports say `react` and 1 say `React`.

**Comment by sebirdman** [comment]
@RyanCavanaugh oh nice! i didn't see that option. that found all of my problems. 

I understand the difficulty with pretending file systems are case sensitive.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
