### ISSUE TITLE
Promise.all resolves incorrectly with previously declared array.

### ISSUE THREAD

**Issue by psachs21** [Microsoft/TypeScript#18828]
**TypeScript Version:**  2.5.2

**Code**

```ts
function a() {
    return new Promise<string>(resolve => {
        resolve('1')
    });
}

function b() {
    return new Promise<{ obj: number }>(resolve => {
        resolve({ obj: 3 });
    });
}

function c() {
    const promises = [a(), b()];
    return Promise.all(promises).then(data => {
        
    })
}
```

**Expected behavior:**

No Errors

**Actual behavior:**

Type '{ obj: number; }' is not assignable to type 'string'.

**Workaround:**

Inline the promises:

```ts
Promise.all([a(), b()])
```

**Comment by kitsonk** [comment]
It is because you end up with an array with an odd type, because TypeScript has to choose which type, and it choose a type that causes an issue when used later when generics are attempted to be extracted out.  All of the valid types that could be inferred at the assignment point are:

```ts
(Promise<string> | Promise<{obj: number}>)[];
Promise<string | {obj: number}>[];
[ Promise<string> | Promise<{obj: number}> ];
```

It is the first one that gets inferred, but it is the last two that would work find with `Promise.all()` because TypeScript can properly _unwrap_ the generic.  It works when you use the array literal, because TypeScript has more information about how to infer the type.  So this is also a work around:

```ts
function a() {
    return new Promise<string>(resolve => {
        resolve('1')
    });
}

function b() {
    return new Promise<{ obj: number }>(resolve => {
        resolve({ obj: 3 });
    });
}

function c() {
    const promises: Promise<string | { obj: number}>[] = [a(), b()];
    return Promise.all(promises).then(data => {
        
    })
}
```

**Comment by psachs21** [comment]
Ah I think I understand. It would be nice for typescript to infer and merge Promise objects into a shared promise if it can.

```ts
const promises = [a(), b()]; // infers Promise<string | { obj: number}>[]
```

This would cover a very common use case in javascript when you're passing promises around. It would require promises to be dealt slightly differently than other generics.

Just a thought to make dealing with promises a lot easier.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
