### ISSUE TITLE
Unused variable `formatOptions` in `getEditsForRefactor`

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#18850]
**TypeScript Version:**  master (as of #18848)

**Code**

In `client.ts` there is a method `getEditsForRefactor` taking a `formatOptions` parameter that is ignored.
We decided not to take format options along with a refactor request because they should be sent just once instead of once per refactor. It looks like this option has been present and unused since #16307.

Will we need to keep this around, or can it be removed?

**Comment by weswigham** [comment]
Technically not unused as it turns out. The version in `client` is unused, sure, but `client` conforms to the `LanguageService` API, and the one in the `LanguageService` is most certainly used. So while `client` doesn't want it it (because the `session` on the other end is going to inject the format settings into the serverside LS it calls), the API it conforms to requires it accept them. So the `SessionClient` lies a bit - its `getEditsForRefactor` claims to take a `formatOptions` that is actually unused. I'm sure the discrepancy will one day be confusing to some user of the `SessionClient` class - probably one of us, but potentially a `tsserverlibrary` consumer.
