### ISSUE TITLE
Typescript 2.5.3 break date-fns types

### ISSUE THREAD

**Issue by plantain-00** [Microsoft/TypeScript#18872]
**TypeScript Version:**  2.5.3

**Code**

`npm i date-fns` first

```ts
import * as format from 'date-fns/format'
```

**Expected behavior:**

no error

**Actual behavior:**

```
Could not find a declaration file for module 'date-fns/format'. '/path/to/my/project/node_modules/date-fns/format/index.js' implicitly has an 'any' type.
```

Notes: it works with typescript v2.5.2, when I update typescript to v2.5.3, it broke.

The types: https://github.com/date-fns/date-fns/blob/master/typings.d.ts

Original issue: https://github.com/date-fns/date-fns/issues/572

**Comment by RyanCavanaugh** [comment]
@andy-ms has this been fixed for the non-`@` case?

**Comment by andy-ms** [comment]
The package has a file `date-fns/format/package.json` which contains only:

```json
{
  "typings": "../typings.d.ts"
}
```

Previously we would assume that whatever you looked at in `node_modules` was the package root, which is wrong if you're looking for `package/foo`, since the real `package.json` is in `package/package.json`, not `package/foo/package.json`. However, this package was adding a different `package.json` in every subdirectory because that (erroneously) was how it worked in older TypeScript versions.

A solution that should work in both old and new versions of TypeScript would be to create a file `date-fns/format/index.d.ts` like is done with `date-fns/format/index.js.flow`, instead of adding many `declare module` in `date-fns/typings.d.ts`. Then there would be no need for adding `typings` to `package.json` since the definitions would be where we expect them to be anyway.
