### ISSUE TITLE
Switch is considered exhaustive or not based on the code after it

### ISSUE THREAD

**Issue by kendfrey** [Microsoft/TypeScript#18882]
**TypeScript Version:**  2.5.3

**Code**

With `--noImplicitReturns`:

1:
```ts
function foo(bar: "a"): number
{
    switch (bar)
    {
        case "a":
            return 1;
    }
}
```
2:
```ts
function foo(bar: "a"): number
{
    switch (bar)
    {
        case "a":
            return 1;
    }

    let unreachable;
}
```
3:
```ts
function foo(bar: "a"): number
{
    switch (bar)
    {
        case "a":
            return 1;
    }

    function doNothing()
    {
    }
}
```

**Expected behavior:**

Either:

(1), (2), and (3):
> error TS2366: Function lacks ending return statement and return type does not include 'undefined'.

Or:

(1) and (3) compile.
(2):
> error TS7027: Unreachable code detected.

**Actual behavior:**

(1) compiles.
(2) and (3):
> error TS2366: Function lacks ending return statement and return type does not include 'undefined'.

**Additional notes:**

I'm not sure which is the correct behaviour, but right now it's inconsistent.

Originally posted as a question here: https://stackoverflow.com/q/46518643/785745

**Comment by ahejlsberg** [comment]
Currently, when an exhaustive `switch` statement is the *last* statement of a function body, we consider the end point unreachable. We could potentially ignore trailing declarations that contain no executable code in this analysis.

**Comment by RyanCavanaugh** [comment]
Accepting PRs - when detecting whether the switch is "final", skip over any declarations that are hoisted (functions but not classes), declarations that are type-only (interface, type, const enum), or declarations that have no side effects (var)

**Comment by charlespierce** [comment]
@RyanCavanaugh To make sure I understand correctly: Should a `var` declaration only be considered side-effect free if it has no initializer? I.e. `var a;` should be skipped but `var a = 1;` should not be?

Also, is there any reason why we can't consider any top-level exhaustive switch to be "final"? Since an exhaustive switch will necessarily return along all code paths, any code after it should be unreachable and thus a function with a top-level exhaustive switch won't ever have an implicit return.

**Comment by DanielRosenwasser** [comment]
If it's truly exhaustive (i.e. it has a `default` and all branches throw or return) then that does seem reasonable.

**Comment by charlespierce** [comment]
@DanielRosenwasser The current logic that determines a Switch is exhaustive requires that the switch:

1. Has *no* `default` branch

2. Expression is a literal type, enum, or union of literal types.

3. All sub-types of the expression are covered by the `case` statements within.

4. All branches throw or return.

That seems at first glance to be more restrictive than your conditions. I'll take a look at implementing it so that functions with exhaustive switches never have implicit returns.

**Comment by charlespierce** [comment]
PR Opened with the above logic #20063

**Comment by mhegazy** [comment]
thanks @charlespierce !
