### ISSUE TITLE
TypeScript breakpoints don't work

### ISSUE THREAD

**Issue by Petermarcu** [Microsoft/TypeScript#19124]
@hypercodeplace reported this originally here: https://github.com/dotnet/core/issues/942

# TypeScript breakpoints don't work

I use .NET Core 2 and create new project by knockout template.

    dotnet new knockout
    npm install

The project is created correctly and works perfect.
But when I try to set breakpoints, only part of them work properly (launch by VS 2017 15.3.3 and IIS Express). Tried to launch by Chrome Version 60.0.3112.113 (Official Build) (64-bit) and IE 11.540 as well.

For example, when I set a breakpoint at [router.ts](https://github.com/aspnet/JavaScriptServices/blob/rel/2.0.0/templates/KnockoutSpa/ClientApp/router.ts) it works fine.
![1](https://user-images.githubusercontent.com/10463889/30057124-6e376c9c-91ea-11e7-8736-eddc649507ce.jpg)

But when I set a breakpont at [counter-example.ts](https://github.com/aspnet/JavaScriptServices/blob/rel/2.0.0/templates/KnockoutSpa/ClientApp/components/counter-example/counter-example.ts) it doesn't work.

![2](https://user-images.githubusercontent.com/10463889/30057126-6e3dba52-91ea-11e7-9741-e50c78fa6d17.jpg)

I use standard [tsconfig.json](https://github.com/aspnet/JavaScriptServices/blob/rel/2.0.0/templates/KnockoutSpa/tsconfig.json)
I also tried to add `"compileOnSave": true` as mentioned at [client-side debugging manual](https://blogs.msdn.microsoft.com/webdev/2016/11/21/client-side-debugging-of-asp-net-projects-in-google-chrome/) but no success. All .map files generated and located at wwwroot/dist directory.

![3](https://user-images.githubusercontent.com/10463889/30057125-6e3d6e8a-91ea-11e7-8286-b3e940d3cbf9.jpg)

Please, let me know what I do wrong.

Thanks.

**Comment by armanio123** [comment]
It's likely a Visual Studio issue. Seem like VS cannot setup the breakpoint because of the filename generated for .js and .map files are different than that of the .ts file. I'll take a deeper look to understand what's happening but in the meanwhile you can make it work by applying the following changes.

Add name to bundle-loader on file [app-root.ts](https://github.com/aspnet/JavaScriptServices/blob/rel/2.0.0/templates/KnockoutSpa/ClientApp/components/app-root/app-root.ts):
```JavaScript
27: - ko.components.register('home-page', require('bundle-loader?lazy!../home-page/home-page'));
28: - ko.components.register('counter-example', require('bundle-loader?lazy!../counter-example/counter-example'));
29: - ko.components.register('fetch-data', require('bundle-loader?lazy!../fetch-data/fetch-data'));
27: + ko.components.register('home-page', require('bundle-loader?name=home-page&lazy!../home-page/home-page'));
28: + ko.components.register('counter-example', require('bundle-loader?name=counter-example&lazy!../counter-example/counter-example'));
29: + ko.components.register('fetch-data', require('bundle-loader?name=fetch-data&lazy!../fetch-data/fetch-data'));
```
On [webpack.config.js](https://github.com/aspnet/JavaScriptServices/blob/rel/2.0.0/templates/KnockoutSpa/webpack.config.js) add the new chunk filename to the output:
```JavaScript
17: + chunkFilename: '[name].js'
```

I have created the [issue](https://developercommunity.visualstudio.com/content/problem/131430/typescript-breakpoints-dont-work.html) on the visual Studio community as well.
