### ISSUE TITLE
Speed up tsc with larger dependencies

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/TypeScript#19166]
In the project that I am working with I have two fairly large dependencies (`matter.js` and `pixi.js`) that get added to the output file. When I run `tsc -w -p src` it takes about 5-10 seconds to build. When I remove them it takes about 1 second or less to build.

Is there anyway that this build time could be sped up with caching or something else?

```json
{
  "compilerOptions": {
    "target": "es6",
    "module": "system",
    "strict": true,
    "sourceMap": true,
    "outFile": "../dist/phoenix.js",
    "removeComments": true,
    "allowJs": true,
    "newLine": "LF",
    "baseUrl": "."
  },
  "include": [
    "../node_modules/pixi.js/dist/pixi.min.js",
    "../node_modules/poly-decomp/build/decomp.js",
    "../node_modules/matter-js/build/matter.min.js",
    "../node_modules/deepmerge/dist/umd.js"
  ],
  "files": [
    // List of files ts files
  ]
}
```

**Comment by gwicksted** [comment]
Check out issue #13538 and run the `diagnostics` -- this will help the team address your particular issue.  I assume having a copy of your repo will help them too: `https://github.com/TheColorRed/phoenix`

You could try `ts-loader` with `webpack` or `tsify` with `browserify` and multiple files instead of a single `outFile`.  Alternatively try `rollup`.

During dev, you could run multi-file (and multiple-source maps) then have an alternate config that generates a single minified file and source map for production.

But the best solution is keeping external dependencies as their own files (pixi / matter) and loading them separately rather than bundling them with your sources.  At the very least I would do this for development and even run the non-minified versions.

**Comment by DanielRosenwasser** [comment]
I'm not entirely sure that TypeScript should be responsible for a concatenation step for an already-processed source-file. The problem is that TypeScript is trying to parse, bind, check & control-flow-analyze, and re-emit each of those files unnecessarily, which is pretty intensive for a library like pixi which gets bundled into about a half-megabyte file.

**Comment by mhegazy** [comment]
As noted by @DanielRosenwasser you are asking the compiler to consider pixi.min.js as an input, parse it, check it for errors, and then emit it again. First this is not what you want, pixi.min.js should not be transformed, it should be used exactelly the way it was built; second, you are wasting cycles and power on your machine building it over and over, and nothing is going to change, and third, do not use tsc as a concatenator for things it did not build, just add a concatenation step at the end that packages all your files..

**Comment by TheColorRed** [comment]
Okay, that makes sense the more I think about it. I will do the concatenation at the end.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
