### ISSUE TITLE
'declare method' code action creating invalid code

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#19165]
**TypeScript Version:**  2.6.0-dev.20171013

**Code**

`main.ts`

```ts
import Foo from "./foo";

const x = new Foo();
x.bar()
```

`foo.ts`

```ts
import {} from 'path'

export default class Foo {
}
```

Trigger the `declare method 'bar'` code action on `f.bar`

**Expected behavior:**
`foo.ts` becomes:

```ts
import {} from 'path'

export default class Foo {
    bar() {
        throw new Error("Method not implemented.");
    }
}
```

**Actual behavior:**
`foo.ts` becomes:

```ts
import {} from 'path'

export default class Foo {
}    bar() {
        throw new Error("Method not implemented.");
    }
```

**Comment by mjbvz** [comment]
Here is the returned action:

```
[Trace  - 11:52:35] Response received: getCodeFixes (645). Request took 3 ms. Success: true 
Result: [
    {
        "description": "Declare method 'bar'.",
        "changes": [
            {
                "fileName": "/Users/matb/projects/san/foo.js",
                "textChanges": [
                    {
                        "start": {
                            "line": 4,
                            "offset": 4
                        },
                        "end": {
                            "line": 4,
                            "offset": 4
                        },
                        "newText": "    bar() {\n        throw new Error(\"Method not implemented.\");\n    }\n"
                    }
                ]
            }
        ]
    }
]
```

You can see that offsets in this case are incorrect

**Comment by amcasey** [comment]
The repro steps produce the expected output in VS.  In VS Code, the behavior seems to depend on the presence of a semicolon after the import in foo.ts.

With (blank line eliminated):
```ts
import {} from 'path';
export default class Foo {
    bar(): any {
        throw new Error("Method not implemented.");
    }
}
```

Without (all whitespace discarded - result doesn't compile):
```ts
import {} from 'path'export default class Foo {
    bar(): any {
        throw new Error("Method not implemented.");
    }
}
```

**Comment by amcasey** [comment]
What is the expected command sequence when VS Code applies a code fix?  Empirically, it appears to be `getCodeFixes`, `change` (which must be specific to VS Code?), `getCodeFixes`.  The first `getCodeFixes` response is indicates a different line number depending on the presence of the semicolon, which is probably a server bug.  The `change` request surprises me a bit since the start offset always appears to be 4 less than the start offset in the `getCodeFixes` response.  That may or may not be causing problems.  The second `getCodeFixes` call seems like it might be the product of a race - after the fix has been applied, it should not be offered again.  However, it is and the response contains a different line number and different insertion text (it appears to be trying to synthesize a new member, rather than replacing the entire type declaration the way it did the first time around).

**Comment by amcasey** [comment]
I think the map from offset to line-column might be returning bad values.  I've seen at least one case where it's beyond the end of a line.  It's possible the `change` message includes a different position because an attempt has been made to correct the position.

**Comment by amcasey** [comment]
The insertion text differs when `getCodeFixes` is called again after the fix is applied because `insertNodeAtClassStart` handles classes with no members specially.

**Comment by amcasey** [comment]
Oh, the conversion is using the `ScriptInfo` for main.ts, rather than the one for foo.ts.  That would explain why the result is incorrect.
