### ISSUE TITLE
removeEventListener does not allow reusing addEventListenerOptions

### ISSUE THREAD

**Issue by HolgerJeromin** [Microsoft/TypeScript#19368]
**TypeScript Version:**  2.5

Right now [`EventTarget.removeEventListener`](https://github.com/Microsoft/TypeScript/blob/faa04a2402288654fddf36f08e969492bea9ef7c/src/lib/webworker.generated.d.ts#L408) is defined with the precise definition from the [Spec](https://dom.spec.whatwg.org/#eventtarget) (without `passive`). But I and [MDN](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener#Matching_event_listeners_for_removal) would suggest to use the exact parameter you used at `addEventListener`.

> unless you have specific reasons otherwise, it's probably wise to use the same values used for the call to addEventListener() when calling removeEventListener().

ref #14196 #18136

**Comment by mhegazy** [comment]
The spec seems to be clear that remove does not accept passive: https://dom.spec.whatwg.org/#ref-for-dom-eventtarget-removeeventlistener%E2%91%A0

I would say we should follow the spec, unless there is a strong reason why not to.

**Comment by HolgerJeromin** [comment]
The Browser does/must [not](https://dom.spec.whatwg.org/#dom-eventtarget-removeeventlistener) [use](https://dom.spec.whatwg.org/#concept-flatten-options) passive. Yes.
But are more rich dictionaries are/should be disallowed?

**Comment by kitsonk** [comment]
Excess properties are allowed when the object is not fresh.  When it is fresh, objects are restricted.  It is intentional to help identify errors.  So yes, [in certain situations](https://www.typescriptlang.org/play/#src=const%20options%3A%20AddEventListenerOptions%20%3D%20%7B%0D%0A%20%20%20%20passive%3A%20true%0D%0A%7D%0D%0A%0D%0Adeclare%20const%20target%3A%20EventTarget%3B%0D%0A%0D%0Aconst%20listener%20%3D%20()%20%3D%3E%20%7B%20%7D%3B%0D%0A%0D%0Atarget.addEventListener('click'%2C%20listener%2C%20options)%3B%0D%0Atarget.removeEventListener('click'%2C%20listener%2C%20options)%3B%0D%0Atarget.removeEventListener('click'%2C%20listener%2C%20%7B%0D%0A%20%20%20%20passive%3A%20true%20%2F%2F%20object%20is%20fresh%2C%20therefore%20checked%20for%20excess%20properties%0D%0A%7D)%3B%0D%0A), subtype dictionaries can be assigned to supertypes.

```ts
const options: AddEventListenerOptions = {
    passive: true
}

declare const target: EventTarget;

const listener = () => { };

target.addEventListener('click', listener, options);
target.removeEventListener('click', listener, options); // Works fine
target.removeEventListener('click', listener, {
    passive: true // object is fresh, therefore checked for excess properties
                  // Object literal may only specify known properties, and 'passive' 
                  // does not exist in type 'boolean | EventListenerOptions'.
});
```

**Comment by HolgerJeromin** [comment]
@kitsonk  
Wow. I never recognized this difference! 
This is exactly what i want! Thanks a lot.
