### ISSUE TITLE
Extended generic type doesn't accept itself

### ISSUE THREAD

**Issue by aminpaks** [Microsoft/TypeScript#19380]
**TypeScript Version:**  2.5.3

**Code**
```ts
export interface Test {
  name: string;
  children?: Test[];
}

function reducer<T extends Test>(items: T[]): T[] {
    return items.reduce((result, current) => {
      return result.concat(current, ...reducer(current.children || []));
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ // <- Argument of type 'Test' is not assignable to parameter of type 'T | T[]'.
    }, [] as T[]);
}
```
Take a look at [this example](https://stackblitz.com/edit/extended-generic-type?file=index.ts)

Note this will fix it:
```ts
export interface Test {
  name: string;
  children?: this[]; // <- `this` here
}
```

**Expected behavior:**
Should all generic types accept extended version of themselves?

**Actual behavior:**
An extended generic type won't accept the extended version of itself.

**Comment by jcalz** [comment]
`T` extends `Test`.  You can pass in a `T` when something expects a `Test`, but you cannot necessarily pass in a `Test` when something expects a `T`.  Your recursive call to `reducer` is giving a parameter of type `T['children']`, which is only known to be `Test[]`, not `T[]`.  So its return a value is also a `Test[]`, which cannot necessarily be concatenated onto an array of `T[]`.  Hence the error.  This seems like intended behavior to me.

By changing the `children` property to be of type `this[]` instead of `Test[]`, then you know that `T['children']` will be an array of `T`, and it works.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
