### ISSUE TITLE
Do we need to use "declare" for type aliased in d.ts files?

### ISSUE THREAD

**Issue by mpawelski** [Microsoft/TypeScript#1940]
I read that `declare` is required for all top level non-interface elements (i.e. `module`, `class`, `var`) in a declaration .d.ts file.

But do we need it for type aliases too?

Right now this code in `tests.d.ts` file gives error:
```
interface ITest {
    foo: string;
    bar: string;
}


type IMyAlias = ITest;
```
`A 'declare' modifier is required for a top level declaration in a .d.ts file.`

For me type aliases are similar to interfaces in this case and should not require `declare` keyword.

**Comment by RyanCavanaugh** [comment]
`declare` should be optional on type aliases and interfaces.

`declare type` and `declare interface` are identical to `type` and `interface`

**Comment by DanielRosenwasser** [comment]
How does this affect #2994?

**Comment by yuit** [comment]
@RyanCavanaugh what you mean by option on interface and type aliases ? Currently we give an error on ```declare interface```.

**Comment by yuit** [comment]
My understanding is that ```declare type``` is allowed as well as ```declare interface```. So we need to stop giving an error for this case ```declare interface```

**Comment by RyanCavanaugh** [comment]
Yui's interpretation is correct.

Since we already shipped type aliases this way, people have had to write `declare type` a bunch of times. We could break them and say "Write `type`, not `declare type`", but that would be a massive break for no real reason.

Having made that decision, it's only logical to allow `declare interface` as a synonym for `interface` for consistency's sake. There are still some places where we're slightly inconsistent, but `type` and `interface` at least should be fully aligned.
