### ISSUE TITLE
Index access type not checked correctly

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#19412]
```ts
interface Container {
    foo: Foo;
}
interface Foo {
    a: string;
}

function example1<T extends Foo>(): T {
    return { a: "foo" }; // Error {a:string} is not T
}

function example2<T extends Container>(): T["foo"] {
    return { a: "foo" }; // No error
}
```
These two functions should behave the same way, since `T` and `T["foo"]` are both type variables.

**Comment by mhegazy** [comment]
@ahejlsberg thoughts?

**Comment by ahejlsberg** [comment]
The distinction here is that with a simple type parameter we know for certain that the type argument will be a subtype of the constraint (otherwise what's the point), but with a generic indexed access like `T["foo"]` it is entirely possible, and in fact common, that the `foo` property is unchanged in each instantiation because type arguments just add more properties. In other words, with `T["foo"]` it is really hard to know if the intent is to vary the `foo` property or to simply add properties to `T`. We assume that the latter might be the case and therefore we are more permissive.
