### ISSUE TITLE
Inconsistency when matching against Partial<Record<keyof X,...>>

### ISSUE THREAD

**Issue by billccn** [Microsoft/TypeScript#19446]
```ts
class X {
    a: any;
    b: any;
    toString(): string {
        return '';
    }
}

let x: Partial<Record<keyof X, number>> = {a: 3};
```

This produces an error:

```
Type '{ a: number; }' is not assignable to type 'Partial<Record<"a" | "b" | "toString", number>>'.
  Types of property 'toString' are incompatible.
    Type '() => string' is not assignable to type 'number | undefined'.
      Type '() => string' is not assignable to type 'number'.
```

because the object literal's `toString()` is picked out as incompatible. However, if you remove the `toString` from class X, it compiles just file even though a `toString()` with the exact same type signature is still inherited from `Object`.

Ideally, for types like `Record<keyof X`, the properties from `Object` should be ignored or matched against their original type instead of the type in the type signature.

**Comment by mhegazy** [comment]
`Record<keyof X, number>`  is a map over all properties of `X` and making them numbers, i.e. `{ a: number, b: number, toString: number }`, you are assigning a regular object to that, and an object has `toString: ()=> string` inherited from `Object`, so that is an invalid assignment. 

I think the source of the confusion here is you expect `toString` not to be in the resulting mapping on `X`. Mapped types operate on index types (i.e. `keyof T`) and that will return you all known, own properties, and since you re-declared `toString` you got that.

A few options here, you ca subtract `toString` from the list of known keys using `Omit` (reference [here](https://github.com/Microsoft/TypeScript/issues/12215#issuecomment-307871458)) or when https://github.com/Microsoft/TypeScript/issues/12215 is implemented using a subtraction operator `-` for instance. The other option is spread operator (https://github.com/Microsoft/TypeScript/issues/10727) that would remove methods, so `...X` is `{a: any, b:any }`, but that also is not implemented yet.
