### ISSUE TITLE
Control flow doesn't work as expected when using T|any

### ISSUE THREAD

**Issue by Alphapage** [Microsoft/TypeScript#19466]
**TypeScript Version:**  2.5.3

**Code**

```ts
let s: string | any; s = ''; s. // s should be of type string
```

**Expected behavior:**
`s` should be of type `string` (same behaviour applied to `{}` or `Object`
**Actual behavior:**
`s` is of type `any`

**Comment by kitsonk** [comment]
That is by design... `any` is a [top type](https://en.wikipedia.org/wiki/Top_type), it cannot be narrowed.  A union type of `string | any` immediately becomes just `any`.

Is there a reason why you would use `any` that way?

**Comment by Alphapage** [comment]
This is just to tell that `s` could become `any` too. So, I was expecting intellisense to cast `s` to string first.

**Comment by kitsonk** [comment]
As stated `any` is a top type.  Once something is `any` that is it, it cannot be narrowed.  Use something other than the top type in a union if you want narrowing via CFA.

**Comment by DanielRosenwasser** [comment]
It's both the top and bottom in a sense which is problematic. Narrowing from `any` would make sense as the top, but makes less sense since it's the bottom - you'd get more known information, but you'd lose its capabilities.

If you use TypeScript with `noImplicitAny` and an uninitialized variable, you'll get the sort of lenient-but-aware narrowing-aware behavior though.
