### ISSUE TITLE
Tuple types accepting incorrect data

### ISSUE THREAD

**Issue by deregtd** [Microsoft/TypeScript#19463]
**TypeScript Version:**  2.6.0-rc

**Code**

```ts
let a: [string] = ['a', 'b'];
```

**Expected behavior:**
Error: [string, string] is not compatible with [string].

**Actual behavior:**
Compiles A-ok

**Comment by kitsonk** [comment]
The type of `string[]` and `[string, string]` is assignable to `[string]`.  Tuple types are not checked for excess elements when _fresh_, unlike objects, so the right hand side is assignable to left hand side.

It is arguable though when the array is fresh, it should follow the same rules as #3823 for objects.

**Comment by DanielRosenwasser** [comment]
Think of it like this

```ts
interface Tuple1<T> extends Array<T> {
    0: T;
}

interface Tuple2<T, U> extends Array<T | U> {
    0: T;
    1: U;
}

declare let a: Tuple1<string>;
declare let b: Tuple2<string, string>;

a = b; // works, 'b' is also viewed as a `string[]` with a `0: string`
```

**Comment by DanielRosenwasser** [comment]
See also: #6229

**Comment by DanielRosenwasser** [comment]
> let a: { x: number } = { x: 4, y: 5 };

TypeScript's original behavior allowed this. The motivating example for disallowing it was options-bag-style APIs. Are you frequently running into excess tuple errors?

**Comment by deregtd** [comment]
Yes, we just made a correction to our codebase to change over a hundred usages of tuples that were being used incorrectly.

**Comment by deregtd** [comment]
The question in my book is what the pros and cons of each way are.  What are the pros of allowing you to do what feels like, to me, "invalid" assignments to tuples?  I.e. why SHOULD it be allowed to do:

```
let a: [string] = [ 'hi', 12345 ];
```

That feels like it's an engineer bug in 100% of circumstances, and if we have the ability to fix it with TSC, then we should.

**Comment by kitsonk** [comment]
Actually that example is [disallowed](https://www.typescriptlang.org/play/#src=let%20a%3A%20%5Bstring%5D%20%3D%20%5B%20'hi'%2C%2012345%20%5D%3B%0A#src=let%20a%3A%20%5B%20string%2C%20number%20%5D%20%3D%20%5B%20'hi'%2C%2012345%2C%20'foo'%20%5D%3B%20%2F%2F%20ok%0Alet%20b%3A%20%5Bstring%5D%20%3D%20%5B'hi'%2C%2012345%5D%3B%20%2F%2F%20bad%0Alet%20c%3A%20%5Bstring%20%7C%20number%5D%20%3D%20%5B'hi'%2C%2012345%5D%3B%20%2F%2F%20ok%0A).  Excess assignment slots only work when the excess values are assignable to one of the member of the tuple. 🤷‍♂️ 

```ts
let a: [ string, number ] = [ 'hi', 12345, 'foo' ]; // ok
let b: [string] = ['hi', 12345]; // bad
let c: [string | number] = ['hi', 12345]; // ok
```

Personal opinion too, when the array is fresh, it should be strictly checked against the left hand, because as @deregtd indicates, how is that ever a desired situation?  Especially considering how [the following works](https://www.typescriptlang.org/play/#src=let%20a%3A%20%5Bstring%2C%20number%5D%20%3D%20%5B'hi'%2C%2012345%5D%3B%0Alet%20b%3A%20%5Bstring%5D%20%3D%20a%3B%20%2F%2F%20not%20assignable%0Alet%20c%3A%20%5Bstring%20%7C%20number%5D%20%3D%20a%3B):

```ts
let a: [string, number] = ['hi', 12345];
let b: [string] = a; // not assignable
let c: [string|number] = a; // ok
```

That, again, while maybe _sound_ from a type system perspective, I can't see why the assignment to `b` is bad while `c` is good from an identifying constructs that are likely to be errors.  Either both are desirable, or neither.

**Comment by mhegazy** [comment]
From #19536, we would like to consider one of two alternatives here:
1. Treat all tuples as exact types, where the `length` property is manifest in the type, and two tuples are only assignable if they have the exact same length. Tuples will need to be `ReadonlyArray` for this to work. We will have to include this under a strict flag.
2. Apply freshness rules on tuple literals, and flag excess members just like we do with objects.

**Comment by deregtd** [comment]
#1 sounds perfect to me.  The way we often use tuples, it's basically just a quick and strong dynamic type that doesn't require wrapping in an interface.

**Comment by RyanCavanaugh** [comment]
See notes in #19585

**Comment by Igorbek** [comment]
@mhegazy (1) seems more preferable and is what #6229 and #17765 propose.

**Comment by sandersn** [comment]
I'll implement (2) just to see how well it works, but I played with (1) and it works great. Note that #17765 implements (1) but that doesn't include the open-length tuples from #6629 (or their improved spread checking).

**Comment by Igorbek** [comment]
@sandersn I guess you meant ~~6629~~ #6229.

**Comment by gcnew** [comment]
My vote goes for freshness, unless the full Strict/Open length tuples proposal gets implemented. Working with non-aliasable tuples is just painful. It will lead to many overloads, which is hardly ideal.

E.g. this is a Haskell library trying to provide uniform usage patterns for tuples of disparate arities: https://github.com/augustss/tuple. The implementation code consists of ugly, automatically generated type class instances (e.g. [Select](https://github.com/augustss/tuple/blob/3da4066568986a6051804f3cb865efb549f11eb3/src/Data/Tuple/Select.hs)). I don't think we'd like to go in that direction.

**Comment by mhegazy** [comment]
Should be fixed by https://github.com/Microsoft/TypeScript/pull/17765
