### ISSUE TITLE
Compiler OOM on strict generic checks 

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#19662]
Reported in https://github.com/Microsoft/TypeScript/issues/18411#issuecomment-341170198

Project: https://github.com/electricessence/TypeScript.NET

The project compiles in Webstorm for the existing tsconfigs with 2.7.  But I'm dependent on gulp to render my distributions and run tests.  The area where it gets problematic is in /source/System.Linq where the Linq.ts lib tries to reconcile the extensive interface signature.  If I rip out the guts of the interface, it will compile (although still quite slowly relative to 2.3.2)

Note: `--noStrictGenericChecks` seems to avoid the crash.

**Comment by electricessence** [comment]
Unless gulp-typescript changed something where passing ```noStrictGenericChecks: true``` to the options doesn't work, then I'm still getting the error.

typescript@2.7.0-dev.20171104
Compilation is taking quite a long time before failing.

Just for reference, here is where the options block is passed through my build process:
https://github.com/electricessence/gulp-typescript-helper/blob/master/source/BuildHelper.ts#L59
I see no reason why it wouldn't be working though since it's been reliable through 2.3.2.

I may have to just wait for a fix.

**Comment by electricessence** [comment]
Ok so this officially has be come a serious issue. (related https://github.com/Microsoft/TypeScript/issues/20251)

TS 2.6.0 will allow me to add:
```ts
readonly [Symbol.toStringTag]: "Promise";
```

But TS 2.3.2 will not.  And 2.3.2 is the latest version that will compile my code successfully.
If I try to hack either version make both happy, they disagree.

**Comment by aldendaniels** [comment]
Process is running out out of memory on TS 2.6.2 when running 
```
tsc --noemit --watch --project .
```

I also tried
```
tsc --noemit --watch --noStrictGenerics --project .
```
As recommended in #18411, but no dice.

Non-watch mode and the IDE interface are OK.

**Comment by mhegazy** [comment]
@aldendaniels can you share your project

**Comment by mhegazy** [comment]
Closing for now. please reopen if a sample exists.

**Comment by electricessence** [comment]
This is how I ended up fixing my problems:
https://github.com/Microsoft/TypeScript/issues/21048

@sandersn helped me through and also had me mark a checkin where it's repoable.
