### ISSUE TITLE
Narrow union type by checking property existence

### ISSUE THREAD

**Issue by aaronbeall** [Microsoft/TypeScript#19691]
**TypeScript Version:**  2.7.0-dev.201xxxxx

I'm sure my line of reasoning is missing something when you take this further, but....

**Code**

```ts
declare const obj: { color: string } | { shape: string };

if (obj.color != null) {
  console.log(obj.color)
} else {
  console.log(obj.shape)
}
```

**Expected behavior:**
No error, type narrows to ` { color: string }` inside `if` block, narrows to `{ shape: string }` in `else` block.

**Actual behavior:**
Error on `obj.color` access: 

```
Property 'color' does not exist on type '{ color: string; } | { shape: string; }'.
  Property 'color' does not exist on type '{ shape: string; }'.
```
Now I can see how trying to access `obj.color` could be considered dangerous, but with `strictNullChecks` the type could be `string | undefined` which would make you check it before doing something dangerous. I guess the hard part is using the existence of the property to narrow down the type, but it *seems* very similar to a tagged union.

**Comment by mhegazy** [comment]
This is a duplicate of https://github.com/Microsoft/TypeScript/issues/1260

Types in TS are open. so if `obj` does have a `color` you can not assume that it is `shape`. you will need https://github.com/Microsoft/TypeScript/issues/12936 for that.

The other part is allowing property access on a union property that is not present in all constituents, by making it `T | undefined`. This would only work in `--strictNullChecks` since no guarantees can be made otherwise that the property will be read without a check.

**Comment by aaronbeall** [comment]
Yeesh, sorry for another dupe, that's ancient id as well... believe it or not I do search first. :) 

Thanks for explanation. Closing...
