### ISSUE TITLE
Allow comma as a separator in object literal types

### ISSUE THREAD

**Issue by jonathandturner** [Microsoft/TypeScript#1969]
To help people who are used to TypeScript not trip over the object literal type syntax, we should allow the comma as a separator.  This allows more parallel syntax when working with object literals.  In effect, with this change, both of these will be valid:

```TypeScript
var x: {y: number; z: string} = {y: 3, z: “bob”};
```
and

```TypeScript
var x: {y: number, z: string} = {y: 3, z: “bob”};
```

This change is also part of the requested changes as part of the Typed JS efforts.

**Comment by CyrusNajmabadi** [comment]
@jonathandturner There are a few interesting issues i'd like to get some resolution on before continuing with this.

First off, the typescript language defines an interface like so:
```
InterfaceDeclaration:
    interface   Identifier   TypeParametersopt   InterfaceExtendsClauseopt   ObjectType
````

As such, if we augment ObjectType such that commas are allowed as well as semicolons, then we will also be changing things so that when we parse an InterfaceDeclaration that commas would not be allowed.

Personally, i think this is fine.  It also has the added benefit that if you take an object type and want to elevate it to an interface, all you have to do is copy it somewhere and add ```interface Whatever``` before it.  

If we want to preserve things such that interfaces only allow semicolons, then we'd need to have to make the grammar such that InterfaceDeclaration is not composed out of ObjectType.  We'd also have a slightly poorer experience (IMO) because it would be more difficult to elevate an object type to an interface type.



Second, if we allow commas and semicolons for object-types (and possibly interface types), are we then being inconsistent by not allowing it elsewhere?  For example, classes would still only allow semicolons, and object literals would only allow commas.  Would we want to go examine all these other delimited grammar elements to see if we should relax things there as well?   Or is that taking things too far.

We should discuss this and see where we want to land, and if we want to just do the specific request exactly, or if we should expand this a bit more.
