### ISSUE TITLE
noUnusedParameters incorrect detection of unused parameter if second parameter is used

### ISSUE THREAD

**Issue by kukjevov** [Microsoft/TypeScript#19711]
**Code**
```ts
//jquery selector
this._selector
    .on("typeahead:select", (event, suggestion) =>
    {
        this.value = this._toValue(suggestion);
        this._externalValueChangeSubject.next(this.value);
     })
```
**Expected behavior:**
Parameter `event` should not be marked as unused, because suggestion is second parameter and it is used. If i remove event, suggestion becomes first parameter which will have value of `event` which i actually do not need.

**Actual behavior:**
Code above should be valid event with `noUnusedParameters` option set to `true`.

*Typescript* 2.6.1

**Comment by andy-ms** [comment]
Add an underscore to unused parameters, e.g. `_event`.

**Comment by kukjevov** [comment]
Well, i think it should check usage of arguments from last, but this explaination is also usable :).

Thank you

**Comment by narkowicz** [comment]
We hit this recently doing a tidy up - very common in map / reduce / etc. where an index value is used... thanks for the tip prepending an _underscore.

This happens to conflict with our TSLint rules- which we will look ad modifying (for now ignoring the line below), but as @kukjevov suggests would prefer if usage was checked from last rather than imposing a style / naming convention to enable use of the `noUnusedParameters` rule.
