### ISSUE TITLE
generated d.ts loses type info (and thus produces errors)

### ISSUE THREAD

**Issue by devdoomari** [Microsoft/TypeScript#19748]
TS version: 2.6.1

I'm trying to create a react rxjs high-order-component typescript library, and the following code does compile but its generated d.ts file contains some errors:
[rx-react-ts.ts](https://gist.github.com/devdoomari/779b80d84821fc42a2076e23e9dc582b)

generated d.ts:
[rx-react-ts.d.ts](https://gist.github.com/devdoomari/f39b0a29dbcb25bf5cc0bde99719f13a)

note that I can fix those errors by manually changing:
```
{}[P]
```
to
```
InjectedStreamProps[P]
```

**Comment by andy-ms** [comment]
Reproduced this with just:
```ts
declare function map<T extends object, U extends {[P in keyof T]: U[P]}>(fn: (x: T[keyof T]) => U[keyof T], obj: T): U;
export function withRxJSStream<T extends object>(streams: T) {
  return map(s => s, streams);
}
```

Output `a.d.ts`:
```ts
export declare function withRxJSStream<T extends object>(streams: T): {
    [P in keyof T]: {}[P];
};
```

**Comment by weswigham** [comment]
@andy-ms That is an issue with inference itself, not just declaration emit. Look at the `quickinfo` for `map` within `f` - we infer `{}`. Also I'm not even sure these types make sense.

**Comment by weswigham** [comment]
Same with the original case - if you mouseover `withRxJSstream`, you see the `{}[P]` we infer as the member type of the type passed in to partial.

**Comment by weswigham** [comment]
Specifically, `__valueForTypeReference` is inferred as 
```ts
{
    [P in keyof InjectedStreamProps]: {}[P];
}
```
which then flows through the rest of the type. It looks like this happens because `InjectedStreamProps[keyof InjectedStreamProps]` is an `Observable<any>` (just look at its constraint), which then causes inference to map backwards when looking at `U[keyof T]` - `keyof T` becomes `P` through inference/instantiation, and `U` has no inference sites, so becomes `{}` - hence `{}[P]`.


```ts
        map<T extends object, TElement>(fn: (x: T[keyof T]) => TElement, obj: T): {[P in keyof T]: TElement};
```
Is a more sensible way to write the ramda `map` overload used here, which actually yields a pile of `any`'s instead of `{}[P]`'s, since it avoids doing a reverse lookup for an index type which has no inference sites.

**Comment by weswigham** [comment]
@ahejlsberg Do you have anything you'd like to add here? While the `ramda` definitions seem (to me) a bit off, I'm also unsure why we keep `{}[P]` around to begin with (or allow the inference in the first place), considering we _do_ issue an error on `{}[P]` when written by a user, as `{}` as no keys and `P` isn't related to the `keyof {}` in any way.

**Comment by devdoomari** [comment]
@weswigham 
so... how is TS going to solve this issue? would the solution enable what I'm trying to do?
I'm willing to change some code for this

**Comment by weswigham** [comment]
@devdoomari As I said, the issue is likely really with `ramda`'s type definitions; they're little too clever and end up not creating an actual usable inference position for `U` in the case of code structured like yours, so we make a substandard inference based on what we know about the structure of the types provided. In the meantime, if you can, I'd ask some people involved with [the ramda types](https://github.com/types/npm-ramda/) to see if they have some way to structure your code/their types that achieves your goals; they're normally pretty involved around here and may be able to help/identify if they expected this to work and why.
