### ISSUE TITLE
Get name of function does not seem to work

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#19757]
**Code**

```ts
export const initLogToStdout = function(marker: string){

  assert(marker && typeof marker === 'string', `first argument to ${initLogToStdout.name} must be a string`);

  return function logToStdout(obj: Object){
    obj[marker] = true;
    console.log(customStringify(obj));
  };
};

```

Here is screenshot:

![screenshot 2017-11-05 18 06 48](https://user-images.githubusercontent.com/11139560/32422258-3b063d68-c254-11e7-9cb2-c2aabf518030.png)

**Expected**
I would expect that the name property would be available on a function expression? I didn't try a function declaration, maybe that'd work.

**Comment by kitsonk** [comment]
Something else is at play in your situations, because there is no issue in the [playground](https://www.typescriptlang.org/play/#src=declare%20const%20assert%3A%20(...args%3A%20any%5B%5D)%20%3D%3E%20void%3B%0Adeclare%20const%20customStringify%3A%20(obj%3A%20any)%20%3D%3E%20string%3B%0A%0Aexport%20const%20initLogToStdout%20%3D%20function%20(marker%3A%20string)%20%7B%0A%0A%20%20assert(marker%20%26%26%20typeof%20marker%20%3D%3D%3D%20'string'%2C%20%60first%20argument%20to%20%24%7BinitLogToStdout.name%7D%20must%20be%20a%20string%60)%3B%0A%0A%20%20return%20function%20logToStdout(obj%3A%20Object)%7B%0A%20%20%20%20obj%5Bmarker%5D%20%3D%20true%3B%0A%20%20%20%20console.log(customStringify(obj))%3B%0A%20%20%7D%3B%0A%7D%3B%0A) with that code.

**Comment by ORESoftware** [comment]
yeah it worked later, no idea why it didn't work before, and then started working later, something to do with webstorm I guess, thanks though

**Comment by aluanhaddad** [comment]
JetBrains IDEs use a custom language service that often has different behavior than tsserver. This behavior is configurable.

**Comment by ORESoftware** [comment]
yeah probably just a different tsc version, dunno

**Comment by aluanhaddad** [comment]
See https://www.jetbrains.com/help/webstorm/service-options.html
