### ISSUE TITLE
Inconsistency between type and interface

### ISSUE THREAD

**Issue by inad9300** [Microsoft/TypeScript#19835]
This is probably me not understanding the subtleties of `type` vs `interface`, but they contain very weird differences indeed. I would expect the following code to work with either of them, but it does not work for `interface`:

```typescript
type JsonLeaf = number | string | boolean | null

interface JsonTree {
    [key: string]: JsonLeaf | JsonTree | JsonTree[]
}

interface InterfaceWithCustomProps {
    anotherProp: string
}

interface InterfaceWithNestedProps {
    someProp: InterfaceWithCustomProps // Does not work with interface.
    // someProp: {[key: string]: string} // Works with interface.
}

interface ChildInterface extends JsonTree, InterfaceWithNestedProps { }

type ChildType = JsonTree & InterfaceWithNestedProps // Works in every case.
```

[See in playground.](https://www.typescriptlang.org/play/#src=type%20JsonLeaf%20%3D%20number%20%7C%20string%20%7C%20boolean%20%7C%20null%0A%0Ainterface%20JsonTree%20%7B%0A%20%20%20%20%5Bkey%3A%20string%5D%3A%20JsonLeaf%20%7C%20JsonTree%20%7C%20JsonTree%5B%5D%0A%7D%0A%0A%0Ainterface%20InterfaceWithCustomProps%20%7B%0A%20%20%20%20anotherProp%3A%20string%0A%7D%0A%0Ainterface%20InterfaceWithNestedProps%20%7B%0A%20%20%20%20someProp%3A%20InterfaceWithCustomProps%20%2F%2F%20Does%20not%20work%20with%20interface.%0A%20%20%20%20%2F%2F%20someProp%3A%20%7B%5Bkey%3A%20string%5D%3A%20string%7D%20%2F%2F%20Works%20with%20interface.%0A%7D%0A%0Ainterface%20ChildInterface%20extends%20JsonTree%2C%20InterfaceWithNestedProps%20%7B%20%7D%0A%0Atype%20ChildType%20%3D%20JsonTree%20%26%20InterfaceWithNestedProps%20%2F%2F%20Works%20in%20every%20case.)

**Comment by ahejlsberg** [comment]
This is indeed one of the differences between `extends` and the `&` type operator. A class or interface declaration inherits index signatures from its base type(s) and validates that the constraints are satisfied by newly introduced members. However, the `&` type operator doesn't perform this validation because `&` is *always* permitted between any two types (even if the outcome is a type for which no values exist).

**Comment by ahejlsberg** [comment]
This is indeed one of the differences between `extends` and the `&` type operator. A class or interface declaration inherits index signatures from its base type(s) and validates that the constraints are satisfied by newly introduced members. However, the `&` type operator doesn't perform this validation because `&` is *always* permitted between any two types (even if the outcome is a type for which no values exist).

**Comment by ahejlsberg** [comment]
I should add that you get an error because you don't have `JsonTree` nodes all the way down, so to speak. When you extend `JsonTree` everywhere it works as expected:

```ts
type JsonLeaf = number | string | boolean | null;

interface JsonTree {
    [key: string]: JsonLeaf | JsonTree | JsonTree[];
}

interface InterfaceWithCustomProps extends JsonTree {
    anotherProp: string;
}

interface InterfaceWithNestedProps extends JsonTree {
    someProp: InterfaceWithCustomProps;
}

interface ChildInterface extends InterfaceWithNestedProps { }
```

**Comment by inad9300** [comment]
Thanks a ton for the clarification.
