### ISSUE TITLE
[ts] Operator '===' cannot be applied to types '"aaa"' and '"bbb"'.

### ISSUE THREAD

**Issue by mrdulin** [Microsoft/TypeScript#19831]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code**

```ts
//This one, tsc give me an error.
const lab = 'icon-yes';
if (lab === '321') {}  //<- [ts] Operator '===' cannot be applied to types '"icon-yes"' and '"321"'.

//All of below are correct.
const lb: string = 'icon-yes';
if (lb === '321') {}

let la = 'icon-yes';  //<- this one , I just replace `const` to `let`. Why it became correct?
if (la === '321') {}

const labc = 'icon-yes';
if (labc === 'icon-yes') {}  //<- compare the error case. Do not understand.

let labcd = 'icon-yes';
if (labcd === '321') {}
```

**Expected behavior:**

`const lab = 'icon-yes';` I think the variable `lab` should be `string` type by type inference.

All of these cases should be correct.

**Actual behavior:**

Can not figure out why.

**Comment by andy-ms** [comment]
In `const lab = "icon-yes"`, `lab` can never have a value other than `"icon-yes"` because it is a const. So it is safe and correct to give it a string literal type.
If you explicitly write `: string` we will use that. If the variable is mutable it might not always have that value, so it gets the `string` type.

As for this case:
```ts
const labc = 'icon-yes';
if (labc === 'icon-yes') {}  //<- compare the error case. Do not understand.
```
It probably should be an error because the `===` operation can never return false, but currently we only have the tests for `===` that can never return true.

**Comment by fenying** [comment]
@andy-ms See also this

```ts
let a: boolean = false;

try {

    a = true;
    a = false;
}
catch (e) {

    if (true === a) { // [ts] Operator '===' cannot be applied to types 'true' and 'false'.

        // ...
    }
}
```

and

```ts
let a: "a" | "b" = "a";

try {

    a = "b";
    a = "a";
}
catch (e) {

    if ("b" === a) { // [ts] Operator '===' cannot be applied to types '"b"' and '"a"'.

        // ...
    }
}
```

**Comment by andy-ms** [comment]
@fenying See #18916 and #18478.
