### ISSUE TITLE
Auto imports import error module name with cnpm.

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#19893]
_From @Lxxyx on November 9, 2017 6:13_

cnpm: npm client for China mirror of npm.

Github: https://github.com/cnpm/cnpm

- VSCode Version: 1.18

Steps to Reproduce:

1. download this repo: https://github.com/Lxxyx/auto-imports-cnpm
2. install cnpm by: `npm i cnpm -g`
3. use `cnpm i` to install dependencies.
4. in index.js
![image](https://user-images.githubusercontent.com/13161470/32590887-5f90334c-c4e2-11e7-80f3-05c767076632.png)
5. but in text.js when I type render:
![image](https://user-images.githubusercontent.com/13161470/32590929-918557ce-c4e2-11e7-8df5-38673fcbd272.png)

And I Get: `import { render } from "_rax@0.4.20@rax";`

6.  The directory structrue in cnpm installed node_modules:

![image](https://user-images.githubusercontent.com/13161470/32590969-c02931ae-c4e2-11e7-828c-bc5c0f482595.png)

Reproduces without extensions: No

_Copied from original issue: Microsoft/vscode#37882_

**Comment by andy-ms** [comment]
Looks like we could fix this by just ignoring any directory name starting with `_`.

**Comment by andy-ms** [comment]
We should only be giving you an import fix for a file that was actually included in the project though.
@sheetalkamat Are we automatically adding all `node_modules` to a project with a `jsconfig.json`? We should probably exclude those from the project entirely rather than a targeted fix to `importFixes`.

**Comment by sheetalkamat** [comment]
@andy-ms ```node_modules``` are auto excluded unless they are not included by include rule. In the view, isnt that just the folder view (which lists everything in the folder whether included or not?) 

For eg out server sources dont include watchguard and such directories in the project but it does show up in folder view.
![capture](https://user-images.githubusercontent.com/8052792/32681457-7397fe90-c624-11e7-959a-8ea9a8c488c9.JPG)

All the folders arent auto included in the project.. From TSServerLog
```
Info 94   [14:42:6.400] Project 'c:/temp/projs/auto-imports-cnpm/jsconfig.json' (Configured) 0
Info 94   [14:42:6.401] 	Files (17)
	c:/typescript/built/local/lib.d.ts
	c:/temp/projs/auto-imports-cnpm/node_modules/_rax@0.4.20@rax/lib/debug/devtools.js
	c:/temp/projs/auto-imports-cnpm/node_modules/_rax@0.4.20@rax/lib/element.js
	c:/temp/projs/auto-imports-cnpm/node_modules/_rax@0.4.20@rax/lib/component.js
	c:/temp/projs/auto-imports-cnpm/node_modules/_rax@0.4.20@rax/lib/purecomponent.js
	c:/temp/projs/auto-imports-cnpm/node_modules/_rax@0.4.20@rax/lib/proptypes.js
	c:/temp/projs/auto-imports-cnpm/node_modules/_rax@0.4.20@rax/lib/render.js
	c:/temp/projs/auto-imports-cnpm/node_modules/_rax@0.4.20@rax/lib/hydrate.js
	c:/temp/projs/auto-imports-cnpm/node_modules/_rax@0.4.20@rax/lib/findDOMNode.js
	c:/temp/projs/auto-imports-cnpm/node_modules/_rax@0.4.20@rax/lib/unmountComponentAtNode.js
	c:/temp/projs/auto-imports-cnpm/node_modules/_rax@0.4.20@rax/lib/findComponentInstance.js
	c:/temp/projs/auto-imports-cnpm/node_modules/_rax@0.4.20@rax/lib/setNativeProps.js
	c:/temp/projs/auto-imports-cnpm/node_modules/_rax@0.4.20@rax/lib/version.js
	c:/temp/projs/auto-imports-cnpm/node_modules/_rax@0.4.20@rax/lib/children.js
	c:/temp/projs/auto-imports-cnpm/node_modules/_rax@0.4.20@rax/lib/index.js
	c:/temp/projs/auto-imports-cnpm/index.js
	c:/temp/projs/auto-imports-cnpm/text.js
```

Also I think we should consider symbolLink path info to determine the auto name. (eg. in this case the import is from rax but because it has used npm link the actual path happens to be the path that starts with _)

**Comment by Lxxyx** [comment]
import for node_modules is important. In React Native, I have to import components `View`,`Text`  all the time. Auto Imports is useful for this case.

Same as lodash, mongoose and many npm lib.
