### ISSUE TITLE
Inconsistent inference in 2.6.1

### ISSUE THREAD

**Issue by ikatyang** [Microsoft/TypeScript#19913]
**TypeScript Version:**  2.6.1 / 2.7.0-dev.20171110

```
strict: true
strictFunctionType: false
```

**Code**

```ts
type List<T> = ArrayLike<T> | T[];

declare function pipe<T1, T2, R>(
  f1: (x1: T1) => T2,
  f2: (x2: T2) => R
): (x: T1) => R;

type R1<U> = U[];
type R2<U, K extends string> = U[] | Record<K, U>;

type F1<T, U> = {
  (list: List<T>): R1<U>;
  <K extends string>(target: List<T> | Record<K, T>): R2<U, K>;
};

type F1_1<T, U> = {
  (list: List<T>): R1<U>;
};

type F1_2<T, U> = {
  <K extends string>(target: List<T> | Record<K, T>): R2<U, K>;
};

declare const fn1: F1<string, number>;
declare const fn1_1: F1_1<string, number>;
declare const fn1_2: F1_2<string, number>;
declare const fn2: (x: List<any>) => any;

pipe(fn1, fn2);
//        ^^^ error in v2.6.1
// Argument of type '(x: List<any>) => any' is not assignable to parameter of type '(x2: R2<number, any>) => any'.
// Types of parameters 'x' and 'x2' are incompatible.
//   Type 'R2<number, any>' is not assignable to type 'List<any>'.
//     Type 'Record<any, number>' is not assignable to type 'List<any>'.
//       Type 'Record<any, number>' is not assignable to type 'ArrayLike<any>'.
//         Property 'length' is missing in type 'Record<any, number>'.

pipe(fn1_1, fn2); // no error
pipe(fn1_2, fn2); // no error
```

**Expected behavior:**

- All passed
- or `pipe(fn1, fn2)` and at least one of `pipe(fn1_1, fn2)` and `pipe(fn1_2, fn2)` throw error

If `pipe(fn1, fn2)` should throw error, at least one of `pipe(fn1_1, fn2)` and `pipe(fn1_2, fn2)` should also throw error since `F1` = `F1_1` + `F1_2`.

**Actual behavior:**

Only `pipe(fn1, fn2)` throw error.

**NOTE**: it was all passed before v2.6.1

---

Original post: https://github.com/types/npm-ramda/issues/311

**Comment by weswigham** [comment]
Hello! Long time no response~ So I looked at this today and the error is one I'd categorize as a "correct" one. `fn1_1`'s overloads indicate it can return either a `{}[]` or a `{}[] | Record<string, {}>`, which is, ofc, just `{}[] | Record<string, {}>`. `fn2` cannot take a `Record<string, {}>` as a parameter, hence the error. `pipe(fn1_2, fn2)` should _also_ be an error for the same reason (IMO). It's not, AFAIK, because we replace  `K` with `never` (instead of `{}`) because we find it in an argument position instead of a return position first. Because of that, `Record<never, string>` looks a lot like just `never` and it happens to typecheck. Looks like this happens because `instantiateTypeWithSingleGenericCallSignature` attempts to instantiate `ArrayLike<string> | string[] | Record<K, string>` in the context of `{}` and decides that `K` as `never` is most appropriate (which, in an isolated bit of reasoning, it is). The overloads don't work the same way because we don't use `instantiateTypeWithSingleGenericCallSignature` and go the long way around instead (and get a different, more correct, answer).

**Comment by RyanCavanaugh** [comment]
Checked at latest and there are now errors on the first and third calls; sounds like the middle one is hitting a limitation.
