### ISSUE TITLE
Overeager new method name completion in class

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#19965]
May be a vscode issue, but putting it here first.

**TypeScript Version:**  2.7.0-dev.20171112

**Code**

```ts
class C {
    theBrownFoxJumpedOverTheLazyDog() {
    }
}

class D extends C {
    public /*here*/
}
```

Type `tjl(`.

**Expected behavior:**

Get what I typed: `public tjl(`.

**Actual behavior:**

Get `public theBrownFoxJumpedOverTheLazyDog(`.
This is a new identifier location so it's likely that the user wanted to write a new method instead of overriding an existing one.
Also, this only happens if the `public` keyword is present.

**Comment by mhegazy** [comment]
We are not sharing this piece of information with VSCode, and thus, they have no way of knowing that it is an identifier definition location to change the behavior..

the issue here is adding these flags to the completion list would break the API. not sure what we can do here, other than specifying a new command.. complesions2, or something..

@mjbvz thoughts?

**Comment by mjbvz** [comment]
Yes we've had a few issues like, such as #2831

For this specific case, the bug is caused because we treat `(` as an commit character. Could we just return the context information on the completion items themselves, so that vs code could disable the commit character here? The downside would be that this context information would have to be duplicate for every completion item

**Comment by mhegazy** [comment]
> so that vs code could disable the commit character here?

yes. VS has a different behavior based on the whether we know if this location is a possible identifier definition location. in these cases what the user wrote is considered a valid completion, and can be committed as well..

![image](https://user-images.githubusercontent.com/8000722/32756094-3a8581b6-c88d-11e7-9a8d-00a0a8850284.png)


>  The downside would be that this context information would have to be duplicate for every completion item

yeah.. and that is gonna be big.. we can put it on the first entry only.. though seems arbitrary

**Comment by mhegazy** [comment]
Should be fixed by https://github.com/Microsoft/TypeScript/pull/25080
