### ISSUE TITLE
Bad decorator code generation.

### ISSUE THREAD

**Issue by thomaseding** [Microsoft/TypeScript#20038]
**TypeScript Version:**  2.5

**Code**
```
function deprecated<F>(target: Object, propertyKey: keyof Test, descriptor: TypedPropertyDescriptor<F>): TypedPropertyDescriptor<F> {
    return Test._deprecated(target, propertyKey, descriptor);
}

class Test {
    public static _deprecated(target: Object, propertyKey: keyof Test, descriptor: TypedPropertyDescriptor<any>): TypedPropertyDescriptor<any> {
        const originalMethod = descriptor.value!;

        descriptor.value = function (this: Test, ...args: any[]) {
            console.log(`Don't use Test.${propertyKey}`);
            return originalMethod.apply(this, args);
        };

        return descriptor;
    }

    @deprecated
    public badCodeGeneration(): null { 
        return null;
    }
}
```

**Expected behavior:**
No runtime crash during initialization of Test class.

**Actual behavior:**
Runtime crash during initialization of Test class.

**Comment by DanielRosenwasser** [comment]
Is this because of class initialization order? In other words, the `Test` class, as captured by `deprecated`, won't be fully initialized, but `deprecated` is used during that initialization. This may be working as intended. A solution would be to move the body of `_deprecated` to `deprecated itself.

@rbuckton @bterlson
