### ISSUE TITLE
[feature request] Interface and type names EMOJI Support!!

### ISSUE THREAD

**Issue by hsir** [Microsoft/TypeScript#20072]
Since all type declarations and infos will be omitted when compiled to JS, it would be safe and great to have interface and type names with emoji support !!!

Just like this:

![2017-11-16 9 19 41](https://user-images.githubusercontent.com/5260937/32893316-a365fad6-ca9e-11e7-8068-8d7c05a5a5b2.png)

And codes will be like:

![2017-11-17 2 57 34](https://user-images.githubusercontent.com/5260937/32910037-269f30bc-cb43-11e7-89e0-19cb3f01ac9c.png)

**Comment by RyanCavanaugh** [comment]
I'm a little 🐑 ish on this

**Comment by mhegazy** [comment]
Looking at the [unicode character data](http://www.unicode.org/Public/6.2.0/ucd/UnicodeData.txt), emoji chars seems to be marked as symbols; which makes them invalid identifier characters (neither [`ID_Start ` nor `ID_Continue`](http://unicode.org/reports/tr31/)) names as per the [ECMAScript spec](https://tc39.github.io/ecma262/#prod-UnicodeIDStart); and since these names exist at runtime, we have no way of naming them in the resulting JS code.

**Comment by hsir** [comment]
@mhegazy Type & declarations infos will be omitted and will not show up in the resulting JS code, is there any possibility or future plans on this? This is gonna be a really cool feature, just like Swift.

**Comment by Ghabriel** [comment]
This feature is a _really bad_ idea IMO. Makes it more difficult to both write and read code (use it a few times and it becomes _annoying_ to read the code). Just my two cents on this.

**Comment by mhegazy** [comment]
> This is gonna be a really cool feature, just like Swift.

I know :(. but we are committed to be a super-set of JS, and part of that is not diverging from the ES spec on issues that may cause conflicts, like identifier names. I would recommend making this an ECMAScript proposal instead. if TC39 approves it, we will do it.
