### ISSUE TITLE
`{}` should not be assignable to `object`

### ISSUE THREAD

**Issue by pelotom** [Microsoft/TypeScript#20296]
**TypeScript Version:**  2.7.0-dev.20171126

**Code**

```ts
const nonPrimitive: object = ((x: {}) => x)(3);
```

**Expected behavior:**

This should be a type error saying that `{}` is not assignable to `object`.

**Actual behavior:**

The code type checks, allowing `nonPrimitive` to be assigned a primitive value (`3`).

**Comment by HerringtonDarkholme** [comment]
Empty object type should be assignable to `object`. Fairly, it is users' choice to use empty object type, in order to annotate one variable can be anything (but checked, not like `any`). By using the empty type, users already lose type information about the variable.

Further more, stricter `object` means only subtype of `object` can be assignable in a structrual type system.

Consider this problem:

```ts
interface ToString {
  toString(): string
}
var b: ToString
var a: object

a = b // error ?
b = 3 // error ?
```

**Comment by mhegazy** [comment]
as @HerringtonDarkholme noted, otherwise it becomes fairly restrictive.

**Comment by gcnew** [comment]
That's an awful loophole. I'm starting to think the problem lies in `{}`. It's not at all intuitive, that everything except `null | undefined` is assignable to `{}`. It's an acquired knowledged which experienced developers have.
