### ISSUE TITLE
How to use compiler API to hold lib.d.ts in precompiled form

### ISSUE THREAD

**Issue by Bobris** [Microsoft/TypeScript#2030]
I am trying to find way how to speed up compilation of lot of independent single file TypeScript programs. I think best result would be to hold lib.d.ts in precompiled form. Is something like this possible with compiler API?

**Comment by DanielRosenwasser** [comment]
You may want to look into [typescript-simple](https://github.com/teppeis/typescript-simple) which utilizes our API.

Otherwise, what you can do is use `ts.createSourceFile` to load `lib.d.ts` exactly once, and then when you make a compiler host, check if `lib.d.ts` is the given file name. If it is, just return your parsed `lib.d.ts`. We do [something similar in our test harness](https://github.com/Microsoft/TypeScript/blob/55aa240ade7949c05293aee82e358a724b1d4f0c/src/harness/harness.ts#L817).

**Comment by Bobris** [comment]
Exactly. I was not sure that it is safe to reuse result of ts.createSourceFile between compilations (and if it make compilation really faster)
