### ISSUE TITLE
Inconsistencies when type arguments are missing from generics

### ISSUE THREAD

**Issue by coreh** [Microsoft/TypeScript#2042]
Suppose you have the following declaration for a generic data structure:

```typescript
declare class MySet<T> {
  constructor();
  add(key: T): MySet<T>;
  delete(key: T): boolean;
  has(key: T): boolean;
}
```

If you attempt to initialize a variable by instantiating this class without specifying a type argument, the compiler will still accept it as valid code and set the type of the variable by performing type inference:

```typescript
var ms = new MySet();
```

However, if you manually specify the variable type but omit the type argument, the compiler will report an error:

```typescript
var ms: MySet; // error TS2314: Generic type 'MySet<T>' requires 1 type argument(s).
```

This behaviour seems to me a bit inconsistent: I'd expect both to work and be equivalent.

Another inconsistency is that the inferred type of the variable `ms` seems to be `MySet<{}>` instead of `MySet<any>`. I understand the reasoning behind this (to be as conservative/strict as possible with the inferred types), but this is probably surprising given that for the built-in `Array` type, if you write `new Array()` you get the inferred type `any[]` and not `{}[]`.

The other generic types in the standard library (e.g. `Set`, `Map`) suffer from this inconsistency as well.

```typescript
var m = new Map(); // Map<{}, {}>
var s = new Set(); // Set<{}>
var a = new Array(); // any[]

var m2: Map; // error TS2314: Generic type 'Map<K, V>' requires 2 type argument(s).
var s2: Set; // error TS2314: Generic type 'Set<T>' requires 1 type argument(s).
var a2: Array; // error TS2314: Generic type 'Array<T>' requires 1 type argument(s).
```

For maximum consistency, it would be nice if the arguments were also inferred when manually specifying the type of a variable, and if it was possible to specify a default type for generic arguments:

```typescript
declare class MySet<T = any> {
  constructor();
  add(key: T): MySet<T>;
  delete(key: T): boolean;
  has(key: T): boolean;
}

var ms = new MySet(); // MySet<any>
var ms2: MySet; // MySet<any>
```

With this feature, the `Map` and `Set` generic types in the standard library could then be updated to match the behaviour of the `Array` built-in.

**Comment by danquirk** [comment]
Some reasonable arguments here. Here's where things stand today and why:
```ts
var ms = new MySet();
```
This infers ```MySet<{}>``` today and is not an error. We give an error when type argument inference has multiple candidates that conflict (ie result in ```{}``` as a best common supertype) but not when there are 0 candidates. We have talked in the past about making this an error but it is a breaking change. We'd have to be very sure we're only breaking code that is essentially already broken. For example with these types of collections there's no error upon construction, but generally at some point later we do report an error when you have to interact with the ```{}``` type that was inferred. Giving the error sooner (essentially requiring explicit type arguments on the constructor) could be an improvement.
```ts
var ms: MySet; // error TS2314: Generic type 'MySet<T>' requires 1 type argument(s).
```
This is disallowed under the assumption that you went to the trouble to write a TypeScript type annotation and we feel it's a little silly to allow you to write such a useless type annotation. This differs from the ```new MySet``` case because in one you have very explicitly done extra work to help the TS compiler (presumably to help yourself get good strong typing), while in the other you've simply brought along some working JavaScript. This rule also first came into being when the default inference for type parameters was ```any``` and not ```{}``` so allowing you to accidentally end up with a ```MySet<any>``` was even worse than a ```MySet<{}>```.

Array has a signature that returns ```any[]``` for ```new Array()```. ```Set``` and ```Map``` do not have this sort of signature but probably should. Default type parameter values are a thing that has come up before I think. The simpler solution for now is definitely to fix the construct signatures for Set and Map.

**Comment by andy-hanson** [comment]
It currently appears to be inferring `any` instead of `{}` even when `--noImplicitAny` is turned on.
The following compiles just fine:

	const m = new Map()
	m.set(0, 1)
	console.log(m.get(0).toUpperCase())

**Comment by mhegazy** [comment]
looks like https://github.com/Microsoft/TypeScript/issues/2175 should address the underlying issue.
