### ISSUE TITLE
never[] type overrides generic defaults

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#20486]
cc @ahejlsberg @sandersn 

**TypeScript Version:**  master

**Code**

```ts
declare function f<T = string[]>(g: (acc: T, val: string) => T, init: T): T;
f((acc, val) => acc.concat([val]), []);
```

**Expected behavior:**

pass

**Actual behavior:**

```
$ node built/local/tsc.js index.ts --strictNullChecks
index.ts(2,28): error TS2345: Argument of type 'string[]' is not assignable to parameter of type 'ReadonlyArray<never>'.
  Types of property 'concat' are incompatible.
    Type '{ (...items: ReadonlyArray<string>[]): string[]; (...items: (string | ReadonlyArray<string>)[]): ...' is not assignable to type '{ (...items: ReadonlyArray<never>[]): never[]; (...items: ReadonlyArray<never>[]): never[]; }'.
      Type 'string[]' is not assignable to type 'never[]'.
        Type 'string' is not assignable to type 'never'.
```

**Comment by DanielRosenwasser** [comment]
What's happening here is that you really want to infer using the return type of the function; however, to do that, it needs its parameters to be typed. TypeScript will need to contextually type those parameters, but to do that well, it will run through arguments that *don't* need a contextual type because those arguments have types that are readily available.

Unfortunately, the only one you have is `[]`, which has the type `never[]` in `strictNullChecks` and `any[]` otherwise. So I'm inclined to mark this as a design limitation or working as intended (@RyanCavanaugh).

**Comment by falsandtru** [comment]
Generally I agree. This behavior may be correct on the type system. However, generic defaults lose the sense with this case. So it is worth treating this as a special case.

**Comment by gcnew** [comment]
Related: https://github.com/Microsoft/TypeScript/issues/19576.
