### ISSUE TITLE
When a .d.ts has no exports, .d.ts should still be an empty module if the file is a module

### ISSUE THREAD

**Issue by misantronic** [Microsoft/TypeScript#20496]
**TypeScript Version:**  2.6.2

**Code**

tsconfig.json:
`"declaration": true,`
file: index.ts

```ts
/** @internal */
export interface MyCoolInterface {
    prop: string
}

...
```

**Expected behavior:**

Create no index.d.ts since its empty

**Actual behavior:**

Creates empty index.d.ts

**Comment by RyanCavanaugh** [comment]
We should actually emit `export { }` here so that the file remains a module

**Comment by weswigham** [comment]
I was going to mark this as `won't fix`, since issues with `@internal` annotations aren't something we prioritize highly (since its experimental and for internal use only); however on inspection the issue can be witnessed without an `@internal` annotation:
```ts
// @declaration: true
// @filename: module.ts
import * as i from "./index";
class Foo {}
// @filename: index.ts
import {} from "./module";
export interface Bar {
    x: string
}
```
emits an empty file for `module.ts` - meaning any TS consumers outside the main compilation who try to require it will get not-a-module errors.
