### ISSUE TITLE
Promise of union types compilation error

### ISSUE THREAD

**Issue by Velenir** [Microsoft/TypeScript#20531]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code**

```ts
const p = Promise.resolve(Promise.resolve('string') || 10)
```

**Expected behavior:**
`p` type to be inferred as `Promise<string | number>`
**Actual behavior:**
Compilation error
```
Argument of type '10 | Promise<string>' is not assignable to parameter of type 'string | PromiseLike<string>'.
  Type '10' is not assignable to type 'string | PromiseLike<string>'.
```

**Notes:**
```
const p2 = Promise.resolve(Promise.resolve('string') || '10')
```
works correctly. It's only when types are different that compilation breaks.

**Comment by andy-ms** [comment]
Note that if you have `--strictNullChecks` on you need `Promise.resolve(1 ? Promise.resolve('string') : 10);` to reproduce this error.

In case you didn't already know, you can work around this using an explicit type argument: `Promise.resolve<string | number>(...)`.

**Comment by sylvanaar** [comment]
When you pass a union type from the use site to a generic method, the behavior seems to be to follow some resolution rules to pick the most applicable component of the union type and apply it rather than combining the types.

`interface Wrap<T> {
    dummy:T
}

type genericWrap = <T>(p: Wrap<T>) => T; 

type genericUnion = <T>(p: T | Wrap<T>) => T; 
const f = {} as genericUnion;
const f2 = {} as genericWrap;

f({} as number | string); // correct

f({} as string | Wrap<number>); // wrong  number | Wrap<number>

f2({} as Wrap<string> | Wrap<number>);  // wrong Wrap<number>`
