### ISSUE TITLE
Debug Failure. False expression: start must be non-negative, is undefined at Object.assert

### ISSUE THREAD

**Issue by ravitb** [Microsoft/TypeScript#2056]
I'm getting this error without further details:
/usr/lib/node_modules/typescript/bin/tsc.js:584
                throw new Error("Debug Failure. False expression: " + (message
                      ^
Error: Debug Failure. False expression: start must be non-negative, is undefined
    at Object.assert (/usr/lib/node_modules/typescript/bin/tsc.js:584:23)
    at Object.createFileDiagnostic (/usr/lib/node_modules/typescript/bin/tsc.js:233:15)
    at getSourceFileFromCache (/usr/lib/node_modules/typescript/bin/tsc.js:6651:40)
    at findSourceFile (/usr/lib/node_modules/typescript/bin/tsc.js:6615:24)
    at processSourceFile (/usr/lib/node_modules/typescript/bin/tsc.js:6587:27)
    at processRootFile (/usr/lib/node_modules/typescript/bin/tsc.js:6575:13)
    at /usr/lib/node_modules/typescript/bin/tsc.js:6544:56
    at Object.forEach (/usr/lib/node_modules/typescript/bin/tsc.js:39:30)
    at Object.createProgram (/usr/lib/node_modules/typescript/bin/tsc.js:6544:12)
    at compile (/usr/lib/node_modules/typescript/bin/tsc.js:18181:26)

Process finished with exit code 8

This issue is related to #1182, all the suggested solutions are not relevant to our project.
This is a blocking issue, therefor it's critical.

I'm using IntelliJ 14.3.

**Comment by RyanCavanaugh** [comment]
Without any information on how to reproduce the issue, we will not be able to fix this very quickly (if at all). Can you post the source code that's causing the failure?

**Comment by DanielRosenwasser** [comment]
@ravitb is your issue resolved?

**Comment by ravitb** [comment]
Yes, I'm using file watchers (IntelliJ) and the file watcher wasn't configured  correctly. The problem solved after fixing the arguments passed to tsc.

**Comment by clark-stevenson** [comment]
I also received this error. Just to note that in my case the character `—` was a part of the generated documentation and when that was in my d.ts file, it caused the above error. 

Removing all instances of that fixed it.  Probably obvious to many, but pretty obscure to me.

**Comment by DanielRosenwasser** [comment]
@clark-stevenson is the stack trace the same? What character are you referring to?

**Comment by loedeman** [comment]
FYI: This issue also appears when using special characters in TypeScript files (e.g. ë, é, ß, and so on). This is kind of awkward, since we tend to use those diacritical characters a lot in Dutch, German and French.

**Comment by clark-stevenson** [comment]
Sorry for the delay. Yes basically what @loedeman said. Inside a definition that I made, I had a special `—` character somewhere in it in the comment stubs.  Due to that character, I got this error discussed here. 

When I did a find and replace of that character, changing `—` to `-` the issue was resolved for me.

**Comment by DanielRosenwasser** [comment]
The error really just means an assumption about the text we're working with has been untrue, so it really doesn't give us a whole lot of information when you say you're getting the same error.

Can either @clark-stevenson or @loedeman please post a stack trace (the same way @ravitb originally did), optimally with a minimal sample that reproduces the error?

**Comment by mhegazy** [comment]
The command line compiler does not support ANSI encoding. this is caused by the underlying file system APIs that are exposed by the JavaScript engines. the issue here, is that the compiler was crashing as it was trying to write the error message for "unsupported encoding".

If you want to use any special characters, you still can, you just need to save your file in a Unicode encoding, utf8 or utf16.

if you are using Visual Studio, you can do that by going to File/Advanced Save Options and select "Unicode (UTF-8 with signature) - Codepage 65001".

**Comment by CyrusNajmabadi** [comment]
Note: regardless of what we support or not, we should not be asserting here, and should instead be giving a good error message that explains the issue to the user.

              -- Cyrus

**Comment by mhegazy** [comment]
@CyrusNajmabadi  the crash has been fixed in #1495

**Comment by liorama** [comment]
I got this error when my automation passed the ```--sourcemap``` argument a file name (needed in the old cli syntax), make sure to remove it.

**Comment by clement911** [comment]
I got that error too. It started happening because I had the micro character in a string 'µ'. Once removed, the error goes away...

**Comment by madmanpierre** [comment]
I have two cases that hopefully will help other people. If you edit code in MS-Word or Outlook, your single quotes and dashes can get changed into 'fancy' ones. If they are then copied back into Visual Studio, you get this helpful (not) message when you build.

I don't know for sure how it happened to us. My best guess is: I copied a comment from code into an email, then I edited it in the email and then copied it back into Visual Studio. And because it was 'just' a comment, I never thought to compile/test (it was on a major development branch that I'm making LOTS of changes to.) so by the time I got the error, it took 3 people several hours to binary search until we found that it was the 'dash' in a comment that was causing this extremely obscure/oblique/useless error.
