### ISSUE TITLE
Ignore import/export statements mode

### ISSUE THREAD

**Issue by achobanov** [Microsoft/TypeScript#20667]
**Disclaimer**

I am a very new in programming and don't have any particular understanding of code transpilation, so please excuse me, if what I propose seems absurd. I would also appreciate some source to educate myself on the matter, since I can't really find concrete readings, specifically related to my request.

**Background**

As things stand right now, I am transpiling my TypeScript only with `tsconfig.json` and using the output `js` file, which I refer as script on the page. Modules are not required. I am using VS code. My problem is that if I don't use `import`/`export` in my code, I get no intelli-sense, which is annoying. Since I have a lot of work on similar projects ahead of me, I'd like to fix that. 

**Enter request**

Create a module mode, for example <b>ignore</b>, which simply ignores all `import statements` and `export` keywords. For example: 
```javascript
export class Constants {
    public static WELLCOME_MESSAGE = 'Hello';
}
```
```javascript
import { Constants } from '../common/constants'

export class Model {
    constructor() { 
        console.log(Constants.WELLCOME_MESSAGE);
    }
}
```
Intelli-sense works, but then I have to compile with `tsconfig.json` - <b>module: amd</b>. It is not impossible, but adds the completely unnecessary in production [require.js][1], since all of my code is in single file anyway. It is also a problem if I work collaboratively with other people, for example in custom tool project. Then everyone would have to use <b>require.js</b>, or I will have to accept the fact that there will be no intelli-sense.

Now if the transpiler could ignore the `import` statement completely - meaning that it would not put any import code into the output and also ignore the `export` keyword, before the <b>Model</b> and <b>Constants</b> - I get the best of both worlds: I get intelli-sense for my project and there are no unnecessary layers of code in the source.

[1]: http://requirejs.org

**Comment by kitsonk** [comment]
You should probably raise these general questions on [StackOverflow](http://stackoverflow.com/questions/ask?tags=typescript) or on [Gitter.im](https://gitter.im/Microsoft/TypeScript), because they go to the basics of using TypeScript.

If you don't want modules, then all the files are assumed to be part of the same global namespace, and you do not need to `import` or `export` anything.  You can use the `"outFile"` compiler option to concatenate all your global JavaScript into a single file which you can load in your page, even if your project is made up of multiple source files.

Also, TypeScript is not designed to be a full build tool.  We have gone down a long long path to make modular code work in JavaScript.  You might want to learn from the many that have gone before you and investigate how something like [webpack](https://webpack.js.org/) can make managing complex sets of dependencies easier and provide you with a single file at the end that can be loaded into a web page.  As soon as you require some other external JavaScript for your project, you are going to want/need to deal with modules.

**Comment by achobanov** [comment]
I am using `"outFile"` in my project and it works in the browser. My problem is that I get no intellisense, because of that. Which is normal, since I don't import any files. I get some partial code-completion, but It's very unreliable and my code is full of red underlines. I merely want to have reliable code-completion and no TS errors white working. That's why I created this <b>Feature request</b>, but maybe I didn't phrase it right, because you thought it was a question. I simply want to use `import/export` in my editor, to get intellisense, then I don't want those `imports` and `exports` in my code. If you think that's not a reasonable request, please do say so and close it ;)

**Comment by andy-ms** [comment]
> My problem is that I get no intellisense, because of that. Which is normal, since I don't import any files. 

You *should* be getting services for global declarations if you are not using modules. The following works for me:

**a.ts**
```ts
const x = 0; // global variable
```

**b.ts**
```ts
x; // Hover over this -- shows `const x: 0`
```

**Comment by achobanov** [comment]
Evidently you are correct. In a custom project that I made myself - it seems to work perfectly. However, it does not work reliably in my project at work. Perhaps the `'tsconfig.json'` is not setup properly. I will investigate tomorrow and come back with a result, but it seems there is no problem here.. In that case, thanks for your time ;)
