### ISSUE TITLE
Wrong type in quick info

### ISSUE THREAD

**Issue by mariusschulz** [Microsoft/TypeScript#20670]
**TypeScript Version:**  2.7.0-dev.20171213

**Code**

```ts
function foo(str: string | null) {
    if (typeof str !== "string") {
        return;
    }

    // (1)
    str += "...";
}
```

**Expected behavior:** Tooltip when hovering over `str` at `(1)` should show type `string`.

**Actual behavior:** Tooltip shows type `string | null`.

**Comment by andy-ms** [comment]
Appears to be a quickInfo-only error, as `str;` before or after that line will correctly have type `string`.

**Comment by mhegazy** [comment]
this is acutely correct.. somehow :)..

so `str += "..."` is `str = str + "..."`. the type of `str` from the compiler perspective is different in both cases.. the first is the declared type.. since `str` can be assigned to `null` at any point in the function. where as the second is the type from flow control, which is what type it has at this specific point int he program.. 

you can see this manifest by hovering on `str` in `str = ""`, it will show `string | null`.

**Comment by mariusschulz** [comment]
That does make sense, indeed. Thanks for elaborating, @mhegazy!
