### ISSUE TITLE
--mapRoot doesn't seem to work

### ISSUE THREAD

**Issue by dani-h** [Microsoft/TypeScript#2067]
```tsc --sourceMap --mapRoot maproot/ --out a.js t.ts```

It simply places the .js.map files in the same directory as the --out file.

**Comment by mhegazy** [comment]
maproot does not place the files in a different place, it just controls the reference to the map file in the .js file. the assumption here is that you will move the map files to a different location, possibly a local directory, where as the other .js files are on your server, or a different server, etc.. it just tells the debugger where to look for the map files instead of next to the .js files.

**Comment by dani-h** [comment]
So the maproot command is there for the debugger to locate the map files, not for moving them anywhere?

**Comment by mhegazy** [comment]
correct. if you look at the javascript output, last line of your file, you will find the reference to the map file. this is what maproot controls. e.g.:

```TypeScript
//# sourceMappingURL=rooot\t1.js.map
```

**Comment by dani-h** [comment]
I see. Thanks! Closing.
