### ISSUE TITLE
bug: async functions are not transpiled correctly

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#20737]
I filed this issue with ts-node, but it appears to be a TypeScript issue

https://github.com/TypeStrong/ts-node/issues/494

**Code**

Here is the offending code:

```ts
const async = require('async');

async.series({
    one: async function(){
      let x = await 1;
      return x;
    },
    two: async function(){
      let x = await 2;
      return x;
    }
  },
  function(err, results){

    if(err){
      throw err;
    }

    console.log('results =>', results);
  });
```

**behavior:**

If we use node.js version 9, it will log `results`
if we transpile with TS first, `results` will not get logged. clear problem.

**Comment by RyanCavanaugh** [comment]
Please read the `async` docs more carefully. The TS emit is correct.

@ORESoftware you've filed 46 issues here and only 1 of them has been a legitimate bug or non-duplicate. I'd be great if you could re-adjust your expectations about how likely it is that you've found a bug in TypeScript vs your own code or some other component. Consider this: If it were true that async functions in TypeScript don't work at all... would you be the *first* person to notice that? If you think you've found a corner case where async functions don't work, then your bug report should be providing the working non-corner-case version as well so that we can immediately diagnose the problem.

**Comment by ORESoftware** [comment]
@RyanCavanaugh I have no idea how the TS emit could be correct given the example above. I can't imagine that a quick read of the async docs is going to help me understand why but I will got take a look right now. And no, more 1 issue I have filed has been useful. I don't like wasting my own time either.
