### ISSUE TITLE
TS doesn't merge members for Window interface

### ISSUE THREAD

**Issue by maximusk** [Microsoft/TypeScript#20747]
I've tried to add a new property `counter` to the `Window` interface like this in the `main.ts` file:

```
// main.ts

interface Window {
    counter;
}
```

**Expected behavior:**

I expected the property to be available on the `window` object:

```
window.counter;
```

**Actual behavior:**

However, I got the error:

```
Error:(19, 16) TS2339: Property 'counter' does not exist on type 'Window'.
```

**Comment by yortus** [comment]
Try this:

```ts
// main.ts

declare global {
    interface Window {
        counter;
    }
}
```

**Comment by maximusk** [comment]
@yortus, thanks a lot, works this way. Can you elaborate a bit?

**Comment by kitsonk** [comment]
Because TypeScript is assuming you are in a module, likely because of the way you have your `tsconfig.json` configured (or the way you are compiling via `tsc`).  It therefore interfaces by default are scoped locally, instead of globally.  `declare global` indicates you are a module attempting to modify the global interfaces.

**Comment by maximusk** [comment]
@kitsonk , got it, thanks a lot!
