### ISSUE TITLE
JSX formatting does not de-indent closing tag with text body

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#20766]
From https://github.com/Microsoft/vscode/issues/40454#issuecomment-352566521

**TypeScript Version:**  2.7.0-dev.20171214

**Code**

```ts
(
    <div>
        text
        </div>
)
```

Run format

**Expected behavior:**

```js
(
    <div>
        text
    </div>
)
```

**Actual behavior:**
No change. Content remains:

```js
(
    <div>
        text
        </div>
)
```

The `</div>` is de-indented if the body is a tag instead of text:

```js
(
    <div>
        <span />
        </div>
)
```

**Comment by Mosho1** [comment]
@mhegazy I've been working on this, and it looks like this doesn't get formatted because the linebreak and whitespace between `text` and `</div>` is consumed as a part of the `SyntaxKind.JsxText` token. I have a fix I can submit but I want to make sure this would be the right behavior (removing the whitespace).

**Comment by mhegazy** [comment]
sounds reasonable. I have not looked at the formatting scanner in a while, so i will need to look at the change, and look around to see if i can poke holes into the fix.

**Comment by orta** [comment]
It's getting late on a Friday, so I'm leaving myself some notes:

Today the text nodes inside the JSX are this range:

```ts
 <div>
     |text
   |</div>
```

Which includes the trailing whitespace. To fix this bug I've explored (a):

```ts
<div>
  |text|
    </div>
```

and (b) 

```ts
<div>
  |text
|   </div>
```

b is generally a bit of a write-off, but a seems promising but needs some finessing somewhere.

Issues:
 - It's changing some  of the JS emit unpredictably:
    - `React.createElement(Bar, null, " q "),` 
        -> `React.createElement(Bar, null, " q"," "),`

- It's bringing up new formatting issues:
    -  This code isn't indenting the 'goodbye' on the 2nd line
        ```
        function foo() {
        return (
                <div>
        hello
        goodbye
                </div>
            )
        }
        ```

There's a good chance the first one is a fencepost error somewhere, but the second I've not figured out yet. [WIP here](https://github.com/microsoft/TypeScript/compare/master...orta:fix_20766?expand=1)

**Comment by orta** [comment]
After amending the parser, it looks like the next issues is that we don't handle JSX siblings affecting indentation: All of these `span`s are [siblings to the `div`s in the AST](https://ts-ast-viewer.com/#code/FACmAJPAeATBLAbgPglaBnADgQwHYD0qUM2+RakcS48sAvAEQAejxJ6WyA8gNLQEulGAQQphmXIXZUy0iaKSoAlMCA):

```ts
(
    <div>
        <span/>
        <span/>
        <div id="x">
            <p>OK</p>
        </div>
        <span/>
        <span/>
    </div>
)
```

Which on master today formats to:

```ts
(
    <div>
    <span/>
    < span />
    <div id= "x" >
    <p>OK < /p>
    < /div>
    < span />
    <span/>
    < /div>
)
```

Which is kinda wild because that code isn't legit JSX.

**Comment by orta** [comment]
It wasn't legit JSX, because it wasn't declared to be a JSX file - doh.
