### ISSUE TITLE
Binding element that is a rest element should always be an array

### ISSUE THREAD

**Issue by osdm** [Microsoft/TypeScript#2085]
In specification 5.1.2, after line "If the binding element specifies an initializer expression, T is the type of that initializer expression" I suggest adding a line:
"Otherwise, if the binding element is a rest element, T is an array type with an element type any".

**Comment by danquirk** [comment]
I believe the current spec is correct. This is the prose associated with binding element:

The type T associated with a binding element is determined as follows:
•	Let S be the type associated with the immediately containing destructuring variable declaration, binding property, or binding element.
•	If S is the Any type:
o	If the binding element specifies an initializer expression, T is the type of that initializer expression.
o	Otherwise, T is the Any type.
•	If S is not an array-like type (section 3.3.2), no type is associated with the binding property and an error occurs.
•	If the binding element is a rest element, T is an array type with an element type E, where E is the type of the numeric index signature of S.
•	Otherwise, if S is a tuple-like type (section 3.3.3):
o	Let N be the zero-based index of the binding element in the array binding pattern.
o	If S has a property with the numerical name N, T is the type of that property.
o	Otherwise, no type is associated with the binding element and an error occurs.
•	Otherwise, if S has a numeric index signature, T is the type of the numeric index signature.
•	Otherwise, no type is associated with the binding element and an error occurs.

**Comment by osdm** [comment]
If S is the Any type and there is no initializer expression, then T would be Any type. How is this correct for a rest element?

**Comment by osdm** [comment]
For example, what type should have "b" in this example?

    function f([a, ...b]) { }

**Comment by danquirk** [comment]
You need to also look at 5.1.3 Implied Type:
_If the declaration specifies an array binding pattern with a rest element, the implied type is an array type with an element type of Any._

which then comes into play with this clause in 5.1.2:
_If the binding element is a rest element, T is an array type with an element type E, where E is the type of the numeric index signature of S._

**Comment by osdm** [comment]
Ok, another example.

    var c: any;
    var [a, ...b] = c;

6.4 doesn't come into play. b is any instead of any[].
