### ISSUE TITLE
Incorrect Resolution of Overloads

### ISSUE THREAD

**Issue by EisenbergEffect** [Microsoft/TypeScript#20932]
I don't know if this is a bug or just me not understanding how overloads work. Here's some code that I've checked against TS 2.5.3:

```ts
class Request1 { }

class Response1 { 
  a: string;
}

class Request2 { }

class Response2 { 
  b: string;
}

interface IServer {
  Send(request: Request1): Promise<Response1>;
  Send(request: Request2): Promise<Response2>;
}

class Server implements IServer { 
  Send(request: any): Promise<any> { 
    return Promise.resolve(null); //TODO: real implementation
  }
}

function createServer(): IServer {
  return new Server();
}

let api = createServer();

api.Send(new Request1()).then(x => { 
    //CORRECT: x is Response1
});

api.Send(new Request2()).then(x => { 
    //FAIL!!! x is Response1 instead of Response2
});
```

[Here's a playground link.](http://www.typescriptlang.org/play/index.html#src=class%20Request1%20%7B%20%0D%0A%20%0D%0A%7D%0D%0A%0D%0Aclass%20Response1%20%7B%20%0D%0A%20%20a%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Request2%20%7B%20%0D%0A%20%20%0D%0A%7D%0D%0A%0D%0Aclass%20Response2%20%7B%20%0D%0A%20%20b%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20IServer%20%7B%0D%0A%20%20Send(request%3A%20Request1)%3A%20Promise%3CResponse1%3E%3B%0D%0A%20%20Send(request%3A%20Request2)%3A%20Promise%3CResponse2%3E%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Server%20implements%20IServer%20%7B%20%0D%0A%20%20Send(request%3A%20any)%3A%20Promise%3Cany%3E%20%7B%20%0D%0A%20%20%20%20return%20Promise.resolve(null)%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20createServer()%3A%20IServer%20%7B%0D%0A%20%20return%20new%20Server()%3B%0D%0A%7D%0D%0A%0D%0Alet%20api%20%3D%20createServer()%3B%0D%0A%0D%0Aapi.Send(new%20Request1()).then(x%20%3D%3E%20%7B%20%0D%0A%20%20%20%20%2F%2FCORRECT%3A%20x%20is%20Response1%0D%0A%7D)%3B%0D%0A%0D%0Aapi.Send(new%20Request2()).then(x%20%3D%3E%20%7B%20%0D%0A%20%20%20%20%2F%2FFAIL!!!%20x%20is%20Response1%20instead%20of%20Response2%0D%0A%7D)%3B)

It seems that the overloads aren't being resolved correctly. No matter what I do, I always get `Promise<Response1>` as the return type. What have I missed?

I've got an API with a single generic `Send` method, but based on what the parameter is, a particular return type follows. If the above is somehow "by design" I'd love an explanation of how/why and if possible some advice on an alternative approach. 

Thanks!

**Comment by kitsonk** [comment]
Working as designed.

TypeScript is a [structural language](https://github.com/Microsoft/TypeScript/wiki/FAQ#what-is-structural-typing).  There is no structural difference between `Request1` and `Request2`, so it always matches only one overload.  You need some sort of structural difference between `Request1` and `Request2` in order to allow TypeScript to discriminate between those types.

[playgournd link](http://www.typescriptlang.org/play/index.html#src=class%20Request1%20%7B%20%0D%0A%20%20private%20type%3A%20'request1'%20%3D%20'request1'%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Response1%20%7B%20%0D%0A%20%20a%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Request2%20%7B%20%0D%0A%20private%20type%3A%20'request2'%20%3D%20'request2'%3B%20%0D%0A%7D%0D%0A%0D%0Aclass%20Response2%20%7B%20%0D%0A%20%20b%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20IServer%20%7B%0D%0A%20%20Send(request%3A%20Request1)%3A%20Promise%3CResponse1%3E%3B%0D%0A%20%20Send(request%3A%20Request2)%3A%20Promise%3CResponse2%3E%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Server%20implements%20IServer%20%7B%20%0D%0A%20%20Send(request%3A%20any)%3A%20Promise%3Cany%3E%20%7B%20%0D%0A%20%20%20%20return%20Promise.resolve(null)%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20createServer()%3A%20IServer%20%7B%0D%0A%20%20return%20new%20Server()%3B%0D%0A%7D%0D%0A%0D%0Alet%20api%20%3D%20createServer()%3B%0D%0A%0D%0Aapi.Send(new%20Request1()).then(x%20%3D%3E%20%7B%20%0D%0A%20%20x%3B%20%2F%2F%20Response1%0D%0A%7D)%3B%0D%0A%0D%0Aapi.Send(new%20Request2()).then(x%20%3D%3E%20%7B%20%0D%0A%20%20x%3B%20%2F%2F%20Response2%0D%0A%7D)%3B)

```ts
class Request1 { 
  private type: 'request1' = 'request1';
}

class Response1 { 
  a: string;
}

class Request2 { 
 private type: 'request2' = 'request2'; 
}

class Response2 { 
  b: string;
}

interface IServer {
  Send(request: Request1): Promise<Response1>;
  Send(request: Request2): Promise<Response2>;
}

class Server implements IServer { 
  Send(request: any): Promise<any> { 
    return Promise.resolve(null);
  }
}

function createServer(): IServer {
  return new Server();
}

let api = createServer();

api.Send(new Request1()).then(x => { 
  x; // Response1
});

api.Send(new Request2()).then(x => { 
  x; // Response2
});
```

**Comment by EisenbergEffect** [comment]
Thanks @kitsonk ! That makes perfect sense. For some reason I thought that nominal typing would work in this particular case, but that's what I get for coding when I should be asleep ;) The good news is that the real implementation will most certainly involve different structures for each input and if not, we could guarantee it using the technique above.
