### ISSUE TITLE
non-null assertion not working on type parameter with constraint

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#20974]
**TypeScript Version:**  2.7.0-dev.20171230

**Code**

```ts
function takeString(p: string) {}

function foo<T extends string | undefined>(param: T) {
  takeString(param!); // error on this line
}
```

**Expected behavior:**
Because of the constraint the compiler knows the type of `param` can only be `string | undefined`. Asserting the type with a non-null assertion should result in `string` and the code should compile without error.

If this is working as intended, I'll write a lint rule to warn about non-null assertions on type parameters.

**Actual behavior:**
```
Argument of type 'T' is not assignable to parameter of type 'string'.
  Type 'string | undefined' is not assignable to type 'string'.
    Type 'undefined' is not assignable to type 'string'.
```

**Comment by RyanCavanaugh** [comment]
> Asserting the type with a non-null assertion should result in string

We would need subtraction types to do this correctly. The correct type isn't `string` (because `T` might be instantiated with some type like `"foo" | "bar"`), it's `T - undefined`.

**Comment by ajafff** [comment]
@RyanCavanaugh makes sense. So this is basically a duplicate of #4183?

**Comment by RyanCavanaugh** [comment]
Not a duplicate since this case wouldn't start working automatically

**Comment by ajafff** [comment]
@weswigham Is this fixed by #22096 or #22348?

**Comment by weswigham** [comment]
#22096 should cover it.

**Comment by weswigham** [comment]
Oh, in case anyone happens to hit this again in the future: The new (more correct) behavior is dependent on the presence of the global `NonNullable<T>` type. If that's not there (because your compilation doesn't include the standard lib or includes an old one), it'll fall back to the older less-correct behavior (and consequently have the same problems). So if you still encounter this issue in TS 2.8+, double check that you've got the latest lib in your build!
