### ISSUE TITLE
`Partial<T>` where `T` has only optional members should not yield `... has no properties in common with type 'Partial<...>'`error

### ISSUE THREAD

**Issue by JasonKleban** [Microsoft/TypeScript#20999]
tsc v2.6.2

Here's an example from [jcormont/documentdb-typescript](https://github.com/jcormont/documentdb-typescript), [Collection.d.ts](https://github.com/jcormont/documentdb-typescript/blob/master/src/Collection.ts) in attempting to support [this new ttl field](https://docs.microsoft.com/en-us/azure/cosmos-db/time-to-live):

```typescript
storeDocumentAsync<T extends Partial<_DocumentDB.DocumentResource>>(data: T, mode?: StoreMode, maxRetries?: number, options?: AllOptions): Promise<T & _DocumentDB.DocumentResource>;

...

export interface DocumentResource extends Resource {
    ttl?: number;
}
```

If I opt NOT to include a `ttl`, I get `[ts] Type 'MyDocument' has no properties in common with type 'Partial<DocumentResource>'.`  

```typescript
const stored = await myDocuments.storeDocumentAsync(myDocument, StoreMode.CreateOnly);
```

I can work around it like this, but it is ugly:

```typescript
const stored = await myDocuments.storeDocumentAsync({ ... myDocument, ttl: undefined }, StoreMode.CreateOnly);
```

**Comment by DanielRosenwasser** [comment]
I believe this is working as intended as part of weak type checking (#16047).

As a side question, does `myDocument` not have an `id` field? I would think `MyDocument` would extend from `Resource` at the least.

**Comment by jcormont** [comment]
Just for reference, this has been fixed by adding `& object` to the type specification for the first parameter of `storeDocumentAsync`.

This makes sense: documents are always 'real' objects (not Numbers, Strings etc) and it seems to stop the TypeScript compiler from being overzealous and warning about common properties -- probably because there _are_ common properties such as `hasOwnProperty`.
