### ISSUE TITLE
"tsc" should not compile a root folder specified in the "typings"

### ISSUE THREAD

**Issue by KostyaTretyak** [Microsoft/TypeScript#20998]
**TypeScript Version:**  2.7.0-dev.20180104

For better visibility, I created a [repository with an example](https://github.com/KostyaTretyak/tsc-is-wrong), which I will refer to here.

If you do the following from the root folder of this repository:

```bash
npm install
npm run compile
```

You will get the following folder structure:

```text
├── dist
│   └── index.js
├── dist-test
│   ├── src
│   └── test
├── node_modules
│   └── typescript
├── package.json
├── package-lock.json
├── README.md
├── src
│   └── index.ts
├── test
│   ├── index.ts
│   └── tsconfig.json
└── tsconfig.json
```

In my opinion, `tsc` works incorrectly in this case, since in `dist-test` it creates two folders: `src` and` test`, instead of creating only `index.js`.

As [you can see](https://github.com/KostyaTretyak/tsc-is-wrong/blob/tsc-is-wrong/package.json#L4-L5), `package.json` specifies that the main project file is `dist/index`. So, why `tsc` ignores this directive for `test` project?

I have noticed that if in `package.json` specify `"typings":"dist/index"` and in root `tsconfig.json` specify `"declaration": true` then it works correctly and in` dist-test` compile only `index.js`.
But what is the reason for changing the behavior of `tsc` if you specify `"typings":"src/index"` and `"declaration": false`?

**Comment by RyanCavanaugh** [comment]
This isn't what `typings` field does. You'd need to specify a path mapping so that `/src` gets redirected to `/dist` instead. We can't change this behavior now since it'd be a breaking change in people's builds.

Automatic redirection from the implementation source file to the output .d.ts file is something I'm working on at #3469. I'll be posting a build there in the next day or so that you can try out which will address this scenario.
