### ISSUE TITLE
Type compatibility of auto-typed object literal is not transitive.

### ISSUE THREAD

**Issue by sccolbert** [Microsoft/TypeScript#2100]
This example demonstrates the issue (runnable in the playground):

```typescript
interface IDict {
	[key: string]: any;
}


function foo(dict: IDict): void { }


function bar(): void {
	var data = { one: 1, two: 2 };
	var data2: IDict = { one: 1, two: 2 }; // ok
	var data3: IDict = data;               // error
	foo({ one: 1, two: 2 });               // ok
	foo(data2);                            // ok
	foo(data);                             // error
}
```

The two error lines (imho) should not be errors. The deduced type is in fact compatible with the interface, as indicated by the acceptance of the literal argument to the function `foo`.

**Comment by DanielRosenwasser** [comment]
This is because `data2` contextually types its initializer expression.

> * In a contextually typed object literal, each property value expression is contextually typed by
  * the type of the property with a matching name in the contextual type, if any, or otherwise
  * for a numerically named property, the numeric index type of the contextual type, if any, or otherwise
  * the string index type of the contextual type, if any.

`data` already had its type inferred; you can't change the type after the fact, which means you can't add a string index signature to its type.

**Comment by sccolbert** [comment]
Thanks for the spec reference! However, this still strikes me as an odd asymmetry, or at the very least a "gotcha" that the deduced type is not structurally compatible with the target. Would you mind expanding a bit on the reasoning which went into the spec decision?

**Comment by DanielRosenwasser** [comment]
That's a bit of a broad question. :smile: 

It depends which part you find to be questionable and what you believe a better alternative would be. If you're curious about why contextual typing exists over plain old inference, I can try to explain that.

**Comment by sccolbert** [comment]
The part which I find strange is that an auto-deduced type is not fully transitive. I would expect there to be no semantic difference between passing an object literal to a function versus storing that literal in an 'auto' variable and then passing it to a function. It would be nice if an 'auto' variable could be contextually typed at the point where it is used instead of restricting its apparent type at the point of definition.

**Comment by DanielRosenwasser** [comment]
That would be a pretty dramatic change to our language. Right now the idea is that you fix types once upon declaration, and this has the benefit of making types easy to reason about. Under your scheme, it sounds like local variables would need to defer contextual typing until specific places like call sites, which would make the type system significantly more complex. For instance, what happens when one call site has a parameter of type `any`? What if you have multiple conflicting call sites? What do you use for the contextual type for an argument when performing type argument inference at a call-site? There are answers to these questions that are acceptable, but probably few that avoid breaking compatibility with existing TypeScript code.

Additionally, I could imagine that there would be a decent overhead impact.

**Comment by sccolbert** [comment]
Fair enough. Thanks for entertaining the question!

**Comment by DanielRosenwasser** [comment]
No problemo - it's always worth discussing!
