### ISSUE TITLE
Unable to use declaration files in a node_modules sub folder with typeRoots

### ISSUE THREAD

**Issue by Neoflash1979** [Microsoft/TypeScript#21018]
So I wrote a bunch of declaration files for a global library under one namespace. I have over 50 `d.ts` files organized in various sub folders, all in the `types` folder. All of the files are written in this style:

```ts
declare namespace pc {
  class Foo {}
  function bar(): void;
}
```

I don't use any triple slash directives, exports or imports anywhere in my declaration files or in my project's source code. TypeScript just does its thing and everything works. If I take all these folders and files and move them from the `types` folder to another folder, lets call it `my-types`, and add `my-types` to `tsconfig.json`'s `typeRoots` compilerOptions, the compiler and my IDE will pick it up and everything still works.

But if I try moving the files and folders into a subfolder of `node_modules`, say `node_modules/my-types` then it doesn't work even if I add `./node_modules/my-types` to the `typeRoots` compilerOptions.

I'm trying this because I want to make all these declaration files into an npm package and I was thinking that I could just add the module's folder to `typeRoots` but it doesn't work.

**Expected behavior:**
I expect `typeRoots` to work with all folders, including `node_modules` subfolders.

**Actual behavior:**
I get a `cannot find namespace pc` error in the compiler and VS Code.

**Comment by andy-ms** [comment]
This is working for me.
**node_modules/my-types/foo/index.d.ts**
```ts
declare namespace pc {
    class Foo {}
}
```

**src/a.ts**
```ts
pc.Foo;
```

**tsconfig.json**
```ts
{
  "compilerOptions": {
    "typeRoots": [
      "node_modules/my-types"
    ]
  }
}
```

Could you try and get a repro for your situation?

**Comment by Neoflash1979** [comment]
Ok, I think I've narrowed down the problem. It seems that declaration files under `node_modules` are only used by TypeScript if they are named `index.d.ts` @andy-ms try changing the name to anything else and you will see an error. This is confusing to me because in any other folder, as long as you add it to `typeRoots`, TypeScript will use all `.d.ts` files, not just the ones named `index.d.ts`.

Like I said in the OP, I have over 50 different `.d.ts` files. I don't see why I would have to rewrite all of them into a single big index.d.ts file just to move them to `node_modules`. They work anywhere else, they should also work under `node_modules`.

**Comment by andy-ms** [comment]
Using a non-`index` file doesn't work for me outside of `node_modules` either. If I move `node_modules/my-types/foo/index.d.ts` to `my-types/foo/scoop.d.ts` and set `"typeRoots": ["my-types"]`, I get a compile error `error TS2688: Cannot find type definition file for 'foo'.`. Could you provide a complete example for your situation?

**Comment by Neoflash1979** [comment]
Weird, it works for me. Actually, I just realized that I don't even need to included it in `typeRoots`, it looks like the compiler and VS Code will just automatically pickup any `d.ts` files in any folder, except for `node_modules`. Here is a link to my repo: https://github.com/Neoflash1979/typescript-test

**Comment by andy-ms** [comment]
In that case `my-types` is included for the same reason that `src` is included -- because it appears in the directory `tsconfig.json` is in, so it's treated like a normal file in your project..

For your original problem of exposing this as an npm package, I would just write an `index.d.ts` file that has a `/// <reference path="foo" />` directive for every file you want included. Then to use this from a program you just reference the package with `/// <reference types="package-name" />` (or add it to `types` in `tsconfig.json`), which picks up `index.d.ts`, which will then include all of the other files.

**Comment by Neoflash1979** [comment]
@andy-ms that's exactly what I ended up doing. I had to write a script that recursively read the folders and file names and write the references to an index.d.ts file. I ended up with about 150 lines of references. Not an ideal solution, but it works in the end.

**Comment by mlwilkerson** [comment]
I have a very similar scenario, except it doesn't involve 50 files. Just one other index.d.ts file that tries to use a triple-slash directive to pull in another .d.ts file with another namespace declaration that I intend to be merged.

I created this little repro repo that shows what's going on. This is with tsc 2.6.2.
[ts-triple-slash-namespace-merge-repro](https://github.com/mlwilkerson/ts-triple-slash-namespace-merge-repro)

@andy-ms Can you see whether I'm doing anything wrong here? I've read and re-read the relevant TypeScript handbook docs and it seems like this should work, especially after reading the additional conversation above.

**Comment by mlwilkerson** [comment]
BTW, while I specified typeRoots similarly in `tsconfig.json`, it doesn't seem to make any difference. Meaning, my working scenario (on my repo's master branch) works regardless of typeRoots, and my erring scenario (on my repo's `triple-slash` branch) errs regardless of typeRoots. So maybe my problem is different from the original in this issue. But it's the closest I've found, having to do both with triple-slash directives and merging namespace declarations.

**Comment by andy-ms** [comment]
@mlwilkerson In that case, you don't actually need a namespace. The namespace merging isn't working because the namespace in `node_modules/foo/index.d.ts` is local, not global, so it isn't merged with the other one.

What you can actually do is:
**node_modules/foo/index.d.ts**
```ts
export as namespace foo;
export function speak(c: Color): void;
```
**node_modules/subfoo/index.d.ts**
```ts
import * as foo from "foo";
declare module "foo" {
  export type Color = 'red' | 'blue' | 'yellow';
}
```

That said, it seems odd to have two separate packages for these if `foo` uses types only defined in `subfoo`, and `subfoo` depends on `foo` -- meaning one can't be used without the other, so they might as well just go in the same package together.

**Comment by mlwilkerson** [comment]
@andy-ms thanks for a blazing-fast reply. Wow!

I clearly need to deepen my understanding of local vs. global namespace. My reasons for using it, though, have to do with trying to mimic the way `@types/react` works, because it's similar to our scenario (I'm adding types to `@fortawesome/fontawesome`). So, for other reasons not illustrated by this simplified repro, it seems like I do need the namespace stuff. But I'm new to TypeScript, and I'm clearly missing something here...

In any case, when I try your code, it generates this error:
```
main.ts(1,28): error TS2306: File '/Users/mike/repos/ts-triple-slash-namespace-merge-repro/node_modules/foo/index.d.ts' is not a module.
node_modules/foo/index.d.ts(1,1): error TS1314: Global module exports may only appear in module files.
node_modules/foo/index.d.ts(2,1): error TS1046: A 'declare' modifier is required for a top level declaration in a .d.ts file.
node_modules/foo/index.d.ts(2,19): error TS2304: Cannot find name 'Color'.
```

Again, I agree that it looks like that these two depend upon one another. And originally, I did have them in the same package. But then I realized that some of our types need to be versioned independently. i.e., we need to be able to deploy a new version of `subfoo` to npm, without necessarily having to deploy a new version of `foo` at the same time.

**Comment by andy-ms** [comment]
@mlwilkerson You probably need to add `/// <reference types="subfoo" />` to the top of `foo/index.d.ts` to ensure that gets included. I don't know why you're getting `node_modules/foo/index.d.ts(1,1): error TS1314: Global module exports may only appear in module files.` though -- the line `export function speak(c: Color): void;` should make that a module file.

If `foo` is exporting something from `subfoo`, have you considered using a re-export? I.e.:
**node_modules/subfoo/index.d.ts**
```ts
export type Color = 'red' | 'blue' | 'yellow';
```
**node_modules/foo/index.d.ts**
```ts
import { Color } from "subfoo";
export { Color } from "subfoo";

export as namespace foo;
export function speak(c: Color): void;
```

**Comment by mlwilkerson** [comment]
Thanks again @andy-ms. I got it working, first in my repro, and then in the actual fontawesome scenario (npm release forthcoming!)

A central part of the challenge all along has been dealing with our library's default export, so I had followed the guidance in the [TS Handbook here](https://www.typescriptlang.org/docs/handbook/modules.html) in the section on "`export =` and `import = require()`" and also used `@types/react` as a guideline, as I mentioned before. Accommodating our default export has been especially difficult with TypeScript and then worse in the CommonJS loading scenario (`--allowSyntheticDefaultImports` is the final piece that completes the default import/export puzzle.)

So, yes, I had tried on a number of occasions to import and then re-export as you suggested most recently, and I always hit the problem that the compiler would not allow me to do both the `export =` and the re-export (like `export { Color } from "subfoo";` above). And since I thought that doing `export =` was crucial for my scenario, I concluded that was a dead end, even though it made sense to me to do the re-export.

After exploring your much simplified suggestions, I'm achieving exactly the loading and type defining scenario I had always intended, but without `export =`. 

Now I'm left a bit confused as to why `export =` seemed so necessary, based on my reading of the TS Handbook, and exemplified by `@types/react/index.d.ts`. And yet, I've solved my problem—in large part—by cutting it out. I'm now basically doing just what your last code sample suggests. (And I don't even need the triple-slash directive any longer).

I'm still trying to find the words to articulate why I think this simplified version is working and my previous version wasn't. Definitely what you said initially about local vs global is a big clue, which seems like it might be related to some other stuff going on in the handbook, discussions of what used to be "external" vs "internal" modules, distinguishing what is now a module from a namespace, what makes one of these files a module at all (because that was one of the error messages I got when trying one of your earlier suggestions—the thing wasn't a module as it was expected to have been), and so forth. Maybe this will all come together in my mind while I'm sleeping tonight, and I'll have a wonderfully summary crisp summary of my new understanding in the morning.
