### ISSUE TITLE
Auto-completion for an indexed interface

### ISSUE THREAD

**Issue by Mosho1** [Microsoft/TypeScript#21022]
**TypeScript Version:**  2.7.0-dev.20180104

**Code**

```ts
export interface Bars {
    bar1?: {a: String};
    bar2?: any;
}

function foo<T extends keyof Bars>(barType: T, bar: Bars[T]) {}

foo('bar1', {});
```

**Expected behavior:**

This line:
```ts
 foo('bar1', {}); 
```
1. Should have an error (`{}` not assignable...)
2. Should autocomplete `a` in this line.

**Actual behavior:**

Has an error but no autocompletion.
If we remove `bar2?: any;`, autocompletion also works.

**Comment by mhegazy** [comment]
For completions to work it needs to know what type of `T` is in this function call. so it does an overload resolution on the call with the given arguments, and that fails since `{}` is not assignable to `{ a: string }`. As a result we have no type of `T`.  
I am not sure what we can do here. one option is to try and use the instantiations even if it failed the overload resolution in the LS..
