### ISSUE TITLE
[TS2.5 regression] Object.values(someEnum) returns string[] (not any[]/number[])

### ISSUE THREAD

**Issue by mprobst** [Microsoft/TypeScript#21089]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code**

```ts
enum X {A, B}

const xs = Object.values(X);
xs.includes(1);
```

**Expected behavior:**

In TS2.5, this used to compile, because `xs` was `any[]`.

**Actual behavior:**

In TS2.6+, `xs` is `string[]`. That's wrong:

```
> Object.values({A: 1, B: 2})
[ 1, 2 ]
```

**Related:**

Curiously, this only happens for enums. `{[k: ...}: V}` style objects work fine.

```
const z: {[k: string]: number} = {
  A: 1
}
const zs = Object.values(z);
zs.includes(1);
```

**Comment by mhegazy** [comment]
The definition of `values` changed, and that seems to trigger this behaviour... 

one option is to give enums a string indexer to `string | number` in addition to the number indexer, but I am not sure i understand what that would affect...

The other is to change definition of values, and use `ArrayLike<T>` instead of `{ [x: number] : T }`. this seems like a smaller change.. I will give this a try.
