### ISSUE TITLE
Implicit 'any' for optional callback in JSX

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#21128]
**TypeScript Version:**  typescript@2.7.0-dev.20180110

**Code**

```ts
import * as React from "react";
export interface RouteProps {
    children?: (props: { x: number }) => any;
}
export class MyComponent<T extends RouteProps = RouteProps> extends React.Component<T> { }
<MyComponent children={({ x }) => {}}/>
```

**Expected behavior:**

No error.

**Actual behavior:**

```
src/a.tsx(6,27): error TS7031: Binding element 'x' implicitly has an 'any' type.
```

**Related:**

@weswigham This is likely related to #21028
Discovered in `react-router` on DefinitelyTyped.

**Comment by weswigham** [comment]
@andy-ms This doesn't repro with the slightly older `react` .d.ts we use in our test harness, so this is going to take a bit longer to debug, as there's more to this than the other issue. From what I've gleaned so far, the primary (meaningful) difference is the application of `Readonly<>` to the `{ children?: ReactNode }` definition of the `props` type (and indeed, adding that to our .d.ts is sufficient to repro the bug), so it looks like this may be caused by some unintended interplay between inference, contextual types, and mapped types. I'm continuing to look into it, but I wanted to give a brief status update.

**Comment by weswigham** [comment]
You can repro this in `2.6.2` without relying on `react`:
```ts
// index.tsx
declare global {
    namespace JSX {
        export type Element = {}
    }
}
// minimal component
interface Component<P = {}, S = {}> { }
declare class Component<P, S> {
    constructor(props?: P, context?: any);
    setState(): void;
    forceUpdate(): void;
    render(): JSX.Element | null;
    props: Readonly<P> & Readonly<{ children?: {} }>;
    state: S;
    context: {};
    refs: {};
}

export interface RouteProps {
    children?: (props: { x: number }) => any;
}
export class MyComponent<T extends RouteProps = RouteProps> extends Component<T> { }
<MyComponent children={({ x }) => {}}/>
```
tsconfig:
```json
{
    "compilerOptions": {
        "jsx": "preserve",
        "strict": true   
    },
    "files": [
        "index.tsx"
    ]
}
```

**Comment by weswigham** [comment]
Also repros in `2.5.3`. `2.4.2`, `2.3.4`, `2.2.2` once you use `noImplictAny` instead of `strict` and remove generic defaults, and `2.1.6`. In short, this issue has existed for as long as mapped types have, so is by no means a recent regression in TS, and is unrelated to #21028. This is definitely a longstanding bug. I'll keep looking for a fix; it's going to be a bit harder since there was never a working version to diff behavior with, though.

**Comment by weswigham** [comment]
The contextual type of `children` is apparently `"(undefined & T["children"]) | (T["children"] & {})"` (where `T` is the props type). When we look for contextual signatures for `T["children"]` intersected with something, we don't resolve the apparent type correctly on the intersection and return no contextual signatures. Fix is simple: actually get the apparent type of intersection constituents when calculating an intersection's apparent type. I'll have a PR up in a bit. This _can_ happen outside of a JSX context, but nobody writes a type that nuts under most circumstances, here it is with no JSX:
```ts
interface Component<P> {
    props: Readonly<P> & Readonly<{ children?: {} }>;
}

interface Props {
    children?: (items: {x: number}) => void
}

declare function f<T extends Props>(i: Component<T>): void;

f({
    props: {
        children: (({ x }) => { })
    }
});
```
You get a `noImplicitAny` error on `x` if `strictNullChecks` is on.
