### ISSUE TITLE
Code Helper attempts to index MPEG-TS files in project and eats 100% cpu

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#21136]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.3.5

**Search Terms**
- video
- mpeg
- mp4
- binary

---

_From @jon-valliere on January 10, 2018 22:54_

- VSCode Version: 1.19.2
- OS Version: 10.13.2

Steps to Reproduce:

1.  Add a MPEG-TS file (e.g. somefile.ts) outside of your normal code folder but somewhere in the project so it shows up in "Explorer" in VSC
2. Look at your processes -- intellicode totally stops working and the process eats 100%

The TypeScript processor should be smart enough to be able to detect if the file is text or not.

_Copied from original issue: Microsoft/vscode#41439_

**Comment by mjbvz** [comment]
_From @usernamehw on January 10, 2018 23:34_

I wonder if you can exclude media folder(or files) from [tsconfig.json](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html):
```javascript
{
  // ...
  "exclude": [
    "media"
  ]
}
```

**Comment by mjbvz** [comment]
There are workarounds we can tell users about on the VSCode side, but moving over to TS to see if the server should be smarter detecting if a file is binary when indexing

**Comment by mhegazy** [comment]
not sure what we can do here.. one option is to bailout on parsing if we see too many parse errors..

**Comment by jon-valliere** [comment]
I have a pretty novel idea: check for data[0] == 0x47 in the first and data[188] == 0x47 // assume this is a mpeg-ts file

**Comment by shirakaba** [comment]
I'm not sure what the convention is about where to continue discussion when an issue is a duplicate, but:

To explain @jon-valliere 's suggestion of reading `date[0] == 0x47` (quoted text from issue #21453 ):

> The [Wikipedia page](https://en.wikipedia.org/wiki/MPEG_transport_stream) indicates that an MPEG-TS file is merely a "sequence of packets, without any global header". Thus, a valid MPEG-TS file will start with a header packet (the format is again described on the Wikipedia page), beginning with a sync byte, invariably with the value 0x47 (The character 'G'). If there is a chance that this could clash with a valid TypeScript file, then further bytes should be read in.

The `data[188] === 0x47` part checks the header at the start of the next packet. It adds some safety, but also wouldn't identify an (admittedly rare) single-packet MPEG-TS file. Unfortunately, the remaining three bytes of the header can all effectively take any value, so they can't be used to extend the fingerprint.

@mhegazy As an alternative to bailing out on high numbers of parse errors, one could bail out if the file size of the .ts file is above a default (yet configurable) threshold, say, 1MB. Java has a similar restriction, wherein the bytecode generated for any method needs to be under 64kB, although I believe that's a hard limit. We are already doing something similar for large JS projects with `--disableSizeLimit` (albeit without allowing one to configure an explicit size limit): #7444.

**Comment by shirakaba** [comment]
@mjbvz Yes, I've tested just now, and that `exclude` option does indeed fix the problem. However, it is ultimately no more than a workaround, as it requires the developer to be fully aware of this issue beforehand; the very nature of this problem is that it is very hard to track down due to the cryptic compiler errors. I could just as easily rename my MPEG-TS files to `.tsv` or `.tsa`, but I've lost a whole day of work on more than one occasion by not being able to identify what the actual cause of the error is.

**Comment by RyanCavanaugh** [comment]
@mhegazy proposing that we bail on files that are > 500 kB and match the above heuristic?

`0x47` is just `G`, unfortunately, but it's hard to imagine a large TS file that doesn't start with `/` or `i`.

**Comment by RyanCavanaugh** [comment]
Probably both; just treat a file like that as having invalid encoding or something.

**Comment by jon-valliere** [comment]
@shirakaba I wouldn't imagine that a file containing a single 188 byte MPEG-TS packet would cause the TypeScript compiler to hang forever.  Not like a 65MB MPEG-TS file does.

**Comment by jon-valliere** [comment]
@mhegazy I guess you could check the entire file, at 188 byte intervals for the 0x47 marker.  If it exists in the entire file, the chance of a false positive would be insignificant.  Maybe the compiler should throw a warning saying that it has detected an MPEG-TS file and print the name just incase there is some crazy situation where there is a false positive.

**Comment by mhegazy** [comment]
A PR would be appreciated. We would follow @jon-valliere's suggestions and check on 188 intervals the input text, then raise an error for an invalid file content if true.

**Comment by shirakaba** [comment]
> I guess you could check the entire file, at 188 byte intervals for the 0x47 marker. If it exists in the entire file

MPEG-TS files can be considerably big (eg. a full Blu-Ray disc can hold 25-50 GB as BDAV MPEG-TS – so if exported to regular MPEG-TS without further compression, would give that kind of ballpark – and one hour of a recorded HD television-quality stream can come to ~1.6 GB). I would recommend not checking the *entire* file if it would cause a large disc read. A few packets should suffice.

Hard disc drives read at ~128 MB/s, and we should aim not to hang on a file for more than a fraction of a second, so how about analysing some (very) small fraction of 128 MB (but as Ryan says, only for files above 500 KB)?

* 3 x 188 KB packets = 564 KB; 0.0044 s read
* 4 x 188 KB packets = 752 KB; 0.0059 s read
* 5 x 188 KB packets = 940 KB; 0.0073 s read
* 10 x 188 KB packets = 1.88 MB; 0.0147 s read
* 20 x 188 KB packets = 3.76 MB; 0.0293 s read

Again, genuine code files do not usually come much larger than 500 KB, so if we keep seeing the sync byte for even around 5 packets, it should indicate a clear positive. How about 188-byte intervals for the first 940 KB, then?

Remember that we may not be talking just one MPEG-TS file here; someone may drop a whole folder of them into the project, so it's wise to be conservative about how much of each one we should be reading in, even if individually the read time might not be too long.

**Comment by jon-valliere** [comment]
@shirakaba I'm not sure where 188 KB packets came from?  They're 188 Bytes; maybe you mean 10,000 x 188 Byte packets?

I like your idea about using a limit. Isn't there already a parse limit of 1MB or am I confused?  Why not just check up to the configured parse limit?

**Comment by shirakaba** [comment]
@jon-valliere Good catch – you're right, I accidentally mistook packets to be in KB rather than bytes in my last comment, so I've corrected it with an edit now. Sorry for the confusion.

For non-TS files, the maximum program size is hard-limited to 20MB (Ryan Cavanaugh explains why shortly after the linked comment): https://github.com/Microsoft/TypeScript/issues/19326#issuecomment-337802257

For TS files, I can't find any mention of a parse limit. Here, someone even performs `tsc --watch` on a 6MB file: https://github.com/Microsoft/TypeScript/issues/10878#issuecomment-250375449

As now edited into my comment above, I have changed my suggested cautionary threshold from 10 packets to 50 packets, as this would keep read times for each file below 1 ms yet still provide a good amount of protection against false positives.

Note: If anyone *really* does need to put a letter 'G' into their file both as the very first character and for every subsequent 188th character for 49 further iterations, then I would suggest a list of good alternatives to the letter 'G' [here - Unicode characters based on 'G'](https://www.compart.com/en/unicode/based/U+0047).

**Comment by jon-valliere** [comment]
@shirakaba The compiler warning about "detection of MPEG-TS file /xxxxx/xxxx.ts" will also notify the user in the unlikely chance that they are attempting to compile a TypeScript file with 'G' in all the wrong places.  That way they're not wondering, "why isn't this file compiling."

**Comment by tchakabam** [comment]
My solution/work-around is quite simple: 

1) I keep source-files in a `src` foldr and have my tsconfig.json only include those. If I need Typescript or JS files in project root or somewhere else, I add them to `include` array explicitely.

2) I keep any MPEG-TS files somewhere else :) 

Since there simply is a collision of file-extension conventions here, I don't see how any "real" solution can be found other than telling the compiler where your Typescript files really are and actually avoiding collisions.

An alternative I could recommend would be using `.tsx` for all TypeScript files, regardless wether they contain JSX or not (since a file that may contain JSX, may also not contain any).

**Comment by rustamsmax** [comment]
When using TS and hls at the same time avoid .ts extension for media chunk files.
There is a `-hls_segment_filename fileNamePath` option for ffmpeg when generating from a media source file

**Comment by rustamsmax** [comment]
![image](https://user-images.githubusercontent.com/36570577/149591985-6063789b-6a2c-470b-8c22-8ef150a6646e.png)

**Comment by jakebailey** [comment]
After #53667, I suspect that this is fixed as we should be bailing out early on these kinds of files. Is anyone still watching this issue that can verify 5.0 vs 5.1 on this front?
