### ISSUE TITLE
Check DOM on-event handlers

### ISSUE THREAD

**Issue by tmkn** [microsoft/TypeScript#21213]
I used TypeScript to move a >60k loc 10y old code base with no unit tests to ES6.
Additionally the foundation was written by people who should have stuck to the backend, lots of weird constructs. So quite the stress-test for TypeScript but it could handle all that pressure as there were no errors due to that refactor and I basically changed a jet engine mid flight.

Among others things the original devs also used DOM on-event handlers thoroughly like this:

`<button onclick="return handleClick(event);">`

which unfortunately TypeScript doesn't account for.
It is doubly painful as there's this nice codelens feature in VSC and some functions now show up with 0 references but they are indeed still needed as they are invoked via DOM on-event handlers.

It would be awesome if TypeScript could look for those and check if the function is resolvable.
In my case there are a lot of JSP's that are variants of this:

`<button onclick="return handleClick('${somestring}', ${anything}, {key: ${value}});">`

In this case I would like to have the compiler check if handleClick is resolvable.
While the actual parameters cannot be determined at this stage we could still do some light type checking as well as we know the number of arguments and can reduce the number of possible types for the first and last parameter.

I think this would complement the spirit of the checkJs command for dealing with legacy code, if this is deemed interesting enough I would like to try and implement that feature(some assistance needed as I'm new to the ts source)

**Comment by mhegazy** [comment]
In Visual Studio today we have similar support in script blocks. In the background, the code in the script blocks is striped out from the html file, and passed in to the analysis engine as separate .js files. We can do something similar here as well.. something like `button.onclick = (event)=>{ return handleClick(event); }`.

This work will need to be done by the HTML editor though, so it is not a TS feature per say.

**Comment by mhegazy** [comment]
//cc @bowdenk7 and @billti

**Comment by billti** [comment]
To expand on Mohamed's point, we only parse script blocks in the JS/TS language service for open files, as the editor for each file-type knows how to extract the script contents within it. Obviously .html files can be straight forward, but we have things like .cshtml with Razor syntax, different templated HTML syntaxes for Node.js or Python, etc. Each of these then introduces complexities that require understanding BOTH languages to parse correctly, as code that runs server-side is often interleaved in the client-side code e.g. in a .cshtml file you can have a script block containing something like ```var x = @serverside.expression;```, where you'd need to know what the C# server expression is going to resolve to in order to figure out the type of JavaScript variable `x`. (Not to mention these pages may be loaded within the context of an outer master or layout page, which may have introduced other scripts that define identifiers being referenced, etc.).

All of these lead to a situation where we can do a best effort at providing very inexact intellisense in script blocks and HTML event handles based on what we can figure out, but being able to feed code into the TypeScript compiler that is of high enough quality/accuracy for useful type-checking becomes next to impossible - especially for language/framework specific file types with their own HTML syntax's (which the compiler would need to understand and parse to remove the current "open files only" limitation).

**Comment by tmkn** [comment]
> This work will need to be done by the HTML editor though, so it is not a TS feature per say.

Idk, I look at it that way that DOM event handlers are a legit way of calling JavaScript, it is in the HTML spec after all so I feel the compiler shouldn't dismiss this method.

Using DOM events instead of addEventListener is perfectly fine, yet the compiler doesn't help you at all in this case. In the very least it should be able to check if the function is resolvable and consequently show up as a reference within the codelens feature.

Making it the duty of the IDE would mean you're at the mercy of whichever IDE you're using, while in reality you do want to know if a particular on-event function doesn't exist as it leads to a TypeError at runtime, while the error would be caught no problem if it was done via addEventListener.
Also CI systems wouldn't be able to detect this.

**Comment by RyanCavanaugh** [comment]
We expose enough LS API now that someone could implement a build-time check for this if they so choose, though the preponderance of this kind of HTML is getting vanishingly small. We don't plan to invest in this area here in the TS project.
