### ISSUE TITLE
Add a "version" key to tsconfig.json

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#2133]
Same as the TypeScript version. This is required to increase the lifetime of `tsconfig.json` files. Few years down:

* if someone wants to open a typescript project they should have an easy way to see why the `tsconfig.json` has compiler options that no longer make sense. And can ask smart questions.
* tools can deny touching a file for a version they do not support. 

# Sample 
```json
{
    "version" : "1.4.1",
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": true,
        "noLib": false
    }
}
```

**Comment by mhegazy** [comment]
One thing to clarify, since it is a JSON file new options are actually ignored by older compilers, so is this intended for documentation purposes or for blocking compilation, i.e. is it expected that tools (compiler, editors, linters etc..) would error if they have a version that is lower than the version in the file?

**Comment by basarat** [comment]
> new options are actually ignored by older compilers

Not necessarily always the case e.g. old options with new values : `'target':'es7'` so the older compiler would barf. 

Even without this it would still be awesome for documentation purposes. Just suggesting if some tooling (like VS) *creates* these `tsconfig.json` files, it should add the `version` field.

**Comment by mhegazy** [comment]
+1

**Comment by johnnyreilly** [comment]
+10 - I think this will be super useful.

**Comment by paulvanbrenk** [comment]
One remark, I would make the version only the first 2 digits, e.g. '1.4'. There should be no breaking changes between 1.4.0 and 1.4.1 (or 1.4.8)...

**Comment by basarat** [comment]
Recommend consistent three numbers. Semver analysis should be left up to the clients. If they don't care about the patch number it's their decision.

**Comment by NickHeiner** [comment]
:+1:

**Comment by RyanCavanaugh** [comment]
We'd like a proposal of what this does in terms of behavior, i.e. what would TypeScript do with this field? Or would it just ignore it?

**Comment by basarat** [comment]
> We'd like a proposal of what this does in terms of behavior, i.e. what would TypeScript do with this field? Or would it just ignore it?

I choose to ignore it. But I've found that it has confused people. So in hindsight just using it for docs was a bad choice on my part 🌹 failed experiment.

**Comment by basarat** [comment]
Better if we say that tsconfig.json "must" support comments. And we leave it up to the creator what they feel like commenting.

**Comment by weswigham** [comment]
> We'd like a proposal of what this does in terms of behavior, i.e. what would TypeScript do with this field? Or would it just ignore it?

The case I can see this being useful is for the selection of a version-appropriate services library by editors for a given project. Which is a good use case, IMO. (Flagging the editor to automatically use the nightly services library so it won't choke on `abstract` and `is`, for example! It's be really nice if I could include the version in my `tsconfig.json` (or `package.json`... since I already declare a TS dependency version there? Not true in VS, I suppose...) and have VSCode fetch it on its own!) 

But no, I don't think TS itself needs to do anything with it. TS is whatever version it is when it reads the file - it's not version managing itself, I don't think.

**Comment by dsebastien** [comment]
+1 for a "version" key.

TS could directly state whether the given tsconfig.json is supported or not (e.g., version more recent than the compiler which would be clear and wouldn't allow for side effects/surprises).

TS could also embed versioned schema files (whatever the state of those is in the json universe) so as to allow editors to provide more contextual information (auto completion and the like).

Having them part of the TS installation would be nice so as to avoid the XML schema hell where all tools embed copies of the schemas etc.

As a side note, knowing that JSON does not support comments (that is sooo wrong Mr Crockford! :p), TS could also ignore all unknown keys, maybe provide hints if a keyname resembles a known one -- or let editors handle that, or at least accept unknown keys matching some rule (e.g., start with _ or whatever).

This would allow us to put inline documentation in the file (e.g., "_target": "Use ES6 because our build pipeline then uses Babel to emit ES5 code").

**Comment by NickHeiner** [comment]
> As a side note, knowing that JSON does not support comments (that is sooo wrong Mr Crockford! :p)

JSON was not originally intended to be a format for humans to read and write, although that's what it's become haha. JSON was just meant to be a way for machines to talk to each other. There are other formats, like yaml and [toml](https://github.com/toml-lang/toml) that are better for config files.

**Comment by mhegazy** [comment]
It does not seem that there is a need for this other than documentation. for that, adding a version property to the tsconfig file is definitely fine. the compiler will not enforce any checks though.
