### ISSUE TITLE
Ordering apply decorators

### ISSUE THREAD

**Issue by kalyuk** [Microsoft/TypeScript#21359]
Why is the decorator for the constructor used in the last place?

`addClassElementDecorationStatements(statements, node, false);
 addClassElementDecorationStatements(statements, node, true);
 addConstructorDecorationStatement(statements, node);`

I think the order should be such

` addConstructorDecorationStatement(statements, node);
  addClassElementDecorationStatements(statements, node, false);
  addClassElementDecorationStatements(statements, node, true);`
since in JS (babel) the order is just such
and it's not logical to apply the decorator to the designer, at that time when the keys have already been initialized

P.S. I apologize for my clumsy English

**Comment by mhegazy** [comment]
The idea is that the class decorator should run when all the members have been processed, and the shape of the class is defined. Consider a case where you have a `@freeze` on a class, you want that to run last after all member decorators, and not before, since a member decorator for instance can call `Object.defineProperty` on a class, or change the value of a method.
