### ISSUE TITLE
Quick fix all for unused imports should only remove other unused imports, not all unused declarations

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#21376]
**TypeScript Version:**  2.7.0-dev.20180119

**Search Terms:** 
- Unused import
- Quick fix all

**Code**

```ts
import a from './a'
import a from './b'

const z = 1;

export default  {}
```

Trigger `quick fix all` on either of the unused imports

**Expected behavior:**
Fix all only removes the other unused imports

**Actual behavior:**
Fix all removes unused imports plus all other unused declarations in the file, such as `z`

**Comment by mhegazy** [comment]
they are actually the same code fix.. to enable this behavior we will need multiple code fixes for each declaration kind.

**Comment by mjbvz** [comment]
Understanable. However removing all the unused declaration when clicking on a import though was unexpected, at least coming from VS. I think that #21378 will make the behavior of quick fix all in this case more clear but would also like to see what others think about handling unused imports separately

**Comment by ricklove** [comment]
I would say there is only a need for two commands:

- `remove all unused imports` 
- `remove all unused declarations (including stuff you might not expect)`

The 2nd command is a powerful feature, it just goes too far: It should only be used on code that has already been committed so that it is easy to verify changes.

In fact, it would be awesome if the 2nd command could actually warn you:

- `remove all unused declarations (including 3 changes not under source control)`

But removing unused imports is reasonably safe since it is easy to add those back with the inverse command: `add all missing imports`. 

Unfortunately there isn't a quick fix for the 2nd: `add that code you were working on for a few hours and just wiped out with a quick fix`.

Oh well, I'll just never use that command again except after committing everything and then doing a refactoring commit (which is likely good practice anyway).

**Comment by mjbvz** [comment]
Closing due to lack of additional feedback over the past few years
