### ISSUE TITLE
Mapped type should take a function form as well

### ISSUE THREAD

**Issue by pleerock** [Microsoft/TypeScript#21421]
According to #12114 mapped types currently support following forms:

```ts
{ [ P in K ] : T }
{ [ P in K ] ? : T }
{ readonly [ P in K ] : T }
{ readonly [ P in K ] ? : T }
```

I think it shall also at least support a function form:

```ts
{ ([ P in K ]) : T }
{ ([ P in K ]) ? : T }
{ ([ P in K])(entities: P[], someBoolean: boolean) ? : T }
```

Currently Im trying to implement a `Functionize<T>` interface which forces implementors to implement any property of the T, but make it a function with maybe additional arguments. Example:

```ts
interface User {
     name: string;
     age: number
}
```

I want to do Functionize<User> which I want to give me:

```ts
{
       name(names: string[]): string;
       age(ages: number[]): number;
}
```

And I'm asking about following method signature:

```ts
type Functionize<T> = {
   [P in keyof T](values: T[])?: T[P];
};
```

**Comment by pleerock** [comment]
Someone suggested to do:

```ts
type Functionize <T> = {
   [P in keyof T]: () => T[P];
};
```

however it does not work with extra function parameters, e.g.

```ts
type Functionize <T> = {
   [P in keyof T]: (values: T[]) => T[P];
};
```

compiler have no errors when values argument is not defined in the implementor of Functionize interface.

**Comment by jack-williams** [comment]
> however if I do simply name() its not telling me that names is required parameter.

The issue might be that a signature that accepts fewer inputs is assignable to one that accepts more (provided they agree on matching parameters and output). So the following is acceptable:

```typescript
let f: () => number = () => 42;
let g: (x: number[]) => number = f;
```

In your specific example, the type `{ name: () => string }` is assignable to the type `{ name: (names: string[]) => string }`.

You get a compiler error when using `boolean[]` because they disagree on a shared parameter.

Also, from your requirements I think the definition of `Functionize` should be: 
```typescript
type Functionize <T> = {
   [P in keyof T]: (values: (T[P])[]) => T[P];
};
```
(added a lookup on the type of `values`.

**Comment by pleerock** [comment]
> Also, from your requirements I think the definition of Functionize should be:

correct, sorry Im using a bit different code, I just wanted to provide an example and make this mistake.

> In your specific example, the type { name: () => string } is assignable to the type { name: (names: string[]) => string }.

correct, that's exactly issue I have. Is it tracked, or is it by design?

**Comment by jack-williams** [comment]
I believe it's by design. From the spec:

> M has a rest parameter or the number of non-optional parameters in N is less than or equal to the total number of parameters in M.

when defining whether call-signature N is a subtype of call-signature M.

Intuitively if a user writes a function of type `() => number`, then it can always ignore extra arguments given and still return a number. So it also works when used as the type `(x: boolean) => number` or `(names: number[]) => number`.

The only way I could see this being something you *don't* want is if the output of the function *must* come from the input of the function. So in the type:
```
{
       name(names: string[]): string;
       age(ages: number[]): number;
}
```

the output of `name` always comes from an element in `names`, and the output of `age` always comes from an element in `ages`. If this is something you want, then I think the most likely solution will be parametricity and generics. Instead, would the follow types for you work?
```
{
       name<X>(names: X[]): X;
       age<X>(ages: X[]): X;
}
```
The rules about adding extra inputs to a function signature still apply, but in this case it's impossible to create something of type `X` out of nothing (unless you cheat and use `any`). An implementor of the function will not be able to write a function with the type: `<X>() => X`; the only way to return an `X` is to use one that is given to you from the input.

**Comment by mhegazy** [comment]
here is the syntax for definitnon a mapped type with function typed properties:

```ts
type methods<T> = {[P in keyof T]?: (entities: P[], someBoolean: boolean) => T };
```

**Comment by pleerock** [comment]
okay thank you guys, I think this issue can be closed.
