### ISSUE TITLE
Spread operator on a static factory method returns objects without instance methods and is uncaught by the compiler.

### ISSUE THREAD

**Issue by delRyan** [Microsoft/TypeScript#21472]
**TypeScript Version:**  2.8.0-dev.20180127

**Search Terms:** 
instance method spread static factory

**Code**

```ts
interface IGreeter {
    greeting: string
    greet(): string
}

class Greeter implements IGreeter {
    public constructor(public greeting: string) { }

    greet() { return this.greeting; }

    // Runtime error if greet() is called. Objects will not have a greet() method. (Unexpected)
    public static greeterFactory1(greeting: string): IGreeter {
        return {
            ...this.emptyGreeter(),
            greeting 
        }
    }

    // // Compile error. Objects will not have a greet() method.
    // public static greeterFactory2(greeting: string): IGreeter {
    //     return {
    //         ...new this(""),
    //         greeting 
    //     }
    // }

    public static emptyGreeter(): IGreeter {
        return new this("");
    }
}
```

**Expected behavior:**
I would expect the above code to not compile for the following reason:
```
Type '{ greeting: string; }' is not assignable to type 'IGreeter'.
  Property 'greet' is missing in type '{ greeting: string; }'.
```

This is the behavior when uncommented greeterFactory2.

**Actual behavior:**
Compilation succeeds and runtime exceptions will be thrown when greet() is called.

**Playground Link:**  [Playground Link](https://www.typescriptlang.org/play/#src=interface%20IGreeter%20%7B%0D%0A%20%20%20%20greeting%3A%20string%0D%0A%20%20%20%20greet()%3A%20string%0D%0A%7D%0D%0A%0D%0Aclass%20Greeter%20implements%20IGreeter%20%7B%0D%0A%20%20%20%20public%20constructor(public%20greeting%3A%20string)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.greeting%20%3D%20greeting%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20greet()%20%7B%20return%20this.greeting%3B%20%7D%0D%0A%0D%0A%20%20%20%20%2F%2F%20Runtime%20error.%20Objects%20will%20not%20have%20a%20greet()%20method.%20(Unexpected)%0D%0A%20%20%20%20public%20static%20greeterFactory1(greeting%3A%20string)%3A%20IGreeter%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20...this.emptyGreeter()%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20greeting%20%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20%2F%2F%20%2F%2F%20Compile%20error.%20Objects%20will%20not%20have%20a%20greet()%20method.%20(Expected)%0D%0A%20%20%20%20%2F%2F%20public%20static%20greeterFactory2(greeting%3A%20string)%3A%20IGreeter%20%7B%0D%0A%20%20%20%20%2F%2F%20%20%20%20%20return%20%7B%0D%0A%20%20%20%20%2F%2F%20%20%20%20%20%20%20%20%20...new%20this(%22%22)%2C%0D%0A%20%20%20%20%2F%2F%20%20%20%20%20%20%20%20%20greeting%20%0D%0A%20%20%20%20%2F%2F%20%20%20%20%20%7D%0D%0A%20%20%20%20%2F%2F%20%7D%0D%0A%0D%0A%20%20%20%20public%20static%20emptyGreeter()%3A%20IGreeter%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20new%20this(%22%22)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20greeter%20%3D%20Greeter.greeterFactory1(%22Hello!%22)%3B%0D%0A%0D%0Aconsole.log(greeter.greet())%0D%0A)

**Comment by aluanhaddad** [comment]
The following are both valid implementations of `IGreeter`
Consider this
```ts
const emptyGreeter = {
  greet() {return this.greeting;},
  greeting: ''
};
```
and this
```ts
const emptyGreeter = new class {
  greet() {return this.greeting;}
  greeting = '';
}();
```
However, both interact differently with the spread operator. 

There is not currently a way to express the _ownness_ of a property at the type level and therefore no way to explicitly express the type level transformation implied by the spread operator.

https://github.com/Microsoft/TypeScript/issues/10727 tracks adding spread types.

However, the language does understand the distinction and tracks it correctly if you let it do its job. 

The types of objects created by spreading other objects are in fact tracked and enforced.

However, by specifying the return type of `emptyGreeter` as `IGreeter` you have _removed_ type information that the compiler would otherwise have, information it needs to track the effects of spreading an object. If you remove the type annotation, you will get the expected errors.

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/10288
