### ISSUE TITLE
 Typescript JSON.stringify() serializing protected keys

### ISSUE THREAD

**Issue by Talha-T** [Microsoft/TypeScript#21608]
**TypeScript Version:**  2.6.2

**Search Terms:**  JSON protected, Typescript JSON serializing protected keys, Typescript json stringify private

**Code**

```ts
class TestClass { 
    protected test: string = "test!";
}

JSON.stringify(new TestClass());
```

**Expected behavior:** JSON.stringify() shouldn't serialize protected keys(properties).

**Actual behavior:** It serializes all properties, without looking at it's accessibility.

**Playground Link:** https://www.typescriptlang.org/play/#src=class%20TestClass%20{%20%20%20%20%20protected%20test%3A%20string%20%3D%20"test!"%3B}JSON.stringify(new%20TestClass())%3B

**Related Issues:**

**Comment by j-oliveras** [comment]
This works as intended: typescript compiles to javascript and at runtime all javascript properties are public.

**Comment by Talha-T** [comment]
But how it is intented if protected variable is gonna get serialized? You could say expected,  but this is definitely not intended I guess

**Comment by DanielRosenwasser** [comment]
Since these are only design-time modifiers, we don't do anything special here. You can always use a JSON replacer or define a `toJSON` [See here](https://stackoverflow.com/questions/4910567/hide-certain-values-in-output-from-json-stringify) for more details.

ECMAScript private fields may be what you want though.
