### ISSUE TITLE
Conditional types can't distinguish boolean type from boolean literals

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#21682]
So TypeScript can't make a comparison type which behaves as *`Eq<false, boolean>` is false*.

cc @ahejlsberg 

**TypeScript Version:**  2.8.0-dev.20180204

**Search Terms:** 

**Code**

```ts
type BLit<T> = T extends false ? 'false' : 'boolean';
type NLit<T> = T extends 0 ? '0' : 'number';
type a = BLit<false>; // 'false'
type b = BLit<boolean>; // 'boolean' | 'false'
type c = NLit<0>; // '0'
type d = NLit<number>; // 'number'
```

**Expected behavior:**

```ts
type b = BLit<boolean>; // 'boolean'
```

**Actual behavior:**

```ts
type b = BLit<boolean>; // 'boolean' | 'false'
```

**Playground Link:**  

**Related Issues:**

**Comment by mhegazy** [comment]
`boolean` is just `true | false`.. plug that in `T extends false ? "false" : "boolean"` and it distributes since it is a union type, i.e. it is repeated for every constituent of the union type.. so you get `(false extends false ? "false" : "boolean") | (true extends false ? "false" : "boolean")` which is `"false" | "boolean"`
So i guess you can define the type as `type BLit<T> = T extends false ? 'false' :  'true';` to get `"false" | "true"` for `boolean`.

**Comment by falsandtru** [comment]
> boolean is just true | false

I described it makes a difference between `boolean` and other types and an impossibility of type comparison. Conditional types have this defect on the type-level programming. @ahejlsberg Is this your intended imperfection?

**Comment by falsandtru** [comment]
I understand this problem appears with all union types. To use Conditional types for narrowing of union type is not good at all.
