### ISSUE TITLE
 Issues with npm typescript@1.4.1 on windows

### ISSUE THREAD

**Issue by dantedubon** [Microsoft/TypeScript#2174]
I got differences between the npm installation on windows and the installation for Mac. On windows when I list my node packages I can see the Typescript 1.4.1, but the version of tsc says 1.0.3.0: 
![windows typescript](https://cloud.githubusercontent.com/assets/7613864/6426853/5b22ca2a-bf33-11e4-8618-dfb3c9a49d16.png)

On Mac, however, I can see the desired tsc version (1.4.1.0):
![mac typescript](https://cloud.githubusercontent.com/assets/7613864/6426859/94a27912-bf33-11e4-96bf-a68050ecf7c0.png)

**Comment by DickvdBrink** [comment]
You might want to execute `where tsc` on your Windows system, it will probably return multiple results and the first one will be the 1.0.3.0 version I think.

Probably your PATH environment variable is wrong, you can check that by executing `echo %PATH%` and you will probably see something like `C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;` tere before the raming npm path. You can change that by going to the Control Panel -> System & Security -> and on the left there is "Advanced System settings", click on It and a popup will open. Chose the tab. "advanced" tere and click the button "Environment variables", there you can change your path. Reopen your command prompt (MSys on the look of your screenshot) or the change wont have any effect.

I hope the names are right, because I'm currently on a Dutch Windows version. If you have any problems please let me know :)

**Comment by dantedubon** [comment]
Thank you very much, This solved my problem, But, this situation happened on a fresh new installation of Node and tsc, using npm. I only had VS2013 before, this could be an error from the package on npm? Again thanks a lot.

**Comment by DickvdBrink** [comment]
Added a comment on your SO question :) glad it worked out!

**Comment by DanielRosenwasser** [comment]
Thanks for getting to this @DickvdBrink. Could one of you guys link to the StackOverflow question for completeness?

**Comment by DickvdBrink** [comment]
Sure: here is the link :) Glad I could help!
http://stackoverflow.com/questions/28776943/compile-issues-with-npm-typescript1-4-1-on-windows

**Comment by styfle** [comment]
I just had this happen to me when installing typescript 1.8 via npm. I couldn't for the life of me figure out why there was an old version of tsc being reported.

The workaround for me was to remove `C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;` from my `PATH` environment variable.

Should this be added to a FAQ? I'm sure anyone with Visual Studio installed will have this problem.

**Comment by gamifiq** [comment]
"The workaround for me was to remove C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\; from my PATH environment variable."

Same for me. Thanks for the hint.
