### ISSUE TITLE
Unsound interaction between `Pick` and union subtyping.

### ISSUE THREAD

**Issue by cakoose** [Microsoft/TypeScript#21820]
Typescript Version: 2.7.1 (with `--strict`).

I'm trying to use `Pick` to type a function like Lodash's `pick` ([docs](https://lodash.com/docs/4.17.4#pick)).

```typescript
declare function pick<T extends object, F extends keyof T> (obj: T, fields: F[]): Pick<T, F>;
```

(This is similar to what the DefinitelyTyped declaration does: [Lodash `pick` type declaration](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ff2359e74ce1c539097e47dc586d49d348a94587/types/lodash/object/pick.d.ts#L19)).

This seems unsound because of the way union subtyping works:

```typescript
type Thing = {
    a: number,
    b: string,
    c: boolean,
};

function good(t1: Thing) {
    const t2 = pick(t1, ['a', 'b']);
    console.log(t2.a);
    console.log(t2.c);  // <-- compile-time error (good)
}

function bad(t1: Thing) {
    const fields: ('a' | 'b' | 'c')[] = ['a', 'b'];  // union subtyping
    const t2 = pick(t1, fields);
    console.log(t2.a);
    console.log(t2.c);  // <-- no compile-time error, just runtime error (bad)
}
```

I think this is the intended use case of `Pick` but maybe I'm mistaken.

It seems like union subtyping goes in the "wrong" direction for this use case.  Intersection subtyping would go in the desired direction, but I can't figure out how to make use of them here.

**Comment by mhegazy** [comment]
Not sure what is the issue here.. `fields` declared type contains `"c"`, so the inference in `pick` seems right to me. 
the assignment seems correct as well.

**Comment by jack-williams** [comment]
The issue is that the return type is technically wrong, it should be a union of object types, where each object type is one of the permutations of the keys. For instance, the array could be empty and the `pick` function will return `{}`, but the empty object is not a subtype of `{
    a: number,
    b: string,
    c: boolean,
}`.

The unsoundness comes from the (implicit) assertion in the `pick` implementation that every key in the union type actually appears in the array.

**Comment by cakoose** [comment]
Right.  I assumed `Pick` was intended for a this use case because its name matched the common `pick` function.

Is there a way to give a precise type to the `pick` function?

**Comment by jack-williams** [comment]
@cakoose I don't think it is that unreasonable to use `Pick` like this, it just has a few conditions to be careful of.

I think the most accurate type is going to be:
```typescript
declare function pick<T extends object, F extends keyof T> (obj: T, fields: F[]): Partial<Pick<T, F>>;
```
that will make every property possible undefined, which reflects the fact that the array might not actually have an element that is in the type `F`, so the property will not appear in the result.

**Comment by cakoose** [comment]
I see.  Typical uses of the `pick` function won't find that type useful, unfortunately.

I guess the best solution right now is to keep using the (unsound) `Pick<T, F>` return type.  It seems to work fine for typical cases because Typescript's current inference will reject the `t2.c` access instead of automatically widening `F` to include `c`.

It would be nice to handle `pick` more precisely, though.  Should I file an enhancement request?

**Comment by jack-williams** [comment]
> I guess the best solution right now is to keep using the (unsound) Pick<T, F> return type.

Agreed. I expect most users would just rely on type inference rather than explicitly making the type larger to include more keys (like `bad`), in which case the current definition should be fine.

> It would be nice to handle pick more precisely, though. Should I file an enhancement request?

If you have suggestions about how this could be fixed then go for it, my experience of the TypeScript team and community has always been positive when it comes to suggestions and feedback. Note: I'm not in anyway affiliated with TypeScript so my recommendation doesn't mean anything!

**Comment by cakoose** [comment]
Filed a slightly modified version at https://github.com/Microsoft/TypeScript/issues/22113
