### ISSUE TITLE
Cannot find name 'require' and 'module' when @ts-check is on

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#21933]
We spoke about this with @mjbvz a few months ago.

When tossing `checkJs` or `// @ts-check` into a project, users almost immediately get feedback like `Cannot find name 'require'` which is frustrating because we specifically understand how `require` works.

I understand that we want users to have more actionable feedback when they require a Node built-in, but the current behavior is not ideal.

**Comment by DanielRosenwasser** [comment]
So two things:

1. We now have Suggestion diagnostics where we can prompt people to `npm install @types/node` if these identifiers show up.
2. We should ensure this works for

   - `require`
   - `module`
   - `exports`

**Comment by mhegazy** [comment]
If we resolve the name `require` and it fails, and `isRequireCall` is true (i.e. it is a call expression, and it has a single argument that is a string literal), then we should resolve it to built-in require symbol (this should replace the use of `isCommonJsRequire`).

If this is a .ts file we should error like we do today, with an explanation `Can not find name "require". Did you forget to install "@types\node"?`.

If this is in a .js file, we should not, since we already treat these in a special way.

**Comment by sandersn** [comment]
We should also special-case the built-in node modules and give an *even* better error message, like "Can not find module "fs". Did you forget to install `@types/node`? (This would also apply to JS.)

**Comment by mhegazy** [comment]
We have the list of built-in node modules in https://github.com/Microsoft/TypeScript/blob/master/src/services/jsTyping.ts#L34. we should use that in giving ppl better error message, and enabling a quick fix to install the app for you.
