### ISSUE TITLE
2.8.0-dev.20180213: Function with conditional type as parameter and return value losing correct type

### ISSUE THREAD

**Issue by Q-Man** [Microsoft/TypeScript#21939]
**Typescript Version**
2.8.0-dev.20180213

**Code**

```ts
type Type1<T> = T extends object ? T : T;
type Type2<T> = T extends object ? T : T;

function myFunction<T>(p: Type1<T>): Type2<T> {
	return null;
}

let value1:Type1<any[]> = null;
let value2:Type2<any[]> = myFunction(value1);
```

**Expected behavior:**
Should compile without errors.

**Actual behavior:**
Compile error: 

**TS2322: Type '{}' is not assignable to type 'any[]'.
  Property 'find' is missing in type '{}'.**

The example doesn't make much sense, but is the minimal code to reproduce the behaviour. Removing the condition in any of the 2 type definitions (`type Type<T> = T`) makes the example work.

**Comment by jcalz** [comment]
Do you expect the compiler to be able to do inference from conditional types the way it can currently do [inference from mapped types](https://www.typescriptlang.org/docs/handbook/advanced-types.html#inference-from-mapped-types)?  That is, do you want it to observe that `Type1<T>` is `any[]` and deduce that `T` must be `any[]` as well?  That might be plausible in the example you gave where `Type1<T>` is always `T`.  But in general such inference would require that the compiler recognize when a conditional type function is [injective/invertible](https://ghc.haskell.org/trac/ghc/wiki/InjectiveTypeFamilies), and then calculate the inverse type function automatically.  That seems unreasonable to me.

As a more reasonable workaround: if you know that a conditional type function is invertible, why not build the inverse type yourself and use it?   For example:

```ts
type Type1<T> = T extends object ? T : T;
type InverseOfType1<T> = T;  // by inspection
type Type2<T> = T extends object ? T : T;

declare function myFunction<T>(p: T): Type2<InverseOfType1<T>>;
declare const value1:Type1<any[]>;
let value2:Type2<any[]> = myFunction(value1); // works now
```

**Comment by Q-Man** [comment]
I'd expect that the compiler executes the condition for the type of the parameter and the type of the return value, then it would be clear that the assigning is right.

**Comment by jcalz** [comment]
In the first case, the compiler is merely verifying that `Type2<string[]>` is assignable to `Type1<string[]>`.   The compiler doesn't have to *infer* anything.  

In the second case, you are asking the compiler to *infer* the generic type `T` in the call to `myFunction(value1)`.  If you instead explicitly specify the intended value of `T` like this:
```ts
let value2: Type2<string[]> = myFunction<string[]>(value1);  // okay
```
everything works.   But by omitting the explicit type parameter, you are asking the compiler to *figure out* what `T` should be, given the facts that `value1` is a `Type1<string[]>` and that the return value is expected to be a `Type2<string[]>`.   

Do you understand the difference now?

**Comment by Q-Man** [comment]
Without knowing the internals of the type inference I would just expect that the compiler uses the generic Type T from the definition of `Type1<string[]>` and `Type2<string[]>` since it's already explicitly defined there. 

I would expect that it's valid to call the function `function myFunction<T>(p: Type1<T>): Type2<T>` without explicit type parameter if T has the same type for Type1 and Type2, no matter what's the actual definition of Type1 and Type2.

**Comment by jcalz** [comment]
TypeScript is largely [structurally typed](https://www.typescriptlang.org/docs/handbook/type-compatibility.html).  That means that if you have two types that have the same structure but differ in name, they are essentially considered to be the same type.  The only surefire way to create two distinct types is to give them differing structures.

It is also the case that [type aliases](https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-aliases) declared using the `type` keyword are merely new names for existing types.  They do not create a new type.

Finally, TypeScript tends to eagerly evaluate type aliases when it can do so.  So if you do this:
```ts
type Foo<T> = {bar: T};
type FooString = Foo<string>;
```
then `FooString` is immediately evaluated to be `{bar: string}` with no memory of the generic `T`.  The compiler does not carry around `Foo<string>` so it can pull out `string` later.  So when you say

>I would just expect that the compiler uses the generic Type `T` from the definition of `Type1<string[]>` and `Type2<string[]>` since it's already explicitly defined there.

there is no `T` anymore for it to use.  As an analogy, it's as if you took this code
```ts
const f = x => x + 1
const y = f(3)
console.log(y);  // 4
```
and expected `y` to remember that it is `f(3)` and somehow pull the `3` out of there.  But `y` doesn't know anything about `f()` or `3`.  It's just `4`.

Armed with that knowledge, do you understand why what you expect is not reasonable?  Yes, it is conceivable that TypeScript could be implemented so that it caches all applications of type alias functions and uses it to attempt to automatically invert them when possible.  But that would be a lot of work and TypeScript just doesn't work that way.  If you want it to work that way, then you need to present a suggestion with a proposal for how it might be implemented. 

---

The above is all my opinion.  I don't maintain TypeScript, so even were I to agree with you I couldn't get anything done here by myself.  At this point I will no longer participate in this thread until someone from the actual team classifies this bug report as a bug, design limitation, or working as intended.  Good luck.

**Comment by Q-Man** [comment]
I understand, thanks for the detailed explanation.
