### ISSUE TITLE
Incorrect escaping of unicode character in JSX attribute

### ISSUE THREAD

**Issue by pomadin** [microsoft/TypeScript#21992]
**TypeScript Version:**  2.7.2

Starting 2.7 typescript transpiles literals differently in JSX. It escapes backslash (`\`) symbol. When I use v2.6 the compiler works as I expect.

**Code**

```ts
// tsc --jsx react
const Space = "\u2000";
function Sample() {
    return <div title="\u2000"/>;
}
```

**Expected behavior:**
```js
var Space = "\u2000";
function Sample() {
    return React.createElement("div", { title: "\u2000" });
}
```

**Actual behavior:**
```js
var Space = "\u2000";
function Sample() {
    return React.createElement("div", { title: "\\u2000" });
}
```

**Comment by mhegazy** [comment]
PRs welcomed.

**Comment by jphhoeks** [comment]
You can use a tempalte string as a workaround:

````
<div title={`\u2000`} />
````

**Comment by Kingwl** [comment]
What is the expected behavior of this?
escape all attribute text have some overkill

**Comment by Andarist** [comment]
The current behavior of TS matches both Babel and esbuild so I'd assume that it's actually the correct one and that this issue can be closed, cc @jakebailey

**Comment by jakebailey** [comment]
I have a hard time believing it's correct when they're entirely different values...

```
> "\u2000"
' '
> "\\u2000"
'\\u2000'
```

**Comment by evanw** [comment]
JSX is XML in JS, for better or worse. Character escapes in XML use `&`, not `\`. That looks like this:

```jsx
const Space = "\u2000";
function Sample() {
    return <div title="&#x2000;"/>;
}
```

That generates the following JavaScript with [Babel](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYewdgzgLgBAygBwIbAKYwLwwEQB0CuATAAynYDcAUAGb5jBQCW48SAtggDaoAUAlDADelGKJgAnVFHziwMADwATRgDcYTKNwzYAZAGIAHiVLlsAegB8VAL5A&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.22.9&externalPlugins=&assumptions=%7B%7D), [esbuild](https://esbuild.github.io/try/#dAAwLjE4LjE2AC0tbG9hZGVyPWpzeABjb25zdCBTcGFjZSA9ICJcdTIwMDAiOwpmdW5jdGlvbiBTYW1wbGUoKSB7CiAgICByZXR1cm4gPGRpdiB0aXRsZT0iJiN4MjAwMDsiLz47Cn0), and also in [TypeScript](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAygBwIbAKYwLwwEQB0CuATAAynYDcAUAGb5jBQCW48SAtggDaoAUAlDADelGKJgAnVFHziwMADwATRgDcYTKNwzYAZAGIAHiVLlsAegB8VAL5A):

```js
const Space = "\u2000";
function Sample() {
    return React.createElement("div", { title: "\u2000" });
}
```

As mentioned already you can easily escape from XML back to JS if you want to write JS instead of XML.

TypeScript appears to be behaving correctly here. I recommend keeping the existing behavior since the ecosystem is already consistent regarding how character escapes in JSX work. IMO it would be unfortunate if TypeScript's behavior started diverging from all other JSX processing tools in this case.

**Comment by jakebailey** [comment]
You're totally right; I was thinking that it was incongruent with backticks until I realized that the backtick example was within `{}`, and `{"\u2000"}` does in fact preserve the escape.
