### ISSUE TITLE
jQuery type definitions are automatically included

### ISSUE THREAD

**Issue by Zyphrax** [Microsoft/TypeScript#22016]
**TypeScript Version:**  2.7.2

**Search Terms:** types,jquery,implicit,import

**Code**

test.ts
```ts
$("body").html("Hello");
```

tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "es6",
    "moduleResolution": "node",

    "sourceMap": true,
    "noEmit": true,
    "typeRoots": [],
    "types": [],

    "allowSyntheticDefaultImports": true,
    "allowUnusedLabels": true,
    "strictNullChecks": true
  },
  "compileOnSave": false,
  "typeAcquisition": {
    "enable": false,
  },
  "include": [
    "app/assets/javascripts"
  ]
```

**Expected behavior:**
$ and jQuery should be undefined.

I expect to have to import `$`:
```ts
import $ from "jquery";
```

**Actual behavior:**
The TypeScript compiler magically knows what $ and jQuery are without importing the types.

I don't want these types to be imported implicitly, that's why I'm setting `types` and `typesRoots`. But somehow the compiler does know what they are.

I've tried disabling this behavior in all kinds of ways, but I can't seem to fix it.

My package.json (I've removed a few irrelevant dependencies):
```json
{
  "private": true,
  "dependencies": {
    "@rails/webpacker": "^3.2.2",
    "jquery": "^2.2.4",
    "jquery-ui": "^1.12.1",
    "jquery-ujs": "^1.2.2",
  },
  "devDependencies": {
    "@types/jquery": "^2.0.48",
    "@types/jqueryui": "^1.12.2",
    "ts-loader": "^3.5.0",
    "typescript": "^2.7.2",
    "webpack": "^3.11.0",
    "webpack-dev-server": "^2.11.1"
  }
}
```

I'm using the latest Visual Studio Code. My `.vscode/settings.json` instructs to use the bundled TypeScript version: `{ "typescript.tsdk": "node_modules/typescript/lib" }`

**Comment by zspitz** [comment]
Is this a VS Code issue? If you run the compiler from the command line, does it compile successfully?

    tsc -p tsconfig.json

**Comment by Zyphrax** [comment]
This is a TypeScript compiler issue.

It is compiling successfully but I want the compiler to fail if I don't do the proper jQuery import. The code shouldn't magically assume that jQuery is defined, I want it to be explicitly imported (like the other libraries I'm using).

1. I have `typeRoots` set to an empty array
2. I have `types` set to an empty array
3. I'm not importing from "jquery" anywhere

To my knowledge the compiler shouldn't be able to resolve `jQuery` or `$`.

Eventually I want to remove jQuery from my project, so I would like to keep track where jQuery is being used.

**Comment by Zyphrax** [comment]
I've created a small test application. It seems if I import jQuery in file A.ts, then it is also automatically available in file B.ts. Is that normal behavior?

**Comment by yortus** [comment]
@Zyphrax it's not a compiler problem, it's the way the types in `jquery.d.ts` are currently declared. The jquery typings include:

```ts
declare const jQuery: JQueryStatic;
declare const $: JQueryStatic;
```

These tell the TypeScript compiler that `$` and `jQuery` are global variables. Once `jquery.d.ts` is included in the project's dependency graph, every file will 'see' `$` and `jQuery` as globals.

It looks like `jquery.d.ts` is written the old way and needs some updating - it should `export` its types and values, instead of `declaring` them. But then that might break other people's code. I'm not a jquery user so I'm not sure what the best way forward is. But hopefully this at least sheds light on the problem you are seeing.

Looks like other people are also wanting to know how to do this: #12473.

**Comment by weswigham** [comment]
Ideally it'd be written as a module and use `export as namespace $; export as namespace jQuery;` to make it available as a global in global contexts. But there's an issue: for real, jquery _always_ patches itself onto the global scope. Like, unless you have a special build of jquery that's removed the global patching behavior, once it's run once, there _will_ be a global `$` and a global `jQuery`.

**Comment by Zyphrax** [comment]
Ah I see, thank you. I'm a bit confused though why you would ever want a global to apply to all .ts files. When I import something in file X, I expect it to only affect the file I'm importing it in. Someone adding a class in the project could potentially change the way the rest of the project works, that sounds a bit scary.

**Comment by weswigham** [comment]
Yep, and it's not a recommended way to build a package, for sure, but that's actually how jQuery works.

**Comment by Zyphrax** [comment]
Would it perhaps be possible to have a compiler option to limit the scope of these globals? Or would that be a lot of work. 

For now I might have a look at this: https://www.npmjs.com/package/jquery-ts

**Comment by weswigham** [comment]
It looks like (?) that package will still put the jQuery stuff in the globals, looking at it's source - it just doesn't report that in its type definitions. I'd personally not trust it, since if you accidentally include two conflicting jQuery versions, nothing will complain (when it probably should, since one will overwrite the other). The optimal solution is a custom jQuery build with `exports/globals` excluded and a modified definition file to remove the global declarations, I just don't know how feasible that'd be for you.
