### ISSUE TITLE
Incorrect declaration file emit for recursive type

### ISSUE THREAD

**Issue by phiresky** [Microsoft/TypeScript#22192]
I'm having an issue where using the code directly works fine, but using the compiled code together with the emitted declaration file does not work.

**TypeScript Version:**  2.4.2, 2.5.3, 2.6.2, 2.7.2, 2.8.0-dev.20180224

**Search Terms:** recursive declaration

**Code**

```ts
export type RecordTypeToJson<
    T extends { _brand: string; _recordType: { [name: string]: any } }
> = ({
    record: { [TName in keyof T["_recordType"]]: RecordTypeToJson<T["_recordType"][TName]> };
} & { [other: string]: any })[T["_brand"]];
export interface Record<T> {
    _brand: "record";
    _recordType: T;
}
export type Smth<T> = any;
export abstract class Expression {
    toJson<TColumns>(this: Smth<TColumns>): RecordTypeToJson<Record<TColumns>> {
        return null!;
    }
}

export function test() {
    return class extends Expression {};
}
```

**Expected behavior:** Declaration file output:

```ts
export declare type RecordTypeToJson<T extends {
    _brand: string;
    _recordType: {
        [name: string]: any;
    };
}> = ({
    record: {
        [TName in keyof T["_recordType"]]: RecordTypeToJson<T["_recordType"][TName]>;
    };
} & {
    [other: string]: any;
})[T["_brand"]];
export interface Record<T> {
    _brand: "record";
    _recordType: T;
}
export declare type Smth<T> = any;
export declare abstract class Expression {
    toJson<TColumns>(this: Smth<TColumns>): RecordTypeToJson<Record<TColumns>>;
}


export declare function test(): {
    new (): {
        toJson<TColumns>(this: any): RecordTypeToJson<Record<TColumns>>;
    };
};
```

**Actual behavior:** test function is wrong:

```ts
[...]

export declare function test(): {
    new (): {
        toJson<TColumns>(this: any): { [TName in keyof TColumns]: ({
            record: any;
        } & {
            [other: string]: any;
        })[TColumns[TName]["_brand"]]; };
    };
};
```

Which throws error:

```
[ts] Type 'TColumns[TName]["_brand"]' cannot be used to index type '{ record: any; } & { [other: string]: any; }'.
```

**Playground Link:** Not useful since playground does not show declaration file output

**Related Issues:** idk, couldn't find anything

**Comment by weswigham** [comment]
@DanielRosenwasser This is just a complex way of exposing our current behavior for recursive type aliases, simplified:
```ts
type A<T extends {fake: string, real: any}> = ({
    a: A<T["real"]>
} & { [index: string]: any })[T["fake"]]; // Somehow not circular, thanks to the delay caused by the index, yet not an error, thanks to the index signature

// type Q = A<{ fake: "a", real: Q /*any circularly referential type will do*/}>; // clearly circular; uncomment, causes alias above to be marked circular, in addition to itself
```

Except in this case, instead of instantiating a type alias, which causes us to emit the circularity error, we encounter the issue while instantiating _a class_ (instead of an alias), so there's no circularity stack and we just print `any` when the type circulates. The circular type has some interesting constraints placed on its by its structure that aren't preserved when we attempt to reprint it this way, causing the error. We can't print it like the OP indicates because that'd require not eagerly evaluating the top level of the `RecordTypeToJson` type into its resulting `record` mapped-type (and also having an alias symbol on the top level indexed access).
