### ISSUE TITLE
Unexpected type when using conditional map types

### ISSUE THREAD

**Issue by bterlson** [Microsoft/TypeScript#22302]
**TypeScript Version:** 2.8.0-dev.20180301

**Search Terms:** 
Unexpected type, conditional map type

**Code**
```ts
type MatchingKeys<Record, Include, K extends keyof Record = keyof Record> =
  K extends keyof Record
    ? Record[K] extends Include
      ? K
      : never
    : never;

type VoidKeys<Record> = MatchingKeys<Record, void>;
interface test {
  a: 1,
  b: void
}

// works
type t1 = MatchingKeys<test, void>;
  
// doesn't work????
type t2 = VoidKeys<test>
```

**Expected behavior:**
I expect t1 and t2 to be identical types.

**Actual behavior:**
t1 and t2 are different types (and t2's type is confusing)

**Comment by mhegazy** [comment]
There are two issues here. the first that `t1` and `t2` are expected to behave differently.. since `t1` is a distributive type, and `t2` is not (since t2 is actually `keyof test extends keyof test ? ....` which then collabses to true, to `T[k] extends U ? ...` which is not distributive). 

After discussion offline with @ahejlsberg and @DanielRosenwasser we can just defer distributive types iff their condition is generic.

The second issue is that the type `t2` is not collapsing.. this seems like a bug.

**Comment by mhegazy** [comment]
@bterlson here is two other ways to write the same map function you want:

```ts
type MK<T, U> = { [P in keyof T]: T[P] extends U ? P : never }[keyof T];

type MK2<T, U, K extends keyof T> =
    K extends (T[K] extends U ? K : never) ? K : never;
```
