### ISSUE TITLE
Trailing comments shouldn't be kept when refactoring multiple statements

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#22399]
```ts
function foo() {
    let x = 10;

    [|x **= 2; // square
    x **= 2; // square again|]
}
```

Extract function on range

**Expected:**

```ts

function foo() {
    let x = 10;

    asd();


    function asd() {
        x **= 2; // square
        x **= 2; // square again
    }
}
```

**Actual:**

```ts
function foo() {
    let x = 10;

    asd(); // square again


    function asd() {
        x **= 2; // square
        x **= 2;
    }
}
```

**Comment by amcasey** [comment]
@DanielRosenwasser, I'm not sure I understand what you're looking for.  I think you're suggesting that extracting `[|foo(); //comment|]` should behave differently from extracting `[|foo();|] //comment`, which - I agree - would be nice.  However, since no comments were either lost or duplicated, I would probably consider this a suggestion, rather than a bug.  How high is this on your list of priorities?

**Comment by DanielRosenwasser** [comment]
Nope, sorry, the key thing I have in mind here is that when I have multiple statements in a refactoring, it makes sense to move trailing trivia of the last statement *into* the extracted function body.

**Comment by RyanCavanaugh** [comment]
Now we duplicate the comment
```ts
function foo() {
    let x = 10;

    x = newFunction(x); // square again
}

function newFunction(x: number) {
    x **= 2; // square
    x **= 2; // square again
    return x;
}
```
It's maybe not obvious which location is better, so letting the user delete whichever they don't like seems like a decent approach. Let's call it good enough.
