### ISSUE TITLE
noImplicitAny produces 'any' inference for a type with boolean param

### ISSUE THREAD

**Issue by ilhamwk** [microsoft/TypeScript#22428]
**TypeScript Version:**  2.8.0-dev.20180308

**Search Terms:** 
label:bug is:open noimplicitAny new inference boolean

**Code**

Below are two snippets where the same problem is observed with noImplicitAny option enabled. The first snippet uses a direct boolean type, where as the second one uses generics that behave like a boolean. I suppose the problem here is the circular type inference.

***Snippet 1***
```ts
class B {
  readonly c: boolean;
  constructor(a: T) {
  }
}

let x = true;
for (let y = 0; y < 10; y++) {
  const b = new B(x);
  x = b.c;
}
```

***Snippet 2***
```ts
class B<T extends true|false> {
  readonly c: T;
  constructor(a: T) {
  }
}

// Parameter influences type
let b1 = new B(true); // B<true>
let b2 = new B(Math.random() > .5); // B<boolean>

let x = true;
for (let y = 0; y < 10; y++) {
  // x's type might have been narrowed by assignment
  // so we should check for assignments. But one of them
  // is *based* on the type of b, so we can't deduce the
  // proper type for b.

  // Uncomment this line to see the narrowing in action;
  // x is temporarily of type false instead of boolean.
  // x = false;

  const b = new B(x);
  x = b.c;
}
```

**Expected behavior:**
'b' should be typed by B.

**Actual behavior:**
The compiler complains:
```
'b' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
```

**Playground Link:**  

Snippet 1: https://www.typescriptlang.org/play/#src=class%20B%20%7B%0D%0A%20%20readonly%20c%20%3A%20boolean%3B%0D%0A%20%20constructor(a%3A%20boolean)%20%7B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Alet%20x%20%3D%20true%3B%0D%0Afor%20(let%20y%20%3D%200%3B%20y%20%3C%2010%3B%20y%2B%2B)%20%7B%0D%0A%20%20const%20b%20%3D%20new%20B(x)%3B%0D%0A%20%20x%20%3D%20b.c%3B%0D%0A%7D%0D%0A%0D%0A

Snippet 2: https://www.typescriptlang.org/play/#src=class%20B%3CT%20extends%20true%7Cfalse%3E%20%7B%0D%0A%20%20readonly%20c%3A%20T%3B%0D%0A%20%20constructor(a%3A%20T)%20%7B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Parameter%20influences%20type%0D%0Alet%20b1%20%3D%20new%20B(true)%3B%20%2F%2F%20B%3Ctrue%3E%0D%0Alet%20b2%20%3D%20new%20B(Math.random()%20%3E%20.5)%3B%20%2F%2F%20B%3Cboolean%3E%0D%0A%0D%0Alet%20x%20%3D%20true%3B%0D%0Afor%20(let%20y%20%3D%200%3B%20y%20%3C%2010%3B%20y%2B%2B)%20%7B%0D%0A%20%20%2F%2F%20x's%20type%20might%20have%20been%20narrowed%20by%20assignment%0D%0A%20%20%2F%2F%20so%20we%20should%20check%20for%20assignments.%20But%20one%20of%20them%0D%0A%20%20%2F%2F%20is%20*based*%20on%20the%20type%20of%20b%2C%20so%20we%20can't%20deduce%20the%0D%0A%20%20%2F%2F%20proper%20type%20for%20b.%0D%0A%0D%0A%20%20%2F%2F%20Uncomment%20this%20line%20to%20see%20the%20narrowing%20in%20action%3B%0D%0A%20%20%2F%2F%20x%20is%20temporarily%20of%20type%20false%20instead%20of%20boolean.%0D%0A%20%20%2F%2F%20x%20%3D%20false%3B%0D%0A%0D%0A%20%20const%20b%20%3D%20new%20B(x)%3B%0D%0A%20%20x%20%3D%20b.c%3B%0D%0A%7D%0D%0A

**Related Issues:**
I don't know, I didn't find any issue that looks close enough.

**Comment by andy-ms** [comment]
This has nothing to do with generics or booleans -- it's just the behavior of control flow analysis in a loop. E.g.:
```ts
let x = true;
for (const em of ["some", "array"]) {
    const b = x;
    x = b;
}
```
The type of `b` depends on the type of `x`, which depends on the type of `b`, so there's an error at `b` that we can't infer its type.

**Comment by agopshi** [comment]
> This has nothing to do with generics or booleans

I don't think this is true. Changing `x` in your example to `123` or `'foo'` compiles without an error:

```
let x = 123;  // x: number
for (const em of ["some", "array"]) {
    const b = x;  // b: number
    x = b;  // x: number
}
```
[Playground](https://www.typescriptlang.org/play/#src=class%20B%3CT%20extends%20true%7Cfalse%3E%20%7B%0D%0A%20%20readonly%20c%3A%20T%3B%0D%0A%20%20constructor(a%3A%20T)%20%7B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Parameter%20influences%20type%0D%0Alet%20b1%20%3D%20new%20B(true)%3B%20%2F%2F%20B%3Ctrue%3E%0D%0Alet%20b2%20%3D%20new%20B(Math.random()%20%3E%20.5)%3B%20%2F%2F%20B%3Cboolean%3E%0D%0A%0D%0Alet%20x%20%3D%20true%3B%0D%0Afor%20(let%20y%20%3D%200%3B%20y%20%3C%2010%3B%20y%2B%2B)%20%7B%0D%0A%20%20%2F%2F%20x's%20type%20might%20have%20been%20narrowed%20by%20assignment%0D%0A%20%20%2F%2F%20so%20we%20should%20check%20for%20assignments.%20But%20one%20of%20them%0D%0A%20%20%2F%2F%20is%20*based*%20on%20the%20type%20of%20b%2C%20so%20we%20can't%20deduce%20the%0D%0A%20%20%2F%2F%20proper%20type%20for%20b.%0D%0A%0D%0A%20%20%2F%2F%20Uncomment%20this%20line%20to%20see%20the%20narrowing%20in%20action%3B%0D%0A%20%20%2F%2F%20x%20is%20temporarily%20of%20type%20false%20instead%20of%20boolean.%0D%0A%20%20%2F%2F%20x%20%3D%20false%3B%0D%0A%0D%0A%20%20const%20b%20%3D%20new%20B(x)%3B%0D%0A%20%20x%20%3D%20b.c%3B%0D%0A%7D%0D%0A)

In your example, `x` is inferred to be `true` instead of `boolean`, which seems incorrect as we used `let`, not `const`. Thoughts?

**Comment by andy-ms** [comment]
The difference is thath `boolean` is union `true | false` and so is subject to being narrowed based on control flow. The compiler doesn't try to narrow `number` or `string`, so it doesn't run into any trouble. You also get the error with `enum E { A, B }; let x = E.A;` or any other union.

**Comment by agopshi** [comment]
I don't understand why that's a problem, though. It seems that falling back to `any` is an escape hatch. Why don't we instead fall back to the widened union type? This would be similar to how types are widened in callbacks that cannot be proven to be synchronous.

**Comment by andy-ms** [comment]
Talked with @sandersn and there might (or might not) be a possibility to improve the behavior here.

**Comment by RyanCavanaugh** [comment]
I don't see anything unusual here; circular inference causing an implicit any has been our behavior since v1. There have been requests to try to muddle through it but I think in practice that would often make things more confusing, since it'd be a silent degradation.
