### ISSUE TITLE
`#region` not always folding

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#22440]
```ts
// #region label1
var x;
// #endregion label1 
```

Actual:

![image](https://user-images.githubusercontent.com/8000722/37219274-c8df68d8-2377-11e8-901b-640d7f0c5c68.png)

Note: I got these from `tests\cases\fourslash\getOutliningSpansForRegions.ts`, so seems like the test is not testing the right thing.

**Comment by uniqueiniquity** [comment]
@mhegazy When stepping through the test, it is actually testing the right thing. Seems that the regex match works in mocha but not otherwise. I can easily fix the issue in general, but am concerned that we don't know what changed. (@DanielRosenwasser)

**Comment by mhegazy** [comment]
not sure i follow.. so the test is working correctly? if so why is it failing for VS/VSCode?

**Comment by uniqueiniquity** [comment]
There seems to be a difference in the way line endings are handled in mocha and otherwise. When attaching a debugger to tsserver, I can see that the regex is failing on the string "// #region label1\r", which is clearly my mistake, I should have handled line endings better. But when attaching a debugger to the mocha test, it reads the string as "// #region label1" and passes fine.
