### ISSUE TITLE
SVG ElementNS missing property "ns"

### ISSUE THREAD

**Issue by ghost** [Microsoft/TypeScript#22465]
The type `SVGSVGElement` does not have the property `ns`.
`Property 'ns' does not exist on type '

```ts
let svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
svg.ns = svg.namespaceURI;
```

How to fix it?
Just add the property `ns` to the type `SVGSVGElement`. The type is `string`.
This property is important to work with svg.

```ts
interface SVGSVGElement extends SVGGraphicsElement, DocumentEvent, SVGFitToViewBox, SVGZoomAndPan {
    ns: string;
}
```

TypeScript: 2.7.2

**Comment by Dakode** [comment]
```ts
interface SVGSVGElement extends SVGGraphicsElement, DocumentEvent, SVGFitToViewBox, SVGZoomAndPan {
    ns: string;
}
```

**Comment by Dakode** [comment]
Workaround: 
Create a new custom type extends SVGSVGElement with ns.
```ts
interface SVGSVGElementNS extends SVGSVGElement {
  ns: string;
}
//...
this.svg = <SVGSVGElementNS>document.createElementNS("http://www.w3.org/2000/svg", "svg");
this.svg.ns = this.svg.namespaceURI;
```

**Comment by Domvel** [comment]
The `ns` property does not exist on specs. For example [here](https://developer.mozilla.org/en-US/docs/Web/API/SVGSVGElement) But I know the problem. The `ns` does exist on this element and is important to use NS SVG Element. Otherwise the svg will not displayed. It's just hidden. 
Maybe this property was inherited. But whatever ... this should be fixed. But I have no idea where. 

Maybe here https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L11645?

**Comment by domske** [comment]
I think `ns` is just an user-defined property, a shortcut for `namespaceURI`. I'm sure.
Perhaps the `ns` property comes from a javascript example. This is not a property of `SVGSVGElement`.
Check out this demonstration: https://stackblitz.com/edit/typescript-4ru3wq
Just use the `namespaceURI` to create path elements in svg. Otherwise the pathes are hidden.
-> Close

**Comment by RyanCavanaugh** [comment]
👻
