### ISSUE TITLE
Codefix: convert const to let 

### ISSUE THREAD

**Issue by jwbay** [microsoft/TypeScript#22473]
**TypeScript Version:**  2.8.0-dev.20180308

**Search Terms:**
const let codefix

**Code**
```ts
const x = 42;

// lots of code

x/*1*/ = 75;
```

**Expected behavior:**
Error with codefix offered at 1 to convert the declaration from `const` to `let`

**Actual behavior:**
Just an error, no codefix

**Related Issues:**
The exact opposite of #13133

**Comment by MagWeaver** [comment]
Can I take this one?

**Comment by DanielRosenwasser** [comment]
Go for it!

**Comment by RubenMateus** [comment]
@MagWeaver any news from this?

**Comment by Fatehsandhu** [comment]
@DanielRosenwasser Can I please take over if it's possible?
Thanks

**Comment by mhegazy** [comment]
Go for it.

**Comment by Fatehsandhu** [comment]
@mhegazy Can I please get some help getting started? Which files should I be looking at?
Thanks

**Comment by mhegazy** [comment]
Quick fixes are attached to diagnostics. in this case `TS Error 2540: Cannot assign to 'x' because it is a constant or a read-only property.`

You can take a look at https://github.com/Microsoft/TypeScript/blob/master/src/services/codefixes/fixAwaitInSyncFunction.ts and https://github.com/Microsoft/TypeScript/blob/master/src/services/codefixes/fixSpelling.ts for a guide to how a quick fix can be implemented.

Also you will need to add handling for the `readonly` property case, where the `readonly` modifier would be removed.

**Comment by muradkhan101** [comment]
@Fatehsandhu Still working on this? If not I'd like to take a shot at it :)

**Comment by muradkhan101** [comment]
Hey @mhegazy, I have a potential fix for this [here](https://github.com/muradkhan101/TypeScript/commit/aea4216a23e2f05ee6fe556539c15415efa7e4e9) , but I couldn't find solid diagnostic messages to use and haven't figured out the readonly case yet though. Just wanted to check in with you to get some info about creating diagnostic messages and see if I'm on the right track here, thanks!

**Comment by muradkhan101** [comment]
@suhailsinghbains I'm currently working on this one and am close to completing so your time may be better spent on another one. I'll let you know if anything changes however.

**Comment by suhailsinghbains** [comment]
Sure @muradkhan101
