### ISSUE TITLE
NodeJS:   new http.Server().listen() method has incorrect interface

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#22528]
I have this code:

```js
const port = process.env.OPENSHIFT_NODEJS_PORT || 3040;
const host = process.env.OPENSHIFT_NODEJS_IP;
const server = http.createServer(app).listen(port, host);
```

I am getting this TS transpilation error:

![screenshot 2018-03-13 17 08 01](https://user-images.githubusercontent.com/11139560/37376409-5dda9a40-26e1-11e8-8e57-ce3f0febe253.png)

Looks like the interface for listen() is:

`
server.listen(port, [host], [backlog], [callback])
`

which can be witnessed here:
https://nodejs.org/api/net.html#net_server_listen_port_host_backlog_callback

seems like a typings bug

**Comment by Bibliofile** [comment]
This is caused by the type of `port`. `port` is defined as `string | number`. If you take a look at the [typings](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/index.d.ts#L2731-L2739) you will notice that there are only two overloads that match the type `string | number` for the first argument.

```ts
listen(handle: any, backlog?: number, listeningListener?: Function): this;
listen(handle: any, listeningListener?: Function): this;
```

With this knowledge, I believe it's obvious why this doesn't work. There isn't a bug in the typings in this case.

Change your definition of port to `+process.env.OPENSHIFT_NODEJS_PORT || 3040` and the type inference you expect will occur.

**Comment by ORESoftware** [comment]
@Bibliofile thanks what is that + notation/syntax? never seen that before

**Comment by Bibliofile** [comment]
`+` can be used to convert a variable to a string - take a look at the [mdn docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators#Unary_plus_())
