### ISSUE TITLE
Breaking change interpreting lowdb types

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#22603]
**TypeScript Version:**  2.8.0-dev.20180307 (works as expected in 2.8.0-dev.20180302)

**Code**

```ts
type False = "0";
type True = "1";
type Bool = True | False;
type If<Cond extends Bool, Then, Else> = { 1: Then; 0: Else }[Cond];

type Obj<T> = { [k: string]: T };
type UnionHasKey<Union extends string, K extends string> = ({ [S in Union]: "1" } & Obj<"0">)[K];

type ReferenceProperty = "@@reference";
type HasReferenceProperty<T> = UnionHasKey<keyof T, ReferenceProperty>;
type NonNull<T> = T & {};
type GetReferenceParent<T> = NonNull<T[keyof T & ReferenceProperty]>;

type GetDefinedReferenceType<TValue, SourceParent = GetReferenceParent<TValue>> = SourceParent[keyof SourceParent & ReferenceProperty];
type GetReferenceTypeIfDefined<T> = If<HasReferenceProperty<T>, GetDefinedReferenceType<T>, T>;
type SourceReference<T> = { readonly "@@reference"?: { readonly "@@reference": T } };

type T = GetReferenceTypeIfDefined<number & SourceReference<number>>; // Should be `number`
const x: T = ""; // Should fail
```

**Expected behavior:**

Error -- T is `number`

**Actual behavior:**

No error.

The example is based on `lowdb` on DefinitelyTyped.

**Comment by andy-ms** [comment]
Worked with @sandersn to get a simpler repro:
```ts
type GetAt<T> = T[keyof T & "@@@"] & {};
type GetAtAt<U> = GetAt<GetAt<U>>;
type V = GetAtAt<{ readonly "@@@"?: { readonly "@@@"?: number } }>; // Should be `number`
const x: V = ""; // Should fail
```

There is an error in `2.7` but not `typescript@next`. Removing the first `?` in `type V` makes it correctly have an error in both versions.

**Comment by sandersn** [comment]
From our offline discussion: this may be by design because `T[keyof T & "@@@"]` behaves like the conditional `T extends { "@@@" } ? T["@@@"] : any`. 

`?` introduces `undefined` into the type, so the type of the object literal is

```ts
{ "@@@": { "@@@": number | undefined } | undefined }
``` 

That means that
```ts
GetAt<{ "@@@": { "@@@": number | undefined } | undefined }>
``` 

is `{ "@@@": number | undefined } | undefined`. The second call to `GetAt` then looks like this:

```ts
GetAt<{ "@@@": number | undefined} | undefined>
```

And of course `undefined` doesn't have any keys (particularly, "@@@"), so `keyof T` is never, `keyof T & "@@@"` is never, and `T[never]` is any.
