### ISSUE TITLE
Microsoft.TypeScript@2.8 not yet on nuget.org

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/TypeScript#22625]
Pinging @paulvanbrenk from #19179?

Can this be added to the RC release please? I'd love to test RCs out on MSBuild projects as they're released.

**Comment by JoshuaKGoldberg** [comment]
Well this is interesting - https://www.nuget.org/packages/Microsoft.TypeScript.MSBuild/2.8.0 is unlisted. :)

**Comment by DanielRosenwasser** [comment]
I'm pretty sure we only list the stables; RCs (e.g. 2.7.0) aren't there though as you'll notice.

**Comment by JoshuaKGoldberg** [comment]
Is there a reason? Nuget allows for beta tagged versions for this reason. It's been useful before for catching flags not her added to the MSBuild logic.

**Comment by paulvanbrenk** [comment]
We definitely unlist beta/rc releases after releasing the final version. I think we used to list the preview bits with a preview flag on Nuget, but I think that was always a manual step. I'll figure out how to automate that, since we now sign our NuGet packages and I don't think we can change the version post signing.
