### ISSUE TITLE
How do I detect if an AST node is a const declaration?

### ISSUE THREAD

**Issue by kristianmandrup** [Microsoft/TypeScript#22681]
Been looking both in the ASTExplorer and the AST generated in the SourceFile via `createSourceFile` and I can see no mention of anything indicating if a `VariableDeclaration` is a `const`. 

Also looked into the `typescript.ts` source and type declarations, with no luck.

Now in desperation, turning to `typescript-eslint-parser` which has a much clearer AST with all the info I need. What am I missing!? Thanks.

**Comment by ajafff** [comment]
That information is not stored in the `VariableDeclartion` but on the `VariableDeclarationList` (typically the parent of the `VariableDeclaration`) as a flag: `variableDeclarationList.flags & ts.NodeFlags.Const` is truthy if this is a const declaration. There's also `ts.NodeFlags.Let` for `let` and if none of the two is set, it's a `var` declaration.

The information not being located on the declaration actually makes sense, because the declaration could also be a catch binding, which has no `var`/`let`/`const` keyword:
```ts
try {
} catch(e /* <- this is also a VariableDeclaration */) {
}
```

**Comment by RyanCavanaugh** [comment]
Thanks for the good answer @ajafff

**Comment by kristianmandrup** [comment]
Thanks for the answer. After further investigation, I guess you could also just do `ts.isConst(node)` ?? There are so many of these buil in node type checkers in the root namespace, that for some reason, VSC didn't display that function `isConst` for me in the assist.

**Comment by ajafff** [comment]
> for some reason, VSC didn't display that function isConst for me in the assist.

That's because they are marked `@internal` and are not intended to be used outside of the TypeScript codebase.

**Comment by ajafff** [comment]
Btw.: I have a lot of utility functions like `getVariableDeclarationKind` in my package `tsutils`.
