### ISSUE TITLE
Assign Enums to Enums?

### ISSUE THREAD

**Issue by milewski** [microsoft/TypeScript#22781]
Im a bit confuse why the following doesn't work:

```ts
export enum Languages {
    English = 'en',
    Chinese = 'zh-cn'
}

export enum Defaults {
    Language = Languages.English,
}
```

```ts
const language: Languages = Defaults.Language

///(48,9): Type 'Defaults' is not assignable to type 'Languages'.
```

is there another way of archiving the same in typescript?

**Comment by DanielRosenwasser** [comment]
It's a little hard for me to imagine a lot of scenarios for this apart from the 'defaults' one you provided.

Typically we only track the original literal values within an enum. I guess we could imagine enum members keeping track of other enum member values, though it seems strange and of limited value in my opinion.

You could instead just declare a const for each default, since I'd imagine your default data might be heterogeneous down the line anyway, and enums currently only handle strings and numbers.

**Comment by RyanCavanaugh** [comment]
@DanielRosenwasser what is the proposal?

**Comment by RyanCavanaugh** [comment]
These get different brands; this is the intended behavior.
