### ISSUE TITLE
Do not Enable JavaScript language service by Default (after upgrade)

### ISSUE THREAD

**Issue by TsunamiJohn** [Microsoft/TypeScript#22795]
Please do not enable the JavaScript language service by default.  And, please do not re-enable it every time VS 2017 is updated.  This service is VERY slow.  My team cannot bear the productivity loss required to have this enabled.  We see no loss of functionality with the service disabled, and VS 2017 performance is so poor with it enabled, that it becomes unusable.  

It is annoying and bothersome that VS 2017 is updating once or twice a week now.  It is even more annoying that after each update, VS 2017 becomes unusable because of terrible performance.  After a few hours, we remember that we have to re-disable the JS language service after each update.

Let this service die a slow death so we can get back to work.

John Loper

**Comment by mhegazy** [comment]
We are sorry @TsunamiJohn that you are running into issues with the language service. we would love to look into the performance issues you are having and try to address them. can you share more details.

**Comment by TsunamiJohn** [comment]
The answer is simple.  Every time I install an update, the JavaScript service is re-enabled.  I notice it because when I am debugging JS files, i have to wait 2 or 3 seconds every time I move my mouse and there is a popup message indicating that VS is fetching the help text, etc.  I can’t use VS with this feature enabled.

Everything works just fine with it off.  VS is unusable with it turned on.

STOP TURNING IT ON EVERY TIME I UPDATE VS!

Thanks,


John P. Loper Sr.
Main:   740-824-5780
Fax:    888-552-4901        
Email:  mailto:jloper@L <mailto:john.loper@tsunamisoftware.biz>opers.Org [Personal]

**Comment by billti** [comment]
The setting you are referring to, if it's the one I think, doesn't disable **_any_** JavaScript language service, it just uses the old one instead of the new. We left the old one as a fall back if needed when the new one was brand new and we expected some early issues. The old one however, will be going away entirely at some point in the near future. It is unmaintained and doesn't support the latest JavaScript language features.

With every update we are fixing numerous issues in the new language service that may have caused users to switch it off. With that (and the above) in mind, we decided not to fix the bug where the new language service is re-enabled on every update. We need to see the number of users who still hit issues and have to go back to the old one (which takes a few seconds in Tools / Options), to know when the usage is low enough that we can remove it. (Else the number of users who have just "set it and forget it" and never try the new one again will keep the numbers inflated).

We have considered a switch to just disable any language service operations for those that would prefer that perf boost over *any* language service operations at all. Bear in mind that then you will effectively have a colorized text editor - with no formatting, brace matching, intellisense, etc. Let me know if that would be a useful option for you.

In general however, by far my biggest preference, would be for you to help me understand why the new language service is so painful for you. I absolutely want to work with you until we have this figured out and you are very happy with experience. The vast majority of users are not switching off the new language service, so there is something specific about your environment or project causing problems that we haven't seen internally. Feel free to reach out to me directly (my alias on GitHub, but at microsoft.com), and I'll work with you until we have it figured out and fixed. (We already have a significant improvement in the architecture under development internally I'd love for you to try).

Sorry for the inconvenience.

**Comment by billti** [comment]
This should have been fixed for a while now. Closing.
