### ISSUE TITLE
WebGL type annotations are inconsistent and cause compile errors when used

### ISSUE THREAD

**Issue by evanw** [Microsoft/TypeScript#22859]
It looks like whoever added `| null` to some of the type declarations missed a lot of them. I'm guessing every type with a `?` at the end in [the spec](https://www.khronos.org/registry/webgl/specs/latest/1.0/webgl.idl) should have `| null`.

**TypeScript Version:**  2.6.2

**Search Terms:** WebGL uniform location null WebGLUniformLocation

**Code**

```ts
function foo(gl: WebGLRenderingContext, program: WebGLProgram) {
  let location = gl.getUniformLocation(program, 'example');
  gl.uniformMatrix2fv(location, false, []);
}
```

**Expected behavior:**
The code compiles correctly.

**Actual behavior:**
```
temp.ts(3,23): error TS2345: Argument of type 'WebGLUniformLocation | null' is not assignable to parameter of type 'WebGLUniformLocation'.
  Type 'null' is not assignable to type 'WebGLUniformLocation'.
```

**Playground Link:**  
https://www.typescriptlang.org/play/index.html#src=function%20foo(gl%3A%20WebGLRenderingContext%2C%20program%3A%20WebGLProgram)%20%7B%0D%0A%20%20let%20location%20%3D%20gl.getUniformLocation(program%2C%20'example')%3B%0D%0A%20%20gl.uniformMatrix2fv(location%2C%20false%2C%20%5B%5D)%3B%0D%0A%7D%0D%0A

**Related Issues:**

**Comment by mhegazy** [comment]
Looking at the [spec](https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.14.10), and [MDN](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/getUniformLocation#Return_value), the function can return `null` if the `name` does not exist.

**Comment by RyanCavanaugh** [comment]
@evanw we'd take a PR on the `uniform*` definitions

**Comment by mhegazy** [comment]
You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by huy-nguyen** [comment]
@mhegazy I can make a PR.

**Comment by andrewvarga** [comment]
This is related to WebGL type annotations, but a slightly different issue (let me know if I should open a new thread):

In lib.d.ts (TS 2.8.1) all the interfaces of WebGL objects like WebGLBuffer, WebGLTexture are empty, and so because of structural (duck) typing, this code compiles without a problem:

```
let texture: WebGLTexture;
let buffer: WebGLBuffer = texture;
```

An external typing file I used for WebGL types solves this by adding dummyprops to these interfaces, which is a little hacky but works:
https://github.com/asgerf/dartify/blob/master/testcases/pixi/webgl.d.ts

I know this is intended behaviour for TypeScript but I wondering if there is a better way to enforce type safety in situations like in the code snippet above?
