### ISSUE TITLE
exports is not defined error in typescript version 2.7

### ISSUE THREAD

**Issue by priyankag1403** [Microsoft/TypeScript#22879]
I am getting exports is not defined error while running a simple typescript project in typescript version 2.7
Is it an open issue?

My tsconfig.json is default which looks like :  {
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": false,
        "sourceMap": false
    },
    "exclude": [
        "node_modules"
    ]
}

**Comment by andy-ms** [comment]
Please provide a code sample.

**Comment by priyankag1403** [comment]
See attached code source where i am try to export one component and using in another component..its a normal typescript project running on lite-server using npm.
[typescript-projects.zip](https://github.com/Microsoft/TypeScript/files/1848439/typescript-projects.zip)

**Comment by andy-ms** [comment]
The problem is that you compiled with `"module": "commonjs"` and then tried running the code in a browser, which doesn't support commonjs. You might want to try targeting ES6 modules (although I couldn't tell you how to get it to work in a browser) or use a tool to bundle modules into a single script, such as rollup or webpack.
