### ISSUE TITLE
typeArgument of JsxOpeningLikeElement ignored while checking JsxAttributes

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#22874]
**TypeScript Version:**  2.9.0-dev.20180328

**Search Terms:** jsx generic type arguments

**Code**

```ts
export {};

declare namespace JSX {
    interface Element {
        render(): Element | string | false;
    }
}

function SFC<T>(props: Record<string, T>) {
    return '';
}

/*1*/<SFC<string> prop={1}></SFC>;
```

**Expected behavior:**

Error on the `prop` attribute, because number is not assignable to string.

**Actual behavior:**

No error. Signature help incorrectly shows `function SFC<number>(props: Record<string, number>): string`

**Playground Link:**  

**Related Issues:**

#22873

**Comment by weswigham** [comment]
Attributes still get typechecked against `any` unless `ElementAttributesProperty` is specified with a `interface ElementAttributesProperty { props: any; }` declaration. (So even though you've said `Record<string, string>`, we ignore it and check against `any` because we failed to find the declaration.) We _proooooooooooooobably_ don't need to look up props like this anymore, since we know we can always just use the the first argument of the ctor/function; but for now you can get the error you expect just by adding the required `interface ElementAttributesProperty {}` declaration into your `JSX` namespace.

**Comment by ajafff** [comment]
@weswigham I actually have `ElementAttributesProperty` declared. I just omitted it for the report:

```ts
export {};

declare namespace JSX {
    interface IntrinsicElements {
        [elemName: string]: any;
    }

    interface Element {
        render(): Element | string | false;
    }

    interface ElementAttributesProperty {
        props: any;
    }
}

function SFC<T>(props: Record<string, T>) {
    return '';
}

<SFC<string> prop={1}></SFC>; // still no error
```

**Comment by weswigham** [comment]
@ajafff We only look up a global `JSX` or a `JSX` under the factory function - your `export {}` makes it non-global, which means we pretty much don't find a `JSX` at all.

**Comment by weswigham** [comment]
Update: `ElementAttributesProperty` is now optional. We'll use the first parameter of the element's constructor/function for the type if it is not present.
