### ISSUE TITLE
vscode jsdoc import module type def not imported

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#22884]
_From @shivshankar3578 on March 24, 2018 11:9_

@vscode:1.21
@node: 8.10

mod.js

```js
/**
 *  @module mod
 */

/**
 * @typedef {Object} foobar
 * @property {String} foo
 * @property {Boolean} [bar] - Optional value
 */

/**
 * 
 * 
 * @param {string} foo 
 * @param {string} bar 
 * @return {foobar} 
 */
function doSomething (foo, bar) {
  console.log(foo, bar);
  // do something
  return {
	foo : foo,
	bar : bar
  }
}

let n = doSomething('a', 'b');

module.exports  = doSomething;
```

jsdoc.js

```js
const mod = require('./mod');
let n = new mod('a', 'b'); 
console.log(n)
```
pic-1 n:foobar

[![pic-1][1]][1]

then why n:any here

[![pic-2][2]][2]

while  imported module have foobar return type

[![pic-3][3]][3]

  [1]: https://i.stack.imgur.com/RtfVu.png
  [2]: https://i.stack.imgur.com/TnFxS.png
  [3]: https://i.stack.imgur.com/o8x6s.png

_Copied from original issue: Microsoft/vscode#46463_

**Comment by mjbvz** [comment]
Possibly covered by #14844

**Comment by sandersn** [comment]
In jsdoc.js, you use `new`, but without assignments to `this` properties inside of `doSomething`, the compiler doesn't recognise it as newable and falls back to `any`. You'll also get an error if you add `// @ts-check` at the beginning of the file, because we think that newing a function with no this property assignment is very suspicious.

If you call `mod` directly as you did on mod.js:27, you will see the correct type for `n`.
