### ISSUE TITLE
函数类型的接口

### ISSUE THREAD

**Issue by wangzhijun-github** [Microsoft/TypeScript#22894]
函数类型的接口可以定义多个？当声明一个不在此约束的函数，却可以用这个函数类型的接口定义？

![如图所示](https://user-images.githubusercontent.com/24643503/37944772-86550982-31af-11e8-816e-5cddfe577505.png)

**Comment by Cryrivers** [comment]
This is by design. As your interface can be simplified as `(string, string) => boolean`

**Comment by Cryrivers** [comment]
I believe this is by design. Because your function `() => boolean` is assignable to `(string, string) => boolean`. You could do `function searchFunc(source: string, subString: string): boolean { ... }`.

If you have other questions rather than bugs, you could check out https://stackoverflow.com 😊

**Comment by andy-ms** [comment]
By the way, the second overload is redundant and will never be called, since it has the same parameter types as the first overload.

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker, so I'll close this up. Next time, please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
