### ISSUE TITLE
jake runtests-browser broken

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#22905]
**TypeScript Version:** master

**Code**

```
> jake runtests-browser b=chrome t=completion
Saving sourcemaps for C:\Users\anhans\work\TypeScript\built\local\bundle.js
Fixing sourcemaps for C:\Users\anhans\work\TypeScript\built\local\bundle.js
Error: ENOENT: no such file or directory, open 'C:\Users\anhans\work\TypeScript\src\services\(.+)$\gm;'
```

I checked and this worked in the commit before #22658. @weswigham

**Comment by weswigham** [comment]
Heh. I've looked into it. It's alllll because of this line:

![image](https://user-images.githubusercontent.com/2932786/38116948-488c02fe-3367-11e8-88b3-0eb45d46ef46.png)

Sorcery's sourcemappingURL-finding regex is significantly more permissive (worse?) than our own and, in fact, picks up our sourceMappingURL regexp as a sourceMappingURL comment, and then tries to lookup the file `(.+$)/gm`. 

#23006 is now open with a fix
