### ISSUE TITLE
Support for optional abstract members in an abstract class body

### ISSUE THREAD

**Issue by Kovensky** [Microsoft/TypeScript#22939]
**TypeScript Version:**  2.8.0-insiders.20180320 (version currently running in playground)

**Search Terms:** 
abstract optional

**Code**

```ts
abstract class Foo {
    abstract foo(): void
    abstract bar?(): void
}

// Non-abstract class Bar missing abstract member bar
class Bar extends Foo {
    foo() { return }
}
```

**Expected behavior:**
It should be possible to omit the definition of `bar` in the `Bar` class.

If something constructs an instance of `Bar`, it should not be possible to call `new Bar().bar()`, either because it is considered `undefined` or because it still retains some "abstractedness".

The intent is to use this in type definitions where subclasses can optionally define methods that will be called by their superclass; similar to lifecycle events in `React.Component`.

Not making them abstract allows things such as calling `super.componentDidMount()` even though it does not exist in `React.Component`'s prototype, or having a subclass without their own `render()` implementation because TypeScript thinks it is provided by `React.Component`.

Supporting optional abstract members could also be used to guard against the common error of not initializing `state` on classes that use `this.state` -- it does not actually exist until either the first `setState` call or until `this.state` is assigned, and initializing `this.state` by assignment is far more common than initializing it with `setState`.

**Actual behavior:**
It's not possible to omit it unless `bar = undefined` is specifically added to `Bar`

**Playground Link:** [Playground Link](https://www.typescriptlang.org/play/index.html#src=abstract%20class%20Foo%20%7B%0A%20%20%20%20abstract%20foo()%3A%20void%0A%20%20%20%20abstract%20bar%3F()%3A%20void%0A%7D%0A%0Aclass%20Bar%20extends%20Foo%20%7B%0A%20%20%20%20foo()%20%7B%20return%20%7D%0A%7D%0A)

**Comment by mhegazy** [comment]
and why not just:

```ts
abstract class Foo {
    abstract foo(): void
    bar?(): void;
}
```

**Comment by Kovensky** [comment]
Because this means that `super.bar` might exist, but it cannot.

**Comment by mhegazy** [comment]
but how would you witness that? you can not just call `super.bar()` since it is potentially `undefined`, so you have to check for its existence... and if so, what difference does it make if it is abstract or missing?

**Comment by simeyla** [comment]
### You may not need abstract at all

I've hit this issue a few times, and one possible approach is to do this - without the abstract keyword.

```
class Animal
{
    // not all animals can bark so the default is to return undefined
    bark(): AnimalBarkStatus { return undefined; }     // no abstract keyword needed
}

class Dog extends Animal
{
   bark() 
   {
      return 'not-the-correct-type';   // compile time error
   }
}
```

One of the reasons you may think you want 'abstract' is to enforce the method signature. So that 'bark' will return the expected type in any subclass.

If you convert the above code to C# it will compile, because it's allowed for the subclass to return a different type. And of course C# has virtual and override that typescript currently does not.

However in typescript if the subclass doesn't return the same type then it just won't compile.

> `Property 'bark' in type 'Dog' is not assignable to the same property in base type 'Animal`

I had cases where I had an optional method in 10% of subclasses, but I wanted the signature to be enforced by the base class if it did exist. The above allows me to do that without any extra keywords.

The only thing that may not be desirable is that the base class method returns undefined - but for me that was just fine.
