### ISSUE TITLE
`infer` recursion limit?

### ISSUE THREAD

**Issue by agentcooper** [Microsoft/TypeScript#23024]
I'm playing around with conditional types and observing the behavior I don't quite understand.

[Playground link](https://www.typescriptlang.org/play/index.html#src=%2F%2F%20building%20on%20top%20of%0A%2F%2F%20https%3A%2F%2Fgist.github.com%2Futatti%2Fc411d0939094ba490ce6dd78c92ffe4c%0A%0Atype%20Nat%20%3D%200%20%7C%20%7B%20succ%3A%20Nat%20%7D%3B%0A%0Atype%20Succ%3CT%20extends%20Nat%3E%20%3D%20%7B%20succ%3A%20T%20%7D%3B%0A%0Atype%20Add%3CX%20extends%20Nat%2C%20Y%20extends%20Nat%3E%20%3D%0A%20%20%20%20X%20extends%20Succ%3Cinfer%20R%3E%20%3F%20%7B%20succ%3A%20Add%3CR%2C%20Y%3E%20%7D%20%3A%20Y%3B%0A%0Atype%20N0%20%20%3D%200%3B%0Atype%20N1%20%20%3D%20Succ%3CN0%3E%3B%0Atype%20N2%20%20%3D%20Succ%3CN1%3E%3B%0Atype%20N3%20%20%3D%20Succ%3CN2%3E%3B%0Atype%20N4%20%20%3D%20Succ%3CN3%3E%3B%0Atype%20N5%20%20%3D%20Succ%3CN4%3E%3B%0Atype%20N6%20%20%3D%20Succ%3CN5%3E%3B%0Atype%20N7%20%20%3D%20Succ%3CN6%3E%3B%0Atype%20N8%20%20%3D%20Succ%3CN7%3E%3B%0Atype%20N9%20%20%3D%20Succ%3CN8%3E%3B%0A%0Atype%20ToType%3CK%3E%20%3D%0A%20%20%20%20K%20extends%200%20%3F%20N0%20%3A%0A%20%20%20%20K%20extends%201%20%3F%20N1%20%3A%0A%20%20%20%20K%20extends%202%20%3F%20N2%20%3A%0A%20%20%20%20K%20extends%203%20%3F%20N3%20%3A%0A%20%20%20%20K%20extends%204%20%3F%20N4%20%3A%0A%20%20%20%20K%20extends%205%20%3F%20N5%20%3A%0A%20%20%20%20K%20extends%206%20%3F%20N6%20%3A%0A%20%20%20%20K%20extends%207%20%3F%20N7%20%3A%0A%20%20%20%20K%20extends%208%20%3F%20N8%20%3A%0A%20%20%20%20K%20extends%209%20%3F%20N9%20%3A%20never%3B%0A%0Atype%20ToNumber%3CN%3E%20%3D%0A%20%20%20%20N%20extends%20N0%20%3F%200%20%3A%0A%20%20%20%20N%20extends%20N1%20%3F%201%20%3A%0A%20%20%20%20N%20extends%20N2%20%3F%202%20%3A%0A%20%20%20%20N%20extends%20N3%20%3F%203%20%3A%0A%20%20%20%20N%20extends%20N4%20%3F%204%20%3A%0A%20%20%20%20N%20extends%20N5%20%3F%205%20%3A%0A%20%20%20%20N%20extends%20N6%20%3F%206%20%3A%0A%20%20%20%20N%20extends%20N7%20%3F%207%20%3A%0A%20%20%20%20N%20extends%20N8%20%3F%208%20%3A%0A%20%20%20%20N%20extends%20N9%20%3F%209%20%3A%20never%3B%0A%0Adeclare%20function%20add%3C%0A%20%20%20%20XK%20extends%20number%2C%0A%20%20%20%20YK%20extends%20number%2C%0A%3E(x%3A%20XK%2C%20y%3A%20YK)%3A%20ToNumber%3CAdd%3CToType%3CXK%3E%2C%20ToType%3CYK%3E%3E%3E%3B%0A%0A%2F%2F%20try%20commenting%20out%20this%20block%2C%20next%20block%20will%20show%20error%0A%7B%0A%20%20%20%20const%20res%3A%206%20%3D%20add(2%2C%204)%0A%7D%0A%0A%7B%0A%20%20%20%20const%20res%3A%208%20%3D%20add(1%2C%207)%0A%7D%0A) (`ts.version: 2.8.0-insiders.20180320`).

```typescript
// building on top of
// https://gist.github.com/utatti/c411d0939094ba490ce6dd78c92ffe4c

type Nat = 0 | { succ: Nat };

type Succ<T extends Nat> = { succ: T };

type Add<X extends Nat, Y extends Nat> =
    X extends Succ<infer R> ? { succ: Add<R, Y> } : Y;

type N0  = 0;
type N1  = Succ<N0>;
type N2  = Succ<N1>;
type N3  = Succ<N2>;
type N4  = Succ<N3>;
type N5  = Succ<N4>;
type N6  = Succ<N5>;
type N7  = Succ<N6>;
type N8  = Succ<N7>;
type N9  = Succ<N8>;

type ToType<K> =
    K extends 0 ? N0 :
    K extends 1 ? N1 :
    K extends 2 ? N2 :
    K extends 3 ? N3 :
    K extends 4 ? N4 :
    K extends 5 ? N5 :
    K extends 6 ? N6 :
    K extends 7 ? N7 :
    K extends 8 ? N8 :
    K extends 9 ? N9 : never;

type ToNumber<N> =
    N extends N0 ? 0 :
    N extends N1 ? 1 :
    N extends N2 ? 2 :
    N extends N3 ? 3 :
    N extends N4 ? 4 :
    N extends N5 ? 5 :
    N extends N6 ? 6 :
    N extends N7 ? 7 :
    N extends N8 ? 8 :
    N extends N9 ? 9 : never;

declare function add<
    XK extends number,
    YK extends number,
>(x: XK, y: YK): ToNumber<Add<ToType<XK>, ToType<YK>>>;

// try commenting out this block, next block will show error
{
    const res: 6 = add(2, 4)
}

{
    const res: 8 = add(1, 7)
}
```

It seems that there is a recursion limit for `infer` keyword. However if the type expression was already calculated, it goes in the cache.

Is this expected behavior?

**Comment by ahejlsberg** [comment]
First, there's an issue with constraint computation for conditional types that affects your example. This issue is fixed in #23039 and with that fix your particular example works with out without commenting out the block.

However, there *is* an internal limit on relating deeply nested instantiations of the same type. Roughly speaking, when relating two types, if we see more than 5 distinct instantiations of the same type, we stop and consider the relation to be "possibly true". Then, as long as nothing else being related is false, we consider the entire relation to be true. We have this internal limit to ensure that we catch runaway recursion in circular generic types.

Even with the fix in #23039, the `Result` type in the following evaluates to `false` because the deeply nested instantiations of `Succ<T>` reach the internal limit.

```ts
type IsIdentical<T, U> = [T] extends [U] ? [U] extends [T] ? true : false : false;
type Result = IsIdentical<ToNumber<Add<ToType<1>, ToType<7>>>, 8>;
```

But if you change some of the declarations in the example to use distinct types, the result is `true` because the types are no longer deeply nested generic instantiations.

```ts
type N0  = 0;
type N1  = { succ: N0 };
type N2  = { succ: N1 };
type N3  = { succ: N2 };
type N4  = { succ: N3 };
type N5  = { succ: N4 };
type N6  = { succ: N5 };
type N7  = { succ: N6 };
type N8  = { succ: N7 };
type N9  = { succ: N8 };
```

We can try to think of better ways to distinguish explicit instantiations from instantiations that are generated by circular types, but it is unlikely to ever be perfect. It's simply the nature of structural type systems.
