### ISSUE TITLE
Pattern matcher doesn't work for name with space

### ISSUE THREAD

**Issue by ghost** [microsoft/TypeScript#23035]
**TypeScript Version:**  master

**Code**

See `navigateToQuoted.ts` (added in #23036)

**Expected behavior:**

"foo bar" works same as "foo-bar".

**Actual behavior:**

Navigation to "foo bar" doesn't work.

**Comment by mhegazy** [comment]
@andy-ms you are more familiar with the pattern matching code, thoughts?

**Comment by andy-ms** [comment]
The documentation on `subWordTextChunks` says:

```
Information about the subwords compromising the total word.  For example, if the
text between the dots is 'GetFoo KeywordBar', then the subwords will be 'GetFoo'
and 'KeywordBar'.  Those individual words will have CharacterSpans of ('Get' and
'Foo') and('Keyword' and 'Bar') respectively.
```

It looks like if you write 'foo bar' we will match against 'foo' *OR* 'bar', and return the best match. But we will *not* match "foo bar". So it treats " " like "|" in a regular expression. Not sure if that's still the desired behavior, or what other languages doo in this situation. If we didn't keep this behavior then the pattern matcher would get a lot simpler because we wouldn't have to compute `subWordTextChunks`, and then a `Segment` would just be a `TextChunk`.

As for why no tests failed, we don't seem to be running them: #23836
