### ISSUE TITLE
Using a condition mapped type on a type that extends another type causes error

### ISSUE THREAD

**Issue by Roaders** [Microsoft/TypeScript#23063]
**TypeScript Version:**  2.8.1

**Search Terms:** 
conditional types, extends 

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
interface StringOption{
    type: "string";
}

interface NumberOption{
    type: "number";
}

type ValidTypes = {
    [key: string]: string | number;
}

interface ISampleObject extends ValidTypes {
    stringParam: string,
    numberParam: number
}

type MappedOptions<T extends ValidTypes> = {
    readonly [P in keyof T]: T[P] extends string ? StringOption : 
        T[P] extends number ? NumberOption : never;
}

const mappedObject: MappedOptions<ISampleObject> = {
    stringParam: {type: "string"},
    numberParam: {type: "number"}
}
```

**Expected behavior:**
This should compile correctly

**Actual behavior:**
A compilation error is shown:
```
Property 'stringParam' is incompatible with index signature.
Type '{ type: "string"; }' is not assignable to type 'never'.
```

**Playground Link:**  
[Playground Link](http://www.typescriptlang.org/play/#src=%0D%0Ainterface%20StringOption%7B%0D%0A%20%20%20%20type%3A%20%22string%22%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20NumberOption%7B%0D%0A%20%20%20%20type%3A%20%22number%22%3B%0D%0A%7D%0D%0A%0D%0Atype%20ValidTypes%20%3D%20%7B%0D%0A%20%20%20%20%5Bkey%3A%20string%5D%3A%20string%20%7C%20number%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20ISampleObject%20extends%20ValidTypes%20%7B%0D%0A%20%20%20%20stringParam%3A%20string%2C%0D%0A%20%20%20%20numberParam%3A%20number%0D%0A%7D%0D%0A%0D%0Atype%20MappedOptions%3CT%20extends%20ValidTypes%3E%20%3D%20%7B%0D%0A%20%20%20%20readonly%20%5BP%20in%20keyof%20T%5D%3A%20T%5BP%5D%20extends%20string%20%3F%20StringOption%20%3A%20%0D%0A%20%20%20%20%20%20%20%20T%5BP%5D%20extends%20number%20%3F%20NumberOption%20%3A%20never%3B%0D%0A%7D%0D%0A%0D%0Aconst%20mappedObject%3A%20MappedOptions%3CISampleObject%3E%20%3D%20%7B%0D%0A%20%20%20%20stringParam%3A%20%7Btype%3A%20%22string%22%7D%2C%0D%0A%20%20%20%20numberParam%3A%20%7Btype%3A%20%22number%22%7D%0D%0A%7D)

This code sample works fine if the `ValidTypes` type is removed. I am using this type to limit the property types that can be used with this mapped type. Without it any type could be used and complex types containing functions and booleans could be created.

**Comment by jack-williams** [comment]
@andy-ms  Is this a bug or just because `StringToNumber` is distributive but `Mapped2` is not?

**Comment by andy-ms** [comment]
@jack-williams I don't really know, better to wait for another team member to look. May not be a bug.

**Comment by mhegazy** [comment]
This is working as intended..  `T[P]` in the conditional type does not distribute.. only a naked type parameter would. you can get the same behavior by factoring out the condition into a different type definition:

```ts

type MappedOptions<T extends ValidTypes> = {
    readonly [P in keyof T]: StringOrNumber<T[P]>;
}

type StringOrNumber<T> =  T extends string ? StringOption : 
        T  extends number ? NumberOption : never;

```

**Comment by Roaders** [comment]
Thanks, I am not sure what you mean by `T[P] in the conditional type does not distribute.. only a naked type parameter would. ` though.

Do you mean that when I do 

`T[P] extends string ? StringOption`

It is not actually using `string` but it is using `ISampleObject`?

Your alternative solution works for me so thanks but I still find it odd that my original code did not work.

**Comment by mhegazy** [comment]
Conditional types can be distributive.. i.e. they distribute over union types during instantiation. For example, an instantiation of `T extends U ? X : Y` with the type argument `A | B | C ` for `T` is resolved as `(A extends U ? X : Y) | (B extends U ? X : Y) | (C extends U ? X : Y)`.
this special feature is only available if the conditional type was defined as `T extends <some type> ? <true type> : <false type>`, and not if the condition is any type expression, e.g. `[T] extends ...`, `T[P] extends ..`, or ` T | number extends ...`, etc..
See https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#distributive-conditional-types for more details.

**Comment by Roaders** [comment]
I am still struggling with this. I have some complicated (for me) conditional transformations and this issue keeps cropping up. It has seemingly randomly disappeared a few times but keeps coming back. It seems very random and unpredictable (to me).

Currently I have this situation

[Playground](http://www.typescriptlang.org/play/#src=type%20argumentPrimitive%20%3D%20string%20%7C%20number%20%7C%20Date%20%7C%20boolean%3B%0D%0A%0D%0Atype%20allArgumentTypes%20%3D%20argumentPrimitive%20%7C%20argumentPrimitive%5B%5D%3B%0D%0A%0D%0Atype%20INonNullableApplicationArguments%20%3D%20%7B%0D%0A%20%20%20%20%5Bkey%3A%20string%5D%3A%20allArgumentTypes%3B%0D%0A%7D%0D%0A%0D%0Aexport%20type%20IApplicationArguments%20%3D%20Partial%3CINonNullableApplicationArguments%3E%0D%0A%0D%0Atype%20ConditionalTypedOption%3CT%3E%20%3D%20%0D%0A%20%20%20%20T%20extends%20string%20%3F%20%7B%20type%3A%20%22string%22%20%7D%20%3A%20%0D%0A%20%20%20%20T%20extends%20number%20%3F%20%7B%20type%3A%20%22number%22%20%7D%20%3A%0D%0A%20%20%20%20T%20extends%20boolean%20%3F%20%7B%20type%3A%20%22boolean%22%20%7D%20%3A%0D%0A%20%20%20%20T%20extends%20Date%20%3F%20%7B%20type%3A%20%22date%22%20%7D%20%3A%20%0D%0A%20%20%20%20never%3B%0D%0A%0D%0Atype%20OptionWithTypeAndMultiple%3CT%3E%20%3D%20T%20extends%20(infer%20U)%5B%5D%20%3F%20%0D%0A%20%20%20%20%7B%20multipleValues%3A%20true%20%7D%20%26%20ConditionalTypedOption%3CU%3E%20%3A%20%0D%0A%20%20%20%20%7B%20multipleValues%3A%20false%20%7D%20%26%20ConditionalTypedOption%3CT%3E%3B%0D%0A%0D%0Ainterface%20SampleValueCommandOption%3CT%3E%7B%0D%0A%20%20%20%20sampleValue%3A%20T%3B%0D%0A%7D%0D%0A%0D%0Atype%20SampleOrConfiguredOption%3CT%3E%20%3D%20SampleValueCommandOption%3CT%3E%20%7C%20OptionWithTypeAndMultiple%3CT%3E%3B%0D%0A%0D%0Atype%20OptionWithOptional%3CT%3E%20%3D%20undefined%20extends%20T%20%3F%20%0D%0A%20%20%20%20SampleOrConfiguredOption%3CT%3E%20%26%20%7Brequired%3F%3A%20false%7D%20%3A%0D%0A%20%20%20%20SampleOrConfiguredOption%3CT%3E%20%26%20%7Brequired%3A%20true%7D%3B%0D%0A%0D%0A%0D%0Aexport%20type%20IApplicationArgumentsConfiguration%3CT%20extends%20IApplicationArguments%3E%20%3D%20%7B%0D%0A%20%20%20%20readonly%20%5BP%20in%20keyof%20T%5D-%3F%3A%20undefined%20extends%20T%5BP%5D%20%3F%20T%5BP%5D%20%7C%20OptionWithOptional%3CT%5BP%5D%3E%20%3A%20OptionWithOptional%3CT%5BP%5D%3E%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20ISampleParams%20extends%20IApplicationArguments%20%7B%0D%0A%20%20%20%20optionalStringProp%3F%3A%20string%2C%0D%0A%20%20%20%20requiredStringProp%3A%20string%2C%0D%0A%20%20%20%20sampleOptionalStringProp%3F%3A%20string%2C%0D%0A%20%20%20%20complexOptionalStringProp%3F%3A%20string%0D%0A%20%20%20%20complexRequiredStringProp%3A%20string%0D%0A%7D%0D%0A%0D%0Aconst%20parameterDefinition%3A%20IApplicationArgumentsConfiguration%3CISampleParams%3E%20%3D%20%7B%0D%0A%20%20%20%20optionalStringProp%3A%20%22%22%2C%0D%0A%20%20%20%20requiredStringProp%3A%20%7BsampleValue%3A%20%22%22%2C%20required%3A%20true%7D%2C%0D%0A%20%20%20%20sampleOptionalStringProp%3A%20%7B%20sampleValue%3A%20%22%22%20%7D%2C%0D%0A%20%20%20%20complexOptionalStringProp%3A%20%7Btype%3A%20%22string%22%2C%20multipleValues%3A%20false%7D%2C%0D%0A%20%20%20%20complexRequiredStringProp%3A%20%7Btype%3A%20%22string%22%2C%20multipleValues%3A%20false%2C%20required%3A%20true%7D%0D%0A%7D)

I understand that this is to do with unions but I have tried to keep each conditional block quite simple...

Any help much appreciated, this issues seems pretty opaque to me with poor error messages and it is still not clear to me why this is happening or how to solve it...

**Comment by kpdonn** [comment]
@Roaders I don't really understand what you are trying to do but I can at least tell you that your first issue is that `keyof ISampleParams` is `string` and not `"optionalStringProp" | "requiredStringProp" | ... ` like I think you expect. That is because `ISampleParams` extends `IApplicationArguments` which has the string index signature from `INonNullableApplicationArguments`.

For a much simpler example consider: 
```ts
type Test = {
    a: string
    b: string,
    [ind: string]: string
}
type TestKeys = keyof Test // string
```
What's going on there is that `keyof Test` would be `"a" | "b" | string` except the `| string` part means that it simplifies down to simply `string` because both `"a"` and `"b"` are included in `string`. That's the same thing that is happening in your example. 

It looks like just taking away the `extends IApplicationArguments` parts actually makes your example compile when `strictNullChecks` is enabled. I'm not sure why it continues to fail with `strictNullChecks` disabled though.

[Playground Link](http://www.typescriptlang.org/play/#src=type%20argumentPrimitive%20%3D%20string%20%7C%20number%20%7C%20Date%20%7C%20boolean%3B%0D%0A%0D%0Atype%20allArgumentTypes%20%3D%20argumentPrimitive%20%7C%20argumentPrimitive%5B%5D%3B%0D%0A%0D%0Atype%20INonNullableApplicationArguments%20%3D%20%7B%0D%0A%20%20%20%20%5Bkey%3A%20string%5D%3A%20allArgumentTypes%3B%0D%0A%7D%0D%0A%0D%0Aexport%20type%20IApplicationArguments%20%3D%20Partial%3CINonNullableApplicationArguments%3E%0D%0A%0D%0Atype%20ConditionalTypedOption%3CT%3E%20%3D%20%0D%0A%20%20%20%20T%20extends%20string%20%3F%20%7B%20type%3A%20%22string%22%20%7D%20%3A%20%0D%0A%20%20%20%20T%20extends%20number%20%3F%20%7B%20type%3A%20%22number%22%20%7D%20%3A%0D%0A%20%20%20%20T%20extends%20boolean%20%3F%20%7B%20type%3A%20%22boolean%22%20%7D%20%3A%0D%0A%20%20%20%20T%20extends%20Date%20%3F%20%7B%20type%3A%20%22date%22%20%7D%20%3A%20%0D%0A%20%20%20%20never%3B%0D%0A%0D%0Atype%20OptionWithTypeAndMultiple%3CT%3E%20%3D%20T%20extends%20(infer%20U)%5B%5D%20%3F%20%0D%0A%20%20%20%20%7B%20multipleValues%3A%20true%20%7D%20%26%20ConditionalTypedOption%3CU%3E%20%3A%20%0D%0A%20%20%20%20%7B%20multipleValues%3A%20false%20%7D%20%26%20ConditionalTypedOption%3CT%3E%3B%0D%0A%0D%0Ainterface%20SampleValueCommandOption%3CT%3E%7B%0D%0A%20%20%20%20sampleValue%3A%20T%3B%0D%0A%7D%0D%0A%0D%0Atype%20SampleOrConfiguredOption%3CT%3E%20%3D%20SampleValueCommandOption%3CT%3E%20%7C%20OptionWithTypeAndMultiple%3CT%3E%3B%0D%0A%0D%0Atype%20OptionWithOptional%3CT%3E%20%3D%20undefined%20extends%20T%20%3F%20%0D%0A%20%20%20%20SampleOrConfiguredOption%3CT%3E%20%26%20%7Brequired%3F%3A%20false%7D%20%3A%0D%0A%20%20%20%20SampleOrConfiguredOption%3CT%3E%20%26%20%7Brequired%3A%20true%7D%3B%0D%0A%0D%0A%0D%0Aexport%20type%20IApplicationArgumentsConfiguration%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20readonly%20%5BP%20in%20keyof%20T%5D-%3F%3A%20undefined%20extends%20T%5BP%5D%20%3F%20T%5BP%5D%20%7C%20OptionWithOptional%3CT%5BP%5D%3E%20%3A%20OptionWithOptional%3CT%5BP%5D%3E%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20ISampleParams%20%7B%0D%0A%20%20%20%20optionalStringProp%3F%3A%20string%2C%0D%0A%20%20%20%20requiredStringProp%3A%20string%2C%0D%0A%20%20%20%20sampleOptionalStringProp%3F%3A%20string%2C%0D%0A%20%20%20%20complexOptionalStringProp%3F%3A%20string%0D%0A%20%20%20%20complexRequiredStringProp%3A%20string%0D%0A%7D%0D%0A%0D%0Aconst%20parameterDefinition%3A%20IApplicationArgumentsConfiguration%3CISampleParams%3E%20%3D%20%7B%0D%0A%20%20%20%20optionalStringProp%3A%20%22%22%2C%0D%0A%20%20%20%20requiredStringProp%3A%20%7BsampleValue%3A%20%22%22%2C%20required%3A%20true%7D%2C%0D%0A%20%20%20%20sampleOptionalStringProp%3A%20%7B%20sampleValue%3A%20%22%22%20%7D%2C%0D%0A%20%20%20%20complexOptionalStringProp%3A%20%7Btype%3A%20%22string%22%2C%20multipleValues%3A%20false%7D%2C%0D%0A%20%20%20%20complexRequiredStringProp%3A%20%7Btype%3A%20%22string%22%2C%20multipleValues%3A%20false%2C%20required%3A%20true%7D%0D%0A%7D)  (Note you need to manually click "options" and enable `strictNullChecks`, the options don't serialize with the code unfortunately)

**Comment by Roaders** [comment]
This is part of a library that parses command line arguments in a node app.
The idea is that you define the interface for the object you expect to get back that includes all your command line options. In this case it is `ISampleParams`. The transformed object `parameterDefinition` is used to configure the parameter parsing code.

Basically you either specify a sample value such as `"string"` or you configure the argument with an object:

```
{type: "string", 
multipleValues: false, 
required: true}
```

Obviously the `ISampleParams` does not exist at run time so we need to take that info contained by the interface (required, argument type, multiple values) and add it to the parsing code configuration.

The idea behind this code is to force the user to properly construct the configuration object so that it accurately reflects the expected output object.

The `IApplicationArguments` limits the types that can be used - we can't pass a complex object or a function into the application through command line options so we limit the types to primitives that can be derived from a string.

**Comment by Roaders** [comment]
The example that I have given works fine if I remove the `{required?: false}` and `{required: true}` from the `OptionWithOptional` type (and the required properties on the `parameterDefinition`. I can't understand why that breaks it when I am doing something very similar with the `{ multipleValues: true }` type.

**Comment by kpdonn** [comment]
> The IApplicationArguments limits the types that can be used - we can't pass a complex object or a function into the application through command line options so we limit the types to primitives that can be derived from a string.

A way to do this that avoids the string index signature that is causing you problems is instead of 
```ts
type IApplicationArgumentsConfiguration<T extends IApplicationArguments> = { ... }

interface ISampleParams extends IApplicationArguments { ... }

const parameterDefinition: IApplicationArgumentsConfiguration<ISampleParams> = { ... }
```
use something like this 
```ts
type IApplicationArgumentsConfiguration<T extends { [K in keyof T]: allArgumentTypes }> = { ... }

interface ISampleParams { ... }  // Note how there is no explicit extends needed here now

const parameterDefinition: IApplicationArgumentsConfiguration<ISampleParams> = { ... }
```

How typescript manages to make that work without complaining about a circular constaint on `T` seems like a minor miracle to me, but I've used it before for basically the same use case you described.

Here's a playground link showing it in action including an error like you are looking for if someone makes a mistake and tries to define a property with a complex object for a type:

[Playground Link](http://www.typescriptlang.org/play/#src=type%20argumentPrimitive%20%3D%20string%20%7C%20number%20%7C%20Date%20%7C%20boolean%3B%0D%0A%0D%0Atype%20allArgumentTypes%20%3D%20argumentPrimitive%20%7C%20argumentPrimitive%5B%5D%3B%0D%0A%0D%0Atype%20ConditionalTypedOption%3CT%3E%20%3D%20%0D%0A%20%20%20%20T%20extends%20string%20%3F%20%7B%20type%3A%20%22string%22%20%7D%20%3A%20%0D%0A%20%20%20%20T%20extends%20number%20%3F%20%7B%20type%3A%20%22number%22%20%7D%20%3A%0D%0A%20%20%20%20T%20extends%20boolean%20%3F%20%7B%20type%3A%20%22boolean%22%20%7D%20%3A%0D%0A%20%20%20%20T%20extends%20Date%20%3F%20%7B%20type%3A%20%22date%22%20%7D%20%3A%20%0D%0A%20%20%20%20never%3B%0D%0A%0D%0Atype%20OptionWithTypeAndMultiple%3CT%3E%20%3D%20T%20extends%20(infer%20U)%5B%5D%20%3F%20%0D%0A%20%20%20%20%7B%20multipleValues%3A%20true%20%7D%20%26%20ConditionalTypedOption%3CU%3E%20%3A%20%0D%0A%20%20%20%20%7B%20multipleValues%3A%20false%20%7D%20%26%20ConditionalTypedOption%3CT%3E%3B%0D%0A%0D%0Ainterface%20SampleValueCommandOption%3CT%3E%7B%0D%0A%20%20%20%20sampleValue%3A%20T%3B%0D%0A%7D%0D%0A%0D%0Atype%20SampleOrConfiguredOption%3CT%3E%20%3D%20SampleValueCommandOption%3CT%3E%20%7C%20OptionWithTypeAndMultiple%3CT%3E%3B%0D%0A%0D%0Atype%20OptionWithOptional%3CT%3E%20%3D%20undefined%20extends%20T%20%3F%20%0D%0A%20%20%20%20SampleOrConfiguredOption%3CT%3E%20%26%20%7Brequired%3F%3A%20false%7D%20%3A%0D%0A%20%20%20%20SampleOrConfiguredOption%3CT%3E%20%26%20%7Brequired%3A%20true%7D%3B%0D%0A%0D%0A%0D%0Aexport%20type%20IApplicationArgumentsConfiguration%3CT%20extends%20%7B%5BK%20in%20keyof%20T%5D%3A%20allArgumentTypes%7D%3E%20%3D%20%7B%0D%0A%20%20%20%20readonly%20%5BP%20in%20keyof%20T%5D-%3F%3A%20undefined%20extends%20T%5BP%5D%20%3F%20T%5BP%5D%20%7C%20OptionWithOptional%3CT%5BP%5D%3E%20%3A%20OptionWithOptional%3CT%5BP%5D%3E%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20ISampleParams%20%7B%0D%0A%20%20%20%20optionalStringProp%3F%3A%20string%2C%0D%0A%20%20%20%20requiredStringProp%3A%20string%2C%0D%0A%20%20%20%20sampleOptionalStringProp%3F%3A%20string%2C%0D%0A%20%20%20%20complexOptionalStringProp%3F%3A%20string%0D%0A%20%20%20%20complexRequiredStringProp%3A%20string%0D%0A%7D%0D%0A%0D%0Ainterface%20BadSampleParams%20%7B%0D%0A%20%20%20%20optionalStringProp%3F%3A%20%7Bcomplex%3A%20%7Bobj%3A%20%22not%20allowed%22%7D%7D%2C%0D%0A%20%20%20%20requiredStringProp%3A%20string%2C%0D%0A%20%20%20%20sampleOptionalStringProp%3F%3A%20string%2C%0D%0A%20%20%20%20complexOptionalStringProp%3F%3A%20string%0D%0A%20%20%20%20complexRequiredStringProp%3A%20string%0D%0A%7D%0D%0A%0D%0Atype%20ExpectAnError%20%3D%20IApplicationArgumentsConfiguration%3CBadSampleParams%3E%0D%0A%0D%0Aconst%20parameterDefinition%3A%20IApplicationArgumentsConfiguration%3CISampleParams%3E%20%3D%20%7B%0D%0A%20%20%20%20optionalStringProp%3A%20%22%22%2C%0D%0A%20%20%20%20requiredStringProp%3A%20%7BsampleValue%3A%20%22%22%2C%20required%3A%20true%7D%2C%0D%0A%20%20%20%20sampleOptionalStringProp%3A%20%7B%20sampleValue%3A%20%22%22%20%7D%2C%0D%0A%20%20%20%20complexOptionalStringProp%3A%20%7Btype%3A%20%22string%22%2C%20multipleValues%3A%20false%7D%2C%0D%0A%20%20%20%20complexRequiredStringProp%3A%20%7Btype%3A%20%22string%22%2C%20multipleValues%3A%20false%2C%20required%3A%20true%7D%0D%0A%7D) (Same note as before about needing to enable `strictnullchecks` in order to make `parameterDefinition` not have a compile error)

**Comment by Roaders** [comment]
Hey! That seems to have done it. A much nicer way of doing that and the errors have gone away!

Many thanks for your help.

**Comment by kpdonn** [comment]
No problem I like playing with complex types like this.

I actually think you can improve them a little more by changing

```ts
type SampleOrConfiguredOption<T> = SampleValueCommandOption<T> | OptionWithTypeAndMultiple<T>;
```
to 
```ts
type SampleOrConfiguredOption<T> = (SampleValueCommandOption<T> & Partial<OptionWithTypeAndMultiple<T>>)
 | (OptionWithTypeAndMultiple<T> & Partial<SampleValueCommandOption<T>>);
```

That should prevent people from potentially writing things that conflict with `ISampleParams` but previously wouldn't cause an error because it would be still be assignable to one side of the union or the other like:

```ts
const parameterDefinition: IApplicationArgumentsConfiguration<ISampleParams> = {
    // multipleValues: true and type: "number" don't make sense here
    // but were previously allowed because it was able to assign
    // sampleValue: "" to SampleValueCommandOption<T>
    requiredStringProp: {sampleValue: "", multipleValues: true, type: "number", required: true},
   ...
}
```
or 
```ts
const parameterDefinition: IApplicationArgumentsConfiguration<ISampleParams> = {
    // sampleValue: 365 doesn't make sense here
    // but was previously allowed because it was able to assign
    // {multipleValues: false, type: "string" } to OptionWithTypeAndMultiple<T>
    requiredStringProp: {sampleValue: 365, multipleValues: false, type: "string", required: true},
   ...
}
```

And the last thing I'll mention is that you might be interested in the https://github.com/gcanti/io-ts library. I'm not sure if it's directly applicable to your example but it does deal with the similar issue of static types not existing at runtime but approaches solving it from the opposite direction. You are starting from the static types and trying to create something at runtime based on them, while in contrast `io-ts` starts with runtime objects and creates static types from those objects.

**Comment by Roaders** [comment]
Thanks, I'll just try and bend my head round that last post and see if I can apply it to my code :-)

**Comment by Roaders** [comment]
@kpdonn many thanks for that last suggestion. I hadn't even realised that was a problem. I am surprised that this
```
type SampleOrConfiguredOption<T> = SampleValueCommandOption<T> | OptionWithTypeAndMultiple<T>;
```

produces a type that can mix properties from `SampleValueCommandOption` and `OptionWithTypeAndMultiple`.

I see that your suggestion

```
type SampleOrConfiguredOption<T> = 
    ( SampleValueCommandOption<T> & Partial<OptionWithTypeAndMultiple<T>> )
    | 
    (OptionWithTypeAndMultiple<T> & Partial<SampleValueCommandOption<T>>);
```

specifically allows that mixing but then enforces the correct `type` and `multipleValues` values.

Thanks again. That's another potential bug squashed.
