### ISSUE TITLE
Generating source maps with relative path in sourceRoot option produces maps with abosolute file paths

### ISSUE THREAD

**Issue by evil-shrike** [Microsoft/TypeScript#23180]
# Problem
I supply `sourceMap: true` and `sourceRoot: "./../src/"` options to tsc (via tsconfig) while compiling with `--declaration` flag: `tsc -d --outDir ./out`.  
I expect that *.js.map will contain relative paths to ../src. 
Instead they contain absolute paths to my local folder:
```json
{"version":3,"file":"index.js","sourceRoot":"D:/Work/Learn/typescript/src/","sources":["index.ts"],"names":[],"mappings": ... }
```

# Steps to reproduce

```
D:.
│   tsconfig.json
│
├───out
│       index.d.ts
│       index.js
│       index.js.map
│
└───src
        index.ts
```
tsconfig.json:
```json
{
	"compilerOptions": {
		"module": "amd",
		"target": "es3",
		"sourceMap": true,
		"sourceRoot": "./../src/",
		"noEmitHelpers": true
	},
	"include": [
		"**/*.ts"
	]
}
```
`src/index.ts`:
```ts
export class MyClass {}
```
run in folder with `tsconfig.json`:
```shell
tsc -d --outDir ./out
```

I tried TS 2.6, 2.7, 2.8 all of them produce the same result.

**Comment by mhegazy** [comment]
PRs welcomed.

**Comment by a-tarasyuk** [comment]
This bug causes because each option which has property `option.isFilePath` processed by function `normalizePath`. `sourceRoot` is also processed, that's why in a sourceMap file contains the new path

```typescript
function normalizeNonListOptionValue(option: CommandLineOption, basePath: string, value: any): CompilerOptionsValue {
    if (option.isFilePath) {
        value = normalizePath(combinePaths(basePath, value));
        if (value === "") {
	    value = ".";
        }
    }

    return value;
}
```

@mhegazy I have couple questions before I'll start work on PR.

1. Should we exclude only `sourceRoot` from _path_ normalization process, or need to do the same for other options?
2. Is it good to add this logic to `normalizeNonListOptionValue`? Or maybe we can add the new property to `option` which will disable normalization _path_, like 

```typescript
{
            newPropertyWhichWillSkipPathNormalization: true,
            name: "sourceRoot",
            type: "string",
            isFilePath: true,
            paramType: Diagnostics.LOCATION,
            category: Diagnostics.Source_Map_Options,
            description: ...
        },
```
or maybe you can suggest another solution. Thanks in advance.

**Comment by mhegazy** [comment]
`SourceRoot` should not have the `isFilePath` flag on it. that should also apply to `mapRoot`.

**Comment by a-tarasyuk** [comment]
@mhegazy ok, I made PR. thanks for your help.
