### ISSUE TITLE
Line numbers are not enabled as default

### ISSUE THREAD

**Issue by forki** [Microsoft/TypeScript#2325]
Please enable "line numbers" as a default for the code editor.

This is a duplicate of https://github.com/Microsoft/visualfsharp/issues/304 and https://github.com/dotnet/roslyn/issues/1222, but we think it should be done for all languages (see https://github.com/Microsoft/visualfsharp/issues/304#issuecomment-78557404)

**Comment by danquirk** [comment]
Let me see if I can figure out how often people actually turn this setting on to help guide whether we should do this.

**Comment by forki** [comment]
great idea. thanks.

**Comment by NoelAbrahams** [comment]
> but we think it should be done for all languages

Who's we? :smiley: 

I don't think that a few plus ones and a comment makes this by any means a done deal.

Line numbers are only only necessary if people
 
- Have individual code files that are too long.
- Don't know that double clicking on an error in the output window takes you straight to the error line.
- Don't know about the line number on the status bar

 ![image](https://cloud.githubusercontent.com/assets/1106823/6626580/c810c7de-c8ef-11e4-8ac6-ba3cb409c56c.png)
- Don't know about Control + G

Line numbers in fact are visually distracting and unnecessary.

**Comment by danquirk** [comment]
Personally I agree and don't turn them on but I realize a lot of people do, a lot of other editors do by default, and a lot of people are just used to having them on at this point. Defaults should obviously reflect what most people actually want so I'll try to figure out what is actually common and not just based on a small sample size in a few GitHub issue (which is not to say the feedback here isn't valuable, we should look into it now, just with a broader data set).

**Comment by KevinRansom** [comment]
I don't use line numbers, at all.  They are nothing more than visual clutter in my opinion.  So do what you will with the Default FSharp Settings but please leave the General Template w/o line numbers.

**Comment by DanielRosenwasser** [comment]
Imagine you have
* someone telling you, through some kind of messaging service, that there is an issue with a specific line number in your file.
* a person behind you trying to tell you to go to a specific line in your file, but cannot express themselves because a person sounds ridiculous when reading code out loud.
* an extremely anal user who does not like line numbers shown sitting right next to you.

Out of these three cases, line numbers by default greatly help out the first two (especially if you don't know about Ctrl+G), while only slightly inconveniencing the latter user.

Of course, if you'd like to apply data analytics to determine what to do, go right ahead. Obviously, I'm being as objective as possible though. :wink:

**Comment by forki** [comment]
Yep it really is mostly about communication with other people (and tools) for me (pairing sessions, talks, code reviews, telephone calls,...). Ctrl+G and the status line are not working here since if I'm not the driver I can't press buttons and how can I reference a different line if I'm only seeing the current line no.? 

But yes,  I really hoped for MS to look at telemetry data. That's something we OSS contributors can't do. Maybe this will even change the default settings for things like CodeLens (which even conflicts with edit behavior).

**Comment by NoelAbrahams** [comment]
> how can I reference a different line if I'm only seeing the current line

I would have thought that to reference a different line one must be seeing that line. Then it's just a case of clicking on the editor to see what the status bar has to say.

@DanielRosenwasser, sounds a bit like you're working in a call centre - not very conducive for writing code :smile: 

I agree that it's useful to have line numbers showing at certain times, but to have them on the remaining 90% of the time when you don't need them is the issue: It's just additional useless information for the mind to process.

**Comment by forki** [comment]
> I would have thought that to reference a different line one must be seeing that line.

it's on the screen. pair programming partner can see it - but not click it (because only one person has the mouse and keyboard). That's not about being in a call centre.

> on the remaining 90% of the time when you don't need them

That's why I hoped we can hear about telemetry data.

**Comment by danquirk** [comment]
Since we're all putting on our UX designer hat (my favorite) I'll just throw in another factor I think is understated: the color scheme greatly affects whether a default like this feels like unnecessary visual noise. I have line numbers on in Sublime and it's no problem, the line numbers are light grey on a darker background. They largely fall away from view compared to white identifier text and colorized keywords. In Visual Studio the default is a white background with teal line numbers. They're closer to the color of keywords than anything else and fundamentally colored in a way that draws attention to them rather than leaves them as ambient information (any bright tone on white will get your attention, that's the point of color afterall). In general I find the default Visual Studio colorization scheme suffers from a number of issues like this. Would be happy to entertain arguments from people with actual UX credentials :)

**Comment by latkin** [comment]
Stating that line numbers are not needed because line info is already in the status bar is tantamount to saying squiggles are not needed because errors are already listed in the error window.  Many of us prefer to have the information available where we are already looking, rather than needing to glance back and forth to the bottom of the screen.  Not to mention the status bar only shows where the cursor is, so you're out of luck if you are scrolling around.

But it doesn't really matter, it's obviously a preference thing and should be easy to turn on/off as each person desires.  The default should be purely a matter of "what do most people do", assuming that it's a strong majority.

FWIW this was looked at by VS platform team in the past and their opinion was that having line numbers enabled is roughly 80% user preference, but they left it disabled for performance reasons (yes it takes cycles to render the numbers). IMO if 80% turn it in on anyways the perf hit isn't enough to worry about...

**Comment by NoelAbrahams** [comment]
> Stating that line numbers are not needed because line info is already in the status bar is tantamount to saying squiggles are not needed because errors are already listed in the error window. 

Not true. The latter is a different window and may exist on a separate screen altogether.

Line numbers are mostly necessary for machines and for the occasional sharing of information. Individuals writing code shouldn't depend on them. I normally get by okay when reading a novel without worrying about line numbers. Written code should read like a novel: self-explanatory - not referenced by the position the sentences occupy on the page.

(Sorry for the Sunday morning sermon!)

**Comment by latkin** [comment]
Found an old UserVoice here http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/3273933-enable-line-numbers-by-default, if anyone cares to vote.

**Comment by RyanCavanaugh** [comment]
Assigning to Dan for getting the data on this.

:bike: :house:

**Comment by basarat** [comment]
I thought visual studio setting are now in the :cloud: by the time yo comment on this shouldn't you have all your copies setup perfectly?

I have them off in vs. But love them in atom. 

Also in atom find panel (like resharper) you can append line numbers using :number e.g :50 in go to file.

**Comment by mhegazy** [comment]
Please refile under https://visualstudio.uservoice.com/forums/121579-visual-studio-2015
