### ISSUE TITLE
Missing type SVGTransformable

### ISSUE THREAD

**Issue by streamcode9** [Microsoft/TypeScript#23420]
**TypeScript Version:**
2.3.4 and later

**Search Terms:**
SVGTransformable missing type

**Code**

```ts
const someFun = (node: SVGTransformable) => { }
```

**Expected behavior:**
Success compilation. 

**Actual behavior:**
Error TS2304: Cannot find name 'SVGTransformable'.

**Playground Link:**
[Link](https://www.typescriptlang.org/play/index.html#src=const%20someFun%20%3D%20(node%3A%20SVGTransformable)%20%3D%3E%20%7B%20%7D)

**Comments:**
Version 1.8.7 has `SVGTransformable` type.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by a-tarasyuk** [comment]
@mhegazy 

> Moved members from 'SVGLocatable' and 'SVGTransformable' to 'SVGGraphicsElement' and removed those interfaces

[SVG-2-new-features](https://github.com/w3c/svgwg/wiki/SVG-2-new-features)

`SVGTransformable` is part of previous spec 1.1. Should we support these two interfaces?

**Comment by mhegazy** [comment]
>  Should we support these two outdated interfaces?

no we should not. thanks for verifying. closing.

**Comment by nponeccop** [comment]
Here are a few considerations:

- The latest SVG recommendation is SVG 1.1. SVG 2 **is not a recommendation** yet but a candidate recommendation, which means **pre-release** status.
- The process of SVG2 standardization [has stalled since 2016][1] which means SVG2 may never be released. The above candidate is from 2016.
- Because of the reasons above, [the Edge team chose not to implement SVG2][2] at all. [Current support by other browsers][3], as viewed by the Edge team, is still fragmentary ("in development").

So basically SVG 2 is not the way to go because it's dead.

So the real question of this issue is whether TypeScript should choose SVG 1.0 or SVG 1.1 or both.

SVG 1.1. is merely a modularization of SVG 1.0. It means the same features but more logical interfaces/types. And it also means that SVG 1.0 types are incompatible with those of 1.1. However, it may be possible to support both with the Typescript type system.

And Typescript currently sticks to the SVG 1.0 spec: the `.transform()` method is in SVGTransformable in SVG 1.1, but in a different interface in SVG.1.0

[1]: https://css-tricks.com/svg-2-conundrum/
[2]: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15169808/
[3]: https://developer.microsoft.com/en-us/microsoft-edge/platform/status/svg2/
