### ISSUE TITLE
Returning a Proxy from a class does not infer and can’t be typed

### ISSUE THREAD

**Issue by mattapperson** [Microsoft/TypeScript#23427]
It seems that typescript does not allow for a class constructor to return a proxy that resolved to anything except what the class itself contains.

Expected:
```
class Foo<ProxiedThing> {
  adapter: any;
  constructor(adapter) {
    this.adapter = adapter;

    return <ProxiedThing> new Proxy(this, {
        get(target, name) {
           return this.adapter[name keyof ProxiedThing]
        }
     })
  }
}
var test = new Foo(
    new SomeOtherClass()
);
test.methodOnSomeOtberClass();
```

The desired effect here is pseudo composable enharatence on classes. This can be done of course in JS but I can only seem to make this work in TS by defining `[key: string]: any` on the `Foo` class to get things compiled but then lackes typechecking and hinting.

**Comment by andy-ms** [comment]
First: Try turning on `--noImplicitAny` -- `constructor(adapter)` implicitly makes `adapter: any`, so there's no way to perform type inference on `new Foo`.

Second, I we don't support returning a different type from a constructor, that is, `new Foo()` must return a `Foo`. It seems like you want `new Foo(new SomeOtherClass())` to return an object with the interface of `SomeOtherClass`. It might be better to write this as a `function createProxy<T>(value: T): T` instead of as a class.
