### ISSUE TITLE
TypeScript repository language incorrect on GitHub home page

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#2344]
![image](https://cloud.githubusercontent.com/assets/1106823/6637675/3a422818-c975-11e4-9203-4dd7aa0e66da.png)

-----------------------------------------------------------------------------------------------------------------------------
>
>

This might help: [My repository is marked as the wrong language](https://help.github.com/articles/my-repository-is-marked-as-the-wrong-language/)

**Comment by danquirk** [comment]
Yeah, we've looked into this before and unfortunately can't really fix it easily until there's some ability to just manually tag your repo language. We've submitted a few fixes to their code classifier tool so that other repos get classified as TypeScript correctly (ex a lot of crypto currency repos have .ts files that aren't TypeScript) but in our case the issue is that repos are classified by what makes up the majority of their repo by file count and for us that's .js baseline files from our test suites.

**Comment by RyanCavanaugh** [comment]
It looks like we can use .gitattributes to override this? https://github.com/github/linguist#troubleshooting

**Comment by RyanCavanaugh** [comment]
Fixed by #2394
