### ISSUE TITLE
[Feature Request] Type guard on conditional types

### ISSUE THREAD

**Issue by Cryrivers** [Microsoft/TypeScript#23493]
**Code**

```ts
type Test<V, M extends boolean> = { multiple?: M } & (
    M extends true ? { values: V[] } : { value: V }
)

function typeGuard<V, M extends boolean>(input: Test<V, M>) {
    if (input.multiple) {
        return input.values;
    } else {
        return input.value;
    }
}
```

**Expected behavior:**
`input.values` can be inferred in `if` block and `input.value` can be inferred in `else` block.

**Actual behavior:**
`Property 'values' does not exist on type 'Test<V, M>'.`
`Property 'value' does not exist on type 'Test<V, M>'.`

**Playground Link:** https://www.typescriptlang.org/play/#src=type%20Test%3CV%2C%20M%20extends%20boolean%3E%20%3D%20%7B%20multiple%3F%3A%20M%20%7D%20%26%20(%0D%0A%20%20%20%20M%20extends%20true%20%3F%20%7B%20values%3A%20V%5B%5D%20%7D%20%3A%20%7B%20value%3A%20V%20%7D%0D%0A)%0D%0A%0D%0Afunction%20typeGuard%3CV%2C%20M%20extends%20boolean%3E(input%3A%20Test%3CV%2C%20M%3E)%20%7B%0D%0A%20%20%20%20if%20(input.multiple)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20input.values%3B%0D%0A%20%20%20%20%7D%20else%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20input.value%3B%0D%0A%20%20%20%20%7D%0D%0A%7D

**Related Issues:**

**Comment by Cryrivers** [comment]
@Kingwl probably no plans yet as marked as `Working as intended`. For most cases you can use discriminant properties to solve the problem, which @jack-williams posted. My case is more complicated than his and it is unlikely to be done with discriminant properties. I'll post a demo if I have time.

Thanks.

**Comment by Kingwl** [comment]
@Cryrivers 
thanks for your suggestion 
I mean i'd like to try this if have not any plan or owner to fix this

**Comment by kpdonn** [comment]
@Kingwl 

I think the thing is that it can't be safely fixed due to @jack-williams example. The problem is that the types for `Test` can look like any of the following:

```ts
type Test<V, M extends boolean> = { multiple?: M } & (
    M extends true ? { values: V[] } : { value: V }
)

type TestTrue = Test<string, true> // { multiple?: true; } & { values: string[]; }
type TestFalse = Test<string, false> // { multiple?: false; } & { value: string; }
type TestBoolean = Test<string, boolean>
// ({ multiple?: boolean; } & { values: string[]; }) | ({ multiple?: boolean; } & { value: string; })
```
It's the third case that makes
```ts
let x: Test<string, boolean> = { multiple: true, value: "hello" };
```
a valid assignment and would make the proposed narrowing unsound.

Although as a side note you can force `Test<string, boolean>` to be a compile error by doing:

```ts
type XorBoolean<B extends boolean> = boolean extends B ? never : boolean
type Test2<V, M extends XorBoolean<M>> = { multiple?: M } & (
    M extends true ? { values: V[] } : { value: V }
)
type Test2True = Test2<string, true> // { multiple?: true; } & { values: string[]; }
type Test2False = Test2<string, false> // { multiple?: false; } & { value: string; }
type Test2Boolean = Test2<string, boolean> // error: type boolean does not satisfy constraint never
```
Still doesn't narrow in the original example however since type constraints like that aren't taken into account.

[Playground link of examples](https://www.typescriptlang.org/play/#src=type%20Test%3CV%2C%20M%20extends%20boolean%3E%20%3D%20%7B%20multiple%3F%3A%20M%20%7D%20%26%20(%0D%0A%20%20%20%20M%20extends%20true%20%3F%20%7B%20values%3A%20V%5B%5D%20%7D%20%3A%20%7B%20value%3A%20V%20%7D%0D%0A)%0D%0A%0D%0Atype%20TestTrue%20%3D%20Test%3Cstring%2C%20true%3E%0D%0A%2F%2F%20%7B%20multiple%3F%3A%20true%3B%20%7D%20%26%20%7B%20values%3A%20string%5B%5D%3B%20%7D%0D%0A%0D%0Atype%20TestFalse%20%3D%20Test%3Cstring%2C%20false%3E%0D%0A%2F%2F%20%7B%20multiple%3F%3A%20false%3B%20%7D%20%26%20%7B%20value%3A%20string%3B%20%7D%0D%0A%0D%0Atype%20TestBoolean%20%3D%20Test%3Cstring%2C%20boolean%3E%0D%0A%2F%2F%20(%7B%20multiple%3F%3A%20boolean%3B%20%7D%20%26%20%7B%20values%3A%20string%5B%5D%3B%20%7D)%20%7C%20(%7B%20multiple%3F%3A%20boolean%3B%20%7D%20%26%20%7B%20value%3A%20string%3B%20%7D)%0D%0A%0D%0Alet%20x%3A%20Test%3Cstring%2C%20boolean%3E%20%3D%20%7B%20multiple%3A%20true%2C%20value%3A%20%22hello%22%20%7D%3B%20%2F%2F%20valid%0D%0A%0D%0A%0D%0Atype%20XorBoolean%3CB%20extends%20boolean%3E%20%3D%20boolean%20extends%20B%20%3F%20never%20%3A%20boolean%0D%0A%0D%0Atype%20Test2%3CV%2C%20M%20extends%20XorBoolean%3CM%3E%3E%20%3D%20%7B%20multiple%3F%3A%20M%20%7D%20%26%20(%0D%0A%20%20%20%20M%20extends%20true%20%3F%20%7B%20values%3A%20V%5B%5D%20%7D%20%3A%20%7B%20value%3A%20V%20%7D%0D%0A)%0D%0A%0D%0Atype%20Test2True%20%3D%20Test2%3Cstring%2C%20true%3E%0D%0A%2F%2F%20%7B%20multiple%3F%3A%20true%3B%20%7D%20%26%20%7B%20values%3A%20string%5B%5D%3B%20%7D%0D%0A%0D%0Atype%20Test2False%20%3D%20Test2%3Cstring%2C%20false%3E%0D%0A%2F%2F%20%7B%20multiple%3F%3A%20false%3B%20%7D%20%26%20%7B%20value%3A%20string%3B%20%7D%0D%0A%0D%0Atype%20Test2Boolean%20%3D%20Test2%3Cstring%2C%20boolean%3E%0D%0A%2F%2F%20error%3A%20type%20boolean%20does%20not%20satisfy%20constraint%20never%0D%0A%0D%0Afunction%20typeGuard2%3CV%2C%20M%20extends%20XorBoolean%3CM%3E%3E(input%3A%20Test2%3CV%2C%20M%3E)%20%7B%0D%0A%20%20%20%20if%20(input.multiple)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20input.values%3B%20%2F%2F%20still%20not%20narrowed%20though%0D%0A%20%20%20%20%7D%20else%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20input.value%3B%0D%0A%20%20%20%20%7D%0D%0A%7D)
