### ISSUE TITLE
Generator functions incorrectly infer a return type as literal types

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#23537]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Search Terms:** 

**Code**

```ts
function* g() {
  yield;
  return 0;
}
```

**Expected behavior:**

Iterator value type is `number | undefined`.

**Actual behavior:**

Iterator value type is `0 | undefined`.

**Playground Link:**  

**Related Issues:**

**Comment by SimonMeskens** [comment]
Not a bug, `0 | undefined` is the correct type. `number` would imply it can return other numbers besides 0, which it cant, it can only return 0, so the type reflects that.

**Comment by rbuckton** [comment]
We need to clarify in which cases we should widen.

**Comment by falsandtru** [comment]
I believe functions and generator functions should should infer the same return type as follows. These two `T` generic types should be the same type when they are returned the same type. At least all literal values shouldn't be literal types without type casting.

```ts
function <T>f(): T {
  return <T or its subtype>;
}
function* g<T, U>(): Iterator<T | U> {
  yield <U or its subtype>;
  return <T or its subtype>;
}
```

**Comment by rbuckton** [comment]
Our behavior today is "correct", and is based on a long-standing approach to how we handle types in a function, in that we _do not widen a union of literal types_:

```ts
// function f1(): number;
function f1() {
  return 1; // `1`
}

// function f2(a: boolean): number;
function f2(a: boolean) {
  if (a) return Number.MAX_VALUE; // `number`
  return 2; // `2`
}

// function f3(a: boolean): 1 | 2;
function f3(a: boolean) {
  if (a) return 1; // `1`
  return 2; // `2`
}
```

- In `f1`, we widen to `number` as `1` is a "unit type" (i.e. a lone literal type).
- In `f2`, we widen to `number` as `1 | number` "widens" only due to subtype reduction.
- In `f3`, we do *not* widen as `1 | 2` has no subtype reduction and is not a "unit type".

We do the same thing for generators:

```ts
// function g1(): IterableIterator<number>;
function* g1() {
  yield 1; // `1`
}

// function g2(): IterableIterator<number>;
function* g2() {
  yield Number.MAX_VALUE; // `number`
  yield 2; // `2`
}

// function g3(): IterableIterator<1 | 2>;
function* g3() {
  yield 1; // `1`
  yield 2; // `2`
}
```

- In `g1`, we widen to `number` as `1` is a "unit type".
- In `g2`, we widen to `number` as `1 | number` "widens" only due to subtype reduction.
- In `g3`, we do *not* widen as `1 | 2` has no subtype reduction and is not a "unit type".

Where it "seems" like there's an issue is when you mix `yield` and `return` in a generator, as today we concatenate `yield` and `return` types for `T` (as they both flow to the `value` property of an `IteratorResult<T>`):

```ts
// function h1(): IterableIterator<number>;
function* h1() {
  yield 1; // `1`
  return;
}

// function h2(): IterableIterator<number>;
function* h2() {
  yield Number.MAX_VALUE; // `number`
  return 2; // `2`
}

// function h3(): IterableIterator<1 | 2>;
function* h3() {
  yield 1; // `1`
  return 2; // `2`
}
```

- In `h1`, we widen to `number` as `1` is a "unit type" and a `return` lacking an expression does not contribute a type.
- In `h2`, we widen to `number` as `1 | number` "widens" only due to subtype reduction.
- In `h3`, we do *not* widen as `1 | 2` has no subtype reduction and is not a "unit type".

This is further complicated by something like original example:

```ts
// with strictNullChecks:
//   function g(): IterableIterator<0 | undefined>; 
// without strictNullChecks:
//   function g(): IterableIterator<number>; 
function* g() {
  yield; // `undefined`
  return 0; // `0`
}
```

- When `strictNullChecks` is *enabled*:
  - In `g`, we do *not* widen as `0 | undefined` has no subtype reduction and is not a "unit type".
- When `strictNullChecks` is *disabled*:
  - In `g`, we do *not* initially widen literal types as `0 | undefined` has no subtype reduction and is not a "unit type", but we *do* widen to `number` when we remove `undefined` and end up with `0` as a "unit type".

It _seems_ like the non-`strictNullChecks` behavior is correct, until you factor in an alternate `return` (like in `f3` above):

```ts
// with strictNullChecks:
//   function g(a: boolean): IterableIterator<0 | 1 | undefined>; 
// without strictNullChecks:
//   function g(a: boolean): IterableIterator<0 | 1>; 
function* g(a: boolean) {
  yield; // `undefined`
  if (a) return 1; // `1`
  return 0; // `0`
}
```

In the end, our behavior is "correct", if possibly surprising.

In the long term, we need to consider a more "correct" version of `Iterator` and `IteratorResult` that keeps the `yield` and `return` types distinct, something like this:

```ts
interface Iterator<TYield, TReturn = TYield> {
  next(value?: any): IteratorResult<TYield, TReturn>;
  throw?(value?: any): IteratorResult<TYield, TReturn>;
  return?(value: TReturn): IteratorResult<TYield, TReturn>;
}
interface IteratorYieldResult<TYield> {
  value: TYield;
  done: false;
}
interface IteratorReturnResult<TReturn> {
  value: TReturn;
  done: true;
}
type IteratorResult<TYield, TReturn = TYield> = IteratorYieldResult<TYield> | IteratorReturnResult<TReturn>;
```

Then we could treat the `yield` and `return` types distinctly. Unfortunately, such a type would be a considerable breaking change.
