### ISSUE TITLE
Refactoring to convert to "named parameters"

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#23552]
It would look something like this

![converttonamedparameters](https://user-images.githubusercontent.com/972891/39023162-e2d99498-43ed-11e8-93a2-14287765aad8.gif)

**Comment by DanielRosenwasser** [comment]
CC @rauschma @appsforartists in case you want to 👍

**Comment by rauschma** [comment]
Apologies for being ungrateful: this doesn’t reflect how I use this pattern – I don’t see the parameters as a whole, I see each parameter individually. As a work-around, I inline the type and don’t define it externally.

Let me try, one last time, to convince you of the usefulness of a better notation for destructuring (nested destructuring will profit, too!). The following is an extreme example, but there are many similar functions in my code:

```typescript
function slidesToNodeTree(
  {conf, configShowoff, inputDir, slideDeckDir, slideFileName, parentPartNode, visitedSlideFiles}
  : {conf: ConfigSlideLink, configShowoff: ConfigShowoff, inputDir: string,
    slideDeckDir: ServePath, slideFileName: string, parentPartNode: PartNode,
    visitedSlideFiles: SlideFileDesc[]}) {
  ···
}
```

With a better notation:

```typescript
function slidesToNodeTree(
  { conf as ConfigSlideLink, configShowoff as ConfigShowoff, inputDir as string,
    slideDeckDir as ServePath, slideFileName as string, parentPartNode as PartNode,
    visitedSlideFiles as SlideFileDesc[]}) {
  ···
}
```

Alternatively:

```typescript
function slidesToNodeTree(
  { (conf: ConfigSlideLink), (configShowoff: ConfigShowoff), (inputDir: string),
    (slideDeckDir: ServePath), (slideFileName: string), (parentPartNode: PartNode),
    (visitedSlideFiles: SlideFileDesc[])}) {
  ···
}
```

Note how, in the last two examples, you actually see parameters with names (vs. a single type for all parameters). The first example looks messy, the last two examples don’t.

If you have ever used a programming language with named parameters and liked them there – isn’t this a compelling use case? Given [the thumbs-up at a recent comment of mine](https://github.com/Microsoft/TypeScript/issues/7576#issuecomment-370196012), there are quite a few people who agree.

This is the only aspect of my plain JavaScript code that became less usable after I moved to TypeScript.

**Comment by appsforartists** [comment]
I love that you're exploring this, but I agree with @rauschma.

I think there's a bit of a cargo-cult bias in the TS community to always prefer interfaces (because they can be extended).  Type literals seem like a more appropriate model for the kwargs pattern, because they allow users to treat each named argument individually.

If a third party made a "convert to named arguments" command, I would probably find it useful to be able to write function signatures normally and then convert them to an interface/type literal.  However, I'd rather the language supported setting the type for a named arg adjacent to the declaration of its name and default value.  It's both hard to read and cumbersome to maintain when the types are separated from the rest of the definition.

**Comment by cancerberoSgx** [comment]
This refactor also must refactor all references to the method in the whole project right ? But a very helpful refactor , in my experience, happened many times when an API signature that needs to be backwards compatible, is defined with multiple params and then you keep adding parameters to implement new features or even change parameter type to OR, like existing: PreviousType|NewSemanticType....

**Comment by Kingwl** [comment]
>  This refactor also must refactor all references to the method in the whole project right ?   

IMO, it should

**Comment by mohsen1** [comment]
This is great! 

Have you thought about the default arguments with no types? Would you infer types there?

```ts
function foo(a = 1, b?: string) 
```

Also would it work in constructor function with `private` or `public` keyword? I think it won't, right?

```ts
class Foo {
  constructor(private a: string) {}
}
```

where would you generate a type name if function is anonymous?

```ts
function (a = 1, b?: string){}.call(1)
```

**Comment by AnyhowStep** [comment]
This would be super helpful to me, even if others would rather a new destructuring syntax for function parameters.

So, if the proposed refactoring somehow loses favour over new destructuring syntax, I would still like for this particular one to be implemented.

I personally use interfaces instead of inlining, especially for large projects. And projects I write that get consumed by others.

I've had to wrap a function many times. And if the library doesn't have those function arguments as an interface, then *I* have to copy-paste code instead of just using an interface that should already be there.

People like to think of interfaces as being "code duplication". But in the big picture, not having those interfaces causes code duplication.

**Comment by Kingwl** [comment]
ummmmmm, I'd like to work on it

**Comment by aleksey-bykov** [comment]
Options your say, why not Params?

**Comment by DanielRosenwasser** [comment]
`Params` is fine too as long as the refactoring provides a rename location on the generated type. @Kingwl this one might involve more work than other refactorings, but nobody's started working on it yet, so go for it!

**Comment by tentreescantbeatme** [comment]
@rauschma then you have two syntaxes to be maintained. Because your version is not compatible with the current version that allows sharing of interfaces between methods. So you get an inconsistency there, because you can't just abolish the current syntax because of exactly this reason.

**Comment by RyanCavanaugh** [comment]
@Kingwl we've decided to have our intern @gabritto implement this for her project - apologies if you've already started on it

**Comment by Kingwl** [comment]
@RyanCavanaugh 
Please feel free, Actually, I haven't started that work

**Comment by DanielRosenwasser** [comment]
For the record, I'd like to not continue discussion around new syntax here. This feature could theoretically work with that syntax anyway so it shouldn't have any bearing on the implementation.

**Comment by RyanCavanaugh** [comment]
✨ 🚲 🏠 ✨ 

**Naming poll**! Vote:
 * 🎉 "Convert to named parameters"
 * ❤️ "Convert to parameters object"
 * 👎 Other (specify)

**Comment by OliverJAsh** [comment]
I call them named parameters, but just throwing another idea out there: "convert parameters to destructed object"

**Comment by ShawnTalbert** [comment]
I wish we wouldn't encourage the pattern of making functions take a single object - it thwarts currying.

**Comment by tjpalmer** [comment]
I know @rauschma said he'd stop and seems to have kept his word, but he's absolutely right that doesn't express what people want to express.

Have people discussed using `is` yet? Example from the top using this syntax follows:

```typescript
function foo({a is number, b is string, c? is boolean}): void {
  a; b; c
}
```

And the TypeScript code base itself is chock full of long lists of parameters with optionals etc. Empirical evidence for where this could help.

**Comment by brasten** [comment]
> Have people discussed using `is` yet? Example from the top using this syntax follows:
> 
> ```ts
> function foo({a is number, b is string, c? is boolean}): void {
>   a; b; c
> }
> ```

There were some discussions about `as` in an earlier issue -- mostly involving concerns about introducing a new keyword in a very specific context. I suspect `is` would have the same complaints.

I haven't thought through every issue, but I'm wondering about using `:` twice, where the renamed variable name can be optional. So instead of `[object_key]: [variable_name] = [default_value]` you end up with `[object_key]: [variable_name]: [type] = [default_value]`. This kind of makes sense since you're typing the variable name, rather than the object key, anyway.

So the most verbose version of this would be:
```ts
function someFunc({ foo: bar: string = 'default' }): void {
  bar;
}
```

... whereas the common case would be:

```ts
function someFunc({ foo:: string }): void {
  foo;
}
```

**Comment by AnyhowStep** [comment]
> I wish we wouldn't encourage the pattern of making functions take a single object - it thwarts currying.

There are cases where it is beneficial to take a single object with many parameters.

For example, that object can be an immutable data structure and the function is just performing some operation on it and returning a new instance of the data structure.

In some cases, those data structures can have dozens of properties... You're not really suggesting we curry in those cases as well, right?

**Comment by jasonwilliams** [comment]
@DanielRosenwasser what's the reason this was closed?
I was looking for this feature earlier and came across this issue.

**Comment by RyanCavanaugh** [comment]
@jasonwilliams it was closed because it was implemented

**Comment by uglycoyote** [comment]
I love this refactoring, but is there a a reason why it does not work on constructors? 

 I sometimes find myself creating a class where the number of constructor parameters grows out of control, with too many optional ones and I wished that I had instead made one "config" or "options" interface that can be passed in to the constructor.   The advantages being:

1) the constructor calls would be clearer, with objects passed in which explicitly have {key:value, key:value} rather than just a bunch of unnamed values passed in as constructor parameters, and 
2) it makes it easier/cleaner to deal with a lot of optional parameters, since they can simply be omitted from the configuration object instead of all of the constructor parameters needing to be passed in the correct order (avoiding the awkward situation where you need to pass a dummy value to the 4th optional parameter so that you can a desired value to a 5th optional parameter)

I notice that @mohsen1 asked about using it on constructors earlier in this thread and @DanielRosenwasser  kiboshed the idea unceremoniously (simply saying "It probably should not for now.").  Maybe that's just because it was early on in the development of this refactoring and you all were trying to keep things as simple as possible?   What extra complications do using this for constructors create that aren't present for functions?

Since this issue is old and closed should I open a new issue called _"Make 'Convert parameters to destructured object' refactoring work for constructors"_?

**Comment by RyanCavanaugh** [comment]
Yes, please open a new issue. Thanks!

**Comment by marco2216** [comment]
If anyone tried this and wonder why it doesn't work, it might be because you are selecting multiple lines. 
Placing the cursor on just one parameter in a function and then opening the refactor menu should do it.

**Comment by Axelhijacker76** [comment]
> I love this refactoring, but is there a a reason why it does not work on constructors?
> 
> I sometimes find myself creating a class where the number of constructor parameters grows out of control, with too many optional ones and I wished that I had instead made one "config" or "options" interface that can be passed in to the constructor. The advantages being:
> 
> 1. the constructor calls would be clearer, with objects passed in which explicitly have {key:value, key:value} rather than just a bunch of unnamed values passed in as constructor parameters, and
> 2. it makes it easier/cleaner to deal with a lot of optional parameters, since they can simply be omitted from the configuration object instead of all of the constructor parameters needing to be passed in the correct order (avoiding the awkward situation where you need to pass a dummy value to the 4th optional parameter so that you can a desired value to a 5th optional parameter)
> 
> (I guess these are the same reasons why it's useful on functions, really)
> 
> I notice that [@mohsen1](https://github.com/mohsen1) asked about using it on constructors earlier in this thread and [@DanielRosenwasser](https://github.com/DanielRosenwasser) kiboshed the idea unceremoniously (simply saying "It probably should not for now."). Maybe that's just because it was early on in the development of this refactoring and you all were trying to keep things as simple as possible? What extra complications do using this for constructors create that aren't present for functions?
> 
> Since this issue is old and closed should I open a new issue called _"Make 'Convert parameters to destructured object' refactoring work for constructors"_?





https://stackdev.space/questions/what-strategies-can-i-employ-to-streamline-my-code-in-c-and-prevent-redundancy-when-refactoring-similar-functions

**Comment by uglycoyote** [comment]
> https://stackdev.space/questions/what-strategies-can-i-employ-to-streamline-my-code-in-c-and-prevent-redundancy-when-refactoring-similar-functions

You seem to have been replying to my post, @Axelhijacker76,  but I'm not clear how your link was intended to help.   

The answer in the link suggests using parameters in functions rather than writing a bunch of differently-named functions which could trivially be a single function with a parameter.  Using parameters instead a having a bunch of similar copy-pasted slightly-different functions is fantastic advice of course, and is something that I do a lot of.   

Adding more and more parameters, while better than writing many redundant functions, leads to the situation that I was described, that this refactoring is designed to help:   a function (or constructor) which eventually gets too many parameters, not all of which are relevant in all situations, and they are annoying to have to pass all in the correct order,  to plumb through multiple levels of the call stack, etc, and would be more simply expressed as a single configuration object which can be initialized to a decent set of defaults and overridden by setting the interesting members by name when needed.
