### ISSUE TITLE
IE11 does not support "startsWith" property 

### ISSUE THREAD

**Issue by wanliyunyan** [Microsoft/TypeScript#23621]
this is my tsconfig 
 "target": "ES2016", 
"module": "es2015",    
"lib": [ "es5", "es6", "es2015", "es7", "es2016", "es2017", "es2018", "esnext", "dom","es2015.core"],    

the lib has include so many,but startsWith is still not supported......
I have already seen https://github.com/Microsoft/TypeScript/issues/6468 and https://github.com/Microsoft/TypeScript/issues/12383

ts version : 2.8.3

The error occurred in lib.js

**Comment by j-oliveras** [comment]
Your config says that you will use es6 (this is the version that adds this method). Typescript don't check if the destination will support any method (your target is es2016, that is not supported by IE11). You should [use core-js or something like that](https://www.npmjs.com/package/core-js).

IE11 only supports until es5.

**Comment by wanliyunyan** [comment]
I change the target to es5, The errors still occurred in lib.js, Webpack package “antd” to "lib.js", It seems that I cannot change the compilation of webpack. "startsWith"is not what I code

**Comment by j-oliveras** [comment]
Is [this the tool](https://www.npmjs.com/package/antd) that you use? If yes, please read the [compatibility section](https://ant.design/docs/react/getting-started#Compatibility). If not, you need to use a polyfill of features needed like core-js, es5-shim or es6-shim.

Anyway, I don't think this is an issue of Typescript.

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Next time, please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!

**Comment by wanliyunyan** [comment]
@RyanCavanaugh @j-oliveras Thank you for your answers.There are always issues with the use of Stack Overflow in the Chinese network,I'm really sorry!
