### ISSUE TITLE
Trying to type destructured params using JSDoc throws

### ISSUE THREAD

**Issue by zombie** [Microsoft/TypeScript#23652]
**Code**

```js
/**
 * @param {object} options
 * @param {number} options.size
 * @param {string} [options.colour]
 */
function widget({size, colour = "red"}) {
  //
}
```

**Actual behavior:**
Type-checking a file with the above code throws
```
[js] JSDoc '@param' tag has name 'options', but there is no parameter with that name.
```

**Comment by mhegazy** [comment]
The example in the OP should be working in latest. the example in the second comment is not correct, since the function does not have a parameter called `size` or `colour`.

Try it with `typesript@next`. VSCode ships with an older version of TypeScript. Please see [Using Newer TypeScript Versions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) documentation for more details on updating your VSCode to use a different version of TypeScript.

**Comment by zombie** [comment]
Uh, I did use a local build, but it was still checked out to an older tag because of #23479.

Thanks and sorry for the spam.
