### ISSUE TITLE
`keyof` causes `Cannot find global type 'Symbol'`

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#23778]
**TypeScript Version:** 2.9.0-dev.20180430

**Code**

```ts
let x: keyof { x: number };
```

Compile with `--lib es5`.

**Expected behavior:**

No error.

**Actual behavior:**

`error TS2318: Cannot find global type 'Symbol'.`

Discovered in `moonjs` on DefinitelyTyped.

**Comment by andy-ms** [comment]
Sorry, looks like it requires `tsc a.ts --target esnext --lib es5 --noEmit`.

**Comment by weswigham** [comment]
As it turns out, the error only appears on the command line, and not under test. Adding `skipDefaultLibCheck` removes the error - The error only appears on the command line because it's an error in the lib. The error is actually expected (and should have been there before) because we report an error on missing `Symbol` when `languageVersion >= ScriptTarget.ES2015`.

Now, the reason it _is_ new is because previously all references to `symbol` in the es5 lib were in function callbacks (which have checking deferred until use, and would require some hoops to extract and get the apparent type of), but once `PropertyKey` got moved to the es5 lib (and incorporated into the base `Object` type), the requisite declarations can get checked whenever you get the apparent type of something (that is to say: often).

@mhegazy You could argue that this is expected.... or we could just silently remove the error on being unable to find a global `Symbol` (for any `target`)... or we could split up `PropertyKey` between the es5 and es2015 libs, doing something like:

lib.es5.d.ts:
```ts
interface PropertyKeyTypes {
    string: string;
    number: number;
}

type PropertyKey = PropertyKeyTypes[keyof PropertyKeyTypes];
```

lib.es2015.core.d.ts:
```ts
interface PropertyKeyTypes {
    symbol: symbol;
}
```

thoughts?

**Comment by mhegazy** [comment]
One option is to move the definition of `Symbol` to `es5.d.ts`. it makes sense to that `symbol` now creeps into many more scenarios than in the past, even in ES5/ES3 targets. The value `Symbol` would not available unless you are in ES2015 though.

**Comment by weswigham** [comment]
@mhegazy an empty symbol interface has about the same effect as just removing the error, except people actually get a (useless) `Symbol` in completions.

**Comment by mhegazy** [comment]
The error guards against ppl using a wrong version of the library really. like with `--noLib`. either way, we injected `symbol` in the program in ES5 seems strange to error if `Symbol` is not defined after that.
