### ISSUE TITLE
Type argument inferred as subtype when supertype is necessary

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#23790]
**TypeScript Version:**  2.9.0-dev.20180430

**Code**

```ts
declare function flatMap<T, U>(array: ReadonlyArray<T> | undefined, mapfn: (x: T) => U | ReadonlyArray<U>): ReadonlyArray<U>;

interface A { a: number; }
interface B extends A { b: number; }

declare const bArr: ReadonlyArray<B>;
declare const cond: boolean;
declare const aArr: ReadonlyArray<A>;
flatMap(aArr, a => cond ? bArr : a);
```

**Expected behavior:**

No error -- type argument inferred as `A`.

**Actual behavior:**

Type argument inferred as `B`.
```
src/a.ts:9:15 - error TS2345: Argument of type '(a: A) => A | B[]' is not assignable to parameter of type '(x: A) => B | B[]'.
  Type 'A | B[]' is not assignable to type 'B | B[]'.
    Type 'A' is not assignable to type 'B | B[]'.
      Type 'A' is not assignable to type 'B[]'.
        Property 'length' is missing in type 'A'.

9 flatMap(aArr, a => cond ? bArr : a);
```

**Related Issues:**

**Comment by mhegazy** [comment]
The issue happens when we are inferring from `A | B[]` to `U | U[]` from the return type of the lambda.

Since there are no common types, we will infer to `U[]` from `A | B[]` then again to `U` from `A | B[]`. the first inference will result in `B`, the second results in `A | B[]`, but then we decide to ignore it since it is a naked type parameter in a union and we already have a better inference. which is the right thing to do.

I guess the intuitive thing that we have missed here is when we are inferring a union to a union, we only carve off types that are common. but if we take the common type references into account, we should be inferring to `U[]` from `B[]` and `U` from the rest of the union in this case `A`.

**Comment by mhegazy** [comment]
The suggestion here is to have smarter logic to inferring from a union/intersection to another union/intersection by removing pairs of types from the source and the target that seem "similar" and applying inference on them, then applying the normal union/intersection inference logic on the rest of the types.

**Comment by RyanCavanaugh** [comment]
This works now

**Comment by janyawat** [comment]
leave comment
