### ISSUE TITLE
Better support for 'defaultProps' in JSX

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#23812]
This proposal aims to fix problems around React's use of `defaultProps`, which TypeScript has trouble understanding today.

# Background

Today, React has a concept called `defaultProps`; these are props that an external user of a component may consider optional, but are *always* present in the component definition.

```ts
export class Greeting extends React.Component {
  static defaultProps = {
    name: 'stranger'
  }

  render() {
    return (
      <div>Hello, {this.props.name}</div>
    )
  }
}

let myElement1 = <Greeting name="Daniel!"/>; // <div>Hello, Daniel!</div>
let myElement2 = <Greeting />;               // <div>Hello, stranger</div>
```

Unfortunately, TypeScript `--strictNullChecks` users who want to take advantage of this are in a tough spot.
They can either specify these props as optional and assert that defaulted properties are present internally,

```ts
export interface GreetingProps {
  name?: string
}

export class Greeting extends React.Component<GreetingProps> {
  static defaultProps = {
    name: 'stranger'
  }

  render() {
    // Notice the non-null assertion!
    //                           | |
    //                           | |
    //                           \ /
    //                            V
    return (
      <div>Hello, {this.props.name!.toUpperCase()}</div>
    )
  }
}
```

or they can jump through levels of indirection:

```ts
export interface GreetingProps {
  name?: string
}

// Notice we are using a 'const' declaration here!
export const Greeting: React.Component<GreetingProps> = class extends React.Component<GreetingProps> {
  static defaultProps = {
    name: 'stranger'
  }

  render() {
    return (
      <div>Hello, {this.props.name!.toUpperCase()}</div>
    )
  }
}
```

# Proposals

## Using resolution semantics of the JSX factory

Users can already emulate this behavior with `React.createElement`: https://tinyurl.com/y9jbptt9

```ts
// React-like API

export interface Component<P> {
    props: P;
}

export interface ComponentClass<P, Defaults = void> {
    new(props: P): Component<P>;
    defaultProps: Defaults;
}

export interface Element<P> {
    type: string | ComponentClass<P>;
    props: P;
}

// Some additions

type Defaultize<T, Defaults> =
    & Partial<Pick<T, Extract<keyof T, keyof Defaults>>>
    & Pick<T, Exclude<keyof T, keyof Defaults>>;

declare function createElement<Props, Defaults>(
    type: ComponentClass<Props, Defaults>,
    props: Defaultize<Props, Defaults> | null):
    Element<Props>

// Now comes your code...

class FooComponent {
    props: { hello: string, world: number };
    static defaultProps: { hello: "hello" };
}

// works: 'hello' got defaulted
createElement(FooComponent, { world: 100 });

// error: missing 'world'
createElement(FooComponent, { hello: "hello" });
```

In theory, just passing the right data to the JSX factory should do the work for us.

However, there are some issues:

1. The `Defaultize` type is hard to read.
2. TypeScript treats the object literal in `createElement` as an inference site, and when inference fails, users get no completions for props. It's not ideal in the general case, but the goal is to continue to give a good experience in JSX.

## Add a new type in the JSX namespace

![](https://i.imgur.com/BsMhHtq.png)

We could potentially add a new field called `ComponentDefaultPropNames` in `JSX` which would either be a union of literal types or possibly an object type whose property names describe the respective names that `defaultProps` could have:

```ts
namespace JSX {
    export type ComponentDefaultPropNames = "defaultProps";
}
```

When writing out a JSX tag for a component, `JSX.ComponentDefaultPropNames` is looked up on the type of the tag name to determine which properties should be considered optional.

So for example:

```ts
<TagName {...someObject}>
```

If `TagName` expects props with the type `Props`, TypeScript can relate `typeof someObject` to some combination of `Props` and `(typeof TagName)[JSX.ComponentDefaultPropNames]`.

# Potential issues

Under either proposal, *some type* is inferred from the type of the component's `defaultProps` property.
Since [React's `.d.ts` files currently define `defaultProps` to be a `Partial<P>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/01e0ffdbab16b15c702d5b8c87bb122cc6215a59/types/react/index.d.ts#L329), where `P` is the type parameter for the type of props, we need to avoid that from making all props optional.

To avoid issues here, we could say that *only required properties* on `defaultProps` satisfy a JSX element's type. So for example:

```ts
interface MyProps {
  name: string;
  age: number;
}

class MyComponent extends React.Component<MyProps> {
  render() {
    return <div>My name is {this.props.name} and I am {this.props.age} years old.</div>;
  }

  static defaultProps: { name?: string, age: number } = {
    name: "Daniel",
    age: 26,
  }
}

// error: 'name' is still considered required
let x = <MyComponent />

// works! 'age' is optional because it was definitely present in the type of 'defaultProps'.
let y = <MyComponent name="Daniel" />
```

**Comment by weswigham** [comment]
> namespace JSX {
    export type ComponentDefaultPropNames = "defaultProps";
}

No. We're better than this now. Instead, for your consideration:

```ts
namespace JSX {
    export type LibraryManagedProps<TComponent, TProps> = /*...*/
}
```

which can be defined as:
```ts
namespace JSX {
    export type LibraryManagedProps<TComponent, TProps> = 
        TComponent extends { defaultProps: infer D; propTypes: infer P; } ? Defaultize<TProps & InferedPropTypes<P>, D>
        : TComponent extends { defaultProps: infer D } ?  Defaultize<TProps, D>
        : TComponent extends { propTypes: infer P } ? TProps & InferedPropTypes<P>
        : TProps;
}
```

where `InferedPropTypes` is a type the maps from the `propTypes` shapes to normal types. This could handle `defaultProps` _and_ `propTypes`, and is a little more aligned with the current goal of attempting to remove the JSX namespace completely (as these are closer to the mechanics the factory function would need to use). `TComponent` is the static class or sfc, and `TProps` is the `props` taken from that component or SFC (so either the `props` member or first argument). Technically `TProps` is derivable from `TComponent`... but, convenience (also we do this to handle SFC overloads, which are not derivable right now and are the major stopping block from using the factory).

We shouldn't tie functionality to strings or properties anymore - we don't need to (we have generic index types now - the property references were a hack for before we had them). And "Defaultize is ugly" isn't really a great argument against it, because that _exact type_ would need to be _hardcoded_ into the checker to make the property-name thing work (except even uglier because it'd have no alias, so would be represented in declaration emit and quick info with no aliasing and a ton of nested conditionals), except it wouldn't be able to be recoded if/when the JSX library's functionality changes - it would hardcode the compiler to the current version and implementation of react (specifically), which should be an nongoal.

**Comment by Cryrivers** [comment]
One thing I'd like to mention is that it doesn't support generic components yet, which has nothing to do with `LibraryManagedAttributes`, but because TypeScript doesn't support high order kinds.

So if your component has `Props<T>`, the generic type `T` would become `undefined` or `any`(I didn't find the pattern here, but I saw both in error messages) when it's passed to `TProps`.

**Comment by inomdzhon** [comment]
`typescript` version **3.0.3**
`@types/react` version **16.4.13**

defaultProps don't work with HOCs  =\

*HOCs*

```
import * as React from 'react';
import { Subtract } from 'utility-types';

// services
import { TimeService } from './TimeService';

export type WithServerTimePropsType = {
  serverTime: number;
};

function withServerTime<T extends WithServerTimePropsType>(
    Child: React.ComponentType<T>,
  ): React.ComponentType<Subtract<T, WithServerTimePropsType>> {
    class WithServerTime extends React.Component<Subtract<T, WithServerTimePropsType>, {}> {
      static displayName: string = `WithServerTime(${Child.displayName || Child.name})`;

      render(): React.ReactNode {
        return <Child serverTime={timeService.serverTime} {...this.props} />;
      }
    }
    return WithServerTime;
  };
```

*Component with `defaultProps`*
```
type PropsType = {
  className?: string;
  timeFormat: TIME_FORMAT;
};

class CountDown extends React.Component<PropsType> {
  static defaultProps: PropsType = {
    timeFormat: 'hms',
  };

  render(): React.ReactNode { ... }
}
```

*Using*
```
const HOCCountDown = withServerTime(CountDown);

// error TS2322: Type '{}' is not assignable to type 'Pick<PropsType, "className" | "timeFormat">'.
  Property 'timeFormat' is missing in type '{}'.
<HOCCountDown />
```

However I indicated `timeFormat` is optional.

**Comment by weswigham** [comment]
@inomdzhon You did not _actually_ declare `timeFormat` as optional for your `HOCCountDown`; your HoC function returns `React.ComponentType<Subtract<T, WithServerTimePropsType>>` - that will not implicitly passthru the specific `defaultProps` from the input type (`React.ComponentType` only asserts that the defaults are bounded to the props, not what the defaults actually _are_). In fact, the component you return will happily override whatever defaults the input component specified with no defaults at all. Now, implementation-wise your code is ok, since the inner component's defaults will pickup what your component missed and you otherwise don't use the props, _but_ your type annotations don't claim this in any way! So your input may have defaults, but your HoC wrapper doesn't care about that or inspect that, and your HoC wrapper doesn't claim to persist the defaults of a component it is passed (just the props)! So your types are claiming to construct a component with the same props as the input component uses, but without the same defaults. You need to derive your output `defaultProps` member type from the input's `defaultProps` member type to do that (or, alternatively, pull in the defaulted props from the input type into your component instead of the input props by using the `LibraryManagedAttributes` implementation from react or an equivalent your write yourself). The source of this complexity is a need to be mindful of the difference between the constructor-arguments-props-type and the component-internal-props-type for a component. The generic parameter is the component-internal type, while the public type is derived from that via react internals (represented in typespace by the `LibraryManagedAttributes` type constructor).

Although it's probably worth mentioning that even if you alter your component to get that right, you _may_ need to be on nightly for it to work, since we partially fixed a related issue in intersected types a few days ago.

**Comment by madou** [comment]
@weswigham any chance for a code example of how that could work? :)

**Comment by inomdzhon** [comment]
@madou woh, it's work 😲...unless this error 🤔

**Comment by maschino** [comment]
@madou I've encountered the same issue - "solved" it by casting the passed component back to a React.ComponentType. You can see it in action here: [withForm.tsx](https://github.com/environment-agency-austria/react-ocean-forms/blob/f70a94ca672fe79f68f5ca6699cb4bcdbddde4ae/src/components/withForm/withForm.tsx#L32)

It works, but it really feels more like an ugly workaround. I'd appreciate it if someone would find a nicer solution!

**Comment by inomdzhon** [comment]
@weswigham hi) what you think about @maschino solution for "provide" defaultProps for HOC?
