### ISSUE TITLE
Auto-importing modules as namespaces?

### ISSUE THREAD

**Issue by rauschma** [microsoft/TypeScript#23830]
I’m not sure what the best way is to fix this, but: auto-importing is incredibly helpful. Alas, it only works for named exports. However, imports such as the following are frequent in Node.js and there, you get no help:

```ts
import * as path from 'path';
```

Possible solution: offer an auto-import if:

* there is an unknown `foo` followed by a dot and
* `foo` is the base name of a module.

**Comment by RyanCavanaugh** [comment]
Can you clarify what you're typing and when you'd expect this to show up?

**Comment by rauschma** [comment]
* Typing: `path.` (`path` being an unknown identifier).
* Quick fix: auto-import `'path'`.

**Comment by andy-ms** [comment]
If something is *already* imported as a namespace, we ought to (but don't currently) prefix a completion with the namespace name, rather than adding a new named import.

**Comment by rauschma** [comment]
> As a second issue we might consider adding an option to always make a namespace import even if one doesn't already exist.

I don’t think that that would be useful:
* With `path`, both named imports and namespace imports are common.
* My thinking usually starts with: “something in module `path`”. Therefore, I’d prefer it if an IDE would namespace-import `path` for me when I first mention its name.

**Comment by mhegazy** [comment]
So the suggestion here is to offer the names of modules in the completion list with an additional action to import them? i.e. `path` would show up as a completion entry in the global scope.

**Comment by rauschma** [comment]
Yes! But I’m not sure what you mean by “in the global scope”. `path` would be global-ish, but the suggestion would appear anywhere, independent of scope.

**Comment by rauschma** [comment]
Oh, and it could be complemented by a quick fix offering to namespace-import `path` whenever that identifier is ever unknown anywhere.

**Comment by mhegazy** [comment]
My only worry is the amount of unrelated names we put in the completion list.

**Comment by DanielRosenwasser** [comment]
> My only worry is the amount of unrelated names we put in the completion list.

True, but we already add in every possible named export in a project context.

**Comment by DanielRosenwasser** [comment]
This just gets very annoying for anything in Node that's a built-in. `path`, `fs`, and more are just painful to import. otherwise. Maybe when `moduleResolution` is calculated as `node`, we could try

- All non-globbed ambient module declarations with no slashes.
- All dependent packages in `package.json` that have a declaration

**Comment by OliverJAsh** [comment]
Issue related to this: https://github.com/microsoft/TypeScript/issues/19630

Perhaps TS could suggest namespace imports based on existing imports in the project?

E.g. if the module `foo` is imported as …

``` ts
import * as FooBar from 'foo/bar';
```

… in _other_ modules, then when I type `FooBar` in _this_ module, suggest importing it using the same import statement as seen in other modules (above). TS would learn from how the same module is imported elsewhere.

**Comment by mikecann** [comment]
Has there been any movement on this?

**Comment by DanielRosenwasser** [comment]
> My only worry is the amount of unrelated names we put in the completion list.

Maybe we could we limit this to ambient module declarations, and packages listed in dependencies, devDependencies, and peerDependencies?

**Comment by andrewbranch** [comment]
> Maybe we could we limit this to ambient module declarations, and packages listed in dependencies, devDependencies, and peerDependencies?

That would happen automatically at this point: https://github.com/microsoft/TypeScript/pull/32517

**Comment by DanielRosenwasser** [comment]
So really the concerns are pretty limited at this point - would the main thing here be to just grab the list of ambients and dependencies and ensure that in the completion list their names

* are camel-cased (`bar-baz` becomes `barBaz`)
* don't include the namespaced portion (e.g. `@foo/bar-baz` becomes `barBaz`)

**Comment by andrewbranch** [comment]
Is this issue specifically about seeing these auto-imports in _completions_ rather than as a code fix (lightbulb) once you type the full module symbol name? I don’t see it noted anywhere in this issue that the latter _does_ work today:

![Kapture 2020-02-24 at 14 00 27](https://user-images.githubusercontent.com/3277153/75195077-20d1cb00-570e-11ea-9f17-b5343fb7755c.gif)

There are a few caveats:

- For node built-ins specifically, you must either have `@types/node` in your package.json (not just included transitively), _or_ have already imported any other node built-in module in that file.
- Your module target and `esModuleInterop` settings determine whether you get `import path from 'path'`, `import * as path from 'path'`, or `import path = require('path')`

**Comment by rauschma** [comment]
@andrewbranch By “today”, do you mean in VS Code Insiders’ Build? I don’t get the lightbulb in VS Code 1.42.1. (my project meets the requirements you mentioned).

Definitely good enough for my needs, but I wouldn’t mind additionally having completions.

**Comment by andrewbranch** [comment]
Yeah, I just tried it with TypeScript 3.7.5 in VS Code Insiders, though I think it’s been working for longer than that. To clarify, are you in a TS or JS file? Support in JS files is a little spotty, even for ES imports. If it’s TS, it should definitely be working. If the repo is open source or if you can give me read access to what you’re looking at, I’d be happy to take a look.

**Comment by rauschma** [comment]
Thanks for the offer – much appreciated!

I switched to a public project and here I am indeed getting the lightbulb!

* Project: https://github.com/rauschma/enumify

* Caveat: If I go to `ts/src/index.ts` and quick-fix `path`, I’m getting:
  ```ts
  import path = require("path");
  ```
  This is old TypeScript(?) Neither CommonJS nor ESM. Not sure why.

**Comment by andrewbranch** [comment]
That’s TypeScript syntax for CommonJS (analogous to `const path = require("path")`). It’s happening because the typings for `path` are [written as a CommonJS module](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e7edc7c479e1d5a37b261706a9f5ad9d84b0aa5e/types/node/path.d.ts#L152) (`export = path` is TypeScript syntax for `module.exports = path`). And while node built-ins _do_ make themselves available as ES modules and CJS modules simultaneously in ways that the DefinitelyTyped typings cannot yet accurately reflect, you’re compiling down to CommonJS, and so those definitions do accurately reflect reality for your project. So, strictly speaking, a CommonJS-equivalent import is the most correct import form given the information available to the compiler.

However, if I’ve learned one thing in this job, it’s that people _hate_ import/require, and no amount of me explaining that it’s really correct makes them feel better about it. So instead of doing that, I’ve been slowly introducing logic that looks for any excuse to prefer a different import form. Namely, if `esModuleInterop` or `allowSyntheticDefaultImports` is enabled, you’ll get a default import (`import path from 'path'`) instead. If your `module` setting is ES2015 or newer, then import/require isn’t allowed (because it’s explicitly CommonJS), so you get a namespace import (`import * as path from 'path'`).

Unfortunately, your code doesn’t match any of those heuristics, and so there’s no reason why the compiler should choose the namespace import over the CommonJS import. So, strict correctness prevails.

Just out of curiosity, if you were writing vanilla JS in ESM, would you use `import path from 'path'` or `import * as path from 'path'`?

**Comment by ExE-Boss** [comment]
I’d probably go with:
```js
import * as path from "path";
```

Since it’s more **ESM**‑ish and doesn’t rely on the fact that **Node.js** synthesises the `default` export for all **CommonJS** modules.

---

That said, non‑**Node.js** built‑ins can only be `default`‑imported.

**Comment by OliverJAsh** [comment]
@andrewbranch 

> Is this issue specifically about seeing these auto-imports in _completions_ rather than as a code fix (lightbulb) once you type the full module symbol name? I don’t see it noted anywhere in this issue that the latter _does_ work today:

This works for `path` but not for other things like `url` or `querystring`. Do you know why?


https://user-images.githubusercontent.com/921609/121009165-c128f300-c78b-11eb-8084-0d66088b2cab.mov

---

I would like to add something to this suggestion: at Unsplash we frequently use namespace imports not just for `node_modules` but also for our own modules. For example:

```ts
import * as Either from 'types/Either';
```

Auto import does not seem to work in this case.

Furthermore, sometimes we name the namespace differently from the file, for example:

```ts
import * as O from 'types/Option';
```

To make this work, I think TS would need to analyse existing import patterns and provide import suggestions based on that. E.g. look to see if the namespace `O` exists anywhere else in the codebase and if it does, provide a matching suggestion.

**Comment by andrewbranch** [comment]
I think the latter suggestion is too complex/expensive, but the rest of these cases seem like they should be an easy fix.

**Comment by OliverJAsh** [comment]
@andrewbranch Perhaps VS Code could provide an API so extensions can contribute import suggestions (which appear in the suggestions drop down when typing _and_ as quick fixes), then someone could write an extension to do this. Do you know if anything like that exists?

**Comment by andrewbranch** [comment]
I’ve looked into this a good bit and decided I don’t want to do it in general. We can’t know the conventions by which the namespace export is named: `path` comes from `"path"` but `React` comes from `"react"`. It would be super annoying when we inevitably get a convention wrong.

I investigated this:

> This works for `path` but not for other things like `url` or `querystring`. Do you know why?

The `"path"` module typings declare [an `export = path`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/355f5ad7ec2ae71bf4a47c0f383df3bc899ae048/types/node/path.d.ts#L167) and we pull the name from the declaration of the symbol being exported. On the other hand, the `"url"` module (along with the majority of node built-ins) has no `export =` declaration; it’s simply a collection of named exports. These named exports could be wrapped in a namespace named `url` and then `export = url` from the top level. The module would behave _almost_ identically to the way it behaves as written today, except that `export * from "url"` would become an error. It’s worth noting that some of the node built-ins like `path` and `assert` are written as an `export =` out of necessity or convenience, and `export * from "path"` is already an error because of that, despite it being valid in Node. It _could_ be worth making the change to the rest of the modules to allow auto-imports to work better. This is a question for the Node typings maintainers to consider on DefinitelyTyped.

@OliverJAsh’s suggestion of picking up on namespace import names used elsewhere in the program is probably the only solution here that can provide a decent UX, but I think it’s too much complexity for the value it delivers. (It would be too expensive to look up these associations from other files on demand when we’re generating a completions list, so we’d have to introduce a new cache, which means you have to think about cache invalidation.)

> Perhaps VS Code could provide an API so extensions can contribute import suggestions (which appear in the suggestions drop down when typing and as quick fixes), then someone could write an extension to do this. Do you know if anything like that exists?

As far as I know, these APIs are separate, but there is nothing stopping a single extension from sharing code to contribute to both APIs.
