### ISSUE TITLE
Subsequent variable declarations must have the same type.

### ISSUE THREAD

**Issue by RasikaMK** [Microsoft/TypeScript#23854]
Hi,
I am getting below error while running angular 4 application.

ERROR in node_modules/msal/lib-commonjs/UserAgentApplication.d.ts(6,9): error TS                                                                                                                                                 2403: Subsequent variable declarations must have the same type.  Variable 'callB                                                                                                                                                 ackMappedToRenewStates' must be of type 'any', but here has type 'Object'.

Please suggest the solution.

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Next time, please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
