### ISSUE TITLE
A non-semicolon line ending before a type cast yields an error

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#2389]
I use to skip ending with semicolon for every line I write. I noticed an error:

This currently fails:
```typescript
interface Interface1 {
	property1: number
	property2: string
}

interface Interface2 extends Interface1 {
	property2: string
}

var node = { property1: 1, property2: 'hej' }
node.property1 = 1 // no semicolon here
(<Interface2>node).property2 = 'hej' 
```
While this doesn't:
```typescript
interface Interface1 {
	property1: number
	property2: string
}

interface Interface2 extends Interface1 {
	property2: string
}

var node = { property1: 1, property2: 'hej' }
node.property1 = 1; // a semicolon here
(<Interface2>node).property2 = 'hej' 
```

Playground:
http://www.typescriptlang.org/Playground#src=interface%20Interface1%20%7B%0D%0A%09property1%3A%20number%0D%0A%09property2%3A%20string%0D%0A%7D%0D%0A%0D%0Ainterface%20Interface2%20extends%20Interface1%20%7B%0D%0A%09property2%3A%20string%0D%0A%7D%0D%0A%0D%0Avar%20node%20%3D%20%7B%20property1%3A%201%2C%20property2%3A%20'hej'%20%7D%0D%0Anode.property1%20%3D%201%0D%0A(%3CInterface2%3Enode).property2%20%3D%20'hej'%20

**Comment by vladima** [comment]
Per ES6 spec [ASI rules](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-rules-of-automatic-semicolon-insertion) are:

1. When, as a Script or Module is parsed from left to right, a token (called the offending token) is encountered that is not allowed by any production of the grammar, then a semicolon is automatically inserted before the offending token if one or more of the following conditions is true:
The offending token is separated from the previous token by at least one LineTerminator.
The offending token is }.
2. When, as the Script or Module is parsed from left to right, the end of the input stream of tokens is encountered and the parser is unable to parse the input token stream as a single complete ECMAScript Script or Module, then a semicolon is automatically inserted at the end of the input stream.
3. When, as the Script or Module is parsed from left to right, a token is encountered that is allowed by some production of the grammar, but the production is a restricted production and the token would be the first token for a terminal or nonterminal immediately following the annotation “[no LineTerminator here]” within the restricted production (and therefore such a token is called a restricted token), and the restricted token is separated from the previous token by at least one LineTerminator, then a semicolon is automatically inserted before the restricted token.

In your case ASI is now applicable because of the first rule, in fact spec has similar code as one of [examples](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-examples-of-automatic-semicolon-insertion):
>The source
```javascript
a = b + c
(d + e).print()
```
>is not transformed by automatic semicolon insertion, because the parenthesized expression that begins the second line can be interpreted as an argument list for a function call:
```javascript
a = b + c(d + e).print()
```
>In the circumstance that an assignment statement must begin with a left parenthesis, it is a good idea for the programmer to provide an explicit semicolon at the end of the preceding statement rather than to rely on automatic semicolon insertion.

**Comment by tinganho** [comment]
I'm providing a number and not a variable. And to follow JS this example seem to work:

![screen shot 2015-03-17 at 7 53 25 pm](https://cloud.githubusercontent.com/assets/1324476/6686741/602ec7d0-ccdf-11e4-83d6-20f437235d8d.png)

**Comment by vladima** [comment]
TypeScript ASI rules are the same with [ES spec](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-rules-of-automatic-semicolon-insertion) and in JavaScript semicolon will not be inserted after 2 in line `x.a = 2`.
```javascript
// a.js
var x = {a: 1, b: true};
x.a = 2 
(x).b = false;
```
Running `node a.js` yields
>(x).b = false;
^
TypeError: number is not a function

meaning that code was effectively parsed as
```javascript
// a.js
var x = {a: 1, b: true};
x.a = 2(x).b = false;
```
leading to runtime error

**Comment by tinganho** [comment]
My fault that example didn't work. Only worked in REPL mode.
