### ISSUE TITLE
Allow generic parameters to propagate on returned type references.

### ISSUE THREAD

**Issue by rjamesnw** [Microsoft/TypeScript#23955]
## Search Terms

Generic type parameters are lost upon return from a function.

## Suggestion

In the case of the following:

```
class Test<Tx> { x: Tx; }
function Func<TClass>(type: TClass) { return type; }
var t = Func(Test);
var o = new t();
```
(https://goo.gl/YefQ6z)

I would have expected that the type of `t` is `typeof Test<Tx>`. `Func()` might be considered as a type of decorator of sorts, but it is a lot more complicated in my actual code, but this gets the idea across. 

## Use Cases

I'm creating a factory type system that is wrapped by a function (i.e. `export Type = CreateFactory(base, class SomeType<T>(){...})`).  It uses type inference to figure out types and adds other types to the return type before exporting a property. Similar to:

```
namespace A {
  interface IFactory {
    'new'?(...args:any[]): any;
    'init'?(...args:any[]): any;
  }
  function CreateFactory<TClass extends new () => any, TFactory extends IFactory>(getClass:()=>[TClass, TFactory])
    : TClass & { originalType: TClass } & TFactory {
    var type = getClass();
    type['originalType'] = type;
    return <any>type;
  }

  export var Test = CreateFactory(() => {
    class Test<Tx> { x: Tx; }
    var factory = {
      new: function <Tx>(): Test<Tx> { return null; },
      init: function <Tx>(o: Test<Tx>) { return o; }
    }
    return [Test, factory];
  });
}

var o = A.Test.new<number>();
```
(https://goo.gl/fMtCPQ)

This works OK, and there is no issue with _non_-generic types.  The problem is now with `A.Test.originalType`.  I have no way to access the generic type signature anymore.  Instead, I simply get `typeof Test`. I recommend the generic type signatures propagate properly. It may even help some people catch more bugs. This should allow me to do this:

```
    type TestType = typeof Test.originalType; // (currently this is only 'typeof Test' and the following fails)
    export interface ITest<Tx> extends InstanceType<TestType<Tx>> { }
```

Note: My actual code is a bit more complicated and allows inheritance chaining of the factories, which is why this pattern was the best suited for it.

## Checklist

My suggestion meets these guidelines:
 [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
 [x] This wouldn't change the runtime behavior of existing JavaScript code
 [x] This could be implemented without emitting different JS based on the types of the expressions
 [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by jcalz** [comment]
The syntax `typeof XXX`  only works when `XXX` is a *value*, not a *type*.  When you declare a `class` in TypeScript, it introduces both a value and a type with the same name.  The *value* refers to the class constructor object (visible at runtime), and the *type* refers to the type of an instance of the class (erased at runtime).  And despite having the same name, the type of the constructor is *not* the type of the instance.   In your case, you have the *type* `Test<T>`, which is structurally equivalent to `{x: T}`, and the *value* `Test`, whose type, `typeof Test`, is structurally equivalent to something like `new <T>() => Test<T>`.  Maybe you know this, but having two things with the same name can be confusing, so I'm trying to spell it out.  

So `typeof Test<T>` doesn't work, since `typeof Test<T>` can only refer to some *value* named `Test<T>`, and values are not generic (there is no runtime object named `Test<T>`).   Are you asking for TypeScript to introduce generic values as in #17574?   I'm not sure why you think you need that, since `typeof Test` is essentially the generic thing you want.  You can do `var o = new t<number>();` and it works, right?

What am I missing here?

**Comment by rjamesnw** [comment]
That was a simple example.  The second code much better explains it.  In essence I'm looking for this:

`interface ITestNumber extends t<number> { }`

Which of course does not work.  As you said, if I can do `new t<number>` I don't understand why I cannot also create an interface from it, since obviously the type system understands `new`ing it, so it much be there in the type system still.  In the second code I posted there is no access to the original class type.  this is a factory pattern, so not sure why you are focusing on using the 'new' operator.

**Comment by rjamesnw** [comment]
JCalz, I hoped it was clear I know that by now.  Of course you can't that's the point.  ;)  I was only trying to give an idea of what I was thinking, that is all.  

> you can't pull the generic relationship between the constructor and the instance type out of the constructor type

Correct, that's my main point. ;)

You made a good point about being able to use a class to inherit from a generic type, in which I could create an interface type from the class type:
```
class T<A> extends t<A> { }
interface ITest<A> extends T<A> { }
```
I think it may be an acceptable workaround. 👍 

Perhaps it is a request for higher order types, not sure either.  All I know is my idea is very simple to lay out.  If I had this:

`class A<T> { }`

Means 'A' references a constructor AND a generic class type. Then if I do this:

`var B = A;`

`B`  SHOULD act the SAME as A (type-wise).  The constructor AND the generic type should be copied over.  I don't see why this is hard to understand? ;)  It's straight forward; however, I'm not sure how straight forward it would be to implement.

**Comment by jcalz** [comment]
If you're saying that `var B = A` (when `A` is a constructor function) should introduce a *type* named `B`, which is equivalent to the *type* named `A`, I think there will be objections.   It would definitely be a breaking change, because it would add a whole bunch of new possibly-conflicting types to existing code.

At this point I should bow out and wait to see what real TypeScript language designers/maintainers have to say, since I'm just an ~~annoying~~ interested bystander.

**Comment by weswigham** [comment]
> If you're saying that var B = A (when A is a constructor function) should introduce a type named B, which is equivalent to the type named A, I think there will be objections. It would definitely be a breaking change, because it would add a whole bunch of new possibly-conflicting types to existing code.

We've actually been considering binding `var a = b` like an alias (meaning like `import a = b`) in JS for a bit now, as it turns out people enjoy writing things like
```ts
const MyClass = module.exports = class Foo {}
```
and then referring to `MyClass` all over. We'd have to do a lot of compat testing and thinking before we decided to do it in TS, though. I think that discussion is mostly unrelated to the OP's request though - it looks like he wants a partially inferred type - something where we've done an inference pass up to a point, but then left some type parameters bare so they can be inferred in another call.

**Comment by mhegazy** [comment]
We currently have no way of letting generic parameters "escape" from an instantiation. the system assume that all parameters will be accounted for. i

**Comment by kresli** [comment]
Seems like not just generic type is lost but constructor too 
```
export function Wrapper() {
    return class {
        title!: string;
  };
}


function bindProperty<Prop extends ReturnType<typeof Wrapper>>(Prop: Prop) {
  class SyncedProp extends Prop {} // <-- why the Prop is NOT a constructor type?
  // Type 'Prop' is not a constructor function type.ts(2507)
}
```
