### ISSUE TITLE
Compiler hang on this complicated example

### ISSUE THREAD

**Issue by shivawu** [Microsoft/TypeScript#24016]
**TypeScript Version:**  2.9.0-dev.20180510
**NodeJS Version:** 9.11.1
**OS Version:** Mac OS X 10.13.4

**Search Terms: hangs** 

**Code**
It's a pretty involved and complicated code. Put it up as a gist for better readability.

https://gist.github.com/shivawu/22053a9292ac694bfc87c97ef3c652bf

Note the last line, if it's commented it out, it compiles just fine. That particular line hangs the compiler.

**Expected behavior:**
It should type check just fine.

**Actual behavior:**
The compiler hangs. Taking 100% CPU, memory keeps increasing non-stop.

**Playground Link:** I would skip that since the code would hang the browser tab :)

**Related Issues:** #7344, #23458 looks similar as well

**Comment by andy-ms** [comment]
I've managed to simplify this a bit -- but this example has a 'Maximum call stack size exceeded' error instead:
```ts
interface HCons<Next> {
    readonly next: Next;
}

type Unionize<T> = keyof T extends infer K
  ? K extends string & keyof T ? Record<K, T[K]> : never
  : never;
type KeysRec<T> = T extends Record<any, infer V>
  ? { 1: HKeys<V>, 0: number }[V extends Whatever ? '1' : '0']
  : never;
type HKeys<T> = KeysRec<Unionize<T>>;

type Normalize<T> = T extends HCons<infer N>
  ? { 1: Normalize<N>, 0: Shabadoo }[N extends Whatever ? '1' : '0']
  : never;

type JustNumber<H extends HCons<any>> = number;

type Keys<T> = JustNumber<Normalize<HKeys<T>>>;
```

**Comment by ahejlsberg** [comment]
With the compiler currently in `master` we don't hang on the original example (probably because of #26558), but it still takes 7.5s to type check and allocates over 700,000 types.

The core issue here is the pattern of using indexed access types to write self-referencing conditional types. It is a Turing Complete device (#14833) and along with that comes the halting problem. It is effectively impossible for us to know if evaluation of such types will ever terminate. For this reason I strongly discourage use of the pattern.
