### ISSUE TITLE
Please revert the breaking change in tsc -w that clears output

### ISSUE THREAD

**Issue by hoegge** [Microsoft/TypeScript#24123]
## Search Terms
tsc -w
clear

#17756 
## Suggestion

Revert the default clearing of console on re-compile using `tsc -w` 

The current (new) imlementation is really annoying. All scripts and packages by others using tsc -w now clears the console and people have to modify packages and scripts. All the people who likes it to clear the screen (as a new) feature should use an option instead of breaking existing functionality.

(@k0pernikus)

## Summary: 

`tsc -w` should not clear screen on re-compile. Add another option like `--clearOutputWatch` or similar.

## Use Cases

Any scripts using tsc

## Examples

n.a.

## Checklist

My suggestion meets these guidelines:
 [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code (it would "UNBREAK" TypeScript after you broke it)
 [x] This wouldn't change the runtime behavior of existing JavaScript code
 [x] This could be implemented without emitting different JS based on the types of the expressions
 [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by RyanCavanaugh** [comment]
This is *really* stretching the definition of "breaking change".

`preserveWatchOutput` exists and it makes a lot more sense for tool authors to write that *once* than for people running from the commandline to type it *every time*.

If people running `tsc` themselves want this to be the default, we can gather feedback on that, but we're not going to flip-flop because script authors took a dependency on how a long-running process manages the console.

**Comment by DanielRosenwasser** [comment]
If you want a stable API for program watching, use that: https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#writing-an-incremental-program-watcher

Please don't rely on our interactive mode's behavior.

**Comment by hoegge** [comment]
Yes! It does - didn't know it existed. Then that would solve most issues I think. Thanks @weswigham
