### ISSUE TITLE
interface implements issue

### ISSUE THREAD

**Issue by spitWind** [Microsoft/TypeScript#24156]
**TypeScript Version:**  2.9.0-dev.201xxxxx

**Search Terms:** 

interface Animal {
  age: number;
  name: string;
}
interface Bird implements Animal{
  speed:number;
}
var b:Bird
b.speed// 只有speed 的属性

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:  type b.age  is number

**Actual behavior:type b.age  is none

**Playground Link:**  

**Related Issues:**

**Comment by MartinJohns** [comment]
By running `tsc test.ts` (with your code) I get the error:

> error TS1176: Interface declaration cannot have 'implements' clause.

You need to use the `extends` keyword instead: `interface Bird extends Animal`

After that change it will run fine, because by default it will not use the strict-compiler options. So `b.age' is a `number`, but in JavaScript it can also be implicitly `undefined`.

By calling `tsc test.ts --strictNullChecks` you enable the `strictNullChecks` feature (https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html) which will change the semantics of `null` and `undefined` from values to types. If you do this, then your code will not compile anymore:

> error TS2454: Variable 'b' is used before being assigned.

The compiler can not ensure anymore that your variable matches the interface.
