### ISSUE TITLE
Disallow assign incompatible type as default value in object destructuring

### ISSUE THREAD

**Issue by ikokostya** [microsoft/TypeScript#24254]
**TypeScript Version:**  typescript@2.8.3, typescript@2.9.0-dev.20180518

**Search Terms:** destructuring, default values

**Code**

```ts
interface Foo {
    x?: string;
}

function f({x = 0}: Foo): void {}
```

**Expected behavior:**

Compile error: number `0` is not assignable to `string | undefined` for property `x`.

**Actual behavior:**

No errors. Resulting type of property `x` in function `f`  is `string | 0`.

**Playground Link:**  http://www.typescriptlang.org/play/index.html#src=interface%20Foo%20%7B%0A%20%20%20%20x%3F%3A%20string%3B%0A%7D%0A%0Afunction%20f(%7Bx%20%3D%200%7D%3A%20Foo)%3A%20void%20%7B%7D

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/16260

**Comment by ikokostya** [comment]
I renamed title of the issue for correctness. Current behavior is unsafe and looks like bug.

**Comment by stefanhamburger** [comment]
It looks like this was changed with TypeScript 3.0. The expected behavior described in the OP has now become the actual behavior. However, I'd argue that the previous behavior (as it existed in 2.x) was correct and therefore disagree with the OP.

My use case is that I want the function argument to have a different type than the function's internal variable:

```ts
interface DatePickerProps {
  defaultValue?: Date;
}

const DatePicker = ({ defaultValue = null, ...props }: DatePickerProps) => {
  //                  ^
  // Error: Type 'null' is not assignable to type 'Date'. ts(2322)
}
```

Ideally, the `defaultValue` variable should have an internal type of `Date | null`, while implementers will call the function with `Date | undefined` (or in JSX syntax, `<DatePicker />` and `<DatePicker defaultValue={new Date()} />`).

I'd argue that TypeScript should not enforce that a function's internal variables must have the same type as the function signature. This is an arbitrary restriction that makes it harder to encapsulate internal logic.

Instead, I now have to use one of these workarounds, neither of which is ideal:

```ts
const DatePicker1 = ({ defaultValue = (null as unknown) as Date, ...props }: DatePickerProps) => {
  // -> This compiles but now `defaultValue` is of type `Date`, not `Date | null` as expected.
}

const DatePicker2 = ({ defaultValue: DO_NOT_USE, ...props }: DatePickerProps) => {
  const defaultValue = DO_NOT_USE ?? null;
  // -> This creates an unnecessary variable.
}
```

**Comment by stefanhamburger** [comment]
@RyanCavanaugh May I ask why you closed this issue?

Is there a better place to discuss this or should I create a new issue? I figured that due to the "Awaiting More Feedback" label, this is the best place.

The 3.0 release notes do not mention a change to object destructuring, and I cannot find a discussion on why the behavior was changed with 3.0.

**Comment by RyanCavanaugh** [comment]
@stefanhamburger because "The expected behavior described in the OP has now become the actual behavior.". It's confusing to have issues flip/flop meaning with regard to the original post; if you don't like the change you are welcome to file a new issue.
