### ISSUE TITLE
Type 'NamedNodeMap' is not an array type

### ISSUE THREAD

**Issue by xuqinggang** [Microsoft/TypeScript#24290]
```
    const attributes = [...dom.attributes];  
   // ts errror: Type 'NamedNodeMap' is not an array type
```
How to solve the above problem?
thans~~

**Comment by NN---** [comment]
Did you set ES6 in tsconfig?
Or “downlevelIteration”: true?

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Next time, please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!

**Comment by mhegazy** [comment]
Relevant discussion in https://github.com/Microsoft/TypeScript/issues/20937. the spec does not seem to suggests that NamedNodeMap is iterable, though chrome and firefox implement it as one.
