### ISSUE TITLE
How to use Sharedworker?

### ISSUE THREAD

**Issue by shamhub** [Microsoft/TypeScript#24316]
Below code uses dedicated worker, in the worker code.

```
const ctx: Worker = self as any;
ctx.addEventListener('message', (e) => {
    // console.log(e)
    if (e.data === 'do some work') {
        console.log('Worker is about to start some work');
        let count: number = 0;
        for (let i: number = 0; i < 1000; i++) {
            count += i;
        }
        ctx.postMessage({ message: count });
    }
})

```
where the calling code is:

```
let worker: Worker = new Worker('worker.js');
worker.postMessage('do some work');

```
and `tsconfig.json` is:

```
{
   
    "compilerOptions": {
   
      "lib": ["es2015", "dom"]
    },
    "files": [
      "./1_webworker/tstut.ts",
      "./1_webworker/worker.ts"

    ]
  }

```

------------------------------------------------

Trying to execute the same code using `let worker: SharedWorker = new SharedWorker('worker.js');` but got the error `Cannot find name 'SharedWorker'`

[here](https://github.com/shamhub/shamhub.github.io) is the folder structure

How to use `SharedWorker` in place of dedicated worker?

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Next time, please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!

**Comment by mhegazy** [comment]
SharedWorker is currently not defined in lib.d.ts, meanwhile you can use `@types/sharedworker`.

Logged https://github.com/Microsoft/TypeScript/issues/24323 to track adding it.
