### ISSUE TITLE
`let` and its binding(s) must be on same line

### ISSUE THREAD

**Issue by donnut** [Microsoft/TypeScript#2439]
```
let a = 1;
let
    b = 2;
const c = 3;
const
    d = 4;
```
This snippet is transformed to:
```
var a = 1;
let;
b = 2;
var c = 3;
var d = 4;
```
If I interpret the specs correctly, `let` and `const` have the same definition and should both be able to handle a line break between the keyword and the binding. Is this a bug or done intentionaly?

**Comment by yuit** [comment]
as per ES6 spec, let can be used as an identifier in non-strict-mode code [11.6.2.1](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-keywords).
```typscript
let
    b = 2;  
```

becomes
```javascript
let;
b = 2;
```

due to automatic semicolon insertion.
In strict mode, however, ```let``` is a keyword and thus TypeScript will output
```javascript
var b = 2;
```
Note:```const``` is a keyword regardless of ```use strict```
