### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined in parsing youtube-dl link

### ISSUE THREAD

**Issue by Muzaffar-Munir** [Microsoft/TypeScript#24440]
I want to enter a link of youtube Video when i enter a link in form it will show it in console.log with key url.Now I want to enter this link into Youtube-dl to download the Video

**Form along its action**
<form method="post" action="">
			<input type="url" name="link" class="form-control" required="">
			<br>
			<input type="submit" name="submit" class="form-control btn btn-info">
    	 </form>
if (isset($_POST['submit'])) {	
		$url=$_POST['link'];
			$data = array("link" => "$url");
			$data_string = json_encode($data);            
			
	 echo"
	 <script>
	
	 $.post('http://localhost:3000/url',{url:$data_string},function(data,status){
	 	if(data=='success'){
	 		alert('success');
	 	}
	 });
	 </script>";
}
**app.js**
var http=require("http");
var express=require("express");
var bodyParser = require('body-parser');
var app=express();

app.use(bodyParser());

app.post("/url",function(req,res){
	var li=JSON.stringify(req.body);
	var a="abc";
	//var b=json.strigyfy(a);
	console.log('data sending From '+li);
		res.send('data senting from '+a);
		var fs = require('fs');
var youtubedl = require('youtube-dl');
var a;
var video = youtubedl(li['url'],
  // Optional arguments passed to youtube-dl.
  ['--format=18'],
  // Additional options can be given for calling `child_process.execFile()`.
  { cwd: __dirname });
// Will be called when the download starts.
video.on('info', function(info) {
	a=info.filename;
  console.log('Download started');
  console.log('filename: ' + info.filename);
  console.log('size: ' + info.size);
   console.log('file '+info._filename+' successfully downloaded');
});
 video.pipe(fs.createWriteStream('video.mp4'));	
});
app.listen("3000");
console.log("Server is alive at port 3000");

**Comment by Muzaffar-Munir** [comment]
here is also attached files

**Comment by j-oliveras** [comment]
This is an error into your code or youtube-dl package, and has nothing to do with typescript.

I installed the dependencies with `npm i express body-parser youtube-dl`.

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Next time, please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
