### ISSUE TITLE
Clarification about the TypeScript Compiler: How to use type definitions when importing/requiring files (not modules) in JavaScript?

### ISSUE THREAD

**Issue by aminadav-leadcoin** [Microsoft/TypeScript#24483]
I have three files:

**a.js**

    var moduleb=require('./b.js')
    moduleb.func('should_be_a_string_and_return_a_boolen')

**b.js**

     function func(arg){
             return arg
     }
     module.exports={func}

**b.d.ts**

     declare function fnc(arg:string):boolean

---

### The question:

How I make TypeScript compiler to understands the type definition in `b.d.ts` and connect it to the exported values in `b.js`?

### What I'm trying to achieve?

I'm using `create-react-app` and I want to add type definition to Components so that I can get IntelliSense, to all the props of the components.

Thanks!

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Next time, please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
