### ISSUE TITLE
Function type guard changed behavior somewhere between 2.8.3 and 2.9.1 

### ISSUE THREAD

**Issue by andriy-kudrya** [Microsoft/TypeScript#24541]
**TypeScript Version:** 
2.9.1

**Search Terms:**
typeof function

**Code**

```ts
function bindComponent<C extends {}>(instance: C): void {
    const keys = Object.getOwnPropertyNames(Object.getPrototypeOf(instance)) as Array<keyof C>

    keys.forEach(key => {
        if (typeof instance[key] === 'function')
            instance[key] = instance[key].bind(instance)
    })
}
```

**Expected behavior:**
No compilation errors

**Actual behavior:**
TS2339: Property 'bind' does not exist on type 'C[keyof C]'.

**Playground Link:**  
[playground](http://www.typescriptlang.org/play/#src=function%20bindComponent%3CC%20extends%20%7B%7D%3E(instance%3A%20C)%3A%20void%20%7B%0D%0A%20%20%20%20const%20keys%20%3D%20Object.getOwnPropertyNames(Object.getPrototypeOf(instance))%20as%20Array%3Ckeyof%20C%3E%0D%0A%0D%0A%20%20%20%20keys.forEach(key%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20if%20(typeof%20instance%5Bkey%5D%20%3D%3D%3D%20'function')%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20instance%5Bkey%5D%20%3D%20instance%5Bkey%5D.bind(instance)%0D%0A%20%20%20%20%7D)%0D%0A%7D%0D%0A)

**Related Issues:**

**Comment by ahejlsberg** [comment]
This is a result of a bug fix in 2.9. Previously we erroneously resolved the constraint of `C[keyof C]` to `any` which effectively turned off type checking. So, we allowed `instance[key].bind(...)`, but really we would have allowed *any* method name and *any* set of arguments. We no longer do that and therefore you need a type assertion to access the `bind` method:

```ts
instance[key] = (instance[key] as any).bind(instance);
```

Separately, your example ought to work if you introduce a local variable to represent `instance[key]` and then check against that. However, it doesn't because of separate issue we're tracking in #18238.

**Comment by andriy-kudrya** [comment]
Thanks for an explanation,
Guess, I can close the issue then

**Comment by ahejlsberg** [comment]
@andriy-kudrya You're welcome. With #24627 you'll be able to write your code like this:

```ts
function bindComponent<C extends {}>(instance: C): void {
    const keys = Object.getOwnPropertyNames(Object.getPrototypeOf(instance)) as Array<keyof C>;
    keys.forEach(key => {
        const x = instance[key];
        if (typeof x === 'function')
            instance[key] = x.bind(instance);
    });
}
```
