### ISSUE TITLE
Transpiler should error if a static property is declared that the language already defines.

### ISSUE THREAD

**Issue by reppners** [Microsoft/TypeScript#2462]
Based on this [issue](https://github.com/angular/angular.js/issues/11401#issuecomment-84920575):

Can the transpiler warn you if something like this happens?

**Comment by billccn** [comment]
Since `lib.d.ts` is generated from IE definitions, I guess it's entirely possible that the compiler is not even aware there's a `name` property.

The interesting question is, once it has been added per ES6, how should the compiler handle unwritable properties in general? Would getters/setters be added to `interface`s?

**Comment by mhegazy** [comment]
@billccn is correct the name declaration is comming from lib.d.ts, and you can edit the file to remove the definition. Also see #1351 for removing these properties from the library file.
