### ISSUE TITLE
Regression in 2.9+: expansion of type operator is incorrect

### ISSUE THREAD

**Issue by pelotom** [Microsoft/TypeScript#24640]
**TypeScript Version:**  2.9.1, 3.0.0-dev.20180602

**Search Terms:** conditional union type operator expansion

**Code**

```ts
type U =
  | {
      tag: 'a';
      foo: number;
      f(): void;
    }
  | {
      tag: 'b';
      bar: boolean;
      g(): void;
    };

type FilterUnion<T extends { tag: string }, K> = T extends { tag: K } ? T : never;
type StripFunctions<T> = Pick<
  T,
  { [K in keyof T]: T[K] extends (...args: any[]) => any ? never : K }[keyof T]
>;
type FilterAndStrip<K extends U['tag']> = StripFunctions<FilterUnion<U, K>>;

type X1 = FilterAndStrip<'a'>;
type X2 = StripFunctions<FilterUnion<U, 'a'>>;
```

**Expected behavior:**
`X1` and `X2` should both have the type `{ tag: 'a'; foo: number }`, since the latter is just an expansion of the first.

**Actual behavior:**

`X2` is correct, but `X1: {}`.

[**Playground Link**](http://www.typescriptlang.org/play/#src=type%20U%20%3D%0A%20%20%7C%20%7B%0A%20%20%20%20%20%20tag%3A%20'a'%3B%0A%20%20%20%20%20%20foo%3A%20number%3B%0A%20%20%20%20%20%20f()%3A%20void%3B%0A%20%20%20%20%7D%0A%20%20%7C%20%7B%0A%20%20%20%20%20%20tag%3A%20'b'%3B%0A%20%20%20%20%20%20bar%3A%20boolean%3B%0A%20%20%20%20%20%20g()%3A%20void%3B%0A%20%20%20%20%7D%3B%0A%0Atype%20FilterUnion%3CT%20extends%20%7B%20tag%3A%20string%20%7D%2C%20K%3E%20%3D%20T%20extends%20%7B%20tag%3A%20K%20%7D%20%3F%20T%20%3A%20never%3B%0Atype%20StripFunctions%3CT%3E%20%3D%20Pick%3C%0A%20%20T%2C%0A%20%20%7B%20%5BK%20in%20keyof%20T%5D%3A%20T%5BK%5D%20extends%20(...args%3A%20any%5B%5D)%20%3D%3E%20any%20%3F%20never%20%3A%20K%20%7D%5Bkeyof%20T%5D%0A%3E%3B%0Atype%20FilterAndStrip%3CK%20extends%20U%5B'tag'%5D%3E%20%3D%20StripFunctions%3CFilterUnion%3CU%2C%20K%3E%3E%3B%0A%0Atype%20X1%20%3D%20FilterAndStrip%3C'a'%3E%3B%0Atype%20X2%20%3D%20StripFunctions%3CFilterUnion%3CU%2C%20'a'%3E%3E%3B)

**Comment by yuretz** [comment]
And yet, if you do
```typescript
type FilterAndStrip<K, V extends U = U> = StripFunctions<FilterUnion<V, K>>;
```
X1 gets the same type as X2. Weird!

**Comment by mhegazy** [comment]
The issue here goes back to how `Pick` works. let me try to walk through what happens.. 

At zero order, `FilterUnion<U, 'a'>` is just `{ tag: "a", foo: number, f(): void; }` running that through the `StripFunctions`, which is just a call for `Pick` and that gets you the desired output..

At higher order `FilterUnion<U, K>` is `FilterUnion<{ tag: "a", foo: number, f(): void; }, K> | FilterUnion<{ tag: "b", foo: number, g(): void; }, K>`, which is a union. now you ask `Pick` to map the properties, of the union type. but the union type has no common properties, so the output is `{}`. 

One option here is to distribute `Pick` on the union type. this way you get a union of the `StripFunctions<FilterUnion<{ tag: "a", foo: number, f(): void; }, K>> |  StripFunctions<FilterUnion<{ tag: "b", foo: number, g(): void; }, K>>` instead of `StripFunctions<FilterUnion<{ tag: "a", foo: number, f(): void; }, K> |  FilterUnion<{ tag: "b", foo: number, g(): void; }, K>>`, e.g.:

```ts
type StripFunctions<T> = T extends {} ? Pick<
    T,
    { [K in keyof T]: T[K] extends (...args: any[]) => any ? never : K }[keyof T]
    > : never;
```

**Comment by pelotom** [comment]
Is it a bug that it worked prior to 2.9 then? What changed in the design that this became a limitation?

**Comment by mhegazy** [comment]
Yes. the current behavior is what i would expect. it was masked in the past by how we were handling keyof of union types (fixed by https://github.com/Microsoft/TypeScript/pull/23645).
