### ISSUE TITLE
Typescript can't call simple javascript on addEventListener 

### ISSUE THREAD

**Issue by nwoow** [Microsoft/TypeScript#24684]
I have tried many thing but I am unable to find a way. That is why I am asking question here.
I am using Angular 6 where I am trying to load a svg map inside html. Using this code:     
`    <object data="assets/img/bihar.svg" id="biharsvg" type="image/svg+xml"></object>
`
I am using this code inside my service I am using this code:

`svg() {
  this.bar();
  let a = document.getElementById("biharsvg")  as HTMLObjectElement;
  a.addEventListener("load", function() {
       var svgDoc = a.contentDocument; 
       var wchamparan = svgDoc.getElementById("wchamparan");
       wchamparan.onclick = function() {     
        console.log("hello");     
     }
  })
 }
`
Here everything work fine but I am trying to add this.bar(); function which is inside my service class but I am getting this error :  [ts] Property 'bar' does not exist on type 'HTMLElement'.
any  When I am trying to use this code:

 ` svg() {
  
  let a = document.getElementById("biharsvg")  as HTMLObjectElement;
  a.addEventListener("load", function() {
       var svgDoc = a.contentDocument; 
       var wchamparan = svgDoc.getElementById("wchamparan");
       wchamparan.onclick = function() {     
       this.bar();        
      console.log("hello");     
     }
})
}
`
My question is can I call any function like this inside addEventListener in javascript it is very easy What is wrong with this.

**Comment by AlCalzone** [comment]
Since you are using classing `function`s as callbacks, inside them `this` is most likely bound to the element they belong to - but you can't be 100% sure. Use arrow functions instead:
```js
a.addEventListener("load", () => {
    // ...
    wchamparan.onclick = () => {
        // ... `this` will be bound to the class instance
    }
}
```

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Next time, please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
