### ISSUE TITLE
Add readwrite member decleration

### ISSUE THREAD

**Issue by Rycochet** [Microsoft/TypeScript#24726]
## Search Terms

"readwrite" "readonly"

## Suggestion

There is already a `readonly` declaration, which tells the compiler that a class or interface member is not allowed to be changed.

This suggestion is simply to add a `readwrite` (and possibly `writeonly`, though that is more of a setter-only choice).

The latest (2.9) added the ability to use `Readwrite<class>` to take any `readonly` declarations off, but there's no corresponding declaration to make it visibly obvious something is read/write.

The terms `readonly` and `readwrite` have been mentioned a couple of times by the team (and in at least one previous minuted meeting), so it isn't a new idea.

## Use Cases

When creating a class with a lot of read-only members, then a single one that is allowed to be written to: It looks less "wrong" to have something that highlights the same way in the editor, and also makes it obvious that the lack of a `readonly` declaration is actually deliberate.

While `get`/`set` can be used to enforce (as can `Object.defineProperty`) that's overhead and compile-time code quality.

Having the ability to annotate every member with a `readonly` / `readwrite` allows for another strict (or lint) check to force all members to be declared.

## Examples

Without:

```javascript
class myClass {
   readonly member1: string;
   readonly member2: number;
   readonly member3: object;
   member4: boolean; // Was this a mistake?
   readonly member5: Array<string>;
}
```

With:

```javascript
class myClass {
   readonly member1: string;
   readonly member2: number;
   readonly member3: object;
   readwrite member4: boolean; // Looks more deliberate?
   readonly member5: Array<string>;
}
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mhegazy** [comment]
We have considered adding a new modifier when we were designing `readonly`. the conclusion we reached back then, and i believe still holds today, that there is no need to introduce a keyword that basically does nothing. it adds complexity to the language, and complicates learning for users. I do not think we need to have a debate on whether everybody should have lint rule that adds `public readwrite` on every property declaration.

`writyonly` is a different cases, since it actually expresses a valid use case that can not be expressed currently in the language in another form. that said, we felt it was not that common (out side DOM event handlers really). I think we should create a new issue for tracking adding `writeonly` support.
