### ISSUE TITLE
Extract to method in class should use static method if possible

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#24879]
**TypeScript Version:**  3.0.0-dev.20180609

**Code**

```ts
class C {
	m() {
		0;
	}
}
```

Highlight `0` and extract choose "Extract to method in class 'C'".

**Expected behavior:**

```ts
class C {
	m() {
		C.newMethod();
	}

	private static newMethod() {
		0;
	}
}
```

**Actual behavior:**

```ts
class C {
	m() {
		this.newMethod();
	}

	private newMethod() {
		0;
	}
}
```

**Comment by TedDriggs** [comment]
This feels like it should be a separate option; static-vs-instance changes the calling convention of the method, and I'm not sure how that would interact with unnamed default export classes.

**Comment by jcready** [comment]
I was always under the impression that a "method" was something that had access to `this` (e.g. an instance of the class). In which case the wording around "Extract to *method* **in** class 'C'" doesn't make sense if the result of performing said action actually extracts it to a static *function* **on** the class constructor.

Can you explain what the you see as the added benefit for utilizing static functions on the class constructor instead of prototype methods in the class?

**Comment by RyanCavanaugh** [comment]
Doesn't seem to user demand for this
