### ISSUE TITLE
"Unused" code action incorrectly removes argument used in the constructor

### ISSUE THREAD

**Issue by Skalman** [Microsoft/TypeScript#24931]
**TypeScript Version:**  3.0.0-dev.20180609

**Search Terms:** unused, code action, constructor, quick fix

**Code**

```ts
export class Example {
  prop: any;
  constructor(private arg: any) {
    this.prop = arg;
  }
}
```

**Expected behavior:**

- VS Code marks `private` as unused.
- Running "Remove declaration for: 'arg'" removes the `private` keyword.

**Actual behavior:**

- VS Code marks the `arg` (in `private arg: any`) as unused.
- Running "Remove declaration for: 'arg'" removes the whole declaration `private arg: any`.

**Playground Link:**  The playground highlighter doesn't mark anything as unused.

**Related Issues:** -

**Comment by mhegazy** [comment]
PRs welcomed.

**Comment by siddhant034** [comment]
I am unable to reproduce this issue. See screenshot.
![issue24931](https://user-images.githubusercontent.com/18205155/41467549-91272102-70c4-11e8-9afd-497b35acb2b3.png)

**Comment by Skalman** [comment]
@siddhant034 It's very strange that `arg` isn't grayed out as unused - on my system it is marked after a few seconds. It does seem as though you also have a code action though. Does it incorrectly remove too much?

![screenshot](https://user-images.githubusercontent.com/138395/41473399-76f4b016-70b9-11e8-94cb-f25d074c8ae7.png)

**Comment by siddhant034** [comment]
@Skalman Yeah, it is incorrectly removing too much. Running "Remove declaration for: 'arg'" removed the whole declaration private arg: any. It should remove only the private keyword.

**Comment by Skalman** [comment]
@siddhant034, where you expecting an answer from me? You're very welcome to implement a fix! :-)

**Comment by mhegazy** [comment]
> Can I take up this issue?

go for it.

**Comment by KnisterPeter** [comment]
@mhegazy I've build a fix which I would consider partial. I need some guidance on how to proceed.

The fix right now assumes that if there is a private modifier on an unused parameter, then it will be removed. This may lead to a new unused warning in case of the whole parameter is unused.
This seems a lot more work to do in one step instead of two.

The `public` and `protected` modifiers are ignored right now. I could add them when the direction of the fix is clear. That should be fairly easy.

Also all kind of test are missing right now.
