### ISSUE TITLE
New definition of PropertyKey does not observe the `keyofStringsOnly` setting

### ISSUE THREAD

**Issue by pelotom** [Microsoft/TypeScript#24945]
**TypeScript Version:**  2.9.2

**Search Terms:** `PropertyKey` `keyofStringsOnly`

**Code**

In `lib.es5.d.ts`, we have now

```ts
declare type PropertyKey = string | number | symbol;
```

however this seems incorrect if `"keyofStringsOnly": true`. So as to observe that setting, it seems like it should be

```ts
declare type PropertyKey = keyof any;
```

**Comment by mhegazy** [comment]
PropertyKey type alias has nothing to do with `keyof` behaviour. `--keyofStringsOnly` controls the behavior of `keyof` to choose whether to use TypeScript 2.9 or pre-TypeScript 2.9 behaviour.

For instance, `Object.hasOwnProperty` accepts a symbol as its input regardless of `--keyofStringsOnly`.

**Comment by pelotom** [comment]
Ok, but `PropertyKey`’s definition was changed in 2.9, coincidentally with the `keyof` change, and it is a breaking change. `—keyofStringsOnly` is supposed to prevent breaking changes in 2.9, so it seems like it should cover this as well.

**Comment by mhegazy** [comment]
> --keyofStringsOnly is supposed to prevent breaking changes in 2.9,

it is not a catch all flag. it is meant for a specific use case.

**Comment by pelotom** [comment]
So `PropertyKey`'s definition was just coincidentally changed to `string | number | symbol` at the same time as the `keyof` change? Why?

**Comment by mhegazy** [comment]
I am not sure i follow. `PropertyKey` was just moved from `lib.es6.d.ts` to `lib.d.ts` to consolidate definitions of `Object` methods. see https://github.com/Microsoft/TypeScript/commit/68ce69a351ad9100b7bd44f3791908bb7e09ff13#diff-a6b488d9bd802977827b535a3011c1f3

**Comment by pelotom** [comment]
I see. I'm not sure why this is suddenly breaking my code in 2.9 then, but oh well 🤷‍♂️. Thanks for the info.

**Comment by nalply** [comment]
Let me add to this issue and point out something I just discovered today.

The definition of `PropertyKey` is a bit too loose for some definitions in `Reflect`, `Proxy` and probably a few more. Numbers will never be encountered in these places. This is not a bug but some surprising hidden JavaScript weirdness: keys are coerced to string **even for arrays**.

Example: `Reflect.ownKeys([42])` gives `[ '0', 'length' ]`.

Perhaps TypeScript should introduce a second, more strict definition like this: `type PropertyKeyOut = string | symbol`?

So that the return type of `Reflect.ownKeys()` in `lib.es2015.reflect.d.ts` can be defined as `PropertyKeyOut[]`?

**Comment by nalply** [comment]
Let me add to this issue and point out something I just discovered today.

The definition of `PropertyKey` is a bit too loose for some definitions in `Reflect`, `Proxy` and probably a few more. Numbers will never be encountered in these places. This is not a bug but some surprising hidden JavaScript weirdness: keys are coerced to string **even for arrays**.

Example: `Reflect.ownKeys([42])` gives `[ '0', 'length' ]`.

Perhaps TypeScript should introduce a second, more strict definition like this: `type PropertyKeyOut = string | symbol`?

So that the return type of `Reflect.ownKeys()` in `lib.es2015.reflect.d.ts` can be defined as `PropertyKeyOut[]`?

**Comment by monfera** [comment]
As luck would have it, I almost filed a TS issue today (ES2015 explicitly says that `Reflect.ownKeys` can only ever return an array of `string` and `symbol` elements) but one [existed already](https://github.com/microsoft/TypeScript/issues/34626) and the [fix](https://github.com/microsoft/TypeScript/pull/41987) got merged a few hours ago 🎉
