### ISSUE TITLE
Intellisense fails to find class in different file unless editing location is last module in file

### ISSUE THREAD

**Issue by AdamTReineke** [Microsoft/TypeScript#2496]
# Description
Intellisense is not provided for a class in the same outer module from a different file unless the inner module being edited is the last module in the file. Using a recent build of Dev14.

# Repro

## item.ts
```typescript
module OuterModule {
	export class Item { }
}
```
## index.ts
```typescript
module OuterModule {
	export module InnerModule {
		interface IFoo {
			get(): Array<Item>;
		}
		class ConcreteFoo implements IFoo {
			//            vvvv Intellisense doesn't provide "Item" as an option
			get(): Array< /*$*/ { 
				throw "Not implemented";
			}
		}
	}
	// If this export comes before InnerModule, Intellisense works as expected.
	export module Maps { }
}
```

**Comment by AdamTReineke** [comment]
TS 1.4

**Comment by mhegazy** [comment]
I can not get a repro for this on the latest from master. @AdamTReineke, can you give the latest a try? the instructions to update the latest: https://github.com/Microsoft/TypeScript/wiki/Dev-Mode-in-Visual-Studio, the script to do that is in: https://github.com/Microsoft/TypeScript/blob/master/scripts/VSDevMode.ps1

**Comment by AdamTReineke** [comment]
@mhegazy Does the PS script pull the latest built language service? Or do I have to enlist and built it myself?

**Comment by mhegazy** [comment]
yeah.. it does not update. just adds a registry setting to point VS to load typescriptServices.js and lib.d.ts from your custom location.

**Comment by DanielRosenwasser** [comment]
@AdamTReineke, you meant completion after the `<` not after the curly brace right? I'm able to repro it *there* if that's what you mean.

**Comment by mhegazy** [comment]
yup. looks like it. sorry about that. it is a bug alright.

**Comment by AdamTReineke** [comment]
Yeah, that was it. Thanks!

**Comment by DanielRosenwasser** [comment]
Editing the issue to clarify.

**Comment by DanielRosenwasser** [comment]
For the sake of documentation, here's what's happenening:

1. While parsing a type reference, the body of the method is assumed to be an object literal type.
2. The object literal type clearly has things wrong with it, and the type reference is missing its `>` token to mark the termination of the type reference.
3. Several levels of error recovery take place, kicking us back to different parsing contexts until we reach the top-level scope.
4. The module `Maps` is assumed to belong to the top-level scope.
5. Since `Maps` is exported, the file itself is considered an external module.
6. Because declarations of external modules don't merge, `OuterModule`'s exports never get merged.
7. That's actually it.

**Comment by mhegazy** [comment]
There does not seem to be a clear fix for this without either having an infinite lookahead, or some re parsing pass.
