### ISSUE TITLE
Support single-module transpilation mode

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#2499]
The compiler does not do emit based on semantic information in most cases. this allows us to provide an api for transpiling a module that does not require typecheck or full program information. just single file syntactic transformation. 
This can be helpful in multiple scenarios, including: typescript-simple (https://github.com/teppeis/typescript-simple), JSPM (#2233), [es6-module-loader](https://github.com/ModuleLoader/es6-module-loader)  and as [atom extensions](https://github.com/atom/atom/pull/5898).

A new compiler flag (--singeFileTranspilation or --disableFullProgramOptimizations for instance) that will make cases that break single file-transpilation an error namely: 1.Const enums defined in ambient modules and 2.Re-exporting types-only constructs when targeting ES6

**Comment by jonathandturner** [comment]
:+1: though we need a good name for the flag :)

**Comment by vladima** [comment]
Proposed implementation #2550.
Regarding the name of the flag: we've already had a long discussion about possible names but all options were non-ideal, Some names that we've tried are: 'separateCompilation', 'singleFileEmit', 'disablGlobalOptimizations', 'safeForTranspile', 'isolated', 'singleFileScope' - we could not pick one since all of them were equally bad. What about moving from the boolean flag and instead have an enum named 'compilationMode' or 'compilationUnit' or something similar? Enum values will be 'program' and 'file' and 'program' will be default.
 
`tsc a.ts b.ts --compilationUnit: file`

**Comment by Ciantic** [comment]
Was this implemented or not? Something was merged, but Visual Studio Code does not transpile on save. It's major pain to transpile and compile all files each time, it causes a lot of file changes and triggers many webpack/browserify processes, time from edit to F5 is really big.

Only tool doing it at the moment single file transpiling is atom-typescript, but it's not using TSC for that.

**Comment by mhegazy** [comment]
@vladima we will need another check for reexporting type-only names in ES6 and in singleFile mode. we also need to update the name of the flag after the next desing meeting discussion.

**Comment by mhegazy** [comment]
PR #3208 renames the flag to `--isolatedModules`

**Comment by mhegazy** [comment]
The flag has been renamed to `--isolatedModules` see PR #3208 for more details.
