### ISSUE TITLE
Unable to narrow parameterized generic types for functions

### ISSUE THREAD

**Issue by lingz** [Microsoft/TypeScript#25039]
**TypeScript Version:**  2.8

**Code**

```ts
function test<T extends 'a' | 'b'>(x: T) {
  if (x === 'a') {
    const z1 = x;
  }
}

function test2(x: 'a' | 'b') {
  if (x === 'a') {
    const z2 = x;
  }
}

```

**Expected behavior:**
`z1` and `z2` should have the same type, which is `a`

**Actual behavior:**
`function test` is unable to narrow parameter x, with the if check, and `z2` resolves to `x`

**Comment by MartinJohns** [comment]
With `strictNullChecks` enabled your code won't even compile, because the type `null` is not compatible with the type `'a' | 'b'`.

Without `strictNullChecks` the value `null` is implicitly compatible with every type. When you call `test(null)` the compiler resolves to `any` because it can't figure out the type of `T`. Based on `null` the compiler can't deduct any sensible type. You **could** expect that it should return `'a' | 'b'`, because `T` must extend from it, but that would still only be a "guess". There's no `T`-type known.

**Comment by lingz** [comment]
I think I communicated the issue wrong, it was not about the actual return type but the type guard in the implementation, I edited the first post to reflect that.
