### ISSUE TITLE
Add no-implicit-union option

### ISSUE THREAD

**Issue by repinvv** [Microsoft/TypeScript#25117]
## Search Terms
implicit, union, inferred

## Suggestion
Please add feature no-implicit-union to treat inferred union types as errors.

## Use Cases
When function has 2 or more branches, people using autocomplete can run into returning wrong field of an object which leads to inferred return type string|number for example, and it leads to errors.

There is, of course, tslint with typedef rule, that forces to specify return type on functions, but it is too strong a rule. It forces me to create interfaces, which i do not want,  in following case:
function(partialArg:IContext) {
   return {
      action1: function ()...
      action2: function() ...
   }
}

## Examples

function getField(obj: SomeType) { // return type is inferred as string | number
if(obj.condition) {
 return obj.stringField;
} else {
 return obj.numberField;
}
}

## Checklist

My suggestion meets these guidelines:
* [ v] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [ v] This wouldn't change the runtime behavior of existing JavaScript code
* [ v] This could be implemented without emitting different JS based on the types of the expressions
* [ v] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mhegazy** [comment]
This used to be the behavior for a long while; users have found that restriction unnecessary, since the type is inferred correctly. we have thus reversed the rule. at this point we have not been getting any feedback about this for a few years now, which leads me to think that most users find the new design better.

The required restriction can be achieved today using tslint rule like https://palantir.github.io/tslint/rules/typedef/
