### ISSUE TITLE
Empty type {} gets inferred to without a warning

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#2511]
```ts
function isOkOf<a>(anything: { isOk: a }) : a {
	return anything.isOk;
}
function notOver<a>(is: (value: a) => boolean) : (value: a) => boolean {
	return function not(value: a) : boolean {
		return !is(value);
	};
}
interface A {
	isOk: boolean;
}
var values : A[] = [{ isOk: true }];

values.map(notOver(isOkOf)); // <-- expected: compilation error, actual: `a` inferred to {} without a warning
```

**Comment by DanielRosenwasser** [comment]
When you say you expect an error, you mean because of the failure to find candidates for type arguments, not for any other reason, right?

If so, this sounds like a duplicate of #2511.

**Comment by aleksey-bykov** [comment]
Somehow I thought #360 was shipped with 1.4, wasn't it?

**Comment by aleksey-bykov** [comment]
https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#stricter-generics

**Comment by DanielRosenwasser** [comment]
No, that relates to if we are unable to find a common supertype as in the following:

```
function f<T>(x: T, y: T) {
    // ...
}

f(10, "hello");
```

**Comment by aleksey-bykov** [comment]
Sorry for the unrelated question, is the milestone for shipping  #360 set?

**Comment by JsonFreeman** [comment]
Your code looks correct, but maybe you are talking about the case where values is not an `A[]`? In that case, isOkOf expects something that has an isOk property, but you will not have one if values is `{}[]` for example.

**Comment by aleksey-bykov** [comment]
Well, I think the code is unsound and vulnerable to refactoring. Consider
```typescript
var values /* : A[] */ = [{ isDeliciousPizza: true }];

values.map(notOver(isOkOf)); // <-- still no warnings
```

**Comment by JsonFreeman** [comment]
I would also add that the compiler does two odd things with your original repro:
* The `a` from notOver is inferred to `{}` because it's fixed before it has any candidates, and we don't report an error on this.
* By the time we have to compare `isOkOf` to `is`, `isOkOf` has been instantiated to any. So even though we never find out that the `a` of `isOkOf` is a boolean, we don't give an error about this.

**Comment by JsonFreeman** [comment]
Yes, the vulnerability you note is my point exactly. Because `isOkOf` is generic, we end of fixing the `a` of notOver, and then we lose the type argument inference we would have gotten. It would be awesome if we could still infer from the structure of `anything`, even though we don't yet know what the `a` of `isOkOf` is yet.

**Comment by JsonFreeman** [comment]
You can test that out by making `isOkOf` not generic. I believe you should now get an error.

**Comment by aleksey-bykov** [comment]
> You can test that out by making isOkOf not generic. I believe you should now get an error.

Weill, whole point it to have `isOkOf` generic for dryer / more reusable code base.

> It would be awesome if we could still infer from the structure of anything, even though we don't yet know what the a of isOkOf is yet.

Wouldn't it? May I dare to ask if there is any chance for TS to ever get Hindley Milner sort of type system?

**Comment by JsonFreeman** [comment]
I mean as a fallback.

**Comment by JsonFreeman** [comment]
I can think of 4 options here:
1. Use contextual signature instantiation during assignability. This would give an error in your original example, and in the delicious pizza example. It also makes the type system much stricter with respect to generics.
2. Give an error when `{}` is inferred because there are no inference candidates. We have discussed this option before, and it never really gained much traction, but we could revisit. Again, it would give an error in both your examples.
3. When the return type of the signature is a function type, we can treat the signature as a curried function and also infer to its return type's parameters. The inferences would come from the contextual type of the call. This would be done recursively until we hit a return type that is not a function type. This would add some complexity in overload resolution, but it's also kind of nice. It would not really make the type system stricter like option 1, just smarter. It would *not* error in your original example, but would error in the delicious pizza example. I think it's my favorite option.
4. Do nothing.

**Comment by JsonFreeman** [comment]
Actually 3 is more complex than I thought. Previously a contextual type could have no effect on a call expression. With this proposal it would. The tricky part is that we'd have to add another condition for fixing type parameters as a result of contextually typing a call expression.

**Comment by JsonFreeman** [comment]
The other complex thing about it is that it messes with the arity of the signature and the number of arguments being passed, and I can't figure out how that would interact with spread and rest.

**Comment by DanielRosenwasser** [comment]
There's a branch that has suggestion 2 called `downWithDreadedCurlyCurly`. Haven't really touched it in a while though.

**Comment by aleksey-bykov** [comment]
I like the best options 1 then 2.
3 - is too specific for the case
4 - doesn't change anything

**Comment by ahejlsberg** [comment]
I'm closing this one since it looks to be covered in #3423.

**Comment by aleksey-bykov** [comment]
@ahejlsberg, I am afraid this request is a related, but separate issue
If so, I would reopen it, consider:

```typescript
interface A<Z> { z: Z }
declare function fn<X extends A<Z>, Z>(value: X): void;
declare var a: A<number>;
fn(a); // <-- a problem: fn<A<number>, {}>
```

I would like the "inferred" empty type was flagged by the compiler.
