### ISSUE TITLE
Re-export from a .d.ts file is not removed when compiling ES modules

### ISSUE THREAD

**Issue by cschleiden** [microsoft/TypeScript#25158]
**TypeScript Version:**  2.9.x

When you have a file `types.d.ts`

```ts
export interface IComponent {
}

export const enum Test {
    Foo,
    Bar
}
```
and re-export this in another module `index.ts`

```ts
export * from "./types";
```

and you compile this to `ES` modules, `index.js` will contain the export from types **even though `types.d.ts` did not result in a module.**

```js
export * from "./types";
```

**Code**
https://github.com/cschleiden/ts-module-repro

**Expected behavior**
`types` export is not output in `index.js`

**Actual behavior**
It is.

**Comment by Alxandr** [comment]
Is this really a bug though? What if you want to export values from a JS library that has typings in a `.d.ts` file?

**Comment by cschleiden** [comment]
Not sure what you mean. If you look at the repro, at runtime `index.js` tries to import (and then export) something from a module that does not exist.

**Comment by Alxandr** [comment]
@cschleiden and how would you expect this to work then? https://gist.github.com/Alxandr/4950f9190dc65def1b3db99c1278d282

Isn't the problem here that you're making a `.d.ts` with no accompanying js file?

**Comment by cschleiden** [comment]
@Alxandr The problem I see is that the TS compiler generates an import to a module that does not exist. Nothing in that module exists at runtime, so even if a corresponding `.js` file would exist, the import would not be required. 

Maybe it's by design, if it is I could live with that, but actually encountered this case in production code and found it confusing.

**Comment by Alxandr** [comment]
@cschleiden And I would again ague that the problem is that you have a `.d.ts` to a module that does not exist. It's like you have a C header file without anything to link agaginst. Due to the way bindings are made, there is no way for TS to know whether or not a module has types to all of the things when you do `export *`. I think removing it would be way more confusing, because you might end up with dependencies on your package breaking because suddenly X wasn't exported anymore and you have no idea why.

**Comment by mhegazy** [comment]
The current design is that export or re-exports of type only declarations are elided. the rational here is the same as that of eliding imports that are only used in type positions.

For this bug, the issue is `const enum`. if the file only included `type` or `interface` declarations it would have behaved as intended.

This is  bug that we need to fix.

**Comment by Alxandr** [comment]
With imports you can guarantee to be right though. With `export * from` (which I argue should probably be a special case), you are stating that "I want everything in X to be available", but the typescript compiler can't guarantee that it knows what "everything" is. If I have typings that are only partyally covering a js library for instance, this could result in the export being removed from the output, changing the result.

**Comment by RyanCavanaugh** [comment]
This is just a misconfiguration. A `.d.ts` file is for describing code that exists elsewhere; just because you only put types in it doesn't mean you should write a .d.ts.
