### ISSUE TITLE
Import suggestions do not find re-exported default exports

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#25246]
**TypeScript Version:**  2.9.2

**Search Terms:** re-export default import

**Code**

```ts
// main.ts
bar
```

``` ts
// export.ts
const bar = 2;

export default bar;

```

``` ts
// re-export.ts
export { default } from "./export";
```

**Expected behavior:** TypeScript/VSCode should suggest imports for `bar` from both `export.ts` and `re-export.ts`.

**Actual behavior:** TypeScript/VSCode suggests imports for `bar` only from `export.ts`, not `re-export.ts`.

![image](https://user-images.githubusercontent.com/921609/41938883-3c3be4c2-798c-11e8-9268-8b8b191efc52.png)

**Playground Link:**  

**Related Issues:** 

**Note**: this *does* work for re-exported named exports.

**Comment by mhegazy** [comment]
> TypeScript/VSCode should suggest imports for bar from both export.ts and re-export.ts.

I do not think this is a desired behavior. think of a big library, e.g. rxjs, subject is exported from multiple modules, you do not want to get a list of 8 diffrent modules to import it from. you want it to import from `rxjs` and that is that.

The current rules that we follow is we prefer the path "closest" to the importing file; that the outer most re-exporting file for external dependencies (e.g. `node_modules\rxjs` instead of `node_modules\rxjs\subject`), and the original file for local dependencies (e.g. `.\foo` instead of `.\foo\index`)

**Comment by OliverJAsh** [comment]
@mhegazy Interesting, thanks. In that case, do you know why this does work as I expected (above) for named exports?

**Comment by mhegazy** [comment]
not sure i understand the question. i would expect it to get it from `export.ts` and not `re-export.ts` since they are in the same folder (the second rule in https://github.com/Microsoft/TypeScript/issues/25246#issuecomment-400464275)

**Comment by OliverJAsh** [comment]
When I try exactly the same thing but with a named export instead of a default export, which is then re-exported, TypeScript/VSCode suggests both the original export and the re-export as possible imports:

```ts
// main.ts
bar
```

``` ts
// export.ts
export const bar = 2;

```

``` ts
// re-export.ts
export * from "./export";
```

![image](https://user-images.githubusercontent.com/921609/41962762-c6c11d2c-79ed-11e8-850b-a3a62c7a5aa5.png)
