### ISSUE TITLE
Argument inferrence for functions passed to overloaded method does not work as intended.

### ISSUE THREAD

**Issue by PaulAvery** [Microsoft/TypeScript#25319]
**TypeScript Version:**  3.0.0-dev.20180629

**Search Terms:** 
Infer, Inferrence

**Code**

```ts
interface Thing {
  method(cb: (problem: string) => void): void;
  method(cb: (problem: string, param: string) => void): string;
}

let thing: Thing;

thing.method(problem => { });
thing.method((problem, param) => {});
```

**Expected behavior:**
In the second call to `method()`, `problem` and `param` are inferred as `string`.

**Actual behavior:**
`problem` cannot be inferred and is therefore implicitly `any`. If the first method-overload is removed, the inferrence works as expected. The first call to `method()` is also inferred as expected.

**Playground Link:** [Click Me.](http://www.typescriptlang.org/play/#src=interface%20Thing%20%7B%0D%0A%20%20method(cb%3A%20(problem%3A%20string)%20%3D%3E%20void)%3A%20void%3B%0D%0A%20%20method(cb%3A%20(problem%3A%20string%2C%20param%3A%20string)%20%3D%3E%20void)%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Alet%20thing%3A%20Thing%3B%0D%0A%0D%0Athing.method(problem%20%3D%3E%20%7B%7D)%3B%0D%0Athing.method((problem%2C%20param)%20%3D%3E%20%7B%7D)%3B)

**EDIT:** Narrowed down example by removing generic on method overload.

**Comment by mhegazy** [comment]
Overload resolution in TS is order dependent. the expectation is that overloads are ordered in declaration from the least general to the most general.

The parameters to `cb` are compared contravariantly, in other words, think of them as the opposite direction of generality.. in other words, you can pass `()=> void` to a function that expects a call back of type `(a)=>void` since it is ok for a function to ignore its parameters..

So `method(cb: (problem: string) => void): void;` is really more permissive/general than `method(cb: (problem: string, param: string) => void): string;`. the correct order of the overloads here is:

```ts
interface Thing {
    method(cb: (problem: string, param: string) => void): string;
    method(cb: (problem: string) => void): void;
}
```

**Comment by PaulAvery** [comment]
Hi, thanks for the quick response.

You are right of course and I appear to be unable to think straight. Sorry for the waste of time.
