### ISSUE TITLE
VSCode doesn't respect sourceRoot in declarationMaps

### ISSUE THREAD

**Issue by michaelaird** [Microsoft/TypeScript#25322]
**TypeScript Version:**  2.9.2

I'm running into an issue when building declaration maps with gulp-typescript/gulp-sourcemaps.

the output of gulp-sourcemaps does this:

```
{"version":3,"sources":["BaseClass.ts"],"names":[],"mappings":"AAAA,kBAAU,UAAU,CACpB;IACI;QAEI,OAAO,CAAC,UAAU,CAAS;;2BAOb,SAAS,EAAK,MAAM;QAK3B,WAAW,IAAI,IAAI;KAI7B;CACJ","file":"Dependency.d.ts","sourceRoot":"../../Dependency"}
```

where the output of tsc does this:

```
{"version":3,"file":"Dependency.d.ts","sourceRoot":"","sources":["../../Dependency/BaseClass.ts"],"names":[],"mappings":"AAAA,kBAAU,UAAU,CACpB;IACI;QAEI,OAAO,CAAC,UAAU,CAAS;;2BAOb,SAAS,EAAK,MAAM;QAK3B,WAAW,IAAI,IAAI;KAI7B;CACJ"}
```

**Expected behavior:**

VSCode should respect sourceRoot and find the source code

**Actual behavior:**

VSCode can't find the declaration when navigating.

I can provide a simple repro if needed.

**Note**

In VSCode, when you try to navigate it does nothing. In VS 15.8.0 Preview 3 it navigates to the d.ts file.

**Comment by weswigham** [comment]
@michaelaird what command line options are you compiling with (your tsconfig settings) when you're using `vscode`?

**Comment by michaelaird** [comment]
When I compile from the command line using tax I’m only using -p to point
at the taco gig file.

I think the issue is VSCode ignoring sourceRoot. Not the difference in
output.

**Comment by weswigham** [comment]
Hmmmmm the only differences I see are that we set `sourceRoot` to `""` and each of the paths in sources to be relative to the sourcemap directly (so `../../Dependency/BaseClass.ts`), while your other sourcemap tool has removed the common path part from all the sources (`../../Dependency`) and placed it as the `sourceRoot` (leaving the source filename as just `BaseClass.ts`).

AFAIK these should function identically. - in both cases applying the sourceRoot to the sourcemaps's dir and joining the filename should yield the same final path.

If anything, `"sourceRoot":"../../Dependency"` from gulp-sourcemaps is missing a tailing slash 🤷‍♂️ 

But anyway - I think I'm going to need more to reproduce your issue; both of those sourcemaps should work fine. Also it'd be nice if you could check if the issue still repros when you use `typescript@next`'s tsserver, since we have made a bunch of fixes to the sourcemaped LS calls recently.

**Comment by vvs** [comment]
I am seeing the same problem with TS 2.9.2, the sourcemaps for *.d.ts files, generated by gulp-sourcemaps are unusable in VS Code (latest insiders), since the navigation is completely disabled.

In the latest TS@next, the navigation is restored, but I end up in the *.d.ts file, *NOT* the actual *.ts file.

The difference between the tsc's generated maps and the ones generated via gulp-sourcemaps, is that:
1. TSC: sourceRoot: "", sources:["../../../../name.ts"]
2. gulp-sourcemaps: sourceRoot: "../..", sources: ["../../name.ts"]

So, the end-result should be the same, but it is not, VS Code properly works with the first version.

**Comment by michaelaird** [comment]
@weswigham I can share a small repro project. where should I send it?

**Comment by michaelaird** [comment]
@weswigham  I sent a small repro to @mhegazy .

**Comment by michaelaird** [comment]
This still fails when project references are used.

Here's a repro: 
[DeclarationMaps.zip](https://github.com/Microsoft/TypeScript/files/2232558/DeclarationMaps.zip)

**Comment by mhegazy** [comment]
@weswigham can you take a look

**Comment by weswigham** [comment]
@michaelaird The `sourceRoot` generated by `gulp-sourcemaps` is off. It's emitting `"sourceRoot":"../../DeclarationMaps/Dependency"`, when it should just be `"sourceRoot":"../../Dependency"`. It looks like your gulp task is moving around the outdir in a way it doesn't respect?

**Comment by michaelaird** [comment]
Yep. you're right. i'll fight with gulp-sourcemaps to sort out the relative paths. sorry about the false alarm!

**Comment by domoritz** [comment]
@michaelaird have you figured out how to get `declarationMap` working with gulp-sourcemaps? Could you share a repo where you used it?
