### ISSUE TITLE
refactoring for removing excessive/impossible cases from the unions in the return type

### ISSUE THREAD

**Issue by zpdDG4gta8XKpMCd** [microsoft/TypeScript#25346]
## Search Terms

https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=is%3Aissue+excessive+cases

## Suggestion

add a refactoring for removing excessive cases from the return types of the functions/methods
```ts
interface A { kind: 'a'; }
interface B { kind: 'b'; }
type C = A | B;
function toA(): C { // <-- problem, the signature promises a wider type that the function can deliver
   const a : A = { kind: 'a' };
   return a;
}
```

## Example
```ts
// before
function toA(): C {
   const a : A = { kind: 'a' };
   return a;
}
```
```ts
// after
function toA(): A {
   const a : A = { kind: 'a' };
   return a;
}
```
## Use Cases

- stricter code, better hygiene, clearer intentions

**Comment by mhegazy** [comment]
So why not just remove all return type annotations?

**Comment by aleksey-bykov** [comment]
um... why not just remove all annotations from everywhere?

let me answer this tough question: because the signature of the function is a contract that says: if you give me this i will give you that

and the body of the function is what fulfills this contract

now in my case the contract is wider than what body is capable off, so the contract is not fulfilled 100% hence all sorts of problems

**Comment by mhegazy** [comment]
> um... why not just remove all annotations from everywhere?

I was not bullying you. i rely meant it. 

there are two scenarios that we have seen, 1. OOP patterns, where the annotation is sometimes meant to be more general than the function, e.g. in the base class with a default implementation. 2. functions with return type using the return type for contextual typing purposes (e.g. literal types).

outside these two scenarios, you are better off having no return type annotations. it is the same as annotating a variable that can be inferred from initalizers. In our code base we have avoided to add return type annotations when not needed for the same reason.

**Comment by aleksey-bykov** [comment]
it's rather a long story, i tried Haskell for awhile, and there like in many alike languages you don't need type annotations at all, you know what i am talking about

so i said, why type more?

quite soon i regretted of my decision because any inconsistent change to a self balancing system creates a cascade of errors, you changed one single function and you get 1000+ errors

that's where type annotations keep it from falling apart

so it's not a question that we need signatures with return types explicitly coded, because the opposite is a complete chaos 

what we need is that type annotation reflect the real state of things

and things go loose/messy very quickly as you refactor the code, so automated check is of great value

**Comment by mhegazy** [comment]
> quite soon i regretted of my decision because any inconsistent change to a self balancing system creates a cascade of errors, you changed one single function and you get 1000+ errors

but is not that what the quickfix would do for you? once you change the type to be more specific you will get a cascade of squiggles down the usage graph.

**Comment by aleksey-bykov** [comment]
my intention is to be as tight as possible, quick fix is supposed to **tighten the signature**, it's a refactoring so it's an opt-in, yes, i want to tighten it to see places where i am still loose

**Comment by aleksey-bykov** [comment]
not sure what your point is, cascade of errors isn't a bad thing, that's what i am looking for, but mind you i want it to be manageable, i don't want to see 1000+ all at once, and explicit signatures help with delivering it gradually, that's why i am all for keeping the signatures, all i am asking about is to automate the process of tightening them, so that if i see the refactoring indicator i know the signature is loose, and i might choose to work on fixing it facing as many errors as needed

**Comment by aleksey-bykov** [comment]
let me put it different way: it could be a tslint rule easily, but last time i tried there is no API exposed by TS that allows to:
- get the flattened union of a given type

i wish i had such API and run my rule matching the types of expressions of all found `return` statements against the flattened union in the result type

**Comment by mhegazy** [comment]
The API exists. `TypeChecker.getTypeAtLocation` on your return expressions.. the hard part is to figure out if it is safe to use replace the type annotation with he new one.

**Comment by RyanCavanaugh** [comment]
This doesn't seem like a common scenario
