### ISSUE TITLE
SyntaxTree and SyntaxWalker in new compiler

### ISSUE THREAD

**Issue by ashwinr** [microsoft/TypeScript#254]
Hi: [tslint](https://github.com/palantir/tslint) uses SyntaxTree and tree walkers extensively for implementing linter rules on top of the compiler (e.g. https://github.com/palantir/tslint/blob/master/src/rules/classNameRule.ts). It looks like the visitor pattern is not present in the new compiler (at least I couldn't find it in the master branch). But languageService-v2 still has it. Can someone please explain if the syntax tree will be present in the new compiler? Because otherwise tslint needs to completely rethink its existing rule implementations for the new compiler. Thanks!

**Comment by lptr** [comment]
Is there any news about this? Will we be able to walk an AST with a visitor? Thanks.

**Comment by DanielRosenwasser** [comment]
We no longer use the `SyntaxTree` type from the &#8804;1.0 compiler. Instead we use `Node` and all types derived from it (see [src/compiler/types.ts](https://github.com/Microsoft/TypeScript/blob/6f6c46a99f446144702bb324f6b50d94a000a690/src/compiler/types.ts#L333)). The language service [augments `Node`](https://github.com/Microsoft/TypeScript/blob/6f6c46a99f446144702bb324f6b50d94a000a690/src/services/services.ts#L14).

Instead of visitors/walkers, we use `forEachChild` in a mutually recursive fashion.

```TypeScript
function getAllBinaryExpressions(root: ts.Node) {
    var result: ts.BinaryExpression[] = [];
    aggregate(root);

    return result;
    
    function aggregate(node: ts.Node): void {
        if (node.kind === ts.SyntaxKind.BinaryExpression) {
            result.push(<BinaryExpression>node);
        }
        
        ts.forEachChild(node, aggregate);
    }
}
```

We are planning to expose a preview of an API as mentioned in #372.

**Comment by ctaggart** [comment]
How do we get a `ts.Node` from a `String`? I'm looking something similar to [this in the old api](https://github.com/ctaggart/TsAst/blob/master/app.ts#L27-L34).

**Comment by basarat** [comment]
Great idea guys, *feels* much nicer :heart:
