### ISSUE TITLE
Error: Initializer of instance member variable 'x' cannot reference identifier 'y' declared in the constructor.

### ISSUE THREAD

**Issue by mpawelski** [Microsoft/TypeScript#2548]
I got this error:
>Initializer of instance member variable 'objectWithFunc' cannot reference identifier 'param' declared in the constructor.

for this piece of code:
```
interface ITest {
    foo: string;
    bar: string;
}

var param: ITest = null;

class Test {    

    constructor(param: ITest) {        
    }

    method() {        
        console.log(param.foo);
    }

    private objectWithFunc = {
        func: () => {
            console.log(param.foo);            
        }
    }
}
```
When I change parameter name in constructor to other name (for example `constructor(param2: ITest)`) it compiles. 

This behaviour was surprising for me. Is it a bug?

**Comment by mpawelski** [comment]
I'm using Typescript 1.4 with Visual Studio Community 2013.

**Comment by mhegazy** [comment]
This is by design. Property initialization happens as part of constructying the object. the compiler will generate it as part of the constructor, that means that your constructor parameter "param" will shadow the variable "param" at runtime. this error message is letting you know that this is going to happen.

so the following ts code:
```ts
var param = null;
class Test {    
    constructor(param) {        
       //constructor body 
    }
    private property = param; // initialization
}
```
will be transformed to:

```js
var param = null;
var Test = (function () {
    function Test(param) {
        this.property = param; // initialization
        //constructor body 
    }
    return Test;
})();
```
