### ISSUE TITLE
"update path on file move" refactoring not working for node

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#25493]
_From @g3offrey on July 6, 2018 9:18_

 

Hi folks 👋 

First of all thank you for your hard work. Each month I'm amazed how Code is becoming an unique awesome piece of software 😄 

I'm opening a ticket because I encounter an issue with "_update path on file move_" refactoring.

Here's are information about it : 

- VSCode Version: 1.25.0
- OS Version: MacOS 10.13.4

Steps to Reproduce:

1. clone https://github.com/g3offrey/example-node-repository
2. try to move file from folder1 to another folder or to the root
3. check if the require path in index.js is updated

Does this issue occur when all extensions are disabled?: Yes

If I can do something to help, don't hesitate to ask me.
Thank you 👍 

_Copied from original issue: Microsoft/vscode#53681_

**Comment by mjbvz** [comment]
@andy-ms Looks like getEditsForFileRename does not work for `require`?

**Comment by andy-ms** [comment]
@mjbvz The following fourslash test already passes:
```ts
/// <reference path='fourslash.ts' />

// @allowJs: true

// @Filename: /folder1/file1.js
////module.exports = { a: 0 };

// @Filename: /index.js
////const { test } = require('./folder1/file1');

verify.getEditsForFileRename({
    oldPath: "/folder1/file1.js",
    newPath: "/file1.js",
    newFileContents: {
        "/index.js": `const { test } = require('./file1');`,
    },
});
```

The problem seems to be that when `file1.js` doesn't contain the `export` keyword anywhere, vscode never makes a `getEditsForFileRename` request. In the example repository, if you add `export const y = 0;` to the bottom of `file1.js`, vscode will start making the request and the rename will work.

**Comment by g3offrey** [comment]
Hi @mjbvz, @andy-ms 👋 

I'm the little guy who opened the issue on Code repo.

After I read your message @andy-ms I explored the repos and thanks to your help I found this commit : https://github.com/Microsoft/vscode/commit/1ee1759e02e343d580acde78238db3acbad8a13d
I guess the issue is here.

Maybe it's finally linked to Code and not Typescript. 
Should I update the ticket on Code side ? 

I guess the solution would be to change the regex from `\bexport\b` to `\bexports?\b` (so it handle `module.exports`). I'm creating a PR for that 😄
