### ISSUE TITLE
Spread tuple parameters don't impact function arity

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#25559]
```ts
declare function call<TS extends unknown[]>(
    handler: (...args: TS) => void,
    ...args: TS): void;
  
call((x: number, y: number) => x + y);
call((x: number, y: number) => x + y, 1, 2, 3, 4, 5, 6, 7);
```

**Expected**:

```
Expected 3 arguments, but got 1.
Expected 3 arguments, but got 8.
```

**Actual**: No error.

**Comment by ahejlsberg** [comment]
Note that with `--strictFunctionTypes` the example above is checked differently:

```ts
call((x: number, y: number) => x + y);  // Error: Argument of type '(x: number, y: number) => number' is not assignable to parameter of type '() => void'.
call((x: number, y: number) => x + y, 1, 2, 3, 4, 5, 6, 7);  // No error
```

Because the `x: number` and `y: number` parameters occur in contra-variant positions, inferences from them are given lower priority. Therefore, the chosen inference for `TS` is the tuple type created from the argument list, i.e. `[]` in the first call and `[number, number, number, number, number, number, number]` in the second call. This causes the incompatible function type error in the first call, but no error in the second call since a function is free to ignore additional parameters.

The fix in #25608 doesn't change this behavior and arguably it is just as correct as the arity errors. Indeed, it is consistent with this example:

```ts
call((x, y) => x + y, 10, 20);
```

Here the inference is made from the `10, 20` in the argument list, regardless of function type strictness.

It would be nice if there wasn't a difference between strict and non-strict here, but we'd likely have to skew it towards the strict function types behavior as it is more consistent.
