### ISSUE TITLE
Duplicate `"use strict"` prologue in the generated output. 

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#25550]
Duplicate `"use strict"` prologue in the generated output. 

See https://raw.githubusercontent.com/Microsoft/TypeScript/master/lib/tsc.js

**Comment by a-tarasyuk** [comment]
@mhegazy @weswigham 

[_TS transformer_](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/transformers/ts.ts#L102) uses `node.prepends`, which includes `build/local/compiler.js` ([`createInputFiles`](https://github.com/Microsoft/TypeScript/blob/fd007e747da92287ea680d02dfbf5867fa97b4ce/src/compiler/factory.ts#L2634), [`node.javascriptText`](https://github.com/Microsoft/TypeScript/blob/527093c758e9cbeee2240e701be881e3caefdf9b/src/compiler/program.ts#L1282)). ` compiler.js` has own `"use strict"` definition - _it is the first `"use strict"`_

_The second `"use strict"`_ _TS transformer_ adds in the method [`visitSourceFile`](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/transformers/ts.ts#L563
) because the following condition does not check `"use strict"` definition  in the `node.prepends`

```typescript
const alwaysStrict = getStrictOptionValue(compilerOptions, "alwaysStrict") &&
   !(isExternalModule(node) && moduleKind >= ModuleKind.ES2015) &&
   !isJsonSourceFile(node);
```

as the result, `tsc.js` contains `"use strict";"use strict";` 

Does that make sense? What do you think?

**Comment by weswigham** [comment]
Yep, that's exactly the problem. To fix it, we need to instantiate a scanner and scan the first of the prepends to see if it already has a use strict statement.

**Comment by weswigham** [comment]
Actually, we should scan all of them and remove any prologues we find and unify them/move them to the top. That has interesting implications for souremapping, too.

**Comment by weswigham** [comment]
@a-tarasyuk Keeping them in the intermediate outputs is fine (heck, we should probably even error if they don't all have the same set of prologues - concating a loose file to a strict in could be bad!) - we just need to remove them when concatenating and fixup the resulting concatenated sourcemaps.

**Comment by a-tarasyuk** [comment]
@weswigham thanks. For instance, during concatenation, we need to remove "use strict" prologue directly in `javascriptText`(_string representation_). is is true? I just want to fix and make PR, if you don't mind. :)

**Comment by a-tarasyuk** [comment]
@weswigham I thought that we could track `"use strict";` prologue when the compiler builds `prepends` - [`getPrependNodes`](https://github.com/Microsoft/TypeScript/blob/527093c758e9cbeee2240e701be881e3caefdf9b/src/compiler/program.ts#L1262), however, it is not true.

**Comment by weswigham** [comment]
Yeah. Instead you wanna create a scanner and scan the text and check the type of the first token.
