### ISSUE TITLE
Unexpected props type for React component with constructor

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#25581]
**TypeScript Version:**  2.9.2

**Search Terms:** react component props type constructor implicit any hoc

**Code**

```ts
type RouteComponentProps = {
    history: {};
};

type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;

declare function withRouter<P extends RouteComponentProps>(
    component: React.ComponentType<P>,
): React.ComponentClass<Omit<P, keyof RouteComponentProps>>;

type FooProps = { foo: string } & RouteComponentProps;
class Foo extends React.Component<FooProps> {
    constructor(props) {
        super(props);
    }
}

// Expect error due to missing props, got one :-)
const a = <Foo />;
// Expect error due to missing props, got one :-)
const b = <Foo foo="1" />;

// However, after using a (correctly defined) HOC, the props type seems to go completely

const Foo2 = withRouter(Foo);

// Expect error due to missing props, but got none :-(
const c = <Foo2 />;
```

… unless we comment out the constructor, or annotate the `props` param:

```ts
class Foo extends React.Component<FooProps> {}

const Foo2 = withRouter(Foo);

// Expect error due to missing props, got one :-)
const c = <Foo2 />;
```

```ts
class Foo extends React.Component<FooProps> {
    constructor(props: Props) {
        super(props);
    }
}

const Foo2 = withRouter(Foo);

// Expect error due to missing props, got one :-)
const c = <Foo2 />;
```

Why does the presence of the constructor change the props type only after the component is ran through the HOC?

**Comment by OliverJAsh** [comment]
I tried to further narrow down the issue. This is where I got to:

``` ts
declare function getComponentProps<P>(
    component: React.ComponentType<P> | React.Component<P>,
): P;

type GetComponentProps<T> = T extends React.ComponentType<infer P> | React.Component<infer P> ? P : never

type FooProps = { foo: string };
class Foo extends React.Component<FooProps> {
    // props param is implicitly `any`
    // Workaround: if we annotate the param, `FooPropsInferred2` will have the expected type
    // constructor(props: FooProps) {
    constructor(props) {
        super(props);
    }
}

// $ExpectType { foo: string }
// and got :-)
type FooPropsInferred = GetComponentProps<Foo>;

const x = getComponentProps(Foo);
// $ExpectType { foo: string }
// but got any
type FooPropsInferred2 = typeof x;
```

**Comment by mattmccutchen** [comment]
I narrowed the issue down further and removed the React dependency:
```ts
class Component<P> {
    props: P;
    constructor(props: P) {
        this.props = props;
    }
}

interface ComponentClass<P> {
    new (props: P): Component<P>;
}

declare function getComponentProps<P>(
    component: ComponentClass<P>,
): P;

declare function getComponentProps2<T>(
    component: T,
): T extends ComponentClass<infer P> ? P : never;

type FooProps = { foo: string };
class Foo extends Component<FooProps> {
    // props param is implicitly `any`
    // Workaround: if we annotate the param, `FooPropsInferred2` will have the expected type
    // constructor(props: FooProps) {
    constructor(props) {
        super(props);
    }
}

const x = getComponentProps(Foo);  // any
const y = getComponentProps2(Foo);  // FooProps
```
In each case, there are two inferences for `P`: an `any` from the constructor parameter and a `FooProps` from the props of the constructed object.  It looks like the root cause of the difference is that inference in conditional types is always performed with the equivalent of `strictFunctionTypes` enabled, while I'm assuming `strictFunctionTypes` was at its default value of off for the `getComponentProps` call.  Glossing over a bunch of detail I don't fully understand, `strictFunctionTypes` affects the way the two inferences are prioritized.  If you enable `strictFunctionTypes` in `tsconfig.json`, then the discrepancy goes away.

I assume the inference was implemented the way it was for a reason, though I don't know the reason.  I think the solution to this case is "use `noImplicitAny`"; I don't think it merits changing anything in the compiler.

**Comment by mhegazy** [comment]
thanks @mattmccutchen for the detailed analysis. implicit `any` is not any different from explicit `any` from a type perspective. inference will proceed from both the same way.

I think the underlying issue here is an expectation that derived class methods, properties, and constuctors "inherit" their types from the base class. that is unfortunately not the case, this is tracked by https://github.com/Microsoft/TypeScript/issues/23911 (previously discussed in https://github.com/Microsoft/TypeScript/issues/1373, https://github.com/Microsoft/TypeScript/issues/3667, and https://github.com/Microsoft/TypeScript/pull/10610).

**Comment by OliverJAsh** [comment]
> If you enable strictFunctionTypes in tsconfig.json, then the discrepancy goes away.

I just tried this on TypeScript 2.9.2 and the discrepancy does not go away when `strict` is enabled, so I'm not sure this does explain the problem. Can we take another look at this?

**Comment by OliverJAsh** [comment]
Closing as apparently this is working as intended.
