### ISSUE TITLE
mapRoot/sourceRoot write sourcemaps using absolute local paths, not URIs

### ISSUE THREAD

**Issue by roblourens** [Microsoft/TypeScript#25587]
From https://github.com/Microsoft/vscode/issues/54026

```json
//tsconfig.json

{
    "compilerOptions": {
        "sourceMap": true,
        "sourceRoot": "src/",
        "mapRoot": "build/"
    }
}
```

`./src/hello.ts` exists

**Actual**

I run `tsc` and get:

hello.js:
```js
console.log("hello world!");
//# sourceMappingURL=/Users/roblou/Downloads/tsTest/build/hello.js.map
```

hello.map.js:
```
{"version":3,"file":"hello.js","sourceRoot":"/Users/roblou/Downloads/tsTest/src/","sources":["hello.ts"], ...
```

**Expected**

This stuff is not clearly spec'd but my understanding is that sourceMappingURL and sourceRoot should be URIs or relative paths, not local absolute paths. In a browser, a path starting with / should be interpreted as relative to the webserver root. 

In Node, Chrome Devtools handles this on Mac, but on Windows, it can't handle a sourceMappingUrl or sourceRoot as a windows-style absolute path. That is what convinces me that this is worth fixing on TS's end.

In vscode, I plan to try to support this scenario somehow, since it previously worked.

**Comment by mhegazy** [comment]
Looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/23180. should be fixed by https://github.com/Microsoft/TypeScript/pull/23989. can you give `typescript@next` a test and let us know if you are still running into issues.

**Comment by mhegazy** [comment]
the sourceRoot / mapRoot are used verbatim. so you can have in there whatever you want, the compiler does not really change these. so you can use `/` to refer to your site root for instance.

**Comment by roblourens** [comment]
I see, I basically get the behavior I expect without those options or just with `outDir`, and these are for someone who wants to override that in some specific situation.

**Comment by dball-adashi** [comment]
We set up our build process leveraging the absolute paths provided by this feature.  Since we build our libraries (individual packages) and then move them to other node_modules folders, the absolute paths worked great.  That is until we needed to develop/debug on OSX.  The source-map-loader webpack loader does not appear to be able to differentiate between an absolute and relative path on a unix style OS like OSX.   While investigating this, we found that if you set the sourceRoot from the command line, it works completely differently than if you set it in the tsconfig.json file.  We are still on tsc version 2.6.2.  The only way to get the absolute path when setting sourceRoot from the command is to pass it in as "$pwd/src".  There appears to be no way to not have the sourceRoot produce a non absolute path if you set sourceRoot in the tsconfig.json file.

Through experimentation, we have found a work around to this.  But it is a bit quirky.  We need to write a post processor for each map file so after it is copied to its target location, the sourceRoot or sources are modified so they work in their new location.  In an ideal world:
1) tsc would work consistently between the settings in the tsconfig.json and the cli options and we could indicate we wanted absolute paths or relative for the two different use cases different developers use.
2) source-map-loader would not have an issue with these absolute paths on linux 

If you already addressed these items, thank you.  If not, hopefully this additional scenario will help.
