### ISSUE TITLE
Visual Studio 2012 and higher versions of TypeScript than 1.0

### ISSUE THREAD

**Issue by chrisaswain** [Microsoft/TypeScript#2564]
Even though Visual Studio 2012 doesn't officially support later versions of TypeScript than 1.0, is there a way to force the plugin to use a later version of the TypeScript compiler?

I do Xbox One media app development and am therefore forced to stay on VS 2012.  We use TypeScript for our project and would like to take advantage of the faster compiler and newer features that are not part of 1.0.

**Comment by mhegazy** [comment]
We have stopped adding new features to VS2012; TypeScript 1.0.1 was the last supported release for VS2012. We have then moved to VS2013, and V2015. See the [TS 1.0.1 release blog](http://blogs.msdn.com/b/typescript/archive/2014/05/13/announcing-typescript-1-0-1.aspx) for more information.

The interfaces between our components have changed quite much since that release, and there is not a way I can think of to get latest bits on 2012 at this point. 

Would it be possible to isolate your TypeScript components on a single project and use that with VS2013/VS2015?

**Comment by chrisaswain** [comment]
That's an interesting idea.  I think that might be possible.  I'll have to experiment.  Thanks for the suggestion and quick response!

**Comment by rahulgarg1985** [comment]
We are using VS2012. Do we have any way to use TypeScript advanced version like 1.5 Beta on VS2012 ?
Can we use  1.5 Beta with Sublime or Bracket IDE ?

**Comment by DanielRosenwasser** [comment]
Our [TypeScript Sublime Plugin](https://github.com/microsoft/typescript-sublime-plugin) currently uses the 1.5 beta release.

From what I can see, there are a couple of plugins for Brackets that support 1.4 (and only bump on stable releases), but since 1.5 should be out soon ideally, they should be on 1.5 in the near future. - maybe @fdecampredon and @tomsdev can weigh in.

**Comment by rahulgarg1985** [comment]
@DanielRosenwasser : Thanks for your response. Is there any way to use 1.5 in   VS2012 ?

**Comment by DanielRosenwasser** [comment]
Unfortunately as @mhegazy mentions above, the architecture of our language service has changed in such a way that we cannot easily support 1.5 in VS2012. When VS 2015 is released, we will have support for that.

Also you may want to look into [Visual Studio Code](https://code.visualstudio.com/), an editor which not only supports TypeScript 1.5-beta, but is partially built in it as well.

**Comment by rahulgarg1985** [comment]
Thanks for quick response. :+1:

**Comment by kazeem** [comment]
Hello Everyone!

As i see from above comments that later versions of Typescript (>1.0) are not supported in VS2012. Is it possible to use Angular2 and Typescript(<1.0) in Visual studio 2012. If yes can you share a sample project for demonstration.

Thanks :)
