### ISSUE TITLE
isNewIdentifierLocation is always set to true inside function call

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#25691]
**TypeScript Version:**  3.0.0-dev.20180713

**Search Terms:** 
- isNewIdentifierLocation
- completions
- suggest

**Bug**
The `completionInfo` request seems to always return `isNewIdentifierLocation` when inside a function call such as:

```ts
console.log(c|)
```

**Expected behavior:**
I believe that `isNewIdentifierLocation` should only be returned when the user is starting to write a arrow function with a parenthesized parameter list, such as:

```ts
(c|)
```

or

```ts
console.log((c|)
```

**Comment by mjbvz** [comment]
@andy-ms One case we are interested in here is whether to enable accepting completions on `,` or not. I think `,` should commit for `c|` when the user is going to type `c => c + 1` but not for `(c|) => c + 1`

I think we could do this with the extra information you are propose

**Comment by highco** [comment]
The bug is still present in TypeScript 3.2.2. It's quite annoying, because in all IDEs, the autocomplete match doesn't get inserted in situation where you would expect it to be inserted.

I think the value of `isNewIdentifierLocation` should depend upon whether an arrow function is valid at the current location. For example:

```
function demo(a:number, b:(x:number) => void)
{
}

demo(a|     // an arrow function isn't valid here, isNewIdentifierLocation should be false
demo(a, b|  // an arrow function is valid here, isNewIdentifierLocation should be true
```
