### ISSUE TITLE
Diagnostics should not include absolute paths

### ISSUE THREAD

**Issue by evmar** [Microsoft/TypeScript#25747]
**TypeScript Version:**  3.1.0-dev.20180717, older verisons too

**Search Terms:** absolute path diagnostics

**Code**

```ts
// foo.ts
export {};
// bar.ts
import {nosuch} from './foo';
```

**Expected behavior:**
Error message about `nosuch` that mentions paths relative to the project.

**Actual behavior:**
Error message includes absolute path:

```
$ tsc
bar.ts:1:9 - error TS2305: Module '"/usr/local/google/home/evanm/t/foo"' has no exported member 'nosuch'.

1 import {nosuch} from './foo';
          ~~~~~~
```

This matters because:
* it's confusing and inconsistent with other error messages
* we don't want to include private paths in error messages
* if the editor services is running in the cloud or whatever then it references bogus paths

**Comment by fearthecowboy** [comment]
I don't suppose this is customizable via `tsconfig.json` at all?

I have a monorepo that I'm using rushjs to build that has multiple projects in, and now when I build everything, the paths come out as relative paths, which doesn't help because they are each relative to their individual project roots.
