### ISSUE TITLE
Error inferring type when using argument

### ISSUE THREAD

**Issue by mc-petry** [Microsoft/TypeScript#25825]
**TypeScript Version:**  2.9.2, 3.0.0-rc

**Search Terms:** generic, inference

**Code**

```ts
type Obj<T> = { data: T }

type HR<T> = () => (value: T) => any

type Pipe = <T>(
  fn: (arg: string) => Obj<T>,
  ...ops: HR<T>[]
) => void

// Demo:

let pipe: Pipe
let obj: Obj<{ data: string }>
let operator: <T>(fn: (hr: { result: T }) => any) => HR<T> 

// Ok:
pipe(
  () => obj,
  operator(s => s.result.data)
)

// Error:
pipe(
  a => obj,
  operator(s => s.result.data)
)
```

**Expected behavior:**

No error on second usage of method `pipe(...)`

**Actual behavior:**

Error on inferring previous type when using function argument

**Playground Link:** [link](http://www.typescriptlang.org/play/#src=type%20Obj<T>%20%3D%20%7B%20data%3A%20T%20%7D%0D%0A%0D%0Atype%20HR<T>%20%3D%20()%20%3D>%20(value%3A%20T)%20%3D>%20any%0D%0A%0D%0Atype%20Pipe%20%3D%20<T>(%0D%0A%20%20fn%3A%20(arg%3A%20string)%20%3D>%20Obj<T>%2C%0D%0A%20%20...ops%3A%20HR<T>%5B%5D%0D%0A)%20%3D>%20void%0D%0A%0D%0A%2F%2F%20Demo%3A%0D%0A%0D%0Alet%20pipe%3A%20Pipe%0D%0Alet%20obj%3A%20Obj<%7B%20data%3A%20string%20%7D>%0D%0Alet%20operator%3A%20<T>(fn%3A%20(hr%3A%20%7B%20result%3A%20T%20%7D)%20%3D>%20any)%20%3D>%20HR<T>%20%0D%0A%0D%0Apipe(%0D%0A%20%20()%20%3D>%20obj%2C%0D%0A%20%20operator(s%20%3D>%20s.result.data)%0D%0A)%0D%0A%0D%0Apipe(%0D%0A%20%20a%20%3D>%20obj%2C%0D%0A%20%20operator(s%20%3D>%20s.result.data)%0D%0A))

**Related Issues:**

**Comment by ahejlsberg** [comment]
This is effectively a design limitation of our type inference algorithm. The difference between the two test cases is that `() => obj` is not _contextually sensitive_ whereas `a => obj` is (a function expression is said to be contextually sensitive when it has arguments without type annotations). We defer type inference for contextually sensitive arguments such that we can make as many candidate inferences as possible for type variables before we freeze and use the inferences to assign types to the parameters of the contextually sensitive function expressions. In the second example this means that we infer from the second argument (`operator(s => s.result.data)`) before we infer from the first argument (`a => obj`) and that causes us to miss the inference from `obj` to `T` because we have already frozen `T`.

The second example works if you write the first argument as `(a: string) => obj` since the argument is then no longer contextually sensitive.

We _might_ be able to do better by realizing that a the contextual type for a function expression references no type parameter in its parameter list and not deferring inference in that case. But I'm not sure how generally useful that optimization would be.

**Comment by Eliav2** [comment]
this should be labeled as a bug and be treated as one and not as a design limitation.

just for reference see annoying this is;
```ts
interface Test<S> {
  func1: (arg) => S;
  func2: (arg) => any;
}

function createTest<S>(arg: Test<S>): Test<S> {
  return arg;
}

createTest({
  func1: () => {
    return { name: "eliav" };
  },
  func2: (arg) => {
    console.log(arg.name); //works - name is recognized
  },
});
createTest({
  func1: (arg) => {
    return { name: "eliav" };
  },
  func2: (arg) => {
    arg; // type unknown, why?
    console.log(arg.name); //ERROR - name is NOT recognized
  },
});
```

there is no workaround around this? i want to use inferring to create autosuggestions to my users in their IDEs
