### ISSUE TITLE
Autocomplete doesn't work with extends constraint

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#25837]
**TypeScript Version:**  3.1.0-dev.20180717

**Search Terms:**

**Code**

```ts
interface A {a: number;}
function foo<T extends Partial<A>>(a: T){ return a }
foo({ /* autocomplete doesn't work */ })

function foo(a: Partial<A>){ }
foo({ /* autocomplete works! */ })
```

**Expected behavior:**
autocomplete should work

**Actual behavior:**
doesn't work

**Playground Link:** 

**Related Issues:**

**Comment by mhegazy** [comment]
Completions rely on the contextual type at the location. in the first case, `{}` is a valid type to instantiate `foo` with, since it is a sub type of `Partial<A>`. so `foo({})` resolves, `T` is inferred to be `{}`, the contextual type is `{}`. and thus no completions.

in the second case, there is a contextual type, and you get completions.

**Comment by cevek** [comment]
Ok, I get that. It is not a bug. 

I think no problem to implement this like a feature
We just need to calculate completion based on a constraint

Now it's very annoying that this simple case don't give you a completion, but if you will type a wrong prop - ts will throw. 

This feature also will resolve  #25549

**Comment by cevek** [comment]
Actially I think this is bug because if there is a some non null props in an extends constraint then autocomplete works fine
```ts
function abc<T extends { x: number; y?: number; z?: number;  }>(t: T) {
    return t;
}
abc({ / * autocomplete works here */ });
```
