### ISSUE TITLE
Warn on function returning `unknown` with no return statement

### ISSUE THREAD

**Issue by ghost** [microsoft/TypeScript#25885]
**TypeScript Version:**  3.1.0-dev.20180721

**Code**

```ts
function f(): unknown { ""; }
function g(): string | undefined { ""; }
```

**Expected behavior:**

Both `f` and `g` are errors.

**Actual behavior:**

Only `g` is an error.

**Comment by chharvey** [comment]
This issue seems to not be fixed yet:

```ts
function empty(): unknown { // Error 
}
function returnNothing(): unknown { // no error
    return;
}
let anon: () => unknown = () => {}; // no error  
```

**Expected behavior:**
Defining a function of type `() => unknown` without a return statement in the body should not result in an error, since `void` is assignable to `unknown`.

**Actual behavior:**
> Error: A function whose declared type is neither 'void' nor 'any' must return a value.

**Playground Link:** [playground link](https://www.typescriptlang.org/play/index.html#src=function%20empty()%3A%20unknown%20%7B%20%2F%2F%20Error%20%0D%0A%7D%0D%0A%0D%0Afunction%20returnNothing()%3A%20unknown%20%7B%20%2F%2F%20no%20error%0D%0A%20%20%20%20return%3B%0D%0A%7D%0D%0A%0D%0Alet%20anon%3A%20()%20%3D%3E%20unknown%20%3D%20()%20%3D%3E%20%7B%7D%3B%20%2F%2F%20no%20error%0D%0A)

**Comment by jthomerson** [comment]
Adding another example that shows what I feel is also weird behavior ... if you simply add a return statement in _any_ code path, the error goes away, even though for all the other code paths nothing has actually changed.

```ts
function errors(a: boolean): unknown {
    if (a) {
    }
}

function doesNotError(a: boolean): unknown {
    if (a) {
        return;
    }
}
```

[Playground Link](https://www.typescriptlang.org/play/#src=function%20errors(a%3A%20boolean)%3A%20unknown%20%7B%0D%0A%20%20%20%20if%20(a)%20%7B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20doesNotError(a%3A%20boolean)%3A%20unknown%20%7B%0D%0A%20%20%20%20if%20(a)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%3B%0D%0A%20%20%20%20%7D%0D%0A%7D)

**Comment by dragomirtitian** [comment]
@RyanCavanaugh  I want to pick this up but it is not really clear to me what the behavior should be.
The original suggestion was to **have** an error on functions returning `unknown`.

In @chharvey 's example he mentions the he actually expects to **not have** an error when creating a function that returns `unknown` since `void` is assignable to `unknown`.

> Defining a function of type `() => unknown` without a return statement in the body **should not result in an error**, since `void` is assignable to `unknown`.

The one bit of inconsistency here IMO is that  `let anon: () => unknown = () => {};` is not raise an error. Maybe we could issue an error in this case as well although I am not sure that this is in the scope of this bug.

@jthomerson 's example behaves exactly as a function returning `undefined` does 

```ts
function errors(a: boolean): undefined {
    if (a) {
    }
}

function doesNotError(a: boolean): undefined {
    if (a) {
        return;
    }
}
```
So I don't think changing  anything for `unknown` is in the scope of this issue. Maybe we should consider forcing a return statement on all branches, even if the return type contains `undefined` although that would be a breaking change and a different discussion that was probably already had.

**Comment by DavidMarquezF** [comment]
Is there any workaround for this? Something such as excluding void from unknown in some way?

**Comment by chharvey** [comment]
Excluding `void` from `unknown` is a bad idea IMO, since `unknown` is supposed to be the “top type” or “universal type” — it is a supertype of every other type. That includes `void`. If you’re looking for way to annotate a function that returns a non-undefined value, try `Object` for any value including primitives, or `object` for any non-primitive value.

```ts
function returnSomeValue(): Object {
   return 42;             // returning a primitive is fine
   return {};             // returning a POJO is fine
   return new Array();    // returning a class instance is fine
   return;                // ERROR: `undefined` is not assignable to `Object`
   // no return statement // ERROR: must return a value
}
function returnSomeNonPrimitiveValue(): object {
   return 42;             // ERROR: primitive is not assignable to `object`
   return {};             // returning a POJO is fine
   return new Array();    // returning a class instance is fine
   return;                // ERROR: `undefined` is not assignable to `Object`
   // no return statement // ERROR: must return a value
}
```
(POJO = plain old javascript object)

**Comment by RyanCavanaugh** [comment]
I think the desirable behavior would be that you're allowed to implicitly return from a function if the annotated return type is assignable from `undefined`, and that `noImplicitReturns` controls whether or not you're allowed to implicitly return

**Comment by RyanCavanaugh** [comment]
These are unified now
