### ISSUE TITLE
Can't use default parameter value if its type a generic

### ISSUE THREAD

**Issue by pleerock** [Microsoft/TypeScript#25918]
Following works fine:

```ts
function a<T extends Object>(p: T) { // good
}
a(Object); // good
```

however this does not work:

```ts
function a<T extends Object>(p: T = Object) { // error
}
a(Object); // good
```

same happens with other types:

```ts
function a<T extends number>(p: T = 1) { // error
}
a(1); // good
```

Results into `Type 'ObjectConstructor' is not assignable to type 'T'` error.

I came into this issue from a different scenario where I tried to use Object in a following way:

```ts
export type Constructor<T = {}> = new (...args: any[]) => T;
export const Taggable = <T extends Constructor>(base: T = Object) => class extends base {
    tags: any[] = [];
}
```

**Comment by mattmccutchen** [comment]
This is working as intended.  The problem is that if someone calls your function with `T` set to a subclass of `Object`, such as `string`, then the default parameter value would not be a valid value of type `T`.  It's probably cleanest to define a separate function for the case where you pass no arguments and want to use `Object`.  If you really want to use a single function, you could overload it like this:
```ts
export function Taggable();
export function Taggable<T extends Constructor>(base: T);
export function Taggable<T extends Constructor>(base?: T) {
  if (base === undefined) base = <T><{}>Object;
  return class extends base {
    tags: any[] = [];
  };
}
```

**Comment by pleerock** [comment]
Actually I want as simple as possible function signature to make it easiest as possible to create mixins.

Thank you for the answer though 👍
