### ISSUE TITLE
In JS object, 'this' assignment in object literal doesn't use contextual type

### ISSUE THREAD

**Issue by miluoshi** [Microsoft/TypeScript#25926]
**TypeScript Version:**  2.9.2 (also tried typescript@next 3.1.0-dev.20180725)
**VSCode version:** 1.25.1

**Search Terms:** this argument jsdoc vscode

I am trying to add TypeScript typechecking using VSCode's intellisense + JSDoc annotation in my AngularJS project. I should be able to explicitly define a type of `this` keyword in a function by providing explicit `this` parameter in as described [here](https://www.typescriptlang.org/docs/handbook/functions.html#this-parameters).

**Code**

`component.d.ts`
```ts
import 'angular'

declare interface IComponentCtrl {
  $onChanges?(onChangesObj: ng.IOnChangesObject): void;
}
declare interface IComponent extends ng.IComponentOptions {
  controller(this: IComponentCtrl, ...args: any[]): void;
}
```

`component.js`
```js
// @ts-check
/** @type {import('./component').IComponent} */
export const component = {
  controller() {
    /** @type {import('./component').IComponentCtrl} */
    const vm = this

    vm.$onChanges = (onChangesObj) => {} // onChangesObj: angular.IOnChangesObject

    this.$onChanges = (onChangesObj) => {} // onChangesObj: any
  }
}
```

**Expected behavior:**
When I define controller's type of `this` explicitly as interface with $onChanges method with argument of specific type, I should get type hints for the argument in the defined method.

**Actual behavior:**
The argument in `this.$onChanges` method has type `any` and the type checking works only if I assign `this` to another variable and explicitly add type annotation to the newly created variable.

**Comment by andy-ms** [comment]
Simplified repro:
```ts
/** @type {{ a(): void; b?(n: number): number; }} */
const obj = {
    a() {
        this.b = n => n * 2; // Parameter 'n' implicitly has an 'any' type
    }
};
```

**Comment by sandersn** [comment]
This is trickier than it looks. The reason it doesn't use the contextual type is that `this.b = n => n * 2` is normally a declaration in Javascript. We don't contextually type declaration initialisers because they provide the declaration's type in the absence of a type annotation.

However, this-property assignments are ambiguous between declaration and assignment. In this case, the information that `this.b = ...` is an assignment, not a declaration, is non-local. Deciding whether to contextually type the initialiser requires the same kind of upward walk as actually contextually typing it.

I'll look at the problem again and see if I can find an easier way, but I'm not sure there is one.
