### ISSUE TITLE
macOS considers typescript files to be MPEG-2 Transport Stream - QuickLook and Spotlight do not work

### ISSUE THREAD

**Issue by curiouslybrown** [Microsoft/TypeScript#25945]
Hello,

macOS considers typescript files to be of type "MPEG-2 Transport Stream." This prevents QuickLook and Spotlight (system search) from working properly. Please address this given macOS is a major platform for devs. Thank you.

**Comment by DanielRosenwasser** [comment]
This sounds like feedback that you'd ideally want to leave with someone at Apple on the Spotlight team at macOS, not TypeScript. It's not in our means to change the way that Spotlight works.

**Comment by curiouslybrown** [comment]
I see where you're coming from for sure. But you are using the same extension as another somewhat popular file-format, that's not so much Apple's problem. I'd be interested in what others have to say, but I will send an email to Apple - just don't expect it to go very far.

**Comment by justinlevi** [comment]
Found a solution to this today: 
https://gregbrown.co/code/typescript-quicklook

Definitely not the cleanest, but it works. 

Here's my setup for quicklook as well
http://justinlevi.github.io/blog/2016/11/21/quick-look-essentials

**Comment by KingOfCramers** [comment]
This solution no longer works on Big Sur as the .plist file is Read-Only. If anyone has found a solution, that would be great, all my Typescript files look like VLC video files 🤦

**Comment by jimmy-zhening-luo** [comment]
Imagine Apple ever listening to user feedback 😂 Years later, this thread in a Microsoft-owned repo on a Microsoft subsidiary's website for a Microsoft-sponsored/-led programming language has gotten more responses (>0) from representatives than dozens of discussions.apple.com of us poor users howling into the void about iOS (and apparently even macOS) providing no facility for selection of file extension associations. Woe is me for having no better mobile phone option than the iPhone, for otherwise I would never subject myself to this sort of paternalistic abandonment. May I never complain the next time I have to edit 20 regkeys just so Windows gives me the privilege of being allowed to save files in My Documents after uninstalling OneDrive, for at least those regkeys may be edited!

**Comment by jackpunt** [comment]
FWIW: my comment in ([#issuecomment-2680167818](https://github.com/microsoft/TypeScript/issues/47611#issuecomment-2607767152)) includes bash code (find,xargs,grep) to search .ts files. 

(I didn't see this thread/issue until recently...)

**Comment by AuthorProxy** [comment]
any progress in 2025?

**Comment by RyanCavanaugh** [comment]
Is this the MacOS issue tracker? 😅

**Comment by cryptolit0** [comment]
> Is this the MacOS issue tracker? 😅

sponsored by microsoft lmao

**Comment by qgustavor** [comment]
I guess the irony here is because that's not a MacOS vs Windows problem, it's a lack of standardization problem: the same issue can happen on any OS as .ts is often recognized as a media file (due to Transport Streams) and not as TypeScript. So much so this issue is happening with Windows Explorer (it's probably not as badly as in MacOS, it just treats my code as a video folder).

While IANA maintains an official registry of MIME media types, I don't know any body that maintains a registry of file extensions, so that's expected to happen. The only thing TypeScript staff can do to improve that is changing the .ts extension to something else, but then it would not solve the huge amount of existing files that use this extension. I guess I can make Windows threat .ts files as being text files, but then I would have to fix it in every computer I own and document how to solve this so others can do the same, and it would break .ts videos (which aren't that common, sure, it doesn't even have an official MIME - as far as I found in IANA's website - but they exist, I even had a TV recorder that recorded TV as .ts files).

For the future, maybe OSes could treat .ts as an special case and rely on magic numbers or heuristics to guess the actual file type. If there were a lot of people affected by this, sure. I don't think there are.

**Comment by qgustavor** [comment]
~~Thinking more about this issue, I guess the best idea is for TypeScript users stop using `.ts` in favor of `.cts` and `.mts`. Reasons:~~

1. ~~It's quite unlikely the `.ts` conflict will ever be resolved: Transport Streams is a 30-year old standard, TypeScript is just 13 years old, so if one would have to stop using this extension, this would be TypeScript, not Transport Streams. That being said, I think it really unlikely TypeScript maintainers would do that: just look this comment thread: lots of people putting the blame on Apple for an issue caused by TypeScript itself, that happens on Windows too.~~
2. ~~`.cts` and `.mts` are already supported by most TypeScript tooling and don't have this issue.~~

~~The only issue with that is that `.cts` becomes `.cjs` and `.mts` becomes `.mjs`, and not all JavaScript tooling supports those two, it can be a breaking change for some people. Developers bothered with this issue can just start doing that for new projects and [existing ones too](https://gist.github.com/qgustavor/e0432e75d131d3460db5901a5fb23992).~~

**Edit:** I noticed the issue @mootari pointed out in the first TypeScript project I tried this. Bummer. Then I forgot to edit this message.

**Comment by neoneye** [comment]
Just wasted 1 hour on trying to resolve this issue with Claude, making all kinds of changes to my mac, clearing caches. No luck getting quicklook working for `ts` files.

**Comment by mootari** [comment]
> stop using .ts in favor of .cts and .mts

`.mts` suffers from the same problem, it gets detected as `public.avchd-mpeg-2-transport-stream` (via QuickTime Player).

From https://github.com/sbarex/SourceCodeSyntaxHighlight (a quicklook plugin for source files):

> .ts and .mts are reserved by macOS and cannot be handled.

**Comment by qgustavor** [comment]
@mootari Just edited my original comment. To be fair, I guess this issue will never be solved: both Transport Stream and TypeScript are heavily used and there isn't something like a "IANA for file extensions", so it's up to the operating systems to choose what to do.

FOSS operating systems have it easier: often someone contributes a fix for this problem. That's why the main blame here is on macOS: it's proprietary, so we can't contribute a fix, just pressure Apple on doing something. And, that said, this problem also happens in Windows too: while I can set on my PC to handle .ts as being a text file, it annoys me having to set it in every PC I work with, by default it shows my TypeScript projects as being video folders (with those huge thumbnails).

Then, what should OSes do? I mean, we can discuss about a solution to recommend OS vendors here and then it will easier to coordinate them to fix that. Allow the user to choose what to do? That's already on Windows and it's annoying (as I mentioned before). Consider that Transport Stream is too technical and default .ts to TypeScript? I guess it's a sane thing to do... except when someone like me has a TV box that stores recordings as .ts files and, when people try to open those files, they don't work. Check for magic numbers? Not so simple: Transport Stream magic number is an ASCII "G" (as per [Wikipedia](https://en.wikipedia.org/wiki/List_of_file_signatures)) so TypeScript files starting with "G" might be falsely flagged if just the first byte was checked (like, if someone starts a file with "Google" for some reason). Check every 188th byte up to a limit (so OSes don't need to read the entire file just to list directory contents)? Is it doable?
