### ISSUE TITLE
Infer from usage for rest parameter should always infer array

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#25994]
**TypeScript Version:** 3.1.0-dev.20180726

**Code**

```ts
function f(...a) {
    return a[0] * 2;
}
```

Apply code fix to infer the type of `a` from its usage.

**Expected behavior:**

`...a: number[]`

**Actual behavior:**

`...a: { [x: number]: number; }`, which is a compile error.

**Comment by sandersn** [comment]
@andy-ms Probably so. I don't think structural inferences are that useful because (1) naive users don't know what to make of them (2) they are usually trivially satisfied by existing code because they specify a small slice of an actual type.  When that changes (or it may already be false in a large program), the failure is structural, which is again hard to understand for a naive user.
