### ISSUE TITLE
Assignability of callback parameter defined with conditional tuple type

### ISSUE THREAD

**Issue by bterlson** [Microsoft/TypeScript#26013]
**TypeScript Version:**  3.1.0-dev.20180727

**Code**

```ts
// ConditionalTuple could also return just [] in the false branch, issue still repros
type ConditionalTuple<T> = [T] extends [undefined] ? [] : [T];

// works fine!
declare var f1: (...args: any[]) => void;
declare var f2: <T>(...args: ConditionalTuple<T>) => void;
declare var f3: (...args: ConditionalTuple<number>) => void;
f2 = f1;
f3 = f1;

// but if we move the signatures above into a callback parameter with that signature,
// assignability breaks - the types of cb are incompatible.
declare var cb1: (cb: (...args: any[]) => void) => void;
declare var cb2: <T>(cb: (...args: ConditionalTuple<T>) => void) => void;
declare var cb3: (cb: (...args: ConditionalTuple<number>) => void) => void;

cb2 = cb1; // can't assign to cb2
cb3 = cb1; // this works though
```

**Expected behavior:**
I am able to construct callback signatures with generic conditional types and tuples that are assignable with the maximally general callback signature (`cb1`).

**Actual behavior:**
`cb1` cannot be assigned to `cb2`, but removing the generic parameter ala `cb3`  makes assignability work as expected.

**Comment by mattmccutchen** [comment]
For `cb1` to be assignable to `cb2`, the callback of `cb2` needs to be assignable to the callback of `cb1` (contravariance).  This isn't working because the following code in [src/compiler/checker.ts](https://raw.githubusercontent.com/Microsoft/TypeScript/2b14bcbb56e8dc2cb4d859a485ef0b362331cdba/src/compiler/checker.ts) `compareSignaturesRelated` around line 10564 is triggering, because the source rest type `ConditionalType<T>` is generic and the target rest type `any[]` is not:
```ts
            const sourceCount = getParameterCount(source);
            const sourceGenericRestType = getGenericRestType(source);
            const targetGenericRestType = sourceGenericRestType ? getGenericRestType(target) : undefined;
            if (sourceGenericRestType && !(targetGenericRestType && sourceCount === targetCount)) {
                return Ternary.False;
            }
```
I'm unsure what this code is supposed to be doing.

**Comment by mhegazy** [comment]
@ahejlsberg was working on a fix for assigning a type to a conditional type if it is assignable to the two branches.

**Comment by ahejlsberg** [comment]
The conditional type is irrelevant here. The examples can be simplified to just:

```ts
declare var f1: (...args: any[]) => void;
declare var f2: <T extends any[]>(...args: T) => void;
f1 = f2;  // Ok
f2 = f1;  // Ok

declare var cb1: (cb: (...args: any[]) => void) => void;
declare var cb2: <T extends any[]>(cb: (...args: T) => void) => void;
cb1 = cb2;  // Ok
cb2 = cb1;  // Error
```

In the second example, the `args` parameter is co-variant, i.e. it is in an output position (a parameter in a callback parameter is effectively checked in the same manner as a return type). So, we're dealing with something similar to:

```ts
declare var ff1: () => any[];
declare var ff2: <T extends any[]>() => T;
ff1 = ff2;  // Ok
ff2 = ff1;  // Error
```

The second assignment fails because `any[]` is not assignable to `T` which seems entirely reasonable. So, I don't think there is a bug here.

@mattmccutchen The code you're looking at is indeed the place we error. It basically says that a generic rest parameter in the source must be matched by a generic rest parameter in the target, because only another generic type could be assignable here (i.e. for a source `T extends any[]`, only a related `U extends T` would ever be assignable to `T`).

**Comment by mattmccutchen** [comment]
> The second assignment fails because `any[]` is not assignable to `T` which seems entirely reasonable.

This is inconsistent with the behavior when the rest parameter is a non-generic tuple type.  For example:
```ts
declare var cb1: (cb: (...args: any[]) => void) => void;
declare var cb2: (cb: (...args: [any]) => void) => void;
cb1 = cb2;  // Ok
cb2 = cb1;  // Ok

declare var ff1: () => any[];
declare var ff2: () => [any];
ff1 = ff2;  // Ok
ff2 = ff1;  // Error
```
So I think there is a bug here: either `cb2 = cb1` should be an error in this example, or it should be allowed in the previous example.

**Comment by DanielRosenwasser** [comment]
@mattmccutchen that's because that effectively gets flattened to

```ts
declare var cb1: (cb: (...args: any[]) => void) => void;
declare var cb2: (cb: (arg0: any) => void) => void;

cb1 = cb2;
cb2 = cb1;
```

and

> [When comparing call or construct signatures, parameter names are ignored and rest parameters correspond to an unbounded expansion of optional parameters of the rest parameter element type.](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md)

Which is definitely an inconsistency in how tuple types and parameter lists are compared.

____

The thing is that you really don't know whether `T` will be instantiated with some subtype of `Array<any>` (e.g. imagine a `MySuperCoolArray<T>` which has an extra member). I do think it's reasonable to say `any[]` is not assignable to a `T extends any[]`, but I'm not sure how to otherwise write the code @bterlson  is aiming for.

**Comment by mattmccutchen** [comment]
> The thing is that you really don't know whether `T` will be instantiated with some subtype of `Array<any>` (e.g. imagine a `MySuperCoolArray<T>` which has an extra member).

TypeScript doesn't normally allow that:
```ts
interface MySuperCoolArray<E> extends Array<E> { 
    hello: number;
}

// Error: A rest parameter must be of an array type.
declare var cb2: (cb: (...args: MySuperCoolArray<any>) => void) => void;
```

So in principle, when we see:
```ts
declare var cb2: <T extends any[]>(cb: (...args: T) => void) => void;
```
we should have a constraint that `T` be an array or tuple type.  TypeScript has no way to express such a constraint, but IMO the least bad thing we can do is allow an `any[]` rest parameter to be assigned to a `T` rest parameter, like we allow it to be assigned to any specific type that is a valid type for a rest parameter.

As an aside, this isn't an error on the playground and it probably should be:
```ts
interface MySuperCoolArray<T> extends Array<T> { 
    hello: number;
}

declare var cb2: <T extends MySuperCoolArray<any>>(cb: (...args: T) => void) => void;
```
