### ISSUE TITLE
verify existence of files linked in markdown of jsdocs

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#26095]
## Search Terms

https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue+links+markdown

## Suggestion

there is little value in allowing links to non-existing files in markdown of jsdocs, please verify that the linked files exist

## Use Cases

clicking on a broken link while looking at jsdocs

## Examples
```ts
/** [see also](./missing-file.ts) */
class MyClass {
}
```
## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by RyanCavanaugh** [comment]
@sandersn want to write a markdown parser?

**Comment by aleksey-bykov** [comment]
@sandersn borrow the parser from vscode

**Comment by sandersn** [comment]
I've already written or used too many parsers for too many badly specified languages...jsdoc, english, swedish, etc. I don't even want to think about markdown.

Seriously, though, this is a lint feature, not a core compiler feature. I worked on [a compiler](https://msdn.microsoft.com/en-us/azure/data-lake-analytics/u-sql/u-sql-language-reference) that requires files to exist in order to compile, and it was a miserable user experience.

**Comment by aleksey-bykov** [comment]
dang
