### ISSUE TITLE
non null assertion removes automatic generics passing

### ISSUE THREAD

**Issue by HolgerJeromin** [microsoft/TypeScript#26148]
**TypeScript Version:**  3.0.1

It is pretty nice that `querySelector` can get the return type from the variable type:
```ts
let rect0: SVGRectElement | null = document.querySelector('.svg-rectangle'); // OK: SVGRectElement | null
```

`querySelector `returns `E | null` type, so the following error is fine
```ts
let rect1: SVGRectElement = document.querySelector('.svg-rectangle'); // Error: SVGRectElement | null
```

But I know that it will find something, so I use the non null assertion but now it gets `Element` instead of `SVGRectElement`
```ts
let rect2: SVGRectElement = document.querySelector('.svg-rectangle')!; // Error: Element
```

**Expected behavior:**
Last example should compile
I am not sure if this is possible, but would be very nice, as the following code is not so elegant because in my real code I dont use rect3 but an class property `protected __SvgRectangle!: SVGRectElement;`

```ts
let rect3: SVGRectElement = document.querySelector<SVGRectElement>('.svg-rectangle')!; // SVGRectElement
```

**Comment by mhegazy** [comment]
The request here is to propagate the contextual types through the null assertion operators.

**Comment by jabrouwer82** [comment]
Any update on this? These lovely generics would also be useful on `getElementById`, which would suffer from the same issue.

**Comment by amakhrov** [comment]
I have a case which seems to be related to the same root cause:
```
type Size = "small" | "medium" | "large";

let sizes: Size[] = ['medium', 'small']; // this compiles well

let sizesWithNonNull: Size[] = (['medium', 'small'])!; // Error: Type 'string[]' is not assignable to type 'Size[]'
```

My snippet looks pretty dumb on the first glance - why would someone write this code in the first place?

However, wrapping a constant array expression into a NonNullExpression like this can happen automatically in an Angular app with a `strictNullInputTypes: false` option. (https://github.com/angular/angular/blob/d466db8285920347972cec53250e0937f07726c7/packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts#L590)
