### ISSUE TITLE
how to use $("xx").click(data,handler)in typescript

### ISSUE THREAD

**Issue by MonsterGoGoGo** [Microsoft/TypeScript#26142]
when I use js to develop, I will write like this
`<input id="btn" type="checkbox" onclick="check(this)"></button>`
but now I use TypeScript to rewrite it, I use jQuery, like this
` $("#btn").click(this,check);`
my "check" function is like this: 
`check=(obj:HTMLInputElement)=>{
     if(obj.checked)alert(123);
}`
it has give me an error "Argument of type‘obj:HTMLElement’=>void is not assignable to parameter of type '(eventObject:jQueryEventObject)'"
What should I do to resolve this issue?

**Comment by MonsterGoGoGo** [comment]
I set no parameters function like `$("#btn").click(check)` gulp have no error notice for me,but when the check function runing, the default parameter the function gets is not a HTMLInputElement type

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Next time, please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
