### ISSUE TITLE
ts.transpile() outputs CRLF as EOL in any OS

### ISSUE THREAD

**Issue by teppeis** [Microsoft/TypeScript#2614]
CRLF is hardcoded:
https://github.com/Microsoft/TypeScript/blob/5e7343f573c3e987caaa3f2326386b8c796e6fa3/src/services/services.ts#L1683

**Comment by mhegazy** [comment]
@teppeis would the use of system-dependent line ending be good enough?

**Comment by teppeis** [comment]
@mhegazy yes, `sys.newLine` is good.

**Comment by nycdotnet** [comment]
FYI: The line endings question has come up in every meta-TypeScript project I've been involved in:

https://github.com/TypeStrong/atom-typescript/issues/216
https://github.com/TypeStrong/grunt-ts/issues/199

This issue is still open as accepting PR:

https://github.com/Microsoft/TypeScript/issues/1693

It's fine to default to the current system's default line ending but to solve this, it really should be overrideable via the tsconfig or a switch.  I had intended to take a stab at 1693, but of course this is the sort of thing where the implementation is the easy part and naming the switch is the hard part.  :-)

**Comment by mhegazy** [comment]
@nycdotnet i agree. i was initially going to do fix it by adding the flag. if you intend to send a PR for #1693 soon, then i would wait for it.

**Comment by nycdotnet** [comment]
I'll give it a shot and let you know either way in the next two weeks.  Based on the ~80% 1.5 issues treadmill, I'm hopeful this should be in plenty of time.

**Comment by teppeis** [comment]
@mhegazy thanks!

**Comment by basarat** [comment]
Having looked at @nycdotnet 's list I am now inclined to say "os.eol" or death in the next meta ts project :)
