### ISSUE TITLE
error TS2363: The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

### ISSUE THREAD

**Issue by SomeKittens** [Microsoft/TypeScript#2624]
I have the following code:

```JavaScript
var blockLen = ecb.determineBlockSize();

var len = ecb.encrypt(Buffer.concat([mysteryBytes, mysteryBuffer])).length;

console.log(len, len/blockLen);
```

The signature of `ecb.determineBlockSize` is `determineBlockSize (): Number {`

However, I get an error on the `console.log` telling me that:

> error TS2363: The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

The return type is `Number`, the `typeof` reveals `number`, yet I still get this error.

```
tsc --version
message TS6029: Version 1.5.0-alpha
```

**Comment by DanielRosenwasser** [comment]
Can you declare the return your of `determineBlockSize` as `number` instead of `Number`?

**Comment by SomeKittens** [comment]
I don't get the error with `number` - what's the difference?

**Comment by DanielRosenwasser** [comment]
The short version is that you should always be returning `number` instead of `Number`, `string` instead of `String`, `boolean` instead of `Boolean`, and usually almost anything else instead of `Object`.

-------------------------------

In TypeScript, we have several primitive types like `number`, `string`, and `boolean`. They describe the type of values like `100.0`, `"hello"`, and `true` respectively. Their behavior with operators is as it's been defined in the specification. However, to determine whether a property access on them is valid (i.e. whether in the expression `foo.x`, it's valid to grab `x` off of `foo`), we get their [*apparent types*](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#3101-apparent-members), which are dependent on the interfaces [`Number`](https://github.com/Microsoft/TypeScript/blob/master/bin/lib.d.ts#L459), [`String`](https://github.com/Microsoft/TypeScript/blob/master/bin/lib.d.ts#L278) and [`Boolean`](https://github.com/Microsoft/TypeScript/blob/master/bin/lib.d.ts#L446) in [`lib.d.ts`](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md). These interfaces exist mainly to serve the apparent types of these primitives.

From the TypeScript spec:
> For purposes of determining type relationships (section 3.10) and accessing properties (section 4.10), the Number primitive type behaves as an object type with the same properties as the global interface type 'Number'.

**Comment by SomeKittens** [comment]
Ah, thanks.  Misread the headings under "Basic Types" (which are capitalized) as the correct way to do things.  Now seeing the code examples are lowercase.

**Comment by chanakaDe** [comment]
I also get the same issue here.
user_checking(registerdata, tested_users):boolean {
    return registerdata.userid && typeof tested_users[registerdata.userid] == 'undefined';
  }
can anyone tell me how to fix ?
