### ISSUE TITLE
Update argument list of call expression using compiler API. 

### ISSUE THREAD

**Issue by shrinktofit** [microsoft/TypeScript#26353]
### Scenario 
The scenario is that I want convert js funtion call to typescript's. 

Since typescript doesn't allow unmatched argument count. I use the compiler API to supply the lacked arguments. For example:
Convert
```js
function fx(arg) {  }
fx();
```
to
```ts
function fx(arg: any) {  }
fx(undefined);
```

### Things I do
* Foreach `NewExpression` or `CallExprexxion` node of `SourceFile`.
* Perform `TypeChecker.getTypeAtLocation()` on that node's caller to get the caller 's type and symbol and value declaration(`valueDeclaration` of `Symbol`) to get the parameters count.
 * Suppose there are N arguments need to supply, create an array with N `ts.parseIsolatedEntityName("undefined", ts.ScriptTarget.Latest)`.
* Concat the array with original `node.arguments` and assign it to `node.arguments`.

This method is feasible when I test it with a simple testcase similar to the example given above.
But an error occurs when I use this method in my real project.

### The error 
In getAssignmentTargetKind(node) function of typescript.js, `node.parent` is `null`.
Use the debugger, I found that the `node` parameter is just the supplied "undefined" argument that created using `ts.parseIsolatedEntityName("undefined", ts.ScriptTarget.Latest)` in step 3.
The origin of call stack is the step 2's `TypeChecker.getTypeAtLocation()`.

## My temprory solution
In step3:
```ts
let newArgNode = ts.parseIsolatedEntityName("undefined", ts.ScriptTarget.Latest);
newArgNode.parent = ts.createStringLiteral(""); // Result is expected.
// newArgNode.parent = node; // This will lead to unexpected result.
```

**Comment by andy-ms** [comment]
Mutating a node is a bad idea. We should probably be marking our API `readonly` in more places (#16312).
If you want to get a series of text changes that can convert one file to another, you might look at the internal `textChanges` API (in `textChanges.ts`) that is used by refactorings and codefixes.

On another note, if the arguments can truly be `undefined`, it might be better to mark the *parameter* as optional instead of updating the call sites.
