### ISSUE TITLE
Bug in lib.dom.d.ts - document.evaluate

### ISSUE THREAD

**Issue by ststeiger** [microsoft/TypeScript#26437]
In TypeScript (my version is 2.5), lib.dom.d.ts specifies document.evaluate as follows:
`evaluate(expression: string, contextNode: Node, resolver: XPathNSResolver | null, type: number, result: XPathResult | null): XPathResult;`

where 

```
interface XPathNSResolver {
    lookupNamespaceURI(prefix: string): string;
}

```

So this means the following code 

```
xmldoc.evaluate(
    '//ns1:RunLocatorResponse',
    xmldoc,
    function (prefix:string) : string {
        if (prefix === 'ns1')
            return 'http://tempuri.org/AWEService/API/WASAPI';
        else
            return null;
    },
    XPathResult.ANY_TYPE,
    null
);
```

reports function (prefix:string) : string  cannot be assigned to XPathNSResolver. 

However, as in the comments of [this](https://stackoverflow.com/questions/23110310/javascript-the-string-ns1runlocatorresponse-contains-unresolvable-namespac/23110498?noredirect=1#comment90628193_23110498) issue under [note of DOM-Level-3-XPath-20040226](https://www.w3.org/TR/2004/NOTE-DOM-Level-3-XPath-20040226/DOM3-XPath.html#ecma-script-binding) the DOM spec clearly says 

> Note: The parameter resolver of the method XPathEvaluator.evaluate is specified as an object that implements the XPathNSResolver interface. **ECMAScript users can also pass to this method a function which returns a String and takes a String parameter instead of the resolver parameter.**

So libdom.d.ts is missing an overload for 
`(prefix:string) => string`
and that leads to a error-message for proper ECMAScript which is not transpiling, which is a bug.

**Comment by knrt10** [comment]
I would love to help in this, unfortunately I have no previous experience in the repository, would anyone please guide me?

**Comment by Fabianopb** [comment]
Hi @ststeiger, I was investigating this issue and I have a couple comments:

First, w3.org says "ECMAScript users can also pass to *this method* a function which returns a String and takes a String parameter instead of the resolver parameter."
Just for me to understand clearly, if *this method* is referring to *evaluate* then it seems you're right, we're missing the possibility of passing _a function which returns a String and takes a String parameter_ in the `lib.dom.d.ts` type definitions, instead of the resolver with type `XPathNSResolver`, right?

Second, I noticed that your method either returns a `string` or `null`, which I think it shouldn't be possible in this case. If we're talking about _a function which returns a String and takes a String parameter_, then as you said the type should be `(prefix: string) => string`, but in reality your function's type is `(prefix: string) => string | null`. Does this make sense for you?

@RyanCavanaugh if you think we're good to go I have already scribbled a solution for this and could create a PR in no time!

Cheers!

**Comment by ststeiger** [comment]
To 1): I didn't write the spec, so why should I know ? 
All I can say is that you can pass a function string=>string in all 3 major browsers, and it works as expected. 

To 2): Since strings are nullable, null is a valid string value, so I don't see your problem, other than there being no typecast like `return <string>null`;  But if you define null as its own type, then yes, it makes sense this way.

Also, the documentation for XPathNSResolver 
https://www.w3.org/TR/2004/NOTE-DOM-Level-3-XPath-20040226/DOM3-XPath.html#xpath-XPathNSResolver
explicitly states:

> Return Value: DOMString | Returns the associated namespace URI or null if none is found.

**Comment by ststeiger** [comment]
It wasn't meant harsh, but sorry anyway. 
Hm, that's an interesting concept - type changes to object if string is set to null, so string as such is indeed non-nullable. 

Yes, the return value is that of lookupNamespaceURI. 
In that case, lookupNamespaceURI should also be fixed, yes.

**Comment by Fabianopb** [comment]
Thanks for the input @RyanCavanaugh and @ststeiger! I'll submit a PR and then we can discuss upon that, how does it sound?

**Comment by Fabianopb** [comment]
@RyanCavanaugh could you just confirm to me if I can modify the file `lib/lib.dom.d.ts`? I was checking these instructions (https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes) which say that _"the files in `lib/` are used to bootstrap compilation and usually do not need to be updated."_ However, that's where `XPathNSResolver` seems to be defined.

**Comment by Fabianopb** [comment]
I've created a PR so we can discuss upon that: https://github.com/Microsoft/TypeScript/pull/27592

**Comment by RA80533** [comment]
This appears to have been fixed in https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/578
