### ISSUE TITLE
Force subclass property to be static

### ISSUE THREAD

**Issue by jpike88** [Microsoft/TypeScript#26504]
`abstract class A {
      static test
}

class B extends A {
     test = 4
}`

In the above scenario, B doesn't throw an error on compile. I think that this is inconsistent. Static properties are incredibly important in organising subclasses and this is should probably even be treated as a bug.

**Comment by MartinJohns** [comment]
This is perfectly legal code and should most definitely not be an error. In `B` you define an **instance** member named `test`. It does not override the static `test`.

Changing this behaviour would be a breaking change and would not align with the existing JavaScript behaviour.

**Comment by jpike88** [comment]
Perhaps an extra qualifier would work to ban use of an instance property matching that name, as it’s rare to have instance and static variable names colliding. While I get the importance of respecting JS, this is a valid issue is it not? I’d rather find a solution than some convoluted workaround that involves generics.

**Comment by MartinJohns** [comment]
Perhaps it would help if you elaborate your use-case. I've never considered static properties "incredible important in organizing subclasses". I don't see how these things are related.

**Comment by andy-ms** [comment]
Seems like you could write a lint rule for this case.

**Comment by RyanCavanaugh** [comment]
There's nothing wrong with this code, and because JS needs either `this`. or `ClassName.` to access a member, there's no ambiguity or risk of stumbling into the wrong property by accident.

It'd be quite annoying for subclasses to get broken if their base class updated to add a *non-conflicting* static member that happened to coincide with an existing subclass instance property.

**Comment by RyanCavanaugh** [comment]
Also please follow the template.
