### ISSUE TITLE
Error when accessing private property in object destructuring assignment with computed name

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#26572]
**TypeScript Version:**  3.1.0-dev.20180818

**Search Terms:**

**Code**

```ts
class Foo {
    private prop = 1;
}
let prop: any;
({['prop']: prop} = new Foo());
```

**Expected behavior:**

No error on destructuring with computed property name.

**Actual behavior:**

Error on all statically known property names.

**Playground Link:** 

**Related Issues:** 
@andy-ms this was introduced in #26381 while fixing #26355

**Comment by RyanCavanaugh** [comment]
I'm *really* tempted to Won't Fix this because the whole "private properties can be accessed via indexing" thing feels like something we only do because we did it in 0.8, and destructuring is new enough that it doesn't feel like this would break anything major.

@ajafff is this affecting you, or just something you noticed?

**Comment by ajafff** [comment]
I just noticed that it's inconsistent with other element access with computed names.
If you say this is working as intended, that's fine for me. In that case you might want to consider reverting the recent change to destructuring BindingElement.

**Comment by RyanCavanaugh** [comment]
Which part of it specifically?

**Comment by ajafff** [comment]
#26360

**Comment by RyanCavanaugh** [comment]
Not going to keep around consistency of the sake of inconsistency.
