### ISSUE TITLE
interface loop

### ISSUE THREAD

**Issue by yzxchoice** [Microsoft/TypeScript#26597]
interface ILabel  {
    text: string,
    textColor?: number,
    size?: number,
    lineSpacing?: number,
    textAlign?: string
}

class Mylabel implements ILabel {
    ....
}

i want loop  ILabel and  get property

**Comment by andy-ms** [comment]
You're probably getting errors that the class didn't implement the interface -- if you don't want to redeclare the properties you could write `interface MyLabel extends ILabel {}` above the class instead. Note this is unsafe if you forget to assign to `text` (which is non-optional).

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
