### ISSUE TITLE
Infer of extended generic type

### ISSUE THREAD

**Issue by vlazh** [Microsoft/TypeScript#26688]
**TypeScript Version:**  3.0.1

**Code**

```ts
type JSONModel<T> = T extends object ? string : number;

interface IBase<T> {
  p: JSONModel<T>; // when don't use JSONModel<T> then infered correctly
}

interface I extends IBase<{ a: number }> {}

type A = I extends IBase<infer T> ? T : never;
```

**Expected behavior:**
type A is { a: number }

**Actual behavior:**
type A is {}

**Comment by nmain** [comment]
This is a similar problem to the unused generic type parameter issue, covered in the Typescript FAQ with various examples: https://github.com/Microsoft/TypeScript/wiki/FAQ#generics

What's happening here is that while `T` is used in `JSONModel`, it's not _really_ used.  Any `T` that `extends object` will give the exact same resulting type:

```
type Foo = JSONModel<{}> // type Foo = string
type Bar = JSONModel<{ a: number }> // type Bar = string
type Baz = JSONModel<{ french: "bread" }> // type Baz = string
```

This makes your example go bad when you ask for `I extends IBase<infer T>`.  The actual structural type of `I` is simply `{ p: string; }`, and it would be the same whether `{}` or `{ a: number }` was used for `T`, so Typescript has no way to know what you want it to infer, and the inference it made is correct.  Changing `p` to `T` or adding another property `z: T` fixes this because now in order to satisfy `I extends IBase<infer T>`, `{ a: number }` must be used.

**Comment by vlazh** [comment]
> Changing p to T or adding another property z: T fixes this

Yes, it fixes when I add another property of type T.
Thank you, @nmain!
