### ISSUE TITLE
Regression - able to use union containing non-indexing type as index

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#26714]
**TypeScript Version:** master at bd40583beb10165fd9

**Search Terms:** array index union error

**Code**

```ts
declare const arr1: (string | string[])[];
declare const arr2: number[];
const j = arr2[arr1[0]];
```

**Expected behavior:** Error - Type `string[]` cannot be used as an index type

**Actual behavior:** No error

**Playground Link:** [Link](http://www.typescriptlang.org/play/#src=declare%20const%20arr1%3A%20(string%20%7C%20string%5B%5D)%5B%5D%3B%0D%0Adeclare%20const%20arr2%3A%20number%5B%5D%3B%0D%0Aconst%20j%20%3D%20arr2%5Barr1%5B0%5D%5D%3B%0D%0A)

**Related Issues:** Regressed during fix of #26409 (**edit**: #26281 ?)

**Comment by RyanCavanaugh** [comment]
Ref #26712 & #26698

**Comment by ahejlsberg** [comment]
Looks to me like this is caused by #26281.

On Aug 28, 2018, at 9:44 AM, Ryan Cavanaugh <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #26714<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FTypeScript%2Fissues%2F26714&data=02%7C01%7Candersh%40microsoft.com%7Cd4a71e519eb742bb819f08d60d058c93%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636710714819794992&sdata=20KrB7JoqXwGmikmgie1ahf1gCuTxO7J2J%2FZlKapjKA%3D&reserved=0> to @ahejlsberg<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fahejlsberg&data=02%7C01%7Candersh%40microsoft.com%7Cd4a71e519eb742bb819f08d60d058c93%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636710714819805000&sdata=D46MFo6ROrjXZYOh2xMY1oYcFGcxBJ6YvvzXH7V4aCA%3D&reserved=0>.

**Comment by weswigham** [comment]
Righto, so this is a bit interesting. Since the index distributes to `number[string] | number[string[]]` and `noImplicitAny` is _off_, `number[string]` silently becomes `any` and then we don't bother to check `number[string[]]`. I can fix it so we still do the validity check even if we won't use the type; just thought it was interesting~
