### ISSUE TITLE
Suggestion: Implicit 'typeof value' where a type is expected

### ISSUE THREAD

**Issue by osi-oswald** [Microsoft/TypeScript#26769]
## Suggestion

TypeScript will complain if a value is passed where a type is expected. Example:

```typescript
type MyType<T> = T;
interface MyInterface<T> { }

function myFunc() { }
const myConst = 42;
// ...

let foo: MyType<myFunc>; // ts error: Cannot find name 'myFunc'
let bar: MyInterface<myConst>; // ts error: Cannot find name 'myConst'
```

Currently it's easily fixed by using 'typeof'

```typescript
let foo: MyType<typeof myFunc>; // ok
let bar: MyInterface<typeof myConst>; // ok
```

But why not make it implicit for values?

**Suggestion**: Make the 'typeof' implicit for values where a type is expected.

Instead of considering the code invalid, assume the users intention is 'typeof value' in these scenarios and consider the code valid.

## Use Cases

Consider a type `Props<T>` that reads out the props type of a React.Component or stateless functional component. For `Props<T>` to be usable, it has always be taken into account if the component (type) is a class or a function for the code to compile. 

```typescript
type Props<T> = T extends React.Component<infer PC> ? PC
    : T extends (props: infer PSFC) => any ? PSFC
    : never;

class MyComponent extends React.Component<{ someProp: number }> { }
const MySfc = (props: { someProp: number }) => null; // ...

let propsOfComponent: Props<MyComponent>; // no implicit 'typeof', since it is already a type
let propsOfSfc: Props<MySfc>; // with implicit 'typeof', Props can be used regardless of it's input
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* I assume already written code will not be affected
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by AlCalzone** [comment]
Another thing to keep in mind:
```ts
class Foo { }
type FooKeys = keyof Foo; // never, as expected

function Bar() { }
type BarType = typeof Bar; // () => void, as expected
type BarKeys = keyof BarType; // never, as expected

class Baz { } // this used to be a function
type BazType = typeof Baz; // typeof Baz, this is the Baz constructor
type BazKeys = keyof BazType; // "prototype"
```
Lets assume that `Baz` used to be a function that has been referenced via `typeof` in type declarations. If we later change it to be a class and **forget** to remove `typeof` everywhere, we might accidentally target the class constructor instead of the class itself.
This wouldn't happen with the proposal.

**Comment by RyanCavanaugh** [comment]
It's very much intentional that we don't this, because it creates dangerous maintenance traps like the one @AlCalzone describes.

**Comment by osi-oswald** [comment]
Isn't the example from @AlCalzone a positive example regarding the proposal? 🤔

**Comment by RyanCavanaugh** [comment]
Perhaps I misread it. Let me show an example of why we didn't do this.

Let's say you start with this code:
```ts
        function foo() {
          const Options = { ... };
          const x = doSomething<Options>(...);
          bar(x);
        }
```
Later, someone adds a type in an outer scope
```ts
   type Options = { ... };
```
This edit breaks `foo`, because the meaning of `Options` in a type position has changed.

(Counterfactually, making `Options` *always* resolve to the local value instead of the outer type would be an enormous breaking change, and one without any clear fix that users could take.)

This is really problematic because it means we could *never* add a global type to `lib.d.ts` without potentially breaking existing code; this is not a problem today because type/value references are always unambiguous.
