### ISSUE TITLE
Named Generic Type Parameter

### ISSUE THREAD

**Issue by KSXGitHub** [Microsoft/TypeScript#26834]
## Suggestion

Allow generic consumer to pass generic argument by name, for instance:

```typescript
interface Provider<Foo, Bar, Baz, Qux, Quux, ...> {
  foo: Foo
  bar: Bar
  tup: [Baz, Qux, Quux]
  ...
}

type Consumer = Provider<
  Foo = number,
  Bar = string,
  ...
>

let consumer: Provider<
  Foo = {},
  Bar = [],
  ...
>
```

This would allow us to write and use a generic with thousands of parameter without decreasing readability.

### NOTES

* Before you ask, this feature request is not a duplicate of https://github.com/Microsoft/TypeScript/issues/22631 in any shape or form.
* This is similar to keyword (named) arguments in Python.
  - Vanilla JavaScript doesn't need keyword arguments as it already has objects, but there's no equivalent for TypeScript generic arguments.

## Use Cases

Above

## Examples

Above

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by RyanCavanaugh** [comment]
We're still investigating the whole named type arguments story as part of partial inference and handling of generics defaults (see linked PRs as suggested).

I think we can confidently say that the "simple" case of passing type arguments by name has been mostly ruled out due to compat concerns - we have been very careful so far to make type parameter names not observable outside the declaration itself and would prefer to keep it that way unless there's absolutely no other way to accomplish the task.
