### ISSUE TITLE
return does not return within forEach loop

### ISSUE THREAD

**Issue by foxjazz** [Microsoft/TypeScript#26910]
I will be commenting on this more once I have a method to share.
```
getSection(sections: Section[], aoid: string, suuid: string): AnalysisObject {
        let sect = sections.filter(a => a.UUID == suuid)[0];
        if (sect) {
            let res = sect.AnalysisObjects.filter(b => b.AOId == aoid)[0];
            if (res)
                return res;
        } else {
            sections.forEach(z => {
                let sect2 = z.children.filter(a => a.UUID == suuid)[0];
                if (sect2) {
                    let res = sect2.AnalysisObjects.filter(b => b.AOId == aoid)[0];
                    if (res)
                        return res;
                } else {
                    z.children.forEach(y => {
                        let sect3 = y.children.filter(a => a.UUID == suuid)[0];
                        if (sect3) {
                            let res = sect3.AnalysisObjects.filter(b => b.AOId == aoid)[0];
                            if (res)
                                return res;
                        }
                    });
                }
            });
        }

        return null;
    }
```

**Comment by andy-ms** [comment]
`return` returns from the arrow function, not from the outer functions. Learn more [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures).

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!

**Comment by foxjazz** [comment]
Ok, learning falt.
