### ISSUE TITLE
Proxied types are not loaded.

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#26921]
_From @zavr-1 on September 4, 2018 3:46_

Issue Type: <b>Bug</b>

When a package loads some modules via another module, their will lack Intellisense and it is not possible to click through to their definition.

VS Code version: Code - Insiders 1.27.0-insider (346018a80dd299c50cbf213e0a706ef0f35f3a67, 2018-08-24T05:12:36.061Z)
OS version: Darwin x64 15.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P7350  @ 2.00GHz (2 x 2000)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: unavailable_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|7, 8, 6|
|Memory (System)|8.00GB (0.16GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_24582|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.5.0
code-spell-checker|str|1.6.10

</details>

from file A
```js
import { throws, equal } from 'zoroaster/assert'
```

where `zoroaster/assert` is a proxy file (only has `module.exports = require(./build/assert)`) to `zoroaster/build/assert` which has: 

```js
let throws = require('assert-throws'); if (throws && throws.__esModule) throws = throws.default;
const $assert = require('assert');
const $assert_diff = require('assert-diff');



module.exports.assert = $assert
module.exports.equal = $assert.equal
module.exports.ok = $assert.ok
module.exports.deepEqual = $assert_diff.deepEqual
module.exports.throws = throws
//# sourceMappingURL=index.js.map
```

```
1. git clone https://github.com/artdecocode/vscode-require-types.git
2. code-insiders vscode-require-types
```
3. open test/spec/default.js
4. try use throws function, there will be no intellisense. try click through -- it will get to the parent package, but not any further than that.

![test](https://user-images.githubusercontent.com/21156791/45008852-89eeeb80-b00d-11e8-9b4d-9265c13eef35.png)

5. Uncomment `// import assertThrows from 'assert-throws'` line. Now, `throws` works fine. 

![test](https://user-images.githubusercontent.com/21156791/45008880-bdca1100-b00d-11e8-9db0-eb8736b4e994.png)

Whenever the proxy in form of `zoroaster/assert` is removed in favour of `zoroaster/build/assert`, then things work. I suppose I have to `ln` the `assert` rather than use `module.exports = require('./build/assert')` but it's still a bug. 

_Copied from original issue: Microsoft/vscode#57833_

**Comment by mjbvz** [comment]
The issue appears to be that that `require('assert-throws')` does not get resolved in `./node_modules/zoroaster/build/assert/index.js`.

Adding a [`d.ts`](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) typings for `zoroaster` should fix this as well

**Comment by zavr-1** [comment]
I don't like TypeScript, I don't think it solves any problems because JS is a duck typed language and using JSDoc with a proper IDE like VS Code which can understand `@ type {import(.)} Type` should be enough. The problem however is more here because I found another case where it happened.

ALSO the `require('assert-throws')` does get resolve properly, if you import it directly via `import { throws } from 'zoroaster/build/assert`, or when the proxy `assert` file is `ln`ed. I think the problem is that TypeScript parser does not go more than 1 level deep, but I'll double check that.

**Comment by mjbvz** [comment]
TypeScript powers both VS Code's javascript and typescript intellisense. It is what analyzes jsdocs 

I recommend that you try writing `d.ts` typings for `zoroaster`. Even if this specific issue is fixed, proper typings will provide a much better experience

**Comment by RyanCavanaugh** [comment]
This works fine for me

![image](https://user-images.githubusercontent.com/6685088/45894865-85079700-bd84-11e8-9685-d2033925979b.png)

**Comment by zavr-1** [comment]
@RyanCavanaugh This is not what it supposed to be showing, the signature of that function is different. The problem is quite annoying actually see 

![bug](https://user-images.githubusercontent.com/21156791/46014315-7cda8f00-c0d7-11e8-95ec-f5675fc9b82d.gif)

In the end when `koa-router` gets selected it's me clicking with <kbd>cmd</kbd> trying to jump to that file, but it does not work. You can try in [this repo](https://github.com/rqt/rqt) in `example/Session`.

**Comment by zavr-1** [comment]
CAN YOU FIX THIS PLEASE IT IS THE MOST ANNOYING BUG EVER

**Comment by weswigham** [comment]
![clickclickclick](https://user-images.githubusercontent.com/2932786/46033978-6111c180-c0b4-11e8-968c-d6a54b816eba.gif)

Am I doing something from your repro wrong?

**Comment by zavr-1** [comment]
@weswigham OK thanks very much for testing, can you basically make sure that `src/index.js` stays open when you do that by double clicking on it?

**Comment by zavr-1** [comment]
@weswigham @RyanCavanaugh I beg you can you make this work it's making all the efforts of writing documentation worthless look it happens everywhere after 1 level of require:

1. git clone `https://github.com/rqt/test2.git`  (https://github.com/rqt/test2.git)
2. cd test2
3. npm i / yarn
4. open `src/index.js` so that it's always open (no italic)
5. add `.create` to `gh.repos` -> there will be no suggestions!!! This is the bug!!! Also try clicking though on `import @rqt/github` then on `./api/repos` on top at `let repos = require('./api/repos');` then you won't be able to click through to `./create`!
6. navigate to `node_modules/rqt/github/build/api/repos/` and double click on it to always open (no italic)
7. go back to `src/index` and there will be suggestions! But this is only because the file is open in the workspace.

**Comment by RyanCavanaugh** [comment]
I haven't seen other reports of whatever this is, so either we've fixed it or it's rare enough to not warrant further investment.
