### ISSUE TITLE
Error is caught while building project abount WebRtc’s RTCPeerConnection

### ISSUE THREAD

**Issue by gyc1299339354** [Microsoft/TypeScript#26932]
MacOS 10.13.6
VSCode 1.26.1

Vue + Typescript
create project using vue-cli 3.0
already installed @types/webrtc

Details:
![image](https://user-images.githubusercontent.com/8892634/45131434-8733f800-b1bf-11e8-845c-111a732f7346.png)

However if I use the old api methods named 'addStream' and 'onaddstream' ( are all deprecated now ),
the compilation will be all right .... though the VSCode's termial shows that they are all nonexistent on RTCPeerConnection's property
![image](https://user-images.githubusercontent.com/8892634/45131873-75535480-b1c1-11e8-9a45-189f3a9bb7ca.png)
![image](https://user-images.githubusercontent.com/8892634/45131881-7d12f900-b1c1-11e8-9af4-10b19bfe2c5c.png)

tsconfig.json
![image](https://user-images.githubusercontent.com/8892634/45131473-a5015d00-b1bf-11e8-8632-f51cab7d1920.png)

This is pressing on me .... so I need your guys' help .... 🙂🙂🙂🙂

**Comment by mattmccutchen** [comment]
This has been fixed in TypeScript 3.0; please upgrade.  And please ask future questions like this on Stack Overflow, not in the issue tracker, after doing basic research of your own.

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
