### ISSUE TITLE
Explicit string indexing access of map type

### ISSUE THREAD

**Issue by mikecann** [Microsoft/TypeScript#26974]
**TypeScript Version:**  3.1.0-dev.201xxxxx

**Search Terms:**

string index, explicit index

**Code**

```ts
type EventDefinitions<TEventPayload extends object> = {
    [eventName: string]: TEventPayload;
  };

type X = keyof EventDefinitions<object>;
```

**Expected behavior:**

The type of X to be `string` as I have explicitly said it will be.

**Actual behavior:**

The type of X is `string | number`.

**Playground Link:**

http://www.typescriptlang.org/play/#src=type%20EventDefinitions%3CTEventPayload%20extends%20object%3E%20%3D%20%7B%0D%0A%20%20%20%20%5BeventName%3A%20string%5D%3A%20TEventPayload%3B%0D%0A%20%20%7D%3B%0D%0A%0D%0Atype%20X%20%3D%20keyof%20EventDefinitions%3Cobject%3E%3B

**Related Issues:**

Maybe this: https://github.com/Microsoft/TypeScript/issues/26470 ?

**Comment by RyanCavanaugh** [comment]
In TypeScript, when a type can be indexed by `string`, it can also be indexed by `number`, so `keyof` is consistent by providing the legal key types for the provided operand.

**Comment by mikecann** [comment]
@RyanCavanaugh oh okay :S Thanks for that, it was certainly unexpected behaviour for me. Is there a way to explicitly say its going to be a string?

**Comment by unional** [comment]
On the other hand:

```ts
type R = Record<string, number>

type Y = keyof R // string
```
It caught me by surprise too. 🌷

**Comment by mikecann** [comment]
@unional yep Record is the way to do it I think 👍

**Comment by naddeoa** [comment]
Worth pointing out that the example in this issue is almost the exact example used in the docs here

https://www.typescriptlang.org/docs/handbook/advanced-types.html#index-types-and-string-index-signatures

That example claims that the keys will be of type `string` but they're actually of type `string | number` it seems.

https://www.typescriptlang.org/play/#src=interface%20Foo%3CT%3E%20%7B%0D%0A%20%20%20%20%5Bkey%3A%20string%5D%3A%20T%3B%0D%0A%7D%0D%0Alet%20keys%3A%20keyof%20Foo%3Cnumber%3E%3B%20%2F%2F%20string

Assuming I didn't miss something, I think those docs could use an update.

**Comment by mikecann** [comment]
@naddeoa you are correct the docs are incorrect.. They say this:

```
interface Map<T> {
    [key: string]: T;
}
let keys: keyof Map<number>; // string
let value: Map<number>['foo']; // number
```

But its not true:

![image](https://user-images.githubusercontent.com/215033/53770728-2fcad680-3f1b-11e9-96ee-d06f87630e35.png)
