### ISSUE TITLE
Consequent renaming of 2 identifiers mentioned in the same lines is broken

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#2716]
Observed in VS2013, TS1.4

This is a hard one to be exact about. I will do what I can:

Say I have 
```
interface Range<a> {
from: a;
to: a;
}
```

I have a lot of code  using this interface. Now I want to rename `from` -> `start` and `to`->`end`. And I do it one immediately after another.

The code that used both `from` and `to` in a single line gets messed up.

```
// before

function fromRange(range: Range<number>): Interval {
   return { start: range.from: end: range.to };
}

///  after renaming both from and to of Range (very exaggerated) 
function fromRange(range: Range<number>): Interval {
  return { start: range.start FDYSSLASH hGDSjW JHDGS SJ jhGQJ EWHGE WJK   };
}
```

**Comment by DanielRosenwasser** [comment]
A few questions:

* I assume you have an interface around like this:

```TypeScript
interface Interval {
    start: number;
    end: number;
}
```

* In your test code, you have a syntactically invalid object literal. Did you mean the following?
```TypeScript
function fromRange<T>(range: Range<T>): Interval {
    return { start: range.start, end: range.end };
}
```
or did you mean for the code to be erroneous?

* What editor and version of that editor are you using?
* Did you try renaming your entities at the declaration-site or at the use-site?

**Comment by aleksey-bykov** [comment]
@DanielRosenwasser

sorry for confusions:

1. Ues I do have the `Interval` interface like you mentioned.

2. No, by accident I made a mistake, fixed.

3. VS2013, TS1.4

4. Don't remember. Tend to think it was a use site.

**Comment by aleksey-bykov** [comment]
It seems like the text buffer after the first renaming doesn't get updated promptly and the second renaming runs against unupdated or partially updated buffer.

**Comment by aleksey-bykov** [comment]
The code base is over 800 files and over 150 000 lines of code

**Comment by DanielRosenwasser** [comment]
So this is not necessarily something that always happens; if you press 'undo' and try it again, you may or may not get the same results?

**Comment by aleksey-bykov** [comment]
Yes, it doesn't always happen. If I give it enough time between the tries it works fine. It is only observed when I do one renaming immediately after another against a considerably large code base.

**Comment by CyrusNajmabadi** [comment]
Does this repro in the latest VS2014 RC?  Our entire LS was rewritten between 2013 and 2014.  Thanks.

**Comment by aleksey-bykov** [comment]
@CyrusNajmabadi, VS2013 as far as I can tell, here are more details:

![image](https://cloud.githubusercontent.com/assets/937933/7107106/3532329a-e127-11e4-8d7a-b516b0b7b211.png)

**Comment by CyrusNajmabadi** [comment]
The VS2013 code was very 'racy'.  In that it had actual race conditions in it that weren't terribly difficult to run into.  It sounds like you may just be running into one of those cases.  Given the size of your codebase, that does not seem altogether surprising given that this would be exacerbated by how much work we needed to do.  If you try out VS2014 and don't encounter this anymore, then that would help indicate if the issue was fixed, or if there is something deeper going on that we'll need to investigate.  Thanks!

**Comment by DanielRosenwasser** [comment]
I believe @CyrusNajmabadi means VS2015/Visual Studio 14.

**Comment by mhegazy** [comment]
As @CyrusNajmabadi mentioned we have done some major re-architecture in VS plugin code to make sure such issues do not happen in VS2015. It would be a non-trivial amount of work to make this work in VS2013. Since VS2015 is in RC and almost ready for RTM, I am going to close this as won't fix.

@aleksey-bykov please let us know if you see similar issues on VS 2015.
