### ISSUE TITLE
Override Javascript Prototype With typescript

### ISSUE THREAD

**Issue by N00ts** [microsoft/TypeScript#27269]
Hello everyone, i'm pretty new with typescript.
In my context I must override some javascript methods from a class in typescript (no choice).

I use module "AMD" and ECMAScript5.
Typcript files are compiled into one file "all.js";

In this exemple the class I must override will be contained in "test.js" and named "test". It looks like :

```
test = function(){
}

test.prototype.myfunction = function(){
    alert("test");
}
```

"test.js" is loaded first then "all.js". I wanted to take advantage that the last method loaded wins to override this prototype in my typescript file (test.ts) :

```
import { myclass } from "./myclass" 

test.prototype.myfunction = function(): void{
    const a = new myclass();
    a.mymethod();
    alert("another test");
}
```

while the compiled js file is loaded after "test.js" the second method should be executed.
The problem is that I have a dependency to "myclass" and AMD, for file order resolution purpose, wrap it into RequireJs "define" method like :

```
define(stuff...);
```

The problem is with this "define" method, the appication does not recognize anymore "test.prototype.myfunction" from compiled js as overriding the first one (from js). I defined "test" in my d.ts file and everything compile fine, the problem is only at runtime.

This is certainly a noob issue but if you have any suggestion, appart from rewrite the first "test.js" file (which is not an option), I will be very happy to hear it.

Regards

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
