### ISSUE TITLE
Mappable tuples with constraints are unwieldy due to lack of covariance

### ISSUE THREAD

**Issue by pelotom** [Microsoft/TypeScript#27351]
**TypeScript Version:**  3.1.0-dev.20180925

**Search Terms:** mappable tuples constraints covariance

I'm trying to make use of the new "mappable tuple and array types" [coming in 3.1](https://blogs.msdn.microsoft.com/typescript/2018/09/13/announcing-typescript-3-1-rc/), and discovered that it's a bit awkward to work with arrays constrained to a particular type.

**Code**

```ts
interface WithFoo<T = any> {
  foo: T;
}

type SelectFoos<A extends WithFoo[]> = { [K in keyof A]: A[K]['foo'] };
```

**Expected behavior:**

Should compile.

**Actual behavior:**

Error: `Type '"foo"' cannot be used to index type 'A[K]'.`.

**Notes**

It's possible to work around this using a conditional:

```ts
type SelectFoos<A extends WithFoo[]> = {
  [K in keyof A]: A[K] extends WithFoo ? A[K]['foo'] : never
};
```

but it seems like it should just work as is.

[**Playground Link**](http://www.typescriptlang.org/play/#src=interface%20WithFoo%3CT%20%3D%20any%3E%20%7B%0A%20%20foo%3A%20T%3B%0A%7D%0A%0Atype%20SelectFoos%3CA%20extends%20WithFoo%5B%5D%3E%20%3D%20%7B%20%5BK%20in%20keyof%20A%5D%3A%20A%5BK%5D%5B'foo'%5D%20%7D%3B)

**Comment by RyanCavanaugh** [comment]
@ahejlsberg bug? feature request?

**Comment by ahejlsberg** [comment]
The issue here is that even though a homomorphic mapped type only maps the element type(s) of the array or tuple, `keyof A` still includes the non-numeric properties of `Array<T>` (i.e. `"length"`, `"concat"`, etc.) and therefore `A[keyof A]` (the constraint of `A[K]`) is a large and fairly useless union type that can't be indexed with `"foo"`.

We considered having `keyof T` for an array or tuple type not include non-numeric properties, but it would be a significant breaking change. For example, `A["length"]` wouldn't work anymore.

Given where we're at, your conditional type workaround seems reasonable.

**Comment by jcalz** [comment]
When mapping over the keys `K` in a type `T` constrained to an array type, is it possible to narrow `K` instead of `T` or `keyof T`?  Assuming there were a ["`numericString`" type](https://github.com/Microsoft/TypeScript/issues/13715#issuecomment-298382761), the suggestion is to treat

```ts
type MapArray<T extends {x: string}[]> = {[K in keyof T]: T[K]['x']}
```

like

```ts
type MapArray<T extends {x: string}[]> = {[K in keyof T]: T[K & numericString]['x']
```

That would possibly give the expected behavior here without pretending that `keyof T` is limited to the numeric keys, so `T['length']` would still exist.  Just a passing thought...
