### ISSUE TITLE
Typescript 3.1.x make document.activeElement have type "never"

### ISSUE THREAD

**Issue by pitAlex** [Microsoft/TypeScript#27446]
Hello,
I wanted to upgrade to the 3.1.1 version of typescript, but after I did it started throwing the following error: 
```
[ts] Cannot invoke an expression whose type lacks a call signature. Type 'never' has no compatible call signatures.
(property) Document.activeElement: never
```
on the following code:
```
if("placeholder" in document.activeElement && "blur" in document.activeElement) {
    document.activeElement['blur']();
} 
```
I am back on 3.0.3 and I can see it when I hover over, but it will let me compile and it will not highlight it. So what changed here and what need to be turned off?

**Comment by weswigham** [comment]
`document.activeElement` is now (correctly, technically) of type `Element` rather than `HTMLElement` - meaning it has neither a `blur` nor `placeholder`. `placeholder` is also only on `HTMLInputELement`, so you need to refine even further to actually get the correct type. Writing it like
```ts
const e = document.activeElement as HTMLInputElement;
if ("blur" in e && "placeholder" in e) { // validate the above cast
    e.blur();
}
```
works fine, in that case.
