### ISSUE TITLE
Allow Map<K,V> inline typing

### ISSUE THREAD

**Issue by lukepighetti** [microsoft/TypeScript#27445]
Today

```
const map: {
  [name: string]: string[];
} : {
  key: ["A", "B"]
}
```

Tomorrow

```
const map: Map<string, string[]> :  {
  key: ["A", "B"]
}
```

**Comment by mattmccutchen** [comment]
Huh?  `{ [name: string]: string[]; }` (string-indexable object) and `Map<string, string[]>` (ES6 `Map` object) are different things.  To create a `Map<string, string[]>` equivalent to your example, you would use:

```ts
const map: Map<string, string[]> = new Map([["key", ["A", "B"]]]);
```

**Comment by DanielRosenwasser** [comment]
I don't even know exactly what the proposal here is, but I'm fairly certain that neither today nor tomorrow will ever work.

**Comment by AlCalzone** [comment]
I think OP is looking for `Record<K,V>`

**Comment by lukepighetti** [comment]
The notation I have in "tomorrow" can be seen in Dart and Bolt. It's very easy to read and write.

**Comment by mattmccutchen** [comment]
@lukepighetti Are you proposing that `Map<string, string[]>` be interpreted as the type of a string-indexable object (which we can't do because that syntax is already taken for the type of an ES6 map) or that `{ key: ["A", "B"] }` be an initializer for an ES6 map (which would be a runtime feature outside the design goals of TypeScript)?

**Comment by lukepighetti** [comment]
I'm proposing that there be an easier way to specify the type of values in an object. The only alternative syntax I am personally aware of is Map<K,V> which I am familiar with from both Dart and Bolt.
