### ISSUE TITLE
Pointer Lock API removed from lib.dom.ts

### ISSUE THREAD

**Issue by cmlenz** [Microsoft/TypeScript#27461]
**TypeScript Version:**
3.1.1

**Search Terms:**
`Pointer Lock`, `requestPointerLock`, `exitPointerLock`, `pointerLockElement`

**Code**

```ts
function tryPointerLock(elem: HTMLElement): void {
  elem.requestPointerLock();
  if (elem !== document.pointerLockElement) {
    console.warn("expected", document.pointerLockElement, "to be", elem);
  }
  document.exitPointerLock();
}
```

**Expected behavior:**
The methods above (from the [Pointer Lock API](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API)) should be part of the `HTMLElement` and `Document` interfaces.

**Actual behavior:**
The methods are not recognized.

They seem to have been removed from `lib.dom.ts` in commit ee25cdecbca49b2b5a290ecd65224f425b1d6a9c.

**Comment by squirly** [comment]
This is expected behaviour. Please see the [breaking changes in TypeScript 3.1](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#some-vendor-specific-types-are-removed-from-libdts) and the [recommended path forward](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#recommendations).

For more information please see: [When should a DOM API be included here? - WC3](https://github.com/Microsoft/TSJS-lib-generator#w3c). Pointer Lock is still Working Draft, https://www.w3.org/TR/pointerlock-2/.

**Comment by cmlenz** [comment]
Oops, I must have missed that. Thanks for the info.
