### ISSUE TITLE
Better handling of optional parameters mismatch

### ISSUE THREAD

**Issue by JacobDanton** [Microsoft/TypeScript#2751]
In Array, map is defined as:

    map<U>(callbackfn: (value: T, index: number, array: T[]) => U, thisArg?: any): U[]

In JSON, parse is defined as:

    parse(text: string, reviver?: (key: any, value: any) => any): any

The following results in a compile error in Typescript, though it works in Javascript:

    serializedObjs.map(JSON.parse)

Since the optional second argument in parse is of type `(key: any, value: any) => any` which does not match the second optional `number` parameter in the callback function of map, the compiler should be able to compile this as, effectively:

    serializedObjs.map((str) => JSON.parse(str))

**Comment by ahejlsberg** [comment]
No, I don't think we can do that. When Array.map calls the callback function, it always passes three arguments. The second one is going to be a `number`, but JSON.parse expects a `(key: any, value: any) => any` function. I guess it works because JSON.parse dynamically validates that the second argument is actually a function before attempting to call it, but clearly the declared types don't match and it is appropriate for the compiler to reject it.
