### ISSUE TITLE
Conditional type inference does not work with a function's generic argument

### ISSUE THREAD

**Issue by samijaber** [Microsoft/TypeScript#27530]
**TypeScript Version:**  3.0.0-dev.201xxxxx

**Search Terms:** conditional type inference generic

**Code**

```ts
type Get<T> = T extends {} ? true : false;

const fn = <T extends {}>(t: T) => {
    // Expected `true`
    // Actual `T extends {} ? true : false`
    type Result = Get<T>;
}
```

**Expected behavior:** correct type inference: `type Result = true`

**Actual behavior:** type inference not performed at all

**Playground Link:** [link](http://www.typescriptlang.org/play/index.html#src=type%20Get%3CT%3E%20%3D%20T%20extends%20%7B%7D%20%3F%20string%20%3A%20number%3B%0D%0A%0D%0Aconst%20fn%20%3D%20%3CT%20extends%20%7B%7D%3E(t%3A%20T)%20%3D%3E%20%7B%0D%0A%20%20%20%20%2F%2F%20Expected%20%60string%60%0D%0A%20%20%20%20%2F%2F%20Actual%20%60T%20extends%20%7B%7D%20%3F%20string%20%3A%20number%60%0D%0A%20%20%20%20type%20Result%20%3D%20Get%3CT%3E%3B%0D%0A%7D)

**Comment by jack-williams** [comment]
This conditional type is distributive because there is a naked type parameter in the check clause. A distributive conditional type will evaluate to `never` when the check type is instantiated to `never`, so it is not possible to immediately resolve this to `true`.

To get the desired behaviour make the conditional type non-distributive like so:
```ts
type Get<T> = [T]extends [{}] ? true : false;

const fn = <T extends {}>(t: T) => {
    const x: Get<T> = true; // ok, Get<T> = true
}
```

**Comment by samijaber** [comment]
Ah, I see. Thanks @jack-williams! Will close this then.
