### ISSUE TITLE
[feature] support union type rest parameter

### ISSUE THREAD

**Issue by Meir017** [microsoft/TypeScript#27532]
## Search Terms

type, union, rest

## Suggestion

allow rest operator on a union type when all cases are array

## Use Cases

in order to declare a ctor with overloads, I wrote something like this
```ts
type TimeSpanCtorArguments = [number]
    | [number, number, number]
    | [number, number, number, number]
    | [number, number, number, number, number];

class TimeSpan {
    private readonly _ticks: number;
    constructor(...args: TimeSpanCtorArguments) {
        if (typeof args.length === 1) {
            [this._ticks] = args;
        } else if (args.length === 3) {
            const [hours, minutes, seconds] = args;
        } else if (args.length === 4) {
            const [days, hours, minutes, seconds] = args;
        } else {
            const [days, hours, minutes, seconds, milliseconds] = args;
        }
    }
}
```
I get the error: `[ts] A rest parameter must be of an array type.`

on the line
```ts
    constructor(...args: TimeSpanCtorArguments) {
```

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by Meir017** [comment]
might be related to #15972

**Comment by Meir017** [comment]
@RyanCavanaugh any update on this?

**Comment by Andarist** [comment]
@RyanCavanaugh this already works since 3.3 so the issue can be closed:
[TS 3.3 playground](https://www.typescriptlang.org/play?ts=3.3.3#code/C4TwDgpgBAKglgWwgZTAQwHYGFgHsBOAgvgOYCuSGwAzlALwBQUUAPlANoYUBGE+Auk1YcuCXvgA0UUeKky+g5m048+c1ZOkb1YhUOXzNhnbK26jG-gG4GDAMYAbNNVrwkqTFADeQsPjgAbmjA0PgQaAAmuBgOIFAA+sBwdgDW1ABcZuL0UAC0AJIYAGZwGHCgNsx20dTA+GR2ePgAFAB07WikGbCIKOjYTcTklDQAlN5CzHBFUM2dJNStDhAYJMAAFvR0dFAAjOM+zEccG3CLiclp-Dnz1JVHAL5QEA7U0NOzt0sra5vbOwBmA6TI7VDC1DjrXBkfDUKQIUpkEJwqBvMERajXHa3e7MJ4vN5QD5zLrfVYbLY7AAswOOVRqwA4ETQIBRUJhKIRXGRUjR0QxWKgOJB+Ne0EOdLBEPYzNZUnZsPhiJ5qIg6M5cAcDjOav5mJuXVxUAeQhNJqAA)
