### ISSUE TITLE
Named AMD Modules as a compiler switch

### ISSUE THREAD

**Issue by andreivanea** [microsoft/TypeScript#27547]
This is a question/feature request combo. I understand it doesn't really fit the "issue guidelines" but I consider it fits better here as it does on StackOverflow.

It's been almost 3 years since [this reply](https://github.com/Microsoft/TypeScript/pull/1158#issuecomment-66165529). If I understand correctly, the problem is with the tooling. 3 years is a lot, given the frequency of Visual Studio and Visual Studio Code updates we're seeing. I am wondering if it's still the same case. Is it still not possible to directly emit AMD Module Names without using the `amd-module` directive?

My scenarios is this: we have a codebase of >100 `.ts` filese, originally written using namespaces, that we need to change to use modules instead. We are using ASP.Net MVC and we want to still take advantage of the built-in bundling & minification process. We don't want to build a single output and instead want to create bundles for specific "features" of our app. This is currently not possible without adding the  `amd-module` directive in every app, which is a tedious task and it makes it hard to spot naming changes or conflicts.

**Comment by fcamblor** [comment]
I'm having the same need here : I'm using AMD/requiredjs on my growing app.
Today, I am currently using `outFile` in my `tsconfig.json` file and everything is working well : AMD module name are emitted into this single `outFile`, and module resolution is performed well.

However, concatenating everything in a single file prevents me from incremental compilation : since my codebase is growing and a ts (full) compilation takes 15-16s now, I considered switching to the `outDir` compiler option in order to benefit from incremental compilation.
The thing is .. as soon as I switch to `outDir`, AMD module names are not emitted anymore, and then I get tons of errors like `Mismatched anonymous define() module` because requirejs needs named modules.

The only solution I see currently is to switch to another build tool (currently using custom grunt scrips) like Webpack, but it would represent a lot of effort for the project to sustain such migration just for incremental compilation.

And honestly, I really don't understand why tsc behaviour is changing regarding emitted module names as soon as we switch from `outFile` to `outDir` ... at least, wouldn't it be possible to provide a compiler option allowing to emit AMD module names to keep backward compat ?

**Comment by fcamblor** [comment]
@RyanCavanaugh just saw you closed PR #28658 with comment 
> PRs need an associated approved issue in order to add new features

Can we discuss this here as I'm really happy with my PR today (it saves me a lot of compilation turnaround minutes at the end of the day).

I am opened to any better workarounds too.
