### ISSUE TITLE
Why promise will be unwrapped by dynamic import?

### ISSUE THREAD

**Issue by takefumi-yoshii** [Microsoft/TypeScript#27678]
I got mysterious inferred type with dynamic import.In `dynamic import` with `typeof`,Promise will be unwrapped.

```json
{
  "foo": "FOO"
}
```

```typescript
const json = import('./sample.json')
type ImportedJsonType = typeof json
type DynamicImportedJsonType = typeof import('./sample.json')
```

```typescript
// result of infer
type ImportedJsonType = Promise<{ "foo": string }>
type DynamicImportedJsonType = { "foo": string }
```
I would like to know the reasons for this behavior. Best reguards.

**Comment by ajafff** [comment]
`import('./sample.json')` as expression returns a Promise because it executes asynchronously.
`import('./sample.json')` as type is not intended to be the same as the expression counterpart. It's meant to reference a type of another module inline. Since it has no runtime behavior, it doesn't need to result in a Promise-type.

**Comment by takefumi-yoshii** [comment]
@ajafff Thanks for reply.If there has some discussion at past time,I'd like to know related issues.I would like to still open this one day.
