### ISSUE TITLE
Source Map Seems Off by One Line for Angular Controllers

### ISSUE THREAD

**Issue by tstearn** [Microsoft/TypeScript#2771]
I'm working with TypeScript 1.4.1 and Angular 1.3.0.  I've been creating controllers and services, registering them with Angular and things work pretty much fine.  However, when I set breakpoints in most Angular controllers, it appears the source map is off by a line, since when I hit a breakpoint, variables that should be defined are not and the callstack is not in the right state.  See in the image below:   the "result"  parameter is not defined and the call stack doesn't show coming back from the $http call in the service:

![image](https://cloud.githubusercontent.com/assets/5204033/7152263/63feaac8-e306-11e4-8da3-fe154c0019fd.png)

The screenshot below shows if I stop one line later, I stop within the callback as I wanted to originally and "result" is defined:

![image](https://cloud.githubusercontent.com/assets/5204033/7152313/3714b6e6-e307-11e4-9648-fa160ef1b577.png)

So, somehow the source map is off by one line.  The reason things didn't match when I put the breakpoint where it logically belongs is I stopped at the service invocation, rather than in the callback.  I've seen this same type of thing in 3 different Angular controllers.  I've yet to see this for a service.

**Comment by sheetalkamat** [comment]
@tstearn I tried this with VS2015 and latest typescript with todoMVC controller and it seemed to work correctly. 
Can you share your project so I can look into it to see if it is something that's specific to how you are writing code that results in this issue. 
You can share the link here or email me at shkamat@microsoft.com if you would rather share it privately.

Thanks

**Comment by aryelu** [comment]
@sheetalkamat 
This occurs in Chrome browsers. try to go to TodoMVC website to [Angular & Typescript ](http://todomvc.com/examples/typescript-angular/) and enter dev tools. It might be related to line breaks in transpiled files [discussion](https://bugs.chromium.org/p/v8/issues/detail?id=2825#c32)

**Comment by Ciantic** [comment]
I'm having exactly this issue in Chrome. Where breakpoints appear few lines below, but when it breaks the excution is few lines above.

Thing is that if I use the visualizer http://sokra.github.io/source-map-visualization/#custom and throw my files there, everthing seems to be right. So the bug can't be in the TypeScript?

**Comment by RyanCavanaugh** [comment]
Possibly a Chrome bug. Have you tried FireFox?

**Comment by Ciantic** [comment]
I now tried firefox, it did work with it and breaking at right point.

For the record, I'm using https://github.com/pepaar/typescript-webpack-react-flux-boilerplate ts-loader -> babel -> react-hot webpack combination. If someone else is using such a chain and finds problems it could be it's adding wrong kind of carriage return somewhere (which is known to cause Chrome source maps go awry), but hard to know where because it's not outputting any files.

Firefox debugger totally fails otherwise call stack is not visible, variable values are not available etc. (haven't used Firefox debugger in ages, perhaps it's not supporting sourcemaps as well as chrome does).

**Comment by mhegazy** [comment]
this should be fixed in latest.
