### ISSUE TITLE
Spec Wording Suggestion in 4.19 Contextual Typed Expression 

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#2780]
In the first sentence, we say 

>Type checking of an expression is improved in several contexts by factoring in the type of the destination of the value computed by the expression. 

However, up until this point, we don't define what we mean by "destination".

See [4.19](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#4.19)

**Comment by DanielRosenwasser** [comment]
I would second this; "destination" kind of pops up out of nowhere since there isn't necessarily always a destination for an expression. What might be marginally clearer is:

> When the value of an expression has a destination in some sense, type checking can be improved by factoring in the type of said destination.

It's not much better, but it does give some context (no pun intended) of the situations which we are interested in.

**Comment by ahejlsberg** [comment]
The introductory sentence is intentionally vague with respect to what the "destination" because it is introduction the concept of contextual typing. We could perhaps talk about the "consumer of the value computed by the expression", but I don't think we can get much closer--that's the whole point of the (long) list of bullets that follows.

I'm inclined to leave this one alone.
