### ISSUE TITLE
ShadowRoot should be a class, not an interface

### ISSUE THREAD

**Issue by justinfagnani** [Microsoft/TypeScript#27929]
**TypeScript Version:**  3.2.0-dev.201xxxxx

**Search Terms:** ShadowRoot

**Code**

```ts
const f = (o) => o instanceof ShadowRoot;
```

**Expected behavior:**
No errors

**Actual behavior:**
Error: `'ShadowRoot' only refers to a type, but is being used as a value here.`

**Playground Link:** http://www.typescriptlang.org/play/#src=const%20f%20%3D%20(o)%20%3D%3E%20o%20instanceof%20ShadowRoot%3B

**Related Issues:** https://github.com/Microsoft/TypeScript/issues/10401

**Comment by weswigham** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by weswigham** [comment]
Note that the constructor needs to be `private`, since even though `ShadowRoot` can be `instanceof`'d and exists in value space, it cannot be constructed.

**Comment by RyanCavanaugh** [comment]
Historically it was not possible to augment an existing class declaration with a subsequent `interface` declaration, so we wrote them as decomposed var/interface pairs so they could be subject to declaration merging so that people could write .d.ts compat files for experimental DOM features.

It was also historically not possible to have `private` constructors. You can only `instanceof` something that has a construct signature, so the `new()`s are there to allow for `instanceof` checks. Now that inheriting from elements is possible, making the DOM element constructors `protected` might make some sense.
