### ISSUE TITLE
Expected at least x arguments, but got x or more

### ISSUE THREAD

**Issue by robbiespeed** [microsoft/TypeScript#28010]
**TypeScript Version:**  3.2.0-dev.20181019 and 3.1.3

**Search Terms:** function arguments count, spread, rest
**Code**

```ts
function foo(a: number, ...r: number[]): void { };

const a = [1];

foo(...a, 2); // Expected at least 1 arguments, but got 1 or more.
foo(...a, 2, 3); // Expected at least 1 arguments, but got 2 or more.
```

**Expected behavior:**
No errors
"at least 1" == "1 or more"

**Actual behavior:**
"at least 1" != "1 or more"
Non logical type error.

**Playground Link:** [here](https://www.typescriptlang.org/play/index.html#src=function%20foo(a%3A%20number%2C%20...r%3A%20number%5B%5D)%3A%20void%20%7B%20%7D%3B%0A%0Aconst%20a%20%3D%20%5B1%5D%3B%0A%0Afoo(...a%2C%202)%3B%20%2F%2F%20Expected%20at%20least%201%20arguments%2C%20but%20got%201%20or%20more.%0Afoo(...a%2C%202%2C%203)%3B%20%2F%2F%20Expected%20at%20least%201%20arguments%2C%20but%20got%202%20or%20more.)

**Related Issues:** 
#26350

**Comment by fatcerberus** [comment]
Well that’s kind of a nasty bug.  Seems like the spread operator is tripping it up somehow.  Possibly a bad interaction between using a spread at the call site and a rest parameter in the declaration?

**Comment by robbiespeed** [comment]
Definitely some bugs with interpreting spread, even without using rest in the function:
```
function bar(a: number, b: number): void { };
function baz(a: number): void { };

const a: number[] = [];

bar(...a, 2); // Correctly interprets getting "1 or more"" arguments 
bar(...a, 2, 3); // Incorrectly interprets getting "3 or more"" arguments > Should be "2 or more""

baz(...a, 2); // Incorrectly interprets getting "2 or more"" arguments > Should be "1 or more""
baz(...a, 2, 3); // Incorrectly interprets getting "3 or more"" arguments > Should be "2 or more""
```
[Playground](https://www.typescriptlang.org/play/index.html#src=function%20bar(a%3A%20number%2C%20b%3A%20number)%3A%20void%20%7B%20%7D%3B%0Afunction%20baz(a%3A%20number)%3A%20void%20%7B%20%7D%3B%0A%0Aconst%20a%3A%20number%5B%5D%20%3D%20%5B%5D%3B%0A%0Abar(...a%2C%202)%3B%20%2F%2F%20Correctly%20interprets%20getting%20%221%20or%20more%22%22%20arguments%20%0Abar(...a%2C%202%2C%203)%3B%20%2F%2F%20Incorrectly%20interprets%20getting%20%223%20or%20more%22%22%20arguments%20%3E%20Should%20be%20%222%20or%20more%22%22%0A%0Abaz(...a%2C%202)%3B%20%2F%2F%20Incorrectly%20interprets%20getting%20%222%20or%20more%22%22%20arguments%20%3E%20Should%20be%20%221%20or%20more%22%22%0Abaz(...a%2C%202%2C%203)%3B%20%2F%2F%20Incorrectly%20interprets%20getting%20%223%20or%20more%22%22%20arguments%20%3E%20Should%20be%20%222%20or%20more%22%22)

Though these don't have a critical impact since they are correct errors, just incorrect error messages, unlike the top bug. Perhaps related though.

**Comment by fatcerberus** [comment]
Based on #26350 it seems that the underlying issue is that the compiler balks when a spread potentially crosses a formal argument boundary (which will always be the case if it’s not in tail position and the thing being spreaded is anything other than a 1-tuple).

**Comment by weswigham** [comment]
So there's two things here: clarifying the error messages for most cases to explain the error better, and _possibly_ improving how spread handles arrays? The last one seems less likely, but the error message improvements should be uncontentious.

**Comment by andrewbranch** [comment]
It would be possible to “fix” this case (i.e., not issue errors) only because the type of the fixed parameter (`number`) is the same as the element type of the rest parameters. If it were `foo(a: number, ...r: string[])`, we currently issue the same error message, but the real issue is not about _how many_ arguments might be passed depending on the length of the spread array, it’s about how the types of arguments will line up with the parameter types depending on the length of the spread array. That problem will always require an error message, and the special case where all the parameters have the same type seems suspiciously unuseful. We suspect that most of the upvotes here come either from an earlier bug where even spreading tuples of known length into parameters was not allowed (if `a` is initialized to `[1] as const`, there is no error—but there used to be one), or from the fact that the error message itself is nonsense.

A better error would be placed on the spread element itself, and convey the general idea of “expected a fixed argument, but got a variable-length spread.”

**Comment by evanjmg** [comment]
best workaround solution is to put a dummy argument unfortunately or retype the input  ie. lodash merge
merge({}, [...])
though this still is a bug.

**Comment by YanYuanFE** [comment]
```
import { pipe } from "rxjs";

validates.length > 0 ? pipe(...validates) : undefined
```
![image](https://user-images.githubusercontent.com/17774285/112106738-06a43e00-8be9-11eb-9456-94a3583ac63e.png)
