### ISSUE TITLE
Building performance is slowdown

### ISSUE THREAD

**Issue by thekiba** [Microsoft/TypeScript#28025]
**TypeScript Version:**  3.2.0-dev.201xxxxx

**Search Terms:** 
performance, slowdown, degradation

**Code:**
After upgrading to typescript 3.1.3, our application has been building for a very long time. The total time has increased tenfold. By profiling the build, I found the reason for the slowdown in performance.

<img width="278" alt="screenshot 2018-10-21 at 16 19 02" src="https://user-images.githubusercontent.com/1910515/47267531-c939b300-d54d-11e8-99df-a18b1fc0d854.png">

The screenshot shows a call to this method:
https://github.com/Microsoft/TypeScript/pull/26192/files#diff-08a3cc4f1f9a51dbb468c2810f5229d3R968
```typescript
oldProgramState.program.getSourceFiles().find(...)
```

When I rolled back the commit changes, the performance problem was solved. But I don’t know how to fix that and so that the PR assertion pass:
https://github.com/Microsoft/TypeScript/pull/26192/files#diff-6f2ace9c4058a2bb2afe0560f9990e33R402

**Expected behavior:**
Performance improvement

**Actual behavior:**
Performance is slowdown

**Related Issues:** 
https://github.com/Microsoft/TypeScript/pull/26192

**Comment by thekiba** [comment]
The count of files in the project ~10k.

I am using @angular/cli. And I tried to set the `compilerOptions.diagnostics` flag in `tsconfig.json`, but I don't receive any information.

**Comment by thekiba** [comment]
I build typescript from your pull request, and used it to build my application. Now the build time is the same as before.

👍Thanks for the quick response.

**Comment by DanielRosenwasser** [comment]
This should be available in TypeScript 3.1.6.

**Comment by Manish3177** [comment]
Could we get updated VS installer for 3.1.6: https://www.microsoft.com/en-us/download/details.aspx?id=55258?

**Comment by Manish3177** [comment]
Pinging again. It's not obvious how to apply the contents of [3.1.6 source](https://github.com/Microsoft/TypeScript/releases/tag/v3.1.6) on top of the installer linked above. Is it just a matter of copying over and overriding tsc.js+tsc.exe? Is there anything else that needs to be copied over? At the very least, I'd like to hear from one of the devs that it won't break anything. A diff of tsc.js between the two version really lights up because the source contains comments.
