### ISSUE TITLE
return wrong definition after util.promise

### ISSUE THREAD

**Issue by yuu2lee4** [microsoft/TypeScript#28020]
typescript: 3.1.3
node: 10.12

before: one optional argument!
![image](https://user-images.githubusercontent.com/8046366/47262660-9b3e7980-d521-11e8-98dc-50fed9c0d221.png)

after: no argument!
![image](https://user-images.githubusercontent.com/8046366/47262663-a2658780-d521-11e8-9bd5-eee1b5dc7ad9.png)

**Comment by mattmccutchen** [comment]
It looks like this is a limitation of the declaration of `promisify` in `@types/node`: it doesn't handle overloaded functions properly.  See #26048 for some more information.  But it looks like you don't need to use `promisify` at all with `bcryptjs` because it already provides promisifed overloads of all the functions you're using.

AFAICT, this is not an issue with the TypeScript compiler.  Please refrain from filing an issue unless and until you've determined that there is an actual bug in TypeScript (i.e., the TypeScript compiler is not working as intended given all of the libraries you are using) or that a given use case cannot be supported by reasonable changes to code and requires a specific change to the TypeScript compiler.  Instead, you can ask questions on Stack Overflow.
