### ISSUE TITLE
Expected 0-2 type arguments, but got 1

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#28053]
**TypeScript Version:**  3.2.0-dev.20181020

**Code**

```ts
new Map<string>();
```
(as of #28052)

**Expected behavior:**

```
No overload expects 1 type argument, but overloads do exist that expect either 0 or 2 type arguments.
```

**Actual behavior:**

```Expected 0-2 type arguments, but got 1.```

**Related Issues:** #19220

**Comment by fatcerberus** [comment]
To be clear, the issue is with the error message and not the error itself, correct?

**Comment by andy-ms** [comment]
Right.

**Comment by pesca** [comment]
@andy-ms As per #19220, the error should give the next lowest and highest arity. What if the arity is not between a pair? Consider:

```ts
new Map<any, any, any>();
```

We get `Expected 0-2 type arguments, but got 3` which isn't contradictory (like the one this issue is trying to address) but still misleading.

Also the expected behavior is incorrect when the given arity does not equal 1. Example: `No overload expects 3 type argument`. Several error messages overlook this detail. Possible solutions:

* Relevant morphemes are parenthesized: `No overload expects 5 type argument(s)`
* Relevant words are parametrized

**Comment by andy-ms** [comment]
> Relevant words are parametrized

I don't think that would work with localization -- we can't have `No_overload_expects_5_type_0, "arguments"` because "arguments" isn't the right word in yiddish. So we have to create two separate error codes if we want to support plurals.

As for `Expected 0-2 type arguments, but got 3`, I suppose that could be `No overload expects 3 arguments, but an overload does exist that expects 2 arguments.

**Comment by pesca** [comment]
@andy-ms OK, I opened a PR.

**Comment by DanielRosenwasser** [comment]
Thanks @pesca!
