### ISSUE TITLE
Unable to discriminate union type because of "Property does not exist"

### ISSUE THREAD

**Issue by lemoinem** [Microsoft/TypeScript#28138]
**TypeScript Version:**  typescript@3.2.0-dev.20181025

**Search Terms:** union narrowing discriminate missing property field

**Code**

```ts
class Foo
{
    private foo: string;
}

class Bar
{
    private bar: number;
}

function fn(baz: { foo: Foo; bar: string; } | { foo: Bar; })
{
    if (typeof baz.bar != 'undefined')
    {
        testFoo(baz.foo);
    }
}

function testFoo(foo: Foo)
{
}
```

**Expected behavior:**
No Error. I can call `testFoo(baz.foo)` since the union type is properly narrowed.

**Actual behavior:**
Property 'bar' does not exist on type 'Baz'. 

Argument of type 'Foo | Bar' is not assignable to parameter of type 'Foo'.
  Type 'Bar' is not assignable to type 'Foo'.
    Property 'foo' is missing in type 'Bar'.

**Playground Link:** https://www.typescriptlang.org/play/index.html#src=class%20Foo%0D%0A%7B%0D%0A%20%20%20%20private%20foo%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Bar%0D%0A%7B%0D%0A%20%20%20%20private%20bar%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Afunction%20fn(baz%3A%20%7B%20foo%3A%20Foo%3B%20bar%3A%20string%3B%20%7D%20%7C%20%7B%20foo%3A%20Bar%3B%20%7D)%0D%0A%7B%0D%0A%20%20%20%20if%20(typeof%20baz.bar%20!%3D%20'undefined')%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20testFoo(baz.foo)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20testFoo(foo%3A%20Foo)%0D%0A%7B%0D%0A%7D

**Related Issues:** I've looked around but found none.

Although, in general, I do understand this should not work, I think it would help greatly if we had a way to discriminate on properties that are only in some of the members of a union.

One of the solutions could be to type properties, that are missing in some of the union members as `prop?: void`, or `prop?: never`, or `prop?: undefined`, or whatever makes sense in the type system.

**Comment by jack-williams** [comment]
> Although, in general, I do understand this should not work, I think it would help greatly if we had a way to discriminate on properties that are only in some of the members of a union.

This should work

```ts
function fn(baz: { foo: Foo; bar: string; } | { foo: Bar; })
{
    if ("bar" in baz)
    {
        testFoo(baz.foo);
    }
}
```

With this PR #27695 you can also do this:
```ts
function fn(baz: { foo: Foo; bar: string; } | { foo: Bar; bar: undefined })
{
    if (baz.bar !== 'undefined')
    {
        testFoo(baz.foo);
    }
}
```

**Comment by lemoinem** [comment]
@jack-williams Your suggestion works. Thank you!

I'll keep this issue open as I think it should be documented and/or we could have better syntax for it... but I might be wrong. I'd like a member of TS team to have a look and provide a definitive decision on that if you don't mind...

**Comment by weswigham** [comment]
BTW, there's a good reason this:
```ts
function fn(baz: { foo: Foo; bar: string; } | { foo: Bar; })
{
    if (typeof baz.bar != 'undefined')
    {
        testFoo(baz.foo);
    }
}
```
doesn't work - consider this call:
```ts
fn({bar: 12, foo: new Bar()});
```
that's a valid call (assignable to the second union member), and is why even if you were to check that `bar` wasn't `undefined` in the input, you might still not have a `Foo` for `foo`. The `in` operator is intentionally a little unsound here, but we figured that its usage was infrequent enough that if you use it you really wanted it to act like this.

**Comment by lemoinem** [comment]
Indeed. I haven't thought of this case.
I guess it would impossible to implement it in a completely sound way.

Thanks for your answer!

**Comment by nuts-n-bits** [comment]
> BTW, there's a good reason this:
> 
> ```ts
> function fn(baz: { foo: Foo; bar: string; } | { foo: Bar; })
> {
>     if (typeof baz.bar != 'undefined')
>     {
>         testFoo(baz.foo);
>     }
> }
> ```
> 
> doesn't work - consider this call:
> 
> ```ts
> fn({bar: 12, foo: new Bar()});
> ```
> 
> that's a valid call (assignable to the second union member), and is why even if you were to check that `bar` wasn't `undefined` in the input, you might still not have a `Foo` for `foo`. The `in` operator is intentionally a little unsound here, but we figured that its usage was infrequent enough that if you use it you really wanted it to act like this.

Hi, I strolled by this thread randomly and I am immediately baffled as to why `fn({bar:12, foo: new Bar()})` should be a valid call? 
Let me play the role of a verbose compiler: 
 1. value `{bar: 12, foo: new Bar()}` cannot be assigned to `{foo: Foo, bar: string}`, because bar is 12, 12 is not string.
 1. value `{bar: 12, foo: new Bar()}` cannot be assigned to `{foo: Bar}` either, because it contains an extra bit `bar: 12`, and TS2322 says: "object literal may only specify known properties". field bar is unknown to type `{foo: Bar}`.
 1. So I will throw an error, I can either reject it because 12 is not a string, or I can reject it with TS2322.

And I tested it, indeed `fn({bar:12, foo: new Bar()})` is not valid call, as tsc complains that number 12 is not a string. (tested for strictNullCheck = true and false)

But then here comes the weird part: `fn({bar:"lol", foo: new Bar()})` is a valid call! This surprises me, as it still doesn't fit either type, for the same reasons the verbose compiler rejected it earlier. Let me role play again:
 1. value `{bar:"lol", foo: new Bar()}` cannot be assigned to `{foo: Foo, bar: string}`, because foo is new Bar(), which is not a Foo.
 1. value `{bar:"lol", foo: new Bar()}` cannot be assigned to `{foo: Bar}` either, because it contains an extra bit `bar: 12`, and TS2322, blah blah.
 1. I should raise an error saying either new Bar() cannot be assigned to Foo, or TS2322.

But since reality doesn't agree with me, it must be I'm understanding union types wrong, or maybe TS has a bug. Do you know what's happening here?

**Comment by RyanCavanaugh** [comment]
> value {bar:"lol", foo: new Bar()} cannot be assigned to {foo: Bar} either, because it contains an extra field bar: 12, and there is a TS rule against that.

This is the wrong bit -- extra fields are allowed when there is some matching property in the target across any union member.

**Comment by nuts-n-bits** [comment]
> This is the wrong bit -- extra fields are allowed when there is some matching property in the target across any union member.

Yeah, about that. 

That was my initial feeling so I did some more testing which ended up contradicting this.

```ts
declare function id_or_name(input: {id:number; name:"joe"}|{name:string})
id_or_name({id:3, name:"alex"})  // Argument of type '{ id: number; name: string; }' is not assignable to parameter of type '{ id: number; name: "joe"; } | { name: string; }'. Object literal may only specify known properties, and 'id' does not exist in type '{ name: string; }'.ts(2345)
```
Somehow this time it doesn't work again. I notice though that if instead of having `name:<primitive type/literal type>` in the parameter, you have `name: <ObjectType>`, then it behaves like you describe again.

```ts
function id_or_name(input: {id:number; name:Date}|{name:string}): void {return}
id_or_name({id:3, name:"alex"})  // no problem
```
