### ISSUE TITLE
Compiling with -d should emit triple-slash lib paths

### ISSUE THREAD

**Issue by bcherny** [microsoft/TypeScript#28195]
## Search Terms

Triple slash, reference, path, lib, library, types, typings, dom

## Suggestion

When compiling a *.ts* file with `declaration: true`, TSC should emit triple-slash reference paths for all `lib`s consumed by the *.ts* file.

## Problem

Say I publish typings for my package `foo` to NPM, and `foo` depends on DOM typings. I then include `foo` in my project (`npm install foo`). There are a few things that can happen:

1. If `foo`'s typings include `<reference lib="dom" />`:
  - `foo` has access to DOM
  - My project has access to DOM types (**is this sort of leakage desirable?**)

2. If my project includes `dom` (or uses the same triple-slash directive as in 1):
  - `foo` has access to DOM
  - My project has access to DOM types

3. Neither my project nor `foo` include `<reference lib="dom" />`:
  - `foo` errors wherever it uses DOM types (but I have to inspect *node_modules/foo/index.d.ts* to see those errors)
  - My project treats `foo`'s DOM types as `any`s (**should this error in `strict` mode?**)

    ```ts
    // foo.d.ts
    export function a(): HTMLInputElement

    // myProject/index.ts
    import {a} from 'foo'
    a() // any
    ```

## Solution

If `tsc -d` generated triple-slash directives for `foo/index.d.ts`, we can ensure that we're always in case (1). This is nice because if my project doesn't use `dom`, I shouldn't have to declare it for the sake of `foo` like I did in (2); it also avoids the `any` from (3).

```ts
// Before
export function a(): HTMLInputElement

// After
/// <reference lib="dom" />
export function a(): HTMLInputElement
```

An open question is how strict should TSC be? Ie. If `foo` uses `dom` but fails to reference it, should this cause a compile error in my project (and a nice message suggesting I add a reference to `dom`)?

## Checklist

My suggestion meets these guidelines:
* [ ] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by kitsonk** [comment]
While you don't think this would be a breaking change, it could actually be a breaking change.  Referencing a lib changes the behaviour of the way that TypeScript's compile context works, and it is then something that can't be easily overridden downstream.  If you are running or compiling TypeScript in a situation where you are targetting a non-browser context, like Node.js or some sort of embedded system, and some random `.d.ts` drags in the `dom` lib, you could have lots of runtime issues with the code.  This is something that would be surprising given the current behaviour.

Also, there are always other ambient types which are not reflected in `.d.ts` file, like anything in `@types`.  So this would only solve part of the problem of the dependency.

My opinion is that it really is up to the author to determine if these need to be present in the files.

**Comment by bcherny** [comment]
@kitsonk I left "This wouldn't be a breaking change" unchecked on purpose 😄

**Comment by kitsonk** [comment]
DOH! Sorry... 😜

**Comment by tschettler** [comment]
I’m actually running into this problem right now for a slightly different use case. I have an ambient module to extend functionality of a dependent third-party library and also fix invalid or missing declarations it has. I am loading it into my main using a reference path. When I build my project using tsc and specify an outDir, the new declaration file for my main has an invalid path reference for the ambient type module because the declaration file is not included in the build output. This causes downstream build issues for consuming applications due to the missing declarations. The only thing I have found to do that works is change the ambient module file extension from .d.ts to .ts, and then it is included in the build output. This approach doesn’t sit well with me though due to the ambient module having no implementations. I also want to keep this declaration shim transparent to the consuming applications.

**Comment by Luke-zhang-04** [comment]
Not sure why this issue is dead but it would've been really nice to see in Typescript 4
