### ISSUE TITLE
Adding Yarn to README

### ISSUE THREAD

**Issue by wirob** [Microsoft/TypeScript#28208]
suggestion readme yarn

Add instructions on how to install TS with yarn.

**Comment by DanielRosenwasser** [comment]
If you're using yarn I think you can figure out how to translate npm commands to yarn.

**Comment by wirob** [comment]
Couldn't that also be said about NPM?

Wouldn't it be better to have both of them in the readme just so that TS wouldn't take sides in which package manager to use?

**Comment by weswigham** [comment]
Providing any instruction at all for `yarn` _is_ taking sides - it's tacitly endorsing `yarn`. `npm` is the canonical package manager bundled with a standard node install - `yarn`, `pnpm`,  `jspm`, and `cnpm` are all community alternatives - sure `yarn`'s somewhat popular, but anyone using it aughta know how to install packages from the `npm` registry and what its equivalents are to `npm` commands. It's a bit pessimistic of me to state it, but I'd assume that the reason all of `fb`'s projects dual list instructions for `npm` and `yarn` is _explicitly_ to advertise for `yarn` and proliferate its name , not because anyone really thinks that node devs need the same command listed twice with a different executable(+flag) at the front!

**Comment by DanielRosenwasser** [comment]
It's not really about taking sides in my opinion (note: Yarn's one of my favorite tools in the Node ecosystem, and I don't think it's just "somewhat popular" 🙂). Rather, 

> anyone using it aughta know how to install packages from the npm registry and what its equivalents are to npm commands.

That's my main objection. We haven't received any questions from users on the matter so I'd prefer not to duplicate the commands in the `README.md`.

**Comment by wirob** [comment]
Great points. And I agree with you.

I couldn't find any issues for this topic so I just wanted to ask the question.
