### ISSUE TITLE
Handbook: clarify different declaration merging scenarios

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#2825]
doesn't work
```typescript 
declare module M {
   interface I {
     fn: {
          (value: number): string;
     }
   }
}

declare module M {
   interface I {
     fn: {
         (value: Date): boolean;
     }
   }
}
```

works
```typescript
declare module M {
   interface I {
     fn(value: number): string;
   }
}

declare module M {
   interface I {
     fn(value: Date): boolean;
   }
}
```

Am  I missing something?

**Comment by RyanCavanaugh** [comment]
Overloads don't combine across anonymous types, the same way these wouldn't combine if the `fn` declarations were `fn: { x: number }` and `fn: { y: number }`

It's a tricky balance because we don't want to just *always* merge types -- detecting conflicts is a key value in static typing -- but sometimes you do want to merge. The syntactic form of `fn` in this case tells us you really mean for `fn` to be a function rather than some object type, and that's our cue to let the merging continue.

**Comment by aleksey-bykov** [comment]
> wouldn't combine if the `fn` declarations were `fn: { x: number }` and `fn: { y: number }`

(out of curiosity, why wouldn't you?)

Anyway I think what you just said should be in the handbook.

**Comment by mhegazy** [comment]
@aleksey-bykov is the information in https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Declaration%20Merging.md sufficient to address this issue?

**Comment by DanielRosenwasser** [comment]
It wouldn't be, that page hasn't been amended with this information since this issue was filed. I've filed https://github.com/Microsoft/TypeScript-Handbook/issues/129.

Though I'll let @aleksey-bykov speak for himself. :smile:

**Comment by mhegazy** [comment]
thanks @DanielRosenwasser. closing this in favor of Microsoft/TypeScript-Handbook#129.

**Comment by aleksey-bykov** [comment]
thanks guys, your are the bestest, [ryan's anwer](https://github.com/Microsoft/TypeScript/issues/2825#issuecomment-94119559) was good enough for me, i believe it can be copied/pasted to the handbook

**Comment by DanielRosenwasser** [comment]
:heart:
