### ISSUE TITLE
Suggestion: refactor to "renamed" named import

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#28367]
## Suggestion

``` tsx
import { foo } from 'bob';

foo();
```

I want to rename the named import but only within this module.

This is possible via ["renamed named imports"](http://exploringjs.com/es6/ch_modules.html#_importing-styles).

A refactoring could update the import along with any internal references:

``` tsx
import { foo as mySpecialFoo } from 'bob';

mySpecialFoo();
```

I'm happy to help implementing this if other people are interested and someone can guide me. 😄 

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by purpledrgn** [comment]
This seems to have already been put into effect for some time. On Version: 1.30.2 and this is how F2 / "Symbol Rename" works.

**I believe it to be a total nuisance!** It completely removes the ability to *intentionally* rename a symbol globally. I don't see any configuration option to switch it back or alternative shortcut.

I understand some people find it convenient for it to always alias, but that's single Ctrl+H or a simple "as [something]" in a single file. On the other hand if I am actively working on a feature and need to modify names of things (because it's something actively worked on; or maybe there's very good reason to rename globally) there's now no easy/safe way to do it outside of going into every file and every little symbol reference (which could be 100).

The use case it removes is far more sensitive and hard to do then the mild convenience it provides. 

Please revert this change or just add back the old functionality.

cc @weswigham

**Comment by OliverJAsh** [comment]
Sounds like a bug, separate from this suggestion to add this functionality as an optional refactor. @purpledrgn Perhaps open a separate issue or search to see if someone already has?

**Comment by purpledrgn** [comment]
But report #29238 (for anyone stumbling on to this problem)

**Comment by OliverJAsh** [comment]
This can be closed because this is now the default behaviour. It can be disabled with these settings:

```json
"typescript.preferences.renameShorthandProperties": false,
"javascript.preferences.renameShorthandProperties": false,
```
