### ISSUE TITLE
The type of assignment expression is not left value's type.

### ISSUE THREAD

**Issue by heroboy** [Microsoft/TypeScript#2841]
Paste code at http://www.typescriptlang.org/Playground
```typescript
interface Number2Number
{
	[id:number]:number;
}

var y:Number2Number;
var z;

var x = (y = {});
var x2 = (z = 1);
var x3 = (z = {});

x[1] = 0;
```
the x's type is ` { [x:number]:undefined } `, it's neither type of y nor `{}`.
And x2's type is `number`.
And x3's type is `{}`.

According to https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#4.17 ,it should be the type of y.

**Comment by DanielRosenwasser** [comment]
> According to https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#4.17 ,it should be the type of y.

I'm seeing the opposite in the spec:

> The result is a value with the type of *expr*.

**Comment by heroboy** [comment]
> The result is a value with the type of expr.

then x's type should be `{}`, not `{ [x:number]:undefined }`

**Comment by RyanCavanaugh** [comment]
The spec ultimately defines what should happen here in section 4.5 (the `{}` is contextually typed by the type of `y`, so it acquires an index signature):

 > Likewise, when an object literal is contextually typed by a type that includes a numeric index signature, the resulting type of the object literal includes a numeric index signature with the union type of the types of the numerically named properties (section 3.8.4) declared in the object literal, or the Undefined type if the object literal declares no numerically named properties.

I believe the spec says `undefined` here because `undefined` is assignable to anything; we could just as easily (I think?) say the index signature has the same type as the contextual type's signature.

Assignment expressions are the only place where the type produced by a contextual typing is observable, hence the weirdness. I remember talking to @JsonFreeman about this a while ago but I don't see any bugs on it; IIRC the conclusion was "probably no one will ever notice this". Just for curiosity, did you hit this in actual code?

**Comment by DanielRosenwasser** [comment]
#1655 is the issue I wanted to dig up for the response.

**Comment by heroboy** [comment]
Thank you @DanielRosenwasser .
Yes, I think it's the same issue.
I opened the issue because the above code `x[1] = 0;` compiles error in the new released typescript.
And I tested the code in playground, and searched issues,there's no duplicatted one.
So is there any playground for the latest typescript, then I don't need to open an already fixed issues?

**Comment by ahejlsberg** [comment]
The example produces an error in the playground (which is based on 1.4 currently), but not with the compiler in master.

With the compiler in master the inferred type of x is `{ [x: number]: any }`. The indexer is present in x's type because the `{}` is contextually typed by y, and y has an indexer. Specifically, the `{}` is given the type `{ [x: number]: undefined }`, and this type is subsequently widened to `{ [x: number]: any }`. This matches the spec.

**Comment by JsonFreeman** [comment]
Yes, as I recall, it produces `{ [x: number]: any }` as of #1795

**Comment by RyanCavanaugh** [comment]
Does it generate an implicit any warning?

**Comment by JsonFreeman** [comment]
And to @RyanCavanaugh's point, using an assignment as an expression does leak the contextual type. Contextual typing is not designed to handle assignments in expression position because it is not common.

**Comment by JsonFreeman** [comment]
Yes, it gives an implicit any error from widening
