### ISSUE TITLE
when has optional elements in tuple types, Promise.all has error

### ISSUE THREAD

**Issue by jkchao** [microsoft/TypeScript#28427]
**TypeScript Version:**  3.1.3

**Search Terms:**
Promise.all, optional elements in tuple types

**Code**
```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.

const arr: [Promise<number>, Promise<string>?] = [
  Promise.resolve(1)
];

arr[1] = Promise.resolve('1');

Promise.all(arr);    // Error

// or

const arr2: Array<Promise<number> | Promise<string>> = [Promise.resolve(1)];
arr2.push(Promise.resolve('1'));

Promise.all(arr2);   // Error
```

**Expected behavior:**

`Promise.all(arr)` should be correct 

**Actual behavior:**

**Comment by grassator** [comment]
The same (or similar) error happens when working with an array that can contain undefined items, [which is OK according to the spec](https://www.ecma-international.org/ecma-262/9.0/index.html#sec-performpromiseall):

```ts
declare const foo: (Promise<number> | undefined)[]
Promise.all(foo) // error
```

Since TS now has conditional types, I could imagine that the definition should be something like:

```ts
type UnwrapPromise<T> = T extends PromiseLike<infer U> ? U : T

declare function promiseAll<T>(values: T[]) : UnwrapPromise<T>;
promiseAll(foo) // (number | undefined)[]
```
