### ISSUE TITLE
[propname] type becomes a string.

### ISSUE THREAD

**Issue by tolerance-go** [Microsoft/TypeScript#28437]
```ts
export interface Attr {
  position: Point;
  width: number;
  height: number;
  opacity?: number;
  rotate?: number;
  scale?: number;
}

type PickAttr = { [key in keyof Attr]: number | Point };

function (attrs: Attr[], attrname: keyof Attr) : PickAttr[] {
      const pickAttrs = attrs.map(attr => ({
        [attrname]: attr[attrname],
      }));
     return pickAttrs
}
```

![image](https://user-images.githubusercontent.com/37258382/48279099-830bab80-e48a-11e8-9f3e-0c85cd7fc331.png)

The actual type returned is inconsistent with the type returned by the declaration, I don't know where I wrote it wrong, I hope you can help me

**Comment by tolerance-go** [comment]
I solved this problem using the as keyword `return pickAttrs as PickAttr[] `，Is that the right thing to do？

**Comment by andy-ms** [comment]
When you write `type PickAttr = { [key in keyof Attr]: number | Point };`, you define a type that maps *all* keys in `keyof Attr` to `number | Point` -- but you're creating an object that only has one property. The error goes away if you use `type PickAttr = { [key in keyof Attr]?: number | Point };`, so that every property is optional.

**Comment by tolerance-go** [comment]
thx @andy-ms
