### ISSUE TITLE
Typescript parsed spread operator in function call problem

### ISSUE THREAD

**Issue by gilbertoalbino** [Microsoft/TypeScript#28486]
I have a piece of code as is:

```
function add(a: number, b: number, c: number) {
  return a + b + c;
}

const hexagons = [1, 6, 15];

const result = add(...hexagons);
```

And VS Code complains about:
`[ts] Expected 3 arguments, but got 0 or more.`

I haven't found if it is necessary to set some config option or this is a bug in the VSCode TS parser itself.

But it is valid code in Chrome:
```
function add(a, b, c) {
  return a + b + c;
}
const hexagons = [1, 6, 15];
const result = add(...hexagons);
```

So I think VSCode is wrongly parsing TS.

**Comment by mjbvz** [comment]
Doing this with array types in general is not valid typescript because you can easily have:

```ts
function add(a: number, b: number, c: number) {
  return a + b + c;
}

const hexagons = [1, 6, 15];

hexagons.pop();

const result = add(...hexagons);
```


Not sure if there are existing TS feature requests that would allow this to be supported

**Comment by weswigham** [comment]
Control flow narrowing of singleton and literal types would about cover it, I think. #16896 specifically mentions what seems to be exactly this.

**Comment by Nathan-Fenner** [comment]
@gilbertoalbino The actual problem with your code is that `hexagons` has the inferred type `number[]`. So `...hexagons` could be 0, 1, 2, 3, ... arguments, even though you must pass 3.

@mjbvz 's point is that because you could pass a `[number, number, number]` value to a function that removes an item from it, it's not sound to permit you to spread it onto your function (or you'd pass an `undefined` where a `number` was expected).

Today, you can fix this just by adding a type annotation

```ts
function add(a: number, b: number, c: number) {
  return a + b + c;
}

const hexagons: [number, number, number] = [1, 6, 15];

const result = add(...hexagons);
```

If you're going to be using this type frequently, I recommend a type definition:

```ts
type Triplet = [number, number, number]

const hexagons: Triplet = [1, 6, 15];
```

It will probably be a while before a complete auto-narrowing solution can be made for object types.

**Comment by gilbertoalbino** [comment]
@Nathan-Fenner indeed using type annotation goes away with the error :   

`[ts] Expected 3 arguments, but got 0 or more.`

But I think I haven't understood yet why this parse error is being triggered.
