### ISSUE TITLE
Declare all missing members quick fix

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#28491]
In #28298 we added a new message that elaborated on several of the missing properties in a type. We should specialize the fix here.

**Comment by Anima-t3d** [comment]
Any update on this, this would be very helpful.

**Comment by cagcak** [comment]
This possible feature might be very helpful. An equivalent action on intellij webstorm is the following:
![equelivent-action-on-webstorm](https://user-images.githubusercontent.com/1567108/95172883-9d5a7b00-07c0-11eb-9834-4ee731b0e424.gif)

**Comment by jaikjoy** [comment]
Do we have any updates on this?

**Comment by tamj0rd2** [comment]
I've made a typescript language server plugin and vscode extension that adds some of this functionality.

Extension: https://marketplace.visualstudio.com/items?itemName=tamj0rd2.ts-quickfixes-extension
Language server plugin: https://www.npmjs.com/package/ts-quickfixes-plugin

It's very basic and doesn't support many cases yet, so please raise an issue if your use case isn't covered: https://github.com/tamj0rd2/ts-quickfixes

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser It seems this issue has many reactions :). I think `fixAddMissingMember` resolves this issue partially. Could you add more cases that need to add to `fixAddMissingMember`?

**Comment by DanielRosenwasser** [comment]
Seems like you'd need to reconstruct the information about which object literal is causing the missing properties issue. If you can get that object literal, you can totally imagine something where:

1. For any missing property whose name exists locally (but maybe not in the global scope), use that as a shorthand property. Potentially, check that the types are compatible if you can first.
2. If that fails, see if the property type has a call signature. If so, scaffold out a method body like throw new Error("not implemented!")
3. Otherwise, create a property declaration and set it to `undefined`. The user will have to correct it manually.

**Comment by chris-schmitz** [comment]
I would definitely love this feature too, just a quick fix to fill everything in would definitely be nice. 

That said, for anyone looking for this feature there is a way of doing it now though it's not as easy as a quick fix to fill everything in. 

VSCode has a command called "Trigger Suggest" that's used to show typeahead suggestions based on the current code context. In the case of missing type definitions of an interface, because the compiler knows the type definition and what's currently missing you can use the suggestion trigger to get the list of suggested properties. 

You can trigger this either from the command pallet or from the keyboard shortcut `shift + cmd + ,` (I'm pretty sure that's the default and not a remapping I did and forgot about :P )

![trigger suggest](https://user-images.githubusercontent.com/2437424/107878654-cfc86300-6e99-11eb-950f-7a0c076539af.gif)

Definitely not as nice as a quick fix that shortcuts all of the properties for you, but still helpful.

**Comment by tamj0rd2** [comment]
> Seems like you'd need to reconstruct the information about which object literal is causing the missing properties issue. If you can get that object literal, you can totally imagine something where:
> 
> 1. For any missing property whose name exists locally (but maybe not in the global scope), use that as a shorthand property. Potentially, check that the types are compatible if you can first.
> 2. If that fails, see if the property type has a call signature. If so, scaffold out a method body like throw new Error("not implemented!")
> 3. Otherwise, create a property declaration and set it to `undefined`. The user will have to correct it manually.

Could something like the extension I posted above be useful? It doesn't check for variables in scope to use as a shorthand, but I could spend a bit of time looking into that. For your 3rd point, it instead gives you a default value. e.g if the property is of type number, it will make a property declaration of `0`. If it's a string, it will do `"todo"`.

I'm keen on starting a PR if this is something the TS team would be happy with!

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!

**Comment by connorjclark** [comment]
For extremely nested/deep object types, this QF would do too much, especially if you are passing references to other objects around (ex: you have a `car` in local scope, and are missing property `car` on a `Purchase` object: preference would be to autofill `car: undefined` or `car: {}` on the `Purchase` object literal, not `{car: {...maybe hundreds of nested properties...}}`). Of course, this is context-specific, so I suggest a seconds QF: "Declare all missing members (shallow)".

There is a VSCode extension that does the same, here was my feedback: https://github.com/tamj0rd2/ts-quickfixes/issues/183
