### ISSUE TITLE
Cannot index generic type with string/keyof union

### ISSUE THREAD

**Issue by WiseBird** [Microsoft/TypeScript#28570]
**TypeScript Version:** 3.2.0-dev.20181115

**Search Terms:**
"cannot be used to index"  union keyof

**Code**

```ts
function func<T>(
    t:  T,
    parameterStr: string,
    parameterKey: keyof T,
    parameterUnion: string | (keyof T),
) {
    console.log(t[parameterStr]);
    console.log(t[parameterKey]);
    console.log(t[parameterUnion]);
}
```

**Expected behavior:**
No error

**Actual behavior:**
`Type 'string | keyof T' cannot be used to index type 'T'.`

**Playground Link:** 
[Link](https://www.typescriptlang.org/play/index.html#src=function%20func%3CT%3E(%0D%0A%20%20%20%20t%3A%20%20T%2C%0D%0A%20%20%20%20parameterStr%3A%20string%2C%0D%0A%20%20%20%20parameterKey%3A%20keyof%20T%2C%0D%0A%20%20%20%20parameterUnion%3A%20string%20%7C%20(keyof%20T)%2C%0D%0A)%20%7B%0D%0A%20%20%20%20console.log(t%5BparameterStr%5D)%3B%0D%0A%20%20%20%20console.log(t%5BparameterKey%5D)%3B%0D%0A%20%20%20%20console.log(t%5BparameterUnion%5D)%3B%0D%0A%7D)

**Related Issues:** 
#23618

**Comment by ahejlsberg** [comment]
This is working as intended. In `--strict` mode, all but `t[parameterKey]` are errors because an indexed access `T[K]` is permitted only if `K` is known to be assignable to `keyof T`, and `string` is not.

The reason you don't get an error on `t[parameterStr]` in the default non-strict mode is that we allow _any_ object to be indexed with a string, producing a value typed as `any`. This is legacy behavior and becomes an error in `--noImplicitAny` mode (which is turned on by `--strict`).
