### ISSUE TITLE
Reflection via Reified Types

### ISSUE THREAD

**Issue by chris-pardy** [Microsoft/TypeScript#28608]
## Search Terms
- Reflection
- Reflect
- Reified
- Runtime Type checking
## Suggestion
Add support for Reflection via [Reified Types](https://en.wikipedia.org/wiki/Reification_(computer_science)). This would require 2 changes.
1. A new type `Type<T>` that would be used to represent the type information via reflection. (structure TBD, can match data in design:metadata)
2. Allow types to be passed as values if an argument is of type `Type`. This would cause the compiler to generate the reflective structure and pass it.

## Use Cases
This would just provide the information necessary for library developers to solve other use cases
- Runtime type checking
- Data serialization via reflection
- Anything else that needs runtime reflection data.
It's more general than using decorators because decorators cannot decorate functions, therefore are completely useless from a functional programming perspective.

## Examples
A runtime type checking library could implement:
```
export function typeChecked<T,R>(arg1Type: Type<T>, func: (arg1: T) => R): (arg1: unknown) => R {
   ...reflect over arg1Type to do runtime type checking...
}
```
Code using the library would then do:
```
import {typeChecked} from 'library';

export type Named = {name: string};

export const typeCheckedFunction = typeChecked(Named,function({name}: Named): string) {
 .... some interesting code ....
});
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code - Current using a type as a value is an error, this would change that in a subset of cases.
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions - Specific reflection structures need to be emitted for each type that undergoes reification but this doesn't require inspection of expression types, simply detecting use of a type as a value.
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.) - 100% could be done in code generation.
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals)

**Comment by jack-williams** [comment]
I think this violates two of the guidelines (3) and (4). Have you looked at how this could be implemented by using a compiler plugin?

**Comment by chris-pardy** [comment]
@jack-williams I would disagree that this violates 3, and 4. But I want to make sure I understand your question. Are you suggesting that I build a compiler to look into the implementation, or is the suggestion that a compiler plugin could replace having this in typescript?

On the guidelines, I want to stress that this wouldn't be different than how enums work now where information exists both in the type system and runtime.
3. Code wouldn't emit differently based on type, there would simply be support for passing a `type` to a function, it would be sent as an instance of `Type<>`. An interface that's TBD but would be the same as the metadata already being written.
4. This wouldn't require runtime code changes, it's simply compile time annotation of type information.

**Comment by jack-williams** [comment]
> Are you suggesting that I build a compiler to look into the implementation, or is the suggestion that a compiler plugin could replace having this in typescript?

The latter. Have something that looks at arguments of special marked types and does an AST rewrite to insert the code you need. I may be talking nonsense but it seems like it _might_ be possible.

It may well be that I'm missing something and I've misunderstood. What would happen in cases such as:
```ts
function foo() {
    return 3;
}
export type Foo = ReturnType<typeof foo> extends string ? number[] : string[]
export const typeCheckedFunction = typeChecked(Foo, ...
```
Would this be rejected or have some special treatment?

**Comment by AnyhowStep** [comment]
I'm neither for nor against reflection but it does look like it goes against their design goals.

I've had situations where I wished for reflection but I think I've almost always found ways to restructure my code to not need it.

-----

Personal rant below.

I never understood letting a compiler or IDE or some tool create runtime checks for you.

For any non-trivial program, there's always *something* that makes these runtime checks insufficient.
For example, in TS' type system, how would you say "I want this field to be a positive integer"?

You cannot. Because `number` is as good as it gets. You could do some hack-ery but that's not very... portable. You'd have many people with many ways to get it done unless TS' has explicit support.

I say this as someone who's had multiple iterations on such hack-ery until I realized that automated runtime checks just don't work out too well. You end up having to write manual validators to augment the automated ones, in the end.

Composing validators by hand gets you very good results, imo.

**Comment by weswigham** [comment]
Reflection and type reification, by definition, require us serializing the design time types to the runtime - we have no intent to do this beyond the limited support we've written for decorator metadata.

**Comment by chris-pardy** [comment]
@weswigham why would this be out-of-scope if it's the same scope as decorator metadata which was already implemented?

**Comment by chris-pardy** [comment]
@AnyhowStep decorating a function like that is fine, however you cannot decorate function parameters, but really the idea was to create a generic way to allow you to pass type information, how it gets used is up to library creators.

**Comment by weswigham** [comment]
To be honest, it's because we only support decorator metadata as a legacy thing. (If it didn't already exist, we likely wouldn't implement it) Type-directed emit causes a bunch of headaches in terms of how we emit stuff and how we provide services - especially troublesome is how it makes emit dependent on the typechecker pass, which reduces opportunities to parallelize our pipelines (and seriously hampers our ability to recompose transforms arbitrarily). Our Babel transformer actually doesn't support any of our type directed emit features (notably const enums) for this reason.

**Comment by ab-pm** [comment]
Many of the libraries mentioned in #1573 can do something like this.
