### ISSUE TITLE
TS: cannot add imports for "Event"

### ISSUE THREAD

**Issue by bpasero** [microsoft/TypeScript#28739]
This never gives me a code action to add the import, probably because "Event" is already defined in the DOM:

![image](https://user-images.githubusercontent.com/900690/46281281-8ac46000-c56e-11e8-988d-1a53e84c2c9a.png)

**Comment by mjbvz** [comment]
I believe the request is to understand that `Event<T>` does not match the `Event` type from `lib.dom.d.ts` and may be defined somewhere else

**Comment by alexandrudima** [comment]
I often encounter this issue with classes `Position` and `Range`. It appears the `lib.d.ts` contains definitions for those too and the quick fix never realizes the global definition is not what I want (in order to suggest an import quick fix)

**Comment by RyanCavanaugh** [comment]
The auto-imports for these symbols are already in the completion list, so that's the best way to import these if that's what you intend to do.

Apart from the edge cases where the reference to the type is provably wrong (which is, AFAICT, *only* when their generic arities don't match, which I imagine is very rare for any two types of the same name), then there's not really anything we can do in terms of a "quick fix" -- once the reference to the type is legal, any further errors or unexpected behavior aren't distinguishable from normal typos or misunderstanding. More problematically, even offering something like "Overwrite the reference to `Position` with an auto-import at the place it was declared" might alter a file other than the one you're editing and cause downstream problems elsewhere. At the end of the day the editor can't be sitting around second-guessing code that is facially valid without creating even worse user friction, performance problems, or both.

**Comment by bpasero** [comment]
Sorry I do not follow. In VSCode I cannot import our `Event` type:

![image](https://user-images.githubusercontent.com/900690/90723710-8a95f080-e2bd-11ea-9ce1-96d01c922db7.png)

Please let me know how I can clarify this better.

**Comment by bpasero** [comment]
Just to give you an example of the pain I have to go through each time this happens:

![recording](https://user-images.githubusercontent.com/900690/90736444-0a2bbb80-e2ce-11ea-8f3b-9a0a1a9ccc0b.gif)

**Comment by DanielRosenwasser** [comment]
Yeah, I know this is painful. We had a sort of mixed discussion on this.

The problem is that there's no way to know until after you've used a type that it's wrong. In the case of `Event`, you can imagine a quick fix to suggest another type where the heuristic is "this one takes type arguments, this one doesn't". That's a potentially reasonable one, and I was personally not against it, but a few people in the editor sync felt like that could potentially be noisy if we suggested the wrong type.

In the case of @alexdima's example, there's no way until any arbitrary operation to know that the type is "wrong"; even if you can figure that out, figuring out which type is "right" could be expensive to do it accurately.

Now you mentioned that there's no way to auto-import `Event` because the global overrides it. That shouldn't be the case, but when we experimented with it in the editor sync, we noticed that a lot of the time, auto-imports are significantly deprioritized to the point where they aren't noticed.

Trying it out on your codebase, I'm definitely seeing `Event` come up (though unfortunately it looks like there are duplicates?)

![eventAutoImportsInVsCodeCodebase](https://user-images.githubusercontent.com/972891/90743586-9c0ed680-e284-11ea-83f8-bf894f7b8798.gif)

**Comment by bpasero** [comment]
@DanielRosenwasser ah yeah good point about the import when you type the name, that helps. I think I often just copy this over from an interface and then miss the suggested auto imports.
