### ISSUE TITLE
Implicit any diagnostics for interface members

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#28750]
```ts
interface Man { man }
interface Bear { bear }
interface Pig { pig }
interface Dog { dog }
interface Cat { cat }
interface Platypus { platypus }
```

None of these should have suggestion diagnostics.

![image](https://user-images.githubusercontent.com/972891/49260832-3d406400-f3f4-11e8-8645-a0cb3f284894.png)

**Comment by sandersn** [comment]
More generally, reportImplicitAnyError should not add suggestions for which no codefix exists yet. There’s more than one of these. It’s unfortunate to couple the checker logic so closely to codefix capability, but that’s kind of what suggestions are *for*.

@DanielRosenwasser  Pretty sure nobody in the real world has noticed this yet because they think the type is required here. Same for any type declaration, I bet.

**Comment by sandersn** [comment]
Are you running the latest language service? When I saw you demo this bug in person, you weren't getting any codefixes for the suggestion. But when I tried to repro it just now, I got a codefix that works properly; it inserts any when no usages exist, and infers types given some usage like `let mann: Man = { man: "homme" }`

**Comment by sandersn** [comment]
Inspecting the code makes it look like it only applies to binding elements. Here's a repro:

```ts
function cdadr([car, cdr]) {
  return car + cdr
}
```

It should be possible to infer `string | number` for both car and cdr, but the infer-from-usages codefix doesn't even try right now. The suggestion should be disabled until that feature is added.
