### ISSUE TITLE
Cannot find module *.*

### ISSUE THREAD

**Issue by EddyVinck** [Microsoft/TypeScript#28808]
Hi, I started converting a project to TypeScript. I looked in the issues and googled and looked in the docs and I could not find a solution for this.

How do I import files while using asterisks in my path? Or does this not work at all? I think this might be a bug.

**TypeScript Version:**  3.2.1

**Search Terms:**
- `*`
- `*.*`
- `cannot find module asterisk`
- `import images`

**Code**

```ts
import imageUrls from "../../img/*.*";
```

**Expected behavior:**
Import any filename with any file extension

**Actual behavior:**
TypeScript error: `Cannot find module '../../img/*.*'.`

**Comment by kitsonk** [comment]
It isn't a bug.

You are expecting some sort of special behaviour from your loader/packager that isn't part of the official ES Module specification/loader.  Because of that, TypeScript has no clue as to what you expect to be returned from that.  It is trying to resolve to a module, not a random list of files?!

TypeScript supports [wildcard module declarations](https://www.typescriptlang.org/docs/handbook/modules.html#wildcard-module-declarations) which can solve this issue for you.

**Comment by EddyVinck** [comment]
Thank you for your help. I think the wildcard module declarations will fix my issue.
