### ISSUE TITLE
using checkJs breaks intellisense on a deep require with no declaration file

### ISSUE THREAD

**Issue by jkantr** [microsoft/TypeScript#28853]
**TypeScript Version:**  3.3.0-dev.20181204

**Search Terms:** checkjs allowjs breaks intellisense code completion

**Code**
Without `checkJs` turned on

![](https://i.imgur.com/40e4rj6.gif)

With `checkJs` turned on

![](https://i.imgur.com/pVmUzwk.gif)

**Expected behavior:** With or without `checkJs` being on, intellisense should otherwise be able to infer the same code types for completion, even if a module being required doesn't have a typings file or module definition.

**Actual behavior:**
*All intellisense / code completion is completely lost* when `checkJs` is turned on but a required module doesn't have declarations.

After trying to find some guidance on the Gitter, I was told to lodge this here. By "`checkJs`" turned on, I mean here is my `.tsconfig`:
```json
{
    "compilerOptions": {
        "outDir": "./built",
        "allowJs": true,
        "target": "es2018",
        "checkJs": true,
        "module": "commonjs",
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true
    }
}
```

**Comment by DanielRosenwasser** [comment]
Do you have a self-contained reproduction here at all?

**Comment by jkantr** [comment]
@DanielRosenwasser sorry, I should have done this initially, here's a repo (of sorts...):

https://github.com/jkantr/ts-checkjs-intellisense-repro

Just clone, `npm install`, and then open index.js and follow the 2 commented lines of instructions.

This isn't quite a "minimal" case as it uses the real-world lib that i encountered the issue with. But the repro itself is minimal. Let me know if this is "good enough"... otherwise I'll have to figure out how to create a minimal example of what the library is doing.

**Comment by sandersn** [comment]
@jkantr I can't repro this with your provided repo on typescript@next. I get no completions regardless of `checkJs`' setting. Do you still observe this difference between checkJs on and off?

Adding `"maxNodeModuleJsDepth": 5` does make things work; perhaps the problem is that `@node-sc2` has a d.ts but it isn't complete so you often want to reference the .js files directly, even though they are nested deeply.

**Comment by jkantr** [comment]
@sandersn Thanks for your reply. So I *do* still observe the difference, but also, setting `"maxNodeModuleJsDepth"` fixes the behavior for me locally. So I'm not sure what to think really.

I was curious about your saying you did not get completions.. so I tried it again by cloning the repo to a fresh directory. I initially experienced the same thing! What I realized is, the `ctrl+space` method of trying to force a completion list *apparently* doesn't work if the engine hasn't already attempted to resolve a symbol. So once I started typing `A` it came back with `ARMORY` and the rest of the list. After that, `ctrl+space` went back to working as usual.

The other thing I noticed is that, yes, this (somewhat.. ahem, obscure) setting of `maxNodeModuleJsDepth` *does* fix my problem, even with `checkJs` on. So I'll leave this in your hands whether to close or research further.

To me, it's still a bug that I can't get the same completions I would have otherwise, with the same JS code, and the only difference being typescript is in `checkJs` mode. However, the module depth settings seems to do the trick... so I guess as a workaround it's good enough for me.

**Comment by sandersn** [comment]
I managed to repro this, but it was `allowJs` that made the difference, not `checkJs` and not having . Here are the two tsconfigs I used:

Succeeds:
```
{
    "compilerOptions": {
        "outDir": "./built",
        "target": "es2018",
        "allowJs": false,
        "checkJs": false,
        "maxNodeModuleJsDepth": 0,
        "module": "commonjs",
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true
    }
}
```

Fails:
```
{
    "compilerOptions": {
        "outDir": "./built",
        "target": "es2018",
        "allowJs": true,
        "checkJs": false,
        "maxNodeModuleJsDepth": 0,
        "module": "commonjs",
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true
    }
}
```

I'll try to shave down this repro and create a fourslash test case to isolate the bug.

(`maxNodeModuleJsDepth` is a flag that *could* be turned into a feature with some additional work, but right now it's mainly useful to give as a workaround.)

**Comment by sandersn** [comment]
Oh I see now.. So, here's the problem. It's not the types of `@node-sc2`. It's whether the tsconfig applies to your source file `index.js` or not. If it *does* (`"allowJs": true`), then the tsconfig settings are used, which sets `"maxNodeModuleJsDepth": 0`. That means only the typescript types for `@node-sc2` are available, and those are incomplete. There are definitely no types for `@node-sc2/core/constants/unit-type`.

However, if `"allowJs": false` then `index.js` isn't part of the compilation. Instead the language service scoops it into an "inferred project", which is everything that isn't part of a tsconfigured project. For javascript files, this inferred project happens to have settings that allow getting completions from `unit-type.js`. Here's some relevant code from src/server/project.ts:

```ts
    /**
     * If a file is opened and no tsconfig (or jsconfig) is found,
     * the file and its imports/references are put into an InferredProject.
     */
    export class InferredProject extends Project {
        // ..........
        private _isJsInferredProject = false;
        // .......
        setCompilerOptions(options?: CompilerOptions) {
            // ......
            const newOptions = cloneCompilerOptions(options || this.getCompilationSettings());
            if (this._isJsInferredProject && typeof newOptions.maxNodeModuleJsDepth !== "number") {
                newOptions.maxNodeModuleJsDepth = 2;
            }
```

It sounds like you want `index.js` to be part of your compilation, though, so this is not a code path you want to take. You can instead:

1. Copy the maxNodeModuleJsDepth setting from the inferred project.
2. Contribute to node-sc2's types so that it correctly includes unit-types.

Typescript does a bad job of telling you what project (if any) a file is part of. We have some ideas of how to improve that, but nothing concrete yet. For now it's a design limitation.
