### ISSUE TITLE
Intersection type disrupts generic inference

### ISSUE THREAD

**Issue by alexfoxgill** [Microsoft/TypeScript#28861]
**TypeScript Version:**  3.0.3 and 3.2.1 (playground)

**Search Terms:**
generic infer intersection

**Code**

```ts
type SomeType = { }

type Foo<A> = SomeType & { }
interface Bar<A> extends SomeType { }
type FooBar<A> = Foo<A> | Bar<A>

type InferA<T> = T extends FooBar<infer A> ? A : never

type FooA = InferA<Foo<number>> // {}
type BarA = InferA<Bar<number>> // number
```

**Expected behavior:**
`FooA` should have the type `number`, like `BarA` does

**Actual behavior:**
`FooA` has the type `{}`

**Playground Link:** 
http://www.typescriptlang.org/play/#src=type%20SomeType%20%3D%20%7B%20%7D%0D%0A%0D%0Atype%20Foo%3CA%3E%20%3D%20SomeType%20%26%20%7B%20%7D%0D%0Ainterface%20Bar%3CA%3E%20extends%20SomeType%20%7B%20%7D%0D%0Atype%20FooBar%3CA%3E%20%3D%20Foo%3CA%3E%20%7C%20Bar%3CA%3E%0D%0A%0D%0Atype%20InferA%3CT%3E%20%3D%20T%20extends%20FooBar%3Cinfer%20A%3E%20%3F%20A%20%3A%20never%0D%0A%0D%0Atype%20FooA%20%3D%20InferA%3CFoo%3Cnumber%3E%3E%20%2F%2F%20%7B%7D%0D%0Atype%20BarA%20%3D%20InferA%3CBar%3Cnumber%3E%3E%20%2F%2F%20number

**Related Issues:** 
Could not find any

**Comment by jack-williams** [comment]
The issue here is the type alias. A generic type alias is basically just a way to substitute something for `A` in the body; I don't believe there is any semantic notion of a 'type application'. As your alias body does not mention `A` the variable evaporates immediately. Interfaces are _slightly_ different, which is why `Bar` works. If you rewrite `Foo` with an interface you get the right thing:

```ts
type SomeType = { }

type Foo<A> = SomeType & R<A>;
interface R<A> {}

interface Bar<A> extends SomeType { }
type FooBar<A> = Foo<A> | Bar<A>

type InferA<T> = T extends FooBar<infer A> ? A : never

type FooA = InferA<Foo<number>> // number
type BarA = InferA<Bar<number>> // number
```

I'll include this link to the [FAQ](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-type-inference-work-on-this-interface-interface-foot---). Combining inference with generics that do not appear in the structure of types is probably going to lead to a suboptimal experience because of structural typing.

**Comment by alexfoxgill** [comment]
perhaps the strange thing then is that the type is preserved without the intersection?:

```typescript
type SomeType = { }

type Foo<A> = { }
interface Bar<A> extends SomeType { }
type FooBar<A> = Foo<A> | Bar<A>

type InferA<T> = T extends FooBar<infer A> ? A : never

type FooA = InferA<Foo<number>> // number
```

http://www.typescriptlang.org/play/#src=type%20SomeType%20%3D%20%7B%20%7D%0D%0A%0D%0Atype%20Foo%3CA%3E%20%3D%20%7B%20%7D%0D%0Ainterface%20Bar%3CA%3E%20extends%20SomeType%20%7B%20%7D%0D%0Atype%20FooBar%3CA%3E%20%3D%20Foo%3CA%3E%20%7C%20Bar%3CA%3E%0D%0A%0D%0Atype%20InferA%3CT%3E%20%3D%20T%20extends%20FooBar%3Cinfer%20A%3E%20%3F%20A%20%3A%20never%0D%0A%0D%0Atype%20FooA%20%3D%20InferA%3CFoo%3Cnumber%3E%3E%20%2F%2F%20number
