### ISSUE TITLE
getBaseTypeOfLiteralType(enumWithSingleMember) returns EnumLiteral type

### ISSUE THREAD

**Issue by mprobst** [microsoft/TypeScript#28869]
**TypeScript Version:**  3.2.1

**Search Terms:** getBaseTypeOfLiteralType

**Code**

```ts
// code
enum SingleValueEnum { A }
```

```ts
// API usage
const p = ts.createProgram({rootNames: ['f.ts'], options: {}});
const enumDecl = /* retrieve from source file */;
const tc = p.getTypeChecker();
const lt = tc.getTypeAtLocation(enumDecl); // returns an EnumLiteral type
const bt = tc.getBaseTypeOfLiteralType(lt); // still returns an EnumLiteral type!
console.error(lt === bt); // true
```

**Expected behavior:**

getBaseTypeOfLiteralType should return the type corresponding to `SingleValueEnum`, with `symbol.name === 'SingleValueEnum'`.

**Actual behavior:**

Returns the type corresponding to `SingleValueEnum.A`, i.e. the `EnumLiteral` type for the single member.

**Comment by weswigham** [comment]
AFAIK this is because we have code in place that marks the base type of a single-element enum as just the type of the single element.

**Comment by ahejlsberg** [comment]
This is by design. An enum type is simply a union of the enum member unit types introduced by the enum. For the declaration

```ts
const enum E { A, B, C }
```

we associate the type alias `E` with the union type `E.A | E.B | E.C`. But since a union of a single type is simply the type itself, we effectively have two names for a single member enum type. That's what you're observing.
