### ISSUE TITLE
Generic constraint incorrectly tagging valid value as invalid

### ISSUE THREAD

**Issue by JohnyDays** [Microsoft/TypeScript#28864]
**TypeScript Version:**  3.3.0-dev.20181205 and 3.1.3

**Search Terms:**
generic, generic constraint, "Argument of type is not assignable to parameter of type"
**Code**

```ts
type WrongType<RecordType extends { id: number }> = {
    getThing: (arg: RecordType) => any
}

function foo<RecordType extends { id: number }>(arg: WrongType<RecordType>) {
    arg.getThing({ id: 2 }) // Shouldn't error
}
```
also tried with an explicit cast, same error
```ts
type HasId = {
    id: number
}
type WrongType<RecordType extends HasId> = {
    getThing: (arg: RecordType) => any
}

function foo<RecordType extends HasId>(arg: WrongType<RecordType>) {
    arg.getThing({ id: 2 } as HasId) // Shouldn't error
}
```

**Expected behavior:**
No error
**Actual behavior:**
Did error with `Argument of type '{ id: number; }' is not assignable to parameter of type 'RecordType'.`
**Playground Link:** 
https://www.typescriptlang.org/play/index.html#src=type%20WrongType%3CRecordType%20extends%20%7B%20id%3A%20number%20%7D%3E%20%3D%20%7B%0D%0A%20%20%20%20getThing%3A%20(arg%3A%20RecordType)%20%3D%3E%20any%0D%0A%7D%0D%0A%0D%0Afunction%20foo%3CRecordType%20extends%20%7B%20id%3A%20number%20%7D%3E(arg%3A%20WrongType%3CRecordType%3E)%20%7B%0D%0A%20%20%20%20arg.getThing(%7B%20id%3A%202%20%7D)%20%2F%2F%20Shouldn't%20error%0D%0A%7D

**Comment by j-oliveras** [comment]
Compiler has reason: `getThing` expects an argument that extend `{ id: number }`, but can have more properties than that (depends on en the current RecordType).

For example (based on your second code):
```ts
type HasId = {
    id: number
}

type WrongType<RecordType extends HasId> = {
    getThing: (arg: RecordType) => any
}

function foo<RecordType extends HasId>(arg: WrongType<RecordType>) {
    arg.getThing({ id: 2 } as HasId) // Shouldn't error
}

type HasIdName = {
    id: number,
    name: string,
}

foo<HasIdName>({
    getThing: arg => arg // getThing argument expects and id an name
});
```
That code that calls your `foo` function with type `HasIdName`, but your `foo` implementation calling `getThing` is not valid because the type `HasIdName` expects an `id` and `name` but your code only provide an `id`.

[Playground](https://www.typescriptlang.org/play/index.html#src=type%20HasId%20%3D%20%7B%0D%0A%20%20%20%20id%3A%20number%0D%0A%7D%0D%0A%0D%0Atype%20WrongType%3CRecordType%20extends%20HasId%3E%20%3D%20%7B%0D%0A%20%20%20%20getThing%3A%20(arg%3A%20RecordType)%20%3D%3E%20any%0D%0A%7D%0D%0A%0D%0Afunction%20foo%3CRecordType%20extends%20HasId%3E(arg%3A%20WrongType%3CRecordType%3E)%20%7B%0D%0A%20%20%20%20arg.getThing(%7B%20id%3A%202%20%7D%20as%20HasId)%20%2F%2F%20Shouldn't%20error%0D%0A%7D%0D%0A%0D%0Atype%20HasIdName%20%3D%20%7B%0D%0A%20%20%20%20id%3A%20number%2C%0D%0A%20%20%20%20name%3A%20string%2C%0D%0A%7D%0D%0A%0D%0Afoo%3CHasIdName%3E(%7B%0D%0A%20%20%20%20getThing%3A%20arg%20%3D%3E%20arg%20%2F%2F%20getThing%20argument%20expects%20and%20id%20an%20name%0D%0A%7D)%3B%0D%0A).

**Comment by JohnyDays** [comment]
Hadn't considered this, thanks. 
What I actually want is to declare a type that can't be extended from outside which would not cause this ambiguity.
I guess #26349 will bring this, I'll wait for that.
Thanks again.

**Comment by JohnyDays** [comment]
I just tried with an explicit cast to the generic RecordType and it worked. 
I guess the compiler hands over the responsibility to me if I narrow the type
