### ISSUE TITLE
JSDoc - Add support for @return {this}

### ISSUE THREAD

**Issue by NemoStein** [Microsoft/TypeScript#28880]
I acknowledge that this feature was dismissed by JSDoc, but I'd like to ask VSCode could support this: https://github.com/jsdoc3/jsdoc/issues/991

Basically, if you have a method that returns `this` the intellisense doesn't tell me that the return type is the same as the class itself.

**Comment by weswigham** [comment]
We already do:
```ts
// @ts-check

class Foo {
    /**
     * @returns {this}
     */
    foo() {
        return null; // stub impl to prove we pickup the type from the doc comment
    }
}

class Bar extends Foo {
    method() {}
}

new Bar().foo().foo().method();
```

we only allow `this` references within classes, though, not object literals or function psuedo classes right now.

**Comment by NemoStein** [comment]
I was testing in a `html` file (inside `<script>`) and the highlight wasn't behaving the same that it is now, in a `js` file.
Nonetheless, I didn't think it through or explained my real use case.
Consider this:
```javascript
class SuperClass
{
	/**
	 * @param {*} element 
	 * @returns {this} This doesn't work because the method is static.
	 */
	static build(element)
	{
		return Object.setPrototypeOf(element, this.prototype) // This DOES work, however!
	}
}

class SubClass extends SuperClass
{
	/**
	 * @returns {String}
	 */
	print()
	{
		return 'Hello world'
	}
}

const test = SubClass.build({})

console.log(test instanceof SuperClass)  // true
console.log(test instanceof SubClass)    // true
console.log(test.print())                // "Hello world"
```

Here are some screenshots of what is displayed in vscode:
![image](https://user-images.githubusercontent.com/2738812/49620091-9f760780-f9a6-11e8-9e33-42584e2e1ec1.png)
![image](https://user-images.githubusercontent.com/2738812/49620118-b9174f00-f9a6-11e8-9e36-4d3aa65ceb88.png)
![image](https://user-images.githubusercontent.com/2738812/49620127-c92f2e80-f9a6-11e8-8e9e-c1cb04a40917.png)
![image](https://user-images.githubusercontent.com/2738812/49620144-dc41fe80-f9a6-11e8-8e60-f9ac2fdc6cf2.png)
![image](https://user-images.githubusercontent.com/2738812/49620173-ed8b0b00-f9a6-11e8-95c4-fae62ff32a79.png)


I expected to have intellisense telling me that `test` is a `SubClass` and `test.print` to return a `String`.
Is it possible?

**Comment by weswigham** [comment]
Yeah, note the error on the first one. There's no `this` allowed there because that's not an instance method (and we don't consider that static `this` as having a real type, since it often isn't substitutable).

**Comment by DanielRosenwasser** [comment]
I'd say you want #5863.

**Comment by NemoStein** [comment]
Thanks, @DanielRosenwasser, that seems to be exactly the same problem.

**Comment by demosofa** [comment]
I have problem when I want to created an export type of a callback that I declared in parent class. I created a @callback in the parent class and create @typedef outside of that class to make the @callback global. In child class, I was be able to get the type from import() but the @returns {this} from the @callback still refered to parent class instead of child class. This problem made code completion from vscode not show any functions from child class but parent class.

**Comment by demosofa** [comment]
> We already do:
> 
> ```ts
> // @ts-check
> 
> class Foo {
>     /**
>      * @returns {this}
>      */
>     foo() {
>         return null; // stub impl to prove we pickup the type from the doc comment
>     }
> }
> 
> class Bar extends Foo {
>     method() {}
> }
> 
> new Bar().foo().foo().method();
> ```
> 
> we only allow `this` references within classes, though, not object literals or function psuedo classes right now.

I have a problem when I want to create an export callback type that I have declared in the parent class. I created @callback in the parent class and to make that @callback exported, I created @typedef outside that class. In the subclass, I can get the type from import() but the @returns {this} from @callback still calls the parent class instead of the child class. This issue causes the code completion from Vscode to not show any functionality from the child class but the parent class.
