### ISSUE TITLE
Class name cannot be Object

### ISSUE THREAD

**Issue by rjamesnw** [microsoft/TypeScript#28912]
Please fill in the *entire* template below.

**TypeScript Version:**  3.1

**Search Terms:**
class name cannot be Object

**Expected behavior:**
All browsers DO NOT generate errors for this line, and it is valid:
var c = class Object {}

**Actual behavior:**
Compiler error, preventing my large project from compiling with no way to turn it off.  This was working perfectly fine for almost 2 years until I upgraded to v3.1.

**Playground Link:** 
https://www.typescriptlang.org/play/index.html#src=namespace%20Test%20%7B%0D%0A%20%20%20%20export%20class%20Object%20%7B%0D%0A%20%20%20%20%20%20%20%20x%3A%20number%3B%0D%0A%20%20%20%20%7D%0D%0A%7D

**Comment by weswigham** [comment]
We forbid this because we use the global `Object` in our helpers and expect it to be available, and so throw when people attempt to overwrite it.

**Comment by weswigham** [comment]
See https://github.com/Microsoft/TypeScript/issues/17494 for details

**Comment by rjamesnw** [comment]
Like everything else, that should be an option.  There are other things that TS emits as well, and you already have options to allow others to implement their own. My object class actually connects back to the original one so everything was working; now it's not.  You should not force this on nested namespaces. In the root perhaps, yes, but not many levels deep, otherwise you are saying that `x.y.Object` is not allowed as a class, but it is valid JS!!! (in every browser)

**Comment by weswigham** [comment]
The error is there to mark that the emit is broken. Changing the emit to handle a used `Object` name was previously quite difficult (though now wouldn't be too bad in our new pipeline, maybe - would still be extensive, though). The error is there in lieu of changing the emit to be much more complicated because we've had few requests to support it over time (and more about how previous to TS 2.2 we silently broke code).
