### ISSUE TITLE
Date type not work properly

### ISSUE THREAD

**Issue by alex2sorin** [Microsoft/TypeScript#28944]
`var x = new Date(2018, 12, 1);
console.log(x)`

you will see that typescript generate 1 Jan 2019 🥇

**Comment by mfulton26** [comment]
I see that MDN uses [`monthIndex`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#Parameters) instead of `month` where applicable. It may help people in the future to use `monthIndex: number` instead of simply `month: number` (assuming they pay any attention to the argument names).
