### ISSUE TITLE
Quick fix for 'experimentalDecorators' error

### ISSUE THREAD

**Issue by roblourens** [Microsoft/TypeScript#29035]
- Open someone's JS project
- See errors on all methods using decorators, that say "Set the 'experimentalDecorators' option to remove this warning"
- But I don't know what that means or where to set it.
 
Seems like a good opportunity for a quick fix?

It could detect whether you have a tsconfig or jsconfig already and offer to set them there. Or it could create a jsconfig with that setting. Or it could set the implicit config setting that fixes this. Do any of those make sense?

**Comment by mjbvz** [comment]
* The error message should probably say that this must be set in the `tsconfig` or `jsconfig`: `"Set the 'experimentalDecorators' option in your `tsconfig` or `jsconfig` to remove this warning"`

* If we do have a `jsconfig` or `tsconfig`, having a quick fix that add `experimentalDecorators` the option would be helpful.

* If we don't have a jsconfig or tsconfig, the best fix is probably for users to set `"javascript.implicitProjectConfig.experimentalDecorators": true` in VS Code. Since the error comes from TS, I'm not sure how we can hint at that

**Comment by DanielRosenwasser** [comment]
Ideally this idea would be maximally useful for the next 8 months, after which point nobody would get the error message in the future. 😉

**Comment by amaksimovich2** [comment]
@DanielRosenwasser Can I try to implement this one?

**Comment by DanielRosenwasser** [comment]
Sure!

**Comment by amaksimovich2** [comment]
Can you give me some advices?) It's my first meet with quick fixes functionality

**Comment by amaksimovich2** [comment]
@DanielRosenwasser As I understand `"javascript.implicitProjectConfig.experimentalDecorators": true` this part of  VSCode config we can't add from code? And also can you explain me how basically happens review  of created PR?
