### ISSUE TITLE
Question: What is BindingPattern?

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#2905]
I'm trying to parse some typescript code for a project of mine.

I'm stuck at figuring out what BindingPattern interface represent in TS code?
```typescript
export interface VariableDeclaration extends Declaration {
    parent?: VariableDeclarationList;
    name: Identifier | BindingPattern;  // Declared variable name  <- What is BindingPattern?
    type?: TypeNode;                    // Optional type annotation
    initializer?: Expression;           // Optional initializer
}
```
I didn't get any smarter by looking at `BindingElement` interface either.

**Comment by DanielRosenwasser** [comment]
In ES6, you can *destructure* values on the right hand side of an assignment so that you don't have to individually extract their values as separate variables.

For instance:

```TypeScript
let x = { a: 100, b: [1,2,3], c: 200 };
let { a, [n1, n2, n3], c: w } = x;
```

The above creates local variables `a`, `n1`, `n2`, `n3`, and `w`.

For a better explanation and more examples, see Mozilla's page on [Destructuring assignments](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)

Also, see the [ES6 draft spec grammar for it](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-destructuring-binding-patterns). Here's a reduced portion of it:

> *BindingPattern*:
&nbsp;&nbsp;*ObjectBindingPattern*
&nbsp;&nbsp;*ArrayBindingPattern*

> ObjectBindingPattern:
&nbsp;&nbsp;`{` `}`
&nbsp;&nbsp;`{` *BindingPropertyList* `}`
&nbsp;&nbsp;`{` *BindingPropertyList* `,` `}`

> ArrayBindingPattern:
&nbsp;&nbsp;`[` *Elision*<sub>opt</sub> *BindingRestElement* `]`
&nbsp;&nbsp;`[` *BindingElementList* `]`
&nbsp;&nbsp;`[` *BindingElementList* `,` *Elision*<sub>opt</sub> *BindingRestElement*<sub>opt</sub> `]`

**Comment by tinganho** [comment]
@DanielRosenwasser thanks!
