### ISSUE TITLE
How to define generics on prop key definition?

### ISSUE THREAD

**Issue by samuelcastro** [microsoft/TypeScript#29054]
For example I want to define generic on which new key definition like:
```
export interface ISelectors {
  <T extends {}>[key: string]: ISelector<T>
}
```

And then I'd like to:

```
selectors: {
    values1: <IMyTypeOne[]>getValues1,
    values2: <IMyTypeTwo>getValues2,
  },
```

But I can't find a way to do so.

**Comment by jack-williams** [comment]
I would suggest trying Stackoverflow first, as the issue tracker is really for bugs and language design, rather than asking questions like this.

I tried coming up with an answer but I'm struggling to really understand your use-case. Could you provide a more complete example? What is the definition of `ISelector`?

I think mapped types _might_ be what you want, but I can't say for sure based on the snippet you have posted.
