### ISSUE TITLE
Non-matching nested inferred type defaults to constraint and passes conditional

### ISSUE THREAD

**Issue by SLaks** [microsoft/TypeScript#29089]
**TypeScript Version:**  3.2.1-insiders.20181128

**Search Terms:** nested conditional infer

**Code**

```ts
class Marker<T> {
  private noStructuralTyping!: T;
}
class MyConfig<T1, TMark extends {}> {}

declare const withMarker: MyConfig<'a', Marker<'A'>>;
declare const withoutMarker: MyConfig<'q', never>;

type UnionToIntersection<U> =
    (U extends never ? never : (k: U) => void) extends((k: infer I) => void) ?
    I :
    never;

type Overloader<T> =
    T extends MyConfig<infer T1, Marker<infer TMark>>? (a: TMark) => T1 : never;
declare let f:
    UnionToIntersection<Overloader<typeof withoutMarker|typeof withMarker>>;

f(2);  // This should error
```

**Expected behavior:**

`Overloader<typeof withoutMarker|typeof withMarker>` should be `(a: "A") => "a"`; it should omit `q` / `withoutMarker` entirely.

Because `withoutMarker`'s `TMark` parameter doesn't extend `Marker<anything>`, it should collapse to `never` in the second branch of the conditional.

**Actual behavior:**

`withoutMarker`'s `TMark` is inferred as `{}`, breaking the overloaded function.

**Playground Link:** https://www.typescriptlang.org/play/#src=class%20Marker%3CT%3E%20%7B%0A%20%20private%20noStructuralTyping!%3A%20T%3B%0A%7D%0Aclass%20MyConfig%3CT1%2C%20TMark%20extends%20%7B%7D%3E%20%7B%7D%0A%0Adeclare%20const%20withMarker%3A%20MyConfig%3C'a'%2C%20Marker%3C'A'%3E%3E%3B%0Adeclare%20const%20withoutMarker%3A%20MyConfig%3C'q'%2C%20never%3E%3B%0A%0Atype%20UnionToIntersection%3CU%3E%20%3D%0A%20%20%20%20(U%20extends%20never%20%3F%20never%20%3A%20(k%3A%20U)%20%3D%3E%20void)%20extends((k%3A%20infer%20I)%20%3D%3E%20void)%20%3F%0A%20%20%20%20I%20%3A%0A%20%20%20%20never%3B%0A%0Atype%20Overloader%3CT%3E%20%3D%0A%20%20%20%20T%20extends%20MyConfig%3Cinfer%20T1%2C%20Marker%3Cinfer%20TMark%3E%3E%3F%20(a%3A%20TMark)%20%3D%3E%20T1%20%3A%20never%3B%0Adeclare%20let%20f%3A%0A%20%20%20%20UnionToIntersection%3COverloader%3Ctypeof%20withoutMarker%7Ctypeof%20withMarker%3E%3E%3B%0A%0Af(2)%3B%0A

**Comment by SLaks** [comment]
Interestingly, this doesn't seem to happen if the conditional branch isn't a function type.

**Comment by Nathan-Fenner** [comment]
Things are working as intended here.

This case can be simplified a lot. Consider:

```ts
interface Thing<T> {
    x: T;
}

type TwoLayers<S> = S extends Thing<Thing<infer A>> ? A : "no";

type Input = Thing<never>;

type Out = TwoLayers<Input>;
```

You were expecting `Out` to become `"no"`, since you assumed that `Thing<never>` doesn't match `Thing<Thing<?>>`.

However, it actually *does* match and returns `{}`.

The problem is that it *does* match: `never` is a subtype of all other subtypes. The variable `A` in this case is inferred to be `{}` (which is the closest thing TS had to a top-type way-back-when).

The rest of the behavior of your types are predictable once you work this out.

You almost certainly mean to use `unknown` instead of `never` to replace your `Marker<...>` type.
