### ISSUE TITLE
Problem of Initialization Process for Subclass Members

### ISSUE THREAD

**Issue by imfox** [microsoft/TypeScript#29113]
**TypeScript Version:**  3.2.2

**Search Terms:** method member class subclass constructor

**Code**

```ts
abstract class GameObject {
    constructor(data) {
        this.update(data);
    }
    abstract update(data);
}

class Role extends GameObject {
    name = "";
    update(data) {
        this.name = data.name;
    }
}

let role = new Role({ name: "fox" });
console.log(role.name);
```

**Expected behavior:**
print 'fox' 
**Actual behavior:**
print '' , After compiling into JS , The order of initialization may be problematic 
**Playground Link:**  [https://www.typescriptlang.org/play](https://www.typescriptlang.org/play/#src=abstract%20class%20GameObject%20%7B%0D%0A%20%20%20%20constructor(data)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.update(data)%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20abstract%20update(data)%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Role%20extends%20GameObject%20%7B%0D%0A%20%20%20%20name%20%3D%20%22%22%3B%0D%0A%20%20%20%20update(data)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.name%20%3D%20data.name%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Alet%20role%20%3D%20new%20Role(%7B%20name%3A%20%22fox%22%20%7D)%3B%0D%0Aconsole.log(role.name)%3B%0D%0A)
**Related Issues:**

**Comment by j-oliveras** [comment]
Workaround:
```ts
abstract class GameObject {
    constructor(data) {
        this.update(data);
    }
    abstract update(data);
}

class Role extends GameObject {
    name: string; // don't set initial value here
    constructor(data) {
        super(data)
        this.name = this.name || ""; // initialize if is not already initialized
    }
    update(data) {
        this.name = data.name;
    }
}

let role = new Role({ name: "fox" });
console.log(role.name);
```
[Playground](https://www.typescriptlang.org/play/#src=abstract%20class%20GameObject%20%7B%0D%0A%20%20%20%20constructor(data)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.update(data)%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20abstract%20update(data)%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Role%20extends%20GameObject%20%7B%0D%0A%20%20%20%20name%3A%20string%3B%20%2F%2F%20don't%20set%20initial%20value%20here%0D%0A%20%20%20%20constructor(data)%20%7B%0D%0A%20%20%20%20%20%20%20%20super(data)%0D%0A%20%20%20%20%20%20%20%20this.name%20%3D%20this.name%20%7C%7C%20%22%22%3B%20%2F%2F%20initialize%20if%20is%20not%20already%20initialized%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20update(data)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.name%20%3D%20data.name%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Alet%20role%20%3D%20new%20Role(%7B%20name%3A%20%22fox%22%20%7D)%3B%0D%0Aconsole.log(role.name)%3B).

Probably this is the expected behaviour, someone on the team can answer it.
