### ISSUE TITLE
Cannot use outFile with umd format

### ISSUE THREAD

**Issue by def14nt** [Microsoft/TypeScript#29154]
**TypeScript Version:**  3.2.2

**Search Terms:**

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
// tsconfig.json
{ 
    "compilerOptions": {
        "outFile": "../dist/bundle.js",
        "module": "umd"
     } 
}
```

**Expected behavior:**
TypeScript lets me just compile it into one UMD file for the browser, which would eliminate my current Rollup & Rollup-Plugin-TypeScript workflow.

**Actual behavior:**
The compiler forces me to use AMD/SystemJS.

**Comment by weswigham** [comment]
Duplicates #6380

**Comment by def14nt** [comment]
@weswigham Wow thats BS

**Comment by weswigham** [comment]
I mean, it boils down to that a chance (and thereby umd) single file output requires building a loading into the output. Webpack and friends already do this (in a very configurable way) and we didn't want to be in the bundling game, if possible. AMD and systemJS single file support exists because it's essentially just a concatenation of their multifile emit, same as non-module single-file emit.

**Comment by saschanaz** [comment]
Explicitly mentioning a workaround (using a bundler) through the error message may help to prevent users from being confused.
