### ISSUE TITLE
Why I use function generic parameters as the other type's generic has compile error?

### ISSUE THREAD

**Issue by linmodev** [Microsoft/TypeScript#29225]
**TypeScript Version:**  3.3.0-dev.20190101

**Search Terms:** Why I use function generic parameters as the other type's generic has compile error?

**Code**

```ts
function fn1<U extends UU, UU>() {

    type T03<T> = {
      action: T;
    };
    type T04<F extends FF, FF> = T03<F> extends T03<FF> ? number : string;

    let v2: T04<"aaa", string> = 222;
    let v3: T04<U, UU> = 78787;
  }
```

**Expected behavior:**

     expect v3' type is number

**Actual behavior:**

    Type '78787' is not assignable to type 'T04<U, UU>'.

**Playground Link:**  [Link](https://www.typescriptlang.org/play/index.html#src=function%20fn1%3CU%20extends%20UU%2C%20UU%3E()%20%7B%0D%0A%0D%0A%20%20%20%20type%20T03%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20%20%20action%3A%20T%3B%0D%0A%20%20%20%20%7D%3B%0D%0A%20%20%20%20type%20T04%3CF%20extends%20FF%2C%20FF%3E%20%3D%20T03%3CF%3E%20extends%20T03%3CFF%3E%20%3F%20number%20%3A%20string%3B%0D%0A%0D%0A%20%20%20%20let%20v2%3A%20T04%3C%22aaa%22%2C%20string%3E%20%3D%20222%3B%0D%0A%20%20%20%20let%20v3%3A%20T04%3CU%2C%20UU%3E%20%3D%2078787%3B%0D%0A%20%20%7D)

**Comment by fatcerberus** [comment]
> assignability does not imply definite assignability

I wasn’t even aware this distinction existed; I’m kind of curious now, what’s the difference?  (Preferably with examples)

**Comment by linmodev** [comment]
@jack-williams  @fatcerberus  I have a another piece.I think is a similar question.

```ts
export interface Action<T = any> {
  type: T;
}
export interface AnyAction extends Action {
  [extraProps: string]: any;
}
export type Reducer<S = any, A extends Action = AnyAction> = (
  state: S | undefined,
  action: A
) => S;
export type ReducersMapObject<S extends any= any, A extends Action = Action> = {
  [K in keyof S]: Reducer<S[K], A>
};


function assertShape<S extends any, A extends Action>(
  reducers: ReducersMapObject<S, A>
) {
  let reducerKeys = Object.keys(reducers);
  reducerKeys.forEach(key => {
    let reducer = reducers[key];
    const SET_AGE="set age haha"
    const action={
      type:SET_AGE 
    }
   // Argument of type '{ type: string; }' is not assignable to parameter of type 'A'.
    reducer({sf:"rewr"}, action);
  });
}
```

**Comment by jack-williams** [comment]
@linmodev That looks a different situation to me, which I think is ok. The type of `reducer` is parameterised by `A` which is not controlled by the callee, but the caller of the function. It seems right that the body of the function should not be able to assume the action takes a string type. This use of the function type-checks:
```ts
const a: (state: "a" | undefined, action: Action<number>) => "a" = () => "a";
assertShape<{ a: "a" }, Action<number>>({ a });
```

@fatcerberus 
This is from the code:
```ts
// Return trueType for a definitely true extends check. The definitely assignable relation excludes
// type variable constraints from consideration. Without the definitely assignable relation, the type
// type Foo<T extends { x: any }> = T extends { x: string } ? string : number
// would immediately resolve to 'string' instead of being deferred.
```

**Comment by linmodev** [comment]
@jack-williams But the compile error just show the second parameter of reducer's type is type A.How to resolve this?

**Comment by jack-williams** [comment]
@linmodev I'm not sure what your use-case is, so I don't know how to _fix_ the error. I believe the error message is correct; in the body of the function, the type `A` represents a fixed but unknown type, so it is not safe to assign to it using a concrete literal. The issue #29049 will produce a better error message though, which should help. Something like:

`'{ type: string; }' is assignable to the constraint of type 'A', but 'A' could be instantiated with a different subtype of constraint '{ type: any; }'.`

**Comment by linmodev** [comment]
@jack-williams Thanks ,Have read the issue ,I find the key point of this eventually. I will continually pay a attention on it

**Comment by ahejlsberg** [comment]
This is a design limitation. The algorithm we use to determine whether to defer resolution of a conditional type doesn't consider constraints of type variables. Specifically, for a conditional type `T extends U ? X : Y`,

* we resolve to `Y` when `T` is not assignable to `U` _considering all type parameters referenced in `T` and `U` related_ (i.e. `T` is definitely not assignable to `U`),
* otherwise we resolve to `X` when `T` is assignable to `U` _considering all type parameters referenced in `T` and `U` unrelated_ (i.e. `T` is definitely assignable to `U`),
* otherwise we defer resolution.

We use these rules because type parameters that appear unrelated, such as `T extends { a: string }` and `U extends { b: string }` might actually become related upon instantiation (e.g. when both are instantiated to `{ a: string, b: string }`). Even so, there are _some_ cases, such as type parameters constrained to other type parameters, where we could deduce that they can never be related, but we currently don't reason about those. For that reason we may sometimes be too conservative in deciding when to resolve conditional types.
