### ISSUE TITLE
Unexpected inference for 'reduce' on arrays of empty types

### ISSUE THREAD

**Issue by bluelovers** [Microsoft/TypeScript#29267]
**TypeScript Version:**  3.3.0-dev.201xxxxx

**Search Terms:**

**Code**

expected `ls` is `IRule[]`, but typescript think it is `IUserRule`

> Error: TS2740: Type missing following properties : length, pop, push, concat, and 28 more.

```ts
export type IRules = IRule[]
export type IUserRules = IUserRule[]

export interface IRule
{

}

export interface IUserRule
{

}

export function handleRules(rules: IUserRules, options?: IOptions): IRules
{
	//options = handleOptions(options);

	let ls = rules.reduce(function (ls: IRules, value)
	{
		return ls;
	}, [] as IRules);

	// Error: TS2740: Type 'IUserRule' is missing the following properties from type 'IRule[]': length, pop, push, concat, and 28 more.
	return ls;
}
```

**Expected behavior:**

> no error

**Actual behavior:**

> Error: TS2740: Type 'IUserRule' is missing the following properties from type 'IRule[]': length, pop, push, concat, and 28 more.

**Playground Link:** 

**Related Issues:** 

i think this isses not same as https://github.com/Microsoft/TypeScript/issues/29197

**Comment by DanielRosenwasser** [comment]
Here's a decent example that explains why this happens:

```ts
export interface Thing {
}

export function handleRules(rules: Thing[]): Thing[]
{
	let result = rules.reduce(function (ls, value)
	{
		return ls;
	}, [] as number[]);

	// Error: TS2740: Type 'Thing' is missing the following properties from type 'Thing[]': length, pop, push, concat, and 28 more.
	return result;
}
```

The problem is that `Thing` is an empty interface - almost *anything* is assignable to it. So given the fact that the following overload exists:

```ts
interface Array<T> {
    // ...
    reduce(callbackfn: (previousValue: T, currentValue: T, currentIndex: number, array: T[]) => T, initialValue: T): T;
}
```

then an `Array<Thing>` will have the method

```ts
interface Array<Thing> {
    // ...
    reduce(callbackfn: (previousValue: Thing, currentValue: Thing, currentIndex: number, array: T[]) => Thing, initialValue: Thing): Thing;
}
```

Notice that the type for `initialValue` is `Thing`, which anything is assignable to - `number[]`, `Thing[]`, whatever.

The solution is just make your interface non-empty.

By the way, as a side note, in the future it would be extremely helpful to give a more specific title (i.e. not just the error message) and a more minimal reproduction (i.e. fewer type aliases, less unused code), and clearer variable names (no duplication).
