### ISSUE TITLE
Type parameter cannot refine the other related type parameters

### ISSUE THREAD

**Issue by mmis1000** [microsoft/TypeScript#29276]
**TypeScript Version:**  3.2.2

**Search Terms:** type prarameter refine

**Code**

```ts
const state = {
  text: "",
  count: 0
};

type State = Readonly<typeof state>;

function isEqual<T extends string>(a: T, b: any): b is T {
    return a === b
}

const changeCount = <T extends keyof State, U extends State[T] = State[T]>(name: T, value: U) => {
    if (isEqual("text" as "text", name)) {
        const tyepT: State[T] = ""
        const tyepofName: State[typeof name] = ""

        state[name] = value // ❌
        state[name] = tyepT // ❌
        state[name] = tyepofName // ⭕
    }
};

changeCount("text", "") // ⭕
changeCount("count", 1) // ⭕
```

**Expected behavior:**
Calling the function automatically refine other parameter
`T` itself refined to `'text'`
The refinement also applied on the type parameter rely on `T`
`U` is now `extends string`
`value` is assignable to `state[name]`

**Actual behavior:**
⭕ Calling the function automatically refine other parameter
❌ `T` itself does not got refined to `'text'`, only `typeof name` does
❌ The refinement does not applied on the type parameter rely on `T` because `T` does not change
❌ `U` is still `'extends  Readonly<{ text: string; count1: number; count2: number; }>[T]'`
❌ `value` is not assignable to `state[name]`

**Playground Link:** 
[link](http://www.typescriptlang.org/play/#src=%0D%0Aconst%20state%20%3D%20%7B%0D%0A%20%20text%3A%20%22%22%2C%0D%0A%20%20count%3A%200%2C%0D%0A%7D%3B%0D%0A%0D%0Atype%20State%20%3D%20Readonly%3Ctypeof%20state%3E%3B%0D%0A%0D%0Afunction%20isEqual%3CT%20extends%20string%3E(a%3A%20T%2C%20b%3A%20any)%3A%20b%20is%20T%20%7B%0D%0A%20%20%20%20return%20a%20%3D%3D%3D%20b%0D%0A%7D%0D%0A%0D%0Aconst%20changeCount%20%3D%20%3CT%20extends%20keyof%20State%2C%20U%20extends%20State%5BT%5D%20%3D%20State%5BT%5D%3E(name%3A%20T%2C%20value%3A%20U)%20%3D%3E%20%7B%0D%0A%20%20%20%20if%20(isEqual(%22text%22%20as%20%22text%22%2C%20name))%20%7B%0D%0A%20%20%20%20%20%20%20%20const%20tyepT%3A%20State%5BT%5D%20%3D%20%22%22%0D%0A%20%20%20%20%20%20%20%20const%20tyepofName%3A%20State%5Btypeof%20name%5D%20%3D%20%22%22%0D%0A%0D%0A%20%20%20%20%20%20%20%20state%5Bname%5D%20%3D%20value%0D%0A%20%20%20%20%20%20%20%20state%5Bname%5D%20%3D%20tyepT%0D%0A%20%20%20%20%20%20%20%20state%5Bname%5D%20%3D%20tyepofName%0D%0A%20%20%20%20%7D%0D%0A%7D%3B%0D%0A%0D%0AchangeCount(%22text%22%2C%20%22%22)%0D%0AchangeCount(%22count%22%2C%201))
**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/4742 (not sure if it describes the exact same issue)

**Notes**
Although refinement on calling is useful enough in most case.
You still can't consume the type correctly in function body itself, which is quite annoying.

**Comment by jack-williams** [comment]
In general, narrowing a value of a generic type does not give enough proof to narrow the type itself. For example: I could call the function like so:
```ts
changeCount<"text" | "count">("text", 1);
```
Observing that `name` is equal to `text` tells us that `T` is related to `"text"`, but it does not give us enough information to say that `T` is _exactly_ `"string"`. For this reason, the first error is correct:
```ts
state[name] = value // error
```
The type of `value` could be number if someone picked an instantiation for `T` that was sufficiently wide, such as `"text" | "count"`.

The second error is raised also because, in general, type parameters cannot be narrowed. The type `State[T]` has to conservatively assume `T` is instantiated with the most general type `"text" | "count"`---the equality test is not sufficient to prove otherwise.

In this instance your type annotation is actually weakening the term, and removing the annotation removes the error. (Effectively you are going from `string | number`, to `string`.
```ts
if (isEqual("text" as "text", name)) {
    const typeT = "";
    state[name] = typeT; // ok
}
```

I will cynically take this opportunity to plug my suggestion of _uniform types_ #28430. In most cases the caller would _never_ want to instantiate the call with a union type and so `T` is always exactly `"text"` or `"count"`. Under these constraints the compiler could potentially do more.

**Comment by mmis1000** [comment]
However this is a very common pattern in javascript, a function accept a key and corresponds value, and operate on object base on the key.
This problem actually makes typing these function without any not possible at all.
