### ISSUE TITLE
Extract<keyof T, string> is not assignable to K extends Extract<keyof T, string> when used as K[]

### ISSUE THREAD

**Issue by manigandham** [Microsoft/TypeScript#29295]
**TypeScript Version:**  3.3.0-dev.20190105

**Search Terms:** keyof string array, K extends Extract<keyof T, string>

**Code**

Using a generic `K extends Extract<keyof T, string>` generic definition does not work:

```ts
function copyAllExcept<T, K extends Extract<keyof T, string>>(target: any, source: T, skip: K[]) {
    for (const key in source) {
        if (source[key] != null && !skip.includes(key)) {
            target[key] = source[key];
        }
    }
}
```
Error at the `!skip.includes(key)` part:

Argument of type 'Extract<keyof T, string>' is not assignable to parameter of type 'K'.
  Type 'string & keyof T' is not assignable to type 'K'.
    Type 'string' is not assignable to type 'K'.
      Type 'string' is not assignable to type 'K'.

Using `Array<Extract<keyof T, string>>` directly as the argument definition does work though:

```ts
function copyAllExcept<T>(target: any, source: T, skip: Array<Extract<keyof T, string>>) {
    for (const key in source) {
        if (source[key] != null && !skip.includes(key)) {
            target[key] = source[key];
        }
    }
}
```

**Comment by weswigham** [comment]
You don't need the `K` type parameter - you're overconstraining your input a bit:
```ts
function copyAllExcept<T>(target: any, source: T, skip: (Extract<keyof T, string>)[]) {
  for (const key in source) {
      if (source[key] != null && !skip.includes(key)) {
          target[key] = source[key];
      }
  }
}
```
and that seems to work fine.

Now, the type parameter doesn't work because you're saying that you're searching through a `K[]` for a `Extract<keyof T, string>` - while `K extends Extract<keyof T, string>`, `Extract<keyof T, string>` is a less specific type and so doesn't satisfy the argument type. `includes` is going to be OK with this at runtime anyway - the parameter type is actually meaningless, you define its type as `unknown` and be fine, which is what's unfortunate here - the `lib` definition of `Array.prototype.includes` constrains its argument to the type of only things in the array - meaning you can't pass less specific types that might still be the same as things in the array.

**Comment by manigandham** [comment]
Ah ok, didn't realize that the `extends` keyword made it more specific. Seems like it would fit since they are both from a limited set of strings coming from `keyof` but the direct argument definition works.

Thanks for the info.
