### ISSUE TITLE
Specify (absolute) path for library projects

### ISSUE THREAD

**Issue by andrewvarga** [Microsoft/TypeScript#293]
I'm moving this issue here from codeplex:
https://typescript.codeplex.com/workitem/1414

This feature would help to use "library projects" in a way that you only have to specify the actual path once (eg. with a compiler flag).

I'd love to see this implemented in the official compiler. I think it's small work and adds huge value.
I can have a try at adding this but I'd value some guidelines on how to edit the compiler and how it would make it's way to be part of the official compiler.

**Comment by mconner** [comment]
Coming from a Java background, this doesn't look much different than the java compiler dealing with classes and packages. In Java, you define classes in a packages (e.g.:  in com.foo.bar,SomeClass) and the compiler finds classes referenced by Java code relative to the classpath:  `javac  -classpath c:\someproject\classes  c:\anotherproject\MyClass1.java ....`
So if `MyClass1` imports `com.foo.bar.SomeClass`, the compiler will look for that class in file `c:\someproject\classes\com\foo\bar\Person.class`  and anywhere else you put on the classpath.

Similarily, a tsc compiler option could be added:  --referencePath, and the syntax for a reference could be updated to recognize a path relative to this referencePath using some special character that only has meaning if you use the -referencePath option, maybe '@', or something:
`/// <reference path="@/common/util/Foo.ts" />`

So, with:  `tsc -referencePath C:\someproject\main\ts  C:\someproject\test\ts\SomeTypeScript.ts`
the typescript compiler would look for Foo.ts in `C:\someproject\main\ts\common\util\Foo.ts`

No special configuration files are needed for this.  You would just have to tell the compiler the root(s) of your file structure to search for references, and indicate that the path is relative in your <reference> tag in your .ts files.

**Comment by TomBecker-BD** [comment]
It is an anti-pattern to put relative paths in source code. When you move or copy code to a different level in the directory hierarchy, it breaks. When you move a library it breaks all source files that reference it. Also, the library path has to be specified somewhere, in order to load the code, so duplicating the paths in the sources violates the DRY principle. 

I agree with @mconner, this problem has already been solved in C and other compilers where you can specify include paths. However, it generally doesn't require the sources to specify a variable (such as "{projectA}" or character (such as "@"). The source file specifies a partial path, or just the file name, and the compiler finds it. 

As a workaround I am using a "_references.ts" file and avoiding putting reference paths in other sources. 

## Proposal

I would like to propose two properties to the "tsconfig.json" file. 

```javascript
    "libraries": [
        "/libs/projectA/src",
        "/libs/projectB/src"
    ],
    "references": [
        "/libs/angularjs/angular.d.ts"
    ]
```
The "libraries" property is similar to @andrewvarga's proposal, but it only defines search paths, not variables for substitution. A source file can reference "/libs/projectA/src/Foo.ts" using: 

```javascript
    /// <reference path="Foo.ts" />
```
It should be an error if the reference path does not resolve to a single file. 

The "references" property works the same as "_references.ts". Having the property in "tsconfig.json" puts all the configuration information together in one place so it is easier to maintain. 

### What the Compiler Has to Do

1. Automatically include the reference paths specified in the "references" property, the same as if they had been specified in "_references.ts". 
2. When a reference path is encountered in the source, search relative to the source file location (for backward compatibility), and also relative to the paths in the "libraries" property. 

There is a performance impact because the reference path search needs to be exhaustive, in order to catch ambiguous reference errors. However, the exhaustive search only needs to be done if the developer opts in by specifying a "libraries" property. Also, there are many ways the searching could be optimized, and the results can be cached. 

There is no impact on generated code, compatibility, or any other features.

**Comment by mconner** [comment]
The reason I suggested a special character (e.g.: @) is that without it, the path is ambiguous.  Is it from the root (i.e.: relative to one of the specified paths) , or is it relative to the current file.  In Java, it is always from the root (or roots, as defined by the classpath), and so no special character is necessary. But to support both existing relative paths and root-level paths, it would be better to be explicit.  This also reduces the amount of searching that would be necessary, and eliminates an accidental hit (however unlikely) where the author meant one, but got another.

**Comment by basarat** [comment]
FWIW I made a proof of concept of the fact that tooling can make it easier : https://github.com/TypeStrong/atom-typescript#relative-paths it can do even more over time.

**Comment by RyanCavanaugh** [comment]
We consider this thing to be outside the scope of tsc, which we generally think of a compiler that does what it needs to and nothing extra. External build systems that understand TypeScript can provide this functionality themselves and provide better flexibility and configurability.

If those external tools settle on a good common pattern that everyone likes, or don't come up with anything at all, we can revisit this post-2.0.

**Comment by eschwartz** [comment]
> We consider this thing to be outside the scope of tsc, which we generally think of a compiler that does what it needs to and nothing extra.

@RyanCavanaugh - I would really like this to be the case, but the problem is that tsc has already taken on the task of converting ES6 style module imports to AMD style imports. Now that that decision is made, **we're kind of stuck with supporting the quirks of AMD module loading, one of which is the lack of support for relative import paths.**

I think the best solution would be for TypeScript to split out the *TypeScript to Javascript compiler" from the the "ES6 module to CommonJS/AMD" compiler. Then we could certainly close this issue as out-of-scope. But if that's not he direction the TS team wants to go, I would like to see better support for AMD.

**Comment by mhegazy** [comment]
@eschwartz We are looking into solving some of these issues in  #2338, we expect this to be in TypeScript 1.6; can you take a look at the suggestion and let us know if that solves the issues you are running into with AMD?

**Comment by SonofNun15** [comment]
Banging my head against this issue currently. My scenario:

Code lives in a 'source' folder that is a sibling of the 'typings' folder (from `tsd`). So all of the reference tags use relative paths to step out of 'source' and into 'typings'. This code is then being deployed via bower, which, by default, dumps the files into a 'bower_components' folder. So now the  type files (*.d.ts) are within 'bower_components\source' and need one more relative step up to get to the 'typings' folder at the root level.

I'll take a look at the suggested transform suggestions above.

**Comment by SonofNun15** [comment]
Turns out if I leave out the `/// <reference>` tags altogether the code still compiles as long as the ambient declaration files are given to the compiler or added to `tsd.d.ts`

**Comment by basarat** [comment]
That is by design. See http://blog.icanmakethiswork.io/2015/02/hey-tsconfigjson-where-have-you-been.html?m=1 for more about not needing reference tags

**Comment by jmp909** [comment]
it'd be good to have a ~ like .NET .. then at least we could move around files in the directories themselves whilst not having to worry about breaking relative references

eg  
`/// <reference path="~/tsDefinitions/jQuery.d.ts" />`
