### ISSUE TITLE
Decorators and closures vs. prototypical class design

### ISSUE THREAD

**Issue by MrMatthewLayton** [microsoft/TypeScript#2940]
Another of my bugbears with TypeScript is it's use of public/private declarations. Since TypeScript currently binds everything to the prototype, everything (once compiled to JavaScript) is public, even when it is declared private in TypeScript.

The closure model is the accepted method for ensuring privacy in JavaScript, whilst having lesser performance over the prototypical way of doing things. However I think it would be useful to be able to define closure based classes and have TypeScript emit these instead.

My proposal is to use a decorator which will tell the compiler to output the class using the closure model, rather than the default prototypical model.

TypeScript Example:

```
@closure
class Point {
    constructor(private x: number = 0, private y: number = 0) {
    }

    public getArea(): number {
        return this.x * this.y;
    }
}
```

Emitted JavaScript:

```
var Point = (function () {
    function Point(x, y) {
        if (x === void 0) { x = 0; }
        if (x === void 0) { y = 0; }
        var x = x;
        var y = y;

        this.getArea = function() {
            return x * y;
        }
    }

    return Point;
})();
```

**Comment by danquirk** [comment]
Is this something you'd always want at the class level or on a per member basis?

**Comment by series0ne** [comment]
That is a fantastic question!

I guess both, however I'm not sure how it would work at a per member basis. At the class level it's easy because the compiler would infer that all members were to be implemented using the closure model.

At the member level I can only imagine that the compiler would need to infer the use of closures where the decorator was applied to the variables.

Example

```
class Point {
    @closure
    private x: number = 0;
    private y: number = 0; // notice that y has not been specified as a closure variable.

    public getArea(): number {
        return this.x * this.y;
    }

    public get X(): number {
        return this.x;
    }

    public get Y(): number {
        return this.y;
    }
}
```
Emitted JavaScript:
```
var Point = (function () {
    function Point {
        var x = 0;
        this.y = 0;

        this.getArea = function() {
            return x * this.y;
        }

        Object.defineProperty(this, "X", { ... });
    }

    Object.defineProperty(Point.prototype, "Y", { ... });

    return Point;
}
```

Notice that since <code>x</code> has been defined using the closure model, the compiler has inferred that <code>getArea</code> and <code>X</code> must also be emitted using the closure model in order to access the <code>x</code> member, whilst <code>y</code> has been defined using the prototypical model, thus <code>Y</code> can be bound to the prototype.

**Comment by nippur72** [comment]
One of the advantages of the closure model is avoiding references to `this` so I would keep this feature in TypeScript too (e.g. no `this.x` but simply `x` in the above code).

Perhaps there could be another keyword `closure` to be used in place of `class` since I don't think that a closure can be extended/chained like a normal class. E.g.

```
closure Point {
   private x: number;
}
```
etc..

**Comment by bhsnll** [comment]
I'd love to see this happen. Closures result in better minification than prototypes. I feel like most of the time sending fewer bytes over the wire is a better optimization than faster object instantiation.

**Comment by RyanCavanaugh** [comment]
Closing due to lack of additional feedback. This would need to be brought through TC39 anyway
