### ISSUE TITLE
#29335 causes regression in property name lookup

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#29428]
#29335 adds a oops-wrong-path redirect to getTypeofVariableOrParameterOrProperty that switches to getTypeOfFuncClassEnumModule. This new redirect breaks property resolution in chrome-devtools-frontend:

```
node_modules/chrome-devtools-frontend/front_end/ui/ContextMenu.js(355,22): error TS2339: Property '_useSoftMenu' does not exist on type 'typeof ContextMenu'.
```

Here's the associated code:

```js
static initialize() {
    InspectorFrontendHost.events.addEventListener(InspectorFrontendHostAPI.Events.SetUseSoftMenu, setUseSoftMenu);
    /**
     * @param {!Common.Event} event
     */
    function setUseSoftMenu(event) {
      UI.ContextMenu._useSoftMenu = /** @type {boolean} */ (event.data); // this line
    }
  }```

I think this is because there are *some* symbols that have ValueModule set, but should still be resolved with getTypeofVariableOrParameterOrProperty. It's a matter of separating those from the ones that #29335 cares about.

**Comment by weswigham** [comment]
Per my commment in the `user` suite test - the new error is correct. The property access was allowed before because `UI.ContextMenu` acquired an `any` type from circular referencing, however now it (correctly) resolves to the namespace side of the type instead and the assignment fails (there is no top level assignment for that property, so it should never have worked).
