### ISSUE TITLE
F2 refactoring: You cannot rename elements that are defined in the standard TypeScript library

### ISSUE THREAD

**Issue by juristr** [microsoft/TypeScript#29445]
I'm getting the above mentioned error when trying to refactor a type named `Comment`.

- VSCode Version: Version 1.31.0-insider (1.31.0-insider) (b4fc71b972eae2425d39ac4041df0c36cfa1bb37)
- OS Version: macOS Mojave

Steps to Reproduce:

Take the following piece of code:

```
interface MyInterface {
  comments: Comment[];
}

interface Comment {
  id: number;
  text: string;
}
```

Click "F2" on the `Comment` type in the `MyInterface` to rename it. `F12` on the other hand works as expected and correctly recognizes my own `Comment` type defined in the same file.

F2 on the other hand seems to target the `Comment` type defined in the `lib.dom.d.ts`:

![image](https://user-images.githubusercontent.com/542458/51233702-dc9cc480-196a-11e9-833e-d1287a42e2ac.png)

At least that's where F12 jumps when I comment my own `Comment` interface.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
The error could be more clear here but having your own `Comment `interface that is merged with the `Comment` interface from `dom.d.ts` is likely not what you want. This merging is the correct TS behavior. 

To prevent the merging of these interfaces, I believe you just need to make sure that you file is a module by adding an `import` or `export`. Otherwise, both `Comment` interfaces will be in the same global scope

**Comment by fatcerberus** [comment]
That is very surprising to me that one needs to have an `import` or `export` to have the file treated as a module — this is not how modules work according to the ES specification.  *Module* and *Script* are entirely separate parse targets.  Is there some historical reason for TypeScript behaving this way?
