### ISSUE TITLE
Unable to distinguish properties of union types for objects in function parameters

### ISSUE THREAD

**Issue by achung89** [Microsoft/TypeScript#29476]
**TypeScript Version:**  3.3.0-dev..20190117 Edit: corrected tsc -v

**Search Terms:**
"Union", "Parameter", "does not exist on type" 
**Code**

```ts
interface A {
  bar: string;
}

interface B {
  baz: string;
}

type C = A | B;


let a:C = {
  bar: 'bar',
};

a.bar; //  No Error

type D = 'cat' | 'dog';
const fn = ( foo: C, animal: D ) => {
  foo.bar; // Error: Property 'bar' does not exist on type 'B'
  foo.baz; // Error: Property 'baz' does not exist on type 'A'
  animal === 'dog'; // No Error
}
```

**Expected behavior:**
No error when foo.bar and foo.baz is accessed in function. 

**Actual behavior:**
when accessing foo.bar, 
  Property 'bar' does not exist on type 'C'.
  Property 'bar' does not exist on type 'B'.
when accessing foo.baz:
  Property 'baz' does not exist on type 'C'.
  Property 'baz' does not exist on type 'A'.
**Playground Link:** 
http://www.typescriptlang.org/play/#src=%0D%0Ainterface%20A%20%7B%0D%0A%20%20bar%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20B%20%7B%0D%0A%20%20baz%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Atype%20C%20%3D%20A%20%7C%20B%3B%0D%0A%0D%0A%0D%0Alet%20a%3AC%20%3D%20%7B%0D%0A%20%20bar%3A%20'bar'%2C%0D%0A%7D%3B%0D%0A%0D%0Aa.bar%3B%0D%0A%0D%0Atype%20D%20%3D%20'cat'%20%7C%20'dog'%3B%0D%0Aconst%20fn%20%3D%20(%20foo%3A%20C%2C%20animal%3A%20D%20)%20%3D%3E%20%7B%0D%0A%20%20foo.bar%3B%20%0D%0A%20%20foo.baz%3B%20%0D%0A%20%20animal%20%3D%3D%3D%20'dog'%3B%20%0D%0A%7D

**Related Issues:** 
#29471

**Comment by dragomirtitian** [comment]
You should not be able to access members of unions unless they are common to all members. In your example although you declare the type as `C` typescript uses flow analysis to determine that the variable `a` can only be of type `A` (based on the assignment). Introduce some uncertainty and you can't acces it anymore:

```ts
let a: C = Math.random() > 0.5 ? {
  bar: 'bar',
} : {
  baz: ""
};


a.bar; // error now since the compiler does not know if a will be A or B
```

In the case of a function the compiler has no way of knowing what you will call the function with, so there is no extra information for flow analysis to take advantage of (unlike the variable case)

You need to use a type-guard to distinguish between the two cases: 

```ts
const fn = ( foo: C, animal: D ) => {
  if ("bar" in foo) {
    foo.bar; // ok foo is A
  } else {
    foo.baz; // ok foo is B since in is not A
  } 
}
```
The `animal === 'dog'` works just fine since `animal` can be either `'dog'` or `'cat'`, so caomparing with either is valid.

**Comment by achung89** [comment]
Thank you for the explanation, I can see how the uncertainty of the union type can be an issue.  In the real world example that I'm using it is probably best to implement typescript's typeguard, thank you for the help.
