### ISSUE TITLE
DeepReadonly type fails to compile on typescript 3.1.1+

### ISSUE THREAD

**Issue by masterkidan** [microsoft/TypeScript#29566]
**TypeScript Version:**  3.1.1+

**Search Terms:** DeepReadonly

**Code**

```ts
export type Primitive = string | number | boolean | undefined | null | Function | symbol;
export type DeepReadonly<T> =
  T extends [infer A]                                                       ? DeepReadonlyObject<[A]> :
  T extends [infer A, infer B]                                              ? DeepReadonlyObject<[A, B]> :
  T extends [infer A, infer B, infer C]                                     ? DeepReadonlyObject<[A, B, C]> :
  T extends [infer A, infer B, infer C, infer D]                            ? DeepReadonlyObject<[A, B, C, D]> :
  T extends [infer A, infer B, infer C, infer D, infer E]                   ? DeepReadonlyObject<[A, B, C, D, E]> :
  T extends [infer A, infer B, infer C, infer D, infer E, infer F]          ? DeepReadonlyObject<[A, B, C, D, E, F]> :
  T extends [infer A, infer B, infer C, infer D, infer E, infer F, infer G] ? DeepReadonlyObject<[A, B, C, D, E, F, G]> :
  T extends Map<infer U, infer V> ? ReadonlyMap<DeepReadonlyObject<U>, DeepReadonlyObject<V>> :
  T extends Set<infer U> ? ReadonlySet<DeepReadonlyObject<U>> :
  T extends Promise<infer U> ? Promise<DeepReadonlyObject<U>> :
  T extends Primitive ? T :
  T extends (infer A)[]           ? DeepReadonlyArray<A> :
  DeepReadonlyObject<T>;

interface DeepReadonlyArray<T> extends ReadonlyArray<DeepReadonly<T>> {}
type DeepReadonlyObject<T> = { readonly [P in keyof T]: DeepReadonly<T[P]> }
```

**Expected behavior:**
This used to work as of typescript 3.0.1

**Actual behavior:**
In typescript 3.1.1 a new error is thrown saying that the type is cyclical
In typescript 3.2+ the above error, instead ends up casting the type as `any`
**Playground Link:**  
Here's a gist with tests for the type 
https://gist.github.com/masterkidan/7322752f569b1bba53e0426266768623

[Playground link](<https://www.typescriptlang.org/play/index.html#src=export%20type%20Primitive%20%3D%20string%20%7C%20number%20%7C%20boolean%20%7C%20undefined%20%7C%20null%20%7C%20Function%20%7C%20symbol%3B%0D%0Aexport%20type%20DeepReadonly%3CT%3E%20%3D%0D%0A%20%20T%20extends%20%5Binfer%20A%5D%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3F%20DeepReadonlyObject%3C%5BA%5D%3E%20%3A%0D%0A%20%20T%20extends%20%5Binfer%20A%2C%20infer%20B%5D%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3F%20DeepReadonlyObject%3C%5BA%2C%20B%5D%3E%20%3A%0D%0A%20%20T%20extends%20%5Binfer%20A%2C%20infer%20B%2C%20infer%20C%5D%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3F%20DeepReadonlyObject%3C%5BA%2C%20B%2C%20C%5D%3E%20%3A%0D%0A%20%20T%20extends%20%5Binfer%20A%2C%20infer%20B%2C%20infer%20C%2C%20infer%20D%5D%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3F%20DeepReadonlyObject%3C%5BA%2C%20B%2C%20C%2C%20D%5D%3E%20%3A%0D%0A%20%20T%20extends%20%5Binfer%20A%2C%20infer%20B%2C%20infer%20C%2C%20infer%20D%2C%20infer%20E%5D%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3F%20DeepReadonlyObject%3C%5BA%2C%20B%2C%20C%2C%20D%2C%20E%5D%3E%20%3A%0D%0A%20%20T%20extends%20%5Binfer%20A%2C%20infer%20B%2C%20infer%20C%2C%20infer%20D%2C%20infer%20E%2C%20infer%20F%5D%20%20%20%20%20%20%20%20%20%20%3F%20DeepReadonlyObject%3C%5BA%2C%20B%2C%20C%2C%20D%2C%20E%2C%20F%5D%3E%20%3A%0D%0A%20%20T%20extends%20%5Binfer%20A%2C%20infer%20B%2C%20infer%20C%2C%20infer%20D%2C%20infer%20E%2C%20infer%20F%2C%20infer%20G%5D%20%3F%20DeepReadonlyObject%3C%5BA%2C%20B%2C%20C%2C%20D%2C%20E%2C%20F%2C%20G%5D%3E%20%3A%0D%0A%20%20T%20extends%20Map%3Cinfer%20U%2C%20infer%20V%3E%20%3F%20ReadonlyMap%3CDeepReadonlyObject%3CU%3E%2C%20DeepReadonlyObject%3CV%3E%3E%20%3A%0D%0A%20%20T%20extends%20Set%3Cinfer%20U%3E%20%3F%20ReadonlySet%3CDeepReadonlyObject%3CU%3E%3E%20%3A%0D%0A%20%20T%20extends%20Promise%3Cinfer%20U%3E%20%3F%20Promise%3CDeepReadonlyObject%3CU%3E%3E%20%3A%0D%0A%20%20T%20extends%20Primitive%20%3F%20T%20%3A%0D%0A%20%20T%20extends%20(infer%20A)%5B%5D%20%20%20%20%20%20%20%20%20%20%20%3F%20DeepReadonlyArray%3CA%3E%20%3A%0D%0A%20%20DeepReadonlyObject%3CT%3E%3B%0D%0A%0D%0Ainterface%20DeepReadonlyArray%3CT%3E%20extends%20ReadonlyArray%3CDeepReadonly%3CT%3E%3E%20%7B%7D%0D%0Atype%20DeepReadonlyObject%3CT%3E%20%3D%20%7B%20readonly%20%5BP%20in%20keyof%20T%5D%3A%20DeepReadonly%3CT%5BP%5D%3E%20%7D%0D%0A%0D%0Atype%20DeepTestType%20%3D%20DeepReadonly%3C%7B%0D%0A%20%20a%3A%20string%0D%0A%20%20b%3A%20number%5B%5D%0D%0A%20%20c%3A%20%7B%20d%3A%20string%2C%20e%3A%20number%5B%5D%2C%20f%3A%20%5Bnumber%2C%20%7B%20g%3A%20string%2C%20h%3A%20number%20%7D%5D%20%7D%0D%0A%20%20i%3A%20%5Bnumber%2C%20string%2C%20boolean%5D%0D%0A%20%20j%3A%20%7B%20id%3A%20number%2C%20name%3A%20string%20%7D%5B%5D%0D%0A%20%20k%3A%20Set%3Cnumber%3E%0D%0A%20%20l%3A%20Map%3C%7B%20id%3A%20number%2C%20name%3A%20string%20%7D%2C%20%7B%20age%3A%20number%20%7D%3E%0D%0A%20%20m()%3A%20void%0D%0A%20%20n%3A%20Symbol%0D%0A%20%20o%3A%20Promise%3Cvoid%3E%0D%0A%20%20p%3A%20Promise%3C%7B%20q%3A%20%7B%20r%3A%20number%20%7D%7D%3E%0D%0A%7D%3E%0D%0A%0D%0Aconst%20record%20%3D%20%7B%20id%3A%20123%2C%20name%3A%20'zxc'%20%7D%0D%0A%0D%0Aconst%20deepTest%3A%20DeepTestType%20%3D%20%7B%0D%0A%20%20a%3A%20'asdf'%2C%0D%0A%20%20b%3A%20%5B123%2C%20234%5D%2C%0D%0A%20%20c%3A%20%7B%20d%3A%20'zxc'%2C%20e%3A%20%5B1%2C%202%2C%203%5D%2C%20f%3A%20%5B1%2C%20%7B%20g%3A%20'iop'%2C%20h%3A%20789%20%7D%5D%20%7D%2C%0D%0A%20%20i%3A%20%5B1%2C%20'a'%2C%20true%5D%2C%0D%0A%20%20j%3A%20%5B%7B%20id%3A%201%2C%20name%3A%20'c'%20%7D%5D%2C%0D%0A%20%20k%3A%20new%20Set(%5B1%2C%202%2C%203%5D)%2C%0D%0A%20%20l%3A%20new%20Map(%5B%0D%0A%20%20%20%20%5Brecord%2C%20%7B%20age%3A%20789%20%7D%5D%0D%0A%20%20%5D)%2C%0D%0A%20%20m()%20%7B%20console.log('m%20says%20mmm')%20%7D%2C%0D%0A%20%20n%3A%20Symbol()%2C%0D%0A%20%20o%3A%20Promise.resolve()%0D%0A%7D%0D%0A%0D%0Aconsole.log(deepTest.a)%20%2F%2F%20pass%0D%0AdeepTest.a%20%3D%20'zxcv'%20%2F%2F%20fail%0D%0A%0D%0Aconsole.log(deepTest.b%5B0%5D)%20%2F%2F%20pass%0D%0AdeepTest.b%5B0%5D%20%3D%20789%20%2F%2F%20fail%0D%0AdeepTest.b%5B1%5D%20%3D%20890%20%2F%2F%20fail%0D%0A%0D%0Aconsole.log(deepTest.c.d)%20%2F%2F%20pass%0D%0AdeepTest.c.d%20%3D%20'asd'%20%2F%2F%20fail%0D%0A%0D%0Aconsole.log(deepTest.c.f%5B0%5D)%20%2F%2F%20pass%0D%0AdeepTest.c.f%5B0%5D%20%3D%20'asd'%20%2F%2F%20fail%0D%0A%0D%0Aconsole.log(deepTest.c.f%5B1%5D.g)%20%2F%2F%20pass%0D%0AdeepTest.c.f%5B1%5D.g%20%3D%20'zxc'%20%2F%2F%20fail%0D%0A%0D%0Aconsole.log(deepTest.i%5B1%5D)%20%2F%2F%20pass%0D%0Aconsole.log(Math.pow(deepTest.i%5B0%5D%2C%201))%20%20%2F%2F%20pass%20(doesn't%20union%20tuple)%0D%0AdeepTest.i%5B1%5D%20%3D%20'zxc'%20%2F%2F%20fail%0D%0A%0D%0Aconsole.log(deepTest.j%5B0%5D.id)%20%2F%2F%20pass%0D%0AdeepTest.j%5B0%5D.id%20%3D%20789%20%2F%2F%20fail%0D%0A%0D%0Aconsole.log(deepTest.k)%20%2F%2F%20pass%0D%0AdeepTest.k.add(789)%20%2F%2F%20fail%0D%0A%0D%0Aconsole.log(deepTest.l.get(record).age)%20%2F%2F%20pass%0D%0AdeepTest.l.get(record).age%20%3D%201%20%2F%2F%20fail%0D%0AdeepTest.l.set(%7B%20id%3A%20789%2C%20name%3A%20'blah'%20%7D%2C%20%7B%20age%3A%20567%20%7D)%20%2F%2F%20fail%0D%0Alet%20keys%20%3D%20deepTest.l.keys()%3B%0D%0Alet%20key%20%3D%20keys.next()%0D%0Awhile(key)%20%7B%0D%0A%20%20console.log(key.value.name)%20%2F%2F%20pass%0D%0A%20%20key.value.name%20%3D%20'zxc'%20%2F%2F%20fail%0D%0A%20%20key%20%3D%20keys.next()%3B%0D%0A%7D%20%0D%0A%0D%0AdeepTest.m()%20%2F%2F%20pass%0D%0AdeepTest.m%20%3D%20()%20%3D%3E%20console.log('n%20says%20nnn')%20%2F%2F%20fail%0D%0A%0D%0Aconsole.log(deepTest.n)%20%2F%2F%20pass%0D%0AdeepTest.n%20%3D%20Symbol()%20%2F%2F%20fail%0D%0A%0D%0AdeepTest.o.then(()%20%3D%3E%20console.log('hello'))%20%2F%2F%20pass%0D%0AdeepTest.o%20%3D%20Promise.resolve()%20%2F%2F%20fail%0D%0AdeepTest.p.then((obj)%20%3D%3E%20console.log(obj))%20%2F%2F%20pass%0D%0AdeepTest.p.then((obj)%20%3D%3E%20obj.q%20%3D%202))%20%2F%2F%20fail>)

**Related Issues:**
https://github.com/Microsoft/TypeScript/issues/27421
https://github.com/Microsoft/TypeScript/issues/13923
https://github.com/Microsoft/TypeScript/issues/26236

**Comment by masterkidan** [comment]
I understand this may be by design, but is there a way to achieve the same with newer versions of typescript?

**Comment by Dean177** [comment]
@masterkidan looks like this is due to the tuple types, without those your code works as expected
[Playground link](https://www.typescriptlang.org/play/index.html#src=export%20type%20Primitive%20%3D%20string%20%7C%20number%20%7C%20boolean%20%7C%20undefined%20%7C%20null%20%7C%20Function%20%7C%20symbol%3B%0D%0Aexport%20type%20DeepReadonly%3CT%3E%20%3D%0D%0A%20%20%2F%2F%20T%20extends%20%5Binfer%20A%5D%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3F%20DeepReadonlyObject%3C%5BA%5D%3E%20%3A%0D%0A%20%20%2F%2F%20T%20extends%20%5Binfer%20A%2C%20infer%20B%5D%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3F%20DeepReadonlyObject%3C%5BA%2C%20B%5D%3E%20%3A%0D%0A%20%20%2F%2F%20T%20extends%20%5Binfer%20A%2C%20infer%20B%2C%20infer%20C%5D%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3F%20DeepReadonlyObject%3C%5BA%2C%20B%2C%20C%5D%3E%20%3A%0D%0A%20%20%2F%2F%20T%20extends%20%5Binfer%20A%2C%20infer%20B%2C%20infer%20C%2C%20infer%20D%5D%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3F%20DeepReadonlyObject%3C%5BA%2C%20B%2C%20C%2C%20D%5D%3E%20%3A%0D%0A%20%20%2F%2F%20T%20extends%20%5Binfer%20A%2C%20infer%20B%2C%20infer%20C%2C%20infer%20D%2C%20infer%20E%5D%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3F%20DeepReadonlyObject%3C%5BA%2C%20B%2C%20C%2C%20D%2C%20E%5D%3E%20%3A%0D%0A%20%20%2F%2F%20T%20extends%20%5Binfer%20A%2C%20infer%20B%2C%20infer%20C%2C%20infer%20D%2C%20infer%20E%2C%20infer%20F%5D%20%20%20%20%20%20%20%20%20%20%3F%20DeepReadonlyObject%3C%5BA%2C%20B%2C%20C%2C%20D%2C%20E%2C%20F%5D%3E%20%3A%0D%0A%20%20%2F%2F%20T%20extends%20%5Binfer%20A%2C%20infer%20B%2C%20infer%20C%2C%20infer%20D%2C%20infer%20E%2C%20infer%20F%2C%20infer%20G%5D%20%3F%20DeepReadonlyObject%3C%5BA%2C%20B%2C%20C%2C%20D%2C%20E%2C%20F%2C%20G%5D%3E%20%3A%0D%0A%20%20T%20extends%20Map%3Cinfer%20U%2C%20infer%20V%3E%20%3F%20ReadonlyMap%3CDeepReadonlyObject%3CU%3E%2C%20DeepReadonlyObject%3CV%3E%3E%20%3A%0D%0A%20%20T%20extends%20Set%3Cinfer%20U%3E%20%3F%20ReadonlySet%3CDeepReadonlyObject%3CU%3E%3E%20%3A%0D%0A%20%20T%20extends%20Promise%3Cinfer%20U%3E%20%3F%20Promise%3CDeepReadonlyObject%3CU%3E%3E%20%3A%0D%0A%20%20T%20extends%20Primitive%20%3F%20T%20%3A%0D%0A%20%20T%20extends%20(infer%20A)%5B%5D%20%20%20%20%20%20%20%20%20%20%20%3F%20DeepReadonlyArray%3CA%3E%20%3A%0D%0A%20%20DeepReadonlyObject%3CT%3E%3B%0D%0A%0D%0Ainterface%20DeepReadonlyArray%3CT%3E%20extends%20ReadonlyArray%3CDeepReadonly%3CT%3E%3E%20%7B%7D%0D%0Atype%20DeepReadonlyObject%3CT%3E%20%3D%20%7B%20readonly%20%5BP%20in%20keyof%20T%5D%3A%20DeepReadonly%3CT%5BP%5D%3E%20%7D%0D%0A%0D%0Atype%20DeepTestType%20%3D%20DeepReadonly%3C%7B%0D%0A%20%20a%3A%20string%0D%0A%20%20b%3A%20number%5B%5D%0D%0A%20%20c%3A%20%7B%20d%3A%20string%2C%20e%3A%20number%5B%5D%2C%20f%3A%20%5Bnumber%2C%20%7B%20g%3A%20string%2C%20h%3A%20number%20%7D%5D%20%7D%0D%0A%20%20i%3A%20%5Bnumber%2C%20string%2C%20boolean%5D%0D%0A%20%20j%3A%20%7B%20id%3A%20number%2C%20name%3A%20string%20%7D%5B%5D%0D%0A%20%20k%3A%20Set%3Cnumber%3E%0D%0A%20%20l%3A%20Map%3C%7B%20id%3A%20number%2C%20name%3A%20string%20%7D%2C%20%7B%20age%3A%20number%20%7D%3E%0D%0A%20%20m()%3A%20void%0D%0A%20%20n%3A%20Symbol%0D%0A%20%20o%3A%20Promise%3Cvoid%3E%0D%0A%20%20p%3A%20Promise%3C%7B%20q%3A%20%7B%20r%3A%20number%20%7D%7D%3E%0D%0A%7D%3E%0D%0A%0D%0Aconst%20record%20%3D%20%7B%20id%3A%20123%2C%20name%3A%20'zxc'%20%7D%0D%0A%0D%0Aconst%20deepTest%3A%20DeepTestType%20%3D%20%7B%0D%0A%20%20a%3A%20'asdf'%2C%0D%0A%20%20b%3A%20%5B123%2C%20234%5D%2C%0D%0A%20%20c%3A%20%7B%20d%3A%20'zxc'%2C%20e%3A%20%5B1%2C%202%2C%203%5D%2C%20f%3A%20%5B1%2C%20%7B%20g%3A%20'iop'%2C%20h%3A%20789%20%7D%5D%20%7D%2C%0D%0A%20%20i%3A%20%5B1%2C%20'a'%2C%20true%5D%2C%0D%0A%20%20j%3A%20%5B%7B%20id%3A%201%2C%20name%3A%20'c'%20%7D%5D%2C%0D%0A%20%20k%3A%20new%20Set(%5B1%2C%202%2C%203%5D)%2C%0D%0A%20%20l%3A%20new%20Map(%5B%0D%0A%20%20%20%20%5Brecord%2C%20%7B%20age%3A%20789%20%7D%5D%0D%0A%20%20%5D)%2C%0D%0A%20%20m()%20%7B%20console.log('m%20)

**Comment by masterkidan** [comment]
@Dean177 : Thanks!, is there a way to make this work without removing support for Tuples?

**Comment by dragomirtitian** [comment]
Actually I think you are better off wating for 3.4  and Improved support for read-only arrays and tuples (#29435). With this new feature mapped types will apply the `readonly` modifier to tuples and arrays and you will not need any special handling for them. This will work as expected (as far as I can tell) in 3.4 (you can try it out with `npm install typescript@next`:

```ts
type DeepTestType = DeepReadonly<{
  a: string
  b: number[]
  c: { d: string, e: number[], f: [number, { g: string, h: number }] }
  i: [number, string, boolean]
  j: { id: number, name: string }[]
  k: Set<number>
  l: Map<{ id: number, name: string }, { age: number }>
  m(): void
  n: Symbol
  o: Promise<void>
  p: Promise<{ q: { r: number }}>
}>
```

**Comment by aleclarson** [comment]
Immer has a "deep readonly" type called `Immutable` (see [here](https://github.com/mweststrate/immer/blob/f8d9d1c02e75db8c0e9ea523daf883908e520856/src/immer.d.ts#L64-L73)) that works fine in 3.1+
