### ISSUE TITLE
Cannot reference type of a different property in the same object literal

### ISSUE THREAD

**Issue by zbjornson** [microsoft/TypeScript#29586]
**TypeScript Version:**  3.3.0-dev.20190125

**Search Terms:** circular, referenced directly or indirectly

**Code**

```ts
const foo2 = {
	bar: {
		baz: 1
	},
	/**
	 * @param {typeof foo2.bar} p1
	 */
	myfun(p1) {
		return p1;
	}
};
```

**Expected behavior:**
TS should be able to type `p1` as `{baz: number}`.

**Actual behavior:**
`p1` is either implicit any (TS) or causes `'p1' is referenced directly or indirectly in its own type annotation. [2502]` (vscode with checkJs). I *think* this should be possible but I sort of see why this is trickier.

**Playground Link:** https://typescript-play.js.org/#code/FAYw9gdgzgLgBAMzGATHAvHA3sAkAIwEMAnALmzwMIC9yBGPAXwBo8B6AKg7zg7gAEADiUIBbbDACeggKZgEiZCgB0RYoziCGuXmzyjJCAK4QAFFoCUFXLmIyYR4hE10A3E2CN3QA

Adding an alias doesn't help (https://typescript-play.js.org/#code/FAFwngDgpgBAYgewQJgEIEMBOAVSsC8M40CAZjKUsgHQBGWwwAxggHYDOIFVMhA3sACQ9TAC4YAwcPQAvcQEYhAXwA0QgPQAqTUJiaYAAQhZ0AWwmIUGHHiUwIiwXvVDTYUgFdWACgcBKCSFBTCgQD0xWe3kAbmVgJVigA).

**Related Issues:** none found

**Comment by fatcerberus** [comment]
I don’t think that works, because if you’re looking at the program from a control-flow POV, the object literal exists before `foo2` does.  BUT since it’s giving you a circular-reference error it seems to be smart enough to figure that out... however you’re still referencing the value being defined *while defining it* so I guess the type checker doesn’t like that.

Probably not a bug, but it would be useful if this could be made to work regardless. :smiley:

**Comment by RyanCavanaugh** [comment]
Due to how the checker is written, it isn't possible to refer to `typeof foo2` until its initializer's type resolved. Fixing this would be a fairly massive architectural change, unfortunately.
