### ISSUE TITLE
completion list doesn't suggest 'readonly' in type context

### ISSUE THREAD

**Issue by ajafff** [microsoft/TypeScript#29666]
**TypeScript Version:**  3.4.0-dev.20190131

**Search Terms:**

**Code**

```ts
type T = read/**/
```

**Expected behavior:**

Completion list should contain `readonly`.

**Actual behavior:**

Completion list doesn't contain `readonly`.

**Related Issues:**
#29658

**Comment by m-henderson** [comment]
@DanielRosenwasser hey, Daniel. Could you give me a starting point so that I can help fix this issue?

**Comment by DanielRosenwasser** [comment]
I would check out `getCompletionsAtPosition` in `src/services`. Tests are in `tests/cases/fourslash`. See more [here](https://github.com/Microsoft/TypeScript/blob/75101d4b72b94d8158dabb249f9b6f969353110c/CONTRIBUTING.md).

**Comment by m-henderson** [comment]
appreciate it

**Comment by m-henderson** [comment]
@ajafff could you give more code detail on how I can reproduce the issue? this is my first time contributing to the typescript library. Do I need to explicitly type your code to reproduce the issue? 
![image](https://user-images.githubusercontent.com/16070192/53171921-bab9e180-35a9-11e9-9f4a-3797b9ad954a.png)

**Comment by m-henderson** [comment]
does anyone know if there is a guide on  how to actually debug the typescript codebase in visual studio code so that I can fix this issue? Basically, I am looking to set a break point while debugging and then when the code tries to auto complete, I would like that break point to be hit. I have never contributed directly to a language so maybe I am approaching this wrong. someone mind giving me a tip/instructions? thanks

**Comment by DanielRosenwasser** [comment]
https://github.com/Microsoft/TypeScript/wiki/Debugging-Language-Service-in-VS-Code
