### ISSUE TITLE
Inconsistent behaviour between interfaces, parameterlist and function calls

### ISSUE THREAD

**Issue by Chieleman** [Microsoft/TypeScript#2967]
Consider the following code:

```ts
module Test {
    interface ITest {
        c(p1: boolean, p2: boolean): void;
    }

    class TestClass1 implements ITest {
        c(p1: boolean) {
        }
    }

    var t1: TestClass1 = new TestClass1();
    t1.c(true); // correct
    t1.c(true, true); // incorrect
    (<ITest>t1).c(true, true); // correct
    (<ITest>t1).c(true, true, true); // incorrect
}
```
Isn't it strange that a function call cannot be made (like in javascript) with more parameters than defined in the function, but the principal of a function definition in an interface IS based on that functionality of javascript. 

In other words, a function definition is not strict with the parameter list (like in e.g. C#) but a function call is.

**Comment by DanielRosenwasser** [comment]
Not really, if you know the function only takes one parameter, why on earth would you explicitly pass two? It's probably an error, and it's under your control at a use site.

On the flip side, if you have an existing parameter that is of type `(a: string, b: boolean) => void, but you don't need parameter `b` in your callback, you're typically not going to the change the definition site to accommodate your callback. It's permissible to ignore `b`, so you can pass in a function like `(a: string) => void`.

In fact, this is a frequent pattern in existing JavaScript, since the callback to [`Array.prototype.forEach`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach) takes several parameters, you may only be interested in the first one.

---------------

Also, as a tip, when posting code in GitHub, you can [post code using triple-backticks](https://help.github.com/articles/markdown-basics/#multiple-lines) instead of with indentation:

    ```TypeScript
    console.log("Hello world!");
    ```

    ```Python
    print("Hello world!")
    ```

**Comment by Chieleman** [comment]
I was actually posting this because it is strange that the compiler accepts the implementation of the interface since the functions parameterlist does not match

**Comment by DanielRosenwasser** [comment]
Ah, I misunderstood and didn't see your `implements` clause; that actually is a bit odd. I'll reopen that and check in with the rest of the team.

**Comment by Chieleman** [comment]
Np.must admit that the explaining text was not very clear ;-)

**Comment by RyanCavanaugh** [comment]
`implements` is checked via "is a subtype of". Functions with fewer parameters are subtypes of functions with more parameters, assuming the present parameters match (as Daniel explained).

The basic rule is here is substitutability -- a `TestClass1` can be used anywhere an `ITest` is needed, even though it does discard some parameters.

**Comment by Chieleman** [comment]
Then why are optional parameters implemented in typescript interfaces, e.g. with a '?'. If parameters are optional it makes optional parameters completely useless.

**Comment by RyanCavanaugh** [comment]
Optional parameters still mean something in interfaces:
```ts
interface Foo {
  bar1(x, y);
  bar2(x, y?);
}
var x: Foo;
x.bar1(0); // Error
x.bar2(0); // OK
```

There's honestly not much value in forcing a class to have the exact same signatures as an interface it's implementing. If you go to write `ITest2#c` in `TestClass1` and finish writing the method without realizing you needed the second argument... then you probably didn't!

**Comment by Chieleman** [comment]
Bit that is what i meant to explain un the iriginal text.

With interface typescript takes the non strict javascript approach, and with function (calls) it is strict as it should be.

That is inconsistent and if i might say so a pitty. Would to see it as strict as it should be. It is not an interface for nothing.

**Comment by Chieleman** [comment]
Getting late over here... Sorry for the type-o's

**Comment by danquirk** [comment]
We have to balance strictness with convenience and what people actually do with their code already. Structurally typed interfaces mesh very well with how people want to describe how their code actually behaves.

**Comment by Chieleman** [comment]
I understand now why it us implemented the way it is.but for someone with a c# background like me it is a little bit strange
