### ISSUE TITLE
New Website Logo: Unsplash

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#29686]
Please fill the following out:

- Name: Unsplash
- Homepage url: https://unsplash.com/
- Brand Guidelines/Licensing:
- Logo: https://jsbin.com/kofahe/2

``` html
<svg class="_2m4hn" version="1.1" viewBox="0 0 32 32" aria-labelledby="unsplash-home" aria-hidden="false"><title id="unsplash-home">Unsplash Home</title><path d="M10 9V0h12v9H10zm12 5h10v18H0V14h10v9h12v-9z"></path></svg>
```

> Example:
>
> Name: Microsoft
> Homepage url: https://microsoft.com
> Brand Guidelines/Licensing: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx
> Logo: https://news.microsoft.com/microsoft-news-center-photos/msft_logo_rgb_c-gray/

**Comment by orta** [comment]
Hey folks -we're looking at a new website and it's likely that the friends of TypeScript page isn't going to make it to the new site. This is mainly because close to everyone is a friend of TypeScript now and listing folks kinda feels a bit un-inclusive to everyone else. 

So I'm going to close this issue - thanks for posting to apply
