### ISSUE TITLE
Show notice properties marked as optional, that are never undefined|null

### ISSUE THREAD

**Issue by sod** [Microsoft/TypeScript#29680]
Given this code:

```typescript
class Bar {
}

class Foo {
    bar?: Bar;

    constructor() {
        this.bar = new Bar();
    }
}
```

The `?` on `bar?: Bar` isn't an error, but it's completely unnecessary, as the class is always created in the constructor. Couldn't typescript provide a hint like `Optional value is never undefined|null, you could remove the optional`

IMO the beauty of typescript is certainty about types. And this hint could get rid of self imposed uncertainty.

Also it may be nice in refactorings if a value that was optional becomes non-optional.

**Comment by dragomirtitian** [comment]
Maybe if the property is `private` and there are no `undefined` assignments within the class. Otherwise it is hard to know that `?` is trully unnecessary, it might be initialized, but the writer of the class might actually want to allow something like this:

```ts
class Bar {
}

class Foo {
    bar?: Bar;

    constructor() {
        this.bar = new Bar();
    }
}

new Foo().bar = undefined;
```

Either way, tslint/eslint might be a better fit for such a check.

**Comment by sod** [comment]
hm, too bad tslint doesn't have a rule like this yet. Closing this as I already got two against me in 3 hours 😅
