### ISSUE TITLE
Microsoft.TypeScript.Compiler NuGet package does not contain 3.2 or 3.3 versions

### ISSUE THREAD

**Issue by ADobin** [Microsoft/TypeScript#29689]
**TypeScript Version:**  3.3.1

**Search Terms:** nuget, Microsoft.TypeScript.Compiler

**Code**
No code example.

**Expected behavior:** Latest TypeScript compiler available as a NuGet package.

**Actual behavior:** Last two versions of the compiler are missing from the NuGet package. You can see the available packages at https://www.nuget.org/packages/Microsoft.TypeScript.Compiler/.

**Playground Link:**  N/A

**Related Issues:** #26582

**Comment by weswigham** [comment]
IIRC that's because after `3.1` we stopped shipping the compiler via nuget, just the [msbuild tasks](https://www.nuget.org/packages/Microsoft.TypeScript.MSBuild/) - since, as always, you can fetch the latest version of the compiler via `npm`. Am I correct @minestarks ?

**Comment by DanielRosenwasser** [comment]
@PranavSenthilnathan what's the work-around here again?

**Comment by Dehalion** [comment]
So what is the recommended way to use TypeScript now if you have Visual Studio web projects?
Go back to install/update the SDK manually or add `npm` just for keeping the TypeScript compiler up to date?

**Comment by minestarks** [comment]
@Dehalion how were you building before?

**Comment by Dehalion** [comment]
I use the Compiler and MSBuild NuGet packages in my ASP.NET projects to have the same TypeScript version on each development machine for a given project.

Additionally I have the TypeScript SDK installed on my machines because I had trouble with linting DOM or Scripthost globals in Visual Studio and this was one try of fixing it.

If the Compiler NuGet package gets no updates anymore how do I make sure my project uses the latest TypeScript, not my installed older SDK version?

**Comment by minestarks** [comment]
The `Microsoft.TypeScript.Compiler` package is redundant with the `Microsoft.TypeScript.MSBuild` package so you can just remove the former as you upgrade. The latter contains `tsc.js`.

You still may need to install the corresponding SDK if you're having IntelliSense issues in the VS editor. But you shouldn't need it for building. The compiler will get picked up from the nuget package.

Which version of Visual Studio do you use to build? If you're using VS 2017, it includes node.js and you shouldn't have to do anything special except have the right nuget package.

**Comment by Dehalion** [comment]
Yes, I'm using VS2017. That's good to know. I'll remove the Compiler package and update the SDK for IntelliSense. Thanks for your help.

**Comment by PathogenDavid** [comment]
> We were utilizing the `exe` file from the Compiler package, which the MSBuild package doesn't provide.

> @PranavSenthilnathan what's the work-around here again?

This question was never answered. Is there simply no alternative to `tsc.exe` anymore? Do we now have to rely on a separate Node install present on the system?

**Comment by PranavSenthilnathan** [comment]
@PathogenDavid Yes, `tsc.exe` has been removed and Node is required to build. `tsc.exe` basically wrapped a JS runtime with tsc.js. So from TS 3.2+ instead of using that JS runtime in the exe, we're just using node. All the arguments to `tsc.exe` will work with `node.exe tsc.js` (specifically, `tsc.exe <arg1> <arg2> ... <argN>` is the same as `node.exe tsc.js <arg1> <arg2> ... <argN>`).

**Comment by PathogenDavid** [comment]
Can you point me towards whatever used to be responsible for making this wrapped exe?

I was hoping to use this NuGet package for integration of TypeScript into a project which doesn't use Node,. The idea of having a self-contained NuGet package to let builds be reproduced in the future without Node installed as appealing to me, but I'm not super in tune with the JavaScript ecosystem in general so I wouldn't know where to begin on making my own self-contained exe like that. Plan B is to just throw Node and tsc.js into an internal NuGet package, but a self-maintained `tsc.exe` route seems more elegant if it isn't a huge ordeal.
