### ISSUE TITLE
New Website Logo: Acamica

### ISSUE THREAD

**Issue by sebasjm** [microsoft/TypeScript#29688]
Please fill the following out:

- Name: Acamica
- Homepage url: https://www.acamica.com/
- Brand Guidelines/Licensing: The Acamica is a trademark of Acamica. Permission is granted to Microsoft to display the logo on any Microsoft website provided it links to a website operated by Acamica. Like https://www.acamica.com
- Logo: https://resources.acamica.com/acamica.svg

**Comment by orta** [comment]
Hey folks -we're looking at a new website and it's likely that the friends of TypeScript page isn't going to make it to the new site. This is mainly because close to everyone is a friend of TypeScript now and listing folks kinda feels a bit un-inclusive to everyone else. 

So I'm going to close this issue - thanks for posting to apply
