### ISSUE TITLE
TS should support double quotes instead of backticks for string interpolation too

### ISSUE THREAD

**Issue by pke** [Microsoft/TypeScript#2978]
Since single and double quotes are historically the same in JavaScript the ES6/7 standard cannot just use double quotes for string interpolation like CoffeeScript does (for performance reasons). However, the backticks chosen by the ES6 team are horribly difficult to type (even here on GitHub) on non-US keyboards.
So maybe the TS compiler could also perform string interpolation on double quotes, and convert them to backticks for ES6 compatibility?

That would certainly help a lot of programmers with non-US keyboard layouts.

**Comment by DanielRosenwasser** [comment]
I think using backticks was a deliberate decision by the ECMAScript committee in order to avoid breaking changes.

For instance, we have a string formatting system for our diagnostics messages, and parse out portions of the string like `{0}`. So for "Unexpected token {0}", we replace `{0}` with some argument. While it sounds a little silly, it's not completely unheard of that another team would do something similar with `${0}`.

There would also be some design changes for which other users would be left unsatisfied (e.g. "can we allow a substitution expression in a module name?", "can we also make regular strings work on multiple lines?", "can strings with substitution expressions be used as property names, or do you need to use them in computed properties?", and the such).

I am sympathetic to those using non-US keyboard layouts, but I don't think the proposed solution is the correct fix, and the situation is, while also annoying, easily amended by using old-fashioned string concatenation.
