### ISSUE TITLE
Breaking change for default parameters

### ISSUE THREAD

**Issue by Akxe** [Microsoft/TypeScript#29803]
**TypeScript Version:**  3.3.1

**Search Terms:**
Type parameter defaults can only reference previously declared type parameters.

**Code**

```ts
interface INamed {
    name: string;
}

class Person<T extends INamed = T> {
    //  ...
}
```
***Intended use***
I wanted to use `T` as shorthand for `INamed`, because it may get very long and unless you make a separate type variable, there wasn't an easy and clean way to do it.

**Previous behavior:**
***no error***

**Current behavior:**
Error: Type parameter defaults can only reference previously declared type parameters.

**Playground Link:** 
[Demo](https://www.typescriptlang.org/play/#src=interface%20INamed%20%7B%0D%0A%20%20%20%20name%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Person%3CT%20extends%20INamed%20%3D%20T%3E%20%7B%0D%0A%20%20%20%20%2F%2F%20%20...%0D%0A%7D)

**Related Issues:**
Not really found anything...

**Comment by anurbol** [comment]
Your code doesn't make much sense..

**Comment by Akxe** [comment]
But that means that every time you have a generic with default, you may need to define new type variable for it.

To me this was more readable, as to me it was intuitive and clearly told that default is what is written next to it.

**Comment by Akxe** [comment]
I mean, the original behaviour might be told to be bug, and such declared fixed, but to me this would be shame.

**Comment by anurbol** [comment]
I have quite an experience in TS and your code doesn't make sense to me *at all*. It's the same if you write in regular JS something like this:

```js
function foo(param = param) ...
```

**Comment by Akxe** [comment]
I suppose I will miss this "feature", but I think this issue can be closed.

**Comment by c9r** [comment]
FYI, this change breaks a different use case for dependent type parameters, which is to provide bounded contravariance for method arguments.

```typescript
interface Updater<V extends U = Value & U, U = AnyValue> {
  getValue(): V;
  setValue(value: U): V;
}
```

We use this pattern everywhere. It's quite convenient because it allows us to abstract over the fact that some methods may take a supertype of their return type as an argument. We use `Updater<Color, AnyColor>`, `Updater<Angle, AnyAngle>`, etc., when we want to support looser method argument types, but need to ensure that the return type conforms to the argument type (we use this pattern for more than just updaters, and need to be able to recursively feed the return value back into the method).

Where the default type parameters come into play is when `V = U`. Allowing out-of-order bounds in default type parameters allows use to use the shorthand `Updater<string>`, and `Updater<number>`, when the upper and lower type bounds are equivalent. And in the degenerate case, we can simply use `Updater`, with no type arguments, to get a default strong union type, and weak structural type.

Is there a fundamental language problem inherent to supporting out-of-order type parameter defaults? We have 80,000 lines of TypeScript code that uses this pattern pervasively... Our API would suffer significant ergonomic degradation without this ability.

Please consider reverting this change. Thank you.

**Comment by anurbol** [comment]
@c9r You should have paid more attention to what this issue is about

**Comment by jordwest** [comment]
We were also using this to get around the issue with #6230:

```
interface A<a> {
    brand: 'a';
    nested: a;
}

interface B<a> {
    brand: 'b';
    nested: a;
}

type C<a> = A<a> | B<a>;

// Doesn't work in any version, see #6230:
// type D = C<D> | string; // <-- i wish

// Works in TS <= 3.2
type D<T extends D<T> = D<T>> = C<T> | string;
```
