### ISSUE TITLE
--downlevelIteration should work without es2015.iterator.lib.d.ts

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#29812]
See https://github.com/Microsoft/vscode/pull/68121

@jrieken @mjbvz @RyanCavanaugh

**Comment by rbuckton** [comment]
`--downlevelIteration` depends on the existence of `Symbol.iterator` for us to typecheck and evaluate properly. We made the same decision for async generators. You could chose to depend on a third-party shim as long as it provides a `Symbol.iterator` declaration, however we now primarily recommend that such libraries use `/// <reference lib="es2015.symbol.wellknown" />` rather than define it themselves.

**Comment by DanielRosenwasser** [comment]
I don't necessarily remember the context here given that it's been a few months since we discussed it in person. If someone from the VS Code side can refresh my memory that'd be helpful.

**Comment by DanielRosenwasser** [comment]
Oh, I see the relevant portion here: https://github.com/microsoft/vscode/pull/68121#discussion_r254739037

**Comment by DanielRosenwasser** [comment]
I guess the question is, is the intended behavior to only work on arrays and error when something doesn't have a `Symbol.iterator` method? Would that be appropriate?

**Comment by rbuckton** [comment]
Our `__values`, `__read`, and `__spread` helpers do not require `Symbol.iterator`, but use it if it is present. We may have already fixed this, however, as the following compiles without errors currently:

```ts
// @target: es5
// @downleveliteration: true
for (const x of [1, 2, 3]) {}
const y = [...[1, 2, 3]];
function f(...args: any[]) {}
f(...y);
```

**Comment by rbuckton** [comment]
Closing as I cannot seem to reproduce this and it doesn't seem like there's any action to take here.
