### ISSUE TITLE
Query regarding using async await in typescript class method

### ISSUE THREAD

**Issue by rohitghy5** [Microsoft/TypeScript#29929]
"I am trying to use async await in class in typescript in Netbeans IDE but getting error: 
error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.".  

Please help me resolve the issue. I am not aware how to create Promise constructor if that is the only solution. Would be great if you if you can point to any complete example for await async usage in 
class. Also is there any better way for method code synchronization in class that await async.
I read some issues here in github but was not able to understand the solution since did not find them complete.

My class method is:
public async login() {
        await driver.get("https://fuscdrmsmc293-fa-ext.us.oracle.com/fscmUI/faces/FuseWelcome");
        await this.username.sendKeys("cvrqst01");
        await this.password.sendKeys("Welcome1");
        await console.log("Password entered");
        await console.log("username entered");
        await console.log("Report");
        await searchBox.sendKeys('webdriver');
    }

Below is my tscconfig.json file:
{
    "version":"1.5",
    "compilerOptions": {
        "target": "ES5",
        "module": "commonjs",
        "lib": [ "es5", "es2015", "es2015.promise", "dom"],
        // types option has been previously configured
         "types": [
            // add node as an option
            "node",
            "mocha"
         ],
         
         // typeRoots option has been previously configured
         "typeRoots": [
            // add path to @types
            "/home/admin/node-v10.15.0-linux-x64/lib/node_modules/npm/node_modules/@types/"
         ]
    }

**Comment by kitsonk** [comment]
This is not a support forum.

Questions should be asked at [StackOverflow](http://stackoverflow.com/questions/ask?tags=typescript) or on [Gitter.im](https://gitter.im/Microsoft/TypeScript).

**Comment by rohitghy5** [comment]
Had posted question there but no one has answered yet.

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
