### ISSUE TITLE
New Website Logo: TypeScript CodeDOM

### ISSUE THREAD

**Issue by zijianhuang** [microsoft/TypeScript#29953]
Please fill the following out:

- Name: TypeScript CodeDOM
- Homepage url: https://github.com/zijianhuang/webapiclientgen/wiki/TypeScript-CodeDOM
- Brand Guidelines/Licensing: MIT
- Logo: https://raw.githubusercontent.com/zijianhuang/webapiclientgen/master/Doc/icons/TypeScriptCodeDOM.svg

**Comment by orta** [comment]
Hey folks -we're looking at a new website and it's likely that the friends of TypeScript page isn't going to make it to the new site. This is mainly because close to everyone is a friend of TypeScript now and listing folks kinda feels a bit un-inclusive to everyone else. 

So I'm going to close this issue - thanks for posting to apply
