### ISSUE TITLE
Type is not enforced

### ISSUE THREAD

**Issue by arvai** [Microsoft/TypeScript#29951]
Hey Guys,

I have this type and this function: 

```javascript
type IDeliverMessage = (
    dispatch: Dispatch
) => (message: IMessageProps, performerId: number) => void

export const deliverMessage: IDeliverMessage = dispatch => message => {
    dispatch({
        message,
        type: MESSAGE_DELIVERED
    })
}
```

As you can see, we have an outer function, which receives a dispatch, and an inner function, which receives a message object. However a  performerId is also declared in the Type, it passes the tsc compiler.

How can it happen ?

**Comment by dragomirtitian** [comment]
This is the expected behavior (see [docs](https://www.typescriptlang.org/docs/handbook/type-compatibility.html#comparing-two-functions)). A function with fewer parameters is assignable to a function which has more parameters. 

If you think about it, if this were not the case, a lot of JS patterns would not be writable in typescript. Consider the `map` function which expects a callback that can have any number of parameters (`callbackfn: (value: T, index: number, array: number[]) => U`) Because of the way function caompatibility works all below are valid:

```ts

[1].map(v=> v*2);
[1].map((v, index)=> v*index);
[1].map((v, index, arr)=> v*index + arr.length);

```

**Comment by arvai** [comment]
Thank you.
