### ISSUE TITLE
Auxclick event handler has arg with Event interface

### ISSUE THREAD

**Issue by Thisman** [Microsoft/TypeScript#29995]
**TypeScript Version:**  3.3.3
**Code**

```ts
const handler = (event: MouseEvent) => {}
document.addEventListener('click', handler); // OK
document.addEventListener('auxclick', handler); // NOT OK:(
```

**Actual behavior:** throw error 
```
Argument of type '(event: MouseEvent) => void' is not assignable to parameter of type 'EventListenerOrEventListenerObject'.
  Type '(event: MouseEvent) => void' is not assignable to type 'EventListener'.
    Types of parameters 'event' and 'evt' are incompatible.
      Type 'Event' is missing the following properties from type 'MouseEvent': altKey, button, buttons, clientX, and 25 more.
```

**Playground Link:** http://www.typescriptlang.org/play/index.html#src=const%20handler%20%3D%20(e%3A%20MouseEvent)%20%3D>%20%7B%20%7D%3B%0D%0A%0D%0Adocument.addEventListener('click'%2C%20handler)%3B%0D%0Adocument.addEventListener('auxclick'%2C%20handler)%3B
(need to strictFunctionTypes on )

Is this bug or expected behavior? MDN says what auxlick has MouseEvent interface https://developer.mozilla.org/en-US/docs/Web/Events/auxclick

**Comment by dragomirtitian** [comment]
@Thisman  Your playground link is broken

**Comment by Thisman** [comment]
> @Thisman Your playground link is broken(it's just a playground link does not contain the actual code, it should be encoded in the URL)

Update link. For see error need to on strictFunctionTypes option on ( link didn't save that param )

**Comment by sandersn** [comment]
https://html.spec.whatwg.org/multipage/webappapis.html#idl-definitions gives the type as EventHandler, which is why it uses that type in lib.dom.d.ts. 

I noticed that the MDN link you gave doesn't have a link to the spec. Confusingly, the spec links to [a different MDN page](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onauxclick) for GlobalEventHandlers, which in turns links to a *different spec*, for UI Events.

The first spec, which we use right now, specifies `event: Event`. The second spec specifies `event: MouseEvent`. Perhaps the problem is that we need to switch that spec for this type.

@saschanaz Do you know whether HTML - Web application APIs is the right spec for auxclick, or UI Events?

**Comment by saschanaz** [comment]
`EventHandler` itself does not say anything about what event object should be used. We should add that information in `addedTypes.json`. The HTML spec [links to UI Event](https://html.spec.whatwg.org/multipage/webappapis.html#event-handlers-on-elements,-document-objects,-and-window-objects) and per the spec it should use `MouseEvent`.
