### ISSUE TITLE
TSServer high cpu usage

### ISSUE THREAD

**Issue by Alexand3r** [Microsoft/TypeScript#30004]
- VSCode Version: 1.31.1
- OS Version: Kubuntu 18.04

Steps to Reproduce:
These steps reproduce under heavy load:
1. Press Control + Space to trigger Intellisense to autocomplete something(Or any action that triggers a request to TSServer)
2. Cancel the request by moving the cursor somewhere else

I've also tested it with both with trace: verbose and off (thinking it might be just me having "typescript.tsserver.trace": "verbose" on TSServer)

TSServer creates an empty file under /tmp/vscode-typescript/tscancellation-*session*.tmp*LastFileNumber*

When files start to pile up, TSServer starts to lag/freeze, have very long delays in responding requests and making VSCode also unresponsive or slow and causing horrible CPU Spikes.

Removing those files restores VScode's speed and TSServer resolves requests under 200ms

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by mjbvz** [comment]
@sheetalkamat or someone else on the TS team: can you please take a look at the logs to see what may be causing the high cpu usage for the tsserver. I didn't see anything obvious

**Comment by sheetalkamat** [comment]
Seems like we are getting too many invocations for `/home/andrei/.cache/typescript/3.3/node_modules/.staging :: WatchInfo: /home/andrei/.cache/typescript/3.3/node_modules`

We do ignore those but on Linux because node doesn't support recursive directory watcher, we create recursive directory watcher of our own and that might be refreshing too many times.

I think just like how we ignore directories in `node_modules` that start with "." we should ignore them in sys implementation of recursive directory watcher as well.

**Comment by sublimator** [comment]
@sheetalkamat 
I'm still getting high cpu usage from tsserver even in latest TypeScript :(
![image](https://user-images.githubusercontent.com/525211/66812257-bee1a780-ef5c-11e9-9d18-b62002e3c76b.png)

**Comment by sublimator** [comment]
Nevermind, was latest 2.4 series of typescript-eslint
