### ISSUE TITLE
lib.d.ts: interface Array<T> should communicate optional variables

### ISSUE THREAD

**Issue by daltin** [Microsoft/TypeScript#3000]
Issue #2392 mentions this for .filter but it is true for many array callbacks (may also be true throughout the def file for other callbacks). While it is true you can pass less args to the callback, that is not what the definition is telling us in the tooling. The **documentation says in plain words** the callback accepts up to 3 parameters, but the **parameter signature** communicates to the user that the parameters are required:

```
// Doesn't communicate the params are optional
filter(callbackfn: (value: T, index: number, array: T[]) => boolean, thisArg?: any): T[];
// Does communicate the params are optional
filter(callbackfn: (value?: T, index?: number, array?: T[]) => boolean, thisArg?: any): T[];
```

I do understand that all or none of the params can be passed, but why not communicate that in the def file and in the IDE? Isn't that what we are trying to do, communicate via the tooling what can/may be passed rather than just have everyone memorize specific rules?

**Comment by DanielRosenwasser** [comment]
(Congrats on issue #3000!)

It sounds like your intention is to communicate that `filter` takes a function, and it's okay if that function doesn't use all its parameters. 

But I don't think it communicates what you're intending. A parameter marked `?` implies the function can do without the being passed an argument at that position - in other words, the function is *resilient* to having its parameter omitted.

So with your suggestion, this would communicate to others that the callback needs to be okay with getting *no parameters*. Since you can always pass in a function taking fewer parameters, we would type *all* callbacks like this. And if we were actually strict in enforcing this, the only callbacks you could ever pass in would be functions that take no parameters at all.

**Comment by daltin** [comment]
(Thanks for the congrats!)

The callback function is actually resilient to having no parameters passed. I am not sure what you mean by "if we were actually strict in enforcing this". Enforcing optional just means the parameters are optional, it doesn't mean you can never pass in the params, right?

**Comment by RyanCavanaugh** [comment]
There are two ways you might interpret `?` in a signature:

 * You don't have to accept this argument if you don't want to ("*callee*-optional")
 * You don't have to pass this argument if you don't want to ("*caller*-optional")

The fact is that *all* arguments are "callee-optional". You are free to, for example, use a zero-argument function as a callback for an event handler (this is super common and it would be annoying to have to declare dummy arguments).

The other option, "caller-optional", is how `?` is always interpreted. However, because people tend to people make this mistake so often when writing .d.ts files, the type system does not enforce this -- if the types match up, the function is considered a match.

See also this thread: https://typescript.codeplex.com/discussions/428458
