### ISSUE TITLE
New Website Logo: Toss

### ISSUE THREAD

**Issue by HyunSeob** [microsoft/TypeScript#30015]
- Name: Toss
- Homepage url: https://toss.im
- Brand Guidelines/Licensing: N/A
- Logo: https://static.toss.im/web-general/brand/static/logo.svg

Thank you in advance!

**Comment by orta** [comment]
Hey folks -we're looking at a new website and it's likely that the friends of TypeScript page isn't going to make it to the new site. This is mainly because close to everyone is a friend of TypeScript now and listing folks kinda feels a bit un-inclusive to everyone else. 

So I'm going to close this issue - thanks for posting to apply
