### ISSUE TITLE
Language service and dts lint disagree on method return type

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#30031]
**TypeScript Version:**  75101d4b72b94d8158dabb249f9b6f969353110c

**Search Terms:** intersection types, overloading, this

**Code**

```ts
interface I1 {
    F(n: number): this;
}

interface I2 {
    F(n: string): this;
}

type T1 = I1 & I2;

interface T2 extends I1, I2
{
    F(n: number): this;
    F(n: string): this;
}

declare const c1: T1;
// $ExpectType T1
const t1a = c1.F(1); // ERROR: dtslint reports I1
// $ExpectType T1
const t1b = c1.F("1"); // ERROR: dtslint reports I2

declare const c2: T2;
// $ExpectType T2
const t2a = c2.F(2); // Fine
// $ExpectType T2
const t2b = c2.F("2"); // Fine
```

In QuickInfo (in VS Code), the constant types match the `$ExpectType` comments.  However, dtslint reports `I1` and `I2` for `t1a` and `t2a`, respectively.

**Comment by sandersn** [comment]
After some discussion with @amcasey I think that dtslint is correctly reporting what the compiler says. I don't think types aliases have `this` types so `this` will have to come from a member of the intersection.

However, it would be less surprising if `this` types worked uniformly for all types instead of only being available on classes. This would be difficult to write and expensive in action, so I'm not sure it's feasible.

**Comment by amcasey** [comment]
What would/should happen if `I1.F` and `I2.F` had the same signature?

```ts
interface I1 {
    F(n: number): this;
}
interface I2 {
    F(n: number): this;
}

type T = I1 & I2;
declare const c: T;
// $ExpectType T
const x = c.F(1); // LS says T, linter says I1
```

**Comment by RyanCavanaugh** [comment]
This seems to work now
