### ISSUE TITLE
Use in Node/io.js

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#3007]
I want to write TypeScript and run my program using Node/io.js. Obviously, for this to happen, the type annotations will need to be stripped before the program is run.

It's easy enough to do this manually for one file, but for a large dependency graph, I would like a better workflow.

**Comment by DanielRosenwasser** [comment]
Hey @OliverJAsh, I'm not sure whether you mean that you're asking if you can pass more than one file to `tsc` (you can!), but I assume you're asking about how to manage a large TypeScript codebase down the line. Depending on how complex you want your project/build cycle to be, there are different answers to this.

### tsconfig.json

We have a file called **[`tsconfig.json`](https://github.com/Microsoft/TypeScript/wiki/tsconfig.json)** where you specify your dependencies.

Because TypeScript editors also use this to decide your project space when writing code, you may want to have this around anyhow.

### Traditional build tools

You can leverage any traditional build tool you want, especially any in the JS ecosystem. For instance, [Grunt](http://gruntjs.com/), [gulp](http://gulpjs.com/), [Jake](http://jakejs.com/), and more. Just pass your `.ts` and `.d.ts` files to `tsc` as part of a build step, or even use tsconfig.json in your build.

These tools often have helpful TypeScript tooling, such as [grunt-ts](https://www.npmjs.com/package/grunt-ts), [gulp-ts](https://www.npmjs.com/package/gulp-ts), and [Jake](https://www.npmjs.com/package/jake-typescript).

### Imports and reference comments

If you're working with ES6 modules/"external modules", you can simply do 

```TypeScript
import { a, b, c } from "foo/bar/baz"
```

and we should be able to resolve it correctly.

TypeScript files can also more or less "include" each other using reference comments: 

```TypeScript
/// <reference path="../typings/lodash.d.ts" />
```

You can then let `tsc` build up the dependency graph; however, if you choose only this, it makes it hard for anyone who offhandedly wants to see a list of files in your project.

----------------------

Honestly, you can mix and match any of these, and there's no lock in if you choose one over the other. You can always switch later down the line. Does that mostly answer your question?

**Comment by NoelAbrahams** [comment]
> Obviously, for this to happen, the type annotations will need to be stripped before the program is run.

TypeScript compiles into JavaScript.

**Comment by OliverJAsh** [comment]
I want to run my program on-the-fly, without having to manually compile beforehand. Currently my workflow would look something like:

```
# outputs foo.js
tsc foo.ts
node foo.js
```

Traceur has `traceur.require.makeDefault`, which transpiles on-the-fly as you require modules, e.g. https://github.com/OliverJAsh/sbscribe/blob/a3a56c6e51303ef34a8e52146fd6918c8d6d7ad7/scripts/traceur-runner.js#L15

**Comment by basarat** [comment]
> I would like a better workflow.

Atom-TypeScript can compile on save : https://github.com/TypeStrong/atom-typescript#compile-on-save 

>  but for a large dependency graph

Just wanted to show off : https://github.com/TypeStrong/atom-typescript#dependency-view

**Comment by mhegazy** [comment]
@OliverJAsh you use ts.transpile to do that. see this change for more details: https://github.com/ModuleLoader/es6-module-loader/pull/366/files#diff-69fab1d4c3446ceed180e4a3f8a482aeR120

**Comment by OliverJAsh** [comment]
@mhegazy Ah, OK. I think that makes sense. Thank you.
