### ISSUE TITLE
Transpiling "var" to "let" through an option in the projects menu

### ISSUE THREAD

**Issue by Sharpiro** [Microsoft/TypeScript#3008]
I know this is a touchy subject to some.

But i really like typing "var" these days.  Is it unreasonable to put in a request for a menu option that is defaulted to off, that allows for the "var" keyword to be transpiled into an ES6 "let"?  Between auto, var, and now let, it can get a bit annoying.  I'd much prefer to combine let/var since i personally only want to use a "let" style keyword now that it is supported in Typescript, and i'm sure at least a few others feel the same.

**Comment by mhegazy** [comment]
The compile transpilers let to var in non-es6 environments because let is not supported. If you are targeting es6, you already have both, so you can type let or bar everywhere. I find it really strange to have the compiler change one legal declaration to another specially that Var and let have diffrent scoping and binding rules.

**Comment by DickvdBrink** [comment]
I'm thinking this issue should be closed?
