### ISSUE TITLE
#27697 made too many bugs

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#30119]
Made #30118 #30049 #30047

**Revert the buggy commit #27697 or fix!**

**Comment by jack-williams** [comment]
A smaller repro from one of the linked examples.

```ts
type Children =
    | Children.Void
    | Children.Text
    | Children.Collection
    | Children.Record;

namespace Children {
    export type Void = undefined;
    export type Text = string;
    export interface Collection extends ReadonlyArray<El> { }
    export type Record = { [field: string]: El; };
}

interface El<
    C extends Children = Children,
    > {
        children: Relax<C>;
    }

type Relax<C extends Children> = C extends Children.Text ? Children.Text : C;

const a: El = 1 as any as El<Children.Void>; // error
```

The issue here is that variance markers that are marking `C` as invariant. Even though we never end up relating two conditional types, the affect of variance computation makes the assignment illegal. I can definitely see this being an issue, but I'm not sure the right thing to do is to back out #27697. Is it possible to not compute variances in conditional types?

**Comment by RyanCavanaugh** [comment]
Please don't go meta on the bugs.
