### ISSUE TITLE
Type 'number' is not assignable to type 'Timeout'

### ISSUE THREAD

**Issue by pronebird** [Microsoft/TypeScript#30128]
**TypeScript Version:**  3.3.3

**Search Terms:**

**Code**

```ts
var timerId: NodeJS.Timeout = setTimeout(() => {}, 1000)
```

My config:

```
{
  "compilerOptions": {
    "alwaysStrict": true,
    "esModuleInterop": true,
    "jsx": "react",
    "module": "commonjs",
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "outDir": "build",
    "resolveJsonModule": true,
    "rootDirs": [
      "src",
      "assets"
    ],
    "skipLibCheck": true,
    "strict": true,
    "target": "es2017",
    "lib": ["es2017", "dom"],
    "typeRoots": [
      "./types",
      "node_modules/@types"
    ]
  },
  "exclude": [
    "node_modules"
  ],
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx"
  ]
}
```

**Expected behavior:**
No error. I have `@types/node` installed.

**Actual behavior:**
Error.

**Playground Link:** 

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/842

**Comment by RyanCavanaugh** [comment]
You included the DOM typings in your `lib`, so TypeScript thinks you're calling the DOM version of `setTimeout` because it's basically ambiguous given two definitions of it. You can write `global.setTimeout` to disambiguiate.

**Comment by pronebird** [comment]
Thanks @RyanCavanaugh. I guess I'll move on with `global.`. Thanks!

**Comment by yotam707** [comment]
For anyone else having this error what worked for me is adding in the tsconfig.js file:
```
"compilerOptions": {

   ...
   "types": [],
}

```

**Comment by SamHard** [comment]
The compiler is getting confused between `global.setTimeout()` and `window.setTimeout()`.  In our application, we intended to use the browser's setTimeout method, so this resolved the mismatched types:
`var timerId: number = window.setTimeout(() => {}, 1000)`

**Comment by token-cjg** [comment]
`NodeJS.Timeout` is a more general type than `number`.  To work around any type issues here when working purely in node and not in a browser, you can just prepend '+' to your global.setTimeout call, i.e. `myTimeoutId: number = +global.setTimeout(() => {...})`.

This is because `NodeJS.Timeout` uses Symbol.toPrimitive: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/121622b2e60d12c33f57683d931653c9e0a68680/types/node/globals.d.ts#L551 .

More docs on symbol.toPrimitive here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toPrimitive .

**Comment by kirvedx** [comment]
The easiest way I've found to handle this situation is to install all the correct typings packages, and then add all the variants of the types  to your `tsconfig` file:

> node_modules/@material/banner...: Type 'number' is not assignable to type 'Timeout'...

In `.tsconfig`:

```json
{
  ...
  "compilerOptions": {
    "types": [
      "window",
      "global"
    ]
  },
  ...
}
```

Good practice to add `mocha` and `jest` to that list too if you have them installed.

HTH, added my input as my search on something related brought me here.

**Comment by nicolasteofilo** [comment]
> global.setTimeout

global.setTimeout worked in React: ^16.13.1.
thank man 😄

**Comment by twoco** [comment]
I'm on Angular and declared `timerId: number` because in DOM context `setInverval` (and `setTimeout`) returns `number`. The tsconfig libs also includes `dom`. But I get the following error: 

> Type 'Timeout' is not assignable to type 'number'.ts(2322)

Because `setInterval` returns the NodeJS version (`NodeJS.Timeout`). 

```ts
function setInterval(callback: (...args: any[]) => void, ms: number, ...args: any[]): NodeJS.Timeout
```

In my opinion NodeJS should change that. But anyway, I wonder how can TypeScript provide the correct types in this context. A DOM context. How to tell TypeScript that I'm on browser and not on NodeJS.

**Comment by unoexperto** [comment]
Could you folks please advice which types should I use to see .ts file where setInterval/setTimeout return `Timeout` ? Currently IDEA opens `node_modules/typescript/lib/lib.dom.d.ts` for me which also has returning type as `number`.
