### ISSUE TITLE
Expose new line ending option in VS

### ISSUE THREAD

**Issue by paulvanbrenk** [Microsoft/TypeScript#3013]
Expose the line ending option in VS, as discussed in Issue #1693 and PR #2921

**Comment by mhegazy** [comment]
@paulvanbrenk is this about project property pages? 

Is so, and since you brought this up :), can you list the options we need to show? We have not touched the project property pages in a while and we have added a lot of new flags since. It would be great if you can look through the list of flags and see if we need to expose them or not? Or possibly expose all flags.

**Comment by paulvanbrenk** [comment]
Not necessarily, this is mostly about the msbuild properties, since I would argue this is an *advanced* feature.

**Comment by mhegazy** [comment]
Ahh.. If this is the case we need another issue for adding --rootDir, --noEmitHelpers as well as support for --module umd and --module system.

**Comment by paulvanbrenk** [comment]
I'll make a list and update this bug.

**Comment by mhegazy** [comment]
I have the list covered in #3034
