### ISSUE TITLE
Incompatibility between Tuple type and Array type

### ISSUE THREAD

**Issue by FlamesoFF** [Microsoft/TypeScript#30132]
```ts
let a: [number, number];
const b = [1,2];
a = b; // Type 'number[]' is missing the following properties from type '[number, number]': 0, 1ts(2739)
```
Same error with any array lenghs:
```ts
let a: [number, number, number];
const b = [1,2,3];
a = b; // Type 'number[]' is missing the following properties from type '[number, number, number]': 0, 1, 2ts(2739)
```

I can't set array with fixed length. Just why? Why it isn't working? Seems like a bug.

**Comment by RyanCavanaugh** [comment]
`b`'s type is inferred to be `number[]`, not `[number, number]`.

You can use the new `as const` assertion (`[1, 2] as const`) if you want `b`'s type to be inferred differently.

**Comment by FlamesoFF** [comment]
@RyanCavanaugh but it works like that:
```ts
let x: [string, number];
// Initialize it
x = ["hello", 10]; // OK
```
Why can't I do like described above? It's the same.

**Comment by MarcelRusu** [comment]
I assume there are no plans to automatically "cast down" arrays to tuples in obvious cases like this? I've come across this many times before and it left me frustrated, this was before `as const` though so maybe that is a good compromise.

**Comment by FlamesoFF** [comment]
@typescript-bot 
```ts
let x : [number, number] = [1, 2];
let y: number[] = [1,2];
x instanceof Array; // true
y instanceof Array; // true
x.length; // 2
y.length; // 2 
x = y; // Type 'number[]' is missing the following properties from type '[number, number]': 0, 1ts(2739)
```
> 'Working as Intended
Rly? Ok.

**Comment by RyanCavanaugh** [comment]
Yes. Variables in TypeScript have the same read type as write type. This is an intentional decision that makes things more predictable.

Consider if this were allowed - this example illegally prints `3` instead of `2`
```ts
function fn(x: { a: [number, number] }) {
  setTimeout(() => console.log(x.length);
}
const obj = { a: [1, 2] };
fn(obj.a);
obj.a = [1, 2, 3];
```

**Comment by buksy90** [comment]
Why cannot array be typed to tuple first when compared to tuple? (if possible internally). Or some other way?

I have written an user friendly language for my project that gets transpilled to set of calls of javascript functions. And I have multiple implementations of those functions which differ a bit in output.
To make everything compatible, I have interfaces and types of functions written in TS and one unit test of my transpiller transpilles the user friendly language to javascript and then runs ts-node to verify the final code satisfies the functions types. It works very well even with object parameters of functions.
But recently I started using tuples to better describe my functions and since transpilled code is pure javascript and types are inferred the tupple is not working 

```
interface ILocation {
    name: string,
    point: [x: number, y: number],
}

function showPoint(loc: ILocation) {}

// This works well
const l1: ILocation = { name: "l1", point: [1,2] };
showPoint(l1);

// This doesnt work when type is inferred
const l2 = { name: "l1", point: [1,2] };
showPoint(l2);
```
[Here's link to typescript playground](https://www.typescriptlang.org/play?ssl=1&ssc=1&pln=15&pc=15#code/JYOwLgpgTgZghgYwgAgJIBkD2C5mJkZAbwFgAoZS5EOAWwgC5kBnMKUAcwBpyrkAHTKDBMA2gA8mIAK60ARtC7IAnlNkKoAXR5kAvuXIxpIBHgIsAFpgDuABSHgAFABtsTDNlz4QASmLl9MnIAemDkABULYGZka0woAGsY6whnZ3IEAlZkZwBGdywcM0IAXmJqOkZkACI86qVBYTFcrgAmTWRdAG5yZis7BzAXXJ8eoLJQiKiYgBNMCGZwWPiE2IsIQjBlfhRo5FAYaCgIGYyssBzW5DKiCvomWtz6gUHmto7u3v77YRdW0aAA)
