### ISSUE TITLE
Library version 

### ISSUE THREAD

**Issue by nirajkryadav** [Microsoft/TypeScript#30145]
when i transpile my project i got the following error, how can i resolve this
```
node_modules/protractor/built/runner.d.ts:1:23 - error TS4090: Conflicting definitions for 'node' found at 'C:/Users/nikumar2/hello/index_issue/node_modules/protractor/node_modules/@types/node/index.d.ts' and 'C:/Users/nikumar2/hello/index_issue/node_modules/@types/node/index.d.ts'. Consider installing a specific version of this library to resolve the conflict.

1 /// <reference types="node" />
                        ~~~~


Found 1 error.
```

MY node version is

```
node -v
v10.15.1
```

MY npm version

```
npm -v
6.4.1
```

My typescript versoin
```
tsc -v
Version 3.3.3
``` 
protractor version 
```
  "protractor": "^5.4.1",
```

what can be the issue? or what version should I work on?

**Comment by j-oliveras** [comment]
Update `protractor` to 5.4.2. In 5.4.1, they defined `@types/node` version 6 as dependency.

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
