### ISSUE TITLE
Compiler hangs with no output - how to debug?

### ISSUE THREAD

**Issue by lvanhala** [Microsoft/TypeScript#30143]
**TypeScript Version:**  3.4.0-dev.20190228

I have a project that contains references to sub-projects. For some reason, the compiler hangs with no output, and finally crashes with FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory.

I haven't been able to isolate the problem. It is somehow related to importing monocle-ts in sub-project, but it seems very random.

My question is: is there a way to find out what causes the compiler to crash? Can I enable debug output in tsc, or something else?

**Comment by RyanCavanaugh** [comment]
There isn't meaningful debug output generating during phases which typically cause these kinds of crashes.

The best thing to do is to run `node --inspect tsc.js [your commandline]`, attach a debugger, wait until you think it's close to crashing, then break the debugger and capture the call stack along with values of relevant locals. Usually there will be a `node` somewhere in the stack trace that will point you to which line of source is the root cause.
