### ISSUE TITLE
Cannot merge an imported namespace

### ISSUE THREAD

**Issue by crystalfp** [Microsoft/TypeScript#30141]
**TypeScript Version:**  3.4.0-dev.20190227

**Search Terms:** namespace merge

**Prerequisites:**
Using the following `tsconfig.json`
```json
{
  "compilerOptions": {
    "target": "ES2018",
    "lib": ["es2018"],
    "esModuleInterop": true
   }
}
```
**Code**
File **types.d.ts**
```ts
export as namespace lunr;
export = lunr;

declare namespace lunr {
    function multiLanguage(lang1: string, lang2: string): any;
}
```
File **index.ts**
```ts
import lunr from "types";

declare namespace lunr {
    function mytest(): void;
}

lunr.mytest();

declare namespace ex {
    function a(): void
}
declare namespace ex {
    function b(): void
}

ex.a();
ex.b();
```

**Expected behavior:**
No error from both namespaces (lunr and ex) merging. `types.d.ts` contains the relevant parts of  `@types/lunr` type definitions for the lunr package.

**Actual behavior:**
The second merge succeeded, the first one fails.
```
index.ts:2:8 - error TS2440: Import declaration conflicts with local declaration of 'lunr'.

2 import lunr from "types";

Found 1 error.
```
**Playground Link:** 
I don't know how to put a type definition file in Playground.

**Related Issues:** 
No

**Comment by RyanCavanaugh** [comment]
See Module Augmentation under https://www.typescriptlang.org/docs/handbook/declaration-merging.html for how this is intended to be written

**Comment by kevupton** [comment]
I don't think this kind of logic should be up to the user to implement. The compiler should take care of the augmentations, otherwise, things just get messy.
It makes sense for it to be able to do this. 

In my scenario, I am trying to do an enum and namespace merge, however, there are circular dependencies when I create the enum functions to transfer back and forwards between each other.

So to solve the circular dependencies, I have separated the namespace and the enum in two different files. However, I can no longer use the declaration merging because of this.
