### ISSUE TITLE
How could I disable `Object.defineProperty(exports, "__esModule", { value: true });` manually

### ISSUE THREAD

**Issue by taoqf** [microsoft/TypeScript#30166]
**TypeScript Version:**  3.3.3333

**Search Terms:**

https://github.com/Microsoft/TypeScript/issues/2242

**Code**

```ts
// a.ts
export default function a(){
console.log('i am a');
}

// b.ts
export default function b(){
console.log('i am b');
}

// c.ts
export { default as a } from 'a';
export { default as b } from 'b';

// d.ts

import d from './d'; // for some reason I don't want force my team worker use import d = require('d');

d.a();  // now d is undefined cause I am using esModuleInterop flag while compling into js.
```

**Expected behavior:**

log 'i am a'

**Actual behavior:**

d.a is undefined

**Playground Link:** 

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/2242

**Comment by j-oliveras** [comment]
You import usage is not correct and your code has some errors.

**TypeScript Version:** 3.3.3333

I understand that should be like:
```ts
// a.ts
export default function a(){
    console.log('i am a');
}

// b.ts
export default function b(){
    console.log('i am b');
}

// c.ts
export { default as a } from './a';
export { default as b } from './b';

// d.ts
import c from './c';
c.a();
```
tsconfig.json:
```json5
{
  "compilerOptions": {
      "module": "commonjs",
      "target": "esnext",
      "strict": true
  },
  "include": [
      "./*.ts"
  ]
}
```

With that I see an error on file d.ts:
```
d.ts:2:8 - error TS1192: Module '"C:/code/test/c"' has no default export.

2 import d from './c'; // for some reason I don't want force my team worker use import d = require('d');
```

You should change that import to:
```ts
// d.ts
import * as c from './c';
c.a();
```
The reason is that `import c from './c';` is import the default export from the module and name it c (c.ts has no default export). `import * as c from './c';` is import all exports (default excluded) from the module and name it as c.

I made a zip with the sample: [30166.zip](https://github.com/Microsoft/TypeScript/files/2920360/30166.zip). The d.ts file has the proposed code commented.

**Comment by taoqf** [comment]
Add this into tsconfig:
```json
{
...
"esModuleInterop": true,
"allowSyntheticDefaultImports": true,
...
}
```

**Comment by taoqf** [comment]
@j-oliveras
