### ISSUE TITLE
New Website Logo: IT.focus

### ISSUE THREAD

**Issue by Ami777** [microsoft/TypeScript#30174]
Please fill the following out:

- Name: IT.focus
- Homepage url: https://itdotfocus.com
- Brand Guidelines/Licensing: none
- Logo: 

![logo_it_focus](https://user-images.githubusercontent.com/7489790/53669215-a3988500-3c76-11e9-9923-fb20f24cc2af.png)

**Comment by orta** [comment]
Hey folks -we're looking at a new website and it's likely that the friends of TypeScript page isn't going to make it to the new site. This is mainly because close to everyone is a friend of TypeScript now and listing folks kinda feels a bit un-inclusive to everyone else. 

So I'm going to close this issue - thanks for posting to apply
