### ISSUE TITLE
Use the operator '!' to cast a type into a more specific union type

### ISSUE THREAD

**Issue by paleo** [Microsoft/TypeScript#30237]
## Search Terms

- union exclamation mark
- union non null operator

## Suggestion

The operator `!` (non-null assertion operator) could be used to cast a type (like `string`) into a more specific union type (like `"a" | "b"`).

## Examples

```
function f1(a: "a" | "b") {
}
const a: string = "a" // we get this string value from something less typed.
f1(a) // Error: Argument of type 'string' is not assignable to parameter '"a" | "b"'
f1(a!) // OK
```

Or:

```
const colors = {
  blue: "#00f",
  red: "#f00",
}
type Color = keyof typeof colors // "blue" | "red"
let list: Color[]
list = Object.keys(colors) // Error: type 'string[]' is not assignable to '("blue" | "red")[]'
list = Object.keys(colors)! // OK
```

## Checklist

I think my suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by AlCalzone** [comment]
So, how do you know without looking at the inferred type if `a!` means "cast this type to the union" or "this variable is not undefined"?

**Comment by paleo** [comment]
> So, how do you know without looking at the inferred type if `a!` means "cast this type to the union" or "this variable is not undefined"?

Both.

For me, these two use cases seem close. The exclamation point is a non intrusive way to silence the compiler, so we use it as little as possible. I am proposing to broaden its scope.

**Comment by krryan** [comment]
A tuple is `['a', 'b']`, the type `'a' | 'b'` is a _union_. So if nothing else, the suggestion has to be corrected to use the right terminology.

Anyway, I don’t think overloading the meaning of `!` is a good idea. “Silencing the compiler” _should be_ an intrusive, glaring operation—that’s why you use casting to do it. Casting is a signal to the programmer that something unsafe is going on. The `!` is too, but it’s much smaller and easier to miss (particularly since `!a` means something entirely different and is usually perfectly safe). Actually, for that reason, our project has a lint rule banning the `!` postfix operator (which can be overridden with a comment but that makes it clear to anyone coming by that something fishy is going on).

So I don’t really like the `!` in general, but at least it means one specific thing. Overloading it just makes it more unclear and easier to misunderstand what’s going on. That’s bad for readability, and anything that “silences the compiler” needs to be as readable as possible, because misreading it is also unsafe.

**Comment by paleo** [comment]
> A tuple is `['a', 'b']`, the type `'a' | 'b'` is a union. So if nothing else, the suggestion has to be corrected to use the right terminology.

I edited. Thank you.

**Comment by RyanCavanaugh** [comment]
Alternative syntax proposal for #2876
