### ISSUE TITLE
Literal enums, when used, are narrowed down to actual value type

### ISSUE THREAD

**Issue by ducin** [microsoft/TypeScript#30310]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:** literal narrow, literal narrowing

**Code**

```ts
type Currency = 'USD' | 'GBP' | 'EUR' | 'PLN'
let myCurrency: Currency = 'USD'

let myPayment = {
  amount: 100,
  currency: myCurrency
}

myPayment.currency = 'GBP' // throws: Type '"GBP"' is not assignable to type '"USD"'.ts(2322)
```

**Expected behavior:**

expect `myPayment.currency` to be of type `Currency`, just like the `myCurrency` variable used to construct the `myPayment`.

**Actual behavior:**

`myPayment.currency` is narrowed down to the actual value of the `myCurrency` variable (`"USD"` in above snippet).

I can see this works exactly the same way for `myCurrency` being a var/let/const variables. It also works the same way for string literal enums, number literal enums, etc. Also, the same behavior appears when the enum value is used to create a property in a new object, as well as when used to create a new variable (e.g. `let anotherCurrency = myCurrency // anotherCurrency is "USD", not Currency`)

If there is some reasoning behind it, I couldn't find it and would be nice to extend the docs (I can help with it).

**Playground Link:** [link](http://www.typescriptlang.org/play/#src=type%20Currency%20%3D%20'USD'%20%7C%20'GBP'%20%7C%20'EUR'%20%7C%20'PLN'%0D%0Alet%20myCurrency%3A%20Currency%20%3D%20'USD'%0D%0A%0D%0Alet%20myPayment%20%3D%20%7B%0D%0A%20%20amount%3A%20100%2C%0D%0A%20%20currency%3A%20myCurrency%0D%0A%7D%0D%0A%0D%0AmyPayment.currency%20%3D%20'GBP'%20%2F%2F%20throws%3A%20Type%20'%22GBP%22'%20is%20not%20assignable%20to%20type%20'%22USD%22'.ts(2322))

**Comment by RyanCavanaugh** [comment]
The widening / control flow rules are hard to write down in a way that covers all the cases.

In this case, the assumption is that maintaining the literal value is a Good Thing because `myPayment` might be trying to assign into a discriminated union.

**Comment by karol-majewski** [comment]
@RyanCavanaugh Thank you for your answer. I do understand where this is coming from. At the same time, wouldn't you agree this behavior contributes to the increasing confusion around how type literals are narrowed/widened?

As a user, when I deliberately opt-out from narrowing to `"USD"` by using an explicit type definition wider than `"USD"`:

```ts
let myCurrency: any = 'USD'
```

or

```ts
let myCurrency: string = 'USD'
```

I would expect consistent behavior for this one, for `Currency` is also wider than `"USD"`.

```ts
let myCurrency: Currency = 'USD'
```

However, that's not what happens. `"USD"` is treated as a type literal when it's assigned.

What is your opinion on that?

**Comment by RyanCavanaugh** [comment]
Consistency is an arrow that points in many directions.

The motivating example is that code like this *should* typecheck:
```ts
function usdToGbp(amt: { amount: number, currency: "USD" }) {
  return amt.amount * 0.76;
}

type Currency = 'USD' | 'GBP' | 'EUR' | 'PLN'

let myCurrency: Currency = 'USD'
let myPayment = {
  amount: 100,
  currency: myCurrency
}
// no good reason to reject this call, arguably
const gbp = usdToGbp(myPayment);
```

In a super ideal world `myPayment` would get a control-flow type (for *reading*) of `{ amount: 100, currency: "USD" }` and a *write* type of `{ amount: number, currency: Currency }`, but we don't distinguish read/write like that. Whether that's a net simplification or not is just another level of the problem here: having more code that "just works" is "simple", but so is having rules you can easily write down.

**Comment by karol-majewski** [comment]
@RyanCavanaugh Thank you, that's a good explanation.

**Comment by OliverJAsh** [comment]
@RyanCavanaugh Are there any plans to show this information in IDEs/VS Code, e.g. when hovering over a value to see its type?

I just ran into this:

``` ts
type MyUnion<T> = (() => T) | T;

const value1: MyUnion<{ foo: number }> = { foo: 1 };
// No type error
value1.foo;

const value2: MyUnion<{ foo: number }> = 1 as any;
// Type error
value2.foo;

declare const value3: MyUnion<{ foo: number }>
// Type error
value3.foo;
```

I expected all values to be treated and behave the same, because when I hover to see their types, VS Code shows the same type for all of them. But really, TS has a bit more information, which isn't obvious until you start digging in TypeScript issues to try and find a rationale.

OTOH, I can imagine this would be an awkward thing to explain, if it was shown in the hover card. 🤷‍♂️
