### ISSUE TITLE
Intersection Types  is code  error

### ISSUE THREAD

**Issue by renbuzhudek** [Microsoft/TypeScript#30335]
```ts
function extend<T, U>(first: T, second: U): T & U {
    let result = <T & U>{};
    for (let id in first) {
        (<any>result)[id] = (<any>first)[id];
    }
    for (let id in second) {
        if (!result.hasOwnProperty(id)) {
            (<any>result)[id] = (<any>second)[id];
        }
    }
    return result;
}

class Person {
    constructor(public name: string) { }
}
interface Loggable {
    log(): void;
}
class ConsoleLogger implements Loggable {
    log() {
        // ...
    }
}
var jim = extend(new Person("Jim"), new ConsoleLogger());
var n = jim.name;
jim.log();
```
the lasted code was error ;
this  object jim don't have property log  ,log  as in  the class's prototype .because the function extend return object  don't have the property ,for loop check hasOwnProperty can't loop  property in the prototype

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
