### ISSUE TITLE
Spurious "Invalid use of 'eval'" error

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#3036]
In 1.5 beta the following is an error

```typescript
    class Foo {

        foo() {

            // Error: Invalid use of 'eval'. Class definitions are automatically in strict mode.
            var eval = true;

        }
    }
```

**Comment by mhegazy** [comment]
This is a change in 1.5 to align with the [ES6 spec](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-strict-mode-code) with function declarations and expressions are implicitly parsed in strict mode. See #2465 for more details.

**Comment by NoelAbrahams** [comment]
Does it not matter that eval is just a var?

**Comment by mhegazy** [comment]
From section 14.1.2 Static Semantics: Early Errors:

> If the source code matching this production is strict code, it is a Syntax Error if BindingIdentifier is the IdentifierName `eval` or the IdentifierName `arguments`.

The rational, and this is my understanding, `eval` and `arguments` are special in the language, yet they are treated like normal names. that can easily lead to ppl overriding them either by mistake or by design. The committee wanted to prohibit that, so it became part of the strict mode, along with the use of `this` in global scope, use of future reserved words as identifiers (which makes it harder to add new keywords without breaking existing code), use of arguments.caller, use of undeclared variables ...etc..

**Comment by NoelAbrahams** [comment]
Ah, okay, thanks.
