### ISSUE TITLE
Shouldn't be able to access bogus properties on `globalThis` even under lax settings

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#30388]
We determined it should be permissible to access bogus members on `this` outside of `noImplicitAny`. However, I would assert that this is for backward-compatibility reasons.

Something that I just noticed is that when `noImplicitAny` is off, we allow you to access any property on `globalThis`.

```ts
globalThis.wargarbl;
globalThis.dsfargeg;
```

Both of these should be errors in TypeScript regardless of strictness settings.

@sandersn @RyanCavanaugh

**Comment by sandersn** [comment]
No. `globalThis` should behave the same as `this`, because people will want to do (1) unsafe things or (2) counter-factual things with it, neither of which the compiler understands. This should be allowed with noImplicitAny off.

In other words, as soon as this ships in browsers, people will want to use it in place of `self`, `this`, `window`, etc since it's a guaranteed way to access the global object.

eg

```ts
// counter-factual
if (globalThis.blah) {
    export(globalThis.blah, true)
}
// unsafe
init(globalThis.trustMeItsThere, global.somebodyElsePutItThere);
```

**Comment by DanielRosenwasser** [comment]
Is there any new code that uses `globalThis` that's guiding our decision? Would the behavior suggested in this issue keep the design space open such that we could revert to the current behavior?

**Comment by sandersn** [comment]
1. No, old code based on `window` and `this`, which I think that authors will think can be find/replaced with `globalThis`.
2. Being stricter would keep the design space open, but at the cost of preventing widespread usage as in (1). The question is how breaky any future improvements to knowledge about global usage would be to `globalThis`. I think future improvements will be much like top-level `this: typeof globalThis`, in that it only finds good bugs.
