### ISSUE TITLE
Allow javascript (or typescript) config file

### ISSUE THREAD

**Issue by alexmiddeleer** [microsoft/TypeScript#30400]
## Suggestion

I suggest allowing a tsconfig.js or tsconfig.ts as an optional alternative to tsconfig.json.

## Use Cases

What do you want to use this for? Primarily to add comments to the tsconfig file. 
What shortcomings exist with current approaches? JSON does not allow comments. You can't even hack in comments by adding fake fields like `"_explanationOfTypeRoots"`, as the build complains about unknown compiler options and stops.

## Examples

Many tools and frameworks allow javascript config files. Jest, for example. `jest --init` produces a heavily commented config file, which is very useful for beginners.

**Comment by j-oliveras** [comment]
> What do you want to use this for? Primarily to add comments to the tsconfig file.
Did you know that you can add comments to `tsconfig.json`?

Try it with `tsc --init`, that produces a heavily commented `tsconfig.json` file.

**Comment by alexmiddeleer** [comment]
Oh, nice! I was under the impression that comments were not allowed in JSON, but it makes sense that someone would write a parser that allows them. Thank you for your response, I am closing the issue because I no longer think this feature is necessary.

**Comment by paxperscientiam** [comment]
@alexmiddeleer No, YOU are right -- JavaScript style comments aren't allowed in JSON; `tsc --init` produces an invalid JSON file. The parser, of course, is permissive.

@msftgits should consider an alternative format for autogenerated config files. This could be solved easily by allowing `tsconfig.yaml`, `tsconfig.js`, or `tsconfig.ts` while continuing to support tsconfig.json in perpetuity.

**Comment by alexmiddeleer** [comment]
I agree that more config options would be ideal. But I’m guessing the core team needs to focus on higher priority items. Maybe this would be a good first contribution for someone new.

**Comment by RyanCavanaugh** [comment]
This format is known as [JSON5](https://json5.org)

> EDIT: I'm guessing the parser just interprets the content of tsconfig.json as JavaScript

JSON is a different top-level production because the initial `{` indicates an object, not a statement block.

We are not accepting PRs to turn config into an executable thing. This opens up an enormous can of worms (is it safe to run this? what dependencies does the config file have? what does the config file assume about its environment?) that we'd prefer remain closed.

**Comment by dradetsky** [comment]
@RyanCavanaugh you said

> We are not accepting PRs to turn config into an executable thing.

Would you accept a PR to support _only_ yaml? Or for that matter, other non-executable formats (e.g. toml, ini, etc, but I'm only interested in yaml).

**Comment by CEbbinghaus** [comment]
> We are not accepting PRs to turn config into an executable thing. This opens up an enormous can of worms (is it safe to run this? what dependencies does the config file have? what does the config file assume about its environment?) that we'd prefer remain closed.

This makes little sense to me when so many other JS libraries support them. 

#39441 names a few but there are plenty more that all allow this behaviour. If every one of them had a discussion on the same security concerns, then wouldn't looking through their discussions yield the information needed to implement it in a safe and responsible fashion?

**Comment by s0ber** [comment]
One could always generate the config dynamically. It just makes it harder to get the job done when this is forbidden. So yeah, it’d be REALLY nice to have this feature.

**Comment by AndreiSoroka** [comment]
What needs to be done to convince developers? For them to add support tsconfig.js? @RyanCavanaugh

**Comment by paulshryock** [comment]
This is a pretty basic feature which would be really nice to have.

**Comment by xuyanzhuqing** [comment]
> Oh, nice! I was under the impression that comments were not allowed in JSON, but it makes sense that someone would write a parser that allows them. Thank you for your response, I am closing the issue because I no longer think this feature is necessary.

I think at lease the developer could have the chooise, not just be accept the " I no longer think this feature is necessary" , as far as I can see, I am trying to use git-submodule for my project, it means at lease I have tow or more projects to be located in one root folder,  I just want to dynamicly modifiy the "compilerOptions.path", but it is impossible, it makes me feel bad

**Comment by AndreiSoroka** [comment]
@RyanCavanaugh, can you give any solution or comment?

**Comment by AndreiSoroka** [comment]
@RyanCavanaugh please, don't ignore us

**Comment by CEbbinghaus** [comment]
Should @alexmiddeleer reopen the issue and we focus this on the JS config to dynamically edit properties within the `tsconfig` at compile time, or do we leave this closed as it was specifically about comments within the JSON and open a new issue to focus on the dynamic aspect?

**Comment by dandonahoe** [comment]
Please leave an explanation about why the issue was closed. If this can't be achieved for some reason, at least explain so we can drop it.

This is a big thorn in decal projects.

**Comment by alexmiddeleer** [comment]
I am reopening since this has so much interest. I closed it initially out of respect for the maintainer’s statements that they didn’t want to support it.

**Comment by alexmiddeleer** [comment]
Though I have some misgivings about issue resurrection and think a fresh issue might be better to make the history less muddy. This one’s initial use case turned out to be solved already.

**Comment by CEbbinghaus** [comment]
So in one of the other issues #30751, there is a reference to an npm package that implements some of this behavior already: [tsconfig.js](https://www.npmjs.com/package/tsconfig.js). As good as it is that there exists an alternative, it essentially functions as a generator that you feed a js file into and a JSON file comes out. 

In the readme for that project is also mentioned an excerpt from the [Design Meeting Notes, 9/28/2018](https://github.com/microsoft/TypeScript/issues/27486)
> * What about tsconfig.js?
>	* Nooooooooooooooooooooooooooooo

Which I feel sums up the attitude towards this suggestion. With very vague hard waving we are assured that it would be too complicated or too big of a security concern.

If any concrete concerns exist then those can be addressed, If it's just feeling uncomfortable with the idea of a js config, then the existence of `webpack.config.js, vite.config.js, .eslintrc.js` and many other config files should help reassure that this is a common and safe practice. I mean even the [Gulpfile.js](https://github.com/microsoft/TypeScript/blob/main/Gulpfile.js) in this very project shows that having your configuration as an interpreted js file is sometimes necessary.

Most other build tools use executable configurations since they allow for more reuse and flexibility, so I am having a hard time justifying how TypeScript is different from any of the other build tools that all support js configurations.

**Comment by simonpai** [comment]
Somehow the npm package mentioned above didn't work for me. I came up with a stupid yet simple solution:

1. Write a node script to output a `tsconfig.json` file by evaluating your `tsconfig.js`.
2. Add the above step into your build process.
3. Optionally add `tsconfig.json` to your `.gitignore`.

See the [gist](https://gist.github.com/simonpai/881ca35d7e32c39bae4f82bd95125b62) for code examples. I hope this helps.

**Comment by qhantom** [comment]
> Somehow the npm package mentioned above didn't work for me. I came up with a stupid yet simple solution:
> 
> 1. Write a node script to output a `tsconfig.json` file by evaluating your `tsconfig.js`.
> 2. Add the above step into your build process.
> 3. Optionally add `tsconfig.json` to your `.gitignore`.
> 
> See the [gist](https://gist.github.com/simonpai/881ca35d7e32c39bae4f82bd95125b62) for code examples. I hope this helps.

Thanks @simonpai that helped a lot!

**Comment by AndreiSoroka** [comment]
@qhantom @simonpai but anyway it is a workaround 😞 

I don't understand. How many people should highlight the problem? No any comment from Microsoft developers, they just ignore the current topic

**Comment by CEbbinghaus** [comment]
for anyone wondering the best way to ensure that these topics get seen & taken seriously is to upvote the original comment that started the issue. Doing so bumps the issue further up the list of things for the TS team to tackle. So anyone wanting to see this added should upvote & encourage others that want the same functionality to do the same.

**Comment by Tofandel** [comment]
Seeing that babel, eslint, tailwind, vite and so many more libs allow `.js` config files as well as `.json`, it would make sense to allow it as well, because though it allows a project with a malware ts config file to run code when running `tsc` , first you are running a build command already which has so many more options to execute code than the tsconfig so you should already never do that in an untrusted project, it's even possible on running `npm install` on the project already so it's a non issue

The real benefit would allow for much more flexible configuration, comments is just one small added benefit

Mainly it would allow the config to contain functions, which could be very useful for plugins, it would also allow export and import, as well as a more flexible composable approach than what currently exists

**Comment by kf6kjg** [comment]
How does a bot make a judgment call? Especially for a feature that is not especially complex and has indeed had recent activity? I say reopen the ticket, there's design work to do by humans.

**Comment by Schweinepriester** [comment]
@RyanCavanaugh: @typescript-bot is misbehaving, please reopen this issue.

**Comment by o-alexandrov** [comment]
JavaScript `tsconfig` file is useful more than ever, due to the relatively new change in the behavior of ESLint + TypeScript parser.
To avoid [a bug related to ESLint & tsconfig included files](https://stackoverflow.com/q/74413483/4122857), a developer might want to reuse included & excluded directives, instead of hardcoding them.
- one workaround is to import a tsconfig.json into ESLint config and reuse the directives, but since `tsconfig` is `json5` (json w/ comments), the import involves an extra `json5` library

**Comment by cmcnicholas** [comment]
This really needs to be re-assessed, we have large monorepo's, a hundred or so `tsconfig.json` with repeated content due to merging strategies when using `extends` which don't satisfy all the needs of how merging should happen. `tsconfig.json` is a thorn in our side for maintenance.

**Comment by silverwind** [comment]
https://github.com/microsoft/TypeScript/issues/57486 highlights the need for this. It tries to invent complex syntax for merging/extending when it could just be done by the user in a code config file.

**Comment by eXory2024** [comment]
Please make this happen, other tools are using dynamic configs too so I can't be that big of a problem.

Also, if you are going to use a dynamic config it's your responsibility to make that code not do stupid things.

**Comment by kerryj89** [comment]
I don't see a good argument against this.  Simple json configs are nice (I'd prefer it if it works for my use case), but your simple configs doesn't allow for merging which is a pain in a world where monorepos are only gaining popularity.  Why not let users with more complex setups handle these ambiguities (which can often harbor on opinions)?  Then you'll make everyone happy.  You can still steer towards the simple json config in your docs, but if you have no plan on making tsconfig.json easier to use with monorepos (which might only make them more convoluted), then I hope you reconsider allowing js for more advanced use cases.  Just my 2c - thanks!

**Comment by DanhezCode** [comment]
now in 2026 ts.config.ts is a good standar

**Comment by irfanstract** [comment]
I'd ask for extending `tsconfig`'s JSONC with some extra stuff, like `const` variables and restricted methods (`map`, `flatMap`, `filter`, `toSorted`, and friends).
