### ISSUE TITLE
Why Type 'string' is not assignable to type 'T'.

### ISSUE THREAD

**Issue by wuchengyang** [Microsoft/TypeScript#30496]
sorry, I am a newbie on typescript.
The problem was below:

```
type Test = <T>(r: object) => T;
const test: Test = (r: object) => r.toString();
```

but i meet a error: 
TS2322: Type '(r: object) => string' is not assignable to type 'Test'.   Type 'string' is not assignable to type 'T'

I spent much time to solve this problem and google a lot, but i can not get it also. 
Thank u very much.

**Comment by krryan** [comment]
Questions don’t really go here; you should ask questions on Stack Overflow.

But anyway, it’s because `Test` requires that the function assigned to it be generic, able to take _use_ `T`. It should be possible to call `test<number>(foo)` and get a `number` out of it. `r => r.toString()` will never return a number.

What you probably meant to do is `type Test<T> = (r: object) => T;` and then `test: Test<string> = (r: object) => r.toString();`. Here, `Test` is a generic type, instead of it referring to a generic function, so you can specify the type when you create `test`, and `test` only has to handle that one type.

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!

**Comment by wuchengyang** [comment]
@RyanCavanaugh Thanks, I am so sorry for this. anyway, Thank u very much.
@krryan Thank u very much, I got it. Thank u.
