### ISSUE TITLE
ramda still broken on ts@next

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#30499]
From: https://typescript.visualstudio.com/TypeScript/_build/results?buildId=25552

**Code**

```ts
declare function prop<P extends string>(p: P): <T>(obj: Record<P, T>) => T;
declare function indexBy<T>(fn: (a: T) => string): (list: ReadonlyArray<T>) => { [key: string]: T };
const a2 = indexBy(prop("id"))([{ id: 'a', p: 1 }, { id: 'b', p: 2 }]);
```

**Expected behavior:**
No error on `prop` call, and indexBy's `T=Record<"id", string>`

**Actual behavior:**
Error on `prop` call: 

`Argument of type '<T>(obj: Record<"id", T>) => T' is not assignable to parameter of type '(a: Record<"id", T>) => string'.`

Two red herrings:
1. ramda's actual code has overloads, but that doesn't interfere here.
2. A simpler version:

```ts
declare function prop<P extends string>(p: P): <T>(obj: Record<P, T>) => T;
declare function indexBy<T>(fn: (a: T) => string): void;
const a2 = indexBy(prop("id"))
```

has a different error in the call to prop, but that's because indexBy infers `T={}` and then can't assign `{} ==> Record<"id", string>`. That might be related, but probably not.

**Comment by ahejlsberg** [comment]
This is working as intended (but perhaps a design limitation). See @tycho01's comment [here](https://github.com/Microsoft/TypeScript/pull/30215#issuecomment-470255416).

Reasoning: The `prop("id")` argument has type `<T>(obj: Record<"id", T>) => T`. The argument is passed to a parameter of type `(a: U) => string`, where `U` is a type variable for which we're performing type inference. Thus we infer `U` to have type `Record<"id", T>` and promote `T` to become a type parameter on the function type result of `indexBy`. Then we check that the argument is assignable to the instantiated parameter type `(a: Record<"id", T>) => string` and discover that it isn't.

In an ideal world with complete unification we would infer `U = Record<"id", T>` and `T = string` (inferences in _both_ directions at the same time) which would reduce to `U = Record<"id", string>`. But this type of unification is beyond what our current algorithm can do.

**Comment by weswigham** [comment]
@ahejlsberg the error message says source `<T>(obj: Record<"id", T>) => T` is not assignable to target `(a: Record<"id", T>) => string` - were the source instantiated in the context of the target before comparison began, I would think the assignment would be able to succeed, as the free type variable in the source can be inferred as `string` from the return type, which, upon instantiation, could then provide an inference for `T` in the target when it flows back into the parameter. Instead what seems to be happening is that the parameter is also instatiated in the context of the target since we do both simultaneously - maybe our "instantiate the signature in the context of the target" logic could separate return type instantation and inference and parameter type instantation and inference, similarly to how we split  up return type and parameter inference for top level call resolution?

**Comment by sandersn** [comment]
Closing for now since I changed ramda on DT to expect this error.
