### ISSUE TITLE
Cannot use `typeof` on an empty module

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#3053]
Hi, 

TS: 1.4/1.5

In the following, the compiler issues an error on the last line:

```typescript
module foo {
	
	export module bar {
		export class F { }
	}
	
	export module empty {
	}
}

var x: typeof foo.bar; // okay
var y: typeof foo.empty; // Property empty does not exist on type 'typeof foo'
```

This has turned out to be a problem for the case when a module is defined across multiple files. For certain references the module will be empty, as it is initialised in a different context.

Why do we have no error for `bar` but an error for `empty`?

**Comment by RyanCavanaugh** [comment]
This is the difference between an *instantiated* module (one that has at least one value, or executable code, in it) and an *uninstantiated* module (which only has types or other uninstantiated modules in it).

It's meaningless to say `typeof empty` because there is no value named `empty`. At the point that you get this error, `typeof empty`, if it existed, would be `{}`, so you should write that instead.

If you want to make `empty` instantiated for some workaround reason, you can place a `var dummy;` in it to force it to be instantiated.

> This has turned out to be a problem for the case when a module is defined across multiple files

Can you clarify this? If the compiler can't see those other files, it's meaningless to write `typeof empty`; if it can, you shouldn't get this error.

**Comment by NoelAbrahams** [comment]
@RyanCavanaugh,

The use case is to capture the shape of an existing module and to ensure that we get a compilation error if the shape of the original module changes:

```typescript
// Original
module foo {
    export module empty {
    }
}

// Copy
interface Copy {
    foo: {
       empty: typeof foo.empty;
   }
}

```

> At the point that you get this error, typeof empty, if it existed, would be {}, so you should write that instead

That's a rather strange argument. What if someone were to add a type to the empty module at a later stage? We'd have to go change all the references.

**Comment by mhegazy** [comment]
looks like #420 would address the underlying issue.
