### ISSUE TITLE
Recognize type definitions in ctor-like functions

### ISSUE THREAD

**Issue by jrieken** [Microsoft/TypeScript#3056]
You will encounter the pattern below very often in the wild. Despite TypeScript having classes as a valid replacement, this should be support IMO, especially when migration a code base or when looking at plain JS code.

```
function X() {
       this.foo = "123";
};

var y = new X();
y.foo; //should be known
```

**Comment by danquirk** [comment]
There're definitely a couple other bugs that cover this suggestion already. @RyanCavanaugh and I have talked about this recently as far as exactly what supporting it would look like. Even in a class context we will potentially want to recognize this pattern as JS users will be migrating code like above as well as classes with actual constructors but no type information. A set of assignments to this.<expression> (they need not be contiguous) could be understood to define an inferred shape for the type as long as there are no instance fields defined (since at that point you'd have already opted into TypeScript syntax and should finish the job by describing the fields that will be assigned via this.<expression> in the constructor).

**Comment by mhegazy** [comment]
//CC: @RyanCavanaugh

**Comment by billti** [comment]
This is done for JavaScript. I'm not sure this is something we want to entertain for TypeScript however. @ahejlsberg ? If not, we should close this.

**Comment by mhegazy** [comment]
We have discussed this in a previous design meeting, and the conclusion was not to introduce another way of defining properties, specially since the committee is looking into property declarations.
