### ISSUE TITLE
TS specifies the parameter type of the callback function with generics, and errors when calling the callback function

### ISSUE THREAD

**Issue by qa1057** [Microsoft/TypeScript#30560]
#TS specifies the parameter type of the callback function with generics, and errors when calling the callback function

     function addIndex<U = string>(fn?: (rest?: U) => any) {
        # Call function error reporting: parameter of type "123" cannot be assigned to parameter of type "U"
        fn("123") 
    }
    addIndex((rest?: string) => {
    
    })

#If the return callback function is called correctly, no error will be reported

     function addIndex<U = string>(fn?: (rest?: U) => any) {
         return fn
    }
    #This way the call will not report errors
    addIndex((rest?: string) => { })("123") 

#What can we do by type checking and calling callback functions internally?
#Who knows why this is the case? Thank you

**Comment by MartinJohns** [comment]
In the first example the type argument `U` can be an arbitrary type. It's not legal to call the function passing `"123"` because the compiler can't ensure that the type of `"123"` is compatible to the arbitrary type `U `. What do you think would happen if you call `addIndex<number>(...)`?

In the second example the type of `U` is inferred to be `string`, based on the parameter you pass in, so the return type of your `addIndex` is inferred to be a function accepting a `string` and thus you can call the function.

No bug, all as expected, all logical.

**Comment by qa1057** [comment]
> 在第一个示例中，type参数`U`可以是任意类型。调用函数传递`"123"`是不合法的，因为编译器无法确保类型`"123"`与任意类型兼容`U `。如果你打电话`addIndex<number>(...)`怎么想？
> 
> 在第二个示例`U`中`string`，根据您传入的参数`addIndex`推断出类型，因此您的返回类型被推断为接受a的函数`string`，因此您可以调用该函数。
> 
> 没有任何错误，一切都符合预期

So what's a good solution?

**Comment by tadhgmister** [comment]
Not clear what your intent is but if `U` is always going to be a string or subset, you need to specify a constraint on U:

```
 function addIndex<U extends string>(fn?: (rest?: U) => any) {
    fn("123") 
}
```

This way U has to be `string` or something assignable to string, like `"A" | "B"`, still not sure what your intent is as the use of a generic argument doesn't make a lot of sense here if you only expect it to be a string.
