### ISSUE TITLE
New Website Logo: Zebra BI

### ISSUE THREAD

**Issue by MitjaBezensek** [microsoft/TypeScript#30575]
- Name: Zebra BI
- Homepage url: https://zebrabi.com/pbi
- Brand Guidelines/Licensing: none
- Logo: https://zebrabi.com/wp-content/uploads/2019/02/zebra-bi-frame.png

**Comment by orta** [comment]
Hey folks -we're looking at a new website and it's likely that the friends of TypeScript page isn't going to make it to the new site. This is mainly because close to everyone is a friend of TypeScript now and listing folks kinda feels a bit un-inclusive to everyone else. 

So I'm going to close this issue - thanks for posting to apply
