### ISSUE TITLE
allow constructing URLSearchParams directly from FormData

### ISSUE THREAD

**Issue by thatbudakguy** [microsoft/TypeScript#30584]
**TypeScript Version:**  3.4.0-dev.20190323

**Search Terms:**
URLSearchParams, FormData

**Code**

```ts
let form = document.createElement('form')
console.log(new URLSearchParams(new FormData(form)))
```

**Expected behavior:**
compilation succeeds and an (empty) `URLSearchParams` instance is constructed using the provided `FormData`. The above code runs without issue on Chrome 73 and Firefox 67 for me.

**Actual behavior:**
compilation fails because `URLSearchParams` doesn't explicitly allow an argument of type `FormData` as input to the constructor.
```
Argument of type 'FormData' is not assignable to parameter of type 'string | Record<string, string> | URLSearchParams | string[][]'.
  Property 'sort' is missing in type 'FormData' but required in type 'URLSearchParams'.
```

**Playground Link:** 
[link](https://www.typescriptlang.org/play/#src=let%20form%20%3D%20document.createElement('form')%0D%0Aconsole.log(new%20URLSearchParams(new%20FormData(form))))

**Related Issues:** 
#12517
#15338

**Comment by thatbudakguy** [comment]
If all that's required for this is to add `| FormData` to the constructor signature, I'm happy to PR.

**Comment by saschanaz** [comment]
#19806 covers this.

**Comment by leonstafford** [comment]
@thatbudakguy - in the meantime, do you have a workaround for this?

**Comment by thatbudakguy** [comment]
@leonstafford my current workaround is just `// @ts-ignore`, sadly.

**Comment by monkeythedev** [comment]
Another workaround is: `new URLSearchParams(new FormData(event.currentTarget) as any)`

**Comment by JirkaDellOro** [comment]
Is there a deadline for this bug to be fixed?

**Comment by JirkaDellOro** [comment]
No? Yes? When?

**Comment by Spongman** [comment]
any news?

**Comment by PaperStrike** [comment]
I don't think it will be "fixed" as [`FormData` may contain `File`](https://xhr.spec.whatwg.org/#formdataentryvalue) while [`URLSearchParams` only accepts `String`](https://url.spec.whatwg.org/#urlsearchparams).

That code runs successfully in browsers because of the implicit conversions in JS. Explicit matched types are needed in TS. Try to filter out the `File`s, or convert them to `String`s. For example,

```js
const form = document.createElement('form');
const searchParams = new URLSearchParams(Array.from(new FormData(), ([key, val]) => [key, String(val)]));
```

You can see the error more clearly in [this TS playground](https://www.typescriptlang.org/play?ts=4.3.5#code/MYewdgzgLgBAZiATgWxgXhgExMArsgUzCgDphECBDKAgUQBsDDiAKAcgRTYEoBuAKFCRYnZABFqlAIKJE6GAG0SysAQDuMAGJJxklqO4BdAfwD0pmLVlJ4NgA4gIEAJYAjRjAAGm5408xnMC9tFAkoSlpiRABPADVKelwCTxJBcGgYCCpEYAALAAVKREpkCAAGeVUNAFUAJQAZAGVsvMLi0v0dMOlZPn4zCwA5EBgCazlKOBo5AgAPO3pnYGdYIQA3MZd01KEM6ERAgHNnOGcCTHlRbplEEmRKOxYWBQBrAmiAGhg1hMNudAAfIo3p8YI0oAcwIcWD96EY+rtYFkiq0iiUIABGSrqGB1JotApojr7I4nM6YPpAA).

**Comment by JirkaDellOro** [comment]
Well, MDN writes that the constructor accepts one the following:
- A USVString, which will be parsed from application/x-www-form-urlencoded format. A leading '?' character is ignored.
- A literal sequence of name-value string pairs, or any object — such as a FormData object — with an iterator that produces a sequence of string pairs. Note that that File entries will be serialized as [object File] rather than as their filename (as they would in an application/x-www-form-urlencoded form).
- A record of USVString keys and USVString values.

Since FormData is explicitly mentioned, TypeScript should gladly compile it and the definition file for the dom should include the mentioned types in the constructors signature. The fact that file won't show a filename but [object File] is a logical problem at runtime, not at compiletime.

https://jsfiddle.net/3ng6qkL1/

**Comment by saschanaz** [comment]
>The fact that file won't show a filename but [object File] is a logical problem at runtime, not at compiletime.

And TypeScript is all for preventing such logical typing problems.

Maybe FormData could be made generic so that this can work:

```ts
const form = document.createElement('form');
console.log(new URLSearchParams(new FormData<string>(form)));
```

**Comment by JirkaDellOro** [comment]
> And TypeScript is all for preventing such logical typing problems.  

True, On the other hand, TypeScript should not prevent standard functionality to work as intended.

**Comment by PaperStrike** [comment]
MDN isn't the standard, strictly speaking.

The file name conversion is defined in [form entry list to name-value pairs conversion, HTML Standard](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#converting-an-entry-list-to-a-list-of-name-value-pairs).

The note about `[object File]` isn't mentioned anywhere in [steps to initialize a URLSearchParams, URL Standard](https://url.spec.whatwg.org/#urlsearchparams-initialize).
It happens by implicit conversions.

**Comment by JirkaDellOro** [comment]
Now let me perform an elegant 180 after digging into it. This issue should not be labeled `bug` but `works as intended` and praised as a feature of TypeScript.

**Comment by thatbudakguy** [comment]
closing, since as others have mentioned it's not a bug for TypeScript to avoid coercing `File` despite this being common behavior elsewhere. thread offers several workarounds for anyone still looking to do this.

**Comment by sacru2red** [comment]
[Negated types](https://github.com/microsoft/TypeScript/pull/29317) feature could clear it. in future
```any not File```

**Comment by lightyaer** [comment]
Another workaround: 

```js

  const formData = new FormData();
  formData.set('something', "something");

  const searchParams = new URLSearchParams(
    formData as unknown as Record<string, string>,
  ).toString();
```

if value is an object, then `JSON.stringify(object);`

**Comment by thoughtsunificator** [comment]
By reading the `FormData` spec :

![Image](https://github.com/user-attachments/assets/6de306a2-6431-480b-8ca7-ae578e59ebd7)

You can see that `FormData` is an `iterable` whose values are a sequence that contains a `USVString` and `FormDataEntryValue` as values and according to the spec: 

> Objects implementing an interface that is declared to be iterable support being iterated over to obtain a sequence of values.

![Image](https://github.com/user-attachments/assets/dea55b2b-c2ae-49e5-8999-cbfe1e892da4)

which means that `FormData` is a valid `init` parameter

**Comment by ITenthusiasm** [comment]
@thatbudakguy any thoughts about the [above](https://github.com/microsoft/TypeScript/issues/30584#issuecomment-2443183562)? If you agree, would you up for re-opening this issue?

**Comment by PaperStrike** [comment]
@thoughtsunificator 
1. Number, undefined, null, File, FileList, Error, the array and object combinations of all these and many more are serializable. You don't need TypeScript if you consider them all as strings, just type in `@ts-expect-error`.
2. For objects annotated with `[Serializable]` attribute specifically, they have detailed desired serialization and deserialization steps that should be taken and let's take File as an example

    > [File](https://w3c.github.io/FileAPI/#dfn-file) objects are [serializable objects](https://html.spec.whatwg.org/multipage/structured-data.html#serializable-objects). Their [serialization steps](https://html.spec.whatwg.org/multipage/structured-data.html#serialization-steps), given value and serialized, are:
    > 1. Set serialized.[[SnapshotState]] to value’s [snapshot state](https://w3c.github.io/FileAPI/#snapshot-state).
    > 2. Set serialized.[[ByteSequence]] to value’s underlying byte sequence.
    > 3. Set serialized.[[Name]] to the value of value’s [name](https://w3c.github.io/FileAPI/#dfn-name) attribute.
    > 4. Set serialized.[[LastModified]] to the value of value’s [lastModified](https://w3c.github.io/FileAPI/#dfn-lastModified) attribute.

   I don't see how this will make `[object File]`.

**Comment by ITenthusiasm** [comment]
> That seems like exactly the situation where TS is helpful: to notify you of edge cases you might otherwise miss.

I'm not sure that this is true. There are some instances where TypeScript really should not intervene because it starts overstepping by trying to predict runtime behaviors which are intrinsically unpredictable. This is why, for example, `JSON.parse()` returns `any` instead of `unknown`. The `unknown` type is technically more "type safe", but it is far less convenient or reasonable. And the _real_ bugs resulting from `JSON.parse()` would be better caught during runtime and/or with tests.

Similarly, regarding `FormData`, this is a runtime issue. Problems with `FormData` likely won't be caught with any kind of type system. They'll be caught when submitting data to the server and seeing the response. So I still think it's worth re-opening this issue.

> If you're in the same situation, use the solution in https://github.com/microsoft/TypeScript/issues/30584#issuecomment-890515551

The comment that you linked to has negative impacts on performance by creating throw-away memory. Moreover, although I haven't tested it yet, that code might produce bugs for scenarios where a given `key` has multiple values (e.g., `<select multiple>`). (I know, for instance, that `Object.fromEntries(formData)` _definitely_ produces bugs in that scenario.) TypeScript is supposed to be something helpful, but developers shouldn't feel burdened to complicate or slow-down their code simply for a compiler. In a sense, that defeats the point of compilers.

Is there a better solution that you would propose (besides `any` or `@ts-expect-error`)? If not, then -- again -- it seems this issue isn't truly `completed` and should be re-opened, no?

**Comment by thatbudakguy** [comment]
https://github.com/microsoft/TypeScript/issues/43797 seems like a wholly valid solution.

**Comment by ITenthusiasm** [comment]
Seems limited but I'll investigate more thoroughly

**Comment by PaperStrike** [comment]
> There are some instances where TypeScript really should not intervene because it starts overstepping by trying to predict runtime behaviors which are intrinsically unpredictable.

Yes, that's why TypeScript has `as`, `!` (the one to exclude nullability), generics, overloads, `@ts-ignore`, `@ts-expect-error` and of course `any` for some totally unpredictables.

> This is why, for example, `JSON.parse()` returns `any` instead of `unknown`.

I doubt if TypeScript would pick `any` if they have `unknown` since v1.0. Search `JSON.parse unknown` in this repo and there's so many asking making it `unknown`. A quick glance over the maintainers' responses look like they relate this change to some bigger change and consider the big change too breaking so they still left it under consideration.

> Problems with `FormData` likely won't be caught with any kind of type system.

TypeScript caught mine and maybe also Budak's problem. I was writing a library that handles forms with possible File fields and confused about the error as you know URLSearchParams and FormData look so perfectly matched.

> Moreover, although I haven't tested it yet, that code might produce bugs for scenarios where a given `key` has multiple values (e.g., `<select multiple>`).

It won't, just give it a try, it works fine.

> TypeScript is supposed to be something helpful, but developers shouldn't feel burdened to complicate or slow-down their code simply for a compiler. In a sense, that defeats the point of compilers.

I agree that it's hard to relate with File in the first place by the error message (maybe caused by https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/741 that the current constructor don't allow string sequence iterables too). TypeScript should somehow improve that but it would be in different issue(s).

For the slow down I used to choose `as` (`as unknown as string[][]`) or `@ts-expect-error` randomly whenever there's no possible File and leave a comment why the cast / expect is there. Recently I rarely deal with FormData directly and I would wrap it to a universal utility that ought to handle any FormData 2 URLSearchParams conversion well if I need to.

> Is there a better solution that you would propose (besides `any` or `@ts-expect-error`)? If not, then -- again -- it seems this issue isn't truly `completed` and should be re-opened, no?

`as`, #43797 generic.

**Comment by ITenthusiasm** [comment]
> Yes, that's why TypeScript has as, ! (the one to exclude nullability), generics, overloads, @ts-ignore, @ts-expect-error and of course any for some totally unpredictables.

Those utilities do solve a number of problems. But I'm not sure I'd say they're intended for the concern that I raised earlier.

> I doubt if TypeScript would pick any if they have unknown since v1.0.

I'm basing this on a convo with orta after `axios` caught flack for changing `any` to `unknown`. A mind change may have happened since that incident, but I don't know that `unknown` is the obvious solution; not everyone wants it.

> TypeScript caught mine and maybe also Budak's problem.

That does not mean all problems can be caught (e.g., explicit `application/x-www-form-urlencoded` w/ `[type=file]` fields). There's a decent set that still has to be caught at runtime (or by foreknowledge). And to be fair, it's worth questioning whether TS really caught the problem or forced you to research/pursue an alternative.

> It won't, just give it a try, it works fine.

You are right. 👍🏾 This was an invalid assumption. Unfortunately, there's still the performance aspect.

> For the slow down I used to choose as (as unknown as string[][]) or @ts-expect-error randomly whenever there's no possible File and leave a comment why the cast / expect is there.

It's this dancing that I don't particularly favor (when it's unnecessary). I understand that you do not frequently use the `FormData` object directly anymore, but that doesn't mean other developers don't.

> as, https://github.com/microsoft/TypeScript/issues/43797 generic.

My `any` comment was referencing type casting in general. (`as any` is faster than `as unknown as *`, and they're both effectively the same hack.) That other GH issue was referenced earlier, yes.

**Comment by sandersn** [comment]
I'm not convinced this is worth re-opening. The [spec snippets](https://github.com/microsoft/TypeScript/issues/30584#issuecomment-2443183562) that @thoughtsunificator posted make it clear that Typescript should regard URLSearchParams's constructor as taking `Record<string, string>` and FormData as `Record<string, string | File>` .
And `Record<string, string | File>` isn't assignable to Record<string, string>`.

**Comment by Quicksilver0218** [comment]
This is my method to filter out all the file entries.
```ts
const params = new URLSearchParams(
  formData
    .entries()
    .filter(([, value]) => typeof value === "string")
    .toArray() as [string, string][]
);
```
