### ISSUE TITLE
Refining one value in a union does not refine all values

### ISSUE THREAD

**Issue by MarkKahn** [Microsoft/TypeScript#30622]
**TypeScript Version:**  3.3

**Search Terms:**

refine union

**Code**

```ts
declare function foo(): [number, string] | [string, number];
const [a, b] = foo();

if (typeof a === 'number') {
  console.log(a, b);
}
```

**Expected behavior:**

Would expect `b` to be of type `string` here

**Actual behavior:**

`a` is refined to `number`, while `b` remains `string | number`

**Playground Link:** 

[link](http://www.typescriptlang.org/play/#src=declare%20function%20foo()%3A%20%5Bnumber%2C%20string%5D%20%7C%20%5Bstring%2C%20number%5D%3B%0Aconst%20%5Ba%2C%20b%5D%20%3D%20foo()%3B%0A%0Aif%20(typeof%20a%20%3D%3D%3D%20'number')%20%7B%0A%20%20console.log(a%2C%20b)%3B%0A%7D%0A)

**Comment by jack-williams** [comment]
There are two issues at play here:

1. Narrowings are not tracked across variables like this. The issue for this is: #12184

2. A `typeof` check will not narrow a union like a discriminant property check, it will only narrow the type of the checked property. This has been the design since CFA was introduced I think, but I don't know if there are any plans to revisit this.

**Comment by MarkKahn** [comment]
Is there a different way to either define the return type or do the refinement so that this will work without needing to refine each?  Also tried leaving the entire object in tact but that doesn't work either for some reason:

```
declare function foo(): [number, string] | [string, number];
const res = foo();

if (typeof res[0] === 'number') {
  console.log(res); // [number, string] | [string, number]
}
```
