### ISSUE TITLE
Quick info & signature help for properties of a union type depend on previous uses of properties of a constituent type

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#3062]
![quick info union types](https://cloud.githubusercontent.com/assets/972891/7506179/4d044708-f411-11e4-91f8-b9339bc33627.gif)

You can see this in the type-writer as well, so I'm sure the issue can also be reproduced in the compiler.

**Comment by mhegazy** [comment]
The issue here is we have a union type for `Number | String` that has a union property `toString`; when we show quick info for the signature we pick the "first one"; it happens here that the two signatures are not identical( String: `()=>string`, Number `(radix?:number)=>string`).

The order of the constituent types in the union type is based on the SymbolID, and this why resolving the Number.toString in the sample above changes the order, and this changes the quick info,

The issue here is in quickInfo and SignatureHelp we should show these as overloads. this way it is consistent, though the order might still be an issue.

**Comment by mhegazy** [comment]
this should be behaving correctly now.
