### ISSUE TITLE
assign a type for an object property as same as another property

### ISSUE THREAD

**Issue by xxyyzz2050** [Microsoft/TypeScript#30670]
how to tell TS that the type of y is the same as x (without creating a separate type interface)
example:
```
interface test{
 x : number | string | (()=>number) | (()=>string);
 y : this.x; //<----------
}
```

note: I don't want to create a separate type fo x, like this:
```
type xx : number | string | (()=>number) | (()=>string);
interface test{
 x : xx;
y : xx;
}
```

**Comment by MartinJohns** [comment]
This issue tracker is not suited well for questions. Please read: https://github.com/Microsoft/TypeScript/blob/master/.github/ISSUE_TEMPLATE/Question.md

**Comment by vlazh** [comment]
Maybe like this:
```ts
interface test {
  x: number | string | (() => number) | (() => string);
  y: test['x'];
}
```

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
