### ISSUE TITLE
Do not resolve json module when outFile is set.

### ISSUE THREAD

**Issue by mehlian** [Microsoft/TypeScript#30684]
## Search Terms

Support for well-typed JSON imports;
Exclude JSON imports when outFile is set;
Use JSON file structure as type definition;

## Suggestion

Add a way to exclude JSON modules from compilation.

## Use Cases

This could be useful on type definitions (no need to create and maintain interfaces).

## Current Implementation

Example project:
```
out/main.js
file.json
main.ts
tsconfig.json
```
file.json:
```
{
    "stringProp": "test",
    "numberProp": 1,
    "objProp": {
        "stringProp" : "example",
        "arrayProp": [1,0]
    }
}
```
main.ts
```
let data: typeof import('./file.json');

console.log(data.objProp.stringProp);
```
tsconfig.json
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "amd",
    "outFile": "./out/main.js",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "resolveJsonModule": true
  },
  "exclude": [
    "./out"
  ]
}
```

**RESULT:**
out/main.js (this code won't run in browser, I need to manually remove json part from output)
```
{
    "stringProp": "test",
    "numberProp": 1,
    "objProp": {
        "stringProp": "example",
        "arrayProp": [1, 0]
    }
}
var data;
console.log(data.objProp.stringProp);
```

**EXPECTED RESULT:**
out/main.js
```
var data;
console.log(data.objProp.stringProp);
```

## Examples

Leave current syntax:
```
let data: typeof import('./file.json');
```

Or use declare keyword as flag:
```
declare type ImportedType = typeof import('./file.json');
```

Or add new flag to tsconfig.json file.

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by AlCalzone** [comment]
Probably related to https://github.com/Microsoft/TypeScript/issues/24744
I would love to have an option to just read type information from json files without including them in the transpilation process. Especially if they are outside `rootDir`, they mess up the output directory structure.

**Comment by RyanCavanaugh** [comment]
We can be sure that it's incorrect to just splat in a JSON file into a `--out` compilation; they should simply be skipped.

**Comment by andrewbranch** [comment]
Hey @mehlian, are you using TypeScript 2.9? That's the only version I could find that exhibits the behavior you described. 3.0 says you can only use `resolveJsonModule` with `module: commonjs`, and then from 3.1 on, I get this output:

```js
define("file", [], {
    "stringProp": "test",
    "numberProp": 1,
    "objProp": {
        "stringProp": "example",
        "arrayProp": [1, 0]
    }
});
var data;
console.log(data.objProp.stringProp);
```

Which is still wrong because you don't need the contents to be emitted as a result of a `typeof import`, but at least the emit is valid JavaScript.

I'm going to start on getting rid of the superfluous module inclusion, but just wanted to let you know that you should be significantly less broken in TypeScript 3.1 and later.

**Comment by andrewbranch** [comment]
Actually, I don't think this has anything to do with JSON (post 3.1). Consider the project:

```js
// tsconfig.json
{
  "compilerOptions": {
    "target": "es5",
    "module": "amd",
    "outFile": "./out/main.js",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "resolveJsonModule": true
  },
  "exclude": [
    "./out"
  ]
}

// a.ts
export const a = 3;

// main.ts
console.log('Not importing anything');
```

Its output is

```js
define("a", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.a = 3;
});
console.log('Not importing anything');
```

`a.ts` is included because it's matched by the project's default include pattern. Doesn't matter whether it's imported as a value, a type, or not at all. If you add a `files`, `include`, or `exclude` that causes `a.ts` not to be picked up, of course it drops out of the emit, since it's not referenced at all.

So let's say we add `files: ["main.ts"]` to the tsconfig, and use a `typeof import('./a')`:

```js
// tsconfig.json
{
  "compilerOptions": {
    "target": "es5",
    "module": "amd",
    "outFile": "./out/main.js",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "resolveJsonModule": true
  },
  "files": ["./main.ts"]
}

// a.ts
export const a = 3;

// main.ts
type A = typeof import('./a');
```

Now, `a.ts` isn't a root file, and its value is never used, only its type. But the module still shows up, ostensibly needlessly, in the out file.

As a final step in the thought experiment, I removed the `outFile`, `module`, `moduleResolution`, and `resolveJsonModule` options from the tsconfig and compiled with default options (still with `files: ["main.ts"]), and indeed an `a.js` does get produced, even though it never gets consumed.

So on the one hand, the current behavior of JSON modules in AMD is totally consistent with any other type of module in any other type of module system. On the other hand, the whole thing feels slightly worse when combined with `outFile`.

It feels like there are several different arguments that could be made, including never emitting JavaScript for files that are only ever brought into the program for their types, but that could technically be a breaking change. @RyanCavanaugh thoughts?

**Comment by RyanCavanaugh** [comment]
We don't really make distinctions about how/why any given implementation file ended up in your program.

I can think of plausible examples that would be badly broken by trying to be clever about it, e.g.
```ts
// register.ts
export function register(name: string, obj: any) {
  lookup[name] = obj;
}
export function lookup(name: string) {
  return lookup[obj];
}

// class1.ts
import { register } from "./register";
export class C { }
register("C", C);

// file.ts
import { lookup } from "./register";
type C1 = typeof import("./class1");
const C = lookup("C") as C1.C;
```

**Comment by andrewbranch** [comment]
Ah yeah, I was thinking of the case where a seemingly unused module gets picked up by something in the runtime environment that TypeScript doesn't know about (e.g. config file with magic name that framework X knows to look for). Modules with side effects would be even worse.

Are you suggesting that there's no bug here because everything works consistently and predictably, or are you suggesting that JSON modules imported only for their types get special treatment since they're obviously side-effect free? I kind of feel like we're seeing expected behavior here, although I resonate with this:

> I would love to have an option to just read type information from json files without including them in the transpilation process. Especially if they are outside the sources dir, they mess up the output directory structure.

But that seems to be tracked separately at #24744.

**Comment by RyanCavanaugh** [comment]
I think I'd err on the side of fewer special cases and say this is working as intended. Using `outFile` is increasingly rare anyway and people should configure their own bundlers if they need more complex behavior than the set of options we already offer.

**Comment by mehlian** [comment]
@andrewbranch yep, I can confirm that my example project was tested on TypeScript 2.9.1.
So, based on your comments this behavior won't change.
