### ISSUE TITLE
TS2339 Error: createContact does not exist in a create contact component on Angular 

### ISSUE THREAD

**Issue by Calebyang93** [microsoft/TypeScript#30765]
Hi Type script developers,

I am struggling with a TS2339 Error for create Contact on this 2 files. Firstly, the create contact in this contact-create component.ts is responsible for creating contact with a data service binding method. However, the property createContact does not exist. 

This is the contact-create.component.ts code snippet 

```
import { Component, OnInit } from '@angular/core';
import { DataService } from '../data.service';
@Component({
  selector: 'app-contact-create',
  templateUrl: './contact-create.component.html',
  styleUrls: ['./contact-create.component.css']
})
export class ContactCreateComponent implements OnInit {
contact: {id, name, description, email} = {id: null, name: '', description: '', email: ''};

  constructor(public dataService: DataService ) { }

  ngOnInit() {
  }
  createContact() {
    console.log(this.contact);
    this.dataService.createContact(this.contact);
    this.contact = {id: null, name: '', description: '', email: ''};
  }

}
```

This error occurs on a second ts file: contact-list.component.ts file: the property getContacts does not exist on dataservice type.

This is the second ts file: contact-list.component.ts 

```
import { Component, OnInit } from '@angular/core';
import { DataService } from '../data.service';


@Component({
  selector: 'app-contact-list',
  templateUrl: './contact-list.component.html',
  styleUrls: ['./contact-list.component.css']
})
export class ContactListComponent implements OnInit {
  contacts;
  selectedContact;

  constructor(public dataService: DataService) { }

  ngOnInit() {
    this.contacts = this.dataService.getContacts(); 
  }
  public selectContact(contact) {
    this.selectedContact = contact;
  }

}

```
If anyone know the reason or the underlying factors and how I should change my getContact property to make it exist on a type object on type script, please share your insights. Thanks a lot.

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
