### ISSUE TITLE
Endless loop in getEncodedSyntacticClassifications(fileName,span)

### ISSUE THREAD

**Issue by featherJ** [Microsoft/TypeScript#3082]
Version: 1.5 beta.

I found that operate the getEncodedSyntacticClassifications function in "typescriptServices.js",  the services will come into endless loop.

For example:
A script: length 800:
The span:(0,500); 

Operate the getEncodedSyntacticClassifications function will come into endless loop.
Because there is no "break"  when  "ts.textSpanIntersectsWith(span, start, width)" return  "false"  in "while(true)".

I think the following code will solve this problem:
```ts
function classifyLeadingTrivia(token) {
...
    while (true) {
    ...
         if (ts.textSpanIntersectsWith(span, start, width)) {
             ...
         } else {
             break;
         }
    }
...
}
```
Thanks and sorry for my poor Engslih.  :)

**Comment by DanielRosenwasser** [comment]
Thought about this for a bit - I think this will indeed terminate, because this function doesn't get called unless `classifyElement` gets called, which only gets called if that token itself intersects with `span`. At that point, we go to the full start of the token and will keep scanning. Eventually, we will hit that token, which, as we said, intersects with the span.

Of course, I could be wrong - do you have a solid way to trigger an error?

 @CyrusNajmabadi what was wrong with the old `getLeadingCommentRanges` approach? Was it just too slow?

**Comment by featherJ** [comment]
You can try this:
Add `/TypeScript/src/services/shims.ts in 1.5beta` to service with filename `demo`
and call `getEncodedSyntacticClassifications("demo",ts.createTextSpan(0, 500))`.

**Comment by CyrusNajmabadi** [comment]
@DanielRosenwasser 'getLeadingCommentRanges' doesn't give you the right spans.  'getLeadingCommentRanges' simulates Roslyn's concept of leading comments (and would not include comments from 'pos' to the end of the first line after 'pos'.  But want *all* the comments from 'pos' to the actual start of the token.

**Comment by DanielRosenwasser** [comment]
Confirmed on my end - thanks for reporting the bug @featherJ!

**Comment by featherJ** [comment]
My pleasure. ^^
