### ISSUE TITLE
Why export const INCREMENT_ENTHUSIASM then export type INCREMENT_ENTHUSIASM again?

### ISSUE THREAD

**Issue by jettangs** [Microsoft/TypeScript#30861]
![image](https://user-images.githubusercontent.com/7941297/55936530-2692ff00-5c69-11e9-8cd2-d7902768eba9.png)
Why `export const INCREMENT_ENTHUSIASM` then `export type INCREMENT_ENTHUSIASM`  again, what's the meaning?

**Comment by jettangs** [comment]
https://github.com/Microsoft/TypeScript-React-Starter

**Comment by j-oliveras** [comment]
To use them in a type position. Consider:

constants.ts
```ts
export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;
```

index.ts
```ts
import { DECREMENT_ENTHUSIASM } from "./constants";

const a: DECREMENT_ENTHUSIASM = "DECREMENT_ENTHUSIASM";
```

If you comment the `type DECREMENT_ENTHUSIASM` declaration you will see an error on `const a`: `'DECREMENT_ENTHUSIASM' refers to a value, but is being used as a type here.ts(2749)`.

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
