### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by svet007** [microsoft/TypeScript#30873]
https://www.typescriptlang.org/docs/handbook/basic-types.html, click Arrays -> "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

**Comment by RyanCavanaugh** [comment]
I don't see a link titled "Arrays" there. Screenshot?

**Comment by delphiactual** [comment]
![Screenshot from 2019-04-11 17-17-09](https://user-images.githubusercontent.com/4798491/55998948-cc506900-5c7d-11e9-90d5-ff6748489c77.png)

FWIW all of `Boolean, Number, String, Array, Tuple, Enum, Any, Void, Null and Undefined, Never, and Object` display this error

**Comment by svet007** [comment]
Hello,

Please see attached.

"Array" header is a link, too. Hope this helps.

Thanks,

Alex.

**Comment by kabirbaidhya** [comment]
Not sure if this issue still persists. Because now there are separate anchor (#) links for each header and all the links work. Probably the issue has been resolved lately? 

https://www.typescriptlang.org/docs/handbook/basic-types.html
![image](https://user-images.githubusercontent.com/3315763/66292192-6b8bab80-e903-11e9-8cab-97e99d60c1a6.png)

**Comment by RyanCavanaugh** [comment]
Website has been basically rewritten in the meantime
