### ISSUE TITLE
Type 'void' is not assignable to type 'undefined'.

### ISSUE THREAD

**Issue by xiaoxiangmoe** [Microsoft/TypeScript#30880]
**TypeScript Version:**  3.5.0-dev.20190410

**Search Terms:** void type

**Code**

"strict": true
 
```ts
const v: void = undefined; // OK
const v2: void = null; // Error: Type 'null' is not assignable to type 'void'.

// so void has only an instance: `undefined`,
// `type void = undefined` should be true.

const undef: undefined = v; // Error: Type 'void' is not assignable to type 'undefined'.
// Why 'void' is not assignable to type 'undefined'?

type A = undefined extends void ? true : false; 
type B = void extends undefined ? true : false; // Why false?

```
**Playground**

please open `strictNullChecks`

[link](http://www.typescriptlang.org/play/#src=%0D%0Aconst%20v%3A%20void%20%3D%20undefined%3B%20%2F%2F%20OK%0D%0Aconst%20v2%3A%20void%20%3D%20null%3B%20%2F%2F%20Error%3A%20Type%20'null'%20is%20not%20assignable%20to%20type%20'void'.%0D%0A%0D%0A%2F%2F%20so%20void%20has%20only%20an%20instance%3A%20%60undefined%60%0D%0A%0D%0Aconst%20undef%3A%20undefined%20%3D%20v%3B%20%2F%2F%20Error%3A%20Type%20'void'%20is%20not%20assignable%20to%20type%20'undefined'.%0D%0A%2F%2F%20Why%20'void'%20is%20not%20assignable%20to%20type%20'undefined'%3F%0D%0A%0D%0Atype%20A%20%3D%20undefined%20extends%20void%20%3F%20true%20%3A%20false%3B%0D%0Atype%20B%20%3D%20void%20extends%20undefined%20%3F%20true%20%3A%20false%3B%20%2F%2F%20Why%20false%3F)

**Related Issues:** 

https://github.com/Microsoft/TypeScript/issues/8322#issuecomment-214928203

**Comment by nmain** [comment]
The intent of `void` is to provide a type for which anything can be written to, but which cannot be read.  It's for functions where the implementer is making no guarantees about the return type except that it won't be useful to callers.  It's not the same as `undefined` because a function returning `void` might, in javascript at runtime, return something other than `undefined`.

As an example:
http://www.typescriptlang.org/play/#src=interface%20Foo%20%7B%0D%0A%20%20%20%20()%3A%20void%3B%0D%0A%7D%0D%0A%0D%0Aconst%20a%3A%20Foo%20%3D%20()%20%3D%3E%20true%3B%20%2F%2F%20Ok!%0D%0Aconst%20b%3A%20Foo%20%3D%20()%20%3D%3E%20%7B%20%7D%3B%20%2F%2F%20Ok!%0D%0Aconst%20c%3A%20Foo%20%3D%20()%20%3D%3E%20undefined%3B%20%2F%2F%20Ok!%0D%0A%0D%0Alet%20d%20%3D%20a()%3B%20%2F%2F%20d%20has%20type%20void%0D%0Aif%20(typeof%20d%20!%3D%3D%20%22undefined%22)%20%7B%0D%0A%20%20%20%20%2F%2F%20wouldn't%20expect%20to%20hit%20this%20path%20if%20void%20was%20undefined%2C%20but%20you%20will%20because%20d%20is%20actually%20true%0D%0A%20%20%20%20console.log(%22wow%22)%3B%0D%0A%7D%0D%0A
