### ISSUE TITLE
Overlapping formatting edits returned for jsx

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#30898]
**TypeScript Version:**  3.5.0-dev.20190412

**Search Terms:**

**Code**
Run format on the following js (note that the whitespace is significant): 
```ts
const a = (
    <div
>x
        
    </div>
)
```

**Bug**
The returned response contains overlapping edits:

```
[Trace  - 2:02:46 PM] Response received: format (16). Request took 3 ms. Success: true 
Result: [
    {
        "start": {
            "line": 3,
            "offset": 1
        },
        "end": {
            "line": 3,
            "offset": 1
        },
        "newText": "    "
    },
    {
        "start": {
            "line": 4,
            "offset": 1
        },
        "end": {
            "line": 4,
            "offset": 8
        },
        "newText": "               "
    },
    {
        "start": {
            "line": 4,
            "offset": 1
        },
        "end": {
            "line": 4,
            "offset": 9
        },
        "newText": ""
    }
]
```

**Playground Link:** 

**Related Issues:**

**Comment by orta** [comment]
It looks like we have always shipped overlapping edits in the formatter: https://github.com/microsoft/TypeScript/issues/6666

When we consume edits ourselves in tests, [we assume the order is important and edit the TextChanges](https://github.com/microsoft/TypeScript/blob/c69b255bf69469838a3b755961471a2cdd63fea7/src/harness/fourslashImpl.ts#L2088) to take into account the overlapping edits, which it seems is left to a client to do (at this point, I'd assume that vscode has the same edits)

Because we consume in our tests this way, we have no idea how many places there are overlapping edits and so fixing it locally isn't really a good idea.

The right solution for this is to have a merging pass before we pass out the TextChanges to clients.

**Comment by mjbvz** [comment]
Just tested using the example and it looks like this no longer happens with 4.5-rc
