### ISSUE TITLE
New Website Logo: Gigadrive

### ISSUE THREAD

**Issue by Zeryther** [microsoft/TypeScript#30915]
* Name: Gigadrive
* Homepage url: https://gigadrivegroup.com
* Brand Guidelines/Licensing: none
* Logo: https://gigadrivegroup.com/assets/img/Logo.png

**Comment by orta** [comment]
Hey folks -we're looking at a new website and it's likely that the friends of TypeScript page isn't going to make it to the new site. This is mainly because close to everyone is a friend of TypeScript now and listing folks kinda feels a bit un-inclusive to everyone else. 

So I'm going to close this issue - thanks for posting to apply
