### ISSUE TITLE
@types/reactstrap@8.0.0 runs out of memory on TS 3.4

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#30973]
1. clone DefinitelyTyped
3. cd types/lodash, types/reactstrap, types/reactstrap/v7
3. tsc 

For tsc 3.4.3 and above (and probably all 3.4.x)

**Expected behavior:**
No unexpected errors.

**Actual behavior:**
node runs out of memory.

This might be an unavoidable effect of the additional work that we do in 3.4 and above, but in that case, those three packages (at least) need to be rewritten to be more efficient.

**Comment by sandersn** [comment]
After cleaning node_modules on DefinitelyTyped, lodash passes.
On windows, reactstrap also doesn't repro -- it uses over 1500 MB of memory before succeeding though.

**Comment by sandersn** [comment]
reactstrap is now much smaller after some changes I made. For this bug, use 8.0.0, not 8.0.1 (or higher).

**Comment by sandersn** [comment]
![Selection_025](https://user-images.githubusercontent.com/293473/56381414-a53bef00-61c9-11e9-8535-0c8af47c7be2.png)
Here's the performance of lodash over the 3.4 release, as measured by type count. The explosion was on 02/27, with only minor differences before and after. I'll bisect to find the exact commit.

**Comment by sandersn** [comment]
#29981 is the culprit here.

**Comment by weswigham** [comment]
@sandersn does #30416 fix that OOM? (I triggered a package build on it after making some small adjustments so it can be tested against)

**Comment by sandersn** [comment]
Fixes lodash -- 485k &rarr; 85k types. (vs 83k on 3.3)
Fixes reactstrap 8.0.0, basically -- 1538k &rarr; 591k types (vs 493k on 3.3)

**Comment by daniel19801** [comment]
StopSent from my Sprint Samsung Galaxy S10+.
-------- Original message --------From: Nathan Shively-Sanders <notifications@github.com> Date: 4/19/19  10:40 AM  (GMT-06:00) To: Microsoft/TypeScript <TypeScript@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [Microsoft/TypeScript] @types/reactstrap@8.0.0 runs out of memory
  on TS 3.4 (#30973) Fixes lodash -- 485k → 85k types. (vs 83k on 3.3)

Fixes reactstrap 8.0.0, basically -- 1538k → 591k types (vs 493k on 3.3)



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Microsoft/TypeScript","title":"Microsoft/TypeScript","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Microsoft/TypeScript"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sandersn in #30973: Fixes lodash -- 485k \u0026rarr; 85k types. (vs 83k on 3.3)\r\nFixes reactstrap 8.0.0, basically -- 1538k \u0026rarr; 591k types (vs 493k on 3.3)\r\n"}],"action":{"name":"View Issue","url":"https://github.com/Microsoft/TypeScript/issues/30973#issuecomment-484934750"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/Microsoft/TypeScript/issues/30973#issuecomment-484934750",

"url": "https://github.com/Microsoft/TypeScript/issues/30973#issuecomment-484934750",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by sandersn** [comment]
This is fixed now.
