### ISSUE TITLE
Leading |/& is not included in the intersection/union node

### ISSUE THREAD

**Issue by bradzacher** [microsoft/TypeScript#30995]
**TypeScript Version:**  3.4.1

**Search Terms:** Union Intersection Leading Character Parse AST

**Code**

```ts
type Foo =
    | A
    | B;
```
https://astexplorer.net/#/gist/52725a31dc27bf4bdf88843ebd3d07f8/eccbc97edfc8d520f8c08aff0f2024053eeab1b7

(note this behaviour is exactly the same for `IntersectionType`s)

**Expected behavior:**
The `UnionType` node should include the leading `|`.

**Actual behavior:**
The leading `|` is not included in the node.
![image](https://user-images.githubusercontent.com/7462525/56301378-903d5e00-60ec-11e9-83fd-71a796706952.png)
(The underlined node is currently hovered, highlighting it in the editor)

This creates some weirdness because it means the leading character ofc isn't part of the Union/Intersection node, and is instead technically a part of whatever node is its parent.

**Related Issues:** 
https://github.com/typescript-eslint/typescript-eslint/issues/435

**Comment by ahejlsberg** [comment]
That definitely seems wrong.

**Comment by mysticatea** [comment]
Does this mean the following code are considered as an intersection/union type?

```ts
type A = | 1
type B = & 2
```

**Comment by MartinJohns** [comment]
@mysticatea No. With a single type it'll be a type alias. See here: https://astexplorer.net/#/gist/8c2a38fd42b7326872dfcde0ec74cb5f/fb65f9cee71509112894c26567d5f74ae377ba3e

**Comment by mysticatea** [comment]
In that case, I'm not sure if this is a bug.

I don't think that `LiteralType` node range should contain the beginning operator. So it's consistent that the intersection/union type node range doesn't contain the beginning operator.

**Comment by ajafff** [comment]
IMO it should parse as union/intersection type with one constituent. That's what happens with a trailing | or &

**Comment by mysticatea** [comment]
@ajafff A trailing `|` or `&` is syntax error: https://www.typescriptlang.org/play/index.html#src=type%20A%20%3D%20%7C%201%0D%0Atype%20B%20%3D%20%26%202%0D%0Atype%20C%20%3D%201%20%7C%0D%0A

**Comment by bradzacher** [comment]
The problem with ignoring it is that you now have this free token in the code which doesn't belong to any node at all, which creates an invalid state in the produced AST.

Not that I want to prescribe a solution (I'm not a language designer).
But from the point of someone looking for consistency, I'd probably want `type x = | T;` to be a syntax error. i.e. prefixing a type with the `|` or `&` operator is not semantically valid *unless* there is more than one type (i.e. it is a union/intersection).

The problem that I see with the current semantics is that this is 100% valid typescript:
```TS
type A = | ( | ( | ( | ( | 1) ) ) );
```
[repl](https://www.typescriptlang.org/play/#src=type%20A%20%3D%20%7C(%7C(%7C(%26(%7C%201))))%3B) 

Which of course means that each of the ParenthesizedType nodes "owns" one `|`, and the TypeAliasDeclaration owns one `|` as well.

**Comment by daniel19801** [comment]
Stop Sent from my Sprint Samsung Galaxy S10+.
-------- Original message --------From: Brad Zacher <notifications@github.com> Date: 4/19/19  11:48 AM  (GMT-06:00) To: Microsoft/TypeScript <TypeScript@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [Microsoft/TypeScript] Leading |/& is not included in the
  intersection/union node (#30995) The problem with ignoring it is that you now have this free token in the code which doesn't belong to any node at all, which creates an invalid state in the produced AST.
Not that I want to prescribe a solution (I'm not a language designer).
But from the point of someone looking for consistency, I'd probably want type x = | T; to be a syntax error. i.e. prefixing a type with the | or & operator is not semantically valid unless there is more than one type (i.e. it is a union/intersection).
The problem that I see with the current semantics is that this is 100% valid typescript:
type A = | ( | ( | ( | ( | 1) ) ) );
repl
Which of course means that each of the ParenthesizedType nodes "owns" one |, and the TypeAliasDeclaration owns one | as well.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Microsoft/TypeScript","title":"Microsoft/TypeScript","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Microsoft/TypeScript"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bradzacher in #30995: The problem with ignoring it is that you now have this free token in the code which doesn't belong to any node at all, which creates an invalid state in the produced AST.\r\n\r\nNot that I want to prescribe a solution (I'm not a language designer).\r\nBut from the point of someone looking for consistency, I'd probably want `type x = | T;` to be a syntax error. i.e. prefixing a type with the `|` or `\u0026` operator is not semantically valid *unless* there is more than one type (i.e. it is a union/intersection).\r\n\r\nThe problem that I see with the current semantics is that this is 100% valid typescript:\r\n```TS\r\ntype A = | ( | ( | ( | ( | 1) ) ) );\r\n```\r\n[repl](https://www.typescriptlang.org/play/#src=type%20A%20%3D%20%7C(%7C(%7C(%26(%7C%201))))%3B) \r\n\r\nWhich of course means that each of the ParenthesizedType nodes \"owns\" one `|`, and the TypeAliasDeclaration owns one `|` as well."}],"action":{"name":"View Issue","url":"https://github.com/Microsoft/TypeScript/issues/30995#issuecomment-484953849"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Microsoft/TypeScript/issues/30995#issuecomment-484953849",
"url": "https://github.com/Microsoft/TypeScript/issues/30995#issuecomment-484953849",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by mysticatea** [comment]
> ```ts
> type A = | ( | ( | ( | ( | 1) ) ) );
> ```

🤣 

I think we have three paths to solve this problem.

1. The beginning operator is floating token as is because it doesn't have any effects for semantic. This is similar to the fact AST nodes don't contain extra parentheses. For example, `var a = ((((1))));`, this `1` Literal node range doesn't contain the parentheses. It's not surprising.
1. Intersection/union node contains the beginning operator *and* the beginning operator makes intersection/union node even if the followed type was not an intersection/union type. [My first question](https://github.com/Microsoft/TypeScript/issues/30995#issuecomment-484855310) came from this way. For example, `type A = | 1` makes a `UnionType` node which has a `LiteralType` node. But as considering @bradzacher 's example, this way can make deeply nested intersection/union types. It's not good.
1. Intersection/union node contains the beginning operator *and* the beginning operator is a syntax error if the followed type was not an intersection/union type. This way looks like the most reasonable, but it's a breaking change.

**Comment by platinumazure** [comment]
Totally new to Typescript, but: What is the semantic value of nesting types in a union or intersection in the first place? Are dynamic expressions allowed here, such that nesting expressions might be a valid use case?

**Comment by daniel19801** [comment]
Stop emailSent from my Sprint Samsung Galaxy S10+.
-------- Original message --------From: Kevin Partington <notifications@github.com> Date: 4/20/19  3:50 PM  (GMT-06:00) To: Microsoft/TypeScript <TypeScript@noreply.github.com> Cc: daniel19801 <daniel.e.thorp54@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [Microsoft/TypeScript] Leading |/& is not included in the
  intersection/union node (#30995) Totally new to Typescript, but: What is the semantic value of nesting types in a union or intersection in the first place? Are dynamic expressions allowed here, such that nesting expressions might be a valid use case?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Microsoft/TypeScript","title":"Microsoft/TypeScript","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Microsoft/TypeScript"}},"updates":{"snippets":[{"icon":"PERSON","message":"@platinumazure in #30995: Totally new to Typescript, but: What is the semantic value of nesting types in a union or intersection in the first place? Are dynamic expressions allowed here, such that nesting expressions might be a valid use case?"}],"action":{"name":"View Issue","url":"https://github.com/Microsoft/TypeScript/issues/30995#issuecomment-485169056"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Microsoft/TypeScript/issues/30995#issuecomment-485169056",
"url": "https://github.com/Microsoft/TypeScript/issues/30995#issuecomment-485169056",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by bradzacher** [comment]
@platinumazure - if I understand your question, you're talking about the use of parenthesis?

They let you clarify types when things become ambiguous. For example:
```TS
type UnionIntersection = A | B & C;
type UnionIntersectionClear = (A | B) & C;
type UnionIntersectionClear2 = A | (B & C);

type ArrowFn = () => string | number;
type ArrowFnClear = (() => string) | number;
type ArrowFnClear = () => (string | number);
```

You can get pretty funky with your nesting if you'd like, the syntax is expressive enough that you can add any combination of types in. `type`s can reference other `type`s, you can inspect types by property names if they have them (`type T = { prop: string }; type TProp = T['prop'];`).

**Comment by platinumazure** [comment]
Thanks @bradzacher, I appreciate the primer. That answers my question.

**Comment by rbuckton** [comment]
I wonder if we should add something like `prefixToken` to `UnionTypeNode` and `IntersectionTypeNode` as a place to put this token, and possibly issue a syntax error on a leading `|` or `&` if we don't end up parsing a union or intersection:

```ts
// ok
type A = 
  | X
  | Y;
// not ok 
type B =
  | X;
```

Alternatively, we could *always* create a `UnionTypeNode` or `IntersectionTypeNode` with a single constituent when we encounter a leading `&` or `|` token, so that we have a place to put the token.
