### ISSUE TITLE
Proposal: Auto-polyfilling

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#3101]
Using new ES5 and ES6 features should be seamless. And they aren't today using TypeScript, because developers need to manually polyfill themselves. The TypeScript compiler have all the information it needs to enable auto-polyfilling(the type and the script target). In fact, it might be the only JS-to-JS compiler that can do auto-polyfilling, because it supports type annotations. It could clearly get an edge over other JS-to-JS compilers. 

Here are some examples.
```typescript
let names = ['emma', 'john', 'eric'];
if(names.includes('emma')) {
  console.log('hi');
}
```
will be compiled into ES5 target.
```typescript
if (![].includes) {
  Array.prototype.includes = function(searchElement /*, fromIndex*/ ) {
    'use strict';
    var O = Object(this);
    var len = parseInt(O.length) || 0;
    if (len === 0) {
      return false;
    }
    var n = parseInt(arguments[1]) || 0;
    var k;
    if (n >= 0) {
      k = n;
    } else {
      k = len + n;
      if (k < 0) {k = 0;}
    }
    var currentElement;
    while (k < len) {
      currentElement = O[k];
      if (searchElement === currentElement ||
         (searchElement !== searchElement && currentElement !== currentElement)) {
        return true;
      }
      k++;
    }
    return false;
  };
}

var names = ['emma', 'john', 'eric'];
if(names.includes('emma')) {
  console.log('hi');
}
```

**Comment by kitsonk** [comment]
Auto polyfilling is a bad idea.  Generally I believe polyfilling is a bad idea, as it modifies the global context in a way that maybe very unexpected for any other code running in that environment.  While you might be doing something to make your life easier, other developers likely won't be expecting that.  Polluting or modifying the global context has led to all sorts of tears over the years.

If you will, shimming, is a much better approach in the long term, if defined as a module returning an object which has only been modified in your context to include the missing feature functionality, and that module figures out if there is native code to handle the missing feature, giving you a consistent API.

My opinion is that if the ES6 feature cannot be cleanly degraded to ES6, then TypeScript shouldn't touch it.  Polyfills would be challenging for TypeScript to maintain, let alone to agree upon which polyfills to include, and debates over code an approach.

If you are 100% confident that in your environment that polyfills are safe, then there are certainly enough of them out there to utilise, most of which have appropriate typings that you can include in your project.  There are also increasingly a number of libraries built on TypeScript becoming available which are starting to close the gaps that are being introduced in ES6, ES7, ES.Next...

**Comment by tinganho** [comment]
>Auto polyfilling is a bad idea. Generally I believe polyfilling is a bad idea, as it modifies the global context in a way that maybe very unexpected for any other code running in that environment. While you might be doing something to make your life easier, other developers likely won't be expecting that. Polluting or modifying the global context has led to all sorts of tears over the years.

I can see a negative side effect with auto-polyfill. If let say that one third library have added a support for `Array.prototype.includes` but with a different API then specified in the ES spec and you as a consumer doesn't know about it. Your application would crash. But how often does it happen? I think not that often. The benefits outweighs the risks here. Many people don't use new JS features because it is not simple to add them. TS is one of few projects that could implement a seamless support.

>If you will, shimming, is a much better approach in the long term, if defined as a module returning an object which has only been modified in your context to include the missing feature functionality, and that module figures out if there is native code to handle the missing feature, giving you a consistent API.

I can't see the difference with polyfill? Could you give me an example of `Array.prototype.includes`?

>My opinion is that if the ES6 feature cannot be cleanly degraded to ES6, then TypeScript shouldn't touch it. Polyfills would be challenging for TypeScript to maintain, let alone to agree upon which polyfills to include, and debates over code an approach.

That's the problem they already have with the core language. Why would polyfills be challenging to support? And why would it be hard to agree upon which to support? And would this new challenges be more challenging then the core language? Babeljs polyfill support(although very simple) is maintained by one guy?

**Comment by RyanCavanaugh** [comment]
There are good, straightforward solutions (namely: ES6 polyfill libraries) to this already.

Having the compiler try to figure out which ES6 methods you need, and where to emit them, and when, with controls for people who *don't* want the polyfills emitted, and ways to change where those polyfills come from, etc, is a big mess that isn't justified by the potential gains over simply including a normal ES6 polyfill library in your script context.

**Comment by tinganho** [comment]
>There are good, straightforward solutions (namely: ES6 polyfill libraries) to this already

That is not the same solution as auto-polyfill. I don't want to polyfill things I don't use. And It's a hell to cherry-pick the polyfills I want.

>Having the compiler try to figure out which ES6 methods you need, and where to emit them, and when, with controls for people who don't want the polyfills emitted, and ways to change where those polyfills come from, etc, is a big mess that isn't justified by the potential gains over simply including a normal ES6 polyfill library in your script context.

I think most people wants them emitted them before the "main" is run. Why can't this be behind a command line flag? Then people can decide whether they want it to be auto-polyfilled or not.

**Comment by RyanCavanaugh** [comment]
What happens when your code is an external module? We have no way of knowing which module is "first" and there's no "main" function.

What happens you write code that invokes a should-be polyfilled method through an `any` instance? We have no way of knowing which method needs to be filled in.

What happens when you have a function that requires that an `includes` method be present on the passed-in object? Do we always polyfill in `includes`, then? What distinguishes that case from any array-accepting method?

What about code that says `var x = arr.includes;` ? Is that an ES6 check and we shouldn't polyfill it, or maybe it's actually a usage of `includes` in some other location?

**Comment by tinganho** [comment]
>What happens when your code is an external module? We have no way of knowing which module is "first" and there's no "main" function. 

If you run `tsc filename` isn't it the root file? The "main" is that file.

>What happens you write code that invokes a should-be polyfilled method through an `any` instance? We have no way of knowing which method needs to be filled in.

Couldn't he just cast it back to a polyfill object?
```typescript
let a: string = 'a';
let b: any = a;
(<string>b).codePointAt(0);// ES6 feature
```

>What happens when you have a function that requires that an includes method be present on the passed-in object? Do we always polyfill in includes, then? What distinguishes that case from any array-accepting method?

If it is derived from a polyfilled type, then polyfill? If it is derived from a custom class that has the same method name, then don't polyfill.

>What about code that says var x = arr.includes; ? Is that an ES6 check and we shouldn't polyfill it, or maybe it's actually a usage of includes in some other location?

If you run a polyfill command and if `arr` is derived from the array type then it should be polyfilled. The dev should know that there is no need to have polyfill checks in his code when running autopolyfill. Even though he polyfills his code – it won't break as long as the auto-polyfill do the same as his polyfill.

**Comment by kitsonk** [comment]
> Your application would crash because your 3rd party library doesn't work, because you modified the polyfill. But honestly how often does it happen? I think not that often.

My experience, especially with the scope you are talking about, is a lot more than you would think.  Very few commercial projects I am aware of are single framework ones.  The commercial reality is you get all sorts of pressure from sales and marketing to include ad-tracking software, you get your own dev pressures to maybe include MVT tooling, etc.  I agree wholeheartedly @RyanCavanaugh that it would be a nightmare to maintain, especially because it has to be delivered with the tooling to turn it off.

> I can't see the difference with polyfill? Could you give me an example of Array.prototype.includes?

Well, Array is the bugger, not because of the concept, but because of the way Arrays work in ES, in that at the moment you can't subclass them and you can't recreate them fully in ES.  For an example of what I would call a TypeScript ES6 shim, check out [dojo-core's WeakMap.ts](https://github.com/dojo/core/blob/master/src/WeakMap.ts).  Notice that it does not change the global namespace.  It either returns a functionally complete shim or it returns the native interface.  From a user's perspective, you just include the module and whatever you require in will be the most "efficient" implementation supported in your environment and you haven't suddenly added something to the global namespace that some other code isn't expecting.  I know the terms get conflated a lot.

Array shims have to take a different approach, because you cannot return a fully functional Array type constructor object.  So what you can do though is return an object which requires an Array as an argument, like [dojo-core's array.ts](https://github.com/dojo/core/blob/master/src/array.ts).

(For full disclosure, I am part of the Dojo team)

**Comment by tinganho** [comment]
Thanks @kitsonk for clarification between shim and polyfill. Never really understood the difference before, but now I do.

**Comment by sk-** [comment]
@kitsonk And what about emitting a call to a wrapper instead of modifying the global context with a polyfill. Knowing the types makes the task much easier for TypeScript. 

Let's say your are using the function [`repeat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat) of String.

```typescript
function duplicateString(s: string) {
  return s.repeat(2);
}
```

In the generated code Typescript could emit, for all types that could potentially be string (i.e. string,String or Any),  a call to a wrapper function like the following:

```javascript
function stringRepeatShimWrapper(s, times) {
  if (typeof(s) === 'string' || s instanceof String) { 
   // Polyfill code.
  } else {
    return s.repeat(times);
  }
}

function stringRepeatNativeWrapper(s, times) {
  return s.repeat(times);
}

var stringRepeatWrapper = String.prototype.repeat === undefined ? stringRepeatShimWrapper: stringRepeatNativeWarpper;

function duplicateString(s) {
  return stringRepeatWrapper(s, 2);
}
```

**Comment by kitsonk** [comment]
That would assume that TypeScript would be able understand every aspect of every built in as functional code, maintain the the "down emit" etc...  This is expressly against the [non-goal](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#non-goals) for TypeScript:

> 6. Provide additional runtime functionality or libraries. Instead, use TypeScript to describe existing libraries.

Setting aside that is a lot of emit. 3 lines of code suddenly balloons to 13+.  Best thing to do is use core.js in environments you need it or other polyfill/shim strategies.
