### ISSUE TITLE
Renaming NumericLiteral to NumberLiteral?

### ISSUE THREAD

**Issue by jbondc** [Microsoft/TypeScript#3104]
There's currently a NumericLiteral:
https://github.com/Microsoft/TypeScript/blob/master/src/compiler/types.ts#L23

And a numberIndex:
https://github.com/Microsoft/TypeScript/blob/master/src/compiler/types.ts#L1507

I'm trying to add:
```
    export interface NumberSetType extends Type  {
        start: number;
        end: number;
        /* @internal */
        sparseValues?: number[];
    }
```
Should this be called a NumericSetType?

My preference would be to rename  NumericLiteral to  NumberLiteral, and keeping NumericLiteral as backwards compat. Is that too much of a big change?

**Comment by DanielRosenwasser** [comment]
This would be a pretty major change. What are you trying to achieve?

**Comment by jbondc** [comment]
Just consistent naming, is NumericSetType  or NumberSetType better?

It's related to #1003

**Comment by DanielRosenwasser** [comment]
I'd prefer it stayed `NumericLiteral`. That said, I would proceed with caution, since the proposal itself hasn't been discussed by the team yet.

**Comment by CyrusNajmabadi** [comment]
ES5 specifies this as NumericLiteral.  What is NumberSetType supposed to represent?  Without knowing, it's not possible to make a good name for it.

**Comment by jbondc** [comment]
@CyrusNajmabadi See here:
https://github.com/Microsoft/TypeScript/commit/4dc4814769a4e9f893c875bde7ed925a84b021a2

I could use your input to 'scan a numeric literal', it's awkward code right now because of scanner compat with JS:
https://github.com/Microsoft/TypeScript/commit/4dc4814769a4e9f893c875bde7ed925a84b021a2#diff-ead24f0f0f59c0ea9c1c511052e8884bR2234

**Comment by DanielRosenwasser** [comment]
You'd probably have to search for a numeric literal, a `...` token and another numeric literal. That said, since `1.` is a valid numeric literal and so is `.3`, you couldn't write `1...3`, you'd have to write `1.....3` or have separators like `1 ... 3` or `(1)...(3)`.

I'll reiterate my word of caution - if you're intent on presenting a proof of concept, then that's great - we love to see when people can do cool stuff with the compiler. Experimenting is a great way for both you and us to learn. We can help answer questions about the internals and give you some guidance, but we can't make any guarantees over whether we're willing to put something like this into the language without further discussion.

**Comment by CyrusNajmabadi** [comment]
I would not do this in the scanner.  Have the scanner just scan out things as normal.  But in the parser, recognize 'number ... number' as your funky thing you're trying out.

**Comment by CyrusNajmabadi** [comment]
Yeah, i'm with Dan on this.  The lexical ambituities are going to be a bit obnoxious to have to deal with.  Note that you'd actually have to write  ```1....3``` (i.e. 4 dots).  That's because `1.` would be one lexeme.  Then ```...``` would be the next.  Then ```3``` would be the last.

I'd recommend some other piece of syntax (tbh, i'm not sure why ```1-3``` wouldn't work, given you're in a type position).
