### ISSUE TITLE
Constraints are not considered for Conditional Types

### ISSUE THREAD

**Issue by hediet** [Microsoft/TypeScript#31096]
**TypeScript Version:**  3.5.0-dev.20190424

**Code**

```ts
function f<
	TType extends { p: string },
>(
	bla: TType
): void {
	const x: TType['p'] = 'test'; // typechecks
	const y: TType["p"] extends string ? string : number = "test"; // does not
}
```

**Expected behavior:**
It typechecks.

**Actual behavior:**
It does not:

> Type '"test"' is not assignable to type 'TType["p"] extends string ? string : number'.
> const y: TType["p"] extends string ? string : number

The assignment to `x` however typechecks.

[**Playground Link** ](https://www.typescriptlang.org/play/#src=function%20f%3C%0D%0A%09TType%20extends%20%7B%20p%3A%20string%20%7D%2C%0D%0A%3E(%0D%0A%09bla%3A%20TType%0D%0A)%3A%20void%20%7B%0D%0A%09const%20x%3A%20TType%5B'p'%5D%20%3D%20'test'%3B%20%2F%2F%20typechecks%0D%0A%09const%20y%3A%20TType%5B%22p%22%5D%20extends%20string%20%3F%20string%20%3A%20number%20%3D%20%22test%22%3B%20%2F%2F%20does%20not%0D%0A%7D)

**Comment by jack-williams** [comment]
This is working as intended. Conditional type resolution ignores type parameter constraints to prevent undesirable resolutions that violate transitivity. See this comment:
```ts
// Return trueType for a definitely true extends check. We check instantiations of the two
// types with type parameters mapped to their restrictive form, i.e. a form of the type parameter
// that has no constraint. This ensures that, for example, the type
// type Foo<T extends { x: any }> = T extends { x: string } ? string : number
// doesn't immediately resolve to 'string' instead of being deferred.
```

A concrete example:
```ts
function f<
	TType extends { p: any },
>(
	bla: TType
): TType["p"] extends string ? string : number {	
	return "test"; // If we used the constraint this would be legal.
}

const res: number = f({ p: 3 }); // res === "test";
```

There are cases where using the constraint is sound but it involves exploring the constraint type.

**Comment by hediet** [comment]
I've managed to overcome this issue by replacing conditional types with map-types:
```ts
function f<
	TType extends { kind: "a" },
>(
	bla: TType
): void {
	const x: TType['kind'] = 'a'; // typechecks
	let y: { a: string, b: number }[TType["kind"]]; // does not
	y = "test";
	y = 4;
}
```

@jack-williams So this restriction is only because of any?

**Comment by jack-williams** [comment]
> So this restriction is only because of any?

In general the root of the issue is that assignability is not a transitive relation, however `any` is the main culprit. There are three violations of transitivity that I know of; there may be more:

(I use `<:` for assignability).

1. `string <: any` and `any <: number`, but it's not the case that `string <: number`.
2. `number <: Object` and `Object <: object`, but it's not the case that `number <: object`.
3. `{ x: number; y: number } <: { x: number }` and `{ x: number } <: { x: number; y?: string }` but it's not the case that  `{ x: number; y: number } <:  { x: number; y?: string }`.

**Comment by rkirov** [comment]
@jack-williams I ended up here looking for 'transitivity failures', so I got one more for you (no 'any's)

```typescript
declare let c: {a(): {}|null|void};
declare let b: {a(): void};
declare let a: {a(): unknown};

b = a;
c = b;
// but 
c = a;
```
Also that means it is not worth filing a bug, given the amount of other known failures.

**Comment by shicks** [comment]
Since this seems to be as good a place as any to document transitivity failures and it's not listed yet, there's also some good ones with optional parameters.  [This one][1] is fun because you can run it both directions.

```ts
declare let x: (a?: number) => void;
declare let y: () => void;
declare let z: (a?: string) => void;

y = z;
x = y;
x = z; // error

y = x;
z = y;
z = x; // error
```

[1]: http://www.typescriptlang.org/play/#code/CYUwxgNghgTiAEEQBd4A8Bc8AUUD8WAdgK4C2ARiDAJTwC8AfPAG4D2AlsANwBQoksBElQBPLNlqMWHbn3DQ4iFPABe4-FgDOyGO0IBzSUzadePEfVW80lkdcsqu8APTP4VGKxg9zltLxVbAL8nV3cYTxggA
