### ISSUE TITLE
Bad parse for union type and function type

### ISSUE THREAD

**Issue by Kingwl** [Microsoft/TypeScript#31106]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**
parser, arrow, union

**Code**

```ts
declare const a: string | (a: string, b: boolean) => string
declare const b: string | () => string
declare const c: string | () => string | number | () => boolean
```

**Expected behavior:**
```
declare const a: string | (a: string, b: boolean) => string
>a : string | ((a: string, b: boolean) => string)
>a : string
>b : boolean

declare const b: string | () => string
>b : string | (() => string)

// ?
declare const c: string | () => string | number | () => boolean
>c : string | (() => string | number | (() => boolean))


```
**Actual behavior:**
parse error

**Playground Link:** 

**Related Issues:** 
#25898

**Comment by dragomirtitian** [comment]
Are we sure not requiring the `()` around the function type is a good idea ? Better error messages as #25898 suggests is definitely a good idea, the current error is very unclear.

The problem is that looking at `string | () => string | number | () => boolean`  it is not immediately obvious if the user means `string | (() => string | number | (() => boolean))`  or `string | (() => string) | number | (() => boolean)`. I actually think that more users are probably trying to define the latter (not based on any data just gut feeling).

**Comment by RyanCavanaugh** [comment]
All on board for better error messages, but we really don't want to open the door further to confusing constructs like
```ts
declare const k: number | () => string | boolean;
```

**Comment by Kingwl** [comment]
But what about only for a better error？same as the previous issue
