### ISSUE TITLE
'this' context of type 'void' is not assignable to method's 'this' of type '***'

### ISSUE THREAD

**Issue by asurance** [Microsoft/TypeScript#31123]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**

**Code**

```ts
class a{
    test() {
        t();
        function t(this: a) {
            
        }
    }
}
class b{
    test(this:b) {
        t();
        function t(this: b) {
            
        }
    }
}
```

**Expected behavior:**
No Error
**Actual behavior:**
'this' context of type 'void' is not assignable to method's 'this' of type '***' when call funtion t
**Playground Link:** 
http://www.typescriptlang.org/play/index.html#src=class%20a%7B%0D%0A%20%20%20%20test()%20%7B%0D%0A%20%20%20%20%20%20%20%20t()%3B%0D%0A%20%20%20%20%20%20%20%20function%20t(this%3A%20a)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0Aclass%20b%7B%0D%0A%20%20%20%20test(this%3Ab)%20%7B%0D%0A%20%20%20%20%20%20%20%20t()%3B%0D%0A%20%20%20%20%20%20%20%20function%20t(this%3A%20b)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%7D
**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Your code has an error because `this.test()` inside `function t` will throw.

**Comment by asurance** [comment]
> Your code has an error because `this.test()` inside `function t` will throw.  

So what's the problem?
```typescript
class a{
    test() {
        console.log('test');
        t();
        function t(this: a) {
            console.log('hello')
        }
    }
}
let t = new a();
t.test();
```
if I ignore the error and run the code below(which displayed on the right of playground),I will get the output I expect.
```javascript
var a = /** @class */ (function () {
    function a() {
    }
    a.prototype.test = function () {
        console.log('test');
        t();
        function t() {
            console.log('hello');
        }
    };
    return a;
}());
var t = new a();
t.test();
```
### PlaygroundLink: 
 http://www.typescriptlang.org/play/index.html#src=class%20a%7B%0D%0A%20%20%20%20test()%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log('test')%3B%0D%0A%20%20%20%20%20%20%20%20t()%3B%0D%0A%20%20%20%20%20%20%20%20function%20t(this%3A%20a)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20console.log('hello')%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0Alet%20t%20%3D%20new%20a()%3B%0D%0At.test()%3B

**Comment by julian-sf** [comment]
@RyanCavanaugh Are you sure this is working as intended?  The first example wasn't that great, but the second one is definitely more clear.

> Your code has an error because `this.test()` inside `function t` will throw.

I think you need to expound on that, as I don't see it throwing any errors in the playground: 

http://www.typescriptlang.org/play/index.html#code/MYGwhgzhAEYN4FgBQ1XQC4FMLoBQEppEU1S98BuZU0gMwFcA7YdASwHtGNd0ALViAC5YhYjXHRgnCOxCYAdCHYBzXAHIwaytQkBfHan1IjoSDABGYtFhw9+Q86IM1yVEuIbM2nbnwHDHImcJSWlZBSVVNXMtNxCjUiMjZClGHGgAQWgAXmhGTAB3WAI3DPkbcmQU6XRoACEcvMLocxLkOvLsciA

**Comment by julian-sf** [comment]
Actually, I think I see why this isn't an issue, although I don't see the code throwing an error.

Anyway, the following code doesn't work because the function `t` isn't bound to anything when invoked. If you run the following code:

```typescript
class A {
    test(this: A) {
        console.log(this)
        t();
        function t(this: A) {
            console.log('in t with');
            console.log(this)
        }
    }
}

const a = new A();
a.test();
```

You get the following output:

![image](https://user-images.githubusercontent.com/50758144/71756422-c9c21f00-2e5d-11ea-9af7-94bdf34dbbdb.png)

If you change the `t();` call to `t.call(this);` then it works as expected:

![image](https://user-images.githubusercontent.com/50758144/71756446-ed856500-2e5d-11ea-8320-f6a68f50bc72.png)

**Comment by rouzwelt** [comment]
@julian-sf your answer really was great and helped me alot, clarified everything for me that how I was missing the bound for my functions. thank you

**Comment by mykohsu** [comment]
I think there's still room for confusion here.

```
class C {
  notZ = true;
  constructor() {
    handle(this, () => this.handler());
    handle(this, this.handler);
  }
  handler() {
    console.log(`C ${this instanceof C}`);
  }
}
function handle(c: C, handler: (this: C) => void) {
  handler(); // This fails with the error on the subject
  handler.apply(c);
}

class Z {
  constructor() {
    badHandle(() => this.handler()); // This doesn't fail as expected
    badHandle(() => this.handler() as ((this: Z) => void)); // This fails as expected
    badHandle(this.handler); // This doesn't fail as I expected, but at least it can be re-bound
  }
  handler() {
    console.log(`Z ${this instanceof Z}`);
  }
}

function badHandle(handler: (this: C) => void) {
  const q = handler.bind(new C());
  q();
  handler.call(new C());
}
```

Calling `new Z()` logs both `Z true` and `Z false`, because the arrow function cannot be re-bound.

At first I thought `handler: (this: C) => void` meant that only a bound function can be passed, but it actually allows unbound functions as well and just means `handler` can't be called without a scope being provided.

And, `badHandle(() => this.handler());` shouldn't be allowed but it is because TS treats this as () => void when it should be able to know that this is (this: Z) => void.  `badHandle(() => this.handler() as ((this: Z) => void));` errors as expected.
