### ISSUE TITLE
Exclude not work on [key: string]:any

### ISSUE THREAD

**Issue by vipcxj** [microsoft/TypeScript#31153]
**TypeScript Version:**  3.4.4

**Search Terms:**

**Code**

```ts
interface TestType {
   a: number;
   b: string;
   [key:string]: any;
}
type NTestType1 = {
   [P in keyof TestType]: any;
}
const test:NTestType1 = {} // error missing a and b. this is correct.
type NTestType2 = {
   [P in Exclude<keyof TestType, 'a'>]: any;
}
const test::NTestType2 = {} // no error, we expect show missing b error here.
```

**Expected behavior:**
show missing b error

**Actual behavior:**
no error

**Playground Link:** 

**Related Issues:**

**Comment by jcalz** [comment]
`keyof` on a type with a string index signature will always be at least as wide as `string` which will swallow up all string literals in a union.  That is, `string | "a" | "b"` is collapsed to `string`.  This is known behavior and not considered a bug.  Excluding `"a"` from `string` is not something that can be done yet, although that [might change](https://github.com/Microsoft/TypeScript/pull/29317).

There are [ways](https://github.com/Microsoft/TypeScript/issues/25987#issuecomment-408339599) of extracting the literal keys if you need to do it.  I'd say this issue is a duplicate but I'm not sure [which issue](https://github.com/Microsoft/TypeScript/issues/12215#issuecomment-414777939) it duplicates.  What issues do you think are related? Hmm, looks like you didn't actually search for it (since your "search terms" are empty).   Oh well.

**Comment by vipcxj** [comment]
@jcalz Have you try your solution? it not work. Though it is the true solution to get a known key such as 'a' and 'b' in the example, this is not my finally target. My target is to produce a new type witch include key 'b' and any other unknown string key.
```
type NTestType = Pick<Test, Exclude<KnownKeys<Test>, 'a'> | string>
const test::NTestType = {} // still no error
```

**Comment by dragomirtitian** [comment]
@vipcxj Let's keep discussions polite and constructive. @jcalz was giving you the starting point for a solution, not a complete solution. `KnownKeys` is necessary to craft a solution, but `Exclude<KnownKeys<Test>, 'a'> | string` will result in the same issue that `string` will eat up any literal types you put next to it (those coming from `KnownKeys`)

To actually get it to work, you first have to `Pick` the known keys from the type and then add the index back in. A generic solution (although not extensively tested) could look something like this:

```ts
type KnownKeys<T> = {
    [K in keyof T]: string extends K ? never : number extends K ? never : K
} extends {[_ in keyof T]: infer U} ? U : never;

interface TestType {
   a: number;
   b: string;
   [key:string]: any;
}

// A bit of arm wrestling to convince TS  KnownKeys<T> is keyof T
type OmitFromKnownKeys<T, K extends PropertyKey> = KnownKeys<T> extends infer U ? 
    [U] extends [keyof T] ? Pick<T, Exclude<U, K>>:
    never : never;
type OmitOnIndexed<T, K extends PropertyKey> = 
    OmitFromKnownKeys<T, K> & // Get the known part without K
    (string extends keyof T ? { [n: string]: T[keyof T]} : {}) // Add the index signature back if necessary

const test:OmitOnIndexed<TestType, 'a'> = { } // error

```

**Comment by vipcxj** [comment]
@dragomirtitian thanks, it partially works. I don't know whether it is the most perfect Omit version, it is the most perfect Omit version I have seen.
This is my updated full version:
```ts
type KnownKeys<T> = {
    [K in keyof T]: string extends K ? never : number extends K ? never : K
} extends { [_ in keyof T]: infer U } ? ({} extends U ? never : U) : never; // I don't know why not just U work here, but ({} extends U ? never : U) work
type OmitFromKnownKeys<T, K extends keyof T> = KnownKeys<T> extends infer U ? 
    [U] extends [keyof T] ? Pick<T, Exclude<U, K>>:
    never : never;
type Omit<T, K extends keyof T> = OmitFromKnownKeys<T, K>
  & (string extends K ? {} : (string extends keyof T ? { [n: string]: T[Exclude<keyof T, number>]} : {})) // support number property
  & (number extends K ? {} : (number extends keyof T ? { [n: number]: T[Exclude<keyof T, string>]} : {})) // support number property
``` 
It is very very complicate. and I still not sure it is the perfect version. I think the perfect version Omit function should be built in.

**Comment by dragomirtitian** [comment]
@vipcxj Typescript tends to offer the building blocks to build such types, they also tend not to include very complicated types in the base lib (the relatively simple `Omit` just made it in recently)

Your version includes `number` index which makes the solution more complete. The problem is that we will need to do some even weirder types when #26797 drops and  the index can be any type not just `number` or `string`.  

The root problem is that there isn't a good way to get the index signature out of a type and to differentiate known keys from the index signature. While this solution works, I do believe it might break in the future (not necessarily break for existing code, but not work with new features). This is also a very good point against including it in the base lib

**Comment by vipcxj** [comment]
@dragomirtitian what I mean is not including it in lib but include it in the syntax level or some native level. Omit is the very very often used type, and it even tightly bind to some syntax, such as the following example. But I haven't seen such a compete version before, even the official version is incomplete.
```ts
interface TestType {
   a: number;
   b: string;
   [key:string]: any;
}
const test: TestType = { a: 1, b: 'test', c: {}, d: 1 }
const { a, ...rest } = test // it seems that typescript think the type of rest is {}. and auto complete hints of rest show nothing. Its type should be Omit<TestType, 'a'>. this should be a very base feature.
```

**Comment by felschr** [comment]
As reported in https://github.com/microsoft/TypeScript/issues/44143 typescript 4.3 broke the `KnownKeys` type which also breaks the `OmitFromKnownKeys` implementations posted here.
In the above issue there's a new `KnownKeys` implementation which works in typescript 4.3 but `OmitFromKnownKeys` remains broken.

I've tried fixing its implementation and I came up with a solution with a small caveat, though:
```ts
type KnownKeys<T> = {
  [K in keyof T as string extends K
  ? never
  : number extends K
  ? never
  : K]: T[K];
};

type OmitFromKnownKeys<T, K extends keyof T> = KnownKeys<T> extends infer U ?
  keyof U extends keyof T
  ? Pick<T, Exclude<keyof U, K>> & Pick<T, Exclude<keyof T, keyof KnownKeys<T>>>
  : never : never;
```

While this is generally working, it resolves to a type like `Pick<Test, "b" | "c"> & Pick<Test, string | number>` instead of an inferred object type, which most would likely prefer:
```ts
type Test = {
  [x: number]: any,
  [y: string]: any,
  a: number,
  b: string,
  c: string,
}

// resolves to:
// const test: Pick<Test, "b" | "c"> & Pick<Test, string | number>
// instead of:
// const test: {
//     [x: string]: any;
//     [x: number]: any;
//     a: string;
// }
const test: OmitFromKnownKeys<Test, "b" | "c"> = {
  a: 42,
  [0]: 21,
  ["something"]: "test",
}
```

Does anyone have an idea for how to make this return the object type instead without losing the known keys?

**Comment by augustobmoura** [comment]
Just a friendly bump, because I found a similar situation in my code, and I found that you can also remove the index signature (as shown [here](https://stackoverflow.com/a/68261113/4595583)), `Omit` the properties, and then re-add the signature back, like so:

``` typescript
// Returns a type with the same well known props but without the index signature
type NoIndex<T> = {
  [K in keyof T as {} extends Record<K, 1> ? never : K]: T[K]
}

// Inverse of NoIndex
type OnlyIndex<T> = {
  [K in keyof T as {} extends Record<K, 1> ? K : never]: T[K]
}

// Omit from NoIndex version of T, and then itersects with the IndexPart of it
type OmitFromKnownKeys<T, K> = Omit<NoIndex<T>, K> & OnlyIndex<T>

type type Test = {
  [x: number]: any,
  [y: string]: any,
  a: number,
  b: string,
  c: string,
}

type TestOmitted = OmitFromKnownKeys<Test, 'b' | 'c'>
```

**Comment by whzx5byb** [comment]
> Does anyone have an idea for how to make this resolve to the object type instead without losing the known keys?

@felschr You could use [Any.Compute](https://millsp.github.io/ts-toolbelt/modules/any_compute.html) util type from https://github.com/millsp/ts-toolbelt to provide a better display.

I have extracted the code there and made an [example](https://www.typescriptlang.org/play?#code/PTAECUFMBcFcCcB2BnUBDU0CeAHSoB3AS2gAtNT9k0BbfAyAG0YFoBrRAewMVB3k45kAGlAAjWNEIlSnSRXxFEAE0gAPUMiIBzRGjjxIAWABQ2PKABynAJIr1AHgAqAPlABeUAG9ToUAG0AaVAlUDZILE4AM1AndFQvAF9QdWhIFVQoAGNOeGUHQNEARjcAflBESAA3SHhQAC5QQIBdRqcg5tNE01MQUDsa+GR8aKtbezVROjREJW0QqU5ERixQbRhUMkUJzR09AxGYjHNIUT3cudBOLbqGZjCuHj4BIVMT0AB5Zaw7VTVnNyeHwmPxBEK8cKRGJxNAJZKpdLKTKQHJ5ArFMpNBoVaq1VqxDpdHomPofGgkUBRAQ0Ma-dSgQZaJZXaGiGbKBS8JRpIYo6CoYhkBTgv6QDk4NDwRYxEhvXD4MkkABi1MCj0QgQiyGcomCCIyYQio2sdP+rkBoAAwpwaDhJJAlYx9A5fH5PuToA4TRMAbq3AAyT7fU0A0wuADcxL6KptoFI0GgQnqIG0MlgYgAdDkaMBycxkDhgPyWNBOJxGGImNBgGJGJwxLnYTzgMg5PAspBkMAAIKILDAa22+0Z-lyiwAIVgREY0DsHldfgAPqAlbBEFloEQlgvQMuAKLwATwHfLgAi+mMILdy68hjQyiWKwCAGUsDQxOWR5xn9B4HMnGg2j4sgv5zN0V5LhAkDaHuag4CeoAAOLpLU+i5GO+CaqsnggX+iDzMuiCwO+tS7pob4fowxLvIOdppI6zrdikahpAaMxYICO5MfqSKgJO06zrw5RMfUXHMaxvHdoeaBYA47EuDuwniYiqBSfAMkONkuT5FhbJ9i4CkQW6wnSbJXhgqEkKjN2-hESR8DNPiNl2ZWDkdMkgZrhw3CIIZbpuo03Y7oFykGlA96PlgakafJO5+EpPHIhF3zRbJWlorp6D6X5-nGVByUrKlDjmcEllGjEznEa5jmBbZVV4u5oCeYg3k8DluXYkFRl+I0JXgoaUKgN2TmNc1rWIJGJjUfKsSdlIQKuv4aiNC5eKNOxwiLVgjS4XM+Iba6aArfV8CbVeYg7aB+FnX4WSXXh2hneBGGzSBioJmKHjusqqrqlh2pOHNogAORiMDZHA1kwMuEAA), based on https://github.com/microsoft/TypeScript/issues/31153#issuecomment-1074283505 by @augustobmoura.

**Comment by yepitschunked** [comment]
I stumbled upon this simple type which I think solves the Omit problem in this thread:
```
type OmitFromMappedType<Type, ToOmit> = {
  [Property in keyof Type as Exclude<Property, ToOmit>]: Type[Property];
};
```

Using [key remapping](https://www.typescriptlang.org/docs/handbook/2/mapped-types.html#key-remapping-via-as), we can map over and `Exclude` the individual keys of `Type`, instead of passing the whole `keyof` union to `Exclude`. We never run into the union collapse issue since we're considering each key individually. 

I made an [example](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKhDOwoF4oG8CwAoKUDaAHgFxQB2ArgLYBGEATgLokCGpIANNrniCYnQEtSAcyZRWHLuJIUa9TjijU+wQSIW4AxirXCFAX2zZQkKAHlKA4ADE6Ae0oBZZmEgATGOAgAeT5HawdhZWAHwo6FJ4AAr2kHSgUEJQANYQIHYAZrBe4vBQAKIEmgA25G4+MXZxoAEwQZbAIWJ+ENGx9KAMANzY+j1YxjlwiMHAwBBu4aO2Ds6uEy2+CMABAOTUq1AAPlCrmqshQA) based on @whzx5byb's example above.
