### ISSUE TITLE
Import suggestion/fix should respect ES module target

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#31219]
**TypeScript Version:**  3.4.1

**Search Terms:** import suggestion fix module esnext es modules target assignment

**Code**

```ts
// ./typings.d.ts
declare module 'foo' {
    const _default: number;
    export = _default;
}
```

```jsonc
// ./tsconfig.json
{
    "compilerOptions": {
        "module": "esnext"
    }
}
```

```ts
// main.ts
foo;
```

When I activate the import suggestion/fix for `foo`:

![image](https://user-images.githubusercontent.com/921609/57107010-e7524e00-6cfc-11e9-86fa-7a876f0fad05.png)

**Expected behavior:**

``` ts
import * as foo from "foo";

foo
```

**Actual behavior:**

``` ts
// Error:
// Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.
import foo = require("foo");

foo
```

**Comment by andrewbranch** [comment]
👍 I've been hit by something similar myself—when using JS with `@ts-check` and CommonJS, auto-imports give me ES6 module imports.

**Comment by rpgeeganage** [comment]
@DanielRosenwasser ,
May I give a try to fix this?

**Comment by DanielRosenwasser** [comment]
Sure! Here's what I think is the expected behavior for an `export = `

* `esModuleInterop`/`allowSyntheticDefaultImport` is on: `import foo from "foo"`
* Otherwise, if the entity is an object type that's **not** callable/constructable, `import * as foo from "foo";`
* Otherwise, `import foo = require("foo")`

Even though that last one will cause an error in `es2015`+ module targets.

**Comment by rpgeeganage** [comment]
@DanielRosenwasser 
 Thanks a lot. I will work on this.

**Comment by rpgeeganage** [comment]
@DanielRosenwasser ,
Is `getTargetOfImportClause` method (at line 2024) in https://github.com/microsoft/TypeScript/blob/master/src/compiler/checker.ts
**Or**
is `getHelperExpressionForImport` in https://github.com/microsoft/TypeScript/blob/master/src/compiler/transformers/module/module.ts#L750
handling this ?

**Comment by DanielRosenwasser** [comment]
I'm unfortunately not familiar enough with the codebase but I think the first one is what you want.

**Comment by rpgeeganage** [comment]
@DanielRosenwasser ,
Thanks. I'll look into it.

**Comment by rpgeeganage** [comment]
@DanielRosenwasser ,
I'm sorry that I could find the location where this causes. Can you give me some more details if possible? Thanks a lot.

**Comment by andrewbranch** [comment]
@rpgeeganage if you’re still interested, I think the place to look is around here: https://github.com/microsoft/TypeScript/blob/a150d55592dbad6a89a12b6612723c1bd73213a1/src/services/codefixes/importFixes.ts#L79-L82

Otherwise, I’ll probably circle around to this next week.

**Comment by rpgeeganage** [comment]
@andrewbranch,
Thanks a lot for the help, I couldn't figure it out.
I'll try to dig into it this week.

**Comment by rpgeeganage** [comment]
@andrewbranch ,
I'm sorry, I won't be able to look into this.

**Comment by andrewbranch** [comment]
> * Otherwise, import foo = require("foo")
>
> Even though that last one will cause an error in es2015+ module targets.

@DanielRosenwasser When the module target is es2015+, I think we should stick with `import * as foo from "foo";` for that one, because IMO the error message gets more to the root of the issue:

> `This module can only be referenced with ECMAScript imports/exports by turning on the 'allowSyntheticDefaultImports' flag and referencing its default export. ts(2497)`

vs.

> `Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead. ts(1202)`

which suggests you try several things that also aren’t going to work.

Plus, IIUC, even callable/constructable objects work with `import *` these days, even though it’s wrong according to the spec:

![image](https://user-images.githubusercontent.com/3277153/60289599-a2493300-98cb-11e9-96d4-3caeadba66cb.png)

The only way I could trigger the “This module can only be referenced...” error was by writing `export = SomeTypeOrInterfaceOrClass`.
