### ISSUE TITLE
Type conversion doesn't actually perform conversion

### ISSUE THREAD

**Issue by acid1103** [Microsoft/TypeScript#31229]
This is a fairly straightforward "bug" that likely won't be fixed, but as I couldn't find any references to it, I wanted to bring it up to get an official comment.
The way TypeScript currently handles `as unknown as InsertTypeHere` is by doing precisely nothing, since JavaScript doesn't have strict types. However, there are times when doing *something* would be the expected behavior. I'll provide a simple example here.

**TypeScript Version:**  3.4.0-dev.201xxxxx

**Code**

```ts
const value: number = true as unknown as number;
console.log(value);
```

**Expected behavior:**
I would expect the above code to write `1` to console.

**Actual behavior:**
However, it writes `true` to console, despite my explicit instruction to convert the type to a number.

**Playground Link:** [playground](https://www.typescriptlang.org/play/#src=const%20value%3A%20number%20%3D%20true%20as%20unknown%20as%20number%3B%0D%0Aconsole.log(value)%3B%0D%0A)

**Search Terms:** type conversion as keyword doesn't convert

**Comment by jcalz** [comment]
You might be confused about what the `as` operator is actually doing.

From [the FAQ](
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-this-incorrect-cast-throw-a-runtime-error):
> TypeScript has *type assertions*, not *type casts*. The intent of `x as T` is to say "TypeScript, please treat `x` as a `T`", not to perform a type-safe run-time conversion.

From [the Handbook](https://www.typescriptlang.org/docs/handbook/basic-types.html#type-assertions):

>Type assertions are a way to tell the compiler “trust me, I know what I’m doing.” A type assertion is like a type cast in other languages, but performs no special checking or restructuring of data. It has no runtime impact, and is used purely by the compiler. TypeScript assumes that you, the programmer, have performed any special checks that you need.


It's safe to say that TypeScript will never support having a runtime cast operator, because it goes against [TypeScript Design Non-Goal #5](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#non-goals):
> [It is not a goal of TypeScript to] add or rely on run-time type information in programs, or emit different code based on the results of the type system. Instead, encourage programming patterns that do not require run-time metadata.

If you want to change the type at runtime, you have to write code that exists at runtime, like

```ts
const value: number = Number(true);
console.log(value);
```

If that seems beside the point to you (e.g., "well, of course it will be a number at runtime if I call `Number()` on it... that would happen in plain JavaScript also!  I want *TypeScript* to do it for me!") then you have not yet become one with the ways of TypeScript.  In this case, the benefit is that the compiler agrees that `Number(true)` will be of type `number` at runtime and the above code compiles with no errors.  Type assertions should be reserved for times when you know what's going on at runtime but the compiler can't, and you'd like to make it stop complaining:

```ts
const valueOops: number = (Math.random() > 9000 ? "over nine thousand!!" : 1); // error!
// compiler: Type '1 | "over nine thousand!!"' is not assignable to type 'number'.
// me: But Math.random() returns a value between 0 and 1.  It *can't* be over 9000.
// compiler: Well, I don't know that.  So that's an error.
// me: Oh yeah?  I'll show you who's the boss here:
const valueOkay: number = (Math.random() > 9000 ? "over nine thousand!!" : 1) as number; // okay
// me: I'm smarter than you 🤓, and I know it's going to be a number 
// compiler: sure thing, just don't blame me if something goes wrong with that at runtime.
```

**Comment by acid1103** [comment]
Ah, I missed that when I was skimming over the FAQ! But that's ultimately what I was looking for. And I believe it's still somewhat helpful to have an issue (which is easier to search for with issues like this imo) which reiterates this for others who might miss that, so thank you. :)

**Comment by RyanCavanaugh** [comment]
Imagine if we had documentation though! 😕
