### ISSUE TITLE
is it needed to assign undefined to a variable to improve garbage recycling?

### ISSUE THREAD

**Issue by zzzgit** [Microsoft/TypeScript#31228]
```ts
    let _bus: EventEmitter = new EventEmitter()
    // after use
    _bus = undefined
```

There's a variable `_bus`. After use, I want to assign `undefined` to `_bus` to improve garbage recycling. That's what I learned in vanilla js period.

However, I got an error:

  `   Type 'undefined' is not assignable to type EventEmitter.ts(2322)`

So, is it still needed to do this to free the memory?

**Comment by nmain** [comment]
I'd rather not offer an opinion on garbage collection, which will depend a lot on the underlying code and the JS engine in use, and is not Typescript's problem.  But if you want to do this, Typescript certainly supports it:

```ts
    let _bus: EventEmitter | undefined = new EventEmitter()
    // after use
    _bus = undefined
```

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
