### ISSUE TITLE
Suggestions not accepted when using commit characters

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#31244]
- VSCode Version: 1.33.1
- OS Version: 10.14.4

Steps to Reproduce:

1. `mkdir test`
2. `code --disable-extensions --user-data-dir temp test`
3. Create new JS file

```
const mySpecialVar = 1;
const foo = mySpec<cursor>
```

When suggestions appear, press `;` (commit character).

Expected: suggestion is accepted + `;` is inserted.
Actual: `;` is inserted.

OTOH, this does work as expected:

```
const mySpecialVar = 1;
const foo = 1 + mySpec<cursor>
```

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
The root cause of this is that the completion info at this location returns `isNewIdentifierLocation: true` so we disable all commit characters.

We could either look into fixing this case (although I'm not sure if it would regress some other completion behavior), or add commit characters to the tsserver #27623

**Comment by mjbvz** [comment]
Alternatively, we could always treat `;` as a commit character. One case where that could possibly cause issues is declaring a property or method in class:

```js
class Foo {
   b|
}
```

**Comment by duzenko** [comment]
Happy three years anniversary!
