### ISSUE TITLE
hatamtehrani

### ISSUE THREAD

**Issue by hatamtehrani** [microsoft/TypeScript#31257]
Please fill the following out:

- Name: hatamtehrani
- Homepage url: https://hatamtehrani.com
- Brand Guidelines/Licensing: https://hatamtehrani.com/about-us/
- Logo: https://hatamtehrani.com/wp-content/uploads/2016/09/logo-hatam.jpg

> Example:
>
> Name: Microsoft
> Homepage url: https://microsoft.com
> Brand Guidelines/Licensing: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx
> Logo: https://news.microsoft.com/microsoft-news-center-photos/msft_logo_rgb_c-gray/

**Comment by orta** [comment]
Hey folks -we're looking at a new website and it's likely that the friends of TypeScript page isn't going to make it to the new site. This is mainly because close to everyone is a friend of TypeScript now and listing folks kinda feels a bit un-inclusive to everyone else. 

So I'm going to close this issue - thanks for posting to apply
