### ISSUE TITLE
Suggestion: reversed syntax for importing symbols from a module

### ISSUE THREAD

**Issue by BenedekFarkas** [Microsoft/TypeScript#3127]
So instead of having to type:
```javascript
import {} from "whatever";
```
and then go back to fill in the {} with IntelliSense, a LINQ-like syntax would be easier to use like this:
```javascript
from "whatever" import {Something};
```

**Comment by tinganho** [comment]
I would love to have this!

**Comment by Piedone** [comment]
Yes! Had the same thought during @ahejlsberg 's Build talk. It's practically the same rationale than for the reversed LINQ syntax in C#.

**Comment by AbubakerB** [comment]
I think everyone would love that! I'm sure even the TS team (i think Anders even pointed it out during the build talk), but the design goals of TS is to follow the ES specs as much as possible (it makes everything so much easier for them -- and us) [[Spec-Goal-6](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#goals)]. If it wasn't for that rule, im sure 100s of things would be different, but it's that goal (and others) that makes it oh so very awesome!

One thing that could be suggested is that we could type it as
```javascript
from "whatever" import {Something};
```
and it get generated as 
```javascript
import {Something} from "whatever" ;
```
but at the same type also support the ES6 spec of typing `import` first then `from` second...., but that's too cumbersome and not worth it i guess.

Another suggestion could be to create a VS snippet for typescript so that when you type `"import[TabKey]"` the following line is emitted with the cursor ($c) inside the `from ""`, as follows:
```javascript
import {} from "$c" ;
```
then another tab would take you within the {} 

.... maybe?

**Comment by tinganho** [comment]
@AbubakerB that would be a very good solution to this problem. I think those who sit in TC39 should have thought about this problem. :angry:

**Comment by AbubakerB** [comment]
@tinganho yea, but I'm sure they had their reasons though (or maybe they just did it for the laughs!)

**Comment by Piedone** [comment]
Good point about ES compatibility... Indeed, it would be a limited but for part of the audience still awesome thing to at least add better support in tooling to make the experience like it would be with the reversed syntax. And if this could be built directly into the TS compiler maybe this tooling support could be accessible for other editor plugins easily?

**Comment by ahejlsberg** [comment]
Much as it would be nice to have `from` come before `import` this is already a done deal and alignment with ES6 trumps here. However, I agree it would be nice to have snippet support so you could easily tab between the fields.

**Comment by danquirk** [comment]
Also see:
https://github.com/Microsoft/TypeScript/issues/2370#issuecomment-81664304
https://github.com/Microsoft/TypeScript/issues/2371#issuecomment-81905846
