### ISSUE TITLE
TypeScript support for Universal App Shared project

### ISSUE THREAD

**Issue by craigktreasure** [microsoft/TypeScript#313]
Moving this over from CodePlex (14 votes, assigned to jonturner, http://typescript.codeplex.com/workitem/2459):

I recently converted my Windows Store app to a Universal App with a Windows Phone and a Shared project. I moved all of my TS files to the Shared project, but TypeScript doesn't behave the way that it used to in a regular JS project. I can't get it to generate source maps and i can't get the JS file nested under the TS file (VS hangs and won't load the project). I basically tried coping the TS configurations from the Windows Store JS project to the .Shared.shproj and the S.Shared.projitems files. I realize that 2013.2 is RC currently, but i'm hoping there is a supported way of adding TS support to a Universal Shared project. 

Also, this really scenario really begs support for cross project support since Universal Apps assume you'll have files spread across the different projects.

**Comment by lukianol** [comment]
This feature is really missing. TypeScriptCompile items are not supported in shproj. Please let me know if there is any easy workaround to bring the support. I guess the support is defined somewhere in code sharing targets of Visual Studio

**Comment by AbraaoAlves** [comment]
+1

**Comment by AbraaoAlves** [comment]
@lukianol 
My workaround was: create a website in same directory of shared project. VS can not do this visually, but by editing .sln.
To do this see my second commit here: [repo/WorkaroundToUniversalAppWithTS](https://github.com/AbraaoAlves/WorkaroundToUniversalAppWithTS)

With that, I edit .ts files with total visual studio support, without losing integration with explorer TaskRunner

[tested on vs2015 ctp6]

**Comment by arangas** [comment]
Another workaround is to create an "HTML Application with TypeScript" project alongside the other projects in your solution. Then include the files from your Shared, etc... projects by adding them **as a link**.

**Comment by Halofreak1990** [comment]
I have the same issues as the OP, but with a 'normal' WinJS app I converted to TypeScript.
Visual Studio does not recognize items marked TypeScriptCompile, and, like the OP, nesting the generated JS files with <DependentUpon> hangs the UI because (I believe) it can't resolve the TypeScript file. (Files marked TypeScriptCompile don't show up unless you have 'Show All Files' enabled)

Visual Studio won't even add the files as 'TypeScriptCompile', anyway, instead marking them as Content, meaning no JS will be generated unless I manually edit the project and change the TypeScript files to TypeScriptCompile.

**Comment by BobFrGit** [comment]
I'm now trying to create IoT applications using Node.js and it's very disappointing that Microsoft isn't treating TypeScript as a first class language by providing VS templates to parallel the JavaScript ones. Has Microsoft given up on TypeScript?

**Comment by kitsonk** [comment]
Clearly not @BobFrGit, [vscode](https://github.com/Microsoft/vscode/tree/master/src/vs) is mostly written in TypeScript, @ahejlsberg plus a load of other really bright folks at Microsoft are dedicated to it.  There are several other parts of Microsoft that are starting to contribute and help with it as well, but the beauty of it all is that it is truly open source and loads of non-Microsoft folks are contributing to it as well.  I am not sure what your point of sort of Microsoft baiting is in this issue, but my opinion is that it isn't a valid critique at all.  Just because it doesn't have exactly what you are looking for at this very moment isn't cause to throw the baby out with the bathwater.

That is the beauty of open source, you can help the community by contributing and put your critiques into beneficial action!

**Comment by BobFrGit** [comment]
I appreciate all of that but my pragmatic test is whether there is TypeScript counterpart to each JavaScript template including those for windows IoT. I had to roll my own to use TS for IoT. The good news is that support has been improving -- if I create a ..ts file much of the magic happens. So it's close but ...

**Comment by lilred** [comment]
Is this still current? What's the current best approach for TypeScript-based UW apps?
