### ISSUE TITLE
Type guarding broken in overriding method

### ISSUE THREAD

**Issue by JonathanMEdwards** [Microsoft/TypeScript#3132]
```ts
class A {
    foo(x: A): boolean {throw new Error;}
}
class B extends A {
    value: number;
    foo(x:A) {
        return x instanceof B && this.value === x.value;
    }
}
```
Error:(7, 51) TS2339: Property 'value' does not exist on type 'A'.
Error goes away if delete the definition of A.foo.
Error in 1.4 and 1.5 beta.

**Comment by ahejlsberg** [comment]
Wow, this one has a good deal of subtlety in it.

Here's what happens: In order to figure out if the `x instanceof B` type guard should narrow the type of `x` we first check if the type of `x` is a subtype of `B`. That is a structural check, so we need to know the (inferred) return type of `foo` in `B` in order to relate it to `foo` in `A`. However, attempting to do that inference creates a circularity, so we short circuit type inference and the return type becomes `any`. That in turn causes `B` not to be a ***subtype*** of `A`, which causes the type guard not to apply, which causes `x` not to be narrowed.

The reason the error goes away if you delete `foo` in `A` is that `A` then becomes an empty type, which is a subtype of `B` no matter what we infer for the return type of `foo` in `B`.

The fix here is to add a `boolean` return type annotation to the `foo` method in `B`. Probably a good idea to begin with.
