### ISSUE TITLE
Why can a string of type any be assigned to type number?

### ISSUE THREAD

**Issue by DongGrudge** [microsoft/TypeScript#31332]
`
let str: any= 'str'
let num: number = str //ok
`

**Comment by j-oliveras** [comment]
Because this is the reason of the type `any`: be assignable from and to any other type. See it on [basic types](https://www.typescriptlang.org/docs/handbook/basic-types.html#any). Recommendation, read the [FAQs](https://github.com/microsoft/TypeScript/wiki/FAQ).

Better ask questions to stackoverflow.
