### ISSUE TITLE
Revert this-parameter filtering for methods

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#31349]
We believe https://github.com/microsoft/TypeScript/pull/20616 may be the cause of some recent slowness in editor completions. We are considering reverting the feature to increase performance (admittedly at the expense of some editor UX).

**Comment by DanielRosenwasser** [comment]
Removing the logic doesn't seem to do much from what we've seen. Completions are still ridiculously slow.

**Comment by ahejlsberg** [comment]
See #31354 for the real fix.

**Comment by ahejlsberg** [comment]
I'm reopening this issue. Turns out this-parameter filtering is also a contributor to the slowdown, it's just that the eager conditional type true/false branch resolution is the main offender. I have verified that removing the this-parameter filtering greatly speeds up completions with styled-components. We basically need both fixes.

**Comment by DanielRosenwasser** [comment]
Understandable if we have to, but it would be unfortunate. Libraries like [fp-ts v2 would be affected](https://mobile.twitter.com/GiulioCanti/status/1127249761134948352).

**Comment by mattiamanzati** [comment]
Is it really worth it? Will some flag to turn this on be present? DX will suffer a lot :/
