### ISSUE TITLE
Allow array `concat` to concat arrays of different types

### ISSUE THREAD

**Issue by golopot** [microsoft/TypeScript#31355]
**TypeScript Version:**  3.5.0-dev.20190511

**Code**
```ts
[0].concat('')
// Argument of type '""' is not assignable to parameter of type 'number | ConcatArray<number>'.
```

**Expected behavior:**
The concated array has type `(number|string)[]`.

**Actual behavior:**
Error.

**Possible fix:**
In https://github.com/microsoft/TypeScript/blob/b7fe99a88c59bd652029bdfe5b6ba8709a677838/lib/lib.es5.d.ts#L1231

```diff
interface Array<T> {
- concat(...items: ConcatArray<T>[]): T[];
+ concat<U>(...items: ConcatArray<U>[]): (T|U)[];
```
**Playground Link:** 
https://www.typescriptlang.org/play/#src=%5B0%5D.concat(%5B''%5D)

**Related Issues:** 
#29604 

**Search Terms:**
array concat

**Comment by jcalz** [comment]
You can always use declaration merging to add a generic overload to `Array.concat()` if you find it useful in your own code:
```ts
// declaration merge
interface Array<T> {
    concat<U>(...items: (U | ConcatArray<U>)[]): (T | U)[]
}

const okay = [0].concat("");  // Array<string | number>
```
[Playground link](http://www.typescriptlang.org/play//#src=%2F%2F%20declaration%20merge%0D%0Ainterface%20Array%3CT%3E%20%7B%0D%0A%20%20%20%20concat%3CU%3E(...items%3A%20(U%20%7C%20ConcatArray%3CU%3E)%5B%5D)%3A%20(T%20%7C%20U)%5B%5D%0D%0A%7D%0D%0A%0D%0Aconst%20okay%20%3D%20%5B0%5D.concat(%22%22)%3B%20%20%2F%2F%20Array%3Cstring%20%7C%20number%3E%0D%0A)

Or, you can widen the array element type yourself before `concat`ing to it:

```ts
const okay = [0 as string | number].concat(''); // Array<string | number>
```
[Playground link](http://www.typescriptlang.org/play//#src=const%20okay%20%3D%20%5B0%20as%20string%20%7C%20number%5D.concat('')%3B%20%2F%2F%20Array%3Cstring%20%7C%20number%3E)

Before the standard library is modified for everyone, though, you'd want to establish that this use case is common enough in real-world code to warrant it.   The compiler tries to catch potential bugs.  For real uses of `concat()` in the wild, what is the false-positive (the compiler thinks good code is a bug) rate of the current typings, and how does that compare to the false-negative (the compiler doesn't catch a bug) rate of the proposed typings?

**Comment by RyanCavanaugh** [comment]
Duplicate #26378

**Comment by Brodzko** [comment]
I have hit this issue while developing a Vue.js component that accepts a `value` property which can be of type `string | string[] | number | number[]`.

It is an option-list type component that allows a user to select either a single or multiple options from a given list, the options being indexed by string or number ids. The reason I'm not only accepting arrays as the `value` prop is that the component is bound directly to my form model, which is in turn created automatically from the view model, so keeping proper value type was a requirement.

Within the component however, it is handy to always work with the prop as an array, so I created a simple getter using the `[].concat()' trick. No biggie in vanilla JS but turned out to be an issue with TS. I have dealt with it like so:

```
get valueArray(): string[] | number[] {  
    return ([] as (string | number)[]).concat(this.value || []) as string[] | number[];  
}
```
