### ISSUE TITLE
Object.assign should support a rest operator-only parameter

### ISSUE THREAD

**Issue by alexandercerutti** [microsoft/TypeScript#31360]
**TypeScript Version:**  3.4.5

**Search Terms:**
Object.assign, assign, rest

**Code:**

```ts
function selfContainedTest(contents: any[]) {
	return Object.assign(
		...contents.map((fileName, index) => {
			// do something to return an array of objects
                        const parsedContent = readSomehowTheFileContent();
			return { [fileName]: parsedContent };
		})
	);
}
```

**Expected behavior:**

No error.

**Actual behavior:**

VSCode highlight `...contents.map( ... )` as an error because `target` of `Object.assign` is not provided, while it should be the first object of the array returned by `.map`;

___

I already applied the edit `lib.es2015.core.d.ts` and was going to create a PR but since I didn't find any related issue with `Backlog` milestone, I stopped myself and opened an issue.
I already tested it in typescript@next.

Thank you.

**Comment by fatcerberus** [comment]
The problem is that calling `Object.assign` with no arguments is an error, so TypeScript rightly forces you to provide at least one:
```text
> process.version
'v12.1.0'
> Object.assign()
Thrown:
TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
```

TS has no way of knowing at compile-time that `contents` will always have at least one item, so it flags it as an error.  A workaround would be to pass an empty object `{}` as the first argument, before the spreaded array.

On a side note: `Object.assign` mutates its first argument.  Knowing that this is the case, I would consider the pattern above to be somewhat suspicious in general even if there was no error.

**Comment by alexandercerutti** [comment]
Oh, I see your point. Yeah, I was considering that maybe it was not a properly correct pattern. Anyway, I'm moving my project to Typescript. There are some still valid choices I made in Javascript that might not be really "safe".
So, okay. Luckily I did not open the PR. 😂
Thank you @fatcerberus.
