### ISSUE TITLE
New Website Logo: [Golrang Industerial Group]

### ISSUE THREAD

**Issue by MasoudBimar** [microsoft/TypeScript#31367]
Name: Golrang Industerial Group
Homepage url: https://golrang.com/
Brand Guidelines/Licensing: https://en.golrang.com/history-of-golrang-industrial-group/
Logo: https://golrang.com/img/gig-logo.png

**Comment by orta** [comment]
Hey folks -we're looking at a new website and it's likely that the friends of TypeScript page isn't going to make it to the new site. This is mainly because close to everyone is a friend of TypeScript now and listing folks kinda feels a bit un-inclusive to everyone else. 

So I'm going to close this issue - thanks for posting to apply
