### ISSUE TITLE
"d" files for organizing project

### ISSUE THREAD

**Issue by akopchinskiy** [microsoft/TypeScript#31397]
Is it possible to use .d files for organizational purposes? For example to store type structures separated from realization:
`data.ts` file
```ts
class MyClass {
  constructor(public prop: IMyObject){
  } 
}
```
`data.d.ts` file
```ts
interface IMyObject {
  prop1: string
  prop2: number
}
```

Currently my `.ts` file doesn't recognize its corresponding `.d.ts` file

**Comment by dizel3d** [comment]
@akopchinskiy yes, you should have different files names. E.g. `data.ts` and `data-types.ts`.

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!

**Comment by akopchinskiy** [comment]
@RyanCavanaugh Why then this repo allows to select "question" type of a topic?
And I don't like Stack Overflow. It has very toxic community.

**Comment by RyanCavanaugh** [comment]
I don't like Taco Bell but that doesn't mean McDonald's has to serve me tacos.

**Comment by akopchinskiy** [comment]
@RyanCavanaugh Actually, MD have taco menu.

**Comment by dragomirtitian** [comment]
@akopchinskiy FYI: I'm on Stack Overflow all the time, I try to keep it non-toxic. At least for the TS tag, the conversations are usually polite and productive 😊. Not all corners of SO are the same.
