### ISSUE TITLE
Accessing generics from inherited type

### ISSUE THREAD

**Issue by pq987** [microsoft/TypeScript#31401]
```ts
abstract class Handle<T> {}
```
```ts
class Foo<K, V> {}
```
```ts
class Bar extends Foo<string, number> {}
```
```ts
class Baz extends Handle<Bar> {}
```

The issue I'm facing is to get the `Baz` class to recognise the inherited generics. I would like to add a method that ensure that a parameter with the type `string` has a return type of `number` in the example above. However, I would only like to have 1 generic type in the `Handle` class. I could change the signature to `Handle<K, V>` and then pass `Handle<string, number>` but that seems counter intuitive since there may be a way to somehow access the 2 generics from `Bar`?

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!

**Comment by pq987** [comment]
@RyanCavanaugh Thanks for the comment, I have already asked on Stack Overflow [here](https://stackoverflow.com/questions/56103566/accessing-generics-from-inherited-type), however I couldn't really find a solution there so I thought that it may have been a TypeScript limitation. Apologies if this is the wrong place.
