### ISSUE TITLE
function ...args with generic union narrows incorrectly after second param

### ISSUE THREAD

**Issue by ChuckJonas** [microsoft/TypeScript#31413]
**TypeScript Version:**  3.4.x (latest ts-playground)

**Search Terms:**
...args with generic to narrow

**Code**

```ts
//setup
type QueryField<T> = keyof T; 

interface FunctionField<T> {
    fn: 'count' | 'avg';
    alias?: string;
    field: QueryField<T>;
}

class fieldBuilder<T>{
    public select<F extends FunctionField<T>, P extends QueryField<T>>(...args: Array<P | F>) {}
}


//example error
interface Foo{
    x: string;
    y: number;
    z: boolean;
}

let builder = new fieldBuilder<Foo>();

//works
builder.select('x', 'y', 'z'); 

//Type Error: Argument of type '"y"' is not assignable to parameter of type '"x" | FunctionField<Foo>'.
builder.select({ fn: 'count', field: 'x' }, 'x', 'y'); 
```

**Expected behavior:**

I would expect that my `...args` array could be any number of items from `FunctionField<T>` or `QueryField<T>`... 

**Actual behavior:**
As soon as I mix the types, it starts to narrow the `QueryField<T>` based on the first type passed it.

**Playground Link:** 
[Link](https://www.typescriptlang.org/play/#src=%2F%2Fsetup%0D%0Atype%20QueryField%3CT%3E%20%3D%20keyof%20T%3B%20%0D%0A%0D%0Ainterface%20FunctionField%3CT%3E%20%7B%0D%0A%20%20%20%20fn%3A%20'count'%20%7C%20'avg'%3B%0D%0A%20%20%20%20alias%3F%3A%20string%3B%0D%0A%20%20%20%20field%3A%20QueryField%3CT%3E%3B%0D%0A%7D%0D%0A%0D%0Aclass%20fieldBuilder%3CT%3E%7B%0D%0A%20%20%20%20public%20select%3CF%20extends%20FunctionField%3CT%3E%2C%20P%20extends%20QueryField%3CT%3E%3E(...args%3A%20Array%3CP%20%7C%20F%3E)%20%7B%7D%0D%0A%7D%0D%0A%0D%0A%0D%0A%2F%2Fexample%20error%0D%0Ainterface%20Foo%7B%0D%0A%20%20%20%20x%3A%20string%3B%0D%0A%20%20%20%20y%3A%20number%3B%0D%0A%20%20%20%20z%3A%20boolean%3B%0D%0A%7D%0D%0A%0D%0Alet%20builder%20%3D%20new%20fieldBuilder%3CFoo%3E()%3B%0D%0A%0D%0A%2F%2Fworks%0D%0Abuilder.select('x'%2C%20'y'%2C%20'z')%3B%20%0D%0A%0D%0A%2F%2FType%20Erro%3A%20Argument%20of%20type%20'%22y%22'%20is%20not%20assignable%20to%20parameter%20of%20type%20'%22x%22%20%7C%20FunctionField%3CFoo%3E'.%0D%0Abuilder.select(%7B%20fn%3A%20'count'%2C%20field%3A%20'x'%20%7D%2C%20'x'%2C%20'y')%3B%20%0D%0A%20)

**Related Issues:**

**Comment by ChuckJonas** [comment]
Also worth note, I only started seeing this issue once I upgraded from 3.3.1 -> 3.4.x

**Comment by ChuckJonas** [comment]
also, I know the MRE doesn't make sense, but it's the simplest way I could reproduce the error

**Comment by ahejlsberg** [comment]
Before I address the issue, let me ask a question. Are `F` and `P` used anywhere else (such as in the return type) in the signature?

```ts
class fieldBuilder<T>{
    public select<F extends FunctionField<T>, P extends QueryField<T>>(...args: Array<P | F>) {}
}
```

If not, why not write the signature like this:

```ts
class fieldBuilder<T>{
    public select(...args: Array<QueryField<T> | FunctionField<T>>) {}
}
```

In general, type parameters should *always* be kept to a minimum. It is suspicious to have type parameters that don't occur both in an input position (i.e. parameter) and an output position (i.e. return type or callback parameter). And it is particularly suspicious to have type parameters that only occur once in a signature (since you might as well replace them with their constraint).

**Comment by ChuckJonas** [comment]
@ahejlsberg I came to that realization after submitting this (which is part of the reason I said the MRE doesn't really make sense). Just typing the parameters directly does fix the issue.

I didn't close it because it still seemed like a bug? If not, feel free to close this out

**Comment by ahejlsberg** [comment]
So, the reason it worked in earlier versions is because we failed to make any inferences for `P` and `F` and just reverted to the constraints. With #29847 we now _do_ make inferences for `P` and `F`. But because there is nothing discerning about `P` vs. `F` (other than constraints which aren't considered until _after_ inference is finished) the inferences end up being poor. So, we now fail in a slightly different manner that causes an error. But, as I alluded to above, the type parameters should just be eliminated.
