### ISSUE TITLE
Composable interfaces

### ISSUE THREAD

**Issue by alshdavid** [microsoft/TypeScript#31421]
## Search Terms

composition interfaces

## Suggestion

Right now we can extend an interface with another interface. This syntax is similar to the class inheritance syntax where you extend classes with other classes.

```typescript
export interface Animal {
  shout: () => void;
}

export interface Human extends Animal {
 think: () => void;
}
```

What would be awesome is the ability to use composition to describe interfaces.
This would allow us to explain the relationships between interfaces in terms of behaviours rather than inheritance trees. This is model that languages like Go employ

## Use Cases

MPJ gives a much better explanation of the use cases than I can
https://www.youtube.com/watch?v=wfMtDGfHWpA
## Examples

```typescript
export interface Shouter {
  shout: () => void
}

export interface Thinker {
  think: () => void
}

export interface Animal {
  ...Shouter
}

export type Human = {
  ...Shouter
  ...Thinker
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [?] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by kitsonk** [comment]
How is that any different than the first example?  It should have some sort of appreciable benefit to warrant additional syntax in my opinion.  Interfaces are allowed by be extended from multiple other interfaces as well, plus other advanced type operators allow all sorts of other strange ways of combining types.

**Comment by alshdavid** [comment]
I apologize, I have updated my post to include the template and a more comprehensive example

**Comment by AlCalzone** [comment]
You can do that already without adding new syntax. The only caveat is that you have to use types instead of interfaces:
```ts
export interface Shouter {
  shout: () => void
}

export interface Thinker {
  think: () => void
}

export type Animal = Shouter;
export type Human = Shouter & Thinker;
export type SpecialHuman = Shouter & Thinker & {
    poop: () => void;
};
```

**Comment by DanielRosenwasser** [comment]
TIL I am an `Omit<SpecialHuman, "think">`.

**Comment by DanielRosenwasser** [comment]
Being serious now: it's not clear what differences you have in mind. Perhaps its the notion that `extend`ing a type implies perfect subtype compatibility in the presence of conflicts.

If the aversion is to the compatibility checks (which I think are valuable), then do intersection types as above model what you have in mind?

**Comment by lll000111** [comment]
I don't understand the example in OPs original post, [because here it is using current TypeScript](http://www.typescriptlang.org/play/index.html#src=export%20interface%20Shouter%20%7B%0D%0A%20%20shout%3A%20()%20%3D%3E%20void%0D%0A%7D%0D%0A%0D%0Aexport%20interface%20Thinker%20%7B%0D%0A%20%20think%3A%20()%20%3D%3E%20void%0D%0A%7D%0D%0A%0D%0Aexport%20interface%20Animal%20extends%20Shouter%20%7B%0D%0A%7D%0D%0A%0D%0Aexport%20interface%20%20Human%20extends%20Shouter%2C%20Thinker%20%7B%0D%0A%7D%0D%0A%0D%0Aconst%20h%3A%20Human%20%3D%20%7B%0D%0A%20%20%20%20shout%3A%20()%20%3D%3E%20%7B%20%7D%2C%0D%0A%20%20%20%20think%3A%20()%20%3D%3E%20%7B%20%7D%0D%0A%7D%0D%0A).

**Comment by DanielRosenwasser** [comment]
@alshdavid hasn't actually verified whether they have something else in mind, so let's not pile up here. If the existing features solve their problem, then we can close the issue.

**Comment by alshdavid** [comment]
> The existing features solve their problem

The existing features do solve the problem. Union types do facilitate this technically.

I've been thinking a lot about what I am trying to solve with this and I think I am directing my attention at the wrong language feature. 

I'll close this but just to continue the discussion I'd love to get some thoughts from TypeScript contributors.

Using factory functions and leveraging the type system is challenging in TypeScript. Are factory functions something that is generally discouraged with TS?

**Comment by kitsonk** [comment]
I worked with factory functions and composition in TypeScript for quite a while.  There have been some improvements in the language since that time, but really the challenge was more that ECMAScript really hasn't tackled traits and composition as part of the language specification.  It was part of the original Harmony specification, which is where the class syntax came from, but traits were too much for TC39 to swallow in one go, so they put all that on hold, getting the MVP through.  There has been off and on again talking about more syntactical support, but I don't believe currently there is really anyone championing it.

The vast majority of the TypeScript compiler is factory functions, so they are certainly supported.  We eventually gave up on factory functions when the TypeScript team relaxed some constraints in the compiler and made traits/mixins realistic, and ever since then, it has just been easier to embrace the class constructor.  Using a mixin class [would look something like this](https://www.typescriptlang.org/play/#src=type%20Constructor%3CT%3E%20%3D%20new%20(...args%3A%20any%5B%5D)%20%3D%3E%20T%3B%0A%0Aclass%20Animal%20%7B%0A%20%20shout()%20%7B%7D%3B%0A%7D%0A%0Ainterface%20ThinkerMixin%20%7B%0A%20%20think()%3A%20void%3B%0A%7D%0A%0Afunction%20ThinkerMixin%3CT%20extends%20Constructor%3CAnimal%3E%3E(Base%3A%20T)%3A%20T%20%26%20Constructor%3CThinkerMixin%3E%20%7B%0A%20%20return%20class%20Thinker%20extends%20Base%20%7B%0A%20%20%20%20think()%20%7B%7D%0A%20%20%7D%3B%0A%7D%0A%0Aconst%20Thinker%20%3D%20ThinkerMixin(Animal)%3B%0A%0Aconst%20myThinker%20%3D%20new%20Thinker()%3B%0A%0AmyThinker.shout()%3B%0AmyThinker.think()%3B%0A):

```ts
type Constructor<T> = new (...args: any[]) => T;

class Animal {
  shout() {};
}

interface ThinkerMixin {
  think(): void;
}

function ThinkerMixin<T extends Constructor<Animal>>(Base: T): T & Constructor<ThinkerMixin> {
  return class Thinker extends Base {
    think() {}
  };
}

const Thinker = ThinkerMixin(Animal);

const myThinker = new Thinker();

myThinker.shout();
myThinker.think();
```

For the most part the types just flow through, the only thing you have to really deal with is that you have to provide an interface for what each mixin function would mixin, but once you have done that, the types just flow through.

**Comment by alshdavid** [comment]
Thanks for the insight. Do you have any thoughts around the implementation of object declaration in the form of Structs - such as in Go (Golang)?

```typescript
type Person = {
    name: string
    walk: (this: Person, steps: number) => void
}

function walk(this: Person, steps: number) {
    console.log(this.name, 'walked', steps, 'steps')
}

function newPerson (name: string): Person {
    return {
        name,
        walk
    }
}

const person = newPerson('marvin')
person.walk(8)
```

Which would be expressed like this in Go

```Go
type Person struct {
	Name string
}

func (p *Person) Walk(steps int) {
	fmt.Println(p.name + " walked " + steps + "steps")
}

func newPerson(name string) *Person {
	return Person{
		Name: name,
	}
}

const person = newPerson("marvin")
person.Walk(8)
```

Differences are that the receiver is defined behind the function name with an arbitrary, rather than being a `this` as a first parameter. The struct itself is a type, rather than being a factory function that accompanies a type.

Thoughts?

**Comment by kitsonk** [comment]
This behaviour, of having to maintain a seperate interface, is finally what led us away from factory functions and just embrace `class`.  It really isn't TypeScript as much as JavaScript/ECMAScript is a prototypical language, of which `class` is arguably bad/confusing syntactic sugar for a constructor function which instantiates a prototype.

The only "trick" to make it more self sustaining would be [something like this](https://www.typescriptlang.org/play/#src=const%20PersonPrototype%20%3D%20%7B%0A%20%20name%3A%20%22%22%20as%20string%2C%0A%20%20walk%0A%7D%3B%0A%0Atype%20Person%20%3D%20typeof%20PersonPrototype%3B%0A%0Afunction%20walk(this%3A%20Person%2C%20steps%3A%20number)%20%7B%0A%20%20console.log(this.name%2C%20'walked'%2C%20steps%2C%20'steps')%3B%0A%7D%0A%0Afunction%20createPerson(name%3A%20string)%3A%20Person%20%7B%0A%20%20const%20person%20%3D%20Object.create(PersonPrototype)%20as%20Person%3B%0A%20%20Object.assign(person%2C%20%7B%20name%20%7D)%3B%0A%20%20return%20person%3B%0A%7D%0A%0Aconst%20person%20%3D%20createPerson('marvin')%3B%0Aperson.walk(8)%3B%0A), but this could be really awkward:

```ts
const PersonPrototype = {
  name: "" as string,
  walk
};

type Person = typeof PersonPrototype;

function walk(this: Person, steps: number) {
  console.log(this.name, 'walked', steps, 'steps');
}

function createPerson(name: string): Person {
  const person = Object.create(PersonPrototype) as Person;
  Object.assign(person, { name });
  return person;
}

const person = createPerson('marvin');
person.walk(8);
```
