### ISSUE TITLE
Add `KeyOf` and `ValueOf` definitions to built-in lib

### ISSUE THREAD

**Issue by SalathielGenese** [microsoft/TypeScript#31438]
## Search Terms

None -
Empirical experience -

## Suggestion

I want to see added `KeyOf` and `ValueOf`

## Use Cases

Let them distribute union

```ts
let a_or_b_002!: KeyOf<{ a: 'Aa' } | { b: 'Bb' }>;      // "a" | "b"
let a_or_b_003!: KeyOf<({ a: 'Aa' } | { b: 'Bb' })>;    // "a" | "b"
```

## Examples

```ts
let a_or_b_002!: KeyOf<{ a: 'Aa' } | { b: 'Bb' }>;      // "a" | "b"
let a_or_b_003!: KeyOf<({ a: 'Aa' } | { b: 'Bb' })>;    // "a" | "b"
```
instead of

```ts
let a_or_b_001!: keyof ({ a: 'Aa' } | { b: 'Bb' });     // "a" & "b"
```

## Checklist

My suggestion meets these guidelines:

* [x ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ x] This wouldn't change the runtime behavior of existing JavaScript code
* [ x] This could be implemented without emitting different JS based on the types of the expressions
* [ x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by SalathielGenese** [comment]
Here's implementation

```ts
declare type KeyOf<T> = T extends any ? keyof T : never;

declare type ValueOf<T> = T extends any ? T[ keyof T ] : never;
```

**Comment by carpben** [comment]
I use $Values by "utility-types" quite often, and find it useful. Would be nice to see a build-in Typescript version.

**Comment by kisaragi-hiu** [comment]
[A quick search on GitHub](https://github.com/search?q=import+%7BValueOf%7D&type=code) shows a mountain of projects defining their own ValueOf or importing [type-fest](https://www.npmjs.com/package/type-fest)'s ValueOf.

- ValueOf should exist because `keyof` already exists, it is implementable and [has been implemented as a one liner](https://github.com/sindresorhus/type-fest/blob/HEAD/source/value-of.d.ts), but can be hard to get right (justifying its inclusion)
- KeyOf should exist if ValueOf exists for syntax symmetry. (I'd argue `keyof` should've never been an operator since it's syntax on top of JS that could've just been a utility type, but that ship has already sailed.)
- A quick search for "typescript valueof" [shows](https://zhuanlan.zhihu.com/p/437553121) [significant](https://dev.to/smeijer/a-typescript-valueof-implementation-and-how-it-s-built-4gim) [interest](https://zenn.dev/bom_shibuya/articles/ed8fd9f80d3782b1f156), including a sort of duplicate issue (#53521)
- #53521 is a feature request asking for a `valueof` operator. It was for some reason marked as a Question then closed as if it's just a resolved question for how to implement `ValueOf` yourself.

**Comment by kisaragi-hiu** [comment]
This is something that would likely be quite welcomed by the TypeScript community.

**Comment by RyanCavanaugh** [comment]
New utility types are declined by policy. See https://github.com/microsoft/TypeScript/wiki/FAQ#new-utility-types
