### ISSUE TITLE
strictFunctionTypes not working?

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript#31471]
**TypeScript Version:**  version in playground at time of writing.

**Search Terms:**

**Code**

```ts
class Animal { }
class Dog extends Animal {}
class Cat extends Animal {}

declare let f1: (x: Animal) => void;
declare let f2: (x: Dog) => void;
declare let f3: (x: Cat) => void;

f1 = f2;  // Error with --strictFunctionTypes
f2 = f1;  // Ok
f2 = f3;  // Error
```

**Expected behavior:**

Based on [the docs](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html), I am expecting there to be a type error.

**Actual behavior:**

There's no error: see the screen shot:

<img width="934" alt="Screen Shot 2019-05-19 at 8 55 19 PM" src="https://user-images.githubusercontent.com/297678/57995766-b4d47f00-7a78-11e9-9c8e-a1704614a7d1.png">

**Playground Link:** 

[playground link](http://www.typescriptlang.org/play/#src=class%20Animal%20%7B%20%7D%0D%0Aclass%20Dog%20extends%20Animal%20%7B%7D%0D%0Aclass%20Cat%20extends%20Animal%20%7B%7D%0D%0A%0D%0Adeclare%20let%20f1%3A%20(x%3A%20Animal)%20%3D%3E%20void%3B%0D%0Adeclare%20let%20f2%3A%20(x%3A%20Dog)%20%3D%3E%20void%3B%0D%0Adeclare%20let%20f3%3A%20(x%3A%20Cat)%20%3D%3E%20void%3B%0D%0A%0D%0Af1%20%3D%20f2%3B%20%20%2F%2F%20Error%20with%20--strictFunctionTypes%0D%0Af2%20%3D%20f1%3B%20%20%2F%2F%20Ok%0D%0Af2%20%3D%20f3%3B%20%20%2F%2F%20Error%0D%0A)

**Related Issues:**

**Comment by kitsonk** [comment]
TypeScript is a structural type system, not a nominal one.  None of the classes vary in structure (in fact empty interfaces are equivalent to `any`) therefore they are assignable to each other.

Having some basic differentiation between the classes will trigger the expected behaviour: [playground link](https://www.typescriptlang.org/play/#src=class%20Animal%20%7B%0D%0A%20%20%20%20type%3A%20string%3B%0D%0A%7D%0D%0Aclass%20Dog%20extends%20Animal%20%7B%0D%0A%20%20%20%20bark()%20%7B%7D%0D%0A%7D%0D%0Aclass%20Cat%20extends%20Animal%20%7B%0D%0A%20%20%20%20meow()%20%7B%20%7D%0D%0A%7D%0D%0A%0D%0Adeclare%20let%20f1%3A%20(x%3A%20Animal)%20%3D%3E%20void%3B%0D%0Adeclare%20let%20f2%3A%20(x%3A%20Dog)%20%3D%3E%20void%3B%0D%0Adeclare%20let%20f3%3A%20(x%3A%20Cat)%20%3D%3E%20void%3B%0D%0A%0D%0Af1%20%3D%20f2%3B%20%20%2F%2F%20Error%20with%20--strictFunctionTypes%0D%0Af2%20%3D%20f1%3B%20%20%2F%2F%20Ok%0D%0Af2%20%3D%20f3%3B%20%20%2F%2F%20Error%0D%0A).

**Comment by jcalz** [comment]
[Relevant FAQ entry](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-all-types-assignable-to-empty-interfaces)

(note to @kitsonk, I wouldn't say empty interfaces are equivalent to `any` or even the true top type `unknown`... with `--strictNullChecks` you can't assign `null` or `undefined` to `{}`.  Maybe `{}` is equivalent to `object | number | string | boolean | symbol`?)
