### ISSUE TITLE
Visibility of types in an `export =` namespace varies between `.ts` and `.d.ts` files

### ISSUE THREAD

**Issue by JakeTunaley** [microsoft/TypeScript#31487]
**TypeScript Version:**  3.5.0-dev.20190518

**Search Terms:** declare namespace declaration export equals type member visibility

**Code**

```ts
// module.ts

namespace X {
    interface A {
        kind: 'a';
    }

    interface B {
        kind: 'b';
    }

    export type C = A | B;
}

export = X;
```

```ts
// module.d.ts
// Generated by `tsc --declaration` from `module.ts`

declare namespace X {
    interface A {
        kind: 'a';
    }
    interface B {
        kind: 'b';
    }
    type C = A | B;
}
export = X;
```

```ts
// index.ts

import * as X from './module';

const a: X.A = {
    kind: 'a'
};

const b: X.B = {
    kind: 'b'
};

const c: X.C = {
    kind: 'a'
};
```

**Expected behavior:**

The accessibility of non-exported types should be consistent between `module.ts` and `module.d.ts`.

**Actual behavior:**

If `module.ts` is used, the following accessibility errors occur:

* `Namespace 'X' has no exported member 'A'. ts(2694)`
* `Namespace 'X' has no exported member 'B'. ts(2694)`

If `module.d.ts` is used, no accessibility errors occur.

**Playground Link:**

Requires multiple files, so no playground link.

**Related Issues:**

https://github.com/microsoft/TypeScript/issues/27620

**Comment by fatcerberus** [comment]
The inconsistency has nothing to do with `.ts` vs. `.d.ts`:
https://typescript-play.js.org/#code/CYUwxgNghgTiAEA7KBbEBnADlMCAa8A3gFDxnwCWiALiDAGY4ICCRp5HA1lcAFzwByKAIDc7MgF9xlGnUa54AITYcuPfgIBGo6VI7UAnpgQBheAF54rAD5KxU4sjRYm8AJoryVWg1esSquTciHyCwmIcDhzecq7KAYHwwaFaOpHE0iAAHpgA9jDU8IbG8GaWNnbEDmC5iOiFUPx4AHSslglkyRrCVWI1dYWaTc3K7dJdgtq9xP318GDDZZ6d6mEC0zO1c6FurRbLSatC6xJ9W4Ug-LujBxOp07OF9FfNSx2HId0nIkA

You can put both of those in the same file and see that the only difference is whether you used `declare` or not.  And this is correct, because `declare namespace` implies `export` of all members; it's a pure declaration with no impact on the emitted code describing what *the rest of the program* can do with it, so it wouldn't make sense to have non-exports there--and therefore the export is automatic in that context.

The only difference between `.ts` and `.d.ts` is that *the latter only allows pure declarations*.  `declare` itself acts the same regardless of where it's found.

**Comment by JakeTunaley** [comment]
@fatcerberus The fact that that is the intended behavior of `declare namespace` isn't what this issue is about - what it's about is the fact that the `.d.ts` file exposes different types than the `.ts` file *it was compiled from*, thus meaning that the types a user can consume *will be different* depending on if they have the `.ts` file or the compiled `.d.ts` file.

**Comment by fatcerberus** [comment]
So then the actual problem here is that TS is exposing non-public implementation details in the public `.d.ts`?  That wasn’t clear from the OP.

**Comment by fatcerberus** [comment]
Now that I understand the problem, my first instinct is that this can’t be helped: the definition of `C` depends on the definitions of `A` and `B` , and if all you have to work with is the declaration file then the compiler still has to know what `A | B` means in order to define `C`.

For this to work there would need to be a way to express the idea of a private type in a `declare namespace`, which isn’t currently possible.
