### ISSUE TITLE
New Website Logo: Panascais

### ISSUE THREAD

**Issue by lenovouser** [microsoft/TypeScript#31494]
- Name: Panascais
- Homepage url: [panascais.net](https://panascais.net)
- Brand Guidelines/Licensing: Nothing
- Logo: [images.panascais.net/vector/logo/external-banner.svg](https://images.panascais.net/vector/logo/external-banner.svg)

**Comment by orta** [comment]
Hey folks -we're looking at a new website and it's likely that the friends of TypeScript page isn't going to make it to the new site. This is mainly because close to everyone is a friend of TypeScript now and listing folks kinda feels a bit un-inclusive to everyone else. 

So I'm going to close this issue - thanks for posting to apply
