### ISSUE TITLE
Possible to merge files without transpiling using tsc api?

### ISSUE THREAD

**Issue by jeremy-coleman** [microsoft/TypeScript#31543]
As a user, I want to concat/bundle a folder of ts files (for example a small react app) into a single file , but keep the files as typescript. Essentially like gulp concat with module deduping. I know the ts compiler has the info to do this, i just dont know if it has an api already and if not where to even start.

From a ts perspective, I want to create a ts.program and with an outputFile: name.ts(x) and not transpile

**Comment by kitsonk** [comment]
This isn't the forum for questions. Questions like this should be asked on StackOverflow or on Gitter.im.  Why did you ignore the issue template?

But anyways, TypeScript modules cannot be concatenated together and still be valid.  That is because TypeScript modules follow the ES Module specification, and ES modules cannot be concatenated together and be syntactically valid.

Bundling of TypeScript files would require rewriting each module into its own scope and then deciding how the modules would deal with their exports out of the resulting bundle.  This is a lot more than doing some basic TypeScript AST manipulation.  This is why ES module bundlers are not straight forward.

**Comment by jeremy-coleman** [comment]
Useful

**Comment by arodic** [comment]
I'm very surprised this is not possible. Rollup can compile multiple .ts files into a single .js (es module without declaration files) so I dont see why this would be impossible with typescript.

Is currently impossible to compile Typescript source into a single .js(esnext) + single .d.ts file. Of course ES bundlers are not straight forward, but this is a solvable problem.

**Comment by RyanCavanaugh** [comment]
> I'm very surprised this is not possible. Rollup can compile multiple .ts files into a single .js (es module without declaration files) so I dont see why this would be impossible with typescript.

The fact that other tools can do it is precisely why we haven't bothered to re-implement it?

**Comment by arodic** [comment]
Other tools can't really do this. As I said roll-up can compile to a single esm file but **can't** emit a single declaration file. Tsc can export to a single file but not esm format. The closest that can do both is a combination of tsc and rollup with some plugins like rollup-plugin-dts. It's a two step process and not very easy to do.

**Comment by kitsonk** [comment]
@arodic it sounds like you are looking for a "dts bundler" of which there are several tools out there for that purpose, versus taking TypeScript and flattening it.  The problem is that one form of "dts bundling" works for someone but doesn't work for someone else, and really needs to be to a degree configurable.  Probably the best tool for that is: Rushstack's API Extractor: https://github.com/microsoft/rushstack/tree/master/apps/api-extractor.
