### ISSUE TITLE
'instanceof' type guard breaks with union types

### ISSUE THREAD

**Issue by fs-eire** [microsoft/TypeScript#31576]
**TypeScript Version:**  3.5.0-dev.20190523

**Search Terms:**

**Code**

```ts
function getTypedArray(flag: boolean) {
  return flag ? new Float32Array(10) : new Float64Array(10);
}
function getTypedArrayConstructor(flag: boolean) {
  return flag ? Float32Array : Float64Array;
}
const a = getTypedArray(true);              // Float64Array | Float32Array
const b = getTypedArrayConstructor(false);  // Float64ArrayConstructor | Float32ArrayConstructor
if (!(a instanceof b)) {
  console.log(a.length);  // Property 'length' does not exist on type 'never'.
}

```

**Expected behavior:**

Should have no compiling error.

**Actual behavior:**

Compiling error: Property 'length' does not exist on type 'never'.

If you run the compiled .js file anyway, it will output `10`.

**Related Issues:** 

I reviewed 4 issues related to `instanceof`, but looks like none of those is the same of this one.

**Comment by ahejlsberg** [comment]
Hm, that's not right. The issue is that we take the `instanceof` check as proof `a` is neither a `Float32Array` or `Float64Array` when in reality it could be either. It appears we can only narrow in false branch when `b` is of a non-union type.

**Comment by fatcerberus** [comment]
Kind of interesting - `instanceof` doesn't actually prove anything (at compile time) if the test condition is a union.  It can be either one - the compiler doesn't actually have any way of knowing which one it is.  I don't think it's *ever* okay to narrow in this case, regardless of whether the result is true or false.

**Comment by ahejlsberg** [comment]
> instanceof doesn't actually prove anything (at compile time) if the test condition is a union.

Not quite. Let's say were checking a variable of type `X` against a union of constructors for `A` or `B`. In the true branch we get type `X & (A | B)`, which normalizes to `X & A | X & B`, which is definitely more specific than just `X`. However, if the false branch we get `X & not (A | B)` (using negated types from #29317) which, when `A` and `B` are disjoint, is the same as just `X`. But until we actually have negated types available, the best approximation would be to only narrow `X` when the check type is not a union.

**Comment by orta** [comment]
Looking at this, I think the plan is:

 - Find the part of the flow graph where the boolean node gets assigned 
  ( the graph in [the playground is](https://www.staging-typescript.org/play?install-plugin=playground-code-show-flow#code/GYVwdgxgLglg9mABAcwKZQCoE8AOqAmAggE7ECGWAFMADZnIBciARnHDamWAJSIDeAKESJi6EMSS16iAPyIwqAO6IAYjThkoAZgBMJclQCMABl5MFytRqgA2ACz6KlE9wDcAgL4DQkWAhTo2HhEpBQAwggAzlDEINBwxNR0jCxsHFy8gsKiUOKSybKq6pq6jliITFaa9mXuXhBRUIhkiAC8AZi4BGWUMSCobsJDwyMA9KNF1jWh5QA+kyV6MwINYNEsbR1B3TMRa33xicBkNJEDrsLjC7YOu42xh4jzVdpLBnvRD1AJAjDAiJQAISUFowfZcCCoOD-ZjcTJCRCrSLsVAAOnUyBB6NQYGQUAAFoNEFcAArEOB4YhQcoAcg4uIJNMQ+DgqEi8jgTVQAA8YOt-NS8IgaQoAG6oYg01GeARAA): 
`True (!(a instanceof b)) ─ Assignment (b = getTypedArrayConstructor(false)) ─ Assignment (a = getTypedArray(true)) ─ Start`) 

  ( Likely lives around `function bindCondition` )

I'm still not too sure if the flow nodes actually keep track of the logic, but I expect it's figured out during type checking (because it actually needs to be used then), but from there:

 - Find the check  against the true branch in the flow graph,
- Check to see if its in a `PrefixUnaryExpression` and that the type we're checking is a union and if so, don't narrow the types
