### ISSUE TITLE
Type wrongly assumed to be undefined | number in this case

### ISSUE THREAD

**Issue by bpasero** [microsoft/TypeScript#31603]
**TypeScript Version:**  3.4.0-dev.201xxxxx

```ts
let a: number | undefined;
let b: number | undefined;

if (a || b) {
	const c = a || b;
}
```

🐛 `c` is wrongly assumed to be `number | undefined` when it should be `number`.

**Comment by AnyhowStep** [comment]
Probably a design limitation because it requires multi variable narrowing, but just wanted to point out the obvious; you can restructure your code to work around it.

```ts
let a: number | undefined;
let b: number | undefined;
const tmp = a || b;

if (tmp) {
	const c = tmp;
}
```

**Comment by fatcerberus** [comment]
Yeah, the problem is that `a || b`, from the compiler's point of view, doesn't prove anything individually about `a` or `b`, so it can't actually narrow them.  At the time the assignment to `c` happens the types are still as follows:

```haskell
a :: number | undefined
b :: number | undefined
```

So as far as the compiler is concerned, both could be `undefined` at the time the assignment to `c` happens.  We know that's not the case since `a || b` requires at least *one of them* to be non-falsy, but the type narrowing mechanism isn't quite that nuanced.  It doesn't track dependencies between variables--the same reason this doesn't work:

```ts
let x: number | undefined
let isNumber = typeof x === 'number';
if (isNumber) {
    // x :: number | undefined
    x += 1;  // error
}
```

**Comment by kamranayub** [comment]
I believe we just encountered this limitation and were scratching our heads:

[Playground link](https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgCoQM5gJLmvJZAbwChlkA3OAGwFcIB+ALmSylAHMBuEgXxJIxaIBGGAB7EMhjjxACiKUa9ZLxbosuSLEQQAlMTLIEkrMmAYAajWAATa3RQBeZAEJXVR8gBk35AHoAIzgofwA6SCw5T3o9HnITEDMwAAtOZBcLBzsHFQYlRzCMAAdqYDA5AHIAD0qDFgBtAF0eXiA)

```js
interface TestInterface {
  value?: string;
}

function foo({ value }: TestInterface) {
  const isValidValue = !!value && /bar/.test(value);
  const thing = isValidValue ? value.split('x') : [];
                            // ^ Object is possibly 'undefined'
}
```

This is a simplified example of what we were trying within our code. "Clearly" if `value` is falsy, there's no way it would be `undefined` when checking `isValidValue`.
