### ISSUE TITLE
Contextual typing with optional discriminant

### ISSUE THREAD

**Issue by matt-tingen** [microsoft/TypeScript#31618]
**TypeScript Version:**  3.5.0-dev.20190525

**Search Terms:** discriminated union, optional discriminant, contextual typing, missing vs undefined

Opened from [SO question](https://stackoverflow.com/q/56344704/9715126) since this seems like a possible bug.

TypeScript supports using an explicit `undefined` for the value of an optional discriminant and contextual typing works with that, but contextual typing does not fully work when an optional discriminant is _missing_.

**Code**
```ts
interface NumProps {
  isString?: false
  onChange: (value: number) => void
}

interface StringProps {
  isString: true,
  onChange: (value: string) => void
}

type Props = NumProps | StringProps

const props: Props = {
  // Error: Parameter 'value' implicitly has an 'any' type.
  // Expected: 'value' is contextually typed as 'number'.
  onChange: value => {},
}

const propsUndefined: Props = {
  isString: undefined,
  // OK: 'value' is contextually typed as 'number'. 
  onChange: value => {},
}
```

**Expected behavior:** `value` is contextually typed as `number` for `props`

**Actual behavior:** `value` is `any`

**Playground Link:** [Playground](https://www.typescriptlang.org/play/index.html#src=interface%20NumProps%20%7B%0A%20%20isString%3F%3A%20false%0A%20%20onChange%3A%20(value%3A%20number)%20%3D%3E%20void%0A%7D%0A%0Ainterface%20StringProps%20%7B%0A%20%20isString%3A%20true%2C%0A%20%20onChange%3A%20(value%3A%20string)%20%3D%3E%20void%0A%7D%0A%0Atype%20Props%20%3D%20NumProps%20%7C%20StringProps%0A%0Aconst%20props%3A%20Props%20%3D%20%7B%0A%20%20%2F%2F%20Error%3A%20Parameter%20'value'%20implicitly%20has%20an%20'any'%20type.%0A%20%20%2F%2F%20Expected%3A%20'value'%20is%20inferred%20as%20'number'.%0A%20%20onChange%3A%20value%20%3D%3E%20%7B%7D%2C%0A%7D%0A%0Aconst%20propsUndefined%3A%20Props%20%3D%20%7B%0A%20%20isString%3A%20undefined%2C%0A%20%20%2F%2F%20OK%3A%20'value'%20is%20inferred%20as%20'number'.%20%0A%20%20onChange%3A%20value%20%3D%3E%20%7B%7D%2C%0A%7D) (enable strict options)

As pointed out in the SO comments, annotating `value` with an invalid type _will_ error which suggests that TS is correctly resolving the discriminated union, but possibly not applying contextual typing to `onChange` at the right time.
```ts
const props: Props = {
  // Error: Type 'number' is not assignable to type 'boolean'.
  onChange: (value: boolean) => {}
}
```

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/16817
https://github.com/Microsoft/TypeScript/issues/13195 (Missing vs undefined props)

**Comment by matt-tingen** [comment]
🤦‍♂ Accidentally created the issue early. Will re-open shortly.

**Comment by NiGhTTraX** [comment]
Hitting the same exact problem when trying to improve the types for [react-select](https://react-select.com/): [Playground Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4BYAKCpgE8wk4AFHMAZzgF44BvKuOMDYBZAK4AbGMAD8ALjiYU4tkgqUBEAHYBhABYpNAcyTyAFADclok3E2iQAIyRQAlFwB8ccxGAATNQC+cAA+vPyCIhJS8jBQ1moaOvpGNhZWNnaOzgDaALpunJ7efoFUVL5IaOIoRHBoWmzwAMpI4pUw8sjoMAB0AGLaADwsEOzualT1mo1wAB5ccNnhgy1tGHBaegbGnDyW4tYedQ0QbT3iEIZpB0guQQD07gA0y6vtEWKSwLuKykhBm2SOz26SOUzYpyQ50u12sdzgjxe6jgK1a7yEnykGyS2yQu32h0Kx2mkOhVwJtwezyouVIQA).

It appears that we can work around it with overloads, but then exporting the type for the component is difficult due to https://github.com/microsoft/TypeScript/issues/32164.

```tsx
import React from 'react';

type SingleProps = { isMulti?: false; onChange: (value: number) => void };
type MultiProps = { isMulti: true; onChange: (value: number[]) => void };

function Select(props: SingleProps): JSX.Element;
function Select(props: MultiProps): JSX.Element;
function Select(props: SingleProps | MultiProps): JSX.Element {
  return <span>foo</span>;
};

const x = [
  <Select onChange={value => console.log(value)} />,
  <Select isMulti={false} onChange={value => console.log(value)} />,
  <Select isMulti onChange={value => console.log(value)} />,
];
```

[Playground Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4BYAKCpgE8wk4BlYAOwHMAbJABRzADOcALxwA3nGACAsgFdOMYAH4AXHEwpOApKTgRWAYQAWKDkjUAKAG6bZ5uK1kgARkigBKEQD44ViMAATOABfCko6Bjg5BWA+CEERcUkZeUU1GCg7XX1jU3Z7a1t7Rxc3AG0AXU9hHz9AkLCqTFlWDGB9ZiRuDAswfgE1Fg5uOMF3NQApJgANADoAUW4QJFYYMObWxQ6mLqQevviBqNTY-vG4KbnFpGXV9Za27d39-sG2Ll5+uAAfY5jRgTnS4LJYreBiKhwOBEGCyKCsOAAHgEYFMXkwEAgiIA9Ci0WFQlQqGh9AJ4AAPRJlSFInbdeA5ExmYRiGycOzeOAk1gCCDcWacCDsQrspDuYJwbFeAA0NMRdL28Ck0UULI0WiQEsZeSQLLZHJqXNJfKQAqFIrs4slMrlCowyRVwD0hiZ+T1RU53N5-MFwv1YolUtllAqpCAA)

**Comment by asterikx** [comment]
Still not working in TS 4.2.4 😕

**Comment by david10sing** [comment]
It seems to be working on the TS playground now. The type of value is inferred correctly. However, if you add an optional property on `B`, and you add that property to `props`, there is no error which I think is incorrect.
