### ISSUE TITLE
Destructuring result of generic function where the return value is the generic type always returns any

### ISSUE THREAD

**Issue by LorenzoOpWerk** [microsoft/TypeScript#31692]
**TypeScript Version:**  3.5.1

**Search Terms:** destructuring generics

**Code**

```ts
const A = <T extends object = object>() => {
    const returnValue = {} as T

    return {
        returnValue
    }
}

const { returnValue } = A()

const result = A()
result.returnValue
```

**Expected behavior:**
The destructured `returnValue` and `result.returnValue` should both have type `object`

**Actual behavior:**
Only `result.returnValue` has type `object`, the destructured `returnValue` has type `any`

**Comment by ahejlsberg** [comment]
In the destructuring assignment, the contextual type for `A()` is `{ returnValue: any }`. Since the only inference we make for `T` is through the return type, we end up with an inference of `any` for `T`.

In the regular assignment, there is no contextual type for `A()`. We therefore make no inferences for `T` and end up using the `object` default.

I agree it's somewhat inconsistent, but, on the other hand, in a well defined generic function all type parameters occur at least once somewhere in a parameter type such that inferences can be made from actual arguments. Otherwise, generic functions are just disguised type assertions--as is the case here.
