### ISSUE TITLE
Checked type of conditional type isn't matched for constraint in true clause unless the type parameter is constrained

### ISSUE THREAD

**Issue by sirian** [microsoft/TypeScript#31700]
**TypeScript Version:**  3.5.1

**Code**

```ts
type Ctor = new () => Date;

 // ERROR, WTF?
type Z1<T> = T extends () => Ctor ? InstanceType<ReturnType<T>> : never; 

// But here NO ERROR
type Z2<T extends any> = T extends () => Ctor ? InstanceType<ReturnType<T>> : never;


 // ERROR
type Z3<T> = T extends () => any ? InstanceType<ReturnType<T>> : never;

// NO ERROR again
type Z4<T extends () => any> = InstanceType<ReturnType<T>>;

```

**Actual behaviour**
`type Z1<T> = T extends () => Ctor ? InstanceType<ReturnType<T>> : never; ` errors

**Expected behaviour**
`type Z1<T> = T extends () => Ctor ? InstanceType<ReturnType<T>> : never;` should be valid

More examples. 
![image](https://user-images.githubusercontent.com/897643/58711000-3f48a700-83c6-11e9-8cf2-ba1620538d18.png)

[**Playground Link:** ](https://www.typescriptlang.org/play/index.html#src=type%20Ctor%20%3D%20new%20()%20%3D%3E%20Date%3B%0D%0A%0D%0A%20%2F%2F%20ERROR%2C%20WTF%3F%0D%0Atype%20Z1%3CT%3E%20%3D%20T%20extends%20()%20%3D%3E%20Ctor%20%3F%20InstanceType%3CReturnType%3CT%3E%3E%20%3A%20never%3B%20%0D%0A%0D%0A%2F%2F%20NO%20ERROR%0D%0Atype%20Z2%3CT%20extends%20any%3E%20%3D%20T%20extends%20()%20%3D%3E%20Ctor%20%3F%20InstanceType%3CReturnType%3CT%3E%3E%20%3A%20never%3B%0D%0A%0D%0A%0D%0A%20%2F%2F%20ERROR%0D%0Atype%20Z4%3CT%3E%20%3D%20T%20extends%20()%20%3D%3E%20any%20%3F%20InstanceType%3CReturnType%3CT%3E%3E%20%3A%20never%3B%0D%0A%0D%0A%2F%2F%20NO%20ERROR%0D%0Atype%20Z3%3CT%20extends%20()%20%3D%3E%20any%3E%20%3D%20InstanceType%3CReturnType%3CT%3E%3E%3B%0D%0A%0D%0A)

**Comment by RyanCavanaugh** [comment]
Regressed between 3.3 and 3.4

**Comment by weswigham** [comment]
Technically this is because we erase `any` in a substitution (or rather, we interpret it as `unknown` so as to not delete information). So a `T extends any ? InstanceType<ReturnType<T>> : never` is essentially `InstanceType<ReturnType<T & unknown>>` which is just `InstanceType<ReturnType<T>>` which is ofc an error. The others all formulate in the same way. Essentially, `any` as a conditional check does _not_ disable type checking, like `any` as a constraint (accidentally!) does. https://github.com/microsoft/TypeScript/pull/29571 would go a lot of the way to making the constraint cases behave like the conditionals (though it's still admittedly incomplete! it only replaces `any` at the top level of a constraint and not throughout the constraint type!)

So this is technically a regression, but it's an intended consequence of an intentional change, and what we have been looking at is making the constraint case behave in the same way, too (as why would a `T extends any` be any different than a `T extends unknown`???)

**Comment by weswigham** [comment]
@RyanCavanaugh if you want, we can discuss this, but after actually looking at it, everything seems in order except for our constraint behavior which we already acknowledge as wrong.
