### ISSUE TITLE
#31711 breaks assignability

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#31762]
```ts
// @strict: true
function g(headerNames: any) {
    let t = [{ hasLineBreak: false, cells: [] }];
    const table = [{cells: headerNames }].concat(t);
}
```

**Expected behavior:**
No error.

**Actual behavior:**
Error on `concat(t)`: `{ hasLineBreak: boolean, cells: never[] }` is not assignable to `{ cells: any }`. `hasLineBreak` is missing.

**Playground Link:** 

**Related Issues:**

**Comment by sandersn** [comment]
Found in the user tests, in prettier.

**Comment by fatcerberus** [comment]
Looks like it got the assignability check backwards, that’s odd.

**Comment by sandersn** [comment]
From in-person discussion, I think we are going to take this as a breaking change for 3.6.

**Comment by fatcerberus** [comment]
Wait, what's the accepted breaking change?  The error mentioned in the OP?  Because if so the error message is nonsensical:

> `{ hasLineBreak: boolean, cells: never[] }` is not assignable to `{ cells: any }`. `hasLineBreak` is missing.

With that wording, it looks like a bug--the apparent bug being that a structural assignability check was done with the source and target reversed.  Even if the breakage is acceptable, the error message IMO isn't as it's exactly backwards a.c.t. typical structural typing semantics.

**Comment by ahejlsberg** [comment]
The issue here is when to widen the object expression in property access (`obj.x`) and element access (`obj["x"]`) expressions. We have been quite inconsistent here. It used to the that we'd always widen `obj` in a property access and never widen `obj` in an element access. That's obviously not right as the two are supposed to be synonymous. In #31711 we switched to widening `obj` only when it is an empty array literal in a property access expression (e.g. `[].concat(...)`), but that isn't right either.

I've given it some thought, and I think the real solution is to widen `obj` when the property or element access is (a) the target of an assignment, or (b) a method access in a call expression (i.e. the `this` of the call). These are the situations in which we are mutating (or possibly mutating) the object and therefore should widen its type.

**Comment by ahejlsberg** [comment]
To demonstrate the inconsistency, this is our behavior in 3.5.1 and earlier:

```ts
// @strict: true
function g1(headerNames: any) {
    let t = [{ hasLineBreak: false, cells: [] }];
    const table = [{cells: headerNames }].concat(t);  // No error
}

function g2(headerNames: any) {
    let t = [{ hasLineBreak: false, cells: [] }];
    const table = [{cells: headerNames }]["concat"](t);  // Error
}
```

**Comment by fatcerberus** [comment]
@ahejlsberg I’m not actually doubting the type error itself - I’m just confused as to how TypeScript arrives at the conclusion that “`(derived)` is not assignable to `(base)`” (per usual structural rules) - even in cases of contravariance it normally gets this right:

```ts
// @strictFunctionTypes: true
let f: (x: Derived) => void;
let g: (x: Base) => void;
g = f;
// error because (ultimately) Base is not assignable to Derived
```
