### ISSUE TITLE
Warning on implicit typing / inference

### ISSUE THREAD

**Issue by JirkaDellOro** [Microsoft/TypeScript#3177]
I started using TypeScript as the first language for teaching programming at our university. Though it's sometimes recommended to leave typing to TypeScript, I force my students to explicitly type in order to create the proper mental modell and simply for the purpose of practice.

It would be very helpful to have an option to display warnings at declarations with implicit types. So far, Eclipse only warns on implicit any-types and the people at Palantir state that this feature needs to exist in the language service first in order for them to implement the visualization.

Hard to implement?

**Comment by DanielRosenwasser** [comment]
Hi @JirkaDellOro, glad to hear you've chosen to use TypeScript!

However, with what you're requesting, I think this is better left to a linter. I don't think we could accomplish this while satisfying everyone. For instance, in your mind, would this proposed feature error in the following two cases?

```TypeScript
var x = (v: number) => v;

var y: (v: number) => number = (v => v);
```

Some might say *"but I already typed `x`!"*, or *"but `y` already contextually typed the arrow function!"*.

Otherwise, while I understand you're trying to get your students to keep types in mind, I don't know such a feature would have many use outside of this - this can be viewed more as a stylistic preference, and in the TypeScript community, letting inference do the work is generally encouraged.

We're more than open to helping you use the API to get this done. We have a [sample linter](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#traversing-the-ast-with-a-little-linter) as a starting out point. You may be interested in the [https://github.com/Microsoft/TypeScript/blob/master/bin/typescript.d.ts#L851](`getContextualType`) function depending on what you want to do in the above examples.

**Comment by JirkaDellOro** [comment]
Thanks for the quick reply and some brainfood.

Your second example already raises an error due to an implicit declaration of v as any. While this was probably just a typo [ should probably be (v) => v ], it shows right there, that the feature is basically already implemented. It would be great to have the warning simply an all implicit inferences.

The proper way, in the context of this particular request, to code your example would indeed look like this:

var x: (v: number) => number;
x = (v: number) => v;

I split it in two lines for readability, what I would also recommend to my students. Using the type-keyword and in case I have several functions with that same signature, I'd even go this way:

type F = (v: number) => number;
var x: F = (v:number) => v;

Looks like readable and nicely explicitly typed code to me.


Getting back to the request, doing it myself would also mean I'd have to also modify the palantir-plugin for eclipse, maybe cutting us off from upcoming versions. I'd appreciate it very much, if one could check if it's possible to simply extend the any-warning, to raise a warning an all types. And I agree that this should be a feature that's turned off in the standard installation, but can be activated, just like the any-warning.

**Comment by RyanCavanaugh** [comment]
I don't think adding this to the compiler is appropriate. Inference is a major selling point of TypeScript, and warning on "harmless" inference is not something an appreciable number of people want to do.

The linter example is already 85% of the way to implementing this. For each of the kinds of nodes that you think need type annotations, add a check for the `type` node and issue an error when appropriate. Feel free to post back here if you have any questions on this; we'd be happy to help.

**Comment by DanielRosenwasser** [comment]
> Your second example already raises an error due to an implicit declaration of v as any. While this was probably just a typo [ should probably be (v) => v ], it shows right there, that the feature is basically already implemented.

Actually this isn't the case; `v`'s gets contextually typed to `number` in my latter example. See [the types on our playground](http://www.typescriptlang.org/Playground#src=var%20x%20%3D%20(v%3A%20number)%20%3D%3E%20v%3B%0A%0Avar%20y%3A%20(v%3A%20number)%20%3D%3E%20number%20%3D%20(v%20%3D%3E%20v)%3B) by hovering over the variables with your mouse. If you're referring to the fact that parentheses used to disable the contextual typing of an expression, [this is no longer the case for TypeScript 1.5](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#contextual-type-flows-through-super-and-parenthesized-expressions).

**Comment by JirkaDellOro** [comment]
@Daniel: I just reported, what Eclipse and the Palantir-Plugin showed. I'm at 1.4

@Ryan: unfortunately, I don't think I wil have the time and resources to get into this. Trying to do the last 15% would probably cost ten times the effort to start on it in the first place. And even if I finished that linter, how do I get these warnings to appear in Eclipse?

**Comment by mhegazy** [comment]
It should be much simpler to add a new rule to tslint. It Should also work withe eclipse plugin, they are both developed by @Palantir :)
