### ISSUE TITLE
esnext conflicts with other versions specified with lib field

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#31794]
This error doesn't appear other targets such as es2018, es2015.

**TypeScript Version:**  3.6.0-dev.20190606

**Search Terms:**

**Code**

1. clone https://github.com/falsandtru/spica
1. change compile target to `esnext` in tsconfig
1. open ./src/type.test.ts via vscode

**Expected behavior:**

pass

**Actual behavior:**

```
{
	"resource": "./src/type.test.ts",
	"owner": "typescript",
	"code": "2318",
	"severity": 8,
	"message": "Cannot find global type 'BigInt'.",
	"source": "ts",
	"startLineNumber": 423,
	"startColumn": 6,
	"endLineNumber": 423,
	"endColumn": 6
}
```

**Playground Link:** 

**Related Issues:**

**Comment by fatcerberus** [comment]
> 1. clone https://github.com/falsandtru/spica

@RyanCavanaugh won’t like that very much. :wink:

**Comment by calebsander** [comment]
The error is caused by the following line:
```ts
assert((): true => true as TEq<Type<bigint>, 'bigint'>);
```
Since the definition of `Type<T>` includes the conditional `T extends bigint`, the compiler has to figure out whether `T == bigint` conforms to `bigint`'s interface. `bigint` inherits methods like `toString()` from the global `BigInt` interface, so the compiler expects a definition of `BigInt`.

It is defined in the library `esnext.bigint`, which you aren't including in the compilation. You can either add it to your `lib` list in `tsconfig.json`, or just remove the `lib` list entirely and it will include `esnext` by default.

**Comment by falsandtru** [comment]
esnext includes bigint: https://github.com/microsoft/TypeScript/blob/master/lib/lib.esnext.d.ts

I found esnext conflicts with other versions specified with lib field. `"target": "esnext", "lib": ["esnext"],` makes not error but `"target": "esnext", "lib": ["es2018"],` makes errors.

**Comment by falsandtru** [comment]
ping @RyanCavanaugh @DanielRosenwasser
