### ISSUE TITLE
[Regression] ReturnType<> Inference works on 3.3.3, breaks on 3.4.1, 3.5.1

### ISSUE THREAD

**Issue by AnyhowStep** [microsoft/TypeScript#31814]
**TypeScript Version:**  3.4.1, 3.5.1

**Search Terms:** regression, ReturnType, parameter, inference

**Code**

```ts
interface Mapper<HandledInputT, OutputT> {
    (name : string, mixed : HandledInputT) : OutputT,
}


export type IsPipeable<
    FromF extends Mapper<any, any>,
    ToF extends Mapper<any, any>
> = (
    ToF extends Mapper<infer HandledInputT, any> ?
    (
        ReturnType<FromF> extends HandledInputT ?
        true :
        false
    ) :
    false
);

export type AssertPipeable<
    FromF extends Mapper<any, any>,
    ToF extends Mapper<any, any>
> = (
    IsPipeable<FromF, ToF> extends true ?
    ToF :
    [ReturnType<FromF>, "is not pipeable"]
);

declare function pipe<
    F0 extends Mapper<unknown, any>,
    F1 extends Mapper<any, any>
> (
    f0 : F0,
    f1 : AssertPipeable<F0, F1>
): void;

declare function literal<ArrT extends (string | number | boolean | bigint | null | undefined)[]>(
    ...arr: ArrT
): (
    Mapper<unknown, ArrT[Extract<keyof ArrT, number>]>
);
declare const b: Mapper<"0" | "1" | 0 | 1 | "false" | "true", boolean>

//TS suddenly thinks the first arg is Mapper<unknown, any>.
//It is actually Mapper<unknown, "0" | "1" | 0 | 1 | "false" | "true">.
pipe(
    //TS knows this is Mapper<unknown, "0" | "1" | 0 | 1 | "false" | "true">
    literal("0", "1", 0, 1, "false", "true"),
    /*
        Expected: works.
        Actual:
        Argument of type 'Mapper<0 | "0" | "1" | 1 | "false" | "true", boolean>'
        is not assignable to parameter of type '[any, "is not pipeable"]'.

        Succeeds with 3.3.3,
        Fails with 3.4.1,
        Fails with 3.5.1
    */
    b
);

const a = literal("0", "1", 0, 1, "false", "true");
//TS now knows the first arg is Mapper<unknown, "0" | "1" | 0 | 1 | "false" | "true">
pipe(
    a,
    /*
        This works.
        `a` is literally the same type as
        `literal("0", "1", 0, 1, "false", "true")`.

        Why would the first pipe() call fail,
        but the second one succeed?

        Succeeds with 3.3.3,
        Succeeds with 3.4.1,
        Succeeds with 3.5.1
    */
    b
);
```

**Expected behavior:**

The below should work,

```ts
pipe(
    literal("0", "1", 0, 1, "false", "true"),
    b
);
```

**Actual behavior:**

It used to work but does not work now.

**Playground Link:** [Playground](http://www.typescriptlang.org/play/#src=interface%20Mapper%3CHandledInputT%2C%20OutputT%3E%20%7B%0D%0A%20%20%20%20(name%20%3A%20string%2C%20mixed%20%3A%20HandledInputT)%20%3A%20OutputT%2C%0D%0A%7D%0D%0A%0D%0A%0D%0Aexport%20type%20IsPipeable%3C%0D%0A%20%20%20%20FromF%20extends%20Mapper%3Cany%2C%20any%3E%2C%0D%0A%20%20%20%20ToF%20extends%20Mapper%3Cany%2C%20any%3E%0D%0A%3E%20%3D%20(%0D%0A%20%20%20%20ToF%20extends%20Mapper%3Cinfer%20HandledInputT%2C%20any%3E%20%3F%0D%0A%20%20%20%20(%0D%0A%20%20%20%20%20%20%20%20ReturnType%3CFromF%3E%20extends%20HandledInputT%20%3F%0D%0A%20%20%20%20%20%20%20%20true%20%3A%0D%0A%20%20%20%20%20%20%20%20false%0D%0A%20%20%20%20)%20%3A%0D%0A%20%20%20%20false%0D%0A)%3B%0D%0A%0D%0Aexport%20type%20AssertPipeable%3C%0D%0A%20%20%20%20FromF%20extends%20Mapper%3Cany%2C%20any%3E%2C%0D%0A%20%20%20%20ToF%20extends%20Mapper%3Cany%2C%20any%3E%0D%0A%3E%20%3D%20(%0D%0A%20%20%20%20IsPipeable%3CFromF%2C%20ToF%3E%20extends%20true%20%3F%0D%0A%20%20%20%20ToF%20%3A%0D%0A%20%20%20%20%5BReturnType%3CFromF%3E%2C%20%22is%20not%20pipeable%22%5D%0D%0A)%3B%0D%0A%0D%0Adeclare%20function%20pipe%3C%0D%0A%20%20%20%20F0%20extends%20Mapper%3Cunknown%2C%20any%3E%2C%0D%0A%20%20%20%20F1%20extends%20Mapper%3Cany%2C%20any%3E%0D%0A%3E%20(%0D%0A%20%20%20%20f0%20%3A%20F0%2C%0D%0A%20%20%20%20f1%20%3A%20AssertPipeable%3CF0%2C%20F1%3E%0D%0A)%3A%20void%3B%0D%0A%0D%0Adeclare%20function%20literal%3CArrT%20extends%20(string%20%7C%20number%20%7C%20boolean%20%7C%20bigint%20%7C%20null%20%7C%20undefined)%5B%5D%3E(%0D%0A%20%20%20%20...arr%3A%20ArrT%0D%0A)%3A%20(%0D%0A%20%20%20%20Mapper%3Cunknown%2C%20ArrT%5BExtract%3Ckeyof%20ArrT%2C%20number%3E%5D%3E%0D%0A)%3B%0D%0Adeclare%20const%20b%3A%20Mapper%3C%220%22%20%7C%20%221%22%20%7C%200%20%7C%201%20%7C%20%22false%22%20%7C%20%22true%22%2C%20boolean%3E%0D%0A%0D%0A%2F%2FTS%20suddenly%20thinks%20the%20first%20arg%20is%20Mapper%3Cunknown%2C%20any%3E.%0D%0A%2F%2FIt%20is%20actually%20Mapper%3Cunknown%2C%20%220%22%20%7C%20%221%22%20%7C%200%20%7C%201%20%7C%20%22false%22%20%7C%20%22true%22%3E.%0D%0Apipe(%0D%0A%20%20%20%20%2F%2FTS%20knows%20this%20is%20Mapper%3Cunknown%2C%20%220%22%20%7C%20%221%22%20%7C%200%20%7C%201%20%7C%20%22false%22%20%7C%20%22true%22%3E%0D%0A%20%20%20%20literal(%220%22%2C%20%221%22%2C%200%2C%201%2C%20%22false%22%2C%20%22true%22)%2C%0D%0A%20%20%20%20%2F*%0D%0A%20%20%20%20%20%20%20%20Expected%3A%20works.%0D%0A%20%20%20%20%20%20%20%20Actual%3A%0D%0A%20%20%20%20%20%20%20%20Argument%20of%20type%20'Mapper%3C0%20%7C%20%220%22%20%7C%20%221%22%20%7C%201%20%7C%20%22false%22%20%7C%20%22true%22%2C%20boolean%3E'%0D%0A%20%20%20%20%20%20%20%20is%20not%20assignable%20to%20parameter%20of%20type%20'%5Bany%2C%20%22is%20not%20pipeable%22%5D'.%0D%0A%0D%0A%20%20%20%20%20%20%20%20Succeeds%20with%203.3.3%2C%0D%0A%20%20%20%20%20%20%20%20Fails%20with%203.4.1%2C%0D%0A%20%20%20%20%20%20%20%20Fails%20with%203.5.1%0D%0A%20%20%20%20*%2F%0D%0A%20%20%20%20b%0D%0A)%3B%0D%0A%0D%0Aconst%20a%20%3D%20literal(%220%22%2C%20%221%22%2C%200%2C%201%2C%20%22false%22%2C%20%22true%22)%3B%0D%0A%2F%2FTS%20now%20knows%20the%20first%20arg%20is%20Mapper%3Cunknown%2C%20%220%22%20%7C%20%221%22%20%7C%200%20%7C%201%20%7C%20%22false%22%20%7C%20%22true%22%3E%0D%0Apipe(%0D%0A%20%20%20%20a%2C%0D%0A%20%20%20%20%2F*%0D%0A%20%20%20%20%20%20%20%20This%20works.%0D%0A%20%20%20%20%20%20%20%20%60a%60%20is%20literally%20the%20same%20type%20as%0D%0A%20%20%20%20%20%20%20%20%60literal(%220%22%2C%20%221%22%2C%200%2C%201%2C%20%22false%22%2C%20%22true%22)%60.%0D%0A%0D%0A%20%20%20%20%20%20%20%20Why%20would%20the%20first%20pipe()%20call%20fail%2C%0D%0A%20%20%20%20%20%20%20%20but%20the%20second%20one%20succeed%3F%0D%0A%0D%0A%20%20%20%20%20%20%20%20Succeeds%20with%203.3.3%2C%0D%0A%20%20%20%20%20%20%20%20Succeeds%20with%203.4.1%2C%0D%0A%20%20%20%20%20%20%20%20Succeeds%20with%203.5.1%0D%0A%20%20%20%20*%2F%0D%0A%20%20%20%20b%0D%0A)%3B)

**Related Issues:**

I feel like it is related to #29133 somehow. Because I have `ReturnType<>` being used in a parameter again. But it's somewhat different this time in that the first argument is not an anonymous function "literal" I created. It's a function given by another function.

**Comment by AnyhowStep** [comment]
This is a simplified repro. My actual use case is more complicated in that `IsPipeable<>` has way more rules. It's not as simple as "Output of `A` must match input of `B`" because `pipe()` may do other things behind the scenes to make the data acceptable to `B`.

**Comment by RyanCavanaugh** [comment]
@ahejlsberg looks like another instance of contextual return type inference messing things up, though it's not completely obvious how in this example

**Comment by ahejlsberg** [comment]
This is an effect of #30215 and I'm not sure there's much we can do to change it. With #30215 we sometimes defer processing of arguments in order to make better inferences (but we didn't before 3.4.1). This is captured here in my comment in `resolveCallExpression`:

> When a call to a generic function is an argument to an outer call to a generic function for which
inference is in process, we have a choice to make. If the inner call relies on inferences made from
its contextual type to its return type, deferring the inner call processing allows the best possible
contextual type to accumulate. But if the outer call relies on inferences made from the return type of
the inner call, the inner call should be processed early. There's no sure way to know which choice is
right (only a full unification algorithm can determine that), so we resort to the following heuristic:
If no type arguments are specified in the inner call and at least one call signature is generic and
returns a function type, we choose to defer processing. This narrowly permits function composition
operators to flow inferences through return types, but otherwise processes calls right away. We
use the resolvingSignature singleton to indicate that we deferred processing. This result will be
propagated out and eventually turned into nonInferrableType (a type that is assignable to anything and
from which we never make inferences).

In the `pipe(literal(...), b)` example, we defer processing of the `literal(...)` call for the reasons explained above. This means we initially make no inferences for `F0`, which in turn means the `AssertPipeable` conditional type isn't happy. Basically, the way the `pipe` function is declared, type inference only succeeds when inferences are made for `F0` and `F1` in the same phase. Things work fine when `AssertPipeable<F0, F1>` is replaced with just `F1` because we can then make independent inferences for `F0` and `F1` in different phases of the type inference process.
