### ISSUE TITLE
Compiler hangs

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#31823]
But looks like CPU and Memory usage is not increasing.

**TypeScript Version:**  master

**Search Terms:**

**Code**

```ts
export type Prepend<Elm, T extends unknown[]> =
  T extends unknown ?
  ((arg: Elm, ...rest: T) => void) extends ((...args: infer T2) => void) ? T2 :
  never :
  never;
export type ExactExtract<T, U> = T extends U ? U extends T ? T : never : never;

type Conv<T, U = T> =
  { 0: [T]; 1: Prepend<T, Conv<ExactExtract<U, T>>>;}[U extends T ? 0 : 1];
```

**Expected behavior:**

pass

**Actual behavior:**

hang

**Playground Link:** 

**Related Issues:**

**Comment by sandersn** [comment]
Also fails on 3.5.1

**Comment by weswigham** [comment]
The type expands so well:

![image](https://user-images.githubusercontent.com/2932786/59374784-79d50c80-8d01-11e9-8285-0b744d2c7835.png)

I'm actually surprised we just hang rather than quickly OOM. _Apparently_ a `Conv<ExactExtract<U, T>>` is not a simple type, and determining if it's assignable to an `unknown[]` is not so easy. :P

**Comment by fatcerberus** [comment]
@weswigham Wait, why does that type expand recursively like that?  Shouldn't that have been caught by the instantiation depth limiter?

**Comment by weswigham** [comment]
Oh, it is. The depth limit is 50 instances of the same type and there's like 10 different types, so that's like 500 types deep that it can easily go.
