### ISSUE TITLE
IntelliSense shows incorrect parameter names (TypeScript)

### ISSUE THREAD

**Issue by korkje** [microsoft/TypeScript#31845]
I am writing a helper function that provides functionality often associated with the traditional switch statement, but in a more functional style. In doing so, I have come across a bug.

Consider the following code, which is a simplification of the helper I'm writing:

```TypeScript
const match = <T>(value: T) => ({
    on: <U>(prediction: T, outcome: U) => prediction === value
        ? matched(outcome)
        : match(value),
    result: () => undefined
});

const matched = <T>(outcome: T) => ({
    on: () => matched(outcome),
    result: () => outcome
});

const num = Math.random() > 0.5 ? 1 : 2;

const numString = match(num)
    .on(1, 'one')
    .on(2, 'two')
    .result();
```

When hovering the first `on` call, we see the expected information:

<img width="483" alt="Screenshot 2019-06-09 at 20 06 00" src="https://user-images.githubusercontent.com/13970894/59162488-2b9dee80-8af2-11e9-853f-ea045d92f4fb.png">

However, when hovering the second `on` call, which is a call to the `on` property of the result of either `match` or `matched`, we get:

<img width="433" alt="Screenshot 2019-06-09 at 20 06 12" src="https://user-images.githubusercontent.com/13970894/59162487-2b9dee80-8af2-11e9-89d4-0024ce40d37e.png">

As we can see, the types are just fine, but the argument names are replaced with 'arg0' and 'arg1'. This in itself could be intentional for some reason, and hence not a bug, but here's what leads me to consider this a bug:

When removing the last argument to the second `on` call, IntelliSense gives us an error as expected, but with an error text containing one of the previously replaced argument names, 'outcome':

<img width="433" alt="Screenshot 2019-06-09 at 20 06 38" src="https://user-images.githubusercontent.com/13970894/59162486-2b9dee80-8af2-11e9-835e-5abce0ba5a90.png">

The same goes for 'prediction' if both arguments are removed.

I suspect this might be a result of trying to derive the parameter names from the second definition of `on` (as a result of the `matched` function), which would be inconsistent as the rest of the call signature is clearly derived from the first definition (as a result of the `match` function). Or I am completely wrong, which is also very much possible.

Anyway, this is misleading. What I expect is for both the call signature and error text to contain 'prediction' and 'outcome' as the parameter names, or at the very least for these to be consistent.

PS: The full thing is at https://github.com/korkje/match/blob/master/src/index.ts, and exhibits the same weirdness.

**Comment by mjbvz** [comment]
Confirmed with TS 3.6.0-dev.20190608

**Comment by fatcerberus** [comment]
Possibly related: [Playground link](https://typescript-play.js.org/#code/GYVwdgxgLglg9mABMATnARgHgCoBpECCiApgB5TFgAmAzogIZgCeA2gLoB8AFMAFyJcAdMPooA5jX4EAlIgC8HRHkTDBoiVOkAoAN5bEBxCmJQQKJMCEjxNaQG4tAXy1bQkWAkToANiHQ84OH4aKBQYMDF8dFF+MBAAW3RiFFkdZ1c0fx8-fAAiaLBGekQab3p4+Ppc-AAOAEYAJnstIA)

```ts
function frob<T, A extends any[]>(f: (...args: A) => T, ...args: A)
{
    return f(...args);
}

function blub(foo: string, bar: number) {}

frob(blub, "banana slamma", 812);
```


![image](https://user-images.githubusercontent.com/4097841/59400643-2517ad00-8d66-11e9-8c37-d613b4f867b9.png)

Parameter names are correct while typing out the call, but...

![image](https://user-images.githubusercontent.com/4097841/59400700-58f2d280-8d66-11e9-9aa6-08aa204ab46f.png)

once everything is totally filled out it reverts to generic `arg_0` etc.

**Comment by dragomirtitian** [comment]
@RyanCavanaugh can I have a look at this ? I dug around preciously in the area (https://github.com/microsoft/TypeScript/pull/30084)

**Comment by RyanCavanaugh** [comment]
Sure!

**Comment by dragomirtitian** [comment]
@RyanCavanaugh A smaller repro of this would be: 

```ts
let fn: (<U>(a1: U) => void) | (() => void) 
fn(1) //  quick info: let fn: <number>(arg0: number) => void
```

The issue is that when the signatures in the union are combined, instead of using the only available name (ex: `a1`) the fallback for when parameter names don't match is used (`arg${i}`). This does not manifest for non-generic  functions as there the signature is just cloned.

Possible Solutions:

1. **Target fix for just this case**: Fix the combination algorithm to use the available name when one of the combined signatures has fewer parameters. This should be a quick easy fix.
2. **Improve on `arg${i}`**: `arg${i}` is not particularly useful or friendly, and this is what is used when signatures have conflicting parameter names. Perhaps we could concatenate parameter names, ideally to something meaningful like `p1 & p2` (where `p1` and `p2` come from the original signatures). While this is not normally a valid name for a parameter, it would make clear to the user that this is an amalgamation of the two original parameter and will probably not have any negative impact in other places since this is just a signature used for type checking (but I have not investigated  this).

Ex:
```ts
let fn2: ((p1:  { b: string }) => void) | ((p2:  { a: number }) => void) 
fn2({}) // quick info: let fn2(p1 & p2: { b: string; } & { a: number; }): void
```
This is a bit of a whack idea but it might be useful 🤷‍♀️

Should I just proceed with 1 ? Or experiment with 2 ?

@fatcerberus  The issue you found has a different root cause to the one in  the original post, it might merit a ticket of its own.

**Comment by fatcerberus** [comment]
For my part I kind of like the second idea, when you have a union of functions it ends up requiring an intersection of arguments which tends to throw people off (especially if they're not used to seeing intersections in everyday code) so it might be good to provide a hint that the signature was in fact synthesized from two (or more) different functions.
