### ISSUE TITLE
Partial accepts extra properties from another type?

### ISSUE THREAD

**Issue by douglascvas** [microsoft/TypeScript#31872]
**TypeScript Version:**  3.4.5

**Search Terms:**
`Partial`

Given interfaces A and B, which contain a `x1` property in common
```typescript
interface A {
  a1: number;
  a2: number;
  x1: number;  // <<<<
}

interface B{
  b1: number;
  x1: number;  // <<<<
}
```

And given the implementations `a` and `b`

```typescript
let a: A = {a1: 1, x1: 1};
let b: B = {b1: 1, x1: 1};
```

**Actual behavior:**

This simply passes, even though `b1` does not belong to `Partial<A>`:
```typescript
let partialA: Partial<A> = b;
```

but this fails pointing out that `b1` does not belong to `Partial<A>`:
```typescript
let partialA: Partial<A> = {b1: 1, x1: 1};
```

**Expected behavior:**
Both cases should fail.

**Playground Link:**  [here](https://www.typescriptlang.org/play/#src=interface%20A%20%7B%0D%0A%20%20a1%3A%20number%3B%0D%0A%20%20x1%3A%20number%3B%20%20%2F%2F%20%3C%3C%3C%3C%0D%0A%7D%0D%0A%0D%0Ainterface%20B%7B%0D%0A%20%20b1%3A%20number%3B%0D%0A%20%20x1%3A%20number%3B%20%20%2F%2F%20%3C%3C%3C%3C%0D%0A%7D%0D%0A%0D%0Alet%20a%3A%20A%20%3D%20%7Ba1%3A%201%2C%20x1%3A%201%7D%3B%0D%0Alet%20b%3A%20B%20%3D%20%7Bb1%3A%201%2C%20x1%3A%201%7D%3B%0D%0A%0D%0Alet%20p1%3A%20Partial%3CA%3E%20%3D%20b%3B%0D%0Alet%20p2%3A%20Partial%3CA%3E%20%3D%20%7Bb1%3A%201%2C%20x1%3A%201%7D%3B%0D%0A%0D%0A%2F%2F%20---------------------%0D%0A%2F%2F%20another%20example%3A%0D%0A%2F%2F%20---------------------%0D%0Aclass%20C%20%7B%0D%0A%20%20constructor(p%3A%20Partial%3CA%3E)%7B%7D%0D%0A%7D%0D%0A%0D%0Alet%20c1%3A%20C%20%3D%20new%20C(%7Bb1%3A%201%2C%20x1%3A%201%7D)%3B%0D%0Alet%20c2%3A%20C%20%3D%20new%20C(b)%3B%0D%0A)

**Comment by dragomirtitian** [comment]
You posted this question on [SO](https://stackoverflow.com/questions/56559542/why-partial-accepts-extra-properties-from-another-type) as well.. maybe wait more than 30 minutes before posting the same question on GitHub.

At least under current rules this is the expected behavior. Generally a sub-type should be assignable to a super-type. Because both types have no required properties either one can be a subtype of the other. Conditional types show this :

```ts
type q1 = Partial<A> extends Partial<B> ? "Y" : "N" // Y
type q2  = Partial<B> extends Partial<A> ? "Y" : "N" // Y

```
The are rules to catch common errors that deviate from the above rule:

1. The direct assignment fails under excess property checks .
2. The indirect assignment would not be allowed under [weak type detection](https://github.com/microsoft/TypeScript/pull/3842) if the types have nothing in common. But since they have `x1` in common the assignment is valid.
