### ISSUE TITLE
When to use which package?

### ISSUE THREAD

**Issue by Bartolomeus-649** [microsoft/TypeScript#31906]
How does the different distribution packages of TypeScript relate to each other, and when should one be used over another?

In Visual Studio Installer there's an option to install the TypeScript SDK, then we have the TypeScript NuGet package, and the Visual Studio TypeScript Extension. Perhaps there's even more TypeScript packages available.

* How do you know which ones to use?
* How do you manage TypeScript version updates when using the Visual Studio TypeScript Extension, when each new TypeScript version is a completely new Extension?
* Do all packages provide the same and equal features and functionality?
* Are there any recommendations or best practices for using TypeScript in Visual Studio when it comes to which distribution of TypeScript to use?
* Any risk of conflicts if you, for example, use the Type Script SDK installed via the VS Installer, and then reference a NuGet package that have a dependency on the TypeScript NuGet package?
* What are the different ways of configure TypeScript and how do they relate to each other? For example, the GUI settings for TypeScript in Visual Studio Options (Menu: Tools -> Options), how do they relate to the various file-based settings?

**Comment by RyanCavanaugh** [comment]
@amcasey can you elucidate?

**Comment by amcasey** [comment]
@PranavSenthilnathan would be the best person to address these questions.

**Comment by Bartolomeus-649** [comment]
???

**Comment by RyanCavanaugh** [comment]
I've pinged Pranav offline

**Comment by PranavSenthilnathan** [comment]
Hey @Bartolomeus-649, sorry for the late reply. Just to clarify, when you mention the "Visual Studio TypeScript Extension", are you referring to [these](https://marketplace.visualstudio.com/publishers/TypeScriptTeam)? If so, then these are equivalent to the SDK in the installer. You can install the SDK from the installer or from the mentioned link. The main purpose of this is that old versions of Visual Studio may not have the newest versions of TypeScript in the installer, so these online downloads will bridge the gap and allow you to use the latest TypeScript in Visual Studio. So in general the two sources for TypeScript are NuGet and SDK.

The mechanism for how these two work might be interesting to know as well, so I can explain it here. The SDK is installed in a well known location (`C:\Program Files (x86)\Microsoft SDKs\TypeScript`). You can check there and you'll find `tsc.js` for compilation, `tsserver.js` for the language server (IntelliSense) and any libraries they depend on. The NuGet package is similar in that it contains mostly the same contents, but it is completely managed by the NuGet package manager in terms of where it's installed/cached.

So let's get to your questions:
- How do you know which ones to use?

Historically the SDK has been used more, but NuGet should be preferred moving forward (for TypeScript 3.2+ and VS2019+). The reason for this is that the NuGet package from 3.2 onwards supports everything that the SDK does plus has some more benefits. One of these benefits is that you don't need to install an SDK on the machine whenever a new TypeScript version comes out - instead you can just update the NuGet package version. Since NuGet and MSBuild work well together, this should provide a better experience.

- How do you manage TypeScript version updates when using the Visual Studio TypeScript Extension, when each new TypeScript version is a completely new Extension?

You would need to download the latest version and install it.

- Do all packages provide the same and equal features and functionality?

As of TypeScript 3.2 the SDK and NuGet will have the same functionality. Specifically, the two functionalities that the SDK has always provided is compilation and Intellisense. NuGet has always provided compilation, and with version 3.2+ it also has IntelliSense.

- Are there any recommendations or best practices for using TypeScript in Visual Studio when it comes to which distribution of TypeScript to use?

Using NuGet is the simplest option and versioning TypeScript can just be handled by versioning the NuGet package. If you are using the SDK (if you are using an older version of TypeScript or using an older version of Visual Studio), then you can manage versioning by downloading the SDK version you need.

- Any risk of conflicts if you, for example, use the Type Script SDK installed via the VS Installer, and then reference a NuGet package that have a dependency on the TypeScript NuGet package?

The NuGet package should only be a build dependency (packages should not list it as a dependency in the nuspec).

- What are the different ways of configure TypeScript and how do they relate to each other? For example, the GUI settings for TypeScript in Visual Studio Options (Menu: Tools -> Options), how do they relate to the various file-based settings?

The options in `Tools -> Options` are the user preferences for the editor/IntelliSense (stuff like tabs vs spaces). This should not affect compilation and are generally a global editor setting. On the other hand, the file based settings (like the MSBuild properties [here](https://www.typescriptlang.org/docs/handbook/compiler-options-in-msbuild.html)) are project level compilation settings. Here you'll see things like `$(TypeScriptStrictNullChecks)` that you can put in the csproj. In addition, there is the project properties page (right click the project in the Solution Explorer and select `Properties`), which is just a UI that will write back into the csproj. This is just a convenience instead of manually editing the csproj.
