### ISSUE TITLE
JSDoc descriptions with @tags in backticks don't work since 3.5

### ISSUE THREAD

**Issue by zavr-1** [microsoft/TypeScript#31993]
**TypeScript Version:**  3.5.1

**Search Terms:** jsdoc backtick

**Code**

```ts
// BELOW [description with `@interface`] IS BROKEN
/**
 * @typedef {Object} Keygrip `@interface` Signing and verifying data.
 * @prop {function(?): string} sign This creates a SHA1 HMAC.
 */

// BELOW IS OK
/**
 * @typedef {Object} Keygrip Signing and verifying data.
 * @prop {function(?): string} sign This creates a SHA1 HMAC.
 */
```

**Expected behavior:**

![Screenshot 2019-06-20 at 03 20 16](https://user-images.githubusercontent.com/21156791/59809678-5bc36980-930a-11e9-8d44-bc45e3adb2ad.png)

**Actual behavior:**

![Screenshot 2019-06-20 at 03 20 47](https://user-images.githubusercontent.com/21156791/59809695-6e3da300-930a-11e9-9b4a-fb0d5d011f6d.png)

This was fine in **3.4**. It's not fixed in **next** (3.6).

**Playground Link:** 

**Related Issues:**

**Comment by sandersn** [comment]
That was an intentional change that was part of a bugfix. JSDoc doesn't technically use markdown, and in fact has no way to escape `@`.

However, I think we can do better -- our jsdoc parsing previously did the *wrong* thing, so it should be possible to do the right thing instead, or at least simple matching of backticks in order to skip `@`.

**Comment by zavr-1** [comment]
@sandersn thank you brother.
