### ISSUE TITLE
Using super inside async class method generate error

### ISSUE THREAD

**Issue by naorzr** [microsoft/TypeScript#31999]
Using 'super' keyword inside async class method generates the following error
```SyntaxError: 'super' keyword unexpected here```

I'm using typescript 3.5.2

**Expected behavior:**
Be able to use 'super' inside async class method

**Actual behavior:**
Throws error when running the compiled code

**Playground Link:** 
https://www.typescriptlang.org/play/#src=class%20Greeter%20%7B%0D%0A%20%20%20%20greeting%3A%20string%3B%0D%0A%20%20%20%20constructor(message%3A%20string)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.greeting%20%3D%20message%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20greet()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20Promise.resolve(%22Hello%2C%20%22%20%2B%20this.greeting)%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20Greeter2%20extends%20Greeter%7B%0D%0A%20%20%20%20async%20greet2()%20%7B%0D%0A%20%20%20%20%20%20%20await%20super.greet()%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A

**Related Issues:**
https://github.com/microsoft/TypeScript/issues/5124

**Compiler Options**
```
  "compilerOptions": {
    "typeRoots": ["./types", "./node_modules/@types"],
    "sourceMap": true,
    "removeComments": false,
    // Target latest version of ECMAScript.
    "target": "es6",
    "module": "commonjs",
    "resolveJsonModule": true,
    // Search under node_modules for non-relative imports.
    "moduleResolution": "Node",
    // Process & infer types from .js files.
    "allowJs": true,
    // Enable strictest settings like strictNullChecks & noImplicitAny.
    //    "strict": true,
    // Disallow features that require cross-file information for emit.
    "isolatedModules": true,
    // Import non-ES modules as default imports.
    "esModuleInterop": true,
    "outDir": "build/",
    "baseUrl": "."
  }
```

**Comment by RyanCavanaugh** [comment]
I don't see an error when building + running this code. Can you post the generated JS and point to where the runtime is identifying a syntax error? Please unassign yourself once that info's provided - thanks!

**Comment by mgroenhoff** [comment]
I came across the same error today. This is mainly caused by the fact that references to `super.x()` are transformed into `_super.x.call()` which indirectly references `super` via a local variable when using a target version where the async functions are transformed into `__awaiter(... function *() { ... })` calls.

Here is a link to [TypeScript Playground](http://www.typescriptlang.org/play/?target=3&ts=3.7-Beta#code/LAKAxgNghgzjAEBBeBvU8PwA4CcD2ALgKZjEAm8sAngHZjwD6AZnngBQCUAXPAAr4BbAJYwiAHgBueIWQB8qAL6glIUJFgIAQvCIAPYjTIJkaEJmwBXAEYQh9APQAqanUf34Ldtz6CR4qTLypubmMBZYRDgAdMysnADc8E7oIRgAeh5CNERR8G6gKak4RAQWODTwbC70nPAAvEGFqZhhEdGxXonJZs3mGTC0BFC6Ojj4OPAAFpFE8EJMAIR59k3mChwJTSoqoGzZAO7wmhxRnpygQA) that demonstrates this. It also contains a commented out `async` keyword that when added causes it to generate the correct code.

A workaround is to add the `async` keyword or if it is not an async function to manually save a reference to whatever you are trying to reference on super ([Example](http://www.typescriptlang.org/play/?target=3&ts=3.7-Beta#code/LAKAxgNghgzjAEBBeBvU8PwA4CcD2ALgKZjEAm8A+gGZ54AUAlAFzwBueAlhSgL6j8QoSLAQAheEQAexAHZkEyNCEzYArgCMInMPFoMW7Lj3SrMMNViI4AdDTpMA3PAD0AKlNn4APT2dZRDbwbi6gnmZgeLIwBFQWVjj2ePAAvPDx1nb6jmEqXvD0sACesrpMqQB8qOH5cZbWSU6uHnm1GL6yhPBQEDDJ1P6BwaGtZryMTuGCgqD0AQDu8GKMNvpMoEA)).

**Comment by manuth** [comment]
Same thing also happens when trying to deal with asynchronous accessors as seen in [this TypeScript Playground](https://www.typescriptlang.org/play/index.html?target=3&module=1#code/MYGwhgzhAECC0G8CwAoa7oAcCuAjEAlsNAOYCmALtAMID2AdhWYwBQCUAXNAAoBOtAWwIQyAHggVeBeiQB8iVBiXRelbL3rQWi5bsgBPesXbQAvPORpd19KorrNAImAMmjRwG4dN9AF827F5Wfqi+qKigkDAAQtBkAB5uACYw8JZKOPhEpJQ0rswU7Fx8gsJiElIyFt7Kdg5aNTYGRlpsZtXBPkp1GlpgAO5gBFQQ2JhkvAB0dIwFbJMUtACqmOO81JBkgY3W-tudYSi+QA)

Thanks, btw, for the helpful advices!
Saving references to local variables helped me to work around this issue.
