### ISSUE TITLE
Export default for CommonJS

### ISSUE THREAD

**Issue by cuongw** [microsoft/TypeScript#32048]
I am creating a npm package that is written by TypeScript and support ESNext and CommonJS. I am having an issue about config `tsconfig.json`. I hope have a solution. Thanks.
```
// index.ts
export default foo;
// index.js
exports.default = foo;
```
Usage:
```
const foo = require('foo').default;
```
Expect:
```
const foo = require('foo');
```
```
// tscofig.json
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "lib": ["es6", "dom"],
    "declaration": true,
    "outDir": "./lib",
    "strict": true
  },
  "include": ["src"],
  "exclude": ["node_modules", "**/__tests__/*"]
}
```

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
