### ISSUE TITLE
Support 'as const' together with type restriction

### ISSUE THREAD

**Issue by KnutRyagerInmeta** [microsoft/TypeScript#32043]
Would be nice to be able to apply type checking to 'as const' types, currently I have to use the silly trick of using type checks when writing them, then switch to 'as const' afterwards.

```
type MyType = {name: string};

const x:MyType = {
    name: 'test' // Autocompleted, typesafe. But Type is {name: string}, not 
                 // what I want, I want {readonly name: 'test'}
} as const;

const x = { name: 'test' } as const; // Gives correct type, but no type check for MyType...
```

**Comment by MartinJohns** [comment]
Your type `MyType` clearly says that `name` is a mutable property. If you want it read-only, then you can just use `Readonly<MyType>`.

**Comment by jcalz** [comment]
Helper function to the rescue!

```ts
type MyType = { name: string };
const asMyType = <T extends MyType>(x: T) => x; // helper function
const x = asMyType({ name: "test" } as const); // 😃
```

**Comment by KnutRyagerInmeta** [comment]
@jcalz this does the trick.

@MartinJohns readonly was not originally of my concern, but emerged with 'as const'. Seems with jcalz's solution readony does not emerge. Now a single string literal type should be readonly by implication though... well you are allowed to overwrite with the same string I guess.

**Comment by MartinJohns** [comment]
@KnutRyagerInmeta You mean a string literal type, e.g. `'fixed'` instead of `string`. In that case the same logic applies: Your type `MyType` explicitly says the property `name` can be of **any** string.

With jcalz solution you will have the same issue when you use the wrong type:

    const x: MyType = asMyType({ name: "test" } as const); // x.name is of type string again

But I likely misunderstand you, and you want something like "make sure this object matches SomeType, then make it a const context", in which case jcalz solution is probably the best.
