### ISSUE TITLE
Variance of union function types going in the opposite direction 

### ISSUE THREAD

**Issue by eloytoro** [microsoft/TypeScript#32045]
**TypeScript Version:**  `3.5.2`, `next`

**Search Terms:** function covariance/contravariance in union types

**Code**

```ts
interface Common {
  c: 0
}

interface A extends Common {
  a: 1
}

interface B extends Common {
  b: 1
}

const b: B = { c: 0, b: 1 };

type fnA = (a: A) => Common;
type fnB = (b: B) => B;

declare var actual: fnA | fnB;
declare var expected: (arg: A | B) => B;

actual(b);
expected(b);
```

**Expected behavior:**

According to the [rules of covariance/contravariance in inherited function types](https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science)#Function_types) the resulting type should have more general argument types and more specific return types, what happens right now is exactly the opposite.

The type `fnA | fnB` has a signature of `(arg: A & B) => Common`, in this case `A & B` is more specific and `Common` is more generic

**Actual behavior:**
`fnA | fnB` should resolve to `(arg: A | B) => B`

**Playground Link:** 
https://www.typescriptlang.org/play/#src=interface%20Common%20%7B%0D%0A%20%20c%3A%200%0D%0A%7D%0D%0A%0D%0Ainterface%20A%20extends%20Common%20%7B%0D%0A%20%20a%3A%201%0D%0A%7D%0D%0A%0D%0Ainterface%20B%20extends%20Common%20%7B%0D%0A%20%20b%3A%201%0D%0A%7D%0D%0A%0D%0Aconst%20b%3A%20B%20%3D%20%7B%20c%3A%200%2C%20b%3A%201%20%7D%3B%0D%0A%0D%0Atype%20fnA%20%3D%20(a%3A%20A)%20%3D%3E%20Common%3B%0D%0Atype%20fnB%20%3D%20(b%3A%20B)%20%3D%3E%20B%3B%0D%0A%0D%0Adeclare%20var%20actual%3A%20fnA%20%7C%20fnB%3B%0D%0Adeclare%20var%20expected%3A%20(arg%3A%20A%20%7C%20B)%20%3D%3E%20B%3B%0D%0A%0D%0Aactual(b)%3B%0D%0Aexpected(b)%3B

**Related Issues:**

**Comment by jcalz** [comment]
But there are no inherited function types here; instead you've got a union of functions.  And a union of function types can only safely take an intersection of their parameter types.  This is working as intended, and this support was [added in TS3.2](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#improved-behavior-for-calling-union-types).  

If you have a function of type `fnA | fnB`, it means someone handed you either a `fnA` or a `fnB` but you don't know which it is.  And if you have a value of type `A | B`, it means someone handed you an `A` or a `B` but you don't know which it is.  You can't call the former function with the latter parameter... because you may have been handed a `fnA` and a `B`, or a `fnB` and an `A`.  You don't know, so you can't do it.  

On the other hand, if you've got an `A & B` value, you *can* pass it to a `fnA | fnB` function, because whether you've got a `fnA` or a `fnB`, the parameter is appropriate.  It's both an `A` *and* a `B`.
