### ISSUE TITLE
Ember auto type acquisition doesn't work

### ISSUE THREAD

**Issue by robgraeber** [microsoft/TypeScript#32075]
- VSCode Version: 1.34.0 
- OS Version: OS X 10.14.2

I've been trying to get the @ember/* types to work automatically without installing @types/ember. The automatic type acquisition doesn't seem to work out of the box. I've tried creating a jsconfig.json file with all sorts of combinations in the typeAcquistion.include field. I saw someone post last year that it was working out of the box for them, so wanted to confirm it is still supported. 

Steps to Reproduce:

Load the attached default ember project, and npm install.
Go to test-component.js and see if the types work for the @ember/* imports.

[ember-example.zip](https://github.com/microsoft/vscode/files/3249848/ember-example.zip)
[tsserver.log](https://github.com/microsoft/vscode/files/3249851/tsserver.log)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Moving upstream. Someone on the TS team should know more about what the expected behavior is here

**Comment by sheetalkamat** [comment]
@RyanCavanaugh @DanielRosenwasser I thought silent failure (except logging in ti log) was expected behaviour. What do you think should happen here? send some kind of event or something to the editor?

**Comment by DanielRosenwasser** [comment]
Wait, is there still a reason that we can't do ATA for scoped packages?

**Comment by sheetalkamat** [comment]
I don't think we ever supported it but there are two issues here?
1. probably we want to handle scoped packages and install `@types/ember__component` instead of `@ember/component` ?
2. What about the failure to install? #32084 says that it is silent. I think this is intended behavior ( that it only logs info in the ti log) but will let you decide.

**Comment by DanielRosenwasser** [comment]
I guess it depends on reasons for failure. If I'm working on a project with `checkJs`, I would want to know why IntelliSense isn't giving me expected results. Otherwise, it would be nice to be able to diagnose these things, in which case discoverability is really the issue. In some cases, users don't even know that their completions could be better, but how can you tell them in a non-invasive way that's still actionable.

**Comment by robgraeber** [comment]
hey @sheetalkamat did your change fix ATA for @ember/* modules? I'm trying the latest VS Code version (v1.38.1) which I think has the typescript v3.6.0+ and doesn't seem to work.
