### ISSUE TITLE
Make ES6+ APIs available when lower target version is specified for tsc

### ISSUE THREAD

**Issue by duanyao** [Microsoft/TypeScript#3211]
After updated TS to 1.5-beta, my code failed to compile. My code uses a few ES6 APIs such as `Set`, but the `--target` is still ES5. It seems TS 1.5-beta removed those ES6 APIs from `lib.d.ts` when targeting ES5. I think this is a bad change.

ES6+'s new language features and new APIs are very different stories. New APIs are shipped earlier in browsers, and can be polyfilled; language features are shipped later, and can't be polyfilled.

My code is targeting modern browsers, so relying on `Set` etc. is not a problem. But for obvious reason I can't specify `--target ES6` for `tsc` because ES6 new language features are not enabled by default in all browsers.

We may have two options to solve this problem:

* Restore all ES6+ APIs in `lib.d.ts`. This may be a short-term solution.
* Add a `--source` option to tsc to specify a "source code API level", values are same as `--target`. This is similar to `javac -source` option. So I can invoke `tsc --source ES6 --target ES5`. This may be a long-term solution.

**Comment by kitsonk** [comment]
Depends on what you consider a "Modern Browser".  Lots of people would consider IE11 a Modern Browser, but [it doesn't support Sets well](https://kangax.github.io/compat-table/es6/#Set) and iOS 7 doesn't support it either.  In a lot of cases, a polyfill or a shim, with the appropriate typings is the safest way to ensure that you don't suddenly stumble across cracks.  The number of egos I have seen dashed over the years thinking "well I will only run this in modern browsers..."

Instead of twisting TypeScripts arms to build something upon sand, I think the better approach is to utilise a shim that offloads to native and doesn't pollute/affect the global namespace in ES.  An example of such an approach in TypeScript is the [dojo-core/WeakMap](https://github.com/dojo/core/blob/master/src/WeakMap.ts).

**Comment by duanyao** [comment]
I generally agree with your point on "Modern Browser", however it is not quite on the topic.
Even if I can use some shim/polyfill, firstly I have to get my TS code compiled, and I don't want to explicitly import something which is supposed to be lib.d.ts by default.

P.S. Currently I have no plan to support IE11 and mobile browsers, so I said it is not a problem to use `Set` etc.

**Comment by Arnavion** [comment]
>and I don't want to explicitly import something which is supposed to be in lib.d.ts by default.

lib.d.ts is meant for ES5 and ES3 targets. lib.es6.d.ts is meant for ES6 target. Things not available in ES5 and ES3 were explicitly removed from lib.d.ts because of this.

You could make the case that there should be a compiler option to set the default lib to lib.es6.d.ts even when target is ES5 and ignore the ES6-only stuff from it (Symbols, etc.). But I feel this is something the typesystem already lets you solve, by making your own es6-shimmed.d.ts with whatever ES6 parts you want to shim for ES5.

**Comment by RyanCavanaugh** [comment]
Ask 20 JavaScript developers whether a given set of APIs is broadly and correctly implemented enough to use today and you're going to get 20 different answers.

Even though *some* browsers have (experimental) implementations of *some* of these APIs, we're not going to add them to the corresponding ES version lib.d.ts file.

You can manually specify a custom lib.d.ts file that has the APIs you think are widely-implemented enough in lieu of the ES5 lib.d.ts if you want to opt in to some ES6 APIs while still having ES5 emit.

**Comment by duanyao** [comment]
@RyanCavanaugh 

>Ask 20 JavaScript developers whether a given set of APIs is broadly and correctly implemented enough to use today and you're going to get 20 different answers.

True, but please let developers make the decision whether they want to take the risk. TS itself should not try too hard to "protect" them.

>Even though some browsers have (experimental) implementations of some of these APIs, we're not going to add them to the ES lib.d.ts file for the wrong version of ES.

Sounds a strange position. As I said, new ES APIs are very different to new ES language features, and APIs like `Set/Map` are shipped __far ahead of ES6__. So they should not be bound strictly to `--target ES6`. Do experimental ES APIs anything different to experimental HTML APIs?
Why you added so many experimental HTML APIs to `lib.d.ts` without a command line option to turn them off?

**Comment by mhegazy** [comment]
@duanyao we have split the library based on feedback from users using unsupported APIs. We are looking into ways to make including pollyfills simpler to alleviate this pain.

From TypeScript's perspective all you need is definitions, whether for DOM, or other JS APIs, you do not need `--target ES6` to use them, just add `lib.es6.d.ts` (which ships with the compiler, and includes all the definitions in lib.d.ts in addition to new ES6 definitions) to your compilation and you should be good to go. you can add it using /// reference, or by including it on the command line. See the [es6 library](https://github.com/Microsoft/TypeScript/blob/master/bin/lib.es6.d.ts) for more details.

**Comment by duanyao** [comment]
@mhegazy Thanks. If `lib.es6.d.ts` can be included from command line then it make sense to me. However I can't find such tsc option, can you elaborate?

**Comment by duanyao** [comment]
@Arnavion 

>lib.d.ts is meant for ES5 and ES3 targets. lib.es6.d.ts is meant for ES6 target. Things not available in ES5 and ES3 were explicitly removed from lib.d.ts because of this.

Things like `Map/Set` __are__ available in ES5 and ES3 mode of major modern browsers. Spec is a thing, but implementation is another thing. I don't think current `lib.d.ts` strictly follows any specs (I also don't think it should), or at least all vendor specific APIs should be removed.

A common practice is feature detection:

```javascript
If(`Set`) {
  //use Set
} else {
  //fallback
}
```
But we need the declarations in `lib.d.ts` to make above code compiled in the first place.

>You could make the case that there should be a compiler option to set the default lib to lib.es6.d.ts even when target is ES5 and ignore the ES6-only stuff from it (Symbols, etc.). But I feel this is something the typesystem already lets you solve, by making your own es6-shimmed.d.ts with whatever ES6 parts you want to shim for ES5.

Because TS already ships ES6 declarations with it, I don't want to duplicate the work. Additionally, if I include my own `es6-shimmed.d.ts`, and someone compiles my code in ES6 mode, it won't compile because of duplications.

**Comment by Arnavion** [comment]
Just to answer some things:

>However I can't find such tsc option, can you elaborate?

Just include it in the list of files you pass to tsc. There is no special option you need to pass (though you may want to pass `-nolib` to prevent lib.d.ts from also being used).

>Why you added so many experimental HTML APIs to `lib.d.ts` without a command line option to turn them off?

>I don't think current `lib.d.ts` strictly follows any specs (I also don't think it should), or at least all vendor specific APIs should be removed.

lib.d.ts is generated by combining core.d.ts, dom.generated.d.ts and some others. lib.es6.d.ts is generated from those plus es6.d.ts

Map and Set and some other ES6 types were originally in dom.generated.d.ts because that file contained everything supported by IE 11, which is why lib.d.ts ended up containing those types. Then the way that file was generated was changed, and those types are no longer present in dom.generated.d.ts, which allowed them to be moved to es6.d.ts

That's why the original lib.d.ts contained many ms-prefixed properties in addition to the standard HTML properties, and now it contains a mix of standard, ms- and webkit-prefixed properties as well.

Regardless of how loose dom.generated.d.ts is with respect to including more things than the HTML spec, core.d.ts only contains definitions for the corresponding ES spec. Since the ES5 spec does not contain those types, they are not in core.d.ts and thus now also not in lib.d.ts

(I do understand that not having the definitions at all also prevents writing feature-detection code.)

The discussion in https://github.com/Microsoft/TypeScript/issues/2953 is also relevant.

**Comment by duanyao** [comment]
@Arnavion Thanks for those information!

It seems the full path to the system `lib.es6.d.ts` should be pass to tsc? This is problematic because it will makes our build script non-portable. Copying `lib.es6.d.ts` to our project looks a bit heavy and dirty, and it won't receive updates automatically when we update TS.

I have read #2953  and https://github.com/enlight/dbgmits/issues/21, and still feel that this is a real issue.

**Comment by mhegazy** [comment]
@duanyao i think we can add a switch that allows you to pick the version of the lib to use. `--library lib.es6.d.ts` that defaults to `lib.d.ts` if not specified. would that work for you?

**Comment by Arnavion** [comment]
Alternatively TS could look for .d.ts files in its own directory as well as a last resort, so that just passing in `lib.es6.d.ts -nolib` would work.

**Comment by mhegazy** [comment]
implicit include path can get tricky with different editors/packaging options; but we can do that as well.

**Comment by mhegazy** [comment]
thinking about it a bit more, @Arnavion's idea would be better. you can also leverage this to add a /// reference in your node.d.ts for instance to "lib.core.d.ts" to short circuit any one using a different library with it, and all node.d.ts users would see the effect..

**Comment by duanyao** [comment]
@mhegazy @Arnavion 
I think both of your ideas could work. Thanks!
