### ISSUE TITLE
ScoreBing

### ISSUE THREAD

**Issue by Frankhof96** [microsoft/TypeScript#32128]
Please fill the following out:

- Name: ScoreBing
- Homepage url: https://www.scorebing.com/
- Brand Guidelines/Licensing: Yes, You can use our logo  
- Logo: https://www.scorebing.com/assets/images/index/V5indexLogoEn.png?_=2

**Comment by orta** [comment]
Hey folks -we're looking at a new website and it's likely that the friends of TypeScript page isn't going to make it to the new site. This is mainly because close to everyone is a friend of TypeScript now and listing folks kinda feels a bit un-inclusive to everyone else. 

So I'm going to close this issue - thanks for posting to apply
