### ISSUE TITLE
Type inference with destructuring and concat

### ISSUE THREAD

**Issue by thany** [microsoft/TypeScript#32137]
**TypeScript Version:**  3.5.1 (Playground)

**Search Terms:** type inference destructuring 

**Code**
```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.

const [firstone] = [...document.querySelectorAll("div")].reduce((result: HTMLDivElement[], div) => {
    return result.concat(div.querySelector("div"));
}, []);
```

**Expected behavior:**
I wouldn't expect any errors here. Every type is sufficiently declared for the compiler to know exactly what's what.

**Actual behavior:**
The bit `div.querySelector("div")` has a curly.:
```
Argument of type 'HTMLDivElement | null' is not assignable to parameter of type 'HTMLDivElement | ConcatArray<HTMLDivElement>'.
  Type 'null' is not assignable to type 'HTMLDivElement | ConcatArray<HTMLDivElement>'.
```
The first part of this error seems wrong. HTMLDivElement is definitely assignable to HTMLDivElement. Sure it could be null, but concatting with null is perfectly valid, afaik.

Another part, `firstone` also has a curly:
```
Initializer provides no value for this binding element and the binding element has no default value.
```
This is a very weird error. I don't even understand how something like this could come to be. The binding element? Huh? The return value of the reduce function is `HTMLDivElement[]`, so destructuring that to a single (first) value, should make it of type `HTMLDivElement`. And it does. So what's with the error? Sure, the result of reduce may be an empty array, but then `firstone` would become undefined, which is a perfectly valid situation.

**Playground Link:**
[Playground Link be here](https://www.typescriptlang.org/play/#code/MYewdgzgLgBA2gMwJYCdrgKYF0YF54B0RAJiMAK4C2GYUBAjuRigJ4DKGANhsFCCgEFOnABQAiYkgBuYgJRYCKDMXLAMIkUojlOUAFwwAEgBUAsgBkAItICi3arThYANDElTZeAHwwA3gCgYIJglKHIUMBCMbV0CUDBgAEMoEXcGJlYObl5+cXc5WQBufwBfVycioA)
 

**Related Issues:** 
Not really. Some issues about type inference with destructuring, but nothing that I could find matches the problem described above.

**Comment by RyanCavanaugh** [comment]
Problem 1:
```ts
const qs = [...document.querySelectorAll("div")];
```
`[...NodeList]` doesn't work in older browsers and your current compiler settings think you're targeting an older browser. Effectively your `lib` setting doesn't include `dom.iterable`, probably because `target` is too low.

Problem 2: The definition of `concat` assumes you want to produce a homogenous array (i.e. `[1, 2].concat("Hello")` is considered an error). `querySelector` might produce `null`, so you're potentially introducing `null`s into an array that doesn't currently allow nulls. The fix here depends on your intent; if you want to possibly get `null`s in, write `concat<HTMLDivElement | null>(div.querySelector("div"))`. If you want to assert that the `null` will never occur, write `concat(div.querySelector("div")!)`.

Problem 3: See #32140. The best fix would be to write `reduce(....., [] as HTMLDivElement[])`

**Comment by RyanCavanaugh** [comment]
See also #30164

**Comment by thany** [comment]
As for 1, why does the compiler not compile these constructs down to a for-loop if I'm specifically targeting older browsers? It seems to be trying to produce modern code, and failing on it because the target doesn't support it... Should be fixed in TS.

As for 2, I'm initializing the array as `[]` which should be equivalent to `any[]` which should allow `null` values, should it not? The `values` argument _is_ typed, but as `HTMLDivElement[]` which are objects, which can be null. So I don't see why null values would not be allowed here.

As for 3, that's an alternate solution to 2, no?

**Comment by RyanCavanaugh** [comment]
1 - turn on `downlevelIteration`

2 - the type of the empty array in is `never[]`, not `any[]`. The error message indicates you have `strictNullChecks` turned on, which means `null` is not a valid `HTMLDivElement`

3 - correct
