### ISSUE TITLE
Typescript warning (ts7016) is showed in Javascript Files

### ISSUE THREAD

**Issue by wangchou** [microsoft/TypeScript#32148]
- VSCode Version: 1.35.1
- OS Version: macOS Mojave 10.14.5

Steps to Reproduce:

1. create a file ended in .js with import like my <code>rollup.config.js</code>
<img width="1008" alt="スクリーンショット 0001-06-16 13 49 27" src="https://user-images.githubusercontent.com/32716/59560069-081cfb80-903e-11e9-945a-b955205ed332.png">

The only workaround I found is adding a typescript config <code> tsconfig.json</code> in my <code>javascript project</code> folder like
```json
{
    "compilerOptions": {
        "outDir": "./xyz",
        "noImplicitAny": true,
        "suppressImplicitAnyIndexErrors": true,
        "allowJs": true
    }
}
```

I hope one day I could get rid of typescript config from a javascript project...

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
The `...` indicates a suggestion, not warning. In this case, the suggestion tells you won't get any IntelliSense for `rollup-plugin-svelte` because we could not find any [typings](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_typings-and-automatic-type-acquisition) for it. You can disable suggestions such as this by setting: `"javascript.suggestionActions.enabled": false`

Moving upstream to see if we want to change the UX

**Comment by wangchou** [comment]
@mjbvz thanks for replying. it works 👍 

vscode now shows suggestions with prefix like `js(6133)` or `ts(7016)`.
I think **showing js suggestions only for js file by default** would generate better UX.

**Comment by RyanCavanaugh** [comment]
@mjbvz I don't think one feedback on this is enough to warrant doing anything. It's a good suggestion for people who want high-quality completion results

**Comment by wangchou** [comment]
@RyanCavanaugh two feedbacks, now. How many feedbacks should I collect?
https://github.com/microsoft/vscode/issues/75858

**Comment by mehas** [comment]
Would it be possible to have a **typescript**.suggestionActions.enabled option?

**Comment by rhernandog** [comment]
```
Version: 1.36.0 (user setup)
Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
Date: 2019-07-03T13:25:46.372Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

I have to agree with @wangchou in this one. I don't want TS warnings, suggestions, etc, in my JS files, heck sometimes this errors pop up when I simply delete a line in my code, and they come in bunches all over a single file.

The main problem here is that somehow you're stating: "Use TS instead of JS". While there are advantages in using TS is just not right to force people to use a particular technology.

The only workaround I've found is to disable js validate, close the program, start it again and enable js validate again.

@RyanCavanaugh that would be three feedbacks now. While this is not happening a lot all over the user base it has been reported quite a few times already: [#54261](https://github.com/Microsoft/vscode/issues/54261), [#54868](https://github.com/microsoft/vscode/issues/54868) and also if you look in stackoverflow you'll see a few incidences there.

Hopefully this can be solved.

Anyway thanks for your hard work and dedication, VSCode is a great piece of software that makes coding very easy and fun.
Best,
Rodrigo.

**Comment by RyanCavanaugh** [comment]
>  I don't want TS warnings, suggestions, etc, in my JS files, heck sometimes this errors pop up when I simply delete a line in my code, and they come in bunches all over a single file.

You can turn off this behavior, as noted above.

> The main problem here is that somehow you're stating: "Use TS instead of JS".

This isn't the intent.

**Comment by mehas** [comment]
> You can turn off this behavior, as noted above.

But it disables Javascript AND Typescript warnings.

This does not match the expected behavior. Disabling validation for JS should disable validation for JS, not other languages.

Can we just add a `typescript.validate.enable`, like `javascript.validate.enable`?

Seems to be a lot of pushback from the devs on the 3 or 4 tickets opened by users that are confused by this behavior. Is there a reason why?

**Comment by rhernandog** [comment]
@RyanCavanaugh I know that is not the intend and I'm not implying that and I'd like to apologize for not making myself clear.

Unfortunately the implementation in the software causes this discomfort, that forces to disable JS validation because of a different file type validation is being enforced in a file that has no trace of the aforementioned file type.

Finally the issue does not comes up every day and at every working hour, but I'm used to seeing it a couple of times a week for the past few months. I can't pinpoint **when** exactly this started but it has been a while though.

Once again, thanks for all your work and sorry I wasn't clear enough in my previous post.

Have a nice day!!

**Comment by Relequestual** [comment]
I want the js errors. I do not want the ts errors.
The codes are known.
Would it not be possible (and maybe even simple) to provide an option that allows the results to be filtered to exclude ts errors?

**Comment by thebinarysearchtree** [comment]
This is not very nice for libraries that do not want to provide TypeScript definitions. It is essentially forcing us to write definition files for TypeScript, when we may have no interest in TypeScript at all.

**Comment by sam-lippert** [comment]
How does it make sense to show typescript errors in javascript files? I just spent an hour trying to figure out why this error was happening, and the real reason is because someone well-actually'd its inclusion and closed the ticket four years ago. Maybe the real fix is uninstalling VS Code.
