### ISSUE TITLE
Smart Select doesn't select the word before the punctuation anymore

### ISSUE THREAD

**Issue by diabolicle** [microsoft/TypeScript#32159]
**TypeScript Version:**  3.5.1

**Search Terms:** smart select, selection, vscode

**Code**

```ts
console/**|*/.log()
arr/**|*/[]
open/**|*/()
```

**Expected behavior:**

The word before the punctuation/bracket should be selected. This was the previous behavior and I personally find it more intuitive. Alternatively, maybe it could select the entire bracket? I just don't find selecting the left bracket very useful.

**Actual behavior:**

The punctuation/bracket is selected.

**Playground Link:** 

**Related Issues:**

**Comment by andrewbranch** [comment]
This is a decision that kind of comes down to opinion/taste, but the logic I chose intentionally works like this:

> Consider the current token to be that immediately ahead of the caret, UNLESS that token is whitespace AND the token immediately behind the caret is not whitespace, then consider the current token to be the one immediately behind the caret.

The justification for my decision is block-style cursors and the way they imply the location of edits, as utilized heavily in editors like vim. Even if I change VS Code to use a block-style cursor, I think it becomes clear that the when forced to choose between the left token and the right token, it makes more sense to choose the one to the right, because that’s the token that’s literally _under_ the cursor:

![smart-select](https://user-images.githubusercontent.com/3277153/60455139-8656d180-9bea-11e9-8b70-e19a208bf00a.gif)

That said, it’s kind of splitting hairs, and there’s room for opinions here. My opinion is that the current behavior is correct, but I’m not strongly attached to that opinion—if the majority of others expect a different behavior, we should change it.

@mjbvz any thoughts here?

**Comment by diabolicle** [comment]
> Consider the current token to be that immediately ahead of the caret, UNLESS that token is whitespace AND the token immediately behind the caret is not whitespace, then consider the current token to be the one immediately behind the caret.

Is that a simplification of the logic? Because I get results that don't adhere to those rules. For instance:

```js
console.log("rabbit/**|*/"); // selects 'rabbit' then '"rabbit"'
console.log("rabbit"/**|*/); // selects ')' then 'console.log("rabbit")' then 'console.log("rabbit");'
```

I don't have any strong opinions either, but I'd prefer consistency with JSON and the old behavior.

**Comment by andrewbranch** [comment]
Yeah, string literals have their own special rules. Quotes aren’t actually syntactic tokens; the entire string, quotes included is a single token. So we made a special rule that selects inside the quotes first.

I suppose the most compelling reason to change the behavior is that VS Code actually highlights instances of the identifier behind the cursor:

![image](https://user-images.githubusercontent.com/3277153/60458763-4dbbf580-9bf4-11e9-878b-ee554f2f39d5.png)

But then, between an identifier and braces, it highlights both, making the choice a bit of a toss-up again:

![image](https://user-images.githubusercontent.com/3277153/60458715-37ae3500-9bf4-11e9-9605-256bcb9a4d34.png)

**Comment by diabolicle** [comment]
Here is another example demonstrating the usefulness of the expected behavior:

```ts
export const a = async (b: string/**|*/) => {}; // selects ')' then 'async (b: string) => {}'
// vs
export const a = async (b: string/**|*/) => {}; // selects 'string' then 'b: string' then '(b: string)''
```

The way I see it, I'm _inside_ the brackets similar to how I'm _inside_ the quotes.

On another note, is there is a way to disable language smart-select providers? Can I just keep the default provider instead?
