### ISSUE TITLE
New Website Logo: TypeScript MasterClass

### ISSUE THREAD

**Issue by miloszpp** [microsoft/TypeScript#32184]
Please fill the following out:

- Name: TypeScript MasterClass
- Homepage url: https://typescriptmasterclass.com
- Brand Guidelines/Licensing: none
- Logo: https://typescriptmasterclass.com/wp-content/uploads/2019/05/Logo.png

TypeScript MasterClass is a newsletter and an on-line course about TypeScript.

**Comment by orta** [comment]
Hey folks -we're looking at a new website and it's likely that the friends of TypeScript page isn't going to make it to the new site. This is mainly because close to everyone is a friend of TypeScript now and listing folks kinda feels a bit un-inclusive to everyone else. 

So I'm going to close this issue - thanks for posting to apply
