### ISSUE TITLE
Code analysis hangs in a loop with Typescript 3.5.2 in IntelliJ IDEA 2019.1.3 (UE)

### ISSUE THREAD

**Issue by jollytoad** [microsoft/TypeScript#32200]
**TypeScript Version:**  3.5.2 and 3.6.0-dev.20190701

**Search Terms:**

3.5.2 IntelliJ IDEA analysis hangs infinite loop

**Code**

Sorry i can't create a totally self-contained piece of code, and even so, it always compiles perfectly fine, seems to be an issue with the language service. Any this is probably the simplest file that we have that gets 'stuck'...

```ts
import {Credentials, S3} from 'aws-sdk'

export const s3 = (credentials: Credentials, region: string) =>
    new S3({
        apiVersion: '2006-03-01',
        credentials,
        region
    })
```

**Expected behavior:**

Code analysis performs quickly, and green tick appears in the top-right corner of IntelliJ editor.

**Actual behavior:**

The 'eye' icon is always present, when hovering it shows a 'Performing code analysis' popup with various progress bars that appear to keep resetting.

**Playground Link:** 

**Related Issues:**

**Comment by jollytoad** [comment]
oh oh oh, isn't it typical, only moments after submitting this that particular file appear as ok!
BUT, i've still got other files that appear to be 'stuck'!

This is making me think it could be a performance regression rather than an outright failure

oh and BTW, downgrading to 3.5.1 cause everything to analyse perfect fine and in quick time.

**Comment by jollytoad** [comment]
and another goes green eventually (still with TS 3.6.0-dev.20190701)
this is screaming out performance regression now!

If anyone can point me in the right direction, i'd be happy to supply any diagnostics for this.

**Comment by G-Rath** [comment]
@jollytoad It would be worth making a ticket for this in [YouTrack](https://youtrack.jetbrains.com/issue/) in case this is an issue specifically w/ IntelliJ.

Have you tried with other IDEs? and have you checked the output of the logs?
IDEs can be interesting beasts, as they often achieve the same end result in completely different ways.

I use IJ personally, and not had a lot of huge performance problems, but also know that there are a number of different ways things can go wrong w/ IJ :)

Feel free to ping me on the [gitter channel](https://gitter.im/Microsoft/TypeScript) for some real-time debugging if you'd like (username is same as github) - otherwise I'd definitely recommend making a YouTrack issue & linking it here.
