### ISSUE TITLE
has no initializer and is not definitely assigned in the constructor

### ISSUE THREAD

**Issue by CunFlower** [microsoft/TypeScript#32226]
i want to know why ? 
![image](https://user-images.githubusercontent.com/19500680/60561350-ce5e2b80-9d85-11e9-9d0e-6444e688c602.png)

**Comment by RyanCavanaugh** [comment]
The error is that you haven't initialized `name`.

It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!

**Comment by CunFlower** [comment]
> The error is that you haven't initialized `name`.
> 
> It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript _itself_, rather than a general forum for programmers using TypeScript to get help or ask questions.
> 
> You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!

OK，thks
