### ISSUE TITLE
No intellisense or linting in VS Code

### ISSUE THREAD

**Issue by neptunian** [microsoft/TypeScript#32259]
**TypeScript Version:**  3.5.1

**Expected behavior:**
For intellisense to work and tslint.  I've followed directions exactly here: https://code.visualstudio.com/docs/typescript/typescript-tutorial .  

**Actual behavior:**
No intellisense or red squiggly lines to indicate errors. It seems the language server isn't starting for some reason.  Does anyone know how can I troubleshoot further or if there is somewhere else I can get help?

**Comment by Seally** [comment]
Never saw this before. Are you sure you have TypeScript installed properly? Since that page instructs a global npm install there's a possibility that it won't be able to find it if the path environments happen to be different for whatever reason (depending on how Node, npm/yarn, the PATH variable, and maybe nvm is set up on your machine). Or when installing you missed the `-g` in `npm install -g typescript` and it ended up in wherever your current directory was at the time (happens to me occasionally).

You can also try Initializing a `package.json` and just add the `typescript` package to dev repositories and it should work.

On a side note, this is probably more appropriate as a VS Code issue.

**Comment by neptunian** [comment]
running `tsc --version` shows typescript version and and if i run `tsc test.ts` it shows me the correct errors.  So its installed and working, just not with VS Code.  I've opened an issue over there, too, but wanted to see if anyone else has experienced this.

**Comment by neptunian** [comment]
Got it working!  I deleted all my preferences and it reopened and everything was working:
`rm -rf $HOME/Library/Application\ Support/Code`
