### ISSUE TITLE
Use strict within AMD define callback if no dependencies

### ISSUE THREAD

**Issue by u-nikos** [Microsoft/TypeScript#3235]
Hey all,

Is it possible to insert the 'use strict' flag within a AMD define callback if the script has no dependencies?

Script with dependencies:
```typescript
import dependency = require("dependency");
"use strict";
class myModule {}
```
Compiles to:
```typescript
define(["require", "exports"], function (require, exports) {
    "use strict";
    var myModule = (function () {
        function myModule() {
        }
        return myModule;
    })();
});
```
Script without dependencies:
```typescript
"use strict";
class myModule {}
```
Compiles to:
```typescript
"use strict";
define(["require", "exports"], function (require, exports) {
    var myModule = (function () {
        function myModule() {
        }
        return myModule;
    })();
});
```

**Comment by mhegazy** [comment]
Just to clarify, the request is in emitting AMD modules, move the use strict inside the body of the require call instead of outside it. this also applies to UMD and System.

On another note, in the example above, 
```ts
import dependency = require("dependency");
"use strict";
class myModule {}
```
the use of "use strict" is not valid as it is not the first statement in the file. it is treated like a normal expression statement (e.g. "blah"); it just happens that the emitter emits as the first statement of the body, it just happens to work in this sample. this on the other hand would break:
```ts
import d, * as ns from "dependency";
"use strict";
d; ns;
```

**Comment by u-nikos** [comment]
Yes, I want to be able to place a "use strict" statement inside the body of the AMD definition function when generating AMD modules.

**Comment by mhegazy** [comment]
Fixed by https://github.com/Microsoft/TypeScript/pull/5116
