### ISSUE TITLE
"JSDoc support in JavaScript" vandalized?

### ISSUE THREAD

**Issue by Darker** [microsoft/TypeScript#32397]
I was using this document for guidance when writing more complex JSDoc type hints in visual studio 2017. I use vanilla javascript.

Somebody just vandalized, deleting all the helpful text that was there for a year or so. It should probably be reverted.

**Comment by cpplearner** [comment]
> A comprehensive introduction to type checking JavaScript files with TypeScript can be found in the [official handbook](https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html).

**Comment by orta** [comment]
Thanks for the issue, but Yep not vandalism. All of those docs are in the same place now, instead of being somewhat duplicated across many places.

https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html#supported-jsdoc

If you specifically want to get to the _exact_ part of that wiki page.

**Comment by pcolangelo73** [comment]
It would be nice if the link to the news docs could be posted in https://github.com/Microsoft/TypeScript/wiki/JSDoc-support-in-JavaScript

That document is still a top result on google when searching "JSDoc Typescript" and many people have likely bookmarked the page. I only found the above mentioned docs after searching the issue tracker.

**Comment by cpplearner** [comment]
@pcolangelo73 I take that to mean the link to “[official handbook](https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html)" is not clear/noticeable enough?
