### ISSUE TITLE
Generic type infer in overloaded function

### ISSUE THREAD

**Issue by Brooooooklyn** [microsoft/TypeScript#32418]
**TypeScript Version:**  3.5.2

**Code**

```ts
export type InputFactory<State, Inputs = undefined> = Inputs extends undefined
  ? (state$: Promise<State>) => Promise<State>
  : (inputs$: Promise<Inputs>, state$: Promise<State>) => Promise<State>

export function usePromise<State>(inputFactory: InputFactory<State>): State | null
export function usePromise<State>(inputFactory: InputFactory<State>, initialState: State): State
export function usePromise<State, Inputs>(
  inputFactory: InputFactory<State, Inputs>,
  initialState: State,
  inputs: Inputs,
): State

usePromise(
(inputs$, _) =>
    inputs$.then(([v]) => v), // why typescript want Promise<number[]> here???? I hovered my mouse to userPromise and I could see the generic params in usePromise was inferred to <0, [number]>. So I assumed the typechecker would like Promise<0> or Promise<number> instead of Promise<number[]> here
    0,
    [1000],
)
```

**Expected behavior:**
usePromise has no type issues without generic type annotation.

**Actual behavior:**
usePromise has issues without generic type annotation.

**Playground Link:** 
http://www.typescriptlang.org/play/#code/KYDwDg9gTgLgBDAnmYcCSA7MBXGAxAQwGMZpEAeAZRgJmABp0tcBnOAXjmwwBNgAzAJYZgPAHwcmOGG1B1ebbnyEieAKDhwA-HAAULGnQAkALjgAFKBAC2glsCqHgYgJQcJlm3YfVazjXBmusLSLKYWVrb25JihYowGfuGeUT5Oru4RXtG+dGJqaqCQsHD83CSCEBhc9inejn5iwcz4xKRQiGaxuIQkZA15Lma5qAA+cBjYADZTheDQ8GUYFVU1wHU56c3Sve2dUj1t-SPxcMKCMIIEUyPDTkNwI3PFi+WXq9i1kfUjjN0yTQCIUOfQ6XRau2OTj+LRY8SBGAuVxuTjufnoCNC4NCGIeTzUn3W33sujU21YRkYAH03Ox8ppNMCZEYAHQwAAWwAwul0AG0AG4AXVpEn5LgxDLgAAYJQzeQBGKVKwW4gqEjYOSbWABGwCgjF5Wt1UEFgPJzOpIoCjNhrI5XJ5AuFmTFss0MutcAVSqlKrULiAA
**Related Issues:** 
No

**Comment by RyanCavanaugh** [comment]
Generic inference isn't able to do overload resolution at the same time

**Comment by Shigma** [comment]
Just to add some notes.

```ts
function foo (arg: string): string
function foo (arg1: number, arg2: number): number
function foo (...args: any[]) {
  // do something
}

type Param = Parameters<foo>
// expected: [string] | [number, number]
// actual: number

type Result = ReturnType<foo>
// expected: string | number
// actual: number
```

**Comment by dragomirtitian** [comment]
@Shigma This works most of the time:

```ts
function foo (arg: boolean): string
function foo (arg: string): string
function foo (arg1: number, arg2: number): number
function foo (...args: any[]): any {
  // do something
}

type AllParameters<T> = 
T extends { (...a: infer A1): any; (...a: infer A2): any; (...a: infer A3): any; (...a: infer A4): any; } ? A1 | A2 | A3 | A4 :
T extends { (...a: infer A1): any; (...a: infer A2): any; (...a: infer A3): any; } ? A1 | A2 | A3: 
T extends { (...a: infer A1): any; (...a: infer A2): any; } ? A1 | A2: 
T extends { (...a: infer A1): any } ? A1 :
never


type Param = AllParameters<typeof foo>
```
[Playground](https://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABMOdEAoCGAnA5gLkQCNUAbAU0zAEpCBnKbGMXAKFElgWVQxwMQMmLWoMbM2HaPCQo0WPAEZCYEAFsi5bABpE-AEwr1m7KNUat7cNO5yMAOkf86hKgE8A2gF1R7xAG9WREQAehDEABM0Ojg1cigACwlWAF9WVig3AAdyRABBUlIABRxMOKgtOgAeABUAPkQAXkRWGsRyAA8KsAi6AIcnQmZgLXzFXzA3AG4B+0whsBHsfP0J6dn5xGHRvIBmNZn0RzmFpfyAFgPEFMQAfjHEAB8Vp-zd17zzxHxW9q7yHp9fwbU47cauSaHY6bbbLPKrCHrI6DLaLHb7REzG73PKKD76D67Qi-TrdXr9ZEnVFnXFXSkwtFwhF6SHXO4PZ7w4ltUkA8nA+mguHglluNk4vE-MDkABulnSmRyiBK2DKTXyhRVZXilSqivIcGAPDgdVYQA)

I say most of the time because if you have a no parameter overload `unknown[]` creeps in there is at least one [issue](https://github.com/microsoft/TypeScript/issues/28867) that shows how this behaves strangely in some cases.

@RyanCavanaugh  Is this something that can be recommended? Or is it in the recursive type alias category, the compiler allows it but better not.

**Comment by Brooooooklyn** [comment]
@RyanCavanaugh the playground codes in my first comment works fine in `TypeScript@3.3`
