### ISSUE TITLE
Poor Intellisense/completion with rest parameters

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#3242]
Test case:

function foo(.<request completions>

Observe:
a list of global visible symbols are proposed. however the only possible completion would be another dot.

the language service shouldn't propose anything here. It doesn't propose anything for

function foo(a<code completions>

either

**Comment by dbaeumer** [comment]
See also: https://code.visualstudio.com/Issues/Detail/16548

**Comment by mhegazy** [comment]
i am not sure i see the problem here.. `.` is not a syntactically valid construct in this location. so what would the user be doing that we are blocking/interrupting by showing a completion list?

the case of `function foo(a` is indeed an identifier definition location, and blocking competition seems to be the correct thing to do.  for `.` we treat it like any other punctuation, wither correct or not, and we show completion list in the global scope.. this applies to something like:
`function foo(a b`

**Comment by danquirk** [comment]
He's saying if you are writing this code:

```ts
function foo(...a: number[]) {
}
```
then we shouldn't provide a completion list at ```function foo(.``` nor at ```function foo(..``` and instead only after ```function foo(...```.

**Comment by mhegazy** [comment]
i see. thanks for the clarification.

**Comment by CyrusNajmabadi** [comment]
This is also bad because <dot> is a completion character.  So if we happen to select something in the list after the first <dot>, then the second <dot> would complete it.

             -- Cyrus
