### ISSUE TITLE
assign null to a const infer to any

### ISSUE THREAD

**Issue by grepug** [microsoft/TypeScript#32439]
typescript version 3.5.3 but vscode indicates 3.5.2

![image](https://user-images.githubusercontent.com/7953740/61362163-4f541180-a8b4-11e9-99a7-fcb6486fe221.png)

![image](https://user-images.githubusercontent.com/7953740/61362262-77437500-a8b4-11e9-8b99-c3fd16862c30.png)

**Comment by grepug** [comment]
here is my tsconfig.json

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "declaration": true,
        "removeComments": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "target": "es6",
        "inlineSourceMap": true,
        "outDir": "./dist",
        "noImplicitAny": true
    },
    "exclude": ["node_modules", "dist"]
}

```

**Comment by nmain** [comment]
I wasn't able to find an issue for this, but I think it's by design.  It only happens when `strictNullChecks` is off.  Since `null` inhabits every type when `strictNullChecks` is off, the `null` type itself isn't that useful of an inference, and `unknown` didn't exist back then, nor is it that useful in a weakly, gradually typed codebase.  So what type would you give `var a = null` 7 years ago?  `any`.

You probably want to just turn `strictNullChecks` on.

**Comment by grepug** [comment]
@nmain it works! thank you for your reply.
I spent one or two hours to figure out this problem this afternoon, and googled a lot, didn't find any related posts or stackoverflows. And I was a little upset then.

And I think I should learn more details about TypeScript.

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
