### ISSUE TITLE
Unable to resolve module if folder structure is different when using project references

### ISSUE THREAD

**Issue by evenflow58** [microsoft/TypeScript#32446]
**TypeScript Version:**  3.6.0-dev.20190717
**Search Terms:** Project Reference module not found
**Code:** https://github.com/evenflow58/TestProjectReference/tree/master/test/packages

I am trying to use project references but the built typescript file paths are different so modules cannot be found. As you can see in the above repo the folder structure looks like this:
/packages
---/child
------/child.model
---/parent
------/nested-folder
---------/parent.service

ParentService references ChildModel. Unfortunately the built code puts ChildModel and ParentService at the same level so the module reference is broken.

**Expected behavior:** It would be nice it modules could still be referenced no matter what the original underlying structure is.

**Actual behavior:** Modules are not able to be referenced.

**Comment by sheetalkamat** [comment]
I don't think this is a bug. The build runs successfully. The folder structure is as per your tsconfig and module references in the source files are not renamed in the generated file. Project reference only mean that instead of mapping including source file of resolved module include d.ts so that the checking is faster. Your reference in parent is `../../child` so that's what you get.
