### ISSUE TITLE
tsserver: tsconfig.json not honored for files that already exist in workspace

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#3244]
TS workspace
create a file foo.ts

export function foo(): number {
	return 10;
}

Observe: the tsserver complains about missing module option
Add a tsconfig.json to it:

{
	"compilerOptions": {
		"sourceMap": true,
		"module": "commonjs"
	}
}

Switch back to foo.ts and observe that the error is still visible.

You need to restart tsserver so that the server recognizes the tsconfig.json file.

**Comment by mhegazy** [comment]
The issue is we are not adding file watchers on failed lookups, i.e. if you are looking at a file `a\b\c\d.ts` we will look for `a\b\c\tsconfig.json`, `a\b\tsconfig.json`, `a\tsconfig.json` and `tsconfig.json`. if non was found the file is deemed as a loose file. now to make this scenario work,. we need to add a directory watcher on each directory in the lookup chain, and ensure that if a tsconfig.json ever showed up the context is recomputed.

**Comment by mhegazy** [comment]
I have chatted with @jrieken and @egamma about this, and we need a new command to force the server to reload all projects. The host would fire this whenever a tsconfig file is added.

**Comment by mhegazy** [comment]
@hoanhtien is looking on adding either a directory watcher or a new command to allow for updating the project strucutre

**Comment by zhengbli** [comment]
#4023 added a new command called "ReloadProjects", which can be called explicitly to reload the projects for all opened files. Can you give it a try?
