### ISSUE TITLE
TypedPropertyDescriptor<T> does not follow the spec

### ISSUE THREAD

**Issue by hbarcelos** [microsoft/TypeScript#32545]
**TypeScript Version:**  3.5.3

**Search Terms:** TypedPropertyDescriptor

**Code**

As currently defined in `lib/lib.es5.d.ts`:
```ts
interface TypedPropertyDescriptor<T> {
    enumerable?: boolean;
    configurable?: boolean;
    writable?: boolean;
    value?: T;
    get?: () => T;
    set?: (value: T) => void;
}
```

So given the following code:

```ts
const desc: TypedPropertyDescriptor<string> = {
  value: 'a',  // <-- should not allow `value` if either `get` or `set` are defined
  set(v: string): void {},
  get(): string {
    return 'foobar'
  },
}

const obj = {}

Object.defineProperty(obj, 'a', desc)
```

**Expected behavior:**

As defined by the ECMAScript [spec](https://www.ecma-international.org/ecma-262/8.0/#sec-topropertydescriptor), section 6.2.5.5 item 15:

> 15 - If desc.[[Get]] is present or desc.[[Set]] is present, then
>      a - If desc.[[Value]] is present or desc.[[Writable]] is present, throw a TypeError exception.

So the following code snippet above should be illegal.

The best approach to do so is to make such object unrepresentable in TypeScript.

**Actual behavior:**

The code snippet above compiles without warnings, but we get the following JavaScript error when running the code:

```
Object.defineProperty(obj, 'a', desc)
       ^
TypeError: Invalid property descriptor. Cannot both specify accessors and a value or writable attribute, #<Object>
    at Function.defineProperty (<anonymous>)
    at Object.<anonymous> (/home/henrique/dev/udemy-typescript-complete-guide/section-15-decorators/src/test.ts:11:8)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Module.m._compile (/home/henrique/.config/yarn/global/node_modules/ts-node/src/index.ts:473:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Object.require.extensions.<computed> [as .ts] (/home/henrique/.config/yarn/global/node_modules/ts-node/src/index.ts:476:12)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
    at Object.<anonymous> (/home/henrique/.config/yarn/global/node_modules/ts-node/src/bin.ts:158:12)
```

**Playground Link:** https://www.typescriptlang.org/play/index.html?target=1#code/MYewdgzgLgBAJgUwsAXDAKgTwA4LgBQCcRdCpMARJYQgS2yhEIB5o6wBzAPhgF4YA3gCgYMAG4BDADYBXBGgDkEhQBoRMCAigAKMQEo0YkLTiCAvmtEct2gxqjsOg9aMJaZhMDAUAzECAAjCUIFdQshMyEhUEhYQIArPnMogHkA+IRgKAA6RB9aMAQiEgQyTG0ElW9lKsRkPSA

**Suggested Implementation:**

I was able to pull out some draft proposal for this:

```ts
interface TypedCommonDescriptor {
  enumerable?: boolean
  configurable?: boolean
}

interface TypedDataDescriptor<T> extends TypedCommonDescriptor {
  value?: T
  writable?: boolean
  set?: never
  get?: never
}

interface TypedAccessorDescriptor<T> extends TypedCommonDescriptor {
  value?: never
  writable?: never
  set?: (value?: T) => void
  get?: () => T | undefined
}

type TypedPropertyDescriptor<T = any> =
  | TypedDataDescriptor<T>
  | TypedAccessorDescriptor<T>
```

This needs more extensive tests, but I was able to obtain the expected behavior:

```ts
const desc: TypedPropertyDescriptor<string> = {
  value: 'foo',
  writable: false,
  // set(x?: string): void {}, // uncommenting any of the following lines result in an error
  // get(): string | undefined {
  //   return undefined
  // },
}
```

However, the generated error message is not very friendly:

```
error TS2322: Type '{ set(x?: string): void; get(): string; value: string; writable: false; }' is not assignable to type 'TypedPropertyDescriptor<string>'.
  Type '{ set(x?: string): void; get(): string; value: string; writable: false; }' is not assignable to type 'TypedDataDescriptor<string>'.
    Types of property 'set' are incompatible.
      Type '(x?: string) => void' is not assignable to type 'never'.```

**Comment by AnyhowStep** [comment]
> get?: () => T | undefined

Why would you allow your getter to return undefined?

**Comment by hbarcelos** [comment]
About your first 2 questions, a believe that the reason is to comply with how property descriptors work today.

I am quite new to TypeScript, so I might not know all the conventions regarding how it interacts with native JavaScript specs.

---

> If you're going to split it into a discriminated union,
>
>    value?: T
>
> Why would you let this be optional?

In JavaScript, `{}` is a valid descriptor. It is considered to be a DataDescriptor whose property value is `undefined`.

---

This is just a draft though. If this issue is accepted as a milestone, I can work in a proper PR and get some feedback from the community.

**Comment by AnyhowStep** [comment]
That just wouldn't play well with type safety

**Comment by hbarcelos** [comment]
I understand, so probably we should try a more restricted typing.

The original problem still persists though: invalid JavaScript is being accepted as valid. The exact solution should be up for discussion.

Thanks a lot for your feedback @AnyhowStep

**Comment by fatcerberus** [comment]
```ts
const desc: TypedPropertyDescriptor<string> = {
  value: 'a',  // <-- should not allow `value` if either `get` or `set` are defined
  set(v: string): void {},
  get(): string {
    return 'foobar'
  },
}
```

I might be wrong but I don't think that particular case is possible to solve without dependent types.  The alternative to that would be to split `TypedPropertyDescriptor` into two (or more) types: e.g. `ValuePropertyDescriptor` and `AccessorPropertyDescriptor` but that seems less than ideal.

**Comment by hbarcelos** [comment]
I've been thinking about this issue in the last couple of days and maybe we should split this problem in two parts.

When we are defining a new property, with `Object.defineProperty` or `Object.defineProperties`, both descriptor's `enumerable`, `configurable` and `writable` properties are optional.

However, when we get the descriptor with `Object.getOwnPropertyDescriptor` or `Object.getOwnPropertyDescriptors`, `configurable` and `enumerable` are always present (they are filled with their default values) and `writable` is present if `value` is present.

Example:

```javascript
const a = {}
Object.defineProperty(a, 'b', { value: 0 })
```

Then:
```javascript
console.log(Object.getOwnPropertyDescriptor(a, 'b'))

// {
//   value: 0,
//   writable: false,
//   enumerable: false,
//   configurable: false
// }
```
So maybe we could take a GraphQL-like approach and have different types for input and output:

```ts
// Inputs

interface TypedCommonDescriptorInput {
  enumerable?: boolean
  configurable?: boolean
}

interface TypedDataDescriptorInput<T> extends TypedCommonDescriptorInput {
  value: T
  writable?: boolean
  set?: never
  get?: never
}

interface BaseTypedAccessorDescriptorInput<T> extends TypedCommonDescriptorInput {
  value?: never
  writable?: never
}

interface TypedSetterDescriptorInput<T> extends BaseTypedAccessorDescriptorInput<T> {
  set: (value: T) => void
}

interface TypedGetterDescriptorInput<T> extends BaseTypedAccessorDescriptorInput<T> {
  get: () => T
}

type TypedFullAccessorDescriptorInput<T> = TypedSetterDescriptorInput<T> & TypedGetterDescriptorInput<T>

type TypedAccessorDescriptorInput<T> = TypedSetterDescriptorInput<T> | TypedGetterDescriptorInput<T> | TypedFullAccessorDescriptorInput<T>

type TypedPropertyDescriptorInput<T = any> =
  | TypedDataDescriptorInput<T>
  | TypedAccessorDescriptorInput<T>

// Outputs

interface TypedCommonDescriptor {
  enumerable: boolean
  configurable: boolean
}

interface TypedDataDescriptor<T> extends TypedCommonDescriptor {
  value: T
  writable: boolean
  set?: never
  get?: never
}

interface BaseTypedAccessorDescriptor<T> extends TypedCommonDescriptor {
  value?: never
  writable?: never
}

interface TypedSetterDescriptor<T> extends BaseTypedAccessorDescriptor<T> {
  set: (value: T) => void
}

interface TypedGetterDescriptor<T> extends BaseTypedAccessorDescriptor<T> {
  get: () => T
}

type TypedFullAccessorDescriptor<T> = TypedSetterDescriptor<T> & TypedGetterDescriptor<T>

type TypedAccessorDescriptor<T> = TypedSetterDescriptor<T> | TypedGetterDescriptor<T> | TypedFullAccessorDescriptor<T>


type TypedPropertyDescriptor<T = any> =
  | TypedDataDescriptor<T>
  | TypedAccessorDescriptor<T>
```

I know this is a mouthful, but is a way I found to make invalid statements unrepresentable and still preserve type safety.

Any thoughts?

**Comment by houghtonap** [comment]
I just ran into a similar issues with Typescript v3.9.3 which has the same implications about enumerable, configurable, writable, value, get/set mentioned by @hbarcelos. The issues @hbarcelos  mentions also apply to the non-typed interface PropertyDescriptor. That interface should also be broken out into separate interfaces as @hbarcelos suggests, later in the thread, to conform with the specification.

**Comment by rbuckton** [comment]
Changing `PropertyDescriptor` is fairly complicated. Even with the definitions provided above, You could specify an incorrect descriptor:

```ts
Object.defineProperty({}, "a", { value: true, get: undefined });
// TS: ok, `get` is typed as `get?: never`, whose type is `undefined | never`, or rather, `undefined`.
// JS: TypeError: Invalid property descriptor. Cannot both specify accessors and a value or writable attribute
```

However, if you limit the types to versions that don't have `get?: never; set?: never;`, etc., then they have overlapping domains (because you haven't restricted the values of `get/set` or `value`) and its harder to test for the difference (i.e., you have to use `if ("get" in descriptor) { ... }` as a type guard instead of `if (descriptor.get) { ... }`.

It is currently impossible to define a type that is both "correct" and "easy to reason over" currently, unless something like the negated types PR is implemented to give us more control over the domain of types allowed. I'm not certain complicating `PropertyDescriptor` or `TypedPropertyDescriptor` is reasonable until we have a more expressive way to define the types.

That said, `TypedPropertyDescriptor` was originally added *only* for the purpose of type checking decorators (to ensure that the a decorator didn't change the type of a method, accessor, or field), although its usage broadened slightly when `getOwnPropertyDescriptors` was added in ES2017.

**Comment by rbuckton** [comment]
@houghtonap: Unfortunately, I don't think `PropertyDescriptor` can be fixed in the way you describe. Consider the following:

```ts
interface GenericPropertyDescriptor { // term comes from GenericDescriptor in ECMA-262
  configurable?: boolean;
  enumerable?: boolean;
}
interface DataPropertyDescriptor extends GenericPropertyDescriptor {
  value?: any;
  writable?: boolean;

  // ensure domain is disjoint w.r.t AccessorPropertyDescriptor
  get?: never;
  set?: never;
}
interface AccessorPropertyDescriptor extends GenericPropertyDescriptor {
  get?(): any;
  set?(v: any): void;

  // ensure domain is disjoint w.r.t DataPropertyDescriptor
  value?: never;
  writable?: never;
}
type PropertyDescriptor = DataPropertyDescriptor | AccessorPropertyDescriptor;
```

There are a number of issues with this:
- Properties like `set?: never` still allow `undefined`.
- The `value?: any;` property in `DataPropertyDescriptor` is not considered a discriminant property because its type is `any`.

You can see examples of these problems here: [Playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAbwL4G4CwAoTBLAdjYKAMwEMBjYOAcWF0OzIAUoIxCYBPAEWAGcyo2MDGiJMcCXDIRcRbAHMArlBIAjADbAA-AC44qiBE0lc6DJLi1FAW0JrNu-YeOnMSTDnyFSFOFxIwJMys7Nx8AkIiUJYgBLgAJrzUtPRMLGywYfyCwqII4pIAbiTqitp6JhxmFgDugoEa5U5GwCZmBRIA9J2WuLzKlPEQ1iR4cDXYMAAWcACCZBS8vNDBGZw82ZGi2EnxOwBWEHgwHXDywDCOdIWE1ZK8F1fAN1Bm7lgYx97klPOLy1BVqENhFctFQHFEsk6II0iFMiCclExOZJOdLgAKACUFVwVVOD0xhVxHBxcEKR3i7VRXR6tH6UEGw1GuHGkxm-kCQIR4SR212ByO+FOxVKTWutzg3TgQz4uAA5PAatAANb6YBkEiKB5wAAGorKjkqurgY05QXSwN5W2iOzguAg8BIMp2EWseBM8DAlsyADpTnVJvZxc9bm4PBhOGw4Nz1tawXAALynAA+fgCFvhcc2YNTcwWfABsayoKi1PiGvUJEZcCIilwZBg2BkMuAcjoxYAPFwYpCksXETaAHwYiB6CCqfYamAAGjgKuAHD0vBgglw8jn8T0XDJFOwVMwFbIVZrdYbTZb6IA8jVcAP41FR+PJ9O5wul3AV2v5GSAErAABHRRsEZeJuwze8cyiIc4DTf8gJA4AwL+QsVh9bNS2gGC03rCt2yQ8s2zwYBiwxZA5wAIhICi52QLEUClHoIDVQBeDcAKD3DyIjt0I4MikEo6jaPGepgz0VcyjnA1gD0ABGOAkHoxi4GYuB2M4-DSPIuAqJoxAzgubFECQeTFOlFS1IwPDiM0-jtMEvTCUM5ATIYszWI4yyuJIni+IE3SEGEoNGjEqAJP0mAnOMhTXLpKAWGiCyrO4rNeK0nShKk2S53RSKXKUwh4tUjyku8lLfLs-zyRKMo9Fwrz4jnRysSMvK3LnVRFHgUL8GwWxLDi0QWMAZD31Osny0vsgLMrgGTsouWqEnq1qmJVdrOrgbqmz6grBpGj5pD6eAK34JNwpvO8eMHMFyp0rEAEIzGlAA5K8ABUAFE9FAEhrDATQkjGM9G2bPo4BEXoGUoA7VyMWt1AgGoZQgOVFTgEgiCIacNr4RR1BODAgYvVkiBkpzTmwIg4AxY6yF9QMGk0Zr8hpCxW34X1CRi+1QwSjyLHed5CZB2sACYyZZimqZp30pKZpTSGwdQknBvZNndXAAmAU4LGlzmlIxYk0bxZrExgvd4lUvb+fDAn62BlsiAAZnFixJYxKNgAgSndYuJNE0TbShZkCime1yRpfp4MuYMFoTEtsOJGlqSucqeOWYFzAgA).

I don't believe this is solvable due to current design limitations. Perhaps we can revisit this in the future as we continue to invest in experiments like negated types.
