### ISSUE TITLE
Rest parameter code change suggestion

### ISSUE THREAD

**Issue by Back-io** [Microsoft/TypeScript#3259]
I realize I might get sent to nit-pickers jail for this ... but:

Right now the following code:

```
function f(...a: any[]) { }
```
Gets outputted like:
```
function f() {
    var a = [];
    for (var _i = 0; _i < arguments.length; _i++) {
        a[_i - 0] = arguments[_i];
    }
}
```
But does it not make more sense to output it like:
```
function f() {
    var a = [];
    for (var _i = -1; ++_i < arguments.length;) {
        a[_i - 0] = arguments[_i];
    }
}
```
Which would cut in half the number of times you need to step over while debugging to get into the function?

Or am I missing something?

**Comment by DanielRosenwasser** [comment]
I would prefer to keep the output look more canonical; this means start from 0, and use the post-iteration statement.

**Comment by danquirk** [comment]
And as far as the user experience goes, sourcemaps should make the debugging experience even fewer steps than this change.

**Comment by Back-io** [comment]
To the best of my knowledge, source maps don't have anything to do with the stepping behavior (at least in Chrome).

**Comment by DanielRosenwasser** [comment]
Sourcemaps allow you to forego debugging your generated JavaScript, instead letting you debug the source code that you wrote more directly. With sourcemaps, you shouldn't even step into the rest argument copy code.

**Comment by Back-io** [comment]
This isn't the case in Chrome. You still need to step through the construction of all the rest args, source maps or not:

https://s3.amazonaws.com/files.back.io/ScreenFlow.mp4

If you notice, I step 14 times in that video instead of what would be 7.

**Comment by danquirk** [comment]
Oh, yeah, in an ideal world Chrome would fix that since this only gets worse for things like async/await in the future. While I get where you're coming from here the debugging UX is still pretty horrific having to step 7 times for every use of rest args. I'd be just setting breakpoints temporarily to be faster. If this was getting us to a point where the UX was actually great I could see changing to less idiomatic emit and causing lots of surprising diffs but the real fix here is to get the major debug engines to understand how to step through sourcemaps correctly for cases like this.

**Comment by Back-io** [comment]
The point is that I need to step 21+1 times instead of what could be 14+1 if the loop was a 2-statement ``for`` instead of a 3-statement ``for``.

It's not a major issue or anything, it just seems to me like the obvious way of doing this. I always write ``for`` loops with 2 statements instead of 3. I never understood why people insist on expanding it out to 3 statements. It's more characters to type and one more thing to step over.

**Comment by danquirk** [comment]
I get that, my point is stepping 14+1 times is still so awful that I would be using actual breakpoints to just skip the whole process and move onto the next line (if the debugger you're using doesn't just have a 'run to cursor' type feature). Your proposal is a mitigation but still leaves people with pretty crappy UX and comes with the cost of being less like code most people actually write (maybe not like what you write though) as well as causing some surprising diffs when everyone upgrades tsc to a new version. We're going to absolutely need the sourcemap stepping behavior fixed when async/await is available at which point this experience would also be fully fixed instead of just getting slightly less crappy :)

**Comment by Back-io** [comment]
Fair enough :)

**Comment by danquirk** [comment]
Thanks for the feedback though, keep it coming, no matter how nit picky it may seem
