### ISSUE TITLE
path mappings from tsconfig / ( auto ) import does not work

### ISSUE THREAD

**Issue by MikeMitterer** [microsoft/TypeScript#32605]
**TypeScript Version:**  Version 3.6.0-dev.20190727

**Search Terms:**
path tsconfig typescript mess

**Code**
```json
        "baseUrl": "./src",
        "paths": {
            "@mmit/mobicore/*": [ "main/*" ]
        },
```
```bash
# File location
mobicore/src/main/model/device/Device.ts

# File that should import Device
mobicore/src/main/services/device/DeviceServiceLocal.ts
```
```ts
// Expected
import { Device } from '@mmit/mobicore/model/device/Device';

// Poor reality
import { Device } from '../../model/device/Device';
```

**Expected behavior:**
Should import with `@mmit/mobicore` prefixed

**Actual behavior:**
`import { Device } from '../../model/device/Device';`

JetBrains is not able to do something against this bug because they are using just your TS-Server these days and MS seems to be to big to care about these UX problems. As a developer you are lost somewhere between those companies. 
This whole path-mappings-thing is just a pain in the ass... I really like TS but the tools around the language are not very mature in my opinion. 

![Bildschirmfoto 2019-07-29 um 13 07 57](https://user-images.githubusercontent.com/116654/62046366-0717e600-b208-11e9-8651-3f1e12a2d13f.png)

**Comment by andrewbranch** [comment]
@MikeMitterer does WebStorm expose this option for TS Server?

<img width="347" alt="image" src="https://user-images.githubusercontent.com/3277153/68409441-f1d22200-013b-11ea-9f31-9514a3a88434.png">

Mine is set to “auto” in VS Code, which is also the default on the server. The only way I could reproduce this in any version of TypeScript was to change it to “relative,” which would be expected behavior for that setting.

That said, the description of “auto” should be noted—it only uses the non-relative path if it has equal or fewer segments than the relative. In your example, each specifier has five segments, and for me at least, auto chooses the non-relative path-mapped path. But, if I move these two files closer together (e.g., move `DeviceServiceLocal.ts` up one directory into `src/main/services`), I get the relative path, because `../model/device/Device` has fewer segments than `@mmit/mobicore/model/device/Device`. If you wanted to always get the `@mmit` path, you should set your setting to `non-relative`. (I personally find this setting obnoxious, because in a deeply nested folder, importing a file right next door to the one you’re in will generate a super long path from the root instead of `./otherFile`.)

Please let me know what you find out—I’m sorry that you got the impression in the past that Microsoft doesn’t care about UX, but I take it very seriously in the small area I can affect.

**Comment by andrewbranch** [comment]
@MikeMitterer since I can’t reproduce this and I haven't heard from you, I’m going to assume it’s working correctly. Feel free to reopen if you have more information.
