### ISSUE TITLE
Type inference fails with tuples, generics and intersection types, unless first assigned to a variable

### ISSUE THREAD

**Issue by martin-schibsted** [microsoft/TypeScript#32622]
**TypeScript Version:**  Version 3.6.0-dev.20190730

**Search Terms:** tuples, generics, intersection types, type checking

**Code**

The commented line does not work whereas the line below it does, even though the only difference is that the result is assigned to a variable before being returned. TypeScript fails to infer that `[x in P2]` is `'b'`, so the return value does not satisfy the requirements of `Extension`.

If `id: string` is removed from `Entity`, or if the type of `id` is changed, the issue disappears. If `T` is replaced directly with `Entity` (i.e. made non-generic), the issue also disappears.

```ts
interface Entity {
    id: string;
}

interface Extension {
    a: {
        b: number
    }
}

const addExtension = <T, P1 extends string, P2 extends string>(
    entity: T,
    path: [P1, P2]
) => {
    return (undefined as unknown) as T & { 
            [x in P1]: {
                [x in P2]: number;
            };
        };
};

function f(entity: Entity): Entity & Extension {
    // The following line does not work:
    // return addExtension(entity, ['a', 'b']);

    // This one does, but it is equivalent:
    const tmp = addExtension(entity, ['a', 'b']); return tmp;
}
```

**Expected behavior:**

The commented line should work.

**Actual behavior:**

The commented line does not work.

**Playground Link:** 

[Link](https://www.typescriptlang.org/play/index.html#code/JYOwLgpgTgZghgYwgAgKLmGAnsg3gKGSOWABMAuZAZzClAHMBufAX331ElkRVQA9IIKsAD2IPIWJxKBYnOQAjSiACuAWwXRJRNm3wIxNZHFKl+g4WOQBeZAB4AKgBpkABQCMyCAIghSValoGF1cAJi8fPwCaOhB6AD4ACm0vDGxKZxSABzgwAAtKAG0PENCAXXwASht4iTkoCDAVKHFElT8IGFAIUmMA9oBrEBEAdxBquACHZAAyPGQU+WJCvhJxDzKZRaX5FbW3cuV1TShmHfkWM53L1mZ8GHaEMFFxGETfZ-S0NKxKynRPjg5uZfJZxLJiAB6SHIBx5FAwEQAGyRowYyCR3WQpBEEACwzAyBGIigA3IKWhyAaTRaxlMIKEL3ePxchQA5HA2S42Qo2WVKnc5JS4cAAmIUDi8S4FCpCZgSAEIABHFTAABucCRH3JcgMQkJYDUWRsdLMkTBzMBrI5XOQPL5AqpjWa4kNWWYLCAA)

**Related Issues:** 

Not that I know of.

**Comment by ahejlsberg** [comment]
This one is a bit involved. It's related to improvements we made in 3.5 for return type inference, but we get tripped up in a convoluted way by this example. Roughly, when inferring from the return type, we end up making an inference for `P2` equivalent to `keyof string | "b"`, but since that type isn't assignable to the constraint of `P2` (`string`) we end up substituting the constraint. That in turn means that the `'b'` in the tuple argument isn't given a literal type, and things then go awry.

The core issue really is that `P2` is constrained to a type that doesn't include all possible property names. Indeed, if you change the declarations of `P1` and `P2` to `P1 extends keyof any` and `P2 extends keyof any` then it all works. That's what I would suggest doing.
