### ISSUE TITLE
Does not infer discriminated unions with !==

### ISSUE THREAD

**Issue by ChuckJonas** [microsoft/TypeScript#32748]
**TypeScript Version:**  v3.5.1

**Search Terms:**
discriminated unions, !==
**Code**

```ts

export interface K9 {
  variant: 'DOG' | 'WOLF';
  bark: ()=>void;
}

export interface Feline {
  variant: 'CAT' | 'LION';
  meow: ()=>void;
}

export type CatOrDog = K9 | Feline;

let instance = {} as any as (K9 | Feline)

if (instance.variant === 'DOG' || instance.variant === 'WOLF') {
    instance.bark(); //works
}

if (instance.variant !== 'DOG' && instance.variant !== 'WOLF') {
    let x = instance.variant; //correct type inferred
    instance.meow() //should work but doesn't
}

```

**Expected behavior:**

The first condition check should be able to infer that we are dealing with a Feline. 

**Actual behavior:**
It is unable to discriminate. 

**Playground Link:** [playground link](https://www.typescriptlang.org/play/#code/FAUwHgDg9gTgLgAgJYDs4hgMwIYGMQIDSAnAgN7AIIBu2MS2aAXAgOQAiA8gOKsIA+bAOqcAMgDFWAbkoIARnQDWLABQBKALwA+alCQATGQF9goSLESp0WPAXEgANqgIUqteozgtWAYQCCACp8gqyiAJKcAHLSsgC2IFAA7qqaOnqGwCZm0PAIcACeEAQ+2HCcMOxQAOYIGkSkgvZOKCAywA4gligAznCM+LXkRgjY3SMo+SNjKiQCCE3OaqZImAgqqL39IAB07gxoCACEGnUcPHwAZBfIPX0o+Lt0+4jHpyISrGrkslQdiGCDDZ3B57TxSBAAeghuFgMBAuDgPxum3uO3iSUhEO6AAsoABXBz6BCJWCKTLLVbrW5bR4eA4nU5cXgCQRAmmg+knYRiSRfVxUZHAnYKGCKYzAIA)

**Related Issues:** https://github.com/microsoft/TypeScript/issues/27541

**Comment by jack-williams** [comment]
What's the difference between this and #30557?

**Comment by RyanCavanaugh** [comment]
@jack-williams here, the narrowed identifier was declared as a union

**Comment by ahejlsberg** [comment]
It works if you change the declaration of `K9` to

```ts
export interface Dog {
  variant: 'DOG';
  bark: ()=>void;
}

export interface Wolf {
  variant: 'WOLF';
  bark: ()=>void;
}

export type K9 = Dog | Wolf;
```

The reason it doesn't work as originally written is that when `instance.variant !== 'DOG'` is applied to the original declaration of `K9`, no narrowing is performed (because `variant` could still be `'WOLF'`). Likewise, `instance.variant !== 'WOLF'` doesn't by itself narrow `instance`. However, when `K9` is declared as a union type we can individually narrow.

So, it's working as intended, but you could argue it is a design limitation.
