### ISSUE TITLE
is this a Generic bug?

### ISSUE THREAD

**Issue by Paul-Lo** [Microsoft/TypeScript#3275]
consider the following class.
```
class GenericPractice<T>{
    private entity: T;
    constructor(entity: T) {
        this.entity = entity;
    }

    public add(item: T): string {
        return item.toString();
    }

}
class CouponInfo {
    public toString(): string {
        return "couponInfo";
    }
}
class Snake{
}

 var genericPractice = new GenericPractice<CouponInfo>(new CouponInfo());
genericPractice.add(new Snake("Sammy the Python")));

```

theoretically, the above last line:
```
genericPractice.add(new Snake("Sammy the Python")));
```
should have compile time error since the generic of class GenericPractice should only allow CouponInfo in method add, not Snake.

However, the compile still passes which violates the fundamental concept of generic.
is this a bug?

**Comment by DanielRosenwasser** [comment]
Note: I assume that you didn't mean to supply an argument to the `Snake` constructor.

This has to do with TypeScript having a predominantly structural type system.

```TypeScript
class CouponInfo {
    public toString(): string {
        return "couponInfo";
    }
}

class Snake {
}

// No problem with either of these.
var x: CouponInfo = new Snake();
var y: Snake = new CouponInfo();
```

Since instances of `Snake` have the same [apparent members](https://github.com/Microsoft/TypeScript/blob/7ee698c450e8317651ecb102534b0601da5ecb9f/doc/spec.md#3.10.1) as those of `CouponInfo`, `Snake`s are assignable to `CouponInfo`s. Thus when `add` expects as `CouponInfo`, you can give it a `Snake`.

If you want to avoid this, you can add a private "tag" member in each class. Privates are not compared in a structural manner, regardless of their name and type.

```TypeScript
class CouponInfo {
	public couponTag: {};
	
    public toString(): string {
        return "couponInfo";
    }
}
class Snake {
	private snakeTag: {};
}

var genericPractice = new GenericPractice(new CouponInfo());

// Now all of these cause errors.
genericPractice.add(new Snake());
var x: CouponInfo = new Snake();
var y: Snake = new CouponInfo();
```

Hope that answers your question!

**Comment by Paul-Lo** [comment]
Thanks for the informative and comprehensive answer!
