### ISSUE TITLE
`tsc --watch` recreates deleted source files

### ISSUE THREAD

**Issue by alexzorin** [Microsoft/TypeScript#3277]
In current stable and also master (de88ede4feeabab91d032359406a19166ed5bbb2), `tsc --watch` will keep recreating `file.js` during recompilation even when the original `file.ts` source file is removed. Only workaround is to restart `tsc --watch` to make it forget about `file.ts`.

For example,

```
$ ls incorrect_recreation/
test2.ts  test.ts  tsconfig.json
$ cat tsconfig.json
<empty>
```
```
$ node bin/tsc.js --watch -p incorrect_recreation/
message TS6042: Compilation complete. Watching for file changes.
```
In another terminal:
```
$ ls
test2.js  test2.ts  test.js  test.ts  tsconfig.json # as expected
$ rm test.ts test.js 
$ ls
test2.js  test2.ts  tsconfig.json # so, no trace of test.js or test.ts now
$ touch test2.ts # force a recompile and wait
$ ls
test2.js  test2.ts  test.js  tsconfig.json # test.js should not have been recreated
```

**Comment by danquirk** [comment]
I assume tsconfig in this case isn't explicitly listing any files?

**Comment by mhegazy** [comment]
This is not specific to tsconfig, though tsconfig is required for to a clear manifestation. the issue is that our watch notification catches only the edit but not the delete notification, so we do not really know that the file is deleted.

**Comment by mhegazy** [comment]
looking at the API i am not sure if there is an easy way we can detect the deleted event without having to hit the disk on every change request, or checking file stats all the time.. we will need to look more into this.

**Comment by alexzorin** [comment]
Is there a particular reason that watches are created on the source file themselves and not the directory in which they are contained? This way, info is provided on file edit (albeit not a full `stat()`), as well as creation/move/deletion within the directory. I believe this is how tools like `tail` work.

There is second issue in tsc that it does not pick up new `*.ts` files, which might also be solved this way.

Speaking only generally, I am not sure whether node provides the adequate APIs/cross-platform-ness to achieve this.

**Comment by mhegazy** [comment]
The problem is node has two interfaces, watchFile, this is cross-platform, but only does files, and watch, not cross-platform and does directories. We have looked into this with the tsconfig file and did not find a good way that 1. works on all platforms, 2. does not have a dependency on a third party node package that can not be used in other engines and 3. has good performance. the conclusion was adding and removing files is not common enough to warrant the complexity. this assumption may not be true now as more ppl run into this issue.

**Comment by DickvdBrink** [comment]
Maybe we could check the stat.size property and if It is `0` it means the file is removed/deleted or someone just emptied the file (but that is not that common I think)

So that would not increase the disk hits that much (but doesn't solve newly created files though).
It is a bit of suboptimal solution I guess.. :]

**Comment by Arnavion** [comment]
@mhegazy fs.watchFile already allows you to know if the watched file is deleted. The "current" Stats object has modified time set to the zero Date, so `mtime.getTime() === 0` can be used to detect deletion. (It's because libuv calls the callback with a default zero-initialized uv_stat_t reference, although this is not documented in libuv's nor node's docs as far as I can see).

**Comment by mhegazy** [comment]
Nice. Thanks @Arnavion, that would do the trick. We would accept a PR implementing @Arnavion's proposal.

**Comment by mhegazy** [comment]
Thanks @ShyykoSerhiy
