### ISSUE TITLE
Error when use spread arguments twice

### ISSUE THREAD

**Issue by KSXGitHub** [microsoft/TypeScript#32835]
**TypeScript Version:** 3.5.1

**Search Terms:**

**Code**

```ts
declare function fn (a: string, b: string, ...c: string[]): void
declare const foo: [string, string, ...string[]]
declare const bar: string[]
fn(...foo) // ok
fn(...foo, ...bar) // error
fn(...foo, ...foo) // error
fn(...bar, ...foo) // error
```

**Expected behavior:**

No errors

**Actual behavior:**

```
Expected at least 2 arguments, but got 1 or more
```

**Playground Link:** [link](https://www.typescriptlang.org/play/?noImplicitThis=false#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVPwAooAueAZwxi1QHMAaeAIzMursYDpuxWqbaAbQC6ASjIA3HFmAAoUJFgIweSkhw4ygtgMY6O8bp31Dhw+eGhx4K1Gqaw+7U7MSpCRxBtHwA9L-gcAGtXd08NLm4HGB9-eBAYGBwYUI9uLxxIzgzYgISklLc0zmisnL88xOSgA)

**Related Issues:**

**Comment by sandersn** [comment]
@elibarzilay I think your tuple PR recently fixed this bug. Can you confirm?

**Comment by elibarzilay** [comment]
#33069 is fixing one aspect of this issue, but there is an additional issue with typechecking the arguments.  An example of this:

    declare function s2n_ (a: string, b: string, ...c: number[]): void
    declare const s2: [string, string]
    declare const n_: number[]
    s2n_(...s2, ...n_);

fails with

    error TS2345: Argument of type 'number' is not assignable to parameter of type 'string'.

which is bogus due to code that does not handle spreaded tuples properly.  (A fix for that is probably in the loop which is around the middle of `getSignatureApplicabilityError`.)
