### ISSUE TITLE
unused type parameter message is wrong for jsdoc `@template`

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#32843]
```js
/**
 * @template {string} K
 * @template V
 */
class MM {
    constructor() {
        /** @type {V} */
        this.t;
    }
}
```

**Expected behavior:**
Message: "K is declared but its value is never read"

**Actual behavior:**
Message: "All type parameters are unused."

Note that the message is the same if `K` comes second. The code in checkUnusedTypeParameters looks suspicious where it tries to handle template tags, so it's probably just wrong.

**Comment by rbrishabh** [comment]
Hey! I would like to take this up!

**Comment by princeseth** [comment]
Hi @sandersn — I've tried to debug this and found that `isReferenced` property of Symbol object remains undefined for every `TypeParameter`. Due to this `isTypeParameterUnused` function always return true for each parameters. 
Could you please give some reference where I can initialize `isReferenced` property of SymbolObject.?
Thanks

**Comment by sandersn** [comment]
`isReferenced` is basically only modified in `resolveName[Helper]`. When the compiler checks `/** @type {V} */`, it should call `resolveName` on `V`, which should then mark it as used.

I'd put a breakpoint in `resolveTypeReferenceName` and see why resolving `V` doesn't end up setting isReferenced.
