### ISSUE TITLE
Use related error spans for "implement abstract class" errors

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#32848]
From https://github.com/microsoft/vscode/issues/78048

**TypeScript Version:**  3.6.0-dev.20190810

**Search Terms:**
- abstract class
- related error spans
- diagnostics

**Problem**
For the TypeScript:

```ts
abstract class A {
	abstract b(): void;
	abstract c(): void;
}

class B extends A { }
```

The typescript server currently generates two errors on `B`, one for `b` not being implemented and one for `c` not being implemented.

Having two errors causes VS Code to show a `fix all...` quick fix even though the single `implement abstract class` quick fix will resolve both errors. See https://github.com/microsoft/vscode/issues/78048

**Proposal**
Instead of generating two errors in this case, generate a single, generic diagnostic that states something like: `B does not implement all abstract members of A` and on that diagnostic return related spans that state specifically which members are not implemented (`b` and `c`).
 
**Related Issues:** 
- #25033

/cc @DanielRosenwasser

**Comment by crc442** [comment]
@DanielRosenwasser can I take a crack at it?

**Comment by DanielRosenwasser** [comment]
Go for it! Start at the checker to consolidate the error messages, and then work within `src/services/codefixes`.

**Comment by TroyTae** [comment]
Actually I tried to solve this issue in the last weekend.

I create an array and push diagnostics.
Instead of firing this code:
```
error(derivedClassDecl, Diagnostics.Non_abstract_class_0_does_not_implement_inherited_abstract_member_1_from_class_2,
                                typeToString(type), symbolToString(baseProperty), typeToString(baseType));
```
After all of loop, I checked all of diagnostics.

I think this code is terrible 😱 
Is there some code that combine two or more errors?
I would like to reference that code.

**Comment by TroyTae** [comment]
@DanielRosenwasser 
Actually I tried to solve this issue in the last weekend.

I create an array and push diagnostics.
Instead of firing this code:
```
error(derivedClassDecl, Diagnostics.Non_abstract_class_0_does_not_implement_inherited_abstract_member_1_from_class_2,
                                typeToString(type), symbolToString(baseProperty), typeToString(baseType));
```
After all of loop, I checked all of diagnostics.

I think my code is terrible 😱 
Is there some code that combine two or more errors?
I would like to reference that code.

@crc442 
If you already finish this work, I want to read and study your code!

**Comment by karthikkp** [comment]
@crc442 Still working on this?

**Comment by FlyingPumba** [comment]
Hi everyone, I just submitted a PR for this issue.

**Comment by DanielRosenwasser** [comment]
Thanks @FlyingPumba
