### ISSUE TITLE
Include additional metadata about which error codes a fix-all quick fix can fix

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#32901]
**TypeScript Version:**  3.6.0-dev.20190810

**Search Terms:**
- quick fix
- code action
- fix all
- tsserver

**Repo**
For the example ts:

```ts
async function init() {
	const result = fetch('url');
	if (result.status === 200) {
		foo((await result).text());
	}
}

function foo(status: string) { }
```

There are two errors related to missing awaits. One has the error code of 2339, while the second has the error code of 2345. However both have a fix all action that will fix both errors. 

**Problem**
VS Code tries to be smart and will only show a fix all action in the UI if there are multiple diagnostics with the same error code in the file. However because these two diagnostics have different error codes, we end up not showing the fix all action even though it really will fix both error

**Proposal:**
I think we should either:

* Only have the TS server return a `fix all` if it knows there are multiple errors that can be fixed in a given file

* Have the existing fix all response (which is returned even if there is just a single error in a file)  include additional metadata about which error code it can fix. Something like:

```
    {
        "fixName": "addMissingAwait",
        "description": "Add 'await'",
        "changes": [
           ...
        ],
        "fixId": "addMissingAwait",
        "fixAllDescription": "Fix all expressions possibly missing 'await'",
        "fixAllCodes": [2345, 2339]
    }
```

**Comment by mjbvz** [comment]
Yes, that would be ideal. That way all editors that use tsserver would have consistent behavior. @amcasey How does VS determine if a fix all action should be shown or not?

**Comment by amcasey** [comment]
I haven't stepped through that code in a while, but I believe we call `getCombinedCodeFix-full` if there's a `fixId` on the code action and show the UI if it returns non-null (null may indicate an error - I didn't confirm).

**Comment by andrewbranch** [comment]
Ok, cool. I think this is a good idea, but it will require us to update every codefix. I’m not certain yet whether that’s feasible for 3.7—my guess is that many error/suggestion codes are _always_ fixable, so simply replicating the logic that counts instances of diagnostic codes might take care of a good chunk of them, but I’ll have to investigate.

**Comment by andrewbranch** [comment]
I didn’t have time for this before 3.7-beta, and I think it’s probably a bit risky to do post-beta. We haven’t done planning for 3.8 yet but I will tentatively bump the milestone, and bring this up when we start planning.

**Comment by andrewbranch** [comment]
@mjbvz is it safe to assume that it’s better to have a false positive that you should show a fix-all than a false negative that you shouldn’t (like the add missing await example in the issue description)?

I’ve been thinking about this more, and for some code fixes, it can be quite difficult to tell what errors will be affected. Example 1:

```ts
for (x of arr) {
  x;
  doSomething(x);
  y;
  z;
}
```

Every single-letter variable in this example has a ts2304 “Cannot find name” diagnostic on it, but only the first has an available code fix. So currently, when we compute the fix on the first, we always return a fix id, and because there are more than ts2304 in the file, VS Code shows the fix-all option, which is a false positive. If we were to try to do a better job on our end, we’d have to look at every unresolved identifier in this file before returning the response for `x`, which seems bad for performance. (This particular code fix is cheap, but generally speaking this doesn’t seem practical.)

Example 2:

```ts
const p = Promise.resolve("");
p.toLowerCase();
p.toUpperCase();
```

Both method calls on `p` return a code fix to add `await` in front of `Promise.resolve()`, which will fix both method calls, but neither is necessarily aware that more than one error will be fixed. So here, even if we did the extra work to find more than one fixable missing-await error, we’d successfully find two, and incorrectly tell VS Code that multiple actions are available.

Anyway, I think we can do something to eliminate the existing false negatives, but I think it would be too expensive to eliminate false positives.

**Comment by mjbvz** [comment]
Yes, false positive are fine (within reason) so long as the original error span the fix is triggered on is fixed. It's also fine to say that some quick fixes do not support fix all as that may result in unexpected code changes
