### ISSUE TITLE
Conditionalize `__esModule` emit?

### ISSUE THREAD

**Issue by RyanCavanaugh** [microsoft/TypeScript#32934]
Numerous issues pointed to from https://github.com/microsoft/TypeScript/pull/32083 have people running in environments where it's not safe to emit the `__esModule` property for whatever reason.

Instead of adding a flag, we could just emit `(typeof exports !== 'undefined') && Object.defineProperty(...`

Thoughts?

**Comment by pocesar** [comment]
one use case for this is, if you use Typescript to generate mongodb atlas stitch code, it won't deploy, unless you manually remove the `Object.defineProperty(exports, "__esModule", { value: true });` at the top.
the reason is simple, it expects always one `export = () => {}` per file at the top, additional functions maybe come at the bottom

**Comment by kirchet** [comment]
Any updates? Almost one year since this issue was created.

**Comment by andrascii** [comment]
Hi, I also ran into the same problem...

**Comment by zardoy** [comment]
Ping @RyanCavanaugh we still need the solution

**Comment by jonathan-nielsen** [comment]
Ignoring issues for over 3 years isn't the way to go. I'm still having this issue and it's almost 2023.

**Comment by RyanCavanaugh** [comment]
Good call. Given the number of people running into this, I don't think a change to the emit is warranted. Alternate transpilers are available if you need support for a niche runtime; we're trying to scale back the emit configuration matrix to mainline scenarios only.
