### ISSUE TITLE
Any method iterates the interface type and gets the attribute name?

### ISSUE THREAD

**Issue by alanhg** [microsoft/TypeScript#32960]
I want to cast subType object to parentType.

```typescript
interface IStudent {
  name: string;
}

interface ISeniorStudent extends IStudent {
  height: number;
}

```

```typescript
 const seniorStudent: ISeniorStudent = { name: 'alan', height: 177 };
 console.log('Class: , Function: , Line 18 (): ', JSON.stringify(seniorStudent)); 
//  {"name":"alan","height":177}
    const stu = { ...seniorStudent } as IStudent;
console.log('Class: , Function: , Line 21 (): ', JSON.stringify(limitedAssign(seniorStudent))); 
// {"name":"alan"}
```

but now , cast failed.it prints {"name":"alan","height":177}.

I think maybe need create a function ,reassign according type property.

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
