### ISSUE TITLE
Do not suggest to convert function to ES2015 class when jsconfig.target is ES5

### ISSUE THREAD

**Issue by rudym87** [microsoft/TypeScript#33007]
**TypeScript Version:**  3.7.0-dev.20190821

**Search Terms:** es5, quick fix, class, constructor, 8002

**Code**

```js
/**
 * @constructor
 */
function Classss() {
  this.a = 1;
}
```
**jsconfig.json**
```json
{
  "compilerOptions": {
    "target": "es5"
  }
}
```
**Expected behavior:**
No suggestion to convert constructor function to class declaration

**Actual behavior:**
Quickfix suggestion is shown in VS Code 1.37.1 and 1.38.0-insiders for `Classss`

**Playground Link:**
Not reproducible on Playground

**Related Issues:**
None

**Comment by orta** [comment]
Could you please explain why you think it shouldn't show the quickfix?

**Comment by rudym87** [comment]
If I use a `jsconfig` just for typechecking and not for compiling, this could produce invalid code for environments which do not support ES2015.
Maybe I'm just misunderstanding the meaning of `target` in `jsconfig`.

**Comment by fatcerberus** [comment]
TS assumes you're always going to transpile the code using tsc.  `target` is thus meant as the *transpilation target*, not the version of syntax supported.  TS itself *always* supports the latest syntax.

That said, I know there are a lot of cases where tsc is used only as a typechecker (which is why `noEmit` is a thing) so it might be nice to have a way to disable unsupported syntax in that case.

**Comment by RyanCavanaugh** [comment]
Newer syntax is always supported (e.g. this is why you won't see an error about using arrow functions, even if `target` is ES3), so the suggestion is sensical as far TS's consistent view of the world. Nothing forcing you to invoke it, of course.

**Comment by nmain** [comment]
This is similar in some ways to https://github.com/microsoft/TypeScript/issues/23391, which was changed after some community pushback.
