### ISSUE TITLE
Generic object generated from another object

### ISSUE THREAD

**Issue by gjabelAmbitas** [microsoft/TypeScript#33048]
Hey👋 i have 1 question.

If i have object like:
const a = `{b:{d:0, e:0}, c:{} } `

where b can be random object 
for example b type is :  `{[key:string]:anything}`   

So question is: 
can be c generic from b? Like c can contain only b object  (only d & e) and nothing more? :) 

Thanks.

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
