### ISSUE TITLE
index signature is missing for type

### ISSUE THREAD

**Issue by X4V1** [microsoft/TypeScript#33099]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**
index signature is missing in type ...

**Code**

```ts
interface A { name: string; }

function testFn (param: {[key: string]: string}) {
    return param;
}

let testA: A = {name: 'Xavier'};
let testB: { name: string; } = {name: 'Xavier'};

testFn(testA); <- Error: index signature is missing
testFn(testB); <- Working fine
```

**Expected behavior:**
Allow to pass testA to testFn.
**Actual behavior:**
Throw an error
**Playground Link:** 
https://stackblitz.com/edit/missing-index-in-type-demo?file=index.ts
**Related Issues:**

**Comment by jack-williams** [comment]
This is working as intended. Object literal types have implicit index signatures---interfaces do not.

If you search "_index signature is missing for type_" issue #32263 appears in the first 10 results, and it should point you to relevant PR's and issues.

**Comment by poseidonCore** [comment]
Note that you can usually get away with a type definition instead because it works similarly to an object literal type.

``` ts
interface A { name: string; }
type C = { name: string; }

function testFn (param: {[key: string]: string}) {
    return param;
}

let testA: A = {name: 'Xavier'};
let testB: { name: string; } = {name: 'Xavier'};
let testC: C = {name: 'Xavier'};

testFn(testA); // throw an error 
testFn(testB); // same structure but this works
testFn(testC); // Works like object literal type.
```
[TS Playground](https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgILIN7JHAthALmQGcwpQBzAbmQF8AoMATwAcUBhZAXk2z0JJlKNBvRgBXEAjDAA9iGSRSAMQUAKFnCh4iGANoBrCEyKlyICgF1TQi7QCUmeshfIoEMOKgLN23FXpRABsPRQhSVCJ0HgwcfCIAcgANOAA3YGgE2gCQsDDSACFdPnjBc2o6bkw4gWS0jKgsnNClMHYiThiaxJT0zOz6RnCwVTVW1HsaAHopxQALKFkAd2Q4BWhFqGQhlRAx4YLJ5BmSfjLxaS8UACNxPLA54GJkJdkoA2Idkb3W9iOTgDqbw+yCCwCMyFk1wAVhBpKDgJBtEFFKwIAA6ehAA)
