### ISSUE TITLE
Declaration dts files cannot represent enums nested in interfaces

### ISSUE THREAD

**Issue by trevorade** [microsoft/TypeScript#33166]
**TypeScript Version:**  3.5.0

**Search Terms:** enum in interface declaration

**Code**

For JavaScript code being edited with Monaco, DTS libraries are used to inform Monaco of the symbols which can be autocompleted.

In our case, our library permits code like the following:

```js
Lib.setEnum(Lib.MyEnum.ONE);
Lib.chain().setEnum(Lib.MyEnum.ONE);
```

The expected way to represent this would be something along the lines of:

```ts
// lib.d.ts
interface Lib {
    chain(): Lib;
    setEnum(val: Lib.MyEnum);
}
const Lib: Lib;
module Lib {
    enum MyEnum { ONE }
}
```

**Expected behavior:**

TypeScript is aware of the symbols `Lib.chain`, `Lib.setEnum`, `Lib.MyEnum`.

**Actual behavior:**

As written, with `module Lib` at the end of `lib.d.ts`, only `Lib.chain` and `Lib.setEnum` autocomplete.  `Lib.setEnum` takes an `any` though instead of `Lib.MyEnum`.

If you move `module Lib` to the top of `lib.d.ts`, only `Lib.MyEnum` autocompletes.

**Comment by sandersn** [comment]
This one is tricky. enums define both a type and a value, so the containing namespace `Lib` defines a value too. That means it can't merge with any other values, like `const Lib`. But in order for references like `Lib.setEnum` to resolve, the *value* `Lib` needs to contain `setEnum`. So you need to declare the functions on the namespace instead of the interface.

This leaves you with a problem of referencing the type that `Lib` defines in `chain`. Confusingly, it's not `Lib` since the namespace `Lib` is a value, not a type. It's `typeof Lib`.

```ts
declare namespace Lib {
    export function chain(): typeof Lib
    export function setEnum(val: Lib.MyEnum): any;
    enum MyEnum { ONE }
}

Lib.setEnum(Lib.MyEnum.ONE);
Lib.chain().setEnum('hi'); // expect error here
```
