### ISSUE TITLE
`export default` enums causes error

### ISSUE THREAD

**Issue by seanchas116** [Microsoft/TypeScript#3320]
```typescript
export default
enum Foo {
  Bar, Baz
}
```

causes

```
test.ts(2,1): error TS1109: Expression expected.
```

error. (file is `test.ts`)

```typescript
export
enum Foo {
  Bar, Baz
}
```

compiles successfully.

**Comment by DanielRosenwasser** [comment]
This is by design - ES6 supports `export default class ...` and `export default function ...`, and so we support those. If you find yourself sorely missing this, you can suggest that we allow enums to be declared as `default` exports, but as a trivial workaround, you can instead just write the following:

```TypeScript
enum Foo {
  Bar, Baz
}

export default Foo;
```

**Comment by SetTrend** [comment]
I'd prefer to have this default export a first class citizen of the language, too. Same fo `const enum`s.

If the workaround is trivial then I belive it should be integrated with the language, so one isn't required to remember this workaround every time it occurs.

**Comment by crbranch** [comment]
I would also vote for making `export default enum` a first-class citizen.  While it's true that the workaround provided by @DanielRosenwasser is trivial, it certainly was not obvious to me beforehand.  If the intention/goal is to steer people away from using `export =` and instead prefer using `export default`, then it would helpful to apply `export default` consistently for classes, interfaces, and enums.  I got tripped up on this while converting some code from the old `export =` to the new `export default` format.  The existing code looked like:

    // Foo.ts
    class Foo {
    ....
    }

    export = Foo;

I changed to:

    // Foo.ts
    export default class Foo {
    ....
    }

This pattern works for classes and interfaces, but not enums.  If you try this with an enum, you get a compiler error (TS1109: Expression expected).  Before discovering the workaround, I thought my only option was to use `export enum` instead of `export default enum` for the enum definition.  But using `export enum` would make the consumer inconsistent on how classes vs. enums are imported and referenced.  For example, suppose we have an enum defined in Color.ts as `export enum Color { ... }`, and a class defined in ColorUtil.ts as `export default class ColorUtil { ... }`, and we want to use both in Consumer.ts:

Option # 1: import syntax is consistent, but each enum usage would require doubling the name:

    // Consumer.ts

    import Color from "./Color";
    import ColorUtil from "./ColorUtil";

    var color: Color.Color = Color.Color.Red;    // not ideal
    ....

Option # 2: you can avoid name doubling if you're willing to use a different syntax for the import:

    // Consumer.ts

    import {Color} from "./Color";        // not ideal
    import ColorUtil from "./ColorUtil";

    var color:Color = Color.Red;
    ....

I dislike both of these options because of the inconsistency between how the class and enum are treated.  Fortunately, this is solvable with the workaround, but only if you aren't willing to settle for # 1 or # 2 above and spend the time to search and hopefully stumble upon this workaround.

**Comment by clavecoder** [comment]
I'm OK with leaving it as is if the reasoning is that interfaces, et al, are not vaid **EcmaScript** and #3917 is implemented.
