### ISSUE TITLE
Suggestion: add global `Dictionary` type to standard library

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#33214]
## Search Terms

global standard lib library dictionary object type

## Suggestion

In my experience it's very common to define a dictionary type to represent an object with an index signature:

```ts
type Dictionary<T> = { [index: string]: T };
```

Seeing as this is a frequent helper, I wonder whether it could be added to the standard library as a global?

This might also help to prevent misuse of `Record`. Usually "record" refers to an object with known keys, e.g. `Record<'foo' | 'bar', string>`, whereas "dictionary" refers to an object with unknown keys—but many people use `Record` to define a "dictionary", e.g. `Record<string, string>`. This doesn't create any errors, but it's very confusing to read and goes against the common terminology of "records" and "dictionaries".

## Examples

In Redux this is very common:

```ts
const usersById: Dictionary<User>;
const user: User = usersById['foo'];
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by ilogico** [comment]
`type Dictionary<T> = Record<string, T>`
- it saves very few keystrokes and doesn't help with readability
- would `type Whatever<T> = Map<string, T>` be acceptable?
- it's common to use objects as dictionaries because we didn't have Map before and because it maps neatly to JSON, but do we really want to make that pattern easier? shouldn't people move to proper data structures where you can `something.has(key)` instead of `Object.prototype.hasOwnProperty.call(something, key)`?
- it's probably more common for me to constrain the keys to some strings:
```ts
type Whatever = 'option-1' | 'option-2';
declare const options: Record<Whatever, Something>;
```
and I think it's a good thing to increase visibility of the `Record` type rather than replacing it with `Dictionary` half the time
