### ISSUE TITLE
NumericLiteral nodes with value 9007199254740993 claim to have .text = 9007199254740992

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/TypeScript#33298]
**TypeScript Version:**  3.7.0-dev.20190907

**Search Terms:** numeric literal max value 9007199254740992 9007199254740993 

**Code**

```ts
const ts = require("typescript");
const sourceFile = ts.createSourceFile("temp.ts", "9007199254740993", 99);
const literal = sourceFile.statements[0].expression;

// '9007199254740992'
console.log("Actual .text:", literal.text);

// '9007199254740993'
console.log("Expected .text:", literal.getText(sourceFile));
```

**Expected behavior:**

`.text` should be the direct textual representation of the literal's value, right?

**Actual behavior:**

...some kind of rounding behavior related to being above `Number.MAX_SAFE_INTEGER`?

**Playground Link:** https://astexplorer.net/#/gist/8ee21b9bb7973f0d0118658496cec5ec/9dcea811268d39e678732414b53d608e37747a63 - since this is an AST parser issue

**Related Issues:** Discovered while writing a codefix for #29863. 😆

**Comment by JoshuaKGoldberg** [comment]
Did a little bit of digging. This happens in `checkBigIntSuffix` (in `scanner.ts`):

https://github.com/microsoft/TypeScript/blob/73a2146583a774d322cfda8531fb22f34b6cc734/src/compiler/scanner.ts#L1478

Removing that `+` fixes the issue. Happy to send a PR if this is desirable!

**Comment by lowr** [comment]
I found this issue while fixing #46195. Looking at the explanation for the `text` property of `LiteralLikeNode` ([link](https://github.com/microsoft/TypeScript/blob/4b794fe1dd0d184d3f8f17e94d8187eace57c91e/src/compiler/types.ts#L2127-L2131)), it seems like it is actually working as intended. I'm not sure it’s always been like so since when this issue was opened, though.

Also it's arguable that the property name `text` is confusing as one would expect it to be the node's textual representation in the source code as OP does.

**Comment by RyanCavanaugh** [comment]
Agreed this is operating as documented.
