### ISSUE TITLE
instanceof

### ISSUE THREAD

**Issue by jeremy-coleman** [microsoft/TypeScript#33291]
**TypeScript Version:**  3.6.2

**Search Terms:**
instanceof
**Code**
```ts
function tryParse(o) {
  if (typeof o === 'string' || o instanceof String) {
      o = JSON.parse(o);
  }
  else o = 'QQ'
  return o
}
```
**Expected behavior:**
instanceof ConstructableThing should be typed as the return type of ConstructableThing, but its treated as the constructor
**Actual behavior:**
![image](https://user-images.githubusercontent.com/25135855/64465454-bdf66400-d0da-11e9-94fd-5857aa1406be.png)

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/31576 maybe

**Comment by fatcerberus** [comment]
`instanceof` as a typeguard narrows to the return type of `ConstructibleThing`’s *`new` signature*, which is indeed uppercase-S `String`.

`"foo" instanceof String` is false.  `new String("foo") instanceof String` is true.  The behavior here is correct.

**Comment by jeremy-coleman** [comment]
ahh so Base -> new Base -> base , thank you

**Comment by fatcerberus** [comment]
> Base -> new Base -> base

Assuming this is meant to be a subtyping relationship: not quite.  `String` is an *object* type: It's a primitive string that's been converted to a full-fledged object ("boxed") so it can have arbitrary properties, gets passed by reference, etc. etc.  `string` is a primitive string value.

**Comment by poseidonCore** [comment]
Just to clarify where this error message actually originates, the problem here is more that a `String` instance is slipping through to `JSON.parse()`, which in its declaration expects a string primitive as an argument, but in reality, it is permissive enough to accept a String instance too:
```ts
...
o = JSON.parse(o);
/*ERROR ----------------------------------------------------------------------------------
(parameter) o: String
Argument of type 'String' is not assignable to parameter of type 'string'.
  'string' is a primitive, but 'String' is a wrapper object. Prefer using 'string' when possible.
----------------------------------------------------------------------------------------------*/
```

In reality, both `JSON.parse(new String('[0,1,2]'))` and `JSON.parse('[0,1,2]')` work normally, but the first produces the error above in TS.

[TS Playground](https://www.typescriptlang.org/play/#code/FIZQ8gcgdADghgJwM4FMAUA7FB3ABCAFwQEsMBzNAcgG0AGAGgEZ6AmAXUoEpOBuAKD6hIsRKip0mrDrz5A)

If you truly expect that to be a possibility, then you can normally hack this by just converting the `String` instance to a primitive with `JSON.parse(String(o));`
