### ISSUE TITLE
Recursive functions are inferred to have return type `any`

### ISSUE THREAD

**Issue by fsoikin** [Microsoft/TypeScript#3336]
Consider this code:

```
function fact( x: number, acc?: number ) {
	if (x <= 1) return acc;
	else return fact( x - 1, (acc||1)*x );
}

var res = fact( 5 );
```
([same thing on playground](http://www.typescriptlang.org/Playground/#src=%0Afunction%20fact(%20x%3A%20number%2C%20acc%3F%3A%20number%20)%20%7B%0A%09if%20(x%20%3C%3D%201)%20return%20acc%3B%0A%09else%20return%20fact(%20x%20-%201%2C%20(acc%7C%7C1)*x%20)%3B%0A%7D%0A%0Avar%20res%20%3D%20fact(%205%20)%3B%0A))

Here, `fact` is inferred to have type `(number, number?) => any`, and consequently `res` is inferred to have type `any`.
This is vaguely reminiscent of cases #1146, #475, and #523, but those deal with some esoteric circumstances, while this here is a [textbook case](https://mitpress.mit.edu/sicp/full-text/book/book-Z-H-11.html#%_sec_1.2.1) of a tail-recursive algorithm. Should work.

*Note*: no, it doesn't have to do with optional parameter, I checked.

**Comment by RyanCavanaugh** [comment]
We briefly had a spec that outlined how this could all work in theory (the term "witnessing" used in #402), but it didn't make it to implementation.

The current rule is that any function that sees itself during the resolution of its return type is `any`. This seems to be good enough in practice, since it's always possible to add the needed type annotation and most functions aren't recursive like this due to tail calls not being part of the ES spec yet (watch that stack!).

Unless some use cases become super compelling in terms of complexity vs gain, we don't foresee changing this for the sake of eliding one type annotation.
