### ISSUE TITLE
String union types question

### ISSUE THREAD

**Issue by lipedeitos** [microsoft/TypeScript#33385]
I just want to know if there's any logic explanation of what is happening and why one example work and other don't.

```typescript

interface CompTest1Props {
    compTest1: 'a' | 'b' | 'c';
}

class CompTest1 extends React.Component<CompTest1Props> {
    render(){
        return this.props.compTest1;
    }
}


interface CompTest2Props {
    compTest2: boolean;
}

class CompTest2 extends React.Component<CompTest2Props> {
    // Doesn't Work
    // 'No overload matches this call.'
    // Types of property 'compTest1' are incompatible.
    // Type 'string' is not assignable to type 'a' | 'b' | 'c''.
    render(){
        return <CompTest1 compTest1={this.props.compTest2 ? 'a' : 'b'}  />;
    }

    render(){
        let test: string;
        test = 'sm';
        return <CompTest1 compTest1={test} />;
    }
    
    // Works as expected  
    render(){
        return <CompTest1 compTest1="a" />;
    }

    render(){
        let test: any;
        test = 'sm';
        return <CompTest1 compTest1={test} />;
    }
}

```

**Comment by AnyhowStep** [comment]
Works on my machine,
```ts
import * as React from "react";

interface CompTest1Props {
    compTest1: 'a' | 'b' | 'c';
}

class CompTest1 extends React.Component<CompTest1Props> {
    render(){
        return this.props.compTest1;
    }
}


interface CompTest2Props {
    compTest2: boolean;
}

class CompTest2 extends React.Component<CompTest2Props> {
    render(){
        return <CompTest1 compTest1={this.props.compTest2 ? 'a' : 'b'}  />;
    }
}
```
[Playground](http://www.typescriptlang.org/play/?jsx=2#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcARFDvmQNwBQdwAdjFlAXlnAMIlgAqWVDACMABWJh0Abzpx5cXH0HCRALjgByZJrgAfLQCNdBzbk30Avg1wAbNOl7gVouFgAerJgBN02PDAAdE6QTFgsADwhLuKSqAB8cLIKcJQ+bAAUAJTJKQqUMACuUExwMAAWwKiBYHGBSs5CovQp1tYMzKzsnDzKTQBMEhBSSXIKDQIDGoYQELY4TFY29qiOfcL9bp7hvphUQSEQYZHRA0NSibnyad6ZOWN5qVhFJXBR664TMQC80hVVNTqXwGcAA-FodHANJpjJZ5AB6eItBRtIA)

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
