### ISSUE TITLE
Update systemjs export emit to support new bulk export variation

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#3346]
see https://github.com/ModuleLoader/es6-module-loader/issues/386 for more details about the fix.

**Comment by mhegazy** [comment]
@vladima We need to decide if this is a 1.5.2 issue or a 1.6 issue.

**Comment by vladima** [comment]
Given that current estimate for patch that will include bulk export support in es6 module loader is somewhere after forthcoming release I'd say that having this item fixed in 1.6 should be ok. I've asked @guybedford for more accurate timings, we can always reconsider this decision based on his answer

**Comment by mhegazy** [comment]
Users will need to update to latest System.js/JSPM

**Comment by guybedford** [comment]
TypeScript was only supported in SystemJS 0.17, which had the bulk export handling in place, so this shouldn't be breaking for TypeScript users of SystemJS.

**Comment by mhegazy** [comment]
I believe TypeScript support was added in release [v0.17.0](https://github.com/ModuleLoader/es6-module-loader/releases/tag/v0.17.0), where as the bulk export was added in release [v0.17.1](https://github.com/ModuleLoader/es6-module-loader/releases/tag/v0.17.1). @guybedford would it be safe to assume no one is using 0.17.0?

**Comment by guybedford** [comment]
Yes there was a ~10 day release window where 0.17.0 was the primary release for TypeScript testing. Because it's a patch upgrade, and the TypeScript support was clearly indicated as a new in-progress feature, I see no issue with including this in TypeScript and allowing the break for that tiny segment, who can simply do a patch update. Strictly it is a breaking change though for this segment, so can certainly be worth documenting according to what fits into your process there.
