### ISSUE TITLE
Omit properties from generic type which set by default and have extend

### ISSUE THREAD

**Issue by Vardner** [microsoft/TypeScript#33484]
**TypeScript Version:**  3.6.3
Omit extended generic type, type has no properties in common with type Pick Exclude
```ts
interface Bar {
    type: string;
    id?: string;
}

class Foo\<T extends Bar = Bar> {
    getParam (param: keyof Omit<T, 'type'>) {}

    test () {
        this.getParam('id');
    }
}
```
**Expected behavior:**
exclude the "type" property, and get in the available properties for the parameter "param" id and the rest that will be present in the interface because Bar is default param for T

**Actual behavior:**
Error "Type 'type' has no properties in common with type Pick <T, Exclude <keyof T>, 'type'>"

**Playground Link:** 
https://stackblitz.com/edit/typescript-8zyjig

**Related Issues:** https://github.com/Microsoft/TypeScript/issues/24791

**Comment by RyanCavanaugh** [comment]
Operations like `keyof Omit` are higher-order and can't be related to concrete types like `"id"`. From inspection we (humans) can say that `"id"` should be assignable to that type, but there's no way for TS to represent `keyof Omit<T, 'type'>`'s type in this format.

**Comment by Vardner** [comment]
@RyanCavanaugh Maybe you should indicate this in the documentation so as not to mislead beginners like me? I expected that TypeScript would understand that a universal type expanding by a certain interface would be able to get keys from it.

**Comment by Vardner** [comment]
@RyanCavanaugh I just want to note that if you extend a given class with a subclass of some kind and pass in a prepared object that is expanded by the Bar interface, then it begins to understand which keys need to be sorted out. That is, this problem can be fixed with a crutch by increasing the chain of inheritance by 1

**Comment by RyanCavanaugh** [comment]
Which documentation pages had you referred to before logging this? I'm trying to figure out which one to potentially add the information to.

**Comment by Vardner** [comment]
@RyanCavanaugh this one https://www.typescriptlang.org/docs/handbook/utility-types.html

**Comment by vipcxj** [comment]
@RyanCavanaugh what does `high-order` mean?
why TS know how to deal with `keyof Omit<Bar, 'type'>`
[playground](NXQyBb4AvvnwIANnBo1kAMQD2CgDwAVZBAAekEJ1npMAXjQYAfNjZFGEMAAUMcALbIAFGQePqAawgkFMZAB5R2AwNQAaZAByUgoo0wBKbFECKxt7KCcARld3TM9kHz8A4NDlA0iY8gh4pKwUy0JIOlc6xvZiAAtgGgA6azsPFyiuKITWVI6unv70jyzh0fH2lOEgA)
Is there some limits on generic type or Omit?

**Comment by mykwillis** [comment]
Something seems a little fishy here, because it seems TypeScript is able to properly build a list of a generic type's properties with `keyof` (i.e., if that generic type is specified to extend from another type), but it is not able to do the same thing with `Exclude`. It wouldn't seem (to an outsider) that these should be different problems.

See for example [this example](https://www.typescriptlang.org/play?ts=4.0.5#code/JYOwLgpgTgZghgYwgAgJLIN4Chm+QBwC5kBnMKUAcwG4sBfLLUSWRFAKUxzwEdiyKIGvUYIANnBIlkAMQD2cgDwAVZBAAekEABNpqAHxc8yANYQAnnJjEA5PhvIAvMjs3qyAPQfkAeQDS3LhmljCoxMFWaE4u9u5evgHGETDK4RaRqs6ucd7+jMbxYAAWwNKlyMUoAK4kKAiSKJTAAG5UBFByAEZiEAC2ZSDIALJyQgq1gWrq4lXaEMQAotNisxCKrgA0pukwyOyGWbGeuYl4GjNzYchLF2vJaFv3+9HZxwmT5ytzqdfLq4r3ZSPHZ7A4xNxvZQAZQATABmGEw4jKcz4FA2ABE+AxDnKIDkYGQkhIwEoIDg3RQYDkFVR6JuXzuIKByAxPAx+hsADpJpN4jU2hotLoidI0VBkMBevger0IOA4GBgKNkJEGatCB9NPLdLZ7FNhdInsgAPzIEAQZrQZBpELITLgnLvYxCnUkK73dCunRGkGcM0Wq0S20ZF5HeJ5F3an0-QEGt3bO3+82W60h3YO17xaHwxHIukuLE4yXSfGE4mk8mUio0sAFmxx70itkY00poM2xMZbkiZBAA) from https://stackoverflow.com/questions/64920228/using-typescript-exclude-with-generic-type
