### ISSUE TITLE
never rest type not assignable to complex rest type

### ISSUE THREAD

**Issue by jack-williams** [microsoft/TypeScript#33495]
**TypeScript Version:**  3.5.1

**Search Terms:**

**Code**

```ts
function foo<T extends any[]>() {
    const fn1: (x: string, ...rest: T) => unknown = (x, ..._) => x;
    const fn2: (...args: never) => unknown = fn1 // error
}
```

**Expected behavior:**

Assignment of `fn1` to `fn2` should pass.

**Actual behavior:**

Assignment of `fn1` to `fn2` should fails.

**Playground Link:** [link](https://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABMOcA8AVRBTAHlbMAEwGdEBDMATwG0BdAPgAoBKRAbwChEfEIESUZGACMALkRNcEwQCcYYAOYAaRADoNs7IIkY2AXgaJwAazBwA7kn2TcqjWoD6Bo7gDc3XvzCDhAJgkmB3JZRRIJMGwAN2xZF2MwM0trYRFOAF8gA)

**Related Issues:** 
#33457

**Comment by jack-williams** [comment]
The goal here would be to make all signatures structurally assignable to `(...args: never) => unknown`.

**Comment by RyanCavanaugh** [comment]
@ahejlsberg this seems reasonable to me. Thoughts?

**Comment by fatcerberus** [comment]
I did some experiments in the playground.  This seems to break only when the rest parameter is generic.  Use a concrete type and all is well:

* [Playground link](https://www.typescriptlang.org/play/#code/DYUwLgBAHghAXBAdiAbiATgbgFCkgTwQG0IBnMdAS0QHMAaCAOmcQFcBbAIwyIF0J+AXmiYIEAPTiIAdwD26ANalsucBABmUBAAotZCtXpNm6EOQRsuPXgEoIggHwRWiBYlnTE9iLobNGAPp2jiKqkOqEPv4Ahug0pBaoGMFOLm4eXsKaohJScorK2OouAMZglLJe6rKyADwAKhAgUGAgiAAmpBDRiPh8Dtp2AN7YYmJ40PBISVijYxORJORUtH7MjUIiYpIQACIAogByAJL7uzA+7pBJXqA00cA2c+Nqmjp6y4ZrjKbmEPUpZyudyeby+YyBQFQHBjCATCI6GJxBLTNDoQFpEGZDTQ7ZSdwyeQKfDYAC+2CAA)

Interestingly, `[ string, ...T ]` (where `T` is generic) isn't even legal and produces the error `A rest element type must be an array type.`  This seems like a pretty big clue: the assignment of `fn1` to `fn2` may only be failing because it's unable to construct a tuple type for the parameter list of `(x: string, ...rest: T) => unknown`.

**Comment by jack-williams** [comment]
This is where it fails in checking:
```ts
const sourceCount = getParameterCount(source);
const sourceRestType = getNonArrayRestType(source);
const targetRestType = getNonArrayRestType(target);
if (sourceRestType && targetRestType && sourceCount !== targetCount) {
    // We're not able to relate misaligned complex rest parameters
    return Ternary.False;
}
```

**Comment by fatcerberus** [comment]
@jack-williams That doesn't seem to explain why it succeeds for the non-generic case.  What is the exact definition of "complex" here?

**Comment by jack-williams** [comment]
> What is the exact definition of "complex" here?

A rest type where you don't know the bounds, or whether it is unbounded---I would guess.

**Comment by jack-williams** [comment]
FWIW. I think the fix is basically:
```ts
function getNonArrayRestType(signature: Signature) {
    const restType = getEffectiveRestType(signature);
    return restType && !isArrayType(restType) && !isTypeAny(restType) && !isTypeNever(restType) ? restType : undefined;
}
```

`+ isTypeNever`.

**Comment by AnyhowStep** [comment]
Repro taken from TS' source code,
https://github.com/microsoft/TypeScript/blob/c447ebc59c49a1b071c099ce6055e94517973eab/src/compiler/core.ts#L1460-L1464

```ts
/**
 * Safer version of `Function` which should not be called.
 * Every function should be assignable to this, but this should not be assignable to every function.
 */
export type AnyFunction = (...args: never[]) => void;

function foo<T extends any[]>() {
    const fn1: (...rest: T) => void = (..._) => {};
    const fn2: AnyFunction = fn1 // error
}
```

[Playground](http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=10&pc=2#code/PQKhCgAIUhlBDAZgUwE6QG5oM4EsD2AdpPopAAYBiAroQMYAuBh5kA7gBa50eTYf5qAGwAmkQvgaQARskh14QochEA6KDACiWVAE9IiWo2Z8BwsbMjxseAOaF405ZAb4XXbABoZ1KQw+mgqLikjJy1nYOTnKukMg6+ob0TETq0MDgyAAeAA74qH66OXIAgoS6NMkmALyQABSqjfCottgAXOLxaADaALoAlJDVAHyY+LgiANzg4EnGRAb4+AA8ACpxWQzIhCLYVuV9w3WDAN5QkBd0RNhSiIQAjB0NjajINx2rgyNjE0P1jaoAPpfUYnAC+0wul2ut0IACYOmUKkYUsRand7pBgMA4qhUPlwGCgA)
