### ISSUE TITLE
Await insert break ASI

### ISSUE THREAD

**Issue by Kingwl** [microsoft/TypeScript#33522]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**

**Code**

```ts
async function foo () {
  const a: Promise<any> = f()
  a./*here*/
}
```

**Expected behavior:**
```ts
;(await a).xxx
```

**Actual behavior:**

```ts
async function foo () {
  const a: Promise<any> = f()
  (await a).xxx // asi broken here
}
```

**Playground Link:** 

https://twitter.com/Luxcium/status/1174602967053471744

**Related Issues:**

**Comment by fatcerberus** [comment]
> `await a.xxx`

That wouldn't be the right thing to do because it would be parsed as `await (a.xxx)` and `a` is a promise.  Which is why the `await` is being added in the first place. 😄

**Comment by Kingwl** [comment]
friendly ping @andrewbranch 
Could you give some suggestions please？I cannot find some existed things about ASI detection....

**Comment by Luxcium** [comment]
[My issue was open there](https://github.com/microsoft/vscode-typescript-next/issues/5)
[I provided code example of my actual issue](https://github.com/Luxcium/questrade-ts/blob/aeefa22e38c5e82f84cebf9597b6b1f6f96665c0/src/core/functions/private/questrade/index.ts)

But in fact as I am coding I am relying on the linter to add semis on save and if autocompletion add parenthesis it should also take care of not becoming continuation of previous line... await by itself or code by itself will not cause problems because of the automatic semi insertion but a set of parenthesis added on the fly change this behaviour and become continuation of previous line...

in most cases it probably requires to add a semi when autocompleting with a set of parenthesis but some edge cases might implies not doing it but I am not sure why if the parenthesis would have been the continuation of previous line I assume it would have been added by the person not as a completion in that context I think

**Comment by Luxcium** [comment]
It’s nice because now automatic completion implement  not only then/catch/finally but also of the « then resolved promises » by adding an await inside a set of parenthesis then a dot and then the other possibility 

```typescript
(async _=>{
const some:any  = await a;
const something:any = some.xxx('do something')
})()
```
now autocomplete and save you of assigning to an intermediary variable 

```typescript
(async _=>{
const something:any = (await a).xxx('do something');
})()
```

If you don’t need to say save to a variable/const then

This ...
```typescript
(async _=>{
  const a: Promise<any> = f()
  (await a).xxx('do something') // asi broken here
})()
```
... is the same as this:

```typescript
(async _=>{
  const a: Promise<any> = f()(await a).xxx('do something') // asi broken here
})()
```

**Comment by andrewbranch** [comment]
@Kingwl I added a lot of ASI logic in #33402; does that look helpful?

**Comment by Kingwl** [comment]
Hi all, sadly I’m not 100% sure what could i do....
