### ISSUE TITLE
import function in ambient declaration

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#3358]
I'm trying to write a declaration file for keystonejs. But it seems like I can't write a function named `import` for it.

**source**:
```typescript
import keystone from "keystone";
keystone.import("models");
```

**Declaration file**:
```typescript
declare namespace Keystone {
    function import(path: string): void;// Fails?
}
declare module "keystone" {
    export default Keystone;
}
```

**Comment by lbguilherme** [comment]
[`import` is a reserved word since EcmaScript 1](https://mathiasbynens.be/notes/reserved-keywords), and I such, it cannot be used to name variables or functions. So this is illegal:

    var import = 3; // SyntaxError: Unexpected reserved word

But this is legal:

    var obj = {};
    obj.import = 4; // Ok

Note that on your code, you define a function named import. This is not allowed on plain javascript:

    function import() { return 5; } // SyntaxError: Unexpected reserved word

**Comment by tinganho** [comment]
Fair enough. I need resolve this issue with:
```typescript
((<any>keystone)["import"])('models');
```
