### ISSUE TITLE
`type` and `namespace` no longer appear as global keyword completion

### ISSUE THREAD

**Issue by uniqueiniquity** [microsoft/TypeScript#33615]
**TypeScript Version:**  3.6.2

**Search Terms:**
keyword, completion, global, namespace

**Code**

```ts
n
```

**Expected behavior:**
Completion gives `namespace`.

**Actual behavior:**
Completion does not give `namespace`.

**Playground Link:**  N/A

**Related Issues:** 
Broken by https://github.com/microsoft/TypeScript/pull/32474
See https://developercommunity.visualstudio.com/content/problem/749982/typescript-intellisense-is-incorrect-for-namespace.html for report.

**Comment by DanielRosenwasser** [comment]
Uh, should the `type` keyword be included too? Seems that list was too eager.

**Comment by simplywondrous** [comment]
@sandersn Can I try working on this?

**Comment by sandersn** [comment]
Sure! I re-reviewed the change and I *think* it was the drive-by fix in `getTypescriptKeywordCompletions` that made this happen; the code was clearly not operating as intended since it was truthy-checking a `kind` property. But I don't think the code that was there was correct either.

I noticed that [I added `declare`,`module` and functionlike-body-keyword to the existing code](https://github.com/microsoft/TypeScript/pull/32474/files#diff-85ceec7b87d5cdf531b9f1523a39e2e6R2066). So probably you have to add `namespace` to the list plus [any other keyword that got removed that you want to put back](https://github.com/microsoft/TypeScript/pull/32474/files#diff-cd92e8371fce86965331cb68f53306f1L4830).

Ping me @DanielRosenwasser and @andrewbranch on the review when it's ready.

**Comment by sandersn** [comment]
@simplywondrous since the beta ends next Monday, I'm going to go ahead and do this.
