### ISSUE TITLE
Typescript and hooks - union types.

### ISSUE THREAD

**Issue by Lukortech** [microsoft/TypeScript#33663]
Question: 

While using TypeScript I am using this as an interface entry: 
```setWhat: React.Dispatch<React.SetStateAction<string | boolean>>;```
but it throws an error, since union types are not really getting along with hooks, I think.

Now, the error states:  `Type 'Dispatch<SetStateAction<string>>' is not assignable to type 'Dispatch<SetStateAction<string | boolean>>'.`

I would expect typescript to understand what I am trying to do, but it seems a bit lost. 

I am using react: ^16.9.0, typescript: 3.5.3 and I'll be happy to provide more information if needed.

**Comment by ilogico** [comment]
Looking at react types: `type SetStateAction<S> = S | ((prevState: S) => S);`
Imagine the following:
```
const x: SetStateAction<string> = (s: string) => string.slice();
// The next line should fail with SetStateAction<string> is not assignable to SetStateAction<string | boolean>
const y: SetStateAction<string | boolean> = x;
if (typeof y === 'function') y(true);
```

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!

**Comment by program247365** [comment]
@Lukortech This helped me - https://fettblog.eu/typescript-react-typeing-custom-hooks/
