### ISSUE TITLE
Generic function return type inference regression in 3.7-beta

### ISSUE THREAD

**Issue by dloehr** [microsoft/TypeScript#33788]
**TypeScript Version:**  3.7.0-beta

**Search Terms:** 3.7-beta, inference, infer, return type

**Code**

```ts
interface Person {
  readonly age: number
  readonly firstName: string
}

declare function getProperty<K extends keyof Person>(name: K): Person[K]

interface Selector<Args extends any[], R> { (...args: Args): R }

type SelectorReturnType<
  Args extends any[],
  Fn extends Selector<Args, any>
> = Fn extends Selector<Args, infer R> ? R : never

declare function select<Args extends any[], Fn extends Selector<Args, any>>(
  selector: Fn,
  ...args: Args
): SelectorReturnType<Args, Fn>

const age = select(getProperty, 'age' as const)
const firstName = select(getProperty, 'firstName' as const)
```

**Expected behavior:**
The type of `age` should be inferred as `number` and the type of `firstName` should be `string`. This is how it works with TypeScript 3.6.3.

**Actual behavior:**
`age` and `firstName` are both `string | number`

**Playground Link:** https://www.typescriptlang.org/play/?ts=3.7-Beta#code/JYOwLgpgTgZghgYwgAgArQM4HsTIN4BQyyUEcAJjgDYCeycA5hAFzIgCuAtgEbQDcREmUohayGMCgYwAOTicWyaVFAMBAXwIFyEBFTilx7EAjDAcyJmFRQsAB2hgaAHgDSyCAA9IIchmQA1hA0WDBomDgAfAAUIPKKrgCUrOhSOADargC6AgSgkLCIKADKEFS6YFhQzgCCUAz+Xj5+9CA06VkANMgASpH4gtEAdCMGDax1Dcm9GlpODsil5aZVPRBg7FAgACo0Ds6Ck43eEL7+cG0dnYIAYrhNpy1LFVW19RjdFzSRBP0AvMg7h4TmdFmUXtUjt1QDBoL1+gB+XrIVggCAAN34Wh0egMKBgxlM5lwGHBpjeDWBzXOly6gPuIKeZMqkPenzakRiglJyxZrDu12IIyGYwwE3eBGmzxWUDWGy2u32UPpkVyCBw0noTGQAJ5FWiVhs9kcNG6ACJGBAzfR-OqQNJEgI7ZqJFJZPEdUpmQb1kaHFAnObXdI5AprXBbRqwI6CEA

**Comment by ahejlsberg** [comment]
This is an intended effect of #33228. The type of the `selector` parameter is the naked type parameter `Fn`, and we now infer the exact type of `getProperty` instead of instantiating `getProperty` in the context of the constraint of `Fn` and inferring from that. While this produces a more general inference for `Fn`, it also erases the connection what we've already inferred for `Args`.

However, there is a much simpler way to write this that has the desired effect:

```ts
declare function select<A extends any[], R>(selector: (...args: A) => R, ...args: A): R;

const age = select(getProperty, 'age' as const)
const firstName = select(getProperty, 'firstName' as const)
```

This works with both 3.6.3 and 3.7.

**Comment by dloehr** [comment]
Thanks @ahejlsberg!
