### ISSUE TITLE
@ts-ignore is hard to use with calls to overloads

### ISSUE THREAD

**Issue by turadg** [microsoft/TypeScript#33795]
**TypeScript Version:**  [3.7.0-beta](http://www.typescriptlang.org/play/?esModuleInterop=true&jsx=2&ts=3.7-Beta#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocpAOwFc8BlXJAUTrwG9y4e4AxAJIIGAFQA03XgxYBhAPIA5ACISAvhXJoANigDOuuExBIZuMHCQAPGDQAmB5OhgA6U+AjUaMADwc4mCAgALkNmNnoxOAAjFCgQ9iikKDhVAD44LlVKTFpqDGAPODkYAAsktzAACgBKDMkeIhhaKGo4SvreHm8jEzMOzs6AekG4AAEYXQBaYABzamgkfoGeAIgAXgAiQWERDaXl4bGJ6bmF-YGYqE2UBhgoYGoZveWeQdSO6vJVIA), [3.6.3](http://www.typescriptlang.org/play/?esModuleInterop=true&jsx=2#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocpAOwFc8BlXJAUTrwG9y4e4AxAJIIGAFQA03XgxYBhAPIA5ACISAvhXJoANigDOuuExBIZuMHCQAPGDQAmB5OhgA6U+AjUaMADwc4mCAgALkNmNnoxOAAjFCgQ9iikKDhVAD44LlVKTFpqDGAPODkYAAsktzAACgBKDMkeIhhaKGo4SvreHm8jEzMOzs6AekG4AAEYXQBaYABzamgkfoGeAIgAXgAiQWERDaXl4bGJ6bmF-YGYqE2UBhgoYGoZveWeQdSO6vJVIA)
(Works in [3.5.1](http://www.typescriptlang.org/play/?esModuleInterop=true&jsx=2&ts=3.5.1&ssl=20&ssc=1&pln=20&pc=2#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocpAOwFc8BlXJAUTrwG9y4e4AxAJIIGAFQA03XgxYBhAPIA5ACISAvhXJoANigDOuuExBIZuMHCQAPGDQAmB5OhgA6U+AjUaMADwc4mCAgALkNmNnoxOAAjFCgQ9iikKDhVAD44LlVKTFpqDGAPODkYAAsktzAACgBKDMkeIhhaKGo4SvreHm8jEzMOzs6AekG4AAEYXQBaYABzamgkfoGeAIgAXgAiQWERDaXl4bGJ6bmF-YGYqE2UBhgoYGoZveWeQdSO6vJVIA))

**Search Terms:** ts-ignore, JSX, React, props

**Code**
(See links on the version numbers above for TS Playground)

```ts
import React from 'react';

enum SomeEnum {
    FIRST,
    SECOND,
};

class SomeComp extends React.Component<{ foo: SomeEnum, bar: number }> {
}

function OtherComp() {
    return (
        <SomeComp
            // @ts-ignore
            foo="FIRST"
            // @ts-ignore
            bar="aString"
        />
    )
}
```

**Expected behavior:** no errors

**Actual behavior:** Error on `foo` and on `bar`. Deleting either prop makes for no errors.

**Playground Link:** 

- [3.7.0-beta](http://www.typescriptlang.org/play/?esModuleInterop=true&jsx=2&ts=3.7-Beta#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocpAOwFc8BlXJAUTrwG9y4e4AxAJIIGAFQA03XgxYBhAPIA5ACISAvhXJoANigDOuuExBIZuMHCQAPGDQAmB5OhgA6U+AjUaMADwc4mCAgALkNmNnoxOAAjFCgQ9iikKDhVAD44LlVKTFpqDGAPODkYAAsktzAACgBKDMkeIhhaKGo4SvreHm8jEzMOzs6AekG4AAEYXQBaYABzamgkfoGeAIgAXgAiQWERDaXl4bGJ6bmF-YGYqE2UBhgoYGoZveWeQdSO6vJVIA)
- [3.6.3](http://www.typescriptlang.org/play/?esModuleInterop=true&jsx=2#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocpAOwFc8BlXJAUTrwG9y4e4AxAJIIGAFQA03XgxYBhAPIA5ACISAvhXJoANigDOuuExBIZuMHCQAPGDQAmB5OhgA6U+AjUaMADwc4mCAgALkNmNnoxOAAjFCgQ9iikKDhVAD44LlVKTFpqDGAPODkYAAsktzAACgBKDMkeIhhaKGo4SvreHm8jEzMOzs6AekG4AAEYXQBaYABzamgkfoGeAIgAXgAiQWERDaXl4bGJ6bmF-YGYqE2UBhgoYGoZveWeQdSO6vJVIA)
- [3.5.1](http://www.typescriptlang.org/play/?esModuleInterop=true&jsx=2&ts=3.5.1&ssl=20&ssc=1&pln=20&pc=2#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocpAOwFc8BlXJAUTrwG9y4e4AxAJIIGAFQA03XgxYBhAPIA5ACISAvhXJoANigDOuuExBIZuMHCQAPGDQAmB5OhgA6U+AjUaMADwc4mCAgALkNmNnoxOAAjFCgQ9iikKDhVAD44LlVKTFpqDGAPODkYAAsktzAACgBKDMkeIhhaKGo4SvreHm8jEzMOzs6AekG4AAEYXQBaYABzamgkfoGeAIgAXgAiQWERDaXl4bGJ6bmF-YGYqE2UBhgoYGoZveWeQdSO6vJVIA)

**Related Issues:** I first thought it was https://github.com/microsoft/TypeScript/issues/33256 but @sandersn [advised to file a separate issue](https://github.com/microsoft/TypeScript/issues/33256#issuecomment-538149858)

**Comment by threehams** [comment]
This is only a problem with class components, interestingly. Function components are fine.
[3.7.0-beta](https://www.typescriptlang.org/play/?jsx=2&ts=3.7-Beta#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocpAOwFc8BlXJAUTrwG9y4e4AxAJIIGAFQA03XgxYBhAPIA5ACISAvhXJoANigDOuuExBIZuMHCQAPGDQAmB5OhgA6U+AjUaMADwc4mCAgALkNmNnoxOAAjFCgQ9iikKDhVAD44LlVKNA9deCMkORgACyS3MBDHDGc+GV9-QJCC8JBImLi4BKSU9IBeOAAKAEo4XvS6LS0NTFpqDGAPOCLSqHLhjMkeIhhaKGpBzd4ebwLlsrNDo6OAemu4AAEYXQBaYABzamgkS6ueAIhegAiQTCESAn6-W4PJ6vD5fCFXdpAlAMGBQYDUN7g348a6pQ5DciqIA)

**Comment by sandersn** [comment]
Briefly, the reason that this fails is that reporting of errors on overloads doesn't want to stack tonnes of errors on individual parameters. Instead it puts a span on the entire call  `<SomeComp ...`. You can work around this problem by putting the ts-ignore above `<SomeComp ...`.

Because overload error reporting can report one error per overload per parameter, the non-overload behaviour of sticking errors on individual parameters would put multiple errors on each parameter. Instead it gives a multiline report-style error, but its span is the entire call.

React.FC doesn't have overloads, so it will only ever have one error per parameter, so it keeps error on each parameter. (React.Component's constructor has two overloads, one of which is deprecated =(

```ts
        constructor(props: Readonly<P>);
        constructor(props: P, context?: any);
```

To fix this, we'd need to come up with a better way to correlate and display per-parameter errors with overloads. I'm not sure what that would look like.

Thanks all for the playground links. React repros are :100: easier now that the playground has react.

**Comment by turadg** [comment]
> You can work around this problem by putting the ts-ignore above `<SomeComp ....`

That does work in the snippets above. How would you do it for this?
```
        <div>
            <SomeComp
                foo="FIRST"
                bar="aString"
                />
        </div>
```
This stops the errors but puts a string into the JSX expression:
```
        <div>
            // @ts-ignore
            <SomeComp
                foo="FIRST"
                bar="aString"
                />
        </div>
```

Flow supports `{/* */}` suppressions, but it seems [TypeScript does not](https://github.com/microsoft/TypeScript/issues/31147).
```
        <div>
            {/* @ts-ignore */}
            <SomeComp
                foo="FIRST"
                bar="aString"
                />
        </div>
```

**Comment by sandersn** [comment]
@turadg How would `{/* */}` solve the problem of inserting a string? The string insertion happens because of the extra line inside the `<div>`, right?

**Comment by lamontadams** [comment]
@sandersn I just want to make sure you know this works as-expected in 3.5 and it feels like a regression in 3.6 - almost like something changed so that `ts-ignore` is applied at the statement level instead of the line level now. 

Putting `ts-ignore` on the whole component works around the issue for me, but it has the undesirable side-effect of removing type-checking on the whole component (because `ts-ignore` applies at the component level rather than at the single prop I want ignored). That's really undesirable for components that have lots of props.

**Comment by turadg** [comment]
> How would {/* */} solve the problem of inserting a string? The string insertion happens because of the extra line inside the `<div>`, right?

@sandersn In JSX within <> expressions, `{}` escapes back into JS.

You can see the [ts-ignore string appear in // style](http://www.typescriptlang.org/play/?jsx=2&ts=3.7-Beta#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocpAOwFc8BlXJAUTrwG9y4e4AxAJIIGAFQA03XgxYBhAPIA5ACISAvhXJoANigDOuuExBIZuMHCQAPGDQAmB5OhgA6U+AjUaMADwc4mCAgALkNmNnoxOAAjFCgQ9iikKDhVAD44LlVKTFpqDGAPODkYAAsktzAACgBKDMkeIhhaKGo4SvreHm9bYAA3VI7OzoB6YbgAARhdAFpgAHNqaCRBoa6jEzMV1c6AiABeACJBYREDre2eGKhDlAYYKGBqObOLi+GBi+9hnv6O6vJVEA) and [be absent in {/* */} style](http://www.typescriptlang.org/play/?jsx=2&ts=3.7-Beta#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocpAOwFc8BlXJAUTrwG9y4e4AxAJIIGAFQA03XgxYBhAPIA5ACISAvhXJoANigDOuuExBIZuMHCQAPGDQAmB5OhgA6U+AjUaMADwc4mCAgALkNmNnoxOAAjFCgQ9iikKDhVAD44LlVKTFpqDGAPODkYAAsktzAACgBKDMkeIhhaKGo4SvreHm9bYAA3VI7Ozo4AegAqOAABGF0AWmAAc2poJDgxkayhrbhvIxMzQe3OgIgAXgAiQWERc8OjnhioC5QGGChgagXb++2RgaPvCMev0OtVyKogA)

> this works as-expected in 3.5 and it feels like a regression in 3.6

+1, this is a regression in 3.6 and persisting in 3.7

**Comment by threehams** [comment]
It's nothing specific to JSX, but rather a change to errors on overloads in general. It's affecting React because of the use of overloading in @types/react (interface Component + class Component). Here's an example of an overloaded function and the difference between 3.5.1 and 3.7.0:
[3.5.1](https://www.typescriptlang.org/play/?jsx=2&ts=3.5.1#code/JYOwLgpgTgZghgYwgAgApQPYAcDOBGZAbwChkzkQ4BbCALmRzClAHMBuU8uAE26ghw56jZiHbEAvsVCRYiFOmw4ATEU5lKNeiACuVAEbQO5ZDz4ChFPYagcp3CAgA2cfshg6QCMMAwhkGABu0E4YPBDcABRYmLj0irh4AJT0gRjA3BwOzq4oHl4+fgHBUKHhUTFK8bH4KchpGRzEQSFhDlEkJpp0yHgANOqmvPyC2jpOTgMSSRxAA)
[3.7.0-beta](https://www.typescriptlang.org/play/?jsx=2&ts=3.7-Beta&ssl=1&ssc=1&pln=16&pc=1#code/JYOwLgpgTgZghgYwgAgApQPYAcDOBGZAbwChkzkQ4BbCALmRzClAHMBuU8uAE26ghw56jZiHbEAvsVCRYiFOmw4ATEU5lKNeiACuVAEbQO5ZDz4ChFPYagcp3CAgA2cfshg6QCMMAwhkGABu0E4YPBDcABRYmLj0irh4AJT0gRjA3BwOzq4oHl4+fgHBUKHhUTFK8bH4KchpGRzEQSFhDlEkJpp0yHgANOqmvPyC2jpOTgMSSRxAA)

Might be a good question for the maintainers of the React types; I don't really understand why the interface overload is there.

**Comment by vamshi9666** [comment]
This worked for me ,

```

           {
              // @ts-ignore
              <p>{chef && user[dataKey]}</p>
            }
```

**Comment by turadg** [comment]
Agree that in 4.2.2 the problem in https://github.com/microsoft/TypeScript/issues/31147 is gone. (What @vamshi9666 said now works.)

Closing this issue since that is a fine work-around for the problem reported.
