### ISSUE TITLE
Allow noEmit and composite together in 3.7

### ISSUE THREAD

**Issue by Volox** [microsoft/TypeScript#33809]
**TypeScript Version:**  3.7.0-beta

**Search Terms:** composite noEmit monorepo

**Expected behavior:**

In 3.6 I was able to compile with those 2 options enabled now in 3.7 beta I cannot do that anymore.

**Actual behavior:**

`error TS5053: Option 'noEmit' cannot be specified with option 'composite'.`

**Related Issues:** No?

**Comment by RyanCavanaugh** [comment]
@sheetalkamat this breaks `vstsc` for projects with `composite` because the task adds `noEmit` to the commandline

**Comment by amcasey** [comment]
As part of it's incremental compilation, VS runs a pass with `--listEmittedFiles --listFiles --noEmit`.  cc @uniqueiniquity

**Comment by sheetalkamat** [comment]
interesting.. Technically with --noEmit shouldn't listEmittedFiles be empty list?

**Comment by amcasey** [comment]
@sheetalkamat, I would think so too, but @uniqueiniquity or @PranavSenthilnathan would know more about why it's there.

**Comment by uniqueiniquity** [comment]
It should - I don't think `--listEmittedFiles` necessarily needs to be part of that pass.

**Comment by yacinehmito** [comment]
The issue seems to be back in 3.8.2.

**Comment by weswigham** [comment]
The revert was reverted again in https://github.com/microsoft/TypeScript/pull/36483 because, per https://github.com/microsoft/TypeScript/issues/32882, it _really_ doesn't make sense to have `incremental` and `noEmit` together, since `noEmit` prevents us from writing incremental metadata. (So nothing is actually incremental).

You should consider `emitDeclarationsOnly` instead of `noEmit`, if you actually just want incremental checking.

**Comment by yacinehmito** [comment]
Thank you. It makes sense.

**Comment by yacinehmito** [comment]
For other readers: the parameter to use is `emitDeclarationOnly` (_declaration_ is singular).

**Comment by pleerock** [comment]
@weswigham right now its impossible to use composite projects, where one of the project is react-based. Because `create-react-app` adds `"noEmit": true` to tsconfig automatically (even if you set it to false, once you run app it will change it to true) it makes impossible to use react and composite projects.

Its a big issue because guess over 95% of react users use `create-react-app`.

**Comment by milesj** [comment]
I'm still not sold on this. I used `noEmit` within our tests folder, because we _don't_ want test files being compiled, nor generating declaration files. Now this pattern isn't possible without using a ton of gitignore patterns.

**Comment by yacinehmito** [comment]
I am in the exact same situation as you are; I was using `noEmit` with `incremental` on test files. However the point is that you're not actually benefiting from `incremental` if you are not emitting declaration files.

> Now this pattern isn't possible without using a ton of gitignore patterns. (...) It also breaks other tooling like ESLint as these built files are now being pulled in (...)

I wonder about the specifics of your project. For ours, all build artifacts are in a `build/` folder. It is ignored by both git and ESLint. When setting `emitDeclarationOnly` for test files, I didn't have to change anything as the declaration files were emitting alongside the normal code.
The only thing I have to add is something to delete these declaration files when publishing.

**Comment by milesj** [comment]
This isn't the project, but a similar setup: https://github.com/airbnb/lunar/blob/master/packages/core/test/tsconfig.json Each test folder has its own `tsconfig.json`, separate from the package itself, since it has different requirements.

Now that incremental emits files, it's converting our test files to js, like `foo.test.ts` -> `foo.test.js`, which resulted in ESLint running against all of these new js files (and failing a ton). I got around this with `emitDeclarationOnly: true`, and gitignoring the `d.ts` files, but it still feels super ugly.

**Comment by weswigham** [comment]
> I got around this with emitDeclarationOnly: true, and gitignoring the d.ts files, but it still feels super ugly.

You can also use the `declarationDir` option to dump the declaration files in a cache directory that's easier to ignore, if you'd prefer.
