### ISSUE TITLE
ES6 transpiled await breaks code if inside for/in loop

### ISSUE THREAD

**Issue by IlCallo** [microsoft/TypeScript#33812]
**TypeScript Version:**  3.6.3 and next

**Search Terms:** async await es6 transpile for in loop

**Code**
```ts
async function exampleA(data: { [index: string]: any }) {
  for (const key in data) {
    console.log('stuff1-a');
    await Promise.resolve(data[key]);
    console.log('stuff2-a');
  }
}

async function set(value: any) {
  await Promise.resolve(value);
}

function exampleB(data: { [index: string]: any }) {
  for (const key in data) {
    console.log('stuff1-b');
    set(data[key]);
    console.log('stuff2-b');
  }
}

const data = {
  'hola': 'hey',
  'ciao': 'hello'
};

exampleA(data);

exampleB(data);
```

**Expected behavior:**
`exampleA` should behave like `exampleB`: wait for the promise to finish and then proceed into logging the following messages.

**Actual behavior:**
When transpiled, `exampleA` awaiter function wraps the whole for/in loop instead of the single await line.
In my code this somehow results in `exampleA` to immediately interrupt execution of the whole function at the very first time the line is processed, without firing off any kind of error even when wrapped into a try/catch.

In `exampleB` the awaiter wraps only the single line of `set` function and everything works as expected.

Strange fact: `exampleA` works fine when it's used into a Jest environment and processed by `ts-jest`, but breaks when compiled directly via `tsc` and run on a Node v12.11.1 process (with experimental modules enabled, but I don't think this matter).
I don't know how to explain this difference because I don't know how to check the code transpiled by `ts-jest`.
If the code is the same, the bug is probably related to my setup, yet I don't understand how and will happily accept some guidance in how to debug it further
Edit: Promise creation was wrong, my bad when I stripped down the example bare bones. In the real code a Firebase Firestore `DocumentReference.set()` is there returning a Promise.

**Playground Link:** [playground](https://www.typescriptlang.org/play/?target=2#code/IYZwngdgxgBAZgV2gFwJYHsIwKYA9gC2ADgDbYCCAFACbDLABcMA3jANqoTV5MjIBOnAOYBdJsAhgYAXwCULAFAx46fjEpRMfGAGtsUzjFr15zJcpiaIIdGQB0JdEMoByPgjhwAjAFpgL2QBuc2VgAHdgVGQYCGwwmAAFfnQCVBBsGjpgNj0wESCQyy1bbAcnV3dPACY-AODlaQVGhVBIWEQUDCx05EoAN2ASBGxxSVNzcMjo2PiklLSMgaHsAuaOqDRMHHxiMgAhTPomVg4uHhg+QQhRUak5RWU4VXUrbVyYQ2NgcYsi6xKys43MgPN4fAAjOqFHqHbK5fL1CyvAGOIGVOA1SEFBpNBQKV7RL4wAC8DxgLgAFrZ-ExKfoXAAacwuKCoYDoFy0inYEiOFxNYIKPCEUgUWEFIU7UUHL5BIA)

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/31621 seems somehow related, but doesn't look like the very same one

**Comment by IlCallo** [comment]
After reading around for a bit, I think I got that `exampleB` is wrong too, because it's solving the problem by ignoring the Promise return, so it doesn't actually wait anything.
I trying also switching the for-in loop with normal for or for-of with no luck.

**Comment by noppa** [comment]
This is not a bug in TypeScript.

exampleA doesn't work because you are giving strings directly to the [`Promise` constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise), which actually expects a function like `new Promise(resolve => resolve(data[key]))`. You could also use `Promise.resolve(data[key])` ([docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve)).

Calling `new Promise('hey')` throws a TypeError, which is why you never see  
`console.log('stuff2-a');` logging. If you are not seeing this error, it's probably more related to your environment (e.g. Jest) than TypeScript.

As you suspected, exampleB doesn't get stuck like exampleA because async & await should actually be in the `exampleB` function for the waiting to happen, not in the `set` function (I mean it can be there _too_ but it doesn't help the calling function).

Btw, since modern JS environments like Chrome, Firefox and Node v. 7+ already support `async`/`await`, you can just remove the type annotations from the example and run it in those to see how they handle the code to quickly check that it's not a TypeScript bug.

**Comment by IlCallo** [comment]
Sorry, `new Promise(data[key]);` is actually pseudo code, I tried to reduce the noise in my code.

In my real code I'm using Firebase JS/TS SDK and that promise is a `set`

**Comment by IlCallo** [comment]
Stripped away TS, still getting silent failing.
Thank you for the advice, gonna search the bug elsewhere
