### ISSUE TITLE
Unable to get this method to compile

### ISSUE THREAD

**Issue by bpasero** [microsoft/TypeScript#33841]
Using TypeScript version 3.6.3, the following does not compile:

```ts
export function assertIsDefined<T>(arg: T | null | undefined): T extends null | undefined ? never : T {
	if (typeof arg === 'undefined' || arg === null) {
		throw new Error('Assertion Failed: argument is undefined or null');
	}

	return arg;
}
```

`Error: Type 'T' is not assignable to type 'T extends null | undefined ? never : T'.`

I want to declare that the method throws in case `arg` is `undefined | null` and otherwise returns `T`. 

What I actually would like to type is something along the lines of:

```ts
export function assertIsDefined<T>(arg: T | null | undefined): T extends null | undefined ? never : arg is T {
	if (typeof arg === 'undefined' || arg === null) {
		throw new Error('Assertion Failed: argument is undefined or null');
	}

	return true;
}
```

But I guess that is just not possible currently.

**Comment by jack-williams** [comment]
With the new assertions you can write:
```ts
function assertIsDefined<T>(arg: T): asserts arg is Exclude<T, null | undefined> {
	if (typeof arg === 'undefined' || arg === null) {
		throw new Error('Assertion Failed: argument is undefined or null');
	}
}

declare const x: string | undefined
assertIsDefined(x);
x // string
```

There is no way to safely infer a conditional type like your first example.

**Comment by bpasero** [comment]
Yeah I thought about that and look forward to that possibility. Will it also work for class members?

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.

It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!

**Comment by bpasero** [comment]
@jack-williams gave a great answer, thanks. And yes, it works with class members too 🚀
