### ISSUE TITLE
err ts(2322)

### ISSUE THREAD

**Issue by cleitonomariano** [microsoft/TypeScript#33890]
Can someone help me? I am using TypeScript, StyledComponent and React with Create React App. This error occurred during the build time and cannot be dismissed.

TypeScript error in ./src/index.tsx(4,1):
Type '{ alt: string; src: string; }' is not assignable to type 'IntrinsicAttributes'.
  Property 'alt' does not exist on type 'IntrinsicAttributes'.  TS2322

./src/components/Image/index.tsx
import React from 'react'
import Styled from 'styled-components/macro'

interface ImageInterface {
  alt?: string | undefined
  src: string
}

const Image = Styled.img`
  max-width: 100%;
`

export default () => ({ alt, src }: ImageInterface) => (
  <Image alt={alt || 'My alternative text'} src={src} />
)

./src/index.tsx

import React from 'react'
import Image from './components/Image'

<Image src="https://cjpatoilo.com/initify/artwork.png" />

./package.json

  "dependencies": {
    "@types/jest": "^24.0.18",
    "@types/node": "^12.7.5",
    "@types/react": "^16.9.2",
    "@types/react-dom": "^16.9.0",
    "@types/react-router-dom": "^4.3.5",
    "@types/styled-components": "^4.1.19",
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "react-router-dom": "^5.0.1",
    "styled-components": "^4.3.2",
    "typescript": "^3.6.3"
  },
  "devDependencies": {
    "enzyme": "^3.10.0",
    "enzyme-adapter-react-16": "^1.14.0",
  },

**Comment by ilogico** [comment]
I'm pretty sure that someone can help you, just not here.
This is an issue tracker for the Typescript compiler, not a help forum.

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
