### ISSUE TITLE
Flattened error messages are still a bit confusing

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/TypeScript#33900]
**TypeScript Version:**  3.7.0-Beta

**Search Terms:** flattened new

**Code**
See example for flattened error reporting
https://www.typescriptlang.org/play/?ts=3.7-Beta&e=182#example/flattened-error-reporting

```ts
class ExampleClass {
  state = "ok"
}

class OtherClass {
  state = 12;
}

let x = { a: { b: { c: { d: { e: { f: ExampleClass } } } } } };
let y = { a: { b: { c: { d: { e: { f: OtherClass } } } } } };
x = y;
```

**Expected behavior:**
```
Type '{ a: { b: { c: { d: { e: { f: OtherClass; }; }; }; }; }; }' is not assignable to type '{ a: { b: { c: { d: { e: { f: ExampleClass; }; }; }; }; }; }'.
  The types of 'a.b.c.d.e.f.state' are incompatible between these types.
    Type 'number' is not assignable to type 'string'.
```
**Actual behavior:**
```
Type '{ a: { b: { c: { d: { e: { f: typeof OtherClass; }; }; }; }; }; }' is not assignable to type '{ a: { b: { c: { d: { e: { f: typeof ExampleClass; }; }; }; }; }; }'.
  The types of '(new a.b.c.d.e.f()).state' are incompatible between these types.
    Type 'number' is not assignable to type 'string'.
```
Its not clear why there is the `typeof` in the first line and especially the `new ...()` in the second line. Maybe there is a less confusing way of expressing these types?

**Comment by j-oliveras** [comment]
I think that is correct because is not the same reference the class that an instance of a class. In your example you reference the class instead of create a new instance. With this you see your expected error:
```ts
class ExampleClass {
  state = "ok"
}

class OtherClass {
  state = 12;
}

let x = { a: { b: { c: { d: { e: { f: new ExampleClass } } } } } };
let y = { a: { b: { c: { d: { e: { f: new OtherClass } } } } } };
x = y;
```

[Playground](https://www.typescriptlang.org/play/?ts=3.7-Beta&ssl=1&ssc=1&pln=12&pc=1#code/MYGwhgzhAECiAeYC2AHEBTAwuK0DeAsAFDTQQAuY560AvNAEQD2A1g8QL7HGiQwDy5ABboATtj75ipClRr0AjACYA3J25EM5aPDr5oYAFz6ARsbzRg56ABNr6awDNjAO3QB3OIlQYJuDtABQYGBapro2gCeehZGptZW+nb6DvrO0G6egiLiODDBBaHEuvSRYUA).

**Comment by AlCalzone** [comment]
Oh right, I interpreted the right hand side as the type of x/y. This also gives the expected error message:
```ts
declare let x: { a: { b: { c: { d: { e: { f: ExampleClass } } } } } };
declare let y: { a: { b: { c: { d: { e: { f: OtherClass } } } } } };
```
