### ISSUE TITLE
Assigning to common property (with different types) of a union type is incorrectly allowed

### ISSUE THREAD

**Issue by eplawless** [microsoft/TypeScript#33911]
**TypeScript Version:**  3.3.3, 3.5.1, 3.6.3, 3.7-Beta

**Search Terms:**
union property assign
discriminated union write

**Code**

```ts
type ExampleUnionType = {
    flag: true,
    value: 10
} | {
    flag: false,
    value: 20
}

let example: ExampleUnionType = {
    flag: true,
    value: 10
};

// inferred type of `example` is `{flag:true,value:10}` here

example.value = 20; // *** FAILS, EXPECTED

function test(input: ExampleUnionType) {

    // inferred type of `input` is `{flag:true,value:10}|{flag:false,value:20}` here

    input.value = 20; // *** DOES NOT FAIL, UNEXPECTED

    // the type of *reading* input.value is `10 | 20`
    // the type of *writing* input.value is also `10 | 20` which is why this is permitted
    // should the type of *writing* input.value be `10 & 20` i.e. `never`?
}

test(example);

// example is now `{flag:true,value:20}`, which is not assignable to `ExampleUnionType`
```

**Expected behavior:**
I should be prevented from putting `example` into an invalid state for type `ExampleUnionType`.

**Actual behavior:**
I was able to put `example` into an invalid state for type `ExampleUnionType`.

**Playground Link:** 
http://www.typescriptlang.org/play/?ssl=26&ssc=37&pln=26&pc=44#code/C4TwDgpgBAogHgQwLZgDYQKoDsCWB7LAFXGgF4oBvAKClqgDNUEBzALimACcBXCAGhp0AbglS92ARgAMVAL5QAPpUG1GLdvVEBnfiqgixEdgCYZsqlXTAoERCnTt4yNJlwFikKOWp0GTNhw8ur4G4lDScgDcFgD0MVA4WPQQnJwQACYcJFB49FAABrbO6PkJWgUUamxcvHyhRtKypQAWKRAWRfYQAHT1XlCmkVBxUABU41AAYgCCAJIAMgDKfLAAGgAKMADChDAAIhb03FgAxsD4WBwQWsAAFIlg3MCOdi7YFx4QAJTKeiOJyVSGSynlyBQeT1KOHK+Uq-lYNX49VYjQUcPUmlQOjqonEpiaUFaaQsvghwF6uLIAykQxG41GUD2AHkYIsoAA5JmEKZzeYrDDsmAbba7A5-eLAVog6Bg0ZpBDpRLMBlkimGMoFaSKan5cUcKWgUF5UYAd04OHOWGVCSwj3JfWhUG0eE1Um1plKJuaOBOzQ1XpA+sdjsgnCQFuAGT1WmaeG4qEykughplxrNFqVKttTzVvCgACNoPktQAyHUJbo9ApYCBCFL5AD8cgskZut06Li+0SoIw76A1WDwJoqVQRQRxhlY+PyKy9Pr9jsH1gQWi0OGYWAQ+f7wBd+ScXXe7hIuqoJwIWjw6G6qDwzHbr3QXaoQA

**Related Issues:** 
Lots of tangential type union bugs, but I wasn't able to find one that displayed this behaviour.

**Comment by RyanCavanaugh** [comment]
Writes through supertype aliases in TypeScript have never been sound. It's the same as if you had written:
```ts
function test(input: { value: number }) {
  // No error
  input.value = 20;
}

test(example);
```

Producing a different write type would make a lot of otherwise-legal code illegal, e.g.
```ts
    // Error, can't assign '10 | 20' to '10 & 20'
    input.value = input.value;
```

**Comment by eplawless** [comment]
Thanks for the quick response :)  I had two quick clarifying questions:

1) Do you think it could be reasonable for that otherwise-legal code to be made illegal?
2) Is there a recommended sound way to achieve this?

The workaround I'm considering, if not, is just marking all fields as `readonly` and forcing the whole object to be replaced each time so we can't encounter unsound behaviour here.

**Comment by eplawless** [comment]
@RyanCavanaugh I'm planning to take a stab at implementing this and providing a PR for feedback, but if you're firmly opposed to this functionality it's probably not a good use of time.  We might also explore a Netflix-internal fork; any guidance on moving forward?

**Comment by eplawless** [comment]
Yeah, we make pretty heavy use of discriminated unions. There's two major sub-patterns I see in 5+ places each just within our project (an internal artist-facing tool for the animation studio).

The first pattern is in guaranteeing properties of a state machine, which is where this would bring the biggest benefit IMO:

```typescript
enum SocketConnectionState {
  DISCONNECTED = "DISCONNECTED",
  CONNECTING = "CONNECTING",
  CONNECTED = "CONNECTED"
}

type SocketState = {
  connection: SocketConnectionState.DISCONNECTED,
  connectionPromise: null,
  ws: null,
  port: null
} | {
  connection: SocketConnectionState.CONNECTING,
  connectionPromise: Promise<void>,
  ws: null,
  port: null
} | {
  connection: SocketConnectionState.CONNECTED,
  connectionPromise: null,
  ws: WebSocket,
  port: PortNumber
};
```

The second is in defining shared message types for some client/server communication, which I can sanitize and post here if it helps, but there's a lot of shared field names with different types.

**Comment by bysdxt** [comment]
Emmm....I also have similar needs:
```ts
declare var StrVar: string;
declare var x: { a: true, b: string } | { a: false, b: number }
const { a, b } = x;
if (a) StrVar = b;
```
`b` should be known as string type in after `if (a)`

**Comment by CraigMacomber** [comment]
I see this is closed as completed, however the original example in this thread seems to have unchanged behavior.

What was completed that resulted in this being closed?

I found this thread when looking into [playground](https://www.typescriptlang.org/play/?#code/JYOwLgpgTgZghgYwgAgILIN4Chm+QNzgBsBXCALmRBIFsAjaAbiwF8tRJZEUAhTHPIVIVkAZzBRQAc2ZsYJEAjDAA9iDEQwANWJkAFCBUATEegA+yHgBoClavWjIL4ySCkBKSvhXAj-PFTGEAB0QmTIALwEslgIauLIcJToURgEuiIAjMgszKKaOsJ6cDYARAAape7McSAJYSL2DFCRiaEZjMgA9F3IFaWJolS0zUA)

```typescript
interface A {
    value: number;
}
interface B {
    value: string;
}
function setValue(node: A | B, v: number | string): void {
    node.value = v;
}
const a: A = { value: 1 };
setValue(a, "X");
const value: number = a.value; // "X" as number
```

This sounds like the same issue discussed in this thread, which sounds like maybe it's working as intended due to TypeScript favoring completeness over soundness in this case, however the "closed as completed" status is confusing me (I was expecting "won't fix" or "as designed" not "completed". This makes me thing that possibly this behavior isn't intended and is a regression of the fix which was made to complete this?


Looking at the handbook [it says](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#working-with-union-types):

>  TypeScript will only allow an operation if it is valid for every member of the union.

The behavior I'm observing, and the behavior discussed in this thread seem to violate that.

Thus I think the handbook and the compiler disagree about how this case is supposed to behave. Therefor I think this issue should be reopened until they agree, and if the resolution is to update the handbook, the resolution should be clarified in this thread with more detail than "closed this as completed".

**Comment by RyanCavanaugh** [comment]
> I see this is closed as completed, however the original example in this thread seems to have unchanged behavior.

See https://github.com/Microsoft/TypeScript/wiki/FAQ#this-is-closed-but-should-be-open-or-vice-versa

**Comment by RyanCavanaugh** [comment]
The Handbook is not intended to be a replacement for a language spec; the "it's valid if it's valid for each thing in the union" is a good heuristic that works 95%+ of the time. The goal of the Handbook is for someone to read it and have a good understanding of TS, not a comprehensive ability to predict 100% of language behavior
