### ISSUE TITLE
TypeScript 3.7 — LanguageService.getEmitOutput returns an empty result

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#33936]
**TypeScript version**: 3.7.0-dev.20191010

We're trying to build VS Code using TS 3.7. As part of this, we use TypeScript `LanguageService.getEmitOutput` method to request the emitted `d.ts` of various files: https://github.com/microsoft/vscode/blob/363b9769412fea0d9aef07fa1801371c14d72741/build/monaco/api.ts#L619

WIth TS 3.6, `getEmitOutput`ends up returning a result. However with TS 3.7, it returns an empty array starting on one file: `vs/editor/common/standalone/standaloneBase`

/cc @DanielRosenwasser

**Comment by mjbvz** [comment]
A few other observations:

* `getEmitOutput` does work correctly for a few files before failing.
*  If I set `emitOnlyDtsFiles` to `false`, I do see the js file being output for `standaloneBase` but not a `d.ts` file

**Comment by sheetalkamat** [comment]
Your tsconfig doesn't have "declaration" enabled and hence its not generating it. 11fd654cf997f6d031c7437fcb4c0b6e0862264e changed the way emitOnlyDts works because I had mixed forcing d.ts emit to be always generated with API `emitOnlyDts` and that could be why you see it. Currently `forceDts` is internal but do you mind making that method as any and passing that as true to see if that resolves the issue?

**Comment by mjbvz** [comment]
Thanks. If I monkey patch the TS source to set `forceDts` to true, It does seem to work. I can't figure out how to enable `forceDts` from our code however
