### ISSUE TITLE
Did `runtests` copy all test files to tests/cases/compiler/ folder?

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#3398]
I'm writing tests for my fork and notice the `currentSourceFile.filename` says my file is under `/tests/cases/compiler` instead of in the sub-folder I originally put it in.  I wouldn't figure it out in the jakefile.

The file I have was located in `tests/cases/compiler/extjs/TableTennis/Equipments/BladeMaterial.ts` and the `currentSourceFile.fileName` is `tests/cases/compiler/BladeMaterial.ts`.  The output file did go to `tests/baselines/local/BladeMaterial.ts`.

Thanks

**Comment by danquirk** [comment]
There's some stuff hardcoded assuming tests/cases/compiler doesn't have child folders (since it never has before). If you put your tests under tests/cases/conformance you'll probably see more what you expect. The relevant code is not in the Jakefile but in src/harness/compilerRunner.ts as that defines how the raw source files that are our tests are dynamically built up into the describe/it calls that mocha requires and how to check/baseline the results.

**Comment by unional** [comment]
How do I run the code in conformance correctly? I move the test file there and I got call stack overflow.

**Comment by unional** [comment]
btw, it does keep the path in the conformance folder.

**Comment by unional** [comment]
When I put the files in conformance, the test runs but at the end it has an error in "after all" hook saying call stack overflow.

**Comment by DanielRosenwasser** [comment]
Are you using the `tests=blahblah` flag when running? I know this is something we've ran into as well but I don't know the details.

**Comment by unional** [comment]
Yes.

**Comment by mhegazy** [comment]
This is already tracked by #3273
