### ISSUE TITLE
(suggestion) Array index type enforcement.

### ISSUE THREAD

**Issue by ttowncompiled** [Microsoft/TypeScript#3399]
Currently, we can define an interface for an Array that is indexed by either string, number, or both. However, there is no way to define an Array that is only indexed by number or only indexed by string.

For instance,
```
interface StringArray {
  [key: string]: string;
}

var sarr: StringArray = {'a': 'a', 0: 'b'};
var s: string = sarr[1];
s[2] = 'string';
```
None of these expressions will generate an error. 

I think it would be very useful if we could enforce that an array is only indexed with the provided type(s).

**Comment by mhegazy** [comment]
Arrays are regular objects. all JS objects can be indexed using string. as a matter of fact engines only index using strings and for numbers, you get the toSttring on the indexer then use that to evaluate, so something like:
```js
var x = [1];
console.log(x[0] === x["0"]);  // true
```

The property type lookup order reflects that, if you are using a number to index into an object, the numeric indexer is first checked, if it does not exist and a string indexer is found it will be used instead.

**Comment by ttowncompiled** [comment]
So I guess there wouldn't be any value in conveying to someone that no element of an array can be accessed by passing in a number?

**Comment by ttowncompiled** [comment]
Or that all elements of an array are accessible by number?

**Comment by danquirk** [comment]
The problem is that all objects by default do have this indexer behavior. So you'd likely need some new syntax here to say what can't be indexed by. While there are some circumstances that might be useful it's fairly rare which means we'd be adding a complexity cost to the language (for users, for our codebase, etc) for what is very much a corner case. Designed in isolation we probably would make indexing arbitrary things by a number an error, but that would break existing JavaScript and so we need to model that.

_Or that all elements of an array are accessible by number?_

You can use a numeric indexer for that rather than a string indexer.
