### ISSUE TITLE
Compiler API

### ISSUE THREAD

**Issue by n2westman** [Microsoft/TypeScript#3406]
I know it's possible to build a linter by getting a file's AST - 

How do I get from the AST to printing out a JavaScript file? I want to make modifications to the AST post parse and then print out the result to a file.

**Comment by DanielRosenwasser** [comment]
You may run into issues here because our emitter usually expects parent references to be set up and a `pos`/`end` that maps to a corresponding source file's text.

That said, I think you can work through [this example](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#a-minimal-compiler) and edit `program`'s SourceFile trees.

Out of curiosity, what are you trying to work on?

**Comment by n2westman** [comment]
I'm working on adding run-time contracts to the language as a research project. Kinda like typed racket.

I've built a scraper which builds basic interface objects and a little dsl that does structural reflection on objects. I basically want to inject some JS code that checks the types of parameters of a function and the output of a function at runtime to make sure that we're actually returning proper objects.

**Comment by n2westman** [comment]
As a follow up, is there functionality to merge two "source file" objects?

**Comment by DanielRosenwasser** [comment]
You mean like concatenate them? Not built in, though, you could use the `--out` compiler option to do something along those lines.

**Comment by mhegazy** [comment]
looks like this issue has been addressed. closing. please reopen if there is more information needed.
