### ISSUE TITLE
Optional chaining disregards expected order of operations

### ISSUE THREAD

**Issue by connorjclark** [microsoft/TypeScript#34109]
**TypeScript Version:**  3.7.0-dev.20191011

**Search Terms:** optional chaining, ternary, order

**Code**

```ts
function main(opts?: { test: boolean }) {
    console.log('opts', JSON.stringify(opts))
    console.log('opts?.test', opts?.test); // undefined
    const val = opts?.test ? 1 : 0; // val type is 1 | 0
    console.log('opts?.test ? 1 : 0', val); // 0
}

main({ test: false })
main({ test: true })
main()
```

**Expected behavior:**

`val` should always be `1` or `0`.

**Actual behavior:**

`val` can be `1`, `0`, or `undefined`.

Output:
```
opts {"test":false}
VM84:5 opts?.test false
VM84:7 opts?.test ? 1 : 0 0
VM84:4 opts {"test":true}
VM84:5 opts?.test true
VM84:7 opts?.test ? 1 : 0 1
VM84:4 opts undefined
VM84:5 opts?.test undefined
VM84:7 opts?.test ? 1 : 0 undefined
```

Note, TS claims the type of `val` is `1 | 0`:

![image](https://user-images.githubusercontent.com/4071474/66709353-f3642200-ed16-11e9-97fe-1c28ce741a87.png)

The desired result can be achieved by doing `(opts?.test) ? 1 : 0`.

**Playground Link:** http://www.typescriptlang.org/play/?ts=3.7-Beta&ssl=1&ssc=1&pln=12&pc=1#

**Related Issues:**

**Comment by j-oliveras** [comment]
As a note, [babel converts this with expected behaviour](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAWwIYzACjgBygZwH4AuRAb0SgFN8pSAjOOAGytSQF8BKcgKEQGIICfCyoA6ZnADmmAOS4CcgDSIAUgGUA8gDlxtAE4ZpMYAE9sefFy79BwsKNaSZ8xUXHVaKxO8KeaKC4AbkQAejDEcAATKmAMKmi7AQdaRAA3VGZEAF5fK38vKERCRABGRFIABlCIjKzKMxwqRBh8csQAH0Qq5KERMRdZBQKAtNKK6p9M5hDwyN6OXl40DEwKItJgLPwW7hX0LA3A0igDED3bVawuIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.6.4&externalPlugins=%40babel%2Fplugin-proposal-optional-chaining%407.6.0%2C%40babel%2Fplugin-transform-typescript%407.6.3).

The babel result is equivalent to add parenthesis around `opts?.test`.

Probably optional chaining will fail in others cases that it no preserve the expected order of operations?

// CC @rbuckton did optional chaining needs to emit a parenthesis around its downlevel if used with other operators?

**Comment by jcalz** [comment]
[Playground link](http://www.typescriptlang.org/play/?ts=3.7-Beta#code/GYVwdgxgLglg9mABAWwIYzACjgBygZwH4AuRAb0SgFN8pSAjOOAGytSQF8BKcgKEQGIICfCyoA6ZnADmmAOS4CcgDSIAUgGUA8gDlxtAE4ZpMYAE9sefFy79BwsKNaSZ8xUXHVaKxO8KeaKC4AbkQAejDEcAATKmAMKmi7AQdaRAA3VGZEAF5fK38vKERCRABGRFIABlCIjKzKMxwqRBh8csQAH0Qq5KERMRdZBQKAtNKK6p9M5hDwyN6OXl40DEwKItJgLPwW7hX0LA3A0igDED3bVawuIA)?
