### ISSUE TITLE
Is it possible for a function to return a list of values?

### ISSUE THREAD

**Issue by Vadorequest** [Microsoft/TypeScript#3418]
I'm wondering if it is possible to return a list of values, something like:

```js
function x(){
  return 1,'dsdsq', 45678.45;
}
```

The aim is to init several variables at the same time, it exists in other languages but I can't find it in TS. Thanks!

**Comment by zhongsp** [comment]
Maybe you could use tuple types:

```ts
function x(): [number, string, number] {
    return 1, 'dsdsq', 45678.45;
}

var tuple: [number, string, number] = x(),
    t0 = tuple[0],
    t1 = tuple[1],
    t2 = tuple[2];
```

**Comment by kitsonk** [comment]
Largely I assume it isn't present in TypeScript, because it isn't present in JavaScript/EcmaScript and the intent of TypeScript is not to "break" JavaScript, but be able to emit valid JavaScript, which would be hard to do.

As a way of solving this in a "JavaScript way", ES6 is adding array destructuring assignment and TypeScript allows you to utilise this feature now.

```ts
function x() {
    return [ 1, 'dsdsq', 45678.45 ];
}

let [a, b, c] = x(); /* a = 1, b = 'dsdsq', c = 45678.45 */
```

TypeScript allows you to destructure arrays, even when targeting non-ES6.

**Comment by RyanCavanaugh** [comment]
If you combine the comments so far, you'll end up at an ideal solution:
```ts
function x(): [number, string, number] {
    return [ 1, 'dsdsq', 45678.45 ];
}

// a: number, b: string, c: number
let [a, b, c] = x(); /* a = 1, b = 'dsdsq', c = 45678.45 */
```

We can't change the existing JS syntax since the comma operator already has a different meaning here.

**Comment by Vadorequest** [comment]
Thanks!
