### ISSUE TITLE
Conditional type extends check ignores readonly constraint

### ISSUE THREAD

**Issue by yyx990803** [microsoft/TypeScript#34274]
**TypeScript Version:**  3.7.0-beta

**Search Terms:** conditional type readonly

**Code**

```ts
interface A {
    foo: number
}

interface B {
    readonly foo: number
}

type C = A extends B ? true : false
type D = B extends A ? true : false
```

**Expected behavior:**

At least one of `C` and `D` is false. (I expect `C` to be false since `B` is a narrower type)

**Actual behavior:**

Both are true.

**Playground Link:** http://www.typescriptlang.org/play/?ts=3.7-Beta&ssl=1&ssc=1&pln=10&pc=36#code/JYOwLgpgTgZghgYwgAgILIN4Chm+TAewIC5kQBXAWwCNosBfLLUSWRFAIUxzygjgAmBEABsAnviKkKNOoyxgxABxQBhZAF40yCAA9IIAQGdkXAPzIwUcilLwRRiAuUoAIptM79EQyfQWrG2Q7OAcIIA

**Related Issues:**

**Comment by fatcerberus** [comment]
> `B` is a narrower type

In theory the read-only type would be *wider*, but even *that* isn't true.  Both conditionals evaluate to `true` because `extends` is an assignability question and both `A` and `B` are assignable to each other: `readonly` does not affect assignability of the containing type in any way.  See here (https://github.com/microsoft/TypeScript/pull/6532#issuecomment-174356151) for the rationale on why that is.

**Comment by yyx990803** [comment]
So here's a tricky situation this behavior leads to:

``` ts
```

**Comment by ahejlsberg** [comment]
This is effectively a design limitation. We'd like to do better, but changing `readonly` properties to not be assignable to unannotated properties ends up being a massive breaking change because so many types (e.g. on DefinitelyTyped) that effectively are readonly are written without `readonly` annotations.

**Comment by yyx990803** [comment]
Thanks for the explanation.
