### ISSUE TITLE
private and protected methods incompatible in derived class

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#3435]
I have read the thread about keeping private property and methods on prototype `MyClass.prototype.privateMethod` rather than pure private in closure.  I understand the reason behind it.

However, if I subclass it with a different signature, the compiler will complain.
I understand that this would probably resulting in `by design`, but it is not very good in practice because if I'm going to write a complex system in TypeScript, with several level of inheritance with private and protected members, then I'll ended up with *property pollution* that my derived class would have less and less freedom in creating properties and methods with clean and simple names.

This would get even worst if you take mixins with private and protected members.

I saw there was a flag that will change tsc to create members that are actually private, is that in current build?

Thanks,

**Comment by mhegazy** [comment]
>  with several level of inheritance with private and protected members, then I'll ended up with property pollution that my derived class would have less and less freedom in creating properties and methods with clean and simple names.

This is more or less the intention; since the private lives on the prototype, an extending class can step on it by defining a property with the same name. The compiler will grantee that any extending class does not accidentally step on a private property. obviously you do not want subclasses accessing the private either, this is where protected comes in play.

> I saw there was a flag that will change tsc to create members that are actually private, is that in current build?

I do not think such flag exists.
