### ISSUE TITLE
conditional extends fails on optional properties

### ISSUE THREAD

**Issue by Gregroam** [microsoft/TypeScript#34409]
**TypeScript Version:**  3.6.3

**Search Terms:** extends conditional optional

**Code**

```ts
type SwapStringNumber<T> = { [K in keyof T]:
  T[K] extends number ? string :
  T[K] extends string ? number :
  never
}

type Foo = {
  a: string;
  b: number;
  c?: string;
  d?: number;
}

type FooSwapped = SwapStringNumber<Foo>;
```

**Expected behavior:**
`FooSwapped` should be 
```
type FooSwapped = {
    a: number;
    b: string;
    c?: number | undefined;
    d?: string | undefined;
}
```

**Actual behavior:**
`FooSwapped` is 
```
type FooSwapped = {
    a: number;
    b: string;
    c?: undefined;
    d?: undefined;
}
```

**Playground Link:**  http://www.typescriptlang.org/play/?ssl=14&ssc=41&pln=1&pc=1#code/C4TwDgpgBAyg7gQzDYAnAlgOwOYDkCuAtgEYSoA8AKgHxQC8UA3lANoDSUWUA1hCAPYAzKJQC6ALgBQUEe1FQIAD2ARMAEwDOUTEVKooAfiga0WbFCkzKchctWbjpnIe26yF6dogA3MpIC+kpKgkFAAYvz89EyeCOKOGDgA3J7E8TokZCkyAMYG8SaJ2NlQavmumagpgcHg0BH88EiQatFNyE54bhQN1ElAA

Only if I change the conditionals to this 
```
type SwapStringNumber<T> = { [K in keyof T]:
  T[K] extends number | undefined ? string :
  T[K] extends string | undefined ? number :
  never
}
```
do I get the expected result

**Comment by jcalz** [comment]
The compiler is working as intended.   `string | undefined` does not extend `string`, and `number | undefined` does not extend `number`:

```ts
type FooC = Foo["c"]; // string | undefined
type Check = FooC extends string ? number : never; // never
```

Any optional properties will therefore fail to match your conditional and will return `never` which becomes `undefined` (since `never | undefined` is `undefined`).  


There are likely other ways of writing `SwapStringNumber<T>` that actually work for all your intended use cases, whatever they are (e.g., do you want `SwapStringNumber<{a: string | boolean}>` to become `{a: number | boolean}` or do you really want `{a: never}` as your definition above implies?) but that's in the realm of Stack Overflow questions or other forums.  Here, it suffices to say that this is not a compiler bug.  Good luck!
