### ISSUE TITLE
Type 'Function' provides no match for signature...

### ISSUE THREAD

**Issue by frangio** [microsoft/TypeScript#34540]
**TypeScript Version:**  3.7.0-dev.20191017

**Search Terms:** function match for signature

**Code**

```ts
const x: Function = () => 4;
const y: (...args: unknown[]) => unknown = x;
```

**Expected behavior:**

Assigning `x` to `y` should be possible. Is there something I'm missing? Any type of value `Function` has some signature even if it's unknown, and the signature `(...args: unknown[]) => unknown` seems to be the most general signature possible and it should implicitly apply.

**Actual behavior:**

Does not compile.

```
Type 'Function' is not assignable to type '(...args: unknown[]) => unknown'.
  Type 'Function' provides no match for the signature '(...args: unknown[]): unknown'.
```

**Playground Link:** https://www.typescriptlang.org/play/?ts=Nightly#code/MYewdgzgLgBAHgLhgMQK5mFAluGBeGACgEp8A+GAFgG4AoUSWATyUIDoOBDAJwHMIknMEwDaAXVJ4KQpvnjUgA

**Related Issues:**  did not find anything

Note: this is preventing me from correctly typing a decorator that can be used for both methods and accessors or function properties because type narrowing through `instanceof Function` does not result in a type with a signature.

**Comment by frangio** [comment]
Okay, that's interesting. It's the kind of thing I feared I was missing.

Is there any way to narrow the type of a value to one with a signature?

**Comment by RyanCavanaugh** [comment]
No; you'd need a type assertion since there's nothing at runtime to match a parameter type against

**Comment by frangio** [comment]
It seems that `typeof Object.create(Function) === 'object'`, whereas otherwise any function `fn` has `typeof fn === 'function'`.

Would it be possible for the type system to use this information? Are there any other cases where calling an instance of `Function` results in a type error?

**Comment by fatcerberus** [comment]
Note that `(...args: unknown[]) => unknown` isn't actually a "most general signature" because `unknown` is a true top type (unlike `any`) and functions are contravariant in their parameter types.  Particularly when `strictFunctionTypes` is enabled.  If a function type says its parameter is `unknown`, that means--if we're only looking at the types--it can handle any type of input at all, so you can only safely assign it another function that accepts an `unknown`.

`(...args: never) => unknown` (yes, that's a legal signature!) would be closer to being a "top type for functions" (but of course `Function` is *still* not assignable to that 🙁)
