### ISSUE TITLE
noImplicitAny setting reversed

### ISSUE THREAD

**Issue by DirtySoc** [microsoft/TypeScript#34541]
**Search Terms:**
noImplicitAny
implicit null type assignment

**Code**
```ts
let implicitNullType = null; // The noImplicitAny option is TRUE!
// The inferred type of implicitNullType should be null.

implicitNullType = 12; // This should not be allowed.
```

**Expected behavior:**
A variable set to null should get inferred as type null when noImplicitAny option is TRUE.
**Actual behavior:**
When the noImplicitAny option is TRUE a variable set to null gets the type any. This is opposite of expected behavior.

**Playground Link:** 
https://www.typescriptlang.org/play/#code/DYUwLgBAlgtgDsKBjKYByBXYwAqBPOECAXggDstgBuCAelohwAsiyB7ASXkRTAEEyeCGzhgobMtADOjAEoBVAKIBCAFD1GLaGQBmIAE76QAEwhgCRNjujdkqTNnyEIUpmyymARq0oA6VbAIduiUTkSkAIwATDQazFAyru7ApuyQ3hAAhthsAO4mvkA

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
This isn't a bug and this isn't an `any`. `let`s initialized with `undefined` or `null`, it becomes a control-flow-tracked type that follows subsequent assignments. These assignments can be of any type, but from a *read* perspective this value always has an assigned, non-`any` type, and you can't create any of the usual problems of `any` from this kind of variable.

```ts
declare function fn(s: string): void;
let s = null;

s = "";
// OK
fn(s);

s = 10;
// Error
fn(s);
```

Again, you can't observe any novel unsound behavior due to this behavior.
