### ISSUE TITLE
Enhance recursive type

### ISSUE THREAD

**Issue by Himself65** [microsoft/TypeScript#34555]
**TypeScript Version:**  3.7.0-dev.20191018

**Search Terms:**
- recursive type
- #33050

**Code**
Example:

```ts
type UnwrapRef<T> = T extends Ref<infer V>
  ? UnwrapRef<V>  // <-- this line will throw error
  : T extends Array<infer V>
    ? Array<UnwrapRef<V>>
    : T extends BailTypes
      ? T // bail out on types that shouldn't be unwrapped
      : T extends object ? { [K in keyof T]: UnwrapRef<T[K]> } : T
```

**Expected behavior:**

```ts
export type UnwrapRef<T> = {
  ref: T extends Ref<infer V> ? UnwrapRef<V> : T
  array: T extends Array<infer V> ? Array<UnwrapRef<V>> : T
  object: { [K in keyof T]: UnwrapRef<T[K]> }
  stop: T extends Ref<infer V> ? UnwrapRef<V> : T
}[T extends Ref
  ? 'ref'
  : T extends Array<any>
    ? 'array'
    : T extends BailTypes
      ? 'stop' // bail out on types that shouldn't be unwrapped
      : T extends object
        ? 'object' : 'stop']
```
they are the same effects, but why couldn't I code like the first example?

**Actual behavior:**

```bash
Error:(14, 5) TS2315: Type 'UnwrapRef' is not generic.
```

**Playground Link:** 

https://gist.github.com/Himself65/dea93908f17d25093938fcedc68eabd3

**Comment by nmain** [comment]
Possibly related to https://github.com/microsoft/TypeScript/issues/33868

**Comment by HerringtonDarkholme** [comment]
This is expected behavior. Conditional type alone doesn't guarantee recursive type alias. Type alias must have one layer of indirection, e.g., as field of interface, array/tuple's item type, as listed in #33050 .

In this example, `UnwrapRef` directly uses itself in the true branch of conditional type. This fails to meet the "indirection" requirement of recursive type alias.

Though, I think the error reported here should be "cyclic type alias" rather than "type is not generic"

**Comment by RyanCavanaugh** [comment]
Thanks @nmain / @HerringtonDarkholme ♥
