### ISSUE TITLE
Array.prototype[Symbol.unscopables] is not a function

### ISSUE THREAD

**Issue by kazatsuyu** [microsoft/TypeScript#34610]
**TypeScript Version:** 3.7.0-dev.20191018

**Search Terms:**
- Array
- @@unscopables

**Code**

```ts
const x = [][Symbol.unscopables];
console.log(x.copyWithin);

const y = [][Symbol.unscopables]();
console.log(y.copyWithin);
```

**Expected behavior:**
`x.copyWithin` occurs no error, and `[][Symbol.unscopables]()` occurs type error.

**Actual behavior:**
`x.copyWithin` occurs type error, and `[][Symbol.unscopables]()` occurs runtime exception.

**Playground Link:** 
http://www.typescriptlang.org/play/?ts=Nightly&ssl=6&ssc=1&pln=1&pc=1#code/MYewdgzgLgBAHjAvDA2gXRQZQJ4FsBGIANgHQCukoADgIb5ECmEaA3ALABQokxDJRIAOYAKOCWrYA6gEsoAC2lgAlOw6du0GNiSoMOAsXKUQtekzTCV68BF78hw7OJNTZC5aqA

**Related Issues:**

**Comment by NicholasLYang** [comment]
Is this because `[Symbol.unscopables]` is not a function? According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/unscopables), `object[Symbol.unscopables]` should be an object. I removed the parens on [this line](https://github.com/microsoft/TypeScript/blob/1cbbe288ac6e67f1b50e0a239ae36fe0105d4458/src/lib/es2015.symbol.wellknown.d.ts#L74) and it appeared to fix the problem. 

Building works correctly with the change but my IDE complains: `TS2717: Subsequent property declarations must have the same type`. I'm not really sure where the other property declarations of `Symbol.unscopables` are. Could I get a point in the right direction? Also should I change all the tests that use `[Symbol.unscopables]()` to `[Symbol.unscopables]`?

**Comment by ExE-Boss** [comment]
@rbuckton This is still broken.
