### ISSUE TITLE
Specialized signature yields incorrect intellisense in playground

### ISSUE THREAD

**Issue by wardbell** [Microsoft/TypeScript#3462]
At least it seems that way to me.

Below  is the code I entered in the [playground](http://www.typescriptlang.org/Playground) based on your documentation for [specialized types] (http://www.typescriptlang.org/Content/TypeScript%20Language%20Specification.pdf).

If you hover over the `el` variable in 

    var el = foo.createElement('div')

intellisense reports the type is "HTMLSpanElement"

That's wrong. It should be "HTMLDivElement".  The generated JS does indeed report that the node type is "DIV" (go ahead and run it).

The intellisense seems to always report  "HTMLSpanElement" no matter the value of the `tagName`.

# The Code

```
interface IFoo {
	createElement(tagName: 'div'): HTMLDivElement;
	createElement(tagName: 'span'): HTMLSpanElement;
	createElement(tagName: 'canvas'): HTMLCanvasElement;
	createElement(tagName: string): HTMLElement;
}

class Foo implements IFoo {
	createElement(tagName: string) {
		if (tagName === 'div') { return document.createElement('div'); }
		if (tagName === 'span') { return document.createElement('span'); }
		if (tagName === 'canvas') { return document.createElement('canvas'); }
		return document.createElement('hr'); // something else
	}
}

var foo = new Foo(); 

// HERE WE GO
var el = foo.createElement('div')
document.body.innerText = 'el is ' + el.nodeName;
```

**Comment by wardbell** [comment]
Here's the intellisense image:
![2015-06-09_18-45-25](https://cloud.githubusercontent.com/assets/129061/8073285/bb229c4a-0ed7-11e5-9ac3-4eef758bdb4c.png)

**Comment by wardbell** [comment]
The code variation below yields more reasonable intellisense
![2015-06-09_18-45-25](https://cloud.githubusercontent.com/assets/129061/8073415/843b5f1c-0ed9-11e5-93fa-b1dcf1933cdf.png)

so not *everything* feels broken.

I was mildly disappointed that it didn't use the information in the specialization string to determine that the type of the element had to be a "number". But at least it isn't wrong.

# The Code

```
interface IFoo {
	createElement(tagName: 'number'): number;
	createElement(tagName: 'string'): string;
	createElement(tagName: string): any;
}

class Foo implements IFoo {
	createElement(tagName: string): number | string | boolean {
		if (tagName === 'number') {return 42}
		if (tagName === 'string') { return "some string"}
		return true; // something else
	}
}

var foo = new Foo(); 

// HERE WE GO
var el = foo.createElement('number')
document.body.innerText = 'el is ' + typeof el;
```

**Comment by danquirk** [comment]
This is a common source of confusion. You actually have to repeat the signatures you want in the implementing class in order to get the behavior you want. What you have currently is saying 'here is a type that defines a set of signatures' (IFoo) and then with an implements clause you ask the compiler 'make sure this thing (Foo) conforms to the set of signatures in this other thing (IFoo)'. The implements clause doesn't automatically push all the signatures into the implementing type. So you want Foo to look like:
```ts
class Foo implements IFoo {
	createElement(tagName: 'div'): HTMLDivElement;
    createElement(tagName: 'span'): HTMLSpanElement;
    createElement(tagName: 'canvas'): HTMLCanvasElement;
	createElement(tagName: string): HTMLElement;
    createElement(tagName: string) {
        if (tagName === 'div') { return document.createElement('div'); }
        if (tagName === 'span') { return document.createElement('span'); }
        if (tagName === 'canvas') { return document.createElement('canvas'); }
        return document.createElement('hr'); // something else
    }
}
```
What's happening in this case where you haven't done that is the compiler checks that ```Foo``` satisfies the contract which ```IFoo``` specifies. In order to do that it has to infer a return type for ```Foo.createElement``` by gathering up all the return values in ```Foo.createElement``` and picking a best common type (leading to the fact that ```Foo.createElement``` is a string->HTMLSpanElement typed function). Now the compiler checks if that satisfies the signatures in ```IFoo```, which it does, so everything is accepted.

**Comment by wardbell** [comment]
Thanks for the explanation, @danquirk.  Maybe it belongs in the documentation as well? I just re-read it and the requirement to re-express the signatures in the implementation is neither stated nor illustrated.

>It's not clear to me why the transpiler let this through without error. Nor is it clear to me why you say that `string -> HTMLSpanElement` is the best common type. None of the other 3 signatures return this type or a type derived from it. If ANY type was a common type it would be the base type `HTMLElement`.

FWIW, let's emphasize the word ***all*** in your statement "*push \_all\_ the signatures into the implementing type*".  When I was confirming your example, I omitted the final declaration

     createElement(tagName: string): HTMLElement;

thinking it unnecessary because the method with the implementing method body has the same signature (except for the return):

     createElement(tagName: string) { ... }
   
I wonder how many will find this intuitive? Not many if, as you say "*this is a common source of confusion.*".  They'll be lucky to learn about it if they happen to search here. Better to learn about it in the spec.

Perhaps this should be re-opened as a documentation issue? I'll leave that to you.

Thanks again for your quick and accurate response.

**Comment by danquirk** [comment]
It's not specific to specialized signatures that's why it's not in that spec section. 8.1.1 (Class Heritage Specification) for example says:

_The implements clause of a class provides a mechanism to assert and validate that the class contains the appropriate sets of instance members, but otherwise it has no effect on the class type._

And yes, the fact that the implementation signature does not count as an overload signature is also a common source of confusion. Trust me we don't like common sources of confusion ;) The problem is (or was) it's not uncommon that your actual implementation signature is full of ```any```s. For example consider the overload set:
```ts
function foo(x: string): string;
function foo(x: number): number;
```
What is the implementation signature? For a long time your only option was:
```ts
function foo(x: any): any { 
   if(typeof x === "number) {
   // and so on
}
```
Today we allow you to use union types to be more precise but there's plenty of existing code with ```any``` in the implementation signature as well as reasons to still use it. So if we automatically included the implementation signature in the overload set then now your overloads are useless because any value passed to ```foo``` will fall back to the last overload which takes ```any```. This would also affect your ability to extract an interface or extend from types that use overloads. So sometimes you end up having to 're-state' a signature that it feels like you've already stated which I agree does feel awkward but there are good reasons for it.

This kind of stuff is in the spec but the simple/readable explanation is better suited to the wiki/handbook and that is something I'll double check is covered well and open a bug for some clarification on the topic if it's missing.

**Comment by wardbell** [comment]
Thanks, Dan. It does make sense and it is H2O for a thirsty dev. The wiki and gradual accumulation of community lore will help.

It is damned noisy though. I suppose that is the nature of strong typing.

So where is the benefit? As you say, I could have just declared the simplest possible signature that covers the bases from a type checking perspective. I could even have used `any` and called it a day.

As I played around, though, I realized that having all of those signatures enriched the intellisense immensely. I could communicate much more specifically about what each signature does and why.

It may help to call attention to this as a reason (THE reason?) for the multiple declarations. Then devs have a basis for choosing a verbose declaration (for public facing, well documented APIs) versus more terse declaration (sufficient for type safety of internal APIs). It wont feel so arbitrary.

Thanks again for your effort in clarifying this feature. I expect many other devs will be grateful too.

And now I rhink we are done 😊
