### ISSUE TITLE
enum vs const enum - order matters

### ISSUE THREAD

**Issue by zhuravlikjb** [microsoft/TypeScript#3466]
This code is compiled okay:

``` (typescript)
enum W {
    A = 1 
}

const enum Q {
    A = 1,
    B = W.A | A
}
```

This code produces a compiler error:

``` (typescript)
const enum Q {
    A = 1,
    B = W.A | A
}

enum W {
    A = 1 
}
```

Seems not to be very nice to depend on declarations order in this case.

**Comment by zhuravlikjb** [comment]
The same happens even for two const enums.

```
const enum Q {
    A = 1,
    B = W.C | A
}

const enum W {
    C = 1,
    A = C | Q.A 
}
```

**Comment by vladima** [comment]
An open question here: what behavior should we have in case of cycles: 
```typescript
const enum A {
    X = B.X
}

const enum B {
    X = A.X
}
```

should it be an error or should we implicitly break the cycle and use some default value instead of the actual one? 

Current behavior does not have this problem and is consistent across const and regular enums. I'm going to convert this issue into the suggestion to alter existing behavior and pick reasonable strategy to deal with cycles.

One this that is definitely wrong in current implementation is error message, it is not really helpful:
```typescript
const enum A {
    X = B.X // in 'const' enum declarations member initializer must be constant expression
}

const enum B {
    X = 1
}
```
I'll file a separate issue to fix the message

**Comment by vladima** [comment]
Error message issue #3963

**Comment by RyanCavanaugh** [comment]
This is just what we want to happen
