### ISSUE TITLE
Explicit boolean type not honored without cast

### ISSUE THREAD

**Issue by niedzielski** [microsoft/TypeScript#34691]
**TypeScript Version:**  3.7.0-beta

**Search Terms:** type narrowing, inference, casting, typecasting, control-flow

**Code**

```ts
const cast: boolean = <boolean>false
const uncast: boolean = false

const record: Record<keyof any, {}> = {}
record.a = {...(cast && {})} // OK.
record.b = {...(uncast && {})} // Error: uncast inferred as false.
```

**Expected behavior:** If a variable is explicitly typed, that type should always be honored.

**Actual behavior:** Type is inferred from actual boolean value without even `<const>`.

**[Playground Link](https://www.typescriptlang.org/play/?ts=3.7-Beta&ssl=1&ssc=1&pln=7&pc=1#code/MYewdgzgLgBMCG0BcMBGIQBsCm8wwF4YAedLXMAPgDN5MJsAoUSWAVzAWTQxz0Ji16TZuGgwATtlASAJigBK0kHOIBrbAE8Q1GHk0AaGAG8AvpQFnGUmbIB08S3ecAKLrABkHk6YCUpmAB6QJgAeQBpO2tlOTtUJ1cOdxgvH38gkIBRCQkVFCTEWABLMGpsHOxZPQhBOgYooA)** 

**Related Issues:**

**Comment by jcalz** [comment]
(Please note that the new issue template asks you to include search terms and related issues.)

Related to #8513, specifically [this comment](https://github.com/microsoft/TypeScript/issues/8513#issuecomment-217710225)

This is working as intended, given #8010: control-flow based type analysis will narrow the type of a union-typed variable upon assignment.  `boolean` is shorthand for the union type `true | false`.

**Comment by fatcerberus** [comment]
This is by design AFAIK.  `uncast`-the-constant is actually still typed as `boolean`; if it were a `let`, you could reassign `true` to it at any time.  The narrowing to `false` was done by control-flow analysis and is temporary within that scope; since the compiler *knows for sure* the value is `false` at that time, the error is generally desirable: it's alerting you that the thing you think could be true or false will actually always be false, which is likely to reflect a bug in most cases.  It's no different than if you did a type guard that ruled out the `true` case and then did something that assumed it could be true: you would get the same error.

**Comment by niedzielski** [comment]
@jcalz, @fatcerberus thanks!

> (Please note that the new issue template asks you to include search terms and related issues.)
Added retroactively.

> `uncast`-the-constant is actually still typed as `boolean`; if it were a `let`, you could reassign true to it at any time.
FWIW, I see the same behavior when using `let`.

Glad it's not a bug but I found the behavior surprising.

**Comment by fatcerberus** [comment]
> FWIW, I see the same behavior when using let.

Yeah, because it's narrowed by CFA.  It's not really typed as `false`, it's just that the compiler knows that's exactly what it is at that moment.  Like I said you could go `uncast = true` and it would be fine (and CFA would then narrow it to `true` :wink:).
