### ISSUE TITLE
OR operator (|) treated like UNION (&) of two types

### ISSUE THREAD

**Issue by selipso** [microsoft/TypeScript#34729]
```
TypeScript error in /home/thakker/Documents/GitHub/crqcentral/src/Models/helpers.ts(34,64):
Property 'then' does not exist on type 'Promise<GraphQLResult> | Observable<object>'.
  Property 'then' does not exist on type 'Observable<object>'.  TS2339
```

I've started receiving errors like these too often starting around TypeScript 3.5. They make me feel like pulling my hair out even though I'm already going bald at a young age. Please think about other developers like me in your design decisions before bloating the language even further. I still have fond memories of Typescript 2. Even TypeScript 3.2 was pretty good and then it just kept going downhill from there. It feels like going from Windows XP to Windows Vista.

In the above error, a Promise is clearly listed as a potential return type. Why is TypeScript focusing on the other return type and not inferring that it is a Promise that is being returned based on the syntax of the calling function?

**Comment by DanielRosenwasser** [comment]
I'm not even sure of the root of the criticism is here - this behavior has been around since TypeScript 1.4 (almost 5 years ago)

The `|` operator *does* create a union type, and because the type-checker doesn't know whether you have a `Promise` or an `Observable`, it can't be sure whether it's safe to call `then.

**Comment by dragomirtitian** [comment]
Could you post an example of code that worked in earlier versions but not in the latest ? Accessing `then` on `Promise<GraphQLResult> | Observable<object>` would never have worked. A union type can be either of the constituents, so you can't access methods that are not common. Consider this simple example:

```ts
let o = Math.random() > 0.5 ? 0 : "" // number | string
o.toString() // ok is on both 
o.toExponential() // not ok what if o is string this would be a runtime error
o.toUpperCase()// not ok what if o isnumber  this would be a runtime error
```

**Comment by selipso** [comment]
But then what's an appropriate `or` operator that actually allows you to compose types?

**Comment by DanielRosenwasser** [comment]
`&`, the intersection type operator.

**Comment by selipso** [comment]
FYI, I am not the only one in this camp because the above library that created declared the typings giving the error is by AWS. The naming conventions of mixed types and union types are just really confusing.

**Comment by dragomirtitian** [comment]
I first encountering intersection and union types it is easy to be confused about why they are named this way (I know I was). You have to think of types in terms of describing sets of instances. 

A union type (`|`) is the set of instances that belong to either constituent in the union (so for `string | number`  an instances is in the set described by the union if it is either in the set described by `number` or the set described by `string`).

The question is having such a type what can we SAFELY do with it? The answer is we can safely access only common members (member which we know to be present regardless of the union constituent an instance actually belongs to). This is where the confusion usually comes in, since the safe members are the intersection of members from the constituent types. But the name union type, refers to the set described by the type not what members we can access.

Same reasoning applies to intersection types (`&`). The set described by an intersection type is the set of instances that belong simultaneously to both constituents of an intersection (So `{ a: number } & { b: string }` represents a type where an instance is at the same type an instance of `{ a: number }` and an instance of `{ b: string }`). SInce the instance is an instance of both of the constituents types at the same type, we can safely access members of either constituents resulting in a union of members, but again the name is not related to members we can access but to the set operation described by the type.

**Comment by RyanCavanaugh** [comment]
https://stackoverflow.com/questions/38855908/naming-of-typescripts-union-and-intersection-types

**Comment by RyanCavanaugh** [comment]
Didn't mean to reopen. Anyway here's a picture

![image](https://user-images.githubusercontent.com/6685088/67587544-f1cc2e00-f708-11e9-8579-e3699feb0490.png)

**Comment by paseaf** [comment]
The picture looks confusing because it's not clear what exactly are being operated on and how the operations are defined.
If Pic 2 is true, then it seems like doing set operations, and object properties are being operated on.

If we define four sets in pic 1 in the following way:
```
Blue_Things = {Things | color = 'blue'}
Red_Things = {Things | color = 'red'}
Big_Things = {Things | size = 'big'}
Small_Things = {Things | size = 'small'}
```

Then pic 2 is reasonable if we do set intersection:
```
intersect(Blue_Things, Small_Things)
= intersect({Things | color = 'blue'}, {Things | size = 'small'})
= {Things | color = 'blue' and size = 'small'}
= Small_Blue_Things
```

But the result of pic 3 is not empty if we do set union:
```
union(Blue_Things, Red_Things)
= union({Things | color = 'blue'}, {Things | color = 'red'})
= {Things | color = 'blue' or color = 'red'}
!= empty
```

Or maybe the question just cannot be easily explained to people who don't know type theory?

**Comment by paseaf** [comment]
After a while of struggling I think finally understand it.

The confusion was because Naming in TypeScript conflicts with in Set Theory (most people who know math know set theory, that's why the naming in TS confusing to many people)

* Union Operator `|` in TS is actually doing **XOR** / **Either Or**, and the **result** properties are equivalent to **Set Intersection** on type properties
* Intersection Operator `&` in TS just equivalent to doing **Set Union** on type properties.

### An even longer example:
**Definitions**
Let `item` a value of arbitrary type.
Let `Type_A = {foo: number, bar: int}`, `Type_B = {bar: int, baz: string}`

* **the Intersection Type `Type_A & Type_B`:** 
Defining `item` of `Type_A & Type_B` means `item` is the **combination of** `Type_A` and `Type_B`, which is actually `{foo: number, bar: int, baz: string}`. Then it is safe to allow `item.foo`, `item.bar`, and `item.baz`.
Hence, we have
`Type_A & Type_B = {foo: number, bar: int, baz: string}`

* **the Union Type `Type_A | Type_B`:**
Defining `item` of `Type_A | Type_B` means `item` is **either** `Type_A` **or** `Type_B`. Then it is unsafe to allow `item.foo`, because that's an error if the actual `item` is of `Type_B`. Similarly, accessing `item.baz` is also unsafe. 
Hence, we have
`Type_A | Type_B = {bar: int}`

**Comment by RyanCavanaugh** [comment]
The names are not backwards. Read the StackOverflow link, or a book on type theory.
