### ISSUE TITLE
 Cannot find name 'MediaRecorder'.

### ISSUE THREAD

**Issue by leishenglin** [microsoft/TypeScript#34728]
![image](https://user-images.githubusercontent.com/25426534/67540808-660ecd80-f719-11e9-9602-075dea090e58.png)

**Comment by AviVahl** [comment]
You can get types for MediaRecorder by installing the types package:
`@types/dom-mediacapture-record`

On another note (personal opinion here), it's quite disrespectful to open such an issue. The "New Issue" page explicitly states that questions go to Stack Overflow. If you believe this to be a bug, there's an entire bug template which you've ignored and replaced with an image. Help others help you.

**Comment by RyanCavanaugh** [comment]
![image](https://user-images.githubusercontent.com/6685088/67891911-caae9b80-fb10-11e9-9883-d21a9cc4b8db.png)

**Comment by timmywil** [comment]
While I completely agree with following issue templates, I think it's worth mentioning that this issue is now near the top of search results for "cannot find name MediaRecorder". That's how I got here (yes, I could have gone to DefinitelyTyped and checked for MediaRecorder, but sometimes you google things).

Point is, despite being an unactionable issue that probably never should have been opened, it now serves a useful purpose as unintentional documentation, answering the simple question of which package is needed to add types for `MediaRecorder`.

Sometimes things work out in ways you would not have expected. This is one of the reasons that I, as an open source maintainer, am a firm believer in showing appreciation for all issues that aren't obviously spam. So thanks @leishenglin.

**Comment by aislanmaia** [comment]
Now that is really a respectful comment coming from you @timmywil . Congratulations!!!

**Comment by ericls** [comment]
How is this unactionable? As a user, if I have access to `HTMLElement` with no third-party dependencies I would expect `MediaRecorder` to also be here. In fact, I expected everything stated on this page: https://developer.mozilla.org/en-US/docs/Web/API to be included by default. Why? because everything else I used is included by default, this is how the human brain works. I think an average user encountering this issue would not consider it a question.  All the comments saying "please use the template. please post questions to StackOverflow" is like saying "please be happy and not be a loser". 

Anyways, here's an actionable suggesting: do a scrape on page: https://developer.mozilla.org/en-US/docs/Web/API, and if there are items not built-in in typescript, change the error message to: "We know this is a built-in browser feature, but we don't have it in typescript by default, please consider installing third-party dependencies".

**Comment by robertnicjoo** [comment]
Open `tsconfig.js`

add following code

```javascript
"angularCompilerOptions": {
    //......
    "types": [
      "node"
    ]
  }
```

**Comment by padunk** [comment]
> How is this unactionable? As a user, if I have access to `HTMLElement` with no third-party dependencies I would expect `MediaRecorder` to also be here. In fact, I expected everything stated on this page: https://developer.mozilla.org/en-US/docs/Web/API to be included by default. Why? because everything else I used is included by default, this is how the human brain works. I think an average user encountering this issue would not consider it a question. All the comments saying "please use the template. please post questions to StackOverflow" is like saying "please be happy and not be a loser".
> 
> Anyways, here's an actionable suggesting: do a scrape on page: https://developer.mozilla.org/en-US/docs/Web/API, and if there are items not built-in in typescript, change the error message to: "We know this is a built-in browser feature, but we don't have it in typescript by default, please consider installing third-party dependencies".

I second this.
Why MediaRecorder need third party dep? Any reason?
Is it still in Working Draft so we need to install third party dep?
Thanks.

**Comment by guiseek** [comment]
> > Como isso é inoperante? Como um usuário, se eu tiver acesso ao `HTMLElement`sem dependências de terceiros, espero `MediaRecorder`também estar aqui. Na verdade, eu esperava que tudo declarado nesta página: https://developer.mozilla.org/en-US/docs/Web/API fosse incluído por padrão. Por quê? porque tudo o mais que usei está incluído por padrão, é assim que o cérebro humano funciona. Acho que um usuário comum que encontra esse problema não o consideraria uma pergunta. Todos os comentários dizendo "por favor, use o modelo. Por favor, poste perguntas no StackOverflow" é como dizer "por favor, seja feliz e não seja um perdedor".
> > De qualquer forma, aqui está uma sugestão acionável: faça um scrape na página: https://developer.mozilla.org/en-US/docs/Web/API , e se houver itens não integrados no typescript, altere a mensagem de erro para : "Sabemos que este é um recurso embutido do navegador, mas não o temos no texto digitado por padrão, considere instalar dependências de terceiros".
> 
> Eu apoio isso.
> Por que o MediaRecorder precisa de um dep de terceiros? Qualquer razão?
> Ele ainda está em Rascunho de Trabalho, então precisamos instalar um dep de terceiros?
> Obrigado.

Hi @padunk & @ericls , how are you?

When they are requesting to include this functionality, it is because we were unable to use it due to typescript typing errors.

VScode marks the same, as not existing in the DOM's type dictionary. They should be present in the file:
`/Users/guiseek/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.dom.d.ts`

If the question should not be here, but in a VSCode issue, direct your users, treat them well, we just want to help with the evolution so that everyone works happily. We are not losers.

Thanks

**Comment by johnwest80** [comment]
So, this is a workaround, NOT a solution, but to get past this in your code without having to add the dependency, just add this line at the top of your code...

`
declare var MediaRecorder: any;
`

**Comment by guiseek** [comment]
it took a long time, but it arrived. now typescript supports MediaRecorder through interfaces
![Captura de Tela 2021-09-05 às 19 56 22](https://user-images.githubusercontent.com/5638096/132143595-a4404807-b0d4-4fb8-af71-26b8bacee36b.png)

I'm really excited about it.

thank you guys

**Comment by guiseek** [comment]
What is happening?

![Captura de Tela 2021-09-05 às 20 55 46](https://user-images.githubusercontent.com/5638096/132144862-ad6b7e95-24e7-4f36-884b-09120cbd7941.png)

What is happening??!?!

**Comment by iliazeus** [comment]
@guiseek are you using the same version of TypeScript both in VSCode and the terminal?

**Comment by guiseek** [comment]
> @guiseek are you using the same version of TypeScript both in VSCode and the terminal?

@iliazeus Sorry for the delay, from what I saw is the version of the project that hasn't arrived in the supported version yet.
