### ISSUE TITLE
Index signature initialization

### ISSUE THREAD

**Issue by BO41** [microsoft/TypeScript#34760]
**TypeScript Version:**  3.5.3

**Code**

```ts
export class User {
  id: number = 0

  [key: string]: any
}
```

**Expected behavior:**

Should work like
```ts
export class User {
  id: number = 0; // <- semicolon

  [key: string]: any
}
```
```ts
export class User {
  id: number // no initialization

  [key: string]: any
}
```

**Actual behavior:**

`error TS1005: ']' expected.`

**Playground Link:**
https://www.typescriptlang.org/play/#code/KYDwDg9gTgLgBAYwDYEMDOa4FU3CnAbwCg44BLAEwC44A7AVwFsAjPOAXjgAYiS4BtANbAAnjTQwoZWgHMAujRS0RRAL5A

CC https://github.com/prettier/prettier/issues/6727 , https://github.com/prettier/prettier/pull/6728

**Comment by IllusionMH** [comment]
IIRC Index signatures are not allowed in class declarations. `[key` part is parsed as computed property and therefore requires `]`(or valid exporession) instead of `:`

**Comment by IllusionMH** [comment]
Looks like this is same problem as with class fields proposal https://github.com/tc39/proposal-class-fields/issues/7.
ASI won't insert `;` if next line starts with `[` and therefore your code is parsed as indexed access `id: number = 0[key` which leads to an error, because `:` won't be part of valid expression for indexed access.

See [proposal source](https://github.com/tc39/proposal-class-fields/blob/87e0af5fd722cfec277e2666fa88287f8da5d2bd/spec.html#L2274-L2285)

Not sure if TS can easily avoid this requirement even if `[` is part of the type and not computed property.

**Comment by RyanCavanaugh** [comment]
ASI hazard is hazardous. We don't want to do a complex lookahead here on `[` to figure out if it's an index signature or element access expression (I'm not even 100% convinced it's never ambiguous).

Line-leading `[` should always have an associated `;` in desemicoloned style
