### ISSUE TITLE
Wrong information in error message for overridden accessor

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#34894]
```ts
class Base {
    set data(value: number) {
        console.log("data changed to " + value);
    }
}

class Derived extends Base {
    data = 10;
}
```

This gives the error message:

```
Class 'Base' defines instance member accessor 'data', but extended class 'Derived' defines it as instance member property.
```

But there is clearly no

> instance member accessor 'data'

because `data` is an accessor on the prototype.

What about the following?

> 'data' is defined as an accessor in class 'Base', but is overridden here in 'Derived' as an instance property.

**Comment by fatcerberus** [comment]
Hmm, I read that differently.  I see it the distinction as being one of “instance property” vs. “static property” instead of “instance” vs “prototype”.

Your proposed message is a definite improvement in any case - it fits with the idea that TS doesn’t distinguish between own keys and prototype keys at the type level.

BUT... isn’t it now legal to do this override, per the class fields proposal?

**Comment by DanielRosenwasser** [comment]
> BUT... isn’t it now legal to do this override, per the class fields proposal?

legal but questionable, especially with the different behavior in `emitDefineForClassFields`.
