### ISSUE TITLE
bug: declaration merging

### ISSUE THREAD

**Issue by aarifkhamdi** [microsoft/TypeScript#34891]
**Code**
```ts
import Express from 'express'

declare module 'express-serve-static-core' {
    export type RequestAnyParams = Omit<Request, 'params'> & { params: any }
}

import { Request, RequestAnyParams, Response } from 'express-serve-static-core'

interface ITest extends RequestAnyParams {
    body: {
        test: string,
    }
}
function isITest(_req: RequestAnyParams): _req is ITest {
    return true
}

const app = Express()

app.get('/test', (req: Request, res: Response) => {
    if (!isITest(req)) {
        res.status(400).send('err')
        return
    }

    req.body // <-- why any??
})
```

**Expected behavior:**
```ts
req.body: {
    test: string,
}
```
**Actual behavior:**
`req.body: any`

**Comment by AnyhowStep** [comment]
`any & { test: string }` is `any`.

**Comment by fatcerberus** [comment]
It's `any` in TS 3.3.3, any version after that gives the correct type as @AnyhowStep pointed out.

**Comment by AnyhowStep** [comment]
Worth noting that `any & { test:string }` is `any`

**Comment by aarifkhamdi** [comment]
@fatcerberus @AnyhowStep i don't know how to reproduce it without `tsc`, but you can find it out with [my repository](https://github.com/aarifkhamdi/typescript_bug)

use `yarn install && yarn build`. As `req.body.lalalalala` does not exists in `ITest` you should get an error. but compilation ends with success

**Comment by nmain** [comment]
The differing behavior on playground vs the local repro repo is due to Algolia.  On the playground, it fetches types from this package:

> [https://www.npmjs.com/package/express-serve-static-core](https://www.npmjs.com/package/express-serve-static-core)

But in the full reproduction, it fetches types from this package:

> [https://www.npmjs.com/package/@types/express-serve-static-core](https://www.npmjs.com/package/@types/express-serve-static-core)

I don't think this is a bug in Algolia; that package is just weird and silly.

Here's a simplified self-contained repro:

[playground](http://www.typescriptlang.org/play/?target=5&module=1&ssl=1&ssc=1&pln=28&pc=1#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgBUykwFsBnAEQWxgQiSIE84BvOAbQGthGAuOMjCjIA5gF1+g4UhEBuOAF8AsAChQkWHBiMweQsXIBBKMWYBeAUNHsxs1eujxtugkVJk4F-e6o06DKGYAH1cDMmNTOxV7cEdEFDQsXDgAJWAARwBXYEEAHnw4UFQkABMPb3JPUJ9qWnomAD5WVQBIACMIEr44TCRGVrA3cn58VWVotVjNZzw0rJyYQz6KjwsAeRIEGFy57MEAGjgAckGwo6aAMlY4U-d+XuZx1WRUDBw8AEkAFQXCkGKyqkMntFsshh4WKo4NC4B0uvxISoYcitAtJFYZPsoTDxuN0JkkH56IgyN8FgAKAD6UAy-F2CyWjBWAEp+NSMiS4GTBM0kTCaTBMlAkFooNkxqpVCVgNgADZEPAANyIcBp6TpwIWkpUCHQcHJAEIEKSfoJyWrmczeWNCrKyHhEci1QA6OGMKLjIA)

**Comment by RyanCavanaugh** [comment]
The linked repo builds without error in 3.7.2

**Comment by aarifkhamdi** [comment]
> The linked repo builds without error in 3.7.2

This is the problem! It should not build successfully

**Comment by RyanCavanaugh** [comment]
Oops! 🤦‍♂️

**Comment by andrewbranch** [comment]
Ok, here’s what’s happening. Thanks @nmain for the isolated repro.

## The explanation

```ts
declare var req: Request<ParamsDictionary>;

if (!isITest(req)) {
  return;
}

// Consider this location in the control flow graph.
req.body;
```

At the last line, what do we know about the type of `req`?

- It must be assignable to `Request<ParamsDictionary>`, because that’s how it was declared.
- It must be assignable to `ITest`, because we checked the negative and returned in that branch.

How do you get a type that’s assignable to two other types? Well, if one type is a subtype of the other, you can just take the subtype. But otherwise, if the types aren’t related, you take the intersection of those two types.

So, is `Request<ParamsDictionary>` a subtype of `ITest` or vice versa? In fact, no. When talking about the _subtype_ relation, `any` behaves like a top type (like `unknown`).

```ts
Request<ParamsDictionary> = { body: any, params: { [key: string]: any } }
ITest = { body: { test: string }, params: any }

// 1. Is Request<ParamsDictionary> a subtype of ITest?
// 1.a Compare `body`
any ⊈ { test: string }

// 2. Is ITest a subtype of Request<ParamsDictionary>?
// 2.a Compare `body`
{ test: string } ⊆ any

// 2.b Compare `params`
any ⊈ { [key: string]: any }
```

So no, neither type is a subtype of the other. So as a fallback we have to take the intersection: `{ body: any, params: { [key: string]: any } } & { body: { test: string }, params: any }`. Which makes the type of `req.body` to be `any & { test: string }`, which, as @AnyhowStep pointed out, is just `any`.

## The answer

You should probably just make sure the declared type (currently `Request`, which defaults to `Request<ParamsDictionary>`) and the predicate type (`ITest`) are subtype-related, which you could do either by making `ITest` extend just `Request`, or typing the `req` param as `RequestAnyParams`. Here’s both ways:

1. [`ITest` extends `Request`](http://www.typescriptlang.org/play/?target=5&module=1&ssl=24&ssc=14&pln=24&pc=22#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgBUykwFsBnAEQWxgQiSIE84BvOAbQGthGAuOMjCjIA5gF1+g4UhEBuOAF8AsAChQkWHBiMweQsXIBBKMWYBeAUNHsxs1eujxtugkVJk4F-e6o06DKGYAH1cDMmNTOxV7cEdEFDQsXDgAJWAARwBXYEEAHnw4UFQkABMPb3JPUJ9qWnomAD5WVQBIACMIEr44TCRGVrA3cn58VWVolWRUDBw8AEkAFRz4IuBSjzSs5eaVOD24Dq7+FlV9s61lySsZABpT-fHx9EykP3pEMkXlgAoAfSgMvxeowAJT8f4ZD5wL6CHZnAEwTJQJBaKDZMaqVQlYDYAA2RDwADciHAAel+JtsoJMZN0HBvgBCBCfJaCb5kkEgnZjQq4sh4E67fZkgB0h0YIvxUsw+Ki4yAA)
2. [`req` is declared as `Request<any>`](http://www.typescriptlang.org/play/?target=5&module=1#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgBUykwFsBnAEQWxgQiSIE84BvOAbQGthGAuOMjCjIA5gF1+g4UhEBuOAF8AsAChQkWHBiMweQsXIBBKMWYBeAUNHsxs1eujxtugkVJk4F-e6o06DKGYAH1cDMmNTOxV7cEdEFDQsXDgAJWAARwBXYEEAHnw4UFQkABMPb3JPUJ9qWnomAD5WVQBIACMIEr44TCRGVrA3cn58VWVolWRUDBw8AEkAFRz4IuBSjzSs5dzexiaWVTgjuA6u-gOVY6utZckrGQAaQ+Px8fRMpD96RDJF5YAKAD6UAy-F2AEp+MCMj84H9BM1LscQTBMlAkFooNkxqpVCVgNgADZEPAANyIcBB6X4m2yeV2DVxk3QcH+AEIEL8loJ-lTweDEWNCoSyHgLlcqQA6U6MSXE+WYYlRcZAA)

By the way, the latter approach recognizes that `RequestAnyParams` is more straightforwardly typed as `Request<any>`, rather than an Omit with an intersection, but it doesn’t have any impact on the outcome.
