### ISSUE TITLE
Type inference does not work when in return position

### ISSUE THREAD

**Issue by jerguslejko** [microsoft/TypeScript#34929]
**TypeScript Version:**  3.7-beta

**Search Terms:** inference, generic functions

**Code**

```ts
export function foo<T, K>(props: {
    seed: T;

    producer: (x: T) => K;

    consumer: (data: K) => void;
}) {
    //
}

foo({
    seed: "foo",

    producer: (seed) => {
        // type of `seed` is string
        return seed; 
    },

    consumer: (data) => {
        // type of `data` is unknown 
    }
})
```

**Expected behavior:** TypeScript infers `K` to a `string`, so the type of `data` is `string`.

**Actual behavior:** `data` variable is `unknown`.

**Comment by AnyhowStep** [comment]
I believe this is also because TS cannot perform inference on the same object multiple times?
https://github.com/microsoft/TypeScript/issues/34865

It is why I use the **builder** pattern.
The builder pattern lets me break apart inference on one giant object into multiple inferences on multiple smaller objects/values
https://github.com/microsoft/TypeScript/issues/34907

**Comment by jerguslejko** [comment]
@AnyhowStep is took me 2 months exactly to understand what you mean :))

I'm able to reproduce this behaviour by swapping from `f({ a, b })` to `f(a, b)`. The non-object version works correctly. However, I'm trying to type a TSX component which always receives an object. 

I think I'm out of luck :( 

Thank you though! I learned something
