### ISSUE TITLE
Completions for private members appear in JavaScript files

### ISSUE THREAD

**Issue by jessetrinity** [microsoft/TypeScript#34934]
When a .d.ts file is included with a .js file (ostensibly created by some .ts file in a galaxy far far away) in order to get intellisense, private class members appear in completions lists. This is probably a bug and we have gotten some feedback from users that they would rather not see this.

A possibly greater pain point is that when the private member shows up in completion, _the icon is wrong_, I'm guessing because we do not have the full signature for private members in .d.ts files. I believe the lack of full signatures is by design though and I don't believe there is a way to make those members appear method-like without them.

**TypeScript Version:**  3.6.3

**Search Terms:**
private completion

**Code**

**.d.ts**
```ts
// @filename:test.d.ts
/** The 'Test' namespace. */
declare namespace Test {
    /** The 'Foo' class.*/
    class Foo {
        /** Constructor. */
        constructor();
        /** I'm private: don't use me. */
        private MethodOne;
        /** I'm public: let's do this. */
        MethodTwo(): void;
    }
}
```
**.js**
```ts
// @filename:file.js
var foo = new Test.Foo();
foo.
```

**Expected behavior:**
The completion list contains `MethodTwo`.

**Actual behavior:**
The completion list contains `MethodOne` and `MethodTwo`.

**Comment by orta** [comment]
Yeah, I agree - want to pair on this with me?

**Comment by Jolg42** [comment]
Hi there :)

So it looks like this bug is still present in the latest stable version, what is the status on your end? Would this be fixed soon maybe?

This bug is quite annoying for developer experience as a library author because it's suggesting to developers that it is fine to use the private properties. Most people won't even know they are actually private. So if they start using them and an internal change breaks these, it will impact the users of the library, even though it's not a real breaking change in the user-facing API.

**Comment by DanielRosenwasser** [comment]
Go for it - language service tests are in `tests/cases/fourslash`, look for `// @filename` comments to create mixed a mixed `.js` and `.ts` context. The core logic is in `src/services/`, probably in a file called `completions.ts`.

**Comment by Jolg42** [comment]
Hi @jessetrinity, will this be in a future `3.9.x` release maybe? Or like the tag suggests the `4.0` August release?
