### ISSUE TITLE
Shadowing built-in types fails with `composite: true` for projects

### ISSUE THREAD

**Issue by ianstormtaylor** [microsoft/TypeScript#35002]
**TypeScript Version:**  3.8.0-dev.20191105

**Search Terms:** composite, references, private, name, exported, variable, import

**Code:**

##### tsconfig.json

```json
{
  "compilerOptions": {
    "composite": true,
    "rootDir": "./src",
    "outDir": "./lib"
  }
}
```

##### dom.ts

```ts
export type DOMNode = Node
```

##### custom.ts

```ts
export type Node = {}
```

##### index.ts

```ts
import { Node } from './custom'
import { DOMNode } from './dom'

type Constructor = new (...args: any[]) => any

export const mixin = (Base: Constructor) => {
  return class extends Base {
    get(domNode: DOMNode) {}
  }
}

```

**Actual behavior:**

```ts
$ tsc -b
src/index.ts:6:14 - error TS4025: Exported variable 'mixin' has or is using private name 'Node'.

6 export const mixin = (Base: Constructor) => {
               ~~~~~


Found 1 error.
```

**Expected behavior:** 

It should successfully compile.

It seems like there's a bug with the shadowing of built-in types in `composite` builds?

Right now, the failure disappears if:

1. If you remove the `composite: true` flag from `tsconfig.json` it will successfully compile. But that isn't a solution for me because I'm using a monorepo.

1. If you rename the `core.ts` type to `CustomNode` it will successfully compile. But this isn't a solution because it requires changing an external package (it's just internal in this small reproduction).

1. If you change the `import { Node }` line to `import { Node as CustomNode }` (using an alias) it will successfully compile, which is weird seeing as there isn't any actual change to the code or typings, just a naming change. 

1. If you remove the unused `import { Node }` line it will successfully compile, which is weird seeing it's unrelated to the error.

1. If you remove the `domNode: DOMNode` argment to the `get()` method it will successfully compile, which is weird seeing as how it doesn't relate to the error message's complaint. 

**Reproduction Repo:** https://github.com/ianstormtaylor/typescript-composite-mixins-bug

**Comment by RyanCavanaugh** [comment]
This is happening because `composite` changes the default of `declaration` from `false` to `true`, not `composite` per se. But it does look like a .d.ts emit bug

**Comment by weswigham** [comment]
So this is a limitation of how aliases work. Since the alias is just `export type DOMNode = Node`, `Node` doesn't get any alias symbol referring to `DOMNode` (it's not a new type of any kind), and the references are directly to the global `Node`. This means when we try to print it back, we want to print `Node` (the global one), but there's a local `Node` which shadows it and makes it inaccessible, so we have no way to print it. _Now_ we do have access to `globalThis` nowadays, so this error is probably a bit out of date, as we should at least be able to write `globalThis.Node`. As a workaround, for now, if you export as
```ts
import N = globalThis.Node;
export { N as DOMNode };
```
instead of
```ts
export type DOMNode = Node
```
we should have an alias-based chain of custody (export aliases behave very differently to type aliases), and should be able to name the type correctly.

**Comment by ianstormtaylor** [comment]
Thank you @weswigham that is super helpful!

Is that workaround example supposed to be `import`? Or is that meant to be `const` or something else? I didn’t realize that was valid syntax.

**Comment by weswigham** [comment]
Yep, supposed to be `import`, and yep, that's valid syntax.

**Comment by SSJ9899TDylan** [comment]
What is going on here?

**Comment by Jack-Works** [comment]
It happened in our project on `ShadowRoot` but we're not shadowing it.

The trick (maybe I don't understand why) @weswigham wrote works for me but I'm curious why.

```typescript
import ShadowRoot = globalThis.ShadowRoot
export const root = x.attachShadow(...)
```

I know this is an import syntax in the early days of ES6. but why does it resolve the TS4025 error? (Notice I didn't re-export the type itself.)

The output `.d.ts` file:

```typescript
import ShadowRoot = globalThis.ShadowRoot;
export declare const portalShadowRoot: ShadowRoot;
export declare function PortalShadowRoot(): Element;
```

This statement also adds a declaration in the JS file, what if I don't want to add it?

```javascript
var ShadowRoot = globalThis.ShadowRoot;
```

The `import type` syntax seems doesn't valid for it

```typescript
import ShadowRoot = globalThis.ShadowRoot
```

**Comment by weswigham** [comment]
`import X = A.B` is an old TS syntax from the era of namespaces that takes one namespace member and aliases it to a local name. Conviniently `globalThis` is a typically available global namespace, so the two combined allow you to create local aliases to global names even when they're shadowed by a local name.

> js emit

Yeah, the syntax is a bit old, so didn't get the `import type` treatment. @andrewbranch how do you feel about it?

**Comment by andrewbranch** [comment]
The purpose of `import type` (and its accompanying tsconfig option, `--importsNotUsedAsValues`) was to let users in particular scenarios have a guarantee about whether external modules would be referenced at runtime. Some needed to ensure that a non-type-only import _would_ reference the module at runtime because they were relying on side effects, and others wanted to enforce that a module _wouldn’t_ reference the module at runtime to avoid circular dependencies or bloated bundles. Neither of those seemed particularly relevant to _internal_ module imports (`import X = A.B`).

My gut reaction is that `import ShadowRoot = globalThis.ShadowRoot` should actually _not_ emit `var ShadowRoot = ...` in JS if it’s never used in value space—this would be consistent with the default behavior external module imports that are never used in value space. The emit resolver knows that and elides them. But I guess we don’t have a similar check for `import X = A.B`. Maybe there’s a good reason we don’t that I’m not thinking of.

**Comment by Jack-Works** [comment]
Another word, `--importsNotUsedAsValues` is not strong enough for me.

```
import { value, Type } from 'mod'
//              ~~~~ should be error!
value()
```

```
import { value } from 'mod'
import type { Type } from 'mod' // ok
```

The reason is that I'm writing a custom transformer, that drop all statements excluding `import` or `export` to generate a tree-shaking purpose only source file.

Source file:

```
import { value, Type } from 'mod'
import type { Type2 } from 'mod2'
value()
value()
// ... stmts
```

Becomes

```
import { value, Type } from 'mod'
__imported('mod', { value, Type })
```

As you can see the `import type` is dropped but the `Type` in the first statement doesn't. I don't have enough information to know if `Type` is a value or a type because all statements are dropped. I have to do the following to prevent a runtime error.

```
import { value, Type } from 'mod'
__imported('mod', {
value: typeof value != 'undefined' ? value : void 0,
Type: typeof Type != 'undefined' ? Type : void 0
})
```

If TypeScript can enforce all type-only import to split to a separate `import type` statement, it will be easier to build the tools for tree shaking.

**Comment by andrewbranch** [comment]
That’s currently an anti-goal of `import type`. For typical TypeScript usage, there’s no reason to do that, but if we made a flag that enforced it, people would use it, and the only effect would be a decrease in productivity. I think what you want to do can be done with the emit resolver, but it’s an internal API 😕

**Comment by Jack-Works** [comment]
Hmm I need to speed up this kind of process so I drop any statements that not related to `import` or `export`, so also for the emitter, there is no information about how the name is used (as value or as type or unused) in the original source file.

I'd like to learn about "emit resolver", I never worked with typescript emitter API before 👀
