### ISSUE TITLE
Assertion functions don't work with wildcard imports

### ISSUE THREAD

**Issue by dfilatov** [microsoft/TypeScript#35004]
**TypeScript Version:**  3.7.2

**Search Terms:**

assert function import export

**Code**

```ts
// Module asserts.ts
function isNonNullable<T>(obj: T): asserts obj is NonNullable<T> {
    if(obj === undefined || obj === null) {
        throw new Error('Must not be a nullable value');
    }
}

export {
    isNonNullable
};

// Module test.ts
import * as asserts from './asserts.ts';

function test(obj: string | null): void {
    asserts.isNonNullable(obj);
    obj.trim();
}
```

**Expected behavior:**
Everything works as expected

**Actual behavior:**
Error: Assertions require every name in the call target to be declared with an explicit type annotation.

If I rewrite test.ts with:
```ts
// Module test.ts
import { isNonNullable } from './asserts.ts';

function test(obj: string | null): void {
    isNonNullable(obj);
    obj.trim();
}
```
then everything compiles without any error

**Comment by ilogico** [comment]
To reproduce this issue, you have to use namespace imports `import * as assert from './assert.js'` and export the function through an export list `export { check }`.
When the function is exported with `export function check(...`, everything works correctly.

**Comment by andrewbranch** [comment]
I seem to recall that a lot of cleverness was required to support tracking these assertion signatures through property access without performance regressions, so this isn’t _super_ surprising... But since `export function isNonNullable ...` does work (thanks @ilogico), I’m hopeful this a simple fix.

**Comment by G-Rath** [comment]
I believe this issue is preventing shipping assert guards in `@types/node`, due to `@types/adone` containing an `std` object that does:

```
import assert = require("assert");
...

export {
  assert,
  ...
}
```

I'm going to look further into this, especially since [`adone`](https://www.npmjs.com/package/adone) is deprecated, so might be able to hack around it, but if this is fixable that would help too 

This is the PR if people want to take a look: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42786

**Comment by dfilatov** [comment]
@RyanCavanaugh Is there any plan to fix this?

**Comment by RyanCavanaugh** [comment]
@dfilatov eventually, yes, or if someone wants to send a PR, that'd be great

**Comment by jakebailey** [comment]
Here is a similar case which affects the module-ified TS compiler:

```ts
// @strict: true

// @filename: src/core/_namespaces/ts.ts
import * as Debug from "../debug";
export { Debug };

// @filename: src/core/debug.ts
export declare function assert(expression: unknown): asserts expression;


// @filename: src/core/foo.ts
import * as ts from "./_namespaces/ts";
import { Debug } from "./_namespaces/ts";

ts.Debug.assert(true);
Debug.assert(true);


// @filename: src/other/_namespaces/ts.ts
export * from "../../core/_namespaces/ts"


// @filename: src/other/bar.ts
import * as ts from "./_namespaces/ts";
import { Debug } from "./_namespaces/ts";

ts.Debug.assert(true);
Debug.assert(true);
```

`ts.Debug.assert` doesn't work, but `Debug.assert` does. That's curious because the latter is still a wildcard import, just not the "top level" one. Using the "top level" one is where it breaks, but going a little more direct works.

**Comment by jakebailey** [comment]
This turned out to be really simple; will send a PR for it soon.
