### ISSUE TITLE
Interface don't working

### ISSUE THREAD

**Issue by FrontendMetis** [microsoft/TypeScript#35008]
Hello, interface DATA don't work, but if I will remove return type Function from getHtmlFunc, typization will work fine:

```ts
interface DATA {
    state: {
        set: number,
        data: object
    }
};

getHtmlFunc()('', {
    state: {
        set: () => { },
        data: {}
    }
});

function getHtmlFunc(): Function { 
    return (templateEntry: string, data: DATA) => { 
        // some code
    }
}
```

 https://www.typescriptlang.org/play/index.html?ssl=15&ssc=25&pln=15&pc=33#code/JYOwLgpgTgZghgYwgAgCIEEAq7kG8CwAUAJADOYckAXHkcWRGDSAK4C2ARtADR3EAmlODQD2HAFYQEYOgF8isgNxEiAc0YAJMGwA2AMRYgEACgCUxgOQXutQsnvJylCDQJ2HH0oxpnkAXgA+PGRZXncPe0EKV3lwkIVTZUIiGENpYBEQZHUwLV0DIzMaAvTM4KIPKEYWKCzjSDYABx1nAFFwKABPGnIoUFUbKOE0LHRTfyDcZAqI+xn7WNkgA

**Comment by RyanCavanaugh** [comment]
Annotated return types take precedence over return expression types.

**Comment by FrontendMetis** [comment]
Will this fix in future versions?

**Comment by RyanCavanaugh** [comment]
This is the expected behavior. It is not a bug.

**Comment by FrontendMetis** [comment]
This is not logical for me.....

**Comment by nmain** [comment]
When a function's annotated return type is less specific than the actual returned expression in the body of the function, the less specific return type is used so that functions can hide implementation details.  In your case, your annotated return type of `Function` indicates that you want external callers to not rely on any particular function with any particular call signature -- they can only be certain that the returned thing is a function.  If you don't want that, then don't use that annotation.
