### ISSUE TITLE
Unable go to definition when Angular project compiled using Ivy engine

### ISSUE THREAD

**Issue by SteveRusin** [microsoft/TypeScript#35014]
This issue valid only for imports from `@angular` modules.
Other imports like `rxjs` works fine, and 
there is no problem to open definition for any imported function.

- VSCode Version: 1.39.2
- OS Version: Windows 10. V 1903

Steps to Reproduce:

1. Install [Angular CLI](https://cli.angular.io/)
2. Create new project `ng new shiny-ivy-app --enable-ivy`
3. Build project `ng serve`
4. Open `app.component.ts` and try to go to definition for `Component`

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by mjbvz** [comment]
Confirmed with 3.8.0-dev.20191105. I see the error:

```
  ERR <semantic> TypeScript Server Error (3.7.2)
Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at tryGetSourcePosition (tsserver.js:115340:26)
    at tryGetSourcePosition (tsserver.js:115341:61)
    at tryGetSourcePosition (tsserver.js:115341:61)
    at tryGetSourcePosition (tsserver.js:115341:61)
    at tryGetSourcePosition (tsserver.js:115341:61)
    at tryGetSourcePosition (tsserver.js:115341:61)
    at tryGetSourcePosition (tsserver.js:115341:61)
    at tryGetSourcePosition (tsserver.js:115341:61)
    at tryGetSourcePosition (tsserver.js:115341:61)
...
```

Possibly related to #33717

**Comment by sheetalkamat** [comment]
Culprit for this is angular `core.d.ts` file which has source map pointing to `core.d.ts.map` next to it. But the source map has source file with contents in memory. 
 Currently we don't support in memory lookup so resolution happens to be core.d.ts file but with different location. So when trying to see if resolved location is generated from source map, we find core.d.ts map again and try to translate new location again. And the loop continues..

**Comment by sheetalkamat** [comment]
To support inline sources would need support in editor as well as tsserver since tsserver would then need to specify inline text along with the source position. Even with that this issue further complicates matters since the filename of this inline text could be same as generated position we are mapping from (eg in this case core.d.ts is generated file and exits on the disk but original file core.d.ts with same path exists only in source map ) so editor and tsserver would need to handle that as well? (currently tsserver doesn't support opening two files with same name and different contents..It would be very hard to distinguish between them as well)

**Comment by initplatform** [comment]
Ahh Thank You. This has been driving me crazy!!! 
Guess there is no work around until this is fixed and then compatible with angular.... so `Go To Definition` is going to be broken in VS Code for Angular imports in new Angular projects when 9 is released for the next.... 6 months... ? year?

**Comment by DanielRosenwasser** [comment]
Can we gently degrade and just not jump to definition in the sourcemap if the file's in memory?
