### ISSUE TITLE
behavior of `never` keyword has been changed?

### ISSUE THREAD

**Issue by Rokt33r** [microsoft/TypeScript#35026]
I'm from https://github.com/vfile/vfile/issues/39

We found that, once a function returning `never` executed, type assertions in below code don't work anymore. I guess this is for performance improvement... But I'm not sure this behavior is really intended or just a bug.

**TypeScript Version:** typescript@3.8.0-dev.20191105

**Search Terms:**

- typescript@3.8.0-dev.20191105
- never
- type assertion

**Code**

https://github.com/vfile/vfile/blob/9f4180893db6fb4d16fa070fd2ec437118276e21/types/vfile-tests.ts#L66-L69

**Expected behavior:**

type of `fileWithData.data` in line 67 should be asserted as `CustomData`

**Actual behavior:**

Type assertion failed

**Related Issues:** 
https://github.com/vfile/vfile/issues/39

**Comment by fatcerberus** [comment]
This is by design:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#better-support-for-never-returning-functions

Some theoretical background: `never` is the bottom type and represents values produced by unreachable code (the wording usually used is "the type of values that never occur", but that's confusing IMO).  It is a type with no inhabitants--you can't possibly have a value of that type unless you're lying to the type system.  Therefore a function returning `never` is treated as though it doesn't return and everything below it is unreachable.

**Comment by Rokt33r** [comment]
Thanks for the comment. :)
