### ISSUE TITLE
Looback 3/NodeJS intellisense not working

### ISSUE THREAD

**Issue by rlyttle** [microsoft/TypeScript#35047]
Not able to get intellisense on Loopback 3 nodeJS framework projects.

Example repo has Account model, I've added "test" function:

![image](https://user-images.githubusercontent.com/19949843/68083824-829bbb80-fe25-11e9-8588-a7b476606d64.png)

Trying to get intellisense for Account.test from another Model file doesn't work:
![image](https://user-images.githubusercontent.com/19949843/68083831-9ba46c80-fe25-11e9-8362-0cc0f7b6209c.png)

Or, trying via app.models.Account as per LB3 conventions:
![image](https://user-images.githubusercontent.com/19949843/68083920-b1666180-fe26-11e9-9990-9ac2c33c4bc5.png)

I've tried everything I can think of, any advice here? This seems like it could be a bug in intellisense?

- VSCode Version: 1.3.9
- OS Version: Mac OS 10.14.6

Steps to Reproduce:

1. clone https://github.com/rlyttle/loopback-example-relations
2. Try to use intellisense between Model javascript files within common/models folder (Account.js and Address.js used as examples).

Does this issue occur when all extensions are disabled?: Yes

**Comment by andrewbranch** [comment]
> Trying to get intellisense for Account.test from another Model file doesn't work:
> ![image](https://user-images.githubusercontent.com/19949843/68083831-9ba46c80-fe25-11e9-8362-0cc0f7b6209c.png)

This one is working correctly—`account` here is the function object exported by `account.js`. It does _not_ have a member `test` at all; the argument _passed_ to that function will get a `test` member added:

```js
const account = require('./account');
account.test; // undefined;

const Account = {};
account(Account);
Account.test; // [Function]
```

--- 

> Or, trying via app.models.Account as per LB3 conventions:
> ![image](https://user-images.githubusercontent.com/19949843/68083920-b1666180-fe26-11e9-9990-9ac2c33c4bc5.png)

The TypeScript compiler (which powers IntelliSense for JavaScript in VS Code) doesn’t (and can’t) know about the naming conventions used by an external framework like Loopback, or about how loopback-boot is wiring all these things up under the hood. As far as TypeScript can tell, everything in `common/models` isn’t even _used_, because it gets loaded dynamically. Because `app.models` is a dictionary with entries based on all this implicit configuration and convention, TypeScript has no idea what `app.models.Account` is, and it _definitely_ can’t tell that it’s the same object passed to the function exported by `common/models/account.js`. There’s simply no way the compiler can connect the dots.

It appears to me that Webstorm is making a wild guess based on string matching, but I can’t say for sure. Whatever Webstorm is telling you, it doesn’t come directly from our language service, and in fact it could easily be wrong, even though it happens to be right in this case.

This configuration pattern was not designed with static typing in mind. You could probably fix your IntelliSense by manually writing type definitions that match your model shapes, but there’s no way for it to be populated dynamically in the pattern that Loopback is using here.

**Comment by rlyttle** [comment]
@andrewbranch many thanks for looking at this - what you've said makes sense. I guess this means no intellisense for Loopback 3 projects :(

Thanks again for your time!
