### ISSUE TITLE
Printer breaks when there is \ in string literal in jsx attrs

### ISSUE THREAD

**Issue by kgtkr** [microsoft/TypeScript#35054]
**TypeScript Version:**  typescript@3.8.0-dev.20191105

**Search Terms:**
compilar api

**Code**

```ts
fs.writeFileSync(
  "out",
  ts
    .createPrinter()
    .printFile(
      ts.createSourceFile(
        "test.ts",
        fs.readFileSync("in", { encoding: "utf8" }),
        ts.ScriptTarget.ESNext,
        undefined,
        ts.ScriptKind.TSX
      )
    )
)
```

in
```
<a x="\\"/>
```

**Expected behavior:**

out
```
<a x="\\"/>
```

**Actual behavior:**
out
```
<a x="\\\\"/>
```

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Confirmed repro. Running `tsc` normally on this input generates the correct output.

**Comment by rbuckton** [comment]
Would this be considered a bug? The issue is due to the fact the string literal node for `"\\"` doesn't have a parent pointer (because the `setParentNodes` argument of `createSourceFile` was passed `undefined`), so we can't determine the source file the node belongs to. We use the source file to extract the actual literal text, and when we can't find the source file we fall back to emitting the literal as best we can (with no knowledge of the surrounding code). This means we escape the `"\\"` as `"\\\\"` since we can only assume this is a JavaScript string literal, not a JSX attribute string.

**Comment by rbuckton** [comment]
I'm looking into solving this by adding `EmitHint.Jsx`, which can be used to ensure the correct encoding for string literals in Jsx Attributes.
