### ISSUE TITLE
Instance property used in reassigning method causes implicit `any` in `checkJs`

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#35099]
```ts
// ./foo.ts

class Foo {
    constructor() {
        this.foo = "Hello";
    }
    slicey() {
        this.foo = this.foo.slice();
    }
}
```

```json5
// ./tsconfig.json

{
  "compilerOptions": { "strict": true },
  "files": ["./foo.ts"]
}
```

## Current Behavior

```
'foo' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.ts(7022)
```

## Proposed Behavior

If an implicit `any` is going to be inferred, but `foo` has an initializer in the constructor, it should always infer the type from the initializer.

**Comment by DanielRosenwasser** [comment]
Found using `checkJs` on the following code https://github.com/jleeson/iris/blob/be259e3a5d11657cbb5775bd96aae48cb8fbd368/src/views/View.js#L12

**Comment by sandersn** [comment]
This has been around since at least 2.3. It's related to over-eager type resolution in Javascript, which causes a circularity in type checking. It appears in a number of places, but this will probably be the most commonly encountered.

It's easy to work around with a type annotation or a stage 3 property declaration.
