### ISSUE TITLE
Inconsistent Inference of Generic Class type parameter

### ISSUE THREAD

**Issue by rdhelms** [microsoft/TypeScript#35110]
**TypeScript Version:**  3.7.2

**Search Terms:**
generic class type parameters inference

**Code**

```ts
class SomeClass<T = object> { }
type TInstance1 = SomeClass                          // SomeClass<object>
type TInstance2 = InstanceType<typeof SomeClass>     // SomeClass<unknown>
```

**Expected behavior:**
I expected `InstanceType` to return an instance type with the type parameter's default value.

**Actual behavior:**
If the class's type parameter is `T extends A = B`, `InstanceType` infers `A` rather than `B`.

**Playground Link:** 
https://www.typescriptlang.org/play/#code/MYGwhgzhAEDKD2BbApgYXFAPAFWgXmngCMArZYAFwD5oBvaAXwCgKBPAB2WmwEkA7CBTB9gyAIz44SNBhjR50APSKpKdJAiZiZSlRYcuvAUJHIATJP6Dho7AcxtO8AGaqZGmgqUqEa2ZgBXPgBrPngAdz49IA

**Comment by rdhelms** [comment]
@jcalz Can I help clarify anything here? Here's another example of something that seems counterintuitive:

```
class SomeClass<T extends string | number = string> { }
type TInstance = InstanceType<typeof SomeClass>   // SomeClass<string | number>
```

I would have expected `TInstance` to be `SomeClass<string>`

**Comment by jcalz** [comment]
You're making generic types with [structurally unused type parameters](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-type-inference-work-on-this-interface-interface-foot--), so I'm not sure what kind of behavior to expect.  After that I guess it might make some sense to expect that the necessarily lossy `InstanceType<SomeGenericConstructor>` might result in the type parameter becoming the default if there is one instead of the constraint, but I don't think I'd *expect* that to happen.

**Comment by rdhelms** [comment]
The fact that the type parameter is unused is just to provide a simple example. The main reason why this was an issue for me was that I wanted to update a type that was originally essentially this:
```
class SomeClass {
    attributes: any
}
```

To instead be something like this:
```
class SomeClass<T = any> {
    attributes: T
}
```

My goal with the above was to make the class typing more robust, while simultaneously not introducing breaking changes. But the above actually is a breaking change due to other code that infers an instance type of `SomeClass`. In the original code, the inferred type of `attributes` was `any`, but with the change, the `attributes` property becomes typed as `unknown`. But if the inference used the default type parameter provided, then doing the above would not be a breaking change.

Hence the expectation 🙂

**Comment by andrewbranch** [comment]
The behavior you’re looking for would be undesirable, because `InstanceType<SomeConstructor>` is supposed to describe any instance of `SomeConstructor`. What you’re proposing is that it describe a specific type instantiation of `SomeConstructor`. The fact that it’s the default type parameter does make that _sound_ reasonable, but it would have some really unintuitive effects if you look at it from the perspective of a function that wants to be passed an instance of something:

```ts
declare class SomeClass<T extends string | number = string> {
    prop: T;
}

declare const s: SomeClass<string>;
declare const n: SomeClass<number>;

function doSomethingWithSomeClassInstance(instance: InstanceType<typeof SomeClass>) {
    // `prop` on an instance of SomeClass could be `string` or `number`, couldn’t it?
    instance.prop;
}

// These are both instances of SomeClass, so
// shouldn’t we be able to call this with any
// instance?
doSomethingWithSomeClassInstance(s);
doSomethingWithSomeClassInstance(n);
```

Put more concisely, it would be strange for any instance of `SomeClass` not to be assignable to `InstanceType<typeof SomeClass>`.

Your examples are a little too pared down to the abstract for me to be able to suggest an alternative approach, but it seems likely that there’s some other way to accomplish your end goal. (E.g., I’m guessing you don’t actually have a class declaration available, otherwise you’d probably just be using `SomeClass<T>` directly instead of `InstanceType<typeof SomeClass>`)

**Comment by rdhelms** [comment]
> because InstanceType<SomeConstructor> is supposed to describe any instance of SomeConstructor. What you’re proposing is that it describe a specific type instantiation of SomeConstructor.

That's an interesting way of phrasing that, because ultimately `InstanceType` *does* describe a specific instantiation of SomeConstructor...it's just a difference between choosing that specific instantiation based on what the type parameter "can theoretically ever be" (in your case `SomeClass<string | number>` as opposed to what the type parameter "would be if no type parameter were specified" (`SomeClass<string`)>.

Since a class' type parameter is really only relevant on its instance type, it seems inherently ambiguous what the expected behavior would be. And unfortunately, the documentation for `InstanceType` only contains a non-generic example...so I was left to guess what it was "supposed" to do. In fact based on this line from the example in the [documentation](https://www.typescriptlang.org/docs/handbook/utility-types.html#instancetypet)...
```
type T0 = InstanceType<typeof C>;  // C
```
...I was led to believe that `InstanceType<typeof SomeClass>` was meant to always be equivalent to `SomeClass`. But if you were to replace `InstanceType<typeof SomeClass>` with `SomeClass` in your example, then the second function call would fail.

If the intent is indeed for `InstanceType<SomeClass>` to behave differently than `SomeClass`, then I would vote for adding an example of `InstanceType` being used with a generic class to that section in the Utility Types documentation.

**Comment by andrewbranch** [comment]
> That's an interesting way of phrasing that, because ultimately `InstanceType` does describe a specific instantiation of `SomeConstructor`

Yes, and as soon as I sent that I _almost_ went back and tried to rephrase 😄 Yes, you _do_ end up with a “specific” instantiation, but the point I intended to make was that the base constraint instantiation is special, and much more significant than the default type parameter. When I say that “`InstanceType` is supposed to describe any instance of `SomeConstructor`,” it’s not as if someone was sitting around trying to design its behavior and settled on inferring to the constraint because it made sense to them. `InstanceType`’s behavior arises from its definition:

```ts
type InstanceType<T extends new (...args: any) => any> = T extends new (...args: any) => infer R
  ? R
  : any
```

and from the regular rules of inference, even outside the presence of `InstanceType` or conditional types altogether. When you don’t have an inference candidate for a type parameter, you _have_ to take the constraint or else there are concrete scenarios where the inferred type will be _wrong_. Here’s a concrete example:

```ts
enum FileKind {
    M4A,
    MOV,
    MP3
}

class MediaFile<T extends FileKind = FileKind.M4A> {
    constructor(public kind: T) {}
}

function makeInstance<InstanceT>(Constructor: new (prop: FileKind) => InstanceT): InstanceT {
    return new Constructor(FileKind.MOV);
}

// Can’t possibly infer `T` in `MediaFile`.
// At runtime, the value will be `FileKind.MOV`,
// so defaulting inference to `FileKind.M4A` would
// produce unsafe results.
const media = makeInstance(MediaFile);
```

[Playground](https://www.typescriptlang.org/play/#code/KYOwrgtgBAYglgG2AaTiAJlA3gKCvqAWQBYBBAGjwMIHkA1SgogBQGYcBfHHAYwQEMAzoKLB0cfvCQAeACpRgADwAuodCKko0mALyxEWjADoSpAHzYq+HgHsQg5QCcwPZTccAKAA5gARgjgeKABrbQAuKFkASmwuLhwAMzAQVzg7KAh+YOAASXtlfhTgaTyHQp5gWTMPAGE7B2dXdwiQYAB3KG9HGy8IzVQMGJ0LUoKi6IjR8srLJkdgZTBHEChWjrr8xrdPfu0TeiiAbk5uAHpTqBrCwEwCZSgvG2E4fwBPKDQE4EcoAANZH-eKx+hDEEk0PyMOHOUFId2cIGUcAgwHIUGUAAtgFAAG78BBgLFtRAIKC+LE-XbGWh0H6UaGCGxQdDABL8MAIREgADmgM+8yKaMZFIMA3QJjIALaNnZ6ChFy83XQLixyUE-E+UHmgnZykEkNs+QyoP4UD0mWyUyKHhB4kkBiOOCAA)

Is this a terrible, terrible API? Yes! But it’s semantically valid, and TypeScript needs to work with what it’s given as safely as possible here, and this demonstrates that the only safe thing to do is infer to the constraint.

> I would vote for adding an example of InstanceType being used with a generic class to that section in the Utility Types documentation.

Agreed. I’ll pass this along!

**Comment by rdhelms** [comment]
Thanks @andrewbranch - that example is helpful, and also mentioning the "regular rules of inference" made me try to think of other examples that also need to use the constraint instead of the default, like with function return types, which reinforces what you're saying:
```ts
type StrOrNumType = <T extends string | number = number>() => T
type Test = ReturnType<StrOrNumType>    // string | number, not number
```

Ultimately I think the confusion came from the simplistic example in the documentation, along with some general confusion about the "necessarily lossy" `InstanceType<SomeGenericConstructor>`, as @jcalz put it.

Thanks!
