### ISSUE TITLE
TypeScript Project Properties for Unit Test Projects

### ISSUE THREAD

**Issue by IgorWolbers** [Microsoft/TypeScript#3518]
I would like to request the feature to support Visual Studio Unit Test projects with this extension (ie. include the project tab TypeScript Build in unit test project properties).

Standard practice is to have 1 unit test project for every code project in Visual Studio and I want to include my type script tests written against my typescript in my web project in the unit test project. The problem is that the visual studio unit test project does not have a project page called "Typescript Build" where I can configure the project to watch and automatically compile the .ts files into .js files. This forces me to use a 3rd party tool like chutzpah to compile files manually so I can test them which is cumbersome and also slower than if VS does it on the fly.

**Comment by danquirk** [comment]
See #1398

**Comment by IgorWolbers** [comment]
Thank you for the pointer Dan. What I am looking for is not a javascript/typescript unit test runner but the option to automatically compile typescript (.ts) files to javascript (.js) in a visual studio unit test without the use of another plugin. I figure the easiest way to add this support is to add the project settings for typescript to other projects. If I am unclear please see this link where I have included a [screen shot in a question on the msdn forums](https://social.msdn.microsoft.com/Forums/vstudio/en-US/29bd24eb-04e8-42e2-bc4c-afa9e3264122/add-typescript-build-option-to-unit-test-project?forum=vsunittest#29bd24eb-04e8-42e2-bc4c-afa9e3264122)

**Comment by danquirk** [comment]
Ah, got it. I'm not an MSBuild expert. You're definitely not going to get the project properties page updated by doing that though. Can you set the action on your TypeScript files to build though (in the Properties window)?

**Comment by mhegazy** [comment]
@IgorWolbers from your msdn issue, looks like you did not add the targets file. what you need is:
1. prop files at the top
2. targets at the bottom
3. all typeScript files should be in `TypeScriptCompile` tags
4. configurations

e.g:
```xml
 <PropertyGroup>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">14.0</VisualStudioVersion>
  </PropertyGroup>
 
  <ItemGroup>
    <TypeScriptCompile Include="app.ts" />
  </ItemGroup>
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props')" />
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <TypeScriptRemoveComments>false</TypeScriptRemoveComments>
    <TypeScriptSourceMap>true</TypeScriptSourceMap>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets')" />

```

**Comment by IgorWolbers** [comment]
Thank you! I am going to try it first thing tomorrow and will report back the results.

**Comment by IgorWolbers** [comment]
Works like a charm, thank you so much!

**Comment by mhegazy** [comment]
glad it helped.

**Comment by gregveres** [comment]
HI @mhegazy or @IgorWolbers 

I have the same problem. I have a main project with TS files in it and that compiles just fine. 
I have a second project (in the same solution) that is my unit test project for my TS files. The TS files in this project do not get compiled. They do get compiled if I save them, but if I do a build clean - the JS and JS.map files don't get cleared out. If I remove them by hand, then they don't get regenerated when I build the project. 

I am trying to understand the comment by @mhegazy and what file he is referring to. Is that the csproj file for the unit test project? If so, I found that I didn't have the import statements in my csproj for the unit test project but I did have them in the main project csproj file. I found that my unit test csproj already had the <TypescriptCompile....> lines for each file in my project. And there were no typescript flags in my debug property group section. 
I added the imports and the debug flags but when I reload the project and select build for that project it still doesn't build the TS files into JS files. 

I noticed that Typescript 2.0.0 is now a nuget package that can get installed into a project. I have been using 1.8 to this point. With 2.0.0, should I be installing the typescript package into my main project and into my unit test project?

Thanks for any help.
Greg

**Comment by gregveres** [comment]
Ok I think I got it. My csproj had lots of stuff in it so I wasn't sure where to put the import lines. It seems the order is important. When I moved the second import line to the bottom of my csproj - right below the import line for c#, then it started to work. My guess, looking at the import statement is that the condition was false when it was evaluated at the beginning of the file because it hadn't hit the <TypescriptCompile...> lines yet. 

BTW, even though this is a work around, I hope something has been done so that when creating a new project and new unit test project all of this is done automatically. 

Thanks
Greg

**Comment by IgorWolbers** [comment]
@gregveres  - correct, the order is important. Why that is I am not sure. However in the most up to date versions of VS you can now include a `tsconfig.json` file and enable the `"compileOnSave": true` feature. This is the now recommended and supported way to ensure that typescript files are compiled in a VS project and also how they are compiled (based on the settings in that file).

**Comment by gregveres** [comment]
Thanks @IgorWolbers 

I did have a tsconfig.json and compileOnSave: true. That's how I have been running for months. This shouldn't and can't be the recommended and only supported way of getting JS files. It works fine for your local dev machne but when multiple people are working on a project, it would mean that every person would have to go touch all the TS files to get JS files rather than doing a build. Also, you can't have compileOnSave work on a hosted build server. I finally ran this down because I am now trying to get my TS unit tests running on Visual Studio Online and the problem I was running into was that the build didn't create the JS files so when Chutzpah ran, it couldn't find anything to run. 

So these modifications to the csproj file need to get into VS studio automatically somehow or the system is just broken. I consider it a bug that the import line wasn't put in there given that the Typescriptcompile lines were put in the csproj file.

**Comment by IgorWolbers** [comment]
@gregveres  - ah hah, got it. Yes, I too struggled for a while to get that working but the good news is that typescript unit testing in VSTS does work.
Good luck!

**Comment by gregveres** [comment]
@IgorWolbers - yup now that I have the build of TS -> JS files working my unit tests are working well on VSO. Do you use modules in TS? I am now trying to setup an MVC app that treats each MVC page as a single page app. I am trying to get TS setup with requireJS but I am having trouble figuring out the right import syntax to use and the right requireJS config settings. If you are using TS with requireJS in a similar fashion I would love to see what you are doing. greg.veres @ rogers . com if you are willing to continue the discussion.

Thanks
Greg
