### ISSUE TITLE
Compiler options pollute linked workspaces

### ISSUE THREAD

**Issue by alex-deas** [microsoft/TypeScript#35202]
**TypeScript Version:**  3.7.x-dev.20191119

**Search Terms:** workspace compiler options

**Example**

I've created an example project which replicates the issue: https://github.com/alex-deas/typescript-workspace-pollution

## Overview

When working with multiple yarn workspaces with varying strength of typechecking, a linked workspace with weaker compiler options can cause a compiler error. It appears to be that the dependencies `tsconfig.json` is ignored in favor of the app's `tsconfig.json`.

## The Issue

When building workspace-b TypeScript returns an error for `workspace-a#log`
because its parameter is implicitly typed as any.

```
../workspace-a/src/index.ts:1:21 - error TS7006: Parameter 'msg' implicitly has an 'any' type.

1 export const log = (msg) => {
                      ~~~


Found 1 error.

error Command failed with exit code 2.
```

## Steps to reproduce
```sh
yarn install
cd workspace-b
yarn tsc
```

**Comment by RyanCavanaugh** [comment]
TypeScript's doing exactly what you told it to do; `a/src/index.ts` ended up in the compilation via the symlink and was typechecked accordingly. This is a common scenario that people want to work this way.

Probably what you want to do is enable declaration emit on `a` and output to a `dist` folder so that `b` picks up `a`'s `index.d.ts` instead.
