### ISSUE TITLE
Conditional types with identical branches are not assignable to each other

### ISSUE THREAD

**Issue by weakish** [microsoft/TypeScript#35235]
**TypeScript Version:**  3.7.2

**Search Terms:** conditional types identical

**Code**

```ts
type Fo<T> = T extends string ? boolean : boolean;
type Ba<T> = T extends number ? boolean : boolean;
const convert1 = <T>(value: Fo<T>): boolean => value; // pass
const convert2 = <T>(value: Fo<T>): Ba<T> => value; // fail
```

**Expected behavior:**

`Fo<T>` and `Ba<T>` should be assignable to each other,
because no matter their condition is true or false,
their target type is always boolean (because both branches are boolean).

**Actual behavior:** `Fo<T>` and `Ba<T>` are not assignable to each other.

**Playground Link:** http://www.typescriptlang.org/play/#code/C4TwDgpgBAYg9gHgCoD4oF4pKhAHsCAOwBMBnKU4AJwEtCBzKAfigCM44AbCAQ0KgBcbDtz4BuAFChIUAEI9kaTNjwES5QgFcAtqwhVmwrr35D2x8RIDGcQpSg3CAN33AAjBiiKAFE56dNCCF4RQBKMxETDDQ-AIgxKAB6RKgwHlJSa1t7RxcqYAAmTx9YwODEVHC5BVRoqFL4pJSAMx4aTiA

**Related Issues:** not found

**Comment by jack-williams** [comment]
This naturally falls out from the assignability rules. Two conditional types are related if their extends types are identical (plus some other constraints), which is why you see the error here.

In the rare case that the true and false types are identical within the same conditional type and with the other conditional type, such as here, then the extends type is irrelevant. Given that conditional types of this form are generally not very useful, I'm not sure it's worth adding an extra rule.
