### ISSUE TITLE
Argument of type 'T' is not assignable to parameter of type 'T[]'.

### ISSUE THREAD

**Issue by Algesthesiahunter** [microsoft/TypeScript#35319]
**TypeScript Version:**  3.5.3

**Search Terms:**

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```
``` ts
function getType<T>(obj: T): string {
  const str = Reflect.toString.call(obj)
  const map: Record<string, string> = {
    '[object Boolean]': 'boolean',
    '[object Number]': 'number',
    '[object String]': 'string',
    '[object Function]': 'function',
    '[object Array]': 'array',
    '[object Date]': 'date',
    '[object RegExp]': 'regExp',
    '[object Undefined]': 'undefined',
    '[object Null]': 'null',
    '[object Object]': 'object',
    '[object Map]': 'map',
    '[object Set]': 'set',
  }
  if (obj instanceof Element) {
   return 'element'
  }
  return map[str]
}

export default function deepClone<T>(ori: T): T {
  const type = getType(ori)
  if (type === 'array') {
    let copy: T[] = []
    return copyArray(ori, copy) as T
  }
  return ori
}

function copyArray<T>(ori: Array<T>, copy: Array<T>): T[] {
  for (const [index, value] of Object.entries(ori)) {
    copy[index] = deepClone(value)
  }
  return copy
}
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:** 

**Related Issues:**

**Comment by Algesthesiahunter** [comment]
Element implicitly has an 'any' type because index expression is not of type 'number'.

**Comment by Algesthesiahunter** [comment]
If you can, please tell me how to implement my deepClone, thank you very much.

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
