### ISSUE TITLE
Type error when using generic function result as argument, but not when assigned to temp variable first

### ISSUE THREAD

**Issue by fatcerberus** [microsoft/TypeScript#35339]
Issue originally discovered by @eyelidlessness on Gitter.

**TypeScript Version:**  3.8.0-dev.20191123

**Search Terms:** `generic` `returntype`

**Code**

```ts
declare const foo: <
    R1,
    F1 extends () => R1,
    R2,
    F2 extends (input: ReturnType<F1>) => R2
>(
    f1: F1,
    f2: F2
) => any

const f1 = () => ({ a: 'a' })
const f2 = (input: { a: string }) => ({ b: 'b' })

foo(f1, f2) // Good

const makeF1 = () => f1;

foo(makeF1(), f2) // Good

const makeF1p = <T>(t: T) => f1;

foo(
    makeF1p(''),
    f2 // Error WHY :(
);

const made = makeF1p('');

foo(
    made, // This is fine
    f2
)
```

**Expected behavior:**

Both `foo()` calls should compile as the only difference is whether the result of a function call is assigned to a temporary first.

**Actual behavior:**

The first call to `foo()`, where `makeF1p()` is called inline, produces a type error at compile time.  The second, where the return value of `makeF1p()` is assigned to temp variable first, compiles fine.  The error is:

```
Argument of type '(input: { a: string; }) => { b: string; }' is not assignable to parameter of type '(input: unknown) => unknown'.
  Types of parameters 'input' and 'input' are incompatible.
    Type 'unknown' is not assignable to type '{ a: string; }'.
```

It almost seems like the type parameter inference machinery is leaking outside the scope of the call expression or something?  It's weird, at any rate.

**Playground Link:**

https://www.typescriptlang.org/play/?ts=3.8.0-dev.20191123&ssl=1&ssc=1&pln=33&pc=1#code/CYUwxgNghgTiAEYD2A7AzgF3gMyUgXPADwBQ858ASgIwA0ZFAYtfCAB4YgrBrwAUASngBeAHxU6DcpQBM9CvEYzWHLj34BLFAAcArhkKUQGXTBQAVAJ7aQRZqKFiqMkqL5Sc1Qs3kVsM7xdHcSgUSxISZHQsbBZhfmD+AG94KEIAcih0+ABfAUjUTBxleL4tPQN4FLT4TBgtAHNcxL4UgCMMtuy8iNwkPljaYqEAehH4AHE8YAioooBbKABrEGYRBJFxWIBuXrw+RZXmQSH-UfGppBmC6PhD1eptdaJzN0rzRJ29-o975m0+Ol0gJfOR-PAxvAAKIwGBIGDwADqAAkAJrwfDuAS7G4LKCgdZ-R6A4E4vruBSLUBDSHmAAWGl4jJwWhAHn8JHyQA

**Related Issues:**  I didn't find any, but @jack-williams says #30215 might be the root cause.

**Comment by eyelidlessness** [comment]
I don't know if this will help, but I was able to work around this by referencing the type parameter `T` in `makeF1p`'s return type:

```typescript
const makeF1p = <T>(t: T) => f1 as Extract<typeof f1 | T, typeof f1>;
```

**Comment by jcalz** [comment]
I think we can remove `R1` and `R2` and still reproduce with

```ts
declare const foo: <F extends () => unknown, G extends (x: ReturnType<F>) => unknown>(
  f: F, g: G) => any
```
[Playground link](https://www.typescriptlang.org/play/?ts=3.8.0-dev.20191123#code/CYUwxgNghgTiAEYD2A7AzgF3gMyUgXPADwBi8IAHhiCsGvABQCU8AvAHzwCuKA1ikgDuKADTwA4uSo06jCoQBKIDFxgoAKgE8ADiFLsWHbnwHD2DbIRJiA5oXGHOUFJoBQr5OizY2jR4wBveChCAHIoUPgAXyYPVEx4G18GeXggkPhMGABLFCSYtk4GIIAjMJLImPdcJAtbFgB6Bok8YHdPBIBbKF4QMlY-QpwAbmq8Bm7ekmZ6+CaWpDa4r3hJvu1fInVzDEJ1f2xR1xqGV3hz1Z71hlDQphEzi6T5gFEYGCQYeAB1AAkATXg+FOTCOHSw3VAvjWJG0NzuRxOj3OkJAYnm6gAFtl6DicLkQMjEq5YkA)

**Comment by shenjunru** [comment]
Similar case: [Playground link](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=29&pc=4#code/MYewdgzgLgBAZmGBeGAeAggGhgIQHwAUA3jAIbYBG2wMAvgFwxEBQMbZjBAlMnjOgG5W7Cp1KN0PJHxxD2MYGImVGOKX1JgAnkNrqmwtqEixYKUtznsATgFMoAV2uJgBKJTdcuuocwD0fjAA7tbgAObMCMSGHDDcvDAAjJgxonGk+okwANRk2AEwAA6hhTAUMFBahbYwAJYQ6YxgDgC2FLbW+g5gANZgIEFgMYrplPqkOWX5gWTWYWV1Dd19A0N6vgUh4ZFg0fLicZkp8mkEAPpHMAXFIKXlldWLjTDNbR1dvf2Dw2JjCRO5KhXGakOYLeowZZfNbeZj+QKgax2YBQHZ7dgHeLSJLHEScS7XEoLB41CEEA6vdqdBKUjo-UZlcaTIEFWbzcoQ2nWZjrIA)
```typescript
const fn = <A, B>({ a, b, c }: {
    a: () => A;
    b: (a: A) => B;
    c: (a: A, b: B) => any;
}) => {
    const t = a();
    return c(t, b(t));
};

// wrong
fn({
    a: () => 1,
    b: (a) => 1 + a, // prop b type is (a: number) => unknown
    c: (a, b) => a + b, //  arg b is unknown
});

// wrong
fn({
    a: () => 1,
    b: (_) => 1, // prop b type is (a: number) => unknown
    c: (a, b) => a + b, //  arg b is unknown
});

// correct
fn({
    a: () => 1,
    b: () => 1, // prop b type is (a: number) => number
    c: (a, b) => a + b, //  arg b is number
});
```

**Comment by fatcerberus** [comment]
Smaller repro, pretty sure this is the same issue:
```ts
declare function foo<T = {}>(): number & T;
declare function bar<T>(x: T): void;

bar(foo());  // T = never

let tmp = foo();  // T = {}
bar(tmp);
```

Contextual typing seems to be causing chained generic calls to influence each others' type parameters.

**Comment by trusktr** [comment]
I'm not sure if this is a bug (regression) or a (new) feature.

It adds one more thing that can make class-factory mixins brittle. F.e., I have to consciously write

```ts
import {Mixin, MixinResult, Constructor} from 'lowclass'

function SizeableMixin<T extends Constructor>(Base: T) {
    let _Base = Constructor(Base) // HERE
    const Parent = Observable.mixin(TreeNode.mixin(_Base))

    class Sizeable extends Parent { /* ... */ }

    return Sizeable as MixinResult<typeof Sizeable, T>
}
```

instead of

```ts
import {Mixin, MixinResult, Constructor} from 'lowclass'

function SizeableMixin<T extends Constructor>(Base: T) {
    const Parent = Observable.mixin(TreeNode.mixin(Constructor(Base))) // HERE

    class Sizeable extends Parent { /* ... */ }

    return Sizeable as MixinResult<typeof Sizeable, T>
}
```

where the definition of `Constructor` is

```ts
export type Constructor<T = object, A extends any[] = any[], Static = {}> = (new (...a: A) => T) & Static

// this is used for type casting in mixins
export function Constructor<T = object, Static = {}>(Ctor: Constructor<any>): Constructor<T> & Static {
	return (Ctor as unknown) as Constructor<T> & Static
}
```

This issue was not happening before (the second example would work), so it seems to be from some relatively new version of TypeScript within the past few months.

**Comment by fatcerberus** [comment]
I’m almost positive it’s a bug.  Type inference for a generic function shouldn’t be affected by whether the result is assigned to a variable vs. directly passing it to another generic function.

**Comment by trusktr** [comment]
Well it should, if the inference is treating the generic type like a "preprocessor", which I think is the case in other cases, as far as I've noticed. The problem is that if it wasn't the case with this particular case, then now it is a breaking change fixing it.



I know they're not preprocessors exactly (they aren't transpiled to alternate source in a precompile step), but in some cases I've seen them behave as if we were to expand the call site to be the definition of the type.


I can't remember off hand which cases I experienced generic types being treated like preprocessors.

**Comment by trusktr** [comment]
I just don't remember where I've seen this preprocessor behavior before, but I do remember that it happens when no generic args are supplied to the generic type.

@dragomirtitian was helping me with class-factory mixins, when I noticed it at some point. At least, it was the only way that I could explain what I saw at the time. @dragomirtitian Do you remember if/when types are treated as preprocessors (where the usage site is basically what causes the inference of the parameters when generic args are not explicitly supplied)?

**Comment by trusktr** [comment]
Deleted my previous comments, I was thinking something else. Yeah in @fatcerberus's example, 

```ts
declare function foo<T = {}>(): number & T;
declare function bar<T>(x: T): void;

bar(foo());  // T = never

let tmp = foo();  // T = {}
bar(tmp);

```

it seems like the generic args for `foo` should first be inferred, then that should guide inference for `bar`.

**Comment by RyanCavanaugh** [comment]
This is a fairly normal consequence of having too many type parameters in the absence of unification. We'd need to have an iterative inference algorithm to process this call as expected. The root problem is that there's a candidate via `R1` being fed to `f2`'s return type, which is why you only see this when it's in the argument position.

I would rewrite `foo` to have fewer type parameters, if applicable:
```ts
declare const foo: <R1, R2>(f1: () => R1, f2: (input: R1) => R2) => R2
```

**Comment by trusktr** [comment]
What's the performance trade off of adding an "iterative inference algorithm"?

**Comment by fatcerberus** [comment]
@RyanCavanaugh 

> too many type parameters

```ts
declare function foo<T = {}>(): number & T;
declare function bar<T>(x: T): void;

bar(foo());  // T = never

let tmp = foo();  // T = {}
bar(tmp);
```

In this case, there is only a single type parameter involved, but appears to trigger the same issue.  *Is* it actually the same issue, or is this something else?  Because I really don't expect the presence of an intermediate assignment (which is itself inferred!) to affect the inference of the function call--and yet it does.
