### ISSUE TITLE
Objects with only a certain number of keys

### ISSUE THREAD

**Issue by jt3k** [microsoft/TypeScript#35357]
```ts
type myTupe =
    | { a: string }
    | { b: number }

const variable: myTupe[] = [
    {
        a: 'lala',
        b: 1234
    },
]
```
Why doesn’t it give an error, and how to make an error?

I need to validate either object {a} or object {b} but not {a, b}

**Comment by j-oliveras** [comment]
Please follow the issue template.

It is better ask question on stackoverflow .

As a workaround, declare `myTuple` as:
```ts
type myTupe =
    | { a: string, b?: never }
    | { a?: never, b: number }
```

**Comment by jt3k** [comment]
Thanks for stackoverflow. But I would like typescript developers to see this problem.

Your option will not work if I have objects of the form {a, b, c, d, e, f ...}

**Comment by j-oliveras** [comment]
I known that the workaround is not scalable.

To solve this probably #202 is needed (or something like that).

**Comment by nmain** [comment]
Something like https://github.com/microsoft/TypeScript/issues/12936 would also fix it; Flow does the "right" thing if the two object types are exact.

**Comment by fatcerberus** [comment]
Structural subtyping means that any object with *at least* the properties of some type is, by definition, a subtype.  `A & B` is therefore a subtype of *both* `A` and `B` and there’s nothing you can do about that; this is how TypeScript’s type system was deliberately designed.

Exact types would solve your problem most likely, but if you read through the discussion in that issue, there are a lot of design challenges that make it difficult to incorporate with the current type system.

**Comment by potatofarms** [comment]
The reason this doesn't give an error is because `const variable` is assignable to `{ a: string }` or `{ b: number }`. In fact it is assignable to both on their own without the union.

If you think of typescript types as lists of valid values, like valid values for `string` being `['a','ab','abc',... and so on]` then type `{ a: string }` is the list of all objects with property "a" and `{ b: number }` is the list of all objects with property "b". Thinking of it this way, you can see how `const variable` is valid for either one of these lists. Using a union in this case makes your type less specific by increasing the number of valid values (since you are adding lists of valid values together). To make it so you need both you can `&` the types together. But if you want it to be exclusively one type or the other you can do the following (source: https://stackoverflow.com/a/53229567):
`ts
type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };
type XOR<T, U> = (T | U) extends object ? (Without<T, U> & U) | (Without<U, T> & T) : T | U;
type test = XOR<
    { a: string },
    { b: number }
>;
`

**Comment by jt3k** [comment]
Thank you all for your participation in the discussion.  It became much clearer to me.
