### ISSUE TITLE
Memory leak when switching git branches on jsconfig.json enabled projects

### ISSUE THREAD

**Issue by robgraeber** [microsoft/TypeScript#35378]
**TypeScript Version:** 3.6.3

VS Code: 1.40.1

**Search Terms:** memory leak, jsconfig, git branch

**Expected behavior:** I expect the typescript language server would use roughly the same amount of memory after switching git branches, as if you restarted the ts server from scratch.

**Actual behavior:** After switching git branches on a large jsconfig-enabled project (particularly for big diffs), the language server will take a while to load the updated files and the memory used by the language server increases by multiples of the original memory used. 

This is for an issue I'm investigating at LinkedIn where large jsconfig-enabled projects seem to have a memory leak or something else that causes the language server to be slow/unresponsive until you have to restart the language server. I can try making a project to reproduce it upon request.

**Comment by sheetalkamat** [comment]
@robgraeber Please provide tsserver log when you see memory leak. Also we would want the logs and confirmation that this repros using [typescript nightly drop](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#visual-studio-code), since the version you are using is old.. 
You can upload logs by following these steps:

1. Set `"typescript.tsserver.log": "verbose"`
2. Restart vscode or vscode insiders
3. Reproduce the problem
4. In vscode or vscode insiders, run the `TypeScript: Open TS Server log` command
5. This should open a large file called `tsserver.log`. Please share this file. Additionally you can also share file `ti.log` created next to it.
If you need to you can send the logs at `shkamat at microsoft dot com`
