### ISSUE TITLE
Object key from another Object value type error

### ISSUE THREAD

**Issue by maciejsikora** [microsoft/TypeScript#35384]
**TypeScript Version:**  3.7.2

**Search Terms:**
object keys, keys from other objects

**Code**

```ts
type CarKeys = "mercedes" | "mercedes_sedan" | "mercedes_hatch";

interface Car { color: string; } 

const KEY_MAP: Record<CarKeys, CarKeys> = {
    mercedes: 'mercedes',
    mercedes_sedan: 'mercedes_sedan',
    mercedes_hatch: 'mercedes_hatch'
}

const carType: Record<CarKeys, Car> = {
    [KEY_MAP.mercedes]:{ color: 'red'}, 
    [KEY_MAP.mercedes_sedan]: {color: 'yellow'},
    [KEY_MAP.mercedes_hatch]: {color: 'black'}
} // error here
```

**Expected behavior:**
As value of elements in `KEY_MAP` equals key of `carType` the type declaration and value should match without any error. 

**Actual behavior:**
Code shows error:
```
Type '{ [x: string]: { color: string; }; }' is missing the following properties from type 'Record<CarKeys, Car>': mercedes, mercedes_sedan, mercedes_hatch
```

**Comment by MartinJohns** [comment]
The problem is your type annotation `Record<CarKeys, CarKeys>`. The compiler knows that every property is **a** `CarKeys`, but it doesn't know which property is which `CarKeys`. As a result the type of `KEY_MAP.mercedes` is `CarKeys`, and not `"mercedes"`. Following that the compiler can't verify that you provided all three different properties in your `carType` instance.

You can fix this by being more specific in your type annotation, for example:

    const KEY_MAP: { [P in CarKeys]: P } = { ... }

**Comment by RyanCavanaugh** [comment]
https://github.com/microsoft/TypeScript/issues/7481
