### ISSUE TITLE
Allow class to extend from a Generic

### ISSUE THREAD

**Issue by GordonSmith** [microsoft/TypeScript#35382]
## Search Terms

class extends generic

## Suggestion

_I am sure this has been raised before, but I could not find a succinct example (all the related ones I found were more about mixins - specifically multiple mixins)._

**Feature Request:** Allow class to extend from a Generic Type.

## Use Cases

Functionally it would be similar to a mixin, except limited by single inheritance.

## Examples

```javascript
class BaseA {
    _id: string = "42";
}

class BaseB {
    _id: string = "43";
}

class Derived<T extends BaseA | BaseB = BaseA> extends T {
    print() {
        console.log(this._id);
    }
}

const instanceA = new Derived();
const instanceB = new Derived<BaseB>();
instanceA.print();  //  Should output "42";
instanceB.print();  //  Should output "43";
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by jcalz** [comment]
When you write `class X {}`, it introduces a *type* named `X` which is the type of instances of the class, and a *value* named `X`, which is the constructor for that class.  The type doesn't exist at runtime but the value does.  That the two have the same name is convenient but confusing.

In `class A extends B {}`, the `B` needs to be the name of a class constructor value that exists at runtime, not a type name.  You can't do this:
```ts
type Foo = { bar: string; }
class Baz extends Foo { } // error, can't extend a type
```
It's a [category mistake](https://en.wikipedia.org/wiki/Category_mistake).  For the same reason, `class A<T> extends T {}` is not possible.

----

What you presumably want to be able to do is have something that takes a generic type `T` and produces an actual runtime constructor for instances of that type, like this:

```ts
const GenericCtor = <T extends object>() => function (this: any, x: any) {
    Object.assign(this, x);
} as any as (new (init: T) => T);

// example
const UnionCtor = GenericCtor<BaseA | BaseB>();
const aOrB = new UnionCtor({ _id: "44" });
console.log(aOrB._id); // 44
```

and instead of `class A<T> extends T` you'd want to write `class A<T> extends GenericCtor<T>()`.   But hey, that's a mixin!    And you can't pass the generic `T` in that expression, as per #26154 and others.  So this is probably a duplicate.

**Comment by GordonSmith** [comment]
@jcalz thanks for the clarification on why it doesn't work today and yes as I alluded to above it is similar to mixins, but with the distinction of being a "mixin" (singular).

As far as the generated JS code goes, the above example simply ends up being syntactic sugar as per the following example:
```javascript
class BaseA {
    _id: string = "42";
}

class BaseB {
    _id: string = "43";
}

//  Without Proposed Generic Support
class DerivedA extends BaseA {
    print() {
        console.log(this._id);
    }
}

class DerivedB extends BaseA {
    print() {
        console.log(this._id);
    }
}

//  With Proposed Generic Support
class Derived<T> extends T {
    print() {
        console.log(this._id);
    }
}
const DerivedA = Derived<BaseA>();
const DerivedB = Derived<BaseB>();
```

IMO this feature has the potential to be very useful (especially when it gets combined with class decorators) while also maintaining very clean TypeScript syntax.
