### ISSUE TITLE
Reuse generic parameters of class field

### ISSUE THREAD

**Issue by senyaak** [microsoft/TypeScript#35407]
## Search Terms
reuse generic parameters 

## Suggestion
I would like to have syntax sugar for reusing generic parameters of some class field. There is a way to do it, but it looks more like hack.

## Use Cases
For example we have that code:
```ts
 class Foo {
      bar: Promise<string[]>;

      // a is the same type as type of promise in bar 
      baz(a: ????): Foo['bar'] {
        // some code
        return Promise.resolve(a);
      } 
    }
```
If we want to say that a has the same type as generic parameter of bar - we have to write something like that 
```ts
(a: Foo['bar'] extends Promise<infer U> ? U : never)
```
of course we could create type or interface - but then it is not a reuse.
```ts
 type Baz = string[];
 class Foo {
      bar: Promise<Baz>;

      // a is the same type as type of promise in bar 
      baz(a: Baz): Foo['bar'] {
        // some code
        return Promise.resolve(a);
      } 
    }
```

## Examples
It would be nice to have something like that 
```ts
(a: <Foo['bar']>) // <Foo['bar']> is resolved to Promise<string[]>
```
So we can reuse generic types without creating a type or interface for that

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
> I would like to have syntax sugar for reusing generic parameters of some class field. There is a way to do it, but it looks more like hack.

We already have a way to do this, and it's not a hack.

    type Unpromisify<T extends Promise<any>> = T extends Promise<infer R> ? R : never;
    
    Unpromisify<Foo['bar']>

**Comment by senyaak** [comment]
@MartinJohns 
That why I wrote 
> syntax sugar

The Unpromisify is not optimal solution, We have to write the type all the time we have another Generics(Observables, Proxy etc.) 
`<Foo['bar']>` is prettier than 
```ts
type Unpromisify<T extends Promise<any>> = T extends Promise<infer R> ? R : never;
Unpromisify<Foo['bar']>
```

**Comment by MartinJohns** [comment]
It's **trivially** solved with existing tools, and adding new syntax should always be the last resort. It will increase the likelihood of collisions with future JavaScript updates and it will increase the complexity of the compiler.

I really don't see the purpose for new syntax because it's a tiny bit prettier (for some people, not for me, it's very subjective).

**Comment by senyaak** [comment]
`Foo['bar']<>` could work with both. For example `Foo['bar']<0>` 
This solution have a major disadvantage - if I want to change Promise to some other class with same interface - I have to:
* change field declaration
* change 'Unpromisify' type
* change 'Unpromisify' to 'Unsometype'
What I want - is to extract type from class by knowing it structure. And if this type changes - the extracted type changes automatically

**Comment by fatcerberus** [comment]
> `Foo['bar']<>`

Now you're in the domain of higher-kinded types.

**Comment by RyanCavanaugh** [comment]
This is already extremely possible with multiple avenues of solution. We'd only add new syntax here if this was a much more common scenario with more defined use cases that weren't being adequately addressed.

There are additional complications here -- if you wrote
```ts
type Foo<T> = Bar<string, T>;
class K {
  m: Foo<number>;
}
```
From a structural perspective, it's *really* not clear if the first type parameter of `m` is `number` because that's how it lexically appears (which should **never** matter!) or `string` because that's the first type parameter given to `Bar` - or maybe `Bar` itself references another generic type? `Foo<T>` and `Bar<string, T>` ought to behave identically and you're proposing making a mechanism that breaks that.

**Comment by senyaak** [comment]
I've found recently a nice thing called `Parameters`. It takes a function and gives the tuple type back.
It would be nice to have that thing for generics.
For example:
```ts
class Foo {
      bar: Promise<string[]>;

      // a is the same type as type of promise in bar 
      baz(a: Gemerics<Foo['bar']>[0]): Foo['bar'] {
        // some code
        return Promise.resolve(a);
      } 
    }
```
