### ISSUE TITLE
Method overload selection is not consistent

### ISSUE THREAD

**Issue by dancrumb** [microsoft/TypeScript#35472]
**TypeScript Version:**  3.7.2

**Search Terms:** Method overloading, overloading

**Code**

```ts
interface FindOptions {
  where: Record<string, string>
}

export interface NonNullFindOptions extends FindOptions {
  rejectOnEmpty: boolean | Error;
}

export const whereEmailIs = (testUser: string): NonNullFindOptions => {

  return {
    where: {testUser},
    rejectOnEmpty: true,
  } as NonNullFindOptions;
};

class Model { }

class Dummy {
  public static findOne<M extends Model>(this: { new(): M } & typeof Model, options?: FindOptions): Promise<M | null>;
  public static findOne<M extends Model>(this: { new(): M } & typeof Model, options: NonNullFindOptions): Promise<M>;
  public static findOne<M extends Model>(this: { new(): M } & typeof Model, options: FindOptions | NonNullFindOptions): Promise<M> | Promise<M | null> {
    return Promise.resolve({} as M);
  }
}

// Works fine
const foo: Promise<Dummy> = Dummy.findOne({ where: { testUser: '' }, rejectOnEmpty: true });

// Why the error?
const optionsLiteral = { where: { testUser: '' }, rejectOnEmpty: true };
const qux: Promise<Dummy> = Dummy.findOne(optionsLiteral);
```

**Expected behavior:**
`foo` and `qux` should be of the same type

**Actual behavior:**
`foo` is a `Promise<Dummy>`
`qux` is a `Promise<Dummy | null>`

**Playground Link:** [Link](http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=38&pc=59#code/JYOwLgpgTgZghgYwgAgGKgCYHkAOZgD2IAzsgN4CwAUMsgO4AW0EAXMgEoQIFQYA8xMFFABzADTJBwkCIB81AL7VqEAB44eYZKEixEKAHJEDAVwA2Z9CGx5CJZGsjXSVm-iKlKNZFAgArLjAsEABRAFs8AE82ACMCAjMIOBBkAB9kEKgoHgBuRWUqNQ0oLW4SLUZmcLhgMwBJUgBeZAAKSEEAVWJoNilRAEo2IxBTC1dcd3tG2XIC2l8wEygUr1paSt82MnawLugFMWo1n39A4PCotiETCEPvBWQ4UmHRy0wJu2I8qgVv6gQzE9SABZAgYCBmcjIJRUf6A4ikAAiJjCYUis28OBMMTMwAQkjAcHw+Jg7xAED4wIcqicGBBYIhsjaDGAxC2yHJdBag2QVIeADJkGBIjgIAQYLyGWYJARbB4APxscZykg8gAK2TCrIpVPSIHMZlk31oWJxeIJRPNpOswR11Np9PBhuZrPZnO5bD5yEFwtF4slTplKrZyBeBuVk2I6s12spRqOyFNuPxgktJLJdscEGcAcZLpDZA5EC5PK9PpFYoloMDyFlkaV72DaVDxnDjcj0YIWu6cebGq7sd1HINM1WawWSxS-e7EAAdL5iAkAG4QFpkB5PXn9Y3Q-KwqhlQTIGDxNjT2PI1GRGbNS9o2fW7Dktf0JibKE7PZQNgAch-0IkXwAgQIJQgiYUrigG5oW3AoAHo4OQAB1Bh0TAJgHCyHh5X+DwtBiOBv2Qc8ezva9kFvFF70fW0Wg2CBqlqBoWj-fpYP3BDkNQoUMOgbIoBwg88NrJtmnoxj6mIFif3Yw98LgAAvM8Y1IqjyMoq8HwzFo60+djqE4lC0N4rCBNw8oRMjAAZYBdDgSFmkLej2U-boiL-ACTmA0CLggoUoJQX5zKPABHExVGUgdVKvG9kDIrSbWfXSPBsuyzG3IA)

**Related Issues:** 
It was pointed out in https://stackoverflow.com/questions/59162017/how-does-ts-select-the-wrong-method-signature that the signature selection is dependant on the order in which they are declared. What's not clear is why the selection seems to depend on the use of an object literal vs a variable.

**Comment by AnyhowStep** [comment]
Your overload order is incorrect.
You want most specific first. Least specific last.

NonNullFindOptions is more specific than FindOptions

**Comment by dancrumb** [comment]
This is an SSCCE, pulling signatures from a 3rd party library. You're right that the `M`s are not useful here, but I don't believe that's impacting things.

However, let me reiterate: the issue here is not with which signature TS selects. It's that the signature selection is inconsistent. The link I provided shows that the type of `foo` is _not_ the same as any of the other variables.

By my reckoning, the behaviour should be the same, regardless of how the value of `options` is passed in.

It's worth noting that adding *any* type assertion to `const foo: Promise<Dummy> = Dummy.findOne({ where: { testUser: '' }, rejectOnEmpty: true });` results in a change of the type of `foo` to `Promise<Dummy | null>`.  

```
Dummy.findOne({ where: { testUser: '' }, rejectOnEmpty: true });
// Promise<Dummy>

Dummy.findOne(<any>{ where: { testUser: '' }, rejectOnEmpty: true }); 
// Promise<Dummy | null>

Dummy.findOne(<NonNullFindOptions>{ where: { testUser: '' }, rejectOnEmpty: true }); 
// Promise<Dummy | null>

Dummy.findOne(<FindOptions>{ where: { testUser: '' }, rejectOnEmpty: true }); 
// Promise<Dummy | null>
```

I cannot find any documentation that explains this behaviour.

**Comment by IllusionMH** [comment]
It should be in order from first to last (with small exceptions for literals as parameters types which are forced before wide types).

In your case it looks good if you change order of overloads as proposed above by **AnyhowStep**
[Example](https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgGKgCYHkAOZgD2IAzsgN4CwAUMsgO4AW0EAXMgEoQIFQYA8xMFFABzADTJBwkCIB81AL7VqEAB44eYZKEixEKAHJEDAVwA2Z9CGx5CJZGsjXSVm-iKlKNZFAgArLjAsEABRAFs8AE82ACMCAjMIOBBkAB9kEKgoHgBuRWUqNQ0oLW4SLUZmcLhgMwBJUgBeZAAKSEEAVWJoNilRAEo2IxBTC1dcd3tG2XIC2l8wEygUr1paSt82MnawLugFMWo1n39A4PCotiETCEPvBWQ4UmHRy0wJu2I8qgVv6gQzE9SABZAgYCBmcjIJRUf6A4ikAAiJjCYUis28AHpMcgsAA3aBmAhwDCkHjgqDIBAMZIiCAYI7IHAmGJmYAISRgOD4Dkwd4gCB8YEOVROUnIUHgsyyNoMYDELbIAV0FqDCXQ5AAMmQYEiOAgBBgErBEIkBFsHiGxnMb2sHw8aoACtkwvLBcDZN9aMzWezOdy-Xy7QKhSKxSCTdLZfLFcrVWxhQ9tbr9YbjVKzRaSAB+NjjLPEJ0ut2h9IgG2exk+tkcwQB3n891hiDOdMQmVgOUKqFxtWJrU6vUGo2S03Ic2Tbv5ydpZAvG3Tz5Fgiu7pCmbpZ0rkvCssVjHHBZLFJb1cQAB0vmICQJLTIDyeEv6Xuh+VhVDKgmQMHibFPJeRVFIhmZpALRc8g2wAU73oJhNihHY9igNgAHIUOhCRfACBAglCCJdSuKAbmhZ8CmxOcCAcLIeH+DwtBiOBkOQf81zA4DkFAlFwMg4IIBaDYIGqWoGhaND+lI99yKMKjsigWjynHAsONgqowhqepiFElCJM-ei4AALz-YtWK49jOKAiDGxaCclz+KgpMo6BZPkr8bI8AAZYBdDgSFmjIFT4P8xDuiYtCMJObDcIuAidSIlBfhcrQAEcTFUIztxMoCQOQNjLODPi3JITzvLMCSCl0x50rPPg2Oy3KeOg-yBMVYKemQMKDgis48MuWLiIUHS6OQGIqoA0y6tMvKoL4vhkmApq4NYBCIE6ELUPQzqsO66Loj6+Ln2QRKqVGzK0QmiyGpm+cxneAtZAW5gWpW3Y1vajbMNOHDznw3brn2nJDsknEQnUQJ6RknhiCOjATsFWrlPqqy+EXDx7oCpaguepD1vCravp6mK-pIgGjqWli4fGhHJsumDmuW1a2o64nAYqmBYZqynzO4qyDqAA)

Otherwise any object assignable to `NonNullFindOptions` will be assignable to `FindOptions` and therefore that overload with `Promise<M | null>` is always picked.

**Comment by dancrumb** [comment]
I'm not sure how to be more explicit.

The issue is **not** which signature is being selected. 

The issue is that the selection is not consistent. The four examples in https://github.com/microsoft/TypeScript/issues/35472#issuecomment-561314239 should all have the same type should they not?

If the behaviour shown here is correct, is there any documentation that explains why?

**Comment by AnyhowStep** [comment]
Object literals are subject to excess property checks

**Comment by AnyhowStep** [comment]
To illustrate the problem you're having better,
```ts
interface FindOptions {
  where: Record<string, string>
}

export interface NonNullFindOptions extends FindOptions {
  rejectOnEmpty: boolean | Error;
}

export const whereEmailIs = (testUser: string): NonNullFindOptions => {

  return {
    where: {testUser},
    rejectOnEmpty: true,
  } as NonNullFindOptions;
};

//Error
const freshA: FindOptions = { where: { testUser: '' }, rejectOnEmpty: true };
//OK
const freshB: NonNullFindOptions = { where: { testUser: '' }, rejectOnEmpty: true };

//OK
const nonFreshA: FindOptions = whereEmailIs('');
//OK
const nonFreshB: NonNullFindOptions = whereEmailIs('');

```
[Playground](http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=26&pc=1#code/JYOwLgpgTgZghgYwgAgGKgCYHkAOZgD2IAzsgN4CwAUMsgO4AW0EAXMgEoQIFQYA8xMFFABzADTJBwkCIB81AL7VqEAB44eYZKEixEKAHJEDAVwA2Z9CGx5CJZGsjXSVm-iKlKNZFAgArLjAsEABRAFs8AE82ACMCAjMIOBBkAB9kEKgoHgBuRWUqNQ0oLW4SLUZmcLhgMwBJUgBeZAAKSEEAVWJoNilRAEo2IxBTC1dcd3tG2XIC2l8wEygUr1paSt82MnawLugFMWo1n39A4PCotiETCEPvBWQ4UmHRy0wJu2I8qgVv6gB6f6ZbJQahlQTIGC+YgMACCbHGtg8yGaZHoTE25GQOz2UDYAHJ8cgDicAgggqEImBotioDdid9AVgANJgjxaKEQGEAISGxnMb2sH2RqPRzC22K5u26eOQhOJEl8ZIpF2pVzpKF+BSZrKo4K0ICIqGhcIR7yRUzFvmqtQaLUJ-UZ-xZbPKyENIGNXIYvOQLwFiMmTStEBt9WI9vxjuoQA)

**Comment by dancrumb** [comment]
Is this concept of "fresh" and "non-fresh" documented somewhere?

**Comment by dancrumb** [comment]
Looks like this covers it: https://basarat.gitbooks.io/typescript/docs/types/freshness.html

**Comment by dancrumb** [comment]
And regarding:

> The real problem here is that the overloads are in the wrong order.
> And, in general, the other real (real-real) problem is that overloads are used in the first place.

Regarding the 'real problem', I agree that there's an issue with the library, but a) I don't own it, so fixing this issue takes some time and b) the problem I was having was that (absent an understanding of Freshness), the differing behaviours made no sense.

They do now - thank you!

Regarding the "real-real" problem are you talking specifically about the use of overloads in an ORM or just in general? I note that you do a fair amount of work with TS and ORMs, so is this a comment on their decision to make `findOne` an overloaded method, or something more?

I appreciate that this may go out of scope of this issue, but I'm not sure how else to pose the question :)

**Comment by AnyhowStep** [comment]
> Regarding the "real-real" problem are you talking specifically about the use of overloads in an ORM or just in general? 

Just in general.

I try to avoid them when I can but I am guilty of using overloads, too, though.
I just did a search and found 16 overloaded functions out of 584 `export function` matches.

If you have to use overloads, it's better if parameters in the same position have incompatible types (rather than having one be a subtype of the other). 13 of my 16 overloads do this.

So, stuff like,
```ts
declare function foo (arg : true) : number;
declare function foo (arg : false) : string;
```

And if one is a subtype of the other, the more specific type should be before the less specific type.

So, stuff like,
```ts
declare function foo (arg : true) : number;
declare function foo (arg : false) : string;
//It's also usually a good idea to have a "catch-all" overload that unions all parameters and return types.
declare function foo (arg : true|false) : number|string;
```

-----

As an aside, shouldn't it be,
```ts
rejectOnEmpty: true | Error;
//And not `boolean|Error`?
```

What happens if `rejectOnEmpty` is `false` and the ORM does not find a matching row?
It can't return `null` because it said it wouldn't return `null`.
It can't reject because you said `rejectOnEmpty : false`.
Seems confusing.

**Comment by dancrumb** [comment]
Thanks. I agree with everything you said.

I think this specific library just takes us down a rabbit hole into some of the more esoteric parts of TS that you rarely need to worry about: overloaded methods with parameters that are in the same inheritance chain is definitely rarefied air.

And I definitely agree that the definition of `rejectOnEmpty` is straight-up weird.

I'm going to close this out as the issue is understood and WAD.

Thanks!

**Comment by papb** [comment]
Thanks @dancrumb for exploring this and @AnyhowStep for the detailed explanations!!
