### ISSUE TITLE
Variable is used before being assigned

### ISSUE THREAD

**Issue by timonson** [microsoft/TypeScript#35529]
The following error comes up using the `--strict` option: **error TS2454: Variable 'd' is used before being assigned.**

```typescript
let a: unknown = 30
if (typeof a === "number") {
  var d = a + 10
}
console.log(d)
```

**Comment by timonson** [comment]
Why the down votes?

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.

It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
