### ISSUE TITLE
No error when using string variable key

### ISSUE THREAD

**Issue by steabert** [microsoft/TypeScript#35538]
**TypeScript Version:**  3.7.2

**Search Terms:** "string variable key", "generic string as key"

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
interface A {
  a: number
}
const invalidKey = 'bla'

const a: A = { a: 1, ['bad']: 2 } // not possible, as expexted since A doesn't have 'bad'
const b: A = { a: 1, [invalidKey]: 2 } // not possible, as expexted since A doesn't have 'bla'
const c: A = { a: 1, [Date.now().toString()]: 2 } // possible, even though key is a string !?
```

**Expected behavior:**

Not able to use generic string as key.

**Actual behavior:**

Able to use generic string as key.

**Playground Link:** 

https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=8&pc=65#code/JYOwLgpgTgZghgYwgAgILIN4FgBQzlwBcyIArgLYBG0uAvrggPYgDOYyoAbnADbAAmAaQgBPZAF5kAcko84U3A2ZsCxdJIyrkARgA0yANoy4-KQF1iAJmS1kAejvIA5sE4QWyaFEZQlrdpRqEphaeoZcvALCIhbI1rYOzq7unlDevjhM-sgIQRqh+gYAInCQAHQgjADuABQAlGVgjADKYFCgTvWx8faOlanpyACEAPxAA

**Related Issues:**

**Comment by MartinJohns** [comment]
Here's the playground link that you decided to omit: https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgILIN4FgBQzlwBcyIArgLYBG0uAvrggPYgDOYyoAbnADbAAmAaQgBPZAF5kAcko84U3A2ZsCEzEWQBGADTIA2jLj8pAXWIAmE7WQB6G8gDmwThBbJoURlCWt2lNRgaOvpcvALCImbIltZ2js6u7lCe3jhMvsgIAUG6egAicJAAdCCMAO4AFACURWCMAMpgUKAO1VExtvalSSnIAIQA-LhAA

---

All three versions show an error... and that error is a syntax error. In all three versions you have a closing `]` too much. [When you remove these invalid characters](https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgILIN4FgBQzlwBcyIArgLYBG0uAvrggPYgDOYyoAbnADbAAmAaQgBPZAF5kAcko84U3A2ZsCEzEWQBGADTIA2jLj8pAXWIAmWsgD015AHNgnCC2TQojKEtbtKajBo6+ly8AsIiZsiWNnaOzq7unt4qCP6BunoAInCQAHQgjADuABQAlLlgjADKYFCg9mWR0bYkjG5QHlDIAIQA-LhAA) all three lines show no error anymore. So it's really unclear what your issue is.

**Comment by steabert** [comment]
Sorry for the omission, though it wasn't that I decided to omit it, rather I was (very) sloppy when reporting. Mea culpa.

I corrected the syntax errors, and included a correct playground link. The errors that are reported on the first two cases are that they cannot be assigned to type `A`, while the third line gives no such error, even though the key can be any string.

**Comment by IllusionMH** [comment]
I think that example should look like this
https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgILIN4FgBQzlwBcyIArgLYBG0uAvrggPYgDOYyoAbnADbAAmAaQgBPZAF5kAcko84UhszbI2UYqtABzCdICMAJgDMUgNy5FrdkTQ6MBYroA0yANoy4-KQF1i+5LWQAekDkTWBOCBZkaChGKAtlSmJ0STtrJ1cuXgFhER9kPwDg0PDI6KhY+JwE9gRk23tkDJcAEThIADoQRgB3AAoASg6wRgBlMCgtQfzCoJDu8srkAEIAfhrkfnrUxubVGf85kkZFuJX1nCA

And the question is - why there is no error excess property check error if computed property results in `string` type, but errors when computed property is string literal type?

**Comment by RyanCavanaugh** [comment]
When TS can detect what the name is and recognizes that the name doesn't correspond to a declared property, an error is issued.

When the name isn't statically determinable, we error on the lenient side and assume you're using some construction that will resolve to a declared property.

For consistency, there isn't any special-casing around types whose known property names have been exhausted.
