### ISSUE TITLE
Generic array types. Bug or Feature?? IDK

### ISSUE THREAD

**Issue by samuelgjabel** [microsoft/TypeScript#35540]
Hey 👋. I have issue with generic array types inside function.. But this is some special issue so IDK if that is bug or feature or correct behaviour? 

If i have 2 objects:

`const a = {
  model: {
    key1: true,
  },
}
const b = {
  model: {
    key2: true,
  },
}`

And generic function: 
`
interface Itest<T> {
  siblings: {
    [k in keyof T]: {
      table: T[k]
      key: keyof  T[k]['model'] 
    }
  }
}
`

IMAGE here becouse github remove generic :D 

<img width="294" alt="Screenshot 2019-12-06 at 10 12 55" src="https://user-images.githubusercontent.com/5537298/70310942-fc520b00-1810-11ea-8791-ddb3b90312e4.png">
Iknow that T[k]['model']  gives me error but forgot about that right now.. I have fix it in my real world app by defining  T.

And if I call function and push inside array object with model.table = object b, key will be keyof that model. Which is fine..

`test({
  siblings: [
    { table: b, key:'key2',},
  ],
})`

So ts as well give me advice about that key like this:
<img width="593" alt="Screenshot 2019-12-06 at 10 00 19" src="https://user-images.githubusercontent.com/5537298/70310120-3b7f5c80-180f-11ea-9fb7-a4585ae66600.png">
<img width="229" alt="Screenshot 2019-12-06 at 10 15 16" src="https://user-images.githubusercontent.com/5537298/70311155-5e127500-1811-11ea-9620-2da4794361f0.png">

If I put inside that array another object with same model (object b)..everything is fine.. so no errors..

But if put there as well object a. Like this: 
<img width="257" alt="Screenshot 2019-12-06 at 10 01 54" src="https://user-images.githubusercontent.com/5537298/70310244-72ee0900-180f-11ea-9d37-ca6ced7e0513.png">

It gives me error... 
I know that mismatch is propably becouse of typescript wrap this generic array models into enum type objects so it cant be accessible.. becouse keyof of that is unknown. 

For example if i remove keyof from ITest interface, intelisense gives me that key is type:
`{
    key2: boolean;
} | {
    key1: boolean;
} | undefined

But I want to have that  that key will only belong to his model inside that array and not to enum types of all array models. :( So key inside will be only keyof that model.

{model:abc, key:'aha'} 
=> key will be always keyof that model

typescript gives me:
[ 
{model:abc, key:'aha'} ,
{model:xyz, key:'aha'} ,
]
=> 
that key is enum of both types model abc & xyz so keyof (xyz | abc) = unkown.

is there some way how to solve this? :) 

Thanks for advice.

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.

It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
