### ISSUE TITLE
Computed properties

### ISSUE THREAD

**Issue by jamiewinder** [Microsoft/TypeScript#3562]
```typescript
const nameMember = "_name";

class Cls {
    private [nameMember]: string;

    constructor(name: string) {
        this[nameMember] = name;
    }
}
```
Could be wrong, but isn't this now legal syntax? In both ES5 and ES6 modes, this generates the error:

"*A computed property name in a class property declaration must directly refer to a built-in symbol.*"

Computed properties are listed on the Roadmap for Typescript 1.5 - is that still the case? If so, will ES6 mode be required, or will it work with ES5? Thanks.

**Comment by RyanCavanaugh** [comment]
Computed property names are valid in object literals. They are not supported as class property declarations (note that property declarations are not part of the ES6 class specification, so this is orthogonal to ES5/ES6).

**Comment by jamiewinder** [comment]
Understood, thanks. I think a similar syntax would be useful specifically for TypeScript though. The code above effectively indicates that is a property is accessed on an instance of this case with the const variable (i.e. a[nameMember]) then assume the return value is a string. Perhaps this is something different entirely, but it'd be very handy.

**Comment by JsonFreeman** [comment]
The feature you are asking for is constant propagation. We'd have to recognize in certain contexts that a const declared name corresponds uniquely to a single value. Then we could support class properties for these kinds of constants.

One requirement is that we could only support string or number literals because we have to know the value of that const at compile time. Otherwise we cannot know if two different consts refer to the same value.

**Comment by mhegazy** [comment]
Constant propagation is covered by #3964
