### ISSUE TITLE
Compiler API is unable to get comments of variable declaration in .d.ts

### ISSUE THREAD

**Issue by shrinktofit** [microsoft/TypeScript#35620]
**TypeScript Version:**  3.7.2

**Search Terms**: Comments; API

**Code**
Input code:
```ts
declare module "index" {
    /**
     * @deprecated Hi
     */
    export const HelloMoto: {};
}
```
Test code:
```ts
import ts from 'typescript';
/* node is HelloMoto VariableDeclaration */
function getComments(node: ts.Node) {
    const sourceFileText = node.getSourceFile().text;
    ts.getSyntheticLeadingComments(node); // undefined
    ts.getSyntheticTrailingComments(node); // undefined
    ts.getLeadingCommentRanges(sourceFileText, node.getStart()); // undefined
    ts.getTrailingCommentRanges(sourceFileText, node.getEnd()); // undefined
}
```

**Comment by ajafff** [comment]
The Jsdoc of `VariableDeclaration` is actually on the containing Statement.

The VariableDeclaration starts at `HelloMoto`, the containing DeclarationList at `const` and the statement at `export`.
Scanning for comments is purely syntactic, therefore you need to scan at the correct position. 

Also note that you should use `node.pos` instead of `node.getStart()` since `getStart` skips comments so you'll never find a Jsdoc comment at that position.

**Comment by shrinktofit** [comment]
> The Jsdoc of `VariableDeclaration` is actually on the containing Statement.

Thx!
