### ISSUE TITLE
Exending a class gives wrong typing

### ISSUE THREAD

**Issue by wuifdesign** [microsoft/TypeScript#35648]
**TypeScript Version:**  3.7.3

**Search Terms:**
extending class, return typing, this call inside super 

**Code**

```ts
class Foo  {
  foo() {
    return {
      a: 0
    }
  }

  getFoo() {
    return this.foo();
  }
}

class Bar extends Foo {
  foo() {
    return {
      ...super.foo(),
      c: 0
    }
  }
}

const a = new Bar();

console.log(a.getFoo().a);
console.log(a.getFoo().c); //TS2339: Property 'c' does not exist on type '{ a: number; }
```

**Expected behavior:**
`a.getFoo().c` shouldn't display a typing error.

**Actual behavior:**
`a.getFoo().c` displays a typing error (TS2339: Property 'c' does not exist on type '{ a: number; }', 

**Additional Information:**
If i also override the `getFoo()` it works fine:
```ts
class Foo  {
  foo() {
    return {
      a: 0
    }
  }

  getFoo() {
    return this.foo();
  }
}

class Bar extends Foo {
  foo() {
    return {
      ...super.foo(),
      c: 0
    }
  }

  getFoo() {
    return this.foo();
  }
}

const a = new Bar();
console.log(a.getFoo().a);
console.log(a.getFoo().c); //works
```

**Comment by fatcerberus** [comment]
The compiler first infers `getFoo()` as returning `{ a: number }` and has no way to know that the non-overridden method suddenly returns the subclass instead, because it doesn’t look into function implementations.  Since `{ a: number }` is a valid structural supertype of `{ a: number, c: number }`, there’s no issue with the implementation from the compiler’s perspective—the problem is at the call site, which is indeed where you see the error.

One way you can probably make this work how you want is to annotate `getFoo` as returning `this`.

**Comment by RyanCavanaugh** [comment]
You could write
```ts
  getFoo(): ReturnType<this["foo"]> {
    return this.foo() as ReturnType<this["foo"]>;
  }
```

**Comment by wuifdesign** [comment]
looks like @RyanCavanaugh workaround is working :)

but i still think the automatic typing should work here. as the code is valid code it should be valid for typescript too. or am i wrong?

**Comment by fatcerberus** [comment]
It's valid code, TypeScript just isn't smart enough to infer the specific types you're looking for.  tsc can't "double back" and infer the types of all the inherited methods again - they've already been inferred.  So all it can do is validate that `Bar` is correctly implemented given the pre-inferred types--and it is.  By process of elimination, that means the call site is in error.

**Comment by RyanCavanaugh** [comment]
It's not even clear what your intent is here -- the base class might be promising to return what *its* implementation of `foo()` returns, *or* it might be promising to return what *its instantiated form* of `foo()` returns. The former is a much safer assumption.

**Comment by fatcerberus** [comment]
In addition to what @RyanCavanaugh said, this is particularly illuminating w.r.t. soundness:
```ts
class Foo  {
  foo(): this {
    return {
      a: 0
    }
  }

  getFoo() {
    return this.foo();
  }
}
```

Now an error is flagged on the implementation of `foo()` because there's no guarantee that the subclass(es) will override it.  The compiler therefore *cannot safely infer* `foo()` as returning `this`, and in that light, the types that are actually inferred make perfect sense.
