### ISSUE TITLE
Contravariance relation broken in generic interface

### ISSUE THREAD

**Issue by winhillsen** [microsoft/TypeScript#35669]
**TypeScript Version:**  Nightly

**Search Terms:**
contravariance interface generic

**Expected behavior:**
The `method` property of `strange` should be a type error, because a function accepting only `number` cannot be used to accept `number | null` as prescribed by the interface `Strage<number>`.

In fact, I expect both `Expected` and `Strange` to exhibit the same behavior with regards to variance, since the only difference between them is that the callable is direct vs is a property, which seems to be of no relevance to variance.

**Actual behavior:**
There is no such error. As a result, `null` will be passed to a function that accepts `number` and we would still get an explosion on the `.toFixed` in both cases :boom:, even though TypeScript tells us the that the `strange` case is safe.

**Code**
```ts
export interface Expected<T> {
    (value: T|null): void
}

const expected: Expected<number> = (arg: number) => console.log(arg.toFixed(2));
expected(null);

export interface Strange<T> {
    method(value: T |null): void;
}

const strange: Strange<number> = {
    method: (arg: number) => console.log(arg.toFixed(2))
}
strange.method(null);
```

<details><summary><b>Output</b></summary>

```ts
const expected = (arg) => console.log(arg.toFixed(2));
expected(null);
const strange = {
    method: (arg) => console.log(arg.toFixed(2))
};
strange.method(null);

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](http://www.typescriptlang.org/play/?ts=3.8.0-dev.20191212#)

**Comment by dragomirtitian** [comment]
Actually this is a deliberate design decision. As stated in the [PR](https://github.com/Microsoft/TypeScript/pull/18654) introducing strict function types (which is the option that makes parameters behave contravariantly instead of bivariantly) 

> The stricter checking applies to all function types, **except those originating in method or construcor declarations**. Methods are excluded specifically to ensure generic classes and interfaces (such as Array<T>) continue to mostly relate covariantly

(**Emphasis added**)

In this case `T` is a subtype of `T | null` so the function signatures relate bivariantly allowing the assignment. If you want to ensure contravariant behavior use a function field:

```ts
export interface Strange<T> {
    method: (value: T |null) =>  void;
}

const strange: Strange<number> = {
    method: (arg: number) => console.log(arg.toFixed(2)) // error now
}
```

[Playground Link](https://www.typescriptlang.org/play/?ssl=14&ssc=2&pln=8&pc=1#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgUXGG1QBMAeAFQD44BvAWACg5W4AKAN0wBsBXYAC44lAD5I+PHgEphnCAlLMAvs2bYISAM7xQYYmWGF9JYBQkBbAEZpaAXg6YoAc2GWbUaXDu0N2iDzAAHQ8EM7sTs5BMBAAYgggZuwATNLSANzMegZJElIZakx60PDIqBg4eADKMFCYSM7AVLSMLGwWwDAAFhCkwly8AsKUcOKSMt60cPKKmUyqTOqaOnA6dQ1CcDXrjeTutt70zGxwHd29-ZFufNZoXj5wfloBwaHhkdFxCUmpXgD0fzgaCg0DgSAgAHcVIUnvA1vVGgB5ADWwm2CKa+yg9iObVYZx6fUcLmutygozB4zg918yxeITC7AiLjgAH5WXAAAzST7xRKkFJpOAAuCaHgATzg3QQWkQsogyOhTHhGyCBN67DyMnSQA)

**Comment by winhillsen** [comment]
@dragomirtitian Thank you for digging this, I wouldn't've figured this out myself at all!

I think I need to try to understand the general rules regarding how TypeScript treats variance relation better.
