### ISSUE TITLE
Destructuring an optional property with union containing literal type should not be widen if the default value is compatible with the union

### ISSUE THREAD

**Issue by vilic** [microsoft/TypeScript#35693]
**TypeScript Version:**  3.8.0-dev.20191214

**Search Terms:** union, default value, literal, destructuring, optional

It surprised me a little bit not finding a duplicate myself. This is a frequent issue for us, though most of the time we can "fix" it with type assertion.

**Code**

```ts
interface Foo {
  bar: 'yo' | 'ha' | undefined;
}

let { bar = 'yo' } = {} as Foo;

bar; // expecting `bar` to be `'yo' | 'ha'`, but gets `string` instead
```

**Playground Link:** http://www.typescriptlang.org/play/?ts=3.8.0-dev.20191214#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChnIBGcUAXMgOQCe6FyAPpQBZx2MCuIAJhDKBFwDcuAL65cAGwhgcREsgC8lGnRGKcauAGc0mYbmJRByAPQnkEAB4AHCAjCgA5sgAGhl8jBZCKF9VoMzKwuADRE7DKO0jouWmBQTh6gcRBwXEA

**Related Issues:**

**Comment by rusev** [comment]
You should be using `let { bar = 'yo' as const } = {} as Foo;`, otherwise that `'yo'` is just string value rather than the literal type `yo`. 

Updated example: https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=77&pc=72#code/JYOwLgpgTgZghgYwgAgGIHt3IN4FgBQyyARnFAFzIDkAnulcgD7UAWcDzAriACYQygIPANwEAvgQIAbCGBwkyyALzU6DOAGdkCdCA1yxynIc1pMo-AVJRhyAPR3kEAB4AHCAjCgA5sgAG1n7IYFjEKH609Eys7H4ANCScct6yWn76UD5BoPoQcDxAA

**Comment by vilic** [comment]
@rusev I am not looking for a workaround though. The compiler itself should just do the job without extra hint.

**Comment by rusev** [comment]
I'm 100% with you, but I think this is intended behavior :).

**Comment by RyanCavanaugh** [comment]
@ahejlsberg thoughts?

**Comment by ahejlsberg** [comment]
My immediate thought is that this is supposed to be equivalent, but isn't:

```ts
let bar = ({} as Foo).bar ?? 'yo';  // 'yo' | 'ha'
```

So, it seems like a fix is merited.
