### ISSUE TITLE
Context typing doesn't work for object literals

### ISSUE THREAD

**Issue by anstarovoyt** [Microsoft/TypeScript#3570]
Context typing doesn't work for object literals. Simple example:
```typescript
var a: {
	do1():(s:string) => void
}

a = {
	do1() { 
		return s => { 
			s. //should be string type
		}
	}
}
```

**Comment by DanielRosenwasser** [comment]
Strangely enough, this might be [per spec](https://github.com/Microsoft/TypeScript/blob/7ee698c450e8317651ecb102534b0601da5ecb9f/doc/spec.md#4.19):

> ## <a name="4.19"/>4.19 Contextually Typed Expressions
* [...]
* In a contextually typed object literal, each property value expression is contextually typed by
  * the type of the property with a matching name in the contextual type, if any, or otherwise
  * for a numerically named property, the numeric index type of the contextual type, if any, or otherwise
  * the string index type of the contextual type, if any. 

Notice that it doesn't mention *method declarations*, so the following actually will work:

```TypeScript
var a: {
    do1():(s:string) => void
}

a = {
    do1: () => { 
        return s => { 
            s. //should be string type
        }
    }
}
```

The question is whether or not it should be. While methods are declarations, not expressions, this behavior leads to a pretty inconsistent experience. @ahejlsberg would be better suited to answer this.

**Comment by anstarovoyt** [comment]
@DanielRosenwasser anyway this example works fine:
```
var a: {
    do1(s:string):void
}

a = {
    do1(s) { 
        s. //actually is the 'string' type
    }
}
```
so context typing works for parameter types and doesn't work for return type.

**Comment by DanielRosenwasser** [comment]
Yes - actually I just noticed the following from the same section of the spec:

> * In the body of a function declaration, function expression, arrow function, method declaration, or get accessor declaration that has a return type annotation, return expressions are contextually typed by the type given in the return type annotation.

So this is still per spec, but for a different reason. I'd still like to get @ahejlsberg's take.

**Comment by anstarovoyt** [comment]
@DanielRosenwasser I guess the main point is ' that has a return type annotation' in the part of spec.

**Comment by ahejlsberg** [comment]
Agreed, this is inconsistent. We already have it captured in #1610.

**Comment by anstarovoyt** [comment]
@DanielRosenwasser @ahejlsberg thank you!
