### ISSUE TITLE
Null Coalesce Operator Breaks Syntax Highlight in Visual Studio 2017

### ISSUE THREAD

**Issue by busyscout** [microsoft/TypeScript#35725]
Null coalesce operator breaks syntax highlighting in VS2017.
Example:
```typescript
class NullCoalesceTest {
    private test() {
        const x = this.getNumber();
        const y = this.getNumber();
        //this.add(x, y); //error
        this.add(x || 0, y || 0); //OK
        this.add(x ?? 0, y ?? 0); //Breaks syntax highlighting in VS2017
    }

    private getNumber() {
        if (new Date().getMilliseconds() % 2 === 0)
            return 1;
        return null;
    }

    private add(x: number, y: number) {
        return x + y;
    }
}
```
VS 2017
![VS2017 Null Coalesce](https://user-images.githubusercontent.com/23096209/70991539-b3d00280-20d8-11ea-82a1-9df15f6c8ecb.png)

VS 2019
![VS2019 Null Coalesce](https://user-images.githubusercontent.com/23096209/70991607-d95d0c00-20d8-11ea-8edd-b471db9e5c4e.png)

Typescript 3.7.3.

**Comment by DanielRosenwasser** [comment]
I assume this isn't an issue in VS2019, just 2017?

**Comment by busyscout** [comment]
Yes. Just VS2017. 15.01.2020, 04:57, "Daniel Rosenwasser" <notifications@github.com>:I assume this isn't an issue in VS2019, just 2017?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by minestarks** [comment]
Unfortunately this isn't something we'll be able to fix for VS 2017 since syntax highlighting in VS uses the TextMate grammar files, which can't be updated out of band. The new syntax is supported in VS 2019 16.4 onwards. 

Here's a (admittedly slightly hacky) workaround you can use: Copy the contents of Common7\IDE\CommonExtensions\Microsoft\TypeScript\tmLanguage from a VS 2019 16.4 installation over to your VS 2017 installation.
