### ISSUE TITLE
optional chaining does not work for unknown

### ISSUE THREAD

**Issue by nkappler** [microsoft/TypeScript#35799]
**Search Terms:**
optional chaining unknown

**Code**
In a real world scenario I have an api which returns unknown
```ts
const prop: unknown = { key : { value: "Hello World" } };

const helloworld = prop?.key?.value;
```

**Expected behavior:**
I want to assign `prop?.key?.value` to `helloworld`, since it exists;

**Actual behavior:**
I get the following error for prop:
const prop: unknown
Object is of type 'unknown'.(2571)

**Playground Link:** 
https://www.typescriptlang.org/play/?ssl=2&ssc=22&pln=1&pc=1#code/MYewdgzgLgBADgJxHAXDArmA1mEB3MGAXhgG8YsBTATxjXIDcBDAG3UrQCIAJSllkDADqIBCwAmnGAF8ZAbgBQC0JFgALPgLyiJxeEjgB+AHRVqJ5m0pygA

**Comment by Barbiero** [comment]
seems like you're misunderstanding what `unknown` does

As a type, `unknown` means that the type is well, unknown. When you declare an object as `unknown`, Typescript gives up any type inference whatsoever and decides that the type must be cast before the variable can used.

So you need to actually tell TS that `prop` has a `key`, which has a `value`:

```typescript
const helloworld = (prop as {key?:{value:string} } | undefined)?.key?.value
// helloworld is now string | undefined
```
that's intentional design for `unknown` to force the developer to reason about the value's typing before using it. You _could_ use `any`, but I feel you'd be shooting yourself on the foot there since `any` simply ignores typing altogether.

**Comment by nkappler** [comment]
Well I do understand what unknown does,
however I expected this to work, because writing a typeguard or casting the value feels cumbersome if you need the value only once.
I understand that it is intentional though, otherwise it would behave too similar to any I guess...

**Comment by nkappler** [comment]
also with `any` you could do `prop.key.value` which might not be safe and it would be a nice feature if you could do optional chaining without types but you would get an error without the questionmarks...

**Comment by 1valdis** [comment]
I think it should be possible to do optional chaining on `unknown`.

**Comment by nkappler** [comment]
What's really annoying is that it works perfectly fine at runtime. helloworld will be initialized with "Hello World"

**Comment by timonson** [comment]
> As a type, `unknown` means that the type is well, unknown. When you declare an object as `unknown`, Typescript gives up any type inference whatsoever and decides that the type must be cast before the variable can used.

@Barbiero then why can I use the `typeof` operator on an `unknown` type? To verify the type maybe? Right, this is exactly what the optional chaining operator is for.

**Comment by Barbiero** [comment]
> > As a type, `unknown` means that the type is well, unknown. When you declare an object as `unknown`, Typescript gives up any type inference whatsoever and decides that the type must be cast before the variable can used.
> 
> @Barbiero then why can I use the `typeof` operator on an `unknown` type? To verify the type maybe? Right, this is exactly what the optional chaining operator is for, too.
> 

Unknown can be any type, including non-objects. Consider

```ts
const prop: unknown = 4

prop?.something // error!
```

Optional chaining won't solve this.

**Comment by timonson** [comment]
@Barbiero but this is exactly what we are *complaining* about. It should not be an error because in your example it would help to verify that `prop` has not the type of `{prop: {something: 3}}` for example. `Unknown` should act with regards to the optional chaining operator exactly like the `any` type does:

```typescript
const prop: any = 4
prop?.something // no error!
```
I guess my main point the following. To use one of JavaScript's best operators to validate types I am forced to operate this operator on type `any` although this should be exactly a case for `unknown`. Because like you said correctly before with regards to `unknown`: 
>  the type must be cast before the variable can used
I would love to use optional chaining exactly for that.

**Comment by Barbiero** [comment]
@timonson how is your example "no error" when it will cause a runtime error?

The point of unknown is that you **must** type check before using it, because you don't know what that type is. `prop?.something`, when the underlying value is `number`, is a runtime error. `unknown` protects you against that.

Optional chaining isn't even relevant here. Its purpose is to protect you against _potentially null or undefined values_. What you are asking is that optional chaining forgoes any type checking at all.

What you want is to use the type `any`. And in that case, you need to pay attention to possible runtime errors. If you want both a top level type and compile-time error checking, then you use `unknown` - in which case, you must either type cast or type check(with a guard, for example).

**Comment by 1valdis** [comment]
@Barbiero what prevents me from using optional chaining right on underlying value? I would expect the following to work since I am considering the fact that `variable` can be undefined.
```typescript
const variable = undefined as unknown;
if (variable?.prop?.something) {
  // do stuff
}
```

**Comment by timonson** [comment]
@Barbiero it does NOT cause a runtime error.

Take a look at this example module please: https://github.com/timonson/deno/blob/std/jwt/std/jwt/validation.ts

There I have various type predicate functions. These functions are used to validate types and I use optional chaining operators.

If I would change the parameter types to `unknown` I would have to evaluate much more expressions because I could not use the optional chaining operator.

**Comment by Barbiero** [comment]
I don't understand why you are trying to use unknown on either of these cases. If you know what type it is(which means you know the type's probable representation), then you **don't** use unknown. Unknown is a top level type meant to represent an.. unknown... Type. When you want to tell consumers of your functions that _pretty much anything can come out of the function_, or when you want to _enforce runtime type checking_.

If you know the type, then it's not `unknown`. Use your type accordingly. Make use of `Partial<T>` or `| undefined`. Optional chaining will be enabled, as expected.

When you declare something `unknown`, then Typescript can't infer it's type - because you **just said it is not known**. If you want the type to be inferred, you don't declare a type.

You're trying to use the wrong tool here.

**Comment by rsimoes** [comment]
> or when you want to _enforce runtime type checking_.

This is the precise use of the optional chaining operator. The suggestion above to review how the operator works is clearly still applicable.

**Comment by msklvsk** [comment]
We did not get an explanation _why_ is the current behaviour intended. No one disproved OP’s point. Let’s wait until the feature of typing errors as `unkonwn` in catch clauses lands in the next version. I bet someone will open a similar issue. `@typescript-eslint/no-implicit-any-catch` brought me here.

**Comment by not-rusty** [comment]
I was gonna comment in favour of OP, but after some thinking, I see @Barbiero point.

If you know the aproximate data structure, then just cast the any type returning function to some `Partial` type. Maybe it could be really handy to add more power to `Partial` and *make all properties and nested ones optional*, so that consumer code must handle `undefined` cases.

Luckily it is easy to define such behaviour in TS with a recursive type:

```typescript
type RecursivePartial<T> = {
    [P in keyof T]?: RecursivePartial<T[P]>;
}
```

(from https://stackoverflow.com/questions/47914536/use-partial-in-nested-property-with-typescript/47914631)

I would avoid type casting as the plague though. I don't like the compiler trusting in me, as I am a human prone to errors, but that's just my opinion.

Enforcing runtype checking with `unknown` looks like a good idea, specially with a really flexible type system such as typescript.

**Comment by timonson** [comment]
> Enforcing runtype checking with unknown looks like a good idea
I am not sure why you think anybody is disagreeing with this.

Your example doesn't work in cases where a type is actually *unknown* - meaning you don't know what type to expect.

**Comment by hraban** [comment]
@Barbiero `4?.foo` is not an error in javascript:

```
$ node
> 4?.something
undefined
```

This is exactly the point of `?.`.

you would expect type inference to just fall through the `unknown`.

IOW:

```ts
declare var x: unknown;
const y = x?.anything;
// expect type of y to be unknown
```

And since we're all talking hypotheticals, maybe some use cases could help illustrate the point: I'm using this for command line option parsers. Akin to JSON.parse, they can output any object of any form. So you want to do:

```
const myflag = args?.group?.flag;
if (typeof myflag === 'string') {
  // use myflag
} else {
  // report usage error
}
```

Same for JSON.parse (which should output `unknown`, not `any`, if it had been introduced today)

**Comment by HunterKohler** [comment]
I think having the optional chaining on the `uknown` type would entirely in line with how javascript intends. We don't trust that it is any one object, or set of values even,

**Comment by Pimm** [comment]
@Barbiero mentioned that `unknown` is designed to "force the developer to reason about the value's typing before using it". That is an excellent way of putting it. I think the point of many in this thread is: (`?.`) shows you're doing exactly that ‒ reasoning about the value's typing before using it.

### The argument

Take OP's example. We have a variable named `prop` of type `unknown`. We know nothing of its type.

If we write `prop?.key`, there are three scenarios.
1. `prop` has a `key` property. Our expression resolves to the value of that property.
2. `prop` does not have a `key` property (because it's `{}` or `4`). our expression resolves to `undefined`.
3. `prop` is [nullish](https://developer.mozilla.org/docs/Glossary/Nullish). Had we written `prop.key`, then a `TypeError` would have been thrown[[spec]](https://tc39.es/ecma262/#sec-toobject). But since we're using `?.`, our expression also resolves to `undefined`[[spec]](https://tc39.es/proposal-optional-chaining/#sec-optional-chaining-evaluation).

Although we know nothing about the type, we know we can safely write `prop?.key`.

### The counterargument

Imagine we have a variable named `tree` of type `undefined | { branches: Array<Branch> }`.

`tree?.branches` is OK. However, TS prevents us from writing `tree?.tentacles`.

If we were to decide that `?.` is allowed on variables of type `unknown`, then `tree?.tentacles` would become OK once we change the type to `unknown`. In other words: knowing _less_ about the type would allow us to do _more_. That doesn't seem right either.

**Comment by hraban** [comment]
> If we were to decide that ?. is allowed on variables of type unknown, then tree?.tentacles would become OK _once we change the type to unknown._ In other words: knowing less about the type would allow us to do more. That doesn't seem right either.

(emphasis mine)

I'd call this expected behaviour: if you change the type to "unknown", that is precisely what it is: unknown. You could make the same argument for `any`, or any other typecast. Casting a value means that you explicitly know, for sure, that the new type is a better description of that value than the old. If that is not true, then it's the cast that was wrong, not the consequences in the typesystem.

**Comment by kralphs** [comment]
Another way to look at it is that the `unknown` type is really all possible types in union. It's the entirety of the type space. Since the entirety of the type space interacts safely with optional chaining, then optional chaining should be allowed on `unknown`. Further, the result of the optional chaining on `unknown`  would be `unknown | undefined === unknown`.

I think mathematically it makes sense, and that's a strong argument for it to be included in the type system. But I guess it depends on how we determine what's in and what's out. Is TypeScript's main goal to catch run-time errors before they happen or is there a "style" of code that it's trying to encourage as well? Although I appreciate languages that try to enforce idioms, I don't really even see a value to such an idiom 🤔. And it's been a frequent friction point since we've started to lint against explicit any. 

And to be clear this does not mean that optional chaining forgoes type checking. If that were the case I could write `unknownVariable?.mightBeHere.iProbablyShouldNotDoThis` and the compiler would accept it. However, by returning `unknown` it protects me from introducing a runtime error.

I feel it's important to reconsider what @timonson brought up: using `unknown` instead of `any` for type guards... if optional chaining works with `unknown`, then we have safer code because the compiler will now _require_ us to use optional chaining instead of just switching off type safety altogether with `any`. 

> If we were to decide that `?.` is allowed on variables of type `unknown`, then `tree?.tentacles` would become OK once we change the type to `unknown`. In other words: knowing _less_ about the type would allow us to do _more_. That doesn't seem right either.

But that's exactly what existing TypeScript documentations recommends. For example, if there is insufficient overlap between two types during an assertion, you'll be told to cast it as `unknown` before making the next assertion. Knowing less allows us to do more...

**Comment by msklvsk** [comment]
Brilliant arguments but I’m afraid nobody is listening. What would it take to bring this to TS team attention again? a petition of some sort?

**Comment by kralphs** [comment]
The discussion is still alive in #37700. My hope is that this argument gets traction because the TypeScript documentation itself has relied on the set theoretic approach to explain some of its counter-intuitive behaviors e.g. a type union has the intersection of properties from the associated types. What's good for the goose is good for the gander, so to speak.

Optional chaining is relatively new, and as more shops go the "no explicit any" route, this will get felt by the community as a pain point. That's what drove me here lol.

**Comment by the-spyke** [comment]
So, the very common usecase of `unknown` like

```ts
try {
  // ...
} catch (err) {
  logger.log(`Got an error:`, err?.message);
}
```

In TypeScript becomes (from comments above)

```ts
try {
  // ...
} catch (err) {
  logger.log(`Got an error:`, (err as { message?: string } | undefined)?.message);
}
```

And what benefits exactly TS adds here? Why object or undefined? It could be anything like a number. Types for the sake of types.

```ts
try {
  // ...
} catch (err) {
  logger.log(`Got an error:`, 
    // from Lodash: is object and not null
    isObjectLike(err)
        ? (err as { message?: string }).message
        : undefined
  );
}
```

This one makes some sense, but no way I will add that pile of code. Optional Chaining was made to free me from exactly that.

**Comment by ansavchenco** [comment]
> ### The counterargument
> Imagine we have a variable named `tree` of type `undefined | { branches: Array<Branch> }`.
> 
> `tree?.branches` is OK. However, TS prevents us from writing `tree?.tentacles`.
> 
> If we were to decide that `?.` is allowed on variables of type `unknown`, then `tree?.tentacles` would become OK once we change the type to `unknown`. In other words: knowing _less_ about the type would allow us to do _more_. That doesn't seem right either.

This can be solved by not autocompleting `tentacles` property and also by forcing the use of "indexed" property access (`tree?.["tentacles"]`) instead of "dot" property access when [noPropertyAccessFromIndexSignature](https://www.typescriptlang.org/tsconfig#noPropertyAccessFromIndexSignature) config option is on.
