### ISSUE TITLE
Typescript class generics inferance prioritizes constructor arguments over assignment.

### ISSUE THREAD

**Issue by saandre15** [microsoft/TypeScript#35820]
# TypeScript Version
3.7.2 and typescript@next

# Search Terms
Meta-Programming
Generic
Generic Inference
Type Parameters
Type Inference
Template

# Code
```typescript
interface Person {
  name: string;
  age: number;
  id: string;
}

interface Client {
  person: Person;
}

class FormField {  }

class FormFieldGroup<T> {
  constructor(private props: { category: string, questions: FormRelation<Required<T>> }) {}
}

type Primitives = string | number | symbol | bigint | undefined | null;

type FormRelation<T> = {
  [K in keyof T]: T[K] extends Primitives ? FormField : FormFieldGroup<T[K]>;
}

abstract class CRUDComponent<D> {
  public abstract clientQuestions: FormRelation<D>
}

class ClientComponent extends CRUDComponent<Client> {
  public clientQuestions: FormRelation<Client> = {
    person: new FormFieldGroup({
      category: "Client",
      questions: {
        name: new FormField(),
        age: new FormField(),
        id: new FormField(),
      }
    })
  }
}
```

# Expected behavior
+ Property `questions` should be the type of `FormRelation<Required<Person>>`.
+ `name`, `age` and `id` should not be `unknown` types, but FormField as it is primitive value.
+ `FormFieldGroup` should auto infer to the type of `FormFieldGroup<Person>`.

# Actual behavior
```typescript
VSCode : Cannot assign FormFieldGroup<{name: unknown, age: unknown, id: unknown}> to FormFieldGroup<Person>.
```
+ All property of `questions` is automatically assigned to the `unknown` type
+ New class type params don't automatically assign to the assignment class type params

# Suggestion
+ Add a diamond / `<>` operator, which auto infers to the assignment generics, rather than the argument generics
+ Or auto infer to the assignment generic by default
+ I don’t want to specify the type

# Playground Link  

[Playground Link](https://www.typescriptlang.org/play/index.html?ssl=38&ssc=2&pln=27&pc=1#code/JYOwLgpgTgZghgYwgAgArQM4HsTIN4BQyyIcAthAFzIZhSgDmA3EcnA1SQK5kBG0LYsAAm1WvRDMCAXwIFQkWIhQBhADbAI4fKwAOmHNXRRsIFrIII1cDBmQAxLFDL3Na4fmIWrNu4+euEO4A4lBYXLoAPAAqAHw6xAg44lwIYE4AFLr0AG5wkMjZWLoY1HjICPkQDE4AnmJ0jAA0yACOXBC0wMnU-mQASkH53SCRg+3AUBDCMbHx0gCU+LIWYLX6aPRkwGDAOZ3IALw0jZLIAD7cfNAXNLV8WGq3vMAMCrdcIMIQMKDTtyAuGo1CwCGsNn1BtZdjhZkcEsgANoAaWQoGQAGsILUsDBkNEALrUaIognICAAD0gXzsqC2Oz2BwA-A4nC43B5emzAiEwhEYqTYuY5HBeOJEGAKtZbMgVP0AKoAERUWDIuhwWjAkUV8UIxF0XF4GgQbDFdAlUs04AAih0uj1Wc4ocNYTqZHIfDL1FawCq1RrtJTqcI7HKlX71SBNZFvZrdXpDcbLZrbZ0YSBSo6BkN0zGNHH4XriIUDCBqFGAO5ZnnCULhXQZIvFipVGpQerIABEsfAnaarGb7TTI0zTebJHInEr1Y5GQW-fHxfYU4gVb6NbnC8XaNEJFXM6Cwk3A+Lsmbi1YKyAA)

**Comment by dragomirtitian** [comment]
The compiler will prefer to infer from the constructor arguments rather than the expected return type. You can use the workaround described by @jcalz  [here](https://github.com/microsoft/TypeScript/issues/14829#issuecomment-504042546):

```ts
type NoInfer<T> = [T][T extends any ? 0 : never];
class FormFieldGroup<T> {
  constructor(private props: { category: string, questions: NoInfer<FormRelation<Required<T>>> }) {}
}
```
[Playground Link](https://www.typescriptlang.org/play/index.html?ssl=15&ssc=2&pln=12&pc=1#code/JYOwLgpgTgZghgYwgAgArQM4HsTIN4BQyyIcAthAFzIZhSgDmA3EcnA1SQK5kBG0LYsAAm1WvRDMCAXwIFQkWIhQBhADbAI4fKwAOmHNXRRsIFrIII1cDBmQAxLFDL3Na4fmKywAT33IAOSwASRAYaAAeABUAPmQAXmQAbSiAXRTkCAAPSBBhOzgQH2QAfmQABmRqEAgAN2hUlisbO0dnVwh3AHEoLC5daLjCYgQccS4EMCcACl16WrhIZDmsXQxqPGQERYgGJx8xOkYAGmQARy4IWmAx6iDQ8KgItrIAJU7Fm5AI94vgKAgwkGMTi0gAlPhZBZfP5UPQyMAwMB6nZEuJGMgAD7cPjQLE0Hx8LBqfG8YAMBT4rh5CAwUCA-EgLhqNQsAgwlAvd7WJE4QYJHTEJIAaWQoGQAGsID4sDBkGlqFERalMjktPk0PDEcirqUHE4XG4PNQXh1ur1+tFlTFzHI4LxxIgwFtrLZkCpXgBVAAiKiwZF0OC0YAi3qGei4vA0CDYDroTpdmnAAEVLtdbvrnNzPnywzI5M03eok2A-QGg9psrkNR6fWXAzVwBFi8Hw8RdJHo4ng6mrryQOtM28Pv3mxpWwLhsRlgYQNUIAB3Idm4Q9Pq6aabAD0W+QHLYrQNK7XluMphirGnWx2eygB2QACIW+AH8dL9OLn2voPt7uogALK4UDgAFkCwCVkHfK9SAoecl1NI1pjBN8ryvdhOBqeCj0Q5CoOnEQ4OXHCUNQ2Qr3BVgoSAA)

**Comment by saandre15** [comment]
OK, thanks
