### ISSUE TITLE
Tagged union isn't always narrowed by intersection

### ISSUE THREAD

**Issue by lightspeedlucas** [microsoft/TypeScript#35828]
**TypeScript Version:**  3.7.2 / Playground's Nightly

**Search Terms:** intersection tagged union ADT narrow brand

**Code**

```ts
type ADT = { brand: 'A', a: number } | { brand: 'B', b: string };
type Narrow<K extends ADT['brand']> = ADT & { brand: K };

let x: Narrow<'A'> = { brand: 'A', a: 8 };
x.a = 9; // OK

let y!: Narrow<'A'>;
y.a = 9; // Error 2339: Property 'a' doesn't exist on type Narrow<"A">.

let z: Narrow<'A'> = <any>{ brand: 'A', a: 8 };
z.a = 9; // Error 2339: Property 'a' doesn't exist on type Narrow<"A">.
```

**Expected behavior:** `Narrow<K>` narrows down the ADT, as seen in the first case.

**Actual behavior:** Narrowing fails in some cases.

**Playground Link:** [Playground Link](https://www.typescriptlang.org/play/?ssl=11&ssc=72&pln=1&pc=1#code/C4TwDgpgBAggIgFSgXigbygIwE4EMB2AJgFxQDkMZANFLqfgK4C2mE2UAvlAD7pZ5FSZAELUspAM7BsAS3wBzTgG4AUKEhQAcrmzYA9gHcAPAGkoEAB7AIRCbEQBtMjgKEyAXQB8Ke0gBkfC6CUGYcqioANhDAUBak2rqGRhRk3qgYQSTklDR0UAAcyioWAHS4PgCcSlAA9DVQAPImKpHRUCAAhPE6+sYpnqogZZXVdVAAoonsAEwAzLMVpAAK+pDYoOS4ZFCEehAS+GQxljJSUHr4UOrQCb1GAEQw954lLVExAF7diX2UaVBGAggTwZARZFK5UiFMIqD7DVBVWr1Sb6GbzRZQFZ6NYbMhbHZ7A5HcwWU4xC5XcA3HpJR7PV5AA)

**Related Issues:** #13300

**Comment by dragomirtitian** [comment]
You are misinterpreting the results of the code. Narrowing is never done by the `&` type operator. `&` just means an intersection of two types. This means that a type has to be both members of the intersection at the same time. While in some cases ts will simplify intersections that can never occur (for primitive intersections) for object intersections ts will not do this. This means that:
ts
```
Narrow<'A'> <=> 
    ( { brand: 'A', a: number } | { brand: 'B', b: string }) & { brand: 'A' } <=>
    ( { brand: 'A', a: number } & { brand: 'A' }) | ({ brand: 'B', b: string }  & { brand: 'A' }) 
``` 

So you will still have a union that you can't access `'a'` on. One could argue `({ brand: 'B', b: string }  & { brand: 'A' })` should simplify to `{ brand: 'B' & 'A', b: string }`  which in turn would be `{ brand: never, b: string }` .. which maybe can be simplified to `never` 🤷‍♀️. But that is just no the way things are done in the compiler currently (and there are probably reason for it)

The case that does work is due to control flow analysis realizing that in spite of you annotation, because of the assignment type type of `x is actually  `{ brand: 'A', a: number }`.


The good news is there is a good way to grab a constituent from a union, it is the `Extract` built-in type, which uses a distributed conditional type to extract constituents form a union:

```ts
type ADT = { brand: 'A', a: number } | { brand: 'B', b: string };
type Narrow<K extends ADT['brand']> = Extract<ADT, { brand: K }>

let x: Narrow<'A'> = { brand: 'A', a: 8 };
x.a = 9; // OK

let y!: Narrow<"A">

y.a = 9; // ok

let z: Narrow<'A'> = <any>{ brand: 'A', a: 8 };
z.a = 9; // ok

```
[Playground Link](https://www.typescriptlang.org/play/?ssl=11&ssc=72&pln=1&pc=1#code/C4TwDgpgBAggIgFSgXigbygIwE4EMB2AJgFxQDkMZANFLqfgK4C2mE2UAvlAD7pZ5FSZAELUspAM7BsAS3wBzTgG4AUKEhQAcrmzYA9gHcAPAGkoEAB7AIRCbEQBtMjgKEyAXQB8Ke0gBkfC6CUGYcqioANhDAUBak2rqGRhRk3qgYQSTklDR0UAAcyioWAHS4PgCcSlAA9DVQAPImKpHRUCAAhPE6+sYpnqogZZXVdVAAoonsAEwAzLMVpAAK+pDYoOS4ZFCEehAS+GQxljJSUHr4UOrQCb1GAEQw954lLVExAF7diX2UaVBGAggTwZARZFK5UiFMIqD7DVBVWr1Sb6GbzRZQFZ6NYbMhbHZ7A5HcwWU4xC5XcA3HpJR7PV5AA)

**Comment by lightspeedlucas** [comment]
Ah, makes sense! Thank you so much for the explanation and solution, closing the issue.
