### ISSUE TITLE
parsing fails for nested array with objects

### ISSUE THREAD

**Issue by chandu0101** [microsoft/TypeScript#35834]
**TypeScript Version:**  3.7.x

**Code**

```ts
const config: {
        obj1?: { one: number, obj1c?: { value: string } },
        obj2?: { two: number, obj2a?: Array<{ name: string, obj2ao?: { value: string } }> },
        arr2?: Array<Array<{name:string}>>
    } = {}
```

***Parsed AST :***

```ts
Type
{ obj1?: { one: number; obj1c?: { value: string; } | undefined; } | undefined; obj2?: { two: number; obj2a?: { name: string; obj2ao?: { value: string; } | undefined; }[] | undefined; } | undefined;

 arr2?: { ...; }[][] | undefined; } // Wrong output 
flags:
524288
objectFlags:
16
aliasSymbol:undefined
aliasTypeArguments:undefined
```

[AST Viewer](https://ts-ast-viewer.com/#code/MYewdgzgLgBKYDMCWBzAXDA3gKBn-eIARgFYCMA-BpjOAKYZgCuAtkXQE4A0tpZwVLDABuAQwA2TBjGgckYFDAC+yrrgL5iJAEyCaUAO4hGrdt147RggIIcOogJ4AeGmFEtps+Sh5btokD0RCSkMLwVlZQA+VXUNGFE7XQxbe2dUxxc3DzRwlCUoqLjIgF4sJSA)

**Expected behavior:**

arr2 should be parsed as `{name:string}[][] `

**Actual behavior:**
`arr2?: { ...; }[][] | undefined; }`

**Comment by dragomirtitian** [comment]
Nothing has failed, this is the expected behavior. The actual type of `arr2` is `{name:string}[][] | undefined`. The `undefined` comes from the fact that `arr2` is optional.

The `...` you are seeing comes from the fact that if a type is too long ts will truncate the long names when printing the type in tool-tips (i believe setting `noErrorTruncation` will remove this behavior at least in part).

If you put the type of `arr2` in a type alias you can again see the full type:

```ts
const config: {
        obj1?: { one: number, obj1c?: { value: string } },
        obj2?: { two: number, obj2a?: Array<{ name: string, obj2ao?: { value: string } }> },
        arr2?: Array<Array<{name:string}>>
} = {}

type arr2Type = typeof config['arr2']
```
[Playground Link](https://www.typescriptlang.org/play/?ssl=7&ssc=38&pln=1&pc=1#code/MYewdgzgLgBKYDMCWBzAXDA3gKBn-eIARgFYCMA-BpjOAKYZgCuAtkXQE4A0tpZwVLDABuAQwA2TBjGgckYFDAC+yrrgL5iJAEyCaUAO4hGrdt147RggIIcOogJ4AeGmFEtps+Sh5btokD0RCSkMLwVlZQA+VXUNGFE7XQxbe2dUxxc3DzRwlCUoqOwVAF4sJWxsKAcABzoEpIAVWvqy6rqQBDhwZBQAbQByRI5tAYBdbAB6SZgACRBhTgSwABMYBxAmGAMkcXEZOjopmZxpjWzPKDkFAG5j5T6xx5gAHxgmVbpkMDoVoA)

**Comment by AnyhowStep** [comment]
Regarding `noErrorTruncation`, https://github.com/microsoft/TypeScript/issues/26238

**Comment by chandu0101** [comment]
`config['arr2']` is working fine in my transformer too, 

> The ... you are seeing comes from the fact that if a type is too long ts will truncate the long names when printing the type in tool-tips and errors 

cool, in my case i am using  `typeChecker.typeToString(t)` 
```ts
   const props = getPropDeclsFromTypeMembers()
    return `{${props.map(p => {
        const n = p.name.getText()
        const t = memberTypes.find(mt => mt.name === n)!.type
        if (n === "config") {
            console.log("******* Type : ", t);
            console.log("******* Type to String : ", typeChecker.typeToString(t));
        }
        return `${n}:${typeChecker.typeToString(t)}`
    }).join(",")}}`
```
IMO  `typeChecker.typeToString(t)` should  return a string without truncation regardless of `noErrorTruncation` compiler option :s

**Comment by DanielRosenwasser** [comment]
`typeToString` takes a 3rd optional parameter where you can disable trunctation with `ts.TypeFormatFlags.NoTruncation`

**Comment by chandu0101** [comment]
perfect thank you :)
