### ISSUE TITLE
Element implicitly has an 'any' type because expression of type 'string' can't be used to index type

### ISSUE THREAD

**Issue by aahmadhadi** [microsoft/TypeScript#35859]
**TypeScript Version:**  3.0.1

**Code**

```ts

import Sequelize from 'sequelize';
import { DbInterface } from'typings/DbInterface';
import { UserFactory } from './User';
import { PostFactory } from './Post';
import { CommentFactory } from './Comment';

export const createModels = (sequelizeConfig: any): DbInterface => {
  const { database, username, password, params } = sequelizeConfig;
  const sequelize = new Sequelize(database, username, password, params);

  const db: DbInterface = {
    sequelize,
    Sequelize,
    Comment: CommentFactory(sequelize, Sequelize),
    Post: PostFactory(sequelize, Sequelize),
    User: UserFactory(sequelize, Sequelize)
  };

  Object.keys(db).forEach(modelName => {
    if (db[modelName].associate) { //Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'DbInterface'. No index signature with a parameter of type 'string' was found on type 'DbInterface'.
      db[modelName].associate(db); //Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'DbInterface'. No index signature with a parameter of type 'string' was found on type 'DbInterface'.
    }
  });

  return db;
};
```

**Comment by dragomirtitian** [comment]
This is a question, not a bug, please use SO for questions. (see [this](https://stackoverflow.com/questions/55012174/why-doesnt-object-keys-return-a-keyof-type-in-typescript/55012175#55012175) it will help)

**Comment by aahmadhadi** [comment]
im sorry, thanks btw for the tips. im a newbie

**Comment by alexandermckay** [comment]
// bad
    const _getKeyValue = (key: string) => (obj: object) => obj[key];
    
    // better
    const _getKeyValue_ = (key: string) => (obj: Record<string, any>) => obj[key];
    
    // best
    const getKeyValue = <T extends object, U extends keyof T>(key: U) => (obj: T) =>
      obj[key];

Bad - the reason for the error is the `object` type is just an empty object by default. Therefore it isn't possible to use a `string` type to index `{}`.

Better - the reason the error disappears is because now we are telling the compiler the `obj` argument will be a collection of string/value (`string/any`) pairs. However, we are using the `any` type, so we can do better.

Best - `T` extends empty object. `U` extends the keys of `T`. Therefore `U` will always exist on `T`, therefore it can be used as a look up value.

**Comment by pke** [comment]
@alexandermckay What if I have this scenario:

```ts
type props = {
  type: string
}

const style = styles[props.type]

const styles = StyleSheet.create({
  base: {
    ...spacing.medium,
    padding: 10,
    textAlign: "center",
    textAlignVertical: "center",
    fontWeight: "bold",
    fontSize: 18,
    height: 50,
  },
  primary: {
    backgroundColor: colors.purple,
    color: colors.white,
  },
  secondary: {
    backgroundColor: "transparent",
    color: colors.purple,
    borderColor: colors.purple,
    borderWidth: 2,
  },
}
```

It complains: 
`Element implicitly has an 'any' type because expression of type 'string' can't be used to index type styles `

**Comment by greenlaw110** [comment]
Same question here, I have

```typescript
const LEVEL_DEBUG = 1;
const LEVEL_FINE = 2;

const LOG_LEVELS = {
  info: LEVEL_INFO,
  debug: LEVEL_DEBUG,
  fine: LEVEL_FINE,
};

let logLevel: string = environment.logLevel;
if (!logLevel) {
  logLevel = 'info';
}
let _level = LOG_LEVELS[logLevel.toLowerCase()]; // here it complains 
```

**Comment by pedoe** [comment]
@greenlaw110 
Try to get the key value by using @alexandermckay's method:

```javascript
const LEVEL_DEBUG = 1;
const LEVEL_FINE = 2;


const LOG_LEVELS: {[key:string]: number} = {
  debug: LEVEL_DEBUG,
  fine: LEVEL_FINE,
};

let logLevel:string = 'debug';
if (!logLevel) {
  logLevel = 'info';
}

const getKeyValue = <T extends object, U extends keyof T>(obj: T) => (key: U) =>
  obj[key];
let _level = getKeyValue(LOG_LEVELS)(logLevel);
console.log(_level); // 1
```

**Comment by bradydowling** [comment]
Just found [this blog post](https://scottw.com/blog/typescript-index-signature/), which was very helpful, and wanted to paste some code here that I think is slightly more straight forward than the code included here so far. If you have the following object:
```
const unitsOfTime = {
  millisecond: 1,
  second: 60,
  hour: 60 * 60,
  day: 24 * 60 * 60,
  month: 30 * 24 * 60 * 60,
  year: 365 * 24 * 60 * 60
};
```
You can declare types for the keys and values in that object like so:
```
const unitsOfTime: { [unit: string]: number } = {
  millisecond: 1,
  second: 60,
  hour: 60 * 60,
  day: 24 * 60 * 60,
  month: 30 * 24 * 60 * 60,
  year: 365 * 24 * 60 * 60
};
```

**Comment by AlexOros** [comment]
Hey, if I do this my object will have the following shape when I hove over it:
```ts
const unitsOfTime: {
    [unit: string]: number;
}
```
so auto-complete is no longer available, am I missing something?

**Comment by dgreene1** [comment]
The workarounds provided here are not recommended. Object.keys is in-fact dangerous. I've provided a[ TypeScript Playground example that demonstrates the runtime error that can occur.](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgJIGED2AbTUDOyA3gFDLIC2coAXMvmFKAOYA0Z9ECmIAJnFACedBkxDMO-KAGsRjFiQC+JEgHpVyGAFcQCMMB7IADmLABBbNgASEAB4A1ONi0R8ACm64oAGUyZpWkZ0GDh4+ACUcmLMxGoa5OrIAKLYEBQQ4MjAFEbYwAjAYNiCyAAWcIRwIMgA5FWCNchggkYoAEZccFr4KHYmrvgG1ZgwTS0oNaIsjQhVNWDIHcjdELxNmFl8dmOttSFe+DUAdHHkyIlnAHIboLzbg8wgcGBaUCgA7oWlyHDGAnDpSBQZAjHYTKbiRrvCqaTA6NaGZq7Gr7MLHNwAdgADABWADM4VO5DeLyg1QA8m0AFZcMBHaQQQTuTx4Xz+QLhI5UIxuBklAC8AD5SBcziTXtUWT4-AEjABtPkAXQA3ETkIpCcpTgARDaXckAFWQvA2YFKwHwR2QBvNhAtyBAmAWv3eeGkAjhfGWIFS+EIgjhZTgADcUFAdPp0shg05gPx9IjygtuCAYMAoBRCGaUHzKm8QT6Su8k0HCB0MsYoJhg3HVsg3HkGVlMABaMAREjaXQJ6omUDmSw2BxOFz4ACqlwAymYAGJJDyhaXsoJoLAHSL0eTiOWK2IJDRm+32355dqdFbIANaGr5-qQPgsJol7Mg6m00s-aq3OwcFMMZBSmysreKgSTIPyAGLkBgQ-IQOjSI67zVDCABKXB4LwAA8EJsJu0SCqqHDimSyCUjSej0oyzJQTKgQgUknLcryjLgcKHDEhApKSjRy70QqjIqhwGpKCof4LDwEDkjANoQJOcC8AACgI7ZSZOjBaHorxOJOWhtEij4QaQ5BULQyAAEQAMQzliWJmew5BSLI5kWTZtn2ZwKZSMIzk2TOdkcIk1z6EgT7PNa4yTggTBGM6liYO8hB2EgfqVpgrRQPorgFp+PCCBQcKEJgb56PgHAAPpRRAzyrAAmlVUB0AATK5IkkGJZR2I4zhZRBfbgBY1idSOrgTtOc5uBJUkyXJinKfgqnqZpUDabp+niOEhGJDa9qfJYyDQFWwKDLoKAgFoFAdAQAFVA6TqLCgVB3MguDvNALazD09bAEcEBWnKSQoShip0LYRxgJgvivVA6AVCg9qOs6mg6HoQzIIS7VwmARhaAsEGlEN3WWkxtiscgoPg5D0Awz0bjhJyVKYKAbh2eZG2iTw+A4L9uDMBNOPY2A4RAA)

**Comment by codemaster101** [comment]
In addition to the answers, people could also try to use interfaces :)
Here is an example, hope it helps:
```
export interface IMapping {
  [propertyName: string]: string;
}

const mapping: IMapping = {
  apples: '$5',
  oranges: '$4',
}

// some code

const fruit: string = await getFruitFromInput();
const price: string = mapping[fruit];
return price;
```

**Comment by mnowotnik** [comment]
> In addition to the answers, people could also try to use interfaces :)
> Here is an example, hope it helps:
> 
> ```
> export interface IMapping {
>   [propertyName: string]: string;
> }
> 
> const mapping: IMapping = {
>   apples: '$5',
>   oranges: '$4',
> }
> 
> // some code
> 
> const fruit: string = await getFruitFromInput();
> const price: string = mapping[fruit];
> return price;
> ```

Unfortunately, weakly typed solutions make autocompletion no longer work.

**Comment by romain20100-rwigo** [comment]
I am a bit confused by this specific type checking.
It seems to me that:
1. it is not actually protecting anything (people come up with hacks to bypass the error)
2. it does not match the reality of javascript where accessing a missing key returns `undefined`.

Going further with the example above:
```ts
const unitsOfTime = {
  millisecond: 1,
  second: 60,
  hour: 60 * 60,
  day: 24 * 60 * 60,
  month: 30 * 24 * 60 * 60,
  year: 365 * 24 * 60 * 60
};

unitsOfTime['anyString'] // Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '...'
```

I see 2 ways of bypassing this, and in my opinion both are wrong.
- Adding a looser type: `const unitsOfTime: { [unit: string]: number } = ...`
  - wrong because it makes it possible to also use a string in cases where I might not want to accept a string that is not specific.
- Augmenting the type of the indexing key: `unitsOfTime['anyString' as keyof typeof unitsOfTime]`
  - even worse because it communicates the idea that the key **IS** one of unitsOfTime even though it might not be.
  - Typescript won't tell the difference but there is a case where things will break.

**What I would expect**:
As far as I know, accessing a key that does not exist in javascript will always return `undefined`.
So in my opinion, accessing such key should actually emit a type that is a union of `undefined` and all other values in the object.
But certainly not 'any'.

This way I could do;

```ts
const unitsOfTime = ...

const time = unitsOfTime['anyString']
if (!time) {
  // handle missing unit
}
// continue with time
```

**Comment by romain20100** [comment]
I am a bit confused by this specific type checking.
It seems to me that:
1. it is not actually protecting anything (people come up with hacks to bypass the error)
2. it does not match the reality of javascript where accessing a missing key returns `undefined`.

Going further with the example above:
```ts
const unitsOfTime = {
  millisecond: 1,
  second: 60,
  hour: 60 * 60,
  day: 24 * 60 * 60,
  month: 30 * 24 * 60 * 60,
  year: 365 * 24 * 60 * 60
};

unitsOfTime['anyString'] // Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '...'
```

I see 2 ways of bypassing this, and in my opinion both are wrong.
- Adding a looser type: `const unitsOfTime: { [unit: string]: number } = ...`
  - wrong because it makes it possible to also use a string in cases where I might not want to accept a string that is not specific.
- Augmenting the type of the indexing key: `unitsOfTime['anyString' as keyof typeof unitsOfTime]`
  - even worse because it communicates the idea that the key **IS** one of unitsOfTime even though it might not be.
  - Typescript won't tell the difference but there is a case where things will break.

**What I would expect**:
As far as I know, accessing a key that does not exist in javascript will always return `undefined`.
So in my opinion, accessing such key should actually emit a type that is a union of `undefined` and all other values in the object.
But certainly not 'any'.

This way I could do;

```ts
const unitsOfTime = ...

const time = unitsOfTime['anyString']
if (!time) {
  // handle missing unit
}
// continue with time
```

**Comment by HIMA-MB02** [comment]
For those of you having this issue with typescript:

// error
```
export interface IFilterData {
    categories: string[];
    genders: string[];
    brands: string[];
    discounts: string[];
}
const selectedFilters: IFilterData = someInitialValues;
for (let key in selectedFilters) {
    // you will get the error here
    selectedFilters[`${key}`].map(filter => {});
}
```
Like @alexandermckay said, we need to specify that the current record's keys are of type "string"
//fix

```
export interface IFilterData extends Record<string, any> {
    categories: string[];
    genders: string[];
    brands: string[];
    discounts: string[];
}
```

So extend your interfaces with Record<string, any>, or generic types to get rid of any.

Hope this helps.

**Comment by codemaster101** [comment]
> Unfortunately, weakly typed solutions make autocompletion no longer work.

The idea would be @mnowotnik, that you use this interface for an object which can have changing key names, or dynamically set key names, during run-time.

```
data["example key name coming from for loop"]: "hey michael"
```

If people are using this solution over a simple interface then it could be a faulty implementation or just bad code practice. This solution is not to be used to help in writing code faster, but so that people do not use `ts-ignore` for their dynamic objects.

**Comment by sghabbour** [comment]
> 

I'm the same problem, could you solv it?

**Comment by sghabbour** [comment]
@pke I have the same problem? could you solve it?
