### ISSUE TITLE
Inside of modules, `this` should be `undefined`

### ISSUE THREAD

**Issue by jkrems** [microsoft/TypeScript#35882]
**TypeScript Version:**  3.8.0-dev.20191224 (current nightly)

**Search Terms:**
* strict mode this
* module globalThis
* module this

**Code**

```ts
const await = new this.Uint8Array(0);
export { await };
```

**Expected behavior:**

* `this` should be undefined, no such property `Uint8Array`.

**Actual behavior:**

* `this` is treated as `typeof globalThis`.

**Playground Link:** [Playground Link](http://www.typescriptlang.org/play/?ts=3.8.0-dev.20191224&ssl=2&ssc=18&pln=1&pc=1#code/MYewdgzgLgBAhgdzgS1gXhmApgmUAWyEAdAKrJhQAcAggE51wCeAFAAwCUA3AFBYAeABxB1YAb3hJUMAL68gA)

**Related Issues:** 
* https://github.com/microsoft/TypeScript/issues/8559 (also about module-specific behavior)

(Found while researching for https://gist.github.com/jkrems/b14894e0b8efde10aa10a28c652d3541)

**Comment by jkrems** [comment]
Side note: Adding `use strict` at the top should have the same effect even outside of modules but I'm not sure how exactly TypeScript configures the difference between modules and other file formats. Adding `use strict` doesn't change the behavior with or without `export` though.

**Comment by qwabra** [comment]
looks like "v3.3.4" latest working version

https://www.typescriptlang.org/play/?ts=3.3.3#code/MYewdgzgLgBA3jYBXaIC2BRANgUzTsKCAGhgEMATCjANwKgBkBLaAnAJxgF8YBeGKAAsWAKCA

version "3.4.1" has this bug

**Comment by sandersn** [comment]
As far as I can tell, `this` has never had the type `undefined` in modules. What was there was an implicit-any error.

The code today could easily issue an implicit-this error, but does not. Or it could correctly give `this: undefined`.

I quickly tried the first and found that our test suite actually gives fewer errors because so few of our tests use strict: true. It's hard to guess how breaky this will be on real code, but probably not very.

I created a PR, #37784, for the second and will ask typescript-bot to run the user tests et al on it. For the simple example above it gives the sort-of-OK error "Object is possibly undefined" on `this`. Only 5 tests from test suite fail, and 2 of them are good errors on subtly wrong code.

However, I'm going to move this to TS 4.0 because the full solution is likely to be slightly more complex and breaky, and because it's a feature request and not a regression.

**Comment by jkrems** [comment]
Thanks for looking into this!
