### ISSUE TITLE
Definite assignment checks don't occur on private fields

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#35884]
https://www.typescriptlang.org/play/index.html?ts=3.8.0-pr-30829-97#code/MYGwhgzhAEDC0G8BQ1oGIBmB7LAuaEALgE4CWAdgOYDcSK0ARuABYAUAlIvaoc6RADpMOWqgC+SMUA

```ts
// @strictPropertyInitialization: true
// @strictNullChecks: true

class C {
  #foo: string;

  blah() {
    this.#foo;
  }
}
```

**Expected**

```
Property 'foo' has no initializer and is not definitely assigned in the constructor.
```

**Actual**

No error

**Comment by mheiber** [comment]
I'll give @dragomirtitian a chance to PR this first, since he expressed interest.

@dragomirtitian I know you would have figured this out in like two minutes, but wanted to share what I found in the off chance that it is helpful. I accidentally looked into this, thinking I found a different issue:

I think the problem is in checker.ts::checkPropertyInitialization

There is an `isIdentifier` check that should probably be like this instead:

```ts
                    if (isIdentifier(propName) || isPrivateIdentifier(propName)) {
```

Then the signature of `isPropertyInitializedInConstructor` would need to be tweaked to accept PrivateIdentifiers.

I tried it out and it seems to work, but I didn't try all cases.
