### ISSUE TITLE
Improper escaping for processDiagnosticMessages.ts

### ISSUE THREAD

**Issue by ghost** [Microsoft/TypeScript#3589]
Problem:

`buildInfoFileOutput` doesn't reliably escape diagnostic messages.

Reasonable input that would be problematic (i.e., non-pathological and yet still not adequately handled) would include backslashes and newlines.  The safe `JSON.stringify` should be used instead of an ad-hoc, regexp-based approach.

Example Input:

```
{
    "Expected \\\nHere's an extended explanation of why.": {
        "category": "Error",
        "code": 9999
    },
    "Expected \"\\\" before {0}": {
        "category": "Error",
        "code": 9998
    }
}
```

**Comment by colbyrussell** [comment]
Fixed in [rev 42a2df03 on diagnosticspp](https://gitlab.com/crussell/typescript-public/commit/42a2df03ca15e134970ad37afc7f64f49e00b41b).

**Comment by mhegazy** [comment]
@colbyrussell we would appreciate a smaller PRs for these issues instead of one large one.

**Comment by colbyrussell** [comment]
Huh?  This is a one line change.

**Comment by mhegazy** [comment]
It is easier and faster to get smaller changes in. if you have this fix ready, send it over.

**Comment by colbyrussell** [comment]
I'm still confused.  I haven't filed any pull requests at this point, and at least for the time being, I don't have any concrete plans to, due to impedance with GitHub's pain points and the poor way it integrates with/chooses to impose overhead on git.

Anyone is certainly welcome to submit PRs for this stuff in the mean time.  I won't be upset.  Like I said, the problem outlined in this issue is a one line fix.

**Comment by mhegazy** [comment]
I see. sorry i miss understood then. i thought you were actively working on these issues.

**Comment by NaridaL** [comment]
@mhegazy fixed by https://github.com/Microsoft/TypeScript/commit/b81e71d9052fffacd29bf28e5fe706243db1a170#diff-49305f30ff9a8b617c761b5edd339f03R69

**Comment by mhegazy** [comment]
thanks!
