### ISSUE TITLE
I can't write interfaces in methods anymore

### ISSUE THREAD

**Issue by bigGoodMan** [microsoft/TypeScript#35917]
**Expected behavior:**

```
 interface ObjINF1 {
    [key: string]: string | number | undefined;
}
interface ObjINF2 {
    id: number;
    title: string;
}
interface ObjINF3 {
    parentId: number;
    name: string;
    desc: string
}
function a1(objArr: ObjINF1[]) {
    
}
function a2(objArr: ObjINF2[]) {
    a1(objArr) 
} 
```

**Actual behavior:**

```
function a2(objArr: ObjINF2[]) {
    a1(objArr) // Type 'ObjINF2' is not assignable to type 'ObjINF1'.Index signature is missing in type 'ObjINF2'.
}
// But it's true
function a3(objArr: {
    id: number;
    title: string;
}[]) {
    a1(objArr)
}
```

why?

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
