### ISSUE TITLE
How to fill marker by result of latitude and longitude from json result?

### ISSUE THREAD

**Issue by ahmedsaba** [microsoft/TypeScript#35928]
How to fill marker by result of latitude and longitude from json result? using angular 7 ?
```

this.partDetailsService.getLocationData(locationArr).subscribe(res => {      
                console.log(res);    
        res.forEach((item, index) => {    
            var dataLocation = res[index]['_source']['GPS1'];      
            console.log(dataLocation);       
            var locationsLatLng = dataLocation.split(',');
           console.log(locationsLatLng);


         });
```
I have foreach loop get GPS1 latitude and longitude from service return latitude and longitude based on array of locationsId then store it separated by comma , on variable locationsLatLng (lat,lng) as following :

52,70
30,40
20,60
50,100
How to file marker by latitude and longitude by values exist on locationsLatLng

```
 markers: marker[] = [
      {
          lat: ?,
          lng: ?
      }
```

**Comment by markusjohnsson** [comment]
@ahmedsaba you will probably be more successful asking questions like this at StackOverflow.

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
