### ISSUE TITLE
VS Community and TS: auto-import adds '.js' extension to the module name, while auto completion not 

### ISSUE THREAD

**Issue by AbuDawood** [microsoft/TypeScript#35926]
visual studio 2019 community, 
for the autocomplete during import the suggested modules are as expected (module name without extension), However, when typing ex. a class name and want to auto-import the incloser module it gets added with .js extension !! what's wrong  

- screenshot for autocomplete the import syntax
![image](https://user-images.githubusercontent.com/28667792/71605129-fed12780-2b66-11ea-9fc4-11ad907633e5.png)

- screenshot for auto import suggestions
![image](https://user-images.githubusercontent.com/28667792/71605199-6be4bd00-2b67-11ea-9026-dc91d72d2fd2.png)

**Comment by DanielRosenwasser** [comment]
For path completions, we currently we find the first existing import that's relative, and then figure out if it uses an extension. If so, we provide paths with `.js` files: https://github.com/microsoft/TypeScript/pull/20624/

However, there *was* talk of following up and making extensions for import paths configurable: https://github.com/microsoft/TypeScript/issues/19019#issuecomment-378373530

**Comment by AbuDawood** [comment]
Thank you for your reply.
The issue is that I am working on a project that uses Webpack i.e. supports the extensionless module's.
According to the mentioned situation, the provided option is not helpful.

**Comment by daramasala** [comment]
> So some context: for path completions, we currently we find the first existing import that's relative, and then figure out if it uses an extension. If so, we provide paths with `.js` files: #20624
> 
> However, there _was_ talk of following up and making extensions for import paths configurable: [#19019 (comment)](https://github.com/microsoft/TypeScript/issues/19019#issuecomment-378373530)

Mine is a typescript project. None of my imports use '.js' (they are all without any extension) yet new auto imports are created with '.js'.
I have another project with exactly the same tsconfig.json file and there, imports are created without an extension.
I would be happy for some guidance on which files/configurations would help troubleshoot the issue (as I said, I don't think it's the tsconfig file since the same file in a different project yields extensionless imports).

**Comment by andrewbranch** [comment]
Lots of things around this have changed since this issue was opened. Certain compiler options indicate that extensions are required by the module system where the code is intended to run. Beyond that, there are editor preferences, and when not set and the compiler options allow multiple options, an attempt to match the style of the existing file is made. Given how many features have been added (and bugs fixed), I’m going to close this. Feel free to open a new one with complete repro steps if you’re still experiencing buggy or confusing behavior.
