### ISSUE TITLE
Mapped type used  with `keyof` not narrowing

### ISSUE THREAD

**Issue by whitneyit** [microsoft/TypeScript#36050]
**TypeScript Version:**  Nightly

**Search Terms:**
[computed type](https://github.com/microsoft/TypeScript/issues?utf8=%E2%9C%93&q=computed+type)
[mapped type narrow](https://github.com/microsoft/TypeScript/issues?utf8=%E2%9C%93&q=mapped+type+narrow)
[keyof narrow type](https://github.com/microsoft/TypeScript/issues?utf8=%E2%9C%93&q=keyof+narrow+type)
[type index narrow](https://github.com/microsoft/TypeScript/issues?utf8=%E2%9C%93&q=type+index+narrow)

**Expected behavior:**
No errors.

**Actual behavior:**
The type for `value` is not being narrowed on either side of the `if` statement.

**Related Issues:**

**Code**
```ts
interface Example {
    b: boolean;
    n: null;
}

function onlyBoolean(arg: boolean): void {
    // do nothing
}

function onlyNull(arg: null): void {
    // do nothing
}

function test<K extends keyof Example>(value: Example[K]): void {
    if (value === null) {
        // Argument of type 'Dict[K]' is not assignable to
        // parameter of type 'null'.
        onlyNull(value);
        return;
    }
        // Argument of type 'Dict[K]' is not assignable to
        // parameter of type 'boolean'.
    onlyBoolean(value);
}
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
function onlyBoolean(arg) {
    // do nothing
}
function onlyNull(arg) {
    // do nothing
}
function test(value) {
    if (value === null) {
        // Argument of type 'Dict[K]' is not assignable to
        // parameter of type 'null'.
        onlyNull(value);
        return;
    }
    // Argument of type 'Dict[K]' is not assignable to
    // parameter of type 'boolean'.
    onlyBoolean(value);
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?ts=3.8.0-dev.20200104#code/JYOwLgpgTgZghgYwgAgKIA84FsAOAbFAbwChkzkAjALkoHtaC4QBuU8kGkAVzz1YF9ixGFxAIwwWiGRS8ATwBC9RiAAUcKAHMaFZRCYBKGgDdawACbIS5ZAHpbyc7WQhaYABahNxQcNHjJaVk5ADkePHUtTnCjZFMLKzYye0dnVw8vHyERMQkpZEgAZzAAHgBpZAh0SBBzQuQAawg5Whg0TFwCAD5VYzg8LggaDGx8CABtMoBdWPjLa3JgNt7+weQAXk2XGMSbGxSAQS0uLAhwGTawORwUAHIAEWBxSanb5GB69OQ4QsLgTRAcAoBAKtCSexSOA02AgkCgFwK1zu3F4twAdOCbMEwrwVgMIAZWHtyFBYVwoCxwYJickHEdNCczmAEVcbsgHk8wC83h8XG5vr9-oDgSgwGCaXYHFCoDC4SykezdAx9CB0eDgkplUw8YNCT4gA)

**Comment by Cryrivers** [comment]
I'm not sure if it is related. TypeScript 3.7.4 infers my variable as `{ [eventName in Keys]?: States | undefined; }[Keys]` instead of further reducing it to `States | undefined`.

[Playground Link](https://www.typescriptlang.org/play/?ts=Nightly#code/PTAEAsBdIBwZwFwgOYEtLgK4CMB0BjAewFtgAnAUwEN9xzraBaTVYbAG0O2GKrkgplgMGgGsqyCnGCRChdpFQxgcMvmCoAdgBMKAD1wArOACgTkAJ4wKoAMLgqZSAB4AypCoC4ofQJ3f+Mi1kABpQAGkKC29fCn9QQOCAPlAAXlAAbxNQUC10VCp2BFB3TykAbmyEjy9irJycgG1XXM0SmqkAXTqqhp9NATIAfmKANUJUbQAxTE18RUJNSr6c9moANwoR0HHJmbmFpd6GxbrQRopNgYA5KmIbLQiouE7t0q9QAF9lhu+qv7+Jn0MEITlAADNZvNUItQABZGjgLQUNwdGJ6PzaAKQIKaUJPaI+DFxLHVXHIJIACiq-DK9kckGK9KcqLKcDCkWiSRMAEpMlU1pBQPhMGRKAN3jZ0rSBMzILg8opCpUqkRNPxQDiqOr8rD0pTNL5OcVOXA+akUvUGmqNTKKAARCjgtLVOkOJy4O1wRoisVxSCSzo-HI2oWGjGSl12x3g3CLRrhyCcoNmPqoZ2UyzWQjOxOR1IF0AAclmunByO0Rb5Vr6GDIhAA7qBDU2AKJi0HUlYNAAGABUyNq4Lq2ppCEKyxXcKAAEQAEgyic5nxnuW8syoHBsslA2AemnWhFEFG0oAb6HAwtF4qFdpdC99N8ln1wPeOOR5wa+PnYcBsNYaaMnVwNYqE2IZcEpT932FRYNUTGMow6OVPTRBNfEDL8cgQ4D-UECCoKwq8-QlDoXTzDoiJAUAAHlsD-Mh1k3NZm3HdMLGOT5-hVEM4KFSRIFsa9-XzUAoLSS1jkoSBRTaR8RMo7jU1AaTZPOLUdUOMIBKEkiAw6TpQD4WD1UgSouJMUN+kwYhQAADX5HIAEl7QAGVbEIqimGjbAAVVcVt7U8rigA)

**Comment by RyanCavanaugh** [comment]
FYI this isn't a mapped type.

The function could be written as
```ts
function test(value: Example[keyof Example]): void {
    if (value === null) {
        onlyNull(value);
        return;
    }
    onlyBoolean(value);
}
```
without loss of generality; if you have a more complete example that requires `K` I could advise further.

The narrowing here can't apply because `value` isn't a union type -- it's a deferred lookup type over a generic type parameter. #33014 would likely be a prerequisite to handling this correctly.

**Comment by whitneyit** [comment]
Consider this more complex example:

```ts
const I18N_EXAMPLE_WITHOUT_DATA_KEY = `Example.WithoutData`;
const I18N_EXAMPLE_WITH_DATA_KEY = `Example.WithData`

type I18nKey = typeof I18N_EXAMPLE_WITHOUT_DATA_KEY | typeof I18N_EXAMPLE_WITH_DATA_KEY;

interface I18nDataMap {
    [I18N_EXAMPLE_WITHOUT_DATA_KEY]: null,
    [I18N_EXAMPLE_WITH_DATA_KEY]: { count: number },
}

function onlyNull(arg: null): void {
    // do nothing
}

function interpolate<K extends I18nKey>(key: K, data: I18nDataMap[K]): string {
    const value = `Use ${key} to fetch value from somewhere`;
    if (data === null) {
        // Argument of type 'I18nDataMap[K]' is not assignable to
        // parameter of type 'null'.
        onlyNull(data);
        return value;
    }
    const result = `Some interpolated value`;
    return result;
}

```

In the above example, `K extends I18nKey` is used to ensure the relationship between `key` and `data` is preserved. Unfortunately my initial example did not show that relationship.

**Comment by pleunv** [comment]
Apologies for digging this up, but I think I'm running into a similar (or the same) issue. Given this code ([playground link](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAMwK4DsDGMCWEV1ACwEMkBnLAN2AGF9g0BrACjVoYC44VhKoBKDrjzgBvAFBw4MfFAgB3TsHkBRKDKiMA5EoBK2gPLaAhBt4BuUQF9RozChjAoCQmmBwAysBhYUAcxIjxOBJPbx8AQQ4AIwgIABtgQhRzCWCvWx8AIQ4yKHTkoJD0qgEkAFtIh3MrUWR0LBw4H08ANUJYpGAAHgAVPBB7FAATf3pgAE8IBHdC3xIAPkZRsY5u-mm02YBtboBdAIlMKcXxuABec7gNVNCwk32JOChPJChcGCgO-Is8WOC4Q7gxzGZwuVxmmTuYgej2er0u9jIGi+Pz+AKBINOl2uRUhgQkTxgL1wAFZkcBfq40UsMZdcdCCMQyJhKDQ6EwlmZAlYLEA)):

```typescript
export function exhaustiveCheck(check: never): never {
  throw new Error('ERROR!');
}

interface Settings {
  settingA: boolean;
  settingB: string;
  settingC: number;
}

function getValue<T extends keyof Settings>(key: T): Settings[T] {
  if (key === 'settingA') {
    return true;
  } else if (key === 'settingB') {
    return 'test';
  } else if (key === 'settingC') {
    return 5;
  } else if (key === '') {
    exhaustiveCheck(key);
  }
}
```

I would expect both the `key` to be narrowed, and the return value to be mapped to the corresponding mapped type. However, neither seems to work:

![image](https://user-images.githubusercontent.com/182021/109061561-1a8e7a00-76e7-11eb-82c8-3902696e4b93.png)

Am I completely missing something here, or is this simply not possible? I have similar approaches in other places that do seem to work fine.
