### ISSUE TITLE
Incorrect type inferrence for default-initialized parameters and noImplicitAny

### ISSUE THREAD

**Issue by dave-hart** [microsoft/TypeScript#36052]
Having a default initialized parameter in a function declaration passed to a function incorrectly asserts that the parameter is an `any` type

**TypeScript Version:**  
3.7.4 (also reproduced on Nightly)
I recently upgraded from Typescript 3.5.2 to 3.7.3. The code below was fine with ts 3.5.2

**Search Terms:**
default parameter noImplicitAny
**Code**

```ts
function execute(script: string | Function): Promise<string> {
  return new Promise((resolve, reject) => {
    if (typeof script === 'string') {
      reject('rejecting promise');
    }
    resolve('resolving promise');
  });
}

export function executeSomething() {
  return execute((root: HTMLElement, debug = true) => {
    if (debug) {
      root.innerHTML = '';
    }
  });
}
```

**Expected behavior:**
No Errors

**Actual behavior:**
I get an error for the `debug = true` statement. "TS7006: Parameter 'debug' implicitly has an 'any' type."

**Playground Link:** 
[Playground link](http://www.typescriptlang.org/play/?ts=3.8.0-dev.20200104#code/GYVwdgxgLglg9mABAUwB7IiKyAUBnCAJxgAcoAuRPKYsAc0QB9EAxcaeMASkoAVC4AWxh5kAHmq06APkQBvAFCJEhZFBCEkYZAHdE-ISNw5VeOABsAbsgA0K5ACsMULogC8sxcuUxgiHFAAniTIcH4ExGTubm6IAOSSMPRxrl7eyqpO0Dhxmc5JDCQCwqIpANxK3gC+lRnIZla4ufUWlgWIRYalXBXKVT0KNQpoJHCEUIigkLAIKOiY2ADKQmoAFgU4qZWq6ppzGFjGAnAUiAASACoAsgAyAKLmyILIYFB2ACbIAEYgDLE0IGQrg88lqiF8-k+PzoW3SGTgJwAdEltIRLrd3PE4r1qpV+hUqkA)

**Related Issues:** 
None

**Comment by RyanCavanaugh** [comment]
```ts
// No error
const f1 = (debug = true) => false;
// Error, but shouldn't be -- contextual type from 'Function'
// shouldn't have negative effects here
const f2: Function = (debug = true) => false;
```

**Comment by ahejlsberg** [comment]
This is actually working as intended. For `f1` it is meaningful to infer from the initializer because the inferred type will constrain arguments that can be passed for `debug`. But for `f2` we've already established that the type is `Function`. Thus, anything we infer for `debug` will be disregarded, and we have no idea what type of arguments will actually be passed (and keep in mind that the default value only kicks in when we're passed an undefined).

It's a similar discussion to here https://github.com/microsoft/TypeScript/issues/30840#issuecomment-487955725.

**Comment by ahejlsberg** [comment]
Having thought about it some more, I now agree that this is a bug. #36476 has the fix.
