### ISSUE TITLE
Splitting of type argument instantiations

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#36130]
The same type argument should have been instantiated to the same type.

**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**

**Code**

```ts
class Coroutine<T = unknown, R = unknown, S = unknown> {
  constructor(_: (this: Coroutine<T, R, S>) => Generator<R, T, S> | AsyncGenerator<R, T, S>) {
  }
}
new Coroutine(function* () {
  const _: number = yield 2;
  return 0;
});
new Coroutine(async function* () {
  const _: number = yield 2;
  return 0;
});
```

**Expected behavior:**
`(local function)(this: Coroutine<number, number, number>): Generator<number, number, number>`
`(local function)(this: Coroutine<number, number, number>): AsyncGenerator<number, number, number>`
**Actual behavior:**
`(local function)(this: Coroutine<unknown, unknown, unknown>): Generator<number, number, number>`
`(local function)(this: Coroutine<unknown, unknown, unknown>): AsyncGenerator<number, number, number>`
**Playground Link:** 

**Related Issues:** #36129

**Comment by falsandtru** [comment]
@rbuckton

**Comment by rbuckton** [comment]
It doesn't seem to like the `this` type specified in the function type.

**Comment by rbuckton** [comment]
Despite the example, this doesn't seem related to generators but how we handle `this` type inference, as the following example fails as well:

![image](https://user-images.githubusercontent.com/3902892/88740718-c5f43380-d0f2-11ea-825e-a3dcb6306f3f.png)

**Comment by rbuckton** [comment]
This is a fairly complex issue as it relates to the order in which inferences are made when resolving the construct signature. Here's what is happening:

1. We start resolution for the construct signature for `Coroutine` and begin inference for its type arguments.
2. We encounter the argument `_` and see that it is context sensitive.
3. We instantiate a signature using the contextual signature of `(this: Coroutine<T, R, S>) => Generator<R, T, S>`
4. We immediately instantiate the `this` parameter of the function expression, which instantiates `Coroutine<T, R, S>` before we've made any other inferences. This fixes the inferences for `T`, `R`, and `S` to their defaults (`unknown`).
5. Since these inferences are fixed, we don't perform inferences against the return type of the function expression.

If you remove the `this` parameter from the contextual signature, when the function expression's signature is instantiated we don't have a reason to map `T`, `R`, and `S`, and thus don't end up fixing the inferences early.

This also occurs when using a regular parameter:

```ts
class Coroutine<T, R, S> {
  constructor(_: (p: Coroutine<T, R, S>) => Generator<R, T, S>) {}
}
const a = new Coroutine(function(p) { return {} as Generator<number, number, number>; });
const b = new Coroutine(function() { return {} as Generator<number, number, number>; });
```
Above, `a` ends up with the type `Coroutine<unknown, unknown, unknown>` again because during inference for the constructor we find a matching, untyped `p` in the function expression and infer its type. This results in us instantiating `p` and again fixing the types for `T`, `R`, and `S` early.

Interestingly enough, `b` ends up with the type `Coroutine<number, number, number>` because it does *not* have a matching parameter to be instantiated. As a result, we don't fix the inferences and correctly infer from the return type of the function expression.

Addressing this may require a complex change to our inference mechanics.

**Comment by RyanCavanaugh** [comment]
Closing as design limitation for now; we can revisit if more people encounter this
