### ISSUE TITLE
TS2565 occurs even if property definitively initialised in super() call

### ISSUE THREAD

**Issue by CreatedBySeb** [microsoft/TypeScript#36158]
**TypeScript Version:**  3.7.4 (local), nightly/3.8.0-dev.20200111 (playground)

**Search Terms:**
TS2565, not definitively assigned (super)

**Code**

```ts
class Superclass {
	public array: Array<string | number>;

	constructor(initial: Array<string | number>) {
		this.array = initial;
	}
}

class Subclass extends Superclass {
	public array: Array<string>;

	constructor(initial: Array<string>) {
		super(initial);
	}
}
```

**Expected behavior:**
The code compiles successfully, as Superclass will definitively set the array property.

**Actual behavior:**
The code fails to compile with `error TS2564: Property 'array' has no initializer and is not definitely assigned in the constructor.`.

**Reproduction**
https://github.com/CreatedBySeb/ts2565-inheritance-reproduction

**Playground Link:**
[Playground Link](https://www.typescriptlang.org/play/?ts=Nightly#code/MYGwhgzhAEDKCuAHApgJ1JGBvAUASEXgCMQBLYaMVVMATwC5oBBaugHggBdVSA7Ac2gAfaL3gBbImgB8Abhz5gAe15dU8YJyWoAFH1KdSYEIxY1aHbn0EixkmQEpouPHk4ALUhAB0Vc9ABeaH1DY3k8AF8cKJwMKDhiOJhkAA9OZF4AExgEFHRweJdCEnJKVgZmcsseATkFPGVVbg0tXRCjE0rzautpJxc8CCQ0PV4DDodwqIigA)

**Related Issues:**
None

**Comment by AlCalzone** [comment]
Since you are only changing the type, you should use a `declare` field instead:
```ts
class Superclass {
	public array: Array<string | number>;

	constructor(initial: Array<string | number>) {
		this.array = initial;
	}
}

class Subclass extends Superclass {
	declare array: Array<string>;

	constructor(initial: Array<string>) {
		super(initial);
	}
}
```
When the `useDefineForClassFields` flag is active (AFAIK this will be the default in the future), `array` **will** be redefined in the subclass and therefore may actually be undefined ([Playground Link](https://www.typescriptlang.org/play/?useDefineForClassFields=true&ts=3.8.0-dev.20200111#code/MYGwhgzhAEDKCuAHApgJ1JGBvAUASEXgCMQBLYaMVVMATwC5oBBaugHggBdVSA7Ac2gAfaL3gBbImgB8Abhz5gAe15dU8YJyWoAFH1KdSYEIxY1aHbn0EixkmQEpouPHk4ALUhAB0Vc9ABeaH1DY3k8AF8cKJwMKDhiOJhkAA9OZF4AExgEFHRweJdCEnJKVgZmcsseATkFPGVVbg0tXRCjE0rzautpJxc8CCQ0PV4DDodwqIigA)).

**Comment by MartinJohns** [comment]
I don't see how this code should be valid in the first place. It's a clear type issue.

    const r1: Subclass = new Subclass(["abc"]);
    const r2: Superclass = r1; // Assignment possible, because inheritance.
    
    r2.array.push(123); // number is possible, because array is typed Array<string | number>
    r1.array; // Type is Array<string>, but it actually contains numbers.

**Comment by AlCalzone** [comment]
@MartinJohns I think this pattern requires some discipline when using the classes.
I'm doing a similar thing in a library of mine. The superclass defines a property as number, the subclasses each redefine them as different enums. Although they are actually compatible in both directions, unlike `string|number` <-> `number`.
