### ISSUE TITLE
BigInt should not be a subtype of an object type

### ISSUE THREAD

**Issue by Vbitz** [microsoft/TypeScript#36155]
**TypeScript Version:**  3.8.0-dev.20200111

**Search Terms:** "BigInt"

**Code**

```ts
declare function test<A, B extends A>(): void;

test<{t?: string}, object>();
test<{t?: string}, bigint>();
test<{t?: string}, number>();
```

**Expected behavior:** `bigint` should behave like `number`.

**Actual behavior:** BigInt instead behaves like a object.

**Playground Link:** https://www.typescriptlang.org/play/?target=99&ts=3.8.0-dev.20200111#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwxAGcMAeAQQBp4AheEAD0NWCPnID4AKASgC54ANxxZgAbgBQEwiVIBvDAH4BJGFlQBzAL7UcAIwBW4DNx6SZZBcvir126nqwb1J3ueKWlKjGs074qMgAtnogMKZiQA

**Related Issues:** 

**Main BigInt Issue:** https://github.com/microsoft/TypeScript/issues/33871

**Comment by AnyhowStep** [comment]
Weird. I would have expected `object` to also fail.
Because `B["t"]` could be `number`inside the function body.

```ts
function foo<A, B extends A>(a : A, b : B, k : keyof A): A {
  a[k] = b[k];
  return a;
}
foo<{t?:string}, object>(
  {},
  {t : 999},
  "t"
).t; //Expected: undefined|string, Actual: 999
```

**Comment by sandersn** [comment]
Notably, `number` fails the common-property check. It doesn't give the expected "Type 'number' does not satisfy the constraint '{ t?: number }'." either.

This has been a bug since bigint was introduced as far as I can tell. Moving to 3.9.

**Comment by sandersn** [comment]
Now that I'm trying to fix this for 3.9, I can't repro *either* example. `bigint` and `number` behave the same in all versions of Typescript that I tested locally -- 3.2 through 3.8. @AnyhowStep's `foo` example correctly returns `string | undefined`. And the playground link in the OP only fails because `bigint` isn't found at all in that dev playground.

I'm going to close this for now, although it's possible that I'm missing something.

**Comment by Vbitz** [comment]
I can confirm the original Playground link I posted now doesn't find the BigInt declaration.

Here is a new playground link switched to the nightly version reproducing the same case with the same code.

**TypeScript Version:**  Nightly

**Code**
```ts
declare function test<A, B extends A>(): void;

test<{t?: string}, object>();
test<{t?: string}, bigint>();
test<{t?: string}, number>();
```



<details><summary><b>Output</b></summary>

```ts
"use strict";
test();
test();
test();

```


</details>


<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```


</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?ts=Nightly#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwxAGcMAeAQQBp4AheEAD0NWCPnID4AKASgC54ANxxZgAbgBQEwiVIBvDAH4BJGFlQBzAL7UcAIwBW4DNx6SZZBcvir126nqwb1J3ueKWlKjGs074qMgAtnogMKZiQA)

**Comment by sandersn** [comment]
ah, the difference is that my test project had `target: "esnext"` but the playground link has `target: "es2017"`. When I change the target on my test project, the error blinks on and off.

**Comment by sandersn** [comment]
The core problem here is that es2020.bigint.d.ts defines the contents of `interface BigInt`. Without `lib: ["es2020"]`, `bigint` is actually assignable to an empty object literal type because its apparent type, `BigInt` is empty.

It's only an error to not define `BigInt` when asking for `bigint`'s apparent type when the target is esnext. Otherwise, you are expected to know that you need to add `"es2020"` to your lib, even when you're targetting an earlier version of JS. This is quite subtle.

**Comment by sandersn** [comment]
This is, as far as I can tell, how bigint and BigInt are supposed to work. It looks like symbol works this way too, judging by the code in getApparentType, which is what converts `bigint` to `BigInt` when needed.

I'm going to close this, since I think we got to the bottom of the current problem. However, a fresh issue with a proposal of how to make bigint less confusing in pre-es2020 targets would be welcome.

I filed #37899 to display an error in ES2020 when BigInt is missing. Previously it only applied to ESNext.
