### ISSUE TITLE
No spelling suggestion/quick fix for misspelled uses of an import

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#36238]
```ts
// ./foo.ts

export class SomeThing {
    
}
```

```ts
// ./bar.ts

import { SomeClass } from "./foo.js";

SomeClas
```

**Expected**: "Cannot find name 'SomeClas'. Did you mean 'SomeClass'?"
**Actual**: Standard "Cannot find name 'SomeClas'." error.

**Comment by a-tarasyuk** [comment]
```ts
import { SomeClass } from "./foo.js";
         ^^^^^^^^^
```
`SomeClass` marked as `SymbolFlags.Alias`, in the meanwhile `getResolvedSymbol` doesn't use `SymbolFlags.Alias`, only `SymbolFlags.Value | SymbolFlags.ExportValue`.

`resolveNameHelper` _`(getResolvedSymbol -> resolveName -> resolveNameHelper)`_ doesn't return any suggestions because `getSuggestedSymbolForNonexistentSymbol` resolves only `SymbolFlags.Value | SymbolFlags.ExportValue` and ignores `SymbolFlags.Alias`.

```ts
suggestion = getSuggestedSymbolForNonexistentSymbol(originalLocation, name, meaning);
```

I'm not sure that `getResolvedSymbol` should have meaning `SymbolFlags.Value | SymbolFlags.ExportValue | SymbolFlags.Alias`, because it will break some tests, and also extending `meaning` by `SymbolFlags.Alias` inside `resolveNameHelper` seems is not the right way.

What do you think @DanielRosenwasser @andrewbranch?

**Comment by andrewbranch** [comment]
The reason we don’t call `resolveNameHelper` with a meaning that includes `SymbolFlags.Alias` is that `getSymbol` (which is usually what `lookup` is in `resolveNameHelper`), when checking that a candidate symbol matches `meaning`, will resolve aliases first, then match `meaning` against the resolved symbol instead of against the alias. The problem seems to me that `getSpellingSuggestionForName` doesn’t do the same:

```ts
function getSpellingSuggestionForName(name: string, symbols: Symbol[], meaning: SymbolFlags): Symbol | undefined {
    return getSpellingSuggestion(name, symbols, getCandidateName);
    function getCandidateName(candidate: Symbol) {
        const candidateName = symbolName(candidate);
        return !startsWith(candidateName, "\"") && candidate.flags & meaning ? candidateName : undefined;
    }
}
```

Here, `candidate.flags` is going to be `SymbolFlags.Alias`, and `meaning` is never going to match that because that’s not a, uhm, meaningful meaning to pass to `resolveNameHelper`. So I think this meaning check needs to do the same thing as `getSymbol`, where it checks the flags first, then if there’s no match and `candidate` is an alias, resolves the alias and checks the flags of the resolved symbol.

**Comment by a-tarasyuk** [comment]
Thanks for your feedback 👍 . I've checked and found that `symbols` can have `export=` which is `Alias` too. If a `candidate` is `export=` - `resolveAlias` returns `Circular definition of...` for code like so

```ts
export = test
```

Maybe there are some other potential cases that will cause a similar error. What do you @andrewbranch  think is it safe to handle `Aliases` directly in `getSpellingSuggestionForName`?

**Comment by andrewbranch** [comment]
I’m not totally following why `resolveAlias` on an `export=` would always result in a circularity... I think I’d have to see the whole problem and maybe work through it. If you want to experiment with it and open a WIP PR, I’d be happy to help look at it, or if you don’t feel like it I can pick it up later this cycle.

**Comment by a-tarasyuk** [comment]
@andrewbranch I'll create Draft PR for this issue
