### ISSUE TITLE
///<reference path=... /> is case sensitive on Linux, but case insensitive on Windows

### ISSUE THREAD

**Issue by duanyao** [Microsoft/TypeScript#3626]
tsc treats path values in `///<reference path=... />` as case sensitive on linux, but case insensitive on Windows. This behavior makes codes writing on windows not portable if the casing of source file paths is inconsistant with the paths in `///<reference path=... />`.

**Comment by kitsonk** [comment]
Isn't that an underlying OS challenge?  I am not sure how you can resolve that cleanly, because there is no way to force either one at the runtime engine perspective to behave like the other.  You can't force Linux to cover off every permutation of case sensitivity.  The only option is to see if the actual file name returned from the OS call on Windows matches the case of the original file, and I wonder if that is actually worth the overhead.  There are several issues including joyent/node#6000 that discuss the issues/challenges with the support in NodeJS.

**Comment by duanyao** [comment]
I think it is technically possible to make the behavior on Windows becomes case sensitive, because Windows file system is case-preserving, i.e. when you ask what the path of a file is, Windows gives you the result in correct case. So after tsc has resolved the referenced file, it can query the actual path from the OS, and compare it with the path specified in .ts case-sensitively; if not matching, fire an error.

It seems that the node's issue you mentioned won't be fixed because of backward compatibility problem.

**Comment by mhegazy** [comment]
It should be fairly easy to add a compiler flag to always treat file lookups as case sensitive. the infrastructure is already in, it is just now surfaced as a compiler option. We would consider a PR if you are interested. you will need to do some pluming through in all places where getCanonicalFileName is used.

**Comment by duanyao** [comment]
@mhegazy Good news, thank you. I'd like to look at this when I have time, though can't promise.

**Comment by benliddicott** [comment]
This seems like an issue for the build system rather than the language...

Looks like an issue for a lint-like tool to me. I.e. warning on uppercase letters in filenames.

**Comment by duanyao** [comment]
@benliddicott `tsc` is the build system involved. Always using lowercase letters in filenames may be OK, but I think it is more natural to use the same name for a class and the file it lives in.

**Comment by benliddicott** [comment]
That could be two compiler warnings then:
1) Warn if the filename in a `///<reference path=""/>` comment differs in case from the filename on disk
2) Warn if two files on disk are found with the same name differing only by case.

They can only be warnings, because the first is not incorrect on case-insensitive systems, and the second is not incorrect on case-sensitive systems. Yet either is probably a mistake by somebody.

I guess the first is most important as a major workflow is develop on Windows, deploy on Linux, and the second doesn't need to be part of the compiler at all (and might be easier as a standalone tool like `node checkFilenameCase.js`.

**Comment by MartyIX** [comment]
@mhegazy @DanielRosenwasser I was doing some research for this issue and I'm stuck because I don't know how to actually get "canonical path" of a file from NodeJs. Any suggestions are very welcomed.

Problematic part of the code is this line: https://github.com/Microsoft/TypeScript/blob/master/src/compiler/sys.ts#L200 where you guys check if given file exists. And it exists for possible capitalizations of the file path.

I went through NodeJs `fs` API and I haven't found any useful function for this (I have already posted a question to Node.js community - https://github.com/nodejs/node/issues/3352 with a request for help.)

Do you have any idea how to move forward?
____
Apparently, it is not so simple to get canonical path in .NET either: http://stackoverflow.com/questions/4763117/how-can-i-obtain-the-case-sensitive-path-on-windows

**Comment by vladima** [comment]
#5275 should address this. It does not attempt to verify that filename used in program matches with the name on file system (this getting the latter one is tricky). Instead it makes sure that all places in program that reference some file have consistent casing of file name.

**Comment by MartyIX** [comment]
I see. 


___
I have tried the snippet from StackOverflow and it is nice that it allows you to write portable TypeScript scripts. My alpha patch has the feature under a compiler flag.

**Comment by duanyao** [comment]
Hi @vladima and @MartyIX ,
It seems not difficult to get case-exact path on Windows Vista+. Windows API [`GetFinalPathNameByHandle`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366789(v=vs.85).aspx) does this trick. On older Windows, use [`CreateFileMapping + MapViewOfFile + GetMappedFileName`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366789(v=vs.85).aspx), though I believe the usage of Windows XP in TS community is neglectable now.

**Comment by MartyIX** [comment]
@duanyao Please consider adding your solution to my question http://stackoverflow.com/questions/33086985/how-to-obtain-case-exact-path-of-a-file-in-node-js-on-windows. I'll gladly upvote. :-)

I would love a flag to ensure that paths are correct on Windows and Linux, but it is not my decision to make.

**Comment by vladima** [comment]
fixed in e811fecda645cd7905821d48fcf5f757dbedfa50

**Comment by mhegazy** [comment]
The fix should be in `typescippt@next` tonight. Use the new `--forceConsistentCasingInFileNames` command line argument to make sure you are catching casing issues consistently.

**Comment by leocaseiro** [comment]
Hi @vladima, is there any option to use forceConsistentCasingInFileNames on `.tsconfig` file? 
I couldn't find it. 
Thanks

**Comment by mhegazy** [comment]
All compiler options can be specified in tsconfig. here is more details on them: http://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by leocaseiro** [comment]
thanks a lot
