### ISSUE TITLE
Invalid declaration file generated when exporting a class marked as internal using stripInternal

### ISSUE THREAD

**Issue by PissedCapslock** [microsoft/TypeScript#36287]
**TypeScript Version:**  3.8.0-dev.20200118

**Search Terms:** stripInternal export class

**Code**

```ts
/**
 * @internal
 */
class Foo{
    public bar(): string{
        return "bar";
    }
}

export {Foo}
```

and compile it using

```
npx tsc --stripinternal --declaration Foo.ts
```

**Expected behavior:**

A declaration  file containing

```
export {};
```

**Actual behavior:**
An invalid declaration file containing

```
export { Foo };
```

Note that it does work when using `export class Foo` instead of first declaring the class and exporting it afterwards.

**Playground Link:** 

**Related Issues:**

**Comment by ajafff** [comment]
stripInternal only removes the declaration it is on. It doesn't affect anything else in the declaration file. This option is meant to be used at your own risk, that's why it's not documented in the official compilerOptions docs. 

You can even create syntactically invalid declarations if you use `// @internal` in weird places.

I wanted to write a linter rule for that, but I never finished it...

**Comment by PissedCapslock** [comment]
I know it's a matter of use at your own risk.
On the other hand, it's currently the only thing library writers have at their disposal if they want to hide implementation details for the users of their library.
