### ISSUE TITLE
Indexed access operator issue with Omit type

### ISSUE THREAD

**Issue by maciejsikora** [microsoft/TypeScript#36316]
**TypeScript Version:**  3.7.2

**Code**

```ts
type A = {
    id: string,
    name: string,
    lastname: string
}

type B<T extends A> = Omit<T, 'id'> // type without id field

type C<T extends A> = B<T>['name']; // error cannot be used to index type 'Pick<T, Exclude<keyof T, "id">>
type D = B<A>['name']; // works correctly
type E = Omit<A, 'id'>['name'] // works correctly
type F<T extends A> = T['name']; // works - important example
```

**Expected behavior:**
As `T extends A` then T has all fields A has, therefore Omit by one field should not be a problem in getting to others.  Also other examples working on `A` directly shows no problems in compilation.

Take a look also that type `F` is also correct where `Omit` was not used. That means that correlation between `T extends A` and `Omit` has problems.

**Actual behavior:**
Type constructor  `C` has compilation error.

**Playground Link:**
http://shorturl.at/ilI59

**Related Issues:**
https://github.com/Microsoft/TypeScript/issues/23647

**Comment by RyanCavanaugh** [comment]
We don't have any mechanisms available that could resolve this. The problem is that `Exclude` is a higher-order operation; when its input is generic, we don't have any way to predict what comes out the other side. If `Exclude` and `Omit` were *built in* to the type system, instead of being type aliases that you can replicate in user space, then there'd be some chance of this, but from TS's perspective this is like you writing `Shark<Mortgage<T>, "id">` - the output type given a `T` is not resolvable.
