### ISSUE TITLE
Typescript should always reduce T[number][] to T when T extends any[]

### ISSUE THREAD

**Issue by ethanresnick** [microsoft/TypeScript#36337]
**TypeScript Version:**  3.8.0-dev.20200119

**Search Terms:** array number index elements

**Code**

One of many examples where TS errors because it doesn't perform the simplification described in the title. Is there some problem with this rule that I'm missing?

```ts
declare function operate<T>(it: T[]): T[];

class Test<T extends any[]> {
  constructor(public field: T) {}

  method(): T {
    // Type param inferred as `any` by default, possibly because this rule is missing.
    return operate<T[number]>(this.field);
  }
}
```

**Expected behavior:**
No type errors.

**Actual behavior:**
Error
```
Type 'T[number][]' is not assignable to type 'T'.
  'T[number][]' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint 'any[]'
```

**Playground Link:** [Playground Link](http://www.typescriptlang.org/v2/en/play#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXxwAcQYoMQAeAFQD4AKLDALnioG0BdAShfY4G4AUJCgBnUaxCiM1eCAAe5VMAlRUAT0414Ab0Hx4YPNJjJMOGHULIARhCxgkWEBGC8uugL6D98ALYgGAAWOMB0PKy6vgYA9DGs6sTwhLBQfvBYqIgkcMDwYvAABmrqhfA26vCgiFDIEBgANPDR8HHJOOJYdpU24LWiCMFYEqYQCMP+w6KZAOYAdC1wGMgw+EQkZJTsqMh+vTAc9EOic4jOrlxCBt7egm1UOPBjsPh+FghQNjjIGPDBCNBUDNkFAZiAmpAHABrfJfABu43wACIAKLyNKEMaiJEEGDwJEAdSCZAA5BIAHIgADuSIWbQA8v8YFThuD4GDftJYOQ8hV4HA3nDZn8glIEEY-AFUBhVMoRQgqRZXBkJOpvnjMVB1DMYN9lAsgA)

**Comment by krryan** [comment]
Unfortunately, that’s not a true assumption: something like `['foo', 'bar', 'baz']` would be a valid argument for `T extends any[]`, but `['foo', 'bar', 'baz'][number][]` would be `('foo' | 'bar' | 'baz')[]`.

**Comment by ethanresnick** [comment]
@krryan Maybe I'm not following, but `('foo' | 'bar' | 'baz')[]` would also be a valid type to assign to `any[]`... I.e.:

```ts
// compiles just fine
const x: any[] = (['foo', 'bar', 'baz'] as ('foo' | 'bar' | 'baz')[])
```

**Comment by krryan** [comment]
Yes, but it would not be valid to assign to `T`. Consider:

```ts
function double<T extends any[] | readonly any[]>(values: T): T {
    const result: T[number][] = [...values, ...values];
    return result;
//  ^^^^^^^^^^^^^^
//  Type 'T[number][]' is not assignable to type 'T'.
//    'T[number][]' is assignable to the constraint of type 'T',
//    but 'T' could be instantiated with a different subtype
//    of constraint 'any[] | readonly any[]'.
}

const doubled = double(['foo', 'bar', 'baz'] as const);
// const doubled: readonly ["foo", "bar", "baz"]
```

This currently (correctly) fails because `[...values, ...values]`, while it **is** a valid `T[number][]`, is **not** a valid `T`. If your reduction of `T[number][]` to `T` were allowed, this would compile, and `doubled` would be assigned type `T`—that is, `['foo', 'bar', 'baz']`, even though it is _definitely not_ going to have that type in practice.

And depending on what `operate` does, your example could have exactly the same problem. What would happen if I used the following code:

```ts
const data: ['foo', 'bar', 'baz'] = ['foo', 'bar', 'baz'];
const test = new Test(data);
const tested = test.method();
```

According to your type annotations, I should expect `tested` to have the type `['foo', 'bar', 'baz']`. Does your `operate` function actually guarantee that? I suspect not.

If you don’t want to worry about this, you are probably better off using an unconstrained `T`, and defining the constructor to take `T[]`, rather than trying to use `T extends any[]`.

**Comment by ethanresnick** [comment]
@krryan You make a good point about tuple types, and I think that probably dooms this concept. If TS had a way to picking out array types that aren't tuple types, then I think there'd be a kernel of an idea here (and it wouldn't be too hard to preserve readonly), but the tuple type thing's a big problem.

**Comment by krryan** [comment]
As someone who works with tuples a lot (and _relies_ on the behavior that’s causing you trouble), I certainly wouldn’t mind a way to constrain things to tuples or non-tuples.

**Comment by RyanCavanaugh** [comment]
Really appreciate the great discussion here! There is definitely some subtlety around `T extends any[]` with `T` vs unconstrained `T` with `T[]`. I don't think this suggestion as-is can go in, but we can always consider a follow-up that doesn't have the tuple problems.
