### ISSUE TITLE
Auto import suggestions for relatives don't work when file is closed in editor

### ISSUE THREAD

**Issue by Yegorich555** [microsoft/TypeScript#36350]
**TypeScript Version:**  3.7.4
**VSCode Version:** 1.4.1

**Search Terms:**
Auto import suggestions don't work

**Code**
```ts
// testA.ts file --- that must be written and closed in VSCode
export default function testA(): void {
  console.warn("imported testA");
}

//index.ts file
testA() //there is no suggestion in suggestions-list
```

**Expected behavior:**
Auto import should suggest import to the relative module when the relative file is closed

**Actual behavior:**
There is no suggestion in suggestions-list to the relative module when the relative file is closed

**Playground Link:** 
[https://github.com/Yegorich555/webpack-mock-server/tree/tsAutoImportBug](https://github.com/Yegorich555/webpack-mock-server/tree/tsAutoImportBug)
1) npm install
2) playground with files in ./src/

**Notes**
It works as expected when required files are opened in the editor. I'm not sure is it the VSCode issue?

**Comment by RyanCavanaugh** [comment]
This is the intended behavior.

TS only considers files considered to be part of the same project. This can be driven by:
 * Existing explicit file dependencies
 * Being included by the same tsconfig.json file
 * Being included by the same jsconfig.json file
 * Being in an open editor window and not associated with another project

Basically, by design, we don't just scan your entire hard drive, or even the current folder, to try to find auto-import candidates.

**Comment by minestarks** [comment]
It's worth noting @RyanCavanaugh 's description only applies to VS Code - this behavior is editor dependent. For what it's worth, the auto-import will work as @Yegorich555  expects in Visual Studio's Open Folder scenario since Visual Studio will proactively include all .ts and .js files in the workspace in the project context, whether they're open or not. 

VS Code does have good reasons for excluding closed files by default, but it's not something enforced by TypeScript itself.
