### ISSUE TITLE
Function is not recognized as first class object.

### ISSUE THREAD

**Issue by rexkenley** [microsoft/TypeScript#36471]
Typescript seems to have an issue with acknowledging that Functions are first class Objects. An acquaintance was able to "solve" it by doing a "double as cast". *ts-ignore is  preferable compared to  that.
 
[TS sample](https://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABMATgCigCxgZwFyICGYAngDSIBuhANiAKYFggC2ARvSgJSIDeAUIkQp6UECiQB5NgCt60AHQBreiRwZsOLguAwwAEzRLEAXgB8iLLgDaSgLqmTJqrQZcA3PwC+-fvWYsiP6sAGq0fIJEpogAjGSRbNEATN6+NKKIbAQYJAAO9HDAQQFhNB5pGQCiAZXUNNGoCmx6hsEspTyEOIhoaHUMeAEc3KYWOFAoegDmiAA+PVB5BUVtHeXScopdODBTYGjVrLW0FKu05fwA9JeIAOqYJIi4lpj0iBBdUML0AI4gMCJ9AB+fgQBA4ODpBQ0OBTXqHFjHepdRDgJRgOAAdyQKMW+UKxVC5wUhHKYLAEKhMLhCKRaBiXHKQA)
credit: @ddlabar twitter

**Comment by IllusionMH** [comment]
Please ask questions on StackOverflow.
You have wrong type because you have wrong type definition of `EnumEval` (function that returns `string` or `typeof Enum`, problem also that wrong example has union instead of intersection) instead of (function that returns `string` or `undefined` and has properties of `Enum` which is`((value: number) => string | undefined) & typeof enumValue`).

`Object.assign` is smart enough to provide correct type: [Fixed example](https://www.typescriptlang.org/play/?ssl=15&ssc=1&pln=16&pc=1#code/GYVwdgxgLglg9mABMATgCigCxgZwFyICGYAngDSIBuhANiAKYFggC2ARvSgJSIDeAUIkQp6UECiQB5NgCt60AHQBreiRwZsOLguAwwAEzRLEAXgB8iLLgDaSgLqmTJqrQZcA3PwC+-fvWYsiP6sAGq0fIJEpogAjGSRbNEATN6+NKKIbAQYJAAO9HDAQQFhNB5pGQCiAZXUNNlodQx4ARzcphY4UCh6AOaIAD6I4Pr0umD0+jwAZJZ5BUXBLKXR0nKKhDg4ML1gaKgKbHqGS6VcFKe0HoieAPS3Qo9Pzy+vb88Ael-f38jHiAB3GA0GjCUTiJAjMZ6SbIOAoRAAZl8EAQODg6QUNDgvTQ1VYtVoCkI5VRYHRmOxuPxLEJNDQMS45SAA)

**Comment by rexkenley** [comment]
@IllusionMH Thanks!
