### ISSUE TITLE
Error is not showing on comparing when interface has optional variables

### ISSUE THREAD

**Issue by vlows** [microsoft/TypeScript#36602]
**Code**

```ts
interface A {
    id?: number;
}
const a:A = {
    id: 5
};
const testA: boolean = (a === 1); //works, but why?


interface B {
    id: number;
}
const b:B = {
    id: 5
};
const testB: boolean = (b === 1); //compiler error -> expected that also on A


```

**Expected behavior:**
An error on the compare line.

**Actual behavior:**
No error

**Playground Link:**
https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=18&pc=1#code/JYOwLgpgTgZghgYwgAgILIN4Chm+cAEwH4AuZEAVwFsAjaAbiwF8sEB7EAZzGThPQC8mHHkJkArM0bsuPSN1RkabNgBsIcEMiEAKONoFCAjAEp6yAPQWA7mygBrTgBpkNCj2sALAJ5Es-0EhYRBQAIWE8fAIySloGZlYOblcScKFsSLFkSSZpJLkIblClFXVNbWQdGgNjM0sLdioAB2B1KGRoKDtkAFoAPg6ADyaIBEgCZDBPOB44VU42ZA40fyA

**Related Issues:**

**Comment by jcalz** [comment]
Context: [relevant SO question](https://stackoverflow.com/questions/60054313/create-compiler-error-on-different-type-check-tsconfig)

Search terms: weak type detection, comparison operators

Related issues: 
#16047 - weak type detection PR
#17215 - comparability spec PR that I think never made it anywhere.

[Looks like this behavior is intentional](
https://github.com/microsoft/TypeScript/pull/17215/commits/e2e20bd6f810dd210f641794ab6a46e0d98eb0a4#diff-a37bdfbd0d2f3627958003f87033871eR2396), at least if I can take #17215 for its word:

> whether a type is considered weak has no bearing on whether two types are comparable,
