### ISSUE TITLE
JSDocThisTag with no type expression has empty type expresison node

### ISSUE THREAD

**Issue by dsherret** [microsoft/TypeScript#36693]
**TypeScript Version:**  3.8.0-dev.20200208

**Search Terms:** JSDocThisTag typeExpression

**Code**

```ts
const sourceFile = ts.createSourceFile("test.ts", `/**
 * @this - Some description.
 */
function test() {}`);

console.log(sourceFile.statements[0].jsDoc[0].tags[0].typeExpression);
```

**Expected behavior:** Undefined as type declaration has that as a possibility.

**Actual behavior:** `{ pos: 13, end: 13, ... }`

Select Options -> typescript@next and check "Show internals":

https://ts-ast-viewer.com/#code/PQKhCgAIUgBAXAFgSwM6QLSQMoHsC2AppACaGoDGATsgA7zK4B2AdFCMOAGYCuTFDZpHjl4ACgCUkAN4BfIA

![image](https://user-images.githubusercontent.com/1609021/74089549-2ec9ef80-4a70-11ea-81f5-c219fa5057fd.png)

**Comment by sandersn** [comment]
As far as I can tell, tags that error on a missing type create an empty type expression. Tags that don't have the property `undefined`.

Returns an empty type expression:
* `@enum`
* `@this`
* `@type`

Returns undefined:
* `@param`
* `@return`

The problem is that `typeExpression` is marked optional on `JSDocEnumTag` and `JSDocThisTag`, and they shouldn't be.
