### ISSUE TITLE
intellisense say error on clone new constructor() syntax

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/TypeScript#36721]
https://github.com/microsoft/vscode/issues/90311#event-3020816501

**Comment by jcalz** [comment]
Likely a duplicate of #3841.  There is a [template](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Bug_report.md) you are supposed to follow when filing a new issue here; even if this is not a duplicate it might be closed as unactionable because you have not followed the proper procedure.
