### ISSUE TITLE
[3.8] [BUG] TLA top-level await breaks with parenthesis

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript#36817]
**TypeScript Version:**  3.8.1-rc

**Search Terms:**

**Code**

```ts
// works:
const DBService = await import('./DBService')
await DBService.start()

// doesn't work
await (await import('./DBService')).start()
await (1 + 1)

// works:
async function foo() {
    await (await import('./DBService')).start()
}

export {}
```

**Expected behavior:**

no error on the `await` word

**Actual behavior:**

TS thinks it is an identifier.

**Playground Link:** 

[Playground link](http://www.typescriptlang.org/v2/en/play?ts=3.8.0-beta#code/PTAEHcHsCcGsGcBcAoAxpAdvALqAIgEIDKAptAG4CWqJoAvKAIbiOW6UC2ADjNgBQByAHTBCpCtRICAlMmatcYslRpCcjaP1nIQoACaQS8DANxQ4clm1B951zj02CRSiTRnS12DVssKbAIygANSgAdq65ggojPAAnhiooABmAK6J2JSYKZCQfNKgAN7IoKVMVri2FaAOvM6ixMqSHl4++cgAvsjIJAAejriFHUA)

**Related Issues:** 

https://github.com/microsoft/TypeScript/issues/35276

**Comment by rbuckton** [comment]
This is a consequence of how we parse source files and determine whether they are a _Module_ or a _Script_ based on the presence or absence of `import` or `export` declarations. According to the [TLA proposal](https://tc39.es/proposal-top-level-await/#sec-modules), `await` is now treated like a keyword at the top level of a _Module_, but not a _Script_. The fact that `await p` (without parens) works at the top level currently is actually due to the fact we would parse it as an `AwaitExpression` for error reporting purposes (and still do for `await` in a normal function). 

To address this, we will likely need to "reparse" a function call whose expression is an `await` and replace it with an `AwaitExpression` in any top-level position.

**Comment by rbuckton** [comment]
We are discussing the details necessary to make this work, but it may depend on changes to our AST Node Factory API proposed in https://github.com/microsoft/TypeScript/pull/35282
