### ISSUE TITLE
Compile error when using `external export` and  `reference path` in conjunction

### ISSUE THREAD

**Issue by wang-prtimes** [Microsoft/TypeScript#3683]
I'm encountering a compiler error when using `external export` and  `reference path` in conjunction.
I have some .ts files placed like below.

```
.
├── Modules
│   ├── UserAction.ts
│   └── UserStatus.ts
└── User.ts

```

`User.ts`
```javascript
class User {
	constructor() {
		...
	}
}

export default User;
```

`UserAction.ts`
```javascript
/// <reference path="../User.ts" />

// import User from '../User';   ← This will work, but I just want to use the `type` of `User`, I'm not going to use `User` it self.

class UserAction {
	public user:User;

	constructor(user:User) {  // TS2304 Cannot find name 'User'.
		this.user = user;
	}
}

export default UserAction;
```

The compiler says `TS2304 Cannot find name 'User'.` 
With using `import User from '../User'` instead, problem solved. But I just want to use the `type` of `User`, not  `User` it self (won't perform something like `new User`...).

If remove `export default User;` of `User.ts`, works fine...
Is this a bug ?

**Comment by danquirk** [comment]
This is by design. A top level `export` like this changes the scope of the things in your file vs what it sees from other files (ie it requires an import to bring things into its scope). See https://github.com/Microsoft/TypeScript/wiki/Modules.

We have an issue somewhere for 'type only' imports but I cannot find it at the moment. Our old import syntax (import x = require()) would elide the import in the generated JS if you only ever used the import in type positions, but this is no longer the case with ES6 syntax.
