### ISSUE TITLE
'async' modifier cannot be used in an ambient context.ts

### ISSUE THREAD

**Issue by francesc79** [microsoft/TypeScript#36989]
**TypeScript Version:**  3.8.2

**Search Terms:** allowJs declaration  'async' modifier cannot be used in an ambient context.ts

**Code**
see [code](https://github.com/francesc79/test-ts)

when run tsc with allowJs and declaration flags enabled the code below
```TestJS.js
export class TestJS {
    callAsync() {
        return Promise.resolve(1);
    }

    async test() {
        await this.callAsync();
    }
}
```
produce the declaretion:
```TestJS.d.ts
export class TestJS {
    callAsync(): Promise<number>;
    async test(): Promise<void>; --> error
}
```
but when a try to use this class I receive 'async' modifier cannot be used in an ambient context.ts(1040)

**Expected behavior:**
the TestJS.d.ts shouldn't contain async 

**Actual behavior:**
TestJS.d.ts conteins async 

**Playground Link:** [code](https://github.com/francesc79/test-ts)

**Related Issues:**

**Comment by pocesar** [comment]
was going to post about this right now, the behavior from JS / TS is definitely off

**Comment by DanielRosenwasser** [comment]
Tests should probably include a test for generators too.

**Comment by francesc79** [comment]
with typescript 3.7.5 work well

**Comment by DanielRosenwasser** [comment]
Seems like this is fixed in the nightlies. @weswigham can you verify, track down the fix, and cherry-pick it?

**Comment by a-tarasyuk** [comment]
This issue related to the method `makeSerializePropertySymbol`. In the [`3.8.*`](https://raw.githubusercontent.com/microsoft/TypeScript/af614ccea19e844142c8e6b0fdd70ccfdfcfa0db/src/compiler/checker.ts)_(need to find the commit where it was done)_  was added the way to get the modifier flags `const modifierFlags = getDeclarationModifierFlagsFromSymbol(p);` of a symbol and use these flags to create nodes. The [`3.7.*`](https://raw.githubusercontent.com/microsoft/TypeScript/9ba45fcaace07510ef259d4cda2bc5ec523cf6d1/src/compiler/checker.ts) handles only static modifier `const staticFlag = isStatic ? ModifierFlags.Static : 0;` - that's why `3.7.*` doesn't emit `async` modifier.

cc @DanielRosenwasser @weswigham @francesc79

**Comment by weswigham** [comment]
@a-tarasyuk it regressed in https://github.com/microsoft/TypeScript/pull/35731 probably, since prior to that we weren't pulling on "original" modifier flags from anywhere.

> Seems like this is fixed in the nightlies

[Looks broken in the nightlies to me](http://www.typescriptlang.org/v2/en/play?ts=next&useJavaScript=true#code/KYDwDg9gTgLgBAYwDYEMDOa4BVhpgKQGU4BvAKDksRSSQEE0BPAOwQAoBKUiq3qYGAFcozOAAUoEALYBLNMAB0-NBCQA3YGwCMHANw9KAXzIG46FgjgxcMTt168UAdxQz4MABZyFCGvSasnPq8xoZAA)
