### ISSUE TITLE
cannot use unique symbol as object key when generating declarations from JS

### ISSUE THREAD

**Issue by boneskull** [microsoft/TypeScript#37022]
**TypeScript Version:**  3.9.0-dev.20200225

Also tried in 3.8.2.

**Search Terms:** js symbol declaration ts9006

**Code**

See gist https://gist.github.com/boneskull/93484ca75cef49c11c69b1d416153bc4

Additionally, `a.d.ts` is created successfully:

```ts
export const kSymbol: unique symbol;
export type WithSymbol = {
    [kSymbol]: true;
};
```

I could not find a workaround (though there may be one!), since the `unique symbol` syntax is seemingly unavailable to JavaScript; it's not allowed in a `@type` docstring attribute. A workaround like this was shown in #36976.

**Expected behavior:**

`b.d.ts` is generated without error.

**Actual behavior:**

`kSymbol` is considered private, `b.d.ts` is not generated, and an error is emitted:

```
b.js:1:1 - error TS9006: Declaration emit for this file requires using private name 'kSymbol' from module '"/path/to/a"'. An explicit type annotation may unblock declaration emit.

1 import {kSymbol} from './a';
  ~~~~~~


Found 1 error.
```

Note that `kSymbol` is explicitly exported, and is not "private".

**Playground Link:** (playgrounds don't support generating declarations)

**Related Issues:** This may be related to #36976.

**Comment by boneskull** [comment]
FWIW, the "An explicit type annotation may unblock declaration emit." needs a better explanation.  An explicit type annotation _where_?

**Comment by tadhgmister** [comment]
What the type `import("./a").WithSymbol` is actually doing is copying the full type definition in place which is not valid for your case.  To illustrate this lets say you had a working type definition like `/** @typedef {{a: boolean}} WithA */` then you'd see the generated declaration for file `b` is this:

```ts
/**
 *
 * @param {import('./a').WithA} value
 */
declare function b(value: {
    a: boolean;
}): void;
```

So it isn't referring to the same type from file `a` but instead copying the whole type definition.  So if it copied the type definition with a computed property `kSymbol` that wouldn't be valid in the context of `b.d.ts` since typescript never emits imports as far as I know.

The correct behaviour is that at the end of the day `b.d.ts` should have an import in it:

```ts
import {WithSymbol} from "./a"
/**
 *
 * @param {WithSymbol} value
 */
declare function b(value: WithSymbol): void;
```

I'm not sure the best way to specify this as the emit, ideally we could have a jsdoc comment format that converts directly to an import in our `.d.ts` so we could put them up near our other imports, something like this:

```ts
/**
 * say we have a typedef that just imports another type we special case it:
 * @typedef {import("PATH").X} Y
 */

 // then we could emit an actual import in .d.ts (which would make the computed property thing valid)
import {X as Y} from "PATH";
```
