### ISSUE TITLE
`"foo" as "bar"` produces no errors

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#37032]
```ts
let x = "foo" as "bar"
```

**Expected**: "foo" is not convertible to "bar"
**Actual**: No error

Presumably we did this to allow some annoying cases around literal types? And this goes all the way back to 2.1 and 1.8, but was an error in 2.0!

**Comment by ajafff** [comment]
This has been discussed in #14156

**Comment by dgoldstein0** [comment]
(hm, it looks like that other issue is closed, does that mean this one should be too? or should we discuss this behavior further?)

While I did see some interesting examples in #14156 they didn't convince me that `"foo" as "bar"` and `1 as 2` and similar are necessary; e.g. the '/dev/null' as (string & { _pathBrand: any })` example could easily be changed to `'/dev/null' as string as (string & { _pathBrand: any });`

https://github.com/microsoft/TypeScript/issues/14156#issuecomment-299965629 is certainly a more interesting point, but I'm less convinced since I don't think I've ever see that in real code.  It's usually possible to structure code to be better understood by the type system (though Typescript has been making that less and less needed, which is awesome).
