### ISSUE TITLE
Type of variable x is number but still able to assign a return type of String type

### ISSUE THREAD

**Issue by dharmendrachouhan** [Microsoft/TypeScript#3707]
var x:number = 10;

function add(x, y) {
	return x + y;
}
x =  add('1', 2); // since type of x is number, this line should have given compilation error

**Comment by philipooo** [comment]
Actually the return type of add is of type `any` and the Typescript Sepcification says

> The Any type is a supertype of all types, and is assignable to and from all types.
> - http://www.typescriptlang.org/Content/TypeScript%20Language%20Specification.pdf

**Comment by dharmendrachouhan** [comment]
Thanks for the explanation,

but even if I make return type of add as number, it works. Please see below 


var x:number = 10;

function add(x, y):number {
return x + y;
}
x = add('1', 2); // since type of x is number, this line should have given compilation error

**Comment by philipooo** [comment]
Of course this works.

Look at this. This is what your code looks implicitly:
```
var x:number = 10;

function add(x:any, y:any):number {
return x + y;
}
x = add('1', 2);
```

As you see 
- you assign `'1'` to `x` which is legal because x is of type any. 
- you make an addition between `x`and `y` which is legal because you add any to any.
- you return a value of type `any` which is legal because you are able to assign `any ` to `number`

You have to change your code like this wo make the get an compilation error.
```
var x:number = 10;

function add(x:number, y:number):number {
return x + y;
}
x = add('1', 2);
```

Cheers

**Comment by RyanCavanaugh** [comment]
@philipooo's explanation is correct. Parameters without type annotations have type `any`.
