### ISSUE TITLE
Decorators don't get applied inside class definitions in assignment expressions

### ISSUE THREAD

**Issue by edenworky** [microsoft/TypeScript#37139]
**TypeScript Version:**  3.8.2

**Search Terms:**
decorators, assignment
**Expected behavior:**
`__decorate` should be called for both `Working` and `NotWorking`.
**Actual behavior:**
`__decorate` is called only for `Working`.

**Related Issues:**

**Code**
```ts
function methodDecorator = (proto, key, desc) => {
    console.log('methodDecorator called')
}

class Working {
    @methodDecorator myMethod() { console.log('myMethod called') }
}

let myVar = class NotWorking {
    @methodDecorator myMethod() { console.log('myMethod called')}
}

```

<details><summary><b>Output</b></summary>

```ts
"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
function methodDecorator() { }
(proto, key, desc) => {
    console.log('methodDecorator called');
};
class Working {
    myMethod() { console.log('myMethod called'); }
}
__decorate([
    methodDecorator
], Working.prototype, "myMethod", null);
let myVar = class NotWorking {
    myMethod() { console.log('myMethod called'); }
};

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/index.html#code/GYVwdgxgLglg9mABAWwKZQBZwCYBFURwBOAhlMYgLyIAUADkXOQDSIDWqAnq9qgM4QAlFQB8iAN4BYAFCI5iQmD5wANqgB0KuAHMaAcjSYc+QqXJEFJFWux7BMgL4yZEFST59EAdWJsYYbQkZeUQAAUMsPAJiMgpkTgBZdEiaYXEFBGU1TR19eKSjbEtrVFthJ2kKmTUoFE4ANRILald3TwA5Jh8iPwCg2Xlw5ONoszjE4exUiQylVQ0tXQMJwuKbOwqKoA)

**Comment by edenworky** [comment]
Of course there's no reason to declare a variable like `myVar`. My use case is passing constructor functions around in objects as shown below, but this seemed like the more general problem.

```typescript
let o: any = {}
o.myVar = class NotWorking ...
```

**Comment by rbuckton** [comment]
We don't currently support decorators on class expressions and haven't since we introduced the feature. The reason you aren't seeing an error in the playground link you posted is that the declaration of `methodDecorator` is invalid. Here's an updated playground link:

https://www.typescriptlang.org/play/index.html?experimentalDecorators=true#code/CYUwxgNghgTiAEYD2A7AzgF3gWxBgFksACLhIxQbkBc8UKAngNwCwAUO5FGmvAOrkA1gEsUAc3gBvdvFnwAArgJFSyClRg4GAWTyFgACgCUUxKjRIIIAHQQkYgwHJsOvUURQIV4I5MBfdgCONissFwA1WHgAXkRoHngAOSQMARgRcSkZOUU3EjJ1ci1dZUMTSTN0Sxs7B2dXUo8vEB8jIKCgA

![image](https://user-images.githubusercontent.com/3902892/78738883-d4320000-7907-11ea-90aa-eca65078faf3.png)

This isn't a bug, per se. We haven't added decorator support to class expressions yet as the proposal has been in flux and very different from our initial implementation for some time, so we have generally held off any major changes involving decorators.
