### ISSUE TITLE
Compiler not forcing extended Generic T when no properties set to base interface

### ISSUE THREAD

**Issue by nisimjoseph** [microsoft/TypeScript#37130]
**TypeScript Version:**  
3.7.x also exist in 3.8.x

**Search Terms:**
Extending generics, 
force interface on generic extends

**Code**
See in the playground section

**Expected behavior:**
The emit function gets an interface that is not extending the Generic interface restriction. it caused because the interface `EmitterData` I made mandatory to extend from is not forced because it has 0 (zero) properties in it.
as you can see from this link [here](https://www.typescriptlang.org/v2/en/play?#code/KYDwDg9gTgLgBDAnmYcCiA3YA7GAVZVAXjgGcYoBLbAcwG4AoB0SWOamYKAMwEMBjVGgC2lGJygARXjF5wA3kwC+TZuGjx+AG16lS6LLhFiJChnAtwwAVwBGWyvzjBRMADx5ps5yE7YAJvrG4lxeciS82IgAfAAUwIb4hABcmDhJKAA0cP4yvAD8yZ55AJTJGBCU-maWtXAA9PVwkhBkEMLAMAAW1DQAdOaWKipMHFx8gui+OP7BEmE1lrmyAIyFthAQWsCRjLXLvABMheRUtIwj-BDY5M6upiTYwADuBulzXLEljC4mXH2-dxoaYBD5SPJxABEnHIkOy8iU3yAA) the compiler not giving any error.

when I just add an optional property to the interface, like in this [link](https://www.typescriptlang.org/v2/en/play?ssl=4&ssc=1&pln=6&pc=1#code/KYDwDg9gTgLgBDAnmYcCiA3YA7GAVZVAXjgGcYoBLbAcwG4AoB0SWOamYKAMwEMBjVGgC2lGJygARXjF5wA3gzjK4AelVw8AC0qk4YXlF7D2eiNgA2iOKF3wYEON0ohNhAMr8qYePwjCwSgsuGygoaDgAdx1+LXZ4bAh4bmh+ahoEHT0OLj5BADolFShgXgATcys4AH0AfgAuACJGxgBfJmZwaF8LXlI9TBwYETEJBSLlMABXACMLSn4bURgAHjxpWRsQTmwygeWJDbkSXmxEAD4ACmAsXAIUesG7wgAaODKZXgb1z4BKeowEEoZXGKjBag0kkcpH8wBgOlohTB7XaTByPAEQm2ODKI3EXCOoJUH1kAEYGjMIBBgqdGGCSbwAEwNchUWhtJh+bDkJajEIkbDASLoW7DA5cS6-RjAcVQfIysQrNDY3Z4w6fK6NTjkRpveStKVAA) the compiler do notice it and rise me an error.

The final working example can be found [here](https://www.typescriptlang.org/v2/en/play?ssl=16&ssc=29&pln=16&pc=48#code/KYDwDg9gTgLgBDAnmYcCiA3YA7GAVZVAXjgGcYoBLbAcwG4AoB0SWOamYKAMwEMBjVGgC2lGJygARXjF5wA3gzjK4AelVw8AC0qk4YXlF7D2eiNgA2iOKF3wYEON0ohNhAMr8qYePwjCwSgsuGygoaDgAdx1+LXZ4bAh4bmh+ahoEHT0OLj5BADolFShgXgATcys4AH0AfgAuACJGxgBfJmZwaF8LXlI9TBwYETEJBSLlMABXACMLSn4bURgAHjxpWRsQTmwygeWJDbkSXmxEAD4ACmAsXAIUesG7wgAaODKZXgb1z4BKeowEEoZXGKjBag0kkcpH8wBgOlohTB7XaTByPAEQm2ODKI3EXCOWx2e3QBwJn1BKg+sgAjA0ZhAIMFTowwdTeAAmBrkKi0NpMPzYchLUYhEjYYCRdC3YZkqCXX6MYBy-LKsQrNDY3Z4w6fK6NTjkRpveStRVAA).

**Actual behavior:**
The compiler needs an error on any interface which is not extending the generic restriction even if that interface has zero properties.

**Playground Link:** 
The issue reproduced [here](https://www.typescriptlang.org/v2/en/play?#code/KYDwDg9gTgLgBDAnmYcCiA3YA7GAVZVAXjgGcYoBLbAcwG4AoB0SWOamYKAMwEMBjVGgC2lGJygARXjF5wA3kwC+TZuGjx+AG16lS6LLhFiJChnAtwwAVwBGWyvzjBRMADx5ps5yE7YAJvrG4lxeciS82IgAfAAUwIb4hABcmDhJKAA0cP4yvAD8yZ55AJTJGBCU-maWtXAA9PVwkhBkEMLAMAAW1DQAdOaWKipMHFx8gui+OP7BEmE1lrmyAIyFthAQWsCRjLXLvABMheRUtIwj-BDY5M6upiTYwADuBulzXLEljC4mXH2-dxoaYBD5SPJxABEnHIkOy8iU3yAA).

**Related Issues:**

**Comment by jcalz** [comment]
I think the template wants to see the code in the text of the question, so please edit that in when you get a chance.

---

This is working as intended.  TypeScript's type system is [structural](https://github.com/Microsoft/TypeScript/wiki/FAQ#what-is-structural-typing), not nominal.  See the [Type Compatibility section of the TypeScript Handbook](http://www.typescriptlang.org/docs/handbook/type-compatibility.html#introduction).

You don't have to *declare* that a type `implements` or `extends` some other type for it to be true:

```ts
interface Foo {
    x: string
}

interface Bar {
    x: string,
    y: number
}

function baz<T extends Foo>() { }
baz<Bar>(); // okay
```

The last line above is not an error; `Bar extends Foo` because of the *structure* of `Foo` and `Bar` and not because of any explicit declaration.


That means that your `EmitterData` interface is completely equivalent to the empty object type `{}`, and any non-`null` and non-`undefined` type will be seen by the compiler as extending it, including `ExtendEmitterData`.  For this reason it's [often a mistake](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-all-types-assignable-to-empty-interfaces) to declare empty interfaces.

If you want to require that a type extend a particular interface, it would be best if there were some useful properties or methods that it has to have.  Otherwise you will be forced to try to simulate nominal typing by adding phantom/useless properties like `_` as you've done (see [the FAQ](https://github.com/Microsoft/TypeScript/wiki/FAQ#how-do-i-prevent-two-types-from-being-structurally-compatible))

In any case, all of this behavior is completely intended and not indicative of any sort of bug in the TypeScript compiler.  Good luck!

**Comment by nisimjoseph** [comment]
Got it, it makes sense. Thank you for the detailed explanation.
