### ISSUE TITLE
Support Block-level function declarations

### ISSUE THREAD

**Issue by rbuckton** [microsoft/TypeScript#3714]
From the kangax compatibility table ([related test](http://kangax.github.io/compat-table/es6/#block-level_function_declaration)):

> [14](http://kangax.github.io/compat-table/es6/index.html#block-level-function-note) Note that prior to ES6, it was [recommended](http://wiki.ecmascript.org/doku.php?id=conventions:no_non_standard_strict_decls) that ES5 implementations forbid block-level declarations in strict mode.

In ES6, block-level function declarations have block scoping in strict mode. Currently the following is a compiler error in TypeScript:

``` ts
"use strict";
function f() { // error TS2393: Duplicate function implementation.
  return 1;
}

{
  function f() { // error TS2393: Duplicate function implementation.
    return 2;
  }
  console.log(f() === 2);
}

console.log(f() === 1);
```

We should consider the following changes:
1. Allow the above in ES6 when in strict mode, with the function declaration `f` being block-scoped with respect to name resolution.
2. For ES5 strict-mode, allow the above with the following emit:

``` ts
"use strict";
function f() {
  return 1;
}

{
  function f_1() {
    return 2;
  }
  console.log(f_1() === 2);
}

console.log(f() === 1);
```

**Comment by falsandtru** [comment]
:+1:

**Comment by DanielRosenwasser** [comment]
I think this should be marked as a bug, not as a suggestion.

**Comment by falsandtru** [comment]
> \2. For ES5 strict-mode, allow the above with the following emit:

This is a breaking change for es5 because it changes a function name to different name. Some library analyzes a function name. Perhaps, AngularJS will not work.

**Comment by weswigham** [comment]
The emit for this should not _actually_ have a function declaration within a block in the emit, as in @rbuckton's example emit above, since this would (strictly, without browser-dependent language additions) be a `SyntaxError` under strict mode in ES5 runtimes. I believe this is why babel unconditionally rewrites it as a var statement and a function expression, and hoists the assignment to the top of the block.

Block scoped functions under non-strict mode on ES6 are where things actually get really confusing [(and is where the web compat appendix can come into play)](https://tc39.github.io/ecma262/#sec-block-level-function-declarations-web-legacy-compatibility-semantics) - you need to give the function both a `let` and `var` binding so that you can both capture the function as a block scoped variable and access it outside of the block as a hoisted variable (though according to the spec, only if you see an identifier reference indicating the need to do so!). Fun.

**Comment by falsandtru** [comment]
example:

```ts
"use strict";
var f_1 = function f() {
  return 1;
}

{
  var f_2 = function f() {
    return 2;
  }
  console.log(f_2() === 2);
}

console.log(f_1() === 1);
```

This code will work on emulated ie8.

**Comment by alexlur** [comment]
@mhegazy Why is the `bug` label removed?

**Comment by mhegazy** [comment]
this should already be addressed by https://github.com/Microsoft/TypeScript/pull/8014

**Comment by mhegazy** [comment]
> Why is the bug label removed?

it is a design change request. the behavior today matches the original design.

**Comment by RyanCavanaugh** [comment]
Doesn't seem to be any customer demand for this

**Comment by falsandtru** [comment]
I don't think it can't be the reason to close the issue. At least all incompatibility with ECMAScript should be logged as open issues.

**Comment by RyanCavanaugh** [comment]
We don't intend to manage the repo that way.
