### ISSUE TITLE
Node JS API

### ISSUE THREAD

**Issue by Subash** [microsoft/TypeScript#372]
Is there an api that can be `require` ed from node to compile file. eg

``` javascript
var ts = require('typescript');
ts.compile(filePath, {options}, function(err, js) {
 //etc
})
```

**Comment by csnover** [comment]
Just to verify, is there any LanguageServiceHost implementation other than LanguageServiceShimHostAdapter?

**Comment by Arnavion** [comment]
@csnover You're meant to give your own implementation of LanguageServiceHost to ts.createLanguageService() , since its implementation (get filenames, get contents of files, etc.) will depend on the hosting application. If you want an example, see class TypeScriptLS in src/harness/harnessLanguageService.ts (that implements the shim interface) and how it's converted via the Adapter to the new interface.
