### ISSUE TITLE
Could we make `strict: true` the default?

### ISSUE THREAD

**Issue by phryneas** [microsoft/TypeScript#37351]
## Search Terms

strict, true, default, tsconfig

## Suggestion

Make `strict: true` the default in future TS versions.

## Use Cases

We're getting quite a number of bug reports because our library typings have a special handling of `undefined` types and method parameters - and people are actively unaware that they have `strictNullChecks` set to `false`.

Given that the `strict` option was added for backwards compatibility in 2.3 (back in April 2017), and people are still missing it today (codesandbox had not added `strict` to their TS sandboxes until recently due to oversight, also a lot of people seem to be copy-pasting `tsconfig.json` files instead of running `tsc --init`), would it be worth to consider changing the default to `true` in some future versions?

Having users once specify `strict: false` in their `tsconfig.json` on a TS version upgrade (that oftentimes bring breaking changes anyways) seems like a much lower risk than loads of people running without `strict` because they just don't know it better.

The last discussion on this (#24773) is almost two years old, so I hope that by now, maybe you'd reconsider :)

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
We yell at each other about this on the first Wednesday of every month just to make sure we still believe it, but yes, we still don't believe this is the right thing to do.

**Comment by phryneas** [comment]
Sooo... who in the office needs to be sent a BIG pack of sweets next tuesday so they change their opinion? :D

No, seriously. I understand the arguments you brought up in the last post, but I'm also seeing these people that miss out on essentially 80% of the great experience TypeScript can be, without being aware of it. 

Has anyone had any creative ideas on how to maybe at least detect new projects and educate new users on what they're missing out on? 
Even something seriously weird like detecting the project is in a git repo that's younger than 10 days and print a warning for a day or so might somehow help... And yes, I think myself that that's a bad idea, but I can't really come up with something better :disappointed:

**Comment by AnyhowStep** [comment]
4.0 breaking change, gogogo

**Comment by RyanCavanaugh** [comment]
There is certainly some upside for people not using `tsc --init`, but the downside just sucks very badly. What does this look like from an end-user's perspective in the cases where they *didn't* want `strict` on?

 * You upgrade to TypeScript 8.0
 * Your project gets A BILLION errors
 * You downgrade because you don't have time for this kind of nonsense, clearly this TS release is just broken
 * You try again later with TypeScript 8.1, maybe the TS team shipped something that worked this time
 * The first and the last error message both say "HEY WE TURNED ON STRICT NOW, GO TURN IT OFF IF YOU'RE GETTING A BILLION ERRORS RN?"
 * You go find however many config files you need to try to update them
 * Wait, there's no config file, it's a commandline build script?
 * Who owns the build script? Someone wrote a wacky perl thing and it's not clear how to update it
 * Actually it's some webpack thing now, where are the options even kept in this repo?
 * Bob wrote that webpack config and no one knows how it works, maybe look for eval calls
 * Never mind, TypeScript 7.9 was good enough

Or maybe

 * Actually the config is right here
 * Let me turn `strict` off
 * Why did they waste my time with this? Anyone who wanted `strict` could have just set it; this is useless and a hostile experience during the trying time of doing a tooling upgrade

The upgrade path here has to look like something that isn't a useless wall of pain to people who intentionally have `strict` off via its default. *Maybe* we start with a warning (note: We would have to *introduce the concept of a build warning* and then argue about what commandline exit codes mean, forever, if we did this) when `strict` isn't *explicitly* set in the config file, wait a year so that approximately everyone has an explicit setting one way or the other... at which point the concept of a default barely exists per se?

So it's roughly equivalent to "force everyone to explicitly set `strict` on or off", which doesn't really *solve* the problem of "what is the default" except to *newly warn people who already didn't set the flag that is supposed to control almost all new warnings*. 🤷‍♂️!

**Comment by kitsonk** [comment]
We turned strict on by default in Deno recently.  It is the most controversial thing we have done, and we don't even have a stable release yet.  Not only did we break a lot of code, we have lots of complaints about `--noImplicitAny`.  We are holding firm, but it is a small eco-system where we want to get off to a good start, not an eco-system with billions and billions of LOC that would break.

Sadly, this is like `"use strict";` in JavaScript.  It is really hard to break things, even if they are super super good ideas.

**Comment by phryneas** [comment]
My experience is that almost every TypeScript version update broke something in some way -  either types themselves of some surrounding tooling like `prettier` or `eslint` due to new syntax. 
So personally I cannot imagine someone actually updating TypeScript in a longer existing project without actually reading the release notes.

Also I believe that you are maybe painting the tooling issues a *little* bit too dark here. At least with webpack it should either be ts-loader or awesome-ts-loader, and both honor the `tsconfig.json` by default. Sure, people sometimes have weird build setups. But I firmly believe that they know about that and won't blame their own f*ckup on TS itself.

And in the worst case: do these projects that have `strict: false` actually gain from upgrading their TS version? Do you expect new features to actually be used in these projects if you don't even trust their developers be able to update their tsconfig?

In the end, I'd consider the "mild inconvenience" the other way round: updating a config file is a mild inconvenience for me, while a person having actual bugs in their project that they could otherwise being aware of (null checks etc) has a real problem.

In the end, it's your decision. 
But I'd love if you could at least talk about it once more when you consider releasing the next major. 
People *expect* breaking changes at major versions, so that's the maximum number of people that will read the ChangeLog you can get ;)

**Comment by MKRhere** [comment]
Fortunately Deno has the advantage of being younger and not stable yet (safer to break). I see how strict by default would break a lot of people's workflow and the anxiety caused in the aftermath. If we ever want to move to strict by default for all TypeScript users, I guess we'd start by warning users to set an explicit `strict: false` if required for a couple of majors at least.

**Comment by AviVahl** [comment]
After several years using TypeScript, I'm very much for the strict-as-possible-by-default-v4.0 suggestion.

People don't just upgrade their typescript package out of the blue. I personally read the release notes first to see what changed. One usually also has to upgrade several `@types` packages to be compatible with the new ts version. It a process, and many errors don't necessarily get you scared. They usually cause one another, so fixing one fixes many.

4.0, because those `"^3.x.x"` version requests will not auto-upgrade with semver in place (even though typescript doesn't respect semver).
