### ISSUE TITLE
Conditional signatures of generic methods.

### ISSUE THREAD

**Issue by d180cf** [Microsoft/TypeScript#3742]
Let's say I want to write a `Promise<T>`-like generic class with a method that makes sense only for certain `T`:

```ts
class PromiseLike<T> {
  then<U>(mapping: (value: T) => U): Promise<U> {
    /*...*/
  }

  /** if T extends U[], then the signature of this method is
      take<U>(index: number): Promise<U> */
  take(index: number) {
    return this.then(v => {
      if (index < v.length)
        return v[index];
      throw new RangeError(`Index: ${index}, array length: ${v.length}.`);
  }
}
```

As you see, `.take` is a small wrapper around `.then` which makes sense if `T` is an array type:

```ts
/** p is resolved to "B" */
const p = PromiseLike.resolve(["A", 'B", "C"]).take(1);
```

Unfortunately, this doesn't work because tsc tries to verify the `.take` method at the moment of its declaration and says that `T` doesn't have to be an array type in the general case and hence `v` doesn't have to have the `.length` property. A workaround would be `<any>v` which isn't nice because all type safety is gone.

It would be nice to somehow tell tsc that `.take` can be invoked only if `T extends any[]`.

**Comment by danquirk** [comment]
Are there other languages with this sort of support?

**Comment by d180cf** [comment]
Does C++ have this feature? It has pretty advanced templates.

I'm not an expert in writing compilers, so my question might be naive: why is this feature hard to implement? It seems fairly trivial to just check whether an inferred type `T` makes sense at each use of the method. Currently tsc seems to check whether the method's implementation makes sense for every possible `T` (for optimisation purposes, I guess) and it only needs to make one change in this logic: if the method doesn't make sense for any `T`, mark this method somehow and then check whether it makes sense for every use in the code:

```ts
class Promise<T> {
  take(index: number) {
    // tsc defers type checking of take<T> because not every T has .length
    return this.then(a => index < a.length ? a[index] : null);
  }
}

Promise.resolve([1, 2, 3]).take(1); // ok, T = number[] has .length
Promise.resolve(null).take(1); // error: T = void, doesn't have .length
```

**Comment by RyanCavanaugh** [comment]
What you're describing is something like C++-style template instantiation, which is a very different strategy (note that they use different names; templates are *not* generics). That's a plausible strategy when every compilation has the source code (or equivalent) of the entire program, but that's not a luxury many other languages have.

Let's say you wrote this class:
```ts
class Foo<T> {
	method(x: T): string {
		let j = x.foo;
		let k = x.bar(j);
		let y = j + k;
		return y.substr(2);
	}
}
```
`method` should be available when:
 * `T` has a `foo` property
 * `T` has a `bar` property
 * `T`'s `bar` property can be invoked with a single argument with the type of `T.foo`
 * `T.foo` and the return type of `T.bar` when invoked with the type of `T.foo`, when added together with `+` is a legal operation (note that it might produce `string` or `number` or be illegal)
 * `T.foo` and the return type of `T.bar` when invoked with the type of `T.foo`, when added together with `+` produce an object that has a `substr` property
 * `T.foo` and the return type of `T.bar` when invoked with the type of `T.foo`, when added together with `+` produce an object that has a `substr` property that can be invoked with a single `number` argument
 * `T.foo` and the return type of `T.bar` when invoked with the type of `T.foo`, when added together with `+` produce an object that has a `substr` property that can be invoked with a single `number` argument that produces a `string`

Let's not even think of the case where you wrote:
```ts
class Foo<T> {
	method<U>(x: T, z: U) {
		let j = x.foo;
		let k = z.bar(j);
		let y = j + k;
		return y.substr(0);
	}
}
```
Now `method` is available when... what?

Then imagine you're trying to produce a declaration file (`.d.ts`) for `Promise<T>` because you want separate compilation. It's simply impossible to produce a file that describes those constraints without essentially rewriting all the source code in place.

Even given the source code, it would be incredibly slow to do this kind of computation every time a generic type is instantiated. Note that C++'s template system is Turing-complete -- a good design principle we have is "try to avoid embedding programming languages into our type system" :wink:

**Comment by d180cf** [comment]
It seems this problem can be easily solved with typed `this` and the bind `::` operator:

```ts
function take<T>(this: Promise<T[]>, index: number): Promise<T> {
    return this.then(results => results[i]);
}

Promise.resolve(["A", "B", "C"])::take(1).then(letter => {
    letter == "B";
});
```

Here `take` acts as a sort of a partial class or class extension.

**Comment by d180cf** [comment]
Hence, @danquirk, I'm suggesting to change the tags to "In Scope" and "Too Easy" :)
