### ISSUE TITLE
ASM.js compilation target.

### ISSUE THREAD

**Issue by electricessence** [microsoft/TypeScript#375]
Original thread: https://typescript.codeplex.com/discussions/438243
Also: http://typescript.codeplex.com/workitem/852

Not sure how this should be approached, but I have some suggestions and for some of us that could really use this right about now, we may need to start another repo/branch to get something working.

1) Ideally, it's just another target.  You set --target asm and it just works if the code doesn't break too many rules.
2) Unless someone already has done this (and can paste a link here), we can start another transpiler that takes standard TSC output and convert it to asm format.  If that goes well, I don't see why the TSC couldn't import that code.

**Comment by jslegers** [comment]
Personally, I don't see much of a benefit of using TypeScript instead of JavaScript. Especially now that the ES6 standard also added class-based object-oriented programming to the language, all you'd really get from adopting TypeScript today would be the addition of static typing... and interfaces. Besides making your code look more like eg. Java code, I really don't see the benefit at all... except when using static typing to optimize the JavaScript code it produces... which is where asm.js comes in.

In environments where high performance is essential (eg. 3D rendering in the browser for browser games or GIS web apps), the current approach is to write the core code (that does the heavy lifting) in C/C++ (compiled to asm.js) and everything else in JavaScript. That means you need a really good understanding of both JavaScript (which I do) and C/C++ (which I don't) to be able to write proper code or maintain existing code for such apps.

How great would it be to be able to use one - TypeScript - codebase for such projects and compile to asm where possible and to regular JavaScript where not possible? Or to put it differently : how great would it be for a JavaScript programmer to be able to program in highly readable superset of JavaScript and have it compiled - where possible - to a highly optimized subset of JavaScript?

It seems like a win-win for everyone, really, especially if you leave it optional whether or not to compile to asm.js for developers who don't work in high performance environments and prefer readability to performance.

IMO, compilation of (a subset of) TypeScript to asm.js would be **major** improvement over TypeScript as it exists today. For me, it would totally be a game changer and make the difference between supporting and not supporting the adoptation of TypeScript at the company I work for...

**Comment by jslegers** [comment]
Those also interested in converting staticly typed variations of JavaScript to asm.js, WebAssembly or C might want to take a look at [ThinScript](https://github.com/evanw/thinscript) or [TurboScript](https://github.com/01alchemist/TurboScript). 

ThinScript compiles to JavaScript, WebAssembly, and C. TurboScript compiles only to JavaScript and WebAssembly.

Both languages have been inspired by TypeScript.

I'd like to thank @RReverser for pointing me in the direction of these two languages.
