### ISSUE TITLE
Import specifiers give inappropriate completion options on the current property name

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#3756]
```TypeScript
declare module "M1" {
    export var ABC;
    export var DEF;
}

declare module "M2" {
    import { ABC/**/ } from "M1"
}
```

Request completion on `ABC`. Even though there's no way we could be typing out `DEF`, we're given that option.

![trampledunderimport](https://cloud.githubusercontent.com/assets/972891/8534562/63847f96-23f2-11e5-940d-a965ce74dffa.gif)

This **isn't** the way it works in an object binding pattern or contextually typed object literal expression:

![notrampleinobject](https://cloud.githubusercontent.com/assets/972891/8534641/0b75789a-23f3-11e5-9ea2-230571e0546f.gif)

**Comment by danquirk** [comment]
I assume your code snippet is meant to match the gifs (DEF not ABCDE)

**Comment by DanielRosenwasser** [comment]
@danquirk yes I corrected it

**Comment by mhegazy** [comment]
The issue is that the filtering logic removes the entry from the completion list, leaving only one entry on the list.

The filtering logic needs to keep the entry if the cursor is at the end of it. we do this for object literal completion, this way you make sure you have the current entry on the list, so "tab" would not overwrite it.

**Comment by mhegazy** [comment]
you probally need to do the same for destructuring, and for jsx elements

**Comment by mhegazy** [comment]
here is the relevant section: https://github.com/Microsoft/TypeScript/blob/master/src/services/services.ts#L3458-L3461
