### ISSUE TITLE
Incorrect unnecessary await detection

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#37657]
await expressions are obviously expected to show their effects when their results will never be captured.

**TypeScript Version:**  3.7.x-dev.20200327

**Search Terms:**

**Code**

```ts
(async function () {
    console.log(1);
    await 0;
    void await 0;
    console.log(3);
}())
console.log(2);
```

**Expected behavior:**
pass
**Actual behavior:**
'await' has no effect on the type of this expression.(80007)
**Playground Link:** https://www.typescriptlang.org/play/index.html?ts=3.9.0-dev.20200327#code/BQQwzgngdgxgBAMwK6wC4EsD2U7AJRwDeAUHGXDNmJgDYCmAdDZgObACMeA3KeSAO4h0qOAAYe5OADdM6ACZwBQkeN5lKUavSatgAZm7EAvvjzENWxszYAmbkA

**Related Issues:**

**Comment by nmain** [comment]
TS80007 is an advisory and doesn't even give a red squiggly.  You can just ignore it when you're being really clever with async.  The message _is_ accurate; it says the type of `await 0` and the type of `0` are the same, not that the containing function will have no observably different behavior due to their presence or absense.

**Comment by falsandtru** [comment]
Do you understand why await is used in the code?

**Comment by falsandtru** [comment]
I filed this issue because that info is listed in the issue panel of VSCode, but now not listed. Maybe something was wrong or fixed (anyway the detection is unreasonable).

**Comment by nmain** [comment]
> Do you understand why await is used in the code?

You're being overly clever with async.  It's not interesting code, it's not realistic code, and the error isn't even warning you of what you claim it's warning you of.

Without running it, I can tell you that your example will print 1 2 3, and that it would print 1 3 2 without the await, and that if something like this was in my code, I would immediately refactor it to be less weird.

**Comment by falsandtru** [comment]
Looks like some official tests are overly clever.

https://github.com/microsoft/TypeScript/blob/master/tests/cases/compiler/es2017basicAsync.ts
https://github.com/microsoft/TypeScript/blob/master/tests/cases/compiler/asyncAwaitWithCapturedBlockScopeVar.ts

**Comment by RyanCavanaugh** [comment]
Suggestions are suggestions; they are precisely suggestions because we know they don't have 100.0% accuracy relative to what you might be intended to do. VS Code shouldn't be showing them in an "issues" panel in a way that isn't filterable; please raise a bug about that (probably in their repo?) if that's happening.

**Comment by jeffmcmahan** [comment]
> The message is accurate; it says the type of await 0 and the type of 0 are the same, not that the containing function will have no observably different behavior due to their presence or absense.

Hm. Might the meaning be clearer if we borrow from @nmain here and say: 

```
'await' will not alter on the value of this expression
```

It may be that "has no effect" reads like an assurance that `await` can be removed *without effect.*
