### ISSUE TITLE
Suggestion: Support for Obj<T>

### ISSUE THREAD

**Issue by nojvek** [microsoft/TypeScript#37695]
## Search Terms

`object with typed values`, `object map syntax like Array<T>`, `object map syntax like Map<K, V>`

## Suggestion

Typescript makes it very easy to write typed arrays e.g

`const strArray: Array<string> = ["1", "2", "3"]`

Writing equivalent object type has somewhat harder to remember syntax

`const strObj: {[key: string]: string} = {hello: "world", foo: "bar"}`

Would be nice to have a mapped type, like Partial, Omit, e.t.c in the default library

`type Obj<T> = {[key: string]: T}`

99% of the time, the key in javascript is usually defined as a string. It's much easier to write `Obj<T>`  like `Array<T>`.

I tend to write a ton of `{[key: string]: T}` types and after a while it gets cumbersome, I have to google it every now and then.  A shorter version as part of lib.d.ts would be a god send. It would be easier to write and remember.

It would be pretty easy to add too (If the TS team agrees, I can make a quick PR). 

I know there is `Record<string, T>`, but that type hasn't made much sense to me, why not just `Record<T>` ?

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by jgbpercy** [comment]
The main purpose for which I use `Record<K, T>` is to provide some type K that _extends_ string (i.e. a string literal union) for the first type argument. The object must then have a key for each member of K:
```
const thinger: Record<'blah' | 'dodar', number> = {
  blah: 1, // if I omit this line or the next it's an error
  dodar: 2,
};
```
In this example, TS will helpfully yell at me if I don't provide blah or dodar properties.

The type `Record<string, SomeType>` indicates to TS that there is a `SomeType` for every `string` key, so I believe it behaves much like (or identically) to `{ [key: string]: SomeType }`, i.e. you could equally define `Obj<T> = Record<string, T>`.

With `Record<string, T>` you don't get the useful check that you get when providing a string literal union, of course, because that would be impossible.

**Comment by RyanCavanaugh** [comment]
We're not adding new top-level type aliases unless we absolutely, absolutely must. Anyone in userland can write `type WhateverTheyWantToCallIt<T> = Record<string, T>;`
