### ISSUE TITLE
Casts should preserve nullness

### ISSUE THREAD

**Issue by rubenlg** [microsoft/TypeScript#37690]
## Search Terms

- cast preserve nullness
- cast hides null
- cast nullness
- cast propagate null
- assertion preserve nullness

## Suggestion

Make casts propagate nullness (`null|undefined`) without having to explicitly mention it. Of course behind a compiler flag, so projects can be migrated to this stricter form at their own pace, if they wish so.

### Corner cases:

- Casting `undefined` to `X`. This won't work today already.
- Casting `unknown` to `X`. I'd keep the rule and make it `X|undefined|null`.
- Casting `void` to `X`. I'd keep the rule and make it `X|undefined`.

## Use Cases

The reason we have nullness options in TypeScript is because developers often forget or they don't realize that something might be nullable, and we need a reminder from the compiler.
More often than not, casts that drop nullness do so by mistake. The intent is often to downcast (like the querySelector example below), or cast a defined object to a partially incompatible type, and when that is the intent, we accidentally drop `null` or `undefined` so static analysis won't help us.

## Examples

```typescript
const foo = document.querySelector('input.my-class') as HTMLInputElement;
console.log(foo.value); // Error, foo may be null

const bar = document.querySelector('input.my-class')! as HTMLInputElement;
console.log(bar.value); // Ok, because nullness was explicitly dropped before casting. 

const baz = document.documentElement;
console.log(baz.nodeValue); // Ok, because documentElement is non nullable.
```

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code (assuming it's introduced behind a flag).
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals]. Specifically addresses the first rule (Statically identify constructs that are likely to be errors).

**Comment by RyanCavanaugh** [comment]
I don't think this would be palatable even behind a flag. Type assertions are otherwise extremely straightforward in their behavior, and it's not really clear why `null` and `undefined` should get special treatment here - one could equally argue that asserting `string | number` to `"foo"` should produce `"foo" | number`.

**Comment by rubenlg** [comment]
I understand that it might make the compiler less elegant, but the first goal of Typescript is to _identify constructs that are likely to be errors_, and casts that drop `null` or `undefined`, are quite often errors.

The [following query](https://github.com/search?q=querySelector+%22as+HTMLElement%22&type=Code) on github shows 15k results that are most likely bugs. I doubt most of these were dropping `null` on purpose when downcasting.

Do you think there are more elegant ways to catch those errors? Is this something that a linter should be doing instead of the compiler?

**Comment by RyanCavanaugh** [comment]
I disagree with your assessment of what qualifies as a bug, I think. Many if not most web pages are built with JS where an implied constraint is that they are only run in the context of pages with some element matching a selector or ID.

One could draw the opposite conclusion from this data - all these invocations of `querySelector` followed by unguarded property/method access in extant codebases shows that devs are writing these queries in places where they know from other means (either environmental, or otherwise construction of their program) that there's no chance for a `null` result.

The supporting data would look like this:
```ts
const el = document.querySelector("??") as HTMLDivElement;
if (el) {
 // do something with el
} else {
 // do something else
}
```
Here (after the `if`), `el` is in a "dangerous" state where it's clear the dev thought it might be missing, but TS think it's not. I don't see much code like that, I think because it's a fairly rare to query the DOM for stuff that might not exist *and also* fail to recognize that you're doing that.

**Comment by rubenlg** [comment]
I agree these results I pulled from GitHub might not be bugs, but it's certainly brittle code. If the HTML is updated, the TypeScript code might break in ways that will be hard to debug (depending on whether the pointer is de-referenced right away, or stored somewhere and used in another task).

FTR, and since there is at least a +1 in the request, leaving here a utility that can be used in absence of compiler support:
```
function safeCast<T extends Element>(input: Element | undefined): T|undefined;
function safeCast<T extends Element>(input: Element | null): T | null;
function safeCast<T extends Element>(input: Element | undefined | null): T | undefined | null {
    return input as T | undefined | null;
}

// Element | null
const x = document.querySelector('foo');

// HTMLButtonElement | null
const y = safeCast<HTMLButtonElement>(document.querySelector('#my-button'));
```

With partial type argument inference it could be made even more generic, but for DOM queries, this is probably good enough.

Closing the issue to reduce noise, since there isn't much interest from the community.
