### ISSUE TITLE
TS2708: Cannot use namespace 'LazyCookie' as a value.

### ISSUE THREAD

**Issue by bluelovers** [microsoft/TypeScript#37722]
**TypeScript Version:**  typescript@3.9.0-dev.20200330

**Search Terms:**

**Code**

LazyCookie in jsdom-extra
https://github.com/bluelovers/jsdom-extra/blob/1ffaa074fd08407ffc1ab8beb135101473005397/lib/cookies.ts#L5-L17

LazyCookie in lazy-cookies
https://github.com/bluelovers/ws-rest/blob/1250d03b98cbe9305f21afc9664e077a374e8135/packages/lazy-cookies/index.ts#L10

```ts
import { LazyCookie, LazyCookieJar } from 'jsdom-extra/lib/cookies';
import { LazyCookie as LazyCookie2 } from 'lazy-cookies';

let a;

// @ts-ignore
console.log(a instanceof LazyCookie)

// @ts-ignore
console.log(a instanceof LazyCookie2)

```

**Expected behavior:**

```ts
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const cookies_1 = require("jsdom-extra/lib/cookies");
const lazy_cookies_1 = require("lazy-cookies");
let a;
// @ts-ignore
console.log(a instanceof cookies_1.LazyCookie);
// @ts-ignore
console.log(a instanceof lazy_cookies_1.LazyCookie);
```

**Actual behavior:**

> TS2708: Cannot use namespace 'LazyCookie' as a value.

> ReferenceError: LazyCookie is not defined

```ts
Object.defineProperty(exports, "__esModule", { value: true });
const lazy_cookies_1 = require("lazy-cookies");
let a;
// @ts-ignore
console.log(a instanceof LazyCookie);
// @ts-ignore
console.log(a instanceof lazy_cookies_1.LazyCookie);
```

**Playground Link:** 

https://www.typescriptlang.org/v2/en/play?module=1#code/JYWwDg9gTgLgBAbzgGQIYC8CeBhCEDWwApgDQoY56FEBSqUcAvnAGZQQhwDkAVgM4ATDgFoiADxhRUAegA2wAEbSAxlWJ8uAbgBQoSLETksuAsTio+RyqaIAmJq3acusisNU2NO7bKLxU3tLScAACMHzCwADmAHbQRNqqMXwQvgB0shBRABSocMDJMKgxykQQLFYm1ACU2tpBoeGRsfGJEMmpRBlZufmFxaXllWp2tdpAA

**Related Issues:**

**Comment by rbuckton** [comment]
I think `jsdom-extra` is attempting to augment the `LazyCookie` namespace and re-export it, but it is doing so incorrectly. We should be reporting an error due to the conflicting definitions for `LazyCookie` in that library:

```ts
// imports a class which is both a value and a type
import { LazyCookie } from "lazy-cookies"; 

// re-exports the class
export { LazyCookie };

// this should be an error as you can't augment the class this way...
export namespace LazyCookie {
  interface Properties { ... }
}
```

In addition, it seems like we see the definition of `LazyCookie` from `jsdom-extra` and interpret it as an "uninstantiated namespace" (i.e., an ambient namespace that only contains types), which does not give it a "value" meaning. Since it doesn't have a "value" meaning, it can't become "referenced", so we don't emit it.

There are two bugs here for the compiler, and one in `jsdom-extra`:
1. `typescript` - You should not be able to have both an `import` and a `namespace` of the same name. We generally allow this when the two declarations do not share a meaning (i.e., one can be a "value" and the other can be a "type"), but a class is both a "value" and a "type" so this shouldn't have been allowed.
2. `typescript` - We may need to reconsider how we handle the above import (which should be considered an error) even when `--skipLibCheck` is enabled.
3. `jsdom-extra` - Needs to update _cookies.ts_ to the correct approach for module augmentation (as they will be broken if we fix (1), above):
   ```ts
   import { LazyCookie, ... } from "lazy-cookies";
   ...
   export { LazyCookie };
   
   // correct way to augment `LazyCookie` 
   declare module "lazy-cookies" {
     namespace LazyCookie {
       interface Properties { ... }
     }
   }
   ```

**Comment by RyanCavanaugh** [comment]
Given that there's at least one external problem here, I'm calling this external. The other issues can be looked at if someone else runs into them.
