### ISSUE TITLE
[Bug] (for of) loop doesn't treat inline array declaration as const

### ISSUE THREAD

**Issue by bogdan** [microsoft/TypeScript#37732]
**TypeScript Version:**  3.8.3

**Search Terms:**

* constant
* array
* iterator loop

**Code**

```ts
type Key = 'a' | 'b' | 'c';

const a: { [key in Key]?: number } = {};

for (const i of ['a', 'b']) {
  console.log(a[i])
}
```

**Expected behavior:**

No compile error

**Actual behavior:**

```
Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{ a?: number; b?: number; }'.
  No index signature with a parameter of type 'string' was found on type '{ a?: number; b?: number; }'.
```

**Playground Link:** 
https://www.typescriptlang.org/play/#code/C4TwDgpgBA0hJQLxQOQEMVQD6oEaZxQGMUBuAWACgqiB7AOwGdgo0AuKAbygG0BreFACW9WPAC6Afg70ArgFtcEAE5QAvki5qK1SgDNaqgBR0mLIVFp7e6FABo8KcQEouVKFFONaAGwgA6H1oAcyM0HiEXKjUqIA

The issue is comming from they type of `i` determined as `string` while it could be `'a' | 'b'` for more strict typing.

Can be solved by manually declaring inline array as const:

```
for (const i of ['a', 'b'] as const) {
```

**Comment by RyanCavanaugh** [comment]
I'm not sure that this is obvious. If you had written
```ts
for (const i of ['a', 'b']) {
  return i;
}
```
it's not apparent that the inferred return type of the function should be `"a" | "b"` instead of the current `string`.

Right now there's a consistent rule that if you want the literal types from an array with no other type context, use `as const`, and if you don't, don't. Making that less consistent doesn't seem like an improvement.
