### ISSUE TITLE
--noEmit hides 'declaration' related errors

### ISSUE THREAD

**Issue by Martaver** [microsoft/TypeScript#37769]
**TypeScript Version:**  3.8.3

**Search Terms:**
noEmit, declaration

**Code**

```ts
export function test() {
  return class MyTestClass {
    private foo = 0;
  };
}
```

**Expected behavior:**
My tsconfig contains `compilerOptions.declaration: true`.

When I run tsc, the above code (correctly) emits compile time error:
```
Property 'foo' of exported class expression may not be private or protected.ts(4094)
```

I would expect running tsc with --noEmit would return the same errors, since all other configuration options are identical, we just want to skip producing our outputs. This is a common use case for tasks that watch for ts compile-time errors.

**Actual behavior:**

When I run it tsc with `--noEmit`, these errors are now hidden.

Practical impact of this is that I have vscode reporting errors inline that my project-wide error watcher does not pick up. 

This causes me anxiety.

**Playground Link:** 
N/A

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/30355

This case demonstrates that the error should be occurring whenever `declaration: true`... this leads me to believe that the error being hidden when `noEmit: true` is an unintended side effect.

**Comment by RyanCavanaugh** [comment]
What part of your build pipeline is actually producing `.d.ts` files?

**Comment by sheetalkamat** [comment]
`noEmit` means you are not emitting so providing errors from declaration emit seems incorrect?

**Comment by RyanCavanaugh** [comment]
Declaration emit errors are produced as part of producing declaration files themselves; basically you only see declaration emit errors iff declaration files are being made. This is the intended behavior since some code is fine when it's not making a .d.ts but needs extra annotations or local aliases to make a valid .d.ts. We could take a separate suggestion for some mode to "act as if" we're generating these files, but there'd need to be some compelling scenario for it since this generally don't seem to be something people need.
