### ISSUE TITLE
Remove extraneous top-level await requirement

### ISSUE THREAD

**Issue by Vandivier** [microsoft/TypeScript#37794]
This may be a bug, I'm not sure. So I'm submitting as a feature request.

## Search Terms

`await`, `top-level`,  `disable rule`

## Suggestion

`"isolatedModules": true,` should not be required to remove top-level await error.

## Use Cases

I'm scripting a very simple file I/O script using Deno. The script runs without issue. Full code is in the below example.

Even though it works, VS Code complains. I think the complaint is at the TS level and I can't ignore it as a specific error. I can ts-ignore line-by-line, but that's not satisfactory.

The error is `'await' expressions are only allowed at the top level of a file when that file is a module, but this file has no imports or exports. Consider adding an empty 'export {}' to make this file a module.ts(1375)`

## Examples

```
const decoder = new TextDecoder("utf-8");
const data = await Deno.readFile("tsconfig.json"); // <!-- VS Code shouldn't have red squiggle here.
console.log(decoder.decode(data));
```

## Checklist

I have no idea whether this feature meets the items in the checklist.

## Related Issues

1. [merged PR] https://github.com/microsoft/TypeScript/pull/35813
2. https://github.com/microsoft/TypeScript/issues/19573
3. https://github.com/microsoft/TypeScript/issues/37402
4. https://github.com/microsoft/TypeScript/pull/37424
5. [closed] https://github.com/microsoft/TypeScript/issues/36036

**Comment by kitsonk** [comment]
@Vandivier TLA await are invalid in script files.  Deno loads every file as an ESM file, but to VSCode your example doesn't look like a module, so it it is treating it like a script.  The current canonical way to for a file to be a module instead of a script when there are no other imports or exports is to include an `export {}` in the file.  This will resolve the issue.

There is a proposal for [a pragma](https://github.com/tc39/proposal-modules-pragma) to force modules, but it is Stage 1 (early stages) in TC39.

**Comment by avin-kavish** [comment]
@kitsonk We now have a way to know whether files are implicitly to be treated as a module though. `type: "module"` so can we consider this?

**Comment by RyanCavanaugh** [comment]
Addressed at https://github.com/microsoft/TypeScript/issues/36036#issuecomment-1211134182
