### ISSUE TITLE
Incorrect type when using nullish coalescing operator in *.js files

### ISSUE THREAD

**Issue by ikabirov** [microsoft/TypeScript#37909]
**TypeScript Version:**  3.8.3

**Search Terms:**
nullish coalescing in js files

**Code**

![image](https://user-images.githubusercontent.com/9967995/79052064-7a4d7500-7c3c-11ea-9be5-5044a3797d67.png)

**Expected behavior:**
same behavior for .*ts and *.js files

**Actual behavior:**
incorrect type in *.js files

**Comment by a-tarasyuk** [comment]
The same behavior for the `||` operator

<img width="211" alt="1" src="https://user-images.githubusercontent.com/509265/79349017-71131f80-7f3e-11ea-90ec-e2b40d5e6244.png">

That's because of `getEffectiveInitializer` for JavaScript context returns the `right` side of the `BinaryExpression`

https://github.com/microsoft/TypeScript/blob/15c3e99cbd315629e8c2c1444ea879a75aa22d8a/src/compiler/utilities.ts#L1973

and for TypeScript entire `BinaryExpression`

https://github.com/microsoft/TypeScript/blob/15c3e99cbd315629e8c2c1444ea879a75aa22d8a/src/compiler/utilities.ts#L1975


```ts
// a.ts
const a /* 'test' | 0 */ = 'test' || 0;
const b /* 'test' | 0 */ = 'test' ?? 0;

// a.js
const a /* 0 */ = 'test' || 0;
const b /* 0 */ = 'test' ?? 0;
```

I'm not sure, maybe it is an expected result.

cc @orta @RyanCavanaugh

**Comment by orta** [comment]
Thanks @a-tarasyuk  - I wonder if that was to short curcuit and simplify the amount of work done in JS mode. I think it's reasonable for us to just switch to `node.initializer` 👍

**Comment by orta** [comment]
Started looking into this, then realized it had been fixed in master: https://github.com/microsoft/TypeScript-Twoslash-Repro-Action/issues/8 🎉
