### ISSUE TITLE
Compiler complains that Object is possibly 'undefined'

### ISSUE THREAD

**Issue by xtianus79** [microsoft/TypeScript#37933]
I know this is another thread that was closed down so you can't reply to it any longer. However, this issue is important and it needs attention. One thing I suggest is some documentation and examples on the issue. 

Half of my day is literally trying to figure out why I am getting this type error and then trying to mitigate it. 

One of the comments was from the moderators was "don't post every time you get an error here." because some if not most of those errors are dev mistakes. Still, even though they're mistakes there's a disconnect and the issue is large enough to address. 

I want you guys to realize that while I love coding in typescript this is HUGELY big problem that is quit frustrating on a day to day basis.  

more context and more explanation and more standardization should help this issue greatly. 

to the code:

why in world would this possibly throw an error? 

```
interface ISearchAddressResponse {
    summary: object | undefined,
    results: [] | undefined
}

const atlasAzureMapSearchAddress = await new AddressSearchService('bZnmFCm4pX4z0K5_ejf1Rc8VYfYfcJP5KfZGPc1TztE', 'https://atlas.microsoft.com/search/address/json', '1.0', `${cityZipCode.city} ${cityZipCode.zipCode}`).searchForAddress();

sample output  {
  summary: {
    query: 'miami 33131',
    queryType: 'NON_NEAR',
    queryTime: 8,
    numResults: 8,
    offset: 0,
    totalResults: 181,
    fuzzyLevel: 1
  },
  results: [
    {
      type: 'Geography',
      id: 'US/GEO/p0/110871',
      score: 4.664000034332275,
      entityType: 'PostalCodeArea',
      address: [Object],

 if (atlasAzureMapSearchAddress) {
            const azureMapSearchResult = atlasAzureMapSearchAddress.results[0].address;
```

**Comment by xtianus79** [comment]
@RyanCavanaugh I added this code snippet here can you answer this?

**Comment by RyanCavanaugh** [comment]
@xtianus79 I don't have the definitions all the types and variables used here, you have some non-code stuff mixed into the middle that I'm not sure how to interpret, and I don't even know which line of code you're getting an error on.

Meaningful, isolated repros can be addressed by us very quickly and precisely. Samples like this just leave us guessing about what you're trying to get at. The templates are clear about what kind of information we need in order to get you the outcome you're looking for; I'd ask that you read them and follow them.
