### ISSUE TITLE
Check index array length

### ISSUE THREAD

**Issue by mdbetancourt** [microsoft/TypeScript#38000]
## Search Terms
Indexing, Array, Strict check

## Suggestion

Strict check to indexing a array

## Use Cases
Safety with arrays usages

## Examples
```ts
const arr: House[] = .... // same as [] | House[]
arr[0] // throw error
if(arr.length > 0) {
  arr[0] // OK
  arr[200] // throw error
}
const arr2: [House, House] = ...
arr[0] // OK
arr[1] // OK

```
## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code (with a flag)
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by Kingwl** [comment]
```ts
let a = []
a[1000] = 1 
a.length // 1001
```
JS AWESOME🤷🏻‍♂️

**Comment by RyanCavanaugh** [comment]
We go into this a bit at #13778. There isn't a huge amount useful that can be done here while still being sound given the existence of things like `pop`, `push`, and `clear` and the fact that those things can be invoked through indirect operations.

**Comment by rubenlg** [comment]
`push()`, `pop()` and the other arguments provided in this thread did not prevent TypeScript from implementing tuples, even though these operations break tuples completely:
```
function foo(x: [number, number]) {
    console.log(x[2]); // Expected compiler error: no element at index '2'.
    x.push(5); // Should this even be allowed on a tuple?
    console.log(x[2]); // Still compiler error? Now there is index 2.
    x.pop(); x.pop(); // Should this even be allowed on a tuple?
    console.log(x[1]); // No problem here? Now length is actually 1
}
function bar(x: [number, number], y: number) {
    // Works, but should fail unless y is typed to be 0, 1 or 0|1
    // I'm ignoring this same as tuples ignore it too.
    console.log(x[y]); 
}
```
Assuming that tuples are still a nice addition to the language, we could leverage them to provide some incremental index safety here, e.g.:
```
function foo(x: number[]) {
  if (x.length > 0) {
    // New behavior: x becomes [number, ...number[]] rather than just number[].
    console.log(x[1000]) // New behavior, TS only allows indexing at 0.
  }
  if (x.length == 2) {
    // New behavior: x becomes [number, number]
    console.log(x[1000]) // TS error (already happens today for [number, number])
  }
}
```

So the idea would be:
1. If you declare your array as a regular `T[]` array, you are on your own when indexing it.
2. If you declare a tuple with a fixed length, you get strict index checking (already happens today).
3. If you declare a tuple with some fixed params and a rest operator, you get strict index checking because you provide _some_ knowledge to the compiler about the length.
4. A check on the length acts as a type guard that transforms the array into a tuple (possibly with rest operator), enabling the checks in 2 and 3.

As an alternative, we could do this only for immutable arrays/tuples. You can't do `push`, `pop` or randomly write to those anyway.

Another alternative is to drop 4 (which can still be implemented with custom type guards), but at least implement 3, so we can do:

```
function hasOneOrMore<T>(x: T[]): x is [T, ...T[]] {
    return x.length > 0;
}

function foo(x: number[]) {
  if (hasOneOrMore(x)) {
    console.log(x[1000]) // Fails because of change 3 above.
  }
}
```

**Comment by Jamesernator** [comment]
I would definitely find even just basic cases working better than nothing. At current I use a custom helper that takes an array and returns if it's a tuple of a given length e.g.:

```js
function isLength<T>(arr: T[], length: 0): arr is [];
function isLength<T>(arr: T[], length: 1): arr is [T];
function isLength<T>(arr: T[], length: 2): arr is [T, T];
// etc
function isLength<T>(arr: T[], length: number): arr is T[] {
    return arr.length === length;
}
```

I use it quite a lot as I'm also using `--noUncheckedIndexedAccess`, but it'd be super nice to be builtin so I can just use `arr.length === 0` rather than using a custom function that only exists for the type system (or more accurately forgetting to use it, and then having an error that value could be undefined). Having `<`, `<=`, `>`, `>=` would be even better for things like `const [first, ...rest]` and so on.

**Comment by Kingwl** [comment]
@Jamesernator 

Well... Just for fun:
![image](https://user-images.githubusercontent.com/6831019/120933283-faca1180-c72b-11eb-8856-6c89beae550d.png)

[playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKgrmANhAyhAjgfQDwwDRQAyBAglBAB7AQB2AJgM5QDaAdOwIY0gC6AfFAC8UEswBEyGgHNgACzE9yVWoyJQA-CKgAuWAmRosuAsRbtWJAjH4AoUJD1JUGY0QHD4TwznxECzWxsAMzgaAGNgAEsAexooSIZCWhlZV0IlanomGjgAWwAjCAAnPgAKDiKi3RgAgkkU3UIASl0KovimTwMXX0IBAG8bKGGoIohgOCK4ttZ6uSFBYTnZGwBfGxs6CDDECugw2IZgKDbdI6LI6QCbSKCoUoSk6TlyyoIAZiamqEGRqAOaEcWFAgpEikcCAxtrE6AQ5GC6FBFMI2msgA)

**Comment by Lonli-Lokli** [comment]
@Jamesernator I havent checked your sample but from what I see you cannot guarantee that array has at least 1 element, right? So your method should be named 'exactLength', instead of 'atLeast'

**Comment by JohnWeisz** [comment]
This is more complex unfortunately

You can do this:

```
let arr = [0,1, 2];

arr.length = 10;

arr[9] =9;
```

And yet...

```
arr[7] === undefined // true
```

**Comment by RyanCavanaugh** [comment]
@rubenlg just because the variable you have has type readonlyarray doesn't mean that someone else doesn't have a reference to the same value with a mutable type of binding, So the readonlyness of array tells you nothing about whether or not it's mutable in practice

**Comment by MDanialSaleem** [comment]
The above discussion makes sense as to why the length check is not enough for type narrowing, but what about when the index is known to contain a non null object because it has been retrieved from findIndex such as:

```
    const index = items.findIndex(item => somecondition);
    if (index !== -1) {
      items[index].children = //still get error;
    }
```

Although this can be easily replaced with this which does not throw any error, I am just curious as to why the first example does not work:

```
    const foundItem = items.find(item => someCondition);
    if (foundItem != null) {
      foundItem.children = // no error;
    }
```

**Comment by rubenlg** [comment]
@MDanialSaleem Several reasons:
1. Because `findIndex` only guarantees that the result is within the array length or -1, it doesn't guarantee anything about the contents of the array, which can still be undefined.
2. Because `index` is just a regular number. It doesn't matter that it came from `findIndex`. When you use it to index the array, it's the same as any other number.

So in the end, it has the exact same problems as doing a bounds check on any other index. Here is an example in which your first code snippet could have a bug, and the compiler is catching it:

```typescript
const x: number[] = new Array(10); // Sparse array, all 10 elements are undefined
const index = x.findIndex((x, i) => i == 2);  // returns 2
console.log(x[index].toFixed(2)); // Typescript complains, and it's actually catching a bug
```

Of course, you can write other callbacks for `findIndex` that successfully guard against undefined values. But Typescript can't statically analyze the `findIndex` callback implementation to understand whether it guards against undefined values or not.

**Comment by MDanialSaleem** [comment]
Thanks @rubenlg for the detailed answer.
> 
> 
> Of course, you can write other callbacks for `findIndex` that successfully guard against undefined values. But Typescript can't statically analyze the `findIndex` callback implementation to understand whether it guards against undefined values or not.

Yes, I was referring specifically to this case. So TS cannot, _right now_, infer if the parameter passed to a function is not null by statically analyzing the body of the function, but can it not be implemented, _potentially_ using the same mechanism that TS uses to infer return types?

Although, I do not think there will be many valid usecases of this, considering that the second example in my original question is a very valid way of doing things.

**Comment by demurgos** [comment]
If/once the [record and tuple](https://github.com/tc39/proposal-record-tuple/) support lands, narrowing based on a native tuple length should become possible.

**Comment by GermanJablo** [comment]
@RyanCavanaugh I think @rubenlg made good points that weren't answered.

Namely, why are restrictions imposed on arrays that are not imposed on tuples or objects?

**Comment by GermanJablo** [comment]
And what do you think about something like what @jcalz suggested here:
https://github.com/microsoft/TypeScript/issues/40316#issuecomment-894693343
