### ISSUE TITLE
typeof fails on variables created with type assertion

### ISSUE THREAD

**Issue by beltaurus** [microsoft/TypeScript#38103]
**TypeScript Version:**  Version 3.8.3

**Search Terms:** typescript typeof type assertion

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
let str1: string = '1'
let str1_: any = str1 as any					
let str2: number = str1_ as number
console.log(typeof str1 === 'string')
console.log(typeof str2 === 'number')
```

**Expected behavior:**
Console should confirm both tests to be `true`
**Actual behavior:**
`typeof str2 === 'number'` registers `false`
**Playground Link:** 
[Playground Link](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=5&pc=38#code/DYUwLgBAzmBOCMAuacCWA7A5hAvBA5PPgFCiQwID6yAhugJ64oIQ1SsMCQ33p4zAJmToArgFsARiFhMK8Sq3ajJ04gGMA9uigbQAOmAbMACjD0ADiA0AzZvFw48+Chkz4AlOq079hk2csbQQcnZSlYDyA)
**Related Issues:** 
No (there were over 100 matches to my search criteria, but from the titles I couldn't derive an equivalent).

**Comment by WhileTrueEndWhile** [comment]
Typescript is an additional type system at compile time, which tries to map the type system of Javascript as good as possible. The runtime behavior is not influenced by Typescript. That means you can trick the compiler **at any time** if a type conversion goes through `any`.

If you want to convert a string to a number, you MUST use e.g. `Number(...)` and not simply convert using `as`. The same applies to `readonly`. If you really want a read-only object, use `Object.freeze`. Please also note: You cannot make an `instanceof` on an interface, because it exists ONLY at compile time and is not anchored in the prototype.

For example, you can use JSON Schema if you want to validate unknown data at runtime. There are also tools that convert JSON Schemas to typescript definitions, so that a synchronous validation at compile time and runtime is possible.

**Comment by MartinJohns** [comment]
https://www.typescriptlang.org/docs/handbook/basic-types.html#type-assertions

> Type assertions are a way to tell the compiler “trust me, I know what I’m doing.” A type assertion is like a type cast in other languages, but performs no special checking or restructuring of data. It has no runtime impact, and is used purely by the compiler. TypeScript assumes that you, the programmer, have performed any special checks that you need.

**Comment by beltaurus** [comment]
Thank you @WhileTrueEndWhile and @MartinJohns.
I think the lesson learned for me is to avoid creating code with `typeof`-based conditions, if the respective variables have been manipulated with type assertions.
A silly example shows that `typeof` is capable of understanding the essential types indeed (there has to be a purpose for the command!):
```
let str1: string = '1'
let str2: number = Number(str1)
console.log(typeof str1 === 'string')
console.log(typeof str2 === 'number')
```
So what I'm thinking is that the constructor `Number()` is the actual typecast operation, and I'm not sure why I would ever use a type assertion?
(I have plenty of experience in program languages and scripting, but JavaScript and TypeScript are brand new tools for me).

**Comment by beltaurus** [comment]
@RyanCavanaugh : unfortunately, this was closed (probably as answered) while I was taking the feedback, and writing a follow up question:
Why would people ever use a type assertion, if you have a more robust solution by using a constructor?
Do I need to open a new issue, or can this existing issue re-open until fully understood?

**Comment by WhileTrueEndWhile** [comment]
Note that this is rather not a help forum, even though the typescript people are pretty cool. I only say this to avoid possible disappointment :) 

> I think the lesson learned for me is to avoid creating code with `typeof`-based conditions, if the respective variables have been manipulated with type assertions.

I'd say it's upside down. Use Typescript like Javascript and let Typescript detect errors early. Because every Javascript operation like `Number(...)`, `Object.freeze(...)` or `instanceof` automatically changes the type at compile time. Only in an emergency you should declare the types manually. Of course, this does not mean that you should not assign a type to class attributes or function/method signatures.

> So what I'm thinking is that the constructor `Number()` is the actual typecast operation, and I'm not sure why I would ever use a type assertion?

`Number(...)` creates a new object. `x as number` only changes the view at compile time. Javascript is strongly typed, although dynamic. Typescript tries to add static typing. So it is not like in C that you can't say anything about a reference at runtime. It is always clear which type an object has at runtime. But you might want to detect some errors before runtime. `typeof` or `intanceof` always tells the truth. Typescirpt can be wrong.

> Why would people ever use a type assertion, if you have a more robust solution by using a constructor?

If you know for sure that a variable has a certain type at runtime, even if it is only ducktyping, then use a type assertion. Interfaces are well suited for ducktyping. If you use classes, the type is known at compile time through the typescript type system. But also at runtime, the type is mapped by the prototype system and can also be checked with `typeof` or `intanceof`.
`Number(...)` is therefore both. Both a type assertion and a "real" conversion at runtime.

If you get data from a server and read it using `JSON.parse`, you can simply make a type assertion to an interface, because you trust the server to deliver the expected data. Of course, it would be cleaner to do a check with e.g. a JSON schema before telling Typescript that you know what type this data is.

----

I hope this helps you to work quickly and productively with this technology. For the fact that web developers are often laughed at, some things are not immediately obvious :D
