### ISSUE TITLE
Incorrectly emitted error TS1149: File name differs from already included file name only in casing

### ISSUE THREAD

**Issue by alespergl** [microsoft/TypeScript#38181]
**TypeScript Version:**  3.8.3

**Search Terms:**
forceConsistentCasingInFileNames, TS1149

**Code**
`index.ts`
```ts
/// <reference types="./foo" />
/// <reference types="./Bar" />
```
`foo.d.ts`
```ts
// empty
```
`Bar.d.ts`
```ts
// empty
```
`tsconfig.json`
```json
{
    "compilerOptions": {
        "forceConsistentCasingInFileNames": true
    }
}
```

**Expected behavior:**
Clean compile.

**Actual behavior:**
```
index.ts:2:23 - error TS1149: File name '/.../bar.d.ts' differs from already included file name '/.../Bar.d.ts' only in casing.

2 /// <reference types="./Bar" />
                        ~~~~~


Found 1 error.
```

**Playground Link:** 

**Related Issues:** 
#25460

**Comment by sheetalkamat** [comment]
This is because `types` are always lower case #10340

**Comment by DanielRosenwasser** [comment]
Uh, I didn't even realize that `types` could get relative paths, but since they do I think maybe they should not automatically lowercase. I'd wait for Ryan on input here.

**Comment by sheetalkamat** [comment]
But its not just the path that's the issue. its the type itself being referred to as `Bar` and will become `bar`

**Comment by kodekage** [comment]
How can one resolve the compilation error?

**Comment by FelipeCarlota** [comment]
So, I had this same issue, and I figured out that, for some reason, my folders on GitHub were not updating as they were in my local architecture.

##Context of the Problem
I had the path:
src/routes/index.ts

And I changed it to:
src/Routes/index.ts

When I pushed it, somehow, my architecture on GitHub looked like this:

```
src
   Routes
      index.ts
   routes
      index.ts
```

##The Deploy Error

My deploy crashed with the error:

`src/routes/index.ts(7,23): error TS1149: File name '/opt/render/project/src/src/routes/user.ts' differs from already included file name '/opt/render/project/src/src/Routes/user.ts' only in casing.`

##How I solved It
I went to the Git repository on the Git platform and deleted the old folders that git push was supposed to change, since they no longer existed in my local repository. After that, the error went away.

##Final Words
I hope this helps someone solve the problem because I really did some things that made no sense to me while trying to fix it. So... I hope it helps.

Take care.
