### ISSUE TITLE
Can not run Nodemon in node project build with Typescript (In Windows Only)

### ISSUE THREAD

**Issue by jimit-raval** [microsoft/TypeScript#38265]
I build a Node project with typescript and it just works fine in Ubuntu & Mac but not in Windows.

There is three script in my package.json 

`"build": "tsc"`
`"start": "tsc --watch & nodemon dist/index.js"`
`"lint": "tslint -c tslint.json 'src/**/*.ts' --fix"`

**"npm run build"** executed and makes build successfully in dist folder

after running **"npm start"** command shows in terminal which in below Image

![Capture](https://user-images.githubusercontent.com/48219961/80720082-0820cf80-8b1a-11ea-972f-b8c47954412d.PNG)

but not starting Nodemon as it is included in "tsc --watch & **nodemon dist/index.js**"

when I run only this **nodemon dist/index.js** command then it will execute successfully but not detect any changes in TS file so it is not good for developer. 

so this is the issue I faced only in Windows.

**Comment by MartinJohns** [comment]
This is not an issue with TypeScript.

Writing the command `tsc --watch & nodemon dist/index.js` will run  `tsc`, and then it will run `nodemon` **once `tsc` finished**. But due to the usage of the watch-mode the process does not finish. This is the normal expected behavior of the Windows command prompt.

**Comment by jimit-raval** [comment]
@MartinJohns Thank you so much for your answer :)

How can we prevent this behavior of cmd in windows to run it smoothly with nodemon ??
