### ISSUE TITLE
Narrowing does not work for constrained template arguments in JS

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/TypeScript#38309]
**TypeScript Version:**  3.8.3

**Search Terms:** jsdoc template narrow

**Code**

```js
/**
 * @template {string | string[]} T
 * @param {T} a 
 */
function foo(a) {
	if (Array.isArray(a)) {
		a.map; // somewhat correctly narrowed to (T & any[])
	} else {
		a.substr; // Error, not narrowed at all (T)
	}
}
```

**Expected behavior:**
1. in the if-branch, `a` is narrowed to `string[]`
2. in the else-branch, `a` is narrowed to `string`

**Actual behavior:**
1. in the if-branch, `a` is narrowed to `T & any[]`
2. in the else-branch, `a` is NOT narrowed

**Playground Link:** This is JS, so the playground doesn't work

**Related Issues:** Constraint support was added in #24600

**Comment by IllusionMH** [comment]
It's not only in JS.

[TS nightly repro](https://www.typescriptlang.org/play/index.html?ts=4.0.0-dev.20200503#code/GYVwdgxgLglg9mABMOcA8AVRBTAHlbMAEwGdESoAnGMAc0QB9yqbaBtAXQD4AKAQwBciDAEpEAbwCwAKACQMYIh4BBSpT4BPAHQwSq9Rv4ixUubL5aAtnwAOAbkQB6R+TiXsAdwAWfKIghwatjQADYaiGB8anAe2ESIUHBKWABkiHxgGpwiMrIAvjghJNgSueZaJCAARhSUDs6IAKLRlAA0EXB+kdGx8b7pISHJOXJ5MmPSQA)

**Comment by AlCalzone** [comment]
You're right. That is probably intended then, but at the very least it is not intuitive...

**Comment by RyanCavanaugh** [comment]
@ahejlsberg @weswigham should we be narrowing to` T & string` in the `else`?

**Comment by weswigham** [comment]
> should we be narrowing to `T & string` in the else?

🤷‍♀️ We certainly don't today. (Generics are never narrowed in the `false` condition.) I'd normally say that something like #29317 would allow us to fix this (since we would pretty trivially say `T & not string[]` in the false branch, which is more accurate, which can then go on to filter the constraint when fetched). Specifically in cases like this, where we're guarding against an element of a union constraint, filtering the constraint and intersecting it _may_ work as a substitute for that... Unfortunately, specifically for `Array`, `Array.isArray` now has a return signature type of `arg is T extends readonly any[] ? unknown extends T ? never : readonly any[] : any[]`, which is _decidedly_ not "exactly an element of a union constraint", so it's.... unclear that we could adjust this without a full negated-type-style fix.

**Comment by ianstormtaylor** [comment]
Ran into this while trying to implement a `size` function:

```ts
const size = <T extends string | Array<any> | Map<any, any> | Set<any>>(value: T): number => {
    if (value instanceof Map || value instanceof Set) {
        return value.size
    } else {
        return value.length // Error: Property 'length' does not exist on type 'T'.
    }
}
```

**Comment by n9** [comment]
Is this issue also cause for the following error?

```ts
let x: unknown
if (!(x instanceof Array)) {
    x = []
}
x.length // <- Object is of type 'unknown'.
```
[TS Play](https://www.typescriptlang.org/play?#code/DYUwLgBAHgXBCuA7A1og9gd0QWAFAEsAzCACgEISoJ9EBnMAQ0QGMQ1iBBAJy4YE8AlAIgBvPBAnQIAXggBtALp4AvnigA6UIgDmYABZA)

Or the cause is different?
