### ISSUE TITLE
TypeScript allows comparison of function objects using ordering operators (<, >, <=, and >=)

### ISSUE THREAD

**Issue by evanw** [Microsoft/TypeScript#3831]
Example:

```
class Foo {
	foo(): number {
		return 0;
	}
}

function check(a: Foo, b: Foo): boolean {
	return a.foo < b.foo;
}
```

This came up when wrapping existing fields in getters. After testing this, it appears that this is valid JavaScript (of course) and it orders the two objects after calling toString() on each one. This seems much less useful to me than an error or at least a warning in this case to catch these kind of accidents. Is this behavior intentional?

**Comment by basarat** [comment]
Its allowed because it isn't disallowed. That said it sounds like a great rule to add to `tslint` : https://github.com/palantir/tslint

**Comment by RyanCavanaugh** [comment]
The spec says

 > [The <, > <=, >=, ... operators] require one or both of the operand types to be assignable to the other. The result is always of the Boolean primitive type.

It's awkward to try to restrict this since there's no way to specify that a generic type parameter must be of some type that does support meaningful comparison, and it would be weird to say that you could use `T > T` in a generic function `f<T>(lhs: T, rhs: T) *and* invoke that generic function with a function, but not compare two functions the same way directly. And it turns out that comparisons of functions actually do generate self-consistent results (`f > g` implies `!(f < g)`), so it's not as meaningless as other operators (`[] + {}`). So on balance it's kind of on the edge and we'd rather not take a breaking change for it.

Note that other comparisons like `a.foo < 0` would have failed in your case.
