### ISSUE TITLE
`4.0-dev` throws "Expression produces a union type too complex to represent", 3.8.3 no issues

### ISSUE THREAD

**Issue by GavinRay97** [microsoft/TypeScript#38343]
**TypeScript Version:**  4.0.0-dev.20200504

**Search Terms:**
```
Expression produces a union type too complex to represent
union type too complex to represent regression
union type too complex to represent 4.0
```

**Code**

https://github.com/vadistic/graphql-extra/blob/complex-unions-issue/test/complex-union-issue.spec.ts

**Expected behavior:**

TS does not error and produces valid types like it does in `3.8.3` in video demo comparing swapping between them below

**Actual behavior:**

https://streamable.com/bq9dnh

**Playground Link:** 

https://codesandbox.io/s/graphql-extra-issues-cq23x

**Related Issues:**

**Comment by weswigham** [comment]
The intersection type mafufactured by the base type of `FieldDefinitionApi` for the final intersected type of the `node` field of the class has `21 * 11 * 23 * 2 * 3 * 43`, or over 1.3 million potential union members (in reality it probably works out to be a tad lower due to some types being the same between input unions, but not by much).

We refuse to manufacture the type (since such a huge type, if it even fits in memory, has terrible perf characteristics) now and issue an error instead~

We started doing this in `4.0` because our stricter intersection member checking causes us to actually inspect the members  of the intersection and materialize the base class `node` field. You can get the same error in 3.9 with an explicit access of the `node` field on `FieldDefinitionApi_base`. For example, if you put a `const x = null as any as InstanceType<typeof FieldDefinitionApi_base>["node"];` somewhere inside `field-definition.d.ts` (and ignore the initializer error), you'll get a complexity error in 3.8 as well.

The type really is just too complex, and needs to be pared back in some way.

**Comment by GavinRay97** [comment]
@weswigham The fact that you gave me an answer and I now understand why it happened made my day (was driving me crazy). Thank you a ton :smiley: 

On a suspected guess, I managed to fix the issue in that library by swapping out the package used to do class mixins to a different one that had more stringent types, and problem disappeared.
