### ISSUE TITLE
Static field emit is IIFE

### ISSUE THREAD

**Issue by robpalme** [microsoft/TypeScript#38528]
**TypeScript Version:**  3.9.2

**Search Terms:**  static field, static class members, emit

**Code**

```ts
// @target: esnext
// @useDefineForClassFields: true
class C {
    static x = 3;
}
```

**Expected behavior:**

Expected JS emit is:

```js
class C {
    static x = 3;
}
```

**Actual behavior:**

Actual JS emit gets wrapped in an unwanted IIFE.

```js
let C = /** @class */ (() => {
    class C {
        static x = 3;
    }
    return C;
})();
```

**Playground Link:**

- [Correct behavior in TypeScript 3.8.3](https://www.typescriptlang.org/play/?useDefineForClassFields=true&target=99&ts=3.8.3#code/FAYwNghgzlAEDCsDexZtlALhTBLEsAHrALywDMA3MAL7BA)
- [Correct behavior in TypeScript 3.9.0-dev.20200214](https://www.typescriptlang.org/v2/en/play?useDefineForClassFields=true&target=99&ts=3.9.0-dev.20200214#code/MYGwhgzhAEDC0G8BQ1XQgFzBg)
-  [Incorrect behavior in TypeScript 3.9.0-dev.20200215](https://www.typescriptlang.org/v2/en/play?useDefineForClassFields=true&target=99&ts=3.9.0-dev.20200215#code/MYGwhgzhAEDC0G8BQ1XQgFzBg)
- [Incorrect behavior in TypeScript 3.9.2](https://www.typescriptlang.org/play/?useDefineForClassFields=true&target=99#code/FAYwNghgzlAEDCsDexZtlALhTBLEsAHrALywDMA3MAL7BA)

**Related Issues:** #38374 

The bug is that classes with static fields are now getting wrapped in an IIFE.  This undesirable bloat occurs unconditionally.  There does not appear to be anyway to turn this off to get back to standard JS emit.

The emit change was introduced by #32011

Credit to @evmar for [discovering this issue.](https://www.reddit.com/r/typescript/comments/gilb3e/announcing_typescript_39/fqfrqzz/)

**Comment by robpalme** [comment]
Also, I should apologize for not catching this sooner.  We promised to set up CI coverage of TypeScript candidate releases.  And we did set it up! Unfortunately the CI early-exited when it hit a package that wasn't ready for TypeScript 3.9, which stopped it reaching our emit-equivalence check for any of the packages.  Having just disabled the early-exit, it immediately revealed this issue in the Beta 😬 We'll do better for the next release.

**Comment by robpalme** [comment]
Ok, I think I understand the full issue now.

Dead-code elimination for unused classes was [previously failing](https://github.com/microsoft/TypeScript/issues/15857) for down-leveled classes with static fields.  So the IIFE + magic-comment was [introduced to fix this.](https://github.com/microsoft/TypeScript/pull/32011)

The remaining problem is that the fix was scoped too widely, and ends up getting applied even in cases where [no down-leveling is required.](https://www.typescriptlang.org/play/index.html?useDefineForClassFields=true&target=99#code/FAYwNghgzlAEDCsDexZtlALhTBLEsAHrALywDMA3MAL7BA)

**Comment by rrdelaney** [comment]
We (Google) are also running into this issue 😞 I filed #38374 to add a flag controlling the IIFE emit, because although the emit is valuable to some users, it messes up our toolchain.

**Comment by robpalme** [comment]
Thanks for highlighting this @rrdelaney.  I think these two issues are related and orthogonal.

- #38374 gives control over different flavors of down-leveling
- #38528 restores the ability to have lossless emit for the case of **no** down-leveling

**Comment by rrdelaney** [comment]
I think we might be on the same page here. The idea behind #38374 is to allow us to have lossless emit behind a flag, while still allowing the community to have optimizer hints if they want them. The IIFE doesn't work with our pipelines but is definitely helpful for a lot of people.

**Comment by clydin** [comment]
The issue here is that the ESNext target is not accounted for in the logic.  In all actual ECMAScript targets, static is down-leveled.  This was definitely an oversight.

**Comment by rrdelaney** [comment]
Only emitting for ESNext wouldn't solve Google's issue, we're still using ES2015 emit.

**Comment by clydin** [comment]
The problem demonstrated in this issue only represents when targeting ESNext and the `useDefineForClassFields` option is enabled.  In this specific situation, static class properties are not down-leveled and are instead kept as direct members of the class.  As a result, a wrapper has no real value (assuming no decorators are present) since the wrapper would only contain the class definition.

**Comment by rrdelaney** [comment]
This is also an issue when targeting ES2015: https://www.typescriptlang.org/play?target=2&module=1#code/MYGwhgzhAEDC0G8BQ1oQC5nQS2NADgE4D2+0AvNAIwAMA3EitAOYCm6ACifgBQCUiJqkLsAroQB2cAHRFSDVAF8kyoA

The output from 3.8 allowed for better understanding of the class declaration by static analyzers. Having the wrapper is definitely valuable for something like Terser, but it is not desirable in all situations.

**Comment by rrdelaney** [comment]
Oh wait ok I think I understand this better now. This issue is a subset of the problem we are experiencing, where we would not like the wrapper for ES2015 classes at all. I should incorporate this fix into my CL as well then.

**Comment by clydin** [comment]
No problem and yes, that's correct. This issue is occurring due to an interesting edge case involving ESNext and the `useDefineForClassFields` option.

As an aside, is there any information on the choice of behavior in this situation regarding the static property retention? I assume it is related to ECMAScript spec compliance regarding initialization ordering but I'm curious if there is any background on the topic.

**Comment by tchetwin** [comment]
https://github.com/microsoft/TypeScript/pull/32011 was reverted by https://github.com/microsoft/TypeScript/pull/38719

**Comment by clydin** [comment]
That’s unfortunate.
The alternative is to reimplement the TS transformer’s wrapping logic separately to support minification against some commonly used tools (terser, etc.).  There’s a variety of edge cases that need to be taken into account that make that transformation non-trivial.

The revert also causes the awkward situation where TypeScript’s ES5 output can be better optimized and smaller than ES2015+ output since the ES5 output is wrapped.
