### ISSUE TITLE
Expand definition of Array-like for destructuring types like Uint8Array

### ISSUE THREAD

**Issue by fmilitao** [microsoft/TypeScript#3855]
I get an error when compiling the following code (using the latest 1.5.3):

```
let x = new Uint8Array(2);
let a = x[0];
let b = x[1];
let [c,d] = x; // ERROR: (4,5): error TS2461: Type 'Uint8Array' is not an array type.
```

Code is emitted correctly, and works as expected.

**Comment by danquirk** [comment]
This is by design according to the spec:

```
4.17.1:
An expression of type S is considered assignable to an assignment target V if one of the following is true:
•	V is an array assignment pattern, S is the type Any or an array-like type (section 3.3.2), and, for each assignment element E in V,
```
where an array-like type is one that is assignable to ```any[]```, which ```Uint8Array``` is not. 

Perhaps we need to consider loosening the definition of array-like. At least in the case where you do not use a spread destructuring pattern this is fine. Only when you use a spread pattern do we start to require Array properties (in particular slice and concat). That is:
```ts
let [c,...d] = x; // ERROR: (4,5): error TS2461: Type 'Uint8Array' is not an array type.
```
emits
```js
var c = x[0], d = x.slice(1);
````

I'm going to edit the title to reflect this.

**Comment by RyanCavanaugh** [comment]
This works now due to iterators
