### ISSUE TITLE
Mapped types not instantiated when defined in JSDoc

### ISSUE THREAD

**Issue by ilogico** [microsoft/TypeScript#38572]
**TypeScript Version:**  3.9.2, 3.8.3, next

**Search Terms:** mapped types jsdoc

**Code**

```js
/**
 * @template T
 * @param {T} a
 * @param {{[K in keyof T]: (value: T[K]) => void }} b
 */
function f(a, b) {
}

f({ x: 42 }, { x(param) { } });
```

**Expected behavior:**
I expected `param` to be of type `number`, like it is when the function is defined in [TS](https://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABMAPAFQHwAoCGAuRNAGkQCMCBvRAbQGlEYkBrAUwE85hCBdArANxwAbECwJo63AJSIAvBkT84MACaIAvjIrqAUDuBYqADwIAWAEwaSxrAAccAJxwBbLRo1SgA).
**Actual behavior:**
`param` is of type `{ x: number }[K]`, even though `K` has no meaning/can't be bound in this context.

**Playground Link:** [playground](https://www.typescriptlang.org/v2/en/play?strictNullChecks=true&noUnusedLocals=true&noUnusedParameters=true&target=99&jsx=0&ts=4.0.0-dev.20200512&useJavaScript=true#code/PQKhCgAIUgBAXApgWwA4BsCGTIBUoyyqYBOmykA3rgL6SYFzFkWWUDaA0pAJYB2kANaIAngHsAZngC6ALkgAKAG6Z0AV0TzcXaQEpIAXgB8kJWJ4ATSDToAjAsHAS1fAMbweYgRIWYANJC2+pTgNOBOCpSQAB7yACwATNYBUdEKzOTBkK5eAM5i6IgAdOhiAOYK0ZAA1JCJunQ0ugDcQA)

**Related Issues:** 

This occurs when defining the function in JS through JSDoc, even when used in TS.
When defined in TS, it works in JS as well.

**Comment by sandersn** [comment]
Note that a separate `@typedef` also gives `param: number`, so defining the mapped type in jsdoc works sometimes. It may have something to do with `@template` in the same jsdoc as `@param`:

```js
/**
 * @template T
 * @typedef {{[K in keyof T]: (value: T[K]) => void }} KT
 */
/**
 * @template T
 * @param {T} a
 * @param {KT<T>} b
 */
function f(a, b) {
}

f({ x: 42 }, { x(param) { } });
```

**Comment by sandersn** [comment]
The special-case code from https://github.com/microsoft/TypeScript/pull/24204/files isn't correct; it always jumps to parameter declaration when searching for type parameters in a `@param`'s type, even when this skips type parameters like `K`.

The fix is to getOuterTypeParameters work correctly with `@param`, I think, instead of pretending that they are really at the location of the parameter. Failing that, getOuterTypeParameter at least needs code to jump from `@param` to the parameter in the same way that the existing code does over-eagerly.
