### ISSUE TITLE
mailing list

### ISSUE THREAD

**Issue by mvolkmann** [microsoft/TypeScript#3866]
I hate to file an issue for this, but I can't find another place to ask this.
Is there a TypeScript mailing list where people can ask questions?
My search for one came up empty and I don't see a Google Group.

**Comment by RyanCavanaugh** [comment]
We don't have a mailing list.

Good communication channels include:
 * StackOverflow for technical questions
 * Gitter (https://gitter.im/Microsoft/TypeScript) for general discussion
 * This issue tracker for bugs / implementation details

**Comment by paulbors** [comment]
If you don't have a mailing list, how do you publish your announcements?

How does one go about requesting features and etc? Get answers to common questions or advance topics?

**Comment by DanielRosenwasser** [comment]
> how do you publish your announcements?

https://twitter.com/typescriptlang

> How does one go about requesting features and etc?

This issue tracker?

> Get answers to common questions or advance topics?

StackOverflow

**Comment by paulbors** [comment]
You seriously advocate Twitter and Roadmap?

Can I also find you guys on Facebook, Gab, Google+, Instagram, LinkedIn, Pinterest, Reddit, Snapchat, Tumblr, Twitter, Viber, VK, WeChat, Weibo, WhatsApp, Wikia, and YouTube.

I mean seriously, I rather just get a RSS feed without having to signup for some social media account and be feed the many adds.

As for StackOverflow... Gosh... where do I start with the pollution of bad answers on there. That'll waste your users more time trying to filter through spam rather than get a straight answer.

Anyways, thank you for your time.

**Comment by DanielRosenwasser** [comment]
Sorry we can't serve every venue; we already get enough traffic from the issue tracker. To be frank though, I don't see what's wrong with the Roadmap or the blog. Our website and wiki also have "What's New" pages if you're interested.

> Reddit

[Yup](https://www.reddit.com/user/DanielRosenwasser/submitted/)

> Facebook

If I can dig up the account credentials, maybe.

> VK...Weibo

If I spoke Russian and Mandarin, you probably would!

> I mean seriously, I rather just get a RSS feed

Here y'go! https://blogs.msdn.microsoft.com/typescript/feed/

The thing is that these venues require little-to-no moderation on our part. We already get so much traffic over GitHub that we don't have the bandwidth to moderate and respond on a mailing list.

**Comment by paulbors** [comment]
You can't serve it because you don't allow the user community to answer their own questions as you're lacking a mailing list.

Take for example Apache Wicket:
https://wicket.apache.org/help/#questions

Notice how simple the user support is delegated to the user community while the developers are doing what they do best, implement the new features:
https://wicket.apache.org/help/email.html

**Comment by MaverikSoftware** [comment]
Yes, a mailing list! StackOverflow isn't the best place to build a community around typescript. Github issues is not the best place for general discussion about typescript... We need a mailing list!

**Comment by orta** [comment]
I'd recommend the TypeScript community discord if you'd like to have general discussion, links are in: http://www.typescriptlang.org/docs/home.html

**Comment by paulbors** [comment]
This is hopeless and also the reason why I don't use any of Microsoft's products home. Wish my job would stop deploying Windows and switch to Linux desktop.

The one think Microsoft almost got right was to fix the web scripting tech (TS) after the messy IE. And then... No user mailing list...
