### ISSUE TITLE
TS 3.9.x disallow spread overwrite?

### ISSUE THREAD

**Issue by tommytroylin** [microsoft/TypeScript#38733]
**TypeScript Version:**  3.9.3

**Search Terms:** spread overwritten
**Code**

```ts
const a = { spm: '123', test: 1 };
const b = { spm: '456', ...a };

```
**Expected behavior:**
No Error

**Actual behavior:**
![image](https://user-images.githubusercontent.com/3364271/82649529-ecf23d00-9c4b-11ea-98b5-e6744c80dc8c.png)

**Playground Link:** 
https://www.typescriptlang.org/play/index.html#code/MYewdgzgLgBAhjAvDA3jCAHAtgLhgcgEYAmAZnwBp49CYBfAbgChRJYAjJVdbPfAFgCsANkowAdJISMgA

**Related Issues:** 
#37559 maybe?

**Comment by nmain** [comment]
Why would you want to do this?  The error is correct and at runtime, the value `spm: '456'` is completely irrelevant and can never be observed

**Comment by ExE-Boss** [comment]
You need to do:
```ts
const a = { spm: '123', test: 1 };
const b = { ...a, spm: '456' };
```

If you want `spm: '456'` to override `spm: '123'`.

**Comment by tommytroylin** [comment]
I provide a bad example. Let me explain it in detail.

consider that I wrote a function `handleQuery`
```ts
interface Query {
    spm: string;
    test: number;
}

type HandleQuery = (q: Query) => void;
```

I would like user provide all the keys explicitly. (in this case spm & test) 
But in the real world some one would call it like `handleQuery({ test: 1 })`.(js / no type check)

so for these cases I would provide a default `spm` value

```ts
const handleQuery: HandleQuery = (q) => {
  const finalQuery = { spm: '123', ...q };
}
```

I understand this error. In most cases it should not occur like that.
A simple type cast would fix that error, so just be it 

```ts
const finalQuery = { spm: '123', ...q };
```

**Comment by nmain** [comment]
Typing `q` as `Partial<Query>` is another way to express your intent here

**Comment by MartinJohns** [comment]
> Typing `q` as `Partial<Query>` is another way to express your intent here

Be aware that it's possible to explicitly set `undefined` to a property, which will override the default value as well. Then the property can be set to `undefined`, even if the type explicitly states that it should not be `undefined`.

Example:

    interface Query { spm: string; test: number; }

    const query: Partial<Query> = { spm: undefined };
    const finalQuery: Query = { spm: '123', test: 123, ...query };

    // Type: string // value: undefined
    console.log(typeof finalQuery.spm);

[Playground link](https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgIoFdoE9kG9kDOADgLYBchYUoA5gNzKQFgUjokBG0DAvgFB8EAexDNkAR0xQsFAApwoYYHAA2AHgzYAfMgC8eQqQroQAEwgxQEU8h51BIsZZCrN0im5z78xcsgDkAIwATADM-gA0jBDMFCGhUQB0yZLYtvZ8APSZyAAqWEQQFMzUIDTI2cgAbqqYxmYWVqYOokIqEIkqQjQAFGAFEEIwyM6uUliJvgCU9kA)

**Comment by waynebloss** [comment]
Why not just let me overwrite the property? Who cares if a property gets overwritten on a spread? I don't.

TypeScript is making things more difficult than they need to be.

**Comment by MartinJohns** [comment]
> Who cares if a property gets overwritten on a spread? I don't.

I do. 🤷 

You can use `// @ts-ignore` to prevent the error. But removing this check and there's nothing I could add to re-gain the safety.

**Comment by waynebloss** [comment]
Overwriting a property is not an error though. It's overwriting a property, something that we all do every day.

**Comment by MartinJohns** [comment]
Unreachable code is not an error either, yet I like that the compiler warns me when I have clearly nonsensical code. `{ value: 1, value: 3 }` is in the same ball-park here.

The error occurs when, according to the type-system, a property will always be overwritten. This is not something that we do every day, that's a bug.

The actual issue is the lack of #13195, which would allow to express the intent properly in the type-system.

**Comment by waynebloss** [comment]
Unreachable code is also never useful, whereas overwriting a property during a spread is extremely common because it's so useful.

Your example is showing an object literal that has the same prop twice. Spreading an object that happens to have the same prop is completely different.

I want to set a default value on my object and overwrite it with the object I'm spreading. `Partial<>` doesn't work here because then TypeScript complains that it's missing properties. So, I have to change my entire type or resort to using `Object.assign` just because TypeScript can't express the proper intent? That's garbage.

There are many, many, many complaints about this new error - what concrete problem does it actually solve for you?

**Comment by ChuckJonas** [comment]
I'd have to agree.  This add a tremendous amount of "typing" overhead for certain use cases.
