### ISSUE TITLE
JSDoc tuple typedef with optional elements became null

### ISSUE THREAD

**Issue by chancancode** [microsoft/TypeScript#38747]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**
JSDoc tuple optional

**Code**

[In JavaScript](https://www.typescriptlang.org/play?strictNullChecks=true&jsx=0&useJavaScript=true#code/PQKhCgAIUgBAXAngBwKYBNUDNIG8DaAdgK4C2ARqgE4A0kJF1A-ALoC+kAglQOYDOUGILhI0ebvzaDg4ADap4kAIa8+AbiA):

```js
/**
 * @typedef {[number, number?]} Args
 * 
 * @type {Args}
 */
let args;
```

[In TypeScript](https://www.typescriptlang.org/play?jsx=0#code/DYUwLgBAhgTg5gZwFwQNoDsCuBbARiGAGgizwIH4BdAbiA):

```ts
let args: [number, number?];
```

**Expected behavior:**

The `args` variable should have the same type in both cases.

**Actual behavior:**

* In JavaScript: `[number, number | null]`
* In TypeScript: `[number, (number | undefined)?]`

**Playground Link:** 

* [JavaScript](https://www.typescriptlang.org/play?strictNullChecks=true&jsx=0&useJavaScript=true#code/PQKhCgAIUgBAXAngBwKYBNUDNIG8DaAdgK4C2ARqgE4A0kJF1A-ALoC+kAglQOYDOUGILhI0ebvzaDg4ADap4kAIa8+AbiA):
* [TypeScript](https://www.typescriptlang.org/play?jsx=0#code/DYUwLgBAhgTg5gZwFwQNoDsCuBbARiGAGgizwIH4BdAbiA):

**Related Issues:** None

**Comment by DanielRosenwasser** [comment]
I think this is just an unfortunate fallout of the fact that JSDoc already has `?` reserved for "null/undefined-able". I guess we could give it a different meaning in tuples, and I personally wouldn't be super opposed to that.

One workaround in TypeScript 4.0 might be to use a labeled tuple:

```ts
/**
 * @typedef {[first: number, second?: number]} Args
 * 
 * @type {Args}
 */
let args;
```

Thoughts @sandersn @weswigham?

**Comment by chancancode** [comment]
My understanding is that JSDoc doesn’t support tuple syntax anyway, so as far as JSDoc is concerned, it is invalid syntax so it’s probably okay. Also isn’t the JSDoc question mark a prefix “operator”?

**Comment by chancancode** [comment]
But yes, looking forward to named tuple types, doubly great if there is way to document each named element with JSDoc syntax 😄

**Comment by sandersn** [comment]
Typescript's support for JSDoc actually tries to be a superset of Typescript type syntax, so it should support all Typescript types plus all JSDoc types. But postfix-? causes at least one other ambiguity -- conditional types.

However, postfix-? only exists in JSDoc because of the closure compiler. And it's deprecated there -- it was only added to Closure because of backward compatibility with some tool now lost to [my] history. I think we could remove support as long as Typescript itself hasn't caused lots of people to use it.

That work is tracked at https://github.com/microsoft/TypeScript/issues/37166
