### ISSUE TITLE
[regression] recursive like types => maximum call stack error

### ISSUE THREAD

**Issue by lifaon74** [microsoft/TypeScript#38825]
**TypeScript Version:**  3.9.x and 4.0.0

**Search Terms:** maximum call stack, recursive type

**Code**

- source code here: https://github.com/lifaon74/observables
- yarn install, yarn run build_all

On one of my big projet, migrating from typescript 3.8.3 to 3.9.3 broke many things:
- "circular constraint" errors appeared. I need some kind of circular reference to check if a Generic type matches a specific pattern
- "maximum call stack" error when building the project (simply running tsc)

**Expected behavior:**
should transpile

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/37475
https://github.com/microsoft/TypeScript/issues/38198

**Comment by weswigham** [comment]
The crash looks to be fixed by #38904 (meaning the crash is probably similar in nature or exactly the issue with the updated definition of `Array.prototype.flat` shipped in 3.9). After that it looks like you just have a lot of newly detected circularities in generic constraints, like `TKVMap extends TFiniteStateKeyValueMapConstraint<TValue, TFinalState, TKVMap>`, where in `TFiniteStateKeyValueMapConstraint`, `TKVMap` meaningfully is supposed to determine the output shape.  IIRC, this is _new_ because in 3.9 we now actually can flag circularities arising as a result of mapped type creation (which is how `TKVMap` is eventually used recursively - in a mapped type), where prior to 3.9 we'd fail to flag these (and instead silently use an empty object type). The new behavior is more complete, as previously we were essentially failing to check these constraints.

**Comment by kasperisager** [comment]
I'm seeing stack overflows for recursive types like the following in both 3.9 and nightly:

```ts
type N<T, K extends string> = T | { [P in K]: N<T, K> }[K];

type M = N<number, "M">;
```

[Playground Link](https://www.typescriptlang.org/play/?ts=4.0.0-dev.20200615&ssl=1&ssc=1&pln=3&pc=25#code/C4TwDgpgBAcgPAFQDRQNJQgD2BAdgEwGcpDgAnAS1wHMA+KAXigSgB8oBvKAbQAUoqaALoAuWIhSp6AX26ohAbgBQS0JCgBZRuNwBXALYAjCGRQAiDWdoKgA)

**Comment by weswigham** [comment]
@kasperisager mind opening a new issue for yours? That's definitely a good repro of a crash distinct from the one in the OP here (which is fixed). The OP's crash was in node building, while yours is in instantiation itself.

**Comment by kasperisager** [comment]
Not at all, I'll open a new issue ASAP 👍 Thanks!
