### ISSUE TITLE
`import 'constants' ` always resolving to the node 'constants' module

### ISSUE THREAD

**Issue by mrlubos** [microsoft/TypeScript#38846]
- VSCode Version:
```
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z (2 wks ago)
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0
```
- OS Version: macOS Catalina 10.15.3 (19D76)

Steps to Reproduce:

1. Open VSCode.
2. Create a file `src/constants.js` exporting `foo`
3. Import `foo` as `import { foo } from 'constants'`
4. Hover over the `constants` file path.
5. See the following.

```
module "constants"
@deprecated — since v6.3.0 - use constants property exposed by the relevant module instead.
```

6. ⌘ + click on `constants` file path.
7. See there are 2 definitions – `constants.d.ts` and `index.d.ts` but no `src/constants.js`

Expected result:
- see the definition of `foo` from `src/constants`

The same issue occurs when using `foo` for the first time in a module, no import suggestion is shown.

My `jsconfig.json` file

```
{
  "compilerOptions": {
    "baseUrl": "./src",
    "jsx": "preserve",
    "module": "es6",
    "moduleResolution": "node",
    "target": "es6"
  },
  "exclude": [
    "**/node_modules/*",
    "coverage",
    "dist",
    "node_modules"
  ],
  "typeAcquisition": {
    "include": [
      "cypress",
      "jest"
    ]
  }
}
```

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
I believe this is the expected behavior if you have the node typings installed, but someone on TS would have to confirm that. Note that if run the script in node, ` require('constants')` also always resolves to the node constants module and not the local `constant.js` file.

I do see the expected local `constants.js` file being resolved if I use a relative import: `'./constants"`

**Comment by RyanCavanaugh** [comment]
This is the intended behavior

**Comment by mrlubos** [comment]
Hey @RyanCavanaugh, that sounds good! How would I go about overriding it to resolve to my local “constants” when working on client code? Importing from “constants/index” doesn’t look as nice 😀 do you recommend simply renaming the folder to something else to avoid all this trouble?

**Comment by RyanCavanaugh** [comment]
You can add a path mapping

**Comment by mmakarin** [comment]
> You can add a path mapping

How exactly you should specify it? Something like `"constants": ["constants/index"]` doesn't work for me.

**Comment by kylemh** [comment]
I've made a reproduction of this issue here: https://codesandbox.io/s/priceless-mccarthy-9uk9p?file=/tsconfig.json

Notice in App.js that I can easily import and get the correct type from modules from `'test.ts'`; however, with `'constants.ts'` that is not the case despite manually creating a path for it.
