### ISSUE TITLE
Promise.resolve() need type assertion for string literals

### ISSUE THREAD

**Issue by clshortfuse** [microsoft/TypeScript#38861]
**TypeScript Version:**  3.9.2

**Search Terms:** Promise type assignable string

**Code**

```ts
function test():Promise<'pass'|'fail'> {
  return Promise.resolve()
    .then(() => 'pass')
    .catch(() => 'fail');
}
```

```js
/** @return {Promise<'pass'|'fail'>} */
function test() {
  return Promise.resolve()
    .then(() => 'pass')
    .catch(() => 'fail');
}
```

**Expected behavior:**

No errors

**Actual behavior:**

Type 'Promise<string>' is not assignable to type 'Promise<"pass" | "fail">'. Type 'string' is not assignable to type '"pass" | "fail"'.

**Playground Link:** 

Apparently there's no share link anymore?

-------

You can coerce the type and it'll work.

```ts
function test():Promise<'pass'|'fail'> {
  return Promise.resolve()
    .then(() => 'pass' as 'pass')
    .catch(() => 'fail' as 'fail');
}
```

```js
/** @return {Promise<'pass'|'fail'>} */
function test() {
  return Promise.resolve()
    .then(() => /** @type {"pass"} */ ('pass'))
    .catch(() => /** @type {"fail"} */ ('fail'));
}
```

**Comment by RyanCavanaugh** [comment]
Inference can't proceed "through" the `resolve` call to realize the return types of the function should be kept as literals.

**Comment by clshortfuse** [comment]
This doesn't give an issue with literals:

````
async function test(): Promise<'pass' | 'fail'> {
  try {
    return await Promise.resolve('pass');
  } catch {
    return await Promise.resolve('fail');
  }
}
````

nor this:

````
async function test(): Promise<'pass' | 'fail'> {
  try {
    await Promise.resolve();
    return 'pass';
  } catch {
    return  'fail';
  }
}
````

I believe it's the same logic. Does the syntax of `async`/`await` make a difference? If Typescript is indeed "smarter" with `async` then I can start shifting to that.

**Comment by fatcerberus** [comment]
In the case of the async function, TS can immediately compare the literals you return to the return type of the function and thereby avoid widening them.  In the case of `.then()`, TS *first* does inference for `() => 'pass'` and widens the return type to `string` (because there is no explicit type annotation on the arrow function and that's the normal behavior for return type inference).  From there you end up with `Promise<string>`, which is not assignable to `Promise<'pass' | 'fail'>` and there's no longer enough information to go back and revert the widening.

**Comment by fatcerberus** [comment]
> Apparently there's no share link anymore?

Tip: Press Ctrl+S (or Cmd+S on macOS).
