### ISSUE TITLE
TypeScript ALM - raising expectations

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/TypeScript#3898]
Currently at [TypeScriptLang.org](http://www.typescriptlang.org/) TypeScript v1.5Beta is publicly and prominently announced.

Why is software *not* being targeted for public audience been announced prominently at a branding website?

If, on the other hand, TypeScript v1.5Beta *is* targeted for public audience, why is the specification/documentation of v1.5 not at the ready?
<br/>
##### I believe the application lifecycle management of TypeScript needs a reconsideration:

If some version - any version - gets announced outside of *GitHub*, hence leaving the private development domain, then *documentation* should be finished and ready for download. Because no-one outside the GitHub development participants' inner circle is either interested in delving into the inner parts of TypeScript implementation nor has the resources to do so.

##### Summarized:

   * *Participants in the development* of TypeScript use *GitHub* for their development.
   * *Users* of TypeScript visit the *branding website*.
<br/>

* *Participants in the development* of TypeScript use the *GitHub roadmap* for their considerations.
* *Users* of TypeScript use the *TypeScript documentation* at [TypeScriptLang.org](http://www.typescriptlang.org/) for their considerations.

So the core point I believe needs reconsideration is to strongly differentiate between *GitHub participients* and *library users*.

Anything announced at [TypeScriptLang.org](http://www.typescriptlang.org/) should be finalized and fully documented.

**Comment by mhegazy** [comment]
Thanks @SetTrend, we are in the process of updating our documentation, you can find our working version at https://github.com/Microsoft/TypeScript-Handbook. We are also working on revamping the website to make it point to the latest and most up-to-date documentation. 

As we are in the process of fixing this issue, please take a look at https://github.com/Microsoft/TypeScript-Handbook, and let us know if there are specific topics that you are blocked on, and we can prioritize these and get them done sooner.

also take a look at the [what's new](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript) page, that is not intended to github users specifically.

**Comment by RyanCavanaugh** [comment]
I should note that, like other projects, we use "beta" to indicate "a release that is not fully done yet". So it should not be surprising to find a "beta" release that doesn't have complete documentation. It would be counterproductive for us to not broadly announce betas - the entire point is to get early feedback from those willing to use releases labelled as such.

**Comment by SetTrend** [comment]
@mhegazy :

Thanks a bunch!

I have been working through the current version of the handbook thoroughly. From my *user's* perspective I'm missing typical constructs incl. very strict, concise examples (five lines at most), e.g. for different types of initializers, language keywords and similar.

In a v1.5 documentation I would prefer to have the changes deliberately highlighted (alternative paragraph background color, for instance). So readers acquainted with v1.4 could quickly browse the document for novelties while readers new to the language could read the whole plot. I wouldn't suggest to separate new content into a separate paragraph, though. Keeping it in it's actual context will help experienced readers to strive through information they tend to believe to have already known but actually didn't.

I also would prefer a rendering of each of the examples in ECMAScript v3, v5 and V6, so it'll be possible to read through the printed version of the handbook and understand the underpinnings for those who are familiar with JavaScript but want to migrate to TypeScript, like me. For this approach of learning it's important to be able to "disassemble" in mind from JavaScript to TypeScript while reading through the handbook.

E.g.

### Example
#### TypeScript
    namespace ns
    {
      export var ex : int;
    }
#### ECMAScript v3
    var ns = { ex: 0 };
#### ECMAScript v5
    var ns = { ex: 0 };
#### ECMAScript v6
    var ns = { ex: 0 };


@RyanCavanaugh :

I comprehend, yes. But in ALM *Beta* is the phase where development and documentation is supposed to be finished. Beta is the final, the *bug fix* stage. This includes documentation and code. Anything else whould be required to be called *Alpha*.

<br/>
Let me keep this topic open for another week. Perhaps someone else wants to add his/her comment, too. I'll close this topic as soon as it becomes idle for a week.

**Comment by danquirk** [comment]
@SetTrend the beta phase means whatever a particular development team deems it to mean. I would argue that the JavaScript ecosystem in particular plays it pretty fast and loose with docs, many popular libraries have very sparse documentation. We care about making sure the docs are available in a timely fashion and of high quality but we're generally not going to block users from getting working updates due to a lack of 100% robust docs.

_How would you want people to verify whether the code is actually doing what's it supposed to do according to documentation if there is no documentation?_

Generally people simply file issues when code behaves in an unexpected way, whether or not it's according to the documentation. We don't expect everyone to carefully cross reference all relevant sections of the language specification before filing issues so whether or not the docs are 100% up to date shouldn't affect one's willingness to send us feedback. Likewise, the docs could be 100% up to date and explain the behavior of a particular piece of code but that behavior could be wrong and still need fixing. As someone familiar with JavaScript you should feel eminently comfortable sending us bug reports about TypeScript behavior simply because it doesn't match your expectations of equivalent JavaScript, whether or not our language spec says it currently is or isn't by design.

**Comment by kitsonk** [comment]
> How would you want people to verify whether the code is actually doing what's it supposed to do according to documentation if there is no documentation?

Sorry to be terse, but [TDD](https://en.wikipedia.org/wiki/Test-driven_development) is one way of achieving this.  I can't remember the last time I read the user manual front to back for a car before I got in and drove it and I was *surprisingly* able to still get to where I was going.

**Comment by SetTrend** [comment]
@danquirk :
I'm afraid this is not true - well, except when you're for yourself, of course. ALM is rather strict on this. [Here's a hyperlink to the corresponding Wikipedia article](https://en.wikipedia.org/wiki/Software_release_life_cycle#Beta) to get an impression on what's called a Beta phase.

*Generally people simply file issues when code behaves in an unexpected way, whether or not it's according to the documentation.*

The question is: What's "unexpected". Unexpected isn't a personal feeling. According to ALM unexpected is: undocumented behaviour.

@danquirk + @kitsonk :
I do understand that it's tempting to just let the waters flow, which is sufficient for personal use or degree courses. But when it comes to addressing a public audience, it becomes not only helpful but necessary to get things straight. Going public professionals evaluate your work. Your work has to pass companies' revision departments. If you want the software to play in that league you need to provide a serious ALM. And this - don't kill the messenger for proffering - includes documentation.

**Comment by kitsonk** [comment]
@settrend please don't confuse my responses as some sort of accountability with TypeScript. I am just a user like many. I do not find your arguments compelling. I also don't feel your "lecture" on the semantics of what *beta* means all that useful, but that is an entirely personal viewpoint.

I have contributed to several open source projects and am a committer on a few, I have also managed large teams of software developers for large commercial organisations. I find in particular with open source that instead of "lecturing" that pitching in to help is a far more useful activity. In particular, I have found the TypeScript team very open for contributions. I have also found it is open source in it truest form, which means, especially beta software is never fully polished nor fully documented, but again I have seldom found that a barrier to adoption. If you require an accountable organisation to hold your hand with TypeScript, there are a number of commercial organisations that would be glad to support you for monetary consideration. Again this is just my personal perspective.

**Comment by SetTrend** [comment]
I absolutely agree with your point of view, which is the perspective of a GitHub contributor. But I am arguing from a library user's point of view, which brings me back to my original argument:

*So the core point I believe needs reconsideration is to strongly differentiate between GitHub participients and library users.*

I'm no a contributor. I'm a library client, a *customer*, so to speak. Customers like ma don't have resources to contribute on each and every Open Source library in the world. Our resources are confined to our own projects.

I strongly feel that lack of soundness is being sold as Open Source. And I feel that a lecture is strongly required. You wouldn't tend use a car for a trip lacking a steering wheel, I believe, even if someone freely offers you to contribute the steering wheel.

**Comment by RyanCavanaugh** [comment]
It simply is what it is. We have a finite amount of resources, exactly zero of which are dedicated documentation writers -- all TypeScript-provided documentation you see is written by the same engineers who could otherwise be writing/designing features, fixing bugs, or explaining things to people on GitHub.

We choose to focus on adding features and quality up until the point when we think a release is ready. At that time, we switch to documenting the features and changes in that release. This is a common schedule both in the OSS and non-OSS world and I'm afraid you'll have to adjust your expectations accordingly.

This order of operations is important because, until we finalize on a release, we can't be sure what the actual features or their behavior will be. We rarely get something perfect on the first commit. It's much better for us to write the documentation once the features are finalized because then it's guaranteed to be accurate. If we wrote the docs before the features were baked, we'd have to a) go back and fix the docs to match the behavior and b) review all documentation *again* to ensure it's still accurate. Both of those operations take time that we could be spending doing other things - things like features, quality, or even *more* documentation.

There is no formal specification for what 'beta' means. Even your own link to Wikipedia doesn't back up the notion that 'ALM' defines a strict set of requirements for a given release label. For us, 'alpha' is what you pull from `master` (which is stable ~99% of the time) and 'beta' is a specific commit that we think is good enough for many people to try. *We* get to declare what that means for us. Lecturing us to change the order that we do things, in a way that takes away time from other important activities, so that you feel the correct letters of the Greek alphabet are being used is not compelling.

If you don't like releases that lack full documentation, I totally respect that. We *have* a system for indicating undocumented releases, and we're following it. I'm sorry that this system isn't exactly the one you'd like it to be in terms of the labels 'alpha' or 'beta', but it's the notation we're using and it's working well for the vast majority of our customers.

**Comment by DaleGardner** [comment]
It seems to me that TypeScript 1.5 beta is appropriate for its development stage. According to the modern distinction of software life cycle and what I observe from other open-source projects anyway. Here is Jeff Atwood's description of the life cycle:

> Pre-Alpha
> The software is still under active development and not feature complete or ready for consumption by anyone other than software developers. There may be milestones during the pre-alpha which deliver specific sets of functionality, and nightly builds for other developers or users who are comfortable living on the absolute bleeding edge.

> Alpha
> The software is complete enough for internal testing. This is typically done by people other than the software engineers who wrote it, but still within the same organization or community that developed the software.

> Beta
> The software is complete enough for external testing -- that is, by groups outside the organization or community that developed the software. Beta software is usually feature complete, but may have known limitations or bugs. Betas are either closed (private) and limited to a specific set of users, or they can be open to the general public.

> Release Candidate (aka gamma or delta)
> The software is almost ready for final release. No feature development or enhancement of the software is undertaken; tightly scoped bug fixes are the only code you're allowed to write in this phase, and even then only for the most heinous and debilitating of bugs. One of the most experienced software developers I ever worked with characterized the release candidate development phase thusly: "does this bug kill small children?"

> Gold
> The software is finished -- and by finished, we mean there are no show-stopping, little-children-killing bugs in it. That we know of. There are probably numerous lower-prority bugs triaged into the next point release or service pack, as well.

> These phases all sound perfectly familiar to me, although there are two clear trends:

> The definition of beta grows more all-encompassing and elastic every year.
We are awfully eager to throw alpha quality code over the wall to external users and testers.
In the brave new world of web 2.0, the alpha and beta designations don't mean quite the same things they used to.

> http://blog.codinghorror.com/alpha-beta-and-sometimes-gamma/

As for the documentation portion: I don't expect, or typically see, complete documentation for a beta. But there should be a fair amount of documentation. For a release candidate, documentation should be roughly complete at that point (but doesn't have to be fully-polished). But I do like the methodology of Documentation-Driven Development (DDD), and perhaps to @SetTrend's point, more TypeScript documentation could be done up-front or earlier. I think it's fine that the engineers are writing the documentation and this takes up some time. In my mind, documentation is a part of a developer's duty.
