### ISSUE TITLE
invariant and failing types infer

### ISSUE THREAD

**Issue by sKopheK** [microsoft/TypeScript#38990]
**TypeScript Version:**  4.0.0-dev.20200607

**Search Terms:** invariant, checkJS, infer

This is JS code, jsconfig.json: **checkJS: true**

After changing standard errors throwing to invariant approach, using this package: https://github.com/zertosh/invariant, I found TypeScript not infering types for properties used in method called in constructor after values are assigned.

**Code**

```js
import invariant from 'invariant';

class A {
  /**
   * @param {object} a 
   * @param {number} b 
   */
  constructor(a, b) {
    this.a = a;
    this.b = b; <-- error here (see Actual behavior)
    invariant(this.fn(), 'err');
  }

  fn() {
    return this.b === 5;
  }
}
```

The problem lies in the interface defined below:

@types/invariant/ts3.7/index.d.ts
```
declare let invariant: invariant.InvariantStatic;

export = invariant;
export as namespace invariant;

declare namespace invariant {
    interface InvariantStatic {
        (testValue: false, format: string, ...extra: any[]): never;
        (testValue: any, format: string, ...extra: any[]): asserts testValue;
    }
}
```

When I leave only the last method definition, it works fine, whatever else is added to the interface causes the above mentioned issue.

**Expected behavior:**
Types of `a` and `b` are correctly inferred, no error is thrown.

**Actual behavior:**
Types of `a` and `b` are not inferred, error `'b' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.ts(7022)` is thrown.

**Playground Link:**  couldn't find an option how to include NPM package in the TS playground

**Related Issues:**  no

**Comment by ahejlsberg** [comment]
This is technically a design limitation. The call signature for `invariant` is overloaded, and because of this full overload resolution is required to figure out which of the two signatures apply. So, to determine the control flow based type of `this.b` in the constructor, we have to know the type of `this.fn()` in overload resolution, which means we need to infer the return type of that function, which means we need to know the type of the `this.b === 5` expression, which means we need to know the type of `this.b`, and presto, we have a circularity.

As you've discovered, commenting out the first overload signature causes the issue to go away because we no longer need to do full overload resolution in the control flow analysis. And, best I can tell, that first signature is completely unnecessary (passing `false` to the second signature has exactly the same effect), so I'd suggest just deleting it and leaving at that.

**Comment by sKopheK** [comment]
hi, got back to TS after half a year and spent another couple of hours catching up on the issues.
found out, it works as expected when `invariant` is called in a separate method. any thoughts?

https://www.typescriptlang.org/play?target=99&ts=4.1.2&useJavaScript=true#code/JYWwDg9gTgLgBMAdgNwIZWKx8BmUIhwDkSaGWMRA3AFA0CmAHpLHACb06oCuANvAGNeqAM4i4AFXoj4Abxpw4AiIhlRuAmNAAUASjjzFimAAtgIgHSM4AXjgAmWgqOl0mbNtPmLIAJ4AxRD0AGmIiXVpFAF86RT9AvQNnRSh6GG4oRDgvS2sbfLgAZki4GJiaAHoKhBQ3CiVUXl44EAhkejZsiDgRejB0VBh6OBxuRE1gFVsAPjhEbvoofCgaIVFxKRl7JMVlVRh1TR19QyMci19bYhN6JohqZLgqmrJ3GE8zS3ig3VCicJKxk+FgENwEAGs9CVyrswZCTo9XOQPOdviEwhFnDCWgEfjsjKl0plssDLvk7EQbncHtEaDEgA
