### ISSUE TITLE
About the use of life files

### ISSUE THREAD

**Issue by vueProgrammer** [microsoft/TypeScript#39069]
I used ts in an old vue nuxt project，When using refs to call component attribute methods, a class class related to the component is defined in the declaration file, and the attributes in the component are added to this class，Below is the code of the famous file
`declare class Choose2 extends Vue {
    topsearch: [{
        [key: string] : string
    }]
}`
Then I introduced the calss class of the declaration file in the ts rewritten page
`import { Choose2 } from '../../vue-shim'`
Then when I use refs, the type of this ref is defined as the imported class
`(this.$refs.choose as Choose2).topsearch[0] = params.name`
Is this standard usage?If not, how to use it is the correct way。Please let me know, thanks

**Comment by ShuiRuTian** [comment]
Hi, this is not an issue of TS in fact.
I think you'd better ask it in https://discord.gg/typescript or StackOverflow.

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
