### ISSUE TITLE
app not initializing with prod build after converting application from angular 8 to angular 9

### ISSUE THREAD

**Issue by chinna510** [microsoft/TypeScript#39072]
Hi, we have an existing application with angular 8. so now we are converting our existing application from angular 8 to angular 9. we have faced some issues while converting but all those errors got solved. we are not facing any issues with dev build but problem with production build. prod build was successful but while opening the application angular app is not initializing.
i have asked in 
[stackoverflow](https://stackoverflow.com/questions/62381891/app-not-initializing-with-prod-build-after-converting-application-from-angular-8?noredirect=1#comment110328011_62381891)

please can any one help me to resolve this issue.
Thanks.

**Comment by orta** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!

**Comment by chinna510** [comment]
sorry! instead of raising issue in angular github by mistakenly i have raised here. this bug can be closed here.
