### ISSUE TITLE
Unable to publish due to baseline difference in `.d.ts` emit

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#39129]
We seem to be hitting some sort of issue with parenthesization on `.d.ts` files. This has been blocking nightly publishes, and will block any sort of beta publish next week.

https://typescript.visualstudio.com/TypeScript/_build/results?buildId=76918&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=00933dce-c782-5c03-4a85-76379ccfa50a&l=139

![image](https://user-images.githubusercontent.com/972891/84962490-d9f05280-b0bb-11ea-8130-c8109e79923e.png)

**Comment by weswigham** [comment]
@rbuckton is this an intended outcome of the node factory work? Should we LKG and accept the difference?

**Comment by rbuckton** [comment]
It could be. Odd though that this didn't show up in the API tests before now.

**Comment by weswigham** [comment]
Iirc, the API tests are consistently captured with the `lib` compiler, so it doesn't appear until you do an LKG (as is done for nightlies and publishes).

**Comment by rbuckton** [comment]
I'm not entirely certain why this changed. `factory.createUnionTypeNode` calls `parenthesizer.parenthesizeConstituentTypesOfUnionOrIntersectionType(types)` which should do the same thing it did prior to moving the API: when unioning `A & B` with `C` it should be parenthesizing it as `(A & B) | C` since our parenthesizing logic for types is fairly aggressive and doesn't take precedence into account.

**Comment by weswigham** [comment]
It's very likely the parenthesizer was never being invoked before, as those return type nodes are normally just copied from the source (since it's an interface)

**Comment by sheetalkamat** [comment]
@weswigham if it was copied from source then it should be copied from source now as well?

**Comment by weswigham** [comment]
It should be! The parenthesizer in the factory may have had other ideas when the `updateUnionType` method was fed back in the  input nodes, though!

**Comment by rbuckton** [comment]
Ah, I discovered the difference, and accepting the change should be fine. In 3.9 we called `parenthesizeTypeParameters` in `declarations.ts` when emitting a type reference:

https://github.com/microsoft/TypeScript/blob/986e9dd252b24d61772d3ddfb1487c43d25025b8/src/compiler/transformers/declarations.ts#L864-L868

And `parenthesizeTypeParameters` would unconditionally create a new `NodeArray` even if there were no changes:

https://github.com/microsoft/TypeScript/blob/986e9dd252b24d61772d3ddfb1487c43d25025b8/src/compiler/factory.ts#L1274-L1286

NOTE: It's not the call to `createNodeArray` but rather the initialization of `params` to a new array here:
https://github.com/microsoft/TypeScript/blob/986e9dd252b24d61772d3ddfb1487c43d25025b8/src/compiler/factory.ts#L1276

By returning a new `NodeArray` here, we end up creating *new* nodes starting at `NodeArray<TypeNode>` in the union `SignatureDeclaration & {typeArguments?: NodeArray<any>} | undefined`, which triggers us to hit our over-aggressive parenthesization logic.


One of the node factory changes was to move the `parenthesizeTypeParameters` logic into the factory, as we do with all other parenthesis rules:

https://github.com/microsoft/TypeScript/blob/fe33e618237d774af4c2b0416b24182b8977ac78/src/compiler/factory/nodeFactory.ts#L1626-L1632

In the updated parenthesizer rules, we use `sameMap` instead of allocating a new array:

https://github.com/microsoft/TypeScript/blob/fe33e618237d774af4c2b0416b24182b8977ac78/src/compiler/factory/parenthesizerRules.ts#L398-L402

This results in us just reusing the original node since there are no changes in the type reference.

**Comment by rbuckton** [comment]
I just pushed up #39173 which runs LKG and accepts the new API baselines.

**Comment by rbuckton** [comment]
Publish is working again:
![image](https://user-images.githubusercontent.com/3902892/85214663-e0ccce80-b322-11ea-8002-9576854dbc50.png)
