### ISSUE TITLE
JSDoc union types not narrowed down by control flow statements

### ISSUE THREAD

**Issue by marvinhagemeister** [microsoft/TypeScript#39159]
**TypeScript Version:**  4.0.0-dev.20200615

**Search Terms:** JSDoc union types

**Expected behavior:** Union type of `obj` is narrowed down by control flow statements.

**Actual behavior:** Union type of `obj` is not narrowed down. Works if the code is converted to TypeScript though.

**Related Issues:** no

**Code**
```ts
/**
 * @typedef {{type: null, value: "foo"}} Foo
 */

/**
 * @typedef {{type: string, value: "bar"}} Bar
 */

/**
 * @param {Foo | Bar} obj
 */
function run(obj) {
    if (obj.type === null) {
        // Should error
        return obj.value === "bar"
    } else {
        // Should error
        return obj.value === "foo"
    }
}
```

<details><summary><b>Output</b></summary>

```ts
// Using JavaScript, no compilation needed.
```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": false,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": true,
    "allowJs": true,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/index.html?ts=4.0.0-dev.20200615&ssl=1&ssc=1&pln=20&pc=2&useJavaScript=true#code/PQKhCgAIUgBAXAngBwKYBNUDNIG9dJoBckAdgK4A2lANJAG4CGl5qJARFgPZfsC+fSADEeUEMHDhQEaHEIZseAijaQAzvABOAS1IBzOkxar2AI0ab+ggEIWxEqWDFxkFxgFs8IrpAA+kW01BLlMAK3twLHJSAGN4bS5SSE1ogAoQ0IBKPChIPO0cdLCAOnlIAF5KsipKbNxcvMbIYGBIAGUACy4qdEhUTU0uTQam5NR4ck0kjOKjVgqqswt2EcFUSjVUHNHGlvaunr6BoZGmzXHJ6ZK5rcryyE4eFaa+cD4gA)

**Comment by ShuiRuTian** [comment]
really strange. On local, I could see the type is narrowed and the error is reported.

**Comment by IllusionMH** [comment]
Looks like you need to enable `"strictNullChecks": true`.
Otherwise you won't have errors even in [TS Playground](https://www.staging-typescript.org/play?strictNullChecks=false&ts=4.0.0-dev.20200615#code/C4TwDgpgBAYg9nKBeKBvUkBcUB2BXAGwIBooA3AQwLwmwCIAzBOgXwG4AoDaAIQoCdkabtgDOwfgEscAc1KVqtKHQBGA1pw4M8OAMbBJcHFH46AFHBUArbPEQAfKH34BKNByieokhlAvWAOm5kJBR8IjdUDy8YgHpYqABlAAs4QgATKAh+fjh+aJjPfghgPH5jSysAhRoQlFV1AqgWLIJRaCjCr3ik1IysnLymmOLS8qhK6qpa0PqmODomlg4WIA)

[JS Playground](https://www.staging-typescript.org/play?strictNullChecks=true&ts=4.0.0-dev.20200615&useJavaScript=true#code/PQKhCgAIUgBAXAngBwKYBNUDNIG9dJoBckAdgK4A2lANJAG4CGl5qJARFgPZfsC+fSADEeUEMHDhQEaHEIZseAijaQAzvABOAS1IBzOkxar2AI0ab+ggEIWxEqWDFxkFxgFs8IrpAA+kW01BLlMAK3twLHJSAGN4bS5SSE1ogAoQ0IBKPChIPO0cdLCAOnlIAF5KsipKbNxcvMbIYGBIAGUACy4qdEhUTU0uTQam5NR4ck0kjOKjVgqqswt2EcFUSjVUHNHGlvaunr6BoZGmzXHJ6ZK5rcryyE4eFaa+cD4gA) see Errors tab.
No errors are reported in editor so you won't see them in current playground.

**Comment by marvinhagemeister** [comment]
That makes sense didn't found such a panel in the current site. Glad to see it was added for the next iteration 👍
