### ISSUE TITLE
Type guard on value's property does not apply to value itself

### ISSUE THREAD

**Issue by yw662** [microsoft/TypeScript#39168]
**TypeScript Version:**  3.9.5

**Search Terms:**

**Code**

```ts
let sth: { a: number | string };
let sth_else: { a: number } | { a: string };
sth = { a: 1 };
// This doesn't work: However it is another issue.
// sth_else = sth;
sth_else = (Math.random() > 0.5) ? { a: 1 } : { a: '1' };

let number_only: { a: number };

if ((typeof sth.a) === 'number') {
    number_only = sth;
}
if ((typeof sth_else.a) === 'number') {
    number_only = sth_else;
}
```

**Expected behavior:**
Both if-statements should pass.
**Actual behavior:**
`Type '{ a: string | number; }' is not assignable to type '{ a: number; }',`
and
`Type '{ a: number; } | { a: string; }' is not assignable to type '{ a: number; }'.`
**Playground Link:** 
https://www.typescriptlang.org/play/index.html?ts=4.0.0-dev.20200615&ssl=1&ssc=1&pln=17&pc=1#code/DYUwLgBAzmAWBcEDeECGiB2BXAtgIxACcIAfaMQgSwwHMIBfAbgChRIZYB9EYKERFOgjZ8RBqWRpEMKrQYsOEALyShARnnMA9FogAVWJSgQAJgHsQUDAHJIAdzOEA1ogASZuyABuYypCNoGGZwvlBQWCAAdNq6HNy8IMrksApw8XxJABQAsqhwkYSoGOY4mQCUEAB8EAAMkQCsFQD8qoga9BACUhDWataarODCuASEnGYYwACeXUIiowOUAGYQmZlgUwAOIGYrHJGoFUrHPfNE1hVIzBA3w6JjE9NJHCz0zMur61s7e2k8fAcjidrGdCBdkNdbqDxpMps8-glXkA

**Related Issues:** 

#37883

**Comment by RyanCavanaugh** [comment]
See #10065

**Comment by thorn0** [comment]
Another example ([playground](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=14&pc=2#code/C4TwDgpgBAglC8UDeUBmB7dAuKBnYATgJYB2A5gNxQBGAhgQPw77HlQC+FAUKJFAEIJkaTM0KlKNemNZkOUAD7CM2POPJU6BHAFcSAEwipSEfR25dDAYwA29aKj1XgRdCTQAKemRwoVMiU1pNVkOAEocADd0In0LazsCaBsIYChaHBgAGhocfgsiVCgvADotKABCeEQ9Q2MSUzDkLihWz1owqgB6LqgAUQAlAYB5AcyCMh0AWwgSNPQi3mgAchhlqCJcKBJ0NNpcXCIyElpqFKhgdCgweloZ4AgCKAWL8BW-URDAqW0vjQ5llx2FwuIVitQyvRKtUoLUjCZ9E0kC02qgPNROkCgA)):
```ts
type A = { foo: string; bar?: string };
type B = { foo: string; bar: string } | { foo: string; bar: undefined };

declare function f(arg: { foo: string; bar: string }): void;

declare let a: A, b: B;

if (a.bar !== undefined) {
    f(a); // ERROR: Argument of type 'A' is not assignable to parameter of type '{ foo: string; bar: string; }'
}

if (b.bar !== undefined) {
    f(b); // OK!
}
```
I expected the types `A` and `B` to behave identically, but turns out it's not the case.
