### ISSUE TITLE
Control compiler evaluation depth limit

### ISSUE THREAD

**Issue by omerman** [microsoft/TypeScript#39160]
## Search Terms

evaluation depth limit, compiling depth limit, control compiler evaluation depth limit

## Suggestion

I would like to see a compiler option key such as `typeCompilationDepth` that is configurable,
I guess by default it would be something around 5/6 and I'd be able to set it as such
`typeCompilationDepth: 15`

## Use Cases

Sometimes I'm writing complex types, and when I hover a type definition for a variable I want to see the evaluated definition and not something like `Pick<Required<Omit<... 10 more...>>>`.

For example:

## Examples

![image](https://user-images.githubusercontent.com/6780529/85117903-3e302500-b228-11ea-9480-77b6083fe196.png)
Notice that `X` is evaluated correctly(fully)

![image](https://user-images.githubusercontent.com/6780529/85117985-5738d600-b228-11ea-91f8-9568b8234f75.png)
Notice that `O` is not evaluated in full, `O` is partially readable, and is only an example,
sometimes I have even more complex cases, and the type is totally unreadble.

So, I'm hoping for a compiler option to set the limit of the evaluation,

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by dragomirtitian** [comment]
This issue is just one of printing types as far as I understand it, not necessarily one of type correctness (the types work the same way even if they are  printed out in an 'ulgy' way). You can force the expansion of a type using this type alias:

```ts
interface Person  {
  name: string, 
  age: number;
  lastname: string, 
}
type ChangeType<T, K extends keyof T, TNew> = Omit<T, K> & Record<K, TNew>
type P = ChangeType<Person, 'age', string> // Pick<Person, "name" | "lastname"> & Record<"age", string>
type Id<T> = {} & {
  [P in keyof T]: T[P]
}

type Simpleified = Id<P>
// Tooltip as
// type Simpleified = {
//     name: string;
//     lastname: string;
//     age: string;
// }
```
[Playground Link](https://www.typescriptlang.org/play/?ssl=18&ssc=5&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgArQM4HsTOQbwCg8Q4BbCALmQzClAHMAaZY5OBq5EAVzICNoAbjYAbOLVIVqteiGasAvoTABPAA4oAwgAs48iABUNEADyGWAaWQQAHpBAATDMgDWEVVhjILPgHIQAO4AfMgAvMgA8mTAYOZWoQBkyABKEAhYUI6mliyGASEqJmjhyLr6nMaapuhQ2CAsAOQcEI0ssoyhAPRdaMAIrjWYOCwARFIQo8gAPsij4pLkk0mp6ZnZoy2j7XSdRZrIAJLZhqER+IrIyUR4ANqoyKBuHl4+ALrUhvdvhMr7KABlYBkdSiCDAGDACCOUrHGrBQg9HxYLCiMDAdTsDCI3pqA5AkFgiFQmHnHF4CkTGS7eQiJEU5ALMBUmg0hh03oMlrUuTs8mKIA)

**Comment by omerman** [comment]
@dragomirtitian You rock. thank you!
