### ISSUE TITLE
[Feature Request] Compile TypeScript .ts code into WebAssembly as AssemblyScript did

### ISSUE THREAD

**Issue by redradist** [microsoft/TypeScript#39193]
I want to renew discussions on https://github.com/microsoft/TypeScript/issues/15837
`AssemblyScript` team has been proven that actually it is possible !!

It would be nice to have only one compile like `Typescript` and be able to compile to `JavaScript` and `WebAssembly`

Actually I do not think that other platforms are needed, because `WebAssembly` could be compiled then to any specific platform architecture  ;)

**Comment by RyanCavanaugh** [comment]
Duplicate #9202

**Comment by redradist** [comment]
> 
> 
> Duplicate #9202

I know that there are lots the identical issue ... but they are all closed ... but topic is very interesting and all this issues was discussed a long time ago when there was not `AssemblyScript` ;)

**Comment by RyanCavanaugh** [comment]
Things that were out of scope a few years ago are still out of scope today; the goals of this project have not shifted.

**Comment by 7ombie** [comment]
I didn't want to open a new issue, but would appreciate this being reopened (and slightly repurposed).

I've tried to start a conversation a few times over the years (since the Late CoffeeScript Era), hoping to improve the user experience (in the browser) for languages that compile to JavaScript. I was repeatedly told that we have a solution already, which is Web Assembly, but we just need GC, and that depends on a couple of things, which depend on other stuff, so basically, wait five or ten years.

It's been five or ten years, GC is in Chrome (behind a flag), and TypeScript (the only major language that compiles to JS) is still committed long-term to compiling to JS source code, with no intention of *ever* compiling to JS bytecode.

It would be helpful to have a clear statement from the TypeScript devs that assures the community that the devs have no plans to ever compile to Web Assembly, so we can then justify at least discussing features that improve life for users of languages like TypeScript, that are going to be compiling to JS long into the future.

**Comment by RyanCavanaugh** [comment]
> It would be helpful to have a clear statement from the TypeScript devs that assures the community that the devs have no plans to ever compile to Web Assembly

We've been rejecting requests to compile to web assembly for a decade now. #375, #1151, #1234, #15837, #16617, #34990. What kind of statement are you looking for?

**Comment by 7ombie** [comment]
Ah, thank you. I was given a different impression, and wasn't aware of those prior requests. That's ideal.
