### ISSUE TITLE
@deprecated appears for any element access that might access a deprecated member

### ISSUE THREAD

**Issue by andrewbranch** [microsoft/TypeScript#39246]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:** deprecated element access

**Code**

```ts
interface Foo {
	/** @deprecated - use `fullName` */
	full_name: string;
	fullName: string;
	email: string;
}

function getFromFoo(foo: Foo, key: keyof Foo) {
	return foo[key];
}
```

**Expected behavior:**

Don’t bother me

**Actual behavior:**

<img width="540" alt="key is crossed out in 'foo[key]'" src="https://user-images.githubusercontent.com/3277153/85635742-80e06b80-b633-11ea-803f-c922202515b7.png">

[**Playground Link**](https://www.typescriptlang.org/play/?ts=4.0.0-dev.20200623&ssl=1&ssc=1&pln=10&pc=2#code/JYOwLgpgTgZghgYwgAgGIHt3IN4CgCQA9AFTHIACAJhAA5QQJySXIC0yArgM4oAGMHADaCAcnAC2EXsmKECA4QH0QEiAC5kXMFFABzANzyho1Rq06QBghHFxggs9r2GAvrlwCQCMMHQhkuhBgqFDo4hjoABQwmBoRADTIANYQAJ4aKanoMGiYAJQ4BPRgHFD+MegA2pkAuq5AA)

**Related Issues:** #33092, #38523

**Comment by Kingwl** [comment]
Thanks! I‘ll take a look

**Comment by luke-john** [comment]
This seems like the behaviour you'd want, otherwise the advantages of deprecating disappear.

I would expect the use of Exclude to be required in the provided example to avoid the message.

```ts
interface Foo {
	/** @deprecated - use `fullName` */
	full_name: string;
	fullName: string;
	email: string;
}

function getFromFoo(foo: Foo, key: Exclude<keyof Foo, 'full_name'>) {
	return foo[key];
}
```

[Playground Link](https://www.typescriptlang.org/play/?ts=4.0.0-dev.20200623&ssl=10&ssc=2&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgGIHt3IN4CgCQA9AFTHIACAJhAA5QQJySXIC0yArgM4oAGMHADaCAcnAC2EXsmKECA4QH0QEiAC5kXMFFABzANzyho1Rq06QBghHFxggs9r2GAvrlwCQCMMHQhkuhBgqFDo4hjoABQwmBoRADTIANYQAJ4aAKIAHgiCHNQAPCmp6DBomIkA5AqCyqqVAHwAlDgE9GAcUP4x6ADaxQC6rkA)
