### ISSUE TITLE
Got too many ".prototype" in the generated JavaScript code

### ISSUE THREAD

**Issue by JiajieBao** [Microsoft/TypeScript#3929]
I am writing a JavaScript library using TypeScript, which requires the generated code to be as short as possible.

However, when I write a class with hundreds of methods, the generated code contains hundreds of "someclass.prototype" in the method definitions, which can not be minified. 

Is there a compile option to first assign the "someclass.prototype" to a variable, then use "thatvariable.methodname" in the method definitions?

**Comment by RyanCavanaugh** [comment]
No. We generally don't minify on emit and it's hard to imagine that this would be a significant enough savings for the amount of work we'd have to do. And if size is really important, your library will be gzipped anyway, at which point the existence of a long string 'prototype' is irrelevant because all but the first instance will be compressed as backreferences.
