### ISSUE TITLE
Property and rest parameter?

### ISSUE THREAD

**Issue by billccn** [Microsoft/TypeScript#3931]
(Sorry if this has been reported before. Darn hard to search.)

```
class A {
    constructor(public ...x: any[]) {}
}
```

Doesn't work

**Comment by RyanCavanaugh** [comment]
Doesn't work because it's not a legal production. A parameter can be a parameter property, or rest, but not both. Just a complexity trade-off since this is pretty rare.

**Comment by kayahr** [comment]
I stumbled over the same limitation and don't understand it. I want to do this:

    class BoundFunction {
        constructor(private func: Function, private context: Object = null, private ...args: any[]) {}
    }

But because the compiler doesn't like this I had to do this:

    class BoundFunction {
        private args: any[];
    
        constructor(private func: Function, private context: Object = null, ...args: any[]) {
            this.args = args;
        }
    }

in my opinion this is an inconsistent behavior of the compiler. The `args` Parameter is a parameter like any other parameter. It's simply an array parameter. So it would be nice if the compiler could treat it as any other parameter and allow visibility keywords in front of it to declare it as a property so I don't have to convert this single parameter into a property manually.
