### ISSUE TITLE
Unexpected behavior with undeclared variable in JS file

### ISSUE THREAD

**Issue by ftolstykh** [microsoft/TypeScript#39341]
**TypeScript Version:**  3.9.2

The code
```ts
a;
```
is generate the error
```
Cannot find name 'a'.
```
at this single line: `a` is undeclared variable of `any` type and it is expect.
But after edit code like this
```ts
a;
a[0] = 0;
```
the error is disappear and `a` is become to `module a`.

**Expected behavior:**
`a` is still undeclared variable.

**Actual behavior:**
No errors.

**[Playground Link](https://www.typescriptlang.org/play?noImplicitAny=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false&esModuleInterop=false&declaration=false&experimentalDecorators=false&emitDecoratorMetadata=false&target=0&jsx=0&module=0&ts=3.9.2&useJavaScript=true#code/IYbgsAUA9FwNoAYC6ACAvChIg)**

**Comment by sandersn** [comment]
A top-level assignment `a[0] = 0` is treated as an expando assignment, even if `a` is not defined in the current file. It might be defined in some other file that's not part of the compilation. This allows us to provide completions for Javascript code that are frequently incomplete.

We probably shouldn't do this inside an ES module, and *maybe* not when `strict: true`. But, overall, top-level assignments are rare enough that it's not been a problem.

I'm going to close this for now; let me know if you saw this in an ES module because it might be worth the effort to disable the behaviour there.
