### ISSUE TITLE
Typescript auto-complete not working in VSCode

### ISSUE THREAD

**Issue by JackkGC** [microsoft/TypeScript#39370]
I'm trying to make use of Puppeteer within a ts file which works fine except the VSCode Intellisense stops working a soon as I'm inside a .ts and not a .js file.
I've seen some posts about this incident but none could help me. What I did:

 - created a project via npm init 
 - installed dependencies as follows:

```
    "dependencies": {
    "@types/node": "^14.0.14",
    "events": "^3.1.0",
    "puppeteer": "^4.0.1",
    "typescript": "^3.9.5" }

      "devDependencies": {
    "puppeteer-tsd": "0.0.2"  }
```
 - created tsconfig.json

```
 "target": "es5",
 "lib": ["es2015", "dom"],
 "outDir": "./dist",
   .
   .
   .
  "include": ["src/**/*", "node_modules/puppeteer-tsd/src/index.d.ts"]
```

- created src and dist folder
- put a main.ts inside my src
- told VSCode to use the project TS version instead of its own

Then I compiled. Everything works fine. But I get no IntelliSense to help me out while I type.
So I created a .js file in my src directory, copied the code from my main.ts inside it and then I got Intellisense to work perfectly fine with all suggestions and so on. And I have no idea left what I could try except accepting it and code without it.
I'd be greatful for any suggestions on what could be the issue. Thx in advance!

Meanwhile I found out, that it works fine with non imported functions like console.log(). It's only Puppeteer (or probably any imported module).

[Heres a Link to my Log File.](https://pastebin.com/8JX3rGqF)

**Comment by mjbvz** [comment]
@JackkGC Thanks. Can you please provide specific steps to reproduce this using using the project? I see IntelliSense working fine in the TS file:

<img width="1743" alt="Screen Shot 2020-07-01 at 6 00 22 PM" src="https://user-images.githubusercontent.com/12821956/86304772-bd2c4280-bbc4-11ea-9c81-fbd0d17e7c06.png">

**Comment by JackkGC** [comment]
It partially works. For example if you try to auto-complete the page.setViewport function a few lines below you'll hopefully be able to reproduce the error. Then trying the whole thing in a normal js file in the same directory with the exact same code should work.

**Comment by sean-chase** [comment]
Same issue as @jtsom in every Angular 10 application I create on different machines, both Windows and Mac.

**Comment by jtsom** [comment]
It's not so much intellisense not working, it's failing to automatically find other files that need to be imported (auto-import). Normally, in my example above, VSCode would have automatically added a 
```
import { Contact } from '../contact';
```
or would offer, in the Fixes, to add the import. It does neither, except show the Typescript error

**Comment by mateusz-pietrzak** [comment]
Does intellisense starts working if you include let's say Contact class in any other file?

I noticed something similar with Angular 10, if file is not included in compilation it will not show up on intellisense, as soon as it's referenced anywhere it will start working.

**Comment by jtsom** [comment]
Again.. it's not really intellisense that's the issue, it's the fact that VSCode can't find the files to enable the auto import. Here's a little more of the layout of a sample:

![image](https://user-images.githubusercontent.com/13488/86609224-a5b0d900-bf79-11ea-81ca-bbce8dd4c9a9.png)

Note that it's showing "no quick fixes available" .. that should be, and it used to be (something like) "... add import of Contact ...". Or ideally, it would have automatically added the import line as soon as I typed line 13.

I don't know if it's something to do with the way Angular changed the structure of the tsconfig files, or what the issue is.

**Comment by jtsom** [comment]
I did a quick test. Angular 10 moved to a "solution-style tsconfig.json" - https://angular.io/guide/migration-solution-style-tsconfig.

In the tsconfig.app.json, a standard Angular 10 app has:

```
{
  "extends": "./tsconfig.base.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "types": []
  },
  "files": [
    "src/main.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.d.ts"
  ]
}
```

Once I changed the include like to be:
```
  "include": [
    "src/**/*.d.ts",
    "src/**/*.ts"
  ]
```

The quick fix now works, as well as the auto-import of the file:

![image](https://user-images.githubusercontent.com/13488/86609865-8a929900-bf7a-11ea-80a3-ac02762823c6.png)


So this must be a result of this change to the tsconfig files in Angular 10.

Off to open an issue there...

**Comment by jtsom** [comment]
While adding the item to the tsconfig.app.json does fix the auto-import and quick fix, it horribly breaks building the application, so that's not an acceptable solution.

This does look like an Angular 10 issue: https://github.com/angular/angular-cli/issues/18040

**Comment by ArturKwiatkowski** [comment]
Hey I was having the same issue in a brand new Angular 10 project. When typing @Injecta.... there was no Intellisense when it comes to the `imports` at the top of the file. 

So I did some checks in those new funky tsconfigs. Seems they are very strict when it comes to telling VSCode about project files.

Try dropping `files` and `include` in exchange to `exclude` and then reopen your VSCode.

My `tsconfig.app.json` after changes looks like this:
```
{
    "extends": "./tsconfig.base.json",
    "compilerOptions": {
        "outDir": "./out-tsc/app",
        "types": []
    },
    "exclude": ["src/test.ts", "src/**/*.spec.ts"]
}
```

This works because as we can read from the magnificent VSCode tips:

_If no 'files' or 'include' property is present in a tsconfig.json, the compiler defaults to including all files in the containing directory and subdirectories except those specified by 'exclude'. **When a 'files' property is specified, only those files and those specified by 'include' are included.**_

Cheers!

**Comment by sheetalkamat** [comment]
The issue here seems to be that `tsconfig.app.json ` does not include new file into the configured project as it explicitly lists files that should be and till you import new file it wont be part of the configured project.  The issue is with configuration file and how it is structured.
Is new file suppose to go to tsconfig.app.json or tsconfig.spec.json or something else is not clear to derive either so there isnt much we can do.

**Comment by jtsom** [comment]
Oh so the movement is to just close it. Thanks for the help 😡

**Comment by JackkGC** [comment]
My original issue even hasn't got anything to do with Angular, btw. :(

**Comment by RyanCavanaugh** [comment]
There are a lot of people reporting a variety of things here that all seem fairly unrelated. If you have a concrete problem you can describe that doesn't match the description Sheetal gave, please log a new issue with clear repro steps that we can use to investigate further.
