### ISSUE TITLE
Provide official NuGet versions packages

### ISSUE THREAD

**Issue by bsouid** [Microsoft/TypeScript#3940]
Hi team,

Thanks a lot for providing an official NPM package. That certainly comes in handy when building web apps on a lot of platforms.

However a lot of projects are using TypeScript in conjunction with Asp.NET and those projects typically already use NuGet for package management. It would be easier for those projects to use a single system. 

I realize that providing NuGet packages will result in more cost to maintain two sets of packages but it may be worth it; please prioritize accordingly.

There are two different unofficial packages out there but neither has updated to v1.5 yet and it would perhaps be better to have at least one core team member as a collaborator on those.

Thanks.

**Comment by leonardochaia** [comment]
##### +1 to this. It's a real need. 
Regarding the unofficial packages, one of the has updated to v1.5, but unfortunately it's missing locale files, which ends up in an unsuccessful build.
Thanks,
Leo.

**Comment by RichiCoder1** [comment]
I'm curious why you'd need a TypeScript package for ASP.NET? In AspNet current you can use VS's built in MSBuild support and in AspNet you can use the NPM/Gulp/Grunt supper. A NuGet package almost seems redundant.

**Comment by leonardochaia** [comment]
Well, when new developers join my development team, they only requirement is Visual Studio right now.
Other reason is that my build server already has VS installed, so packages just work, without the need of installing extra packages managers.
Besides, **I really don't want to install NPM just to download Typescript** compiler, and the only way available for my project is to use the supplied installer.
And also, since NuGet is the official Visual Studio package manager, It should already be there.

**Comment by liquidsnk** [comment]
I'm also interested in this for the reasons stated above, for us trying to reduce setup and to rely solely on visual studio being installed would be very helpful.

**Comment by RichiCoder1** [comment]
Are you expecting NuGet to provide the msbuild support required for typescript?

**Comment by paulvanbrenk** [comment]
I published a couple of NuGet packages to [https://www.myget.org/users/typescriptteam](the new TypeScript page on MyGet.org).

The following packages are published: 
* Microsoft.TypeScript.Compiler, this contains just the compiler
* Microsoft.TypeScript.MSBuild, this contains the MSBuild tasks, target files, and the compiler

Although the version of the packages is 1.7-rc, the components are the 1.7 RTM components. I marked the packages as RC, since this is their first release and we're explicitly looking for feedback on them. In the future we plan to publish the RTM bits to NuGet and have nightly builds on MyGet.org.

With that, let me know how we can make them better and more useful for you. 

You can access the packages in VS by adding a 'package source' in Tools > Options.

![image](https://cloud.githubusercontent.com/assets/5273975/11798594/0fe53e94-a281-11e5-982f-43b7c9fd98b4.png)

**Comment by paulvanbrenk** [comment]
Official stable packages are available here:
* [Microsoft.TypeScript.Compiler](https://www.nuget.org/packages/Microsoft.TypeScript.Compiler/)
* [Microsoft.TypeScript.Build](https://www.nuget.org/packages/Microsoft.TypeScript.Build/)

And nightly packages here:

* [TypeScript-Preview](https://www.myget.org/gallery/typescript-preview)
