### ISSUE TITLE
Null coalescing operator for "void" produces "void | null" type

### ISSUE THREAD

**Issue by PlonkaAdam** [microsoft/TypeScript#39449]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:** null coalesce void, void null, void is not assignable

**Code**

```ts
function a(): void | string {
}

function b(): null | string {
   return a() ?? null;
}
```

**Expected behavior:**
Should compile with no errors, resulting type is "null | string"

**Actual behavior:**
Error:
```
Type 'string | void | null' is not assignable to type 'string | null'.
  Type 'void' is not assignable to type 'string | null'.(2322)
```
Resulting type is "null | void | string"

**Playground Link:** [Playground Link](https://www.staging-typescript.org/play?#code/GYVwdgxgLglg9mABAQwBQEoBciBucYAmiAPogM5QBOMYA5ogN4BQAvk06JLAogEYbYwIADbCS5KjXrNEsxAHp5iEGSmJKAUzIioiAFbIcyMhGoAHXccRQAnma2mYFxAHc4lANZlEwGhqZyCgBUAYFyRpSIAPrIANyhYeoaUCCUSKgxiAC8KBjoiACEWTlCoogAZOXRyIXFuPhEAAyIAPzViIIiwvGBQfLsgZopabn5LW2l3axAA)

**Related Issues:** didn't find any related issues

**Comment by MartinJohns** [comment]
Duplicate (or at least heavily related): #35236 / #35850.

A `void` return type does not mean "_nothing_". It means "_anything, but you shouldn't use this for anything_". It could be a `undefined`, but it could just as well be a `string`. It can be truthy or falsy.

https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-returning-non-void-assignable-to-function-returning-void

---

IMO this should actually error due to #26262.

**Comment by PlonkaAdam** [comment]
This is the javascript code produced by the typescript code above

```ts
var _a;
var b = (_a = a()) !== null && _a !== void 0 ? _a : null;
```

b is of type `string | null` and not `string | null | void`
Shouldn't typescript be consistent with resulting javascript?

**Comment by RyanCavanaugh** [comment]
It's legal for `a` to (indirectly) return `0`, for example, which would cause `b` to return `0` which is neither `null` or `string`.

See also https://stackoverflow.com/questions/58885485/why-does-typescript-have-both-void-and-undefined/58885486
