### ISSUE TITLE
4.0: Assigning dynamic property in spreaded object with index signature adds `| undefined` type to properties

### ISSUE THREAD

**Issue by thwonghin** [microsoft/TypeScript#39494]
**TypeScript Version:**  4.0.0-beta

**Search Terms:** 

**Code**

```ts
interface Foo {
    [key: string]: string;
}

const bar = {
    key: 'value',
};

const foo1: Foo = {
    one: 'test',
};

// Type '{ [x: string]: string | undefined; }' is not assignable to type 'Foo'.
//   Index signatures are incompatible.
//     Type 'string | undefined' is not assignable to type 'string'.
//       Type 'undefined' is not assignable to type 'string'.(2322)
const foo2: Foo = {
    ...foo1,
    [bar.key]: 'test', 
};
```

**Expected behavior:**
`foo2` still compatible with  `Foo` interface. (As in 3.9.x)

**Actual behavior:**
`foo2` is incompatible with `Foo` interface because the properties are added `| undefined` type.

**Playground Link:** https://www.typescriptlang.org/play/?ts=4.0.0-beta#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChkHIDaA1hAJ4BcyAzmFKAOYC61dDIjA3LgL664E6EHWQAjOFGQBeHPkJkqyAOQA3OABsArhGUAaPj0HDRMTAEZqGLLLyFkwiNWWQ6+wwKEiwyM+gBMVpgycvYAdBF+5gb2RBJQYYqsKq5g7rw8QA

**Related Issues:**

**Comment by 0rvar** [comment]
We're having this issue too.
More information:

**TypeScript Version:**  4.0.0-beta


**Search Terms:** Record, Spread, Undefined, Index signatures are incompatible

**Code**

```ts
const reduce = (state: Record<number, number>, id: number): Record<number, number> => ({
  ...state,
  [id]: 3,
});
```

**Expected behavior:**
The above typechecks on TS 3.9.x

**Actual behavior:**
Error:
```
Type '{ [x: number]: number | undefined; }' is not assignable to type 'Record<number, number>'.
  Index signatures are incompatible.
    Type 'number | undefined' is not assignable to type 'number'.
      Type 'undefined' is not assignable to type 'number'.ts(2322)
```
**[Playground Link](https://www.typescriptlang.org/play/?ts=4.0.0-beta&ssl=1&ssc=1&pln=4&pc=67#code/MYewdgzgLgBATgUwCYFdgJgXhgCmgQygQC4YAlBUOJAHjBQFsAjBOAGhnudYD4OBLJKS4s4ASlIUqtEaw6y4PLEpwBvAFAwYAOl0EibTTADaggLqkAzIYC+YgNzqgA)**

**Comment by andrewbranch** [comment]
This is already fixed in typescript@next; I’m adding a test for it.
