### ISSUE TITLE
Diagnostic message contains a stray "[object Object]"

### ISSUE THREAD

**Issue by whatisaphone** [microsoft/TypeScript#39524]
**TypeScript Version:**  v4.0.0-dev.20200708

**Search Terms:** implicitly index signature map get

**Code**

```ts
interface Foo {
    bar: Map<string, string>;
}

declare const foo: Foo;

const nom = foo.bar['nom']; // error on this line
```

**Expected behavior:**

The error should say:

>Element implicitly has an 'any' type because type 'Map<string, string>' has no index signature. Did you mean to call 'foo.bar.get'?

**Actual behavior:**

The error says:

>Element implicitly has an 'any' type because type 'Map<string, string>' has no index signature. Did you mean to call 'foo.**[object Object]**.get'?

**Playground Link:** 

[Playground Link](https://www.typescriptlang.org/play/?target=7&ts=4.0.0-dev.20200708&ssl=1&ssc=1&pln=7&pc=28#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChkHIBGcUAXMgLJwAOAPAM5hSgDmANMkyyKwHwBuXAF9cuACYQEAG1IoE6EE2QxMFDOiG4FSsMhDoAtsgC8KzADoSUANoByA4bsBdAUA)

**Related Issues:**

**Comment by IllusionMH** [comment]
@RyanCavanaugh @elibarzilay can I take an attempt on this one? PR will be in 30-40 min

**Comment by RyanCavanaugh** [comment]
@IllusionMH that'd be wonderful!

**Comment by a-tarasyuk** [comment]
@IllusionMH Sorry didn't notice you message. I can Close PR in favor of your.

**Comment by IllusionMH** [comment]
Typed PR message. So close... 😄 

@a-tarasyuk I think your will be preferable because I wasn't aware of `entityNameToString` and used `unescapeLeadingUnderscores(expr.name.escapedText)` to match approach existing in same function
https://github.com/microsoft/TypeScript/blob/03c79d7422f77b286b9e4c7576b5bde873056551/src/compiler/utilities.ts#L4764
Maybe make sense to align them?
