### ISSUE TITLE
Numeric separated literals should disallow zero leading

### ISSUE THREAD

**Issue by MaxGraey** [microsoft/TypeScript#39563]
**Search Terms:**
numeric separator

[spec test for checking leading zero separated literal](https://github.com/tc39/test262/blob/master/test/language/literals/numeric/numeric-separators/numeric-separator-literal-nzd-nsl-dds-leading-zero-err.js)

**Code**

These literals should be invalid: 
```ts
0_0
0_0.0
0_0e0_0
0_0_1
```

but this should valid:
```ts
1_0.0_1 // 10.01
1_0e0_1 // 100
```

**Expected behavior:**
SyntaxError: Numeric separator can not be used after leading 0.

**Actual behavior:**
```ts
0_0     // -> 0  valid but shouldn't
0_0.0   // -> 0  valid but shouldn't
0_0e0_0 // -> 0  valid but shouldn't
0_0_1   // -> 1  valid but shouldn't. Btw 001 is invalid in strict mode

1_0.0_1 // -> 10.01 ok
1_0e0_1 // -> 100 ok
```
[playground](https://www.typescriptlang.org/play/#code/PTAEGcAsHsFcBsAmoCWA7AbgQ3ixAuAKAAYB9Yk8gOgrOIFM7DCRRtdFCBGasr78o1JcgA)

**Comment by IllusionMH** [comment]
Browsers have different behavior in case of `00_1` or `077_77`:
Chromium reports `Uncaught SyntaxError: Invalid or unexpected token`
SpiderMonkey reports `Uncaught SyntaxError: numeric separators '_' are not allowed in numbers that start with '0'`

Currently TS parses it as 2 tokens: `NumericLiteral` `00` (with `Octal` flag) and `Identifier` `_1` (because `scanOctalDigits` will stop on `_`) and therefore [reports 2 errors](https://www.staging-typescript.org/play?#code/AzD6EYg): `Octal literals are not allowed in strict mode.` and `Cannot find name '_1'.`

Question is: Should fix for this issue should handle only cases `0_` (and process `00_` as it currently does) or `00_` as well (and report error similar to one from SpiderMonkey)? If later - this might break bad code.

**Comment by IllusionMH** [comment]
@RyanCavanaugh I'd like to take on this issue.

[According to spec test it should be an syntax error](https://github.com/tc39/test262/blob/master/test/language/literals/numeric/numeric-separators/numeric-separator-literal-lol-00-err.js) so I'll update `scanOctalDigits` to skip over `_` or just use `scanBinaryOrOctalDigits`.
This will be "breaking change" for already invalid code.

> Strange that TS doesn't report An identifier or keyword cannot immediately follow a numeric literal. for 00_O1 but does for 0_O1.

Will create separate issue to report errors in this case.

Do you have any objections?
If that "breaking change" is not feasible - fix for `An identifier or keyword cannot immediately follow a numeric literal.` error should be noticeable enough for cases like `00_1` or `077_77`

P.S. I hope @a-tarasyuk doesn't work on this one 😄

**Comment by DanielRosenwasser** [comment]
@IllusionMH I think that sounds reasonable, I don't expect it to be a large breaking change but we can run the test suite

**Comment by a-tarasyuk** [comment]
Not sure that I understood the point to mention me in this issue 😕 . As I know, if the issue marked with the Backlog label anyone can try to resolve it, maybe I'm wrong and @DanielRosenwasser :point_left: can clarify the current process better. I do PRs from time to time _(I can't even say that I did a lot of PRs :worried:)_, however, I definitely cannot work on all issues :joy:.

**Comment by IllusionMH** [comment]
@a-tarasyuk It was some kind of joke and my real hope that I will have chance to submit PR this time because IMHO you fix a lot of issues and do it quickly (previously beat me by 2 minutes in other issue with a bit better solution:+1:).
I also agree think that everyone can submit fix for these kinds of issues. Thank you for a bunch of submitted fixes, some of them I rely on every day! 🙇 

I'm sorry if that mention was inappropriate and for ping.

---

As for this issue - I have fix for numbers starting with `08...` and `09`, and plan to finish "legacy octal literals" this weekend.

**Comment by DanielRosenwasser** [comment]
Yeah, I understood it as a joke in a positive light - as in "@a-tarasyuk fixes a lot of issues really fast, I hope I can fix this one first!"

For what it's worth, we all really appreciate working with both of you on this issue tracker, so thank you both! Please don't feel bad about either of your contributions.

**Comment by evanw** [comment]
FWIW I have another data point for this: Someone recently reported this as a bug in esbuild's TypeScript-to-JavaScript transformer: https://github.com/evanw/esbuild/issues/2833. The confusion is understandable because TypeScript still incorrectly considers this to be valid syntax. However, I'm planning to keep it a syntax error in esbuild because it's supposed to be an error in JavaScript. But it would be helpful if TypeScript also considered this to be a syntax error so that it would appear as an error when people write code like this in their IDE.
