### ISSUE TITLE
core-js and TypeScript - how do these fit together?

### ISSUE THREAD

**Issue by johnnyreilly** [Microsoft/TypeScript#3956]
The recent blogpost on the TypeScript 1.5 release highlighted the contrast between Babel and TypeScript in terms of ES6 compatibility.

However both are listed as Babel + **core-js** and TypeScript + **core-js**:

![image](https://cloud.githubusercontent.com/assets/1010525/8809143/8d982d80-2fde-11e5-8bbc-d1bc43cb5d43.png)

I understand that Babel ships with core-js but I'm a little confused as to what TypeScript + core-js actually means.  Since TypeScript ships some of its own polyfills and [core-js](https://www.npmjs.com/package/core-js) is entirely polyfills (as I understand) I'm puzzled as to what TypeScript + core-js actually is?

Is there a compilation flag that prevents TSC from generating `super` and the like so that core-js can be dropped in instead?  Or is there an advised way of combining TypeScript and core-js that I haven't stumbled upon yet?

Apologies for raising it as an issue as it's more a question.  I've looked on StackOverflow and found this related question:

http://stackoverflow.com/questions/31417833/using-core-js-with-typescript

However it didn't resolve my mystery.  All guidance appreciated!

**Comment by RyanCavanaugh** [comment]
"TypeScript + core-js" is just what it sounds like - using the TypeScript compiler with the core-js polyfills.

The Kangax table is a little confusing because it's designed for measuring runtimes, not transpilers. For example, the TypeScript language isn't itself going to do anything special to support the "Array.prototype methods" row. We just add it to lib.d.ts and we're "done", but the Kangax table tests for runtime compat, which isn't going to work without a polyfill.

If we didn't include a polyfill library in our column, we'd be limited to a ~30% maximum score, which is really misleading when comparing to other downlevel transpilers that *are* including polyfills as part of their score. Including core-js as part of the TypeScript column just makes the top-line number apples-to-apples.

**Comment by johnnyreilly** [comment]
Thanks for that @RyanCavanaugh.  

For my own part I'd come away with the impression that TypeScript was planning by 1.6 to provide near enough 100% ES6 compatibility.  I took this to mean not only compilation level but also polyfills for downlevel transpilation.  From what you've said I now realise it doesn't.

Is there somewhere I can look to clarify what polyfills TypeScript supplies and so which ones core-js will add into the mix?  Also I'm curious to know if there's a defined policy of what TypeScript will look to polyfill and what it won't as the project progresses.  Perhaps there's also guidance that I've missed on the best way to combine TypeScript with core-js as well?   (Probably just as simple as including core-js with the served scripts.)

**Comment by DanielRosenwasser** [comment]
See [the DefinitelyTyped `.d.ts` for core.js](https://github.com/borisyankov/DefinitelyTyped/blob/master/core-js/core-js.d.ts) to get an idea of what we don't polyfill ourselves.

The rule of thumb is that if there's a canonical/sane emit that doesn't have a huge perf-hit, we'll try to support it. We don't add any runtime methods or data structures, which is more what core.js serves to do.

**Comment by aikeru** [comment]
@RyanCavanaugh I personally disagree and I think you have it backwards.
As core.js does not ship with TypeScript, TypeScript shouldn't get the extra score.

Why not core.js + Traceur?
For that matter, why not core.js + Chrome/Firefox/IEx?

...and why stop at core.js when there are other shims and polyfills that could raise other scores?

I'm sympathetic that those who support and enjoy TypeScript want a higher score. The best way to do that is to either build a better transpiler that can support ES6 features or to have TypeScript ship with something like core.js.

If the compatibility table is used as a decision tool, including core.js as a default for TypeScript is misleading at best. I would argue that the default TypeScript use-case is within the Microsoft/.NET/Visual Studio community. If core.js does not work out of the box, then I as a Microsoft stack developer will likely be surprised when ES6 features simply don't work as expected.

TypeScript isn't just the language and transpiler - it's also the part of the IDE which is no small selling point for TypeScript.

I'd be happy if both scores were included, but TypeScript's base score was on without core.js. Core.js could still still as that semi-transparent background score.

**Comment by kitsonk** [comment]
@aikeru I didn't realise it was a game to try to win by scoring the most points...  As long as the table is clear on how what is being measured, then it is like any other table/chart.

Personally, I find it informative to see how TypeScript compares with other solutions that are looking to fill the whole gap of ES6/ES2015 in a runtime environment.  TypeScript is not looking to polyfill functionality/mutate globals, only to address basic language constructs that can be fully addressed via transpilation.  Others are looking to do more than that.  It really depends on what you are looking for.  If it is just ES6 compatibility in ES5, choosing TypeScript would likely not be a good choice.

**Comment by aikeru** [comment]
@kitsonk I invite you to read my response to @RyanCavanaugh in the kangax ticket.

I will reiterate one of the key points I made here, however.
The question we should be asking is this one:

What percentage of ES6 (or 7, etc.) works with Babel out of the box, in the default configuration?
What percentage of ES6 (or 7, etc.) works with TypeScript out of the box, in the default configuration?

The rest is in my other comment.

**Comment by RyanCavanaugh** [comment]
To even the playing field, let's define "out of the box" as "the compiled JS runs without any other scripts loaded"

**Comment by johnnyreilly** [comment]
Thanks for the clarifications @ryancavanaugh and @danielrosenwasser. I don't want to participate in the bun fight this issue is fast becoming.

That said, I think it would be valuable to list somewhere in the official TypeScript documentation what ES latest => ES5/ES3 transpilation is provided by TSC "out of the box" / where "the compiled JS runs without any other scripts loaded".

Whilst it's possible to inspect the core-js typing on DT and compare that to the ES6 spec it's not a moments work. A canonical place to look would be greatly welcomed by me and a useful resource for the community I think.

How would you feel about this being added to the documentation somewhere?

**Comment by aikeru** [comment]
@RyanCavanaugh I see. So rather than basing it off of the npm package for babel/typescript or the playground/try-it-now environments on the official site or the actual install you'll use for your project ... Because Babel, by default, includes the shims for those functions in a library, are you saying you think it should be excluded for all of them?

Nevermind that it's included in the packaging as well as the documentation and that it's the expected default use case for babel, but not TypeScript.

If I have to do anything extra other than the instructions laid out for installation on the official website for the product - IE: download 3rd party tools that aren't even referenced anywhere - then including them as part of the feature set of that product is at best misleading.

As I said in my other comment on the kangax repo, TypeScript could...
- At minimum, including links and instructions for using core.js with TypeScript on the Microsoft website
- Packaging core.js, even if it's an optional component or make including it a compiler switch or something
- Improving the transpiler so that only the needed shims are included
(as a side-note, given an intelligent enough transpiler, all of these features could be provided as part of transpilation that didn't require any shim)

...but none of these are provided.

**Comment by aikeru** [comment]
Is there even a canonical answer from TypeScript folks on how core.js should be included?
It would be awfully nice to have.

**Comment by kitsonk** [comment]
@aikeru not to be rude, but I am afraid I have other things to do then read your arbitrary personal opinions in other forums.  I am interested in participating in the TypeScript community, contributing to it, not randomly bashing people in a semi-neurotic way.

**Comment by aikeru** [comment]
@kitsonk the level of integration and support that TypeScript provides for core.js is simply not the same as with babel. That's a fact, but we (the community) could change this.

My hope is to engage the JavaScript community at large into a productive discussion which will lead to better information when choosing a transpiler or a set of tools for client code.

Please, if you wish to contribute to the TypeScript community, help write the canonical references for core.js' inclusion and integration or help push for core.js to be an out-of-the-box (albeit opt-in, since as @RyanCavanaugh mentioned, the overhead could be undesirable) feature.

**Comment by RichiCoder1** [comment]
>* Packaging core.js, even if it's an optional component or make including it a compiler switch or something
>* Improving the transpiler so that only the needed shims are included (as a side-note, given an intelligent enough transpiler, all of these features could be provided as part of transpilation that didn't require any shim)

These two, at least, are specifically excluded in part by:
https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#non-goals

I could agree with providing some link to Core JS. Would love some official documentation or a wiki blurb in including it in a project.

**Comment by DanielRosenwasser** [comment]
> Would love some official documentation or a wiki blurb in including it in a project.

A wiki/handbook blurb might be useful. Perhaps we'll mention it around our non-goals, but that might not be as visible for interested users.

**Comment by RichiCoder1** [comment]
>>Would love some official documentation or a wiki blurb in including it in a project.

>A wiki/handbook blurb might be useful. Perhaps we'll mention it around our non-goals, but that might not be as visible for interested users.

To use the meme, why not both? A dedicated wiki page, a mention in the getting started ocs, and a [1] in non goals with a reference to aforementioned wiki page. Might require some more somewhere, but that would cover most the bases.

**Comment by mhegazy** [comment]
Starting with TS 2.0, you can use the [`--lib` flag](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#including-built-in-type-declarations-with---lib). you can add specific library parts as needed, e.g. `--lib es2015.promise,es2016.symbol, es2016.iterables` or just `--lib es2015` for the whole thing.

**Comment by amcdnl** [comment]
@mhegazy - does it polyfill in core-js for u automatic?

**Comment by mhegazy** [comment]
No. TypeScript does not inject any polyfills. it is up to you to chose which polyfill to use, and how to import it.
the `--lib` only imports the shapes of the APIs (e.g. `Proxy`, `Promise`, `Map`, `Set`, etc..) into your scope so that the compiler can check your code against them.

**Comment by johnnyreilly** [comment]
Hey @mhegazy,

I've been a happy user of `target: "es2015"` for some time and I'm a little confused about the overlap of functionality between `target` and `lib`.  If I use `lib: "es2016"` do I not need `target: "es2016"` with TS 2?  Or do I need both?  Could you flesh out the overlap / differences please?  I've read the docs but it's not clear to me...

**Comment by mhegazy** [comment]
No. Target is for syntactic transformations; e.g const vs a var. lib is for injecting types, e.g. Promise. Use lib if you know a specific type exits or if you have a polyfill.

**Comment by johnnyreilly** [comment]
I'm still a little confused I'm afraid.  `target` gives you the types as well as I understand. Certainly I have `Promise` / `Map` etc to play with as long as using `"target": "es2015"`

So there's some crossover still I'm guessing?  

I feel like I've got the wrong end of the stick somehow.  For my part I'm always emitting the highest possible target of ES and having Babel do the downlevel transpilation for me (it brings polyfills).  I can't work out if I actually have any use for `lib` or not.

**Comment by kitsonk** [comment]
In ES2015, there were both syntactic and functional features.

In ES2016, there was only one syntactic feature (exponentiation) and essentially one functional (`Array.prototype.includes`)

In ES2017, there are a few both syntactic features (e.g. `async`/`await`) and functional features which are likely to get approved.

`target` describes the emit syntax that is generated by TypeScript, but it also assumes the functional features of the language will also be available at run-time.  Therefore there is no need to expressly tell TypeScript that.

`lib` allows you to specify specifically what functional features TypeScript should "assume" when emitting.  So a `target` of `es5` but a `lib` that included `es6` would instruct TypeScript to emit everything syntactically, but would assume that *someone* has loaded the functional features of ES2015.

Because ES2016 was so "small" syntactically, I think the TypeScript core team assumed it would not make sense to add a separate syntactic target and since the vast majority of run-time engines have just introduced while still implementing ES2015 features...

It is apparent that the TypeScript team are still figuring out exactly how to deliver ES2017, but considering it isn't yet ratified and syntactic features already available in TypeScript are under a compiler flag, it is likely it will take a while.

So @johnnyreilly for your use case, it is unlikely you will need to instruct TypeScript to load additional TypeScript provided libs, though if you are adapting functional patterns of future ES functionality that you then are polyfilling in some other fashion at run-time, you *could* use `lib` to load those, but you could also just include them in your compile path as well.

**Comment by johnnyreilly** [comment]
Awesome - thanks @kitsonk for a really clear explanation!  

I think that, for my own use case, I'll just be using `target`; but if I decide to opt into some new hotness that Babel can polyfill and TypeScript support in `lib` then I'll be able to.

So initially I'm probably just going to be happy with `tsc --target 2016` which allows me to write ES2016 code.  But perhaps later I might use (for example) `tsc --target 2016 --lib es2017.object`.  

TypeScript will let me write either.  Babel will transpile either.

 which Babel will handle.

Then if later on

**Comment by johnnyreilly** [comment]
Ah - slightly misunderstood you.  No matter; I think I have it now; I've written it up here: http://blog.johnnyreilly.com/2016/09/typescript-20-es2016-and-babel.html

The tl;dr is: you need `tsc --target 2016 --lib es2015,es2016,dom`
