### ISSUE TITLE
Octal escape sequences should be a lexical/syntactic error in strict mode and ES5

### ISSUE THREAD

**Issue by JsonFreeman** [microsoft/TypeScript#396]
The following code should be disallowed in strict mode and ES5:

```
"\5";
"\05";
"\55";
"\055";
```

This is disallowed by Annex B.1.2 of the EcmaScript 5 spec.

**Comment by alexgorbatchev** [comment]
This has become an a problem since 1.8 release. I had ANSI escape codes in my TypeScript files, which were compiled to JS just fine, but 1.8 started adding `use strict` and all of a sudden node started freaking out.

I think a compiler error is due here if `use strict` is inserted.

**Comment by xogeny** [comment]
I don't quite understand the status of this issue?  It is still present in `2.1.4`.  Is the TypeScript leaving this for the community to fix? (if so, fine...I just want to know).

I've run into this a number of times when using @basart's `typestyle` package to import raw css via **template strings**.  It is very unintuitive that template strings allow embedded octal literals (since the contents of the template string are NOT TypeScript or Javascript). Nevertheless, that is the standard behavior.  As such, the TypeScript compiler shouldn't be outputting invalid template strings (i.e., in my opinion the TypeScript compiler should consider an invalidate template string as an error and not emit it).  It is particularly nasty when you run this gets passed through both `tsc` and `webpack` only to throw an error in the browser.  At that point, it is so far downstream it is often difficult for people to trace things back to the original issue.

**Comment by sandersn** [comment]
Yes, that is what the 'Accepting PRs' label means.

**Comment by masaeedu** [comment]
@sandersn What's the process for adding new error messages? Just make something up?

**Comment by sandersn** [comment]
See [Instructions for Contributing Code](https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#instructions-for-contributing-code) for full details, but here's a summary:

Create a test file in `tests/cases/compiler/disallowOctalEscapes.ts` that has some octal escapes.

`gulp runtests --t=disallowOctalEscapes` will make the test "fail" into `tests/baselines/local`, but the output will not have the error, so don't run `gulp baseline-accept` yet.

Add the error message in `src/compiler/diagnosticMessages.json`. I don't think we have a style guide for writing good errors, so base it on the existing examples.

Add code in the compiler to add the error. Rerun the test, check `baselines/local/disallowOctalEscapes.error.txt` to make sure the error is there, then run `gulp baseline-accept`.

**Comment by NaridaL** [comment]
I've started to read the source for parser.ts and scanner.ts to figure out how/where to implement this. So far I've figured out:

The scanner parses `"\055"` as `"\0" + "55"`, i.e. a null character followed by "55", and `"\55"` as just `"55"`, so either the scanner needs to be modified or whatever does the checking needs to do the same as emitter.ts and lookup the actual value in the original file source text (also duplicating the scanning effort with a regex for the check). I'm not sure what is preferable.

The actual check is dependent on whether we are in a strict context, so can't be done in scanner.ts directly, am I correct that it belongs in checker.ts? If so, some pointers as to where exactly it should be added would be appreciated.

**Comment by mhegazy** [comment]
> The actual check is dependent on whether we are in a strict context, so can't be done in scanner.ts directly, am I correct that it belongs in checker.ts?

yes. we defer these checks to the binder/checker.

**Comment by aslatter** [comment]
Would folks be open to a PR which only updates the scanner to correctly interpret octal-escape syntax, but does not go so far as to add warnings about their use? I'm using the `text` field in the `LiteralString` nodes, and it would help me to have them be more correct.

Updating the scanner would be required for the warning, so it seems like a step in the right direction.

**Comment by aslatter** [comment]
@mhegazy Sorry for not being clear - I was more asking if a PR adding full support for octal escape sequences to the lexer would be accepted. Someone else can come in later and add an error to the binder if it makes sense.

**Comment by mhegazy** [comment]
how would you test the change then?

**Comment by aslatter** [comment]
I could add a test for #24209 and verify that `x as "\1"` is assignable to `y as "\x01"`, or something like that. I don't actually care about that type, but I do care about the `text` field in the AST being correct.

**Comment by iansan5653** [comment]
Note that octals are disallowed completely (`SyntaxError`) in template literal strings, whether in strict mode or not. They're technically only deprecated in normal ES5 code. So it should definitely be an error in template literals, and possibly just a warning outside of them.

Also this may be obvious but `'\0' is not an octal sequence while all other one, two, or three-digit forms are, ie `'\00'` and `'\1'`.

**Comment by elibarzilay** [comment]
List of things to do for resolving this:

* `parser.ts`:
  * Not really needed, but there is a comment here that is no longer relevant and should be removed:
    `// Octal literals are not allowed...`

* `scanner.ts`:
  * At the end of `scanEscapeSequence()` should add:
    ```
    if (isDigit(ch)) tokenFlags |= TokenFlags.ContainsInvalidEscape;
    ```
    but...

* `types.ts`:
  * `ContainsInvalidEscape = 1 << 11` is defined here but it's unused!
  * `TemplateLiteralLikeFlags = ContainsInvalidEscape` ⇒ this is fishy, probably should be its own value

* `binder.ts`:
  * See `checkStrictModeNumericLiteral` and make a similar checker for strings with the `ContainsInvalidEscape` flag.

One decision to make is whether to allow octal escapes in TS when *not* producing strict-mode code.  It would probably be easier to forbid them anyway (especially since they're never allowed in template strings) but if not, then the scanner mode should also parse the octal escapes in case the output is not strict.

**Comment by reez12g** [comment]
@elibarzilay 
Can I work on this issue?
Am I correct in understanding that I should work on the to-do list that you have written?
This is my first time contributing to Typescript and I'm looking forward to working on it!

**Comment by orta** [comment]
Yeah, just give it a shot and see how it goes 👍🏻

**Comment by reez12g** [comment]
@elibarzilay @orta 
Can I consider a fix to disallow octal escaping even if it is not strict-mode?
Do you have any concerns about this?

(Is this a topic that should be discussed in PR rather than in this Issue?)

**Comment by orta** [comment]
I'm afraid that would be over-stepping, as they are allowed in those modes: https://github.com/microsoft/TypeScript/issues/396#issuecomment-403903004

**Comment by reez12g** [comment]
I see, too much.
Thanks for the quick reply!

>One decision to make is whether to allow octal escapes in TS when not producing strict-mode code. It would probably be easier to forbid them anyway (especially since they're never allowed in template strings) 

https://github.com/microsoft/TypeScript/issues/396#issuecomment-853564421
↑I was just trying to make sure about this.

So, is it the policy that octal escaping is allowed (or left allowed) when not in strict-mode?
I'm sorry if I misunderstood.

**Comment by reez12g** [comment]
@orta 
https://github.com/microsoft/TypeScript/issues/396#issuecomment-910158675
If you could confirm this, it would be greatly appreciated!
