### ISSUE TITLE
Breakpoints and systemjs

### ISSUE THREAD

**Issue by MihaMarkic** [Microsoft/TypeScript#3961]
Looks like breakpoints are disabled in Visual Studio when working with systemjs and using IE.
Here is a [stackoverflow issue](http://stackoverflow.com/questions/29017386/typescript-debugging-in-vs-not-working-for-aurelia-jspm-set-up) and here is a [blog post](http://colinsalmcorner.com/post/aurelia--debugging-from-within-visual-studio).
Is this a bug, a feature, something else?

**Comment by danquirk** [comment]
tagging @vladima

**Comment by sheetalkamat** [comment]
@MihaMarkic I was looking at the [Aurelia AppInsights Project shared here](https://github.com/colindembovsky/aurelia-appInsights) and saw that the js files are moved to the dist folder as part of some build step. Since the map files aren't present next to js files it results in breakpoints not being able to be hit. You would need to use <TypeScriptMapRoot> and <TypeScriptSourceRoot> property in your project to set the correct path when compiling ts files.
