### ISSUE TITLE
Type merging for imported types only works if the type is imported from "node_modules/@types/" dir

### ISSUE THREAD

**Issue by ezsh** [microsoft/TypeScript#39691]
Consider the following example.

In typings_module:
vars.d.ts:
```ts
interface UserProperties {
}

declare global {
    const variable: UserProperties;
}
```
index.d.ts:
```ts
export as namespace ModuleNamespace;
export * from "./vars"
```
Now, we want to specify properties for the `UserProperties` interface.
a_project_file.d.ts:
```ts
declare module "typings_module" {
	export interface UserProperties {
		test: number;
	}
}

export {}
```
The bug is the type merging works only if the "typings_module" files are inside "node_modules/@types/<module name>" and does not work if the same files are referenced from another location via the "typeRoots" TSC option in "tsconfig.json".

**TypeScript Version:**  3.9.6

**Search Terms:** "type merging", "declaration files"

**Comment by RyanCavanaugh** [comment]
It's hard for us to guess about file layouts from prose; can you make a sample repo or zip file?

**Comment by ezsh** [comment]
The layout is simple: a typings module with two files (vars.d.ts and index.d.ts, see their content above). The thing is if I symlink a dir with those files in node_modules/@types, type merging works, but when the typings are plugged in via the "typeRoots" project options, the merging breaks. Except for the merging, the typings work fine in both configurations.

**Comment by RyanCavanaugh** [comment]
It's hard for us to guess about file layouts from prose; can you make a sample repo or zip file?

**Comment by ezsh** [comment]
Here is the real example where I discovered the problem: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46236/files#diff-411587a1c5c471aa01bb2b97932f74f1R62

I'll try to create an MWE.

**Comment by ezsh** [comment]
[typescript-issue-39691-mwe.zip](https://github.com/microsoft/TypeScript/files/4955526/typescript-issue-39691-mwe.zip)

Here is the MWE. Check out the `client/index.ts` file. To make it work, I do `ln -s ../../../types/typings-module` in the `client/node_modules/@types/` dir.

**Comment by sheetalkamat** [comment]
The issue here is that when the `typings-module` is included through custom type root the user source file extending interface (`extension.d.ts` in the example) cannot resolve "typings-module" from that source file, so it does not merge those two things together.
The reason being module resolution does not take into account the custom type roots only `node_modules/@types` which is what results in this. That issue is tracked by #37958 and is breaking change and i have been investigating this but it cannot be taken for 4.2.
Keeping this alive but marking for 4.3
