### ISSUE TITLE
Build failing due to octokit plugin-rest-endpoint

### ISSUE THREAD

**Issue by nonara** [microsoft/TypeScript#39712]
**Note**: 
- I've confirmed this on different machines (linux + windows), at home and on my VPS.
- This appears to be due to the latest patch with `plugin-rest-endpoint-methods.js`, released 3hrs ago.
- I've filed an issue there: https://github.com/octokit/plugin-rest-endpoint-methods.js/issues/172

Filing an issue here as well so that it can be tracked if anyone else experiences the same.

**Steps**:
```
git clone https://github.com/microsoft/TypeScript.git
cd TypeScript
npm install
npm run build:compiler
```

**Search Terms:** octokit, build failing

**Affected Versions**: 3.9 - 4.0 fail (3.8.2 succeeded)

**Errors**
```
[21:44:13] Finished 'generateLibs' after 571 ms
node_modules/@octokit/plugin-rest-endpoint-methods/dist-types/generated/parameters-and-response-types.d.ts:961:60 - error TS2339: Property 'GET /user/:migration_id/repositories' does not exist on type 'Endpoints'.

961             parameters: RequestParameters & Omit<Endpoints["GET /user/:migration_id/repositories"]["parameters"], "baseUrl" | "headers" | "mediaType">;
                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@octokit/plugin-rest-endpoint-methods/dist-types/generated/parameters-and-response-types.d.ts:962:33 - error TS2339: Property 'GET /user/:migration_id/repositories' does not exist on type 'Endpoints'.

962             response: Endpoints["GET /user/:migration_id/repositories"]["response"];
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@octokit/plugin-paginate-rest/dist-types/generated/paginating-endpoints.d.ts:987:31 - error TS2339: Property 'GET /user/:migration_id/repositories' does not exist on type 'Endpoints'.

987         parameters: Endpoints["GET /user/:migration_id/repositories"]["parameters"];
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@octokit/plugin-paginate-rest/dist-types/generated/paginating-endpoints.d.ts:988:29 - error TS2339: Property 'GET /user/:migration_id/repositories' does not exist on type 'Endpoints'.

988         response: Endpoints["GET /user/:migration_id/repositories"]["response"];
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 4 errors.
```

**Comment by nonara** [comment]
Issue fixed on plugin side. https://github.com/octokit/plugin-rest-endpoint-methods.js/issues/172

Forthcoming from contributor is: 'post-mortem to explain what happened, how I'll make sure it won't happen again.'

**Comment by gr2m** [comment]
Here is the promised post-mortem:
https://github.com/octokit/plugin-rest-endpoint-methods.js/issues/172#issuecomment-663164635

I'll also look through your code base to see how you use `@octokit/rest`. It's possible that using `@octokit/core` instead with only the plugins you need might be a better fit. It has a much smaller API surface, which will lower the risk for future incidents as well as lower the maintenance overhead, as there are not nearly as many breaking changes. It also has a smaller bundle size which will fasten your build times

**Comment by gr2m** [comment]
I looked through your code and I think you should use `@octokit/core` instead of `@octokit/rest.`

The changes will look like this. Instead of 

```js
gh.pulls.get({ pull_number: +process.env.SOURCE_ISSUE, owner: "microsoft", repo: "TypeScript" }))
```

the code will be

```js
// https://docs.github.com/en/rest/reference/pulls#get-a-pull-request
gh.request('GET /repos/:owner/:repo/pulls/:pull_number', { pull_number: +process.env.SOURCE_ISSUE, owner: "microsoft", repo: "TypeScript" }))
```

`gh.request` has TypeScript definitions for all known routes, so from a user experience it's not such a big trade off. `@octokit/core` is roughly `1/3` of the code size, and it does not need to generate the 600+ rest endpoint methods each time you instantiate an `Octokit` instance. You also won't be affected by method name changes, which happened a lot in the past (it will slow down now though).

I'd be happy to send a pull request if you'd like that.

One thing I'd like to do first though is to update the type definitions for the paths from `/repos/:owner/:repo/pulls/:pull_number` to `/repos/{owner}/{repo}/pulls/{pull_number}`. Both work at run time, but the latter aligns with the new documentation, e.g. https://docs.github.com/en/rest/reference/pulls#get-a-pull-request

I promise to release that change as a breaking change in `@octokit/types` 🤞🏼😁
