### ISSUE TITLE
`unknown` type declaration for catch argument doesn't work in js

### ISSUE THREAD

**Issue by elibarzilay** [microsoft/TypeScript#39836]
From #36775, `unknown` doesn't work in JS with a jsdoc comment:

```ts
try {
	// something
} catch (/** @type {unknown} */ err) {
	// `err` is still typed as `any`:
	err; // $ExpectType unknown
}
```

**Comment by bajtos** [comment]
Because of this bug, it's not possible to use [`@typescript-eslint/no-implicit-any-catch`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-implicit-any-catch.md) to lint JavaScript code bases using JSDoc comments for type annotations (see https://devblogs.microsoft.com/typescript/how-to-upgrade-to-typescript-without-anybody-noticing-part-2/).

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
