### ISSUE TITLE
Generic interface with a union type involving a generic function causes problems with `unknown`

### ISSUE THREAD

**Issue by zeddic** [microsoft/TypeScript#39843]
**TypeScript Version:**  3.9.2

**Search Terms:**
union type, generics, generic function with unions, unknown, unknown is not assignable to

**Code**

```ts
interface UpdateFn<State> {
  (draft: State): State;
}

interface Container<State> {
  value: State;
  update(input: State|UpdateFn<State>): void; // <-- union here causes failure
  // update(input: State): void;                            // OK
  // update(UpdateFn<State>): void;                         // OK
  // update(input: State|((input: string) => State)): void; // OK
}

const containers: Array<Container<unknown>> = [];

function addContainer(c: Container<string>): Container<string> {
  containers.push(c);  // <-- error
  return c;
}

```

**Expected behavior:**
`Container<string>` may be added to `Array<Container<unknown>>`

**Actual behavior:**
```
Argument of type 'Container<string>' is not assignable to parameter of type 'Container<unknown>'.
  Type 'unknown' is not assignable to type 'string'.(2345)
```

**Playground Link:**
[Playground link](https://www.typescriptlang.org/play/?ssl=19&ssc=1&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgKoAcAmdIDEQA8AymDhAHzIDeAsAFDLIAUmUcMYAXMiWQJTdekANz0AvvXqhIsRCgDCAe3BxQ0YqUiVaDZADc4AGwCuEQZoijdxrGSah0xrjwsAfDNjyEhFAfsXAmMLIAPQhyAQAtJHIxiDAysgAFtAoCHDGAM4QmcjwwCZQEPSMYbG2kPYgjs4+fnoBQYzNLa1t7aHhAPIA0iWd5Z4QTB5k+Bpk5PWNwR1z7WW9-WU2Q1U15mSuTOtO3JlgUKAA5nzIALyUddOBwYt9dBJ09AjKB8ivKmpQmdwAglA2ABPAhKL4gdRxADWIEUAHcQORKOdkABtAC6VnoMDiCDACRAyDgmEwYNI3yYCG4ZNUEKgBAORxAxym1OU5LpDMOJ20-U+HOgmQAdI5MklKXxZmUojFoFBFFB+kUwMYoISEFYnkA)

**Related Issues:**

**Comment by jack-williams** [comment]
This is caused by a variance measurements which marks `Container` invariant in `State` because a function of type `(x: A) => A` is invariant in A. The measurement means that `Container<A>` is assignable to `Container<B>` if `A` is identical to `B`, which `string` and `unknown` are not.

The reason the union triggers the error is because there is special logic to treat callbacks bivariantly, but the addition of the union to the argument of `update` no longer marks the argument as a callback, so it gets related strictly.

I believe this is working as intended, thought it might be slightly tricky to unpick.

Assuming that you are unhappy with some (technical) unsoundness, which may be ok if you only call `update` with the `value` stored in the container, then one solution is the bivariance hack:
```ts
interface UpdateFn<State> {
  callback(draft: State): State;
}

interface Container<State> {
  value: State;
  update(input: State | (UpdateFn<State>['callback'])): void;
}
```

**Comment by RyanCavanaugh** [comment]
@jack-williams 's analysis is correct as usual
