### ISSUE TITLE
Result of Exclude not expected

### ISSUE THREAD

**Issue by waitingsong** [microsoft/TypeScript#39862]
**Search Terms**:
Exclude, Extract, extends

**TypeScript Version:**  3.9.7 and 3.9.4

**Code**

```ts
export type KExclude<
  TS extends unknown,
  ExcludeKey extends PropertyKey | void,
> = ExcludeKey extends PropertyKey
  // ? Exclude<keyof TS, Extract<keyof TS, ExcludeKey>>
  ? Exclude<keyof TS, ExcludeKey>
  : keyof TS

interface User {
  uid: number
  name: string
  ctime: string
}

type K1 = 'uid' | 'name'
type R1 = KExclude<User, K1>

type K2 = 'uid' | 'name' | 'foo'
type R2 = KExclude<User, K2>

```

**Expected behavior:**

```ts
type Expect = 'ctime'
```

**Actual behavior:**

```ts
R1 = 'uid' | 'name' | 'ctime'
R2 = 'uid' | 'name' | 'ctime'
```

But below correct:

```ts
export type KExclude2<
  TS extends unknown,
  ExcludeKey extends PropertyKey | void,
> = Exclude<
  keyof TS, 
  ExcludeKey extends PropertyKey ? ExcludeKey : never
>

type R3 = KExclude2<User, K1> // 'ctime'
type R4 = KExclude2<User, K2> // 'ctime'

```

**Comment by jack-williams** [comment]
The problem is that the conditional type is distributing over the input union of keys `K1`. This process can be illustrated by defining an intermediate conditional type that has fixed keys with a generic `TS`:
```ts
type ExpandWithKeys<TS extends unknown> = KExclude<TS, K1>;
// ('uid' extends PropertyKey ? Exclude<keyof TS, 'uid'> : keyof TS) | ('name' extends PropertyKey ? Exclude<keyof TS, 'name'> : keyof TS)
// === Exclude<keyof TS, 'uid'> | Exclude<keyof TS, 'name'>
```
If we were to replace the generic `TS` with `User`, then the type continues to reduces as follows:
```ts
// === (keyof User - 'uid') | (keyof User - 'name')
// === ('name' | 'ctime') | ('uid' | 'ctime')
// === 'name' | 'ctime' | 'uid'
```
Which explain the output you see: you are individually removing each key and then union'ing the result back together.

As your conditional type is '[distributive](https://www.typescriptlang.org/docs/handbook/advanced-types.html#distributive-conditional-types)' you are introducing this artificial union which is not what you want.

Reading the conditional type, I guess the specification is: if `ExcludeKey` is a valid property set, filter that from the keys of `TS`, otherwise return the keys of `TS`. I think this can be implemented using:
```ts
export type KExclude<
  TS extends unknown,
  ExcludeKey extends PropertyKey | void,
> = [ExcludeKey] extends [PropertyKey]
  ? Exclude<keyof TS, ExcludeKey>
  : keyof TS
```
which uses the `[]` tuple type constructor to suppress the distribution.

If you don't care about returning `keyof TS` when `ExcludeKey` contains an invalid key, such as `type R2 = KExclude<User, 'name' | void>`, then you can use your definition of `KExclude2`.

**Comment by waitingsong** [comment]
@jack-williams  Thank for your explanation.

When only on input ,the reulst is expected:
```ts
type K1 = 'uid' 
type R1 = KExclude<User, K1> // got 'name'  |  'ctime
```

according to yours
```
// === (keyof User - 'uid') 
// === ('name' | 'ctime')
```
