### ISSUE TITLE
Why 'input' event has `Event` type of event instead of `InputEvent`

### ISSUE THREAD

**Issue by kaczor6418** [microsoft/TypeScript#39925]
https://github.com/microsoft/TypeScript/blob/da5ff57608dd73247b898812c9fccca285969ab3/lib/lib.dom.d.ts#L5715

Hi I am wondering why type of **`'input'`** event type is a `Event` type (I thought it should be `InputEvent`)? 

I came across on this problem doing this:
```typescript
interface OnInputTextFieldListenerProps extends BaseTextFieldListenerProps {
    eventName: Extract<keyof GlobalEventHandlersEventMap, 'input'>;
    callback(e?: InputEvent): void;
}

if (isOnInputTextFieldProps(listenerProps)) {
    this.input.addEventListener<'input'>(listenerProps.eventName, listenerProps.callback.bind(this));
}
```
And now I am getting this error:
>TS2345: Argument of type '(e?: InputEvent | undefined) => void' is not assignable to parameter of type '(this: HTMLInputElement, ev: Event) => any'.

Which is absolutely correct. 

But why `GlobalEventHandlersEventMap` **`'input'`** is typed as `Event` instead of `InputEvent`. If [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event) says that `GlobalEventHandlers.oninput` interface is `InputEvent`. `oninput` is probalby equivalent of typescript `input`. I think like that because in MDN docs every key of `GlobalEventHandlers` interface starts with `on`.

You can find this `GlobalEventHandlersEventMap` interface here **[lib.dom.d.ts - L:5715](https://github.com/microsoft/TypeScript/blob/da5ff57608dd73247b898812c9fccca285969ab3/lib/lib.dom.d.ts#L5715)** at line **`5715`**.

>I also created a question at [StackOverflow - Why 'input' event has `Event` type of event instead of `InputEvent`](https://stackoverflow.com/questions/63273548/why-input-event-has-event-type-of-event-instead-of-inputevent)

**Comment by andrewbranch** [comment]
I believe the answer to this is that InputEvent is, as MDN says, an “experimental technology” covered in a [draft specification](https://w3c.github.io/input-events/#interface-InputEvent), and not in the [HTML living standard](https://html.spec.whatwg.org/multipage/indices.html#event-input), which says the event interface is `Event`. MDN’s browser compatibility table indicates only partial support, which means, depending on where your code runs, you may or may not in fact have an `InputEvent`, but you’ll definitely have an `Event`. I’m not sure what our threshold of usage/support is for changing our DOM typings—maybe @sandersn can comment.

To be both run-safe and type-safe, your callback parameter should take an `event`, and then check `e instanceof InputEvent` (or even `typeof InputEvent !== "undefined" && e instanceof InputEvent` if you want to be extra careful with super old browsers) before accessing InputEvent-specific properties. (Even there, you should be careful, since some browsers may support InputEvent but not every property that the draft spec says exists.)

**Comment by kaczor6418** [comment]
@andrewbranch thank you for your answer

**Comment by wbt** [comment]
Is browser support strong enough now to change it? We are already using InputEvent on 'beforeinput' and it would be helpful to have it on 'input' too.

**Comment by andrewbranch** [comment]
It looks like there’s another issue: https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1174
