### ISSUE TITLE
PickUsed<T> which widens the keys as the properties are used.

### ISSUE THREAD

**Issue by kolodny** [microsoft/TypeScript#39952]
## Search Terms

autopick pick used

## Suggestion

Having a `PickUsed<T>` type that expands it's type of the properties of `T` that's used

## Use Cases with Examples

Many times people only need one, two, or a couple of properties of type. Technically a `Pick` should be used but in reality most people just use `T` as the type and the unused properties are not considered. This leads to callers needing to provide those properties even though it makes no sense to need to do so:

```
class Person {
  constructor(readonly name: string, age: number, id: string) {}
}

function sayHi(p: Person) {
  console.log(`Hello ${p.name}`)
}

sayHi({ name: 'tester' }); // Error
sayHi({ name: 'tester', age: 123, id: '123' }); // OK
```

To use this function or to test it we need to create a full `Person` even though we only need the `name` property for this to work properly. While this can be worked around by using `Pick`

```ts
function sayHi(p: Pick<Person, 'name'>) {
  console.log(`Hello ${p.name}`);
}

sayHi({ name: 'tester' }); // OK
```

My suggestion is to have a `PickUsed` or `InferPick` type that expands as properties are used

```
function sayHi(p: PickUsed<Person>) {
  console.log(`Hello ${p.name}`);
}

sayHi({ name: 'tester' }); // OK
```

This is a fundamental type that would need to do property tracking similar to how arrays are widened as they are used. I realize that **this FR is by no means a trivial request**.

When the type is forwarded to a new function, assuming the other function is typed to `Person` we won't be able to infer anything and the function would fall back to need the full `Person` object.

There's an argument to be made that smart property inference should be the default behavior for types and if that tracking is working throughout the stack it would be much more helpful for developer experience and more aligned with the goals of making development on JS easier and more robust. For example consider this

```ts
class Person {
  constructor(readonly name: string, age: number, id: string) {}
}

function doSomethingWithPerson(p: Person) {
  sayHi(p);
  verifyAge(p);
}

verifyAge = (p: Person) => assert(p.age > 18);

class DraftPerson {
  constructor(readonly name: string, age: number) {}
}

doSomethingWithPerson(new DraftPerson('Foo', 33)); // Should be OK.

const updatePerson = (p: Person) => api.update({id: p.id, name: p.name.toUpperCase()});
updatePerson(new DraftPerson('Foo', 33)); // Should error.
```

Also consider someone just needing a small subset of a much larger class. The following code should just work but TypeScript gets in the way:

```ts
const useRx = (o: Observable<string>) => {
  const unsub = o.subscribe({
    next: value => console.log(value),
  });
  return () => unsub.unsubscribe();
}

const myLightweightObs = {
  subscribe: (o: { next: (s: string) => any }) => {
      return {
          unsubscribe: () => {}
      };
  }
};

useRx(myLightweightObs);

```

But baby steps.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by tyler1205** [comment]
Idk it looks/sounds somewhat confusing to me what it is you are asking for, but bare with me, I'm kinda new here and still trying to learn the ropes and etiquette of both Github and TS. Anyway, here's my random 2 cents worth. It sounds like what you are looking for are optional parameters? If not, why? Just trying to understand a bit better.

For example perhaps:  
`// Note the ? (syntactic sugar?) denoting an optional (id's type becomes `id: string | undefined`)
class Person {
  constructor(readonly name: string, public age: number, id?: string) {}
}

function doSomethingWithPerson(p: Person) {
  sayHi(p);
  verifyAge(p);
}

var verifyAge = (p: Person) => assert(p.age > 18);

class DraftPerson {
  constructor(readonly name: string, public age: number) {}
}

// WILL be OK, I believe, since 
doSomethingWithPerson(new DraftPerson('Foo', 33));`

I could be way off here and sounding stupid so I apologize in advance if that's the case. But one thing that's pretty cool about typescript that I've noticed recently is that some of the more complex and pressing challenges/typing scenarios one is trying to tackle often can be solved in simpler ways than you might at first otherwise think. I guess I just like simple solutions that actually work lol.

**Comment by kolodny** [comment]
The main difference between optional and what I'm proposing is that I don't want any of the properties to be allowed to be optional on the Person class (or interface), I only want the callers to not need to support the full Person type since some properties aren't used. Perhaps the following example will show the usefulness of what I'm after:

```ts
interface Person {
  name: string;
  age: number;
  id: string;
}

function getHeaderText(p: Person) {
  return `Hello ${p.name}`
}
```

I can do the following

```ts
const personLike = { name: 'Foo' }
getHeaderText(personLike);
```

If later getHeaderText changes to

```ts
function getHeaderText(p: Person) {
  return `Hello ${p.name}, you are ${age} years old`
}
```

Then this should start failing

```ts
const personLike = { name: 'Foo' }
getHeaderText(personLike); // personLike doesn't have an age property.
```

This fails because `personLike` doesn't have an age property. While this wasn't a problem before since `age` wasn't used in the the `getHeaderText` function, it is being used now and all usages of this function will fail if they don't provide the correct interface to the function.

---

This is the very similar to how people use duck typing in JavaScript. Using `Person` is supposed to make things easier, not to tie users down to providing a full object when the function itself doesn't use most of the properties. The following snippet is something I'd do if I was wearing my JavaScript hat but can't do in a TypeScript context:

```ts
function processPromise(p: Promise<number>) {
    p.then(x => console.log(x.toFixed(2)))
}

declare let fakePromise: {
    then: (n: number) => void;
};

processPromise(fakePromise); // This should work but errors with:
// Argument of type '{ then: (n: number) => void; }' is not assignable to parameter of type 'Promise<number>'.
//  Type '{ then: (n: number) => void; }' is missing the following properties from type 'Promise<number>': catch, [Symbol.toStringTag]
```

Again, this example may be contrived but not too far off from using a lightweight wrapper around some heavy object like a node stream or using the `Console` type

**Comment by tyler1205** [comment]
So for:
```
interface Person {
  name: string;
  age: number;
  id: string;
}

function getHeaderText(p: Person) {
  return `Hello ${p.name}`
}
```

This actually gives me an error in the latest TypeScript:
```
const personLike = { name: 'Foo' }
getHeaderText(personLike);
```

since personLike is missing age and id.

And here:
```
function getHeaderText(p: Person) {
  return `Hello ${p.name}, you are ${age} years old`
}
```

I'm assuming that's a typo and that you really meant p.age?

Anyway there's a way to get around this that:
    A) Does not require changes to the interface and/but
    B) restricts the passed arg to allow only an object with a variable number of properties of correct corresponding type (as declared on/in in the interface) and nothing more.

So how about the Partial utility type? Would that solve it? Partial is like the opposite of Required, it takes a type/object and returns a type/object where all of its properties are marked optional. That way, your interface itself is not mutated while the partial person objects that we allow are scoped/restricted to only where they are specified to be allowed (using the Partial type). For example neither of these will throw any error:

``` typescript
interface Person {
    name: string;
    age: number;
    id: string;
}

function getHeaderText(p: Partial<Person>) {
    return `Hello${p.name ? " " + p.name : ""}${
        p.age ? ", you are " + p.age + " years old." : "."
    }`;
}

// All fine
getHeaderText({ name: "Foo" });
getHeaderText({ name: "Foo", age: 5 });
getHeaderText({ age: 5 });
getHeaderText({});
```

Although getHeaderText() would throw both a TS/compile-time error because the arg itself is not optional even though its props are (but changing it to function getHeaderText(p?: Partial<Person>) would make the entire arg optional too). And if we changed it to optional then we'd have to use optional chaining with default value (as to not get "undefined" in the string or something) since we're in a string (p?.name ?? "" and p?.age ?? "") to avoid both runtime and compile time errors.

**Comment by RyanCavanaugh** [comment]
There's really no way we could do this given how inference in TypeScript works. It's effectively the same as other proposals that ask that we do the same style of inference as flow. This would also fail very badly in cases where you have a method or getter on an object that accesses properties via `this.`, which wouldn't be analyzable *at all*.
