### ISSUE TITLE
Handle non-type-level additions to JavaScript

### ISSUE THREAD

**Issue by danfo** [microsoft/TypeScript#39961]
## Search Terms

javascript, features, additions, tc39, abstract class, enum, parameter property, decorator

## Suggestion

I find it exciting that the TypeScript team is working with TC39 to improve JavaScript. For example, in an alternate history, something like optional chaining could have ended up just being a TypeScript feature. Is there sense to apply this approach retrospectively?

> TypeScript extends JavaScript by adding types.
>
> — [typescriptlang.org](https://www.typescriptlang.org)

> Enums are one of the few features TypeScript has which is not a type-level extension of JavaScript.
>
> — [The TypeScript Handbook, Enums](https://www.typescriptlang.org/docs/handbook/enums.html)

I don't know exactly which these few features are, I expect this list would be crystal clear to TypeScript contributors. Maybe they are:

- Abstract classes
- Decorators (handled :thumbsup:)
- Enums
- Parameter properties

### Potential actions

- Open TC39 proposals, benefiting JS more broadly
- Demarcate in documentation
- Add compiler options to opt-out, with defaults to not break compatibility, e.g.
  ```ts
  experimentalAbstractClasses: boolean; // default true
  experimentalDecorators: boolean; // default false
  experimentalEnums: boolean; // default true
  experimentalParameterProperties: boolean; // default true
  ```

### Workarounds

1. ESLint rule

```json
{
  "rules": {
    "no-restricted-syntax": [
      "error",
      {
        "selector": "TSEnumDeclaration",
        "message": "Enum restricted."
      },
      {
        "selector": "ClassDeclaration[abstract=true]",
        "message": "Abstract class restricted."
      },
      {
        "selector": "TSParameterProperty",
        "message": "Parameter property restricted."
      }
    ]
  }
}
```

2. Use JSDoc types and `--checkJs` instead

## Use Cases

N/A

## Examples

N/A

## Checklist

My suggestion meets these guidelines:

- [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [x] This wouldn't change the runtime behavior of existing JavaScript code
- [x] This could be implemented without emitting different JS based on the types of the expressions
- [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
- [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by DanielRosenwasser** [comment]
So based on the fact that `experimentalDecorators` has been around for about 5 years, we've sort of steered clear of experimental feature flags. Eventually, someone relies on these features and gets broken. With optional chaining, we took this to heart. We waited for TC39, and when there was an opening in the champion group, I decided to see if I could help move things along with the proposal.

I can't with total conviction say that we anticipate the other features landing in ECMAScript (at least, in their current form). I think that calling them "experimental" would be disingenuous because the features are stable and not likely to be removed given the amount of code that already relies on them.

I also think it's really not something we need to build into the compiler as an option. The request to not use a construct already built into the language is basically something you can achieve with a linter. If you're the type of person who feels strange using runtime features that are part of TS but not ES, it's fair to say you're likely to be capable of configuring this.

As one minor point of pedantry, abstract classes don't affect runtime semantics. Without remembering the exact semantics of `useDefineForClassFields`, I believe the modifier is just erased away, along with any abstract member declarations and signatures.

**Comment by danfo** [comment]
OK – thanks for confirming TS position on these language additions.

(and for all the great work!)
