### ISSUE TITLE
inconsistent excess property check behavior for tagged union 

### ISSUE THREAD

**Issue by lolicon** [microsoft/TypeScript#39993]
**TypeScript Version:**  4.1.0-dev.20200811

**Search Terms:`excess property check` `tagged union`

**Code**

```ts
type Foo = {
  type: 1;
  payload: { name: string };
};

type Bar = {
  type: 2;
  payload: Record<string, any>;
};

type Baz = {
  type: 3;
  payload: boolean;
};

type Buzz = {
  type: 3;
  payload: number;
};

type Unions = Foo | Bar | Baz;
export const shouldExcessPropertyButDidNot = (): Unions => ({
  type: 1,
  payload: { name: "naming", xxx: 100 },   // ** line one **
});

type Alternatives = Foo | Bar | Buzz;
export const shouldExcessPropertyAndDid = (): Alternatives => ({
  type: 1,
  payload: { name: "naming", xxx: 100 }, // ** line two **
});
```

**Expected behavior:**

`line one` and `line two` should both perform excess property check or not

**Actual behavior:**
`line two` performs excess property check & issue an error while `line one` does NOT

**Playground Link:** 
[Playground Link](https://www.typescriptlang.org/play?ts=4.0.0-dev.20200803#code/C4TwDgpgBAYg9nKBeKBvAUFKpIC4oCMA3JlGAIYgA2c5AJvqlAHbkC2E+AzsAE4CWzAOZQAviXHp0OaACFyvZGlIz8AJhJYK1WgygAlCAGM4vOgB4eA4QBoo5ZiAB8EktPBzyALyUYsqqABmTTJKGnp8ACMEKggHVykZKFkAVy8fFD9sD3xg0m1wvWYUtkiIXgT3SCgAVWZ+OGYuJXhEAB9khSgO+S8SCAAPMFNgKBMm0a4ACzgUqjoAUQGjCC4uAAVeOEheUFTgABF+OgA5OFGUAAoASnw6hqbkJyhLrICCG3yw3UYWdk4oAAiVhsQRCQF2AZQ-AEAAMsLEn1E1zcSQAglRgOVWMB+AA3VYtBDdTqKHppProQbDXZjRo8KDTWbzJYrNabbblUBo5h0I50JQ3fAYrG8HH4wlIZ6vFQ5QifLTfCJoP4cfDA9hgiFQKEDGHwxHoZEkIA)

**Related Issues:**

**Comment by sandersn** [comment]
The immediate difference is that `boolean` is a union of unit types: `true | false` and `number` is not. If you change `Buzz["payload"]: 0 | 1`, you don't get the excess property error either. I'll try to figure out why not.

**Comment by sandersn** [comment]
Looks like both `type` and `payload` count as discriminants when `payload: boolean` because `boolean` is really `true | false`, which are both literal types. That's because any property that has literal types in its union counts as a discriminant. In other words, `payload : true | false | { name: string } | Record<string, any>` counts as a discriminant (even though you wish it were just a payload), but `payload: number | { name: string } | Record<string, any>` does not.

Unfortunately, the compiler won't issue excess property checks on discriminants -- `payload` is treated as a peer to `type`, even though it includes some object types in its type.

**Comment by sandersn** [comment]
Here's an example where `payload` gets used as a discriminant:

1. Change `Baz` to

```ts
type Baz = {
  type: 3;
  payload: boolean;
  hi: number
};
```

2. Give an ambiguous discriminant for `type` but not `payload`:

```ts
declare const ott: 1 | 2 | 3
type Unions = Foo | Bar | Baz;
export const shouldExcessPropertyButDidNot = (): Unions => ({
  type: ott,
  payload: true,   // ** line one **
  hi: 1
});
```

You will get an assignability error saying that `1 | 2 | 3` isn't assignable to `3`.
Now add an excess field `bye: "bye"`. You'll get an excess property error instead.
