### ISSUE TITLE
[Question] Do you need typescript if you are using vscode?

### ISSUE THREAD

**Issue by techsin** [microsoft/TypeScript#40033]
I understand this is a question and should have been asked on SO, but it was asked on SO and deleted as soon as it was asked. I'm genuinely interested in learning answer to this question, if someone has concrete insights It'd help me a ton.

If you are using vscode, which has TS engine, and have jsconfig enabled, then TS engine can understand your code very accurately and reliably. It feels like you get almost all the benefits of a typed language in IDE without having types.

Features I enjoy:

1. Function parameters hints whenever you type ( or ,.
2. Click to find all places the function is being called.
3. Click to find where was this function defined.
4. Rename a variable/symbol across entire project. (This is not search & replace).
5. Refactor out a function out of file and have it imported in one click.
6. Move files and have imports updated in entire project.
7. Get reliable hints about object's properties derived from object literal or class.

Lot of these features are only available because IDE is able to understand the code rather than just checking syntax. So my question is what are additional benefits that you may get if you did use typescript.

**Comment by DanielRosenwasser** [comment]
You mentioned all those features, but those features only work reliably when you have a fully-typed program, whether that's JavaScript or TypeScript. For example, find-all-references on `method` won't work fully in the following example.

```js
function foo(obj) {
    obj.method();
}

foo({
    method() {
        console.log("hi!");
    }
}
```

Even getting good editor support for your favorite libraries is powered by `.d.ts` files.

This is because the entire experience is powered by TypeScript, which tries to understand common patterns and leverage types specified in JSDoc comments. The patterns we try to understand are kind of based on heuristics, so it may be a bit difficult to build up a mental model of what constructs are supported. You also lose type-checking validation unless you're willing to use `// @ts-check` (or `checkJs` in your `jsconfig.json`).

```js
"hello".toLowercase(); // oops! could've been caught with type-checking.
```

In theory, can you use only JavaScript and have a fully typed program and get these benefits? Yes, and a couple of teams do. We ourselves often do for quick scripts or small projects in Node.js, since you don't need a compile step to run these; but in practice, after you've written a lot of typed JavaScript code, it starts to feel really cumbersome to use JSDoc syntax, which is where TypeScript feels way better to use.

Anyway, if you're enjoying the support, that's great; that's kind of the point of the work we've done here for editors. I do encourage you to use TypeScript if you haven't already though! Everything you've already mentioned gets better, and you can get actual type-checking.

**Comment by techsin** [comment]
Thanks for the answer and providing concrete example. Much appreciate it. I'll do a small my own project.
