### ISSUE TITLE
"importModuleSpecifier" ignores "paths" in tsconfig when auto importing

### ISSUE THREAD

**Issue by Floriferous** [microsoft/TypeScript#40116]
I have 2 conflicting settings, that I wish were making a different compromise:

* `javascript.preferences.importModuleSpecifier: "relative"` in `settings.json`
* `compilerOptions.paths` in `tsconfig.json`

I defined an alias in `paths`, and would like all imports to it to be absolute imports. For the rest of my code, I want to use relative paths. However, when setting both these settings above, autoImport always resolves the aliased path relatively, instead of absolutely.

Here's a reproduction: https://github.com/Floriferous/paths-resolution

When you go into `test.js` and try to import `someVar`, it will only suggest to import it with a relative path. I wonder if this is by design, or if this is something that could be altered?

- VSCode Version: 1.48.0
- OS Version: macOS 10.15.6

EDIT: This has been happening for a long time, I just decided to open an issue now.

**Comment by LRNZ09** [comment]
I also have this issue, path aliases are recognised at compile time by Babel but not by VS Code

**Comment by RyanCavanaugh** [comment]
Duplicate #36235

**Comment by andrewbranch** [comment]
@Floriferous there’s a lot going on in your repro. What’s the symlink for? Your tsconfig says to exclude the symlink, but include the realpath. Those both refer to the same folder, and the exclude wins, so constants.js is excluded from the program, which is why it doesn’t show up in your auto-import at all.

> I defined an alias in `paths`, and would like all imports to it to be absolute imports. For the rest of my code, I want to use relative paths.

Suppose you had another file in `shared`. From that file, how would you expect to reference `shared/constants`? As `"shared/constants"` or `"./constants"`?

**Comment by andrewbranch** [comment]
The title made it sound like this was a duplicate of #36235, but it’s really a duplicate of #36624.
