### ISSUE TITLE
Possible regression in conditional types using typescript@4.0.2

### ISSUE THREAD

**Issue by traverse** [microsoft/TypeScript#40182]
**TypeScript Version:**  4.0.2

**Search Terms:** conditional, regression, 4.0.2

**Code**

```ts
type Selector<T> = (selector: T) => any

type Value<T extends Selector<any>> = ReturnType<T> extends string[]
  ? ReturnType<T>[0][]
  : ReturnType<T> extends string
  ? ReturnType<T>[]
  : never

function buildQuery<T = any, S extends Selector<T> = Selector<T>>(selector: S, values: Value<S>) {
  values.forEach(value => {
     // do things with the value
  })
}

```

**Expected behavior:**
Using `typescript@3.9.5` it used to be the following type `(string[] & ReturnType<S>)[0]` which can be seen [here](https://www.typescriptlang.org/play?ts=3.9.2#code/C4TwDgpgBAyhA2EDGwD2AnAPAFQHxQF4oAKAZwWTXQC4psBKQ-AQwDsQAoD0SKANWbwArhBxQIAD2ARWAE1KwKKDJjYhc+IgCUIwIelbZwovOKkz5UUsHQBLVgHMA2gF0OUKAH4oOvQaOQOLhOAAwuru5QtL76hsZBZtJyCtZ2jpHeMf7xeBEetKwQAG4Q6FwAZkKsKLaorFAARkK28LIAiiLoIGJEagA0sIkWCnCIylimRKOUKni4ZEpUtDADRYIipLQCwqIwuIwA3pFrO6QAdOUYAKLMSAAWxCciTFAHAL70HG8cQA)

**Actual behavior:**
Using `typescript@4.0.2` the type definition changes to an implicit `any` which can be seen [here](https://www.typescriptlang.org/play?ts=4.0.2#code/C4TwDgpgBAyhA2EDGwD2AnAPAFQHxQF4oAKAZwWTXQC4psBKQ-AQwDsQAoD0SKANWbwArhBxQIAD2ARWAE1KwKKDJjYhc+IgCUIwIelbZwovOKkz5UUsHQBLVgHMA2gF0OUKAH4oOvQaOQOLhOAAwuru5QtL76hsZBZtJyCtZ2jpHeMf7xeBEetKwQAG4Q6FwAZkKsKLaorFAARkK28LIAiiLoIGJEagA0sIkWCnCIylimRKOUKni4ZEpUtDADRYIipLQCwqIwuIwA3pFrO6QAdOUYAKLMSAAWxCciTFAHAL70HG8cQA)

**Playground Link:** See above

**Related Issues:**  I did not find any similar issues.

If any more information is required let me know!

**Comment by weswigham** [comment]
This is working as expected now - `ReturnType<T>` where `T` is a selector will always resolve to `any`, and `any` resolves to _both_ conditional type branches, so you end up with array element types `(string[] & ReturnType<S>)[0]` _and_ `string & ReturnType<S>` (realistically, when `S` is instantiated, these will all collapse to `any`, but it's not, so it isn't). These two options mean we have a union of two different array types, meaning `values` is a union of types, and we're doing `.forEach` on it. The `value` parameter type isn't the same across those two overloads, so we type it `any` (or require a type annotation by issuing an implicit `any` error with `noImplicitAny` on).

Even in 3.9.2, you can actually witness the same behavior if you change `Selector` to return `unknown`, rather than `any` (so it doesn't trigger the buggy behavior we previously had).
