### ISSUE TITLE
Type parameters in return values are sometimes inferred as never

### ISSUE THREAD

**Issue by jordanbtucker** [microsoft/TypeScript#40276]
**TypeScript Version:** 4.1.0-dev.20200826

**Search Terms:** type parameter in return value inferred as never

**Code**

```ts
// External library
type Req<B> = {
  body: B
}

type ReqHandler<B> = (req: Req<B>) => any

declare function use<B = string>(handler: ReqHandler<B>): any


// My code
type Handler<Q> = (req: Q) => any

declare function createHandler<Q>(): Handler<Q>

// Error: Argument of type 'Handler<Req<never>>' is not assignable to parameter of type 'ReqHandler<string>'.
// However, intellisense says createHandler() returns Handler<Req<string>>
use(createHandler())

// Accepted: createHandler() returns Handler<unknown>
const handler = createHandler()
use(handler)

// More examples are listed in the Playground link
```

**Expected behavior:** `use(createHandler())` should infer the return value of `createHandler` as `Handler<Req<string>>`.

**Actual behavior:** `use(createHandler())` infers the return value of `createHandler` as `Handler<Req<never>>`.

**Playground Link:** https://www.typescriptlang.org/play?ts=4.1.0-dev.20200826#code/PTAEFEA8BcFMCcB2BDANqVBLARvZ8BPAWAChoCAHWUAJVgEcAeAIQD5QBeUAb1NFGwB7ACYEAXKGakAvqVLkqtBgAlkiYagQt2XABTwGEukzYBKTuzXESpYbADGqfNQBmAV0T3omQYlBuAZ1gWTlAA6HhMRABzVl0ACzUNBCMVJM14bVMJKzkbEhBQAFkCUHsRWHlKalV1DMYARR1QfUNQBvMOS0RrWwcnA1B3T29fMoNkOFrkzKbdbNBp+qa8wvB4eEF4CQBBeGi3AFtYRGhQQRdQBWoAciWtY0ZEWAA3BFZWG9BMANBEQTOyACAUw0RQ2E0V0EoAo+GQxzg8HOl2uoBuxnumXCkRinwAdKRCspBAB3V4IAA031OsFQWCCiCCYWQBF+9gmU3SCHmoAM0DcSF+mMYj2xUVirFIgVgunZsEmsEx81MqzAO3s9lgFDgwgkcoVSvMfIFjMWXMyjysHylQUYVtlHMV5uVqtA6s12tguvG8s5dW5Rtg-MFZv9FoYTyO2HekpI0sjh2j8Di+r9Mxd+UK7q1Or1jsNvKDJqF5pFEcQUZjNplqadYbLTAriZjGcJao1Oa9ed9dfTgeDpuFHgA1v8SYhY+VGWdEmHQrXDdWEuaVfk26AAMKCDyI0CwSDwiiaPqOZxDDxeHx+WsY0tseapejCtiu7Oe703tJhnnGkO3+sjmOE5Lp+T7OqYq5AA

**Related Issues:** Nothing specific to this issue.

**Comment by weswigham** [comment]
During return type inference we create a type mapper with a `NoDefaults` flag - this makes us return the `silentNeverType` when inference fails, rather than the constraint or default type parameter value. The `silentNeverType` is supposed to then prevent any inference to the result, however since it immediately flows into the `ReqHandler` and then `Req` type via instantiation, we happily perform inference to `Req<never>` even though we would have blocked inference to the `never` itself. That's why if you change it so the `Req`'s (or `ReqHandler`s) match up during the same inference pass it works out - the inference gets blocked. I'm trying to find a way to tweak this without breaking generic function inference - it's very tight, as we seem to rely on the `silentNeverType` flowing into instantiations so it can be unpacked into, and flow through, expressions later, so it can flow into outer signatures to block inference in them and allow generic propagation.

**Comment by RyanCavanaugh** [comment]
OP now checks with zero errors.
