### ISSUE TITLE
ReactElement<typeof ... some ...> not worked as expected

### ISSUE THREAD

**Issue by feonit** [microsoft/TypeScript#40286]
ReactElement<typeof ... some ...> not worked as expected

![image](https://user-images.githubusercontent.com/3956831/91423110-c6522c80-e860-11ea-80a4-7a974fe38ba8.png)

**Comment by feonit** [comment]
Inside WrapButton in example must be only elements of MyButton, why here  div is valid i dont know, its wrong usecase

**Comment by feonit** [comment]
![image](https://user-images.githubusercontent.com/3956831/91430587-cefa3100-e867-11ea-8bdd-be6662315802.png)

**Comment by MartinJohns** [comment]
The type of `MyButton` is `() => JSX.Element`. `<div>` is a `JSX.Element`, so it's compatible.

**Comment by feonit** [comment]
need resolve problem, dont know how
![image](https://user-images.githubusercontent.com/3956831/91433318-c73c8b80-e86b-11ea-90a0-d9a8776b12df.png)

**Comment by RyanCavanaugh** [comment]
Please use text, not screenshots:
 * Many people have vision limitations that will prevent them from reading text rendered at your resolution, font size, or color settings
 * Computers can't read images either, so the issue won't show up in text-based searches
 * If someone wants to show a minor edit to your code, they have to type the whole thing in manually

Root cause is #21699
