### ISSUE TITLE
Extract the attribute value of type

### ISSUE THREAD

**Issue by lgf196** [microsoft/TypeScript#40300]
Like
interface props {
    title:string;
    type:'small' |'middle' |'default'
}
How can I get the value of type in the props interface?

**Comment by j-oliveras** [comment]
Something like:
```ts
interface props {
title:string;
type:'small' |'middle' |'default'
}

type allTypes = props["type"];
```

[Playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgA5QPaoM7IN4CwAUGMGADYQBc2YUoA5gNzFgCeq1A5NgLZzlyXZAB8uvYABNJlYWMkR4AV3JguxAL7FWHFAPIAVXbgC8aTDgDaAInadrAXRZEgA).

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
