### ISSUE TITLE
No spelling suggestion/quick fix for types

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#40314]
Follow-up from #40169.

```ts
declare let a: numbers;
declare let b: Numbers;
declare let c: objects;
declare let d: Objects;
declare let e: RegEx;

namespace yadda {
  export type Thing = string;
}
let f: yaddas: Thing;
```

Each of the above examples should presumably get a spelling suggestion and quick fix.

**Comment by sarathps93** [comment]
Is it ok if I take this up as my first issue? @DanielRosenwasser

**Comment by DanielRosenwasser** [comment]
Go for it!

**Comment by DanielRosenwasser** [comment]
Though, actually I'd first check if @a-tarasyuk is already working on this.

**Comment by DanielRosenwasser** [comment]
And additionally, I've marked this issue as "moderate" in difficulty. If this is your first issue, you might want to go through a couple of issues tagged with [`good first issue`](https://github.com/microsoft/TypeScript/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22). I'm not saying you can't do this issue, but I wouldn't suggest starting out with this one.

**Comment by a-tarasyuk** [comment]
I'm fine if @sarathps93 will work on this issue. I experimented a bit with the problem, however, I didn't make a PR.

**Comment by a-tarasyuk** [comment]
My thoughts about this issue. The following cases can be handled by `getSuggestedSymbolForNonexistentSymbol` helper
```ts
declare let d: Objects; // Object declaration can be found in lib
declare let e: RegEx;   // RegExp declaration can be found in lib

namespace yadda {
  export type Thing = string;
}
let f: yaddas.Thing; // yadda has namespace declaration
```

There is an issue with the reserved type names, like `number`, `boolean`, `string`, etc. `getSuggestedSymbolForNonexistentSymbol` for the following example will suggest `Number` instead of `number` because `number` doesn't have a symbol in `globals`

```ts
declare let a: numbers; // Number ?
```
There is option to use `getSpellingSuggestion` with the list of reserved type names `["number", "string", "never"...]` _(maybe there is helper that returns all reserved type names)_. However, `getSpellingSuggestion` converts `candidateName` to lowercase, and will suggest `number` for `Numbers`. Also, `["number", "string", "never"...]`  is array of strings - not symbols, so in QF need to handle that, or convert string to symbols. 

cc @DanielRosenwasser

**Comment by DanielRosenwasser** [comment]
@a-tarasyuk I'd say that #39060 should fix that case-sensitivity issue.

**Comment by chenjigeng** [comment]
@DanielRosenwasser  Do you think the code below should be Number or number
```typescript
declare let a: numbers; // Number or number
```

As @a-tarasyuk  says, the lastest version will change it to Number
