### ISSUE TITLE
Utility wrapper type such as Readonly<T> breaks control flow analysis of function in T that returns type `never`

### ISSUE THREAD

**Issue by mmorearty** [microsoft/TypeScript#40346]
**TypeScript Version:**  v4.1.0-dev.20200901

**Search Terms:** readonly never return control flow

**Code**

```ts
interface Services {
    panic(message: string): never; // note, returns 'never'
}

function foo(services: Readonly<Services>, s: string | null): string {
    if (s === null) {
        services.panic("ouch");
    } else {
        return s;
    }
}
```

**Expected behavior:**

Should compile. Since `services.panic()` returns `never`, control flow analysis should allow this to compile.

Note that if you change the first param of function foo to `services: Services` instead of `services: Readonly<Services>`, it does compile.

Also note that this is not specific to `Readonly` — that was just the easiest way to demo the problem, and that is the scenario I'm actually hitting. Even if you make a no-op utility type, you see the same problem:

```ts
interface Services {
    panic(message: string): never; // note, returns 'never'
}

// A no-op wrapper around a type
type Identity<T> = {
    [P in keyof T]: T[P];
};

function foo(services: Identity<Services>, s: string | null): string {
    if (s === null) {
        services.panic("ouch");
    } else {
        return s;
    }
}
```

**Actual behavior:**

Error: Function lacks ending return statement and return type does not include 'undefined'. (2366)

**Playground Link:** https://www.typescriptlang.org/play?ts=4.1.0-dev.20200901&ssl=5&ssc=24&pln=5&pc=33#code/JYOwLgpgTgZghgYwgAgMrQG7CQZ2QbwChkTkAHOEbACgFsIcc4BzCALmRzClGYEoOICBmgBuZAHoJyEAHtIAGmRQIYAK5QQeAORCRUbYQC+hQjDUgEYYLJDIYs2dRyZsDDgCUIcACa2ANgCeADzoUFi4AHxKOBxcPCDMyAA+Mmr+-gKc3LwExKTAMMjOyAC85WkZfHmktZyuuAB0FFQI1ABEsmoIABbtfKL5JEbIEP4uNXUkKuqanIO1JiZAA

**Related Issues:** Could not find any.

**Comment by ahejlsberg** [comment]
Technically this is a design limitation, but it is subtle. As explained in #32695, in order to avoid control flow analysis circularities we have some fairly stringent rules for how a function or method needs to be declared in order to be considered in the assertion and never-returning analysis. In this particular case, the `services.panic` reference fails to meet the requirements because `panic` isn't declared with an explicit type annotation (rather, it's type is computed from mapping a property in another type).

It wouldn't be too hard to support this particular case (i.e. we could allow properties with types that result from mapping another property with an explicit type annotation). I will put up a PR for that.
