### ISSUE TITLE
getter/setter interface for type-forced implementation.

### ISSUE THREAD

**Issue by TotooriaHyperion** [microsoft/TypeScript#40415]
## Suggestion

support getter type in interface.

## Use Cases

require implement of getter

## Examples

```
interface HasValue<T = any> {
  get value(): T;
}

// error: need implement value getter.
abstract class A implements HasValue<string> {
}

// error: need implement value getter.
abstract class A implements HasValue<string> {
  value = 123;
}

// ok
abstract class B implements HasValue<number> {
  get value() {
    return 123;
  }
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
As expected. You can add it as an abstract getter i your base class.

**Comment by devanshj** [comment]
In JavaScript getters and setters are just implementation details to property gets and sets. From a external point of view they are simply properties.

So ...
```typescript
interface HasValue<T = any> {
  get value(): T
}
```
... is same as writing ...
```typescript
interface HasValue<T = any> {
  readonly value: T
}
```
Because that's now an external agent would see it.

So your example becomes something like this
```typescript
interface HasValue<T = any> {
  readonly value: T;
}

abstract class A<T = any> implements HasValue<T> {
  abstract readonly value: T;
}

// expected error
class B extends A<number> {

}

// no error
class C extends A<number> {
  get value() { return 42 }
}
```
[Playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgBJwM4DU4BsCuEAPACrIC8ycIAngHzIDeAUMslBHACYD2IuNZADc8hAFzISAbmYBfZszgAjDGCiIwyBLkwZkAQVIUqtBsAC2AB1wRzEcHvTZRxEgxZtlq9Qk0dufALCLhLScgoA9BHIEAAelhC+EFwxUFA8UMzausgAQjGxkCBceoYg+OZK0O4K8sxRyCA8qemZ2Rh6AMIFRSUGROWV1UysyADmEJoiBBAAFACUTOyT+FAgyAAsAEzI8rJAA)

**Comment by RyanCavanaugh** [comment]
This doesn't really fit with our type system because types don't enforce implementation details

**Comment by TotooriaHyperion** [comment]
@devanshj 
yes i don't want allow
```
class D extends A<number> {
  value = 42
}
```

And in js getter/setter can be seen as a special type that differ from properties/methods. I'm not pretty sure yet what it should be recognized. But it did has some differences.

**Comment by RyanCavanaugh** [comment]
There are a lot of implementation details that are theoretically observable from the outside; this is one we've chosen to say are not usually relevant in a way that matters.
