### ISSUE TITLE
T[keyof T] gives a union and not an intersect of all keys of T

### ISSUE THREAD

**Issue by iamkenos** [microsoft/TypeScript#40448]
**TypeScript Version:**  4.0.2

**Search Terms:**

T[keyof T], union, intersect, generics

**Code**

```ts
const foo = {
  bar: {
    bar_one: 'bar_one val 1',
    bar_two: 'bar_two val'
  },
  baz: {
    bar_one: 'bar_one val 2',
    baz_one: 'baz_one val'
  }
};

class Clazz<T> {
  props: T[keyof T] // acts like T["bar"] | T["baz"] instead of T["bar"] & T["baz"] 

  constructor(obj: T) {
    //@ts-ignore
    this.props = Object.assign({}, ...Object.keys(obj).map(k => obj[k]));
  }
}

const quz = new Clazz<typeof foo>(foo);

console.log(quz.props) // { "bar_one": "bar_one val 2", "bar_two": "bar_two val", "baz_one": "baz_one val" }
console.log(quz.props.bar_one) // ok
// console.log(quz.props.baz_one) // error
```

**Expected behavior:**
`console.log(quz.props.baz_one)` should be allowed

**Actual behavior:**
`console.log(quz.props.baz_one)` not allowed

**Playground Link:** 
[Here](https://www.typescriptlang.org/play?jsx=0&ts=4.0.2#code/MYewdgzgLgBAZiEMC8MDeAoGMBGBDAJwC50ttdCB9cAUxIHJ8DqwaYA3PAGxgEZ6ANGWxNKUAO4gGoiUk5d6ZAL5CReAF4lM5Cs1rSqtDtxgAmQcIrqWdGIw03jC5RiUBuDBmBc8ECDABhH3V1AB4AFQA+UmwABwIQWIgScIBtAGsaAE8QOBhwgF0YAHpimDxgKH8uAEtM-NSAIiZGooAfBuaNVpgayCgaPAATGFzOlqKAMnHuos9sUH6CAFdKkAIAChAcACsUgEoY8lKAASqAWhqAczB1mksoAAsaiAA6eMT-VAB5XZpK16+CDXMAbNAqGCvKG-Hb-KCvTJZCBbXb7V4AWzwsQ26RQ0W2OwyBX2+w82CUrk8i2gMAAjst1CgYKxxIFgmEoFlYjQxggQJENnzSVTwBAQFwaK8uCArht6ep3gkkodSugYF09KxGiQNY55GZGgJ1TJJNrjVRZE5DebrLQzV1bawrTAKdTxZLpbL5YrPq9RLQVWUQOkMKq3RKpTK5QyfUk-Q4AyUyjQCAkCEA)

**Related Issues:**

**Comment by devanshj** [comment]
That's how it's supposed to work under type theory. Here's easier to understand rational without going into theory:
```typescript
const randomKey = () => Math.random() > 0.5 ? "a" : "b";
// randomKey :: () => "a" | "b"

const v = { a: 100, b: "100" }[randomKey()]
// v :: { a: number, b: string }["a" | "b"]

// you would expect v to be `number | string` right? rather than `number & string`.
```

You can convert unions to intersections via this [type](https://stackoverflow.com/a/50375286/9591609).
```diff
+ type UnionToIntersection<U> = 
+   (U extends any ? (k: U) => void : never) extends ((k: infer I) => void) ? I : never
+
  class Clazz<T> {
-   props: T[keyof T]
+   props: UnionToIntersection<T[keyof T]>
```
And now [it works](https://www.typescriptlang.org/play?jsx=0&ts=4.0.2&ssl=26&ssc=24&pln=26&pc=109#code/MYewdgzgLgBAZiEMC8MDeAoGMBGBDAJwC50ttdCB9cAUxIHJ8DqwaYA3PAGxgEZ6ANGWxNKUAO4gGoiUk5d6ZAL5CReAF4lM5Cs1rSqtDtxgAmQcIrqWdGIw03jC5RiUBuDBigBPAA5sAVTAAS3AAFRAASTAoGgIIGmAoULAAHgCAPhQYMgAKAJgaAA9YsAATCBg8MG8YAH4YXIBrEgCAShQs9hBgspgSVnY4juLSisbmkmCwODiYSI7kLp6yjobI-phBuM9gLjwISoBhffV1VLCs7RhfAhBfCFaQ8KiYuISklIuAbSaabxAcBgYQAuhlPNhQJAoAQAK5JEAEXIgHAAKxIYQ612wAHocQABKAQAC0wQA5mBETRLFAABbBCAAOlu90qqAA8mjElBGQcIOSwLk0CoYIyxZzUdzGX9vBBkWi2oyALZ4XzNTowFGo34gtptDzYJSuXbgaAwACOsPU2VY4hgJw05x8-kB8EQGVyCBA+pNkBAXBojK4IDJuUt6mZdweHTx6BgACJRLR4yRE4ZWE4zPGBAmZJIU7mqLInNnC9Zk6n8OWM-J4zAjVCIP7A8HQ+HI6zGUnWDGcZqmhhG82gyGw1aOw8uw5aL3+0A)

(This issue should be closed with "By Design" label)

**Comment by RyanCavanaugh** [comment]
The above explanation is correct. Type operations reflect the *read* type of properties.

**Comment by iamkenos** [comment]
> That's how it's supposed to work under type theory. Here's easier to understand rational without going into theory:
> 
> ```ts
> const randomKey = () => Math.random() > 0.5 ? "a" : "b";
> // randomKey :: () => "a" | "b"
> 
> const v = { a: 100, b: "100" }[randomKey()]
> // v :: { a: number, b: string }["a" | "b"]
> 
> // you would expect v to be `number | string` right? rather than `number & string`.
> ```
> 
> You can convert unions to intersections via this [type](https://stackoverflow.com/a/50375286/9591609).
> 
> ```diff
> + type UnionToIntersection<U> = 
> +   (U extends any ? (k: U) => void : never) extends ((k: infer I) => void) ? I : never
> +
>   class Clazz<T> {
> -   props: T[keyof T]
> +   props: UnionToIntersection<T[keyof T]>
> ```
> 
> And now [it works](https://www.typescriptlang.org/play?jsx=0&ts=4.0.2&ssl=26&ssc=24&pln=26&pc=109#code/MYewdgzgLgBAZiEMC8MDeAoGMBGBDAJwC50ttdCB9cAUxIHJ8DqwaYA3PAGxgEZ6ANGWxNKUAO4gGoiUk5d6ZAL5CReAF4lM5Cs1rSqtDtxgAmQcIrqWdGIw03jC5RiUBuDBigBPAA5sAVTAAS3AAFRAASTAoGgIIGmAoULAAHgCAPhQYMgAKAJgaAA9YsAATCBg8MG8YAH4YXIBrEgCAShQs9hBgspgSVnY4juLSisbmkmCwODiYSI7kLp6yjobI-phBuM9gLjwISoBhffV1VLCs7RhfAhBfCFaQ8KiYuISklIuAbSaabxAcBgYQAuhlPNhQJAoAQAK5JEAEXIgHAAKxIYQ612wAHocQABKAQAC0wQA5mBETRLFAABbBCAAOlu90qqAA8mjElBGQcIOSwLk0CoYIyxZzUdzGX9vBBkWi2oyALZ4XzNTowFGo34gtptDzYJSuXbgaAwACOsPU2VY4hgJw05x8-kB8EQGVyCBA+pNkBAXBojK4IDJuUt6mZdweHTx6BgACJRLR4yRE4ZWE4zPGBAmZJIU7mqLInNnC9Zk6n8OWM-J4zAjVCIP7A8HQ+HI6zGUnWDGcZqmhhG82gyGw1aOw8uw5aL3+0A)
> 
> (This issue should be closed with "By Design" label)

Easy to understand indeed. Thanks for pointing that out and showing the solution!
