### ISSUE TITLE
`const` in class body

### ISSUE THREAD

**Issue by nycdotnet** [Microsoft/TypeScript#4045]
Hi,

I know ES6 doesn't support using const with class members and I'm assuming this is why TypeScript also does not.  I'm wondering if the error if someone tries to do this with TypeScript can be improved.

```ts
class AtomicNumbers {
  static const H = 1;
  static const He = 2;
}
```

In the code above, TypeScript gives the error "`'=' expected.`", twice.

It would be much better to get an error such as "Class members cannot be declared with the const keyword.".  Bonus points if it suggested something like, "Consider creating a module of the same name and exporting a constant from there."

**Comment by MartyIX** [comment]
I'm a newbie but this is a result of my debugging analysis:

The problem is in `parseClassElement()` function:

1) `parseModifiers()` function swallows modifiers that are not in proper context ( https://github.com/Microsoft/TypeScript/blob/master/src/compiler/parser.ts#L4714). So `parseModifiers`  skips `const`. 
2) `parsePropertyCall` (https://github.com/Microsoft/TypeScript/blob/master/src/compiler/parser.ts#L4788) then assigns   word `const` to `name` variable (instead of `H` as expected).

How to resolve the issue? I guess it is necessary to either:

  * add `parseErrorAtPosition` function call on the line https://github.com/Microsoft/TypeScript/blob/master/src/compiler/parser.ts#L4714 to add a generic message "the modifier is not allowed in the context"

or

  *  add a new property `modifiers.invalidModifiers` in `parseModifiers` and then handle the errors for each case.

**Comment by DanielRosenwasser** [comment]
I would probably check if the current token is considered a keyword in any context and whether the subsequent token is a potential class member declaration or keyword on the same line. If so, then I would have a separate function that aggregates the invalid modifiers, reports errors on them, and returns the actual thing being declared.

So for the following:

```TypeScript
class C {
    public const var export foo = 10;

    var constructor() { }
}
```

I would expect:

```
The 'const' keyword cannot appear on a class member.
The 'export' keyword cannot appear on a class member.
The 'var' keyword cannot appear on a class member.
```

I'm shying away from "A class member cannot have a '{0}' modifier" because it reads awkwardly if the modifier starts with a vowel. Maybe @JsonFreeman has suggestions all around.

**Comment by JsonFreeman** [comment]
You could use "A class member cannot have *the* '{0}' modifier"

**Comment by DanielRosenwasser** [comment]
Or specifically for the 'var' case, "A class member cannot have the '{0}' keyword."

Does that still work?

**Comment by JsonFreeman** [comment]
Yes I think so.

**Comment by DanielRosenwasser** [comment]
We now give an error message thanks to @MartyIX.

**Comment by nycdotnet** [comment]
@martyix way to go!
