### ISSUE TITLE
Why vscode doesn't intellisense function inside packages in typescript monorepo?

### ISSUE THREAD

**Issue by wizardnet972** [microsoft/TypeScript#40487]
Version: 1.49.0-insider (user setup)
Commit: e4256dd1a02339bb1d56647ecd9134bf38bc7c03
Date: 2020-09-04T18:49:12.955Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

I created a monorepo with lerna (the code in github).
Inside I have two packages each package export sum function.
In app1 folder I want to import this function but vscode doesn't find the function.

Steps to Reproduce:

1. clone my repo: `https://github.com/wizardnet972/lerna-test`
2. run `npm i`
3. open the vscode insiders
4. open the file: `apps/app1/src/index.ts`.
5. try to get autocomplete to `sum`  function. 
6. you will get:

![image](https://user-images.githubusercontent.com/4997825/92313025-5c0f5980-efcf-11ea-8d80-9ba58579c386.png)

**expected:**
suggest results (where the `sum` function is): 
```
@packages/pck1
@packages/pck2
```

Does this issue occur when all extensions are disabled?: Yes

[stackoverflow question](https://stackoverflow.com/questions/63755918/why-vscode-doesnt-intellisense-function-inside-packages-in-typescript-monorepo)

**Comment by mjbvz** [comment]
I believe your project is not configured properly. See [this example](https://github.com/RyanCavanaugh/learn-a) of how you can use project references to tell TypeScript about the links between the packages

**Comment by rnarcos** [comment]
Hi 👋

I've wanted to complement this question here:

Just to give you a brief explanation here, my library setup is as the following:

```
packages/foo
├── README.md
├── babel.config.js
├── jest.config.js
├── package.json
├── setupTests.js
├── src
│   ├── components
│   │   ├── Foo
│   │   │   ├── Foo.component.tsx
│   │   │   ├── Foo.data.ts
│   │   │   ├── Foo.designs.ts
│   │   │   ├── Foo.props.ts
│   │   │   ├── Foo.style.ts
│   │   │   ├── Foo.test.tsx
│   │   │   └── index.ts
│   │   └── index.ts
│   ├── index.ts
│   ├── theme
│   │   └── index.ts
├── styled.d.ts
└── tsconfig.json
```

I have a rollup build that generates my libraries files in a way that allows me to import all the paths present under my library. In essence, it allows me to import:
`import foo from 'foo';`,
`import foo from 'foo/components/Foo';`,
`import foo from 'foo/components/Foo/Foo.component.tsx'`

Although my rollup build scheme is correct (I **am** able to import my `foo` library correctly using those imports statements - outside of the monorepo), after following [this demo](https://github.com/RyanCavanaugh/learn-a) from @RyanCavanaugh, my intellisense offers me the following imports:
`foo`,
`foo/src/components/Foo`,
`foo/src/components/Foo/Foo.component.tsx`

Having `src` in the "nested" imports for me is problematic because it's going to raise issues when building / in production and I'd like to know if there'd be any way to "fix" the imports to not offer `src` as part of the intellisense.

My tsconfig at my `packages/foo` library is:
```json
{
  "extends": "../tsconfig.settings.json",
  "compilerOptions": {
    "rootDir": "src",
    "outDir": "ts"
  }
}
```

My tsconfig at my `packages/baz` library is:
```json
{
  "extends": "../tsconfig.settings.json",
  "compilerOptions": {
    "rootDir": "src",
    "outDir": "ts"
  },
  "references": [
    { "path": "../foo" }
  ]
}
```

My packages/tsconfig.json file:
```json
{
  "files": [],
  "references": [
    { "path": "baz" },
    { "path": "foo" }
  ]
}
```

My packages/tsconfig.settings.json file:
```json
{
  "compilerOptions": {
    "composite": true,
    "declaration": true,
    "emitDeclarationOnly": true,
    "declarationMap": true,
    "sourceMap": true,

    "module": "esnext",
    "target": "es5",
    "lib": ["es2020", "dom"],
    "jsx": "preserve",
    "moduleResolution": "node",
    "downlevelIteration": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "noErrorTruncation": false,
    "skipLibCheck": true
  }
}
```

The demonstration cleared 90% of my typescript issues when using a monorepo, thank you for that!

**Comment by ScottMorse** [comment]
For others struggling with solutions to this, in [my SO answer here](https://stackoverflow.com/questions/69652809/how-can-i-get-vscode-auto-imports-working-in-a-typescript-monorepo/79301919#79301919) I detail how you can fix this  without declaration files or using the tsconfig `"paths"` by referencing workspaces by `"@example/workspace-name": "*"` in each dependent workspace's `package.json` `"dependencies"`. 

There are more details to the conditions for getting this working in the full answer in the link.

I also added `"typescript.preferences.includePackageJsonAutoImports": "on"` to my VSCode settings.json.
