### ISSUE TITLE
Type checking using single or double question marks

### ISSUE THREAD

**Issue by evilworm** [microsoft/TypeScript#40492]
**TypeScript Version:**  4.0.2 (also tested on 4.1.0-insiders.20200910)

**Search Terms:** question type checking, double question type checking

**Code**

```ts
function test(param:string) {        
}

const a:any = undefined;
test(a ? a : 0);
```

**Expected behavior:**
test(a ? a : 0) should return TS2345 error. The same should happen if test(a ?? 0) is used. If you expand this to
```ts
if(a) { test(a); } else { test(0); }
```
then you get the expected behavior and TS2345 is shown

**Actual behavior:**
No TS2345 error is shown

**Playground Link:** https://www.typescriptlang.org/play?ts=4.0.2#code/GYVwdgxgLglg9mABFApgZygCgA4EMBOuAtgFwb4xgDmAlIgN6JPNMBQAvq6xAhoriVxgAnogC8icABMUwSiikBubryiIARiTAgi6lPnGIADMtaoMmXIgD8-RCWM1l5rFdtH7-J2fSub77xdLfw1vVhhgSzp6VhYg3G92RBQAGzQUBljmIKNvON9MdUSuViA

**Related Issues:** not that I know of

**Comment by RyanCavanaugh** [comment]
The problem is, what is the type of the expression `a ? a : 0`. That question is evaluated independently of the fact that it's in an argument position. The type of `a ? a : 0` is `any`, not the type `any | 0` (this is a degenerate way of writing `any`, since `any` encompasses every value including `0`).

If we "fixed" this by making `test(a ? a : 0)` "consistent" with the other form, then we'd just move the inconsistency elsewhere
```ts
// v: any
const v = a ? a : 0;
test(v);
```

**Comment by evilworm** [comment]
in this case string is a sub-type of any, but 0 is not and it still should throw TS2345
