### ISSUE TITLE
The presence of a `jsxImportSource` pragma or compiler option should implicitly include the types of the target module

### ISSUE THREAD

**Issue by weswigham** [microsoft/TypeScript#40502]
This is a followup for #39199. If the pragma or compiler option is present, we should append the values to the `types` we look up, to reduce the duplication required in the compiler options.

**Comment by xiaoxiangmoe** [comment]
```tsx
/** @jsxImportSource react */
function App() {
  return  <div className="App"> </div> ;
}
```

This don't work in ts unless we use this pragma `jsx: react-jsx`.

Also, we may use 
```tsx
/** @jsxImportSource ./utils/my-jsx */
function App() {
  return  <div className="App"> </div> ;
}
```

And I want it compiles to `import { jsx as _jsx } from "./utils/my-jsx/jsx-runtime";`

**Comment by ddprrt** [comment]
Quick Q: Is this the issue addressing that once I add 

```
{
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "preact",
    "strict": true
  }
}
```

to my compiler options, I get a `JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.ts(7026)` error, because TypeScript does not add the `jsx-runtime` types?

Is there a workaround for that at the moment?

**Comment by weswigham** [comment]
No, that's the other issue about automatically including import source types, but it does have a simple workaround - also add `"types": ["react"]` to your options.
