### ISSUE TITLE
Intellisence Import Update Feature creates erroneous updates when used with a compilerOptions.paths 

### ISSUE THREAD

**Issue by egucciar** [microsoft/TypeScript#40560]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.1.0-dev.20200914

**Search Terms**
- automatic path update

---

- VSCode Version: 1.48.1
- OS Version: Mac OS 10.13.6

Steps to Reproduce:

1. Use `jsconfig.json` to set up some absolute paths
2. Rename a folder/file within one of those absolute paths
3. Random imports throughout the codebase will be rewritten incorrectly and undeterministically.

e.g. we have something like this:

```js
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "*": ["./next/src/*"],
      "@app": ["./modules/@app/*"],
      "@app/*": ["./modules/@app/*"],
      "@local": ["./modules/@local/*"],
      "@local/*": ["./modules/@local/*"],
    },
    "jsx": "preserve"
  },
```

I rename a folder within `@app` and then and a random import in the codebase like this:

```
@local/deep/path
```

gets rewritten to

```
@app
```

Which is very annoying since i dont always catch it in time to undo then need to look for all the files which are now randomly broken 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by andrewbranch** [comment]
@egucciar there is a bug here, but FYI your `paths` are invalid and will probably cause you more pain in the future. `"@app": ["./modules/@app/*"]` doesn’t make sense because you have a `*` on the right but not the left. Same goes for the `@local` entry. If you remove the star, you get a different path, but one that’s more obviously the bug that #41959 fixes.
