### ISSUE TITLE
createScanner function no longer exposed in typescriptServices.d.ts on latest build

### ISSUE THREAD

**Issue by gscshoyru** [Microsoft/TypeScript#4057]
createScanner was previously exposed in #3020, along with the Scanner class. However, in the latest master branch of typescript, the Scanner class is still there but createScanner is missing.

**Comment by danquirk** [comment]
@mhegazy intentional or bug?

**Comment by mhegazy** [comment]
that was not intentional.

**Comment by mhegazy** [comment]
feel free to send a PR removing the `/* @internal */` comment and that will make it show up again.

**Comment by adidahiya** [comment]
I'll take up this PR.

**Comment by adidahiya** [comment]
wait, nevermind, this is no longer an issue on `master`, despite the `/* @internal */` above `createScanner`. maybe that's because of the comment in between the internal flag and the function name? https://github.com/Microsoft/TypeScript/blob/master/src/compiler/scanner.ts#L677

looks like `/* @internal */` should be removed there anyway though.

we also use `computeLineStarts()` in tslint and would like that exported in `typescriptServices.d.ts`. would you be cool with making that non-internal? https://github.com/Microsoft/TypeScript/blob/master/src/compiler/scanner.ts#L279

**Comment by DanielRosenwasser** [comment]
@adidahiya if you can send a quick PR that would be great, it should indeed be removed

**Comment by DanielRosenwasser** [comment]
Oh, regarding `computeLineStarts`, @mhegazy should answer that

**Comment by mhegazy** [comment]
what do you uses that for? would not `getPositionOfLineAndCharacter`  and `getLineAndCharacterOfPosition` be sufficient? lineStarts is really an implementation detail.

**Comment by adidahiya** [comment]
Figured out a way to get around using `computeLineStarts`. Must've been left over from usage of an older version of the LS API. So that can remain internal.

I made an error my above comment; this issue is _not_ resolved on `master`: (https://github.com/Microsoft/TypeScript/blob/master/lib/typescriptServices.d.ts#L1416), so I'll go ahead and fix it.
