### ISSUE TITLE
Property Decorators last argument is undefined

### ISSUE THREAD

**Issue by DanilaFadeev** [microsoft/TypeScript#40577]
**TypeScript Version:**  4.0.2

**Search Terms:**  property decorator undefined the last argument

**Code**

```ts
function propertyDecorator(...args) {
  console.log(args);
}

class Test {
  @propertyDecorator
  name: string;
}
```

**Expected behavior:**
`[ Test {}, 'name' ]`

**Actual behavior:**
`[LOG]: [ {}, "name", null ]`

**Playground Link:** https://www.typescriptlang.org/play?ts=4.0.2#code/GYVwdgxgLglg9mABABwE52QU1VAngEUwjlQEMoSAKAOltNQHMBnALkVLFwG0BdASkQBvAFCJExMEzgAbTNWlwGlesz4BuYQF9hwiNNJMmiACqYmUIaMQABNBmx5CxMhVRWwpALaY251DDAGDU0gA

**Related Issues:** Not found

**Comment by IllusionMH** [comment]
Just in case `[LOG]: [ {}, "name", null ]` looks like website bug. In browser console it correctly logs `[{…}, "name", undefined]`.

/cc @orta

**Comment by orta** [comment]
Thanks 

Seems pretty legit, I've given the whole logging system an overhaul to handle more specific primitives in https://github.com/microsoft/TypeScript-Website/pull/1108

It'll either go live with the next prod website deploy (scheduled every Monday) or sometime before if I need to make a deploy.

**Comment by DanilaFadeev** [comment]
@orta Sorry, but my reported issue is not about the website logging, but about the wrong number of decorator parameters.  `PropertyDecorator` should receive only two arguments, because of its core definition [lib.es5.d.ts#L1415](https://github.com/microsoft/TypeScript/blob/9ff24b6fc87dd4a376a434d1019d356dfe743c53/lib/lib.es5.d.ts#L1415). But somehow we receive 3 parameters and the last one is undefined.

**Comment by orta** [comment]
OK, so, I think I'll need @rbuckton to give this a look over. 

The JS version of your code looks like this:

```js
"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function")
        r = Reflect.decorate(decorators, target, key, desc);
    else
        for (var i = decorators.length - 1; i >= 0; i--)
            if (d = decorators[i])
                r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function")
        return Reflect.metadata(k, v);
};
function propertyDecorator(...args) {
    debugger;
    console.log(args);
}
class Test {
}
__decorate([
    propertyDecorator,
    __metadata("design:type", String)
], Test.prototype, "name", void 0);
```

With `d(target, key, r)` being the call which passes the `undefined` through as the third arg. This can be switched out with an extra check for the undefined as the `r`:

```diff
-                r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
+                r = (c < 3 ? d(r) : c > 3  && r !== undefined ? d(target, key, r) : d(target, key)) || r;
```

Then it will give a console log of `[ {}, 'name' ]`. 

I'm just not sure of the network effects of such a change.

**Comment by rbuckton** [comment]
This is intended behavior:

- We call `__decorate(decorators, F)` for class decorators
- We *used* call `__decorate(decorators, target, key, Object.getOwnPropertyDescriptor(target, key))` for methods/accessors.
- We *now* call `__decorate(decorators, target, key, null)` for methods/accessors (`null` indicates we should call 
`Object.getOwnPropertyDescriptor` in the helper). This was a backwards compatibility feature in a release where we reduced the footprint of calls to `__decorate`.
- We call `__decorate(decorators, target, key)` for methods/accessors/fields when targeting **ES3**, because ES3 has no `Object.defineProperty`.
- We call `__decorate(decorators, target, key, void 0)` for fields when targeting **ES5 or higher**, because you can convert a field into an accessor by returning a `PropertyDescriptor`.

Run the following code in the playground and you'll see what I mean:

https://www.typescriptlang.org/play?ts=4.0.2#code/GYVwdgxgLglg9mABABwE52QU1VAngEUwjlQEMoSAKAOltNQHMBnALkVLFwG0BdASkQBvAFCJEqTFBCokgxADdSAGxCY2ARkQBfYTuGhIsBCnRYcBIiXIkATDTqNW7TrwEixxMEzhLM1JXAMlPTMfADcusLCEEqkTEyIACqYTFBCoogAAmgY2HiExGQUqDYZ2aZ5FoXWqBlgpAC2aoipqDBgDBFaQA

As esoteric as it is, if you check `arguments.length` in your decorator and only get `2`, that essentially means your decorator is being evaluated by a TypeScript compiler targeting ES3, and returning a value from it will have no effect.

**Comment by rbuckton** [comment]
Here's a playground link for the same code targeting ES3:

https://www.typescriptlang.org/play?target=0&ts=4.0.2#code/GYVwdgxgLglg9mABABwE52QU1VAngEUwjlQEMoSAKAOltNQHMBnALkVLFwG0BdASkQBvAFCJEqTFBCokgxADdSAGxCY2AIgAWMdYgC+wg8NCRYCFOiw4CREuRIAmGnUat2nXgJFjiYJnCVMaiU4Bkp6Zj4AbkNhYQglUiYmRAAVTCYoIVFEAAE0DGw8QmIyClQHHPzLIptS+1QcsFIAWzVETNQYMAYYo19-QODQynTM6gKKPCxqZrbooA

And the output:
```
[LOG]: [ {}, "name" ] 
[LOG]: undefined 
```

**Comment by DanilaFadeev** [comment]
Thanks, @rbuckton, now it's clear about the actual behavior. Lately, for ES3, to make a general decorator for any decorator type, we could define which type it has, with just `arguments.length`, but for the ES5+ we need to clean up the argument array first. It's a bit confusing but okay for me. 
Nice job, glad to be helped!

**Comment by dxhsmwqcwelllee** [comment]
Is there any way for the development environment to make the last parameter not undefined?

**Comment by rbuckton** [comment]
> Is there any way for the development environment to make the last parameter not undefined?

No, not with the legacy decorator support provided by `--experimentalDecorators`. Fields do not have descriptors as they do not exist until after they are installed, such as when an instance is created. This is a capability that changed somewhat with native decorators (currently Stage 3), as a field decorator will receive a context object like any other decoration target, and are able to inject an initializer function. We are not likely to make further changes to legacy decorators at this time.
