### ISSUE TITLE
Object displacement and typing bug

### ISSUE THREAD

**Issue by socketpair** [microsoft/TypeScript#40589]
TypeScript Version: 4.0.2 

```ts
type SomeType = {
  a: number;
  b: string;
};

const values = {
  b: 'test',
  c: true
};

const x: SomeType = { a: 1, ...values }; // WUT? Why no error here ?!    <-- problem here
const y: SomeType = { a: 1, b: values.b, c: values.c }; // 'c' is extra. That's correct.
const z: SomeType = { ...values }; // property 'a' is missing. That's correct.

console.log(x);
```

**Expected behavior:**

Error have to be shown on indicated line

**Actual behavior:**
No error show on indicated line.

https://www.typescriptlang.org/play?#code/C4TwDgpgBAyg9gWwgFXNAvFA3gKClAQwC4oA7AVwQCMIAnAbjyipIGdhaBLUgc0YF9GOAMZxS7KADcCAG3IRWUTLnwsoAcmALg6gDRNhJDvJyCcIsRIAeJeElSQl2QiQCMuqADpv0uQqiCUAD0QVAA6gCqyAD8UADuABYgZHBQdLRwtFAJdNDRAIQW4sBQILaIKGhOWC5Q7sxEvvKsnlQehlKyzZ7CAfTBoerC6lAAJnD+pHAlEFac7C1QyAkEOoqitLQQwsCeRRIAXuX2VcpePl3+gSFQYBmQtKAaBCPzUAjzrNw8nksra1ANlsdnt9nAZBBPDI4DwABRWACUjCAA

**Comment by RyanCavanaugh** [comment]
Object types aren't sealed; excess property checks occur to detect typos but are not an intrinsic part of the type system

**Comment by socketpair** [comment]
1. As shown in the example, type checking seems is not consistent. So I don't agree the there is no bug.
2. How should I change the source in order TS to show such kind of errors ?

**Comment by RyanCavanaugh** [comment]
1. It is not inconsistent, because those lines are not the same. Different code does different things; this is how you are able to write different programs.
2. See #12936

**Comment by jgbpercy** [comment]
@socketpair excess property checks are a special case check for when you write an object literal with keys written inline. [That's how its defined to work](https://www.typescriptlang.org/docs/handbook/interfaces.html#excess-property-checks). You may not like the fact that doesn't take into account spreads, but it's not a bug.

The way I think about it is that TypeScript's type system seeks to guarantee that if you have a object of type `SomeType`, then that object has "at least" the shape of `SomeType`, but it doesn't really seek to guarantee that it **doesn't** have **extra** properties. Excess property checks are not seeking to do that, they're just seeking to conveniently catch obvious cases that are highly likely to be a mistake.

Generally, having extra properties on a JS object above and beyond the type TS knows about doesn't tend to be a problem. Obviously with something like `Object.keys` it can matter, but as Ryan says, for TS to address that properly some form of Exact Types are needed (as in the linked issue) rather than just addressing more special cases.

**Comment by socketpair** [comment]
That's pity. Thank you for the explanation. Will wait for `Exact` or, better, compilation option (like `--strictNullChecks `) that will switch behavior.
