### ISSUE TITLE
Suggestion: Separate typescript source compiler from any ide integration

### ISSUE THREAD

**Issue by delebash** [Microsoft/TypeScript#4059]
I would think it would be better to separate typescript's compiler and bug and release cycle from any ide related issues.  To me if the command line compiler works as expected then any ide integration should be the responsibility of that ide.  Of course the typescript community can maintain plugins for ide's in separate repo's if they want in order to help increase typescripts use.

The last release was tied to VS and also several bugs that where VS related were either holding up the 1.5 release or were moved to 1.6 prior to 1.5 official being released.  Not just picking on VS this would include Atom, Webstorm ect...

I am not that familiar with the things involved in having a particular ide support a language, but maybe some type of open api or maybe there is already a standard method to publish language features for ide consumption and typescript just needs to conform to that standard.

I just think this type of separation of compiler and ide would make for a smoother and faster development environment for the typescript language.

**Comment by RyanCavanaugh** [comment]
Are you talking about moving the source code around, or changing how we schedule releases? The compiler source and the VS integration source are already completely separate.

**Comment by mhegazy** [comment]
A few thoughts here, as of last week [TypeScript now has a nightly release on npm] (http://blogs.msdn.com/b/typescript/archive/2015/07/27/introducing-typescript-nightlies.aspx). we have kept master in a shipable state for the last few years. so nightly builds should not be broken builds, but rather may include design changes.without due breaking announcements. we are also working on getting a faster release cadence for all tools as well as the compiler, and ultimately a nightly tooling drop as well.

Tooling has been, and continues to be one of the TypeScript value propositions. TypeScript services are not only used for VS, but in VS Code, sublime text, Atom, eclipse, etc.. getting a release out for all these tools takes some time, and that participates in the time we spend "stabilizing" a release.

I do not think it is correct to ship a compiler that does not match tooling. it is annoying to me as a user to have to get errors in my editor, that i can "ignore" because i know my build tools is ok with it. it makes it hard to users to trust their tools feedback.

**Comment by delebash** [comment]
@RyanCavanaugh I was mainly referring to release schedule where you have a stable build of typescript as far as the core and language services, but you still have a bug in 1 or 2 particular editor's that may hold up the official release. 

@mhegazy I agree that editor support is very important or people will not use the language.  It just seemed that sometimes the core compiler and tsc are feature complete and work fine in some editors but are buggy in others and we have to wait for all major editors to be fixed before official release.  This just seems very tightly coupled.  It just hit me as something where I thought workflow could be better by decoupling typescript from editors.  Now if I am reading this correctly then the Language Service is like an api for editors to consume to show errors, debug info,breakpoints ect...  I don't understand why if editors say Atom and Webstorm compile typescript fine and breakpoints are hit, then this should mean that the core and language service are good to go, but then say Sublime or VS Code has a problem why is this a bug in typescript, it could be but then would that not mean it is a bug for all editors as long as those editors conform to your specs.  I do understand your quote that it takes time to get editor support, and it is necessary in order for the language to be adopted for typescript to provide plugins for some ide's by default and that those plugins need to work with each new release,  but then you are endorsing or officially supporting X ide's over others.  I just prefer having the core feature set independent of any vendor's ide's.  You can certainly maintain official repos for plugins and keep them up to date with the official releases but not all plugins have to be working when the each version of typescript is released, it could be that x ide's plugin has some bugs but it works fine in other ide's now and we will have it fixe for x ide shortly, this also pushes the responsibility on the ide vendors to provide support for the language if they want their ide to be better.  Like any javascript framework say react, angular, they do not wait for certain ide's to add support for their framework before each release, of course basic javascript support works in the ide's but many add specific react angular features to their ide's to enhance debugging and error checking support specific to that framework.

So enough of the complaining, :)  Seriously not a complaint just a suggestion.

I really like typescript so far, Thanks for the 1.5 release and looking forward to finished es6 feature set with some es7.  

Thanks,
Dan

**Comment by danquirk** [comment]
@delebash definitely hear this loud and clear, it's something I have actually spent quite a bit of time thinking about lately. 

I complain more than most so don't feel bad about the occasional light rant ;) Always happy to have feedback.

**Comment by RyanCavanaugh** [comment]
Two things to add.

First, I think we're in general agreement (internally) that the 1.5 release cycle was *waaaaaay* too long. It initially made sense to align this release with the VS schedule, but software schedules are prone to certain things that ended up making this release interval much longer than intended. This won't be repeated.

Second, getting our language working in at least one editor is a critical part of vetting the decisions we're making. It would be imprudent to release a commandline compiler that had syntax, semantics, or performance characteristics that ended up having bad downstream effects on editors. We don't necessarily need to make VS be the first editor to fully support each iteration of the language, but we do need *some* editor in common use to be usable before we can have confidence that we're releasing a good next step. We're making progress toward some architectural changes that will allow us to iterate on the VS side faster so that we can tighten up that feedback loop.

**Comment by delebash** [comment]
Glad to hear about shorter release cycles, I am all for short sprints vs long hauls.  This was just food for thought, so in the end as long as typescript releases are not held back for long periods of time by problems with x,y, or z ide integration problems then its all good.
