### ISSUE TITLE
Add support of Item method (stage 3)

### ISSUE THREAD

**Issue by Kingwl** [microsoft/TypeScript#40695]
## Search Terms
esnext, item method

## Suggestion
https://github.com/tc39/proposal-item-method

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
Wow, it's already stage -3! ;-)

**Comment by RyanCavanaugh** [comment]
Linked repo says stage 2, can you clarify?

**Comment by IllusionMH** [comment]
Closest think I saw today: https://twitter.com/robpalmer2/status/1308292088484696066

**Comment by MartinJohns** [comment]
Proposals overview lists it under stage 3: https://github.com/tc39/proposals

**Comment by lifaon74** [comment]
This `item` proposal changed  to `at` recently: https://github.com/tc39/proposal-relative-indexing-method
It could be worth to wait for stage 4?

**Comment by rbuckton** [comment]
The name `at` is tentative. The current status is that the same investigation as to the viability of `item` needs to be performed for `at` or some other method name to ensure there are no web compatibility breaks with the name. This doesn't mean waiting for stage 4, but it does mean waiting for the champion and implementers to settle on an acceptable name that will not break web compatibility.

**Comment by rbuckton** [comment]
It looks like `.at` [caused a web compatibility issue](https://github.com/tc39/proposal-relative-indexing-method/issues/41), but since that was in application code and not in a library/framework the champions were able to reach out to the engineering team for the web site that was broken and they were able to address the compatibility issue so that `.at` would be unblocked.

Since `.at` is shipping in v8 92 and SpiderMonkey 90, I think its fair to say that `.at` is the stable name for the feature.

**Comment by rbuckton** [comment]
It seems this was addressed in #46291
