### ISSUE TITLE
`debugger;` statement in typescript's src/compiler/debug.ts legit?

### ISSUE THREAD

**Issue by JasonKleban** [microsoft/TypeScript#40729]
I'm trying to profile some eslint performance stuff and I keep hitting this debugger statement, even if I blackbox it.  It has been there for at least 7 months, but is it a mistake to have left it in?  The only other examples I found in this repo seem to be test cases.  If this is legit to leave in, I might even expect a comment there like `// this is legit to leave in` to avoid out-of-my-depth questions like this one.

https://github.com/microsoft/TypeScript/blob/b5bd38bcdc4d3c49bc58f255384caeeaed1aa85b/src/compiler/debug.ts#L47-L54

**Comment by andrewbranch** [comment]
I have always assumed it is, and it is occasionally useful; however, it’s also occasionally super annoying because certain methods in certain test harnesses call things like `host.readFile(file)` inside a try/catch knowing it will often fail, and that particular `readFile` (or whatever it is, I don’t recall) uses `Debug.fail` instead of throwing directly. (The result is an incredibly painful debugging experience for those particular tests.) So I would not be opposed to removing it, or wrapping it in a check for a certain environment variable or something. Maybe @rbuckton has opinions here?

**Comment by DanielRosenwasser** [comment]
It sounds like any use of `Debug.fail()` that's not actually a violated assertion should be a thrown exception instead.

**Comment by andrewbranch** [comment]
@JasonKleban could you share the stack you see when you’re hitting this?

**Comment by JasonKleban** [comment]
@andrewbranch On typescript 4.0.3:

`cross-env NODE_OPTIONS=--max_old_space_size=8192 node --inspect=8880 ../../node_modules/eslint/bin/eslint.js ./src/ --ext js,jsx,ts,tsx,json --quiet`

![image](https://user-images.githubusercontent.com/17498172/94318555-cd02bb00-ff56-11ea-836a-b1a45cd8e8b6.png)

This seems to happen regularly during this seemingly infinite run of eslint - it doesn't matter how long I wait to attach the debugger, I will hit this within a few minutes.  

This experimental branch of my code enables `deprecation/deprecation` eslint rule (to survey all the deprecated stuff we use from another library) which requires `@typescript-eslint/parser` and the `parseOptions.project` parameter which has been documented to increase the amount of work needed.  I suspect a memory leak - it doesn't finish after hours and will probably eventually run out of memory.

**Comment by andrewbranch** [comment]
Ah ok, so it looks like someone else (whoever owns deprecation.ts) is calling into our API incorrectly. I still would be fine with removing that debugger statement, but I don’t feel that strongly about it 🤷

**Comment by sheetalkamat** [comment]
i would prefer for it not to be removed as its easier to diagnose issues where assumptions break
