### ISSUE TITLE
in does not sufficently narrow union type

### ISSUE THREAD

**Issue by Nokel81** [microsoft/TypeScript#40753]
**TypeScript Version:**  4.0.2

**Search Terms:**
- in narrowing 
- keyof union in union

**Code**

```ts
type Child1 = {
    a: string;
    b: string;
}

type Child2 = {
    c: string;
    d: string;
}

type Parent = Child1 | Child2;
type ParentKeyFail = keyof Parent // this is `never`
type ParentKey = keyof Child1 | keyof Child2; // keyof Parent fails with `ParentKey` being `never`

const key: ParentKey = "a"
declare let p: Parent

if (key in p) {
    /**
     * this is typed as implicitly `any` because it claims that 
     * `"a"` doesn't exist on `Parent`, even with the `in`
     */
    console.log(p[key])
}
```

**Expected behavior:**
Because of the test `key in p` and because `key` is limited to being a `keyof Parent` (or more specifically a member of the union of the `keyof`'s `Parent`'s union members), it should be able to have `p[key]` be specifically `typeof Child1[key] | typeof Child2[key]` in general and specifically here (because of the `in`) to be `string`. 

**Actual behavior:**
`p[key]` is typed as `never`

**Playground Link:** 
https://www.typescriptlang.org/play?#code/C4TwDgpgBAwgFgSwDYBMCMUC8UDeAoKQqAQwC4oBnYAJwQDsBzAbgKICNyrbGWBfPPKEixEqAExZcrQgGNONes2lQU87kv6Dw0AArFqEOsEnxk6KAB8RZsSyG79h4AGkIIAGLFkkgNZuA9gBmUHoGRlAA9BFQwIgUUAjxAAZ0EABuENRJWsKhTq4gvgHBpqgYVn4gQdbiTJHRldV54YFeSPEA7gixUEnNLm5JUGwQir2pGVkCMv50VFCV5P0FkgBExKt4KBAySI5QSBDGYEuORgIIwQAUlQl0UGAAlFJEkQBUb8pQbzFxCfH2FAkeIIAC2YCQCBk3SQhSSxDoICGIxkxAArhRoN0oLsvKCAXBiMYvj8kutVkMUP4IBQ6AByYwQAAeiWMs16-SSABooOlDFAuj1YtAkvRsq9vhFlDM5v5DgA6JD+BhXMAAbUqAF1HnheEA

**Related Issues:** 
Maybe #33014

**Comment by andrewbranch** [comment]
There are three problems here:

1. The type system has no idea that `key` is `"a"` because you’ve manually widened it to `"a" | "b" | "c" | "d"`. There’s no way you could narrow `Parent` if that’s all you know about `key`.
2. Even if you removed `: ParentKey` so that the type of `key` is `"a"`, we apparently only narrow on the pattern `"stringLiteral" in someUnion`—it’s not enough to say `key in someUnion` where the type of `key` is `"stringLiteral"`. This is probably for performance reasons. We’ve seen in the past the addition of more control flow nodes like this add 1–3% overhead, which is almost always not worth it.
3. Even if we didn’t have that limitation, `in` narrowing is still inherently unsafe, because there is no guarantee that an object of type `Child2` _doesn‘t_ have the property `a`. The only thing we can say for sure about a `Child2` is that it has a `c` property that's a `string` and a `d` property that's a `string`. It can have any number of additional properties of any name and any type. Given the significant caveats that come with `in` narrowing, I think that makes addressing (2) less attractive.
