### ISSUE TITLE
When `jsx` is `react-jsx` or `react-jsxdev`, TypeScrip won't report error if @types/react and @types/react-dom not installed but slient give it any type.

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript#40759]
**TypeScript Version:**  4.1.0-dev.20200924

**Comment by weswigham** [comment]
So... we definitely seem to issue an error. Except in one scenario.
If neither `react` nor an appropriate version of `@types/react` is installed, we issue
![image](https://user-images.githubusercontent.com/2932786/101087956-d2d4d800-3567-11eb-9468-1e9318252ee2.png)

If `react` is installed, but _not_ `@types/react`, we issue:
![image](https://user-images.githubusercontent.com/2932786/101087723-783b7c00-3567-11eb-8c6d-aff217c241ff.png)

but only under `noImplicitAny: true` (same as other imports which don't resolve to `.d.ts` files but to resolve to `.js`, turns out). Do we want more? What should we be checking for, and what should the error say? The same, but make it not `noImplicitAny`-specific? Something specific to JSX?

**Comment by RyanCavanaugh** [comment]
Allowing modules to resolve under `noImplicitAny: off` is the intended behavior
