### ISSUE TITLE
Compiler error when try to use destruction for strings (only ES5 target)

### ISSUE THREAD

**Issue by MaxGraey** [microsoft/TypeScript#40782]
## Search Terms
string, chars, array destruction

## Suggestion
This fully legit operation on JavaScript and TS targets more than ES2015, but for ES5 TypeScript print error: `Type '"...."' is not an array type. (2461)`.

## Examples

```ts
const [D,e,s,t,r,u,c,_t] = 'Destruct';
const [T,h,...is_] = 'This!';
```

ES5: [playground](https://www.typescriptlang.org/play?target=1&ts=4.1.0-dev.20200926#code/MYewdgzgLgBA2gEQDQFMkSVJAnJBXJYJAfSgF0YBeGAcgRWmz2ChoG4AoUSWOAFSQALJADoxASwjEK1Gn0GSAhOw4wYQA) (errors)

ES2015:  [playground](https://www.typescriptlang.org/play?target=2&ts=4.1.0-dev.20200926#code/MYewdgzgLgBA2gEQDQFMkSVJAnJBXJYJAfSgF0YBeGAcgRWmz2ChoG4AoUSWOAFSQALJADoxASwjEK1Gn0GSAhOw4wYQA) (ok!)

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
ES5 runtimes don't support destructuring, and ES destructuring on strings is based on graphemes instead of characters so there's no straightforward downleveling that has the same semantics as the undownleveled version.

You can enable `--downlevelIteration` if you want to take the risk and do it anyway.

**Comment by MaxGraey** [comment]
I see. Thanks!

**Comment by MaxGraey** [comment]
> ES5 runtimes don't support destructuring, and ES destructuring on strings is based on graphemes

One minor corrections - not graphemes, but proper UTF-16 code points (instead USC-2 as usual) same as `Array.from(str)`

**Comment by RyanCavanaugh** [comment]
Thanks, I always mess up this terminology 😅

**Comment by danieltroger** [comment]
Hey guys, I did not have compiler errrors but for me destructuring a string simply transpiled incorrectly, how can that be "working as intended"? I Accidentally thought I was using babel and opened and issue there: https://github.com/babel/babel/issues/12456

Here's a reproduction of it: https://www.typescriptlang.org/play?noImplicitAny=false&target=1#code/GYVwdgxgLglg9mABMOAnAtgQygB1TCAUwAo8DCBKAbwChFEIEBnKRAbQDouyiB9TVKkwBPALqIAvIgByIdACNCqUviIUOUOAGUo+MAHNiFANx1EAG0KtUhAG5KmhACa8ehSYjf9BIjjfuojkYANGYoGNhQzq6q7lJsoqb0-g7RbhzhAKKYEAAWxMR5AjlRqMGIMGBOhAAeFJIAfMhoWFBRLuk4IEz5XBzEldU1iABkI4gAhANVtYgApIgAzPUA-OwARIjr5UVC0EriAFzsuyUHFBdJiDZQIKhI4a3tMeR+dqlGHABWcJXE6+sTDQAL40GiPbBuYgARgATIsACwAVgAbAB2AAcAE5oQAGCg0IA

If you go there and click "run" and have your console open at the same time it will throw an error.

I'm not sure if I'm having the same issue as this issue and I'm afraid of opening a duplicate, but it can't be intentional to break my code when ran in a browser, can it? What crappy functionality is that?

**Comment by RyanCavanaugh** [comment]
@danieltroger when I run your snippet through the TS Playground with downlevelIteration enabled, it produces the output `"12 345 678 910"` which seems expected. There's an error identified when downlevelIteration is disabled because TS knows it *needs* downlevelIteration enabled to transpile this code. It sounds like you have a parcel problem (or misconfiguration) if you're not seeing that error in your build process.

Obviously we don't intentionally break your code; please be constructive and assume good faith (both here and on other repos!).
