### ISSUE TITLE
Infer keyword should work with unused generic type parameter of a superclass

### ISSUE THREAD

**Issue by nicky1038** [microsoft/TypeScript#40796]
**Search Terms:** infer keyword subclass superclass generic type parameter

**Code**

```ts
class A<T1, T2, T3> {  }

class B<T1, T2> extends A<T1, T2, boolean> { }

type FirstAParam = B<string, number> extends A<infer T1, any, any>
    ? T1
    : never;
```

**Expected behavior:** `FirstAParam` is `string`.

**Actual behavior:** `FirstAParam` is `unknown`.

[**Playground Link**](https://www.typescriptlang.org/play?ts=4.1.0-dev.20200927#code/MYGwhgzhAECCA8AVAjAGmogTOxBmAfNAN7TQC+AUBaJDAEJJoaaECmAHgC6sB2AJjAQoc2aACMA9hJCswPQiUoVOATwAOraADEAlgCcInWAAUwesAFtoAXmgNDenTwDm6HgFcLY1nrZdeAnDwTgBmPhhMciroUfgUpKQA-BHxCQBc0DysAG4+ANxAA)

**Comment by nicky1038** [comment]
Possible, not pretty, but still usable **workaround** for **temporary** problem solving on the user code side:

```ts
class A<T1, T2, T3> { 
  readonly stub: T1 = {} as T1;
}

class B<T1, T2> extends A<T1, T2, boolean> { }

type FirstAParam = B<string, number>['stub']   // FirstAParam is string
```

[**Playground link**](https://www.typescriptlang.org/play?ts=4.1.0-dev.20200927#code/MYGwhgzhAECCA8AVAjAGmogTOxBmAfNAN7QBQ00ATgKZgAmA9gHYgCe0EALgK4BGAXBmTQAvMQC+0SEIDcpcaVKhIMAEJI0GTIWoAPTtSZ0YCFDmzReDBiFpNCJBaU6sADtWgAxAJaUusAAUwSjAAW1FodS5KbyYAc3QmblDeakp8AG0Aci4+LIBdIA)

**Comment by jcalz** [comment]
This is working as intended.  See [this entry](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-type-inference-work-on-this-interface-interface-foot--) in the (somewhat outdated) FAQ.  The type system is structural, not nominal; two types are the same iff they have the same *structure* or *shape*, not iff they have the same *name* or *declaration*. 

In your code above, the type `A<T1, T2, T3>` is exactly the same as the empty object type `{}`.  They are just two different names for the same type.  To expect the compiler to be able to infer `string` from the type `A<string, number, boolean>` is to expect that it should be able to infer `string` from the type `{}`, which obviously doesn't work... just because the *name* you used to refer to `{}` mentioned `string` it doesn't imply that the type itself depends on `string`.  (In practice the compiler sometimes does remember the name you used to refer to a type, and these in-principle-impossible inferences actually do happen; but you really can't rely on them.)

Your workaround is the recommended way to deal with cases like this: make sure your types are structurally dependent on the generic type parameters... the easiest way being to give them members of those types, like your `stub`.  In any case this behavior is not a bug, but the expected behavior of TypeScript's structural type system.

**Comment by nicky1038** [comment]
@jcalz Thank you for explanation and sorry for not reading the entire FAQ!

It's a sort of sad because I have a complex scenario where one generic parameter of a class should be used later by class consumers, though there are no any properties of its type inside the class. OK, I understand, there is nothing to do except using the workaround :(

BTW, in this case:

```
type FirstAParam = A<string, number, boolean> extends A<infer T1, any, any>
    ? T1
    : never;
```

`FirstAParam` is `string`, and it becomes a bit confusing why does this work one way in the first example and another way in this one.

**Comment by RyanCavanaugh** [comment]
Thanks @jcalz
