### ISSUE TITLE
window.requestIdleCallback type missing

### ISSUE THREAD

**Issue by nstepien** [microsoft/TypeScript#40807]
**TypeScript Version:**  4.1.0-dev.20200925

**Search Terms:** requestIdleCallback

**Code**

```ts
requestIdleCallback(() => {})
```

**Expected behavior:**
`requestIdleCallback` is typed.

**Actual behavior:**
```
Cannot find name 'requestIdleCallback'. ts(2304)
```

**Playground Link:** 
https://www.typescriptlang.org/play?#code/E4UwjgriDOAuCSATANiAwgQ2cgRhgxgNYAUxAlAAQC8AfBQN4C+ZQA

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/21309
The previous issue was labelled as "working as intended" over 2 years ago, but I don't think the API is experimental anymore. It is available in Chrome/Firefox/Edgium, and Safari (behind a flag).
https://www.w3.org/TR/requestidlecallback/
https://w3c.github.io/requestidlecallback/
https://caniuse.com/requestidlecallback
https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback

**Comment by utsav0209** [comment]
Do we want the support for this? 

As I read from [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback#Browser_compatibility) safari still does not support the `requestIdleCallback`.

If we want to have support, I can make a PR.

**Comment by RyanCavanaugh** [comment]
I want to discuss our experimental API coverage in lib.d.ts before committing to accepting a PR, but certainly it should eventually be in there

**Comment by thw0rted** [comment]
Ryan, on the previous issue you said that TS doesn't support experimental APIs.  The MDN page for `requestIdleCallback` is marked as experimental but so is `fetch` -- the biggest difference I can see is that `requestIdleCallback` comes from a "Proposed Recommendation", rather than a "Living Standard".  Is the status of the spec the issue here?

(It strikes me as strange that `requestIdleCallback` doesn't appear to have gone anywhere in over 3 years, but is supported in all modern browsers except Safari.  I guess the old draft didn't have any major problems so they've left it alone?)

**Comment by nstepien** [comment]
https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1029
It's in TS 4.4! Thank you
