### ISSUE TITLE
Can't get the type of the nth argument of an overloaded method / polymorphic method

### ISSUE THREAD

**Issue by crubier** [microsoft/TypeScript#40816]
**TypeScript Version:**  4.1.0-dev.20200928

**Search Terms:** constructor parameters overload polymorphic 

**Code**

```typescript
export default class Zoom {

  constructor(opt_options?:{}){
    return;
  }
    
  on(type: 'change', listener: any): void;
  on(type: 'error', listener: any): void;
  on(type: 'propertychange', listener: any): void;

  on() {
    return true;
  }
}

type EventType = Parameters<InstanceType<typeof Zoom>["on"]>[0];


const w1:EventType = "change"; // Should typecheck OK, but does not
const w2:EventType = "error"; // Should typecheck OK, but does not
const w3:EventType = "propertychange"; // OK because it's the last
```

**Expected behavior:**

I use a library which defines a class like this:

```typescript
// node_modules/@types/ol/control/Zoom.d.ts
    
export default class Zoom {

  constructor(opt_options?:{});
    
  on(type: 'change', listener: any): void;
  on(type: 'error', listener: any): void;
  on(type: 'propertychange', listener: any): void;

}
```

Now, I would like to get the type of the first argument of the `on` method.

I expect to get this kind of result:

```typescript
type EventType = "change" | "error" | "propertychange"
```    

**Actual behavior:**

But sadly, when I try:

```typescript
type EventType = Parameters<InstanceType<typeof Zoom>["on"]>[0];
```

The result is like this:

```typescript
type EventType = "propertychange"
```

Only the last declaration seems to be accessible.

Here is a screenshot of VSCode showing this:

[![VScode screenshot with only propertychange][1]][1]

On the other hand, typescript still knows the actual type, because VSCode shows me this:

[![enter image description here][2]][2]

So there must be a way to get this working.... Any idea?

**Playground Link:** https://www.typescriptlang.org/play?ts=4.1.0-dev.20200928#code/KYDwDg9gTgLgBAE2AMwIYFcA28DGnUDOBcAWhBALZwDeAULXHDhAHYExTo4zQAUEYGAH0BMAJasCAfgBc1AL4BKOo0ZRgMdFBYBuBnHn7G+1rxgBPMMBlwA5DgAWqFgHNgtgDRxMY9sBbAUDbO5oo2AG4QYgh6jKYWVja2gVDQnt6+MP6BwSyhEVExJixmltZ2YKlWsOaOzm7pPn4BQXAhYXCR0XrFvIo0RnDqmtpwHOjAsQa0hrQJwHAAouH+MAAqZXAAvHAACqhQqBQagQQAPACSbDDOOMAbVmfzEMik5BQAfADaAESsPwBdb4ABgBPVozGucAA7gBGGTLVYPBY7H51VzAH46OAAehxcAAyg4IFgEGMyo5gDgANZwADyAGkvAAjdDwBAQYDEFgQGAQyTwaEAJgRKxY602qJS0CxuPxRJJmDJ80pNPpTLgrPZnO5vP5UOhAGZRUjJXAfpUBIELOi3LK8erNVSMAQFmIYLZiDAHAt8OwgA

**Related Issues:** 

Question on stackoverflow https://stackoverflow.com/questions/64107789/how-to-get-the-type-of-the-nth-argument-of-an-overloaded-method-polymorphic-me

  [1]: https://i.stack.imgur.com/7DmpD.png
  [2]: https://i.stack.imgur.com/mg3ZH.png

**Comment by MartinJohns** [comment]
https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-inference-in-conditional-types

> When inferring from a type with multiple call signatures (such as the type of an overloaded function), inferences are made from the last signature (which, presumably, is the most permissive catch-all case). It is not possible to perform overload resolution based on a list of argument types.

**Comment by crubier** [comment]
This makes sense, but why does VSCode succeeds in finding the alternatives? I think this auto completion is based on the TS language server

**Comment by MartinJohns** [comment]
> This makes sense, but why does VSCode succeeds in finding the alternatives?

I'm not sure what you mean. Do you mean the auto completion in your screenshot? That operators on a completely different value, it's not using a conditional type.

**Comment by jcalz** [comment]
>  There is no way to get this working.

Well, there's always [this](https://stackoverflow.com/a/64107995/2887218)... but it's not pretty.

**Comment by AlCalzone** [comment]
@crubier if you're trying to strongly type an EventEmitter interface (or something similar), the following pattern works pretty well for me:
https://github.com/AlCalzone/node-zwave-js/blob/86ee24d69b8172c4c2ab8d6dd0ca90dc1569424d/packages/zwave-js/src/lib/controller/Controller.ts#L102-L145

**Comment by crubier** [comment]
Thank you @AlCalzone but I dont want to modify the type of the event emitter-like interface, I just want to use it.

@jcalz your solution sounds like it could work... I might try aha

**Comment by crubier** [comment]
@MartinJohns 

> Do you mean the auto completion in your screenshot? 

Yes

> That operators on a completely different value, it's not using a conditional type.

Ok. There does seem to be a design limitation behind the scenes here indeed, because the way to get there might be different, but the type of these two strings (in my two screenshots) should be exactly the same in the end. I mean, as a user this is what I expect.

**Comment by zikeji** [comment]
I'm running into the same issue. I can definitely see why it's a design limitation though. I have no control over the events as they're from a third party library, so I can't use a simple fix like the pattern suggested by AlCalzone. And the overload suggest by jcalz only supports so many different events.

My goal is "simple", to be able to map a listener's parameters to a function in my class based on the name of the event. At least, it sounds simple. In practice it is apparently complex.

I haven't quite mapped the overload to the functionality I desire (type completion on my "run" function) - not even sure if it's possible. But it seems like I should figure out some other pattern to make this work.

[here is my playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgCoAthQCYAU5RgCeAogG4TgDOyA3gFDLIAUjTyEF4AXMgESdKYAPIgIfZAB9+g8KgDuAez4AaNkwA2wKpDFRezALZUA5rx1RQJlcgB09giaq8AriADWIRfJABtALoAlMgAvAB8yGSKwNhsgbwAyoqGEABKcCDYyRhYeATEAMIacFRUANxszLJgvAJcYBhQEOI2WjqU0AYIim41yCAuhgBG0MHhkdHY8chJKemZ2Zg4+IRERSXlldW11QBiPVCqyG26nSwE+v2DI1ABYxFRMdOzaRlZhjnL+WvFpRVMVXqO3qu2AFCOJw6l2YF14A2G0DuoQek2eyVeCw+Szyq3Wf3oAF96PRsBAEMUmshQJBYIgUC95u9PjjCr8aAwmIoQLxmStiOQhJsifRiAAHFDCChQDSKODYKgAHlQERCbFQHAAHrp5XR1Cx7LZHM4qSAYNBkABBACM01AZqgyFSVrK+ocUCcvDt5otACZbabzakff92MwDUbPQGHRaAMz++2OmMusNuj0mhMWgAs8cDmbYBOQAH5kL49SnDe7jdb7o6rTZyxHLX7kY6fWp2K6K2nYzXUjH6+HK7ws7280x-MgeZrteyy4O017ozbIwmncn58bF02cw6gyGARuV9640fdzH80WS3PU1WbS2nQOb8Pm+Mg+3Q4fLXH7+fx5O0NOlA6hyH5Pum3rLuBu7Op2jZbr6O6thexalh2DZDpad6vnWsEYQh94+mwE5ThAWpAbOaGfvBkFbk6yFXpRYHVveVpEf+GREMSYooAKchEOKoTICscApDSiqStAMpyoqDJvIsuR8j8Gy+AA5FyKn+GEvjwjcmm+AADP4Ir8SgAAy2inA6IRCQQIkQGJCrCaJ0DiVKUnygqsmYry3x4lQqnqXpOnQHpVqaRU9DUtA8BII6bh6MIopgMAXIURwQLILxDQmRUwpwEMFiIGAyDkhscUgHoVKGKKGgQCk1DlQlSUpSAaXVCG3StWAUAuAgYCKFAzCKM1qW8Kk8XQIlyWpcEIFMGAmBULY1SCcN02tct9QhkSTD5YVfXICURAgAgyA9SA6FpuZ7R6NMuBQMk2gQAqjzYGEuXEqVpSZfUohpBNDqkTOjXmiBnUWL1-WDbNepUC44qDXN7DbDIv1iHweoEoE21sEdJ1nW4zAwx24OKLVtgyiYzB8Og0DiNj+aEp9bI-UI+wuFA40VeaQPkSDDpg6l3WQwNRO6h2cMI8wSNMCjdRswcGMdljOO7VQx2nedzCQDo5jdVYxPsKT5OU9rEA6DYNN03wDNMESRJAA)

**Comment by zikeji** [comment]
Another variant - I extrapolated from jcalz's design to make a "solution" to fit mine. Not sure if it's workable though. The main drawback is if the function type interface doesn't have enough members the EventParameter type falls back to "any". So you can't just make one mega type to cover it (which is why I believe you had the fallbacks in the overload).

Also, doesn't really fit the ideal of keeping it simple for library user's - the goal is to let them extend the "runner" and specify the type in the constructor. This latest design requires that they specify the type in two areas - the type parameter and the constructor options.

It's fun in theory, but it'd be nice if the logic to infer could recursively infer or have a spread syntax of some sort.

[Playground](https://www.typescriptlang.org/play?ssl=46&ssc=38&pln=46&pc=49#code/JYOwLgpgTgZghgYwgAgCoAthQCYAU5RgCeAogG4TgDOyA3gFDLIAUjTyEF4AXMgESdKYAPIgIfZAB9+g8KgDuAez4AaNkwA2wKpDFRezALZUA5rx1RQJlcgB09giaq8AriADWIRfJABtALoAlMgAvAB8yGSKwNhsgbwAyoqGEABKcCDYyRhYeATEAMIacFRUANxszLJgvAJcYBhQEOI2WjqU0AYIim41yCAuhgBG0MHhkdHY8chJKemZ2Zg4+IRERSXlldW11QBiPVCqyG26nSxekM7IFlZjEVEx07NpGVmGOcv5a8WlFUxV9R29V2wAoEmkdSECWAAA8jicOvoWAQkQNhtAAncJo9EskXgt3ks8qt1r8toCZPUAILgylCABC8O0pyRzCaVBcGj6Q0Uig0EAyWIeU1xc1ei1yK0KP02AF96PRsBAEMUmshQJBYIgUM95m8PsTpRs6GxFCBeAapaR6nKFcQAA4ochCFZwFKa0JsS1fZ3UDgw3TYGgMdgsbbqkAwaDIKkARlazMRvFAUagMYATNMMkQ1KGAUJk5Ho-T48dE3pC6nkPTM7xs7n2PmeBGqwVSwiKy3owVa8h6+owxSU9GACLt8tnYdpke9-t58NT5AkcftTuLkizkBENiy5AAfjYtF8AH0IzHY-7AzQbiATPvz8g61v-LxXe7oFQADxU9OXyhBlh7FsRwrmzTFQgibN7x-R8+y3MJdwAMkPE8zxLP9MmvMBLFve90KfIgX2QN8IE1L8awwgDmCAkCCPA8YoL3atfwIhDkGQpgj1PUBkDbSisJwu8mL4giiJIsjPx7fjAIcKAnDooIILgoh7yk1ikJQ7iQGQMdpJvISdIvUTXwIN1SI-T8Z2k6jZPk5T6Mgrd7ys9T2M0s9lz07CrHvTzjOI0z3ygL8N2smi5NArcHOU3yWOUhC2AIip6AdJ16lQIhHVCJcAygRAwE-dwICIRQYCXepxOgGx9LCBV6A1aB4CQZBUjcPRhHtMBgDNYM2HDX0GkyiAKnleg4CGCx8uQFVjVakA9E-VBpIGjLHQiYBDHtfkUj9Ob2s67qQF6phqj+aaeuwlwEDARQoGYRQDp63g9ugDqup64IQ3YMBMCoWxqmyh73qO-76jO+UmHGybrr7KgiBABBkCgNwbOAiLeAGyqoF8VAglfKBkm0CBP2FMIRoVGbSnKoR9hcKAXrTCAA3-GgGc-SFwFpw4Ii+7ojsu67buYT6Bw5R07q+0Nww5sAub4AdZUCcG2BKeHEeRkBmAuCArn06ZcAJwwiZJyYeYHPmqD5CBbA0RQTC1xRLiVnd6FGi2wAjHQMmakJ+ggeRqc5g4GeFipQC9hHrY15g+EuMA+CVoA)

**Comment by MartinJohns** [comment]
@jcalz
> Well, there's always [this](https://stackoverflow.com/a/64107995/2887218)... but it's not pretty.

I will pretend that I didn't see this. 🤢

**Comment by Patrick-Remy** [comment]
> It's fun in theory, but it'd be nice if the logic to infer could recursively infer or have a spread syntax of some sort.
Since TS 4.1 supports conditional recursive types, is there any chance for an overload rest/spread operator?

Something like this:
```ts
type EmitSignatureFromOn<T> = T extends {
  (event: infer E1, listener: (...args: infer L1) => any): any
  ...RestOverloads
} ? {
  (event: E1, ...args: L1): boolean
  ...EmitSignatureFromOn<RestOverloads>
} : T extends (event: infer E1, listener: (...args: infer L1) => any) => any ?
  (event: E1, ...args: L1) => boolean : never
```

Or did anyone find a related ticket/proposal for this?
