### ISSUE TITLE
"This file is not currently part of a tsconfig project" in TypeScript project

### ISSUE THREAD

**Issue by DanTup** [microsoft/TypeScript#40821]
When I open the the source for [Dart-Code](https://github.com/Dart-Code/Dart-Code) and click the TS version number in the status bar, I see this - despite there being a tsconfig.json file:

<img width="971" alt="Screenshot 2020-09-14 at 11 19 05" src="https://user-images.githubusercontent.com/1078012/93074413-3bed3380-f67c-11ea-8ead-bd21bc038444.png">

Clicking the file opens the existing tsconfig file (so it must be in the right location!).

**Comment by mjbvz** [comment]
Tested in the dart project but I believe this is a configuration issue. I opened `src/extension/analysis/analyzer_das.ts` but it looks like `"src/extension"` is explicitly listed in the `"exclude"` section of the tsconfig. You can confirm the file is not considered part of any project by running `TypeScript: Go to Project Configuration` in it.

Clicking the link still happens to work in this case because normally when a file is not part of any project, clicking on the `create tsconfig` link really does create a `tsconfig` at the root of your workspace. Since this file already exists though, we just open it

**Comment by DanTup** [comment]
@mjbvz that folder is excluded because I don't want it to be compiled into JS (as it's handled by webpack). I still get analysis/language services for the file, so it seems strange to not let me change the SDK setting (which as far as I can tell, the exclusion makes no difference to?).

**Comment by mjbvz** [comment]
Try creating multiple projects for this case: one for compiling named `tsconfig.build.json` and then one or more `tsconfig.json` projects used for IntelliSense
