### ISSUE TITLE
Wrong autoimport presense for dependency not in package.json

### ISSUE THREAD

**Issue by zerkalica** [microsoft/TypeScript#40911]
Demo: https://github.com/zerkalica/ts-references-autoimport-bug/tree/wrong-autoimport-presense

TypeScript Version: 4.0.2
VSCode Version: 1.49.2
OS: Ubuntu 20.04.1 LTS

Package 'b' depends only on 'c', package 'c' depends on 'a'.

Autoimport in any file in 'b' sees 'a' as a relative import.

Steps to reproduce

1. Clone, switch to wrong-autoimport-presense branch, yarn install
2. Open lib/b/b.ts in vscode, type someA
3. Expected: no autoimport, actual: autoimport present and broken (relative)

**Comment by andrewbranch** [comment]
Hmm, this is an interesting case. I have personally put a lot of effort into helping auto-import detect various monorepo-like structures and use heuristics to prioritize the best possible paths for auto-import to use. But I’ve mostly tried to avoid introducing ways for auto-import to give you _no results_ despite knowing about modules that would satisfy your request. One long-standing exception is the package.json filter.

Right away, we see two possible paths to the module containing `someA`—the non-relative symlink through node_modules, and the relative path outside the project root. If the one in node_modules were in your package.json, we would know that it is _much_ better than the other, and not even offer the relative one. However, since it gets filtered out by not being a listed dependency, we’re left with the relative path. There’s no actual rule that prevents the relative path from working, so we offer it to you. I would be extremely hesitant to break that behavior, as it seems very prone to producing false positives. Ultimately, auto-imports are _suggestions_, and you’re responsible for validating them. I’m very open to _improving_ what suggestions you get based on heuristics, but very wary of _removing_ them based on heuristics.

**Comment by zerkalica** [comment]
Some of this problems i try to "fix" in ls plugin: https://github.com/zerkalica/ts-plugin-autoimport-fix/blob/master/index.ts

AutoImportProviderProject.getRootFileNames hack helps to include all dependency project files, not only index.ts and collect all monorepo subpackages roots.

proxy.getCompletionsAtPosition removes unnecessary monorepo packages from suggest.

proxy.getCompletionEntryDetails replaces relative imports to absolute for monorepo subpackages.

Main problem not with AutoImportProviderProject, somewhere later project.getSourceFiles() returns relative imports for suggestion.

**Comment by zerkalica** [comment]
Working as Intended? Looks like heuristic miss: 'c' package.json is not used, relative import calculated from imports tree without this information.

I think, autoimport can suggest 'a' in 'b' if 'c' depends on it, but not relative.

c.ts:

```ts
import { someA } from '@some/lib-a'
```

b.ts:

```ts
// autoimport:
`import { someA } from '../a'`
```

**Comment by andrewbranch** [comment]
I explained [here](https://github.com/microsoft/TypeScript/issues/40911#issuecomment-703874791)

**Comment by nin-jin** [comment]
Expected:
- autoimport present
- suggesting non-relative path
- autocoplete adds import and dependency to package.json
