### ISSUE TITLE
const enums shouldn't start from 0

### ISSUE THREAD

**Issue by apirila** [Microsoft/TypeScript#4097]
Current const enum implementation of TypeScript is problematic due to type coersion in JavaScript. The first element in enum is compiled to 0, which equals to false. Others equals to true. It would be better that all values in the const enum would evaluate to true. 

I know that this is a breaking change and while in TypeScript only project, the change shouldn't brake much things, but with external interfaces this change might be problematic.

**Comment by RyanCavanaugh** [comment]
I can't think of a language where it *isn't* the case that an implicitly-numbered enum's first member is false when coerced to a boolean.

If anything, JavaScript programmers should be more equipped to deal with this than e.g. C programmers, because we've had to deal with other falsy primitives like `""`.
