### ISSUE TITLE
Different behaviour of `undefined extends 1` in `.d.ts` file versus `.ts` file.

### ISSUE THREAD

**Issue by SirJosh3917** [microsoft/TypeScript#40982]
**TypeScript Version:**  4.0.2

**Search Terms:** extends, behavior, undefined, constant, number, optional, required

**Code**

```ts
// in .d.ts
export type T = undefined extends 1 ? true : false;
```

```ts
// in .ts
export type T = undefined extends 1 ? true : false;
```

Make sure to have strict null checks enabled - in tsconfig.json:
```json
{
    "compilerOptions": {
        "strict": true
    }
}
```

**Expected behavior:**
Both `T`s should evaluate to `false`

**Actual behavior:**
The `.ts` file evaluates to `false`, whereas the `.d.ts` file evaluates to `true`.
![image](https://user-images.githubusercontent.com/9854865/95368204-c99af800-08a3-11eb-99fc-3127d227cdcf.png)
![image](https://user-images.githubusercontent.com/9854865/95368221-cf90d900-08a3-11eb-9c5e-265ec38c9a9e.png)

**Playground Link:** N/A - unsure how to create one specifically for .d.ts files

**Related Issues:** N/A

**Explanation**
I encountered this bug upon trying to debug why a `computed-types` library seemed to generate a type with all optional values. After having dived deep into it, it seems to have used `undefined extends T` behavior, which produces different results in a `.d.ts` file. [The issue for context is over here.](https://github.com/neuledge/computed-types/issues/69)

After having talked to Retsam19 on the TypeScript Community Discord, I've narrowed this specific bug down to typescript interpreting the `.d.ts` file differently based on the presence of a `tsconfig.json` with strict null checks or not. I'm unsure of whether this is a bug now, given that the presence of tsconfig.json determines how to interpret the types. This behavior is _still_ extremely visible when you have a `x.d.ts` file and `x.ts` file with the same line `export type T = undefined extends 1 ? true : false` (they will evaluate to different things on hover), so I'm leaving this up for someone else to close if this is all expected behavior.
[what.zip](https://github.com/microsoft/TypeScript/files/5342892/what.zip)

**Comment by andrewbranch** [comment]
The “problem” is that your editor is _not_ processing the .d.ts file under `--strict` mode, because it’s not part of your project. (When you open a random *.js/*.ts/*.d.ts file not governed by any project config, it just gets default compiler options, which are non-strict.) It’s not part of the project because it appears to be an _output_ from `why.ts`. If you delete `why.ts` or rename either file, the declaration file no longer appears to be an output, so it can be considered an input, and is processed under strict mode, so you see `false`.

(Why does `undefined` extend `1` without strict null checks, you ask? The way strict null checks work is by stripping null/undefined out of the domain of types wherever we see them, so for example, `string | undefined` becomes `string`. What do you get when you remove `undefined` from `undefined`? The empty union, also known as `never`. `never` is assignable to everything, including `1`, so you get `true` out of that conditional. This is the same reason why, _with_ strict null checks, the type of `undefined!` is `never`—the `!` postfix explicitly removes `null`/`undefined` from its argument, whereas this is done automatically all over the place in non-strict mode.)
