### ISSUE TITLE
typeof class to include the class / instance duality of the type

### ISSUE THREAD

**Issue by xaviergonz** [microsoft/TypeScript#40993]
## Search Terms

generic class, infer, inference

## Suggestion

```ts
class P<T> {
}

const P2 = P // infered to be typeof P

// this works ok
const a = new P2<number>() // typeof a1 is P<number> (would be better if it was P2<number> though)
const b = new P<number>() // typeof b1 is P<number>
const c: P<number> = new P<number>() // typeof b2 is P<number>

// but this one fails
// 'P2' refers to a value, but is being used as a type here. Did you mean 'typeof P2'?ts(2749)
const d: P2<number> = new P2<number>()

// this one does not compile, but because of
// 'P2' refers to a value, but is being used as a type here. Did you mean 'typeof P2'?ts(2749)
// it would be better if it gave the error that there's a generic missing (like it would if we just used const b: P = new P<number>
const e: P2 = new P2<number>() // a3 is any
```

Could we make the type P2 also accept the generics acceptable for the original type? This is, to accept the duality class type/instance type of classes when using typeof a class.

This is, making
```
const P2 = P // or f(P)
```
equivalent to 
```
const P2 = P // or f(P)
type P2<T> = P<T>
```
for the cases where P type is inferred

## Use Cases

It would be really useful for functions that transform classes into other classes with the same members, this is, that do the same work as currently do class experimental decorators.

For example:
```ts

function transformClass<T>(clazz: T): T {
    // here we would like to do extra stuff after the original constructor
    // so we need to override it
    class X extends (clazz as any) {
        constructor() {
            super(...arguments)
            // do extra stuff
        }
    }    
    return X as any
}

class P<T> {
    x!: T
}
const P2 = transformClass(P)
// if we were to add type P2<T> = P<T> here then everything below would work (as long as the class is not passed directly as a parameter)

// good
const a = new P2<number>() 

// good, does not compile
// it would be better if it gave the error that there's a generic missing (like it would if we just used const b: P = new P<number>())
const b: P2 = new P2<number>() 

// bad, does not compile. it should accept the type duality
const c: P2<number> = new P<number>()

// meh - compiles, but then needs refer a different class for the type, which is confusing
const d: P<number> = new P2<number>()
```

## Examples

See above

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by andrewbranch** [comment]
I’m not confident this behavior would be broadly desirable—my hunch is that it would not—but we can ignore that question because it’s not compatible with the fundamental architecture of the compiler. Declarations are bound on a file-by-file basis, prior to type checking, and the symbols created by the binder contain the “meaning” of that declaration (e.g. type, value, namespace, alias, some valid combination of those). Consequently, we can and must know, from syntax alone, what meanings a declaration has. One of the things we do with that information right away is issue duplicate declaration errors. Consider this example:

```ts
import { someFactory } from "./mod";

type MaybeAClassWhoKnows = unknown;
const MaybeAClassWhoKnows = someFactory();
```

The binder knows this is valid because a type alias declaration can _only_ contain a type meaning, and a variable declaration can _only_ contain a value meaning, so these meanings are allowed to merge. We can know that without having any clue what `someFactory` returns, which is important, because we _don’t_ yet know anything about `someFactory`. We need to build the symbol tables for every file in the binder so that the checker can bring them all together and check the program holistically. But in your suggestion, we would need the type checker to resolve the import of `someFactory` and tell us what type it returns as part of building the symbol table for this file—so there is a circular dependency here.
