### ISSUE TITLE
Generic function unable to compare value of specific type to properties on object matching that type

### ISSUE THREAD

**Issue by tshelburne** [microsoft/TypeScript#41028]
**TypeScript Version:**  v4.1.0-insiders.20201010 

**Search Terms:** "have no overlap" "generic function key value type"

**Code**

```ts
type Foo = {
    prop1: string
    prop2: number
    prop3: number
    prop4: boolean
    prop5: string
}

type KeysOfType<T extends object, V> = {
    [K in keyof T]: T[K] extends V ? K : never
}[keyof T]

type FooStrings = KeysOfType<Foo, string>

function eqExplicit(o: Foo, k: FooStrings, v: string): boolean {
    return o[k] === v
}

function eqGeneric<T extends object>(o: T, k: KeysOfType<T, string>, v: string): boolean {
    return o[k] === v
}
```

**Expected behavior:**

I expect the code to build successfully, and that `eqExplicit` would have the same behavior and typecheck as `eqGeneric<Foo>`.

**Actual behavior:**

`o[k] === v` in the `eqGeneric` function is marked with an error:

> This condition will always return 'false' since the types 'T[KeysOfType<T, string>]' and 'string' have no overlap.(2367)

**Playground Link:** 

https://www.typescriptlang.org/play?ts=4.1.0-insiders.20201010#code/C4TwDgpgBAYg9nKBeKBvAUFLUwCc5gCMAXFAM7C4CWAdgOabZ4EBMpNArgLYBGEujLMzABmdtz4DsOfGAAspHggA2EAIY1BMggFZSFavXQBfdOlCQoAaQggyAeQBmAFXAQAPM6gQAHsAg0ACZkUHA8AFYQAMbAADRQAGoAfMhoWgDaVlC0UADWtnCOUM4AuqTOmSXefgHBiVAA-NZQ7BAAbvwm6fkghcUlZhbQ8HAAypS0dCEoNnZOrpDuI-EGk0lmjhw0MVRwNN4AjgCiPmDKVFFUwAAUcKTLefcI44ZT8W36E-QAlIoq6vsMNJcBBgBxcPs4N0qkhYVA2iYNlsdntDgBxAL8C6ear+IIhMKRGJJW7leK5UizBwuNyeFZfOhJd6fV6-KBKOCqDRpYGg8GQ6HIOEI4xAA

**Related Issues:** 

https://github.com/microsoft/TypeScript/issues/40832

**Comment by tshelburne** [comment]
As a followup, I tried using what was suggested in the comments of #40832 and got the following:

```ts
// suggestion from #40832

function eqGenericKey<T extends object, K extends KeysOfType<T, string>>(o: Record<K, string>, k: K, v: string): boolean {
	return o[k] === v
}

// actual use case

type KFilter<K> = {
	v: string
	k: K
}

type TFilter<T extends object> = {
	v: string
	k: KeysOfType<T, string>
}

function eqGenericKFilter<T extends object, K extends KeysOfType<T, string>>(o: Record<K, string>, filter: KFilter<K>): boolean {
	return o[filter.k] === filter.v
}

function eqGenericTFilter<T extends object, K extends KeysOfType<T, string>>(o: Record<K, string>, filter: TFilter<T>): boolean {
	// Error: Type 'KeysOfType<T, string>' cannot be used to index type 'Record<K, string>'.
	return o[filter.k] === filter.v
}
```

I would expect `eqGenericTFilter` to work the same way as `eqGenericKFilter`, but the former errors while the latter does not.

**Comment by RyanCavanaugh** [comment]
@weswigham OP is WAI (can you explain) but there *might* be something going on in the second example? I'm not sure what the rules are here

**Comment by weswigham** [comment]
Second example is just incorrect. You define a type which has a subset of `KeysofType<T, string>`'s keys with `K extends KeysOfType<T, string>` and then index with just `KeysOfType<T, string>`. This could easily produce invalid instantiations, for example, `eqGenericTFilter<{x: string, y: string, z: number}, "x">({x: "ok}, {v: "oh no", k: "y"})` would typecheck based on the signature, but the implementation would throw at runtime (since the input record does not contain a `"y"` key).

**Comment by weswigham** [comment]
As far as the explaination for the OP goes: It's a limitation of our assignability analysis. A generic indexed access on `T`, `T[KeysOfType<T, string>]` is neither assignable to nor from `string`, making it fail the comparability check. That's the case because our constraint analysis of that is essentially `object[string | symbol | number]`, which, ofc, doesn't produce a result (since `object` has no index signatures), so no comparison is performed. (Now, there's an argument to be made that in the case of comparability, maybe that means we should err on the side of _allowing_ the comparison, but I'm just explaining how it currently works)

**Comment by tshelburne** [comment]
@weswigham My understanding was that `K extends KeysOfType<T, string>` would mean that `K` must, at a minimum, contain the string keys of `T`, meaning `"x" | "y" | [whatever else]`. And then `TFilter<T>` is defined such that the `k` values can *only* be those keys, so runtime errors couldn't occur. What am I missing?

**Comment by weswigham** [comment]
You're understanding is reversed. `K extends KeysOfType<T, string>` means `K` must be a _subtype_ of `KeysOfType<T, string>`, so if `KeysOfType<T, string>` is `"x" | "y"`, then `"x"` is a valid subtype, `"y"` is a valid subtype, and `"x" | "y"` itself is a valid subtype, however `"x" | "y" | "z"` is _not_ a valid subtype because `"z"` isn't a member of `"x" | "y"`.

**Comment by tshelburne** [comment]
Well, that will do it. Sorry to keep bothering, but then why does it work in the `eqGenericKFilter` example?

**Comment by weswigham** [comment]
Because then your filter is `K`, which is the same type you're indexing with, rather than a supertype of `K`.

**Comment by tshelburne** [comment]
Thanks for your help!
