### ISSUE TITLE
Can type object|undefined be assigned to parameter of type Record<string, any>?

### ISSUE THREAD

**Issue by RevealedFrom** [microsoft/TypeScript#41056]
**TypeScript Version:**  4.0.2

**Search Terms:** assign union types

```
class C {
  private o1:object|undefined = { };
  
  constructor() {
    this.f(this.o1);  // #1

    let o2:object|undefined = { };
    this.f(o2); // #2

    o2 = this.o1; 
  };

  f(o: Record<string,any>) { }

}
```

**Expected behavior:** Both invocations of `this.f` should either be allowed or not allowed as both `o1` and `o2` has the same type.

**Actual behavior:** Every line of code above can compile except the first invocation of `this.f`. The error is `Argument of type 'object | undefined' is not assignable to parameter of type 'Record<string, any>'.` The second invocation of `this.f` can compile.

**Related Issues:**

**Comment by MartinJohns** [comment]
The compiler can see that `o2` will **always** have the type `object` when invocing `this.f()`, that's why you don't see an error. Your explicit type annotation is ignored in this case, and this is by design.

Bring in some dynamic behavior that matches your type and you'll see the expected behavior:

   let o2:object|undefined = Math.random() > 0.5 ? undefined : { };

**Comment by RyanCavanaugh** [comment]
TS is indeed smarter than you give it credit for 😉
