### ISSUE TITLE
Type refinement inside instanceof guard fails

### ISSUE THREAD

**Issue by alexeagle** [Microsoft/TypeScript#4107]
bug.ts:
```ts
type Type = new (...args: any[]) => any;
interface ComponentDefinition {
}

interface RouteDefinition {
  component?: Type | ComponentDefinition;
  loader?: Function; 
}
 
class Route implements RouteDefinition {
  component: Type;
}
class SyncRouteHandler  {
  constructor(public componentType: Type) {  }
}

function test(foo: RouteDefinition): boolean {
 if (foo instanceof Route) {
   new SyncRouteHandler(foo.component); // should know that Route.component is a Type, not a Type | ComponentDefinition
 }
 return false;
}
```

```
$ tsc --version
message TS6029: Version 1.5.3
$ tsc bug.ts
bug.ts(19,25): error TS2345: Argument of type 'ComponentDefinition | (new (...args: any[]) => any)' is not assignable to parameter of type 'new (...args: any[]) => any'.
  Type 'ComponentDefinition' is not assignable to type 'new (...args: any[]) => any'.
```

Interestingly, removing the `loader` property from the `RouteDefinition` interface fixes it, as does adding a `loader` property to the `Route` class.

+cc @btford

**Comment by RyanCavanaugh** [comment]
This is behaving according to spec (emphasis mine)

> *	A type guard of the form x instanceof C, where x is not of type Any, C is of a subtype of the global type 'Function', and C has a property named 'prototype'
  *  when true, narrows the type of x to the type of the 'prototype' property in C provided it is a **subtype of the type of x**, or, if the type of x is a union type, removes from the type of x all constituent types that aren't subtypes of the type of the 'prototype' property in C, or
   *	when false, has no effect on the type of x.

The problem is that `Route` is assignable to, but is not a subtype of, `RouteDefinition` (as the spec says, "*[one of the differences between subtype and assignability is that] an object type without a particular property is assignable to an object type in which that property is optional.*")

Confirmed that changing the relation used in the type guard code from `isSubtypeOf` to `isAssignableTo` (in `getNarrowedType` line ~6211) makes this work as one would expect. I don't immediately know what the other implications of that change would be.

@ahejlsberg weigh in on what's desirable here?

**Comment by JsonFreeman** [comment]
As far as I know, the guiding principle on which relation to use has been the following. If the relation is being used in order to choose the "best" type from some set of types, we use subtype. If the relation is used to determine if something is allowed, we use assignability.

This is a rule of thumb, and indeed the type guard case seems like it is somewhere in between. On the one hand, we are choosing between two candidate types when deciding whether to narrow. That suggests subtype. On the other hand, these types are not born equal. One is the prior type that was already known, and one is a test type, so it seems like we could use assignability.

It seems like it might be reasonable to use assignability here. However, later in the bullet point that @RyanCavanaugh mentioned, it says

>if the type of x is a union type, removes from the type of x all constituent types that aren't **subtypes** of the type of the 'prototype' property in C

Would that also be changed to assignability?

**Comment by alexeagle** [comment]
I would add that I haven't read the spec, and hadn't thought of the subtlety of assignability vs. subtype (and would think the `implements` keyword always declares a subtype relation).
To me, the least-surprising thing would be to narrow in this case, if you don't find a case where changing to assignability breaks something.

(oh and for comic relief: I can't solve this by explicitly casting, because we transpile Angular to Dart, and their analyzer fails on 'unneeded cast')

**Comment by JsonFreeman** [comment]
It's probably fine to use assignability. Also, the `implements` keyword does not declare a subtype relation. It requires an assignability relation.

**Comment by RyanCavanaugh** [comment]
This turned out to be slightly more complicated that just changing the relation. It's best to look at the testcase I added to the PR to see the different variants of things that need to work correctly.

**Comment by RyanCavanaugh** [comment]
Changed in `master` now. Thanks for the report!

**Comment by btford** [comment]
Thank _you_!
