### ISSUE TITLE
Type narrowing fails when using comma operator for function parameter

### ISSUE THREAD

**Issue by dummdidumm** [microsoft/TypeScript#41183]
**TypeScript Version:**  4.0.2
**Search Terms:** comma operator flow narrow type function

I encountered a case where type narrowing fails when using the comma operator and passing the result to a function which does type narrowing.

**Code**

```ts
const otherValue = () => true;
const value : number | string = null as any;

function isNumber(obj: any): obj is number {
    return true; // method implementation irrelevant
}

// Good case - works
if (typeof (otherValue(), value) === 'number') {
    const b = value; // number
}

// Bad case - fails
if (isNumber((otherValue(), value))) {
    const b = value; // string | number , but should be number
}
```

**Expected behavior:**
I would expect the second case to also narrow down the type to `number`

**Actual behavior:**
Type is `string | number`, it was not narrowed.

**Playground Link:** 
https://www.typescriptlang.org/play?#code/MYewdgzgLgBCUAsCmAnAagQwDYFckwF4YAKASkID4YoU8BuAKFElgDds8YAuGMHAWwBGqGAB8Y0FAEswAc0K8cWLDAwRVYAJ6MGAMxxhgUKeBhSIAOQHCUxEIIBWPDFtI97Ds+r5CRAbwYYIJgUJCgcFDBqWiQ6GAB6eJh+MIQQABMzfgAHLCQUsCgMY1MpFFC89kKGAF8GBildEihNbKQQJrtEVExcJDIAGhh2PvICcZgAch8bSfIA4JhmaBhBBRH6BKSZ1Fr6xpJzK19bLuR0Dn7SIY2kUnuYBeDl2DWiW7jEiRoZeXEdlC1IA

**Related Issues:** 
Sounds a little related: https://github.com/microsoft/TypeScript/issues/35484

**Comment by GrzegorzKazana** [comment]
This is an interesting issue - I wonder if narrowing down the comma expression in any case is actually the correct behavior.
Doing so is not safe, since we may trigger a side effect from inside of it.
(Obviously the question is why anyone would do such thing, but still)

For example:
```ts
const isNumber = (x: unknown): x is number => typeof x === 'number'
let thing = 42 as number | string;

const doSth = () => {
    thing = '100% evil stuff'
}

if (typeof (doSth(), thing) === 'number') {
    thing; // number
}
```
In this case narrowing to `number` is a mistake - since `doSth` changed `thing` to string.

So I think there are two topics:
- one explained by @dummdidumm, which is inconsistency when using `typeof` guard and custom type-guard - why does only one of them actually narrows down the type
- should comma expressions be even narrowed down?

**Comment by MartinJohns** [comment]
> In this case narrowing to number is a mistake - since doSth changed thing to string.

It's not a mistake. The comma operator evaluates each of its operands from left to right. Sure, it changes the value to a string inside the function, but that just results in the comparison to be `false`.

**Comment by GrzegorzKazana** [comment]
Ahh, my bad. Thanks for correcting me @markusjohnsson 😅
