### ISSUE TITLE
Request: classes as types

### ISSUE THREAD

**Issue by CrimsonCodes0** [microsoft/TypeScript#41187]
## Search Terms

classes, class, class as type, typeof class, class type alias

## Suggestion

I recommend allowing the general structure of a declared class to be used as a type alias.

## Use Cases

Now, I may be totally incorrect, but currently, code that deals with runtime-created classes can not describe the types that they are working with, without type deduction.
Ex:
```ts
function not_a_class<N extends number> (parameter: N) { // how do we describe this type, without the type?
    return class Class {
        x: N = parameter;
    };
};
```

## Examples

```ts
type Klass<N extends number> = class Class {
    x: N = parameter;
};

function not_a_class<N extends number> (parameter: N): Klass<N> { // Now we have a type annotation :)
    return class Class {
        x: N = parameter;
    };
};
```

## Checklist

My suggestion meets these guidelines:

* [ * ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ * ] This wouldn't change the runtime behavior of existing JavaScript code
* [ * ] This could be implemented without emitting different JS based on the types of the expressions
* [ * ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ * ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by DanielRosenwasser** [comment]
What's the point exactly? Just so you can copy/paste the same code in the type alias position?

**Comment by 00ff0000red** [comment]
> What's the point exactly? Just so you can copy/paste the same code in the type alias position?

Ok, so you want a legitimate use case...

Some classes aren't just globally defined, meaning you can't simply do `declare class foo { ... }`.

For example, instead of writing that code... what if I told you to declare it?

```ts
declare function not_a_class<N extends number> (parameter: N): ???;
```

You might be able to but to perfectly "type" it, it would be very complicated.

I tried to give a type to the WebIDL TypedArray abstract class.

```ts
const TypedArray: ??? = Reflect.getPrototypeOf(Int8Array);

class Int128Array extends TypedArray { ... }
```

Currently, it can't be given a proper type annotation.

The same exists for several other "hidden" classes, ex: `AsyncFunction`, `GeneratorFunction`, and `AsyncGeneratorFunction`, to name a few.

Is there a preferred way to type classes? `new (...args) => T` wouldn't fit well here.

I'm starting to think that I might be able to pull it off with interfaces, would that be a good approach?

**Comment by RyanCavanaugh** [comment]
This is already possible?
```ts
type Klass<N extends number> = {
  new(): {
    x: N;
  }
}

function not_a_class<N extends number> (parameter: N): Klass<N> {
    return class Class {
        x: N = parameter;
    };
};
```

**Comment by RyanCavanaugh** [comment]
Or inline
```ts
function not_a_class<N extends number> (parameter: N): new() => { x: N;  } {
    return class Class {
        x: N = parameter;
    };
};
```

**Comment by 00ff0000red** [comment]
> This is already possible?
> ....

Well, yes, it could be done like that, for simple cases at least.

But then we get into inheritance and it becomes more complicated, or TS abstract classes.

```ts
function f() {
    return class extends T { ... };
}
```

The type definitions all just get more verbose and complicated, yet the class shape itself is simple, so why not just allow the syntax to, if anything, simplify it?

Also, how could you do abstract classes?

```ts
function f() {
    abstract class T {};

    return T;
}
```
