### ISSUE TITLE
Picture-in-picture API types

### ISSUE THREAD

**Issue by SukantPal** [microsoft/TypeScript#41205]
https://w3c.github.io/picture-in-picture/#document-extensions

* pictureInPictureEnabled, pictureInPictureElement, exitPictureInPicture not supplied to `Document`
* 'enterpictureinpicture', 'exitpictureinpicture` events not supplied to HTMLElement.addEventListener

**Comment by MartinJohns** [comment]
Please respect the issue templates for [bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Bug_report.md) and [feature requests](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Feature_request.md). :-) This will make the work for the TypeScript team much easier and they can focus on improving the language, instead of deciphering GitHub issues.

I honestly don't understand why that step is so difficult. 😕 

---

Experimental features (it's an early draft) are usually not added to the standard type library. [browser-compat-data lists it as unsupported.](https://github.com/mdn/browser-compat-data/blob/e2e4af58e55b06a6824684cd476e7b74b427bfaa/http/headers/feature-policy.json#L1342-L1389) You should check out: https://github.com/microsoft/TypeScript-DOM-lib-generator#additions.

You can always add the types yourself for your own project using definition files.
