### ISSUE TITLE
Strange bug with ternary -> not respecting union with undefined

### ISSUE THREAD

**Issue by SrBrahma** [microsoft/TypeScript#41234]
**TypeScript Version:**  Nightly

**Search Terms:**

**Code**

```ts
const infoArray: {a: number, b: string}[] = [];

let mode: 'X' | 'Y' = 'X'

let i = 5;

const oppositeKnownTimestamp: number | undefined = (mode === 'X'
  ? infoArray[i + 1]?.a
  : infoArray[i - 1]?.a
)

const a = oppositeKnownTimestamp;
```

**Expected behavior:**
`a` should be number | undefined.
**Actual behavior:**
`a` is just number
**Playground Link:** https://www.typescriptlang.org/play?ts=4.1.0-beta#code/MYewdgzgLgBAlmAZiAggJzQQwJ4C4YDem+YArgLYBGApmgDQyX7RoIDmAvgNoC6MAvDF4BuAFCiANtVjkQAE2r4A5AA0lMAD4wlATXWDVS8VNhwBMAKxjRoSLBAAHByAhwo1ANJgQAdzAAVOHJqaExyBxIKGjRNGFIwBUQEajlzAApZBQF+AzVRGBgAfngkVAwcLjMAahgARh5CgDpMfJh8BGR0LGxKmABaOobm0QBKcVtoGExzR2dXdy9fAKCQqDCHYSA

**Related Issues:**

**Comment by MartinJohns** [comment]
If you remove the ternary operator the result is the exact same.

The example can be simplified to:

    const infoArray: number[] = [];
    const a: number | undefined = infoArray?.[5]
    a;

Your issue essentially boils down to the array access returning the type `{ a: number, b: string }`, and **not** `{ a: number, b: string } | undefined`. So even after applying the null-conditional operator your type still does not include an `undefined`, and as a result the type of `oppositeKnownTimestamp` is `number`, and **not** `number | undefined`. The type of `a` being the same as of `oppositeKnownTimestamp`.

Additionally TypeScript is smart enough to ignore your explicit type annotation of `number | undefined` for `a` (assuming my example code) and knows the type is `number`, which can be seen when hovering over the `a` variable. This behavior is intentional.

The issue of array access returning `T` instead of `T | undefined` can be dealt with using the `noUncheckedIndexedAccess` flag coming up with TypeScript 4.1 (see issue #13778)

**Comment by SrBrahma** [comment]
Thank you very much.

The issue you linked is really good. Constantly I have to define the array value as union with undefined.
