### ISSUE TITLE
declarations not re-generated for .js files when changes are made

### ISSUE THREAD

**Issue by jrobinson01** [microsoft/TypeScript#41245]
**TypeScript Version:**  4.0.3

**Search Terms:**
jsdoc
**Code**
a repo reproducing the issue is [here](https://github.com/jrobinson01/tsc-jsdoc-2)

**Expected behavior:**
When changes are made to the source .js files, tsc should regenerate their .d.ts files.

**Actual behavior:**
tsc ignores .js source files once .d.ts files have been generated.

**Comment by RyanCavanaugh** [comment]
@sheetalkamat this config file has `checkJs` and `allowJs`; `traceResolution` shows:
```
======== Resolving module './module-a.js' from 'D:/Throwaway/tsc-jsdoc-2/src/index.js'. ========
Explicitly specified module resolution kind: 'NodeJs'.
Loading module as file / folder, candidate module location 'D:/Throwaway/tsc-jsdoc-2/src/module-a.js', target file type 'TypeScript'.
File 'D:/Throwaway/tsc-jsdoc-2/src/module-a.js.ts' does not exist.
File 'D:/Throwaway/tsc-jsdoc-2/src/module-a.js.tsx' does not exist.
File 'D:/Throwaway/tsc-jsdoc-2/src/module-a.js.d.ts' does not exist.
File name 'D:/Throwaway/tsc-jsdoc-2/src/module-a.js' has a '.js' extension - stripping it.
File 'D:/Throwaway/tsc-jsdoc-2/src/module-a.ts' does not exist.
File 'D:/Throwaway/tsc-jsdoc-2/src/module-a.tsx' does not exist.
File 'D:/Throwaway/tsc-jsdoc-2/src/module-a.d.ts' exist - use it as a name resolution result.
======== Module name './module-a.js' was successfully resolved to 'D:/Throwaway/tsc-jsdoc-2/src/module-a.d.ts'. ========
```
To get the behavior desired here, we would want to check for `'D:/Throwaway/tsc-jsdoc-2/src/module-a.js'` before any `.d.ts`; I was sort of surprised this didn't happen under `allowJs`. Thoughts?

**Comment by sheetalkamat** [comment]
We have always preferred d.ts files over .js and i think this changed because we started writing d.ts files for .js as well. 
The interesting question is if this happens in `node_modules` folder, we probably still want to prefer d.ts over .js.. We can experiment fixing this but it would be breaking change in a way.

Also if `allowJs` is true, would we never want to look for module.d.ts ? I think the answer that to is yes. Presence of module.js shouldnt change whether we look for module.d.ts or not if it is referenced by module.d.ts

**Comment by sheetalkamat** [comment]
Our resolution does not depend on whether allowJs is on or not and as shown in traceResolution is deterministically designed to follow the extensions in that order so its just bad configuration.
