### ISSUE TITLE
JS autocomplete doesn't work for object literal shorthands 

### ISSUE THREAD

**Issue by jurajmatus** [microsoft/TypeScript#41259]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.1.0-dev.20201026

**Search Terms**
- suggest / suggestion
- intellisense
- object short hand

---

- VSCode Version: 1.51.0-insider (7a3bdf4ee9588755d447aa1c3b5db4a123fc11a9)
- OS Version: Arch Linux

Steps to Reproduce:

1. Suppose there are variables in the current context (be it local or global)
2. Create an object literal and try to use a variable in a shorthand style
3. No semantic autocompletion is offered, and textual autocomplete is only offered after 3 characters

GIF file to better demonstrate:
![vscode](https://user-images.githubusercontent.com/17612051/97086075-7524a600-1621-11eb-82cb-ec93d5dad396.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by orange4glace** [comment]
If you don't mind, I can work with this issue. FYI @andrewbranch

**Comment by andrewbranch** [comment]
Sounds good @orange4glace, let me know if you get stuck. You have about a month and a half before we need to get a fix in.

**Comment by orange4glace** [comment]
@andrewbranch Thanks for the reply! I have one question for this.
I'm planning to change the code like [this](https://github.com/orange4glace/TypeScript/commit/ea29b1580511d56935bfaddad2679f15226c48de) and with this code, 
every tests are passed except [`completionListAtIdentifierDefinitionLocations_destructuring`](https://github.com/microsoft/TypeScript/blob/master/tests/cases/fourslash/completionListAtIdentifierDefinitionLocations_destructuring.ts), which is,
```ts
/// <reference path='fourslash.ts' />

//// var [x/*variable1*/

//// var [x, y/*variable2*/

//// var [./*variable3*/

//// var [x, ...z/*variable4*/

//// var {x/*variable5*/

//// var {x, y/*variable6*/

//// function func1({ a/*parameter1*/

//// function func2({ a, b/*parameter2*/
                         ~
                         Getting Global Autocompletion

verify.completions({ marker: test.markers(), exact: undefined });
```

As l understood, the parenthesis `{` of the last line after the `func2(` is recognized as **ObjectLiteral** with `any` type rather than **ObjectBinding** since the line is getting following error,
```
'}' expected.ts(1005)
41259.ts(15, 16): The parser expected to find a '}' to match the '{' token here.
41259.ts(13, 16): The parser expected to find a '}' to match the '{' token here.
```

I'm curious that,
1. Is the test case valid one even though there's an syntax error? (Original PR for testcase : https://github.com/microsoft/TypeScript/pull/1767)
2. If so, Fixing the code to satisfy both original issue and the testcase seems pretty hard as I think.

I'm very new to this community and anything that can be helped would be much appreciated!

**Comment by andrewbranch** [comment]
We definitely want test cases that have syntax errors because they reflect half-written code as though a user is actively editing, and we want completions to work in those cases. That said, any particular assertion in a test like this might become wrong and need to be updated. What completion is showing up there?

**Comment by orange4glace** [comment]
*With my [modified version](https://github.com/orange4glace/TypeScript/commit/ea29b1580511d56935bfaddad2679f15226c48de)*, it autocompletes global symbols at,
```ts
....
var {x, y/*variable6*/
function func1({ a/*parameter1*/
function func2({ a, b/*parameter2*/
                    ~
                    Global symbols Autocompletion
```
whereas with *Typescript v4.0.5*, it autocompletes nothing.

Currently, the compiler parses the testcase code like this,
```ts
/* Statement #0 Starts (VariableStatement) */
var [x
/* Statement #1 Starts (VariableStatement) */
var [x, y
/* Statement #2 Starts (VariableStatement) */
var [.
/* Statement #3 Starts (VariableStatement) */
var [x, ...z
/* Statement #4 Starts (VariableStatement) */
var {x
var {x, y
function func1/* Statement #5 Starts (ExpressionStatement) */({ a
function func2({ a, b
```
The opening bracket `{` in the `func2({ a, b` is recognized as an *ObjectLiteralExpression* even though it looks like (or it should be) an *ObjectBindingPattern*, finally it autocompletes with global symbols.

**Comment by andrewbranch** [comment]
I think that’s probably alright. Can you go ahead and open a draft PR so we can make a playground build?

**Comment by orange4glace** [comment]
Sure! I've just opened it. :)
