### ISSUE TITLE
Type safety and implicit any from ambient declarations

### ISSUE THREAD

**Issue by use-strict** [Microsoft/TypeScript#4126]
I'm using the "noImplicitAny" compiler option to achieve some degree of type safety (still possible to explicitly opt out of type checking). This eliminates errors by omission from inside the app but it doesn't protect against explicit "any"-s coming from the outside world (*.d.ts files for external libraries). The problem is that we are "implicitly" inheriting "any" from 3rd-party code. This feels like it should still fall under "noImplicitAny", or at least have a stricter setting that would catch this case.

Example:
```typescript
// in angular.d.ts
$watch(watchExpression: string, listener?: (newValue: any, oldValue: any, scope: IScope) => any, objectEquality?: boolean): Function;

// in app.ts
$scope.$watch('someProp', (newVal) => { // <- I would expect an implicit any error here
});
```

One solution could be something like explicit "any" only working within the file boundary (might be similar to this concept in FB's flow: http://flowtype.org/docs/type-annotations.html#module-boundaries), together with a stricter compiler option.

I realize that strictly speaking this is not a TypeScript issue. Ideally, it should be fixed in each *d.ts library definition by switching to generics, but it is not always possible to do it and there are cases when it's intentionally left out, so it falls back to the compiler catching these cases if we explicitly ask it to. See https://github.com/borisyankov/DefinitelyTyped/issues/3641)

**Comment by RyanCavanaugh** [comment]
There's not much the compiler can do about it without being a giant pain, I think. Contextually-typed `any`s are still non-implicit. We don't track file boundaries in the type system.

The real fix is in the .d.ts files. Callbacks like this should at least be typed using` {}` in place of `any`. That's a non-breaking change for anyone who has explicit type parameters on their function parameters, and probably a useful warning who was consuming those values as `any`.

I believe TSLint is starting to add type-based rules. It'd be pretty straightforward to add a linter rule for "Don't let an `any` appear in function parameters due to contextually type".
