### ISSUE TITLE
tsfmt and JSX

### ISSUE THREAD

**Issue by myitcv** [Microsoft/TypeScript#4127]
I've been using [`tsfmt`](https://github.com/vvakame/typescript-formatter) to format TypeScript code. I believe this uses the pretty-printer from core compiler service. 

But I've hit upon the following issue when formatting:

```typescript
/// <reference path="typings/tsd.d.ts" />

import React = require("react");

function test(): any {
    return <span>This is a test</span>;
}
```

the output is:

```
/// <reference path="typings/tsd.d.ts" />

import React = require("react");

function test(): any {
    return <span>This is a test< /span>;
}

```

Notice the problematic `< /span>`.

The former compiles, the latter does not:

```
$ ./node_modules/.bin/tsc --jsx react --module system test.tsx
test.tsx(6,34): error TS1003: Identifier expected.
test.tsx(6,35): error TS1005: '>' expected.
test.tsx(9,1): error TS17002: Expected corresponding JSX closing tag for 'span'.
```

Any thoughts?

**Comment by myitcv** [comment]
Another related example:

```typescript
/// <reference path="typings/tsd.d.ts" />

import React = require("react");

function test(): any {
        let v: number = 5;
    return <span>{ v }</span>;
}
```

is formatted as:

```
/// <reference path="typings/tsd.d.ts" />

import React = require("react");

function test(): any {
    let v: number = 5;
    return <span>{ v } < /span>;
}
```

**Comment by RyanCavanaugh** [comment]
This is a tsfmt bug.

Here: https://github.com/vvakame/typescript-formatter/blob/master/lib/formatter.ts#L14

The source file the compiler gets is being created with the '.ts' extension, which means it's consumed using the regular TypeScript grammar. tsfmt needs to be able to support passing a '.tsx' file extension when appropriate so that expressions of the form `<T>x` are interpreted as JSX tags rather than type assertions.

**Comment by myitcv** [comment]
@RyanCavanaugh - thanks very much.

**Comment by vvakame** [comment]
ah, I understand. thank you!
