### ISSUE TITLE
Property 'sourceFileToPackageName' does not exist on type 'Program'.

### ISSUE THREAD

**Issue by ericmorand** [microsoft/TypeScript#41301]
The following TypeScript code throws the error `Property 'sourceFileToPackageName' does not exist on type 'Program'.`:

```ts
        const builderProgram: EmitAndSemanticDiagnosticsBuilderProgram = createIncrementalProgram({
            rootNames: [file],
            options: options,
            host: host
        });

        const program: Program = builderProgram.getProgram();

        const map = program.sourceFileToPackageName;
```

This is extremely disturbing because on your own source code, you retrieve the property `sourceFileToPackageName` from a Program instance with no issue:

https://github.com/microsoft/TypeScript/blob/85ef91e2233fa384e980005c109fadc04376ce3e/src/compiler/program.ts#L1416

**Comment by MartinJohns** [comment]
The `sourceFileToPackageName` property is marked as **internal**: https://github.com/microsoft/TypeScript/blob/85ef91e2233fa384e980005c109fadc04376ce3e/src/compiler/types.ts#L3791

You can get access by providing your own type information using declaration merging, but be aware that the property could be removed at any release without an announcement (because it's internal).

**Comment by RyanCavanaugh** [comment]
Implementation details are intentionally marked internal and are subject to change
