### ISSUE TITLE
error TS2304: Cannot find name 'MSStyleCSSProperties'.

### ISSUE THREAD

**Issue by lvignals** [Microsoft/TypeScript#4132]
TSC 1.5: I keep getting that error on all my existing code when transpiling:

error TS2304: Cannot find name 'MSStyleCSSProperties'.

What is the issue and how to resolve or is that a 1.5 bug?

**Comment by mhegazy** [comment]
This is caused by removing IE-specific types from lib.d.ts as part of 1.5 release. See [breaking change notification](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#dom-interface-changes) for more information.

if you can share more code, i might be able to help with how to change it.

**Comment by lvignals** [comment]
Thanks for the link.
Using https://github.com/Microsoft/TypeScript/blob/v1.5.0-alpha/bin/lib.d.ts did fixed the issue as explained in the article you sent me.
Code I was having the issue with can be cloned from https://github.com/awayjs
Thanks for the solution!
