### ISSUE TITLE
Fail to infer recursively defined `Json` type

### ISSUE THREAD

**Issue by xieyuheng** [microsoft/TypeScript#41337]
Example:

``` typescript
// "typescript": "^4.0.5"

type Json =
  | string
  | number
  | boolean
  | null
  | Array<Json>
  | { [key: string]: Json }

const json = [{ y: "" }, { x: "" }]

// NOTE Add type annotation would work:
// const json: Json = [{ y: "" }, { x: "" }]

const _: Json = json
```

Error report:

```
[8:30:16 PM] File change detected. Starting incremental compilation...

src/test.ts:16:7 - error TS2322: Type '({ y: string; x?: undefined; } | { x: string; y?: undefined; })[]' is not assignable to type 'Json'.
  Type '({ y: string; x?: undefined; } | { x: string; y?: undefined; })[]' is not assignable to type 'Json[]'.
    Type '{ y: string; x?: undefined; } | { x: string; y?: undefined; }' is not assignable to type 'Json'.
      Type '{ y: string; x?: undefined; }' is not assignable to type 'Json'.
        Type '{ y: string; x?: undefined; }' is not assignable to type '{ [key: string]: Json; }'.
          Property 'x' is incompatible with index signature.
            Type 'undefined' is not assignable to type 'Json'.

16 const _: Json = json
         ~

[8:30:17 PM] Found 1 error. Watching for file changes.
```

**Comment by MartinJohns** [comment]
This is a result of #19513. Check the inferred type of `json`, it contains optional properties. As a result it's not assignable to your `Json` type, because `undefined` (of the optional properties) is not a valid type anywhere.

You can just explicit type your initial variable already:

    const json: Json = [{ y: "" }, { x: "" }]

Alterantively, if you replace `Array<Json>` with `ReadonlyArray<Json>` you can use const contexts:

    const json = [{ y: "" }, { x: "" }] as const

Lastly you could create some elaborate conditional type that would remove all undefined properties (I wouldn't follow this path).

---

I'd categorize this under "Working as Intended".

**Comment by xieyuheng** [comment]
Thanks for your reply, and the link to the PR.

My concern is cleared now.
