### ISSUE TITLE
Module augmentation: TypeScript overrides declarations instead of merging them

### ISSUE THREAD

**Issue by mikeconley12** [microsoft/TypeScript#41351]
**TypeScript Version:**  4.1.0-dev.20201031

**Search Terms:** "declare module", "module augmentation"

**Code**

[codesandbox](https://codesandbox.io/s/typescript-playground-export-forked-dsdly?file=/index.ts)

**Expected behavior:** TypeScript should merge two separate declarations of the `ParsedPath` interface.

**Actual behavior:** TypeScript overrides the declaration of the `ParsedPath` interface. This behavior can be fixed by uncommenting the line `export type Foo = "";` in `types.ts` file.

**Playground Link:**  [codesandbox](https://codesandbox.io/s/typescript-playground-export-forked-dsdly?file=/index.ts)

**Related Issues:**

**Comment by MartinJohns** [comment]
I'm not too sure about the internal details, but you see this behavior because `types.ts` is not a module. You can only augment modules within modules or declaration files. Once you add an `import` or `export` statement it's a module. Alternatively you can make `types.ts` a decaration file by renaming it to `types.d.ts`.

**Comment by mikeconley12** [comment]
Thanks for the explanation!
