### ISSUE TITLE
Recursive conditional type infer unknown[] instead of string[]

### ISSUE THREAD

**Issue by Pomar81** [microsoft/TypeScript#41414]
**TypeScript Version:**  4.1.0-beta

**Search Terms:**

**Code**

```ts
type Join<T extends string[], D extends string> =
    T extends [] ? '' :
    T extends [string] ? `${T[0]}` :
    T extends [string, ...infer U] ? `${T[0]}${D}${Join<U, D>}` :
    string;
```

**Expected behavior:** string[] should be inferred

**Actual behavior:** unknown[] is inferred

**Playground Link:** https://www.typescriptlang.org/play?ts=4.1.0-beta#code/C4TwDgpgBAUg9gSwHYB4AqUIA9gSQEwGcpDgAnZAcygG0BdAGigBFMc8iTyqA+KAXgBQUEVAzZcBYvSgB+KAHIFUAFzDR49lNqkKSSnTlQABgBIA3mhoAGOgF9jq9SM2TONXVSYA6X8gBmEGRQAKqG8maWNvYWzHYW8MgoIUzMPA5Oolx6lADcQA

**Related Issues:**

**Comment by Nathan-Fenner** [comment]
While it would be nice if TypeScript support this case, be aware that there is a workaround (for this and all related problems): you can replace `U` with `U extends string[] ? U : never`, which effectively acts as a "truth me, or explode later if I'm wrong":

```ts
type Join<T extends string [], D extends string> =
    T extends [] ? '' :
    T extends [string] ? `${T[0]}` :
    T extends [string, ...infer U] ? `${T[0]}${D}${Join<U extends string[] ? U : never, D>}` :
    string;
```

The conditional will never fail (provided that there's no bug in the TypeScript compiler and your reasoning that it is definitely `string[]` is remains actually correct).

You can also consider something like `U extends string[] ? U : ["uh oh, something went wrong - check assumption on line 4"]` so that the literal type _might_ show up and allow you to debug later. That's a handy debugging technique, anyway.

**Comment by Pomar81** [comment]
As a workaround I used following expression 
`U & string[]`

**Comment by RyanCavanaugh** [comment]
I don't think there's a good path forward that could accomplish this. We'd have to have a *lot* of extra higher-order reasoning to determine that `...infer U` would always produce something assignable to `string[]`
