### ISSUE TITLE
Optional properties coming from conditional spread lose "| undefined"

### ISSUE THREAD

**Issue by danvk** [microsoft/TypeScript#41418]
**TypeScript Version:**  4.2.0-dev.20201105

**Search Terms:**

- spread optional

**Expected behavior:**

The `start` symbols should both have type `number | undefined`.

**Actual behavior:**

The one destructured from the conditional spread has somehow dropped the `undefined`.

**Related Issues:**

#39376

**Code**

I'd expect the two `start` variables in the following code to have the same type. But they don't, one is `number`, whereas the other is `number | undefined`:

```ts
declare let hasDates: boolean;

{
  const nameTitle = { name: 'Khufu', title: 'Pharaoh' };
  const pharaoh = {
    ...nameTitle,
    ...(hasDates && { start: -2589, end: -2566 }),
  };
  // type is const pharaoh: {
  //     start?: number;
  //     end?: number;
  //     name: string;
  //     title: string;
  // }, which is character-for-character identical to Reign, below.
  const { start } = pharaoh;
  // const start: number
}

interface Reign {
  start?: number;
  end?: number;
  name: string;
  title: string;
}
declare let reign: Reign;

{
  const { start } = reign;
  // const start: number | undefined
}

```

<details><summary><b>Output</b></summary>

```ts
"use strict";
{
    const nameTitle = { name: 'Khufu', title: 'Pharaoh' };
    const pharaoh = Object.assign(Object.assign({}, nameTitle), (hasDates && { start: -2589, end: -2566 }));
    // type is const pharaoh: {
    //     start?: number;
    //     end?: number;
    //     name: string;
    //     title: string;
    // }, which is character-for-character identical to Reign, below.
    const { start } = pharaoh;
    // const start: number
}
{
    const { start } = reign;
    // const start: number | undefined
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.2.0-dev.20201105#code/CYUwxgNghgTiAEEQBd4AsoGcAiVkkwC54AjAezKSgDsBuAKHoG9754wzrNVqoBbEABUAlsiTwAvPCbxeA4gHIA0mgCuAM1UKANPGSikigAoYYUMmgXwAvgzYcuqAA6nzaSdNZt4AOj9yhAxBtLzY-HwAKDBw8AngAMnjpeG5YZGIAWgAmAFYADgBOXRBqYEzcgDYKmwBKELZbLwB6Jr0ATycEYUx2Tm54F1g3YhY2Fu82VJhkAH5ialU+EhAYO3hxiZLgOdlF5dXm1omA4m4YYWoAczWN730xEFPkc6ub1utdAHc0YTB3bvYrjA+BgGXUZFBfyGwJW8GEoGo+jAUAgejI8AASiBhJdqLplhAyJ8fF4HP0ZFNUNYPIMzBY3r1HClkGl5nsVvRrIwLiD1FAwAgsTjqJ5JizpjsFksVmstpL2Qc2CdmS9rl57oYVRc1VzQJBYAgkKg4MLiELcQxmKS+qgKeKqR4TRbDoz+pS2dKYPAAD7wVSlEDqC4gYCc+hAA)

**Comment by RyanCavanaugh** [comment]
@andrewbranch I think we should consider for 4.1 at least; this seems bad

**Comment by andrewbranch** [comment]
This is very interesting. It’s actually been a bug at least since 3.8, with https://github.com/microsoft/TypeScript/pull/34853, but the new behavior of conditional spreads creating optional properties increases your chances of observing it. Here’s an example of [the bug in 3.8.3](https://www.typescriptlang.org/play?ts=3.8.3#code/CYUwxgNghgTiAEA3W8D2AjAVgLngbwF94AffeKXAZwBcYBLAOwHN4CBuAKGRjSwCZ4AXjIA6MRkys28APQyyUAPxVajFgQ5hUDGuSG9MfEVGlz4Nes3iBeDcCMexyA).

Basically, as far as I can tell, we’ve never had the necessary machinery to mix optionality into the type retrieved from a _synthetic_ optional property. The place where we union with `undefined` for optional parameter declarations and property signatures actually looks at the declaration node for the `?` token—we never even look at `SymbolFlags.Optional` for this purpose.

Despite having diagnosed the problem, I’m having trouble fixing this in a way that doesn’t broadly change the type printout of these synthetic optional property symbols from `x?: number` to `x?: number | undefined`. The couple different places where you could add the optionality also come into play in the node builder. I’m assuming the reason this isn’t a problem for properties that can be traced back to an optional property signature is because we simply use that property signature node as part of the printout. I’m not sure the best way to proceed—I _think_ it would be ok to just tweak the node builder such that if a property is both optional and synthetic, and its type is a union, we can filter `undefinedType` from the union. But maybe there’s a more subtle option I’m missing. /cc @weswigham

**Comment by weswigham** [comment]
Hm, that doesn't seem so bad, at least. Certainly better than a synthetic optional property declaration or the like. The other option would be adding a `SymbolLink` flag that represents "should this property have `undefined` mixed in" (the thing we directly look up from the declaration). Essentially adding a cache for the declaration lookup, then directly setting that cache in synthetic property situations like this.

**Comment by ahejlsberg** [comment]
Why is it a problem that the printout changes to `x?: number | undefined`. We do that in other places anyway. For example:

```ts
type Foo = (x?: number) => void;  // Prints back as (x?: number | undefined) => void
```

Or am I misunderstanding something?

**Comment by andrewbranch** [comment]
It’s not a huge problem, it just changes a bunch of seemingly unrelated baselines, and is more verbose while conveying no more information, so it seems undesirable all other things held equal.

**Comment by ahejlsberg** [comment]
> is more verbose while conveying no more information, so it seems undesirable all other things held equal.

I tend to agree, but that is nonetheless what we currently do for print back of optional properties. If we're going to change it, we should change it across the board, not just in this targeted scenario.

**Comment by andrewbranch** [comment]
Huh, I must have been confused by existing baselines that _already_ exhibit this bug, because I was confident this didn’t happen for property signature printback, but apparently I’m wrong. In that case, I think this is a small change, and we can look at making printback more concise separately.

**Comment by ahejlsberg** [comment]
Actually, I think the current scheme does convey important information. The type of an optional property really is `xxx | undefined` since that's what you get when you read the property and that's what you're allowed to assign to the property. It's just that instead of complaining that `x?: number` is an invalid declaration, as a convenience we automatically union in `undefined`.

**Comment by andrewbranch** [comment]
Hmm, actually this causes another break. Consider [this case](https://www.typescriptlang.org/play?ts=4.2.0-dev.20201109#code/CYUwxgNghgTiAEEQBd4DMYHsC2BBAdvpslMgJab4Bc8A3vAB4D8N+ArtgEYgzwC+AbgBQoSLARJUMGvQDaAaxABPGgGdkMMvgDmAXVYduvQUN4BeOvAB0NjDgJES5Sv2FDJ6LNgCiDAA5wqqoU+PAW9DZWAIRRGmwITJYMNADM-PAyfK6mYZaRdj7+gcEuJkA):

```ts
declare let r: { [key: string]: number };

declare let fromAnnotation: { x?: number };
r = { ...fromAnnotation }; // Error: Type 'undefined' is not assignable to type 'number'.

let fromExpression = { ...!!true ? { x: 3 } : {} };
r = { ...fromExpression }; // Ok
```

The latter works today, and is asserted in a test, only because when we get the type of the `x` property in `fromExpression`, we incorrectly do not include `undefined`. If we fix that type, both assignments error, which is... a win for consistency, and I don’t know how bad the bad consequences are—but it is a breaking change.

**Comment by danvk** [comment]
@andrewbranch much of the discussion in the Design Meeting was about index types. I don't entirely see the connection. Is an index signature somehow involved behind the scenes here?

I noticed that [the example in the release notes](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1-rc/#conditional-spreads-create-optional-properties) for TS 4.1 RC is also broken because of this issue:

```ts
interface Person {
    name: string;
    age: number;
    location: string;
}

interface Animal {
    name: string;
    owner: Person;
}

function copyOwner(pet?: Animal) {
    return {
        ...(pet && pet.owner),
        otherStuff: 123
    }
}

const owner = copyOwner();

const loc = owner.location;  // type is string, should be string | undefined
console.log(loc.blink());
// 💥 Cannot read property 'blink' of undefined
```

[playground](https://www.typescriptlang.org/play?ts=4.2.0-dev.20201112#code/JYOwLgpgTgZghgYwgAgArQM4HsTIN4CwAUMqciHALYQBcyGYUoA5gNzFnJzO3kCulAEbR2JMgBssCOGGA46DJiDbEAvsWKhIsRCgCCIYJTjj8HMhWoLGLUZywB3ENDroo2EKPVFiMPiARZHGQELAAHAE8AeSdoAAowiDAAfjoDIxMASjMxUigkvihcQlzOZAA6SoSk5AAyWuREsHLHZyhMgBpzMuQsMAALaABlMD4YGDoARgAmAGZu5G9vYlCQBl7YqGQAXhDw6M24zNEVnHXJBB2NtvKLmTlPU7WscQhbrGY4i-LBcVAAayOx2IAHoQcgAMJwEAgPrIfJwAAmjSg4WgYAiyAA5L8AVjejBkP5ERAYKAIIjiEA)

**Comment by andrewbranch** [comment]
@danvk a lot of the conversation focused on index signatures because fixing this bug breaks an existing test where an object with optional properties is asserted to be assignable to an index signature. There is no disagreement that the type of the property is a bug, but we can’t fix it this late in the release cycle because the bug has been around at least since 3.8, and fixing it is a breaking change. So, much of the discussion focused on the question of when we do fix the property type, should we consider additional changes to make the assignability of optional properties to index signatures less breaky.
