### ISSUE TITLE
4.1.1-rc strange Type is not assignable to type never with yield & generators

### ISSUE THREAD

**Issue by eamodio** [microsoft/TypeScript#41428]
**TypeScript Version:**  4.1.0-beta (4.1.1-rc too)

//cc @mjbvz 

**Expected behavior:**
No error on the following line
```ts
const selection = yield step;
```

As it works fine in TypeScript 4.0.5, and I'm unsure where the `never` is even coming from. Here is the actual source if it is interesting: https://github.com/eamodio/vscode-gitlens/blob/787bc8f3a976135d51032547e209b93267e14b2f/src%2Fcommands%2FquickCommand.steps.ts#L1794-L1814

**Actual behavior:**
Error on the line
```
Type 'QuickPickStep<QuickPickItem>' is not assignable to type 'never'.(2322)
```

**Related Issues:**

**Code**
```ts
export enum Directive {
	Back,
	Cancel,
	LoadMore,
	Noop,
}

export namespace Directive {
	export function is<T>(value: Directive | T): value is Directive {
		return typeof value === 'number' && Directive[value] != null;
	}
}

export interface QuickPickItem {
	label: string;
	description?: string;
	detail?: string;
	picked?: boolean;
	alwaysShow?: boolean;
}


export interface QuickInputStep {

	placeholder?: string;
	prompt?: string;
	title?: string;
}

export interface QuickPickStep<T extends QuickPickItem = QuickPickItem> {
	placeholder?: string;
	title?: string;
}

export type StepGenerator =
	| Generator<QuickPickStep | QuickInputStep, StepResult<void | undefined>, any | undefined>
	| AsyncGenerator<QuickPickStep | QuickInputStep, StepResult<void | undefined>, any | undefined>;

export type StepItemType<T> = T extends QuickPickStep<infer U> ? U[] : T extends QuickInputStep ? string : never;
export namespace StepResult {
	export const Break = Symbol('BreakStep');
}
export type StepResult<T> = typeof StepResult.Break | T;
export type StepResultGenerator<T> =
	| Generator<QuickPickStep | QuickInputStep, StepResult<T>, any | undefined>
	| AsyncGenerator<QuickPickStep | QuickInputStep, StepResult<T>, any | undefined>;
export type StepSelection<T> = T extends QuickPickStep<infer U>
	? U[] | Directive
	: T extends QuickInputStep
	? string | Directive
	: never;
export type PartialStepState<T = unknown> = Partial<T> & { counter: number; confirm?: boolean; startingStep?: number };
export type StepState<T = Record<string, unknown>> = T & { counter: number; confirm?: boolean; startingStep?: number };

export function canPickStepContinue<T extends QuickPickStep>(
	_step: T,
	_state: PartialStepState,
	_selection: StepItemType<T> | Directive,
): _selection is StepItemType<T> {
	return false;
}

export function createPickStep<T extends QuickPickItem>(step: QuickPickStep<T>): QuickPickStep<T> {
	return step;
}

export function* showStep<
	State extends PartialStepState & { repo: any },
	Context extends { repos: any[]; title: string; status: any }
>(state: State, _context: Context): StepResultGenerator<QuickPickItem> {
	const step: QuickPickStep<QuickPickItem> = createPickStep<QuickPickItem>({
		title: '',
		placeholder: ''
	});
	const selection: StepSelection<typeof step> = yield step;
	return canPickStepContinue(step, state, selection) ? selection[0] : StepResult.Break;
}
```

<details><summary><b>Output</b></summary>

```ts
export var Directive;
(function (Directive) {
    Directive[Directive["Back"] = 0] = "Back";
    Directive[Directive["Cancel"] = 1] = "Cancel";
    Directive[Directive["LoadMore"] = 2] = "LoadMore";
    Directive[Directive["Noop"] = 3] = "Noop";
})(Directive || (Directive = {}));
(function (Directive) {
    function is(value) {
        return typeof value === 'number' && Directive[value] != null;
    }
    Directive.is = is;
})(Directive || (Directive = {}));
export var StepResult;
(function (StepResult) {
    StepResult.Break = Symbol('BreakStep');
})(StepResult || (StepResult = {}));
export function canPickStepContinue(_step, _state, _selection) {
    return false;
}
export function createPickStep(step) {
    return step;
}
export function* showStep(state, _context) {
    const step = createPickStep({
        title: '',
        placeholder: ''
    });
    const selection = yield step;
    return canPickStepContinue(step, state, selection) ? selection[0] : StepResult.Break;
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2019",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?target=6&jsx=0&ts=4.1.0-beta#code/KYDwDg9gTgLgBMAdgVwLZwCIEsrAMYxYBuwcA3gFACQAQgIZ4DWANNQMJ2J7AA2rVAGQh0AJgFlowfgDkIEMKwC+FCqEiw4iOqmABnMA1LZcBYqUpU10eADNkXQhERwsugDwAVAHwAKInR5kYAAuTBx8QhI4AB84DwBKUP9A0lcwk0jzaipcGGQoZxgATzBgCBs4ZKC4AF46uAByFFQAI2AoBrgAMi70iLMAbSrgAF04AEIazWQeHgBuamVlVXBrF0QYdptDOABFZCwmAAVDxgBJTfQLHjo2nlDdGCgsRABzBaoRPTxnsEdEAD8DyeL3e1C+MDoWB4QLgj2ebw+YFOwBEsJach4wE4HwCAHc6EVdABlAAWEDx6Mx2MQC2WK3U8Bemyg224ewOTDOiDAyBgxM2YHIKioYBu3HJPC+UFh8NBSKgEFQf1lIMR1EIMCxqoRYOWVg0zK2O32pxOTAFwDAngQIE2iBEug5ZtOF2A6CmpuOrsuXmFovFwEl0p18o1WC1wFD6v1qw0xVKcEtYAA4kh2nQYNBatRYmnEBms1A3F7GObGMmYs6uTy+cnmEnBQAlPQzGBuIgQLAiKv2L42F6orwNzhFXsO4ADgsiLy5uAAQV0RS4+cL0BLnLLp0rsVL3N5-MFDeTLd0bY7XZ7sT7k8HM5HiDH14nU6HCwZawTpGTbtQHhKwCeH6UweLa9qOtWW4WoKbgvDY7RwAAqn6AJIQMYyhKBoDgU6e61oeVpwKhcpvHAoQFiQUALAa8BaDo+g7CerY8PAFg0XAeBOI8cA0LgdCMLUSZFK0EA8D4DS8diFaCg08R0h+8YAY2Vqnue3iCV+5TKWAqksQAdJJ-FVh41FxvAX7abpMCrlAmbrupNRzjZdnFqW5Y7pB+51kelnMe23gPk+cA3q+M5zouy54M5RYbi60GEbum5eQRCi+WeLFAYF479neXimYycAWcmxK8P0ThAYJWF2kgEFuduMFwQhyHUKhiHoVWxj9CQ1CYWBNW4Ul+HJi1cJqq8HXhKY3VUORwCUfln5KUcdCwFgATFZCmw2lM9iMIgFKIMBcDLatAQVb0ZAcRA9gsuRaBtFRV2IAOUCoFSok0nMo0rYQbzJrCzQPXAigLYpiYbZmgGgVMLacVAIhuCRrwNrt+14odR2gRdV03e0d2tO0X2cc9OBvaEGIfTi32rX9goA-dCEgyo7F2A4WBOBxnDuYKbBOL9QQ2th-WQdzVq+NQAD6jxWph-BS5tITHT9a08BDmxy7opWmE4oQ-pc-6lBVsSdVNUgUIkcBS1r-wuE6evugbUN+hYuT5M42w8Jr8kKbY9ja84PzYpsovWlVOEiz67q+NLYChHV8Wh14Fvx9JVoVS7wB5AUo1Wt7LN+-8ABUcLkniyZuNQAqQ31DpOidhDrYKVebN05BwLgkChKOwP8LzGzYTXEGXR3EC6F3j7oV9mpYsCupfY8mbIGPcDd8o0cK7rCsNhLxObHaoR93vMAW0x6XWemtkxSnv7O9QxPcTHcebiHsXelyvqCYHkMv9fvo+BYVBp6KwaA0fgAZDDBjxo0Boiw5J3y4vATWWJ-abytCVZB-w3CaQqDHI6RQsC8B7DHD4rts54C5vVK0h8XhBB8DHBsC91ZwmtuzRA8QiLMIwawgYAAGDCaU2wGT4owOkQA)

**Comment by mjbvz** [comment]
Hey @RyanCavanaugh, can someone on the TS team please take a look since this looks like it could be a regression/change in behavior with 4.1

**Comment by DanielRosenwasser** [comment]
If this is a regression, we should consider whether something will need to be done for a patch release.

**Comment by rbuckton** [comment]
The `never` seems to come from the return type annotation? If I change `showStep` to explicitly return `Generator<QuickPickStep | QuickInputStep, StepResult<QuickPickItem>, any | undefined>` instead of the union produced by `StepResultGenerator<QuickPickItem>`, the error goes away: [Playground](https://www.typescriptlang.org/play?target=6&jsx=0&ts=4.1.0-beta#code/KYDwDg9gTgLgBMAdgVwLZwCIEsrAMYxYBuwcA3gFACQAQgIZ4DWANNQMJ2J7AA2rVAGQh0AJgFlowfgDkIEMKwC+FCqEiw4iOqmABnMA1LZcBYqUpU10eADNkXQhERwsugDwAVAHwAKInR5kYAAuTBx8QhI4AB84DwBKUP9A0lcwk0jzaipcGGQoZxgATzBgCBs4ZKC4AF46uAByFFQAI2AoBrgAMi70iLMAbSrgAF04AEIazWQeHgBuamVlVXBrF0QYdptDOABFZCwmAAVDxgBJTfQLHjo2nlDdGCgsRABzBaoRPTxnsEdEAD8DyeL3e1C+MDoWB4QLgj2ebw+YFOwBEsJach4wE4HwCAHc6EVdABlAAWEDx6Mx2MQC2WK3U8Bemyg224ewOTDOiDAyBgxM2YHIKioYBu3HJPC+UFh8NBSKgEFQf1lIMR1EIMCxqoRYOWVg0zK2O32pxOTAFwDAngQIE2iBEug5ZtOF2A6CmpuOrsuXmFovFwEl0p18o1WC1wFD6v1qw0xVKcEtYAA4kh2nQYNBatRYmnEBms1A3F7GObGMmYs6uTy+cnmEnBQAlPQzGBuIgQLAiKv2L42F6orwNzhFXsO4ADgsiLy5uAAQV0RS4+cL0BLnLLp0rsVL3N5-MFDeTLd0bY7XZ7sT7k8HM5HiDH14nU6HCwZawTpGTbtQHhKwCeH6UweLa9qOtWW4WoKbgvDY7RwAAqn6AJIQMYyhKBoDgU6e61oeVpwKhcpvHAoQFiQUALAa8BaDo+g7CerY8PAFg0XAeBOI8cA0LgdCMLUSZFK0EA8D4DS8diFaCg08R0h+8YAY2Vqnue3iCV+5TKWAqksQAdJJ-FVh41FxvAX7abpMCrlAmbrupNRzjZdnFqW5Y7pB+51kelnMe23gPk+cA3q+M5zouy54M5RYbi60GEbum5eQRCi+WeLFAYF479neXimYycAWcmxK8P0ThAYJWF2kgEFuduMFwQhyHUKhiHoVWxj9CQ1CYWBNW4Ul+HJi1cJqq8HXhKY3VUORwCUfln5KUcdCwFgATFZCmw2lM9iMIgFKIMBcDLatAQVb0ZAcRA9gsuRaBtFRV2IAOUCoFSok0nMo0rYQbzJrCzQPXAigLYpiYbZmgGgVMLacVAIhuCRrwNrt+14odR2gRdV03e0d2tO0X2cc9OBvaEGIfTi32rX9goA-dCEgyo7F2A4WBOBxnDuYKbBOL9QQ2th-WQdzVq+NQAD6jxWph-BS5tITHT9a08BDmxy7opWmE4oQ-pc-6lBVsSdVNUgUIkcBS1r-wuE6evugbUN+hYuT5M42w8Jr8kKbY9ja84PzYpsovWlVOEiz67q+NLYChHV8Wh14Fvx9JVoVS7wB5AUo1Wt7LN+-8ABUcLkniyZuNQAqQ31DpOidhDrYKVebN05BwLgkChKOwP8LzGzYTXEGXR3EC6F3j7oV9mpYsCupfY8mbIGPcDd8o0cK7rCsNhLxObHaoR93vMAW9F64px5eEHvWaXninv7Divj7Zbe07O9QxPcTHcebiHsXelyvpBKB0hr-O+vofAWCoNPRWDQGj8ADIYYMeNGgNEWHJd+XF4CayxP7TeVoSo4P+G4TSFQY5HSKFgXgPYY4fFdtnPAXN6pWkPi8IIPgY4NgXurOE1t2aIHiERHhhC+EDAAAwYRvvpQyjA6RAA)

I'll have to look into what changed caused this.

**Comment by eamodio** [comment]
@rbuckton Any update on this -- still seeing it with 4.2-beta

**Comment by Andarist** [comment]
I updated one of my open PRs to cover for this case as well: https://github.com/microsoft/TypeScript/pull/51196
