### ISSUE TITLE
Easily bypass type inference even with guards

### ISSUE THREAD

**Issue by Mdsp9070** [microsoft/TypeScript#41437]
**TypeScript Version:**  4.0.5

**Search Terms:** guards, arrays types

**Code**

```ts
function isNumberArray(arr: Array<string | number>): arr is number[] {
    return arr.every(x => typeof x === "number")
}

function messUpTheArray(arr: Array<string | number>): void {
    if (isNumberArray(arr)) {
        arr.push(3)
        return
    }

    arr.push(3)
}

const strings: Array<string> = ['foo', 'bar'];
messUpTheArray(strings);

const s: string = strings[2];
console.log(s.toLowerCase())
```

**Expected behavior:** Compiler complain about trying to push a number into a string Array. First I tried without guard and obviously the compiler did nothing. This causes on the last line:
"s.toLowerCase is not a function".

**Actual behavior:** Compiler infer that even after the guard, the arrays is of type (string | number)[] and accepts pushing a number into a string array. Th

**Playground Link:** https://bit.ly/3lcJBH6 (shortened because the link was giant)

**Comment by MartinJohns** [comment]
Completely unrelated to type guards:

    const strings: Array<string> = ['foo', 'bar'];
    const stringsOrNumbers: Array<string | number> = strings;
    stringsOrNumbers.push(3);

    const s: string = strings[2];
    console.log(s.toLowerCase())

See: https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant

**Comment by JoostK** [comment]
I don't think variance is even relevant here; the fact that `isNumberArray` determines that the array only contains numbers does not mean that if that is not true that the array only contains strings.

You can actually get an error here with a more specific types for the `arr` parameter:

```ts
function messUpTheArray(arr: Array<string> | Array<number>): void {
    if (isNumberArray(arr)) {
        arr.push(3)
        return
    }

    arr.push(3) // error TS2345: Argument of type 'number' is not assignable to parameter of type 'string'.
}
```

This works because the type system now captures the fact that the array only ever contains strings, or numbers, but not both. Whether that is true or not in your situation I cannot tell (based on the implementation of `isNumberArray` it might not be) but if you can in fact have mixed arrays, then there is no error to be reported for that code.

**Comment by Mdsp9070** [comment]
Ok, now I understand it! These tricky types sometimes confuses me, I'm just getting into now!
