### ISSUE TITLE
Operator '+' cannot be applied to types 'T' and 'T'

### ISSUE THREAD

**Issue by jflatow** [microsoft/TypeScript#41449]
I think @Jameskmonger is right that this is a compiler bug. The type `T` is definitely known and constrained by the compiler to be a specific type, that's important to how generics fundamentally work and why the compiler refuses to compile even if you force it to accept the addition, e.g.:

```
type Numeric = bigint | number;

function sum<T extends Numeric>(a: T, b: T) {
  return <any>a + <any>b;
}


console.log(sum(1, 2))
console.log(sum(1n, 2n))
console.log(sum(1n, 2))
```

Note that the last sum is refused by the compiler (not at runtime).

From previous discussion:

@Jameskmonger if `T extends string | number` then `T` can be `string | number` which means one value of type `T` can be `string` a different value of type `T` can be a `number`.

It really sounds like you should use overloads here rather than a type parameter.

_Originally posted by @RyanCavanaugh in https://github.com/microsoft/TypeScript/issues/12410#issuecomment-286860930_

**Comment by Nathan-Fenner** [comment]
This is behaving somewhat unusually, but not for the reason you're thinking.

```ts
const x: number = 45;
const y: bigint = 45n;

const z = x + y;
//        ^^^^^ Operator '+' cannot be applied to types 'number' and 'bigint'.(2365)
```

It is entirely legal to write `sum<number | bigint>(1, 2n)`, where `T` is explicitly instantiated to include both numbers and BigInts. So without `as any` casts inside `sum`, the compiler _rightly_ rejects:

```ts
function sum<T extends bigint | number>(a: T, b: T) {
    return a + b;
}
```

since there's no guarantee that `a` and `b` are both `number` or are both `bigint`, which is needed to be able to use `+` to combine them.

---

What's weird here is that the third function call is rejected at all - it has nothing to do with the `+`, and everything to do with TypeScript's constant inference going haywire. Read the error message (the following case makes it more clear):


```ts
function weirdInference<T extends bigint | number>(a: T, b: T) {
  return null;
}

console.log(weirdInference(1, 2)); //   inferred: T = 1 | 2
console.log(weirdInference(1n, 2n)); // inferred: T = 1n | 2n
console.log(weirdInference(1n, 2)); //  inferred: T = 1n
console.log(weirdInference(1, 2n)); //  inferred: T = 1
```

For some reason, TypeScript is unwilling to infer a union of `number` and `bigint` types. The above example is using constant types, but it also applies if that's not the case:

```
function weirdInference<T extends bigint | number>(a: T, b: T) {
  return null;
}

function makeNum(): number {
  return Math.floor(Math.random() * 100);
}
function makeBig(): bigint {
  return BigInt(Math.floor(Math.random() * 100));
}
console.log(weirdInference(makeNum(), makeNum())); // inferred T = number
console.log(weirdInference(makeBig(), makeBig())); // inferred T = bigint

console.log(weirdInference(makeNum(), makeBig())); // inferred T = number
console.log(weirdInference(makeBig(), makeNum())); // inferred T = bigint
```

Of course, explicitly specifying `T` to be `number | bigint` passes:

```ts
weirdInference<number | bigint>(1, 2n);
```

thus this is just a problem with inference.

**Comment by MartinJohns** [comment]
Related: #27808

**Comment by jflatow** [comment]
Hm yes I think I was expecting it to behave like #27808 would. It's kind of surprising to me that `|` *doesn't* behave like `oneof`, since it would be easier to decouple args to be different types than to constrain them, and there seems to be no way currently to narrow them as intended.

**Comment by RyanCavanaugh** [comment]
Everything described so far is the intended behavior. Not inferring union types from disparate candidates is 100% intentional; this doesn't yield expected results in a huge majority of cases even though it can be theoretically justified.

**Comment by Zain-ul-din** [comment]
@RyanCavanaugh why this is not working this should suppose to work since I'm saying both a and b type would be the same

```ts
type Addable = string | number
type BeSame<T>= T extends number ? number : string
function addMe<T extends Addable,U extends BeSame<T>>(a: T,b: U) {
    return a+b;
}
```

**Comment by RyanCavanaugh** [comment]
TypeScript isn't equipped to do the kind of inference you're expecting here
