### ISSUE TITLE
Typescript doesn't support Contacts and mozContacts in Navigator. please add it in future updates

### ISSUE THREAD

**Issue by noonhe** [microsoft/TypeScript#41442]
I need to open user's phone contacts from my Angular app and I need to use the contacts and mozContacts to do it but there are errors that say: properties 'contacts' and 'mozContacts' don't exist in Navigator.

**Comment by MartinJohns** [comment]
Please use the issue templates for [bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Bug_report.md) and [feature requests](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Feature_request.md). This will make it much easier for the TypeScript team and allows them focus on improving the language, instead of decyphering GitHub issues. :-)

---

`Navigator.contacts` seems to be a **very early draft**. The [Mozilla documentation](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/contacts) does not even list a specification for it. Such early and experimental features are usually not supported by TypeScript (see the [TypeScript-DOM-lib-generator](https://github.com/microsoft/TypeScript-DOM-lib-generator) readme).

You will have to make use of [Declaration Merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) and provide your own types in your projects.

**Comment by noonhe** [comment]
> Please use the issue templates for [bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Bug_report.md) and [feature requests](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Feature_request.md). This will make it much easier for the TypeScript team and allows them focus on improving the language, instead of decyphering GitHub issues. :-)
> 
> `Navigator.contacts` seems to be a **very early draft**. The [Mozilla documentation](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/contacts) does not even list a specification for it. Such early and experimental features are usually not supported by TypeScript (see the [TypeScript-DOM-lib-generator](https://github.com/microsoft/TypeScript-DOM-lib-generator) readme).
> 
> You will have to make use of [Declaration Merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) and provide your own types in your projects.

It's being used in other angular apps and I need to use it too. 


`interface NavigatorContacts{
  readonly contacts : ContactsManager
}

interface ContactsManager {
  getProperties() : Promise<string[]>;
  select(properties:string[], options?:boolean) : Promise<any>;
};

interface Navigator extends NavigatorContacts{}`

I added this code to my component but there's still that error. can you please tell me how to make it work?
