### ISSUE TITLE
Cannot use arguments.callee to remove a listener

### ISSUE THREAD

**Issue by chrilith** [Microsoft/TypeScript#4147]
Hi,

When using quick addListener/removeListener I used to something like this:

```
target.addEventListener("animationEnd", function() {
	this.removeEventListener("animationEnd", arguments.callee);
	// ... do more here ...
});
```

But with TypeScript, a Function is not assignable to a EventListenerObject.

Of course I can save my function in a var and use this var when removing the listener. But I'd like to understand it is not possible to use `callee` here.

Thanks!

**Comment by kitsonk** [comment]
The above is [valid TypeScript](http://www.typescriptlang.org/Playground#src=let%20target%20%3D%20document.createElement('div')%3B%0A%0Atarget.addEventListener(%22animationEnd%22%2C%20function()%20%7B%0A%20%20%20%20this.removeEventListener(%22animationEnd%22%2C%20arguments.callee)%3B%0A%20%20%20%20%2F%2F%20...%20do%20more%20here%20...%0A%7D)%3B%0A):

```typescript
let target = document.createElement('div');

target.addEventListener("animationEnd", function() {
    this.removeEventListener("animationEnd", arguments.callee);
    // ... do more here ...
});
```

So any issue you are having a runtime issues, likely because it is running in [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#Making_eval_and_arguments_simpler) where `arguments.callee` doesn't exist or you are running it as an ES6 module, which is always in strict mode.

**Comment by chrilith** [comment]
Indeed, now it seems to work... weird... when I posted this example, SublimeText was telling me that a Function is not assignable to a EventListenerObject.

Closed then. Sorry.
