### ISSUE TITLE
HTMLOrSVGElement does not extend Element

### ISSUE THREAD

**Issue by MarsiBarsi** [microsoft/TypeScript#41529]
**TypeScript Version:**  any

**Expected behavior:**
HTMLOrSVGElement extends Element

**Actual behavior:**
it does not

**Playground Link:** https://www.typescriptlang.org/play?ts=4.2.0-dev.20201112#code/DYUwLgBAhgXBASAVAsgGQPICcDKA1A4gKKgC2IAdmANwBQokARnMSGZbTQxALzRVA

**Comment by RyanCavanaugh** [comment]
This is correct; Element lacks some things that are in both HTMLElement and SVGElement

**Comment by MarsiBarsi** [comment]
Thank you for answer, @RyanCavanaugh! 
Sure. My proposal is to extend `HTMLOrSVGElement` with `Element` because both `HTMLElement` and `SVGElement` are actually `Element`

**Comment by RyanCavanaugh** [comment]
The interface describes the common properties between `HTMLElement` and `SVGElement`. It's still not safe to assign an arbitrary `Element` to that

If you have `DogOrCat`, you still can't assign a `Mammal` to it, because there are `Mammal`s that aren't `Dog`s or `Cat`s` even though both of those are `Mammal`s. This would only be valid if you could prove that there are no other `Mammal`s *except* `Dog` or `Cat`, but this isn't the case.

**Comment by waterplea** [comment]
@RyanCavanaugh I believe you are confused because playground link is incorrect example. With your example of `DogOrCat` interface and `Mammal` — `DogOrCat` **IS** a `Mammal` therefore `DogOrCat` should extend `Mammal`. Right now, say, if `Mammal` interface has `milk` property, `DogOrCat` interface doesn't have it, although it should.

**Comment by RyanCavanaugh** [comment]
I don't disagree, but the example provided attempts to assign an `Element` to an `HTMLOrSVGElement`, which still shouldn't be allowed.

**Comment by MarsiBarsi** [comment]
Yes, I am very sorry :) I have meant to show this: https://www.typescriptlang.org/play?ts=4.2.0-dev.20201112#code/DYUwLgBAhgXBASAVAsgGQPICcDKA1A4gKKgC2IAdmANwBQokARnMSGZbTQxALzRVA

**Comment by ExE-Boss** [comment]
The current behaviour is correct, because <code>[HTMLOrSVGElement]</code> is an <code>[interface mixin](https://heycam.github.io/webidl/#idl-interface-mixins)</code>:
```webidl
interface mixin HTMLOrSVGElement {
  [SameObject] readonly attribute DOMStringMap dataset;
  attribute DOMString nonce; // intentionally no [CEReactions]

  [CEReactions] attribute boolean autofocus;
  [CEReactions] attribute long tabIndex;
  undefined focus(optional FocusOptions options = {});
  undefined blur();
};
```

[HTMLOrSVGElement]: https://html.spec.whatwg.org/multipage/dom.html#htmlorsvgelement
