### ISSUE TITLE
Type inference not working with private fields from constructor

### ISSUE THREAD

**Issue by Apacheli** [microsoft/TypeScript#41535]
**TypeScript Version:**  4.x

**Search Terms:**
private class field, type prediction, inference

**Code**
```ts
class Testing {

  #test;
  test;

  constructor(test: string) {
    this.#test = test;
    this.test = test;
  }
}
```

**Expected behavior:**
`Testing.#test` should have type `string` implied as it's type. This behavior seems to work correctly with `Testing.test`.

**Actual behavior:**
`Member '#test' implicitly has an 'any' type.ts (7008)`

**Playground Link:** [here](https://www.typescriptlang.org/play?useDefineForClassFields=true&target=99&module=1#code/MYGwhgzhAEAqCmEAuBLAdgc2gbwLACgDpoBiJRJAbiOnOWsP2OAHs1kAnAV2CRY4AUdJAC5ondBgCUOGsSQALFBAB0ZCtAC8tCg2Lylq4Vp30aAXwKXGaeAHc4FSQIDkACXggQLADTQA6vwgACYAhC5SDEA)

**Related Issues:**

**Comment by a-tarasyuk** [comment]
@RyanCavanaugh It seems this issue was fixed in 4.1.* - [`Example`](https://www.typescriptlang.org/play?useDefineForClassFields=true&target=99&module=1&ts=4.1.0-beta#code/MYGwhgzhAEAqCmEAuBLAdgc2gbwLACgDpoBiJRJAbiOnOWsP2OAHs1kAnAV2CRY4AUdJAC5ondBgCUOGsSQALFBAB0ZCtAC8tCg2Lylq4Vp30aAXwKXGaeAHc4FSQIDkACXggQLADTQA6vwgACYAhC5SDEA)
