### ISSUE TITLE
Object contextual type has no effect in nested object assignment in JS

### ISSUE THREAD

**Issue by kazarmy** [microsoft/TypeScript#41593]
**TypeScript Version:**  4.2.0-dev.20201119

**Search Terms:**

javascript cast narrow array tuple

Sorry but didn't find any duplicates within a reasonable amount of time. Didn't check every issue on every page though.

**Code**

```js
/**
 * @type {import('eslint').Linter.Config<import('eslint/rules').ESLintRules>}
 */
const config = {
  rules: {
    'strict': 2,
  },
};
// ...
config.rules.strict = [2, 'global'];
```

Code is JavaScript. Using `@types/eslint` 7.2.5.

**Expected behavior:**

No error.

**Actual behavior:**

```
Type '(string | number)[]' is not assignable to type 'RuleEntry<["function" | "safe" | "global" | "never"]>'.
  Type '(string | number)[]' is not assignable to type '[RuleLevel, ("function" | "safe" | "global" | "never")?]'.
    Target requires 1 element(s) but source may have fewer.ts(2322)
```

on the `config.rules.strict` line.

Workaround is to do:

```js
config.rules.strict = /** @type {typeof config.rules.strict} */ ([2, 'global']);
```

or the less cumbersome but apparently undocumented:

```js
/** @type {typeof config.rules.strict} */
config.rules.strict = [2, 'global'];
```

I confirm that the type checking does work with either of the annotations (e.g. replacing `'global'` with `'globa'` will elicit a complaint from the type checker). In either case though, imho better not to have the annotation at all since it interrupts code reading flow.

**Playground Link:**

Emm couldn't get the `import('eslint')` to work in the Playground.

**Related Issues:**

Unfortunately no. If I find any, I'll add them to this list.

**Comment by andrewbranch** [comment]
Self-contained example:

```js
/**
 * @typedef {["one", "two"]} Num
 */

 /** @type {{ prop: { blah: Num } }} */
 const obj = {
   prop: {
     blah: ["one", "two"]
   }
 };

obj.prop.blah = ["one", "two"];
```

Interestingly, the error goes away if

- you remove the `prop` object, so it’s just an assignment to `obj.blah`, or
- the `Num` type is not objecty

**Comment by sandersn** [comment]
The binder can't tell that `obj.prop.blah = ['one', 'two']` isn't an expando declaration, so it speculatively creates a symbol on `blah`. This is incorrect in this case, since there's already a declaration of `obj` around. It also wouldn't make sense in a module, because the speculative symbol just exists to allow global merges.
(It's also possible that the symbol is completely incorrect.)

The presence of the symbol means that the checker also thinks that the assignment is a declaration, and declarations don't get contextual types from their left side.

The singly-nested case (`obj.blah`) has the same incorrect binding, but there's a bizarre fallback that redoes a lot of the work that getTypeOfExpression would do on a single identifier, but only if the declaration has an explicit type annotation.

I'm going to try making the binder stricter and see whether I can get rid of some of this special-case code. I'll leave this in 4.2 for now in case it turns out to be a simple bug, but if I have to improve the binder significantly I'll move it to 4.3.

**Comment by sandersn** [comment]
1. binder: nope.The binder only inspects declarations, not initialisers, so it can't know that `blah` is already bound.
2. checker: nope. Replacing the bizarre fallback with `getTypeOfExpression` causes lots of stack overflows and circular `any`s.

There might be a cleverer bizarre fallback I haven't thought of, and of course it's possible to expand the current bizarre fallback to *two* levels instead of just *one*.

At this point I'm not sure there's a good fix for this bug.

**Comment by kazarmy** [comment]
I've turned the associated `.eslintrc.js` configuration file into a `.eslintrc.cts` file (TypeScript 4.6.3) and all seems to work well so I'm closing this issue.
