### ISSUE TITLE
noUncheckedIndexedAccess gives unexpected behavior for string.split

### ISSUE THREAD

**Issue by sla100** [microsoft/TypeScript#41638]
**TypeScript Version:**  4.1.2

**Search Terms:**
`4.1.2` `split`

**Code**

```ts
const [a] = 'a:b'.split(':');
```

**Expected behavior:**
typeof `a` should be `string`

string.split ALWAYS return string at first position

**Actual behavior:**
tyeof `a` is `string|undefined`

**Comment by ilogico** [comment]
Do you have `noUncheckedIndexedAccess` turned on?

**Comment by sla100** [comment]
Yes

**Comment by AlCalzone** [comment]
Then you did not read the release notes:
![image](https://user-images.githubusercontent.com/17641229/99998638-4ab03f00-2dbf-11eb-9ad8-2d079ba54b4f.jpeg)

**Comment by sla100** [comment]
But "more trickly" !== incorrect. 
First item of `string.split` NEVER will be empty.

**Comment by AlCalzone** [comment]
String.split returns an array. You're indexing into the array.

**Comment by RyanCavanaugh** [comment]
> First item of string.split NEVER will be empty

This is actually tricky since it depends on the splitter argument. `"".split("")` is `[]`

I don't think we want to bother special-casing the result of this function based on the split input.

**Comment by sharshuv-quotient** [comment]
> This is actually tricky since it depends on the splitter argument. "".split("") is []
> 
> I don't think we want to bother special-casing the result of this function based on the split input.

So the _only_ case that the first element in the array can be undefined is if both the string being split, and the separator are an empty string?

I think in almost all most situations this is not the case, and I wish typescript could handle that better:

**Option 1**:  in situations in which one of the strings (the one being split, or the separator) are known in advanced to be not empty, typescript should interpret the first item of the resulting array to be defined.
**Option 2**: expose a dedicated tsconfig flag for this scenario, to be used together with `noUncheckedIndexedAccess`, in order to customize the behavior of split, so that the first item is always defined. I would use this flag as I can live with the edge case of `''.split('')`

**Comment by RyanCavanaugh** [comment]
You can put this in your project
```ts
interface String {
    split(splitter: ""): string[];
    split(splitter: string): [string, ...string[]][];
}
```
We don't need a commandline flag for that.

**Comment by rpmccarter** [comment]
@RyanCavanaugh thanks for the tip! But just in case anyone else stumbles upon this, I believe the correct typing is
```ts
interface String {
    split(splitter: ""): string[];
    split(splitter: string): [string, ...string[]];
}
```
(no brackets at the end of the second `split`)
