### ISSUE TITLE
Normalize our lib files by compiler settings

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#4168]
Right now the compiler depends on a monolithic `lib.d.ts` file that is resolved according to the script target (ES5 or ES6). We have to build several different lib.d.ts files out of smaller parts.

We should refactor this so that the different aspects of the compiler settings can map to smaller sub-parts of the libraries.

Language target:
 * ES3
 * ES5
 * ES6
 * Latest

Host:
* Browser with DOM
* WebWorker
* NodeJS
* Windows Script Host :mask: 

Module system:
* CommonJS
* AMD
* None

The idea is that we a function that takes a CompilerSettings and produces a list of filenames. These files might reference each other, e.g. `lib.es5.d.ts` would probably reference `lib.es6.d.ts` and just provide interface augmentations.

This provides several benefits:
* It will be easier for us to edit these files because they are smaller
* It will be easier for users to patch in only specific versions if they decide they need to fork certain things
* It will be possible for users to have a custom version of one file while still getting bug fixes for the other files
* Provides a more natural way to shim in specific things based on compiler settings without having a combinatorial explosion of concatenated lib.d.ts files

**Comment by weswigham** [comment]
A _really_ common practice right now is compiling for ES5, but still needing ES6 `Promise` types. The DefinitelyTyped `es6-promise` types get used in combination with the ES5 lib in this case right now, but it would be _very_ nice if we could enable/disable `lib.d.ts` parts by _feature_, rather than by target spec (since the spec version target is just a collection of features, from a consumer of TS's point of view).

Breaking down the stdlib files into more parts could help work towards this considerably.

**Comment by mhegazy** [comment]
so what is the granularity, what needs to be in a flle by itself and what is not.. also what is draw back from just including all es6 types?

**Comment by weswigham** [comment]
Including ES6 types would drop many extra types into your IDE/Editor experience which you don't actually have access to in your targeted environment, for one. Beyond that, many awkward things (interface redefinitions and the like) happen when you try to depend on a partial ES6 polyfill `.d.ts` (like one included by a library you're using) file alongside the full TS ES6 lib.

**Comment by mhegazy** [comment]
I agree with the principal, my question is about the details.. what is the granularity? is it down to methods (es6.array.is.d.ts) or containers (es6.array.d.ts, es6.object.d.ts), or areas (es6.core.d.ts, es6.typedarrays.d.ts, es6.promise.d.ts)?
a concreate list of files we want to generate would be ideal.

**Comment by weswigham** [comment]
If we can get away with it, the highest level of granularity possible will allow the greatest amount of compiler consumer control later (and also combinatoric expansion in possible compiler configurations). 

Generally speaking though, I'd say I'm partial to group by feature area ([like how babel groups language features](https://babeljs.io/docs/advanced/transformers/)), since it's seemed like that's how they've gotten implemented in [JS environments](https://www.chromestatus.com/features) - one feature at a time. (Eg, the 'Set' API, the 'Map' API, the new 'Array' API, etc.)

**Comment by yortus** [comment]
If more granuar targetting is on the cards, then some consideration ought to be given to **emit**, not just lib files, for precisely the same motivations.

As @weswigham points out, JS environments implement and release features incrementally. Babel reflects this reality. With TypeScript one must choose the lowest common denominator for the target, even if the environment supports many but not all features of a higher target. Otherwise the emitted code will not run on the target. For example its still prudent to target ES5 for node projects, even though V8 now supports a great many ES6 features.

My suggestion would be to add a key to `tsconfig.json`, something like so:
```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "ES5",
        "targets": {
            "builtins.map": "ES6",
            "builtins.weakMap": "ES6",
            "syntax.arrowFunctions": "ES6",
            "syntax.generators": "ES6",
            "syntax.templateStrings": "ES6"
        }
    }
}
```

So a project can have a default target, and then override targets for particular features it uses. Note that 'features' cover far more than just `lib.d.ts` contents - they affect emit too. I know the emit part is straightforward to implement in the compiler because our fork does exactly this to support node.js (ES5) + native generators (ES6) compiling fine with `tsc`.

**Comment by LPGhatguy** [comment]
I definitely agree with the proposal @yortus has included, and I filed an issue about it independently with issue #4389. This only solves the problem of weird inbetween JS targets, not DOM features, though. Maybe they could be solved with a similar idea?

**Comment by Arnavion** [comment]
How would this work with something that crosses features like symbols, which would add members to other types that may or may not be there?

For example, the presence of "builtins.symbol" cannot naively result in `interface Promise<T> { [Symbol.species](); }` being included to the generated lib.d.ts, *unless* "builtins.promise" is also defined. So it seems the constituent .d.ts will need to be property-level granular (promise.symbol.d.ts), not feature-level (promise.d.ts, symbol.d.ts).

**Comment by weswigham** [comment]
I imagine `builtins.symbol` would define symbols in isolation (the Symbol object, maybe covertly turn on the compiler flag to support them as indexers), then we could have separate extensions to `builtins.promise` which depend on `builtins.symbol`, like `builtins.promise.symbolextensions`, which define the additions to the promise interface which _can_ come with symbols.

Symbols are a little interesting since a full implementation of them touches a lot of other objects... regexes, arrays, etc... but those well-known symbols aren't always present depending on the target('s implementation status), so being able to choose the ones you know will exist is a good thing.

**Comment by yortus** [comment]
I made a proposal for a possible solution over at #4692. There is a working implementation too.

**Comment by bpasero** [comment]
I like this approach, but will I be able to define a new host? TypeScript should not hardcode the possible hosts my code can run in but provide a solution where I can provide my own host. To give an example: Electron is a host for JavaScript that adds API on top of plain JS and node.js. Specific versions of Electron might have different API. I want to express in my tsconfig.json that the host is "Electron: 0.34.x".

**Comment by mhegazy** [comment]
> Specific versions of Electron might have different API. I want to express in my tsconfig.json that the host is "Electron: 0.34.x".

I do not think we can do a generic support for all hosts, the ones we know about are "core", i.e. some ES3/ES5/ES6 compliant engine (things like Object, JSON, Error, etc..), and "DOM" (regular and webworker, only latest, version would not possible here). for anything else, you need to pass a .d.ts for your host. so you should have `electron.0.34.d.ts` that you feed in to the compiler along with `--noLib` and things should just work.

**Comment by mhegazy** [comment]
subsumed by https://github.com/Microsoft/TypeScript/issues/6974

**Comment by remojansen** [comment]
Hi guys, 

I'm getting:

    TypeScript error: Error TS2318: Cannot find global type 'Array'.

Only in [one version of node (6.5.0 x86)](https://ci.appveyor.com/project/remojansen/inversifyjs/build/186) with [tsify](https://github.com/TypeStrong/tsify). I'm not sure about what is causing the issue but I'm using:

    "target": "es5",
    "lib": ["es6", "dom"]

Any ideas? Full details available at [tsify/issues/196](https://github.com/TypeStrong/tsify/issues/196).

Thanks!

**Comment by mhegazy** [comment]
do you happen to have `--noResolve` set?

**Comment by remojansen** [comment]
I'm using `noResolve` false (default)

**Comment by RyanCavanaugh** [comment]
This is likely a `tsify` bug. The gulp TS plugin had a similar issue

**Comment by remojansen** [comment]
Thanks for helping me out @RyanCavanaugh @mhegazy it is now confirmed as a [tsify bug](https://github.com/TypeStrong/tsify/issues/196).

**Comment by RyanCavanaugh** [comment]
Thanks!

**Comment by RyanCavanaugh** [comment]
Oops
