### ISSUE TITLE
const/let variables with require() initializer are not correctly block-scoped

### ISSUE THREAD

**Issue by sokra** [microsoft/TypeScript#41697]
**TypeScript Version:** 4.2.0-dev.20201126

**Search Terms:** TS2300

**Code**

```js
// compiled in JS mode. Works fine when compiled as TS
switch(something) {
    case "a": {
        const x = require("fs"); // TS2300: Duplicate identifier 'x'
        console.log(x);
        break;
    }
    case "b": {
        const x = require("fs"); // TS2300: Duplicate identifier 'x'
        console.log(x);
        break;
    }
    case "c": {
        const x = 123; // No error (only happens with require() as initializer)
        console.log(x);
        break;
    }
}
x.readFileSync("x"); // should be error
```

**Expected behavior:**

No TS2300 error. `const` variables should be block-scoped.

**Actual behavior:**

`const` variables with `require()` initializer leak into outer scope. Looks like they are incorrectly function scoped.

**Playground Link:** [Playground link](https://www.typescriptlang.org/play?ts=4.2.0-dev.20201126&useJavaScript=true#code/JYWwDg9gTgLgBAIgHYQCYFMEG4BQODOA7sDAMYAWAFMUqhIQHQA2EpAhjMBEg+VOgDMAlHADeOOJLjt86RGwQAuMRKlrS3fPAAecALxx+ARwCuwfpQQD8CIbjXrNEJumYQA5pW13VDuACN+NgBreykAX19pNllEfyUVP0kNJC04XQNjMwsrGx8k6ScXN09vML9A9BDyuEj1GLkEUgTxApS0jLgARgAmAGYsOAB6IbgAOQg4dCgoaCjHVOdXFlL8pMrqqMjI7QYg1AAxYBcAZQBPJFJLbVtBkbh8cggTJlQAuWnZqCA)

**Related Issues:**

**Comment by ExE-Boss** [comment]
That’s because in **JS** code, **TypeScript** treats
```js
const x = require("foo");
```
as
```ts
import x = require("foo");
```
which gets transpiled to
```js
var x = require("foo");
```

**Comment by sk-** [comment]
Thu culprit seems to be #39770. Unfortunately there was no mention of this change in the release notes and there are many related issues.

**Comment by RyanCavanaugh** [comment]
> Unfortunately there was no mention of this change in the release notes 

We didn't realize it was a break at the time -- our bad!

**Comment by sandersn** [comment]
I surveyed Definitely Typed, our user tests and all the code in their `node_modules` to see how often this is used, and found that 5 projects used it outside of generated code or tests.

The total number of duplicated imports is quite small: 55 out of 71,000 non-toplevel `require` calls in aws-sdk, `@babel/core`, webassembly-feature and read-installed:

- `require` json files in different functions, all with the same type
- `require` different protocol handlers, all with the same type
- some kind of delayed evaluation pattern
- codegen repeated `require` calls for feature detection
- conditionally `require('graceful-fs')` with a fallback to `fs`. I assume they must be treated as if they have the same type.

So:
- this affects a small proportion of non-toplevel imports
- most JS users don't have checkJS on, which would not report the error, but give the error semantics where the first `require`'s type is used.
- more than half of the duplicated `require`s gave [nearly] the same type to every `require`, which would make the error semantics [nearly] the same as correct semantics
- block-scoping wouldn't give the correct semantics to the codegen examples, just silence the error.

I think the value of just silencing the error is pretty low since it only helps checkJS code bases, and we expect checkJS code bases to be on the way to using TS/ES imports anyway. Especially if the cost is making the 71,000 other non-toplevel `require` back into non-aliases.
