### ISSUE TITLE
variadic tuple types broken since 4.1.2 (same error as in 3.x.x)

### ISSUE THREAD

**Issue by ChillkroeteTTS** [microsoft/TypeScript#41701]
**TypeScript Version:**  
4.1.2 and newer

**Search Terms:**  
rest elements, variadic tuple types

**Code**

```ts
type Numbers = number[];
type test = [...Numbers, string];
```

**Expected behavior:**
It should compile as it does in 4.0.5

**Actual behavior:**
tsc fails with the following (3.x like) error message
>  A rest element must be last in a tuple type.

**Playground Link:** 
https://www.typescriptlang.org/play?ts=4.1.2#code/C4TwDgpgBAcgrgWwEYQE4GcoF4oDtEqoDaAugNwBQokUwE6w2URAdG-MmugDRQOoBLXAHNyQA

**Related Issues:**

**Comment by AviVahl** [comment]
This changed with 4.0:https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/#variadic-tuple-types

**Comment by whzx5byb** [comment]
related: https://github.com/microsoft/TypeScript/pull/41544

**Comment by RyanCavanaugh** [comment]
This is a correct error since the output type is absolutely not what you think it will be. The linked PR will make it not an error and make it do what you expect

**Comment by joshkel** [comment]
I ran into this today while experimenting with tuple types. If I understand correctly, this is exactly the case that was advertised as TypeScript 4.0's ["variadic tuple types"](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#variadic-tuple-types):

> But with TypeScript 4.0, this restriction is relaxed.
>
> Note that in cases when we spread in a type without a known length, the resulting type becomes unbounded as well, and all the following elements factor into the resulting rest element type.
> 
> ```
> type Strings = [string, string];
> type Numbers = number[];
>
> type Unbounded = [...Strings, ...Numbers, boolean];
> ```

That example from the TypeScript 4.0 docs is working in 4.0 ([Playground Link](https://www.typescriptlang.org/play?ts=4.0.5#code/C4TwDgpgBAysBOBLAdgcwM5QLxQNroRVQBooCk0BdAbgChRIoA5AVwFsAjCeTHZdrvFw1a9cNACqyDgHsWyACYQF2PADoNcChlIa1rTt3SlZMgDYQAhshFA)) and not working in 4.1 ([Playground Link](https://www.typescriptlang.org/play?ts=4.1.3#code/C4TwDgpgBAysBOBLAdgcwM5QLxQNroRVQBooCk0BdAbgChRIoA5AVwFsAjCeTHZdrvFw1a9cNACqyDgHsWyACYQF2PADoNcChlIa1rTt3SlZMgDYQAhshFA)), so it does seem like a regression in 4.1 rather than "working as intended"?

Or am I misunderstanding?
