### ISSUE TITLE
Function extends Record<string, any> but not Record<string, unknown>

### ISSUE THREAD

**Issue by jo32** [microsoft/TypeScript#41746]
**TypeScript Version:**  4.1.2

**Search Terms:**
extends unknown

**Code**

```ts
type A = (() => true) extends Record<string, any> ? true : false; // true
type B = (() => true) extends Record<string, unknown> ? true : false; // false
```

**Expected behavior:**
type A and type B should be the same

**Actual behavior:**
not the same

**Playground Link:** 
https://www.typescriptlang.org/play?#code/C4TwDgpgBAglC8UAUSCUCB8VgCcCuE6EAHsBAHYAmAzlAEoQDGA9jpQDzW4CW5A5gBooAQ3IgsAfmz5oALigAzYQBtqEANxQA9FukEAUKEhQAQgmRpMewlBJkqtBizace-IXnIBrcswDu5JLWUPJKqhraumFqQA

**Related Issues:**
N/A

**Comment by RyanCavanaugh** [comment]
These are different types and have different behavior. A `Record<string, any>` matches anything, but `Record<string, unknown>` requires an index signature of any sort in the source type.

**Comment by jo32** [comment]
@RyanCavanaugh 

why Record<string, any>(aka {[k: string]: any}) matche anything while Record<string, unknown>(aka {[k: string]: unknown}) requires an index signature? 

However everything extends any or unknow.

I don't see the logic here and cannot infer other cases.

**Comment by RyanCavanaugh** [comment]
Normally the source type *must* have an index signature if the target type does, but for `: any` there's really nothing implied by this (every property must match `any`, by definition), so we made `[s: string]: any` a no-op for assignability reasons. This enabled some patterns that didn't work before:
```ts
function doSomething(obj: { [s: string]: any}) {
  // ...
}

const obj = { a: 1, b: 2 };
// WAS ERROR: 'obj' lacks index signature
doSomething(obj);
```

This creates some undesirable assignability in some cases, so we didn't apply this rule to `: unknown` so that you could pick which behavior you wanted.
