### ISSUE TITLE
Cannot use bigint with any in certain arithmetic expressions

### ISSUE THREAD

**Issue by abacabadabacaba** [microsoft/TypeScript#41741]
**TypeScript Version:**  4.2.0-dev.20201130

**Search Terms:** is:issue bigint

**Code**

```ts
var x: any, y: bigint
-x + y
++x + y
x++ + y
~x + y
x - x + y
x * x + y
```

**Expected behavior:**

The code should compile without errors, because `x` could be a `bigint`.

**Actual behavior:**

Each of the expressions fails to typecheck: `error TS2365: Operator '+' cannot be applied to types 'number' and 'bigint'.`.

**Playground Link:** [link](https://www.typescriptlang.org/play?strictNullChecks=false#code/G4QwTgBAHgXBIDsCeAaCS4CMCWBzbCALgFAC0UEA1OsZZRdUsVHVTQH4M0WnRtMUAVH0bEgA)

**Related Issues:** none.

**Comment by RyanCavanaugh** [comment]
This was intentional since, unlike other operands, operations like `80n + 1` throw rather than produce possibly-useful values.

**Comment by abacabadabacaba** [comment]
@RyanCavanaugh I disagree. Since `x` is `any`, it could be a `bigint`, in which case all of the expressions are perfectly valid. The problem is that if the type of `x` is `any`, the type of `-x`, `x - x`, etc. is deduced to be `number`, which is wrong because it could be `bigint`.

**Comment by abacabadabacaba** [comment]
Another example:
```ts
var x: any = 0n
var y = -x
```
Now, the type of `y` is `number`, but the value is `0n`, a `bigint`.

**Comment by prettydiff** [comment]
I am getting this error: `Operator '+' cannot be applied to types 'BigInt' and 'BigInt'`

TypeScript version 4.1.3.

I can understand throwing an error for applying arithmetic to mixed types since BigInt and number are not compatible, but this is a BigInt plus a BigInt.  For some background the operation is question is:

```typescript
details.size = details.size + size;
// details.size is defined as a BigInt
// size comes from "size" property of Node type BigIntStats
```

**Comment by fwienber** [comment]
> Another example:
> 
> ```ts
> var x: any = 0n
> var y = -x
> ```
> 
> Now, the type of `y` is `number`, but the value is `0n`, a `bigint`.

> This issue has been marked 'Working as Intended' ...

I can understand the design decision to not allow "potentially mixed computations", but this last example is clearly wrong typing, they can't be serious this is "working as intended". The original argument was to "throw rather than produce possibly-useful values" (@RyanCavanaugh), but this example shows that there are cases where the typing is too "optimistic".
It seems the unary `-` operator suffers the same problem as update expressions (`++`, `--`), see #49558. I could include your example in that issue as it seems to be a closely related problem.
