### ISSUE TITLE
In JS, checking `require.main === module` causes the type of `module` to get messed up

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/TypeScript#41764]
**TypeScript Version:**  4.1.2

**Search Terms:** require.main module

When using Node.js's [recommended approach](https://github.com/nodejs/node/blob/master/doc/api/deprecations.md#dep0144-moduleparent) to check if a module is the main module, tsc chokes on the types it infers:

**Code**
**Note:** This is JavaScript!
```js
if (require.main === module) { // ERROR TS2367 The types "Module | undefined" and "{ "\"c:/Repositories/ioBroker.test/repro\"": number; }" have no overlap
	module.exports = 1; // ERROR TS2339 The property exports does not exist on type `never`
}
```

**Expected behavior:**
no error

**Actual behavior:**
bunch of incorrect errors (see code). I'm not even sure what that type which is inferred for `module` is supposed to mean.

**Playground Link:** doesn't work on the playground

**Related Issues:** https://github.com/microsoft/TypeScript/issues/30088

**Comment by sandersn** [comment]
These two errors result from two independent features:

1. The type of `require` in `@types/node` is `Module | undefined`, whereas the `module` identifier has the object type of the exports of the module. In this case it's `{ [exports]: number }` because of the `module.exports = 1` assignment. These types do not, in fact, have any overlap.
2. When two variables with non-overlapping types get the error from (1), control flow narrows both variables to `never` since the compiler believes that the comparison can never happen. Note that JS' special assignment-declaration code still works to understand that the sole export of the module is `1`, even though `module` is narrowed to `never`. That's because it's a mostly syntactic check.

I think the right fix is to change the type of `module` to be closer to node's `Module` type, although I'm not sure how feasible that is.

**Comment by sandersn** [comment]
There's a clearly out-of-date comment in `getTypeOfVariableOrParameterOrProperty` that says:

```ts
            // CommonsJS require and module both have type any.
```

The code immediately below that instead creates an anonymous type with a single `exports` entry in its members. But it must not be creating it correctly because the resulting type doesn't behave as if it has a property named `exports`, but one named "/home/nathansa/src/test/test.js" (that is, whatever the filename is).

**Comment by sandersn** [comment]
The problem is that, even though the entry is named `exports`, the symbol is still the file symbol, so its name is (for example) `"~/src/test/test.js"`, not `exports`. Since the whole `module` type is faked anyway, I'm tried cloning the file's symbol and changing the name. It changes a whole lot of test baselines, but I think it's in a good way. I'm looking over them now and will send a PR if they look OK.
