### ISSUE TITLE
Incorrect output for #private with nested class in ESNext

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#41788]
Found from https://github.com/microsoft/TypeScript/issues/41773#issuecomment-737552030

```ts
// @target: esnext

class A {
    #str = 'pr Str'
    constructor() {
        new A.B(this)
    }
    private static B = class {
        constructor(private a: A) {
            console.log(this.a.#str)
        }
    }
}
test: {
    new A
}
```

Currently, this is emitted as

```js
"use strict";
class A {
    constructor() {
        this.#str = 'pr Str';
        new A.B(this);
    }
    #str;
}
A.B = class {
    constructor(a) {
        this.a = a;
        console.log(this.a.#str);
    }
};
test: {
    new A;
}
```

However, `#str` has been orphaned and this code will have errors.

CC @robpalme

**Comment by robpalme** [comment]
Thanks for highlighting this.  I played around and reduced it to [a slightly simpler case in the playground.](https://www.typescriptlang.org/play?target=99&ssl=10&ssc=9&pln=1&pc=1#code/FAYwNghgzlAECCsDexZtgYgB6wFywFcA7AEwFMAzASyLJIG5V0oAXCFqkWAIVgF5Y4aHBToxggPZFWAJwIgWEmQAoAlMibjxtAO4I1AOmyMtaAL6bYFi7oQHu9IA)

```ts
// @target: esnext

class A {
    #x : undefined;
    static B = class {
        constructor() {
            new A().#x;
        }
    }
}
```
...produces the following incorrect ESnext emit...
```ts
class A {
    #x;
}
A.B = class {
    constructor() {
        new A().#x;
    }
};
```
...whereas desired ESnext emit should retain the static field initialization inside the class...
```ts
class A {
    #x;
    static B = class {
        constructor() {
            new A().#x;
        }
    }
}
```

- The bug does **not** occur [when down-levelling](https://www.typescriptlang.org/play?target=7&ssl=9&ssc=2&pln=2&pc=1#code/FAYwNghgzlAECCsDexZtgYgB6wFywFcA7AEwFMAzASyLJIG5V0oAXCFqkWAIVgF5Y4aHBToxggPZFWAJwIgWEmQAoAlMibjxtAO4I1AOmyMtaAL6bYFi7oQHu9IA) because access to the private field happily goes via the module-scoped WeakMap.
- The bug does **not** occur [when enabling `useDefineForClassFields`](https://www.typescriptlang.org/play?useDefineForClassFields=true&target=99&ssl=9&ssc=2&pln=2&pc=1#code/FAYwNghgzlAECCsDexZtgYgB6wFywFcA7AEwFMAzASyLJIG5V0oAXCFqkWAIVgF5Y4aHBToxggPZFWAJwIgWEmQAoAlMibjxtAO4I1AOmyMtaAL6bYFi7oQHu9IA) because the static field initialization remains inside the class.

Making the static field assignment work without `useDefineForClassFields` might be possible if we sneakily export a getter.

```ts
class A {
    #x;
    static __bornToDie = t=>t.#x;
}
var __get_A_X = A.__bornToDie;
delete A.__bornToDie;
A.B = class {
    constructor() {
        __get_A_X(new A());
    }
};
```

But this feels like a lot of work for the matter at hand.  Maybe the simplest solution would be to make `target:ESnext` imply `useDefineForClassFields:true` to side-step the problem entirely.  Alternatively, an easy/quick solution to achieve correctness would be to degrade the `target:ESnext && useDefineForClassFields:false` case to use down-levelling.

Until this is fixed, users of `target:ESNext` can workaround this by enabling `useDefineForClassFields`

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser I suppose `static` methods/properties should be _transformed_ because the [`proposal is at Stage 3`](https://github.com/tc39/proposal-static-class-features/). Am I right?

**Comment by a-tarasyuk** [comment]
Why I asked this question, maybe it doesn't make sense, https://github.com/tc39/proposal-class-fields is at Stage 3 too, and TS emits _Private fields_ without polyfills. [Example](https://www.typescriptlang.org/play?target=99#code/FAYwNghgzlAECCsDexZtgYgB6wLywFcA7AEwFMAzASyLJIG5gBfYIA)

```ts
class A {
    #x = undefined;
}


// .js
"use strict";
class A {
    constructor() {
        this.#x = undefined;
    }
    #x;
}
```

However, TS downgrades [static _methods/properties_](https://github.com/tc39/proposal-static-class-features/). [Example](https://www.typescriptlang.org/play?target=99#code/MYGwhgzhAEBiD29oG8BQ0PQgFzNglsNAB7QC80AjANyoC+QA)

```ts
class Foo {
  static x = 1;
}

// .js
"use strict";
class Foo {
}
Foo.x = 1;

```

**Comment by sandersn** [comment]
I like @robpalme's idea of ESNext implying useDefineForClassFields; the emit is simpler and spec-standard class properties are widely enough supported that people overusing target:esnext [1] are unlikely to run into problems.

For the explicit combination of (1) target:esnext (2) useDefineForClassFields: *false* (3) nested static class with private reference, we should add an error that says "you can't do this, change useDefineForClassFields: true, or target an earlier version of ES."

[1] for example, somebody who just wants to use every feature in JS without the compiler doing any downlevelling, but who hasn't thought too much about which browser will.

**Comment by dragomirtitian** [comment]
@sandersn I would like to pick this up if that's ok. Just to clear on the statement of work:

1. If `target:esnext`,then `useDefineForClassFields: true` will now be the default.
2. If `target:esnext, useDefineForClassFields: true` we emit correct code so no further action is needed ([ex](https://www.typescriptlang.org/play?useDefineForClassFields=true&target=6#code/FAYwNghgzlAECCsDexZtgYgB6wFywFcA7AEwFMAzASyLJIG5V0oAXCFqkWAIVgF5Y4aHBToxggPZFWAJwIgWEmQAoAlMibjxtAO4I1AOmyMtaAL6bYFsa3adYAYX6wKxBVSlqNp2Lv2qjLBN0a3RgCz94A256IA))
3. If `target:esnext, useDefineForClassFields: false` and we encounter a usage of a `#private` field  in a static member we emit an error like "You can't do this, change useDefineForClassFields: true, or target an earlier version of ES."

**Comment by rbuckton** [comment]
I would strongly discourage using `delete`, as that is a performance cliff in V8 and other engines and implementers have strongly advised *not* to do this.

One approach I've seen is to leverage a computed property name, if possible:

```js
var B_1;
class A {
    #x;
    static [(B_1 = class {
        constructor() {
            new A().#x;
        }
    }, "B"]() {}
}
A.B = B_1;
```

This, of course, doesn't work if the class has no non-private members, in which case we might have to add an unused member, as you propose, but *don't* delete it.

```js
var <temp variables>;
class A {
  #x;
  // NOTE: __tsfieldinit__ would be an optimistic unique name
  // NOTE: __tsfieldinit__ is a placeholder. It won't actually be evaluated.
  static [(<inlined expressions>, "__tsfieldinit__")() {} 
}
<static assignments>
A.__tsfieldinit__ = void 0; // mark undefined, but otherwise leave as is. `delete` is terrible for performance...
```

**Comment by rbuckton** [comment]
> I like @robpalme's idea of ESNext implying useDefineForClassFields; the emit is simpler and spec-standard class properties are widely enough supported that people overusing target:esnext [1] are unlikely to run into problems.

The downside of this is that it could be considered silent breaking change (if you previously used `--target:esnext` on its own, your class field emit changes without notification, which can lead to subtle breaks). If we *were* going to make a change, I'd suggest that `--target esnext` should make you *explicitly* define your choice for `--useDefineForClassFields` if you use class fields in your code (assuming you haven't set `--noEmit`), at least for a few releases (or a future TS 5.x) to make people aware of the change.

**Comment by rbuckton** [comment]
We do have other cases where we downlevel things like destructuring to the ES5 form even when targeting ES2015, particularly in the module transforms, which is why `destructuring.ts` is separate from the `es2015.ts` transform. We could consider forcing the downlevel private field emit when we encounter the combination.
