### ISSUE TITLE
Unable to `import` JSX types, Error: "no interface JSX.IntrinsicElements exists", although it exists

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript#41813]
**TypeScript Version:**  4.1.2

**Search Terms:**

no interface JSX.IntrinsicElements exists

**Code**

This works:

```ts
namespace JSX {
    export interface IntrinsicElements {
        div: {[k: string]: any}
    }
}

const d = <div /> // <-- no error
type test = JSX.IntrinsicElements // <-- no error
```

[playground](https://www.typescriptlang.org/play?jsx=1#code/PTAEHUAkEkBkFFQBUYGUIHkBKBpVAaAKADsBDAWwFMBnAB1IGNLQApVADVAG9DQ-RKAD1oB7AE4AXUAEtiEymIBmjZtDljZ1aQ3gAbSlTnVuvfmYAm0gG4AubgG0A1neoSNxAOYBdO6WIBPAF9TPmDgwhBkNFAAEQx4dAA5DCRMXAA6CLBpclFJUAl-WmYuNnZA0EUxEXJQAHJqEV1pcwBaACtqOsJCBhFiV1BzUABeUAAeSytQYAA+GbBx1tbQYhEBMWqxHsLigpopMbL0tTdNbT0DSiMFieXV9YUtoA)

But this does not work:

```js
import type {JSX} from 'solid-js'

const d = <div /> // Error: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.

// But JSX is in scope, just that JSX expressions do not see it.
// As an example, the following non-JSX code works fine:
type test = JSX.IntrinsicElements // <-- no error
```

[playground](https://www.typescriptlang.org/play?jsx=1#code/PTAEHUAkEkBkFFQBUYGUIHkBKBpVAaAKBFADsBDAWwFMBnAB3IGNrQApVADVAG9ixQg0NQAe9APYAnAC6gAlqWnVJAM2atoiyQtpym8ADbUai2r35DLggCZyAbgC5eAbQDWT2tO2kA5gF0nclIATwBfC0twknCLFGh0ABEMeHQAOQwkTFwAOkI5SgkZUGlg+lYeDk5Q0BVJcUpQAHJacQM5awBaACtaRsJCJnFST1BrUABeUAAeWztQYAA+ebB4STrJJ0rhIxNZfPo2pjlpA2DQAAtyMxKypqDgxtAAI2omcgBXWlZScXlFZTULCalWymi8Oj0hmM1FMj1Eck8tFyFgAQu9ZFsEX9QLRBmV8KAup9ZNJLhiuMIxJI6LohmZrL8frIvqxjrkSABBMxBSlUA7UAmk1gqVoGcQAdwUPjIQw6W0G1lY4qkrjMKgU1AchBurCUI0mILB3l0+h2MOkZhIUw6HRlwjWUiAA)

**Expected behavior:**

It should see the definition of `JSX.IntrinsicElements` which is clearly present due to the `import` statement.

**Actual behavior:**

The JSX definition in the second example (`import`ed) appears to be invisible to TS.

As you can see from both examples, only a locally-defined `JSX` works, but not one that is `import`ed.

**Comment by trusktr** [comment]
If libraries could export non-global versions of JSX types, then projects could _very easily_ have a mix of files where each file may have a different type of JSX (f.e. React in some files, Preact in others, and Solid.js in others, assuming those libs export non-global JSX types).

**Comment by RyanCavanaugh** [comment]
```ts
namespace JSX {
    export interface Element {
//  ^^^^^^
        foo: number
    }
    export interface IntrinsicElements {
//  ^^^^^^
        div: HTMLDivElement
    }
}

const d = <div></div>
```

**Comment by weswigham** [comment]
> If libraries could export non-global versions of JSX types, then projects could very easily have a mix of files where each file may have a different type of JSX (f.e. React in some files, Preact in others, and Solid.js in others, assuming those libs export non-global JSX types).

They can. `preact` [does this](https://github.com/preactjs/preact/blob/master/src/index.d.ts#L7).

**Comment by trusktr** [comment]
Ahh, thanks! I never use `namespace`; I totally overlooked `export`.

**Comment by trusktr** [comment]
Turns out it actuall doesn't work when JSX is `import`ed, as any person organizing their code will want to do:

This does not work:

```tsx
// WHILE THIS WORKED
// namespace JSX {
//     export interface Element {
//         foo: number
//     }
//     export interface IntrinsicElements {
//         div: {foo: number, bar: string}
//     }
// }

// THIS DOES NOT
import type {JSX} from 'solid-js'

const d = <div foo={123} bar="string"></div> // JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
```

[playground](https://www.typescriptlang.org/play?jsx=1#code/PTAEBUAkEkGVQOoHkBKBpWAoEoB2BDAWwFMBnAB3wGNjQApWADVAG9sxRPRiAPcgewBOAF1ABLXMOKCAZtVoBRADbESk1uy5bOM-vwBceAK6EARtM1aAvpa68BI8ZOlyaoaJMETSYqstXEkqQaONpcACZiAG6GLLoGxmbSADSgpviChqTCXrgA5jahXIVgNppQcKAAIkgK8ABySOCIqGiYYoQOosIAnuS0LAyMVqAygvyEoADkpPxKYuEAtABWpFOYmFT8uNmg4aAAvKAAPJFRo3oHLACMAEwAzCPpggcARNm5ea8AfMfAZ99QDghtwVGpRB1yPMqGJhEoeqAABb4YK9frTfC4HpTNLEKj4IykWi4fhOKSyeTTIYAOg8OW8vn84LW3B4YmypGpGxwCEgAE0BYKhcKhUA)

**Comment by trusktr** [comment]
Please note, the `JSX` type from `solid-js` is in a `.d.ts` file, and in that case TypeScript apparently does not require `export` inside the `namespace JSX` definition. TS requires `export` inside the `namespace` when the file is a module (the inconsistency is confusing).

I also tried converting that file to a `.ts` file, and adding `export` for each type inside the JSX definition, but the error remains the same (the consumer code can not find the `JSX.IntrinsicElements` interface).

**Comment by weswigham** [comment]
You wanna use the `@jsx` pragma to change the factory function used from `React.createElement` to whatever the factory for your library is. The JSX factory is looked up relative to the factory specified. So if your factory is `h` (eg, via a `/* @jsx h */`) we look for `h.JSX`.

**Comment by trusktr** [comment]
Thing is, I don't want any jax pragma. I'm using `preserve`, and transpile JSX with a custom step.

But still, JSX types are in scope, and TS is not picking it up. I don't think there should be any difference between an inline declaration and an import with regards to visibility. JSX shouldn't have special treatment.

**Comment by trusktr** [comment]
We have an existing `import` syntax, and I think it is very intuitive for that to work.

There is a new `/* jsxImportSource ... */` syntax specifically for importing JSX types coupled with a factory. That is not intuitive: people don't assume to import all types with `import` except one special type (JSX) that requires comment syntax.

I think that

```ts
import {JSX} from `somewhere`
// or
import type {JSX} from `somewhere`
```

Should just work. I really feel there isn't a need to make JSX a hacky unique type when it comes to making it visible in a scope.

**Comment by weswigham** [comment]
You can still use the pragma with `preserve`, I believe - we need the name of the factory function to know under which non-global namespace to look for the JSX namespace.

**Comment by weswigham** [comment]
(Also, we didn't "invent" the comment pragma syntax - we just copied it from babel)

**Comment by trusktr** [comment]
`jsxImportSource` requires a `jsx-runtime.d.ts` file at the root of a package. This coupling of JSX types to a specific filesystem structure is not ideal at all.

We should be able to

- write `"jsx": "preserve"` in tsconfig.json (or specify a jsxFactory for compile output)
- `import type {JSX} from 'anywhere'` in any file (or import it from a file that makes it global, which already works), or specify `"jsxImportSource": "anywhere"` (without the implied `jsx-runtime` path) to have it auto-imported in all files.

and be done.

I can't think of a good reason to have this stuff coupled to specific files or coupled to React.

The "runtime" in `jsx-runtime` doesn't make any sense for libraries that want to use `jsx:preserve`, as there isn't even a runtime for TypeScript to care about.

After fixing `jsxImportSource` to not require some particular file path, it will make more sense because:

- if `jsx:preserve` is used along with `jsxImportSource`, then one can expect that it will import only type definitions (which apparently is not documented anywhere to begin with)
- if `jsx:react` or `jsxFactory` or similar are used, then the runtime can be expected to also be imported from `jsxImportSource`

But it would be best to simply allow `import {JSX}` (or `import {JSX, jsx}`, or `import {JSX, h}`, depending on tsconfig options) in any file, allowing users to use `import` instead of `jsxImportSource`, being more closely aligned with standards and conventions.

**Comment by trusktr** [comment]
TypeScript playground does not install dependencies for `jsxImportSource`. [playground example](https://www.typescriptlang.org/play?jsx=1#code/PTAEBUAkEkGVQOoHkBKBpWAoEoB2BDAWwFMBnAB3wGNjQApWADVAG9sxRPRiAPcgewBOAF1ABLXMOKCAZtVoBRADbESk1uy5bOM-vwBceAK6EARtM1aAvpa68BI8ZOlyaoaJMETSYqstXEkqQaONpcACZiAG6GLLoGxmbSADSgpviChqTCXrgA5jahXIVgNppQcKAAIkgK8ABySOCIqGip5lT4RqS04PBiwUYEpiqgwvzcfPw99EygMoL8hKCk-Epi4QC0AFbB42MAFrQMzPaCZD78uKSaYoQOosIAnuS0LCdW84vLAOSr61tdj9MOUYPAanVQI1msh0O1iJ1ur14OQlPgnnlFkNwqBwvwyHh+KJvMJ8EolLjiK9cOFAlQxASFktQLseNB7kJhLB+EZBDRUlclE8vsy7g8VqSpGphDdgAAqUAAAVZ7Ie3N5bn+Gx2wTlwBBVCu2VxoAAvKAADyRKLzPSmlgARgATABmT7pQSmgBE2VyeS9AD4LcBrQHQDgTtwVNLxPd1vThELQAd8HsXrQfvhcE8fmkEV0ZrgJhIpLJ5KAficAHQeHLeXz+aWkXO8AYyquaAB6oAAwjylDii6IZBIcYR+OEjKMtYDSMBWZtBENhHdiCCcAhIABNHe7vf7vdAA)

If we could instead rely on `import`, the playground example (which will install solid-js based on the `import`) would just work.

**Comment by trusktr** [comment]
Besides when [`@jsxImportSource` comments aren't working](https://github.com/microsoft/TypeScript/issues/41985) (I posted a reproduction there),

I realized that we have to import JSX _twice_ in order to use it in both normal code, and with JSX expressions.

So in order for the following code to work ([try it here live in your browser](https://gitpod.io/#https://github.com/trusktr/solid-jsx-typescript-parcel-starter), requires free Gitpod account, or see [the repository](https://github.com/trusktr/solid-jsx-typescript-parcel-starter)), we must import JSX in the same file using both syntaxes:

```ts
/* @jsxImportSource solid-js */ // first import of JSX
import { createState, onCleanup, Component, JSX } from "solid-js"; // second import of JSX
import { render } from "solid-js/web";

const App: Component = () => {
  const [state, setState] = createState({ count: 0 }),
    timer = setInterval(() => setState("count", (c) => c + 1), 1000);
  onCleanup(() => clearInterval(timer));

  // The @jsxImportSource comment is needed for this JSX expression to recognize the <div> intrinsic element.
  return <div>{state.count}</div>;
};

render(() => <App />, document.getElementById("app"));

// The `import {JSX} from "solid-js"` is  needed in order to use the JSX types in non-JSX expressions
interface Foo extends JSX.HTMLAttributes<HTMLDivElement> {}
```

I hope by now you may be convinced that `import {JSX}` for both cases is more intuitive, more DRY, and probably less likely to not work.

**Comment by trusktr** [comment]
@weswigham I updated the OP to make it clear based on the new findings regarding `import`.

**Comment by ryansolid** [comment]
I appreciate your consideration on this issue. At this point I'm fairly used to having most of the ecosystem assume JSX === VDOM factory function because Babel/TypeScript ship with a default JSX transform. But the spec for JSX makes no mention of what the output should be only indicates the syntax. I'm happy to have any solution at all. Even it is simply from the fact that React decided one day to have a new version that doesn't rely on a pragma import. The pre 4.1.1 solutions were horrendous, so I will happily follow predefined file paths for types if it accomplishes the goal. I understand since you did not invent the syntax for jsxImportSource you can't really change its function, but importing JSX working seems like it could be reasonable.

**Comment by weswigham** [comment]
We do two things to find JSX types:

1. Look for `<root identifier of JSX factory entity name>.JSX` - IMO, this is preferred, as it is local to a file, and customizable on a per-file, and per-JSX package basis. However, it is also newer (and was not in our original JSX implementation), so fewer packages/authors support it.
2. Look for a _global_ JSX namespace. This was our original implementation behavior, done as such because all JSX types are essentially compiler-intrinsic changing types that set global behaviors. We had no concept of file-local JSX behavior.

We have never looked for a locally scoped namespace named `JSX`, nor do I think we should further diversify what strange things you can do to typecheck JSX. We already have a mechanism for locally-sourced JSX definitions - if you can, I recommend using it.

**Comment by ryansolid** [comment]
Right, Global though is basically a mess. You can't have multiple JSX providers in the same project using Global they attack each other and it is completely broken. In those scenarios it is basically a non-starter. 

I strongly dislike the assumption JSX has a single factory function. It is very narrow view that isn't true. From Inferno's precompiled VDOM, Solid's custom DOM transformations.. It is not a coincidence these also happen to be the most performant JSX libraries. You will see more optimizations of this nature in the future for performance reason. I would expect similar from Vue at some point and I wouldn't count React out in the future.

There are plenty of things that JSX can generate and do. So `jsxImportSource` not being attached to a factory is a huge step forward to remove the last of the global JSX as it gets adopted. I'm fine with that generally but there are some obvious inconsistencies which @trusktr brings up. I'm not sure the best way though since the default would be to apply it across the project without any per file intervention. The challenge is that `jsxImportSource` only means something terms of the new Babel translation so coming from a clean slate perspective it's not obvious why. The next time Babel changes (like they just did) so will TypeScript.

So it could be beneficial to have a native TypeScript solution, but I do understand if the plan is just continue keeping this perspective and follow Babel's lead. Interestingly Babel itself does a pretty good job following the spec in terms of their syntax support, whereas TypeScript has historically tuned the implementation to match React.

**Comment by trusktr** [comment]
> I strongly dislike the assumption JSX has a single factory function

I agree. This discludes other forms of JSX that do not have factory functions (like @ryansolid's [Solid.js](https://github.com/ryansolid/solid) is quite amazing), and it means they would have to define a fake type for something that doesn't actually exist.

> The next time Babel changes (like they just did) so will TypeScript.

Disregarding that, I really don't see why we can't just have `jsx:preserve` along with `import {JSX} from 'anywhere'`, which would be intuitive and following standards that the ES community already has, and be on our way.

If `import` worked, I wouldn't have spent multiple days fiddling to try and get JSX segregation working.

@weswigham Have you used more than one form of JSX in a single project? It is a _real big pain_. 

I believe `import {JSX} from 'anywhere'` should at least be supported, regardless how the other stuff changes. It makes so much sense.

**Comment by trusktr** [comment]
The `@jsxImportSource` feature is also lacking.

- There is no hovering on it to see any intellisense tooltips.
- With `import` we can hover on the imported identifiers and see information.
- With `import` we can Go To Definition on imported identifiers or the module specifier.

It really makes much sense to support `import {JSX}`.

> nor do I think we should further diversify what strange things you can do to typecheck JSX.

You should honestly remove the strange things. But even if you keep them, `import` works in an obvious way, and it isn't strange, and people know what to expect.

The _very first_ thing I thought was: I'll just import `JSX`.

**It makes so much sense!**

**Comment by trusktr** [comment]
Note, Babel's new `jsx-runtime` feature (which also does not follow ES Module standards by virtue of requiring a particular import path) is specifically for libraries with runtime factory functions, and largely guided by React.

_This is unfair to the rest of the JSX ecosystem, and TypeScript is making the choice to support the unfairness (or, at least not providing easier options for other forms of JSX)._

**Comment by RyanCavanaugh** [comment]
@trusktr Can you please log a new concrete suggestion issue for supporting that? Piling on more comments to something that was filed as a bug is very confusing for us; if we want to have a real discussion on that point it's very awkward that we'd have to scroll down *n* comments to understand what the issue was really about.

**Comment by trusktr** [comment]
@RyanCavanaugh I think the OP describes the issue fairly clearly. I'm not sure what I can provide in a new issue.

**Comment by trusktr** [comment]
@weswigham @RyanCavanaugh Mind re-opening the issue? The OP describes the issue exactly, there is no need for a new one. But I can make a duplicate if you confirm that is what you want me to do.
