### ISSUE TITLE
"K extends never" doesn't give the expected type when K is never

### ISSUE THREAD

**Issue by ericmorand** [microsoft/TypeScript#41911]
While trying to write an utility type handling `never`, I stumbled upon an unexpected behavior.

Consider the following utility type:

```ts
type Sanitize<T> = T extends never ? "never" : "not never";

type CleanedTypeNever = Sanitize<never>; // never, should be "never"
type CleanedTypeString = Sanitize<string>; // "not never"
```

I expect `CleanedTypeNever` to be "never". But for some reason, it is `never`.

To confirm that `never` can be transformed by an utility type, I wrote the following test:

```ts
type ForcedNumber<T> = number;

type ForcedNumberNever = ForcedNumber<never>; // number
type ForcedNumberString = ForcedNumber<string>; // number
```

Which works perfectly, proving that it is possible to transform `never` to another type.

Is there a reason why this utility type is set to `never` when the transormed type is `never`?

```ts
type Sanitize<T> = T extends never ? "never" : "not never";
```

**Comment by ericmorand** [comment]
I tried to write the utility type the other way around and it still is `never` when `never` is passed as parameter:

```ts
type Sanitize2<T> = T extends string ? "string" : "not string";

type CleanedTypeNever2 = Sanitize2<never>; // never, should be "not string"
type CleanedTypeString2 = Sanitize2<string>; // "string"
```

**Comment by MartinJohns** [comment]
Please use the issue templates for [bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Bug_report.md) and [feature requests](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Feature_request.md). This will make it much easier for the TypeScript team and allows them focus on improving the language, instead of decyphering GitHub issues. :-)

---

You got hit by [Distributive Conditional Types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types). With `never` there's nothing to distribute over, so the result is `never`. The documentation provides an example on how to avoid this behavior.

**Comment by ericmorand** [comment]
Thanks a lot, using `type Sanitize<T> = [T] extends [never] ? "never" : "not never";` solves the issue.

Sorry for the unformatted issue. I'll use the provided templates from now on.
