### ISSUE TITLE
Symbol as index type fails in checkJs mode

### ISSUE THREAD

**Issue by Ethan-Arrowood** [microsoft/TypeScript#41996]
**TypeScript Version:**  4.1

**Search Terms:**
checkJs, ts(7053), symbol index type

**Code**

This block of code is valid in both TypeScript and JavaScript with no modification:

```ts
const symbols = {
  kFoo: Symbol('foo')
}

class Bar {
  constructor () {
    this[symbols.kFoo] = 'foo'
  }
}
```

When evaluated as a TypeScript file there are no errors. When evaluated as a JavaScript file it errors with: `Element implicitly has an 'any' type because expression of type 'symbol' can't be used to index type 'Bar'.ts(7053)`

I've tried some JSdoc things but nothing works.

**Expected behavior:**

checkJs can properly handle the code block (or there is a solution to annotate with JSDoc)

**Actual behavior:**

**Playground Link:** https://www.typescriptlang.org/play?target=2&jsx=0&module=1&useJavaScript=true#code/MYewdgzgLgBBCeBbARiANhGBeGBvAUDDANYBiIIAXDAMpKpoAUA5AGYXMCU+AvvvsDQBDCJgBCQgE55CMUJCiSArsCghpjTjKJEoACwCWEANoIU6CADoyFALrYYbDrL48gA

Note, this playground link is set to `useJavaScript` mode. Feel free to flip it to TypeScript to see the behavior described above

**Related Issues:** Some very old ones but nothing directly related as far as I can tell

**Comment by andrewbranch** [comment]
The fact that the [TypeScript equivalent](https://www.typescriptlang.org/play?target=2&jsx=0&module=1#code/MYewdgzgLgBBCeBbARiANhGBeGBvAUDDANYBiIIAXDAMpKpoAUA5AGYXMCU+AvvvsDQBDCJgBCQgE55CMANoIU6CADoyFALrYYbDgG5e+IA) also errors sheds some light on what’s going on:

```ts
const symbols = {
  kFoo: Symbol('foo')
}

class Bar {
  [symbols.kFoo] = 'foo';
// ^^^^^^^^^^^^ A computed property name in a class property declaration must refer to an expression whose type is a literal type or a 'unique symbol' type
}
```

`symbols.kFoo` is not a `unique symbol` because, from [the docs](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#unique-symbol):

> The new type is only allowed on `const` declarations and `readonly static` properties.

Since `kFoo` is an object property (and could therefore be mutated), its type can only be `symbol`, not `unique symbol`, which is what we need it to be for indexing. If we change `kFoo`’s declaration to be a const or a static readonly class property, it works:

```js
const kFoo = Symbol('foo')

class Bar {
  constructor () {
    this[kFoo] = 'foo'
  }
}
```

```js
class Symbols {
  /** @readonly */
  static kFoo = Symbol('foo')
}

class Bar {
  constructor () {
    this[Symbols.kFoo] = 'foo'
  }
}
```

**Comment by Ethan-Arrowood** [comment]
Ahh I see. In the project this was extracted from, all the symbols are defined in a file and are then exported in an object; which is what's causing this issue. Thank you for the links and explanation!
