### ISSUE TITLE
Globals can shadow locals

### ISSUE THREAD

**Issue by evmar** [microsoft/TypeScript#42114]
# Bug Report

### 🔎 Search Terms

global local shadow "declare global"

### 🕗 Version & Regression Information

Shows in old and current versions, so no regression.  I think this might be intended behavior.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about globals and shadowing

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAbwL4G4BQaD0m4EkC2AhgOYCWAdsHDABakDOcARgDYQDGA1nAz+XPQj4qAM0JQ4hAO6EAnnBGkWwADRwAJsEXkKxAUKoByALLAYhdYXOG+MYFDHtgAOjSb2LcVWJsmhFohocMG29o5UpuaW5oEhcXAAbvb0pBDkAFwCMFC66HFIaAVYOAByEFI8RGSUfNQ0VOwArlBQwOTwispqshCNGsAeXvrCoQ6ETpLk6nAy7dQQcEScwMU88D4QfiyuaBR2YxORFlaEsSEpAF7AmfTZuYUY7p6tcBtbZ8GgkLDUsmBUADElMAjtFTgBeOCgk7oIpPIbKeAgTJA5TQ8zoEDOS7AFDBbBwexQaBqVEgszHGL+UiEejARi0KgwCBgKEUsFAA)

### 💻 Code

```ts
export {};

// Imagine this block is in some far away file, defining some 'Metadata' interface.
declare global {
    interface Metadata {
        version: string;
    }
}

// Now imagine in the current file, you declare some interface and want to make
// it global.

interface Metadata {
    size: string;
}

declare global {
    // Attempt to export the local interface under a different name.
    export type FileMetadata = Metadata;
}

declare let x: FileMetadata;
x.size;  // error, FileMetadata aliases the top Metadata
```

### 🙁 Actual behavior

If you have a local with the same name as a global, you cannot put that local into the global scope, even under a different name.

### 🙂 Expected behavior

There is some way to reliably put a local into the global namespace, without other globals shadowing you.

**Comment by andrewbranch** [comment]
I guess the most foolproof way to do it would be to export the local from a module, then in the global augmentation, do `export type FileMetadata = import("./whatever").Metadata`. That would guarantee no other global could shadow you. Alternatively, I would probably just declare the new type in the global augmentation itself. I sort of agree this is weird, and maybe I’d design it differently from scratch now that globals can be explicitly referenced off the `globalThis` namespace, but it is intentional, and not worth the disruption of changing if we wanted to.
