### ISSUE TITLE
Inferring type from Record where keys are template literal types should return correct value type

### ISSUE THREAD

**Issue by minheq** [microsoft/TypeScript#42159]
# Bug Report

### 🔎 Search Terms

- record template literal types [infer]
- record template literal key 
- template literal types

Found https://github.com/microsoft/TypeScript/issues/29718 but not sure if it is the same error

### 🕗 Version & Regression Information

TypeScript v4.2.0-dev.20201230 

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.2.0-dev.20201230#code/PTAEBcE8AcFNQMIHsA2SBOoC8oDO50BLAOwHNQRQAVAC0N1AHcMBrXAKCjkVQ21AAGAY17oAJAG98RMgF8BnGPGRp0DHACVYI9ABMAPCowAaPARKkAfAG527EcXygRq3AC4er-hPag-oAHIXDAAhFABXWACPALDIgONff0oAZRokcJRdUGh0JABbaHBQWHQ89AB+JL8AkgA3AEMUQl1owK1WxNk7ShCAVQBxADpnUVASADNShnAkQXDiFiRGYgFxx3BYBuykCcFpCwEh+yQN0dV+UlhwAGlYSAA1JsiACmC1UyDROKiASjsJgshOBCKdQFdbvcnhFYPoklQSgAPTbEXQMLQ6AwHMimBYsYjLYiWRJ+G5IlFo0Ase67ajsSwvJAAIwAVh4qKZqZAPDdfuyANo3AC6oB8fnQ13C6GIoGZLP5XKFtm6QA

### 💻 Code

```ts
// type Color = string // This works
type Color = `color${string}`
type Colors = Record<Color, string>;

const colors: Colors = {
    'colorBlue': 'Blue',
    // BUG. should prompt error?
    'invalid': 'Red',
}

// BUG. color infers to `unkown` instead of `string`.
const color = getKeyValue(colors, 'colorBlue')

function getKeyValue<
  T extends Record<string, unknown>,
  K extends keyof T
>(obj: T, key: K): T[K] {
  return obj[key];
}
```

### 🙁 Actual behavior

- `getKeyValue(colors, 'colorBlue')` infers `unknown`
- `'invalid': 'Red',` is still valid key for `colors: Colors`

### 🙂 Expected behavior

- `getKeyValue(colors, 'colorBlue')` should infer `string` return value
- `'invalid': 'Red',` should prompt an error as it does not match template literal type

**Comment by andrewbranch** [comment]
The definition of `Record` is

```ts
type Record<K extends keyof any, T> = {
    [P in K]: T;
};
```

which is a mapped type that creates a property for every constituent of `K` if `K` is a literal type that can be used as a property name, or a union of those. E.g., `Record<'one' | 'two', string>` is equivalent to `{ one: string, two: string }`. If `K` can instead be used as an index signature, it will do that instead, e.g. `Record<number, string>` is equivalent to `{ [key: number]: string }`. Template literal types cannot be property names (since they can stand for an infinite number of property names), and currently, only `string` and `number` can be used as an index signature. So the mapped type can’t do anything and falls back to `{}`. (You can hover `Colors` in your playground and see this.)

This will be fixed if https://github.com/microsoft/TypeScript/pull/26797 is merged, because template literal types will be allowed as an index signature parameter.

**Comment by minheq** [comment]
@andrewbranch thanks for clear explanation! i hope the PR will eventually get merged :D

**Comment by andrewbranch** [comment]
Me too! 😄

**Comment by andrewbranch** [comment]
Haha no worries, I think it depends on whether or not the TS version is explicitly encoded into the URL
