### ISSUE TITLE
Assertion Error 

### ISSUE THREAD

**Issue by zsattari** [microsoft/TypeScript#42199]
```
  foundedModels.forEach(async(x)=> {
    let filter: IFilter = {};
    filter[name] = x._id;
    x[field] = await relatedSchemaFn({
        filter: filter,
        getObj,
    });
  });
```
In this code, when it reaches the await  line, it gives an assertion error
```
error: Uncaught (in promise) AssertionError
    throw new AssertionError(msg);
          ^
    at assert (asserts.ts:152:11)
    at WireProtocol.receive (protocol.ts:80:7)
````
**How DO I Do**

**Comment by ElhamAfshar** [comment]
```
list.map(async (x)=>{
      const u=await users.findOne({_id:x._id});
      return u;
    });
```

I also have this error
It gives me an error when I use array methods such as a `map` to fetch the database and it gives me Assertion Error.
So I have to use the `for` .

```
error: Uncaught (in promise) AssertionError
    throw new AssertionError(msg);
        
```

**Comment by MartinJohns** [comment]
This is not a TypeScript issue. You're mixing sync and async code in an incompatible way. You're not awaiting the promises. In both your cases you should utilize `Promise.all()`.

Questions like this are better suited for StackOverflow.

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.

It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
