### ISSUE TITLE
Unexpected behaviour reducing an array of unknown

### ISSUE THREAD

**Issue by dcampoy** [microsoft/TypeScript#42201]
# Bug Report

### 🔎 Search Terms

reduce, "unknown[]", list of unknown

### 🕗 Version & Regression Information

- This is the behaviour in every version I tried, and I reviewed all FAQ for entries related.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/dev/bug-workbench/?ts=4.1.3#code/PTAEHUEsBcAtQIYCckIJ6gPYDNQGdolIA7AczwBpQAVAZVAHdMkBrPRdgUwA8AHTgMbROAEwBQAzMQKIU6APLZahEqVABeUAG0Auh3wqyusWOSo0i5UTIA6JKICuAzgAoXCAQKoA3AJQaAPlAAbzFQcMRPDUiBUABqUABGAG4wiPtoByRiGLEAXyoABl8TEFAAIQdSCSkZMwVsAFViFmJMBhzNXX0HFraO41M5Cya+9uI7R2c3Dy9QP0CQtPDZ6NWElNAy8saAcQBCCCQpUgAbDAQ8PAcAW05QOARoB9h72duHU6fmUFhLl-ueAQdweaH4LwQOTg928CFODk4y1AGSyOVm+SKviAA)

### 💻 Code

```ts
// With array of strings, TS works as expected
const arrayOfString = [] as string[]

arrayOfString.reduce((acc, v) => {
    acc = acc + 1;
    return acc
}, 0)

// Bug
const arrayOfUnknown = [] as unknown[]

arrayOfUnknown.reduce((acc, v) => {
    acc = acc + 1; // BUG! Wrongly assumes that the accumulator has the same type as the value: "unknown"
    return acc
}, 0)
```

### 🙁 Actual behavior

The inferred type of acc is "unknown" instead of "number".

### 🙂 Expected behavior

To get the same inferred type when running on an array of string or an array of unknowns.

**Comment by RyanCavanaugh** [comment]
This is due to the ordering of the `reduce` overloads; this example "wants" to hit the third overload, but validly selects the second instead. It's not clear to me how we'd fix this without causing other breaks -- a homogeneous `reduce` call is clearly preferable, but creates a precision loss in this case. Maybe with negated types the second overload could specify `not T` as the `acc` value, but who knows what would break.

Please add to #36554 regardless.

**Comment by navanshu** [comment]
Isn't this wrong since, a single reduce can be used as a combination of filter and map when used together, the code runs faster,
and is easier to deal with and produces the result while using lower memory. I think so one should be able to have an accumulator of the choice one like. This kind of limits the usage of reduce function.

**Comment by RyanCavanaugh** [comment]
Inference is inference and has to make certain conservative assumptions. You can add a type argument to explicitly specify what you want to happen.

**Comment by navanshu** [comment]
Still the typescript compiler complaints and seeing such errors over the project is a bit triggering.
