### ISSUE TITLE
Visual Studio 2015: TypeScriptCompiler always generates empty concatenated target file

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/TypeScript#4225]
If I configure the TypeScript compiler in project settings (project type: "HTML application With TypeScript") to create a single concatenated target file, it always creates an empty file only. The resulting file never contains anything except "//# sourceMappingURL=SwingPanel.js.map" (see attached image).

![empty joined typescript file](https://cloud.githubusercontent.com/assets/9283914/9143653/dee49162-3d47-11e5-9971-fbd6e076c745.png)

**Comment by danquirk** [comment]
Are the files in your compilation actually putting anything into the global scope (these are what end up in the --out target file) or are they all external/ES6 modules?

See https://github.com/Microsoft/TypeScript/issues/1544

**Comment by SetTrend** [comment]
Yes, I think so.

In Visual Studio it doesn't seem like there is a filter on what input files the TypeScript compiler is using, so I assume it's taking them all. Given that case, main.ts should contain a gobal that's requiring all the others:

![typescriptempty](https://cloud.githubusercontent.com/assets/9283914/9155396/23aeca5e-3eb7-11e5-9766-3d863ef17ab3.png)


However, I'm trying to create a library, supposed to be deployed into a single file.

Is there any option to have the --out option concatenate all input files in correct sequence, disregarding an global objects requiring them?

**Comment by SetTrend** [comment]
I have now created a concise Visual Studio 2015 project demonstrating the issue. You may [find it here](https://dl.dropboxusercontent.com/u/77113703/TSCombinationTest.zip).

**This project should run flawlessly, but it doesn't.**

I'd like to add that I believe it would be very feasible to be able to set a source folder array to the "concatenate transpiled files into a single file" option so not all files in the project are getting concatenated into one single file but only a selection of them.

The preferred syntax is:
```javascript
[ "./TypeScript/*.ts": "./js/combined.js"   // glob either ends with wildcard or directory to search
, "./Lib/*.ts": "./js/Lib.js"   // syntax is: "source files": "concatenated into destination file"
, "./Test/TypeScript": "./Test/js/main.js"
]
```
All TypeScript files not found by this array shall be transpiled and written separately, either to the optional TSC destination folder or to the same folder of the TypeScript source file.

Here's a screenshot of the new sample project:

![typescriptcombinederror](https://cloud.githubusercontent.com/assets/9283914/9704220/39620224-549e-11e5-8e7b-6b33a7c804eb.png)

**Comment by danquirk** [comment]
This is working as intended. All your files are modules (formerly called external modules). main.ts uses an import statement, Base.ts and Derived.ts use export= statements. This means they each define their own module scope. The --out (and new --outFile) flag only concatenates globally scoped code into a single file, which you have none of, so you get an empty file. We have an issue tracking adding support for an error/warning if you use --out and get an empty file since it's likely a mistake. We don't currently support combining multiple external modules into a single file with a compiler flag but we have some work in progress on that front, like https://github.com/Microsoft/TypeScript/issues/4434
