### ISSUE TITLE
Inconsistent error for initialization of abstract property

### ISSUE THREAD

**Issue by ajafff** [microsoft/TypeScript#42287]
# Bug Report

### 🔎 Search Terms

abstract property initializer

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `abstract`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.0-dev.20210111#code/IYIwzgLgTsDGEAJYBthjAgwgg3gWACgFiFRIZ4EAHKAeyoQF4EBGAbkJKVoDtyBXeLSgAKAJS5OXEhAAWASzAA6GvSasOREgF9C2oA)

### 💻 Code

```ts
abstract class C {
    abstract prop = 1; // this is allowed
    constructor() {
        this.prop = 1; // this is not allowed
    }
}
```

### 🙁 Actual behavior

No error on the property initializer, but on the assignment in constructor. Though the initializer is not emitted.

Aside: what is an "abstract property" anyway? There's nothing the derived class can implement about that property in terms of actual executable code. It cannot even implement it as accessor, because that's no longer allowed since `useDefineForClassFields` was introduced.

### 🙂 Expected behavior

The initializer should be an error too, because the property declaration including its initializer is NOT emitted.

/cc @sandersn who seems to be responsible for all the things abstract and recently looked into this.

**Comment by sandersn** [comment]
A quick search of my usual corpora doesn't find any examples of  `abstract prop = 1`, so it seems that people haven't been foolish enough to do this in the real world.

I own abstract properties because of historical randomness -- I joined the team around the time when they were added -- and I have *never* been able to pay attention long enough to convince myself there's a good reason for them. Every time I try to follow an argument, my mind spirals through a reductio ad absurdum to a world without `class`.
