### ISSUE TITLE
tsconfig.json - extends property should handle more than one config paths

### ISSUE THREAD

**Issue by RamoFX** [microsoft/TypeScript#42386]
# Suggestion - tsconfig.json - extends more than one configs

## 🔍 Search Terms

- tsconfig multiple extends config
- TS5024: Compiler option 'extends' requires a value of type string
- tsconfig extends
- tsconfig extends multiple
- tsconfig extends string array

## ✅ Viability Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals]

## ⭐ Suggestion

A `tsconfig.json` have `compilerOptions`, `include`, `files` and `extends`, I'll be describing the `extends` feature suggestion.

It only takes a `string` type which is a path to the `tsconfig.json`, but it would be useful to take more paths.

So `extends` property should be able to process one or more paths.

## 📃 Motivating Example

Below I attached an example code image of what this can be helpful for. The image shown tree of 7 config parts in the left side and the code example on the right of `extends` them together.

![image](https://user-images.githubusercontent.com/24795597/104854398-c386cf80-5906-11eb-8a4b-a25ae4fda5d3.png)

### What do you want to use this for?
It will give a lot of possibilities.
For example, you will be able to make one configs directory and mixing them via `extends`  for best config and fast project configuration.

### What shortcomings exist with current approaches?
Inconvenience: you need to chain them one by one, which is of course not the best practice. If you will add another one and next ot it will be another 10 files then it takes some time to make it works again.

### What workarounds are you using in the meantime?
Chaining them (b extends a, c extends b, etc.).
Or you can even make some script that generates certain config from other parts.
Or maybe some package that includes all files into one.

**Comment by MartinJohns** [comment]
Related / duplicate: #29118. Used search terms: `extends tsconfig in:title`

**Comment by RamoFX** [comment]
Oh, you are right. Sorry for that.

**Comment by RamoFX** [comment]
But there is no response and the issue is closed.

**Comment by gurunars** [comment]
I would rather say that multiple inheritance is bad even in the context tsconfigs.

I personally tend to generate tsconfig files before performing typescript builds this allows me to create quite sophisticated pipelines. IMO, tsconfigs' syntax should be as blunt and featureless as possible and any extension and re-usability should be achieved at a meta level.

**Comment by MartinJohns** [comment]
Distantly related:

- #37884
- #40027
- #30400

**Comment by RamoFX** [comment]
> I would rather say that multiple inheritance is bad even in the context of tsconfigs.
> 
> I personally tend to generate tsconfig files before performing typescript builds. This allows me to create quite sophisticated pipelines. IMO, tsconfigs' syntax should be as blunt and featureless as possible and any extension and re-usability should be achieved at a meta level.

Hi! Thanks for your advice, I'll consider it in the future.

**Comment by RyanCavanaugh** [comment]
I've reopened #29118

**Comment by mutech** [comment]
> I would rather say that multiple inheritance is bad even in the context of tsconfigs.
> 
> I personally tend to generate tsconfig files before performing typescript builds. This allows me to create quite sophisticated pipelines. IMO, tsconfigs' syntax should be as blunt and featureless as possible and any extension and re-usability should be achieved at a meta level.

The same argument would hold for single inheritance. The proposition adds no features that you could not achieve with single inheritance, except for providing a better composability.

I agree that the additional complexity always adds a risk. However, the complexity of build pipelines is already suffocating and adding to that complexity is no less risky or painful. The solution for most developers who are not working on an industrial scale is typically Copy & Paste, painful comparisons of different tsconfigs, painful research in the docs to remember conflicting settings or their precise semantics.

To me, the current limitation looks like the complexity is already there, we just deny ourselves to benefit from its existence.

**Comment by mutech** [comment]
> I've reopened #29118

I think it's more interesting to follow this issue, since there are conflicting opinions here.

**Comment by mutech** [comment]
Oh I meant that your ticket is more interesting, if closing was a reaction on my comment ;-)

**Comment by RamoFX** [comment]
Sorry, I have little problem with understanding english. Maybe two duplicated issues make contributors think about this after several years.

**Comment by Zemnmez** [comment]
I agree that I rarely need this feature, however when I use any of the 'tsconfig' packages, e.g. https://www.npmjs.com/package/@tsconfig/node12, I often want to use both that and some base config that has my common rules in. Currently, the only way to use tsconfig packages is to maintain parity -- which is, to some extent just fine.

**Comment by johncmunson** [comment]
I would just like to post a concrete example I've come across where multiple inheritance could potentially be helpful.

I've been setting up a Typescript monorepo structure that looks something like this. Of course, there are other workspaces besides just `foo`, but this structure is enough to demonstrate the issue at hand.
```
my-project
|_ tsconfig.build.json
|_ tsconfig.json
|_ foo
  |_ tsconfig.build.json
  |_ tsconfig.json
  |_ src
    |_ index.ts
```

 Now, you may be wondering why there are two different versions of tsconfig, both at the root level and the workspace level. This is because I've been following the technique described in [this article](https://medium.com/@NiGhTTraX/how-to-set-up-a-typescript-monorepo-with-lerna-c6acda7d4559) for allowing better integration with tooling such as VSCode.
 
 The technique relies on utilizing path aliases while in development, but excluding them when running the build. For example, this is my current root level `tsconfig.json`...
```
{
  // The purpose of this file is to enable better integration
  // between our Typescript monorepo and IDEs and other tooling
  // that expects to find a file named tsconfig.json. The important
  // thing is the "paths" property below which sets path aliases.
  // So when the IDE sees an import starting with @marketing-milk/foo,
  // instead of resolving to the build output inside of node_modules,
  // it will instead resolve to the actual src of foo. This has a number
  // of advantages...
  //   - You can iterate on foo and dependent workspaces will
  //     immediately see the changes. No need to rebuild foo.
  //   - You can clone the project and everything will just
  //     work out of the box without needing to run the builds.
  //   - Go To Definiton will work as expected and take you to
  //     the correct location.
  "extends": "./tsconfig.build.json",
  "compilerOptions": {
    "paths": {
      "@marketing-milk/*": ["*/src"]
    },
    // Any tooling that reads from this file in realtime, such
    // as VSCode, should not be producing any output.
    "noEmit": true
  }
}
```

However, once you get to the workspace level and you setup the same `tsconfig.json` / `tsconfig.build.json` dichotomy, there is an ambiguity that is introduced. There has already been a precedent set that `tsconfig.json` should extend from the sibling `tsconfig.build.json`. But the `tsconfig.json` at the workspace level of course needs to somehow inherit the path aliases from the root level `tsconfig.json`.

For a `tsconfig.json` at the workspace level, it seems there are two conflicting needs, and you can only choose one.
- the need to inherit workspace level settings and overrides from `./foo/tsconfig.build.json`
- the need to inherit global path aliases from `./tsconfig.json`

So, naively one might think that being able to do something this is a great idea...
```
{ "extends": ["../tsconfig.json", "./tsconfig.build.json"] }
```

But then you have to decide _which order_ the array items should be, and there's not necessarily a correct answer there.

My personal opinion is that it would be awesome to have this feature, and people can use at their own risk. If this feature were introduced, it would be super beneficial to have some sort of CLI flag that allows you to print out the final resolved configuration. Because in a tsconfig that extends other ones, it's definitely not always clear what Typescript is deciding the final output should be.

**Comment by ts-web** [comment]
This feature is mentioned in the [5.0 release blog post](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#supporting-multiple-configuration-files-in-extends) though it's still not mentioned in the [tsconfig extends documentation](https://www.typescriptlang.org/tsconfig#extends)

**Comment by MarArMar** [comment]
So is this available in typescript 5 ?

**Comment by mrgrain** [comment]
This is implemented, but not yet documented here: https://www.typescriptlang.org/tsconfig/#extends
