### ISSUE TITLE
Allow type alias recursion when argument is shrinking structurally

### ISSUE THREAD

**Issue by bakhtiyarneyman** [microsoft/TypeScript#42393]
# Suggestion
## 🔍 Search Terms
circular reference 
recursive type

## ✅ Viability Checklist
My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Expand the cases when the type aliases are allowed to circularly reference themselves to support recursion when the argument of recursion is shrinking structurally.

## 📃 Motivating Example

I want to groom data that comes from a NoSQL database: check presence of fields and their types, replace malformed parts with defaults. Types can be nested, but are generally simple: only number, boolean, string, products, sums, arrays, maps are supported. 

I could write a grooming function for each data type, but that's a lot of work. I'd rather have a single generic function that takes in data structure that describes type `T` and its defaults, an `any` coming from the database, and produce a value of type `T`. Using types to emit runtime code is not a design goal of TypeScript, so let's go the other way around. Let's encode the type spec using values and use TypeScripts excellent type-level evaluation to generate TypeScript types:

```
export type TypeRec<T> = {
  -readonly [K in keyof T]: Type<T[K]>
}

export type Type<T> =
    T extends "boolean"
      ? boolean
  : T extends "number"
      ? number
  : T extends "string"
      ? string
  : T extends readonly ["tuple", infer U, infer V]
      ? [Type<U>, Type<V>]
  : T extends readonly ["union", infer U, infer V]
      // Doesn't work.
      // ? Type<U> | Type<V>
      ? never
  : T extends readonly ["apply", "Array", infer V]
      ? Array<Type<V>>
  : T extends {}
      ? TypeRec<T>
  : never

const FOO_SPEC = {
  "num": "number"
} as const 
const BAR_SPEC = {
  "strAndBool": ["tuple", "string", "boolean"],
  "foos": ["apply", "Array", FOO_SPEC]
} as const

export const Bar: TypeRec<typeof BAR_SPEC> = {
  strAndBool: ["abc", false],
  foos: [{ num: 42}]
}
```

This ungodly approach works except in the case of unions. Which is a shame, because from the conditional type it's obvious that there is no infinite recursion in this case because `T` is getting structurally "smaller" with each iteration.

**Comment by jcalz** [comment]
Could you provide a reproducible example of exactly what doesn't work "in the case of unions"?  I tried [this](https://www.typescriptlang.org/play?ts=4.1.3#code/KYDwDg9gTgLgBDAnmYcAqzgCVgGMA8aAfHALxwDeAsAFBxwC0UwAhgCYQB2ANonANoBpOAEtOcANbBEEAGboAugC50mQkIVFaAX1q1QkWAkyqUhEqVr00cUDGCc2AZzgAiAEYQI3Vp1dW4AH44T29fAJUbOwdnN04AVwBbd2AoVzgA4ITk1Ij0WxB7RxdXJxgoMQBzfzoguDKKzkq8qMKYl2Z2Ll4BVxh4sB9XABpRTllUuABVUbEJqDgANQVMgQwzKaJR9eB8RaIV2siCotjOjh4+fld4zhEuEbH56dnxyeXVnfxNuAAfU12+xaJ3acHO3SurhYYEGiEergAglAoCw4a9nh9asEkSjEIQ1PstEd8tFipRdFiATgCMQ8pxgAA3XI0Wi4LhlOAAMQA8tyAPoAZQACgBRADCZEoAVc2VcKhlSRSaR0cBYLjZnDKrPZ8AAQgisILRRLyNRaqVytyoLqvNw5b1bvc-KMLY1qi7Qj4WH4FMNpbIvE57ddobD4TjUY8efzheLDtpVeqdXoaAZoPANRzdSwoJFMNT8EgUHI4PrDbGxRYpbUGlabd4VABZFgwAAWADoUY4IIkABQASjg+DgAAZ2wBWOqudIqcrxYB+2oBiBOFT8ChwbIqAAsACY4Np47QgA) and it seems fine to me.  What am I missing?   

Furthermore I'm not sure what you mean by "shrinking structurally" or how it's obvious that there is no infinite recursion:

```ts
type OrElse = ["union", "string", OrElse];  
type UhOh = Type<OrElse>; // infinite recursion here, error
```
[Playground link](https://www.typescriptlang.org/play?ts=4.1.3#code/KYDwDg9gTgLgBDAnmYcAqzgCVgGMA8aAfHALxwDeAsAFBxwC0UwAhgCYQB2ANonANoBpOAEtOcANbBEEAGboAugC50mQkIVFaAX1q1QkWAkyqUhEqVr00cUDGCc2AZzgAiAEYQI3Vp1dW4AH44T29fAJUbOwdnN04AVwBbd2AofzoguATk1Ij0WxB7RxdXJxgoMQBzdPpgsorOSryowpiXZnYuXgFXGHiwH1cAGlFOWVS4AFURsXGoOAA1BQDg-gwzSaIR9eB8BaJljMiCotiOjh4+fld4zhEuYdG5qZmxiaWV013NuAAfL72WiO+WixTg5y6V1cLDAA0Qj1cAEEoFAWPDXs8PhlgsjUYhCGp9kD6MdQbEKLpsV8cARiHlOMAAG65Gi0XBcMpwABiAHkeQB9ADKAAUAKIAYTIlACrmyrhUsqSKTSOjgLBc7M4ZTZHPgACFEVghWLJeRqBlSuUeVA9V5uPKerd7n4RpaGtVXaEfCw-AohjLZF4nA7rjC4QjcWjHryBSKJYdtGqNbq9DQDNB4JrOXqWFBIpgafgkCg5HADUa4+KLNKMvVrbbvCoALIsGAACwAdKjHBBEgAKACUcHwcAADB2AKyZVyuOAqcrxYD+jKBiBOFT8ChZJIqAAsACY4NoE6ni6hraLuE5UORrk6Hq76lVHher8AFABuei0M9TNs8tspR2fBX2vIgvwAegg2wUWgABCVMgA)

But since the failure occurs for me inside the definition of `UhOh` and not inside the definition of `Type`, I'm brought back to my first question: what specifically doesn't work?

**Comment by bakhtiyarneyman** [comment]
My apologies, I fell victim to `vscode` using an older, 4.0 version of the compiler compared to what is in `tsconfig` :(. Apparently 4.1 supports this feature already.

Apparently it's not so obvious that there is no infinite recursion. :) What I meant is that the argument to `Type`, `T` is being decomposed into `["union", infer U, infer V]`, and those are being fed to `Type` again. If the argument to `Type` is finite, the result with also be finite. Your example illustrates exactly what may happen if the argument is not finite.
