### ISSUE TITLE
block scoped variables erroneously error on declaration order

### ISSUE THREAD

**Issue by sccolbert** [Microsoft/TypeScript#4244]
The following example does not compile, claiming the block-scoped variables are used before declaration, which is not true. The equivalent JavaScript version executes correctly.

```typescript
function foo() {
	a = 13;
	var c = b;
}

let a: number;
const b = 42;
```

[Playground Example](http://www.typescriptlang.org/Playground#src=function%20foo()%20%7B%0A%09a%20%3D%2013%3B%0A%09var%20c%20%3D%20b%3B%0A%7D%0A%0Alet%20a%3A%20number%3B%0Aconst%20b%20%3D%2042%3B)

**Comment by weswigham** [comment]
Background from [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let):
> In ECMAScript 6, let does not hoist the variable to the top of the block. If you reference a variable in a block before the let declaration for that variable is encountered, this results in a ReferenceError, because the variable is in a "temporal dead zone" from the start of the block until the declaration is processed.

and from the [spec](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-let-and-const-declarations).

The equivalent JS in question:
```
function foo() {
    a = 13;
    var c = b;
}

let a;
const b = 42;
```

Quite obviously this JS never actually executes `foo`, so any runtime binding errors aren't found by executing it as written (unless, say, by static analysis by the TS compiler). But, say we do run this JS and then call `foo()`, like so:
```js
function foo() {
    a = 13;
    var c = b;
}

let a;
const b = 42;
foo();
```
... it executes without error. Why is that? That is because the `let a;` declaration has been bound by the time we've called `foo()`. If you try this:
```js
function foo() {
    a = 13;
    var c = b;
}
foo();
let a;
const b = 42;
```
You'll get a `ReferenceError` because you've attempted to access `a` before it was declared. Since `let` declarations are dependent on having been executed before being accessed, you can construct situations such as this where it is possible to initialize the binding after the apparent usage and still have that usage be valid (whoa).

Perhaps more interestingly, this means I can do this:
```js
let a = 7;
(function() {
  foo();
  function foo() {
      console.log(a);
      return a;
  }
  let a = 2;
  foo();
})()
```
and the first call to `foo` results in a `ReferenceError` because the `let a` from the inner scope has already "blocked" `a` from being read until it is executed.

IMO, this is silly (I certainly see `let` as something that was supposed to make JS scoping more clear), but after reading over the spec one can see why it's the case.

So back to the issue at the top - is it correct for the TS compiler to error on the above? With just that snippet, nothing else involved? We can emit valid JS for that - for sure - but we would emit JS which it is _possible_ to incur the temporal let `ReferenceError` error - for example, if this chunk is emitted in the middle of a set of files that get concatenated and `foo` gets called before `let a` is executed (this is valid, since function declarations are hoisted!). In isolation the TS compiler can't know if `foo` will be called before or after the `let a` and only one of those is valid runtime behavior. It's certainly safer to error and let the programmer know that this is unsafe (I know I'd want to know).

Still, in isolation the above contains no syntactical errors and the usage of `let` and the inner function is technically valid, if potentially unsafe.

**Comment by sccolbert** [comment]
My particular use case which demonstrated this problem had to do with namespace-level variables. I like to structure my code with the exported "public" symbols at the top of the namespace, and the inaccessible "private" variables at the bottom. This allows a user/reader to immediately see what can be consumed from the public API without having to wade through a bunch of implementation details.

So, it was something like the following:

```typescript
namespace project {

export
class PublicClass {
	
	publicMethod(thing: any): void {  
		let data = extraData.get(this);
		// do stuff with data
	}

	private _id = globalID++;
}

let globalID = 0;
const extraData = new WeakMap();

}
```

**Comment by weswigham** [comment]
This is only safe because of the implementation details of TS `namespace`s - in effect, abusing the `namespace` system to guarantee safety. If your code wasn't automatically wrapped in an IIFE and executed in order by the TS emit it would be unsafe (but valid) JS. The sad truth is that when you abuse `let` in this manner if you had wanted to instantiate `PublicClass` and increment `globalID` in the static part of your namespace, there is the very real possibility of that being an error.

The perfectionist in me says this could go back to being a flaw in the ES6 spec for `let` and `const` - that block-level declarations can be captured by inner functions when the declaration has yet to be executed feels _wrong_ - and against the "intuitiveness" (I declare it and it's available in all the code _after_ it and never the code _before_ it) that `let` and `const` are supposed to bring. In effect, the binding of a function is exempt from the block declaration "temporal deadzone".

Anyways, TS could probably add static analysis to detect when it's safe to use `let` like this, since it is valid sometimes? I don't particularly like that it even _can_ be valid, myself, but that's generally what linters are for, I suppose.

**Comment by mhegazy** [comment]
As @weswigham explained earlier, there is not a way to know for sure if this is a runtime error or not. as it depends on execution order. We could do control flow analysis as well as alias analysis to identify cases where it would be safe to use the declaration. 

Alternatively we could relax the restriction of being "syntactically declared before used", but that means we are leaving more possible runtime errors unflagged.

**Comment by RyanCavanaugh** [comment]
I think we should error on the side of allowing anything that *might* work. It's a *temporal* dead zone, not a *lexical* dead zone, after all. The only case we should error on is where the use occurs in the same scope (i.e. not a function body) prior to the declaration.

**Comment by weswigham** [comment]
Aye. I personally don't like that it even _can_ work, but since it can by the JS spec it should probably be supported. But the question then becomes should we relax the requirements on `let` scope checking, or should we do that but also add the analysis @mhegazy mentioned to detect uses within the temporal deadzone?

**Comment by Arnavion** [comment]
@RyanCavanaugh By "same scope" do you mean lexical scope? So you won't error in this case:

```typescript
{
   a = 5;
}

let a;
```

because they're in different scopes, even though the assignment is obviously executed in the TDZ of `a` ?

If you do decide to complain in that case, then how will you differentiate it from this case:

```typescript
if (false) {
    a = 5;
}

let a;
```

where the assignment is not executed in the TDZ of `a` ?

I assume you'll not complain in either case.

**Comment by mhegazy** [comment]
As @RyanCavanaugh mentioned, it is only function bodies, not block scopes. so the two cases you reference are still errors, only something like `a` below would be allowed.

```ts
function foo () {
    a; // No Error
}
let a;

if (false) {
    b; // still an error
}
let b;
```

**Comment by sccolbert** [comment]
Another argument for loosening the checks (or tightening them, depending on perspective) is that this example compiles fine, when it clearly violates temporal dead zone semantics:

``` typescript
let f = Foo.foo;

namespace Foo {
	export const foo = 12;
}
```

**Comment by JsonFreeman** [comment]
Also, some people like to put all their functions declarations at the top, even if they reference entities declared later in the code. The strict policy makes it impossible to adhere to this style for those who prefer it. And I think it is a common enough preference.

**Comment by mhegazy** [comment]
This should be fixed now. errors are only reported within the same function if the use site is after the declaration, as it is guaranteed to fail, otherwise, no error is reported.

**Comment by sccolbert** [comment]
:+1: thanks!
