### ISSUE TITLE
Comparing numeric enum to number narrows variable to 'never'

### ISSUE THREAD

**Issue by ajafff** [microsoft/TypeScript#42442]
# Bug Report

### 🔎 Search Terms

enum, number, never

### 🕗 Version & Regression Information

- This changed between versions 3.8.3 and 3.9.7

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.0-dev.20210121#code/KYOwrgtgBAolDeAoKKoEMoF4oEYA0yqARllAEwEC+iiAJsAMYA2aATsFE8AC5QBuALlgBuRAEsAZlAAUfKAEJM2AAwBKBIRRyAZNhgA6NKMpA)

### 💻 Code

```ts
enum E {
    a = 1,
    b = 2,
}

declare let v: E;
if (v !== 0) {
    v &= E.a;
}
```

### 🙁 Actual behavior

`v` is narrowed to `never` inside the IfStatement. The compound assignment gives a compile error: `Type 'number' is not assignable to type 'never'.(2322)`

### 🙂 Expected behavior

`v` is still of type `E` and there's no error.

**Comment by ahejlsberg** [comment]
The issue here is the oddball rule we have (for backwards compatibility reasons) that values of type `number` are assignable to any enum literal type. This rule also extends to the comparable relationship, meaning that *any* value to type `number` is comparable to *any* enum literal type. Where this gets us into trouble is when we use comparability to filter types in control flow analysis. In this specific example, we filter the type of `v` by removing everything that isn't comparable to `0`--but because of the rule, every value in the enum is comparable to `0`, and thus we're left with `never`. Nonsense!

I think the solution is to remove the strange rule from the comparable relationship. That will cause the example to error on the `if` conditional with the diagnostic "This condition will always return 'true' since the types 'E' and '0' have no overlap." Which is the behavior we want (as it is indeed true).

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt
