### ISSUE TITLE
How infer parameter type?

### ISSUE THREAD

**Issue by junhwong** [microsoft/TypeScript#42470]
I want to implement a state management library similar to redux, and I have trouble defining types.
The prototype is as follows:
```ts

interface IModel<S, A> {
  state: S
  action: IActions<S, A>
}

type IActions<S, A> =  {
  [K in keyof A]: (state: S, payload: ???) => void // `???` How should it be defined here
}

class Model<T,A> implements IModel<T,A>{
  //...
}

// examples

const model=new Model({
  state:{name:"foo"},
  action:{
    setName:(state,name: string)=>{
      //...
    }
  }
})

//
let state={name:''}
model.action.setName(state,'bar') // ok
model.action.setName(state,123)   // error
```

Please forgive me for posting the question here!

**Comment by jcalz** [comment]
> Please forgive me for posting the question here!

You are forgiven. As penance, please close this issue and ask your question [on Stack Overflow](https://stackoverflow.com/questions/tagged/typescript) or another appropriate forum.  Go in peace. 🕊

**Comment by junhwong** [comment]
@jcalz  thank you for your reply and humor, but can I give you one 👎?
1. I have posted the same question on  [stackoverflow](https://stackoverflow.com/questions/65871538/how-to-infer-parameter-type-in-typescript)
2. The purpose of posting here is to be most of the ts experts here, and understand the description of the problem better, because I think this problem is more difficult. I have checked a lot of information and referenced other implementations but did not solve it.

The most important thing is to hope to get a solution

**Comment by jcalz** [comment]
Joking aside, I'm afraid that this is just not the place for such questions.  When opening an issue here, one is generally presented with a [list of choices](https://github.com/microsoft/TypeScript/issues/new/choose) like this:
<img src="https://user-images.githubusercontent.com/150626/105717879-40f1a780-5ee6-11eb-868b-4ab667162b4d.png" width="50%">

This issue is not a compiler bug report, nor a feature request.   It is a usage question, and does not belong here.  Continue trying on Stack Overflow or the TypeScript Community Discord, or some other place where such questions are actually welcome.  

Of course you would like a solution to your problem, but the TypeScript team's resources are limited and it is an imposition to expect them to address usage questions in a space dedicated to maintaining and improving the language itself.  The restriction is there for a reason; this venue would simply be overrun with usage questions otherwise.

So, not joking this time: please close this issue so that nobody from the team has to spend their time either closing it or labeling it as Question so they can filter it out.  

All is not lost, however: if you come to discover through your efforts in  or elsewhere, that what you are trying to do cannot be done in TypeScript, and if you think the use case is important, you should feel free to open a feature request for it by filling out the [appropriate template](https://github.com/microsoft/TypeScript/issues/new?assignees=&labels=&template=Feature_request.md&title=).  Good luck to you!

**Comment by junhwong** [comment]
@jcalz 
Of course I know that the team’s resources are limited, so I’m here and I’m sorry again. With the popularity and application of react hooks, this use case should also be a “just need”. At present, most of these libraries or frameworks are solved in other ways in disguise, such as: `{type:"action": payload:...}` or directly `any`. I think this approach brings great Bad experience (non-library provider).
The other purpose of my question is to be unsure whether the current grammar of TS supports this form, and it is not mature to send a proposal.
Of course, if the community thinks this `problem' should be closed, it will be closed after a few days if I try or give up, thanks.

**Comment by RyanCavanaugh** [comment]
We would be literally unable to function if everyone who wanted to post questions to StackOverflow also posted "bugs" here. The template instructions could not be clearer about this; please respect them even if it represents a challenge for you.
