### ISSUE TITLE
Constructor overloading issue

### ISSUE THREAD

**Issue by kamilbiela** [Microsoft/TypeScript#4254]
I have following error when using bluebird typescript definitions. 
```
error TS2345: Argument of type 'number' is not assignable to parameter of type 'Thenable<number>'.
  Property 'then' is missing in type 'Number'.
```

I have extracted definitions from file and here is the code to reproduce issue. 

definitions:
```
interface Thenable<R> {
    then<U>(onFulfilled: (value: R) => U|Thenable<U>, onRejected: (error: any) => Thenable<U>): Thenable<U>;
    then<U>(onFulfilled: (value: R) => U|Thenable<U>, onRejected?: (error: any) => U): Thenable<U>;
}

declare class Promise<R> implements Thenable<R> {
    /**
     * Create a new promise. The passed in function will receive functions `resolve` and `reject` as its arguments which can be called to seal the fate of the created promise.
     */
    constructor(callback: (resolve: (thenable: Thenable<R>) => void, reject: (error: any) => void) => void);
	constructor(callback: (resolve: (result: R) => void, reject: (error: any) => void) => void);
	
    then<U>(onFulfill: (value: R) => U|Thenable<U>, onReject: (error: any) => Thenable<U>, onProgress?: (note: any) => any): Promise<U>;
    then<U>(onFulfill: (value: R) => U|Thenable<U>, onReject?: (error: any) => U, onProgress?: (note: any) => any): Promise<U>;
}
```
code to trigger error:
```
var p = new Promise<number>(function(resolve, reject) {
	resolve(100);
});
```

interesting is that when You move second constructor definition before the first one, code starts to work ok, and no errors are shown.

link to playground: http://goo.gl/iwROXb

**Comment by RyanCavanaugh** [comment]
This is the correct behavior.

One fact we use when resolving overloads is that it's impossible, at runtime, to look at a function and know what kind of arguments it's expecting. In other words, it's not possible that `Promise`'s constructor can "tell" which constructor overload you were invoking, so it doesn't know whether it should be calling `callback` with the function that accepts `Thenable<R>` or with the function that accepts `R`.

Given no better information about the situation, we accept the first constructor signature because it's the first one that's acceptable.

The reality is that the constructor is going to invoke `callback` with a function that accepts *either* a `Thenable<R>` or an `R`. There is one overload, not two. So let's write it that way:

```ts
declare class Promise<R> implements Thenable<R> {
    /**
     * Create a new promise. The passed in function will receive functions `resolve` and `reject` as its arguments which can be called to seal the fate of the created promise.
     */
    constructor(callback: (resolve: (thenableOrResult: R|Thenable<R>) => void, reject: (error: any) => void) => void);

    then<U>(onFulfill: (value: R) => U|Thenable<U>, onReject: (error: any) => Thenable<U>, onProgress?: (note: any) => any): Promise<U>;
    then<U>(onFulfill: (value: R) => U|Thenable<U>, onReject?: (error: any) => U, onProgress?: (note: any) => any): Promise<U>;
}

// No errors
var p = new Promise<number>(function(resolve, reject) {
    resolve(100);
	
    let p = new Promise<number>(() => {}); 
    resolve(p);
});
```

**Comment by kamilbiela** [comment]
@RyanCavanaugh thank You for explanation! :)
