### ISSUE TITLE
ts will NOT generate a tsconfig.json file regardless of anything I try

### ISSUE THREAD

**Issue by Johnrobmiller** [microsoft/TypeScript#42562]
# Bug Report

IMPORTANT INFO: I tried installing ts after setting up a basic snowpack app using this tutorial: https://www.snowpack.dev/tutorials/react.

### 🕗 Version & Regression Information

sorry, I don't have time to run these tests.

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

I tried using these commands...
npm install typescript
npm install -g typescript
npm install typescript --save-dev

### 🙁 Actual behavior

node.js did not generate a tsconfig

### 🙂 Expected behavior

-

**Comment by AviVahl** [comment]
https://stackoverflow.com/questions/36916989/how-can-i-generate-a-tsconfig-json-file

**Comment by z0gSh1u** [comment]
tsconfig.json is generated using `tsc --init`

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
