### ISSUE TITLE
Symbol#getJsDocTags adds whitespace in URLs

### ISSUE THREAD

**Issue by RomainMuller** [microsoft/TypeScript#42581]
# Bug Report

### 🔎 Search Terms

`@see`, `JsDocTags`

### 🕗 Version & Regression Information

This changed between 3.9 and 4.1.

### 💻 Code

```ts
/** @see http://lmgtfy.com */
export class Foo {}
```

### 🙁 Actual behavior

Consider the exported symbol `Foo` above... When calling `getJsDocTags()` on that, the result includes:
```js
{ text: 'http ://lmgtfy.com', name: 'see' }
//           ^-- spurious space
```

### 🙂 Expected behavior

Expected the `@see` tag's text to be represented as-is:
```js
{ text: 'http://lmgtfy.com', name: 'see' }
```

**Comment by z0gSh1u** [comment]
This specified problem is introduced since https://github.com/microsoft/TypeScript/pull/39760. The parser of compiler always tries to `parseJSDocNameReference` although there might be none. So, for `http://lmgtfy.com`, it stucks at `:` since it's an `UNKNOWN` token for current grammar. Then, `http` becomes a `NameReference`, while `://lmgtfy.com` is comment. However, the whole string is all comment in fact.

https://github.com/microsoft/TypeScript/blob/fd6178b8260b1df40125242e00e59718e543fc79/src/compiler/parser.ts#L7757
https://github.com/microsoft/TypeScript/blob/fd6178b8260b1df40125242e00e59718e543fc79/src/compiler/parser.ts#L7226

Same problem occurs with `@implements` and maybe more JSDoc annotations for `typescript@4.1.3`.

**Comment by sandersn** [comment]
@z0gSh1u's analysis is correct. The comment-parsing part of jsdoc parsing skips initial whitespace, which isn't correct for jsdoc where whitespace is usually significant. getJsDocTags then separates the name of a tag from the comment with a space. Unfortunately, it's a fairly large change to fix this.

The output of `getJsDocTags` is now DisplayParts in 4.3, but it still inserts the space.
