### ISSUE TITLE
Undetected access to uninitialized variable

### ISSUE THREAD

**Issue by tuedeldude** [microsoft/TypeScript#42678]
### 🔎 Search Terms

* ReferenceError: can't access lexical declaration before initialization
* undetected access uninitialized variable
* used before assignment

### 🕗 Version & Regression Information

Reproducible in Playground with versions > 3.3.3333 including

* 4.1.3
* 4.2.0-dev20210206
* ...

*Not* reproducible with 3.3.3333

This changed between versions 3.3.3333 and 3.5.1

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.1.3#code/MYewdgzgLgBA2gKBsmBDANElAjTBdGAXhgAoSBKALnjAFcBbbAUwCd0Y7HWDCA+GAN5ZkAehEwAqmAAmTKE2DzpaYMCYQIMKCBi0wASwNR9qADb6AXk2UA3VCxPZTTYTFCQQzgHSmQAcxJUcgBuVxY5WhYweFcUGAAGTDi4xNc8UIBfcgpgoA)

### 💻 Code

```ts
const [
    a,
    b,
] = ((): [number, number] => {
    // Undetected access to uninitialized variable
    console.log(a);
    return [
        0,
        0,
    ];
})();
```

### 🙁 Actual behavior

Undetected access of uninitialized variable.  Crash at JavaScript runtime.

### 🙂 Expected behavior

Compile time error:  "Variable 'a' is used before being asigned."

**Comment by softwareCobbler** [comment]
binding elements appear to be "assumed initialized", would it be enough to just check if the use of the identifier is a descendant of the initializer? (inside `checkIdentifier`)

**Comment by RyanCavanaugh** [comment]
It's legal to reference `a` in that position *as long as the execution of the function doesn't happen immediately*, so it's not correct to just disallow any reference to `a` in its own initializer when that reference is inside a function expression.

The bug here is that the IIFE should be inlined for control flow analysis purposes, but that logic didn't work here for some reason.
