### ISSUE TITLE
How do I enable strict mode in TypeScript?

### ISSUE THREAD

**Issue by acterhd** [Microsoft/TypeScript#4270]
I can't found option in Visual Studio for enable strict mode when compiling typescript to JS. Without this option Ecmascript 6 code not working in chrome, because required strict mode. 
```
Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

**Comment by DanielRosenwasser** [comment]
Just add `"use strict"` to the top of your file.

**Comment by ClaudenirFreitas** [comment]
IIFE with 'use strict';
(function() {
'use strict';
...
})();

**Comment by dharness** [comment]
Doesn't it seem a tad obtuse to add "use strict"; to every file? Is there any way to enforce strict mode in every file?

**Comment by kitsonk** [comment]
All ESM modules will automatically be interpreted in strict mode, as per the standard.

If the code you are compiling is to CJS, AMD or UMD, TypeScript automatically emits the `'use strict';` prolog in order to maintain the run-time compatibility with ESM.

If it is a "plain" non-modular file, then TypeScript is like JavaScript, in that it is an opt-in feature.

**Comment by mattmccutchen** [comment]
If anyone else finds this thread in a search, the latest status is that a compiler option to enable strict mode is planned (#10758).
