### ISSUE TITLE
Can't negatively narrow by a numeric literal if another literal constituent has the same base primitive type

### ISSUE THREAD

**Issue by jeengbe** [microsoft/TypeScript#42876]
# Bug Report

### 🔎 Search Terms

- Typescript
- Explicit number check
_I am sorry, but I do not know what to search for_

### 🕗 Version & Regression Information

- ~This is a crash~
- ~This changed between versions ______ and _______~
- This is the behaviour in every version I tried, and I reviewed the FAQ for entries about _I honestly have no idea what to search for_
- ~I was unable to test this on prior versions because _______~

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210219#code/GYVwdgxgLglg9mABBAhgZwKYEEAUAoRRAWwE8B5AIwCsNoAuAwxAH0QG9GmmBrDEgRjqIADAG5OXRLxIAmIWBAAbReMmIAvhNYc1haYMQKiFDACdRugPSXEAOThQMQ-YjjBEUEgAcMiAORGJqZ+iAAWZhgSXNJyhiDGZqqSmlysCsp4AJRCAG5wMAAm7Iww7jiklDTQiAC8dXHKLKwV1LRQAHQudTUimcVcphhQIKZgSSmIikNSfDK1xOSt0J2zFtaIAKIAHj7QGEWePvLxQYzrhAB6TD2BZiwNiniaeHigkLAIyOgYAEL4hC0qlAGKl+rp9EIxFEeLNjsoklwJoRtNC9HwDPwLLouOt7I5nOjXO5Dr4-PwQuFBqiZrJjglzNCkfd0o9sog8oUwaVEOVFkDavUWU0FpU2isBAKesI+jomINhqNxowplAaXMeoCxTE1jZtrtHAdvE44vSzjZLtcTad1EA)

### 💻 Code

```ts
() => {
  declare const myObject:
  | {
      key1: 0;
      key2: null;
    }
  | {
      key1: 1;
      key2: number;
    }
  | null;

  if (myObject === null || myObject.key1 === 0) {
    return;
  }
  let key2 = myObject.key2; // Expected type: number
  //   ^   = number | null
}
```

### 🙁 Actual behaviour

In the above code sample, `key2` is of type `number | null`, although the explicit check for `myObject.key1 !== 0` should prevent this.

### 🙂 Expected behaviour

`key2` should solely be of type `number`.

### Notes
Feel free to suggest a better title and keywords, I am not really sure, what category this belongs to.

**Comment by ahejlsberg** [comment]
Your examples in the playground link work as expected. When the type of `key1` is `number` it could possibly have the value `0`, so a check for `0` doesn't exclude that variant. But when the type of `key1` is `1` it works as expected.

**Comment by jeengbe** [comment]
How does a check for `!== 0` not exclude type `number`? By exiting the function when `key1 === 0`, it is guaranteed that `key2` is not of type `null`. If `key1` were `0`, `key2` could be of type `number | null`, but since the check rules out the latter, only `number` is left. Nevertheless, it is still of type `number | null`.

**Comment by ahejlsberg** [comment]
> Nevertheless, it is still of type number | null.

Only if `key1` is declared as type `number` as in your first playground example. `number` includes `0`.

**Comment by jeengbe** [comment]
Consider [this example](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210219#code/GYVwdgxgLglg9mABAWwJ4DFzXmAFAKERVQHkAjAKwFNoAuQoxAH0QG8HHGBrK1ARlqIADAG4OnRD1QAmQWBAAbBWImIAvuJbtVRKQMTzkZKgCcVOqbIMgjp85w2cW8pfgCUggG5wYAEzYMMMC4aOTU0IgAhAC80dZKiABkicRhNFAAdHpRscJuAZyhlOnmGhpAA): How can `myObject` (in line 13) still be of type _see below_, although `key1` is explicitly checked for being non-`0`.
```typescript
(parameter) myObject: {
    key1: 0;
    key2: null;
} | {
    key1: number;
    key2: number;
}
```

Have I not understood `|` or am I missing something obvious here?

**Comment by RyanCavanaugh** [comment]
@ahejlsberg I think you misread the example? `key1` is a proper discriminant.

The issue here is that narrowing isn't functioning quite right for the illegally-positioned `declare const`. If you put this in a valid position or give it an `any` initializer, everything works as expected.

**Comment by RyanCavanaugh** [comment]
Okay it's *very* confusing to have the playground link and sample code be different; please don't do this.

**Comment by jeengbe** [comment]
> illegally-positioned declare const

I am sorry, I had that code in global scope and added the surrounding function directly on GitHub, I think my thought process was making clear, that it is encapsulated.

> Okay it's very confusing to have the playground link and sample code be different; please don't do this.

I, again, am sorry; I believe I came up with a better example whilst pasting it in the playground. Why do you require the code to be pasted twice, one here and once in the playground, though?

**Comment by RyanCavanaugh** [comment]
>  Why do you require the code to be pasted twice, one here and once in the playground, though?

Because Playground links have settings, so we're not left guessing whether the behavior describing is specific to some particular set of compiler options.

Also, before the advent of "include a Playground link", people would frequently just write ill-formed non-reproducing samples with syntax errors and expect us to figure out what they meant.

**Comment by ahejlsberg** [comment]
We'd need something like negated types to properly handle this scenario. We can reason about removing `0` from a _finite_ type like `0 | 1 | 2 | 3`, but we can't reason about removing `0` from an _infinite_ type like `number`. We may be able so special case certain scenarios, but a core design assumption in the discriminated union narrowing logic is that we can first construct a narrowed discriminant type and then from that construct a narrowed union of discriminated object types. And we fail on that first step because we can't subtract `0` from `number`.

**Comment by rdsedmundo** [comment]
@RyanCavanaugh @ahejlsberg I'm wondering if this problem is related, so I'm commenting here instead of creating a new issue for avoiding a duplicate.

```ts
type Test = { a: string; b?: undefined } | { a?: undefined; b: string };

const result = ({} as unknown) as Test;

if (result.a !== undefined) {
  console.log(result.a.slice());
} else {
  // works, result.b is string
  console.log(result.b.slice());
}

if (typeof result.a === 'string') {
  console.log(result.a.slice());
} else {
  // does not work, result.b is string | undefined
  console.log(result.b.slice());
}

```

[Playground link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKhDOwoF4oG8oEMBcVECcBLAOwHMBuKAIwH5cBXYgEwgDMSImoBfKAH3RY6URi3bFOlKrgIlSPcgChFAYwD2xRFHwJ6AGySoAFGl6Z4I4gGtiagO7EAlFgtxESxYVZQjO+PuAAOkwoAEJkVFE2DiZnNEUoKHVNNT0IQL01Ul9dA2DA+D1CFQgjR0clXgg9eGh4xIB6Bqg7NXwreAAabVygqihCC1kyBKSNeFT0zOy-AMCqAqKSsorFbmUvH1BINW9ZvJCI1AByYdJjuNHkibSMrJz-A8Xi0vLKqGra9FGmqCY1BBQWxIVrtbr7PoDIbAIhkfiWMQxK7jSZ3Ga9ebPZZvNaKIA).
