### ISSUE TITLE
async/await, optional-chaining and new scope transpiled to ES5: variable gets overwritten

### ISSUE THREAD

**Issue by Azlond** [microsoft/TypeScript#42879]
# Bug Report

### 🔎 Search Terms

async, await, scope, transpile, overwrite

### 🕗 Version & Regression Information

- 3.8.3 is what we currently use, but it's still present in 4.1.5 
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about it

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAE2AMwIYFcA28DGnUDOBcAggML5FwDeAUHA3KhYQQPIBGAVsDjAFxwASr2gIAPARhQAlgDsA5gBomcgJ4A+OAF4aAXwDcteo0Jq5OOFGAx0UOe268YABSgQAtjILAAFKhdUKFQPQQ4ICExgVDkdODRMHwBKGhNGRmtbe30jdL1jdLMLePQLGBkIOQAVAAtUGAAha1QAawJfFLp09JxKqVUSKGC1QUHh8RjNOIBtAF1c7oZeh3gYzh4+QRFeqAkpWUUVSa1dakM07uRoOF9l-tQANSCZVA4ouAhkAaHUNU6LxYMNZOPjTR7PV5RAB0MgQsziqAA7qgZPAYDVvFDMnYHOtnG5PN4-ODZJDgFCkGB0QB+GEIJILQGMXwdHRaLpMwF3SLkzAQBT+J6kt7ABkAwF6JIdRndfJ5Wj5IA)

### 🙁 Actual behavior

When using `tsc aFile.ts --target "ES5" --skipLibChec`, the following output is generated:
```ts
// ....
var _a, _b;
return __generator(this, function (_c) {
    switch (_c.label) {
        case 0:
            _a = anObject;
            _b = aVariable.id;
            return [4 /*yield*/, this_1.returnsObjectPromise((_a = aVariable.depth) === null || _a === void 0 ? void 0 : _a.id)];
        case 1:
            _a[_b] = _c.sent();
            (function () {
                console.log(aVariable);
            })();
            return [2 /*return*/];
    }
});
// ...
```
in case 0 `_a` is first assigned the `anObject`-variable. The optional-chaining-check overwrites it. Once the await is resolved, it is accessed again in case 1, which is now potentially null/undefined.
For this to happen, the aVariable-variable needs to be accessed in a new scope after the await.

### 🙂 Expected behavior

The variable should not get overwritten. The optional chaining check should be written into a new variable, e.g. _d.

**Comment by MartinJohns** [comment]
Sounds like a duplicate of #40897. Used search terms: `async optional chaining`

**Comment by Azlond** [comment]
Hm, might be - though in my case the new scope is explicitly required for it to break.
Transpiling the following does not result in the error:
```ts
// ...
for (const aVariable of anArray) {
    anObject[aVariable.id] = await this.returnsObjectPromise(aVariable.depth?.id);
    if (anObject[aVariable.id].someProperty) {
        console.log(aVariable);
    }
}
// ....
```

not sure if/how much this changes things.

**Comment by ExE-Boss** [comment]
That’s because in 

> ```ts
> // ...
> for (const aVariable of anArray) {
>     anObject[aVariable.id] = await this.returnsObjectPromise(aVariable.depth?.id);
>     if (anObject[aVariable.id].someProperty) {
>         console.log(aVariable);
>     }
> }
> // ....
> ```

The `aVariable` doesn’t get re‑assigned until the next loop iteration, which only happens after the inner `await`.

---

This however shows the issue with `var` hoisting:

```ts repro
// @showEmit
// @importHelpers
// @noEmitHelpers
// @target: ES5
declare interface AVariable {
	readonly id: string;
	readonly depth?: { readonly id: string };
}

declare interface AnObject {
	readonly someProperty: boolean;
}

declare interface API {
	returnsObjectPromise(this: this, id?: string): Promise<AnObject>;
	doStuffWithAnArray(
		this: this,
		anArray: readonly AVariable[],
		anObject: Record<string, AnObject>,
	): Promise<void>;
}

async function doStuffWithAnArray(
	this: API,
	anArray: readonly AVariable[],
	anObject: Record<string, AnObject>,
) {
	const aVariableGets: Array<() => AVariable> = [];

	for (const aVariable of anArray) {
		anObject[aVariable.id] = await this.returnsObjectPromise(aVariable.depth?.id);
		if (anObject[aVariable.id].someProperty) {
			aVariableGets.push(() => aVariable);
		}
	}

	for (const getAVariable of aVariableGets) {
		console.log(getAVariable());
	}
}
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?noEmitHelpers=true&importHelpers=true&target=1&module=1&noEmit=true&lib=%2C&ts=&ssl=1&ssc=1&pln=37&pc=1#code/PTAEAEGcAsHsHcCiBbAlgFwFAgq5AHWAJ3QAkBTAG33KMmzHADtYUMLrb6dx0BDIgHNy6AFyhEAZQCsmACbkAxpQHlQqJuloAzPorUBBAGoDUfAEaU1Ab0wBIIuT5zYTSgE91c8ZHRENggDc9o7Orh6gCvjo0AD84tagoS5unqjeoL7+TIKgAL7BeZjySiqO6po6eoZMAPLmAFZK6KC2Dk4pEZCwyOQACkSwNCTu4uawsFZ8TIXFCsqqFVpEuvqgBn0Akq0hIgCuREyQ9U2K6AM9qJDkABQxV+L3kAA0XvGZfgEAlOIXaNcAHgMdUazQAfME7C5JOg9tptAB1DDQYEGIhEPjuG72OxPR7QK7PHHTNEY0ZJDrhTzGUwWKwAbQAukS7HZpidmuIAEpKYhyAFZAKvYEcs5glk-UB-K7kAEAN1g6QhmCKmD4kHcTEUoG0ey16FQrkisBhcMRyNR6MxdwJkHEG02rxJVvJySp6xM-jp5CZTpBpzEoB5ij5As+OWF-vBXx2dhDRxafE9Zks5AA4iI7esXQCbjGALxgj201NF-OgJnBezaYigG7x3ygJMlqygWDaJtMUmYmNtNlRs705te1MAOnSjNA5b48D4GFAT1Hjlhh2OoLO0uuN2HKaso6iMVi47kX0hdlQHe3A-QQ+T3uPjNH3V6F2G6HcvZxbLvqYz6Ego74HsMA3HmU5Fju3qnjiRR2Kqdg1kQdYNi0wjoDSI6tu2TY-lYf6QJ+rINpM5CjpQsCCDcaEYbutxfNBcEqpgQA)

**Comment by Azlond** [comment]
This is no longer reproducible in newer versions.
