### ISSUE TITLE
template literal types starting with ${string} don't work when the string has more than 1 character

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#42903]
# ~~Bug Report~~ Suggestion

### 🔎 Search Terms
template literal types string

### 🕗 Version & Regression Information
4.3.0-dev.20210221

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about trmplate literal types

### ⏯ Playground Link
https://www.typescriptlang.org/play?ts=4.3.0-dev.20210221#code/MYewdgzgLgBAZiEAuGADAJAb2gJwJZgDmAvlmAK4C2ARgKY7GowC8MA5AIYCMATAMxsYAeiFgQMejhA4AsAChQkWNQ44UGbFHxFSmCjXqMW7BCF4DhQgCoBPAA612AIlPmngvBBhjYHCBDxCMA5qABtHKHEoe0c2DVwCEjIqOgZUNgA6IA

### 💻 Code

```ts
const foo: `${string}${number}` = 'a123' //no error
const bar: `${string}${number}` = 'foo123' //Type '"foo123"' is not assignable to type '`${string}${number}`'.
```

### 🙁 Actual behavior
```
Type '"foo123"' is not assignable to type '`${string}${number}`'
```

### 🙂 Expected behavior
no error

**Comment by ahejlsberg** [comment]
This is working as intended. The pattern matching we use in template literal type inference and assignability checking is (by design) pretty simple. From #40336:

> Type inference supports inferring from a string literal type to a template literal type. For inference to succeed the starting and ending literal character spans (if any) of the target must exactly match the starting and ending spans of the source. Inference proceeds by matching each placeholder to a substring in the source from left to right: A placeholder followed by a literal character span is matched by inferring zero or more characters from the source until the first occurrence of that literal character span in the source. ***A placeholder immediately followed by another placeholder is matched by inferring a single character from the source***.

For your example code to behave as you expected we'd have to scan ahead and find the point where the remainder of the string is a valid number. But valid numbers include things like `1e1`, `Nan`, `Infinity`, and so on. So, we simply don't attempt that and instead _always_ match exactly one character for a placeholder immediately followed by another placeholder.

**Comment by DetachHead** [comment]
i see. can this be changed to a feature suggestion instead of a bug then?
