### ISSUE TITLE
Extra long code compilation whitch finished with "memory leak" report after ~20min

### ISSUE THREAD

**Issue by mixalbl4-127** [microsoft/TypeScript#42937]
This issue started here: https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/569

## Current behavior

Make file: `Api.ts`

```typescript
/* eslint-disable */
/* tslint:disable */
import { HttpClient } from "./http-client";

export class Api<SecurityDataType = unknown> {
  constructor(private http: HttpClient<SecurityDataType>) {}

    abc1 = () => this.http.request();
    abc2 = () => this.http.request();
    abc3 = () => this.http.request();
}
```

and `http-client.ts`

```typescript
/* eslint-disable */
/* tslint:disable */

/** Overrided Promise type. Needs for additional typings of `.catch` callback */
type TPromise<ResolveType, RejectType = any> = Omit<Promise<ResolveType>, "then" | "catch"> & {
  then<TResult1 = ResolveType, TResult2 = never>(
    onfulfilled?: ((value: ResolveType) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: RejectType) => TResult2 | PromiseLike<TResult2>) | undefined | null,
  ): TPromise<TResult1 | TResult2, RejectType>;
  catch<TResult = never>(
    onrejected?: ((reason: RejectType) => TResult | PromiseLike<TResult>) | undefined | null,
  ): TPromise<ResolveType | TResult, RejectType>;
};

export interface HttpResponse<D extends unknown, E extends unknown = unknown> extends Response {
  data: D;
  error: E;
}

export class HttpClient<SecurityDataType = unknown> {
  public request = <T = any, E = any>(): TPromise<HttpResponse<T, E>> => {
    return '' as any;
  };
}
```

try to compile, you will see that "Issues checking in progress..." process take extra long time ~15 sec.
I dont know why, but if you Copy-Paste `http-client.ts` to `Api.ts` directly this check take <1 sec.

This files make this lib https://github.com/acacode/swagger-typescript-api with ~1000 `this.http.request`, and each `this.http.request()` took ~7 sec of checking. When I do this in `intel i7` CPU, **after ~30 min of compiling I got error about `memory leak`.**

**Video:** https://user-images.githubusercontent.com/3511307/108701953-4a842480-7511-11eb-9924-7f3c0c60acd0.mp4

## Environment
 - **fork-ts-checker-webpack-plugin**: 6.1.0
 - **typescript**: 3.9.9
 - **eslint**: 6.8.0
 - **webpack**: 4.46.0
 - **os**: Linux mint 18.3 KDE

**Tested on latest typescript 4.2.2** - same result.

Same with `tsc --watch --noEmit`.

**Video**: https://user-images.githubusercontent.com/3511307/108986783-2eac8a00-769b-11eb-9f9e-27f914830c8d.mp4

**Comment by sheetalkamat** [comment]
This is issue with declaration emit and repros if you run 
`tsc --d api.ts`

**Comment by weswigham** [comment]
My initial takes just looking at the example: `TPromise` being private means we have to print it back structurally when referenced outside that file. `TPromise` is rather large and complicated, so that probably doesn't help, since every member you're specifying is of a `TPromise` type. `export`ing it _probably_ gets the performance under control (I haven't validated this hypothesis yet, I just think it's likely).

**Comment by weswigham** [comment]
Yeah, my initial guess was spot on - `TPromise` not being exported means we have to print the type of `this.http.request()` structurally; except that structure is self-recursive, so we have to keep printing it until we hit our depth limit (5) and issue a truncation error (as you can see when declaration emit is on) - this takes a _long_ time, because in generating that truncated type we have to calculate (and recalculate, since, as I've mentioned elsewhere, there's no caching of any kind for symbol visibility) visibility for every type listed in the structure. For context, the (truncated) structural type of the expression doesn't even fit on one screen:
![image](https://user-images.githubusercontent.com/2932786/117213802-ef906880-adb0-11eb-8902-cbb0e995f140.png)
because the `TPromise` type expands so much. So yes, the quick fix for y'all is to export `TPromise`. https://github.com/microsoft/TypeScript/pull/30979 would be the ideal fix from us, I think, since then we could quickly and easily serialize the type without iterating to a depth limiter. In lieu of that, #43973 offers an improvement by way of adding a dumb cache into symbol visibility lookups, which is enough to bring the example runtime down from 20s to 7s on my machine. To bring it down more (which I do think would be possible), I think we'd need a smarter cache, or just more optimized symbol visibility lookup.
