### ISSUE TITLE
console.log still can output the private data

### ISSUE THREAD

**Issue by tonyload** [microsoft/TypeScript#42978]
console.log still can output the private data

**Comment by MartinJohns** [comment]
Please use the issue templates for [bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Bug_report.md) and [feature requests](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Feature_request.md). This will make it much easier for the TypeScript team and allows them focus on improving the language, instead of decyphering GitHub issues. :-)

---

If you're talking about `private` properties being logged, then this is the correct and wanted behavior.

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.

**Comment by NightshadeX9X** [comment]
Typescript compiles to JavaScript. Any TypeScript only features, such as private class members (although that's coming to JS soon), are only there during compile time, i.e. when you run "tsc" in your terminal. VSC is an IDE that can catch TS compile time features, and will underline even TS only errors with red. But these are not "actually" errors. They are only meant for developer experience and bug catching. I hope you understand what I mean. To summarize, TS is essentially a blanket you put on your JS code that restricts you doing certain things that typically lead to bugs. It restricts you by throwing compile time errors, but you can just choose to completely ignore these and you code will work anyway.
