### ISSUE TITLE
Possible to have a more type-safe `Map` type?

### ISSUE THREAD

**Issue by matthias-ccri** [microsoft/TypeScript#43101]
# lib Update Request

The `Map` type unions all of its keys and values, which is fine if all values are the same type. But in some libraries like LitElement, values can be distinct types. LitElement uses a `Map` to represent "the properties that changed" in its lifecycle methods (https://github.com/Polymer/lit-element/issues/1133). And properties can be any type. In this case, it would be awesome if we could define a `Map` type that infers precise value types based on the key.

I understand this will likely be a breaking change to the existing `Map<K, V>` type. It seems that passing an interface  would be the only way to convey more granular types, and avoid unions:

```ts
declare const m = Map<{k1: type1; k2: type2;}>;
const val1: type1 = m.get('k1')
```

So I'd like to get your input on this, whether the answer is "we have no plans to support this", or whether you'd allow a built-in utility type. Otherwise this type can be added to third-party type libraries like type-fest.

This issue also touches on best practices, so I'm wondering if you'd suggest to use a plain object instead of a Map, or a better way to achieve type safety in this case.

Thanks!

## Configuration Check

My compilation *target* is `ES2017` and my *lib* is `the default`.

## Missing / Incorrect Definition

`Map`

## Sample Code

[playground link](https://www.typescriptlang.org/play?target=7#code/MYewdgzgLgBAtgTwLIEMAOMC8MwFMDuMqaAPAOSIByArnGTAD4wUIDKUATmQDQzQcBLMAHNGOWgCNcHAHwAKANoAoGKpgKW7LrzIo9ZALrcVajVVo8YARgBMAZiNKDASgDcSpQHpPMAKIAPNFxgWDAQGGkOEA4IAC4lUEhYfli+TiFRbERiADphXCg5TU4yNwTwaHE4VLBJaSx4ZHQ8gqLzOjKvHwABKAgAWlxA4KhBjiiOGBQICAFhMAypqqlJqHCUNMERJWzmiFbi7Wt7Mu8YXoGhoJCxiamZuYWRJf5FtaXauBWdprQc-cKLBodB0ehQpXcHjOABEOCgAGawEDwl6ccDCAA2CH6UAQQQAJkR0EpcUEYFp0ViACp43D44gwEhUiL+KC4MD4iAwABKwWi+JIKDACF4QoQMhkWBMqmZQzZHK5vNAHAFQnh9QA0rgEBAAKoLcC8NX1ABqKAx1FweoNYElAH5pWpVABvR1Op35KCpEgalnyzkwLU6-UCcCSuQAa21qQ1ziwkqpCg1Bnc7rTfAK3t9cvZAaD1tDtpgkejgd4ADdzZbUonk3HMAnU+mAL6Omq4cvSJSQs5Uq1QRYCL1KfHBDEoDi4GCJSq7NA2VIUkTU2n09AkZ3tGp1DiuRpaVKvETNmQeGfJTgLzaLLK-GwtQGILQQ8pJKpXz4rBpz++etoIYEXy6PxhhCCJxmiOJ7lmeY3gACynfAomeUkrRyH5iHvAF-2fXhbDsMof3+A52ksXR9DKIA)

## Documentation Link

[Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map)

**Comment by RyanCavanaugh** [comment]
If you have a use case where `Map`'s behavior corresponds to some object type like this, I'd type-assert it to something like what you wrote. That seems like the right metaphor -- you have a more-specific "version" of a Map and are telling TS about it.

I don't think this belongs in the lib since it represents one member of an arbitrary large set of behaviors that one could imagine a `Map` having, and the particular use case to me is very much "Why aren't you using an object" (but I don't know about your use case enough to judge).

It seems like anything you'd do with a `Map` here would be better accomplished with a [proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy), but again I don't know why it's not an object to begin with so I'm only speculating.

**Comment by trusktr** [comment]
> "Why aren't you using an object"

Because `Map`s can have keys that are not `string | symbol | number`. This is not representable with Object types.
