### ISSUE TITLE
Cannot define a matching template literal type to a defined template literal 

### ISSUE THREAD

**Issue by EdwardDrapkin** [microsoft/TypeScript#43143]
# Bug Report

### 🔎 Search Terms

string, template, literal, type

### 🕗 Version & Regression Information

This is the behavior in every version I tried, including Nightly

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210308#code/GYVwdgxgLglg9mABAcwKZQMIEMBOATAFRigBtUAKWU1ALkQGcocYxkBKOgAylUYFoAJAG9GzVgF9OiIQChE8xDnQgcSbryiChVMpIDcM8UA)

### 💻 Code

```ts
function getCardTitle(title: string): `test-${string}` {
    return `test-${title}`;
}
```

### 🙁 Actual behavior

TS infers the type `string` for the returned string, instead of the templated type.

### 🙂 Expected behavior

No error!

**Comment by EdwardDrapkin** [comment]
It appears to happen in any case where there's a literal type, even the most trivial case fails:

```ts
const aString: `a${string}` = `a${'string'}`;
```

**Comment by RyanCavanaugh** [comment]
`as const` shouldn't be needed here

**Comment by ahejlsberg** [comment]
We currently only produce template literal types from template literal expressions in `as const` contexts. We tried template literal types for all template literal expressions in #41891, but reverted it because it was too breaky. However, a happy medium would be to give template literal types to expressions that are contextually typed by string-like types. I can't imagine that breaking anything and it would solve this and other related issues.
