### ISSUE TITLE
Syntax error in emitted output from `tsc` when exporting value of symbol key

### ISSUE THREAD

**Issue by laverdet** [microsoft/TypeScript#43154]
# Bug Report

### 🔎 Search Terms
syntax error tsc declaration class symbol  TS1003 Identifier expected

### 🕗 Version & Regression Information
Every version from 3.3.3 - 4.2.3 and nightly

- This is a crash

### ⏯ Playground Link
https://www.typescriptlang.org/play?ts=4.3.0-dev.20210308#code/MYewdgzgLgBAyjAvPAngWwEYgDYAoCUA3AFDDYCGEEMAYiCDAN7EyszTlQCWwMA2nAC6BRgF9i4gKYAPAA4gATrFCRYaSVAAWIACZJa9AYMJA

### 💻 Code
```ts
const S = Symbol();
class Foo {
    static [S](){}
}
export const method = Foo[S];
```

### 🙁 Actual behavior
Output of the `d.ts` follows:
```ts
declare const S: unique symbol;
declare class Foo {
    static [S](): void;
}
export declare const method: typeof Foo.[S];
export {};
```

There is a syntax error on line 5: `typeof Foo.[S]`

### 🙂 Expected behavior
A dot should not be emitted when the key is a symbol

**Comment by a-tarasyuk** [comment]
I suppose the result for `method` should be like so

```ts
declare const foo: () => void;
```

because the following result throws the error  

```shell
'S' refers to a value, but is being used as a type here. Did you mean 'typeof S'?
```

```ts
export declare const method: typeof Foo[S];
```

@RyanCavanaugh What do you think?


/cc @weswigham

**Comment by laverdet** [comment]
@a-tarasyuk thanks for taking a look at this. I noticed another issue with the emitter that will cause a syntax error:
```ts
const S = '#foo' as const;
class Foo {
    static [S](){}
}
export const method = Foo[S];
```

This emits: `export declare const method: typeof Foo.#foo;` which of course needs to be quoted.

**Comment by vimark1** [comment]
This is still an issue in main (4903c64ad2)

**Comment by csutorasr** [comment]
I tried to resolve the issue. I could remove the useless dot, but it wasn't enough, as the generated declaration should look like this:

```
declare const S: unique symbol;
declare class Foo {
    static [S](): void;
}
export declare const method: typeof Foo[tyepof S];
export {};
```


@RyanCavanaugh 
I managed to create the test for it. 

I changed this function in the emitter:

```typescript
        function emitQualifiedName(node: QualifiedName) {
            emitEntityName(node.left);
            if (!getTextOfNode(node.right, /*includeTrivia*/ false).startsWith("[")) {
                writePunctuation(".");
            }
            emit(node.right);
        }
```

I know this is a bad solution but this would be my first MR, and I was just trying to make some changes.

I think I should check in `emitQualifiedName` if the Identifier in the right node is a symbol. If it is, then use `writePunctuation` to add the brackets(`[`,`]`) and emit the node.right between the two instead of writing a `.`. I should also change the emitter for the node.right to write only `S` instead of `[S]` if it is a symbol. I don't know if the second part should be done at parse time, check time or during emitting.

The issue doesn't cover the adding of `[typeof S]` instead of `[S]`.

Please help me to make the decisions in the followings:

* Is my first suggest OK?
* Where should I change the second part? (Text for `node.right`)
