### ISSUE TITLE
No-op distributive conditional type in union causes strange type inference

### ISSUE THREAD

**Issue by ada-waffles** [microsoft/TypeScript#43168]
# Bug Report

### 🔎 Search Terms

interface extends subtype conditional inference union

(This issue doesn't occur with named interfaces until they're extended, so I initially searched thinking this was an inheritance issue)

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about conditional types and inference

### ⏯ Playground Link

[Playground link with below code sample](https://www.typescriptlang.org/play?ts=4.2.3#code/C4TwDgpgBAggznCAnYAeAKgGigVShAD2AgDsATOKdAPigF5cBuAKFEigEkSA3AQyQCWvEmhr0oACgIAuKgEp6tdC2YB6VVQAWAyjqi8oZHcEEAjAK7AB3aAGMA9uQFXHvADZQ2ERlAEAzKBB7c3w4W152ZygAd2dNKABtAF04bCjo+yQAa0peSkJIW2IyADpWcGgABURzMnsOMlIrUAxaBnR8IlIKfRIQKAB+KihZZXL2dAg4NBhsACE2xNmoOewYKAAfFaTO4nJKBIESP2QoAA0049OATUuTpHPNqGqIWvrGkWcQVCP7qGvqDshgkLv8drISBAbEgVOpEgAiGDw7CI+FPeFzeFJcbQM7iSbTVColGY6jMHFUKbAeCIFACRyoZYLcQ05BoLh8QTCNAJJlJajYDn8IQiDBUxnzahSnzqACiSCQmWYQA)

### 💻 Code

```ts
type Assert<T, U extends T> = U;
type Invariant<T> = (x: T) => T;

// This is a distributive conditional type; if you escape it with []s, it works as expected.
type PseudoIdentity<T> = T extends T ? T : T;
type Test<A, B> = [A, B, A | B] extends [infer X, infer Y, infer X | PseudoIdentity<infer Y>] ? [X, Y] : never;

// ["A", "A" | "B"]
type X = Test<"A", "B">

type TestAssertion<A, B> = Assert<Invariant<[A, B]>, Invariant<Test<A, B>>>; //Error
```

### 🙁 Actual behavior

Type `X` resolves to `["A", "A" | "B"]`

### 🙂 Expected behavior

Type `X` should resolve to `["A", "B"]`, as the first two tuple members should make the type inference trivial.
(Also, I'd generally expect a conditional type with the same thing on both branches to be a no-op)

An extra bit of strangeness is that changing `T extends T` to `T extends any` moves the union to `X` instead of `Y`, except on 3.3.3 and 3.5.1.

**Comment by RyanCavanaugh** [comment]
I don't understand why that's expected. You have multiple inference locations with the same priority for `X`, so TS is going to take all of them into consideration.

**Comment by tjjfvi** [comment]
- With `PseudoIdentity<T>` being `T extends T ? T : T`, `Test<A, B>` is `[A, A | B]`. 
- If you change `PseudoIdentity<T>` to be `T`, `Test<A, B>` is `[A, B]` (as expected).
- If you change `PseudoIdentity<T>` to be `T extends unknown ? T : never`, it becomes `["A" | "B", "B"]`.

Afaict, all of those definitions should behave equivalently to the bare `T` case.

**Comment by duke9509** [comment]
This was my original reproduction, before I got some help reducing it further: [Playground link](https://www.typescriptlang.org/play?ts=4.2.3#code/PTDiEsDcFMDsAIAuALa8BG0A2B7A7vOLItAE4BmAhgMZoCyAngCoMAOalsAJvNcuFh5ESFGmgCiADxLcAzoxbsANACgQeVAhRo+AocTJVahWYVizEnROEokeecCiR4c8AFTUcAW1ZZoJLAZ4AFdYcABHYOg3JDY0VkpSSi9-MllVECJyMlIiAHMkZBxZeMTk1NJTdBoAa3gcYMR4SBtCtGqS2PZ4UmhZYKxEUyJ4SngLJNg8tFDwHAQR7XHoT254VmLHOdgALhVEOPgmPqaAXngpGS55ZjiAHgAiAEEGBgeleAeAIWhoB4A+eDQaRwa7wBT3LJkeBPD5Q0jwL6AgD88AA2rDEQBdeA7eCwaAwUgAbngIDRz1e70+Lze8AAPp8fn8sSpVhYMKQcDU4HiKbTqd9fg8cedYAMsABCUamY4ckDiUhc0gqNTAOiUGr5QrgUxjA7dShYGymLyavr41xccDkbK9WC0FTCQxicG3dh3TFI+AAbxU8ADozxT2J-sD6DxX1DYYDIAAwshOHltQADHDoABWK0QKaQrhTnAYuZwCJToRqsHwsFzsm80CKBAA+l4cDBTEscvNoA1TLN5nm2vAAPJMAAS4gASl1SkkUiJGwA6GNk4AJpPaxwD6iUViOI0AWiH8BTQ8z2dzXBwFsrKHyS8DK4n0BbLSmg9W1us8yN09Ggxw0zaAigGmLkPA4OQg6sFy6B+F496BiAAAKjTWG+1q2mQcBNLeUymP2SzoJMfAWhB77zJ+2w-pQmHUEMg7wr0PAGhaIwYXa2HjIgkzTPAeCUAwsgIbGwAAJIAOReCEsipl8uKIrmmDbsEnSOOJ7aoPALYcg8XhEOAZpYA88DkCWnx6WEhk9NA0E4FwwR0dsxmcEITS4NypjGjyhBNLIRQDDwmCjJa+44KwwkhGE8zBgy8AABRycCVz4WedHwKicmRgAlKGAC+qogBqWpvreeq-kaJomeAkgWkstmwc+8AAKoAHIADLiAAyp18AMA00loCmABkvoLmNuW5ogriUFwPDGiIRqBKMsBBDgQFac+mCVGqcbeL4qRLb0L7aqV5VrBmKlNCpqYQh6lJvB8Qp-ICI0+qZOB4oWE2jOgrbxL0JSkG2g6dgiU04EuzqiMYlygjcijQJ6HzeklcNugjSOIoCPr5WqTCaUQ1otPZP62ewpDWBaiRoCxPCeEq2aBCoXArFg1O8PMHIkBYeKw3It2I-dgrMgCobc4gC6UKSIBC-sJwLug0vAE9DxyxYC59rAStC7FKsqEAA)

This arose from a problem I was having with mobx-state-tree. Array types are a sub-interface of `IType`, and the subtype causes an unexpected result when the array type is inferred as an `IType` because of this behavior.

**Comment by RyanCavanaugh** [comment]
Each of those forms creates different inference priorities, so it's expected that they'd behave differently.

Using `T<infer X>` in a way where `infer X` becomes manifested in the test position of a conditional type is very confusing - I'm honestly not sure what that's supposed to mean. Even writing something like `infer Q | infer W` is not creating well-defined semantics.

The same problems apply to a structural inference in the second example from `ExtendsMyType` -> `MyType`. There's no obvious algorithm here to line these up "correctly" and TS has chosen a sound but insufficiently precise candidate as a result. You just need to provide more help here for the compiler to figure out what your intent was. I would probably write this as
```ts
type Test = ExtendsMyType<"Ayy", "Bee"> extends Omit<MyType<infer A, infer B>, "union"> ? [A, B] : never; //["Ayy", "Ayy" | "Bee"]
```
or
```ts
type Test = ExtendsMyType<"Ayy", "Bee"> extends Pick<MyType<infer A, infer B>, "a" | "b"> ? [A, B] : never; //["Ayy", "Ayy" | "Bee"]
```
which both behave as expected.
