### ISSUE TITLE
Record is inlined in declaration emit after 4.2

### ISSUE THREAD

**Issue by dragomirtitian** [microsoft/TypeScript#43209]
# Bug Report
### 🕗 Version & Regression Information

- This changed between versions 4.1 and 4.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/dev/bug-workbench/?ts=4.2.3#code/PTAEAEBMFMGMBsCGAnRAXAlgewHYCg8QIAzDeaHRAW2gC5QA6YRBtAZzzQE8AHaUAEpxQAXkFwsySAB42aZBhwBzADSgAjAD4A3AWgAPHpLSgYxRAFd4JgN55QD0D2RYe9GwF9QiNuNh4PAgIicFJyShp6JkUYfVYODCojZBNEUGIXKlAAIiZEbN08A2STM0trbwZnV20gA)

### 💻 Code

```ts
// @filename: ./a.ts
type Rec = Record<string, 1>;

export default {
    prop: {} as Rec
}

// @filename: ./index.ts
import a from "./a";

export default a.prop;
```

### 🙁 Actual behavior

In generated declarations for `index.d.ts` we get:
```ts
declare const _default: {
[x: string]: 1;
};
```

### 🙂 Expected behavior

In previous version we had `Record` preserved, which is better both as size and as readability:

```ts
declare const _default: Record<string, 1>;
export default _default;
```

**Comment by RyanCavanaugh** [comment]
@ahejlsberg thoughts?

**Comment by ahejlsberg** [comment]
I think the issue here is that in `type Rec = Record<string, 1>` we now preserve `Rec` as the alias for the type. However, that type isn't exported, so we fall back to a structural declaration in the export from the second module. Not sure there's much we can do since we don't have provisions for maintaining multiple type aliases for the same type.

**Comment by robpalme** [comment]
A bold way to side-step this issue is to not inline, using `typeof` to reference the original type.

Proposed declaration emit for `index.d.ts`:
```ts
import a from "./a";
declare const _default: typeof a["prop"];
export default _default;
```

Users can already nudge TypeScript to create the above declaration emit today by altering the input slightly. [Playground link.](https://www.typescriptlang.org/dev/bug-workbench/?ts=4.2.3#code/PTAEAEBMFMGMBsCGAnRAXAlgewHYCg8QIAzDeaHRAW2gC5QA6YRBtAZzzQE8AHaUAEpxQAXkFwsySAB42aZBhwBzADSgAjAD4A3AWgAPHpLSgYxRAFd4JgN55QD0D2RYe9GwF9QiNuNh4PAgIicFJyShp6JkUYfVYODCojZBNEUGIXKlAAIiZEbN1YXDknFzdQbj4sYm8AbWznV2yAXVFvBkaeXQNkkzNLa1LXbSA)
```ts
// @filename: ./index.ts
import a from "./a";
const prop: typeof a["prop"] = a.prop;   // redundant type annotation - disables declaration inlining
export default prop;
```

It would be nice if this nudging was not necessary.
