### ISSUE TITLE
Allow user to define the global object

### ISSUE THREAD

**Issue by dreifachstein** [Microsoft/TypeScript#4331]
ECMAScript has the concept of implementation defined [global object](http://es5.github.io/#x15.1), so that properties of the _window_ object in a web page can be accessed globally. Implementing this can eliminate a bunch of duplicated declarations in the default lib and also make it easier to target other runtime environments.

**Comment by mhegazy** [comment]
I remember discussing this issue around the 0.8 time frame, and the conclusion was that global namespace polluters (e.g. Window) are not a good practice in general, and thus should not be nativelly supported. what i am talking about is things like window properties can be accessible with no qualifications, and window becoming the value for `this` in global functions etc..

The way you would do this today, as you mentioned, involves a bit of extra work, and again this was intentional. All changes needed should be in a library file, and the rational for this was that the library file is not special. anyone can write a .d.ts and define different global etc..

**Comment by dreifachstein** [comment]
I agree that it is easy to emulate the global object in a library file, which is usually a one-time effort. So I will close issue.

FYI I am writing automation scripts for our artists. Having to duplicate a bunch of declarations was quite frustrating at first. After writing scripts to generate .d.ts from photoshop and aftereffects reference manual this become a non-issue.
