### ISSUE TITLE
TypeScript doesn't understand `fromEntries`

### ISSUE THREAD

**Issue by vdegenne** [microsoft/TypeScript#43332]
Look at this example

```typescript
const exchanges = {
  kraken: new Object,
  binance: new Object,
  others: new Object
}

declare type AvailableExchanges = keyof typeof exchanges;

declare type WalletsData = {
  [key in AvailableExchanges]: []
}

let wallets: WalletsData
wallets = Object.fromEntries(Object.keys(exchanges).map(exchange => {
  return [exchange, []]
}))
```

I have an initial object `exchanges` (key: name of the exchange, value: Object).
Then I declare a type to have all the exchange names in a string literal type.
I declare another object representing a wallet for each exchange in a separator data structure.

Finally I create wallets object based on this last structure. I expect no error since I am only creating a structure similar in keys of the first one only a different value type that `map` take care to create.
But `wallets` variable is having an error saying : 

`Type '{ [k: string]: []; }' is missing the following properties from type 'WalletsData': kraken, binance, others`

**Comment by RyanCavanaugh** [comment]
We don't have any type constructors that could do this, so the definition is written as well as it can be.

**Comment by nmain** [comment]
If you refactor the `Object.fromEntries(Object.keys(.....` code into a helper function that takes a value selector predicate, you can usually put a type on the helper function that lets you have strong typing when calling that function using mapped types.  The types for `lodash` may have some inspiration in them.

**Comment by yw662** [comment]
It is a `Object.fromEntries` issue but also a `Object.keys` issue before that.
You may right your own version for `Object.fromEntries` to workaround that issue.
like this:
https://www.typescriptlang.org/play?target=99&jsx=0#code/MYewdgzgLgBApmKAnAlnCMC8AoGeYA8AKgHwAUcAXDEQJRYm754DyARgFZzBQB0CyNBAr0AhhgDeTZngDaAaRgowMANZwAniABmNALrUFAGhoK9e6fgC+s9Vt1E9si9lCRY2pCAC2AUUSo6FgwTASKcAAeUAgAJhjQqGAA5iYAauQCgRCG8kapTnr0mCQhzOxcPLyePv6C6BQBQmKSlnJ2SiryBjCpllbYruDQ8BHAABaiyUGYMFJ4qkii6mDUYHAA7jDl3FBGTGzKk8BUMGub2zx7eCBQY3BI2acbW5w72P3YMdwANqJIcDAoBoAA4AgCCADdRChfmxvnBfKMJlMMDM7DpASC4BjIuNJkl0ABuAZfYC-f6Y0EwADqom+8KgEAAIqIoKJgnMYLZNB0YJDobD4Yi8Sjus53gNBu4YEikrUsoZ0bogaCcUj8egTM4CsFMkIKOqUbReN5RMCyGRbCZCsUrVzzLQBm5hus6QzHrT6XBGSy2cFqn5GvVZfKmkA

**Comment by lmmarsano** [comment]
The type system is powerful enough to do better than this.
I often override the built-in type definitions if it's bad enough.

```typescript
type UnionToIntersection<Union>
  = (
    Union extends unknown
    ? (distributedUnion: Union) => void
    : never
  ) extends ((mergedIntersection: infer Intersection) => void)
  ? Intersection
  : never
type Entry<T, K = keyof T>
  = K extends keyof T
  ? [K, T[K]]
  : never
type _FromEntry<T extends readonly [PropertyKey, unknown]>
  = T extends unknown
  ? { [k in T[0]]: T[1] }
  : never
type FromEntry<T extends readonly [PropertyKey, unknown]> = UnionToIntersection<_FromEntry<T>>

interface ObjectConstructor {
  entries<T>(o: T): Entry<T>[]
  fromEntries<T extends readonly [PropertyKey, unknown]>(entries: Iterable<T>): FromEntry<T>
  keys<T>(o: T): (keyof T)[]
}
```

Some type definitions at first glance seem unnecessary: they're written that way to take advantage of [distributive conditional types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types).
Distributivity in `Entry` produces a union of ordered-pairs instead of a single order-pair of unions.
`UnionToIntersection` takes advantage of covariance in function parameters & distributivity to infer an intersection.
`FromEntry` distributively maps each ordered-pair of a union to a singleton key/value mapping, then intersects that union to merge all those mappings.

With these definitions, your code (lightly modified to explicitly type ordered pairs) [passes type check](https://www.typescriptlang.org/play?target=99&jsx=0#code/C4TwDgpgBAqgdgSwPZwCpIJJ2BATgZwgGNhk4AeeMgPgCgooBeKACnodkRSggA8c4AE3xQArnADWcJAHc47BgH5WghPmC4EAI1E5BVFAC5OZAJRNqUAG5IEghVGNwIVvO3N8Bw1iwC2eAHMIQSwcAmJSIygEOAAzPChQvEISMwtrW0FTdmUk8NSUdicXN1BIKABRbFwQclQAGigAaSYoCQgQJFioVDoGZhbPCCERds7u1ByoAG0mxtRZgF1FoqhnV1xaMugAfQAxXCRfKo1a1B5+Ye9cCABDQRQAGxAZgAVDyFxQJo7G8SlZHBFn1WuchiMxJJpHIpgBvGYSaJwHrTAAMy2MCwAjIsoABfVbrUrgaAHI4nGp1C5eEQ3e5PF7Td5IT7fX6QgFyYGtAxoTDYZIRMjkfaHY7VM7UOi0GJhWK3IjQADyWgAVhEAMIodS4UQkJC4KCw9jDDQICD4OrUFhITGmYwUyXTFYMWJiinmy1gy4QukPODPN4fPBskB-KGA4EsU2aC3GDBhW5aR4QK32qBk8WnK3sMZe622nrplhjLpF520AlEbXAC5EAAWtzgQREzGNDAkuFu7TgxRkUBV6pI9XYWhiTcVfYHaoiI4YSGA9eSU8HEUrtFogmIj1uNyg2ygAEErLcEDvkxAKrwG02W61S91tmW+DfmxaANwbrdEHd7g8AdVuR4U2AfAABFbmAW5WnbBEOiRI8TzPJMUyvV8W0WYwKwJWgQKgGQgJA-BjEA4CIFAiCoNoAiyNA1pVxIAA6N1yWqT0WAY4BGLzaNr0bN98FMRjfFuMBePQ6BGEschpifboX34oJGmdYFpgU28IGU5ZTFMIA).
