### ISSUE TITLE
how can I declare an abstract data type

### ISSUE THREAD

**Issue by bobzhang** [Microsoft/TypeScript#4334]
I am compiling ocaml to typescript, for ocaml, the type declaration does not make sense in typescript, so I want make it abstract type

```ocaml
type intlist  = | Null | Cons of int * intlist
```

is this below correct?

```typescript
declare interface IntList {
}
```

or 
```typescript
declare class IntList{
}
```

Thanks

**Comment by DanielRosenwasser** [comment]
Hi there @bobzhang. In the future, [StackOverflow](https://stackoverflow.com] may be better suited for questions like this.

There is no integer type in JavaScript, so TypeScript has the `number` type. That said, you probably want

```TypeScript
interface NumberList {
    value: number;
    next: NumberList;
}
```

`undefined` or `null` would be your `Nil`/`Null`/`[]`.

The class declaration you gave implies that there exists a class with a default constructor *in your JavaScript codebase*. This means that you'd be telling the compiler that you're able to write something like `new C()` even though at runtime the code will fail. If you omit the `declare` part of your class declaration, it will actually work though, since you'll actually get a class declaration in your JavaScript emit.

You can omit the `declare` portion of your interface - `declare` implies that some runtime value actually exists, but it doesn't make sense.

> I am compiling ocaml to typescript

Do you mean you're translating an existing OCaml program to TypeScript, or that you're writing something to compile code from OCaml to TypeScript?
