### ISSUE TITLE
Assigning to Partial object from full object is errored

### ISSUE THREAD

**Issue by joshkarges** [microsoft/TypeScript#43426]
## 💻 Code
The simplest example I could come up with is this:
```typescript
const obj = {one: 'foo', two: 5};
type OneTwoObj = typeof obj;
const partialObj: Partial<OneTwoObj> = {};
const key = 'one' as keyof OneTwoObj; // 'one' | 'two'
partialObj[key] = obj[key]; // Error: Type 'string | number' is not assignable to type 'undefined'. (2322)
```

## 🙂 Expected behavior
`partialObj['one'] = 'foo';`

## 🙁 Actual behavior
Compiler error:
```
Type 'string | number' is not assignable to type 'undefined'.
  Type 'string' is not assignable to type 'undefined'.(2322)
```

## ⏯ Playground Link
[Here's the playground link on v4.2.3](https://www.typescriptlang.org/play?#code/MYewdgzgLgBCBGArGBeGBvcBTAXDA5AGYgj4A0MUA7iHgKwC+A3AFBQCeADljAPJhYAKjV5JUlLlhCE4SVqEixOAQwBOUAJbKANqMR4ACms06APPyEikAPnHpmLBdBgBrLO3H5s+GMoiv3aT4BYRA9VhV1LV0kAG03dgBdcQREePdEpiA)

The issue seems to be that the `key` is a union of the strings that make up the keys for `obj`, when we use that key to assign to a partial object.

**Comment by joshkarges** [comment]
Seems similar to this issue except in this case, there's no generics: https://github.com/microsoft/TypeScript/issues/31661
It's a little hard to tell what the resolution of that issue is.

**Comment by joshkarges** [comment]
My current workaround is to use lodash [`_.set`](https://lodash.com/docs/4.17.15#set):
```typescript
_.set(partialObj, key, obj[key]);
```

**Comment by mongoose700** [comment]
The issue is that when you do `as keyof OneTwoObj`, it doesn't know what the value is. Then when you use the key, it's not able to recognize that it's using the same key in both the left and right side. It's clearer when you split the `obj[key]` into its own line:
[Playground](https://www.typescriptlang.org/play?#code/MYewdgzgLgBCBGArGBeGBvcBTAXDA5AGYgj4A0MUA7iHgKwC+A3AFBQCeADljAPJhYAKjV5JUlLlhCE4SVqEixOAQwBOUAJbKANqMR4ACms06APPyEikAPnHpmLBdBgBrLO3H5s+GMoiv3aT4BYRA9eXBnVQ0AcwALKABlDQATHjQERABtN3YAXVYVdS1dJBz3PPFo+KTUrCYgA)

```
const obj = {one: 'foo', two: 5};
type OneTwoObj = typeof obj;
const partialObj: Partial<OneTwoObj> = {};
const key = 'one' as keyof OneTwoObj;
const rightSide = obj[key];
partialObj[key] = rightSide;
```

**Comment by mongoose700** [comment]
Something like [this](https://www.typescriptlang.org/play?#code/C4TwDgpgBA0hIDED2AnAagQwDYFcIB4AVKCAD2AgDsATAZygCUIBjVa-ABRSUhVDhAAaKDkoBrSkgDulAHzC0sqAF4oAbwBQUKAG0YUAJaUoY+EgBmUQgF0AXFDQlyVOlb3WoAflhR7lCABuECgA3BoAvjqmIBZW1mEarJS0wFBIAEYAVirqSP72AOTmSEgFwsBSSPYArOFhoJBQAPL+hJVNWTkNELEZmWFJKVBgGHwG2B2Z9hyjwONY+C0QbUiTSqpqdYl5Q9H2Asjo2HiLre1ZwikoRgDm61AFeRAFAzup1zcAFsAAygbU0FUfSi8HiGhGYwmWRBIA8qg+3z+AJCQA) would work, since it keeps track of the value type associated with the key:

```
type KeyForValue<T extends Record<PropertyKey, unknown>, V> = {
  [K in keyof T]: V extends T[K] ? K : never;
}[keyof T];

const obj = {one: 'foo', two: 5};
type OneTwoObj = typeof obj;
const partialObj: Partial<OneTwoObj> = {};
const key: KeyForValue<OneTwoObj, string> = 'one';
const rightSide = obj[key];
partialObj[key] = rightSide;
```

**Comment by RyanCavanaugh** [comment]
The assignment
```ts
t[k] = s[k]
```
is only safe when the indexing expression `k` is known to produce the same value in both the left and right expressions, but our type system doesn't track value identity - it just sees this as a `T[K1] = S[K2]` which is possibly invalid (e.g. when `K1` and `K2` point to different keys).

We're considering special-casing this exact form but for now this is a design limitation.
