### ISSUE TITLE
Asserting partial object type containing empty array has obscured error

### ISSUE THREAD

**Issue by alololox** [microsoft/TypeScript#43490]
# Bug Report

When you are type asserting a partial object that includes an empty array, the error thrown doesn't reflect the actual problem, .e.g.

```ts
type EarningsResponse = {
    earnings: number;
    extraProp: string;
    earningsList: number[];
}

const newEarning = {
    extraProp: "test",
    earningsList: [] 
    /* Property 'earnings' is missing in type '{ extraProp: string; earningsList: never[]; }' but required in type 'EarningsResponse'. */
} as EarningsResponse;

const newEarningwithArrayType = { 
    earnings: 1,
    earningsList: [1] /* <-- non-empty array and no more complaint even with missing 'extraProp' */
} as EarningsResponse;
```

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.0.5#code/C4TwDgpgBAoghgJwHYEskHMDOAlCmwD2Sm0AvFAN4BQUtUEiqGmAXFEgK4C2ARhAgG4adCAA9gCOAAUEBMG0wS06IXXqNlmADIpFbTr34BtALpCAvlSoBjIovYQA7vGTKo5amrETps+VAAiYDxgAIAaYVoGV2YdPShTKAB6ACooAB4AWkz6LjBQKERJECgeDmAoWzyAGzg0Ct1CngJyqC5dTDcAcm9JGTkuqBSkqnNCzFgNZlx8OwghGzsKpCcXJnRHFGAACwBBBGKAFXAySihI9RisNgBGCK8prDjgNiMbk2S0rJykIkyIPIFIpwEpwJAAE3YBDaBAQ0CqYFq9XoADcIEgoJsdm0Ot1er4BkMRmM4BM1poZoRiPMgA)
A more helpful error message would be...  `never[] is not assignable to type number[]`

### 🔎 Search Terms

missing properties, type assert, never[]

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.0.5#code/C4TwDgpgBAoghgJwHYEskHMDOAlCmwD2Sm0AvFAN4BQUtUEiqGmAXFEgK4C2ARhAgG4adCAA9gCOAAUEBMG0wS06IXXqNlmADIpFbTr34BtALpCAvlSoBjIovYQA7vGTKo5amrETps+VAAiYDxgAIAaYVoGV2YdPShTKAB6ACooAB4AWkz6LjBQKERJECgeDmAoWzyAGzg0Ct1CngJyqC5dTDcAcm9JGTkuqBSkqnNCzFgNZlx8OwghGzsKpCcXJnRHFGAACwBBBGKAFXAySihI9RisNgBGCK8prDjgNiMbk2S0rJykIkyIPIFIpwEpwJAAE3YBDaBAQ0CqYFq9XoADcIEgoJsdm0Ot1er4BkMRmM4BM1poZoRiPMgA)

### 🙁 Actual behavior

I get this error message:

```
Conversion of type '{ extraProp: string; earningsList: never[]; }' to type 'EarningsResponse' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Property 'earnings' is missing in type '{ extraProp: string; earningsList: never[]; }' but required in type 'EarningsResponse'.
```

### 🙂 Expected behavior

An error message that reflects the issue:

```
Conversion of type '{ extraProp: string; earningsList: never[]; }' to type 'EarningsResponse' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Property 'earningsList' of type never[] is not assignable to type number[] from EarningsResponse.
```
Or alternatively, infer as `any[]`

**Comment by andrewbranch** [comment]
But `never[]` _is_ assignable to `number[]`. The `earningsList` property is not actually problematic in terms of assignability to `EarningsResponse` in either declaration here. The problem is that type assertions don’t provide a contextual type, so we can’t tell that the empty array is conceptually an empty `number[]` array, and I guess the comparable relationship doesn’t treat that as overlappy. I agree it’s weird that one has an error message and the other doesn’t, but the error message you get actually seems like the best possible error message. Assertions are inherently unsafe, but insofar as there is a problem with either of these assertions, the `earnings` property _is_ the problem. Changing the inferred type of the array simply brings the expression type close enough to the asserted type that we think you know what you’re doing.
