### ISSUE TITLE
How to consume declarations from declaratoinDir in an another project

### ISSUE THREAD

**Issue by maksimr** [microsoft/TypeScript#43500]
This is mostly a question which I was asked a month ago but without any answer, so **sorry** I will post it here because I don't know a better place where we can find a valuable answer.

https://stackoverflow.com/questions/66537004/how-to-consume-declarations-from-declaratoindir-in-an-another-project

-----

We have several projects some of them written on JavaScript some on TypeScript. To share code between projects we have "common" library written on JavaScript. But for TypeScript projects we want to provide type declarations based on JSDoc compiled to d.ts.

We can easily generate d.ts files based on JSDoc, but we want to keep them in a separate folder (We don't want to put .d.ts files near js files). TypeScript provide options for that declaratoinDir. Problem how to consume this type declarations in projects which use "common" library?

Structure of shipped "common" library

```
common/foo/foo.js
common/types/foo/foo.d.ts
```

Currently, if import "common/foo/foo" in TypeScript project we get error that we don't have d.ts file for this module.

`typescript@^4.2.2`

Thanks

**Comment by DanielRosenwasser** [comment]
I've answered on the StackOverflow question. The TL;DR is that you should [investigate using TypeScript's project references](https://www.typescriptlang.org/docs/handbook/project-references.html). Let me know if that works!

**Comment by maksimr** [comment]
@DanielRosenwasser Thanks a lot for your response. Yes, we have tried to use references, but without luck, maybe we did something wrong. So I have created a test repository where I have set up relationships between projects and our setup with reference approach.

https://github.com/maksimr/TS43500

**Comment by maksimr** [comment]
@DanielRosenwasser I'm a bit confused with the process. Should I continue the discussion on stackoverflow?

Thanks

**Comment by DanielRosenwasser** [comment]
@RyanCavanaugh @sheetalkamat  any ideas here? I've played around with the sample repo and even after turning on `emitDeclarationOnly`, after running `tsc -b` from within `foo`, it seems to have some issues:

```
src/index.ts:1:23 - error TS7016: Could not find a declaration file for module 'common/src/common-1'. 'C:/Users/drosen/TS43500/common/src/common-1.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/common` if it exists or add a new declaration (.d.ts) file containing `declare module 'common/src/common-1';`

1 import {common1} from 'common/src/common-1';
                        ~~~~~~~~~~~~~~~~~~~~~
```

Technically, you'll never be able to publish this package and have "deep imports" picked up without project references - but I can't tell whether this is considered working as intended or not.

**Comment by sheetalkamat** [comment]
I had to do two things.. 
Set `foo/tsconfig` to reference `../common` instead of `node_modules/common` since the file you want to resolve is not in node_modules (shown by `--traceResolution`) That is the file you want to lookup and map to project reference is: `c:/temp/TS43500/common/src/common-2.js`

The other thing i had to do was because the `foo` project doesnt have `allowJs` it cant pick up js files in `node_modules` so i had to set `maxNodeModuleJsDepth` to `1` to be able to include that js file and in turn its dts file. 

But i think problem here isn't that of project reference, dont you think the options for foo should include some kind of path mapping so that "common" translates to "common/types" instead ? Because we always tell people to write imports that work at run time and then make them work using `compilerOptions` configuration.

eg adding these two properties to `foo/tsconfig.json` instead of references should also work?
```
"baseUrl": ".",
    "paths": { 
      "common/*": ["node_modules/common/types/*"]
    },
```
