### ISSUE TITLE
Spreading one named tuple in another throws an error

### ISSUE THREAD

**Issue by pushkine** [microsoft/TypeScript#43516]
TS stable and nightly
[Playground Link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKgDFAvFA2gOgygRgQwE4BcUAzsHgJYB2A5gLq0CwAUKJLAIxKoBmA9r0VIUaAGigY02fILJU6tIA)
```ts
type T0 = [...[bar: string]] // = [bar: string]
type T1 = [foo: string, ...[bar: string]] // Error : Tuple members must all have names or all not have names. (5084)
```

**Comment by armanio123** [comment]
This is by design. Is a bit confusing but what's happening is that `type T1 = [foo: string, ...[bar: string]]` is an invalid syntax. Instead can label it and fix it by changing it as:
```
type T1 = [foo: string, ...args: [bar: string]]
```
There has been a design discussion some time ago about this. You can check more details here: https://github.com/microsoft/TypeScript/issues/43744
