### ISSUE TITLE
Mapping an interface to function signatures and extracting the resulting signatures does not work as intended

### ISSUE THREAD

**Issue by samvv** [microsoft/TypeScript#43518]
# Bug Report

Not sure if this is desired behavior or out of scope, but I cannot map interface properties to function signatures and then extract the union type out of them. Surprisingly, I couldn't find any issues that address this although I have not looked at each issue individually.

The reason I'm asking for a fix is that I'm writing a small and generic RPC library and I want to be able to write a fully typed 'catch-all' handler that is overloaded based on the API that the user provides.

The full type that is used in the code looks like this:

```ts
export type RPCHandler<M extends Record<string, (...args: any[]) => any>>
  = { [K in keyof M]: (name: K, ...args: Parameters<T[M]>) => ReturnType<T[M]> }[keyof M]
```

### 🔎 Search Terms

 - mapped interface overload

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.3.0-dev.20210403#code/KYDwDg9gTgLgBDAnmYcDqwCWUAmBBABQEkAeAWTlBmADscBnOAJWAGNocT6YpMaBzADRwAhjUQA+CQCg4cALxwA3nADaAaTh84Aa2CIIAMzhkAugC44AChoiAtsEvqAlAolwAbhEw44AX1U9A2MzaWkcNgAbEShUdhpuOEMaSwxsfGISFUMICEsaAFc7ACNgKABuOGKYy25eAUq-CXLpZKsAIhyIducWoA

### 💻 Code

```ts
export type VerySimpleRPCHandler<M extends Record<string, any>>
  = { [K in keyof M]: (name: K) => void }[keyof M]

declare const fn: VerySimpleRPCHandler<{ foo: number; bar: string; }>;

fn("foo");
```

### 🙁 Actual behavior

```
Argument of type 'string' is not assignable to parameter of type 'never'.
```

The argument `name` of `fn` resolves to `never` from the moment there is more than one entry in the interface.

### 🙂 Expected behavior

I expect TypeScript to be able to map the properties `foo` and `bar` to new function signatures that are returned as a union when doing `[keyof M]`, just as you would like when mapping regular properties.

**Comment by whzx5byb** [comment]
In your example the type of `fn` is `((name: 'foo') => void) | ((name: 'bar') => void)`, which is not callable because neither `'foo'` nor `'bar'` are assignable to another case.

You should use a generic function type here.
```
export type RPCHandler<M extends Record<string, (...args: any[]) => any>>
  = <K extends keyof M>(name: K, ...args: Parameters<M[K]>) => ReturnType<M[K]>;

declare const fn: RPCHandler<{
  foo: (x: number) => void;
  bar: (a: string, b: string) => string;
}>;

fn('foo', 1);
fn('bar', 'a', 'b');
```

https://www.typescriptlang.org/play?ts=4.3.0-dev.20210403&ssl=10&ssc=21&pln=1&pc=1#code/KYDwDg9gTgLgBDAnmYcBKAFAwgCQIYB2AJgDbBQA8AsnKDMMQM7rADG0RFjMUAlgQHMANHAAUAOkl4oAxgC44hRAG0AugEo4AXgB8igoh06AUHG1wKAaVoh6TOAGtgiCADM4VHaIJ4AtsAVLEUlxaVkFDGk-YHooRmplS1UdTV0WGABXKAIAFWRgBKSdAG5jYyI2EmlUdgJuOFcCBUxcQlJyCgBvUwaICAVREAUCDN8AI3JUvQA3CF4iUrMx6QG8BW4+QREx9Z5+ASm4Df3SgF8SssbRAHJXPuuRAEZ1Uqvr5agHuGu8L-frl5AA

**Comment by samvv** [comment]
That's ingenious! This solves my issue completely, thanks!
