### ISSUE TITLE
Different behaviors between actual compiler and baselines of class member override.

### ISSUE THREAD

**Issue by g-plane** [microsoft/TypeScript#43533]
# Bug Report

### 🔎 Search Terms

class override

### 🕗 Version & Regression Information

- This changed between versions **4.2.0** and **nightly**

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?strictNullChecks=false&strictPropertyInitialization=false&ts=4.3.0-dev.20210405#code/MYGwhgzhAEBC0G8BQ1XQA4EYBc0B2ArgLYBGApgE7QC80mA3CmugEy6GmU3QuNoYBmdsXJVaAvswAswzmOhTJqAPbL0s0Uozr8IylrUb9SAL5IkoSDAAi0MgA8ALmTwATGLGT9XZSxTIYOLpy5vzKAG6UFACWPtA+fgGsRhSMTKj+YK7KeCAAntARUbFJQsGaoWhFFDFxmdm5Begy5cbphZE1JdAQjmCO0cA9OhwV7dW1ARPdqiN6qZWo6AQkIIMdxXHoc3IGnZMYK2tDhq0L4-vdwDm9FATAjspUABQAlIjt-BAE6JRvWmYzEA)

### 💻 Code

```ts
class B {
    p1: number = 1;
    p2: number = 2;
    p3: number = 3;
    p4: number = 4;
    oop: number;
    pp: number;
    op: number;
}

class D extends B{
    declare p1: number

    override declare p2: number;

    readonly override p3: number;

    override readonly p4: number;

    override static sp: number;

    override override oop: number;

    public override pp: number;
    override public op: number;

    override constructor () {
        super();
    }
}
```

### 🙁 Actual behavior

I've tried the same code in playground with nightly version and with `npm install typescript@next`, and there's only one compilation error occurred: `'override' modifier already seen.` . Other errors, such as `'public' modifier must precede 'override' modifier.`, `'static' modifier cannot be used with 'override' modifier.` and etc. can't be reproduced as baselines in https://github.com/microsoft/TypeScript/blob/master/tests/baselines/reference/override5.errors.txt , so I'm not sure which one is correct.

Context: we're implementing parsing `override` syntax in swc: https://github.com/swc-project/swc/pull/1541 .

### 🙂 Expected behavior

Not sure. Stated as above.

**Comment by andrewbranch** [comment]
It looks like all those errors depend on [`--noImplicitOverride` being enabled](https://www.typescriptlang.org/play?strictNullChecks=false&strictPropertyInitialization=false&noImplicitOverride=true&ts=4.3.0-dev.20210405#code/PTAEAEDsHsEkFsAOAbAlgY1QFwPIDcBTAJyNQBMCAuULIgVwIChH1kBDAZw9ACFQBvRqGGhEARmqQ68AEbFQAXlBiA3EJGIATJOlyii0JrUjRAZh2z5S08Y0AWC3oN3bw6NESPir0Z9BTLIh8PLyDGAF9mVk5uABFQAgAPLAJIMm4+QRMKaKICUQl-XWJmE2hCEnJ8nPY80W0iwLV1YTy2MmhIZABPUHLiUgozUOayisH8to6u3sQHRr1RkX7KoY4sNiwMUA4-AMXS5fGqvuOh9z3isJbROhk0dFOBk8RLppuVidv77ZCF70ObjO+XQnXW9HQWGg+gAFABKAQ3EwcOiIYjwnyRSJAA). I don’t know why that would be the case—it seems like all the grammar checking should happen regardless of the flag. Also, was it intentional that the order of modifiers between `override` and `readonly` isn’t enforced? /cc @DanielRosenwasser @Kingwl

**Comment by DanielRosenwasser** [comment]
I think `override` should precede `readonly`.

**Comment by Kingwl** [comment]
My bad. Thanks!

**Comment by g-plane** [comment]
There's another pull request which may be related to this: https://github.com/microsoft/TypeScript/pull/43545 .
