### ISSUE TITLE
Map constructor does not handle nested array variable reference as an argument

### ISSUE THREAD

**Issue by arkon** [microsoft/TypeScript#43575]
# Bug Report

### 🔎 Search Terms

- map
- map constructor

### 🕗 Version & Regression Information

- This is the behavior in every version I tried between v3.3.3333 and v4.3.0-beta.

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYewdgzgLgBADgQwE4ILYFMrqRGBeGAbUIHIBrdATwEYSAaGEgNwQBsBXdWgXQdIsoAmeoxYd0w7twDcAKDDoA7jACyCOAApi5KrQbM2nHnx1CRB8ZO4BKeUtXqNiFBiw4YCXAEk3CAEas6AA8hNBIAJZgAOYMYZFR3AB8tgrKaprOaJjYELayoJCwma45ggBcMD7Y-oEhcdGxUBHRSfhE-LrmYkYkvESmwvrdEr0ydmmOxdk4gtZAA

The behaviour occurs in every version currently available in the Playground (i.e. down to v3.3.3333).

### 💻 Code

```ts
// Works
new Map([['key1', 'value1'], ['key2', 'value2']]);

const parameters = [['key1', 'value1'], ['key2', 'value2']];
new Map(parameters);  // doesn't work
new Map(parameters as Iterable<[string, string]>); // works

// Also works
const parameters2: Iterable<[string, string]> = [['key1', 'value1'], ['key2', 'value2']];
new Map(parameters2);
```

### 🙁 Actual behavior

No overload found for a regular array. This appears to be a gap in type inference.

### 🙂 Expected behavior

Should work as it does in vanilla ECMAScript:

```ts
const parameters = [['key1', 'value1'], ['key2', 'value2']];
new Map(parameters);
```

**Comment by MartinJohns** [comment]
> No overload found for a regular array.

Because a regular array can have an arbitrary amount of elements (including 0 or 666), whereas the map requires exactly two elements (a tuple). Adding an overload would hide this very valid compiler complaint and prevents bugs from being visible at the type level.

> Should work as it does in vanilla ECMAScript:

That is really not an argument. The point of TypeScript is to provide type-safety at compilation level, which is exactly what you get here. `[] + 2` is valid ECMAScript as well, but it reports an error in TypeScript.

See also: [What does “all legal JavaScript is legal TypeScript” mean?](https://stackoverflow.com/questions/41750390/what-does-all-legal-javascript-is-legal-typescript-mean)

---

The easiest solution to your problem is just to fix your type and use a tuple instead of an array. You can use a [const assertion](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions) for this:

    const parameters = [['key1', 'value1'], ['key2', 'value2']] as const; // Now a tuple, not an array.

**Comment by arkon** [comment]
Is there some opportunity to better infer a valid array (i.e. a tuple) in these cases? I'm fine with more explicit typing if needed, but it may seem slightly unintuitive.

**Comment by MartinJohns** [comment]
- If you declare a literal, use a const assertion as demonstrated.
- If you have an array, and you're absolutely certain that the elements match up, use a type assertion (as you used in your code example).
- Otherwise write a custom type guard that verifies the amount of elements in the array and narrows the type.
