### ISSUE TITLE
Negative type guards (with `Exclude`) do not narrow types in some situations

### ISSUE THREAD

**Issue by JakeSidSmith** [microsoft/TypeScript#43589]
# Bug Report

Negative type guards (using `Exclude`) do not appear to correctly narrow types in some examples. This is only appears to be an issue if the types that you are narrowing overlap (e.g. number keyed objects and arrays).

As you can see in the `isNotArray` example below, the narrowed types do not reflect the types that the guard seems to guard against.

In the last example it is impossible to use, for example, `thing.map(() => null)` in either branch of the if statement.

It would be really nice to have an `is !` or `is not` syntax specifically for this purpose, as opposed to using `Exclude` if this is the intended behaviour of `Exclude` (though it doesn't _feel_ right currently).

### 🔎 Search Terms

Negative type guard, extract, exclude

### 🕗 Version & Regression Information

I believe this has always been an issue.

First noticed in `3.9.9`, have since tested in `4.2.3` and `4.3.0-beta`.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about negative type guards.

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYewdgzgLgBAlhAggJ2QQwJ4wLwwDwAqMApgB5TFgAmEMaYGAfABRxgAOArlAFwwEBKPmy6wEMAKLl0wKIQA0MZMTRVwAGyz0MAbQC6jHIZToMAOgQnMrDtwEBuAFChIYiADkQUK1lyES5JQ0dAwsItx8gsK2bpKkwOqcVMQKSipqYJohugZGMACEPhZIqNbhUA6OzuDQMFAAFmwA5jgw+nS0yqoaWNDIze0APjAASsSgyFR4YJwAtgBGxMiK2oxOjnAAZjCsJabMDc0CAjAA3o4wlzAA9Ndp3Zm9UP1gTfoXV4evTgC+JOoQYhnD6XW6jcYgSbTOaLZbZRgguqNb6OH5VLY7fKWUoYA7IprHYFXG53MYTKYzBZLFahRFfJq-f6AolXMFdDJZPoDPR0-G-KpggAiIGItDAXhgAHdIQBrEgAN0oSJAnCa9XgsDQ7HYKmQtCgIBgE2UsiyYDQqBAkqRQKgGB18G2GBVMHqIEVyBg7qWGrMfscYPK8FoZMhFJh1PhG22u083hxeKOJ3OxLZ6R6MC5ryG4PJ0KpcNWvOajOIAKBKdZdzAxA9xZRPyAA

### 💻 Code

```ts
const isArray = <T extends any>(input: T): input is Extract<T, readonly any[]> => Array.isArray(input);
const isNotArray = <T extends any>(input: T): input is Exclude<T, readonly any[]> => !Array.isArray(input);

const thing = [] as readonly string[] | Record<number, any>;

if (isArray(thing)) {
    // readonly string[]
    thing;
} else {
    // Record<number, any>
    thing;
}

if (!isArray(thing)) {
    // Record<number, any>
    thing;
} else {
    // readonly string[]
    thing;
}

// Does not work even though it appears to correctly narrow the type if you hover over it...
// input is Record<number, any>
if (isNotArray(thing)) {
    // readonly string[] | Record<number, any>
    thing;
} else {
    // never
    thing;
}
```

### 🙁 Actual behavior

When narrowing overlapping types using type guards, types instead include overlapping types (or never).

### 🙂 Expected behavior

Types should be narrowed to exclude those which were defined in the `Exclude`.

**Comment by andrewbranch** [comment]
This is expected behavior. Here’s what’s happening:

1. When you call `isNotArray(thing)`, `T` is instantiated with `readonly string[] | Record<number, any>`.
2. With a concrete `T`, we can resolve the `Exclude` conditional type right away, which distributes over the union `T`:
    1. `readonly string[]` is assignable to `readonly any[]`, so this constituent’s instantiation evaluates to `never`
    2. `Record<number, any>` is not assignable to `readonly any[]`, so this constituent’s instantiation resolves to `Record<number, any>`
    3. The result of the `Exclude` conditional is the union of the results from the previous two steps, which is `Record<number, any>`
3. So, the return type of `isNotArray(thing)` is `thing is Record<number, any>`
4. Inside the body of that `if`, we get the type of `thing` by looking for relevant control flow nodes:
    1. We know from the `if` condition that `thing is Record<number, any>`
    2. We know from the declaration of `thing` that it is `readonly string[] | Record<number, any>`
    3. So the resulting type can be calculated by filtering out the constituents of `readonly string[] | Record<number, any>` that are not assignable to `Record<number, any>`:
        1. `readonly string[]` is assignable to `Record<number, any>`
        2. `Record<number, any>` is assignable to `Record<number, any>`
        3. So, the result is `readonly string[] | Record<number, any>`

The key takeaways from this are:

* `readonly string[]` is a subtype of `Record<number, any>`, so determining that something is a `Record<number, any>` definitely does _not_ prove that it is not a string array. By the same reasoning, `readonly string[] | Record<number, any>` is not a particularly meaningful type (it reduces to `Record<number, any>`), though it does enable you to do distributive operations with conditional types like `Exclude` and `Extract`.
* You would need negated types (#29317) to express the type “anything other than a string array.”

**Comment by JakeSidSmith** [comment]
Thanks for the confirmation. 😁 That's pretty much what I'd imagined (although in less detail 😂).

I guess the number record vs array wasn't the best example of this, but I imagine my other use cases all fall into a similar explanation that would be resolved by the negated types.

I guess I was expecting potential overlap in the resultant guarded types (due to the overlapping union), but was just surprised when I was unable to access array methods in the other branch as you'd expect the type guard to be essentially saying "this is an object with number keys, but not the array methods" and therefore the other half would be "this has array methods".

In any case it seems that what I really need is those sweet negated types. 🤤 

Is this feature on the roadmap? It looks like that PR has been open for a few years now. 😐

**Comment by andrewbranch** [comment]
It’s not currently on the roadmap. Negated types are definitely useful for some things, but it seems like your example here shows that you _don’t_ actually need it, because your `isArray` guard works properly to narrow to `readonly string[]`. And precisely _because_ the union is not disjoint, there’s not really any point in saying “this is definitely _not_ an array,” because the things you can do with that type are the same things you can do with `readonly string[] | Record<number, any>`, because that type _is_ essentially `Record<number, any>`.
