### ISSUE TITLE
Allow use of instance type on static methods of an generic abstract class

### ISSUE THREAD

**Issue by thiago4455** [microsoft/TypeScript#43587]
# Suggestion

It is currently impossible to use an instance type of a class in a static method. Which makes perfect sense, because in a static method there is no instance to obtain a type.

One noticeable thing using a generic abstract class is that since it cannot be instantiated, the type parameter must be passed through its derived class. However, even so, it is not possible to use the instance type in a static method, even though this information is already known at compile time.

In many cases, it is desirable to create classes derived from a generic abstract class, passing itself as the type parameter. This pattern is so common that it was called CRTP _(Curiously recurring template pattern)._

I believe that the use of static methods in a CRTP would be very useful, and I will discuss further the specific case that made me want this feature, in the hope of demonstrating how it can add value to TypeScript. 

## 🔍 Search Terms

static method generic abstract class instance type

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Basically, I wish I could do this: 
```typescript
abstract class Foo<T>{
    static baz():T { /* Get me food*/ }
    static qux(t: T) { console.log(t) }
};

class Bar extends Foo<Bar>{
    fruit: string;
    amount?: number;
};

let myBar : Bar = Bar.baz();
Bar.qux(myBar)
```

## 📃 Motivating Example

My problem started when I was creating my database connection classes.
I am using a NoSQL database, and in my case there is no difference between the methods of each table for communicating with the database, so I created an abstract class that implements all the necessary CRUD methods.

My objective then was to create classes of the tables extending this initial class, where it would only define the properties of the table and allow me to have typing of the data originated from the database. 

```typescript
abstract class Table<T>{
    static table_name : string;
    static get(t): T{
        // database.get(table_name, {params: t})
        return;
    }
    static put(t: T){
        // database.put(table_name, {params: t})
        return;
    }
}

export class User extends Table<User>{
    static table_name = 'User';
    email: string;
    name?: string;
}
```

I would like CRUD's methods to be static, so that I could interact with the database just like this:
```typescript
let bobsName = User.get({email: 'bob@example.com'}).name;
User.put({name: 'John', mail: 'john@example.com'});
```

This would be very useful for my case, and totally valid, since all the type information is already at compile time.
However, due to the rule of static methods this is not possible. 

#### What do you want to use this for?
For type definition in static methods of generic classes, where it is possible to know the type at compile time 

#### What shortcomings exist with current approaches?
The need to use the `any` type for these cases of abstract classes 

#### What workarounds are you using in the meantime?
For my specific problem I could use non-static methods, but it would be at least an ungraceful solution.

My example is just one of several. Considering the very existence of CRTP, it is already a sign that it is a relatively recurring problem.

**Comment by jcalz** [comment]
Your terminology suggests that you're coming from a language like C++, where generic classes are literally *templates* that generate new code for each instance whenever it runs across a mention of the template with the template parameters filled in.  This is called *specialization*, and it means that if I have a generic class `Foo`, then `Foo<int>` and `Foo<std::string>` are *two different classes* at runtime.  

TypeScript is more like Java, in that generics (and for TS, the whole static type system) are completely erased at runtime.  There JavaScript code that gets emitted for `class Foo<T> {...}`  is just `class Foo {...}` (for any modern target environment anyway).  So there is no `Foo<number>` class distinct from the `Foo<string>` class at runtime.  There's just the one `Foo` class constructor.  

That's why it makes little or no sense for the static side of classes to know anything about the instance generic type parameter.  Or at least, it only makes sense in the relatively rare case that the entire static side of the class can act like all possible specifications of the type parameter at once, a so-called "generic value", as asked for in #17574.  The construct signature itself is like this (something like `new <T>() => Foo<T>`) but there's no way to expand this to other static properties. 

It's possible there's some form of this proposal that would make sense without full support for generic values, but I'm not really seeing it.

---

As a workaround, I'd suggest that whenever you need the scope of a generic type parameter to encompass the static side of a class, you consider making a class *factory function* that outputs entire class constructors.  This will make it behave more like C++, in that every call to the factory function will result in a new class constructor, which is then able to "know" something about the type parameter.  Here's an example of your `Table` code:

```ts
function Table<T>() {
  abstract class Table {
    static table_name: string;
    static get(t: Partial<T>): T {
      return database.get(this.table_name, { params: t });
    }
    static put(t: T) {
      return database.put(this.table_name, { params: t });
    }
  }
  return Table;
}
```

And then you can specialize it with `User` like this:

```ts
class User extends Table<User>() {
  constructor(public email: string, public name?: string) { super() };
  static table_name = 'User';
}

User.put(new User("bob@example.com", "Bob"));
let bobsName = User.get({ email: 'bob@example.com' }).name;
console.log(bobsName) // "Bob"
User.put(new User("John", "john@example.com"));
```

Or other specializations like this:

```ts
class Something extends Table<Something>() {
  static table_name = 'Something';
  constructor(public age: number, public height: number, public description: string) {
    super();
  }
  yell() {
    console.log(("I am " + this.description + "!!").toUpperCase())
  }
}

Something.put(new Something(20, 40, "An old tall thing"));
Something.put(new Something(5, 2, "A young short thing"));
Something.get({ age: 5 }).yell(); // I AM A YOUNG SHORT THING!!
```


[Playground link to code](https://www.typescriptlang.org/play?declaration=false#code/MYewdgzgLgBAtgQwA4C4YCUCmoBOATAHmhwEswBzAGhgTAE8BtAXQD4YBeGAbwF8AoPgDMArmGBQS4GOUxQAFFDTEyVGKm5qEOBHAhpadGD2riQONGEwB3GHICUHNgbv763PjBihIsHLI62iEgMUEwwAD7hMMx2AHSCZHhyAB6OMADyAEYAVthQsZhgUKSYEHJIsUhaOhBxmABumDh0cnIMANbU9UwO7GwpHWHswzD1duMA3B4wJIK2AIR+UA5QABY4IDaWNgCiOBs4CjAA1DAARDBgILCCIKJ4Z3ZTnkvCOGAwS1P8QqLikh8kMJ5IoYMoKNR1FxNNpdK5DDwXDQ3FxpkEQkNAsgMREojFnvBsaFKsIIKtypVqronnwft5oDA8AgoAhMggIJgAqjPDIoJDgbSBCIxBIpAAVVkAG0wBDFLHs7k8wEl7IgMAlmWlis8YJZEmAMBZmswAH0wDpMEpiioCZ5oMySAbeQo0AAFLQSBCS2UsJFi7U6z6yN4fJlG9mYWLOtYkCCxI3Ss0W6jQqqwvSGozUGO1W1GaZ2vWOtTAl3qhzcwNBqAhxnM1kRkkg1ax+NS03muCYFMwmpoWCIvP8TzD6u1jXS74CAD0s7n84X84EytVMAAqhycDBMMkoIU8GqJzKN015RXpvTisJTIcgZri5hECRJVbSBCS-eDZ3MAB+V8qCswWEJAmgVHgCXtfVDXbJMuwCAByE8cHgqc+CQps5G2ddNzkM5MhATIAAEdx0JBpViUA4DOagzgAIQIx4aT4aVYHwzIIAAOQtAJ0OdaFHwQZ80HgtjiOSUjyMo+CjDib8pnpEByMlEByDkNjOItBxZxgejMjQzcMKwpDcIAKRAVYwGo85snMsAxIkyNKMYqY+BXCA1QAZRALsYwobdd33Q92wILyfJbCgz21SDiwTDtuM4eDQtkcLyBQi9wGIa8oDMcphE-GgZAsYQ4EyJp+Xy1ZMBIchVlBMBitKnByslYs8FKYBSCQUUwH-Chz0DCBgNAmkR2mOhMElSUFUrJUMsUyNlNU3CAEkaDgc4TkNFs4zaiAOpILqAU2s55nmR54xANckBAnAAGEI3sOxpn4H4kt88hDOsGA3pSuQACYAAZqAAFiB84AEEPkUvBoMmraVGcvgfpUT6bGRig5AAVmoP6aPBmA6DuPyyTMWB3sR9GPr4grLRgTGZNicbJvsCYYG01bwYAWRgfGAE10jXDiAHFvoACXSdB-TFUXluF06+CAA)

**Comment by thiago4455** [comment]
Wow, this is a very good solution to my problem, I hadn’t thought about the possibility of an _factory function_.

I still think it would be interesting to allow the generic type in static functions of abstract classes, because by the default behavior of abstract classes you would necessarily pass the type through the extended class.
At runtime it would be exactly the same, the only difference would be to help with linting and typing checking. In my example, the database will return the correct data regardless of the generic class type, but it would be nice if the the return type propagated to the rest of the application.

But thank you very much for the workaround, it will help me a lot to solve my problem.

**Comment by andrewbranch** [comment]
> because by the default behavior of abstract classes you would necessarily pass the type through the extended class.

But the type argument to the base class could just be _another type parameter_:

```ts
class NotUser<T> extends Table<T> {}
```

at which point we would have a problem with

```ts
NotUser.get({}); // returns ????
```

Great explanation and suggestion by @jcalz—that’s probably how I would approach this as well.

**Comment by steveetm** [comment]
@jcalz I also ran into this and tried your workaround. Originally it looked promising, then I run into this:
```
TS4094: Property 'xx' of exported class expression may not be private or protected.
```
I'm using project references, so declaration emit must be turned on. Any advice?

**Comment by jcalz** [comment]
Make the property public?  Without a reproducible example of your issue I couldn't say what to do, and this issue isn't really the right forum for that anyway (maybe Stack Overflow or the TS Discord would be a better place to ask)?
