### ISSUE TITLE
`noUncheckedIndexedAccess` does not narrow properly with `"prop" in obj`

### ISSUE THREAD

**Issue by andreialecu** [microsoft/TypeScript#43614]
# Bug Report

Apologies if this is a duplicate, but I wasn't able to find anything.

### 🔎 Search Terms

noUncheckedIndexedAccess property in object

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&ts=4.3.0-beta#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXy1QDdYspUMAKMPYLbPALngCMccIRyBKZqAZ34gYGfvBqo6DVAG4AUHJTppSdpRwsAVswBKXYHggBPADx6aMYCf4YYhAOYAaeDbup7APg-d4AbznwBMSk5FQARBggNmFB8Bqa3PKBAPTJGAAWCHgILCAQOADu8AU4MADWYgAOMDiVwsYB8KmEJHahlACEHfEA2hFRGGEAuokKgRI28AAe8AC8cVp9kdFDTckutg7wAD7waKCIhCDArMgYLuk4yBAnuRtu9nIAvkA)

### 💻 Code

```ts
declare function invariant(condition: boolean): asserts condition;

function foo(obj: Readonly<Record<string, string>>) {
  invariant(obj && "test" in obj);
  // this one below does narrow to `string`
  // invariant(!!obj["test"]);

  const x = obj["test"] // string | undefined but should be string
}
```

### 🙁 Actual behavior

`x` is typed as `string | undefined`

### 🙂 Expected behavior

`x` should be typed as `string`

**Comment by andreialecu** [comment]
Seems related to https://github.com/microsoft/TypeScript/issues/41848

**Comment by andrewbranch** [comment]
This isn’t really related to `noUncheckedIndexedAccess`—`in` narrowing doesn’t ever take `undefined` out of the domain of a property: https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&ts=4.3.0-beta#code/CYUwxgNghgTiAEA3W8D2AjAVgLngb3gBcQBnQgflzJgEsA7Ac3gF8BuAKHZoDN4AKAETEyA+PTRYAlPnbx4YVHTLwAHvAC8EzAG0hpQgIC6HOQqWF4ATw1aAdMMIdm7IA

You should check for equality / non-equality with `undefined` if you want that behavior.

**Comment by andreialecu** [comment]
Not sure I understand. The type of `obj` cannot have undefined values in it as per its definition.

How does `undefined` fit into `Readonly<Record<string, string>>`?

**Comment by andrewbranch** [comment]
Ah, I see. When you set `--noUncheckedIndexedAccess`, the read type of property access on a `Readonly<Record<string, string>>` goes from `string` to `string | undefined`. But we don’t currently have the ability to model the difference between properties that are `undefined` and properties that are _missing_. If we were to introduce a `missing` type in the future, we would be able to implement the behavior you expect here—the read type from that index signature would be `string | missing`, and you could know that it’s not `missing` via an `in` test. But right now, because we lack the concept of `missing`, an `in` test on an object with an index signature does nothing.

**Comment by derolf** [comment]
With exactOptionalPropertyTypes, unchecked index access could map to
`missing` and not `undefined`.

Then `key in` guarded access should work equally on optionally declared properties and index signatures.

**Comment by KaelWD** [comment]
This seems like a bug rather than a design limitation then.

**Comment by tskj** [comment]
I agree that this is neither a design limitation nor working as intended. This is simply a bug and @derolf's example proves it.
