### ISSUE TITLE
Generator interface does not extend IterableIterable interface

### ISSUE THREAD

**Issue by mfulton26** [microsoft/TypeScript#43629]
> The [`Generator`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator) object is returned by a [generator function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*) and it conforms to both the [iterable protocol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_iterable_protocol) and the [iterator protocol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_iterator_protocol).

However, `lib.es2015.generator.d.ts` only defines `Generator` to extend `Iterator` and not also `IterableIterator`.

https://github.com/microsoft/TypeScript/blob/131875bb849c0a9c56c26d09881453aace0cbfed/lib/lib.es2015.generator.d.ts#L23-L29

I wonder if there are technical reasons for this or if such is intentional. When writing functions that receive an `Iterable<T>`/`IterableIterator<T>` I can pass in something typed `Generator<T>` as it satisfies the same structure as `Iterable<T>`/`IterableIterator<T>` but if want to add to [the %IteratorProrotype% Object](https://tc39.es/ecma262/#sec-%iteratorprototype%-object) and expose that to the type system I have to [merge declarations](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) with not only `IterableIterator<T>` but also `Generator<T>`, it would be simpler if `Generator<T>` already extended `IterableIterator<T>` which would, from what I can tell, be inline with the ECMAScript spec.

Thank you.

**Comment by andrewbranch** [comment]
@rbuckton can probably speak to this

**Comment by rbuckton** [comment]
Is there a reason it needs to? `Generator` defines a `[Symbol.iterator]()` method with a more specific return type than what `IterableIterator` provides. 

Inheriting from `IterableIterator` can cause some problems, as well. `IterableIterator` inherits from `Iterator<T>`, so the `TNext` type argument is defaulted to `undefined`, which means that not every `Generator` is assignable to an `IterableIterator`. This is actually by-design, since `IterableIterator` was never correctly typed. 

Consider the following:

```ts
function * f(): IterableIterator<number> {
  let count = 0;
  while (true) {
    yield count++;
  }
  return count;
}

function * g(): Generator<number, number, boolean> {
  let count = 0;
  let running = true;
  while (running) {
    running = yield count++;
  }
  return count;
}
```

In earlier versions of TypeScript, we did not distinguish between the yielded or returned value, and did not type the value passed via `next`, so code written for earlier versions of TypeScript could do this:
```ts
for (const value of f()) {
  console.log(value);
  if (value > 10) break;
}
```

When we introduced more specific types for generators, we didn't want to break existing code, however we did want to provide an error if you write this:
```ts
for (const value of g()) { // error: Cannot iterate value because the 'next' method of its iterator expects type 'boolean'
                           // but 'for-of' will always send 'undefined'
  console.log(value);
  if (value > 10) break;
}
```

`IterableIterator` essentially exists for backwards-compatibility, and to explain the behavior of built-in iterators for `Array`, `Map`, `Set`, etc.. User defined generators should use the more specific `Generator` type when possible. We may eventually change the definition of `IterableIterator` to accept additional type arguments, but that would necessitate changing `Iterable` as well. This is something we have held off from doing as that could have far-reaching consequences in declaration emit.

**Comment by rbuckton** [comment]
Also note that `Generator<T>` is *not* the same as `IterableIterator<T>` because the default type argument for `TNext` for a `Generator<T>` is `unknown`. If you want to accept a `Generator` that is compatible with `IterableIterator<T>`, you must specify its `TReturn` and `TNext` type arguments: `Generator<T, any, undefined>` (or `Generator<T, void, undefined>`, `Generator<T, unknown, undefined>`, etc.).
