### ISSUE TITLE
.

### ISSUE THREAD

**Issue by newcanopies** [microsoft/TypeScript#43631]

**Comment by jcalz** [comment]
This looks like a runtime problem and is not related to TypeScript, except that the program you are having problems with happens to be written in Typescript.  You might want to ask a question on [Stack Overflow](https://stackoverflow.com/) or some other more appropriate place.

**Comment by newcanopies** [comment]
thank you @jcalz 

I have not found any examples of Typescript syntax that includes SSL certificates, 
and the package/project is really about ROS.
How would you typescript the below server.key and server.crt 

```
var express = require('express')
var https = require('https')
var certOptions = {
  key: fs.readFileSync(path.resolve('build/cert/server.key')),
  cert: fs.readFileSync(path.resolve('build/cert/server.crt'))
}
var server = https.createServer(certOptions, app).listen(50001)
```


into the App.tsx lines opening the port 50001 below:
`const token = jwt.sign({ user: 'example-user' }, 'rmf', { algorithm: 'HS256' });`
  `    const transport = await SossTransport.connect('example', 'wss://localhost:50001', token);`

**Comment by jcalz** [comment]
I don't know the answer to that... I'd suggest figuring out how to do whatever you're doing in JavaScript / node without worrying about TypeScript, and then later work on typings.  In any case, though, this is not the appropriate forum for this question, so you are unlikely to get a satisfying answer here.  You should consider closing this issue and asking elsewhere.  Otherwise someone from the TS team will get here eventually and, most likely, close the issue themselves (or mark it as a "Question" to remove it from their triage queue).
