### ISSUE TITLE
If statement variable reassignment fail type check

### ISSUE THREAD

**Issue by dabreadman** [microsoft/TypeScript#43663]
# Bug Report

### 🔎 Search Terms

-  if statement variable reassignment not assignable to parameter of type
-  if statement variable reassignment not assignable
-  if statement variable reassignment 
-  variable reassignment type 
-  variable reassignment

### 🕗 Version & Regression Information

- Relatively new to Typescript, encountered this on  `typescript@4.2.4`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210413#code/GYVwdgxgLglg9mABMOcBCBDATgChXALkQCIAjbYxAHxPIC9iBKI01AGwFMMkBvAKESIsHKCCxJ8iALwzaFANx8Avnz6hIsBMhgBnABYAVbgGsczRKziduifoM5REMMAAcQjqSWKLBMYIhwAQmc3KEZbAUEnV3dpOSxvSKVEDjYdDid-HBDYwNkyCkQAMiLo0MQ8zwKGcLso4VFxZAw0jh9EFUiGsQlUTFwcsMVOoA)

### 💻 Code

```ts
function fooBar(foo: "bar" | "baz"): boolean {
  return foo === "bar";
}

function fishTank(): boolean {
  let input = "";
  if (!input) {
    input = "bar";
  } else if (input !== "bar" && input !== "baz") {
    return false;
  }
  return fooBar(input);
}
```

### 🙁 Actual behavior

Failed to compile, `Argument of type 'string' is not assignable to parameter of type '"bar" | "baz"'.ts(2345)`

### 🙂 Expected behavior

Compiles successfully.  

![Flow](https://i.imgur.com/UQ8Myfg.jpg)

**Comment by DanielRosenwasser** [comment]
I believe we just don't narrow infinite types to singleton types in equality checks. @andrewbranch was dealing with a similar issue, but I can't recall what the reasoning was.

**Comment by andrewbranch** [comment]
It is kind of similar to https://github.com/microsoft/TypeScript/issues/43584, but the premise of that issue is I feel like `unknown` may be worth treating specially. In this case, you probably just want a type annotation: https://www.typescriptlang.org/play?ts=4.3.0-dev.20210413#code/GYVwdgxgLglg9mABMOcBCBDATgChXALkQCIAjbYxAHxPIC9iBKI01AGwFMMkBvAKESIsHKCCxJ8iALwzaFANx8Avnz6hIsBMhgBnABYAVbgGsczRKziduifoM5REMMAAcQUImQrU5DH+AATDmBnDgDFQRhgRBwAQmc3KEZbAUEnV3dpOSxiCMQlRA42HQ4naJwEzNjZLxzEADJ69MTEaqlfJhS0oRExCQxijjyVVOFRcWRUTFxKpMURoA

**Comment by dabreadman** [comment]
I see, thanks.
