### ISSUE TITLE
Narrowed "unknown" type not detected inside getter

### ISSUE THREAD

**Issue by samisayegh** [microsoft/TypeScript#43676]
# Bug Report

### 🔎 Search Terms

narrow, narrowing, getter, unknown

### 🕗 Version & Regression Information

I noticed this bug on `v4.1.2`. I can also reproduce it on older versions such as `v2.8.1`

Please keep and fill in the line that best applies:

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about ___ __X__ ____
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAdwE4EMAOAKAbugGwC5FwBrMOZMASkQG8BYAKEURmEWygE9MBTOJ3wFEAQgC8ExAHIAzlFQwwAcxl0mrNoigALVFURh+yRAFFUB1NhoBuFmwC+LB4ggI5cAvwB0BOCp4hHQA9CGIAEQiEexyRuiWVPwAJjpwkQpKqjHocfwAHgLQKT6urqj8UCCoSJraiCqVAGqEIPw2DK71FVU1iCK2iGGR0bHxicgpaRmKyio5eYX8xcmlWk4ANC7rDZX9re0aXdo91UgDQ+FRhDEwcQowBKIR5JTUEWv1zlrfjkA)

### 💻 Code

```ts
function wrap(val: unknown) {
  if (typeof val !== 'string') {
    throw new Error();
  }

  console.log(val) // "val" is narrowed to "string" as expected.
  
  return {
    getValue() {
      return val; // "val" is narrowed to "string" as expected.
    },

    get value() {
      return val; // "val" is still "unknown".
    }
  }
}
```

### 🙁 Actual behavior

The type is not correctly narrowed inside getters.

### 🙂 Expected behavior

The type to be narrowed inside getters, as is the case for references in other parts of the function.

**Comment by a-tarasyuk** [comment]
It seems this issue was resolved in  https://github.com/microsoft/TypeScript/issues/45006, [Playground](https://www.typescriptlang.org/play?ts=4.5.0-dev.20210908#code/GYVwdgxgLglg9mABAdwE4EMAOAKAbugGwC5FwBrMOZMASkQG8AoRRGYRbKAT0wFM52+AogCEAXjGIA5AGcoqGGADmUukxYsoAC1RVEYXskQBRVLtTYaAbmaIAvrdupeUEKiTqNSlwDVCIXksGWw1EZ1d3RCErRAB6WMQAIiFE1hl9dDMqXgATRCg4JLkFZVT0dN4ADz5oXIA6EPsAGkZG7ygo-0C1RpZwtyRouITkwlSYdLkYAmFE8kpqRLrERocWBzsgA). So I think it can be closed.

```ts
get value() {
>value : string
    return val;
>val : string
}
```

/cc @andrewbranch
