### ISSUE TITLE
Object literal method not working as inference source

### ISSUE THREAD

**Issue by Youmoo** [microsoft/TypeScript#43704]
# Bug Report

Hi. Someone asked a question [here](https://www.v2ex.com/t/744162#reply1). 

After some experiment，I find different parameter passing style leads to different compile result. Perhaps this is a bug?

Please check.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.3#code/GYVwdgxgLglg9mABBATgUwIZTQZSndAHgChFEAlAGlMQFFE0APbMAEwGcK0IDXD2oKGGADmlRAAoMKEQC4KASkQBeAHyIAbnBitVxVRIEE08gN6J0rEBDQp288gG4GwYNyj26iAL5Lz34kCAeiCGFBQCYlRMbDxjCVMaS2tbT0SyMgALNAAbHLgJPx9qMm8SlzdoNJoyAHcCHNYpGT8ajJDEAHkAIwArd0QYTjhgRCgATwAHNEQAcnAAazA4WrBZtrJpEQA6bLyChUc2spoT3yPg0KERTKgo9CxcfHQEpLQrGzszNr38wsR-OVvIgMJweGABOU0K53NUMoh6ihGs0RK14ZsZLtcn9DscgdRzpcLDAbndwQILO8UnYVACaL8DgDisRvEdoo84i90pSPqkoTCqt94YjkVs0eitlj9oUjvCTqUCbigA)

### 💻 Code

```ts
function createStore<
  R,
  E extends Record<string, (arg: R) => void>
>(store: { reducers: R; effects: E }) { }


// error
createStore({
  reducers: {
    hello() { },
  },
  effects: {
    world(arg) {
      // Object is of type 'unknown'
      arg.hello();
    },
  },
});


// right
createStore({
  reducers: {
    hello() { },
  } as const,
  effects: {
    world(arg) {
      arg.hello();
    },
  },
});

// right
const reducers = {
  hello() { },
};
createStore({
  reducers,
  effects: {
    world(arg) {
      arg.hello();
    },
  },
});
```

### 🙁 Actual behavior

Three similar `createStore()` invocations yield different results.

### 🙂 Expected behavior

I thought all of them should be right (or wrong?)

**Comment by andrewbranch** [comment]
Object literal methods (`{ hello() {} }`) are context sensitive due to having a `this` type parameter, so they are deferred in inference. So, the type of `R` gets inferred from `world(arg) { ... }` instead of from `reducers: { hello() {} }`, and since `arg` lacks a type annotation, it becomes `unknown`.

Probably the best way to write this is with an arrow function instead: https://www.typescriptlang.org/play?ts=4.2.3#code/GYVwdgxgLglg9mABBATgUwIZTQZSndAHgChFEAlAGlMQFFE0APbMAEwGcK0IDXD2oKGGADmlRAAoMKEQC4KASkQBeAHyIAbnBitVxVRIEE08gN6J0rEBDQp288gG4GwYNyj26iAL5Lz34kDUTGw8YwlTGktrW09IsjIACzQAGxS4eQklNUR-ajJvfJc3aDiaMgB3AhTWKRk-coTpEQA6ZLS4LMdGwppe326gA

**Comment by Youmoo** [comment]
Thanks.  Now I know TypeScript more ☺️.
