### ISSUE TITLE
Conditional type narrowing ignores nullish coalescing to falsy value

### ISSUE THREAD

**Issue by aaronadamsCA** [microsoft/TypeScript#43705]
# Bug Report

`if (a.b?.c ?? false) a.b.c` does not narrow the type of `a.b` to remove nullish types.

### 🔎 Search Terms

conditional type narrowing, nullish coalescing operator

### 🕗 Version & Regression Information

Occurs in v4.2.3 and v4.3.0-beta. Behaviour appears consistent since nullish coalescing was first introduced in v3.7.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.3#code/JYOwLgpgTgZghgYwgAgILIN4FgBQzkBGA-AFzIBCA3LgL666iSyIrma74JkDOYUoAc2o46OXAAo4ZVAEoyANwD2wACbIAvAD52eZAHo9yAOqKoAa24AaQgFcwyRhBAqIaghAAWcecEU2oDtzINiAIADYQcFAcDjDIkgB0xAkIMshwSSkJESACYB7CMQbIACKKENwgAOT2AO6mZsiAvBuAgnsxwHGJyQjIRETIAEQDaRkEWTl5BUWG+LNz87MAesgA8gQAVhAI9sBBAA6K3NzABGEAnshVIS4woK5VCchg3OIATACsAMyvMvS6xQA5RT2eTQC4IRShXYoVrtTqjIgpZAAQnU6mCzggtxArmQADI8elMqkiWMENknJNhDRhEA)

### 💻 Code

```ts
interface A {
  b?: B;
}

interface B {
  c: string;
}

(a: A): void => {
  // Works, but intended behaviour is unclear
  if (a.b?.c) a.b.c.length;

  // Doesn't work 🙁
  if (a.b?.c ?? "") a.b.c.length;
  //                  ^ Object is possibly 'undefined'. ts(2532)

  // Not very concise 🙁
  if (a.b?.c !== undefined && a.b.c) a.b.c.length;
};
```

It's an edge case with a good use case. [`@typescript-eslint/strict-boolean-expressions`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/strict-boolean-expressions.md) helps avoid tricky bugs by requiring code to separately handle nullish vs. falsy values. Nullish coalescing would be the simplest way to explicitly treat nullish values the same as an empty string.

This might be related to #38136 but I'm unsure.

**Comment by Zzzen** [comment]
why don't you use `if (a.b?.c != undefined) a.b.c.length;` ?

**Comment by andrewbranch** [comment]
Why is `if (a.b?.c) a.b.c.length` unclear? When I see `if (a.b?.c ?? "")` or `if (a.b?.c ?? false)`, I get very confused as to why something already falsey (null or undefined) would need to be coalesced to something else falsey in a conditional.

**Comment by RyanCavanaugh** [comment]
It doesn't seem like this particular lint rule configuration is helping code clarity (for humans or machines). If this turns out to be a popular thing to write we can see about adding detection for it but generally we don't spend perf budget on handling constructs that don't change the code behavior.

**Comment by andrewbranch** [comment]
As an additional workaround, `if (!!a.b?.c)` seems like it would satisfy both your lint rule and our control flow analysis, though I’m generally in favor of turning off painful lint rules.

**Comment by aaronadamsCA** [comment]
I can change the use case, sure, but I wanted to point out the gap anyway. Never know when a little thing points to a bigger thing.

**Comment by JeanRemiDelteil** [comment]
> As an additional workaround, `if (!!a.b?.c)` seems like it would satisfy both your lint rule and our control flow analysis, though I’m generally in favor of turning off painful lint rules.

This is not testing only for `null || undefined`, but anything falsey. So the behavior changes.


Here is a simple code example that output an error in typescript, when it should not:
```typescript
const readProp = (property: string | undefined | null): string => {
  if ((property ?? undefined) === undefined) {
    return ''
  }

  return property;
  //     ~~~~~~~~
  // Type 'string | null | undefined' is not assignable to type 'string'.
  // Type 'undefined' is not assignable to type 'string'.
}
```
[Playground link](https://www.typescriptlang.org/play?#code/MYewdgzgLgBATgUwIYBMAKcQAcYF4YAUWmWCcUAngFwzRwCWYA5jAD4wCuYKCAZowhRsYYDgBsxAShp1GLXAD4YAbwCwAKBgx6vQkRJlKMAPzHO3PgJSS8ufFx78wgm2s1b4CKBzhgYAcn8NLQBfDWDPb18YYmxDCgBuDRCgA)

_Our Context:_ 
We have a rule not to use `null` in our project,  and writing the test like this avoid usage of null, while still checking in javascript against potential null values (that can happen due to external libraries).

Anyway, there is a problem in the type checking / type guard when using nullish coalescing operator "??".

**Comment by aaronadamsCA** [comment]
FWIW, I long ago reconfigured our ESLint rules to use `eqeqeq: ["error", "smart"]` so that we could use the pattern `if (a.b?.c != null) a.b.c.length;`.
