### ISSUE TITLE
Indexed class method is not inferred correctly

### ISSUE THREAD

**Issue by A5rocks** [microsoft/TypeScript#43714]
# Bug Report

### 🔎 Search Terms

- parameters
- parameter types disappearing
- params
- param types disappearing
- generic key indexing

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about parameters

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.3#code/MYGwhgzhAECiAeYC2AHEBTaBvAUNf0ARuABYAUYAXNAHYCuSh6ATgJTUQAuzAljQObY8BEc3Sc6zGtDAA6TgHsAytz78yrANzD8AXxw7o8AJ4AvU8bKEOqge1oMmzISNHjJ0wrIwDOJbSL6+jgAZnQ0wJw8CtLoiKgYAOrMYCgoLAA8ACrQcZzoNAAmMADW6MYKIXDxaOgAfGQ0yOjUWQA00LJdYMz8ENQACj3N+cwQGQjItQDaWQC6dfYASu5SWcbpEzUYswsuBGISUrToAO7VUxga001I6HNkXbI9fVo4+kA)

### 💻 Code

```ts
class Example {
    blah(a: number): string {
        return a.toString();
    }
}

function exampleWrapper<T extends keyof Example>(name: T, ...args: Parameters<Example[T]>): ReturnType<Example[T]> {
    return new Example()[name](...args);
}
```

### 🙁 Actual behavior

Two errors:
```
Type 'string' is not assignable to type 'ReturnType<Example[T]>'.
```

```
Expected 1 arguments, but got 0 or more.
```

(the first disappears on earlier versions)

### 🙂 Expected behavior

No errors.

Full disclaimer that my typing knowledge is... a little lacking, so I may be missing some covariant or something somewhere. However, I would think the code should work? (and the title / search terms can probably be improved)

**Comment by RyanCavanaugh** [comment]
To start, this function isn't ever quite going to work the way you want, since `T` could be instantiated with a union (for the sake of argument, assume `Example` had multiple methods, since otherwise you wouldn't have written `exampleWrapper` in the first place).

By the same token, the type of the call isn't `ReturnType<Example[T]>`, it's just the flattened type of all the return values of the methods of `Example`. We don't have any mechanisms in place to predict during the evaluation of that call that we should prefer the higher-order form vs the lower-order form, nor could we due to the existence of overloads.

**Comment by A5rocks** [comment]
Oh okay, yep thought it would be similar to that. Thanks for the detailed answer!
