### ISSUE TITLE
Tuple types are spread incorrectly/ inconsistently on unions

### ISSUE THREAD

**Issue by alexrecuenco** [microsoft/TypeScript#43787]
# Bug Report

```typescript
const f = (a: string | Error) => 1;

const g = (c: [string]|[Error]) => {
 const [d, ... rest] = c
 f(d, ... rest) //ok
 f(...c) // error ts(2556)

}

```
### 🔎 Search Terms

Union, spread, bug, arguments, spread operator, tuple

### 🕗 Version & Regression Information

Version 4.2.4

Tested also on typescript@next as well as older versions (3.x.x) using the playground

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about spread operators and tuples

### 🙁 Actual behavior

It is unable to know that when spreading there will always be one element, but it is inconsistent, depending on whether you deconstruct the arguments first yourself or not

### 🙂 Expected behavior

Both ways should work

**Comment by RyanCavanaugh** [comment]
This is only a valid call because the tuple happens to be 1-length, which the first call makes manifest by putting it into a variable.

For the general case of a union of *N*-tuples, we don't treat this as "Try calling it with each of the union elements" because this is potentially combinatorially explosive. The call would only be valid if the reduction of the tuple into a union is valid, and if that's true, there's no reason to write it as `[T] | [U]` instead of `[T | U]`

**Comment by alexrecuenco** [comment]
For reference came up on a test case I was writing, in which I was using "as const". 

Something similar to this

```typescript
const cases = [
  {
    args: ["test"],
    expected: "v",
  },
  {
    args: [/* 's' */], //It knows the tuple length is at least one, because the first form fails with this commented out
    expected: "v",
  },
  {
    args: ["main", "other"],
    expected: "v",
  },
] as const;

const testf = function (a: string, ...b: string[]) {
  return [a, ...b].join("");
};
declare function expect(v: any): any;
cases.forEach(({ args, expected }) => {
  const [a, ...rest] = args;
  expect(testf(a, ...rest)).toBe(expected); //works
  expect(testf(...args)).toBe(expected); //doesnt
});

```
