### ISSUE TITLE
Intl.NumberFormat error when `options` is only parameter.

### ISSUE THREAD

**Issue by carlansley** [microsoft/TypeScript#43801]
# lib Update Request

## Configuration Check

My compilation *target* is `ES2020` and my *lib* is `esnext`.

## Missing / Incorrect Definition

`Intl.NumberFormat` constructor produces error when the optional `locales` parameter is left out, but `options` is present.

## Sample Code

Valid code:

```
Intl.NumberFormat({
  style: 'currency',
  currency: 'USD',
});
```

Produces compiler error: 

```
 error TS2345: Argument of type '{ style: string; currency: string; }' is not assignable to parameter of type 'string | string[] | undefined'.
  Object literal may only specify known properties, and 'style' does not exist in type 'string[]'.

8   style: 'currency',
    ~~~~~~~~~~~~~~~~~
```

## Documentation Link

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat

**Comment by Scharkee** [comment]
Unless I am missing something, the code above is not valid.

The [Mozilla documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#syntax) clearly outlines that the `Intl.NumberFormat` object can be constructed without any parameters, with a `locale` parameter, or with `locale` + `options`. More to the point, [ECMAScript 2022 Internationalization API Specification](https://tc39.es/ecma402/#sec-intl-numberformat-constructor) indicates the exact same parameter usage - either no arguments, `locales`, or `locales` in conjunction with `options`, but just providing `options` is not permitted.

The code above is not functional in JS, since whatever is passed in as the `options` object is attempted to be used as the `locales` parameter, and thus it has no effect. Example: 

```
Intl.NumberFormat({
    style: "currency",
    currency: "USD",
    maximumSignificantDigits:2
}).format(22222222);
```
Expected result: `"$22,000,000"`, actual result:  `"22,222,222"`. The expected result can be obtained by adding a locale such as `"en"` as the first argument.

**Comment by carlansley** [comment]
You're right, I originally discovered this in some unit tests that worked yet `tsc` errored on.  But did not check the options object was being ignored.
