### ISSUE TITLE
Narrowing of an enum using string constants from another enum fails  

### ISSUE THREAD

**Issue by guncha** [microsoft/TypeScript#43839]
# Bug Report

### 🔎 Search Terms

enum narrow string literal constant from another enum

### 🕗 Version & Regression Information

All versions available in the playground, including the Nightly.

This is the behavior in every version I tried, and I reviewed the FAQ for entries about enums.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210426#code/KYOwrgtgBAolDeAoKKoDED2GoF4oCIAzLfAGmVQCEBDAJ1wICM6zEBfRRUSKAOQQooa9PDAB0w8qnRYG4zBnIdEAYwwgAzgBcoIAFx8GYEABNghAJYhgJqNQ12QATwDcnDQHcLWlQAsoABQgAJQC0ir2wHwSdAZavrQYHgTC+G7hkdEKcQlJBAppglBmhNRgADZaekXh6tpQAG4G1g3AIrrp0qjxicnWyTC0ibQB+DAAHgAOwCpaNrrArbSkUB72BFAA1I3BbuxAA)

### 💻 Code

```ts
enum E {
    Foo = "foo",
    Bar = "bar",
}

enum N {
    Bar = E.Bar,
    Foo = E.Foo,
}

const n: N = undefined as any;

switch (n) {
    case N.Bar: throw "Bar";
    case N.Foo: throw "Foo";
    default:
        const v: never = n;
        throw new Error("Expected never, was " + v);

}
```

### 🙁 Actual behavior

Error `Type 'N' is not assignable to type 'never'.(2322)` on the line with `const v: never = n`. 

### 🙂 Expected behavior

Expected `n` to be narrowed to `never` in the `default` block because we already checked all of the enum variants.

**Comment by RyanCavanaugh** [comment]
Enums creating by initializing with nonliteral expressions create branded primitives, not unions, so they don't narrow like this. This is the intended behavior.

**Comment by guncha** [comment]
Thanks, @RyanCavanaugh, I thought this might be as designed. What threw me for a loop was that when I hover `N.Bar` the compiler sees it as `(enum member) N.Bar = "bar" which looks the same as if it was initialized using a literal.

**Comment by kaya3** [comment]
May I ask what the rationale is for preferring branded literals over unions, in cases where the enum value is a non-literal but constant expression? As pointed out, the value is already being determined at compile-time (as seen in the hover hint, and the fact that `Bar` can still be declared as a `const enum`).

My use case is to declare one enum like `enum Foo { FIRST_FOO = 1, ..., LAST_FOO }` and then another like `enum Bar { FIRST_BAR = Foo.LAST_FOO + 1, ... }` in order to ensure that `Foo` and `Bar` remain disjoint and consecutive even if more values are added to `Foo`. But since this prevents narrowing of the union type `Foo | Bar`, it defeats the purpose. My workaround is `if(Foo.LAST_FOO + 1 !== Bar.FIRST_BAR) { throw Error(); }` but this means it's checked at runtime instead of compile-time.

So in my use-case, a union would be better than a branded primitive. Is there an example where a branded primitive is better?
