### ISSUE TITLE
Allow the spread operator for `arguments`

### ISSUE THREAD

**Issue by jbrantly** [Microsoft/TypeScript#4384]
There are multiple parts to this issue: allow spread operator on `arguments` and allow spreaded arguments in function and `super()` calls.

``` typescript
function foo(...args) {
    [...args]; // works
    [...arguments]; // Type 'IArguments' is not an array type.
}
```

If I'm not mistaken, although `arguments` is not _technically_ an array in JS, it can be treated like one for all practical purposes, but I may be missing an edge case here.

Secondly, allow this to be used in function and super calls:

``` typescript
function foo (data: string) {}

function bar(data: string) {
    foo(...arguments);
}

class Parent {
    constructor(foo: string, bar: number) {
    }
}

class Child extends Parent {
    constructor(foo: string, bar: number) {
        super(...arguments);
    }
}
```

These changes would enable common patterns with re-passing parameters for higher-order functions and (I think) it's pretty common for subclasses to have the same construction signatures as their parents.

**Comment by kitsonk** [comment]
While I haven't read the ES spec, that isn't valid ES6.  Firefox complains `SyntaxError: 'arguments' object may not be used in conjunction with a rest parameter`.

**Comment by jbrantly** [comment]
Thanks @kitsonk. I did some reading and testing this morning and here is what I found. Using FF as a reference implementation:

```
> (function(...args) { return [...args] })(1, 2)
  Array [ 1, 2 ]
> (function(...args) { return [...arguments] })(1, 2)
  SyntaxError: 'arguments' object may not be used in conjunction with a rest parameter
> (function() { return [...arguments] })(1, 2)
  TypeError: arguments[Symbol.iterator] is not a function
> (function() { return [...Array.from(arguments)] })(1, 2)
  Array [ 1, 2 ]
```

Based on this and my reading of the spec, you can't use the spread operator on `arguments`. There are workarounds, namely:

```javascript
// to do this
function bar(data) {
    foo(...arguments);
}

// you can either do this
function bar(...args) {
    [ data ] = args;
    foo(...args);
}

// or this
function bar(data) {
    foo(...Array.from(arguments))
}
```

Unfortunately using `...args` breaks any sort of static checking on concrete arguments (assuming you wanted some) and it would likely be very hard for TypeScript to somehow model this:

```typescript
function foo (data: string) {}

function bar(data: string) {
    foo(...Array.from(arguments));
}
```

So based on that I'm going to close this. Sorry for the noise.

**Comment by Izhaki** [comment]
@jbrantly 

Not sure why you have `data: string` in your signature. This works:

```
function bar() {
    foo(...Array.from(arguments));
}
```

**Comment by Izhaki** [comment]
At any rate, not sure why this ticket is closed.

Why is this not valid ES6:

```
function bar() {
    foo( ...arguments );
}
```

or just this:

```
function bar() {
    foo(arguments );
}
```

Why reconstruct and deconstruct `arguments`?

**Comment by theseyi** [comment]
I think FF has corrected this issue, the examples you provided actually work now @jbrantly 

Also I think the spec actually reads that the arguments object is an `iterableObject` which means it can be spread.
http://www.ecma-international.org/ecma-262/6.0/#sec-functiondeclarationinstantiation

This issue was raised on [SO](https://stackoverflow.com/questions/34614653/is-the-arguments-object-supposed-to-be-an-iterable-in-es6) and the relevant part of the spec:

> If argumentsObjectNeeded is true, then
If strict is true or if simpleParameterList is false, then
Let ao be [CreateUnmappedArgumentsObject](http://www.ecma-international.org/ecma-262/6.0/#sec-createunmappedargumentsobject)(argumentsList).
Else,
NOTE mapped argument object is only provided for non-strict functions that don’t have a rest parameter, any parameter default value initializers, or any destructured parameters .
Let ao be [CreateMappedArgumentsObject](http://www.ecma-international.org/ecma-262/6.0/#sec-createmappedargumentsobject)(func, formals, argumentsList, env).

Can this issue be re-opened?

**Comment by mhegazy** [comment]
This should be working as intended using `--downlevelIteration`.
