### ISSUE TITLE
infer `err` in `catch(err) {}` as `unknown`

### ISSUE THREAD

**Issue by gerardolima** [microsoft/TypeScript#43960]
# Suggestion

I think the inferred type for `err` in `catch (err) { }` should be `unknown`, which it _is_, instead of `any` which is unsafe and highly discouraged. `unknown` is safer and provides better semantics; I really don't understand why this is not the default for tsc.

## 🔍 Search Terms

catch exception type inference infer unknown any

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Infer the type for `err` in `catch (err) { }` as `unknown`

## 📃 Motivating Example

This is valid Typescript 4.2.3 code as shown [here](https://www.typescriptlang.org/play?#code/C4JwngBA3hwBYgPYHcIDsCmqCiIkgAoBKCAXwgGMBDYCuAjPEmCxNAZ0QBsMA6LxAHMGeXgAdEwGohKkAUEA) 
```ts
try { throw new Error() } catch(err) { console.log(err.potato) }
```

## 💻 Use Cases

What do you want to use this for?

> Improve type safety to `catch` blocks. 

What shortcomings exist with current approaches?

> `catch(err) {}` infer the type of err as `any`
 
What workarounds are you using in the meantime?

> `catch (err: unknown) {}`

**Comment by whzx5byb** [comment]
See https://github.com/microsoft/TypeScript/issues/41016

**Comment by gerardolima** [comment]
hey, @whzx5byb, #41016 advocates for a compiler flag to enable this behaviour. I advocate this to be the _default_ behaviour. Other than that, it's the same. Should I close this issue, then?

**Comment by whzx5byb** [comment]
I think this should not be the default behavior since it would bring breaking changes.

**Comment by MartinJohns** [comment]
@gerardolima Why do you believe changing the **default** type to a more restrictive one won't be a breaking change?

**Comment by gerardolima** [comment]
hey, @MartinJohns, I think this would enforce correct type checks on _optimistic code_. Nevertheless, this issue was flagged as duplicate (I think related to #41016).

**Comment by Stirfry70** [comment]
Not sure what you mean?Sent using the mobile mail appOn 06/05/2021 at 2:10 PM, Gerardo Lima wrote:
                
            
            
                
                    From: "Gerardo Lima" ***@***.***>Date: 6 May 2021To: "microsoft/TypeScript" ***@***.***>Cc: "Subscribed" ***@***.***>Subject: Re: [microsoft/TypeScript] infer `err` in `catch(err) {}` as `unknown` (#43960)
                
                
hey, @MartinJohns, I think this would enforce correct type checks on optimistic code. Nevertheless, this issue was flagged as duplicate (I think related to #41016).

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/microsoft/TypeScript/issues/43960#issuecomment-833745897",
"url": "https://github.com/microsoft/TypeScript/issues/43960#issuecomment-833745897",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
