### ISSUE TITLE
Initial build mode build emits twice

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#43995]
From https://github.com/microsoft/TypeScript/issues/42173#issuecomment-833148607

In the course of investigating #42173, I noticed that a clean build of the largest project spent 50 seconds on emit.  I picked out the slowest files and noticed that each occurred twice.  It turns out that `updateShapeSignature` triggers a separate emit from the real one (fortunately, with no file writing), which accounts for 22 seconds of the emit time.  Note that this was with TS 4.2 - 4.3 skips signature computation on a clean build.

It seems like we could potentially realize a very significant perf win if we could combine the two emit passes.  I believe @sheetalkamat has already been thinking about ways to do this.

**Comment by sheetalkamat** [comment]
Copying this from https://github.com/microsoft/TypeScript/pull/49156#issuecomment-1151628840


I am having hard time reasoning about this change. 
There are three places currently doing declaration emit/transforms:
1. Builder: To get signature
2. DeclarationDiagnostics: Does only transform and gets error
3. Actual d.ts emit

As part of this i am caching either transform or text (preferring text over transform) and declaration diagnostics so we can reuse it.
I am unable to see lot of benefit of this though. Mainly because:
1. By default when we everything is clean and not emitted, the first run: Builder is not going to do signature emit any more (#43314)
2. Change to store signature computed during emit helps with not having big working set for the next iteration: (#48616) so this makes it as if in first build we did d.ts emit so number of files on which d.ts emit would be done to calculate their signature by the builder should be smaller. So perf win is possible only in next edits but that is not huge since the file list is smaller.
3. `noEmitOnError` is only when we really get declaration diagnostics separately so thats the only place we would save d.ts transform cost. 

I havent been able to find repo where this benefits significantly. Numbers remain more or less same.
