### ISSUE TITLE
Prefixed properties should be optional

### ISSUE THREAD

**Issue by hesselink** [microsoft/TypeScript#440]
The pre-declared Console object contains a property `msIsIndependentlyComposed`. It is declared as

```
msIsIndependentlyComposed(element: Element): bool;
```

I think this should be

```
msIsIndependentlyComposed?(element: Element): bool;
```

This way, it is clear (and checked) that this property is non-standard, and might not exist. The same should go for all vendor prefixed properties, since they by definition only exist in one browser.

Migrated from codeplex [issue 1233](http://typescript.codeplex.com/workitem/1233).

**Comment by duanyao** [comment]
@RyanCavanaugh can you reconsider this issue? I think @hesselink's suggestion does has benefit when one wants to implement an interface which contains vendor prefixed API.

Recently our code base was broken due to a tsc upgrade, because we had implemented a polyfill of `DataTransferItem`:

```js
class DataTransferItemImpl implements DataTransferItem {
    constructor(private _dataT: DataTransfer, public kind: string, public type: string, private _data?: string | Blob) {
    }
    getAsString(_callback: Function) {
      _callback(this._data as string || this._dataT.getData(this.type));
    }
    getAsFile(): File {
      return this.kind === 'file' ? (this._data as File || this._dataT.files[0]) : null;
    }
  }
```

However, this code won't compile with tsc 2.2.2, because its `DataTransferItem` has a `webkitGetAsEntry` method:

```js
interface DataTransferItem {
    readonly kind: string;
    readonly type: string;
    getAsFile(): File | null;
    getAsString(_callback: FunctionStringCallback | null): void;
    webkitGetAsEntry(): any;
}
```

So we are forced to add a dummy implementation of `webkitGetAsEntry` to `DataTransferItemImpl`, which is sad. If `webkitGetAsEntry` were optional, this would be a non-issue.
