### ISSUE TITLE
Function union types acting oddly

### ISSUE THREAD

**Issue by sethen** [microsoft/TypeScript#44032]
# Bug Report

There seems to be some interesting behavior when using function type unions.  Basically the idea is to build an object of properties that have functions.  When trying to build functions in this way while using a `Record<string, (data?: T) => { .. }>` I get an error.  It can't seem to detect the parameter is being passed in the function.  It simply tells me that it's not expecting a parameter at all.

### 🔎 Search Terms

generic type function union

### 🕗 Version & Regression Information

This is occurring in version `4.2.4`

### ⏯ Playground Link

[View the code here](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgLIE8CCAxAriBMYAexABV0AHFAbwFgAoZZACgEoAuZG5MKiLgGcwUUAHNkAXwDcjSY0ahIsRCgwAhPASKkK1ADzqAfN0bMWAIwD8XdZ269+QkeIA0yANYR0N5OuQAPsj4ACYQMKAQIVKyDPIMiuDQ8Eho6ADCWoQk5Pz66Sb0TKwIvun2PHzUzqIgYu6UcFBwALZlgcEgYREgUTFyCgww+NmkaTgjOiDsXBgT2jl6tGbMyFAQYLhQIMjDC6TspsWrq+ub20cnV6tVAsgA5HD3K9fxJ-HxjHujOxpZU4YjDM0ppJos8sZLqcNlsdt8piwvD5bGwoddgDBWLdiJikcgALyEh6hcKREL3VFFa7XM6wtHU663Lj3CzPY4MqQvK6fdknWkXKkc5hI1xchlMh6ssWrN4ygYJIZgsYYTJKkD5IH2FX-cEGAr0-lwtUsRrNNpccr0k4YrH8HHIU2tAlE+4knpRClW6mGr1CiX3BBsoXMWWvQYMn2CoWOlqi3nU-2B6UhrkfQa3NI60gAVRAOUM7n1+PGWdy1A6fzVS0BFYyperBViXzVaQAShAEMQoCFSwXkAVDlHkJ2QMI1h2uyFBFx253u-phLV6pm1bn8+pC0YTMWaDJw9C51OANqPe4AXQJJeNbFifIn3cEJ9ZF+Llf20xvXPWh8fAfPl+1a8m3ZH1v0nQRYh5JRklUEEAEkkhUVIhxgYhiGZCwmjZKDEJSNQMgQ5Q8PpTCAC8MNwQRsMGEcxxadBZ3AgCGPvHs1X0DRCJgpB3BVLikIgTVgPoxiHwAOjgdhYhE1jBDEiwWB4VD0MlLCpE-BgZJ-MSEEU5AyIwuBBAeSQbyAA)

### 💻 Code

```ts
interface MyAFunctionType {
  (): { type: string };
}

interface MyBFunctionType<B> {
  (b?: B): { type: string, key?: B | undefined };
}

interface MyCFunctionType<C> {
  (c?: C): { type: string, param?: C | undefined };
}

function MyAFunction(): MyAFunctionType {
    return function() {
        return {
            type: 'a'
        }
    }
}

function MyBFunction<B>(): MyBFunctionType<B> {
    return function(key?: B) {
        if (typeof key === 'undefined') {
            return {
                type: 'b'
            }
        }

        return {
            key,
            type: 'b'
        }
    }
}

function MyCFunction<C>(): MyCFunctionType<C> {
    return function(param?: C) {
        if (typeof param === 'undefined') {
            return {
                type: 'c'
            }
        }

        return {
            param,
            type: 'c'
        }
    }
}

type MyFunctionUnion<B, C> = MyAFunctionType | MyBFunctionType<B> | MyCFunctionType<C>;

function MyRecordFunction<B, C>() {
    const records: Record<string, MyFunctionUnion<B, C>> = {};

    records['a'] = MyAFunction();
    records['b'] = MyBFunction();
    records['c'] = MyCFunction();

    return records;
}

interface MyBInterface {
    foo: 'bar'
}

interface MyCInterface {
    baz: 'bus'
}

const myRecords = MyRecordFunction<MyBInterface, MyCInterface>();

myRecords.a();
myRecords.b({ foo: 'bar' });
myRecords.c({ baz: 'bas '});
```

### 🙁 Actual behavior

TypeScript throws the following error:

`Expected 0 arguments, but got 1.(2554)` when trying to called `myRecords.b` and `myRecords.c` even though the type of `Record<string, MyFunctionUnion<B, C>> = {};` should know the correct types.

### 🙂 Expected behavior

I would expect that TypeScript would know the function parameter type and pick it up.

**Comment by jcalz** [comment]
This is the intended behavior.  

The type `Record<string, MyFunctionUnion<MyBInterface, MyCInterface>>` does not specify which function type is present at which property key.  For all the compiler knows, `myRecords.b` could be a `MyCFunctionType<MyCInterface>`, and so you can't safely call `myRecords.b({foo: "bar"})`.  The only safe way you can call a union of function types is if you pass it a parameter that would work for every single member of the union.  That is, a union of functions accepts an *intersection* of its parameters (see ["improved behavior for calling union types"](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-3.html#improved-behavior-for-calling-union-types)).  In your case, only a no-arg call would work for each of `MyAFunctionType`, `MyBFunctionType<MyBInterface>`, and `MyCFunctionType<MyCInteface>`, so the union of those functions is seen as only having a no-arg call signature.

If you need to keep track of which function type is at which key, then a dictionary of unions is inappropriately wide; you need a subtype like `{a: MyAfunctionType, b: MyBFunctionType, c: MyCFunctionType>}` as [this Playground link](https://tsplay.dev/m02jrw) demonstrates.  If you need to use a union, it should be a [discriminated union](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#discriminated-unions) so that you can inspect the contents of the property to figure out how it wants to be called, as [this Playground link](https://tsplay.dev/wEVKbN) demonstrates.  [I've tried to have this conversation before](https://stackoverflow.com/questions/67325273/typescript-generics-and-union-function-types) but it didn't seem to go well.  Well, hopefully the second time is a charm!

**Comment by sethen** [comment]
> This is the intended behavior.
> 
> The type `Record<string, MyFunctionUnion<MyBInterface, MyCInterface>>` does not specify which function type is present at which property key. For all the compiler knows, `myRecords.b` could be a `MyCFunctionType<MyCInterface>`, and so you can't safely call `myRecords.b({foo: "bar"})`. The only safe way you can call a union of function types is if you pass it a parameter that would work for every single member of the union. That is, a union of functions accepts an _intersection_ of its parameters (see ["improved behavior for calling union types"](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-3.html#improved-behavior-for-calling-union-types)). In your case, only a no-arg call would work for each of `MyAFunctionType`, `MyBFunctionType<MyBInterface>`, and `MyCFunctionType<MyCInterface>`, so the union of those functions is seen as only having a no-arg call signature.
> 
> If you need to keep track of which function type is at which key, then a dictionary of unions is inappropriately wide; you need a subtype like `{a: MyAFunctionType, b: MyBFunctionType<B>, c: MyCFunctionType<C>}` as [this Playground link](https://tsplay.dev/m02jrw) demonstrates. If you need to use a union, it should be a [discriminated union](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#discriminated-unions) so that you can inspect the contents of the property to figure out how it wants to be called, as [this Playground link](https://tsplay.dev/wEVKbN) demonstrates. [I've tried to have this conversation before](https://stackoverflow.com/questions/67325273/typescript-generics-and-union-function-types) but it didn't seem to go well. Well, hopefully the second time is a charm!

That makes a lot of sense, thank you for this explanation!
