### ISSUE TITLE
Unexpected type union

### ISSUE THREAD

**Issue by socketpair** [microsoft/TypeScript#44118]
```typescript
type s = number;
type x1 = { value: string };
type x2 = { count: number }
type StrangeRecord = Record<string, ((state: s, action: x1) => s) | ((state: s, action: x2) => s)>



function getMapped(arg: StrangeRecord) {
    return Object.fromEntries(Object.entries(arg).map(([k, v]) => [
        k,
        (action: Parameters<typeof v>[1]) => v(42, action)
    ]));
}


const data: StrangeRecord = {
    a: (state: s, action: x1) => state + parseInt(action.value),
    b: (state: s, action: x2) => state + action.count,
}

const asd = getMapped(data);

asd.a({ value: 'fff' });
asd.b({ count: 1 });

```

https://www.typescriptlang.org/play?target=7#code/C4TwDgpgBAzlC8UB2BXAtgIwgJwNwChRIoAPARgSgG8oA3AQwBsUIAuWYbASyQHMoAvgSLQSAJko0AxgHsUSYO1SYcgwuGgBlTvT4QAShFnYAJpUPGTAHhicevADRQAFM9v1gbWE-pTgXGSR2cgBKBAA+WDCAHxc3YA8vGB8-AKDSMTD4SJgQ8PwC-AAzeVTAqF4IYABZejBIE2d6bF52bWxdSosZUzCqfChBqGwqlGwkKAB5DAArI2AAOiLsGTQAUQVuCBhnabm-BYhNrm2mlpCFtDrXAG0AaydaAF0syJuBoc+Hj8-BprL0gAFZr0NBVHAwKwiGRFOjhG5kF4ROjOAAsYhS-kCIR+UBeIQIAkKsiQtigJg89DaOj03VMklxVJc7k87GSUF8WPSoWRLOgAGooGBmjAIABJBT-LkLBjMCAhBy4jDseKJNmYtLBTK8hKeKCCzlpBayeTARVE-Aksn0GBmRCVGp1BrOCkJAkFG0mBb0Zw0WUsdgAciKIcDgndnoWGF9UBNCnYFAE7qAA

I don't understand where did it get `x1 & x2` ?!

![Снимок экрана от 2021-05-17 15-24-27](https://user-images.githubusercontent.com/1157412/118474488-90254780-b724-11eb-9004-52d721176143.png)

**Comment by MartinJohns** [comment]
Your function type is `((state: s, action: x1) => s) | ((state: s, action: x2) => s)`. Because TypeScript doesn't know *which* of these two it is, you must provide arguments that match *app* of the arguments. So the argument for `action` is the intersection type `x1 & x2` (not a union type). It's as expected.

**Comment by socketpair** [comment]
1. what is `app of the arguments` ?
2. I still don't understand why it can't be `x1 | x2` instead of `x1 & x2`.

**Comment by MartinJohns** [comment]
> I still don't understand why it can't be `x1 | x2` instead of `x1 & x2`.

Because the function might one that accepts `x1`, or it might be one that accepts `x2`. If the argument is tyepd `x1 | x2`, then you can pass `x1` **or** `x2`, regardless of the actual type of your function. Passing `x2` to a function accepting `x1` would be a bug, and vice versa.

> what is app of the arguments ?

Sorry, my mistake. Auto complete struck and I didn't notice it. I meant **all** of the arguments. In one case it`s `x1`, and in another case it's `x2`. Since TypeScript doesn't know which case you actually have, you must provide an argument that matches all possible options.
