### ISSUE TITLE
Embedded browser interpreter

### ISSUE THREAD

**Issue by dani-h** [Microsoft/TypeScript#4413]
I was wondering if there was any project that allows you to run TypeScript in the browser similar to the stuff CoffeeScript does[1]. This is purely for development and experimental purposes. Setting up compilation or build systems can be annoying for tiny projects.

[1] http://stackoverflow.com/questions/5170473/is-there-a-way-to-send-coffeescript-to-the-clients-browser-and-have-it-compiled

**Comment by DanielRosenwasser** [comment]
I don't know of any specific projects - I think I did this for fun using our compiler API, looking through `script` tags with `type="text/typescript"`. Any tags with a `src` attribute are downloaded through an `XMLHttpRequest`. The problem is it doesn't work the same way as plain JavaScript because of the order in which things are loaded/executed, but CoffeeScript has the same problem.

It's a little easier now than it was then. We've exposed a [`transpile` function](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#a-simple-transform-function) in our compiler API, so you can use that on the contents of your `script` tags and then just `eval` the result, though it's probably not a very production-ready solution.

**Comment by lbguilherme** [comment]
One method to fully mimic the behavior of native `<script>` is to use [`MutationObserver`](https://developer.mozilla.org/en/docs/Web/API/MutationObserver). Whenever a script tag gets added, if it has a `src`, do a synchronous `XMLHttpRequest`, then `transpile` and `eval` in-place. The major drawback is that it will freeze browser rendering, but that's ok for non-production envs. This would keep things like this working:

```html
<script type="text/javascript">
    var js = 5;
</script>
<script type="text/typescript">
    function ts() : string {
        return js;
    }
</script>
<script type="text/javascript">
    console.log(ts());
</script>
```

**Comment by DanielRosenwasser** [comment]
@lbguilherme that's exactly what I was looking for when I first wrote that - thanks for the tip!

But yeah, @dani-h, keep in mind that downloading/compiling in a synchronous manner is not a good idea for production environments because it can lead to a sub-optimal user experience.

**Comment by dani-h** [comment]
@lbguilherme I was looking for a code snippet so thanks! I'm still not sure how to include the lib/tsc.js as it seems to execute and throw an error whenever it's included. Can anyone provide a snippet on how the compiler is included and how it can be used to transpile scripts?
```
Uncaught TypeError: Cannot read property 'args' of undefined
```

I'm guessing this is because of the last line in the file `tsc.js`
```javascript
ts.executeCommandLine(ts.sys.args);
```

@DanielRosenwasser Yeah I had no intention of using it in any production environments, only for playing around with small projects.

**Comment by danquirk** [comment]
@dani-h tsc.js is the actual command line compiler so that's why you're seeing that behavior. You likely want to start with typescript.js and follow some of the examples at https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API

**Comment by dani-h** [comment]
@danquirk Thanks I think I can figure it out from here. If no one wants to add anything else to the discussion feel free to close this issue.
