### ISSUE TITLE
tsc check time step takes too long

### ISSUE THREAD

**Issue by EmadKhella** [microsoft/TypeScript#44146]
I am writing an SPFX solution contains one WebPart and it has multiple components. 
when I try to bundle the solution it takes long time to finish **(20 to 25 mins)**.
After I investigate the bundle steps I found that **tsc subtask** takes around 20 mins to finish, 
### This is the diagnostics 
![image](https://user-images.githubusercontent.com/54295822/118657089-80922580-b82e-11eb-95c3-27f41b5a354b.png)

### I reviewed the tsconfig.json and this is the all compiler options 
![image](https://user-images.githubusercontent.com/54295822/118657368-c3ec9400-b82e-11eb-9baa-30648658e624.png)

Is there any configuration I miss that can decrease check time for type script compilation step ???

**Comment by DanielRosenwasser** [comment]
Looks like while you've got a pretty decently sized project, your check time is way out of proportion. The first thing I would do is ensure that you're seeing consistent behavior when you run the `tsc` executable (i.e. ensure this isn't an issue specific to your build tool).

I would recommend running a performance trace, described here:

https://github.com/microsoft/TypeScript/wiki/Performance#performance-tracing

In addition to that, instead of spending time in Edge/Chrome's tracing view, @amcasey has written a tool to get a quick digest of what statements are causing the biggest slowdown on your project based on the output of TypeScript's `--generateTrace`.

https://www.npmjs.com/package/@amcasey/ts-analyze-trace

If you can provide some information, we might be able to provide some guidance to you on next steps.

**Comment by EmadKhella** [comment]
I ran the ts-abalyze-trace and it shows 5 hot spot components . 
![image](https://user-images.githubusercontent.com/54295822/118934424-b3066480-b98d-11eb-814a-c020b0f87c4a.png)
how can I know what code causing the slowness to fix it ?
Any guidance about code I shouldn't use to decrease check time ?

**Comment by EmadKhella** [comment]
![image](https://user-images.githubusercontent.com/54295822/119085997-2076cb80-ba48-11eb-86f5-7a1046f856fa.png)

Is that can help ?

**Comment by amcasey** [comment]
@EmadKhella That trace appears to be 16 seconds long, but you mentioned above that it was taking 19 minutes.  Assuming the 16 second trace is correct, it's very consistent with having a lot of not-particularly-complicated code.  You could check for subtle sources of slowdown, like importing two different versions of the same package, but there probably isn't a quick and easy way to make things faster.  For what it's worth, your tsconfig settings look good.

If it really is taking 19 minutes, I'd need to see a 19 minute trace to tell you more.

**Comment by EmadKhella** [comment]
After I bundled I run the two commands and show you the trace file. but if you check the diagnostics above you can see that check time takes 1139 second = 19 min. 
how can I show you that on tracing tool?

**Comment by EmadKhella** [comment]
Hi @amcasey 
I bundled the solution "gulp bundle --ship" with compiler options:
 "diagnostics": true
 "extendedDiagnostics": true,
The output diagnostics was that :
![image](https://user-images.githubusercontent.com/54295822/119355471-a9139700-bce8-11eb-9730-00896fa098b1.png)

but when I ran the command 
tsc -p . --generateTrace trace_output --incremental false
it shows that statistics 
![image](https://user-images.githubusercontent.com/54295822/119355777-01e32f80-bce9-11eb-9642-fbdf21a92db9.png)
 
this is the check time I sent in previous screenshot.
Why there is a difference between check time of both ? I assume that generate track is reading from bundled files.!!!!!

**Comment by amcasey** [comment]
I would guess that the bundler you're using (webpack?) is calling TypeScript programmatically, via the API, rather than invoking tsc.js, as you are manually.  Unfortunately, the tracing functionality is still quite new and it has not yet been hooked up to the API - only to tsc.js and tsserver.js.  As a result, I don't know of a way to get a trace from a bundler.

Looking at the two different diagnostic outputs, I notice that they don't have the same file count.  I think that this probably indicates that they are not using the same version of TypeScript (though they might just be configuring it differently).  The next thing I would check is which version of TypeScript your bundler is using (probably by looking in its package.json file).  If you find that it's different from the version you're running in your tsc command, you can try running your tsc command with the version from the bundler to see if it also shows a 19 minute check time.

**Comment by EmadKhella** [comment]
@amcasey  Thanks for the second point you listed. SPFX is using one of packages " @microsoft/rush-stack-compiler-3.3@0.1.6" and it used Typescript v3.3 so I updated it to latest version "@microsoft/rush-stack-compiler-3.9" which use TS version 3.9 .
After that check time takes 31 seconds as it is shown using generateTrace package. 

Thanks for your help
