### ISSUE TITLE
tsc incorrectly adds .ts file to the build

### ISSUE THREAD

**Issue by freshp86** [microsoft/TypeScript#44185]
Consider the following tsconfig.json file

```json
{
  "compilerOptions": {
    "module": "esnext",
    "target": "esnext",
    "noEmitOnError": true,
    "allowJs": true,
    "rootDir": "src",
    "outDir": "tsc"
  },
  "files": [
    "src/foo.js",
    "src/bar.js"
  ]
}
```

The 'src' folder has 3 files as follows
```js
// src/foo.js
import {bar} from './bar.js';
console.log(bar());
```
```js
// src/bar.js
export function bar() { return 'bar'; }
```

```ts
// src/bar.ts
export function bar(): string { return 'bar'; }
```

Note that the `src/bar.ts` file **is not** part of the `files` field in tsconfig.json, and instead `src/bar.js` **is** part of the build. 

Running `tsc --explainFiles` reveals that `src/bar.ts` is incorrectly picked up by tsc, in addition to `src/bar.js`, as follows:

```
...
src/bar.ts
  Imported via './bar.js' from file 'src/foo.js'
src/foo.js
  Part of 'files' list in tsconfig.json
src/bar.js
  Part of 'files' list in tsconfig.json
```

`src/bar.ts` should be completely ignored, since the equivalent JS file is explicitly part of `files`. This can cause problems, for example `src/bar.ts` could be a stale file containing various errors, and having it picked up could lead to the build failing unexpectedly (facing this issue in the Chromium codebase as part of https://crbug.com/1189595).

Moreover, even if `src/bar.ts` is explicitly excluded with the `excludeFiles` option, it still gets picked up by tsc.

**Comment by MartinJohns** [comment]
When you have the same filename with two extensions (`.js` and `.ts`), then TypeScript will favor the `.ts` file because the `.js` file is considered a build artifact. That you don't have the `.ts` file part of the `files` array is irrelevant. TypeScript will not only consider the files listed here, but also all includes, and you're including from the `bar` module (which is found via `bar.ts`).

This is working as intended.

**Comment by freshp86** [comment]
Thanks for the quick response.

> TypeScript will favor the .ts file because the .js file is considered a build artifact. 

This would make more sense if rootDir and outDir pointed to the same folder. When using a different outDir folder, then I think it is safe to assume that the .js file is not a build artifact, no?

**Comment by freshp86** [comment]
Also note that src/bar.ts is **not** added to the build, if instead of a relative `./bar.js` URL an absolute `/bar.js` URL is used. This also suggests to me that the current behavior is somewhat arbitrary and possibly a bug.

**Comment by RyanCavanaugh** [comment]
The intentional design here is that the `files` list does not interact with module resolution.

**Comment by freshp86** [comment]
> The intentional design here is that the files list does not interact with module resolution.

Ack. Unfortunately this makes the behavior of tsc less predictable, where it can fail for one developer but not for another, because of the presence of stale files, even though they are both synced to the same revision of a shared project (in this case Chromium). I suppose the only solution is to preemptively detect and delete such files before spawning tsc.

**Comment by fatcerberus** [comment]
One of the more technical issues here, as far as I can tell, is that an explicit `import "./foo.js"` _must_ be able to pick up `./foo.ts` as well because TS doesn't (currently) rewrite import specifiers, but ESM environments--both Node and browser--require the extension to be present on file-based imports.  So with that in mind, the obvious choice is to prefer the `.ts`  if it's present.
