### ISSUE TITLE
Impossible to define static 'length' function on class

### ISSUE THREAD

**Issue by hesselink** [Microsoft/TypeScript#442]
The following typescript program is accepted:

``` typescript
class C {
    static length ()  { return "twelve"; }
}
```

However, in the generated code:

``` javascript
var C = (function () {
    function C() {
    }
    C.length = function () {
        return "twelve";
    };
    return C;
})();
```

Here, an attempt is made to assign to the `length` property of a function. This doesn't work (at least in Firefox and Chrome), causing subsequent calls of `C.length()` to crash. Perhaps calling a static class function `length` should just be disallowed?

Migrated from codeplex [issue #1260](http://typescript.codeplex.com/workitem/1260).

**Comment by tinganho** [comment]
I don't think the properties `name`, `caller` and `length` are doable. They are read-only properties and can't be overridden. All assignments to them will be ignored.

**Comment by basarat** [comment]
@tinganho agreed

**Comment by lazutkin** [comment]
Ok, but since people catch this kind of error from time to time I think that TS should notify them about doing something wrong. It because properties like `name` or `length` are so natural to keep in mind that people will try to redefine them again and again.

**Comment by Ghayyas** [comment]
May be because Lengh, Name  are Already Defined.

**Comment by cjbarre** [comment]
I'm going to try and work on this. Apart from what has already been mentioned, are there more property names that shouldn't be allowed?

So far I see:
length, name, arguments, caller

What exactly should happen when someone tries to set a static property with one of the forbidden names? Compiler error? Visible warning to the user?

I'm new to this so if I'm missing something, then some guidance would be appreciated. :+1:

**Comment by zerkms** [comment]
Why not compile

```ts
class C {
    static name = 'something';
    static arguments = 'args';
    static caller = 'caller';
}

console.log(C.name); // 'C'
console.log(C.arguments); // null
console.log(C.caller); // null
```

to something like

```js
var C = (function () {
    function C() {
    }
    
    C.__statics = {
        name: 'something',
        arguments: 'args',
        caller: 'caller'
    };

    return C;
})();
console.log(C.__statics.name); // 'something'
console.log(C.__statics.arguments); // 'args'
console.log(C.__statics.caller); // 'caller'
```

**Comment by basarat** [comment]
Question came up on stackoverflow as well : http://stackoverflow.com/a/34644236/390330 :rose:

**Comment by RyanCavanaugh** [comment]
@zerkms please don't post the same comment in two places; it's confusing.

You can't arbitrarily sometimes rewrite names in a structural type system.

Consider some code like this
```ts
interface HasName {
  name: string;
}
class Foo {
  static name = 'fooClass';
}
let bar: HasName = { name: string };
let q = Math.random() > 0.5 ? Foo : bar;
console.log(q.name);
```

**Comment by zerkms** [comment]
@RyanCavanaugh that's a fair example, indeed (I don't develop on TS, but gosh - its type system is weird as soon as it treats this code as valid).

**Comment by AlexanderMattoni** [comment]
If it's not possible to transpile them without risk, perhaps we should just disallow them?

**Comment by basarat** [comment]
> If it's not possible to transpile them without risk, perhaps we should just disallow them?

Definitely not changing the transpile, just making it a compile error :rose:

**Comment by RyanCavanaugh** [comment]
> [...] perhaps we should just disallow them?

Some enterprising developer should send us a PR! :wink:

**Comment by LPGhatguy** [comment]
Some of these properties are still overridable with `Object.defineProperty` when targeting ES5. `arguments` and `caller` aren't able to be redefined, but I was able to redefine `name` in at least Chrome and Firefox.

Is there a comprehensive list of properties where this is a problem? How many of them are overridable with `Object.defineProperty`? I think that 'name' is a common enough property name to have a special case for.

**Comment by nicolo-ribaudo** [comment]
Why not use `Object.defineProperty`?

e.g.
```ts
class C {
    static length() { return "twelve"; }
}
```
would be transplied to something like
```js
var C = (function () {
    function C() {
    }
    Object.defineProperty(C, "length", {
        value: function () { return "twelve"; },
        writable: true
    });
    return C;
}());
```

**Comment by basarat** [comment]
@nicolo-ribaudo That does indeed work. My opinion: but **I** would rather see an error instead of such a transpile. TypeScript generally leans on the side of graceful error instead of *fixing JavaScript* :rose:

**Comment by zerkms** [comment]
> TypeScript generally leans on the side of graceful error instead of fixing JavaScript

Is not the whole idea of TS is to fix the JS by filling the gaps it cannot and will never be able to.

**Comment by basarat** [comment]
> Is not the whole idea of TS is to fix the JS by filling the gaps it cannot and will never be able to.

Yes. But by understanding how JavaScript works. Take an example of `null` and `undefined`. TypeScript choses to understand both (instead of consolidating it into a single thing like Dart does https://www.dartlang.org/docs/synonyms/). TypeScript gives errors (instead of fixing it in transpile) if you use the wrong JavaScript pattern :rose:

> My opinions are my own and not endorsed by anyone but me :rose:

**Comment by about-code** [comment]
Meanwhile ES6/2015 native support has landed in Chrome and Firefox. If we observe how these handle the issue natively then it comes close to what @nicolo-ribaudo and I have proposed (see #9778). 

With respect to what @tinganho has written earlier about the readonlyness of `name`, `length` and `caller` we can observe for the native implementations that the properties are writable on a constructor function once we have defined either of those as a static class member (feel free to review or modify my [recent warnings on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name) regarding dangerous assumptions about `Function.name` for getting a class name, because of this).

So using `Object.defineProperty` as suggested by @nicolo-ribaudo would emulate the native behavior accurately. A thing we need to considered is that some older but ES5 compatible browser versions had set the properties to be `configurable: false`. So trying to make them `writable: true` will fail for them (e.g. see configurability of [Function.name](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name))

To sum things up, my take on the issue were:
-  We can't use `Object.defineProperty()` for compile-target `es3`. Without `Object.defineProperty`, running ES3 code in an ES5 environment, though, would hit the read-only problem. Therefore we need a compile error for target `es3`
- compile it with `Object.defineProperty()` and `writable: true` for compile-target `es5` and issue a warning/error stating that using these property names can cause errors in browsers `x of version <= y`suggesting that, if these browsers must be supported, the safest option were to choose another name.
- if you absolutely don't want people to use the properties, generate a compile error for either target.

Independent of the compile output I think any kind of additional message would be better than how the situation is today (TS 1.8.10) where we get no hint at all about potential problems with the compiler output.

**Comment by about-code** [comment]
@RyanCavanaugh: could you please revisit this issue for milestone TS 2.0.1. Solution seems straight forward but depending on which option you choose emitter output may need to change (see my previous comment). Release of TS 2.0 then may be best to include the fix.

**Comment by kitsonk** [comment]
The tags on the PR indicate that the TypeScript team, which have limited resources, are leaving this open to the community to address.  If you want this issue addressed, someone in the wider community will have to tackle it until the TypeScript core team feel they have sufficient room in the backlog to put it into a release (which likely would be a long long time).

**Comment by about-code** [comment]
@kitsonk Thank you for explaining the PR label. I think I understood that. What I suggested was to reevaluate whether its still the right way to handle the issue. Static class properties called *name* or *length* are not so unlikely to happen and TS produces errorneous output for that. Hence I wouldn't even call the issue and "edge case".

Apart from putting ever new features into the language getting basic features right should be top priority, shouldn't it? I consider static properties being at the core of the language and even if there aren't pull requests yet, solutions for the issue have been presented in this thread.

Nevertheless, I will evaluate whether I can provide a PR but I must admit that I am not yet that knowledgeable about TS sources and I am afraid TS 2.0 will be released before.

**Comment by about-code** [comment]
This issue is a bit more complicated than I originally thought. For the time being I withdrew my PR. I think I need more discussion. 


| member declaration | target `es3`, `es5`                    | target  `es6` |
|--------------------------|------------------------------------------|-------------------|
| `static prototype`     |     configurable: **no**, writable: **no**   | configurable: **yes**, writable: **no**
| `static prototype`     |     configurable: **no**, writable: **no**   | configurable: **yes**, writable: **no**
| `static prototype`     |     configurable: **no**, writable: **no**   | configurable: **yes**, writable: **no**
| `static prototype`     |     configurable: **no**, writable: **no**   | configurable: **yes**, writable: **no**
