### ISSUE TITLE
Is this inconsistent? typeof return statement.

### ISSUE THREAD

**Issue by xLama** [Microsoft/TypeScript#4427]
```
class  A {}

    function foo(): A {
        return A; // No error. Why?
    }

    function foo2(): A {
        return new A(); // Ok.
    }

    function bar(): typeof A {
        return A; // Ok.
    }

    function bar2(): typeof A {
        return new A(); // Error. It´s ok.
    }
	
 function baz() { // Inferred typeof A
        return A;
 }
	
	
var A_A = foo(); // Inferred A
var instance = new A_A(); // Error beause it is not typeof A


var A_B = bar(); // Inferred typeof A
var instance = new A_B(); // Ok

```

I think this can be confused.

**Comment by danquirk** [comment]
The body of ```foo``` has no error because ```A``` has no members. The constraint on the return type of ```foo``` is then ```{}```. Add a member to ```A``` and you'll see an error there as you expected. Does the rest of it make sense then? Returning ```A``` in an expression is returning the constructor function for the class, which is denoted in type position by ```typeof A```.
