### ISSUE TITLE
subset type is not assignable to "partial" superset type

### ISSUE THREAD

**Issue by yaquawa** [microsoft/TypeScript#44286]
# Bug Report
Here is an example to show what I mean:

```ts
class Foo<A extends {a:string},B extends A>{
    b(data:Partial<B>){

    }
    
    a(data:A){
        this.b(data) // error!!
    }
}



// However, this WILL work, does this is a bug?
class Foo2<A,B extends A>{
    b(data:Partial<B>){

    }
    
    a(data:A){
        this.b(data)
    }
}
```

But when I provide a literal object type, it works too. so strange..
```ts
class Foo<A extends {a:string}>{
    b(data:Partial<{a:string,b:string}>){

    }
    
    a(data:A){
        this.b(data)
    }
}
```
### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD28A8BBaBTAHgF3QOwBMYBvMALgmwCcBLPAcwF8AaAIQx3yOhQD5iAUNGHQARgAoCYbOQAKYKthpgQSVrwCUgoSMY7h+6GEnTyKLYZHRsACxoQAdBKkyNhvXoEDQkGAngATKhsHLiEMHyCVs6mZPKKyqrqFu6GhsYuZhZWVrb2TiauqYxAA)

**Comment by DanielRosenwasser** [comment]
There's no telling what `A` and `B` are so you can never be sure that it should work.

```ts
let foo = new Foo<{ a: string }, { a: string, b: boolean }>();

let obj = {
    a: "hello",
    b: "world", // notice, this is a 'string', not a 'boolean'.
};

foo.a(obj); // oops! this would be allowed
```

**Comment by DanielRosenwasser** [comment]
I guess the real weirdness that you're observing is that we enforce the check for generics, but not for concrete object types.

**Comment by Stirfry70** [comment]
Thank goodness I was just trying to get a hold of my boy

**Comment by Stirfry70** [comment]
[]()

**Comment by RyanCavanaugh** [comment]
@ahejlsberg any thoughts/justification?

**Comment by ahejlsberg** [comment]
Given type parameters `A` and `B extends A`, the reason `A` is assignable to `Partial<B>` is that we treat a type parameter with no constraint as having the constraint `{}`, and `{}` is assignable to any partial type. When `A` as any other constraint, `A` is not assignable to `Partial<B>`, effectively for the reason that `A` is not assignable to `B`.

Aside from the `{}` being assignable to any partial type, the reason `A` is not assignable to `Partial<B>` is that `B` might give properties more specific types. For example, the assignment is unsafe when `A` is `{ a: string }` and `B` is `{ a: 'foo' }`. It is generally safe only for subtypes that _add_ more properties, such as when `A` is `{ a: string }` and `B` is `{ a: string, b: boolean }`. So that explains why it works for certain literal types.

**Comment by Stirfry70** [comment]
- [[**_[@@![image](https://user-images.githubusercontent.com/46066539/120909782-77c29180-c62d-11eb-9eea-61bf063f5f8e.png)]()_**]()]()

**Comment by Stirfry70** [comment]
> # Bug Report
> 
> Here is an example to show what I mean:
> 
> 
> 
> ```ts
> 
> class Foo<A extends {a:string},B extends A>{
> 
>     b(data:Partial<B>){
> 
> 
> 
>     }
> 
>     
> 
>     a(data:A){
> 
>         this.b(data) // error!!
> 
>     }
> 
> }
> 
> 
> 
> 
> 
> 
> 
> // However, this WILL work, does this is a bug?
> 
> class Foo2<A,B extends A>{
> 
>     b(data:Partial<B>){
> 
> 
> 
>     }
> 
>     
> 
>     a(data:A){
> 
>         this.b(data)
> 
>     }
> 
> }
> 
> ```
> 
> 
> 
> But when I provide a literal object type, it works too. so strange..
> 
> ```ts
> 
> class Foo<A extends {a:string}>{
> 
>     b(data:Partial<{a:string,b:string}>){
> 
> 
> 
>     }
> 
>     
> 
>     a(data:A){
> 
>         this.b(data)
> 
>     }
> 
> }
> 
> ```
> 
> ### ⏯ Playground Link
> 
> 
> 
> [Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD28A8BBaBTAHgF3QOwBMYBvMALgmwCcBLPAcwF8AaAIQx3yOhQD5iAUNGHQARgAoCYbOQAKYKthpgQSVrwCUgoSMY7h+6GEnTyKLYZHRsACxoQAdBKkyNhvXoEDQkGAngATKhsHLiEMHyCVs6mZPKKyqrqFu6GhsYuZhZWVrb2TiauqYxAA)
> 
> 
> 
> 
> 
>

**Comment by RyanCavanaugh** [comment]
@Stirfry70 please stop posting noise comments to our repo. We will be forced to block you if this continues.
