### ISSUE TITLE
Meta: Renaming default branch to `main` this weekend

### ISSUE THREAD

**Issue by RyanCavanaugh** [microsoft/TypeScript#44323]
Heads up to contributors: We'll be renaming the default branch over the weekend to `main`. We believe we have the correct automation in place to update existing PRs, but you may need to update any personal scripts or muscle memory on your side to account for the change. Let us know if you encounter any technical issues with this.

Happy coding!

**Comment by orta** [comment]
GitHub says this is going to close 3 open PRs, I assume they either have all their commits upstream'd  but are still open, but will monitor the notifications and re-open (and re-target) them if it makes sense

![Screen Shot 2021-05-31 at 10 40 43 AM](https://user-images.githubusercontent.com/49038/120174308-da1a2d00-c1fc-11eb-9abc-a8b0a528364b.png)

**Comment by orta** [comment]
Used the GitHub API to find the 3 PRs which the migration auto-closed after the fact (I didn't get emails because they were  my actions):

- https://github.com/microsoft/TypeScript/pull/38518 @rbuckton 
- https://github.com/microsoft/TypeScript/pull/34941 @sandersn 
- https://github.com/microsoft/TypeScript/pull/33441 (me)

I checked via the API these are PRs which did _not_ have the 'Allow maintainers to push to this branch' flag set on the PR which means GitHub reasoned that they couldn't be  changed upstream. I'll leave a comment in them.

**Comment by orta** [comment]
I've got https://github.com/microsoft/TypeScript/pull/44347 validating our bot commands

**Comment by orta** [comment]
Looks like build artifacts are not being passed between devops jobs as expected, _they_ probably have master hardcoded as an arg somewhere - [correctly uploads](https://typescript.visualstudio.com/TypeScript/_build/results?buildId=104379&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=96da07f6-0fa7-579e-8e42-3e66cb7a1abe) then [can't be found](https://typescript.visualstudio.com/TypeScript/_build/results?buildId=104379&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=08d41a1b-6013-5b01-b962-661a2fb402c0) by our scripts.

**Comment by orta** [comment]
I'll keep this open for a week to give a central place for notes, but it all seems to be transferred over fine.

**Comment by orta** [comment]
Not all CI systems are running on PRs:

![Screen Shot 2021-06-01 at 3 49 37 PM](https://user-images.githubusercontent.com/49038/120343904-01522680-c2f1-11eb-8e78-669cf8039808.png)

**Comment by RyanCavanaugh** [comment]
Done and things seem to be running smoothly now
