### ISSUE TITLE
What is the correct way to type a "Dictionary" (Record/Object does not work)

### ISSUE THREAD

**Issue by edaqa-uncountable** [microsoft/TypeScript#44361]
I'm trying to find the correct way to type a logical Dictionary object in TypeScript. The `Record` and `Partial` types combined do not work the way I want them to -- my "want" is to behave like a common dictionary/map available in other languages.

Given a `dict: Dictionary<K,V>` I want:

- `dict.key` / `dict[key]` to have the type `undefined|V` since the key may not exist
- `Object.values(dict)` to have the type `Iterable<V>`
- `Object.entries(dict)` to have the type `Iterable<[K, V]>`
- `Object.keys(dict)` to have the type `Iterable<K>`

`Record<K,V>` does not work, since accessing by key always yields the value type `V`, even though the key may not exist.

`Partial<Record<K,V>>` does not work, since then `Object.values` returns a type of `Iterable<V|undefined>`

How can I properly define a `Dictionary` type that works with standard JS objects?

It's fine if I have to override definitions of `Object.values/entries/keys` for a Dictionary type. I'm not clear on how I override `Object` functions for specific types only.

_Note: I'm aware of a lot of the history of these types here. I'm interested in finding a solution that works. The above Dictionary is a common typing paradigm available in many languages, so I would like it to be possible in TypeScript._

----

I've migrated this from my [Stack Overflow Post](https://stackoverflow.com/questions/67717350/correct-way-to-handle-a-partial-record-with-iteration-not-showing-undefined-in-t) since I believe it's a critical issue with TypeScript. It repeatedly comes up in code I work on, and I'm unable to give answers to new TypeScript users as to what the solution is. We're constantly required to make type assertions on type-correct record code.

**Comment by whzx5byb** [comment]
You can use `Record<K,V>` with `noUncheckedIndexedAccess: true`.
See: https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!

**Comment by edaqa-uncountable** [comment]
@RyanCavanaugh The reason I posted it here is because it feels more like a bug in the way Record and Object are handled and despite lots of searching I've been unable to find any solution. I've left the question phrasing to be clear in the intent, but underlying it I still feel as though there is a deficiency here that needs to be "officially" addressed.

**Comment by RyanCavanaugh** [comment]
@edaqa-uncountable Being unable to find a satisfactory solution to a particular pattern is not a bug, or even per se deficit. Please note that we have templates here that attempt to steer you toward actionable issue reports.

**Comment by edaqa-uncountable** [comment]
> You can use `Record<K,V>` with `noUncheckedIndexedAccess: true`.
> See: https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess

This unfortunately goes well beyond unchecked access for records, applying to all arrays as well (even in situations where the length is properly checked).

**Comment by TobiasJacob** [comment]
I think Type Script needs something like this. I'm trying to implement a 

```javascript
Record<string, string | undefined>
```

type for a field where it is likely that keys will be missing, so the user has to check for undefined when using this certain field. Other Records in my program are unlikely to return undefined, it's just one that needs special treatment.

**Comment by acnebs** [comment]
I think it would be more correct if there were different options for Objects/records vs Arrays rather than just having `noUncheckedIndexAccess` apply to everything that can be accessed by index, as the patterns for each are distinct enough  (due to type limitations) that I would argue the existing behavior is wrong.

For instance, I don't think [this example](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true#code/MYewdgzgLgBAtgTwMpQE4EswHMYF4YBEEIcAplABaY4Du6lIArrAIYwAmIANly6jBHRYwMTKKgEAUJNCRYYUjRQZseeMjTUAdBAAOXegAoCAEgIBKANoAGALrTZ0GL2gAZclFKoAQqQBmIKikACLcvKhIQiL4Ckqa2JaxytpcpNiUMAC0MACMtkA) should result in any type errors, but it does.

```ts
// noUncheckedIndexAccess: true

const myString = "something without a dollar sign in it"

const newString = myString.split("$")[0]

const lastLetterBeforeDollarSign = newString[newString.length - 1]
```

`newString` is *never* actually `undefined`, but the compiler tells me it might be. I don't want errors like this in my code, but I would like to see instances where I am accessing an object by index and *assuming* it is defined even if it may not be.
