### ISSUE TITLE
What does using a `const` assertion after a `const` string declaration do?

### ISSUE THREAD

**Issue by ugultopu** [microsoft/TypeScript#44391]
Sorry for asking a question, tried both [Stack Overflow](https://stackoverflow.com/questions/67808865/what-does-using-a-const-assertion-after-a-const-string-declaration-do) and Discord but none worked.

What's the difference between:

```
const CONSTANT = 'VALUE';
const object = { property: CONSTANT };
```

and

```
const CONSTANT = 'VALUE' as const;
const object = { property: CONSTANT };
```

In both cases, the type of `CONSTANT` is inferred to be `"VALUE"` (instead of as `string`). However, only in the second case, the type of `object` is inferred to be:

```
{
    property: "VALUE";
}
```

Instead of as:

```
{
    property: string;
}
```

I'm wondering why this is the case, even though in both examples, the type of `CONSTANT` is inferred to be `"VALUE"`.

**Comment by MartinJohns** [comment]
> Sorry for asking a question, tried both Stack Overflow

You asked only **one hour ago**. Have some patience.

**Comment by ugultopu** [comment]
The docs give an example like:
```typescript
// Type '"hello"'
let x = "hello" as const;
```
In my case, it is:
```typescript
// Type is already '"hello"' even without the const assertion.
const x = "hello";
```
I don't know how more I can clarify this question. I think it is very clear. Just read the first post again please.

**Comment by MartinJohns** [comment]
Because you're using const. The example uses let.

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
