### ISSUE TITLE
Type narrowing as documented is broken

### ISSUE THREAD

**Issue by Craigfis** [microsoft/TypeScript#44450]
# Bug Report
Following the example of type narrowing in the documentation here: https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates

The code just doesn't work as documented. In the else clause below, pet is treated as never type.

### 🔎 Search Terms
type narrowing
### 🕗 Version & Regression Information

All versions I've tried in Playground exhibit this (3.*, 4.*, nightly)

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?jsx=0&ts=4.3.2&strict=true#code/C4TwDgpgBAYglgZwBZQLxQN5QQdzgWwC4oAKASjQD4oA3AezgBMBfAbgChRIoAhOAJ0ZpMUAGYAbEMXJVaDFh1EBXAHYBjYHDoqoieMhKRgxfSgA+vAYzLEjuhLEQoM7KFH4RgS-jsOeoAIYOpmQAdLgEUACEqOiqjBCicCoQjBzM7GraCMBQduhYEUSkFKjUGMxs7OxwoqR6Tn7AZBQubkbhePjk6VAQ4gjQbXmeoRIgPezMQA)

### 💻 Code

```
type Fish = { swim: () => void};
type Bird = { fly: () => void};
function isFish(pet: Fish | Bird): pet is Fish {
  return (pet as Fish).swim !== undefined;
}
const pet = { swim: () => {}};

if (isFish(pet)) {
  pet.swim();
} else {
  pet.fly();
}

```
### 🙁 Actual behavior

The code doesn't work as documented. In the else clause below, pet is treated as never type.

### 🙂 Expected behavior

In the else clause, pet should be a Bird type.

**Comment by Craigfis** [comment]
OK, it looks like it is because I have defined pet statically here rather than use a function per the docs.

**Comment by ArkaneMoose** [comment]
Since you defined `pet` as an object literal, its type matches exactly what it was defined as, specifically `{ swim: () => void; }`.

Since this matches `Fish`, in the `else` clause, TypeScript eliminates the possibility that `pet` is a `Fish`, leaving the `never` type. In other words, TypeScript is saying that this can never happen; the `else` clause is unreachable according to what TypeScript knows about the types.

To demonstrate the behavior you’re expecting, you have a few options:
- [Cast the object literal to the `Fish | Bird` type,](https://www.typescriptlang.org/play?jsx=0&ts=4.3.2&strict=true#code/C4TwDgpgBAYglgZwBZQLxQN5QQdzgWwC4oAKASjQD4oA3AezgBMBfAbgChRIoAhOAJ0ZpMUAGYAbEMXJVaDFh1EBXAHYBjYHDoqoieMhKRgxfSgA+vAYzLEjuhLEQoM7KFH4RgS-jsOeoAIYOpmQAdLgEUACEqOiqjBCicCoQjBzM7GraCMBQduhYEUSkFKjUGMzMgcFOUBZ8ghzscKKkek5+wGQULm5G4Xj45OlQEOII0L15nqESIMPszEA) thereby asking TypeScript to pretend that the variable could be either a `Fish` or a `Bird` (instead of just a `Fish`):
  ```ts
  const pet = { swim: () => {}} as Fish | Bird;
  ```
- [`declare` the variable as your expected type, rather than defining it.](https://www.typescriptlang.org/play?jsx=0&ts=4.3.2&strict=true#code/C4TwDgpgBAYglgZwBZQLxQN5QQdzgWwC4oAKASjQD4oA3AezgBMBfAbgChRIoAhOAJ0ZpMUAGYAbEMXJVaDFh1EBXAHYBjYHDoqoieMhKRgxfSgA+vAYzLEjuhLEQoM7KFH4RgS-jsOeoAIYOpmQAdLgEUACEqOiqjBCicCoQjBzM7Alq4gEeUGraCMBQRiZOUBZ8ghzscKKkek5+wGQULm5G4Xj45OlQEOII0O0lnqESIL3szEA) This is telling TypeScript that the variable exists as the given type, defined outside of the scope of this code.
  ```ts
  declare const pet: Fish | Bird;
  ```
- [Use a function that returns (or is declared to return) either a `Fish` or a `Bird`.](https://www.typescriptlang.org/play?jsx=0&ts=4.3.2&strict=true#code/C4TwDgpgBAYglgZwBZQLxQN5QQdzgWwC4oAKASjQD4oA3AezgBMBfAbgChRIoAhOAJ0ZpMUAGYAbEMXJVaDFh1EBXAHYBjYHDoqoieMhKRgxfSgA+vAYzLEjuhLEQoM7KFH4RgS-jsOeoAIYOpmQAdLgEUACEqOiqjBCicCoQjBzM7OzK6praUADmngDK+AHi4gAKnuQmTlAWfIKYrrqipACyAcBIofwBKox0+DIAPFAADKEArBQubm4eXj4iEUSkFKjUGMxQbC07EOII0HPzi946WBJS67LbuxxuGRnsatoIwFB26IXAJWWVapkDjsOBtEh6Jx+YBkWYtIzhPDDYHsA5HE7wzyha7kdJAA) This is what is done in the documentation you linked.
  ```ts
  function getSmallPet(): Fish | Bird {
    if (Math.random() < 0.5) {
      return { swim: () => {} };
    } else {
      return { fly: () => {} };
    }
  }

  const pet = getSmallPet();
  ```

Only the last method is one you would expect to write in real code. The other two are more useful for toy examples than anything else.

Hope this helps.
