### ISSUE TITLE
'in' operator related bug

### ISSUE THREAD

**Issue by Asaf-S** [microsoft/TypeScript#44470]
# Bug Report

### 🔎 Search Terms

`N/A`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `Type System Behavior`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/FAFwngDgpgBAkgZQK4GMVQM4ZgXhgb2BhgxAEMQkMAuGAIg1XSzoBoiYAbAexQoEtuAO1qkATvyEBzdgF8A3MFCRYcAKpDGaTBgBmSTrgIdSFKrTpQxY7mLYcU3ACZRaQpAFsARlfbEPOmRSriQgEtJyikrg0PAAghD8AEqYEMIYsHiITDowAD7wGlrMegZRwI6aIDBkiSkYELRwCcmp6ZnGxMSmlDT0xTr2XVy8AsIW9gpK-LoAFHQ8fCCCQnQwkjV1qQCUnV2VGNycUAB0PFKzAOQDWJfbirIwUJwZe8QHR6fns7WtDScBLBBKD3GAAejBMAAKgALfjYDAw7gGJwwITcao+GpCJ7WWzAWRAA)

### 💻 Code

```ts

type ISuccess = {
  status: "success",
  location: string,
};

type IUnsuccessful = {
  status: "error",
  code: number,
  message: string,
};


type IApiResponse = ISuccess | IUnsuccessful;


const apiResp: IApiResponse = {
    status: "success",
    location: "",
};

if("location" in apiResp) {
    console.log('success');
} else {
    console.log(apiResp.message); // This should not be an error
}
```

### 🙁 Actual behavior

Got the following error: `Property 'message' does not exist on type 'never'. (2339)`

### 🙂 Expected behavior

No error!

**Comment by MartinJohns** [comment]
This is working as intended, and it's unrelated to the `in` operator.

---

The issue lies in this assignment:

    const apiResp: IApiResponse = { status: "success", location: "" };

You mistakingly think that `apiResp` is typed `IApiResponse`, but this is not the case. It's actually typed `ISuccess`. As a result you get the `never` type in the `else` block, because it's typed `ISuccess`, and the `ISuccess` case is already handled. You can see this when you hover over `apiResp` in your `if` condition:

![image](https://user-images.githubusercontent.com/5269069/120940943-2c3ce000-c720-11eb-8069-f1fbb87ffd8b.png)

You can use a type assertion to get the expected behavior:

    const apiResp: IApiResponse = { status: "success", location: "" } as IApiResponse;

Now the type of `apiResp` is `IApiResponse`, and you get the type `IUnsuccessful` in the `else`-block.

**Comment by RyanCavanaugh** [comment]
☝

Too smart for our own good sometimes 😉

**Comment by Asaf-S** [comment]
@MartinJohns - Thank you!
