### ISSUE TITLE
Empty object should default type to Record<string, unknown>

### ISSUE THREAD

**Issue by unional** [microsoft/TypeScript#44503]
# Suggestion

## 🔍 Search Terms

- Don't use `{}` as a type. `{}` actually means "any non-nullish value".

- empty object type

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Type empty object literal `{}` as `Record<string, unknown>`.

## 📃 Motivating Example

When using the type object type `{}`,
TypeScript provides a nice error message: `Don't use `{}` as a type. `{}` actually means "any non-nullish value".`.

but by default, empty object is typed as `{}`: `const y = {} // y: {}`

This make code like this fail:

```ts
function isBoolean<T>(s: T): boolean extends T ? true : false {
  return typeof s === 'boolean' 
}

isBoolean({}) // true, should be false
```

## 💻 Use Cases

This basically fills a hole in the type system.

🌷

**Comment by jcalz** [comment]
It's [@typescript-eslint/ban-types](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/ban-types.md) giving you that error message, not TypeScript.  Ban-types also doesn't like `object` and wants you to use `Record<string, unknown>` there too.  Perhaps after the Type Wars, all types will eventually be replaced with `Record<string, unknown>`.  But here in the Before Times, I think the current behavior is intentional and not considered a type hole.

**Comment by unional** [comment]
Yeah, sorry, didn't realize it is from `@typescript-eslint`. 😛
