### ISSUE TITLE
TypeScript and TSX files are showing up as Visual C# files

### ISSUE THREAD

**Issue by jonathandturner** [Microsoft/TypeScript#4450]
In VS, if you do add a new file use Add New Item, go to Scripts, you'll see TypeScript and TypeScript Jsx file listed as Visual C# files.  

Shouldn't these at least be something like JavaScript files?

**Comment by danquirk** [comment]
Is this just keyed off project type (csproj) or something?

**Comment by paulvanbrenk** [comment]
They are in the Visual C# category because the project you're adding them to is a C# project, you see the same for CoffeeScript/JavaScript. This is not ideal, but we don't have any control over how this is displayed in the New Item Dialog.

![image](https://cloud.githubusercontent.com/assets/5273975/10407209/adb69f64-6e9c-11e5-88cb-fb0664a18281.png)
