### ISSUE TITLE
Feature Request: Insert Line Breaks When Formatting

### ISSUE THREAD

**Issue by hediet** [microsoft/TypeScript#44504]
# Suggestion

Given this code:
```ts
assert.deepStrictEqual(
  context.getAndClearViewStates(),

  [
    'foo[bar]',
    'foob[ar]',
    'foobi',
    'foobi[zz]']
);
```

If I format this code, I would expect the outcome to be
```ts
assert.deepStrictEqual(
  context.getAndClearViewStates(),

  [
    'foo[bar]',
    'foob[ar]',
    'foobi',
    'foobi[zz]'
  ]
);
```
However, currently the formatter does nothing on the input code.

It would be nice if this is supported.

## 🔍 Search Terms

Formatting, Formatter, Line Break, Prettier

## More Example

This is also not formatted when invoking the formatter:
```ts
const range = word ? { startLineNumber: 1, startColumn: word.startColumn, endLineNumber: 1, endColumn: word.endColumn } :
  Range.fromPositions(pos);
```

**Comment by RyanCavanaugh** [comment]
This is an intentional design choice to err on the side of preserving user linebreaks/lack-of-linebreaks. I'd encourage the use of prettier or other tools if you want something that takes a more prescriptive approach to formatting; we are very much "hands off" when it comes to linebreaks and other things likely to raise hackles.

**Comment by hediet** [comment]
Thanks!
