### ISSUE TITLE
Object literal strictness and unions

### ISSUE THREAD

**Issue by jonathandturner** [Microsoft/TypeScript#4452]
Currently, if I have the following:

```TypeScript
function f(a: {c: number }) { }

f({ a: 3, c: 4 });
```

I get the error that "Argument of type '{ a: number; c: number; }' is not assignable to parameter of type '{ c: number; }'. Object literal may only specify known properties, and 'a' does not exist in type '{ c: number; }'."

Which makes sense, given our recent work on object literal strictness.  What I'm not clear about is why this doesn't allow me to get an intuition about union types.  For example, this does not error:

```TypeScript
function f(a: { a: string } | {c: number }) { }

f({ a: 3, c: 4 });
```

By inspection, I'd expect the above to give me an error.  The object literal I'm passing in matches neither type in the union strictly, and it's arguable the parts it does seem to match are hinting that I'm doing something wrong.

As a user, wouldn't it be my expectation that I'm saying "strictly either an object with a of type string -or- an object of c with type number"?

**Comment by ahejlsberg** [comment]
That's a *union* type, not an *intersection* type. But technicalities aside, I understand why you might expect an error. We currently consider a property unknown if it doesn't exist in *any* of the constituent types in a union or intersection type on the target side. For example, if you specified a property `b` in your object literal you'd get an error. I can sort of see it both ways and I'm not sure I consider this a bug.

**Comment by jonathandturner** [comment]
@ahejlsberg good catch, updated

If we have time, we can chat about this at the design meeting and update the bug after.

**Comment by RyanCavanaugh** [comment]
Doesn't seem to be anyone hitting this badly in practice and the check we'd have to do to detect this error would be quite expensive.

**Comment by denis-sokolov** [comment]
For posterity, I would like to record another instance of this same issue. With TypeScript 2.9.0-dev.20180402 the issue is still present.

The following behavior confused me for a long time. It is a combination of this issue with a slightly confusing `{}`.

```ts
type Union = { name: string } | { age: number } | {};

type Base = {
  // Try commenting out the base prop
  base: boolean;
};

// Try replacing with just Union
function f(parameter: Base & Union) {}

// Notice the age field is invalid, but is not an error
f({ age: "John", base: true });

// Notice the non-existent field is an error
f({ nonExistent: "", base: true });
// Object literal may only specify known properties, and 'nonExistent' does not exist in type 'Base | (Base & { name: string; }) | (Base & { age: number; })'.
```

(Try [in the playground](https://www.typescriptlang.org/play/#src=type%20Union%20%3D%20%7B%20name%3A%20string%20%7D%20%7C%20%7B%20age%3A%20number%20%7D%20%7C%20%7B%7D%3B%0D%0A%0D%0Atype%20Base%20%3D%20%7B%0D%0A%20%20%2F%2F%20Try%20commenting%20out%20the%20base%20prop%0D%0A%20%20base%3A%20boolean%3B%0D%0A%7D%3B%0D%0A%0D%0A%2F%2F%20Try%20replacing%20with%20just%20Union%0D%0Afunction%20f(parameter%3A%20Base%20%26%20Union)%20%7B%7D%0D%0A%0D%0A%2F%2F%20Notice%20the%20age%20field%20is%20invalid%2C%20but%20is%20not%20an%20error%0D%0Af(%7B%20age%3A%20%22John%22%2C%20base%3A%20true%20%7D)%3B%0D%0A%0D%0A%2F%2F%20Notice%20the%20non-existent%20field%20is%20an%20error%0D%0Af(%7B%20nonExistent%3A%20%22%22%2C%20base%3A%20true%20%7D)%3B%0D%0A%0D%0A).)

I don’t know which behavior would be most expected, but whatever treats `age` and `nonExistent` fields similarly: either both are errors or both are not errors.

_Search optimization: empty interface, narrowing, intersection, union, set, known properties._
