### ISSUE TITLE
1.57.0 breaks TS Language Features for large projects, prompts to "Configure Excludes"

### ISSUE THREAD

**Issue by daprahamian** [microsoft/TypeScript#44556]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Open a large TypeScript project
2. See that following prompt appears:
```
To enable project-wide JavaScript/TypeScript language features, exclude large folders with source files that you do not work on.
```

This did not appear on previous VSCode versions, and Typescript Language Features worked fine. Why does it now require this configuration in 1.57.0?

**Comment by mjbvz** [comment]
Can you share some more information about your project? Have you tried configuring excludes for it?

**Comment by tristanpendergrass** [comment]
Hi, I'm having the same problem as @daprahamian. With today's update that notification fires and code navigation doesn't work in typescript files despite working on this exact code base prior to today. I don't know what to say about how it is structured but to figure out how many files there are I ran the following command and obtained the result of 16k files.

```
~/src/server $ find ~/src/server/metaserver/static/js -type f \( -iname *.tsx -o -iname *.ts -o -iname *.d.ts -o -iname *.js -o -iname *.jsx \) -not \( -path *.test.ts -o -path *.test.tsx -o -path *\/node_modules\/*  -o -path *\/external\/* -o -path typings\/*  \) | wc -l
   16319
```

Several other coworkers have reported the same thing on this codebase. I find that if I start a new VSCode far enough down on the tree it will work, but I'm hoping to go back to opening it from the root of the project since that's how ts code navigation is most useful :)

**Comment by daprahamian** [comment]
I ran `tsc --listFiles | wc` and got `21067`.

I think it is worth noting that we are already excluding all `node_modules`, test files, and imported typings.
