### ISSUE TITLE
tsconfig extend does not deep-clone compilerOptions.types

### ISSUE THREAD

**Issue by tholewebgods** [microsoft/TypeScript#44597]
# Bug Report

### 🔎 Search Terms

`extends` `tsconfig` `types` `compilerOptions` `Cannot find module` `or its corresponding type declarations` `svelte`

### 🕗 Version & Regression Information

- Affected version is 4.3.2 and earlier

### ⏯ Playground Link

[Repository with relevant code](https://github.com/tholewebgods/typescript-extend-not-deep-clone-mcve)

### 💻 Code

MCVE: https://github.com/tholewebgods/typescript-extend-not-deep-clone-mcve

### 🙁 Actual behavior

The compiler does not load modules of a specific type configured via `extends` config when root config also specifies `types`.

### 🙂 Expected behavior

When extending from configs `types` shall be merged.

**Comment by MartinJohns** [comment]
Related: #27098

**Comment by RyanCavanaugh** [comment]
This is the intended behavior; if you *didn't* want to copy down the parent types, you'd have no way of expressing that, whereas today you can at least write what you mean. It'd be a fairly large breaking change in build system to change this now, especially since there'd be no workaround apart from editing the upstream config file (which you'd have no way of tracking down the child dependencies of).

**Comment by Exotelis** [comment]
Sorry for reopening this, but I also stumbled over this behavior. Wouldn't it make sense to point this out in the [documentation](https://www.typescriptlang.org/tsconfig#types) then? What else is excluded from inheritance then, is there a document list?
