### ISSUE TITLE
Provide a way to ensure that when merging objects no property values are overrwritten

### ISSUE THREAD

**Issue by Roaders** [microsoft/TypeScript#44594]
# Suggestion

## 🔍 Search Terms

prevent value overwrite merge 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Allow a way to ensure that when merging `TypeA` and `TypeB` into `TypeC` that non of TypeA or TypeB's keys conflict

## 💻 Use Cases

I have a series of different forms that all save different data as part of a single project. We need to be able to combine all of these different form results into one record:

```ts
type TypeA = {
    submitter: string;
    contacts: string[];
    notes: string;
}

type TypeB = {
    reviewer: string;
    overview: string;
    contacts: string[];
}

type TypeC = TypeA & TypeB;

const typeA = {} as TypeA;
const typeB = {} as TypeB;

const typeC = {...typeA, ...typeB}; // ERROR - we have lost contacts from TypeA
```

I would like a compile time check that would throw an error if any types from any our forms have a key that conflicts with any of the other forms.

**Comment by nmain** [comment]
I don't think this requires any new language features.
```ts
function merge<T1, T2>(a: T1 & { [K in keyof T2]?: never }, b: T2 & { [k in keyof T1]?: never }): T1 & T2 {
    return { ...a, ...b };
}
```

**Comment by RyanCavanaugh** [comment]
Overwrites on spread are very common and idiomatic, so I don't think this belongs as a check. A userland merge function like suggested above would be appropriate.

**Comment by Roaders** [comment]
thanks for the help. I have this:

```ts
type DistinctKeys<T1, T2> = T1 & { [K in keyof T2]?: never };

function merge<T1, T2>(a: DistinctKeys<T1, T2>, b: DistinctKeys<T2, T1>): T1 & T2 {
    return { ...a, ...b };
}

type DistinctA = DistinctKeys<TypeA, TypeB>; // never
type DistinctB = DistinctKeys<TypeB, TypeA>; // never
```
where `DistinctA` and `DistinctB` are both never. How can I get this to be a compile error when these types are never?

**Comment by nmain** [comment]
The compile error comes in because there's no way to properly call `merge` with the given inputs: 

[TypeScript Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKuEEEoF4oG8BQVtQM4FcAjAWwEthgIAnALj2CtIDsBzAbixwGMB7J4AIZdguOrgbMWAbQC6HHFCY9Ko+o1YcAvhgyhIseACEU6TtioQAbqQgB3amIkazUHperW7j9exe9+QiLekrJaOnrQcJAAwiZRiFAAZAaQhhwY-uJQEUioaJpQArgpiByZwNlGJvmFxfFpOuWVMdUAdO05ADRQ7a0RhppsUAD0w1AAogBKkwDyk1AAtFD2UAAWAu5QADY8Wf6CwsUAZlQ8xCUIOkf4TMKkfFDE1CwQADwwAIzdMABMAHwACgEdE+SXQUCkAGkoMwoABrCAgHhHWA-GQAfjoTCs1Cgmm6hBBPzBaAhcJhTHhiORsA+GKxOKoeIAlCCPmDfqYFBZgPgqJTSb0BN1eoQ8WEME8qC8AV1mhBDMyOEA)

If you need more assistance, it might be better to post this to StackOverflow as this tracker is only for issues in the language and tooling and is not well suited for a Q&A format.

**Comment by Roaders** [comment]
Yeah but I don't actually want a function call. Just getting an error from the types would be better. I could have a fake function just to throw the error but it would neater to cause a compile error in types alone...
Thanks very much for your help though, you got me 90% of the way there.
