### ISSUE TITLE
I am using React Typescript and getting errors while implementing CartProvider, please solve my issue

### ISSUE THREAD

**Issue by mmnirfan** [microsoft/TypeScript#44600]
import { useContext, useState, useEffect } from 'react';

import CartContext from './CartContext';

const defaultCartState = {
  currency: 'INR',
  items: [],
  totalAmount: 0,
};

interface CartProviderProps {
  data: object;
  name: string;
  price: number;
  item_id: string;
  amount: any;
}

const CartProvider: React.FC<CartProviderProps> = (props: any) => {

  const [cart, setCart] = useState(defaultCartState);
  const [message, setMessage] = useState("");

  useEffect(() => {
    let localCart = window.localStorage.getItem("cart");
    if (localCart) setCart(JSON.parse(localCart));
    else setCart(defaultCartState);
  }, []);

  useEffect(() => {
    window.localStorage.setItem("cart", JSON.stringify(cart));
  }, [cart]);

  return (
    <CartContext.Provider value={{
      data: cart,
      addToCart: ( name: any, price: any, _id: string ) => {
        const item = {
          name,
          price,
          item_id,
        };

        const tempItems = [...cart.items].find((item) => item.item_id === item.item_id);
        console.log(tempItems);
        if (!tempItems) {
          setCart((currentCart) => ({
            ...currentCart,
            amount: currentCart.amount + price,
            courses: [
              ...currentCart.items,
              course
            ]
          }));
          setMessage('success')
        } else {
          setMessage('error')
        }
      },
      removeFromCart: (item: object) => {
        let items = [...cart.items];
        items = items.filter((item) => item.item_id !== item.item_id);
        setCart((currentCart) => ({
          ...currentCart,
          amount: (currentCart.amount - item.price) || 0,
          items
        }));
      },
      clearCart: () => {
        window.localStorage.setItem("cart", '');
        setCart(defaultCartState);
      },
      message
    }}>
      {props.children}
    </CartContext.Provider>
  );
};

export default CartProvider;

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
