### ISSUE TITLE
Object is possibly 'undefined' when instantiating object during declaration

### ISSUE THREAD

**Issue by hsson** [microsoft/TypeScript#44697]
If attempting to instantiate an object during declaration, where the type of a property is optional/nullable, the type checker does not seem to understand that the property is actually set when trying to use it.

Does not work:
```typescript
type Dummy = {
    options?: string[];
};
const a: Dummy = { options: [] };
a.options.push('test'); // <-- Object is possibly 'undefined', refering to a.options
```

Works:
```typescript
type Dummy = {
    options?: string[];
};
const a: Dummy = {};
a.options = [];
a.options.push('test')
```

Would somebody be kind enough to explain if I'm failing to see some subtle detail here, or if this is perhaps intentional or a even a bug in the type checker?

**Comment by andrewbranch** [comment]
This is intentional. When you annotate the declaration for `a` with `Dummy`, you’re throwing away all the information that the type checker checks about the innards of that object. It checks to make sure your declaration is consistent with the type annotation, but from then on, it just goes with your annotation: `a` is `Dummy`, and `Dummy` is not a narrowable type (in contrast to something like `Dummy | undefined`, in which we would try to track which of those types it might be), so it’s just always `Dummy`, and `options` is optional in `Dummy`.

There are lots of ways you could get around this, including the one you posted, but the first thing that comes to my mind is something like

```ts
function createDummy(): Dummy {
  const a: Required<Dummy> = { options: [] };
  a.options.push('test'); // No error because 'options' is required
  return a; // 'Required<Dummy>' satisfies 'Dummy'
}
```

**Comment by devsmitra** [comment]
You are getting errors Because in the type you have defined options can be undefined as well. May be below example can help

```
type Dummy = {
    options?: string[];
};

const a: Dummy = { options: [] };
a.options?.push('test');
```

**Comment by hsson** [comment]
Thank you for your thorough explanation @andrewbranch 👍 🙂
