### ISSUE TITLE
Partial modules and output optimization

### ISSUE THREAD

**Issue by Davidhanson90** [microsoft/TypeScript#447]
We have a typescript application and a use a file per class. There are lots of benefits to this the major one being source control conflict reduction. 

We compile our app using the --out compiler flag but I think there is room for some serious optimization of the compilers output for modules. 

Currently if you have two classes defined in separate files the compile generates the following JavaScript. 

``` javascript
var Example;
(function (Example) {
    (function (Nested) {
        (function (Issue) {
            var bar = (function () {
                function bar() {
                }
                return bar;
            })();
            Issue.bar = bar;
        })(Nested.Issue || (Nested.Issue = {}));
        var Issue = Nested.Issue;
    })(Example.Nested || (Example.Nested = {}));
    var Nested = Example.Nested;
})(Example || (Example = {}));

var Example;
(function (Example) {
    (function (Nested) {
        (function (Issue) {
            var foo = (function () {
                function foo() {
                }
                return foo;
            })();
            Issue.foo = foo;
        })(Nested.Issue || (Nested.Issue = {}));
        var Issue = Nested.Issue;
    })(Example.Nested || (Example.Nested = {}));
    var Nested = Example.Nested;
})(Example || (Example = {}));
```

I suggest a compiler flag that composes all classes/ functions etc under a single module declaration? So the output code would be like the example below. This would dramatically reduce the size of the JavaScript the compiler outputs. I estimate that our app which currently compiles to around 15,000 lines of probably be only be 2000 lines if this were available.

``` javascript
var Example;
(function (Example) {
    (function (Nested) {
        (function (Issue) {
            var bar = (function () {
                function bar() {
                }
                return bar;
            })();
            Issue.bar = bar;
            var foo = (function () {
                function foo() {
                }
                return foo;
            })();
            Issue.foo = foo;
        })(Nested.Issue || (Nested.Issue = {}));
        var Issue = Nested.Issue;
    })(Example.Nested || (Example.Nested = {}));
    var Nested = Example.Nested;
})(Example || (Example = {}));
```

**Comment by Davidhanson90** [comment]
I have a good example of where partial would be useful.

https://github.com/Microsoft/TypeScript/blob/master/src/compiler/parser.ts

**Comment by seshualluvada** [comment]
It all started when I was trying to define multiple classes under a namespace across multiple files (one class in each file) and I learnt that namespace level variables had to be exported in order to gain accessibility to a namespace level variable in a different file than what it has been defined. Please see #6457 . A big problem with having to export is that developers are forced to expose internal variables to code out side the namespace (just because the namespace is defined across multiple files), which they would never want to do. It basically brings us to choose between either exposing internal namespace variables to the general public or struggle to maintain "all" the name space related code in a single file, where neither of them is a desirable development experience.

Here are my thoughts on one approach to handle this.

1. Add a compiler option --aggregateNamespaceDefinitions. What this would do is that before the actual compilation process, it would pull out namespace related code from all of the ts files and creates either one single ts file for entire project or multiple ts files based on the toplevel name of the namespace. The compiler option aggregateNamespaceDefinitions can take values "single" or "toplevel" to emit this behavior.
2. Reorganize the type definitions in the namespace so that the types are defined in the same order as one would have coded if they defined the entire name space in one file.
3. If there are variable name conflicts / type name conflicts, where the same variable / type is defined in multiple files at the same namespace level, error out the compilation process.
4. If everything is fine, run the core compiler using these re-authored files than the original files.
5. If the aggregateNamespaceDefinitions flag is not present, the emit behavior would be the same as it is currently.

This approach would take care of both the javascript bloat where the name space is defined several times in the compiled javascript code when a namespace was defined across multiple files as well as having to export internal module variables and making them visible to code outside the namespace when using namespace level variables across files. 

In my line of business, it is primarily enterprise mobile devices that will be consuming javascript code, and so I have to take every step to eliminate the javascript bloat to optimize load performance.

Below is an example of what I was describing.

>file1.ts

```
namespace Parent.Level1.Level2{
    var level2InstanceCount: number = 0;
    class Level2Child1{
        constructor(){
            level2InstanceCount += 1;
        }
    }
}
```
>file2.ts

```
namespace Parent.Level1.Level2{
    class Level2Child2{
        constructor(){
            level2InstanceCount += 1;
        }
    }
}
```
>file3.ts

```
namespace Parent.Level1{
    var level1InstanceCount: number = 0;
    class Level1Child1{
        constructor(){
            level1InstanceCount += 1;
        }
    }
}
```
>file4.ts

```
namespace Parent.Level1{
    class Level1Child2{
        constructor(){
            level1InstanceCount += 1;
        }
    }
}
```

The re-authored TS file would be like below.  

>Parent.ts

```
namespace Parent {
    namespace Level1 {
        var level1InstanceCount: number = 0;
        class Level1Child1 {
            constructor() {
                level1InstanceCount += 1;
            }
        }
        class Level1Child2 {
            constructor() {
                level1InstanceCount += 1;
            }
        }
        namespace Level2 {
            var level2InstanceCount: number = 0;
            class Level2Child1 {
                constructor() {
                    level2InstanceCount += 1;
                }
            }
            class Level2Child2 {
                constructor() {
                    level2InstanceCount += 1;
                }
            }
        }
    }
}
```

While the re-authoring can be done using a pre-build task too, it would be very neat if the typescript compiler can do that.

**Comment by gulbanana** [comment]
Would a PR adding this feature be considered by the team?

**Comment by fis-cz** [comment]
So, how does i look wit review of this PR?

**Comment by fis-cz** [comment]
From my perspective, the typescript compiler should do combine same namespaces to the same IIFE, even if its splitted over multiple files. Otherwise its not a same namespace. And its confusing. Moreover, same modules should be combined to same file. 

Consider we have a project with following structure:

```
program
   a
      Ns_a1
         ClassA.ts
         ClassB.ts
      Ns_a1.Ns_a12
         ClassA.ts
      module_exports.ts
   b
      Ns_b1
         tools.ts
      module_exports.ts
   blah.ts
   tsconfig.json
```

a and b are modules, Ns are namespaces. Export file should be possible as is should be simply possible to find out what we are exporting out of the module.

The compilation output will be a.js , b.js and blah.js according to definition in files:

module_exports.ts
```
module a {
   // reexport interface and class B form namespace Ns_a1
   export Ns_a1.I;
   export Ns_a1.B;

   // export whatever else from the module
   export function something() {
   }

   export const blah: string = "blah";

   // of course, it should be possible to export the whole namespace
   export Ns_a1;
}
```
ClassA.ts:
```
module a {
   namespace Ns_a1 {
      class A { 
         // class code here, class is not exported so not visible out of Ns_a1
      }
   }
}
```
ClassB.ts:
```
module a {
   namespace Ns_a1 {

      class A {
         // class merge or Duplicate identifier error
      }

      // under normal circumstances, i would place I to separate file but just to shorten the post
      export interface I {
         // exported interface so visible inside module a
      }

      export class B extends A implements I {
         // class code here, class is exported so visible as Ns_a1 inside module a
      }
   }
}
```
ClassC.ts:
```
module a {
   namespace Ns_a1.Ns_a12 {
      // extending Ns_a1.B should be possible even without import as Ns_a1 is parent scope and B is exported out of the IIFE closure
      export class A extends B {
      } 
   }
}
```
tools.ts
```
// tools does not define module so nothing to be merged with and works as in the current TS, so
// compiled to separate file (or considered as separate file in case of --out)
namespace something {
   ...
}

I will not write the code for the b folder branch as it is hopefully clear from previously mentioned code.

As far as I understand TS internals and JS,  this design should stay compatible with previous TS versions. Maybe, if somebody used same module names in different files it can be a beraking change for him as modules would be joined to single file only.

**Comment by fis-cz** [comment]
@volak I don't think modules can be splitted over multiple files. And I would not even recommend it. From my perspective, module is a group of code related to some problem domain. It similar to lib, ko, dll, whatever. With its exports and imports it works very well and mainly, we have module loaders for various systems so nobody will change it. What we need is the well maintainable code which is not currently possible to achieve without additional tools. And when additional tools are used we usually lost development IDE compatibility.

**Comment by pankleks** [comment]
Maybe group exports in one and privates in separate as such:

```
namespace A {
  export class C1 {
  }
  let x = 10;
}

namespace A {
  export class C2 {
  }
  let x = 20;
}
```ts

I think this should be output:
```
var A;
(function (A) {
    class C1 {
    }
    A.C1 = C1;
    class C2 {
    }
    A.C2 = C2;        
})(A || (A = {}));
var A;
(function (A) {
    let x = 10;
})(A || (A = {}));
var A;
(function (A) {
    let x = 10;
})(A || (A = {}));
```js

Yes - it looks even worst, but in majority of the cases one does not use private members - just single exported class - so it would collapse nicely.

**Comment by RyanCavanaugh** [comment]
Large namespace-based projects are increasingly rare; this isn't an area of future investment for us.

**Comment by gulbanana** [comment]
That’s a shame. Namespaces still have the major advantage of not needing a bundler; they let you write Typescript for the browser without requiring extra tools to turn it into a single file that the browser can (efficiently) consume. I wish this kind of feature was considered significant, because for my team it’s a major draw of the ecosystem - in particular, not having to use npm in our build process is very valuable.
