### ISSUE TITLE
Default export ignores the type annotation when exporting combined style-components

### ISSUE THREAD

**Issue by danfma** [microsoft/TypeScript#44731]
# Bug Report

### 🔎 Search Terms
default, export, typescript, React, styled-components, Object.assign

### 🕗 Version & Regression Information

I'm using TypeScript `4.3.2`, `^4.2`, and `next`. All those are showing the same errors.

### 💻 Code

I've attached this image to illustrate the problem.

![image](https://user-images.githubusercontent.com/101121/123309818-c4e2a680-d4fb-11eb-9d93-c7dd99d9e7ac.png)

```tsx
import styled from 'styled-components';

const A = styled.div``;
const B = styled.div``;

export default Object.assign(A, {
  B
});
```

This is a pattern used to group components related to the same context (kind of namespace simulation). The idea is to use that exported components like the following:

```tsx
<A>
  <A.B />
</A>
```

### 🙁 Actual behavior

The exported type annotation of the default exported value is not being generated.

### 🙂 Expected behavior

The exported type annotation should be generated with the code.

**Comment by weswigham** [comment]
@danfma This is going to sound odd - but hear me out - you need to add a dependency on `@types/hoist-non-react-statics` to your project (the same version that `@types/styled-components` depends on - and ensure it's loaded, either via a `types` reference or the compiler option). The issue, as best as I've recreated it, is that we (correctly) determine that we can't reference `"hoist-non-react-statics".NonReactStatics` safely (and need to because of its usage in the definition of `StyledComponent`, which the object assign augments) because we don't have a direct dependency on `"hoist-non-react-statics"` - and because of that, we refuse to generate an annotation. We _should_ also be generating an error along the lines of `"This statement needs an explicit type annotation. Serialized result depends on './node_modules/styled-components/node_modules/hoist-non-react-statics' - this is likely not portable"`, however that error is getting swallowed somewhere. I'm going to get that error surfacing again; but in that meantime, you should be able to get your emit working by making that (type) dependency explicit. Or by adding an annotation with the type yourself.

**Comment by danfma** [comment]
Thanks, @weswigham!

I will try what you said tomorrow. But it makes sense.
