### ISSUE TITLE
A value of Req<T> type can't be assigned to a variable of "Req<T> & Opt<T>" type, although Opt<T> has all fields optional and T is a record

### ISSUE THREAD

**Issue by dko-slapdash** [microsoft/TypeScript#44748]
# Bug Report

When some record type is e.g. defined as generic `FullRow<T extends { id: string }> = RequiredRow<T> & OptionalRow<T>` where RequiredRow is a row with all required fields and OptionalRow is a row with all optional fields, an attempt to assign a value of RequiredRow<T> to a variable of FullRow<T> fails, although it should've been possible since OptionalRow has all fields optional.

When using no generics, it works as expected.

### 🔎 Search Terms

keyof generic

### 🕗 Version & Regression Information

Nightly & previous versions too

### ⏯ Playground Link

Here is a [playground link](https://www.typescriptlang.org/play?ts=4.4.0-dev.20210625#code/MYewdgzgLgBAJAZQJoFkYF4YIJ4FsBGIANgBQCUA3ALABQtU2ADgKYwAqAhvka5gN60YMAJYATAFwxoAJ2FgA5tRoBfWrWYAPRiGmwGLGACVmARwCuw6c1EIoshYZAB3ADxtO3VpqjMwoiOxcPAB8GDACNEIA2gDSImBSdnLyMABkMADWzNggAGbsHjwAupIyyUrKSupaOnpMrADyjFDC4BxEOATEjq7uQV4aPn4Bhcyh-IIwsfFSeIREaZnZeQX9RQD8pUkKFVU0mtq6MPqsAGJmREQ9bqMw3r7+gZ7jRqYWVjbb8td9z4tNLTaHTm3WcN36wT2B1qMFyZjAwEBCQgIFwzAAjODPHdBg8RhDyOFJqBILBpOjJMZzJZrLZ7N8wb8QmE+MoYBwAhwwNglEISdAYNIAEySc6XH6jF7kigwAD0spgLgAtEqYE4ABbYdbE8AongAOiIIHkJGFlFoqjo+xqRzhCKRUlRzCFhIiQhOWCdtwmkSEIgkiXpvL9KLRWyDk2iiFQJUD5Umlr5urJFNe1I+dOS1wQXohLLZHPZ3OD-LJIpgYquYJzaMlYWlcoVytVwlgTh0GQgOsgxGYhuNpqF5pUtCAA)

### 💻 Code

```ts
const $SYM = Symbol();

type Table = {
  id: string;
}

export type RequiredStringRow<TTable extends Table> = {
  [K in string & keyof TTable]: string;
};

export type OptionalSymbolRow<TTable extends Table> = {
  [K in symbol & keyof TTable]?: string;
};

export type FullRow<TTable extends Table> = RequiredStringRow<TTable> & OptionalSymbolRow<TTable>;

export function some1<TTable extends Table>() {
  const r1: RequiredStringRow<TTable> = {} as any;
  const r2: FullRow<TTable> = r1; // <-- ERROR HERE; why?
  console.log(r2);
}

export function some2() {
  type SomeTable = {
    id: string;
    some: string;
    [$SYM]: string;
  }
  const r1: RequiredStringRow<SomeTable> = {} as any;
  const r2: FullRow<SomeTable> = r1; // <-- it works
  console.log(r2);
}
```

### 🙁 Actual behavior

In some1(), the error is

```
Type 'RequiredStringRow<TTable>' is not assignable to type 'FullRow<TTable>'.
  Type 'RequiredStringRow<TTable>' is not assignable to type 'OptionalSymbolRow<TTable>'.
    Type 'symbol & keyof TTable' is not assignable to type 'string & keyof TTable'.
      Type 'symbol & keyof TTable' is not assignable to type 'string'.(2322)
const r2: FullRow<TTable>
```

The question is, why does it even try to type-match `RequiredStringRow` to `OptionalSymbolRow`, although it knows that FullRow is defined as RequiredStringRow & OptionalSymbolRow (and thus, it should've been 100% sure that RequiredStringRow is assignable to FullRow)?

(I actually have a suspicion why this happens: maybe I haven't convinced TS enough that OptionalSymbolRow<T> always has all its fields optional, so TS thinks that it may have something non-optional. Is there a way to convince TS that some generic has ALL its fields optional no matter what?)

### 🙂 Expected behavior

r2 is correctly assigned

**Comment by andrewbranch** [comment]
> The question is, why does it even try to type-match `RequiredStringRow` to `OptionalSymbolRow`, although it knows that FullRow is defined as `RequiredStringRow & OptionalSymbolRow` (and thus, it should've been 100% sure that `RequiredStringRow` is assignable to `FullRow`)?

I think you have this backwards—intersection types are _at least as narrow_ as the narrowest of their constituents, which means that `A & B` is always assignable both to `A` and to `B`, but not the reverse. Conversely, `X` is assignable to `A & B` if it is assignable both to `A` and to `B` individually. 

So the job here is to find some value that can inhabit `RequiredStringRow<TTable>` but not `FullRow<TTable>` for some instantiation of `TTable`. I’ll use your `SomeTable` definition ([playground](https://www.typescriptlang.org/play?ts=4.4.0-dev.20210625#code/MYewdgzgLgBAJAZQJoFkYF4YIJ4FsBGIANgBQCUA3ALABQoksiqATBlnoaZbbVNgA4BTGABUAhviLDMAb1owYASwAmALhjQATorABzajQC+PGoIAe-EJth8hMAEqCAjgFdFmwcoRRte+yAB3AB4RcUlhcyhBMGUIUQkpAD42ORoFAG0AaSUwDR8dXRgAMhgAa0FsEAAzUTCpAF11LQKDQwNac0trGFthAHl+KEVwMSIcAmJ-YNCEiLMomLi6wWTZeRgsnI0OYmKyiura2fqAfib8vVb20wsrGwFhADEXIiIpkOWYSOjY+PDVhzONweLwXXTvGb-PYDIYjMY7N6BD6zRLXTp3GBVFxgYCw3IQEC4QQARmR4S+8x+SxR5BgqQU9GgME0xPUjlc7k83l84KRkKSKUMMDEcTEYGwBgZ4CZmmY6merwhywBLIoMAA9OqYEEALQ6mABAAW2BO60ZxEEADoiCBdCRZdwjCZ0d0sTi8RpCYJmLT6T0HlgvZ81mkFEo1HkeZKwwSieco+sMkwUI1Iy11sYaGbpbAWSlE+H1AAiFRFgA0BdjgmLVfLBfSydTAGYK6G2iYpQwYAB9NlAzmgnnvBBBlFsVXZruy+UvRHBEdE5Xj4mtWhAA)):

```ts
type SomeTable = {
  id: string;
  some: string;
  [$SYM]: string;
}

const r1 = {
  id: "id",
  some: "some",
  [$SYM]: 3, // ❗️
};

const _: RequiredStringRow<SomeTable> = r1; // Works
const r2: FullRow<SomeTable> = r1;
//    ^^
// Type '{ id: string; some: string; [$SYM]: number; }' is not assignable to type 'FullRow<SomeTable>'.
//  Type '{ id: string; some: string; [$SYM]: number; }' is not assignable to type 'OptionalSymbolRow<SomeTable>'.
//    Types of property '[$SYM]' are incompatible.
//      Type 'number' is not assignable to type 'string | undefined'.(2322)
```

This proves that not all `RequiredStringRow<T>` are assignable to `FullRow<T>`, because the former may have excess properties whose types conflict with those needed by `OptionalSymbolRow<T>`. Put another way, while your intuition is correct that `FullRow<T>` could not possibly require any additional properties that `RequiredStringRow<T>` doesn’t contain, _if_ any additional symbol-keyed properties are present, their types could easily conflict with what `OptionalSymbolRow<T>` would require them to be.

**Comment by fatcerberus** [comment]
> ```
>     Type 'symbol & keyof TTable' is not assignable to type 'string & keyof TTable'.
>       Type 'symbol & keyof TTable' is not assignable to type 'string'.
> ```

These last two lines of elaboration are admittedly a bit confusing - saying, essentially, that the reason assignability is denied is due to `symbol` not being assignable to `string` when really that's *not* the cause of the error, it's actually precisely this:

```
Type 'RequiredStringRow<TTable>' is not assignable to type 'OptionalSymbolRow<TTable>'.
```

In other words the fact that there might be symbol properties isn't the problem *per se*, it's that those symbol properties might have *values* of the wrong type.  Thus the elaboration is misleading.

**Comment by dko-slapdash** [comment]
@andrewbranch 
> Conversely, X is assignable to A & B if it is assignable both to A and to B individually

But doesn't it apply to only types where all the fields are required? Here is an [example](https://www.typescriptlang.org/play?#code/C4TwDgpgBAglC8UDeBYAUFKBDAXFAzsAE4CWAdgOYDc6AvuuqJFAEILLqYBGA-HoaUo009NOgDGAezKFseOIiRyoAIizqVUWsKkzgULnjaLlajVqpQA9FagAVcNADkS3AWLlqWp1BL4oZJL6WPj4JBRkWFwANtDAklBMzixOAHQMaLqyAB7yUABkrOyueGZYmtrWtgDyANIAhEA):

```ts
type A = {
  a: string;
}

type B = {
  b?: string;
}

const a: A = { a: "aaa" };
const b: B = { a: "aaa" }; // Type '{ a: string; }' is not assignable to type 'B'.

const x: A & B = { a: "aaa" }; // OK!
```

In this example, `{ a: "aaa" }` is assignable to A and not assignable to B, but still, it's assignable to A & B.

**Comment by andrewbranch** [comment]
I did not say “`X` is assignable to `A & B` if **and only if** it is assignable both to `A` and to `B` individually.” 😄 Excess property checks, common property checks, and other things that make assignability different from the type-theoretical subtype relationship do indeed make that untrue. But I’m pretty sure that even for assignability, the statement I made is true, and it was a direct answer to your question of

> [when checking if `RequiredStringRow` is assignable to `FullRow`] why does it even try to type-match `RequiredStringRow` to `OptionalSymbolRow`, although it knows that `FullRow` is defined as `RequiredStringRow & OptionalSymbolRow`

—the algorithm for checking if `RequiredStringRow` is assignable to `RequiredStringRow & OptionalSymbolRow` would be to check that the former is assignable to _all_ constituents of the intersection. It is assignable to itself, so then it must check if it is assignable to `OptionalSymbolRow`, and it is not, so that’s where the error elaboration starts.
