### ISSUE TITLE
Typescript is inferring, even if there is an error. Something weird.

### ISSUE THREAD

**Issue by ndr47** [microsoft/TypeScript#44743]
I would like to infer the return type of a function as value of a constant object.
The other keys of the object might not be functions.

Therefore I created a type like this:

```ts
type MyKeys = 'one' | 'two';

const MyConstObj = {
    one: ():'MyConstantTypeAsString' => {
        return 'MyConstantTypeAsString';
    },
    two: 2
} as const;

type MyType<T extends MyKeys> =
    T extends keyof typeof MyConstObj ?
    typeof MyConstObj[T] extends (...args:any) => any ?
    ReturnType<typeof MyConstObj[T]> :
                // ~~~~~~~~~~~~~~~~
    unknown :
    unknown;

export const myvar_a:MyType<'one'> = 'Something wrong';

export const myvar_b:MyType<'two'> = 'Something else';

```

Typescript give me an error on 
``` ts
ReturnType<type MyConstObj[T]>

// Type '{ readonly one: () => "MyConstantTypeAsString"; readonly two: 2; }[T]' does not satisfy the constraint '(...args: any) => any'.
//  Type '(() => "MyConstantTypeAsString") | 2' is not assignable to type '(...args: any) => any'.
//    Type 'number' is not assignable to type '(...args: any) => any'.
```
Since I am using:
```ts
typeof MyConstObj[T] extends (...args:any) => any ?
```
why typescript still doesn't allow me to use it in `ReturnType`?

Even tho it seems it can correctly infer the types: 
if you over on `myvar_a` the type is inferred correctly. Also `myvar_b` has the correct type.

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/C4TwDgpgBAsiDSEQGcoF4oHID2A7CmUAPlsAO7aYDcAUDQMZ7LCwgDCTwA8gEYBW6KAG8aUMVDwQAXFAAUASimY4HXMwCGuYABVwEAILIAysABOAS1wBzQmgB8w0eOemIwAK6ncWFZ0069QxMLa2onMQBfABpwqHJsGQAmGgiodVRGNWBaGlBIVl1IAB5tKAgAD2AIXAATVDhEFAc0WNKKqtrUAGskbAAzOL1+1lVmXgEAfhoASDyIYd8s8YBtbQBdMsrqurkAOn31UytkKU0QeXQHM6gp6YAlN09cQogiuYX2ThX1hylY91wXVw2DI3j+zgBQJBuByFTA2FMLEyzCgAFsQAA3Q4AfXUUjgLyKOHwmGaWCM2FRbgAFpYrFAyKY8DZYeV4YioMiWOisaZsTx8SBCZh4qTBJgKVTgLTrGUADbIAi0IA)

**Comment by nmain** [comment]
You can make this work if you rearrange the types a bit:  [TypeScript Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAsiDSEQGcoF4oHID2A7CmUAPlsAO7aYDcAUDQMZ7LCwgDCTwA8gEYBW6KAG8aUMVDwQAXFAAUASimY4HXMwCGuYABVwEAILIAysABOAS1wBzQmgB8w0eOemIwAK6ncWFZ0069QxMLa2onMQBfABpwqHJsGQAmGgiodVRGNWBaGlBIWHUQHggAJTdPXF1IAB5tBwxtKAgAD2AIXAATVFkAOj71UytkKU0QeXQHUagAfigyjy8qiFqHGXdcAGtcbDJcHLzoOCXaptb2rtZEFHrYxpa2ztQNpGwAMzi9N9ZVZl4BWZghWK8wqxwOX18WT+AG1tABdVZQdZbHZ7OgtMDYUwsTLMKAAWxAADcBgB9dRSI56ao4fCYeo+dh+LRLIJmSw2HIYrE4zgE4lkniUkDHTDxemCTBGbD4twACw5TQANsgCLQgA)

I don't know if it's a bug.

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.

**Comment by ndr47** [comment]
@RyanCavanaugh yes, sorry. It seems a bug to me, because it is working and giving an error at the same time.
