### ISSUE TITLE
Enum: ability for tsc to disable emit reverse mapping

### ISSUE THREAD

**Issue by bigopon** [microsoft/TypeScript#44753]
# Suggestion

## 🔍 Search Terms

Keywords searched
- enum reversed mapping

Example https://github.com/microsoft/TypeScript/search?q=enum+reverse+mapping&type=issues

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

Ability to configure `tsc` to not generate the reverse mapping for const enum (is enum qualified?) to reduce the amount of code generated.

## 💻 Use Cases

Consider the following example: https://www.typescriptlang.org/play?preserveConstEnums=true#code/KYDwDg9gTgLgBAYwgOwM72MgrgWzgBSmAWABNMS4BvAKDjgDUBDKASydNYXp97-oC8cAAwAjYROEBGGVOkAaOnACCqVKwDmyfjr5Cxk6bLmL6AYRScYrFEwA2uvSPGTjM03Av3gqBK2Qajk4GEnKGwh4AMhAaXPYA8gBKQcEuYeFRMXF2ygByACIpPPpp6ZIeAKIAjlj2rDAAnkW8JdLh5UqJwHZM1rYOza1yZRIeyqRWrABuwM3FzkbtEUoAslh21mB2cdYzQUMy7R4AQv4sTXPzYiOGUcAAZjAAEkzIpADKrORFJTehHoRWDhzpdBM4-iYlABVZAg0Fg65Ldw0AC+NCAA

The reverse mapping would never be used. It should have been a lot cleaner/smaller like this
```ts
export var Precedence;
(function (Precedence) {
    Precedence["Variadic"] = 61;
    Precedence["Assign"] = 62;
    Precedence["Conditional"] = 63;
    Precedence["Coalescing"] = 64;
    Precedence["LogicalOR"] = 128;
    Precedence["LogicalAND"] = 192;
    Precedence["Equality"] = 256;
    Precedence["Relational"] = 320;
    Precedence["Additive"] = 384;
    Precedence["Multiplicative"] = 448;
    Precedence["Binary"] = 512;
    Precedence["LeftHandSide"] = 513;
    Precedence["Primary"] = 514;
    Precedence["Unary"] = 515;
})(Precedence || (Precedence = {}));
```
rather than this
```ts
export var Precedence;
(function (Precedence) {
    Precedence[Precedence["Variadic"] = 61] = "Variadic";
    Precedence[Precedence["Assign"] = 62] = "Assign";
    Precedence[Precedence["Conditional"] = 63] = "Conditional";
    Precedence[Precedence["Coalescing"] = 64] = "Coalescing";
    Precedence[Precedence["LogicalOR"] = 128] = "LogicalOR";
    Precedence[Precedence["LogicalAND"] = 192] = "LogicalAND";
    Precedence[Precedence["Equality"] = 256] = "Equality";
    Precedence[Precedence["Relational"] = 320] = "Relational";
    Precedence[Precedence["Additive"] = 384] = "Additive";
    Precedence[Precedence["Multiplicative"] = 448] = "Multiplicative";
    Precedence[Precedence["Binary"] = 512] = "Binary";
    Precedence[Precedence["LeftHandSide"] = 513] = "LeftHandSide";
    Precedence[Precedence["Primary"] = 514] = "Primary";
    Precedence[Precedence["Unary"] = 515] = "Unary";
})(Precedence || (Precedence = {}));
```

**Comment by MartinJohns** [comment]
This sounds just like #37282.

**Comment by andrewbranch** [comment]
This sounds like a good idea in theory, but in practice it would be a nightmare for the same reasons that const enums are often nightmares. So if you enabled this flag, we’d have to add type checking logic to disallow you from doing reverse lookups on enums that were compiled this way, right? This is easy enough for enums that you wrote yourself within a single project, because all we have to do is look at the compiler options you’re running under. But what about enums declared in an external `.d.ts` file? How do we know what mode they were compiled under? We don’t! We would either have to come up with a syntactic modifier _just_ for enums or compile under the more conservative assumption that reverse lookups will fail, breaking tons of existing code. Enums are such a pain already that I don’t think we would have much appetite for creating yet another variation of them requiring different type-checking behavior, much less creating more syntax to accommodate them.

I would suggest just using an object literal if you’re writing code that will be consumed as a library, or perhaps using a const enum if you’re writing purely internal/app code and just want to trim down the generated code (and eliminate a bunch of property lookups).
