### ISSUE TITLE
Allow auto import codefix for shorthand object notation {XXX}

### ISSUE THREAD

**Issue by heroboy** [microsoft/TypeScript#44799]
# Suggestion

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Currently, in vscode:
```tsx
const obj = { XXX };
```
When `XXX` is not import yet.
It doesn't auto complete and auto import `XXX` for the code above. And the auto fix doesn't try to import `XXX`.

but for code:
```tsx
const obj = { XXX: XXX }
```
It would auto complete and auto import `XXX` when typing the second `XXX`. And the auto fix would import `XXX` for the second XXX.

I suggest typescript will auto import and auto fix for first code.

**Comment by a-tarasyuk** [comment]
Currently, auto-imports disabled for shorthands.

```ts
 // If current completion is for non-contextual Object literal shortahands, ignore auto-import symbols
 if (isNonContextualObjectLiteral) return false;
```
I think @andrewbranch can help clarify this case.

**Comment by andrewbranch** [comment]
I suggested disabling it because I thought it would be a somewhat unusual case. Part of the thinking was that if you start typing in an object literal, there’s a pretty good chance that you’re actually just going to type a unique key name followed by `:`, and so none of our completions are going to be useful to you, so we better make the completions we do offer pretty unobtrusive. I would be particularly worried about a situation like this: suppose I want to type `const x = { state: true }`, and I get completions when I've gotten to `const x = { s`. I see that the top one actually does say `state`. “Cool!” I think, as I press tab. But it turns out it was an auto-import of some identifier named `state` that I didn’t care about, and I just hit it too quickly to notice that it was an auto-import. Perhaps I have to hit undo and re-type the rest of my property, or perhaps I don’t even notice the mistake, and later TypeScript complains that I’ve never used that import. So I think I’m biased toward disabling auto-imports whenever you’re in a new identifier location. But I’m open to feedback.

**Comment by heroboy** [comment]
I agree the auto completions auto import is sometimes annoying, it is very easy to accidently import something that I don't want.

But in my origin post, I also point the "auto fix" or "code action" to auto import.

For example, when I fully typed `{XXX}`, and typescript know `XXX` is an invalid symbol. Then when I move the cursor to the `XXX`, press `Ctrl + .`, there should be a menu to help me import the `XXX`.

**Comment by andrewbranch** [comment]
Ah yeah, we can definitely give the codefix there. That’s no problem.
