### ISSUE TITLE
Excess property checks still appear in presence of index signature

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#44793]
```ts
interface A {
    a?: string
    b?: number
    [key: symbol]: string
}

const symbolKey = Symbol('key')

const a: A = {
    [symbolKey]: '123',
}
```

`symbol` still not working：[ts playground](https://www.typescriptlang.org/play?ts=4.4.0-dev.20210627#code/PTAEiJrQ5+MU3NAYlUAqBPADgUwMoGMBOBLFAF1EA47QBTlAudUBh-gKBFEE34wejNAAOUCo5QTb9ADeUAXjQbPlAaP6BMxSqAwJUDVcoBiVQGbagAzlEqTLgLFAIW6BFf0CbXoCAGGnTCAKg0D3yoFO5E4CDNQNBygSDlAs56BO00Dw+oH95QBSugYO1AWP-79oUAFpQdkBYOUAseUAWD0B5dUBvuUBVeUAcOUB-SNU5BXRsfCJQVUAGdXtdegCgtkBleUAYrLSlTOJAW+jAVZtANz1AODlAaojALrkJXPzfIvZXQDi5QGlbQFXo4MAYFUqMlVABQEXowHxzQHylQF+A1UBMm0BG710aPAA7QjQcADMAQyw0UABBUABvGj8-E4B+AC5QAGdCfF2Ac3uHgBGr1AuwArgBbAGHf5+ADaAGs0Eg3gADAAe-gAJDdPt8fgBfFGgAA+HyQkIA9gAbAC6b1xez++L0WApu0+ZMpVIA0kjQABeUAYckA6kACgA5IikBKAJQstkck5va6Cu4PUASjEnCVvCUARgATABmCUAGhhoFh7xF1N5SDpmqNppozN8pkAnQ6Ab8VAFBy9lUoEAOASALk9ANHygFwCUCANCMg4AG00A36nhqgmQBhcoBjyMAL2aALE1AM6K-RqgAAo1SAQ-lAPYG2gARL4o4BQAMABEqAEzSGIBsuUAFzaAKcSGoAUOUAAPqAac03FRAC6mbHIFFUgDQ5QAyroBfhMAejr9Li6IA)

_Originally posted by @liuweiGL in https://github.com/microsoft/TypeScript/issues/44512#issuecomment-869415311_

**Comment by ahejlsberg** [comment]
It's an easy fix, but the odd thing is that it ends up being a breaking change because we previously would validate symbol-named properties again string index signatures when performing excess property checking. For example, we previously allowed:

```ts
declare let obj: { [key: string]: string };
const sym = Symbol();
obj = { [sym]: 'hello' };  // No excess property error
obj[sym] = 'hello';  // Error as expected
```

We need to decide if we still want to permit symbol-named properties when only a string index signature is present or whether to now give an error and require the target to have an index signature for key type `symbol`. This for example impacts the `PropertyDescriptor` type in `lib.d.ts`.

**Comment by DanielRosenwasser** [comment]
I opened up https://github.com/microsoft/TypeScript/issues/44794 to discuss that issue - I guess it makes sense that the simplest fix would end up forcing a decision on that issue.

**Comment by ahejlsberg** [comment]
A non-breaking fix for now would be to validate symbol-named properties against symbol index signatures, but also fall back to validating them against string index signatures if no symbol index signatures are present.
