### ISSUE TITLE
type {} should not allow assignment of any non-nullish value

### ISSUE THREAD

**Issue by nojvek** [microsoft/TypeScript#44874]
# Bug Report

### 🔎 Search Terms

Empty object, {}, non-nullish value

### 🕗 Version & Regression Information
I don't think this has ever been fixed before.

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/DYUwLgBAZhC8EG8C+BuCB6dEAqBlCAzgBYD2ArsACYRgBOIAhpGEQJYEQMcgC2ADmACeEEgCMAViADGYAFCyY8AIwAmAMxpMhUhWohatErQVwIAIiIhgwEmc1Zi5KhH2HjimrTIh72p3oMjeSgAOgZTVQ0MLFcjDi4XAA8+aTAQSnlZUEgGAC5EPiV80RISUAYAOyRTBEL8um9UWXDldV9Y2njuZNT05tMLKxs7aJdAzs5ulJk+ls9vdvGupOm0jIYQvhUBrkooM1GO5ZAemcogA

### 💻 Code

Assigning any non-nullish value to `{}` seems like a hole in the type system. `{}` ought to mean an empty object. 

Unintuitive that once a single property is added, then TS behaves as expected, but without any properties, typescript acts like its drunk.

```ts
let f = {}; // TS should treat this as empty object

f = 123; // should error
f = "hello"; // should error
f = true; // should error

f.a = 123; // errors as expected


let a: {p1: boolean} = {p1: true};
a = 123; // errors as expected
a = "hello"; // errors as expected
a = true; // errors as expected
a.p2 = "asdf" // errors as expected
```

### 🙁 Actual behavior

See comments.

### 🙂 Expected behavior

See comments in code. Treat '{}' as legit empty object without any own properties.

**Comment by DanielRosenwasser** [comment]
This is working as intended. In those last assignments, TypeScript is explicitly rejecting values that don't have a `p1` property. Here's an example where TypeScript has at least one property and accepts those values.

```ts
let b: { toString: () => string } = {};

b = 123;
b= "hello";
b = true;
```

The language is looking to ensure that if properties have been stated, then their types must match.

**Comment by jcalz** [comment]
This is working as intended, and while there *are* holes in the type system, this is not one of them.

Object types in TypeScript are not *exact* (see #12936) and are allowed to have more properties than declared.  [Excess property checking](https://www.typescriptlang.org/docs/handbook/interfaces.html#excess-property-checks) makes this more complicated, because sometimes the compiler will warn on such excess properties, but this only happens when assigning "fresh" object literals, and is explicitly disabled for the empty object type `{ }` anyway (see #38932).  

Your examples with `{p1: boolean}` all yield errors because neither `number` nor `string` nor `boolean` have an apparent `p1` property of type `boolean`. If you replaced it with something that they *do* have, the errors would go away:

```ts
let a: { toString(): string } = { toString() { return "" } };
a = 123; // no error
a = "hello"; // no error
a = true; // no error
```

[Playground link to code](https://www.typescriptlang.org/play?#code/DYUwLgBAhgXBDeEwHsDKYBOBLAdgcwAoBKOAZ01zwgF8IBeBJNC-YxjcAVwxwgCI+NGgG4AUFHoQAjACYAzMIgB6JRBzIIIDBmQZxkvgAsQwYMj6KVajVp16JDTJxCXV6zdt2igA)

**Comment by DanielRosenwasser** [comment]
> ah, scooped by @DanielRosenwasser !

Your explanation has way better context - thanks!

**Comment by nojvek** [comment]
I see, so you're saying that because `123`, `"hello"`, `true`, all have Object in their prototype chain, this is a valid assignment.

I guess that makes sense.

**Comment by fatcerberus** [comment]
> because 123, "hello", true, all have Object in their prototype chain

It's more because `{}` has no stated properties, and therefore, no constraints on what may be assigned to it (except `null` and `undefined` which are not object-coercible).

**Comment by RyanCavanaugh** [comment]
If we rejected an assignment from `"hello"` -> `{ }`, then by transitivity of subtyping we'd have to reject an assignment from `"hello"` -> `{ length: number }`, which is in practice not how strings are treated in JS -- they definitely do have a `length` property!
