### ISSUE TITLE
An accessibility modifier cannot be used with a private identifier

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/TypeScript#44870]
# Suggestion
i think ts should allow the modifier `private` on a private identifier.
for keep a kind of design correlation in a project.

Actually change a public identifier to #private , lint error on all ts private modifier 
![image](https://user-images.githubusercontent.com/24865815/124301345-b1ec5980-db2d-11eb-9460-fd9f43aa9ea9.png)

Is there a way to ignore this error in tsconfigu ?
```ts
export class A  {
	private #foo= new foo();
}
```
i color all my `accessibility modifier` for fast nav, but private identifier lint error with the private `accessibility modifier` !

## 🔍 Search Terms
An accessibility modifier cannot be used with a private identifier

**Comment by sandersn** [comment]
`#private` and `private` are mutually exclusive, like `public` and `private`. Typescript doesn't allow combining those either. It's confusing because they do nearly the same thing, but that's even more reason to keep them separate.

**Comment by djmisterjon** [comment]
> `#private` and `private` are mutually exclusive, like `public` and `private`. Typescript doesn't allow combining those either. It's confusing because they do nearly the same thing, but that's even more reason to keep them separate.
ho oki, i will take a look on doc to understand more !
thanks for your fast answer and your reason to keep this separate , i will close !

**Comment by revolter** [comment]
> like `public` and `private`

Not quite, since they're not opposites.

> they do nearly the same thing

Not that nearly, since `private` is enforced at compile time, and `#private` is enforced at runtime: https://stackoverflow.com/a/59641565/865175.

**Comment by ctsstc** [comment]
I wanted to know if this transpiles down to a [`#privateProperty`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_properties) I guess it [does not](https://www.typescriptlang.org/play/?target=99#code/MYGwhgzhAEAqCmEAu0DeAoa0AOAnAlgG5hLzSnL4B2A5tALzQBmYIE8A3JtAMR5El4ABVwB7bPFxIAng3K4Arp3QBfIA) unfortunately even with the target of `esNext`.

I know there's deep history here. The `private` keyword has been utilized by TypeScript well before JavaScript even had private properties or even classes. I would expect if the TSConfig target was modern enough that it should be transpiling `private` into a `#privateProperty`. But then we would need to make sure there wasn't any conflict. It seems that if we have the language feature now and have the runtime safety of OOP private access that it should be utilized. It makes me wonder if older transpilation targets have never isolated the values, or if that was lost in the transition to classes?

If we look at the [ES3 target transpilation](https://www.typescriptlang.org/play/?target=0#code/MYGwhgzhAEAqCmEAu0DeAoa0AOAnAlgG5hLzSnL4B2A5tALzQBmYIE8A3JtAMR5El4ABVwB7bPFxIAng3K4Arp3QBfdEA), we'll see that transpilation did indeed protect its scope a bit more it seems by abstracting it out into a variable. This would just depend what context this was then ran it, but it wouldn't expose the property on the class instance.

**Comment by RyanCavanaugh** [comment]
@ctsstc see https://github.com/microsoft/TypeScript/issues/31670

**Comment by ocket8888** [comment]
`private member;` can't transpile to `#member;` for a few reasons. First is that a class can have both the property `member` *and* the property `#member` so unless the compiler does an annoying amount of property name mangling it wouldn't be able to support that. Second, it would break existing (but bad imo) code:

```typescript

class X {

  private foo = "secret";

}

const x: any = new X();

console.log(x.foo); // prints "secret"

```

changing how that's transpiled to use `#` would cause it to behave differently at runtime.


But most interestingly, it can't be done because `private` and `#` don't and can't model the same thing. The code:

```typescript

class A {

  #x = "bar";

  public logA(): void {

    console.log(this.#x);

  }

}


class B extends A {

  #x = "foo";

  public logB(): void {

    console.log(this.#x);

  }

}


const b = new B();

b.logB();

b.logA();

```

prints

```

foo

bar

```

this is because both at compile time and at run time **the `#x` of each class is stored and accessed entirely separately**.


Now on the other hand, if you try to do the same thing with `private`:

```typescript

class A {

  private x = "bar";

}


class B extends A {

  private x = "foo";

}

```

you get a compilation error: `Class 'B' incorrectly extends base class 'A'.  Types have separate declarations of a private property 'x'`.


Why?


Because Javascript itself treats the inheritance of these properties specially. If we try to bypass the compiler and just see how Javascript acts:

```javascript

class A {

  x = "bar";

  logA() {

    console.log(this.x);

  }

}


class B extends A {

  x = "foo";

  logB() {

    console.log(this.x);

  }

}


const b = new B();

b.logB();

b.logA();

```

this will print:

```

bar

bar

```

because in both cases **the `x` of each class is stored and accessed as the same, single property**.


On the *other* hand, there's no real reason I can think of that the compiler shouldn't allow a `private` modifier on `#` identifiers. It *would* mean changing what `private` means in those contexts. But I don't really think that's a big deal since JavaScript also treats those identifiers specially. It would make `private` accurately model how JavaScript treats class members: inheritable without `#` and not inheritable with `#`.


Here's my proposal. The compiler already treats `#` identifiers specially by disallowing access modifiers. So asking that it treat `private` differently for those identifiers isn't all that big of a change. I think you should be allowed to add `private` to `#` identifiers even though that won't mean exactly the same thing as `private` on any other identifier. The changes should be pretty minimal, because it doesn't change anything about how the compiler should actually treat the identifier; you can literally just ignore `private` if it's there.

**Comment by ocket8888** [comment]
> It's confusing

i dont agree. Adding `private` would change absolutely nothing about how the identifier is handled at compile time or at runtime. If you don't understand that `#` identifiers are special for any reason then you are not going to be able to use them without confusion regardless of if `private` is there. If anything it would help people who *don't* know that because then they probably wouldn't even have to know for the vast majority of use-cases.
