### ISSUE TITLE
Promise.catch `null` vs `null as null`

### ISSUE THREAD

**Issue by bluelovers** [microsoft/TypeScript#44913]
# Bug Report

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

> Version 4.4.0-dev.20210705

![image](https://user-images.githubusercontent.com/167966/124636135-c8423e80-deba-11eb-91f5-735464db76ac.png)

```ts
export function f1()
{
	return Promise.resolve(1).catch(e => null)
}

export function f2()
{
	return Promise.resolve(1).catch(e => null as null)
}

// @ts-expect-error
f1().then(v => v.split('')) // <====== should is `number` but `any`

// @ts-expect-error
f2().then(v => v.split(''))

```

```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2019",
    "jsx": "preserve",
    "moduleResolution": "node",
    "allowJs": false,
    "allowUmdGlobalAccess": false,
    "sourceMap": true,
    "inlineSourceMap": false,
    "inlineSources": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "allowSyntheticDefaultImports": true,
    "resolveJsonModule": true,
    "strict": false,
    "strictBindCallApply": true,
    "strictNullChecks": false,
    "strictFunctionTypes": true,
    "noImplicitThis": true,
    "noImplicitOverride": true,
    "preserveConstEnums": true,
    "forceConsistentCasingInFileNames": true,
    "incremental": true,
    "noErrorTruncation": true,
    "removeComments": true,
    "traceResolution": false,
    "newLine": "lf",
    "esModuleInterop": true,
    "importHelpers": true
  }
}

```

### 🙁 Actual behavior

```
// @ts-expect-error
f1().then(v => v.split('')) // <====== should is `number` but `any`
```

### 🙂 Expected behavior

```
// @ts-expect-error
f1().then(v => v.split('')) // <====== should is `number`
```

**Comment by fatcerberus** [comment]
I think this happens because in the absence of a type annotation, `null` gets inferred as `any`, even under `strictNullChecks`.

```ts
let x = null;  // type: any
let y = null as null;  // type: null
```

**Comment by rbuckton** [comment]
> I think this happens because in the absence of a type annotation, `null` gets inferred as `any`, even under `strictNullChecks`.
> 
> ```ts
> let x = null;  // type: any
> let y = null as null;  // type: null
> ```

That's not quite true. When outside of `--strictNullChecks` there are two `null` types: A non-widening `null` type and a widening `null` type. The widening `null` type is returned when `null` is used as an expression, while the non-widening `null` type is returned when `null` is used as a type. At any point where we widen (such as when we widen `"foo"` to `string`), the widening `null` is either removed from any union it is contained in, or is converted to `any`, while the non-widening `null` is only removed from unions if there are any other non-widening types. When inside of `--strictNullChecks`, there is only ever one `null` type, which is the non-widening `null` type. The same is also true for `undefined`.

The example you show here isn't quite correct, as the type you see when you hover over `x` isn't the _inferred_ type, it is the type resulting from control flow analysis:

```ts
// @strictNullChecks: true
let x = null;
//  ^?  let x: any

   x;
// ^?   let x: null
```
[Playground](https://www.typescriptlang.org/play?#code/PTAEAEGcBcCcEsDG0ByBXANhgwgCwKaIDWkAXKHGvgLABQG+0oAHqALygB2mGA3HSFCgAegH46dIS361BYukA)

In the example from the OP, you can see that both `number` and `null` are preserved in `--strictNullChecks`:

```ts
// @strictNullChecks: true
export function f1()
{
	return Promise.resolve(1).catch(e => null)
}

export function f2()
{
	return Promise.resolve(1).catch(e => null as null)
}

// @ts-expect-error
f1().then(v => v.split('')) // <====== should is `number` but `any`
//        ^? (parameter) v: number | null

// @ts-expect-error
f2().then(v => v.split(''))
//        ^? (parameter) v: number | null
```

[Playground](https://www.typescriptlang.org/play?#code/PTAEAEGcBcCcEsDG0ByBXANhgwgCwKaIDWkAXKHGvgLABQ+AHgA4D2s0oAZmgHbLwseXAIwAKAJR0A3nQCQsfNDSwhABVgsAtvEj4AdAsgsMAN3yjh4vYgCG0RLlH5QAXgB8oHpgyTaAXzo6RlZ2Ll5+QS4AJglpOQUlFVB1LR19Q2MzCytbe0dnd09vUBtIIqxfANo6EAhoSABaYMJoJtgNWDpOMStoAh5RE1cPEz1IJgx4aFEAchnxcVBagB4XNfXQSFwWTAATUB1QAAMvTQAjfFgj0DO0DiObHgBPI5qwUA-P0AA9AH5A2i1cD1JrMFptDpdGK9fqDYagUbjSbTOYLN5fL5-IA)

The reason why you see `any` is due to `null` being the only possible return value of `.catch`. As a result, it widens to `any` as the type escapes the body. You can see that here, though I had to replace the arrow function with a `function` expressions so I could have something to point the `^?` comment at:

```ts
// @strictNullChecks: false
export function f1()
{
	return Promise.resolve(1).catch(function(e) { return null; })
    //                              ^? (local function) (e: any): any
}

export function f2()
{
	return Promise.resolve(1).catch(function (e) { return null as null; })
    //                              ^? (local function) (e: any): null
}

// @ts-expect-error
f1().then(v => v.split('')) // <====== should is `number` but `any`
//        ^? (parameter) v: any

// @ts-expect-error
f2().then(v => v.split(''))
//        ^? (parameter) v: number
```
[Playground](https://www.typescriptlang.org/play?strictNullChecks=false#code/PTAEAEGcBcCcEsDG0ByBXANhgwgCwKaIDWkAXKAGYCGGk+AsAFD4AeADgPazSVoB2yeBz6UAjAAoAlEwDeTAJCx80NLBEAFWBwC28OgDolkDhgBu+caMn7EVaIlziK-QcPH5JoGaCUq1oPkwMAG5QAF9pRlBo0BAY+ITEpISAPQB+JjCmJlZObl4BaCERCgAmKVkFX1UNLV0DIxNzS2tbe0dnQuLQd09vav9ArFAqSACg0IimeLjkufno9MzsxjjwaEgAWlzCaG3YLVgmCglraAI+cVNQAF4APlBTfUg2DHhocQByT8lPOIAeG5A4GgSC4DiYAAmoD0oAABoFtAAjfCwOGgJFoHhwqh8ACecKYs0SS0YRLA6y2O2Q+0Ox3KZwuV1uDyeLzeH2+v3JyXSQA)

As a result, when constructing the resulting `Promise` type returned from `catch` in `f1`, the result is `number | any`, which is reduced to `any`.

Currently, this is a limitation of running outside of `--strictNullChecks`, but I'm considering whether there are any changes we can make here.

**Comment by rbuckton** [comment]
I've put up #59661, which reports an error due to the implicit widening from `null` to `any`.
