### ISSUE TITLE
Incorrect behaviour of type guards?

### ISSUE THREAD

**Issue by Motii1** [microsoft/TypeScript#44920]
# Bug Report

### 🔎 Search Terms

`type guard`

### 🕗 Version & Regression Information

`4.3.5`

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/IYIwzgLgTsDGEAJYBthjAgEhCAHAolFAPZQICmAHhOQHYAmGhJZA3gFAIKiQzwIBzchGx4AwsXrkAFAEoAXAloBXALYhyUANzsAvu3Yo0GAPIBrUQSKkK1Ooyw4rLBBy5CRTiVLmKV6zVcEKGFlKFoEACYABmitBH19Q1R0BAA5YggAMWJlBktmGyoaBgwC6zZOQWFLbxkFJTUNNmDQ8IQAFmiO+MSDI1SAEWJVYABLWkKyYvsmCqD9AYwJVVGGDOzchlsSh2HRiamF-uJaSAQxsBW1+g2cvPoEAF4EaTBlEAArcnhFKYb3l8fohLghrsB1pl7tsngA+BCA778CaQCGwcjEABmYJGNzuW3oJzOiFGuH241oABViOUWAB9NImSl0gDqJgASgBpACSaQA4s9XpoWIpyYcKg1aTY4a4qlwxtjpJdwZDNg9pMLSLJZLKuHq9SEIGEIrRyAB3dJQglSqAaioAOlU5HQwCEsh0+v0+rlrSN7VNFvMNrtLEdzrArvI7r0RPOpLFVJpTimrI5PP5gpDpFFIwp-0UNue8LceoVQvmKIgaIx2JVtytDx1Jf1XENxqU5stavyyYqWagYZdbo9eq9ep9bf9naDvZY-cHEeHeiAA
### 💻 Code

```ts
abstract class HttpError extends Error {
  abstract getHttpCode(): number;
}

class OkHttpError extends HttpError {
  getHttpCode(): number { return 200; }
}

class NotFoundHttpError extends HttpError {
  getHttpCode(): number { return 404; }
}

class DomainError extends Error { }
class CommandNotFound extends DomainError { }

const isCommandNotFound = (subject: Error): subject is CommandNotFound => subject instanceof CommandNotFound

const mapDomainToHttpError_NOT_WORKING = (error: DomainError): HttpError => {
    if (isCommandNotFound(error)) {
        return new NotFoundHttpError(error.message);
    }
    
    return new OkHttpError(error.message); <-------- Property message does not exists on type `never` 
}

const mapDomainToHttpError_WORKING = (error: DomainError): HttpError => {
    if (error instanceof CommandNotFound) { 
        return new NotFoundHttpError(error.message);
    }
    
    return new OkHttpError(error.message);
}
```

### 🙁 Actual behavior

simple type guard and its plain body pasted in `if` statement do not behave equivalently 

### 🙂 Expected behavior

simple type guard and its plain body pasted in `if` statement should behave equivalently

**Comment by MartinJohns** [comment]
This is likely due to #17344 and intentional.

In general having "empty" classes is code smell, unless you make them nominally typed (have a `private` or `protected` member). There's no difference between `Error` and `DomainError`, they're essentially the same. And `instanceof` has a gotcha in TypeScript: Because classes with only public members are structurally typed, you can assign a matching object literal. `instanceof` will fail, but TypeScripts type-system will assume it will always match.

Also you extend `Error` wrong. see: https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-extending-built-ins-like-error-array-and-map-work
