### ISSUE TITLE
Object assign-ability is not strict when inferred via a function with a generic param

### ISSUE THREAD

**Issue by sharshuv-quotient** [microsoft/TypeScript#45042]
# Bug Report

### 🔎 Search Terms

Object assign-ability is not strict when inferred via a function with a generic param

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&noUnusedLocals=true&noUnusedParameters=true&strict=true&noFallthroughCasesInSwitch=true&noImplicitOverride=true&noPropertyAccessFromIndexSignature=true#code/GYVwdgxgLglg9mABDAJgUzLKBPAPAcQD4AKAcwC5F8BKS-RAbwChFEAnNKENpUgbiYBfJkxiY0bYAEMIaRAFlsASXGSZc5q1SUAzlDZj+QkRAR7EUyopVQJ02YgC8jFshSUA5AEYPAGiF8iAD0QYgADlI6Omg6FrFoAB5haNBoKEymYOYARlbKqvZyzgyIrtqI3n6u2JRerCGI0jAANrGRiInJqemCAkygkLAIiKSc1gXqXsS0Cvm2ag4lDRFRMXEdSSm26awcXDwurFruFT7+rL3G-eDQ8Lxjc3bqAEzTeTZPi6573EglrsdPGcAYgaogvL56qEmq11p0tmlXJdhNdBncRg8Pgs0ABmN6zLGFRjBUIraJteKbbrfTi-NwYLDYYiaI7lSpI6gCFEDW7DUZQcbzQoAFnxgs+Ghp+yQqAZMBwzNKRzcQKqyrBdWWkXJkOyICgGy620QUDgjSkLQ5XJEPKG9wFj2xAFYxY6iSyfgdZZh5XhxdiSP9lWzgerapCGjCKYaETtEIJOUIgA)

### 💻 Code

```ts
function identity<G>(g: G): G {
  return g;
}

interface MyInterface {
  id: string;
}

function getMyInterface(): MyInterface {
  return identity({ 
    id: '1',
    y: 1 // passes, but expected to fail
  });
}
```

### 🙁 Actual behavior

The code compiles without errors. 
This is wrong because it results in an object that is thought to be of type MyInterface, but actually has a property "y" which does not exists on "MyInterface". (This is especially a problem if y is a typo of an optional property on MyInterface, which will break the code silently)

### 🙂 Expected behavior

Typescript should infer that the generic param of identity must be MyInterface for the method "getMyInterface" to return the right type, and not allow the non-existing property y on the object. 

**Please note the following, very similar cases, where the code behaves as expected:**
```ts
const b: MyInterface = { 
  id: '1',
  y: 1  // fails as expected
};
```
```ts
function getMyInterface(): MyInterface {
  return { 
    id: '1',
    y: 1,  // fails as expected
  };
}
```
```ts
function getMyInterface(): MyInterface {
  return identity<MyInterface>({ 
    id: '1',
    y: 1, // fails as expected
  });
}
```

**Comment by fatcerberus** [comment]
In general, objects are allowed to have extra properties.  In the presence of an explicit type annotation, you get excess property checking for object literals, but otherwise, objects with additional properties are assignable to types with fewer, as long as the subset of properties named in the type match.  This is by design.

Your first example doesn’t produce an error because `identity()` is generic, so its type parameter is inferred according to the object literal passed in - there is no context for which to do excess property checks. From there, the function returns an object which is indeed compatible with `MyInterface` because it contains an `.id` property which is a string.  It’s not different from first assigning the object literal to a local variable with an inferred type and then returning the variable.

When you provide the type parameter explicitly, you get an error because the type of `identity()`’s parameter is then `MyInterface`, and TS does excess property checking on the object literal.  But in general, you can’t prevent excess properties—you would need [Exact Types](https://github.com/microsoft/TypeScript/issues/12936) for that.
