### ISSUE TITLE
Contextual inference not working in "nested" scenarios, inferred type is never

### ISSUE THREAD

**Issue by kucharskimaciej** [microsoft/TypeScript#45041]
# Bug Report

### 🔎 Search Terms

Contextual inference 
Does not exist on type 'never'

### 🕗 Version & Regression Information

Tested in 4+, and this is the behavior in every version I tried.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.0-beta#code/FAFwngDgpgBAsgewCYFcA2UDqBLEALAZRAEMQoAeAFSNKgD4YBeGAb2Bg5gGcSyAuGNV5QA3MAC+wUJFg0yTVu07EBAOxQBbAEZQATmMnTo8BLqhzYzNpxgAvAT13ZVAcwNSAZilUBjENgRVGB8zWkRUDCoLABpBAEE-ANUuOgAKHloBIVpY4kTAriyE-wKASgFw9CxcQmEo4QYAMnj85MUbMxAUXSDrG04MsmilfpgAOgm8kuSRmElDL19p4MCANz0QepyW6ZTUjQrkKpx8Cy2yJp2krnKTCOrTuuz5ZsQzC0vKYuv2zk7u3qzGwTMYaYajDiDKACPoQzggjRjKHguGcewwABEWgQCAxQM44mGs3mUmAPgKIBgWlCAGsuApyap1roQKlZiEoGEjhhUrD+ioYABGABMxNifJsHhxqVKv1RMH+PRgIF0KCg+I4khs4lKwFKYmpnLpY2IwENxGNthlZtpXDGUoQ1rJFJgGmQDNCZEqPL5ApFEnFswdMrl-UVQRVauJEl1zuSlIA7qY6Qy1ht9sh9cAk7pjcHY0A)

### 💻 Code

```ts

type ModuleWithState<TState> = {
    state: TState;
}

type State = {
    a: number;
}

type MoreState = {
    z: string;
}

function createModule<TState, TActions>(state: TState, actions: TActions): ModuleWithState<TState> & TActions {
    return {
        state,
        ...actions
    }
}

function convert<TState, TActions>(m: ModuleWithState<TState> & TActions): ModuleWithState<TState & MoreState> & TActions {
    return {
        ...m,
        state: {
            ...m.state,
            z: "boo"
        },

    }
}


const breaks = convert(
    createModule({
        a: 12
    }, {
        foo() {
            return true
        }
    })
);

breaks.a; // Property 'a' does not exist on type 'never'.
breaks.z; // Property 'z' does not exist on type 'never'.
breaks.foo() // Property 'foo' does not exist on type 'never'.

const mod = createModule({
    a: 12
}, {
    foo() {
        return true
    }
})

const works = convert(mod);
works.a; // number
works.z // string
works.foo();
```

### 🙁 Actual behavior

The first scenario (`breaks`) fails the infer the correct type of the passed argument. Second scenario `works` works as expected. The only difference between the two is that in the latter the argument is first assigned to a variable.

### 🙂 Expected behavior

Both scenarios work exactly the same.

**Comment by devanshj** [comment]
You probably meant to write `breaks.state.a`, `breaks.state.z`, `works.state.a` and `works.state.z` (because that is what is expected to work according to the runtime code and types). Also your playground link is inconsistent with the code.

This seem to be related to #40439. Because if you make `foo` a non-function say `true` then it starts [working](https://www.typescriptlang.org/play?ts=4.4.0-beta#code/FAFwngDgpgBAsgewCYFcA2UDqBLEALAZRAEMQoAeAFSNKgD4YBeGAb2Bg5gGcSyAuGNV5QA3MAC+wUJFg0yTVu07EBAOxQBbAEZQATmMnTo8BLqhzYzNpxgAvAT13ZVAcwNSAZilUBjENgRVGB8zWkRUDCoLABpBAEE-ANUuOgAKHloBIVpY4kTAriyE-wKASgFw9CxcQmEo4QYAMnj85MUbMxAUXSDrG04MsmilfpgAOgm8kuSRmElDL19p4MCANz0QepyW6ZTUjQrkKpx8Cy2yJp2krnKTCOrTuuz5ZsQzC0vKYuv2zk7u3qzGwTMYaYajDiDKACPoQzggjRjKHguGcewwABEWgQCAxQM44mGs3mUmAPgKIBgWlCAGsuApyap1roQKlZiEoGEjhhUrD+ioYABGABMxNifJsHhxAhAuhQUGJpWApTE1M5dKRwjGxGAauIGqhY1sutpXDGUoQUkZPBgGmQDNCZEqPL5ApFEnFswtqVKv1G-x6MFl8uJEiVZIpMAA7qY6Qy1ht9sgVcAY7oDVqdWmM7QjanY2aLVIgA).

**Comment by RyanCavanaugh** [comment]
@ahejlsberg the behavior in the playground link seems bad. Thoughts? Possibly related to #44476 (not sure) ?

**Comment by ahejlsberg** [comment]
@RyanCavanaugh It's a simple issue of not properly propagating the special `silentNeverType` in intersections. Trivial fix, will have a PR up soon.
