### ISSUE TITLE
TS6133 error when augmenting an interface in external module using a type from the same module

### ISSUE THREAD

**Issue by katemihalikova** [microsoft/TypeScript#45061]
# Bug Report

### 🔎 Search Terms

declare module, augment, TS6133

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (2.0, 2.5, 3.0, 3.5, 3.7, 4.0, 4.1, 4.2, 4.3, beta, next), and I reviewed the FAQ for entries about merge/merging/augment/declare.

### ⏯ Playground Link

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?noUnusedLocals=true#code/PTAEAEDsHsFVIK4GcCmATAMtAxgQwDZIBQJIoAKikgC6h6qgCMAXKAIIIDmAtipNQEtInUEOooATgDNc2FKMigUAD3ETIBUN2hoE+FADpQAMVwDCoAO4DqACwoBlAGyMAzK9YByB9F7kAngAOKJ6iSKBoKNj4uBLooABGCLQ24QBuBAjyAuGQKGmSoHG4aAZEZOBS5ny4vKziNIwG1MQVkhLQEkisLu5EAtyBnbQA3qA+fkHyAL6gUh3coJ4N1AC02rr6jJ4A3CSR0bHyG3ryy1RrJ1uhI0SgCmoycqBYeILQkADCtrjCKACiBX4oFu93uJUiaAACh1ghJqP5WBMUAFgnt7tMiJjymBKtUNHVQDBIgB9K5UYArdY6U6MYBCSLKAylFpEFRDeEPSRPeTI1HyUGgJC+FB2IScLy2SQhPaY9nDLnSWTyABKvzQvgAkvxucqQUQAJCdAScIQEGHQOEIpEi-mykg4igXOi4BgAJlYAHkANIAGi0uH8CXkdmygwVOSJ0FoeXQ6AA-KAAHLQSyiWgyczhax2Rxu1wABgALKxPr8YBmGUTamc+VNPGUKlV9ASUPULm7mq1ce1Ot1QPni0QDjE4loafollTyW6bndFTyXjhcO8vj8-oC+KN5+C0JCLVbEeNbVN0aBMdim-ia6xiSgyROKdPH276ZBGcyu2zlByUjqlc8dbBPq9zCrwYrCJK0q7Fi36-guepqu+Wr-outxGhIJpmvgB6SNax6TGisFAA)

### 💻 Code

```ts repro
// @noUnusedLocals


// Test case 1: Augmenting interface in external module. Fails with TS6133: 'SomeType' is declared but its value is never read.
// @filename: test1.ts
// @errors: 6133
import { SomeType } from 'test-module1';

declare module 'test-module1' {
  interface LocationChangeEvent {
    addedProperty: SomeType;
  }
}

// @filename: node_modules/test-module1/index.d.ts
export interface SomeType {
  something: 'here';
}
export interface RandomInterface {
	originalProperty: SomeType;
}


// Test case 2: OK, maybe the import is not needed? Now it fails with TS2304: Cannot find name 'SomeType'.
// @filename: test2.ts
// @errors: 2304
declare module 'test-module2' {
  interface LocationChangeEvent {
    addedProperty: SomeType;
  }
}

// @filename: node_modules/test-module2/index.d.ts
export interface SomeType {
  something: 'here';
}
export interface RandomInterface {
	originalProperty: SomeType;
}
```

### 🙁 Actual behavior

`noUnusedLocals` is `true`. Trying to augment an interface (using interface merging) from an external module by adding a new property of type that is imported from the same module.

➡️ TypeScript fails with error `TS6133: 'SomeType' is declared but its value is never read.`

_Sanity check:_ Maybe I misunderstood something? Let's try to listen to TypeScript and remove that import.

➡️ TypeScript fails with error `TS2304: Cannot find name 'SomeType'.`

### 🙂 Expected behavior

I expect the import used in module augmentation to be not marked as unused.

**Comment by andrewbranch** [comment]
The trick is that `SomeType` is in scope in the module augmentation, but when you remove the unused import, `test1.ts` ceases to be a module at all, and so `declare module 'test-module1'` becomes an ambient module declaration rather than a module augmentation, putting `SomeType` out of scope again (not to mention defeating your attempted augmentation entirely). You need to delete the `SomeType` import, but keep `test1.ts` a module. You can do that simply by adding an `export {}`.

https://www.typescriptlang.org/dev/bug-workbench/?noUnusedLocals=true#code/PTAEAEDsHsFVIK4GcCmATAMtAxgQwDZIBQJIoAKikgC6h6qgCMAXKAIIIDmAtipNQEtInUEOooATgDNc2FKMigUAD3ETIBUN2hoE+FADpQAMVwDCoAO4DqACwoBlAGyMAzK9YByB9F7kAngAOKJ6iSKBoKNj4uBLooABGCLQ24QBuBAjyAuGQKGmSoHG4aAZEZOBS5ny4vKziNIwG1MQqgdAStADeAL4kkdGx8tq6+qCeDdQAtCN6KIyhXUSgCmoycqBYeILQkADCtrjCKACiBfygSysrJZFoAAoS0MGd-qw+fkEoANzLoH19cpgSrVDR1UAwSIAfVm+iQwEmMx0c0YwCEkWUBlKLSIbQ6KX4knW8g+KACwUufyQvhQdiEnC8tkkIV+fTxnVWRNk8gASkc0L4AJKE6TcykASA6Ak4QgIj2ekmob1ApPJPyIgKBECq+jBKFYUmg0GaxAE3HaHK6mxwuB2+0OxzOfFoPVAUie3FAACJEbD5l7fvpaMpWFtbQJdgcjpxTudqABtTy3dDyl5KzwAXVAAF5Lj1fkA

**Comment by katemihalikova** [comment]
Thanks a lot, totally missed that. #9748 should have led me into the right direction. Thank you for your time!

For reference, when trying it in a minimal reproduction project, I got `TS2664: Invalid module name in augmentation, module 'test-module' cannot be found.` error. It went away after I actually used the module (import) somewhere else in the project.
