### ISSUE TITLE
Unexpected `any` with project references

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#45071]
# Bug Report

### 🔎 Search Terms

project references composite fromEntries lib dom iterable function return type

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about project references

### ⏯ Playground Link

N/A

### 💻 Code

Full reduced test case: https://github.com/OliverJAsh/ts-project-references-any-bug

Contents inlined below.

`shared/tsconfig.json`:
```json
{
    "compilerOptions": {
        "rootDir": "..",
        "outDir": "../target/",

        "composite": true,
        "lib": ["DOM", "DOM.Iterable", "ES2017", "ES2019.Object"]
    }
}
```

`shared/url-helpers.ts`:
```ts
export const toDictionary = (
    urlSearchParams: URLSearchParams,
  ) =>
    Object.fromEntries(urlSearchParams.entries());
```

`app/tsconfig.json`:
```json
{
    "compilerOptions": {
        "rootDir": "..",
        "outDir": "../target/"
    },
    "references": [
        {
            "path": "../shared/tsconfig.json"
        }
    ]
}
```

`app/test.ts`:
```ts
import { toDictionary } from "../shared/url-helpers";
const test = toDictionary(new URLSearchParams());
test;
```

### 🙁 Actual behavior

The type of `test` in `app/test.ts` is `any`.

![image](https://user-images.githubusercontent.com/921609/125983718-612af082-9bcf-4ab1-89f6-e6d73e6e214b.png)

### 🙂 Expected behavior

The type of `test` in `app/test.ts` should be `{ [k: string]: string; }`.

### Notes

When I inspect the definition of `toDictionary`, I can see it has the correct inferred return type:

![image](https://user-images.githubusercontent.com/921609/125983698-e13cd3cc-8a75-47ff-b4ba-6223046c2c93.png)

However, when I try to use `toDictionary` in another module, the return type appears as `any`:

![image](https://user-images.githubusercontent.com/921609/125983804-1b13f141-66ce-4b87-bbc3-f8c8842e1c3a.png)

Note there are 0 build errors when I run `tsc --build --verbose app/tsconfig.json`.

**Comment by andrewbranch** [comment]
This is completely expected and explainable, but not great. Your `shared` project includes `dom.iterable`, which augments the `URLSearchParams` interface in a way that makes it use a resolve overload of `Object.fromEntries(urlSearchParams.entries())` than it does in your `app` project, which lacks that augmentation. The editor, by default, uses the source files, not the built .d.ts files for referenced projects, which means it has to infer the return type of `toDictionary`. If you enable `disableSourceOfProjectReferenceRedirect`, and when you run `tsc --build`, it uses the declaration files instead, which include the return type annotation `{ [k: string]: string }`, so that’s obviously what you get there.

I’m not sure what we could/should do differently here. I think the best workaround is to add an explicit return type annotation on `toDictionary` since it’s dependent on lib inclusion, and you’ve intentionally set different libs in your different projects.

**Comment by OliverJAsh** [comment]
Interesting, that makes sense.

I guess this highlights a difference in type checking between the editor and `tsc --build`. I wonder if there's a way to make the editor match the behaviour of `tsc --build` without resorting to `disableSourceOfProjectReferenceRedirect`. I understand the downside of `disableSourceOfProjectReferenceRedirect` is poor dev UX (you have to run `tsc --build` before you can use the editor). Perhaps TS could build dependencies from source on the fly, so the dev UX still feels seamless but it's always consistent with the behaviour of `tsc --build`?
