### ISSUE TITLE
[Types Feature Request]: MediaStreamTrack['kind'] can use enum instead of string

### ISSUE THREAD

**Issue by upupming** [microsoft/TypeScript#45090]
https://github.com/microsoft/TypeScript/blob/a84ca309e077aed2c1d9e05793e28ea869c81561/lib/lib.dom.d.ts#L10033-L10038

As per the [w3c spec](https://www.w3.org/TR/mediacapture-streams/#attributes-1), the `kind` attribute is an enum, and can only be `audio` and `video`. So can wen change the `kind` to an enum type for a more specific type? If I am mistaken, please let me know, thanks!

**Comment by andrewbranch** [comment]
I see how you could read it that way, but if you look closer, that’s not what the spec says.

> **`kind` of type `DOMString`, `readonly`**
>
> The `kind` attribute MUST return the string `"audio"` if this object represents an audio track or `"video"` if this object represents a video track.

1. Just reading it logically, it doesn’t say that `kind` can’t be any other value, just that if the object represents an audio track it must be `"audio"` and if the object represents a video track it must be `"video"`. The spec leaves open the possibility that the object represents something else entirely, in which case it does not specify what value `kind` must be.
2. English is a messy language and even technical documents can be written ambiguously or misinterpreted. However, we know that the spec does not intend `kind` to be an enum, because the spec [actually defines and uses enums](https://www.w3.org/TR/mediacapture-streams/#dom-mediastreamtrackstate) where enums are appropriate. If they intended `kind` to be limited to `"audio"` or `"video"`, they would have defined an enum for it.
