### ISSUE TITLE
Recursive self-type inference

### ISSUE THREAD

**Issue by danieldietrich** [microsoft/TypeScript#45100]
# Bug Report

### 🔎 Search Terms

* [recursive self type](https://github.com/microsoft/TypeScript/search?q=recursive+self+type&type=issues)
* [generic type self reference](https://github.com/microsoft/TypeScript/search?q=generic+type+self+reference&type=issues)
* [recursive generic type](https://github.com/microsoft/TypeScript/search?q=recursive+generic+type&type=issues)

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _generics_, _self reference_, _unification_.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.0-beta#code/FAehAIHcFNwVwM6wIbgObQHbQE4EsBjcAB2R2QFtoAXXcage3D0wCtoDr6ALWAhzLQAeXBgDNwyADZSGMACbN5CADjBqAT2KwA8gCNWAHgCS8gHzgAvOADeSgFzhTAGnA5oYgPyPT4AL7AoBDcctAAbriuMJJSCEyQyIL0TCxidNS84EhceMrgYjgMFJJZ0ACO0HBYBLDi4PqsCOpasACqmHgCOmKmCIYAKuDQIlh5DYZwmADWmHKYZgDaALoW1v0LmHAUerhLCwDkuftLgWDggKDk9C3g-dAIXNYARGIMDI-gAD7gj3pkj83aG53B7gdqdTDdXqGBbAcBw2wOcD7F4MfZ+Zyw+F2XKOfa-HBo4ArU4QQB8G4AQveYmDSOFpLDQJSQUgk7gIcBwCDwESugMY4DC0lyyFozBZHgQknc-MFilyTXkHCkZFgYkmnHB4AIvAIUwGQxGmDGBkMYK6PWUAzMixWAAoGAYEI5+gBKRxhBi5EkXYBajhTG0w+EInFIlH7fwYoPY+S4-H7VzuMS4sMRonOr2AGXJwABhHQAWQACsYADIAUQAyuAAEKtQbGcClgAaBdL2f6pYAIuAAII5-NFssNgBKQ50Q592v9gaxiORr3D6MxcOjsbI8bcHlxs2oAFpEjvhnh7vSd0dU0t00A)

### 💻 Code

```ts
// we use a generic parameter to inject the context of allowed ids
type Obj<Id> = { id: Id, ref?: Id }

// however, we also want to infer the set ids from a seqeuence of Objs
type UnionOfIds<T extends Obj<unknown>[]> = T[number]['id']

// inferrring a self recursive type to validate if refs are valid ids
declare function check<T extends Obj<UnionOfIds<T>>[]>(objs: T): void
```

### 🙁 Actual behavior

The following `ref` is not a valid id `'foo' | 'bar'` but it compiles.

```ts
check([
    { id: 'foo' },
    { id: 'bar', ref: 'not-an-existing-id' }
])
```

### 🙂 Expected behavior

The compiler should produce an error and emit a message like:

```
Type '"not-an-existing-id"' is not assignable to '"foo" | "bar" | undefined'. (2322)
```

**Comment by whzx5byb** [comment]
Arrays are mutable, so `[{ id: 'foo' }, { id: 'bar', ref: 'not-an-existing-id' }]` is inferred as `Obj<string>` instead of `Obj<'foo' | 'bar'>`.

To produce your expected behavior, you should declare the argument as const.
```
type Obj<Id> = { id: Id, ref?: Id }
type UnionOfIds<T extends readonly Obj<unknown>[]> = T[number]['id']
declare function check<T extends readonly Obj<UnionOfIds<T>>[]>(objs: T): void
// Notice the 'readonly' modifier above

check([
    { id: 'foo' },
    { id: 'bar', ref: 'not-an-existing-id' },
] as const)
// Error as expected
```

[Playground](https://www.typescriptlang.org/play?ts=4.4.0-beta#code/FAehAIHcFNwVwM6wIbgObQHbQE4EsBjcAB2R2QFtoAXXcage3D0wCtoDr6ALWAhzLQAeXBgDNwyADZSGMACbN5CADjBqAT2KwA8gCNWAHgCS8gHzgAvOADeSgFzhTAGnA5oYgPyPT4AL7AoBDcctAAbriuMJJSCEyQyIL0TCxidNS84EhceMrgYjgMFJJZ0ACO0HBYBLDi4PqsCOpasACqmHgCOmKmCIYAKuDQIlh57sjyAlIa9QaGcJgA1phymGYA2gC6Ftb965hwFHq4m+sA5Llnm4Fg4ICg5PQt4P3QCFzWAERiDAwf4AA+4A+ejIH2a2mer3e4HanUw3V6hnWwHAqNsDnAZ2+DDOfmcKLRdlyjjOIJwuOA2xuEEAfBuAEL3mJg0jgWSw0CUkFIJO4CHAcAg8BFHhDGOAwtJcshaMxuR4EJJ3GKJYpck15BwpGRYGIFpw4eACLwCIsBkMRpgxtAJlMZg1DLCuj1lAMzBttgAKBgGBCOfoASkcYQYuWp92Aho4i3dyLR6OJmOxZ38+NjRPkJLJZ1c7jEJMTycpknl-Ewbz9obu4aNUZjhIxWJ+SbxBNRaYzZCzbg8JJW1AAtIk+8M8G82X3LgXNkWDQIy8AgA)

**Comment by danieldietrich** [comment]
Thank you @whzx5byb, that makes absolutely sense to me. One more reason that I am looking forward to [records #{} and tuples #[]](https://github.com/tc39/proposal-record-tuple).

I will close this issue, this works as designed.

Thank you for your help!
