### ISSUE TITLE
overridden method with narrower input shouldn't be allowed

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#45142]
# Bug Report

### 🔎 Search Terms

method override narrow input

### 🕗 Version & Regression Information

4.4.0-dev.20210721

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=next#code/MYGwhgzhAEBiD29oG8BQ0PQEZgE4ApIATAMwH4AuAOwFcBbLAU1wEoVV1MBfVH1USDABCYAF7RGADwAujKkRgIkaTNjyEIpCtFoNmbFaszB4VCPBCMAdCHgBzDaSvT4AZWm4AllQcsWnDB4+EzNpaBJEbSVoAF4dRgB3aBFRfH9UCPgrHAI2AHo8qiRmXHhcABpwsE8QGDAw3BoqaU86RmxGYDAaCHbiEmhPGCKwokYSb0YiaCA)

### 💻 Code

```ts
class Foo {
    bar(asdf?:number) {

    }
}

class Baz extends Foo {
    bar(asdf: number) {
        console.log(asdf.toString())
    }
}

const foo: Foo = new Baz()

foo.bar() //no error, fails at runtime because asdf is not defined 
```

### 🙁 Actual behavior
no compile error, fails at runtime

### 🙂 Expected behavior
type error

**Comment by IllusionMH** [comment]
Methods are always bivariant even with `strictFunctionTypes` enabled. See https://github.com/microsoft/TypeScript/pull/18654

You need to use function properties instead. [Example](https://www.typescriptlang.org/play?ts=4.4.0-dev.20210721#code/MYGwhgzhAEBiD29oG8BQ0PQEZgE7QF5oAKSAEwDMB+ALgDsBXAWywFNcBKQgPhVXUwBfVMNShIMAEJgAXtFYAPAC6s6ZGAiRpM2PIRLkKNaIxbsuBXtp2Zg8OhHghWAOhDwA5qQiUXS+ADKSrgAlnReHBwCGMKidg5K0BSIxpr6dKwA7tDSMsRRqMnwLji4+dAA9BV0SOy48LgANElgISAwYIm4DHRKIUys2KzAYAwQg4bQITA1iWSsFGGsZNBAA)

**Comment by MartinJohns** [comment]
This behavior is mentioned in the FAQ.

**Comment by DetachHead** [comment]
@MartinJohns my bad, though it's easy to miss that because the example used makes it look like an explanation for using generics.

https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant

```ts
function trainDog(d: Dog) { ... }
function cloneAnimal(source: Animal, done: (result: Animal) => void): void { ... }
let c = new Cat();

// Runtime error here occurs because we end up invoking 'trainDog' with a 'Cat'
cloneAnimal(c, trainDog);
```

at first glance this looks like it has nothing to do with variance and that the solution would be to simply use a generic:

```ts
function cloneAnimal<T extends Animal>(source: T, done: (result: T) => void): void { ... }
```

**Comment by dgreensp** [comment]
Now that we have the `override` keyword, could TypeScript check that the method argument types are appropriate when it encounters `override`?

The original example above is pretty egregious, and in a codebase that makes heavy use of subclassing, it's a pretty big hole in the type system and potential source of bugs.  For example, I just changed a method argument type to a less specific type, and TypeScript doesn't mind that the subclasses that override that method still expect the more specific type, because method overrides can narrow the types of their arguments, even though that is nonsensical.  Note that it's not practical to work around this issue by eschewing method syntax for function syntax everywhere (e.g. when implementing methods in classes).

Could adding checks to `override` be a way to address this without changing assignability rules?
