### ISSUE TITLE
Indexable type checking is weird

### ISSUE THREAD

**Issue by donggyu04** [microsoft/TypeScript#45175]
Indexable type checking is weird.

### 🕗 Version & Regression Information

typescript: 4.3.5

### 💻 Code

```typescript
// test.ts

type keyValueType = {
    [key: number]: number;
}
const makeObject = (key: string, value: number): keyValueType => ({[key]: value});
console.log(makeObject('Hello', 3));
```
### 🙁 Actual behavior
```
tsc test.ts
node test.js

{ Hello: 3 }
```
### 🙂 Expected behavior

```
tsc test.ts --> error Type '{ [x: string]: number; }' is not assignable to type 'keyValueType'
```

**Comment by fatcerberus** [comment]
Why wouldn't that work?  The `number` index signature just says what the type is for *number* keys, but you're allowed to have other keys.  Same reason `{ foo: string, bar: string }` is assignable to `{ foo: string }`.

**Comment by ilogico** [comment]
> Why wouldn't that work? The `number` index signature just says what the type is for _number_ keys, but you're allowed to have other keys. Same reason `{ foo: string, bar: string }` is assignable to `{ foo: string }`.

That's true, but doesn't apply here because it's a fresh object and the function is annotated with a return type, so excess property checks should prevent you from doing this.

TypeScript is only allowing the creation of `string` properties, not `'foo'` or `'bar'` properties:
```ts
interface D {
	[index: number]: number;
}

var a: D = { ['foo']: 42 }; // error
var b: D = { ['bar' as string]: 42 }; // OK

b['x']; // error
b['y' as string]; // error

b['x'] = 42; // error
b['y' as string] = 42; // error
```
[playground](https://www.typescriptlang.org/play?ts=4.4.0-dev.20210724&ssl=12&ssc=32&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgCLIN4FgBQBIAbVABMIAPALmRAFcBbAI2gF0rbHoBuXAX11wBucKMjhV0AXkzICAchgB7BbNbIALACZkPTsgD0e5NCgKog4cgbjkUjDNkNhs0QGdkLsFFABzVZu26BsgA8gDS-DgMcmQqgYbGprhRsgCeznBuHl4gvnFGUCZmOEnRKjbqGnkJRclpru6ePszlmlUFpkA)

It's hard to see how this can be intentional.

**Comment by fatcerberus** [comment]
In that case it looks like this is a duplicate of #36920.

**Comment by donggyu04** [comment]
@fatcerberus @ilogico 
Thank you for your kind ans.
