### ISSUE TITLE
Auto-array typing not working in 4.4

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#45188]
```ts
function unique(elems: string[]) {
    const arr = [];
    for (const e of elems) {
        if (!arr.some(x => x === e)) {
            arr.push(e);
        }
    }
    return arr;
}
```

**Expected**: The type of `arr` is `string[]`.
**Actual**: An error under `noImplicitAny`.

```
Variable 'arr' implicitly has type 'any[]' in some locations where its type cannot be determined.
```

[Playground Link](https://www.typescriptlang.org/play?useUnknownInCatchVariables=true&ts=4.4.0-dev.20210726#code/GYVwdgxgLglg9mABOGBHEBTAFBgNhgWwGcAuRIqAJxjAHMBtAXQEpEBvAKEW8QgQsQBDSpUQBeREwDcXHsDiisfMAIyI4wRHkJFWnHgcQxNWAITDKAOiJwC2AB7iAfIkdj3W5ntmHDFywAOIEQAFjjMMr7cAL4+iLEGlBhQIJRIFjLRQA)

Originally found in #45117, reported by @mkubilayk.

**Comment by Kingwl** [comment]
Possible related with https://github.com/microsoft/TypeScript/issues/40359 ?

**Comment by ahejlsberg** [comment]
This is working as intended. We complain about `arr` having an implicit `any[]` type because it is possible for control to reach the `arr.some(...)` call before any elements have been added to the array. It's equivalent to what happens in this example:

```ts
const a = [];
if (!a.some(x => x === 'foo')) {  // Error, a implicitly has type any[]
    a.push('bar');
}
```

Now, you could argue that the implicit `any` types don't matter because when the array is empty the arrow function is never called. But that's only because we know the semantics of the `some` method. It's not a general assumption we can make.
