### ISSUE TITLE
Incorrect Object.assign return type

### ISSUE THREAD

**Issue by AndreyKuznetsovQS** [microsoft/TypeScript#45215]
# Bug Report

### 🔎 Search Terms

object.assign return type

### 🕗 Version & Regression Information

Faced this problem in the 4.3.2 version and checked on 4.3.5, 4.4.0-beta(problem still exists)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.5#code/C4TwDgpgBAyg9gWwgEQIbFVAvFA3lVALigDsBXBAIwgCcoBfAbgChmBjOEgZ2CgHMIweEjQZsUABQBKYsJTpMAHyhkSAEwgAzAJYkIa7AD48zKFBqCyNEivVbd+lvVYB6F1AgAPSG2D6oagpQoJCyiPJiyqoaOnpqzG4EvmSoADYBQSEQYSIK7Jw8GWI4APKUAFYQvgB0qFxc2nwkErj0ADT8gnKiqNJSQA)

### 💻 Code

```ts
type SomeData = { a: number };

const getSomeData = (): SomeData | undefined => {
  return undefined;
}

// expected data type: SomeData | undefined
// actual data type: SomeData
const data = Object.assign({}, getSomeData())

```

### 🙁 Actual behavior

Incorrect type inference

### 🙂 Expected behavior

Correct type inference

**Comment by MartinJohns** [comment]
> // expected data type: SomeData | undefined

Why would you expect `undefined`? That can never be the result. I'd rather expect something like `{ a?: number }`.

**Comment by jcalz** [comment]
The return type of `Object.assign()` is modeled as the intersection of the types of the input values, which is a rough approximation of what actually happens.  It's a simple heuristic and is good enough to be useful, but there are edge cases (see #31982, #44983, #45034, #43110).  It is possible to get a better approximation, but at the expense of being a lot more complicated and so far nobody has decided it's worth it to do that. 

In this example, the compiler sees `Object.assign({}, undefined)` as returning `{} & undefined` which is `never`, while what actually gets returned is of type `{}` (not `undefined`, as @MartinJohns points out).  So the right return type for `Object.assign({}, getSomeData())` is something like `SomeData | {}` (or possibly `Partial<SomeData>` since you know that the value `{}` has no `a` property).  

In the likely case that this will be closed as a design limitation, you should probably just work around it by [asserting](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-assertions) it like `Object.assign({}, getSomeData()) as Partial<SomeData>`.
