### ISSUE TITLE
Missing autocomplete on the "abstract" keyword

### ISSUE THREAD

**Issue by pushkine** [microsoft/TypeScript#45260]
# Bug Report

### 🕗 Version & Regression Information

ts stable & nightly

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAYwDYEMDOa4DEITgbwF8g)
    
### 💻 Code

```ts
export class Foo {}
```

<img width="415" alt="Code_2021-08-01_08-43-51" src="https://user-images.githubusercontent.com/30108880/127761997-0627bb01-0393-4bdb-84a0-bda9d332747c.png">

**Comment by heyAyushh** [comment]
@DanielRosenwasser I want to work on this. 
How do I get started?

**Comment by DanielRosenwasser** [comment]
The fix will likely start in `src/services/completions.ts` and you should start with a failing test in `tests/cases/fourslash/`.

**Comment by fabioemoutinho** [comment]
is this related?
https://github.com/microsoft/TypeScript/pull/34491

**Comment by sourabh112** [comment]
Hi @DanielRosenwasser, I would like to work on this issue if no one else is working on it. As I'm quite new to this, I might need your guidance for a lot of things.

**Comment by DanielRosenwasser** [comment]
If @heyAyushh isn't still working on this, go for it, but I would encourage you to explore/familiarize yourself with the surrounding code I've pointed out above, and look to those PRs to get a sense of what sort of work this change might involve.

**Comment by heyAyushh** [comment]
Yes @DanielRosenwasser , I haven't started contributing as I am exploring typescript source code right now. 
If there's a resource let me know.

I also didn't have the resources for testing docker.

**Comment by DanielRosenwasser** [comment]
You don't need to use Docker to contribute, using a container is just an option if you find that helpful.

**Comment by sourabh112** [comment]
@DanielRosenwasser, I was looking at the code of file `src/services/completions.ts`.  and found this piece of code.
https://github.com/microsoft/TypeScript/blob/59b8bef3e721262a62dba1612a3e0d14e7507f31/src/services/completions.ts#L3015-L3028
I think Abstractkeyword should not be placed here because it can be used anywhere not only in classes. So, I was thinking of removing it from here and adding it places for global completion following #34491. Then I will run the test on `tests/cases/fourslash/` and make changes if needed.

Please confirm, If I'm going in the right direction. If not then please correct me, As it is my first time working on TypeScript.
