### ISSUE TITLE
Type alias not recognized when tagged intersection is used as Record key.

### ISSUE THREAD

**Issue by alessioprestileo** [microsoft/TypeScript#45408]
I have defined a tagged intersection as explained here:
https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes-func.html#type-aliases
and I'm using that type as the keys of a Record.
It works fine as long as I use the record type directly:
```
type Selector = string & {
    __tagSelector: never;
};

const a: Record<Selector, number | undefined> = {};
```
In this case, when I hover on `a` I get
`const a: Record<Selector, number | undefined>`.

It stops working if I define a type alias:
```
type Selector = string & {
    __tagSelector: never;
};
type MyRecord = Record<Selector, number | undefined>;
const a: MyRecord = {};
```
In this case, when I hover on `a` I get 
`const a: MyRecord`
but when I hover on `MyRecord` I get
`type MyRecord = {}`.

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions. Specifically, it's not clear what the expected behavior is.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.

**Comment by alessioprestileo** [comment]
@RyanCavanaugh 
I'm sorry, I didn't get any pre-populated template.
I think the problem is that I clicked on the "New issue" while I was logged out.
The login modal was displayed and I logged in, and I got to this screen
<img width="2672" alt="Screenshot 2021-08-12 at 10 34 36" src="https://user-images.githubusercontent.com/16187074/129165960-d98b0e5a-7542-426d-8e9f-f9aa7dece150.png">
