### ISSUE TITLE
(...)

### ISSUE THREAD

**Issue by amjadsh97** [microsoft/TypeScript#45413]
# Bug Report

### Welcome everybody,
**I have an express server with react app with typescript, so when i run "npm run dev" the server work fine, but when I run "npm start" in another session in terminal the module in tsconfig.json changed automatically from "commonJS" to "esnext".   so the server was turned off and because the module was changed. so can anyone help me to sove this problem**

#typescript #module

**Comment by MartinJohns** [comment]
First time I saw someone writing the entire question in the title.

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
