### ISSUE TITLE
If generic function type parameter can't be inferred, `T` should be `any`, not `{}`.

### ISSUE THREAD

**Issue by heroboy** [Microsoft/TypeScript#4542]
For example:
```
declare function foo<T>(x: T[], callback: (item:T) => void);
var arr:any;
foo(arr, x=> {
    //here x should be any, not {}
});

```
and
```
declare function bar<T>(f:(item:T)=>void);
bar(x=>{
	//x should be any
});

```

**Comment by kitsonk** [comment]
I don't think you are using generics right.  TS is being more permissive than maybe it could be, you really aren't following a signature of the declare.  For example you are specifying the generic parameter, second you aren't passing an array in the first argument.  I would have thought you would have done something more like this:

```typescript
declare function foo<T>(x: T[], callback: (item: T) => void);
var arr:any[] = [];
foo<any>(arr, x => { /* do something */ });
```

**Comment by matthewjh** [comment]
I get the impression that @heroboy intended to write `var arr:any[];` rather than `var arr:any;`…?

**Comment by heroboy** [comment]
@matthewjh 
No, `arr` is `any`.
First ,I think `any` can be any type, `string`, `number`, `string[]` and `any[]`. Why `any` can't be `any[]`?
Second , as @kitsonk said, I was not using generics right, why it's not a compile error? And what is `{}` type come from?

**Comment by kitsonk** [comment]
It isn't the "type", it is part of the [arrow function syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions).

**Comment by heroboy** [comment]
@kitsonk 
I know arrow function syntax.
```
var x:{}; //{} is type
var y = (x:{})=>{};// arrow function syntax
```
http://www.typescriptlang.org/Playground#src=declare%20function%20foo%3CT%3E%28x%3A%20T[]%2C%20callback%3A%20%28item%3AT%29%20%3D%3E%20void%29%3B%0D%0Avar%20arr%3Aany%3B%0D%0Afoo%28arr%2C%20x%3D%3E%20{%0D%0A%20%20%20%20%2F%2Fhere%20x%20should%20be%20any%2C%20not%20{}%0D%0A}%29%3B
Move the cursor on `x`, it shows x is `{}`.

**Comment by kitsonk** [comment]
There is likely a good reason why when you mis-use generics you don't get error messages, but if you properly use them, [your issue goes away](http://www.typescriptlang.org/Playground#src=declare%20function%20foo%3CT%3E(x%3A%20T%5B%5D%2C%20callback%3A%20(item%3AT)%20%3D%3E%20void)%3B%0D%0Avar%20arr%3Aany%3B%0D%0Afoo%3Cany%3E(arr%2C%20x%3D%3E%20%7B%0D%0A%20%20%20%20%2F%2F%20here%20x%20is%20any!!!%0D%0A%7D)%3B):

```typescript
declare function foo<T>(x: T[], callback: (item:T) => void);
var arr:any;
foo<any>(arr, x=> {
    // here x is any!!!
});
```

Because `any` is using a hammer to crack a nut, `any` can be passed as the first argument without throwing an error, because you are basically telling TypeScript you know better than it does.

**Comment by zhengbli** [comment]
After talking to @DanielRosenwasser, it is a conservative design to inferred ``{}`` instead of ``any`` for ``foo`` here. ``{}`` is stricter in a sense that it doesn't allow random property access. 
The assumption is that if you are using generic functions, it is more likely that you "want" to use types for some reason, and it is less likely that your code came from a existing JavaScript code base.

**Comment by heroboy** [comment]
Ok,thank you. I'm happy it is by design, not a bug. Although I more like it to be a compile error.
And I hope you can provider a more powerful type inference algorithm. For example:
```
declare function bar<T, U>(x: T|U, y: (item: T) => void, z: (item: U) => void);
bar(1, y=> { }, z=> { });//  T|U==number  =>  T==U==number
bar(1, y=> { }, (z: string) => { });//  (T|U==number && U==string) => T==number
```
