### ISSUE TITLE
Exporting generic function gives error `Exported variable 'bar' has or is using private name 'foo'`.

### ISSUE THREAD

**Issue by vilic** [Microsoft/TypeScript#4547]
TypeScript version 1.7.0-dev.20150830

```ts
function foo<T>() { }
export var bar = foo;
```

**Comment by danquirk** [comment]
We don't have a conformance test for this case? ;(

**Comment by mhegazy** [comment]
Looking at this again, this is not a bug; this behaves as intended. the emitter will not write out named types as anonymous types, if it finds a named entity, function `foo` in this case, it will use it. so `bar: typeof foo` would be the intended output. since `foo` is not exported, `typeof foo` is not a valid type name, and hence the error.

To avoid the error, either export `foo` or write an explicit type annotation for `bar`.

**Comment by vilic** [comment]
@mhegazy :+1: It was confusing because 1.7 would not complain about this if no generic involved.
