### ISSUE TITLE
Unable to use TypeScript (Code Helper 100% of processor)

### ISSUE THREAD

**Issue by davidavz** [microsoft/TypeScript#45491]
Since a couple of days I can't use VScode properly with TypeScript (show info on hover, auto import etc.) it works 5 minutes when I launch the app and then I have a Code Helper process at 100% of processor and I can't use it anymore.
I tried reinstall 1.58.2, Insiders version but I still have this issue.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59 & 1.58.2
- OS Version: macOS Big Sur 11.5.1

**Comment by mjbvz** [comment]
Thanks. Can you also test on the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) to confirm this is still happening

**Comment by davidavz** [comment]
I've just tested right now and I have the same issue. I generated the `tsserver.log` if you want it ...

**Comment by DanielRosenwasser** [comment]
I'm not as well-versed in tsserver log reading as my coworkers, but I don't think I'm seeing anything in the logs except for the basic project loading. That does take around 6.4 seconds which isn't great, but for the number of files I'm seeing it's not out of the question. Otherwise, there's not enough context here to see what's slow, and even if we could, providing suggestions without the code in question would require a lot of time. I would suggest reading through [our wiki page on Performance](https://github.com/microsoft/TypeScript/wiki/Performance) so that you can uncover why you might be experiencing performance issues. 

Specifically, if you've avoided all the common issues, I'd suggest trying to find hot spots in a basic compilation with `tsc` by [getting a performance trace](https://github.com/microsoft/TypeScript/wiki/Performance#performance-tracing) and using @amcasey's [ts-analyze-trace](https://github.com/amcasey/ts-analyze-trace) tool.

**Comment by jgoux** [comment]
Hello, I'm a colleague of @davidavz and I have the exact same issue since a couple of days ago.

TS server isn't outputting any error, but the logs always end up with these sequences : 
```
Info 1417 [15:18:00.041] Starting updateGraphWorker: Project: /Users/admin/Documents/Code/Clovis-team/clovis-labs/clovis/packages/client/tsconfig.json
Info 1418 [15:18:00.100] Finishing updateGraphWorker: Project: /Users/admin/Documents/Code/Clovis-team/clovis-labs/clovis/packages/client/tsconfig.json Version: 8 structureChanged: false Elapsed: 58.97808400169015ms
Info 1419 [15:18:00.100] Different program with same set of files:: structureIsReused:: 2
Info 1420 [15:18:00.102] getCompletionData: Get current token: 0.012628000229597092
Info 1421 [15:18:00.102] getCompletionData: Is inside comment: 0.023969002068042755
Info 1422 [15:18:00.102] getCompletionData: Get previous token 1: 0.012947000563144684
Info 1423 [15:18:00.102] getCompletionData: Get previous token 2: 0.02292799949645996
Info 1424 [15:18:00.102] getCompletionsAtPosition: isCompletionListBlocker: 0.2235580012202263
Info 1425 [15:18:00.107] collectAutoImports: starting, not resolving module specifiers
Info 1426 [15:18:00.107] collectAutoImports: module specifier cache size: 7
Info 1427 [15:18:00.231] getSymbolToExportInfoMap: cache miss or empty; calculating new results
Info 1428 [15:18:00.487] getSymbolToExportInfoMap: caching results
Info 1429 [15:18:00.487] getSymbolToExportInfoMap: done in 379.4849450029433 ms
Info 1430 [15:18:00.765] collectAutoImports: done in 657.4780550003052 ms
Info 1431 [15:18:00.765] getCompletionData: Semantic work: 662.3724420033395
```

After these instructions, there is nothing logged until I reboot TS server (all the hover/autocomplete interactions are stuck on Loading...).

**Comment by DanielRosenwasser** [comment]
I think I see - we get a request for completions and never seem to come back with a result. I didn't catch that in the original logs. Thanks for clarifying!

My assumption is we're doing a *lot* of work that can't be short-circuited (most likely), or are caught in some sort of infinite loop (rarer these days).

**Comment by jgoux** [comment]
Hello, a small update!

We still aren't able to pinpoint the issue **but** it seems that bumping the allocated memory for tsserver "solves" the issue. (`"typescript.tsserver.maxTsServerMemory": 8192`), I had something like 3Go previously.

VSCode is back to normal, the autocompletion / imports and type checks are instant! 🚀

**Comment by andrewbranch** [comment]
@jgoux what version of TypeScript are you running now? Can you double check that removing that memory option actually reproduces the problem again? My understanding is that a while back, Node changed to be allowed to use however much memory the system can give it, making the `--max-old-space-size` flag really only able to _limit_ the memory space, not increase it. I’m wondering if something else changed at the same time—e.g., if you’re using the nightly TypeScript builds, we’ve made some pretty major performance fixes recently (#44851) and I wonder if you’re actually seeing that instead.

**Comment by jgoux** [comment]
@andrewbranch We're using `4.4.4` right now so I don't think it's related to the last performance fixes.

If I remove the option it will fallback to its default at [`3072`](https://github.com/microsoft/vscode/blob/1aa9a712d19c1c059fba0576137d92981d7228eb/extensions/typescript-language-features/package.json#L1026) and the issue is back. 😅 

Once the performance fixes are on stable I'll test against them with the option back to `3072` and I'll tell you if it's better. 👍

**Comment by andrewbranch** [comment]
Oh, I missed that the option has a default coming from VS Code. Very interesting. Thanks!
