### ISSUE TITLE
@returns documentation gets lost when inheriting getter

### ISSUE THREAD

**Issue by ilyub** [microsoft/TypeScript#45508]
# Bug Report

### 🔎 Search Terms

@returns documentation gets lost when inheriting getter

### 🕗 Version & Regression Information

4.3.5

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYGwhgzhAECC0G8BQ1oHoBUGWo9AIgKYTABOAlgA4Au5A9gHYB0O0ereAAqYdQK6kGMAMrUKDAOYtUbNDgm9oADwAUASgBc0CGPKTEraD36DoAIjMBuHAF8kOTNhl4iJCjXrMO0b914ChaFFxKQ45VAAzdS0dEIMZI39TC2tUGx87JFBIGAAhaEIlakIGABMYeGRUBWplaO1dfSqZYwDzK1t7SPrYvQl4lqSGdtTodNQkOyA

### 💻 Code

```ts
class A {
  /**
   * Description.
   * 
   * @returns String.
   */
  get x(): string {
    return "";
  }

  /**
   * Description.
   * 
   * @returns String.
   */
  f(): string {
    return "";
  } 
}

class B extends A {
  get x(): string {
    return "";
  }

  f(): string {
    return "";
  }   
}
```

### 🙁 Actual behavior

Typescript shows @returns documentation for inheritted function but looses it for getter inside class B:
![Screen1](https://user-images.githubusercontent.com/70687432/129993584-dda20d03-bb5e-4293-b4db-6c884a439fff.jpg)
![Screen2](https://user-images.githubusercontent.com/70687432/129993589-30e3beb8-9b2d-4ab7-ae4e-70957274bc4b.jpg)

Inside class A it shows @returns both for getter and function.

### 🙂 Expected behavior

Since typescript shows @returns for getter in class A, it should also show it for inheritted getter.

**Comment by ShuiRuTian** [comment]
Well, life is complicated, so this issue is not that easy as it looks...

@DanielRosenwasser Sorry for bothering, but I want to ask some questions before continuing coding. Or is there an existing design meeting note I missed?

Some existing problem I found(or I think it is! Not pretty sure):
1. Property could not inherit JsDoc too, not only setter/getter
2. When we have setter and getter in base class and derived class, and the getter and setter in base class are documented, the description of quickInfo getter/setter in derived class are both combined. I think they should only inherit correspond accessor.
3. quickInfo of getter and setter in class declaration should be "getter"/"setter" rather than "property"

Finally, @ilyub should we really use `@returns` on getter/setter? There is a discussion:https://github.com/jsdoc/jsdoc/issues/973

**Comment by ilyub** [comment]
> Finally, @ilyub should we really use @returns on getter/setter?

This makes sense. But in any case I would expect it to be consistent, i.e. either show in both places or not show in both places.
