### ISSUE TITLE
Why not add a new keyword to use real `this` in arrow functions

### ISSUE THREAD

**Issue by alisabzevari** [Microsoft/TypeScript#4551]
I am not professional to designing languages, so the thing that I am proposing here may seem silly!

Consider the situation that I have a class in which I work with a highcharts configuration object:
``` typescript
class MyChart {
    private getFoo() {
        return "Foo";
    }

    public getHighchartsConfig() {
        var instance = this;
        var config: HighchartsOptions = {
            chart: {
                events: {
                    load: function (event) {
                        console.log(instance.getFoo()); // Here I need MyChart instance
                        console.log(this.container); // Here I need this of event. According to http://api.highcharts.com/highcharts#chart.events.load
                    }
                }
            }
        }
    }
}
```
It is obvious that I can't use arrow function because I miss `this` of event. I think It would be nice to have another keyword (for example `contextthis` or anything better) to make that code more concise:
``` typescript
class MyChart {
    private getFoo() {
        return "Foo";
    }

    public getHighchartsConfig() {
        var config: HighchartsOptions = {
            chart: {
                events: {
                    load: (event) => {
                        console.log(this.getFoo()); // Here I need MyChart instance
                        console.log(contextthis.container); // Here I need this of event. According to http://api.highcharts.com/highcharts#chart.events.load
                    }
                }
            }
        }
    }
}
```

**Comment by kitsonk** [comment]
Arrow functions were specifically designed to refer to the lexical `this`.  If you don't want the lexical `this`, don't use arrow functions.

It is highly unlikely that TypeScript would introduce something like this, because it would be breaking for compatibility with ES6.  If such a feature should exist (which just using standard functions solves) it should be proposed at the ECMAScript level.

**Comment by SimonMeskens** [comment]
@kitsonk That's not really true, is it? You can easily compile this into idiomatic javascript. The problem is that it's very confusing syntax. If I declare a huge arrow function and somewhere in the middle I use `contextthis`, it will be compiled differently, when targeting ES6.

If you ask me, the fact that the ES6 committee didn't accept the thin arrow syntax is a mistake. Imagine being able to:

`
...
let self = this;
...

load: (event) -> {
                        console.log(this.getFoo()); // Here I need MyChart instance
                        console.log(self.container); // Here I need this of event. According to http://api.highcharts.com/highcharts#chart.events.load
                    }
`

Maybe Typescript could add this syntax?

**Comment by alisabzevari** [comment]
@kitsonk What is the difference between your thin arrow and `function` here?

**Comment by xLama** [comment]
@alisabzevari  -> is not part of TS sintax.
I hate use event this. I suggest you use arrow functions and  target property from event object. All Event classes should have a target property that refers to the object that triggered the event .

An alternative is create a closure.  For example:

```
class CallBack {
   public static createCallBackFunction(context:any, method: Function): Function{
       return function(){
            method.apply(context, arguments);
       }
   } 
}

```

**Comment by DanielRosenwasser** [comment]
If you're looking to at least cut out the need to type `function`, you can use method syntax in your example:

```TypeScript
class MyChart {
    private getFoo() {
        return "Foo";
    }

    public getHighchartsConfig() {
        let  instance = this;
        let config: HighchartsOptions = {
            chart: {
                events: {
                    load(event) { // <-- right here
                        console.log(instance.getFoo());
                        console.log(this.container);
                    }
                }
            }
        }
    }
}
```

**Comment by alisabzevari** [comment]
@xLama  I don't like it too. That's the reason to propose a syntax. The problem is some libraries do not provide this property. In javascript, when you write a function as a public method in a library, you have to think about how the function will be called. This may cause errors in code.

**Comment by SimonMeskens** [comment]
@alisabzevari Thin arrow is exactly the same as `function`, but it has all the benefits of ES6 arrows (optional return statement, optional brackets). There was at one point a vote about it and that feature didn't make it, basically because of inertia.

**Comment by danquirk** [comment]
Realistically, what likely happens here from TypeScript's side is:
- thin arrow functions if and only if ES adopts them
- support for proper this typing (see https://github.com/Microsoft/TypeScript/issues/3694 amongst others)
- you'll need to manually capture the ```this``` you want to persist across function boundaries. It's perfectly reasonable to imagine that you'd want not just the nearest outer ```this``` but the ```this``` one level higher than that, but now ```contextThis``` isn't useful since it only works one level up.

Adding specific syntax just to get at the nearest outer ```this``` doesn't seem worth the complexity.
