### ISSUE TITLE
Use template literal type as object key

### ISSUE THREAD

**Issue by marceleq27** [microsoft/TypeScript#45541]
# Suggestion

Use template literal type as a key in object

## 🔍 Search Terms

template literal string as object key

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Hello, I have a problem and maybe this thing will be a good feature. I would like to use template literal types as a key in for example interface. Let me show an example.

## 📃 Motivating Example

```ts
type ActionStringType<S extends string, D extends string> = string extends S
    ? ""
    : S extends ""
    ? ""
    : S extends `${infer T}${D}${infer U}`
    ? `${Lowercase<T>}${Capitalize<ActionStringType<U, D>>}`
    : Capitalize<Lowercase<S>>
```
```ts
const createRequestAction = <T extends string>(name: T) => {
    const actionName = name
        .split("_")
        .map((item, i) => {
            if (i === 0) {
                return item.toLowerCase()
            }
            return item.charAt(0).toUpperCase() + item.slice(1).toLowerCase()
        })
        .join("") as ActionStringType<T, "_">
    return {
        [`${actionName}Success`]: createActionCreator(`${name}_SUCCESS`),
        [`${actionName}Error`]: createActionCreator(`${name}_ERROR`),
        [`${actionName}Done`]: createActionCreator(`${name}_DONE`), 
    }
}
// createActionCreator is a function from 'deox' npm package
```

I've made a `ActionStringType` and for example:

```ts
type S1 = ActionStringType<"SET_AS_FAVOURITE">
// returns "setAsFavourite" which is good
```

I was trying to make a action generator in redux and I found a problem where I can't type keys in object that `createRequestAction` returns. So this type is working fine but TS is still not seeing the names (keys of object) of action creators.

And for example now something like `...createRequestAction("SET_AS_FAVOURITE")` returns:

```ts
const createRequestAction: <"SET_AS_FAVOURITE">(name: "SET_AS_FAVOURITE") => {
    [x: string]: ExactActionCreator<"SET_AS_FAVOURITE_SUCCESS", () => {
        type: "SET_AS_FAVOURITE_SUCCESS";
    }> | ExactActionCreator<"SET_AS_FAVOURITE_ERROR", () => {
        ...;
    }> | ExactActionCreator<...>;
}
```
I want to change this `[x: string]` to something like S1 type returns.

So, that is my idea, idk how to implement this, maybe it's impossible for now, but i think it will be a good feature. Let me know your thoughts, maybe I'm doing something wrong :)

## 💻 Use Cases
- creating action generators etc.
- typing keys in object

**Comment by jcalz** [comment]
Looks like a duplicate of #13948 and/or #21030.   Your example is kind of complicated for what amounts to a demonstration of using a computed key of a template literal type, but if I use the "unionize" type from [here](https://github.com/microsoft/TypeScript/issues/21030#issuecomment-356376955) to distribute records over unions, like this:

```ts
type DistribRecord<K extends PropertyKey, V> = { [P in K]: { [Q in P]: V } }[K]
const kv = <K extends PropertyKey, V>(k: K, v: V): DistribRecord<K, V> => ({ [k]: v } as any)
```

Then instead of `{[foo]: bar}` we can write `kv(foo, bar)` to get the behavior you want.  Your return value would probably look like

```ts
  return {
    ...kv(`${actionName}Success`, createActionCreator(`${name}_SUCCESS`)),
    ...kv(`${actionName}Error`, createActionCreator(`${name}_ERROR`)),
    ...kv(`${actionName}Done`, createActionCreator(`${name}_DONE`)),
  }
```

And then you get 

```ts
const x = createRequestAction("SET_AS_FAVOURITE")
x.setAsFavouriteDone // ExactActionCreator<"SET_AS_FAVOURITE_DONE", () => { type: "SET_AS_FAVOURITE_DONE"; }> 
x.setAsFavouriteError // ExactActionCreator<"SET_AS_FAVOURITE_ERROR", () => { type: "SET_AS_FAVOURITE_ERROR"; }>
```

[Playground link](https://www.typescriptlang.org/play?target=99#code/JYWwDg9gTgLgBAbzgYygUwIYzQQWTYCAOwGF0to4BfOAMyghDgHIATNCAD2YCgeYAnmDRwAIsADOMKMABGAJTTJorADwBpOGk7YirCXAAKDYbAHq0AgDRwAagD44AXkRwA2objAicdQF0ALlc3AEUvH0NAu2pqN38eZSIpOABrADdnOA0tHTQ9A2MIU0ELazt7AAoUoPUbNKDbAEog8SkZBSUVDRsHZ0cKpDcUqIyaDAMMIgFGvn4hETwCYgBlaW8AcwAVedVlnN19ODaNm1F9vMPjonXHFyv18-y4ZZ44OAB+OAAiL9e4IL22gOBh+f0+oLeAMehwABgASBDeWhoKBwTZUBGiDGIojI1EAVSoMLBcHhCAAMhAAO4o5DjNCqTb2bEkDBgYAwDAAG2AAC8GYtCERVjJrtthKp8ad7MziZC4Kz2ZyefzVJSaVA6RIGcsZXxEslUJhsIoAI4AVzQUkFxEyjOhBnulSIGBAaCCm0afUQfwN8Aw+CFADlXSIXC63X83gA6CRgHkwCpfAD6XxmbxjIDZFQqHLQIBswC9TkcCCjGeAtDguecThcAAYvWWMy24OgYOaoD48yBozAIOqUaztRV062qOW3u3O93sL3kAALDBQHCJxt9iD4sCmYdoUdwADUXjnsZ5yD3AEZGhvB1Bd6Py1QxzGAFYQbxJtNwcZwG3CtZijsmw2CmXz2H805dj6LbRrB6QVGSAZLEQIZulQyzmsg54SBIMI2EaWC4IGxBkMa0AIQiEZoFQybLPiJAkAAossywwo0jRWOWsHRvBiHEShoZUIxUAMFAeEoOQ2B-qRFBQBRCBUTRjHyPIADy8hsRxXFwWk8lIcGgmiMQaDiQRUn8TJ-ZyWSinJqIqlBoxmmcW8E4TgkxDJJwmRmWgZqWta-FJssjGbMmODLMmABiOC2Kp+LyAAkpsjFpjwnCxmgMA4BIUUYGkECdnmRlECIAD0ZVwIxnBIdJknQKoXwhWFEXRbF8VJSldkOalNj7iWriCMIQRNaF4WRTFcUJcljHdY5XwANzUI46WZdluX5YVMjYMJolwBVVU1fgdVkVAjXNeNbVTZ1s3KWp8hfH1xalnAQ3ut8F2tZNHUzcmd3qYty08EAA)

**Comment by marceleq27** [comment]
Hi, yes, that's that I'am talking about. For now I figured out this problem like this:

```ts
type Types = "Success" | "Error" | "Done"

type SnakeToCamelCase<S extends string> = S extends `${infer T}_${infer U}` ? `${Lowercase<T>}${Capitalize<SnakeToCamelCase<U>>}` : Lowercase<S>

type Output<T extends string> = {
    [key in `${SnakeToCamelCase<T>}${Types}`]: ExactActionCreator<
        T,
        () => {
            type: T
            payload: any
        }
    >
}
```
And function looks like this:

```ts
const createDeoxRequestAction = <T extends string>(name: T): Output<T> => {
    const actionName = name
        .split("_")
        .map((item, i) => {
            if (i === 0) {
                return item.toLowerCase()
            }
            return item.charAt(0).toUpperCase() + item.slice(1).toLowerCase()
        })
        .join("") as SnakeToCamelCase<T>
    // eslint-disable-next-line @typescript-eslint/no-unsafe-return
    return {
        [`${actionName}Success`]: createActionCreator(`${name}_SUCCESS`),
        [`${actionName}Error`]: createActionCreator(`${name}_ERROR`),
        [`${actionName}Done`]: createActionCreator(`${name}_DONE`),
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any
}
```
And that work properly, so if it's duplicated topic - I'm closing :)

Thanks for your help @jcalz ;)
