### ISSUE TITLE
Non-null assertion is not assignable to NonNullable of indexed access type on generic

### ISSUE THREAD

**Issue by ktint** [microsoft/TypeScript#45783]
### 🔎 Search Terms

not assignable to type NonNullable

### 🕗 Version & Regression Information

Present in 4.4.2, 4.3.5

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMrQG7QEoQM4AOA9iHhADwAqAfMgN4BQyyAJnGHAFzKUDaAugwC+DBjACuIBGGAlkAcwhhchEmQAi7OFQA0yAFLIIAD0ggWeNJhz5ipCjWoAKLjwEBKbgDkSX8QBt-OAAjfwp9XgByNg5I-lpGZiglcSgQZDgAQmQAehyeAE8CFEi+fkjkYEsQIjAMvDxgeRAQsOQwInaikp8QP0DW8N4AIhi4YfjIgDowPCcAJgBmefn3YSA)

### 💻 Code

```ts
interface ServerResponse<T> {
  data: T[]
}

function getResponseData<T, J extends ServerResponse<T>>(a: T[]): NonNullable<J['data']> {
  return a! // Type 'T[]' is not assignable to type 'NonNullable<J["data"]>'.ts(2322)
}
```

### 🙁 Actual behavior

It doesn't pass typecheck with that return signature.

Not a major bug for me or anything, I just thought it was interesting!

### 🙂 Expected behavior

The non-null assertion operator should cause this to pass typecheck, the same as if the return signature were NonNullable<T[]>.

**Comment by MartinJohns** [comment]
The non-null assertion operator doesn't do **anything** here, because the type of `a` is not nullable in the first place.

**Comment by ktint** [comment]
Sorry, I might've lost some context there trying to make the repro more minimal. The odd thing about it is that this code passes typecheck:

```ts
interface ServerResponse<T> {
  data: T[]
}

function getResponseData<T>(a: T[]|null): NonNullable<T[]> {
  return a! 
}
```

But this code does not:

```ts
interface ServerResponse<T> {
  data: T[]
}

function getResponseData<T, J extends ServerResponse<T>>(a: T[]|null): NonNullable<J['data']> {
  return a! // Type 'T[]' is not assignable to type 'NonNullable<J["data"]>'.ts(2322)
}
```

Even though the type of J['data'] in the second _should_ be identical to T[] in the first, as far as I can tell.

**Comment by andrewbranch** [comment]
`J extends ServerResponse<T>` does not mean that `J` is identical to `ServerResponse<T>`. It means only what it says—that `J` will be constrained to a subtype of `ServerResponse<T>`. If `T` is `number`, `J` can legally be `ServerResponse<0>`, because that is assignable to `ServerResponse<number>`. Then, you’d be trying to return a `number` where you need a `0`.

**Comment by andrewbranch** [comment]
That’s the theoretical reason why it doesn’t type check, but you can also zoom out to intuitive human programmer view and note that `J` is useless in this definition, and that’s the high-level reason the behavior seems weird. But again, it’s hard to tell what’s relevant in a super simplified example like this, because from what’s posted here, the signature needs only be

```ts
function getResponseData<T>(a: T[] | null): T[]
```

but I’m sure you have some reason to have `ServerResponse<T>` involved.

**Comment by ktint** [comment]
Ah, I think I see! Yes, the actual real-world function I was writing was this:

```ts
  async request<T, J extends PostgrestResponse<T> | PostgrestSingleResponse<T>>(query: PromiseLike<J>): Promise<NonNullable<J['data']>> {
    const promise = new Promise<J>((resolve, reject) => {
      query.then(res => {
        if (res.error) {
          reject(res.error)
        } else {
          resolve(res)
        }
      })
    })
    NProgress.promise(promise)
    const { data } = await promise
    return data! as NonNullable<J['data']>
  }
```

It wraps a library to add progress indicators and throw errors on failure. Since data only comes back as null when there's also an error, it never returns null data. I thought it might be a bug that the "as" at the end there was necessary-- but more likely I just don't quite know how to accurately express the signature in TS.

**Comment by andrewbranch** [comment]
It certainly looks to me like you should just rewrite each reference to `J` in terms of `T`.
