### ISSUE TITLE
JSDoc-style computed string enums in TypeScript proper

### ISSUE THREAD

**Issue by sdegutis** [microsoft/TypeScript#45826]
# Suggestion

## 🔍 Search Terms

jsdoc computed string enum

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Allow TypeScript's type checking of JSDoc-style computed-string enums, but in TypeScript itself.

## 📃 Motivating Example

```ts
import assert from 'assert';

// This would work, but it's not dynamic
// export enum DealStage {
//   EVAL = 'EVAL',
//   CLOSED_WON = 'WON',
//   CLOSED_LOST = 'LOST',
// }

// This fails to compile:
//   Only numeric enums can have computed members, but this expression has type 'string'. If you do not need exhaustiveness checks, consider using an object literal instead.(18033)
// export enum DealStage {
//   EVAL = required('HUBSPOT_DEALSTAGE_EVAL'),
//   CLOSED_WON = required('HUBSPOT_DEALSTAGE_CLOSED_WON'),
//   CLOSED_LOST = required('HUBSPOT_DEALSTAGE_CLOSED_LOST'),
// };

// This compiles, but does not have comprehensive type checking unless it's defined in a .js file and has this JSDoc:
/** @enum {string} */
export const DealStage = {
  EVAL: required('HUBSPOT_DEALSTAGE_EVAL'),
  CLOSED_WON: required('HUBSPOT_DEALSTAGE_CLOSED_WON'),
  CLOSED_LOST: required('HUBSPOT_DEALSTAGE_CLOSED_LOST'),
};

function required(key: string): string {
  const value = process.env[key];
  assert.ok(value, `ENV key ${key} is required`);
  return value;
}

function dostuff(dealstage: DealStage) {
  dealstage === DealStage.CLOSED_WON
  dealstage === 'hi' // this should fail with:
  // This condition will always return 'false' since the types 'DealStage' and '"hi"' have no overlap.(2367)
}
```

## 💻 Use Cases

In the above example, I can build an enum of dynamically generated values. But I can only do this with JSDoc @enum syntax currently.

**Comment by anthonyjoeseph** [comment]
In the function `dostuff`, isn't `DealStage.CLOSED_WON` defined in a `.env` file? If the `.env` file looks like this:
```
CLOSED_WON=hi
```
Shouldn't `dealstage === 'hi'` be true?

**Comment by sdegutis** [comment]
That would fail if this were defined in a .js file with JSDoc's `@enum` syntax, saying there's no overlap. The idea is to not be able to compare to string constants, but only enum members. And trust the developer (as TypeScript already does in that scenario) to ensure that the values never overlap.

**Comment by anthonyjoeseph** [comment]
Aha - I think I understand what you're looking for

You can get pretty close using a [unique symbol](https://kubyshkin.name/posts/newtype-in-typescript/) - [playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAQwM5IKazgMyhEcDkyas+AUKZgK4B2AxjMBNXFKgI6XCsAmAFANaoAngC44SGFGDUA5gEoxEqbLgBvUnDi0mEuADcEAG0qo4AXjhgctVCgB0qanoDagoQF0A3BsQp0MOwh+XgNjVAAaOAADAFEAOQA1ODc4ABJVNwBfOGAkFnZOHii5b01WGEooZlCTb0zybWpdAFUmhExUABFUIwBlGAQZUwt1TRiEgEEAGTFWDi5UPnwACWaAIV6ABQB5ABUAfU6Y6d7diYBxGP3x6fw5cJ8AYSnt3pjO-YB1bbjZgoWlqsNjsDkcTmdLvtnq93l8fncHppoW8Pi9Tn95jxeCt1ls9odjlNThcrsjYWjdgjSJlvKQAPQAKgZcAAAo5KHhVEppDJsgy6aRUAAPSAYRq6bp9AZDcxwVpIdpdHqGfqDUzIOAAJVQ2ig3AAPD43BBMHAYEIwKgTXK2h1JSrpRE4D5uSoAGRqfIIbhMQxCOD7fbSsQ0YAcUxIIQgABGEEMcHqAD5yObLXAEkYTNtMPqJonZRNXMJrRN3BQaPRGMwfRJKJhMLxuMqJGqxBmwtn9amrab7aqhom5GofE2jC2ZWZJ3A+467GSPt84uRNHS6WaABa5OA+2zUfDwTAIYDxxsmM0QLQQAxSBB0UwAWg3wjgsZg6-ECAYSEw-rfpm7BCujIdwjs2jrmFO+CbmQ9TkKuL6UPAb5bjuSCkOKB5HvGFg1hU9bYtBcgNDo8BIJQtA2Cgsq4XWDYzmqdg3FMRFAA)

**Comment by andrewbranch** [comment]
Yeah, you’ll still be allowed to compare a `string` with a tagged string type because comparability rules are loose, with a special carve-out for enums, but @anthonyjoeseph’s solution is about as good as you can get—I’d simplify it to [this](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAQwM5IKazgMyhEcDkyas+AUKZgK4B2AxjMBNXFKgI6XCsAmAFANaoAngC44SGFGDUA5gEoxEqbLgAyOAG8WqBNyYAbIXAD6xmAhliawDqnFCQAIwj64AX02k4cWkwlwANwR9SjsAXjgwHFpUFAA6VGoAgG1BIQBdAG4vRBR0GDiIfl4gkNQAGjgAAwBRADkANTg0uAASDTSPYCRtDi5Ubiq5bO9WGEooZlLQ3MRqIWy3cl9qfwARHX0AZXMZcM9vGoaAQQAZMVY+nl58AAkAVQAhLYAFAHkAFWM1mrOtj+OAHEasYjmd8HJyjkAMKnN5bGprYwAdTedQu7E41zuT1en2+v1O-yBINh8MRKLREKh3jJCKRcP+GKuAxuD2e7y+Pz+AOBxjpFMZH2ppDc2VIMCEYDsDWCoTemAAPMcAHxwCLHVLCCCYODHdIUGj0RjMPQSSiYTC8bibCQWVBiWVlBWKyXSnVwDbBHb2lVyA5wG3BO17dVhCJe7a7VBxAVI1F1cjeAD0ybgMAAFt1AxBYtR8PBMAhgK5rTMYBAfBAglIEHQ7ABadMZ4RwZyZ8QIBhITBGTN2N12fBKaQyCE5IP6EPhcMELNkJbkVNtyjwTPZvSxUgrfxFkvqnPmy03edyZZ+eBISi0GIoA9m8bHyM+vZxMGnM9AA).

@sdegutis, I think your suggestion actually has a better chance if you keep the idea of “enum-like comparability rules with a non-enum enum-like object” without being attached to the JSDoc switch—there’s nowhere else that a JSDoc tag changes the type of something in TypeScript, but overall I think a lot of people would like to see the useful parts of enums become available without the footguns of enums.

**Comment by sdegutis** [comment]
I think we can close this considering JSDoc is on the way out and Type Annotations will resolve this more cleanly in the future.
