### ISSUE TITLE
yield * does not work for custom iterator method

### ISSUE THREAD

**Issue by znakeeye** [microsoft/TypeScript#45847]
# Bug Report

### 🔎 Search Terms
yield generator

### 🕗 Version & Regression Information

4.4.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/dev/bug-workbench/?ts=4.4.2#code/MYGwhgzhAEBiD29oG8CwAoaXoDNEQC45EBtAXWgF5pyBuDDbaAKgHMBTAO3YCcwAXeDwAUASiIBJfrwFCAPAngA+FIybY8PaMJDt+uRNHg5o-ABYBLCADo88CKNWZ1LgPSvoAFQCeAB3bQAORSMoI8CogANNBgnN7RAK6cACbsOBbcyUqB0AC2CRD6ZmAAbgFgQSQAyt65AEbwINYW0nxhZGI5uXpm8Mmmxfo8egk8nDCx0C2hQtZqLkzeFuwg-cwG8NYc3G1CYvTOLgC+89An6EdAA)

### 💻 Code

```ts
class Foo {
    foos: Foo[] = [];

    *generator(): Iterator<Foo> {
        for (let foo of this.foos) {
            // Type 'Iterator<Foo, any, undefined>' must
            // have a '[Symbol.iterator]()' method that returns an iterator.
            yield * foo.generator();
        }
    }
}
```

### 🙁 Actual behavior

`yield *` does not work for custom `generator` method. Makes no sense?

### 🙂 Expected behavior

Preferably, it should work like it does for `[Symbol.iterator]`. No?

**Comment by ilogico** [comment]
It doesn't work because you typed the function as returning an Iterator instead of an Iterable, an IterableIterator, or a Generator. You can only use `yield*` on Iterables, not on Iterators.
[Playground](https://www.typescriptlang.org/dev/bug-workbench/?ts=4.4.2#code/MYGwhgzhAEBiD29oG8CwAoaXoDNEQC45EBtAXWgF5pyBuDDbaAKgHMBTAO3YCcwAXeDwAUASiIBxLrwFCAPAngA+FIybY8PaMJDt+uRNHg5o-ABYBLCADo88CKNWZ1LgJ4X2IACbMD8axzcfIIiovTOLgC+aljR6JFAA)

**Comment by znakeeye** [comment]
Ah, that makes sense. Thanks! It seems `*generator(): Iterable<Foo>` would also work.
