### ISSUE TITLE
Quick info uses JSDoc for inherited instance property with static property of same name

### ISSUE THREAD

**Issue by HolgerJeromin** [microsoft/TypeScript#45907]
# Bug Report

### 🔎 Search Terms
static class instance intellisense

### 🕗 Version & Regression Information

Tested TS 3.3 till nightly

- This is the behavior in every version I tried, and I reviewed the FAQ 

### ⏯ Playground Link and 💻 Code
```ts repro
class foo {
    constructor() { }
    /** instance bar */
    readonly bar = 'instance foo';
}
class foo2 extends foo {
    static readonly bar = 'class foo2';   // <- look at tooltip for 'bar' here
}
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?#code/MYGwhgzhAEBmD29oG8CwAoaXrHgOwgBcAnAV2EPmIAoBKFaAXw22gHoAqD6ASwMLB5gAU2gAjMMWgc2LbMWFgAJvhABPcZOgBeaAHI+RQSLiI9AbgzN0oSDATwATNGEAPQsLxL7iFHKxGhDzA0ArKqhoSUrp6tlCmThZWQA)

A bit larger example:
```ts repro
class foo{
    constructor() {
    }
    /** instance bar */
    readonly bar = 'instance foo';  //    <- tooltip here for 'bar' is correct
    /** class bar */
    static readonly bar: string = 'class foo'; //   <- tooltip here for 'bar' is correct
}
class foo2 extends foo{
    static readonly bar = 'class foo2'; // <- look at tooltip for 'bar' here
}
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?#code/MYGwhgzhAEBmD29oG8CwAoaXrHgOwgBcAnAV2EPmIAoBKFaAXw22gHoAqD6ASwMLB5gAU2gAjMMWgc2LbMWFgAJvhABPcZOgBeaAHI+RQSLiI9AbgzN0oSDATwATNGEAPQsLxL7iFHKxGhDzA0ArKqhoSUrp6tlCmThZWQA)

### 🙁 Actual behavior
Hover with the mouse over the static property of the inherited class. Is shows the jsdoc / tsdoc information from the instance property.

![image](https://user-images.githubusercontent.com/2410353/133596477-bd7a7a1c-ce2c-4774-bb0b-161e33bb646c.png)

### 🙂 Expected behavior
In the first example the tooltip should show nothing. In the second example I should see `class bar`.

**Comment by eliasm307** [comment]
@sandersn I'm still figuring out the code base however I've got a question regarding testing. So from what I understand it is like snapshot testing where in this case "baselines" are defined for different code examples in different formats to describe the expected symbols, types etc for each line of example code.

So following from this I have tried to create a failing test to highlight the points in this issue and I get the following symbol baseline:

```js
=== tests/cases/conformance/jsdoc/jsDocClassStaticProperty.ts ===
// Bug 45907
class Foo1 {
>Foo1 : Symbol(Foo1, Decl(jsDocClassStaticProperty.ts, 0, 0))

  /** instance bar */
  readonly bar1 = 'instance Foo1';
>bar1 : Symbol(Foo1.bar1, Decl(jsDocClassStaticProperty.ts, 1, 12))

  constructor() { }
}

class Foo2 extends Foo1 {
>Foo2 : Symbol(Foo2, Decl(jsDocClassStaticProperty.ts, 6, 1))
>Foo1 : Symbol(Foo1, Decl(jsDocClassStaticProperty.ts, 0, 0))

  static readonly bar1 = 'class Foo2';
>bar1 : Symbol(Foo2.bar1, Decl(jsDocClassStaticProperty.ts, 8, 25))
}

class Foo3 {
>Foo3 : Symbol(Foo3, Decl(jsDocClassStaticProperty.ts, 10, 1))

  /** class bar */
  static readonly bar2: string = 'class Foo3';
>bar2 : Symbol(Foo3.bar2, Decl(jsDocClassStaticProperty.ts, 12, 12))

  /** instance bar */
  readonly bar2 = 'instance Foo3';
>bar2 : Symbol(Foo3.bar2, Decl(jsDocClassStaticProperty.ts, 14, 46))

  constructor() {
  }
}

class Foo4 extends Foo3 {
>Foo4 : Symbol(Foo4, Decl(jsDocClassStaticProperty.ts, 21, 1))
>Foo3 : Symbol(Foo3, Decl(jsDocClassStaticProperty.ts, 10, 1))

  static readonly bar2 = 'class Foo4';
>bar2 : Symbol(Foo4.bar2, Decl(jsDocClassStaticProperty.ts, 23, 25))
}

```

I'm assuming lines like `>bar1 : Symbol(Foo1.bar1, Decl(jsDocClassStaticProperty.ts, 1, 12))` are to represent declaring a unique code symbol based on the item "Foo1.bar1" and context information from a specific file where the symbol is defined, in this case 
"jsDocClassStaticProperty.ts" and the line number and character number on that line the symbol starts from. Then the same symbol can be represented in other places using the same file, line number, and character number information.

If the above is accurate, then I'm not sure how to test this issue as it seems to declare the relevant symbols as unique but the issue is with the content of the documentation which isnt shown in the tests explicitly?

**Comment by eliasm307** [comment]
I've found the fourslash tests which seem to be more appropriate, let me know if this is the right place to be looking

**Comment by sandersn** [comment]
Yes, fourslash is the correct place. Let me know if you need additional pointers; you probably want to write an example program and then call `verify.baselineQuickInfo()`

**Comment by eliasm307** [comment]
Oh, hadn't noticed someone was already working on it, atleast it's been resolved :D

**Comment by HolgerJeromin** [comment]
works in playground.
thanks @a-tarasyuk
