### ISSUE TITLE
sourcemap off-by-one errors

### ISSUE THREAD

**Issue by amir-arad** [Microsoft/TypeScript#4591]
(using version 1.6.0-dev.20150825, with --declaration --module CommonJS --target ES5)
For some typescript code inputs, the compiler creates invalid mapping entry, mapping characters from the compiled code to the line break character at the end of the source line.
Sometimes, the mapped character from the compiled code is itself non-existent in the compiled file, like the last character in the last line.
for example, this code:
```typescript
class Product {}
export default Product;
```
is compiled into this code:
```javascript
var Product = (function () {
    function Product() {
    }
    return Product;
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = Product;
//# sourceMappingURL=test.js.map
```
with this source map:
```json
{"version":3,"file":"test.js","sourceRoot":"","sources":["test.ts"],"names":["Product","Product.constructor"],"mappings":"AAAA;IAAAA;IAAeC,CAACA;IAADD,cAACA;AAADA,CAACA,AAAhB,IAAgB;AAChB;kBAAe,OAAO,CAAC"}
```
here is a [visualization of the mapping in the example above](http://sokra.github.io/source-map-visualization/#base64,dmFyIFByb2R1Y3QgPSAoZnVuY3Rpb24gKCkgewogICAgZnVuY3Rpb24gUHJvZHVjdCgpIHsKICAgIH0KICAgIHJldHVybiBQcm9kdWN0Owp9KSgpOwpleHBvcnRzLmRlZmF1bHQgPSBQcm9kdWN0OwovLyMgc291cmNlTWFwcGluZ1VSTD10ZXN0LmpzLm1hcA==,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidGVzdC5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbInRlc3QudHMiXSwibmFtZXMiOlsiUHJvZHVjdCIsIlByb2R1Y3QuY29uc3RydWN0b3IiXSwibWFwcGluZ3MiOiJBQUFBO0lBQUFBO0lBQWVDLENBQUNBO0lBQURELGNBQUNBO0FBQURBLENBQUNBLEFBQWhCLElBQWdCO0FBQ2hCLGtCQUFlLE9BQU8sQ0FBQyJ9,Y2xhc3MgUHJvZHVjdCB7fQpleHBvcnQgZGVmYXVsdCBQcm9kdWN0Owo=). Notice how locations 1:16 and 2:23 do not exist in the source file's text, as well as 6:26 in the compiled code.

**Comment by mhegazy** [comment]
@sheetalkamat can you take a look.

**Comment by sheetalkamat** [comment]
@amir-arad. while investigating this here are the mapping entries(note I converted them into 1 based while printing) for visualization as shown [here](http://sokra.github.io/source-map-visualization/#base64,dmFyIFByb2R1Y3QgPSAoZnVuY3Rpb24gKCkgew0KICAgIGZ1bmN0aW9uIFByb2R1Y3QoKSB7DQogICAgfQ0KICAgIHJldHVybiBQcm9kdWN0Ow0KfSkoKTsNCmV4cG9ydHMuX19lc01vZHVsZSA9IHRydWU7DQpleHBvcnRzWyJkZWZhdWx0Il0gPSBQcm9kdWN0Ow0KLy8jIHNvdXJjZU1hcHBpbmdVUkw9YS5qcy5tYXA=,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiYS5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbImEudHMiXSwibmFtZXMiOlsiUHJvZHVjdCIsIlByb2R1Y3QuY29uc3RydWN0b3IiXSwibWFwcGluZ3MiOiJBQUFBLElBQU0sT0FBTztJQUFiQSxTQUFNQSxPQUFPQTtJQUFFQyxDQUFDQTtJQUFERCxPQUFUQSxPQUFVQTtBQUFEQSxDQUFDQSxBQUFoQixJQUFnQjtBQUNoQjtxQkFBZSxPQUFPLENBQUMifQ==,77u/Y2xhc3MgUHJvZHVjdCB7fQ0KZXhwb3J0IGRlZmF1bHQgUHJvZHVjdDs=)
```
Emitted(1, 1) Source(1, 1) + SourceIndex(0) nameIndex (-1)
Emitted(1, 5) Source(1, 7) + SourceIndex(0) nameIndex (-1)
Emitted(1, 12) Source(1, 14) + SourceIndex(0) nameIndex (-1)
Emitted(2, 5) Source(1, 1) + SourceIndex(0) name (Product)
Emitted(2, 14) Source(1, 7) + SourceIndex(0) name (Product)
Emitted(2, 21) Source(1, 14) + SourceIndex(0) name (Product)
Emitted(3, 5) Source(1, 16) + SourceIndex(0) name (Product.constructor)
Emitted(3, 6) Source(1, 17) + SourceIndex(0) name (Product.constructor)
Emitted(4, 5) Source(1, 16) + SourceIndex(0) name (Product)
Emitted(4, 12) Source(1, 7) + SourceIndex(0) name (Product)
Emitted(4, 19) Source(1, 17) + SourceIndex(0) name (Product)
Emitted(5, 1) Source(1, 16) + SourceIndex(0) name (Product)
Emitted(5, 2) Source(1, 17) + SourceIndex(0) name (Product)
Emitted(5, 2) Source(1, 1) + SourceIndex(0) nameIndex (-1)
Emitted(5, 6) Source(1, 17) + SourceIndex(0) nameIndex (-1)
Emitted(6, 1) Source(2, 1) + SourceIndex(0) nameIndex (-1)
Emitted(7, 22) Source(2, 16) + SourceIndex(0) nameIndex (-1)
Emitted(7, 29) Source(2, 23) + SourceIndex(0) nameIndex (-1)
Emitted(7, 30) Source(2, 24) + SourceIndex(0) nameIndex (-1)
```

Note that 
```
Emitted(1, 5) Source(1, 7) + SourceIndex(0) nameIndex (-1)
Emitted(1, 12) Source(1, 14) + SourceIndex(0) nameIndex (-1)
```
Represent name Product correctly in source and emitted file. 

I am looking into fixing the encoded mappings of kind 1:16, 2:23 in source as you mentioned because theoretically It should instead be next line column 0 in source instead.

**Comment by amir-arad** [comment]
Thank you. 
What about the last mapping? in your entries, this line:
```
Emitted(7, 30) Source(2, 24) + SourceIndex(0) nameIndex (-1)
```
signifies the one-after-last character in destination code (just before //# sourceMappingURL) , mapped to the one-after-last character in source. any thoughts on that?

**Comment by mhegazy** [comment]
This should be working as expected in latest.
