### ISSUE TITLE
4.5 Beta: import assertion json requires moduleResolution + resolveJsonModule options

### ISSUE THREAD

**Issue by dnalborczyk** [microsoft/TypeScript#46188]
# Bug Report

### 🔎 Search Terms
import assertions

### 🕗 Version & Regression Information
4.5 Beta

### Repro:

`index.ts`
```typescript
import some from "./some.json" assert { type: "json" }
```

`some.json`
```json
[]
```

`tsconfig.json`
```json
{
  "module": "ESNext",
  "target": "ESNext"
}
```

```terminal
npx tsc 
```

### 🙁 Actual behavior
// Cannot find module './some.json'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?

### 🙂 Expected behavior
I would assume it should work without the `moduleResolution` option.

<br />
when `moduleResolution: node` is applied we get the following:

### 🙁 Actual behavior
// Cannot find module './some.json'. Consider using '--resolveJsonModule' to import module with '.json' extension.

### 🙂 Expected behavior
I would assume it should work without the `resolveJsonModule` option.

**Comment by andrewbranch** [comment]
> I would assume it should work without the `resolveJsonModule` option.

Why?

**Comment by dnalborczyk** [comment]
> > I would assume it should work without the `resolveJsonModule` option.
> 
> Why?

because it's now an official ecmascript language feature, as opposed to be only supported by node.js+commonjs.

https://www.typescriptlang.org/tsconfig#resolveJsonModule

```
Allows importing modules with a ‘.json’ extension, which is a common practice in node projects. This includes generating a type for the import based on the static JSON shape.
```

**Comment by dnalborczyk** [comment]
@andrewbranch what about `moduleResolution` ?

**Comment by andrewbranch** [comment]
The thing that’s “working as intended” here is that import assertions do not change the behavior of the compiler in any way. We simply parse them and emit them as-is if your module target is high enough. Unfortunately, we simply do not have an appropriate module resolution mode for browser-based ESM right now. I am supposing that the new `node12` or `nodenext` options are going to be the best fit, because at least they enforce using file extensions and indexless paths, but they’re also going to do some things that obviously won’t happen on the web, like look for node_modules and export maps and whatnot.
