### ISSUE TITLE
mongodb broken by #41821

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#46228]
mongodb has a mapped type `SetFields` that calls a conditional type `Flatten`. Before #41821, `Flatten` propagated its constraint from its argument to its return type. Now it does not.

To reproduce:

1. `npm i mongodb@4.1.2`
2. Create a tsconfig with index.ts and strict: true.
3. In index.ts, `import mongodb = require("mongodb")`
4. Error in mongodb.d.ts on line 5233.

I'll see if I can create a standalone repro.
If this error is intended, we need to provide a fix for mongodb so they don't break when people start using 4.5.

**Comment by sandersn** [comment]
Here's a messy standalone repro:

```ts
export declare type Flatten<Type> = Type extends ReadonlyArray<infer Item> ? Item : Type;
export declare type AddToSetOperators<Type> = {
    $each?: Array<Flatten<Type>>;
};
export declare type KeysOfAType<TSchema, Type> = {
    [key in keyof TSchema]: NonNullable<TSchema[key]> extends Type ? key : never;
}[keyof TSchema];
export declare type NotAcceptedFields<TSchema, FieldType> = {
    readonly [key in KeysOfOtherType<TSchema, FieldType>]?: never;
};

export declare type KeysOfOtherType<TSchema, Type> = {
    [key in keyof TSchema]: NonNullable<TSchema[key]> extends Type ? never : key;
}[keyof TSchema];
declare class ObjectId {
    _bsontype: 'ObjectId';
    /* Excluded from this release type: index */
    static cacheHexString: boolean;
}
export declare type OptionalId<TSchema extends {
    _id?: any;
}> = ObjectId extends TSchema['_id'] ? EnhancedOmit<TSchema, '_id'> & {
    _id?: InferIdType<TSchema>;
} : WithId<TSchema>;
export declare type WithId<TSchema> = EnhancedOmit<TSchema, '_id'> & {
    _id: InferIdType<TSchema>;
};
export declare type InferIdType<TSchema> = TSchema extends {
    _id: infer IdType;
} ? {} extends IdType ? Exclude<IdType, {}> : unknown extends IdType ? ObjectId : IdType : ObjectId;

export declare type EnhancedOmit<TRecordOrUnion, KeyUnion> = string extends keyof TRecordOrUnion ? TRecordOrUnion : TRecordOrUnion extends any ? Pick<TRecordOrUnion, Exclude<keyof TRecordOrUnion, KeyUnion>> : never;
export type SetFields<TSchema> = ({
    readonly [key in KeysOfAType<TSchema, ReadonlyArray<any> | undefined>]?: OptionalId<Flatten<TSchema[key]>> | AddToSetOperators<Array<OptionalId<Flatten<TSchema[key]>>>>;
} & NotAcceptedFields<TSchema, ReadonlyArray<any> | undefined>) & {
    readonly [key: string]: AddToSetOperators<any> | any;
};
```

Errors are on Flatten uses inside SetFields.

**Comment by weswigham** [comment]
It may be a regression, but it's 100% correct. We should have always issued an error on this, but failed to due to before because we took too long to expand the conditional type constraints (and issued a bogus `Maybe` result). `OptionalId` demands that the type you pass it have an optional `_id` member. Both of `Flatten`'s branches are only constrained to `unknown`, and thus _aren't_ proven to have that member. You can work around this with the traditional `Cast` conditional type if you want to, which would look like `type Cast<T, U> = T extends U ? T : T & U;` and then write `OptionalId<Cast<Flatten<TSchema[key]>, {_id?: any}>>`. But better would just be removing the constraint on `OptionalId`'s type argument if it's intended to be used on `unknown` types like this.

**Comment by sandersn** [comment]
Fixed by https://github.com/mongodb/node-mongodb-native/pull/3004
