### ISSUE TITLE
Inaccurate type for return value of `Intl.RelativeTimeFormat.prototype.formatToParts`

### ISSUE THREAD

**Issue by justingrant** [microsoft/TypeScript#46245]
# Bug Report

The types for [`Intl.RelativeTimeFormat.prototype.formatToParts`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat/formatToParts) in lib.e2020.intl.d.ts have a few issues. 

1. According to the spec (and MDN docs), either singular or plural names for units are accepted as input, but only singular names are output. The current types assume that plural names can also be output, which is incorrect.  The relevant step in the spec is Step 5 in https://tc39.es/ecma402/#sec-PartitionRelativeTimePattern, where plural inputs are converted to singular before being used in the output.

2. Also, there's a missed opportunity here to narrow the return type of this method, because for any input unit, the return unit will be the same unit, unless it's a plural in which case it's the plural unit converted to singular.  (See https://tc39.es/ecma402/#sec-makepartslist.)  So the return type could be a generic where `unit` in the output depends on `unit` in the input.

3. Finally, there's another missed opportunity to narrow the return type using the `type` property, because according to https://tc39.es/ecma402/#sec-FormatRelativeTimeToParts and https://tc39.es/ecma402/#sec-makepartslist, if `type === 'literal'` then `unit` will be omitted, while if `type` is any other value, then `unit` will be present in the output. 

I'd be happy to submit a PR to change these types. (If a PR would be welcome.) 

Here's excerpts from the current relevant types in lib.e2020.intl.d.ts:

https://github.com/microsoft/TypeScript/blob/cb158e7eb63c69b0d4007a77511b46026c924bd2/lib/lib.es2020.intl.d.ts#L114-L118

https://github.com/microsoft/TypeScript/blob/cb158e7eb63c69b0d4007a77511b46026c924bd2/lib/lib.es2020.intl.d.ts#L183-L186

https://github.com/microsoft/TypeScript/blob/cb158e7eb63c69b0d4007a77511b46026c924bd2/lib/lib.es2020.intl.d.ts#L38-L47

### 🔎 Search Terms

Intl
RelativeTimeFormat
formatToParts
plural
singular

### 🕗 Version & Regression Information

Introduced in #36084.

### ⏯ Playground Link

https://www.typescriptlang.org/play?target=99#code/MYewdgzgLgBATlAZjAvDMBTA7jAkmKAGwDoAlDQgQygEsA3DAFRoFsMAxEOF6gCgEoA3AFgAUKEiwADpQQRU8JMURceURiAAKsqBF4AWAEwAaGAHIWNMAFcoGCGaFiA9M5jkI1wlACqYGrA08lAAFhgwlMBQ1pSEMFAAnlLhcBjRcJgAJjDJcPFhMACiAMIAsgCCALT6AAyGMBDJwGKJye72Xr7+sGgARAkYsr0wAD4wvQCOMQgYcMNjvSzgofPjWBgYANarvZmUCcOj4yEg1nNHi1a2GDsQGBKZvSLi4NA5OhAA6gEhfgEKMjkyho3lmvCkqAAfDliNZuk4XpIYHCAgAudqebx-HrvOTfULYgDaNQAurDugBCZ6uGC0mAAPUZ9JcbkYSXCZnIVFoDGYbE43Go2LMMCC6BAsEoEAgNAA5mBKAAjQjhKAgeLs8weTrC4gsmBstpmfqDOAQXoisVgCURaVyhXK1Xq1oc7VY7pmYi8QwAZkMhn4YiAA

### 💻 Code

```ts
const rtf = new Intl.RelativeTimeFormat();
const parts = rtf.formatToParts(42, 'minutes');
// ResultUnit is the actual type returned per the ECMA-402 spec
type ResultUnit = "year" | "quarter" | "month" | "week" | "day"  | "hour" | "minute" | "second";
const partsWithUnit = parts.filter(p => p.unit);
const unit: ResultUnit = partsWithUnit[0].unit!;
//    ^^^^
// Type 'RelativeTimeFormatUnit' is not assignable to type 'ResultUnit'.
// Type '"years"' is not assignable to type 'ResultUnit'.(2322)
```

### 🙁 Actual behavior

TS error 2322

### 🙂 Expected behavior

No error because the unit of the return type is always singular.

**Comment by orta** [comment]
Cool, happy to have `SingularRelativeTimeUnit` added and switched out where needed 👍🏻 

I'm not too wild on making the functions generic to support some of the narrowing, we really want to keep the shipped libs as simple as possible because they get included in everyone's projects and historically a lot of the times we've been clever we've had to backtrack

**Comment by justingrant** [comment]
> Cool, happy to have `SingularRelativeTimeUnit` added and switched out where needed 👍🏻

OK, I'll send a PR soon.

I also noticed another Intl type-declaration issue: the input properties to the `options` param of the `Intl.DateTimeFormat` constructor are narrowly typed string literals, e.g. `localeMatcher?: "best fit" | "lookup"`. 

But the `ResolvedDateTimeFormatOptions` type, which should represent the same range of string literals, is typed more loosely as `string`.  Any idea why this is?  Do TS lib types generally restrict inputs but are more forgiving for outputs in order to support later platforms that can output values that old TS lib declarations don't know about?  Or is this a bug and they should match?

Here's the types for reference:
https://github.com/microsoft/TypeScript/blob/5d0d7ae85d1ff52d3ef4cb6cac653f33f7e76724/src/lib/es5.d.ts#L4392-L4406
https://github.com/microsoft/TypeScript/blob/5d0d7ae85d1ff52d3ef4cb6cac653f33f7e76724/src/lib/es5.d.ts#L4408-L4423

> I'm not too wild on making the functions generic to support some of the narrowing, we really want to keep the shipped libs as simple as possible because they get included in everyone's projects and historically a lot of the times we've been clever we've had to backtrack

OK, sounds reasonable, I won't include (2) in the PR. What about (3) above which is a discriminated union not a generic?

**Comment by orta** [comment]
Generally we want to use a union of string literals when it makes sense which is most of the time, but it's can be hard to do that (which means falling back to `string`.) For example if a new option for hour cycle is added in `es2022` we don't have a way in TypeScript to safely describe that it is `    hourCycle?: ES2011hourCycle | "h25"` when you are in es2022. 

As seen in something like

https://github.com/microsoft/TypeScript/blob/61d29393594f81fa5032b426c8bfcdbc8bd90c98/src/lib/es2018.intl.d.ts#L41-L44

The other is that these are contributions from a range of people, and while I gave them all big look over for 4.5, that doesn't make them all perfectly consistent and accurate (because I've barely used these APIs in production) - so we're OK to back breaking changes like `string` -> `"h11" | "h12" | "h23" | "h24"` so long as it has some history of been in for a while and isn't looking to drastically change in the future
