### ISSUE TITLE
Template literal in string pattern index signature error

### ISSUE THREAD

**Issue by davidbielik** [microsoft/TypeScript#46309]
# Bug Report

### 🔎 Search Terms

template literal string pattern

### 🕗 Version & Regression Information

- Typescript 4.4.3
- Typescript 4.4.5-beta

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.3#code/JYOwLgpgTgZghgYwgAgJIBED2CCuBbCcZAbwChlkQ4CAuZAZzClAHMBuc5AbTgBNeIvAPp0ABnwHCAJMUbMQLAL6iAunRD4ARtC4rkAH2Q4QAmKEEdFpUgkwhGySAgAWARmQBeEpwo4cwXjoAcgB2AAZNACYANkiQgFYAWniwgE5oxIAWCEzNRNTeFMSAZgR0+LKIFJDioIAaUkUOUgB6FuQAd2cAT2ReTAh6R2dgIegoTCgAfhs7B36EOgxsfEIwT28KKlpkACJdhooucX5BIRknNwA6PwDlNW5XVPCw11eVBqbrNuRNHHWwCMhv1BiAgmAZrZ7OsFpEllhcAQiF4yFtqBA6PtDtwTpIhHBNAhVHQuK5IsVMvEVI1rKBILBEChloi1pFNtwJGcxJzpLImKx7uotDo9IZjKZzLxLN92nATMNRn0BvQwRDZtClQhivCVkiwGyUT4cTzzsRLq4bv5eILHs8wq93p8gA)

### 💻 Code

```ts
interface IDocument {
  name: string;
  [added_: `added_${string}`]: number[] | undefined;
}

const tech1 = {
    uuid: '70b26275-5096-4e4b-9d50-3c965c9e5073',
};

// why does this error?
const doc: IDocument = {
  name: "",
  [`added_${tech1.uuid}`]: [19700101],
};

// but this doesn't?
const doc2: IDocument = {
  name: "",
  [`added_abc`]: [12345]
}

interface IDocument2 {
  [added_: `added_${string}`]: number[] | undefined;
}

// and this doesn't?
const doc3: IDocument2 = {
    [`added_${tech1.uuid}`]: [19700101],
}
```

### 🙁 Actual behavior

```
Type '{ [x: string]: string | number[]; name: string; }' is not assignable to type 'IDocument'.
  'string' and '`added_${string}`' index signatures are incompatible.
    Type 'string | number[]' is not assignable to type 'number[] | undefined'.
      Type 'string' is not assignable to type 'number[] | undefined'.
```

### 🙂 Expected behavior

I don't understand why there is an error. If i remove the "name" key, the error goes away.

If i replace the templated string with a literal string `added_abc` the error goes away

**Comment by jcalz** [comment]
I think I've explained what's going on in [my answer to your SO question](https://stackoverflow.com/a/69528712/2887218).  

As it stands the code here fails because `` `added_${tech1.uuid}` `` is seen as type `string` unless you use a `const` assertion (as per #42588).  If you add the const assertion like `` `added_${tech1.uuid}` as const `` then it still doesn't work because of #13948, because the type `` `added_${string}` `` in a computed property gets widened to `string`.  

To the extent that this issue differs from #13948, maybe it can be seen as a suggestion not to widen pattern template literal computed keys (as opposed to unions of string literals)?
