### ISSUE TITLE
Suggestion: Implicit interfaces

### ISSUE THREAD

**Issue by BigBen1307** [Microsoft/TypeScript#4633]
Caveat: I have mainly written dart code during the last 12 months.

I think it would be great if a class would implicitly define an interface that you could implement (like in dart). The implicit interface would only contain the public instance members of the class and of any interfaces it implements.

This would help in cases where you don't have control over a class, it exists in some third party library, and they haven’t exposed an explicit interface.

Example:
```typescript
class Person
{
    // Not in the interface, since this is private
    private name;

    // Not in the interface, since this is a constructor.
    constructor(name : string)
    {
        this.name = name;
    }

    // In the interface.
    greet(who : string) : string
    {
        return `Hello, ${who}. I am ${this.name}.`;
    }
}

// An implementation of the Person interface.
class Imposter implements Person
{
    greet(who : string) : string
    {
        return `Hello, ${who}. Do you know who I am?`;
    }
}
```

**Comment by mhegazy** [comment]
look like the same as #3854

**Comment by danquirk** [comment]
Yep. To be clear, this is true today:

_if a class would implicitly define an interface that you could implement (like in dart). The implicit interface would only contain the public instance members of the class and of any interfaces it implements._

The problem is just that if there are non-public members they are not dropped but are also considered part of the implicit interface of the class. The issue Mohamed mentions covers lifting this restriction somehow.
