### ISSUE TITLE
Typescript 4.5 resolveJsonModule should also work with node12 and nodenext module and resolveTypes

### ISSUE THREAD

**Issue by frank-dspeed** [microsoft/TypeScript#46362]
# Bug Report

### 🔎 Search Terms
resolveJsonModule typescript 4.5 node node12 nodenext

### 🕗 Version & Regression Information
4.5 +

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code
set resolveJsonModule true and moduleResolution node12 or nodenext in the tsconfig.json

### 🙁 Actual behavior
Errors

```
TS5070: Option '--resolveJsonModule' cannot be specified without 'node' module resolution strategy.
```

### 🙂 Expected behavior
 should work with ```node12``` and ```nodenext``` also

**Comment by weswigham** [comment]
JSON imports in esm mode imports at least are still [experimental](https://nodejs.org/api/esm.html#esm_json_modules) and need a flag, and there's a big kerfuffle over on the `node` repo as to weather they should _require_ an `assert { type: "json" }` on the import (see conversations on https://github.com/nodejs/node/pull/37375 and https://github.com/nodejs/node/pull/40250 ). We can allow it for cjs mode imports pretty painlessly, but for esm imports it's still experimental, unfortunately (and not having any named imports is unfortunately going to be a big change from current behavior, too). So the fix for this might not take the shape you're expecting.

**Comment by frank-dspeed** [comment]
@weswigham we use it only for typechecking inside our project https://github.com/rollup/rollup/blob/master/rollup.config.ts
