### ISSUE TITLE
Typescript predicts wrong type when using intersection types as parameters in overloaded function signatures

### ISSUE THREAD

**Issue by sbmelvin** [microsoft/TypeScript#46398]
# Bug Report

Consider the following: 
```
interface Options {
    complete: boolean;
}

function f(options: Options & { complete: true }): ReturnTypeA;
function f(options: Options): ReturnTypeB;
function f(options: Options): ReturnTypeA | ReturnTypeB {
    // implementation here. See playground link for full example.
}

const completeIsTrue: Options = {
    complete: true
};

const result = f(completeIsTrue);
const result2 = f({ complete: true });
```

When run, the code executes correctly with both `result` and `result2` being of type `ResultTypeA`, however in an editor (tested VSCode and TS Playground), Intellisense thinks `result` is `ReturnTypeB`. 
<img width="496" alt="Screen Shot 2021-10-16 at 1 53 15 PM" src="https://user-images.githubusercontent.com/172780/137597388-1970443d-1f53-408a-bb65-446d02f94a01.png">

This causes problems because Intellisense will then offer incorrect autocomplete suggestions and mark valid code as errors.

### 🔎 Search Terms

intersection types
function overloading

### 🕗 Version & Regression Information

Tested 4.4.3 and nightly.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about function overloading and intersection types.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.3#code/JYOwLgpgTgZghgYwgAgPIAczAPYgM7IDeAUMmcgtgLboA2EkAXMgEbbb1wgDcxAvsWKhIsRCgBKDAK5QQAFQCe6CAEEipcnGZ4wUUAHNeA4dHhJkksDPlKIAIXXlW23QaOCYUkAiy5kwPEtrRWUVAAotC2lZENVkAB8oqxjbOwBKZjh-AiCU0MdkKGiQZAjkOBzi2JU0gDosgEIAXibkLwATCBhQCHb3Yk9vXxKYMOxMHHxmDGGCADIiCmo6BghmXSkUPgyk4NsVXkGfSeRR8dnpidw8HdybZTtDr2O-M6uptHeb5jvqhN28vYCmRgDBSudJnhapQaPRIGlgU4lvgwIUIHgpLQwD8qvtkK0SEiieVmAAidBQcbIPAAC2wmParBQcFJGiJfF4xLRyRKRQxWM55D4yAgtDwKEJxMoKLR-OxAPuQIJbK5zmQ5Mp6GpdIZTNYrK5HJVTiKPNlmLAgrIAgExGlOiWsNWcigm0us3xiJhKyYyA2EH4vDt11R3rhEAAYnAxWtPh7lU4w6tmPAY-xBPbURAAB7KHxqVqjJOQF2bNLcVXkYMynN5sAqABMntGhEdPtj-u2vEzItzEB8DkLYWLkej4vL1Ydtf7YDsTaHrZHKbHWwnA2wUFKPezyGwYIA2tP8wAaXt1xuno+zy99gcNgC6CMlZHtHAgtVo2H0YVJAV++zJU8-1xUIwmzNJT3AowgA)

### 💻 Code

My example demonstrating the problem is above. The actual code that is causing this issue is:
```
export function decode(token: string, options: DecodeOptions & { complete: true }): null | Jwt;
export function decode(token: string, options: DecodeOptions & { json: true }): null | JwtPayload;
export function decode(token: string, options?: DecodeOptions): null | JwtPayload | string;
```

This is from the [type definition package for `jsonwebtoken`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9f080ffe44df63f3773fa1489b6c4833e595e6f4/types/jsonwebtoken/index.d.ts#L241).

### 🙁 Actual behavior

Type hints generated by Intellisense/static analysis are wrong when function overloads use intersection types. Seems to have something to do with object literals as well?

### 🙂 Expected behavior

The correct type hints.

**Comment by fatcerberus** [comment]
> intersecting types with similar properties sometimes results in properties having the type never.

`A & B` at a high level means "a type which is simultaneously assignable to both A and B”.  For object types, this usually just means you get a type with both sets of properties (because extra properties can be present and still be assignable to the original type), but if there’s overlap then the overlapping properties have to be intersected too, and that means you sometimes get `never`: there is no value that is simultaneously assignable to both `string` and `number`, for instance, so `string & number` reduces to `never`—an empty set.

**Comment by andrewbranch** [comment]
```ts
function f(options: Options & { complete: true }): ReturnTypeA;
function f(options: Options): ReturnTypeB;
function f(options: Options): ReturnTypeA | ReturnTypeB {
    // implementation here. See playground link for full example.
}
```

This signature can’t be correct. The fundamental problem is that if you have an `Options`, its `complete` property _might_ be `true`—you don’t know. If values like `{ complete: true }` always return `ReturnTypeA`, the second overload must be wrong, because that overload will be matched for `Options` where `complete` is an unknown boolean. Probably what you meant is

```ts
function f(options: Options & { complete: true }): ReturnTypeA;
function f(options: Options & { complete: false }): ReturnTypeB;
function f(options: Options): ReturnTypeA | ReturnTypeB;
function f(options: Options): ReturnTypeA | ReturnTypeB {
    // implementation here. See playground link for full example.
}
```

So here we say that if we _know_ that `options.complete` is `true` or `false` we can match the appropriate overload and get the corresponding narrower return type. But if we _don’t_ know what `options.complete` is (beyond the fact that it must be a boolean), of course our return type is going to be `ReturnTypeA | ReturnTypeB`. (Note also that the implementation signature doesn’t actually count as an overload, so the last one has to be duplicated. From the caller’s perspective, it doesn’t matter what goes in it. This is handy when you have so many overloads with no common supertype so you just put some `any`s in there and deal with it.)
