### ISSUE TITLE
keyof as function argument .ts(2322)

### ISSUE THREAD

**Issue by ObscurusGrassator** [microsoft/TypeScript#46390]
# Bug Report

### 🔎 Search Terms

keyof as function argument .ts(2322)

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABFApgZygRgDwBVEoAeqYAJmogN4DaA1gFyIYBOMYA5gLqNggC2AIxTMAvgD4AFHAEArRrgA0iWigCejFarjBEuAJRUAUIhOJpMums6IAvIkwAmAMwBuRAHp3iAKIAlXwDyvvKqAA4oiADkvILCkYgwFGBwUIgAhmhoMOxgaQIANhFQcMhhEZG4llo6uJyRAHQSzg4OeoYihqgYmBKUaWmMziJKkf2Rem6eiAEA0p3oWL39g07DUQIC45Nes4gS3oTh0CikPszMcMxthjegkLAIyAtOeATEKGQUNAxMUKwc3EQMSEoiUMzeJHIyjU2l0knM8iUmkYMwMlGMpnMVWsdkcrg8Xj8gWCujKUWBcQSSRS6Uy2VyBSKJSgZIq1BmdUazVa7XmGCcSwGiCGIzGEwJ0zmXSgAr6QpF6024qmu32hxQx1O3nOlzaQA)

### 💻 Code

```ts
function test1<T extends {[k: string]: number}>(obj: T, key: keyof T) {
    obj[key] = 123; // ERROR: Type 'number' is not assignable to type 'T[keyof T]'.(2322)
}
test1({aa: 23}, 'aa'); // OK
test1({aa: 23}, 'bb'); // OK (Expected Error)
    // again in JSDoc:
/**
 * @template { {[k: string]: number} } T
 * @param { T } obj
 * @param { keyof T } key
 */
function test2(obj, key) {
    obj[key] = 123; // ERROR: Type 'number' is not assignable to type 'T[keyof T]'.ts(2322)
}
test2({aa: 23}, 'aa'); // OK
test2({aa: 23}, 'bb'); // OK (Expected Error)



function test3<T extends {[k: string]: number}, K extends keyof T>(obj: T, key: K) {
    obj[key] = 123; // ERROR: Type 'number' is not assignable to type 'T[K]'.(2322)
}
test3({aa: 23}, 'aa'); // OK
test3({aa: 23}, 'bb'); // OK (Expected Error)
    // again in JSDoc:
/**
 * @template { {[k: string]: number} } T
 * @template { keyof T } K
 * @param { T } obj
 * @param { K } key
 */
function test4(obj, key) {
    obj[key] = 123; // ERROR: Type 'number' is not assignable to type 'T[K]'.ts(2322)
}
test4({aa: 23}, 'aa'); // OK
test4({aa: 23}, 'bb'); // OK (Expected Error)
```

**Comment by sandersn** [comment]
The error is correct. Here's a call to `test1` that fails because its property types are subtypes of `number`:

```ts
test1<{ a: 0 | 1, m: 1 | 2 }>({ a: 1, m: 1 }, 'a')
```

This incorrectly assigns `123` to `a: 0 | 1`.

**Comment by ObscurusGrassator** [comment]
Sorry, I do not understand your answer. Why did you use the { a: 0 | 1, m: 1 | 2 } value in your example? In my example I enter to function object with number values: {[k: string]: number} . I apologize for bothering you with this again.

**Comment by sandersn** [comment]
I guessed the missing Expected/Actual section of this bug was 

Expected: No error.
Actual. Error 2322 in the body of test1/test2/test3/test4.

If that's the case, then the error is correct, because each of those functions has a type parameter `T extends { [k: string]: number }`. Then the body of the function does `obj[key] = 123`.

The problem is that `T extends { [k: string]: number }` means that T **extends** that type. So you can restrict the value type of T's index signature to something narrower than `number`; `1 | 2` for example: `test1<{ m: 1 | 2 }>({ m: 1 }, 'm')`. The problem is that you're not allowed to assign `123` to `1 | 2`. That's why you get the error.
