### ISSUE TITLE
mts default export support for @types/node 

### ISSUE THREAD

**Issue by xiaoxiangmoe** [microsoft/TypeScript#46444]
# Bug Report

### 🕗 Version & Regression Information

TypeScript 4.5

### 💻 Code

file a.mts

```ts
import * as process from 'node:process';

console.log(
  global.process === process.default,
  global.process.cwd === process.cwd
);
```

If we save this file as mjs and it runs well.

### 🙁 Actual behavior

![image](https://user-images.githubusercontent.com/8111351/138063540-ec09a053-268e-4a14-b02e-f54cd75019e3.png)

### 🙂 Expected behavior

`default` exist on process.

**Comment by DanielRosenwasser** [comment]
This seems like a problem with the types at `@types/node`, not something specific to TypeScript, right?

**Comment by weswigham** [comment]
Uh, depends, what compiler options we talking about? We only add the implicit whole-module `default` member to the import if `allowSyntheticDefaultImports` (or `esModuleInterop` or `module: node12` or `module: nodenext`) is set.

**Comment by andrewbranch** [comment]
This does repro with `esModuleInterop`.

**Comment by andrewbranch** [comment]
But yeah, the problem is that the type definitions are written as a CJS module; there’s no `default` export to speak of. This was done because when you turn on `esModuleInterop` as a consumer and use a default import, you get pretty good cross-compatibility between CJS and ESM with only one set of type definitions. So this is a general problem with practically everything on DT where the implementation library has a module wrapper that detects for ESM usage and adds the `default` there (which is quite a lot of libraries). Going forward, these libraries can start to add separate type definitions for `import` vs. `require` with an export map if they feel like that’s valuable. But yeah, a specific request for Node to do something like this should be brought to DT.
