### ISSUE TITLE
Ternary two different types infers to one type when one is a subset of the other

### ISSUE THREAD

**Issue by danielbartsch** [microsoft/TypeScript#46449]
# Bug Report

### 🔎 Search Terms

ternary type union

Maybe related: https://github.com/microsoft/TypeScript/issues/33070, https://github.com/microsoft/TypeScript/issues/20863

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about https://github.com/microsoft/TypeScript/issues/31751, but that isn't really it I guess

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.0-dev.20211020#code/C4TwDgpgBAglC8UDeUCGAuKA7ArgWwCMIAnAbigMwGdhiBLLAcygF8AoUSKAIQWTUy5CJVmyhQ2AYwD2WGgNh8UGKAFYANBUwBybaJlzgWnkoUBGAAyi2AehtoCUBgDMSVNO+6aqAC2k4AGwATCmg4AB8eKVl5VEdEAFlUYB8AOmJULCDpPAAKAEooAD4oC1TVKAB+NChMAiA)

### 💻 Code

```ts
type A = { a: number; b: string }
type B = { a: number }
  
const a: A = { a: 5, b: '' }
const b: B = { a: 10 }

// ab infers as B, should be A | B
const ab = Math.random() > 0.5 ? a : b
```

### 🙁 Actual behavior

`ab` infers to `B`

### 🙂 Expected behavior

`ab` should infer to `A | B`

**Comment by MartinJohns** [comment]
@danielbartsch In that example the variable `ab` is still typed `B`, not `A | B`. Assigning a value to a variable narrows the type of the variable, and you're assigning a value of type `B` - so `ab` is of type `B`. This behaviour is intentional.

If you want to explicitly type it as `A | B` you can use a [type assertion](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-assertions):

```typescript
const ab: A | B = (Math.random() > 0.5 ? a : b) as A | B
```
