### ISSUE TITLE
Too many tab stops in method signature completions

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#46588]
# Bug Report

### 🔎 Search Terms
- method signature completions
- completion
- suggestions

### 🕗 Version & Regression Information
4.5.0-dev.20211029

### Problem

After playing around with method signature completions a bit for a VS Code extension, I found the tab stops to be more of a hinderance than helpful

I suggest that we remove the tab stops and only move the cursor into the correct final location inside the method:

```ts
completedMethod(param: type) {
     $0
}
```

That is the behavior I almost always want

**Comment by andrewbranch** [comment]
I suggested this at first, but then I realized the behavior is pretty good if we just make sure the _first_ tab stop is in the method body. Then a user can tab into the parameters if needed, or can hit the escape key to remove those tab stops. There’s an item open in #46568 to make the method body both the first _and_ the last tab stop as an additional improvement (`$1$0` in the body). I agree I don't often want to edit the parameter names/types, but as long as they don't stop me from getting to the method body, they don't bother me. From our conversation in the editor sync, I think @DanielRosenwasser liked having the tab stops, so this seemed like a good compromise to me.

**Comment by andrewbranch** [comment]
> There’s an item open in #46568 to make the method body both the first and the last tab stop as an additional improvement (`$1$0` in the body).

Update: open at #46593

**Comment by mjbvz** [comment]
Yes I remember we discussed this. After trying it myself though, I really don't like how all the tab stops get highlighted along with the code I type in the method body:

![Screen Shot 2021-10-29 at 2 58 16 PM](https://user-images.githubusercontent.com/12821956/139506086-d409d705-ecf1-4117-ab38-4ca5d8f4ca96.png)

 I end up pressing `esc` right away to cancel out of the snippet right away

**Comment by gabritto** [comment]
The highlights were pretty much my only concern with placing the tab stops

**Comment by andrewbranch** [comment]
> I end up pressing `esc` right away to cancel out of the snippet right away

Same, but I find I get easily distracted by completions popping up when I'm trying to think, so I already have a habit of pressing `esc` quite a lot to get rid of visual noise, so this one doesn't bother me.

I really don't have a strong opinion here, but I think the most valuable place to have placeholders is on the `any` type annotations on an overload implementation signature, because a user is pretty likely to want to change that. On the other hand, the fact that we produce `any` there is already something we'd like to improve in the future. @DanielRosenwasser's biggest concern with decisions around the placeholders was not disrupting users' muscle memory for getting to where they're trying to end up, but I tend to think that concern is mitigated by the fact that we're landing the cursor in the method body right away now. But this is perhaps something we don't want to flip flop on and confuse users, so it would be nice if we can reach a consensus we feel good about before 4.5 stable.

**Comment by DanielRosenwasser** [comment]
That was also @amcasey's concern too, so I'd like his opinion.

Here's a compromise - tab stops on parameters where all of the parameters were `any`, no tab stops otherwise.

**Comment by DanielRosenwasser** [comment]
Thinking about it some more, I actually don't mind getting a tab-stop into an `any` in TypeScript. But I also specifically took a job to add types on top of JS.

**Comment by gabritto** [comment]
I think we should get opinions from people that do use snippets, I feel totally unequipped to give an opinion on this because I pretty much just never use snippets and I *click* things heh 😅

**Comment by amcasey** [comment]
My primary concerns are (1) real-world usefulness and (2) consistency.  For me, @mjbvz's actual user experience trumps most other considerations (barring an opposite opinion from some other user).  I'm fine with never having tab-stops; I'd be reluctant to have tab-stops conditionally unless it's _really_ clear when you should expect them.

**Comment by mjbvz** [comment]
Thank you for the quick turn around! I think the tab stops sounded good on paper but weren’t great with vs code’s current handing of snippets
