### ISSUE TITLE
Go To Type Definition fails if the identifier is a type name

### ISSUE THREAD

**Issue by justingrant** [microsoft/TypeScript#46627]
# Bug Report

Go To Type Definition fails if the identifier is a type name.  This is confusing. Instead, Go to Type Definition should navigate to the declaration of the type. 

I'm filing this bug as requested by @weswigham in https://github.com/microsoft/TypeScript/issues/6209#issuecomment-525927965

### 🔎 Search Terms

Go To Type Definition

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _Go to Type Definition_

### ⏯ Playground Link

This issue cannot be reproduced in TS Playground because the "Go to Type Definition" context menu is not available in the Playground. 

However, reproducing it in VSCode is trivial. 

### 💻 Code

```ts
type T = string;
const x: T;
// in VS Code, right click on the second `T` and choose "Go To Type Definition"
```

### 🙁 Actual behavior

![image](https://user-images.githubusercontent.com/277214/139734822-ce7a7bb8-9d89-4511-9cd5-304c2c3fa2ae.png)

### 🙂 Expected behavior

Navigates to the declaration of `T`

**Comment by andrewbranch** [comment]
Proposal:

- if the symbol has a value meaning, then get its type and try to go to that definition (I think this is the only thing that happens now)
- else, if the symbol has a type meaning, try to go to its own definition
- else, give up

Not sure why we would just do nothing if the symbol has no value meaning. We could indicate a better error message to be displayed by VS Code, but that would actually be more work than just going to the definition of a type (because it would be a protocol change).
