### ISSUE TITLE
the exact behaviour of assignment semantics on callable types

### ISSUE THREAD

**Issue by icefapper** [Microsoft/TypeScript#4663]
hello
consider this: var pickyCallable: {(l: any): any, (): aType };
in the above example, only functions that have _both_ (l: any): any and (): aType signatures could be assigned to this "pickyCallable" thing; is this the actual behaviour of the typecheckr?

**Comment by ahejlsberg** [comment]
No, that's not how it works. In an assignment `f = g`, where `f` and `g` are functions of type `F` and `G`, for each signature in `F` there must be *at least one* compatible signature in `G`, but `F` and `G` aren't required to be identical. So:

```typescript
var x: { (x: any): any, (): aType };
var y: { (x: any): any };
var z: { (): aType };
x = y;  // Error
x = z;  // Ok
```

The `x = y` assignment is an error because `x` can be called with no arguments, but `y` always expects an argument. The `x = z` assignment is ok because `y` is free to ignore the argument possibly passed to `x`, and `aDate` is assignment compatible with `any`.

See also #4661.
