### ISSUE TITLE
Array comprehensions when targeting es6?

### ISSUE THREAD

**Issue by d180cf** [Microsoft/TypeScript#4666]
Are there plans to support array comprehensions, especially when generators are involved, in the es6 mode? Not sure how useful they are in general, but they seem to appear quite often in implementations of various algorithms. For instance I have an old style array initialization:

```ts
        const liberties: XY[] = [];

        for (const root of roots)
            for (const s of region(root, (t, s) => sameColor(s) && b.inBounds(t.x, t.y)))
                if (!b.at(s.x, s.y))
                    liberties.push(s);
```

The first loop iterates over a plain array, while the second - over an iterator. It could be simplified this way:

```ts
        const liberties = [
            for (const root of roots)
                for (const s of region(root, (t, s) => sameColor(s) && b.inBounds(t.x, t.y)))
                    if (!b.at(s.x, s.y))
                        s];
```

Looks a bit more concise.

**Comment by d180cf** [comment]
Btw, there is a fancy way to achieve about the same result with the spread operator and a throw-away anonymous generator:

```ts
        const liberties = [...function* () {
            for (const root of roots)
                for (const s of region(root, (t, s) => sameColor(s) && b.inBounds(t.x, t.y)))
                    if (!b.at(s.x, s.y))
                        yield s;
        } ()];
```

Not very efficient, but it should work.

**Comment by danquirk** [comment]
Array/sequence comprehensions are fantastic features and I'm sure we would love to have them at some point. However, because they're not part of ECMAScript we have to be very conservative in what expression level syntax we add here. Imagine if TypeScript adds this feature but then ECMAScript ends up adding array comprehensions in ES9 (or whatever version). If they have differing syntax/semantics then that's pretty confusing (bad, but not the end of the world). Much worse, is if ECMAScript uses the same syntax but different semantics than TypeScript originally did and now TypeScript has to make an update that breaks tons of existing TypeScript code. 

See https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals
