### ISSUE TITLE
Jsdoc https @link text not parsed properly

### ISSUE THREAD

**Issue by NorthBlue333** [microsoft/TypeScript#46734]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.6.0-dev.20211108

**Search Terms**
- jsdoc
- quick info

---

Does this issue occur when all extensions are disabled?: Yes

After searching the issues, I have found relevant ones :
- https://github.com/microsoft/vscode/issues/126180
- https://github.com/microsoft/vscode/issues/126626 (closed as duplicates of the first one)

They are closed since `v1.58.0` with this commit https://github.com/microsoft/vscode/commit/7339e948305024dbf0479e926e7e5bccb8baa97b. I don't know if they are related or  not.

---

![sandbox-jsdoc-vscode-4.4.3](https://user-images.githubusercontent.com/43409865/140770451-a336de64-1de6-49ee-ab1e-d8351b551116.png)
Using VSCode `v1.62` shipped with TypeScript `v4.4.3`, the url gets splitted after `https?`.

![sandbox-jsdoc-vscode-4.2.4](https://user-images.githubusercontent.com/43409865/140770730-56319a0c-68b3-4a9a-b4e1-0b30cd340c29.png)
Using TypeScript `v4.2.4` only URLs work, not symbols.

![sandbox-jsdoc-vscode-4.3.5](https://user-images.githubusercontent.com/43409865/140770854-eb57dd1c-64b2-4e8e-ab82-145f0d826d6c.png)
Using TypeScript `v4.3.5`, everything works fine.

I do not understand why the JSDoc implementation on VSCode is dependent of TypeScript version even in pure JS files. I apologize if TypeScript version older than `v4.3` are not supported, and I think they are not by reading the issues about implementing `@link`. 

There is still an issue with the latest version.

I currently do not have the time to investigate more, sorry for that. Thanks for reading me!

Here is the sample of code I used :

```js
class MyClass {
  foo;
}

/**
 * See {@link MyClass} and {@link MyClass.foo foo}.
 * Also, check out {@link http://www.google.com} and
 * {@link https://github.com GitHub}.
 * 
 * 
 * 
 */
function myFunction() {}
```

VSCode About section :

```
Version: 1.62.0
Commit: b3318bc0524af3d74034b8bb8a64df0ccf35549a
Date: 2021-11-03T15:18:44.904Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-89-generic
```

**Comment by mjbvz** [comment]
For:

``js
/**
 {@link http://www.google.com}
  */
function myFunction() {}
```

The returned `quickInfo` is:

```js
"documentation": [
        {
            "text": "",
            "kind": "text"
        },
        {
            "text": "{@link ",
            "kind": "link"
        },
        {
            "text": "http ://www.google.com",
            "kind": "linkText"
        },
        {
            "text": "}",
            "kind": "link"
        }
    ],
```

**Comment by fatcerberus** [comment]
> I do not understand why the JSDoc implementation on VSCode is dependent of TypeScript version even in pure JS files.

VSCode uses the TypeScript language service for IntelliSense in both JavaScript and TypeScript.  This includes JSDoc parsing, which TS implements because it can optionally use it for type checking with `checkJs`.

**Comment by SchoofsKelvin** [comment]
There's another issue regarding the display text for `@link` tags. According to the [TSDoc specification](https://tsdoc.org/pages/tags/link/) and its dependant [API Extractor](https://api-extractor.com/pages/tsdoc/tag_link/), if we want the display text to be different from the reference, we need to use `{@link DECLARATION_REFERENCE | DISPLAY_TEXT }`. But doing it this way results in the following tooltip in VS Code:
![Screenshot](https://user-images.githubusercontent.com/14597409/147279469-725d1d82-aa43-4f8d-8b4e-04ae0e558284.png)
Notice how the vertical bar (`|`) is included, even though it is not meant to be included.

While removing the vertical bar does make it display the correct text in the tooltip, this goes against the above documentation, their example code and even the official [tsdoc library](https://github.com/microsoft/tsdoc), as the latter will output a `tsdoc-reference-missing-dot` warning, since it thinks it's still parsing a declaration reference due to not encountering a vertical bar.

It's worth mentioning that [JSDoc does allow omitting the vertical bar](https://jsdoc.app/tags-inline-link.html), but it also supports having the vertical bar. Their examples showcase that if a vertical bar is used, it isn't displayed, similar to how TSDoc handles the vertical bar.

_Tested using TypeScript versions 4.4.4 and 4.5.4_

**Comment by sandersn** [comment]
@SchoofsKelvin can you open a separate bug for that? It's worth fixing, but from my perspective it's a separate feature than correctly keeping `http` and `://` together.
