### ISSUE TITLE
 static : are the semantics right ?

### ISSUE THREAD

**Issue by icefapper** [Microsoft/TypeScript#4678]
hello; consider this ts-like piece:

class C {
     static cai;
     var pinst;
};

from what I get, "static" preceding cai means it is _accessible_ and common to all _instances_ of C as well as C itself , that is , the expected behaviour might be as below: 

var c1 = new C(); c1.cai = "c1";  //c1.cai ==  "c1"
var c = new C(); c.cai = "c";  // c1.cai == "c"
C.cai = 5; // will sure be 5

I reckon that it is where "static" gets its name -- each instance has a "pinst" that  exclusively belnogs to it, and a common-to-all "cai"

  but it looks like ts does not work like that; in reality, the supposedly-common-to-all-instances "cai" is merely availabl to (and through) the class it belongs to, that is, C; one could say that C is merely a namespace around its static members

 I understand the reason of ts's "static-side instanc-side" dichotomy might well lie in the function-is-the-class-and-its-proto-has-its-instance-members semantics js is using to go OO; I do also understnd  the reason static behaves in this manner in ts is the fact that functions themselves can have members (function.memberName is ts's-static, function.proto.member is ts's-instance , and the function represents the notion of a classic "class") and the fact that assigning to a non-existing instance member would add that member to that instanc rather than looking it up in the proto and assigning the appropriate slot (that is, if I have C.proto.cai = 5, doing new C().cai = "c1" will _not_ have {C.proto.cai} become "c1") which would make having static behave the way it should somewhat complicatd to achieve when in js; still, with the compile-time semantics ts has, I  would be glad to know why its implementation is not making static behave the way it is excpected to behave ):-{

**Comment by DanielRosenwasser** [comment]
Hi @icefapper. Static methods do not exist on an instance, and if one attempts to invoke a static method on an instance we do not automatically resolve/fix the invocation to use what you may have intended. While other traditional OO languages might have those semantics, [ECMAScript does not](http://www.ecma-international.org/ecma-262/6.0/#sec-runtime-semantics-classdefinitionevaluation) and it would be harmful to diverge TypeScript from ECMAScript in its property access behavior.

This is especially important because ECMAScript needs to stay consistent with other parts of the language when possible. For instance, a statically resolvable property accesses needs to be equivalent to an element access with the analogous string:

```TypeScript
class C {
    static prop() { return 100 };
}

let propName = "prop";
let instance = new C();

let a = instance.prop(); // 'a' is 'undefined'
let b = instance[propName](); // 'b' is 'undefined'
let c = C.prop(); // 'c' is '100'
let d = C[propName](); // 'd' is '100'
```
