### ISSUE TITLE
Generic type variable is inferred as `unknown` unexpectedly

### ISSUE THREAD

**Issue by mkermani144** [microsoft/TypeScript#46805]
# Bug Report
I don't exactly know if this is a bug, a limitation of typescript or my lack of knowledge about how typescript infers generic type variables.

### 🔎 Search Terms
- Generic type variable unknown inference
- Higher order function generic type inference

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?&q=178#code/MYewdgzgLgBAFiAZgLhgHgCIEMpYHwAUAsAFAwwCWYYApgE6oFZ0Dmq2uAlDALx4wcsAGlLc+AnFl4wCVWnTH859AmACuAGw0wsEHWACenANylSoSLCk94SJq178ATCdIB6NzBoAPAA41gKBoAExgoA38YJB1UdQBbACN6d086AJoKADcQsIiaKMQYmDUwAGswEAB3MCA)

### 💻 Code

```ts
const hof: <Data>(
  inner: (arg: Data) => Data,
) => Data = (inner) => inner(null as any);

const a = hof(foo => 2);
// expected type of `a` and `foo`: number
// received type of `a` and `foo`: unknown
```

### 🙁 Actual behavior

I get type `unknown` for the return value of `hof` (and `foo`).

### 🙂 Expected behavior

I have generic type variable `Data` as return type for `hof` function, which should be inferred as `number` because of the `arg => 2` argument I have provided to `hof` function as `inner`. `foo` should be inferred to the same type, too, as both use `Data` as type.

**Comment by RyanCavanaugh** [comment]
Generic inference proceeds on the principle that information can't flow backward through time - specifically, there's no way for `hof` to know that it should pass a number to `foo => 2`, since it has to invoke the function with some argument to get the return value in the first place.

Indeed, there's nothing you could write in `hof`'s initializer that doesn't have some sort of invalid type assertion in it in that invocation.

**Comment by tadhgmister** [comment]
I appreciate you reducing the example down to something very clear but is this coming up in real code? I can't imagine a real usecase for a function with this kind of signature, how would it know what to pass the `inner` function to behave correctly? I suspect you want the generic inference in some different place in your actual case.

**Comment by mkermani144** [comment]
@RyanCavanaugh 
Hmm, interesting. I think this "disability to flow backward through time" should be documented in the handbook, as the generics section in the handbook does not cover it.

What made it confusing for me was that in `foo => 2`, no matter what the type of `foo` is, it always returns a `number` and does not depend on `foo`. I thought maybe typescript could infer it _somehow_.

Just as a workaround for the people who come to this issue in the future, in order to get the right return type for `hof`, we can do this:
```
const hof: <Data>(
  inner: (arg: any) => Data,
) => Data = (inner) => inner(null as any);
```
(I don't know if there is a better solution. I will appreciate if any.)
Of course, this only fixes the return type, but typing of `arg` is sacrificed. In order to get the type for both return type of `hof` and type of `arg`, we should annotate them explicitly.

**Comment by mkermani144** [comment]
@tadhgmister 
Yes, I had a use case so I opened this issue. I tried to add declaration file for [this react hook](https://github.com/Fieldscope/flux-hooks). I tried the following but it didn't work:
```ts
const useFluxStore: <Store, State>(
  store: Store,
  reducer: (prevState: State, store: Store) => State,
  deps?: any[],
  strictEqual?: boolean,
) => State;
```
It is off-topic anyway.

**Comment by tadhgmister** [comment]
> What made it confusing for me was that in foo => 2, no matter what the type of foo is, it always returns a number and does not depend on foo. I thought maybe typescript could infer it somehow.

Well yes but all it takes is `foo=>foo+1` to no longer be able to infer `foo`, in general a function argument can't determine the argument based on the return type since you can very easily run into a cyclic dependency. 

With your exact signature `()=>2` works as intended [playground](https://www.typescriptlang.org/play?jsx=4#code/CYUwxgNghgTiAEYD2A7AzgF3gCyQMwC54AeAESgygD4AKAWACh54BLFFEGIm2AcyPKUAlPAC8VeIKgAaRiPGSKURo2TosGEJiIoArgFsARpzE58NGkPEAmIYwD095s5euXAPQD8jIA)

```ts
declare const hof: <Data>(
  inner: (arg: Data) => Data,
) => Data
const VALIDATE_IS_NUMBER: number = hof(()=>2)
```

and knowing the actual use case was relevant because this isn't an option for you. That second argument `store` that might be used is what is tripping you up.

I suspect you would want an overload for this, the first one with the parameter `unknown` so if there is no type annotation on the `prevState` argument then the return type is still inferred while leaving the `prevState` unknown, and a second overload that works as expected when you explicitly annotate the type of `prevState` [playground](https://www.typescriptlang.org/play?jsx=4#code/PTAEDMEsCcGcBdQHsBuBTaAbJBDAJqHkmrAHYDkiSARrBuqPABZqgAO0aKAyvDvKxzQA5gFcAtmlLwAsACg8aAMaYhrcKNJL4kJKVCi6AMWwB3ADwAVAHwAKTnlFKMALlC2AqgDkP3AKIAIi6aANakSKakAJQAvNaWUW6W8iCgdEp6BKgY2PiExLCgOKQEUrCinIWQiJCFzKywOJJFdSygnPAVpPKKKmoQmtq6+oZoJhFWdg5Oru4cXNz8aC4JcQlJ8vIZpAhFbqQS1BigMQbGZra2bLHWAKxRoKkoOJiQWehYuAQAjAA07KBaowAJ5sVihcKRLZ6XbUfaHY6nUbjUyXHAuA7iI7QG44ADU3weTxeb2QH1yBAATJs5Ntdkp4VjEWcxhccHF8YTHmBsp88t8iiVQBhoEg4IwmPxQAADTnSwGFcKIZ6vPDQnaIAhI84RNEYhE4jkAOngSD8AA82HopDoXrYokSwCKxa0pbZ0ZjsTcENBIKRhArQErQCq3v9JLBGsJWLUKIhTUhQJLoARTe00PgjUA)

```ts
// first overload doesn't observe the prevState argument
declare function useFlow<T>(reducer: (UNUSED:unknown)=>T): T
// second overload does and ensures it is the same as the return
declare function useFlow<T>(reducer: (prevSate:T)=>T): T

const a: number = useFlow((p)=>5) // valid overload 1, p is type unknown
const b: number = useFlow((a:number)=>a+1) // valid overload 2

const c: number = useFlow(a=>a+1) // overload 1 and errors that `a+1` is not valid
const d = useFlow((a:number)=>a.toExponential()) // errors that (a:number)=>string is not valid, message isn't too hard to read.
```

**Comment by mkermani144** [comment]
> Win general a function argument can't determine the argument based on the return type since you can very easily run into a cyclic dependency.  

In general, yes. But what if typescript could handle these _special_ cases itself? Anyway, because I don't know how typescript does its job and whether it is possible to implement such a functionality, I leave the conversation as-is. 

As for your solution, using two overloads is a better approach than [the one I suggested before](https://github.com/microsoft/TypeScript/issues/46805#issuecomment-969278959) because as you mentioned, it covers both cases whether inner function argument is annotated or not. (In my case, though, I'm sure I will never annotate the argument.)

**Comment by mkermani144** [comment]
This issue can be closed. Just to remind again, I think the generics section of the handbook should be updated accordingly.

**Comment by RyanCavanaugh** [comment]
I don't think this sort of information is appropriate to the handbook, which is intended to be a general-purpose guide rather than an in-depth explanation of everything (including an unbounded list of "weird things we don't do" 😉). A more complete reference page on how generic inference works, which is on the backlog, will explain this.
