### ISSUE TITLE
Not all code paths return a value.ts(7030), incorrect behavior

### ISSUE THREAD

**Issue by zzzgit** [microsoft/TypeScript#46800]
# Bug Report

![image](https://user-images.githubusercontent.com/1060733/141666227-f91162cf-7ed2-4ef8-a772-12fe4740876e.png)

I got this error:

> Not all code paths return a value.ts(7030)

So, I think this behavior is not correct. There's nothing wrong with my code. 

1. if there's one item in the array that is not a card then it's not a flush. 
2. if one of the cards doesn't belong to the same suit as the first card, then it's not a flush.
3. other wise, it's a flush.

### 💻 Code

```ts
	static isFlush(cards: SuitCard[]): boolean {
		const firstCard = cards[0]
		cards.forEach((card) => {
			if (!(card instanceof SuitCard)) {
				return false
			}
			if (card.getCardSuit != firstCard.getCardSuit) {
				return false
			}
		})
		return true
	}
```

**Comment by fatcerberus** [comment]
Your code is not correct. Your `return false` is returning from your *forEach callback* (and is subsequently ignored by forEach itself), not `isFlush`, which always returns `true`.

As for the error in question: TS is alerting you to the fact that only some code paths in the forEach callback return a value.  However that’s irrelevant since the code is incorrect in the first place.

**Comment by RyanCavanaugh** [comment]
Seems like you also forgot to invoke `getCardSuit`?

Anyway, TypeScript is correct here for the reasons mentioned above.
