### ISSUE TITLE
Octal literal error is usually duplicated

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#46810]
The binder issues an error on all octal literals that are in strict mode: inside a class or module.
The checker issues an error on all octal literal types, and octal literal values when the target is `es5` or higher or the value is in the initialiser of an enum member.

```ts
export enum E {
    A = 12 + 01
}
const orbitol: 01 = 01
```

Expected: one error on each `01`.
Actual: Two errors on each `01`.

This means that octal literals nearly always get two errors, because most code targets es5 or higher and is inside a module.

The checker implementation is a bit flabby and inefficient, but is probably the best place to consolidate the errors -- and efficiency doesn't matter much for syntax that's hardly ever used. I don't think it would be difficult to re-create the equivalent of the binder's `inStrictMode` flag.

**Comment by jayeclark** [comment]
Hi @sandersn! I'm new to the repository (poking around in issues as a way to better understand the inner workings of Typescript.) I've found where the first duplicate error issue above arises and it seems like it might be most straightforward to fix within the binder. 

If I'm interpreting the explanation above correctly, the conditional to issue an error for an octal literal in strict mode should first check that the target is < es5. (If the target is es5 or higher, a general error will be issued for the octal literal, so the strict mode error is unnecessary and redundant.) 

Does that sound accurate?

I'll open a draft PR so that the location in the code & the suggested solution are a little clearer, but please don't hesitate to give feedback if I'm off base.
