### ISSUE TITLE
EventListener on a union of Element types should accept a specific event type as parameter

### ISSUE THREAD

**Issue by bennypowers** [microsoft/TypeScript#46819]
# Bug Report

### � Search Terms

HTMLElement, HTMLButtonElement, HTMLAnchorElement, HTMLElementEventNameMap, EventListener, MouseEvent, KeyboardEvent, Event, parameter, EventListenerOrEventListenerObject

### � Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `strictFunctionTypes` (this affects functions as well as methods)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### � Code

```ts
document.createElement("button").addEventListener('click', onClick);
document.createElement("a").addEventListener('click', onClick);
const clicker = document.querySelector<HTMLAnchorElement|HTMLButtonElement>('#clicker');
// @ts-expect-error: should not error, but gives type error below
clicker?.addEventListener('click', onClick);
function onClick(e: MouseEvent) {}
```

### � Actual behavior

```
Argument of type '(e: MouseEvent) => void' is not assignable to parameter of type 'EventListenerOrEventListenerObject'.
  Type '(e: MouseEvent) => void' is not assignable to type 'EventListener'.
    Types of parameters 'e' and 'evt' are incompatible.
      Type 'Event' is not assignable to type 'MouseEvent'.
```

### � Expected behavior

No error, the parameter type `MouseEvent` should be inferred as congruent with the parameter type of `EventListener`

**Comment by RyanCavanaugh** [comment]
Non-DOM version for clarity
```ts
type A = {
    listen(callback: (this: A, arg: string) => void): void;
    listen(callback: (arg: unknown) => void): void;
    isA: true;
}
type B = {
    listen(callback: (this: B, arg: string) => void): void;
    listen(callback: (arg: unknown) => void): void;
    isB: true;
}
declare const a: A;
declare const b: B;
declare const ab: A | B;
a.listen(fn);
b.listen(fn);
ab.listen(fn);

function fn(arg: string) {}
```
This happens because the signature unification step occurs first and collapses to the second overload.

I can't think of a way to handle this in the general case that isn't combinatorially explosive; it's basically the same problem as #7294 in a different form.

**Comment by wbt** [comment]
I also encountered this issue and after spending a nontrivial number of hours in the TypeScript code, found a solution to the immediate problem, as well as a more general case.  

From the [original code posted above, without the error-burying comment](https://www.typescriptlang.org/play?#code/CYewxgrgtgpgdgFwHRgE4wIYJgUQDYyyIAUARAEYQIIhykCUSGwwOAbvAgDICWAztjgxUxAORg8PMAGtRAGgAEtAMKSZ9ANwBYAFChIRZGkzZ8hTmQwMmLdp14D4wsRKmzFKtdM26wtAQquMsIKALwK+tCcSACOEMIAngDKMARgNKgAPAASACoAslwAgnBgABYgqGaGAD55hQBCVDRw1ZwAfGIAxEHSwqI+Or3CAPw2rByIDoLO4l7ySnCqboMAZhClCDy0i8syxDAAXAr5IBB8uJMI9AoA3gC+QA), I tweaked it [to put the listener definition first](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAgwgGxhA1gCgKYBciAsnCAM54CiAbnmFAJSIDeAvgLABQAJnBCAC29KADoIAJzwBDKNTR5hDHACIARiChQEKxqOk8etEQBkY5OWDwScAcggZstgDTIw6TFkYBubnwFKYpIyclQKgarSuvqGxgxmFvTWdg6eLm4e2D7cEAgWiKnY1ogAvIj+QiKiAI4g1gCeAMp4CtBwEgA8ABIAKsQmAIKQABbtYYoiAD69-QBCmtpg44EAfHYAxIVY1rbZXFvWAPwxRnTx5pbJ9o5Y6ag3PkA), and [add a more explicit null check](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAgwgGxhA1gCgKYBciAsnCAM54CiAbnmFAJSIDeAvgLABQAJnBCAC29KADoIAJzwBDKNTR5hDHACIARiChQEKxqOk8etEQBkY5OWDwScAcggZstgDTIw6TFkYBubnwFKYpIyclQKgarSuvqGxgxmFvTWdg6eLm4e2D7cEAgWiKnY1ogAvIj+QiKiAI4g1gCeAMp4CtBwEgA8ABIAKsQmAIKQABbtYYoiAD69-QBCmtpg44EAfHYAxIVY1rbZXDDAOFvFAIQlZWAgaGjMLNyIDwWO2xIxRnTx5pbJ9s-pqM89mwgA). The error remains.  However, [explicitly casting as an HTMLElement](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAgwgGxhA1gCgKYBciAsnCAM54CiAbnmFAJSIDeAvgLABQAJnBCAC29KADoIAJzwBDKNTR5hDHACIARiChQEKxqOk8etEQBkY5OWDwScAcggZstgDTIw6TFkYBubnwFKYpIyclQKgarSuvqGxgxmFvTWdg6eLm4e2D7cEAgWiKnY1ogAvIj+QiKiAI4g1gCeAMp4CtBwEgA8ABIAKsQmAIKQABbtYYoiAD69-QBCmtpg44EAfHYAxIVY1rbZXDDAOFvFAIQlZWAgaGjMLNyID4hHjtsSiNLkiDMmyyJ6BkY6PFzJZkvYXulUC89mwgA) solves it.  

The event map used to give more specific events is defined [here](https://github.com/microsoft/TypeScript/blob/d962091d94c8fa1a02a4a88c2b6e9809472a1509/lib/lib.dom.d.ts#L5550) (with the click event listed [here](https://github.com/microsoft/TypeScript/blob/d962091d94c8fa1a02a4a88c2b6e9809472a1509/lib/lib.dom.d.ts#L5562)). That map is merged with others [here](https://github.com/microsoft/TypeScript/blob/d962091d94c8fa1a02a4a88c2b6e9809472a1509/lib/lib.dom.d.ts#L6378) and used on [this line](https://github.com/microsoft/TypeScript/blob/d962091d94c8fa1a02a4a88c2b6e9809472a1509/lib/lib.dom.d.ts#L6401) to add the more specific event listeners.  The definitions of [HTMLAnchorElement](https://github.com/microsoft/TypeScript/blob/d962091d94c8fa1a02a4a88c2b6e9809472a1509/lib/lib.dom.d.ts#L5948) and [HTMLButtonElement](https://github.com/microsoft/TypeScript/blob/d962091d94c8fa1a02a4a88c2b6e9809472a1509/lib/lib.dom.d.ts#L6129) show that both directly extend HTMLElement,  but both also have a definition for `addEventListener<K extends keyof HTMLElementEventMap>...` where the ‘this’ type is specified more narrowly than in the parent. 

This is not an obvious solution because one would expect TypeScript to be able to figure out that `clicker` is an `HTMLAnchorElement|HTMLButtonElement` which are both `HTMLElement`s so `clicker` should be treatable as an `HTMLElement` without requiring the cast. However, because both subtypes override the parent's `addEventListener` method, each subtype appears to be treated as if that method were not defined on the parent, and TypeScript won't look at that parent definition when trying to match. 

In the much more general case, I think it would be reasonably efficient that if there’s an error encountered in matching a function on a union type, search the nearest common ancestor of the unioned types.  Computing the nearest common ancestor type of a union type seems like it could be relatively efficient especially with the relatively short inheritance chains that are common in practice.  In this case, it would have been easy to identify `HTMLElement` as a common ancestor, along with all of its ancestors, and search there for a matching signature.  As shown by the success of the cast, this would’ve worked.

In the moderately general case, it seems like it should be possible to address this in the lib.dom.d.ts file that ships with TypeScript, using a generic such as
````typescript
interface HTMLEventListener<E extends HTMLElement> extends DocumentAndElementEventHandlers, GlobalEventHandlers {
    addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: E, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: E, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}
````
and then the individual elements could extend that type, either directly or through another layer with generic, such as 
````typescript
interface HTMLButtonElement extends HTMLElement, HTMLEventListener<HTMLButtonElement> {
````
or 
````typescript
interface HTMLElementWithListeners<E extends HTMLElement> extends HTMLElement, HTMLEventListener<E> { 
//...
interface HTMLButtonElement extends HTMLElementWithListeners<HTMLButtonElement> {
````
In such a PR, the two interfaces extended by `HTMLEventListener` would be removed from `HTMLElement`.  However, it would also appear to be necessary to similarly genericize `Element`, `EventTarget`, `EventListenerOrEventListenerObject`, and `EventListener` to avoid conflicts, and that sounds like much more major surgery than my time budget allows. There may be a much simpler way to do this with other features of generics that are beyond my current time budget to explore but which may be already known to someone more expert than I.  This might not be the only issue fixed by such a use of generics.

**Summary:** It's definitely possible to overcome this in a very specific case by casting, likely possible to overcome this in a moderately general case by changes to the DOM type library, and maybe possible to overcome this in a much more general (though still not universal) case by examining common ancestors of unioned types for signature matches where the existing searches fail.

**Comment by RyanCavanaugh** [comment]
The bulk "Close" action I applied to Design Limitation issues doesn't let you pick what kind of "Close" you're doing, so don't read too much into any issue's particular bit on that. I wish GitHub didn't make this distinction without a way to specify it in many UI actions!

The correct state for Design Limitation issues is closed since we don't have any plausible way of fixing them, and "Open" issues are for representing "work left to be done".
