### ISSUE TITLE
`ThisType` doesn't work when extending it with an interface

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#46835]
# Bug Report

### 🔎 Search Terms

thistype interface

### 🕗 Version & Regression Information

4.6.0-dev.20211116

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.0-dev.20211116#code/JYOwLgpgTgZghgYwgAgGIHt3IN4FgBQyRyMmAXMgBQCUyAvAHzIBu6wAJgNwEC+BBoSLEQoAchADuAFQAWwAM4BJcNHhJkEAB6QQ7eclkKpATwAOEADwZ0TPIWIyIAGyfoKNek1Yde-fGDMxSUN5E3N6AzlQwKtMJgAyHAJiZEcXNypaRhY2dl98AgR0EHkwEgBXEAQwYGL5CnFpKLCUOiT7IjTXChhK6tqQDzsUlLAogDpSdBpOZAB6OYl0KABreWTiPnwtwrqy3qqauoAmBuCo5SE1VvaUroyD-uKhjZHkMYVJzBn5ufZ0CDyEAAcjKS1WAH5Xsgtjt8EA)

### 💻 Code

```ts
interface Foo {
    foo: () => void;
}

interface NewThisInterface extends ThisType<Foo> {
    hello: () => void
}

type NewThisType = ThisType<Foo> & {
    hello: () => void
}

const functions: NewThisType = {
    hello: function() {
        this.foo(); //works
    }
}

const functions2: NewThisInterface = {
    hello: function() {
        this.foo(); //doesn't work?
    }
}
```

### 🙁 Actual behavior

> Property 'foo' does not exist on type 'NewThisInterface'.(2339)

### 🙂 Expected behavior

no error

**Comment by MartinJohns** [comment]
Possibly because `interface` and `type` are not equivalent. Interfaces are subject to declaration merging, and don't extend `Record<string, unknown>`.

**Comment by DetachHead** [comment]
yeah i'm aware of the differences between types and interfaces, but i don't see how any of those differences would break `ThisType`, though it's hard to tell because `ThisType` seems to be intrinsic, although it isn't marked as such

**Comment by fatcerberus** [comment]
The purpose of `ThisType` is to change the contextual type of anything assigned to it (e.g. object literals without an explicit `this` type on their methods).  `extends` isn't assignment so inheriting from it doesn't work.

**Comment by RyanCavanaugh** [comment]
`extends` and `&` are different operations. `extends` "copies down" the operand type's members, and `ThisType` is just a marker type, so effectively nothing happens because there is nothing to copy down. Intersection is intersection, so when contextually typing the function, we can successfully find the nominal `ThisType` among the intersection's constituents.

This wouldn't be fixable without doing some heavy-duty changing of what `extends` means in a way that would have observable follow-on effects, and this behavior has been present since 3.3.3, so I'm going to round this up to "intended" behavior.
