### ISSUE TITLE
btnEvent is not triggering

### ISSUE THREAD

**Issue by TheMasterRoot** [microsoft/TypeScript#46839]
Hello , im using the new node jabra sdk ( 4.0.1 ) with a Blueparrot Headset.
Id like to capture BlueParrot Button Events but its not working

here is my code:

`const j = require("@gnaudio/jabra-node-sdk");
j.createJabraApplication('900').then((jabra) => { 
    jabra.on('attach', (device) => {
        console.log('Press any key on Jabra device ' + device.deviceName);        
        device.on('btnPress', (btnType, btnValue) => {
          console.log('New input from device is received: ', j.enumDeviceBtnType[btnType], btnValue);
        });	
    });
});`

the `device.on` action is not triggering by any button pressed
my blueparrot headset model is : `C300-XT MS`

please some one can help me?

**Comment by MartinJohns** [comment]
This repository is not suited to for such questions. You should try ask on StackOverflow.

**Comment by jcalz** [comment]
"Sir, this is a Wendy's."

This isn't the place for such questions; you might want to try Stack Overflow.

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
