### ISSUE TITLE
Objects with the same type from different files have different behavior.

### ISSUE THREAD

**Issue by TotooriaHyperion** [microsoft/TypeScript#46834]
# Bug Report

Objects with the same type from different files have different behavior.

It happens _**when the type extends a type that is not Empty**._

### 🔎 Search Terms

Actually, the problem is so weird that as a non-native English speaker, I don't know what keyword I should use to search.

I can only find something like duplicated type declarations from multiple files etc...

### 🕗 Version & Regression Information
typescript: 4.4.4
tslib: 2.3.1

I just find that inconsistent behavior.

Add: Just checked all my recently used versions, this happens from(but not starts at, because I haven't used this code at versions that are lower than 4.1.3) typescript@4.1.3 to typescript@4.4.4.

### ⏯ Playground Link

It only happens in a situation with multiple files. So I have to reproduce it with a repo.

https://github.com/TotooriaHyperion/maybe-ts-bug

### 💻 Code

https://github.com/TotooriaHyperion/maybe-ts-bug

![image](https://user-images.githubusercontent.com/16434801/142141926-cfb17e79-227b-43d9-80be-303bc4a80b2b.png)

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
```

### 🙁 Actual behavior

Notice that in src/spec.ts, Line 25 to 35
The infer2(outerIdWithSymbol) should not error but behaves the same as infer2(innerIdWithSymbol).

```ts
// changing 
export interface ToInferWithSymbol<T = any> extends Symbol {}
// to
export interface Empty {}
export interface ToInferWithSymbol<T = any> extends Empty {}
// can fix it

// but this also has the problem
export interface NotEmpty {
  a?: number;
}
export interface ToInferWithSymbol<T = any> extends NotEmpty {}
``` 

### 🙂 Expected behavior

The two object(innerIdWithSymbol and outerIdWithSymbol) from different folder with same type **Identifier\<Target\>** behaves consistently.

**Comment by whzx5byb** [comment]
If you change 
```ts
const innerIdWithSymbol: IdentifierWithSymbol<Target> = Symbol("");
```
to
```ts
const innerIdWithSymbol: IdentifierWithSymbol<Target> = Symbol("") as IdentifierWithSymbol<Target>;
```
It will behave the same as `outerIdWithSymbol`. The reason is that the type of `innerIdWithSymbol` is narrowed to a unique symbol, instead of `IdentifierWithSymbol<Target>`. There are some discussions in https://github.com/microsoft/TypeScript/issues/46731.

PS: You can use [Bug Workbench](https://www.typescriptlang.org/dev/bug-workbench/?#code/PTAEAEDMEsBsFMB2BDAtvAXKALgTwA7wDOAdNkQFDwAe+A9gE7ajSLbwOTIDG8oAKnQCSiSBwA8-UAF5QyRLgB8oAN4BfKrUbNW7Tjz6CRYhgHVo2ABYBlXKgBGdWJJlyFymu0QATIqFsOTqoamvRMLGwcXLygAIL2RNgMPNiSyioUoKD4DHTYeQSYAgDcFCE0Ycx4hP4cAG7QvELeSNjQMBL8yrKJDKwA5qAAPqBEdo6ww6AAcvAA7sj2CGlT8b0paaWh2hF60XyzC0vwKxlZiPOgABQAlFj8peVa4dV8za3t0J2u8kquRqJOsoRtZ6o14O82J8gaUKjtXqBIW0OmYLDZxk4XLJft1MlMASZzFYAhM0niQWCmi0oSjNhRti9CgJkAx+vBmLIzqBEABXVBYXkODiPLZw8LcOiIRKgOg8vTNLBI6EMSQstnYbr+DGwK4AIl1N1hz2YEqlzFl8u8RPRgVgiupyK+qOJ2tVrPZmpJTj1Bq2FBAEBgCBQ6CwkEQZEo0FQlVUAmEgIYABp48YONavZM1KBILlUKBdSRgK8iLrRcaczzENw2pKIiY0lc6lgANoEoEAXTuoDbHaNscgVZr0DrrAb-AAjCn+AAmRRN1vtlWTxTThPjuddxdTgQzvsM5iD6u1xD176eJC+HskG9LlsdjvzvE3kjQXz3CjdrktgDSEVAADW8C4HQkACB29y-h2oAXj4fhLuIY4cKAAAKygAPyoaAArwHUwplP2OxHsOo6Jrcqh4gw7I8gwp7qHIfi-I89JioeQ4nmeDAzo2zY9kuGaul0W58furGVseI6nkhXGSDus5PlkvFtuu6ZopmsmrqmiYCbakibkmn7btOe6EeExEcdJ3FSLBV4ti+-Fqdq96Plcz43m+RAfl+eK-v+QEgWB-AQQIUEwdQXhXg5Lq6dJqEYVhOF4QwIoHuJJFSYmM7kVyVHYDRdHZsgjEKMx-pgFAcBIGgRREIQ3CRhQ0axionEppZoDZrmdD5oWwDhmWjUxjsXJKiiBlZKNTo6RM40ynKHDNLNFoLVajm2rN-BquyBmdXmBZFiWA0UKa0qsBcDAKoiDrKm66qetqPqGsdkqnYg53NNNTj2h8KKfc4m3uhqriZo9DFXT9U1raSAN3VsJ3MC2XWoCI50TtBsjSVcZ0rU98M9kjKMcHuriYy22MXd4XZbATb0cBOJCCqUNPnTODN8nDL0I0jADy80MGjJNkctFO45z+N5rzejExjZEtsLzRU-SPN8-TjMUMrUts6gHNmuL3WEwwADM6OcVl5MfVDTii7riN5gbAAsJuWVcZO0xTf2K+rdtu4bWtM97532379J47b3WSxwxuCyYWXy6t0UTNb0ph6gEcMI70dEy7cce09Xvh3zvtqxrHBB4zQA) to reproduce bug with mutiple files.

**Comment by TotooriaHyperion** [comment]
It's intended behavior but needs a better hint.

related discussion
https://github.com/microsoft/TypeScript/issues/46731

related suggestion
https://github.com/microsoft/TypeScript/issues/45870
