### ISSUE TITLE
Unnecessary debugger statement

### ISSUE THREAD

**Issue by lgrammel** [microsoft/TypeScript#46883]
# Bug Report

There is a debugger statement in https://github.com/microsoft/TypeScript/blame/main/src/compiler/debug.ts#L113 that disrupts plugin development when using TypeScript as a npm module in VSC.

Opening this bug report and a PR in case this has been inadvertently put in and can be remove.

It get's triggered when e.g., resolving position in the AST when the input position information is wrong (i.e. the position does not exist in the AST).

### 🔎 Search Terms

debugger

### 🕗 Version & Regression Information

4.3

### ⏯ Playground Link

N/A

### 💻 Code

N/A

### 🙁 Actual behavior

VSC stops in the debugger.

### 🙂 Expected behavior

No debug stop when an error occurs (only exception thrown).

**Comment by MartinJohns** [comment]
Related: #40729 and #32313.

**Comment by RyanCavanaugh** [comment]
@MartinJohns is correct; this statement is there on purpose. It's extremely useful because it's impractical to have first chance exceptions on due to other codepaths that need to throw for performance reasons, but you virtually always want to break on this particular function call since it means an important invariant has been violated

**Comment by lgrammel** [comment]
Cool, I'll close the bug & PR. I was in fact usign the API somewhat incorrectly due to a race condition (converting position information on a new AST with locations from the old input text).
