### ISSUE TITLE
bug in type narrowing

### ISSUE THREAD

**Issue by ARZarkesh** [microsoft/TypeScript#46885]
# Bug Report

I wrote a helper type to making some fields of object optional. But I got the following error in type narrowing.

### 🔎 Search Terms

type narrowing, optionalize

### 🕗 Version & Regression Information

- 4.4.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBA8mwEsD2A7AhgGwQLwgHgBUAaKAaSggA9gIUATAZygGsIQkAzKAgPigF5YAWwTBCJUnwBkUAN5QA2qTZQEKMgF0AXNyUaoAHygBXehA5qIdKAF8AUHdCQoAQQAKASQFyolHSmMhACMIACcSEB0GYFC1AHNbBw5TAGNEVCgGWjoACjUwY2AdOHT0LFw8dw8SAHIQGp4ASh0quTsoVS48lALgADoQAX5BUzpzSzpGqGAAC1CkAHcoFAglgFFQ+dCcmrUAN0wEa3zCmsaHDtCIYGNQ9RPgOxsgA)

### 💻 Code

```ts
type Optionalize<T, K extends keyof T> = Omit<T, K> & { [Key in K]: T[K] | undefined }

type API = { x: number, y: string }

function send(input: Optionalize<API, 'y'>): API {
  if (input.y === undefined) throw new Error('invalid input')

  return input
}
```

### 🙁 Actual behavior

`input.y` is `string | undefined`

### 🙂 Expected behavior

I expected `input.y` to be `string`

**Comment by MartinJohns** [comment]
Your described actual behaviour is wrong. The actual behaviour is what you describe in expected behaviour. The type of `input.y` **is** narrowed to `string`, **it is not** `string | undefined` anymore.
![image](https://user-images.githubusercontent.com/5269069/142759614-99d72b08-6021-4ed7-9b38-a667a3933c89.png)

---

You expect the type of `input` to be narrowed to `API`, but that's not supported.

[Quoting @jack-williams:](https://github.com/microsoft/TypeScript/issues/31755#issuecomment-498669080)

> Type guards do not propagate type narrowings to parent objects. The narrowing is only applied upon access of the narrowed property which is why the destructing function works, but the reference function does not. Narrowing the parent would involve synthesizing new types which would be expensive. More detail in this [comment](https://github.com/microsoft/TypeScript/issues/30506#issuecomment-474802840).

Used search terms: `type guard property parent`
