### ISSUE TITLE
can we export more declaration file for us library?

### ISSUE THREAD

**Issue by Mcalready** [microsoft/TypeScript#46895]
# Suggestion

## ⭐ Suggestion

When I was writing a library, there were three libraries under my namespace. After publishing to npm, when I used my library in the typescript project. the main namespace repository would not report an error when it was used. 
```typescript
import { A } from 'my-library';
...
render(){
  return (<A/>)
}
```

When using a sub-repository, it will report an error "Could not find a declaration file for module'my-library/libs/js/libsB'"
```typescript
import { B } from 'my-library/libs/js/libsB';
...
render(){
  return (<B/>)
}
```

In my library's package.json，I want to set types param a object，but types param is required string.
At present, the type field is set in my package file like this：
```json
{
  ...
  types: 'lib/types/a.d.ts'
}
```
I see. the following usage may be feasible, but it is not currently supported, I hope to support it in the future:
```json
{
  ...
  types: {
     'my-library': 'lib/types/a.d.ts',
     'my-library/libs/js/libB': 'lib/types/libB/b.d.ts',
  }
}
```
Grateful！！！

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!

**Comment by fatcerberus** [comment]
@RyanCavanaugh It looks like it's a feature request for the `types` field in package.json, though?

**Comment by mdbetancourt** [comment]
it's a question because there is already a solution for it (only for nightly builds) with exports https://nodejs.org/api/packages.html#conditional-exports
like
```json
{
  "exports": {
    ".": {
      "types": "..",
      "import": ".."
    },
    "./libs/js/libsB": {
      "types": "..",
      "import": ".."
    }
  }
}

also he can put the .d.ts files togethers

libs
|- js
|- |- libsB.js
|- |- libsB.d.ts
