### ISSUE TITLE
No proper check for interface type

### ISSUE THREAD

**Issue by eshturman** [microsoft/TypeScript#46914]
# Bug Report

### 🕗 Version & Regression Information

- Any version

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.1.5#code/JYOwLgpgTgZghgYwgAgJIAUD2UzIN4CwAUMsiJmMDAJ4AUAJnGHAFzIDkc7yAPhwEbc+7BEI712ASjYA3TMHoBuYgF9ixBABs4AZx3IAgvmKkEmEDrBQArgjDZaAB2v9NwBMh3QZ7iAbYY2GCSxiSknt6+BgB05JQ0tJxSymFqRGka2nrIAMqRSEaEYXFUdIzMbAJSoeHIJshpGURmFrheUD4FyAC8ZBAA7rn5frSSKcQgA4a07Z1+Y0A)

### 💻 Code

```ts
interface IPort {
  notify(data: 'a' | 'b' | 'c' | 'd'): void;
}

class A {
  constructor(public serviceA: IPort) {
    serviceA.notify('a');
  }
}

class ServiceA {
  notify(data:  'b') {
    
  }
}

const serviceA = new ServiceA();

new A(serviceA);
```

### 🙁 Actual behavior

I am not getting the error

### 🙂 Expected behavior

I expect to get a mismatch error between the type of the expected interface and the actual implementation

**Comment by MartinJohns** [comment]
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant

Use properties instead of methods.

**Comment by Enuvid** [comment]
This works also in common:

[Playground](https://www.typescriptlang.org/play?ts=4.1.5#code/JYOwLgpgTgZghgYwgAgJIGUD2BbFBvAWAChlkEoI5IAKANzimDnAC5kByOd5AHw4CNufdgnYBKNrUzAAJgG5iAX2LEEAGzgBnTciy5kwbAAc1EXOB0Yc+YqXKUa9RszBtOQgeOR5kyon9VMEE0wZE1rNit9AF5kEAgAd11rajEFInDcADp7KghqEXF0lSIAelLkAFpqypLiMABPIxQAMRAADWRYujg1Ny5eTzEugD5kKVl0xubkNoBNLuQevo4B4UFBwuHosYn5EoQgkOQADzY2zu76NW2xvEV0w+DQhvOQBave2+8Hg6OXgBMbw+pzkQA)

For example here:

```ts
type FnX = (val: 'a' | 'b') => void;
type FnY = (val: 'a' | 'b' | 'c') => void;

const x: FnX = (val: 'a' | 'b') => {};

const y2: FnY = x;
```

We are not able to assign `FnX` method to `FnY`.

> Type 'FnX' is not assignable to type 'FnY'.
  Types of parameters 'val' and 'val' are incompatible.
    Type '"a" | "b" | "c"' is not assignable to type '"a" | "b"'.
      Type '"c"' is not assignable to type '"a" | "b"'.

because otherwise, we will able to:

```ts
 y2('c');
```

that did not look valid.


**But with implementing interface in class we able to use a subset of parameter type (instead of same type or superset) without any error:**
```ts
interface ISome {
  create(variant: 'a' | 'b' | 'c'): void;
}

class Some implements ISome {
  create(variant: 'a' | 'b') { }
}

const some: ISome = new Some();
some.create('c');
```

This looks not valid from my point of view. I guess there should be caused an error in the implementation stage or on assigning Some to ISome.

**Comment by MartinJohns** [comment]
As mentioned before, this is working as intended and a known unsoundness. You will have the same behaviour with functions if you disable `strictFunctionTypes`.

If you use properties instead you have the behaviour you want:

```typescript
interface ISome {
  create: (variant: 'a' | 'b' | 'c') => void;
}

class Some implements ISome {
  create: (variant: 'a' | 'b') => { }
}
```
