### ISSUE TITLE
Using startsWith & endsWith to narrow type

### ISSUE THREAD

**Issue by LinusU** [microsoft/TypeScript#46958]
# lib Update Request

## Configuration Check

My compilation *target* is `ES2020` and my *lib* is `ES2020`.

## Missing / Incorrect Definition

`startsWith` & `endsWith` doesn't narrow the the type, it just returns a boolean.

## Sample Code

```typescript
interface BuiltinPaymentMethod {
  id: `builtin-${string}`
  // ...
}

// ...

declare const id: string

if (id.startsWith('builtin-')) {
  // Here I want `id` to be typed as `builtin-${string}`
}
```

## Documentation Link

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith

## Pull Request

https://github.com/microsoft/TypeScript/pull/46959 🚀

**Comment by RyanCavanaugh** [comment]
I don't think this is a good fit for the general library. Two main concerns: Changing a function from not-overloaded to overloaded has fairly pervasive effects in areas like contextual typing, generic inference, and how exactly it can be invoked with the method operand is a union. The other is that template string literals are inherently combinatorially explosive, so a call like `startsWith(union of 24) && endsWith(union of 24)` produces a union of 576 elements, which is bad from a performance and comprehensibility perspective.

Thankfully since this is an additional overload rather than a replacement, you can add it to your own project through declaration merging if those trade-offs are a good fit for your use cases.

**Comment by LinusU** [comment]
Fair enough, thanks for taking the time to explain

**Comment by alexgleason** [comment]
Here is a declaration that does it:

```ts
interface String {
  startsWith<P extends string>(searchString: P): this is `${P}${string}`;
  startsWith<P extends string>(searchString: P, position: 0): this is `${P}${string}`;
}
```

I created an MR to add this to the ts-reset package: https://github.com/total-typescript/ts-reset/pull/161

**Comment by PatrykKuniczak** [comment]
There still no place to implement it inside TS?
