### ISSUE TITLE
Incorrect ES6 module default export type

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#4707]
Code

```ts
// export.ts
export default typeof foo;
export var bar: typeof foo;
declare var foo: {
  ()
}
// import.ts
import { default as foo, bar } from './export';

var fizz: { () } = foo;
var bazz: { () } = bar;
```

expected

```
$ node built/local/tsc.js --module commonjs export.ts import.ts
```

actual

```
$ node built/local/tsc.js --module commonjs export.ts import.ts
import.ts(4,5): error TS2322: Type 'string' is not assignable to type '() => any'.
```

**Comment by vladima** [comment]
this is by design, `typeof ` in a value position is a javascript [typeof operator](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-typeof-operator) that returns a string and I guess here it is mistaken with `typeof `TypeScript [type queries](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#3.8.10)

**Comment by falsandtru** [comment]
Sorry, this is my mistake. Thanks for your help.
