### ISSUE TITLE
Inconsistent return type widening

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#47108]
Reported [on DT](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57563#discussion_r766357595).

Why would these two declarations produce different types?

```ts
declare function useState1<S>(initialState: (S extends (() => any) ? never : S) | (() => S)): S; // No args
declare function useState2<S>(initialState: (S extends ((...args: any[]) => any) ? never : S) | (() => S)): S; // Any args

const func1 = useState1(() => () => 0); // () => number
const func2 = useState2(() => () => 0); // () => 0
```

[Playground](https://www.typescriptlang.org/play?ts=4.6.0-dev.20211210#code/CYUwxgNghgTiAEAzArgOzAFwJYHtX2QGcQBlDKDEARgB4SA+ACi1S2ygjIpAC55GS8EAA9KqYIX6MAlPAC89eFFQBPWQH54qEADcQMeHxKyAPlNkL4x6UYDc8APQP4AORxKYAc0IAoUJFgEFHRsPAJiLkoAJjomFjYsDkjefkERMQkpADoc2G8+ZRUAbQBdC0VCjS1dfUMrU3N5RWs7R2cAQVUPbx8fMDxCDCQ0MCp5cNJySipGGSb+cvgABml7JwX51GQAWwAjfT6BoeCwKPGiSe4o2cW5yxW15zvFJaA)

It seems to have been like this since 3.6, so not urgent - just perplexing.

**Comment by amcasey** [comment]
@DanielRosenwasser offered a [tweaked](https://www.typescriptlang.org/play?ts=4.6.0-dev.20211210#code/CYUwxgNghgTiAEAzArgOzAFwJYHtX2QGcQBlDKDEARgB4SAaeAFXhAA9LVhD4SA+ABRZUWbFAhkKIAFzwBLdp25yBASngBePvCioAnuoD88VCABuIGPFlN1AHxXqtvVatkkA3PAD03+ADkcHRgAc0IAKFBIWAQUdGw8AmJJSgAmOkYFDhAuHn4hETEJckpZeVZs3JUAOlrYMNldPQBtAF0nbSajE3NLa2Z7R01tEld3L194AEF9YLDw8LA8QgwkNDAqTSTSEuoBNWG5DvgABlUJvwPnVGQAWwAjS0Xl1biwVK2iHalU-eOr7RnC5HQ4nIA) version that behaves more intuitively.

**Comment by DanielRosenwasser** [comment]
The tweaked version was intended to see if we could "capture" where things are going wrong, I just feel more confused now though 😅

**Comment by weswigham** [comment]
`useState1` silently creates a circularity during instantiation that makes the return position contextually typed by `any` rather than itself, which it otherwise would be typed by; `useState2` avoids this because it hits our `isAnySignature` fast path in `compareSignaturesRelated` and thus avoids recursively pulling on the return type of the target signature.

It's pretty easy to expand that fast path to avoid pulling on the source signature return when the target signature return is `any` - in fact, we already do so for `void` returns. Now, that makes both cases consistent - in fact, it _also_ makes the other two examples from the playground @amcasey linked _also_ fall into line with a literal `0` return type.

Now, is that prefered? Ehhh

**Comment by weswigham** [comment]
I have [another change](https://github.com/microsoft/TypeScript/commit/7e6b4fc7d54cdd71571608a874b9aab66ed6e74f) I can layer on top of #47306 if we'd like to fix the broader issue of signatures contextually typing themselves and creating literal return positions; it just has more (imo, intended) fallout in our existing baselines.
