### ISSUE TITLE
Auto imports not provided for rxjs operators

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#47139]
From @benlesh

> ```
> mkdir temp/
> cd temp/
> npm init
> npm i -D typscript
> npx tsc --init
> npm i -S rxjs
> ```
> 
> make `get-data.ts`:
> 
> ```ts
> import { Observable } from 'rxjs';
> declare const getData: () => Observable<string>;
> export default getData;
> ```
> 
> Add `index.ts` and type:
> 
> ```ts
> import getData from './getData';
> 
> getData().pipe(m/**/
> ```

Request completions at `/**/`

> ...I'd expect to see `mergeMap` or `map` from the rxjs package suggested, but it doesn't do that for me.

**Comment by DanielRosenwasser** [comment]
Looks like this is working.

**Comment by RyanCavanaugh** [comment]
"Have you tried turning autoimports off and then back on again"

**Comment by benlesh** [comment]
This works and the latest version of RxJS 7.2+ but not with deep imports from RxJS 6, for example from `rxjs/operators`. Which is why I was under the impression it didn't work. I did have auto imports off though. Hahaha. 😅

So it's a non-issue unless it's a deep import it seems in which case it doesn't work for whatever reason.

**Comment by benlesh** [comment]
You can probably close this unless you think the deep import thing is a problem.

**Comment by RyanCavanaugh** [comment]
I believe the issue of deep operators is addressed elsewhere - specifically that they're either dispreferred due to being a "longer" path than the top-level re-export, or that those files don't end up in the program at all until the first time they're imported.
