### ISSUE TITLE
ReReview the Issue : Compiled JavaScript import is missing file extension

### ISSUE THREAD

**Issue by jogibear9988** [microsoft/TypeScript#47188]
This issue was closed as "works as intended" see: #40878 

How can that be?

Why are imports transpiled to workin ones when using "System" or "Amd" as module type. But don't work if I use "ESM" modules.

**Comment by DanielRosenwasser** [comment]
The reason that system and AMD work is because those systems define a set of conventions for how a module is resolved at runtime, and if you omit the module's extension, they'll still perform a `.js` lookup. With ES modules, the same isn't built-in.

There is a lot of discussion on that thread, along with several linked threads that can provide some background - specifically

- https://github.com/microsoft/TypeScript/issues/40878
- https://github.com/microsoft/TypeScript/issues/15479
- https://github.com/microsoft/TypeScript/issues/13422

Unfortunately we can't reiterate the same points over and over. I encourage you to read through these discussions, and I hope you understand that the problem space is not an easy one to tackle for the general case.

**Comment by fatcerberus** [comment]
To add to the above: TypeScript *in general* doesn't touch your import specifiers, regardless of the setting of `"module"`.  The bug, if there is one at all, is that there is not (yet) a module resolution mode in tsc that corresponds to the runtime behavior of ESM-based engines; they're all too lenient.  In all cases you're meant to use the specifier that works at runtime, that's just not properly enforced in ESM codebases.  From what I understand, this is a big part of what the `node12` and `nodenext` module modes are meant to solve.

**Comment by jogibear9988** [comment]
But also Typescript does do a lookup to find the Modules. And it also does that acording to some rules. Why should it not be possible to do this also in the compilation process?
In my build process, I only have a small gulpfile wich changes the imports (see: https://github.com/node-projects/web-component-designer-demo/blob/master/gulpfile.cjs), but okay I do not respect every rule wich is mention in the node spec.
Typescript already needs to finde the imported file, so why can't it write that path to the file? 
It does not need to be the standard, but why no option to allow this?
Is it really needed people add a bundling step, only to change the import paths?

**Comment by jogibear9988** [comment]
I've created a pull request wich wich solve this for raltive imports, see:

https://github.com/microsoft/TypeScript/pull/47436

I've added a compiler switch:

       appendModuleExtension
