### ISSUE TITLE
TS 4.5.4 - Array.prototype.reduce: wrong overload type

### ISSUE THREAD

**Issue by djfm** [microsoft/TypeScript#47243]
In the following simplified code, it seems the compiler is not choosing the appropriate type for the overload of `Array.prototype.reduce`, producing the error:

```
Type 'Element' is not assignable to type 'number'.
  Type 'Obj' is not assignable to type 'number'.ts(2322)
```

The offending code is:

```typescript
export type Element = number | Obj;

export interface Obj {
  components: Element[];
}

export const test = (net: Element): number => {
  if (typeof net === 'number') {
    return net;
  }

  const reducer = (acc: number, n: Element): number => acc + test(n);
  return net.components.reduce(reducer, 0);
};

console.log(test({ components: [1, { components: [2] }] }));
```

I'm pretty sure the code is correct, because by replacing `net.components.reduce(reducer, 0)` with `(net.components as any[]).reduce(reducer, 0)` to get it to compile, the predicted result (3) is logged to the console.

**Comment by MartinJohns** [comment]
You forgot to fill out the [issue template for bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/Bug_report.md).

It works fine in TypeScript 4.5.4: [Playground link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAsiCiAbCBbCA7YUC8V0FcUAjCAJygB8oB5IgKwG4BYAKFYEtMyAzAQwGNotOlADerKFH4B7FGGnoMwAM4AuWAmRpMAbQC6zFgF9WrGemVZgESzigAKRcHVwkqJQEp1BYmRwA+MQkodm4HUEhpMKccbFwAch8SUniPIJZJSVIIYHxSdDwcw0kTNgypBVtsgBN8QXJcewF+b0JkgBo8F013TC88Nr9sQOaoAGooa0tHD2KobNz8wuAAOhk5BSVlFZq6iHtd+s6ABlnWI0MzSulkFcRpAHN7KeB7UQqNxUw1KB0ARk673W8i+KnUOgATHooEZoUYPGcykA) (I had to rename `Element` to `MyElement`, because `Element` is provided by the DOM lib which is referenced in the playground.)

**Comment by djfm** [comment]
Ah, sorry about that!

Well since the issue is fixed can we just close it? I'll do better next time.
