### ISSUE TITLE
tsconfig.paths not working with ES modules

### ISSUE THREAD

**Issue by eng-dibo** [microsoft/TypeScript#47453]
I switched my project to enable ES modules

- added `type: module` in package.json
- changed `module: commonjs` to `esnext`

it works fine, except when starting using paths aliases.

so, ` import test from './file';` works, but  `import test from '@app/file';` doesn't

[minimal reproduction](https://stackblitz.com/edit/node-wlm8vs?file=index.ts)
run `npm run tsc`

**Comment by MartinJohns** [comment]
You forgot to fill out the issue template for bug reports. Also, I don't see any TypeScript error in your example.

**Comment by fatcerberus** [comment]
You shouldn't be using `paths` unless your runtime and/or bundler directly directly understands `@app/file` as a valid import.  It's not a path-rewriting mechanism.

---

To the TypeScript maintainers:

The website currently has this paragraph at https://www.typescriptlang.org/tsconfig:
> In this case, you can tell the TypeScript file resolver to support a number of custom prefixes to find code. **This pattern can be used to avoid long relative paths within your codebase.**

This is potentially very misleading because `paths` can't be used "to avoid long relative paths" without runtime support.

**Comment by eng-dibo** [comment]
I don't look for a runtime resolvin for aliases, I only talk about finding those paths while compiling

**Comment by MartinJohns** [comment]
The command you're running is `tsc index.ts`. As the documentation mentions, when you provide a list of files you're not using the project configuration (tsconfig.json) anymore.

**Comment by eng-dibo** [comment]
closed as the issue confirmed to be with `tsconfig-paths`
