### ISSUE TITLE
handbook: incorrect recipe for "function with parameters"

### ISSUE THREAD

**Issue by wardbell** [Microsoft/TypeScript#4751]
As I write, the handbook says that the following usage:
```
zooKeeper.workSchedule = "morning";
zooKeeper(giraffeCage);
```
should have the following TypeScript declaration
```
// Note: Function must precede module
function zooKeeper(cage: AnimalCage);
module zooKeeper {
    var workSchedule: string;
}
```

That doesn't work AFAIK.  I believe the recommendation should be:
```
interface zooKeeper {
  (cage:AnimalCage) : void;
  workSchedule: string;
}
```

**Comment by weswigham** [comment]
Functions and namespaces do merge - [`node.d.ts` in DT](https://github.com/borisyankov/DefinitelyTyped/blob/master/node/node.d.ts#L1779) uses that feature to define its "assert" module export.

It does usually feel cleaner to just use a single interface for that kind of thing - however, if you need to be able to nest types, the namespace is your only option (since you can't export types inside an interface).

**Comment by DanielRosenwasser** [comment]
What @weswigham said. Also, a more up-to-date version of the handbook can be found on https://github.com/Microsoft/TypeScript-Handbook and issues about it can be filed there in the future.
