### ISSUE TITLE
Omitting tracing spans for bindSourceFile?

### ISSUE THREAD

**Issue by dgieselaar** [microsoft/TypeScript#47565]
In https://github.com/elastic/kibana, we have a lot of projects that have 1000s of files. When tracing is enabled (for the language server), it seems there is significant overhead from creating `bindSourceFile` spans, which makes it harder to isolate measurements of performance improvements/regressions. I was wondering if these should be turned off, but I'm not sure what the value is of the invididual spans (compared to creating one `bindSourceFiles` span).

**Comment by RyanCavanaugh** [comment]
@amcasey ?

**Comment by amcasey** [comment]
@dgieselaar Can you tell me more about the problems you're seeing?  Significant slowdowns during tracing are expected and my thinking was that they were fine as long as they were proportional (i.e. making everything twice as slow won't hide hot spots).

Are you investigating a perf issue in the binder or just trying to shorten your feedback loop by cutting out the uninteresting measurements?  If the latter, I have no particular objection to dropping those events, since I've never seen them produce anything useful, but I'd also be pretty surprised to learn that they're causing problems.

I imagine this is obvious, but if you're measuring the impact of your speculative performance changes, you should be doing so with tracing disabled because the tracing execution time is not a good proxy for the actual execution time.

**Comment by dgieselaar** [comment]
Yeah, I'm using tracing to find hotspots, not measure execution time (I assume I can still count on relative execution time to help me identify those). Fwict the sheer number of bindSourceFile spans leads to a situation where binding of files seemingly take up more time (relatively) than eg expression checks. It was mostly a source of confusion for me.

**Comment by amcasey** [comment]
@dgieselaar Do you have a repro you can share?  I've never seen anything like that.  In particular, there are also per-file tracing costs for parsing, checking, and emit, so it's not obvious to me how binding could stand out.

**Comment by dgieselaar** [comment]
@amcasey elastic/kibana. I might be missing what you mean though, because this seems like a rather obvious issue. Fwict the language server is re-binding 1000s of files on every request from vscode.

**Comment by amcasey** [comment]
Sorry, I missed that you were talking about the language server.  Yeah, we definitely have enough information to detect that it's LS tracing and drop those events.  Could you tell me more about which file you're editing during your tests so I can confirm the change has the desired effect?

**Comment by dgieselaar** [comment]
@amcasey I think mostly any file in x-pack/plugins/apm will do (on my mobile now, so that's about as specific I can get)

**Comment by amcasey** [comment]
Thanks!  I'll have a look and let you know if it's not straightforward.

**Comment by amcasey** [comment]
@dgieselaar It turns out that we _call_ `bindSourceFile` on every file but most of them reuse a previous result.  We can have the best of both worlds by just moving the tracepoint down a level to where the actual binding occurs.

**Comment by dgieselaar** [comment]
Thanks, even better!

Op di 25 jan. 2022 22:25 schreef Andrew Casey ***@***.***>:
