### ISSUE TITLE
Require implements keyword to correctly use inheritance

### ISSUE THREAD

**Issue by jeserkin** [Microsoft/TypeScript#4768]
I've looked through examples provided in tutorial on `TypeSscript` resource and noticed one, that struck me as odd. This one http://www.typescriptlang.org/Playground/#tut=ex5.

Now I worked with `Java`, `PHP`, `C/++` and `JavaScript`. As I understand `TypeScript` introduces types and OOP standards into JavaScript until ES6 implementation is under development in various browsers.

Regarding languages named above, for code in example to work as far as I know `class` must implement `interface` for function to accept instance of this `class`.

I've tried to use `class Student implements Person` and TS allows it, but I find it as odd, that it is so flexible, that it is **allowed and not required**.

Are there configurations, that allow to use more strict mode?
Will it be changed in later versions?

**Comment by kitsonk** [comment]
Lots of languages don't require explicit interfaces, when the interface can be inferred. TypeScript is such a language.

An interface is a type structure without any implementation.  A class, includes implementation of type, but can be constrained at design time by an interface (or interfaces).  The TypeScript class mirrors the ES6 class but with additional typing information and TypeScript.

You cannot force classes to require implementation of an interface.  It is unlikely to be changed in later versions as it would be a significant breaking change without any benefit.

**Comment by danquirk** [comment]
Because TypeScript uses a structural type system (as opposed to a nominal one like you are used to in Java/C++) it supports assignments like this as long as the types are structurally compatible, whether or not a specific name or constraint was declared ahead of time to match. The ```implements``` keyword is essentially you telling the compiler to ensure that the declared type is always fulfilling the constraints required by that interface.

A primary motivation for this sort of flexibility is to allow this (which is legal/common JavaScript):

```ts
function printName(person) {
    console.log(person.firstName + ' ' + person.lastName);
}

var me = { firstname: "dan", lastname: "quirk" };
printName(me);
```

I should be able to add a type annotation to ```printName``` (: Person) and continue to use objects like this without having to declare a class/interface up front and an explicit ```implements``` statement.
