### ISSUE TITLE
Computed property doesn't work with partial generic parameter

### ISSUE THREAD

**Issue by Janpot** [microsoft/TypeScript#47703]
# Bug Report

### 🔎 Search Terms

"computed property"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "computed"

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.4&ssl=7&ssc=1&pln=1&pc=1#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVNQEYAeAFQD4AKKALnlIBp4AjOgBVmygjPIEo6pALAAoUSnTY88DCADOGEo3gBpeCAAes1MDnwA1iACeORPSo5mAK0FMADjBx26KpgDduggNoqAun3gAb1F4eAB6MPgAQRgAc2QAWxBUDHhTGSM7BAByQPgvDToFGCxUWN9vPwBueABfbPgsPVQcVKg5OSxY1ChmCAQMHHg7WCgk2Rg0swxMnI4YLh4KbIA6EPg4DGQYfEQiSksrJjyvBycK+A8IOr4q0VrRIA)

### 💻 Code

```ts
declare function fn1<T>(a: T, b: Partial<T>): T

function test1<T, K extends keyof T>(obj: T, prop: K, val: T[K]) {
  // Argument of type '{ [x: string]: T[K]; }' is not assignable to parameter of type 'Partial<T>'.
  return fn1(obj, { [prop]: val });
}
```

### 🙁 Actual behavior

```
// Argument of type '{ [x: string]: T[K]; }' is not assignable to parameter of type 'Partial<T>'.
```
And no way to make it see that variable as a `Partial<T>`

### 🙂 Expected behavior

The following works:

```ts
function test<T, K extends keyof T>(obj: T, prop: K, val: T[K]) {
  const test: Partial<T> = {};
  test[prop] = val;
  return fn1(obj, test);
}
```

**Comment by RyanCavanaugh** [comment]
The crux of this is what type to give the expression `{ [prop]: val }`

It *seems* like it's a `Record<K, T[K]>`, but it's not, since an instantiation of `test1<{x: number, y: number}, "x" | "y">` would imply that `{ [prop]: val }` is `{ x: number, y: number }` and that's not true.

The closest representation for that expression in the type system we have is `{ [x: string]: T[K] }`, which isn't a sufficient match to `Partial<T>`.

**Comment by osdiab** [comment]
But in that case, although I understand that it can't safely be called a `Record<K, T[K]>`, could it safely be called a `Partial<Record<K, T[K]>>`, as `fn1` requests? I don't fully understand why despite the fact that `key` in this case is typed as `K`, making an object with it as the key doesn't type it at least as `K` rather than `string`.
