### ISSUE TITLE
Import for `IDisposable` is no longer suggested

### ISSUE THREAD

**Issue by bpasero** [microsoft/TypeScript#47779]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.6.0-dev.20220206

**Search Terms**
- auto import 
- suggest / suggestions
- completions

**Repro**
1. In the VS Code codebase
2. Open a file such as [codeActionContributions.ts](https://github.com/microsoft/vscode/blob/1498d0f34053f854e75e1364adaca6f99e43de08/src/vs/editor/contrib/codeAction/browser/codeActionContributions.ts#L20)
3. Try triggering suggestions for `IDisposable`

---

I am not sure if this is an issue with the UI or a TS issue, I no longer see `IDisposable` being suggested in the suggest widget, only in the quick fix:

![Recording 2022-02-06 at 07 22 33](https://user-images.githubusercontent.com/900690/152670013-0da70d3b-8034-4b83-9c83-7743746047d8.gif)

**Comment by mjbvz** [comment]
Actually that may be unrelated. I suspect that the root cause is that `IDisposable` happens to be re-exported from another file even through it is primarily consumed through the original file: 

https://github.com/microsoft/vscode/blob/84163149f3aa4f57b4407199cae52af18f0d8269/src/vs/workbench/workbench.web.main.ts#L196

**Comment by andrewbranch** [comment]
@mjbvz is correct—we only offer one auto import per "target symbol" in completion lists to avoid massively cluttering the list when you have a series of barrels. The one we chose was chosen because it has fewer slashes than the other. I don’t think we’re looking to change this behavior in general at the moment (there is an open suggestion for it somewhere I think), but in the particular example you provided, there was already an existing import from `vs/base/common/lifecycle`, which should make it the top priority import. (In fact, when you trigger the code fix menu, you see we _don’t_ offer to import it from `vs/workbench/workbench.web.main` because we understand updating an existing import to be far superior to adding a new one.) I’ll double check that it’s not a big perf cost to do the same thing in completions, but I think that should be doable.
