### ISSUE TITLE
Support some assignments to guarded variable in type guards

### ISSUE THREAD

**Issue by crobi** [Microsoft/TypeScript#4778]
The following does not compile (tested with 1.6 compiler and playground):

``` typescript
function foo(s: {}): string {
    if (typeof s === "string") {
        s = s; // This line confuses the compiler. Same with s="abc";
        return s.substring(0,1); // Property 'substring' does not exist on type '{}'
    } else {
        return "";
    }
}
```

Commenting out `s = s;` solves the problem. It looks like an explicit assignment makes the compiler forget that the type of `s` is a string (which it inferred before from the typeof check).

**Comment by danquirk** [comment]
This is by design at the moment. The language spec has a bunch of verbiage around this restriction (no assignments to the guarded variable) in section 4.24:

_In the true branch statement of an 'if' statement, the type of a variable or parameter is narrowed by a type guard in the 'if' condition when true, provided no part of the 'if' statement contains assignments to the variable or parameter._

The basic idea is for the compiler to only narrow when it knows for sure the narrowing is safe.

That said, we could certainly investigate widening what is supported in cases like this (and the restriction is not exactly intuitive, especially in cases like this). Certainly it's reasonable to ask whether assignment to the guarded variable should really turn off the guard if we statically know the source and target type are identical.

**Comment by mhegazy** [comment]
See https://github.com/Microsoft/TypeScript/issues/9998 for more details.
