### ISSUE TITLE
How to import asset function in typescript ?

### ISSUE THREAD

**Issue by mjmanav4** [microsoft/TypeScript#47812]
I have trying to use assertNonNull check in my typescript code, but the fxn is not found
can you please specify which lib to import

<img width="523" alt="Screenshot 2022-02-09 at 5 12 17 PM" src="https://user-images.githubusercontent.com/9611624/153193367-506cacd9-d753-4f8d-91f2-fb40b6c9de50.png">

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
