### ISSUE TITLE
Prevent calls to Array.prototype.sort() on arrays containing symbols

### ISSUE THREAD

**Issue by mmiller42** [microsoft/TypeScript#47840]
# lib Update Request

## Configuration Check

My compilation *target* is `ES2015` and my *lib* is `the default`.

## Missing / Incorrect Definition

The otherwise innocuous `Array.prototype.sort()` function unfortunately throws a `TypeError` with its default implementation of `compareFn` if the array contains at least one symbol.

This is because the default comparison function coerces elements to strings before comparing them, and coercing a Symbol to a string throws a TypeError: `Cannot convert a Symbol value to a string`.

It might be nice to be able to type-guard arrays and help developers discover this error at compile-time?

```typescript
interface Array<T> {
  sort(): Extract<T, symbol> extends never ? this : never;
  sort(compareFn: (a: T, b: T) => number): this;
}
```

## Sample Code

```typescript
const array = [1, 2, "foo", "bar", Symbol()] as const;
array.sort(); // ❌ Runtime TypeError
```

## Documentation Link

* [Array.prototype.sort() compareFn on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#comparefn)
* [Symbol type conversions on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol#symbol_type_conversions)
* [Spec: Array.prototype.sort(comparefn)](https://tc39.es/ecma262/#sec-array.prototype.sort)
  * > [Spec: ToString(argument)](https://tc39.es/ecma262/#sec-tostring)

**Comment by fatcerberus** [comment]
> `sort(): Extract<T, symbol> extends never ? this : never;`

I'm not sure how this would help.  `never` can be assigned to any other type, so it wouldn't produce a compile-time error regardless of what you do with it.

**Comment by jcalz** [comment]
<sup>:eyes: <i>Psst, your sample `array` is a `readonly` tuple and therefore `sort()` is already disallowed by TS; you might want to remove `as const`</i>:eyes:</sup>

I doubt this the kind of problem that happens often enough to be worth complicating the `sort()` call signature for everyone.  Unfortunately since you're trying to prohibit calls that currently succeed, I don't think you can use declaration merging to get the desired behavior in your own code.  You'd have to use a modified copy of the library instead.  Still, my suggestion for a call signature that works the way you want would be something like:

```ts
interface Array<T> {
  sort(...args: symbol extends T ?
    [compareFn: (a: T, b: T) => number] :
    [compareFn?: (a: T, b: T) => number]
  ): this;
}

const noSymbols = [1, 2, "foo", "bar"];
noSymbols.sort((a, b) => 0) // okay
noSymbols.sort(); // okay

const someSymbols = [1, 2, "foo", "bar", Symbol()];
someSymbols.sort((a, b) => 0) // okay
someSymbols.sort(); // error, expected 1 argument but got 0

```
[Playground link](https://www.typescriptlang.org/play?ts=4.5.4#code/JYOwLgpgTgZghgYwgAgIJSnAngHgCoB8yA3gFDLIC2WAygPZRgAUAdG3FAOYDOAXMtyyUARnQA2yCAA9IIACbdkeZAH5yFZAG0EdSgAcOEAGIh+TOPzwAaZMMsBKZAF4iIAK4joAXWS91FbV0DKGMQFTMLJRs7JUcXZHdPKC91e34wAAtgbgBuUgBfUlIdEG4wBLoaIVExRSctAEYbACYbACIYOjo29uEONq88kErq8W4WanpGJnNouKIABkcAemXkOgBrbFJhqpExidoGZnsc5FX1rawikrKBXQg9mrrGlvbO7t7+myfxJntBqRuA9frVDlNmLNbPNkEtzmtNttgZRHqMwZNjv8zhdoFAGDZpHoIAhIHJkA1kBxOB4IOBbG5ypw6OUFkU2UA)

**Comment by RyanCavanaugh** [comment]
The amount of complexity we'd have to add just to catch this one case is much too high IMO. Sorting *anything* but a `string[]` without a comparator function is super fraught already and really the only thing (if anything) we should do with `sort` is ban that entirely.
