### ISSUE TITLE
How to use React mixins in TypeScript 1.6?

### ISSUE THREAD

**Issue by pdeva** [Microsoft/TypeScript#4784]
There is no examples for this either.
Some sample code would be very helpful for people using React with TypeScript 1.6.

**Comment by mhegazy** [comment]
//CC: @RyanCavanaugh

**Comment by weswigham** [comment]
Well, going forward, from [the react docs](https://facebook.github.io/react/docs/reusable-components.html) on ES6 classes:

>No Mixins
Unfortunately ES6 launched without any mixin support. Therefore, there is no support for mixins when you use React with ES6 classes. Instead, we're working on making it easier to support such use cases without resorting to mixins.

While that's not an _entirely_ true statement (you _can_ use a kind of mixins with ES6 classes), the way forward for React users seems to be to just not use mixins at all. Instead, they recommend composing components.

As far as when using the `React.createClass` old-style form, the class specification object it takes can have a `mixins` key whose value is an array of mixin objects to use as mixins... but the `.d.ts` for that might be [wrong](https://github.com/borisyankov/DefinitelyTyped/blob/master/react/react.d.ts#L202) over on DT, because that doesn't look like an array in the definition to me.

**Comment by jbrantly** [comment]
@weswigham I think you're right about the .d.ts being wrong. Not sure when that happened :frowning: 

Also /agree with everything else @weswigham said. My advice is to just avoid mixins entirely.
