### ISSUE TITLE
#47069 breaks narrowing in @types/has and @types/lodash

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#47940]
```ts
declare function hasOwnProperty<P extends PropertyKey>(target: {}, property: P): target is { [K in P]: unknown };
declare const arrayLikeOrIterable: ArrayLike<any> | Iterable<any>;
if (hasOwnProperty(arrayLikeOrIterable, 'length')) {
    arrayLikeOrIterable; // $ExpectType ArrayLike<any>
}
```

Expected: arrayLikeOrIterable narrows to `ArrayLike<any>`
Actual: It doesn't, so instead the compiler intersects the declared type with `{ length: unknown }`.

Broken by #47069

**Comment by sandersn** [comment]
Also breaks lodash like so:

```ts
interface LoDashStatic {
  isArrayLike<T extends { __lodashAnyHack: any }>(t: T): boolean;
  isArrayLike(value: ((...args: any[]) => any) | null | undefined): value is never;
  isArrayLike(value: any): value is { length: number };
}
declare var _: LoDashStatic

declare const anything: any;
const value: string | string[] | { [index: number]: boolean, length: number } | [number, boolean]
  | number | { length: string } | { a: string } | null | undefined
  = anything;

if (_.isArrayLike(value)) {
  const result: string | string[] | { [index: number]: boolean, length: number } | [number, boolean] = value;
} else {
  const result: number | { length: string } | { a: string; } | null | undefined = value;
}
```

**Comment by weswigham** [comment]
Relying on subtyping with `readonly` properties in the wrong direction? :(

How about if you slap a `readonly` in that mapped type in the OP?

Only "fix" I can think of would be swapping user-defined-typeguard narrowing to use not-subtype because subtype reduction demands ordering between two non-identical types. I wouldn't be happy about it though - if we did it, I think it should only be behind a compat flag, since, while it just didn't matter before, these kinds of guards really should be looking for read-only props if they expect to match them (which becomes extra important with how we have distinct setter types now, too).

**Comment by jakebailey** [comment]
This seems to be blocking changes to the affected libs; DT runs 4.7 in CI so PRs that modify these stubs fail, e.g. https://github.com/microsoft/TypeScript/issues/47940 which is to revert a bad change in lodash.
