### ISSUE TITLE
Typescript asynchronous decorators decorate synchronous methods

### ISSUE THREAD

**Issue by GO-DIE** [microsoft/TypeScript#48022]
**How to correctly identify synchronous methods that have been modified to be asynchronous when using asynchronous decorators to decorate synchronous methods.**

### 💻 Code

```ts
function AsyncDecorator() {
  return (target: any, propertyKey: string, descriptor: PropertyDescriptor) => {
    const originalMethod = descriptor.value;
    descriptor.value = async function (...args: any[]) {
      await sleep(100);
      const result = await originalMethod.apply(this, args);
      return result;
    };
    return descriptor;
  };
}

async function sleep(ms: number) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

class Test {
  // This function appears to be a synchronous function, but has been changed to an asynchronous function by an asynchronous decorator, but I didn't know that
  @AsyncDecorator()
  fun(): string {
    return 'Hello World!';
  }
}

const result = new Test().fun();
console.log(result); // Expect results: Hello World!  Actual result: Promise {<pending>}
```

### 🙁 Actual behavior
Promise {\<pending\>}

### 🙂 Expected behavior
Hello World!

**Comment by MartinJohns** [comment]
You need #4881, which is not supported (and likely won't be for quite a while, **at least** until the decorator proposal is finally finished).

**Comment by jcalz** [comment]
Is this a bug report or a question? If it's a bug report you didn't fill out the full template; could you go back and do that?. If it's a question, then it doesn't belong here; maybe [Stack Overflow](https://stackoverflow.com/q/71248888/2887218) is a better place, oh wait, you already opened a question there.  😃

 In any case I'm not sure why your expected behavior is "Hello World!" given that you are logging a promise to the console, seemingly intentionally.  I think your real expected behavior is that `new Test().fun()` should be seen as a `Promise<string>` instead of as a `string` and that the compiler should complain if you write, say, `new Test().fun().toUppercase()` instead of `new Test().fun().then(x => x.toUpperCase())`.
