### ISSUE TITLE
Cannot read property 'get' of undefined – file.pragmas.get("jsximportsource") in getJSXImplicitImportBase

### ISSUE THREAD

**Issue by jaredh159** [microsoft/TypeScript#48039]
[This issue](https://github.com/microsoft/TypeScript/issues/43373)  was reported a while back, if I could re-open that issue, I would. The bug was accepted and assigned and put on a milestone, but eventually given up on because no one could provide a consistent reproduction:

https://github.com/microsoft/TypeScript/issues/43373

I'm opening this because **I have a consistent set of steps to reproduce the bug,** and I'm hoping someone can look into it.

In the original issue, the OP described the project being in a monorepo, and another commenter described having the same problem in a repo that relied upon another repo importing react components (I think). I mention that because the setup shown below is similar.  It's not a monorepo, but the issue occurs in a repo that relies upon importing components from elsewhere in the filesystem using `compilerOptions.paths` in the `tsconfig.json`, like this:

```json
{
  "compilerOptions": {
    "paths": {
      "@evans/*": ["../evans/src/components/*"]
    }
  }
}
```

And then in the repo components are imported like this:

```tsx
import CartComponent from '@evans/cart';
```

Here are the exact steps you can run to create the issue:

```bash
# set up supporting repo
git clone git@github.com:friends-library-dev/evans.git
cd evans
git fetch
git checkout graphql-refactor
git reset --hard f3879ecd
npm install

# set up main (erroring) repo
cd ../  # 👋  important! the repos must be side-by-side
git clone git@github.com:friends-library-dev/storybook-web.git
cd storybook-web
git reset --hard e8232dd
npm install

# produce the error
node --trace-deprecation --trace-warnings --unhandled-rejections=strict node_modules/.bin/build-storybook
```

Thanks so much for looking into this!

**Comment by RyanCavanaugh** [comment]
Have you reproed this running `tsc` ?

There's so much going on with this repro I would want to set it up in a VM. If you have something that is just clone + run `tsc` we can investigate sooner; repros like this tend to eventually end up in an external component.

**Comment by jaredh159** [comment]
i don't have a simple way to repro with just `tsc`, sorry. i was hopeful, based on the other issue, that just having a reliable repro would be enough for someone to go on.  i don't think you'd really need a VM, it's just two npm packages cloned side-by side (unless i'm not understanding).

**Comment by RyanCavanaugh** [comment]
The issue here is how the ts-loader API is using the compiler API. The incoming call stack is this:
```js
function getEmitOutput(instance, filePath) {
    if (fileExtensionIs(filePath, instance.compiler.Extension.Dts)) {
        return [];
    }
    if (utils_1.isReferencedFile(instance, filePath)) {
        return instance.solutionBuilderHost.getOutputFilesFromReferencedProjectInput(filePath);
    }
    const program = utils_1.ensureProgram(instance);
    if (program !== undefined) {
        const sourceFile = program.getSourceFile(filePath);
        const outputFiles = [];
        const writeFile = (fileName, text, writeByteOrderMark) => outputFiles.push({ name: fileName, writeByteOrderMark, text });
        const outputFilesFromWatch = getEmitFromWatchHost(instance, filePath);
        if (outputFilesFromWatch) {
            return outputFilesFromWatch;
        }
        //       vvv here
        program.emit(sourceFile, writeFile, 
        /*cancellationToken*/ undefined, 
        /*emitOnlyDtsFiles*/ false, instance.transformers);
        return outputFiles;
```
Here, `sourceFile` is:
```
sourceFile: SourceFileObject
fileName: "D:\\Throwaway\\fld\\evans\\node_modules\\@friends-library\\cover-component\\src\\css\\helpers.ts"
originalFileName: "D:\\Throwaway\\fld\\evans\\node_modules\\@friends-library\\cover-component\\src\\css\\helpers.ts"
path: "d:/throwaway/fld/evans/node_modules/@friends-library/cover-component/src/css/helpers.ts"
redirectInfo: {redirectTarget: SourceFileObject, unredirected: SourceFileObject}
resolvedPath: "d:/throwaway/fld/evans/node_modules/@friends-library/cover-component/src/css/helpers.ts"
```
Note: no `pragmas` set here.

When calling `const sourceFile = program.getSourceFile(filePath);`, TS may return a source file with a `.redirectInfo`, in which case this caller needs to operate on `sourceFile.redirectInfo.redirectTarget`.

**Comment by RyanCavanaugh** [comment]
cc @johnnyreilly

**Comment by johnnyreilly** [comment]
Thanks @RyanCavanaugh. @jaredh159 if you'd like to experiment with a fix to `ts-loader` to resolve your issue, I'll happily take a look at a PR.

Based upon @RyanCavanaugh's comments, the tweaks would be here: https://github.com/TypeStrong/ts-loader/blob/dcec071c110bff12d9d510a35869395862e4a6eb/src/instances.ts#L794

**Comment by jaredh159** [comment]
@RyanCavanaugh thanks a ton for isolating the problem.  Yup, happy to tackle a PR for ts-loader, already started digging in.  Question though: the `SourceFile.redirectInfo` and `RedirectInfo` are both marked as `@internal` types, so it's not really visible to a consuming library like ts-loader. Any tips on this? Do i just need to do some casting to `any`?  If libraries like `ts-loader` should be handling these edge cases, why are these types internal?

**Comment by RyanCavanaugh** [comment]
I think I might have misdiagnosed this. Based on reading the code, the source file we hand back is supposed to be a prototypal descendant of the original source file, so everything should have "just worked". Looking more...

**Comment by RyanCavanaugh** [comment]
I can reproduce the essence of the crash now.

tsconfig.json
```
{
  "compilerOptions": {
    "target": "es2019",
    "module": "commonjs",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "outDir": "out",
    "skipLibCheck": true,
  },
  "include": [
    "copy1/node_modules/target/*",
    "copy2/node_modules/target/*",
  ]
}
```

copy1 and copy2 are both folders with
```
node_modules/
  target/
    index.ts
    import.ts
    package.json
```
where index.ts is
```ts
export const a = 1;
```
import.ts is
```ts
import {} from "./";
```
and package.json is
```json
{
    "name": "target",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
    },
    "keywords": [],
    "author": "",
    "license": "ISC",
    "dependencies": {  }
}
```
This gives a call stack with the same root cause
```
> tsc
D:\throwaway\fld\storybook-web\node_modules\typescript\lib\tsc.js:94453
                throw e;
                ^

TypeError: Cannot read properties of undefined (reading 'length')
    at computeLineStarts (D:\throwaway\fld\storybook-web\node_modules\typescript\lib\tsc.js:7033:27)
    at Object.getLineStarts (D:\throwaway\fld\storybook-web\node_modules\typescript\lib\tsc.js:7086:60)
    at getCurrentLineMap (D:\throwaway\fld\storybook-web\node_modules\typescript\lib\tsc.js:88792:59)
    at emitDetachedCommentsAndUpdateCommentsInfo (D:\throwaway\fld\storybook-web\node_modules\typescript\lib\tsc.js:92388:94)
    at emitBodyWithDetachedComments (D:\throwaway\fld\storybook-web\node_modules\typescript\lib\tsc.js:92225:17)
    at emitSourceFile (D:\throwaway\fld\storybook-web\node_modules\typescript\lib\tsc.js:91054:21)
    at pipelineEmitWithHintWorker (D:\throwaway\fld\storybook-web\node_modules\typescript\lib\tsc.js:88895:24)
    at pipelineEmitWithHint (D:\throwaway\fld\storybook-web\node_modules\typescript\lib\tsc.js:88881:17)
    at noEmitNotification (D:\throwaway\fld\storybook-web\node_modules\typescript\lib\tsc.js:87525:9)
    at onEmitNode (D:\throwaway\fld\storybook-web\node_modules\typescript\lib\tsc.js:76504:13)
```

[crashsample.zip](https://github.com/microsoft/TypeScript/files/8165258/crashsample.zip)

The root cause is a redirect from one `.ts` file to another - I think this should probably just not ever happen.

**Comment by RyanCavanaugh** [comment]
Possible related issues/PRs #44554, #41717, #44024

**Comment by jaredh159** [comment]
@RyanCavanaugh thanks for continuing to work on this.  Just to be clear, in your minimal repro, are you saying there is some kind of cyclical import between adjacent directories?  If so, I'm pretty sure in my (not minimal) repro there is no cyclical import.  The `storybook-web` dir imports from `evans`, but never the other way around.  Not sure if that's relevant info, but thought I'd mention it.

**Comment by RyanCavanaugh** [comment]
No, it's not a circularity issue.

The problem is that we have logic that says if you import multiple copies of "the same" module, we can save a bunch of work by only processing one of them. "the same" is defined by package name + version (as defined in its `package.json`). This saves a huge amount of time because it's somewhat common to have multiple copies of various subdependencies with a common version (e.g. large projects with many indirect dependencies on both v7 and v8 of a popular utilities library).

Under common conditions, the only way to get multiple copies of "the same" module is when a package manager lays out transitive dependencies under subfolders, as was common in earlier versions of npm and is now common in package managers which are enforcing stricter layouts. And under common conditions, it's impossible to have two *top-level* (i.e. direct dep) packages with the same name and version, since all top-level packages live in the same `node_modules` directory.

And if a dependency is indirect, it's basically guaranteed to be "someone else's" package, which means you're consuming its `.d.ts` rather than its `.ts`.

The "process only one of them" logic works by creating a "redirect" Source File object in place of the one we would have otherwise parsed+loaded. This redirect file isn't suitable for emit for a variety of reasons, but under common conditions, we wouldn't be doing any emit because it's a `.d.ts` file.

This repro violates some of the key "common" conditions that prevented it from being found earlier: This repro has two different modules which we consider "the same", which *aren't* `.d.ts`, coming from two different `node_modules` folders. That's where things went off the rails.

So we either need to include "parent node_module directory name" as part of the "is same" key, or just outright never redirect when the underlying source file is `.ts` instead of `.d.ts`
