### ISSUE TITLE
`slice` return type resolves to wrong type when used on string intersection with union containing array type

### ISSUE THREAD

**Issue by FatalMerlin** [microsoft/TypeScript#48054]
# Bug Report

### 🔎 Search Terms

union intersection type slice 

### 🕗 Version & Regression Information

4.5.4, nightly (v4.7.0-dev.20220215)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220215#code/C4TwDgpgBAQg9iAkgdQJYGcAWK4FcA2AJgEoTpz4BuEAKnAMrABOqAdgOZQC8UAFOszacAPlFLsAogA8wAWQCGwAMaYAgkybyQUUblaEIAMzYRCASigAyKAJYcA3AChH+CMCjAywAIwAuWAgoGNjIeESk5FS0DIIc3FAARIhQSvKsUABG0PI2sewJTq7ungIATP7wSGhYOAQkZBTUdIx2nDwA2gDkyamsrHDuWVBpwxpanQC6hW4eXgDMFYHVIWH1kU0xrfElPgB0ALaKKrwA9D1p-YPZYhCSMgrKamPaEKjAmBBMJ2YAhE6Ohj0SmAqDg6R2ADFWLwwPJNPtFlVgrVwg0os08hYAN6OKB4qBFKCoeiYVYwCCqFpCGC4YCIVT7VQAVVYoNYAHlDFSOKp9Nz2OpNNoeLD4bt0PhUEoILwAAwAGm8Zn++KJ7NY+BAqiU0rAwH56F4xNJdXJlLyNLpDOZrLBnP5vMIDueyscAF9nIDWMC2WqNVqdRA9QaYXD5Ajcq1sR6gA)

### 💻 Code

```ts
type BoyIWishIWouldResolveToString = (string | RegExpMatchArray | undefined) & string;

let test1: BoyIWishIWouldResolveToString = "I can be a string";
let test2: BoyIWishIWouldResolveToString = ['I cannot be an array']; // error here (correct)
let test3: BoyIWishIWouldResolveToString = test1.match(/I cannot be a RegExpMatchArray either/)!; // error here (correct)

function testFn(param: BoyIWishIWouldResolveToString) {
    // type is `string | string[]`
    let iShouldBeAStringButIAmAUnionOfStringAndStringArray = param.slice(0,1);

    // error here (wrong)
    iOnlyAcceptStrings(iShouldBeAStringButIAmAUnionOfStringAndStringArray);
}

function iOnlyAcceptStrings(param: string) {}
```

### 🙁 Actual behavior

`slice` returns a union of `string | string[]`.

### 🙂 Expected behavior

`slice` returns `string` because the underlying intersection type can only resolve to `string`.

**Comment by fatcerberus** [comment]
This happens because TS isn't sure whether you're calling `Array#slice` or `String#slice`.  It's true that `BoyIWishIWouldResolveToString` has no legal inhabitants other than `string`, but TS doesn't know that, it only knows it has something that can either be a `string` or a `RegExpMatchArray & string`.  This pattern of intersecting a primitive type with an object type is often used to create branded primitives, so TS doesn't simplify it out of existence.

**Comment by fatcerberus** [comment]
To be clear on why `RegExpMatchArray & string` is considered a possibility here: Intersections distributes over unions, so:

```ts
type BoyIWishIWouldResolveToString = (string | RegExpMatchArray | undefined) & string;

// is equivalent to

type BoyIWishIWouldResolveToString = (string & string) | (RegExpMatchArray & string) | (undefined & string);
```

The first is just `string` and the third reduces to `never` (thus being simplified away), but the compiler considers the middle one to be inhabited for the reasons mentioned above.

**Comment by FatalMerlin** [comment]
@fatcerberus why does typescript not know this? What would be the correct way to limit the union type to string?

**Comment by fatcerberus** [comment]
@FatalMerlin There's no *technical* reason why TS couldn't figure out that `string & RegExpMatchArray` is uninhabited, but people often write things like `string & { foo: never }` to create branded types and then manually cast values to them, to enforce validation, e.g.  If such types eagerly collapsed to `never`, that wouldn't work.  Unfortunately `RegExpMatchArray` is just another object type from this perspective, thus you hit this issue.  The underlying behavior is by design so there's really no way around it other than "avoid intersecting primitives with object types"

**Comment by FatalMerlin** [comment]
@fatcerberus are you saying that typescript was designed in a way that prevents it from narrowing unions of primitive and object types back down to primitive types contained in the union?

**Comment by fatcerberus** [comment]
This has nothing to do with narrowing of unions.  What I'm saying is that if you have a type `string & SomeObjectType`, TS treats that as a distinct type from `string`.  You're expecting it to *automatically* simplify to `string` because `string & RegExpMatchArray` is an impossible type, but it doesn't because you might have good reason to construct such a type.

**Comment by tjjfvi** [comment]
The essential part here is that `{ a: number }` is not a type restricted to objects. For example, `number` is a valid `{ toFixed(digits?: number): string }`. So, `string & { a: number }` is, theoretically, possible, even though `string & object` is not. Similarly, `RegExpMatchArray` isn't restricted to just objects, so it can't reduce `string & RegExpMatchArray` to `never`.

Might `Extract<string | RegExpMatchArray | undefined, string>` (which resolves to `string`) be what you're looking for?
