### ISSUE TITLE
typescript@4.5.5,Using generics in closures cannot be checked

### ISSUE THREAD

**Issue by Jack-Zhang-1314** [microsoft/TypeScript#48051]
---
name: Support
---

## Bug Report

* typescript@4.5.5,Using generics in closures cannot be checked

### 🔎 Search Terms

1. Generics
2. Closure

> I didn't find the answer I was looking for

### 🕗 Version & Regression Information

* typescript@4.5.5

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?jsx=0&ts=4.7.0-dev.20220215#code/GYVwdgxgLglg9mABBOBbADnAzgUwBQB0RwYWAXIgGLjTxgDaAugJSIDeAUIojMIniSwEANjjABzKAAtEAXnmIADK07duAJxxQQ6pHgCG68RWqRYCVrIB8iQ+K6IAvg979BIsZJnzZiAIwqDhpaOkiC9IqMDs7B2rqI7poAJiAQ+EH8+gA0iABGllYZ3AA8ACpWhER25IilTMwmNOZI1kVq+ni5lQTVzMxt3A79zhygZnQJMOpYUGUVhupkdSyqiJpxSAsRUSNjtAhrOABuONM4cwbqi8vMq+uhtlcEmidneMMcHCikUIjC+jM5Mg0JhcAIpjMsi9Trh+gB6OGaTDqX76JDgKAAT3QOCSiFO6jg6g4CP+M2KYBAqFypwq9D8WQATFkAMxZAAsWQArCwEQSiZ8EQKEQAZbA4RDSCU4YDAHDQRBwPhYnHIKTygDWMAkiA4ZKgeHoACJ9EamayOdyWEA)

### 💻 Code

```ts
function compose(...fns: Function[]) {
  if (fns.length === 0) {
    return (arg: Function) => arg
  }
  if (fns.length === 1) {
    return fns[0]
  }
  return fns.reduce(
    (a, b) =>
    //Writing a type here won't do any good
      <T>(...args: T[]): Function =>
        a(b(...args))       
  )
}

function first<T>(arr:T[]){
  return arr[0]
}

function reverse<T>(arr:T[]){
  return arr.reverse()
}

const last = compose(first,reverse)
//report an untyped error
//last<number>([1,2,3,4,5])//error

//or
//Lose the effect of type checking 
last(["a",2,3,4,5])
```

### 🙁 Actual behavior

>I hope this can be returned with a closure type checking, however the closure will not accept any return type checking

```ts
//report an untyped error
last<number>([1,2,3,4,5])//error

// So I have to do my best to make sure I pass in the right type
```

* Untyped function calls may not accept type arguments

### 🙂 Expected behavior

> I want the function returned by the closure to have a type checking effect, such as this`last<number>([1,2,3,4,5])`

**Comment by jcalz** [comment]
There is a [template](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/Bug_report.md) you're supposed to fill out when you open a bug report here.  Please edit this issue with the requested information; otherwise there's a good chance this issue will just be closed as unactionable.

**Comment by Jack-Zhang-1314** [comment]
> 当您在此处打开错误报告时，您应该填写一个[模板。](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/Bug_report.md)请使用请求的信息编辑此问题；否则这个问题很有可能会因为无法操作而被关闭。

OK

**Comment by jcalz** [comment]
I don't see a bug here.  

The return type of `compose` is inferred as `Function` because `fns.reduce(cb)` returns `Function` because the element type of `fns` is `Function`.  And [`Function` represents a completely untyped function call](https://www.typescriptlang.org/docs/handbook/2/functions.html#function), so it doesn't know or care about the relationship between input and output at all.  It's usually not recommended to use `Function`.

Even if you used something better than `Function`, the compiler doesn't infer generic call signatures from function implementations.  If you want to represent what a variadic `compose()` function will do in terms of the input/output types of its inputs, you would need to write that type manipulation yourself.  And it would be tricky and run into problems with generic functions.  But all of that is out of scope for this issue as reported.

If there's a bug here I'm not seeing where it's supposed to be.

**Comment by RyanCavanaugh** [comment]
`compose` is a non-generic function, and by definition, non-generic functions' return types don't depend on their input types.
