### ISSUE TITLE
Error when inferring string literal types as index signature

### ISSUE THREAD

**Issue by redplant3d** [microsoft/TypeScript#48056]
# Bug Report

Error when inferring string literal types as index signature

### 🔎 Search Terms

- string literal type
- index signature
- infer string literal type

### 🕗 Version & Regression Information

Tested with 4.5.4 and Nightly (4.7.0)

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.7.0-dev.20220215#code/FAMwrgdgxgLglgewgAhgUwM4wDwBUB8AFAgEYBWAjAFzK4A0ypZATDbgJTIDewyfyAJzQwwAlE2YBuYAF9gwAPQAqFarXqNmrdp269m5EoWL9u5ACEBCANZoU5tAAsAhgDdEogPzIAogA8ABzRYNAATZCgEAFsAuAAbNGQ0ASsBQ1M1Q2NFBVoATyDkFwxkZxQ4uHQBZzjUNBi453RUArRgGFbkAEFkAF5kACVghAFQ7AADABIuCDAokmSZAH0AqwDxhln55PxpSIgsUpoe-p5+ZAAiAFYVtYuaK7pZaXbO8z7B4dHsLAE4CAA5ps5gsBLtgPtDiQqO9Trx+M5QojnABmB5Pc7IpGsZAAdieMheClyADkEL4UiMaP4giFQlQct0BAC5nYYIwQC1CgByczc5BwEoQBDs5wYDBwAEQZwkBKockBZzVKLCZIcrmJbldbkAOkZ3N+-wB-LK4W5UxmIMWtwQ635-1CaD8yAlUqaokwpSEAug0UV8FlaD16CwhGcDBI7CJGRjsbj8Y0WRMCb0vkCwXQ4QcLncCFE6RTMaTjIAys4VaUSl0I2B2XBOQA1GpgNAAWlwnUFyFC9ZAyTZbFaGCgfwC7Md6FgJRIIscSUpAhKkRSGbieQZHUKAGEPkNl2MLVtQctVraNi6YH9AeDIeyoDQd3DztcbQF7pcrhcCUTcl0Sk7aUzdpMBgQgoAjKNGVbfBGS6ZlWQgdkEE5TdNT5AUhRFStXWlQN5WQRVlVVNJkI1ZBuS3XVGXIw1ARNCAzUPK0BBPNZxntBinRdSVpREIQSiVRJ-kiGImjgQM9WJc4Ox5I9kntTDRXFHiZTlGByVQmjLyNXVCGYFEABYrnYIA

### 💻 Code

```ts
// just a generic function which i want to infer its param type. Both params must have the same type
function test<T>(obj1: T, obj2: T) {
return obj2;
}

/**** Broken Behaviour? Expected compile error **** */

// Type has an literal template type
type A = Record<`${number}_prop`, number>;
const a: A = {
"5_prop": 5,
};

type B = Record<string, number>;
const b:B = {
adada3: 5,
adada2: 7,
};

// No Error, despite a/b being different types: Expected:
// Argument of type 'B' is not assignable to parameter of type 'A'.
// 'string' and '`${number}_prop`' index signatures are incompatible.
test(a, b);
test<A>(a, b); // same behaviour

/***** Expected Behaviour **** */

// Same as A, but if Value-Type is different: Typescript detects both errors correctly:
type C = Record<`${number}_prop`, string>;
const c: C = {
"5_prop": "5",
};

// As expected
test(c, b);
// ->
// Argument of type 'B' is not assignable to parameter of type 'C'.
// 'string' and '`${number}_prop`' index signatures are incompatible.
// Type 'number' is not assignable to type 'string'.(2345)
```

### 🙁 Actual behavior

No error, despite Type A and B being different

### 🙂 Expected behavior

First case should raise (2345) with incompatible index signatures

**Comment by jcalz** [comment]
This is working as intended.

Object types in TypeScript are open/extendible not closed/sealed/exact, so you are allowed to add extra properties without violating the type:

```ts
interface Foo {
    x: string;
}
const bar = { x: "hello", y: 123 };
const baz: Foo = bar; // no error
```

See #12936 for the feature request to add closed/sealed/exact types to the language.

This is complicated by [excess property checks](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-1-6.html#stricter-object-literal-assignment-checks), which mark extra properties as an error, but only when you are assigning an *object literal* directly in a place where the extra properties will be immediately forgotten by the compiler:

```ts
const qux: Foo = { x: "hello", y: 123 }; // error
```

It's not that `{x: "hello", y: 123}` isn't a valid `Foo`, it's that knowledge of the `y: 123` property will be thrown away and maybe that's indicative of a mistake.

So, in general, extra properties are allowed.

---

That means `B` is assignable to `A` because every possible property in `B` is also a valid property in `A` (e.g., `"5_prop"` is also a `string` key).   It's okay for `B` to have explicit support for more properties than `A` does; extra properties are allowed.

Additionally, since you defined  ``type A = Record<`${number}_prop`, number>``, then `A` is also assignable to `B`.  That's because `A` is given an [implicit index signature](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#implicit-index-signatures).  Implicit index signatures are not really type safe, since they allow you to do things like `const x = {"5_prop":5, someExtraProp: true};` and then `const y: A = x;` and then `const z: B = y`, but that's the way it is.  And so in your code you can also call `test<B>(a, b)` with no error.  As it stands, `A` and `B` are mutually assignable, which is working as intended.

If you had defined `A` like ``interface A { [k: `${number}_prop`]: number }`` then `A` would not be assignable to `B` , since `interface` types are not allowed to have implicit index signatures (see #15300 for details) and then `test<B>(a, b)` would be a problem.  But `test<A>(a, b)` would work no matter what.

---


[Playground link](https://www.typescriptlang.org/play?ts=4.5.4#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChkHIAeAXMgM5hSgDmA3LgL64LoiXIBGcUyAvDmJkARAAsIAGwnphAGmQBPMgEYATAGZkjBq3ZgucAF5kMWAdyh1kAemvIQWaFHRQWbDgEcArqTSZ+gr5iktJyiioaWla2yE4uuLgwXiAIYMBsyJCUADwAKgB8ABTonABWymS58iWlqpUAlDj4hFAQYF5QIMg1qgzMuCBwALYQ5AAOiCgA8tQ0Tc0EYApjKACCAdjIANoA1mQABgAk2CBeQ5zQjAD6Y85j+wC6ZKfn0FoJhMi6HHBk6wJ4T6fYQAVhud2EZBBsgWUQ+hFAkFgk2QACEmkDCLsyJRqCAaE97GcLpZYcxPt99JwyOiAbDPnAACZMuDqKEwzEEFnMurIADsHMI2nhBEpxA2yFB4PQY0hyGhFHQIwAokQqHAAAp3MhULwoYUU9z6JTIf7EBiGvTIYxogIKBiwrJgQpweSceoWwhO7KrIqurgex2jMDZVF+t2BhL9AbDUYTJDIACS8ATeFhiOgKbWgmxyCOJ2Jl2l90JLxJ71hYt+po29MIUtuMrl0LJDs+GeRCfRgM5udxtFLhdJn3JhDF1NtdM5yG5rPZda5zJ5ZAFrZFXyN4oBkrBjdl7MVKrVUE12syUD1cMtHBNZqIntFm5ttMU0TscVcQcoLojD8ywZ9cMAz-b0wx-YCbHfKBnE-RggA)

**Comment by redplant3d** [comment]
Thanks for the clarification. We see it now.
