### ISSUE TITLE
Dynamic import compiles to `require()`, which throw errors when importing ES modules 

### ISSUE THREAD

**Issue by aquapi** [microsoft/TypeScript#48103]
# Bug Report

The dynamic import feature supports importing ES modules into CommonJS modules. `npx tsc` compiles dynamic import to `__importStar(require())` which cannot import ES modules

### 💻 Code

```ts
import("file.mjs")
```

### 🙁 Actual behavior

```javascript
__importStar(require("file.mjs"))
```

### 🙂 Expected behavior

```javascript
import("file.mjs")
```

**Comment by RyanCavanaugh** [comment]
To get that behavior, set `module` to `esnext`

**Comment by magicdawn** [comment]
Hello here is the use case.

we want TypeScript emit commonjs modules in node.js, and node tell us we can use
dynamic import in commonjs module to load an esm module. https://nodejs.org/dist/latest-v16.x/docs/api/esm.html#import-expressions

tsconfig.compilerOptions.module can not be changed, since esm & commonjs have many differneces, migrate a whole project would be a big effort.

**Comment by magicdawn** [comment]
same as https://github.com/microsoft/TypeScript/issues/43329

**Comment by sguillia** [comment]
To get that behavior, set `moduleResolution` to `node16` while leaving `module` to `commonjs`.

This will convert all imports to requires, except dynamic imports (`await import()`)
