### ISSUE TITLE
Spurious [?] circularity error in getter with spread

### ISSUE THREAD

**Issue by RyanCavanaugh** [microsoft/TypeScript#48178]
# Bug Report

### 🔎 Search Terms

circularity getter

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAQg9gDygXigbwFBSgYzgO2AkIH4AuKAMTjigB9ZEMBfAbgwBMIcAbAQwBO0PPgDOwKACMK8BO159RoqjXRYoAcwgSAZjQAUASjXZsQ4AFcB+E6ewiihCsAAWAS2WKVtBrIA06nYAdCGSgVBs6swsQA)

### 💻 Code

```ts
type Box = {
  content?: Foo | Box
};
declare const b: Box;
class Foo {
  get foo() {
    return {
      content: this as Foo | Box,
      ...b
    };
  }
}
```

### 🙁 Actual behavior

Circularity error on 'foo' when this is probably deferrable

### 🙂 Expected behavior

No circularity error

Ref. #46981

**Comment by Andarist** [comment]
The problem comes from within the [`checkAccessorDeclaration`](https://github.dev/microsoft/TypeScript/blob/c6fb2e10dcdf4839924a4288dae1cfd93b3c1c57/src/compiler/checker.ts#L38221) and the [`getTypeOfAccessors`](https://github.dev/microsoft/TypeScript/blob/c6fb2e10dcdf4839924a4288dae1cfd93b3c1c57/src/compiler/checker.ts#L38276) call in it. 

This starts a type resolution that ends up with a cycle because `getSpreadType` tries to create a union of the left type and the right type [here](https://github.dev/microsoft/TypeScript/blob/c6fb2e10dcdf4839924a4288dae1cfd93b3c1c57/src/compiler/checker.ts#L18114). The problem is that this is a subject of subtype union reduction and this [`find(getPropertiesOfType(source), p => isUnitType(getTypeOfSymbol(p)))`](https://github.dev/microsoft/TypeScript/blob/c6fb2e10dcdf4839924a4288dae1cfd93b3c1c57/src/compiler/checker.ts#L16196) leads to requesting the `get foo`'s type while we are still resolving it.

**Comment by RyanCavanaugh** [comment]
Not an error anymore

**Comment by Andarist** [comment]
Bisected to https://github.com/microsoft/TypeScript/compare/f218a562bfb417ecec263fc96d7a7a71abf96268...1df5717b120cddd325deab8b0f2b2c3eecaf2b01 and confirmed that it was fixed by https://github.com/microsoft/TypeScript/pull/53413

**Comment by jakebailey** [comment]
Oh what, that PR should have only been a perf optimization, not a behavior change...
