### ISSUE TITLE
Generic classes with `this` functions contain signatures for those functions regardless of actual arguments

### ISSUE THREAD

**Issue by JordanLongstaff** [microsoft/TypeScript#48188]
# Bug Report

Classes with generics can have functions with a `this` parameter that restricts their usage to classes with the correct arguments, e.g.:

```
class Foo<Key extends "a" | "b"> {
    public bar(this: Foo<"a">) {
        // do something
    }
}
```

So if I have a `Foo<"b">`, I cannot call `bar` on it because it's not a `Foo<"a">`. But `bar` still exists within the signature of `Foo<"b">`, meaning that I can cast it as `{ bar: () => void; }` and then its usage is accepted by the compiler when it should not be.

### 🔎 Search Terms

`is:issue this`

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because my workplace only just discovered this issue. We use Typescript 4.2.2, but we can confirm that the issue persists in Typescript 4.6.2.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?suppressImplicitAnyIndexErrors=true&ts=4.6.2#code/MYGwhgzhAEDCIQDwDECmAXYALVATaqAHuqgHa4wBEYl0APtJQEa0OXCUB80A3gFDRB0AA4BXJiACWwaMAD2pCOgBOo4OjnKAFAKF7hyyQDcwJaMtRhcCkAE9oplRABcvANoBpVPcmloaTBxcAF1XUlEAWyZUZQBfXUEASl4E6Hi9PlSxCWloAHMMAEEtdCxJFzgERGouRLDI6OUUvT0LdFFlPwBGAG5U+Pi+ADNRUnVJBWghgAYtUAr4JGZa+qiY5qE2jr95gDoC9GLEvsGRsfQJv19cSQtxhS1fJVceA8LXLWSAXm5wtbi6tA-o0NoItp1oE90Psip8Tpkzvc-EMunMEK5FtUWJxAcD1vxWhhtpDyLdUEi0RBjnxBkA)

### 💻 Code

```
class Foo<Key extends "a" | "b"> {
    public constructor(private readonly key: Key) {}

    public bar(this: Foo<"a">): number {
        return 0;
    }
}

type FooSignature = {
    bar: () => number;
};

const foo: FooSignature = new Foo("b");
foo.bar();  // SHOULD BE A TYPE ERROR, BUT ISN'T
```

### 🙁 Actual behavior

Typescript does not return a compile-time error at the `bar` call. This is corroborated by the playground which has different code, but works on the same principle: `f0` correctly returns a compile-time error, and `f1` should too, but it doesn't.

### 🙂 Expected behavior

There should be a compile-time error at the call to `foo.bar()`.

**Comment by fatcerberus** [comment]
> `foo.bar();  // SHOULD BE A TYPE ERROR, BUT ISN'T`

`foo.bar()` is a valid call to make on a `FooSignature`, so the *call* shouldn't be a type error.  The assignment of a `Foo<"b">`` *to* `FooSignature`, however, *should* be an error, but isn't because a function without an explicit `this` type is treated as `this: any`.  Unfortunately, `noImplicitThis` has no effect on function type assignability. 😞

**Comment by RyanCavanaugh** [comment]
We tried putting `this` parameters everywhere behind the scenes when we first implemented `this` types, but the perf implications were horrifying.

**Comment by fatcerberus** [comment]
@RyanCavanaugh I understand that functions not having an actual `this` type unless specified is for perf reasons, but it would be nice if there were a `strictFunctionThis` option that would make `(this: T) => void` not be assignable to `() => void`.  Conceptually, the former has one more required parameter than the latter.  Particularly salient since one of the most common pitfalls in JS is to do this:
```ts
setTimeout(foo.bar, 1000);
```
and then have `bar` not get the right `this` when it's called.

**Comment by RyanCavanaugh** [comment]
I'd take a suggestion on that and we could experiment. I'm not sure why that rule wasn't in place initially - it seems sensible
