### ISSUE TITLE
Referencing module name using index when resolving module name can be incorrect

### ISSUE THREAD

**Issue by sheetalkamat** [microsoft/TypeScript#48229]
We cannot assume that module name is referenced at index `i` in containing source file because we could be calling you with only few module names from the source file. https://github.com/microsoft/TypeScript/blob/main/src/compiler/program.ts#L1571 shows that case

_Originally posted by @sheetalkamat in https://github.com/microsoft/TypeScript/pull/45884#r825151963_

**Comment by sheetalkamat** [comment]
@weswigham

**Comment by weswigham** [comment]
Hm, the called should just need to get updated to pass in `ReferencedFile`s then, rather than a raw name list, since the `ReferencedFile`s include the index in the original name list with which we can lookup the mode of the import. Similar to how `getModuleNameStringLiteralAt`'s callers already use `FIleReference`s.

In any case, do you know how this'd manifest in an issue so we can have a test?

**Comment by sheetalkamat** [comment]
```ts
import {a} from "a"
import { b} from "./b"
```

I think in this case if b.ts was not present in first pass and then b.ts is created this could be true.  Some resolutions can be reused but others need to recalculated in the file.

**Comment by weswigham** [comment]
So I've spent far, far too long on this - and not on fixing it, no, that's [_easy_](https://github.com/weswigham/TypeScript/commit/0acc4002ed0d1a27a329d5ed56bf1c92b8384191). Writing a _test_ that actually proves there's an issue that needs fixing is what's been burning away the hours.

So, your example. It's close to what you'd think would trigger an issue (you'd need to ensure the modes of both imports are different, too, to actually cause a problem, which means using type-only imports and assertions), given the way `resolveModulesReusingOldState` is written, but no - it's actually _impossible_ for the `resolveModuleNames` callsite within to get a partial resolution list, at least with our built-in hosts and caches. This is because we only reuse old resolutions at all if the new file is the same as the old file, in which case we'd reuse every resolution - the only missing resolutions would be those which didn't originally resolve, as you suspect. However, when there _is_ a missing resolution, we invalidate _all_ resolutions in the file when any of those missing resolutions appear! (And thus recalculate _all_ resolutions in the file from scratch.) Thus, there's no circumstance where we ever attempt to resolve a partial list of resolutions, as much as the code is evidently written to try to handle such as case.

So it's actually impossible to test my [fix](https://github.com/weswigham/TypeScript/commit/0acc4002ed0d1a27a329d5ed56bf1c92b8384191) for this (which is fairly straightforward), because it's actually impossible to trigger a problem, at least without custom resolution caches and LS hosts that behave very differently from our builtin ones. This is [a test you would expect to fail](https://github.com/weswigham/TypeScript/commit/73eaf811dfebdd0a817a663204176d11f33a4dff), but it's already passing because of the aforementioned over-invalidation done by our hosts.


So not sure what to do here, tbh.

**Comment by sheetalkamat** [comment]
Found the test case as part of my module resolution caching work
