### ISSUE TITLE
Command line option descriptions should be more consistent

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#4825]
Consider the description for `newLine` and `noEmit`:

Option Name | Description
------------|------------
`newLine` | "Specifies the end of line sequence to be used when emitting files: 'CRLF' (dos) or 'LF' (unix)."
`noEmit` | "Do not emit outputs."

The two are phrased in different [verb forms](https://en.wikipedia.org/wiki/Uses_of_English_verb_forms) (and I'm sure @JsonFreeman could categorize them down perfectly).

These diagnostics should be consistent, and any changes should ideally be reflected on the respective wiki page: https://github.com/Microsoft/TypeScript-wiki/blob/master/Compiler-Options.md

**Comment by mhegazy** [comment]
Feel free to send a PR to clean them all up.

**Comment by JsonFreeman** [comment]
Good catch @DanielRosenwasser. The difference is the mood, which is indicative in the first and imperative in the second.

That said, I'm not sure the inconsistency is bad. The reason is that the subject of the first description is the compiler's option, whereas the subject of the second is the compiler's behavior. So different subjects might warrant different moods in this context. I'm inclined to say these two make sense the way they are.

**Comment by DanielRosenwasser** [comment]
@vladima was actually the one who caught this. Still I'm not sure the compiler should go through grammatical mood swings between a list of options.

**Comment by JsonFreeman** [comment]
Haha, mood swings. I think it's fine to make it consistent mood, but you may have to change the subject of the phrase to do so. How about this

>Use the specified end of line sequence when emitting files

**Comment by JsonFreeman** [comment]
The other difference btw is the negation in "Do not emit outputs". Consider what it would sound like if the option was "Does not emit outputs". The natural question would be "well then, what *does* it do?"

**Comment by DanielRosenwasser** [comment]
Hah, yeah, I had a hard time figuring out a better way to make `noEmit`'s message consistent with `newLine`, but the opposite switch seems slightly easier.
