### ISSUE TITLE
Investigate recent regression on Material UI from contextual discrimination changes

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#48298]
#43937 seems to have regressed our check times on material UI drastically.

![image](https://user-images.githubusercontent.com/972891/158706142-5ebcb7ea-7273-461c-910a-7d1e2c6459ab.png)

We'll need to address this before TS 4.7

_Originally posted by @DanielRosenwasser in https://github.com/microsoft/TypeScript/issues/43937#issuecomment-1069730519_

**Comment by weswigham** [comment]
cc @erikbrinkman who may or may not still be interested in the saga of this issue

**Comment by weswigham** [comment]
> reproducibility - can you point me to how to run the material-ui benchmark to test different changes?

Unfortunately, we don't keep our perf tests in a public repo. Fortunately, in this case, it's just the compiler run on material-ui right off GitHub. (Admittedly an old version, but that hopefully shouldn't matter for tracking down the perf issue)

debugging / profiling - it may be helpful to time individual sections, are there tools in place to help with this sort of profiling?

`--extendedDiagnostics` for rough timing information like it's used to make the chart above. `--generateCpuProfile` for a V8 [function by function profile](https://www.typescriptlang.org/tsconfig/#generateCpuProfile). `--generateTrace` for some very [detailed timing data](https://github.com/microsoft/TypeScript-wiki/blob/main/Performance-Tracing.md).

> Caching - ... other documentation on appropriate caching of things like this, that would also be helpful

There is not any docs per sey, but types are checker local, so just storing the results in an appropriately keyed map in the type itself should work. (The only interesting things we do for caching is look-aside tables for caches associated with symbols and nodes since those can last thru multiple checker runs - `getSymbolLinks` and `getNodeLinks` respectively)

**Comment by erikbrinkman** [comment]
I'm having trouble reproducing the regression.

Below are the times in seconds for each sub-package of material-ui (tag v5.5.1) as profiled by lerna in non-parallel mode on my machine. I ran the tests for three commit hashes, the one right before this PR, the current main branch, and the main branch with a reversion commit of this pr.

package | before #43937 | main | reverted #43937
----|-----|----|-----
@mui/base | 26.268347600000002 | 26.7986195 | 33.0626978
@mui/icons-material | 26.870894 | 27.19544 | 26.792166100000003
@mui/joy | 45.258862799999996 | 49.9254462 | 62.4831679
@mui/lab | 40.5806509 | 45.2504982 | 57.1469001
@mui/material | 70.86257459999999 | 77.4559788 | 88.8601728
@mui/material-next | 21.8407785 | 24.106021600000002 | 22.7398095
@mui/private-theming | 22.3616186 | 23.1901557 | 27.4129729
@mui/styled-engine | 34.4923338 | 34.983745299999995 | 34.9130545
@mui/styled-engine-sc | 49.7938617 | 51.5644316 | 53.9521717
@mui/styles | 25.465002600000002 | 30.1549613 | 39.1888584
@mui/system | 31.444028199999998 | 36.7753012 | 46.1737295
@mui/types | 7.4932431 | 7.7030562 | 7.6045776
@mui/utils | 33.7302696 | 34.9460455 | 34.3483024
docs | 6.3518498 | 6.978989299999999 | 6.8208478
test | 32.532102 | 33.2769884 | 33.110612100000004
typescript-to-proptypes | 15.6097092 | 15.9531274 | 15.6577215

There does seem to be a significant regression between before the PR and main, although it appears to be at most 20% not the 80% that seen in the attached graph. Strangely, simply reverting the commit makes things significantly worse. I'm running these on WSL so maybe that's why there's weird diagnostic overheads. It's also probably worth noting that I get errors on both branches that aren't main, having to do with `Excessive stack depth comparing types`.

The only thing I can think of is that maybe material-ui has changed. Is it possible to get the commit hash of the version your profiling is based off of? Alternatively would it be hard for someone to verify the profiling behavior on v5.5.1 of material-ui?

**Comment by weswigham** [comment]
I don't have an exact SHA, but I can tell you it's from `material-ui` version 4.8.3. Hopefully anything from that version is comparable (hopefully there's a git tag).

**Comment by amcasey** [comment]
And the benchmark in question is building `-p docs -incremental false`

**Comment by erikbrinkman** [comment]
Thanks for the tips! I'm still struggling to reproduce.

On the latest tag (v5.5.1) the pinned typescript reports no errors, but there are errors with ~v4.4 (so all the versions I'm comparing for timing). On v4.8.3. `yarn tsc -p docs` fails with both the tagged version on all of the different cuts I'm testing.

If I ignore the errors and look at timing, then I still can't reproduce the performance regression. I could try to fix all of the errors on v4.8.3, but it's not clear if the way that I fix them will show consistent regressions. Also, apriori I have no estimate for how difficult fixing them is going to be.

I know you don't have a commit hash for what your benchmarking on, but I imagine to test recent versions of the compiler you've had to make independent patches on top of the cut you took. Is there any chance you can upload a patch of those commits? Ideally just something where tsc v4.4 works when applied to 4.8.3.

**Comment by amcasey** [comment]
On my box, reverting 751c11412618e8b2a504380135bc2f0b2505e18f cuts the check time for the docs project in MUI [`master`](https://github.com/mui/material-ui/commit/f2d6337305b75df97d49e58f19288429b7f767e5) by 20%, back to the TS 4.6 level.

**Comment by amcasey** [comment]
My repro steps:

1. git clone https://github.com/mui/material-ui
2. cd material-ui
3. `yarn --ignore-scripts`
4. `yarn docs:typescript:check` (this used to generate some files - not sure if it still does)
5. `node pathtomylocal/tsc.js -p docs -incremental false -extendeddiagnostics`

(This is largely from memory, so I may have missed a step)

**Comment by amcasey** [comment]
> I know you don't have a commit hash for what your benchmarking on, but I imagine to test recent versions of the compiler you've had to make independent patches on top of the cut you took

Actually, I believe the benchmark remains immutable and we eventually end up measuring how long it takes to produce appropriate errors.

**Comment by erikbrinkman** [comment]
Thanks so much @amcasey for the context. I can now reproduce!
