### ISSUE TITLE
Type inference as any with child classes and generics

### ISSUE THREAD

**Issue by Nokel81** [microsoft/TypeScript#48293]
# Bug Report

### 🔎 Search Terms

- inference
- any
- child classes
- generics
- parameters

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about 
- I tried this in 3.8, 4.6, and nightly

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2#code/GYVwdgxgLglg9mABDKBTATgUQG4YJ4A8AKgHwAUAzuhAFyICSa6AhgEYA2qxJANIsGDplszdnSIBKRAF4SiZmDwS6rOHE4LEAbwBQifnHSIyEBBSiIR7RHGCIqEKbv36YdsgEIBw0RKd6XfXRUKBB0JGBRClQAbgD9AF8ApIDg0PDEKHQQWJ0U0EhYBHsQikwARxBRAgBpcmY6AGUQ2t5EViaWuuV2tQ0kZ0Q0sKRmADoKGAAvVBlpaXaJ6dmAMhXkJhx8MnGrHIoyCT4rGTlWMYALZgOrPziUgBNUCHZmYMQX64pEAHlWaPQIg4qGaUG4yAAtgAHTgQ1BgKDfUHgwb6F6oN6HOjYOAwB5xQLAQyYZgQC4mUTsVikgDWADFBMY9qhxMdRDkAEyskpQTpg0hSWSWXEPPhQC4wCgAQXQAHMAPx0BRKbEigkuWUhezLLGIMAgCGsDDq-TMB4PHzsHLiHriyUmxBPThoS3W+SKHqqdQYsAOq43dks90q3rehQO+FZGCoA49RgYNiceMsKCGAgAbSIfCIAF0SA6aag8LG6MnE6gy6n0NwHcySwwmOXK2nSA7gjDSagyHBxRg6H8AUDOMjSIgAD6IIjpnPjoYYh4Idh4SfTnoDjBDkEtVvxTJwABSjR+ADldVOcw7U40o2BZbrzOgYLeHenGnhDeoxigE1Wc7qy8CzbVjugSahYr7vqo7BjFeN6ykQzCyn+PQPk+sr3DoOjRIiFRVOwZBgKgADuiDIqht7kEcerEb8-wbuWZFwZREhxNhZSVKIBE0eugIMS05GypRfCESRPGboxj4UYcLFYaUuGcSJpH8UxhzCTRElocxMRAA)

### 💻 Code

```ts
function iterEvery<T>(src: Iterable<T>, fn: (val: T) => any): boolean {
  for (const val of src) {
    if (!fn(val)) {
      return false;
    }
  }

  return true;
}

function setsEqual<K>(a: Set<K>, b: Set<K>): boolean {
  return a.size === b.size && iterEvery(a.values(), val => b.has(val));
}

declare class ObservableSet<T> implements Set<T> {
    clear(): void;
    forEach(callbackFn: (value: T, value2: T, set: Set<T>) => void, thisArg?: any): void;
    get size(): number;
    add(value: T): this;
    delete(value: any): boolean;
    has(value: any): boolean;
    entries(): IterableIterator<[T, T]>;
    keys(): IterableIterator<T>;
    values(): IterableIterator<T>;
    replace(other: ObservableSet<T> | T[] | readonly T[]): ObservableSet<T>;
    toJSON(): T[];
    toString(): string;
    [Symbol.iterator](): IterableIterator<T>;
    get [Symbol.toStringTag](): string;
}

// A
setsEqual(new Set<string>(), new ObservableSet<string>());
// B
setsEqual(new ObservableSet<string>(), new ObservableSet<string>());
// C
setsEqual(new ObservableSet<string>(), new ObservableSet<number>());
// D
setsEqual(new Set<string>(), new Set<string>());
// E
setsEqual(new Set<string>(), new Set<number>());
```

### 🙁 Actual behavior

In cases `A`, `B`, and `C` the type parameter on hover for `setsEqual` is `any`.

In case `D` it is `string` and in case `E` it is string with a type error

### 🙂 Expected behavior

In cases `A`, `B`, and `C` the type parameter on hover for `setsEqual` is `string`.

**Comment by DanielRosenwasser** [comment]
It seems to be because you have defined `delete` to take `any` (technically more correct), whereas `Set` defines it as taking `T`.

```diff
-    delete(value: T): boolean;
+    delete(value: any): boolean;
```

I believe what's happening is that when we perform inference from an `ObservableSet<string>` to a `Set<T>`, we try to infer from `any` to `T` which spoils all the other inference candidates.

**Comment by Nokel81** [comment]
@DanielRosenwasser Even if I restrict the interface for the `setsEqual` function without `delete` the inference still fails.

[Link to playground](https://www.typescriptlang.org/play?ts=4.6.2#code/GYVwdgxgLglg9mABDKBTATgUQG4YJ4A8AKgHwAUAzuhAFyICSa6AhgEYA2qxJANIsGDplszdnSIBKRAF4SiZmDwS6rOHE4LEAbwBQifnHSIyEBBSiIR7RHGCIqEKbv36YdsgEIBw0RKd6XfXRUKBB0JGBRClQAbgD9AF8ApIDg0PDEKHQQWJ0U0EhYBHsQikwARxBRAgBpcmY6AGUQgBkYAGsuOr5WJtaOrpJlRFV1VE1nRDSwpGYAOgoYAC9UGWlpEYXl1YAyHeQmHHwyeascijIJPisZOVY5gAtmC6s-OJSYMCZIiFXmqDanVqckmwWYABMEOw8PZtnQwCAALasDBxfRnVAXYaMDBsTg4lhQQzAtGIJ4vUQ5Og1YajDRgd46HTg1AQdjMYKINnPCiIADyrGi6BEHFQ-24yERAAdOIjUF9eeLSNp4lyNOhLnRsHAYODSfpgIZMMwIA8TKJ2KwTe0AGKCYwY8TXSmoABMTpKUD6UG4Ulklh14L4UAeMAoAEF0ABzAD8dAUSi1gf1iCjIVhK01iARyNRqoh4J87CpiEkdBDYZTLM4aCLJYTtLU9JT5LrqHjikbYwUKflWRgmKzBLxqGHRPQBAA2kQ+EQALokFOdPBYujD0Vj4mkFMY1cMJgjzcT7eq4Iyk2oMhwEMYOgCoUizhKuQAH1Lk7niDfYMhYGh77nYZ7wwR8xRCbgUyJAApRo+QAOSzIgP0guBGn7MAoyzcx0E+KMU0nRo8GRdQ5hQXFxznIcDw3A9xwg1U0wsAiiNUdg5iJNCcIwohmCjSjhmw3DGR0aIoDKSpRDIMBUAAd0QcVBIw8grmzWT+UFECRwU9Co2UiQ4lE8SqnYKS1OA4UtPAxTdMuPhpLk8zQO0ribLeETSgqYzTLk5zcOUuy1N8pTLn0oA)

```typescript
interface SetLike<K> {
  readonly size: number;
  values(): IterableIterator<K>;
  has(value: K): boolean;
}

function setsEqual<K>(a: SetLike<K>, b: SetLike<K>): boolean {
  return a.size === b.size && iterEvery(a.values(), val => b.has(val));
}
```

**Comment by DanielRosenwasser** [comment]
I think that's just the same problem I described, but caused by the `has` method taking `any` instead of `T`.

[Check out this playground link as an example](https://www.typescriptlang.org/play?ts=4.6.2#code/GYVwdgxgLglg9mABDKBTATgUQG4YJ4A8AKgHwAUAzuhAFyICSa6AhgEYA2qxJANIsGDplszdnSIBKRAF4SiZmDwS6rOHE4LEAbwBQifnHSIyEBBSiIR7RHGCIqEKbv36YdsgEIBw0RKd6XfXRUKBB0JGBRClQAbgD9AF8ApIDg0PDEKHQQWJ0U0EhYBHsQikwARxBRAgBpcmY6AGUQgBkYAGsuOr5WJtaOrpJlRFV1VE1nRDSwpGYAOgoYAC9UGWlpEYXl1YAyHeQmHHwyeascijIJPisZOVY5gAtmC6s-OJSYMCZIiFXmqDanVqckmwWYABMEOw8PZtnQwCAALasDBxfRnVAXYaMDBsTg4lhQQzAtGIJ4vUQ5Og1YajDRgd46HTg1AQdjMYKINnPCiIADyrGi6BEHFQ-24yERAAdOIjUF9eeLSNp4lyNOhLnRsHAYODSfpgIZMMwIA8TKJ2KwTe0AGKCYwY8TXSmoABMTpKUD6UG4Ulklh14L4UAeMAoAEF0ABzAD8dAUSi1gf1iCjIVhK01iARyNRqoh4J87CpiEkdBDYZTLM4aCLJYTtLU9JT5LrqHEjbGChT8qyMExWYJeNQQ6J6AIAG0iHwiABdEgpzp4LF0Iei0fE0gpjErhhMYcb8db1XBGUm1BkOAhjB0AVCkWcJVyAA+pYns8Qr7BkLA0Lfs+GO8MAfMUQm4FMiQAKUaPkADksyId8ILgRo+zAKMs3MdBPijFMJ0aPBkXUOYUFxMdZ0Hfd133MdwNVNMLHwwjVHYOYiVQ7D0KIZgowo4YsJwxkdGiKAykqUQyDAVAAHdEHFAT0PIK5sxk-lBWA4d5LQqMlIkOIRLEqp2Ek1SgOFTSwIUnTLj4KTZLMkCtM46y3mE0oKiMkzZKcnClNs1SfMUy49KAA).

**Comment by Nokel81** [comment]
Okay I understand thanks.
