### ISSUE TITLE
how to typeScript node_modules .gitignore on github? 

### ISSUE THREAD

**Issue by mdyeamin** [microsoft/TypeScript#48325]
![image](https://user-images.githubusercontent.com/73517661/159047928-af9af770-1bb1-4b58-b120-58fe6fdcfb0b.png)

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
