### ISSUE TITLE
Extending from a class with generics breaks type checking?

### ISSUE THREAD

**Issue by Lorthirk** [Microsoft/TypeScript#4838]
Hello all.

Whle trying to implement a simple serialization for my models, I stumbled upon what I think is a bug.

Consider the following scenario:

```typescript
interface ITest {
	a: number,
	b: number
}

class Test extends BaseModel<ITest> {
	constructor(obj:ITest) {
		super(obj);
	}
}

class BaseModel<T> {
	constructor(obj:T) {
		for (var propName in obj) {
			this[propName] = obj[propName];
		}
	}
}

var array:Test[];
array.push({c: "test"});
```
I expect the array.push() in the last line to fail because I would be pushing something that does not conform. Instead, no error is thrown on that line.

Am I doing something wrong?

**Comment by ahejlsberg** [comment]
Problem is that the `Test` type has no members, meaning that any object type assignable to it. This is an effect of TypeScript's structural type system (specifically, a source object type is assignable to a target object type as long as the source object type has all the properties of the target object type--which in your case is none). Once you add members to `Test` you get the expected behavior.
