### ISSUE TITLE
Missing HTMLMediaElement.preservesPitch

### ISSUE THREAD

**Issue by Tenpi** [microsoft/TypeScript#48444]
# lib Update Request

## Configuration Check

My compilation *target* is `ES2015` and my *lib* is `the default`.

## Missing / Incorrect Definition

HTMLMediaElement.preservesPitch is missing from the types. It is supported in nearly every browser. 

## Sample Code
```ts
// throws error
videoElement.preservesPitch = true
```

## Documentation Link
Documentation: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/preservesPitch

**Comment by huytd** [comment]
Hi, I'd like to work on this issue

**Comment by huytd** [comment]
Based on the discussion in https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1300, I think there is no need to fix this issue from within TypeScript's codebase.

The main reason for this issue is because `preservesPitch` is only available in the standard form in Chrome, and is prefixed in other browsers. Once the other browsers implemented it, the `lib.dom.d.ts` generator will be able to generate the type correctly.

Here are the relevant issues to track in Safari and Firefox:

- https://bugs.webkit.org/show_bug.cgi?id=214922
- https://bugzilla.mozilla.org/show_bug.cgi?id=1652950

**Comment by Tenpi** [comment]
Hi, thanks for the info, didn't know that it only works with a prefix on Firefox and Safari.

**Comment by jakebailey** [comment]
This was fixed in #49596.
