### ISSUE TITLE
Default argument doesn't constrain generic in higher-order function edge case

### ISSUE THREAD

**Issue by texastoland** [microsoft/TypeScript#48480]
# Bug Report

### 🔎 Search Terms

<kbd>default argument infer generic</kbd>

### 🕗 Version & Regression Information

- This is the behavior in _every_ version I tried, and I reviewed the _entire_ FAQ

### ⏯ Playground Link

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?ts=4.7.0-dev.20220329#code/MYewdgzgLgBAlmAZgUwE4EFUHMYF4YA8AKjMgB5TJgAmEMA2gK5gDWYIA7mAPwC6AfAApEALhiCAdFICG2CGKIBKPPxgA3EHGqKxUAJ4AHZCEQxTuVYgBQVgPS2Y0gDYQQMdqVSoQqeGBjQqHDAUNxWCCgY2IKC0LKw+AAMyhYwAN4Avsr2hPRxqKFizGycYAJ2DgB6YRFomFgx+VBiYIwAtgBGaHgwySrpWTA5BHlQ8dwt7V2+AD4wzNTIiAjI1AJAA)

### 💻 Code

```ts repro
const inferArg = <T extends [unknown?]>(f: (...args: T) => void): typeof f => f

// also no error in strict?
inferArg((start = 0) => {}) // <[start?: unknown]>
// ^?
inferArg((start: number = 0) => {}) // <[start?: number | undefined]>
```

### 🙁 Actual behavior

Infers `start` as `unknown`.

### 🙂 Expected behavior

Infers `start` as `number?`. I expect the 2 calls to be equivalent.

Inference was a minor inconvenience because I'm using JSDoc. There's a separate DX issue that there was no compiler feedback on failed inference.

Is there already a ticket requesting an additional strict flag when a generic param can't be specialized and doesn't specify a default? I couldn't find it!

**Comment by RyanCavanaugh** [comment]
Parameter defaults don't act the same as type annotations because taking the more-specific type of the initializer can often defeat inference that would have otherwise succeeded. For example:
```ts
declare function callsIt<T extends string | number>(func: (arg1: T, arg: T) => void): void;
callsIt((n = 0, m = "") => null);
```
IOW we treat a default in this case exactly the same as its desugaring (a conditional reassignment at the top of the function body, which has no effect on the parameter type).

> Is there already a ticket requesting an additional strict flag when a generic param can't be specialized and doesn't specify a default? 

This happens way more often than you think it does (example: unspecified optional parameters); a flag that produced an error on this condition wouldn't be usable in practice.

**Comment by texastoland** [comment]
Thanks for the example!
