### ISSUE TITLE
Odd behavior on commonjs modules not inside node_modules folders

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#4849]
Consider the package:
- `/mylib`
  - `package.json`
  - `index.d.ts`
  - `/sublib`
    - `package.json`
    - `index.d.ts`
    - `other.d.ts`

We correctly find and import the `.d.ts`s in `mylib` and `sublib`, but we do not apply the restrictions applied in #4738, despite being within an external package.

Repo with repro: https://github.com/weswigham/ts-4849-repro

**Comment by vladima** [comment]
this is by design, currently it is assumed that external module typings is something that is referred by non-relative name is resolved from node_modules folder. Rationale: such modules are not authored by user so user cannot control what is inside. There if of course another aspect of it when external module typings use relative module name to imports something from the same package. this is another bug when we don't propagate import resolution context when loading transitive imports, I think it is currently tracked by #4667
