### ISSUE TITLE
Got the wrong return value when overloading method

### ISSUE THREAD

**Issue by xipx** [Microsoft/TypeScript#4852]
The declaration is something like this:

```ts
interface JQuery {
    /**
     * Store arbitrary data associated with the matched elements.
     *
     * @param key A string naming the piece of data to set.
     * @param value The new data value; it can be any Javascript type including Array or Object.
     */
     data(key: string, value: any): JQuery;
    /**
     * Store arbitrary data associated with the matched elements.
     *
     * @param obj An object of key-value pairs of data to update.
     */
     data(obj: { [key: string]: any; }): JQuery;
    /**
     * Return the value at the named data store for the first element in the jQuery collection, as set by data(name, value) or by an HTML5 data-* attribute.
     *
     * @param key Name of the data stored.
     */
     data(key: string): any;
    /**
     * Return the value at the named data store for the first element in the jQuery collection, as set by data(name, value) or by an HTML5 data-* attribute.
     */
     data(): any;
 }
```

But ... the following expression give me a `JQuery` type, which is incorrect. 
It should be valued as `any` type because of the call signature(`data(key: string): any;`).

```ts
var abc = $('.selector').data('text'); // abc:JQuery

if(abc === 'abc'){ // this got me a error... which is incorrect!
    
}
```

Is this a bug or expected behavior?

The tsc version is 1.6.2.

**Comment by DickvdBrink** [comment]
Had the same issue here, workaround I did was to move the 
`data(key: string): any;` to the top which fixed 14 errors in my code; Hope this helps for you to so you can continue to use ts1.6.2 without hacking in the code :)

**Comment by viniciusx** [comment]
exact same thing happened to me.
workaround for me was:
```javascript
let data: string = $(data.prevPage).data("bind"); //error : type mismatch
let data: string = $(data.prevPage).attr("data-bind");
```
but i like the first one better.

**Comment by danquirk** [comment]
The rules for overload resolution state (from 4.15.1 of the spec):

•	First, a list of candidate signatures is constructed from the call signatures in the function type in declaration order. 
...
•	Otherwise, if the candidate list contains one or more signatures for which the type of each argument expression is a subtype of each corresponding parameter type, the return type of the first of those signatures becomes the return type of the function call.
•	Otherwise, the return type of the first signature in the candidate list becomes the return type of the function call.

The problem here is that there are multiple candidate signatures, namely the signature that takes ```obj``` of an indexer and the one which takes only a ```key``` argument. The 2nd overload is actually the most general single argument overload, so it needs to be listed last. The type ```{ [key: string]: any; }``` is essentially ```any```. This behaves how you want:
```ts
interface JQuery {
     data(key: string, value: any): JQuery;    
	 data(key: string): any;	
     data(): any;
	 data(obj: { [key: string]: any; }): JQuery;
 }
```

**Comment by mhegazy** [comment]
@DanielRosenwasser updated the JQuery typings, see https://github.com/borisyankov/DefinitelyTyped/commit/1d6c126e8ead25892ded5a32df2e813ffad06905

refresh your copy and you should get a working version.
