### ISSUE TITLE
Incorrect operation of type unknown

### ISSUE THREAD

**Issue by JWo1F** [microsoft/TypeScript#48531]
# Bug Report

### 🔎 Search Terms

unknown, extends, unknown does not satisfy

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about unknown and any

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2#code/C4TwDgpgBAaghgGwK4QM5QLxQEoQMYD2ATgCYA8qwRAlgHYDmANFHLSAHwDcAsAFCiQoAMVpkYUCAA9gEWiXTxkadpigAKAG6IUqAPwAuWAEpMKjQWokevPoVqUoAWxAjVagGa1DIskloBrWgIAd1p2EwwVAG8+KDioTzUjawBfTiA)

### 💻 Code

```ts
type Values = Record<string, any>;
type Fn<V extends Values> = (values?: V) => void;

const myFn = (fn: Fn<unknown>) => fn();
```

### 🙁 Actual behavior

I get the error
```
Type 'unknown' does not satisfy the constraint 'Values'
```
However, as the documentation says, anything can be cast to unknown (as well as to any).

### 🙂 Expected behavior

The type unknown should be accepted in the same way as the type any is now accepted.

**Comment by jcalz** [comment]
This is working as intended. The relation being checked is not “can `Values` be cast* to `unknown`” (answer: yes) but “is `unknown` assignable  to `Values`” (answer: no).  The `unknown` type is assignable *from* everything, but assignable *to* very little.

<sup>* The term “cast” is ambiguous and best avoided.  Maybe you mean “asserted” or possibly even “widened” here. In either case, this is not the relevant relation.

**Comment by fatcerberus** [comment]
One potential source of confusion here (which incidentally I was discussing on Discord the other day) is that `V extends Values` is a *covariant* constraint, while `V` itself is contravariant (because it occurs in an input position).  Technically `Fn<unknown>` should be a valid instantiation in this case (it being a subtype of `Fn<Values>`), but TS (currently) has no support for contravariant constraints.  See https://github.com/microsoft/TypeScript/issues/14520.

**Comment by RyanCavanaugh** [comment]
`Fn<unknown>` is a valid `Fn<Values>` structurally, but the directionality of a constraint isn't dependent on the measured variance of the constrained parameter (for better or worse).
