### ISSUE TITLE
Recursive type definition with Promise crashing the compiler

### ISSUE THREAD

**Issue by felipe-mb** [microsoft/TypeScript#48551]
# Bug Report
### 🔎 Search Terms

recursive, types, typescript, javascript, function, promise

### 🕗 Version & Regression Information
Noticed bug last week. 

- This is a crash
- This was tested on versions 4.6.2, 4.6.3 and nightly, and the bug occurs in all

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220401#code/C4TwDgpgBAQghgEygXigZ2AJwJYDsDmUAPlAAqYD2AttmhADzwIB8xUAFAJQqtMDcAWABQANziYoFHPjxwANlABcsRCg7dkrAOQALCHLkUtgocLkRgUAMaHc0ZUyhquPKAG9hTzBYCumXJLSsnJcJgC+QA)

### 💻 Code

```ts
type Bad = string | Promise<Bad> | () => Bad;
var original : Bad = () => 'hello';
let clone : Bad = () => {
  return original();
}
```

### 🙁 Actual behavior
This causes the compiler to get stuck in an infinite computation, and it eventually crashes due to a stack overflow.

### 🙂 Expected behavior
The compiler to correctly read the type of `clone` without a crash. If `Promise<Bad>` is removed from the definition of `Bad` then the bug no longer persists and the expected behaviour occurs.

**Comment by rbuckton** [comment]
This may have been fixed by #49748, as it does not seem to repro in the [nightly](https://www.typescriptlang.org/play?ts=4.8.0-dev.20220725#code/C4TwDgpgBAQghgEygXigZ2AJwJYDsDmUAPlAAqYD2AttmhADzwIB8xUAFOwJQqtNcBuALAAoAG5xMUCjnx44AGygAuWIhQceyVgHIAFhAUKKOgVFGiFEYFADGx3NFVMoG7rygBvUa8zWArpi40rLyCtzCIgC+okA) build.
