### ISSUE TITLE
4.6.2 regression: `Type instantiation is excessively deep and possibly infinite.`

### ISSUE THREAD

**Issue by seansfkelley** [microsoft/TypeScript#48552]
# Bug Report

### 🔎 Search Terms

recursive conditional types 

### 🕗 Version & Regression Information

- This changed between versions 4.5.5 and 4.6.2

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.6.2#code/C4TwDgpgBAigrhATiAPAFQHxQLxQN4BQUUA2gApQCWAdlACIQRgDSEIAzuhgLoD8AXFHbBENAOYBuAgF8pBUJChlRAW0rBKAN2jYCASAA+UanAA2p-UbjUAJhABmNCDctCR41yZUAjJK+8A9gGmEACG1K7sID7B-pRiNMByCtAMTKwcXDhQaFAQAB7AELbsSqrqWhBEULzGENqI1fzVxMRGABQA1mwB9jlQAGRuotRiAJQtrUaErbOt5FS03SC9-UPCI2Lcgmjk3HmFxTal7TT2SFAAktTUSGMk3JNzrbUABgAkeGTSAHSfaSw2JxrrdEBhpK8ns8oDs9gciiUoAFvAArCAAY2AUOeb0+3z+eABGU4uzI3HBkOhc0EZCkVOkJGWq1y63co24EiAA)

### 💻 Code

```ts
type Query<T> = {
  [P in DeepKeys<T>]?: string;
};

type Primitive =
	| null
	| undefined
	| string
	| number
	| boolean
	| symbol
	| bigint;

type DeepKeys<T> = T extends Primitive
  ? never
  :
      | (keyof T & string)
      | {
          [P in keyof T & string]: T[P] extends (infer Inner)[]
            ? `${P}.${DeepKeys<Inner>}`
            : T[P] extends object
            ? `${P}.${DeepKeys<T[P]>}`
            : P;
        }[keyof T & string];
```

### 🙁 Actual behavior

`Type instantiation is excessively deep and possibly infinite.` at the `${P}.${DeepKeys<T[P]>}` snippet.

### 🙂 Expected behavior

No error. Type properly resolves to dot-notation keys of input object.

**Comment by RyanCavanaugh** [comment]
Bisected to #47341

**Comment by ahejlsberg** [comment]
In #47341 we added code to not explore circular constraints, which for sure is correct. But with that code in place we now run into #30639, which by its nature explores more type relations. In this case, the constraints of the types we explore just balloon and we run into the instantiation limiter after creating >5M instantiations.

The quick fix is to rewrite the `DeepKeys<T>` to be more efficient:

```ts
type DeepKeys<T> = T extends Primitive ? never :
    (keyof T & string) | { [P in keyof T & string]: DeepSubKeys<T, P> }[keyof T & string];

type DeepSubKeys<T, P extends keyof T & string> =
    T[P] extends (infer Inner)[] ? `${P}.${DeepKeys<Inner>}` :
    T[P] extends object ? `${P}.${DeepKeys<T[P]>}` :
    never;
```

It's subtle, but moving the template type in the mapped type into a separate type alias causes us to do more caching and explore fewer implied constrains (because there are fewer containing conditional types), and that in turn eliminates the ballooning.

It seems that we might also be able to reduce the number of types we explore in `getResolvedBaseConstraint`. I'll look into that and put up a PR so we can see the effects.

**Comment by seansfkelley** [comment]
Thanks for the detailed explanation! I had fiddled with some solutions using two related types, but I don't think I ever tried breaking them across these lines with mutual recursion.

**Comment by ahejlsberg** [comment]
@seansfkelley You're welcome. BTW, here's an alternate formulation that avoids mapped types which is likely more efficient:

```ts
type DeepKeys<T> =
    object extends T ? string :
    T extends readonly unknown[] ? DeepKeys<T[number]> :
    T extends object ? keyof T & string | DeepSubKeys<T, keyof T & string> :
    never;

type DeepSubKeys<T, K extends string> = K extends keyof T ? `${K}.${DeepKeys<T[K]>}` : never;
```

The separate type for subkeys here is needed to ensure distribution over `K`.

**Comment by seansfkelley** [comment]
Indeed! Anecdotally, that is far more efficient to respond to autocompletes than the type I was using before. Definitely more readable, too.
