### ISSUE TITLE
`never` cannot be spread into object, but it can be spread into JSX props

### ISSUE THREAD

**Issue by knpwrs** [microsoft/TypeScript#48556]
# Bug Report

### 🔎 Search Terms

- props
- never
- spread

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about jsx, `never`, and spreads. This seems like a design limitation.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEAEBcGcFoEsDmA7A9gJwKYCgDGrlpJRUAjAKwC5RlMA3TdUAXlAG8BfbPAokigEwt2AOjFlyXfIWKYANsIA8AE3h1R4ih1DAAfEA)

### 💻 Code

```ts
// @ts-ignore
const obj: never = {}

const obj2 = {...obj}
const el = <div {...obj} />
```

### 🙁 Actual behavior

As seen in https://github.com/kiliman/remix-params-helper/pull/19, `never` is able to be spread into JSX props, even though `never` cannot be spread into objects. This seems odd to me as both compile to `Object.assign`. See screenshots:

TypeScript prevents spreading `never` into an object:

![image](https://user-images.githubusercontent.com/174864/161621825-ebb5811c-6de2-43cf-85be-a99eb2feec30.png)

But spreading `never` into props works fine:

![image](https://user-images.githubusercontent.com/174864/161621889-7f53556c-b73c-4d41-b62c-5e6665dac05f.png)

### 🙂 Expected behavior

`never` should be prevented from spreading into jsx props, just like it cannot be spread into objects.

**Comment by Josh-Cena** [comment]
I wish spreading `never` is allowed—if anything it should be allowed in objects as well.

`never` extends `object` or any object type, so from a soundness perspective, I don't think this is unsafe. If it is compiled to `Object.assign({}, obj)`, then `obj` being `never` is also fine because it's simply a top-type in parameter. From an ergonomics perspective, I often use `...(props as never)` in some cases where TS can't reason the type properly, like a simple polymorphic component:

```ts
function Comp<T extends "div" | "pre">({
  as: As,
  ...props
}: { as: T } & React.ComponentProps<T>) {
  return <As {...(props as never)} />
}
```

The `never` here reads well to me because props can be naturally seen as function parameters in the context of functional components. If `never` is disallowed here, I'd have to do `(props as any)`, which is undesirable because (a) it's less safe (though not so much) compared to `never` and (b) it's [banned by ESLint](https://typescript-eslint.io/rules/no-explicit-any) for good reason and I don't want to disable it for this particular case.
