### ISSUE TITLE
Inference rejects unbound type variable for function parameter

### ISSUE THREAD

**Issue by rpeszek** [microsoft/TypeScript#48625]
# Bug Report

### 🔎 Search Terms

I done none, the issue is not very searchable

### 🕗 Version & Regression Information

Tested with 4.6.3 and 4.5.2.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PQKhCgAIUgVBlSBLAdgMwKYCcMoMYaQAWAhgM6QAOWA9gEYA2GAthQO5IAuRkKJWtDigDmkAK4o6NCQBMMMyJwCelQgDd+SEowwVONSGgl5OSGikUrdAOkhQQwcODl4G-QkfynzxGkwA8sAB8ABQAlABccE7geOZknJAklJQMSpAAvJCBADSQAEpBkCFoKFEhAPoAjFGwYZlF+fUZRSGcEXVR+Q2GKG1hTsmpSiFEfhjhYUA)

### 💻 Code

I apologize if the issue is known,  I am reporting it because it could indicate a bug in the type inference computation. 

```TypeScript
// Given universally quantified, unbounded <T> 
const hole = <T>(): T => {
    throw new Error("hole"); 
}

const apply = <T, R> (fn: (_1: T) => R) => (t:T): R => fn(t)

//I use  universally quantified <T> as a function type.
//
// But this does not compile 
// 
// Argument of type '(_: never) => never' is not assignable to parameter of type '(_: unknown) => unknown'.
//   Types of parameters '_1' and '_1' are incompatible.
//     Type 'unknown' is not assignable to type 'never'. ts(2345)
apply(hole())
```

Note:
```TypeScript
//This compiles just fine, and would be a good choice for the inferred type for 'fn'
apply(hole<(_: never) => unknown>())

//this compiles with a questionable computed type for 'apply'
//const apply: <unknown, unknown>(fn: (_1: unknown) => unknown) => (t: unknown) => unknown 
apply({} as any)
```

### 🙁 Actual behavior

Code does not compile. 
It appears that the inference algorithm is using variance incorrectly widening instead of narrowing types in the negative position (function params).  

### 🙂 Expected behavior

Code compiles.

**Comment by RyanCavanaugh** [comment]
It looks like you're expecting a unification algorithm of some kind, but that isn't how inference proceeds. When relating generic signatures like this, we use the directional flow of data to inform where candidates can come from, and there's no way for `hole` to know what kind of type it's supposed to produce, so it ends up at `never`, which is correct in its own right because the only legal implementation you can have of `hole` is the one you have - to `throw` (or deadlock).
