### ISSUE TITLE
Array.prototype.filter drops a deferred generic type given by a user-defined type guard

### ISSUE THREAD

**Issue by jfet97** [microsoft/TypeScript#48705]
# Bug Report

### 🔎 Search Terms

filter, type guards, generic

### 🕗 Version & Regression Information

Tested with the nightly version of TS (`4.7.0-dev.20220408`), it has not been fixed yet

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about filter

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=99&jsx=0&ts=4.7.0-dev.20220408#code/JYOwLgpgTgZghgYwgAgKoGdrIN4ChkHJgCeADhAFzIDkArplNQNz6EhwC2ly6YUoAcxaFkcAdxC0OAI2jDCAewQJapOGGAKQVXvxBDcAX1y5QkWIhQBBACYdQOVgRLkq1OHdDMnydlx18gvIEYhJSslDByFAKADbcukFGJhAAHqQKUGBEZCgACtDoWsgAvGgMyAA+yLb2ICy4MLQgCBrFwOgAyuQIwDDACAVQRSAAPAAqyGmQIDboyEMjANrULhDUALoAfAAU5MNaVItaADTI+yPjuVTjAJRUF+3zAKKpfIhgo8cgZ9g5rshJoYto4RFAIGBaFAQOdCloAHRrUolMqPEBXcjJXBpDJZZBNFptGH9WLmb7oCZTN4QWbzb4rNabXZo9BUABKEA8WlixCsUCgcGIXzhIC2ZzRGO4dyor3erWFBx+OH+UuQwKWG1BhAQWl4RAUHOyqJF6HhJPMe1KII63QgvX6gxFe3FIslt1uyBMIgA9N7kDaen0Bt9kDYFBB5gB3TIAax8fR2AbtQcdir2JqWAAYNi7FW6PXgRCIdSA9WjSrDFegsxsfD6-UWAHoAfh8xh84Mh0P1huQvtE8x2soF8ow0F+KpuTDVIOqw4+o1qoAnaynwNuGqxQA)

### 💻 Code

```ts
interface User {
    type: 'user';
    name: string;
    age: number;
    occupation: string;
}

interface Admin {
    type: 'admin';
    name: string;
    age: number;
    role: string;
}

export type Person = User | Admin;

function isSpecificPerson<T extends Person['type']>(person: Person, personType: T): person is Extract<Person, { type: T }> {
    return person.type === personType
}

export function filterPersons<T extends Person['type']>(persons: ReadonlyArray<Person>, personType: T): Extract<Person, { type: T }>[] {
    const toRet = persons.filter(p => isSpecificPerson(p, personType)) 
    return toRet // <-- Type 'Person[]' is not assignable to type '(Extract<User, { type: T; }> | Extract<Admin, { type: T; }>)[]'
}
```

### 🙁 Actual behavior

`toRet`'s type is inferred as `Array<Person>` despite the `isSpecificPerson` type guard

### 🙂 Expected behavior

`toRet`'s type inferred as `Array<Extract<User, { type: T; }> | Extract<Admin, { type: T;}>>`

**Comment by ilogico** [comment]
The problem is that type guards must be explicitly typed and your anonymous function is not (`p => isSpecificPerson(p, personType)`).
You can either add a type annotation to the anonymous function or workaround it  by using a high order function:
```ts
function isSpecificPerson<K extends Person['type']>(personType: K) {
    return (person: Person): person is Extract<Person, { type: K }> => person.type === personType
}
```


[playground](https://www.typescriptlang.org/play?target=99&jsx=0&ts=4.7.0-dev.20220408#code/JYOwLgpgTgZghgYwgAgKoGdrIN4ChkHJgCeADhAFzIDkArplNQNz6EhwC2ly6YUoAcxaFkcAdxC0OAI2jDCAewQJapOGGAKQVXvxBDcAX1y5QkWIhQBBACYdQOVgRLkq1OHdDMnydlx18gvIEYhJSslDByFAKADbcukFGJhAAHqQKUGBEZCgACtDoWsgAvGgMyAA+yLb2ICwmMLQgCBrFwOgAyuQIwDDACAVQRSAAPADSyGmQIDboyEMjANrULhDUALoAfAAU5MNaACq5VOMAlI4iUBBgtFAgyHuFWlSLWmdU+yPIHcgAoqk+IgwKM3iAADQ4HKuZCTQxbUoIr5aAB0a1KJTKyJAx3IyVwaQyWWQTRabQe-Vi5jB6FGhymgIgs3mYJWa02u2x6CoACUIB4tLFiFYoFA4MRQc8QFtIdjcdxDh9-oCxa1JQcIVC1lR6fClhtLoQEFpeEQFHzslipegUZTzDsOt0IL1+oMpU8NfKzhcTCIAPR+n5dHp9AZg5A2BQQeYAd0yAGsfH0HcHnaG3RqPSMvVmTUsAAwbb2GkQEY0gU3Y0rILkFjY+f2B0sAPQA-D5jD5rrd7maLcgA6J5jsAUC1RhoJDsNCFUxkPCqsqxyDaqApzOdUx4Wd9figA)

**Comment by jfet97** [comment]
> The problem is that type guards must be explicitly typed and your anonymous function is not (`p => isSpecificPerson(p, personType)`). You can either add a type annotation to the anonymous function or workaround it by using a high order function:
> 
> ```ts
> function isSpecificPerson<K extends Person['type']>(personType: K) {
>     return (person: Person): person is Extract<Person, { type: K }> => person.type === personType
> }
> ```
> 
> [playground](https://www.typescriptlang.org/play?target=99&jsx=0&ts=4.7.0-dev.20220408#code/JYOwLgpgTgZghgYwgAgKoGdrIN4ChkHJgCeADhAFzIDkArplNQNz6EhwC2ly6YUoAcxaFkcAdxC0OAI2jDCAewQJapOGGAKQVXvxBDcAX1y5QkWIhQBBACYdQOVgRLkq1OHdDMnydlx18gvIEYhJSslDByFAKADbcukFGJhAAHqQKUGBEZCgACtDoWsgAvGgMyAA+yLb2ICwmMLQgCBrFwOgAyuQIwDDACAVQRSAAPADSyGmQIDboyEMjANrULhDUALoAfAAU5MNaACq5VOMAlI4iUBBgtFAgyHuFWlSLWmdU+yPIHcgAoqk+IgwKM3iAADQ4HKuZCTQxbUoIr5aAB0a1KJTKyJAx3IyVwaQyWWQTRabQe-Vi5jB6FGhymgIgs3mYJWa02u2x6CoACUIB4tLFiFYoFA4MRQc8QFtIdjcdxDh9-oCxa1JQcIVC1lR6fClhtLoQEFpeEQFHzslipegUZTzDsOt0IL1+oMpU8NfKzhcTCIAPR+n5dHp9AZg5A2BQQeYAd0yAGsfH0HcHnaG3RqPSMvVmTUsAAwbb2GkQEY0gU3Y0rILkFjY+f2B0sAPQA-D5jD5rrd7maLcgA6J5jsAUC1RhoJDsNCFUxkPCqsqxyDaqApzOdUx4Wd9figA)

I see, thanks!
