### ISSUE TITLE
Compiling with tsc under monorepo will include the package content corresponding to paths

### ISSUE THREAD

**Issue by chnliquan** [microsoft/TypeScript#48715]
# Bug Report

### 🔎 Search Terms

- pnpm
- monorepo

### 🕗 Version & Regression Information

- This is a crash

### 💻 Code

https://github.com/chnliquan/tsc-monorepo

1. Download

```bash
$ git clone git@github.com:chnliquan/tsc-monorepo.git
```

2. Install

```bash
$ pnpm i
```

3. Compile

```bash
$ cd packages/web & npx tsc -p tsconfig.build.json
```

### 🙁 Actual behavior

when tsc is used to compile the `utils` subpackage, the content of `utils/src` will be generated in the lib folder, its correct.

when tsc is used to compile the `web` subpackage, the total utils and web will be generated in the lib folder.

Note：The `paths` option in the `tsconfig.json` is to get the correct dependencies at compile time

### 🙂 Expected behavior

when compiling the `web` subpackage with tsc, only the content below `web/src` is generated under lib, the compilation of `utils` should not be included

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
