### ISSUE TITLE
Why tsc wont check type of references project

### ISSUE THREAD

**Issue by lovetingyuan** [microsoft/TypeScript#48717]
Why tsc wont check type of references project?

I think tsc should follow `references` projects and perform type checking of them.

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
