### ISSUE TITLE
[4.7 Beta/Dev] import.meta reports invalid "Cannot find name 'meta' ts(2304)" error

### ISSUE THREAD

**Issue by Jamesernator** [microsoft/TypeScript#48731]
# Bug Report

### 🔎 Search Terms

"Cannot find name 'meta'" "2304"

### 🕗 Version & Regression Information

- This is an issue with new "nodenext" support

### ⏯ Playground Link

The issue doesn't present in the playground (however it has it's own issues with the code sample).

Instead [here is a repo with the issue](https://github.com/Jamesernator/ts-import-meta-issue).

### 💻 Code

```ts
const u = new URL(import.meta.url);
```

### 🙁 Actual behavior

It produces the error:

```
Cannot find name 'meta'.ts(2304)
```

The error vanishes if you edit `tsconfig` in any way, however if you then edit the file again it reappears.

![Screenshot from 2022-04-17 05-23-48](https://user-images.githubusercontent.com/8518303/163685182-175d423e-7216-4529-a243-d64b0dfee06f.png)

While this error is shown, the rest of the behaviour of `import.meta` is still fine, like the type is correct and such.

### 🙂 Expected behavior

There should be no error.

**Comment by weswigham** [comment]
Looks like this is another services issue that flew under the radar when we had separate services and error-reporting checkers - our symbol lookup logic for `import.meta` is incorrect and triggers a diagnostic in the process of doing the wrong thing. (It looks up `meta` inside the global `ImportMeta` type, fails that (naturally), then falls back to looking up `meta` in the surrounding scope, wat. I have to assume we have no tests for goto-def on the `meta` in `import.meta`!) As usual with issues like this, I think the fix is pretty simple (correct the logic in `getSymbolAtLocation` for meta properties), but the test for the regression is going to be just a bit more annoying to write than usual (since it essentially requires a test that requests diagnostics after requesting symbols for the file).

**Comment by weswigham** [comment]
Lol, we _do_ have tests for goto-def for `import.meta`, they just all expect to fail with a missing symbol (?!), even though there was (incorrect) logic to look up a symbol in place. Looks like #44364 and #45031 didn't actually mesh all that well together.
