### ISSUE TITLE
Convert react to react default when use "module": "commonjs"

### ISSUE THREAD

**Issue by lalLAL95828** [microsoft/TypeScript#48778]
tsconfig.json
```js
{
    "compilerOptions": {
      "outDir": "lib",
      "module": "commonjs",
      "target": "es5",
      "declaration": true,
      "jsx": "react",
      "moduleResolution":"Node",
      "allowSyntheticDefaultImports": true,
      "skipLibCheck": true,
    },
    "include": [
        "src"
    ],
    "exclude": [
    "src/**/*.test.tsx",
    "src/**/*.stories.tsx",
    "src/setupTests.ts",
    "src/stories/"
    ]
  }
```

out
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CatarcUIContextProvider = exports.CatarcUIContextConsumenr = exports.CatarcUIContext = void 0;
var react_1 = require("react");
var catarcUIdefaultProps = {
    // exist:false,
    classNamePrefix: "catarc-ui",
    theme: {
        "primary": "primary",
        "success": "success",
        "warning": "warning",
        "danger": "danger",
        "catarc": "catarc",
    }
};
exports.CatarcUIContext = react_1.default.createContext(catarcUIdefaultProps);
exports.CatarcUIContextConsumenr = exports.CatarcUIContext.Consumer;
exports.CatarcUIContextProvider = exports.CatarcUIContext.Provider;

```

**Comment by lalLAL95828** [comment]
error TypeError: Cannot read properties of undefined (reading 'createContext')  when use jest

**Comment by Josh-Cena** [comment]
You need to turn on `esModuleInterop`, or use `import * as React from "react"`

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
