### ISSUE TITLE
`globalThis` sometimes being stripped from type emition can leads to errors in emited definition

### ISSUE THREAD

**Issue by LeonardDrs** [microsoft/TypeScript#48783]
# Bug Report

### 🔎 Search Terms

globalThis, removed, remove, stripped, 2502, own type annotation, referenced, definition, .d.ts

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, since 3.5.1, and I reviewed the FAQ for entries about globalThis, 2502, own type annotation

### ⏯ Playground Link

[Playground link with relevant code, mainly using the `D.TS` tab](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220420#code/PTAEDoBNwFwZ1AMwJYBsCmoDmyBu64AoEUAckXRgGMALU0ZBAJ3QpYDsr1JRJkWqMVAE9QAeyYN2fAUNHJ2DeOIDuimMIAOmAIbt2YmDpjIx7cKAAUAJgCsABmsBKYmHQAPTRJi90VVDosoFRmcD4U1DQAymIAtpQ0ClgAXFYRtKka2mKISJS0TqAAvAB8oFnoOXmRANyEHl5MPiHsYdW0MfEwiexYxVaEAJDpNJlalblYqGIARjqoACqJcOAjhE5j2ZPTc4vLq-k0xWVrrqBLjKAqEgDWgWIArtJXt3AANKAABlOz8xdwnwYCE0LDg6HYMHqnm8wVC4UOnQSSQA6rckqlLCNNhNsDs-vsRoVSuVxlUfrt-gdIv1MYciSdDnUzv9QDd0OhNAhkMpvni9oxASw2OCuFDGj4KqAAGIIuJI3r9ADeQyxJK2uN+-JWawAvoQxTD-Do4AgZZFEd0kgBhAIm0DK4aHAD82LJfMpuv1DRhkrNHTllt6UqeglMiiKaUOru2mo9dOOapx5PxjCptCAA)

### 💻 Code

```ts
export const fetchSomething = (
	fetch: typeof globalThis.fetch
): typeof globalThis.fetch => fetch
```

### 🙁 Actual behavior

This code will generate the following `.d.ts` file, which contains the `'fetch' is referenced directly or indirectly in its own type annotation. (2502)` error
```ts
export declare const fetchSomething: (fetch: typeof fetch) => typeof fetch;
```

### 🙂 Expected behavior

Generated d.ts file should keep the reference to `globalThis`
```ts
export declare const fetchSomething: (fetch: typeof globalThis.fetch) => typeof globalThis.fetch;
```
as it does when declaring a function, type or class:
```ts
export type FetchSomething = {
	fetch: typeof globalThis.fetch
}

export class FetchSomethingClass {
	fetch?: typeof globalThis.fetch
}

export type FetchSomethingFunction = (fetch: typeof globalThis.fetch) => typeof globalThis.fetch

// .d.ts
export declare type FetchSomething = {
    fetch: typeof globalThis.fetch;
};
export declare class FetchSomethingClass {
    fetch?: typeof globalThis.fetch;
}
export declare type FetchSomethingFunction = (fetch: typeof globalThis.fetch) => typeof globalThis.fetch;

```

### :thinking:  Workaround

Typing the const instead of the anonymous function works as expected.
```ts
export const fetchSomething: (fetch: typeof globalThis.fetch) => typeof globalThis.fetch = (fetch) => fetch;
```

**Comment by jakebailey** [comment]
It looks like this applies to in any case where the function type is inferred from an arrow function (and probably function expression too?). The below shows a number of variations that break in `d.ts` emit, but also show the wrong thing in the tooltip (shown via `// ^?`).

[Playground Link](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEBzCB7ARlC8DeBYAUAJAB2UAtiAM4AOUYCAZiijgYYWCsZQC7wYwAXPGIBXMmhAwA3GwC+bBqOJgeASy7wmKABQBKYQDcUa4LPwL8BEAA9qKGH07c+a4gylxgAFQCe1BABeeB1tYR5-EBQGJFQMCG8ACzVKADptA3gIgOjY9EwklPTmeECAPi1mcwB6avh6hsb6gD0AfgJrOwcnLl54Nw8YLz8AgCZSkLCsyNzkfITktO0AGn5YVvCZmLn4wqXmTOyo7biCxeKWcrWYeFbWypQauqaXto78W3tHeGc+gc8QD5IgBBYjAABKIB4ohgxAmoWYmxyJ3mewuelKFW0Txer3aVg+XW+v1c7gBQICoIhUJhxHGwQRKCRxzyu3OK2uG2myNZZyKGSuAlu92xBFquKabwJ4oAqioUGQKMQ+BR4FAwSIUDwEIkUAB3LKJBBQNAoQzGjU8I3wYCpHiUeAgMhqJyJdWIKipMV1T7dH7QSgO7Q4SxAA)

The main issue seems to be that we don't set the enclosingDeclaration to the arrow function when converting its signature to a type node; doing so _almost_ fixes the bug but changes all sorts of other tests (honestly, many in positive ways, with a few confusing breaks). However, we then emit `global.fetch` (or similar) and not `globalThis.fetch`. The former errors out saying that `global` is not available.

You can actually see this result if you declare something at the module level with the same name; then we do the right thing (because we see the arrow function's parent and decide to write it explicitly) except that `globalThis` becomes `global` which is weird. My example above shows this if the last line is uncommented.
