### ISSUE TITLE
ts.getResolvedModule cannot be used to get ambient modules

### ISSUE THREAD

**Issue by zelliott** [microsoft/TypeScript#48807]
# Bug Report

### 🔎 Search Terms

getResolvedModule ambient module

### 🕗 Version & Regression Information

This repros on the latest version of TypeScript, and I don't believe it's ever worked on previous versions.

### ⏯ Playground Link

See repro steps in linked https://github.com/microsoft/rushstack/issues/3335.

### 💻 Code

```
// index.d.ts
import './modules';
export { Foo } from 'foo';

// modules.d.ts
declare module 'foo' {
    class Foo {}
}

// some_other_file.ts
ts.getResolvedModule(indexSourceFile, 'foo');  // returns `undefined`
```

The helper `ts.getResolvedModule` is found at https://github.com/microsoft/TypeScript/blob/v3.2.2/src/compiler/utilities.ts#L218.

### 🙁 Actual behavior

`ts.getResolvedModule` does not seem to return the resolved module for ambient modules.

### 🙂 Expected behavior

I'd expect this helper to return the resolved module.

**Comment by andrewbranch** [comment]
Ambient modules are not “resolved” like other imports/references during module resolution, as we haven’t processed all files yet, and the declaration could be anywhere. Module resolution is concerned only with what can be found on the filesystem, and pulling those resolutions is what this API is supposed to do. Ambient module declarations get symbols in the global scope (just like any other declaration in a non-module file) during binding, and when a type checker is initialized, those symbols get merged into one big global symbol table. Only then do we know what ambient modules exist, and so module name resolution in the checker begins by querying those global symbols before trying the filesystem resolutions that you’re looking at. TLDR, the API is doing exactly what it’s supposed to, and it would be impossible for it to do what you want because it doesn’t accept a TypeChecker parameter.

**Comment by zelliott** [comment]
Thanks for the quick response @andrewbranch, that makes sense.

Maybe you can help me find an alternative TS compiler API to solve my problem. The @microsoft/api-extractor package uses the TS compiler to (1) determine if import/export statements are "external" to the current package (via `ResolvedModuleFull.isExternalLibraryImport`) and (2) get the corresponding exported declaration for a given import/export statement (e.g. get `Foo` for `import { Foo } from 'foo'`).

For an import/export of an ambient module, what helpful TS compiler APIs are available to do these two things? If this isn't the right forum for these questions, no worries (maybe the issue linked above is better). Thanks again!

**Comment by andrewbranch** [comment]
For just module specifiers, should probably be using `checker.resolveExternalModuleName`, and check if any/all of the declarations of the symbol returned are in node_modules, or not in the project’s root files, or whatever your specific use case requires. For imported symbols like `Foo` in your example, you should use `checker.getAliasedSymbol` and do the same.

**Comment by zelliott** [comment]
Is `checker. resolveExternalModuleName` exposed to the public? I'm on TS 4.5.5 and don't see it on the `TypeChecker` interface. There's also a code comment on the api-extractor repo that says:

> Map the filename back to the corresponding SourceFile. This circuitous approach is needed because we have no way to access the compiler's internal resolveExternalModuleName() function

**Comment by andrewbranch** [comment]
Hm sorry, I didn’t notice that function was internal. `checker.getAliasedSymbol` should cover all the cases where the import declaration has at least one name binding. I think you can use `checker.getSymbolAtLocation` on the string literal of the module specifier, which dispatches to `resolveExternalModuleName`.
