### ISSUE TITLE
[perf] Full instantiation of anonymous object types could be avoided

### ISSUE THREAD

**Issue by Andarist** [microsoft/TypeScript#48827]
I've seen this pattern in libraries like [`ts-toolbelt`](https://github.com/millsp/ts-toolbelt):
```ts
export type Compute<A extends any, depth extends Depth = 'deep'> = {
    'flat': ComputeFlat<A>
    'deep': ComputeDeep<A>
}[depth]
```

[Source code](https://github.com/millsp/ts-toolbelt/blob/319e55123b9571d49f34eca3e5926e41ca73e0f3/sources/Any/Compute.ts#L58-L61)

And I've wondered if the compiler can "pattern match" this and only instantiate the value that is going to be selected. It turned out that it doesn't - so I'm proposing a change to optimize this because it should be fairly easy to avoid full instantiation of such an object type.

**Comment by ahejlsberg** [comment]
> And I've wondered if the compiler can "pattern match" this and only instantiate the value that is going to be selected.

Do you have an actual test or scenario where you're seeing degraded performance because of this? Keep in mind we never do a "full" instantiation of anything because that'd immediately blow up on infinite recursive types. In this particular scenario, the "full" instantiation simply amounts to creating instantiated symbols for each of the members (so, in this case, two symbols). Resolution of the types of the symbols is deferred, so we never actually instantiate the types unless someone asks. And, if the `depth` type parameter is always `deep`, we only instantiate `ComputeDeep<A>`.
