### ISSUE TITLE
Regression causes Function top-type to be callable with no arguments

### ISSUE THREAD

**Issue by webstrand** [microsoft/TypeScript#48840]
# Bug Report
### 🔎 Search Terms

function top type callable spread never regression

### 🕗 Version & Regression Information

- This changed between versions 3.8.3 and 3.9.7

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=3.9.7#code/CYUwxgNghgTiAEEQBd4DMD2GBc8AUAdEbAOYDOuAdiAG4gwCU8AvAHzw0YCWwA3AFCYMLfAA9cZZDC6USTNvADeAXwFC8DXvHgB6HfErD6MDDCA)

### 💻 Code

```ts repro
declare let foo: (...args: never) => void;
foo = (x: string) => {};
foo();  // no error
```

### 🙁 Actual behavior

`foo()` was permitted.

### 🙂 Expected behavior

`foo()` should not be permitted because it is unsafe. `(...args: never) => unknown` behaves as the top-type for all functions; all function types are assignable to it. So calling it will lead to unsafe behavior by functions expecting 1 or more arguments.

**Comment by andrewbranch** [comment]
@typescript-bot bisect good v3.8.3 bad v3.9.7

**Comment by andrewbranch** [comment]
I think this aliasing unsoundness is actually unrelated to whether `(...args: never) => void` is callable. Consider `(...args: never[]) => void` or even `(...args: string[]) => void`. The assignment to `foo` in your example would still work, and yet these types are obviously callable with no arguments.

**Comment by webstrand** [comment]
I've always considered this to be the distinction between `(...args: never) => unknown` and `(...args: never[]) => unknown`. The latter _has_ to be callable with no arguments because `never[]` is assignable from `[]`.

**Comment by webstrand** [comment]
```ts
declare let foo: (...args: never[]) => void;
foo = (x: string) => {};
```
makes sense, fundementally, because `[string]` is assignable to `never[]`

**Comment by andrewbranch** [comment]
> Otherwise, without `(...args: never) => unknown`, there is no top-type for all functions.

Well, `(...args: never[]) => unknown` is still a function top type in that every other function type is assignable to it (the two formulations in question are cross-assignable). But it does feel like you ought to be able to express a function type constraint that is itself not callable because you have no idea what to pass it 🤔

**Comment by webstrand** [comment]
For real-world use, this most commonly shows up in my code like
```ts
function foo<T extends (...args: never) => unknown>(fn: T) {
    fn(); // no error
}
```
or
```ts
const registry = new Map<(...args: never) => unknown, unknown>();
for(const [fn, data] of registry) {
    fn(); // no error
}
```

**Comment by andrewbranch** [comment]
> Well, `(...args: never[]) => unknown` is still a function top type in that every other function type is assignable to it

Actually I found a counterexample from AnyhowStep by reading around https://github.com/microsoft/TypeScript/issues/48840#issuecomment-1109002426

**Comment by jack-williams** [comment]
> ```ts
> declare let foo: (...args: never[]) => void;
> foo = (x: string) => {};
> ```
> 
> makes sense, fundementally, because `[string]` is assignable to `never[]`

Function arguments are related in the other direction. For this to make sense, `never[]` needs to be assignable to `[string]`.
```typescript
let x: (...args: never[]) => unknown = () => {}
const y: (...args: ["one arg"]) => unknown = (x) => alert(x.charCodeAt(0))

x = y;

try {
  x() // throws
} catch(e) {
  alert(e)
}
```

I think it is just broken that `(...args: never) => unknown` is callable.

**Comment by tjjfvi** [comment]
It seems there are two different unsoundnesses being discussed here:
```ts
declare let foo: (...args: never) => void;
foo(); // should error (`[]` isn't assignable to `never`), but does not
```
```ts
declare let foo: (...args: never[]) => void;
foo = (x: string) => {}; // should error (`never[]` isn't assignable to `[string]`), but does not
```
Both of these unsoundnesses relate to a top function type being callable; however, the correct fix for the former is to make the type `(...args: never) => void` uncallable but still a top function type, while the correct fix for the latter is to make the type `(...args: never[]) => void` not a top function type but still callable.

**Comment by RyanCavanaugh** [comment]
We shouldn't even let you write `declare let foo: (...args: never) => void;`. It doesn't make sense.

The second assignment isn't unsound. What is your proposed demonstration of unsoundness here?

**Comment by tjjfvi** [comment]
> We shouldn't even let you write `declare let foo: (...args: never) => void;`. It doesn't make sense.

Are you saying that the type `(...args: never) => void` doesn't make sense and should be removed? It seems perfectly logical as a top function type; the type of `...args` is, in a sense, the intersection of all possible argument types, which is `never`. You can't call a function of type `(...args: never) => void`, because you don't know what arguments it takes, but you know that it is something that could be theoretically called, you just don't know what it could be called with. It's like `{}` being the top type of property-bearing things; you can't directly access properties on it, because you don't know what properties it might have, but you know that it has properties that could theoretically be accessed.

> The second assignment isn't unsound per our definition of rest args being assumed to have sufficient arity (or more accurately, it's unsound in the way that all rest args / finite parameter lists are unsound)

Ah, good point.

**Comment by RyanCavanaugh** [comment]
Upon further reflection, I think you're right about `(args: never)`

**Comment by jcalz** [comment]
So, just running into this again, presumably `declare const f: (...args: never[]) => unknown` should allow `f()` because `[]` is assignable to `never[]`, but `declare const g: (...args: never) => unknown` should not allow `g()` because `[]` is not assignable to `never`.  And therefore `(...args: never) => unknown` is a top type for functions but `(...args: never[]) => unknown` shouldn't be.  

Right now both types are callable with no arguments and both of these are considered top types for functions.  Which of these can we fix without breaking everyone?

**Comment by webstrand** [comment]
I've been using and teaching `(...args: never) => unknown` as the supertype of all callables.

**Comment by jcalz** [comment]
Would it break the universe if we stopped `(...args: never[]) => unknown` from being considered a top type? No function that requires an argument should be assignable to it.  (e.g., `const f: (...args: never[])=>unknown = (x: string) => x.toUpperCase(); f();` compiles and explodes at runtime.) I'm guessing it's been used as a top type in various real-worldy places and these would be broken if the change were made.  But I'd at least like to see an official "we know this is unsound but it's too late to touch it now" comment somewhere I can refer people to.

**Comment by mkantor** [comment]
@jcalz are you talking generally about assigning to functions with rest parameters (so stuff like [this](https://www.typescriptlang.org/play/?#code/MYewdgzgLgBAZgLhgCgHToIYCcDmEnRYCWYOA2gLoCUMAvAHwyEk50wZ2MapQgCqABwEBTLAGEMEYcioBYAFBwZMAPQqYAIxAgAtkA) would also become illegal under your proposal)? Or are you suggesting that `never[]`-typed rest parameters be special-cased?

If it's the former, see discussion in #9352 and #58552 for rationale. Apparently this hole was plugged in a historical version of TypeScript (I was unable to determine which) and people complained. Also some standard APIs like [`String#replace`](https://github.com/microsoft/TypeScript/blob/833a8d492c728d606454865e8c0fee84842f9f10/src/lib/es5.d.ts#L452) basically expect this sort of thing to be allowed (I personally wouldn't mind being forced to use optional parameters with APIs like that, but then again I'm also the kind of masochist who enables `--noUncheckedIndexedAccess`).
