### ISSUE TITLE
Does it make sense to allow `module: nodenext` + `moduleResolution: node`?

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#48854]
In https://github.com/microsoft/TypeScript/issues/48835, a user ran into an issue where the combined options were questionable. It seems like an innocent mistake, and by all means `moduleResolution: node` sounds compatible with `module: nodenext` or `moduleResolution: node`.

Should we issue an error in some of these cases?

CC @weswigham @andrewbranch

**Comment by weswigham** [comment]
So it is _technically_ a useful configuration - we won't detect any esm files (since the resolution mode is pre-esm), but we _will_ use the new cjs transform (ie, leaving dynamic import alone) on all the input modules.

**Comment by craigphicks** [comment]
Apart from the question of whether that combination should be allowed, I believe there is an issue of accidental confusion over the roles of *module* and *moduleResolution*.  Both include allowed values of *node12* and *nodenext*.  

The [man page for "module Resolution"](https://www.typescriptlang.org/docs/handbook/module-resolution.html) begins with 
> Module resolution is the process the compiler uses to figure out what an import refers to. Consider an import statement like import { a } from "moduleA"; in order to check any use of a, the compiler needs to know exactly what it represents, and will need to check its definition moduleA.

There is nothing in that statement that lets the user know that the *moduleResolution* can be critical in generating correct module output.  However, in fact it is the *moduleResolution* setting to *node12* or *nodenext* (internally `ModuleResolutionKind.Node12` or `ModuleResolutionKind.NodeNext`) that enables the *package.json:type* value to determine the default output (which can be overridden by *cts* or *mts* source extensions).

There is a property `SourceFile["impliedNodeFormat"] ` which is correctly set to determine the final output, but only when moduleResolution* is set to *node12* or *nodenext*.  Otherwise it is *undefined* and *compilerOptions.module* should be/ will be referenced.  

However, even the source documentation for SourceFile["impliedNodeFormat"] appears possibly confused:

        /**
         * When `module` is `Node12` or `NodeNext`, this field controls whether the
         * source file in question is an ESNext-output-format file, or a CommonJS-output-format
         * module. This is derived by the module resolver as it looks up the file, since
         * it is derived from either the file extension of the module, or the containing
         * `package.json` context, and affects both checking and emit.
         *
         * It is _public_ so that (pre)transformers can set this field,
         * since it switches the builtin `node` module transform. Generally speaking, if unset,
         * the field is treated as though it is `ModuleKind.CommonJS`.
         */
        impliedNodeFormat?: ModuleKind.ESNext | ModuleKind.CommonJS;

I believe clarity demands that should be written starting with *When `moduleResolution` is `Node12` or `NodeNext`*

Here is the source code where the value for *SourceFile.impliedNodeFormat* is determined:
```
export function getImpliedNodeFormatForFile(fileName: Path, packageJsonInfoCache: PackageJsonInfoCache | undefined, host: ModuleResolutionHost, options: CompilerOptions): ModuleKind.ESNext | ModuleKind.CommonJS | undefined {
        switch (getEmitModuleResolutionKind(options)) {
            case ModuleResolutionKind.Node12:
            case ModuleResolutionKind.NodeNext:
                return fileExtensionIsOneOf(fileName, [Extension.Dmts, Extension.Mts, Extension.Mjs]) ? ModuleKind.ESNext :
                    fileExtensionIsOneOf(fileName, [Extension.Dcts, Extension.Cts, Extension.Cjs]) ? ModuleKind.CommonJS :
                    fileExtensionIsOneOf(fileName, [Extension.Dts, Extension.Ts, Extension.Tsx, Extension.Js, Extension.Jsx]) ? lookupFromPackageJson() :
                    undefined; // other extensions, like `json` or `tsbuildinfo`, are set as `undefined` here but they should never be fed through the transformer pipeline
            default:
                return undefined;
        }
```

I think it would be worth explicit mention in the documentation for both *module* and *moduleResolution* that it is *moduleResultion* (and not *module*) that must be set to *node12* or *nodenext* in order to generate output according to value of *package.json:type* (but allowing cts and mts extension overrides).

**Comment by magicdawn** [comment]
the moduleResolution option naming is bad, `classic` & `node` is well documented on page https://www.typescriptlang.org/docs/handbook/module-resolution.html

but not node12/nodenext(now node16/nodenext), and not updated on [tsconfig reference page](https://www.typescriptlang.org/tsconfig#moduleResolution)


![image](https://user-images.githubusercontent.com/4067115/180510481-4ac75e13-c921-42a2-b502-d9c524f8f7d7.png)

the `node12` / `node16` / `nodenext` should be renamed to `node-esm` and points a link to the Node.js ESM resolve spec https://nodejs.org/dist/latest-v16.x/docs/api/esm.html#resolver-algorithm-specification

**Comment by andrewbranch** [comment]
Strongly disagree. The TSConfig reference docs should change. `node16`/`nodenext` is the only correct module resolution option if you are targeting Node 16+ (really 12+ with some caveats about async/await and certain package.json `exports` features). `node16`/`nodenext` do not imply that everything uses ESM resolution; they simply correspond to versions of Node where ESM is available side-by-side with CJS. The resolution algorithm switches between CJS (more or less what you get all the time in `--moduleResolution node`) and Node’s new ESM resolver algorithm based on the input type that Node will see for the given import, which varies based on package.json `type`, file extension, and import syntax. Even if you are using exclusively CJS source and dependencies in Node 12+, using `--moduleResolution node` would be incorrect because it doesn’t respect package.json `exports`, while CJS resolution in Node 12+ does. Eventually, I would like to rename `node` to something that implies it’s only suitable for legacy code.
