### ISSUE TITLE
Key in mapped variadic tuple should not be literal after the variadic part

### ISSUE THREAD

**Issue by Josh-Cena** [microsoft/TypeScript#48856]
# Bug Report

### 🔎 Search Terms

Variadic tuple mapped type keyof

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2#code/C4TwDgpgBA0hIGcA8B5KEAewIDsAmCUArjgNY4D2A7jgNoC6AfFALxQDeUtMUAljlFLwKAMygp6ALlhQAvgG4AUItCQoAQVax4yWgmAAnfgHMANFAB0V-UZzGGTJQHonUNwD0A-CvDQAQlpwiEh6hibmVhY2JgzmOEQAtgBGEAaOii5uUF6KQA)

### 💻 Code

```ts
type Keys<O extends unknown[]> = { [K in keyof O]: K };

type A = Keys<[string, ...string[]]>;
type B = Keys<[string, ...string[], number]>;
```

### 🙁 Actual behavior

`A` and `B` both have the variadic part typed as `..."1"[]`, which is wrong. `B` is further wrong because the `number` part becomes `"2"`, while in practice it would rarely be `"2"`.

### 🙂 Expected behavior

`A` should be `["0", ...number[]]`; `B` should be `["0", ...number[], number]`

**Comment by ahejlsberg** [comment]
I don't think this is a bug. Consider:

```ts
type Box<T> = { value: T };
type Boxified<T> = { [P in keyof T]: Box<T[P]> };

type T0 = Boxified<[number, string, ...boolean[]]>;  // [Box<number>, Box<string>, ...Box<boolean>[]]
```

With the proposed change, `P` would be `number` instead of `"2"` for the rest element, which means the resulting rest element would be `...Box<string | number | boolean>[]` instead of just `...Box<boolean[]>`. Not only is that less correct, it is a breaking change. Effectively, `number` is a less precise way of expressing "element at index 2 or above", whereas `"2"` gets much closer. This speaks to the fact that in homomorphic mappings over array and tuple types, the key types are just exemplars and not an exact representation of some specific property.

**Comment by Josh-Cena** [comment]
I also thought about that. The problem is it's really hard to be correct for both the key type itself, and for homomorphic mapped types to continue be homomorphic. However, accessing `T[P]` and `P` directly should be two orthogonal actions. In my actual case, I'm doing `Entries` instead of `Keys`:

```ts
export type Entries<O extends unknown[]> = { [K in keyof O]: [K, O[K]] };
```

In an ideal world, I'd like `Entries<[number, string, ...boolean[]]>` to be `[["0", number], ["1", string], ...[number, boolean][]]`. Does that sound reasonable?

**Comment by ahejlsberg** [comment]
@Josh-Cena FWIW, I now agree with your observations and suggested changes. See #57031. Better late than never! 😄
