### ISSUE TITLE
Implement the updated JS decorators proposal

### ISSUE THREAD

**Issue by arackaf** [microsoft/TypeScript#48885]
# Suggestion

Implement Decorators!

## 🔍 Search Terms

TypeScript Decorators

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

Decorators

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

Not sure - this would be badly breaking against your legacy decorators feature, but I think it meets the goal to align TS with JS

## ⭐ Suggestion

The TypeScript proposal is now Stage 3!!!

https://github.com/tc39/proposal-decorators

We've all seen the issue from hell requesting better typing support for decorators 

https://github.com/microsoft/TypeScript/issues/4881 

but now that the proposal is moving forward, currently at Stage 3, I thought I'd open this issue to see if there are plans to finally, fully implement (and type) the ES version of decorators. 

## 📃 Motivating Example

N/A - just implementing new JS features, to keep JS and TS aligned. 

## 💻 Use Cases

All the various ways decorators can be used.

**Comment by DanielRosenwasser** [comment]
I think the first step will be implementing decorators. We're not going to try to model the "decorators can change the types of things" portion at first, but I think we can get something good and working.

**Comment by arackaf** [comment]
@DanielRosenwasser that sounds perfect. 

But just to be clear, annotating how a decorator change’s a type will be on the roadmap long term?

**Comment by glen-84** [comment]
Shhh, don't say "long term". 😉

**Comment by wycats** [comment]
@DanielRosenwasser the biggest "type-related" transformation that comes up for me in the current implementation of decorators is communicating that a field decorator initializes the field's value.

I **think** that this would just fall out of `accessor` decorators (since the decorator turns into a getter, the concept of an uninitialized value no longer makes sense). Is that right?

Also, a regular field decorator might still want to communicate that the value is initialized (for example, a decorator that implements a default by returning a new initializer). Is it possible to address the issue of communicating that a decorator initializes the value on a different timeframe than arbitrary type transformation, or is it just as hard?

**Comment by Jamesernator** [comment]
> We're not going to try to model the "decorators can change the types of things" portion at first, but I think we can get something good and working.

Simple transforms should be easy enough right? 

Like:

```js
function wrapInBox<R>(f: () => R): () => { value: R } {

}

class Foo {
    @wrapInBox
    method(): R {
        
    }
}

const foo = new Foo();
foo.method().value;
```

Has very little difference to:

```js
class Foo {
    method = wrapInBox(() => {
    
    });
}
```

(Other than prototype vs own property, but that doesn't impact the difficulty for the type system).

Isn't it primarily the metadata-based type-mutations that are hard to actually support? (given they need to communicate types *across* calls)

**Comment by trusktr** [comment]
> @DanielRosenwasser that sounds perfect.
> 
> But just to be clear, annotating how a decorator change’s a type will be on the roadmap long term?

Besides this, also [picking types from a class by specific decorator](https://github.com/microsoft/TypeScript/issues/48413) would be wonderful... in the longer term. :D

**Comment by trusktr** [comment]
> Also, a regular field decorator might still want to communicate that the value is initialized (for example, a decorator that implements a default by returning a new initializer). Is it possible to address the issue of communicating that a decorator initializes the value on a different timeframe than arbitrary type transformation, or is it just as hard?

So like,

```js
class Foo {
  @alwaysString foo = 123 // initializes it to "123"
}
```

I think TypeScript would create the type right then and there, at class definition. The user cannot (write any code that will) 
observe a moment when the value is a number instead of a string, apart from the decorators themselves.

Another thing could be that maybe decorators can augment the type of a class, but not necessarily the type of the thing they decorate directly. For example, this

```js
class Foo {
  @withDouble count = 123
}
```

could add a new `doubleCount` variable that is always the double of `count` whenever `count` changes. The type would be `{ count: number, doubleCount: number }` where `count` was not modified.

However, I think that with this new decorator API, decorator functions can be completely generic, with their input and output types completely known by TypeScript. So, this should be possible:

```js
function alwaysString<T, C extends ...>(_: T, context: C): (initial: T) => string {
  if (context.kind !== 'field') return // type narrowing based on union of string values for `kind`

  return initial => initial.toString()
}
```

and based on something like this, I imagine it totally possible for TypeScript to look at the return type and determine that the final type of the property should always be a `string` (or to always have any setter, string getter).

But a version with class types not modifiable would still be totally usable!

**Comment by ruojianll** [comment]
I suggest implement decorators first, then add type support. The current legacy class decorator could return a non-class constructor value, and it won't be recognized by ts type system, but it is still easy to use.

**Comment by wycats** [comment]
> I suggest implement decorators first, then add type support

As long as `@dec accessor foo` understands that you don't need to explicitly initialize `foo`, I think I can live with that.

**Comment by wycats** [comment]
I wonder if the narrow case of initializer mapping might be more doable than other kinds of changes caused by decorators.

**Comment by DanielRosenwasser** [comment]
This is kind of what I've been thinking recently. I can imagine a world where

* decorators can support a more-derived type than the initializer of a field
* a type annotation on a field has to 100% match the type returned by the decorator

It's enough to help with auto-initialization (which is just removing `undefined` from a type) and creating more-specialized types (which is turning something like `[1, 2, 3]` into a `WatchedArray<number>`/`ReactiveArray<number>` instead of an `Array<number`).

The reason for the latter bullet is being able to support something along the lines of https://github.com/microsoft/TypeScript/issues/47947, along with some other precedent we have (e.g. async functions need to say they return a `Promise<ThingBeingReturned>` rather than `ThingBeingReturned`, and the wishful thinking in `--exactOptionalProperties`).

**Comment by DanielRosenwasser** [comment]
It's, uh, also not compatible with decorator metadata.

**Comment by trusktr** [comment]
> decorators can return a more-derived type than the initializer of a field

This part works:

```js
class Foo {
  @reactive array = [1, 2, 3] // converts to ReactiveArray<number> for example
}
```

But what about this?

```js
const f = new Foo

f.array = [4, 5, 6] // Should also accept a plain array and convert to a (or map to the) `ReactiveArray<number>`
```

**Comment by trusktr** [comment]
Also what about this case, which is a real case in my case, namely for attribute processing with custom elements:

```js
class MyEl extends HTMLElement {
  // also accepts strings (f.e. from HTML attributes)
  @reactive coords = "1 2 3" // converts to ReactiveArray<number> for example
}

customElements.define('my-el', MyEl)

const el = new MyEL

el.array = [4, 5, 6] // Should also accept a plain array and convert to a (or map to the) `ReactiveArray<number>`
el.array = "7 8 9" // Should also accept a string with space-separate list of numbers and convert to a (or map to the) `ReactiveArray<number>`
el.array // `ReactiveArray<number>`
```

**Comment by trusktr** [comment]
Hmm, now that I think about it, maybe an `accessor` is all that is needed, because the decorator would then receive an object with `get` and `set` functions. The decorator could define each one of those to have separate types, just like class getters/setters currently can.

Example:

```js
// some-custom-element-lib
export function numberAttribute() {
  return {
      get(): ReactiveArrayTriplet<number> {
        // ...
      },

      set(val: `${number} ${number} ${number}` | [number, number, number] | ReactiveArrayTriplet<number>) {
        // ...
      },
  }
}
```

```js
import {numberArray} from 'some-custom-element-lib'

class MyEl extends HTMLElement {
  // also accepts strings (f.e. from HTML attributes)
  @numberArray accessor coords = "1 2 3" // converts to ReactiveArray<number> for example
}
```

In this case, the type of the implied getter/setter can be determined from the decorator return value.

There's actually a way to write the above without using the `accessor` keyword in plain JavaScript, like so:

```js
import {element, numberArray} from 'some-custom-element-lib'

@element // this added decorator is needed for creating reactive accessors in a returned subclass based on decorated fields
class MyEl extends HTMLElement {
  @numberArray coords = "1 2 3"
}
```

but then I don't see how TypeScript would be able to determine differing get/set types for `coords`.

**Comment by ruojianll** [comment]
> 

@trusktr Maybe that should be write in grouped accessors.
```
class Foo {
accessor coords{
  get():ReactiveArrayTriplet<number>{
    //...
  };
  set(){
  };
}
}
```

**Comment by ruojianll** [comment]
@wycats In my opinion, the accessor type should be declared in the class. Decorators should be compatible with accessor type.

```
class Foo{
  @Dec accessor bar?:string //not allowed, bar must be instialized
  @Dec accessor bar2:string|undefined//allowed
}
```

Decorators shouldn't break the type defined in class. That's also a typescript way to implement.

**Comment by uasan** [comment]
Is there any information about TS plans to implement decorator extensions?
https://github.com/tc39/proposal-decorators/blob/master/EXTENSIONS.md

Many real use cases require exactly the extended capabilities of decorators.
Thanks.

**Comment by justinfagnani** [comment]
@uasan I'm sure TypeScript wouldn't implement them before they're standardized, so it's really a question for TC39 and the decorators proposal champions.

**Comment by trusktr** [comment]
> > 
> 
> @trusktr Maybe that should be write in grouped accessors.
> 
> ```js
> class Foo {
> accessor coords{
>   get():ReactiveArrayTriplet<number>{
>     //...
>   };
>   set(data:`${number} ${number} ${number}` | [number, number, number] | ReactiveArrayTriplet<number>){
>     //...
>   };
> }
> }
> ```

The entirely defeats the purpose of having decorators: to write concise code. Of course I know I can skip using decorators and just write an entire accessor, or even just actual getter and setter, but that's not what we are here for!

**Comment by trusktr** [comment]
For the time being, it would be great to have an option to not compile decorators (just like we can leave JSX untouched), so that we can pass output code along to other tools like Babel.

**Comment by trusktr** [comment]
Along with a `decorators: "preserve"` or similar option, `export` needs to be allowed before `@decorator`. Then we're off to the races without TS needing full support yet!

**Comment by trusktr** [comment]
Currently we can make this work using `@babel/typescript` (type check code with `tsc` separately) by splitting `export`s from `class` definitions to avoid errors that `tsc` currently gives.

This does not work:

```js
export // export is required before stage-3 decorators, currently an error in TS
@stage3Decorator
class Foo {}
```

This works:


```js
@stage3Decorator
class Foo {}
export {Foo}
```

Your babel config plugins will look something like this:

```js
	plugins: [
		['@babel/plugin-transform-typescript', {...}],
		['@babel/plugin-proposal-decorators', {version: '2022-03'}],
		['@babel/plugin-proposal-class-static-block'], // needed, or decorator output will currently not work in Safari.
	],
```

and off to the races! 🐎

**Comment by trusktr** [comment]
For now, here's what the signature of a stage 3 decorator may look like to avoid type errors:

```ts
export function someDecorator(...args: any[]): any {
	const [value, {kind, ...etc}] = args as [DecoratedValue, DecoratorContext]
	console.log('stage 3!', value, kind, etc)

	if (kind === 'class') {
		// ...
	} else if (kind === 'field') {
		// ...
	} else (/*...etc...*/) {
		// ...
	}

	// ...
}

interface DecoratorContext {
	kind: 'class' | 'method' | 'getter' | 'setter' | 'field' | 'accessor'
	name: string | symbol
	access: Accessor
	private?: boolean
	static?: boolean
	addInitializer?(initializer: () => void): void
}

interface Accessor { 
    get?(): unknown
    set?(value: unknown): void
}

type Constructor<T = object, A extends any[] = any[], Static = {}> = (new (...a: A) => T) & Static

type DecoratedValue = Constructor | Function | Accessor | undefined
```

**Comment by pokatomnik** [comment]
Sorry for the offtopic question, but what will happen to stage3 decorators? Will they be removed from Typescript?

**Comment by rbuckton** [comment]
> Sorry for the offtopic question, but what will happen to stage3 decorators? Will they be removed from Typescript?

I assume you mean the Stage 1 "experimental" decorators that are already in TypeScript? That will remain behind `--experimentalDecorators` for the foreseeable future as there are a number of decorator features that are not yet covered by the current Decorators proposal:
- Metadata (https://github.com/tc39/proposal-decorator-metadata)
- Parameter Decorators (https://github.com/tc39/proposal-decorators/issues/47)
- A way to decorate a getter/setter pair via `{ get, set }` (https://github.com/tc39/proposal-grouped-and-auto-accessors). While this does exist for the new `accessor` fields, there is no easy alternative for normal getters and setters.

We also do not currently support decorated `declare` fields with Stage 3 decorators, as that would introduce significant additional complexity due to the timing of decorator application.

**Comment by rbuckton** [comment]
> For now, here's what the signature of a stage 3 decorator may look like to avoid type errors:
> 
> [...]

The built-in lib definitions in https://github.com/microsoft/TypeScript/pull/50820 contain types that will hopefully be able to help:

```js
// class decorator
const MyClassDecorator: ClassDecoratorFunction = (target, context) => {
};

// method decorator
const MyMethodDecorator: ClassMethodDecoratorFunction = (target, context) => {
};

// or, a catch-all decorator
function MyDecorator(target: unknown, context: DecoratorContext) {
  switch (context.kind) {
    case "class": ...;
    case "method": ...;
    ...;
  }
}
```

**Comment by pokatomnik** [comment]
@rbuckton, thank you, I mean ES decorators reached stage 3. And because of that, I believe they'll be implemented in the Typescript as well. And correct me if I'm wrong, but the newest decorators are not compatible with the good old "experimental". So I thought, Typescript will have to support them since a lot of frameworks are relying on them.
In other words, my question is "should I write a new code with the experimental decorators or will they be deprecated in  about 3 years?"
Thanks in advance!

**Comment by ruojianll** [comment]
> "should I write a new code with the experimental decorators or will they be deprecated in about 3 years?"

Hope there is adapter to update experimental decorators to stage 3 automatic.

**Comment by trusktr** [comment]
@pokatomnik while experimental stage 1 decorators will be supported for some unknown amount of time, I believe we can assume that eventually non-experimental stage 3 decorators will land and we'll be able to rely on those (and ignore stage 1 decorators at that point).

If you want to prepare for this future, the best way to do that currently is to use `tsc` only for type checking, and use `babel` for transpiling stage 3 decorators today. Then it should be minimal effort later to switch to using just `tsc` for type checking and compiling.

I'm betting on stage 3 decorators.

**Comment by trusktr** [comment]
> Hope there is adapter to update experimental decorators to stage 3 automatic.

I don't think TypeScript will do that. Experimental and stage 3 decorators are highly incompatible.

**Comment by ruojianll** [comment]
> > Hope there is adapter to update experimental decorators to stage 3 automatic.
> 
> I don't think TypeScript will do that (I don't think it has ever been done for any feature). Experimental stage 1 decorators and stage 3 decorators are highly incompatible. Start migrating!

I will try, but it is a terrible work especially for package creators to update their user's code.

**Comment by jithujoshyjy** [comment]
> * Metadata (https://github.com/tc39/proposal-decorator-metadata)
A little nod about the metadata in decorators. https://github.com/tc39/proposal-type-annotations/issues/159 can this be done in typescript?

**Comment by rbuckton** [comment]
> > Hope there is adapter to update experimental decorators to stage 3 automatic.
> 
> I don't think TypeScript will do that (I don't think it has ever been done for any feature). Experimental stage 1 decorators and stage 3 decorators are highly incompatible. Start migrating!

No, we won't automatically adapt legacy decorators as that would require type-directed emit. Also, there is not 1:1 parity between legacy decorators and ECMAScript decorators, which [I mentioned above](https://github.com/microsoft/TypeScript/issues/48885#issuecomment-1309327151).

It's possible to write a custom decorator adapter, though that would entail varying degrees of complexity depending on the decorator you are adapting. An adapter that provided full backwards compatibility with legacy decorators would likely incur a performance penalty, though it would be feasible:

```ts
// legacy.ts
@foo
@bar({ x: 1 })
class C {
  @baz method() {}
  @quxx field;
}

// native.ts
import { createDecoratorAdapter } from "./adapter";

const _ = createDecoratorAdapter();

@_ // <- last applied decorator
@_(foo)
@_(bar({ x: 1 })
class C {
  @_(baz) method() {}
  @_(quxx) field;
}

// adapter.ts
export function createDecoratorAdapter() {
  // TODO: returns a function that queues up each legacy decorator application
  // and performs legacy decorator evaluation at the end as part of a
  // final class decorator.
}
```

**Comment by rbuckton** [comment]
Here's a rough implementation of a comprehensive `createDecoratorAdapter()`: https://gist.github.com/rbuckton/a464d1a0997bd3dab36c8b0caef0959a

NOTE: It's not designed to be intermingled with native decorators, as all decorator applications are queued until an adapted class decorator runs (or the adapter itself is used as a class decorator).
