### ISSUE TITLE
`noEmitOnError` slows down incremental per file emit

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#4894]
This might be by design. I'm creating this issue purely for clarity :rose:

Basically `services.getEmitOutput(filePath);` goes from under 10ms to over 1.5seconds probably because it seems to validate *the whole project*. So we can't do a *file by file emit*. 

First reported by @robertknight here : https://github.com/TypeStrong/atom-typescript/issues/590

**Comment by mhegazy** [comment]
yup. that is by design. when you have noEmitOnError, you are asking the compiler not to emit *any* files if there is *any* error in your project. to do this the compiler needs to check all files do not have errors, which is in fact the majority of the time for emit.

i would suggest not setting the flag if you are doing incremental builds.
