### ISSUE TITLE
why interface to Record<string, string> get an error, but use type is normal?

### ISSUE THREAD

**Issue by WormGirl** [microsoft/TypeScript#48985]
# Bug Report

### 🕗 Version & Regression Information

- This is a crash at offical playground.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCbvCwDKgU8JkY7p7ehCTkVDQS2E6gnPCxGcwmZqDSTgzxxWWVoASMFmgYkAAeRJTInN3ymj4d-jSCeNsMq-wuoPaOltigAKoASgAywhK7SbGQZIIz5VWCFzSeCrZagNYbChbHaxUDcCjJZLfSDbExIAgUdxkUBIursJzCFJtXydajBBCcQQ0MwAUVWDEQC0gADVHBQGNJ3KAALygABEAAkYNAMOB4GRonzFBTBPB3AERcwABS0+mM9ysygc9wASmCGQUZGSDCWAFkUexhABvRQlY5UyCIADC8G4kHyV1QlE4zAA3LarngHYgAHIM92e71+gP2hSIACS3A9VKj-oAvv6ZTRpB6KmQyEwADzmziWgB8PNAAG0AzaSnag3GXW6PQByFPDVu8AMN4Nh5Btjs+rs9wPBxODr2dgNpxQAXX97mpHsekAQZG4haHzDsU59Zarc8rh-94l50n9xRwzQ8ZC8iHFzmB7BoXzcZmY7AYzEg-Fg0HURIOXgPQRC8Pk6QZJlBD5JJsT5cAHFQdtQBDSAJD5IIVAAeS+Mh3kEX8tEgI5UEcBRXGkPBQCcB8dGGLB9BQBBEGhYRLjfCRxWiEQDA4bEFiYVgOB4IISiAA)

### 💻 Code

```ts
interface Menus {
  systemCode: string;
  systemName: string;
  systemId: string;
};
const b: Array<Menus> = [
  {
    systemCode: 'string',
    systemName: 'string',
    systemId: 'string'
  }
];
let a: Record<string, string>[] = [];
// this get error
a = b;
```

```ts
type Menus = {
  systemCode: string;
  systemName: string;
  systemId: string;
};
const b: Array<Menus> = [
  {
    systemCode: 'string',
    systemName: 'string',
    systemId: 'string'
  }
];
let a: Record<string, string>[] = [];
// this work fine, why ?
a = b;
```

**Comment by MartinJohns** [comment]
You forgot to fill out the issue template. Duplicate of #42825.

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
