### ISSUE TITLE
Readonly spread array in tuple

### ISSUE THREAD

**Issue by olegdunkan** [microsoft/TypeScript#49017]
🔎 Search Terms

readonly tuple

💻 Code

Why does TypeScript reduce **readonly** modifier in the next snippet?
Or it is better to ask why does TypeScript allow **readonly** modifier if it makes no sense?

```
let a:[boolean, ... readonly string[]] = [true, '1', '2', '3'];

a[0] = false;
a[1] = 'one'; 
```

⏯ Playground Link[
](https://www.typescriptlang.org/play?ts=4.6.2#code/DYUwLgBAhgXA2gIwPZNFAdgGggOjxAJxCgBMl1gBPCAZzAIEt0BzOAXTYgF4I56BXENgDkARmEiATBIjCAzMLYBuALAAodVDgAGTjwBmUYDRCq1W0XtnkQwpRAD0D9EgggCBJAWwJ+kBpA0ABZI-MAkEAggbh5e6vEaiQnJiUA)

🙁 Actual behavior

It is completely working solution
 
🙂 Expected behavior
```
let a:[boolean, ... readonly string[]] = [true, '1', '2', '3']; 
a[0] = false;
a[1] = 'one'; //no error, but it should be error
```
if **readonly** are allowed then we can't assign to a[1] in the opposite **readonly** are not allowed.

**Comment by jcalz** [comment]
You forgot to fill out the issue template.

**Comment by jcalz** [comment]
Note that this came from [the following Stack Overflow question](https://stackoverflow.com/q/72161399/2887218). 

 My speculation there is that the type `[T, ...U]` should be equivalent to the type of `[t, ...u]` if `t` is a value of type `T` and `u` is a value of type `U`.  And thus `[boolean, ...readonly string[]]` would be equivalent to `[boolean, ...string[]]` because the new array literal into which things are spread will not be readonly.  Is that the proper reasoning here?  Or is something else going on?

**Comment by olegdunkan** [comment]
> Note that this came from [the following Stack Overflow question](https://stackoverflow.com/q/72161399/2887218).
> 
> My speculation there is that the type `[T, ...U]` should be equivalent to the type of `[t, ...u]` if `t` is a value of type `T` and `u` is a value of type `U`. And thus `[boolean, ...readonly string[]]` would be equivalent to `[boolean, ...string[]]` because the new array literal into which things are spread will not be readonly, even if the original array is. Is that the proper reasoning here? Or is something else going on?

Yes, it is proper reasoning here, but 
If so then it is counterintuitive to allow **readonly** modifier in that case.

**Comment by RyanCavanaugh** [comment]
It's legal to write `readonly` here for the same reason that a symbolic calculator will let you write `3 + (8 * 0)` even though the `8 *` part of it doesn't do anything.

If you wrote
```ts
type M = readonly [number, number];
type S = [number, ...M];
```
then `S`'s intended type is (I think, clearly) `[number, number]`. There's no need to make you erase the readonliness for a spread; the semantics of the containing array's mutability follow directly from other spreads like those in expression space.

We generally don't break substitional symmetry unless there's a really good reason to.

**Comment by olegdunkan** [comment]
@RyanCavanaugh Types script doesn't define the **substation symmetry** as a language entity that is why so difficult to understand exceptions like this. For me `3 + (8*0)` is a special case of `3 + (8*x)` where x belongs to real numbers. It is easy to think in generalized way then in the way of special cases.

**Comment by fatcerberus** [comment]
> Types script doesn't define the substation symmetry as a language entity that is why so difficult to understand exceptions like this. For me 3 + (8*0) is a special case of 3 + (8*x) where x belongs to real numbers. It is easy to think in generalized way then in the way of special cases.

I… have no idea what you’re trying to say here.

**Comment by RyanCavanaugh** [comment]
> That is, the reasoning in https://github.com/microsoft/TypeScript/issues/49017#issuecomment-1120512130 is correct?

Yes.

**Comment by RyanCavanaugh** [comment]
If partially-readonly arrays were a thing in general (like, anywhere...), we'd *maybe* consider preserving the readonlyness of the slots. But I don't think even then it really makes sense, because spread can the indices (keys) of these properties, so a `[T, ...U]` doesn't give you back a `U`-like thing anyway. It's just not clear *why* you would copy over the readonlyness in the first place given that the same thing doesn't happen in expression space -- TC39 could have said that `[0, ...Object.freeze([1, 2])]` created some hybrid object that had a mutable `0` slot and frozen `1` and `2` slots, but no one wants that kind of object.
