### ISSUE TITLE
Declaration file not work well when import other type

### ISSUE THREAD

**Issue by Jokcy** [microsoft/TypeScript#49043]
# Bug Report

### 🔎 Search Terms

Custom types not working

### ⏯ Playground Link

[A Demo repo](https://github.com/Jokcy-Demos/ts-declare-problem)

### 💻 Code

```ts
import { ComponentType } from "react";

declare module "a/b" {
    const B: ComponentType<any>;
    // const B: import("react").ComponentType<any>;
    export default B;
}
```

### 🙁 Actual behavior

When using this syntax, ts will emit error `cannot find module a/b`. But if I use the `import("react").ComponentType<any>` syntax it will work fine (note you need to delete the first import line).

### 🙂 Expected behavior

Both syntax will work fine.

**Comment by RyanCavanaugh** [comment]
This is the expected behavior though admittedly confusing. A file that contains both top-level `import`/`export` declarations and `declare module "a"` blocks is a *module augmentation* that can only add meanings to the *existing* module `"a"`. If you want to create a freestanding declaration of `"a/b"`, it needs to be in a file without top-level `import` or `export` declarations.
