### ISSUE TITLE
Anonymous class expressions always have names in ES6 emit

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#4908]
`foo.ts`:

```TypeScript
(class {})
```

`foo.js`:

```JavaScript
(class class_1 {
}
);
```

**Comment by MartyIX** [comment]
I guess it can be fixed by changing:

`if ((node.name || !(node.flags & NodeFlags.Default)) && !thisNodeIsDecorated) {` (the first exclamation mark should not be there)

->

`if ((node.name || (node.flags & NodeFlags.Default)) && !thisNodeIsDecorated) {`  

on line https://github.com/Microsoft/TypeScript/blob/master/src/compiler/emitter.ts#L4533

**Comment by DanielRosenwasser** [comment]
@MartyIX if you're up to it, we'd be willing to take a pull request :smiley:

**Comment by MartyIX** [comment]
I've just done that. It takes forever to run all tests on my computer. However, a few of them fails. If I get it right, it seems that I need to run all tests using `jake runtests` (it's still running :-) ) and then I should try `jake baseline-accept` and check visually if the results are correct. Is this the idea of fixing tests?

**Comment by DanielRosenwasser** [comment]
Yup, that's exactly it. For a small speedup, use `jake runtests light=true`, and try to use either Node 4 (or Node 0.10.33 if that's still too slow)

**Comment by DanielRosenwasser** [comment]
See https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md for more details.

Also, for a good free folder diff tool on Windows, I suggest WinMerge.

**Comment by mhegazy** [comment]
thanks @MartyIX!
