### ISSUE TITLE
'async' modifier cannot be used with 'abstract' modifier

### ISSUE THREAD

**Issue by sugandansa** [microsoft/TypeScript#49096]
'async' modifier cannot be used with 'abstract' modifier

abstract async init(): Promise<void>;

**Comment by MartinJohns** [comment]
That is correct. An abstract method can not be async, because it has no implementation.

You forgot to fill out the issue template.

**Comment by sugandansa** [comment]
can i remove async is there any alternative i am getting this error 'async' modifier cannot be used with 'abstract' modifier

**Comment by MartinJohns** [comment]
You can remove it, and then check out some JavaScript tutorials to learn what `async` actually does. And note that this is not a support forum.

**Comment by fatcerberus** [comment]
The only two things the `async` modifier does is: 1. make a function return a promise, and 2. allow use of `await` in the implementation.  Since an abstract method has no implementation and you *already* have to declare its return type as `Promise<Whatever>`, the `async` is redundant in that context.

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!

**Comment by SeanKelly369** [comment]
What an utter pain.  No consideration for those of us who have to deal with legacy code.  A major re-write is now required. 
 Thanks Microsoft.

**Comment by MartinJohns** [comment]
A major re-write is required, because a keyword is not allowed in a situation where it makes no sense and has no effect?

**Comment by SeanKelly369** [comment]
When dealing with legacy code, yes.

**Comment by MartinJohns** [comment]
Having to remove one single word, resulting in the same behavior, constitutes a "major re-write"? Wow.

**Comment by SeanKelly369** [comment]
I didn't write it
