### ISSUE TITLE
type of this in Object.defineProperty

### ISSUE THREAD

**Issue by tbontb-iaq** [microsoft/TypeScript#49162]
# Suggestion

Typescript can't detect the type of this in `Object.defineProperty`

```typescript
Object.defineProperty(ConstructionSite.prototype, "memory", {
  get: function (): ConstructionSiteMemory {
    return (Memory.construction_sites[this.id] ??= {
      pos: { x: this.pos.x, y: this.pos.y },
      type: this.structureType,
    });
  },
});
```

VSCode tells me that `this` is of type `any`, and autocompletion doesn't work.But actually `this` is an instance of `ConstructionSite`.

I can use `asserts` to solve this problem.

```typescript
function assert<T>(value: any): asserts value is T
{ /** simply does nothing */ }
...
assert<ConstructionSite>(this);
...
```

So, is there any other way to help typescript detect the type of `this`, or can typescript to be smart enough to know the type of `this` in `Object.defineProperty`.

## 🔍 Search Terms

- `Object.defineProperty`
- type hint
- this

## ✅ Viability Checklist

My suggestion meets these guidelines:

- [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [x] This wouldn't change the runtime behavior of existing JavaScript code
- [ ] This could be implemented without emitting different JS based on the types of the expressions
- [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Automatically detect the type of this in `Object.defineProperty`

**Comment by jcalz** [comment]
Could you provide a standalone example that when pasted into [The TypeScript Playground](https://www.typescriptlang.org/play?target=7#code/PIIwVgpgxgLgdAEwgMwJYDsIAUBOB7ABwhxgE8AKAYT3QGcYcBXWVGgZVRgjgPxjzJEANAAIARAFsIEvDlJjRAbwCwAKBEiA5hBgAuEckboWNEeQCU+6nQbMYrdBy4BZabNIiV6jSJw7GOOhmrjJycFA09Ewm6AD6tJwQtADaMAAWqLRwqAgAuiIA-AUAvJ5qPj4EeLT6iiIAHvrpmTzVcPWipE0ZWVVZHgC+QuUVIoIQ3S1RdgEQACqkwiMaA+YA3CNDaqtrQA) clearly demonstrates the issue without unrelated problems?

**Comment by Josh-Cena** [comment]
`lib.es5.d.ts` has explicitly added `ThisType<any>`:

```ts
defineProperty<T>(o: T, p: PropertyKey, attributes: PropertyDescriptor & ThisType<any>): T;
```

It's not safe to say `ThisType<T>`, because the `this` value is the object on which the property is being accessed, but not necessarily `o` itself. For example:

```ts
const child = Object.create(ConstructionSite.prototype);
child.id = { "I am": "not a string" };
child.memory; // The `this` value inside the getter will be `child` instead of an instance of `ConstructionSite`
```

Of course, whether that's the actual reasoning I'm not sure. TS is super weak when it comes to prototypes and inheritance and even `this` contexts in general...

**Comment by Josh-Cena** [comment]
I don't think checking `this instanceof ConstructionSite` is sufficient, because in my example, `child` also has `ConstructionSite.prototype` in its prototype chain, but the `id` property has been overridden with something totally unrelated. You probably need to check for the type of `this.id` specifically, if you want to guard against the case I brought up. Again, I don't know if that's the reason why TS has `ThisType<any>`, because you can hack class getters/object getters in the same way, which TS seems to be happy about.

If you just want better type hints, your empty assert function already works. Otherwise, you can also use an explicit `this` parameter:

```ts
Object.defineProperty(ConstructionSite.prototype, "memory", {
  get(this: ConstructionSite): ConstructionSiteMemory {
    return (Memory.construction_sites[this.id] ??= {
      pos: { x: this.pos.x, y: this.pos.y },
      type: this.structureType,
    });
  },
});
```
