### ISSUE TITLE
Generic type's default value is ignored when used in a mapped type

### ISSUE THREAD

**Issue by ehmicky** [microsoft/TypeScript#49203]
# Bug Report

### 🔎 Search Terms

Generic, mapped type, default value

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about it.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.0-beta#code/MYewdgzgLgBAZgVzMA8mApjAvPJwoCW4APACozoAeU6YAJhDNAE4FgDm2MARMNwHwAKAIYAuGAG8YAbQCqMNjEHkqNeo2FgAnjAD8McuNIBKALrjNOgL4AaGACNdR4+IBuIAnUlWAUImRo6IJSwOJQzAiYVsYwAPSxMADKCMDA6OgMfniBwTB0YRFRMfEwAGLCBAA2ED4+oJCw-sCkAO4gXE2EJCrUtAxM4WycOLwCIuJScgpgBuYwljC2Dk4GLjDunt5ZyK0gufkw4ZGLxQnJqekMQA)

### 💻 Code

```ts
const funcOne = function<T extends string = "c">(a: { [U in (T extends any ? T : T)]: any }, b?: T): void {}
funcOne({ c: true }) // Succeeds
funcOne({ d: true }) // Fails

const funcTwo = function<T extends string = "c">(a: { [U in T]: any }, b?: T): void {}
funcTwo({ d: true }) // Succeeds
```

### 🙁 Actual behavior

`funcOne({ d: true })` typing fails with:

```
Argument of type '{ d: boolean; }' is not assignable to parameter of type '{ c: any; }'.
  Object literal may only specify known properties, and 'd' does not exist in type '{ c: any; }'.
```

But `funcTwo({ d: true })` typing does not fail.

### 🙂 Expected behavior

`funcTwo({ d: true })` typing should fail as well. 

Since the `b` argument is not passed, `T` should use the default type `"c"`, resulting in `a` having type `{ c: any }`.
Instead, it appears that the default type `"c"` is not assigned and `T` uses only `extends string` instead, resulting in `a` having type `{ [index: string]: any }`.

**Comment by jcalz** [comment]
`T` is inferred as `{d: any}` in the call to `funcTwo({d: true})`.  The use of `T` in `{[U in T]: any}` is an inference site for `T`.  Since there is an inference candidate for `T`, then the generic default is not used.  This is working as intended, as far as I know.  

It seems that you expect the compiler to treat the `T` in `{[U in T]: any}` as a *non-inferential type parameter usage*, as discussed in #14829.  If you want to say "don't infer `T` from here", there's no *direct* support for this, but there are various ways to get this effect in some situations.  [Generic conditional types](https://github.com/microsoft/TypeScript/issues/14829#issuecomment-504042546) like the `T extends any ? T : T` in `funcOne()` work this way sometimes.  

I guess this is either working as intended or a duplicate of #14829.

**Comment by ehmicky** [comment]
Thanks @jcalz, this makes total sense!
I was feeling like my question might be more of a misunderstanding of an intentional feature than a bug. What you are describing does make lots of sense.
I agree this is a duplicate of #14829, so I will close this. I also agree having a way of not inferring some types might be useful.
