### ISSUE TITLE
Catch usage of `this` in methods called by a base class constructor

### ISSUE THREAD

**Issue by craxal** [microsoft/TypeScript#49230]
# Suggestion

## 🔍 Search Terms

constructor inheritance private super this

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

In complex construction scenarios, a base class constructor might call an abstract function implemented in a derived class. Because the base class constructor is currently executing, trying to reference `this` in the implementation of the abstract function causes an error similar to the following:

> Cannot read private member from an object whose class did not declare it

TypeScript does not currently catch errors like this, since there's not syntactic way to determine whether this situation is in play. Control flow analysis may be able to catch errors like this during compilation.

The idea here is to catch errors in complex object and relationship constructions. Showing errors like this would also help dissuade authors think about better construction patterns.

## 📃 Motivating Example

```ts
abstract class Base {
    constructor() {
        this.constructorHelper();
    }

    protected abstract constructorHelper(): void;
}

class Derived extends Base {
    constructor() {
        super();
    }

    protected override constructorHelper() {
        // Here's where the problem is:
        // `constructorHelper` is called from the constructor for `Base`.
        // Because we're still in the call to `super()`, we can't refer to `this`.
        this.#derivedMethod();
    }

    #derivedMethod() {
        // Do something
    }
}

// This will throw a type error.
const obj = new Derived();

console.log("Done!");
```

## 💻 Use Cases

For example, this occurred while I was building a set of abstract and concrete classes representing dialogs. Each dialog has a very similar structure with minor details in things such as labels or where initial data came from. The common dialog components were factored out into a hierarchy of abstract classes, and each actual dialog implemented concrete classes inheriting from these. Part of the construction of these objects required a cnstruction helper method similar to that described above.

**Comment by MartinJohns** [comment]
Related: https://github.com/microsoft/TypeScript/issues/37671#issuecomment-606212433, #30834.

**Comment by RyanCavanaugh** [comment]
The problem here is that neither `Base` nor `Derived` is identifiably incorrect from a type system perspective -- it may well be that the design contract of `Base` is that `constructorHelper` is not supposed to immediately use `this`. It'd be fully legal, for example, to write this code:
```ts
class Derived extends Base {
// ...
    protected override constructorHelper() {
        setImmediate(() => this.#derivedMethod());
    }
```
which isn't meaningfully different from the broken version.

We'd have to bolt on an entire system of "safe to access `this` immediately, or not, from this method" and track that everywhere, but this only really catches a very small subset of the ways you can call functions in the wrong order in a programming language. A virtual call from a constructor is never a *good* idea but it's also almost never a *provably wrong* idea - there are safe ways to go about doing it and unsafe ways, but we can't reliably tell them apart.
