### ISSUE TITLE
Intersection Types that have overlapping properties can fail

### ISSUE THREAD

**Issue by wdamien** [microsoft/TypeScript#49264]
This seems to be the source: https://github.com/microsoft/TypeScript/pull/31838

Example:
Try an intersection of 2 types where the same property has inconsistent overlapping types:

```
type Bar = {
    Prop: string
};

type Works = Bar & {Prop: number}; // Bar & {Prop: number}
type ThisIsNever = Bar & {Prop: null}; // never
```

It makes sense to me that individual types can be reduced to never, but why can intersecting types with nested overlapping property types get reduced to `never`?

Playground link: https://www.typescriptlang.org/play?ts=4.7.0-beta#code/C4TwDgpgBAQghgJygXigbwFBW1ACggezAC4oBnYBASwDsBzDAXwG4MMB6dqAdQIQGsyUAGa0IGUJCgBJGsAgIyEAMbAqBGiliIoAMnT4ipGgFcAtgCMFLKJ21J9aQySinL1ieGgA5CADcFWXlFFTUNLXgHA0IXGn9rZlsuSL1oo1d4hEY2O28CYCgIAA9IVQgAE08pbxMAG1qghSVVdU1UFMdnYzramzsAJRUIKgDy40ykqABREtCK0gADDrTYnsYFqAAKPiglnU6Y8YCshYBKKugAVRpyiFE48saQlvD2-ZXSExu7sXK+rkGymGoyOCkmM1K8jGu2WTkOUC+t3uFXWWx2eyicPScWO63OQA

This might be expected, but it does feel like a bug to me. My initial use case was joining a few different types together to get a union of all their keys. But since some props had a `null | undefined` type, it was reduced to `never`. Causing my use of those keys to fail unexpectedly. I would expect `ThisIsNever` to have a `Prop: never` property instead, or maybe a union of `string | null`. Or at-least surface an error saying the union is not possible because of `Prop` being incompatible.

Tested on: 4.6.4, 4.7.0-beta
This worked as expected in: v3.8.3.  And starts not being expected in v3.9.7

**Comment by jcalz** [comment]
You didn't fill out the template.

This is working as intended as per #36696.  Since TypeScript 3.9, [intersections are reduced by discriminant properties.](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#intersections-reduced-by-discriminant-properties) `null` and `undefined` are unit/singleton types, and [a property whose member types contain at least one unit/singleton type are considered discriminant properties](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-2.html#non-unit-types-as-union-discriminants).

**Comment by fatcerberus** [comment]
Shouldn’t *both* types reduce to `never`?  Realistically it’s not possible to produce a value of either one.

**Comment by RyanCavanaugh** [comment]
Conflicting primitives are in the grey zone between conflicting unit types and conflicting object types. It's *definitely* not possible to produce an intersection of two unit types, definitely *is* possible to produce an intersection of two object types, but intersections between two primitives sometimes arise in places that are benign.
