### ISSUE TITLE
Different behavior for `a?.b<c>.d` depending on the compilation target

### ISSUE THREAD

**Issue by nicolo-ribaudo** [microsoft/TypeScript#49293]
# Bug Report

### 🔎 Search Terms

instantiation expression optional chaining target

### 🕗 Version & Regression Information

This feature has been introduced in 4.7. I tested 4.7.0-dev.20220528

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=6&ts=4.8.0-dev.20220528#code/IYfgdARgPAxgfGAJkA)

### 💻 Code

```ts
a?.b<c>.d
```

### 🙁 Actual behavior

When targeting <=ES2019 it generates `(a === null || a === void 0 ? void 0 : a.b).d`, while when targeting >=ES2020 it generates `a?.b.d`.

They have different behaviors: in the ES2019 output it always reads `.d`, while in the ES2020 output it only reads `.d` if `a` is not nullish.

### 🙂 Expected behavior

They should have the same behavior.

The ES2020 behavior feels more useful, but "adding `<c>` to an optional chain ends the optional context" (as wrapping it in parentheses does) would be ok too as long as it's consistent. You would then have to write `a?.b<c>?.d`.

(Babel's implementation has the same different behavior depending on the target, so this is apparently something very easy to overlook while implementing instantiation expressions :grimacing:)

**Comment by RyanCavanaugh** [comment]
@jakebailey good luck 🍀

**Comment by jakebailey** [comment]
That being said, I think there's also a checker bug here that's related. In writing a test case, I get a confusing `Object is possibly 'undefined'` error if there's an instantiation expression present.

```tsx
declare namespace A {
    export class b<T> {
        static d: number;
        constructor(x: T);
    }
}

type c = unknown;

declare const a: typeof A | undefined;

a?.b<c>.d;

a?.b.d
```

[Playground Link](https://www.typescriptlang.org/play?ts=4.8.0-dev.20220601#code/CYUwxgNghgTiAEA7KBbEBnADlMCCC8A3gLABQ8F8IAHpgPYwAu8kU668ARgDwAqAfETKUR8dIyiMAlmHjAAXEgCuKTiBgBuYaIpg6icTCVhGDABTVFvAJRbylAL5knpMowCemBLIC88JYgA1oh0AO6IdmSgrHAs+uLwUIoeXnQAZvAEAD7+iKBpUoggwJGkUAD8AHQ8YPyVJWRkFdX1ZEA)

**Comment by jakebailey** [comment]
Confusingly, I don't always get this error in my test, but I see it in the editor and on the playground.

**Comment by jakebailey** [comment]
Hm, scratch that; given it's a `PropertyAccessExpression` with a `ExpressionWithTypeArguments` inside of it, those branded types should be fine. I think it's probably more that `skipPartiallyEmittedExpressions` doesn't skip those arguments.

I'll keep digging and stop pinging people until I have a real view.

**Comment by jakebailey** [comment]
It seems to be a mix of everything I listed above; for example `isOptionalChain` and other functions like it make assumptions about parents and such, including code like:

```ts
export function isExpressionOfOptionalChainRoot(node: Node): node is Expression & { parent: OptionalChainRoot } {
    return isOptionalChainRoot(node.parent) && node.parent.expression === node;
}
```

Which use a type guard to say that a parent is a chain root, when for example, `parent.expression` may be a `ExpressionWithTypeArguments` that then contains the current node. These helpers are used all over the checker, and I am guessing are part of my error problem.

Then in `es2020.ts`, the extra node breaks chain detection because it doesn't know to keep looking upward. This one seems more approachable, but also uses those same branded types and helpers.

**Comment by nicolo-ribaudo** [comment]
That sounds reasonable!

**Comment by nicolo-ribaudo** [comment]
Q: If you will disallow `a<b>?.c`, did you also talk about `a<b>?.()`? (I don't think that `?.(` should be disallowed).

**Comment by jakebailey** [comment]
"Disallow" is probably too strong of a term; what I mean is that we'll bail out of parsing the `PropertyAccessExpression`, and then do the "right thing" when getting to the call because that's outside of that node. In your example, I believe the `?.` token is a part of the `CallExpression`, not the `PropertyAccessExpression`, so it should work. But that's a great test case I'll be sure to include.

**Comment by nicolo-ribaudo** [comment]
Actually, replying to myself: what would be the difference between `a?.<b>()` and `a<b>?.()`?

(sorry, I'm just dumping my thoughts here in case they are interesting for you :sweat_smile:)

**Comment by jakebailey** [comment]
Hm, that's definitely interesting; looking at the emitter output, only the former works, which is confusing because the latter reads more correctly?

In any case, I think that's somewhat a separate problem because it doesn't involve property access, but is in the same vein.

A full example:


```tsx
declare interface A {
    static c: number;
    <T>(): T;
}

type b = 'b type';

declare const a: A | undefined;


a?.<b>();

a<b>.?();
```

[Playground Link](https://www.typescriptlang.org/play?ts=4.7.2#code/CYUwxgNghgTiAEBLAdgFxDAZlMCCC8A3gLABQ8F8AzqlKomPGAFzzICuAtgEYYDcZSvAA8AFQB8ACgCUrUQNIBfMmVQBPAA4Ju8ALzwA5DvVaDCsqEiwEYAPbIa8KKwIAfeO2ShMKEMHOkZFAA-AB0wtxS0gFQEeKhwTJ8QA)

The question being "why is the first one valid, and the second not, and not the other way around?"

**Comment by jakebailey** [comment]
I had a silly typo:

```tsx
declare interface A {
    c: number;
    <T>(): T;
}

type b = 'b type';

declare const a: A | undefined;


a?.<b>();

a<b>?.();
```

[Playground Link](https://www.typescriptlang.org/play?ts=4.7.2#code/CYUwxgNghgTiAEBLAdgFxDAZlMCCC8A3gLABQ8F8YAXPMgK4C2ARhgNxmXwA8AKgHwAKAJS1eHUgF8yZVAE8ADgmbwAvPADkK+Uo0SyoSLARgA9sgDOqeFFoEAPvHrJQmFCGD7SZKAH4AdNzMQsJeUEH8ASJsQA)

We emit:

```
a === null || a === void 0 ? void 0 : a();
(_a = (a)) === null || _a === void 0 ? void 0 : _a();
```

Which is... weird, but the same. I'll have to see if one the latter one breaks when I fix this bug.

**Comment by ExE-Boss** [comment]
> We emit:
> 
> ```js
> a === null || a === void 0 ? void 0 : a();
> (_a = (a)) === null || _a === void 0 ? void 0 : _a();
> ```
> 
> Which is... weird, but functionally equivalent (same as if you do `(a)?.()`; the expression with type arguments node is like a paren). I'll have to see if one the latter one breaks when I fix this bug.

The second one is correct, because if `a` is a getter on the global object, then the former will invoke it each time, which is incorrect.

**Comment by jakebailey** [comment]
That sounds unrelated; the top one is how we emit `a?.()` (and I think we always have). If that's a problem, I'd suggest filing a new issue.

**Comment by nicolo-ribaudo** [comment]
@DanielRosenwasser In `x?.[x = y]`, `x` is reassigned _after_ referencing it so it's safe to avoid a temporary variable.

**Comment by nicolo-ribaudo** [comment]
Hey, I realized that there is at least one case where a property access after an instantiation expression is meaningful:
```ts
function f<T extends 0 | 1 | 2 | 3>(this: T, a: T) {
   return this + a;
}

let fn1 = f<0 | 1>.bind(1);
let fn2 = f<0 | 1 | 2>.bind(1);

fn1(2); // error
fn2(2); // ok
```

**Comment by jakebailey** [comment]
That's an interesting case; we talked about this in the design meeting and while it feels like the true problem is the optional chaining, we're not certain enough about this syntax to allow it. We'd rather be conservative here about the syntax, given this is a hole we didn't see when the feature was merged. We can always revisit and allow this syntax, or some forms, but the main goal right now is to make sure people aren't writing spuriously incorrect code like the one in the original issue without knowing.
