### ISSUE TITLE
Nightly bug(?) with infering function generic while being part of intersection

### ISSUE THREAD

**Issue by toodols** [microsoft/TypeScript#49307]
First of all, the title exists for the sake of a title. I don't really know exactly what is wrong with this bug. I came across this while working on something with redux tookit.
<img width="300" alt="Screen Shot 2022-05-30 at 2 15 00 AM" src="https://user-images.githubusercontent.com/67543533/170959557-9742be58-a1de-4ccb-95ca-5f7db9582a64.png">
**Error**: `Parameter 'state' implicitly has an 'any' type.`
**Expected**: `state = WritableDraft<{username: string, isLoggedIn: true, ...}>`

I am using the nightly extension and the bug has not occured because of an update to redux toolkit or a change in my code, but has instead been because of typescript versions changing.
The code itself works in [typescript 4.7.0](https://www.typescriptlang.org/play?ts=4.7.0-beta#code/JYWwDg9gTgLgBAbzgYygUwIYzQZQDbDJoA0cAwulrgUQPJgzAQB2AzqQAoYCeeEGAEwCCyRi1L5CaMhlZoASmgEBXIlFZwAvnABmUCCDgAiAALoVADwBWrAPQwIEPAGtgMIwG4AsAChfaC0hYFBZWeGQCNGYYSSI4AF4USmxYtAAKBF8ASGYMEDQALmMySOijYmzgZjdgDDwcGCoizJ8srOU5KFz8oqNy7KzgVgAZCABzMaUASWYinTq5Ctb2zqmBXv7ljAA3LAwoDaWszSPzVTR1ZoGWEuAomABVTrIACwxmSYE0sKpSDFEmLM4FxePxhACWABKFptLK2WxwAB0yIGmmyaJ8mkhHiAA) but not in [typescript nightly/4.8.0](https://www.typescriptlang.org/play?ts=4.8.0-dev.20220530#code/JYWwDg9gTgLgBAbzgYygUwIYzQZQDbDJoA0cAwulrgUQPJgzAQB2AzqQAoYCeeEGAEwCCyRi1L5CaMhlZoASmgEBXIlFZwAvnABmUCCDgAiAALoVADwBWrAPQwIEPAGtgMIwG4AsAChfaC0hYFBZWeGQCNGYYSSI4AF4USmxYtAAKBF8ASGYMEDQALmMySOijYmzgZjdgDDwcGCoizJ8srOU5KFz8oqNy7KzgVgAZCABzMaUASWYinTq5Ctb2zqmBXv7ljAA3LAwoDaWszSPzVTR1ZoGWEuAomABVTrIACwxmSYE0sKpSDFEmLM4FxePxhACWABKFptLK2WxwAB0yIGmmyaJ8mkhHiAA)

In order to create a minimum reproducible example, I have tried to simplify it as much as possible, (which was harder than I imagined). The problem is rather weird, there are multiple parts that cause this bug and removing any will fix it. However, the issue remains, [version 4.7.0](https://www.typescriptlang.org/play?ts=4.7.0-beta#code/KYDwDg9gTgLgBAE2AYwDYEMrDgMwK4B2yMAlhAXMlujMAMqonLAA8AwugM7ABKwCeZlE4A+ABQBYAFBxZcLAKGcAXHADe0gJCaA2gGlVnGFBIEA5gF1VYozWCq1AXwCUAXhEA3CCQRbHcADJ1LV0AFThTOABrYABPCBw4Dm4+RWBhK3VHP2lnVS8fAG5paSpgOwYmYEkpTQ1azXQxdGcsnKlnIA) works while the same on [nightly](https://www.typescriptlang.org/play?ts=4.8.0-dev.20220530#code/KYDwDg9gTgLgBAE2AYwDYEMrDgMwK4B2yMAlhAXMlujMAMqonLAA8AwugM7ABKwCeZlE4A+ABQBYAFBxZcLAKGcAXHADe0gJCaA2gGlVnGFBIEA5gF1VYozWCq1AXwCUAXhEA3CCQRbHcADJ1LV0AFThTOABrYABPCBw4Dm4+RWBhK3VHP2lnVS8fAG5paSpgOwYmYEkpTQ1azXQxdGcsnKlnIA) errors.

At this point, I still do not know exactly what the problem is. In fact, it may even be intentional. However, this is something that breaks redux toolkit so I think the matter is something worth taking a look at.

What search terms have I used? None. I don't know how to put this bug into words.

**Comment by andrewbranch** [comment]
@typescript-bot bisect good v4.7.4 bad main

**Comment by andrewbranch** [comment]
A possible rebuttal of my analysis that I thought about but forgot to address: you might say that getting a property of a contextual type is fuzzier and more permissive than getting a property of that same type via something like a property access expression. For example, if I have a union type `string | { x: (state: string) => void }`:

```ts
type T = string | { x: (state: string) => void };
declare let a: T;
a.x; // Error because `x` is not on all constituents of the union

const y: T = {
  // `state: string` - we simply ignored the unuseful constituents when
  // doing the "same" operation on a contextual type
  x(state) {}
}
```

However, if the only relevant distinction was "getting a property of a contextual type is not the same as getting a property of a type generally," we would expect this to work:

```ts
let x: { [key: string]: (state: string) => void } & { f: object } = {
  f: (a) => {} // Error: `a` is implicitly `any`
};
```

and it does not. There is something different happening not just because there is a contextual type, but because of... well, something else around that mapped type mapping over `keyof T`.

**Comment by RyanCavanaugh** [comment]
Andrew and I kicked this around a while and think the right move on *this particular repro* is Won't Fix. Reasons for this:
 * The thing that broke it changes other things in demonstrably good ways
 * In the given repro, there's just no reason to write that index signature, since it only presumably subsumes the behavior of the existing typing since all functions are objects (and in cases where this is not the case, the error is correct). The one place it *doesn't* is symbol keys, and if you write `T in (keyof CaseReducers) & symbol]: {}`, then the code works as hoped-for
 * We don't really know how to fix it

So anyway if you have a repro that falls under both the "intersection *is* necessary" and "contextual parameter inference *would be* sound" umbrellas, we can take a look at that in a new issue. Thanks!

**Comment by lukeapage** [comment]
Redux Toolkit is the recommended way of doing redux and is highly used. The current documentation (https://redux-toolkit.js.org/usage/usage-with-typescript) is that when creating a slice, the state parameter does not need to be typed, as it will infer from the initial state.

You can see this error also on your New Errors bug: https://github.com/microsoft/TypeScript/issues/50028 - the redux counter example now fails.

I'm afraid I'm not enough of an expert to fully get what you are saying - are you suggesting that the redux toolkit types should be fixed to work with 4.8 by not having `{ f: object }` ? Since you have narrowed down the example I'm finding it hard to work out where in redux toolkit this is? somewhere here? https://github.com/reduxjs/redux-toolkit/blob/master/packages/toolkit/src/createSlice.ts#L227

or are you saying that this infer will no longer work and everyone using redux needs to copy-paste a state type argument on to every reducer case?

I'm going to create a issue with redux-toolkit and see if they have any better luck in figuring this out.

**Comment by lukeapage** [comment]
I tried to cleanup ValidateSliceCaseReducers to this:
```
export type ValidateSliceCaseReducers<S, ACR extends SliceCaseReducers<S>> = ACR & {
    [T in keyof ACR]: ACR[T] extends {
        reducer(s: S, action?: infer A): any;
    }
        ? A extends PayloadAction<any>
            ? CaseReducerWithPrepare<S, A>
            : never
        : CaseReducer<S, PayloadAction<any>>;
```

but it didn't help...

**Comment by andrewbranch** [comment]
Hmm, I actually think Ryan’s simplified repro may have simplified too far: in the simplification, the first intersection constituent was an object with an index signature, whereas in the real case, it is a type parameter _constrained_ to such an object. My analysis was based on the specific behavior we see in getting properties from an intersection like that. But in the actual redux-toolkit types, I can remove the constraint to the index signature and the behavior looks the same. So I think there’s something deeper going on here.

I will try to investigate a bit more. As a last resort, it certainly seems like we would be ok to revert https://github.com/microsoft/TypeScript/pull/48668 if we can’t fix this before 4.8 is released.

**Comment by andrewbranch** [comment]
[Simplified a little less:](https://www.typescriptlang.org/play?ts=4.8.0-beta#code/C4TwDgpgBAygNgSwMYQMIEMDOEBKEAmArigE6YA8Mw6wEAfFALxQDeAUFJ1ANoDSAXFEzASCAHYBzALqCAFMJoRBVRQEomDFbSgAfKADcA9gnwBuNgF9zbUJCgA1dInyL4yNFlwFiEMpQA0UACCqDhQEAAetGL4mLCIKBjYeESkFDB0DMwhYQBkrBxc3AAqUOJQsgDWECCGAGbBoaoyjTglUuFREDFx7Fz9UCTepPLKgehIwAiGYgD8guJ1vsGqguhiIOb9FlCzBQNcYENg6EOyAHSX6IJiEPq+3FKrUADyALYIwORBgQDkthBfnQtlwdoIWFZLNZ8BAkHBTtA6oQxJNpmIoEghq4EhBKNRaIEkl5Ur44pForF4u4iSkfH4tPQ6LJCoYwFMZphwYVOOJPggnAzlPjoHpZLJ1IxNMLVCDOEMSWRBI5nNjqZ5aWk8YpCerhqTgYULGxnkYTNZImBDCRgBiOTa4QhusA3CgmBisbQXRBZOwAJC8qYC4Vc32+wjYEhidBvJRQABEcf8bFDCEwABlDBIJAQAJJiQR1JzYJOh8O+HP4QQJku+9D6GinKuJ5MWEvyumcgqhmaoRBOgCqEdQAAt1tn8PJpV3QwB6GdQS7nZO+1stywyoA)

```ts
type SliceCaseReducers<State> = {
    [K: string]: (state: State) => State | void;
};

type ValidateSliceCaseReducers<S, ACR extends SliceCaseReducers<S>> = ACR & {
    [T in (keyof ACR)]: ACR[T] extends {
        reducer(s: S, action?: infer A): any;
    } ? {
        prepare(...a: never[]): Omit<A, 'type'>;
    } : {};
};

declare function createSlice<State, CaseReducers extends SliceCaseReducers<State>>(
  options: {
    initialState: State | (() => State);
    reducers: ValidateSliceCaseReducers<State, CaseReducers>;
  }
): void;

export const clientSlice = createSlice({
	initialState: {
		username: "",
		isLoggedIn: false,
		userId: "",
		avatar: "",
	},
	reducers: {
		onClientUserChanged(state) {
			// ...
		},
	}
});
```

**Comment by andrewbranch** [comment]
> But in the actual redux-toolkit types, I can remove the constraint to the index signature and the behavior looks the same.

I was wrong about this.

Minimal repro with the type parameter constrained to a record:

```ts repro
type Validate<T> = T & { [K in keyof T]: object }
declare function f<S, T extends Record<string, (state: S) => any>>(s: S, x: Validate<T>): void;

f(0, {
  foo: s => s + 1,
})
```

It looks like here, when we are trying to contextually type `s` from `T & { [K in keyof T]: object }` where `T extends Record<string, (state: S) => any>`, we are pulling exclusively from the mapped type template. (I can change `object` to be a function taking a parameter of some conflicting type, like `string`, and that contextual type “wins,” creating an assignability error at the call site.) So this is, after all, the same behavior I described earlier that is pervasive in intersections with index signatures. I don’t think it’s good, and it looks particularly bad here as a constraint, but it still is more consistent with how we handle index signatures elsewhere.

It looks like @phryneas has solved this on redux-toolkit, but we should keep an eye out to see if other things are impacted by #48668 too.

**Comment by phryneas** [comment]
Thanks for the further research!

It was a bit of an error on our side, since the intention was never to `& object` the properties of T that were functions - but only those that were objects in the first place. But the sudden change was definitely very irritating.

There is also more (probably unrelated to this) breaking in 4.8, in the ["generic" use cases](https://github.com/reduxjs/redux-toolkit/blob/a60e79d9dd87f393f16d991d6fab9623ef719954/packages/toolkit/src/tests/createSlice.typetest.ts#L442), but that's a lot less pressing than this one was - I'll see if I can investigate that further anytime soon.

**Comment by Meligy** [comment]
You can see a workaround for the redux case in user-land (where redux toolkit is the user of TypeScript) in this PR:
https://github.com/reduxjs/redux-toolkit/pull/2547

**Comment by markerikson** [comment]
Hi, I'm another Redux Toolkit maintainer. Wanted to follow up on this.

Lenz has put together a potential workaround on our side, but it requires what is frankly a pretty ugly hack (a separate package that abuses `typesVersions` to figure out what TS version we're dealing with, and changing what our `createSlice` type includes based on that).

Any thoughts on whether this issue is something the TS team intends to address before 4.8 is released?

**Comment by RyanCavanaugh** [comment]
I've been looking at `createSlice` today to try to figure out if there's something that can be done in userland to avoid the problem. 

The originating use case at #48812 is a lot more compelling due to its simplicity, but I don't like breaking Peter to fix Paul.

**Comment by markerikson** [comment]
@RyanCavanaugh thank you! Lenz is on vacation atm, but if you've got any questions or anything, please ping me . Appreciate you at least looking at this!

**Comment by RyanCavanaugh** [comment]
Is there a test suite or equivalent where I can try different definitions of `createSlice` to make sure I'm preserving the typing of the use cases?

**Comment by markerikson** [comment]
Yeah. We have both unit tests, and a set of "type tests".

- https://github.com/reduxjs/redux-toolkit/blob/master/packages/toolkit/src/tests/createSlice.test.ts
- https://github.com/reduxjs/redux-toolkit/blob/master/packages/toolkit/src/tests/createSlice.typetest.ts

to run them:

```
cd packages/toolkit
# Run just the createSlice unit tests
yarn test createSlice.test 
# Run _all_ the typetests
yarn type-tests
```

**Comment by Andarist** [comment]
Hmm, what's the current status of this particular issue? Is it considered to be a valid use case? I've found myself being somewhat confused by index signatures in more complex scenarios and I don't know how to properly reason about this.

Note that both latest reduced repros from @andrewbranch can be fixed by moving the intersection to the mapped type itself: [nightly TS playground](https://www.typescriptlang.org/play?ts=4.9.0-dev.20220811#code/C4TwDgpgBAygNgSwMYQMIEMDOEBKEAmArigE6YA8Mw6wEAfFALxQDeAUFFANoDSAXFEzASCAHYBzALoCAFEJoQBVBQEomDZbSgAfKADcA9gnwBuNgF8zbUJCgA1dInwL4yNFlwFiEMpQA0UACCqDhQEAAetKL4mLCIKBjYeESkFDB0DMzsnFwAKlBiUADWECAGAGZBIdJVOHmSYZEQ0bHZnFAkXqRySgHoSMAIBqIA-AJi5T5BKgLooiBmnOYc7SOsK+3tYJ1g6J0yAHRH6AKiEHo+XJIzUADyALYIwOSBAQBENhBvdIubUMubATBOq5SRmSxsNj4CBIOB7aDlQiiAZDURQJCdFzxCDkFaaCB+FaJTwpHyxCJRGJxNzE5LeXz4uhsOgyAxgQbDTACNpiJ4IRz4pTULS6GQyNSMDTCiAqX6dUlkAQOJxYmkeOmpSjSgK0rpkn4WG6GYxWCJgAwkYDozlW2EIZrAVwoJjozG0J0QGQ80R8gXS7kbKCEbAkUToe6KKBvN6EzYITAAGQM4nEBAAkqIBOVHNhY+1gz40-gBNG85x0HoaHsSzGVuY8-L6Vz1pthqhEA6AKoh1AACzmqfwcmlajamwA9OOoEcDoH63XCeZZZDPvZHMYFORcplWNweAU0SUypVQQJcrwGgAyKAGABGACsYVbltDYfCoIjkRy0eV-FB8hSzRUngSAWvg5BCCIEgBMOChKBKDBzCAGQ9LAAThEq67OLQW50EaRimJC5QyAADAEbTlAYBgCLEkqCFAADUUAAIyLioQA)

**Comment by phryneas** [comment]
@Andarist unfortunately, the `T[K]` would break `createSlice` in older TS versions, so it's not a fix that would work for us on it's own. So we now end up adding another conditional to decide between `{}` and `T[K]` depending on the TS version.

**Comment by markerikson** [comment]
@RyanCavanaugh : just to check, what was the final resolution? Just a reversion of the commit that caused this breakage for us?

**Comment by Andarist** [comment]
Since this has been fixed by reverting the other fix - could we reopen https://github.com/microsoft/TypeScript/issues/48812 ?

**Comment by RyanCavanaugh** [comment]
@markerikson correct - reverted in both 4.8 final and ongoing in `main`. Hopefully a fix can be found that satisfies both use cases.

@Andarist done 👍

**Comment by markerikson** [comment]
Thank you for taking a look at this!
