### ISSUE TITLE
Property 'message' does not exist on type '{}'.

### ISSUE THREAD

**Issue by CharleeWa** [microsoft/TypeScript#49318]
# Bug Report

### 🔎 Question

How to fix `unknow ` type ?

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
const res = { 'data': null }

const { data = {} } = res

console.log(data && data.message)
```

**Comment by jcalz** [comment]
This isn't a bug report, and questions about how to use TypeScript don't belong here.  Try [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript) instead (and if you do, please search for existing questions before posting your own).  Good luck!

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
