### ISSUE TITLE
Confusion: There's different result  when using the same javascript code with Intellij ideaIU and TypeScript

### ISSUE THREAD

**Issue by tancolo** [Microsoft/TypeScript#4936]
Hello, I'm a fresh man about javascript and TypeScript.
The environment as below:
1) Intellij ideaIU-14.1.4, TypeScript is 1.6.2
2) The others tools are installed.
3) Chrome version 44.0.2403.157 m

[Description]
the javascript code like this, very simpleness.

``` javascript
function max1() {
    console.log(arguments);
}
max1(1, 2, "Hello");
```
and the html like this:

``` html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test</title>
    <script type="text/javascript" src="index.js"></script>
</head>
<body>

</body>
</html>
```
When I run the Chrome and check the console like this: 
![intellij-ok](https://cloud.githubusercontent.com/assets/7859533/10037745/e8bce634-61ec-11e5-85c5-a6e41d559387.png)

==> ok, that's right!

But when I compile the same javascript code on TS, it tell me that one error is occured. 
![ts-error-01](https://cloud.githubusercontent.com/assets/7859533/10037812/f381be2c-61ed-11e5-9e4d-089722771c64.png)

But in the generated index.js, the JS code can also run on the Chrome.( console can show arguments info) 

[Confusion]
So my question is that since the js code can't be compiled to success in TS. But it can be also create the *.js file ,and the js file can be run.  So In my babyish opinion the largest benefit of TypeScript is checking compilation errors of JS. Right??
If that, I think when the compilation errors are occured, the file js(like index.js) should't be generated.

[Resolution]
Of course, this error has been fixed, when I add some arguments to max1.
like this:

```
 function max1(a, b, c) {
 	console.log(arguments);
 }
 max1(1, 2, "hello");
```

**Comment by DanielRosenwasser** [comment]
You can prevent the compiler from emitting using the `--noEmitOnError` option.

We still emit syntactically valid JavaScript despite errors because our philosophy is that the type system shouldn't have the final say on whether the code is runnable - the user might feel that that an error is overly restrictive, and so they have the final say on that.

Type-checking is certainly one of the biggest advantages of TypeScript; another is that we support features from ECMAScript 2015 (a.k.a. ES6, the most recent version of JavaScript), as well as some other syntactic goodies, even when emitting to ES3 targets.

For example, another way you could fix your issue is to use ES6 rest parameters:

```TypeScript
function max1(...args: any[]) {
    console.log(args);
}
max1(1, 2, "hello");
```

Hope that helps!
