### ISSUE TITLE
Incorrectly 'inferred'/'hinted' type for intersection types that uses generics

### ISSUE THREAD

**Issue by kaczor6418** [microsoft/TypeScript#49366]
# Bug Report

### 🔎 Search Terms

Incorrectly inferred/hinted type from types intersection if omit all Function  like fields

### 🕗 Version & Regression Information

- This is a compiler issue
- This behavior can be spotted (or earlier) since version 4.4.4 to 4.7.2 and Nightly
- I was unable to test this on prior versions because I want to avoid spending time checking every version below 4.4.4 (there are quite many versions, If it is required, please let me know, and I will do that)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.2#code/JYOwLgpgTgZghgYwgAgKIBsIFsAicxzIDeAUMsnAPwBcyIArlgEbQDcZyTtDzbHC3RiyjtyAE0G8R-ABbB0YqBBCThAbQC67AL4kSoSLEQoM2AJIgAzgRBJiHCKr7kYT6eQDmb0cjH44tKa4-jp6YACeAA4oAPIg6OEAClAA9tFQYMAQlgA8ACoAfMgAvPbkagDSyKDIANYQ4SkwyHkUli2VGsgQAB6QIGLtAGL0tpkpIMiUdBAAbtDItBUatHmdJLokEdHIAMIycCAeEGJ4BPndfcqDaJjBBAA0yABql-03QWdwRaUxWMBgHJxBLJNLQTLZfIFJ4AcgQcgUShAMKKADIysh4fJFMpaM9NKF9OBoPA7ABlaIIYAwYAIL4XXrvdpBCzWQ5IJ6vRnXdoUiBUml0-z5J6HcIFIrcgbtP4AnKffywuAojG9SIpDIACgAlLR9odjqdhc8nmsYX4CDCNAVCQh0HBLLzKdTaV8ABKHMSYKAMq7S27mKw2DkvN485B8gWu4V5UUgcVFYBYSJ3ZRgJ38l1C86xl5FUjkJglZAARh8CGLACYfGJiwBmcsInGTUoEvTkNUasA6vUHI4nekmjrm-xW-McchKMD0KCTAvkBdcUsPCcLgTIMBySwAOgQK4XC4kG6327E+4PmKbSNomlXunIum0QA)

### 💻 Code

```ts
interface ElemData {
  a?: number;
  b: number;
  c: number;
  d: number;
  children: number[];
}

interface ElemInstance {
  e: number;
  f: number;
  g: number;
  data: ElemData;
}

type OnlyProperties<T> = {
  [K in keyof T as T[K] extends Function ? never : K]: T[K]
}

type ChangedData<T extends ElemData, V extends ElemData> = Omit<OnlyProperties<T>, 'children'> & {
  children: V[];
}

interface SpecificData<T extends ElemInstance, V extends SpecificData<T, any>> extends Omit<ElemData, 'a'> {
  export(): ChangedData<V, T['data']>;
}

class SpecificDataHandler<T extends ElemInstance, V extends SpecificData<T, any>> implements SpecificData<T, V> {
  b = 1;
  c = 2;
  d = 3;
  children = [];

  export(): ChangedData<V, T['data']> {
    return {
      b: 1,
      c: this.c,
      d: this.d,
      children: []
    }
  }
}
```

### 🙁 Actual behavior

Only `children` field is required. Compilation error:

>Type '{ b: number; c: number; d: number; children: never[]; }' is not assignable to type 'ChangedData<V, T["data"]>'.
  Object literal may only specify known properties, and 'b' does not exist in type 'ChangedData<V, T["data"]>'.(2322)

### 🙂 Expected behavior

TypeScript compiler should require all fields from base `ElemData` interface excluding these that are omitted

### Comment:

I think type `export(): ChangedData<V, T['data']>` is incorrectly inferred/hinted. I think TypeScript compiler should require all fields that are not omitted from `ElemData` interface. Furthermore, I think like that because If V extends `ElemData`, then it means it has to be at leas `ElemData` (or I am wrong if yes, please let me know in comment). If you change code like below (`OnlyProperties<`**T**`>` -> `OnlyProperties<`**ElemData**`>`):

```typescript
type ChangedData<T extends ElemData, V extends ElemData> = Omit<OnlyProperties<T>, 'children'> & {
  children: V[];
}
```
to
```typescript
type ChangedData<T extends ElemData, V extends ElemData> = Omit<OnlyProperties<ElemData>, 'children'> & {
  children: V[];
}
```
Everything works and there are no errors

**Comment by RyanCavanaugh** [comment]
The Playground shows an error on `c`, not `b` - can you clarify?

**Comment by kaczor6418** [comment]
> The Playground shows an error on `c`, not `b` - can you clarify?

Sorry, I have copied error from a bit different playground. I have updated playground link and error message in issue description

**Comment by RyanCavanaugh** [comment]
There's a lot going on here but I think a smaller example demonstrates what you're seeing
```ts
type OnlyProperties<T> = {
  [K in keyof T as T[K] extends Function ? never : K]: T[K]
}
class Foo<T extends ElemData> {
  someMethod(obj: OnlyProperties<T>): OnlyProperties<T> {
    return {
      b: 1,
      c: 1,
      d: 1,
      children: []
    }
  }
}
```
When evaluating `OnlyProperties<T>`, the conditional type `T[K] extends Function ? never : K` can't soundly assume `T[K] extends Function` to be false -- a subtype of `ElemData` can legally have a property that is `number & Function`. This type instantiation is effectively fully deferred in any generic location; there's nothing you can write that will fulfill an `OnlyProperties<T>`.

This is a good thing, because the putative implementation of `export` is  unsound. You could instantiate `SpecificDataHandler` that had a more-specific type for `data.b` (say, for example, `b: 42`), and the implementation of `export` would wrongly provide a value of `1` into a binding with type `42`. There could also be extra properties, for example.

The only thing that's correctly assignable to a `ChangedData<T, U>` is another `ChangedData<T, U>`, rendering the entire "problem" of the deferred evaluation of `OnlyProperties` basically moot -- you can't possibly *yourself* construct one of these objects, only reuse an existing one.
