### ISSUE TITLE
Add a way to declare that a package should not add to the imports list (and make TypeScript use it)

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript#49418]
# Suggestion

Support a `package.json` entry which indicates that this package should be ignored from the global importing of identifiers (or maybe even special case typescript.) In order to not 'pollute' the auto-completion with TypeScript's APIs which most apps do not use directly.

## 🔍 Search Terms

typescript autocomplete remove typescript no auto imports opt-out imports

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

To use TypeScript, almost all node projects include `typescript` in their devDependencies - which opens them up to having auto-complete from the TypeScript API. For a lot of dev tools, using the JS API is  rare  but we include their APIs in the auto-completes - being able to declare that this is only relevant if the require/import is available in the current source file would mean that a lot of prefixes like `is*` are not full of tooling results where an accidental import could drag in a few MB of code to a bundler. 

![image](https://user-images.githubusercontent.com/49038/172400145-e6d6821c-50fd-4716-acff-6c7e32035eff.png)

## 💻 Use Cases

I'd imagine other tooling specific packages like prettier/eslint/etc could also use the same entry to indicate they aren't super relevant most of the time.

**Comment by andrewbranch** [comment]
There are two times that we look at your package.json in auto-imports:

1. What should we be proactively pulling into auto-imports that’s not _already_ in your program?
2. Of the things we found in your program, what should we filter out?

In the former, we only pull in `dependencies` and `peerDependencies`. But in the latter, any kind of dependency is allowed. So by design, projects _won’t_ get `typescript` auto-imports just by having it in their devDependencies. But they _will_ get them if `typescript` is already in their program, meaning they imported or referenced it already. I’m assuming that in your case, it wasn’t _you_ importing typescript per se, but one of your dependencies. We don’t currently track that in auto-imports, and it would take a bit of investigation to see how readily that info is available. If it had reasonably low complexity and near-zero perf impact, I think it would be a good idea to filter out devDependencies if they got in your program via a dependency rather than by your root files. I’m more pessimistic about a package.json field that says _always_ ignore this package, as there will always be API consumers of these packages, or always excluding devDependencies, as that would make writing tests and build scripts a pain.

**Comment by andrewbranch** [comment]
Semi-related and currently under investigation: #35395

**Comment by orta** [comment]
Yeah, I agree with all that - and it makes sense to me - judging on that second part, handling it properly starts to verge on per-file environments too. Which is a bird's nest I don't want to ruffle. Happy to close if you want 👍🏻

**Comment by andrewbranch** [comment]
Out of curiosity, what’s the dependency chain getting typescript into your project right now? (`--explainFiles` should tell you)

**Comment by orta** [comment]
It does explain why it _always_ happens to me:

```
  Imported via 'typescript' from file 'node_modules/@types/relay-compiler/lib/core/IR.d.ts' with packageId '@typescript-deploys/pr-build/lib/typescript.d.ts@4.6.0-pr-47126-18'
node_modules/@types/relay-compiler/lib/core/IR.d.ts
```

[AKA here on DT](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/80f099931572d06e3778dd3c1fe70fc72ff8b4bf/types/relay-compiler/lib/core/IR.d.ts#L9) will see if that's replaceable with a fake equivilent

**Comment by andrewbranch** [comment]
Haha, if I had a dollar for every time some weird misconfiguration was discovered due to auto-imports not trying to be overly smart 😄

**Comment by RyanCavanaugh** [comment]
Gonna call this a soft 'no' until we find more places this comes up
