### ISSUE TITLE
Type of keys is not correctly used be keyof

### ISSUE THREAD

**Issue by DaSchTour** [microsoft/TypeScript#49425]
# Bug Report

keyof doesn't use index signature to infer possible types of keys

### 💻 Code

```ts
type WithKeys = Record<string, any>;

class SomeClass<T extends WithKeys> {
   private foo: T;
   getItem(key: keyof T) {
      // TypeScript reports an error about implicit conversion of symbol
      console.log(`Get Item with key ${key}`);
      return this.foo[key];
   }

  method1(key: keyof T) {
    // needs typecasting
    this.method2(key);
  }

  method2(value: string) {

  }
}
```

### 🙁 Actual behavior

Typecasting to string is needed as keyof can also be symbol.

### 🙂 Expected behavior

`keyof T` can only be string

**Comment by MartinJohns** [comment]
> `keyof T` can only be string

Nothing in your code specifies this. `T extends Reord<string, any>` does not mean `T` only has `string` keys, it only means all `string` keys are compatible with the type `any`.

**Comment by DaSchTour** [comment]
@MartinJohns well I see that it's possible to do something like this, which for me doesn't make any sense and should not work.

```ts
type WithStringKeys = Record<string, number>;

const foo: WithStringKeys = {
  [Symbol('Bar')]: 'Not a Number!'
}
```

**Comment by DaSchTour** [comment]
It's even stranger. This fails with `Type 'unique symbol' cannot be used as an index type.(2538)`

```ts
type WithStringKeys = Record<string, number>;

const bar = Symbol('Bar');

const foo: WithStringKeys = {
  [bar]: 'Not a Number!'
}

const value = foo[bar]; 
```

So I can put something into the object with a symbol as a key but I can not retrieve it because the type of the object doesn't allow it. That doesn't make any sense.

**Comment by fatcerberus** [comment]
Types aren't sealed.  You can always assign an object with more properties to a type with fewer.  That's by design.  Your example is an error for the same reason this is:

``ts
interface Foo { foo: string };
const thing = { foo: "foo", bar: "bar" };
const foo: Foo = thing;  // okay
const bar = foo.bar;  // error, Foo doesn't have a 'bar' property.
// (even though it exists at runtime, we have no way to know what type it is now)
```

In your *original* example, `T` is *generic*, which means `keyof T` may very well include symbols.

See https://github.com/microsoft/TypeScript/issues/12936 for exact (sealed) types.

**Comment by RyanCavanaugh** [comment]
The confusion is that you think `[key: string]: T` means is "this object only has string keys and those properties are of type T".

What it actually means is "If a property exists at a string key, it has type T". There is no constraint on the type *or presence* of keys that aren't `string`

See also https://stackoverflow.com/questions/58458308/what-does-a-typescript-index-signature-actually-mean

**Comment by DaSchTour** [comment]
So there is no possibility to create an interface that says there is an object that only has string keys?

**Comment by MartinJohns** [comment]
There is not. This would require #12936, as mentioned before.

**Comment by DaSchTour** [comment]
Even this doesn't help any further
```
interface WithStringKeys {
   [key: string]: string;
   [key: symbol]: never;
}
```
I actually would have expected that TypeScript would have a solution for this looking at the maturity in other areas. Very very strange behavior.

**Comment by DaSchTour** [comment]
Isn't the documentation about `keyof` operator missleading? https://www.typescriptlang.org/docs/handbook/2/keyof-types.html

There is nothing about key beeing possibly symbol mentioned there!

**Comment by fatcerberus** [comment]
If I were to write `type FooKey = `keyof { foo: string, [sym]: string }` then it makes perfect sense that  I get `'foo' | typeof sym` , since `keyof` is the union of all the things the type system will let you use to index that object, and the symbol key has no canonical string representation.

The handbook shouldn’t be viewed as canonical technical documentation - it’s more of a “getting started” guide and often glosses over more advanced concepts (in this case there’s no need to bring up the possibility of symbols, since the example in question doesn’t use them).  Which can be frustrating sometimes I agree, but it is what it is.

**Comment by DaSchTour** [comment]
Yeah. But it actually also mentiones that key can be number.

BTW: The solution for the problem above is not exact sealed types but this: `type StringKey<T> = Exclude<keyof T, symbol | number>;`
