### ISSUE TITLE
Why is there no error when type assertion fails???

### ISSUE THREAD

**Issue by fanybook** [microsoft/TypeScript#49436]
# Suggestion
There should be an error when the type assertion fails

typescript
```js
let str: unknown = 'hello'
str = 666 // or str = null

let newStr:string = <string>bb

console.log(typeof newStr) // number
console.log(newStr) // 666

let slice = (<string>bb).split(',') // Error
console.log(slice)​
```

golang
```go
var str interface{} = “hello”
str = 666

// newStr, ok :=  str.(string) // ok is false
newStr :=  str.(string) // Error

// string operation
```

**Comment by guillaumebrunerie** [comment]
Because Typescript is not Go, `<string>bb` means "please consider `bb` as a string even if it isn’t". It does not (and cannot) check whether it is actually valid. When you use this notation, it's your responsibility for it to make sense. If you want runtime checks, you can write them using `typeof`.

**Comment by fatcerberus** [comment]
For the record, the term "type assertion" is maybe a bit misleading - it's not an "assertion" in the same sense as `assert(typeof foo === 'string')` - it's *you* asserting that the value is actually the type you say, regardless of what the compiler currently thinks it is.  You won't get a runtime error if you're wrong, because the type information is completely erased by the compiler.
