### ISSUE TITLE
Excess property check not working with certain intersections

### ISSUE THREAD

**Issue by ahejlsberg** [microsoft/TypeScript#49520]
### 🕗 Version & Regression Information

This is the behavior in every version I tried.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/DYUwLgBAHgjAXBA3hAJgQzGhysQM5gBOAlgHYDmEAvtRALxKoa44IBEAFiMMAPZsAaCACMERAK4hqVANwQIAegUQAolADGIPHggAHQr10hCYAJ4RjBwgChQkKACZsTTM9wESFWjQBkjKAD8CB5klDQMyOiujLic3HyCImKEktJyispqmtp6BkYm5pa8NnbQAMzOANoA1iCmwUShALpuDZ5htBEuLBCxXDz8QqIQElJUsvJKqhpaOvqGxmYWhFa24NAALFW19fiNFC0xbaHeEH7Igcde4YxRPX3xg0kjKWMTGRAAcrzLVgCE1iAA)

### 💻 Code

```ts
let x1: { data: { a: string } } = { data: { a: "hello", b: true }};  // Excess property error
let x2: { data: { a: string } } & { x?: string } = { data: { a: "hello", b: true }};  // Excess property error
let x3: { [key: string]: { a: string } } = { data: { a: "hello", b: true }};  // Excess property error
let x4: { [key: string]: { a: string } } & { x?: string } = { data: { a: "hello", b: true }};  // No error!
```

### 🙁 Actual behavior

No excess property error on the last line of example.

### 🙂 Expected behavior

Excess property errors on all lines of example.

**Comment by ahejlsberg** [comment]
This issue was uncovered by #49503. With #49503 there is now an excess property error issued in one of the test of the `waterline` Definitely Typed package. That error should have been there all along (and the test even seems to indicate so in a comment).

**Comment by jcalz** [comment]
Looks like the fix for this caused some unexpected excess property warnings in other intersections:

```ts
interface Baz {
  foo: { a: number };
}

const createDefaultExample = <K extends keyof Baz>(x: K): Baz[K] & { x: K; } => {
  return { a: 0, x }; // okay in TS4.7, error in TS4.8
}
```
[Playground link](https://www.typescriptlang.org/play?ts=4.8.2#code/JYOwLgpgTgZghgYwgAgEJwF7IN4ChnIwD2RAXDsnOSAK4C2ARtMgL4DcuLuuCRIAzmGQIoEOJAAiEeDQA2YAKIAPOHQAOslAF5kAHgDSyCEsggAJv2QBrCAE8iMNJgB8ACiXl9ASnLoMAbX0AXWQAMgoPZH02VmQtZxx8ZFEwGigQCipkAAYAGmQlVhiAemLkIis4W2RQZAAVAGUAFgA6AHZ86CgiKBqMxtaADk5uUuQhluyAWjMIADcWgCZsxeWANgBGJprLMAALFBhgKEFkMGA6FH2UOAYiOZRgSzgMrp6gA)
