### ISSUE TITLE
 Type tuples no longer inferred properly from rest arguments with mapped generic type tuples.

### ISSUE THREAD

**Issue by joelek** [microsoft/TypeScript#49556]
I recently updated the dependencies for a TypeScript-based project and unfortunately ended up with some unexpected breakage.

The TypeScript version was changed from 4.6 to 4.7 and type tuples are no longer inferred properly from rest arguments with mapped generic type tuples.

```ts
type MyMappedType<Primitive extends any> = {
	primitive: Primitive;
};
```

The project uses several helper types to map type tuples to other type tuples as shown below.

```ts
type TupleMapperOld<Tuple extends any[]> = {
	[Key in keyof Tuple]: Tuple[Key] extends Tuple[number] ? MyMappedType<Tuple[Key]> : never;
};
```

After updating to TypeScript 4.7 it is still possible to use the helper directly. TypeScript will correctly infer the type as expected.

```ts
// Type should be [MyMappedType<string>, MyMappedType<number>] in TypeScript 4.6 and TypeScript 4.7.
type MyMappedTupleOld = TupleMapperOld<[string, number]>;
```

However, type inference breaks when using the mapper to map the rest arguments of a generic function as shown below.

```ts
function extractPrimitivesOld<Tuple extends any[]>(...mappedTypes: TupleMapperOld<Tuple>): Tuple {
	return mappedTypes.map((mappedType) => mappedType.primitive) as Tuple;
}

// Inferred type should be [string, number] but becomes [unknown, unknown] in TypeScript 4.7.
const myPrimitiveTupleOld = extractPrimitivesOld({ primitive: "" }, { primitive: 0 });
```

The problem can be mitigated by explicitly specifying the generic type tuple argument. It can also be solved by removing the mapping constraints in the mapper as shown below.

```ts
type TupleMapperNew<Tuple extends any[]> = {
	[Key in keyof Tuple]: MyMappedType<Tuple[Key]>;
};
```

I decided to open this issue and let you decide if this is something worth investigating since I couldn't find any information about the difference in behaviour in the release notes.

### 🔎 Search Terms

tuple mapping
type inference
rest arguments
generics

### 🕗 Version & Regression Information

This changed between versions 4.6 and 4.7.

### ⏯ Playground Link

[Playground 4.6.4](https://www.typescriptlang.org/play?ts=4.6.4#code/C4TwDgpgBAsiMEMyQCYBVwQDwAUBOAlgLYHAEBu0EAHsBAHYoDOUC9IAfFALxQDeAKACQYQiTKUAXFHzFSFCAG4BAX2UDQkKGgCuYADYREyCHgDy+lFl0GqtBs1bsA2gF0uvQUOcBpCCCgCeigAa38AewAzbT1DV2kbQ19-VygaOkYWRIhneh0iACNTVIB+WHgkVAxIa1icvxB3KGl6CEo8ZTUBAQB6Hu1MKCYAC3CdSygiqGc4YyrMLCZgQnoAcw4AGnK5iHQFvMLTDlSggcgAZQBjQjBgKAAWADoANicUM4grm7ungHZHjSDWaVXbZCzvXjZHbmSxYZxLFarLYHIp4dzqSI6eiXMjhYLpPAIHGycQKJjg2q2NL2TJOEBuDgACkeLKIIL2kCYCTq0Ip2Q4AEpuVSvHgIMAdHhgmyTByIExHjLGYyZfNIAKeFxVaDMI9RHIJBANQgsnVOt0+lAAJL0SKmMXvTTQEZjCZTeHLIJIqAo4qTHR3IqXcJEeXTLEhejhADu9C2EajsZOwWqn2uBFuD0e-wEwfoSygRBAJPklDBE14BKJwBLhvJlkZfCg+tJUigACJ21AVFsmy3SxBpAAGbsC9ROmK2aEAOQg0cphmpGUcbHpTU8wmSAVOYRAUUncWkwNlqYX9RSHE66ktqaGo3G73dx7V2ARXs223Zp99eGOgRTmBfBmPwvG8HxAZmfwAhOz6gnUs7RjwB5GCCeAIXCb5rMi+Soui3SYtiuL4rQhLEmIA5MOh2RLg4LCrgyzKsl+mBcshM5zmegrCouoripK0rMZyipIMq2pyhq3BaoJEB6uRhrGqatjmr0-Q2naeAOlAE4ug+kzQB6iLYYcaL-uB6aQaBbDvKmEEgTmeYFkWtYKNkCFIVWZEGmSCGNs2ckKNInbdr2fleW2I4qGOQA)

[Playground 4.7.2](https://www.typescriptlang.org/play?ts=4.7.2#code/C4TwDgpgBAsiMEMyQCYBVwQDwAUBOAlgLYHAEBu0EAHsBAHYoDOUC9IAfFALxQDeAKACQYQiTKUAXFHzFSFCAG4BAX2UDQkKGgCuYADYREyCHgDy+lFl0GqtBs1bsA2gF0uvQUOcBpCCCgCeigAa38AewAzbT1DV2kbQ19-VygaOkYWRIhneh0iACNTVIB+WHgkVAxIa1icvxB3KGl6CEo8ZTUBAQB6Hu1MKCYAC3CdSygiqGc4YyrMLCZgQnoAcw4AGnK5iHQFvMLTDlSggcgAZQBjQjBgKAAWADoANicUM4grm7ungHZHjSDWaVXbZCzvXjZHbmSxYZxLFarLYHIp4dzqSI6eiXMjhYLpPAIHGycQKJjg2q2NL2TJOEBuDgACkeLKIIL2kCYCTq0Ip2Q4AEpuVSvHgIMAdHhgmyTByIExHjLGYyZfNIAKeFxVaDMI9RHIJBANQgsnVOt0+lAAJL0SKmMXvTTQEZjCZTeHLIJIqAo4qTHR3IqXcJEeXTLEhejhADu9C2EajsZOwWqn2uBFuD0e-wEwfoSygRBAJPklDBE14BKJwBLhvJlkZfCg+tJUigACJ21AVFsmy3SxBpAAGbsC9ROmK2aEAOQg0cphmpGUcbHpTU8wmSAVOYRAUUncWkwNlqYX9RSHE66ktqaGo3G73dx7V2ARXs223Zp99eGOgRTmBfBmPwvG8HxAZmfwAhOz6gnUs7RjwB5GCCeAIXCb5rMi+Soui3SYtiuL4rQhLEmIA5MOh2RLg4LCrgyzKsl+mBcshM5zmegrCouoripK0rMZyipIMq2pyhq3BaoJEB6uRhrGqatjmr0-Q2naeAOlAE4ug+kzQB6iLYYcaL-uB6aQaBbDvKmEEgTmeYFkWtYKNkCFIVWZEGmSCGNs2ckKNInbdr2fleW2I4qGOQA)

### 💻 Code

```ts repro
type MyMappedType<Primitive extends any> = {
	primitive: Primitive;
};

type TupleMapperOld<Tuple extends any[]> = {
	[Key in keyof Tuple]: Tuple[Key] extends Tuple[number] ? MyMappedType<Tuple[Key]> : never;
};

// Type should be [MyMappedType<string>, MyMappedType<number>] in TypeScript 4.6 and TypeScript 4.7.
type MyMappedTupleOld = TupleMapperOld<[string, number]>;

function extractPrimitivesOld<Tuple extends any[]>(...mappedTypes: TupleMapperOld<Tuple>): Tuple {
	return mappedTypes.map((mappedType) => mappedType.primitive) as Tuple;
}

// Inferred type should be [string, number] but becomes [unknown, unknown] in TypeScript 4.7.
const myPrimitiveTupleOld = extractPrimitivesOld({ primitive: "" }, { primitive: 0 });
//    ^?

type TupleMapperNew<Tuple extends any[]> = {
	[Key in keyof Tuple]: MyMappedType<Tuple[Key]>;
};

// Type should be [MyMappedType<string>, MyMappedType<number>] in TypeScript 4.6 and TypeScript 4.7.
type MyMappedTupleNew = TupleMapperNew<[string, number]>;

function extractPrimitivesNew<Tuple extends any[]>(...mappedTypes: TupleMapperNew<Tuple>): Tuple {
	return mappedTypes.map((mappedType) => mappedType.primitive) as Tuple;
}

// Inferred type should be [string, number] in TypeScript 4.6 and TypeScript 4.7.
const myPrimitiveTupleNew = extractPrimitivesNew({ primitive: "" }, { primitive: 0 });
```

### 🙁 Actual behavior

The type tuple is inferred as [unknown, unknown] in TypeScript 4.7.

### 🙂 Expected behavior

The type tuple is inferred as [string, number] in TypeScript 4.7.

**Comment by andrewbranch** [comment]
@typescript-bot bisect good v4.6.4 bad v4.7.4

**Comment by andrewbranch** [comment]
> ```ts
> type TupleMapperOld<Tuple extends any[]> = {
>   [Key in keyof Tuple]: Tuple[Key] extends Tuple[number] ? MyMappedType<Tuple[Key]> : never;
> };
> ```

What was the purpose of this conditional type? At a glance it seems like it should always evaluate true.

**Comment by jakebailey** [comment]
So, at first glance, the above appears to be intended to filter the keys of a tuple type to only the numeric indexes (so, filter out any named things like if you had `any[] & { foo: number }`, except that it seems to not really work correctly because if you have `[string, number] & { foo: number }`, `foo` wouldn't be filtered out because it has a value type of `number` and that is one of the values of the indexed types. It would seem like the right thing to write would be:

```ts
type TupleMapper2<Tuple extends any[]> = {
  [Key in keyof Tuple]: Key extends number ? MyMappedType<Tuple[Key]> : never;
};
```

This doesn't doesn't compile and has a confusing error at the call.

But, depending on what we think `keyof Tuple` is supposed to be comprised of, this would feel like it should always be true.

#48837 seems to be intended to change indexed accesses to arrays/tuples to not only be `number` but also `` `${number}` ``. So, if you change the above such that it is still always true (presumably, #48837 was a breaking change in that way), you can write:

```ts
type TupleMapper3<Tuple extends any[]> = {
  [Key in keyof Tuple]: Key extends (number | `${number}`) ? MyMappedType<Tuple[Key]> : never;
};
```

And this compiles with the original example in 4.7, so _maybe_ it's a workaround?

If we go back to the original example, it would seem like we could make the same transformation by adding `` `${number}` `` and write:

```ts
type TupleMapper4<Tuple extends any[]> = {
	[Key in keyof Tuple]: Tuple[Key] extends (Tuple[number] | Tuple[`${number}`]) ? MyMappedType<Tuple[Key]> : never;
};
```

Except that we get an error that says that `Tuple` cannot be indexed by `` `${number}` ``, which is what #48837 seems to have been intended to change, so that feels incongruent (as though there's some other part of the checker that also needs to be updated to allow this). I'm not sure if that's the entirety of the problem or if it's that + the fact that #48837 sort of broke the assumptions that code can make about what keys can be in arrays/tuples.

All examples better laid out here: [Playground Link](https://www.typescriptlang.org/play?ts=4.7.4#code/C4TwDgpgBAsiMEMyQCYBVwQDwAUBOAlgLYHAEBu0EAHsBAHYoDOUC9IAfFALxQDeAKACQYQiTKUAXFHzFSFCAG4BAX2UCBAek1QAtPo0DQkKGgCuYADYREyCHgCMWc1aq0GzVuwDaAXS68gkLeANIQIFAE9FAA1uEA9gBmphbWvtIu1qHhvlA0dIwsmRDe9GZEAEb2uQD8sPBIqBiQzqklYSD+UNL0EJR4ymoaKBAAxpYIeNCJZvSjZPHR+XgI87LiCkxOxXnuhV4gfhwAFAB050SNEOiYTBlttpCOra4cAJT3ruqji0zAUNQHDxdsAVmsxPJKFtjnwoKI5BIINIAETIqAqAA0-DhEMR0gADOi3sptFAyVAAHo1Qyk-S6QzGaDFR72ABML2sII8LDYhy6gWE2QiUViCWSxXSUA6XP2ZUq9igdTgLJuLWKQq6PT69kG6hG40m01m8wIixBYOA60hECY7J2+W5ByOZwuV1VNs+1hZeDtbXenqUGh+9D+ANZwOWq0tuM2rJhOIRChRaMx2PhGykUEJKmJWh05KpNJ0dIZmBSrm9AGYOW4Cp5eUdgUEhZFonEQEly2lpNKHftjnKqngoAAfKAAAwAJHxB-YVOO3or6irmth1R1NVBev1dcMxhMplAZnMFktaBarYimNX7Xt6z5-C7Tpc7O67l2bFc8De-R8P99fn+ahKwjc8o0vTZK3jdNrWTdEsVhGC8SzIkSXzMlCw0WkDA0RkP29AAWGsZXvPkAn4QVpRFdtOwlAMNRIlhjnVWc8FyMd1SnGdyiHedfEXJUGlfVcaw1LgtR3VQ9X3Q0j2NU9zXAmMoSI286x5B8TnOZ83VXd9mS-VTfwDACQyAgjQNBJTExU6DlKRKBUXgtN7IJVC83JSlqSAA)

**Comment by andrewbranch** [comment]
I think the upshot of this is that the purpose of the conditional type was to do exactly what #48837 does unconditionally, so it can just be removed. The conditional type _is_ a workaround for the previous weird behavior of mapping over generic tuples/arrays. That said, I think the lost inference in the original example is still probably a bug.

**Comment by jakebailey** [comment]
Just to complete my side investigation, the "Type '`` `${number}` ``' cannot be used to index type 'Tuple'." message is caused by our definition of the index type for `Array`, which is defined as `[n: number]: T`; changing this to `` n: number | `${number}`]: T `` makes the error go away, but does not fix the inferencing problem reported in this issue, so I doubt it is the cause like you say. (It also breaks a number of other things in mysterious ways, so I doubt it is a desirable change anyhow, at least not the prototype I tested.)

**Comment by jakebailey** [comment]
This seems to have turned out to just be a bug; see #52848.
