### ISSUE TITLE
Visual Studio IntelliSense errors from nested tsconfigs in node_modules

### ISSUE THREAD

**Issue by CodeBlanch** [microsoft/TypeScript#49553]
# Bug Report? Question?

### 🔎 Search Terms

I have searched the internet twice over on this 🤣 

* TS18003
* TypeScript Virtual Projects
* TypeScript IntelliSense errors
* Child/nested node_modules tsconfig errors

### 🕗 Version & Regression Information

* Microsoft.TypeScript.MSBuild NuGet v4.7.3
* VS 17.2.4

### 💻 Code

I have a project structure sort of like this...

```
AspNetCoreNet6Template
   Code\
      ...cs files...
   Program.cs
   package.json
   tsconfig.json
   index.ts
   Scripts\
      Utilities.ts
      MyComponent.svelte
   node_modules\
      @tsconfig\
          svelete\
             tsconfig.json
      ...lots of other things some of which contain tsconfigs...
```

For compilation I am using "external" (npm install / npm build via some custom targets). Build works totally fine!

When I open VS and then index.ts after a few seconds I get a TypeScript Virtual Project for AspNetCoreNet6Template\tsconfig.json. No IntelliSense errors, everything works totally fine. Then a few seconds later... an explosion of IntelliSense errors (hundreds) for any folder in node_modules that also contains a tsconfig.json. Lots of TypeScript Virtual Projects show up.

![image](https://user-images.githubusercontent.com/28367120/173738593-888763d4-56e9-438c-b549-95368ddf348b.png)

![image](https://user-images.githubusercontent.com/28367120/173740393-112b97a4-bedc-4fa4-b7bf-75c9ef3f2798.png)

Seems like what is going on is any tsconfig.json found under root becomes its own virtual project. In the case of svelte, its tsconfig is just a template meant to be extended from. The other stuff, I have no idea. Most of the artifacts in my node_modules are pulled in indirectly.

What I'm looking for is a way to tell the tools (IntelliSense) to not create any virtual projects for anything in node_modules under my tsconfig. I can use the VS option to only show errors for opened files but that isn't ideal because anyone who clones the repo is going to have to sort it out for themselves. Ideally there would be a way to do this via some file in the repo so a fresh clone is clean.

The closest thing I have found to a solution is https://stackoverflow.com/a/71774397 which is to go through node_modules and delete tsconfigs. There has to be a better way 🚀

**Comment by minestarks** [comment]
@CodeBlanch thanks for reporting. Are you able to try this on VS 2022 17.3 Preview 2 ? We just shipped a design change that (I believe) should fix this problem.

**Comment by minestarks** [comment]
@CodeBlanch in case you want to dig deeper in the current version of VS you have, it's hard for me to give you a definitive root cause without seeing your project, but there are a few things you can try.

Basically, VS (versions prior to 17.3 Preview 2) creates a "virtual project" for a `tsconfig.json` if it is included from the .csproj in an `<ItemGroup>` with an item type of `Content`, `TypeScriptCompile` or `TypeScriptConfiguration` . 

You can expand your project file by compiling with the [`/preprocess:`](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2022) switch and look for `ItemGroup`s that include the above file types. This can give you an idea about how these `tsconfig.json`s are getting included. Most likely, _some_ glob is supposed to exclude paths under `node_modules`, but it doesn't.

You can also simply try adding the following to your project to exclude these paths no matter what:

```
<ItemGroup>
  <Content Remove="**/node_modules/**/tsconfig.json" />
  <TypeScriptCompile Remove="**/node_modules/**/tsconfig.json" />
  <TypeScriptConfiguration Remove="**/node_modules/**/tsconfig.json" />
</ItemGroup>
```

Let me know how that goes for you. But if you'd rather wait, like I said, I'm fairly sure this problem is fixed in the latest VS since we are now ignoring items from .csproj files _entirely_ and only looking at open files when building virtual projects.

**Comment by CodeBlanch** [comment]
@minestarks Thanks for looking at this! I took it for a spin using VS 17.3.0 Preview 2 and things look much better. I opened all the .ts files in my solution and let it sit for a bit. What I ended up with is two virtual projects. 1 for my tsconfig and 1 called "Miscellaneous" for a random file that wasn't included by the tsconfig. No errors reported 🥂 I'll close this issue.

Regarding...

> Basically, VS (versions prior to 17.3 Preview 2) creates a "virtual project" for a tsconfig.json if it is included from the .csproj in an <ItemGroup> with an item type of Content, TypeScriptCompile or TypeScriptConfiguration .

I think this might be bugged. I put this into my project...

```xml
		<Content Remove="**" />
		<Compile Remove="**" />
		<None Remove="**" />
		<TypeScriptCompile Remove="**" />
		<TypeScriptConfiguration Remove="**" />
```

Everything in my project disappears from VS, as I would expect. When I turn on "Show All Files" it looks like this:

![image](https://user-images.githubusercontent.com/28367120/174121209-61dbdce7-cace-4a51-a4f0-ab5d4dcea27a.png)

However, I still get the virtual projects (and errors)! It seems like IntelliSense part isn't respecting the project?

![image](https://user-images.githubusercontent.com/28367120/174121493-43490a44-190f-4c62-95bd-1b935c957b79.png)

**Comment by minestarks** [comment]
@CodeBlanch glad to hear it! Thanks for reporting the oddness too, I may need to go back and update my understanding of how the current version works. I certainly _thought_ we filtered things out based on the project file but there may be gaps in that behavior. Let us know if anything else comes up!
