### ISSUE TITLE
Implicit this.property completions not returned while writing property

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#49566]
# Bug Report

### 🔎 Search Terms

- suggest / suggestions
- completions 
- insertText

### 🕗 Version & Regression Information

4.8.0-dev.20220614, not a regression

### 💻 Repo

For the following code:

```ts
class Foo { 
    private _prop = 123;
    public prop = _pr // trigger suggest here
}
```

Trigger suggestions on the public version of prop

### 🙁 Actual behavior

No suggestions shown.

### 🙂 Expected behavior

We should return a suggestion for `_prop` that inserts `this._prop` when accepted. This is what happens when you trigger suggestions inside of method bodies

**Comment by fatcerberus** [comment]
Somewhat off-topic but I always find it weird seeing `this` in a property initializer, because I tend to view the initializer as having static scope.  Similarly if I see `public x = Math.random()` I'll tend to think all instances will get the same value.  Having the initializer not be evaluated until the constructor is called is counterintuitive given the structure of the code.
