### ISSUE TITLE
The difference between `keyof T` and `T[number]`

### ISSUE THREAD

**Issue by wusfe** [microsoft/TypeScript#49608]
# Bug Report

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts

type TestFunOne<T extends any[]> = {
   [key in keyof T]: key;
}

type SomeTestTwo<T extends any[]> = {
   [key in T[number]]: key;
}
type test1 = ['a', 'b', 'c', 8, 1];

type result1 = TestFunOne<test1>; // ["a", "b", "c", 8, 1]

type result2 = SomeTestTwo<test1>; 
/**
 * {
    1: 1;
    a: "a";
    b: "b";
    c: "c";
    8: 8;
}
 */
```

### 🙁 Actual behavior
result1 returns the array type, result2 returns the object type

### 🙂 Expected behavior

Why both result1 and result2 return objects?

**Comment by Josh-Cena** [comment]
`keyof T` is the key type (i.e. `number | "map" | "filter" | ... | "0" | "1" | ...`), `T[number]` is the value type (i.e. `"a" | "b" | "c" | 8 | 1`). `T[number]` reads as "the type returned when `T` is indexed with a `number`". `TestFunOne<test1>` is `["0", "1", "2", "3", "4"]` instead of an object because it's a homomorphic mapped tuple.
