### ISSUE TITLE
Inconsistent error with Self-Referential Super Class `this` Type Reference

### ISSUE THREAD

**Issue by frank-weindel** [microsoft/TypeScript#49672]
# Bug Report

### 🔎 Search Terms

this, type context, class self-referential super class typing

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries that mention the word "this"
  - I tried 3.3.3333 up until 4.8.0-beta, including current Nightly

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.0-beta#code/JYOwLgpgTgZghgYwgAgEJwM4QCJzHZAbwFgAoZC5AI0wgAUoB7ABwEYAuZDMKUAcwDcZStVoMWAJk4gArgFsq0IaQC+ZMggA2mDMgCyAT1z4Awo3BxQ0IsMoATPHE7osxggF4b5EZRpZxbJwA5HBUCEEANLY+ov5MzFLIrBIAzNHIKsoi6XKMdsAwRo4AFA74nHRwUGDAcJoAPGAAFsAYANpBZXBBALoAfACUXjEUAPSjyNiMXIxyEM386Wqq6qSgkLCIKACiAB6QIHYQdm7IEPsQh7ouOI7DlOcHR3YBHNSMjJoQcCBZDxeHY4BRKyBRKMjLDTaDC6Qx7J7HNxmCxWKBnAF2WFFUzmfCo+4ULqceGXZ6nTwkbwxPz0eJvEJhSLpEQ04GcZIpKJUnyPUlAumcHgyCBckbohEveKJDlLZTpUYAKgVzIVyAAglA+PJLmBkIwYMgwAZmCggoRYrSWG8AES7AwAL2tAnFfMlVs48E0WGdKiCyFayBAjF1OmAfBAoS+humzCqcDmGz1BqNJuQQUq1VqDQW7WtXWt-SCADpiqkACwAVgGKuQNdQEAQcBkWGQAAMc63-SBDU0UCmUAhcY9-bog7qqIwZIdo-oDCTASdHMi8SBoCrRukYFOENsoEwoMUhpSxTmi7l8oU3MVj2LfGIBWm7famdyxbyF68PXUsMzKCoBn8FCQtyirKq+qp7MwmjAAgwBgJoBhcPMNQgHwPZ9saKD6m2HYjsgBAAO6MFAADWVSTocETUDIuo5nh5jQJOug-HYyB2IwEAYCAQS6nIcAkSgWAgD+4EbtyW4gAgADqxFkUwU52MUOacHCGKIkuuKWKuUBHr+FCnueBTYnA156T4rIPkET4vre-wSp+yCeiJYr-oBGQQqsoHCKqADydh2AhVEQAAbtABgLKheEwFY-oGgYk7II2miaOhbaGZeJQDJ2EkIDU5gulAEbJQY3liYOwm8QYADKMhUCY0K6J4q4EbO85khpKLaYecqkHI1W1fVOhnnkRlXjeFAWe6j4OjZdmug5TkQBCAFAA)

### 💻 Code

```ts
interface BaseData {
    baseProp1: string;
    baseProp2: number;
}

class MyDataContainer {
    data: BaseData = {
        baseProp1: 'abc',
        baseProp2: 123
    };
    
    modifyData(data: Partial<this['data']>) {
        // Do something
    }
}

interface ExtendedData extends BaseData {
    extendedProp1: boolean;
    extendedProp2: number;
}

class MyExtendedDataContainer extends MyDataContainer {
    data: ExtendedData = {
        baseProp1: 'abc',
        baseProp2: 123,
        extendedProp1: true,
        extendedProp2: 123
    };

    /**
     * Argument of type '{ baseProp1: "xyz"; extendedProp1: false; }' is not assignable to parameter of type 'Partial<this["data"]>'.(2345)
     * 
     * Because `this` in the type context is not bound to MyExtendedDataContainer
     */
    funcError() {
        this.modifyData({
            baseProp1: 'xyz',
            extendedProp1: false
        });
    }

    /**
     * Explicitly setting the type of `this` is a workaround, but this is onerous and doesn't make sense why its needed here
     */
    funcWorkaround(this: MyExtendedDataContainer) {
        this.modifyData({
            baseProp1: 'xyz',
            extendedProp1: false
        });
    }
}

/**
 * Oddly, everything is fine if you call the `modifyData()` function externally
 */
const mySubClass = new MyExtendedDataContainer();

mySubClass.modifyData({
    baseProp1: 'xyz',
    extendedProp1: false
});
```

### 🙁 Actual behavior

Error:
```
Argument of type '{ baseProp1: "xyz"; extendedProp1: false; }' is not assignable to parameter of type 'Partial<this["data"]>'.(2345)
```
in the call to `this.modifyData()` in funcError().

A work around exists, shown in funcWorkaround(), of explicitly setting `this` to the class. But shouldn't `this` already be implicitly set to that class?

### 🙂 Expected behavior

No error, because `this` should be implicitly set to the MyExtendedDataContainer class instance type.

### Description

Tried the best I could to describe this problem in the subject, but if there's a more clear way to refer to it, please update it. Jump to code first as the narrative might be unnecessary.

I'm trying to take advantage of the ability to reference `this` in the type context as a parameter type for a class method. My base class (MyDataContainer) has a `data` property with a set base data type interface (BaseData). It has a method `modifyData(partialData: Partial<this['data']>)` which would patch and update the `data` property. See that I'm using `this['data']` to refer inwardly to whatever the type of the `data` property is. The reason for this is so that someone can extend the base class that adds new properties to the BaseData interface. This is done in the `MyExtendedDataContainer` class.

What I'm trying to do seems fully comprehendible by TypeScript. It works fine, for instance, if I call `modifyData()` from outside of the class (i.e. `myExtendibleDataContainer.modifyData({ /* .. */ }` works fine). But I run into issues if I try to call `modifyData()` from within the class (i.e. `this.modifyData({ /* .. */ })`). Doing this gives me the error seen above. There is also a workaround by explicitly setting `this` within the calling function to `MyExtendedDataContainer`. But its unclear why this is needed as `this` should implicitly be `MyExtendedDataContainer` already.

I'm aware that something like this is attainable by introducing Generics. But that isn't possible for every use case.

Thanks in advance

**Comment by marckassay** [comment]
I think the error message is vague since object literals are being passed into `modifyData`. Would changing the following in `MyExtendedDataContainer` class:
```diff
-       this.modifyData({
-           baseProp1: 'xyz',
-           extendedProp1: false
-       });
+     this.modifyData(this.data);
```

... and changing the following in `MyDataContainer`:

```diff
- modifyData(data: Partial<this['data']>) {
+ modifyData(data: Partial<BaseData>) {
```

...and finally, change the following in your external usage example:

```diff
mySubClass.modifyData({
    baseProp1: 'xyz',
    extendedProp1: false
- });
+ } as ExtendedData);
```
... still would reach your objective?

**Comment by frank-weindel** [comment]
@marckassay Unfortunately not. Changing the first block especially, completely changes the behavior of my example. The goal is, whether internal/external you can call `modifyData()` exactly the same way and also get intellisense documentation / type-security that the object you pass to it conforms to ExtendedData.

**Comment by marckassay** [comment]
I see. You did mention you were able to accomplish this goal of yours using Generics. However, you mentioned doing so limits the versatility of this pattern without mentioning why. Below is a link to Playground demonstrating my usage of Generics accomplishing, I believe, what you're attempting; strong-typed parameter, intellisense.

[With generics](https://www.typescriptlang.org/play?ts=4.8.0-beta#code/JYOwLgpgTgZghgYwgAgEJwM4QCJzHZAbwFgAoZC5AI0wgAUoB7ABwEYAuZDMKUAcwDcZStVoMWAJk4gArgFsq0IaQC+ZMggA2mDMgCyAT1z4Awo3BxQ0ZAB5syCAA9IIACa70WY3AB8RYZSueHCcnjjByAC8-uQilDRY4mycAORwVAgpADQBcaKJTMxSyKwSAMy5yCrKlXKMrsAwRsEAFEH4nHRwUGDAcJp2PgCUMXkUAPTjyNiMXIxyEGAAFvyVaqrqpKCQsIgoAKLOEG4Qrt4OR24etOcksRROLq6nSRzUjIyaEHAgyiKPx2eriSxVkCiUZHWGm0GF0hkOT1O3jMFisUAuTzhzVM5nwaJsCMBSOCfjuIkq7RCyEJJzOEWiZLGCXohTeaQy2UqImZIM4pTKOXucQBtNenB4MgggrGGKJwMKxX5az+lEq4wAVOquerkABBKB8eTHMDIRgwZBgAzMFApQj5FksN4AIkcBgAXk6BLLRazOPBNFgvSoUshgLoQIwTTpgHwQOkvhbZsxunAFjtTebLdbkCkuj0+gNlmGANpOylOgC6PhSADoWuUACwAViG2uQbdQEAQcBkWGQAAMixh+6GQBaligsygELjHqHw5H3jI3In9AYaUDkbjLCBoNrxpUYMuEPsoEwoC0Roy8kOa3UGk1vC1rzL7WKc663ZyhTKRUD3-6WBcpQKhDCqFBQkKGpaj+OqHMwmjAAgwBgJoBhcIsvQgHw46TlaKBmgOQ4jmGyAEAA7owUAANbdIwy6uFk1AyCaQ7zqau5ML2ZErq4jAQBgIApCachwNRKBYCAQGwQeQpHiACAAOpUbRXFuC0Q6cPClybsEKJ4pxV7ARQt73o02JwM+xlxDyvofu636vpQf4vHZgEQNZoHgVUkKbDOUkiQYJgwro0S7uRa5bqinGXsochBSFd71OZT6ELZjqpOkmReZskzUgASvlADy+XIAAtFwoBIJFenbmiyB8Mc0BIexYTeGQ8XBToSUPhZVlCulyT2V+0rOTprkZcg7mQmBfnmNwyDxQAyjIVBdbCUTIOFa4bsSOLRdAsUdQYK1rYlZmPq0L6DWyn6OWNiLypN02qLNpBkHl+yFSV5WVQpKDaY9UUGdYjWcS1pG7XS+DHad60YD1KVXZUEbvikd2jQ841PUNL05aQQA)

There are 2 intentional errors in the demo above which indicates the parameter for `modifyData()` is strong-typed to the generic that is being used for that instance. And this works the same for internal/class usage.

At this moment, the only other thing that might work, is possibiliy [`ThisType<Type>`](https://www.typescriptlang.org/docs/handbook/utility-types.html#thistypetype). But doing so may require modifiying code in not so ideal ways.

**Comment by RyanCavanaugh** [comment]
This is a correct error. A class further derived from `MyExtendedDataContainer` could declare a more-specific type for `data`, for example defining that the only allowed values of `baseProp1` were `def` and `ghi`, and the call to `modifyData` would violate that declaration. This is the behavior you're opting *into* when using a `this[key]` type instead of referring to the declared type.
