### ISSUE TITLE
with infer in template string, suggestion works in 4.6, but not work in 4.7

### ISSUE THREAD

**Issue by xxleyi** [microsoft/TypeScript#49680]
# Bug Report

### 🔎 Search Terms

suggestion pathof

### 🕗 Version & Regression Information

4.7

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.4#code/FAehAIHMFMBdwGYCcD2BbcALWsAOBnALjEgEtZMBXAIwDoBjdENU+1fFBWEAFQE9c0AMptSubqXz5K0fCABMABgAs8gMwBiSdOiM0aaADtYAWgAcARnkBWAGzKzq4LAHRwABQCGFAPIIAPDwANOAA0uDQAB6wRgAm+OD4sEikhpAh7hHRcQlJKWngALzgAEQlAHxFwOBhWTGG8eAABgAkAN6pCNBI4ACqAL607Z3d4ABq-U3VNeAA-H11OeAA1tB8nOA8cx7emH6BANq9ALohYyGtbe797QO0TZWEze3X7avrCJvgAGTgABR5VKQcAAH3AhkoaGo3QAlJNpjUnuEovVGu8Nlt5pdXm1QpNwE9sTc2ujPltfgDkkDQeDIdCkHCmgBuYCs2K6AA2niQbgQlEM9FgpBQhnAjEM0gMSH8yOyDVyVLS5T+uF2Ty8vgCbU8T0BaRC1CebXousVkH6-RCoXKMIJtKh3RZrPFku6fwA5HR3TDgEA)

### 💻 Code

```ts

// get from https://github.com/microsoft/TypeScript/issues/20423#issuecomment-812564842
type PathOf<T, K extends string, P extends string = ""> =
  K extends `${infer U}.${infer V}`
    ? U extends keyof T ? PathOf<T[U], V, `${P}${U}.`> : `${P}${keyof T & (string | number)}`
    : K extends keyof T ? `${P}${K}` : `${P}${keyof T & (string | number)}`;


declare function consumer<K extends string>(path: PathOf<{a: string, b: {c: string}}, K>) : number;

// suggestion works well in 4.6, and not work in 4.7
consumer('b.')
```

### 🙁 Actual behavior

![image](https://user-images.githubusercontent.com/12626454/175751755-63f3d4b4-87e8-4d6a-81c2-69df4fd77e9a.png)

### 🙂 Expected behavior

![image](https://user-images.githubusercontent.com/12626454/175751850-261fdba7-2654-41e8-a29a-25b6b3beaec2.png)

**Comment by rbuckton** [comment]
This doesn't seem to be due to `infer`, but instead is a direct result of the changes in #48410. @andrewbranch, is this an intended consequence of that change? Prior to this change (or if I skip the call to `runWithInferenceBlockedFromSourceNode`), we instantiate `K` with the string literal type `"b."`. However, with `runWithInferenceBlockedFromSourceNode` we instead end up instantiating `K` with `string`.

**Comment by rbuckton** [comment]
Note that we have no suggestions in 4.7.4 for `"b."` because the suggestion list we return includes `"a"` and `"b"`, and `"b."` has essentially already filtered out the possible suggestions.

**Comment by andrewbranch** [comment]
No, not intended. The nonlinearity of conditional types makes it impossible to guess with any certainty whether a wider or narrower instantiation is going to produce better completions... maybe we ought to do both and concatenate the results.

**Comment by dmitri-gb** [comment]
We have also come across a somewhat similar case where the list of suggestions in TS 4.7 (and 4.8) is no longer the same as it was in TS 4.6.

```typescript
declare function pick<T extends object, K extends keyof T>(obj: T, ...keys: K[]): Pick<T, K>;

const obj = { aaa: 1, bbb: '2', ccc: true };

pick(obj, 'aaa', ''); // suggestions inside the empty string
                      // TS 4.6: aaa, bbb, ccc
                      // TS 4.7: aaa
```
[Playground link](https://www.typescriptlang.org/play?ts=4.7.4#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwAcswBrAHgBV4QAPDEVYAZ3hwCMArcDAGngGlqdBs3gkQATxyJ4FAHwAKdhwBcsvgDot4iUzX8A2gF0AlGoAKxchT785AbgBQjsHiYZWneAF54Ab3goILUARj42CLUAcgAmKL4wRLUMGGQEAF8nRyJSJU4+KKCoePgoqJMnIA)

It is worth noting that if I rewrite `pick` and make `keys` a proper array instead of a rest parameter, then the list of suggestions will include all the properties just as in TS 4.6.

Another way to get around the issue is to use a slightly different definition for `pick`:
```typescript
declare function pick<T extends object, K extends (keyof T)[]>(obj: T, ...keys: K): Pick<T, K[number]>;
```

It's unfortunate that the (seemingly) more natural definition of `pick` looses its ability to provide useful suggestions. I'm curious if this is something that the TS team would consider a regression and try to revert, or is this how we should expect things to work from now on?

**Comment by wwwouter** [comment]
I'm experiencing the same thing. It worked with 4.6.x, and it still works with 4.9.0-dev.20221007 and 4.8.1-rc 

4.6.4

<img width="867" alt="image" src="https://user-images.githubusercontent.com/997207/194931256-db1225d0-402e-4bbd-8635-086f66ee57c2.png">

4.7.4:

<img width="861" alt="image" src="https://user-images.githubusercontent.com/997207/194930986-4f490cda-3321-4ce1-81ef-fa193d50764d.png">

**Comment by itsUndefined** [comment]
Can this task get a higher priority?

**Comment by Andarist** [comment]
@dmitri-gb's and @wwwouter's cases are somewhat different from the OP. The problem with those 2 is that the type param is being used as rest but only the "current" argument is being "blocked". If all arguments typed through this rest would get blocked then it would work OK. At the same time... it's not that hard to imagine that a different piece within a given call could fix the inference in a similar way, so fixing this specific case by blocking sibling arguments that are typed through the same rest wouldn't necessarily fix the whole issue. OTOH, this particular use case is probably more common than those other cases so perhaps it would still be worth exploring this as a solution right now.
