### ISSUE TITLE
Conditional result is incorrect when providing generics parameters to a type within a class

### ISSUE THREAD

**Issue by igor-quotient** [microsoft/TypeScript#49769]
# Bug Report

### 🔎 Search Terms

* Conditional
* Generics

### 🕗 Version & Regression Information

In 4.7.4

- This changed between versions `4.4.4` and `4.7.4`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgJKoPICMBWAeAcQDU4AbAVwgD5kBvAKGWTCjhAGcYB7KAWwC5kACgBuZSoOLiIASmQBeGlIoQA3PQC+9ehAAeABx5hmAT30oAKgFFe+sCYCCUVidQwrAR3JlCY0gEYAGmQCPwAmGnkQv39kPUgQABN2aLIw5AB+ZABtAF1kQXRsfFCyfyp1bQRSOHYUiwh2MEICCBBoYAQaBiZ9KC59f0FrW3snFzdPb1IWto6EYIJW9qhOyJzc1WQAem3kCzMUAHI8o+RgFJAuY1r2YABzEDgsUhQwLlNzZCORu0dnOCudxeHxLOarBYhZbzKhHAB0QjCAGYwmEZIxkH0BmFhjY-uNAZMQTMQOReFhoMFSeToOs8ltdsgAO48ADW7E0QA)

### 💻 Code

```ts
interface IIObj<GValue> {
  transform: (value: GValue) => GValue;
}

export type TEmptyArrayIfEqual<Gval1, Gval2> = Gval1 extends Gval2 ? [] : IIObj<Gval1>;


class Test<GGeneric> {
  prop1: TEmptyArrayIfEqual<GGeneric, GGeneric> = []; // Type '[]' is not assignable to type 'TEmptyArrayIfEqual<GGeneric, GGeneric>'.(2322)
  prop2: TEmptyArrayIfEqual<number, number> = []; // works
}
```

### 🙁 Actual behavior

`prop1` is not assignable to []

### 🙂 Expected behavior

`prop1` should be assignable to empty array since same type(GGeneric )is provided as GVal1 & Gval2 params

**Comment by MartinJohns** [comment]
Resolving of conditional types involving unbound generic type arguments is deferred. At that point the compiler doesn't know what `TEmptyArrayIfEqual<GGeneric, GGeneric>` resolves to, because the compiler doesn't know what type `GGeneric` is.

**Comment by igor-quotient** [comment]
@MartinJohns Thanks for the answer! So if I'll strict `GGeneric`([link](https://www.typescriptlang.org/play?ssl=8&ssc=35&pln=8&pc=21#code/JYOwLgpgTgZghgYwgAgJKoPICMBWAeAcQDU4AbAVwgD5kBvAKGWTCjhAGcYB7KAWwC5kACgBuZSoOLiIASmQBeGlIoQA3PQC+9ehAAeABx5hmAT30oAKgFFe+sCYCCUVidQwrAR3JlCY0gEYAGmQCPwAmGnkQv39kPUgQABN2aLIw5AB+ZABtAF1kQXRsfFCyfyp1bQRSOHYUiwh2MEICCBBoYAQ43QTk5BByXixoGgYmfSgufX9Ba1t7Jxc3T29SFraOhGCCVvaoTsic3NVkAHpT5AszFAByPJvkYBSQLmNa9mAAcxA4LFIUMBcUzmZA3OZ2RzOOCudxeHw7Db7LYhXabKg3AB0QjCAGYwmEZIxkBMpmFZjYIYtocs4WsBkNoMF6cMoIc8idzsgAO48ADW7E0QA)) it should solve the 2nd case you have mentioned, right?

``
Resolving of conditional types involving unbound generic type arguments is deferred
``
Is there a way I can make the generic type arguments "bound"?

**Comment by MartinJohns** [comment]
> Thanks for the answer! So if I'll strict `GGeneric`([link](https://www.typescriptlang.org/play?ssl=8&ssc=35&pln=8&pc=21#code/JYOwLgpgTgZghgYwgAgJKoPICMBWAeAcQDU4AbAVwgD5kBvAKGWTCjhAGcYB7KAWwC5kACgBuZSoOLiIASmQBeGlIoQA3PQC+9ehAAeABx5hmAT30oAKgFFe+sCYCCUVidQwrAR3JlCY0gEYAGmQCPwAmGnkQv39kPUgQABN2aLIw5AB+ZABtAF1kQXRsfFCyfyp1bQRSOHYUiwh2MEICCBBoYAQ43QTk5BByXixoGgYmfSgufX9Ba1t7Jxc3T29SFraOhGCCVvaoTsic3NVkAHpT5AszFAByPJvkYBSQLmNa9mAAcxA4LFIUMBcUzmZA3OZ2RzOOCudxeHw7Db7LYhXabKg3AB0QjCAGYwmEZIxkBMpmFZjYIYtocs4WsBkNoMF6cMoIc8idzsgAO48ADW7E0QA)) it should solve the 2nd case you have mentioned, right?

`never` extends `number`. `never` extends every type.

> `Resolving of conditional types involving unbound generic type arguments is deferred`
> Is there a way I can make the generic type arguments "bound"?

It is bound as soon as the compiler has an actual type for it. For example `new Test<number>`, now the type argument is bound to the type `number`.

This is a design limitation.

**Comment by fatcerberus** [comment]
Generics are kind of like, if you write a function:

```ts
function foo(x: number) {
    console.log(x);
}
```

Inside the function, you only know `x` will be a number, you can't assume anything else about it besides what its type annotation requires.  `x` is basically in superposition.  So you're forced to write a function that works predictably for all possible numbers that the caller might use, lest you end up with weird bugs later.

With generics, it's like that, but with *types*, which puts you on a pretty tight leash because the compiler actually cares about types in a way it doesn't about individual values.  In `class Test<GGeneric>` the code inside the class must work for any type `GGeneric` can be, which can be literally any type at all, and the compiler actually tries to enforce this.  That's limiting enough, but in your case you also have a conditional type involved, and so long as you're in a context where the input to the conditional type isn't known, TS treats it as essentially opaque - it's only resolved to a usable type once TS has a concrete type to work with.

**Comment by sharshuv-quotient** [comment]
I'm not sure I understand...
if I change the left side of the condition like so:
```ts
type TEmptyArrayIfEqual<Gval1, Gval2> = Gval1 extends Gval2 ? [] : {};
```
It works. So typescripts correctly understand that the left side of the condition (`[]`) is that type it should resolve to. Why does it matter that I change the other type to include `Gval1` ?
Why doesn't the explanation about the possibility of "never" doesn't hold in the first case?

**Comment by RyanCavanaugh** [comment]
I think if we had been smarter, conditional types would have had restrictions on what kind of things you could write, with special syntax to opt into nonlinear behavior. See also https://twitter.com/SeaRyanC/status/1369397210094448643

**Comment by fatcerberus** [comment]
If by "nonlinear behavior" you're referring to distribitivity then yes, I've always thought it was... less than ideal that whether a conditional type was distributive was based on semantics (whether the input is a naked type parameter) rather than purely syntactic.

@RyanCavanaugh Was my analysis of the situation above accurate?

**Comment by RyanCavanaugh** [comment]
I mean writing a conditional type like `T extends U ? A : B` where `A` and `B` are disjoint.

**Comment by sharshuv-quotient** [comment]
@RyanCavanaugh Can you explain how the issue in the twitter post relates to the issue above?

**Comment by RyanCavanaugh** [comment]
The type `Gval1 extends Gval2 ? [] : IIObj<Gval1>;` is suspect because it can't correspond to a real runtime behavior, since this type claims to e.g. make a distinction between `string | number` and `string`, but if you're given a string at runtime there's no way to tell if it might have legally been a number.
