### ISSUE TITLE
Accessing property on null should fail

### ISSUE THREAD

**Issue by aaronshaf** [Microsoft/TypeScript#4981]
It seems that even without non-nullable types (#185), TypeScript should fail when attempting to access a property on a variable that is assuredly null.

```javascript
var o = null;
console.log(o.x);
```

... should fail.

**Comment by RyanCavanaugh** [comment]
The usefulness of this doesn't justify the complexity needed to implement it. With flow control analysis we could do more broadly-useful "use before initialization" things. And because JavaScript has `let` now, there's no need for `o` to exist before its initialization anyway, so these kinds of bugs should be rather rare in practice.
