### ISSUE TITLE
generator polyfill bug when use "function.call" call generator iterator next

### ISSUE THREAD

**Issue by konicyQWQ** [microsoft/TypeScript#49832]
# Bug Report

### 🔎 Search Terms

function.call and generator iterator

### 🕗 Version & Regression Information

- This is the behavior in every version I tried.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/zh/play?strict=false&noImplicitAny=false&strictNullChecks=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&declaration=false&target=1&ts=4.1.5&filetype=ts#code/GYVwdgxgLglg9mAVAAgOYFMwAoCUyDeAUMichAgM5wA26AdNXKlgJ4zrUAmyAjDoQF9ChAG4BDAE5pkAXjSZcAGjQAmWfOw4A3IVR0w6AB5RcO1Cv1GT24eKkBbdFAAWcbnL0HjZy8ax8dRxc3Oggxamosc2U+IA)

### 💻 Code

```ts
function* gen() {
    console.log(yield 1)
}

var g = gen(), g2 = gen();
g.next();
g2.next();

var method = g.next;
g.next(1);
method.call(g2, 1)
```

### 🙁 Actual behavior

```ts
1
```

### 🙂 Expected behavior

```
1
1
```

**Comment by rbuckton** [comment]
Native ECMAScript generators utilize an internal slot on the object to store state, allowing `next` et al to use the `this` value. Our helper utilizes a closure over the generator state, so our implementations of `next` et al cannot be torn off and reused in the same way.

We've previously chosen not to have 100% perfect alignment with the spec regarding the downlevel `__generator` helper, so long as we support the primary use case. For example, we do not expose a shared `GeneratorFunction` prototype or `Generator` prototype. In a per-file helper, those prototypes wouldn't actually be shared between files. We'd also like to avoid artificially increasing the size of the `__generator` helper merely to address pedantic semantic cases, since there are ways to inject your own version of our helpers to address specific needs.

This seems like a very narrow corner case, and the changes that would be necessary to achieve this do not warrant the impact to all consumers of the helper.
