### ISSUE TITLE
Code Generation - Line omitted from class constructor. 

### ISSUE THREAD

**Issue by troppoli** [microsoft/TypeScript#49854]
# Bug Report
Emitted javascript omits a line of code that should be be there. 

### 🔎 Search Terms
Code Generation, omitted line, missing, super

### 🕗 Version & Regression Information
This issues does not happen in 4.6.4, but does ever after. 
- This changed between versions 4.6.4 and 4.7.4

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.4#code/FDDGBsEMGdoAgEIwKYG9gF8TIB4AcB7AJwBc4IZ4AxAguXE5AOwBN4lo1g4fyCnoJIgFdQJYgApuvGXiIBLAG6RGcALbI1AI2REAXHC21wySEwA00ngEo46GTIDkTAOYBJJgCtkYxwG4rB2hhPF0JawCHXlB+aAITADpwAhcJRzgAdwALXWQ4FnkWOBIs+XgXAgB+ascIuAB6ergAHlbW4tL4cHkmPJdkEngCNXkSRiKeuH7eohVkIs9IZWhQBTwyGJZkQKwMIA)

### 💻 Code
```ts

class Base{
}

export class Foo extends Base{
    constructor(
        private member: boolean,
    ) {
        'ngInject';
        super();
        console.log(' where did this go???'); // <<<<< this line gets omitted in generated javascript code
    }
}
```

### 🙁 Actual behavior
Javascript output does not include the console.log statement.
```js
class Base {
}
export class Foo extends Base {
    constructor(member) {
        'ngInject';
        super();
        this.member = member;
    }
}
```
### 🙂 Expected behavior

All the code should make it through. If you duplicate the log line, then one of them will come through.

**Comment by fahadm** [comment]
FYI: 
I can see variants of this issue also happen in 4.6.2, 4.6.3 and 4.6.4.

So basically this has been broken since 4.6.0

Would it be possible to push the fix to the new 4.7.X, as otherwise we will have to resort to ugly hacks  (noop line) to get stuff working. 
I think it is a very silent bug that basically all hybrid applications will have to deal with when they migrate to angular 14 ( as you can only use typescript 4.6.X+ for angular 14)

Here is an example of the issue that is present on all versions after 4.5.5.

**Code**
```
class Base{
}

export class Foo extends Base{
    public currentYear: number = new Date().getFullYear();

    constructor(
        private member: boolean,
    ) {
        'ngInject';
        super();
        console.log(' where did this go???'); // <<<<< this line gets omitted in generated javascript code
    }
}
```
**Expected behavior**

The line should not silently disappear.
