### ISSUE TITLE
Incorrect TypeScript import suggestion

### ISSUE THREAD

**Issue by Heyoxe** [microsoft/TypeScript#49870]
Issue Type: <b>Bug</b>

**Minimal reproduction repository**: https://github.com/Heyoxe/vscode-typescript-incorrect-import-suggestion

**Reproduction steps**:
1. Have a type definition for a library relying on non publicly exported type (types not being exported in the `index.d.ts`)
2. Try to import one of the non public type in your code
3. TypeScript will suggested the types despite it being only exported in some deeply nested type and not by the `"types"` entrypoint

**Expected behavior**: TypeScript should not suggested these imports

VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:36.503Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.10.0-11-amd64
Remote OS version: Linux x64 5.10.0-11-amd64
Remote OS version: Linux x64 5.10.0-11-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (21.10GB free)|
|Process Argv|--folder-uri vscode-remote://ssh-remote%2Bworkstation/home/farroyo/dev/github.com/lddkb/ts-std --crash-reporter-id 127337f6-41d0-4c14-af39-c77f7138051c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: workstation|
|OS|Linux x64 5.10.0-11-amd64|
|CPUs|AMD Ryzen 5 3600 6-Core Processor (12 x 2200)|
|Memory (System)|62.73GB (2.99GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: workstation|
|OS|Linux x64 5.10.0-11-amd64|
|CPUs|AMD Ryzen 5 3600 6-Core Processor (12 x 2200)|
|Memory (System)|62.73GB (2.99GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: workstation|
|OS|Linux x64 5.10.0-11-amd64|
|CPUs|AMD Ryzen 5 3600 6-Core Processor (12 x 2200)|
|Memory (System)|62.73GB (2.99GB free)|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
gitpod-desktop|git|0.0.40
remote-containers|ms-|0.241.3
remote-ssh|ms-|0.82.1
remote-ssh-edit|ms-|0.80.0
material-icon-theme|PKi|4.19.0
better-toml|bun|0.3.2
vscode-database-client2|cwe|5.5.6
vscode-eslint|dba|2.2.6
gitlens|eam|12.1.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.5.0
gitpod-remote-ssh|git|0.0.32
rest-client|hum|0.25.0
protobuf|kan|1.1.6
vscode-docker|ms-|1.22.0
vscode-protolint|ple|0.7.0
prisma|Pri|4.0.0
vscode-yaml|red|1.8.0
datetime|rid|2.1.4
rust-analyzer|rus|0.3.1115
svelte-vscode|sve|105.18.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by andrewbranch** [comment]
This repro is not properly configured for Node. There are several problems:

1. You are using `"moduleResolution": "classic"` by default. If you are running in Node, you need to use `"module": "node16"` or `"module": "nodenext"` which will imply the correct `moduleResolution` setting as well. These are the only ones that support package.json `exports`. `'somelib/helper/incorrect.mjs'` resolves under `classic` without even going through `node_modules`, because `classic` is super weird and wrong and should never be used. (I am looking into making it not be the default for anything in the future.)
2. A `.d.ts` file cannot type a `.mjs` file, as you have in `somelib`. Either your declaration file should have the suffix `.d.mts`, or the `.mjs` files should be `.js` (the package.json already has `"type": "module"` so there’s no need for the `mjs` extension).
3. Your declaration file in `somelib` must use ESM-compatible module specifiers because it is an ESM declaration file due to `"type": "module"`. This means `export * from './lib/correct'` will not resolve, and needs to include the `.js` or `.mjs` file extension, depending on how you choose to resolve (2). In your particular example, `index.d.mts` should be identical in content to `index.mjs`. (I would encourage people not to hand-write declaration files like this, because it’s hard to get right. If you had generated these JS and declaration files with `tsc`, they would be guaranteed to agree.)
