### ISSUE TITLE
Type parameters constrained to type alias of generic class can't be used  with instanceof - TypeScript 4.8 regression

### ISSUE THREAD

**Issue by dragomirtitian** [microsoft/TypeScript#49937]
# Bug Report

### 🔎 Search Terms

generic type parameters type aliases generic classes instanceof 

### 🕗 Version & Regression Information

- This changed between versions 4.7.3 and 4.8-beta

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.0-beta&ssl=15&ssc=1&pln=1&pc=1#code/PTAEEkDNQFQQwEYBsCmoCWBnUA7A9jqAOYo4oBO6AxqBeXuaACZ4rb4AuoeVVAruQBQTFFSRxyaMXEzZ4yFAGFxsgDwBlUAF5QcHAE8AfKFABvQSZMB9SOhRImALlDrBAX0GCUADwAODLg59XzR5VG1YRFRlGUwAbk9IPhwqDnQCUEgcVRhabw5SJjkolEMACjxnGABKMwtLSQ4BQjwMHEwOPSoUPGgwpRVsEFpyekZ0QgAWADoADndPEWlJUCoCDu4qkoTWiY6unr6SmNlQYZgACywMbDwAa1BPJ88gA)

### 💻 Code

```ts repro
// If Table is non generic error does not occur
declare class TableClass<S = any>  {
    _field: S
}

export type Table = TableClass;

function fn<T extends Table>(o: T) {
    return o instanceof TableClass // error in 4.8
}

declare const o: Table;
o instanceof TableClass // This is ok 
```

### 🙁 Actual behavior

`o instanceof TableClass` causes an error when `o` is typed as a generic type parameter constrained to `Table` but not when `o` is typed as `Table`. This behavior is different in 4.7 and 4.8. In 4.7 neither of these was an error.

### 🙂 Expected behavior

`o instanceof TableClass` is valid in both cases

**Comment by dragomirtitian** [comment]
Also reported in Bloomberg feedback https://github.com/microsoft/TypeScript/issues/49835

**Comment by jakebailey** [comment]
@typescript-bot bisect good v4.7.4 bad v4.8-beta

**Comment by jakebailey** [comment]
Bisects to #49119.

**Comment by jakebailey** [comment]
Definitely something going on with the type flags. `T` is assignable to `boolean` for some reason. https://www.typescriptlang.org/play?ts=4.8.0-dev.20220718#code/CYUwxgNghgTiAEkoGdnwCpQEYRAYWlQB4BleAXnigDsBPAPnngG8AoJpgfQDMBLECMABc8EqwC+rViAAeABwD2MAC7xltOQkw4ElbbgIpkAbincArtTDLeC6vG7Ui6eLOUhqwNPpD0AFAoi6ACULOwcYHbIqjIiWAoKuDQU8AqmHPBwyuYw9grwvNTRNGAgCtwY2AaEyBJmlta29o4ATM6uMu6e3lX4Nf6BGKFsGZFFMXEJSfaUaeFMWTl5BeMlZRU+hqh1rKBIcIhRqoM+pvmFxVbrlTpbtUA

**Comment by jakebailey** [comment]
This is definitely a bad interplay of the changes in intersection reduction with relations; when the comparing a type variable to a union, we run `getEffectiveConstraintOfIntersection` on the type variable. It's supposed to be that when this recurses and the function is called on its own result, nothing changes, but it does, leading to some relations succeeding.

This means that currently, any type variable constrained to a type alias to a class is assignable to any union that contains a primitive: [Playground Link](https://www.typescriptlang.org/play?ts=4.8.0-dev.20220718#code/CYUwxgNghgTiAEkoGdnwCpQEYRAYWlQB4BleAXnigDsBPAPngG8Aoed+AfQDMBLECMABc8EiwC+LFgBdaABwSYcCSktwEUyANxTe1aSBjcoYBCQD2AWxDSAFnoDmzNhzkxzckdQCulrIZ1JFlAkOHhcaSoAIXNzXBoRLFj46h0Q6DCIqhJpGEcAeRgAOV9-GBFkXMd4AB94Hz8A4PAMhCyoHLzqB0KLaztHCqru2tErG3tunRZub2owaV5zanhuaiJ0eBAADwNqYDQ1EHoACnMRdABKZw5o5JAaCnhzHVuO4Z7i0sMnl5d2d5dT59CbVSh-f7wODSbwwFbmeB6So0UzmbgYbDqQjaCQsIA)

And that broke the `instanceof` code because the checker issues the aforementioned error iff the left hand side is not assignable to any primitive value. In checking that, it tests `boolean`, which is a union of `true` and `false`.

**Comment by fatcerberus** [comment]
> This means that currently, any type variable constrained to a type alias to a class is assignable to basically *any union*

Ouch.

**Comment by jakebailey** [comment]
I have a fix, but I'm currently verifying that it's not just a band-aid over top of some other problem.
