### ISSUE TITLE
Rename "tsconfig.json" to "tpsconfig.json" due to transphobia

### ISSUE THREAD

**Issue by tetherlaundromat** [microsoft/TypeScript#49932]
# Bug Report

The name tsconfig.json is triggering because it sounds like "trans configuration", as if trans people need to be fixed. I propose changing to tpsconfig.json
### 🔎 Search Terms

tsconfig.json

### 🕗 Version & Regression Information

Forever

### 🙁 Actual behavior

tsconfig.json sounds like "trans config", as if trans people are not good enough on their own and need configuring

### 🙂 Expected behavior

 tpsconfig.json which sounds more like typescript and less like trans

**Comment by owovin** [comment]
Does this really need to be changed? who cares. its a file name. it could be named dsklfjnfkltghfjkltfjklhdjfgkl.json for all i care and i wouldnt make a issue changing it.
:)

**Comment by zorbyte** [comment]
This is a poor representation of the trans community. If you really care about the trans community, you wouldn't make issues where they don't exist because transgender individuals have enough on their plate already. TS when said as an initialism or said as a word, is a far stretch from the word trans bar 2 sounds. You could just as easily made this extrapolation with the word trains. You're probably just a troll, but I think this ought to be said regardless.

**Comment by Mg138** [comment]
Does TG mean Transgender to you?

**Comment by nmggithub** [comment]
As a trans person myself, this is clearly a bad-faith troll post pretending to be trans to then screenshot and/or point to as an example of how unreasonable trans people are.

The only person who reacted positively (with many reacts, mind you) is a user who proudly admits to being banned for "thinking different" (which is, in my opinion, a telltale sign of someone who arrogantly holds onto objectionable (bannable) beliefs).

**Comment by RyanCavanaugh** [comment]
I don't think this merits a response.
