### ISSUE TITLE
"Expando assingment" for Javascript namespace stopped working.

### ISSUE THREAD

**Issue by mpawelski** [microsoft/TypeScript#49944]
Looks that the "declare a namespace with a function inside and expand the function with expando assignments" [workaround](https://github.com/microsoft/TypeScript/issues/37321#issuecomment-599812917) for my "JS namespaces" stopped working in TS 4.5

### 💻 Code
```
declare namespace app {
  function foo(): void;
}

app.foo.bar = (function () {
  const someFun = (arg: number) => {};
  return { someFun };
})();

app.foo.bar.someFun(1);
```

This works in [4.4.2](https://www.typescriptlang.org/play?ts=4.4.4#code/CYUwxgNghgTiAEA7KBbEBnADlMCqc3gG8BYAKHngDMBXRMAFwEsB7RallgCgEoAueADcWTYAG5yAX3Ll8mAHRVO8gEax4AXnhda9Zm209i5SmDboG8dCzQAxOpu2wA5gMQ0UKkDCMaAfMSSEhTwcAw0MOxEVjYg9uxBUjy8wbIEispqMPLWdnRcAIw8YkA).
This doesn't work in [4.5.5](https://www.typescriptlang.org/play?ts=4.5.5#code/CYUwxgNghgTiAEA7KBbEBnADlMCqc3gG8BYAKHngDMBXRMAFwEsB7RallgCgEoAueADcWTYAG5yAX3Ll8mAHRVO8gEax4AXnhda9Zm209i5SmDboG8dCzQAxOpu2wA5gMQ0UKkDCMaAfMSSEhTwcAw0MOxEVjYg9uxBUjy8wbIEispqMPLWdnRcAIw8YkA)

### 🙁 Actual behavior

Compiler error:
```
 Function implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.
 ```

### 🙂 Expected behavior

No error with proper inference.

**Comment by babakks** [comment]
@mpawelski I just tested with v4.7.3 and it worked (compiled with no error) and this is the resulting JS file:

```js
app.foo.bar = (function () {
    var someFun = function (arg) { };
    return { someFun: someFun };
})();
app.foo.bar.someFun(1);
```

**Comment by mpawelski** [comment]
@babakks 
To be clear it does compile when I don't use  [`--noImplicitAny`](https://www.typescriptlang.org/play?noImplicitAny=false&ts=4.7.4#code/CYUwxgNghgTiAEA7KBbEBnADlMCqc3gG8BYAKHngDMBXRMAFwEsB7RallgCgEoAueADcWTYAG5yAX3Ll8mAHRVO8gEax4AXnhda9Zm209i5SmDboG8dCzQAxOpu2wA5gMQ0UKkDCMaAfMSSEhTwcAw0MOxEVjYg9uxBUjy8wbIEispqMPLWdnRcAIw8YkA) option.
But then `app.foo.bar` is `any` which is not the case in [4.4.2](https://www.typescriptlang.org/play?ts=4.4.4#code/CYUwxgNghgTiAEA7KBbEBnADlMCqc3gG8BYAKHngDMBXRMAFwEsB7RallgCgEoAueADcWTYAG5yAX3Ll8mAHRVO8gEax4AXnhda9Zm209i5SmDboG8dCzQAxOpu2wA5gMQ0UKkDCMaAfMSSEhTwcAw0MOxEVjYg9uxBUjy8wbIEispqMPLWdnRcAEQA7jBszvDYMKgFPGJAA) where I get proper type inference and validation

**Comment by babakks** [comment]
@RyanCavanaugh I tried to debug/compare on both the current dev (v4.8) and v4.4.2.

At last, it seems like the problem has something to do with the `getContextualReturnType` function where it checks for immediately-invoked-function-expressions (this section was not present at v4.4.2):

```ts
function getContextualReturnType(functionDecl: SignatureDeclaration, contextFlags: ContextFlags | undefined): Type | undefined {
// ...
      const iife = getImmediatelyInvokedFunctionExpression(functionDecl);
      if (iife) {
            return getContextualType(iife, contextFlags);
      }
// ...
}
```

When the control reaches this, `iife` is assigned with `true` (returned from the `getImmediatelyInvokedFunctionExpression` function) and then the `getContextualType` function is called, which then tries to resolve the return type of the immediately-invoked function expression by walking up the nodes tree and finally reaching the `bar` symbol, again (because it was all started when `bar` was first encountered by the checker). So, the circular relationship is concluded.

To confirm this I introduced a new parameter to the `getContextualReturnType` to let it optionally skip the IIFE contextual type checking. It worked and the circular reference errors were gone. Obviously, this is not a viable solution and I don't know what can be done.

@mpawelski One workaround for this, though I'm sure you've already found that, is to separate the function definition and the invocation like this:

```ts
declare namespace app {
    function foo(): void;
}

function expand() {
    const someFun = (arg: number) => { };
    return { someFun };
}
app.foo.bar = expand();

app.foo.bar.someFun(1);
```

**Comment by Zzzen** [comment]
It's not related to IIFE, a simple object literal have the same error. [playground](https://www.typescriptlang.org/play?ts=4.9.0-dev.20220827#code/CYUwxgNghgTiAEA7KBbEBnADlMCqc3gG8BYAKHngDMBXRMAFwEsB7RallgCgEoAueADcWTYAG5yAX3LkA9LPgByAEaxF8JikwQmYJgwgBPeAAso6eA0OYEiqIkPrl4KDXQJ98YCwxIWDUyhBPEtrPEREfyhmNnh7YA0LOCoQOHoQBOAmOEYjeBYYDUQsnINjJnZ9CxYAd0rEfSYoHQAvVIA6LgB2AAYAJj6ecnxMdqpOdtVCgF5ickp0FjQAMTouWABzAUQaFGcYHmJpMkkJMmGCMYmp9sWVtYBGHjEgA)

```ts
declare namespace app {
  function foo(): void;
}

// 'bar' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.(7022)
app.foo.bar = {
  someFun(arg: number) {}
};

app.foo.bar.someFun(1);
```
