### ISSUE TITLE
TypeScript adds suffix "_1" to some variable names and spoils sourcemaps

### ISSUE THREAD

**Issue by myshov** [microsoft/TypeScript#50036]
# Bug Report

TypeScript adds suffix "_1" to some variable names when the option `target: es5` is present. Because of this in some places of the code DevTools can't resolve symbols in the debugger (tested in Firefox and Chrome).

### 🔎 Search Terms

_1 suffix
es5 suffix

### 🕗 Version & Regression Information

I tested in all versions available in the playground. The bug is present in all cases.

- This is a crash: NO
- This changed between versions: n/a
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about: YES (tested in all versions available in playground since 3.3.3 up to nightly)
- I was unable to test this on prior versions because: n/a

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=1&ts=4.7.4#code/JYOwLgpgTgZghgYwgAgILIN4Chm+cAEwC5kQBXAWwCNoBuLAXyywgA8AHAeyjGRjJAIwwTiD4gAFIRLlq0AJQlUAbQC6mHHgA2EXnChQ4ATwDyMVErXIAvMmUZpyAIwAGBgBpMhZEScNV9Hj4MMhSBMgAhNa2AEzyGkFBCKIAzrwIABYQCADWJlQAVjZeBEyaicGhmdl5hQB03tG2TvHYFRVQumRQYvqGpuZ1MMBakFASElrx1gB8yFoN4U3I1bn5BYvyge1MQbt4nWDdYvaObgGMQA)

### 💻 Code

```ts
// target: es5
interface A {
    id: number;
}

export function fn(id: number): A[] {
    let arrayOfA: A[] = [{id: 10}, {id :1}];
    if (id !== 2) {
        const checkObj = {id}

        if (checkObj.id === 1) {
            return arrayOfA.filter((l) => l.id === checkObj.id);
        }
    }
    return [{id: 0}];
}
```

### 🙁 Actual behavior

Transpiler transforms the symbol `checkObj` to `checkObj_1`.

### 🙂 Expected behavior

Transpiler should keep the current symbol intact

**Comment by myshov** [comment]
Probably related to the issue #21177

**Comment by IllusionMH** [comment]
More like #9627

Suffix is required to avoid name collisions in not so trivial cases, e.g. imports, destructurization etc. And if not here, then in that places you would still have same problem

**Comment by RyanCavanaugh** [comment]
Adding a `_1` here is a little weird, not sure why that's happening - would accept a PR to fix it if there aren't downside. But it's not a bug per se, these transforms are necessary in many places and the source map does accurately reflect those renames. Debuggers not supporting name lookup is not something we can control.

**Comment by DanielRosenwasser** [comment]
I believe the reason we do this is because if you capture a block-scoped variable in a closure, you possibly open yourself up to use-before-declaration (what TDZ is supposed to enforce).

```ts
export function fn(id: number){
    {
        const checkObj = {id};
        [].map((l) => checkObj);
    }
    {
        [].map((l) => checkObj);
        const checkObj = {id};
    }
}
```

If you never uniquified these, downleveling `checkObj` to a `var` would leak and be reused in in the subsquent block (where it's not supposed to exist at all).

So when a `let`/`const` is not at the top-level of a function, and it's captured by a closure, we need to play it safe and uniquify, and the naive approach works well enough.

THAT SAID, if someone wants to try to fix it, the temporary variable generation strategy `GeneratedIdentifierFlags.Optimistic` might fix it, but it might impact *a lot* of baselines.

**Comment by gabzim** [comment]
> GeneratedIdentifierFlags

how do we use that flag?
