### ISSUE TITLE
type alias does not work with classes

### ISSUE THREAD

**Issue by BBGONE** [Microsoft/TypeScript#5014]
I defined a class:

        export class TCommand<TSender, TParam, TThis> 
        {
        }

and created a synonym for the closed type:

     export type Command = TCommand<any, any, any>;

now when i try:

     export class NextCommand extends Command {
     }

the compiler says: Error	1	Cannot find name 'Command'

but i can write

      var cmd: Command = null;

without errors,

Expected: to allow using this type synonym for inheritance purposes.

**Comment by BBGONE** [comment]
var cmd = new MOD.mvvm.Command();

Does not work too. The same Error!

**Comment by mhegazy** [comment]
The problem here is `extends` needs a value to use at run time.  The generated code will look something like:

```js
var NextCommand = (function (_super) {
    __extends(NextCommand, _super);
    function NextCommand() {
        _super.apply(this, arguments);
    }
    return NextCommand;
})(Command);  /// notice Command is not defined.
```

So you can only extend from *value*. the type alias `Command` is just an alias, another name you can use in the TS code to refer to type `NextCommand` and does not exist in the generated code, this is why you can use it in a type position, e.g. `var cmd: Command`, as this has no implication at run-time.

you can achieve what you want by creating a new class, something like:

```ts
class Command extends TCommand<any, any, any> { }

// then this works
export class NextCommand extends Command {
}

// and this:
var cmd = new MOD.mvvm.Command();
```

for more information about what is *value* vs. what is *type* see: https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Declaration%20Merging.md#basic-concepts

**Comment by BBGONE** [comment]
@mhegazy 
Thanks for yor reply. It was not a problem if typescript would create a true alias.
That means instead of "Command" put in that  place TCommand - because "Command"  is only an alias for TCommand. We need replacements, not a new definition "Command" in the compiler's output.

**Comment by mhegazy** [comment]
if you want an alias for both value and type use `import`:

```ts
export import Command = MOD.mvvm.TCommand;
```

for your request, see #2559

**Comment by BBGONE** [comment]
@mhegazy 
Is this would work too?
export import Command = MOD.mvvm.TCommand;<any,any,any>

**Comment by mhegazy** [comment]
yes.

**Comment by BBGONE** [comment]
@mhegazy 
No it dos not work with generic parameters

**Comment by mhegazy** [comment]
> No it does not work with generic parameters in TCommand

Please see #2559 .
