### ISSUE TITLE
Declaring an existing module / namespace

### ISSUE THREAD

**Issue by TFTomSun** [microsoft/TypeScript#50143]
I want to write a type declaration that allows me to write Typescript that compiles to the following output 
```js

class MyTest{

    public  Test() {
            var instance = new mymodule.MyClass();

    }
}

```

There should be no import generated, because the Javascript library gets already imported somewhere else.

I tried already many possible solutions to solve it, one of them is the following typescript declaration
```ts

export module mymodule{
 export class MyClass{
 }
}

```
I try to use import type, because I don't want to get the import compiled to the Javascript file.

```ts
import type { mymodule } from "./Declaration.ts"


class MyTest{

    public  Test() {
            var instance = new mymodule.MyClass();

    }
}
```
The compiler fails with the following error message:

`
mymodule' cannot be used as a value because it was imported using 'import type'`

When I use import (without type), then I get the import compiled into JavaScript, which fails at runtime.

Is there a possibility to write the declaration that it simply works without emitting any import?

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
