### ISSUE TITLE
[Question] Co-operate on an object without central control

### ISSUE THREAD

**Issue by loynoir** [microsoft/TypeScript#50174]
# Suggestion

## 🔍 Search Terms

`co-operate on object` `plugin` `iter over list type` `merge`

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

Given
```ts
import type { Merge } from "type-fest";

const pluginFoo = () => ({ 'foo@checksum': 1 });
const pluginBar = () => ({ 'bar@checksum': 1 });
const pluginBaz = () => ({ 'baz@checksum': 1 });
const pluginQux = () => ({ 'qux@checksum': 1 });
const metadataPlugins = [pluginFoo, pluginBar, pluginBaz, pluginQux] as const;
```

Expected
```ts
type IMetadata = {
    'foo@checksum': number;
    'bar@checksum': number;
    'baz@checksum': number;
    'qux@checksum': number;
}
```

Implement needs hard code. Very dirty, and not scalable,
```ts
type IMetadata = Merge<
  ReturnType<typeof metadataPlugins[0]>,
  Merge<
    ReturnType<typeof metadataPlugins[1]>,
    Merge<
      ReturnType<typeof metadataPlugins[2]>,
      ReturnType<typeof metadataPlugins[3]>
    >
  >
>;
```

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
