### ISSUE TITLE
compiler signal error using recursive type where it shouldn't be 

### ISSUE THREAD

**Issue by andrewasd** [microsoft/TypeScript#50208]
**Code** 

```
type mytype = 
{
   value:myType|string[]
}

const a:mytype = {
     value:["str1","str2"]
}

const b:mytype = {
    value:a
}

console.log(b.value.value[0]) // expected behaviour to print "str1" but gives error 
```

**Behaviour**
get error
_Property 'val' does not exist on type 'myType | string[]'.
  Property 'val' does not exist on type 'string[]'_

**Expected Behaviour:**
print "str1"

**Comment by whzx5byb** [comment]
The type of `b` is `mytype`, so `b.value` is `mytype | string[]`, on which you can't access `value` because `string[]` doesn't has a `value` prop.

If you want the literal type of `b` to be preserved, see https://github.com/microsoft/TypeScript/pull/46827. Here is [a playground](https://www.staging-typescript.org/play?ts=4.7.0-pr-46827-30#code/C4TwDgpgBAtiqSgXigKAN6qtgbgQwBsBXCALjgQgB8BnYAJwEsA7AcwG0BdVAX1VQDGAe2Z0oeZFEzYZ+YmXYAiOvQCMigDTKGAJkXceUGnmCMaAM0YQaseOAj9ho4FABGk6bMIlSeXkZMzS2tbSkcRGiECCAA6AiFWAApXGLkSVO8IdgAGTgBKIA).
