### ISSUE TITLE
Unable to assign self to indirect self-referential union generic

### ISSUE THREAD

**Issue by Seamooo** [microsoft/TypeScript#50283]
# Bug Report

### 🔎 Search Terms

union generics
self-referential generic
ndarray
recursive type references

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about generics

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYg9nAKuCAeRA+KBeKiDaAulAD54DcAUKJFAEICGATspOlrvEiql62pgxUa0APJhgAQSZMGIdjjyko4qTLnsiVSgGM4AOwDOwKEzgBXfQBNR+6LgAUAShxYA3pShQ9RkwCNmAC56Zn5UfXMAWz8IJg4oLU9vA2MoADMEYL4eCOjY+PwAZkIqLwCmADowc0MACwcMuCdS5KM4ABsICva4AHMHN3KAX2bKIe0fVLNLK0QAdzhFZ1coDy9J-yCVCWlZeVyYuMVE9ZSTRuPilvKqmvrG0dO2zu6+geHR8cpKaetbCGcVF+swWgKAA)

### 💻 Code

```ts
type FooType<T> = T[] | T;
type BarType<T> = FooType<FooType<T>>;
const bar: BarType<number> = [];
const foo: FooType<number> = [3];
bar.push(foo);
```

### 🙁 Actual behavior

When making use of an indirect self-referential union generic such as:
```ts
type FooType<T> = T[] | T;
type BarType<T> = FooType<FooType<T>>;
```
I'm unable to assign what I believe to be a reasonable pathway of the expansion

```ts
const bar: BarType<number> = [];
const foo: FooType<number> = [3];
bar.push(foo);
```
this should be the equivalent of `FooType<number>[]`, however typescript disagrees that this assignment is valid
and only allows type `number`

`Argument of type 'number[]' is not assignable to parameter of type 'number'.`

I understand that the message is due to the number literal, but the typing is equivalent, as expressed
by the annotations.

Interestingly the single type version of this works, as demonstrated in (#33050)
```ts
type FooType<T> = T | FooType<T>[];
```
So it appears that the indirection is what's breaking this.

### 🙂 Expected behavior

I'm able to compile the above without error

**Comment by whzx5byb** [comment]
I don't see any unexpected behavior. 

`FooType<number>` fully resolves to `number[] | number`, and `BarType<number>` fully resolves to `number | number[] | (number[] | number)[]`. There is no self reference or circular reference here.

Because of CFA, when you assign `const bar: BarType<number> = []`, the actual type of `bar` is narrowed to `number[] | (number[] | number)[]`, so that you can call `.push` on it. Also note that function parameter type is contravariance, that means `(M[] | N[]).push` will only accept `M & N`. In your case it is `number & (number[] | number)`, which resolves to `number`.

**Comment by Seamooo** [comment]
My mistake, closing
