### ISSUE TITLE
JSDoc {Object} and {object} shown as any

### ISSUE THREAD

**Issue by zamicol** [microsoft/TypeScript#50321]
I understand that {Object} [showing as `any` is the expected behavior](https://github.com/microsoft/TypeScript/issues/18396), but is there a recommended way of constricting the doc type to something more useful?  

Having the jsdoc type of `any` on objects makes jsdoc's typing much less useful.

**Comment by DanielRosenwasser** [comment]
The problem with `Object` and `object` is that JSDoc community conventions have diluted the meaning. You can instead use `{}`.

[Playground Link](https://www.typescriptlang.org/play?filetype=js#code/PQKhFgCgAIWgBADgQwE7ILbQPYCMBW0A3kQL6lSzBQBmArgHYDGALgJbYPQ3bYAUefAEpiUUkA)

```js
/**
 * @param obj {{}}
 */
function foo(obj) {
}
```

**Comment by horvski** [comment]
It appears naming variables the same as typedefs results in an alias, and exporting these variables does not properly show the type on typedefs.

**Comment by horvski** [comment]
It appears naming variables the same as typedefs results in an alias, and exporting these variables does not properly show the type on typedefs.

**Comment by horvski** [comment]
@DanielRosenwasser  Thanks for the response, that was very helpful.

It appears naming variables the same as typedefs results in an alias, and exporting these variables does not properly show the type on typedefs.

In the following example: https://playcode.io/943389/
only 'c' carries the type information, but still shows 'any' for the typedef. 

It is unclear to me why this is the case. Can you clarify this behavior?

**Comment by DanielRosenwasser** [comment]
So in your example, there's some weird interference with the `@typedef`s and the values, all identically named `a`, `b`, and `c`. I've never seen this behavior, but here's my guess.

I think this is also caused by our heuristics, again thanks to the diluted intentions of existing JSDoc. TypeScript probably tries to resolve all meanings of a name in type position.

It finds

* a `@typedef` which is treated as a type alias
* a variable, and the type system *probably* assumes a user meant the type constructed by that variable

You can loosely validate that last behavior with this example

```js
// @ts-check
var C = class { hello = 42 };

/** @type {C} */
var d;
d.hello++ // works
```

So that's why your quick info is showing up with two aliases:

```
type c = {}
(alias) type c = any
export c
```

It looks like despite the quick info, the actual type always wins though.

```ts
// @ts-check

/** @typedef {{ world: string }} C */

var C = class { hello = 42 };

/** @type {C} */
var d;
d.hello++ // errors
```

**Comment by kungfooman** [comment]
It starts to work as expected via:

```js
{
    "compilerOptions": {
        ...
        "allowJs": true,
        "checkJs": true,
        "noImplicitAny": true, // critical for proper types
        ...
```

It's strange notetheless, why would an `object` type cause an `any` type in the first place? I guess everyone is on the same page about that `noImplicitAny` is only for erroring about a type not given. But the object type *is* given, right?

This is causing serious type issues, every `object` type can be anything without error detection:

https://www.typescriptlang.org/play/?noImplicitAny=false&ts=5.5.0-beta&filetype=js#code/MYGwhgzhAEDiBOYAOALAcgewCYFNoG8AoaE6AegCoLjToLoABJMRAWwIgBd4BLAOwDmAX2hhO3aAFpoAFRQ8YwMH2g4enFDnjQARjgB0hmqXpMWYdvgw6AVjmCcRANzAgArnmkBJAGbQNeD488Fyi8AJurDh8nIb6xiQUZAlBfFgA8nw4ABRi3AA00C7uOACUBAm0ZGTQcQlChA3AGHyhAoiomLjQALzQWQDucB3o2DmlANyE7cijuPqpGVnZAER8FjgrhSucOFwrk9MjXQaLmTlrG1vQAIwATADMhzOdYwv8SxfrUQdTQA

Can this please be reopened and fixed? @sandersn is the expert on JSDoc, would you happen to know what's going on here?

**Comment by sandersn** [comment]
Without `noImplicitAny`, `object` and `Object` are treated as `any` in JSDoc because of the years and years of usage in JS files where it means pretty much anything. We don't want to give overly restrictive results in legacy JS files.

We've added a number of `any`-related toggles to `noImplicitAny` over the years, simply because it's a pain to add and teach people about new flags -- specifically, people who care about strictness usually already have it turned on and don't have to learn about any other flags.

**Comment by kungfooman** [comment]
> We don't want to give overly restrictive results in legacy JS files.

That's funny, if you check the settings in my shared TypeScript Playground example you see that `strict` is `true` and then it shall not be strict anyway, so basically `strict` means something like `slightly-strict` now?

I just fail to see how `noImplicitAny` should have anything to do with making a strict-enabled project water-down `object` types into `any`. I see your point about legacy projects, would they enable `strict` in the first place if they don't want type error spam?

**Comment by MartinJohns** [comment]
> That's funny, if you check the settings in my shared TypeScript Playground example you see that `strict` is `true` and then it shall not be strict anyway, so basically `strict` means something like `slightly-strict` now?

`strict` means the same as it always did: a collection of default settings. You can still overwrite individual settings explicitly. The playground does not support "missing" settings, so `strict` in the playground is essentially pointless.

> I just fail to see how `noImplicitAny` should have anything to do with making a strict-enabled project water-down `object` types into `any`.

`strict` makes `noImplicitAny` `true`, but it can still be explicitly set to `false`. The behaviour for disabled `noImplicitAny` is for legacy / compatibility reasons.

**Comment by kungfooman** [comment]
> You can still overwrite individual settings explicitly.

There is no setting for `noObjectToAny`, `noImplicitAny` was misused for that and I can't enable `noImplicitAny` until the project I'm working with is fully typed, otherwise it's raining type errors.

**Comment by mackuba** [comment]
I've just come across this, I accidentally discovered that a function where I declared a param as `{object}` wasn't showing an error if I called it with `undefined`, and it slowly dawned on me that this just doesn't work anywhere I declared it like that… I was looking at this here: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-2.html#object-type and I was expecting the JSDoc version to work the same way.

I think it would be nice to at least add a mention of this somewhere here https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html (there is basically nothing about the `object` or `Object` type mentioned there, apart from where it's used as a base for custom types).

**Comment by mackuba** [comment]
@DanielRosenwasser also, following the TypeScript example from here:

```ts
declare function create(o: object | null): void;
create({ prop: 0 }); // OK
create(null); // OK
create(42); // Error
create("string"); // Error
create(false); // Error
create(undefined); // Error
```

It looks like a function declared in JSDoc as `@param {{}} obj` also accepts a number, plain string or a boolean, I only get an error for `undefined`...

**Comment by sandersn** [comment]
@mackuba Adding an explanation of built-in aliases is a good idea. I'll see what I can do.

A few comments about your most recent example:

- What version of Typescript are you using? `object` hasn't been a synonym for `any` since 3.8, even with `noImplicitAny: false`.
- `{}` is a supertype of `object`. It contains all values except `null` and `undefined`, so allows numbers, strings and booleans.
- When you pass `undefined` to `object` and there's no error, do you have both `checkJs: true` and `strictNullChecks: true` ?

**Comment by mackuba** [comment]
Version 5.4.5 - testing on such file:

```js
/**
 * @param {object | null} o
 */

function create(o) {}

create({ prop: 0 }); // OK
create(null); // OK
create(42); // Error
create("string"); // Error
create(false); // Error
create(undefined); // Error
```

When called like this, I get 4 errors:

```
npx tsc --noEmit --allowJs --checkJs --strict test.js
```

But with noImplicitAny, even with strictNullChecks, I get 0 errors:

```
npx tsc --noEmit --allowJs --checkJs --strict --noImplicitAny false --strictNullChecks test.js
```

**Comment by sandersn** [comment]
I documented the intended behaviour at https://github.com/microsoft/typescript-website/pull/3107. Turns out I was wrong: `object` *is* still a synonym for `any` with `noImplicitAny: false`.

I got confused by the fact that quick info displays `(o: object | null) => void` for `create` but `o: any` for `o` itself. That actually is a bug.

I opened a new bug #58606 though -- the title of this one applies, but the actual request is different. Plus you actually have a repro, so I used that.

**Comment by zamicol** [comment]
>What version of Typescript are you using? object hasn't been a synonym for any since 3.8, even with `noImplicitAny: false`. #https://github.com/microsoft/TypeScript/issues/50321#issuecomment-2121118477

So the [example](https://playcode.io/943389) should have different behavior?  I'm assuming that tool is JSDoc out of date. 

@sandersn, what's idiomatic if I want `@typedef {Object} b` and explicitly `any` not to be valid?

**Comment by sandersn** [comment]
> What version of Typescript are you using? object hasn't been a synonym for any since 3.8, even with noImplicitAny: false.

I was wrong when I said this because of #58606. Quick info has shown the type as written instead of the calculated type since 3.8, which confused me.

The example has the intended behaviour, at least with noImplicitAny: false.
I guess the closest thing to idiomatic would be to have a global types.d.ts file with `type b = Object` in it. However, `Object` isn't idiomatic in Typescript. `object` is idiomatic -- but `Object` is just the type for the methods on all object (toString, hasOwnProperty, etc), which are available on all objects already. So `type b = object` is likely even better.
