### ISSUE TITLE
Inconsistent incompatible types error for a sparse array type declaration

### ISSUE THREAD

**Issue by upsuper** [microsoft/TypeScript#50351]
# Bug Report

### 🔎 Search Terms

incompatible types inconsistent 

### 🕗 Version & Regression Information

The behavior changes between 4.4.4 and 4.5.5, but the previous state wasn't the expected result either.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=6&ts=4.9.0-dev.20220817#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgJWEwBMIkAbATwGUxMoBnYAQSik0oB4AVAPjgDeAKDhwoRUhUpxywJAHMYACwBccJAFcAtgCM0AbhFwG5BLgAUDGPRgB+NZt1oANHDnF767XqgBKNbT0TKzsXHyGosAAbmhc1G4gqEjEDHB85kaiomDixGaYqGrmUZjkGsBq3K7IxKAO3mi+cAC8-CVleAip1M5G-nDKXYiphCRkVIGMLGwcnNS8hkbiY1JwANpI9U5QALqVcAA+cBrJwOjIwMQRcOjkBQCymGCcAKq85til5Do4ANZF7XKlWqpxAWx8TVacBehzEEnG0heax2sNGkgmdCmIVmb36SJ2hgAvkIhKBILBECg0FhcHBJsEZmF+KAkikCPCpPTpqEePxhKINuC0Hs0rCTrVzkhLkSSQB6WVwbBkKxwAD6mACmIZPKsUGQ8n4zXWAHJMMaCSSydB4OgTtgYAgyDcIBBeeZ+miEVzsUzBJkZMB4Bq0siWusLVk4TANFAkHBMDKhPLFcr4KqdJqgtzZrr9YaTWaLUA)

### 💻 Code

```ts
export interface ReadonlySparseArray<T> {
  readonly length: number;
  slice(start?: number, end?: number): SparseArray<T>;
  every<S extends T>(
      predicate: (value: T, index: number) => value is S,
  ): this is ReadonlySparseArray<S>;

  readonly [n: number]: T | undefined;
  flatMap<U>(callback: (value: T, index: number) => U | readonly U[] | ReadonlySparseArray<U>): U[];
}

export interface SparseArray<T> extends ReadonlySparseArray<T> {
  [n: number]: T | undefined;
}

// const _a: SparseArray<string> = ['a'];

export function foo<T>(): ReadonlySparseArray<T> {
    let a: T[] = [];
    return a;
}
```

### 🙁 Actual behavior

The code above reports:
```
    Type 'T[]' is not assignable to type 'ReadonlySparseArray<T>'.
      The types returned by 'slice(...).flatMap(...)' are incompatible between these types.
        Type '(U | ReadonlySparseArray<U>)[]' is not assignable to type 'U[]'.
          Type 'U | ReadonlySparseArray<U>' is not assignable to type 'U'.
            'U' could be instantiated with an arbitrary type which could be unrelated to 'U | ReadonlySparseArray<U>'.
```
on `return a;`.

However, if the `const _a` line is uncommented, the error goes away. If you move that line to after the generic function, both places report this error.

(Weirdly, if you remove the `every` method from the `ReadonlySparseArray`, both places would be reporting the error regardless of the place of the `const _a` line.)

### 🙂 Expected behavior

It should not report error, since `SparseArray` and `ReadonlySparseArray` here should be compatible with array type. It's just a declaration of some of its methods.

**Comment by upsuper** [comment]
Rethought about it, I now believe that the correct behavior is that TypeScript should consistently reject it. Because for `flatMap`,
* `U | readonly U[]` is a subtype of `U | readonly U[] | ReadonlySparseArray<T>` (and not the reverse, since sparse array is not supposed to be assignable to dense array), so
* `(...) => U | readonly U[]` is a subtype of `(...) => U | readonly U[] | ReadonlySparseArray<T>`, thus
* `(callback: (...) => U | readonly U[] | ReadonlySparseArray<T>) => U[]` is a subtype of `(callback: (...) => U | readonly U[]) => U[]`, which means
* `ReadonlyArray.flatMap` should not be assignable to `ReadonlySparseArray.flatMap` here.

**Comment by andrewbranch** [comment]
This is caused by a false positive of `isDeeplyNestedType`. @upsuper is correct that `flatMap` should consistently cause an assignability error. However, because of the interconnected return types in the methods of `ReadonlySparseArray` and `SparseArray` and the order they’re written, we end up bailing out of comparing `flatMap` just barely too early. The comparison stack at the point of bailing looks like:

|  | Source | Target |
|--| --- | --- |
| 0 | `(literal) Array<string>` | `SparseArray<string>` |
| 1 | `(literal) Array<string>["slice"]` | `SparseArray<string>["slice"]` |
| 2 | `Array<string>` | `SparseArray<string>` |
| 3 | `Array<string>["every"]` | `SparseArray<string>["every"]` |
| 4 | `Array<any>` | `ReadonlySparseArray<any>` |
| 5 | `Array<any>["slice"]` | `ReadonlySparseArray<any>["slice"]` |
| 6 | `Array<any>` | `SparseArray["any"]` |
| 7 | `Array<any>["flatMap"]` | `SparseArray<any>["flatMap"]` |
| 8 | `U \| ReadonlyArray<U \| ReadonlySparseArray<U>> \| ReadonlySparseArray<U>` | `U \| ReadonlyArray<U> \| ReadonlySparseArray<U>` |
| 9 | `ReadonlyArray<U \| ReadonlySparseArray<U>>` | `ReadonlySparseArray<U>` |
| 10 | `ReadonlyArray<U \| ReadonlySparseArray<U>>["slice"]` | `ReadonlySparseArray<U>["slice"]` |
| 11 | `Array<U \| ReadonlySparseArray<U>>` | `SparseArray<U>` |

While this looks pretty chaotic, it does finish with the correct results if you bump the `maxDepth` parameter of `isDeeplyNestedType` from `3` to `4`.

Note that the comparison at index 8 is the result of contextual signature instantiation after a potentially questionable inference explained [here](https://www.typescriptlang.org/play/?target=6&ts=5.5.0-dev.20240424#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgZQgFcpcBGOAbwCg44BbTMALjgB58A+ACm0wBt+AIxwBrdElbcAbgKLBWAZxhRkAcwCUcALycCW3QQDaAXQDc1AL7VqoSLEQo0WXHAAqmKGuDwadRizsbjx8giLY4pJwMnIKcMqqSJo6em5wAD5wREgAJsDoyMA5BqmmFtbUedj8nnj8PvFkrIQk5BZVNVB1DTCsHl4+FtQA9MNwACIk6nAwABZ46BCCEADu05iKighqSPTAKAA0cAAGLaTAZEYARAFXJsdw3jCKI2PIypgoCJioOXBrcxm8zg2AgThAMCIAhmAE8wHhjv0ntdbvc4EJ8tA8Nh5hF1K84BstjtMEIEPwEDAYQA6dwQOA5elzH5HT6OdBofauBCKBiYPIzemnY60gBi0BOZ3IxwOBLmeDB-BhIM+OQQOR+eB5JzSmWyeQKSCKD3QUAg9CBeC6kKgSFh8LgEHQJ1CwjEEhFBIAkkgOV0kK4BIp6VBsrywScAg9rSQ7VT4bzTqYHqqdcmjkIiPB5XAuooiPwYATtWrFHwoHk-hi+ERFFqYIBMAl5obtANmhLg-FWaHZnIDeDAqmglJpcAAgrzMLngPnC7LRv88Ps-kQwPFgMBpghnTnQeDIQIlY4Pl9NX9g608MSkD8SApXgS6LxD+FIlJZPx5EoVOoSu4MlkuT5IUxQpNEuqAQaIEaKYD4LtqRLbDeQj1IKlozJ4TzxEht5dMwcFjE+rqvhI76xN+iTJIYEH6sBRqgdRsGjASqY5jGtr2jOKq1ngOZYOSRSEpsOFkhSVK0gAQlmQkdrMRCMHaXT8mgxZOFAg4+NMKyzMqxyKGQDzakgEDwIhJIobxQowDKcBeseqD8nAwAAI5QqgkoprkOrHCxXnqvsMDbsqOaADgESn8IAuARwIOEAWRaGzoexcZwgqzrHMR7pIIZdqIphPg+Qu3CIgBtGGsaWgYus8Srmg8apehYJajlUoXA8RX4A8gBJhN5GjUjY8DaI0ZhwAuEn8qw9mfIFmqJh1-yUu2xV6kBZU5DZ-H8ImUbTjayUOmZyHkiONgLl6DYWsZ8D5l0-yzD8uYFleszEPwfxMGAR7zF0GbSZS67APQvIUqIvHAqCUBdNg8DIH6XLAASixQB5jhAtqe6oBCUL8JNp6BRG2qIjZl06iVK0gSKcDikjoL0GAng8mC85jF9wBNh20hoFsEbMvAiO4LyPM49NeOtgtJwAHIQD6fo2axwJoGaSN7JsmDeASXYQKIvIYjAqBQPhtjgNA0NqS4eAtQATFQtB8oEHAhC+mVkZ+cQJL+YGS9LaD23++BlFYNgdLUnYNIoFvNMQ5wWxYA3xNHI1jAA4hAEA5Kw7wwFN3yoLNDxtt5RwbYmGURB6O2xpxQnXqSR1UtQQA). That’s a separate bug, but fixing it would probably prevent this particular example from triggering the depth limiter.

**Comment by andrewbranch** [comment]
#58321 fixes this by changing the weird inference mentioned above, but I feel like it’s probably wrong

**Comment by andrewbranch** [comment]
@ahejlsberg says possibly related to https://github.com/microsoft/TypeScript/issues/56099
