### ISSUE TITLE
Investigate Regression in Compilers-Unions

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#50360]
Our perf dashboard has a \~230ms regression on the compilers-unions benchmark starting at 4e33e0eb6c0e3173dbed1d4a825965f44b2b9e09 introduced in #49865.

![image](https://user-images.githubusercontent.com/972891/185459792-a226325a-82d2-45fe-9d7b-b122f02c74ca.png)

**Comment by DanielRosenwasser** [comment]
I think you can just fix this if you check whether the target has the appropriate primitive-like flag for the literals you're checking.

**Comment by andrewbranch** [comment]
I don’t quite understand—the target is always a weak object type here, never a primitive.

**Comment by DanielRosenwasser** [comment]
Hm - is it possible that it has to do with the use of `isLiteralType` which returns true if any given type in a union is a literal? So you may be doing the work of getting the apparent type of fairly large union types?

**Comment by andrewbranch** [comment]
So, my assumption was that the perf impact was more likely to be due to actually performing more common-property checks, but the condition `relation === comparableRelation && isLiteralType(source)` is never actually true in Compiler-Unions, so if the benchmark is to be believed, the cost is _solely_ due to calling `isLiteralType(source)` itself, which does _not_ get the apparent type or anything expensive; it just does `every((type as UnionType).types, isUnitType)` over unions. We could try caching that bit on `UnionType`, but it seems odd that it’s really making that big of a difference here.

**Comment by DanielRosenwasser** [comment]
That's surprising. You don't really need to cache though because you'll re-enter the same branch where `isRelatedTo` will distribute across union types, right?

**Comment by DanielRosenwasser** [comment]
Let's see if #50423 fixes this.
