### ISSUE TITLE
yield* and string literal types

### ISSUE THREAD

**Issue by decodejacques** [microsoft/TypeScript#50400]
The following code throws a type error

```
function* foo() : Generator<"bar", number, undefined> {
  yield* "bar" // Error: Type 'string' is not assignable to type '"bar"
  return 10
}
```

And trying to add a type annotation doesn't help

```
function* foo() : Generator<"bar", number, undefined> {
  yield* "bar" as "bar" // Error: Type 'string' is not assignable to type '"bar"
  return 10
}
```

But the type error goes away if you give the function a more generic type signature

```
function* foo() : Generator<string, number, undefined> {
  yield* "bar" // no error
  return 10
}
```

Or if you write yield instead of yield*

```
function* foo() : Generator<"bar", number, undefined> {
  yield "bar" // no error
  return 10
}
```

**Comment by MartinJohns** [comment]
You forgot to fill out the issue template for bug reports / feature requests.

I don't see a bug here. `yield` yields a single element, `yield*` yields a sequence. When `yield`ing `"bar"` you yield the single string `"bar"`. When you're `yield*`ing `"bar"` you yield each individual character: `"b"`, `"a"`, `"r"`. That's why you get an error when use the type `"bar"` in your return type annotation, but don't get an error with `string`. `"b"`, `"a"` and `"r"` are not compatible with the type `"bar"`, but are compatible with the type `string`.

**Comment by decodejacques** [comment]
> You forgot to fill out the issue template for bug reports / feature requests.

For some reason when I clicked on the "new issue" button it didn't present me with the template options and instead presented me with a textarea.

> I don't see a bug here.

Yes, you're right. The bug was with my understanding of yield*
