### ISSUE TITLE
Possible bug with generic constraints

### ISSUE THREAD

**Issue by NickHeiner** [microsoft/TypeScript#50552]
# Bug Report

### 🔎 Search Terms

generic constraints

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (back to 4.4), and I reviewed the FAQ for entries about generic constraints

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.0-beta#code/KYDwDg9gTgLgBDAnmYcAixhgAoENYCWuANgDxoB8cAvOnKDMAHYAmAznBAEYBWwAxjABQcUXAD8cAN4ixc0QG1scAkzgBrYIggAzdAF1xALnSYc+GETJol+igG5ZcgL5O4JtI6GhIsFU0YoHVx+VABBaTcdKAgAWxMmAFdYrmAoR1dvcGh4VUDg0LgAIVIAFXoQRlYOCNowqhk5EGM4UoyhIR1EpkECCDUdUgAxCqr2OHqACjAYsDYTEqGKAEpIuSQUOCGAJhpi4Yc3AHojuABJeDZMWI5iAk0EAAsCDjZHiETiFjhUznUAOjgAHVHrh4Nw+II4PxcEwAOTwX6xXAsVC4OBgCxWcRufj9NjwFgeMx4QgkYbbKi0GYQObtIQnc56ADuqAA5sB4FACN9dE92cw0gR+AAaFTwZnQdRsf6dbq9fpwHTbaazeb7eqrRpiDaoUq7WgleqOOR4pgEuBE0xYUmWcn6qkYtXtIA)

### 💻 Code

```ts
export type DeepPartial<D> = D extends object
    ? {
          [P in keyof D]?: DeepPartial<D[P]>;
      }
    : D;

export interface A {
    from: number;
}

export interface B<T extends A = A> {
    x?: T;
}

function f<F extends A>(props: B<F>) {
    type F2 = B<F>;
    // It seems like this should be ok. What object can't be made a partial?
    const d: DeepPartial<F2> = props;
}

// If we get rid of the generic, it works.
function f2(props: B<A>) {
    type T2 = B<A>;
    const d: DeepPartial<T2> = props;
}

```

### 🙁 Actual behavior

I get this error:

```
Type 'B<F>' is not assignable to type '{ x?: DeepPartial<F> | undefined; }'.
  Types of property 'x' are incompatible.
    Type 'F | undefined' is not assignable to type 'DeepPartial<F> | undefined'.
      Type 'F' is not assignable to type 'DeepPartial<F> | undefined'.
        Type 'A' is not assignable to type 'DeepPartial<F>'.(2322)
```

### 🙂 Expected behavior

No error

### Notes
There's a good chance this "bug" is just my lack of understanding, so I apologize if this is a waste of your time. :smile: But I asked around locally and thought about it myself and couldn't figure out why this was happening.

It surprises me that 1) there's any object that can't be passed to `DeepPartial` and 2) that it seems to matter if the function declares a new generic.

**Comment by RyanCavanaugh** [comment]
> What object can't be made a partial?

What you're saying by this is that you have a proof that for any `T`, `DeepPartial<T>` is assignable from `T`. How did you make that proof? By looking at each possible code path through `DeepPartial` and reasoning that:
 * Any type `T` that's an `object `must be assignable from a `DeepPartial<T>`
 * Any other type `T` must be assignable from `T`
That first line there is an inductive argument that presupposes the thing being proved. In this case that happens to be valid because we can't imagine a type that doesn't terminate somewhere or safely recurse forever, but TS doesn't have any mechanics in place to make those kinds of reasoning.

So anyway TL;DR TypeScript is not a theorem-prover and can't make determinations like that.

**Comment by NickHeiner** [comment]
Ok, that makes sense! Sounds good. I mostly just wanted to make sure that I wasn't misunderstanding and actually writing unsafe code.
