### ISSUE TITLE
ts-server gets high latency (about 5 seconds per action) for ts/js language feature

### ISSUE THREAD

**Issue by Arichy** [microsoft/TypeScript#50598]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.2
- OS Version: macos 12.5.1

I made a simple demo to reproduce this problem: https://github.com/Arichy/minitest
Steps to Reproduce:

1. git clone https://github.com/Arichy/minitest.git
2. open the repo in vscode
3. yarn install
4. goto `src/index.tsx` and type whatever ts/js code as you're really coding

It seems ts throw an error: Expression produces a union type that is too complex to represent.
But I don't know why ts throws the error. I only know the `memo` without generic in `Comp.ts` and the collection of custom elements declaration in `react-app-env.d.ts` cause the error together after trying many times.
 
The problem acts like this:

![Kapture 2022-08-27 at 00 56 58](https://user-images.githubusercontent.com/29599723/186955143-7dd14e3f-d9d9-4b4b-ab19-36050fbd29b0.gif)

As you see, ts language features such as autocompletion, goto definition, method hint are all having very high latency. It will be more serious in my practical business project.

**Comment by andrewbranch** [comment]
I’m not familiar enough with React types off the top of my head to tell you exactly why this is causing an exploding union, but I am familiar enough to tell you how/why the augmentation you’ve added is wrong. The types of the keys of `IntrinsicElements` is supposed to be the _props_ that an element of that kind accepts, whereas `ReactNode` is anything that can be rendered by React. Instead of `ReactNode`, you want to put a type that specifies what props these custom elements can take. For example, if they take standard HTML attributes that all native HTML elements take, and if a `ref` on that element gets you an `HTMLElement`, it would look something like this:

```ts
declare namespace JSX {
  interface IntrinsicElements {
    'my-web-icon-add-small': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement>;
    // ...
  }
}
```

You can adjust that accordingly; maybe `HTMLElement` isn’t quite right for custom elements; it’s been too long since I’ve done frontend work. If these things don’t need to take _any_ props, you can just do

```ts
declare namespace JSX {
  interface IntrinsicElements {
    'my-web-icon-add-small': {}
    // ...
  }
}
```

**Comment by Arichy** [comment]
> I’m not familiar enough with React types off the top of my head to tell you exactly why this is causing an exploding union, but I am familiar enough to tell you how/why the augmentation you’ve added is wrong. The types of the keys of `IntrinsicElements` is supposed to be the _props_ that an element of that kind accepts, whereas `ReactNode` is anything that can be rendered by React. Instead of `ReactNode`, you want to put a type that specifies what props these custom elements can take. For example, if they take standard HTML attributes that all native HTML elements take, and if a `ref` on that element gets you an `HTMLElement`, it would look something like this:
> 
> ```ts
> declare namespace JSX {
>   interface IntrinsicElements {
>     'my-web-icon-add-small': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement>;
>     // ...
>   }
> }
> ```
> 
> You can adjust that accordingly; maybe `HTMLElement` isn’t quite right for custom elements; it’s been too long since I’ve done frontend work. If these things don’t need to take _any_ props, you can just do
> 
> ```ts
> declare namespace JSX {
>   interface IntrinsicElements {
>     'my-web-icon-add-small': {}
>     // ...
>   }
> }
> ```

Got it, thanks!😊
