### ISSUE TITLE
Please add a helpful message to when the dist/ folder has been deleted but tsconfig.tsbuildinfo has not been updated

### ISSUE THREAD

**Issue by psygo** [microsoft/TypeScript#50646]
As [this answer on SO](https://stackoverflow.com/a/72250405/4756173) states:

> Every single time I've ended up here after Googling "typescript tsc no output" it's for the same reason.  Since this has definitely happened more than once I'll throw my answer into the ring too.
> 
> Every time this has happened to me it's because TypeScript is configured with `composite: true` and I deleted the output directory (the one set as `outDir` in `tsconfig`), but didn't delete the `tsconfig.tsbuildinfo` file.
> 
> This leads TypeScript to assume that the output doesn't need updating, because the timestamp on the `tsbuildinfo` file says that the last build was after all the files were modified.

This behavior is so weird and difficult to guess. It feels so unnatural and unnecessarily brittle. Could there at least be a helful message in the terminal like:

```error
there is no `dist/` folder anywhere,
but the `tsconfig.tsbuildinfo` file says everything is ok,
so Typescript will do a total of jack shit
```

**Comment by jakebailey** [comment]
@sheetalkamat Is there something we could change in the tsbuildinfo such that we could detect that the output folder (or output file) is missing and therefore must be output again?

**Comment by FabianFrank** [comment]
This is a significant foot gun when setting up project references (and npm workspaces), especially when doing it for the first time and not knowing about this behavior. In regular projects the tsbuildinfo file ends up in your output (`dist/` or whatever) folder so when you `rm -rf dist/` its' gone with it, you can use TypeScript for years without ever running into this. Until the day you use project references, because with composite set to true you tend to also set a root dir and then the tsbuildinfo ends up outside your output folder, at the root of the package. I'll admit, I wasted a good amount of time trying to figure out why my module can't be found, thinking I got some project reference path or npm workspace paths wrong or whatever until realizing that tsc isn't generating output in one of my packages and then ending up here.

**Comment by sheetalkamat** [comment]
We do provide the `tsc -b --clean` to safely remove all output artifacts. We also provide `tsc -b -f` to force compilation irrespective of all outputs.
So there are workarounds for this.

Checking output timestamps has cost involved and it shouldnt be incurred for every project and hence this is currently working as designed.
