### ISSUE TITLE
TypeScript codes copied from Visual Studio 2015 do not contain syntax highlight

### ISSUE THREAD

**Issue by engineforce** [Microsoft/TypeScript#5064]
Codes copied from Visual Studio always contain syntax information (including spacing, syntax highlight, etc.), this allow me to copy codes to Word for documentation purpose.

However, I just found that this feature is broken for TypeScript 1.6.3.0 in Visual Studio 2015, when I copy TypeScript codes to Word, they don't contain Syntax Highlight, which is very annoying. Note that this feature for all other languages still works fine including JavaScript, but broken for TypeScript.

In Visual Studio:
![invisualstudio](https://cloud.githubusercontent.com/assets/3614365/10236647/9606b838-68eb-11e5-875b-8ecba0681344.png)

In Word:
![inword](https://cloud.githubusercontent.com/assets/3614365/10236663/decb955c-68eb-11e5-9b2b-faef0b813c57.png)

Please fix this issue, as it is a great feature of Visual Studio, it is very useful for documentation purpose. Thanks!

**Comment by mhegazy** [comment]
this is managed by Roslyn. @CyrusNajmabadi any ideas?

**Comment by CyrusNajmabadi** [comment]
This is likely due to us using View taggers, whereas the editor is probably only getting classification for Copy/Paste from buffer taggers.

**Comment by CyrusNajmabadi** [comment]
To solve this, we'll need to export a buffer tagger provider for this purpose.  *However* (and this is critical) the buffer tagger provider needs to return a tagger that does *nothing* inside it's ```GetTags``` method.  That's because we definitely do *not* want to be doing full classification in this buffer tagger through the normal ```GetTags``` call.  This would defeat the purpose of us having view taggers to only classify what's in view.

So what do we need to do instead?  Well, instead we return an implementation of an ```IAccurateTagger```.  Our implementation will do nothing in ```GetTags```, but will block and return all the right tags inside ```GetAllTags```.  

THen when the editor wants to copy/paste, it will call through this codepath and get the right tags (in a blocking fashion).

**Comment by engineforce** [comment]
Thanks for the quick response, could you please give me a rough estimate on when will you release a patch/fix for this issue?

**Comment by mhegazy** [comment]
No ETA at the time being. we will try to get this in the next release. but no promises.

**Comment by mhegazy** [comment]
this should be fixed now.
