### ISSUE TITLE
optional argument that don't need to be specified

### ISSUE THREAD

**Issue by jimmywarting** [microsoft/TypeScript#50657]
# Suggestion

Some stuff have become to strict... that it's becoming too annoying!

```js
await new Promise(rs => {
  setTimeout(() => rs(), 1000)
})
```
```
Expected 1 argument, but got 0. 'new Promise()' needs a JSDoc hint to produce
a 'resolve' that can be called without arguments
```

it's not only that. `new ArrayBuffer()` and `new Uint8Array()` is also something that requires an argument but it's perfectly fine to omit it to represent a 0 length buffer in the cases where you need a empty placeholder

## 🔍 Search Terms

promise resolve

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by jakebailey** [comment]
`Promise` definitely requires an argument. If you do not pass it a function, it will throw.

It's true that at runtime, `ArrayBuffer` and `Uint8Array()` "work" when you don't pass an argument, but only because the parameter is then `undefined`, which is coerced to a number which is then zero. We could say the same about passing `"0"` or `false`. In general, we don't aim to make types so wide as to capture coercion behaviors; e.g., we do not `parseInt(undefined)` even though that "works" and returns NaN. The `ArrayBuffer` and `Uint8Array` constructors are all documented in the spec and MDN and such as having a required parameter, so I don't think it's a good idea to change this.

**Comment by jimmywarting** [comment]
> Promise definitely requires an argument. If you do not pass it a function, it will throw.

i wasn't talking about the promise constructor. i was talking about the resolver's argument

**Comment by jakebailey** [comment]
RE: Promise, we know that this isn't ideal; see #46570, #40505. What we'd need is some sort of concrete proposal that would help things.

RE: The constructors, we already have the overloads in place such that types like `Uint8Array` are legal without parameters. [Playground Link](https://www.typescriptlang.org/play?#code/HYUw7gBAqglsAuAOAggJ1QQwJ4AoCUA3ALABQoksCAjAGxqa6GnkT3YBCArgGbcir4CQA)

This isn't the case for ArrayBuffer, but it's really to just explicitly pass in `0` as the parameter.
