### ISSUE TITLE
Helpers should not access `this` in ESM output

### ISSUE THREAD

**Issue by devongovett** [microsoft/TypeScript#50761]
# Bug Report

### 🔎 Search Terms

helper, this, __classPrivateFieldSet

### 🕗 Version & Regression Information

- Since 3.8

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=6&isolatedModules=false&ts=4.8.2#code/MYGwhgzhAEAqCmEAu0DeAoaXoGIBmA9gdALzQBMA3OptkokgBQCUat2dAFgJYQB0+IqWgBmahwC+6CUA)

### 💻 Code

```ts
class Test {
    #foo = 2;

    test() {
        this.#foo = 3;
    }
}
```

### 🙁 Actual behavior

TypeScript outputs helpers with code like this:

```js
var __classPrivateFieldSet = (this && this.__classPrivateFieldSet) || function /* ... */
```

However, in ES modules, `this` is always `undefined` so this check is unnecessary. I assume this was meant to check a global variable, but this won't work within a module. In ESM, `this` is undefined. In CommonJS, `this` is the `exports` object. Not exactly sure what the purpose of it is.

In addition, bundlers like Parcel and webpack support "hybrid" modules, where some ESM syntax is used, as well as some CommonJS syntax. When `this` is seen in a module, bundlers must assume that it is actually CommonJS for compatibility with older code. This may cause things like tree shaking to bail out, resulting in larger bundlers for users. Since TSC is commonly used to compile libraries, removing this check may result in smaller bundles across the ecosystem.

### 🙂 Expected behavior

Depending on the output module format, TypeScript should omit this check. I think it is unnecessary for both ESM and CommonJS at least.

**Comment by rbuckton** [comment]
If you are using a bundler, I would recommend installing the `tslib` package and building with `--importHelpers` instead. That will not only avoid the `this` reference but will also ensure that such helpers are only loaded once across the compilation.

The `(this && this.__helper) || ...` prefix TypeScript uses for its helpers has existed since we shipped 1.0, and changing it has the likelihood of breaking some users who may have a mixed codebase consisting of both modules and scripts. In addition, the `this` reference in the expression does not fail at runtime when not using a bundler, so this seems more like an issue with Parcel's detection logic. TypeScript's helper emit has remained consistent for years, so it's conceivable that bundlers like Parcel could potentially use a heuristic to detect them and ignore them for the purpose of detecting CommonJS compatibility.

At this time, we're unlikely to change our helper emit without a stronger motivation, though we're more than happy to discuss this further with the Parcel maintainers.
