### ISSUE TITLE
server doesn't watch for file add/remove

### ISSUE THREAD

**Issue by jrieken** [Microsoft/TypeScript#5076]
* run tsserver
* run a command that removes/add TS files, like _tsd install foo, git pull, etc_
> the tsserver doesn't notice that change, https://github.com/Microsoft/TypeScript/blob/master/src/server/editorServices.ts#L881

**Comment by dbaeumer** [comment]
The interesting case here is the tsconfig.json which defines the project scope. Reloading the project in this case is an 'overkill' since all that needs to be done is to add/remove files to/from the project. IMO the tsserver should either handle that case correctly or should give up on file watching and rely on the editor to provide the file events.

**Comment by mhegazy** [comment]
@zhengbli is working on a fix for this as part of #4553 and #4643

**Comment by mhegazy** [comment]
@jrieken can you give this a try..
