### ISSUE TITLE
Using a union type for a rest parameter type annotation

### ISSUE THREAD

**Issue by myitcv** [Microsoft/TypeScript#5077]
According to the spec (see later in this note), the following should be valid:

```typescript
function DoIt(...v: number[] | string[]): void {
}
```

but this gives an error:

```
A rest parameter must be of an array type
```

I'm guessing this is therefore an error in the spec?

```
RestParameter:
   ... BindingIdentifier TypeAnnotation_opt

TypeAnnotation:
   : Type

Type:
   UnionOrIntersectionOrPrimaryType
   FunctionType
   ConstructorType

UnionOrIntersectionOrPrimaryType:
   UnionType
   IntersectionOrPrimaryType

UnionType:
   UnionOrIntersectionOrPrimaryType | IntersectionOrPrimaryType

UnionOrIntersectionOrPrimaryType:
   UnionType
   IntersectionOrPrimaryType

IntersectionOrPrimaryType:
   IntersectionType
   PrimaryType

PrimaryType:
   ParenthesizedType
   PredefinedType
   TypeReference
   ObjectType
   ArrayType
   TupleType
   TypeQuery

ArrayType:
   PrimaryType [no LineTerminator here] [ ]

PredefinedType:
   any
   number
   boolean
   string
   symbol
   void
```

**Comment by RyanCavanaugh** [comment]
It's a valid grammatical production, but not valid according to the type system. The grammar is about what's syntactically valid, not necessarily semantically valid (the same way that `var x: number = 'foo'` is allowed by the grammar, but not allowed by the type system).

We perhaps *could* change the rule from "a rest parameter must be an array type" to "a rest parameter must be an array type or a union type in which all constituents are array types" but that seems not worth adding complexity for, since it's easy enough to add overloads to clarify the intended behavior:

```ts
// Either this
function DoIt1(...v: string[]): void;
function DoIt1(...v: number[]): void;
function DoIt1(...v: any[]): void {
}

// Or maybe this is what you meant?
function DoIt2(...v: Array<number|string>): void {
}
```

**Comment by myitcv** [comment]
> It's a valid grammatical production, but not valid according to the type system

Got it, thanks.

>  but that seems not worth adding complexity for, since it's easy enough to add overloads to clarify the intended behavior

Agreed. 

> `// Or maybe this is what you meant?`

No, you understood me correctly!

**Comment by vilic** [comment]
@RyanCavanaugh Though it would still be great if we can achieve something like this:

```ts
function invoke<T, U extends any[]>(fn: (...args: U) => T, ...args: U): T { }
```

**Comment by mischkl** [comment]
You can also write this as follows:

```ts
function DoIt(...v: (number | string)[]): void {
}
```

(discovered in the Protractor type definitions)
