### ISSUE TITLE
Array.prototype.at() does not accept non number input

### ISSUE THREAD

**Issue by lukaspatschil** [microsoft/TypeScript#50770]
# Bug Report

The type definition does not behave according to the ECMA specification and only accepts type `number` but should also accept other input.

See: https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.prototype.at

### 🔎 Search Terms

- at
- .at
- array.at
- array at
- array.prototype.at

### 🕗 Version & Regression Information

This happened in version `4.8.3`.

It is not fixed in `4.9.0-dev.20220914`.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Type System Behavior and Functions.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=99&moduleResolution=99&ts=4.9.0-dev.20220914&noLib=true#code/NoRgNATAugdAhgFwBQIE4FcCmBKIA)

### 💻 Code

```ts
[1,2].at(true)
```

### 🙁 Actual behavior

The compiler emits an error that a boolean is not allowed.

### 🙂 Expected behavior

A boolean or for that matter any other primitve type should be allowed to be used in Array.prototype.at().

**Comment by jcalz** [comment]
[What does "all legal JavaScript is legal TypeScript" mean?](https://stackoverflow.com/questions/41750390/what-does-all-legal-javascript-is-legal-typescript-mean)

**Comment by fatcerberus** [comment]
Hah, I was just going to post that but @jcalz got to it before me. 😆

**Comment by fatcerberus** [comment]
As an aside, the specification is a poor basis for objections about type checking because 1) the spec is very liberal w.r.t. coercion and 2) there is no undefined behavior in JavaScript.  If TS had to allow everything the spec allowed, most of the reason to use TS in the first place would be rendered moot.  For example, `num * str` is well-defined by the spec but probably isn’t something anyone should be doing in real code.
