### ISSUE TITLE
"Property does not exist on type 'never'" error shown when using dot notation, but not for bracket notation 

### ISSUE THREAD

**Issue by tigrr** [microsoft/TypeScript#50785]
# Bug Report

When trying to access Event.target.value inside an event handler, even after checks, error appears saying `Property 'value' does not exist on type 'never'`.

### 🔎 Search Terms

Property does not exist on type 'never'
Event.target.value throws error: Property 'value' does not exist on type 'never'
Error shown when using dot notation, but not for bracket notation

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `never`, dot and bracket notations

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.2#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCoASMFmgY7p7ehCTkVOle4jUMdRLYTqCc8LEZzCZmoNJODPHFZZXVtZYYkAAeRJTInDQS8po+rf40gnjbDKv8LqD2jpbYoACqAEoAMsK7sUmxkGSCc+VVQQuaTwVb1UBrDYULY7PagbgUZLJH6QbYmJAECjuMigZEMVDsJzCFLNXxtajBFQAUTIbF+kjh3GGg2G+Io8E4igQnEENGSXFgAEZQABeUAACkg+VAVL02wAlKKAHygADeihKJUREsgAVQjmYkBoADJjRKAOQ6BjQdiQc0iLy6-VkQ2oeWK9War3onnwdwBaDwZiSvUGo0BK02yDyjWagC+igTxQAIvB9CyaD86QzPlMevEjRm2RyuRzebiBQAmUU66Wy1Fu5Vq2Na1Ih52u0Cmi2R232jIQ0Muo3u5vezXcwR+3WB4NOsOoADalutfYAujGvQmE0A)

### 💻 Code

```ts
// Errors with dot notation
const func1 = (e: Event) => {
    if (e.target && ('value' in e.target)) {
        console.log(e.target.value) // <-- Property 'value' does not exist on type 'never'
    }
}

// Does not error with bracket notation
const func2 = (e: Event) => {
    if (e.target && ('value' in e.target)) {
        console.log(e.target['value']) // <-- OK
    }
}
```

### 🙁 Actual behavior

`func1` produces an error `Property 'value' does not exist on type 'never'`, `func2` doesn't produce any errors.

### 🙂 Expected behavior

Neither dot, nor bracket notation should throw an error.

**Comment by MartinJohns** [comment]
Duplicate of #42999.

**Comment by tigrr** [comment]
@MartinJohns why should they throw an error?

**Comment by MartinJohns** [comment]
Because `never` represents an invalid state, something that should not occur. The developer should be informed about this, instead of silently letting them continue to use a value that shouldn't exist.

If you want to use it, you can use a type assertion to change the type to `any`.

But I think the actual question you want to ask is why `'value' in e.target` resolves to `never`, and what you can do about that. This is the case because `e.target` is typed `EventTarget`, which has no `value` property. So after checking a property that shouldn't exist does exist, TypeScript is left with no further type information, so it resolves to `never`. You should use a type assertion here to change the type to `HTMLInputElement` (or whatever might be right).

**Comment by tigrr** [comment]
@MartinJohns thank you for the explanation.
Closing as duplicate.
