### ISSUE TITLE
Semicolon is added when organize import in specific case

### ISSUE THREAD

**Issue by orblazer** [microsoft/TypeScript#50817]
# Bug Report

### 🔎 Search Terms

- Semicolon organize import
- Semicolon vscode 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about semicolon organize import

### 💻 Code

```ts
import { resolve } from "path"

type test = { var1: number; var2: string }

console.log(resolve(__dirname))
```

Vscode config (`settings.json`) :
```jsonc
{
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.formatOnSave": false,
  "editor.codeActionsOnSave": {
    "source.organizeImports": true
    // "source.sortImports": true // This also append when this is enabled
  },
  "typescript.tsdk": "./node_modules/typescript/lib"
}
```

Prettier config (`.prettierrc`)
```json
{
  "semi": false
}
```

### 🙁 Actual behavior

When i save file, this add semicolon on all `import`.

### 🙂 Expected behavior

No add semicolon on `import`.

### Additional information

That issue **ONLY** append when i have an type write like that `{ var1: number; var2: string }`, so i think the organize/sort (maybe from here #31801) think the semicolon is used because is present in code.

**Comment by RyanCavanaugh** [comment]
TypeScript doesn't know about prettier and uses a heuristic to figure out it if seems like you're using semicolons or not. Since you could have used a comma to separate `var1` and `var2`, this appears to be a "semicolon-friendly" codebase based on that heuristic.

Set the "Semicolons" formatter option according to your formatting style:
![image](https://user-images.githubusercontent.com/6685088/191376057-19a6ef2e-26e5-405e-a6f4-6a4e1ad54c69.png)
