### ISSUE TITLE
How do I get immutable types

### ISSUE THREAD

**Issue by lzxb** [microsoft/TypeScript#50843]
# Suggestion

```ts
const data: 'name' | 'age' = 'age';
// Output: "name" | "age"
// How to output: "age"

// Only output: "age"
// Why
switch (data) {
    case 'age':
        break;
    // Type '"name"' is not comparable to type '"age"'.ts(2678)
    case 'name':
        break;
}

```

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion
```ts
const data: 'name' | 'age' = 'age';
// Output: "age"

```

**Comment by MartinJohns** [comment]
Assignment narrows the type.

**Comment by lzxb** [comment]
```ts
interface Data1 {
    type: '1';
}
interface Data2 {
    type: '2';
}

type Data = Data1 | Data2;

function data<T>(data: Data) {
    return data;
}

const result = data({
    type: '1'
});
// (property) type: "1" | "2"
// result.type
// How to output: "1"

```

**Comment by lzxb** [comment]
> Assignment narrows the type.
> 
> This is not a bug, and especially not a feature suggestion.

I am designing a class library. After receiving the type parameter, I will return a converted object, but it should not be a joint type, but a determined type

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
