### ISSUE TITLE
Running `tsc` ignores `exclude` config in jsconfig.json 

### ISSUE THREAD

**Issue by markcellus** [microsoft/TypeScript#50862]
# Bug Report

This has been reported in https://github.com/microsoft/TypeScript/issues/43043 and https://github.com/microsoft/TypeScript/issues/42797 which have been auto-closed. Still not sure why they were closed when the issue still exists in latest version. Hope this issue isn't closed as well 🙈. Note: the user who has filed the above referenced tickets did also have both jsconfig.json and a tsconfig.json, but this issue exists even when the project has only a jsconfig.json file. 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about it
- Also checked this using `typescript@next` and still has same issue

### ⏯ Playground Link

_Cannot reproduce on TypeScript playground because I don't seem to have access to the node_modules directory and I don't know whether or not a jsconfig.json is being used._

### 💻 Code

1. Install one of the npm packages below with type errors. At the time of this writing, having all of them installed produces the following type errors: 
     ```
     2  node_modules/cookie-parser/index.js:146
     1  node_modules/cookie/index.js:236
     6  node_modules/cors/lib/index.js:166
     2  node_modules/express/lib/express.js:39
     1  node_modules/gauge/lib/index.js:286
    49  node_modules/node-fetch/lib/index.js:3
    26  node_modules/npmlog/lib/log.js:87
     1  node_modules/object-assign/index.js:31
     3  node_modules/set-blocking/index.js:3
     2  node_modules/supertest/index.js:15
     ```
1. Install typescript `npm i typescript`
2. Add a `jsconfig.json` file with the following contents:
    ```json
         {
         "compilerOptions": {
             "module": "commonjs",
             "target": "es6",
             "checkJs": true,
           },
         "exclude": ["node_modules"]
         }
    ```
4. Run `npx tsc -p jsconfig.json` to typecheck

### 🙁 Actual behavior

Outputs

```
     2  node_modules/cookie-parser/index.js:146
     1  node_modules/cookie/index.js:236
     6  node_modules/cors/lib/index.js:166
     2  node_modules/express/lib/express.js:39
     1  node_modules/gauge/lib/index.js:286
    49  node_modules/node-fetch/lib/index.js:3
    26  node_modules/npmlog/lib/log.js:87
     1  node_modules/object-assign/index.js:31
     3  node_modules/set-blocking/index.js:3
     2  node_modules/supertest/index.js:15
    14  node_modules/supertest/lib/agent.js:15
    15  node_modules/supertest/lib/test.js:28
```

### 🙂 Expected behavior

Should exclude checking in node_modules directory and should not output any errors.

**Comment by MartinJohns** [comment]
I can not reproduce the issue with your instructions. The compiler complains about missing inputs, as no input was found. When I create an `index.js` it works without issues.

You are most likely **importing** these modules in your code. Note that `exclude` only excludes whatever files are included by `include`. You can't explicitly exclude files that you have imported in your code.

**Comment by markcellus** [comment]
Ah that makes sense. Sorry for the incomplete example. Closing...

**Comment by RyanCavanaugh** [comment]
> This has been reported in https://github.com/microsoft/TypeScript/issues/43043 and https://github.com/microsoft/TypeScript/issues/42797 which have been auto-closed. Still not sure why they were closed when the issue still exists in latest version

They were closed because they were misunderstandings of the `exclude` option.

**Comment by markcellus** [comment]
Oh wait @RyanCavanaugh why does it work when I replace the jsconfig.json with a tsconfig.json file? It no longer outputs the node_module errors.

**Comment by RyanCavanaugh** [comment]
jsconfig and tsconfig have different default settings

**Comment by markcellus** [comment]
Sure but what is the specific setting that is causing the difference in behavior?

**Comment by MatthewPinheiro** [comment]
I just made pull request https://github.com/microsoft/TypeScript-Website/pull/2839 to the TS docs site to detail the default settings of a jsconfig.json over a tsconfig.json. 

You're seeing this weird behavior because jsconfig.json sets the [`maxNodeModuleJsDepth`](https://www.typescriptlang.org/tsconfig#maxNodeModuleJsDepth) option to 2 (tsconfig.json default is 0). This means that when your code imports a `node_modules` package that doesn't have its own `.d.ts` file, tsc will follow imports into that package up to 2 imports deep. This is really helpful in cases where you want to infer typings for packages that don't have a type declaration file, but on the downside this also means that it ends up type checking a portion of your `node_modules` folder regardless of any include/exclude settings.

So you have two solutions. The best option is probably to manually install type definition packages (e.g. [`@types/express`](https://www.npmjs.com/package/@types/express)) for the modules you need. In fact, one of the other jsconfig.json defaults has TypeScript automatically search for and install these type definition packages into a global cache for you, but for reasons I'm unsure of this sometimes breaks. 

The other option is to set `maxNodeModuleJsDepth` back to 0, which will have the downside of eliminating typings for any packages that don't have a type declaration file.

**Comment by thernstig** [comment]
@MatthewPinheiro what is the rationale for the default ``"maxNodeModuleJsDepth": 2` in `jsconfig.json`, but not in `tsconfig.json`.

One never knows if an npm module has type declarations or not, no matter if it is a JavaScript or TypeScript project one is working on when importing modules from node_modules?

https://www.typescriptlang.org/tsconfig#maxNodeModuleJsDepth is not good I think. For example, the explanation you have above is important:

> ... end up type checking a portion of your node_modules folder regardless of any include/exclude settings.

In addition https://www.typescriptlang.org/tsconfig#maxNodeModuleJsDepth is weird in:

>The maximum dependency depth to search under `node_modules` and load JavaScript files

"and load JavaScript files"? That is very ambiguous.

> However, there are cases where you may want to turn this on at the expense of speed and potential accuracy.

"expense of speed" is a negative characteristic of enabling it. But "potential accuracy" is a positive characteristic, as I assume it means that it **improves** the potential accuracy?

TypeScript docs are generally good, but https://www.typescriptlang.org/tsconfig leaves much to be desired.
