### ISSUE TITLE
target cannot remove keyword completions from newer JS versions in jsconfig.json

### ISSUE THREAD

**Issue by RYLF5** [microsoft/TypeScript#50956]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.2
- OS Version: macOS 11.6.6

Steps to Reproduce:

1. File > New File save as test.js in a new folder "test"
2. Open folder "test" in vsCode
3. Click "Yes, I trust the authors"
4. run "Javascript: go to project configuration" from command palette
5. click "Configure jsconfig.json"
6. replace the default contents with<code>
{
    "compilerOptions": {
        "lib": ["ES5"]
     }
  } </code>
8. save jsconfig.json
9. type "con" in test.js
10. Observe that "const" is suggested by intellisense even though const is not supported by ES5:

![Screen Shot 2022-09-26 at 9 59 42 AM](https://user-images.githubusercontent.com/114416684/192300334-6f5c654f-8c15-4194-93f5-498719931eac.png)

This continues even after restarting vsCode. In one case jsconfig.json was respected (con didn't cause intellisense to suggest const), but after restarting vsCode jsconfig.json was no longer respected.

**Comment by fatcerberus** [comment]
For context: This is handled by the TypeScript language service.

`"lib"` only affects which builtin functions have their type definitions imported into the project.  TypeScript is used to parse both TS and JS and always parses the most modern syntax it supports, regardless of settings.  In a TS codebase the code would be transpiled to the target ES version, so using e.g. `const` would never be an error.  But builtins aren't polyfilled automatically, so the `lib` option lets you limit which builtin functions are suggested.

AFAIK there's no way to prevent it from offering `const` as a completion here.

**Comment by RYLF5** [comment]
Thank you for replying so quickly with a detailed answer!

So to get ES5 while having the advantages of intellisense is my only option to work in Typescript and then transpile to ES5? I looked into Babel, but seems that doesn't target a particular standard.

Is there any way to restrict syntax highlighting to ES5 to make sure that coloring is accurate in existing ES5 code? E.g. so that const doesn't get the same color as var?

**Comment by DanielRosenwasser** [comment]
We can't really rely on the `target` because it's unclear if a user intends to use a compiler to rewrite the code. They might be using ES5 as a shorthand for "use the ES5 `lib`".

> So to get ES5 while having the advantages of intellisense is my only option

I don't think that the two are at conflict. Auto-suggestion will provide things that it thinks are valid to write, but you ultimately get the say in whether you want to add that code. If you want to restrict what you can write, a linter might be the best option.

> I looked into Babel, but seems that doesn't target a particular standard.

[Babel's `preset-env` just downlevels to ES5 when no target is specified](https://babeljs.io/docs/en/options#no-targets), but I'm not an expert at it.

> Is there any way to restrict syntax highlighting to ES5 to make sure that coloring is accurate in existing ES5 code? E.g. so that const doesn't get the same color as var?

I believe that if you have semantic highlighting enabled, it will subtly color consts differently than mutable variables. But the keywords themselves are just both keywords or reserved keywords in all modern versions of the language, and there's no way to configure those differently.

**Comment by RYLF5** [comment]
Thank you for thinking about this.
