### ISSUE TITLE
Did `out` become `outFile`

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#5107]
I no longer see `out` in https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/tsconfig.json 

Is it deprecated? (sorry I couldn't find the main issue, although there are a few references to the topic e.g. https://github.com/Microsoft/TypeScript/issues/4399)

If so I would think of this as a breaking change in 1.6, worthwhile to add here : https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes 

refs https://github.com/TypeStrong/atom-typescript/issues/633 :rose:

**Comment by DanielRosenwasser** [comment]
Yup; see https://github.com/Microsoft/TypeScript/wiki/Compiler-Options:

> DEPRECATED. Use `--outFile` instead.

But I don't think it's a breaking change; we still support `--out`, it's just that `--outFile` isthe preferred way to go.

**Comment by basarat** [comment]
Cool :rose: I'll support both (by copying `outFile` to `out`) till there is a breaking change.

**Comment by DanielRosenwasser** [comment]
Wait, what do you mean exactly? Why can't you just use `--outFile`?

**Comment by basarat** [comment]
> Wait, what do you mean exactly? Why can't you just use --outFile?

I don't have to refactor any code past the point of parsing outFile from config

**Comment by DanielRosenwasser** [comment]
Well the two have slightly different behavior in [how the file paths are parsed](https://github.com/Microsoft/TypeScript/blob/331d26f40271c7a21c6fa74ffac633b45f653dda/src/compiler/commandLineParser.ts#L449). From my understanding, `--outFile` works relative to the path of `tsconfig.json`, whereas the path given to  `--out` is relative to the current working directory (i.e. wherever the user typed in `tsc`.

@yuit and @mhegazy might know more and should feel free to correct me.

**Comment by mhegazy** [comment]
There is no breaking changes here. both are supported. from the command line they both behave identically. the only difference is in tsconfig.json, `outFile` is resolved relative to the tsconfig.json file location (like other path properties in the file), while `out` is resolved relative to the current directory (a bug that fixing will cause a breaking change to existing projects).

Since the behavior of `out` does not make much sense, but we need to keep it this way to avoid breaking users, we added `outFile`, and encouraged users to use it instead. we intend to keep `out` with its current semantics supported.

**Comment by mhegazy** [comment]
see https://github.com/Microsoft/TypeScript/pull/4388 for more information.

**Comment by basarat** [comment]
Thanks for the clarification and link 🌹
