### ISSUE TITLE
Generic keyof types should contextually be constrained inside conditionals.

### ISSUE THREAD

**Issue by warent** [microsoft/TypeScript#51119]
# Suggestion

## 🔍 Search Terms

keyof type infer return from generic parameter ts(2322)

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [?] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [?] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

I don't know the answer to some of these questions, sorry.

## ⭐ Suggestion

```ts
type Bar = {
  "someNumber": number
  "someString": string
}
function foo<T extends keyof Bar, R extends Bar[T]>(target: T): R  {
  if (target === "someNumber") {
    return 42;
  } 
  return "hi";"
} 

const val = foo("someNumber");
```

TypeScript is smart enough to infer that `val` is `typeof number` because the input parameter is explicitly `"someNumber"`. However, for some reason it doesn't understand that the return type is constrained while inside the function.

i.e. the `return 42` line should be fine, because we have fixed the `typeof target` using our conditional `if (target === "someNumber")`, but TypeScript seems to completely miss that we're inside a constrained, well-defined conditional block, and it complains:

```
Type 'number' is not assignable to type 'R'.
  'number' is assignable to the constraint of type 'R', but 'R' could be instantiated with a different subtype of constraint 'string | number'.ts(2322)
```

## 💻 Use Cases

Useful for factories etc.

**Comment by jcalz** [comment]
Your example code emits an error for a good reason.  Generic function type arguments like `R` are specified by the *caller* of the function, not the implementation.  Yes, these are often inferred, but they can always be specified explicitly like this:

```ts
const val = foo<"someNumber", 0>("someNumber");
// const val: 0

({ 0: "oops" })[val].toUpperCase(); // RUNTIME ERROR 💥 
```

[Playground link](https://www.typescriptlang.org/play?ts=4.8.4#code/C4TwDgpgBAQghgJygXigbwFBSgIgM4D2AthAHICuRARhAjgFxQB2lNCWuhJAysAgJZMA5gyh4+goRgC+GAGbkmAY2D8CTKHIIEAPABUoEAB7AITACZ4oAawggCc2IgA0UAEqGTZy04QBtPQBdAD4ACmBEIQhgRj0ASkYPTGx+R3DI6JRkVHxiMlZaHDj0DmwEaPIEDQAWACYAbg5ZMoqq3AALfhxG2QwldXEoADc4ABsUTW0dXJIKakLXAAYwmfz5ujjGgHotqH6mQZHRxkWMULQoRcYcbTA8HChpOL8jwIA6YAIAVTBIBABhOB4CChTZQHbuL6kPQASQAsgBRKAItxuADyHkAvBuAUp2oEA)

Here the caller has specified that `R` is `0`, which is a subtype of `number`.  The call signature therefore claims to return a value of type `0`, but at runtime it is apparently `42`, which can cause runtime errors.  It is not appropriate to return `42` for a value of type `R`, since all the implementation can know about `R` is that it *extends* `Bar[T]`, not that it *is* `Bar[T]`.  Hence the error message.

---

If you remove `R` and just write 

```ts
function foo<T extends keyof Bar>(target: T): Bar[T] {
  if (target === "someNumber") {
    return 42; // error
  }
  return "hi"; // error
}
```

You still get errors in the implementation, but now this suggestion seems like a duplicate of #33014.

**Comment by warent** [comment]
Thank you @jcalz , fantastic thoughtful answer. You're right, it's a duplicate.
