### ISSUE TITLE
Cannot dynamically import JSX components in Next app

### ISSUE THREAD

**Issue by MariaSolOs** [microsoft/TypeScript#51124]
# Bug Report

### 🔎 Search Terms

next, dynamic import, nodenext

### 🕗 Version & Regression Information
Not sure when exactly this started happening, but I do have [this application](https://github.com/MariaSolOs/ramble-next) using TypeScript v4.3.5 and Next v11.1.4 where this wasn't happening (refer to this [code](https://github.com/MariaSolOs/ramble-next/blob/619266ea681380cae913f5fa9ce5fd6c1fef399e/components/GlobalLayout/GlobalLayout.tsx#L9-L23)).

### 💻 Code
I prepared [this small repo](https://github.com/MariaSolOs/nodenext-app) with a reproduction of the problem.

The issue is that I'm not able of using [Next's dynamic imports](https://nextjs.org/docs/advanced-features/dynamic-import) without getting TypeScript or build errors. 

Below I include the relevant code.
```
import dynamic from 'next/dynamic'
import '../styles/globals.css'
import type { AppProps } from 'next/app'

// TS error: Cannot find module 'components/DynamicButton' or its corresponding type declarations,
// but running "yarn dev" works fine.
const DynamicButton1 = dynamic(() => import('components/DynamicButton'));

// Argument of type '() => Promise<{ default: typeof import(\"/Users/majosolano/Desktop/nodenext-app/components/DynamicButton\"); }>' is not assignable to parameter of type 'DynamicOptions<{}> | Loader<{}>'.
// Type '() => Promise<{ default: typeof import(\"/Users/majosolano/Desktop/nodenext-app/components/DynamicButton\"); }>' is not assignable to type '() => LoaderComponent<{}>'.
// Type 'Promise<{ default: typeof import(\"/Users/majosolano/Desktop/nodenext-app/components/DynamicButton\"); }>' is not assignable to type 'LoaderComponent<{}>'.
// Type '{ default: typeof import(\"/Users/majosolano/Desktop/nodenext-app/components/DynamicButton\"); }' is not assignable to type 'ComponentType<{}> | { default: ComponentType<{}>; }'.
// Type '{ default: typeof import(\"/Users/majosolano/Desktop/nodenext-app/components/DynamicButton\"); }' is not assignable to type '{ default: ComponentType<{}>; }'.
// Types of property 'default' are incompatible.
// Type 'typeof import(\"/Users/majosolano/Desktop/nodenext-app/components/DynamicButton\")' is not assignable to type 'ComponentType<{}>'."

// On top of that, the development server crashes with a "Module not found" error.
const DynamicButton2 = dynamic(() => import('components/DynamicButton.jsx'));

// TS is happy, but the browser still shows a "Module not found" error.
const DynamicButton3 = dynamic(() => import('components/DynamicButton.jsx').then(({ default: button }) => button));

// Replacing the above examples with relative paths doesn't fix the error either.

function MyApp({ Component, pageProps }: AppProps) {
  return <Component {...pageProps} />
}

export default MyApp
```

### 🙁 Actual behavior

I cannot import `DynamicButton` without getting a TS error or the build crashing.

### 🙂 Expected behavior

I'm able to compile and build my JS application while making both NextJS and TypeScript happy.

**Comment by MariaSolOs** [comment]
Okay so after playing around I think that `"moduleResolution": "nodenext"` in my `tsconfig` is the culprit. Changing it to `"node"` fixes the issue.

I still think this might be a bug, given that I had not encountered issues with imports like `import DynamicButton from 'components/DynamicButton'`. It seems like the import inside `dynamic` is behaving differently...

**Comment by DanielRosenwasser** [comment]
Getting this working is not as minimal as we'd usually like for repos. I tried to get it running, and Next kept kicking the tsconfig out of `nodenext` - so I'm not sure off the bat how to configure Next.

So that said, here's at least a bit of friction that I noticed...

1. I think `components/DynamicButton` is expected not to resolve under `nodenext`. That's because the path needs to have an explicit extension (and folder imports do not work either).

   You might need one of:

     * `components/DynamicButton.jsx`
     * `components/DynamicButton/DynamicButton.jsx`

   __________

1. Assuming that `DynamicButton` is a folder, does `components/DynamicButton/DynamicButton.jsx` work? 

   If it doesn't, it might not be generated at build time. Instead, does `components/DynamicButton/DynamicButton.js` work?

   If that's the case, I believe that's toggleable by `"jsx": "react"`, rather than `"jsx": "preserve"`. This is expected, but confusing.

   __________

1. The type error is **extremely confusing**. What is happening is that because you opted into `nodenext`, every single existing file is understood to be a CommonJS file, whose contents only exist in a `default` export. So you need a second level of unwrapping the `default`.

   You can switch them all to ESM by adding `"type": "module"` in your `package.json`, and Next will tell you to rename your `next.config` file to use a `.cjs` extension.

   __________

5. Seems like TSServer is really slow to re-resolve after making a change to a path...

**Comment by MariaSolOs** [comment]
@DanielRosenwasser thanks for trying it out and sorry for the trouble. I'll try to be more minimal in the future.

> I tried to get it running, and Next kept kicking the tsconfig out of nodenext - so I'm not sure off the bat how to configure Next.

What exactly do you mean by Next kicking out the `tsconfig`? I just cloned the repo, ran `npm i` and `npm run dev` and it seems to be working as expected...?

I can successfully import the button without using `dynamic` and under `nodenext`. The code below works without any TS nor Next errors.
```
import '../styles/globals.css'
import type { AppProps } from 'next/app'

import Button from 'components/DynamicButton';

function MyApp({ Component, pageProps }: AppProps) {
    return (
        <>
            <Button />
            <Component {...pageProps} />
        </>
    );
}

export default MyApp
```

So I think that what makes this extra confusing is that the behavior with and without using `dynamic` is different.
