### ISSUE TITLE
the option of outDir is not work

### ISSUE THREAD

**Issue by classmatewu** [microsoft/TypeScript#51174]
### my tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es2015",
    "rootDir": "./src/index.ts",
    "outDir": "dist",
    "sourceMap": true,
    "declaration": true,
  }
}
```

### my script
```bash
"build": "tsc"
```

### my version
tsc Version 4.5.5
node Version 14.16.0

### performance
only outDir is not work, others option is normal

**Comment by fatcerberus** [comment]
Going to need more information than “it doesn’t work”

**Comment by classmatewu** [comment]
this is my output
<img width="210" alt="image" src="https://user-images.githubusercontent.com/44048381/195761314-28f8c5f5-6c4d-4a39-bd08-633f5e99d111.png">

**Comment by MartinJohns** [comment]
You specify a **file** for `rootDir`, that confuses the compiler. Replace it with `./src` and it works.

**Comment by ritschwumm** [comment]
sounds like an error message "rootDir points to a file but is expected to point to a directory" would be a good idea...

**Comment by dsatizabal** [comment]
Yes indeed, specifying the **src/index.ts** files makes it fail, wondering under which circumstances it would be valid to ser **rootDir** as the path to a file, thanks to @MartinJohns!

**Comment by fatcerberus** [comment]
Thanks @MartinJohns, I didn’t even spot that.

**Comment by classmatewu** [comment]
thanks o lot. But why the entry is not a/multi- file, but a dir?

**Comment by fatcerberus** [comment]
The option is called root**Dir**, why would you want to specify a file?

**Comment by classmatewu** [comment]
> The option is called root**Dir**, why would you want to specify a file?

Because I only bundle one file under the outDir.

**Comment by fatcerberus** [comment]
That's... not what that option is for.  It only affects what the directory structure of the outDir looks like relative to the input paths.  Directly from the documentation:

> **Importantly, rootDir does not affect which files become part of the compilation.**  It has no interaction with the `include`, `exclude` or `files` `tsconfig.json` settings.

Emphasis theirs.  If you only want to compile a single file, you should use `files` (but note it will still pull in anything imported by the single file): https://www.typescriptlang.org/tsconfig#files

If you want to compile multiple files but only have a single output file, you need to use a bundler because TS won't do that for you.
