### ISSUE TITLE
Class property type inference failure when destructuring return value of generic function

### ISSUE THREAD

**Issue by paul-go** [microsoft/TypeScript#51203]
# Bug Report

### 🔎 Search Terms

Class Property
Destructuring
Type Inference
Generic

### 🕗 Version & Regression Information

- This is a crash: No
- The issue occurs on the latest nightly (v4.9.0-dev.20221017), as well as on version 4.7.4. I haven't tested on other versions, but my suspicion is that this has been a hidden bug for a while.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.0-dev.20221017#code/FAYwNghgzlAEBiB7RwDexadiRA7KALgE4CuIBiRAFAJQZbpZOwDaBAFgJZQB0AHgBpYHbjwCeAXVgBeWJ1ycCtANz1MAX2BrYfVUzGrNwAGYlc5TnjkKCAHgAqAPlpptRAKYESRXKwAMQgBEgVLQrLgkALYARu5EQoRE8gDmEobAQA)

### 💻 Code

```ts

class Foo {
    constructor() {
        [this.x, this.y] = init();
    }

    x; // Any
    y; // Any
}

function init<T>() {
    return [0, ""] as [number, string];
}

```

### 🙁 Actual behavior

The `x` and `y` properties are typed as `any`.

### 🙂 Expected behavior

The `x` and `y` properties should be typed as `number` and `string` respectively.

### Further investigation

If the return value of the function is captured in a local variable, and then destructured from there, everything works as expected:

```ts

class Foo {
    constructor() {
        const bar = init();
        [this.x, this.y] = bar;
    }

    x; // number
    y; // string
}

function init<T>() {
    return [0, ""] as [number, string];
}

```

Or, if the generic argument is omitted, everything works as expected:

```ts

class Foo {
    constructor() {
        [this.x, this.y] = init();
    }

    x; // number
    y; // string
}

function init() {
    return [0, ""] as [number, string];
}

```

Making use the generic type argument `T ` does not appear to resolve the issue:

```ts

class Foo {
    constructor() {
        [this.x, this.y] = init(false);
    }

    x; // Any, should be number
    y; // Any, should be boolean
}

function init<T>(value: T) {
    return [0, value] as [number, T];
}

```

**Comment by fatcerberus** [comment]
As an additional note: If you're wondering why the compiler thinks `T` might depend on the type of `x` and `y`, it's due to the same contextual typing mechanism that makes this work:

```ts
let x: Promise<number> = new Promise(resolve => resolve("foo"));  // error on resolve call
```

**Comment by paul-go** [comment]
Well, I'm not familiar enough with the granularities of the type checker logic in order to refute what you're saying, but the error is still generated in the case when a default generic type argument is defined for `T`:

```ts
class Foo {
    constructor() {
        [this.x, this.y] = init();
    }

    x; // Still fails
    y; // Still fails
}

function init<T = string>() {
    return [0, ""];
}
```

If I'm understanding what you're saying correctly, then I would imagine that such a work-around should at least dodge the issue. But the error persists. Also worth noting that if the generic argument is provided at the call site, everything works as expected:

```ts
class Foo {
    constructor() {
        [this.x, this.y] = init<string>();
    }

    x; // number
    y; // string
}

function init<T>() {
    return [0, ""];
}
```

**Comment by fatcerberus** [comment]
The default is only used when TS can’t successfully infer a type for the generic.  It’s still going to try to infer it through the usual means, and thus hit the aforementioned circularity (which will indeed end with `T` getting its default type, to be clear).  At that point though the property in question now has an “implicit any” as its type and the compiler can’t walk it back because that would require more than one round of inference.  Hence the design limitation.

That providing the type argument at the call site dodges the error is fully expected - it bypasses generic inference (there’s no reason to prefer an inference over a type provided explicitly).

**Comment by fatcerberus** [comment]
In short, any case where type inference X depends on type inference Y and vice versa will be detected as circular, even if there’s a different way to infer X that avoids the circularity, because inference is only done in a single pass.  TS doesn’t do full unification (see #30134).

**Comment by fatcerberus** [comment]
Short version: TS tries to infer both `T` and `prop` “at the same time”.  Both fail because the inferences depend on each other.  `T`, being a type parameter, has a working failure case (fall back to default/constraint), `prop` does not and gets flagged as implicit-any.  There is no mechanism to try inference again and you get stuck with implicit-anys. 😢 

Fix would be to do type inference in multiple rounds (allowing failed inferences to be retried using information from the previous round), but responses to similar issues in the past have suggested it’s a performance issue.

**Comment by RyanCavanaugh** [comment]
This is a true circularity, as outlined above.

**Comment by fatcerberus** [comment]
Well, technically, it’s a finite spiral—`T` has a working fallback mechanism that would resolve the circularity if not for the restriction that types must all be inferable in a single pass.
