### ISSUE TITLE
Confused behavior of multiple rest elements in tuple

### ISSUE THREAD

**Issue by yyytiancai** [microsoft/TypeScript#51257]
# Bug Report
### ⏯ Playground Link
https://www.typescriptlang.org/play?target=5&jsx=0&module=5#code/C4TwDgpgBAcgqgWQEIFEBKBlKBeKA7AVwFsAjCAJwG0BdAKFEiiIIBtgBLNCAZ2AEYcUSgDpR8ZOgwAaKKOHjUmOg2jM2nHsABMgkaIBm7crwBc+YmSrUZc7hADGAezwATM4VIUa1IA

### 💻 Code
type NUMBERS = number[]
type multiRest1 = [...NUMBERS, ...NUMBERS]
type multiRest2 = [...first: number[], ...second: number[]]

### 🙁 Actual behavior

multiRest2 :A rest element cannot follow another rest element.

### 🙂 Expected behavior
multiRest1 should have the same report as multiRest2.

**Comment by RyanCavanaugh** [comment]
In higher-order situations, you're "allowed" to have consecutive rest elements - otherwise type instantiation could "fail", which isn't really a thing.

In zero-order, writing `[...first: number[], ...second: number[]]` is the same as writing `number[]` and indicates that you think something is happening when it really isn't. For example, you might think that `[...first: string[], ...second: number[]]` is making a type where zero or more strings are followed by zero or more numbers, but it's actually just `(string | number)[]`.

**Comment by yyytiancai** [comment]
您好，已收到。

**Comment by fatcerberus** [comment]
Hmm, a bit confusing then that the error message implies it’s completely verboten.

**Comment by yyytiancai** [comment]
> In higher-order situations, you're "allowed" to have consecutive rest elements - otherwise type instantiation could "fail", which isn't really a thing.

I still don't understand the meaning of this sentence. what is the difference between higher-order situations and zero-order situations?
`type NUMBERS = number[]
type STRINGS= string[]
`
 In higher-order situations, [...NUMBERS, ...STRINGS] will not expand like (string | number)[]?

**Comment by fatcerberus** [comment]
“Higher-order situations” meaning you’re passing a type variable (which includes type aliases in this case) rather than a known type.  This is allowed because `[ …TTuple1, …TTuple2 ]` is legal, but at the time that check is done, any type aliases involved haven’t been expanded—that happens later, during type instantiation, which the compiler has no means to make fail.
