### ISSUE TITLE
Spread object type inference error

### ISSUE THREAD

**Issue by wmzy** [microsoft/TypeScript#51253]
# Bug Report

### 🕗 Version & Regression Information

TS version: 4.8.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKlC8UDeAoKUBmB7LB+AXFAM7ABOAlgHYDmA3CgL70oDGWlJUAhoXIktiyEArpQAmEDFQhimrdpwBGCZIMIBydQBooAOn1cmQA)

### 💻 Code

```ts
type T = {
  foo?: string;
};

const a: T = {foo: undefined};
const b = {foo: '', ...a};
```

### 🙁 Actual behavior

![image](https://user-images.githubusercontent.com/5526525/197108646-85a11323-a35c-4d58-bac7-8bbaefb2d8a9.png)

### 🙂 Expected behavior

The type of `b` should be:
```ts
{
  foo?: string;
}
```

**Comment by fatcerberus** [comment]
There's no reason to infer `foo` be optional in `b` - there will always be a `foo` property, even if `a` doesn't have one, because you've provided it upfront.  The unsoundness here is that `undefined` is assignable to optional properties - you can enable `exactOptionalPropertyTypes` to prevent that.

**Comment by fatcerberus** [comment]
btw this is not destructuring assignment - it’s a spread.  Destructuring is when you do

```ts
let { x, y } = point;
‘``

**Comment by MartinJohns** [comment]
@fatcerberus Object spread only skips properties that *haven't been defined*, but it does not skip properties that *have been defined to be `undefined`*. Confusing, I know. The object ends up being `{ foo: undefined }`, so the type `string` is wrong.

But I'm certain there's an existing issue for this that I can't find right now.

**Comment by fatcerberus** [comment]
@MartinJohns Yes, I was aware.  Without exactOptionalPropertyTypes, optional properties can be set to `undefined`, but the type system still generally treats the property as if it’s either present-with-the-given-type or else non-present.  This is indeed unsound, but the fix is to enable exactOptionalPropertyTypes. 😄
