### ISSUE TITLE
Warn about emit with an implicit `outDir` of `.`, high likelihood of creating a mess

### ISSUE THREAD

**Issue by SephReed** [microsoft/TypeScript#51268]
Most people actively don't want a bunch of `.js` files spread throughout their project, put next to the `.ts` ones.  Unfortunately, this is the default behavior of `tsc`.

It may make sense to warn users before generating tons of files in this way.  Something like:
```
you don't have a dist target, so the following files will be created:
/me/code/project/src/user/user.js
/me/code/project/src/user/user-type.js
/me/code/project/src/user/user-connect.js
/me/code/project/src/home/home.js
/me/code/project/src/home/home-list.js
/me/code/project/src/home/home-buyer.js
/me/code/project/src/paint/red.js
/me/code/project/src/paint/orange.js
/me/code/project/src/paint/yellow.js
/me/code/project/src/paint/green.js
/me/code/project/src/paint/blue.js
/me/code/project/src/paint/magenta.js
/me/code/project/src/number/one.js
/me/code/project/src/number/one.js
/me/code/project/src/number/one.js

would you like to continue?(y/n):
```

Alternatively -- if changing default behavior is undoable -- being able to set global tsc to a "safe mode" where it actively tries not to create any messes would work.

**Comment by fatcerberus** [comment]
I could get behind a warning *if an `outDir` is not present at all*, which is indeed the case for the default `tsconfig.json` generated by `tsc --init` (it's commented out).  If `outDir` is explicitly set, even to `"./"` then there shouldn't be a warning, because this indicates the developer wants this to happen.

It doesn't even necessarily have to list all the files, IMO.  Just warn that because there's no `outDir` set the `.js` and `.d.ts` files will be created alongside the `.ts` files by default.

**Comment by SephReed** [comment]
what tends to happen to me is I'll intend to write `ts-node` and write `tsc` while running a test file, then it'll end up going through every single ts file referenced by the test and generating a .js one.  Clean up is easy ish, it only requires going through my git changes and dropping the creation of any .js file.  But it's still somewhat nerve-wracking.. I'm always very worried I'll discard some useful changes too.

**Comment by RyanCavanaugh** [comment]
The behavior implied by the title change isn't something we'd do. There are many questionable configs and we don't do Y/N prompts to have the user confirm they know what they're doing.

**Comment by SephReed** [comment]
That's your title.  I can change it back to what it was before you changed it, and perhaps you can look over the text in the question as well?

**Comment by RyanCavanaugh** [comment]
What's the question?

**Comment by RyanCavanaugh** [comment]
I guess I don't understand the `--warnWithoutOutDir=true` thing. If you knew to write that in the first place, you wouldn't have the problem. It's the people who don't realize they're about to make a mess who are affected by this behavior.

That's why I felt like the implicit suggestion was the one I rewrote the title to -- that `outDir` shouldn't be `.` unless someone explicitly opts in to that behavior. That allows people to specify that they're making a "mess" on purpose without having to have an opinion about what the default `outDir` should be.

We don't really have any behavior of the form "Just *nag* the user and continue"; usually proposing unprecedented modes of operations isn't going to go very far unless the value proposition is extremely strong.

**Comment by SephReed** [comment]
>  If you knew to write that in the first place, you wouldn't have the problem.

The first time, yes.  But habits exist.  I'm sure you have many examples of learned command line habits which add to a base command.   Here are some of mine:
- `sudo apt install` (could be run without sudo, never do)
- `npm init -y`
- `ls -a`
- `git commit -m "some message"`

If there was a `tsc --safe` then I could make a habit of using it, and eventually `tsc` alone would seem wrong.  And I think it would be very nice to have a command with consistent outcomes.
