### ISSUE TITLE
Incorrect function union type

### ISSUE THREAD

**Issue by whitneyit** [microsoft/TypeScript#51355]
# Bug Report

### 🔎 Search Terms

* [function union](https://github.com/microsoft/TypeScript/issues?q=function+union)
* [function union never](https://github.com/microsoft/TypeScript/issues?q=function+union+never)
* [function types](https://github.com/microsoft/TypeScript/issues?q=function+types)

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _functions_

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcDCEC2YCGVgBKwAzgK4A28AvHALQCMcAPnAAzNz0DcAUD6JFgJkqDNjzAAYgDsAcqUwAjYFDg0AFBGnAAXHGkLlUADQIA7hD0GlKgJRqAfOiy58RMpV4Do8JCmfi+DIAyjBQAJbSAOZqcJraesRhkVGmMBaJydH2VE5iroQkFDC8-OA+wv75EjKx1UFyhioc9VLSoRHRpQAmwADG5BJwfVpJwy410nqtMj39g-jj0mPWRgDyCfpNULy9A0Mjy-CrKgAqGVs2O3x7C6iHY0mdURu6cE8pu-MHo-Af0edLO8slFSiNAm11CcoK9TNDAbZeOCCjJ1P8XtpTOiEVwgA)

### 💻 Code

```ts
export type CompareResult = -1 | 0 | 1;

export type CompareFnNumber = (one: number, two: number) => CompareResult;
export type CompareFnString = (one: string, two: string) => CompareResult;

export type CompareFn = CompareFnNumber | CompareFnString;

declare const compareFn: CompareFn;

declare const numberOne: number;
declare const numberTwo: number;

declare const stringOne: string;
declare const stringTwo: string;

compareFn(numberOne, numberTwo);
compareFn(stringOne, stringTwo);
```

<details><summary><b>Output</b></summary>

```ts
compareFn(numberOne, numberTwo);
compareFn(stringOne, stringTwo);
export {};

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

</details>

      

### 🙁 Actual behavior

The following errors are thrown:

> Argument of type 'number' is not assignable to parameter of type 'never'.
> Argument of type 'string' is not assignable to parameter of type 'never'.

### 🙂 Expected behavior

No errors to be thrown.

I would expect in the first case, that `compareFn()` be typed as `CompareFnNumber`.
I would expect in the second case, that `compareFn()` be typed as `CompareFnString`.

However, what actually happens is that `compareFn()` gets typed as `(one: never, two: never) => CompareResult`.

**Comment by MartinJohns** [comment]
This is working as intended. When calling a union of functions, you must provide arguments matching all overload versions, because the compiler can't possibly know which version it actually is. So the argument you must provide is of the type `number & string`. But such a type is impossible to represent, so you end up with `never`.

**Comment by Andarist** [comment]
Perhaps you have wanted to represent overloads here and for that, you can use and intersection (rather than a union):
[TS playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcDCEC2YCGVgBKwAzgK4A28AvHALQCMcAPnAAzNz0DcAUD6JFgJkqDNjzAAYgDsAcqUwAjYFDg0AFBGnAAXHGkLlUADQIA7hD0GlKgJRqAfOiy58RMpV4Do8JCmfi+DIAyjBQAJbSAOZqcJraesRhkVGmMBaJydH2VE5iroQkFDC8-OA+wv75EjKx1UFyhipwAGQBBSFZUaUAJsAAxuQScP1aSSMuNdJ69VLSvQND+BPS49ZGAPIJ+k1QvH2Dw6Or8OsqACoZOzZ7fAdLqMfjSRHRW7pwLyn7i0dj8F9opdLJ8uqVRoE5uozlB3qYYcDbLwIR1pOpAVE4aDXlFEaUAPT4uAAARgxFoAgGMApUCg0B4KKm6K6WIRFiRQA)
