### ISSUE TITLE
generic bound doesn't work when used in index type with concrete index type

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#51394]
# Bug Report

### 🔎 Search Terms

index type generic 

### 🕗 Version & Regression Information
4.9.0-dev.20221025
### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.0-dev.20221025&ssl=8&ssc=60&pln=8&pc=59#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChnJwBcyIArgLYBG0A2gLr7JUkDOYUoA5g7gL65cAEwgIANnCgoE6EO2QxMJDOkEy5YZKwhgAanDFkUAXmQAeACrIIAD0gghrZAGsIAT3Qw0mAHwAKVzcSCwAaZAA3AyNlTFoLelpyamh6AEpkYx8cJgB6AComCzcABxQAcj92ThAuZAAfUkoaKFSGMuRgJxB0TThWVmAuEDgqMRQwLDAS8pU4+jKAOiZkItLkCqruesbklraOrp7CfsHh0fHJ6fWk5oZkADItDm42pYJ31fLK55rtm+hWvMDqQjn0BkMRmNkBNoVcyv8oK9lu8VnDNr8Ggj2p0Qb0ThDztDLmt4U1oItkSjUST0VxsYc8eCzlCYVMSVi3sg8jkmIp0LRAvQMshaJFDBBGHwgA)

### 💻 Code

```ts
interface Foo {
  a: number[]
  b: string[]
}

declare const foo: Foo

const setValue = <T extends keyof Foo>(key: T, value: Foo[T][number]) => {
  foo[key] = [value]
}
```

### 🙁 Actual behavior
```
  Type '(string | number)[]' is not assignable to type 'Foo[T]'.
   Type '(string | number)[]' is not assignable to type 'number[] & string[]'.
     Type '(string | number)[]' is not assignable to type 'number[]'.
       Type 'string | number' is not assignable to type 'number'.
         Type 'string' is not assignable to type 'number'.
```
### 🙂 Expected behavior
no error, since it works when the type of value is `Foo[T]`:
```ts
const setValue = <T extends keyof Foo>(key: T, value: Foo[T]) => {
  foo[key] = value
}
```

**Comment by jcalz** [comment]
This is similar to #30581 and as such the current non-type-assertion solution is to refactor as mentioned in #47109, but the cure might be worse than the disease. 

---

So, TS is protecting you from doing this (unlikely in practice) terrible thing:
```ts
const setValue = <K extends keyof Foo>(key: K, value: Foo[K][number]) => {
  foo[key] = [value] // compiler error
}
setValue(Math.random() < 0.999 ? "a" : "b", "oopsie"); // no compiler error
foo.a.map(x => x.toFixed()) // 99.9% chance of runtime error
```

Of course that same problem can happen in the version that "works":

```ts
const setValue = <K extends keyof Foo>(key: K, value: Foo[K]) => {
  foo[key] = value // no compiler error
}
setValue(Math.random() < 0.999 ? "a" : "b", ["oopsie"]); // no compiler error
foo.a.map(x => x.toFixed(2)) // 99.9% chance of runtime error
```

But, as described in https://github.com/microsoft/TypeScript/pull/30769#issuecomment-498428559 
> One rule we've always had is that any given type (and, by extension, any `T[K]` for identical `T` and `K`) is by definition assignable to itself, and that's the basic unsoundness we permit.
So assignment `lhs = rhs` is allowed if `typeof lhs` and `typeof rhs` are considered *identical* by the compiler, even if it would be unsound to allow it. 

The version that works has identical `Foo[K]` on both sides, but the one that fails has `Foo[K]` on the left and `Foo[K][number][]` on the right, so they are not identical.  You could rewrite your types as described in #47109 so that the compiler sees the assignment as being identical types on both sides, which involves multiple reassignments (but no type assertions):

```ts
type _Foo<K extends keyof Foo = keyof Foo> = { [P in K]: Foo[P][number][] };
const _foo: _Foo = foo; // no compiler error
const setValue = <K extends keyof Foo>(key: K, value: Foo[K][number]) => {
  const __foo: _Foo<K> = _foo; // no compiler error
  __foo[key] = [value]; // no compiler error
}
```

But, uh, all that to work around stuff so that it permits unsoundness without type assertions is a little much; you might as well just assert and move on:

```ts
const setValue = <K extends keyof Foo>(key: K, value: Foo[K][number]) => {
  foo[key] = [value] as Foo[K]; // no compiler error
}
```

It would be nice if there were something better here, but I don't know what that would be.

[Playground link](https://www.typescriptlang.org/play?ts=4.8.4#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChnJwBcyIArgLYBG0A2gLr7JUkDOYUoA5g7gL65cCdCHbIYmEhiwBeHE2LIGAGiYsljAbhBwKEVgAdEKAPKcu8gsNFhkrCGABqcADZkUcgDwBpZBAAekCAAJqzIANYQAJ7oMGiYAHwAFJFRJN7KyABuru5SmLTe9LTk1ND0AJTIMgmWBOIFqfTVSjluEIwEAgT2TrkQSQCycGAAFgB0UHAh6BRJVZ7IAAzjAJzryAD8yABEcDvIJDtUO5k7mAaswBA7FQDcTBxRdQQS6ONw4xRwBkn+1bV-OMwOhUMB-BBgkkAEwVKoAenhyHWawApMgEKNpkhkFAyOBgHo-FAoOgoEw+BiRpjkEkIFU8PUMSJWOgXBBxi50Fw6QikUCQWCIcFkMAwiB0LY4OJ8QgwMARBT+NpdPojDiAMqqgAKpKo7Io8iY1jEvWc7RaPj8gQgITCqVi8XQyVS6UybTyTsKlQBLwa6FoTRaHogSp6DnN7iGIwmUxmcwWyzWG22ewORxOmVo53Ql2uO0qDwITz9bw+Xx+f19AtB4MhMLhyERyNWaIxWJAOLxBKJ0FJ5K6VLANN5fpNbI5XJ59Kb-OBteFovFksIMs78sVXWVKr0hmMyAAShB4HKyQAWADsAEYlqsjcWogYUAB9aRWgJBUIRaKO6QtB1xNItRyNgSjaqKIDIEU+QBtqxSlDQUDFM0fBFsyNjIM+bwkK+mAtG8aEmrYZr9JavgfraX4AU6LrRG62T9DB3olJQiE+jUY4srYz5YZImFvt4wGYQRTAEDxbyBtEzRyLQIb0GhWhaDou7qiggzAFwoxgAAgqwADqEAuC4dREXYEakV45E2na34xIBiQpHRUHuoxXpFCxZRIVUHGMvUElBjJexUAgBaEGE0jegp-BAA)

**Comment by fatcerberus** [comment]
#30769 is related, as it's the source of the intersection behavior you see (`number[] & string[]`) in the OP.  Prior to that PR being merged, patterns like this actually used to work.

> So, TS is protecting you from doing this (unlikely in practice) terrible thing

I'm not convinced it's that unlikely either.  While nobody is going to write `Math.random() < 0.999 ? "a" : "b"` for the key, they *may* be passing the key in via a variable typed as `keyof Foo` and then all bets are off (worst case scenario: one of the properties is typed as `unknown` and now you can pass in *anything at all* for the value).  I feel like the "correct" (i.e. most elegant) solution to this problem would be to implement [`oneof` constraints](https://github.com/microsoft/TypeScript/issues/27808), wherein the compiler can know for sure that `T[K]` isn't going to be a union of several property types.

**Comment by DetachHead** [comment]
@RyanCavanaugh what is this a duplicate of? all of the links above were merged PRs, i don't see any other open issues for this?
