### ISSUE TITLE
Using `satisfies` on a self-referencing object causes `any` - TS 4.9.2-RC

### ISSUE THREAD

**Issue by mahdiboomeri** [microsoft/TypeScript#51495]
# Bug Report

### 🕗 Version & Regression Information
Version 4.9.2-rc

### 💻 Code

```ts
interface Items {
  id: 'a' | 'b';
  condition: () => boolean;
}

// 'items' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.ts (7022)
const items = {
  foo: {
    id: 'a',
    condition: () => true
  },
  bar: {
    id: 'b',
    condition: () => items.foo.id === 'a'
  },
} satisfies Record<string, Items>;

```

### 🙁 Actual behavior

`items` implicitly has type `any`.

### 🙂 Expected behavior
`items` should be checked with the `Items` interface and still have typesafe keys.

**Comment by DanielRosenwasser** [comment]
I'm not sure if there's a way for us to avoid pulling on the type of `types` here before it's been initialized, but since [you can observe the same thing with a "fake" version of `satisfies` in older versions of TypeScript](https://www.typescriptlang.org/play?ts=4.8.4#code/JYOwLgpgTgZghgYwgAgJKQLYGdkG8CwAUMssACYBcyA5HNcgD40BG1A3ESQgPYhnBhgvKgAoAlMgC8APmTNu3ADYQ4IDoQC+RImQgJFcKChgBXEAkG9kWOIKwxgELAB4AqgBpkAFWQQAHpB8OK5SyK7SIgBucIpUXmJx2oQA9Mk0AhDY9MAYAA6KwAgCigCeyAAWcDhgJbkotCAl9Mx6cCZYKALIZNxOyCDcYBVwkShwyDV1yKoDYLZCINN8pDhGMNAQ5hBk3cBGFqXI3FCkfHt6YIegpGA43ADui6ACwDHAAF7QAHS3yCIA7AAGABMwLERB4ICwQwy2FCNjsDiczgASnpjmRnNCoKAAOaedCZLDSCIEYjIGAKKhkkgkchUWjUdycWmQ-iWECiCQyCZQEwQFkaZnk5iGaksumUFhMiXINkvYR-bmyWFYL6U7hfchSSSSGh0QXCjRiNhAA), I might be tempted to say that this is an expected design limitation.

```ts
interface Items {
  id: 'a' | 'b';
  condition: () => boolean;
}

declare function satisfies<U, T extends U = U>(val: T): T

// 'items' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.ts (7022)
const items = satisfies<Record<string, Items>>({
  foo: {
    id: 'a',
    condition: () => true
  },
  bar: {
    id: 'b',
    condition: () => items.foo.id === 'a'
  },
});
```

That said, maybe we could do something a little different here. We could possibly defer *all* comparisons for `satisifes` until after all deferred function bodies have been checked as well. So basically `satisfies` does nothing except for provide a contextual type at first, and *then* is checked after everything else.

**Comment by fatcerberus** [comment]
Wait, why isn't this just a straight circularity?  `items` does indeed reference itself in its own initializer so it's kind of weird that the presence or absence of `satisfies` makes a difference.

**Comment by DanielRosenwasser** [comment]
TypeScript can create a type without fully resolving the types of each member. By doing that, and waiting to fully check function expressions, that allows us to create a type that we can refer to, and even request the types of some other members, without the type-checker being forced to eat its own tail and run into a circularity.

It allows [code like the following too](https://www.typescriptlang.org/play?ts=4.8.4#code/MYewdgzgLgBAZjAvDAFASiQPngbiA):

```ts
const f = () => f;
```

(at least, that's my understanding)

**Comment by fatcerberus** [comment]
I feel like TS needs better error messages.

The error text…

> because it does not have a type annotation and is referenced directly or indirectly in its own initializer

…implies that simply referencing yourself is sufficient cause for error, but in reality sometimes it’s allowed (intentionally, even).  I’m starting to see why people complain so much about TS being inconsistent—context matters, but the error messages tend to speak in absolutes, making any difference in error-producing behavior look like a bug…

**Comment by RyanCavanaugh** [comment]
> because it does not have a type annotation and is referenced directly or indirectly in its own initializer

Would adding "... in a way that could not be deferred" move the ball?

**Comment by greg-hornby-roam** [comment]
I've been getting around stuff like this using a var to hold an item

```typescript
interface Items {
  id: 'a' | 'b';
  condition: () => boolean;
}

let f: Items;

const items = {
  foo: f = {
    id: 'a',
    condition: () => true
  },
  bar: {
    id: 'b',
    condition: () => f.id === 'a'
  },
} satisfies Record<string, Items>;
```

**Comment by douglasg14b** [comment]
@RyanCavanaugh Is this the final behavior that is expected? That types cannot self-reference and use `satisfies`?

I ask because this was auto-closed as not-a-defect, and this behavior is actually somewhat frustrating for self-referencing types that are const assertions, which use the `satisfies` operator. Making such types non-viable.
