### ISSUE TITLE
Custom module resolution - Language Service Plugin

### ISSUE THREAD

**Issue by WalterWoshid** [microsoft/TypeScript#51493]
I'm trying to create a [Language Service Plugin](https://github.com/microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin) to extend module resolution.

For example:
```ts
// custom-types.d.ts
declare module 'customFolder/fileName*.js' {
  function abc(): string;
}

// customFolder/fileName3.js
abc();
```

Now this plugin should find all source files which matches the wildcard string `customFolder/fileName*.js` and add the `abc` function declaration, so it doesn't return `TS2304: Cannot find name 'abc'.`.

Resolving the source files works as expected, but adding the declarations seems not possible. I tried proxying the `getTypeChecker().resolveName()` method, but the typeChecker returns a new instance. 

Is there any way to add these declarations to the source file?

**Comment by MartinJohns** [comment]
You forgot to fill out the issue template.

From your link:
> Plugins can't add new language features such as new syntax or different typechecking behavior, and plugins aren't loaded during normal commandline typechecking or emitting, (so are not loaded by `tsc`).
> [..]
> Examples of things language plugins cannot do:  
> - Customize the type system to change what is or isn't an error when running `tsc`

Fairly sure your use case would fall under this case.

**Comment by WalterWoshid** [comment]
@MartinJohns Thanks for the information.

**Comment by SamuelScheit** [comment]
@WalterWoshid how were you able to resolve this issue?
I've been working on adding custom syntax to typescript and compiling works as expected with `tsc`, however VSCode marks it as an error.
I'm using `transformProgram: true` for my plugin and patched `tsserver.js` and all other ts libraries,
but it seems like the ts language service incrementally builds the project files and does not recreate the program?
I've seen that `ts-patch` also patches the emit function of the program, but it looks like the `getSyntacticDiagnostics()` function of the language service does not use `program.emit(...)` and therefore uses the input program, that wasn't processed by my plugin.
Btw. if I patch `getSyntacticDiagnostics()` to always return an empty array `[]` VSCode does not show any errors, but that is not a solution, because I still want to display normal errors after the program has been transformed by the plugins.

> Plugins can't add new language features such as new syntax or different typechecking behavior, and plugins aren't loaded during normal commandline typechecking or emitting, (so are not loaded by tsc).
[..]
Examples of things language plugins cannot do:
Customize the type system to change what is or isn't an error when running tsc

I know that the official ts language service plugins cannot modify the program, but after ts patching the createProgram function, the transform plugins are applied properly, but at a stage where not all project files are loaded yet.

@nonara maybe you have an idea on how to approach this problem?

**Comment by nonara** [comment]
If you're looking to extend language / compiler functionality, your best bet is most likely forking the compiler and adding the functionality directly. 

In the course of doing that, you may learn the underlying mechanisms well enough to figure out a workaround way via existing tsp, but ultimately, I think that extending the language on that scale (beyond simple diagnostic modification) will require the ability to add custom compiler patches.

That said, though we don't currently have a time frame in mind for release, the future tsp redesign will include the ability for compiler patches. The current release had much of the foundation in place.
