### ISSUE TITLE
Inconsistent literal type widening with `satisfies` operator

### ISSUE THREAD

**Issue by dragomirtitian** [microsoft/TypeScript#51516]
# Bug Report

### 🔎 Search Terms

satisifies tuples

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because this feature is new

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.0-dev.20221114#code/DYUwLgBAHhC8EG0BEBBJBdCBnAhmAllgGb4haKpIQA+ESAQhhAPTMVroBQokA9nBADeEAA4AuOmggBfbHkIkyQ0RMo06jGZ27gIATwFrcBYqXJraDKizZYwAJ3wA7AOZA)

### 💻 Code

```ts
let x = ["A"] satisfies ["A" | "B"] // ["A"]
let o = { p: "A" } satisfies { p: "A" | "B" } // { p: "A" }

let y = "A" satisfies "A" | "B"  // string
```

### 🙁 Actual behavior

For the first two, we have the literal types preserved, while for the last one the type is widened to `string`

### 🙂 Expected behavior

literal types are preserved either in all cases or in none of the cases

**Comment by hameda169** [comment]
While using a constant string inside of an array or object, it's considered a `const` but while using it otherwhere, you should cast it as a const if you mean it. 
```js
let y = "A" as const satisfies "A" | "B"  // string
```

**Comment by dragomirtitian** [comment]
@hameda169  Why is it considered a `const` inside an array or object ? It isn't usually so. Normal inference without `satisfies` or `as` would have it as `string`, even when assigned to a `const`. 

One could argue that since `satisfies` has no hint of immutability in it and since the array and object are mutable, the correct types should be `["A" | "B"]` and `{ p: "A" | "B" }`

**Comment by fatcerberus** [comment]
I'm a bit surprised it's inferring literal types at all.  `satisfies` isn't supposed to change the inferred type of an expression and without it you get  `string[]` and `{ p: string }` for `x` and `o` respectively.

**Comment by dragomirtitian** [comment]
@fatcerberus That was my understanding of the operator as well. The behavior is surprising. It also changes the type of an array to a tuple if we use the trick of constraining `[] | any[]` which is how I originally stumbled on this:

```ts
let t = [1,2] satisfies [] | any[] // [number, number]
```
[Playground Link](https://www.typescriptlang.org/play?ts=4.9.2-rc#code/DYUwLgBJC8ENoEYA0AmAuhAzgQzAS0wDM8RN4MAfCbAOwE84MB6J+GgVwFsAjEAJyQQOPfmiA)

**Comment by RyanCavanaugh** [comment]
We have a bit of a competing invariant problem here: The design goal of the `satisfies` operator is that
 * The overall expression type is the type of the asserted expression
 * The expression should be contextually typed by the asserted type

These principles are in direct conflict when it comes to literal types and there's not a clear way to resolve the situation without just creating a different inconsistency. The root cause is that the process that causes the bare literal `"A"` to decay to `string` (widening) is different from the process that causes e.g. the literal `[1, 2]` to become `[number, number]`.

Maybe some day someone smarter than all of us can unify contextual typing and widening into a single process and fix all this (this is not sarcasm btw, I believe it's possible), but until then all we can really say is that these types are fully consistent with the different processes which produce them and that we'd actually be introducing more inconsistency by trying to undo those processes.

For something like
```ts
let t = [1,2] satisfies [] | any[] // [number, number]
```

I think you could make a variety of arguments about what the "correct" type of `t` depending on the names of variables, what line of code follows, etc.. It's just not clear. The *observed* type of contextually-typed expressions was previously very hard to get at in TypeScript but this feature makes it fairly transparent, unfortunately, since people's mental models of how contextual type works are frequently wrong (and understandably so; they are subtle).

**Comment by acutmore** [comment]
The [4.9 announcement post](https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/)  says:

> The new satisfies operator lets us validate that the type of an expression matches some type, without changing the resulting type of that expression.

If that is not entirely correct it feels like the documentation around the operator should elude to there being situations where the inference is impacted, maybe with links to read more for the curious reader. That said I do appreciate the need for a certain level of brevity and explaining the intuition to have for these cases is no easy task.

**Comment by dragomirtitian** [comment]
I'm actually happy to have a way to force the inference of  mutable tuples. I will be recommending this when the need arises:

```ts
let t = [1,2] satisfies [] | any[] // [number, number]
```

I was just making sure this is intentional behavior and not a bug. Like @acutmore mentioned, the high level description of the `satisfied` operator confused me into thinking  this behavior might be bug:  

> The new satisfies operator lets us validate that the type of an expression matches some type, without changing the resulting type of that expression.

**Comment by RyanCavanaugh** [comment]
I guess the precise wording would be that

> The new satisfies operator lets us validate that the type of an expression (evaluated with a contextual type of the asserted type) matches some type, without coercing the resulting type of that expression to the provided type.

If the operator didn't work this way, then `[1, 2] satisfies [number, number]` would actually fail, which I think would seem pretty weird.

**Comment by acutmore** [comment]
I like that wording, nicely out.

**Comment by fatcerberus** [comment]
> If the operator didn't work this way, then `[1, 2] satisfies [number, number]` would actually fail, which I think would seem pretty weird.

Agreed, with the caveat that this is then squarely in "design limitation" territory - it feels very much like the *intent* of `satisfies` is that such an assertion should succeed without changing the type of the expression, and the only reason this is impossible today is because of internal compiler implementation details.

**Comment by RyanCavanaugh** [comment]
> it feels very much like the intent of satisfies is that such an assertion should succeed without changing the type of the expression,

I guess the question is how you would interpret `x => (x + 1) satisfies (n: number) => number`. For `[1, 2]` we can reasonably discuss its narrowest possible type `readonly [1, 2]`, but for a function expression it's sort of meaningless to talk about its narrowest possible type (in the absence of a completely different type inference algorithm).

**Comment by Zamiell** [comment]
Here's a slightly different example of the `satisfies` behavior:

https://www.typescriptlang.org/play?ts=5.0.0-dev.20221118#code/KYDwDg9gTgLgBDAnmYcASBDAzgQQDZ4CiAdgK4C2A0sIlgDwAqcoMwxAJlnFjFAJbEA5nAA+cMuQBGwKAD44AXjgBvAFBw4UYBnYRieRHADaAaxpwBcBgF0AXHFLETxCAHdiAblUBfL6rYUcACyiCSBahoaAGoYeKTAAIwANOqRMXHAAEwpkXDp8QDMKd6qqgD0AFQVcOrVOHDkGGBgAsIQAGbBoRIIEHAY4hTSUAikYHjAAHS1NXDVDAAWfFwL2OJ9MlDQWNNzZf7g0PAAxno8wQCaAPqEAHIAqkFXDADyVw9BAEKEAErP9wAFAAyhCuCXsEU02l0+kMpnMlhCYXIdjgP2hegMQSadAkwySxhA9jxMgJiGJQxk1lkXm8ihUqSMSIkk3yiVRxGArmCTQAFEZUhojAAGAlGAC0yTgBWs1hycGsAEoUozmRRWbF4pkOVyeWB+YLjKLjJKCTK5YajFKrUVpbL5UqVUK1eQNRkZcTddj9QLciKxQA2AmS+2W61BuAAdlDfuyxgAHAToxaNI6fP0uKdiDw-JUKjN6o1mq04B0usjev1BlIZKNxlM4LzFqhQBhjvAsBhyKgYEshBm4NJ2tAporajNFss4KsuJttoPgMcMKQsKhXKgdOxgOwqwAiTswZbtPjALC7uBZnhQDACGCTOAAdVW8EEfAAbqeAPy1fagSCwC8zngIJrjuR5njeD5vj+BhARBK5MghVItB0TE4TMQxEW6ChUXRVDYW9XFKSgMUiWrfE4HJciqRpdMlEhJlsNdNkEh1blvQNP1jQlKVzQdZVSmdJi3S1Ni9U4yJ-RNXiY0k60EltPjUjTVVhLZD1xC9PlfUk7iIxDFM5MDJNZKFOMjETKNZLTOk1kvDsMEPLBj1PdBsHwIgJGoWg6BdWigA

In this playground, we have two identical objects. But with the second object, we add a `satisfies` constraint, which causes it to throw a compiler error. But the compiler error has nothing to do with the constraint - it has to do with the `satisfies` operator actually mutating the type of the object itself (which causes the `as const` part to not work properly, I guess).

I *think* that this is just the same widening behavior that the OP is describing, but I'm not 100% sure.

Like others in the thread, I would naively expect the `satisfies` operator to be a "verify my thing" operation, not a "subtly modify the thing I just created while also verifying it" operation, so some more documentation surrounding this would be appreciated. (Right now, I can't even find any documentation for `satisfies` on the [official handbook](https://www.typescriptlang.org/docs/handbook/)!)
