### ISSUE TITLE
private Auto-accessors do not transform in esnext when useDefineForClassFields is false

### ISSUE THREAD

**Issue by rbuckton** [microsoft/TypeScript#51528]
Playground: https://www.staging-typescript.org/play?ts=5.0.0-pr-50820-31

When target is ESNext,

```ts
class C {
    static accessor h = 0;
}
```
is transformed, but
```ts
class C {
    static accessor #h = 0;
}
```
is not. I will expect they are both transformed until the proposal reaches stage 4.

_Originally posted by @JLHwung in https://github.com/microsoft/TypeScript/issues/50820#issuecomment-1314349887_

**Comment by rbuckton** [comment]
@JLHwung, I assume you are using `--target esnext --useDefineForClassFields=false`? Neither declaration transforms when `--target esnext --useDefineForClassFields=true` (which is the correct behavior), but only one of the two declarations are transformed when `--useDefineForClassFields=false` (which is a bug).

**Comment by JLHwung** [comment]
> @JLHwung, I assume you are using `--target esnext --useDefineForClassFields=false`? Neither declaration transforms when `--target esnext --useDefineForClassFields=true` (which is the correct behavior), but only one of the two declarations are transformed when `--useDefineForClassFields=false` (which is a bug).

Yes, you are right. actually I didn't known the `--useDefineForClassFields` option until you mentioned. 😄

> Neither declaration transforms when --target esnext --useDefineForClassFields=true (which is the correct behavior)

Well on that REPL the decorator syntax e.g. `@dec class {}`will be transformed when targeting `esnext`, so I assume the `esnext` is for stage-4 proposals only. If that is correct, it feels strange to me that the auto-accessors are preserved while decorators are transformed, since they are in the same proposal.

**Comment by fatcerberus** [comment]
@JLHwung `esnext` in practice means “don’t transform anything”;`useDefineForClassFields` defaults to `true` in that case, as turning it off is non-spec compliant.  You only have to explicitly set it to `true` when targeting an ES version that predates class fields (for backwards compatibility reasons specific to TS).  It sounds like you might have `useDefineForClassFields` explicitly set to `false`, so you should probably make sure there isn’t a good reason for that before enabling it.

As for proposals, you don’t need to wait for Stage 4 for new features, since TS implements them at Stage 3.  S4 literally just means the feature made it into a published spec, so if TS waited until then `esnext` wouldn’t need to exist at all.

**Comment by JLHwung** [comment]
> You only have to explicitly set it to true when targeting an ES version that predates class fields

@fatcerberus I assumed you mean `useDefineForClassFields: false` here. If so I agree with you. Thanks for clarifying the `esnext` target.

**Comment by rbuckton** [comment]
The 5.0.0 beta seems to have made this worse, going from not transforming `accessor #h`, to crashing. I'll have a fix up for that shortly.
