### ISSUE TITLE
Unexpected behavior returning type using a type predicate

### ISSUE THREAD

**Issue by sergiocarracedo** [microsoft/TypeScript#51571]
# Bug Report

### 🔎 Search Terms

type inference
type predicate
argument is type

### 🕗 Version & Regression Information

All versions available on the playground

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/es/play?ts=4.8.4&ssl=30&ssc=2&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgMoAs4AcUG8BQyyYAnjgFzIDkAzgI4CucUEVyAPtRADbfBY1W+AL758oSLEQoAwsCgJuKCAA9IIACY00mHMgJFSFLr36CqhZFDgbgDGpRAMAtgCNoRZCLETo8JMgAoqYCymoQmtoY2HiWRhCUVDx8oRZE1rb2ji7uUJYZdjQATNlu0N5i+DAMIAhgwAD2IMjANHIKSgAUNLoJOjEAlJQ9MS3a7Yqx6RBgDFDNIzgAdPHIALwbJinmyABku8gAhJ1UBfZFbKDIixADFdW19U3IzBBw3b2UE0pEnMHbt1KuX0lmAMGQnVa3wgH0GA30REsRAA9Mjrr1aMQyCgeg0GNwNMh3C9kAh5JMkVYZnMFr0lmdtAAqdExek2QrIZkAWTgYHQSwACgBJSyiSyolk4TGrVpBEKCfLU+aSiBszJMlVqwpFTnIHl8wUi4RAA)

### 💻 Code

```
interface Shape {
  type: 'square' | 'ellipse'
}

interface Circle extends Shape {
  type: 'ellipse'
  radius: number   
}

interface Ellipse extends Shape {
  type: 'ellipse'
  radius: number
  radius2: number
}

function isCircle(shape: Shape): shape is Circle {
  return shape.type === 'ellipse' && !('radius2' in shape)
}

function area(shape: Circle  | Ellipse): number {
  if (isCircle(shape)) {  
    // shape's type should be a Circle but is Circle | Ellipse
    return shape.radius * shape.radius * Math.PI
  }

  return shape.radius * shape.radius2 * Math.PI
}
```

### 🙁 Actual behavior

the type guard `isCircle` that returns `shape is Circle` returns Circle | Ellipse
(Using the same code inside `isCircle` in the area function as type guard works

```
function area2(shape: Circle | Ellipse): number {
  if (shape.type === 'ellipse' && !('radius2' in shape)) {      
    return shape.radius * shape.radius * Math.PI
  }

  if (shape.type === 'ellipse' && ('radius2' in shape)) {      
    return shape.radius * shape.radius2 * Math.PI
  }
  return 0
}
```

### 🙂 Expected behavior

the type guard `isCircle` should return the type is Circle if the shape argument meets the condition and returns true

**Comment by MartinJohns** [comment]
Every `Ellipse` is also a `Circe`, because the types are structurally compatible. So when you say "this is not a `Circle`", it also means it's not an `Ellipse`.

**Comment by sergiocarracedo** [comment]
Thanks for the answers and good to know, but in my opinion, it is confusing as the type predicate doesn't do the same as the same type guard but outside of the type predicate function. I mean
```
if (isCircle(shape)) {  // doesn't narrows the type, still being Circle | Ellipse
}
....
 if (shape.type === 'ellipse' && !('radius2' in shape)) {   // Do the time narrowing to Circle   

}
```

**Comment by fatcerberus** [comment]
In general whenever you have a union that looks like `Supertype | Subtype` you’re going to have a bad time.  Either type guards stop working properly (as here) or else you get the subtype removed from the union via subtype reduction, as in #51512.

`"radius2" in shape` works as a guard because then the compiler *knows* the value must be an `Ellipse` and can eliminate types accordingly (and also knows that this check failing doesn’t necessarily mean it’s *not* still a valid `Circle`).  The type predicate doesn’t work because unlike the property check which is type-agnostic, it’s specifically making a statement about the type `Circle` as a whole - `isCircle` is *not a valid implementation* because it returns `false` for an `Ellipse`, which contradicts its return type.

Of course, the real problem is actually at a higher level in the system.  All this unsoundness happens ultimately because of the way the types are written - in reality not all `Ellipse`s are `Circle`s, but you’re implicitly telling the type system this is true via structural typing.  `Ellipse` should not be assignable to `Circle`, so if you can fix that the issue here goes away.

**Comment by sergiocarracedo** [comment]
Thanks so much for the detailed answer
