### ISSUE TITLE
Narrowing fails with union of functions 

### ISSUE THREAD

**Issue by ElianCordoba** [microsoft/TypeScript#51639]
# Bug Report

### 🔎 Search Terms

function union, function union, multiple signatures

### 🕗 Version & Regression Information

- This is the behavior in every version I tried. It's not fixed in nightly

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.0-dev.20221124&ssl=11&ssc=2&pln=1&pc=1#code/C4TwDgpgBAyglgWzAGwgMQHZQLxQBTAQAewAXFAM7ABOcGA5gJQ4B8lNd9UAUKJFAHU4wABYBBavQqYc+QiXJVaDADRQAdJoD2YYHC0YKijgwDaAXWbY2eK2yWdu3OoWoAzAIYBjaJgCyHmCQ1FAA3txQUKYA1hAgxsr05uTwSKgyAD6CwuKS0hgA3NwAvk5eBlRQCIHB5P41ECG44ZFuWlrkBMTAdlAA5H1q3AD0w5HjUAB601AAotTUWtRq8sBQcBRQHhggahQiWgCuyAAmUABG0A4MJUA)

### 💻 Code

```ts
type SimpleFn = (text: string) => string 
type WithArgsFn = (text: string, ...options: string[]) => () => string

interface FnMapper {
  [key: string]: SimpleFn | WithArgsFn;
}

const mapper: FnMapper = {
  foo: (text) => '', 
//      ^^^ Error, text is any, should be string
}
```

### 🙁 Actual behavior

Parameter `text` implicitly has an `any` type.

### 🙂 Expected behavior

No error plus `text` should be of type string

**Comment by Andarist** [comment]
I can't be sure right now if the root issue is the same but this issue feels related: https://github.com/microsoft/TypeScript/issues/48663

**Comment by ahejlsberg** [comment]
We only infer contextual parameter types from a union of contextual function types when the contextual function types have identical parameter lists, so this is effectively a design limitation. We could possibly do better by inferring the widest possible parameter types in such situations.

**Comment by RyanCavanaugh** [comment]
It's very very rarely useful to contextually type by a union of functions -- the only cases where it really helps are basically places where you could have used the subtype instead, as is the case here (using `WithArgsFn` instead).

**Comment by fatcerberus** [comment]
@RyanCavanaugh For the record, manual subtype reduction isn't possible here because one has a return type of `() => string` while the other just `string`.  **BUT** this actually highlights an issue with the code as written: the signatures overlap.  `WithArgsFn` can legally be called without any `options`, in which case the union with `SimpleFn` suggests it's intended to return a `string`.  But if a given caller is only passing `text` there's no way for the compiler to tell the two signatures apart.

**Comment by Andarist** [comment]
TS can't pick one of the union members here for any given key. This is the same "problem" as this one:
```ts
type Valish = (value: string) => boolean;
type CurryValish = (...args: number[]) => Valish;

const fn1: Valish | CurryValish = (value) => true; // implicit anys
const fn2: Valish | CurryValish = (curry) => (value) => true; // implicit anys
```

And it stems from the fact that you can't really call a union of functions like this. How would you discriminate between members?

```ts
type Valish = (value: string) => boolean;
type CurryValish = (...args: number[]) => Valish;

declare const fn: Valish | CurryValish

fn() // const fn: (arg0: never, ...args: number[]) => boolean | Valish
```

As long as your arguments are different (and you have `string` and `number` at the first positions here) that will reduce to `never` (the parameters are intersected). For example, this one works OK since both functions use `number` at the first position:
```ts
type Valish = (value: number) => boolean;
type CurryValish = (...args: number[]) => Valish;

declare const fn: Valish | CurryValish

fn(10) // ok
```

This wouldn't help you with those contextual parameter types though, as per https://github.com/microsoft/TypeScript/issues/51639#issuecomment-1328054602
