### ISSUE TITLE
setter does not accept designated type

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript#51676]
# Bug Report

setter does not accept designated type

### 🔎 Search Terms

setter

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about class

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.0-dev.20221128#code/MYGwhgzhAEDCA8AVAfNA3gKGt6BzApgC7QAeAFAJQBc0EhATgJYB2u609RArvc9AOT9oAXyw4IRUmQBuYEDTpNW0AD7REFdKNHAA9szrRg0ALzRm+AO5x4ilrgDaAXWSUMwAHQlT0Z9Ei0DPbOGEA)

### 💻 Code

```ts
class C<T> {
    get x(): string { return '' }
    set x(val: string | T) {}
}
const c = new C<string[]>()
c.x = [] as string[]
```

### 🙁 Actual behavior

```
Type 'string[]' is not assignable to type 'string | T'.
  Type 'string[]' is not assignable to type 'T'.
    'T' could be instantiated with an arbitrary type which could be unrelated to 'string[]'.(2322)
```

### 🙂 Expected behavior

No error

**Comment by fatcerberus** [comment]
This is definitely a bug.  "`T` could be instantiated with..." errors are only supposed to happen for *uninstantiated* generics (i.e. inside the implementation of the generic), it's essentially a "T could be any number of types here and not all of them will allow this assignment" error.  That should never happen for an already-instantiated generic because `T` is already bound to a concrete type by then (in this case `string[]`).

**Comment by RyanCavanaugh** [comment]
Seems to be specific to the case where the getter doesn't reference the type parameter

**Comment by rotu** [comment]
Fixed? The playground example passes in version 5.3.2.
