### ISSUE TITLE
Trange function return type

### ISSUE THREAD

**Issue by ruojianll** [microsoft/TypeScript#51727]
# Bug Report

### 🔎 Search Terms

Function type

### 🕗 Version & Regression Information

v4.9.3

### ⏯ Playground Link
https://www.typescriptlang.org/play?#code/FAYw9gdgzgLgBALzgXjgCgIYC46wE4CWEA5gDRwBGOEArgLYUCmeAlCgHxwCMATAMxwMUOOGgxgAG0bwAjikRoA5IvJc2AenVw5BYbz7kKNeAXhQAFmBoSAJpUZxaDZsCA
### 💻 Code
```

const a = 123
let b = a // correct!

const z = (a: string, b: number) => 123 as const
let q = z('', 1) // wrong! q is 123, but it should be number

```
### 🙁 Actual behavior

q is 123

### 🙂 Expected behavior

q is number

**Comment by MartinJohns** [comment]
This is working as intended. Because you did not provide a type annotation for your functions return type, the return type is inferred based on the value you return. By returning `123 as const` you say you want to return `123`, and do not widen the type to `number`. So the return type is inferred to be `123`.

**Comment by fatcerberus** [comment]
No, because TypeScript has literal types.  It's the same as if you did

```ts
let q: 123 = 123;
q = 321;  // error, 321 is not assignable to 123
```

By returning `123 as const`, you're telling the compiler to preserve the literal type of `123` instead of widening it to `number`.
