### ISSUE TITLE
window narrows to never when assuming ResizeObserver is not contained

### ISSUE THREAD

**Issue by fabb** [microsoft/TypeScript#51780]
# Bug Report

### 🔎 Search Terms

resizeobserver, narrow

### 🕗 Version & Regression Information

- This changed between versions 4.8.4 and 4.9.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.3#code/GYVwdgxgLglg9mABAZzgWwKZQBYzAcwAoBKRAbwChFrEZhCByAJQ2RgC8MB5AI2QwBOAN0ENaSAO54AJnAmlKNJYgFYQAsFRoBfRBgA2-cluWIA9GcRQAngAdWEATFtREAPgC8AFgB0ADitcMABrZECAQ1cAAykwWQko2jCosAwRAUTsQQwAGkQeDAhwkCMYVxw8UIjo2PjE8P0JcOswiAQocLww8MQoljZOXn5hQXq4wOzgOFUJ3oN+RKKjIqRU9MRscNt7TVNqWrkfcOlpAFERMCgAGRhkKAxUgUZVAYwGPJJEDzdybWITRDaChAoA)

### 💻 Code

```ts
function something() {
    if('ResizeObserver' in window) {
        return
    } else {
        // typescript >=4.8 thinks that `window` is `never` here, because it thinks that `window` always contains a `ResizeObserver` and therefore the `else` case can never happen
        window.addEventListener('resize', () => {})
    }
}
```

### 🙁 Actual behavior

Compilation error:
```
Property 'addEventListener' does not exist on type 'never'.
```

### 🙂 Expected behavior

Should compile since older browsers might not support `ResizeObserver` yet. Maybe even dependent on `lib`.

**Comment by MartinJohns** [comment]
The behaviour of TypeScript is correct here, because, according to the type definition, `window` **always** has a `ResizeObserver`. So when you verified that it does not has this property, it means it can't be a `window` anymore, so it narrows to `never`.

One option would be to make the property optional, in which case an issue in the [TypeScript-DOM-lib-generator](https://github.com/microsoft/TypeScript-DOM-lib-generator) repository would be appropiate. But it could be that this is intentional, blindly assuming that every DOM runtime has this property already.

In your code you can simply workaround this by not using the `in` operator, but instead check if `window.ResizeObserver` is `undefined`.
