### ISSUE TITLE
Standardize on use or non-use of indefinite articles in error messages

### ISSUE THREAD

**Issue by RyanCavanaugh** [microsoft/TypeScript#5179]
Error messages are inconsistent about "A foo may not baz" vs "Foos may not baz":
- "A required parameter cannot follow an optional parameter."
- "A class member cannot be declared optional."
- "A tuple type element list cannot be empty."

vs
- "Computed property names are not allowed in enums."
- "Classes can only extend a single class."
- "Generators are not allowed in an ambient context."

Let's pick one and stick to it as much as possible.

**Comment by RyanCavanaugh** [comment]
My :bike: :house_with_garden: vote is for the latter form.

**Comment by DanielRosenwasser** [comment]
I'd be up to taking an hour and going one by one through the messages if I wasn't doing it alone.

**Comment by RyanCavanaugh** [comment]
Let's have an error message session during the doc-a-thon :balloon: :tada:

**Comment by danquirk** [comment]
I believe C#/VB already have a style guide that specifies the preference in this case?

**Comment by RyanCavanaugh** [comment]
We should also standardize on "may" / "may not" vs "can" / "cannot"

**Comment by ahejlsberg** [comment]
Regarding singular vs. plural, I prefer singular because I find it less ambiguous. For example, "A class can only extend a single class" is pretty clear, but "Classes can only extend a single class" leaves me wondering if *all* classes can only extend the *same* single class.

Regarding "can" vs. "may", we clearly have a preference for "can" and "cannot" in the existing error messages. There are for more of those than "may" and "may not". So, I would just stick with "can" and "cannot".

**Comment by RyanCavanaugh** [comment]
~ no one cares ~
