### ISSUE TITLE
Copyright comments are not preserved when generating d.ts files

### ISSUE THREAD

**Issue by dpogue** [Microsoft/TypeScript#5183]
My TypeScript files all start with a pinned copyright line:
```typescript
/*! Copyright 2015 MyCompany Inc. */
```

This is preserved in the compiled JS output, but it not preserved in the generated d.ts files.

We have company-wide requirements that every file must include a copyright header, and we're unable to publish our module for use by other teams due to these constraints.

Building with the `removeComments: false` option should retain pinned comments in d.ts files.

**Comment by delta-nry** [comment]
I am part of a group of students from the University of British Columbia looking to contribute to a bug fix. Is this bug still available for us to contribute to?

**Comment by DanielRosenwasser** [comment]
@delta-nry, this is scheduled for the 2.0 milestone right now, so if you'd like to see this fixed sooner, I think you could take this on. @yuit @mhegazy are you okay with that?

**Comment by yuit** [comment]
@delta-nry go for it! Thanks for your interest :cookie:

**Comment by MartyIX** [comment]
@dpogue I was looking into the issue and if you use

`/** Copyright 2015 MyCompany Inc. */`

instead of

`/*! Copyright 2015 MyCompany Inc. */`

your comment will be preserved.

**Comment by MartyIX** [comment]
@mhegazy I found out that the issue is caused by the following functions:

https://github.com/Microsoft/TypeScript/blob/master/src/compiler/declarationEmitter.ts#L56
https://github.com/Microsoft/TypeScript/blob/master/src/compiler/declarationEmitter.ts#L322
https://github.com/Microsoft/TypeScript/blob/master/src/compiler/utilities.ts#L424

The comment of the OP - `/*! Copyright 2015 MyCompany Inc. */` - is not taken into account because only JsDoc comments (i.e. `/** */`) are being considered.

I can think of several ways how to fix the issue but I'm not sure what is your idea of the bugfix. What do you suggest here?

Thank you

**Comment by dpogue** [comment]
Yes, JSDoc-style comments are preserved, but then the copyright appears as documentation for the module, which is not the intended result.

**Comment by yuit** [comment]
@MartyIX one suggestion of this fix will be using `emitDetachedComment` in the [emitter.ts](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/emitter.ts#L8089) and call the function from `emitSourceFile` in [declarationEmitter.ts] (https://github.com/Microsoft/TypeScript/blob/master/src/compiler/declarationEmitter.ts#L468). The `emitDetachedComment` already does most of the work in getting leading comment and filter only for detachedComment and emit the comments out.

Additional clarification on terminology, `detachedComment` is a comment at the top of the file, function body that separate from the next statement by space. The compiler, then, considers the comment "detached" from the next statement. 

Note: this may require some refactoring

**Comment by MartyIX** [comment]
Thanks @yuit. It sounds good. I'll try it.

**Comment by mhegazy** [comment]
thanks  @MartyIX !
