### ISSUE TITLE
Mirror Cursor for JSX

### ISSUE THREAD

**Issue by octref** [microsoft/TypeScript#51832]
microsoft/vscode#47069 implements this for HTML.

We should look for a way to support this for JSX/TSX.

**Comment by mjbvz** [comment]
Here's a proposal for the TS Server protocol to implement this in VS Code. 


## TS Server protocol

Add a new request `jsxLinkedTag` that takes a file location (path + position) and returns an array of text spans for all occurrences of that tag

```ts
interface JsLinkedTagRequest extends FileLocationRequest {
	command: 'jsxLinkedTag';
	arguments: FileLocationRequestArgs;
}

interface JsLinkedTagResponse extends Response {
	readonly body: TextSpan[];
}
```

A few details on the expected behavior:

- The returned ranges should include both the tag at the current cursor position and it's matching tag.
- The ranges should include the full range of the tag name (but not attributes and not `<` or `/`).
- If there is no matching pair, we return an empty list.
- Self-closing tags always return an empty list.

This same request should also let us support making normal rename (F2) rename matched tags instead of 

## Examples
In these examples, `|` is the cursor position:

---

```tsx
const jsx = (
    <div|>
    </div>
);
```

Same for cursor being anywhere on `div`

- startLine: 1, startCharacter: 5, endLine: 1, endCharacter: 8
- startLine: 2, startCharacter: 6, endLine: 2, endCharacter: 9

---

```tsx
const jsx = (
    <div| style={{ color: 'red' }}>
        <p>
            <img />
        </p>
    </div>
);
```

- startLine: 1, startCharacter: 5, endLine: 1, endCharacter: 8
- startLine: 5, startCharacter: 6, endLine: 5, endCharacter: 9

---

```tsx
const jsx = (
    <div>
        <p>
            <img| />
        </p>
    </div>
);
```

- Empty, we're on a self closing tag

---

Namespace

```tsx
const jsx = (
    <someNamespa|ce.Thing>
    </someNamespace.Thing>
);
```

This applies for the cursor being anywhere in the tag name

- startLine: 1, startCharacter: 5, endLine: 1, endCharacter: 25
- startLine: 2, startCharacter: 6, endLine: 2, endCharacter: 26


---

Invalid tags 1

```tsx
const jsx = (
    <div|>
        <div>
    </div>
);
```

Match what HTML does:

- Empty

---

Invalid tags 2

```tsx
const jsx = (
    <div>
        <div|>
    </div>
);
```

Match what HTML does:

- startLine: 2, startCharacter: 9, endLine: 2, endCharacter: 12
- startLine: 3, startCharacter: 6, endLine: 3, endCharacter: 9


---

Fragment shorthand

```tsx
const jsx = (
    <|>
        <img />
    </>
);
```

Return empty ranges (need to confirm VS Code supports this):

- startLine: 1, startCharacter: 5, endLine: 1, endCharacter: 5
- startLine: 3, startCharacter: 6, endLine: 3, endCharacter: 6


---

Only exact matches of the entire name are supported

```tsx
const A = thing;
const B = thing;

const jsx = (
    <A>
    </B>
);
```

- empty, tags don't match

**Comment by ThaJay** [comment]
How is this not the default 3 years later?

**Comment by mjbvz** [comment]
@iisaduan I've updated the proposed protocol to more closely match VS Code / LSP. Here's the LSP spec for reference: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_linkedEditingRange

This PR against VS Code also stubs out this feature using the proposed API: https://github.com/microsoft/vscode/pull/176279 Let me know once you have something on the TS side and I will update the VS Code PR to match the actual protocol

**Comment by Cristy94** [comment]
I see this issue is closed, but it still doesn't work for me. Is JSX linked editing supported?

**Comment by andresribeiro** [comment]
@Cristy94 be sure that `"editor.linkedEditing": true` is set on `settings.json`

**Comment by Cristy94** [comment]
> @Cristy94 be sure that `"editor.linkedEditing": true` is set on `settings.json`. it's disabled by default

Am I missing anything? Is there a shortcut for it? I didn't find any documentation for this feature.
If I just edit the opening tag of a `<div></div>` element, the end tag is not updated.
If I use <kbd>CTRL+F2</kbd>, all occurrences of `"div"` in that document are replaced.

**Comment by Cristy94** [comment]
It seems to work for HTML (as expected, automatically edit, no keyboard shortcut needed). But for .jsx and .tsx it doesn't work or highlight the tags. 

<img width="283" alt="image" src="https://github.com/microsoft/TypeScript/assets/1384885/b14e2a5a-947f-481a-a9cf-13974ff3e345">

**Comment by Cristy94** [comment]
Found the issue, it doesn't work in TypeScript 5.0, and my editor was using the wrong version:

<img width="646" alt="image" src="https://github.com/microsoft/TypeScript/assets/1384885/5d5bd120-9fab-49f7-b7b4-41f64ca4abc5">
