### ISSUE TITLE
`{@link Foo.length}` unexpectedly resolves to Function.length

### ISSUE THREAD

**Issue by phlegmaticprogrammer** [microsoft/TypeScript#51938]
# Bug Report

### 🔎 Search Terms
tsdoc, vscode, link, declaration reference

### 🕗 Version & Regression Information

Version: 1.74.1 (Universal)
Commit: 1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a
Date: 2022-12-14T10:33:40.793Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: Yes

### 💻 Code

This code lives in a .mts module:

```ts
/** A coordinate is a number between 0 and {@link Line.length}. */
export type Coordinate = number

export class Line {
    positions : Coordinate[]
    length : number
    public constructor() {
        this.positions = [];
        this.length = 0;
    }
}
```

### 🙁 Actual behavior

When hoovering over the `Coordinate` type in the `Line` declaration in VS Code, the help
for `Coordinate` shows `Line.length` instead of `length`, and instead of pointing to member `length` in class `Line` it points to somewhere in the Typescript library.

<img width="630" alt="VSCodeBug" src="https://user-images.githubusercontent.com/317171/208266527-7ab6c8a3-11e6-4b3d-aff1-8886c6f80c8e.png">

### 🙂 Expected behavior

It should say `length` instead of `Line.length` in the help popup, and it should be a link to the member `length` of class `Line`.

**Comment by sandersn** [comment]
The link is to Function.length in the standard library. That's definitely wrong [1], but I don't understand why quickinfo should just say `length` when the link text is `Line.length`.

In fact, using Ctrl+click to goto-def usefully distinguishes between `Line` and `length`, although `length` still goes to `Function.length` in the standard lib instead of `Line.length`.

[1] Although not technically as wrong as you might expect, because Line *is* a function and so `Line.length` would resolve to `Function.length` *if* `class Line` had no property `length`.

**Comment by sandersn** [comment]
The problem is that `Line.length` is interpreted as the typescript qualified name `Line.length`, a *static* property of Line. Since Line is a Function, it does have a static property `length` and doesn't reach the fallback code path which resolves `Line.length` as if it were `Line#length` -- that is, looking for instance properties.

The fix is probably to always check `Line#length` first and use that if it resolves. statics aren't that common and most people aren't rigorous with usage of `Class#property`, or don't use it at all.

**Comment by sandersn** [comment]
Here's a smaller, more obvious repro:

```ts
class C {
  static a = 1
  a = 1
}
/** {@link C.a <-- links to static, not instance} */
```

Having slept on it, the three options I can think of are:

1. Do nothing to Typescript. Change the code to `Line#length`.
2. Make Typescript resolve `Line.length` to the instance property whenever there's a conflict. No way to link to the static in that case.
3. Make Typescript resolve `Line.length` to the instance property whenever there's a conflict and the static property is in a base class.
3b. same, but only with the static property is in a base class in the standard lib.

(2) is less expressive since you can't disambiguate between conflicting names, which is itself confusing. (3) is complex to implement and even more confusing. I'm going with (1) since this is only a problem when there's a static/instance name conflict and only at its most confusing for Function properties like `length/name/caller`. 

I'm going to document the distinction between `.` and `#` syntax on the JSDoc handbook page.
