### ISSUE TITLE
`Node *` and `Node lts/*` CI jobs are duplicates

### ISSUE THREAD

**Issue by ddzz** [microsoft/TypeScript#51943]
# Bug Report

In the GitHub Actions CI matrix, the Node versions `*` and `lts/*` both resolve to the same version (currently `18.12.1`), making these two jobs duplicates.

### 🔎 Search Terms

CI, continuous integration, Node version

### 🕗 Version & Regression Information

N/A

### ⏯ Playground Link

https://github.com/microsoft/TypeScript/actions/runs/3721283259/jobs/6311330943#step:3:9

https://github.com/microsoft/TypeScript/actions/runs/3721283259/jobs/6311330986#step:3:10

### 💻 Code

https://github.com/microsoft/TypeScript/blob/main/.github/workflows/ci.yml#L21-L22

### 🙁 Actual behavior

The Node version in the two CI jobs are the same, making them duplicates.

### 🙂 Expected behavior

The Node version `"*"` in the matrix should be changed to `"19.x"` so that tests run using the latest Node version.

**Comment by jakebailey** [comment]
This has to be a bug in `setup-node`, as their docs say that if `check-latest` is enabled, it will pull the latest dist from https://nodejs.org/dist/index.json which says 19.3.0.

Honestly, I'm not super convinced that we should keep using these special version specs. This issue is one problem, but now we're technically supposed to be testing 14/16/18/19 but our workflow doesn't actually hit 14 anymore, which is a problem.

**Comment by jakebailey** [comment]
Ah, so "*" means "whatever is newest on the runner", versus "current" or "latest" which explicitly pull the newest. I can change us to doing that, but I am a little unhappy with the fact that we don't quite get the versions right already.

**Comment by fatcerberus** [comment]
It kind of makes sense though - I would generally interpret `*` in this context to mean either "try all versions" or else "use whatever, I don't care"
