### ISSUE TITLE
[Spec] Duplicate ambient external module name

### ISSUE THREAD

**Issue by mhegazy** [microsoft/TypeScript#52]
``` TypeScript
declare module "fs" {
    var x: string;
}
declare module "fs" {
    var y: number;
}
```

Expected: 
!!! Duplicate identifier ''fs''.
!!! Ambient external module declaration cannot be reopened.
Actual: no error

**Comment by spion** [comment]
It seems like this doesn't work if the module is exported by assignment? 

```typescript
declare module "m" {
  function inner(s: string) { }
  module inner { export interface Test {t: string;} }
  export = inner
}

declare module "m" {
  module inner { export interface Other { t: number; } }
}
```

**Comment by RyanCavanaugh** [comment]
@spion The name `inner` is not "shared" between declarations here -- when there's an `export =`, all other declarations inside that module declaration are considered to not be visible at all

**Comment by spion** [comment]
@RyanCavanaugh I see. The original problem is express.d.ts

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/express/express.d.ts

Here, express exposes a namespace `Express` to let us extend `Request`. Unfortunately those extensions cannot contain types imported from ambient external modules, which means they're of limited use. However, since express-the-module is also a function, the only way to declare the module is to use declaration merging then write export = module at the end.

I'll open a separate issue.
