### ISSUE TITLE
ES2022 Class Decorators not working when Class has self-static member

### ISSUE THREAD

**Issue by vladimir-siv** [microsoft/TypeScript#52004]
# Bug Report

Class decorators are not working properly when the class has a static field of the same type and is instantiating it statically. Seems like this only happens when targeting ES2022.

### 🔎 Search Terms

Various combinations of the below search strings. Haven't been able to find anything useful.
Been searching for several days now, these are just the most recent ones I could remember:

- Typescript class decorator with static property not working
- Typescript decorators: TypeError: undefined is not a constructor
- Typescript decorators not working (with es2022)
- Typescript decorator es2022
- Angular custom decorators not working
- Angular custom decorators with aot

### 🕗 Version & Regression Information

Regressed when `tsconfig.compilerOptions.target` is ES2022. Other ES versions that I tried seem to be working as expected.
Tried Nightly version in the playground, could still repro it (after I changed target to ES2022 in TSConfig).

### ⏯ Playground Link

[Bug repro in Playground](https://www.typescriptlang.org/play?target=9&jsx=0&module=7&ts=5.0.0-dev.20221223#code/GYVwdgxgLglg9mABAWQKYGd0EMDmqAU0cATgFyIBi408YAlAFADeDAkBAunADaoB03ODnwADAEqocMdFGIwwOcgCIAJEyLE+YLAFtUAXyUi6Abgb6GDAAJpMuVAwjcsmRAAV5OW9jzM2ABxAAI24YCEQZLFhwgBFUYCwQbihyDwVve0QAXkQwVAB3d08MvHxTRAB6CsQAbQBBAF0A4NDwjjAZYhANfECQsMRiVCwAEwRuAE9EADUsbhBUck7PbMQlNJwlOkQmRAsLBiqi9IwffjiEpKhVvMKNkoJyo5qAISb2rl4BIXx70-s+BdEsk+LN5qhTJYjgBlfJYfz+FbySJgWBRWiIYDEOA6WqNRBQOC1N6DVBgEaoYjoAkAC2kiA4FMQ+RIAGtPHxDtVoahUDpqaFWagGZxZN1CcREPSwHBrhTgPJUCNmahuNxmXTeFKOlAsKiYOiFIgsBFddFEHodEFKcyYFA6Ug7dS4PkkE4XOhOUA)
You can try setting e.g. ES2021, and the code works, but not on ES2022.

### 💻 Code

`src\index.ts`:
```ts
function Message(ctor: Function)
{
    console.log(`Registring: "${ctor.name}"`);
}

@Message
class PingMessage
{
    public static Default: PingMessage = new PingMessage(); // [A]
    public constructor(public readonly Value: string = "Ping") { }
}

// PingMessage.Default = new PingMessage(); // [B]
console.log(PingMessage.Default.Value);

// Swapping instantiation from [A] to [B] renders this code working.
// Seems like constructor is not defined well while instantiating a static member within its own class.
```

`package.json`:
```json
{
  "name": "decorator-test",
  "version": "1.0.0",
  "description": "Test App",
  "scripts": {
    "start": "(if exist dist rd /S /Q dist) >nul 2>nul && tsc && node ./dist/index.js"
  },
  "dependencies": {
    "tslib": "^2.4.1"
  },
  "devDependencies": {
    "typescript": "^4.9.4"
  }
}
```

`tsconfig.json`:
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist",
    "target": "ES2022",  // <----- !!!
    "module": "ES2022",
    "strict": true,
    "experimentalDecorators": true,
    "useDefineForClassFields": false,
    "lib": [
      "ES2022",
      "dom"
    ]
  },
  "files": [
    "src/index.ts"
  ]
}
```

### 🙁 Actual behavior

~\dist\index.js:13
    static { this.Default = new PingMessage_1(); } // [A]
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&nbsp;^

TypeError: undefined is not a constructor
&emsp;at Function.<static_initializer> (\~\dist\index.js:13:29)
&emsp;at Object.<anonymous> (\~\dist\index.js:12:19)
&emsp;at Module._compile (node:internal/modules/cjs/loader:1155:14)
&emsp;at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
&emsp;at Module.load (node:internal/modules/cjs/loader:1033:32)
&emsp;at Function.Module._load (node:internal/modules/cjs/loader:868:12)
&emsp;at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
&emsp;at node:internal/main/run_main_module:22:47

### 🙂 Expected behavior

Console.logs:

```
Registring: "PingMessage"
Ping
```

**Comment by rbuckton** [comment]
The binding for `PingMessage_1` is initialized too late. I believe I've fixed this for Stage 3 decorators, but not for legacy decorators.

**Comment by rbuckton** [comment]
When targeting ES2022+, the emit for the example above is currently:

```js
let PingMessage = PingMessage_1 = class PingMessage {
    static { this.Default = new PingMessage_1(); } // [A]
    constructor(Value = "Ping") {
        this.Value = Value;
    }
};
PingMessage = PingMessage_1 = __decorate([
    Message,
    __metadata("design:paramtypes", [String])
], PingMessage);
```

However, `PingMessage_1` isn't yet initialized. The emit should probably be this instead:

```js
let PingMessage = PingMessage_1 = class PingMessage {
    static { PingMessage_1 = this; }
    static { this.Default = new PingMessage_1(); } // [A]
    constructor(Value = "Ping") {
        this.Value = Value;
    }
};
PingMessage = PingMessage_1 = __decorate([
    Message,
    __metadata("design:paramtypes", [String])
], PingMessage);
```

Please note that class decorators and static initializers that reference `this` or the class constructor don't play well together under `--experimentalDecorators` because static initializers run before decorators are applied. That ordering can be problematic when a class decorator performs constructor replacement as the initializer will not use the replacement constructor. In the Stage 3 Decorators proposal, decorators are applied _before_ static initializers instead.

As a workaround, you could lazily initialize the value so that the constructor is run later:

```ts
@Message
class PingMessage
{
        private static _Default: PingMessage | undefined;
	public static get Default() { return PingMessage._Default ??= new PingMessage(); }
	public constructor(public readonly Value: string = "Ping") { }
}
```

**Comment by vladimir-siv** [comment]
No worries, feel free to close the issue, there are several ways to work around this, I made a similar workaround, just wanted to report this issue.

**Comment by markwhitfeld** [comment]
Came across this issue recently. I believe it is in fact a TS bug that needs to be resolved.
The issue is caused by the aliased class name, which is not initialised at the time of the static initialisers being called, where the class itself is, in fact, available from within the static initialisers in ES2022.

Given the following TS Code:
```TS
function createFromClass(caller: string, classRef: unknown) {
    console.log(`${caller}:`, classRef);
    return 'foo';
}

function SomeDecorator(): ClassDecorator {
    return () => { };
}

class UndecoratedClass {
    static test = createFromClass('UndecoratedClass', UndecoratedClass);
}

@SomeDecorator()
class DecoratedClass {
    static test = createFromClass('DecoratedClass', DecoratedClass);
}
```
If this is run targeting `ES2021` or earlier then the class is available to the static initialisers for both `UndecoratedClass` and `DecoratedClass`. But, if we target `ES2022` or later then the `DecoratedClass` class receives `undefined` as its reference to itself from within its static initialisers.
This is a result of the intermediary `..._1` class reference in the generated code not being populated yet:
```js
let DecoratedClass = DecoratedClass_1 = class DecoratedClass {
    static test = createFromClass('DecoratedClass', DecoratedClass_1);
};
DecoratedClass = DecoratedClass_1 = __decorate([ SomeDecorator() ], DecoratedClass);
```
When there is no decorator, then the intermediary reference is not created and it all works as expected.

Here is a playground of the above example:
https://www.typescriptlang.org/play?target=9#code/GYVwdgxgLglg9mABBATgUwIZTQMRXAWwGEAbDAZ3IAoIMSS0UAuRcqFGMAcwBpkzKAJTTAW4ANZg4AdzABKRAG8AUIjXIE5OAwB0JOFyoADACSLa9RgF8mRvhAHlhwOQG5V69FBAokAcmA4OD93K2VlUEhYBEQAZUI0ABE0CDgULDSqORZSCnJk1PSoNKUPNS8fJCzEAF4APiVEK1DwhzzEAFUwABMUtKw0btzKUvVWKCwYCERsNlrkdAG8QmHqPy7ewoGhxz8+Db6iwdW3ZTDlAAF4giTDjJQs5TaRgv7sHfaVMbZJ6dmoeaoTDYZbERxUPyvI4fSh7RBQ7YnUJAA

## Proposed solution

Not sure all the reasons for the intermediary class reference, but potentially an alternative would be for TS to generate the following JS code when a decorator is used:
```js
let DecoratedClass = (() => {
    class DecoratedClass {
        static {             
            this.test = createFromClass('DecoratedClass', DecoratedClass); 
        }
    };
    return __decorate([ SomeDecorator() ], DecoratedClass);
})()
```
The code above effectively uses a shadowed variable name within the IIFE as the intermediary class reference to the same effect, but without the reference initialisation timing issue.
This even allows for less of a need for modification of the decorated class code and the final code has fewer characters (ignoring whitespace).
@rbuckton What do you think of this proposed approach for legacy decorators?

**Comment by markwhitfeld** [comment]
I am seeing more and more Angular projects running into this issue.
@rbuckton is there any plan to address this issue soon?
Hopefully my proposed solution above could provide some ideas.

**Comment by rbuckton** [comment]
> Not sure all the reasons for the intermediary class reference, [...]

ECMAScript classes are "doubly bound", which means that the class name (i.e., `DecoratedClass`) is bound both outside the class and inside the class body, separately. This differs both from function declarations, which only bind the function name outside of the function, and function expressions, which only bind the function name inside of the function. The result of this behavior is that any reference to `DecoratedClass` _inside_ of the class body will always be the original class, even if a class decorator replaces the constructor:

```js
class A {
  static foo() { console.log(A.name); }
}

// replace A with B
A = class B extends A { }

// print the current name of A
console.log(A.name); // B

// indirectly print the name of A that the 'foo' method sees:
A.foo(); // A
```

> [...] but potentially an alternative would be for TS to generate the following JS code when a decorator is used:
> 
> ```js
> let DecoratedClass = (() => {
>     class DecoratedClass {
>         static {             
>             this.test = createFromClass('DecoratedClass', DecoratedClass); 
>         }
>     };
>     return __decorate([ SomeDecorator() ], DecoratedClass);
> })()
> ```
> 
> The code above effectively uses a shadowed variable name within the IIFE as the intermediary class reference to the same effect, but without the reference initialisation timing issue. This even allows for less of a need for modification of the decorated class code and the final code has fewer characters (ignoring whitespace). @rbuckton What do you think of this proposed approach for legacy decorators?

I'm not sure what you mean by "shadowed variable" in this context, but unfortunately this doesn't work per the reason I stated above.

> (EDIT: It could even be trimmed down to the following, but it really depends on the reason for the intermediary reference as to how far we simplify this.)
> 
> ```js
> let DecoratedClass = (() => 
>   __decorate([ SomeDecorator() ],
>     class DecoratedClass {
>       static {
>         this.test = createFromClass('DecoratedClass', DecoratedClass);
>       }
>     }
>   )
> )();
> ```

This also wouldn't work since `DecoratedClass` wouldn't be the replaced constructor.

The only change I could see us making would be to more closely emulate native decorators with regards to the timing of static initializer evaluation, such that where we previously ran static initializers _before_ decorators, we would run them _after_ decorators. However, I'm not certain whether there are customers that might be affected by such a major semantics change. I'm more likely to err on the side of caution and make it an error to reference the class name immediately within a static initializer (much like we do for a TDZ check for let/const).

I would still suggest using lazy initialization for these fields, as I mentioned [above](https://github.com/microsoft/TypeScript/issues/52004#issuecomment-1372689174).

**Comment by markwhitfeld** [comment]
@rbuckton I have spent some time trying to understand the problem, and I found your commit [here](https://github.com/microsoft/TypeScript/commit/1bb96555da2d6cfd0a0b5d7e6357ea50ce5c95d1) which resolved this [issue](https://github.com/microsoft/TypeScript/issues/5386) as well as the double binding problem.

I think I have found a solution that would cover these cases and would additionally allow code to function in the same way when targeting ES2022 as when we target ES2021 or earlier.

Given the following TS code:
```TS
@SomeDecorator()
class DecoratedClass {
    static test1 = doSomething('DecoratedClass', DecoratedClass);
    static test2 = DecoratedClass;
    static test3() { return DecoratedClass; }
}
```
and assuming that the `SomeDecorator` decorator did something dramatic to modify the constructor, like this:
```TS
function SomeDecorator() {
    return (target) => {
        return class ModifiedClass extends target {};
    };
}
```
---
If we compile with ES2021, we get:
```TS
let DecoratedClass = DecoratedClass_1 = class DecoratedClass {
    static test3() { return DecoratedClass_1; }
};
DecoratedClass.test1 = doSomething('DecoratedClass', DecoratedClass_1);
DecoratedClass.test2 = DecoratedClass_1;
DecoratedClass = DecoratedClass_1 = __decorate([
    SomeDecorator()
], DecoratedClass);
```
This results in the following observations:
1) `DecoratedClass.test1` has its initialiser called with `DecoratedClass` before the decorator ran
2) `DecoratedClass.test2` references the `DecoratedClass` from before the decorator
3) `DecoratedClass.test3`, when invoked would return `ModifiedClass`  (as returned by the decorator)
---
If we compile with ES2022, we get:
```TS
let DecoratedClass = DecoratedClass_1 = class DecoratedClass {
    static { this.test1 = doSomething('DecoratedClass', DecoratedClass_1); }
    static { this.test2 = DecoratedClass_1; }
    static test3() { return DecoratedClass_1; }
};
DecoratedClass = DecoratedClass_1 = __decorate([
    SomeDecorator()
], DecoratedClass);
```
This results in the following observations:
1) `DecoratedClass.test1` has its initialiser called with `undefined`
2) `DecoratedClass.test2` is `undefined`
3) `DecoratedClass.test3`, when invoked would return `ModifiedClass` (as returned by the decorator)

1 and 2 are breaking changes.
---
This would be fixed if the following code was generated when targeting ES2022:
```TS
let DecoratedClass = DecoratedClass_1 = class DecoratedClass {
    static { this.test = doSomething('DecoratedClass', this); }
    static { this.test1 = this; }
    static test2() { return DecoratedClass_1; }
};
DecoratedClass = DecoratedClass_1 = __decorate([
    SomeDecorator()
], DecoratedClass);
```
As you can see, references to `DecoratedClass_1` have been replaced with `this` for the `test1` and `test2` initialisers.
So, if I understand things correctly, references to the containing class from static property initialiser expressions could be replaced with `this`, but static function declarations would still use the aliased name (`DecoratedClass_1`) in order to bind to the decorated class.

Do you think that this is a viable solution?

PS. I know that native decorators would do things differently here, but the "Experimental Decorators" have a different historical behavior in this regard, so I think that the historical behavior should be maintained for the experimental decorators.

**Comment by markwhitfeld** [comment]
PS. Just an additional note that a static initialiser like this:
```TS
static test4 = accessLater(function foo() { return DecoratedClass });
```
would also still need to return the aliased class `DecoratedClass_1` and not `this` because the `foo` function has its own `this` that we would not want to be referencing.

**Comment by markwhitfeld** [comment]
Ok, I think I have got a solution that will work for all scenarios.
I reworked the playground to make the expectations clearer too: [See here](https://www.typescriptlang.org/play?target=9&ts=4.9.5#code/GYVwdgxgLglg9mABDMMoAoIEMA2OCmATgFyIDOUhKA5gDSIQ5ZlkBK+wpAYuNPGAEpEAbwBQiCQwRk4BAHQ441dAAMAkkhRoYuGGSL0yACzggcAE0QAjfIgDkAEmHY8RAL53iK+o2ZsOiABkgQxMLOzAcmBYALb4AgDc4pKE+FAghEi+4RxJbqKioJCwCIjmcABycFBGNOjAYNy8JYIikojJEqnpmYgNeQVFfKUAynBxACL4EHCEWFCz6AKkAMJhZFMzcwuEIp1SYDLyisp2ahVqACqIm7Pzs3aJ+90ZSOhQWITUaaRYYACey0Qf3+iAAvAA+Nr7dozQ6yfAKJToOy3bY0UJ+Yh2egfL5pKKxeJJdrtF69bJkRAAdTmAAc6fhLPgAB5QfBgcxUvHfKAifLtNwDURwo6Ik4osFSm7TJhUMDUUgAeSo1BQuEeSVEAAExpNpncdksRetECqYGrojg9u0KPMYBBEOyKABGcHIVAYOzmy0a+g+9U4J62j6wR3OqAAJndAatJMkdrDTvwFAAzEs2uSkLHcAlEAKE6GHcmKAAWd3lKo1OpDFqIDPCRBZs2qwP54OF+3hlNQACsMdbVoA-HII6WlsLRQikacALTzxAAQWA7N2mzl9oQhhMZksNhp9MZ5mx-sHuEJcSeU+OyJUdgjLrs5B3FmsthzOC8p4tgdHPZdI7RJeSTXuKt73j2kZPsYpivvuH5fi2P5Wn+FCRoBRJXtI04SneEbpgI0EvpYza0lgDJMohH6oVABEYcBIrYTeyh4T246Ec+sEkWkrwHuRR5UWeOA0ex9HEox8LMaoEEUL2RFcW+SG+p+3hKb+Ea9mJiRAA)

Trimmed TS example code:
```TS
console.log('=== Declaring: Original');

@SomeDecorator()
class Original {
    static test1 = init('Original', Original);
    static test2 = Original;
    static test3() { return Original; }
    static test4 = doNothing(function () { return Original });
    static test5 = Original?.test4();
}

console.log('--- After Declaration, should be Wrapped:', Original.name);
console.log(`'test1' should be Original:`, Original.test1?.name);
console.log(`'test2' should be Original:`, Original.test2?.name);
console.log(`'test3()' should return Wrapped:`, Original.test3()?.name);
console.log(`'test4()' should return Wrapped:`, Original.test4()?.name);
console.log(`'test5' should be Original:`, Original.test5?.name);
```
When [run using ES2021](https://www.typescriptlang.org/play?target=8&ts=4.9.5#code/GYVwdgxgLglg9mABDMMoAoIEMA2OCmATgFyIDOUhKA5gDSIQ5ZlkBK+wpAYuNPGAEpEAbwBQiCQwRk4BAHQ441dAAMAkkhRoYuGGSL0yACzggcAE0QAjfIgDkAEmHY8RAL53iK+o2ZsOiABkgQxMLOzAcmBYALb4AgDc4pKE+FAghEi+4RxJbqKioJCwCIjmcABycFBGNOjAYNy8JYIikojJEqnpmYgNeQVFfKUAynBxACL4EHCEWFCz6AKkAMJhZFMzcwuEIp1SYDLyisp2ahVqACqIm7Pzs3aJ+90ZSOhQWITUaaRYYACey0Qf3+iAAvAA+Nr7dozQ6yfAKJToOy3bY0UJ+Yh2egfL5pKKxeJJdrtF69bJkRAAdTmAAc6fhLPgAB5QfBgcxUvHfKAifLtNwDURwo6Ik4osFSm7TJhUMDUUgAeSo1BQuEeSVEAAExpNpncdksRetECqYGrojg9u0KPMYBBEOyKABGcHIVAYOzmy0a+g+9U4J62j6wR3OqAAJndAatJMkdrDTvwFAAzEs2uSkLHcAlEAKE6GHcmKAAWd3lKo1OpDFqIDPCRBZs2qwP54OF+3hlNQACsMdbVoA-HII6WlsLRQikacALTzxAAQWA7N2mzl9oQhhMZksNhp9MZ5mx-sHuEJcSeU+OyJUdgjLrs5B3FmsthzOC8p4tgdHPZdI7RJeSTXuKt73j2kZPsYpivvuH5fi2P5Wn+FCRoBRJXtI04SneEbpgI0EvpYza0lgDJMohH6oVABEYcBIrYTeyh4T246Ec+sEkWkrwHuRR5UWeOA0ex9HEox8LMaoEEUL2RFcW+SG+p+3hKb+Ea9mJiRAA), the output is:
```
[LOG]: "=== Declaring: Original" 
[LOG]: "In initialiser, should be 'Original':",  "Original" 
[LOG]: "INIT Decorator" 
[LOG]: "Decorating class:",  "Original" 
[LOG]: "--- After Declaration, should be Wrapped:",  "Wrapped" 
[LOG]: "'test1' should be Original:",  "Original" 
[LOG]: "'test2' should be Original:",  "Original" 
[LOG]: "'test3()' should return Wrapped:",  "Wrapped" 
[LOG]: "'test4()' should return Wrapped:",  "Wrapped" 
[LOG]: "'test5' should be Original:",  "Original"
```
All expectations align.

But, when [run using ES2022](https://www.typescriptlang.org/play?target=9&ts=4.9.5#code/GYVwdgxgLglg9mABDMMoAoIEMA2OCmATgFyIDOUhKA5gDSIQ5ZlkBK+wpAYuNPGAEpEAbwBQiCQwRk4BAHQ441dAAMAkkhRoYuGGSL0yACzggcAE0QAjfIgDkAEmHY8RAL53iK+o2ZsOiABkgQxMLOzAcmBYALb4AgDc4pKE+FAghEi+4RxJbqKioJCwCIjmcABycFBGNOjAYNy8JYIikojJEqnpmYgNeQVFfKUAynBxACL4EHCEWFCz6AKkAMJhZFMzcwuEIp1SYDLyisp2ahVqACqIm7Pzs3aJ+90ZSOhQWITUaaRYYACey0Qf3+iAAvAA+Nr7dozQ6yfAKJToOy3bY0UJ+Yh2egfL5pKKxeJJdrtF69bJkRAAdTmAAc6fhLPgAB5QfBgcxUvHfKAifLtNwDURwo6Ik4osFSm7TJhUMDUUgAeSo1BQuEeSVEAAExpNpncdksRetECqYGrojg9u0KPMYBBEOyKABGcHIVAYOzmy0a+g+9U4J62j6wR3OqAAJndAatJMkdrDTvwFAAzEs2uSkLHcAlEAKE6GHcmKAAWd3lKo1OpDFqIDPCRBZs2qwP54OF+3hlNQACsMdbVoA-HII6WlsLRQikacALTzxAAQWA7N2mzl9oQhhMZksNhp9MZ5mx-sHuEJcSeU+OyJUdgjLrs5B3FmsthzOC8p4tgdHPZdI7RJeSTXuKt73j2kZPsYpivvuH5fi2P5Wn+FCRoBRJXtI04SneEbpgI0EvpYza0lgDJMohH6oVABEYcBIrYTeyh4T246Ec+sEkWkrwHuRR5UWeOA0ex9HEox8LMaoEEUL2RFcW+SG+p+3hKb+Ea9mJiRAA), the output is:
```
[LOG]: "=== Declaring: Original" 
[LOG]: "In initialiser, should be 'Original':",  undefined 
[LOG]: "INIT Decorator" 
[LOG]: "Decorating class:",  "Original" 
[LOG]: "--- After Declaration, should be Wrapped:",  "Wrapped" 
[LOG]: "'test1' should be Original:",  undefined 
[LOG]: "'test2' should be Original:",  undefined 
[LOG]: "'test3()' should return Wrapped:",  "Wrapped" 
[LOG]: "'test4()' should return Wrapped:",  "Wrapped" 
[LOG]: "'test5' should be Original:",  undefined 
```
Many cases are broken for ES2022.

Here is the current code emitted for the ES2022 target:
```JS
let Original = Original_1 = class Original {
    static { this.test1 = init('Original', Original_1); }
    static { this.test2 = Original_1; }
    static test3() { return Original_1; }
    static { this.test4 = doNothing(function () { return Original_1; }); }
    static { this.test5 = Original_1?.test4(); }
};
Original = Original_1 = __decorate([
    SomeDecorator()
], Original);
```

I think the best solution that covers all bases here is to add a static initialiser block at the top of the emitted class:
```JS
    static { Original_1 = this; }
```
Now the alias will be available to all the static initialiser blocks. Everything works!

Here is an example of the [tweaked JS output code (playground)](https://www.typescriptlang.org/play?target=9&ts=4.9.5&filetype=js#code/EQVwzgpgBGAuBOBLAxrYBuAUANwIbygH1CATCZAe3l1mgF4oAKWAC0TCgDJOpX2A6YmUrVaASigAfSVABmIAHapEFBU2FUaVMABpe+AOYRYegNYQAnnrJhkEgN6YozqHgLIoDQyAC2EBbBg-AA2-gasegQMHgA8UADMUAD8+vBGsFAAXFA2HnT5UAogwcHJORC2nlAA8gBGAFbksPzp1QDuCgAK8BQADhDwsBYAIhXISL2wVMyGxmaWEtm51lguUIiyTEP9FJsAShCyoaieBcAUDU3AXDzbELtQB0dN-Bqi9GfySrAqCsASUUeh2OzTeNAgjDBU3gulS6XmVnKtjEqxcEGCkDkVCYbnWVSh2hCYVYUAAtFAAIzoPEAPgYAAZqYhSaSJBt1PjyJpoWAANqIAC6AKqjFiCTKJEY8EWUA8NPFKUlsFmJig5kR0qyORmaTmaoWEmkUHgqOc8GMIHgajl4u4xpuNUuqFeh0QCgg3T6AyGOvh+o1YkiWAAvlhcdUkAY3bhgoQqZgvspVOsFIhYKKY6F4HpkMFcGAwE8HE4XJQFGAKKEQhQDIwAAYASTUbrTiBj7AGejALAoxRIUFq0AA5AASezITMDYNDzJ1nN5gtPB25-OFw78BS4Pwoktmi1W2ULteyEMJxRJtQkCgAOQofAUtdkCmLa3NsEtaifp8TP2TAGUKD8UYRC0eBGBfUtVArKtghrRghwba8GwAFSgYDuSoIcd1ffc1F9YwJDoeVHDWNYy2giBq1rId0NEN0DEPVdMiHPRlV1ZpN23U1SLfD9GILKAAHVqF6fp+wgAAPWgFBIDg2PSKASNI5xQ13KBVODTByMrSjYOo-IGGAvMkAfbII0QKNN2CLCsFCDJzMsmMqgc6NYwpKoVwElyrMUtS4BoFBFJqSNXLjKo+DAalgygAB6GKoBiFkoE6PZqk6ao-wAQQAGSgZDqigTLhmGPKAAkGz-KBssQgBRPzlR+Dx7F4NggloOB3IYFt0yHbyYxY4KLNCikUXU+qAqalqBHa2AACZnJCqy4yi8bGt4CpYHicCgt4g8+rcla1n8tbmoi-gZoAFnxG87zYB9GB-X4mAcY1cMGxyDvU0bNKOhrAtO1rzo2gBWBahqWikkiBuALvAlbVP2sGPrChghC5d5GF5NSAKA9HQPAzABT0fad20mC4KHFlyUy2RaAIIz8AC1Qux7PsB2gYTcFEiASGY4nFpjDctwgUmoJ0qj6yHGaKSHGBWeCftB3e1zZ358HBelqHOJFrAyd0uC6yljbZtl7tewV9nlas1WrY142teF0Xy3FvTJZmraxFN+X+12tROe53m51t4Joc28CHa4rSxfJ2tDcu8CvfNn23v9sSbf20PYbECOdaj52Y7dkHE7ZpX9vTgWQ5m4Gc53IA) with just this one line added: 
```JS
let Original = Original_1 = class Original {
    static { Original_1 = this; } // <-- PROPOSAL TO ADD THIS LINE
    static { this.test1 = init('Original', Original_1); }
    static { this.test2 = Original_1; }
    static test3() { return Original_1; }
    static { this.test4 = doNothing(function () { return Original_1; }); }
    static { this.test5 = Original_1?.test4(); }
};
Original = Original_1 = __decorate([
    SomeDecorator()
], Original);
```

@rbuckton what do you think of this solution?

**Comment by rbuckton** [comment]
> ```js
> let Original = Original_1 = class Original {
>     static { Original_1 = this; } // <-- PROPOSAL TO ADD THIS LINE
>     static { this.test1 = init('Original', Original_1); }
>     static { this.test2 = Original_1; }
>     static test3() { return Original_1; }
>     static { this.test4 = doNothing(function () { return Original_1; }); }
>     static { this.test5 = Original_1?.test4(); }
> };
> Original = Original_1 = __decorate([
>     SomeDecorator()
> ], Original);
> ```
> 
> @rbuckton what do you think of this solution?

Yes, this will work fine. I should have a PR up for this shortly.

> PS. potentially the line: `let Original = Original_1 = class Original {` could now be simplified: `let Original = class Original {` because the alias is assigned internally. Although this is just a bundle size optimization.

No, this will not work. Inside of a class body, the bound name of the class is immutable (constant) and cannot be changed.

**Comment by rbuckton** [comment]
> > PS. potentially the line: `let Original = Original_1 = class Original {` could now be simplified: `let Original = class Original {` because the alias is assigned internally. Although this is just a bundle size optimization.
> 
> No, this will not work. Inside of a class body, the bound name of the class is immutable (constant) and cannot be changed.

Sorry, I misread your suggestion. To clarify, you're stating that the `Original_1` assignment in the `let` is unnecessary because it will be assigned in the first static block. Yes, this will work.

**Comment by KurtGokhan** [comment]
Will this be backported to 4.9? We are running into this issue in Angular 15 which uses TS 4.9 and targets ES2022 by default.

**Comment by lalo-mx** [comment]
How likely is to be fixed in 5.0 branch? Angular 16 currently depends on 5.0 branch and looks like is expected to be fixed on TypeScript side https://github.com/angular/angular/issues/49415

**Comment by RyanCavanaugh** [comment]
In general we only backport critical crashes or regression specific to a particular release, or issues without any workarounds. This doesn't appear to qualify for any of those criteria.

**Comment by russcarver** [comment]
This is still an issue with Angular 16.1.4 and Typescript 5.0.4 and a tsconfig with lib: es2022, module: es2022 and target of es2022. It's fine with a target of es2021.

According to the Angular upgrade matrix (https://gist.github.com/LayZeeDK/c822cc812f75bb07b7c55d07ba2719b3), for Angular 16.x.x, you must use Typescript >=4.9.5 <5.1.0

Has anyone tried Typescript >=5.1.0 with Angular ^16.1.4?

If no one knows the compatibility results, I'll give it a try and see what happens.

**Comment by ericrovtar** [comment]
> This is still an issue with Angular 16.1.4 and Typescript 5.0.4 and a tsconfig with lib: es2022, module: es2022 and target of es2022. It's fine with a target of es2021.
> 
> According to the Angular upgrade matrix (https://gist.github.com/LayZeeDK/c822cc812f75bb07b7c55d07ba2719b3), for Angular 16.x.x, you must use Typescript >=4.9.5 <5.1.0
> 
> Has anyone tried Typescript >=5.1.0 with Angular ^16.1.4?
> 
> If no one knows the compatibility results, I'll give it a try and see what happens.

To answer this question: Yes, using TypeScript 5.1.3 with Angular 16.2.12 did the trick.

**Comment by iqaan** [comment]
Still an issue with Angular 17 (tried, 17.3.12) and TypeScript 5.4 (tried, 5.4.3)
