### ISSUE TITLE
`navigator.serviceWorker` may be undefined in some secure contexts

### ISSUE THREAD

**Issue by TheCymaera** [microsoft/TypeScript#52044]
# lib Update Request

## Configuration Check

My compilation *target* is `ESNext` and my *lib* is `the default`.

## Missing / Incorrect Definition

`navigator.serviceWorker` is undefined in some secure contexts (private mode on Firefox), thus the correct type definition should be:
```typescript
readonly serviceWorker?: ServiceWorkerContainer;
```

## Sample Code
Bad:
```typescript
navigator.serviceWorker.register()
```

Good:
```typescript
navigator.serviceWorker?.register()
```

## Documentation Link

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/serviceWorker

**Comment by RyanCavanaugh** [comment]
APIs like these are marked non-optional for convenience, since it's extremely plausible that your script runs only in secure contexts as an invariant.

**Comment by FozzieHi** [comment]
@RyanCavanaugh I think this should be revisited. `navigator.serviceWorker` also [may not be available in Firefox Private Windows](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/serviceWorker).

I think this makes it much more likely to have breakage go unnoticed rather than it just not being available in non-HTTPS contexts. Indeed I only came across this issue after experiencing such breakage on a public website.

**Comment by TheCymaera** [comment]
Similarly, navigator.share is not defined on MacOS Chrome in secure contexts.
