### ISSUE TITLE
Ternary operator less strict than if statement

### ISSUE THREAD

**Issue by inad9300** [microsoft/TypeScript#52099]
Switching from an `if-else` block to a logically-equivalent ternary operator should not mean having less help from the compiler.

```ts
interface Thing {
  potato: 'potato';
}

function f(): Thing { // Meant to write "Thing[]", but made a mistake.
  const things = sessionStorage.getItem('things');
  if (things) return JSON.parse(things)
  else return []; // Correctly reports error.
}

function g(): Thing {
  const things = sessionStorage.getItem('things');
  // Fails to report that the second branch is not correct (presumably due to the first branch being of type `any`).
  return things ? JSON.parse(things) : [];
}
```

[Playground link](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgCoAtQHNkG8CwAUMsgA4D2YcY5AXMgOQVU0MDcRAvkUTAK4gEYYORDIYACgCU9DNjzIA9IuQBZCHHDIayAO5RgkZACI5ILAG0AusYA0yAEZ8wyALZwAJijhvgAZyoAawgAOiISBFEA7UxzP2QAXmQ-CD8-ERAAZRooOCxQ-LAASUhXCQYwWKw-BikOYmRgGGQJSuw-KWQoCDA+KDEAKUyAeQA5ENI4KBTWqo7w5AgAGxSunr6xazYlFQBhcihuoSWATzWKKDB46CgDsMJuQl4BIQzkLGlZKrwFyJBotpxRLJVLpUTZA55Ao9EoQMoVOa1eokZTIABicGAK205HOBxclWoMRQKT+HkcuUE6Ea8RAlGQkUOECELVI3T8fHcDlOyA8fBQOkqKBgwGmLgclIQ1IcEHk5GaYBOpBQAANNCcVVJ7iRur1+jF2sgAPzIIZjCZTGaA6qdehbLhAA).

**Comment by MartinJohns** [comment]
You forgot to fill out the issue template.

The behaviour is as intended. Using a ternary operator both sides are elevated to a common type. Since one of the sides includes `any`, the final type of the expression will be `any` as well.

**Comment by MartinJohns** [comment]
The TypeScript team provides the template to get a quick glance over the issue.

Yes, TypeScripts goal is to provide type safety, but that's gone as soon as you use `any`. There's really not something that can be changed here. What should the type of the ternary operator expression be? One side is `any`, the other an array. Even a union wouldn't work, because any type in union with `any` is reduced to `any`.

**Comment by fatcerberus** [comment]
The maintainers will immediately close issues that don't follow the template without looking at them, so you're wasting more time by not filling it out.

> Perhaps the intentions should be changed. TypeScript's top priority should be to catch bugs in people's programs.

While there's an argument to be made that `JSON.parse()` shouldn't return `any`, there's nothing to be "fixed" in the type checking here.  Once you have an expression typed as `any`, no type checking will be performed on that expression, because that's the *purpose* of `any`.  How would you propose this be fixed, given that the compiler must by necessity compute a single type for the ternary expression?

**Comment by inad9300** [comment]
My whole report is a single sentence, then the necessary code snippet. I fail to see what kind of quicker glance do you expect to get.

I don't know TypeScript internals, so I'm not really the person to ask for a solution. If you wanted to solve this problem, I am certain you would find one. I can only look at it from a user perspective, and, as a human, abstractly, it is pretty easy to tell what kind of checks need to be done to catch this type or problem.

Internally, you will surely need a concept of "ternary expression" as a thing with two types, even if this is not exposed as such. Heck, you could even do a pass where ternary expressions are rewritten as `if` statements and the problem would be solved. In everybody's minds, those two are just different syntactically after all.

In fact, you may have argued the same in the case of `if` statements. Functions must return a single type, which in the example above is `any`. If checking the actual return type against the stated one were the only thing you did, you wouldn't catch the type mismatch. But you do, because TypeScript is more sophisticated than that.

**Comment by RyanCavanaugh** [comment]
By your own argument, any semantics-preserving transform of code *must* have the same behavior, so let's do that:
```ts
function g(): Thing {
  const things = sessionStorage.getItem('things');
  const x = things ? JSON.parse(things) : [];
  return x;
}
```
The type of `x` is unambiguously `any` (any union involving `any` must behave like `any`, since that's what `any` means). And a `return any` is obviously legal, by definition. So the correct behavior of this code is to not have an error.

There are practical limits to how far you can take this argument while still producing desirable results.

**Comment by inad9300** [comment]
This is a mischaracterization of what I meant. I would argue, instead, that any semantics-preserving transform of code _should_ have the same behavior. I totally understand there are practical limits to making this a reality, of course. See? I actually don't mind at all if the answer to a problem is that it isn't practical for you to solve it due to non-technical concerns. But it rarely is.

**Comment by fatcerberus** [comment]
> See? I actually don't mind at all if the answer to a problem is that it isn't practical for you to solve it due to non-technical concerns.

The tone here is getting a bit uncomfortably passive-aggressive.  Please dial it back.

**Comment by inad9300** [comment]
It occurred to me to have a look at Flow, which I seldom do. I don't have much experience with it, so I may be wrong in my conclusions, but it looks to me like a pretty solid proof that this problem is solvable...

[Flow](https://flow.org/try/#0MYewdgzgLgBARgLniEAbApgQzDAvDKAJwFd0AoM0SWMJMYgWznUL3hgH4YApAZQHkAcgDoADpkIR0ACgDkABlkBKGElkBGWRQBmxMMCgBLcDG3SldRs1YBvMjBiF0UYoRxxOPASPGSZC5VUYDS0AXx09A2McAHNzGDsHJxc3di4+ITEJKTlFFTVNMnDKcGgYBksmFjY4pTIgA). [TypeScript](https://www.typescriptlang.org/play?#code/MYewdgzgLgBARgLniEAbApgQzDAvDKAJwFd0AoM0SWMJMYgWznUL3hgH4YApAZQHkAcgDoADpkIR0ACgDkABlkBKGElkBGWRQBmxMMCgBLcDG3SldRs1YBvMjBiF0UYoRxxOPASPGSZC5VUYDS0AXx09A2McAHNzGDsHJxc3di4+ITEJKTlFFTVNMnDKcGgYBksmFjY4pTIgA).

```ts
const b: boolean = true

const n: number = b ? JSON.parse('0') : '1'

function f(): number {
  return b ? JSON.parse('0') : '1'
}

function g() {
  return b ? JSON.parse('0') : '1'
}

const m: number = g()
```

**Comment by EliLichtblau** [comment]
I have essentially zero knowledge of flow but playing around with it I'm going to guess it treats "any" a little differently. In typescript
```ts
type T = (T1 | T2 | T3 ... | any) === any
```
This doesn't seem to be the case in flow. Essentially in typescript, the typechecker drops all types and casts to any while in flow it drops all anys and casts to the the union of "T"'s. Changing this would be a breaking change to typescript. It seems like a philosophical difference in language design. 

Warning: My knowledge of typescript and the compiler internals is very little and for flow its functionally zero, so take what I say with something of a grain of salt.
