### ISSUE TITLE
Class member snippets should probably not have a lower priority than keywords

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#52121]
```json5
        "includeCompletionsWithSnippetText": false,
        "includeCompletionsWithClassMemberSnippets": true,
```

```ts
interface Foo {
    prop: string;
    method(): void;
}

class C implements Foo {
    /**/
}
```

Request completions at `/**/`.

This is the **desired**/**expected** list:

![image](https://user-images.githubusercontent.com/972891/210876178-9f76518d-18e5-4e99-8349-4fafa6b1191c.png)

Here's what we provide today:

![image](https://user-images.githubusercontent.com/972891/210876161-98a86b59-9372-4b45-9b4f-d46f62a5f1bb.png)

**Comment by DanielRosenwasser** [comment]
It seems super weird that writing `protecte` would complete with a member instead of a keyword. Even if the sort text is higher, I wouldn't expect the method to even be selected. Is it possible that that's an editor-side issue?

**Comment by DanielRosenwasser** [comment]
Sounds like #48196 might not have been the right solution - editors support a `filterText` property which defaults to `insertText` if it's present.

So it sounds like the right solution is to provide a `filterText` whenever `insertText` is also present.

**Comment by gabritto** [comment]
@DanielRosenwasser it appears that using a `filterText` that omits the modifiers doesn't really work in this situation in vscode, because it makes the method completion be filtered out as you type the modifier.
In an example like:
```ts
class Foo {
    protected method(): void {}
}

class C extends Foo {
    /**/
}
```
Assuming `filterText` is set to `method(): void {}` (and `insertText` is still `protected method(): void {}`), what happens is if you type `protected` inside `class C`, the completion entry for `method()` is filtered out by vscode and never displayed, because its filter text doesn't start with `protected`.

**Comment by DanielRosenwasser** [comment]
Gotcha - what do you think of the following idea:

If one of the results is a snippet completion, then look at the touching identifier. If there is an identifier, and its text has a prefix match with a keyword, then omit the `filterText` and lower the priority of that specific completion (or set its completion priority to keyword completion priority). Otherwise, the `filterText` should be set to the declaration name.

It might be worth prototyping in the meantime just to play around with and figure out if that's a good heuristic.

_____

By the way, one part of your response caught me by surprise:

> Assuming `filterText` is set to `method(): void {}`

Is there any reason `filterText` is set to `method(): void {}` instead of simply `method`?

**Comment by gabritto** [comment]
> Gotcha - what do you think of the following idea:
> 
> If one of the results is a snippet completion, then look at the touching identifier. If there is an identifier, and its text has a prefix match with a keyword, then omit the `filterText` and lower the priority of that specific completion (or set its completion priority to keyword completion priority). Otherwise, the `filterText` should be set to the declaration name.

I'm not sure I understood your suggestion correctly, but based on what I understood, I think that doesn't work, because vscode requests completions when nothing has been typed yet, and then proceeds to filter those as the user types. So we'd get a request completion for the following scenario:

```ts
interface Foo {
    prop: string;
    protected method(): void;
}

class C implements Foo {
    /**/
}
```

But then we wouldn't get another completion request as the user types a possible keyword prefix, say:
```ts
interface Foo {
    prop: string;
    protected method(): void;
}

class C implements Foo {
    protect/**/
}
```

One thing we could do is to have class member snippet completion entries that start with modifiers have a lower priority than keywords, and the ones that don't have modifiers would have a higher priority than keywords. But that's also inconsistent and not the ideal experience either.

> By the way, one part of your response caught me by surprise:
> 
> > Assuming `filterText` is set to `method(): void {}`
> 
> Is there any reason `filterText` would be set to `method(): void {}` instead of simply `method`?

Not that I'm aware, although there might be some filtering vscode does based on what comes *after* the completion position and what's in the `filterText`. But I'm not sure.
