### ISSUE TITLE
Intersection types not merged in 4.9.4

### ISSUE THREAD

**Issue by jenovs** [microsoft/TypeScript#52252]
# Bug Report

### 🔎 Search Terms

Intersection types not merged

### 🕗 Version & Regression Information

- This changed between versions 4.8.2 and 4.9.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAigrhATiKBeKBvAUFKAbASwGdgCA7AcwC5MdcoAzCAQ2DkQiJu3vrEQIBbZsip1eGKAH0poSGWaCIAfhoByAGIs2HNVAC+4+gDJavXgGMA9niuIuZ870IUAFsBpk4ggEZIANEZOACYiANae3n6IgU64+rHmhrwJRhasEBR2BJw0AIKIiMwgADySRQDukb4BjHbCwMAQwTQkApQGAHx0yVCmGkUUSmTAWIZYctADzEMQI2iOTKzsuY64-EIiIGIS0rLgc4oq6lrLugZGpjzm1rb23EH0Lu7V0Y+98YmpuOlNWQKrApFUqSBj1VhNFpQNrkChdMZYLDWMgkKAcIhgKwoiA0eBIFDoa6EEiwh68JY6VbXXgbYSiNY3Gx2BzUuLPDxQACMiTiUFCiAiUAAzDykqLPkZvvRfplsqsANqPVm8So0ABM4voYMQDUh6gAqkRmmpNVLcABdL6BcZYIA)

### 💻 Code

```ts repro
type Query = {
  listing: {
    features: {
      primary:
      { __typename?: 'Feature' }
      & {
        colors: {
          light: number,
          dark: number,
        },
      }
    },
    categories: Array<{ raw: number, formatted: string }>
  }
  & Fragment
}

type Fragment = {
  features: {
    primary:
    { __typename?: 'Feature' }
    & {
      colors: {
        light: number
      }
    },
  },
  categories: Array<{ formatted: string }>
}

const response: Query = {
  listing: {
    features: {
      primary: {
        colors: {
          light: 1,
          dark: 3,
        },
      },
    },
    categories: [
      {
        raw: 2,
        formatted: 'Used',
      },
    ],
  },
}
```

### 🙁 Actual behavior

`colors.dark` and `categories.raw` are marked as errors as missing in the type definition.

### 🙂 Expected behavior

Errored fields are defined in the `Query` type and should be valid.
If I remove `{ __typename?: 'Feature' }` from `Fragment` the error goes away.

**Comment by Woodz** [comment]
For reference: this bug only seems to impact TS 4.9 (looks like it was fixed in TS 5.0), based on my reproduction in [TS playground](https://www.typescriptlang.org/play/?ts=4.9.5#code/C4TwDgpgBAYg9nKBeKBvAUFKBDAXGzLHARnwGdgAnASwDsBzAbkIF8BtAXWawCN8MiUHqSgUaDVsxbp0oSFABC2SsgJY8aothFi6TQuoBM5Knu5R2XQn028dphud7HRD+pPQsoAMlgJmsuDQSgBeqvCIAD6KygFywcoAgqoACsrA1NgANgA8SpRsAOTYhRxstACuALY8EJQcAHzoAMZwtBRCSfj5ySgCJPjFxIUANITYLsWGhZ4y8TGUCqnpmbn5RTylTa3twJ2L3cpLfdYihcKj1pM807MtbR08yocqJ+r4bP3qZ9qXghODCYzLAsDhjXj8AxCM4XcFEG6DG7AiyzHYdMArbL5fBpSgZbJ5ZQNVT9DSfKHaQHDOFGQG3EFg6yQwTCRHUqEIqDneko6QAMwqtGaGTaUDAlDgzQgZDIoQAFE8QocQgBKfAANzg1AAJmhpOLJdLZdgQnLSR8vgMub8aThJkC4aC4TZLayubCOddpo7PCqZAKhSLaGKJVKZbj8Vl5YqcZi1iaGmqoJqdXr0Aaw2QI6t5eaoOT-j92f97d7WIyIbZoWy-vCvbXpCw-YF5AANElW3SOCycKDRM2dtyMO0mcRMHscHxoQdj4eWFXMNF7AAe+HbKALVqGtYB1tuoOY8wAmh3Ka5ZxY+1AB2eu+Pd3e51PUDOzBYF-ddlAQPgT28tza4ylpcLDMEAA)
