### ISSUE TITLE
Pressing dot breaks jsx

### ISSUE THREAD

**Issue by Zombobot1** [microsoft/TypeScript#52288]
Some time ago I noticed that something inserts invalid jsx (in a `.tsx` file) and I found a bug.
If I press `dot` while the suggestion menu is open invalid jsx `={}` gets inserted.

![image](https://user-images.githubusercontent.com/48030070/212544477-e80307bf-199c-4904-be92-50f8a16e755f.png)

![image](https://user-images.githubusercontent.com/48030070/212544494-0241eff2-6377-46c5-adc8-8f33a4eb2ef1.png)

Outside jsx there is no such problem

Extension version v5.0.202301100
Tested on Mac

**Comment by mjbvz** [comment]
Minimal repo:

```jsx
const a = <div id={JSO|}></div>
```

Trigger suggestions for JSON

Here's the `completionInfo` response


```
        {
            "name": "JSON",
            "kind": "var",
            "kindModifiers": "declare",
            "sortText": "15",
            "insertText": "JSON={$1}",
            "isSnippet": true
        },

```

**Comment by pyBlob** [comment]
I can reproduce this when using tsserver through the vscode language server.

I tried to to reproduce this in tsserver and using fourslash, but in all responses, and "verify.completions", I never received a completionInfo with "insertText". Do you have some hints on how to make a raw tsserver or the fourslash tests behave the same like vscode+tsserver?

This is what I've tried so far in the new test `tests/cases/fourslash/completionsJsxAttributeInitializer3.ts`:
```ts
// @Filename: /a.tsx
////declare namespace JSX {
////    interface IntrinsicElements {
////        div: { a: string, b: string }
////    }
////}
////const value = "test"
////<div a={[|val/*0*/|]} />

verify.completions(
    {
        marker: "0",
        isNewIdentifierLocation: true,
        includes: {
            name: "value",
            kind: "const",
            kindModifiers: "",
            sortText: completion.SortText.LocationPriority,
        },
        preferences: {
            includeCompletionsWithSnippetText: true,
            includeCompletionsWithInsertText: true,
        },
    },
);
```

I didn't find out, why this only happens in vscode, but while debugging, I found this:
https://github.com/microsoft/TypeScript/blob/7f41c9045494f40efde5c4740e73dbf9ad38f929/src/services/completions.ts#L2901

It mentionts that `// Second case is for "<div foo={true} t[||] ></div>"`:
- The previous token is the identifier `t`.
- The parent of the previous token is a JsxAttribute without initializer. Therefore, the second `||` should have probably been a `&&`.
```ts
if (previousToken.kind === SyntaxKind.CloseBraceToken || (previousToken.kind === SyntaxKind.Identifier && previousToken.parent.kind === SyntaxKind.JsxAttribute))
```

Note that this is exactly the case that is triggered in this issue: `<div a={val/**/} />`
- The context token is `{` whose parent is the JsxExpression that initialized the attribute.
- The previous token is the identifier `val` that needs completion &rarr; matches `previousToken.kind === SyntaxKind.Identifier`
- The parent of the previous token is also the JsxExpression (It might also be a nested expression when completing an identifier of a member access: e.g. `JSON.str`) &rarr; already an initializer, because it does not match `previousToken.parent.kind === SyntaxKind.JsxAttribute`

I think this is enough for a pull request, though I would also like to provide a failing fourslash testcase.

**Comment by jakebailey** [comment]
If you can't get this in as fourslash but can get a trace, you can try doing it as done in this PR: https://github.com/microsoft/TypeScript/pull/52373

Where you effectively write the trace into a unit test and baseline the responses.

**Comment by pyBlob** [comment]
Pull request is running checks
