### ISSUE TITLE
TS Pick Up The Wrong Object Property

### ISSUE THREAD

**Issue by KiddoV** [microsoft/TypeScript#52294]
***I am not sure what VSCode extension does this, but If I am posting on the wrong REPO, please point me to the right direction!***

I have a ``global.d.ts``
```ts
interface JQuery {
    modal(options?: ModalSettings | ModalBehaviors, ...aguments: any): this;
}

interface JQueryStatic {
    modal(options?: ModalSettings | ModalBehaviors, ...aguments: any): this;
    //Settings
    fn: {
        modal: {
            settings: {
                templates: {
                    [key: string]: (...params: any) => ModalSettings;
                }
            }
        },
    }
}
```
In my ``main.ts`` when I call the JQuery:
```ts
$.fn.modal.settings.templates.authForm = function () {
    ....
}
```
It would yell:
![Untitled](https://user-images.githubusercontent.com/28552977/204620574-7c08e096-3f07-4756-88b6-92d031650c65.png)

... and that's stupid. I called my ``modal`` object from ``$.fn.modal.settings...`` from ``JQueryStatic`` not ``$(".element").modal({})`` from ``JQuery``!!! Why didn't it recognize that?

Any explanation?
Thanks!

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
