### ISSUE TITLE
Property 'toNumber' does not exist on type '{}'.ts(2339)

### ISSUE THREAD

**Issue by evilkongsNFTs** [microsoft/TypeScript#52379]
I am working on a project in Next.js and it has thrown me an error that I really have no idea how to solve since I have only been doing this for a week, I have not found proper answers on the internet to solve this, what should I do and how?

![image](https://user-images.githubusercontent.com/118764825/214160210-301274ec-e85f-4bbe-a81e-463136f874ce.png)

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
