### ISSUE TITLE
Type inference for declared enum member assignment

### ISSUE THREAD

**Issue by molisani** [microsoft/TypeScript#52531]
# Bug Report

### 🔎 Search Terms

enum, declare enum, union enum

### 🕗 Version & Regression Information

- This changed between versions 4.9 and 5.0

Noticed this change when testing the 5.0 beta, specifically in the wake of #50528.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.0-dev.20230131#code/KYOwrgtgBAsgngUXNA3lAggGigIWwYSgF8BYAKHIBtgAXKANwENKBGKAXlkWQDp0Buck1YcuSSDxyCKZACbAAxpUYAnYFFCQuAEUXK1s8agzY8UQqRnU6wgEyj4upauCHeAoc3udHel24kpciA)

### 💻 Code

```ts
enum MyEnum { A, B, C }

let val1 = MyEnum.A;
//  ^? MyEnum
val1 = MyEnum.B;

declare enum MyDeclaredEnum { A, B, C }

let val2 = MyDeclaredEnum.A;
//  ^? MyDeclaredEnum.A
val2 = MyDeclaredEnum.B;
// ^ Type 'MyDeclaredEnum.B' is not assignable to type 'MyDeclaredEnum.A'.(2322)
```

### 🙁 Actual behavior

Assigning a declared enum member to a variable with `let` infers the type to be exactly the type of that specific enum member.

### 🙂 Expected behavior

The declared enum assignment should be the same as the regular enum assignment, where the type is inferred as the enum itself (a union of all enum members).

**Comment by ahejlsberg** [comment]
In a declaration context (a `declare` declaration or in a `.d.ts` file), an enum member without an initializer is considered a computed enum member. Previously, such members caused an enum to become a non-union numeric enum type where there aren't distinct types for each member. For example, in

```ts
declare enum E { A, B, C }
```

the members would all have the same type `E`. Following #50528 we now create unique and opaque enum member types `E.A`, `E.B`, and `E.C` and consider `E` a union of those types. This is analogous to what happens when the members are initialized with literal values. However, we don't have "fresh" and "regular" forms of the unique enum member types, and therefore they don't widen. So, where `E.A` widens to `E` (which is the union `E.A | E.B | E.C`) when `E.A` is declared with a literal value, it doesn't when it is a computed member. Looks like we need to fix this by having "fresh" and "regular" forms of computed enum member types.
