### ISSUE TITLE
`any | T` from conditional type does not reduce to `any` 

### ISSUE THREAD

**Issue by dragomirtitian** [microsoft/TypeScript#52568]
# Bug Report

### 🔎 Search Terms

any union 

### 🕗 Version & Regression Information

- This changed between versions 5.0.0-dev.20221207 and 5.0.0-dev.20221208

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.0-dev.20230201&ssl=5&ssc=24&pln=1&pc=1#code/C4TwDgpgBAypDGUC8UCGA7EUIA9gXQBMBnKAewCMArCeYKAfjUygC4pjgAnAS3QHMA3AFgAUGNCQoAdR7AAFnFoAeACrY8BElHQBXALYUIXAHzIoqsRPDQASudkKl8Zc5NA)

### 💻 Code

```ts
type Spec = any extends object ? any : string;

type WithSpec<T extends number> = T

type R = WithSpec<Spec> // error here  in 5.0
```

### 🙁 Actual behavior

`Spec` is `any | string` so it can't be used with `WithSpec`

### 🙂 Expected behavior

`any | string` is reduced to `any` as it was in 4.9

**Comment by Tobias-Scholz** [comment]
I believe this is caused by #50397 and #51621.

In 4.9 we had a check in `getSubstitutionType`  where the `baseType` was returned when both `baseType` and `constraint` where non-generic. This check was removed in #51621, so a `SubstitutionType` is created for `any`.

A simple fix might be to just return the `baseType` when the `baseType` is `any`.

```typescript
function getSubstitutionType(baseType: Type, constraint: Type) {
  if (constraint.flags & TypeFlags.AnyOrUnknown || constraint === baseType || baseType.flags & TypeFlags.Any) {
    return baseType;
  }
```
