### ISSUE TITLE
Nested callbacks are not contextually typed with a type parameter dependent type query

### ISSUE THREAD

**Issue by dragomirtitian** [microsoft/TypeScript#52575]
# Bug Report

### 🔎 Search Terms

nested callbacks contextual types

### 🕗 Version & Regression Information

- This changed between versions 5.0.0-dev.20221216 and 5.0.0-dev.20221217

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.0-dev.20221217&ssl=23&ssc=1&pln=1&pc=1#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgUQDdgUAeAFQD44BvAKDkbm0wBtWAjHAawC44AFFGABnSEhHB+5AJRwAvNUIQEAEwDcDJklGpV-ekyPM2nHvyGjxk6XMVxlazUYC+dN3VCRYcGAE8wPABhAFcRGAgAWyISGBEFWi1GTH4YsnCoZABzSiS4DlTiMiQQyI40agB6SrgASXQ4CCRWP0adEyRVNUxUXwC8UARw+IR4AHdobhF3TTpVYGxWTGE4dBCkbBgEJrhgSNGKXZBUTvjuYD8IBtDwqLS4ygF-QOkAGjhVHpS4G4jooriAG1yABdGT8RyqOiefYwAQAckw8PehiYLHYXGwfEEUDs1BoLne1TgUEQ8Qy2UQSDgABYAHQATjgmE6cAArHSAAx5HThYD6RLGNGmTHYoR42hwYmkoZwClILJU2mM5mslm7KBQaBKjncvKuV55QnuGSaIA)

### 💻 Code

```ts
export interface Event<T> {
    callback: (response: T) => void;
    nested: {
        callback: (response: T) => void;
    }
}

export type CustomEvents = {
    a: Event<string>
    b: Event<number> // If only one candidate type exists it works
};

declare function emit<T extends keyof CustomEvents>(type: T, data: CustomEvents[T]): void

emit('a', {
    callback: (r) => {}, // r is string in 4.9 and 5.0
    nested: {
        callback: (r) => { // r is string in 4.9 and an error in 5.0

        },
    },
});
```

### 🙁 Actual behavior

The parameter of the callback in nested is not typed and gives an error : Parameter 'r' implicitly has an 'any' type.

### 🙂 Expected behavior

The parameter of the callback in nested is typed as string, same as in 4.9 and same as for the top level callback

**Comment by Andarist** [comment]
Somehow [the PR with `const` type parameters](https://github.com/microsoft/TypeScript/pull/51865) introduced this regression. cc @ahejlsberg

**Comment by Andarist** [comment]
This happens within `checkExpressionWithContextualType` called from [here](https://github.dev/microsoft/TypeScript/blob/bbfb9ac14fda34eba34fcdd41f6dee3ea9e08563/src/compiler/checker.ts#L32008)
1. Each of those properties goes through `getContextualTypeForObjectLiteralElement` and thus through `getApparentTypeOfContextualType`.
2. Each of those receive `CustomEvents[T]` back but they both try to instantiate it
3. the `callback` property is a function so the `contextFlags & ContextFlags.Signature` holds true for it and it instantiates the type [here](https://github.dev/microsoft/TypeScript/blob/bbfb9ac14fda34eba34fcdd41f6dee3ea9e08563/src/compiler/checker.ts#L28981-L28985), it receives `Event<string>` back
4. the `nested` property is not a function, so nothing happens there, and `CustomEvents[T]` is returned to the caller. However, in there, it's "dumped" to the constraint of that type [here](https://github.dev/microsoft/TypeScript/blob/bbfb9ac14fda34eba34fcdd41f6dee3ea9e08563/src/compiler/checker.ts#L28965-L28970) and that is `Event<string> | Event<number>`
5. And thus this ends up with conflicting signatures for the inner `callback` (`((response: string) => void) | ((response: number) => void)`) and the contextual type fails to be provided

It seems that perhaps the contextual type for `nested` should get deferred instead of being resolved to the constraint.

**Comment by ahejlsberg** [comment]
Hmm, yeah I see what's going on here, and it's subtle. To improve performance #51865 introduced caching of contextual types in `checkArrayLiteral` and `checkObjectLiteral`. Those caches can really only be consulted by `getContextualType` calls with no `contextFlags`, but we aren't keeping track of whether an entry on the contextual type stack is a cache entry or not. I will put up a PR that adds that tracking.
