### ISSUE TITLE
Type isn't get inferred properly in the context of mapped types for a single function with generic and multiple arguments using the same generic.

### ISSUE THREAD

**Issue by pleerock** [microsoft/TypeScript#52649]
# Bug Report

Type isn't get inferred properly in the context of mapped types for a single function with generic and multiple arguments using the same generic.
Not really sure how to describe the issue, the problem is clearly demonstrated in the playground.
Feel free to edit my message to put the relevant info and terminology for other people.

### 🕗 Version & Regression Information

All versions, including latest `4.9.5`.

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?#code/MYGwhgzhAECqEFMBO0DeAoaXoEsAmAhAFzQB2ArgLYBGym2pYlCx0EALkjqQOb1Ycw7chFYAibgDcc7BHjHQAPtDHMayMegC+6dOwCeABwTQA8tQBWCYOwAqRhAB5bAPmgBeMggDu0ABQAdEFgSDwQJGCk+gDaALoAlB5utrqgkDAAogCO5GAgpsZIQgD2SM5uGNjQwMWkHEjkNqV+huTUIDjA0JJ55AgktomV2Do6eg7QAOoAFshOGaTsMvpunsNY0QAKuKTQANYI+sUAZtALSwaxAPwk58tbsUpnOXkFyCVldwYPLtq6x+RSDYcLVoMduHhTKR5otli4-PxoAhYQYAMLgKAkcxWGz2YyOL4rAA0iOKhiWtXCU1mSBhF2J6CGYwBQIpu3BpDwBJRKz8yPp6PSWMs1jsDm59JcQ0RtOESF2fjJbKpMzmErhiXcFURVVl5HliNG-whUIQfngyCJaERgmEVOhvmyuXyhQ+fgkpGksnk8StAHo-c9nW8iuxStA8MUEBBSABydg7Y7IaDsWYphzaeLGznmxBIeJ+dZsdhCEQkB1B16usNId1SGRyMS+6ABysu941xPIGCpkwGYyZoA).

### 💻 Code

```ts
class User {
    id!: number
    name!: string
    status!: "invited" | "member"
}

type ObjectType<T> = new (...args: any[]) => T

class EqualOperator<T> {
    constructor(public value: T) {
    }
}

type Where<Entity> = {
    [P in keyof Entity]?: Entity[P] | EqualOperator<Entity[P]>
}

function findOne<Entity>(
    entityClass: ObjectType<Entity>,
    options: Where<Entity>,
) {}

function find<Entity>(entityClass: ObjectType<Entity>) {
    return (options: Where<Entity>) => {
        return
    }
}

findOne(User, {
    status: new EqualOperator("invited"), // EqualOperator doesn't infer the type
})

find(User)({
    status: new EqualOperator("invited"), // EqualOperator infers the type
})
```

### 🙁 Actual behavior

`EqualOperator` does infer string literal / enum type when used in the context of Entity[P] only for the second function.

### 🙂 Expected behavior

`EqualOperator` to infer string literal / enum type when used in the context of Entity[P] for the first function as well.

**Comment by RyanCavanaugh** [comment]
In general if you have two candidates of equal priority, the less-specific type is going to get chosen. That's what's happening here. This is effectively the same as having written
```ts
const m = new EqualOperator("invited");
findOne(User, {
    status: m,
})
```
wherein `m` has the widened type `EqualOperator<string>`. Inference isn't really capable of using a literal type from one candidate to influence whether a second candidate's type is kept as a literal or not, nor is it necessarily apparent that it'd be a good thing (since there is equal argument that the example above "should be" equivalent to the code as written).

In 5.0 you can write
```ts
class EqualOperator<const T>
```
to get the desired behavior, or in 4.9- write `"invited" as const`
