### ISSUE TITLE
Parameter type inference went bizarrely wrong, When using slightly complex parameter

### ISSUE THREAD

**Issue by wenq1** [microsoft/TypeScript#52716]
# Bug Report

### 🔎 Search Terms

conditional return type

### 🕗 Version & Regression Information

4.9, and yes, typescript@next is tried.

- This is NOT a crash
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### ⏯ Playground Link

See below:

[Playground link with relevant code](https://www.typescriptlang.org/play?&filetype=ts#code/FASwdgLgpgTgZgQwMZQAQGUAWAFBMEC2qA3sKuReQM4QwD6AbggDYBcl1t4A5gDRkdyAewAOERiwD87SjRg9+AX2ChIsRClS58BKNBgAVAJ4i0pQeRh6AcgFcCAI1jSKtW1H4XUcgIwyLcgoCglSYIniE-hRY2oTAysBwtmBIECBCYKhIVgjQADIITswADAA8APKoUAAe0GAAJlRaEbr6xqa8qAYAfAAU4FTlDgBW7AadIPXlMNaEUOzlAJQLVbVQDU3EVhB2jrDsblCKqJKoYPZOMKhjJMGoEJgwQgDuqABEySAEIsxQumr1N4AbniKl+EG8YRaFAAvCQ5BI2KgAORyZHHBBNGItEFgvSoBCoOHZKC5KAFIrFVC9ZGYKDMZhCZGdLY2C77e4wdydXzsADMAsUiyBlAA9KLUHBwFBgOLyAA9SR4iEOIlZHL5Qr0qk0ukMpks7a7S4HLkeby0PwotFCkWoOVSsAyuWoRXKrJqklkina6m0+mM5kkI3smCm7kWmAAVnYqNo6OF5Ad0tlEtdSuA4NQ9U9GvJWpKfr1gcNbL2Yc5EbkMet8Z5UJ0tqTErAQghUt+qYVGazaGJeZ9hd1AYNwbLJsr5tC4R0PMtsZtiftEueTzA3FQ4DgQlQzzpmUwQgYsB4qCPsC6UBoAGFmJiqAA6L2aopd9PuuC50kv33D-VB1kdlDcMpwbQg5xgK04xgINq1jYsmSbZczheSMo03JphlsGhN24VsrHqN83SAA)

### 💻 Code

```ts

interface ShParam {
        str_val:      string,
        opt_val?:     string,
}

interface ParameterType {
        retNumber?:   true,
        str1:         string,
        shparam:      ShParam
}

function createLabel0<O extends ParameterType, T>(insObj: T, idOrName: O): O extends {retNumber: true} ? number : T {
    throw "unimplemented";
}

let shparam   = {str_val: 'str'} as ShParam;


let a = createLabel0 ('hello', {retNumber: true, str1: 333});    // fine
//  ^?

let b = createLabel0 ('hello', {retNumber: true, str1: 'str'});  // fine
//  ^?

let c = createLabel0 ('hello', {retNumber: true, str5: 'str'});  // fine
//  ^?

let d = createLabel0 ('hello', {retNumber: true, str5: 'str', shparam});  // not file
//  ^?

let e = createLabel0 ('hello', {retNumber: true, shparam, str1: 'str'});  // wrong info when hovering over TestClass.createLabel
//  ^?

let f = createLabel0 ('hello', {retNumber: true, shparam, str1: 'str', str5: 'hello'});  // now str5 is just ignored
//  ^?

```

### 🙁 Actual behavior

Please hover on createLabel0 of case e and f. Its prototype becomes:
```js
function createLabel0<{
    retNumber: true;
    shparam: ShParam;
    str1: string;
}, "hello">(insObj: "hello", idOrName: {
    retNumber: true;
    shparam: ShParam;
    str1: string;
}): number
```

And more importantly, in case f, "str5" is not detected as wrong parameter anymore, like in case c and d.

### 🙂 Expected behavior

createLabel0's prototype should be:
```js
function createLabel0<ParameterType, "hello">(insObj: "hello", idOrName: ParameterType): "hello"
```

**Comment by fatcerberus** [comment]
> prototype

I think you mean “signature”.   “Prototype” means something completely different in JS than it does in C.

**Comment by wenq1** [comment]
> > prototype
> 
> I think you mean “signature”. “Prototype” means something completely different in JS than it does in C.

I’m sure you are correct. I just forgot where I borrowed the word from. Thanks for reminding.

**Comment by jcalz** [comment]
(I am not a TS team member, just an <strike>annoying</strike> interested fellow user)

I don't see any incorrect behavior here from the compiler, but explaining why nothing is wrong could take pages of text, links to documentation, and example code, and probably doesn't belong here but on Stack Overflow or some other more appropriate forum.  In short (ish):

* Excess properties are generally allowed, or else you couldn't extend interfaces or classes by adding properties.  Excess property warnings on object literals only happen because they are likely to be forgotten about, not because they violate the type system.  

* For `a`, `b`, `c`, and `d` inference fails, because your argument is bad.  You got an excess property warning in `c` and `d` because the argument was not valid `ParameterType` even *without* the `str5` property... so type argument inference of `O` failed and fell back to the `ParameterType` constraint, and `str5` is not expected in that type.  

* In `e` and `f` your argument is good because you supplied all the necessary properties.  Type argument inference *succeeded*, and `O` was inferred as the type of the passed-in argument, which necessarily `extends ParameterType`.  Since `O` knows about every property in the argument, there are no excess properties.

If there's something in particular you still think is broken, could you write out *very explicitly* what the problem is?

**Comment by wenq1** [comment]
Thanks for taking time to provide the detailed reply.

> * In `e` and `f` your argument is good because you supplied all the necessary properties.  Type argument inference _succeeded_, and `O` was inferred as the type of the passed-in argument, which necessarily `extends ParameterType`.  Since `O` knows about every property in the argument, there are no excess properties.

In "e", "f" cases, arguments are indeed good. However, why in these two cases, the function signature is inferred as
`function createLabel0<{retNumber: true; shparam: ShParam; str1: string;}, "hello"> ...` instead of `function createLabel0<ParameterType, "hello">`? Especially in case "e", the input parameter has a full match.

**Comment by jcalz** [comment]
The displayed call signature is showing you the results of type inference, with inferred type arguments substituted for type parameters.  When inference succeeds, `O` is inferred as exactly the type of the passed-in `idOrName` argument, so that's what gets substituted for `O`, not `ParameterType`.  Unless the argument is exactly of type `ParameterType`, you won't see `O` as `ParameterType` unless inference *fails*, in which case it falls back.  If you want `O` to be exactly `ParameterType` all the time, then your function should probably not be generic in `O` at all.

As for your more specific question, this isn't a forum for asking how to write code, so I don't feel comfortable continuing too much about how to resolve your particular code issue. I explained why excess properties are not a type violation... when you say "places I need to change" you are making an assumption about the language that isn't true.   Presumably you want *exact types* in TypeScript as requested in #12936, and you can look in there for approaches that people use there to simulate such behavior.  Maybe [this playground link](https://www.typescriptlang.org/play?&filetype=ts#code/FASwdgLgpgTgZgQwMZQAQGUAWAFBMEC2qA3sKuReQM4QwD6AbggDYBcqNM4A5gDRmUKAewAOERiwD87Tj34BfYKEixEKVLnwEo0GABUAniLSlBFGDoByAVwIAjWNNS1rUfmeq0AjDNpyBZlSYIniE7FiahMCKwHDWYEgQIEJgqEgWCNAAMggOzAAMADwA8qhQAB7QYAAmVBqh2rqGxqgAZKgASlBIQjDVhQCi5UjM1tVQhQDWUAZCcKjFvKjTs-ORjbDNUAB8S2BQDLC7qHrbABQBguBUxXYAVux6SyDVxTCWhFDsxQCU32WVKA1OrEVAWCA2eywdguNDyVCSVBgWwOGCoR4kS6UCCYGBCADuqAARPEQAQRMwoNoVNUiQBuaJKSkQDjBBqoAC8JA4tAkbFQAHJOALUPCEHUIg0GUydKgEJy0hlsrkoAUzgLMKrmEIBUtQeDIaiYTBXEtOD5UABma2in50ygAegdqDg4CgwCd5AAepIZSy7Ar0lBMlAcnl8urNcxtbruQaUdDnCa3DyYBahbQRfI7eRPa79h7nagfX60oGlaGVWqNVqdXqwVYEzBjabUwBWdgZmBZnOoPNuwve33AZmoarl4PK8OR2ux-WNqHNpOtzgdwXCs1srS2+1951gIQs12U1CFAC0Z5dIEpiOJB4gRKv+1vAHVMJlUCA6twhDxUClUHxEAcWcTAvzSIQCGpCBfU9Yth1HNAuSDEMw1VCMa2jOs4wXI1lxTIIQi0M1vE7YUd1zZ18TxMBuE-MA4CEQDNVSTAhEOLhaP-DiTigGgAGFmHFKgADoUKnVVTwvUC0HARjUG1IRJjqLhuEwFkICY7RB3g0t5mQis0OrKMY3reNFxbAit0IEi0zIzNbLXTCYwovdUE1CwhVQWZrDRBAwCofFYB0ksgA) will help you... but again, further discussion probably belongs elsewhere, and unless you can articulate a specific bug in TypeScript itself you should probably close this issue to save the TS team from the effort of triaging this.

**Comment by wenq1** [comment]
Solved my specific issue by not relying on tsc to warn me of excess parameters, but resorting to jscodeshift to do codemods automatically.

Thank you anyway for the playground link, which also works perfectly! Hopefully it didn't intrude too much into the uneasy zone of code-writing tutoring. Much appreciated.
