### ISSUE TITLE
Only last overload error is shown even with `noErrorTruncation`

### ISSUE THREAD

**Issue by eps1lon** [microsoft/TypeScript#52745]
# Bug Report

### 🔎 Search Terms

overload error message

### 🕗 Version & Regression Information

- I was unable to test this prior to 3.3 because we didn't even have errors for each overload if we had less than 4 overloads

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?noErrorTruncation=true#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVNQGYAKDATwAcQAueVZAWwCMQYBKWgNxy2AFgAUKEiwEKdNjwES5KrQDOGGFlQBzDvG69Bw6HCRpMufIiKlKNeAGUyzHBA1b+AneD1jDkk6gAs5uXSMLOxcPM66ogYSxgR+spaKymqOYa4i+uJGUqZxFrQ2dg6h2kJukZlesf6WTiklgqYyMMggbIINvqTNrUA)

[Playground link using 3.3](https://www.typescriptlang.org/play?noErrorTruncation=true&ts=3.3.3#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVNQGYAKDATwAcQAueVZAWwCMQYBKWgNxy2AFgAUKEiwEKdNjwES5KrQDOGGFlQBzDvG69Bw6HCRpMufIiKlKNeAGUyzHBA1b+AneD1jDkk6gAs5uXSMLOxcPM66ogYSxgR+spaKymqOYa4i+uJGUqZxFrQ2dg6h2kJukZlesf6WTiklgqYyMMggbIINvqTNrUA)

### 💻 Code

```ts
declare function fn3(type: number): void
declare function fn3(type: string): void
declare function fn3(type: Symbol): void

declare function fn4(type: number): void
declare function fn4(type: string): void
declare function fn4(type: Symbol): void
declare function fn4(type: void): void

fn3(true)

fn4(true)
```

### 🙁 Actual behavior

error message is displayed as

```
671181234512
declare function fn3(type: number): void
declare function fn3(type: string): void
declare function fn3(type: Symbol): void

declare function fn4(type: number): void
declare function fn4(type: string): void
declare function fn4(type: Symbol): void
declare function fn4(type: void): void

fn3(true)

fn4(true)

```
No overload matches this call.
  The last overload gave the following error.
    Argument of type 'boolean' is not assignable to parameter of type 'void'.(2769)
input.tsx(8, 18): The last overload is declared here.
``` 

### 🙂 Expected behavior

Since I have `noErrorTruncation` enabled, I expected the error for each overload to be included like I would have, if the function had less than 4 overloads.

**Comment by RyanCavanaugh** [comment]
There are a lot of functions with dozens or even hundreds of overloads and it was intentional to make this cutoff (3 overloads or less) apply to avoid near-infinite spamming in those cases.

`noErrorTruncation` is mostly about turning off type truncation in error messages, it's not intended to change this behavior.

**Comment by eps1lon** [comment]
So how would I debug why no overload matches?

**Comment by Andarist** [comment]
I'm not saying that it's great DX but I usually just comment out overloads and leave a single one in the file. Then I get the best-printed error for that particular overload. I usually already know which overload I want to investigate though, if you have a lot of them and you want to check why each one is not matching... then it might be more work.

**Comment by eps1lon** [comment]
> I'm not saying that it's great DX but I usually just comment out overloads and leave a single one in the file.

I don't consider this DX at all. That's going to cause TS screaming at me in other places making it even harder to understand what's going wrong.

**Comment by Andarist** [comment]
Yeah, I wasn't exactly commenting on the issue at hand - just responding to the question posted by you 😉 Since I don't know how to do this in a better way - I just follow this strategy and shared it.

> That's going to cause TS screaming at me in other places making it even harder to understand what's going wrong.

Ye, sure - but when u investigate the error at a given call site u can ignore the rest. You just focus on the particular call site in the IDE and after you figure it out then you just uncomment the rest.

**Comment by RyanCavanaugh** [comment]
I explained the scenario where printing all overload matches would be undesirable. We can argue about where the boundaries of the grey zone are, but I think it's inarguably bad DX for a single call to e.g. `document.createElement` to spew *hundreds* of lines of error text.

I don't know how to move the ball forward when I've given our stated reasoning. If you don't think our reasoning is intentional, well, we'll have to agree to disagree on that one?

**Comment by fatcerberus** [comment]
> We can argue about where the boundaries of the grey zone are

Yay sorites paradox!
