### ISSUE TITLE
Bad inference when passing a field of a discriminated union as field function instead of arrow function

### ISSUE THREAD

**Issue by paoloricciuti** [microsoft/TypeScript#52798]
# Bug Report

### 🔎 Search Terms

discriminated union function

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wG4AocgeipgAsik4oUA7AE1zhgE8wkAzgBo4rCKzhooAVzTAUAGziZo3OsAFwkADxTgFScr35wAgnAC8cAN7k4cFAC44AIwgQDbIeQC+lY0wAQpY2dq7OAjBQwKwA5t5+RnxMAMIhtvZozqzSIC5IUBSJNPQacGX0TGygKDDA4ppgOGCawADkeDAoANYxseWsAHTlmijMSGjQ7HAQmHDdSDyjHA4SEC4AVhPwk+AQAkjTs9RUNgBuitJI2bn5UD6r02PsGlKgMbWHcNKs9UNwAEk5r0VlZ8Ch8HAeBBpFCYXA6CgzkwYBA4GAUAJNOZMMAkAp2AITo8ZmA6uJFAoeA5lD8MH81LVxjBpFBWKN0ShYPIlLMzIMkiZTL8QLU-porBk4ABtBY8CJRPoAXWcAAprHALgorjc8gU4A8AGRwVVhewakHsZzg-AiTB0gD8qoAlM4AApcuqKAA8pgAfAa4MbzAAfM02eYxK0EFy22msNBO11wD3cn2BANGuDBMP2c2RjjWtBx+0JpPuz0870pTNBuApMLO52+fzJOAAZV4BlTem9ABUtNoYEgONiRWKGgGrMhJlB2N65Xy+yJItE4n6KCdKujmpo+dvdpBWCOYIMz8B4F0FqsauT2XAB2wnvH6eJGZeeoITmMZ1M4AB3C86AcBQlG3OU9zmR8VlXPoBAFAIzHHYd2AANTxf83V3ftB2HUckNvcUp1CexIh4Aw1XDapRTvARUMuQRnE7cikB7EB+z9RtLADWC4goexqIndlnD7IpN0mdl4BSXAjxPEIcJ0PDCQImiiPVG9VIaFcuyYHxnGFW9DnQpBMOwvs-Wdbi4G9P1vSoTjyAkyIzDAMAQhdKypSIFk2Wszi82s6S9mPVh4EE2iLGsKUAuHSJnGigKC2jG1vESvMtR1OAAEZUrShxnCiK5coCvwStKxKyIMSLVWoyyLADBK8rzGgAD0HXDAKaDoAomERTRoVhNA2DgA4mGAOBYiQMLRC5HB-31AIOrzbzWQkfB8HDHwHns8Nqxk8Q5PC8VIsa7hBBgeKlvsS1rQhYrEoy65svugKnG4GQkBe5qqBcaQws0AR3AkTFygcdhplKTRSzQK6XxdU6ApW3yEcSt7Cs+2H7HKtLsbzXGtqWyqkGq2rPMxxLWvapqaHGybpsA9h9Um49ojQbhklhpG1o2sq4B2gK9uCw7kOOqKltii6SLym6CDu2HHucHLYbRj6vvsGhfvgYA5m3aG7xGVYHCgOaXzvWHobVZ16pR+wualpqBIK1Xydxkqlvx12Rp0kmRTqhryc6qg2thmm9wTKpYhQGIaVYWaIHmqB2f4TmptWggebx7b-OsnaHnIIA)

### 💻 Code

```ts
import React from "react";

//three random types, non crucial for this example
type A = {
  a: boolean,
}

type B = {
  b: string,
}

type C = {
  c: number;
}

//this is the animations props i'm taking in. is a record of keys and an object composed of
// {value: number} and a discriminated union. If kind = "a" you you have to pass A fields
// and optionally a function that returns a partial of A.
type Animations = {
  [key: string]: ({ value: number } & (
    { kind: "a", func?(): Partial<A> } & A |
    { kind: "b", func?(): Partial<B> } & B |
    { kind: "c", func?(): Partial<C> } & C
  ))
}

type StyleParam<T extends Animations> = Record<keyof T, string>;

//the props of the component...it take animations T and a function that takes
//a Record with all the keys of T and strings.
type AnimatedViewProps<T extends Animations> = {
  style: (
    animationsValues: StyleParam<T>
  ) => string;
  animations: T;
};

const Component = <T extends Animations>({ animations, style }: AnimatedViewProps<T>) => <></>

const App = () => {
  return <>
    <Component animations={{
      test: {
        kind: "a",
        value: 1,
        a: true,
      }
    }}
      style={(anim) => {
              //^?
        //here has you can see i get a narrower type
        return ""
    }} />
    <Component animations={{
      test: {
        kind: "a",
        value: 1,
        a: true,
        //but as soon as i add this func
        func(){
          return {
            a: true,
          }
        }
      }
    }}
      style={(anim) => {
              //^?
        //i get a wider generic type
        return ""
    }} />
    <Component animations={{
      test: {
        kind: "a",
        value: 1,
        a: true,
        //but if the function is an arrow function
        func: ()=>{
          return {
            a: true,
          }
        }
      }
    }}
      style={(anim) => {
              //^?
        //is once again a narrower type
        return ""
    }} />
  </>
} 

```

### 🙁 Actual behavior

If i pass func as a field function the type inference gets lost

### 🙂 Expected behavior

It should not matter if the function is passed as an arrow function or as a normal function

**Comment by Andarist** [comment]
The whole object containing a context-sensitive function is marked as non-inferrable, so u don't gather that object as an inference candidate, it escapes here, just before pushing it as a candidate:
https://github.dev/microsoft/TypeScript/blob/588dd82afe1dd7049f0915c9c45e6f4557bcbdc3/src/compiler/checker.ts#L24141-L24159

The context-sensitive function is replaced during inference with `anyFunctionType` (https://github.dev/microsoft/TypeScript/blob/588dd82afe1dd7049f0915c9c45e6f4557bcbdc3/src/compiler/checker.ts#L35391), that has `ObjectFlags.NonInferrableType` on it and that's a "propagating" flag so it taints the whole object here: [https://github.dev/microsoft/TypeScript/blob/588dd82afe1dd7049f0915c9c45e6f4557bcbdc3/src/compiler/checker.ts#L29781](https://t.co/zYeH1qAAWK)

Perhaps this could be fixed if instead of using `anyFunctionType` to replace context-sensitive functions, we'd use some kind of a reverse~ symbol. If I understand correctly, the point here is to block inferring from this function + avoid exposing it to the user through the candidate. But if that property would be allowed on the candidate but if its type would get deferred and resolved later then maybe this could work. There is also a good chance that I don't know what I'm talking about - I don't have a good mental model for conflicting inference candidates and stuff like that yet.
