### ISSUE TITLE
Generic function taking array of promises not inferring resolved types into union

### ISSUE THREAD

**Issue by ericbf** [microsoft/TypeScript#52806]
# Bug Report

### 🔎 Search Terms

generic function promises union type inference

### 🕗 Version & Regression Information

As early as 3.3.3, and up to nightly.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about 4.9.5

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAGxlApgJwIbIM4A8AKgHwAUAbtpngFyJEDaAugJT1GIDeAUIv4kzooITEio1GABmY8Avjx6oMOfGWkAaRACJtWsCGTIt4ACbpgMMOlNtFoSLASIADpjgBbGHnSFSlajpEAAV3Lx9iEhZ2ELDvdEjuPgEhETFECTxpWQUeN094vHVQgp8AOiE8OGQKdDIpVi0S8PQK32rasl1G2NLWyo66gyMe5vi2qpq6swsrG1Y2IA)

### 💻 Code

```ts
function literals<T>(vars: T[]): T {
    return vars[0]
}

literals([0, "", null, undefined])

function promises<T>(vars: Promise<T>[]): Promise<T> {
    return vars[0]
}

promises([Promise.resolve(0), Promise.resolve(""), Promise.resolve(null), Promise.resolve(undefined)])
```

### 🙁 Actual behavior

Error on `promises` call:

```
Type 'Promise<string>' is not assignable to type 'Promise<number | null | undefined>'.
  Type 'string' is not assignable to type 'number'.(2322)
```

### 🙂 Expected behavior

The inferred type of promises call to be `Promise<number | string | null | undefined>`, like in the `literals` call (the type inferred there is `string | number | null | undefined`).

**Comment by Andarist** [comment]
It's likely that the first non-nullable candidate wins and fixes this inference - nullable candidates are also allowed and added as candidates (likely because this is a common use case). Type parameters appearing at the top-level and in other positions tend to behave slightly differently on purpose. I think this is going to be classified as "Working as intended"/"Design limitation" but I could be wrong.

**Comment by RyanCavanaugh** [comment]
I believe the operative rule here is that fresh literals are allowed to union during inference, but not unfresh literal types. Regardless, boundary conditions in inference are unavoidable; this isn't a bug.

**Comment by ericbf** [comment]
So then this would be more of a request/inquiry. Should it allow "unfresh" literal types to union? Why is that limitation in place?

**Comment by RyanCavanaugh** [comment]
I think what's happening here is that, since there are generic calls with type parameters in the return position, we collect those candidate types directly from the function arguments, and so there are effectively 4 candidates here (string, number, null, undefined), and inference correctly "rejects" the call by picking one somewhat arbitrarily, since this is desired behavior.

That doesn't happen in the `literals` case; intuitively this makes sense because this refactoring is clearly a valid program and so its inlining should also be valid, thus this is desired behavior.
```ts
const sn = [0, "", null, undefined];
literals(sn);
```
So the `literals` call collects 1 inference candidate (`string | number | null | undefined`) and the call succeeds.

Unfortunately both of those principles make sense and cannot be simultaneously satisfied. Which heuristic you hit depends on what kind of code you write.

**Comment by ericbf** [comment]
Ok, given that there's a workable path forward for the same use case by reworking it a bit, and we determined it’s working as intended, I’ll close this out! Thanks!
