### ISSUE TITLE
<Infer X> in conditional type changes the return type when testing a union. 

### ISSUE THREAD

**Issue by JeanMeche** [microsoft/TypeScript#52882]
# Bug Report

I have a line that looks like following : ```type Baz = Foo | Bar extends FormGroup<infer U> ? true : false;```

The presence of generic inference `<infer U>` changes the return type : `true` without, `false` with. This does only happen when using the union of the left-hand side of the  `extends`  operator. 

### 🔎 Search Terms

* infer
* condtional type
* generics  / generic
* generic inference
* union

### 🕗 Version & Regression Information

Not a regression.  Bug present in 5.0 nightly

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.5#code/C4TwDgpgBAYg9nKBeWcBOBbA4muBXMAHgG8pgBLYAGwgC4oBnYNcgOwHMoBfAPgChQkKACEAhmmSpMOfEVIVqEAEz0mLDtx4BuPnwgAPMOmBQAJhADGVcdCuiGDKdlwFCAFQDCcVszhVJoqwgPFCkUOF84eEAZqwAjAAU4uz0nt6+VACUqV4+uFSRUbFKSWgpUGl5ftlQAAxQBsAQrKaOlRlQAPxkaHjQ9NGiVAwQfFy6gtBiAF6S8IgAPiLiDfpNLY7w0i5EbNEQEgCqId3MfVADQyM6APQ3UQB6nbp3UADqlAAW+CbAn9CEPYHKDHAA0UAABmcIBCoORHGgIMA8GhWBBTHxXuRolBilBPvYoKw4CZRFALN5TJRyN4hlBEcjUWRwBBwZQoFdEAyUaxIdCIUA)

### 💻 Code

```ts
type Foo = FormGroup<{ title: string }>
type Bar = FormGroup<{ title2: string }>;

export declare class FormGroup<TControl = any> {    
    fn1(arg: TControl): TControl
    fn2(arg: TControl): 0 extends TControl ? true : false
}

type Baz = Foo | Bar extends FormGroup<infer U> ? true : false;
//   ^? false

// Without the `<infer U>`, `true` is returned
// if `fn2` has not a conditional return type, it also return `true`
```

### 🙁 Actual behavior

When adding `<infer U>` the type changes. 

Also note, that this does not happen if there is no conditional type in the class. 

### 🙂 Expected behavior

The generic inference should not influence the typing.

**Comment by fatcerberus** [comment]
By leaving out the `<infer U>`, you're testing against `FormGroup<any>`, which succeeds.  No other type fits for `U`, and IIRC TS intentionally tries to avoid inferring `any` in an `infer` position.

**Comment by JeanMeche** [comment]
Then why would that work without the conditional return type on `fn2` ?

**Comment by whzx5byb** [comment]
@JeanMeche 

Consider this type: `type A<T> = { fn1(x:T): T }`. 

Although the type parameter `T` appears in both contravariant position and covariant position, it is still considered as only covariant because of [Function Parameter Bivariance](https://www.typescriptlang.org/docs/handbook/type-compatibility.html#function-parameter-bivariance). So `A<T> | A<U>` is assignable to `A<T | U>`, and `T | U` will be a reasonable candidate of `R` when infer `A<T> | A<U> extends A<infer R>`. That's why it works without the conditional return type.

**Comment by fatcerberus** [comment]
Indeed, it becomes false again if one or more of the methods are defined as properties instead (assuming `strictFunctionTypes` is enabled), because then the class becomes invariant like in conditional type version: [Playground](https://www.typescriptlang.org/play?ts=4.9.5#code/C4TwDgpgBAYg9nKBeWcBOBbA4muBXMAHgG8pgBLYAGwgC4oBnYNcgOwHMoBfAPgChQkKACEAhmmSpMOfEVIVqEAEz0mLDtx4BuPnwgAPMOmBQAJhADGVcdCuiGDKdlwFCAFQDCcVszhVJoqwgPFCkUOF84eEAZqwAjAAU4uz0nt6+VACUqV4+uFSRUbEqUEloKVBpeX6ZyCFVGXxcuoLQYgBekvCIAD4i4lAGwBCspo7w0i5EbNEQEgCqIQD8ZGh40PTRolQMEDoA9PtRAHpLuodQAOqUABb4JsA30IQzc1CLADRQAAbM699QciONAQYB4NCsCCmPgXcjRKDFKA3exQVhwEyiKAWbymSjkbzbKAgsEQsjgCBfShQbYMRDE8GsH5-CDfIA)

The conditional type is a red herring; it's a variance issue.  In general `T<A> | T<B> extends T<infer C> ? ...` will fail if `C = A | B` isn't a valid substitution.
