### ISSUE TITLE
Extract to constant doesn't work with nested binary expressions on the right

### ISSUE THREAD

**Issue by zardoy** [microsoft/TypeScript#52980]
# Bug Report

### 🔎 Search Terms

No extract symbol refactor

### 💻 Code

```ts
// works
const a = [|1 + 2|] + 3

// doesn't work
const a = 1 + [|2 + 3|]
```

In last case refactoring is not suggested.

In this case there is binary expression node with `1 + 2` on the `left` and `2 + 3` on the `right`

**Comment by RyanCavanaugh** [comment]
The "extract" options only show up when you have a selection span that covers a proper subtree of the AST, which in this case (due to left-associativity) the selection doesn't. Apart from this exact case it's hard to figure out any other place where this matters so I don't think it's worth trying to implement some much more complex logic to handle this.

One could also make the argument that this particular extraction isn't semantics-preserving, but I'm not going to 😉

**Comment by fatcerberus** [comment]
It took me way too long to realize you meant `2 + 3` is not a proper subexpression because the AST says `+(+(1, 2), 3)`, and I only figured *that* out from the "non-semantics-preserving" remark...

**Comment by zardoy** [comment]
> Apart from this exact case it's hard to figure out any other place where this matters

But why don't record a range instead of node to replace in case if selection consists of *plain* binary expression only, like `a && [|b && c|]`. On the other hand I fully agree with you second statement…
