### ISSUE TITLE
Illegal declaration file can be emitted (duplicate parameter names) when spreading tuples into parameter positions

### ISSUE THREAD

**Issue by RyanCavanaugh** [microsoft/TypeScript#53011]
# Bug Report

### 🔎 Search Terms

parameter spread duplicate identifier parameter tuple

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMAFASkQbwFCL4qATwAcBTRAQUQF5EBtAZwC5EGoAnGMAcwF0BuXPiJlEAYRr0AdDIoAaRDKkUB2IXnakoIdklCRYCZGBRKAhu27NxGTIgC+2R0A)

### 💻 Code

```ts
function f() {
    // n.b. not illegal
    type C = [s: string, s: string]; 

    return function fn(...args: C) { }
}
```

Less-degenerate form where you can't just not make that mistake:
```ts
function f() {
    type A = [s: string];
    type C = [...A, ...A];

    return function fn(...args: C) { }
}
```

declaration emit in either case becomes
```ts
declare function f(): (s: string, s: string) => void;
```
which we consider a syntax error:
```
error TS2300: Duplicate identifier 's'.

1 declare function f(): (s: string, s: string) => void;
```

### 🙁 Actual behavior

Multiple parameters with the same name get printed

### 🙂 Expected behavior

Probably something like `(s: string, s_0: string) => void` instead

**Comment by fatcerberus** [comment]
Is there a reason this emits as `(s: string, s: string) => void` instead of `(...args: [s: string, s: string])`, preserving the original form of the definition?

IMO there's also a case to be made that, since the rest-param version is semantically equivalent to the separate parameters (enough so that decl emit will freely substitute one for the other), it should just be an error to use a tuple with duplicate labels.

Either way I'm a bit surprised nobody seems to have hit this before, tbh

**Comment by RyanCavanaugh** [comment]
> Is there a reason this emits as ...

Not particularly. You'd obviously want to see the former in something like signature help since it's easier to parse and highlight, and we largely share codepaths for type printback.

> Either way I'm a bit surprised nobody seems to have hit this before, tbh

Me too!
