### ISSUE TITLE
`transpileModule` does not account for package.json `type` when ran with node16/nodenext module setting

### ISSUE THREAD

**Issue by romkhub** [microsoft/TypeScript#53022]
# Bug Report

### 🔎 Search Terms

transpileModule node16 nodenext

### 🕗 Version & Regression Information

Checked with

`@4.9.4`
`@beta` - `5.0.0-beta`
`@next` - `5.1.0-dev.20230227`

It's only about `node16`/`nodenext` and therefore doesn't affect TS versions before 4.7

### ⏯ Playground Link

https://github.com/romkhub/ts-transpile-node16

The repo illustrates how `tsc` provides ESM, while `transpileModule` gives CJS upon the same setup.
After debugging I see it related to [this code](https://github.com/microsoft/TypeScript/blob/v4.9.5/src/services/transpile.ts#L68) which, as I understand, essentially hides all the files except the one transpiled.

My real-world scenario is an attempt to use node16 TS setup in a repo built with webpack and ts-loader in `transpileOnly` mode. With `transpileOnly: true` I get CJS, `transpileOnly: false` - ESM

### 🙁 Actual behavior

`transpileModule` does not recognize `"type": "module"` in package.json and emit CJS, while `tsc` emits ESM

### 🙂 Expected behavior

JS emitted by `transpileModule` is the same as of `tsc`

**Comment by mrazauskas** [comment]
Hitting the same problem. Seems like the cause of it is the following:

- a custom `compilerHost` is created inside of `transpileModule()`
- the `fileExists()` method of the host is only able to check existence of the input file path: https://github.com/microsoft/TypeScript/blob/27d3454f07cb41a24275d7f1de07621b8217f739/src/services/transpile.ts#L108
- the host is passed to `getImpliedNodeFormatForFile()` function, which is responsible to find nearest `package.json` and to look at its the `"type"` field
- this job is done by `getPackageJsonInfo()` function, which calls `host.fileExists()` on each of potential `packageJsonPath`s: https://github.com/microsoft/TypeScript/blob/27d3454f07cb41a24275d7f1de07621b8217f739/src/compiler/moduleNameResolver.ts#L2263

Unfortunately the host cannot know about `package.json` files, because it is only able to check the existence of the input file path.

---

Might be this is expected behaviour. For instance, if the `transpileModule()` function is intended to work with visual files only and it shouldn’t know anything about the real file system.

**Comment by mrazauskas** [comment]
Here is a patch of the `compilerHost` which makes `"module": "node16"` compiler option work as expected:

```diff
- fileExists: (fileName): boolean => fileName === inputFileName,
- readFile: () => "",
+ fileExists: (fileName) => fileName.endsWith("package.json") ? sys.fileExists(fileName) : fileName === inputFileName,
+ readFile: (fileName) => fileName.endsWith("package.json") ? sys.readFile(fileName) : "",
```

**Comment by RyanCavanaugh** [comment]
I'll wait for @rbuckton to make a final call, but my impression is that the entire point of `transpileModule` is to be a text-only transform process. It shouldn't attempt to hit the disk at all; it *especially* cannot call `sys` functions.

**Comment by rbuckton** [comment]
I concur with @RyanCavanaugh. `transpileModule` shouldn't interact with the file system at all. If you want it to treat the input file as ESM, you would need to provide a `fileName` to the `transpileOptions` argument with a `.mts` (or `.mtsx`) extension. If that isn't sufficient, we could consider adding an option to `TranspileOptions` to override the implied node format.
