### ISSUE TITLE
Mapped type with union in value with data type accessing failing to strongly type

### ISSUE THREAD

**Issue by justinfernald** [microsoft/TypeScript#53030]
# Bug Report

### 🔎 Search Terms
mapped type, mapped object, unioned types 

### 🕗 Version & Regression Information

Observed issue on version 4.9.5 and sees that it also exists on Nightly
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about mapped types

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?#code/KYOwrgtgBAKgngB2FA3gWAFBW1AggGkxygCFCscBhTAX00wEsQAXYAJwDMBDAY2QAUucADYB7LgBMAyszZgezMG2ToK2CV2Zd4SAFyxEwANxEcGrfrAgA1iFEB3ECYx0MjFu258ogkeIm4UMAAHqwgEgDOPkJikjJyCkoqpuqa2ob6OsAAdLjOxOZc+hGyTADmzq7urJy8AjH+JEGhoJHRfnGy8orKqClQhVmZhtkk+WZp+uAQAEbslfQYTDVe9R0SlM1hbb6x0l2JvaoFaUMGSNmU46kWfWrEUMFTkHNs1w9wz7Pz-TQLbhhmIZ2nsoABeEH+QIAH0hkiasN2-moAKBSCgAEkQBx2MAJEjJIEIQSJFAAGSoQYZc45XB-TA8UQgEpQIqY7G4-ENQngu4nW4AIgAFgwBeR+ek9DTcrRFgB6OVQSiiNjKBTCOBQBhRNHIEpscoMpksrgAEUm7Jxyi561wAG0BYUBQBdXnC0WLXVQACyXAQSBtewAjLzjjg7dZgJqmHCJA6qUgXc6APz6AAUhX0JPJlNO1MjcBoAEpwQA+KAAN1EDAksoBjOZzCgCG5kSD+l9-rxJJDELD2AVUHNWi1Ta9+vKrKiISQCjx-TtWVyzvTKEKxbLqAbEVEwhyYjKGbSRdcVUBwM7AZJACZQwuC1qQLH43nE86U+nM1A09mKWvX8A+gFsWL5aC6JZguWVY1nWRqNs2rYRNeHZ+lera3n2-SDhiUD2KIYDCKSM7AAoAxpFAzCiFAcxQKIHAUcCE4gGU+DUWATYMBxUQSEywALkuuArt+hQQeWKDbru+6iIeImnkAA)

### 💻 Code

```ts
enum Type {
    A,
    B,
    C
}

interface PayloadStructure {
    dataType: Type;
    data: unknown;
}

interface PayloadA extends PayloadStructure {
    dataType: Type.A;
    data: string;
}

interface PayloadB extends PayloadStructure {
    dataType: Type.B;
    data: number;
}

interface PayloadC extends PayloadStructure {
    dataType: Type.C;
    data: {
        x: number;
        y: number;
    };
}

type Payload = PayloadA | PayloadB | PayloadC

type MappedPayload2 = {
    //                                                                v - issue comes from selecting a type from property
    [key in Payload["dataType"]]?: (data: (Payload & {dataType: key})["data"]) => void
}

const payloads2: MappedPayload2 = {
    // [ISSUE]: I would expect data to be of type string, but it is every type from Payload's data property
    [Type.A]: (data) => {console.log(data)}
}
```

### 🙁 Actual behavior

Noting code snippet with comment prefixed with "[ISSUE]"
Using a mapped type then using the key to do an intersection with a type then getting a property, doesn't use the key to get the specific type from the property; however, if you do not get the type from a property, it does correctly type the values.

### 🙂 Expected behavior

Noting code snippet with comment prefixed with "[ISSUE]"
Using a mapped type then using the key to do an intersection with a type then getting a property, doesn't use the key to get the specific type from the property; however, if you do not get the type from a property, it does correctly type the values.

In the playground I put comments where when you are not accessing the property, it works, but when you do, it doesn't.

**Comment by RyanCavanaugh** [comment]
I'm not sure if this is intentional or not; someone can investigate.

Anyway, here's a workaround:
```ts
type GetPayload<P, K> = P extends { dataType: K,  data: infer D } ? D : never;
type MappedPayload2 = {
    [key in Payload["dataType"]]?: (data: GetPayload<Payload, key>) => void
}
```

**Comment by Andarist** [comment]
`checkParameter` leads to an eager resolution for this indexed access. The problem is that this branch of code is **not** entered:
https://github.dev/microsoft/TypeScript/blob/e9868e96e87996df46a13b4323866acc639e71ce/src/compiler/checker.ts#L17555-L17576

If it would get entered here then this indexed access would be deferred~ and thus, later on, when instantiating the mapped type, the existing correct mapper would actually resolve `K` to `'a'. That would unwrap the correct value from this indexed access. 

I'm not sure why this `objectType` is not treated as a generic object if it contains `K`, I think I might not know what a "generic object" is for the compiler. 

Either way - when I forcefully entered this branch for this given object, I got the expected result. The caveat was that the indexed access within the declared signature reported: `error TS2536: Type '"data"' cannot be used to index type 'Payload & { dataType: K; }'`. I expect that to be fine though, it's likely that the required change in the logic for deferral purposes should just be accompanied by a change in the logic that checks if a given object can be indexed with a given property or not. At the moment I'm not sure how to extend this condition to defer this indexed access though.

**Comment by ahejlsberg** [comment]
As @Andarist describes above, the issue here is that we aren't deferring the `(Payload & {dataType: key})["data"]` indexed access type and thus we miss the opportunity to reduce the type as we instantiate the members of the containing mapped type. Keep in mind here that while `(Payload & {dataType: key})["data"]` is how we display the type, it is actually a union `(PayloadA & {dataType: key})["data"] | (PayloadB & {dataType: key})["data"] | (PayloadC & {dataType: key})["data"]`, which evaluates into `string | number | data: { x: number, y: number }` because it isn't deferred.

As I was looking at workarounds, I discovered that this errors when really it shouldn't:

```ts
type GetPayload<P, K> = P extends { dataType: K } ? P["data"] : never;  // Error on P["data"]
```

It's definitely possible for us to defer resolution of indexed access types where the object type is reducible by instantiation. We already have similar logic in place for deferring `keyof xxx` for such types. I'll put up a PR that fixes this, plus the error I discovered above.
