### ISSUE TITLE
Duck typing on anonymous object literals and class objects

### ISSUE THREAD

**Issue by zeeshanhanif** [Microsoft/TypeScript#5303]
Based on new duck typing concept fresh objects can not have access property.
Like this

```javascript
let a = { name:"Bill"};
let b = {name:"Bill", age:20};

a = {name: "James", age:30 }; // Error - excess property not allowed
a = b; // No error - works fine
```

Now the questions is does this concept also applies to class objects
Like this:

```javascript
class Human {    
    name: string;    
    constructor(name: string){
        this.name = name;
    }
}

class Animal {
    name: string;
    age: number;    
    constructor(name: string, age: number){
        this.name = name;
        this.age = age;
    }
    eat(){
        console.log(this.name + " is a Human and is eating");
    }
}

let h1 = new Human("James");
let a1 = new Animal("Dog", 2);
h1 = new Animal("Cat", 1); //this is working -- But based on duck typing concept it should not because it has excess property and its fresh object
```

The error is same if I remove constructor.

Is there any difference in duck typing concept for anonymous objects and class objects OR may be I'm missing something?
Or is it really considered as fresh object?

**Comment by ziaukhan** [comment]
I have the same question?

**Comment by NasrullahKhan** [comment]
I also have the same question.

**Comment by DanielRosenwasser** [comment]
*Object literals* have an associated freshness before they're bound to a variable. The same doesn't apply for any other expressions.

The idea is that object literals are often used for option bags (where the user has to manually type out each property name at each use-site), and this behavior catches typos.

If you'd like to prevent `Animal` from being assigned to a `Human`, you can add a `private` property to `Animal`, since `private` and `protected` properties need to originate from the same declaration to be compatible.

**Comment by zeeshanhanif** [comment]
Thanks its clear now
