### ISSUE TITLE
Type narrowing for predicates with empty object union not working anymore

### ISSUE THREAD

**Issue by mahmood-sajjadi** [microsoft/TypeScript#53039]
# Bug Report

### 🔎 Search Terms
is, predicates, narrowing

### 🕗 Version & Regression Information

Typescript: from V4.8.4 (4.7.4 is fine)
typescript@next still has the issue

- This changed between versions 4.7.4 and 4.8.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.4#code/JYOwLgpgTgZghgYwgAgIIFtRwDbIN4CwAUMsiHOhAFzIDOYUoA5sQL7GiSyIoBiwtABb5ipWgHdg6WjQBGAe3nYIcEGw7ho8JMgAi8piJLJxOANYzkCpSrVF2RYjACuIBGGDyQyAfyEAKAAcIMBo-YQAfPQNkKLxWAEoaYLAfWmRwo1IoEOcobyCQ5Dh08ISAOgkpdIBCAF465FcAEwgYUAhmgG51Ihc3Dy80-SZC0IyBSOjDOMTkooFprOQcsDyClOL0kYrTbAtkesaWto7u3qdXd09vJhDUECkcfyTkfwwsXAAyN8yonYSsXwrGWCC89BWqma8nQpDqAFk4GBBOUoFCYS8esZgDA3miQNDYQ1GgAGWJRfGE5DE5Ak8oAVkBq3WwKx2Vy+UhBJhyAAfLSGcgAPzLUjkSg0ABE4UlABpRKQ6JJpDQGM4IPLjCCaIRjGKKNRkJKRnLkArSHsLKqoOrNaRWFiHGCQBDVE9cI07mAHu7McQOLj-AB5WQAKwg7nKZggAE9aP43egcBVlCAmMjqQ0SYDdaRnbQbOVsAZ-AByCDoQJgGPIeRhiNgUsJXo4-y+SYJx5J7AJHMK-OF4ujRM4WXFLs4crijXj92VZW0Zv2ANt2gjTvu3ug8GDksj7Bj-dTg2HifYcqWxe9IA)

### 💻 Code

```ts
function test(obj: Base & (Fish | Dog)) {
  if (isFish(obj)) {
    // in all typescript version : obj type is (Base & Fish) as expected, we have access to Base attributes
  }
  if (isDog(obj)) {
    // in all typescript version : obj type is (Base & Dog) as expected, we have access to Base attributes here
  }
}

function test2(obj: (Base & (Fish | Dog)) | {}) {
  if (isFish(obj)) {
    // until typescript 4.7.4 : obj type is (Base & Fish) as expected, we have access to Base attributes
    // from 4.84, obj type is (Fish | (Base & Fish)), we will not have access to Base attributes anymore
  }
  if (isDog(obj)) {
    // until typescript 4.7.4 : obj type is (Base & Dog) as expected, we have access to Base attributes
    // from 4.84, obj type is (Dog | (Base & Dog)), we will not have access to Base attributes anymore
  }
}
```

### 🙁 Actual behavior

See above please

### 🙂 Expected behavior

see above please

**Comment by ahejlsberg** [comment]
This is working as intended. In your example, you're operating on the type `(Aminal & (Fish | Dog)) | {}` which is simply a more complicated way of writing `{}`, because `{}` is a supertype of every type except `null` or `undefined`. In 4.8 we fixed some inconsistencies in narrowing of singleton types vs. union types, and you're seeing the effect of that. Specifically, `isFish` applied to `(Aminal & (Fish | Dog)) | {}` would incorrectly narrow to `Animal & Fish`, but now correctly narrows to `Fish | (Aminal & Fish)`. Which again is just a more complicated way of narrowing `{}` to `Fish`.

**Comment by mahmood-sajjadi** [comment]
Thanks @ahejlsberg for quick response

So there is no way anymore to say

The input is an empty object OR Animal-Fish OR Animal-Dog
I mean all Fish and Dogs are Animals (Without extending Fish and Dog but by composition) but we can have empty object as input?

**Comment by fatcerberus** [comment]
The root of your issue is that `{}` is not the "empty object" type.  There is, in fact, no such type because any object can have more properties than its type calls for (see #12936).  So it doesn't really make sense for your logic to try to say, e.g. "this is either a dog or an empty object", rather you should reformulate the code to say "this is either a dog or it isn't".

**Comment by mahmood-sajjadi** [comment]
Thanks @fatcerberus 

Would you please let me know how we can create a type for
> this is either a dog or it isn't
For the body of the function it is clear but when we want to create a function to accept empty object or Dog or Fish, 
if we define the function as
`Function myFn(obj: Animal & (Dog | Fish))`
it will not accept `{}`

So what is the correct solution to create a function which can accept empty object, Fish and Dog?

**Comment by fatcerberus** [comment]
> we want to create a function to accept empty object or Dog or Fish

You can't.  That's what I'm trying to say.  Your "empty object" is not guaranteed to be empty and may, in fact, be a dog or fish (or cow, or pig, or...).  Hence why TS is unable narrow away the `{}` possibility from the union.  By saying the function can accept `{}`, you're effectively saying it will accept any object at all.
