### ISSUE TITLE
`instanceof` not work

### ISSUE THREAD

**Issue by yingshaoxo** [microsoft/TypeScript#53214]
```typescript
class User {
    id: Number | null = null
}

let a_user = new User()
a_user.id = Number(2)

console.log(a_user.id instanceof Number)
// it print out 'false', but it should be 'true'
```

**Comment by MartinJohns** [comment]
You forgot to fill out the issue template.

This behaviour is correct and unrelated to TypeScript. This is just how JavaScript operates. When you use `new Number(2)` instead of `Number(2)` it will print `true`. Using `new` you end up with a `Number` object (a wrapper around a `number`), but using `Number(2)` you end up with the primitive `number`.

**Comment by yingshaoxo** [comment]
ok, thanks for the tip

**Comment by MartinJohns** [comment]
Also, there's really no reason to use the `Number` wrapper. Stick to `number` instead. If you want to check if a value is a `number` you can use the `typeof` operator.
