### ISSUE TITLE
Type guards with `Readonly` don't work with 5.x as they did with 4.x

### ISSUE THREAD

**Issue by akx** [microsoft/TypeScript#53486]
# Bug Report

### 🔎 Search Terms

* readonly
* type guard

### 🕗 Version & Regression Information

- This changed between versions 4.9.5 and 5.0.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.2#code/KYDwDg9gTgLgBDAnmYcCqUCWBBOBeOAbwFcsAuOAZxiwDsBzAXwG4AoUSWBZVAOQEMAtsFwFCtIcArU6TNh2jwkKOKPRZcAHzgDh2NqwBmxWgGMYmCLTiZKGHAAp+FAErB+AEysAbRAB5sAD4ASgp+G0p1HCJWODgoYBhSawcAclJMVJtrcIAyXO4UCEM4fgA6DPw8AlSZTAZU4LZGViMTc0trekSANX5vYmAnV3cvWl8AkOkaevoYuISkqGtbe2wnYLgAflKKrDgwsolhZtYgA)

### 💻 Code

```ts
export type UriA = {uri: string};
export type NameA = {name: string};
export type A = UriA | NameA;

function isUriA(a: Readonly<A>): a is UriA {
  return ('uri' in a && typeof a.uri === 'string');
}

function getValue(a: Readonly<A>): string {
  return isUriA(a) ? a.uri : a.name;
}
```

### 🙁/🙂 Actual and expected behavior

In TypeScript 4.9, the above code typechecks; the inferred type of `a` in `getValue`'s ternary expression's else arm is `Readonly<NameA>`, so `.name` can be accessed.

In TypeScript 5.0, the type is `Readonly<A> `, so `.name` may not exist.

**Comment by ahejlsberg** [comment]
This is an intended change in 5.0. Given some type `X`, in analysis of type predicate functions we now consistently consider `X` a subtype of `Readonly<X>` (because, intuitively, it is sound to treat an `X` as a `Readonly<X>`, but not vice-versa). This in turn implies that there exists `Readonly<X>` values that aren't `X` values (presumably because they aren't mutable). So, in a check of whether a `Readonly<UriA>` is a `UriA`, according to the types it is possible to have objects that aren't, and that's the reason `a` has the full `Readonly<A>` type in the false branch.

The simple fix in the example is to have `isUriA` return `a as Readonly<UriA>`.

The 4.9 behavior of treating `X` and `Readonly<X>` as mutual subtypes led to odd behavior like the following:

```ts
function getValue(a: Readonly<A>) {
  if (isUriA(a)) {
    a;  // UriA
  }
  else {
    a;  // Readonly<NameA>
  }
  a;  // UriA | Readonly<NameA>
}
```

Notice how the type of `a` all of a sudden differs following the `if` statement.
