### ISSUE TITLE
spreading an array of type `T[] | U[]` results in mixed array `(T | U)[]`

### ISSUE THREAD

**Issue by robinzigmond** [microsoft/TypeScript#53670]
# Bug Report

### 🔎 Search Terms

Array, spread, mixed, union

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about arrays/spread

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.3#code/GYVwdgxgLglg9mABBOAHAngRgDwBUA0iAqgHwAUAhgE5UBciuA2gLqIA+xLAlIgN4CwAKEQjEVAKZQQVJIwB0C6lWYBuIQF8hQ0JFgJkadACY8hUpRr0mrDkW58hosZOlIlcgM4AbGBHFkuNUFNQSA)

### 💻 Code

```ts
function copy1<T, U>(arr: T[] | U[]) {
    return [...arr];
}

function copy2<T, U>(arr: T[] | U[]) {
    return arr.slice();
}
```

### 🙁 Actual behavior

The return type of `copy1` (using the spread operator) is inferred as a mixed array type `(T | U)[]` even though it must have the same type as the argument, which is a non-mixed array of one of the two types.

`copy2`, which uses the `slice` method instead, infers the expected return type.

### 🙂 Expected behavior

Both return types to be inferred as `T[] | U[]`.

**Comment by RyanCavanaugh** [comment]
The type `(T | U)[]` is a correct bound on the type.

We have to choose between two inconsistencies here. If you had written
```ts
   return [arr[0]];
```
that'd be a `(T | U)[]`, which would not be consistent but effectively semantically identical in terms of mixed vs non-mixed usage.

**Comment by robinzigmond** [comment]
Thanks for the reply! I'm afraid that I'm a little confused by it though.

For one thing, although of course `(T | U)[]` is "a" correct bound on the type, it's not strict enough for the real use-case where I first came across this (inside a function which expected a non-mixed array, of one of the two types, to be returned). (Although I realise I can use a type assertion to make it correctly `T[] | U[]`, but I prefer not to have to do that, especially in cases where it looks to me like the correct type should be able to be inferred anyway.)

You say that returning `[arr[0]]` would be `(T | U)[]` (which I've confirmed) and that wouldn't be consistent - well it seems consistent to me given that's what returning `[...arr]` also does. Of course `arr.slice()` returns `T[] | U[]` which is what I view as correct here, so `[arr[0]]` can't be consistent with both - but one of the most puzzling things to me here is why these two operations, which as far as I understand them should be identical in behaviour, behave differently in Typescript in this particular situation. Is there some subtle difference in (plain JS) behaviour here that I'm unaware of?

It's also not clear to me why `T[] | U[]` shouldn't be inferred as the return type anyway - I see that you might want to push other elements on to the array after doing this, and you might want to make it mixed, but I'm not sure if that needs special treatment when you might even want to push a completely separate third type onto it. So I'm also curious as to the reasoning behind making the spread operator return the mixed type.

I'm happy for this to be closed as "not a bug" if the behaviour is indeed intentional (as it seems it is) - and if so I'd also appreciate a link to an FAQ entry or blog post explaining this in more depth, if such an explanation exists.

Thanks again!

**Comment by RyanCavanaugh** [comment]
You have a completely valid argument for why you might expect `T[] | U[]` here.  There's also a completely valid argument for `(T | U)[]`: the type of `[...expr]` should be the same type you'd get if you indexed `expr` by a number, and make "an array of that the type" of the resulting expression, since that's what's really happening at runtime, and that doing something differently for e.g. `[...expr[0], ...expr[1], ...expr]  (a thing which semantically cannot change the mixedness of the array and `[...expr]` ) would be an inconsistency.

In general we find it's better to have behavior that is consistent, with fewer special cases, as long as that behavior is broadly correct, which this behavior is. We also don't like to just change things for the sake of changing them, so if behavior is correct (which this is), then we need a stronger motivating scenario than "That's not what I expected" since as soon as we change this, the converse inconsistency "bug" appears and someone else can say "That's not what I expected, *also you broke my code*" and we start to have to justify why we're not changing it *back* to the behavior that was previously correct.

This isn't a frequently-asked question so I don't have a link.

**Comment by robinzigmond** [comment]
Thanks, that makes a lot more sense. I'm not seriously asking you to change this, given the risks that you quite rightly point out, so I suppose you need reply no more, but I'm still curious, since you talk about consistency a lot: why is the inferred return type of the spread operator different in this case than that of the `slice` method? All the arguments you give for `[...arr]` above could equally apply to `arr.slice()`, unless I'm overlooking something (which I quite possibly am!)

**Comment by RyanCavanaugh** [comment]
A method call is just a method call. TS doesn't "know" that the method you're calling is `slice` and try to apply Array semantics to it; it's just a method that happens to be called `slice`. We don't want to special-case built-in libraries unless it's absolutely unavoidable, since people often want to create user types with "the same" semantics as built-ins.

*In general* if you take a `T<U> | T<V>` and turn it into a `T<U | V>`, that operation is super unsafe:
```ts
type Box<T> = {
  datum: T;
  getSelf(): Box<T>;
  accept(val: T): void;
};

declare const b: Box<"a"> | Box<"b">;
const c = b.getSelf();
// must error
c.accept("b");
```
so a method call on a union type is effectively distributive rather than coalescing.

**Comment by robinzigmond** [comment]
Of course - but a method call, especially a built-in one in this case, should have a defined return type, which will be something specific and appropriate to that particular method. But your "in general" point about distribution explains the behaviour in this case. (Although this "super unsafe" thing is exactly what spreading an array turns out to do, which is where this started :) )

I think I understand now, and will say no more - thanks again for the explanations!

**Comment by fatcerberus** [comment]
> Although this "super unsafe" thing is exactly what spreading an array turns out to do, which is where this started :) 

In practice, yes, but not according to the type system - because TS pretends (intentionally) that array types are covariant.
