### ISSUE TITLE
tsc capitalizing file name.

### ISSUE THREAD

**Issue by DavidSouther** [Microsoft/TypeScript#5371]
https://github.com/DavidSouther/rupert/tree/ts-master

In this project, `./src/di/binding.ts` gets compiled to `./dist/di/Binding.{d.ts,js,js.map}` (Notice the capitalized Binding.) When its siblings then `import { } from './binding' in dependent projects, TSC fails because that file isn't present.

What arcane things might I have done to cause this to compile that way?

**Comment by vladima** [comment]
this happens because `src/di/di.ts` imports this file as `'./Binding'`. On case-insensitive file systems both `./Binding` and `./binding` refer to the same file and internally we just store the name that we met first.

NOTE #5275 adds a flag to force consistent naming on case-insensitive systems. If I use it to compile your example I get `error TS1149: File name 'src/di/binding.ts' differs from already included file name 'src/di/Binding.ts' only in casing`

**Comment by DavidSouther** [comment]
OMG I looked at that import like three times. Thanks :)
