### ISSUE TITLE
ReadonlySet and ReadonlyMap are not narrowed by instanceof checks

### ISSUE THREAD

**Issue by cevr** [microsoft/TypeScript#53800]
# Bug Report

### 🕗 Version & Regression Information

I have noticed this bug on the 5.0.4 version of typescript, but I suspect this has been around since `ReadonlySet` and `ReadonlyMap` were introduced.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `ReadonlySet` and `ReadonlyMap`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=7#code/FAUwHgDg9gTgLgAgGYFcB2BjOBLKaFxQDCUANqSFrmgDwAqAfABQBuAhqSiAFwJ0CUvOgnBwQaACYBnBABlsUuPIDWIGtjRIQMBADUGCAPx6A2gF0EQkWDGSZAJUqwJKtRq079RhI4zOaijAaAOYANHoGvGggLNoIAN7ACAjYSEwK8oqurBxc-PwJSckpaeycICloimyYIFBICADKIHAFicXFMC0oMPgmAHSDZVxmRckAvmMIAPTTBAAWFV1SKKQ4aMEEAJ4QFejUCIrY5JUYnBIgDiBsEnikW81wU11wPfjDIEWTyanpUr7ObIffKFDq-D6Vaq1eoIACybAgbSmyRebwQAHkAEYAK0ocH6SBgUAAtgBRNBwIKXHLlfriSnYan5KbfYqzBZLS6rdabOA7PZoA5HE4aM4oC5XG53LbwiDPbq9BAfL7AIpweZEgDuCGi2tJMCJMCYACI0FBEGwEH5yHjqABaUjYVTG-jASaq8DQeDbXZyBRKJ1qRgIAC8RQAPnxzBGmi16AwY44pWh7gBBA1sLbxxPXW4ph5xxgAbg9kFgiD5voBMBcgfjoZzfhrAQZG3CjBjspbQTbfATyUjSbz9y7gRC7YYJeAqEwODwKSkmQDqhoqeYH146GUZs1aEEStyFQUfqydbXoIQqMVEI0UIwdQajwQ4cj6Zgmf6CjfmZpeTdqpnKh5wUataxXNdfx4BAtx3PdeBvK4mzAtRz3aS8FXwJgphvKo4Bqe8YVlZ9wymJhKwfA9ylDEMQwQY0oBxPFjQQAAyFjkUorgEAAQhonVVlIVj2I6ZJuO-LZPykcTIIKNiOO4yDITw6FHxaZlkn4EtxiAA)

### 💻 Code

```ts
export function toCollection<T>(value: T): T extends ListLike<infer V> ? V[] : T extends RecordLike<infer V> ? Record<string, V> : never {
  if(isListLike(value)) {
    if(value instanceof Set) {
      return [...value]
    }
    // the resulting type union still includes ReadonlySet
    return value
  }
  if(isRecordLike(value)) {
    if(value instanceof Map) {
      return Object.fromEntries(value.entries())
    }
    // the resulting type union still includes ReadonlyMap
    return value
  }

  throw new Error("not a collection-like")
}


export type ListLike<T> =
  | T[]
  | Set<T>
  | ReadonlyArray<T>
  | ReadonlySet<T>;

export type RecordLike<T> =
  | Record<string, T>
  | Map<string, T>
  | ReadonlyMap<string, T>;

function isListLike<A>(value: unknown): value is ListLike<A> {
  return value instanceof Set || Array.isArray(value)
}

function isRecordLike<A>(value: unknown): value is RecordLike<A> {
  return (
    value instanceof Map ||
    (typeof value === "object" &&
      value !== null &&
      !Array.isArray(value) &&
      !(value instanceof Set))
  );
}
```

### 🙁 Actual behavior

`ReadonlySet` and `ReadonlyMap` are not narrowed by `instanceof Set` or `instanceof Map` conditions 

### 🙂 Expected behavior

I would expect both `ReadonlySet` and `ReadonlyMap` to be narrowed by `instanceof Set` or `instanceof Map` since they are just qualifiers over `Set` and `Map`.

**Comment by MartinJohns** [comment]
> since they are just qualifiers over `Set` and `Map`.

But they're not. They're independent interfaces. There's nothing in the type system that links these interfaces to `Set` and `Map`,

**Comment by cevr** [comment]
@MartinJohns Are you suggesting that a ReadonlyMap is not a Map when compiled? 

The expectation is that when checked with `instanceof` the resulting union includes the readonly variants, not exclude them.

**Comment by MartinJohns** [comment]
Technically, neither values typed as `ReadonlyMap` nor `Map` (the interfaces of TypeScript) have to be instances of the `Map` class at runtime, the values just have to match the interfaces.

The type system can't really represent what you want. `instanceof Map` narrows to `Map` because the value `Map` is typed as `MapConstructor` ([es2015.collection.d.ts line 36](https://github.com/microsoft/TypeScript/blob/main/src/lib/es2015.collection.d.ts#L36)), and the `prototype` of `MapConstructor` is typed as `Map<any, any>` ([es2015.collection.d.ts line 34](https://github.com/microsoft/TypeScript/blob/main/src/lib/es2015.collection.d.ts#L34)). There's no such thing for `ReadonlyMap`. It can't narrow to both `Map<>` and `ReadonlyMap<>`.

**Comment by cevr** [comment]
I see. It's something that can easily worked around in code, I figured it might be possible to make it easier to work with these interfaces in library code.

**Comment by robbiespeed** [comment]
Related issue for readonly arrays: https://github.com/microsoft/TypeScript/issues/17002

You can get it to narrow properly for your toCollection function by excluding readonly types from the isX functions here, [playground link](https://www.typescriptlang.org/play?target=7#code/FAUwHgDg9gTgLgAgGYFcB2BjOBLKaFxQDCUANqSFrmgDwAqAfABQBuAhqSiAFwJ0CUvOgnBwQaACYBnBABlsUuPIDWIGtjRIQMBADUGCAPx6A2gF0EQkWDGSZAJUqwJKtRq079RhI4zOaijAaAOYANHoGvGggLNoIAN7ACAjYSEwK8oqurBxc-PwJSckpaeycICloimyYIFBICADKIHAFicXFMC0oMPgmAHSDZVxmRckAvmMIAPTTBAAWFV1SKKQ4aMEEAJ4QFWhQCKR4wXEaGJwSIA4gbBJ4pFvNcFNdcD34wyBFk8mp6VK+ZzZT75QodP6fSrVWr1BAAWTYEDaU2Sr3eCAA8gAjABWlDg-SQMCgAFsAKJoOBBK45cr9cRU7A0-JTH7FWYLJZXVbrTZwHZ7A5HDanTAXK4+G53NAPBEQF7dXoIT7fYBFODzYkAdwQ0R1ZJgxJgTAARPtEGwEH5yPjqABaUjYVQm-jASagSCwRD83ZyBRKJ1qRgIAC8RQAPnxzBGmi16AwY45bvctgBBQ1sLbxxNSlNPeMAbjV4Gg8G2vsBMBcgfjoZzfirAUZG3CjBjcqbQRbfATyUjSelssRnZCrYYReAPoqAH1MgHVLWw32o6Nl-nGBOpwhp5Xqwvg0uEP2nI3AqOe+3h2fuxu1ahMDg8CkpHPXDRU8xPrx0Mp9lq0IIyq5BUCjbq+NYfmCCBokqkIaNCGB1A0TxHpG6YwJm-QKOhma0nkbp3ugVBPgou5vh+eE8AgP5-gBvBwTIO4nnuaiQe00GKvgTBTHBVRwDUiGwnKqFTEwU6wpCIZSQgJpQLi+ImggABkSkokB5QIAAhNJaCrKQymqR0ySaThWxYVIpmUQUKlqZplFQvxMLIS0LLJPwRaTEAA). Which makes more sense anyway in this particular case since readonly types are not readonly at runtime.

**Comment by MartinJohns** [comment]
> since readonly types are not readonly at runtime.

Always important to point out that "readonly" only means "readonly via this interface", it does not mean immutable.

**Comment by RyanCavanaugh** [comment]
Not being a `Map` doesn't mean something isn't a `ReadonlyMap`, the same way that something not being a dog doesn't mean it's not an animal.
