### ISSUE TITLE
Error "Could not resolve" when trying to use an enum defined in a .d.ts file

### ISSUE THREAD

**Issue by Woodz** [microsoft/TypeScript#53807]
# Bug Report

### 🔎 Search Terms

"could not resolve" file .d.ts

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because it is not easy to reproduce

### ⏯ Playground Link

Not possible due to TS Playground not supporting multiple files

### 💻 Code

`foo.d.ts`
```ts
export enum Foo {
  Test = 'test'
}
```

```ts
import { Foo } from './foo'

// Using as a type is fine
let foo: Foo;

// Using as a value causes issues
Foo
```

### 🙁 Actual behavior

If you try to use a type defined in a `.d.ts` file as a value, tsc fails with `ERROR: Could not resolve "./foo"`, which is very misleading because `./foo.d.ts` exists.

### 🙂 Expected behavior

The error message should explain that types imported from a `.d.ts` file cannot be used as values

**Comment by fatcerberus** [comment]
Actually it's not even just that the error message is misleading, but that *this shouldn't be an error at all.*  Enums have runtime representation and you haven't used `import type`, so if the type-level reference is valid, the value-space one should be as well.

**Comment by fatcerberus** [comment]
...unless what you're actually seeing is a *runtime error*, in which case that's because your `.d.ts` says it exports an enum, which is supposed to have value representation and is expected to be implemented in an accompanying `foo.js` (which you haven't mentioned existing).  There is no such thing as a type-only module in TS.

**Comment by MartinJohns** [comment]
That's not an error by TypeScript.

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
