### ISSUE TITLE
Add --ignore-unrecognized-flags option

### ISSUE THREAD

**Issue by re222dv** [Microsoft/TypeScript#5393]
Now that #5231 I have a hard time using the latest version.
Atom complains that I need the flag to use async/await but the compiler errors if I do.

A `--ignore-unrecognized-flags` would be nice so one could pass newly removed options until other tools have been updated.

**Comment by mhegazy** [comment]
The behavior is intentional to avoid having misspelled compiler options go unchecked.

In this specific case, we can put pack the flag as "known", but not require it, for a release or so, until all tools have moved on.

Before i do this, i would like to know what is the issue here, @basarat any idea why this would be an issue with atom? would that be something fixed by taking latest from master of release-1.7 branch.

**Comment by basarat** [comment]
> would that be something fixed by taking latest from master of release-1.7 branch.

Yes definitely, mostly waiting on two bugs (linked here https://github.com/TypeStrong/atom-typescript/issues/663) : https://github.com/Microsoft/TypeScript/issues/5278 (labeled as a bug needing fixing) & https://github.com/Microsoft/TypeScript/issues/5110 (not reproduced cause I don't have the test files ... so will probably update even without this)

**Comment by Pajn** [comment]
>The behavior is intentional to avoid having misspelled compiler options go unchecked.
The default behaviour yes, but this is a request for a flag to circumvent this behaviour.
Even if this specific case is fixed, it will probably pop up again when other flags are removed. Having a flag that can be set in those cases would make it easier for everyone. You doesn't need to keep "ghost flags" around and we can workaround this kind of problems instead of rolling back the version.

**Comment by mhegazy** [comment]
I understand the issue, but i do not think the proposed solution of a new flag solves it, it just hides the problem. We will get #5278 fixed today, and that will unblock @basarat. and moving on will take a a more gradual approach to removing flags to make sure non one runs into this again.

**Comment by mhegazy** [comment]
We keep the original issue in mind in the future. we should have a better deprication story for flags. sorry for the trouble. but i believe now migrating to latest atom-typescript safely.
