### ISSUE TITLE
Generic types do not propagate into inherited class expressions

### ISSUE THREAD

**Issue by russpowers** [Microsoft/TypeScript#5400]
When using `extends` in a class expression, the generic types do not propagate correctly to the super class of the expression.   The below example should compile (I think!), but fails with `Type 'C' is not assignable to type 'T'`.

```
class A<T> {
	genericVar: T
}

function B<T>() {
	return class extends A<T> {
	}
}

class C extends B<C>() {
	name: string;
}

var c = new C();
c.genericVar = c;
```

**Comment by mhegazy** [comment]
@sandersn can you take a look.

**Comment by sandersn** [comment]
Here's a simpler repro that illustrates that the problem is a lack of type argument capture/application for anonymous classes:

```ts
class A<T> {
	genericVar: T
}

function B<U>() {
	return class extends A<U> {
	}
}

class C extends B<number>() {
	name: string;
}

var c = new C();
c.genericVar = 12;
```

It also happens with classes, eg

```ts
class B<U> {
    anon: class extends A<U> { }
}
class C extends (new B<number>().anon) { ...
```

`class extends A<U>` captures `U` correctly. But when `C extends B<number>()` is evaluated, the compiler currently applies the type argument `number` to `B` but not to its return type. I'm not yet sure if it's an oversight in how `extends` is checked or in how anonymous classes are checked.

**Comment by sandersn** [comment]
This also fails, so it's not the anonymity of the class that's causing the failure:

```ts
function B<U>() {
    class Inner extends A<U> {
    }
    return Inner;
}
```

**Comment by sandersn** [comment]
As a workaround, you can return a type that has unbound type parameters. Then apply your type to that instead of to the containing function:

```ts
function B() {
    return class Inner<U> extends A<U> {
    };
}
class C extends B()<C> {
}
```

**Comment by russpowers** [comment]
Thanks for looking into this, and for the workaround!  I had no idea it was possible to apply a type parameter to a value returned by a function.

**Comment by sandersn** [comment]
Everybody who's seen it seemed surprised. :)
