### ISSUE TITLE
ConstructorParameters doesn't work with class alias 

### ISSUE THREAD

**Issue by hheimerd** [microsoft/TypeScript#54007]
# Bug Report

### 🔎 Search Terms

typeof doesn't work with class alias 
only refers to a type, but is being used as a value here
Use ConstructorParameters with class alias

### 🕗 Version & Regression Information

I tested it on 5.0.4 and nightly

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230424#code/MYGwhgzhAEDCAqBPADgU2gbwL4CgcBcV14wAnAc1X2gF5MdpoAzAS1RABMAuOJNHXASK8iAQRAtItaCQpUA2gHJW7DooC6AbiFo44KH3R0AdqgDu0ABQA6W2XIQeYY4gCUtAHzRnibTvQAkhAAymAAtkYiaOKSMKgAHvioxhwwCMIA-ND4pACu6DymAG6opNqEukEAcgD2+KER0unRElIJSSkwFag1TFHoWTn50IWoJWV43dBBAKKkpDWk0t29-TGQ5cLweagA8qSiLstEq82o63GJyal6kBCG0IM7I9DFpZu6VWOlTYYX0O1rml9PdMtlnqNxn4pgARGqoCDGfAAdUWAGsmjVjBAhsB8IsAApkcJUUoQAA8ZwuXgAPnAsTi8njCcSIklSBSVn0qa0ILTptj8M5gKhDJS-ryPDggA)

### 💻 Code

```ts
class CType {}

type Target = {
  field: CType
}

type CTypeAlias = Target['field'];
type ClassType = new (...args: any) => any;

type IsSame = CTypeAlias extends CType ? true : never;
type IsNotSame = CTypeAlias extends typeof CType ? true : never;

type IsError = typeof CTypeAlias;
type TrueOrAny = typeof CTypeAlias extends ClassType ? true : never;
type Never = CTypeAlias extends ClassType ? true : never;

type DoesntWork = ConstructorParameters<CTypeAlias> | ConstructorParameters<typeof CTypeAlias> | InstanceType<CTypeAlias>
```

### 🙁 Actual behavior

I get the error "only refers to a type, but is being used as a value here" when trying to call typeof on a class alias.
I get the error "does not satisfy the constraint 'abstract new (...args: any) => any'" when trying to use ConstructorParameters with class alias.

### 🙂 Expected behavior

I want to get either a class type or a real alias for the class with all its features, such as typeof. The type description specifies the Initial type of this type, but if you use the value of the Initial type, then it will have more possibilities. If you get the class type via typeof, it will also have more features than the class alias. As a result, the alias of the class is neither the class itself nor the typeof the class, but it is equivalent in type to the Initial type.

P.S.
I'm sure it's a duplicate. But I did my best to find it, but I didn't find it. So I apologize in advance

**Comment by MartinJohns** [comment]
`type` aliases are just that: type aliases. They don't represent values. However, a class definition is **both** a type and a value. This is working as intended.

**Comment by fatcerberus** [comment]
I wish there was another duplicate to link to for this.  I forgot how much of a trainwreck #50897 was, geez.

Anyway, just to clear up any confusion: `typeof` isn’t the “static side of a class” operator, but rather the “what is the type of this thing I can access in value-space” operator (so you can also use it to get, e.g. the type of a local variable).  `type` doesn’t create anything in value-space, which is why this doesn’t work.

**Comment by hheimerd** [comment]
Thanks for the answers. That is, by analogy with static fields, I can't get constructor arguments, since the constructor is a static method? That is, there is no way to infer the types of constructor arguments if you don't know the concrete class (as in the case of the inferred class)?

In webstorm I get an error in this expression:
```typescript 
typeof CTypeAlias extends ClassType ? true : never;
```
but the resulting type displays true, that is, typescript is capable of this if you remove the error
![image](https://user-images.githubusercontent.com/38163258/234815525-cb1fd7e4-0874-4545-8bdb-a6d6d344269f.png)

However, ConstructorParameters returns type P from its declaration 
```typescript 
type ConstructorParameters<T extends abstract new (...args: any) => any> = T extends abstract new (...args: infer P) => any ? P : never;
```
![image](https://user-images.githubusercontent.com/38163258/234816121-001899cd-f39c-4993-bcfc-e1ea451988c9.png)

**Comment by hheimerd** [comment]
[MartinJohns](https://github.com/MartinJohns), I can't use const in my case since the class type is inferred

**Comment by fatcerberus** [comment]
`typeof CTypeAlias` doesn’t make any grammatical sense because `CTypeAlias` isn’t something you can refer to at runtime.  It only exists in type space and `typeof` doesn’t accept a type identifier.  The confusion here is that a class definition creates *two* separate identifiers - one in expression space that refers to the constructor (what you’re referring to when you say `new Class()`) and a separate one in type space that refers to the type *returned* by the constructor.  They are related, but linguistically distinct.

`typeof x` means, if I write e.g. `console.log(x)`, what is the type of `x`.

**Comment by fatcerberus** [comment]
@hheimerd Long story short, your suspicion is correct: if all you have is the instance type of a class, you can’t use that to recover the constructor type.
