### ISSUE TITLE
Calling recursively Generic<infer T>, the T becomes any

### ISSUE THREAD

**Issue by CptFabulouso** [microsoft/TypeScript#54151]
# Bug Report

Please refer to the playground, I am not able to explain the issue very much. Possibly that when calling a type recursively, which has infered generic param type, than the infered type becomes `any` at 2 levels deep.

### 🔎 Search Terms

- typescript recursive infered generic param is any
- typescript infer results to any
- typescript generic infer any
- type inference changes nested mapped types issue

### 🕗 Version & Regression Information

Since version 4.8.x

- This changed between versions 4.7 and 4.8

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.4#code/PTAEAsFMBsAdIE4GcBQAXAnvUA5AhgG4CWA5nmgPYIDKAxgpJAHYAKeCeAtkgDxsecAMkSRoAfKAC8oAN4pQC0EnqMmAfgBcoJpAKIA3PMWx2XJJu26DRhUSZE0RPNAs69CQ4tAm04C6IQ7EkMAX1AAH1kbUABtACUKAFc0SHxOSFA7UABrSAwKADNQfi5hUQBdLTkvL2UGZi0E5NSuSE8ahRMBJC0SoRE0eKSUtMhy9o67BycXLQAjCgpoSDwmCZqfPy0AoPWQ0Jjc-KK+srRxlHQsDLZfAGEKJgLSPlN+0VBIAA8UpgATJCyEISaRyACQdVU5l65HADyepAAsnhYK8BGcxCgwVNHM4miNWhYjoVim8zigQpdMNhbnDHs8SMjUacBp8fswAUCQVEvENmqNMkwcnkSSyKhYcI8cIloNA8HNlmjSgM+QT0uUJN9fpz8MQyJQaCpmH1eHYCohQAAVNnawEyYGgNRKNCBJgkCKk+70l6WiTbF1BD0AeU4DleXoRJB49rEABpQABySHMJAJj0JnEzfEtdIJsShQwoECgRJIPAkSBXbAJChoXVSKJghCLNBaXWkchUOj1VhvXjgsHLPTQACMbcIHYN3dUJujWLBg6s0AATFV5wukBR0kHYI5Hv7XSR15SF8CsWfKShaI8PkxCPCGTCIwymTwa3XCNzwc3a2uF5m8WGHNIC0BMhxgEcE1jedkyYHpGwXcDRz-BdsXsXFoGzUZQKQ5coPXCEjTglDUNwkjUJAAiwRCaDUOo2jTwYmjz2gykgA)
This issue arrises in react-navigation ([issue](https://github.com/react-navigation/react-navigation/issues/9897)) I extracted the relevant code and removed unnecessary parts. 
I don't understand the need for the union in the NavigatorScreenParams type, but it is necessary in order for it to work correctly.
I tried simplifying it even more by removing the dependency on NavigatorScreenParams, but the `level1` always resolved to `any`, therefore I think it's a bug and not a wrong type definition.

### 💻 Code

```ts
// helpers
type NavigatorScreenParams<ParamList> = {
    screen?: never;
    params?: never;
} | {
    [RouteName in keyof ParamList]: {
        screen: RouteName;
        params: ParamList[RouteName];
    };
}[keyof ParamList];

type PathConfig<ParamList extends {}> = {
	screens?: PathConfigMap<ParamList>
	initialRouteName?: keyof ParamList
}

type PathConfigMap<ParamList extends {}> = {
    [RouteName in keyof ParamList]?: NonNullable<ParamList[RouteName]> extends NavigatorScreenParams<infer T extends {}> ? string | PathConfig<T> : string | Omit<PathConfig<{}>, 'screens' | 'initialRouteName'>;
};

// usage
type RootNav = {
	root: NavigatorScreenParams<{
		level1: NavigatorScreenParams<{
			level2: {
				someOption: string
			}
		}>
	}>
}

const navConfig: PathConfigMap<RootNav> = {
	root: {
		initialRouteName: 'level1',
		screens: {
			level1: {
				initialRouteName: 'level2',
				screens: {
					level2: {
						//
					},
				},
			},
		},
	},
}

```

### 🙁 Actual behavior

From the playground, with TS 4.8.4 and above which has the result as:
<img width="340" alt="Snímek obrazovky 2023-05-05 v 15 07 29" src="https://user-images.githubusercontent.com/25827002/236468002-78f0049a-e976-49cd-ab3f-20a7098de6e7.png">

### 🙂 Expected behavior

From the playground, with TS 4.7.4 which has the correct result as:
<img width="354" alt="Snímek obrazovky 2023-05-05 v 15 07 11" src="https://user-images.githubusercontent.com/25827002/236467916-7362c8b2-3c19-476d-b21d-6437c8252e88.png">

**Comment by ahejlsberg** [comment]
The root cause of the issue here is that the conditional type in `PathConfigMap` relies on inference to a "lossy" generic type. Specifically, inference to `NavigatorScreenParams<infer T>` only works when the source type is exactly a type with an associated `NavigatorScreenParams<XXX>` alias, in which case we can simply infer from the `XXX` type argument to `T`. If the source type is structurally equivalent, but doesn't have a `NavigatorScreenParams<XXX>` alias, inference fails because the type uses the type parameter in a manner that isn't reversible (i.e. `ParamList` never occurs as the exact type of some location in the type, rather its property names and types are spread out in a union of new object types).

Between 4.7 and 4.8 we changed the definition of `NonNullable<T>` to be an intersection `T & {}` instead of a conditional type. This had the side effect of sometimes associating the alias `NonNullable<YYY>` with a type where previously we wouldn't have done so (because we have a slight difference in handling type aliases in instantiations of intersection vs. conditional types). That gets us to the problem here: The conditional type infers from `NonNullable<YYY>` to `NavigatorScreenParams<infer T>`, which only works when `YYY` is a type with a `NavigatorScreenParams<XXX>` alias _and_ `NonNullable` doesn't associate a new alias with the type. In 4.7 it didn't, but in 4.8 and later it does. So, we attempt to infer from `NonNullable<NavigatorScreenParams<XXX>>`, which doesn't work because the outer aliases no longer match.

The easy workaround is to simplify the conditional type to just

```ts
type PathConfigMap<ParamList extends {}> = {
    [RouteName in keyof ParamList]?: ParamList[RouteName] extends NavigatorScreenParams<infer T extends {}> ? ...;
};
```

That is, get rid of the `NonNullable` that isn't needed anyway. Alternatively, if there are cases where non-nulling is actually needed, use a local definition that's similar to 4.7:

```
type NonNull<T> = T extends null | undefined ? never : T;
```

That said, longer term it would probably be better to devise a "non-lossy" definition of `NavigatorScreenParams<ParamList>` that allows inference to succeed structurally.
