### ISSUE TITLE
Disjunction with boolean doesn't include true in union

### ISSUE THREAD

**Issue by cefn** [microsoft/TypeScript#54168]
# Bug Report

Following up on a Stackoverflow report which seems like an inference problem.

https://stackoverflow.com/questions/76192267/typescript-inferred-type-of-expression-with-or

The code example included below logs "disjunction === true is true" but the type of disjunction is inferred as `{}` not `true | {}` as we expected. Consequently the type `{}` is being assigned to something which can easily be of type `true` instead.

### 🔎 Search Terms

disjunction union boolean true

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about disjunction and boolean.

### ⏯ Playground Link

![image](https://user-images.githubusercontent.com/159819/236675805-d5aae70d-9b70-4663-8593-48b79d70754b.png)

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBMAWBTYBrGBeGUBOBXRMAhhDAEYggA2ihYA3AFBOiSwAmAlhAFa5jBQO4DHCSoYAHwkwA3gF9m4aDEQAPAA7YRAIk48+AoWAzpMOfNoYsIVRADpKIAOYAKAAYASGWs1yYXGC9EADdCShcfbABKOTcooA)

### 💻 Code

```ts
const check = true as boolean;

const disjunction = check || {}

const expr = "disjunction === true"
console.log(`${expr} is ${eval(expr)}`)
```

### 🙁 Actual behavior

Type of the disjunction is inferred only as potentially being the second operand.

### 🙂 Expected behavior

Type of the disjunction should be inferred as being either `true` or the second operand.

**Comment by MartinJohns** [comment]
`{}` is a supertype of `true`. The type of your expression would be `boolean | {}`, which then gets simplified to `{}`.

**Comment by cefn** [comment]
Hey thanks for clarifying the situation for me! 

I think the type of the expression would be `true | {}` though, as `false` would be erased by 'falling through' to `{}` if I understand the code path analysis correctly. 

However, with `{}`and `true` structurally identical and if the treatment of true's primitive nature doesn't prevent it, I can see how they would coalesce. It becomes equivalent to `const car` below which is not of type `Car | FastCar` it's just `Car`. 

I understand from this that we shouldn't expect superclasses in unions to be treated like the similar-looking Dog vs Car case that follows, where the union keeps them distinct. 

```ts
class Car {
  public vroom(){}
}

class FastCar extends Car {
  public vroomvroom(){}
}

function createCar(fast:boolean){
  return fast? new FastCar() : new Car();
}

// type Car
const car = createCar(true);
```

```
class Car {
  public vroom(){}
}

class Dog {
  public woof(){}
}

function createThing(animal:boolean){
  return animal? new Dog() : new Car();
}

// type Car | Dog
const car = createThing(true);
```

**Comment by fatcerberus** [comment]
@cefn Yeah, it’s a common misconception that `{}` means only non-primitives - it’s actually the “everything except `null` and `undefined`” type (unless strictNullChecks is disabled, then it’s just a full-on top type) due to structural typing.

**Comment by jcalz** [comment]
Note that the SO question it came from still has the open question: why does the compiler reduce `disj` to `A` but leave `conj` as `false | A` in

```ts
const check = true as boolean;
class A {}
const a = new A()
const conj = check && a; // false | A
const disj = check || a; // A
```
[Playground link to code](https://www.typescriptlang.org/play?#code/HYQwtgpgzgDiDGEAEA5A9gZQC4CcCu8WeOyA3gFBJVLxrBRY0AWE8A1kgLxK57IhQkAIzRoANhBDAA3JWrwxAwQEEkpJAF85VWvUYguSYBADuSZQAoAlNpp0Gd4ACtD8FuyQAyT0hDSkAPQBSABmIGJQyAA+5ra6DgAmAJZQLtxurBxRMX6Bwcrk5FrkoJCwCMjY+ITEZHH2jBke3Lz8giLikjJxilAqakgAXoYAjJr1er6GxmaWNtSODrppzJlePrlBoeGRSDEFC-GMyamu7lk5-lute7FF5EA)

In some sense the answer is "who cares, it's an implementation detail whether and when the compiler decides to reduce reducible unions", and if you add some structure to `A` you get `true | A` for `disj` also, so it's not doing anything *wrong*.  Still I wonder how we're supposed to answer the original question, and since you went through the trouble of filing an issue about it I'd've been curious to hear an official word on the matter. But it's closed so that probably won't happen.

**Comment by fatcerberus** [comment]
@jcalz

> who cares, it's an implementation detail whether and when the compiler decides to reduce reducible unions
 
Ryan has said pretty much exactly this, but unironically, in other issues.  The handwave tends to be something along the lines of "subtype reduction can happen at any time, but is not *required* to happen either."  I'm pretty sure the type system is so complex at this point, due to years of pragmatic changes without a normative spec, that nobody really understands the rules anymore except in the abstract.
