### ISSUE TITLE
Impossible to define static property `name` in classes

### ISSUE THREAD

**Issue by alex-kinokon** [microsoft/TypeScript#54193]
# Bug Report

### 🔎 Search Terms
Static class property, static initialization blocks, ts(2699)

**Related issue:** #442 (issue) and #12065 (PR). It seems that 2699 is supposedly be emitted only for compilation target ES5 or lower, but this is reproducible with ESNext. 

### 🕗 Version & Regression Information
5.0.4

This is the behavior in every version I tried, and I reviewed the FAQ.

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?target=99#code/MYGwhgzhAECC0G8BQ1XQgFzBglsaAdmALYCm0AvNAETVIC+QA)

### 💻 Code

```ts
class A {
  static name = "";
}
```

This code works exactly as expected on Chrome 112, Firefox 113 and Node v18.15.0. `A.name` evaluates to `""`.

### 🙁 Actual behavior
Two separate issues here:

1. Static property 'name' conflicts with built-in property 'Function.name' of constructor function 'A'.(2699)
2. The compiled result when `target` is set to ESNext is `class A { static { this.name = ""; } }`, which causes a TypeError crash in runtime.

### 🙂 Expected behavior

It should produce neither a 2699 error nor invalid code.

**Comment by fatcerberus** [comment]
# 2 is solved by enabling `useDefineForClassFields` in the Playground (in a normal workflow, that's enabled by default when targeting ESNext).  With useDefineForClassFields *turned off*, the TS2699 error is correct exactly *because* you've opted out of `[[Define]]` semantics and using `[[Set]]` semantics to set the property is a runtime error.  The code in the OP could probably be allowed with it *turned on*, however.
