### ISSUE TITLE
Type guard "in" for undefined not working when using strictNullChecks + noUncheckedIndexedAccess

### ISSUE THREAD

**Issue by kkmuffme** [microsoft/TypeScript#54241]
# Bug Report

type guard in undefined array indexed access

### 🕗 Version & Regression Information

- This changed from version 4 with the introduction of noUncheckedIndexedAccess
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&filetype=ts#code/FAYw9gdgzgLgBAQwEYgFxwEoFNwCcAmAPLLgJYQDmANCeRQHxwC8cA3gL4DcwwAZgK4QQMUpDhIEuABSJcFdLUpwAlG2BwNcUrzgzJFLREQoVazebjho8fAhgJmxkAG1ZBgLrdz7YD6A

### 💻 Code

```ts
const abc: Record<string,string> = {};

function bar( arg: string ) {
    if ( arg in abc ) {
        const data = abc[ arg ];
    }
}
```

### 🙁 Actual behavior

data is `string|undefined` despite it being typeguarded with "in" on a `Record<string, string>` which means that it cannot be `undefined`

### 🙂 Expected behavior

`data` should be `string`

The current bug causes either lots of redundant code (as we have to typeguard for undefined again separately) or disabling `noUncheckedIndexAccess` which would snooze tons of potential bugs though.

**Comment by jcalz** [comment]
Being tracked at #10530.  The issue is that `arg` is of type `string` and not a string literal type.  Observe the difference:

```ts
const abc: Record<string, string> = {};
function bar() {
    const arg = "k"
    if (arg in abc) {
        const data = abc[arg];
        // const data: string
    }
}
```
Until and unless #10530 is fully resolved, the most ergonomic way to do what you're doing is to give up on `in` and just check for `undefined`:

```ts
function baz(arg: string) {
    const data = abc[arg];
    if (data !== undefined) {
        data;
        // const data: string
    }
}
```

[Playground link to code](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&filetype=ts#code/FAYw9gdgzgLgBAQwEYgFxwEoFNwCcAmAPLLgJYQDmANHCeRQHxwC8cA3gL4DcwAZgK4QQMUpDhIEuABQBKdsDiK44aPEkUWcAEQBrLQqWlecKerjlEKOWwNKlK2HHwIYCTchABtdQF0eduwB6QOVIR2dXdDpKWzgOYHi+QWFRCHEEAC9TXAoomDJKa1iHeAi3Vg9vHL9YoxMyuABCZlZBfCxecix8IoClMv8+uGDQ1ScXBDyCilj4xKA)

**Comment by jcalz** [comment]
Sigh, no it's the right issue, it's just that the description isn't quite specific enough anymore.  See #53454 for example.

**Comment by RyanCavanaugh** [comment]
[This was the entire concern of the feature in the first place](https://github.com/microsoft/TypeScript/pull/39560) when we implemented it. People wanted a sound and convenient method to check for array bounds or key inclusion automatically. And we said, "We don't have any way to do that since both index and map array mutation can happen at almost any time," and everyone said, "No, that's fine. We can deal with the inconvenient but sound version, having anything is better than nothing for sure." So that's what we have, and indeed it is inconvenient in some cases.

**Comment by fatcerberus** [comment]
@RyanCavanaugh I suppose there's an argument to be made that naming a feature "no *unchecked* indexed access" was misleading when it errors even in cases where the index is checked (via `in`, e.g.), and the enforced contract is actually that you check the *value* you receive, not the indexed access itself (which can remain unguarded).

But yeah, this is a good case-in-point for why noUncheckedIndexedAccess isn't the default.
