### ISSUE TITLE
The type of the first element of the `[...T[], T]` type is `T | undefined` when `noUncheckedIndexedAccess` is enabled

### ISSUE THREAD

**Issue by ootidea** [microsoft/TypeScript#54420]
# Bug Report

### 🔎 Search Terms

spread array type, first element, undefined, noUncheckedIndexedAccess

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `Array`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&ts=5.0.4#code/PTAEDkHsBcFNWgCwIbQY+A7SBVTBjDfAa1gBMBJTM2AD3IEF99YBnV0SAB2gEtJMoXh1iZkAIwA25ALAAoefgGs0yAE5rkATwBcoANoA6Y5gCuAW3Gw1+gLoAaUGcvXboALwGAjI4BMjgGZbRWU0ADNeNRU9Zys1D1B1TS19AAY3UFAQUAAVLS54azVINQBCXIwEfPhIMMSNbTS3YScLONAAH1BTalgIzFk5IA)

### 💻 Code

```ts
// Note that the noUncheckedIndexedAccess option is enabled

const array: [...number[], number] = [1, 2, 3]
const first: number = array[0]   // Type error! The type of array[0] is number | undefined
```

### 🙁 Actual behavior

The type of `array[0]` is `number | undefined`.

### 🙂 Expected behavior

The type of `array[0]` is `number`.
In general, the type of the first element of the `[...T[], U]` type should be `T | U`.

**Comment by juancarlosbaezpozos** [comment]
Hi, with the noUncheckedIndexedAccess option enabled, TypeScript assumes that indexed access can potentially return undefined if the index is out of bounds. However, in this case, since the array is not empty, accessing array[0] should correctly result in the type number, rather than number | undefined.

Two different approachs in the mean time as workaround :)

Ensure that the array is not empty before accessing its first element:
`const first: number | undefined = array.length > 0 ? array[0] : undefined;`

If you are certain that the array will always have at least one element, you can use a non-null assertion operator (!) to assert that the value will not be undefined:
`const first: number = array[0]!;`

**Comment by ehoogeveen-medweb** [comment]
> Ensure that the array is not empty before accessing its first element: `const first: number | undefined = array.length > 0 ? array[0] : undefined;`

This actually doesn't help - or at least, `array.length` checks do nothing to remove `undefined` from the type of `array[0]`. I wish they would - it would make `noUncheckedIndexedAccess` a lot more usable. But the situation in this issue should be an exception, since `array` is typed to contain at least 1 element.
