### ISSUE TITLE
Tolerate `undefined` as key of `Map`

### ISSUE THREAD

**Issue by ryuujo1573** [microsoft/TypeScript#54528]
# lib Update Request

## Configuration Check

My compilation *target* is `ES2015` and my *lib* is `the default`.

## Sample Code

```ts
function *matchLocalTracks(...ids: (string | undefined)[]) {
  for (const id of ids) {
    if (id) {
      yield this.localTracksMap.get(id)
    } else {
      yield undefined
    }
  }
}
```
becomes:
```ts
function *matchLocalTracks(...ids: (string | undefined)[]) {
  for (const id of ids) {
    yield this.localTracksMap.get(id)
  }
}```

<!--
  What's some code using this that should work, but doesn't?
-->

## Documentation Link

<!--
  Link to relevant documentation (e.g. MDN, W3C, ECMAScript Spec) to consult for this property.
  Note that lib.dom.d.ts intentionally does not include browser-specific extensions
   or early experimental features.
-->

**Comment by MartinJohns** [comment]
I have no idea what `this.localTracksMap` is. Perhaps you want to update your sample code to something working.

**Comment by MartinJohns** [comment]
From your linked pull request I take it that you mean `Map<K, T>`, and want the `get()` method to accept `undefined` as well. I think that's a bad idea. It's perfectly legal to have `undefined` as a key in your map, and your suggestion could potentially hide bugs. If I say my valid keys are `"a" | "b"`, then I want it to error if I pass in an invalid key (including `undefined`). When my valid keys are `"a" | "b" | undefined`, then `undefined` would be a valid case.

**Comment by RyanCavanaugh** [comment]
This doesn't make any sense. Why allow `undefined` as an extra key here when there's already a type parameter where you could define that value as being acceptable? We might as well add `0`, the empty string, or `null`; there's no rhyme or reason why `undefined` should be the only additional out-of-band type allowed there. If you can augment your DTS to add whatever you want, but this isn't an appropriate change for TypeScript itself.

**Comment by kaluginserg** [comment]
@MartinJohns 

Let's have a case:

``` js
function do(entity?: {id: number}) {
  const _map = new Map<number, number>()
  const val = _map.get(entity?.id) // <<<<< here typescript inconvenient error
  if(val != null) {
      .....
}
```

The `Map.get(value)` in fact allows us to use undefined and it is very useful, and it does not violate the strict principles of the Map.

How to handle In the current implementation:
``` js
// weak (bad) solution1 !: bad non null assertion!
  const val = _map.get(entity?.id!)

// weak (bad) solution2 !: bad 'as' keyword
  const val = _map.get(entity?.id as number)

// weak (bad) solution3 !: unnecessary condition for runtime, decrease performance
  if(entity?.id === undefined){ ... } else {
  const val = _map.get(entity.id)

// weak (bad) solution4 !: unnecessary weak key declaration, that decrease strict checks for .set, .foreach etc.
  const _map = new Map<number | undefined, number>()
```

We expect that this typescript **won't** declare new behavior for Map, in fact, Map allows us to pass undefined as an argument, specification allows it, and all browsers and node.js allows it.
And it is useful, as we no need aditional `if` condition, because in case of undefined it will return undefined.
BTW it is not only about `.get()`, but also about `.has()` - those operations won't change the state of Map. Also they will return `undefined` as a result if something is not found.

How it could be done in proper way with the current interface?
Another question about the current `get(key: K): V | undefined;` - how it helps with type safety for key? Any cases and examples? @MartinJohns

**Comment by RyanCavanaugh** [comment]
Not allowing `undefined` in this argument position has been the behavior for at least six years now, and this is the first we've seen where someone didn't like it. So I think it's pretty safe to say that most people prefer to have some null safety here as compared to more convenience.

**Comment by ryuujo1573** [comment]
After consideration, I would agree that this is not an appropriate change. 
And thanks for the workaround example provided by @RyanCavanaugh 

> ```ts
> interface Map<K, V> {
>     get(k: undefined | K): V | undefined;
> }
> ```

This practice is much more better than what I've come up with: add `!` assertions everywhere.
This is not causing any runtime error for that underground JS allows me to do `map.get(undefined)`.

Thanks for all your replies. ❤️
