### ISSUE TITLE
Type `new () => T` replaces type `{ prototype: T }` with `{ prototype: any }` from an intersection

### ISSUE THREAD

**Issue by ajvincent** [microsoft/TypeScript#54585]
# Bug Report

### 🔎 Search Terms

`is:issue prototype new is:open `

I did read over the open issue summaries matching these terms, and I wasn't able to find a match.  That said, I would be very surprised if this wasn't a duplicate.  I just couldn't find it.

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about new and prototype
- I tested it as far back as version 3.3.3333, and as recently as v5.2.0-dev.20230608

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=99&jsx=0&ts=5.2.0-dev.20230608#code/PTCWFsAcHsCcBcAEBveBPSBTRBhANgIYDORANLtAHZHywCuAxvHIgL6IBms04iAROiwBaDphp8A3AChB2fMSIAeACrkAgrADmdcJkrwiiTAA94egCaG6lANaVoAd0oBtALqIAvIgKU0bgHyeFNS0jMywKupaOnoGgQBkKJDczLIAXIjKrNKywTT0THCRiBrauvqGJmaUlojWdo4u7l4+fq6BXpSYDgAUAHQDBNHlBgD6GaUxFQCUnoHK0jIY2AByOgBGmLAAyrSglJrKy0HIUojniLCYWATwAGJwDkPmPUQZ+fua5JQZlBtb03eewO0gul2umFuACECAwbD0fog-uBNrByG9EB8DoDMcDNNJslIllhEAANIIABVAcMU8hIijWKK2u1gnyOWH85BsmDQ0A4uEI9MZqJZbOW-n80hAFwAegB+KRAA)

### 💻 Code

```ts
//import {type Class, Constructor } from "type-fest";
type Class<T, Arguments extends unknown[] = any[]> = Constructor<T, Arguments> & {prototype: T};
type Constructor<T, Arguments extends unknown[] = any[]> = new(...arguments_: Arguments) => T;

type NumberStringType = {
    repeatForward(s: string, n: number): string;
    repeatBack(n: number, s: string): string;
};

type X = Pick<Class<NumberStringType>, keyof Class<NumberStringType>>;
//   ^?
```

### 🙁 Actual behavior

`X` is `{ prototype: any }`

### 🙂 Expected behavior

`X` is `{ prototype: NumberStringType }`

Edit: updated playground because I just plain did it wrong

**Comment by jcalz** [comment]
Looks like construct signatures just inherit `{ prototype: any }` from `Function`, and therefore intersecting will give you `any`.  If there's a bug or missing feature here it's that construct signatures don't get a stronger `prototype` property automatically... but then you wouldn't need to intersect in the first place.  If I were trying to do this I'd use a single object type or interface extension instead of intersecting:

```ts
interface Class<T, A extends unknown[] = any[]> {
    new(...args: A): T;
    prototype: T
}
```
[Playground](https://www.typescriptlang.org/play?target=99&jsx=0&ts=5.1.3#code/JYOwLgpgTgZghgYwgAgMIBs4GcsB4AqANMgILIQAekIAJlsgK4gDWIA9gO4gDaAusgF5kcEAE8+APmQBvAFDIFyEBA4AKAHSa4UAOZYAXKQCUh-AG55igA5Q2YO6KsRTsgL6zZYRygByDALYARtAAymBQoDr43oIylgpQEE5wYABibFAc2jSqBshY4ZHEIIYgAcFQJvmFIDoWisiJyWAAQojMqiVK5dDEeQURtVUDkRauFp4xABqxAArACMy4GNh4fkGhNVHeEsTMEKJsMGiYOLjrFWGD204SEhYA9A+KAHoA-EA)

**Comment by RyanCavanaugh** [comment]
@jcalz is correct

You prboably should write
```ts
type Class<T, Arguments extends unknown[] = any[]> = Omit<Constructor<T, Arguments>, 'prototype'> & {prototype: T};
```
