### ISSUE TITLE
Generic inference of union is different when the generic type is nested. 

### ISSUE THREAD

**Issue by JeanMeche** [microsoft/TypeScript#54626]
# Bug Report

### 🔎 Search Terms

* generic
* inference
* union

### 🕗 Version & Regression Information

Not a regression, tested on 5.1 and 4.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.3#code/CYUwxgNghgTiAEYD2A7AzgF3gNwFzwCIoD4AfQgIwIG4BYAKAdElgQDMBXFMDAS1XhsAPABUANPACq8EAA8MIFMDTwA3gF8y8AAwA+ABQN4x+Bnzj4SfKvgd809QwCU+ANoXJAXTqN6ydFhsSEjwALyC+tgSNnbwAORQcfDqTgwA9Gkm8AB6APwMDP6YgsEATGERUWq2+AlJUCpFWCnwGfAA7kgwANawSFzA6ZkmeQX0GROTU2PM0HCCXDz8KPAA5qIS0nIKSioaWnqG9Flm8Baxks5uHt5jTSVIAMwVq5ESdanjw8Z5QA)

### 💻 Code

```ts
declare const v: "a" | "b";

declare function f<T, U extends {} | 0>(
    t: T, o: { u: U }
): [T, U];

const foo = f(v, { u: 'a' })
const foo2 = f(v, { u: 'a' as const }) // workaround

//////////////

declare function g<T, U extends {} | 0>(
    t: T, u: U
): [T, U];

const foo3 = g(v, 'a')
```

### 🙁 Actual behavior

`foo` is infered as `["a" | "b" , string]`

### 🙂 Expected behavior

`foo` is infered as `["a" | "b" , "a"]` like in the non-nested example (`foo3`)

**Comment by RyanCavanaugh** [comment]
This is consistent with other places where object properties and bare values have different behavior

**Comment by jcalz** [comment]
In [the Stack Overflow question this seems to be based on](https://stackoverflow.com/q/76460318/2887218) the original constraint was more like `U extends T | 0` instead of `U extends {} | 0`.  Presumably the same behavior is happening there too:

```ts
declare const v: "a" | "b";
declare function f<T, U extends T | 0>(t: T, o: { u: U }): [T, U];
const foo = f(v, { u: 'a' }) // const foo: ["a" | "b", 0 | "a" | "b"]
declare function g<T, U extends T | 0>(t: T, u: U): [T, U];
const foo3 = g(v, 'a') // const foo3: ["a" | "b", "a"]
```

So the steps are something like
* using another type parameter in a constraint doesn't provide a literal context for whatever that other parameter ends up being inferred as or constrained to (so the fact that `T` is `"a" | "b"` doesn't give `U` a string literal context), so `T | 0` is no better than `{} | 0` in terms of hinting for string literal types
* the argument `{u: "a"}` is widened to `{u: string}`, while the argument `"a"` stays as `"a"`
* when `{u: string}` provides `string` as an inference candidate for `U`, this *fails* because `U` is constrained to `0 | "a" | "b"`.  So `U` falls back to its constraint
* this then *succeeds* because `{u: "a"}` is assignable to `{u: 0 | "a" | "b"}`.

Do I have that right?

**Comment by JeanMeche** [comment]
@fatcerberus oh thanks for the head's up ! 👍
