### ISSUE TITLE
spread error when using tuples within overload signatures

### ISSUE THREAD

**Issue by Enteleform** [microsoft/TypeScript#54812]
# Bug Report

### 🔎 Search Terms

- overload
- spread

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.2.0-dev.20230628#code/C4TwDgpgBAglC8UDaA7ArgWwEYQE4Bop1s8BdAWAChRIoAhBZAZ2FwEsUBzQl9ri6uGgwGiOAB96VKgDM0KAMbA2AexRQZKlQAoAdPoCGuTkwBcMAJSmoANxVsAJlAD0AKigB3FbgDWTTwAWEOq4EBgqNhBOrs6y8kqq6po6+rpGJqZ0Vrb2Tm6e3n6BwVCh4ZHRsZRyispqGlp6hsZmIhYA3gC+0pQKaixQ6f6ISACMhABMpIP+Ij3JTWktFlTOzrBQTGChBk7pmMHAUBhoAxBswEG4UAEGkYNQwGhgADbQNNDeUDhQYAZMTCijxUD1CAz+uAMGAgwDwum0EwArIiAGwWIA)

### 💻 Code

```ts
type A = [number, number]
type B = [string, string]
type AB = A | B

function foo(...args:A): void /* works when removed */
function foo(...args:B): void /* works when removed */
function foo(...args:AB){}

const args = [1, 2] as AB

foo(...args)
// A spread argument must either have a tuple type or be passed to a rest parameter.(2556)
```

### 🙁 Actual behavior

Type Error:
```log
A spread argument must either have a tuple type or be passed to a rest parameter.(2556)
```

### 🙂 Expected behavior

No type errors. All resolutions of the `AB` union are valid tuples and should be spreadable.

**Comment by mkantor** [comment]
Even if this continues to be an error, the message is pretty confusing.  "A spread argument must either have a tuple type or be passed to a rest parameter"… but `args` is a union of tuple types and it is being passed to a rest parameter.

**Comment by fatcerberus** [comment]
> arguably a rest parameter with a fixed length isn't a "real" rest parameter

Fun fact, this isn’t just a “no true Scotsman” quibble - IIRC TS sees no difference between `(...args: [ number, number ])` and `(arg1: number, arg2: number)` at the type level.  As far as the compiler is concerned there is no rest parameter, “real” or otherwise.  This lets you use tuple types to express parameter lists generically.

That said, I’ve agreed for a while that the wording of this error message is confusing in many of the cases where it shows up.

**Comment by RyanCavanaugh** [comment]
Agreed; if someone wants to update the error message that'd be fine
