### ISSUE TITLE
Missing type inference on nested generics

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#5485]
```ts
function f<T>(_: (p: T) => any) {}
function g<T>(_: <U>(p: T) => any) {}

f<void>(p => p); // info: `function f<void>(_: (p: void) => any): void`
                 // info:          `(parameter) p: void` <= match
g<void>(p => p); // info: `function g<void>(_: <U>(p: void) => any): void`
                 // info:             `(parameter) p: any` <= mismatch, should be void

f<void>(p => p = 0); // error
g<void>(p => p = 0); // should be error
```

**Comment by ahejlsberg** [comment]
This is by design. Function expressions and arrow functions are contextually typed only when the corresponding parameter type has a single call signature and that call signature isn't generic ([section 4.10](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#410-function-expressions) in the language specification has the details).

So, in the calls to `g`, the arrow function isn't contextually typed, and `p` is given type `any`. If you compile with `-noImplictAny` we'll report errors in the two calls to `g`.

Is there a particular scenario for which this is a problem?

**Comment by falsandtru** [comment]
Oh... I see. This is my simple use case. I want to restrict a `extract` function signature.

```ts
class Command {
	val: string;
}
class PUT extends Command {
}
class POST extends Command {
}
class Entity {
	cmd: PUT|POST;
}

function f<T extends Object>(
	entity: T,
	extract: <U extends Object>(entity: T) => U,
	Command: new (...args: any[]) => {},
    cb: (entity: T) => any
) {
	if (extract(entity) instanceof Command) {
		cb(entity);
	}
}

f<Entity>(new Entity(), entity => entity.cmd, PUT, e => e); // ok.
f<Entity>(new Entity(), entity => entity.query, PUT, e => e); // should be error because query is not a member.
f<Entity>(new Entity(), entity => 0, PUT, e => e); // should be error because 0 is not a object.
```

**Comment by ahejlsberg** [comment]
I'd suggest you write the `f` function as follows:

```typescript
function f<T extends Object>(
    entity: T,
    extract: (entity: T) => Object,
    Command: new (...args: any[]) => {},
    cb: (entity: T) => any
) {
    if (extract(entity) instanceof Command) {
        cb(entity);
    }
}
```

In other words, get rid of the (unused) type parameter in the `extract` type annotation and contextual typing now kicks in and gives you the expected error. At least for the call involving `entity => entity.query`. There is no error for `entity => 0` because `0` (and any other primitive value) is considered assignable to `Object`. There is no way to specifically exclude primitive types, other that requiring some type with a property that the primitive types don't have.

**Comment by falsandtru** [comment]
> There is no error for `entity => 0` because `0` (and any other primitive value) is considered assignable to Object.

You are right. I was mistaken because primitive values are not an object in javascript (`0 instanceof Object` is false). Thanks for your suggestion!
