### ISSUE TITLE
Support colon after @ts-nocheck and @ts-check

### ISSUE THREAD

**Issue by not-my-profile** [microsoft/TypeScript#54859]
The following directive is recognized:

```
// @ts-nocheck foo
"test" - 1
```
([playground link](https://www.typescriptlang.org/play?#code/PTAEAEBcGcFoDsD2BjAFgU2Qa1AM0YgFCEBEk60kJosoAjEA))

However if the comment directive is followed by a colon it is not recognized: the following code results in a type error:

```
// @ts-nocheck: foo
"test" - 1
```
([playground link](https://www.typescriptlang.org/play?#code/PTAEAEBcGcFoDsD2BjAFgU2QawFygGaKIBQxARJOtJGaLKAIxA))

This is pretty unintuitive considering that the `@ts-ignore` and `@ts-expect-error` comment directives support trailing colons (the following work as expected):

```
// @ts-ignore: this is ignored because ...
// @ts-expect-error: we expect this to fail because ...
```

**Comment by Mateusnasciment** [comment]
The error occurs due to the difference in syntax between the @ts-nocheck and @ts-ignore/@ts-expect-error directives in TypeScript. @ts-nocheck is a standalone directive that disables type checking for the file or section of code. The @ts-ignore and @ts-expect-error directives are used to ignore or expect specific errors in the following lines or blocks of code, requiring the use of a colon. When @ts-nocheck is followed by a colon, TypeScript does not recognize it as a valid directive, resulting in the type error.
