### ISSUE TITLE
Interfaces that extend Symbol can't be used as computed props

### ISSUE THREAD

**Issue by matthew-dean** [microsoft/TypeScript#54885]
# Bug Report

Extending a Symbol allow the variable to be used as a `symbol` key. See:

https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgJIgFYQWYB7EAaQgE9kIAPSEAEwGdkBlEgWwCM8AbZAbwF8AsAChhCAnTDIA1qWQBeJqw6cAFAEpkcBuiw58RUsNHjJMPHnm9hyZAG0ZJALoAuZAHIAbnE4BXCG+E+IA

### 🔎 Search Terms

"extends symbol"

### 🕗 Version & Regression Information

This errors on all versions tried on the TypeScript playground

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgJIgFYQWYB7EAaQgE9kIAPSEAEwGdkBlEgWwCM8AbZAbwF8AsAChhCAnTDIA1qWQBeJqw6cAFAEpkcBuiw58RUsNHjJMPHnm9hyZAG0ZJALoAuZAHIAbnE4BXCG+E+IA)

### 💻 Code

Note: this is an issue because it it means that the recommended pattern in Vue 3 can't be used to inject values in test environments like Vitest without explicitly re-casting to symbol. https://vuejs.org/guide/typescript/composition-api.html#typing-provide-inject

```

### 🙁 Actual behavior

A value that is a symbol, but cast as an interface that extends symbol, is no longer recognized as a symbol.

### 🙂 Expected behavior

Because the interface extends symbol, it should qualify as a symbol key.

**Comment by Andarist** [comment]
> Note: this is an issue because it it means that the recommended pattern in Vue 3 can't be used to inject values in test environments like Vitest without explicitly re-casting to symbol.

Perhaps it would be good to include some code to demo this problem.

Reading the Vue docs we might find this:
> To properly type injected values, Vue provides an InjectionKey interface, which is a generic type that extends Symbol. 

Honestly, it just sounds like an abuse of the compiler - especially given the fact that `T` doesn't appear anywhere in the `InjectionKey`, it's just used as a type param (Vue's source code [here](https://github.com/vuejs/vue/blob/49b6bd4264c25ea41408f066a1835f38bf6fe9f1/src/v3/apiInject.ts#L5))

**Comment by matthew-dean** [comment]
@Andarist 

> Honestly, it just sounds like an abuse of the compiler

I'm not a member of the Vue team, but I'm sure they would love to know a different way to support this pattern:
```
// File 1
provide(key, someValue) // key must be string, number, or symbol

// File 2
inject(key) // return value must be the type of `someValue`
```

Regardless, even though I discovered this _because_ of Vue's API, it's not really about Vue. The issue is: why is an interface that extends symbol not allowed to be used as a key?

> Perhaps it would be good to include some code to demo this problem.

I did? The playground link is most simplified version of the issue.

**Comment by Andarist** [comment]
> I'm not a member of the Vue team, but I'm sure they would love to know a different way to support this pattern:

Perhaps they could reconsider the API. React does a similar thing with its `createContext` and it doesn't suffer from that because the type is "bound" by the `createContext` factory and doesn't have to "provided" to both `Provider` and `useContext` separately. That's a tangent discussion though - but I feel like they are using this pattern to accommodate their API and that with a different API the problem would just go away).

> The issue is: why is an interface that extends symbol not allowed to be used as a key?

Only unique symbols can be used as keys like that. `Symbol()` factory is kinda special for TS and it only returns `unique symbol`s when you call `Symbol()` in the top-level scope. Remember that those might have to be printed in declaration files so it's not that obvious how you'd emit declarations even for this:
```ts
function wrapper() { return Symbol() }
export const obj = {
  [wrapper()]: 1
}
```
What should be the type of `obj`? Remember that each `wrapper` call gives you a new **unique** symbol at runtime so you can't emit something "static" for this.

But either way - this is just a showcase of how symbols are a little bit special. In your case, you are altering (by casting) the type there. `extends Symbol` inherits from the interface, it might inherit all of the properties from there etc but it doesn't inherit the related "primitive type".

This doesn't work either:
```ts
interface InjectionKey extends String {}
declare const key: InjectionKey
const foo = { [key]: 'value' } // error

function accept(a: string) {}
accept(key) // error as well
```

> I did? The playground link is most simplified version of the issue.

I referred to this part: "the recommended pattern in Vue 3 can't be used to inject values in **test environments like Vitest** without explicitly re-casting to symbol"

It seems like usually, Vue users don't suffer from this problem since there are not a lot of issues reported about this here. So I wonder how your use case is different.

**Comment by matthew-dean** [comment]
@Andarist I think you're right. Vue's official TypeScript API for `provide` / `inject` is not great and an abuse of the type system.

I went ahead and made this: https://github.com/matthew-dean/vue-atoms. That seems to solve the type issue and doesn't abuse the type system, so we could probably close this.

> It seems like usually, Vue users don't suffer from this problem since there are not a lot of issues reported about this here. So I wonder how your use case is different.

`provide` and `inject` are fairly new, so not many people use it, I think. Being new, I'm not sure why they designed it by default in a way that's impossible to infer the type, while, as you note, React Context and other state libraries don't have this issue. I think it was just poorly-thought-out.

**Comment by RyanCavanaugh** [comment]
`extends Symbol` is not the same as being a `symbol`; `Symbol` is the global interface that defines which properties are available on `symbol` values.

I would write
```ts
interface InjectionKeyProps {
  idunno: string;
}

const key = Symbol() as (symbol & InjectionKeyProps);

const foo = {
  [key]: 'value'
}
```

**Comment by matthew-dean** [comment]
@RyanCavanaugh I agree, and unfortunately Vue types fail if you do that, so I could open that as a specific Vue types bug. Thanks for feedback!
