### ISSUE TITLE
Incorrect type definition at union

### ISSUE THREAD

**Issue by Sparebola** [microsoft/TypeScript#54913]
# Bug Report

### 🔎 Search Terms

Incorrect type definition at union

### 🕗 Version & Regression Information

For the first time
This is the behavior in every version I tried, and I reviewed the FAQ for entries about possible errors with the
3.3.0 > TS < 5.2.0-dev.20230707

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYOwrgtgBAkiAuwDmwBOUDeAoKV4HcB7KAXigCYAaHPAC1WGFKgGZrcAzASwDcmyArFgC+WLPACeAByYA5SACM0AFWn8oAbXAQlqDQF1KsBMjQA6bn30BucWqgBleKi4gkqmcw0BnZ66RGcIgoqGYExAA+xsHm8PSMNnaeAKogXIQgHuryOir2UU4ublm2WADGGb54AIYKXhoADEYNhlAC+lDV3lCp6ZlqthUgVRpDvtUIRmPwE-BZHWQzCqVcHFAAFNOzWaQkZEGmoeFQEVFbCDt7+yYhYfHAAJSYNGOEADbAZm+ESJuVMxc1FN-rMHrZhFBgG9vExsLgAPTwqDnOZqABc0UOFl4wBoiORIIQGN8RSQJyg2l0BjxSPwtAkAH4mS9Ku9Pt9fiissDhgD4GCRFggA)

### 💻 Code

```ts
enum Integer {
  two = 2,
  three = 3,
  five = 5
}

type NumberType = [number[], Integer.five];
type StringType = [string, Integer.two | Integer.three];
type UnionType = NumberType | StringType;

const tab = [[0, 0], 5] as UnionType;
const [constant, constantType] = tab;

if (constantType === Integer.two || constantType === Integer.three) {
  console.log(constantType, constant);
} else {
  // constantType: Integer.five
  // constant: string | number[]
  // why???
  console.log(constantType, constant);
}

```

### 🙁 Actual behavior

Typescript defines the constantType correctly, but defines the constant type incorrectly. The union type comes out of nowhere

### 🙂 Expected behavior

Сonstant must be number[] type and no other type

**Comment by RyanCavanaugh** [comment]
The problem here is that control flow proceeds on a step-by-step, node-by-node basis, analyzing each variable effectively independently. But if you only analyze this code "step by step", there's no way to narrow `constant` -- it's possibly `string | number[]` after the first `===` since `constantType` might be the other value, but then is also possibly `string | number[]` after the second `===` because  `constantType` might be the *other* other value.
