### ISSUE TITLE
vscode embedded request forward trigger completion command 

### ISSUE THREAD

**Issue by gaoanyuan** [microsoft/TypeScript#54926]
when i use vscode embedded request forward just like
```typescript
 vscode.languages.registerCompletionItemProvider([{ pattern: '**/*.txt' }], {
    async provideCompletionItems(document, position, token, context) {
      const fsPath = document.uri.path.replace('.txt', '.ts')
      const uri = Uri.parse(`content://${fsPath}`)

      const list = await vscode.workspace.openTextDocument(uri).then(document => {
        vscode.languages.setTextDocumentLanguage(document, 'typescript')
        return vscode.commands.executeCommand('vscode.executeCompletionItemProvider', uri, position).then(completionList => {
          // 处理返回的代码补全项
          console.log(completionList)
          return completionList
        })
      })
    },
  })
```
repo: typescript-language-features send file like '^/scheme/ts-nul-authority/c://test/src/hello.ts'
repo: typescript tsserver get this message, and check this file name is dynamic(function isDynamicFileName) because filename first char is '^'
when tsserver try to find config file(tsconfig), the getConfigFileNameForFile function just return undefined because file is dynamic
i want embedded memory file can be to use the project tsconfig file.
Is there anyone who can give me some advice?

**Comment by gaoanyuan** [comment]
Is there anyone who can give me some advice?

**Comment by gaoanyuan** [comment]
I must illegally intrude to modify the following code in order to achieve the desired functionality. The file is dynamic, but when projectRootPath is available, can we search for tsconfig.json based on projectRootPath?
```typescript
if (scriptInfo.isDynamic && projectRootPath) {
      return combinePaths(projectRootPath, "tsconfig.json")
}
```

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
It looks like this is a question rather than a bug report.

This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
