### ISSUE TITLE
jsdoc link's trailing underscore is not shown in the quickinfo of a reference

### ISSUE THREAD

**Issue by yf-yang** [microsoft/TypeScript#55005]
# Bug Report

### 🔎 Search Terms

- jsdoc
- underscore

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about all stuff.

### ⏯ Playground Link

[playground link](https://www.typescriptlang.org/play?#code/PQKhCgAIUgBBnApoyBvWAbAlgOwNaQAWALsQA7wBcwwAJgPYDG8AdGQJ7GH04v0BOAc2ABmYP0QAzRBJyNEdAIbFFAW3q1EGFiVUYAxPQBGAK0SNiLAPpWJZfjYC+UEMHCSArnOJYekO-wAFACUaI5AA)
### 💻 Code

```ts
/**
 * @see {@link https://docs.python.org/3/reference/datamodel.html#object.__repr__}
 */
function repr() {}
```

### 🙁 Actual behavior

When hovering and get quickinfo:
![image](https://github.com/microsoft/TypeScript/assets/36890796/96bc466d-0d89-42fe-a954-7f27985cb6ac)

### 🙂 Expected behavior

Those two underscore at the end of the link should be part of the link

**Comment by a-tarasyuk** [comment]
The `linkText` includes the entire link. @RyanCavanaugh Is that correct?

```json
{
    "marker": {
      "fileName": "/tests/cases/fourslash/quickInfoLink11.ts",
      "position": 100,
      "name": ""
    },
    "item": {
      "kind": "function",
      "kindModifiers": "",
      "textSpan": {
        "start": 100,
        "length": 4
      },
      "displayParts": [
        {
          "text": "function",
          "kind": "keyword"
        },
        {
          "text": " ",
          "kind": "space"
        },
        {
          "text": "repr",
          "kind": "functionName"
        },
        {
          "text": "(",
          "kind": "punctuation"
        },
        {
          "text": ")",
          "kind": "punctuation"
        },
        {
          "text": ":",
          "kind": "punctuation"
        },
        {
          "text": " ",
          "kind": "space"
        },
        {
          "text": "void",
          "kind": "keyword"
        }
      ],
      "documentation": [],
      "tags": [
        {
          "name": "see",
          "text": [
            {
              "text": "",
              "kind": "text"
            },
            {
              "text": "{@link ",
              "kind": "link"
            },
            {
              "text": "https://docs.python.org/3/reference/datamodel.html#object.__repr__",
              "kind": "linkText"
            },
            {
              "text": "}",
              "kind": "link"
            }
          ]
        }
      ]
    }
  }
```

**Comment by jeswinsimon** [comment]
This is not an issue on the typescript complier side. [vscode](https://github.com/microsoft/vscode) uses [Marked](https://github.com/markedjs/marked) for rendering markdown [here](https://github.com/microsoft/vscode/blob/41ef82075cd61e60498b9724425034a57cd2d46a/src/vs/base/browser/markdownRenderer.ts#L252). Marked strips off trailing underscores as per [GFM spec](https://github.github.com/gfm/#autolinks-extension-). This was also previously discussed in https://github.com/markedjs/marked/issues/2757. This has to be fixed in vscode since typescript language service returns the right url.

The same issue can also be observed in Github's markdown renderer by directly pasting in the url. https://docs.python.org/3/reference/datamodel.html#object.__repr__
