### ISSUE TITLE
`-0` in enum value is transformed to `+0`

### ISSUE THREAD

**Issue by nicolo-ribaudo** [microsoft/TypeScript#55093]
# Bug Report

### 🔎 Search Terms

enum negative zero 0

### 🕗 Version & Regression Information

Every version I tested

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYOwrgtgBAglDeAoKUAeUC8UC0AGRAvogMYD2IAzqQDbAB01pA5gBQDyARgFbDEAudAJYUWMOqgA0OXAEoZQA)

### 💻 Code

```ts
enum A {
  x = -0
}
console.log(Object.is(A.x, -0))
```

### 🙁 Actual behavior

`-0` is transformed to `0`, and thus that code logs `false`:

```js
"use strict";
var A;
(function (A) {
    A[A["x"] = 0] = "x";
})(A || (A = {}));
console.log(Object.is(A.x, -0));
```

### 🙂 Expected behavior

It is incredibly surprising that TS transforms a value into another, since this does not happen anywhere else. I would expect that code to log `true`, with the following output:
```js
"use strict";
var A;
(function (A) {
    A[A["x"] = -0] = "x";
})(A || (A = {}));
console.log(Object.is(A.x, -0));
```

**Comment by fatcerberus** [comment]
The cause of this bug probably has something to do with the fact that `-0..toString()` returns `"0"`.  As you saw in https://github.com/microsoft/TypeScript/issues/55091, TS doesn’t just preserve the expression verbatim but tries to use its primitive value.

**Comment by nicolo-ribaudo** [comment]
&lt;OT> `-0..toString()` actually returns `-0` 😛 &lt;/OT>

**Comment by fatcerberus** [comment]
Oops, I made the same mistake as TS does in https://github.com/microsoft/TypeScript/issues/54992 😝  
Edited.

**Comment by ilogico** [comment]
`-0..toString` is `-(0.toString)`, it's a number coerced back from the string `'0'`

**Comment by jp-diegidio** [comment]
Unless I am missing something, the problem here is rather related to `Object.is` which does distinguish -0 from 0, while the two are simply equal as numbers all over the place including in literal types...  See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is#description for details.

**Comment by RyanCavanaugh** [comment]
Unless there's a real use case I'm missing here, I don't think even a 0.1% chance of breaking someone else is worth changing something for the sake of fixing a case where you *tried* to break TS and were successful 😅

**Comment by jp-diegidio** [comment]
Hmm, I wouldn't agree with that: it is a fact that -0 is not 0, and the compiler does get a -0 when solving that constant, it's the code generation that (apparently, I haven't checked it) does a to-string and there we are losing information, but an if with a strict equality (in that place and not only, of course this would be not a minor refactoring overall) could fix that: indeed, more generally, Object.is was introduced to *tighten* some JS things up, i.e. as the opposite of an anti-pattern...  Anyway, I am still quite new to TS overall, so just my 2c.

**Comment by Josh-Cena** [comment]
> Object.is was introduced to _tighten_ some JS things up, i.e. as the opposite of an anti-pattern

If the "JS thing" is `0 === -0`, then that's the right behavior specified by IEEE-754.

**Comment by jp-diegidio** [comment]
<< In the IEEE 754 standard, zero is signed [...]  The two values behave as equal in numerical comparisons, but some operations return different results for +0 and −0. For instance, 1/(−0) returns negative infinity" >> [courtesy WP](https://en.wikipedia.org/wiki/IEEE_754#Signed_zero).  Then, back to "patterns", the rationale with `Object.is` (as I get it) was that `-0` and `0`, indeed by the standard, are not *the same* object, regardless of operations one then applies to then...

That said, all considered, I am not saying it is improper to just simplify the whole thing by stating that in TS the literal `-0` is *the same as* the literal `0` (I mean in values and in types), and that that's it, possibly with a side note or even a specific restriction of the language such that `Object.is` should not be used in TS... or something of the sort.  Somewhat tough decisions...

**Comment by jp-diegidio** [comment]
P.S.  But of course "in values" would not work, just "in types", since JS remains JS, and that would be inconsistent... so we seem to be left with just the general advice not to mix `Object.is` with TS concepts...  I suppose.

**Comment by nicolo-ribaudo** [comment]
I do not disagree with the "won't fix" label. I still believe that this is a bug, but yeah it will not affect the real world :P

(I wasn't actually trying to _break_ TS, but to make sure that Babel behaved the same in every case)

**Comment by jp-diegidio** [comment]
It does affect *type safety*, for those who care (and I for one do very much: "unpatchable holes" in a language are a show stopper as far as I am concerned), and in a way that cannot be worked around or at least be made explicit (where the user is at least in charge) since the bug/inconsistency (apparently, this hasn't really been confirmed) is in the compiler/emitter's code itself...

**Comment by fatcerberus** [comment]
There are a lot type holes in TS pretty much by design:

https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

> [Don’t try to] Apply a sound or "provably correct" type system. Instead, strike a balance between correctness and productivity.

Complete type safety is not an endgoal.

**Comment by jp-diegidio** [comment]
But I'd seriously disagree with that goal: a structural type system on top of a suitably restricted dynamic language is not at all an impossible feat.  And I cannot share it because it's commercial software, but I do have a "typing" module where I do ensure a specific kind of safety, together with, and I cannot do otherwise in my code, some specific "normative" conventions.  And that just works great, except if I cannot keep things together at all because there's a bugs inscribed in the compiler/emitter: that becomes a show stopper, if one cares for correctness (aka the code does what it says!)...  So, while I agree there is always a balance to strike, it's about the level of requirements supported, not about their correctness: aka restrict the scope if necessary, do not just leave "holes"...

**Comment by jp-diegidio** [comment]
And I get a thumbs down for pointing out that that is simply a broken approach on top of broken code...

I am using TS professionally so I'll fork and fix this bug because it's even trivial, and I'll post a pull request: then you'll either accept it or at least explain why TS must stay broken.

**Comment by lionel-rowe** [comment]
At the risk of beating a dead horse, the current behavior seems pretty reasonable, given that both objects and `Map`s have identical behavior to enums regarding negative zero:

```ts
let obj = { [-0]: 42 }
obj // { "0": 42 }
obj[0] // 42
Object.is(Number(Object.keys(obj)[0]), -0) // false

obj = {}
obj[-0] = 42
obj // { "0": 42 }
obj[0] // 42
Object.is(Number(Object.keys(obj)[0]), -0) // false
Object.is(Number(Object.keys(obj)[0]), 0) // true

let map = new Map([[-0, 42]])
map.get(0) // 42
Object.is(map.keys().next().value, -0) // false
Object.is(map.keys().next().value, 0) // true

map = new Map()
map.set(-0, 42)
map.get(0) // 42
Object.is(map.keys().next().value, -0) // false
Object.is(map.keys().next().value, 0) // true
```

**Comment by jp-diegidio** [comment]
@lionel-rowe  But there is conversion to string there (which I had mentioned above, among other things), where that behaviour *is* valid.  Indeed, probably TS is just converting literals to strings where/while it shouldn't.  The bug in question rather affects the correctness of *numeric computation*, and even more than that if one cares for consistency with JS, not just the floating-point standard.  That (again) said, I can try and answer any technical questions, but otherwise I won't insist: if the problem is not generally perceived as such, so be it.  OTOH, frankly, I have rather stopped using TS since then.

**Comment by lionel-rowe** [comment]
> But there is conversion to string there (which I had mentioned above, among other things), where that behaviour is valid.

For objects yes, but not for `Map`s. Maps use [`SameValueZero`](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-samevaluezero) logic, i.e. `0 == -0`, and furthermore [`-0` always gets converted to `0` upon setting](https://tc39.es/ecma262/multipage/keyed-collections.html#sec-canonicalizekeyedcollectionkey) (so it's impossible for a `-0` key to even exist):

> 24.5.1 CanonicalizeKeyedCollectionKey ( key )
> The abstract operation CanonicalizeKeyedCollectionKey takes argument key (an [ECMAScript language value](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-ecmascript-language-types)) and returns an [ECMAScript language value](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-ecmascript-language-types). It performs the following steps when called:
> 
> 1. If key is -0𝔽, return +0𝔽.
> 2. Return key.

But the types remain the same, nothing to do with string conversion.

**Comment by jp-diegidio** [comment]
Yeah, still along the lines of what every professional programmer should know about floating point, not to mention, again, notions such as consistency and correctness: indeed, your examples are simply not the bug in question.  Anyway, I am out of here: the issue indeed is more deeply one of methodology and responsibility, as well as one of systematic misguidance and the institutionalised broken tools, patterns, and practices.  (EOD.)
