### ISSUE TITLE
Module name collosion

### ISSUE THREAD

**Issue by laszlojakab** [Microsoft/TypeScript#551]
Hi,

I'm using an external library through a .d.ts file. This file contains the following module definition:

```ts
declare module ExternalLibrary 
{
  interface ExternalLibraryInterface { ... }
}
```

Now I want declare my own module (MyModule.ExternalLibrary) where I want to use the ExternalLibrary.ExternalLibraryInterface:

```ts
module MyModule.ExternalLibrary
{
  class MyClass {
     X : ExternalLibrary.ExternalLibraryInterface;
  }
}
```

The problem is that the compiler doesn't recognize that the ExternalLibrary.ExternalLibraryInterface is not in my own code. Is there a way to define a "fully qualified" typename for ExternalLibraryInterface?

**Comment by IanYates** [comment]
:100: - I've run in to this a couple of times now.  I think something like global:: would be neat.

As for how the JS gets emitted...  That's a trickier issue.  For me I was just needing to reference an interface (to provide some type information) so I didn't need any JS to be emitted.  However if I was trying to new up a class from the global scope then that would be tricker.  I guess applying the `window.` prefix would do the trick (I've only got browser JS experience - I appreciate this wouldn't work in node).

Could we start by allowing it for interface definitions, since there's no JS emit issue, and then flesh it out further afterwards?

**Comment by IanYates** [comment]
#983 seems to have more traction and is about the same topic...
