### ISSUE TITLE
keyof collapses the expression when used in a mapped type

### ISSUE THREAD

**Issue by Mad-Kat** [microsoft/TypeScript#55129]
# Bug Report

### 🔎 Search Terms

- keyof union generic
- keyof union
- keyof

### 🕗 Version & Regression Information

- Since  4.1.5 (Playground test where mapping works)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.6#code/C4TwDgpgBAYgTgVwJbCgXgFBSgHygby22IDsBDAWwgC4oAiMsMAGwjoG4jioBjAe2Z84tOnAgATDlygBfInkLds5KiIBGZcuSlLeAoSJARmggO47ic7AunLKNekM0BzNp139Bwx3BdvpMpwYoJBQAEoQAM4IzMAAjAA8ACpQEAAewBAk4pEEKg6RwHBIJM64UCQIFGoQcOx6XrSFxaXlldW1sgB86AREANoA0hAgUCVQKWS5AAYAJPjDIP0A5PnLALoy1POLK55CGzLT67QIJADWJHymJBiBUMHg0BHRsQBMyakZWTl59k1FEplPDtGp1BoGKDNIFtKpg7q9c4jPgAMz62CGIzGJAmUCmUDmCxGKzWm22RKWy32cEOx1OFyuNzuGAwAHpWVCABZ8GLiKA1eiMFg0MSScp0DRaMjUIwma50cVOUo0JWuOiPUJJKLxRHItEvGLxBLwZDAHrs4CcpC5UxCc6RIjs7gAPQA-CynZFubz+dAGExWNRRQq8BLNOGZcYzCGfH5qKq2BroFrCm9egb3sbEChzazLdaoOI+FESMtULa4Oc8dkoABJZYUCp8VDRMRQUyc0bUAAijo5xDdLOwGCAA)

### 💻 Code

```ts
type Fruit =
  | {
      name: "apple";
      color: "red";
    }
  | {
      name: "banana";
      color: "yellow";
    }
  | {
      name: "orange";
      color: "orange";
    };

type Result1<T extends {name: string | number; color: string | number }> = {
  [Key in T as `${Key['name']}:${Key['color']}`]: unknown
}; 
type Result2<T extends {name: string | number; color: string | number }> = keyof {
  [Key in T as `${Key['name']}:${Key['color']}`]: unknown
}

// should be "apple:red" | "banana:yellow" | "orange:orange"
type Test1 = keyof Result1<Fruit> // this works

// should be "apple:red" | "banana:yellow" | "orange:orange"
type Test2 = Result2<Fruit> // this doesn't work and I'm not sure why :D
```

### 🙁 Actual behavior

- Test2 is `"apple:red" | "apple:yellow" | "apple:orange" | "banana:red" | "banana:yellow" | "banana:orange" | "strawberry:red" | "strawberry:yellow" | "strawberry:orange"`
- Somehow `Result2` is collapsed:
![image](https://github.com/microsoft/TypeScript/assets/7972860/c581da43-6d9b-4efb-86fd-e76739a53b92)

### 🙂 Expected behavior

- Test2 should be `"apple:red" | "banana:yellow" | "orange:orange"`

**Comment by fatcerberus** [comment]
`Result1` is distributive (i.e. it `Array.map`s over the individual union members of `T`, more or less).  I'm not sure of the exact rules for when a mapped type is distributive or not, but adding the `keyof` in `Result2` seems to be disabling it.

**Comment by Andarist** [comment]
I think this should be classified as a bug and not a question :p I prepared a fix for this but regardless of the fact if my fix is right or not, I think this is just a bug.

`keyof` here doesn't really turn off the distributivity of this mapped type. It's just an accidental simplification of this index type (where an index type is a `keyof T`). It happens before the final instantiation [here](https://github.dev/microsoft/TypeScript/blob/fac24ae4f707f9c9a6c44248861b4bea98291a68/src/compiler/checker.ts#L13267). This call instantiates ```${Key['name']}:${Key['color']}``` to ```${T['name']}:${T['color']}``` and later when `T` gets instantiated with `Fruit` the compiler is evaluating that to all possible permutations. By that time it lost the fact that `T` ts both sites has to be identical/a single member of the union.

A similar thing happens with:
```ts
declare const str: "a" | "b"
const output = `${str}:${str}` as const
```

The `output`'s type is `"a:a" | "a:b" | "b:a" | "b:b"` but in reality, it can only be `"a:a" | "b:b"`. This case is much harder to fix though, while the case presented here can be fixed by avoiding simplification (deferring resolution) at the generic level.
