### ISSUE TITLE
Partially discriminated union with explicitly defined key loosens inferred type

### ISSUE THREAD

**Issue by cwoolum** [microsoft/TypeScript#55239]
# Bug Report

*Please feel free to change the title to make it more accurate. I wasn't sure what to call this*

### 🔎 Search Terms

union narrow

### 🕗 Version & Regression Information

5.1.6

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=99#code/KYDwDg9gTgLgBDAnmYcAiEC2A5CATYAZSQBtUBeOAUTM2ADsZjEy4AfOASUwEMBzIqWABuAFCjQkWAmSoawOo2atKAb1FxNCfth50AXHADOMKAEt6fMVuNDDquAGtgiQyfOXhcAG48SAV2A3Uws+OABfAG0AXWstAGMACzMSPCgGQwAKeUUmIXY4AGEIRgY8lmAAShixcLEJcGh4JBQikpgy5Qo4B3j2suCPMLrxSSaZVu5+QQq4NQ0tGB09ILgAcjNMPjW4zU3pwgh-KHjV91CC+n8SEl3bCvsnF0HQr18As5DLCJqFzSSUmkMnBsrROvkOMVSkohNVYqIRuI+vQTHB9gJDBgcPgZioen9tHxdAZ1pttgAaAnoohHE6rNaJGAwMBGfQAejZoD0YDIADo+pg2dTeQArMAUuAcuAAFWSRjR8r6UHS8RgvLamDAKWAUDg6QAjv4zOl5QADamHY6nU0EkwPOAxSk2AGpdL0QwxBH1ABm-noqrMJTgeAghzoAHVoI5MvQcZisLgCF1Kviqd6QcKlkSVnNyJQAERk-Mp9Q2Z0lIwQPkkCB8TLCi2006VAnhBFAA)

### 💻 Code

```ts
export type DomNodeStyle = ElementStyle | ImageStyle;

export type ElementStyle = {
    tagName: string;
    style: { key: string; value: string }[];
    children: (ElementStyle | ContentStyle)[];
};

export type ContentStyle = { content: string };

export type ImageStyle = {
    tagName: 'img';
    imageSource: string | null;
    style: { key: string; value: string }[];
    children: (ElementStyle | ContentStyle)[];
};

const image = {
    tagName: 'img',
    imageSource: 'https://example.com/image.jpg', // This is correct. Compiler requires `imageSource` because tagName is `img`.
    style: [],
    children: []
};

function doSomeWork(node: DomNodeStyle) {
    if (image.tagName === "img") { // Narrowing is not occurring correctly
        console.log(image.imageSource) // Error message: Property 'imageSource' does not exist on type 'ElementStyle'
    }
}
```

### 🙁 Actual behavior

For a partially discriminated union, when trying to access a narrowed field value, the compiler does not properly narrow the type. This forces the user to use the `in` operator to determine if the field exists. When instantiating the object though, the compiler does correctly infer that the field from the narrowed type needs to exist. 

### 🙂 Expected behavior

I would expect the compiler to properly narrow the type if the explicitly defined union is set. In this case, if `tagName` is `img`, the compiler should infer that `imageSource` is required and available. If `tagName` is any other string value, the compiler should fall back to `ElementStyle` for the type.

**Comment by fatcerberus** [comment]
Pretty sure this is a duplicate of a few issues.

This is not a bug; the underlying problem here is that `image.tagName === "img"` isn't actually sufficient to narrow the union to `ImageStyle`: `image` might still be an `ElementStyle` whose `tagName` just *happens* to be `"img"`.  You'd need a way to say `string & not "img"` for this to work correctly.

You can actually see this in action by commenting out `imageSource` in the object literal - [there is no compiler error and `image` is inferred to be a valid `ElementStyle`](https://www.typescriptlang.org/play?target=99#code/KYDwDg9gTgLgBDAnmYcAiEC2A5CATYAZSQBtUBeOAUTM2ADsZjEy4AfOASUwEMBzIqWABuAFCjQkWAmSoawOo2atKAb1FxNCfth50AXHADOMKAEt6fMVuNDDquAGtgiQyfOXhcAG48SAV2A3Uws+OABfAG0AXWstAGMACzMSPCgGQwAKeUUmIXY4AGEIRgY8lmAAShixcLEJcGh4JBQikpgy5Qo4B3j2suCPMLrxSSaZVu5+QQq4NQ0tGB09ILgAcjNMPjW4zU3pwgh-KHjV91CC+n8SEl3bCvsnF0HQr18As5DLCJqFzSSUmkMnBsrROvkOMVSkohNVYqIRuI+vQTHB9gJDBgcPgZioen9tHxdAZ1pttgAaAkAeip6KIRxOqzWiRgMDARn0NNAejAZAAdH1MLTeAI+QArMAUuA0uAAFWSRjRir6UHS8RgfLamDAKWAUDg6QAjv4zOlFQADOmHY6nc0EkwPOAxSk2AGpdL0QwxBH1ZFGCD8kgQPiZOmVMQymxRgB6AH5xAAzfz0dVmEpwPAQQ50ADq0EcmXoOMxWFwBC6lXxBLMCZBdL5SyJKzm5EoACIyW3K+oowkSv7A8HQyLgHyrQzTpUCeEEUA).

**Comment by cwoolum** [comment]
I guess I had assumed that the compiler would automatically pick the narrower type but being explicit with a negative type is probably the better approach. 

I'll close this as a dupe since it is the intended functionality.

**Comment by everett1992** [comment]
```
console.log(image);
//          ^? const image: ElementStyle
```

Woah, that's the first time I've seen the `^?` comment on the playground, that's really useful!

**Comment by MartinJohns** [comment]
> guess I had assumed that the compiler would automatically pick the narrower type

But that wouldn't be safe. Your type `ElementStyle` **explicitly** says that **any** `string` is a valid `tagName`, that includes `"img"`.
