### ISSUE TITLE
type checking after instainceOf condition in else block is working incorrectly

### ISSUE THREAD

**Issue by stepancar** [Microsoft/TypeScript#5523]
[see example in playground](http://www.typescriptlang.org/Playground#src=interface%20IFoo%20%7B%0D%0A%09value%3A%20string%5B%5D%7Cstring%3B%0D%0A%7D%0D%0A%0D%0Afunction%20bar(options%3A%20IFoo)%20%7B%0D%0A%09var%20val%20%3D%20options.value%3B%0D%0A%09var%20result%3A%20string%3B%0D%0A%09if%20(val%20instanceof%20Array)%20%7B%0D%0A%09%09result%20%3D%20val.join('')%0D%0A%09%7D%20else%20%7B%0D%0A%09%09result%20%3D%20val%3B%0D%0A%09%7D%0D%0A%7D)
``` javascript
interface IFoo {
	value: string[]|string;
}

function bar(options: IFoo) {
	var val = options.value;
	var result: string;
	if (val instanceof Array) {
		result = val.join('')
	} else {
		result = val;
	}
}
```
val has one of two types strting[] or string
in 'if' condition checked instanceofArray
in else statement compiler should know that val has string type

**Comment by sandersn** [comment]
#5442 should fix this, I think.

**Comment by weswigham** [comment]
#5442 only changes `typeof` type guards and composite type guards.

But this behavior is actually by spec - with `instanceof` type guards, we only affirmatively narrow (so in the `true` branch) - the logic being that since TS uses structural typing, even if `instanceof` catches something, `instanceof` _not_ catching something doesn't mean that the thing you're checking is  _not_ a given type. (In effect, `val instanceof Array` does not imply that val does not have the type of an array, since it could still have the shape of an array but not the same constructor.) User-defined type guards are more strict, as we assume when you make a type predicate that it's capable of being exhaustive, and `typeof` is more strict because primitives are effectively nominal.

In the example above, if you do this:
```ts
interface IFoo {
    value: string[]|string;
}

function bar(options: IFoo) {
    var val = options.value;
    var result: string;
    if (typeof val !== "string") {
        result = val.join('')
    } else {
        result = val;
    }
}
```
it will narrow as you desire. Prefer `typeof` to `instanceof` where possible because of this.

**Comment by RyanCavanaugh** [comment]
#1719 is the issue for this
