### ISSUE TITLE
'extends' keyword evaluates differently when: conditionally typing generics VS generic type parameter constraint

### ISSUE THREAD

**Issue by Olesj-Bilous** [microsoft/TypeScript#55255]
# Bug Report

### 🔎 Search Terms

extends, conditional, vs, generic, type, parameter, constraint

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about: 'extends'

### 💻 Code

```ts
// conditionally typing on 'extends'

type Extension<U, T> = T extends U ? T : never

type Wide = Extension<number, number | string> // number


// constraining generic type parameter with 'extends'

type Extended<U, T extends U> = T

type Widened = Extended<number, number | string> // error
// Type 'string | number' does not satisfy the constraint 'number'.
 // Type 'string' is not assignable to type 'number'. ts(2344)


// non-distributive conditional typing on 'extends'

type ExtensionNonDist<U, T> = [T] extends [U] ? T : never

type WideNonDist = ExtensionNonDist<number, number | string> // never

```

### 🙁 Actual behavior

When conditionally typing on an extends clause, `number | string` is evaluated as `extends number` and _definitionally coerced_ to `number`

This does not correspond to the behavior when passing a generic type parameter to the same `extends number` constraint

In that case, an error is produced since `number | string` does not satisfy the constraint `number`

We can eliminate the _definitional coercion_ when conditionally typing the generics by using non-distributive conditional typing. In that case, the defined type is correspondingly `never`

### 🙂 Expected behavior

It is not immediately evident why `extends` should behave differently when constraining vs conditioning, or why disabling distributive conditioning should revert the difference in behavior. 

While this behavior is surprisingly useful, it does not appear to be documented and might be unintentional. It could be related to various unexpected behaviors.

**Comment by MartinJohns** [comment]
I do not see a bug here. You're comparing two different features that just share a keyword. When you use different features you get different behavior. Neither is a replacement for the other.

**Comment by jcalz** [comment]
So do you want to close this issue then since it's not a bug?  

There might not be a specific place in the documentation that says "`extends` works different ways" explicitly, but there is documentation for both [constraints](https://www.typescriptlang.org/docs/handbook/2/generics.html#generic-constraints) and [conditional types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html).

**Comment by jcalz** [comment]
Distributive conditional types split input unions into members before evaluation, so it's not comparing `number | string` to `number`; it compares `number` to `number` and then `string` to `number`.  In any case, TypeScript is working as intended and there's no bug here.  Could you please close the issue so that the TS team is saved the effort of triaging and ultimately closing it themselves?  After that, interested parties could presumably continue discussion here, although Stack Overflow and/or Discord are probably more appropriate venues for that.

**Comment by Olesj-Bilous** [comment]
> Distributive conditional types split input unions into members before evaluation, so it's not comparing number | string to number; it compares number to number and then string to number. In any case, TypeScript is working as intended and there's no bug here
I see, that makes sense, thank you
