### ISSUE TITLE
Resolutions not updated after `npm ci`

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#55275]
1. Create a Codespace for https://github.com/microsoft/typescript-error-deltas (you might not need a Codespace in practice).
1. Open up
 
   ```
   src/utils/exerciseServer.ts
   ```

   Notice all resolutions have red squiggles. 
1. Run

   ```
   npm ci
   ```

   Notice red squiggles remain.
1. Type within each import specifier and then undo. Some of the squiggles disappear afterwards. Sometimes `@typescript/server-harness` never gets picked up.

Here's my [tsserver.log](https://github.com/microsoft/TypeScript/files/12265133/tsserver.6.log)

![busted-npm-ci-resolutions-aug-4-2023](https://github.com/microsoft/TypeScript/assets/972891/43db3554-c2bc-42ec-b3b8-8b67df84fe03)

**Comment by jakebailey** [comment]
Wild guess but can you change your watch mode?

```
"typescript.tsserver.watchOptions": {
    "watchFile": "fixedPollingInterval"
},
```

**Comment by so1ve** [comment]
Interesting… I run into this issue months ago and I expect a tracking issue should already be created by a random person, but … :D

**Comment by sheetalkamat** [comment]
Ok after investigating this one, it seems like this is not related to OS but because we arent watching paths like `/workspaces/typescript-error-deltas/node_modules/@types` because its too close to root folder. 
Eg we have baselines now for what we can watch: https://github.com/microsoft/TypeScript/blob/main/tests/baselines/reference/canWatch/getDirectoryToWatchFailedLookupLocationAtTypesPosix.baseline.md#rootdirforresolution-folderatrootfolder1folder2 and you can see for `/folderAtRoot/folder1/node_modules/@types/dir/somefile.d.ts` is not watched
