### ISSUE TITLE
获取装饰器修饰了哪些属性

### ISSUE THREAD

**Issue by renaiss** [microsoft/TypeScript#55281]
### 🔍 Search Terms

Decorator

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

在类型计算的时候可以获取装饰器使用到了哪些属性上面

### 📃 Motivating Example

目前类型计算的过程中对于装饰器不太友好，如果每次维护代码都需要手动维护一次装饰器的属性合集，还是太麻烦了。

### 💻 Use Cases

```html
function Prop() {
  return function (target: any, propertyKey: string) {
    // nop
  }
}

class App {
    @Prop() visible!: boolean;
    @Prop() title!: string;
}

type AppProps = PickPropertyDecorators(App, Prop) // "visible" | "title"
```

**Comment by jcalz** [comment]
I assume the downvotes here are because this isn't written in English.  Is there a policy that says English is required?  It seems reasonable that there *would* be, but I didn't find one in my search (I only see that communications about security issues are *preferably* in English). 

Anyway, assuming machine translation is accurate, I'd say this is a duplicate of #48413.
