### ISSUE TITLE
`resolvePackageJsonExports` and `resolvePackageJsonImports` doesn't properly handle extensionless subpaths

### ISSUE THREAD

**Issue by kherock** [microsoft/TypeScript#55337]
### 🔎 Search Terms

resolvePackageJsonImports resolvePackageJsonExports package.json imports map exports map

### 🕗 Version & Regression Information

- tested on TS 5.0 and 5.1, which are the first versions to support resolving imports via package.json imports/exports maps

### ⏯ Playground Link

https://github.com/kherock/ts-packagejson-import-maps-bug

### 💻 Code

I'm trying to replace my tsconfig.json paths with an `imports` map since it has pretty good tooling support at this point, only it seems like TypeScript doesn't handle some edge cases where a subpath ends in `/*` and `"moduleResolution": "Bundler"` is used in tsconfig.json.

```json
  "imports": {
    "#components/*": "./src/components/*"
  },
```

In TS, the following imports don't work

```ts
// error TS2307: Cannot find module '#components/MyComponent' or its corresponding type declarations.
import MyComponent from '#components/MyComponent';
```

Curiously, attaching a file extension on the import resolves the issue, despite having `"moduleResolution": "Bundler"` in my tsconfig:

```ts
// both work
import MyComponent from '#components/MyComponent.ts';
import MyComponent from '#components/MyComponent.js';
```

### 🙁 Actual behavior

My bundlers are able to resolve these paths at runtime, but TypeScript complains with the following error:

```
error TS2307: Cannot find module '#components/MyComponent' or its corresponding type declarations.
```

### 🙂 Expected behavior

TypesScript should resolve paths from `imports` and `exports` maps with the same rules documented by the `moduleResolution` field. i.e. with `moduleResolution: "Bundler"`, file extensions should not be required. This is in line with how Webpack and Vite resolve these fields.

**Comment by kherock** [comment]
For import maps, there is a workaround I can use that mimics `"Bundler"`'s resolution logic:


```json
  "imports": {
    "#components/*": ["./src/components/*", "./src/components/*.js", "./src/components/*/index.js"]
  },
```

but obviously this doesn't work for package exports that I do not have control over

**Comment by andrewbranch** [comment]
Yeah, Webpack and Vite behave as you said, but notably esbuild does _not_ resolve like this. Even one major bundler doing things by Node.js’s spec is enough to justify TypeScript being more conservative here, in my opinion.

**Comment by kherock** [comment]
I understand that it violates  Node.js’s spec, and I don't like the argument that it will lead to more packages being published incorrectly due to library authors using `bundler` internally. `bundler` is already leaky in other places such as in internal relative imports and index file resolution; I don't think it's going to save the library from being unusable on Node.js just because self-referencing package exports or internal imports are being resolved more strictly.

I had the impression that using `bundler` was a way of making code be intentionally more lax to accommodate how _most_ bundlers work  - if esbuild behaving more strictly is relevant, is there any argument for using `bundler` with esbuild? Why not just use `nodenext` all the time?

**Comment by andrewbranch** [comment]
>  is there any argument for using bundler with esbuild?

- extensionless relative paths
- index/directory modules
- ability to load an ES module from a CJS module
- syntax-based conditions for `"imports"` and `"exports"` resolutions

All these things (except the last) were done by bundlers to support loads of existing CJS code. `"imports"` and `"exports"` are new, so there’s absolutely no reason for anyone to diverge from the algorithm in the only place it’s actually spec'd out. The fact that Webpack is diverging might even be a bug. It is a goal to support patterns adopted by most bundlers, but if you look at the original design docs, I explicitly said I didn’t plan to support everything, because in some places, it’s better to draw an opinionated line in the sand if it encourages consistency and reduces configuration complexity. In other words, I only plan to support _good_ behaviors adopted by most bundlers.
