### ISSUE TITLE
Unable to infer parameter type

### ISSUE THREAD

**Issue by marvinhagemeister** [microsoft/TypeScript#55370]
### 🔎 Search Terms

Function overload, type inference

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type inference + function overloading
- The behavior is also present in nightly

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAyiB2BjAYvAPAFQHxQLxQAowAnAezAGcAuKAbygDNTSaMBfASjxwuGIEt4AcwBQoSFACCFBCnTY8heAFcAtjRWqARhGIAaKADcAhgBtlEVl1w4ACmVX8KENLwHCsAbhEALYMEoqAHoggHdwgDpxCApEATBgU2NhCNJiISCwJJAAfgBiEQZlJGB+UngoABMIBkEIAGFy2qFMAwBVKAgAD2AIeEqKWFlUTBwAHykZJBGFfDhp+XHJ4cWsAgZ4GjaOLboRKChiCGBlYgqN7zYRERCoULSAawoRatr4Bqb+FrdBITXjKaIJRqAwmcwQaw4Wj7Q7HU4VABECJEnGutwwPicUCxggYuiOlSgAKJ8BAUCoBBeNTqjXgzVcfF+ayIZEokL2ByOJzOUBI5AoESYpEuHCAA

### 💻 Code

```ts
type SyncFn<T> = (props: { foo: T}) => string
type AsyncFn<T> = (num: number, value: T) => Promise<string>;

function defineConfig<T, U extends SyncFn<T> | AsyncFn<T> = SyncFn<T> | AsyncFn<T>>(fn: U): U {
  return fn;
}

// works
defineConfig<string>(async (num, value) => {
  return ""
})

// props is inferred as any :(
defineConfig<string>((props) => {
  return props.foo;
})
```

### 🙁 Actual behavior

The `props` function argument is inferred as `any`

### 🙂 Expected behavior

The `props` argument would be inferred as `{ foo: T }`

### Additional information

When you drop the `return` value in the async variant, TS gets confused too about which overload to pick. It seems like it ignores the `async` keyword.

![Screenshot 2023-08-14 at 18 25 08](https://github.com/microsoft/TypeScript/assets/1062408/6e9ac814-8db3-4aae-945f-a64eb95325d4)

**Comment by MartinJohns** [comment]
> It seems like it ignores the `async` keyword.

`async` does absolutely nothing for inference.

> The `props` argument would be inferred as `{ foo: T }`

Where do you believe the `T` should come from? There is no `T` in this context.

**Comment by marvinhagemeister** [comment]
Oh right, yeah that would've need to be specified like `defineConfig<string>(...)`. I'll update the code sample

**Comment by Andarist** [comment]
I'd encourage you to keep the parameters list the same for both variants (sync and async). This should make your life easier here. You still won't be able to infer narrowed down `U` since you need to provide an explicit type param for `T` and partial inference is not a thing (yet?).

Notice how implicit any problem goes away here:
```ts
type SyncFn<T> = (props: { foo: T}) => string
type AsyncFn<T> = (props: { foo: T}) => Promise<string>;

function defineConfig<T, U extends SyncFn<T> | AsyncFn<T> = SyncFn<T> | AsyncFn<T>>(fn: U): U {
  return fn;
}

defineConfig<string>(async (num) => {
  return ""
})

defineConfig<string>((props) => {
  return props.foo;
})
```

The problem is that, in your original code, the sync variant can't discriminate the union for the contextual type of this function expression. The contextual type stays as a union and then those 2 signatures can't satisfy the `compareSignaturesIdentical` check (note that this particular check ignores return types) and thus final `contextualSignature` gets returned as `undefined`. That ends up assigning `any` to your parameters.

**Comment by marvinhagemeister** [comment]
Interesting, that's a good idea about making both functions take the same number of arguments. In my case that doesn't work without making a breaking change to my software. The main difference on my end is that one function is synchronous and the other `async`. I don't really follow why the distinction isn't done on that basis first before checking the number of function arguments. Like the `async` keyword is a very strong indicator.

I guess internally TS converts this to a normal function with a `Promise` return type or something.

**Comment by Andarist** [comment]
> Like the async keyword is a very strong indicator.

Yes, and that's why the async variant works. The sync variant doesn't have that luxury because type-wise an async function is just `(...args: any) => Promise<any>` and a function without the `async` modifier can be made assignable to that (`() => Promise.resolve('')` is a thing after all). So the sync variant can't discard the async one from your union.
