### ISSUE TITLE
Inconsistencies inferring the instance type as a type parameter of a static method constrained by the type of this

### ISSUE THREAD

**Issue by ghostinpeace** [microsoft/TypeScript#55496]
### 🔎 Search Terms

"typeof this"
"instance type"
"InstanceType"
"Parameters"
"static"
"generic"
"inheritance"

### 🕗 Version & Regression Information

Not working up to 5.3.0

### ⏯ Playground Link

https://www.typescriptlang.org/play?target=9#code/C4TwDgpgBAkgzgEQgJwJYDcIBMA8AVAPigF4o8oIAPYCAOyziiTUyygH4phkBXaALigAzAIYAbOBADcAWABQ8gMZiRcRgCFV0AN7yo+qHGAjgqRV3AQA9kLwQjACmCD4zDNhwxaRkbUUQ8SxxQSBsuAAtUOAICAEoobSgAXz0DH1NzAHM6FDM7I3wKajoGKE1JAidIuEFaCAB3KAcAOlaRZEyaqF8QeOIiPAAaLhdEXNZ8OITk+VT9ACNangBbeZQSKAAGWTkUhTllVUY3ViKaeg0tBLmoLCXV9dJt+T35cohmkOtbe2AHUQkEFiUigAHpQVArABreRfMgARg2AAV2iJlhAaMg4MFLGF3p9cT8jAQANqbAC6IPBwnEkiaiis3ii52AsXkJ2wBNCRL+AMkwLBEOhgi+YWA1UMpjEYigIFQEDEpVFQjKWlhljIACZkaj0ZjscqmONOcr8sBSRSqRC+dAHAymUY6KzZnJ8dk6mhFGb-rSgVbITC5HC8ABmHXINEYlAGwmqyTNd25L2-C2UwU0wH0xlwZlOtlyDlYBM5T3e7h8AXU4URXxQxjAKwRaCJz0WMCoWiZYb1ZsYtvfI0sbDqyBkAAs4cj+px3MH7iLLbyKbJaeprWaUHmPGAUFoVh34RQEAAhBm6Q4O-ac47aM79vIgA

### 💻 Code

```ts
type IsDerived<T> = T extends Derived ? true : false;

class Base {
    static typeofTest(t: IsDerived<InstanceType<typeof this>>) { }
    static genericTest<T extends Base>(this: new (...args: any) => T, t: IsDerived<T>) { }

    b: number = 0;
}

class Derived extends Base {
    d: number = 0;
}

Base.typeofTest(false); // ok
type T1 = Parameters<typeof Base.typeofTest>[0]; // false (consistent)
Derived.typeofTest(false); // ok: typeof this still yields typeof Base
type T2 = Parameters<typeof Derived.typeofTest>[0]; // false (consistent)

Base.genericTest(false); // ok
type T3 = Parameters<typeof Base.genericTest>[0]; // false (consistent)
Derived.genericTest(true); // ok: thanks to the generic typing, we get typeof Derived
type T4 = Parameters<typeof Derived.genericTest>[0]; // ... but not here! false (inconsistent)

```

### 🙁 Actual behavior

``typeof this`` in a static function seems to be resolved to the type of the constructor function of the class it was written in, regardless of inheritance; this may be ok.
Using a generic function to infer the instance type (with parameter ``this: new (...args: any) => T``), inheritance is now taken into account (we get the instance type according to the actual constructor function used to call the static function).
However, when this type ``T`` is used as the expected type for a parameter of the static function, an attempt to access it through the ``Parameters`` utility type may result in another type, since inheritance now seems to be ignored again.

### 🙂 Expected behavior

``Parameters<typeof Class.staticMethod>`` should match the types that are actually expected when writing a call to staticMethod

**Comment by andrewbranch** [comment]
Type argument inference only happens when you call a function (or construct a constructor). The `typeof Derived.genericTest` is just `<T extends Base>(this: new (...args: any) => T, t: IsDerived<T>) => void`. All `Parameters` sees is that type, so it can’t possibly infer anything in it, so it instantiates `T` with the base constraint of `Base`. Inference requires an expression-level call site to work with.

You might say that a special case should be made for `this` parameters in `typeof`, but consider this case:

```ts
declare class Base {
  static filter<T, ThisInstance>(
    this: new (...args: any) => ThisInstance,
    arr: T[],
    predicate: (elem: T) => any
  ): T[]
}

class Derived extends Base {}

type T = typeof Derived.filter;
```

What would the type of `T` be here? You have two choices: (1) a generic function signature like it is today, or (2) one that is fully instantiated, with an inference source for `ThisInstance` but not for `T`. If you choose the latter, I guess you could never get the generic signature of any function?

**Comment by ghostinpeace** [comment]
... 😇
Thank you for taking the time to explain :)
