### ISSUE TITLE
Compiler API: `@template` tags do not set the `constraint` property on their type parameters

### ISSUE THREAD

**Issue by Gerrit0** [microsoft/TypeScript#55619]
### 🔎 Search Terms

compiler api, template tag, jsdoc constraint

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about the compiler API

### ⏯ Playground Link

https://ts-ast-viewer.com/#code/PQKhCgAIUgBAXApgWwA4BsCGTIG8B2ArsgEaIBOAvpACpQwICeqiAJogGZ43U3Nv1gQA

### 💻 Code

```js
/**
 * @template {number} T
 * @typedef {T} Typed
 */
```

### 🙁 Actual behavior

`templateTag.typeParameters[0].constraint` is `undefined`

### 🙂 Expected behavior

`templateTag.typeParameters[0].constraint` should be a `number` type, the equivalent TS type parameter works as expected:

```ts
type Typed<T extends number> = T
```

### Additional information about the issue

I mentioned this in the TS Discord, @jakebailey confirmed it looks like a likely bug

Originally reported in: https://github.com/TypeStrong/typedoc/issues/2384

**Comment by jakebailey** [comment]
To be clear, I really only meant that it wouldn't surprise me if this were just a bug, I'm not an expert on this particular thing.

**Comment by MartinJohns** [comment]
But it's still evaluated correctly: [Playground link](https://www.typescriptlang.org/play?filetype=js#code/PQKhCgAIUgBAXApgWwA4BsCGTIG8B2ArsgEaIBOAvpACpQwICeqiAJogGZ43U3Nv1g4cKAjQ4qTOUzJu-VgB4AzvHIBLfAHMAfNSmbB4DoXwBjeGoD2+SB0uWAFPoCUeSuCA)

**Comment by Andarist** [comment]
`templateTag` corresponds to the `@template` bit of this typedef and you have its constraint available at `templateTag.constraint`. `templateTag.typeParameters[0]` indeed refers to the declared generic (`T` in this example) so I find it a weird structure that the `constraint` is set on the parent object (perhaps it's related to the source order of this information?). That said, the same information shouldn't be available at two places in the AST node.

**Comment by andrewbranch** [comment]
This is the only way it can be for two reasons:

1. Source order constraints of the scanner/parser according to @sandersn 
2. AST types—the `templateTag.constraint` is a `JSDocTypeExpression` whereas the `templateTag.typeParameters[0]` is a `TypeParameter` node reused from TS, whose constraint is a `TypeNode`. We need to preserve a spot for that `JSDocTypeExpression`, especially since it’s valid to put things like `{string?}` there which are not valid TS type nodes.

Nathan says we could have made a separate `JSDocTypeParameter` AST node with a cleaner API, but it didn’t feel worth it to make breaking changes when support for constraints were added.

**Comment by Gerrit0** [comment]
That's unfortunate, guess I need to add even more special casing to TypeDoc's JSDoc converter then, thanks!
