### ISSUE TITLE
Cant satisfy complier on calls x implements y, where y is class.

### ISSUE THREAD

**Issue by shlomiassaf** [Microsoft/TypeScript#5571]
Hi,

Typescript 1.6.2
When trying to implement a class with private variables complier wants the derived class to implement the parent's private variables.

```
export class Father {
    private hidden: string;
    public visible: string;
}

export  class Child implements Father{
    public visible: string;
}
```

__(7,15): error TS2420: Class 'child' incorrectly implements interface 'father'.
  Property 'hidden' is missing in type 'child'.__

Trying to do the wrong thing and do implement the private variable results in the compiler not happy since we implement a private variable of the parent (In a typed language this is wrong as well, but in JS it might be a good catch...)
```
export class Father {
    private hidden: string;
    public visible: string;
}

export  class Child implements Father{
    private hidden: string;
    public visible: string;

}
```
__(7,15): error TS2420: Class 'child' incorrectly implements interface 'father'.
  Types have separate declarations of a private property 'hidden'.__

**Comment by sandersn** [comment]
Can you try `extends` instead of `implements` ? `implements` is for interfaces.

**Comment by shlomiassaf** [comment]
I can try, but as you can see I try to do some "mixin" stuff

Typescript has an official documented approach for it, https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Mixins.md

I'm sure I've seen some other places in the docs that "implement" concrete classes...
So it should be possible

**Comment by mhegazy** [comment]
the issue here is the `private` property declaration. When implementing  a class with `private`, the implementing class gets the property declaration but not its implementation. `private` members can not be re-implemented, the only allowed implementation for them is their original declaration. so now you have a class is not implementable.
for mix-in patterns, do not use private members, or split your non-private declarations in an interface and use that.

**Comment by mhegazy** [comment]
see #1101 for more details.
