### ISSUE TITLE
Auto import does not import Disposable or Emitter from VS Code's codebase

### ISSUE THREAD

**Issue by Tyriar** [microsoft/TypeScript#55781]
Related to https://github.com/microsoft/vscode/issues/116375

This issue has been around for years, I think I've mentioned it in DMs but not sure if there's an issue. Regardless, here's a detailed description of it. I'm assuming this is an upstream issue but please keep this issue open to track as it's a papercut.

This does impact my productivity; instead of auto import just working like it's supposed to, I instead have to:

1. Import one of the other symbols
2. Scroll to the top of the file
3. Find the import
4. Change the import
5. Go back
6. Change the symbol I entered in step 1

---

![Image](https://github.com/microsoft/vscode/assets/2193314/a8bc4f20-7ab3-448d-9885-2691db777ad0)

`AsyncEmitter` and `EmitterOptions` shows up:

https://github.com/microsoft/vscode/blob/85de2f21c63608e8bbc5c2347fe927b00c8300bf/src/vs/base/common/event.ts#L1184

https://github.com/microsoft/vscode/blob/85de2f21c63608e8bbc5c2347fe927b00c8300bf/src/vs/base/common/event.ts#L695

But not `Emitter`:

https://github.com/microsoft/vscode/blob/85de2f21c63608e8bbc5c2347fe927b00c8300bf/src/vs/base/common/event.ts#L897

---

![Image](https://github.com/microsoft/vscode/assets/2193314/846ed581-a918-46ee-b2a9-f7d0761ed064)

![Image](https://github.com/microsoft/vscode/assets/2193314/97bca93f-b007-45c7-8659-3e5aae647b98)

`DisposableStore` and `DisposableMap` shows up:

https://github.com/microsoft/vscode/blob/85de2f21c63608e8bbc5c2347fe927b00c8300bf/src/vs/base/common/lifecycle.ts#L210

https://github.com/microsoft/vscode/blob/85de2f21c63608e8bbc5c2347fe927b00c8300bf/src/vs/base/common/lifecycle.ts#L503

But not `Disposable`:

![Image](https://github.com/microsoft/vscode/assets/2193314/97bca93f-b007-45c7-8659-3e5aae647b98)

**Comment by mjbvz** [comment]
@andrewbranch Any ideas why `Event` would be found from a bunch of files in our codebase but not the main definition we typically want: `vs/base/common/event`

![Screenshot 2023-09-18 at 2 20 23 PM](https://github.com/microsoft/TypeScript/assets/12821956/b6f1dcae-1266-4619-a0e1-5dae5ca0bbde)

I see `EventBufferer` gets picked up from there so the file is known but something must be filtering out `Event`

**Comment by andrewbranch** [comment]
It’s because the `Event` declared at `vs/base/common/event.ts` is re-exported via `vs/workbench/workbench.web.main.ts`. Completions only shows you a single location for each exported symbol, and the most-reexported one is assumed to be the “most public.” This is designed to avoid duplicates from cascading barrel files. Suppose `Dropdown` is subsequently re-exported by the following files:

- `/foo/shared/components/dropdown/Dropdown.ts`
- `/foo/shared/components/dropdown/index.ts`
- `/foo/shared/components/index.ts`
- `/foo/shared/index.ts`
- `/foo/index.ts`

We only show a completion for the last one because it had the longest chain. Note that at this point in the filtering, we don’t know what the module specifier is going to be yet, but this often (but not always) results in us picking a file that will generate a shorter module specifier than the others.

This heuristic is becoming increasingly suspect. Many users are beginning to realize that barrel files are terrible for tree-shaking their apps and will try to go out of their way to avoid importing from one in their dependencies, but TS always prioritizes it. But it doesn’t seem like there’s a universally better heursitic for choosing a location, and the alternative is exploding the size of the completions list with lots of duplicates. Including all symbol export locations or switching to another heuristic that operates on the final module specifier (as opposed to the file name or position in the re-export chain) would increase the number of items we have to generate a module specifier for, which is a relatively expensive operation within completions.

**Comment by Tyriar** [comment]
@andrewbranch any recommendation for how we can solve this on our end? I don't think we ever want to import these functions from workbench.web.main.ts while working in the core repo as that's just the public API for embedders like vscode.dev.

**Comment by bpasero** [comment]
@Tyriar I had thought this setting would do the trick? But maybe it broke?

```
"typescript.preferences.autoImportFileExcludePatterns": [
    "xterm",
    "xterm-headless",
    "node-pty",
    "vscode-notebook-renderer",
    "src/vs/workbench/workbench.web.main.ts",
    "src/vs/workbench/api/common/extHostTypes.ts"
]
```

**Comment by Tyriar** [comment]
@bpasero I don't see that in our settings.json, is that the problem?

**Comment by bpasero** [comment]
@mjbvz for me this setting never fixed `Event`. I think it only helped for `Disposable`. Here is a recording of what I see:

![Recording 2023-09-19 at 20 19 31](https://github.com/microsoft/TypeScript/assets/900690/878d8643-f411-470c-8cb1-2cfe1f8772b3)

The issue for `Event` seems to be that the name duplicates the DOM `Event`, so no import is suggested, not even when I add generics.

**Comment by Tyriar** [comment]
@mjbvz still not working for me after pulling the settings change and restarting ts server

![image](https://github.com/microsoft/TypeScript/assets/2193314/a6c5dbac-ac09-444d-8af5-2512f67295f6)
![image](https://github.com/microsoft/TypeScript/assets/2193314/b88c8945-362c-4d0b-98a9-63d4fc634a2f)

**Comment by mjbvz** [comment]
@Tyriar It's working for me:

![Screenshot 2023-09-19 at 12 11 13 PM](https://github.com/microsoft/TypeScript/assets/12821956/01032098-ce51-4f3b-855b-a4d7dac25624)

Are you on windows? Wonder if there's something happening with `\` paths

**Comment by Tyriar** [comment]
That's it! Could we make that setting work regardless of separator since we don't have https://github.com/microsoft/vscode/issues/5595 yet?

**Comment by Tyriar** [comment]
@mjbvz yes I'm on Windows. I thought I saw it working just now after changing the separator but it's broken again. Using this doesn't seem to work 😕 

```
		"src/vs/workbench/workbench.web.main.ts",
		"src/vs/workbench/api/common/extHostTypes.ts",
		"src\\vs\\workbench\\workbench.web.main.ts",
		"src\\vs\\workbench\\api\\common\\extHostTypes.ts"
```

**Comment by andrewbranch** [comment]
The slashes should be normalized by TS, but maybe there’s something else Windows-specific going on 🤔

**Comment by jasonlyu123** [comment]
The Windows problem should be related to the drive letter. The `src/vs/workbench/workbench.web.main.ts` pattern is normalized to `/**/src/vs/workbench/workbench.web.main.ts` in the client, and the regex pattern for that is `/^((\/.+?)?\/src\/vs\/workbench\/workbench\.web\.main\.ts)($|\/)/i` which doesn't match the drive letter in the start `c:/path/to/vscode/src/vs/workbench/workbench.web.main.ts`.

#56415 also uses Windows, so it should be related.

**Comment by Tyriar** [comment]
Just came back from a break and noticed this was fixed, thanks so much!
