### ISSUE TITLE
future reserved words in JS strict mode do not cause SyntaxError

### ISSUE THREAD

**Issue by eps1lon** [microsoft/TypeScript#55974]
### 🔎 Search Terms

future reserved words strict mode SyntaxError

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about parser 

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.0-dev.20231004#code/OQVwzgpgBGAuBOBLAxrYAoA9Jq8KXgDcIATKAdwHt4SwpEA7KAKQGUYEVYoBbSk6ACMQ3SgwA2ATygAiSDwCGDWCigR48amBn0mAFVbpkYuPR4AHcRB4RldALxRgeAsRIZjDU41jqAZgrI0I7O+OpuHibc5oEA1goA5sFOLuGkkV7RSIQKvlAhqUTpRlFQ5pq+qKT5KWFF7iWZZSCC4qoFdRHoQA

### 💻 Code

```ts
'use strict'
// reserved words in JS strict mode but only "semantic errors" in TS
const implements = 'reserved'
const interface = 'reserved'
const package = 'reserved'
const private = 'reserved'
const protected = 'reserved'
const public = 'reserved'
```

### 🙁 Actual behavior

each variable declaration leads to an error (e.g. `Identifier expected. 'implements' is a reserved word in strict mode.`). TypeScript ESLint maintainers called these "semantic errors".

### 🙂 Expected behavior

The first usage of a future reserved word leads to SyntaxError like `const class = 'reserved'` would. 

As far as I can tell, this would match the spec:

> It is a Syntax Error if this phrase is contained in [strict mode code](https://tc39.es/ecma262/multipage/ecmascript-language-source-code.html#sec-strict-mode-code) and the [StringValue](https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#sec-static-semantics-stringvalue) of [IdentifierName](https://tc39.es/ecma262/multipage/ecmascript-language-lexical-grammar.html#prod-IdentifierName) is one of "implements", "interface", "let", "package", "private", "protected", "public", "static", or "yield".

-- https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#_ref_18301

### Additional information about the issue

Without raising a SyntaxError, consumers will assume the code is syntactically correct e.g. TypeScript ESLint will not raise an issue when parsing files containing future reserved words in strict mode (see https://github.com/typescript-eslint/typescript-eslint/issues/7720)

**Comment by bradzacher** [comment]
As mentioned in the attached issue - for TS it makes little delineation between syntax and semantic errors.

The biggest difference is that a syntax error is generally unrecoverable (eg "exit right now because Fubar"), whereas semantic errors are recoverable (eg "something isn't right but we can continue with an assumption").

So this case is "technically" a syntax error as per the JS spec - however it is fully recoverable - TS is able to parse the code, recognise its an identifier in a variable declaration, and continue parsing with that assumption.

TS recovering many "bad syntax" cases is a good thing because it means that it can provide a high-quality IDE experience that is resilient to typos and that continues to work in the presence of malformed code.

From the user's POV they run a typecheck via the CLI and it will evaluate all errors (syntax and semantic) and report them all - preventing malformed code from passing.

**Comment by RyanCavanaugh** [comment]
We really can't help it if API users take incorrect assumptions about implementation details which are intentionally made unobserverable through normal means (tsc, ts server, etc). There are a variety of grammar checks that happen later; `createSourceFile` is not intended as a means to "syntax"-check a file and we have not documented any hard line between what counts as a syntax error and what counts as a semantic error.

**Comment by bradzacher** [comment]
We don't make an incorrect assumption here. We intentially choose to ignore semantic errors as calculating them is too expensive.

We instead purposely emit our own errors in cases where we want syntax or grammar checks. These errors are a subset of all of the errors TS may report.

Sebastian expected that our parser would error on the code because it will syntax error at runtime, and because other eslint parsers error on that code.

However as per the discussion on the attached issue - it is intentional that we do not error on such code because it's more than syntactically correct enough for us to lint without any issues or weirdness.

**Comment by fatcerberus** [comment]
@bradzacher What I take from Ryan's remarks is that 

> it is intentional that we do not error on such code because it's more than syntactically correct enough for us to lint without any issues or weirdness

is not something you can count on *in general* if you only pay attention to the errors produced by `createSourceFile`.  In this specific case, sure, but that's not an invariant of the API design.  Hence the comment that

> Checks might move between those phases internally for performance or correctness reasons
