### ISSUE TITLE
(intellisense) typescript tuple suggestions incorrect

### ISSUE THREAD

**Issue by yuliang1997** [microsoft/TypeScript#56058]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.83.0
- OS Version: Windows 10 21H2

Steps to Reproduce:

copy this code any .ts file

```typescript
type Foo = { field: ["type1", "11" | "22"] | ["type2", "33" | "44"] }
const b = {} as Foo
b.field = ["type1", ]
```
When I input quotes after 'type1', the smart suggestion prompts me with '11 | 22 | 33 | 44', 
but I expected it to be '11 | 22' because I have specified 'type1' as the first item in the tuple.

**Comment by RyanCavanaugh** [comment]
In general, the filtering logic tries to only filter completions when there's an unambiguous discriminant, and tries to not filter when you're in the process of writing a discriminant, both of which are at play here. Both elements of the tuple appear to be possible discriminants since they're both unions of literals, and neither appears to unambiguously be "the" discriminant.

**Comment by fatcerberus** [comment]
> neither appears to unambiguously be "the" discriminant.

Would a possible improvement be for the logic that determines this to prioritize discriminants that are non-union typed?

**Comment by NicolasCwy** [comment]
Hi @RyanCavanaugh facing the same issue, could you let me know if there is a way to achieve what @yuliang1997 was trying to get?

**Comment by NicolasCwy** [comment]
Seems like this is related to [Code hint not narrowed properly on union of literal tuple #46457](https://github.com/microsoft/TypeScript/issues/46457)
