### ISSUE TITLE
Adding always true condition using refined variable prevents subsequent refinement of variable

### ISSUE THREAD

**Issue by MichaelMitchell-at** [microsoft/TypeScript#56144]
### 🔎 Search Terms

narrow, always true

### 🕗 Version & Regression Information

- This changed between versions 5.2.2 and nightly

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.0-dev.20231018&ssl=11&ssc=1&pln=13&pc=1#code/C4TwDgpgBAqgdgSwPZygXgFBSgHygbylEgC4oByAQ3IG4oA3SgJwUrmDIEYoBfLXAkXAQyVWg2at2ZAEy9+eQsREUARuV40MGAGYBXOAGNgyVBAAelALZgANhE4AKRrb0r4pgJRklw0dTpGFjYOKDkeATg9W1sCfgQdKGdKVwgAOmUoAEI0NApqTzjsbCYIYD0mVCiYrWw+eMTk1LSgqWB0XKhOQvx+ErKKqujbWvl+UvLKiVStev0jExQoC2s7CBkmtzIPFG9BZX9xVpDZXkjhoqgEpJc3DOFszrEevqgJwahqkf567GvHV63dKZXJ5MRQABkEKgAHoYVAAM4ACyQ0QAJlAUgB3SggBFQVTQYBMNyAlJ3Y7sDp5Tj8F7FN4DKZfUa-WHwgBySCxRCREFK5HxlCEkGWTCYSCY4yZqCBs2082MpmWlhs9gAzJt3Ihdj4RSoxIFJCcwmc8F9Lv8gfdRTkwQVLv1JkMaj9tH9GmTmpkoezESj0ZjbDi8QSiSSIF6KcaqaCunTHYznZ9hqz3X6uTzgHyBUL9WKJVKnR85Rg+EA

### 💻 Code

```ts
type Union =
  | { type: 'a'; variant: 1 }
  | { type: 'a'; variant: 2 }
  | { type: 'b' };

function example1(value: Union): { type: 'a'; variant: 2 } | null {
  if (value.type !== 'a') {
    return null;
  }

  if (value.variant === 1) {
    return null;
  }

  return value;
}

function example2(value: Union): { type: 'a'; variant: 2 } | null {
  if (value.type !== 'a') {
    return null;
  }

  if (
    value.type === 'a' && // should always be true
    value.variant === 1
  ) {
    return null;
  }

  // Now there's a type error
  return value;
}

function example3(value: Union): { type: 'a'; variant: 2 } | null {
  if (value.type !== 'a') {
    return null;
  }

  if (
    value.type && // should always be true
    value.variant === 1
  ) {
    return null;
  }

  // Now there's a type error
  return value;
}

```

### 🙁 Actual behavior

Type error

### 🙂 Expected behavior

No type error

**Comment by RyanCavanaugh** [comment]
Bisects to #55464

**Comment by ahejlsberg** [comment]
Hmm, yeah, that's not right. The issue here is that the `type` property isn't classified as a discriminant property in the computed type `{ type: 'a'; variant: 1 }  | { type: 'a'; variant: 2 }` because it has a uniform type. It's only classified as a discriminant property in the declared type `Union`, but with the change in #55464 we're examining the computed type. I think the fix is to always examine the declared type as long as the computed type is a subset of that type, and only examine the computed type when it isn't a subset (e.g. because of a preceding type predicate narrowing, as in #55425).
