### ISSUE TITLE
`Object.create` used in ES3 output

### ISSUE THREAD

**Issue by SamuelEnglard** [Microsoft/TypeScript#5623]
I'm currently compiling to ES3 yet the TypeScript 1.6 compiler is using `Object.create` for inheritance.

**Comment by mhegazy** [comment]
this is only used if you `extend null` or an expression that reruns null. 

so are you seeing it break in other scenarios?

**Comment by SamuelEnglard** [comment]
I'm seeing it done on https://github.com/SamuelEnglard/Humanizer.Js/blob/master/Localisation/NumberToWords/ArabicNumberToWordsConverter.ts

**Comment by mhegazy** [comment]
a self contained repro would be highly appreciated.

**Comment by SamuelEnglard** [comment]
https://gist.github.com/SamuelEnglard/778cecb30b64ac9dcda6

**Comment by RyanCavanaugh** [comment]
It doesn't actually *invoke* `Object.create` unless the base class type is `null`, which isn't supported in ES3 anyway.

**Comment by SamuelEnglard** [comment]
That's true, and therefore it is safe. Just seems wrong to output `Object.create` in ES3 even if it will never be called

**Comment by mhegazy** [comment]
The reason is we can not have multiple versions of the extend function. the function is only defined if it has not been defined before. imagine you compile with --t es3, but then some one takes a dependency on you but run in ES5, now depending on which piece runs first, a version of extend will be loaded. so to solve this issue we have one version, but we condition the use of ES3 APIs, and check for them at design time.

**Comment by SamuelEnglard** [comment]
Ok, that makes sense. Thanks!
