### ISSUE TITLE
Typescript Find All Reference does not work in monorepo

### ISSUE THREAD

**Issue by jaysoo** [microsoft/TypeScript#56268]
Does this issue occur when all extensions are disabled?:No

```
Version: 1.83.1 (Universal)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:46:55.789Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0
```

Steps to Reproduce:

1. Git clone the [Nx monorepo](https://github.com/nrwl/nx)
    ```shell
    git clone https://github.com/nrwl/nx.git
    cd nx
    pnpm install
    ```
2. Open vscode `code .`
3. Open file `packages/devkit/src/utils/async-iterable/create-async-iterable.ts`
4. Find all references of `createAsyncIterable`

**Expected:**
All references are found (should be 17 invocations)

**Actual:**
No usages found (only reference is the declaration)

<img width="1565" alt="Screenshot 2023-10-26 at 11 03 16 AM" src="https://github.com/microsoft/vscode/assets/53559/6871d0b6-674f-4ffb-8e80-b29c90ae8a48">

## Related issues
https://github.com/microsoft/TypeScript/issues/30823, https://github.com/microsoft/vscode/issues/65102

**Comment by RyanCavanaugh** [comment]
This seems working as intended. You have a "solution" tsconfig at `packages/devkit/tsconfig.json`, so as far as TS can tell, that's the entire "world of analysis" available to it (in other words, this appears to be you *trying* to make sure nothing else loads, and nothing else loads). TS doesn't communicate with VS Code about what the workspace root is - these are kind of supposed to be separate concepts - so there's nothing that tells TS that it ought to go looking into `packages/js` for example. It appears to be "not your code".

**Comment by jaysoo** [comment]
So the only workaround is to not use solution tsconfig? Is there anything else that can be done tell VS Code to follow the paths from root tsconfig file?

**Comment by svallory** [comment]
it's been a while @jaysoo , but just in case...

And for others stumbling upon this issue...

What @RyanCavanaugh meant by "solution tsconfig" is that the tsconfig file inside dev kit defines all that is need to be compiled. It's the **entire** thing and not, for example, part of a larger solution, a composite tsconfig which references or is referenced by other tsconfigs.

VSCode asks TS about project information, never the other way around. And When typescript compiles the devkit project, it will follow the tsconfig.json, and only look at the files specified there and in referenced projects.

Since from the tsconfig the TSC does not know of the existence of other projects, no reference will be found.

Your options are either to reconfigure the tsconfig of the projects to use project references, or to create a separate `tsconfig.vscode.json` which includes code from all projects and tell vscode to use it instead via workspace settings

(actually, maybe you'll have to create a `tsconfig.build.json` for building and optimize the original just for the IDE)

I suggest you start using project references
