### ISSUE TITLE
Typescript fails to generate an error when comparing deeply nested TypeBox types

### ISSUE THREAD

**Issue by sanderalvin** [microsoft/TypeScript#56291]
### 🔎 Search Terms

"typebox no Typescript error" 

### 🕗 Version & Regression Information

- This is a crash

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.0-dev.20231031#code/JYWwDg9gTgLgBAbzgZRgQxsAxgGjgFQE8wBTOAXzgDMoIQ4ByAAQGdgA7LAGzWCgHoYxEgCMIADwYBuAFAz+-OADkAgvgCSANQCicbQA0VAWQAKAGV0Baazdu25Q0ihBouXJRmAA3EkScBeRBk4ELguEh8uAEYALiDQhLCIki4AJjiEYMTsqggIOJYYKA4Ac1lskPJy0KqZWplHMgAhYBKPTB8-MkDMhPDI2PiK-pT0oYrQ3Py4QuL2MqyJkJE0KAKi0urs2oTa+oUCAHcIOAATEhIwLkI4dhJCklO4RpY4Eu8yLGgoEix4EigtCgMioAFdOJgIOxbp4fE1VgAKMCrNAgOLIFxudofLoAbQAugBKOItNqw3zCAnjOA-GCgqDQ5FQVGychyA52Tk2dmKfAATRM2iaAHl9HpDKYLHAuVyHMJnK4uF0xOIunBAqhPFgADyNCBUBVuZUSLoAPlkX3YhUNSuEKrVgS6ADphSIAFa-GAI3qhEbROLOlSAtCEBHO10ev7exaJP1jQPB0Ph92e6NLSZ5APCJ2oOYlBGEnAx3aEwsx8ilosV2QNeWk42q+Ua9CYHV6g31u0m4TmmSW62d0j2psEbMR1M+kJ+wYJ5lJscpqOT2PJNJZ0hOoNzsMLyNe5cTKbrkg5jbzAtF9PLVbH095i-FmqV8vP6s86jgv7AKHUPJIlFojaDZdMScCDqI3ZOJkBwhLS9KMgBsgHGy8iKAAwvSPzsDA1zPAAFsAryEXAHBfICnpOnA6jwCwoJgJALCPM8Jx4WgPhwACQJwGgRHQgAROw5LwlAfEceIqJXCQqFUQahAQKCcCfnQIAkNhcB8VMoloGIPgBgRryHMAbhvB8HGAtAcAImRPx-HAIgkKxXjflAhLSeosnyYpnDKap8AaXkon2VwECHHpxGGcZSjCvgJnsZxFkIqR3yenZDlsc5rlghC37QisUD-sygEYoqwGUkSJKtKVpBUsucEMnATIsnU75ZV+P5TAVqLopitpDpBJCgeBw5QdJsEkHS9WNSASGKChHIygtMhAA

### 💻 Code

```ts
import { Static, Type } from '@sinclair/typebox';

// NATIVE EXAMPLE --------------

type SmallNativeType = {
    level1: {
        level2: {
            foo: string;
        };
    };
};

type BigNativeType = {
    level1: {
        level2: {
            foo: string;
            bar: string;
        };
    };
};

// Two deeply nested types give correct error
function nativeBar(param: SmallNativeType[]): BigNativeType[] {
    return param;
}

// --------------

// TYPEBOX EXAMPLE --------------

type SmallTypeboxType = Static<typeof SmallTypeboxType>;
const SmallTypeboxType = Type.Object({
    level1: Type.Array(Type.Object({
        level2: Type.Array(Type.Object({
            foo: Type.String(),
        })),
    })),
});

type BigTypeboxType = Static<typeof BigTypeboxType>;
const BigTypeboxType = Type.Object({
    level1: Type.Array(Type.Object({
        level2: Type.Array(Type.Object({
            foo: Type.String(),
            bar: Type.String(),
        })),
    })),
});

// function foo(param: SmallTypeboxType): BigTypeboxType {
//   return param;
// }

// Currently this is incorrect. It supposed to have error as in "nativeBar" example
// If you uncomment "foo" above: This will give error (correct behavior)
// If you uncomment "foo" below: This will NOT give error (incorrect behavior)
function bar(param: SmallTypeboxType[]): BigTypeboxType[] {
    return param;
}

// function foo(param: SmallTypeboxType): BigTypeboxType {
//   return param;
// }

// ------------------

```

### 🙁 Actual behavior

No Typescript error generated on line 58 inside `bar` function.

### 🙂 Expected behavior

There should be an TS error on line 58 inside `bar` function just like there is a similar error inside `nativeBar` function on line 24.

### Additional information about the issue

I first reported this issue to TypeBox repo, but I was advised that this is actually a Typescript problem.
Link to Typebox issue: https://github.com/sinclairzx81/typebox/issues/636

**Comment by sanderalvin** [comment]
Some PR-s which are related to the reported issue:
https://github.com/microsoft/TypeScript/pull/56169
https://github.com/microsoft/TypeScript/pull/55638

A previous issue opened by TypeBox creator:
https://github.com/microsoft/TypeScript/issues/56138

**Comment by fatcerberus** [comment]
TS failing to produce an expected error isn’t a crash.

**Comment by ahejlsberg** [comment]
Problem here is that `SmallTypeboxType` and `BigTypeboxType` have three levels of nested `Array<T>` instances after which we consider the types deeply nested. The instances all originate in the same generic declaration (the `static` property in `TArray`) and we simply don't have a way to recognize that the instantiations eventually terminate.

**Comment by sinclairzx81** [comment]
@ahejlsberg Hi, thank you for taking the time to look into this. 

> Problem here is that SmallTypeboxType and BigTypeboxType have three levels of nested Array<T> instances after which we consider the types deeply nested. The instances all originate in the same generic declaration (the static property in TArray) and we simply don't have a way to recognize that the instantiations eventually terminate.

I note that the use of `(T & { params: P })['static']` on `Static` seems to be the source of these issues (which TypeBox is using for recursive inference); but was wondering if there might be a more compiler friendly way to uniformly handle recursive inference when applied to both recursive and non-recursive mapped types (somehow proving to the compiler in advance a type was finite when non-recursive)

### Workarounds

Based on the above, I had experimented with a library level workaround to perform a forward query on the type searching for interior instances of `TThis` (indicating the type is recursive) and only perform the reverse inference if found, otherwise just use `T['static']`. This does allow nested Arrays to go very deep (8 levels and beyond) for finite types while retaining support for singular recursive inference (albeit with a possible inference performance hit)

[Workaround 1 (Inline)](https://www.typescriptlang.org/play?ts=5.3.0-dev.20231102#code/C4TwDgpgBAShDGBXATgZwJYDcIBVzQF4oBlYAQ2HXgB5RIB7AM1gRQ2z0gD4AoeegHapgLJGiy58UIpwgA6OGPYQAFDgAW6VNK5RZcgPIAjAFYJgKgN5QBEAB7AAXHs3aAvgEoPPAPQ+o-EIiyKzi2M6KbBKy0lDWtg7O8fZOcTYpSemJUHK5UG75hQV+NoIAtCFgIagQAuRGADYQPHyCwlAAIhAQYDFE1DhQKbUAJto4xPDqEAC2ZFwqqFOzZM44Hjp6+Iam5lY8UFBN2A0AjGvbAILIyGQgatvGZvAWlgeHRxAnAEwXkHLXW73fRPPZvD4fY4QBoAZj+8kBdwe-1BL32EIhUIaABZ4QCbkiQbs0eCMZivtCAKx4xHAx7E17vMnkk4ANhpBLpKIZ6OZZKxAHYOUDkfJUYy+XysQAOYVIpbTOYeAA0TMlh08KrVfM1qvVuu1HwNZONRq8evy5p4nhadGgxDmDQasiM9DsfRI5EoNDtTBIjud+Fd7vwvEC7QdZCdLrdHq6PVkop2zwlUEY9HoeNIyHQAgA5ipvJrbVIAELoPMxkOQWKkChUWj4P3lytB2Oh1pBKAtqtx7q9fBJ8W89OZrb-bO5gtaw5GMjILPAHP5wvWrwtRiIAQvdCCKDACDCFRgedkGbOSPRtvViAAbQAuh5nD3r7IH3F3iFgCgBFAT7cZgAbigEpqDKIY7EgF4hhuehkGtFoSjKZCUNQtD0IwzCsOwnDcLwrDfH8OtvWcABFRAIGQEB9ykdNkCgXNhDIbdDygP0cA0LQ5CgAwBAaajEBqP9TxmbRcwPNBzAY5h0y3EY5EIqB8OUlTVLU9Syh4ewwDgkQ7SgAAJMhUE41AAAVkHoSBkEoQ8Bggg8BDGPQLKsyjbNQXQiFJW8AGkGN-ABrCAQHY+9nCMkzXAGPz710YYnO0JcKKgAB+KBTigZwAAZrVvYLQuYHB7wc0YxIERhKNgd50syhLnJgGr92QCj3mcRgoxqNr0mweCtMg3SaJrSLTPs+rxkmRV5mkd5BnGvRTLS5qUscWbSsSvRaWoXNKvoszdHSkbov2rK1vmnBxW2iqqpOw7jNM1zrI86gTtWw4SjIEYRnQShBCjIbWOmEIclyd4OoaLr+p0myAc9esaDmhwyr0SaVmVKAzPW5yt0CgR6AAdwEd8iAfLz3iOrQBnipGNuS5oIXStQoAAMjSf8z1QZxMc8W8AHImO9XmSpA-wQiUCRhOAdQ1TWPmBaoIX1XVEpGFzH7oBPKXEP8DTdb1-X8MUiZljmRSDfNi3zahwbxMojr4GgY2po-Q55fgZwcbxwn3nZ0SPYEXGCaJ+8EKQy3w4j5SjdpM3I7j+P0OtmHbeQe3Ha2xHHOcp2VmprOJpNsgXYB5xefnIFefeN3nC24iGxwdGpa0PnfdQIWuF4NxY4Tnu46N8Vu97oeLaTvSpBwR73PQViiEUOCRmoYRlzzdGc7mXhtJtuo7bIB29EuzPkYnyynunzysYL53STtUv6AZSvXa9KhMj8gKoAKsKLyfhHYsb1wW5Em3OK+RQ462HuAg2RtJz5kHhAuBqlR4BQkmnFGS4pwXxRoXYuN8oD8zQfmB+UBq5EPwXmUBSl4GUJUkbUysCqH0MwoglOKCOKuAwWvIu198Clybm3Ku39nC8IAQBIBt5sohy7mHBh0iMJG0iGEZoUiZHKOQog-SOB5HKDgCMRADsxo02zqjdetZv4DHRreDRoQtEQB0XonAXA4pMO3qnXejtNESH0fnTBU085HyMZw-h8M1juOwNo3REAqbkJUdEzSJRZB0JiVQxBIwEANHnNAAQZ5Dwnj3jEUkm8Yabm3L9X8ISImHw2hwhY8AowNDnPAQKzgVC8NkGsUyGwCC6HWMEqxHj7HvAKSIIpO49wZ3Yf4hY6s-Z6CfJtTkkTDiDLTFuEZv4D7sMnjZM+CwqhuS2YeNYsyLoMgWRBaGQyVklM9MvQsaxoFkK7kAA)

[Workaround 2 (Integrated)](https://www.typescriptlang.org/play?ts=5.3.0-dev.20231102#code/JYWwDg9gTgLgBAbzgFQJ5gKYBoUGUDGAFhiAIZwC+cAZlBCHAOQACAzsAHb4A2pwUAehjoMAIwgAPRgChpwzHABKGfAFco7AG4Y0CgLxxcMUjGD4APPIwRqSleq06RAPmn4IHVvGVqNwbboYcAaBAHQ+Dv4YABTIhMCswc4oIqEA8qIAViow0UgcGBIwAFwo8YkUAJSV0gICcO6e8FD2ftqlEW1O+ohwBUWl+YUlvf0jQwNwodOUs1RUdX0eALQtYC2sGBzGotwYso1ecAAiGBhggcFw5shww1sAJonIBMRkztGsRCSkpciVSRSmHSWRyeWkcDge203AAjH9UgBBKBQUioWKpDLZfC5BAQyFQjAwgBMCOByNR6LCWLBeIJBOhGG4AGYyRhQhS0RjgTSceD6fTGdwACxsjkornU0F8ukCwVEpkAVjFnKpmOluPxcvlMIAbCqJWqeRr+dq5UKAOwGync9m8zVms1CgAc1q5XzepEqWC1jshVW9vrNAZ9fpDQYJ4blUcj1VDlDj0iqsishjI3G4gXEEkuBiMJjMlhENjTpAzWckgVch3guHTmZE2dzJzOFxEtpB2IdNAgEDFRignAA5tEagGUyI4AAhYBDis5yd54ymCxWEszueNysuNweI4b+fN07nQId+2m6i9-swQccEeByGiUhQa+3+9J6qyaiqLimDxwGAMC8aIwGfUgQFKOsywbTAmxEABtABdSpSgPLcF0wJDEHxFoYHUDg4FA1EQAAbjgRZzGWO4JEwHE7hRaAk1kRZllYtj2I4ziuO4njeL4-iBJ42p6nzFdSgARVUDAoFQADJ0vKA4E4LxSC4IC4BLZA4gSUI4DSDhuFk1RNjgWI4AAMl6IjwNYUoAAUEyU2xLx-B5QmEuBBK87yfN8vzlmkUBIFgOAACo4FIZ4RESWh6CYNhOB4PhBCsbMZGkQpgvgVMAAlIu01hlC8G5qMAjgniBIDQheb4yCQ5IDHxW57nKxJ4M4ahpLgAAZUrHiizBWGq14fhwaZQg6rrFD61rKqGmrPSQxDfQAfjgPLWAK8xuuSFqKpvKS4AjNaDqCCNSg2gqipgcxFGSX1SmoMtNlkTLoGyydLvKOy6EwWBgCAkq9oGqrkB+iA-tMICGt6fF4IAaSUgiAGsMFQTTEIu-LyhuBHEN2op+oAqBDrW2E4FKAAGI7KHg1H0dsZBEJmirJsU6atTJlnEg5gUTpJs6BUe57BchYXuBejKaPeuSFC+hIgcJ2bAnmkb3mCJrubm6qAGE9wOnFoHMNm4DsnATbuuA1vlwqgJuuyCbK-aBat4nDqxzacct4pNeB7XkAAMR-HFgA8Y2OE6xSzaRyOlGSa3sYSa7zAdrXTtd9OPa273faViqVeq+1w9j3B4-WxPWHByGAdYcxS4pmmUC1gvkAASW2aTNhxYuuvrhPPaTu26+SH3IWavOQfmgBVDhQ44HvFL78uB9t4r69Hpu-Zb5BVDAPYF8MMubeT9fc6dyfqtVA+l5t4eKbPomW-BkAEgwa+j4ru+N-H8--cRVhUBcFboBVEMAjYmxvp-U+Y9m7RWqsA6SJhwER17h-FeX8H7KzgVpcoGcXalHxE9CW+wpZZVlkEUShYf6P2wWrUgOAHJ+x-MjDgEAADuHAsIGHqlcW+yBHZE3TviNaZlLJIGsiAWypsEzwUYCpFcjBmbkXqC0XwjhCImEIPiP4sj5FmEUX6P0ixqCcGAIBDRMBCBAA)

### Recommendations

Honestly, I think the update on https://github.com/microsoft/TypeScript/pull/56169 would likely solve the vast majority of cases (where I'd imagine deeply nested arrays of this form to be quite uncommon), but was wondering if there were recommendations from the TypeScript team for handling recursive mapped types in general; possibly approaches that would allow the compiler to quickly prove in advance a type was finite using something akin to the above `HasThis<T>` check.

Are there any recommendations for approaching recursive mapped inference?

**Comment by ahejlsberg** [comment]
> I note that the use of `(T & { params: P })['static']` on `Static` seems to be the source of these issues

It's actually a combination of things, most of which are implementation details of the compiler. The workarounds you present ultimately depend on the (implementation defined) order in which generic type instantiations are materialized.

When a type is materialized, it is assigned a type ID, which is simply a sequentially increasing number. When checking for deeply nested types, we only count types that have increasing type IDs because increasing IDs typically are an indication of some pattern of recursively occurring instantiations.

In the workarounds, the use of (recursive) inference in the `Static` conditional type causes types to be materialized inside-out, meaning that the deepest `Array<T>` instantiations have the lowest type IDs, and the types therefore don't appear to be deeply nested. But minor (and seemingly irrelevant) changes to the workarounds cause instantiation to instead occur outside-in (which would be typical because type instantiation is deferred for as long as possible).

So, the workarounds work due to implementation details that could change. That's unfortunate, but as of now we have no better solutions. We'll continue to think about it though.
