### ISSUE TITLE
`ES2023` missing for `target` in docs?

### ISSUE THREAD

**Issue by thernstig** [microsoft/TypeScript#56303]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

Caveat: I am not entirely sure where these faults stem from, but they have existed for some time and causes confusion for users. I am starting here.

From: https://www.typescriptlang.org/tsconfig

- `es2023` is missing for `target` (but it should exist, see https://github.com/microsoft/TypeScript/pull/49636)

If we use VS Code it reports that it cannot be used:

![image](https://github.com/microsoft/TypeScript/assets/30827238/ca77ad5a-4e32-4cbb-acd9-644e56c1271e)

But https://json.schemastore.org/tsconfig  has it.

I have no idea where the fault in VS Code comes from as it is/should be checking https://json.schemastore.org/tsconfig, and I also do not know why it was not included on From: https://www.typescriptlang.org/tsconfig.

It is possible I should split this up in more than one bug report, if this is a bug.

**Comment by RyanCavanaugh** [comment]
This is a bit confusing - the error message is auto-generated from the set of possible values that the parser knows about. *Today* `esnext` and `es2023` are the same value, so it doesn't realize it needs to print them back separately since they're not long-term semantically identical.

While we're at it, we should remove `es3` from the printback list.

**Comment by thernstig** [comment]
@RyanCavanaugh note there are two bugs then. The error message from the parse + the docs issue on https://www.typescriptlang.org/tsconfig.

**Comment by fatcerberus** [comment]
I’ve always thought the all-lowercase variants were canonical, fwiw.  I assume the camel-case versions probably originate from the TS source since there’s an enum for it.  Though I guess ultimately the tsconfig parser doesn’t care about the capitalization.

> Today esnext and es2023 are the same value

Wait, that doesn’t seem right.  When I was working with the compiler API `ESNext` always had value 99 while all `ES20xx` were 0-based; there was never a case where one of them overlapped with `ESNext`.  Has that changed?

**Comment by RyanCavanaugh** [comment]
Oh, I got messed up, ignore almost everything up there. OP is confusing `lib` and `target` -- `es2023` is a valid lib, but isn't a valid target because there's nothing different between es2022 and es2023 re: syntax

**Comment by RyanCavanaugh** [comment]
New runtime methods (i.e. things that can be polyfilled) are not syntactic features.

>  if I have "target": "es2022" then it cannot have "lib": "es2023 I assume,

You can. Did you try it?

**Comment by thernstig** [comment]
> New runtime methods (i.e. things that can be polyfilled) are not syntactic features.

By what definition? The top 10 Google results for `javascript es6 features` give e.g. `Array.from()` in a list of "ES features". The core of the problem is how `target` is documented.

> You can. Did you try it?

I did try. But the core of the problem is this:

> Changing target also changes the default value of [lib](https://www.typescriptlang.org/tsconfig#lib).

I would suspect many users e.g. know they want to support `es2023`. Then they might go about their day and just set `"target": "es2022"` since they noticed that `es2023` is not a valid option. But they might then forget to set `"lib": ["es2023"]`.

Why not just include `"target": "es2023"` even if nothing new is happen, since that could then also change the default lib?

**Comment by RyanCavanaugh** [comment]
I'm trying to give you a definition. A new method is not a syntax.

Doc improvements always welcomed.

**Comment by thernstig** [comment]
> I'm trying to give you a definition. A new method is not a syntax.
> 
> Doc improvements always welcomed.

I will give it a try soon.
