### ISSUE TITLE
Property assignments are not valid for intersections of generic class instances with union types

### ISSUE THREAD

**Issue by benStre** [microsoft/TypeScript#56320]
### 🔎 Search Terms

"generic boolean intersection", "intersection type", "generic class property assignment", "generic class property setter"

### 🕗 Version & Regression Information

- This changed between versions 4.2.3 and 4.3.5

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYGwhgzhAEDiCmA7eAnAlsA8gIwFb2ABcAeAFWgF5pEBXAW21QD5oBvAKGi+gnkOgAeACgEAuaKQCUbaAF9289sAD2iCPwBuARkrV4AdzhJUGHPiJDpkTtwTJ0WPAX4AyaENbQwAfnHr0iADmctAAPjLYvtT0jChykgDc7NoAdAK6ACwAzABMCdAA9AXQxAC0pRIAngAO8NAA5LQMqPXQaDCIyvyQEGiBiGDYIHWEytCENXX1pPUp7PMqapo5usiGdiaO5oSWXhA2XBsOZs7Qbp4+foQBwbJJGjlpmXmFxfrKKADW+wvgUEb2UxOIgAdTQhAAFsoaIQAMp8QioMirGLMNgHaAAEwI4BQdTEEgUC1U6mgGiyqwMAM2J1B4KhMPhhERKF21m41OOwMIYMh0LhCNQZ3cFyi-jQQRC4U8kXETVi8XuWSeVAyLyK0HeXx+oB60AAch86GAQLT+BwObx+MICfLUNJPPJFItSRoMpTDIaUMbTdy2fsOV6fWbhR4vGLrhLbmEIlE7XFZIlkhkVdA1fkNVrvkA

### 💻 Code

```ts
class GenericObject<T = number> {
    set x(x: T) { }
}

const v1 = new GenericObject() as
    GenericObject & ({ a?: string } | { b?: number });
v1.x = 432; // <-- Type 'number' is not assignable to type 'T'.


const v2 = new GenericObject() as
    GenericObject & { a?: string };
v2.x = 42; // works


class GenericObjectWithoutSetter<T = number> {
    declare x: T
}

const v3 = new GenericObjectWithoutSetter() as
    GenericObjectWithoutSetter & ({ a?: string } | { b?: number });
v3.x = 42; // works

class NormalObject {
    set x(x: number) { }
}

const v4 = new NormalObject() as
    NormalObject & ({ a?: string } | { b?: number });
v4.x = 42; // works
```

### 🙁 Actual behavior

TypeScript shows an error:
```
Type 'number' is not assignable to type 'T'.
  'T' could be instantiated with an arbitrary type which could be unrelated to 'number'.(2322)
```

### 🙂 Expected behavior

The property assignment should be valid. This works with all other type intersections, e.g. `GenericObject & { a?: string }`, just not with union types like `GenericObject & ({ a?: string } | { b?: number })`.

**Comment by jcalz** [comment]
Whatever's going on here is likely because `boolean` is actually the union `true | false`.  If you replace any of your other types with a union it will show the same behavior.  So it's the intersection of a generic class with a *union* that's the issue... and intersections with primitives are weird, so I'd think you'd talk about objects instead.  

That is, you might want to translate this example to:

```ts
class GenericObject<T = number> {
    set x(x: T) { }
}

const v1 = new GenericObject() as
    GenericObject & ({ a?: string } | { b?: number });
v1.x = 432; // <-- Type 'number' is not assignable to type 'T'.


const v2 = new GenericObject() as
    GenericObject & { a?: string };
v2.x = 42; // works


class GenericObjectWithoutSetter<T = number> {
    declare x: T
}

const v3 = new GenericObjectWithoutSetter() as
    GenericObjectWithoutSetter & ({ a?: string } | { b?: number });
v3.x = 42; // works

class NormalObject {
    set x(x: number) { }
}

const v4 = new NormalObject() as
    NormalObject & ({ a?: string } | { b?: number });
v4.x = 42; // works
```

[Playground link](https://www.typescriptlang.org/play?#code/MYGwhgzhAEDiCmA7eAnAlsA8gIwFb2ABcAeAFWgF5pEBXAW21QD5oBvAKGi+gnkOgAeACgEAuaKQCUbaAF9289sAD2iCPwBuARkrV4AdzhJUGHPiJDpkTtwTJ0WPAX4AyaENbQwAfnHr0iADmctAAPjLYvtT0jChykgDc7NoAdAK6ACwAzABMCdAA9AXQxAC0pRIAngAO8NAA5LQMqPXQaDCIyvyQEGiBiGDYIHWEytCENXX1pPUp7PMqapo5usiGdiaO5oSWXhA2XBsOZs7Qbp4+foQBwbJJGjlpmXmFxfrKKADW+wvgUEb2UxOIgAdTQhAAFsoaIQAMp8QioMirGLMNgHaAAEwI4BQdTEEgUC1U6mgGiyqwMAM2J1B4KhMPhhERKF21m41OOwMIYMh0LhCNQZ3cFyi-jQQRC4U8kXETVi8XuWSeVAyLyK0HeXx+oB60AAch86GAQLT+BwObx+MICfLUNJPPJFItSRoMpTDIaUMbTdy2fsOV6fWbhR4vGLrhLbmEIlE7XFZIlkhkVdA1fkNVrvkA)
