### ISSUE TITLE
String.prototype.includes() searchString parameter should accept Readonly<string>

### ISSUE THREAD

**Issue by nicolasperez19** [microsoft/TypeScript#56331]
### ⚙ Compilation target

ES2016

### ⚙ Library

ES2015

### Missing / Incorrect Definition

It should be possible to pass a string of type Readonly<string> into String.prototype.includes() without any compilation errors.

### Sample Code

```TypeScript
const doesDescriptionDataContainKeyword = (
  obj: Record<string, string>,
  keyword: Readonly<string>
): boolean => {
  return Object.values(obj).some((value) => value.includes(keyword));
};
```

### Documentation Link

This new change would not conflict with the [String.includes()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes#syntax) specification.

**Comment by MartinJohns** [comment]
Given that `Readonly<string>` is basically just `string` it already seems to work. What error are you getting?

**Comment by fatcerberus** [comment]
Yeah, this already works as far as I can tell:
[Playground link](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAJiAphAIs4AnAlgByl8FAQyiIGFxSswBpRATwHcQM4YBeGACgCgYYQAIwBWALhgAlRKFYAeaNjABzADQwF1JQD4VfGAGsGzVuKlEEYADb15URdp4BKcYJAhLiImA5aYAbz0MRCgAVwxvAHkRaSgAOgA3IksQ5C4hYUdYiBAAW0QuLkTkxEcfGCKU2OpgZLhUwyYWOEdHAG4eAF92oA)

If you hover over `keyword`, you see that the compiler just treats it as `string` and therefore there is no type error.  `Readonly<string>` doesn't really make sense as a type since strings are already immutable to begin with.

**Comment by nicolasperez19** [comment]
Looking back at my code, I realized my example is a little more contrived. I was parsing a string from zod and then converting it into a branded type.

✔ When I passed in the branded type without making it Readonly, it would work:
```ts
type Keyword = string & z.BRAND<"Keyword">;
const doesDescriptionDataContainKeyword = (
  obj: Record<string, string>,
  keyword: Keyword
): boolean => {
  return Object.values(obj).some((value) => value.includes(keyword));
};
```

❌ However, when I made it Readonly, it wouldn't work: 
```ts
type Keyword = Readonly<string & z.BRAND<"Keyword">>;
const doesDescriptionDataContainKeyword = (
  obj: Record<string, string>,
  keyword: Keyword
): boolean => {
  return Object.values(obj).some((value) => value.includes(keyword));
};
```

Since @fatcerberus mentioned that strings are immutable by default, I can just go with the first option
