### ISSUE TITLE
`import type from from "foo"`

### ISSUE THREAD

**Issue by magic-akari** [microsoft/TypeScript#56376]
### 🔎 Search Terms

- type import
- parser
- import type from from

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAMyhEjmoERQKYEMDGMGA3HAPRlwQDWAUKJLHDAJ5jZwAeaKcWehEuUo164aPFbseqJL34EipCnDC4oAZw7YoyKEA

### 💻 Code

```typescript
import from from "react"; // ok
import type x from "react"; // ok
import type from from "react"; // parse error
```

### 🙁 Actual behavior

parse error

### 🙂 Expected behavior

I have merely observed its inconsistency, without discerning whether it is by design or a bug.

**Comment by fatcerberus** [comment]
Looks like the parser is interpreting `type` as an identifier on line 3 and then choking when it sees the second `from`.

**Comment by evanw** [comment]
There's still a problem with `import type from = require('foo')`: [(playground link)](https://www.typescriptlang.org/play?ts=5.4.0-dev.20231118#code/JYWwDg9gTgLgBADzgXjlApgRwK7AwCgCIMBDAYxkIEoBuOAenrggGsAoUSWOAMyghAo0WXAWLpylWgyas2HcNHgwAnmHRwVQjDjzp8AclIUDVGc3aclcVet79BqHaP1GJJs4zhgSUAM4a6FD8UGxAA). That seems like a bug if it's expected that `from` is allowed to be the name of an imported type. Should that be fixed as part of this issue as well?

For context, I'm commenting here because I was linked to this bug from esbuild's issue tracker, and I need to figure out how to handle this kind of type syntax in esbuild.
