### ISSUE TITLE
Variance annotations are not allowed in type aliases for interfaces

### ISSUE THREAD

**Issue by bgenia** [microsoft/TypeScript#56390]
### 🔎 Search Terms

variance annotations

### 🕗 Version & Regression Information

- This seems to be a bug
- This is the behavior in every version I tried since variance annotations came out

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAKgYgewQHgGoEMA2BXCA+KAXigG8oA3LXALigx2gF8AoUSWAIXQCdkBLAHZQE2YHSr4isRCnq4CAegVQA8gGlmzQcAjcAZugDG0AJIy0EgmUoNacploE79R0116Dho8QwIQAHjoCACYAzlBmSBa+pIxQSqoarODQ7vxCImL2BMQmadnxygCi3NwI3MxAA

### 💻 Code

```ts
type TFoo<Value> = { value: Value }
type TBar<in out Value> = TFoo<Value> // OK

interface IFoo<Value> { value: Value }
interface IBar<in out Value> extends IFoo<Value> {} // OK

type Bar<in out Value> = IBar<Value> // Error
```

### 🙁 Actual behavior

The error says that variance annotations are only allowed for object types, but `IBar` is an object type.

### 🙂 Expected behavior

There should be no errors

**Comment by RyanCavanaugh** [comment]
This is a correct error because it prevents a footgun with variance annotations.

So let's say you have
```ts
type TypeRef<T> = TypeTarget<T>;
type TypeTarget<T> = TypeFinal<T>;
type TypeFinal<T> = { value: T };
```

Given an assignability check from `TypeRef<Source>` to `TypeRef<Target>`, we could in theory do any of these three operations equivalently (since they all eventually end up at the same place):
* `Source` to `Target` (if `TypeRef` is covariant on `T`)
* `TypeTarget<Source>` to `TypeTarget<Target>`
* `TypeFinal<Source>` to `TypeFinal<Target>`
* `Source` to `Target` (via the `value` property)

For performance reasons, it's best to start as low in the stack as possible, so when there's an immediate type alias, we instantly go to the second bullet point and do the comparison starting there. This means any variance annotations present on `TypeRef` are ignored.

This is *not* a bug, because variance annotations are not intended to *change* the variance of a type. If you wrote a variance annotation that isn't the observed variance of a type, that's an operator error. In this case since we know the variance annotations on `Bar` aren't ever going to be used, we should be erroring since you're clearly annotating the wrong place (and probably shouldn't be annotating at all).

This is also somewhat alluded to to in the FAQ https://github.com/Microsoft/TypeScript/wiki/FAQ#structural-vs-instantiation-based-inference as regards to inference of type parameters (rather than comparison, as occurs here)

The Handbook entry really needs to emphasize that variance annotations are **not** for *changing* the variance of a type parameter, despite all outward appearances.
