### ISSUE TITLE
For the same input type, 'infer' produces a different type depending on the RHS of its surrounding conditional

### ISSUE THREAD

**Issue by yseymour** [microsoft/TypeScript#56405]
### 🔎 Search Terms

infer conditional never undefined

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.4.0-dev.20231114#code/C4TwDgpgBAogNhAthAdsAKuCBGAPOgPigF4p0oIAPYVAEwGcoBlCYXASxQDMIAnKAKpEA-IKgAuKCggA3PgG4AsAChQkWAmRpMkAEz4ipclRooGzVh259BIsZPRLlKtdACSKMAFdgJC2xQvRAAjPiIAHygvMwguTghaJxcsKAAlCHovOGBsP3gkVAwsPA9vYAJ5KAB6KqhcAFooAHkAaRUoatqAPWEVZPV0zOzdPM1CnQh9Up8KzrrGgDkAe19W9rmelSA

### 💻 Code

```ts
type ElementType1<T> = T extends Set<infer U> ? U : never;
type ElementType2<T> = T extends Set<infer U> ? U : T;

type Input = Set<number> | undefined;

type Result1 = ElementType1<Input>;
  // number

type Result2 = ElementType2<Input>;
  // number | undefined
```

### 🙁 Actual behavior

When the false branch is `never`, `infer U` produces `number`, as expected.

When the false branch is `T`, `infer U` produces `number | undefined`. This is unexpected.

It is surprising for one branch of the type to depend on the other.  Is there something I am missing?

### 🙂 Expected behavior

`infer U` to produce `number` in both cases.

**Comment by fatcerberus** [comment]
`infer U` produces `number` in both cases; the difference in behavior is entirely down to the false branches.

This is due to [distributive conditional types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types).  The conditional expression is evaluated once for each member of the union `Set<number> | undefined` (think `Array#map`) - the first time it takes the true branch (`T = Set<number>`, `U = number`), the second time it takes the false branch (`T = undefined`).  So `Result1` ends up being `number | never` which reduces to just `number` while `Result2` ends up as `number | undefined`.

If you don't want the distributive behavior, wrap the check types in brackets as documented at the link above.

**Comment by yseymour** [comment]
@fatcerberus , yeah, I just arrived at the same conclusion as you posted that... mea culpa! Not the first time I've tripped over distribution...
