### ISSUE TITLE
Intellisense not resolving modules when using `exports` in package.json

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#56412]
Reposting from VSCode repo for @magnusriga. I transferred the original issue to the wrong repo and now can't transfer it back

----

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.84.2
- OS Version: Windows 11 Pro

Steps to Reproduce:

1. Build any project (A) with a dependency on another project (B), where project B's package.json exports files using the `exports` field
2. Observer how Intellisense does not work
3. Insert the `main` and `types` fields and see that Intellisense starts working again

### **Intellisense Works When `main` and `types` are set:**
**Package B's `package.json`**

![image](https://github.com/microsoft/vscode/assets/38915578/c4a87fea-7ee8-4bdb-8f96-37396e5b4fdb)

**Package A's `import` (notice the Intellisense pop-up. It is possible to ctrl-click the path.)**

![image](https://github.com/microsoft/vscode/assets/38915578/46e25339-85f3-4666-8922-d640942778d6)

### **Intellisense Does Not Work When only `exports` is set:**

**Package B's `package.json` (removed `main` and `types`)**

![image](https://github.com/microsoft/vscode/assets/38915578/382f9478-6031-4214-a60c-08fa055d224b)

**Package A's `import` (not possible to crl+click to find the package, i.e. no Intellisense)**

![image](https://github.com/microsoft/vscode/assets/38915578/7b138a5c-217a-4adc-b2cf-52e7721d035c)

**Comment by RyanCavanaugh** [comment]
We need an actual repro. Also, please post code, not screenshots of code.

**Comment by magnusriga** [comment]
I finally got Intellisense to work and respect the `exports` field.

Here is a working repo: https://github.com/magnusriga/my-turborepo

Leaving my config below in case it is helpful to anyone else. The below is slightly different to the repo above, it uses a `src` folder in package B.

**Package B's package.json**

````json
{
  "name": "@acme/ui",
  "version": "3.0.1",
  "private": true,
  "sideEffects": [
    "**/*.css"
  ],
  "exports": {
    ".": {
      "types": "./types/index.d.ts",
      "import": "./dist/index.js"
    },
    "./*": {
      "types": "./types/*.js",
      "import": "./dist/*.js"
    }
  },
  "scripts": {
    "build": "rimraf dist && tsc -p",
    "clean": "rm -rf dist",
    "dev": "rimraf dist types .Cache && tsc --watch",
    "lint": "eslint src/",
    "test": "jest",
    "check-types": "tsc --noEmit"
  },
  "jest": {
    "preset": "jest-presets/jest/browser"
  },
  "devDependencies": {
    "@babel/preset-react": "latest",
    "@types/react": "latest",
    "@types/react-dom": "latest",
    "@types/styled-components": "latest",
    "autoprefixer": "latest",
    "eslint-config-custom": "workspace:*",
    "fs-extra": "latest",
    "rimraf": "latest",
    "postcss": "latest",
    "react": "latest",
    "tailwind-config": "workspace:*",
    "tailwindcss": "latest",
    "tsconfig": "workspace:*",
    "typescript": "latest",
    "watch": "latest"
  },
  "peerDependencies": {
    "react": "latest",
    "styled-components": "latest"
  }
}
````

**Package A's import**

```javascript
import { Button } from '@acme/ui/components/button';
```

**Package B's `tsconfig` (the three are chained via `extends`)**

```json
{
  "extends": "tsconfig/react-library.json",
  "compilerOptions": {
    "allowJs": true,
    "declaration": true,
    "noEmit": false,
    "noEmitOnError": true,
    "incremental": true,
    "outDir": "dist",
    "declarationDir": "types",
    "tsBuildInfoFile": ".Cache/tsc.buildinfo.json",
    "rootDir": "src",

    "sourceMap": true,
    "inlineSources": true,
    "sourceRoot": "src",

    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"],
      "@components/*": ["src/components/*"],
      "@utils/*": ["src/utils/*"],
      "@lib/*": ["src/lib/*"],
      "@styles/*": ["src/styles/*"],
      "@ui/*": ["src/ui/*"],
      "@context/*": ["src/context/*"],
      "@templates/*": ["src/templates/*"],
      "@public/*": ["public/*"]
    }
  },
  "include": ["./src"],
  "exclude": [
    "dist",
    "build",
    ".Cache",
    "types",
    "node_modules",
    "cypress",
    "test",
    "**/__tests__/*",
    "jest.setup.tsx"
  ]
}
```
```json
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "display": "React Library",
  "extends": "./base.json",
  "compilerOptions": {
    "jsx": "react-jsx",
  }
}
```

```json
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "display": "Default",
  "compilerOptions": {
    "esModuleInterop": true,
    "skipLibCheck": true,
    "target": "es2022",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "moduleDetection": "force",
    "strict": true,
    "noUncheckedIndexedAccess": true,
    "moduleResolution": "Bundler",
    "module": "ESNext",
    "noEmit": true,
    "lib": ["es2022", "dom", "dom.iterable"],

    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "preserveWatchOutput": true
  },
  "exclude": ["node_modules"]
}
```

**Comment by andrewbranch** [comment]
@magnusriga can you please provide instructions on how to reproduce the problem in the context of the repo you shared?

**Comment by magnusriga** [comment]
@andrewbranch I actually got it to work. I posted a working repo above to showcase the settings needed to make it work (in case it is useful to others in the future).

I will mark it as resolved.

**Comment by virtuallyunknown** [comment]
Hey folks, can this be reopened please? Here is a bare-minimum example:

https://github.com/virtuallyunknown/esm-exports-no-intellisense

To reproduce:

1. clone the repository
2. `npm install` (important step)

---

The problem can be observed in [packages/two/test.js](https://github.com/virtuallyunknown/esm-exports-no-intellisense/blob/master/packages/two/test.js#L5) where there is no Intellisense. Why? Because the package we're exporting from - `@repo/one` does not define a `main` field and only uses the modern `exports` variant.

Adding a `main` field fixes the problem.

```diff
{
    "name": "@repo/one",
    "version": "1.0.0",
    "author": "me",
    "type": "module",
+   "main": "./src/index.js",
    "exports": {
        ".": {
            "import": "./src/index.js"
        }
    }
}

```

**Comment by virtuallyunknown** [comment]
@andrewbranch thanks for taking your time to explain the issue to me, I really appreciate it.

I have tried the `jsconfig.json` and it seems to do the trick, so I suppose this is an acceptable workaround for the time being (or alternatively using main field), and if you and/or the vscode team are aware of the issue, then that's great.

In my personal opinion it's important that developers can make use of all ESM features so we can finally move away from CJS and all start using one unified system, but I also understand you guys probably have more pressing issues that require your attention.

Cheers!

**Comment by virtuallyunknown** [comment]
Hey @andrewbranch sorry to bother you again, but I have a follow-up question.

In my demo (mono)repository we export some files from `@repo/one` and we import them in `@repo/two`. Adding `jsconfig.json` in project root fixes the issue with the `imports` field, but another issue arises if `@repo/two` is a typescript project with a `tsconfig.json` of it's own.

You can see the basic project overview here, and I updated [my demo repository](https://github.com/virtuallyunknown/esm-exports-no-intellisense) as well with a reproducible example, where the same problem as before arises if `@repo/two` is a typescript project.

```
.
├── packages
│   ├── one 👉👉👉 export from here
│   │   ├── src
│   │   │   ├── bar.js
│   │   │   ├── foo.js
│   │   │   └── index.js
│   │   └── package.json
│   ├── tsconfig
│   │   ├── src
│   │   │   ├── tsconfig.node.json
│   │   └── package.json
│   └── two 👈👈👈 import here
│       ├── src
│       │   └── dummy.ts
│       ├── package.json
│       ├── test.js
│       └── tsconfig.json ❗❗❗ this is a typescript project now.
├── jsconfig.json
├── package.json
└── package-lock.json
```

So I guess my question is if there is a similar workaround for this particular problem? One might think to themselves that this is quite a weird setup to have, but my use case is that I put build scripts in the root of each sub-project (where test.js currently is), and my typescript files reside in the src directory.

If all of this is taking too much of your time then no worries, I will work with what I currently have, cheers.

**Comment by andrewbranch** [comment]
What’s happening here is the presence of the `tsconfig.json` next to `test.js` is throwing us off from finding the root `jsconfig.json` when looking for a config to use for editor support. When you open `test.js`, we start looking for jsconfig/tsconfig files up the directory spine from that file. We stop when we see the tsconfig.json, but it doesn’t actually include test.js. Instead of continuing the search, it seems like we give up and put test.js in an inferred project with default settings. I don’t know if this is a known limitation or a bug, but it seems like something that could be improved. (cc @sheetalkamat)

I think the most conventional workaround would be to put your scripts in their own directory with their own tsconfig.json/jsconfig.json. Alternatively, you could name your package-level tsconfigs something else (tsconfig.src.json) and reference them from a root-level solution tsconfig.json:

```json
{
  "files": [],
  "references": [
    { "path": "./packages/two/tsconfig.src.json" },
    { "path": "./tsconfig.scripts.json" }
  ]
}
```

The trick is to make it so that the nearest file named literally `tsconfig.json` (or `jsconfig.json`) up from any file actually includes that file somehow, either directly or by fanning out into a referenced project that includes it.

**Comment by magnusriga** [comment]
@andrewbranch Thanks for the awesome support here. I made a change to my repo and now have issues again. If you have time, could you check out my last comment in this PR: https://github.com/vercel/turbo/pull/6575

Long story short, Turbo's example is a monorepo with, among others, a next.js package and a `@repo/package/ui` (only supports TS). The maintainer claims that IntelliSense (auto-import) does not work if we use a catch-all (`"./*": "./src/*.tsx"`) in the `exports`, due to a TypeScript bug. Is that right?

Also, I got it to work if I used a conditional export, any idea why that is? I.e. what is the difference between these:

`"./*": "./src/*.tsx"`

`"./*": {import: "./src/*.tsx"`}

**Comment by andrewbranch** [comment]
> Also, I got it to work if I used a conditional export, any idea why that is? I.e. what is the difference between these

That sounds like a bug. Can you provide a specific repro?

> Lastly, is there a way for IntelliSense to support both TS and JS files? These did not work

It’s hard to tell exactly what the intent is here without a repro, but something that seems relevant is [file extension substitution](https://www.typescriptlang.org/docs/handbook/modules/reference.html#file-extension-substitution). Any time TS sees a request to resolve a file ending in `.js`, it actually tries to resolve `.ts`, `.tsx`, and `.d.ts` at a higher priority, because if one of those exists, it’s assumed to be the _source_ of the `.js` file (or typed artifact, in the case of `.d.ts`).

**Comment by andrewbranch** [comment]
> I have actually tried manually including the `test.js` file in the `include` field of the `tsconfig.json` file that sits in the same directory next to it, and naively I thought that might do the trick, but unfortunately it didn't.

Probably need to add `allowJs` or `checkJs` to that tsconfig to get `test.js` properly included.

**Comment by virtuallyunknown** [comment]
> Probably need to add `allowJs` or `checkJs` to that tsconfig to get `test.js` properly included.

I just tested and unfortunately it doesn't do anything in terms of intellisense.

`allowJs` makes these 3 dots (not sure what they are called) appear and if you hover it gives you a warning that the declaration files are missing.

![image psd](https://github.com/microsoft/TypeScript/assets/24871108/f6dfed89-b6cf-499a-83af-b2370e9ffc91)

And if `checkJs` is enabled, it gives you the red squiggly/wavy line indicating the error itself. But trying to trigger the intellisense/autocomplete with `ctrl+space` while between the `{ }` still doesn't trigger any suggestions, otherwise this would've been a nice workaround.

```
Could not find a declaration file for module 
 . /home/user/projects/esm-exports-no-intellisense/packages/one/src/index.js implicitly has an type.
```

**Comment by magnusriga** [comment]
> > Also, I got it to work if I used a conditional export, any idea why that is? I.e. what is the difference between these
> 
> That sounds like a bug. Can you provide a specific repro?
> 
> > Lastly, is there a way for IntelliSense to support both TS and JS files? These did not work
> 
> It’s hard to tell exactly what the intent is here without a repro, but something that seems relevant is [file extension substitution](https://www.typescriptlang.org/docs/handbook/modules/reference.html#file-extension-substitution). Any time TS sees a request to resolve a file ending in `.js`, it actually tries to resolve `.ts`, `.tsx`, and `.d.ts` at a higher priority, because if one of those exists, it’s assumed to be the _source_ of the `.js` file (or typed artifact, in the case of `.d.ts`).

Hi @andrewbranch . Please find the repo here:  https://github.com/magnusriga/turbo-tailwind.git

**First issue**

IntelliSense works for `apps/web/foo-typescript.js`, but not for `apps/web/foo-javascript.js`. Why is that?

**Second issue**

I actually got both these to work now:

Works:

```json
"./*": {
     "import": "./src/*.tsx"
}
```

Also works:

```json
  "./*": "./src/*.tsx"
```

However, this does _not_ work to export both my js and ts:

```json
"./*": "./src/*"
```

Any idea how to achieve the latter (exporting both the TS and JS).

**Comment by magnusriga** [comment]
> > Probably need to add `allowJs` or `checkJs` to that tsconfig to get `test.js` properly included.
> 
> I just tested and unfortunately it doesn't do anything in terms of intellisense.
> 
> `allowJs` makes these 3 dots (not sure what they are called) appear and if you hover it gives you a warning that the declaration files are missing.
> 
> ![image psd](https://private-user-images.githubusercontent.com/24871108/289993833-f6dfed89-b6cf-499a-83af-b2370e9ffc91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1ODU1OTMsIm5iZiI6MTcwMjU4NTI5MywicGF0aCI6Ii8yNDg3MTEwOC8yODk5OTM4MzMtZjZkZmVkODktYjZjZi00OTlhLTgzYWYtYjIzNzBlOWZmYzkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDIwMjEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMTgwMTgxZDI4MDUwNmI2M2JlZTQ0YWQ1YWU1YmNjMDZhYjEwZGJmZDIyNGI2ZTQzMDE3ODZiZjIwYWU0MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bID20qwzIE1cxB1Da-SblUb9C4h7KQQMVVkMALBJgV0)
> 
> And if `checkJs` is enabled, it gives you the red squiggly/wavy line indicating the error itself. But trying to trigger the intellisense/autocomplete with `ctrl+space` while between the `{ }` still doesn't trigger any suggestions, otherwise this would've been a nice workaround.
> 
> ```
> Could not find a declaration file for module 
>  . /home/user/projects/esm-exports-no-intellisense/packages/one/src/index.js implicitly has an type.
> ```

For whatever it is worth @virtuallyunknown : I also had the issue with the "missing declaration files" ESlint error when importing a JS file, and got it to go away by adding this to m;y tsconfig: `"noImplicitAny": false`.

**Comment by andrewbranch** [comment]
Can you be more specific about how to repro and what your expected and actual behavior is? This is a big repo with many files, and both “IntelliSense” and “works” are loaded terms 😁

**Comment by virtuallyunknown** [comment]
> For whatever it is worth @virtuallyunknown : I also had the issue with the "missing declaration files" ESlint error when importing a JS file, and got it to go away by adding this to my tsconfig: `"noImplicitAny": false`.

Hey man, don't get me wrong, I appreciate your help, but I wouldn't actually suggest disabling `noImplicitAny` just to make tooling or other non-critical editing features work. You'd be basically sacrificing type-safety this way, and `noImplicitAny` is part of the `strict` ruleset`.

Of course this is just my opinion and maybe you have a better use case than I do, but for me this would weaken the type system which I'm not a fan of.

**Comment by magnusriga** [comment]
@virtuallyunknown What you say makes complete sense, but I couldn't find any other way to remove that ESLint error you mentioned, which I got when importing a JS file into a TS file. Obviously the JS file does not have type declarations in the first place, so ideally it should not check that file when it sees that it is JS and not TS.

**Comment by magnusriga** [comment]
> Can you be more specific about how to repro and what your expected and actual behavior is? This is a big repo with many files, and both “IntelliSense” and “works” are loaded terms 😁

Yes, sorry. Just open the repo I linked in you vscode, then follow these steps:

1. `pnpm i`
2. Go to `apps/web/foo-typescript.js` and see that you get suggestions on the RHS of this statement: `import { Bar } from '@repo/ui/'`.
3. Go to `apps/web/foo-javascript.js` and see that you do _not_ get suggestions on the RHS of this statement: `import { Card } from '@repo/ui/'`.

**Comment by andrewbranch** [comment]
@magnusriga the `.js` file is explicitly excluded from your project. This change makes it work.

<img width="845" alt="image" src="https://github.com/microsoft/TypeScript/assets/3277153/e0bbae76-ba2a-476b-972a-6a0e6b7e731e">

**Comment by magnusriga** [comment]
> @magnusriga the `.js` file is explicitly excluded from your project. This change makes it work.
> 
> <img width="845" alt="image" src="https://github.com/microsoft/TypeScript/assets/3277153/e0bbae76-ba2a-476b-972a-6a0e6b7e731e">
> 

Legend @andrewbranch , thank you so much.

Re. my second question above, is it possible to export both JS and TS files with a wild card export, and still be able to see the IntelliSense suggestions when importing? `"./*": "./src/*.tsx` works to export all tsx files while maintaining IntelliSense on import, and so does `"./*": "./src/*.js` for all the js files. However, I want to export both js and ts files and be able to see them all as suggestions by IntelliSense when importing.

**Comment by andrewbranch** [comment]
I can’t repro that issue. With these `exports`:

```
  "exports": {
    "./styles.css": "./dist/index.css",
    "./*": "./src/*"
  }
```

I see:

<img width="523" alt="image" src="https://github.com/microsoft/TypeScript/assets/3277153/fbf60299-8c9b-4991-b102-b1a71c8cb399">

**Comment by magnusriga** [comment]
@andrewbranch Apologies for the late reply, I have been away over the holidays. Hope you had a good break.

Regarding your last post, I see the same as you in the TSX file, but not in the JS file:

![image](https://github.com/microsoft/TypeScript/assets/38915578/7e3a6bf8-0de4-4d84-ac30-7a6b9115de31)

**Comment by magnusriga** [comment]
@andrewbranch I got it to work, following your suggestions. Thank you so much.

A quick question, if you have time: How come the `tsconfig` in the `web` folder (where you added `src` to the `include` property) controls what is seen by Intellisense in other packages outside `web`? Specifically, by adding `src` we suddenly started seeing js files from external package `@repo/ui`. I would have thought it was the `tsconfig` inside `@repo/ui` that controlled what is seen in that package, by those packages that import it.

**Comment by andrewbranch** [comment]
`@repo/ui/bar` and `@repo/ui/card` are not valid module specifiers via that wildcard `exports`. The result of a wildcard `*` substitution is a file lookup, so file extension adding and `index` directory lookups don't occur. So, the correct module specifiers would be `@repo/ui/card.tsx` and `@repo/ui/bar.js`.

```
❯ node
Welcome to Node.js v21.3.0.
Type ".help" for more information.
> require.resolve('@repo/ui/bar')
Uncaught:
Error: Cannot find module '/Users/andrew/Developer/microsoft/eg/turbo-tailwind/apps/web/node_modules/@repo/ui/src/bar'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1181:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1169:15)
    at resolveExports (node:internal/modules/cjs/loader:591:14)
    at Module._findPath (node:internal/modules/cjs/loader:668:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1130:27)
    at Function.resolve (node:internal/modules/helpers:187:19) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/andrew/Developer/microsoft/eg/turbo-tailwind/apps/web/node_modules/@repo/ui/package.json'
}
> require.resolve('@repo/ui/bar.js')
'/Users/andrew/Developer/microsoft/eg/turbo-tailwind/packages/ui/src/bar.js'
```

The TS bug is that the path completions suggested `card` and `bar` without file extensions. I'll open a new issue for that.

> How come the tsconfig in the web folder (where you added src to the include property) controls what is seen by Intellisense in other packages outside web? Specifically, by adding src we suddenly started seeing js files from external package @repo/ui. I would have thought it was the tsconfig inside @repo/ui that controlled what is seen in that package.

TypeScript doesn't know anything about the boundaries of these "packages," because you haven't set up project references. Each package here has its own independent TS project that contains all files you reference, compiled under the single tsconfig for that package. The tsconfigs in other packages are completely independent and never even discovered by the TS project you're editing.

> Specifically, by adding src we suddenly started seeing js files from external package @repo/ui

Probably what you were seeing here is that imports in the `apps/web/src/foo-javascript.js` were wrong/incomplete because that file was being processed under default VS Code settings, and once it was included by the intended tsconfig, its `moduleResolution` setting changed and made additional import paths available. Changing the `include` of `apps/web` did not change what files in `packages/ui` are reachable inside the `apps/web` project; it just changed what project some of the files in `apps/web` belong to, which changed how their imports are processed.

**Comment by magnusriga** [comment]
> `@repo/ui/bar` and `@repo/ui/card` are not valid module specifiers via that wildcard `exports`. The result of a wildcard `*` substitution is a file lookup, so file extension adding and `index` directory lookups don't occur. So, the correct module specifiers would be `@repo/ui/card.tsx` and `@repo/ui/bar.js`.

Got it @andrewbranch . So, there is no way to change the `exports` field so that the import can be done without explicitly stating the imported module's file extension, if we want to maintain the `exports` field's catch-all form (i.e. avoiding to explicitly list each exported file)?

In other words, I only have two options: Either state the file extension in the `import`, or change the `exports` to include the file extension there:

**OPTION 1**

```javascript
// Package one
import { Card } from '@repo/ui/card.tsx';
```

```json
// Package two
"exports": { "./*": "./src/*" }
```

**OPTION 2**

```javascript
// Package one
import { Card } from '@repo/ui/card';
```

```json
// Package two
"exports": { "./card": "./src/card.tsx" }
```

Is it correct that I am limited to these two?

Thanks!

**Comment by andrewbranch** [comment]
That's correct, at least according to the `exports` spec written by Node.js, which is what TS tries to follow. Some bundlers may be more flexible than this but there is some ongoing discussion about making those bundler resolvers conform to the spec in future major version bumps. Neither option is better practice than the other. It's up to you.

**Comment by magnusriga** [comment]
@andrewbranch One other thing I noticed which may also be a bug:

![image](https://github.com/microsoft/TypeScript/assets/38915578/0bd9730b-14a8-40ba-9c8c-63bd94be09da)

In words, the left-hand-side Intellisense does not work when importing a js file. I.e. the exported function Bar does not show up as a suggestion.

**Comment by andrewbranch** [comment]
> One other thing I noticed which may also be a bug

This is working as intended. JavaScript files imported from `node_modules` are not analyzed for type information by default.

> Subpaths in exports also seem to break IntelliSense (auto-complete of RHS import paths does not work)

This appears to be a bug.

**Comment by andrewbranch** [comment]
Yes, I'll try that out and see if there are any objections.

**Comment by magnusriga** [comment]
> Yes, I'll try that out and see if there are any objections.

Not sure if I misunderstood you @andrewbranch .

Did you know of a way to make the left hand side of the import statements work with IntelliSense, when importing a JS file from node_modules (which in reality is from our own monorepo)? If so, how do I do it?


Thanks!

**Comment by andrewbranch** [comment]
> If so, how do I do it?

Update to TypeScript 5.4 when it comes out. #56946

**Comment by magnusriga** [comment]
@andrewbranch Quick and somewhat related question, that might or might not be a bug:

In node it is possible to self-reference a package. So, using the repo in this thread, TS and JS modules in `/package/ui`, which is named `@repo/ui` should be able to import from itself via `@repo/ui`: `import { Foo } from '@repo/ui/components/foo'`.

The problem I am facing is that I am not getting any autocomplete for my own package when typing the right-hand-side of the import above. Specifically, ctrl+space at `import { Foo } from '@repo/` will only list the @repo-packages I have in my package.json `devDependency` field.

Since node supports self-referencing, it would be great if Intellisense did too.

------

**PS:** Quick side-question that is also related. The @-rules in tsconfig's `compilerOptions.paths`, how are they resolved? I import package/ui components into the main app, without any bundling, so if those components use @-rules, will those use the tsconfig in `package/ui` or in the app the component is imported into?

**Comment by xavierex-president** [comment]
Give this a glance https://disparity3.github.io/swift/
