### ISSUE TITLE
`allowSyntheticDefaultImports` doesn't work when importing a typescript module

### ISSUE THREAD

**Issue by Malix-off** [microsoft/TypeScript#56435]
### 🔎 Search Terms

"allowSyntheticDefaultImports", "import", "typescript", "module"

### 🕗 Version & Regression Information

- This changed between versions 5.0.X and 5.2.2

### 💻 Code

main.ts
```ts
import * as a from './test';
import b from './test';
```

test.ts
```ts
export var test = 1;
```

tsconfig.json
```json
{
	"compilerOptions": {
		"noEmit": true,
		"allowSyntheticDefaultImports": true,
		"allowImportingTsExtensions": true
	}
}
```

### 🙁 Actual behavior

![image](https://github.com/microsoft/TypeScript/assets/76160668/cc3744d7-308f-4c0f-bf0e-bd35ae400eb1)

### 🙂 Expected behavior

No error

**Comment by andrewbranch** [comment]
test.ts uses ESM syntax and therefore will include the `__esModule` flag in its CommonJS emit. `allowSyntheticDefaultImports` is designed to allow using a default import to access the `module.exports` of a “true” CommonJS file, not one that’s been transpiled from ESM. N.B. this is relaxed when importing from declaration files, because we don’t know for sure whether the JavaScript file will have that `__esModule` marker. When it’s a TS file, we control the emit, so we know it will.

Technical emit-based explanation aside, if you have two files that are written with ESM syntax, the expected behavior is that they reference each other using valid ESM semantics.
