### ISSUE TITLE
Type cast is failing to check when there is more than 1 object in array

### ISSUE THREAD

**Issue by spyhere** [microsoft/TypeScript#56446]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

I couldn't find anything like that on the internet, so I'm not even sure if it's a bug, a feature request or something else, please advise.

**Examples:**
```typescript
type Item = { id: 'Row' | 'Column' }
type Menu = {
    menu: readonly Item[]
}

const worksVar: Menu = {
    menu: [{ id: '' }, { id: 'Row' }] // Type '""' is not assignable to type '"Row" | "Column"'
}

const kindaWorksVar = {
    menu: [{ id: '' }] // Type '""' is not assignable to type '"Row" | "Column"'
} as Menu

const notWorksVar = {
    menu: [{ id: '' }, { id: 'Row' }] // Doesn't care
} as Menu
```

[Link to Typescript playground](https://www.typescriptlang.org/play?jsx=0&ssl=16&ssc=10&pln=1&pc=1#code/C4TwDgpgBAksEFsoF4oG8oEsAmAuKA5AEoD2A7gVAD6EDCJANgK4IB2lAvgFCiRQCyEVkxTouUCVARCm+AE4QAhthKsGIWPAQBtALpduXAMaqAzsChkScgNamAaorn5Bw0WnGTpw-Now58Ak4AGnQsPEJSCigOXSgAenioABVwaAIAIgzKTFMoVhILRVNTTABzVkUAIwZoYBIoXnSMqIzqKAz6ZjZsgy5jMwsbTFZsRQB1aztHOXdPCW9ZKD9wwM44xJS0wiycvIKikvLKmrqGpp3W9s7GFlZejihigRl+k1ZzfMLJ2wcnOckUhkvn8ESCMVCoMCUXWCSSABESBBTOwLEYnBADE88q4mFwgA)

**Why do I need type cast?**

I'm having a big configuration object that has a lot of objects and props inside. Since it's tedious to list every possible key in type I'm using `<const>`, so Typescript is expecting and suggesting exactly those keys, but I also want to ensure that the configuration meets the described shape — so it's assured that the configuration wasn't accidentally broken and bug will be detected before going into production.

**Example of my configuration object:**

```typescript
type Configuration = {...}

export default <const>{
  key1: {...} as Configuration,
  key2: {...} as Configuration,
  key3: {
    key1: {...} as Configuration
  },
  ...
};

```

**Is it possible to have everything as constant and control the shape with types?**

```[tasklist]
### Tasks
```

**Comment by fatcerberus** [comment]
You probably want to use `satisfies` here instead of `as`: [TS Playground](https://www.typescriptlang.org/play?jsx=0#code/C4TwDgpgBAksEFsoF4oG8oEsAmAuKA5AEoD2A7gVAD6EDCJANgK4IB2lAvgFCiRQCyEVkxTouUCVARCm+AE4QAhthKsGIWPAQBtALpduXAMaqAzsChkScgNamAaorn5Bw0WnGTpw-Now58Ak4AGnQsPEJSCigOXSgAenioABVwaAIAIgzKTFMoVhILRVNTTABzVkUAIwZoYBIoXnSMqIzqKAz6ZjZsgy5jMwsbTFZsRQB1aztHOXdPCW9ZKD9wwM44xJS0wiycvIKikvLKmrqGpp3W9s7GFlZejihTRWBcgDNMCDzXJn6TVnM+UKk1sDicc0kUhkvn8ESCMVCsMCUXWCSSABESF92BYjE4IAYni93p9vjIuEA)

* `as` is a type assertion, it's basically "Trust me, it's actually this type here, even if you don't think so".  While TS tries to reject "obviously wrong" casts, it's still unsafe by design (e.g. stuff like `animal as Dog` is allowed since the types are related).
* `satisfies` properly checks for assignability, which seems to be what you intended to do here.

**Comment by fatcerberus** [comment]
For the record this has nothing to do with how many items the array has; the one that's *not* an error is simply because it has an entry in common with the type.  If all the values are non-matching, you get an error again:

```ts
const alsoWorksVar = {
    menu: [{ id: '' }, { id: 'foo' }] // error again
} as Menu
```

Basically, `X as Y` succeeds if `X` is related to `Y`.  I don't know the exact criteria for what's considered "related" though, but it's a much weaker check than assignability.

**Comment by spyhere** [comment]
@fatcerberus Thank you very much, I've completely forgotten about `satisfies`!
