### ISSUE TITLE
Donating Funds to TypeScript

### ISSUE THREAD

**Issue by Lfada** [microsoft/TypeScript#56471]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

Hi TypeScript maintainers. I'm Lucas, a core contributor to the Radworks project. https://radworks.org/

We've been using https://github.com/microsoft/TypeScript as part of [[Drips](http://drips.network/)]. It's in fact one of our most critical dependencies!

We really appreciate the work you all do and even though we know you might not need the funds, we still wanted to share our gratitude, as we are doing with 30+ of our other critical dependencies. We are doing it through [Drips](https://www.drips.network/). This would allow you to also split those incoming donations to your critical dependencies if you don't need 100% of the funds. 

Who can I talk to about it?

**Comment by arswaw** [comment]
Well I think you answered your own question. TypeScript is maintained by Microsoft employees. Microsoft funds TypeScript development as part of a larger initiative to support open-source software. The fact that Radworks is eager to repay the maintainers of the open-source projects it depends on is welcome. I recommend running `npm fund` in your project to find out which of your dependencies are looking for funding, and go from there.

**Comment by Lfada** [comment]
> Well I think you answered your own question. TypeScript is maintained by Microsoft employees. Microsoft funds TypeScript development as part of a larger initiative to support open-source software. The fact that Radworks is eager to repay the maintainers of the open-source projects it depends on is welcome. I recommend running `npm fund` in your project to find out which of your dependencies are looking for funding, and go from there.

Thanks for responding. We already chose which dependencies to fund :) [Drips Dependency List ](https://www.drips.network/app/drip-lists/48495160997488293670723292622742268320163565037397170198477469637178) 

The funds sent to TypeScript cannot be claimed back by us. This is why we would love to chat with someone who can decide what to do with them, and ask any questions they have in order to make a decision. Are you that person @arswaw, or someone else?

**Comment by MartinJohns** [comment]
This looks more like advertisement for "Drips" than anything, especially since the same issue has been opened in over 10 repositories.

**Comment by fatcerberus** [comment]
> The funds sent to TypeScript cannot be claimed back by us.

This seems unwise.  What will you do if the maintainers reject the donation, which is what I suspect is going to happen?

**Comment by RyanCavanaugh** [comment]
Appreciate the thought, but we have no capacity to receive donations and aren't seeking any. I'd suggest the funds be redirected to non-corporate-sponsored projects. Thanks!

**Comment by lftherios** [comment]
I understand that the issue is now closed but I still wanted to clarify the intentions behind this initiative as I believe there may be some misconceptions.

The goal of Drips is to motivate financially stable companies to continuously support vital software they depend on, moving away from one-off donations. We've developed a system and user-friendly interface to simplify the process of companies continuously funding these dependencies and for developers to channel the funding where it's needed the most. We believe this approach benefits both contributors and the projects they support. We’ve written a longer post about it [here](https://mirror.xyz/dripsdev.eth/xxQQxgE6YOh1YmJ6onJquJmAgIy71vmVXLlatRQH5qo).

> This looks more like advertisement for "Drips" than anything, especially since the same issue has been opened in over 10 repositories. Every time it's the same template, and "one of our most critical dependencies".

We opened GH Issues with more than 10 repositories because we've committed $1M in funding to [30+ dependencies](https://www.drips.network/app/drip-lists/50330452048867519181028275890986093327647919805766323166158196453514). The intent behind opening issues is to inform maintainers that they have been allocated a portion of these funds and to offer them support to claim or further pass them along to other devs that need the capital. It's entirely up to the maintainer/s to claim, split or reject those funds. There’s a lot of maintainers to inform, templates make it easier to do that.

@fatcerberus, thanks for sharing your opinion. I personally don’t think it's as binary as you are putting it. We assume that even if a project rejects the donation, they would consider passing the funds along to their dependencies or other projects. **Unlike Typescript, many open source projects are underfunded, and could potentially benefit from the funds allocated.**

If you're interested I would be happy to share more information and answer your questions about why we believe Drips is a good tool for FOSS developers. If not, thank you again for your time and for all the FOSS work you do!
