### ISSUE TITLE
Latter type parameters are not suggested in constraints of the preceding ones

### ISSUE THREAD

**Issue by Andarist** [microsoft/TypeScript#56474]
### 🔎 Search Terms

type parameters constraints completions

### 🕗 Version & Regression Information

- This changed in https://github.com/microsoft/TypeScript/pull/52690

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.4.0-dev.20231120#code/GYVwdgxgLglg9mABFApgZygHgGIwE4aIoAeqYAJmogMoD0AVPbQDQ0oQLkB8AFAIYAuRLgJRWAIyHV2nAJSIA3gF8AUCqA

### 💻 Code

```ts
function test<First extends S/**/, Second>(a: First, b: Second) {}
```

### 🙁 Actual behavior

`Second` is not suggested at this marker

### 🙂 Expected behavior

I'd expect `Second` to be suggested since depending on the latter type parameters is valid (even if weird at times). 

### Additional information about the issue

This change was called out in comments of the PR that introduced this (initially it focused only on expression-space parameters) but I wonder if this is something that could be revisited. cc @zardoy

**Comment by zardoy** [comment]
I didn't remember the exact [motivation](https://github.com/microsoft/TypeScript/pull/52690#issuecomment-1434979172) for filtering them out, probably I just found these completions annoying myself as I couldn't imagine a case where you would write `First extends Second, Second` instead of `First, Second extends First`, though there are pretty complex function signatures that still do this (just Vue.extend for example). Since these completions don't cause any type-errors, I think it would be more correct to revert the change for type parameters as you suggest.

Ideally checker and completion modules should use more methods in common so it's easier to filter out completions that can cause type errors to avoid such misalignments as this one.
