### ISSUE TITLE
pnpm peer dependency handling conflicts with source file redirection / deduplication

### ISSUE THREAD

**Issue by bestlyg** [microsoft/TypeScript#56762]
### 🔎 Search Terms

 error TS2741

### 🕗 Version & Regression Information

version: latest.

### ⏯ Playground Link

https://github.com/bestlyg/component-type-checker

### 🙁 Actual behavior

error TS2741.

### 🙂 Expected behavior

Normal compilation.

**Comment by bestlyg** [comment]
steps:
run script `pnpm install` in root directory.
run script `pnpm start` in `component-type-checker/packages/app/package.json`

<img width="1484" alt="image" src="https://github.com/microsoft/TypeScript/assets/51100990/dac29d0b-7ee0-4798-90f8-02d3abe46b4f">

**Comment by bestlyg** [comment]
I had tried debug the bug :
- findSourceFile `app.tsx`
    - findSourceFile `@component-type-checker/sdk`
        - findSourceFile `@component-type-checker+components@0.0.1_@component-type-checker+button@0.0.1`
            - findSourceFile `@component-type-checker/button@0.0.1`
    - findSourceFile `@component-type-checker+components@0.0.1_@component-type-checker+button@0.0.2` 
        - reuse sourceFile `@component-type-checker+components@0.0.1_@component-type-checker+button@0.0.1`.
 
Because `@component-type-checker+components@0.0.1_@component-type-checker+button@0.0.1` and `@component-type-checker+components@0.0.1_@component-type-checker+button@0.0.2` has the same packageId, when findSourceFile`@component-type-checker+components@0.0.1_@component-type-checker+button@0.0.2` , ts will reuse the sourceFile of `@component-type-checker+components@0.0.1_@component-type-checker+button@0.0.1`.
filepath: `TypeScript/src/compiler/program.ts`
<img width="1130" alt="image" src="https://github.com/microsoft/TypeScript/assets/51100990/01e12c70-c305-47a6-9fb3-ff6444e98156">

**Comment by bestlyg** [comment]
In most cases it is accurate, but in an environment where pnpm is used to build node_modules, if a package has a peer dependency, it will generate multiple packages of the same version.

They will link different versions of peer dependencies.So I want to add a option disableRedirectedSourceFile for disable redirected source file. I havd tried it and it works for me.
Could you check this PR for me?. I had sended a PR [#56722](https://github.com/microsoft/TypeScript/pull/56722).

**Comment by jakebailey** [comment]
I think there's actually a bug here, or at least an unfortunate problem.

pnpm has an interesting strategy to handle conflicting deps when peer deps are involved; it makes multiple directories that contain multiple versions of "the world" such that resolution in each location is slightly different in order to give each package the correct view.

We appear to attempt to deduplicate different copies of the same package using a "package ID", which really just consists of the package name and version. But that's not enough when the same `node_modules` has multiple of the same package but with different resolution.

It's not totally clear to me how this sort of deduplication is ever safe; this layout is problematic, but I can imagine the same module getting duplicated into multiple trees within a project for other reasons. For example, I may have a transitive dep on the same package but with multiple versions, such that there are multiple copies of each depending on who imports it internally. But, those are entirely different `node_modules` dirs.

@sheetalkamat @andrewbranch @weswigham Do you have any thoughts on this?

**Comment by jakebailey** [comment]
I'll also note that I recently remembered another thread about this; not sure if it's #42873 or something else but I think that this has been a known problem for a long time, and that the package ID thing is "intentional" in that it hides errors about nominality or similar. But, it sure feels like it's unsafe and that depending on the same dep via two places isn't going to work well (and the errors would be right).

**Comment by weswigham** [comment]
> and that the package ID thing is "intentional" in that it hides errors about nominality or similar

It's definitely the case that nominally typed things were the primary motivator for the "package id"-based deduplication. Honestly, it'd be... cleaner? if we just read them all in as separate files (RIP build times), but adjusted our "nominal" comparisons to do the "package id" comparison in there (...but then you also need some way of knowing if two types are corresponding across two packages to know to do that comparison that late, which means you need, like, canonical package-local namepaths to reference types by, which we don't *really* have today, but you can conceive of conventions for.)

This is spitballing, but there's any number of levels of coalescing we could perform to try and get two copies of a package to seem like the same thing and reduce our workload, but our current one is basically the most maximal one where we don't even do resolutions from non-primary locations that look to be the same package. A bit too maximal, as it turns out, since it wholesale deletes path information for non-primary copies. Thinking about how type serialization works, if we wanted to still only typecheck one copy (mostly), but allow referencing it by all those other paths when we do emit/go to def/services features, we'd need like one source file for each path, but each source file all containing references to the same set of parsed statements. Like a `NodeArray` with multiple parents. Or at least backup parents. Or a side lookup table with similar information available in a two way mapping.

But I think in all cases, the solution in some way involves rolling back the full deduplication we do today to a more partial deduplication so we can hold on to more information. To what degree we merge the packages is something we could probably debate, based on what level of checking you expect out of similar (identical?) packages in differing locations.
