### ISSUE TITLE
Property does not exist on generic type based on `Record<string, any>`

### ISSUE THREAD

**Issue by RoelVB** [microsoft/TypeScript#56793]
### 🔎 Search Terms

generic type record interface property missing

### 🕗 Version & Regression Information

Tried 4.0.5, 5.3.2 and v5.4.0-dev.20231215

### ⏯ Playground Link

https://www.typescriptlang.org/play?jsx=0&ts=5.3.2#code/FAYwNghgzlAEAqBTKAXAPPWiAeLEDsATOAJURAHsAnQtVKgS3wHMAaWCfATwD4fgA3sFgjYAW0QoAFhUIAKCFWYAuBAEphooaJ0clAOigUJ0ps1gBeWAHJrAbk27YAemexAMuSwAClQoAHRCoULhsjEykza1hCCmRYfAoULGwGVFgKfFhggJt4a305ACYAZmKATg0dAF9gR3FJGUJChSVVMkoaOhRGFnZOXkqtOp1FZkNjBrNLG3th0VdYQFByWABRADdArhQp1NgAMyZEOpqaoA

### 💻 Code

```ts
class Test<T extends Record<string, any>>
{
    method(arg: T)
    {
        arg.something = '';
        // ❌ Property 'something' does not exist on type 'T'.(2339)
    }

    method2(arg: Record<string, any>)
    {
        arg.something = '';
        // ✅ Everyting is fine
    }
}
```

### 🙁 Actual behavior

Throws the error that a random string property does not exist on `Record<string, any>`

### 🙂 Expected behavior

It should accept any string property

**Comment by MartinJohns** [comment]
Your type `T` is not a record, it just has to extend it. The type may be more specific, including a type that has a `something` property typed `boolean`.


```typescript
new Test<{ something: true }>
```

**Comment by RoelVB** [comment]
Thank you for the prompt response @MartinJohns 
I still don't really understand why this wouldn't work as expected.

Let me explain a little more about our actual use case.
We have an interface with some required/known properties, but it can also contain any other properties, like this:
```typescript
interface IData extends Record<string, any>
{
    required: string;
}
```
or:
```typescript
interface IData
{
    required: string;
    [key: string]: any;
}
```

If we create a class with a generic type extending `IData` we can only use the property `required`:
```typescript
class Test<T extends IData>
{
    method(arg: T)
    {
        arg.required = 'Test';
        arg.something = 'Test'; // ❌ Property 'something' does not exist on type 'T'
    }

    method2(arg: IData)
    {
        arg.required = 'Test';
        arg.something = 'Test'; // ✔ Everything is fine
    }
}
```

**Comment by MartinJohns** [comment]
Data structures like that are inherently unsafe. You wrongly assume `required` is always typed `string`, when it in fact can be any type due to assignability vis the indexer.

But I've demonstrated why it's not supported the way you want to. The type can be more specific than what you're extending. If you want to be able to access and modify any property, then just use the type `Record<string, any>`.

**Comment by fatcerberus** [comment]
It behaves this way for the same reason you can’t assign an arbitrary number - let’s say 4 - to a variable typed `T extends number`: because `T` might be instantiated as `1 | 2 | 3`.

`T extends Record<string, any>` doesn’t mean `T` can only be a record-like type (this is a common mistake), it can in fact be any type that’s assignable to the aforementioned `Record` type.  Which includes things like `{ something: number }` to which the assignment of a string is unsound.

**Comment by RyanCavanaugh** [comment]
I don't see any advantage of writing `Record<string, any>` over just `any` except to try to silence overzealous linters. Regardless, this is the intended behavior.
