### ISSUE TITLE
ts(80008) 9007199254740992 can be represented but still flags a warning

### ISSUE THREAD

**Issue by BlobTheKat** [microsoft/TypeScript#56904]
### 🔎 Search Terms

- `ts(80008)`
- `9007199254740992`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### 💻 Code

The number `9007199254740992`, while not being considered "safe" by `Number.isSafeInteger`, is still representable accurately as a javascript number

The reason `9007199254740992` is not considered a safe integer is that it can be the result of a rounding of `9007199254740993`. However, when the literal `9007199254740992` appears in code, this obviously cannot be the case

```ts
// Your code here
const doesntFlag = 9007199254740991
const shouldNotFlagButDoes = 9007199254740992
```

### 🙁 Actual behavior

A warning for `shouldNotFlagButDoes` that
> Numeric literals with absolute values equal to 2^53 or greater are too large to be represented accurately as integers

### 🙂 Expected behavior

# A
No warning, since `9007199254740992` can accurately be represented as an integer (albeit not a JS safe integer).
The warning for larger numbers should also be adjusted to not include "equal to"

# B
A more accurate warning that
> Numeric literals with absolute values equal to 2^53 or greater are too large to be represented as **safe javascript integers**

**Comment by RyanCavanaugh** [comment]
It seems like you went nitpicking and found a nit, rather than a real problem? I think the warning as given is fine and is useful to inform the programmer that they are in the range where `n + 1` will not work as expected. You can write `9.007199254740992e15` if you really need an error-free representation of that number

**Comment by BlobTheKat** [comment]
> It seems like you went nitpicking and found a nit, rather than a real problem?
Probably
> I think the warning as given is fine and is useful to inform the programmer that they are in the range where `n + 1` will not work as expected.
This has no relevance to the warning. The warning is about representing the number, not working with it
> You can write `9.007199254740992e15` if you really need an error-free representation of that number
I mean sure but this isn't exactly the best solution, making my codebase more confusing just to avoid a ts warning

**Comment by BlobTheKat** [comment]
> Do you actually have a codebase where you need to write that number?

yes
> You can also write it as `Number.MAX_SAFE_INTEGER + 1`, which feels a lot clearer.

In my codebase's context writing `2**53` would make more sense than `Number.MAX_SAFE_INTEGER + 1`, though I still feel the warning shouldn't be there for the literal

**Comment by BlobTheKat** [comment]
Given the relatively minor consequence of this issue, and the relatively effortless workaround (writing `2**53`, which actually makes more sense), and also the label `Working as Intended`, I have decided to close the issue

**Comment by lgarron** [comment]
I also ran into this in a codebase which specifically needs this number in the source *because* it's the supremum of fully representable integers.

https://github.com/lgarron/random-uint-below.js/blob/f501f070b50ed3e7da40512f86d1d9676f2fab5a/src/random-uint-below/randomUIntBelow.ts#L6

I guess `2 ** 53` is also okay in our case, as JS engines seem to compute that super quickly and we can amortize it using a single initialization.

But what throws me off is that VS Code shows a `…` warning that… can't be turned off? I tried adding a `@ts-ignore` and it seems to do absolutely nothing. Is this some special kind of warning that can't be ignored?
![clipboard](https://github.com/microsoft/TypeScript/assets/248078/ae91ee58-604e-476d-8013-9b3bf0b39ceb)
