### ISSUE TITLE
Type-unsafe usage of Record<string, () => void>

### ISSUE THREAD

**Issue by paskozdilar** [microsoft/TypeScript#57105]
### 🔎 Search Terms

TypeScript Record Function TypeError

### 🕗 Version & Regression Information

5.3.3

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/G4QwTgBAZgrgdgYwLYgA4C4ICUCmCD2YAJgDwDOALmAJZwDmANBABQCUEAvAHwTD7VEeHCAG8AvgG4AsAChQkWIk7R4yNAG0A5EXw4yEOPgoQcAD2qVNAXWkzFCNhIgB6ZxAAqAT1Q4AomDBCAEJZIA

### 💻 Code

```ts
var funcmap: Record<string, () => void> = {};
var func = funcmap['does not exist'];
func(); // TypeError!
```

### 🙁 Actual behavior

TypeScript compiles successfully (even with `--strict` option).
TypeScript infers the type of `func` variable to be `() => void`, even though it can be `undefined` when the key doesn't exist.

### 🙂 Expected behavior

TypeScript doesn't compile successfully, because the code didn't check whether `func` is `undefined` or not.

**Comment by jcalz** [comment]
Duplicates #13778 (see that and various linked issues there).

You're apparently looking for [`--noUncheckedIndexedAccess`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-1.html#checked-indexed-accesses---nouncheckedindexedaccess) and for many people this turns out to be more annoying than helpful.  Often the recommendation is to use `(()=>void) | undefined` instead of enabling this.

**Comment by paskozdilar** [comment]
Oh, I missed that one.
Thanks, I think that flag will do.
Cheers :)
