### ISSUE TITLE
Introduce the ?? type declaration as shorthand for null or undefined

### ISSUE THREAD

**Issue by deltaboukensha** [microsoft/TypeScript#57137]
### 🔍 Search Terms

syntax, alias, shorthand, type declaration, null or undefined

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Me and other developer would like there to be a shorthand syntax-hand syntax for null | undefined. The reason is that both null and undefined is returned from the external api's we consume on a daily basis. We thus must check in runtime if the argument is truthy before we use the argument. This would greatly reduce the verbosity of the codebase.

### 📃 Motivating Example

```
// long version 2024
foo(bar?: string | undefined | null){}

// shorthand
foo(bar??: string){}

// alternative syntax
for(bar: string??){}

// alternative syntax
foo(bar?: string?){}
```

### 💻 Use Cases

1. What do you want to use this for?
Reduce verbosity of the codebase

3. What shortcomings exist with current approaches?
Is possibly confused with the single ? syntax

4. What workarounds are you using in the meantime?
The long syntax

**Comment by BribeFromTheHive** [comment]
I literally logged in to request this just now, but you beat me to the punch!

I was just going to mention the benefits:
Quicker development time. Currently, I have a 'Nullable' type that I declared which takes a generic. So I'd do something like 'Nullable<string>' to make a variable that can be eithe undefined, null or string. But it is annoying of course.

I would also like to add:
When declaring a 'let' variable, it is currently impossible to declare it with an optional indicator as well. I would like to also have the option to do:
```ts
let i??: string;
if (condA) {
  i = 'Active';
} else if (condB) {
  i = 'Suspended';
} else {
  i = tryToGetAStringThatCouldReturnNullOrUndefined();
}
```

'null' is, of course, a much more understood word and much more keyboard-friendly than 'undefined'. I would respect the ability for ?? to be a valid syntax option. For parameters as well.

**Comment by RyanCavanaugh** [comment]
Discussed at #7426 and ultimately decided this wasn't a good fit. If we were going to expend the syntactic complexity to add this, it would need to be for a feature that was in *extremely* high demand, but that obviously hasn't been the case in the intervening seven years

**Comment by rotu** [comment]
> ```ts
> // long version 2024
> foo(bar?: string | undefined | null){}
> ```

Note that `foo(bar?: string | null)` is sufficient since `?` allows `undefined` as a value.

Also, I'd recommend getting out of the habit of using `null` for "no value". Two reasons come to mind:
- If you use JavaScript default arguments `baz(x = 'someDefault')`, then calling the function as `baz()` or `baz(undefined)` will both use the default value, whereas `baz(null)` will not.
- Similarly, `Number(undefined)` is `NaN`, whereas `Number(null)` is `0`, which can cause some subtle mistakes.

**Comment by BribeFromTheHive** [comment]
> Discussed at #7426 and ultimately decided this wasn't a good fit. If we were going to expend the syntactic complexity to add this, it would need to be for a feature that was in *extremely* high demand, but that obviously hasn't been the case in the intervening seven years

My main gripe with needing to include "null" in an ambiguous context is really with Angular and how their treatment of "null" in various contexts where "undefined" would have been more than sufficient, hence I have to double down on my type declarations in a myriad of ways that the simple nullish coalescing/optional chaining, friendlier 'x == null' versus 'x === null || x === undefined' handle much smoother.

I would wager a number of people that turn off "strictNullChecks" would be the target audience for this feature. They don't come here to request such graceful elements, because their work is unnaffected by it (but of course suffers in the process).

**Comment by MartinJohns** [comment]
> I would wager a number of people that turn off "strictNullChecks" would be the target audience for this feature.

People who turn off `strictNullChecks` don't have `undefined` and `null` types. For them this feature doesn't make any sense.

**Comment by BribeFromTheHive** [comment]
> > I would wager a number of people that turn off "strictNullChecks" would be the target audience for this feature.
> 
> 
> 
> People who turn off `strictNullChecks` don't have `undefined` and `null` types. For them this feature doesn't make any sense.

Correct, and they also do not have "never". My point is that if someone has disabled strictNullChecks, their project is far worse for it, but they may have left it disabled due to how much manual effort is needed. This would likely soften the blow, and make it more encouraging for these types of users to migrate towards better coding practices.
