### ISSUE TITLE
Could TypeScript allow the use of JS code as part of the type-checking process?

### ISSUE THREAD

**Issue by ghostinpeace** [microsoft/TypeScript#57147]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

I was essentially wondering about explicit choices that could have been made at some point regarding this question.

**Comment by RyanCavanaugh** [comment]
Extremely unlikely for a large number of reasons.

Code can't be reasoned about in the same way types can, e.g. you can't (in general) take a piece of JS code that returns `true` or `false` and say if it returns `true` for a subset or superset of the same inputs as some other piece of code, so any type-function couldn't have inferred subtyping rules.

Code can't be optimized with use of higher-level invariants like variance, so is likely to be slow in a lot of cases that *should* be fast

Security, of course - you can't just run this code natively or it's a security problem, so now you have to sandbox it (which slows it down further), define what's in and out of the sandbox, and then the things people typically want to make "code" for (files) are not something you want the sandbox to have access to.

**Comment by ghostinpeace** [comment]
Thank you very much for the insight :)

**Comment by fatcerberus** [comment]
> you can't (in general) take a piece of JS code that returns true or false and say if it returns true for a subset or superset of the same inputs as some other piece of code

Also known as the halting problem :wink:

**Comment by rotu** [comment]
> Also known as the halting problem 😉

~~the halting problem~~ [Rice's Theorem](https://en.wikipedia.org/wiki/Rice%27s_theorem)

> Rice's theorem states that all non-trivial semantic properties of programs are undecidable.

**Comment by fatcerberus** [comment]
> Rice's Theorem

Good to know there's a name for the more general statement - I realized quite a while ago that the recursive nature of the definition of "program" implied that *all* questions you can ask about the behavior of a program were as undecidable as the halting problem[^1], but didn't realize that fact had already been formalized.

[^1]: Since "program" is defined recursively, and there are subprograms for which an analyzer can never "find the end" (i.e. decide if it halts or not), then it follows that for any question you can ask, for at least one program, that information is completely inaccessible to the analyzer.
