### ISSUE TITLE
`override` keyword doesn't check symbol-key class members

### ISSUE THREAD

**Issue by whzx5byb** [microsoft/TypeScript#57141]
### 🔎 Search Terms

override symbol
override symbol member
override in:title

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYewdgzgLgBAZiEMC8MDKBPAtgIxAGwAoBKAbgFgAoYfAQwghgEEYBvKgXyqpvsYCEYAUwAeUIWAAmjFu0owFMEADchAJzUBLSUJgBtBCAC6JNjC6UOMIA

### 💻 Code

```ts
const foo = Symbol();
class A {
}

class B extends A {
    override [foo]() { }
} 
```

### 🙁 Actual behavior

It compiles.

### 🙂 Expected behavior

There should be an error: `This member cannot have an 'override' modifier because it is not declared in the base class 'A'.`

**Comment by topdev658** [comment]
Class inheritance in TypeScript does not allow derived classes to be broader than base classes. As per the Handbook:
TypeScript enforces that a derived class is always a subtype of its base class.

This means that members of the class that extends the base class that you override are covariant (as derived class is always a subclass of its base or, put simply, is more specific). Consider the following - the override works because "A" is a subtype of a broader union "A" | "B":

class A {
    static b : Array<{ c: "A" | "B" }> = []
}

class B extends A {
    static b : Array<{ c: "A" }> = [] // OK
}

**Comment by fatcerberus** [comment]
Please don't post AI-generated replies that just explain normal everyday behavior and have nothing to do with the actual defect being reported.

**Comment by topdev658** [comment]
I did post stackoverflow answer.  lol
