### ISSUE TITLE
The generic type cannot be successfully inferred.

### ISSUE THREAD

**Issue by LiST-GIT** [microsoft/TypeScript#57185]
### 🔎 Search Terms

The generic type cannot be successfully inferred.

### 🕗 Version & Regression Information

5.3

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBMEM7APoCMA8AVANFAwugGgHxQC8U6UEAHrAHYAmcUA3gL5QD8LUA2gNJQAlrSgBrCCAD2AM3IBdAFzl+cyjQgMmACgDGwKkoCGtENklhgcIyewA6e4YBOAcytDa0iI6gAFAJSkxMKe3gBKnFC6+kp4+GYWbsxioqJKtACuALbIXlCsdg4ubv6BUOFpEABuuexKAEwA3ABQ0um0eoKSIoY9hqgAItjohFrASkn0HEqDUNJT5FAAPjDwSGhY3HBbaVk53qzErAFJrE29hlrMTVA3UAD0d1D041BbbgCMdQDMedgPuJJMpkNMBhM4YAALQRMAA2wmgknSwCgAHdBDCYVAQIIIDD6E9BNIQiCoI54OkYZZbNdbtJxjTbrcLnoqPFLNhescGYyeSzbG9uYz8oLbsgoqyoOZ2VBOSwRTyoHyBQqbsKVYrxWy4Byelz1YylVt5b9jW8lAByAACCCcwHNmG5wqOQA

### 💻 Code

```ts
type test_b<T, CTX> = T extends {} ? { [K in keyof T]: T[K] extends (ctx: any, opts: any, ...args: infer P) => infer R ? (ctx: CTX, opts: { kkk: number }, ...args: P) => R : never } : 2;
function aaaa<D, T>(t: { d?: D, f?: T | test_b<T, { sss: number }> }) { }
aaaa({
    // d: { sss: 123 }, // Commenting this line out will yield different results.
    f: {
        a(ctx, opts, aaa) {
            ctx.sss
        },
        b(ctx, opts, aaa) {
            ctx.sss
        },
        c(ctx, opts, aaa) {
            ctx.sss
        },
        sss: '@start',
    },
})
```

### 🙁 Actual behavior

The error occurred after set `d`.

### 🙂 Expected behavior

It should always converge successfully.

**Comment by Andarist** [comment]
This is an interesting example of https://github.com/microsoft/TypeScript/issues/47599

The problem here is that when u add ur `d` property you make the whole object "partially inferrable" and the inference algorithm successfully infers `{ sss: number; }`. At the same time, the other part of the object is non-inferrable (due to the presence of context-sensitive functions). Judging by the observable results the parameter types are pulled before inferences for this reverse mapped type (`T`) can be made (maybe before a candidate for that `T` can even be created). 

When the property is not included no inferences are made in the first pass~ and the reverse mapped type and TS avoids pulling the parameter types. In the second pass~ the candidate for `T` can finally be created and it resolves much better in your case.

Or something like that 😉
