### ISSUE TITLE
When using "union types", the performance of structural operations is incomprehensible

### ISSUE THREAD

**Issue by Zachary0476** [microsoft/TypeScript#57181]
The demonstration is as follows：
```
type A = {
	a:string
}
type B = {
	b:string
}
type CombinType = A | B;
const obj: CombinType = {
    a:"i'm a",
    b:"i'm b",
}

const { a, b} = obj;

WRONG info：
1、Type 'CombinType' has no property 'a' and no string index signature.
const a: any
--------------------
2、Type 'CombinType' has no property 'b' and no string index signature.
const b: any
```
Expected: Normal structure, TS does not report errors;

Doubt: As mentioned above, since union types can accept obj variables that only carry property "a" or only carry property "b" or both, but cannot infer the correct type in object deconstruction operations? How should we understand relevant knowledge?

Description: Unable to understand the mysteries in the official documents after consulting, please do not hesitate to provide guidance;

**Comment by craigphicks** [comment]
The issue is still open, so - 
The key "a" is not in both, so to access the key you need a guard:
```
if ("a" in obj && "b" in obj){
    obj.a; // string
    obj.b; // unknown
}
if ("b" in obj && "a" in obj){
    obj.a; // unknown
    obj.b; // string
}
``` 
Odd, isn't it?  Let's split hairs.

**Comment by Zachary0476** [comment]
Fine, I understand. Thank you

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
