### ISSUE TITLE
Examples from handbook for "Writing .d.ts files" do not compile with 1.6.2

### ISSUE THREAD

**Issue by uwinkelvos** [Microsoft/TypeScript#5720]
I copied the examples for external modules from here http://www.typescriptlang.org/Handbook#writing-dts-files-examples into files and fed them to the compiler. They both do not compile. The _zoo example_ can be fixed by adding a "declare", but i have no idea how to fix the _eagle example_.

See my test project here: https://github.com/uwinkelvos/tsc-dts-bug

**Comment by DanielRosenwasser** [comment]
Hey @uwinkelvos, if you'd like to send a PR to https://github.com/Microsoft/TypeScript-Handbook, we'd appreciate it.

**Comment by DanielRosenwasser** [comment]
Just a question, which eagle example do you mean specifically?

**Comment by uwinkelvos** [comment]
This:
https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Writing%20Definition%20Files.md#typing-4
https://github.com/uwinkelvos/tsc-dts-bug/blob/master/external/eagle.d.ts

I kind of need exactly that functionality to type koa-body.

**Comment by DanielRosenwasser** [comment]
Fixed by https://github.com/Microsoft/TypeScript-Handbook/pull/102

What's wrong with that example? [It seems to work correctly in the playground](http://www.typescriptlang.org/Playground#src=%2F%2F%20Note%3A%20can%20use%20any%20name%20here%2C%20but%20has%20to%20be%20the%20same%20throughout%20this%20file%0Adeclare%20function%20eagle(name%3A%20string)%3A%20eagle%3B%0Adeclare%20module%20eagle%20%7B%0A%20%20%20%20var%20favorite%3A%20string%3B%0A%20%20%20%20function%20fly()%3A%20void%3B%0A%7D%0Ainterface%20eagle%20%7B%0A%20%20%20%20new(awesomeness%3A%20number)%3A%20eagle%3B%0A%7D%0A%0Aexport%20%3D%20eagle%3B).

**Comment by uwinkelvos** [comment]
The .d.ts file will "compile", but the code using it won't. please see: https://github.com/uwinkelvos/tsc-dts-bug

**Comment by DanielRosenwasser** [comment]
Wow, I just realized that. That's awful. I think the intent was to export something that had a type and value side, but the example conveys that poorly.

**Comment by DanielRosenwasser** [comment]
Fixed in 55ceaf7b86ff4314dfd8b3bb8214d336ddd02bb1.

**Comment by uwinkelvos** [comment]
ah thx. fixed the eagle-eddie-diversion here: https://github.com/Microsoft/TypeScript-Handbook/pull/103

This might not solve my Koa typing problems though, but that's an other story/issue. :)

**Comment by DanielRosenwasser** [comment]
Hopefully you're not having too much trouble! Feel free to post an issue if there's a real problem with the language, or if you're unsure of how to accomplish something there's always StackOverflow and Gitter.
