### ISSUE TITLE
Class decorators can't be used with static private identifier (using 'experimentalDecorators' and 'emitDecoratorMetadata')

### ISSUE THREAD

**Issue by StiliyanKushev** [microsoft/TypeScript#57309]
### 🔎 Search Terms

"Class decorators can't be used with static private identifier", "ts(18036)"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ.

### ⏯ Playground Link

https://www.typescriptlang.org/play?experimentalDecorators=true&emitDecoratorMetadata=true&ts=5.3.3#code/GYVwdgxgLglg9mABAERAWzQT2QUwnAJwEMpCAeAFQD4AKAOgaIIHMBnALkSLEwG0BdAJScKiAN6ICOKCAJIwIADaKurRKIC+AKERaAAqgzY8hEoRqCtERUVZrDWAMI274nYg+soJGBEQBiABN0LAAFAhgANxIcRwQvbihEAF5EAEYAJgBmAG4tDSA

### 💻 Code

```ts
function DummyDecorator<T>(...args: any[]): T { return null as T }
 
@DummyDecorator()
class DummyClass {
    static #dummyPrivateConstant = 123;
}
```

### 🙁 Actual behavior

We get a compile time error that effectively should never happen as the tsconfig change introduces little to no difference in the actual expected behavior of the static private (encapsulated) properties.

### 🙂 Expected behavior

I expect this to work just like it would if you removed:

```diff
-        "emitDecoratorMetadata": true,
-        "experimentalDecorators": true,
```

from the `tsconfig.json` file.

**Comment by RyanCavanaugh** [comment]
Experimental decorators have different semantics from the standard decorators and aren't compatible with private static properties.

**Comment by StiliyanKushev** [comment]
Hey @RyanCavanaugh :wave: 

Im sorry, but this seems rather dubious. Respectfully, would you care to elaborate and provide some sources I can read to educate myself?

I particularly don't understand why "ts(18036)" is marked as working as intended. I mean, why wouldn't it be able to work in theory?

**Comment by RyanCavanaugh** [comment]
@rbuckton can you fill in additional context?

**Comment by StiliyanKushev** [comment]
Hm, I'd love to, I'm just not sure what else to add to my previous message. Perhaps it's a stupid question, but my question simply put is: 

Why would the experimental decorators not support static private fields?

**Comment by rbuckton** [comment]
The runtime semantics for TypeScript's legacy "experimental" decorators are wholly incompatible with native JavaScript private names. In both the legacy and native decorators implementations, class decorators may optionally replace the constructor. In the native decorators proposal, private fields and methods are installed on the _final_ class, after decorators are applied. In the legacy decorator implementation, private fields and methods are installed on the _initial_ class, before decorators are applied. As a result, any decorator that performs constructor replacement on a class that uses private static fields and methods are guaranteed to fail on use.

Here is a modified version of your example [in the playground](https://www.typescriptlang.org/play?experimentalDecorators=true&emitDecoratorMetadata=true&ts=5.3.3#code/GYVwdgxgLglg9mABAERAWzQT2QUwnAJwEMpCAeAFURwA8ocwATAZ0TBwHdEAKAOn6IEA5swBciImEwBKRAF4AfBKkLuUQUJxRxFaTsQBvAFCJTiAPTnEBLSAJJ1wrQG4LVjoQDWzE2cvXbe0RwRhxgGHZGV38PAm9fUxsoOyQIABsiZlZaeiZWR00oQwBfaKsAIxsieOKTIwABVAxsPEISQiN0zNYmrABhDKzDBMRmdVgIRABiRnQsAAUCGAA3Ehw+hDHJIrlEAEYAJgBmZxGticRgODhuWWMzB8QoAAsYZl4ZucxFlbWNsC2YCgpwetVqRl6mAG3V4Vxu0mcQA):

```ts
function DummyDecorator<T extends new (...args: any) => any>(target: T): T {
    // return target; // works
    // return undefined; // works
    return class extends target {}; // breaks
}
 
@DummyDecorator
class DummyClass {
    static #dummyPrivateConstant = 123;
    static foo() {
        this.#dummyPrivateConstant;
    }
}

DummyClass.foo();
```

If you click Run in the playground for the above example, you will see that the private static field access in `DummyClass.foo()` can only succeed if the constructor is not replaced by the decorator. As a result, we report an error to warn you against this combination as it is likely to result in errors or other incorrect behavior.

However, this is not an issue when targeting native decorators, since the static private field is installed on the wrapped class: [playground](https://www.typescriptlang.org/play?ts=5.3.3&emitDecoratorMetadata=true&experimentalDecorators=true#code/GYVwdgxgLglg9mABAERAWzQT2QUwnAJwEMpCAeAFURwA8ocwATAZ0TBwHdEAKAOn6IEA5swBciImEwBKRAF4AfBKkLuUQUJxRxFADSIA+vjD064gMIAbIs2a58xUgXMJTUSguk7EAbwBQiIGIAPTBiARaIARI6sJaANwhYRyEANbMAUGh4ZHRiOCMOMAw7IyJ2SkE6ZmBEVBRSBDWttR0DCyIsZpQvgC+5WEARhFE1b0BfgACqBjYeIQkhH5NNqwzWFarvjWIzOqwEIgAxIzoWAAKBDAAbiQ4LmB7kj1yiACMAEwAzPE7TweIYBwODcWT+IIQzoACxgzF4JzOmEuNzuDyeJl+EPG4z860wm1svCBIOk8SAA)

**Comment by StiliyanKushev** [comment]
I see, thanks!

And is there any particular reason why there's a discrepancy between the two decorator implementations when it comes down to which of the two classes we'll attach the private fields onto? (final class vs the initial)

**Comment by fatcerberus** [comment]
TypeScript `experimentalDecorators` was based on an older version of the ES decorator spec, where presumably that's the way it was written.  The spec text changed before it reached Stage 3.  Assuming that's the case, it seems likely the behavior was changed for precisely this reason - the older behavior makes interop with private fields impossible.  You'd have to ask a TC39 member for a definitive answer, though.

This kind of thing, incidentally, is why TS now intentionally avoids introducing runtime features until they're at least Stage 3 in the ECMAScript standardization process.

**Comment by StiliyanKushev** [comment]
Hm, okay. So I guess we'll just have to live with this discrepancy.

FYI, many frameworks use the experimental decorators because they need the metadata for automation purposes.
That means we can't use static private fields with them. 

Actually, I only found this out due to my hitting that exact bump, using NestJS.

But okay, not that big of a deal I guess :)

**Comment by fatcerberus** [comment]
I think there’s ongoing work on a standard for decorator metadata with native decorators, fwiw

**Comment by rbuckton** [comment]
Yes, Decorator Metadata is also a stage 3 proposal and is supported by TypeScript when using native decorators downlevel, so long as you shim the `Symbol.metadata` property.

Native decorators can access a metadata object that is shared for all declarations on the class by accessing `context.metadata`. This object will be installed on the class constructor as `[Symbol.metadata]`. Since this is a single shared object for the whole class, it's up to the decorator author to ensure they keep per-element metadata distinct using information about the element on the `context` object.
