### ISSUE TITLE
[TS 5.4.0-beta] `instaceof` narrowing impacted by prototype property

### ISSUE THREAD

**Issue by acutmore** [microsoft/TypeScript#57397]
### 🔎 Search Terms

instanceof, narrowing, prototype

### 🕗 Version & Regression Information

- This changed between versions 5.3.3 and 5.4.0-beta. 
- This changed on 5.4.0-dev.20231130 ([commits](https://github.com/microsoft/TypeScript/compare/2869579b2cad770ae20617e4148741c2ce35ffdc...7216ee0bb821b4b565d54c52dcbf788a3fdf7062))

### ⏯ Playground Link

https://www.typescriptlang.org/play?target=99&ts=5.4.0-dev.20231130#code/CYUwxgNghgTiAEkoGdnwOoEtgHMQBd4BvAKHnNGXxgHsBPACgEoAueANxuwG4SBfEiVBI4iGgDsqGbHnwBhCVRgBXMPhow2pcuXEgA7szZZcBXgKHhoosIsIBZEOOUnZc6Ki1kdew62LeOjqYyI7OADIh+GwARjQ0ECBQ4rxBfPAAZNKm+Kk6AA606vh0+SBsJWU0AGbZbnYqahrc8AD0rfAAPAC03fBwALY07JjiOPD4ABYh8FCc2GggMLQw-LwklQhhLjIE8AC88ACSkvjJYCAAKqUgnZs18NuuBO4oyAB868LWCLanj04djkKjcHk9dvIPGgstofAYjADnM98GtBO10RjMVjsTjcXj0YJEoQ-vgnNFEUDZPAAD7wZTiUDVUYgYC8b6wX52DjGCHrTC1BjseCjKjnEBgwHIpgBILkElkg4cFrtLq9eC+eBLFbC8TwACsADoACwGgAM3RiBCg-EEIAAHvkNIQiAIgA

### 💻 Code

(reduced down from large repo as best I could)

```ts
declare class Widget {
   destroy(): void;
}

declare const WidgetConstructor: {
    new(): Widget;
}

declare const MenuWidgetClass: {
    new(): {
        isMenuList: boolean;
    } & Widget;
    prototype: typeof WidgetConstructor; // <-- removing this avoids error
};

type MenuWidget = InstanceType<typeof MenuWidgetClass>;

declare const MenuWidget: typeof MenuWidgetClass & {
    new(): MenuWidget
};

/////////////////////////////////////////////////////////

let content: MenuWidget | undefined;
declare const v: Widget;

if (v instanceof MenuWidget) {
      content = v; // <-- new error in 5.4.0-beta
}
```

###  New behavior

TypeScript `5.4.0-beta` appears to be consulting the `.prototype` property of the type in a way that it wasn't before resulting in the `instanceof` narrowing to narrow to the base class.

###  Previous behavior

The code in `5.3.3` was expecting the `instanceof` to narrow to the return type of the function being consulted.

### Additional information about the issue

Note: this is more of a change report than a bug report, as I don't think this was announced in the 5.4.0-beta breaking changes. I suspect the change is an improvement and is catching a potential issue that was previously unsafe.

**Comment by acutmore** [comment]
> A better commits list can be found [here](https://github.com/microsoft/TypeScript/compare/2869579b2cad770ae20617e4148741c2ce35ffdc...7216ee0bb821b4b565d54c52dcbf788a3fdf7062).

Thanks. That is what I used (the `githead` from package.json). Our two lists of commits are the same, just in reverse order?

**Comment by RyanCavanaugh** [comment]
If you're curious to bisect something, [`every-ts`](https://github.com/jakebailey/every-ts) is the best tool for the job

**Comment by jakebailey** [comment]
Off topic-ish, but the issue template links to it; is there something we can do to make it more obvious?

**Comment by acutmore** [comment]
Maybe if I hadn't raised a few tickets in the past I would have been less hasty to fill in the form without really reading the extra info bits.

That said, maybe also putting a link to it in a HTML comment in the text box would make it more visible. As harder to not read the inputs.

**Comment by RyanCavanaugh** [comment]
Bisect confirmed #54753

**Comment by Andarist** [comment]
I think this works kind of as expected right now. 

The break is related to this change:
```ts
type P = (typeof MenuWidget)["prototype"]; // TS 5.3: any, TS 5.4: new () => Widget
const p = MenuWidget.prototype; // TS 5.3: any, TS 5.4: new () => Widget
```

It boils down to the fact that a concrete `prototype` property trumps the `.prototype` that comes from the "object function property augment". We can verify that by going to the definition of this property - in TS 5.3 it brings us to two locations. One of them is inside `interface Function`. This change to `prototype` has been spotted in the process of reviewing https://github.com/microsoft/TypeScript/pull/54753 (albeit in a different context) and it has been accepted as working as intended now. I think it makes sense to keep the behavior as otherwise some patterns become impossible because there is no way to opt-out of your types being impacted by this augment.

That said, it has a very surprising effect on this given example. I think though that it just uncovers a weird implicit implementation detail. It is surprising that the official `InstanceType` doesn't quite follow the logic embedded in `getInstanceType` (that is used by `instanceof`).

The "true" `InstanceType` (one that would mimic what `getInstanceType` does internally) would look something like this:
```ts
type IfAny<T, Y, N> = 0 extends 1 & T ? Y : N;

type ConstructorType = abstract new (...args: never) => any;

type Constructed<T extends ConstructorType> = T extends abstract new (
  ...args: never
) => infer R
  ? R
  : any;

type TryConstruct<T> = T extends ConstructorType ? Constructed<T> : {};

type InstanceType2<T> = "prototype" extends keyof T
  ? IfAny<T["prototype"], TryConstruct<T>, T["prototype"]>
  : TryConstruct<T>;
```

**Comment by acutmore** [comment]
Thank you so much for that analysis @Andarist! I can confirm back in the original project that the `["prototype"]` lookup has gone from `Function.prototype`'s `any` to the actual concrete `prototype` property of the type. And agree that this is overall an improvement. Chalking it up as a "positive breaking change".

This change is only causing one error in a widget that is still using our 'legacy' class system that pre-dates ES2015 classes (thus all the manual class-like type generation), and we can work around this in our code until the widget gets migrated.

Thanks again!
