### ISSUE TITLE
Proposal of a convention about npm modules distribution.

### ISSUE THREAD

**Issue by vilic** [Microsoft/TypeScript#575]
There was an discussion about generating ambient declarations for external CommonJS modules: http://typescript.codeplex.com/workitem/2080

But even if typescript generates the definitions as we what we want, we'll still need to add references manually, which is not doing better job than JS libs with NuGet DefinitelyTyped packages.

I propose that when we publish a typescript package via npm, publish the .d.ts file(s) generated with the current style along with it.

So that we can manage to write a tool (or add a feature to something like WebEssentials) to watch related node_modules directory, resolve the definition references and create wrapped definition file(s) under scripts/typings folder.

Thoughts?

**Comment by mhfrantz** [comment]
We're interested in a cleaner solution than ts-pkg-installer, which we wrote to address TypeScript modularity in the NPM/TSD ecosystem.

https://github.com/RedSeal-co/ts-pkg-installer

We also use dts-bundle, which complements ts-pkg-installer in that it generates a declaration file that can  be installed with ts-pkg-installer.

**Comment by mhegazy** [comment]
@vladima  has  proposal in #2338 for managing typings as part of resolving node_modules. the idea is that the package.json would have a "types" as a property, and the typescript compiler will look up that file and use it if it exists. would that work?

**Comment by vilic** [comment]
@mhfrantz I am also designing a package manager for TypeScript. Hoping it could be compatible with NPM and other package managers like bower. And I would like it to support some simple pre-compile features for supporting libraries with or without module system. https://github.com/vilic/tying

**Comment by vilic** [comment]
@mhfrantz I am also designing a package manager for TypeScript. Hoping it could be compatible with NPM and other package managers like bower. And I would like it to support some simple pre-compile features for supporting libraries with or without module system. https://github.com/vilic/tying

**Comment by mhfrantz** [comment]
@mhegazy, having reference paths work with node_modules/package.json would be ideal.  The most brittle part of the reference path feature is the necessity of specifying the exact location of files.  Resolving reference paths within node_modules makes the most sense from the NodeJS standpoint.

It is important to incorporate DefinitelyTyped declarations as well, as all type information is not embedded within the NodeJS module itself.

It is also important to de-dupe the declarations.

**Comment by mhegazy** [comment]
Thanks @mhfrantz  for the feedback, a few comments:

> The most brittle part of the reference path feature is the necessity of specifying the exact location of files. Resolving reference paths within node_modules makes the most sense from the NodeJS standpoint.

The proposal in  #2338 looks in node_modules and reads package.json

> It is important to incorporate DefinitelyTyped declarations as well, as all type information is not embedded within the NodeJS module itself.

Any proposals on how to do that, and how would that be diffrent from something like what tsd is doing today.

> It is also important to de-dupe the declarations.

What are the rules? any proposals on how this should be done?

**Comment by mhfrantz** [comment]
@mhegazy If you look at what ts-pkg-installer is trying to do, it builds a TSD config file so that if multiple modules depend on the same declaration, they will all resolve to the same file.  This is awkward, since it involves building config files, and then running the TSD utility on the result.

If it were incorporated into TSC, then perhaps reference paths would contain simple names, like a module name.  It could look in node_modules first, and then in typings.

For example, suppose you see this:
```
///<reference path="mocha"/>
```
This is a reference to the module "mocha", which (today) has no TypeScript declaration of its own.  Thus, it would resolve to typings/mocha/mocha.d.ts.

**Comment by mhegazy** [comment]
so what is the proposal, add `<root>/typings` as an implicit include path? though I am not a fan of include paths in general.

**Comment by mhfrantz** [comment]
@mhegazy It is not as simple as adding `<root>/typings` as an include path, since the logic for determining the exact *.d.ts file name varies.  Given a reference to "@scope/foo":
- If we find a module in node_modules called "@scope/foo", and its package.json contains a "types" section, then use that *.d.ts file.
- If we find a module in typings called "@scope/foo", then use foo.d.ts in that directory.

Thus the proposal is to support both NPM packages written in TypeScript with embedded type declarations as well as NPM packages whose type declarations come via TSD.  This can be accomplished with a single, coherent reference path syntax that is agnostic of the distinction between these two cases.

**Comment by poelstra** [comment]
@mhfrantz Just re-read this thread, and noticed that I seem to have run into a similar issue as what you describe (de-dupeing declarations, and supporting TSD case).

I created #2839 with a proposal for a solution, would it fit to your use-case too?
