### ISSUE TITLE
Return completions in alphanumeric order

### ISSUE THREAD

**Issue by AnandaArya** [microsoft/TypeScript#57742]
Hello,  I'm working with TypeScript in Visual Studio Code and I've noticed that the autocomplete suggestions for union types are not displayed in a logical order. Specifically, I have a union type for column sizes in a grid layout system:
 
 
![image](https://github.com/microsoft/vscode/assets/59549599/c92a16b4-619d-4c70-ba2e-97fb22279734)

**Comment by RyanCavanaugh** [comment]
What's the bug here? The `sortText` isn't wrong; it's this entry:
```ts
    export const SortText = {
        // Presets
        LocalDeclarationPriority: "10" as SortText,
        LocationPriority: "11" as SortText,
        OptionalMember: "12" as SortText,
```
The items are coming back in lexical string ordering; VS Code can reorder those if that's desired

**Comment by jrieken** [comment]
I think there are different understandings of `sortText`. For VS Code it means how an item is sorted relative to other items of a result. When all sortText-values are equal we fallback to comparing labels. 

@RyanCavanaugh So the ask is that TS sorts its suggestion in lexical order (in this case) or in the order declaration (in this case) because TS is has the most complete knowledge

**Comment by RyanCavanaugh** [comment]
It is sorted. `1` comes before `2` and it's a lexicographic sort.

**Comment by mjbvz** [comment]
Within a the same `sortText` level, TS seem to already sort completion items. I think this uses TS's `compareStringsCaseSensitiveUI`

What we'd like is for this to use an alphanumeric sort. This may be as simple as adding `numeric: true` in the `Intl.Collator` used: https://github.com/microsoft/TypeScript/blob/b5b6048bb3c4a1c8272c85062bc0b585fcb99754/src/compiler/core.ts#L2256
