### ISSUE TITLE
Getting error `Class '*' used before its declaration. ts(2449)`  - for class decorators

### ISSUE THREAD

**Issue by Avivbens** [microsoft/TypeScript#57766]
### 🔎 Search Terms

used before its declaration. ts(2449)
Class decorators having issues to contain the class namespace 

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions `5.4.2` (not exists) and `5.5.0-dev.20240312` (exists)

### `5.4.2`
![CleanShot 2024-03-13 at 21 57 01@2x](https://github.com/microsoft/TypeScript/assets/77183871/7b2c0e34-6035-4e9f-9323-f5050340dbb3)

### `5.5.0-dev.20240312`
![CleanShot 2024-03-13 at 21 56 43@2x](https://github.com/microsoft/TypeScript/assets/77183871/5c090c7c-96be-4877-a2e4-506bcc9beae5)

### 💻 Code

```ts
@Injectable()
export class CacheService {
  constructor(
    @Inject(REDIS_CLIENT) private readonly cache: IRedisClient,
    //  Getting the error for the following line
    @LoggerNamespace(CacheService.name) private readonly logger: Logger,
  ) {}

  /**
}
```

### 🙁 Actual behavior

Getting this error:

```
Class 'CacheService' used before its declaration.ts(2449)
cache.service.ts(8, 14): 'CacheService' is declared here.
```

### 🙂 Expected behavior

No errors should be presented.

**Comment by fatcerberus** [comment]
This change was intentional, see https://github.com/microsoft/TypeScript/issues/57366 -> https://github.com/microsoft/TypeScript/pull/57666

**Comment by Avivbens** [comment]
> This change was intentional, see #57366 -> #57666

I get your point.
But for implementations like I mentioned, there is just no sense to emit an error. 
The provided example is part of a NestJS application, which uses the **`Injectable` decorator.**
Therefore, the `name` property under the class namespace **would always exist.** 



I think we need to come up with a solution that handles all conditions.


### PS.
By keeping it the way it is, I think it might be a breaking change 🤷‍♂️

**Comment by MartinJohns** [comment]
Probably worth mentioning that this only affects legacy decorators, as JavaScript decorators don't support parameters (yet).

**Comment by fatcerberus** [comment]
> this only affects legacy decorators, as JavaScript decorators don't support parameters

Even if they did, IIRC the spec-mandated behavior for native decorators is to evaluate all decorator expressions *first* before running any of them, so it doesn't matter what `Injectable` does in that case.

**Comment by Avivbens** [comment]
> > this only affects legacy decorators, as JavaScript decorators don't support parameters
> 
> Even if they did, IIRC the spec-mandated behavior for native decorators is to evaluate all decorator expressions _first_ before running any of them, so it doesn't matter what `Injectable` does in that case.

In fact, it is. the `Injectable` itself is a decorator, so it is also running **before** the class constructor. 
That is why we **do get** the `class.name` correctly in here. 

Bottom line - this change might be good, but still needs to be modified, as it has an effect over a good-practice code which is not supposed to contain any kind of bugs whatsoever.

**Comment by rbuckton** [comment]
> Probably worth mentioning that this only affects legacy decorators, as JavaScript decorators don't support parameters (yet).

Yes, though native parameter decorators would also fail since `CacheService` would still be in TDZ when they execute.

We previously allowed this in legacy decorators because class decorators (incl. constructor parameter decorators) because the pre-decorated class is bound and we just reassign it. However, it's generally unsafe to reference `ThisClass.foo` from a decorator factory since it may not be initialized yet. That `.name` works is only because every class/function has a `.name` property.

Instead, it's far safer to depend on the name passed to the decorator itself:

```ts
class CacheService {
  constructor(
    @((t, k, i) => LoggerNamespace(t.name)(t, k, i))
    private readonly logger: Logger
  ) {}
}
```

[Playground Link](https://www.typescriptlang.org/play?experimentalDecorators=true#code/PTAEAEFMA8AdIE4EsC2kB2AXAhgGwCKQDGA9gtpmQM4BcomCArpAFAsBmj6RmSJ6oADIkA5iMQA5bGiqxsRSAAp00yLPmQ6VBknQiAlHQAK2cmkyJCpcpQSgA3i1DPQCSJkYIBizABpQANb+SPqgALwAfA5OLrGk6FQkuJAAdLiiyqrqCvoA3DHOAL75hWyYAJ7wQqLidmEOxWxEuNhUVKAAwvIAFpAAyogAbkgK0c7x2kw8ZIoFEIo+-kGgIeFRwmKSWXIKPikqaPqLgcH6+nOwyIMUkK6Q2AAm-LjloOmbCHQbtTGh9qWFIA)

**Comment by Avivbens** [comment]
> > Probably worth mentioning that this only affects legacy decorators, as JavaScript decorators don't support parameters (yet).
> 
> Yes, though native parameter decorators would also fail since `CacheService` would still be in TDZ when they execute.
> 
> We previously allowed this in legacy class decorators (incl. constructor parameter decorators) because the pre-decorated class is bound and we just reassign it. However, it's generally unsafe to reference `ThisClass.foo` from a decorator factory since it may not be initialized yet. That `.name` works is only because every class/function has a `.name` property.
> 
> Instead, it's far safer to depend on the name passed to the decorator itself:
> 
> ```ts
> class CacheService {
>   constructor(
>     @((t, k, i) => LoggerNamespace(t.name)(t, k, i))
>     private readonly logger: Logger
>   ) {}
> }
> ```
> 
> [Playground Link](https://www.typescriptlang.org/play?experimentalDecorators=true#code/PTAEAEFMA8AdIE4EsC2kB2AXAhgGwCKQDGA9gtpmQM4BcomCArpAFAsBmj6RmSJ6oADIkA5iMQA5bGiqxsRSAAp00yLPmQ6VBknQiAlHQAK2cmkyJCpcpQSgA3i1DPQCSJkYIBizABpQANb+SPqgALwAfA5OLrGk6FQkuJAAdLiiyqrqCvoA3DHOAL75hWyYAJ7wQqLidmEOxWxEuNhUVKAAwvIAFpAAyogAbkgK0c7x2kw8ZIoFEIo+-kGgIeFRwmKSWXIKPikqaPqLgcH6+nOwyIMUkK6Q2AAm-LjloOmbCHQbtTGh9qWFIA)

Sounds reasonable, but still a breaking change
Just note that in the RC release

**Comment by rbuckton** [comment]
> Therefore, the `name` property under the class namespace **would always exist.**

As I said above, `name` is only available because all functions have a name, it's not safe to access other fields and we aren't likely to special case this.

> By keeping it the way it is, I think it might be a breaking change 🤷‍♂️

Yes, it is.

**Comment by Avivbens** [comment]
> > Therefore, the `name` property under the class namespace **would always exist.**
> 
> As I said above, `name` is only available because all functions have a name, it's not safe to access other fields and we aren't likely to special case this.
> 
> > By keeping it the way it is, I think it might be a breaking change 🤷‍♂️
> 
> Yes, it is.

Thanks 🙏 

So we'll expect some changes over TS v6+

**Comment by RyanCavanaugh** [comment]
To clarify: "this was incorrectly allowed" isn't a breaking change, it's a bug fix.

**Comment by Avivbens** [comment]
> To clarify: "this was incorrectly allowed" isn't a breaking change, it's a bug fix.

Well, this bug exists for like a few years then, and all Typescript consumers might think upgrading to the new version won't break anything. This is not the case in here. 

As part of the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) standards, it seems to be a breaking change, even if this is indeed a bug. 

If you have no intention to drop this change, I'm just asking you to be responsible in terms of versioning. 

Thanks a lot 🙏

**Comment by RyanCavanaugh** [comment]
I'm not sure why semver has a patch field if you're not allowed to fix bugs in patch versions. Can you elaborate?

**Comment by fatcerberus** [comment]
TypeScript intentionally doesn’t follow semver.

**Comment by Avivbens** [comment]
> I'm not sure why semver has a patch field if you're not allowed to fix bugs in patch versions. Can you elaborate?

Fixing bugs is always more than welcome!
Just keep in mind - if you're not backward compatible, you should notify your consumers (by semantic versioning).
I personally read release notes, looking for breaking changes / features / bug fixes (based on the case). 



> TypeScript intentionally doesn’t follow semver.

Why is that?
I do not see any reason why not being backward compatible / notify about the breaking changes. 


And for both of you, here is an idea of how you could keep that without the breaking change:
Simply add a new property under `tsconfig`, enabling this new rule. 
The property not there? behave like before. 

Mark this `false` option as deprecated, and remove the compatibility over the next major release.

**Comment by RyanCavanaugh** [comment]
> Fixing bugs is always more than welcome!
> Just keep in mind - if you're not backward compatible, you should notify your consumers 

If a bug was observable by a consumer of your library, then someone could have taken a dependency on the wrong behavior, and been "broken" by an upgrade. If the bug wasn't observable, you wouldn't have shipped an update in the first place, so obviously the patch field exists so that libraries can remove buggy behavior.

**Comment by Avivbens** [comment]
> > Fixing bugs is always more than welcome!
> 
> > Just keep in mind - if you're not backward compatible, you should notify your consumers 
> 
> 
> 
> If a bug was observable by a consumer of your library, then someone could have taken a dependency on the wrong behavior, and been "broken" by an upgrade, but that's not what anyone means by "breaking change". If the bug wasn't observable, you wouldn't have shipped an update in the first place, so obviously the patch field exists so that libraries can remove buggy behavior.

Not going to argue on here, just give it a second thought. 
As I said, this "bug" exists for more than a few years, and for the example I've posted here, it is not a bug at all. The code works perfectly without any issues (BTW, it is the best-practice implementation by NestJS).

**Comment by rbuckton** [comment]
> Why is that?

One of the goals of the TypeScript language is to help you find bugs in your code by continually improving our type checking and code analysis. Essentially, _every_ TypeScript release contains what some might consider to be breaking changes, but that's the point. More often than not, when we call out a breaking change it is either because it is something that affects how you consume upstream code, something that affects how downstream consumers consume your code, or because we had to make a choice between two equally reasonable behaviors. 

If your code works today because we incorrectly inferred `string` when we should have inferred `"foo" | "bar"` and you're passing the value `"baz"`, then that's a bug. If your build fails because a new TypeScript version improved that inference that's not a breaking change, that's a feature.

If we followed semver to the letter and considered such changes to be breaking, we would just be constantly revving the major build number and the semantic meaning behind the version number becomes meaningless. Instead, we tend to use the major version number as a way to indicate major breaking changes in our API, or as an indicator of a major milestone in the language's feature set. In between major versions we generally avoid API breaking changes in favor of soft deprecations and compiler diagnostics for soon-to-be-removed features. This is more in line with the spirit of semver.

> I do not see any reason why not being backward compatible / notify about the breaking changes.

We do notify users about breaking changes when those changes meet the criteria above (or something similar, as this is a very rough approximation).

**Comment by rbuckton** [comment]
> (BTW, it is the best-practice implementation by NestJS).

If the best practice is to inject the current class's `name` for a specific decorator, I would expect they could have the decorator do that by default since that information is readily available to the decorator itself.

**Comment by Avivbens** [comment]
> > Why is that?
> 
> 
> 
> One of the goals of the TypeScript language is to help you find bugs in your code by continually improving our type checking and code analysis. Essentially, _every_ TypeScript release contains what some might consider to be breaking changes, but that's the point. More often than not, when we call out a breaking change it is either because it is something that affects how you consume upstream code, something that affects how downstream consumers consume your code, or because we had to make a choice between two equally reasonable behaviors. 
> 
> 
> 
> If your code works today because we incorrectly inferred `string` when we should have inferred `"foo" | "bar"` and you're passing the value `"baz"`, then that's a bug. If your build fails because a new TypeScript version improved that inference that's not a breaking change, that's a feature.
> 
> 
> 
> If we followed semver to the letter and considered such changes to be breaking, we would just be constantly revving the major build number and the semantic meaning behind the version number becomes meaningless. Instead, we tend to use the major version number as a way to indicate major breaking changes in our API, or as an indicator of a major milestone in the language's feature set. In between major versions we generally avoid API breaking changes in favor of soft deprecations and compiler diagnostics for soon-to-be-removed features. This is more in line with the spirit of semver.
> 
> 
> 
> > I do not see any reason why not being backward compatible / notify about the breaking changes.
> 
> 
> 
> We do notify users about breaking changes when those changes meet the criteria above (or something similar, as this is a very rough approximation).

Really appreciated your answer, very well explained. 

Thank you for your support 🙏
