### ISSUE TITLE
`tsc --watch` changes shell's current directory to ~ in Terminal.app while running

### ISSUE THREAD

**Issue by verhovsky** [microsoft/TypeScript#57894]
### 🔎 Search Terms

watch current directory

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because it's too much work

### 💻 Code

```sh
tsc --watch -p ./
```

### 🙁 Actual behavior

When running the above command in macOS's Terminal.app and pressing Cmd+t to open a new shell it opens a new shell at my home directory

### 🙂 Expected behavior

Terminal.app should open the new shell in the same directory that I ran the command from.

### Additional information about the issue

```
webpack --watch
```

works the way I expect.

**Comment by RyanCavanaugh** [comment]
We never call `chdir` or equivalent as far as I can tell -- I don't know how Terminal.app decides what the new shell directory logic is, but maybe it's something else?

**Comment by verhovsky** [comment]
Yea, it's something to do with Terminal.app. iTerm2 does the right thing after enabling Profiles → Working Directory → Reuse previous session's directory and so does Alacritty.

**Comment by RyanCavanaugh** [comment]
If you can point to what we're doing wrong I'm happy to fix, but we don't have a realistic way to reverse engineer what Terminal.app is looking for / doing.

**Comment by Dremora** [comment]
This has been bothering me for a while, so I decided to investigate.
The culprit is the code that clears the screen in watch mode. Thus, running `tsc` with `--preserveWatchOutput` serves as a workaround.
In [sys.ts](https://github.com/microsoft/TypeScript/blob/6d3be985c82bead3b41348de76efec8110c677c5/src/compiler/sys.ts), in the `clearScreen` function, `\x1Bc` is sent to the stdout to erase the screen, where `\x1B` initiates an escape sequence and `c` executes [Reset to Initial State](https://vt100.net/docs/vt220-rm/chapter4.html#S4.18.2), which, amongst other things, seems to reset current working directory in a macOS Terminal.

I've checked out how similar functionality is implemented in Jest, which doesn't suffer from the same issue. [Jest is using](https://github.com/jestjs/jest/blob/cce44d767e5e1d5c62eaaf5f93fb73748c25266b/packages/jest-util/src/specialChars.ts#L17) a combination of 3 escape sequences (with a fallback to another combination on Windows):

- `\u001B[2J` - erases entire screen
- `\u001B[3J` - erases saved lines
- `\u001B[H` - moves cursor to home position (0, 0)

See also:
- https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797
- https://github.com/vitest-dev/vitest/issues/3608

I'm happy to submit a PR if this issue gets reopened.

**Comment by RyanCavanaugh** [comment]
@Dremora nice 🕵️!
