### ISSUE TITLE
Inconsistency with Template Literal Types and Conditional Types

### ISSUE THREAD

**Issue by 13OnTheCode** [microsoft/TypeScript#57983]
### 🔎 Search Terms

"Template Literal Types", "Conditional Types", "`${number}`"

### 🕗 Version & Regression Information

5.4.3

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAKhDOwA8MoQB7AgOwCbykQCcBLbAcwD4oBeWNTHfKAJQgGMB7I3FAGigBXbAGtsnAO7ZqAfijAig6AC4oAMwCGAG3gQAUHtCRYABgCMtWAmQADACQBvbIIC2AIwhEAvjcp6A9P5QwQB6MgZG0DAmAEyWcIhI9g5uJORkwD5+gcFQYRHgUSYAzPHWSY7EZORZAUGh4UA

### 💻 Code

```ts
type Test<T extends string> = T extends Record<T, unknown> ? true : false

type T01 = Test<`${number}`> // true

type T02 = Test<`${bigint}`> // false

type T03 = Test<`${string}`> // false
```

### 🙁 Actual behavior

inconsistent behavior

### 🙂 Expected behavior

-

**Comment by jcalz** [comment]
I’m struggling to understand what you’re trying to demonstrate. Surely, in general, `Test<T>` should depend on `T`, so why would it be “inconsistent” for different inputs to lead to different outputs? 

Why would one expect a template literal to be usable as a key to itself? When do you write `str[str]` and expect that to make sense? Strings have a numeric index signature but not a string index signature or a “bigint index signature” so things look reasonable to me. 

I think you should strongly consider explaining the expected/actual behavior instead of assuming it’s obvious.
