### ISSUE TITLE
is there a way to export more than one module per npm package via typings?

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#5804]
According to [typings for npm packages](https://github.com/Microsoft/TypeScript/wiki/Typings-for-npm-packages) there can be a file specified in the `"typings"` property or an `index.d.ts` which implies that there can only be a single typescript module (javascript file + declaration file) per npm package.

Is there a way to export typings for more than one module per npm package?

**Comment by falsandtru** [comment]
You can export many files in single file:

```ts
// a.d.ts
export declare var a1;
export default function a()

// b.d.ts
declare module 'b' {
  export var b1;
  export default function b()
}

// index.d.ts
export * from './a.d';
export {default} from './a.d';
import './b.d';
export * from 'b';
export {default as b} from 'b';
```

**Comment by aleksey-bykov** [comment]
interesting idea

**Comment by falsandtru** [comment]
And you can define many modules but you should not.

```ts
// node_modules/b/types.d.ts
declare module 'a' {
  export var a;
}
declare module 'b' {
  export var b;
}

// node_modules/b/index.d.ts
import './types.d';

// index.ts
import 'b';
import {a} from 'a';
```

**Comment by aleksey-bykov** [comment]
Mind me asking why shouldn't I?

**Comment by falsandtru** [comment]
Because you should not override other module typings. It is global namespace pollution.

**Comment by blakeembrey** [comment]
You can not use ambient modules for the `typings` field in `package.json` so those examples would not work. Typings in NPM packages should only ever be external module declarations which limit you to exporting a single module anyway. You should not be exporting more than one module from your NPM package, since the NPM package is itself only one module.

**Comment by aleksey-bykov** [comment]
Since when a typescript module is equal to a npm package?

**Comment by blakeembrey** [comment]
> Since when a typescript module is equal to a npm package?

When you publish it on NPM and use their module namespace options, you're publishing your code as a package under a single name that node will use to resolve. You can not have two modules inside the same NPM package, so TypeScript doesn't resolve like that either.

**Comment by aleksey-bykov** [comment]
that's not true, you can load separate JavaScript files from under a
module:

var sub = require ('npm-module-name/separate-javascript-file');

**Comment by blakeembrey** [comment]
Perfect, now I understand. I was mixing the terminology of module and package since I'm coming from the NPM ecosystem where they are used interchangeably. Only ambient modules have that ability in the same file. I thought TypeScript resolved the files using that syntax already, but I could be wrong. There's a few more limitations right now that just that in TypeScript, such as not differentiating `browser` either. I'll leave the TypeScript team to comment more though.
