### ISSUE TITLE
Intersection types does not work as generics

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#5823]
```ts
class Foo<T> {
	f<U>(): Foo<T&U> {
		return;
	}
	g(): T { // require for correct generics resolution using intersection types
		return;
	}
}

class Bar<T> {
	f<U>(): Bar<T&U> {
		return;
	}
}

var foo: Foo<string&number> = new Foo<string>(); // correct error
var bar: Bar<string&number> = new Bar<string>(); // should be error
```

**Comment by kitsonk** [comment]
I think you have the concept of generics wrong.  `string & number` is a single type.  Therefore it occupies a single generic type place holder.  A generic intersection, like you are suggesting.

Also, an intersection of `string & number` is useless.  How can a variable be a `string` and a `number` at the same time?

Functionally what are you trying to accomplish?  Because you code is very confusing...

If you are trying to merge types, you can take a look at [something like this](https://github.com/dojo/compose/blob/3e7a17e0e3b89c9f38f930f46c41bca7dec649b0/src/compose.ts#L116).

**Comment by falsandtru** [comment]
Okay, I show more real example. This is a solution for formal proof, and a simple bug of generics:

```ts
declare class A {
	private id;
}
declare class B {
	private id;
}

class Foo<T> {
	f<U>(): Foo<T&U> {
		return;
	}
	g(): T { // require for generics resolution of intersection types
		return;
	}
}
class Bar<T> {
	f<U>(): Bar<T&U> {
		return;
	}
}

var foo: Foo<A&B> = new Foo<A>(); // correct error
var bar: Bar<A&B> = new Bar<A>(); // should be error
```

**Comment by kitsonk** [comment]
Ok... you are right, the second one should be an error but isn't:

```typescript
var bar: Bar<A&B> = new Bar<A>(); // should be error
```

Still confusing what you are actually trying to accomplish though functionally, like what the real use case is.

**Comment by falsandtru** [comment]
It is not important... There are many usages because union types and intersection types has relation to the set theory. This is useful for the formal proof. e.g.

```ts
declare class Sanitized {
    private id;
}
function sanitize<T>(data: T): Sanitized&T {
	return <Sanitized&T>data; // any processing
}

class Foo<T> {
	constructor(public value: T) {
	}
    sanitize(): Foo<Sanitized&T> {
        return new Foo<Sanitized&T>(sanitize(this.value));
    }
    g(): T { // require for correct generics resolution using intersection types
        return;
    }
}

var plain: Foo<string> = new Foo('');
var sanitized: Foo<Sanitized&string> = new Foo(''); // unassignable
var sanitized: Foo<Sanitized&string> = new Foo<string>('').sanitize(); // assignable
```

Okay?

**Comment by ahejlsberg** [comment]
This isn't a bug. The problem is that class `Bar<T>` never actually references `T` itself in a *member* so all instantiations of `Bar<T>` are structurally compatible. In particular, note that use of `T` as a type argument doesn't necessarily cause any members to reference `T`. If you add a member that actually references `T` you will indeed see an error (as is the case with the `Foo<T>` class).

**Comment by aleksey-bykov** [comment]
would it be an option to add pseudo fields for the type parameters that don't have a property (a member referring to them)?

**Comment by weswigham** [comment]
A type argument which doesn't change the structure of a type doesn't affect its structural equality. If you need it to behave as though it does, that's on you to add the dummy brand member. Its not "counterintuitive" - its consistent with the rest if the type system.

**Comment by falsandtru** [comment]
@ahejlsberg thank you for your explain. I mostly understood that. There is one thing that bothers me. Is that a trade off for the performance or the optimization?

**Comment by aleksey-bykov** [comment]
@weswigham, I speak for myself and @falsandtru who, as we see, happen to tip over it too. My code is full of dummy brand members ever since I was told I have to use them in order to make the type system to consider the type parameters that otherwise ignored (although present because written on purpose). Hence the question, if the type parameter is already declared in the type why we default to ignoring it, what's the use case of it? Doesn't it look more common sense to take it into account without having to employ dummy artifacts?

**Comment by aleksey-bykov** [comment]
the very idea of brand members is sucked out of the thumb, there is no other language out there that requires dummy properties to make their type system work

**Comment by falsandtru** [comment]
Probably, this is incorrect behavior as a theory but this is not a bug as a type resolution. This is a selection of the design. Thanks.

**Comment by aleksey-bykov** [comment]
so it was proclaimed by design that the "structural" can only come from the members but not from the type arguments, if we take it as a definition of what structural is then yes, structural has nothing to do with the unused type parameters

but if we consider the type parameters (declared with as much consciousnesses as any other member of a type) as a different part of being of "structural" that sits next to the explicit members then suddenly the structural equality as it is doesn't look complete

**Comment by falsandtru** [comment]
I know, it is not a better behavior. It is violation of the principle of least astonishment. But all things are the balance and the demand.

**Comment by aleksey-bykov** [comment]
If ignoring an unused type parameter had **one single meaningful use case**, then yes, we would have been talking about trade-offs.

**here is no such cases.**

What we see instead is that **always** when there is a type parameter there is **either** a real member **or** a dummy surrogate. So there are trade-offs between one situation or another, there is one single 100% same situation. All type parameters need to be bound to members in order to be considered for type equality, no matter whether those members are real or artificially added. If so why won't we automate the need to add artificial members that don't do anything but support the type system that is incapable to see them otherwise?
