### ISSUE TITLE
Type guard not working as expected in function overloading with union types

### ISSUE THREAD

**Issue by remojansen** [Microsoft/TypeScript#5826]
```
class Square {
	length : number; 
	constructor(length : number) {
		this.length = length;
	}
}

class Rectangle {
	length : number;
	width : number;
	constructor(length : number, width : number) {
		this.length = length;
		this.width = width;
	}
}

class Triangle {
	base : number
	height : number;
	constructor(base : number, height : number) {
		this.base = base;
		this.height = height;
	}
}
```
The following works as expected:
```
namespace function_overloading_with_any {
	
	function calculateArea(shape : Square) : number;    // overloaded signature
	function calculateArea(shape : Rectangle) : number; // overloaded signature
	function calculateArea(shape : Triangle) : number;  // overloaded signature
	function calculateArea(shape : any) : number        // implementation signature
	{
		if(shape instanceof Square) {
			return shape.length * shape.length;
		}
		else if(shape instanceof Rectangle) {
			return shape.length * shape.width;
		}
		else if(shape instanceof Triangle) {
			return (shape.base * shape.height) / 2;
		}
	}
	

	var square = new Square(5); 
	var rectangle = new Rectangle(3, 5); 
	var triangle = new Triangle(3, 5);
	
	calculateArea(square);  
	calculateArea(rectangle); 
	calculateArea(triangle); 
}
```
However, when I use an union type instead of `any`in the implementation signature:

```
namespace chapter02.function_overloading.with_union {
	
	function calculateArea(shape : Square) : number;
	function calculateArea(shape : Rectangle) : number;
	function calculateArea(shape : Triangle) : number;
	function calculateArea(shape : (Square | Rectangle | Triangle)) : number {
		if(shape instanceof Square) {
			return shape.length * shape.length;
		}
		else if(shape instanceof Rectangle) {
			return shape.length * shape.width; // Error!
		}
		else if(shape instanceof Triangle) {
			return (shape.base * shape.height) / 2;
		}
	}
	
	var square = new Square(5); 
	var rectangle = new Rectangle(3, 5); 
	var triangle = new Triangle(3, 5);	
		
	calculateArea(square); 
	calculateArea(rectangle); 
	calculateArea(triangle);
}
```

I get a compilation error:

```
error TS2339: Property 'length' does not exist on type 'Triangle'.
error TS2339: Property 'width' does not exist on type 'Triangle'.
```

Looks like the type guard is not working as expected. I can use an `if` instead of `if else` to fix the error:

```
	function calculateArea(shape : Square) : number;
	function calculateArea(shape : Rectangle) : number;
	function calculateArea(shape : Triangle) : number;
	function calculateArea(shape : (Square | Rectangle | Triangle)) : number {
		if(shape instanceof Square) {
			return shape.length * shape.length;
		}
		if(shape instanceof Rectangle) {
			return shape.length * shape.width; // OK!
		}
		if(shape instanceof Triangle) {
			return (shape.base * shape.height) / 2;
		}
	}
``` 

I'm using TypeScript `1.8.0-dev.20151129` with gulp-typescript:

```
gulp.task('build', ['lint'], function() {
  
    var tsProject = ts.createProject('tsconfig.json', {
        typescript: require('typescript')
    });
    
    var compile = ts(tsProject);

    return gulp.src("src/**/**.ts")
                .pipe(compile)
                .js.pipe(gulp.dest("src/"));
});
```

And the following `tsconfig.json` compilation:

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "umd",
    "moduleResolution": "node",
    "isolatedModules": false,
    "jsx": "react",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "declaration": false,
    "noImplicitAny": false,
    "removeComments": true,
    "noLib": false,
    "preserveConstEnums": true,
    "suppressImplicitAnyIndexErrors": true
  }
}
```

The source code that I used to discover this issue can be found [here](https://github.com/remojansen/TsCookbook/blob/master/chapter_02/src/05_function_overloading.ts#L67).

Thanks!

**Comment by lbguilherme** [comment]
error TS2339: Property 'length' does not exist on type 'Triangle'.

Just a note: 'length' indeed doesn't exist for Triangle. It should be 'base', no?

**Comment by DanielRosenwasser** [comment]
I think this is happening because we try to eliminate all types in the union that are assignable to `Square` in the first `else`. That's very incorrect because `Rectangle` is assignable to `Square`, but it has nothing to do with its instance identity.

**Comment by weswigham** [comment]
I think this may be a regression - [in the playground, there's no errors for this example](http://www.typescriptlang.org/Playground#src=class%20Square%20%7B%0D%0A%20%20%20%20constructor(public%20length%3A%20number)%20%7B%7D%0D%0A%7D%0D%0A%0D%0Aclass%20Rectangle%20%7B%0D%0A%20%20%20%20constructor(public%20length%3A%20number%2C%20public%20width%3A%20number)%20%7B%7D%0D%0A%7D%0D%0A%0D%0Aclass%20Triangle%20%7B%0D%0A%20%20%20%20constructor(public%20base%3A%20number%2C%20public%20height%3A%20number)%20%7B%7D%0D%0A%7D%0D%0A%0D%0Afunction%20calculateArea(shape%20%3A%20(Square%20%7C%20Rectangle%20%7C%20Triangle))%20%3A%20number%20%7B%0D%0A%09if(shape%20instanceof%20Square)%20%7B%0D%0A%09%09return%20shape.length%20*%20shape.length%3B%0D%0A%09%7D%0D%0A%09else%20if(shape%20instanceof%20Rectangle)%20%7B%0D%0A%09%09return%20shape.length%20*%20shape.width%3B%0D%0A%09%7D%0D%0A%09else%20if(shape%20instanceof%20Triangle)%20%7B%0D%0A%09%09return%20(shape.base%20*%20shape.height)%20%2F%202%3B%0D%0A%09%7D%0D%0A%7D).

**Comment by weswigham** [comment]
I think I've figured out why this is a regression - when I swapped narrowing to work from outside in rather than inside out (lol) in #5442 so empty sets could correctly propagate down and compound/nested type guards would work as expected, at the same time I made it so behaviors like this became visible. We had always been narrowing with the logic saying this would happen, but since we'd narrow by the `if` within the `else`, then the `else`, we'd narrow `Square | Rectangle | Triangle` to `Rectangle` and then just return that subtype again at the higher level (since `Rectangle` wouldn't narrow any further by old logic the expression `!(instanceof Square)` - it would have been an intervening empty set which resulted in the type at that step just getting reused (`Rectangle`)).

So fixing a set of other bugs exposed this one. :D

While the new behavior is a change, the behavior described in the post, as Daniel says, is _by design_. Since `Rectangle` is a `Square`, `instanceof Square` removes `Rectangle` from the union, as `instanceof` type guards act the same way as user-defined type guards - structurally.

This is actually problematic - `instanceof` at runtime is highly nominal, it will actually only catch instances of the RHS constructor or its inheritors - structural similarity doesn't play into it, and because of our ignorance of this, we do inaccurate narrowing. We could add a nominal relationship to use with `instanceof` fairly easily, but it is fairly against the philosophy of TS - we're actively trying to remove the only place where we've accidentally introduced nominality.

So @ahejlsberg, this behavior stays unless we want to add a nominal relationship to use with `instanceof`.

**Comment by weswigham** [comment]
@remojansen as a workaround while we figure this out, you can either brand your classes with dummy members (`_square: void`, `_rectangle: void`, `_triangle: void`) so they're not structurally assignable or reorder your `if`/`else if` chains so that the more specific types (eg, `Rectangle`) are first.

**Comment by remojansen** [comment]
@weswigham :+1: thanks for that
