### ISSUE TITLE
generic parameter is not narrowed down correctly in extends clause when using keyof operator

### ISSUE THREAD

**Issue by Eliav2** [microsoft/TypeScript#58273]
### 🔎 Search Terms

generic 
parameter 
narrowed
down 
extends clause

### 🕗 Version & Regression Information

v5.4.5

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAKuEBMBKB7ArsCAnAPABSggA9MA7BAZyguCwEtSBzAPigF4oBDUkAKF9CRYEGjiSsOSQiQjkqAb15QoAbQDWEEAC5qtBowC6O7iADcvAL5KoAfiiLlj1QQZQNIFADMoSI7HjI6Ji4eMzWylbKOqQQAG7YpkA

### 💻 Code

```ts
type TypedRouter<P extends string> = any

type Test<R> = R extends {
  [key: string]: any;
}
  ? {
      [P in keyof R]: TypedRouter<P>
//                                                 ^ 'string | number | symbol' is not assignable to type 'string'
    }
  : never;
```

### 🙁 Actual behavior

if `R extends {[key: string]: ...}` then `keyof R` is `string`, so why `P in keyof R` is `'string | number | symbol'` and not `string`?

### 🙂 Expected behavior

.

**Comment by MartinJohns** [comment]
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#support-number-and-symbol-named-properties-with-keyof-and-mapped-types

**Comment by fatcerberus** [comment]
> if `R extends {[key: string]: ...}` then `keyof R` is `string`, so why `P in keyof R` is `string | number | symbol` and not `string`?

`{ a: string, b: string }` extends `{ a: string }`, but its `keyof` is `"a" | "b"`.  The same rationale applies here.

**Comment by jcalz** [comment]
Yes, this behavior is by design. `number` keys are already subsumed by `string` index signatures, and `symbol` keys are not *prohibited* by `string` index signatures because types in TS are not sealed. There's no bug in this code. 

The statement "if `R` extends `{[key: string]: ...}` then `keyof R` is `string`" is demonstrably false:

```ts
type Ex<R extends { [key: string]: number }> = void;

type A = { a: 1, 2: 3, [Symbol.toPrimitive]: "abc" };
type B = Ex<A>; // <-- this is fine
type C = {} & keyof A; 
//   ^? type C = typeof Symbol.toPrimitive | "a" | 2
```
[Playground link](https://www.typescriptlang.org/play?#code/FDAuE8AcFMAIFEAeAeASrajTQHYBMBnWAb1gG0BracALlgNACcBLHAcwF06cBXAWwBG0RrAC+APlgBeWADcA9szwBuEBBiwAgtJKwAhnQCMAGlgAmOgGZTZAMrhB8gDYA6UPIAKLPs1DNZ0FywAER6AgDGwWKq6nAAQjpIyJriyrAA9OmwyAC0ObCgABbMRCWwAGas0GBQcADCOsSisABksFTg8uVaacCZsAMAegD8IEA)

**Comment by Eliav2** [comment]
thank you all. I finally got it.
