### ISSUE TITLE
Is assignment not allowed here?

### ISSUE THREAD

**Issue by masterYi2333** [microsoft/TypeScript#58298]
### 🔎 Search Terms

Why is an error reported here??

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAggdiAShAxgewE4BMoF4rLrYA8AhggDRTkgB8AUPQGYCucKwAlmnFACoQAzsGJ8oEAB7AIcLINgJCmHPnhJUy2gAoAbqQA2LCAC5+ASigBvelCihIUAKLO8-cVJlyF6ojgD8dhhGUKZMBoIQjLbocMLiECZOLvhh+hHU8qnpAPTZUH4FNlAxcQkQAIymzo6uwEHQpPJ1wbn5hdE8pQkATKbN0Pj9UXbg0NXltfVFJcDxEADMVc4Tg-UZgUbTnWj6EAB0+mgA5lplZluxO-uHJ2Xl5x2XuwfHpz3n9AC+QA

### 💻 Code

```ts
type AnyRecord = Record<any, any>

function Test<T extends AnyRecord = AnyRecord>(value: T) {
  type EEE = T extends AnyRecord ? true : false

  const eee: EEE = false as false // ???
  const eee1: EEE = true as true // ???
  const eee2: true = true

  type EEE1 = true
  const eee3: EEE1 = true as true
  console.log(eee)
  console.log(eee1)
  console.log(eee2)

}
```

### 🙁 Actual behavior

Is this way of writing wrong? Why does assigning true and false not work?

**Comment by whzx5byb** [comment]
You may expect `EEE` to be resolved to `true`, but it is unresolved. See https://github.com/microsoft/TypeScript/issues/56045#issuecomment-1756274339

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
