### ISSUE TITLE
Undocumented breaking change in 5.5.0-beta for reference directives

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript#58324]
### 🔎 Search Terms

5.5.0-beta

### 🕗 Version & Regression Information

- This changed between versions 5.4 and 5.5

### ⏯ Playground Link

https://github.com/Jack-Works/reproduce

### 💻 Code

Clone the repo

```sh
git clone https://github.com/Jack-Works/reproduce/ --filter=blob:none
cd reproduce/typescript-5.5-dts
pnpm install

pnpm run old
pnpm run new
```

### 🙁 Actual behavior

Global augmentation no longer works in 5.5.0-beta across different projects. (`pnpm run new`)

### 🙂 Expected behavior

Global augmentation works in 5.4 across different projects. (`pnpm run old`)

### Additional information about the issue

Global augmentation across different projects is an important ability. Here are some examples:

- You have a components project that augments the global JSX type, and you access those elements from another project
- Theming a UI library

**Comment by robpalme** [comment]
Hello @Jack-Works, thanks for highlighting this. [Your repro](https://github.com/Jack-Works/reproduce/blob/main/typescript-5.5-dts/a/index.ts#L1) is using reference directives in the project's public-facing entrypoint module.

```ts
/// <reference path="./env.d.ts" />
```

It's true there is an intentional breaking change introduced by @jakebailey in the PR for [Do not preserve references in declaration emit, unless preserve=true](https://github.com/microsoft/TypeScript/pull/57681). And this is not yet documented in t[he TS 5.5 Beta announcement.](https://devblogs.microsoft.com/typescript/announcing-typescript-5-5-beta/#notable-behavioral-changes) so that post should be updated.

The intended workaround for cases where you want the reference directive included in the published declaration file is to add `preserve=true`.

```ts
/// <reference path="./env.d.ts" preserve=true/>
```

**Comment by jakebailey** [comment]
Sorry about that; it definitely was meant to be there in the blog! We'll get it updated.

**Comment by jakebailey** [comment]
Blog post has been updated: https://devblogs.microsoft.com/typescript/announcing-typescript-5-5-beta/#simplified-reference-directive-declaration-emit
