### ISSUE TITLE
Type guards don't work for interfaces with only optional properties

### ISSUE THREAD

**Issue by domoritz** [Microsoft/TypeScript#5842]
For some reason type guards to not work if an interface has only optional properties. 

```ts
interface A {
  foo : number;
}

function isA(object: any): object is A {
  return true;
}

let a: A | boolean;

if (isA(a)) {
  a.foo;   // compiles
}



interface B {
  foo? : number;
}

function isB(object: any): object is B {
  return true;
}

let b: B | boolean;

if (isB(b)) {
  b.foo;  // does not compile because type inference says its `B | boolean`
}
```

**Comment by mhegazy** [comment]
For a type guard, it will look through all the union type constituents (`B` and `boolean` in the example), and will filter out types that are not assignable to the target type. since `B` has only optional properties, booelan is assignable to, and it is not filtered out from the union. looks like a good candidate for #3842. 

a work around is to tag type B, see https://github.com/Microsoft/TypeScript/issues/4895
