### ISSUE TITLE
Additions result wrong

### ISSUE THREAD

**Issue by susanne99** [microsoft/TypeScript#58466]
### 🔎 Search Terms

typescript add function

### 🕗 Version & Regression Information

typescript version 5.4.5

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/DYUwLgBAzgrgthAXBAdvARiAThAvBATgDoCCBuAKAtgQGp8BGABiaIYCZKaJ6JnWOlCgGMA9iiijQRYKIDmAChoBKIA

### 💻 Code

```ts
let sum : number = 9.99;

sum += 100.12;
sum += 100.12;

console.log(sum)
```

### 🙁 Actual behavior

At first I thought it was related to Vue JS, but the error also occurs in TypeScriptPlayground. why is the result not 210.23 but 210.23000000000002

### 🙂 Expected behavior

correct result: 210.23

**Comment by MartinJohns** [comment]
This is completely unrelated to TypeScript, it's just the way JavaScript works.

See also this StackOverflow question: [How can I deal with floating point number precision in JavaScript?](https://stackoverflow.com/questions/1458633/how-can-i-deal-with-floating-point-number-precision-in-javascript)

**Comment by susanne99** [comment]
ok, than please tell me the correct addition routine for typescript !

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!

**Comment by bhavukish** [comment]
let sum : number = 9.99;

sum += 100.12;
sum += 100.12;

console.log(sum.toFixed(2));

Try to do fixed decimal length.
