### ISSUE TITLE
[ERROR] 15:13:55 Error: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by yizhishiliu** [microsoft/TypeScript#58530]
### 🔎 Search Terms

Error: Cannot set headers after they are sent to the client

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### 💻 Code

```ts
// Your code here
```

### 🙁 Actual behavior

Using typescript to write the backend interface, this error message appears after a normal response to a request, causing the entire program to end abnormally, unable to respond to subsequent requests.
[ERROR] 15:13:55 Error: Cannot set headers after they are sent to the client

### 🙂 Expected behavior

The request is responded to normally and does not affect the normal execution of other requests.

**Comment by Mingdaj** [comment]
Adding "@Res() res: Response" to the controller's method parameter successfully solved the response problem.

As:

`import { Controller, Get, Res } from '@nestjs/common';
import { Response } from 'express';

@Controller('test')
export class CatsController {
  @Get()
  testRes(@Res() res: Response) {
    res.status(200).send('OK');
  }
}`

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
