### ISSUE TITLE
Why don't declaration files specify a compiler version?

### ISSUE THREAD

**Issue by Roam-Cooper** [Microsoft/TypeScript#5869]
It would be very useful if declaration files specified a compatible compiler version as I am constantly having trouble with declaration files written for a newer or older version of the compiler.

**Comment by DanielRosenwasser** [comment]
Curious, with TypeScript 1.7, what sorts of issues are you running into regarding definitions written for older versions of the compiler?

**Comment by mhegazy** [comment]
the problem is not the version of the compiler that generated the file. the problem is in the features that the file contains. just cause you created this file on 1.7, does not mean you can not compile it on 1.1.

**Comment by RyanCavanaugh** [comment]
I don't see what the proposal is or what we could even do with that information if it existed. A file generated in 1.5 might work in 1.6, a file generated in 1.6 might work in 1.5. And a hand-written file could do anything. The real problem comes when there's new syntax... but the file won't even parse at that point, which is going to be a bigger problem than anything else. The best we could do is a vague error like "Declaration file came from a newer version of the compiler so *maybe* the problem is that there's new unsupported type system syntax?" which isn't always going to be correct anyway.

**Comment by myitcv** [comment]
Related discussion in the context of `typings` https://github.com/typings/typings/issues/49
