### ISSUE TITLE
TypeScript Dount

### ISSUE THREAD

**Issue by codewithunknown** [microsoft/TypeScript#58691]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

Hello! I'm encountering an issue with a React component that accepts two props. Here's how it's set up:

```tsx
type Props<T> = {
  value: T,
  onChange: (date: T) => void
}

const DateRangeInput: React.FC<Props<DateRange | Date | undefined>> = ({
  // Component code here
})

```
And here's an example usage of the component:
```tsx
import { DateRange } from "../Common/DateRangeInputV2";
const Loading = lazy(() => import("../Common/Loading"));

export type DateRange = {
  start: Date | undefined;
  end: Date | undefined;
};

export const InsuranceDetails = () => {
  const [date, setDate] = useState<DateRange>({
    start: undefined,
    end: undefined,
  });

  const handleDateChange = (date: DateRange) => {
    console.log("date in insurance", date);
    setDate(date);
  };

  return (
    <div>
      <DateRangeInput
        name="range_date"
        value={date}
        onChange={handleDateChange}
      />
    </div>
  );
};
```
The error I'm encountering is:

```txt
Type '(date: DateRange) => void' is not assignable to type '(date: DateRange | Date | undefined) => void'.
  Types of parameters 'date' and 'date' are incompatible.
    Type 'DateRange | Date | undefined' is not assignable to type 'DateRange'.
      Type 'undefined' is not assignable to type 'DateRange'.ts(2322)
DateRangeInputVivek.tsx(41, 3): The expected type comes from property 'onChange' which is declared here on type 'IntrinsicAttributes & Props<DateRange | Date | undefined>'
(property) onChange: (date: DateRange | Date | undefined) => void

```

is there any way to handle this, because the type of value should reflect onChange . Can anyone help me with this?

ps : without using any

**Comment by MartinJohns** [comment]
The error message is clear. The component calls `onChange` passing an argument typed `DateRange | Date | undefined`, but your handler can only deal with `DateRange`.

This issue tracker is for bugs and feature requests for TypeScript. It's not suited as a general support forum.

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
