### ISSUE TITLE
Allow logical XOR using `^` operator

### ISSUE THREAD

**Issue by drewnoakes** [microsoft/TypeScript#587]
Consider:

```
var a: boolean = ...;
var b: boolean = ...;

if (a ^ b) {
  // ...
}
```

Currently attempting to use the `^` operator on `boolean` values fails with:

> error TS2113: The left-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

The `|` and `&` bitwise operators have logical counterparts, `||` and `&&`. No such `^^` is available.

JavaScript allows bitwise XOR to apply to `boolean` values.

Currently workarounds are:
- casting: `<number><any>a ^ <number><any>b`
- using a negated equality test: `a !== b`

The XOR operator is clearer than both of these.

**Comment by saideldah** [comment]
@RyanCavanaugh  
"Discussed in the design meeting and declined. Relevant points:

!== is equivalent and not necessarily less clear (plus it returns a value of the appropriate type)
If we supported ^ for boolean, we'd want to support & and | for consistency, but catching && vs & errors is important"

I think the XOR operator is very important and can reduce some code, however why you can't make ^^ instead of single ^

**Comment by RyanCavanaugh** [comment]
@saideldah making new binary operators is TC39's job, not ours

**Comment by saideldah** [comment]
@RyanCavanaugh 
Ok, thanks for the clarification.
what you are trying to say that you can't add something that does not already exist in Javascript.
is that right?

**Comment by RyanCavanaugh** [comment]
We don't want to add new expression-level syntax with runtime semantics.
