### ISSUE TITLE
Incorrect type inferrence that sub-class does not extend super-class with generics

### ISSUE THREAD

**Issue by mtripg6666tdr** [microsoft/TypeScript#58736]
### 🔎 Search Terms

generics, extends, keyof, subclass, "generic constraints", "generic inheritance"

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because I don't think this has ever worked.

I tested this v5.4.5 and v5.5.0-dev.20240602

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.5.0-dev.20240602#code/LAKAlgdgLgpgTgMwIYGMYAIBiB7b6Deo66CuAXOgM5RyQDmA3KAL6igoA2Sll6AQtxgAeACroYAD1gQAJrxzYAfASIlcQgKripMWbwDWMAJ7YE6EYoAUhoxQ0BKAulYgX7Lj3QAReGABuMDLa0nL8gkIKyoQgxNgBcLQyGKTYmsG6oTamWLhWNnaO+M4sbCBQRgAOGACSlADKAK4ARgDCHpQA8ggClMIW6AC85ul6Yb1CSBBGygD86DQNGBTIHL1MIKDlVd6+ATK1ja3tXT0YQwfNbdyd3eE+tHuKDOgA9C8kSKswpUA

### 💻 Code

```ts

interface Foo {
  foo: string;
}

class Base<T extends Foo> {
  foo<U extends keyof T>(key: U) { }
}

class Derived extends Base<Foo> {
  override foo<U extends keyof Foo>(key: U) { }
}

type IsSubClassOfBase<T> = T extends Base<any> ? true : false;

type DerivedIsSubClassOfBase = IsSubClassOfBase<Derived>; // false

```

### 🙁 Actual behavior

the type `DerivedIsSubClassOfBase` is `false`

### 🙂 Expected behavior

the type `DerivedIsSubClassOfBase` is `true`

**Comment by jcalz** [comment]
"I was unable to test this on prior versions because I don't think this has ever worked." 😕 You can test this exact code on the TS playground all the way back to TS4.3 [link](https://www.typescriptlang.org/play/?ts=4.3.5#code/LAKAlgdgLgpgTgMwIYGMYAIBiB7b6Deo66CuAXOgM5RyQDmA3KAL6igoA2Sll6AQtxgAeACroYAD1gQAJrxzYAfASIlcQgKripMWbwDWMAJ7YE6EYoAUhoxQ0BKAulYgX7Lj3QAReGABuMDLa0nL8gkIKyoQgxNgBcLQyGKTYmsG6oTamWLhWNnaO+M4sbCBQRgAOGACSlADKAK4ARgDCHpQA8ggClMIW6AC85ul6Yb1CSBBGygD86DQNGBTIHL1MIKDlVd6+ATK1ja3tXT0YQwfNbdyd3eE+tHuKDOgA9C8kSKswpUA) and even back to TS3.3 [link](https://www.typescriptlang.org/play/?ts=3.3.3#code/LAKAlgdgLgpgTgMwIYGMYAIBiB7b6Deo66CuAXOgM5RyQDmA3KAL6igoA2Sll6AQtxgAeACroYAD1gQAJrxzYAfASIlcQgKripMWbwDWMAJ7YE6EYoAUhoxQ0BKAulYgX7Lj3QAReGABuMDLa0nL8gkIKyoQgxKTYmsG6oTamWLhWNnaO+M4sbCBQRgAOGACSlADKAK4ARgDCHpQA8ggClMIW6AC85ol6Ye1CSBBGygD86DRVGBTIHO1MIKCFJd6+ATLl1fWNLW0YPVu1DdzNreE+tBuKDOgA9HckSPMw+UA) if you get rid of `override` (which doesn't change anything anyway).

This doesn't look like a TS bug. You can easily have a generic class where two different instantiations of the generic type argument are not compatible.  Certainly you don't expect `Base<X>` and `Base<Y>` to always be compatible with each other. You might think that `Base<any>` should be compatible with everything, and often just using `any` will have that effect... but  you've got `keyof T` in there which, for `any`, resolves to `string | number | symbol` so it's quite easy to make something incompatible with it.  It's very similar to this:

```ts
interface X<T> {
  a: (k: keyof T) => void;
}
interface Y extends X<{ b: 0 }> {
  a: (k: "b") => void;
}
declare const y: Y;
const xAny: X<any> = y; // error!
/* Type 'Y' is not assignable to type 'X<any>'.
  Types of property 'a' are incompatible.
    Type '(k: "b") => void' is not assignable to type '(k: string | number | symbol) => void'.
      Types of parameters 'k' and 'k' are incompatible.
        Type 'string | number | symbol' is not assignable to type '"b"'.
          Type 'string' is not assignable to type '"b"'.(2322) */
```

TypeScript has plenty of inconsistent type checking behaviors, but most of them are there for a reason, and I don't see this code hitting anything that unreasonable.  Indeed I'd expect there to be a error because the only possible thing you could do inside your `foo` override is treat `key` as `"foo"`, but a `Base<any>` can be given any keylike input at all:

```ts
class Derived extends Base<Foo> {
  override foo<U extends keyof Foo>(key: U) {
    const x = {foo: "abc"}[key]; // this is not an error, after all, U extends "foo"
    console.log(x.toUpperCase());  // this is not an error, since `x` is a `string`, right?
  }
}
const b: Base<any> = new Derived(); // error, but what if it wasn't?
b.foo("xyz"); // no compiler error, but 💥 at runtime: x is undefined!
```

So if you think this is a bug, you probably have to explain in more detail where it is. If I were trying to write your `IsSubClassOfBase` type, after running into the problem you're having here, I might consider changing your test to something like

```ts
type IsSubClassOfBase<T> = T extends Base<infer _> ? true : false;
type DerivedIsSubClassOfBase = IsSubClassOfBase<Derived>; // true
```

using `infer _` instead of `any`.

[Playground link to code](https://www.typescriptlang.org/play/?ts=5.5.0-dev.20240602#code/JYOwLgpgTgZghgYwgAgBoB4AqA+ZBvAWAChlk4AuZACgGtKaIBPAexmUwEpkBeXAN2bAAJgG5iAX2KhIsRCgCa+YqQrU6yAEQAjDV17IBwsUUlEhEBABs4UFAmYgAzmGSNK84wHpPye05cAHgCCIG5o6HChuNyuIsjeyNBQzFAAhMSeAFTsjAAOKADk8gXIwI7IIMwucI6OwADmIHBalihgzMhgeYUYkYzYBQB0yjn55azIucn5UF3IBXAlNiig9gC2uXBgwC0QwySko4W0lNq6PPyCQiVlFVVktQ1Nu50dXfnzJ8jOUKD1yAAfCoAVzWWmggO+jDBzEsekuwiGI0OR3GbE2UDgawgMnKBRoSxAQnmBLItlKIHWm22u32KJRmG68x+f0hIFB4KgkMc0K0sJu5Uq1UejWarVenSZBTOSIO9MOjI+BRZIHqAruwrqope7UlSplgyoACYAMxGo1cTKeYg2oi2qTgaDwJDIABizA6hAOMA9lBV9WMpmIVhq5QAQjUIFhEgFIETyu7mLgvaQfcx0ABVGNxoTlBgsNg4WhMSgZrh4ZCmINEEO1ZAAEWgwD4EGJEFjEHjyAjjijieTI2YLagv3MyDTmezndzyHzE37xbCZaUct8DmcyACPHwadOzQQGnEAG18wBdYwovyOWF7SzMepUAKDdoZ3IzADCkaoHA4cUOIyrW0rxcLRKB7KM+miCoIAAdwbJsWyEb9jC0QY0yoDQAkYAAvXQ4gSJIUgAGk3UpymBIkIBgUBW3SO16PeFAAElHAAZWBLR32sWoAHkYHArAoMwKcuwE0AYAhAB9XAAH5OigYEUEoeBLF7YxiEY+DfkQlj2M47jHD48Dt10jiuNDIzI3QRttNbbB8J8MAFIgIA)

**Comment by mtripg6666tdr** [comment]
Thank you for your detailed explanation. ❤️
Now I completely understand what it does.

Also, when I create a new issue, I will test it on the all versions which are available in the playground. Thanks at all ☺️

**Comment by fatcerberus** [comment]
Interesting, `infer` acts like an existential there.
