### ISSUE TITLE
TS 5.5 type guards overly strict in some cases

### ISSUE THREAD

**Issue by benasher44** [microsoft/TypeScript#58959]
### 🔎 Search Terms

- predicate
- guard
- type guard

### 🕗 Version & Regression Information

- This changed between versions 5.4.x and 5.5

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/MYGwhgzhAEDKAOBTYBLMICiAnLB7L0iAHgC6IB2AJjNngQN4C+AUMwGYCu5wJKu50FBATI0mHPgAUiCVgBc0WvgCU0es2jQsiEhywCZdQeQgkw3RLjZwkqdEqwBuZi3ZcefAWVOTV6zcD8poSy0AC80OSIAO6Ksr7OmijWkkIiduJ00rLKfhqaWjp65InQLAFBuCCIAHQguADm2XQ1ALaIUGANiMrOLEA

### 💻 Code

```ts
class SpecialError extends Error {}

function isSpecialError(error: Error) {
  return error instanceof SpecialError;
}

function test() {
  const error = new Error();
  if (isSpecialError(error)) {
    return;
  }
  console.log(error.message);
}
```

### 🙁 Actual behavior

Error: "Property 'message' does not exist on type 'never'."

Even if `error` isn't `SpecialError`, it's still of type `Error`, which means it has a `message` property.

### 🙂 Expected behavior

This should compile. The error not being a SpecialError does not mean the error isn't still of type Error, which has a message property.

### Additional information about the issue

In TS 5.4, this was allowed, but it's broken as of 5.5. My initial thought was that this had something to do with automatic type predicates, but adding an explicit type guard to the function doesn't help.

**Comment by benasher44** [comment]
Interestingly, someone on my team discovered that adding a random getter to `SpecialError` works as a workaround:

```
class SpecialError extends Error {
  get blah() {
    return "blah";
  }
}
```

With that in place, the error goes away 🤔

**Comment by MartinJohns** [comment]
> Interestingly, someone on my team discovered that adding a random getter to `SpecialError` works as a workaround:

That's because the types are structurally the same without an additional property.

This really didn't change, it was the same behavior in earlier TypeScript versions. Just in earlier versions your `isSpecialError` function is not inferred to be a type guard, it's just a function returning a `boolean`, while in 5.5 [it now is inferred as a type guard](https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/#inferred-type-predicates). When you add a type annotation you get the same behavior in 5.4: `function isSpecialError(error: Error): error is SpecialError`

This works as intended. See also: https://github.com/microsoft/TypeScript/wiki/FAQ#what-is-structural-typing

**Comment by benasher44** [comment]
Ah! I see. The fact that it's a different class doesn't matter. Because the types are structurally the same, the types may as well be the same, in the eyes of TypeScript. Makes sense! Closing
