### ISSUE TITLE
Typescript does not explicitly pass undefined, which breaks intelliSense [5.5.2]

### ISSUE THREAD

**Issue by MrOxMasTer** [microsoft/TypeScript#58976]
### 🔎 Search Terms

Typescript does not explicitly pass undefined, which breaks intelliSense

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "Typescript does not explicitly pass undefined, which breaks intelliSense" 

### ⏯ Playground Link

https://codesandbox.io/p/devbox/test-typescript-q89n2h

### 💻 Code

```ts
import Link from "next/link";
import { ComponentProps } from "react";

type HTMLButtonProps = ComponentProps<"button"> & {
  href?: undefined;
};

type HTMLLinkProps = ComponentProps<typeof Link>;

type buttonAndLink = HTMLButtonProps | HTMLLinkProps;
type actionProps = buttonAndLink;

export const Action = ({
  //  intent, size,
  ...props
}: actionProps) => {
  if (typeof props.href !== "undefined") {
    const { className, ...rest } = props;

    return (
      <Link
        // className={cn(actionVariants({ intent, size, className }))}
        // {...rest}
        {...rest}
      />
    );
  }

  const { className, ...rest } = props;

  return (
    <button
      // className={cn(actionVariants({ intent, size, className }))}
      {...rest}
    />
  );
};
```

### 🙁 Actual behavior

Without explicitly specifying href={undefined}, conditional types do not work

### 🙂 Expected behavior

Instead of the typical: "button" | "submit" | "reset" | undefined
I get the type: string | undefined

### Additional information about the issue

Let's move on. Why do I lose button typing if I don't have an href?
![image](https://github.com/microsoft/TypeScript/assets/59291123/98e8da45-a6dd-41ea-8b6b-52f3910c873c)

For some reason, button types are shown here only if undefined is explicitly specified
![image](https://github.com/microsoft/TypeScript/assets/59291123/0042c7bc-a850-48d1-a000-340ed5568bd7)
It may then open up a new issue for this problem that typescript does not implicitly define undefined (props that do not pass)

It determines if there is some kind of internal typing, but it is not displayed when opening intelliSense:
![image](https://github.com/microsoft/TypeScript/assets/59291123/f89b3b72-af90-419e-9ae4-a0f96081ddb7)

**Comment by jcalz** [comment]
If you're trying to report a bug in the TypeScript language, you should make an effort to reproduce it with a small self-contained example, one that fits in a single file and does not need to pull in type definitions from other libraries like react or next.  Codesandbox is not the TS playground. The vast majority of bugs can be demonstrated in just a few lines of code.

If you're just having trouble with *using* TypeScript along with these other technologies, you should consider closing this and opening a question of Stack Overflow or in the TypeScript discord channel.  Then, assuming you follow their guidelines and someone responds, if it turns out that the problem really is a bug in TypeScript you might be directed back here with a truly minimal example, or someone might point to an existing bug (like maybe #38849 or #50139) so you can track the progress (or lack thereof) there.

Side note: you mention "conditional types" but there are no [conditional types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html) here. You presumably mean [union types](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#union-types) instead. Your search terms just look like your title, indicating maybe you didn't really search first? If you [search for "react union intellisense"](https://github.com/search?q=repo%3Amicrosoft%2FTypeScript+react+union+intellisense+&type=issues), do any of the results look like your problem?

**Comment by RyanCavanaugh** [comment]
I'm not really seeing a bug demonstrated here

**Comment by MrOxMasTer** [comment]
> I'm not really seeing a bug demonstrated here

That is, logically, I always need to explicitly specify undefined for each props so that I can display types in intelliSense under this condition:
```ts
if (typeof props.href !== "undefined")
```
After all, undefined is always passed there by default, if there is no defined props. The question is, why?

**Comment by MrOxMasTer** [comment]
it would be normal if it simply did not define and, for example, with the value "a", it would not give an error. So why, if it defines the necessary types, not output them?

**Comment by MrOxMasTer** [comment]
By the way, here's another moment from issue #38849. I don't explicitly specify href and the types work for me, but they don't work in jsx
![image](https://github.com/microsoft/TypeScript/assets/59291123/f9bfec20-6896-476c-9efe-63c6e4579a30)

**Comment by MrOxMasTer** [comment]
> I'm not really seeing a bug demonstrated here

Also, after a couple of actions, intelliSense will stop working for calling the function:
https://github.com/microsoft/TypeScript/assets/59291123/e79db2b9-e012-487f-9b04-c2902c8a5825

![image](https://github.com/microsoft/TypeScript/assets/59291123/63920497-821e-4d3e-aabf-856f1786006b)
![image](https://github.com/microsoft/TypeScript/assets/59291123/cf5dd61a-a77d-46bf-9db9-f7bd13bb237c)

**Comment by MartinJohns** [comment]
> I'm not really seeing a bug demonstrated here

He expects the absence of the `href` property to be used for narrowing, so that the props are narrowed to `HTMLButtonProps`, which has a limited type for `type` including only three specific strings (unlike the link-props, where it's `string`). When having an explicitly set `href` it is being narrowed for auto-completion purposes.

Here's a simplified example: [Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wG4AocmATzCTgCEBXGGCAOwAUcwBnOALxwA3nAAWRTAH4AXHCbsAJkkzB2SRaTg06cgOQo9cAD5w9AIyMBfKrXoAZNQGtuEPoJHjJc3jChqAcy0dJB8-QLgbcjQOXzgAQQxgDg8ACjAeXjlmVg5Xd1NHdhdMgEpBAD44AB5FYAA3CuqAejrGimjY+BQPasSYZPYvFQFhfBRzNHwrbTsBfHw4ZorO9jjzXv7B4cxRhWVVdUUZkPnF5dW4tE2klNOFpZWgA)

Auto completion for `type` works in line 9, but in line 10 it does not work.

**Comment by MrOxMasTer** [comment]
> He expects the absence of the `href` property to be used for narrowing, so that the props are narrowed to `HTMLButtonProps`, which has a limited type for `type` including only three specific strings (unlike the link-props, where it's `string`). When having an explicitly set `href` it is being narrowed for auto-completion purposes.

I understand that, yes, but just undefined is always passed by default in the component if there are no props. From my point of view, I understand that this is not critical, but it is inconvenient that you need to explicitly specify undefined. Rather, it makes no sense to specify undefined for props.

And another question. And how do you explain in the video that when I call a function, at first everything is displayed normally in intelliSense, and then it stops being displayed at the slightest action

**Comment by MrOxMasTer** [comment]
> He expects the absence of the `href` property to be used for narrowing, so that the props are narrowed to `HTMLButtonProps`, which has a limited type for `type` including only three specific strings (unlike the link-props, where it's `string`). When having an explicitly set `href` it is being narrowed for auto-completion purposes.

In the playground, in your example, such a thing does not appear:
![image](https://github.com/microsoft/TypeScript/assets/59291123/42fa443b-9f72-4863-8b2e-9f5a16230369)

Although it is much more logical and better than that:
![image](https://github.com/microsoft/TypeScript/assets/59291123/8c5c7d85-e850-44c8-abaf-234fd3e6d10a)

I don't know, I don't think this is really convenient, and it would be better to fix it, because if props was not passed, it is equal to "undefined"
