### ISSUE TITLE
Property 'blur' does not exist on type 'Element' > document.activeElement

### ISSUE THREAD

**Issue by svanuden** [Microsoft/TypeScript#5901]
When using document.activeElement.blur() the compiler tells me that the property does not exist.

**Comment by jeffreymorlan** [comment]
`.blur()` is only guaranteed to exist on HTMLElements, not all Elements. I have frequently seen exceptions caused by unguarded `document.activeElement.blur()`, because document.activeElement was an SVG element rather than HTML.

**Comment by bharatramnani94** [comment]
@svanuden If you're sure you want to use that, you may use it like:
```
(document.activeElement as HTMLElement).blur();
```
Though I'll suggest to still wrap it in a try-catch block.

**Comment by caleywoods** [comment]
@bharatramnani94 Running into a very similar issue and tried your `(document.activeElement as HTMLElement)` but I'm trying to call the `type` property. Its use case is determining if the user has a text input focused so that keyboard shortcuts within an app don't fire. Both of the below lines of code still make VSCode highlight "type" red and say that the type property does not exist on `HTMLElement`:

`const elementType = (document.activeElement as HTMLElement).type;`
```
const element = <HTMLElement>document.activeElement;
if ( element.type === 'text' ) {}
```

Of course you can still use it and it works in the console but it seems like there should be a way to fix it. The [MDN Docs](https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/activeElement) for it say it returns an Element which according to other TS issues I've found says that we should likely be casting it as an `HTMLElement`.

**Comment by tischsoic** [comment]
Save solution might be to check if `document.activeElement` is of type `HTMLElement`:

```ts
if (document.activeElement instanceof HTMLElement) {
    document.activeElement.blur();
}
```

Then you don't need try/catch block, because you ensured that your element has `blur` method. No cast needed to satisfy TypeScript.

**Comment by johnneuland** [comment]
I am trying to pass a ref property into a custom FieldInput component where I use Input from Native Base. 
```
const fieldRef = useRef<Input>(null);
...
 fieldRef.current?.blur();
```
I get the same error here: ```Property 'blur' does not exist on type 'Input'.```
How can I resolve it in this case? @tischsoic @bharatramnani94 

https://stackoverflow.com/questions/63757905/property-blur-does-not-exist-on-type-input

**Comment by vvo** [comment]
@johnneuland You could do:

```js
if (
  document.activeElement === fieldRef.current
) {
  document.activeElement.blur();
}
```

**Comment by MichaelMammoliti** [comment]
> @svanuden If you're sure you want to use that, you may use it like:
> 
> ```
> (document.activeElement as HTMLElement).blur();
> ```
> 
> Though I'll suggest to still wrap it in a try-catch block.

I am against `try/catch` here. instead, you should always check for the input to exist and return or use the optional chaining operator.

optional chaining operator:
```
element?.blur();
```

or: 
```
if (element) {
  element.blur();
}
```

or:
```
if (!element) {
  return;
}

element.blur();
```

**Comment by RemiGirard** [comment]
> > @svanuden If you're sure you want to use that, you may use it like:
> > ```
> > (document.activeElement as HTMLElement).blur();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Though I'll suggest to still wrap it in a try-catch block.
> 
> I am against `try/catch` here. instead, you should always check for the input to exist or use the optional chaining operator.
> 
> optional chaining operator:
> 
> ```
> element?.blur?.();
> ```

It's nice because it's error safe. Additionnaly to be compatible with Typescript you can use : 

`(document.activeElement as (Element & { blur?: () => void }) | null)?.blur?.();`

**Comment by lsheva** [comment]
`onWheel={(e) => e.currentTarget.blur()}` plays well with typescript
