### ISSUE TITLE
Codefix add missing function declaration inserts function in wrong file

### ISSUE THREAD

**Issue by hediet** [microsoft/TypeScript#59116]
![Image](https://github.com/user-attachments/assets/52c924ea-bf71-45f1-9648-1366f69d5b6a)

`main.ts`:

```
import { X } from "./lib";









X.foobar();
```

`lib.ts`:
```ts
export namespace X {
    export function test() {}
};
```

**Comment by mjbvz** [comment]
Confirmed that this seems to be an issue on the TS Side. Here's the returned edit:

```
    {"seq":0,"type":"response","command":"getCodeFixes","request_seq":61,"success":true,"body":[{"fixName":"fixMissingFunctionDeclaration","description":"Add missing function declaration 'foobar'","changes":[{"fileName":"/Users/matb/projects/sandbox/index.ts","textChanges":[{"start":{"line":13,"offset":2},"end":{"line":13,"offset":2},"newText":"\n\nexport function foobar() {\n    throw new Error(\"Function not implemented.\");\n}\n"}]}]}]}
```

**Comment by andrewbranch** [comment]
I'm seeing a similar response but a different editor behavior. We do have incorrect logic for figuring out where to export the function, but the response shows that it should be inserted two lines after the end of the file being edited. For me, this does _not_ result in `X.foobar` being split at the cursor when invoked with the cursor in the middle of `foo|bar`, but rather the function gets added with newlines after `X.foobar`

![image](https://github.com/microsoft/TypeScript/assets/3277153/99ad85a7-440b-43be-9f5d-f11cfaecd2c6)

I think the behavior shown in the gif where the text is apparently inserted at the cursor instead of at the end of the file might be an editor bug, but one that I can't reproduce. That said, is it expected for TS Server to be returning an insertion range that's outside the bounds of the current document length?

**Comment by andrewbranch** [comment]
Note that the bug still happens when the namespace `X` is a global in another file, but not when it's in the same file as the call expression.

**Comment by hediet** [comment]
> I think the behavior shown in the gif where the text is apparently inserted at the cursor instead of at the end of the file might be an editor bug, but one that I can't reproduce. That said, is it expected for TS Server to be returning an insertion range that's outside the bounds of the current document length?

Sorry for the confusion, that was a coincidence. The amount of new-lines roughly equals the characters in the other document at where the method should be inserted. It just happened to be the editor cursor location in this case, but that is unrelated.
