### ISSUE TITLE
Grammar allows infer statement on the left side in a nested conditional

### ISSUE THREAD

**Issue by DavidHancu** [microsoft/TypeScript#59234]
### 🔎 Search Terms

infer on the left side, nested conditional

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about common bugs.

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/C4TwDgpgBAygPAQQHxQLxQVCAPYEB2AJgM5QAUAlvgGYQBOUAQlrgSVPgK4C2ARvVAD8UYsDpUA5lABcHCADd6ASiFMZUagEMANsQgBuIA

### 💻 Code

```ts
type S<A> = A extends (infer B extends number ? string : never) ? B : false;
```

### 🙁 Actual behavior

It was allowed.

### 🙂 Expected behavior

This seems off since the constraint on A changes based on the inference of B, but this would create a cyclic type.

**Comment by Andarist** [comment]
You might find the information contained [here](https://github.com/microsoft/TypeScript/pull/59235/files#r1673602168) interesting

**Comment by That-Guy977** [comment]
I think this is part of a broader range of grammar, allowing `infer` to be used inside constructs: [playground](https://www.typescriptlang.org/play/?#code/C4TwDgpgBAagPAFQHxQLxQQbgFDdJKAQURXQSggA9gIA7AEwGcoBLWgMwgCcoANKAPx8oALii0IAN24580AEIk0GCtTpNYcNpx68UQ-mInSus8NADCSsqpoNmACm3dhVOxtoBXADbfBUYC5PaDF2AENvRggASn9DcSkZPHMoABFrFTd1ZgBtADoC510AXTjRBJMzAgBRDPIs+ygAbyhKMSLhAF8yo0TTZIIAMTrbbOaoHIBpVloZnT5iox8-boNy4yS5KABxEYaNFqmZqEZAtgBzRbmXflXhXsqB6AAJPbVGw4BrMVOuC6uOrcehVNikAJJvdyOQGjD6tMSeWifWgAewA7rNOtEcgAiSg40prB6gggAKUhYxabROZ1o5wANFAQEsALYAIxcnRyMP2zDxOKgAB8oDiQATgRt+k8oIMAIzKYZUpa+RnM8TLKCdJDYAD0OqgBoAegJpYMAEwKuBK9Uqpk-WnnTXavUGqDG6XbeXoXbWry2tW-C5O3X6o0mrZgr1QCG+jVakOu91bUlR8k4nHO0Nuk1AA)

Most of these do make sense, but a conditional doesn't seem to have much use.

**Comment by Andarist** [comment]
Those are especially interesting:
```ts
type I<T> = T extends (infer X extends { x: unknown })["x"] ? X : never;
type J<T> = T extends { x: string, y: number }[infer X extends "x" | "y"] ? X : never;

type I1 = I<{ x: null }>
type J1 = J<"">
```

Those are... weird but creative :P It kinda makes sense, TS is able to decompose this and infer into a check type (and true type and false type).  If those happen to be conditional types... well that still works.

**Comment by ahejlsberg** [comment]
I'll readily admit that the original example seems wrong at first sight. But while the `infer B` doesn't occur in the `extends` position of the inner conditional type, it _does_ occur the the `extends` position of the outer conditional, so it isn't per se incorrect. Indeed, the compiler correctly scopes `B` to the outer conditional. That said, it is a pretty useless construct. You would think that an instantiation `S<X extends number ? string : never>` for some type variable `X` would infer `X` for `B`, but that never happens because we defer the entire outer conditional type when either of the check or extends types is generic. And manifest conditional types are by definition generic, as otherwise they would have resolved to their true or false type.

The comment [here](https://github.com/microsoft/TypeScript/pull/22764#pullrequestreview-105846102) about why `infer` declarations should be permitted anywhere in conditional types (and scoped to the innermost enclosing `extends` clause) still holds, So I don't think we want to change anything here.
