### ISSUE TITLE
A strange behavior when checking `extends ReadonlyArray<any>`

### ISSUE THREAD

**Issue by ruojianll** [microsoft/TypeScript#59430]
### 🔎 Search Terms

"extends", "ReadonlyArray"

### 🕗 Version & Regression Information

- This changed between versions 5.5.3

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/C4TwDgpgBAglC8UBKECGATA9gOwDYhgCdDUQAeAchgoD4AoUSKAIQWTSzwONMudobhoMAMYiIYYDDIAVKBAAewCNnQBnWDTYzBTGRDXAAjG1HjJ0mFoD011GInL0u6PsMAmUw4tlmN6xDEmIQuUG7AAMxe5lK+8koq6uwYOPhEJOSo2CBaAPwsUABcLP5Q9jEQ6EA

### 💻 Code

```ts
type A = ReadonlyArray<'A'>
type B = ReadonlyArray<'B'>
type AcceptA<T extends A> = T
type Test1 = AcceptA<A> //accepted
type Test2 = AcceptA<B> //error
type Test3 = AcceptA<B extends ReadonlyArray<any> ? B : B> // accepted
```

### 🙁 Actual behavior

It could be accepted in Test3 but it's still the same B in Test2 which has an error.

### 🙂 Expected behavior

Show an error as `Test2`.

**Comment by jcalz** [comment]
[SO question](https://stackoverflow.com/q/78798849/2887218)

@RyanCavanaugh  Are we sure this is a bug? The type `B extends ReadonlyArray<any> ? B : B` is a substitution type like `B & ReadonlyArray<any>` (due to #37348), and that intersection is indeed allowed in `AcceptA` because of the unsoundness of `any`.  It's *weird*, but why would someone write `B extends ReadonlyArray<any> ? B : B` in the first place except to expose some substitution-type behavior?

**Comment by RyanCavanaugh** [comment]
@jcalz yeah, good observation. I agree

**Comment by ruojianll** [comment]
@jcalz @RyanCavanaugh But isn't it a bug? `Test3` shouldn't accept `B` in result.

**Comment by ruojianll** [comment]
The true value `B` is should not be `B & ReadonlyArray<any>`. If the condition is true, why do we need to narrow down the true value?

**Comment by ruojianll** [comment]
I still consider it as a bug. @ahejlsberg
