### ISSUE TITLE
Overeager generic type expansion/unrolling prevents TypeScript from catching a type mismatch

### ISSUE THREAD

**Issue by lukasagross** [microsoft/TypeScript#59515]
### 🔎 Search Terms

Generic type expansion / unrolling

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type expansion / unrolling.

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play/?#code/C4TwDgpgBAKg9gBQIYEsBOBnAPDKEAewEAdgCYZRwBGAVhAMbAB8UAvFAN4BQUvfvAbQDSUFMSgBrCCDgAzWAF0AXFAFSQKoQBooANyQAbAK4QVMYQoUBuLgF810uYptdQkKAGVgR2fPbd+WTg4FQxgNDEAcxt+KiQ0FWIjAFsqCDQbWxc3aAB5YAALdK8fP04ePiCQqCTU9Ji+OISoMIjiaLsXejhiMMpC4u9fNigACjgMFWQ0YBRDLHyitBLfJgBKNhYAvjQIbzRxCYA6Jsyunr7ZI2J6EZw8QhJyWERUTCwV2SYmUaO-hxAOn0xggylgG1YWwqvDgA2WQ1kow4qnUYOBJigtjWZy4XG6vWAUCuNwATHdcAQiGQKPBkOhsJ9vr9-uogYYTGCYBCofwDHsahAAO4ANXZEAavBQ8lG6jYrHYACIqgqNtt+LxiELRSCRsiAWixZiJZi8AYMNA1erNSLDf4UdIDTqstDMS7YUtPqNrdqTNjOkA)

### 💻 Code

```ts
// Utility to pre-associate the key-value pairs with tuple types
type ToPairs<T extends object> = {
        [K in keyof T]: [key: K, value: T[K]];
}[keyof T];

type Stuff = {
    foo: string;
    bar: number;
};

type OtherStuff = {
    foo: number;
    bar: string;
};

const otherStuff = (os: Partial<OtherStuff>) => {
    return os.bar;
};

const func = <T extends ToPairs<Stuff>>(...[key, value]: T) => {
    otherStuff({ [key]: value }); 
};

const func2 = <T extends ToPairs<Stuff>>(...[key, value]: T) => {
    let newValue;
    if (key === "foo") {
        newValue = { [key]: value };
    } else {
        newValue = { [key]: value };
    }
    otherStuff(newValue); // error: Type 'string' is not assignable to type 'number'
};
```

### 🙁 Actual behavior

The first `func` does not report the type unsafety in assigning a `Partial<Stuff>` to a `Partial<OtherStuff>` due to  expanding `value` to `string | number`.

### 🙂 Expected behavior

As illustrated in `func2`, TypeScript should be able to determine that these types are not compatible if it deferred fully expanding the generic type.

**Comment by RyanCavanaugh** [comment]
Root cause analysis is a bit off here. Reads of optional properties on aliases aren't sound; this is a known trade-off.

If you look at what `{ [key]: value }` is in `func`, it's `{ [s: string]: string | number }`:
```ts
const func = <T extends ToPairs<FooStringBarNumber>>(...[key, value]: T) => {
    const temp = { [key]: value };
    //    ^?
```
This value matches `Partial<...>` because it's a subtype of `{}` (which is in turn a valid `Partial<anything>`).

This is the same unsoundness you'd see in this example:
```ts
const takeFooNumberBarString = (os: Partial<FooNumberBarString>): string | undefined => {
    return os.bar;
};
const obj: { [s: string]: string | number } = { bar: 42 };
const test = takeFooNumberBarString(obj);
```

The underlying underlying problem is that there's no better type we can give to `{ [key]: value }` than the weak one with the index signature.

Intentionally combinatorial exploding it is fine when there's only one small `key`, but doesn't scale up to arbitrarily large computed objects (which do occur quite often in reality).
