### ISSUE TITLE
Type error in array.push due to ‘Unrelated Types for Getters and Setters’

### ISSUE THREAD

**Issue by cnzgray** [microsoft/TypeScript#59555]
### 🔎 Search Terms

Type error in array.push due to ‘Unrelated Types for Getters and Setters’

### 🕗 Version & Regression Information

- This changed between versions 5.1 and nightly

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.6.0-dev.20240807#code/JYOwLgpgTgZghgYwgAgKoihANnSATANTiwFcIAeAFQBpkBlAXkoD5kBvAWAChlkBzCGGQA3YmQAUASgBcySgG5uvAM6CRYiOOGy6kxVwC+3bggD2IZULjIGyANoBdZHGXIAglChwAnuXSYcfCJSChASAFsAI2haSyhQPgAfMKjoZmZ9OAA6AAcSZQALcTZ1ENkARmQDPW5svMLi0rJZACJylqq9ZAB6buQwZXEAJgBmIaHJWrsABgcs0RCbZCHMmbmFsiWWoZb5IA

### 💻 Code

```ts
interface UnrelatedValue<T, S=T> {
  get value(): T;
  set value(v: S);
}

const a = [] as Array<UnrelatedValue<number, string|number>>;
a.push({ value: 1 });
a.push({ value: "1" }); // ts(2322)
a[0].value = 2;
a[0].value = "2";
```

### 🙁 Actual behavior

As shown in the previous code, `a[0].value` can be set to a `number` and a `string`, but the push operation does not accept the `{ value: "1" }`.

### 🙂 Expected behavior

Push is also a type of set operation and should be allowed to be set as {value: "1"}.

**Comment by jakebailey** [comment]
That doesn't make sense, though; push is not a "set" operation. The object you push in still has the strong as the value when you run the code: https://www.typescriptlang.org/play/?ts=5.6.0-dev.20240807#code/JYOwLgpgTgZghgYwgAgKoihANnSATANTiwFcIAeAFQBpkBlAXkoD5kBvAWAChlkBzCGGQA3YmQAUASgBcySgG5uvAM6CRYiOOGy6kxVwC+3bggD2IZULjIGyANoBdZHGXIAglChwAnuXSYcfCJSChASAFsAI2haSyhQPgAfMKjoZmZ9OAA6AAcSZQALcTZ1ENkARmQDPW5svMLi0rJZACJylqq9ZAB6buQwZXEAJgBmIaHJYy4zC1MsCCysUz5xOEkgA

If anything, it's odd that one can do that first push, because the later sets won't fix up the type at all: [Playground Link](https://www.typescriptlang.org/play/?ts=5.6.0-dev.20240807#code/JYOwLgpgTgZghgYwgAgKoihANnSATANTiwFcIAeAFQBpkBlAXkoD5kBvAWAChlkBzCGGQA3YmQAUASgBcySgG5uvAM6CRYiOOGy6kxVwC+3bggD2IZULjIGyANoBdZHGXIAglChwAnuXSYcfCJSChASAFsAI2haSyhQPgAfMKjoZmZ9OAA6AAcSZQALcTZ1ENkARmQDPW44OwAGByzREJtkACIAJnaTc0sRNrrG5o19AHox3l4APQB+XotTLAgsrFM+cTBvHIhTGBFJIA)

**Comment by MartinJohns** [comment]
This is unrelated to arrays and an issue with object initialization:

```typescript
const v: UnrelatedValue<number, string | number> = { value: "2" }
```

I believe this is intentionally. Such setters are expected to transform the value to whatever type the getter is. When you use an assignment you make use of the setter (unsoundness of object literals aside), but when you initialize an object there is no such setters used.

**Comment by MartinJohns** [comment]
> I believe this is intentionally.

I feel confirmed.

**Comment by cnzgray** [comment]
Thank you for the explanation. After careful consideration, I realize that you are right. One is the initialization of the object, and the other is assigning a value to the object after it has been initialized.
