### ISSUE TITLE
How can i define an interface for method only available to specific other methos

### ISSUE THREAD

**Issue by sebglon** [Microsoft/TypeScript#5966]
On pouchdb.d.ts projet i'm stuck on writing for the emit method that is accessible only for reduce method.

Exemple

```
function reduce(doc) {
   emit(xx, yy)
}
```

the emit method can only by called by reduce function.

How can i write this on Definitely type?
Thanks for your help.

AGBrown/pouchdb.d.ts#36

**Comment by jesseschalken** [comment]
If a method on an `interface` is only accessible to one or more other methods on that interface, then what use is it have it in the interface, since you can't use it from the outside?

If you want to write a method in a class (eg `emit`) that can only be called by a specific other method in the same class (eg `reduce`), then you can just define it locally inside method you want to use it in.

```ts
function reduce(doc) {
    var emit = (x, y) => {
        // ...
    };
    // ...
    emit(xx, yy);
    // ...
}
```

**Comment by sebglon** [comment]
````javascript
function mapReduce(doc) {
    var emit = (x,y) => {
         // ...
    }
 var mapFun = z.callback
}

var mapFun = (doc) => {
      emit(doc.x,doc.y);  // emit can only be called from callback function
}
````

**Comment by jesseschalken** [comment]
So pass `emit` into `mapFun`?

**Comment by sebglon** [comment]
My project is to create definitelytyped for existing javascript PouchDB.
I can't change PouchDB implementation.
I just want to create d.ts interface for compatibility.

**Comment by jesseschalken** [comment]
So if I understand correctly, a JavaScript library provides an object with an `emit` method which, although it is technically accessible anywhere, is only _expected_ to be called from within a callback called `reduce`. I don't think there is a way to express this in TypeScript, and it seems like a strange API. I would expect the `emit` method to be passed _to_ your callback if it is only expected to be called from it.

**Comment by mhegazy** [comment]
I agree with @jesseschalken; I would say JSDoc comments would be a good place to document this restriction.

**Comment by fredgalvao** [comment]
I think @sebglon wasn't quite able to express what we need on this one.
This is not a javascript per se issue, as in "browser or node issue". This happens because CouchDB makes a global function `emit` available for any `map` function, but only in that scope.

We cannot declare the `emit` for every `map` function as in

```typescript
function mapThis(doc){
    var emit: () => {};
    emit(...);
}
```

because we have no controll over the user's code. We can only define what type the `mapThis` is expected to be.

We wanted to know if there's anything in typescript that would allow us to say that for that function type, and for it only, an `emit` function would be available. Similar to reserved words, like the way `export` is handled at the moment, but with limited scope like modules.

### **tl,dr;**
We want to know if there's anything that makes this possible:
```typescript
interface ExistingDoc {}

type MapFunction = (doc: ExistingDoc) => void;

interface MapReduce {
    map: MapFunction;
}

emit(); // this should not compile
var ordinaryFn = function () {
    emit(); // this should not compile either
}

var mapFunction: MapFunction = (doc) => {
    emit(); // this should compile
}

var queryObject = {
    map: (doc) => {
        emit(); // this should also compile
    }
}
```

Otherwise, we would need to advise the user that we can't do that, and tell them to define it themselves (which is the last resort).

**Comment by mhegazy** [comment]
if the function is visible in the scope, i do not think there is much we can do to restrict its use.
