### ISSUE TITLE
ts.sys should be more extensibility

### ISSUE THREAD

**Issue by WanderWang** [Microsoft/TypeScript#5967]
in ```sys.ts ``` , there are the code 
```
   if (typeof WScript !== "undefined" && typeof ActiveXObject === "function") {
            return getWScriptSystem();
        }
        else if (typeof process !== "undefined" && process.nextTick && !process.browser && typeof require !== "undefined") {
            // process and process.nextTick checks if current environment is node-like
            // process.browser check excludes webpack and browserify
            return getNodeSystem();
        }
        else {
            return undefined; // Unsupported host
        }
```

I want to use my custom Virtual-IO-System to run typescript-compiler with CompilerAPI in browser ( Chrome and so on  ) 。so I think  maybe it should be a dependency injection pattern , such as this one :

```

ts.sys.register( new MyFileSystem());

```

If you agree with me ,I will send a PR here

**Comment by DanielRosenwasser** [comment]
Hi there @WanderWang. If you want to run TypeScript in the browser, I think you should create a `CompilerHost` object (see [here](https://github.com/Microsoft/TypeScript/blob/3ce91c438a47a6ec9ee627345b6a2a1ea5796c99/src/compiler/types.ts#L2629-L2637)) and use `ts.createProgram` (see [here](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/program.ts#L327)).

@mhegazy might know more.

**Comment by WanderWang** [comment]
Thanks @DanielRosenwasser . Is there some example to should me how to run typescript in browser ?

Seems that I can only follow the ``` tsc.ts ``` and modify it

**Comment by WanderWang** [comment]
seems that I should create a custom ``` CompilerHost ``` , and I will copy & paste lots of code in https://github.com/Microsoft/TypeScript/blob/master/src/compiler/program.ts#L209 .  I don't think it is a pretty solution ... Maybe have some new way ?

**Comment by vladima** [comment]
`sys` was never an official extensibility point for a compiler for a several reasons:
- interface of `sys` is shaped so it can only be useful in command line compilation scenarios (i.e.all arguments are already passed as an array of strings etc..). `CompilerHost` is much less string oriented and provides a nicer typed view of various compiler options. In addition `CompilerHost` allows to customize module lookup process by implementing `CompilerHost.resolveModuleNames` which `sys` cannot do.
- `sys` is a global variable inside the compiler scope and its initialization happens at some point during evaluation of `ts` module meaning that consumer of the API must precisely control the script loading process to make sure that it will replace `sys` either at some point in time when `sys` is either not yet initialized or it is already set but nothing in compiler codebase have captured its previous value. This part is a very brittle especially comparing to a completely predictable solution with `CompilerHost` that does not have this issue by design (since `compilerHost` is just a parameter to `createProgram`).

In theory we can revise current architecture and make initialization of `sys` more deterministic however in current circumstances don't think it worth it. The only scenario when substitution of `sys` can be beneficial over using `CompilerHost` is if somebody wants to run command line compiler in some new environment that is not `node` / `CScript` / `WScript`/ `ChakraCore` / `tsc` (i.e. in [Rhino shell](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino/Shell) or [Nashorn](https://docs.oracle.com/javase/8/docs/technotes/guides/scripting/nashorn/shell.html)) and so far we don't have any requests for this.

**Comment by fixedtablev6Update** [comment]
hi, I also want to use the compiler from a web-browser but am running in the same issues. I have also created default compiler options and a compiler host from it, but not sure how to call parsing/checking code on that?

Can you also please share your PR for a local fileSystem that can be embedded in local code if needed. 

thanks.

**Comment by megamindbrian** [comment]
I want to use a virtual filesystem too!

**Comment by chrisdutz** [comment]
Hi,

being quite annoyed by the current workflow in using TypeScript in Maven (Dumping the compiler and libraries to the local filesystem and spawning a new OS process to run the compiler), I started working on a little experiment to run the TypeScript compiler inside Java's Nashorn JavaScript engine. Unfortunately I too have encountered this problem. Right now I can't see a way to add a new type of System without patching the compiler code (or duplicating a lot of code, which I think is equally bad). I too would like to have the option to register additional types of Systems. I am willing to invest some time in this, if there is a chance for it being accepted.

Anyone else tried running the TypeScript compiler in Nashorn?
