### ISSUE TITLE
Inheritance and static members

### ISSUE THREAD

**Issue by benzid-wael** [Microsoft/TypeScript#5989]
I think that is useful to access to static members :

* from instances
* from sub classes

Below an example:
```
class A {
  protected static type: string;

 public log(): string {
    console.log(this.type);
  }
}

class B extends A {
  protected static type: string = 'C';
}

class C extends A {
  protected static type: string = 'C';
}

b = new B();
b.log(); // => 'B'

c = new C();
c.log(); // => 'C'
```

**Comment by ahejlsberg** [comment]
We can't do it the way you suggest since `this.type` is used to access an *instance* property named `type`, not a *static* property.

However, your example works if you write it as follows:

```typescript
class A {
  "constructor": typeof A;  // Explicitly declare constructor property
  protected static type: string;

  public log() {
    console.log(this.constructor.type);  // Access actual constructor object
  }
}

class B extends A {
  protected static type: string = 'B';
}

class C extends A {
  protected static type: string = 'C';
}

let b = new B();
b.log(); // => 'B'

let c = new C();
c.log(); // => 'C'
```

By default the `constructor` property of an instance is of type `Function`, but you can specialize it in a class by manually declaring it. Once you do that you can access the statics through `this.constructor.xxx`, and you'll get the properties of the constructor object that actually created the instance (i.e. the derived constructor object).
