### ISSUE TITLE
useVsCodeWatcher interferes with updating typescript @aliased imports paths on file or folder moves

### ISSUE THREAD

**Issue by ShravanSunder** [microsoft/TypeScript#59952]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Make sure you have `useVsCodeWatcher` enabled in settings
2. Create a monorepo
3. have a folder with files that are imported by other files with tsconfig aliases
4. Rename a folder in monorepo.  
5. ts and tsconfig has an error.  References are not renamed

Renames works if `useVsCodeWatcher` fine is disabled.  There are no errors with folder renames.
Unfortunately this experimental feature is enabled by default.

See reference issues:
- video of the issue:  https://github.com/microsoft/TypeScript/issues/59603#issuecomment-2284919153

Related issues
- a possilbe explanation of issue: https://github.com/microsoft/TypeScript/issues/51763#issuecomment-2282329357
- https://github.com/microsoft/TypeScript/issues/59603#issuecomment-2290815321
- https://github.com/microsoft/TypeScript/issues/51763

**Comment by sheetalkamat** [comment]
Need the repro we can clone and steps to run on that repro to be able to investigate this. The repro steps are pretty vague at this point.

**Comment by ShravanSunder** [comment]
I currently don't have time to do a repo.  The work around is to  disable this feature. `useVsCodeWatcher` so i'll be just doing that.  

There's lots of references in the issues provided that show this option is problematic.  Feel free to close the case if you feel like its not enough.

**Comment by sheetalkamat** [comment]
Without a repro this is hard to investigate and may be already fixed?

**Comment by wfern** [comment]
@sheetalkamat Yeah, I can confirm that this issue is fixed in 5.6.x on VSCode.

This was an old and inconsistent issue that was always fast fixable restarting the TS server. I don't know when it really started or why but I never bother to search about it until today.

I take long time tracking the solution across multiple issues. First I found out and change `typescript.tsserver.experimental.useVsCodeWatcher` to `false` in VSCode settings and it fix the issue too, then I tried the `next` version of TS, then the latest `5.6` and confirm that upgrading fix the issue without disabling the new VSCode watcher. 

1. The latest version of VSCode ships with 5.5 and I think people are having a hard time changing the current typescript version.

2. Some stacks like react-native (expo) fix the TS version to 5.3.

3. I think most people don't even know about the new VSCode watcher and just restart the TS server and don't go find the real fix for the issue.

4. I tried in multiple stacks: vue, vite react, expo and this issue is happens across all stacks. 

Would be amazing to pin a issue in the VSCode repo explaining why and how to bump TS to 5.6 until the next VSCode version ships with it.
