### ISSUE TITLE
Do we need to import twice to pick up global augmentations

### ISSUE THREAD

**Issue by brupxxxlgroup** [microsoft/TypeScript#59988]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

Hello

I have a package called **core.error**. In this package i have two files

_global.d.ts_

```typescript
export {};

declare global {
  export interface Error {
    foo(): void;
  }
}
```

_index.ts_

```typescript
Error.prototype.foo = function (this: Error): void {
 
};

export const dooFoo = (err:Error) : void => {
  err.foo();
}
```

Now i have this package as a dependency in my second project. It seems the global augmentation only gets picked up when i do this.

```typescript
import "core.error"

const err = new Error();
err.foo();
```

But when i try to import the dooFoo function only i will get a TypeError saying _TypeError: err.foo is not a function_

```typescript
import { dooFoo } from "core.error"

const err = new Error();
err.foo();
```

Is this expected behaviour? If so do i need to import twice from my module like this?

```typescript
import "core.error"
import { dooFoo } from "core.error"

const err = new Error();
dooFoo(err.foo());
```
Is there any other solution to autoload my global augmentations from the module?

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
