### ISSUE TITLE
Missing overload method on union types

### ISSUE THREAD

**Issue by wheeOs** [microsoft/TypeScript#60006]
### 🔎 Search Terms

overlaod union

### 🕗 Version & Regression Information

- ~~This changed between versions ______ and _______~~
- ~~This changed in commit or PR _______~~
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about overload
- ~~I was unable to test this on prior versions because _______~~

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.7.0-dev.20240919#code/FAMwrgdgxgLglgewgAgOYCcFgA4CECeAPACoB8AFAIbrqX4BcyAgjXSaQD7IBKAppQBMkAG3wtaRMgBpkAa14NklCPgCUjALKVshZfhni2ZUsgDewZMnS8YYdCmoSAdNYFgovQlp16DrSaSB5FRQUDK8wrwAtrwQMKrIALwm5haWyFBIAM4wcknIMPjYvAggcgpJiYnIAOTg0PBINcgA-Mjk8vhKWe0R0bEwjMQJyUoqquR9MXEJjFMDANqd3eX4pcjEALoA3GmWkbkYWNj5lKFOqDYdqrvpyHBl5ACERzgJ5neWZ1BOWVeyMleJ2qC02Nz2yAAvhCgU5sGAsgALSaRabxW7pay2exKUK7NKQmQQXgAd2Q3l0Kj8EnYFFU4OhwCAA

### 💻 Code

```ts
function groupBy<T>(array: Array<T>| ReadonlyArray<T>, key: any): Map<any, Array<T>> {
  return array.reduce<Map<any, Array<T>>>((acc, element) => {

    const k = typeof key === 'function' ? (key as (element: T) => any)(element) : element[key as keyof T];
    let group = acc.get(k);
    if (!group) {
      acc.set(k, group = []);
    }
    group.push(element);
    return acc;

  }, new Map<any, Array<T>>());
}
```

### 🙁 Actual behavior

getting the errors:

**Expected 0 type arguments, but got 1.**

```
Type 'T' is not assignable to type 'Map<any, T[]>'.
Expected 0 type arguments, but got 1.
Property 'get' does not exist on type 'T'.
Property 'set' does not exist on type 'T'.
```

### 🙂 Expected behavior

Allowing the use of the 3rd overload method `reduce<U>` of `Array` / `ReadonlyArray`

**Comment by jcalz** [comment]
There doesn't seem to be a reason to write `Array<T> | ReadonlyArray<T>` since that's equivalent to `ReadonlyArray<T>` as shown [in this playground link](https://www.typescriptlang.org/play/?ts=5.6.2&ssl=2&ssc=1&pln=15&pc=1#code/FAMwrgdgxgLglgewgAgOYCcFgA4CECeAPACoB8AFAIbrqX4BcyASgKaUAmSANvgII10SpADTIA1iwbJKEfAEpGAWUrZCM-KP60iZUsgDewZMnQsYYdCmraAdKfZgoLQstXrNAnaW-kqUKKIsXCwAtiwQMHLIALx6hsbGUEgAzjDiMcgw+NgsCCDikjHR0cgA5ODQ8EilyAD8yOQS+NLJDUGh4TCMxFGx0rJy5O1hEVGMw50A2k0tBfh5yMQAugDcRgnBaRhY2BmU-jaoZo1yawnIcPnkAITbOFHx59IHycdione7JZNLp+vGAF9-mhMDgbNgwMkABZDYIjSJnBKmcyWZ5QNbrAGiCAsADuyFcalkHm0Qgocj+QOAQA)

But I kind of thought #53489 took care of these "union of array" things.

**Comment by wheeOs** [comment]
@jcalz 
> There doesn't seem to be a reason to write Array<T> | ReadonlyArray<T> since that's equivalent to ReadonlyArray<T>

true that, thanks for pointing that out. I initially wrote the function for `Array<T> `, then I had to modify it for `ReadonlyArray` and it ended up like that, but apparently unnecessarily

**Comment by RyanCavanaugh** [comment]
You're reporting this issue specifically?
```ts
function groupBy<T>(array: Array<T> | ReadonlyArray<T>) {
  array.reduce<any>((acc, element) => {
    throw new Error();
  });
}
```

**Comment by wheeOs** [comment]
@RyanCavanaugh yes the code sample can be reduced to that

**Comment by Andarist** [comment]
> But I kind of thought https://github.com/microsoft/TypeScript/pull/53489 took care of these "union of array" things.

This was released in TS 5.2 and it's only about fallback signatures. It applies to situations when a signature can be found in a normal way but we can see that TS was able to find some signatures here even before that: [TS 5.1 playground](https://www.typescriptlang.org/play/?ts=5.1.6#code/GYVwdgxgLglg9mABAcwE5xABwEIE8A8AKgHwAUAhqqubgFyICCVNRxiAPogEoCm5AJggA2uJtQIkAlIgDeAKESJK4gHSoe-EBB6kKECABpEPITwC2PMFGkBeNvMWKoAC3QB3RGB4eAolTiopJIA3AqIAL4hcuFyQA). 

This case loses the relevant signatures in (somewhat complicated) `getUnionSignatures`. This function is able to compute some signatures (2 to be precise) in this case though so the referenced improvement from TS 5.2 doesn't even kick-in.

**Comment by weswigham** [comment]
Yeah, the fallback logic is for unions of arrays over differing element types (to consider them close enough to a single array over the union of both element types) - this example is differing array types over the same element type. We end up saying we can't consider the `reduce` overload with a type argument as identical (rightly so) across the two array types because the 3rd argument of one callback is `T[]` while the other is `readonly T[]`. It's interesting here because we could just subtype reduce the signatures in this case and get a canonical signature set out pretty easily.

**Comment by weswigham** [comment]
For now, we've chosen to leave this behavior as-is, unless we get some more frequent/compelling examples that require unifying multiple generic signatures to the subtype rather than dropping them, as we do today.
