### ISSUE TITLE
Incorrect name of es6 modules default export unnamed functions and classes

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#6013]
source:

``` ts
export default function () {
}
```

emit:

expected:

``` js
define(["require", "exports"], function (require, exports) {
    var default_1 = function () {
    }
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.default = default_1;
});
```

or

``` js
define(["require", "exports"], function (require, exports) {
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.default = function () {
    };
});
```

actual:

``` js
define(["require", "exports"], function (require, exports) {
    function default_1() {
    }
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.default = default_1;
});
```

Unnamed class has same problem.

**Comment by mhegazy** [comment]
actually the right semantics as per ES6 spec (see http://www.ecma-international.org/ecma-262/6.0/#sec-function-definitions-runtime-semantics-instantiatefunctionobject) is to set `Function.name` to `"default"`.

**Comment by falsandtru** [comment]
thanks for your review!

**Comment by DanielRosenwasser** [comment]
So what is the correct emit here?

**Comment by kitsonk** [comment]
Technically, to be most compliant with ES6:

```javascript
define(["require", "exports"], function (require, exports) {
    function default() {
    }
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.default = default;
});
```

But obviously the is emitting to AMD, so can anyone say what is "right"?  Since there is no official module loader for ES6, it would seem anything that ensures the default is located on "*module*.default" would seem correct.  I guess though it should either be an anonymous function or named properly, because being named `default_1` will certainly cause odd stack traces.

**Comment by RyanCavanaugh** [comment]
Going to track this under #6433
