### ISSUE TITLE
`exactOptionalPropertyTypes` faults the use of `Omit`

### ISSUE THREAD

**Issue by hinogi** [microsoft/TypeScript#60138]
### 🔎 Search Terms

exactOptional

### 🕗 Version & Regression Information

I guess this could be in since TS 4.4 with the introduction of that compiler option.

### ⏯ Playground Link

https://tsplay.dev/WoZ89m

### 💻 Code

```ts
type Scalars = {
  Int: { input: number, output: number }
}
type InputMaybe<T> = T | null;
type Foo = {
  a?: InputMaybe<Scalars['Int']['input']>; // InputMaybe<number> | undefined
  b?: InputMaybe<Scalars['Int']['input']>; // InputMaybe<number> | undefined
}

class Bar implements Omit<Foo, 'a'> { // <---
  b?: InputMaybe<number> | undefined; // Error: Types of property are incompatible, InputMaybe<number> | undefined is not assignable to InputMaybe<number>
  //b?: InputMaybe<number> ; Makes the error go away
}

function test(input: Foo){
  const Fuz = new Bar();
  console.log(input.b);
  //                ^?
  Fuz.b = input.b // errors if b in Bar is fixed

}

const Baz = new Bar();
Baz.b;
//  ^?
```

### 🙁 Actual behavior

In this example `Bar` throws an error because `b` is not implemented correctly, but when instantiated and `b` gets assigned it is correct. When removing `undefined` in `Bar` from `b` the error goes away but then the assignment errors.
This only happens when `exactOptionPropertyTypes` is true.

### 🙂 Expected behavior

The types should match even if `Omit` or other mapped types are used

**Comment by MartinJohns** [comment]
This looks to be working correctly and is unrelated to `Omit<>`.

Here's a simplified example of your code:

```typescript
interface A { b?: string; }
class B implements A { b?: string | undefined }

const b = new B();
b.value = undefined;
```

The interface says it has an optional property `value` typed `string`, so implementing it with the incompatible type `string | undefined` errors. If you change this to `string`, the assignment errors because you're trying to assign `undefined` to an optional non-`undefined` property (which is not allowed under `exactOptionalPropertyTypes`.

**Comment by hinogi** [comment]
> This looks to be working correctly and is unrelated to `Omit<>`.
> 
> Here's a simplified example of your code:
> 
> ```ts
> interface A { b?: string; }
> class B implements A { b?: string | undefined }
> 
> const b = new B();
> b.value = undefined;
> ```
> 
> The interface says it has an optional property `value` typed `string`, so implementing it with the incompatible type `string | undefined` errors. If you change this to `string`, the assignment errors because you're trying to assign `undefined` to an optional non-`undefined` property (which is not allowed under `exactOptionalPropertyTypes`.

I am afraid I can't follow.

**Comment by hinogi** [comment]
oh now I get it
![image](https://github.com/user-attachments/assets/46a22396-3a25-4588-a7c7-7428cbc16824)
I guess this is what you meant, so I typed the example without turning exactOptionalPropertyTypes and assumed it would stay the same when turning it on, that makes more sense now

**Comment by hinogi** [comment]
oh one question though, if i remove the undefined in B.b it still says  B.b is string | undefined

**Comment by MartinJohns** [comment]
With `exactOptionalPropertyTypes` you have different types for write and read access. When having a property `b?: string` you can only assign a `string`, but on read access it can either be a `string` or `undefined`. The tooltip you see shows you the read-type.

**Comment by hinogi** [comment]
okay that is confusing, can it be made equal in one or the other way or only by turning off exactOptionalPropertyTypes?

**Comment by MartinJohns** [comment]
This is intentional and the very purpose of the `exactOptionalPropertyTypes` flag. With this flag optional properties may only be *missing* (aka unset), so assigning `undefined` is not allowed (unless explicitly typed `undefined`). However, when you try to read the property and it's unset you end up with `undefined`.

When you disable this flag it's allowed to explicitly set `undefined` to optional properties, so there's no difference between "explicitly set to `undefined`" and "unset" properties.
