### ISSUE TITLE
No typecheck on assign incorrect type to interface with all optional props

### ISSUE THREAD

**Issue by Strate** [Microsoft/TypeScript#6014]
Some code:

```
interface A {
    id?: number
}

const a: A = {text: "text"} // error comes only here
const notA = {text: "text"}
const b: A = notA
```

I expect 2 errors *TS2322: Type '{ text: string; }' is not assignable to type 'A'*, but I get only one, for `const a: A = {text: "text"}` line. There is no error on `const b: A = notA` line. Is it by design? Looks weird.

**Comment by ahejlsberg** [comment]
This is by design. The type `{ text: string }` *is* assignable to the type `{ id?: number }` because the `id` property is optional and the `text` property is simply an extra property. The error we report isn't about assignment compatiblity, but rather about the object literal having an unknown extra property `text`.

It is entirely possible that `notA` uses (or intends to use) the `text` property for other purposes elsewhere in the program, so there isn't an error in the last assignment. However, if the source is an object literal with extra properties, we know that those extra properties are irretrievably "lost" in the assignment in the sense that no other part of the program could get to them. So, in the object literal case we can with certainty conclude that there is something wrong.
