### ISSUE TITLE
Typescript cannot support paths in other local projects referenced in the package

### ISSUE THREAD

**Issue by alamhubb** [microsoft/TypeScript#60288]
### 🔍 Search Terms

I have a project A, which has path: "@" configured in it. Then this alais is used in this project. Another project B references the code in project A, and it prompts
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@/syntax'
How can I solve this situation?

### ✅ Viability Checklist

- [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [x] This wouldn't change the runtime behavior of existing JavaScript code
- [x] This could be implemented without emitting different JS based on the types of the expressions
- [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [x] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [x] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

none

### 📃 Motivating Example

none

### 💻 Use Cases

none

**Comment by ritschwumm** [comment]
who "prompts Error [ERR_MODULE_NOT_FOUND]"? the typescript compiler, or the runtime?

**Comment by alamhubb** [comment]
> who "prompts Error [ERR_MODULE_NOT_FOUND]"? the typescript compiler, or the runtime?

../../testa/src/TestA.ts:1:20 - error TS2307: Cannot find module '@/TestAA.ts' or its corresponding type declarations.

1 import TestAA from "@/TestAA.ts";
                     ~~~~~~~~~~~~~

TestB.ts:1:19 - error TS5097: An import path can only end with a '.ts' extension when 'allowImportingTsExtensions' is enabled.

1 import TestA from "testa/src/TestA.ts";

When I compile ts files using tsc I get the error

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.

You can ask questions on sites like [Stack Overflow](https://stackoverflow.com/questions/tagged/typescript). We are not able to provide one-on-one support on the issue tracker. Please read the issue template carefully - it has important information on what kinds of reports can be acted on here, as well as links to useful TypeScript resources. Thanks!
