### ISSUE TITLE
Migrate-a-thon: ProceduralPlant

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#6049]
URL: https://github.com/GreenSpiny/ProceduralPlant

Size: Small
Tech: Browser, THREE

**Comment by paulvanbrenk** [comment]
**Feedback**

Used Visual Studio 2015 Update 1 + TS 1.7.5

1. Created a new TypeScript HTML Application, and included the non-lib files as `.ts` files. 
2. Included required definition files. 
3. Disabled allow implicit any.

**Remarks**
Definition files on Definitely Typed have a number of errors, both because they were not updated to the latest version of the library, and because of genuine errors. 
Converting the following to a class is cumbersome:
```typescript
function leafObj(vertex, rotation){
    this.position = vertex;
    this.rotation = rotation;
}
```
There is little value in doing a basic conversion to .ts files. Unless you also disallow implicit any, you won't find many actual errors.

**Comment by paulvanbrenk** [comment]
I migrated the files one at a time initially

After enabling no implicit any, you're forced to complete all files, and the number of errors can be overwhelming.
