### ISSUE TITLE
Contextual typing should not be prioritized over generic type parameter defaults during inference

### ISSUE THREAD

**Issue by jarpoole** [microsoft/TypeScript#60519]
### 🔎 Search Terms

contextual typing, control flow analysis, generic type parameter defaults, inference

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about [contextual typing](https://www.typescriptlang.org/docs/handbook/type-inference.html#contextual-typing)

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.6.3&ssl=11&ssc=1&pln=2&pc=1#code/FAEwpgxgNghgTmABAMwK4DsIBcCWB7dFPPAHgBUAaRAJUQF5EyA+ACh3QAdUsAuRgSj7UA3MGBQwWRDD4BnLHHYBzRAB9EGcMnZgQomPSJ4WAcgAWYKFDwn+wGMMQB6J4nmL0K9ZrDb0uxB4WMQgCeUQAI0NkYlMLKxs7AwYI-UcXNwVlQLsgA

### 💻 Code

```ts
declare function foo<T, R = T>(input: T): R;

let a: string | undefined;
a = foo('hello')
a; // string | undefined
```

If I introduce a useless intermediate assignment then everything works correctly:

```ts
const b = foo('hello')
a = b;
a; // string
```

### 🙁 Actual behavior

CFA does not narrow the type of the `let` declaration because contextual typing appears to kick in.

### 🙂 Expected behavior

The return type `R` is not specified explicitly and so should (according to its default) take the value of `T` which is `string` in this case. This should allow CFA to narrow the type of `a` after the assignment without any useless intermediate assignments.

### Additional information about the issue

I hit this issue when working with NestJS's dependency injection accessor method `.get()`. The type signature is as follows (there are a bunch of overloads but they don't matter):

```ts
export interface INestApplicationContext {
    get<TInput = any, TResult = TInput>(typeOrToken: Type<TInput> | Function | string | symbol): TResult;
}
```

Perhaps the real question is why `TResult` is even required here?

**Comment by jcalz** [comment]
This doesn't look like a bug, TS intentionally infers from return types and defaults intentionally don't take precedence over inferred types. If you don't want to infer from the return type then use `NoInfer` like
```ts
declare function foo<T, R = T>(input: T): NoInfer<R>;
```
[Playground link](https://www.typescriptlang.org/play/?ts=5.6.3#code/FAEwpgxgNghgTmABAMwK4DsIBcCWB7dFPPAHgBUAaRAJUQF5EyA+ACh3QAdUsAuRgSj4A5PAEl0yMHBLUmAbmDAoYLIhh8AzljjsA5ogA+iDOGTswIBTHpE8LAOQALMFCh57-YDDmIA9L8QtHXRdYCA)

**Comment by jarpoole** [comment]
@jcalz given I can't modify the type of the library function in NestJS where this actually appears (see the additional context section) I guess I'm just out of luck then and I have to fall back to an intermediate assignment? 

As an aside, I'd love to dive deeper into how typescript prioritizes sources for types. Any documentation you'd recommend that would answer why its desirable to prioritize contextual inference over the default parameter type for example?

**Comment by jcalz** [comment]
I'm not a TS team member so I'm not able to answer authoritatively.

I'd say ask NestJS about why their thing is the way it is.  It looks like either they were expecting someone to manually specify generic type arguments, or they *wanted* inference from return type. You might not be "out of luck" but since this isn't a bug in TypeScript, I don't know what to tell you. Work around it somehow? Use declaration merging to add a call signature of your choosing, maybe? 

Defaults were implemented in #13487 as fallbacks for failure of inference, not as ways to override inference. It would be very strange indeed if defaults took precedence over inference. Maybe you want to split inference into inference from passed arguments and inference from contextually typed return types, and then change priorities somewhere, but that's not how it was implemented. I don't know how to point to documentation for why things don't behave the way they don't behave (seems like it would need lots of documentation for everything that doesn't happen in TypeScript). Maybe this problem has come up before and someone can find an existing GitHub issue describing it? Not sure.

**Comment by jarpoole** [comment]
Thank you for taking the time to triage my report and for the extra details! The linked PR definitely does state that this is not a bug: `If a default type is specified and inference cannot chose a candidate, the default type is inferred`. I'll close this issue out momentarily and focus on figuring out if NestJS could adopt `NoInfer<>`...

BTW I owe a good chunk of my typescript knowledge to your stackoverflow posts so thank you so much for your contributions to the community!

**Comment by chocolateboy** [comment]
Another example of this surprise, since this is hard to find:

**keywords**: assign, assignment, default type parameter, type inference, undefined

```typescript
const parent = <T extends Element = HTMLElement>(el: Element): T => {
    // XXX Node.parentElement incorrectly has type HTMLElement in lib.dom.d.ts
    return el.parentElement as unknown as T
}

let result1: HTMLElement | undefined
let result2: HTMLElement | undefined
let result3: HTMLElement

// Error: Type 'Element' is missing the following properties from type 'HTMLElement': accessKey, accessKeyLabel, ...
result1 = parent(document.head)

// OK
const temp = parent(document.head)
result2 = temp

// OK
result3 = parent(document.head)
```

Wrapping the return type in `NoInfer` resolves the issue in this case:

```typescript
const parent = <T extends Element = HTMLElement>(el: Element): NoInfer<T> => {
    return el.parentElement as unknown as T
}

let result: HTMLElement | undefined

// OK
result = parent(document.head)
```
