### ISSUE TITLE
Migrate-a-thon: bee-app

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#6052]
URL: https://github.com/kellydavid/bee-app

Size: Medium/medium-small
Tech: Cordova, Ionic, Angular

**Comment by billti** [comment]
The conversion went well. You can see the changes at https://github.com/billti/bee-app/commits/ts-migration. Below is a brief overview of the timeline, and my general process and experience.

### Adding the basic infrastructure
 - I am completely new to Ionic, and not that familiar with Angular1, so ramp up and understanding the project before any changes was a non-trivial task.
 - As all the source is under `./www/js`, I just made a sibling `./www/src` folder and added a `tsconfig.json` with an `outDir` of `../js` to overwrite the original files on compilation as I ported them.
 - Figuring out which typings to get and how was probably the biggest challenge. I tried using `tsd`, but querying on `angularjs` returns nothing, for some reason you need a trailing `/` (see output below)

```
MacBook-Pro:bee-app bill$ tsd query angularjs

>> zero results
MacBook-Pro:bee-app bill$ tsd query angularjs/

 - angularjs / angular-animate            
 - angularjs / angular-cookies            
 - angularjs / angular-mocks              
 - angularjs / angular-resource           
 - angularjs / angular-route              
 - angularjs / angular-sanitize           
 - angularjs / angular                    
 - angularjs / angular-scenario-v1.2.0   
```

 - After installing all the typings (via `tsd install angularjs/ `), I actually then had a bunch of errors compiling with TypeScript - this before I'd even started touching any source files:

```
MacBook-Pro:src bill$ tsc
../../typings/angularjs/angular-animate.d.ts(18,30): error TS2305: Module 'ng' has no exported member 'IAugmentedJQuery'.
../../typings/angularjs/angular-animate.d.ts(19,30): error TS2305: Module 'ng' has no exported member 'IAugmentedJQuery'.
../../typings/angularjs/angular-animate.d.ts(20,33): error TS2305: Module 'ng' has no exported member 'IAugmentedJQuery'.
../../typings/angularjs/angular-animate.d.ts(21,36): error TS2305: Module 'ng' has no exported member 'IAugmentedJQuery'.
../../typings/angularjs/angular-animate.d.ts(22,33): error TS2305: Module 'ng' has no exported member 'IAugmentedJQuery'.
../../typings/angularjs/angular.d.ts(17,1): error TS2440: Import declaration conflicts with local declaration of 'ng'
../../typings/angularjs/angular.d.ts(173,55): error TS2305: Module 'ng' has no exported member 'auto'.
../../typings/angularjs/legacy/angular-scenario-1.2.d.ts(166,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'angular' must be of type 'IAngularStatic', but here has type 'IAngularStatic'.
../../typings/ionic/ionic.d.ts(128,73): error TS2305: Module 'ng' has no exported member 'IAugmentedJQuery'.
../../typings/ionic/ionic.d.ts(170,83): error TS2305: Module 'ng' has no exported member 'IPromise'.
../../typings/ionic/ionic.d.ts(175,24): error TS2305: Module 'ng' has no exported member 'IPromise'.
../../typings/ionic/ionic.d.ts(176,24): error TS2305: Module 'ng' has no exported member 'IPromise'.
../../typings/ionic/ionic.d.ts(212,30): error TS2305: Module 'ng' has no exported member 'IPromise'.
../../typings/ionic/ionic.d.ts(227,44): error TS2305: Module 'ng' has no exported member 'IPromise'.
../../typings/ionic/ionic.d.ts(233,84): error TS2305: Module 'ng' has no exported member 'IPromise'.
../../typings/ionic/ionic.d.ts(237,36): error TS2305: Module 'ng' has no exported member 'IPromise'.
../../typings/ionic/ionic.d.ts(238,24): error TS2305: Module 'ng' has no exported member 'IPromise'.
../../typings/ionic/ionic.d.ts(256,55): error TS2305: Module 'ng' has no exported member 'IPromise'.
../../typings/ionic/ionic.d.ts(259,48): error TS2305: Module 'ng' has no exported member 'IPromise'.
```

 - Removing most of the plugins and just leaving the core `angular.d.ts` file referenced resolved the above issues.
 - I installed the remaining libraries in use via TSD without any issue (ionic, cordova, chartjs).

### Converting the code

 - I started by looking for files with the least dependencies (e.g. leaf nodes) and started there (with `services.js`).
 - Only one error after renaming to `services.ts`, and it was a legitimate bug! There was a typo on an identifier, so it would have been `undefined` (this was for mock data, so probably had no runtime impact).
 - Next I renamed `controllers.js`, and this had a type error. Basically it was initializing a var to a number, then converting to a string if below 10 by prepending "0". Easily fixed. See below for change.:

```
  var month=d.getMonth()+1;
  if (month<10){
    month="0" + month;
  };
```
Fixed by changing to the below code:
```
  var month=(d.getMonth()+1).toString();
  if (month.length < 2){
    month= "0" + month;
  };
```

 - Overall the conversion was easy enough, however nearly every type in the file was `any`, as in Angular style nearly every value you operate on is passed into a function expression as a param, and by default params without annotations are `any`, so not super useful at this point.

### Adding types
 - At this point I tried to add some types for the specific Ionic and Angular objects in usage.
 - Here I hit more issues trying to find and use the typings correctly. For example, The keyboard plugin declares the `Keyboard` object as a global, not on the `plugin` interface where it is accessed. In a similar vein, the `StatusBar` value is declared on `window`, but the code then accesses it as a global (the type `StatusBar` is global however. I worked around both of these with the below for now.

```
interface CordovaPlugins {
  Keyboard: any;
}
declare var StatusBar: StatusBar;
```

 - Next on trying to add more param types, I had to find out that `angular-ui` used by Ionic is a separate project again (https://github.com/angular-ui/), and the types need to be acquired separately.
 - After downloading this and adding a few param types, it seemed like more trouble than it was worth, as the param types are quite lengthy (see below), yet the APIs very simple and only called a couple times. Perhaps during authoring time this would have been more useful, or if the usage was more extensive.

```
.controller('TaskImageDescriptionCtrl', function($scope, $state, 
          $ionicPopup: ionic.popup.IonicPopupService, 
          $ionicHistory: ionic.navigation.IonicHistoryService) {
```

 - Most of the project is concerned with manipulating the $scope and $state params, which are a complex custom type. I didn't get time to tackle modeling this, but I would imaging this is where most bugs would be found and authoring would have been most useful. This is probably true in general of Angular projects, and the DefinitelyTyped [page for AngularJS](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/ffceea9dd124d277c4597c7bd12930666ec074c5/angularjs#a-word-on-scope-and-assigning-new-members) has some useful explaining this.

### Summary
Overall for this simple project, getting the correct typings in place for Angular and Ionic was painful and didn't add a lot of value. Adding a custom type for the data model would likely have been more useful, especially if done at authoring time, but I didn't get to add this.
