### ISSUE TITLE
Migrate-a-thon: cutie-clicker

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#6053]
URL: https://github.com/stawberri/cutie-clicker

Size: Medium
Tech: jQuery, non-prototypal classes (challenge!)

**Comment by sandersn** [comment]
Cute clicker is a clicker game that focuses on complex mechanics. I couldn't find anything that automates the clicking either. Fortunately I didn't have to understand how it worked in order to port to typescript. In two days I was able to port the whole thing, including compiling without implicit any and adding decent d.ts for the two that were missing from definitely typed. At the end of the second day I even had enough time for some simple type-directed refactoring -- mostly simplifying uses of signatures that didn't really need to have Union types. 

I was mostly able to restrict my edits to a types file that I added. I had to add type assertions for a lot of objects that were technically built up incrementally even though the assignments to finish up the object were right below the initial assignment. Otherwise I had to change very little. Contextual typing took care of the rest. 

The value of the types file is debatable -- literally. Either it is there to satisfy the compiler or else it serves as valuable documentation for the reader. Maybe both.
