### ISSUE TITLE
Wrong type inferred with the new genric typed arrays

### ISSUE THREAD

**Issue by pfumagalli** [microsoft/TypeScript#60638]
### 🔎 Search Terms

typed array
Uint8Array
ArrayBufferLike

### 🕗 Version & Regression Information

- This changed between versions 5.6 and 5.7

### 💻 Code

This is a very simple file that exports a `Uint8Array` parser created by a factory method:

```ts
export type Parser<T> = (input: string) => T

function createUint8ArrayParser(): Parser<Uint8Array> {
  return (_input: unknown): Uint8Array => {
    throw new Error('Not implemented')
  }
}

export const parser = createUint8ArrayParser()
```

### 🙁 Actual behavior

The resulting `.d.ts` file looks as follows:

```ts
export type Parser<T> = (input: string) => T;
export declare const parser: Parser<Uint8Array<ArrayBufferLike>>;
```

The type returned for `parser` includes the generic version of `Uint8Array` which basically mean that anything depending on this export _must_ also be at least on version 5.7.

When importing this in a project using TypeScript 5.6 we get an error:

> **TS(2315):** Type 'Uint8Array' is not generic.

### 🙂 Expected behavior

The type returned for `parser` should be `Parser<Uint8Array>` and **not** `Parser<Uint8Array<ArrayBufferLink>>`

```ts
export type Parser<T> = (input: string) => T;
export declare const parser: Parser<Uint8Array>;
```

**Comment by jcalz** [comment]
Doesn't seem like a *bug*, per se, since I assume whenever TS adds or modifies types in its libraries, the emitted code might be incompatible with older versions of TS (like, I'm guessing when TS added `Awaited`, things that produced that stopped being compatible with prev versions, etc).  Maybe you could work around it like

```ts
export type MyUint8Array = Uint8Array;
function createUint8ArrayParser(): Parser<MyUint8Array> {
    return (_input: unknown): Uint8Array => {
        throw new Error('Not implemented')
    }
}
```
[Playground link](https://www.typescriptlang.org/play/?#code/KYDwDg9gTgLgBDAnmYcAKBDKBnYUA8AKgHxwC8cAFAJYB2YArjAFxzYxR0DmAlOaYQBQoSLATJUAWUQBVOjAAcAQShQMicnDm1FKtYgDcggGYNaAYxjUItOOajAMMYNt2r1mHHko9Wn3ATSrsruiKQA3oJw0XAOMAxQtpQA+nSMLHBmANa0EADutL5a8iH6-HCRMVUIABZQ+XC0wHlwAKKq0JQA5AByEPDUALZgADbAg8A6wAAmXTxRMQC+gsvC4NDw5jbscGBYAZr2js7Beh773jxAA)

**Comment by RyanCavanaugh** [comment]
Backcompat like this is not an invariant, but we should add a rule to downlevel-dts for this case
