### ISSUE TITLE
Regression of disposable async iterators (#59633)

### ISSUE THREAD

**Issue by james-pre** [microsoft/TypeScript#60654]
### ⚙ Compilation target

N/A

### ⚙ Library

ESNext, Typescript 5.7.2

### Missing / Incorrect Definition

`AsyncIterator` is missing a `[Symbol.asyncDispose]` property. I found this after investigating a type error I got while creating a polyfill of `node:fs`'s `ReadStream`. You can follow the rabbit hole here: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/71307.

At the end, I discovered that `AsyncIteratorObject` has the `[Symbol.asyncDispose]` property (from #59633) and since `AsyncIterator` doesn't extend `AsyncIteratorObject`, it is missing the property. In fact, `AsyncIteratorObject` extends `AsyncIterator`.

### Sample Code

```TypeScript
declare const it: AsyncIterator<any>;

it[Symbol.asyncDispose](); // <-- error!
```

Error:
```
Element implicitly has an 'any' type because expression of type 'unique symbol' can't be used to index type 'AsyncIterator<any, any, any>'.
  Property '[SymbolConstructor.asyncDispose]' does not exist on type 'AsyncIterator<any, any, any>'.ts(7053)
```

### Documentation Link

I wasn't able to independently find anything in the ECMAScript specification or on MDN, so the only reference I have is #59633

### Fix

This can be fixed by having `AsyncIterator` extend `AsyncDisposable`.

**Comment by Jamesernator** [comment]
> At the end, I discovered that `AsyncIteratorObject` has the `[Symbol.asyncDispose]` property (from [#59633](https://github.com/microsoft/TypeScript/pull/59633)) and since `AsyncIterator` doesn't extend `AsyncIteratorObject`, it is missing the property. In fact, `AsyncIteratorObject` extends `AsyncIterator`.

The `AsyncIterator` type doesn't refer to the builtin object of the same name because TypeScript already used it for the async iterator protocol where it already perfectly legal to have an async iterator that doesn't have `[Symbol.asyncDispose]`.

The new `AsyncIteratorObject` is the builtin `AsyncIterator` object (i.e. the one on the prototype of async generators).

> ```
> declare class Broken implements AsyncItWithNode {
>	it: AsyncIterableIterator<any>; // <-- error!
> }
> ```

The error you are getting in the linked discussion is expected, an arbitrary async iterator doesn't have `[Symbol.asyncDispose]`. Only those that actually extend the builtin `AsyncIterator` object, or those that implement it themselves, do.

**Comment by james-pre** [comment]
Great, thanks. I'll look into resolving the issue on `@types/node`.
