### ISSUE TITLE
How does indexing an optional property within a mapped type behave?

### ISSUE THREAD

**Issue by juhort** [microsoft/TypeScript#60717]
### Acknowledgement

- [x] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

So, the outcome of reading an optional property would always have an `| undefined` in the result irrespective of whether the `exactOptionalPropertyTypes` setting is OFF or ON.

```ts
// @exactOptionalPropertyTypes: false

declare const person: {name: string; age?: number};

const age = person.age;
//    ^? const age: number | undefined
```

```ts
// @exactOptionalPropertyTypes: true

declare const person: {name: string; age?: number};

const age = person.age;
//    ^? const age: number | undefined
```

**And this makes sense.**

<br>

But when we access an optional property within the context of a mapped type, why isn't the behaviour deterministic?

In the following case, I'd expect `Type[P]` to always have `| undefined` when `P` is an optional property, because reading an optional property should have `| undefined` in the outcome. However, when the setting is ON, I don't get the `| undefined`.
```ts
// @exactOptionalPropertyTypes: true

type Foo<Type> = {
  [P in keyof Type]: Type[P];
};

type T = Foo<{a?: 1}>;
//   ^? type T = {a?: 1;}
```

But if I wrap `T[P]` in a tuple, then I do get `| undefined`.
```ts
// @exactOptionalPropertyTypes: true

type Foo<Type> = {
  [P in keyof Type]: [Type[P]];
};

type T = Foo<{a?: 1}>;
//   ^? type T = {a?: [1 | undefined];}
```

Does this have something to do with homomorphism? But, from what I understand both the last two examples are homomorphic.

**Comment by juhort** [comment]
@MartinJohns I don't think that answers my question, my question is _not_ about what homomorphic mapped types are, but about indexing optional properties.

**Comment by jcalz** [comment]
I think the behavior of `Type[P]` is the same, but the type *display* is different. To my understanding, there's now two "flavors" of `undefined`. One which means "present-and-`undefined`", and one which means "*missing*".  So there's an undefined type and a missing type, but both usually display as `undefined`. The only time a missing type is suppressed when displayed is if it's in the type of an optional property. I think you can tease that information out like this: 

```ts
// @exactOptionalPropertyTypes: true

type Foo<Type> = {
  [P in keyof Type]: { r: Type[P], o?: Type[P] };
};

type T = Foo<{ a?: 1, b: 2, c?: 3 | undefined }>;
/* type T = {
    a?: { r: 1 | undefined; o?: 1;             };
    b:  { r: 2;             o?: 2;             };
    c?: { r: 3 | undefined; o?: 3 | undefined; };
} */
```
[Playground](https://www.typescriptlang.org/play/?exactOptionalPropertyTypes=true&ssl=13&ssc=1&pln=3&pc=1#code/PTAEAEFMA8EMGMAuB5ADoglgewHawDYAKATlqpMYgJ4AqV5AzgFyiLECukAUF9eaADEsWADx1yAPlABeUAG8uoUAG1CoDDlABrSFSwAzUOMgBdFnNDEWx1SYA0oLAH5r9SLdABfANxcfPPkgjGUFhEQtYF1AARgcAIxYAJgd4KIBmUAAfUHYcABNIfQ1IPK8JX2AAKlY3YNkFJSVI80sWaKyc-MLivO9HKOi+xuGR-2GEpQsrUEShkfnnJLn54bHG1JbpjOzcgqKcEr7F0G3OvZ6+-09QSuAeIA)

So `T["a"]`'s `undefined` is definitely the "missing" one, since it is absorbed into `{o?: 1}`.

I do think the missing type is "unstable" in the sense that it will spontaneously "decay" to `undefined` if you try to manipulate it too much. While the above `Foo` mapped type preserves the missingness, if you write something like

```ts
// @exactOptionalPropertyTypes: true

type Miss = { a?: 1 };
const m: Miss = { a: undefined }; // error

type Undef = { a?: Miss["a"] };
const u: Undef = { a: undefined }; // allowed
````
[Playground](https://www.typescriptlang.org/play/?exactOptionalPropertyTypes=true#code/PTAEAEFMA8EMGMAuB5ADoglgewHawDYAKATlqpMYgJ4AqV5AzgFyiLECukAUF9eaAFkMDBqAC8oAN6hYAfhYBGUAF8A3F3i4GiUAFsWQkeKkyW7HABNIAMww5IFlatAhQFUsR59IoAKqWbY2k5A2EGAG0AIlhIgF0nDS0ddhZ-K2sg01BzdLsHJxcwAnwsAHcHIA)

the indexing into an existing optional property and reusing it elsewhere causes the missingness to itself go missing so instead of being missing, the type is now undefined.  Uh, I think. 😵 I'm going to go lie down.

**Comment by RyanCavanaugh** [comment]
Type display is indeed very subtle and we don't always do a great job suppressing `| undefined` in cases like these (PRs welcomed btw). Checking the actual *behavior* is the only way to ensure you're seeing exactly the correct EOPT results.
