### ISSUE TITLE
Can not use parameter of a constructor in generic function, but allowed as a argument

### ISSUE THREAD

**Issue by blakeembrey** [Microsoft/TypeScript#6073]
```ts
function test <T extends Constructor> (value: T = Test): T {
	return value
}

interface Constructor {
	new (...args: any[]): any
}

class Test {
	cause: string
}

test(Test)
```

Couldn't find an existing issue on this, but the same thing occurs in the function body. As far as I understand, they are compatible types - the behavior is just different from within and outside the `test` function.

**Comment by blakeembrey** [comment]
On the same note, I can't quite solve how to describe this interface:

![image](https://cloud.githubusercontent.com/assets/1088987/11758714/6405af64-a023-11e5-8912-b3214b89c247.png)

**Comment by ahejlsberg** [comment]
The error in your original example is by design. The type `typeof Test` is not assignable to type `T` because `typeof Test` is not be assignable to all possible type arguments for `T`. For example:

```typescript
class Derived extends Test {
    foo: number;
}

test(Derived);  // Same as test<typeof Derived>(Derived);
```

Here, the inferred type argument for `T` is `typeof Derived`, and `typeof Test` is not assignable to that type.

**Comment by blakeembrey** [comment]
Interesting. Is there a way or proposal to solve the initial example? Having a generic with some constraint used on the input. I expected this to work since they are structurally the same, I just needed to say I can accept more than defined. For example, this works:

```ts
interface Constructor {
    new (...args: any[]): any
}

class Test {
    cause: string
}

var x: Constructor = Test
```

Is there a resource I should read to get my head around this?

**Comment by ahejlsberg** [comment]
You could write your example like this:

```typescript
function test(value: Constructor = Test): Constructor {
    return value;
}
```

You can then pass `Constructor` or any class derived from `Constructor` as an argument. The returned value will always have the static type `typeof Constructor`, and might be `Test` if the value you passed was undefined. This contrasts with your initial example where the static type of the result is the same as the static type of what you passed as an argument. And because the static type might be further derived than `Test`, you can't use `Test` as a default value.

Hope this helps.

**Comment by blakeembrey** [comment]
Thanks for the explanation. 

What I was trying to type is https://github.com/julien-f/js-make-error, but it sounds like it won't be possible to make it 100% correct. The type definition I currently ended on is https://github.com/typings/typed-make-error/blob/master/index.d.ts, but it's not accurate. The issue is that it takes a function, mutates the prototype of the input and then returns the same input function (which is a constructor). Using the ES6 extends isn't an issue in TypeScript, trying to support the functional use-case was just an extra attempt to understand the constraints of the type system for me. This type definition might be possible to improve if there's variadic parameters/generics, since I could use that for `makeError.Constructor`.

Anyway, thanks!
