### ISSUE TITLE
Incorrect constructor overload: takes only first overload, but not others

### ISSUE THREAD

**Issue by psnet** [microsoft/TypeScript#60745]
### 🔎 Search Terms

constructor, typescript, Uint32Array, Uint16Array, Uint8Array, Uint32ArrayConstructor, Uint16ArrayConstructor, Uint8ArrayConstructor

### 🕗 Version & Regression Information

- This changed between versions 5.6.3 and 5.7.2

### ⏯ Playground Link

https://www.typescriptlang.org/play/?target=9&ts=5.7.2#code/FAFwngDgpgBAkgOwCZQB4FEA2UC2UEgDOAwgPYKEgBOArgMYilUwC8MAqgJYEDMATAEEqVAIZgyFavUbMAPh24gAjADYho8eUq0GTGPK4EAHOrETt0pgG5gwAGY0EDTuRggolABR1SOCOXwQABVIKAAuGAQaHAAjKCoAGhg6AAtHAGsAEREQEQAhbgjTMDyaOzt4gEoYAG9gGAaYbBAYADdOKAB3EOgIxBQMbDwCEi0pXSobesbCTs4QVJhvX38EQJ6oarrGneSRQlgAdSgYgHEAGT4AJXwUKm4Acwl3VBAAOnYAOQBlOFPP9CZAD6cE+QTC012u3aXQ2rAUvEEwjEUyhUJiVCgInSqLRdH2RxOF2ut3ij2eaHeX1+-0BQO+AAkAPJXcGQtENGHdULwwzKNTIsC4jkNDFYnG2Dn4g4wY5nS43ZBkhBPcgvKk-P4A4F5ACaQXQEJFjS5cLYfJMguFIrF2OtOxQdhENEwICNxrcKSopE6kS6MHQwiYngABgAiHx+AIEDZhmCcQiRUgtalaumgoJJVO04GMllBGB6bPaoF6g1LAAkNUjq3WoQAvpUQ5UbDt65LGj5JHtMHQXTkoEhSuV4kzygcWmwACytztjHt9zADodlCpUc74B4gFLwozWzEgGhUBB+32m0LeNIILI5fLcJL43v99wrkdUMd2CcPkRPpcv4drhuKrbi2wDtkAA

### 💻 Code

```ts

type IndexElementsConstructor = Uint32ArrayConstructor | Uint16ArrayConstructor | Uint8ArrayConstructor;

function test(componentType: number, chunkDataBin: ArrayBuffer) {
    let viewType: IndexElementsConstructor;

    switch (componentType) {
        case WebGL2RenderingContext.UNSIGNED_INT:
            viewType = Uint32Array;

            break;

        case WebGL2RenderingContext.UNSIGNED_SHORT:
            viewType = Uint16Array;

            break;

        case WebGL2RenderingContext.UNSIGNED_BYTE:
            viewType = Uint8Array;

            break;

        default:
            throw new Error(`"componentType" is not UNSIGNED_INT, UNSIGNED_SHORT or UNSIGNED_BYTE (${componentType})`);
    }

    const calculatedBufferOffset = 4;
    const calculatedBufferLength = 8;

    return new viewType(chunkDataBin, calculatedBufferOffset, calculatedBufferLength);
}

```

### 🙁 Actual behavior

![Image](https://github.com/user-attachments/assets/00b54c38-324a-4d48-84e0-6d8ed44526ca)

### 🙂 Expected behavior

![Image](https://github.com/user-attachments/assets/aa12a5ff-c568-49ee-a7b7-7823af339cf4)

### Additional information about the issue

If change code to simpler variant:
```ts
type IndexElementsConstructor = Uint32ArrayConstructor | Uint16ArrayConstructor | Uint8ArrayConstructor;

function test(componentType: number, chunkDataBin: ArrayBuffer) {
    const viewType: IndexElementsConstructor = Uint32Array;

    const calculatedBufferOffset = 4;
    const calculatedBufferLength = 8;

    return new viewType(chunkDataBin, calculatedBufferOffset, calculatedBufferLength);
}

```
newest TS version recognizes this.

**Comment by psnet** [comment]
As we can see 3rd overload:

`Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\lib.es5.d.ts`:

```ts

interface Uint32ArrayConstructor {
    readonly prototype: Uint32Array<ArrayBufferLike>;
    new (length: number): Uint32Array<ArrayBuffer>;
    new (array: ArrayLike<number>): Uint32Array<ArrayBuffer>;
    new <TArrayBuffer extends ArrayBufferLike = ArrayBuffer>(buffer: TArrayBuffer, byteOffset?: number, length?: number): Uint32Array<TArrayBuffer>;
    new (array: ArrayLike<number> | ArrayBuffer): Uint32Array<ArrayBuffer>;

    /**
     * The size in bytes of each element in the array.
     */
    readonly BYTES_PER_ELEMENT: number;

    /**
     * Returns a new array from a set of elements.
     * @param items A set of elements to include in the new array object.
     */
    of(...items: number[]): Uint32Array<ArrayBuffer>;

    /**
     * Creates an array from an array-like or iterable object.
     * @param arrayLike An array-like or iterable object to convert to an array.
     */
    from(arrayLike: ArrayLike<number>): Uint32Array<ArrayBuffer>;

    /**
     * Creates an array from an array-like or iterable object.
     * @param arrayLike An array-like or iterable object to convert to an array.
     * @param mapfn A mapping function to call on every element of the array.
     * @param thisArg Value of 'this' used to invoke the mapfn.
     */
    from<T>(arrayLike: ArrayLike<T>, mapfn: (v: T, k: number) => number, thisArg?: any): Uint32Array<ArrayBuffer>;
}
declare var Uint32Array: Uint32ArrayConstructor;
```

**Comment by jcalz** [comment]
This isn't a bug in TS, but it's unfortunate fallout of the new feature whereby [`TypedArray`s are generic over `ArrayBufferLike`](https://devblogs.microsoft.com/typescript/announcing-typescript-5-7/#typedarrays-are-now-generic-over-arraybufferlike) as implemented in #59417. You're running afoul of one of the caveats in the the support for [calling union types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-3.html#improved-behavior-for-calling-union-types) implemented in #29011:

> Only one type in the list of union members is allowed to have overloads, and only one type within the list of union members is allowed to have type parameters

So since the new constructors are generic, they have type parameters, and things go sideways. They wanted #59417 not to be a breaking change but I think there are these edge cases where it happens. You should probably change `IndexElementsConstructor` to 

```ts
type IndexElementsConstructor = new (buffer: ArrayBuffer, byteOffset?: number, length?: number) =>
    Uint32Array | Uint16Array | Uint8Array;
```

to make it work again.

[Playground link to code](https://www.typescriptlang.org/play/?target=9&ts=5.7.2#code/FAFwngDgpgBAkgOwCZQB4FEA2UC2UEgDOAwgPYKEgBOArgMYilUwC8MCUA7jABQBGNAGaCoVAFwwAglSoBDMACEhIqgBoYfMCCgB5YYSggA-BIQ0cfUeuwIA5iAAWJ9uctUAlKwB8wGH5gAqgCWBADMAEzScmAwAD6BISAAjABsUfJxCQQAHOlgANzAwII0CAxB5DDalDx0pDgQ5PggACqQUKauVjB0DqUA1gAisiCyCiESeUrCop4A3r7+2CAwAG5BXG3QEogoGNh4BCTklLQMTEX+MIScQSC9vHUNTQRbUPOLV350sgYwAOpQPgAcQAMuEAEr4FBUEK2MgENAgAB0AQAcgBlODAtHoQYAfTgaJaYk+Xyu6027VYWRAETyhTJ5L8fCoUFk-UZzJ6v1ggJB4KhyFEcIR2lQKPRWJxePxGIAEjoISSmczKZw3jTggRUgzLtz-Kz2Zz9eSfn9+WDIdCRXYxUjUZjsbiCQoAJotdCkg3+dWatjakC5GTyLk+jRsjlh8koQSyGiYEDe8OOKikbgcbjoGRMHgAAwARE9GhxXu0CzAgoR2KQVlLnbKiS11PWZQSFUqWjAmIEnW38e7PbwACRzYsvVrtAC+7jz7kKVynpp6JxWP0wdATIygSGmKj0ggMKzYABYF-46hQ17IN1vtLvlKJQfh7A4adlozA2SAaFQEOwuDWDYNXaWo+gQIYRjGEJ1HXTdMG3B8ZioA8j1gm94MQvcnxfRx52AJciiAA)

**Comment by rubick24** [comment]
I’m experiencing same problem in ts 5.7 when extending TypedArray class like this:
https://www.typescriptlang.org/play/?target=99#code/KYDwDg9gTgLgBAYwDYEMDOa4A06hsAOwBNMAxJCFGAZgCYBBKKFATzgG8AoORCAtGFACuCGNAAUMAFxwADHAA+cAIyK4tAJQduPOGgDuASxgIAFnElauu3QnTA5UnTZ5ohYYFHHKNzlwCMoYBQAaz8eOzQHZScXXTcPLwJgfThGZhYAISEAMxzPcQ0AGjkSn3DdQOCwuKJgHJQhJGkK13cC5NSAZVMUIKJ01my8guLSlV84nirQvwBfHQWFoA

**Comment by psnet** [comment]
@jcalz thanks for explaining. Sadly that during https://github.com/microsoft/TypeScript/pull/59417 were not implemented better solutions and when for union types caveats. Because of that all together code in the example above feels like tricky. Or you need to write code that will satisfy TS, code for TS, not for you 😢

**Comment by psnet** [comment]
Now if we want `BYTES_PER_ELEMENT` from 
```ts
type IndexElementsConstructor = Uint32ArrayConstructor | Uint16ArrayConstructor | Uint8ArrayConstructor;

let viewType: IndexElementsConstructor;
...
viewType.BYTES_PER_ELEMENT
```
things become more complicated.

**Comment by RyanCavanaugh** [comment]
@psnet See https://github.com/Microsoft/TypeScript/wiki/FAQ#this-is-closed-but-should-be-open-or-vice-versa

**Comment by rbuckton** [comment]
When you union constructor types, generic signatures must match exactly. Since each constructor type in the union produces a different return type, they are excluded from the resulting set. In the long term, I can look into adding non-generic overloads for these cases, assuming its feasible to do so without introducing further breaks. In the short term, @jcalz [suggestion](https://github.com/microsoft/TypeScript/issues/60745#issuecomment-2538876758) is a good workaround.
