### ISSUE TITLE
tsc cannot resolve the node temp module

### ISSUE THREAD

**Issue by aeisenberg** [Microsoft/TypeScript#6121]
I am trying to use [node temp](https://github.com/bruce/node-temp/), but tsc is not finding the module. When I use this module in a raw javascript project, I have no problems.

I am attaching a very simple project that illustrates the problem. To reproduce:

1. `npm install temp`
2. create `file.ts` in same location with the following contents: `import temp = require('temp');`
4. `tsc --module commonjs file.ts`:
5. **BUG:** compiler output is:

>  file.ts(1,23): error TS2307: Cannot find module 'temp'.

You can see that this module is actually installed by running node from the terminal in the same directory:

```
$ node
> console.log(require('temp'))
{ dir: '/var/folders/36/yjgv05hn78b4xn331jdt8klrcvt5zc/T',
  track: [Function],
  mkdir: [Function: mkdir],
  mkdirSync: [Function: mkdirSync],
  open: [Function: open],
  openSync: [Function: openSync],
  path: [Function],
  cleanup: [Function: cleanup],
  cleanupSync: [Function: cleanupSync],
  createWriteStream: [Function: createWriteStream] }
```
Is the module itself somehow malformed?

**Comment by DanielRosenwasser** [comment]
You'll need to declare the structure of the `"temp"` module with a `.d.ts` file.

As a workaround, you can also just write something like the following:

```ts
declare function require(moduleName: string): any;

var temp = require("temp");
```

**Comment by aeisenberg** [comment]
Hmmm...it works if I use `var` instead of `import`. Why is that?

**Comment by DanielRosenwasser** [comment]
My understanding is that when TypeScript originally did imports, we had AMD and CommonJS. It's not entirely clear when you're using one and not the other, and users often want to target both, so `import temp = require("temp")` was created as a specialized syntax.

As a side note, I'm working on a definition for you right now since this seems to be a simple-enough module to type. :smiley:

**Comment by DanielRosenwasser** [comment]
@aeisenberg can you check out https://github.com/DefinitelyTyped/DefinitelyTyped/pull/7234 and tell me if that type definition looks okay?

**Comment by aeisenberg** [comment]
Commented on the commit. Looks great to me.

So, when using commonjs, are we better off using `var` or `import`? We had been using import, but it seems like there's a problem with that.

**Comment by DanielRosenwasser** [comment]
Alright, so my definitions for the `temp` library have gone in. Here's what you should do from here:

1. Install `tsd` by running `npm install tsd`
2. Use `tsd` to grab the type definitions by running `tsd install temp --save`
3. Add `typings/tsd.d.ts` to the list of files you're compiling.
4. Use `import * as temp from "temp";`

Let me explain each of these so I'm not just pushing you into a dark room and telling you to try and find the lights:
_____________

(1) tsd is sort of like npm for definition management. It's managed by DefinitelyTyped, a community dedicated to making distributing typings easier.

_____________

(2) `tsd install temp` will grab the typings for `temp`. Those typings will be placed in a folder called `typings`, where a file called `tsd.d.ts` will also be created.

`--save` will create a `tsd.json` file so that you can run `tsd install` on any computer and all your dependencies will get grabbed. It's very similar to a `package.json` file.

As a note, you shouldn't check in your `typings` folder to source control, just like you wouldn't put `node_modules` under source control either.

_____________

(3) Recall that `tsd install` created a `tsd.d.ts` as well. That file refers to all the typings you installed earlier.

_____________

(4) JavaScript introduced a new and standardized import syntax, so what we all should be using is

```ts
import * as temp from "temp";
```

However, there are certain times when that won't entirely work. If you've ever seen something like

```js
module.exports = function Foo {

}
```

the way you'll need to import that is using the older style import syntax that TypeScript supported

```ts
import temp = require("temp");
```

**Comment by aeisenberg** [comment]
Makes sense. Thanks for your help. Using it now. It's still a bit confusing on how many different ways there are to import modules. But this is probably not the proper forum to ask the question. I'll get a stackoverflow question together about this.

**Comment by DanielRosenwasser** [comment]
Yup, StackOverflow and our [Gitter channel](https://gitter.im/Microsoft/TypeScript) are usually better venues for this sort of thing.

Modules are a surprisingly subtle in JS, and it's pretty common to discover how when starting with TypeScript. We're in the process of trying to add more documentation on it (https://github.com/Microsoft/TypeScript-Handbook).
