### ISSUE TITLE
Completion fails to find subsequent declaration in incomplete ternary

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#6127]
``` ts
1 ? f // does not work the autocompletion, `func` cannot select.
1 ? 1 : f // work the autocompletion, `func` can select.

function func() {}
```

Divides #6079.

**Comment by DanielRosenwasser** [comment]
Specifically, you will only see this if you have one ternary at a time. In other words, this works:

```ts
1 ? 1 : f/**/

function func() {}
```

and this does not work:

```ts
1 ? f/**/

function func() { }
```

I think this is actually due to the parse error where we expect a `:`, and then assume we must have a function expression in the false branch. Since a function expression doesn't create a binding in the rest of the function, it won't show up in your completion list.

I wonder if a reasonable thing to do would be to parse out a missing node if the colon is missing and the following token is on the next line. It'd be reasonable to try it out.

**Comment by falsandtru** [comment]
Sorry for my poor English. Thanks for your fix.

**Comment by DanielRosenwasser** [comment]
It's fine, I knew what you meant, I was just changing the title so whoever works on this knows exactly what the problem is. :smile:

**Comment by mhegazy** [comment]
thanks @Kingwl !
