### ISSUE TITLE
allow constants for string literals types

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#6151]
``` typescript
const vow = 'will never change';
let promise: vow;
```

**Comment by RyanCavanaugh** [comment]
We can't do this since it would be a breaking change -- `vow` has not previously introduced an entry in the type namespace, so doing so now would mean random types would start getting shadowed.

`typeof vow` should do what you want here (if we made `const`s be of their string literal type  @DanielRosenwasser please confirm?).

**Comment by aleksey-bykov** [comment]
> typeof vow should do what you want here (if we made consts be of their string literal type

in the expression context `typeof vow` gets me `"string"`
in the type expression context it gets me "will never change", but it's a **type** which I cannot assign to a variable

**Comment by DanielRosenwasser** [comment]
Like @RyanCavanaugh said, in order to do `typeof vow`, you'd need #5796. That said, I don't know if that PR will go in. The behavior isn't entirely ideal because it's not clear when you want the literal type and not `string`.

**Comment by mhegazy** [comment]
Here is the proposal: https://github.com/Microsoft/TypeScript/issues/6167#issuecomment-171455369

**Comment by sceutre** [comment]
What about allowing interpolated strings as string literal types.  So:
```
const vow = "will never change";
let promise: `${vow}`;
```

**Comment by mhegazy** [comment]
The issue in the OP should be fixed by https://github.com/Microsoft/TypeScript/pull/10676

Allowing string interpolation, or any form of string manipulation in type positions is not something we are looking to allow.

for this specific example, use `typeof` operator, e.g. `let promise: typeof vow;`  and this should be `"will never change"`.

**Comment by mhegazy** [comment]
@aleksey-bykov do you agree this proposal is covered by #10676 and `typeof`?

**Comment by aleksey-bykov** [comment]
yes, it's solved, please clise
