### ISSUE TITLE
Remove restriction of properties overriding prototype methods

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#6154]
We currently enforce this rule:

``` ts
class Base {
  foo() {
  }
}

class Derived extends Base {
  // Error, cannot override method with property
  foo: () => { };
}

```

This breaks two real scenarios:
- You can't declare 'foo' as a property and then mix it in later (#6147)
- You need to implement `foo` as an arrow function because you have some unbound callers that your base class didn't

The reverse case is important to continue to enforce, but no one can remember why we have this rule.

**Comment by RyanCavanaugh** [comment]
Pinging @bterlson to make sure we're not forgetting some weird edge case before simply removing this error

**Comment by bterlson** [comment]
I can't think of why this should be an error (it isn't with ES classes + class property declarations proposal, either).

**Comment by DickvdBrink** [comment]
@RyanCavanaugh, maybe the reason was because it is a bit dangerous to use them in the constructor itself? If they where both methods it worked as expected but with the base a method and the derived a property the results are different.
Note that the code you gave (which I slightly modified) does transpile but the result is Constructor -> Base instead of Constructor -> Derived. Looking at the transpiled code it is obvious but from the TS code perspective it doesn't (might be just me).
Just guessing here though ;)
```
class Base {
	constructor() {
		alert("constructor")
		this.foo();
	}
  foo () {
	  alert("BASE")
  }
}

class Derived extends Base {
  // Error, cannot override method with property
  foo =  () => { alert("Derived"); };
}

new Derived();
```

**Comment by RyanCavanaugh** [comment]
I'd call it mildly surprising, relative to what people's random expectations of initialization order seem to be :wink:

**Comment by cameron-martin** [comment]
I can have a look at this one, as my first issue :)
