### ISSUE TITLE
Simple encoding of sum types causes strange error

### ISSUE THREAD

**Issue by jhp** [Microsoft/TypeScript#6158]
The following code fails with some bizarre errors, like "Maybe is not callable," in typescript 1.7.5.

(see below for updated code, this version had a bug)

**Comment by jhp** [comment]
fail.ts(25,12): error TS2322: Type 'boolean' is not assignable to type 'Maybe<{ out<Z>(ft: (t: T) => Z, fs: (s: S) => Z): Z; }>'.
      Property 't' is missing in type 'Boolean'.
    fail.ts(25,20): error TS2348: Value of type 'typeof Maybe' is not callable. Did you mean to include 'new'?
    fail.ts(27,47): error TS2322: Type 'Maybe<{ out<Z>(ft: (t: S) => Z, fs: (s: {}) => Z): Z; }>' is not assignable to type 'Maybe<{ out<Z>(ft: (t: T) => Z, fs: (s: S) => Z): Z; }>'.
      Type '{ out<Z>(ft: (t: S) => Z, fs: (s: {}) => Z): Z; }' is not assignable to type '{ out<Z>(ft: (t: T) => Z, fs: (s: S) => Z): Z; }'.
        Types of property 'out' are incompatible.
          Type '<Z>(ft: (t: S) => Z, fs: (s: {}) => Z) => Z' is not assignable to type '<Z>(ft: (t: T) => Z, fs: (s: S) => Z) => Z'.
            Types of parameters 'ft' and 'ft' are incompatible.
              Type '(t: S) => any' is not assignable to type '(t: T) => any'.
                Types of parameters 't' and 't' are incompatible.
                  Type 'S' is not assignable to type 'T'.

**Comment by jhp** [comment]
my mistake

**Comment by jhp** [comment]
I think my code is correct now, the problem is still present.

    function just<T>(t: T) {
        return new Maybe(t) }

    function nothing<T>() { return new Maybe<T>() }

    class Maybe<T> {
        private t: T
        constructor(t: T = null) { this.t = t }
        fmap<U>(fn: (t:T) => U) : Maybe<U> {
            if(this.t === null) {
                return nothing<U>() }
            else {
                return just<U>(fn(this.t)) }} }

    type Either<T,S> = {out<Z>(ft : (t:T) => Z, fs: (s:S) => Z) :  Z}

    function inLeft<T,S>(t: T) : Either<T,S> {
        return {out<Z>(ft: (t:T) => Z, fs: (s:S) => Z) : Z { return  ft(t) }} }
    function inRight<T,S>(s: S) : Either<T,S> {
        return {out<Z>(ft: (t:T) => Z, fs: (s:S) => Z) : Z { return  fs(s) }} }


    function dist<T,S>(v : Either< Maybe<T>, Maybe<S> >) : Maybe< Either<T,S> > {
        return v.out < Maybe < Either < T , S > > (
            (t: Maybe<T>) : Maybe<Either<T,S>> => t.fmap(inLeft),
            (s: Maybe<S>) : Maybe<Either<T,S>> => s.fmap(inRight) ) }


The following errors are given:

    fail.ts(25,12): error TS2322: Type 'boolean' is not assignable to type 'Maybe<{ out<Z>(ft: (t: T) => Z, fs: (s: S) => Z): Z; }>'.
      Property 't' is missing in type 'Boolean'.
    fail.ts(25,20): error TS2348: Value of type 'typeof Maybe' is not callable. Did you mean to include 'new'?

**Comment by Arnavion** [comment]
The error about boolean is because you have unmatched `<>` in the `v.out` line. Fixed code is at http://www.typescriptlang.org/Playground#src=function%20just%3CT%3E(t%3A%20T)%20%7B%0A%20%20%20%20return%20new%20Maybe(t)%0A%7D%0A%0Afunction%20nothing%3CT%3E()%20%7B%20return%20new%20Maybe%3CT%3E()%20%7D%0A%0Aclass%20Maybe%3CT%3E%20%7B%0A%20%20%20%20private%20t%3A%20T%0A%20%20%20%20constructor(t%3A%20T%20%3D%20null)%20%7B%20this.t%20%3D%20t%20%7D%0A%20%20%20%20fmap%3CU%3E(fn%3A%20(t%3AT)%20%3D%3E%20U)%20%3A%20Maybe%3CU%3E%20%7B%0A%20%20%20%20%20%20%20%20if%20(this.t%20%3D%3D%3D%20null)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20nothing%3CU%3E()%0A%09%09%7D%0A%20%20%20%20%20%20%20%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20just%3CU%3E(fn(this.t))%0A%09%09%7D%0A%09%7D%0A%7D%0A%0Atype%20Either%3CT%2C%20S%3E%20%3D%20%7B%0A%09out%3CZ%3E(ft%3A%20(t%3AT)%20%3D%3E%20Z%2C%20fs%3A%20(s%3AS)%20%3D%3E%20Z)%3A%20Z%3B%0A%7D%0A%0Afunction%20inLeft%3CT%2C%20S%3E(t%3A%20T)%20%3A%20Either%3CT%2C%20S%3E%20%7B%0A%20%20%20%20return%20%7B%0A%09%09out%3CZ%3E(ft%3A%20(t%3AT)%20%3D%3E%20Z%2C%20fs%3A%20(s%3AS)%20%3D%3E%20Z)%20%3A%20Z%20%7B%0A%09%09%09return%20ft(t)%3B%0A%09%09%7D%0A%09%7D%0A%7D%0A%0Afunction%20inRight%3CT%2C%20S%3E(s%3A%20S)%20%3A%20Either%3CT%2C%20S%3E%20%7B%0A%20%20%20%20return%20%7B%0A%09%09out%3CZ%3E(ft%3A%20(t%3AT)%20%3D%3E%20Z%2C%20fs%3A%20(s%3AS)%20%3D%3E%20Z)%20%3A%20Z%20%7B%0A%09%09%09return%20fs(s)%3B%0A%09%09%7D%0A%09%7D%0A%7D%0A%0A%0Afunction%20dist%3CT%2C%20S%3E(v%20%3A%20Either%3CMaybe%3CT%3E%2C%20Maybe%3CS%3E%3E)%3A%20Maybe%3CEither%3CT%2C%20S%3E%3E%20%7B%0A%20%20%20return%20v.out%3CMaybe%3CEither%3CT%2C%20S%3E%3E%3E(%0A%20%20%20%20%20%20%20%20(t%3A%20Maybe%3CT%3E)%3A%20Maybe%3CEither%3CT%2CS%3E%3E%20%3D%3E%20t.fmap%3CEither%3CT%2C%20S%3E%3E(inLeft)%2C%0A%20%20%20%20%20%20%20%20(s%3A%20Maybe%3CS%3E)%3A%20Maybe%3CEither%3CT%2CS%3E%3E%20%3D%3E%20s.fmap%3CEither%3CT%2C%20S%3E%3E(inRight)%0A%09)%0A%7D%0A

**Comment by jhp** [comment]
Oy, right you are.
