### ISSUE TITLE
Generic function types cannot merge using union types

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#6160]
``` ts
type f = {
  (): number;
} | {
  (): string;
}

var f: f;
f(); // valid

type g = {
  <T>(): number;
} | {
  <T>(): string;
}

var g: g;
g(); // error
```

``` ts
type f = {
  (): any;
  (v: any): any;
} | {
  (v?: any): any;
}

var f: f;
f(); // valid

type g = {
  <T>(): any;
  <T>(v: any): any;
} | {
  <T>(v?: any): any;
}

var g: g;
g(); // error
```

**Comment by weswigham** [comment]
This is by design, apparently. We have this comment in the [related code](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/checker.ts#L3493):
```ts
        // The signatures of a union type are those signatures that are present in each of the constituent types.
        // Generic signatures must match exactly, but non-generic signatures are allowed to have extra optional
        // parameters and may differ in return types. When signatures differ in return types, the resulting return
        // type is the union of the constituent return types.
        function getUnionSignatures(types: Type[], kind: SignatureKind): Signature[] {
```

However, I'm not sure if we have good spec/test coverage for this, and I think attempting quick info on the function call in [this example](http://www.typescriptlang.org/Playground#src=type%20call1%20%3D%20%7B%0A%20%20%3CT%3E(a%3A%20T%2C%20v%3A%20any)%3A%20any%3B%0A%7D%3B%0A%0Atype%20call2%20%3D%20%7B%0A%20%20%3CT%3E(a%3A%20T%2C%20v%3A%20any)%3A%20any%3B%0A%7D%3B%0A%0Atype%20g%20%3D%20call1%20%7C%20call2%3B%0A%0Avar%20n%3A%20g%3B%0An(42%2C%2012)%3B%20%2F%2F%20error) seems to freeze the language service.

Though this behavior is currently by design, we could possibly? do better here.

**Comment by falsandtru** [comment]
Shall I change this issue to a proposal?

**Comment by falsandtru** [comment]
Please change this issue title if you need.

**Comment by RyanCavanaugh** [comment]
This is no longer an error
