### ISSUE TITLE
Unassignable type error when trying to access a class's static method from iVar reference.

### ISSUE THREAD

**Issue by Think7** [Microsoft/TypeScript#6170]
The below example attempts to access a public static method on a class whose type is held in an ivar;

If i compare this._type with MyClass, the objects are identical and the method DOES exist and can be called. It's only TSC that's saying it doesn't exist. Am i doing something wrong or is there a workaround for this situation?

```
interface ClassOf<T> { new(...args: any[]): T; }

class MyClass {
    public static aStaticMethod(): void {/*... blah ...*/ }
}

class GenericClass<T extends MyClass> extends Array<T> {
    private _type: ClassOf<T>;
    public get type(): ClassOf<T> { return this._type; };

    public instanceMethod(): void {
        let theClass = this._type;
        let tmp: MyClass = <MyClass>theClass.aStaticMethod();
        // Causes Error ----------------------- ^^^^^^^^
        // Error:(400, 27) TS2339: Property 'aStaticMethod' does not exist on type 'ClassOf<T>'.

        MyClass.aStaticMethod();
        // ^^^ Works Great!
    }

    constructor(aClass: ClassOf<T>) {
        super();
        this._type = aClass;
    }
}
```

**Comment by thorn0** [comment]
Instead of
`<MyClass>theClass.aStaticMethod();`
you should've written
`(<MyClass>theClass).aStaticMethod();`
or (which is the same thing)
`(theClass as MyClass).aStaticMethod();`

Also this expression doesn't return MyClass, so you can't assign it to `let tmp: MyClass`.

**Comment by DanielRosenwasser** [comment]
First off, are you sure you want to cast `theClass.aStaticMethod()` as a `MyClass`? It returns `void` according to your signature.

For now, forget everything you know about static method lookup in other languages.

A class introduces two separate types: the instance side and the static side. The static side holds any static properties and is also a constructor function. The instance side is the type created by the constructor function.

The instance side always gets the same name as the class itself. So in this case, the type name of the instance is `MyClass`. The static side actually gets an anonymous type, however, you can always refer to that type using `typeof MyClass` (because `MyClass` is the name of the constructor function as well).

**Comment by Think7** [comment]
Wow, Thank You!

- Yes! Forgot the parentheses. This example was semi copied from production code about 45 seconds before going to bed. Shame on me!

- Completely missed how / when / why to use typeof for this case. Looking over your example now it makes perfect sense. Will have another read through the handbook.

I've changed the title of this issue to better reflect it being a "why doesn't this work" question instead of a bug.

If in the future i am in a situation like this and am unable to work out why or how to do something strictly TS related, May i create a new question-issue?

**Comment by Think7** [comment]
Below is a clearer example of what i'm trying to do:

```
interface ClassOf<T> { new(...args: any[]): T; }

class Model {
    public static fromData(data: Object): Model {
        let inst = new Model();
        // ... Populate the model ... //
        return inst;
    }
}

class RefArray<T extends Model> extends Array<ObjectID> {
    private _type: ClassOf<T>;
    public get type(): ClassOf<T> { return this._type; };

    public resolve(): Array<T> {
        let ModelClass = <typeof Model>this._type;
        //               ^^^ This throws error
        // Error:(404, 26) TS2352: 
        // - Neither type 'ClassOf<T>' nor type 'typeof Model' is assignable to the other.
        // - Property 'fromData' is missing in type 'ClassOf<T>'.
        return this.map((cData: Object): T => {
            return <T>ModelClass.fromData(cData);
        });
    }

    constructor(aClass: ClassOf<T>) {
        super();
        this._type = aClass;
    }
}
```

**Comment by DanielRosenwasser** [comment]
In general, these questions are better fit for StackOverflow, but since you're already here it's not a problem. :smile: 

This is an annoying subtlety. Basically type assertions check assignability in both directions. `this._type` can't be assigned to `ClassOf<T>`, because `T` might be a more derived type when you instantiate it. The other way around, `ClassOf<T>` can't be assigned to `this._type` because it's missing the static method.

You could perform an assertion to `any` and then to `ClassOf<T>` but I don't necessarily recommend that.

What about moving `typeof Model` to your type parameter?

```ts
class RefArray<TModel extends typeof Model> extends Array<ObjectID> {
    private _type: TModel;
    public get type(): TModel { return this._type; };

    public resolve(): Array<TModel> {
        let ModelClass = <TModel>this._type;
        return this.map((cData: Object): TModel => {
            return <TModel>ModelClass.fromData(cData);
        });
    }

    constructor(aClass: TModel) {
        super();
        this._type = aClass;
    }
}
```
