### ISSUE TITLE
Contextually type the rightmost operand of comma operators and logical 'AND's

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#6199]
See https://github.com/Microsoft/TypeScript/pull/6196#issuecomment-166480593

**Comment by weswigham** [comment]
`&&` is probably important since we use it's type in narrowing. Also i think its required to support the "short circuiting as ternary" pattern - `if ("foo"  === a && "foo" || "bar") `. If the `&&` doesn't get contextually typed here, I think we get `string | "bar"` for the rhs type, rather than `"foo" | "bar"`.

**Comment by DanielRosenwasser** [comment]
You'd just get `string` actually. Did you mean `if ("foo" === a && a || "bar")`, but with your type narrowing change applied?

**Comment by weswigham** [comment]
Maybe? I'm just pretty sure the rhs operand of `&&` should get contextually typed, mostly so you get consistent results with narrowing within/involving compound binary logic. In my example above I'm pretty sure I want the type of the RHS expression to be contextually typed as `"foo"|"bar"` rather than as `string` because this matches how a functionally equivalent ternary would have worked. I think.

**Comment by weswigham** [comment]
So my point is that if in the statement `if ("foo" === a ? "foo" : "bar")` the RHS has type `"foo" | "bar"`,  the RHS of the statement `if ("foo" === a && "foo" || "bar")` should be the same. Mostly since if we plan to disallow `if ("foo" === a ? "baz" : "bar")` (as neither `"baz"` nor `"bar"` are assignable to type `"foo"`), it follows that `if ("foo" === a && "baz" || "bar")` should be the same type error by extension, since the expression is equivalent.

**Comment by DanielRosenwasser** [comment]
@weswigham Just to clarify, did you mean to parenthesize the conditional? In other words, by `"foo" === a ? "foo" : "bar"` you meant `"foo" === (a ? "foo" : "bar")`.

**Comment by weswigham** [comment]
Aye. Parenthesis.

**Comment by DanielRosenwasser** [comment]
I put out a fix for this with #6355.
