### ISSUE TITLE
Loop contains block-scoped variable 'i' referenced by a function in the loop

### ISSUE THREAD

**Issue by tcstory** [Microsoft/TypeScript#6219]
typescript version: 1.7.5

I have the following code,

```
function testing () {
    for (let i = 0; i < 5; i++) {
        setTimeout(function () {
            console.log(i);
        },0);
    }
}
```
when set the  target javascript version to es5, ts compiler reports the following error:

```
Error:(7, 5) TS4091: Loop contains block-scoped variable 'i' referenced by a function in the loop. This is only supported in ECMAScript 6 or higher.
```
but the compiled code is ok. and if I change the target javascript to es6, it won't have this error.

who can tell me why it give me the error? thanks!

**Comment by vladima** [comment]
the problem is that `let` in ES6 is block-scoped so in your code every iteration should capture its own value of `i` and the expected output is:
```
0
1
2
3
4
```
Prior to TypeScript 1.8 (that is the to-be-released version) we preserved ES6 semantic in downlevel emit using only renaming to resolve name collisions and it worked fine everywhere except loops. 
```ts
function testing() {
    for (var i = 0; i < 5; i++) {
        setTimeout(function () {
            console.log(i);
        }, 0);
    }
}
```
This is output for your example in TypeScript 1.7 and its behavior is different from the original code:
```
5
5
5
5
5
```
Reason why it happened - `var` is function scoped so all iterations of the loop work with the same variable.

This behavior is [fixed](https://github.com/Microsoft/TypeScript/issues/3915) in master bits, you can try it out using our nightly builds that are available as `typescript@next`on npm.

**Comment by tcstory** [comment]
thanks for your help
