### ISSUE TITLE
Rename members does not work on type argument values

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#6244]
```typescript
interface A {
    a: string;
}
function f(): Promise<A> {
    return Promise.resolve({
        a: '',
    });
}
```
Renaming `A.a` to `A.b` doesn't work on above example.

**Comment by tinganho** [comment]
The cursor could also be in both places. Both yield error result.

**Comment by DanielRosenwasser** [comment]
This is because we can't figure out `Promise<A>` is the type returned by `Promise.resolve` - it's just `Promise<{ a: string }>` which is structurally compatible. @RyanCavanaugh don't we have an issue for use-sites as an inference site for type arguments? I can't find it.

We should also consider a "Rename all structurally compatible types." option for rename.

**Comment by mhegazy** [comment]
We talked about this before, not sure if there is an issue for this though.

**Comment by mhegazy** [comment]
@DanielRosenwasser wanna file an issue for it?

**Comment by DanielRosenwasser** [comment]
Which issue specifically? Structural references, or adding inference sites?

**Comment by mhegazy** [comment]
structural references.

**Comment by DanielRosenwasser** [comment]
Done. See #6388.

**Comment by mhegazy** [comment]
We can close this one then?

**Comment by DanielRosenwasser** [comment]
Yup. The inference site idea was #5254 for future reference.
