### ISSUE TITLE
Decorator evaluation order

### ISSUE THREAD

**Issue by meirgottlieb** [Microsoft/TypeScript#6268]
In the [decorator evaluation order](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Decorators.md#decorator-evaluation), what is the reason that the class decorators are evaluated last?

Thanks!

**Comment by DanielRosenwasser** [comment]
It corresponds to the order in which the class itself is constructed. The class as a whole doesn't exist before static and instance members are declared. I think it's more or less a coin toss between constructor parameters and actual constructors, but it's probably more consistent and easier if the class decorator goes last.

Though @rbuckton and @vladima know more about this matter than I do.

**Comment by meirgottlieb** [comment]
That's helpful. Thanks.

**Comment by Arnavion** [comment]
Also, the only way for property decorators to propagate information to the class decorator would be if the class decorator ran after its property decorators. Similarly a function decorator has to run after its parameter decorators.

For constructor parameters vs constructors, it's probably because they behave the same as regular functions except constructors can't have decorators, so only constructor parameter decorators are considered in step 3.
