### ISSUE TITLE
Emit a helper for default imports based on if __esModule is specified

### ISSUE THREAD

**Issue by louy** [Microsoft/TypeScript#6296]
I think I'm running into a small bug here.

```ts
import React from 'react';
export = React;
```

With `allowSyntheticDefaultImports: true` and `module: commonjs` it compiles fine but I get the following output:

```js
var react_1 = require('react');
module.exports = react_1.default;
```

I believe it should be:

```js
var react_1 = require('react');
module.exports = react_1;
```

**Comment by DanielRosenwasser** [comment]
The idea is that your module loader (e.g. SystemJS) is going to do some special work to re-jigger your modules and give you the full module when you do a `default` import. Because this is the case, you might want to use a default import and have TypeScript understand that it's going to be the full module. However, our emit will not change, because the assumption is that the module loader will do this.

If your module loader doesn't do this, the flag should not be used.

See https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md#inter-format-dependencies.

**Comment by louy** [comment]
So babel [does this](https://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&code=import%20_%20from%20'underscore'%3B%0A) (i.e. the `_interopRequireDefault` helper.) I thought Typescript would do the same.

**Comment by DanielRosenwasser** [comment]
We could potentially do that. I'll change the issue to reflect that.

**Comment by louy** [comment]
I think just emitting the correct value (`require().default` vs `require()`) as it was described in the issue is better than using a helper because typescript already knows how the other module looks like. it's much cleaner and we have an advantage over babel here.

**Comment by louy** [comment]
so we can just use the same type interference logic that's used when `allowSyntheticDefaultImports` is enabled to decide whether `.default` should be added or not

**Comment by mhegazy** [comment]
We have had a long discussion around the use of __esmodule a while back when the ES6 module support was being implemented. you can see this discussion in https://github.com/Microsoft/TypeScript/issues/2242.

The flag `allowSyntheticDefaultImports`, is there to allow you to use old-style modules if the loader messes *generates* a default export for you. otherwise there is no way to use these modules correctly with such loaders (i.e. system js). 

if you are using commonJS, the module loader does not do any magic around default, so your import should not use `import r from "react"` instead you should use `import * as r from "react"`.
