### ISSUE TITLE
No compilation error on incorrect interface implementation

### ISSUE THREAD

**Issue by chel-man** [Microsoft/TypeScript#6298]
Environment: scientific linux 6, tsc 1.7.3
```typescript
interface Service {
    m(id:number):void
}

class ServiceImpl implements Service {
    m():void {}
}

**Comment by kitsonk** [comment]
Implementations are allowed to ignore arguments if they don't depend on them in the implementation.  I don't have a handy reference to quote it exactly.  But because TypeScript is structurally typed, both of those methods are structurally compatible.

**Comment by chel-man** [comment]
what is mean ".. if they don't depend on them in the implementation." ?

**Comment by kitsonk** [comment]
You have a method, which is ignoring the arguments passed to it, therefore it is allowed to ignore it but still be [structurally compatible](http://www.typescriptlang.org/Playground#src=interface%20Service%20%7B%0D%0A%20%20%20%20m(id%3A%20number)%3A%20void%3B%0D%0A%7D%0D%0A%0D%0Aclass%20ServiceImpl%20implements%20Service%20%7B%0D%0A%20%20%20%20m()%3A%20void%20%7B%7D%3B%0D%0A%7D%0D%0A%0D%0Aclass%20AnotherServiceImpl%20implements%20Service%20%7B%0D%0A%09m(id)%3A%20void%20%7B%20console.log(id)%3B%20%7D%3B%0D%0A%7D%0D%0A%0D%0Aclass%20BadServiceImpl%20implements%20Service%20%7B%0D%0A%09m(id%3A%20string)%3A%20void%20%7B%20console.log(id)%3B%20%7D%3B%0D%0A%7D%0D%0A%0D%0Aclass%20AndAnotherServiceImpl%20implements%20Service%20%7B%0D%0A%09m(id%3A%20number%2C%20...args%3A%20any%5B%5D)%3A%20void%20%7B%7D%0D%0A%7D%0D%0A%0D%0Aclass%20AnotherBadServiceImpl%20implements%20Service%20%7B%0D%0A%09m(id%3A%20number%2C%20foo%3A%20string)%3A%20void%20%7B%7D%3B%0D%0A%7D%0D%0A%0D%0Aclass%20ButThisWorksServiceImpl%20implements%20Service%20%7B%0D%0A%09m(id%3A%20number%20%3D%2012%2C%20...args%3A%20any%5B%5D)%3A%20void%20%7B%7D%3B%0D%0A%7D%0D%0A):

```typescript
interface Service {
    m(id: number): void;
}

class ServiceImpl implements Service {
    m(): void {};
}

class AnotherServiceImpl implements Service {
	m(id): void { console.log(id); };
}

class BadServiceImpl implements Service {
	m(id: string): void { console.log(id); };
}

class AndAnotherServiceImpl implements Service {
	m(id: number, ...args: any[]): void {}
}

class AnotherBadServiceImpl implements Service {
	m(id: number, foo: string): void {};
}

class ButThisWorksServiceImpl implements Service {
	m(id: number = 12, ...args: any[]): void {};
}
```

As you can see by the link to the playground, there are several ways structural typing works that many people might find surprising, but it is the best way to type ECMAScript, because of the way it behaves at runtime... All the implementations (except the bad ones) can fulfil the interface contract, and therefore are valid.

**Comment by vladima** [comment]
this behavior is by design, you can check [Type Relationships](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#311-type-relationships) section in the spec. The reason for this:
```ts
let s: Service = ...;
let si: ServiceImpl = ...
s = si;
s.m(10);
``` 
It is safe to invoke `s.m` when type of `s` is `ServiceImpl` since `ServiceImpl` ignored the argument. The opposite will not be true (i.e. if argument was omitted in `Service` but present in `ServiceImpl`) , because implementation will expect argument to be there but user have not chance to pass it.
