### ISSUE TITLE
Inconsistent narrowing of 'any' type

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#6301]
```typescript

let value1 : string | any;
if (typeof value1 === 'string') {
    value1 // <-- check me
}

let value2: Object | any;
if (value2 instanceof Object) {
    value2 // <-- check me
}

function isString(value: string | any) : value is string {
    return typeof value === 'string';
}
let value3: string | any;
if (isString(value3)) {
    value3 // <-- check me
}
```
Only the `typeof` query will narrow to a `non-any` type above.

**Comment by DanielRosenwasser** [comment]
I think `any` being in a union here is unrelated.

You don't want to narrow from `any` to `Object` because now you can effectively do nothing with your value. So in general, we don't narrow with `instanceof` type guards.

User-defined type guards need to exhibit the same behavior; however, we are considering narrowing from `any` for primitives, regardless of the type guard you use. See #5930 and #6015.

**Comment by tinganho** [comment]
Ok thanks @DanielRosenwasser. I have followed the discussion about `any` narrowing. Didn't know the rule applied to union consisting of type anys too.
