### ISSUE TITLE
Weird type-widening issue when using methods instead of function properties.

### ISSUE THREAD

**Issue by srijs** [Microsoft/TypeScript#6309]
Hi there.

I'm using the tsc compiler, version 1.8.0-dev.20151231, and I'm running into a weird issue where widening of structural types works when I'm defining a class with a function property, and fails when I'm replacing that function property by a "proper" method.

But see for yourself: [This](http://www.typescriptlang.org/Playground#src=class%20Predicate%3CT%2C%20X%3E%20%7B%0A%20%20constructor(private%20_run%3A%20(T)%20%3D%3E%20X)%20%7B%7D%0A%0A%20%20public%20run%3A%20(T)%20%3D%3E%20X%20%3D%20(v%3A%20T)%20%3D%3E%20%7B%0A%20%20%20%20return%20this._run(v)%3B%0A%20%20%7D%0A%0A%20%20public%20chain%3CY%3E(f%3A%20(X)%20%3D%3E%20Predicate%3CT%2C%20Y%3E)%3A%20Predicate%3CT%2C%20Y%3E%20%7B%0A%20%20%20%20return%20new%20Predicate((v%3A%20T)%20%3D%3E%20f(this.run(v)).run(v))%3B%0A%20%20%7D%0A%7D%0A%0Afunction%20fooIsEq(x%3A%20number)%3A%20Predicate%3C%7Bfoo%3A%20number%7D%2C%20boolean%3E%20%7B%0A%20%20return%20new%20Predicate((v)%20%3D%3E%20v.foo%20%3D%3D%3D%20x)%3B%0A%7D%0A%0Afunction%20barIsEq(x%3A%20number)%3A%20Predicate%3C%7Bbar%3A%20number%7D%2C%20boolean%3E%20%7B%0A%20%20return%20new%20Predicate((v)%20%3D%3E%20v.bar%20%3D%3D%3D%20x)%3B%0A%7D%0A%0Afunction%20fooAndBarEq(x%3A%20number)%3A%20Predicate%3C%7Bfoo%3A%20number%2C%20bar%3A%20number%7D%2C%20boolean%3E%20%7B%0A%20%20return%20fooIsEq(42).chain(()%20%3D%3E%20barIsEq(42))%3B%0A%7D
) is the version that compiles, and [this](http://www.typescriptlang.org/Playground#src=class%20Predicate%3CT%2C%20X%3E%20%7B%0A%20%20constructor(private%20_run%3A%20(T)%20%3D%3E%20X)%20%7B%7D%0A%0A%20%20public%20run(v%3A%20T)%3A%20X%20%7B%0A%20%20%20%20return%20this._run(v)%3B%0A%20%20%7D%0A%0A%20%20public%20chain%3CY%3E(f%3A%20(X)%20%3D%3E%20Predicate%3CT%2C%20Y%3E)%3A%20Predicate%3CT%2C%20Y%3E%20%7B%0A%20%20%20%20return%20new%20Predicate((v%3A%20T)%20%3D%3E%20f(this.run(v)).run(v))%3B%0A%20%20%7D%0A%7D%0A%0Afunction%20fooIsEq(x%3A%20number)%3A%20Predicate%3C%7Bfoo%3A%20number%7D%2C%20boolean%3E%20%7B%0A%20%20return%20new%20Predicate((v)%20%3D%3E%20v.foo%20%3D%3D%3D%20x)%3B%0A%7D%0A%0Afunction%20barIsEq(x%3A%20number)%3A%20Predicate%3C%7Bbar%3A%20number%7D%2C%20boolean%3E%20%7B%0A%20%20return%20new%20Predicate((v)%20%3D%3E%20v.bar%20%3D%3D%3D%20x)%3B%0A%7D%0A%0Afunction%20fooAndBarEq(x%3A%20number)%3A%20Predicate%3C%7Bfoo%3A%20number%2C%20bar%3A%20number%7D%2C%20boolean%3E%20%7B%0A%20%20return%20fooIsEq(42).chain(()%20%3D%3E%20barIsEq(42))%3B%0A%7D) is the version that doesn't.

What is the difference here? Is this a bug in the type inference engine?

**Comment by DanielRosenwasser** [comment]
This doesn't have to do with widening.

The problem is that you typed `run` as `(T) => X` which is ***actually*** `(T: any) => X`. [Parameter names are required in function type literals](https://github.com/Microsoft/TypeScript/issues/3081). You can catch this more easily by using `--noImplicitAny`.

You'll see [the version that errors the same way here](http://www.typescriptlang.org/Playground#src=class%20Predicate%3CT%2C%20X%3E%20%7B%0A%20%20constructor(private%20_run%3A%20(x%3A%20T)%20%3D%3E%20X)%20%7B%7D%0A%0A%20%20public%20run%3A%20(x%3A%20T)%20%3D%3E%20X%20%3D%20(v%3A%20T)%20%3D%3E%20%7B%0A%20%20%20%20return%20this._run(v)%3B%0A%20%20%7D%0A%0A%20%20public%20chain%3CY%3E(f%3A%20(x%3A%20X)%20%3D%3E%20Predicate%3CT%2C%20Y%3E)%3A%20Predicate%3CT%2C%20Y%3E%20%7B%0A%20%20%20%20return%20new%20Predicate((v%3A%20T)%20%3D%3E%20f(this.run(v)).run(v))%3B%0A%20%20%7D%0A%7D%0A%0Afunction%20fooIsEq(x%3A%20number)%20%7B%0A%20%20return%20new%20Predicate%3C%7Bfoo%3A%20number%7D%2C%20boolean%3E(v%20%3D%3E%20v.foo%20%3D%3D%3D%20x)%3B%0A%7D%0A%0Afunction%20barIsEq(x%3A%20number)%20%7B%0A%20%20return%20new%20Predicate%3C%7Bbar%3A%20number%7D%2C%20boolean%3E(v%20%3D%3E%20v.bar%20%3D%3D%3D%20x)%3B%0A%7D%0A%0Afunction%20fooAndBarEq(x%3A%20number)%3A%20Predicate%3C%7Bfoo%3A%20number%2C%20bar%3A%20number%7D%2C%20boolean%3E%20%7B%0A%20%20return%20fooIsEq(42).chain(()%20%3D%3E%20barIsEq(42))%3B%0A%7D).

**Comment by srijs** [comment]
Thanks, I enabled `--noImplicitAny` for building my project now.

Out of interest, is there a way I can make this program typecheck without any? Why is TypeScript not able to widen `{foo: number}` contra-variantly to `{foo: number, bar: number}` to make it assignable?

**Comment by DanielRosenwasser** [comment]
Part of it is the way we select inference points, and the flow of direction between types. Supporting many different inference sites can be complex.

One way to get what you want is to make `fooIsEq` and `barIsEq` generic. That way you can say ahead of time what type you're working with.

```ts
function fooIsEq<T extends { foo: number }>(x: number) {
  return new Predicate<T, boolean>(v => v.foo === x);
}

function barIsEq<T extends { bar: number }>(x: number) {
  return new Predicate<T, boolean>(v => v.bar === x);
}

function fooAndBarEq(x: number) {
  return fooIsEq<{foo: number; bar: number }>(42)
  			.chain(() => barIsEq(42));
}
```

Another approach is to say that `chain` can build types up with an intersection type:

```ts
class Predicate<T, X> {
  constructor(private _run: (x: T) => X) {}

  public run: (x: T) => X = (v: T) => {
    return this._run(v);
  }

  public chain<U, Y>(f: (x: X) => Predicate<U, Y>) {
    return new Predicate((v: U & T) => f(this.run(v)).run(v));
  }
}

function fooIsEq(x: number) {
  return new Predicate<{foo: number}, boolean>(v => v.foo === x);
}

function barIsEq(x: number) {
  return new Predicate<{bar: number}, boolean>(v => v.bar === x);
}

function fooAndBarEq(x: number) {
  return fooIsEq(42).chain(() => barIsEq(42));
}
```

This will allow you to compose predicate functions easily, but you're more prone to accidentally passing in an incorrectly typed function.

By the way, does `Predicate` really need two type parameters? Usually they just return `boolean`s.

**Comment by srijs** [comment]
Thanks a lot. The `&` intersection type is pretty cool. Tbh, I had looked for a dual to `|` previously, but wasn't able to find anything. Is there documentation for in the current TypeScript spec for it? I'd be especially interest in how co & contravariance are solved for it how it plays together with the bivariance of function arguments. Is that why you were saying "[I was] more prone to accidentally passing in an incorrectly typed function." with this approach?

**Comment by DanielRosenwasser** [comment]
We're in the process of documenting things a little more, and the spec will have it soon as well.

What I meant is that you can `chain` with basically any single-argument function. I guess in practice it won't be a problem, since you'll get an error when you actually try to `run` with some value that isn't compatible.
