### ISSUE TITLE
inference strangeness - 4

### ISSUE THREAD

**Issue by zpdDG4gta8XKpMCd** [microsoft/TypeScript#6329]
``` typescript
interface A { x: number; }
interface B { y: number; }
interface C { z: number; }

function fn<a, b, c>(one: a & c, two: b & c): c {
    return undefined;
}
let one: A & C;
let two: B & C;
let result = fn(one, two); // <-- expected type C, actual {}
```

**Comment by ahejlsberg** [comment]
Our inference algorithm makes no inferences when the target is a union or intersection involving more than one type parameter because it is not clear how the source type should be "carved up" into more than one target type. There may be cases such as your example where you could *perhaps* argue for a certain pattern of "carving", but I just don't see how you meaningfully solve it for the general case. Did you have a particular algorithm in mind?

**Comment by aleksey-bykov** [comment]
Here are some of my naive thoughts. Let's consider a straightforward situation:

```
interface A { x: number; w: string; }
interface B { y: number; w: string; }
interface C { z: number; }
function fn<a, b, c>(one: a & c, two: string, three: b & c) : c {};
let result = fn(<A & C> undefined, 'hey', <B & C> undefined);
```

Need to deduce `c`. 
1. Get all unresolved bare types from the original signature that mention the type in question `c`: `a & c`, `b & c`
2. Get all constituent types from 1: `a`, `b`, `c`
3. Try to resolve (instantiate?) types from step 1 using all available information from the current context, so signatures and properties are known as much as possible: `a & c` - '{x : number; z: number}`, `b & c` - `{y: number; z: number; }`
4. Out of what we got at step 3 try to find an intersection (common denominator) type: `{ z: number; w: string; }`
5. If there is a non-empty type it can be used as an answer, but chances are it might be more elaborate than we expect (`w` property).
6. Narrow the type from step 5 to the widest type out of the constituent types from step 2 that participate in types from step 1.


How is this for a start?
