### ISSUE TITLE
Union Type Order Strangeness

### ISSUE THREAD

**Issue by kitsonk** [Microsoft/TypeScript#6336]
I tried to see if there was an issue for this, but I couldn't and may have missed why there is a reason for this, but it is suprising.  It seems that when you have a function interface as the second member of the union, you get a very [cryptic error](http://www.typescriptlang.org/Playground#src=type%20Foo%20%3D%20string%20%7C%20(item%3A%20string)%20%3D%3E%20boolean%3B%20%2F%2F%20Cannot%20find%20name%20'item'%0A%0Atype%20Bar%20%3D%20(item%3A%20string)%20%3D%3E%20boolean%20%7C%20string%3B%20%2F%2F%20Works!%0A), but you change the order and all sins are forgiven:

```typescript
type Foo = string | (item: string) => boolean; // Cannot find name 'item'

type Bar = (item: string) => boolean | string; // Works!
```

If there is a valid reason, you would think at least a more informative error could be given.

**Comment by ivogabe** [comment]
Function types should be wrapped in parenthesis in such case. Bar is actually a function (that returns a boolean or string). The error message isn't really helping here though.

**Comment by kitsonk** [comment]
@ivogabe you are right... I mis-read my own code.  That is not only surprising, but dangerous. :-S

**Comment by RyanCavanaugh** [comment]
We argued a lot about this when union types came around because there's no obviously-correct interpretation of `() => boolean | string`. Either precedence is bound to surprise someone, unfortunately.

The first line you posted has multiple syntax errors issued as well; in general we don't bother improving semantic errors in the presence of syntax errors unless it's a very common error *and* we can reliably figure out what you were trying to write.
