### ISSUE TITLE
ES6 module variables are copied when re-exported

### ISSUE THREAD

**Issue by jonaskello** [microsoft/TypeScript#6366]
Given this example:

a.ts

``` js
export var a = 1;
export function changeA() { a = 2; }
```

b.ts

``` js
export * from './a';
```

c.ts

``` js
import { a, changeA } from './b';
console.log(a); // 1
changeA();
console.log(a); // Expected 2 but get 1
```

tsconfig.json

``` json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "outDir": "out"
  }
}
```

Result of runing c.js:

```
$ node out/c.js
1
1
```

This happens because in b.ts this:

``` js
export * from './a';
```

transpiles to

``` js
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
__export(require('./a'));
```

and the value of variable a is copied and not referenced.

If I run the same example through babel it works because it generates getters that references the original variable. This was also proposed [here](https://github.com/Microsoft/TypeScript/issues/1215#issuecomment-63756746).

I propose that if the target is set to es5 then the generated code for commonjs modules uses getters instead to make sure that re-exported variables are referenced instead of copied.

**Comment by RyanCavanaugh** [comment]
@mhegazy we should discuss this ASAP (Friday?)

**Comment by Arnavion** [comment]
Isn't this "Bug" instead of "Suggestion" ? :) 

For re-exports from modules with relative paths, TS could avoid the tax of getters and maintain ES3 support by rewriting the import of the re-export to use the original export, eg `import { a, b } from "./b"; console.log(a, b);` could compile to `var a = require("./a"); var b = require("./b"); console.log(a.a, b.b);`. (This is similar to what rollup does when it merges modules.) But it only works for modules with relative paths, not for re-exports from node_modules, etc., so it may be of limited value.

**Comment by camillol** [comment]
This issue has been dormant since 2016, but it's still valid. And it seems like it really should be labeled as a bug.

As far as I can tell, re-exports are supposed to be live views in ES6, and a re-exported variable is supposed to reflect changes. Looking at the code generation examples [here](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Modules.md), TypeScript exports map directly to ES6/ES 2015 modules when targeting ES 2015, so they will have the correct ES6 semantics in that case, right? Which makes it even more undesirable for them to have different semantics when transpiling to ES3.

At any rate, regardless of the current behavior of different compilation targets, it seems like the behavior of TypeScript modules should eventually align with that of ES6 modules. One advantage of having native module support should be that there is a common, clearly defined semantics for module import/export.

**Comment by stephenh** [comment]
I'm running into this issue while issuing the barrel pattern, i.e. in an `index.ts`:

```typescript
export * from "./Entity1";
export * from "./Entity2";
export * from "./Entity3";
```

Then later:

```typescript
import { Entity1, Entity2, Entity3 } from "entities";

someFunction() {
  const entities = [Entity1, Entity2, Entity3]
  // Entity3 is undefined
}
```

If I change it to:

```typescript
import { Entity1, Entity2 } from "entities";
import { Entity3 } from "entities/Entity3";
```

Then it works and `Entity3` is no longer undefined.

I'm technically running tests via `ts-jest` but I assume this is the same underlying issue in the "re-exports are not live bindings".
