### ISSUE TITLE
UMD output option for single file

### ISSUE THREAD

**Issue by pspeter3** [Microsoft/TypeScript#6380]
It seems like TypeScript 1.8 will support a single file option for AMD and SystemJS. Adding UMD support as well would be great.

**Comment by mhegazy** [comment]
A single file output does not really make much sense for node/CommonJS. UMD is just a wrapper around AMD/CommonJS. commonJS require implementation can not load a module from the same file anyways. so you have to use a custom loader, if so, just use AMD/SystemJS to do the trick.

**Comment by chge** [comment]
TypeScript is so useful tool due to its cross-platform abilities out-of-the box.

If you want to create a lib for browsers, it's a sign of good taste to use UMD wrapper around your code to support any user's toolchain. But currently you have to connect TypeScript with other tools and then mess around trying to fix `mkdir -p` or glob issues in Windows shell with additional plugins or forks of popular bundlers. Why to increase dependencies with heavyweight build systems and runners, instead of using one-line npm script `tsc --module umd --watch --outFile ...`?

This is a very useful feature, please implement it.

**Comment by aluanhaddad** [comment]
@chge CommonJS
