### ISSUE TITLE
Optional abstract members

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#6413]
I want to be able to make the implementation optional for abstract member, but it seems like it is not doable today.

```typescript
abstract class Component {
    public abstract setText?(l: GetLocalization): void;
    public abstract bindInteractions?(): void;
}
```
I have some component classes and they MUST extend the base component class and optionally implement certain methods with a certain signature. Right now, I can only rely on good documentation.

```typescript
class Post extends Component {
    public setText(l: GetLocalization): void {
        //...
    }
    // Though I don't want to implement bindInteractions method.
}
```
I want the power of auto-completion to also kick in.

## Why is this useful?

It is useful for classes with life cycle methods.

**Comment by RyanCavanaugh** [comment]
What would be an observable difference between optional and abstract optional?

**Comment by mhegazy** [comment]
you can do this today with class an interface merging:

```ts
interface Component {
   optionalMethods?(l: GetLocalization): void;
}
abstract class Component {
    public abstract mustImplement(): void;
}

class Post extends Component {
    public mustImplement(): void {
       if (this.optionalMethods) {
            // do something
       }
    }
}

```

**Comment by tinganho** [comment]
@mhegazy your trick seem to have solve my issue.

Though I think defining members and having some of them on a interface declaration and some of them in the class declaration is quite confusing. Besides there is some life-cycle methods that I don't want to expose publicly. I guess your solution only works with public members?

>What would be an observable difference between optional and abstract optional?

I guess this could be said with non-optionals as well? I guess the noticeable difference is that, access modifier can be set to private and protected.

**Comment by mhegazy** [comment]
looking at the original post again, i do not think `abstract` makes sense here. marking a method as `abstract` says it is impossible to instantiate this class without implementing this method. if it is optional, i.e. the class can work just fine without instantiating the class. so what you need is either 1. do not mark it as `abstract` and give it some default implementation, or 2. declare it as a property and do not mark it as `abstract` either.

**Comment by tinganho** [comment]
I think I'm fine with empty body methods if `abstract` cannot be optional. 

Little bit OT, is there a reason you don't autocomplete methods on an extended class?

**Comment by vilic** [comment]
@mhegazy Currently TypeScript supports marking an abstract as optional but does not allow concrete classes to omit the implementation, this looks weird to me:

```ts
abstract class Foo {
  abstract foo?(): void;
}

class Bar extends Foo {
  // ERROR: Non-abstract class 'Bar' does not implement inherited abstract member 'foo' from class 'Foo'.
}
```

And an abstract method, though optional, could suggests the user that "you may want to try out implementing this", instead of "what can I do, I've implemented all those abstract methods, but I still need some tweaks over there".

**Comment by valotas** [comment]
With interface/class merging, the types of the optional function are not inferred:

```
interface Component<T> {
   optionalMethod?(l: T): void;
}
abstract class Component<T> {
    public abstract mustImplement(): void;
}

class Impl extends Component<Props> {
  mustImplement() {
    // do nothing
  }

  optionalMethod(p) {
    // error TS7006: Parameter 'p' implicitly has an 'any' type.
  }
}
```

shouldn't p type be inferred here?

**Comment by sapjax** [comment]
```javascript
abstract class Component {
    optionalMethod?(l: GetLocalization): void;
    public abstract mustImplement(): void;
}

class Post extends Component {
    public mustImplement(): void {
       if (this.optionalMethod) {
            // do something
       }
    }
}
```

I just do not use `abstract` right now.

**Comment by laughinghan** [comment]
If `abstract` overrides the `?`-optionality (which IMO it shouldn't), can we at least `abstract method?();` be a syntax error or warning that the `?` does nothing, and interface merging should be used instead?

**Comment by laughinghan** [comment]
@valotas Parameter types of subclass methods [don't ever appear to be inferred](http://www.typescriptlang.org/play/#src=class%20Parent%20%7B%0D%0A%20%20%20%20optionalMethod%3F(s%3A%20string)%3A%20void%3B%0D%0A%7D%0D%0Aclass%20Child%20extends%20Parent%20%7B%0D%0A%20%20%20%20optionalMethod(s)%20%7B%0D%0A%20%20%20%20%20%20%20%20s%20%2F%2F%20(parameter)%20s%3A%20any%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aabstract%20class%20AbstractParent%20%7B%0D%0A%20%20%20%20abstract%20abstractMethod(s%3A%20string)%3A%20void%3B%0D%0A%7D%0D%0Aclass%20ConcreteChild%20extends%20AbstractParent%20%7B%0D%0A%20%20%20%20abstractMethod(s)%20%7B%0D%0A%20%20%20%20%20%20%20%20s%20%2F%2F%20(parameter)%20s%3A%20any%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Ainterface%20Iface%20%7B%0D%0A%20%20%20%20method(s%3A%20string)%3A%20void%3B%0D%0A%7D%0D%0Aclass%20Klass%20implements%20Iface%20%7B%0D%0A%20%20%20%20method(s)%20%7B%0D%0A%20%20%20%20%20%20%20%20s%20%2F%2F%20(parameter)%20s%3A%20any%0D%0A%20%20%20%20%7D%0D%0A%7D):

```ts
class Parent {
    optionalMethod?(s: string): void;
}
class Child extends Parent {
    optionalMethod(s) {
        s // (parameter) s: any
    }
}

abstract class AbstractParent {
    abstract abstractMethod(s: string): void;
}
class ConcreteChild extends AbstractParent {
    abstractMethod(s) {
        s // (parameter) s: any
    }
}

interface Iface {
    method(s: string): void;
}
class Klass implements Iface {
    method(s) {
        s // (parameter) s: any
    }
}
```

So I don't think that's because of the interface/class merging.

**Comment by Zarel** [comment]
> If `abstract` overrides the `?`-optionality (which IMO it shouldn't), can we at least make `abstract method?();` be a syntax error or warning that the `?` does nothing, and it should be made non-abstract or moved into a merged interface instead?

I think this could be useful for situations where you explicitly want the child class to say `method: undefined;` so you don't forget about the method.

But I think the error message should hint that you might have meant `method?();` instead of `abstract method?();`.
