### ISSUE TITLE
Unable to constrain the callback function parameter length

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#6416]
Generalization of #4241.

```ts
type F	 = (cb: (a: number, b: string) => number) => number;
var f: F = (cb: (a: number) => number) => cb(0); // should be a compile error
f((a, b) => a + b.length); // runtime error
```

**Comment by RyanCavanaugh** [comment]
There's not really anything we can do here, unfortunately. This is allowed because of the combination of function argument type bivariance (which we have to have) and the allowed variance of "a function accepting fewer parameters" (which we have to have).

This is only tangentially related to #4241 -- that one is about contextual typing, but there's no impact of contextual typing in this code.

**Comment by falsandtru** [comment]
It is unfortunate. Thanks.
