### ISSUE TITLE
What's import without a require?

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/TypeScript#6417]
Reading the angular.d.ts file I found some strange import/export lines which I strongly feel I don't understand:

```typescript
// Collapse angular into ng
import ng = angular;
// Support AMD require
declare module 'angular' { export = angular; }
```

Please, can someone explain these lines to me?

*    What is `import` without a `from`?
*    Why is the module name a string? Shouldn't this be a regular identifier? What's the difference?
*    In today's TypeScript they'd have written `declare namespace` instead of `declare module`, right?

Thanks a bunch!

**Comment by DanielRosenwasser** [comment]
`import foo = some.entity` is an *alias* to `some.entity`. Basically, `foo` takes on all meanings (i.e. value, type, and namespace semantics. It's useful if you have some long that is a little too cumbersome to type out. This functionality is unfortunate in its keyword usage.

Before we continue, just know that namespaces used to be called "internal modules", and modules used to be called "external modules. This is an unfortunate accident of history.

`declare module "angular"` declares a module (ES6/CommonJS/AMD-style modules, or "external modules") named `"angular"`. This is useful for if your library doesn't come with typings, and will be used to describe the shape of `"angular"` when you import it.

Because we wanted to make the difference easier for newcomers, you can't use the `namespace` keyword with a string. That way, the two concepts overlap less, so `declare namespace` can *only* declare a namespace with identifier names. `declare module` can declare either a module or a namespace, but you should pretend it only declares modules with string names.

**Comment by DanielRosenwasser** [comment]
You can [see our handbook section on *ambient modules*](https://github.com/Microsoft/TypeScript-Handbook/blob/008c280f886daad2bcf16ad0fca05ee6258deb14/pages/Modules.md#ambient-modules) for more details.

**Comment by SetTrend** [comment]
Thanks, @DanielRosenwasser for clarifying.

The handbook doesn't give this information, I'm afraid. Read the suggested page before.
