### ISSUE TITLE
Promise.all overloads listed in wrong order

### ISSUE THREAD

**Issue by arfmann** [Microsoft/TypeScript#6423]
I think this is a valid assignment:

```typescript
    const [a, b, c] = await Promise.all([
        Promise.resolve(1),
        Promise.resolve(2),
        Promise.resolve(3)
    ]);
    // a = 1, b = 2, c = 3
```
And it appears to work as I expect, but TypeScript is giving the following warning:

Tuple type '[number, number]' with length '2' cannot be assigned to tuple with length '3'

**Comment by ahejlsberg** [comment]
Issue is that the overloads for `Promise.all` are listed in the wrong order in lib.es6.d.ts. The highest arity overloads should come first. Currently the compiler just picks the first overload because a tuple with more elements is assignable to a tuple with fewer elements as long as the first elements match.
