### ISSUE TITLE
invalid code generated with target "es2015" and "system" modules

### ISSUE THREAD

**Issue by FlorianDold** [Microsoft/TypeScript#6426]
The following code

```typescript
export class MyClass { }

export function myFunction() {
    return new MyClass();
}
```
is compiled (with `tsc test.ts -m system --target es2015`) to

```javascript
System.register([], function(exports_1) {
    "use strict";
    var MyClass;
    function myFunction() {
        return new MyClass();
    }
    exports_1("myFunction", myFunction);
    return {
        setters:[],
        execute: function() {
            class MyClass {
            }
            exports_1("MyClass", MyClass);
        }
    }
});

```

which is wrong, since the actual definition of `MyClass` is not in scope of `myFunction` anymore.

Compiling down to es5 works as expected with respect to the scope of the class.

**Comment by JKillian** [comment]
I believe that this is the correct behavior @FlorianDold. When you do `export class MyClass { }` you are using a class expression instead of a regular class declaration. In class expressions, the BindingIdentifier portion (i.e. `MyClass`) is optional. If provided, as you did, it is only available for use inside of the class body. ([See bullet point #2 here](https://github.com/Microsoft/TypeScript/issues/497#issue-40826560)).

Instead, you could do something like this:

```ts
class MyClass { }
export MyClass;
export function myFunction() {
    return new MyClass();
}
```

Your TS code should generate an error, as `return new MyClass();` is invalid because `MyClass` isn't available there. If there's no error, that is a bug most likely.

**Comment by weswigham** [comment]
`export class MyClass { }` is still a class declaration (with an `export` modifier). Our emit is probably wrong - the declaration within the `execute` function behaves as block scoped (which is normal), but we need to hoist it so its binding is available in the initialization block above. This is probably best done by rewriting the class as a class expression which is assigned to the `var` made above. (or leaving it as a declaration, but mangling the hoisted name and assigning it to the mangled name)

**Comment by JKillian** [comment]
Thanks for the correction @weswigham. If you did want to export a named class expression, assuming you could do something like `export (class SomeName { });`?
