### ISSUE TITLE
TSX: Can't use a component stored in a variable

### ISSUE THREAD

**Issue by rigdern** [Microsoft/TypeScript#6446]
### Repro

Suppose I have a component called `MyComponent`.

Using `MyComponent` like this works:

```tsx
render() {
  return <MyComponent />;
}
```

but storing `MyComponent` in a variable and then trying to use it does not:

```tsx
render() {
  var anAlias = MyComponent;
  return <anAlias />;
}
```

It results in the following error:
```
error TS2339: Property 'anAlias' does not exist on type 'JSX.IntrinsicElements'.
```

### Workaround

Instead of using TSX, use `React.createElement`:

```tsx
render() {
  var anAlias = MyComponent;
  return React.createElement(anAlias);
}
```

**Comment by vladima** [comment]
`anAlias` is an intrinsic JSX element since [it starts with lowercase letter](https://github.com/Microsoft/TypeScript/wiki/JSX#type-checking). Intrinsic elements are looked up on [JSX.IntrinsicElements](https://github.com/Microsoft/TypeScript/wiki/JSX#intrinsic-elements)  interface and in your case it presumably does not have member `anAlias`. Try making it upper-case so it will be treated as [value-based element](https://github.com/Microsoft/TypeScript/wiki/JSX#value-based-elements).

**Comment by RyanCavanaugh** [comment]
Vlad covered it -- this is the same behavior you'd see with the regular JSX transformer (lower-case identifiers are treated the same as `div` or `span`)

**Comment by rigdern** [comment]
Thanks. I was not aware of the distinction between intrinsic and value-based elements and I didn't know that the casing of the first letter was significant.
