### ISSUE TITLE
Typing (string[] | string[][]) not recognized properly

### ISSUE THREAD

**Issue by rogierschouten** [Microsoft/TypeScript#6453]
Hi all,

I have two small examples that I expected to be equivalent but tsc accepts only one:

Working example:
```
let myArray: (string | string[])[];
myArray.forEach((element: string | string[]): void => {
}); // no compile error
```

Not-working example:
```
let myArray: string[] | string[][];
myArray.forEach((element: string | string[]): void => {
}); // compile error: Cannot invoke an expression whose type lacks a call signature
```

**Comment by ahejlsberg** [comment]
Methods are available on a union type only when each of the underlying methods have identical parameter lists (which isn't the case here). This is by design. From a typing perspective it technically isn't correct to do what you expected in all cases (i.e. union together the parameter types of each of the underlying methods). For example, say you had a method with two parameters of the array element type. The underlying signatures would be `foo(x: string, y: string)` and `foo(x: string[], y: string[])`, and we'd produce a combined signature `foo(x: string | string[], y: string | string[])`. That would permit you to call with `x` and `y` arguments of *different* types, which is incorrect.

**Comment by BairDev** [comment]
@ahejlsberg Maybe I'm at a loss, but why is `foo(x: string, y: string)`

>a method with two parameters of the array element type

Of course, here you can't do `x.forEach()` in the function body.

I mean (and maybe OP, either), that here `a` is an array anyway. 

    let a: number[] | string[];
    // later
    a.forEach(); // compile error: Cannot invoke an expression whose type lacks a call signature

What is the technical difference between `string[] | number[]` and `(string | number)[]`?

**Comment by sledorze** [comment]
@BairDev 

string[] | number[] means either an array of string OR an array of number.

(string | number)[] means an array of either string OR number, in a non exclusive way.
so that: ["a", 5] is such an array that cannot be bound to string[] not to number[].

**Comment by sledorze** [comment]
@ahejlsberg is there any notion of variance in typescript? I think something can come out from properly considering that aspect.

**Comment by sledorze** [comment]
@mhegazy I think it could be reopened

**Comment by kitsonk** [comment]
Contra/covariance is covered in #1394 as well as somewhat related to variadic kinds proposed in #5453.
