### ISSUE TITLE
Refactor move file

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#6487]
_From @tamascsaba on December 7, 2015 15:15_

I want to move file to another location but there is no way :(
like: https://www.jetbrains.com/idea/help/move-refactorings.html

_Copied from original issue: Microsoft/TypeScript-Sublime-Plugin#416_

**Comment by mhegazy** [comment]
_From @tamascsaba on January 8, 2016 9:8_

???

**Comment by RyanCavanaugh** [comment]
What's going on here?

**Comment by mhegazy** [comment]
API support for a new LS operation to move a file. the new operation would result in , similar to rename, a set of changes to be applied to the project. 

for instance, if you more a module, all imports will be adjusted to reflect the new name/path. similarly /// references would be rewritten as well. possiblly tsconfig.json references.

**Comment by danielrasmuson** [comment]
+1

**Comment by mhegazy** [comment]
A better explanation can be found in https://github.com/Microsoft/TypeScript/issues/10218#issue-170099571

**Comment by daprahamian** [comment]
:+1:

**Comment by designxtek** [comment]
👍

**Comment by liaotianr** [comment]
I consider that as a very important feature. No one wants to manually rename all imports.

**Comment by misantronic** [comment]
+1

**Comment by sergeu90** [comment]
+1

**Comment by xLama** [comment]
I think this is a MUST. Very useful.

**Comment by remojansen** [comment]
Do you guys have any updates about this issue? It is not in the [Roadmap](https://github.com/Microsoft/TypeScript/wiki/Roadmap).

**Comment by derth** [comment]
The reason i code with webstorm open, side by side with vscode, to rename/move files/folders and update all imports automatically.
+10

**Comment by aluanhaddad** [comment]
Aggregate 👍 on the OP 😀

**Comment by uglycoyote** [comment]
@aluanhaddad, no, it's good that he posted this.  He provided valuable information that Webstorm has an implementation of this.

**Comment by whitecolor** [comment]
This would be very valuable and actually, must. When this can be expected?

Another feature, not sure mentioned anywhere or not, is ability too move TS export (interface/function/const../whatever) into another file, so that it would find all the import references in other files and changed them to a new location. Also, would add import in the original file if moved object was used there.

**Comment by Tinee** [comment]
+1

**Comment by orgito** [comment]
I have been using this [Move TS](https://marketplace.visualstudio.com/items?itemName=stringham.move-ts) extension with good results.

**Comment by designxtek** [comment]
Would the changes be on vscode or typescript api providing vscode that ability to rename/move files?

**Comment by jcezarms** [comment]
A definite must. If you don't plan a months-ahead architecture for any big project you get in, the final structure will either be a complete mess or organized at the cost of many head-scratching hours.

**Comment by moonforeshot** [comment]
@orgito damn that plugin should have been built into vscode itself! a real gem

**Comment by alalonde** [comment]
Agreed that this vital.  Without that plugin it would have pushed me over the edge to Webstorm.  The only weakness with the plugin is that it saves automatically; to be compatible with "rename symbol" in VSCode it should make the changes in all dependent files but not save them.

**Comment by Chris2011** [comment]
Any news here?

**Comment by amivit** [comment]
No news?

**Comment by leocaseiro** [comment]
This extension works great https://marketplace.visualstudio.com/items?itemName=stringham.move-ts

**Comment by baszalmstra** [comment]
+1

**Comment by leocaseiro** [comment]
Hi @misantronic, @sergeu90, @Tinee and @baszalmstra

Have you ever seen that you could use emoji reaction instead of posting `+1`?

Every time we post comments on GitHub, all the subscribers of the topic receive notifications and some users, receive emails too. It's kind of frustrated reading an email written: `+1`

The community appreciates if we all start using the reactions instead:
[github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments](http://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)


I apologise for any offence it may cause and for the others getting this notification.

**Comment by umagon** [comment]
So, is this not gonna be implemented?

**Comment by mhegazy** [comment]
Should be covered by:
1.  New rename command: https://github.com/Microsoft/TypeScript/pull/23573
  Triggered by IDE to update the project after a file rename event
2. Refactor - Move to a new file: https://github.com/Microsoft/TypeScript/pull/23726
  Triggered manually by selecting a declaration(s) and moving them to a new file
