### ISSUE TITLE
Properties should be set on the prototype

### ISSUE THREAD

**Issue by gamealchemist** [Microsoft/TypeScript#6515]
### 1) uninitialized properties

I was surprised to see that, when defining uninitialized properties, the compilated js code was just empty ( a Function doing nothing) :  

So the class :  

    class PointClass {
      x : number;
      y : number;
    }

compiles to : 

    var PointClass = (function () {
        function PointClass() {
        }
        return PointClass;
    })();

Which is annoying for those reasons : 
  • an iteration ( for..in) will have no effect, while we declared properties. 
     ( For instance, one might want to initialize all properties to 0 with a for..in).
    In the same way, Object.keys, and Object.getOwnPropertyXXXX returns nothing.
  • the JIT has no hint about the hidden class that corresponds to this js class : 
any late access to any unitialized property will cause deoptimization, when in fact
it was known from the start (in the ts code) that this property existed.  

### 2) Initialized properties
If you initialize properties, you still could do better by using the prototype : 

    class PointClass {
      x : number = 0;
      y : number = 0;
    }

now compiles to : 

    var PointClass = (function () {
        function PointClass() {
           this.x = 0;
           this.y = 0;
        }
        return PointClass;
    })();

But it might seem as useless to initialize the properties when the prototype fits perfectly to hold default values : 

    var PointClass = (function () {
        function PointClass() {
        } 
        PointClass.prototype.x = 0;
        PointClass.prototype.y = 0;
        return PointClass;
    })();

The issue i see in such a change is that Object.keys, and Object.getOwnPropertyXXXX behaves differently.   
But the creation of such object is way faster (especially when the number of property grows).
Obviously, reference types should still be set in the constructor, and can be set to null in the prototype as a type hint for the JIT.  

Wether the property are initialized or not, an additional benefit of defining properties (?also?) on the prototype is the readability of the generated code. See http://stackoverflow.com/a/26614436/856501 , the poster explains it better than i could do.

As a workaround, i used the following property decorator :   

    function setOnProto(defaultValue) {
      function _setOnProto(target:Object, propertyName : (string | symbol)) {
           target[propertyName] =  defaultValue;
      }
      return _setOnProto;
    }

With this decorator, the code reads :

    class PointClass {
       @setOnProto(0)
       x : number ;
       @setOnProto(0)
       y : number ;
    }

**Comment by Arnavion** [comment]
This shares instance properties between instances, which apart from being an oxymoron also breaks down when the values are mutable.

The SO answer you linked hand-waves that away by prescribing that array and object properties should be set to null and only initialized to real values in the constructor, which is just dangerous and error-prone. The other justification it gives, that properties on the prototype are useful for describing the public surface and attaching documentation, is already supported by the TS class properties syntax.

The [class properties syntax proposed for ES7](https://github.com/jeffmo/es-class-fields-and-static-properties/blob/24232cb/README.md#instance-field-declaration-process) also sets properties on the constructed object, so TS has even less reason to deviate from it.

>the JIT has no hint about the hidden class that corresponds to this js class

Assuming you're talking about V8, properties set in the constructor function are exactly how V8 determines the hidden class for that function. Once created this class is associated with the constructor function and directly used for future invocations. It would've been quite a useless optimization for all the years that V8 has been compiling ES5 constructor functions if it didn't already work this way.

>As a workaround, i used the following property decorator

This approach requires you to write a decorator on each field individually, so already you can't do what you initially wanted to do - "( For instance, one might want to initialize all properties to 0 with a for..in)"

If you're looking for meta-programming like getting all the fields of a class, then decorators are designed for that approach anyway. Use them instead of trying to enumerate the prototype's properties.

**Comment by RyanCavanaugh** [comment]
I think @Arnavion covered everything important here.

Regarding point 1, a general theme is that some people want these properties initialized and some don't. It's *much* easier for the people who do want them to exist to say `x: number = undefined` or `x: number = 0` than to make the people who *don't* want them initialized to have to use some weird syntax to say "don't initialize this field please".
