### ISSUE TITLE
Questions about your testing strategy

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#6528]
Your testing strategy is awesome and I'm very impressed. It is one of the big golden eggs in this project. I just wonder, if it where you guys who invented it? Is there a name for it and if there is more info about it?

**Comment by DanielRosenwasser** [comment]
@RyanCavanaugh and @danquirk, you two are best-suited to answer this. :smile:

**Comment by DanielRosenwasser** [comment]
And @CyrusNajmabadi might have some thoughts on this as well.

**Comment by tinganho** [comment]
Since my daily job is to write web applications. I implemented a similar testing strategy for one of my web applications(I hope you guys don't mind me "borrowing" your strategy), where I test the HTTP response for my backend and a web browser screenshot for my frontend and it diffs against references as your strategy. And I'm glad to see it being a magnitude more effective than anything I tried before.

**Comment by plantain-00** [comment]
I borrowed the strategy of `test and accept baseline` from here too, for testing my back-end RESTful api.

The strategy seems hard to used for front-end, eg, clicking a button, mouse hovering.

**Comment by RyanCavanaugh** [comment]
Test strategy guy here.

In general "baseline the *correct* result" has a very long history as a test strategy and I cannot pin down any of its origins more precisely than that. It can be successful if used correctly, but needs a subtle implementation.

That said, I've worked with some *very* unsuccessful baseline-based strategies in the past. Key things I've learned:
* Baselines must be human readable, including their diffs. Our error baselines used to be very bad in this respect. You can't just say Baseline:"Error from char 12 to 53" -- it has to be something I can load in a basic diff tool and understand.
* Baselines must be trivial to update. I once worked on a system where baseline updates required 24+ hours. Not good. Scott Louvau created some extremely strong tools around this area in his team many years ago and I credit him for showing me how good this could be.
* Baselines are part of source control. Eventually you *will* need to `git bisect` a baseline. Again, a bad system I worked on (and possibly made...) had no versioning. Nightmare.
* Baseline tests must be easy to add. This falls under my primary test thesis: adding a test should be as easy as fixing the easiest bug the test can find. In our case, literally dropping the file that reproduces the bug into a folder is sufficient.
* There is an important trade-off in criticality, noise, and performance:
  * The less likely something is to change, the more baseline changes matter. For example, the symbol baselines seem worthless (they *very* rarely change), but any change in a symbol baseline is usually a *very* important bug. We pay the high performance cost of running these tests all the time.
  * Conversely, the more something changes, the less baseline changes matter. lib.d.ts changes all the time; for this reason, we exclude its line numbers from baselines to reduce noise.
* Organization is probably less important than you think, as long as you follow all the above advice.

Things we still need to figure out:
* How do we properly review "broad but shallow" changes? We've seen some diffs that touch 10%+ of baselines, which is a *huge* number at this point. How can we reduce noise so that we're only manually reviewing the changes which are "different" from other changes?
* How the do you write a *good* baseline format for arbitrarily complex data? For example, the source map baselines are currently incomprehensible, but this is a rather fragile feature, so we would love to have a readable text format.

----------

TSLint perhaps exemplifies these rules as hard as humanly possible.

Here's an example of a not-great test (the *test coverage* of this is good, it's just embedded in a test format that is a maintenance disaster): https://github.com/palantir/tslint/blob/c25d0841862ed0c9116c35ef79c41368bc31d42d/test/rules/indentRuleTests.ts

TypeScript tests used to look like that. Result: no one added tests.

And then here's the same coverage, in a test format that is easy to read, easy to revise, easy to diff, just easy in all possible ways: https://github.com/palantir/tslint/blob/new-test-system/test/rules/indent/tabs/test.ts.linttest

**Comment by tinganho** [comment]
@RyanCavanaugh do you mind if I can get your thoughts on an article I've written about this topic? I can only share it with Google Docs.

**Comment by tinganho** [comment]
> The strategy seems hard to used for front-end, eg, clicking a button, mouse hovering.

@plantain-00 selenium has a screenshot API. just use that as a baseline. Right now, I use something like click -> action -> action -> screenshot. And it test JS, CSS and HTML :smile: . As @RyanCavanaugh pointed out it takes long time. Though I have some tools for cherry-picking tests and I'm currently thinking about how to run tests in parallel.

**Comment by RyanCavanaugh** [comment]
@tinganho I'd be happy to take a look

**Comment by JKillian** [comment]
> TSLint perhaps exemplifies these rules as hard as humanly possible.

:smile: Converting the tests from the old format to the new format for TSLint was actually a pretty enlightening experience. All of the sudden you could see where the output of TSLint was good/bad, whereas that was almost impossible with the old tests. If a TSLint lint error message was poor, you saw that message immediately in the context of the code it was talking about and could tell that it was not descriptive/accurate/clear enough. And the same was true for the location of the error as well. 

Long story short, it became so much easier to compare what results you want TSLint to produce and what it is actually producing.

And thanks to the TypeScript team for the idea/inspiration for the test system for TSLint. I believe the new system follows all your rules mentioned above @RyanCavanaugh, and they all seem like big positives as far as TSLint is concerned. We haven't implemented things quite the same way, there's currently no concept of accepting baselines, but that's because TSLint is a simpler project than TypeScript, and expected results are seldom going to change.

**Comment by DanielRosenwasser** [comment]
I'd also add that when I joined the team, seeing our error baseline output immediately made me say "Can we make the compiler's error messages look like this?" The fact that could visualize our error output was something I thought users could might find very useful - especially back when tsserver wasn't a thing. Thanks to that, TypeScript 1.8 will have the `--pretty` flag.

**Comment by danquirk** [comment]
I would just add that as a general principle, regardless of baseline strategies and such, execution speed is crucial. The value developers get from your test system is proportional to how often they run it and how quickly they can benefit from it. If you have a great test system but it takes 24 hours to run your basic tests then developers cannot effectively edit->test->debug, and the value of all your tests is reduced. When I started on TypeScript I think 'jake runtests' (or whatever we called it back then) took 90-120s to run and that created a baseline performance expectation (pun intended). Ever since, eventually when average test runtime approached 5-7 minutes (due to new tests or new test automation features) people would start complaining and someone would spend time fixing the test infrastructure itself to be faster. Being able to push atomic changes and have Travis-CI validate your micro tasks within 5ish minutes allows you to work with great confidence (assuming your speedy test system has good coverage). Saving a couple minutes there on every developer inner loop operation pays for itself many times over.

**Comment by tinganho** [comment]
@RyanCavanaugh do you have an email I can share a Google doc with you?

Great comments btw.

**Comment by tinganho** [comment]
@danquirk @RyanCavanaugh do you guys have any opinions/thoughts about baseline testing having a workflow where you write your source code first and then accept the baseline. Which sound very contradictory to what TDD stands for. TDD wants you to write your test case first and then your source code, so that you don't fit your test after your source code.

**Comment by weswigham** [comment]
@tinganho - When I first joined the team, I tried a strategy of editing baselines by hand, then making a commit with the new (now failing) baselines, then editing the code to make it match the new baseline. It is cumbersome at times, and requires a strong ubderstanding of how your planned change will affect the baselines, but it can be done.

Generally speaking though, many changes can affect baselines you didn't expect (perhaps because you weren't even aware the test existed), so you end up diff-and-accept'ing anyway. There's also emitter changes like "move parenthesis in class emit" which end up affecting the baselines for almost every test - which, in TDD could mean our tests are poorly isolated, as changes in one subsystem can affect many unrelated tests. Given that our tests are all end-to-end tests, though, I'd call it expected (even if the test is designed to test type guards, it also happens to cover some portion of the emitter).

**Comment by CyrusNajmabadi** [comment]
To add to what @danquirk said:  Currently on Roslyn the time to build and test everything is apprx 40 minutes.  That's far too slow to make part of your inner loop.  Now, we can use our CI system as an *asynchronous* source of confidence.  i.e. I can be at my machine locally making changes A, B, C... and continuously pushing them to the CI server.  As I continue working i'll starting hearing about the results of A, B... and I can incorporate any necessary changes accordingly.  But i'm always going to have to wait 40 minutes from my last push to get final results.  

That is effectively a long stall in the ability to to process a single issue.  Devs can still be productive by pipelining other work during those stall times.  But that "randomization" can be difficult for some.   So we're strongly looking into how we can get our own build/test times down to the 'minutes' level.  Some wins are going to be simple (i.e. better build systems that don't rebuild things unnecessarily).  But some wins will be hard.  How do you make things faster when you do have literally hundreds of thousands of *important* tests that you do want validating your changes?  If you start from a position that your entire test run should be under a certain amount of time, then it's easy to keep yourself there (more or less).  As you hit your high water mark, you profile and address issues, win some buffer space and have room for more tests.  But when you come after this after the fact, and you need to shave off 90% of your test running time, it's much much much harder to reach these goals.

**Comment by CyrusNajmabadi** [comment]
TDD is certainly a viable way to test things, it's just not the only way.  I find TDD great for making very specific statements about what I want my code to produce.  However, because of that, you can need an enormous amount of up front tests written to explicitly specify everything that you would expect your compiler to produce.

Baseline tests, on the other hand, help validate a *massive* swath of functionality, as well as ensuring that changes in behavior are effectively captured at the macro scale.  These baseline tests then effectively act as integration tests of all the layers of the compiler.  i.e. they're tests that verify that the parser/binder/type-checker/emitter/etc. layers all integrate properly and produce the right results.   

We use TDD to produce some tests.  We just don't *only* use TDD.

**Comment by RyanCavanaugh** [comment]
@tinganho ryanca@microsoft.com

**Comment by RyanCavanaugh** [comment]
One way I do TDD with baselines is to write a baseline file that outlines the use cases for the behavior I want to change / add, then baseline-accept that, then start making changes until the new baseline looks the way I want it.

This also has the advantage that in code review, you can show someone the most pertinent changes in a wrapped-up example.

**Comment by DanielRosenwasser** [comment]
> One way I do TDD with baselines is to write a baseline file that outlines the use cases for the behavior I want to change / add, then baseline-accept that, then start making changes until the new baseline looks the way I want it.

This is also what I do. I also keep my baseline accepts separate from my test creations in case I ever want to make rebasing a little easier.

**Comment by tinganho** [comment]
@RyanCavanaugh I just shared my doc with you.

Quite interesting to hear the strategy about editing the baseline manually to do TDD.
