### ISSUE TITLE
why doesn't this work?

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#6538]
```typescript
interface X { x: number; }
interface Y { y: number; }
interface Named { name: string; }
interface Z { z: number; }
type W = (X | Y) & Named | Z;
function isNamed(w: W): w is Named {
	return undefined;
}
```

![image](https://cloud.githubusercontent.com/assets/937933/12433246/f30856e4-becd-11e5-9b43-2a32b4d2ea81.png)

**Comment by RyanCavanaugh** [comment]
I tried to write an explanation, but the explanation was the same as the error message.

Are you asking why type predicates must be assignable to their corresponding parameter types? Or something else?

**Comment by DanielRosenwasser** [comment]
@RyanCavanaugh it sounds like that should succeed. Shouldn't `Named` be assignable to `(X | Y) & Named`?

**Comment by DanielRosenwasser** [comment]
Here's a simplified example:

```ts
interface Animal {
    animal;
}

interface Dog extends Animal {
    dog;
}

interface Car {
    car;
}

let thing: Dog | Car;

function isAnimal(x: Car | Dog): x is Animal {
    return "animal" in x;
}

if (isAnimal(thing)) {
    thing
}
```

Basically we're trying to tell you that it's nonsensical to say `x is Animal` because `Animal` is more general than `Dog`. If you're getting a `Dog` as your input, you should say `x is Dog`.

That said, it sounds like we should have a better error message here. See #6540

**Comment by sandersn** [comment]
[Assuming that the question is why the assignability check failed.]

The error message actually doesn't make it clear that the compiler tried to assign `Named` to both `Z` and `(X | Y) & Named`. It reports only that `Named` isn't assignable to `Z`. The compiler *also* tried to assign `Named` to `(X | Y) & Named`, but that also failed, because `Named` is not assignable to `(X | Y)`.

I wouldn't call @DanielRosenwasser's example simplified so much as shifting the root cause of assignability failure from intersection (`& (X | Y)`) to subclassing (`extends Animal`).

**Comment by aleksey-bykov** [comment]
@RyanCavanaugh I hear you, give me the number of the issue that deals with it.

Isn't `(X | Y) & Named` === `X & Named | Y & Named`?

If so how is `(X | Y) & Named | Z`  this different from `Named | Z` which **works**?

**Comment by sandersn** [comment]
The difference is the assignability of intersection versus union:

```ts
declare var n: Named;
let xnamed: X & Named = n;
```

`Named` is not assignable to `X & Named` because it doesn't have X's properties.

**Comment by aleksey-bykov** [comment]
but from a common sense stand point situation where I ask whether `w: X & Named | Z` can be `Named` is normal, isn't it? If I can come up with a runtime test that asserts it why is it a crime from assignability standpoint? It looks like assignability checkings aren't the proper vehicles for type guards.
