### ISSUE TITLE
Generic default parameter use can result in loss of type info compared to providing parameter directly

### ISSUE THREAD

**Issue by jameslong** [microsoft/TypeScript#6573]
You can lose type information when using a default parameter compared to providing the exact same value as the matching parameter. E.g.

```
const identity = <T>(value: T) => value;

const testFn = function <T, U>(val: T, fn: (val: T) => U = identity) 
{
        return fn(val);
}

interface Int {};
const val: Int;

const x = testFn(val); // x: {}
const y = testFn(val, identity); // y: Int
```

I would have expected the two cases to match and return a type of `Int` but the types are resolved differently.

**Comment by sandersn** [comment]
Looks like the default value doesn't participate in type argument inference so U isn't inferred to be `Int`. I don't know the spec or implementation well enough to know if this is by design. I'll check and in the meantime maybe @ahejlsberg or @JsonFreeman will know.

(by the way, the repro is missing a `return` on the `fn(val);` line)

**Comment by sandersn** [comment]
All I see in the spec is in section 3.10.6: "If *M* is a call signature and a corresponding call signature *N* exists in *S* [the source], ...inferences are made from parameter types in *N* to the corresponding parameter types in *M* **for positions that are present in both signatures**"

Since the second position is not present in the caller (*S* in the quote above), no inferences are made. I might have missed something about optional arguments, but if not, then this is by design and the spec would need to change to fix it.

**Comment by JsonFreeman** [comment]
As far as I know, the spec has never taken default parameter values into account for type argument inference.

@sandersn The quote you are referencing is about inferring between parameter lists of two different signatures, not making an inference from a call argument to the parameter of the callee. But if you look at the type argument inference section in chapter 4 of the spec, note that it talks about contextual signature instantiation in the inferential typing section. That is the mechanism that causes the second call in the repro to work. The issue is that this only happens for arguments, and not for default parameter initializers.

**Comment by karptonite** [comment]
I just ran into something similar. But now it is the case that this code:
```ts
const identity = <T>(value: T) => value;

const testFn = function <T, U>(val: T, fn: (val: T) => U = identity) 
{
        return fn(val);
}
```
gets a compiler error:
`Type '<T>(value: T) => T' is not assignable to type '(val: T) => U'.
  Type 'T' is not assignable to type 'U'.`

Thanks to @NaridaL on gitter for explaining this to me: the compiler is right. This is not valid code, because it would allow someone to do `testFn<string, number>('foo')`, and you may have a run time error when a number is expected but a string is returned.

This can be done properly with overloading:
```ts
const identity = <T>(value: T) => value;

function testFn<T, U>(val: T, fn: (val:T) => U): U;
function testFn<T>(val: T): T;
function testFn( val: any, fn = identity ) 
{
        return fn(val);
}
```

**Comment by RyanCavanaugh** [comment]
The spec is now an "archived" artifact and we won't be tracking defects against it anymore.
