### ISSUE TITLE
Incorrect code generation in TSX files

### ISSUE THREAD

**Issue by pdeva** [Microsoft/TypeScript#6586]
Typescript version 1.7.3.

Given the following TSX code:

```
renderThresholdPanel(metric:MetricDefinition) {
	var panel;
	switch (metric.unit) {
		case MetricUnit.PERCENTAGE:
			panel = PercentageThresholdConfigPanel;
			break;
		case MetricUnit.RESPONSE_TIME:
			panel = ResponseTimeThresholdConfigPanel;
			break;
		case MetricUnit.MEMORY_SIZE:
			panel = MemoryThresholdConfigPanel;
			break;

	}

	return <panel ref="thresholdPanel"/>;
}
```

The output is: 

```
function (metric) {
	var panel;
	switch (metric.unit) {
	    case metricTypes_1.MetricUnit.PERCENTAGE:
	        panel = percentageThesholdConfigPanel_1.PercentageThresholdConfigPanel;
	        break;
	    case metricTypes_1.MetricUnit.RESPONSE_TIME:
	        panel = responseTimeThresholdConfigPanel_1.ResponseTimeThresholdConfigPanel;
	        break;
	    case metricTypes_1.MetricUnit.MEMORY_SIZE:
	        panel = memoryThresholdConfigPanel_1.MemoryThresholdConfigPanel;
	        break;
	}

	return React.createElement("panel", {"ref": "thresholdPanel"});
};
```

**Expected**

Should have used the `panel` variable
```
return React.createElement(panel, {"ref": "thresholdPanel"});
 ```

**Actual**

Uses the string literal `"panel"` instead:

```
return React.createElement("panel", {"ref": "thresholdPanel"});
```

**Comment by DanielRosenwasser** [comment]
I don't think that's correct. All element names beginning with lowercase letters are intrinsics, and should be emitted to a string. But I'll defer to @RyanCavanaugh instead of closing this.

**Comment by RyanCavanaugh** [comment]
@DanielRosenwasser is correct.

This is unfortunately 100% necessary since there's a ton of React code that writes things like `let div = <div>Hello world!</div>`, so even the presence of the `panel` local here isn't definitive proof of anything.

It sounds like you're using some non-React framework (since this code wouldn't work with the React transformer either) so the recommended actions are 1) use `--jsx preserve` and pipe that output to an appropriate JSX transformer or 2) let us know which other framework you're using so we can take that into account for future JSX decisions.

**Comment by pdeva** [comment]
i was using react itself.
