### ISSUE TITLE
Conditional Import of Module Fails

### ISSUE THREAD

**Issue by 2426021684** [Microsoft/TypeScript#6601]
I expected the following code to work.
```typescript
if (!(<any>window)._babelPolyfill){
	import "babel/polyfill"
}
```
Instead I got an error.
`An import declaration can only be used in a namespace or module.`
Is it possible to conditionally import a module?

**Comment by basarat** [comment]
> Is it possible to conditionally import a module?

Not according to ES6. You need to use a `module loader syntax` specific to your module loaders. For ES6 people tend to use `System.js` and that has `System.import`. (more http://www.2ality.com/2014/09/es6-modules-final.html) 

Personally I'm just going with webpack / npm all the way (the whole React community is pretty settled on that choice) and the backend is already `npm / commonjs / nodejs` :rose:

**Comment by 2426021684** [comment]
Thanks. It works now.

**Comment by jbrantly** [comment]
If you're using webpack then I have an example for conditionally loading a module at https://github.com/TypeStrong/ts-loader/tree/master/test/codeSplitting

There's also a psuedo-ES6 example at https://github.com/TypeStrong/ts-loader/tree/master/test/es6codeSplitting (but it still uses `require.ensure` instead of `System.import`). When webpack2 hits you could use `System.import`.

**Comment by codebling** [comment]
For prosterity, you can see jbrantly's examples (whose links now 404) here: 
https://github.com/TypeStrong/ts-loader/tree/d4b85fcbbd4b10ada4bdd4559e87c66799f3d8ec/test/codeSplitting
https://github.com/TypeStrong/ts-loader/tree/d4b85fcbbd4b10ada4bdd4559e87c66799f3d8ec/test/es6codeSplitting

See also [Optional Module Loading and Other Advanced Loading Scenarios](https://www.typescriptlang.org/docs/handbook/modules.html#optional-module-loading-and-other-advanced-loading-scenarios).
