### ISSUE TITLE
Salsa could show warning messages on require statements if it is not configured with a module system

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#6669]
_From @alexandrudima on January 27, 2016 10:36_

Testing #2218 

I don't have a `jsconfig.json`

![image](https://cloud.githubusercontent.com/assets/5047891/12610832/0c016754-c4ea-11e5-9545-59a1f217f96a.png)

_Copied from original issue: Microsoft/vscode#2426_

**Comment by billti** [comment]
This is valid CommonJS/Node code and doesn't need to be compiled/transpiled. It seems reasonable this should *just work* without a config file.

**Comment by alexandrudima** [comment]
@billti The reason I filed this is because from the past, I have noticed many users do not even realize they need to create a `jsconfig.json` file to get good language support. And many folks don't read the documentation so they just jump in without a `jsconfig.json` file and see that cross-file suggestions don't work. Would be nice if we have a path to guide them towards adding it...

**Comment by billti** [comment]
We're looking into making the defaults (with or without a config file) work as part of #6690. If we switch to 'commonjs' by default, this issue should evaporate.
