### ISSUE TITLE
Error regression: explanation for Argument of type 'blah' is not assignable to parameter of type 'blah' is missing

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#6676]
error TS2345: Argument of type 'string' is not assignable to parameter of type 'A'
**error TS2345:   Property 'B' is missing in type 'String'** (this line is no longer show in error message)

**Comment by sandersn** [comment]
This might be a result of change #5777. It was an intentional change to drop an extra line of elaboration for the *apparent* type of primitives since in most cases it's completely useless. The commit that removes the extra line is here: c82fe8631513bf9940093b9c9d8d2f6426a3a1dc

The example you give here is arguably better without the extra line too -- we shouldn't need to give examples of 'string' members to show that it's not assignable to 'A'.

**Comment by yuit** [comment]
@sandersn got it. Though I still not understand why it is not useful to give example of members of primitives types vs non-primitives?

**Comment by RyanCavanaugh** [comment]
The general idea is that if you see something like `string is not assignable to HTMLElement`, you already know what's going on and don't need any more explanation.

There's very little intentional assignability between primitives and non-primitives.
