### ISSUE TITLE
Single file compilation with available sources

### ISSUE THREAD

**Issue by jwbeech** [Microsoft/TypeScript#6831]
Hi There

I have started using typescript in some of our projects. We are using a slow approach by only implementing new code in typescript. Due to this approach we have a unique requirement of the compiler and I cannot seem to figure out how to get it to work.

Without using file references in every file (this is a major refactoring headache so staying away from it).

Is it possible for me to compile a **single** typescipt file and pass a list of other files (.ts & .d.ts) to be used as source files for resolving class references.

e.g.:
file_a.ts - Single file to be compiled, references a class in file_b.ts and another class in file_c.d.ts
file_b.ts
file_c.d.ts

I would like the compiler, if possible to use the .tsconfig to find all the source files (file_a.ts, file_b.ts, file_c.d.ts) and then only compile file_a.ts

Any thoughts / help would be greatly appreciated :)

**Comment by mhegazy** [comment]
The commandline compiler will compile all .ts files in one shot. .d.ts files do not have output anyways, so i do not think they are relevant to this question. Can you elaborate on why you need to compile just `file_a.ts` but not `file_b.ts`?

**Comment by jwbeech** [comment]
Managed to sort it out using gulp-typescript and only writing the files that I need to be written. Its a bit slow but serves my needs so will close this ticket.

We need single file compilation for watch tasks during testing in browser and continuous test running, if I build all of my files, we have another n processes triggered which are triggered creating a much much slower workflow. The build process cannot change due to the nature of the integration and framework.

**Comment by thorn0** [comment]
I've just tried to make Grunt recompile only changed files when it's watching for changes. Because otherwise the recompilation delay is too long to be acceptable. But I get a lot of type errors when just a single file is passed to tsc. I'd like to let the compiler somehow know about the rest of the files, just for the types. Ideally it'd be a reference to tsconfig.json,

So I think it's a valid issue. Can we reopen it?

**Comment by mhegazy** [comment]
Most of the time the compiler spend is in type checking, parsing and emit is very small. so if your intend is to decrease the time spent in the compilation process, this approach does not solve it. i suggest looking at splitting your project into smaller ones, with .d.ts generated from one and used as an input to the other (thus limiting the types processed by the checker), and or considering the use of the transpile API, and getting your errors from an IDE instead of needing to build to get them.
