### ISSUE TITLE
Using specialized signatures in relations breaks code with inheritance

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#6886]
Take the following adapted from `lib.d.ts`:

```ts
interface NodeList {
    // ...
}

interface NodeListOf<TNode extends Node> extends NodeList {
    // ...
}

interface Element {
    // ...
    getElementsByTagName(tagname: "a"): NodeListOf<HTMLAnchorElement>;
    getElementsByTagName(tagname: "p"): NodeListOf<HTMLParagraphElement>;
    getElementsByTagName(tagname: string): NodeList;
}
```

Now take a class that extends `Element` from some TypeScript 1.7 code:

```ts
class CustomElement implements Element {
    getElementsByTagName(tagname: string): NodeList {
        // ...
    }
}
```

This used to work because specialized signatures were ignored when it came to compatibility checking. However, it now fails because we try to see if the implementation is assignable to each of the overloads in `Element` - even the specialized ones.

@RyanCavanaugh and I had two ideas here:

My idea is that if the signatures in the base type come from overloads, then we should perform the same compatibility checking as we do for implementations against their overloads. I think this makes sense because you are providing an implementation for a series of overloads anyway, so this would be consistent in that respect.

Ryan's idea is that this code was already wrong from the get-go because it violates the substitution principle and breaks the contract that `Element` provided since CustomElement *looses the overload signatures*. We should not allow users to write this sort of code. I fully agree with this sentiment, but I think it displays shortcomings with how inheritance works today.

**Comment by ahejlsberg** [comment]
I think I agree with Ryan here. This seems like it was just wrong to begin with. The type of the `getElementsByTagName` property in `Element` is

```typescript
{
    (tagname: "a"): NodeListOf<HTMLAnchorElement>;
    (tagname: "p"): NodeListOf<HTMLParagraphElement>;
    (tagname: string): NodeList;
}
```

Any override of that property must have an assignable type and `(tagname: string) => NodeList` isn't enough (because it doesn't promise to return more specific types for `"a"` and `"p"`).

Absent any new rules or mechanisms you need to repeat the overloads in an override. That can be tedious, I agree, but I don't think the solution should be to violate the assignability requirement. Even if we let it slide by, you've now lost the specialized signatures and likely that wasn't what you wanted.

Perhaps we could consider some sort of automatic way it which you "inherit" the specialized signatures, but I don't have any good ideas as to how that would work.

**Comment by DanielRosenwasser** [comment]
So should we port over the specialized signature checks to 1.8, or will this become a break for just 2.0?

**Comment by DanielRosenwasser** [comment]
We'll need to document this.
