### ISSUE TITLE
Provide language service operations in 'tsconfig.json'

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#6890]
It would be nice if

* We could gracefully recover and report errors when a tsconfig.json was invalid (#6600)
* Invalid option combinations got error spans on the options themselves.
* Go to definition worked on files in the `"files"` list.

@bowdenk7

**Comment by basarat** [comment]
Would also like autocomplete :D :rose:

**Comment by mhegazy** [comment]
I do not think we want a new JSON language service. There are already multiple implementations, there is also a JSON schema available to drive completions and validation, and tsconfig.json is available at http://json.schemastore.org/tsconfig. So this is out of the scope of the TS project.

What this issue is better error reporting and recovery for the compiler and tools. This is within the scope. we already have a JS parser, so we should be able to easily handle parsing the file, and gracefully serializing it into a valid compilerOptions object, along with some more actionable diagnostic messages.
