### ISSUE TITLE
cannot use 'require' without assigning it

### ISSUE THREAD

**Issue by pdeva** [Microsoft/TypeScript#6899]
If i have imports like this:

```
import moment = require('moment');
require('moment-duration-format');
```

the 2nd line `require('moment-duration-format')` will fail with msg:

```
error TS2304: Cannot find name 'require'.
```

This is valid javascript and should not result in error.

Using TS 1.7.3

**Comment by yortus** [comment]
`require` is actually not part of JavaScript. You need to include something like [`node.d.ts`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/node/node.d.ts) in your build (`require` is ambiently declared as a global function in that file).

The first line in your example works because earlier versions of TypeScript settled on this syntax for module imports before the ES6 module spec matured, so it's treated specially by the compiler.

**Comment by ahejlsberg** [comment]
You can import a module just for its side effects using an ES2015 style import:

```typescript
import 'moment-duration-format';
```

In fact, you might consider using ES2015 style imports for both:

```typescript
import * as moment from 'moment';
import 'moment-duration-format';
```
