### ISSUE TITLE
Do not show error codes in compiler output

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#693]
Currently the compiler shows "filename.ts: error TS code: message"; the error code is practically useless. so stop showing it by default.

**Comment by DavidBruant** [comment]
In the scenario "developer vs compiler", the error code is indeed fairly useless.
However, I've found it extremely useful in the "developer + Google vs compiler" context because if the error code is useless, it's an excellent way to find other developers who came across the same issue (and hopefully discover if they find a solution and which it is).

**Comment by mhegazy** [comment]
This has been sitting there for a while. We ran into issues with build tools e.g. msbuild fixing this, and there is not an easy way to remove them without breaking other things.
