### ISSUE TITLE
Why not operator overloading in Typescript?

### ISSUE THREAD

**Issue by acterhd** [Microsoft/TypeScript#6936]
Hello. Why not operator overloading in Typescript? I can not found discussion about.

**Comment by kitsonk** [comment]
Can you provide a specific use case of what you are trying to accomplish?

In most of the use cases I can conceive of operator overloading, it would require some sort of run-time emit, which is very anti-pattern for TypeScript.

**Comment by acterhd** [comment]
For example: vector classes. 

```
  var p0 = new Point(0, 0);
  var p1 = new Point(100, 0);
  var p = p0 + p1; //Operator with overload
  var d = 1 !+ 2; //Strict operator (not overloaded)
```

**Comment by RyanCavanaugh** [comment]
See #5407

**Comment by gdefraiteur** [comment]
I want operator overload in typescript!

i write a fuckin game engine in typescript if there is operator overloading in it.

**Comment by nidin** [comment]
@gdefraiteur check out TurboScript with operator overload and pointers which compile to WebAssembly. Even better for game engine 😎

**Comment by gdefraiteur** [comment]
@nidin why not, but the thing is that i like to code with visual studio, and i'm not sure your language is handled in visual studio node project. :/

the interest of typescript for me is that it is usable in such an ide.

**Comment by nidin** [comment]
@gdefraiteur IDE support can be achieved by developing a small plugins. Between TurboScript was a prototype. Prototype phase ended, now I am working on a detailed language spec. https://github.com/turboscriptlang/spec

**Comment by gdefraiteur** [comment]
@nidin  well, then i hope your project will go well and that you ll make those required plugins.

**Comment by nidin** [comment]
@gdefraiteur of course 🙂

**Comment by Ytrog** [comment]
To add my 2 cents: I would like to be able to define a composition operator for function composition like `const composedFunc = f >> g;` or a pipe operator like `const result = textBox.value |> trim;`

**Comment by LinBoLen** [comment]
+1

**Comment by munrocket** [comment]
You can use Proxy. [Here](https://github.com/munrocket/overload-bracket) example of overload operator[] in ES6. As i know it will work in typescript [too](https://www.typescriptlang.org/docs/handbook/advanced-types.html).

**Comment by kungfooman** [comment]
Yea, there is no reason for not doing it. HaXe e.g. compiles to JavaScript aswell and also supports operator overloading. And so does AssemblyScript, which compiles directly from TypeScript to WebAssembly.

Every game developer will thank the implementator of operator overloading.

It probably isn't even that hard, just some simple recursive ast conversions from `a + b` to `node.add(node)` etc. There are quite some examples for that in pure JavaScript and acorn JS parser, e.g. `PaperScript`.

**Comment by MarvinHannott** [comment]
@kungfooman, but it isn't that simple. In fact operator overloading with type inference is hard. And as far as I know, TS doesn't use the Hindley-Milner type system. In effect that means that operator overloading would throw away all of TS's guarantees. For operator overloading to be of any use, the type system needs to be sound and capeable of advanced type inference. TS's type system is neither. Maybe that kind of proposal made more sense for Flow, if it weren't for the fact that they also try not to alter JavaScript in any way. But because Flow tries to be sound instead of pracitcal, it has all the problems TS tries to avoid.
Haxe and Dart (just mentioning) require special JS interop (aka wrappers) and have sound type systems (and Haxe is a very good example how to not do operator overloading).
To wrap it up: It isn't possible. And features like that do hurt compiler performance.

Of course there are other dynamic languages that do support operator overloading, namely Python. But they don't have to worry about type safety. Java doesn't have operator overloading because of all those complications (and some other reasons).

**Comment by Ivanca** [comment]
Why is it hard exactly, I assume is due inheritance and generics?

**Comment by MarvinHannott** [comment]
@Ivanca, because the compiler has to evaluate the order of execution and must then determine if the types are compatible. And the receiving type might not actually be the one you are expecting. A + A doesn't have to result in A.
But this is all theory, the TS team has clearly stated that they don't want to implement any kind of dependent emit.
One must also think about compatibility with existing libraries. Many classes do have an add method but they don't intend it to be used as an operator overload. Should we then use some cryptic special function?

**Comment by Ivanca** [comment]
if A + A always results in A it would be good enough for most use cases, meaning implementing a subset of overloading where all elements must be the exact same type and the result is that same type as well. 

The compatibility is the lesser issues of them all, you can just prefix the methods and be done with it, e.g.  __typescript_add__, __typescript_sub__
