### ISSUE TITLE
Overload Resolution

### ISSUE THREAD

**Issue by evanbb** [Microsoft/TypeScript#6966]
In TypeScript 1.7, method overloads are not properly resolved when base generic interfaces with similar (but different) shapes are involved. For example, in some declaration file:
```
declare interface BaseInterface<D> {
    data: D;
}
declare interface DataOne {
    value: string;
}
declare interface InterfaceOne extends BaseInterface<DataOne> { }

declare interface DataTwo {
    value: string;
    anotherValue: number;
}
declare interface InterfaceTwo extends BaseInterface<DataTwo> { }

declare interface DataHandler<D> {
    (data: D);
}

declare interface SomethingWithSomeOverloads {
    handle(type: InterfaceOne, data: DataOne);
    handle(type: InterfaceTwo, data: DataTwo);
    handle(type: InterfaceOne, handler: DataHandler<DataOne>);
    handle(type: InterfaceTwo, handler: DataHandler<DataTwo>);
}

declare var instanceOfSomethingWithSomeOverloads: SomethingWithSomeOverloads;
declare var instanceOfInterfaceOne: InterfaceOne;
declare var instanceOfInterfaceTwo: InterfaceTwo;

declare var instanceOfDataOne: DataOne;
declare var instanceOfDataTwo: DataTwo;
```
Then, in some consumer code:
```
//this compiles, even though the second parameter should be instanceOfDataTwo
instanceOfSomethingWithSomeOverloads.handle(instanceOfInterfaceTwo, instanceOfDataOne);

//this doesn't compile, as TS thinks the first delegate parameter is a DataOne instance...
instanceOfSomethingWithSomeOverloads.handle(instanceOfInterfaceTwo, (d) => {
    d.anotherValue;
});
```
The first method call compiles when it shouldn't - passing an instance of `DataOne` should only be allowed when the first parameter is of type `InterfaceOne`.  Similarly, the delegate that expects an instance of `DataTwo` gets passed an instance of `DataOne`.

**Comment by RyanCavanaugh** [comment]
The issue here is that `DataTwo` is a *subtype* of `DataOne`. Overload resolution happens *in declaration order* -- the first overload that matches is the one that's selected. So in the example given, the `handle(type: InterfaceTwo, data: DataTwo);` overload is effectively unreachable because anything that would be a valid `DataTwo` call is necessarily a valid `DataOne` call.

Two possible fixes:
* Re-order the overloads such that the `DataTwo` overloads appear first
* Add any member that isn't `anotherValue: number` to `DataOne` so that one type isn't assignable to the other.

**Comment by evanbb** [comment]
Gotcha - thanks for the clarification. I'm a bit spoiled by C#, but there's lots to be said for simpler overload resolution rules - no "best match" algorithm and fewer breaking changes going forward :)

I'm gening a bunch of TS so ordering overloads from most to least specific might be possible. For now I added a unique property on each to ensure they are all distinct shapes.

Thanks again!
