### ISSUE TITLE
Optional parameter with jsdoc does not be respected by salsa intellisense

### ISSUE THREAD

**Issue by Thaina** [Microsoft/TypeScript#6992]
When I use jsdoc to create constructor the intellisense work well. Except a bug that it must obey parameter. It will not know type if the parameter is not all passed in. even it marked as optional by jsdoc

![screen shot 2559-02-10 at 12 02 13 pm](https://cloud.githubusercontent.com/assets/1042507/12939084/240cda72-cfee-11e5-8a05-f8eef6b9cb8c.png)

As the screenshot. air is optional by jsdoc

![screen shot 2559-02-10 at 11 56 43 am](https://cloud.githubusercontent.com/assets/1042507/12939086/2bf5250a-cfee-11e5-9b1b-0bae6381420c.png)

this work but

![screen shot 2559-02-10 at 11 54 19 am](https://cloud.githubusercontent.com/assets/1042507/12939089/325376ae-cfee-11e5-986f-a1e3f52ee421.png)

not

**Comment by billti** [comment]
Testing with the latest `release-1.8` bits and we seem to have fixed this. Note the various different syntaxes supported for optional params below (p2 - p4 are all optional below):

<img width="591" alt="screen shot 2016-02-12 at 11 28 34 am" src="https://cloud.githubusercontent.com/assets/993909/13017950/021d2414-d17c-11e5-8d34-9c762394ecb4.png">

Please try again with the latest bits in the `release-1.8` branch, and if you are still not seeing optionality on params appear problem, comment with more details (ideally some code I can cut/paste), and I'll look into it.

Thanks!

**Comment by Thaina** [comment]
@billti I think you may misunderstand the issue a little

The problem is registering intellisense to constructor

Here is the code I use for test
```
/**
 * @param {string} p0
 * @param {string} [p1]
 */
function Test(p0, p1) {
	this.P0 = p0;
	this.P1 = p1;
}


var test = new Test("");
```

And this is result. When parameter is missing it then make an object created from that constructor to not know what it is

![untitled-1](https://cloud.githubusercontent.com/assets/1042507/13026352/5b4a52c4-d257-11e5-9906-aee842948201.jpg)

**Comment by Thaina** [comment]
@RyanCavanaugh  @billti If you close issue then does you get notification?

**Comment by billti** [comment]
Yes, but it is the weekend (and Monday is a holiday).

**Comment by Thaina** [comment]
@billti OK then I'm apologize. Just not sure that it is or not. Because it still closed

**Comment by RyanCavanaugh** [comment]
So this is a somewhat different issue than what's being described; we should discuss the implications of fixing it.

Currently in TypeScript if you try to invoke a function (or constructor) and zero overloads match, we issue an error and return `unknownType` (which is effectively identical to `any`). This is the general pattern we use everywhere because it stops downstream errors.

However, if there *are* any overloads, we could give a better Salsa (and arguably a better TypeScript) experience by choosing the last overload in the set instead of `unknownType`. That would give you back what we generally believe to be the "most general" return type of the function, and you could start seeing downstream errors.

This is probably the right thing to do everywhere. e.g. today, even in TypeScript, if you say
```ts
function makeString(n: number) {
	return 'the number is ' + n;
}

let j = makeString();
let k = j.subtr(4);
```
you get an error on the initializer for `j`, but nothing on the incorrect spelling of `substr`. That's bad for Salsa (as shown above) and bad for TypeScript because you really do have two errors (not one), and now need to go through two compilation cycles instead of one.

@ahejlsberg any thoughts on this change and/or this pattern in general?

**Comment by RyanCavanaugh** [comment]
Open question with this approach: what to do about generic signatures?
```ts
function fn<T>(x: T, y: T): T { ... }
let x = fn(3, ""); // was x: any, now x: ??
```
