### ISSUE TITLE
name of variable same as class name problem

### ISSUE THREAD

**Issue by abenedykt** [Microsoft/TypeScript#6998]
I've came across a strange behavior. It compiles. WTF! It turned out that it can compile and gives me no warning that I've used variable name same as class name. 

```
class abc{
    run(){
        var hello = new hello();
        hello.name = 'abc';
        hello.surname = 'def';

        hello.b = true;
        var result = hello.selected;
    }
}

class hello{
    name:string;
    surname:string;
}
```

**Comment by vladima** [comment]
Because this is legal javascript 
- names in the function scope can shadow matching names from the enclosing scope
- bindings for `var` declared names are created during (FunctionDeclarationInstantiation)[https://tc39.github.io/ecma262/#sec-functiondeclarationinstantiation] so one can use such name before its declaration.

You can always switch to use `let` or `const` and in this case you'll get `block-scoped variable is used before declaration` error

**Comment by abenedykt** [comment]
True, but I would be happy to get at least a warning that it might give unexpected behavior. I'm heavily concerned that one might find it useful and use it as a feature :)

**Comment by RyanCavanaugh** [comment]
This is a warning under `--noImplicitAny`: 

error TS7022: 'hello' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
