### ISSUE TITLE
Update references of 11.1.5 Object Initializer

### ISSUE THREAD

**Issue by jsoref** [microsoft/TypeScript#7009]
@mihailik noted in #6932 that [ECMA web site](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-object-initializer)

> 12.2.6 Object Initializer
> NOTE 1 An object initializer is an expression describing the initialization of an Object, written in a form resembling a literal. It is a list of zero or more pairs of property keys and associated values, enclosed in curly brackets. The values need not be literals; they are evaluated each time the object initializer is evaluated.

https://github.com/Microsoft/TypeScript/blob/331d26f40271c7a21c6fa74ffac633b45f653dda/src/compiler/checker.ts#L7284
Should probably be revisited:

> ```
>        // This is motivated by ECMA-262 sections 9.3.1, 9.8.1, 11.1.5, and 11.2.1.
> ```

**Comment by mihailik** [comment]
Perhaps the whole repository needs to be checked?

Look at this search: https://github.com/Microsoft/TypeScript/search?utf8=%E2%9C%93&q=ecma

If the numeration of the sections tends to move, maybe it's best to spell out the section names?

Also note, that their URL#hrefs use names rather than numbers too! Those are probably more stable, and even when they break it's easy to find the target applying some common sense and/or Ctrl+F.

**Comment by jsoref** [comment]
FWIW, originally ECMA didn't have named anchors, it was put it because browser vendors complained.

I personally would switch to just using section names (and link to the named sections), but I'm not willing to do that w/o some buy-in from project owners.

**Comment by RyanCavanaugh** [comment]
> I personally would switch to just using section names (and link to the named sections), but I'm not willing to do that w/o some buy-in from project owners.

I think we'd take a PR for that. It certainly doesn't help anyone to have orphaned numbered spec section links.

**Comment by RyanCavanaugh** [comment]
The spec is now an "archived" artifact and we won't be tracking defects against it anymore.
