### ISSUE TITLE
Class properties doesn't inherit types from interface

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/TypeScript#7011]
Moved from Microsoft/vscode#2881
From @moostad 

![aaaa](https://cloud.githubusercontent.com/assets/10362398/12943780/c958a772-cff8-11e5-84ae-cf072516b715.gif)

**Comment by DanielRosenwasser** [comment]
#6118 should fix this, right @sandersn?

**Comment by sandersn** [comment]
No, #6118 only fixes contextual typing of implemented properties. The fix is probably related, but they are two separate bugs.

**Comment by RyanCavanaugh** [comment]
Raw notes
-------

Where did it come from: base class or implemented interface
Is it: Initializer, property declaration, method declaration, or constructor declaration

* Initializers of property declarations without type annotations
  * Contextually type from base class if it exists
  * Contextually type from implemented interfaces if all declarations have identical types
  * Otherwise none
* Method declarations
  * Return expressions get contextually typed by base signature's return type
  * Unannotated parameters get contextually typed by base signature's parameter types
* Unannotated uninitialized declarations
  * Simply get base type's type
  * `foo;` is as if you had written `foo = undefined;`, e.g. get `foo: string` if that was your base type's `foo`
* Same for `static` declarations and constructor parameters

**Comment by IljaDaderko** [comment]
This still seems to be an issue, any development on it? Feels trivial to re-type everything that is already defined in implemented interface

**Comment by sandersn** [comment]
We re-discuss it every six months or so, and haven't come up with any new ways to fix it without breaking old code.

**Comment by robertdempsey** [comment]
@sanderson do you mean breaking old code that's out in the world that's not conforming to interfaces being implemented?

**Comment by sandersn** [comment]
@robertdempsey See [this comment in #6118](https://github.com/Microsoft/TypeScript/pull/6118#issuecomment-216595207) for details under the heading "The ugly". The code there is arguably correct, or at least useful, as-is.

**Comment by RyanCavanaugh** [comment]
Tracking at #10570 now
