### ISSUE TITLE
Are there any merging or extending object that could work in salsa js intellisense?

### ISSUE THREAD

**Issue by Thaina** [Microsoft/TypeScript#7047]
I has to work in js, ECMA version 5, and I try to use many kind of feature available in js5 and jsdoc to merge/extend object. Nothing could result in compatible with intellisense

Are there anything preferable for salsa intellisense?

**Comment by RyanCavanaugh** [comment]
Again, please post some code.

We close issues that do not provide anywhere near enough information to address them because we do not have the resources to go back and forth with "What do you mean by this?". Please look at what other issues in this issue tracker look like to get an idea for what an acceptable issue report looks like.
