### ISSUE TITLE
Defaulting function parameter value failes for null

### ISSUE THREAD

**Issue by ingoe** [Microsoft/TypeScript#7049]
When using function parameter defaulting the resulting javascript fails for ```null ``` values. E.g.:
`(function len(val = ''): number {
    return val.length
}(null))`

View on [TypeScript Playground](http://www.typescriptlang.org/Playground#src=(function%20len(val%20%3D%20'')%3A%20number%20%7B%0A%20%20%20%20return%20val.length%0A%7D(null))) and [fiddlesalad](http://fiddlesalad.com/typescript/typescript-fails-for-parameter-default-value-null/)

**Comment by yortus** [comment]
This behaviour is correct by design. The default parameter is only used if the argument is `undefined`. If you replace `null` with `undefined`, or just pass no argument, then the default value is used.

**Comment by ingoe** [comment]
Then we should maybe question the design. Do you know the rational behind this?

**Comment by yortus** [comment]
TypeScript's rationale is to stick exactly to JavaScript semantics.

For the JavaScript rationale, maybe [start here](http://tc39wiki.calculist.org/es6/default-parameter-values/). Default parameters are only supposed to be substituted when no actual parameter was provided. Due to JavaScript's semantics, this is precisely when the actual parameter value is `undefined`.

As a counter point, what if the default parameter was used whenever the supplied value was *falsy*? This would replace a range of values, including empty strings and `false`, with the default value, which is probably not what was desired in most cases.

**Comment by ingoe** [comment]
Thanks for the explanation. This reminds me why we have libs like underscore.

**Comment by yavuzmester** [comment]
Underscore does not default null values either. Try this:
`_.defaults({x: null}, {x:5})`
