### ISSUE TITLE
Incorrect behavior for moduleResolution classic with relative paths

### ISSUE THREAD

**Issue by use-strict** [Microsoft/TypeScript#7051]
When using "moduleResolution" set to "classic", relative paths appear to be resolved in the same way as module paths, by looking at the parent folder. This behavior is incorrect and generates invalid paths. 

Example:
```typescript
// <root>/A.ts
export default class A {
    test() { console.log("hello world"); }
}
// <root>/some/B.ts
import A from "./A"; // <- this should error

let x = new B();
x.test();
```

This example should not compile. Tested with:
tsc 1.5.3 => doesn't compile (as expected)
tsc 1.6.2, 1.7.5 (moduleResolution = classic) => compiles
tsc 1.6.2, 1.7.5 (moduleResolution = node) => doesn't compile (as expected)

**Comment by use-strict** [comment]
Could be related to https://github.com/Microsoft/TypeScript/issues/5223

**Comment by vladima** [comment]
as bizarre as it may sound this is by design - `classic` resolution strategy always used folder walk to resolve module names. At this point we cannot modify this behavior it as it will be a breaking change since somebody might rely on it.

**Comment by use-strict** [comment]
@vladima , i'm quite positive that it can't be by design because it behaved as expected in tsc 1.5.3. That is unless 1.6 was a breaking change and both moduleResolution methods were different from 1.5, which seems quite wrong to me. I think you misunderstood and confused this to non-relative paths. Please correct me if I'm wrong.

**Comment by vladima** [comment]
I've rechecked and yes in 1.5.3 behavior was slightly different:
- we do discover and include `<root>/A.ts` into the programm so if this has any contributions into the overall compilation (errors or changes in global scope you'll see them).
- however during module name resolution in the checker we stopped and don't return anything because the name is relative.

To me this behavior is inconsistent, pinging @mhegazy for his opinion

**Comment by mhegazy** [comment]
looks like a bug to me.

**Comment by vladima** [comment]
discussed offline: we'll fix the behavior for `classic` mode to not do folder walk if module name is relative or rooted. As a result it behavior for initial case will be:
- module resolution error since now we really cannot find `./A.ts`
- no other effect that can originate in `./A.ts` for the same reason
