### ISSUE TITLE
Is this how you treat question?

### ISSUE THREAD

**Issue by Thaina** [Microsoft/TypeScript#7054]
I have a question about how salsa work. And posting question like this

![untitled-1](https://cloud.githubusercontent.com/assets/1042507/13013363/bf83343e-d1e1-11e5-9a81-3d370e21c096.jpg)

But then this guy closed it and even block it

However there are many thread about question / discussion / suggestion which does not provide any code or information because it is JUST a QUESTION

![untitled-2](https://cloud.githubusercontent.com/assets/1042507/13013407/f2de5282-d1e1-11e5-9b63-2af8989e7dff.jpg)

This guy is a liar.

PS. I think I has provide enough information now right?

**Comment by mhegazy** [comment]
@Thaina please refrain from personal insults on this forum. please keep discussion technical and professional.

We are a small team, we look at questions on this form, SO, gitter, slack, etc.. as well as build the product you. We would love to help everyone all the time, but time is a finite commodity.

Managing issues is an ongoing tax that pay, and we are trying to make it less expensive. If you file an issue please refer to https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md first, please provide details, code is nice and easy to understand vs. prose (specially for non-native English speakers like myself), references to other tools that does something similar, other programming languages where the scenario works, context about what the issue applies to, etc.. in short if you do not know nothing about you can still look at it and investigate it.

@RyanCavanaugh blocked the issue, which is a new policy to limit ppl commenting on issues that have been closed a year ago, which is a real problem we have today.

Please feel free to open a new issue with needed information.

**Comment by Thaina** [comment]
@mhegazy I have already report issue related to the question I post, which is #7046 

But then again, it has no one react to it. So I guess there would be some way you could already done with. So I post a **question** to ask that "Are there anyway you have already done for this problem I would not know anout" in another thread

But then this guy was close it without even looking on it that it is a **question** not bug. Question and suggestion was already exists in this issue am I right? What information is needed more than what I post for a **question** like this?

**Comment by RyanCavanaugh** [comment]
@Thaina I have responded to literally thousands of issues on this issue tracker. 99% of them included enough upfront information that I had at least some clue what they were talking about. I did not wake up this morning with the idea to randomly close and lock a question.

You posted two issues in a row that had zero code, barely any text, and not enough context for me (or anyone else) to understand what was being talked about.

As it says in CONTRIBUTING.md, questions should generally be posted to Stack Overflow. If you have a question you think only we can answer, please be respectful of our time and provide enough information upfront so that we can answer it without excessive back-and-forth.

If you think that there's enough information in the issues you're posting and that there's nothing else you can add to clarify, then I'm sorry, there's clearly too large of a gap for us to reach a conclusion.

**Comment by Thaina** [comment]
@mhegazy Also you said that
>  which is a new policy to limit ppl commenting on issues that have been closed a year ago

My question is not even week old and he block it. What does it mean?

It means he abuse his power over policy

**Comment by mhegazy** [comment]
Not sue there is any "power" abuse involved. we have the "power" to close issues, and you have the "power" to open them :) so we both need to work together here :D

**Comment by Thaina** [comment]
@RyanCavanaugh If questions must be posted to Stack Overflow. Then Why you have label `question` ?

"should generally" is not the same word as "must" am I right?

What I have seen is you have enough time to press close issue. You even have enough time to press block comment button in addition to just close. But not enough time to just said "not enough info" and let me try to post more info after that

The thing is, in that thread, what I post is not issue. I post a question. A question to ask that "How you implement salsa. I don't know what approach I could make object extend another object that salsa could listen to (with ECMA5)"

Should I also state that ECMA5 has no class keyword? Should I need to relate a problem about salsa can't listen to `@typdef`jsdoc from #6976 ? Should I must bring #7046 again to pinpoint that intellisense is not work normally on prototype ?

What kind of information I could provide here?

The information about how salsa work is what I want
And I think only you guys who is owner of the project can answer so I post the question here

You don't have enough time to look at #7046 but you have enough time to close a question you don't want to answer is what I have seen now

Also I was adding more information in #7043 but you already close it
How the hell closing issue that could be a real problem can be solve a problem?

I agree that closing and silencing old issue since one year or even 3 months is great way to keep things not overload. But not yesterday

**Comment by Thaina** [comment]
@RyanCavanaugh Seriously. What I try to ask in that #7054 is I was optimistically think that maybe I just use your product in the wrong way. Maybe you was making it does not work as #7046 for some purpose and I have a better way to write code as you expect us to do

So I was avoid to mention about what it not work and just asking that "how it really work"

Which now I think I am really wrong to have high expectation on you. I'm sorry, I really apologize to have some optimistic way of thinking on you

**Comment by RyanCavanaugh** [comment]
> If questions must be posted to Stack Overflow. Then Why you have label question ?

Because some questions, only our team can answer.

> "should generally" is not the same word as "must" am I right?

Correct

> But not enough time to just said "not enough info" and let me try to post more info after that

If someone comes up to you on the street and says GIVE ME TEN DOLLARS, do you say "No" and keep walking? Or do you patiently wait for them to make a reasoned case about why you should give them ten dollars?

Our time here is a finite, expendable resource. Issues that *aren't even close* to having enough information get closed, because it's the same as the guy interrupting you on the street. That guy can come up to you later and ask again, with a better case, but the initial issue is closed because we're not going to spend all our time interrogating people about what they're talking about.

> I post a question. A question to ask that "How you implement salsa. I don't know what approach I could make object extend another object that salsa could listen to (with ECMA5)"

I implemented the majority Salsa and I have *no clue* what you're trying to say here. It's not even clear that it's a question. I realize there's a language barrier here, but you have to make an effort to provide more information.

> What kind of information I could provide here?

Again, there are literally thousands of issues here. You could open up almost any of them and find things like:
 * Here's some code that I'd like to issue an error, but it doesn't
 * I would expect `x` to show up in a completion list when I write (code block), but it doesn't
 * How do I represent the following type flow: (code block) ?

Yours consisted of a nongrammatical set of words that are each highly ambiguous (do you mean `extend` the keyword, or 'extend' the english word?).

> The information about how salsa work is what I want

This is great and we're happy to provide that information once we understand the question.

> You don't have enough time to look at #7046 but you have enough time to close a question you don't want to answer is what I have seen now

I've already tagged and assigned a milestone to #7046 before you posted that comment, so I don't know what else you want me to do. We work through the issues in the order we see them and we simply hadn't gotten to that one yet.

I don't understand what's wrong about the *order* in which we look at issues. #7046 was logged 10 hours ago, 7 of which I was asleep during, and 1 of which I've spent responding to you calling me a liar, an abuser of power, and other names.

**Comment by Thaina** [comment]
>If someone comes up to you on the street and says GIVE ME TEN DOLLARS

But this is not a street. This is your board of issue that you openly let anyone report problem and you just consider to give any dollar to anyone you liked to
I would not go around asking for ten dollar freely if it not that you state that you welcome people to do

Enough information is subjective terms. You let anyone report you, you may state that you want information. But when someone throw information you not sure about you just shut it that you don't have enough information?

As I said. You have enough time to close issue, which take more times than just said "not enough info". You could then just go do other things until some more info will notify you at any times or never at all but you don't need to spend more time than that. But you spend those time to block it instead. How is it precious ?

If you want to filter for your team, then you may need label "info needed" or "backlog" but not blocking it from comment

**Comment by Thaina** [comment]
> It's not even clear that it's a question

You may not understand my question but to not see it as question is not language barrier that what I'm sure about

> Are there any merging or extending object that could work in salsa js intellisense?

What is this sentence can be if it not question? The question is "Are there something that could work in your system?". Something here is the feature to merge or extend object, and your system here is salsa jsdoc intellisense

> but it doesn't

And as I said. I was asking question that "how it could work" not "why it won't work" so I don't mention about what it fail there. I want to know how you implement this system and what pattern you expect us to work with

Which you have _no clue_ because you never think about it right? You just know it don't have this functionality and I have seen you just add it to next version roadmap

**Comment by Thaina** [comment]
> I've already tagged and assigned a milestone to #7046 before you posted that comment, so I don't know what else you want me to do. We work through the issues in the order we see them and we simply hadn't gotten to that one yet.

#7046 is just before #7047. You have close #7047 2 hours ago so I have post this issue (#7054)

You just interest in #7046 just after I has mention to it here ,the place I was insult you

Which, as I said, you have time to go closing question, not to mention about making argument here, than solving problem

Which also, as I said, closing issue is not the way to solve problem if it is really a problem

**Comment by Thaina** [comment]
@RyanCavanaugh Do you want more information about timestamp of each one? #7047 was closed 2 hours ago, 11:21 at GMT+7. Which leads me to post issue here at 11:42 GMT+7, 20 minutes after it was closed

Then you just go look at #7046 and add label to it at 12:39 GMT+7. More than a hour to just look and add label

Not to mention it because I mention to it here, evidently

![untitled-1](https://cloud.githubusercontent.com/assets/1042507/13016668/bb4cf5f6-d1f2-11e5-9303-6cf25f39f747.jpg)

I know you all need to sleep. I know we live on difference time. I never really have that problem

The problem is first thing you do with my case after you wake up is close and block my question. You understand?

**Comment by mhegazy** [comment]
Thanks @Thaina for your feedback. We have definitely heard you, and we will take your input into consideration as we revisit our issue management policies. We are sorry your experience was not what you expected, or what we aspire for; and hopefully future interactions will be more positive.
