### ISSUE TITLE
Redirect Javascript output to directory does not work on 1.7.6 TypeScript

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [Microsoft/TypeScript#7073]
Have created Nodejs project with NodeJs tools and VS2015. Added "Redirect Javascript output to directory" option:
1) On save .js files ARE NOT created there instead they are created next to .ts files with content
2) On build .js files ARE created in output directory but EMPTY

As I saw this is not first time when this option is not working as expected. It is very annoying to upgrade and downgrade TypeScript versions when you realize that it messes all your project. I think it would be great to have some unit test for this.

**Comment by mhegazy** [comment]
@vytautas-pranskunas- we are sorry about this regression. we have made some architectural changes to make sure these issues do not happen again.
for now, there are two workarounds,
1. use a tsconfig.json at the root of your project (needs TS 1.8), and use that to manage your project properties instead of using the project file
2. unload project, edit the project file, replace `<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">` with `<PropertyGroup Condition="'$(Configuration)' == 'Debug'">` removing the `|$(Platform)` and `|AnyCPU` portions, and it should work again.

again sorry for the inconvenience.

**Comment by JohnKozell** [comment]
Is that all I need to get redirect to work?
I'm upgrading from 1.7.6 and I no longer see the TypeScript build tab in the project properties, and my settings in tsconfig.json seem to be ignored.
Is there more to it than this? Or is my TypeScript broken now for my Visual Studio?

**Comment by paulvanbrenk** [comment]
What did you upgrade to?

**Comment by JohnKozell** [comment]
1.8.6, from here: https://www.microsoft.com/en-us/download/details.aspx?id=48593
Visual Studio reports 1.8.6
TSC.exe was placed in a directory ..\TypeScript\1.8 and reports 1.8.5
I don't know if it should be running when I do a visual studio build, or if I have to use the command line?
I've been playing with the settings and can sometimes get a compile on save, but only if I name the output file App.js...
doesn't seem like it should be this hard. :-(
