### ISSUE TITLE
Specify TypeScript version in solution rather than IDE.

### ISSUE THREAD

**Issue by simonvane** [Microsoft/TypeScript#7078]
I would like to be able to upgrade to Visual Studio 2015 Update 1. The problem is that this will also update the TypeScript compiler to version 1.7. My code does not compile in version 1.7 for some reason so I cannot do this yet.

I think the TypeScript version should be a project option rather than tied to the IDE, that way I can upgrade Visual Studio 2015 to update 1 without having to fix any code and without having to upgrade the build server and get the whole team of devs to upgrade.

Is this possible?

Thank you.

**Comment by meritozh** [comment]
try to use `npm` to install a local special version, and use `glup.js` to compile `TypeScript` for you project.

or maybe you can try to replace the `tsc.exe`...

here are links can help you:
#1110
[Use specific TypeScript compiler version in Visual Studio](https://stackoverflow.com/questions/23245395/use-specific-typescript-compiler-version-in-visual-studio)

**Comment by mhegazy** [comment]
you can set the `TypeScriptToolsVersion` in your project to 1.6 (or which ever version that works for you) and your project will always build against this version of the compiler. The IDE plugin in is not tied to the compiler version, so upgrading the IDE is possible without upgrading the compiler.
Note that since the IDE plugin version is different, you might get different errors from that at build time.

See https://github.com/Microsoft/TypeScript/wiki/Setting-Compiler-Options-in-MSBuild-projects#toolsversion for more information about toolsVersion
