### ISSUE TITLE
Union type of string literals

### ISSUE THREAD

**Issue by andersekdahl** [Microsoft/TypeScript#7090]
With TypeScript 1.8, this code fails:
```
type SomeString = ('string1' | 'string2') & ('string3' | 'string4');
const x: SomeString = 'string1';
```
With the following error: `Type 'string' is not assignable to type '("string1" | "string2") & ("string3" | "string4")'. Type 'string' is not assignable to type '"string1" | "string2"'. Type 'string' is not assignable to type '"string2"'`.

Is this by design? Should it not be possible to use unions for string literal types?

**Comment by yortus** [comment]
The following *does* work:

```typescript
type SomeString = 'string1' | 'string2' | 'string3' | 'string4';
const x: SomeString = 'string1';
```

So it is possible to use unions for string literal types. Your example is an intersection, which `'string1'` cannot possibly satisfy, because it must simultaneously satisfy `'string3'|'string4'`, which it clearly can't.

The error message you are getting from tsc is not very helpful in this case.

**Comment by andersekdahl** [comment]
Ah, completely mixed up union and intersection types, sorry!
Closing this because brain fart.
