### ISSUE TITLE
Unable to do module augmentation

### ISSUE THREAD

**Issue by yortus** [Microsoft/TypeScript#7148]
**TypeScript Version:** 

nightly (1.9.0-dev.20160217)

**Code:**

```ts
// OK - fixed by #6742
declare module 'express' {
    interface Request {
        id: number;
    }
}

// ERROR: Cannot augment module 'knockout' because it resolves to a non-module entity
declare module 'knockout' {
    interface KnockoutStatic {
        track(obj: any, propertyNames?: string[]): any;
        mapping: KnockoutMapping;
    }
}

// ERROR: Cannot augment module 'jquery' because it resolves to a non-module entity
declare module 'jquery' {
    interface JQuery {
        timepicker(): JQuery;
        timepicker(options: TimePickerOptions): JQuery;
    }
}
```

Asking the same thing as #6722, but for `jquery` and `knockout`.

**Comment by DanielRosenwasser** [comment]
I'm assuming that the relevant `.d.ts` files are part of your compilation, right? Do you have a minimal repro?

**Comment by yortus** [comment]
@DanielRosenwasser here's a little repro project: https://github.com/yortus/repro-7148

**Comment by Guria** [comment]
I have failed to augment `moment` as well

**Comment by vladima** [comment]
this is not a bug in implementation but rather the consequence of the fact that currently typings for 'knockout' and 'jquery' are not augmentation-friendly - they both export variable with some global type as module and so i.e. in case of JQuery
```ts
declare module 'jquery' {
    interface JQuery {
        timepicker(): JQuery;
        timepicker(options: TimePickerOptions): JQuery;
    }
}
```

module 'jquery' is [defined](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/jquery/jquery.d.ts#L3207) as 
```ts
declare module "jquery" {
    export = $;
}
declare var jQuery: JQueryStatic;
declare var $: JQueryStatic;
```

so type of 'jquery' is effectively `JQueryStatic` that does not have nested interface `JQuery` thus the failure.

What you can do:

- UMD modules [support](https://github.com/Microsoft/TypeScript/pull/7264) that will be shipped TS 2.0 will support this scenario
- for not since `JQueryStatic` is defined in a global scope you can use global augmentation to patch it.
```ts
/// <reference path="./jquery.d.ts" />
declare global {
    interface JQuery {
        timepicker(): JQuery;
    }
}

$().timepicker();

export {}
```

**Comment by cervengoc** [comment]
@vladima Could you please add a few words about how the above mentioned UMD support solves this? I'm currently stuck with this situation and wouldn't like to use the global scope declarations unless I have no other way.

**Comment by mhegazy** [comment]
> @vladima Could you please add a few words about how the above mentioned UMD support solves this? I'm currently stuck with this situation and wouldn't like to use the global scope declarations unless I have no other way.

http://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html#umd does not cover your question?

**Comment by cervengoc** [comment]
It doesn't get me closer, as I still don't see what the working alternative is for

```
declare module 'jquery' {
    interface JQuery {
        timepicker(): JQuery;
        timepicker(options: TimePickerOptions): JQuery;
    }
}
```

as it still doesn't work at me. The compiler still can't see these extension methods.

**Comment by mhegazy** [comment]
where is `jquery` defined?

**Comment by cervengoc** [comment]
It's installed via the `@types/jquery` NPM package.

**Comment by mhegazy** [comment]
the issue is that Jquery as defined in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/jquery/index.d.ts) is not a module, it is really [a variable](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/jquery/index.d.ts#L3770).

The correct fix is to submit a PR to DefinitelyTyped turning the jquery definition into a module.

Alternatively, you can augment the interface `JQuery`, e.g.:

```ts
declare global {
    interface JQuery {
        timepicker(): JQuery;
        timepicker(options: TimePickerOptions): JQuery;
    }
}
```

**Comment by cervengoc** [comment]
Yes I know that, I was just confused because @vladima wrote in one of the previous posts that there are *two options*, and the first option was to wait for UMD support as it will solve it. The second was to augment the global scope jQuery definitions. 

So basically UMD support doesn't solve this particular issue, as the issue is still with the jQuery definition file if I understand correctly. Thank you for the clarification.

**Comment by mhegazy** [comment]
well, jquery does not use UMD modules. so no, it does not solve the issue for jquery.

**Comment by deadmann** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Build:Cannot augment module 'moment' because it resolves to a non-module entity.	RealEstate	F:\Project2017\S1\BaseProject\RealEstate\RealEstate\Scripts\libs\typings\modules\moment-jalaali\index.d.ts	13	

i have same issue.
