### ISSUE TITLE
Allow `super` constrains for type parameters

### ISSUE THREAD

**Issue by chadaustin** [Microsoft/TypeScript#7265]
I'd like to be able to express constraints in a generic function the opposite direction as `extends`.  For example, I'd like to write something like:

```
class Foo {
	bar: number;
}
function send<T, Foo extends T>(overrides: T) {
}
send({ bar: "hello" }); // this should be a compile error
```

That is, T cannot have any fields not in Foo.

**Comment by RyanCavanaugh** [comment]
Is there a public API that follows this pattern?

**Comment by mhegazy** [comment]
This looks similar to #6613, see https://github.com/Microsoft/TypeScript/issues/7079#issuecomment-183932828

**Comment by vsiao** [comment]
Yeah, sounds like React's `setState` problem:

```ts
class Component<Props, State> {
    setState<T, State extends T>(state: T);
}

**Comment by chadaustin** [comment]
Indeed, very much like React's setState problem.  In my particular case, I have the following function:

```
export function make_model_from<T, U extends T>(instance: U, overrides: T) {
  let override_props = {} as any;
  for (let k in overrides) {
    override_props[k] = { enumerable: true, value: overrides[k] };
  }
  let rv = Object.create(instance, override_props);
  Object.freeze(rv);
  return rv;
}
```

That works wonderfully.

But then I have a utility function built on top of make_model_from that allows specification of a constrained set of overrides:

```
    // I'd like to constrain overrides to so its fields are restricted to a subset of MessageModel.
    // I don't think you can spell that in TypeScript today.
    function send_message(overrides = null) {
      const new_message = make_model_from(message_model, overrides ? overrides : {});
```

Does that make sense?

**Comment by mhegazy** [comment]
looks like what you want is a https://github.com/Microsoft/TypeScript/issues/6613#issuecomment-175314703

so your send_messafe would be something like:
```ts
function send_message<T super typeof message_model>(overrides: T = null) {
   const new_message = make_model_from(message_model, overrides ? overrides : {});
}
```

**Comment by RyanCavanaugh** [comment]
Tracking the general issue of `setState` / JSX property modifications at #7004 since these seem to be the same scenario

**Comment by joewood** [comment]
@RyanCavanaugh not sure if #7004 is the same issue. That seems to be more about reusing the JSX TypeScript feature for Angular Templates. 

Support for optionality of React state (and other scenarios) seems to be close by using f-bounded polymorphism. The support doesn't seem consistent (it works in a function, but not in a method - see here for an example https://github.com/Microsoft/TypeScript/issues/6613#issuecomment-235624676). @ahejlsberg suggests that this is by design in #7079, but I don't see how it does work in a regular function and not in a method.  As I mention in #6613, this has become more of a pain in Typescript 2.0 because making your state members all optional forces massive code changes when using strict null checks.
