### ISSUE TITLE
VS doesn't respond to keyboard inputs when setting "noResolve" to true in tsconfig.json

### ISSUE THREAD

**Issue by genne** [Microsoft/TypeScript#7367]
**TypeScript Version:** 

1.8.6.0

**tsconfig.json**

```ts
...
"noResolve": true
...
```

**Expected behavior:**
VS editor should respond to keyboard inputs when setting "noResolve" to true in tsconfig.json. Currently only responds to delete, tab and copy/paste.

**Actual behavior:** 
VS editor doesn't respond to keyboard inputs when setting "noResolve" to true, except for delete, tab and copy/paste.

**Related issue?**
https://github.com/Microsoft/TypeScript/issues/6392

**Comment by mhegazy** [comment]
i can not reproduce this locally on a new project from template with a tsconfig with only "noResolve". can you share a project that i can look at?

**Comment by genne** [comment]
I've created a sample project here: [TypeScriptHangs](https://github.com/genne/TypeScriptHangs)

Simply open up a .ts file and try to write in it. Nothing happens. Reproduced on three different computers.

**Comment by mhegazy** [comment]
thanks, the repro does help. looks like we were running into an exception looking up a file reference in a dictionary that we did not add previously because of noResolve. I have a fix queued, and should be in the next release. Unfortunately this is the managed VS Plugin portion, and you need a new installer to get to the fix.

why are you using noResolve if i may ask?

**Comment by genne** [comment]
Great to hear!

There is no special reason why we are using noResolve, it was simply part of a skeleton project for Aurelia that we used. Turning it off was an acceptable workaround for us, was mostly a bit frustrating before we realized what was causing the bug.
