### ISSUE TITLE
noEmit should be allowed with outDir

### ISSUE THREAD

**Issue by anilanar** [Microsoft/TypeScript#7397]
And possibly with other `out` variations. Ideally, `noEmit` should have priority over output related options.

Reasoning: I have a syntax checking script that should not actually write files. My build script relies on `tsconfig.json` which has `outDir` compiler option set.

Syntax check command: 
```
> tsc --noEmit 2>&1 | pipe_it_somewhere_for_syntax_checking
```

Build command:
```
> tsc
```

tsconfig.json
```
{
   ...
   "outDir": "build/"
   ...
}
```

Error: `error TS5053: Option 'noEmit' cannot be specified with option 'outDir'.`

**Comment by mhegazy** [comment]
Have you considered using `noEmitOnError`?

**Comment by anilanar** [comment]
Yes. I don't want syntax checker to write files whether there are errors or not.

**Comment by mhegazy** [comment]
> I don't want syntax checker to write files whether there are errors or not.

I am not sure i understood this statement. what is the "syntax checker" here? and who is writing the files?  is it tsc? or some other tool? when do you want them to be written? and when not?

**Comment by anilanar** [comment]
Let's assume I'm the syntax checker, I'm the builder and there are no tools involved. 

To compile, I just run `tsc`. It's done based on my config in tsconfig.json.

In addition, I want to see if there are any errors or not, without writing anything to the disk. So I run `tsc --noEmit`. It complains about `outDir` and `noEmit` not working together.

Obviously there are workarounds for this simple example. I can omit outDir from tsconfig.json, run `tsc --outDir 'path'` to compile and run `tsc --noEmit` to syntax check.

It feels intuitively better for `noEmit` to override output related compiler options instead of returning an error.

**Comment by mhegazy** [comment]
I do not disagree with the original suggestion; I am just wondering why run the compiler twice on the same set of sources?

**Comment by kylecordes** [comment]
@mhegazy  I can't answer for the others, but for me this is because I might want to check from the command line that everything is good, but I in fact never use the output I create by running tsc; the actual work happens from (for example in some projects) webpack.  if I'm running a commandline check that all is well, there's no point in admitting output in any case, because it's going to get ignored anyway and recompiled when webpack run the TS compiler. You might wonder, why ever bother to compile from the command line, since I'm using a different tool to run the compiler for actual output anyway? Probably the same answer as Anil: for a reason, I occasionally want to check from the command line that I have a clean compile.

**Comment by anilanar** [comment]
Another use case is for vim-syntastic. It's a linter tool for vim and supports multiple languages. It uses tsc for typescript by default. It's not supposed to compile and write files so it currently uses `noEmit` option. It breaks if there's a tsconfig.json with `out*` options.

**Comment by mhegazy** [comment]
Thanks for the details. PRs are welcomed. The change will be to remove the error check, do not think anything else is required.
