### ISSUE TITLE
es6 modules must not export unexported identifiers

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#7399]
**TypeScript Version:** 

master

**Code**

```ts
// lib.d.ts
export interface Public extends Private {
}
interface Private {
}
// index.ts
import {
  Public,
  Private // should be an error
} from './lib.d';
```

**Comment by vladima** [comment]
cannot repro:
```ts
// a.ts
import {
  Public,
  Private // should be an error
} from './b';
// b.ts
export interface Public extends Private {
}
interface Private {
}
```
```
node built\local\tsc.js a.ts
a.ts(3,3): error TS2305: Module '"D:/Playground/TypeScript/b"' has no exported member 'Private'.
```

**Comment by falsandtru** [comment]
update:

```ts
// lib.d.ts
export interface Public {
}
interface Private {
}
// index.ts
import {
  Public,
  Private // should be an error
} from './lib.d';
```

I also test on v1.7.5, latest and next.

```
$ npm i typescript@1.7.5
$ node_modules/.bin/tsc index.ts --noEmit -m commonjs
index.ts(3,3): error TS2305: Module '"lib"' has no exported member 'Private'.
```

```
$ npm i typescript@latest
$ node_modules/.bin/tsc index.ts --noEmit -m commonjs
```

```
$ npm i typescript@next
$ node_modules/.bin/tsc index.ts --noEmit -m commonjs
```

@vladima please refer a declaration file.

**Comment by vladima** [comment]
yes, I can repro this: per comment [here](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/binder.ts#L889)
```
 // A declaration source file or ambient module declaration that contains no export declarations (but possibly regular
 // declarations with export modifiers) is an export context in which declarations are implicitly exported.
```

[this](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/binder.ts#L874) function checks if declaration file contains export declaration or export assignments however it does not take into account exported declarations which is certainly strange. 

```ts
// does not report error
// m.d.ts
export interface Public {
}
interface Private {
}
// index.ts
import {
  Public,
  Private // should be an error
} from './m';
```
```ts
// reports error
// m.d.ts
interface Public {
}
interface Private {
}
export {Public};
// index.ts
import {
  Public,
  Private // should be an error
} from './m';
```

However adjusting the behavior will be a breaking change - pinging @mhegazy for the opinion.

**Comment by falsandtru** [comment]
Can you revert this change? Do you need any more info? @vladima @mhegazy

**Comment by mhegazy** [comment]
well.. this is by design. the `export` modifier is optional in an ambient context. everything is implicitly assumed to be `export`ed. the rational is, if you are writing one of these .d.ts files by hand, you do not want to keep writing `export` everywhere.

changing this would be a massive breaking change. just look at how definitelytyped files do not use `export` on all exported declarations. so i do not think we can do this.

As @vladima noted, using an export statement `export {Public}` changes this rule. While this is a subtle distinction, this is the only way to make export statements work without breaking all the pre-1.5 definitions out there.
