### ISSUE TITLE
what is a recommended way for sharing the same code base between commonjs and amd?

### ISSUE THREAD

**Issue by zpdDG4gta8XKpMCd** [microsoft/TypeScript#7403]
Referring modules in CommonJS and AMD is quite different. AMD can understand CommonJS (relative paths) to some extent. CommonJS cannot understand AMD mostly.

So this is the problem. What do I need to do to share the same code base between CommonJS and AMD? What is a best practice for this?

Currently the options known to me are:
- copying the code after compiling so the modules are where the module system can find them
- running a path transformation routine over compiled code

Neither of those look right to me.

**Comment by RyanCavanaugh** [comment]
Good question and I'd love to hear what other people are doing.

My solution for this is to write a config file for requirejs, e.g. https://github.com/RyanCavanaugh/jsx-demo/blob/master/require-config.js

**Comment by DanielRosenwasser** [comment]
In writing [a quick-start guide](https://github.com/Microsoft/TypeScript-Handbook/pull/177) that uses RequireJS, I ended up at basically the same conclusion of using a project-wide `config.ts`.

@RyanCavanaugh, as a heads up, that solution looks problematic because configuration may occur *after* loading `bin-app` (see https://github.com/RyanCavanaugh/jsx-demo/blob/master/index.html#L5-L6), so if I'm not mistaken, it can randomly fail. The solution is to require the module immediately after your configuration has been loaded synchronously.

See [this page on the RequireJS wiki](https://github.com/jrburke/requirejs/wiki/Patterns-for-separating-config-from-the-main-module) for more information.

**Comment by yortus** [comment]
We share code between CommonJS and AMD in our projects. Our approach:
* All TypeScript source is transpiled into CJS modules using `module=commonjs`.
* We use [cajon.js](https://github.com/requirejs/cajon) to load thes CJS modules directly to browsers
* Our require.js/AMD config takes care of mapping URLs to appropriate paths for these static files
* And a few other careful details involving routing, security, etc...

It's definitely not straightforward to do this. But now that we've done it we are happy with our setup - a single codebase with no duplication, a simple build process, and isomorphic javascript where it makes sense.
