### ISSUE TITLE
Generic type defaulting to {} instead of any

### ISSUE THREAD

**Issue by robianmcd** [Microsoft/TypeScript#7505]
**TypeScript Version:** 
1.7.3

**Code**

```ts
window['test'] = {a:1, b:2};

function myFunc<T>(): T
{
    return window['test'];
}

let test = myFunc();
console.log(test.a);
```

**Expected behavior:**
The type of `test` is `any` so there is no compiler error.

**Actual behavior:** 
I get the following error message
myFile.ts(9,18): error TS2339: Property 'a' does not exist on type '{}'.

**Use Case**
I run into this issue whenever I'm working on an Angular project and using the $http service. The type definition for `$http.get()` is as follows

```ts
get<T>(url: string, config?: IRequestShortcutConfig): IHttpPromise<T>;
```

so if you don't explicitly specify what T is you get an error when you try to access the response.

**Comment by sandersn** [comment]
`myFunc` doesn't have any arguments to infer `T` from. So type inference will end up assigning the type `{}` if it's not specified. This behaviour is by design.

I realise this is a cut-down repro, but can you explicitly specify the return type instead of using `T`. If you want `any`, just use `any`.

**Comment by robianmcd** [comment]
When you don't specify a type everywhere else in TypeScript the type defaults to `any` so this behavior seems counter intuitive to me. But yeah I can just specify the type to workaround it.

**Comment by mhegazy** [comment]
https://github.com/Microsoft/TypeScript/pull/6354 would be a better solution here.

**Comment by mhegazy** [comment]
also, you can achieve the same result today by defining an overload.

```ts
function myFunc(): any;
function myFunc<T>(): T;
function myFunc(): any {
    return window['test'];
}
```

**Comment by sandersn** [comment]
I think it's because "T" inside of a function acts like `{}` -- you can't see any properties on it, for example. So if you return T, and the compiler never inferred any actual type for it, it sort of makes sense that it comes out as `{}`.

Also, unlike the other cases where there is no type specified, there is a type *variable* here -- `T` -- which the compiler infers a type for. `{}` indicates failure rather than `any`. `any` would be easier to use, though.

**Comment by robianmcd** [comment]
@mhegazy yeah the issue you linked to would be a good solution. Also I didn't think of overloading the function like that. thanks
