### ISSUE TITLE
[IntelliSense][VSCode] Salsa doesn't work on Ubuntu

### ISSUE THREAD

**Issue by nguymin4** [Microsoft/TypeScript#7534]
**TypeScript Version:**  1.8.2  and nightly (1.9.0-dev.20160217)
**VSCode Version:** 0.10.11
**OS:** Ubuntu 14.04

**Problem**

![loading](https://cloud.githubusercontent.com/assets/6953273/13801076/4a03a6ac-eb37-11e5-96e6-302f7bb80fdd.jpg)

![status](https://cloud.githubusercontent.com/assets/6953273/13801092/60a060d0-eb37-11e5-8b05-b86a4210e31e.jpg)

IntelliSense alway display loading dialog. I tried to update typescript from default version 1.8.2 bundled with VSCode to nightly build but the problem is still there.

Same project, in Windows 10, Salsa does work.

**Comment by billti** [comment]
Do you have any symbolic links in the directory structure at all? Are there any that don't resolve? We just [checked in a fix](https://github.com/Microsoft/TypeScript/commit/b23503cb160768699ec2308b905295c9e4e29aa4#diff-cc0eed295cd2bad794329f871b2669fdR480) today for an issue where Node throws an exception if you do an fs.stat() on a location that is a symlink that doesn't resolve. (So if you try with tonight's nightly and the problem goes away, that was probably it :smile: ).

**Comment by nguymin4** [comment]
Yes, I do have some symbolic links in node_modules but I am not sure if that is the problem.
I find out the culprit is `jsconfig.json`, I just remove it and everything works again. 
But i receive no IntelliSense suggestion from `*.d.ts` files like before.

**Comment by billti** [comment]
It's because removing the jsconfig.json file means we no longer scan all the files/folders under the jsconfig.json location. That means it is not scanning the folders with the symbolic links (and crashing), but it's also not scanning and picking up the .d.ts files.

For your jsconfig.json, you can either use a `files` property to specify which source files make up your program explicitly, or you can use the `exclude` property to tell it which directories not to scan for source files (such as `node_modules`). There are two examples on the page at https://github.com/Microsoft/TypeScript/wiki/tsconfig.json which show the usage of each of these (they are mutually exclusive).

**Comment by nguymin4** [comment]
In the first `jsconfig.json` I wrote, I stated explicitly  `exclude` with `node_modules` and `bower_components` but there was error.
But now, I see the update in documentation in from VSCode now and will try that way. Thank you for your help. Case closed
