### ISSUE TITLE
Error 'cannot be named' when using an exported union-type declaration

### ISSUE THREAD

**Issue by johan-gorter** [Microsoft/TypeScript#7544]
TypeScript Version: 1.8.7

file1:
```ts
export interface I1 {
  foo: string;
}

export interface I2 {
  bar: number;
}

export type I = I1 | I2;
```

file2:
```ts
import {I} from './file1';

export let createI = (): I => {
  return undefined;
};
```

Compile these files with declarations using 
```
tsc --init
tsc -d
```
**Expected behavior:**
Javascript and .d.ts files are generated
**Actual behavior:** 
An error is thrown: `error TS4023: Exported variable 'createI' has or is using name 'I1' from external module "file1" but cannot be named.`

**Comment by mhegazy** [comment]
Well, this is subtle. but it is by design.

The emitter tries to write a name for the type. type aliases are not really types, they are just aliases. so there is nothing called type `I` there is only `I1 | I2`.

Now the type for `createI` is inferred, though it is specified explicitly, it is specified in an assignment, so the actual type of `createI` as the compiler sees it is `() => I1 | I2` (try to hover over it in your editor and you should see the same.); now it tries to write that, but `I1` is not visible in this scope, and writing it would result in an invalid .d.ts. thus the error is generated.

You can specify the type explicitly, as such: `let createI: ()=> I = () => { return undefined; }` and that should be an "explicit" type for `createI`, and the emitter will honor it and write it the way it is. the other option is to export `I` as an interface instead of a type alias.

**Comment by johan-gorter** [comment]
Hooray!

This finally got fixed in https://github.com/Microsoft/TypeScript/tree/v2.9.1
