### ISSUE TITLE
Support of ES6 class constructor property

### ISSUE THREAD

**Issue by blmarket** [Microsoft/TypeScript#7605]
**TypeScript Version:** 

1.7.5

**Code**

```ts
class Foo extends React.Component<any, any> {
 // ... some class definitions
}
Foo.defaultProps = {
  bar: 'baz'
}
```

**Expected behavior:**

No error.

**Actual behavior:** 

TS2339: Property 'defaultProps' does not exist on type 'typeof Foo'.

### Description

Hi, I'd like to create react class using typescript with [ES6 classes](https://facebook.github.io/react/docs/reusable-components.html#es6-classes), and encountered above error.

It would be awesome if I can set class property like above instead of class body. seems typescript does not supports it?

**Comment by Arnavion** [comment]
The error is that by default there is no `defaultProps` static property on `Foo`. So you just have to tell the compiler that you want such a property.

```typescript
class Foo extends React.Component<any, any> {
	static defaultProps: any;
}

Foo.defaultProps = {
  bar: 'baz'
}
```

In general, if the props was of some type `P` instead of `any`, then it would be `class Foo extends React.Component<P, ...` and `static defaultProps: P;`

**Comment by RyanCavanaugh** [comment]
You can also use module merging for slightly less code:

```ts
class Foo { ... }
namespace Foo {
  export const defaultProps = {
    ...
  }
}
```

**Comment by blmarket** [comment]
Thank you very much for kind answers! :+1:
