### ISSUE TITLE
Question: 40xx visibility errors and the specification

### ISSUE THREAD

**Issue by zhuravlikjb** [microsoft/TypeScript#7652]
https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#104-export-declarations

Own example:

```
module M1 {    
    class C {
    }
    export interface F extends C {   // according to the spec, C is not exported and that should be an error
    }
}
```

Example just from the specification:

```
interface A { x: string; }

namespace M {
    interface B { x: A; }
    interface C { x: B; }
    export function foo(c: C) {  }  // according to the spec, this should be an error, to reference non-exported interface in exported function parameter
}
```

But the compiler yields no error in both cases.

Is this specification section obsolete, or is it a compiler bug?

**Comment by mhegazy** [comment]
The spec should be more explicit.

the error is generated iff you are trying to emit declarations (`--declarations`) for your sources. otherwise it is OK.

the rational is, if you are emitting declarations, the emitter needs to write a name for type `C`. this will result in exposing something that is not originally exposed. so all your exported declarations should not use other declarations of lesser visibility. 

if you are not emitting declarations, there is no reason to prohibit you from doing this. `C` is not visible, so callers of `foo`, can not reference `C` by name, but can provide something that is structurally compatible with `C`.

**Comment by RyanCavanaugh** [comment]
The spec is now an "archived" artifact and we won't be tracking defects against it anymore.
