### ISSUE TITLE
Inline callback destructuring does not work with generics

### ISSUE THREAD

**Issue by leonyu** [Microsoft/TypeScript#7679]
**TypeScript Version:** 

1.8.0

**Code**

```ts
function transform<T>(func: (stuff: T) => any) {
	return null;
}

let f = ({a}) => 'foo';
transform(f); // success 
transform(({a}) => 'bar'); // error
```

**Expected behavior:**
Both cases should inference `T` as `{ a: any }`. 

**Actual behavior:** 
If `func` is defined as a variable, it works fine. But if it is inlined, it doesn't work. 

Might be a duplicate of #1729, but this use case has no overload.

**Comment by sandersn** [comment]
This bug is due to contextual typing interfering with type argument inference, not overload resolution. Notice that #1729 doesn't exhibit a difference between an inline reference and a variable reference this bug does. So it's not a duplicate.

I'm not sure what the right behaviour is here, given the limitations of the type inference algorithm. I'll have to think about it.

**Comment by sandersn** [comment]
We can fall back to the shape of the binding pattern if inference only gets `{}`. I'm not sure it's the right thing, but PR #8632 has the change.
