### ISSUE TITLE
Async arrow functions generate broken code when targeting es5

### ISSUE THREAD

**Issue by nevir** [Microsoft/TypeScript#7706]
**TypeScript Version:** Tested on 1.8.9 and Version 1.9.0-dev.20160327

**Code**
```ts
let foo = async (_arg) => {};
```

Compiles to the following (when `{"target": "es5"}`):

```js
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator.throw(value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : new P(function (resolve) { resolve(result.value); }).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments)).next());
    });
};
var foo = function (_arg) __awaiter(this, void 0, void 0, function* () { });
```

**Comment by Arnavion** [comment]
The compiler also gives an error:

`foo.ts(1,11): error TS1057: An async function or method must have a valid awaitable return type.`

It's by design that the compiler emits some output (which may be garbage) even if there's an error. If you don't want the compiler to emit on error then use `noEmitOnError: true`

**Comment by yortus** [comment]
I also reported this a month ago (#7334).

It's not specific to async arrow functions, it's when the async function is an expression (e.g. RHS of assignment) rather than a declaration.

@Arnavion that error `TS1057` is due to an internal check that relies on the existence of `Promise` (which is not in ES5 by default). #7334 defines `Promise`, which unmasks the real problem - that no compiler errors are raised for async function expressions in ES5 even though the generated code is unusable.

**Comment by AppShipIt** [comment]
@yortus @mhegazy I've been ignoring the error and emitting ES5 anyway. I believe it's on the roadmap anyway? If so could this be reopened?

##### Given
```js
async () => aPromise
```

##### ES2015
```js
(() => __awaiter(this, void 0, void 0, function* () { return aPromise; }));
```
##### ES5

```js
(function () __awaiter(this, void 0, void 0, function* () { return aPromise; }));
//           ^ syntax error
```

CC @spicydonuts
