### ISSUE TITLE
2.0: Type guards not working inside callbacks

### ISSUE THREAD

**Issue by jeffreymorlan** [Microsoft/TypeScript#7719]
```ts
function f(x: {}) {
	if (typeof x === 'string') {
		x.charAt(0); // OK
		[1, 2].map(i => x.charAt(i)); // OK in 1.8, error in current master
	}
}
```
This appears to have started with commit dad05642d71408a864e80e0aad34fc43091e38ac

**Comment by Arnavion** [comment]
The new behavior is correct, since TS cannot know when the callback will execute. Consider:

```typescript
var x: {} = "a";
if (typeof x === "string") {
    setTimeout(() => console.log(x.charAt(0)), 0);
}
x = 5;
```

It is wrong to assume `x` is a string when `x.charCodeAt()` is called, as indeed it isn't.

The fix is to bind it to a scoped local:

```typescript
var x: {} = "a";
if (typeof x === "string") {
    let y = x;
    [1, 2].map(i => y.charAt(i));
    setTimeout(() => console.log(y.charAt(0)), 0);
}
```

**Comment by mquandalle** [comment]
Also instead of scoped locals, we can use const. This works just fine:

```ts
function f(x: {}) {
    const y = x;
    if (typeof y === 'string') {
        y.charAt(0);
        [1, 2].map(i => y.charAt(i));
    }
}
```

Having to rename function parameters to use `const` is quite cumbersome though, I hope TS will provide a compiler parameter to assume `const` automatically for all functions parameters as suggested in https://github.com/Microsoft/TypeScript/issues/9491#issuecomment-230132322.
