### ISSUE TITLE
Can't build from root directory where tsconfig.json exists

### ISSUE THREAD

**Issue by volkanceylan** [Microsoft/TypeScript#7767]
**TypeScript Version:** 

1.8

**Code**

I have following tsconfig.json file in my project root directory (e.g. P:\MyProjectRoot\tsconfig.json):

```json
{
    "compileOnSave": true,
    "compilerOptions": {
        "preserveConstEnums": true,
        "experimentalDecorators": true,
        "declaration": false,
        "emitBOM": true,
        "sourceMap": true,
        "outFile": "Scripts/site/Serene.Web.js"
    }
}
```

I have my .ts files under some sub folders of ~/Scripts and ~/Modules directories.

I'm running TypeScript compiler with the following command line:

      P:\MyProjectRoot>"c:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\tsc"

**Expected behavior:**

I expect it to generate a output at P:\MyProjectRoot\scripts\site\Serene.Web.js

**Actual behavior:** 

tsc just exists without generating a file or giving any error.

If i run same command line under P:\MyProjectRoot\scripts:

      P:\MyProjectRoot\scripts>"c:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\tsc"

It generates the expected output.

As a side note, tsc is not in path, not sure if it has any effects.

Also this root folder has a .csproj file with TypeScript configured. I tried to delete all files except tsconfig.json in root directory, but it had no effect.

There is no other tsconfig.json file in subdirectories or parent folders.

**Comment by mhegazy** [comment]
This should be fixed in the next release. there is a problem generating the full path of the tsconfig.json that causes it to ignore it. 

this also occures with `tsc --p .\` or `tsc --p .\tsconfig`

The fix is not available untill the next public release, or through [nightly Nuget packages](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#using-nuget-with-msbuild).

As a work around use `tsc --p <full path to tsconfig.json>`
