### ISSUE TITLE
coercion should be either fully allowed or completely banned

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#7769]
nightly build

```
const x = Math.random() > 0.5 ? 'hey' : 1;
x + ''; // works, because you know strings are special
x + 1; // expected to work too, actual: owie
```

speaking of #7746

**Comment by RyanCavanaugh** [comment]
We do not ban idiomatic JavaScript constructs. There's simply too much code in the world that does stuff like `console.log('The current value of x is ' + x);` and produces a meaningful result.

`x + 1` is a different case. No one idiomatically adds `1` to a non-numeric string, because the resulting `NaN` is meaningless.

**Comment by aleksey-bykov** [comment]
> No one idiomatically adds 1 to a non-numeric string, because the resulting NaN is meaningless.

![image](https://cloud.githubusercontent.com/assets/937933/14214601/f7f91496-f80b-11e5-92c9-b0bda7fc95bb.png)

**Comment by RyanCavanaugh** [comment]
I forgot how JavaScript works -- I was thinking of `*` / `-` / `/` :cry: 

Is the proposal that `string|number` + `number` produce `string|number` ?

**Comment by aleksey-bykov** [comment]
> Is the proposal that string|number + number produce string|number ?

well, who needs it? i personally want #7746
