### ISSUE TITLE
missleading undefined[] in diagnostic message

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#7786]
![image](https://cloud.githubusercontent.com/assets/937933/14226238/5311fd18-f8aa-11e5-8da5-dd07cef6a84a.png)

i suppose that the `[]` literal doesn't infer `undefined` as a type of its elements, does it?

**Comment by DanielRosenwasser** [comment]
Actually it does - try out

```ts
const x: string = [null];
```

and you'll see the `null` type surface itself as well!

Here's what's happening:

1. We've seen an array literal. We try to get the best common type of its elements.
2. There are no elements to infer from. We default to the `undefined` type. Why? Well typically we'll be widened to `any[]` if it matters anyway.
3. `x` has a type annotation. Rather than inferring the widened type of its initializer, we'll just check against `string`.
4. Compare `undefined[]` to `string` and you get this confusing error message.

We have #6524 to track this issue, but since the `null` and `undefined` types are actually going to be representable in 2.0, I'm inclined to say that this is not really bad.
