### ISSUE TITLE
Keywords (e.g. 'delete', 'var') should be valid export names from a module

### ISSUE THREAD

**Issue by davetemplin** [Microsoft/TypeScript#7787]
**TypeScript Version:**  1.8.9

**Code**

```ts
module XFile {
	export function "delete"(path: string): void {
		console.log(path);
	}
}
XFile.delete('test.tmp');
```

**Expected behavior:** Code compiles without error.

**Actual behavior:** Property 'delete' does not exist on 'typeof XFile'.

Please note keywords are valid method names in a class... (see related bug #181)
```ts
class XFile {
	static "delete"(path: string): void {
		console.log(path);
	}	
}
XFile.delete('test.tmp');
```
Arguably a pure a static class such as this should be expressible as an equivalent module.

**Comment by DanielRosenwasser** [comment]
Method names (in both classes and object literals) are expressible as strings because object literal property names could be strings, so they're consistent in that respect.

I don't think we should be deviating from the ECMAScript grammar at the top-level when we can help it, and for that reason I don't think we should be add any special-cases to namespaces (what you've expressed above).

Part of this is to be consistent, and a bigger part of this is that (external) modules are preferable anyway, where you could write

```ts
function del() {

}

export { del as delete };
```

If you really want to use a reserved name for a function for a namespace, you can use class/namespace merging:

```ts
class XFile {
    static delete() {
        // delete
    }
}

namespace XFile {
    // Other members go here
}
```

**Comment by davetemplin** [comment]
Agree with your argument about not deviating from standards. My scenario is around external modules, and the suggested *export {del as delete}* approach actually seems ideal. Didn't occur to me to do it that way--thanks so much for taking the time to suggest it!

**Comment by DanielRosenwasser** [comment]
No problem! Glad to help! :smile:
