### ISSUE TITLE
fix the JS committee decisions, make import module syntax right

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#7793]
`import * as ts form 'typescript'` can't support autocompletion because the source comes after the imported identifiers. Let's do it the right way up: `import from 'typescript' * as ts` (just like Linq [does](https://msdn.microsoft.com/en-us/library/bb383978.aspx)) so we go naturally from a whole to a part, not the other way around

**Comment by aleksey-bykov** [comment]
syntax wise nothing changes the both ways can peacefully co-exist

**Comment by aleksey-bykov** [comment]
even `import from from 'whatever';` is unambiguous:
- current syntax: import the `from` identifier from `'whaterver'`
- proposed syntax: would fail because a string literal is expected coming after `import from`

so the 2 don't intersect

**Comment by DanielRosenwasser** [comment]
I'll note that `import from "typescript" * as ts` is not really useful because you can name the import whatever the heck you want.

The real use would be when you're importing individual members of an import like `import { A, B, C } from "the-alphabet"`. The usual proposal is `from "typescript" import { SyntaxKind };`.

We've gotten this request a good few times:

* #5821
* #5029
* #2371
* #4880

Believe me, I completely get it, but I don't think we could do this without the committee. I wouldn't be against us trying to work with the committee to get an alternate syntax in, but that's a separate problem in general.
