### ISSUE TITLE
Compiled files do not work in webpack (problem with default exports)

### ISSUE THREAD

**Issue by tomitrescak** [Microsoft/TypeScript#7794]
Typescript compiles following 

```
import React from "react";
const dom = React.DOM;
``` 

into following 

```
var react_1 = require("react");
var dom = react_1.default.DOM;
```

Yet, this fails as "react_1.default" is undfined and DOM is directly part of "react_1". As a result it should be:

```
var react_1 = require("react");
var dom = react_1.DOM;
```

How can I make typescript work with reacts default exports? Thanks!

[EDIT] Doing `import * as React from "react";` seems to resolve the issue, but it's a bit messy IMHO

**Comment by DanielRosenwasser** [comment]
`import * as React from "React" is actually the correct way to import React. The problem is that React's documentation only assumes that you are using Babel, and Babel performs a trick to load the default export if the module object has a certain flag on it (see #6296).

If you're piping through Babel (or SystemJS which I've heard also does this), you can use our `--allowSyntheticDefaultImports` flag so that TypeScript understands what the module loader is going to do.
