### ISSUE TITLE
Typing error on JQuery.on()

### ISSUE THREAD

**Issue by mog0** [Microsoft/TypeScript#7827]
TypeScript Version: 1.8.29.0

I've just updated to Visual Studio 2015 Update 2 and the following function that used to work with Update 1, now throws a type error:

```
function on(dialog: JQuery, event: string, callback: Function): void {
    dialog.on(event, callback);
}
```

The error given is: "Error	TS2345	Argument of type 'string' is not assignable to parameter of type '{ [key: string]: any; }'."

I can't see anything wrong with this function, the parameters seem to match those in the JQuery API docs and it has been working for months before the update.

**Comment by mhegazy** [comment]
use `callback: ()=>void` instead of `callback: Function`

The underlying issue is that the definition on definitely typed uses `{ [key: string]: any; }` to mean `any`, but they are not the same. 

this is similar to a previous issue with the definition of data, see https://github.com/Microsoft/TypeScript/issues/4619

@DanielRosenwasser can you submit a change to Jquery definition for this?

**Comment by DanielRosenwasser** [comment]
Sure I'm on it

**Comment by DanielRosenwasser** [comment]
Actually, the problem is really just that `Function` isn't callable, but that is for certain technical reasons. I think @mhegazy's suggestion above is actually a better fix than modifying the JQuery definition.
