### ISSUE TITLE
Click to symbol does not jump to file but to the import (JSX/JS).

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#7930]
_From @admmasters on April 5, 2016 13:34_

- VSCode Version: Version 0.10.14-insider (0.10.14-insider)
- OS Version: OSX 10.11.4

Steps to Reproduce:

1. Cmd+Click on a Component in JSX (also JS).
2. VSCode jumps to the import and not the file itself.

Expected:
VSCode should just jump to the file referenced in the import as its smart enough to know the specific import.

_Copied from original issue: Microsoft/vscode#4964_

**Comment by dbaeumer** [comment]
_From @mquandalle on April 5, 2016 14:12_

I get that behavior also on non-JSX functions.

**Comment by dbaeumer** [comment]
_From @admmasters on April 5, 2016 17:32_

Updated, you are correct.

**Comment by dbaeumer** [comment]
This is how the TS server currently resolved. IMO the behavior is 'technically' correct but not very user friendly. IMO the tsserver should either:

- offer a flag to control that
- resolve the definition to the 'implementation' if the import doesn't rename the symbol
- jump to the import if it does rename the symbol.

**Comment by angelozerr** [comment]
@dbaeumer it seems that the issue https://github.com/Microsoft/TypeScript/issues/7905 is the same than you. My idea is that tsserver should provides a new command "definitions" which returns the 2 definitions. After that when you do Ctrl+Click, the IDE opens a popup to choose which definition you want to go. 

In Eclipse context, you can have several hyperlink. Today I have supported one hyperlink because tsserver can return one definition. If tsserver could return a list of definition, I could have a list of Hyperlink. VSCode could does that too. What do you think about this idea?

**Comment by DanielRosenwasser** [comment]
Is this a duplicate? It might be fixed by #3669.

**Comment by DanielRosenwasser** [comment]
@angelozerr this is *related* but not the same.

**Comment by mhegazy** [comment]
With the fix for https://github.com/Microsoft/TypeScript/issues/3669, we are doing what @dbaeumer suggested as in `2. resolve the definition to the 'implementation' if the import doesn't rename the symbol`.

Resolving this issue as fixed. @angelozerr has https://github.com/Microsoft/TypeScript/issues/7905 to track the other suggestion.
