### ISSUE TITLE
`var __extends` as `--extends` CLI option

### ISSUE THREAD

**Issue by streamich** [Microsoft/TypeScript#7983]
Every time you *extend* a class in TypeScript this code is appended to the transpiled `.js` file:

```js
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
```

Here is a possible quick fix to allow developers remove this code and specify a global `__extends` function for all files. In TypeScript command line tool add an extra parameter `--extends` that allows to provide the code for the `__extends` function.

For example:

```
tsc --extends 'window.myExtends;` hello-world.ts
```

This would output the `__extends` function as:

```js
var __extends = window.myExtends;
```

**Comment by DanielRosenwasser** [comment]
We already have a `--noEmitHelpers` compiler option so that you can define your own `__extends` function yourself in code. Is there any reason that scenario doesn't suffice?

**Comment by streamich** [comment]
@DanielRosenwasser thanks, looks like it does the job. But I'm not sure what exactly that option does, I found in documentation:

> Do not generate custom helper functions like __extends in compiled output.

So, I'm not sure what *else* besides `__extends` it stops to generate, otherwise it's good.

**Comment by DanielRosenwasser** [comment]
That's a good point - it might not be quite as granular as you'd want. But [here are all of the helpers](https://github.com/Microsoft/TypeScript/blob/ac6224d600ceeaca02dad0890b776e004d462e8b/src/compiler/emitter.ts#L342-L387) TypeScript will currently emit.

They're used for:

* Class inheritance
* Decorators & decorator metadata
* Async functions (i.e. `async`/`await`)
* JSX Spread attributes

In any case, for now I think we'll close this (since the extra emit isn't so bad anyhow), but if it becomes a real issue, we can consider making things more granular.

**Comment by streamich** [comment]
1. Yes, more granular would indeed be helpful.
2. What do you exactly mean by *JSX Spread attributes*? For me in `.tsx` files it just generates *Reacts*'s `React.__spread`.
3. BTW, `React.__spread` is deprecated now, will it be replaced in the future?

**Comment by DanielRosenwasser** [comment]
Check out #7270.
