### ISSUE TITLE
Error when assigning to read-only interface properties from merged interfaces

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#7987]
From @nbransby on https://github.com/Microsoft/TypeScript/pull/3333#issuecomment-207822397:

```ts
interface Foo {
    readonly name: string
}

class Foo {
    constructor(name: string) {
        this.name = name; //error
    }
}
```

The above errors stating that `name` is a read-only property; however, if you move the declaration of `name` into the class, then everything works again.

**Comment by mhegazy** [comment]
This looks right to me. if you want to assign to it from the constructor define it in the class.

**Comment by DanielRosenwasser** [comment]
That's fair, though it is a strange inconsistency.

@nbransby, what is the scenario you had in mind?

**Comment by nbransby** [comment]
Well I had the interface defined in one shared project then different implementations in sub projects via declaration merging. Obviously I had to remove the readonly to get it to work but I wanted the objects to be immutable

**Comment by mhegazy** [comment]
@sandersn i assume we are missing one more getMergedSymbol call

**Comment by DanielRosenwasser** [comment]
@nbransby so the class is aware of all of its extensions in subprojects? Or is there a common core between subprojects that all share some common fields which are assumed to be assigned to?

**Comment by nbransby** [comment]
Yes there is a common core that contains the interfaces and the subprojects define classes with the same name instead of implementing the interfaces. The advantage is not having to repeat the variables defined in the interface.

Although since I switched to modules this pattern does not work due to the restrictions on cross module merging. So I've switched to classes in the shared core being extended in the subprojects (from which I've encountered https://github.com/Microsoft/TypeScript/issues/7590)

**Comment by sandersn** [comment]
It turns out that `isReferenceToReadonlyEntity` intentionally does not allow assignment to readonly properties from a different, merged declaration. I think this is correct. The constructor assignment exception shouldn't extend from an interface to a merged class.
