### ISSUE TITLE
Constructor initialisers don't output property metadata.

### ISSUE THREAD

**Issue by jamcoupe** [Microsoft/TypeScript#7991]
**TypeScript Version:** 

Version 1.8.9
Version 1.9.0-dev.20160130

**Code**
Given
```ts
export class Person {
  constructor(@Emit public name: string) {}
}
```

**Expected (Desired) behavior:**
```ts
class Person {
    constructor(name) {
        this.name = name;
    }
}
__decorate([
    ser.Emit, 
    __metadata('design:type', String)
], Person.prototype, "name", void 0);
Person = __decorate([
    __param(0, ser.Emit), 
    __metadata('design:paramtypes', [String])
], Person);
```
**Actual behavior:** 
```ts
class Person {
    constructor(name) {
        this.name = name;
    }
}
Person = __decorate([
    __param(0, ser.Emit), 
    __metadata('design:paramtypes', [String])
], Person);
```

**Comment by andy-ms** [comment]
This behavior is expected. When a decorator appears in a parameter list, it applies only to the parameter even if it is a parameter property. Otherwise it would be ambiguous whether the decorator should be called on the parameter, property, or both (called 2 times).

You can have separate decorators for the property and the parameter:

	function foo(proto, name) {}
	function bar(target, key, index) {}
	export class Person {
		@foo name: string;
		constructor(@bar name: string) {
			this.name = name;
		}
	}
