### ISSUE TITLE
Weak type check for union types.

### ISSUE THREAD

**Issue by volth** [Microsoft/TypeScript#7996]
**TypeScript Version:** 

1.9.0-dev.20160405

**Code**

```ts
class P {
  compare(p: P) {}
}
class R {
  compare(r: R) {}
}
var x: P | R = new P;
var y: P | R = new R;
x.compare(y); // type error expected, as (new P).compare(new R) is called
var z: P & R = null;
x.compare(z); // it is ok

```

**Expected behavior:** I expect type error at compile time

**Actual behavior:** The code is compiled with no error

**Comment by DanielRosenwasser** [comment]
This is because TypeScript's type system is structural and the two are structurally identical. We're looking into better solutions, but if you add some discriminating member or method for each of them, you should get the behavior you want.

```ts
class P {
    __pTag: void;
    compare(p: P) {}
}
class R {
    __rTag: void;
    compare(r: R) {}
}

let x: P | R = new P;
let y: P | R = new R;
x.compare(y); // error.
```

See:

* https://github.com/Microsoft/TypeScript/wiki/FAQ#how-do-i-prevent-two-types-from-being-structurally-compatible
* https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-all-types-assignable-to-empty-interfaces
* https://github.com/Microsoft/TypeScript/wiki/FAQ#why-is-astring-assignable-to-anumber-for-interface-at--
