### ISSUE TITLE
TypeScript version in Visual Studio

### ISSUE THREAD

**Issue by pebezo** [Microsoft/TypeScript#8030]
If I go to Help > About, I see TypeScript 1.8.29.0. If I run the installer from https://www.microsoft.com/en-us/download/details.aspx?id=48593 it doesn't update this value. Is this expected? Thanks.

**TypeScript Version:** 

Well, that's part of the problem... how do I find out what version VS2015 is using?

**Comment by dylanparry** [comment]
Looks like that's the latest version.

Will the tools be updated to include the latest fix for React? At the moment if you have Visual Studio compiling your TypeScript, it still outputs `React.__spread()` calls, whereas the npm and nuget versions have been fixed.

**Comment by pebezo** [comment]
What's puzzling is that I can uninstall all TypeScript installations (from Add/Remove programs) and nothing changes in VS; which makes me wonder if it installed/uninstalled properly.

**Comment by mhegazy** [comment]
Sorry for the confusion, since we are releasing with VS Updates, and sometimes before that, our version numbers get a bit messy. we need to ensure that a new VS Update has a higher version that the same TS release for a previous update. to even make this harder, by the time the VS release is locked down for stabilization we do not know what the next version would be.

so to be safe, we have designated the 1.8.0 - 1.8.7 to be VS 2015 Update 1, and 1.8.2* to be VS 2015 Update 2 installers. 

So 1.8.6 for update 1, has the version 1.8.26 for Update 2 (VS 2015 Update 2 RC).
And 1.8.9 has the version 1.8.29 for update 2.

you can find more details at: https://github.com/Microsoft/TypeScript/releases/tag/v1.8.9

**Comment by mhegazy** [comment]
>  it still outputs React.__spread() calls

The react spread change was not part of TS 1.8.9, but rather TS 1.8.10. see https://github.com/Microsoft/TypeScript/releases/tag/v1.8.10 for more details.

**Comment by pebezo** [comment]
Can you just put the TypeScript compiler version as part of the title (for the extension)? So instead of "TypeScript 1.8.29.0" say "TypeScript (compiler version 1.8) 1.8.29.0"... Quite frankly the compiler version is more important than the tool version.

**Comment by mhegazy** [comment]
but there could me multiple versions of the tools using the same compiler. Let me see if we can make this better the next time around.
