### ISSUE TITLE
Property decorator cannot return a PropertyDescriptor

### ISSUE THREAD

**Issue by JohnWhiteTB** [Microsoft/TypeScript#8063]
From the [documentation](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Decorators.md#property-decorators) regarding decorators:

 > If the property decorator **returns** a value, it will be used as the Property Descriptor for the member.

However, when the return type of the decorator function is actually `PropertyDescriptor` or `TypedPropertyDescriptor` (or whatever type is inferred from the returned object), the compiler strikes with an error, such as in the case of the following:

```typescript
function initNull(target: any, propertyKey: string) {
    return {
        value: null
    };
}

function initNullB(target: any, propertyKey: string): PropertyDescriptor {
    return {
        value: null
    };
}

class Person {
    @initNull // Error...
    public firstName: string;
    
    @initNullB // Error...
    public lastName: string;
}
```

The error message -- both when the return type is explicitly annotated and when it is automatically inferred -- is the following:

 > The return type of a property decorator function must be either 'void' or 'any'.
 > > Unable to resolve signature of property decorator when called as an expression.

Which is strange, as according to the documentation linked above, returning a PropertyDescriptor _is_ supported and as such, I believe I shouldn't need to resort to disabling type-checking to use it, a built-in functionality. If `any` is explicitly specified as the return type, the error obviously goes away, but I feel this might be an oversight.

```
tsc -v
1.8
```

**Comment by sccolbert** [comment]
I'm also facing this same issue. There seems to be a discrepancy here between the docs/spec and the compiler.

**Comment by mhegazy** [comment]
The issue here is that property declarations can not be overwritten. Decorator initialization happen only once at class declaration time, and not in the constructor for every instance. 
non-static properties do not live on the prototype, they live on the instance object, so to change the value the decorator needs to run in the constructor, which is not the case.
the error tells you that a non-static property decorator should return a `void`, since the return value will be ignored by the generated code, (see http://testsite-typescript-41eeb979-7eaa-4c74-9d47-9d182c7b61ab.azurewebsites.net/play/index.html#src=class%20Person%20%7B%0D%0A%20%20%20%20%40initNull%0D%0A%20%20%20%20firstName%3A%20string%3B%0D%0A%7D%0D%0A%0D%0A).

The descriptors that can be overwritten are those on the prototype, i.e. getters/setters and methods.

having said that, the decorator proposal at TC39 is undergoing changes at the moment, that should address some of these concerns. once that proposal is finalized, we should be able to share the new details and how this would impact existing code using decorators. so stay tuned.
