### ISSUE TITLE
It should be possible to ignore errors in d.ts

### ISSUE THREAD

**Issue by Cedware** [Microsoft/TypeScript#8084]
It should be possible to ignore errors in d.ts,
it's pretty annoying to have hundert of errors just because of some definition files of a third party library and it makes it hard to identify your own errors.
So I would recommend a flag in the tsconfig-file to prevent those errors to be mentioned.

**Comment by mhegazy** [comment]
The errors are just a symptom of a bigger issue. they just say that the compiler did not understand these files. if the compiler ignores them silently, checking code that depends on these definitions might not be right, e.g. any's will creep into your code, you might get other errors in your code that would not be explainable, etc..

what kind of errors are you getting, and what is the offending .d.ts file?

**Comment by eberzosa** [comment]
I'm having the same problem. I downloaded a 3rd party definition file (Highcharts) and I'm getting 'Cannot redeclare exported variable' and 'Exports and export assignments are not permitted in module augmentations'

**Comment by RyanCavanaugh** [comment]
@eberzosa which other files do they conflict with?

**Comment by eberzosa** [comment]
Themselves. You can see the file here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/highcharts/highcharts.d.ts

The following lines conflict: 6059 with 6292, and then 6298 gives the agumentation error.

**Comment by mhegazy** [comment]
I do not see any errors in this file by itself. the re-declaration of `Highcharts` is superfluous but should not be an error as they have the same type.

the augmentation error should not happen unless the file is considered a module (i.e. has a top level import or export), which this file does not have. 

Have you modified this file locally? does your local copy match the one on definitelytyped?

**Comment by eberzosa** [comment]
No, my local copy does not match that file. I installed it using typings. Find attached what is downloaded using "typings install dt!highchargs --save" command. And the error VS2015 gives me when I compile the project.

[highchartsdefinitions.zip](https://github.com/Microsoft/TypeScript/files/237172/highchartsdefinitions.zip)
![capture](https://cloud.githubusercontent.com/assets/15267818/14828727/1da4507e-0be0-11e6-847e-11137f69e7d6.PNG)

**Comment by mhegazy** [comment]
looks like a typings issue. Ping @blakeembrey.

**Comment by mhegazy** [comment]
This issue should be filed at https://github.com/typings/typings

**Comment by basarat** [comment]
@eberzosa you need to exclude either `main` or `browser` definitions : https://github.com/typings/typings/blob/master/docs/faq.md#module-resolutions

**Comment by eberzosa** [comment]
@basarat your solution doesn't help. I was only referencing one of the files. Anyway, I did that and nothing changed. Same removing one of the two folders.

**Comment by mhegazy** [comment]
@basarat the issue is not duplicate definition. the issue is the typings tool wrapped the initial module into another module declaration, it removed the extra `declares` but did not remove, 1. the re declaration of the variable (re declaration allowed, but not reexports), and 2. the external module declaration (which turns into an augmentation when wrapped in another module declaration). the net result, an invalid .d.ts file.

**Comment by basarat** [comment]
@eberzosa what's your version of `typings`? It ships with a definition compiler that does the compile locally so versions matter :) :rose:

**Comment by blakeembrey** [comment]
@basarat I pointed out the issue in the `typings` repo. Check the full explanation there, but basically an ambient dependency has been installed as non-ambient (an external module). Since Typings can't properly detect whether something is _really_ an external module or not anymore (because `declare` could be a module augmentation and the flags provided by TypeScript are also wrong since module augmentation was introduced) no error occurs and it's being wrapped up into an ambient module. Once that happens, it falls apart though because the existing `declare` turns into an augmentation and you get duplicate exports on existing `declare var` (there's two duplicates).

**Comment by mhegazy** [comment]
@blakeembrey should not the user get some feedback about the module they are installing, that it is not possible to install as non-ambient?

**Comment by blakeembrey** [comment]
@mhegazy Yes, absolutely should, but I haven't been able to completely refactor it since TypeScript 1.8 augmentations some definitions can be either.

**Comment by mhegazy** [comment]
but if the original file was a script, wrapping it in a module will change its meaning, and that should be an error.

**Comment by eberzosa** [comment]
I installed it as ambient and I stop getting those errors. Thank you all for the help :)

**Comment by blakeembrey** [comment]
@mhegazy Can the compiler correctly tell me if it's _definitely_ a script or not? I haven't been able to.

For reference, the check for that was removed because 1. the module augmentation doesn't appear to require a related import, so there's no real way to know if it's module augmentation or an ambient external module definition and 2. people can be doing weird things like https://github.com/rbuckton/ReflectDecorators - it's abusing the fact you can have something that both appears ambient (script) and external (this is actually the issue that was originally brought up and I couldn't find a way to quickly cater for it).

**Comment by mhegazy** [comment]
> Can the compiler correctly tell me if it's definitely a script or not? 

use `ts.isExternalModule(sourceFile)`

**Comment by mhegazy** [comment]
> it's abusing the fact you can have something that both appears ambient (script) and external (this is actually the issue that was originally brought up and I couldn't find a way to quickly cater for it).

the UMD support hopefully will eliminate the need for such declaration gymnastics.

**Comment by blakeembrey** [comment]
@mhegazy I'll take a look, I have no problem detect if it _shouldn't_ be ambient, it was the reverse direction that was difficult to tell (because by that check installing `ReflectMetadata` would fail).

**Comment by blakeembrey** [comment]
Is that code basically the same check as https://github.com/typings/core/blob/master/src/lib/compile.ts#L442?

**Comment by mhegazy** [comment]
yup. just without the any cast :)

**Comment by blakeembrey** [comment]
Ok, cool. I can correct the usage, but as mentioned I couldn't handle the reverse condition easily. I guess an improvement may be (to detect if external module is valid):

1. Has an external module indicator
2. Has no external module indicator but parent module (`import`er) is an external module

Would that make sense? That way, tricks like `ReflectMetadata` work but direct ambient installations fail.

**Comment by mhegazy** [comment]
I would think you want to check if it is safe to rewrite the declaration file as a ambient module declaration. and it is only safe to do this iff the source file was an external module. if the file is not an external module, then there is no grantee that the output will be correct.

I suppose you could go further, and find an external module declaration e.g. `declare module "Highcharts" {.. }` and then try to inline the file to get teh same module shape, i.e. follow the references from `export = Highcharts`, and build a new module that looks like it, except not global. but this is not a trivial task. so my recommendation is to not do it if it is not safe instead, and/or give the user a meaningful error message.

**Comment by blakeembrey** [comment]
But it's safe to rewrite `ReflectMetadata` and the file is not an external module. Sure, I can enable the check you describe, but it was literally disabled for the use-case of `reflect-metadata`. I'd love to have errors again, of course, but it depended on context so I wanted to check if the check above is enough context for an external module compilation.

**Comment by blakeembrey** [comment]
For reference, the original issue was https://github.com/typings/typings/issues/340 and I do believe it's still a bug - Typings should compile it. I just want to make sure we get errors back to avoid this confusion.

**Comment by mhegazy** [comment]
in general declaration files should not be authored this way, and i would consider `reflect-metadata` is a hack. so hopefully these go away in the future (famous last words :))
