### ISSUE TITLE
Get rid of reference comment tag

### ISSUE THREAD

**Issue by xBodro** [Microsoft/TypeScript#8108]
Why do we need to write comment tags to bring up classes into the scope?
What if I move file into another folder? Should I go though all the usages and correct the path in reference tags?
Why visual studio can't just pick up all the files and compile the project?
Why typescript compiler can't behave like C# compiler? 
Even though the compiler gives me 'Cannot find name XXX' error it still compiles a ts file into js.
Even though the compiler gives me 'Cannot find name XXX' it still correctly find the definition file if I hit F12 
So why on Earth I need to write these comments?

**Comment by basarat** [comment]
> So why on Earth I need to write these comments

Now that we have `tsconfig.json` most people don't. At lest not in the code *they write*. That said they are still good for Typing authors + quick project demonstrations. 

PS: removing them would be a *big* breaking change. Which has got a bit to do with why they are still there :rose:

**Comment by xBodro** [comment]
I have had an empty tsconfig.json that used to do the trick. But now with TS 1.8.30.0 released it stopped working. I've just found out that I need to have at least opening and closing curly braces to make it work. Missing the file makes compiler crazy highlighting every class in my code. Why just not treat missing file as if it were empty? Why not include all files in build list until I explicitly tell to include or exclude certain files?

**Comment by mhegazy** [comment]
> But now with TS 1.8.30.0 released it stopped working

I think this is a bug. do you mind filing a separate issue for it.

> Why just not treat missing file as if it were empty? Why not include all files in build list until I explicitly tell to include or exclude certain files?

missing files where? /// references? if so, do not use /// references. or use `--noResolve`.

**Comment by mhegazy** [comment]
> Why visual studio can't just pick up all the files and compile the project?

it does. not sure what is the issue here. create a new project from "HTML Application with TypeScript", and it does not have any /// <references > and all files are picked up.

> Why typescript compiler can't behave like C# compiler? 

it is exactelly like C# compiler when it comes to VS, and no need to ever use /// references if you do not want to.

> So why on Earth I need to write these comments?

so that you can open a file, with no project, and no tsconfig.json and it figures out its "context". C# does not do that, if you open a loose C# file, you get almost no support from VS except for colorization. JS developers like to edit their files outside projects, so we have added this feature.
it is optional. if you do not like it, do not use it.

**Comment by mhegazy** [comment]
as @basarat mentioned in https://github.com/Microsoft/TypeScript/issues/8108#issuecomment-210437116, this is a huge breaking change that we can not make.
