### ISSUE TITLE
Function#bind/call/apply doesn't return or have same signatures

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#8129]
**TypeScript Version:** 

master

**Code**

```ts
interface F {
  (): number;
  (p): string;
}
var f: F = (<F>null).bind(null);
var c: number = f.call(null);
var a: number = f.apply(null);
```

**Expected behavior:**

```
$ node built/local/tsc.js index.ts
```

**Actual behavior:** 

```
$ node built/local/tsc.js index.ts
index.ts(5,5): error TS2322: Type '(this: void, ...argArray: any[]) => string' i
s not assignable to type 'F'.
  Type 'string' is not assignable to type 'number'.
index.ts(6,5): error TS2322: Type 'string' is not assignable to type 'number'.
index.ts(7,5): error TS2322: Type 'string' is not assignable to type 'number'.
```

**Comment by mhegazy** [comment]
@sandersn looks like the changes to the library had this unintended effect. we should revert these changes, specially that they do not really provide much added type safety.

**Comment by sandersn** [comment]
I think this is a real bug with this function types, not with lib.d.ts. The bug goes away when I rewrite the example plus Function.bind/call/apply to have explicit "this-like" parameters.

**Comment by sandersn** [comment]
Never mind, there was an error in my rewrite.

**Comment by sandersn** [comment]
It turns out this behaviour is in the spec, section 3.10.6. When performing type inference of types with multiple call signatures, the compiler pairs them all up but ignore extra ones *at the beginning*. So `F`'s second call signature will be the only one considered.

In any case, TypeScript doesn't have the capability to have Function.call/apply/bind choose between different overloads based on number of arguments.

**Comment by mhegazy** [comment]
@sandersn , yes. But before it used to return any, after your change it returns something more concrete, which breaks user code. since we concluded that the change does not provide much value in terms of type safety, it seems better to roll it back and unbreak such scenarios.

**Comment by chirayuk** [comment]
I came across this issue while using the nightlies and noticed I lost some type safety.

Is there a recommended practice for this common pattern (imho):

```
// Note that JSX.Element everywhere in this comment is automatically inferred—I'm sticking it in here for the reader.
class Foo extends React.Component<Props, State> {
    _someCallback(): JSX.Element {
        …
    }
    someCallback = this._someCallback.bind(this);
    
    render() {
        // pass along this.someCallback in props somewhere
        // we use the pre-bound method so that shallow comparison of props works correctly
    }
} 
```

The specific error I received (`error TS2453: The type argument for type parameter 'P' cannot be inferred from the usage.`) was because, when using helper function for creating react elements, and the props containing this callback, the type inference is crucial to avoid specifying a nested template argument.

I've worked around it by re-writing as:

```
class Foo extends React.Component<Props, State> {
    someCallback = (): JSX.Element {
        …
    }
```

However, such a method is unavailable to subclasses.  It doesn't matter to me at the moment—but I'd avoid having to make bigger changes if I did need it to be available.

Is there a cleaner bind syntax available that preserves the types or a way of specifying it in the `someCallback = this._someCallback.bind(this);` line?

**Comment by sandersn** [comment]
I'm not sure what you mean when you say that assigning an arrow function is unavailable to subclasses. Could you do the following, or are you talking about a different case?

```ts
class Bar extends Foo {
    someCallback = () => this._someCallback();
}
```

There's not much overhead since `_someCallback` has zero arguments, but of course you'd end up repeating all the arguments if it had more.

**Comment by chirayuk** [comment]
@sandersn

The 2nd code snippet in my comment skipped the `_someCallback` declaration and that's why the arrow function wouldn't be available in the callback.  The common thing in both snippets is that the signature is specified exactly once.  As you correctly point out, a solution is to repeat the full signature a 2nd time when defining the arrow function.  Typically, these bound callbacks, when passed as props to child components, are expected to be called with parameters (that I didn't show in the example.)  If these parameters don't have simple names to refer to them (inline interface definitions, repeated template params), it's ugly repeating them.

This is not a deal breaker or a complaint.  I'm trying to figure out a clean way to create such bindings.  It sounds like the arrow functions are the way to go (or I'd have received an alternate suggestion), so this satisfies my question.  Thanks.

**Comment by chirayuk** [comment]
I just answered my own question.  I can write a helper,

```
function bind<F extends Function, T>(func: F, self: T) {
    return func.bind(self) as F;
}
```

and then

```
someCallback = bind(this._someCallback, this);
```

and that preserves the types.

**Comment by basarat** [comment]
> However, such a method is unavailable to subclasses.

Try not to create deep hierarchies *with overrides* in ReactJs components. 

> I'm trying to figure out a clean way to create such bindings

If you want to use `bind` ([don't recommend that either as you already figured](https://basarat.gitbooks.io/typescript/content/docs/tips/bind.html)) you can use the pattern shown here to return to type safety : https://basarat.gitbooks.io/typescript/content/docs/project/declarationspaces.html :rose: 

```ts
class Foo {
	someCallback() { }
}
declare let _foo: Foo;

class Bar extends Foo {
	_someCallback: typeof _foo.someCallback = this.someCallback.bind(this);
}
```

**Comment by chirayuk** [comment]
@basarat—gotcha.  I don't actually have subclasses in my own code (preferring composition) so point taken.

Thanks for your link to your typescript docs—there's some nice stuff there.
