### ISSUE TITLE
Properties with only getter or setter in an interface

### ISSUE THREAD

**Issue by IKoshelev** [microsoft/TypeScript#814]
Right now interfaces use the same syntax for properties with and without accessors. This is fine for duck typed interfaces, but the problem is, there is no way to specify properties with only one part (getter or setter) present. Usually, they are read only, without setter. The problem is, we can't tell this to a compiler, so it will not warn us when assigning to such a prop and JS runtime will simply ignore this assignment without throwing.

 It would be good to have syntax like this

``` javascript
interface IEmployee{
     get fullName: string;
     set firstName: string;
     set lastName: string; 
}
```

to prevent such errors.

**Comment by justinfagnani** [comment]
This issue doesn't seem like a duplicate of #12, as declaring that a property can be read, and that it can't be set are two very different things.

When I recently tried to write an interface like this:

```typescript
interface HasTemplate {
  get template(): HTMLTempalteElement;
}
```

I wasn't trying to declare that `template` is readonly, only that it can be read.

This could be obviously implemented by a getter:

```typescript
class A implements HasTemplate {
  private _template : HTMLTemplateElement;
  get template() : HTMLTemplateElement { return _ template }
}
```

but also by a field:

```typescript
class B implements HasTemplate {
  template() : HTMLTemplateElement;
}
```

`readonly` seems very different, in that it says explicitly that there is no setter.

Given that JavaScript has getters and setters, it seems like interfaces that describe JavaScript objects should include them. @RyanCavanaugh Any chance this suggestion could be reopened?

**Comment by RyanCavanaugh** [comment]
I don't understand what the distinction is. What's an observable difference between a *property with a getter but no setter* and a *readonly property* ?

**Comment by justinfagnani** [comment]
The difference is between describing having _at_least_ a getter, and describing not having a setter.


| interface  | field | getter | setter | readonly |
| --- | --- | --- | --- | --- |
| field | ✓ | ✓ | ✓ | x |
| getter | x | ✓ | x | x |
| setter | x | x | ✓ | x |
| readonly | x | ✓ | x | ✓ |

**Comment by RyanCavanaugh** [comment]
A read/write property (whether implemented as a field or a get/set pair) is substitutable for a read-only property.

**Comment by justinfagnani** [comment]
@RyanCavanaugh that's... weird. If that's the case, then why was new syntax invented rather than just allowing standard accessors in interfaces? And why is the name of the annotation `readonly` when it seems to mean `readable`?

Anyway, I guess my main questions were answered. Thanks.

**Comment by RyanCavanaugh** [comment]
> that's... weird. 

If a read/write property *weren't* substitutable for a readonly property, the language would be literally unusable.

>  If that's the case, then why was new syntax invented rather than just allowing standard accessors in interfaces?

So that you can write this:
```ts
class X {
  readonly y: number;
}
```

> And why is the name of the annotation readonly when it seems to mean readable?

I don't see why that name would be preferable.
```ts
interface X {
  readable a;
  b;
}
let y: X;
let z = y.b; // must be illegal since 'b' wasn't marked readable
y.a = 1; // might be legal, 'readable' doesn't imply 'not writeable'
```

**Comment by justinfagnani** [comment]
> If a read/write property weren't substitutable for a readonly property, the language would be literally unusable.

I'm more referring to the fact that `readonly` does not actually mean "read only", it means that a property is at least readable, without saying anything about being writable.

> So that you can write this:

JavaScript already has syntax for this though, it's:

```javascript
class X {
  get y() { ... }
}
```

Since I prefer my TypeScript to be as small of a difference from JavaScript as possible (TypeScript team's opinion may differ, of course), and that interfaces are classes without bodies/initializers, I would think that this would be preferable over an entirely new keyword:

```typescript
interface X {
  get y();
}
```

**Comment by jakeknerr** [comment]
> I don't understand what the distinction is. What's an observable difference between a property with a getter but no setter and a readonly property ?

A getter can return an evaluated expression.

```
class X {
  readonly y: number;
}
```
vs.
```
class X {
  get y (): number {
    // return an evaluated expression
    return 10 * 2 + myVar.jingle - 10; // etc.
  };
}
```

Of course you could move get y() into a function on the prototype, like getY,() but I am writing code to conform to an API, so I need to use property accessors. 

+1 for the OP request.
```
interface IEmployee{
     get fullName: string;
     set firstName: string;
     set lastName: string; 
}
```

**Comment by justinfagnani** [comment]
I hit this again when trying to write a declaration for a type that uses accessors, because I forgot that TypeScript doesn't support accessors in interfaces. I still this it's a usability/ergonomics issue, because the most obvious derivation of standard JavaScript syntax into TypeScript interfaces isn't used, but I realize now it's also a correctness issue.

To reiterate the usability issue, when writing a declaration for this class:
```javascript
class X {
  get y() { ... }
}
```

I would expect to be able to just remove any method bodies and write:

```javascript
declare module 'foo' {
  class X {
    get y();
  }
}
```

This is the most obvious thing to try, yet it doesn't work.

As for correctness, there is a difference in the shape of objects between a property and an accessor:

```javascript
class WithProperty {
  x;
  constructor(x) { this.x = x; }
}
class WithAccessors {
  _x;
  constructor(x) { this.x = x; }
  get x() { return this._x; }
  set x(v) { this._x = v; }
}

let withProperty = new WithProperty(1);
withProperty.hasOwnProperty('x'); // true
withProperty.__proto__.hasOwnProperty('x'); // false

let withAccessors = new WithAccessors(1);
withAccessors.hasOwnProperty('x'); // false
withAccessors.__proto__.hasOwnProperty('x'); // true
```

So letting a class declaration describe it's accessors, which live on the prototype, separately from its fields/properties, which live on the instance would be the more correct solution.
