### ISSUE TITLE
Defining a generator on an interface results in a compile error.

### ISSUE THREAD

**Issue by bfgeek** [Microsoft/TypeScript#8258]
**TypeScript Version:** 

1.8.10

**Code**

```ts
interface Foo {
  *generator(): Iterable<number>;
}

class Bar implements Foo {
  *generator(): Iterable<number> {
    yield 1;
    return 2;
  }
}
```

Compile with: `tsc --noImplicitAny --target ES6 Foo.ts `

**Expected behavior:**
Compiles with no warnings :)

**Actual behavior:** 
Foo.ts(2,3): error TS1131: Property or signature expected.
Foo.ts(2,15): error TS1005: ';' expected.
Foo.ts(2,33): error TS1005: '(' expected.
Foo.ts(3,1): error TS1128: Declaration or statement expected.

**Comment by Arnavion** [comment]
A function only needs the `*` if it contains `yield`, and this is a property of the implementation of the function, not the declaration. Since functions in interfaces don't have implementations, they don't need the `*`, so it's not allowed.

A caller of the function only cares that it returns an `Iterable`, not whether it returns an `Iterable` using `yield 1;` or using `return { next: () => { done: true, value: 1 } };`

It's the same for async functions where the intent is expressed via the return type being a `Promise`.

So just write it as `generator(): Iterable<number>;` in the interface.

**Comment by bfgeek** [comment]
Ah thanks for that :) sorry for the noise!
