### ISSUE TITLE
Index signature declarations issues

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#8272]
I got problem define an interface property optional with an index signature:

```ts
export interface HTTPHeaders {
    'Accept'?: string;

    [name: string]: string;
}
```
It gives me the error `string | undefined` is not assignable to `string` with `strictNullChecks`.

**Comment by ahejlsberg** [comment]
That's by design. The type of the `Accept` property is `string | undefined` because it is an optional property, and `string | undefined` isn't assignable to `string`. I'd suggest changing your index signature to be of type `string I undefined`. In general, with `--strictNullChecks` it is somewhat suspect to have index signatures that don't include `undefined` because that's what you're going to get if you try to access a missing property.

**Comment by martine** [comment]
@ahejlsberg is it ever the case that an index signature *won't* need to include undefined?  Perhaps it should always be implied by virtue of it being an index type?

I think there's maybe a case to be made that it's better to be explicit (so you should type out "undefined" each time), but especially in the case of simple map types it feels a bit heavy.

E.g. these types are always wrong:
```js
let x: {[key: string]: string} = {};
function foo(files: {[path: string]: string}) ...
```
because it's always possible to do a lookup for a key that is not found.

**Comment by RyanCavanaugh** [comment]
This was discussed, but it was too annoying for practical use because it's very common to deterministically know that an object does contain a key in a way that is not apparent to the type system
```ts
const names = ['cat', 'dog', 'elephant'];
const obj: { [key: string]: number } = { };
for (const n of names) {
 obj[n] = 2;
}
for (const n of names.filter(n => n.length === 3)) {
 // Error, could be undefined! But not really
 console.log(obj[n] * 2);
}
```
