### ISSUE TITLE
get accessors and this typing

### ISSUE THREAD

**Issue by kitsonk** [Microsoft/TypeScript#8370]
**TypeScript Version:** 

nightly (1.9.0-dev.20160429)

**Code**

```ts
interface Foo {
	readonly foo: string;
}

const foo = {
	get foo(this: Foo): string { // <- A 'get' accessor cannot have parameters.
		return 'foo';
	}
};
```

**Expected behavior:**

Ability to type `this` without errors.

**Actual behavior:** 

Errors given when trying to type `this` in a `get` accessor.

While this example is non-sensical, `this` typing on other `get` accessors would be a useful feature and since they are erasable, it isn't like the accessor has an actual parameter.

**Comment by mhegazy** [comment]
accessors are not checked for this reference at use sites, only call expressions are. so the defined `this` will only be used inside the accessor body. is this the intention?

**Comment by mhegazy** [comment]
//cc: @sandersn

**Comment by kitsonk** [comment]
> so the defined this will only be used inside the accessor body. is this the intention?

Correct.

**Comment by sandersn** [comment]
I made an intentional decision to disallow `this` on accessors because I was not sure of the story and it didn't seem that useful. However, we can discuss this again at the next design meeting.

Some details that need to be decided:
1. Should `this` be checked on access? (As Mohamed points out, this would be a new code path.)
2. How is assignability checked? (I don't know the normal rules for getters, so I'll have to check.)
3. Does the this-type of a getter/setter pair have to match?

**Comment by kitsonk** [comment]
A potentially more "useful" use case:

```typescript
interface Foo {
	value: number;
	readonly asString: string;
}

const foo = {
	value: 0,
	get asString(this: Foo) {
		return String(this.value);
	}
};
```

Essentially because the contextual `this` typing in object literals is removed (for now), there is no way to get intellisense in accessors.

I know it isn't a totally fair comparison, but it is allowed this way:

```typescript
Object.defineProperty(foo, 'asString', {
	enumerable: true,
	get(this: Foo) {
		return String(this.value);
	}
});
```

As far as point 3, my opinion is that it would be logical, since the value to the setter and the return type of the getter have to match.

**Comment by sandersn** [comment]
also note that if you have `--noImplicitThis` turned on, you are forbidden from `this` in accessors inside object literals, because you have no way to annotate them:

```ts
// @noImplicitThis: true
interface Foo {
  value: number;
  readonly asString: string;
  method(this: Foo, n: number): void;
}
const foo: Foo = {
  value: 0,
  get asString() { // sorry, contextual type does not include `this`
    return String(this.value); // and you cannot (currently) annotate it yourself
  }
  method(n) {  // ok, contextual type includes `this`
    console.log(this.n + this.value); 
  }
};
```

**Comment by sandersn** [comment]
Another note from reading the spec:
If one accessor has a type annotation and the other does not, then behave as if both have the type annotation.

**Comment by sandersn** [comment]
I went ahead and tried it out. I'll put up a PR once I clean up the code a bit.

It turns out that, of my concerns, (1) and (2) are red herrings -- there's no way to tear off properties like there is with methods. And as @kitsonk points out, (3) is easily extended from the spec's requirements that parameter types are identical.

So I think it doesn't actually need much discussion. It's a pretty simple addition and it turns out people actually *do* want it. :)

**Comment by natarajanmca11** [comment]
I am not getting the Read-only property at the run time. Actually I am sending the `PageContext` object from client. `Node` web server (`Expressjs`)  request does not receive the read only property. 

Let me know how to resolve this issue.

``` typescript
export class PageContext {
    public PageSize: number;
    public PageNumber: number;
    public get Limit(): number {
        return this.PageSize === 0 ? AppConfig.DefaultPageSize : this.PageSize;
    };
    public get Offset(): number {
        return (this.PageNumber - 1) * this.PageSize;
    };
}
````

![image](https://cloud.githubusercontent.com/assets/9244766/15060627/a65a2356-1380-11e6-855f-5964d76b577b.png)
