### ISSUE TITLE
"this instanceof x" before calling super()

### ISSUE THREAD

**Issue by jjrv** [Microsoft/TypeScript#8416]
I need to detect if a constructor was called without the `new` operator from non-TypeScript code and add it if necessary. The class has a parent class. This code worked at least before TypeScript 1.6:

```TypeScript
constructor() {
    if(!(this instanceof arguments.callee)) {
        return(new (Function.prototype.bind.apply(
            arguments.callee,
            Array.prototype.concat.apply([null], arguments)
        )));
    }

    super();
}
```

Now it instead gives a compiler error:

```
error TS17009: 'super' must be called before accessing 'this' in the constructor of a derived class.
```

But I don't want to call `super` if `this` has a wrong type.

Adding `if(0) super();` to the beginning works but is a bit silly.

**Comment by kitsonk** [comment]
While you have "successfully" tricked the compiler and you *should* be ok when targeting ES5, what the compiler is trying to save you from is runtime behaviour of ES6 Classes, where `this` would actually be `undefined` before that call to `super()`, so if you targeted ES6 you code would break.

Also, you are using `arguments.callee` which is a very bad idea, because it is not available in [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments/callee) and TypeScript emits all modules in strict mode to make it more like how modules will be interpreted in ES6 when loaded.

In ES6, you are supposed to use [`new.target`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target) to detect if the class was constructed without `new`, but I don't think TypeScript can properly down-target this (but maybe it should).

Also, you cannot call ES6 Classes without the `new` keyword, they automatically throw.  If you wanted to replicated that in ES5, you would want to do this instead of using `arguments.callee`, but again after `super()`:

```typescript
class A {
    constructor() {
        if (this && this.constructor !== A) {
            throw new TypeError("Class constructors cannot be invoked without 'new'");
        }
    }
}
```

**Comment by jjrv** [comment]
The current behavior makes sense then. I'll just keep the hack for now and switch to throwing errors later. This is for an Emscripten library, it's going to target ES5 for now.
