### ISSUE TITLE
Type hint for expression of alias type shows "underlying" type

### ISSUE THREAD

**Issue by myitcv** [Microsoft/TypeScript#8440]
```
TypeScript: 1.9.0-dev.20160429 (although shows in playground too)
```

[Playground repro](http://www.typescriptlang.org/play/index.html#src=type%20A%20%3D%20string%3B%0D%0Alet%20x%3A%20A%3B)

```ts
type A = string;
let x: A;
```

**Expected behavior:**

Type of `x` shown via hover should be `A`

**Actual behavior:** 

Type of `x` shown via hover is `string`

**Impact**

I'd noticed this before but assumed it was something we were doing wrong... I think it's fair to assume the above expected behaviour?

The reason this is significant is that we use type aliases for friendlier, shorter types. 

But then in our editor if we're inspecting the type of an expression via the type hint (hover) then we see the massive, underlying type (which isn't at all helpful)

**Comment by malibuzios** [comment]
The thing is I considered, at some point, to suggest that interface types would show the internal structure of the type as an additional piece of information, something like:
```ts
interface Example {
  a: number;
}

let x: Example;
```
And hovering `x` would show something like
```ts
let x: Example ({
  a: number;
})
```
So what I eventually did to work around this was to change many types that were defined as `interface` to use `type` aliases instead, just to get a more detailed information when hovered!

So I feel there are many cases where having this extra information is very useful. So instead of removing detail, the hint could just include the name of the alias, though I personally feel it would be that useful in most cases, perhaps just use `interface` instead?

**Comment by ahejlsberg** [comment]
@myitcv This is the expected behavior. Internally, `A` is simply a symbol that aliases the `string` type, and by the time we resolve the type there is no path back to `A` so to speak. A type can only have one associated name, and for `string` that name is, well, `string`.

There are cases where we could do what you suggest without too much overhead. For example, when declaring a type alias for an anonymous object type (i.e. `type Foo = {...}`) we could possibly associate the name with the anonymous type because it isn't otherwise shared. However, we couldn't easily do the same for union and intersection types because they are hashed and shared based on their structure (i.e. their constituent types), and that sharing is performance critical. So, without deeper changes to the compiler, all we could is *sometimes* show you the type alias name.

**Comment by myitcv** [comment]
@ahejlsberg 

> This is the expected behavior

... given the current implementation.

But would you agree that ideally the alias should be used as the type hint? 

Another area where the underlying type "leaks" out is in compiler errors (can't think why I didn't bring this up in the original post). This is arguably more "serious" than the type hint because it happens far more regularly. Again, there is no correspondence between one's code and the compiler error:

```ts
type A = string;
let x: A;

x = 5;  // type 'number' is not assignable to type 'string'. But x is of type A!!
```

If you have multiple levels of aliasing (as we do) then the problem is further exacerbated: you literally have to remember the "reverse" of the alias in order to decipher the compiler error. Again this is _further_ exacerbated if you have generic type aliases (as we do).

Clearly I'm not keen on sacrificing compiler speed, but debugging these sorts of errors is, at times, a nightmare so anything that can be done to improve this situation would be greatly appreciated.

**Comment by myitcv** [comment]
@mhegazy I'm assuming this has been closed because you consider this behaviour "By Design"?

**Comment by mhegazy** [comment]
Yes. Type aliases are just aliases and not named types. Changing that, while possible, would have perf impact on the compiler and will require some rearchitecting.

**Comment by myitcv** [comment]
@mhegazy thanks. 

> Type aliases are just aliases and not named types


Clearly the example above is a simple one; we have situations like the following:

```ts
type primitive = string | number | boolean;

// Using ImmutableJS
type ImmutableKey = Immutable.IndexedSeq<primitive>;

let x: ImmutableKey;

x = 5; // Type 'number' is not assignable to type 'IndexedSeq<string | number | boolean>
```

How would you advise the developer handle compiler error messages like the above? 

The issue I have with labelling this "By Design" is that it implies a design decision was made that intended for the developer to be left in this situation - given the problems it creates, I think that's unlikely.

**Comment by mhegazy** [comment]
"Design limitation" would be a better label.
