### ISSUE TITLE
Parameter Defaults See Scope of Function Body

### ISSUE THREAD

**Issue by SlurpTheo** [Microsoft/TypeScript#8465]
**TypeScript Version:** 

1.8.10

**Code**

```ts
namespace A {
	"use strict";
	let foo = "out";
	export function bar(func = () => foo) {
		let foo = "in";
		console.log(func());
	}
}
A.bar();
```

**Expected behavior:**
I read http://www.2ality.com/2015/02/es6-scoping.html (section: _5.3. Parameter default values don’t see the scope of the body_) and then tried out:
```js
(() => { "use strict"; let v = "out"; ((f = () => v) => { let v = "in"; console.log(f())})()})()
```
in node v6.0.0 and got the value `'out'`.

**Actual behavior:** 
What TypeScript generates gives you the result `'in'`.

Doesn't matter if you swap `var` for `let`.

**Comment by SlurpTheo** [comment]
FYI: ~same issue


If you read [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters#Functions_defined_inside_function_body) and try:
```ts
// Doesn't work! Throws ReferenceError.
function f(a = go()) {
  function go(){return ":P"}
}
```
in the [playground] (http://www.typescriptlang.org/play/index.html), the error shown isn't because it does not "see" the function `go` (which it shouldn't), it's complaining that the default parameter is a reference to something that isn't declared yet.

![image](https://cloud.githubusercontent.com/assets/5269716/15046777/2a7804bc-12a7-11e6-86fb-47bde1d5795a.png)

**Comment by mhegazy** [comment]
the error is what i would expect. and we should be showing the same error in the case in the OP.

The emitted output will evaluate these initializes in the body of the function, i.e. the function `go` is what the name will point to at runtime, it is probably not what you intended, so it is an error.

**Comment by mihailik** [comment]
@mhegazy your point is based on how TS **implements** codegen for ES6->ES5 translation.

However, in ES6 the original example returns "out", and the latter example fails with ReferenceError: go is not defined. In other words ES6 differs from TSC approach.

That may lead to confusion and obscure issues — I wonder whether the right thing is to keep TSC way of erroring in such cases, but make sure the error message is very clearly tailored to this special case of default initializers.

Also the original example doesn't seem to be reflected in the tests. I think it's a significant case, because unlike the trivial fail/succeed tests, it results in different value being returned based on some obscure treatment. Would be great to make sure the behaviour is well-defined and pegged to one specific outcome.

**Comment by mhegazy** [comment]
> In other words ES6 differs from TSC approach.

that is correct. we are being more restrictive than what ES6 allows. 

> That may lead to confusion and obscure issues

there is an error reported, not sure i see how that would cause confusion.

> Also the original example doesn't seem to be reflected in the tests.

Test PRs are always welcomed.

**Comment by mihailik** [comment]
> there is an error reported, not sure i see how that would cause confusion.
`Initializer of parameter 'func' cannot reference identifier 'foo' declared after it.`

That error in the original use case would cause confusion the reader of the code (even though it is technically correct as per TS spec). Hence my suggestion: treat this case specially, generating bespoke error. Something less academic, clearer and more actionable

`Initializer of parameter 'func' cannot reference local 'foo' from the body of the function, declared at XXX.`

P.S. Sure I'll submit a test PR in the meantime :-)

**Comment by mhegazy** [comment]
A PR for a better error message is also welcomed.
