### ISSUE TITLE
why doesn't this code typecheck?

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#8511]
nightly build

```typescript
export function mapUntilCant<a, b>(
    values: a[],
    canTake: (value: a, index: number) => boolean,
    mapping: (value: a, index: number) => b
): b[] {
    let result: b[] = [];
    for (let index = 0, length = values.length; index < length; index++) {
        let value = values[index];
        if (canTake(value, index)) {
            result.push(mapping(value, index));
        } else {
            return result;
        }
    }
    return result;
}
```

![image](https://cloud.githubusercontent.com/assets/937933/15093533/31940364-1459-11e6-9cc7-f223076f687b.png)

**Comment by malibuzios** [comment]
Best effort so far at reducing this:
```ts
declare function func1<V>(value: V, index: number): any;
 
function func2<T>(values: T[]) {
	
	let index = 0;
	
    for (; ;) {
		
        let value = values[index];
		
        if (func1(value, index)) {
        } else {
            return;
        }
    }
}
```
The error only seems to happen when both `strictNullChecks` and `noImplicitAny` are enabled.

It would not error if:
* The `for` loop is removed.
* `let index = 0` is moved into the body of the `for` loop.
* the `else { return; }` block is removed.
* `0` is used instead of `index` in `let value = values[index]`.
* `0` is used instead of `index` for the arguments of `func1`.

**Comment by ahejlsberg** [comment]
This is a case of the control flow analyzer being a bit too eager in trying to analyze whether the `index` variable could possibly be `undefined` in the `values[index]` expression (which obviously it can't) as it is processing the declaration of the `value` variable. During the (unnecessary) analysis of the flow back in the loop, a check for whether `canTake` is a user defined type guard requires the argument expressions to be resolved, which then forces a circularity in the declaration of `value`.
