### ISSUE TITLE
{ "moduleResolution": "node" } support incomplete; doesn't understand package.json files

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#8527]
_From @mattflix on April 29, 2016 21:46_

- VSCode Version: 1.0.0
- OS Version: Mac OS 10.11.3

Steps to Reproduce:

1. Create the following project structure.
2. Open the root folder in VS Code.
3. Observe errors and poor Intellisense in ./src/entry.js.

It appears that the "Node module resolution" support in VS Code is incomplete, and only understands two variants:

- how to resolve a single [file as a module](https://nodejs.org/api/modules.html#modules_file_modules) (e.g., ./src/node_modules/foo.ts),
- how to resolve a [folder as a module](https://nodejs.org/api/modules.html#modules_folders_as_modules) that contains an "index" file (e.g., ./src/node_modules/bar/index.ts).

It doesn't understand the third variant:

- how to resolve a [folder as a module](https://nodejs.org/api/modules.html#modules_folders_as_modules) that contains a "package" file (e.g., ./src/node_modules/baz/package.json pointing to ./src/node_modules/baz/main.ts).

All three of these variants (in any mixture) are _vital_ to proper support for "Node module resolution" in modular Node project structures.

Also, _none_ of these variants work when the file extensions are .js instead of .ts (even when using a jsconfig.json file or allowJs=true).  This is terrible, and makes VS Code useless for navigating many existing Javascript projects.  The fact than any of the variants work for .ts files is great, but they should definitely work for .js files!

**./tsconfig.json**
```
{
    "compilerOptions": {
        "module": "es6",
        "moduleResolution": "node"
    }
}
```
**./src/entry.ts**
```
import foo from 'foo'; // OK
import bar from 'bar'; // OK
import baz from 'baz'; // [ts] Cannot find module 'baz'.

foo.foo(); // has Intellisense
bar.bar(); // has Intellisense
baz.baz(); // does not have Intellisense
```
**./src/node_modules/foo.ts**
```
export function foo(x: string) {}
```
**./src/node_modules/bar/index.ts**
```
export function bar(y: number) {}
```
**./src/node_modules/baz/package.json**
```
{
    "name": "baz",
    "version": "1.0.0",
    "main": "./main.ts"
}
```
**./src/node_modules/baz/main.ts**
```
export function baz(z: boolean) {}
```

_Copied from original issue: Microsoft/vscode#6001_

**Comment by dbaeumer** [comment]
Moving to TS.

**Comment by mhegazy** [comment]
The TS module resolution uses `"typings"` field in package.json to locate modules. the reason is `"main": "./main.ts"` is not going to work at runtime as .ts will not be executed by node.


see more documentation about module resolution in http://www.typescriptlang.org/docs/handbook/module-resolution.html

**Comment by mattflix** [comment]
@mhegazy  Good point...  my use of main.ts in the package.json is somewhat of a typo then.  But, my point stands, all the standard Node module resolution, and Intellisense that can be derived thereof, should work (to some extent) for plain .js files.

My real point was, the { "moduleResolution": "node" } feature doesn't seem to understand that package.json files refer to code (e.g., the "main" or "browser", which should also be configurable, btw) that should also be statically analyzed and contribute to Intellisense.

**Comment by mhegazy** [comment]
i think you are asking about https://github.com/Microsoft/TypeScript/issues/6670, which is handled by https://github.com/Microsoft/TypeScript/pull/7075

**Comment by mattflix** [comment]
Perhaps.  Although the discussion in those issues gives me pause as well.  The proposed solutions seem to assume that any folder named "node_modules", or code that is located "is up a level", is somehow special.  But, this is not the case.

A folder named "node_modules", wherever it appears, simply has prescribed treatment under Node module resolution rules.  It is highly desirable to take advantage of these rules for project organization, creating a node_modules folder anywhere in your project hierarchy in order to modularize code.  (With zero configuration other than the file structure itself.)

Consider:
```
/project
    /node_modules
    /app
        /node_modules
        /foo
        /bar
```       
Here, /project/app/node_modules might contain private modules used by the "foo" and "bar" components of the application's source code.  Nothing in /project/app/node_modules would be installed or managed by NPM, or considered "read-only".  It is just modularized source code.  If I want to use Intelliense and refactoring features (esp. renaming) to make changes to code residing anywhere under /project/app, it would be nice (read, very useful) to be able to do so with a minimum of fuss.

Sure, the "top-level" node_modules folder (here /project/node_modules) is very often the place where already-baked NPM modules are installed, but tools should not make this assumption, or limit or fix functionality based on it.

**Comment by mhegazy** [comment]
i am sorry i do not understand the issue any more. what is the specific ask from the compiler that it does not support today?
