### ISSUE TITLE
Fluent API "double dot" support:

### ISSUE THREAD

**Issue by pankleks** [Microsoft/TypeScript#8536]
Does anyone thought about adding support for fluent API (something similar/same as Dart does)?
```ts
class A {
  k = 10;
  constructor(private n) {
  }

  run(): void { ... }

  test(): void { ... }
}

new A(2)
  ..k = 20
  ..run()
  ..test();
```

this could be translated to:
```javascript
var a = new A(2);
a.k = 20;
a.run();
a.test();
```

That would simplify a lot writing A class in a way fluent API is supported.

**Comment by aluanhaddad** [comment]
Why not just return `this`?

**Comment by basarat** [comment]
Will not happen till someone does an ESNext proposal for it. I couldn't find one.

Other operators in a similar area (making function chaining easier): 
https://github.com/mindeavor/es-pipeline-operator ([some people did call this double dot in their own languages](https://esdiscuss.org/topic/the-pipeline-operator-making-multiple-function-calls-look-great)) / https://github.com/zenparsing/es-function-bind

Also note that E4X had this operator once :) https://developer.mozilla.org/en-US/docs/Archive/Web/E4X/Processing_XML_with_E4X :rose:

**Comment by pankleks** [comment]
Sorry, not sure if I understand relation between TypeScript and ESNext?
Is TS not all about adding sugar on top of ES spec?

This looks like very nice and straight forward to implement. Could we reuse spec from Dart? Looks mature - at least in this area;)

**Comment by DanielRosenwasser** [comment]
> Is TS not all about adding sugar on top of ES spec?

Nope, TypeScript is mainly about giving a type system on top giving you future features from JavaScript today. Expression level syntax is typically avoided when possible because it can conflict with future specifications. We can revisit this if an ES proposal ever comes along.

**Comment by kitsonk** [comment]
For reference, [TypeScript Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#goals):

> 8) Avoid adding expression-level syntax.

**Comment by basarat** [comment]
> Sorry, not sure if I understand relation between TypeScript and ESNext?

Just another diagram :rose:

![image](https://cloud.githubusercontent.com/assets/874898/15165510/92fd998c-1759-11e6-9d8b-668e66a3e74a.png)

Don't add stuff that might conflict with ESNext otherwise we would no longer be a superset (and will be a disjoint set) :rose:

**Comment by basarat** [comment]
more docs https://basarat.gitbooks.io/typescript/content/docs/why-typescript.html :rose:

**Comment by mindplay-dk** [comment]
@pankleks this is commonly referred to as a "cascade operator" in other languages - can you update the description/title, so that others can find this? (I opened a duplicate issue because I couldn't find this.)

**Comment by aluanhaddad** [comment]
I don't like this pattern because I am _convinced_, without ever having used it mind you 😉, that it is a refactoring hazard. Regardless it encourages mutability while existing fluent interface patterns can be implemented mutably or immutably.

**Comment by mindplay-dk** [comment]
@aluanhaddad my perspective is almost the opposite of yours.

As an alternative to fluent interfaces, personally I find that the cascade operator *reduces* the refactoring hazard - methods that do make changes to state sometimes do need to return a value (e.g. to indicate success, or return some value from the model, etc.) and this breaks fluent interfaces and leads to breaking changes; this is the main reason I strongly discourage coworkers from creating fluent interfaces.

As for immutable types with fluent interfaces, I don't view those as being at all the same thing - I view the fluent methods of immutable objects as being simply factory methods, nothing more. I don't think of those as fluent interfaces - the methods are there for a very different reason, to generate *new* objects; to me that's not the same issue as modifying the state of mutable objects, at all.

You find this pattern encourages mutability, but we're talking about a language where mutable state is by design and a fundamental feature of the language, so I don't see how that's wrong. I personally find that the *absence* of the cascade operator drives people to write fluent interfaces, and to me, that's far more problematic than someone simply using the language the way it was intended to be used. 

(If it's not obvious, I don't partake in the hype/witch-hunt on mutable state, and it's my opinion that the struggle for immutability in mutable languages does more harm than good, as they are simply not a natural fit in an eco-system with a history and codebase almost exclusively built on the foundation of mutable state. There are other languages much better suited for those ideals.)

**Comment by aluanhaddad** [comment]
The hazard is very real. Consider the following code.
```ts
const value = 'abcd';

const result = value
    .replace('a', '')
    ..replace('b', '');

console.log(result); // result is 'acd'
```
That is very very bad.

> You find this pattern encourages mutability, but we're talking about a language where mutable state is by design and a fundamental feature of the language, so I don't see how that's wrong. I personally find that the absence of the cascade operator drives people to write fluent interfaces, and to me, that's far more problematic than someone simply using the language the way it was intended to be used.

Let me clarify, temper what I meant. 
Firstly, programming with mutable state is fine by me. 
Secondly, I mean that it encourages one to express everything in terms of side effects, that is to say encourages one write methods that return `void`, something which JavaScript cannot even express, as opposed to writing methods that return values.

**Comment by mindplay-dk** [comment]
> I mean that it encourages one to express everything in terms of side effects, that is to say encourages one write methods that return void, something which JavaScript cannot even express, as opposed to writing methods that return values.

Frankly that's an *enormous* stretch for me.

Methods should return whatever is meaningful for them to return - that's the problem I'm pointing out with chainable APIs, is it blocks you from making rational decisions (much less changes) about return values.

If people are going to write chainable APIs in lieu of this feature, that's much worse than providing syntax that removes the temptation to abuse the language in this way.

Anyhow, each to his own, I guess.
