### ISSUE TITLE
Allow relative names beginning with `./` in ambient module definitions

### ISSUE THREAD

**Issue by RyanCavanaugh** [microsoft/TypeScript#8601]
There are a few definitions on DefinitelyTyped that include literally hundreds of submodules, e.g. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/material-ui/material-ui.d.ts#L3384

We _could_ convert these into files but it would likely be a massive perf hit (and becomes unmaintanable).

We should have some sort of behavior that allows us to write e.g.

``` ts
declare module './lib/svg-icons/maps/directions-subway' {
  export import MapsDirectionsSubway = __MaterialUI.SvgIcon;
  export default MapsDirectionsSubway;
}
```

and have that be treated as if you actually had a corresponding file on disk.

This should be relatively straightforward; the only question is how to know that we should short-circuit file-based resolution and crack open a definition file to look for these psuedofiles.

/cc @mhegazy @vladima

**Comment by DanielRosenwasser** [comment]
A solution to this could also solve the problem where people want to get bundled `.d.ts` files while still avoiding versioning conflicts.

**Comment by yahiko00** [comment]
I'm wondering what was the design motivation for not allowing relative names for ambient modules? Wouldn't it be more homogeneous and less confusing to allow relative names?

**Comment by basarat** [comment]
@yahiko00 note that it is possible to write the definitions in a manner that its relative path importable. 

The discussion here is purely to make it easier to do `declare "./somethingrelative", and there needs to be thought about how it would behave ... e.g. 

```ts
// foo.d.ts
delcare module "foo"{
  // stuff
}
declare module "./bar" { // What does it mean..... is it `foo/bar` (if so maybe it should be inside `foo'), is it `./bar` everywhere (bad idea) etc.
}
```

:rose:

**Comment by DaSchTour** [comment]
I guess I hit the problem described here, but from another direction.
http://stackoverflow.com/questions/40884048/create-typings-for-module-bundle

I have a mixed ecosystem with JS + TS with namespaces that are just concatenated and new modules that are bundled with systemJS. While bundling with systemJS I add a globalName for better handling in my mixed JS + TS namespace environment. But there is no possibility to create proper typings for this bundle because there is no possibility to export the interfaces from my submodules inside a namespace.

**Comment by RyanCavanaugh** [comment]
Closing due to lack of feedback
