### ISSUE TITLE
Consider loosening strict null checks & implicit return checking in the presence of the 'nothing' type

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#8602]
From a discussion with @wycats.

Currently, even if a type is narrowed down to `nothing`, we still consider control flow errors in those branches even though you might just be handling error cases:

```ts
// Error: Not all code paths return a value.
function foo(x: string | number) {
    if (typeof x === "string") {
        return true;
    }
    else if (typeof x === "number") {
        return false;
    }
    fail("Unexhaustive!");
}

function fail(message: string) {
    throw message;
}
```

Similarly, if you add a type annotation, you'll get an error.

```ts
// Error: Function lacks ending return statement but return type lacks 'undefined'
function foo(x: string | number): boolean {
    if (typeof x === "string") {
        return true;
    }
    else if (typeof x === "number") {
        return false;
    }
    fail("Unexhaustive!");
}

function fail(message: string) {
    throw message;
}
```

**Comment by mhegazy** [comment]
The issue here is that 1. the compiler does not know that these conditions are exhaustive, sometimes it involves multiple variables, and 2. we do not know that `fail` always throws.

we could add a syntactic form of defining that a function always throws, but do not think relaxing the check is the solution. there are valid cases, that you want the compiler to catch.
