### ISSUE TITLE
Using interface of an enumeration and module merged type as generics type parameter

### ISSUE THREAD

**Issue by laszlojakab** [Microsoft/TypeScript#8642]
I found a strange behaviour of enumeration and module merging when using generics. Take a look at the following example:

```typescript
interface IEnumerationType {
	 getNames(): string[];
}

enum RoleType {
	ApplicationRole,
	CompanyRole,
}

module RoleType {
	export function getNames(): string[] {
		return ["ApplicationRole", "CompanyRole"];
	}
}

var r : IEnumerationType = RoleType;
```

It compiles without error. The RoleType implements the IEnumerationType, it has a getNames method because of the enum+module merging.

If I want to use IEnumerationType and RoleType as a generic type parameter, it fails:

```typescript
interface MyInterface<TEnumeration extends IEnumerationType> {
	enumerationType: TEnumeration;
}

var x : MyInterface<RoleType>; // error, why? RoleType implements IEnumerationType
```

Is this a bug or is it a documented behaviour?

**Comment by RyanCavanaugh** [comment]
The type name `RoleType` refers to a value of the enum type. Remember that you would normally write:
```ts
let x: RoleType = RoleType.CompanyRole;
```
The type `RoleType` doesn't implement `IEnumerationType` because it's just a specialized subtype of `number`.

The type of the value `RoleType` itself is actually anonymous; you can refer to it using the `typeof` operator:
```ts
var x : MyInterface<typeof RoleType>; // OK
```

**Comment by laszlojakab** [comment]
Thanks for the help I could solve the problem.
