### ISSUE TITLE
Incorrect tooltips for contextually typed IIFE

### ISSUE THREAD

**Issue by zhuravlikjb** [Microsoft/TypeScript#8661]
Tooltip sometimes shows 'any', despite the fact that the type is correctly inferred:
![iife_tooltip](https://cloud.githubusercontent.com/assets/4499495/15357928/0b968a36-1d02-11e6-95b7-3474f3069789.png)

The same in example:
```ts
((a, b, c) => { a;b;c })("foo", 101, false);
```

Tooltip for 'a' shows 'any', tooltips for 'b' and 'c' show correct types.

**Comment by sandersn** [comment]
During batch compilation, we check the call expression first, which sets `resolvedSignature` to `anySignature` temporarily so that recursive calls between `resolveCall/getContextualTypeOfSignatre` short-circuit. This doesn't happen when checking the parameter directly from the services layer, so the contextual typing recurs a few times before it hits a limit, at which point it just returns `any`.

Probably the new code I wrote for contextually typing IIFEs need to set `resolvedSignature = anySignature` temporarily too.

**Comment by sandersn** [comment]
Yes, that was the fix. It's viewable at #8698.
