### ISSUE TITLE
tsconfig chaining

### ISSUE THREAD

**Issue by khooz** [Microsoft/TypeScript#8671]
Hi,

I was looking for ability to chain tsconfig files in different sources but couldn't find any. Also in the compiler option part of handbook there is a `--project` aka `-p` option that is not included to the tsconfig schema.

It will be great to add this property to the schema as an array of source directories that each has their own tsconfig files and chaining them up. This can potentially lead to a directory structure that deprecates `files` property and will come in handy in big code bases.

Cheers

**Comment by mhegazy** [comment]
tsconfig.json is just a way to pass configurations to the compiler instead of passing them on the command line. A single tsconfig.json represents a single invocation to the compiler (i.e. one call to tsc.exe or tsc.js).

For dependency checking, and building multiple projects, please use a build orchestration tool like gulp, grunt, MSBuild, Broccoli etc...

the `--project` is what you pass to `tsc` to tell it to use a specific `tsconfig.json`. if none was passed the compiler tries to find one automatically by looking for one in any enclosing directory starting by the current directory. 

Thus the property does not make much sense in the tsconfig.json itself, as its importance is to locate the file.
