### ISSUE TITLE
Give better message for rest parameter properties

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#8827]
If I write the following code:

```ts
class C {
    constructor(private ...x) {
    }
}
```

then I get the error `',' expected.`.

Instead, I should get an error like `A parameter property cannot be declared using a rest parameter.`

As motivation, for the following

```ts
class C {
    constructor(private {x}) {
    }
}
```

we currently give the error `A parameter property may not be a binding pattern.`

Additionally, in fixing this, the two should be consistent. Preferably, the new error for the latter should be `A parameter property may not be declared using a binding pattern.`

**Comment by OrangeShark** [comment]
Hello, I am interested in working on this. I already had a chance to look through the code and I am wondering what would be the best way to approach this. Currently the error `',' expected.` is from the parser when trying to parse a parameter list and it considers `private` as a parameter, not a modifier to `...x` because `...` token is not allowed to follow a modifier token. Should this be changed to allow `...` to follow a modifier and then in the checker have the new error message created just like the binding pattern error mentioned above?

**Comment by DanielRosenwasser** [comment]
@OrangeShark yup, that sounds about right. I haven't been in the code recently, but if that's what we currently do for binding patterns, that's what we should probably do here.
