### ISSUE TITLE
Unable to run Array.map on an Array

### ISSUE THREAD

**Issue by xeoneux** [Microsoft/TypeScript#8890]
**TypeScript Version:** 

1.8

**Code**

```ts
function getARPTable() {
    return new Promise((resolve, reject) => {
        arp.table((error, devices) => {
            if (error) reject(error);
            else resolve(devices);
        });
    });
}

async function scanPorts() {
    let devices = await getARPTable();
    console.log(Array.isArray(devices)); // true
    devices = devices.map((device) => device); // error
                      ^
    return true;
}

scanPorts();
```

**Expected behavior:**

No error output

**Actual behavior:** 

` error TS2339: Property 'map' does not exist on type '{}'.`

**Comment by kitsonk** [comment]
TypeScript cannot contextually determine what the `Promise` resolves to (see: #5254) therefore you have to assert it.

Something like:

```typescript
function getARPTable() {
    return new Promise<any[]>((resolve, reject) => {
        arp.table((error, devices) => {
            if (error) reject(error);
            else resolve(devices);
        });
    });
}
```

**Comment by xeoneux** [comment]
@kitsonk Thanks! I created a similar interface to fix it. However, I am still not sure why does the error occur after successful compilation to JavaScript?

**Comment by kitsonk** [comment]
Because, instead of inferring type `any` for the `Promise` resolution, TypeScript infers `{}` which is an object with no properties, therefore doesn't have a `.map` method.  IIRC there was a lot of discussion in the ticket I linked to as to why `{}` instead of `any` makes sense when filling a generic that cannot be contextually determined.  By default, TypeScript will still emit the code, even if it has errors.  So while the run-time behaviour works, TypeScript couldn't be sure it would be when it emitted the code.

**Comment by xeoneux** [comment]
@kitsonk I didn't realise that the error was during compilation and not during runtime. Thanks for the clarification! 😄
