### ISSUE TITLE
Boolean function returns null

### ISSUE THREAD

**Issue by tinchou** [Microsoft/TypeScript#8892]
**TypeScript Version:** 

1.8.10

**Code**

```ts
// A self-contained demonstration of the problem follows...
function bool_fun(value: string) : boolean {
    return value && value == "bug";
}

console.log(bool_fun(null)); // should log false or throw a compiler error, but logs null
console.log(bool_fun("false"));
console.log(bool_fun("bug"));
```

A `boolean` value should always be `true` or `false`, but never `null` (even if it's a falsy value). This would break strict comparisons like `===`. The spec is also very clear: https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#3.2.2

**Expected behavior:**
Either we have a compiler error or the console prints:
```
false
false
true
```

**Actual behavior:** 
The console prints:
```
null
false
true
```

**Comment by basarat** [comment]
> A boolean value should always be true or false, but never null (even if it's a falsy value).

Please compile with `strictNullChecks` and it will be a compile error :rose:

**Comment by tinchou** [comment]
I just tried adding it to my `tsconfig` file without luck (but don't worry, I'll figure it out). Anyway, adding this to my own project won't help if other dependencies are not using it, right?

**Comment by kitsonk** [comment]
@basarat forgot that `strictNullChecks` is only in the pre-release version of TypeScript (`typescript@next`)

The challenge here is that TypeScript before 2.0 (which is in pre-release) did not considered all types to be inclusive of `null` and `undefined` to reflect the run-time behaviour of JavaScript.  With `strictNullChecks`, those types are removed from other types and guarded against.

TypeScript is not changing the runtime behaviour of the code you wrote (which effectively 

But you still have issues with the way you wrote your code, because there are several cases where JavaScript at runtime will short-circuit your logic and return something other than a boolean:

```javascript
console.log(bool_fun(null));
console.log(bool_fun(undefined));
console.log(bool_fun(0));
console.log(bool_fun(''));
```

Of course the third one would be caught by TypeScript today and the first and second one with `strictNullChecks` but the forth one will pass all the type guarding and it is a tough logic error to do static analysis on in TypeScript.  So if you always want something that returns a boolean, write it so it always returns a boolean and don't let runtime JavaScript implicit coercions (or lack there of) ruin your runtime behaviour:

```typescript
function bool_fun(value: string) : boolean {
    return Boolean(value && value == "bug");
}
```

**Comment by tinchou** [comment]
Thanks to both, that's very helpful!

**Comment by mhegazy** [comment]
We can do better here. #8949 contains the fix.
