### ISSUE TITLE
Control flow analysis: T|T[] case, Array.isArray and else case

### ISSUE THREAD

**Issue by Strate** [Microsoft/TypeScript#8935]
**TypeScript Version:** 

1.9.0-dev (nightly)

**Code**

```ts
// A self-contained demonstration of the problem follows...
function <T>(arg: T|T[]) {
  if (Array.isArray(arg)) {
    // arg expected to be T[] here, and it has type T[] (works as expected)
  } else {
    // arg expected to be T here, but it is has type T|T[] (unexpected behaviour)
  }
}
```

**Comment by mhegazy** [comment]
do not think this is accurate. T can be an array.

`foo<number[]>([[1],[2]]);`

**Comment by Strate** [comment]
Same thing about non generic functions:

`arg: string|string[]`

**Comment by mhegazy** [comment]
![animation](https://cloud.githubusercontent.com/assets/8000722/15759936/decd14dc-28c5-11e6-87fe-ab58fcc6537a.gif)

**Comment by Strate** [comment]
@mhegazy Sorry for inconvience, there should be a little more complex case.
```typescript
interface Struct {
    type: string
    [key: string]: any
}
function handle(object: Struct | Struct []) {
    if (Array.isArray(object)) {
        for (let single of object) {
            handle(single)
        }
    } else {
        Object.keys(object).forEach(key => {
            let value = object[key];
            if (Array.isArray(value)) {
                console.log(value.length);
            } else {
                console.log(object.type);
            }
        })
    }
}
```
This code raises compilation error on typescript 1.9.0-dev.20160602-1.0:
```
 error TS2339: Property 'type' does not exist on type 'Struct | Struct[]'. on line `console.log(object.type)`
```
But with typescript 1.8 [everything is ok](http://www.typescriptlang.org/play/index.html#src=interface%20Struct%20%7B%0D%0A%20%20%20%20type%3A%20string%0D%0A%20%20%20%20%5Bkey%3A%20string%5D%3A%20any%0D%0A%7D%0D%0Afunction%20handle(object%3A%20Struct%20%7C%20Struct%20%5B%5D)%20%7B%0D%0A%20%20%20%20if%20(Array.isArray(object))%20%7B%0D%0A%20%20%20%20%20%20%20%20for%20(let%20single%20of%20object)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20handle(single)%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%20else%20%7B%0D%0A%20%20%20%20%20%20%20%20Object.keys(object).forEach(key%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20let%20value%20%3D%20object%5Bkey%5D%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20(Array.isArray(value))%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20console.log(value.length)%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%20else%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20console.log(object.type)%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20%7D)%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A).

**Comment by mhegazy** [comment]
The issue is a change in how narowing works. in TS 1.8 narrowing worked cross function expression/lambda expression, which was not correct; the compiler has no guarantee that `forEach` will call the lambda expression immediately, so making assumptions about the type of `object` is not correct. you can find more information about this in https://github.com/Microsoft/TypeScript/issues/7719#issuecomment-202684512

if `object` was a const, the compiler will narrow correctly the type through the function expressions, as it knows it can not be modified once captured. so:

```ts
function handle(obj: Struct | Struct []) {
    const object = obj;  // capture it in a const
    if (Array.isArray(object)) {
        for (let single of object) {
            handle(single)
        }
    } else {
        Object.keys(object).forEach(key => {
            let value = object[key];
            if (Array.isArray(value)) {
                console.log(value.length);
            } else {
                console.log(object.type);
            }
        })
    }
}
```

You would probably like to get the same behavior for function arguments, except that there is no way to tell the compiler that these are "constant" like variables or "readonly" like members. We have recently discussed allowing a `const` modifier on function arguments, that will allow the compiler to make these assumptions without giving up on safety. you can find more about this in https://github.com/Microsoft/TypeScript/issues/8908.
