### ISSUE TITLE
Two diferent results transpiled from ts file on Visual Studio 2013

### ISSUE THREAD

**Issue by acostaf** [Microsoft/TypeScript#8937]
Hi Team

I am using angular 2 / TypeScript 1.8.10 / Visual Studio 2013 with plugging 1.8.5 (hack to use 1.8.10 replacing old tsc with new version) 

My csproj is set to use commonjs as module to get rid of the type issues from angular.
	 <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
		<TypeScriptModuleKind>commonjs</TypeScriptModuleKind>
		 .....

And my tsconfig.json looks like that
```json
	{    
		"compilerOptions": {
			"target": "es5",
			"module": "system",
			"moduleResolution": "node",
			"sourceMap": true,
			"emitDecoratorMetadata": true,
			"experimentalDecorators": true,
			"removeComments": false,
			"noImplicitAny": true,
			"suppressImplicitAnyIndexErrors": true
		},
		"exclude": [
			"node_modules",
			"typings/globals",
			"typings/index.d.ts"
		]
	}
```

Now the issue lies on the the transpiled javascript, on vs2013 build  I can see that JavaScript files are generated wrap around **"System.register(['@angular/core',"** following the module resolution on tsconfig.json but after saving the file (rather than full build) I get everything transpiled with the systemjs registration

Best Regards

**Comment by mhegazy** [comment]
The issue here is that VS 2013 does not support tsconfig.json. so when you are building from the commandline you are using your tsconfig.json configuration, (module === system); but when you are saving in Visual Studio, it is using the configuration in the project file, in this case, nothing there, so you probably get module === commonjs.

To work around this, you can either, 1. disable compile-on-save for your project (project properties), and rely on the build to generate the outputs. or 2. make sure you have the same configurations in the project file the same way you have them in the tsconfig.json. every command line option available in tsconfig.json can be defined using an MSBuild propoerty, see the mapping table in http://www.typescriptlang.org/docs/handbook/compiler-options-in-msbuild.html.
