### ISSUE TITLE
Implicitly initialise null for nullables

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#8972]
I guess you have already been discussing this before, but I would like to hear the arguments for why TS have not choose to have implicit null initialisation. When a variable can be null and not undefined why you don't default initialise the variable to null?

```ts
class A {
   propA: string | null;
}
let a = new A()
a.propA // null
```
For me typing `string | null = null` it's very time consuming.

Before TS, i.e. in the old days, I use to just type the initialisation myself:

```ts
function A {
  this.a = null;
}
```
but now when TS introduced the null type it is very cumbersome to write `string | null = null`.  This syntax actually encourages people to use undefined everywhere, because everything default initialise to `undefined`, and it is less cumbersome to write. Though, I think using `undefined` in the above case is incorrect since it has a different meaning. It really would ease my life a lot if I don't have to write so long syntax for anything I declare as nullable, which is a lot.

**Comment by ahejlsberg** [comment]
I don't see us doing this. JavaScript already defines `undefined` as the default value and guarantees that initialization to `undefined` will occur in *all* cases. But we'd only be able to automatically initialize to `null` in *some* cases. For example, we wouldn't be able to do it for new array elements. Also, we generally don't want to do type-directed emitting of code because it makes it impossible to do single file compile-on-save without first typing checking the entire program. For example, imagine a property declared as `propA: Foo`. Without resolving `Foo`, which may be declared non-locally as a union type that includes `null`, we wouldn't know what to emit for that declaration.
