### ISSUE TITLE
Default "exclude" property in tsconfig.json doesn't respect relative path of the "ourdir" 

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#8998]
```json
{
  "compilerOptions": {
    "outDir": "../someFolders"
  }
}
```

The default "exclude" property doesn't include "../someFolders"

**Comment by jcansdale** [comment]
It doesn't seem to automatically exclude a simple outDir either. For example:

{
  "compilerOptions": {
    "outDir": "lib"
  }
}

This is a problem if "allowJs" is true!

**Comment by yuit** [comment]
@jcansdale do you mean this won't work correctly:

```json
{
    "compilerOptions": {
       "outDir": "lib",
       "allowJs": true
     }
}

then default "exclude" won't exclude "outDir" value
```

**Comment by jcansdale** [comment]
@yuit Almost. The following isn't working correctly for me:

{
  "compilerOptions": {
    "outDir": "lib",
    "allowJs": true
  },
  "exclude": [
    "node_modules"
  ]  
}

It produces such gems as:
Build: Cannot write file '..../NodejsConsoleApp2/MyModule/lib/lib/lib/lib/lib/lib/lib/index.js' because it would overwrite input file.

(I'm using tsc 1.8.10 and Node.js Tools for Visual Studio 1.2 Alpha)

**Comment by yuit** [comment]
@jcansdale this issue of not include "outdir" in "exclude" at all already fixed in the nightly built.

Though the nightly built will not include "outdir" into "exclude" correctly if "outdir" is in relative path format . However, with your format it should work correctly
