### ISSUE TITLE
Use more reasonable file unit names in harness compiler

### ISSUE THREAD

**Issue by RyanCavanaugh** [microsoft/TypeScript#9029]
Compiler tests currently create the "unit name" as provided to the compiler as e.g. `tests/cases/compiler/foo.ts` (including that leading path).

This is problematic when we also have commandline options specified in `// @name: value` test directives because _those_ values are relative to the imaginary root of the harness file system, whereas all the filenames are in the `tests/cases/compiler` folders. So we end up having to specify `// @currentDirectory` values and absolute file paths in multi-file compiler tests to make all the path logic work out.

This also makes the error messages longer than they need to be.

Instead we should just put everything in the imaginary root of the harness file system, and put the path to the testcase at the top of the baseline file (so people can find it more easily).

**Comment by weswigham** [comment]
I don't think we've had anyone complain about this since the great test harness `vfs` rewrite - the test filesystem is quite pliable nowadays, including allowing you to specify in your tests that your files are at, eg, `/filename.ts`. The defaults are still such that the test file is at `tests/cases/compiler/foo.ts`, but that's mostly just so we don't rewrite the paths in thousands of test baselines for no great reason.

@RyanCavanaugh you can reopen if you disagree, but I think this is sufficiently solved nowadays.
