### ISSUE TITLE
JSON schema of tsconfig.json unclear for module property

### ISSUE THREAD

**Issue by amilner42** [Microsoft/TypeScript#9048]
The Typescript docs for the  [tsconfig.json](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html) point to this [JSON schema](http://json.schemastore.org/tsconfig)

Inside that schema for property `module` you see: 
```            "module": {
              "description": "Specify module code generation: 'none', 'CommonJS', 'Amd', 'System', 'UMD', or 'es2015'.",
              "enum": [ "commonjs", "amd", "umd", "system", "es6", "es2015", "none" ]
            },```

This left me confused (how is it different than the `target` property?!) only later to find out that you are referring specifically to `import/exports`, let's change up the docs to something more reflective of the purpose: ```            "module": {
              "description": "Specify module import/export code transformations: 'none', 'CommonJS', 'Amd', 'System', 'UMD', or 'es2015'.",
              "enum": [ "commonjs", "amd", "umd", "system", "es6", "es2015", "none" ]
            },```

**Comment by kitsonk** [comment]
The current description makes sense to me.

Module formats are more than "imports/exports"... `module` specifies the format of the generated module.  Your confusion is that you may not understand fully the term module.

`target` specifies the syntactical target of what the compiler should emit for the functional code.  Target doesn't necessarily have anything to do with module format.

I guess you could blame TC39 for including a module format specification in the ES6/ES2015 specification.  It guess it could be argued though that a better name for the ES6 module format could be `esm` and that should be the preferred way of referring to it, since it does get confusing as the years progress and additional revisions of the language come into play.

**Comment by amilner42** [comment]
Ah I see, thank you.

What about:
`Specify module code generation --> Specify module ​*format*​ code generation`

Simply to avoid reading like it's code generation for code *inside* the module.
