### ISSUE TITLE
Expose Typescript Engine to EnvDTE or Roslyn

### ISSUE THREAD

**Issue by pswetz** [Microsoft/TypeScript#9087]
I am attempting to expand a visual studio extension I work on to support TypeScript for certain file generation functionalities and also for actions based on the user right clicking text in the code editor.

Currently the only way I know to handle the file generation is by manually string building the .ts file contents and for parsing the clicked item I have the manually parse the text by caret location and attempt to determine the syntactic item the user is trying to act on. This is extremely cumbersome and difficult compared to how I perform these operations using either the Roslyn APIs or the EnvDTE Visual Studio interfaces (FileCodeModels). Currently Visual Studio will not provide a FileCodeModel for a TypeScript file and Roslyn can provide a Document object for the file but cannot provide any syntax based information (IE GetSyntaxRootAsync)

It does not appear there is any way currently to get a handle to the typescript engine and use it for code introspection within a visual studio extension. If I am incorrect please advise otherwise I would like to submit for a future feature addition (enable support for visual studio automation through existing APIs). Thank you.

Example using Roslyn

Microsoft.VisualStudio.Text.Editor.IWpfTextView textView = GetTextView();
SnapshotPoint caretPosition = textView.Caret.Position.BufferPosition;
Document document = caretPosition.Snapshot.GetOpenDocumentInCurrentContextWithChanges();
//always null
 SyntaxToken? token = document.GetSyntaxRootAsync().Result?.FindToken(caretPosition);

**Comment by mhegazy** [comment]
The TypeScript language service is written in TypeScript and hence JS. this is where all the syntax trees and semantic information live. we only expose a language service API, see https://github.com/Microsoft/TypeScript/blob/master/src/services/shims.ts#L109, to VS. so this information is not visible on the VS side, like in the Roslyn case. we have no intentions to marshal the AST across language boundary, mainly because of the perf issues, but also because of the complexity.

Also note that TS language services run in multiple host IDEs and not just VS, e.g. VSCode, sublime text, emacs, etc.. We are currently looking into enabling a TS extensibility model, tracked by https://github.com/Microsoft/TypeScript/issues/6508. This would be the place to get more information from the language service.

**Comment by pswetz** [comment]
Any way of loading the engine and retrieving a tree syntax view of a file code model would be wonderful. I will track that issue, thanks.

**Comment by mhegazy** [comment]
The language service is available in the typescript npm package and as a standalone file in https://github.com/Microsoft/TypeScript/blob/master/lib/typescriptServices.js. you can load this in an instance of [jsrt](https://msdn.microsoft.com/en-us/library/dn249673(v=vs.94).aspx), and, you can talk to it over IDispach calls. i would highly recommend not marshaling the tree, but rather doing the work on the JS side.

here is some documentation on using the API

https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API
https://github.com/Microsoft/TypeScript/wiki/Using-the-Language-Service-API
