### ISSUE TITLE
Triple slash reference should include extension '.d.ts' or not?

### ISSUE THREAD

**Issue by frogcjn** [Microsoft/TypeScript#9112]
`/// <reference path='../../../typings/index.d.ts' />`

or 

`/// <reference path='../../../typings/index' />`

?

Thanks!

**Comment by kitsonk** [comment]
Questions like this should be asked on Stack Overflow or on Gitter or IRC.

TypeScript issues are for tracking bugs and defects with TypeScript.

But to answer the question, the triple slashes follow module resolution as documented [here](https://www.typescriptlang.org/docs/handbook/module-resolution.html).

**Comment by frogcjn** [comment]
Because there is no clear document about it.
tsc says ok, but vscode said no.

**Comment by kitsonk** [comment]
Clearly the compiler overrules the visual editor.

Issues related are Visual Studio Code are reported [here](https://github.com/Microsoft/vscode).

**Comment by frogcjn** [comment]
@kitsonk
referee to Microsoft/TypeScript#9116

**Comment by dbaeumer** [comment]
@kitsonk this is a TS issues since the diagnostic reported inside VS Code are generated by the tsserver owned by the TS team.

**Comment by kitsonk** [comment]
Yes, I understand that, but that wouldn't be known until the problem was triaged.

The OP didn't raise an issue, they asked a question.  Then it was clear that the issue the OP was having was with a presentation in vscode, which then it was only logical for the issue to be triaged with the vscode team to find out where the error was occurring, which it now has been.  The OP ignored the issue template and didn't provide any information in order to even determine there was an issue.

**Comment by frogcjn** [comment]
Sorry for my expression, I'll notice that and express more clearly.
