### ISSUE TITLE
Error if module not found

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#9132]
If I try to import a module and TS doesn't find it, I don't get any errors. `allowJs` is enabled.

**Comment by kitsonk** [comment]
You need to provide to provide more information than this...

What is your project configuration?  How do you know that TS doesn't find it, what problems is this causing?  What version of TypeScript are you using?  What is an example of a file that does not exist?

Are we just supposed to guess?

Just randomly guessing, based on other questions you have asked, you are trying to import JavaScript files using the `import 'something.js';` for its side affects... In this case, TypeScript assumes you know what you are doing and since it does not need to resolve the module since it isn't importing any of that into the scope of the program it is compiling, it does not attempt to do so and just passes that to the emit.  

Resolving that at design time and throwing an error, would cause a lot of problems for people attempting to import 3rd party libraries which are not resolvable at design time.

**Comment by mhegazy** [comment]
There are no semantic errors reported in JS files. only in .ts files. If i am guessing correctly you are expecting this error in .js file. 

The rational here is users could have existing JS files with dynamic behavior, e.g. `require("myModule"+getModuleSuffix());` that the compiler has no way to understand. so instead of giving users errors for working code, we chose not to report these errors in JS files.

I understand that leaves more to be desired, we have https://github.com/Microsoft/TypeScript/issues/6802 tracking making these JS errors more configurable, so you can decide whether or not you want to see these errors.

**Comment by mhegazy** [comment]
leaving this as needing more info. as @kitsonk noted, more context would be needed to assess or investigate this issue.

**Comment by OliverJAsh** [comment]
Here is more info.

I have enabled `allowJs`. In my TS file, I have this import, for a non-existent file:

```
import "./foo";
```

TS does not give me any errors.

**Comment by kitsonk** [comment]
@OliverJAsh as stated above:

> Just randomly guessing, based on other questions you have asked, you are trying to import JavaScript files using the `import 'something.js';` for its side affects... In this case, TypeScript assumes you know what you are doing and since it does not need to resolve the module since it isn't importing any of that into the scope of the program it is compiling, it does not attempt to do so and just passes that to the emit.

**Comment by mhegazy** [comment]
I think this is the same as #6802. The compiler has this information, it just decides not to report these errors in JS files. we will need some error configuration infrastructure to make them surface.

**Comment by mhegazy** [comment]
closing in favor of #6802

**Comment by kitsonk** [comment]
> The compiler has this information, it just decides not to report these errors in JS files. we will need some error configuration infrastructure to make them surface.

#6802 is broad, but likely the right place.  I will mention it there too that if that were the case, like this one, not all of these errors are fatal and even in an IDE.  I suspect the `import 'foo.js';` use case is in a `.ts` file is often used to load external libraries at run-time which are often not located in a resolvable location at run-time and that change in behaviour would have some significant consequences, as there is not syntatical notation to differentiate between those "just trust me, load this" and "actually, even though this import will have no design time affect on my code, I want tsc to error..."
