### ISSUE TITLE
Type inference bug with Union Types

### ISSUE THREAD

**Issue by Loilo** [Microsoft/TypeScript#9211]
**TypeScript Version:** 

1.8.10

**Code**

```ts
class Item1Stuff {}
interface Item1 {
    stuff: Item1Stuff;
}

class Item2Stuff {}
interface Item2 {
    stuff: Item2Stuff;
}

type Item = Item1 | Item2;

function handler(item: Item) {
	return item.stuff;
}
```

**Expected behavior:**
The inferred return type of the `handler` function should be `Item1Stuff | Item2Stuff` no matter how they're implemented since they are completely unrelated classes.

**Actual behavior:** 
The return type is inferred to be `Item1Stuff`. This only changes if `Item1Stuff` implements any property/method (doesn't need to be public) that does not exist in `Item2Stuff` or only exists with another signature.

Note that this only works this way around -- if `Item2Stuff` implements something not contained in `Item1Stuff` it doesn't change anything.

**Comment by mhegazy** [comment]
TS has a structural type system. `Item1Stuff` and `Item2Stuff` are identical types from a structural view point. 

There is a sub-type reduction process that happens when looking up union type members. the result is picking the type which is more general.

if the two types are disjoint, then both will be in the result. if they are not, the one that is a super type of the other will be picked.

**Comment by Loilo** [comment]
Oh okay. Didn't know that structural system thing. Thanks for the information. :)

**Comment by zbjornson** [comment]
This seems like wrong behavior regardless of the type system. At the very least it's confusing to see the wrong return type. In @Loilo's example, given the call `handler(myItem2)`, TS will report that it has returned an instance of `Item1Stuff`, which is incorrect; only the instance members are the same.

Another example:
```ts
function doStuff(input: Float32ArrayConstructor|Float64ArrayConstructor) {
	return new input(2);
} // inferred output type is "Float32Array"
doStuff(Float64Array) // claims this is a Float32Array
```

We can override the inferred return type with the same union type as the params, but then the result of `doStuff` remains a union type as well.

**Comment by RyanCavanaugh** [comment]
It's just :turtle: s all the way down in that example, though, because `Float32Array` and `Float64Array` are *also* identical, so there's no reason (from a type system perspective) to prefer one of them over the other. The real fix is that `Float32Array` and `Float64Array` should be made different by some means or another and there are already a bunch of issues discussing how to make that happen.

**Comment by zbjornson** [comment]
Haha :)

Looks like you're referring to #5388. Thanks for pointing that out.
