### ISSUE TITLE
Discriminated union types lose their narrowed type inside nested function scopes

### ISSUE THREAD

**Issue by ryanatkn** [Microsoft/TypeScript#9258]
**TypeScript Version:** 

nightly (1.9.0-dev.20160619-1.0)

**Code**

```ts

interface Rectangle {
    kind: "rectangle";
    width: number;
    height: number;
}

interface Circle {
    kind: "circle";
    radius: number;
}

type Shape = Rectangle | Circle;

function test1(s: Shape) {
    if (s.kind === "rectangle") {
        s;  // Rectangle
        setTimeout(() => {
          s; // Rectangle | Circle
        });
    }
}

```

**Expected behavior:** both `s` usages to narrow to type `Rectangle`

**Actual behavior:** the `s` in the nested function scope has type `Rectangle | Circle`

**Comment by yortus** [comment]
I believe this is by design, and applies to all type guards, not just those for discriminated unions. The problem is that the compiler cannot in general be sure *when* the nested function will be called, so it's not safe to assume the narrowed type will still apply by the time the function is actually called. The variable may have been re-assigned by then.

There are a couple of special cases involving IIFEs and `const`s where the narrowing can safely cross into the nested function body, and the compiler handles these cases correctly. See #8849.

**Comment by ryanatkn** [comment]
Makes sense, thank you!
