### ISSUE TITLE
tsc complains when accessing indexable property

### ISSUE THREAD

**Issue by benweet** [Microsoft/TypeScript#9299]
**TypeScript Version:** 

1.8.10

**Code**

```ts
let authMiddleware: RequestHandler = function (req, res, next) {
  if (req.headers.authorization) {
    ...
  }
}
```

**Expected behavior:**

No compilation error/warning.

**Actual behavior:** 

Compilation error:

```
[ts] Property 'authorization' does not exist on type '{ [key: string]: string; }'.
```

**Note:**

I think it has already been discussed here: #5305 but was closed for some reason.

**Comment by kitsonk** [comment]
No, it is unrelated to that issue... When accessing something that only specifies an indexer, and not a named property, you have to access it via its index:

```typescript
let authMiddleware: RequestHandler = function (req, res, next) {
  if (req.headers['authorization']) {
    ...
  }
}
```

**Comment by benweet** [comment]
https://github.com/Microsoft/TypeScript/issues/5305#issuecomment-149695202 was related.

**Comment by kitsonk** [comment]
@benweet it said it needed a formal suggestion, the OP did not create a formal suggestion.

**Comment by benweet** [comment]
@mhegazy there was no question. Or maybe "what is the rational behind this?"

**Comment by kitsonk** [comment]
The rational is to help the developer ensure that the property they are accessing is not formally defined on the interface for the object, therefore they likely need to guard better against it, like make sure it is spelled right and actually defined.

Since interfaces are open ended, it is quite easy for an end developer to be more explicit about what is known to be contained in an indexed object.
