### ISSUE TITLE
should ts avoid to use the this keyworld in class ?

### ISSUE THREAD

**Issue by John0King** [Microsoft/TypeScript#9368]
**version**
1.8.31

```ts
class A {
    public count: number = 10;
    public AddOne(): void{
        this.count += 1;
    }
}
```
and will generate those js
```js
var A = (function () {
    function A() {
        this.count = 10;
    }
    A.prototype.AddOne = function () {
        this.count += 1;
    };
    return A;
}());

```
this is ok when you ` let a = new A() `  and `a.AddOne()`  , 
but when  ` let myadd = a.AddOne `  and   `myadd()`
the result will be different . because  `this`  became something else.

should  the output js like this ?
```js
var A = (function () {
    var _this;
    function A() {
        this.count = 10;
        _this = this;
    }
    A.prototype.AddOne = function () {
        _this.count += 1;  // not use this
    };
    return A;
}());
```

**Comment by kitsonk** [comment]
This is just the behaviour of JavaScript.  When using `class` in a ES6 compatible environment, you get an error when you called an improperly bound method:

```javascript
class A {
	constructor() {
		this.count = 10;
	}
    AddOne() {
        this.count += 1;
    }
}

const a = new A();
const myaddone = a.AddOne;

myaddone();  // Uncaught TypeError: Cannot read property 'count' of undefined
```

Therefore if your suggestion would break compatibility with ES6 classes.

If you need a reference of a method bound to an instance, just bind it:

```typescript
const myaddone = a.AddOne.bind(a);
```

**Comment by John0King** [comment]
@kitsonk  How to use it in  jquery's  `click`  or  `change` method ?

**Comment by kitsonk** [comment]
I am afraid this isn't a general support forum, but without some example of how you want to use something and what is not working, it is really difficult to even answer that question.  The problem could be solved any number of ways, which are patterns used with construction functions with prototypes since the early days of JavaScript.  Most libraries like jQuery have mechanisms for being context when it can be lost as well as ES6 offer lexical `this` binding when using arrow/lambda functions.

But all of this is probably not for discussion in a issue tracker for bugs with TypeScript.  StackOverflow, Gitter and IRC are better places to discuss "how do I use" something.

**Comment by John0King** [comment]
@kitsonk   you are right , my suggestion can fix in es 5 and lower but can not fix in es6.
