### ISSUE TITLE
New tsconfig.json "include" syntax does not work with ".."

### ISSUE THREAD

**Issue by skorlir** [Microsoft/TypeScript#9451]
**TypeScript Version:**  nightly (2.0.0-dev.20160630)

**tsconfig.json**
```json
{
  "include": [
    "../app/**/*.ts"
  ]
}
```

**Expected behavior:**

Running `tsc` will compile all `.ts` files in `../app`.

**Actual behavior:** 

Running `tsc` does nothing.

**NOTE**

Specifying `"files": [ "../app/someFile.ts" ]` *does* work; it is just that "include" seems to ignore "..".

**Comment by mhegazy** [comment]
@riknoll can you take a look

**Comment by riknoll** [comment]
@mhegazy yep, I can reproduce this. I'll work on a fix.

**Comment by riknoll** [comment]
So I think we should support using `..` before recursive wildcards (i.e. `**`), but it is an error if they are used after one. It isn't immediately clear what they mean in that scenario and I don't think it gains us any power. In other words,

This is all good:
```
../src/**/*.ts
```

But this will be an error:
```
src/**/../*.ts
```

And this probably will be too, since really there is no reason to have `..` anywhere but the beginning:
```
src/**/somedirectory/../*.ts
```

**Comment by mhegazy** [comment]
I think this makes sense.
