### ISSUE TITLE
Missing type guard with Arrays

### ISSUE THREAD

**Issue by HolgerJeromin** [Microsoft/TypeScript#9469]
**TypeScript Version:**  1.8.0

**Code**

```ts
var myAny: any = 'anythinghere';

if (Array.isArray(myAny)) {
	var newarray: string = myAny;
}
```

**Expected behavior:**
myAny should be of type any[] and not any after the check. 
Tested with Visual Studio 2015 Update 2 and TypeScript Playground mouse hover.
And compile should break.

**Comment by kitsonk** [comment]
`any` is never narrowed...  expected TypeScript behaviour

If the type was `any[] | string` then it could be narrowed.

**Comment by HolgerJeromin** [comment]
OK, thanks for the explanation.
Can we change that? :-)

**Comment by kitsonk** [comment]
Changing `any` to be narrowed would be a gigantic breaking change.  In order to have TypeScript be compatible with JavaScript, it needs a universal top type like `any`.  If you want to keep it from not accepting `any` value, don't assign that as the variable type.

Why is assigning a type other than `any` a challenge/issue?

**Comment by DanielRosenwasser** [comment]
> Can we change that? :-)

Unfortunately, as @kitsonk said, it broke a lot for when people do something like `myAny instanceof Object`, because you basically can't get any distinct information off of an `Object`.

See #5011 for when I tried to address this.

**Comment by HolgerJeromin** [comment]
Thanks everyone!
