### ISSUE TITLE
Using tsc's paths config with WebPack, Browserify, etc.

### ISSUE THREAD

**Issue by tp** [Microsoft/TypeScript#9515]
**TypeScript Version:**  2.0.0-dev.20160701

**Code**

`paths` in `tsconfig.json`:
```json
"paths": {
      "*": [
        "*",
        "components/*/src"
      ]
    }
```

**Expected behavior:**

The generated JS is usable by programs using the Node.js module resolution algorithm (like Browserify, WebPack or plain Node.js).

**Actual behavior:** 

It is nice that TypeScript is now able to allow very advanced lookup strategies to find related modules without resorting to symlinking in node_modules, dummy `package.json`s only containing a "typings" field and similar workarounds used in the past.

But I am wondering how this fits in the overall ecosystem because the generated JS code has no remapped paths in `require` function calls, and therefore running the generated code with plain node or a bundler like WebPack or Browserify will result in module not found errors.

So I am wondering how this function is to be used in practice when the compiled JS is not usable without counterparts on the tools further down the chain.

Should consuming projects like Browserify and WebPack be configured in the same vein? (Which I don't think is possible out of the box yet with them).

Any input on how this should be handled is appreciated. Once a decision is reached, this should probably be added to the WebPack and other tutorials.

**Comment by kitsonk** [comment]
I think generally that this was a solution to a problem that many of us were having when using AMD loaders, SystemJS and WebPack in that we would often remap where things were loaded from but TypeScript could not keep up.

From a toolchain perspective, we see TypeScript as one part of the toolchain, and therefore instead of "driving" the configuration of the project, it is the wrap of the toolchain that we expect to configure each part of the toolchain as appropriate and try to keep things in sync.

And from a [TypeScript design goal perspective](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#non-goals), the team clearly feel the same way as the have stated a non-goal:

> 4) Provide an end-to-end build pipeline. Instead, make the system extensible so that external tools can use the compiler for more complex build workflows.

It is a fair point that the tutorials could be updated, of course once TypeScript 2.0 is released.

**Comment by DanielRosenwasser** [comment]
As @kitsonk mentioned, path mapping is supposed to reflect your runtime's resolution, but it does not necessarily imply that your runtime will use *TypeScript's* path-mapping configuration to guide it. Something similar has been requested on https://github.com/TypeStrong/ts-loader/issues/213, but otherwise, I believe that this is external.
