### ISSUE TITLE
No completion for "export default exports" modules

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#9520]
_From @ithinkihaveacat on July 4, 2016 8:20_

- VSCode Version: 1.2.1
- OS Version: OS X 10.11.5

Steps to Reproduce:

1. `git clone https://gist.github.com/ithinkihaveacat/ed5fc36db488b6e5ecb209fb2d31aa68`
2. `typings install`
3. open main.ts in VSCode
4. Note that there are no completions for `$.`. (`$.greet` should be a completion.)

_Copied from original issue: Microsoft/vscode#8711_

**Comment by mhegazy** [comment]
@ithinkihaveacat  JQuery is not added in your typings.json. why do you think it should be installed? 

after installing JQuery defintions, please set `"allowSyntheticDefaultImports" : true` in your tsconfig.json.

**Comment by ithinkihaveacat** [comment]
@mhegazy Wait, what? This doesn't have anything to do with jQuery--the same thing happens if e.g. `$` is replaced with `quux`.

My issue is that I can't get completion/intellisense working on what (I think) is 100% valid TypeScript code. It compiles and runs just fine:

````sh
$ typings install
$ tsc *.ts
$ node main.js
Hello, World
````

However completions/intellisense is not available.

([The code](https://gist.github.com/ithinkihaveacat/ed5fc36db488b6e5ecb209fb2d31aa68); I've changed `$` to `quux` in case that was confusing.)

**Comment by mhegazy** [comment]
From https://gist.github.com/ithinkihaveacat/ed5fc36db488b6e5ecb209fb2d31aa68#file-typings-json,

```json
{
  "globalDependencies": {
    "node": "registry:dt/node#6.0.0+20160621231320"
  }
}
```

you are only installing definitions for `node`. `$`, `quux` or any thing else is not installed. why do you expect it to work any differently?

**Comment by ithinkihaveacat** [comment]
I'm not sure why I need to import definitions for TypeScript code; I thought the point of the ambient definitions was to add types to existing JS code?

`import * as quux from "./foo"` generates completions just fine:

![screen shot 2016-07-06 at 07 44 00](https://cloud.githubusercontent.com/assets/51244/16609638/89606362-434d-11e6-821b-062834d5906a.png)

`import quux from "./foo"` (i.e. utilising `export default exports`) does not:

![screen shot 2016-07-06 at 07 44 16](https://cloud.githubusercontent.com/assets/51244/16609651/a102b830-434d-11e6-959b-02a749032f79.png)

How can I make the `import * as quux` case (no need to explicitly list names to import) work the same as `import quux` (with respect to completion/intellisense)?

**Comment by kitsonk** [comment]
> I thought the point of the ambient definitions was to add types to existing JS code?

Exactly, but how were you expecting to acquire those ambient definitions?  TypeScript cannot magic them out of thin air.  The information you provided indicated that you have not included any ambient typing information in the scope of your project.  TypeScript is good, but it isn't magical.

> How can I make the `import * as quux` case (no need to explicitly list names to import) work the same as `import quux` (with respect to completion/intellisense)?

Generally, as @mhegazy instructed:

> please set `"allowSyntheticDefaultImports" : true` in your tsconfig.json.

When external libraries do not use the ES6 module syntax, and therefore don't have a default export, that compiler flag allows you to do that.  On the other hand, if the module actually has a default export declared in the ambient typings, it will provide code completion for that default export.

**Comment by ithinkihaveacat** [comment]
First of all, thanks for looking into this--I do appreciate your time even though I haven't managed to convince you that this is an issue.

However, I still don't understand why `import * as quux` behaves differently to `import as quux`, or more precisely why this behaviour is desirable or necessary, rather than undesirable.

(I think it happens because TypeScript does not understand what `exports` refers to in the context of a module--it only knows that `exports` exists because it appears in (Node's) ambient definitions, where [its type is `any`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/node/node.d.ts#L73). But if TypeScript was given a better understand of what `exports` means (c.f. its [special knowledge of `export =`](https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require)) it might be able to provide completion in the `export default exports` case as well.)

> … how were you expecting to acquire those ambient definitions? TypeScript cannot magic them out of thin air.

I don't see why TypeScript would need to magic definitions out of thin air. From looking at the reproduce code, a programmer can say what `quux.greet()` does, and that `quux.baz()` does not exist, so in principle TypeScript could figure it out too. (It's not like the function is dynamically generated at runtime.)

> … please set "allowSyntheticDefaultImports" : true in your tsconfig.json

I did try this, but it doesn't make any difference to the completion behaviour.

After poking around a bit, I discovered that this construction does activate completion:

````js
// for the `import * as quux` case
export function greet() {
  console.log("Hello, World");
}

// for the `import quux` case
export default {
  greet: greet, 
};
````

However this requires manually listing each of the functions to be exported by default. (And only for completion--it compiles without error and runs just fine without it.) Is there any way to avoid this?

**Comment by kitsonk** [comment]
Generally, TypeScript follows the ES6 module format.

`export something` is a named export, meaning that to import it you should `import { something } from 'module';`  If you utilise `import * as anything from 'module'` you will get all the exports of the module.

`export default something` is the default export, to import it you use `import anything from 'module'` where.

`export = something` is legacy syntax to support "legacy" modules, to import that type of export, you should use `import * as anything from 'module'`.  `allowSyntheticDefaultImports` should change the behaviour of TypeScript so that `import anything from 'module'` is equivalent to `import * as anything from 'module'`.  If the module has a `default` export though, even with `allowSyntheticDefaultImports`, if the module has a `default` export, you will get that when using the `import anything from 'module'` construct.

You cannot have an `export = something` and a `export default something` in the same module.
