### ISSUE TITLE
Error on subclass if missing constructor

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#9523]
**TypeScript Version:**  nightly (1.9.0-dev.20160627)

**Code**

```ts
class Foo {
  constructor(option: { something: string }) {  // <-- required `option` param
    console.log(option.somthing); // Throws Cannot read property 'something' of undefined
  }
}

class Boo extends Foo {
}
```

**Expected behavior:**
Show error at compile or mark error on IDE.

**Actual behavior:** 
Does not.

**Comment by DanielRosenwasser** [comment]
You'll get [an error at the call-site](http://www.typescriptlang.org/play/#src=class%20Foo%20%7B%0D%0A%20%20constructor(option%3A%20%7B%20something%3A%20string%20%7D)%20%7B%20%20%2F%2F%20%3C--%20required%20%60option%60%20param%0D%0A%20%20%20%20console.log(option.something)%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20Boo%20extends%20Foo%20%7B%0D%0A%7D%0D%0A%0D%0A%0D%0A%0D%0Anew%20Boo()%3B%0D%0A%0D%0Anew%20Boo(%7B%20something%3A%20%22Hello!%22%20%7D)%3B) because a constructor is "synthesized" and that constructor redirects its arguments to a `super` call. See [Step 10.a of of 14.5.14 (Class Definition Evaluation) of the ES 2016 spec](https://tc39.github.io/ecma262/2016/index.html#sec-runtime-semantics-classdefinitionevaluation).
________
![image](https://cloud.githubusercontent.com/assets/972891/16597917/3f9ce2ac-42b0-11e6-913c-470c697c1a24.png)

**Comment by unional** [comment]
Ar I see. I didn't get that because I am using dependency injection to create instance of `Boo`.
