### ISSUE TITLE
@types/nunjucks should include constructor on FileSystemLoader

### ISSUE THREAD

**Issue by Pajn** [Microsoft/TypeScript#9525]
The FileSystemLoader class has no specified constructor and thus allows no parameters to be passed, however passing parameters is required for specifying search path.
According to documentation https://mozilla.github.io/nunjucks/api.html#filesystemloader
it should include a constructor like
```typescript
constructor(searchPaths? string|string[], options?: {watch?: boolean, noCache?: boolean})
```

**Comment by mhegazy** [comment]
should be fixed in `@types/nunjucks@0.0.26-alpha`.

For future reference, declaration file issues should be filed on  https://github.com/DefinitelyTyped/DefinitelyTyped/issues; issues filed on https://github.com/Microsoft/TypeScript should be related to the publishing process, i.e. the declaration file is accurate on https://github.com/DefinitelyTyped/DefinitelyTyped, but there is a problem with the npm package itself, dependencies, version, naming, etc..
