### ISSUE TITLE
[Bug] Cannot default export an expression that begins with async

### ISSUE THREAD

**Issue by Seikho** [Microsoft/TypeScript#9531]
**TypeScript Version:**  nightly (2.0.0-dev.20160705)

The changes in #9445 have caused a breaking change in my code base. This is a pattern that we use very frequently our projects.
The compiled output has also changed and no longer functions as expected. The same error also occurs when using the `async` library in the same way (e.g. `export default async.map(...)`)

**Code**

```ts
import {async,await} from 'asyncawait';
export default async(() => await(Promise.resolve(1)));
```

should compile without error and emit:
```js
const asyncawait_1 = require('asyncawait');
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = asyncawait_1.async(() => asyncawait_1.await(Promise.resolve(1)));
```

but incorrectly emits:
```js
const asyncawait_1 = require('asyncawait');
asyncawait_1.async(() => asyncawait_1.await(Promise.resolve(1)));
```

**Expected behavior:**
Compiles without error
**Actual behavior:** 
`[ts] Declaration expected`  
Incorrect compiled output

**Comment by yortus** [comment]
Looking at the changes in #9445, it seems that if the next token after `export default` is `async`, then it's treated like a declaration rather than an expression. But `async` is not a keyword ([spec](http://www.ecma-international.org/ecma-262/7.0/index.html#sec-keywords)), and a valid expression may begin with an `async` token, as in @Seikho's two examples above.

I think `export default <expression>` should be allowed even if the expression is something like `async.map(...)` or `async(() => {...})`, since these are valid expressions.

**Comment by yortus** [comment]
If this makes it into the 2.0 release, it will be a breaking change.

**Comment by DanielRosenwasser** [comment]
Thanks for tracking the regression down @yortus!
