### ISSUE TITLE
Different behaviours between undefined property and optional

### ISSUE THREAD

**Issue by plantain-00** [Microsoft/TypeScript#9543]
**TypeScript Version:**  nightly (2.0.0-dev.20160706)

**Code**

```ts
type A = { a: number | undefined };
const b: A = { a: undefined };
const c: A = {}; // error, property a is missing in type {}
```

**Expected behavior:**
no error
**Actual behavior:** 
error

Seems bug, or by design?

update: same when not in strict null check mode.

**Comment by ahejlsberg** [comment]
This is by design. A property can be omitted only if it was declared with a `?` modifier. So, `{ a?: number }` says that `a` is optional and may be omitted (and `undefined` is automatically included in the type if it isn't explicitly specified), whereas `{ a: number | undefined }` says that `a` must be specified and `undefined` is one of the permitted values.
