### ISSUE TITLE
Intellisense support in 'this' keyword inside an object.

### ISSUE THREAD

**Issue by sant123** [Microsoft/TypeScript#9583]
Hi, maybe this is a bug but is not showing any intellisense regarding with the current object. 

**TypeScript Version:**  1.8.0

**Code**

```ts
interface Person {
	name : string;
	lastName : string;
	age: number;
	
	greet() : string;
}


var People : Person[] = [{
	name : "Santi",
	lastName : "Aguilar",
	age : 21,
	greet : function(){
		return this.name;
	}
}]
```

**Expected behavior:**

Offer intellisense for the current object (this)

**Actual behavior:** 

![image](https://cloud.githubusercontent.com/assets/7959437/16705800/1e28417c-455b-11e6-9cab-9c4c948d754e.png)

**Comment by DanielRosenwasser** [comment]
We experimented with inferring the type of `this` by the surrounding object, but because it broke a lot of existing code (see #8191).

You can add an explicit `this` type in each method in TypeScript 2.0 (check our nightlies with `npm install -g typescript@next`):

```ts
var People : Person[] = [{
    name : "Santi",
    lastName : "Aguilar",
    age : 21,
    // Notice 'this: Person'
    greet : function(this: person) {
        return this.name;
    }
}]
```

Alternatively, you can add `this: this` to each method on the `Person` interface and implicitly have it work:

```ts
interface Person {
    name : string;
    lastName : string;
    age: number;

    greet(this: this) : string;
}


var People : Person[] = [{
    name : "Santi",
    lastName : "Aguilar",
    age : 21,
    greet : function() {
        return this.name;
    }
}]
```

If you ever want to avoid `this` being typed as `any`, we've also provided the `--noImplicitThis` flag, which gives an error when you used `this` and the type is not inferrable.

**Comment by sant123** [comment]
Thank you for your answer @DanielRosenwasser :smile:

**Comment by ahejlsberg** [comment]
See #14141.
