### ISSUE TITLE
TypeScript Language Service (via VS Code) reports error using async in non-ES2015 target

### ISSUE THREAD

**Issue by bytenik** [Microsoft/TypeScript#9587]
Despite the fact that the code compiles successfully, the language service in 2.0.0-dev.20160707 is reporting (via VS Code in my instance) an error whenever a function is declared `async` when targeting < ES2015:

![image](https://cloud.githubusercontent.com/assets/441347/16708375/621a3390-45bf-11e6-9661-6fcffd3f57e8.png)

VS Code is successfully using the correct 2.0 preview:

![image](https://cloud.githubusercontent.com/assets/441347/16708377/75a795f6-45bf-11e6-908a-eb9731e733bc.png)

I can post this to the VS Code issue tracker if more appropriate, but I'm pretty sure these errors come from the TS language service.

**Comment by yortus** [comment]
I think the language service error is correct, since TSC does not yet support async functions for non-es2015 targets. But until recently it didn't report an error in some cases (see #7334). This was fixed recently, and your language service is recent enough to have this fix, but I suspect the version you are compiling with is older. If you look at the emitted code for async functions, you might see they are not emitted correctly (see #7706).

**Comment by bytenik** [comment]
I know that TSC didn't support it until recently, but that's actually what caused me to upgrade to 2.0 prerelease.

What would cause it to think I'm using an older compiler? I'll admit I fire the compiler off using `gulp` rather than `tsc`, but I did both a global and project-local install of `typescript@next` which is what caused Code to show the new version in the corner.

**Comment by yortus** [comment]
> I know that TSC didn't support it until recently, but that's actually what caused me to upgrade to 2.0 prerelease.

The latest prerelease still doesn't support async functions in ES3/5, that hasn't been merged yet. #1564 is still open and looks like the last feature yet to land before 2.0 is ready for release.

> I fire the compiler off using gulp

Perhaps gulp has it's own dependency on tsc v1.8? I would be installed somewhere like `proj/node_modules/gulp-typescript/node_modules/typescript/`.
