### ISSUE TITLE
Salsa - Type discovering for angularjs 1 js controllers

### ISSUE THREAD

**Issue by miguelchico** [Microsoft/TypeScript#9600]
**TypeScript Version:**  1.8.10

Using the controller above (written in javascript) the type of injected parameters can't be infered.

**Code**

``` js
(function () {
    'use strict';

    angular
        .module('app')
        .controller('TestController', TestController);

    TestController.$inject = ['$q', '$http', '$timeout'];
    /* @ngInject */
    function TestController($q, $http, $timeout) {
        var vm = this;

        activate();

        function activate() {

        }
    }
})();

```

**Expected behavior:**
parameters $q, $http and $timeout well typed

**Actual behavior:** 
parameters $q, $http and $timeout of type any

Check: https://github.com/Microsoft/vscode/issues/8163

**Comment by bmontgom** [comment]
This is a feature I strongly desire. Please remedy this soon!

**Comment by githop** [comment]
Check out [typings](https://www.npmjs.com/package/typings) on npm!
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/angularjs/angular.d.ts

**Comment by miguelchico** [comment]
@githop, have you checked the related issue in vscode project?

**Comment by bmontgom** [comment]
@githop unfortunately the problem here seems to be that VSCode itself no longer supports Typings as fully as it did a few weeks ago, after a recent update. Check the referenced issue @miguelchico made, he explains in there.

**Comment by aluanhaddad** [comment]
@miguelchico This has absolutely nothing to do with _typings_, and everthing to do with how you have structured you code.

* Angular controllers have no specific interface they are required to implement, they must simply be instantiable view `new` so  there is nothing regarding the parameter types that can be inferred inferred, because there are no limitations on them. Even if you wrote you controller inline, a bad practice but useful to illustrate my point, you would see the following
![image](https://cloud.githubusercontent.com/assets/5034656/16719967/079e04b4-46ff-11e6-852e-03ca032f2551.png)
There is no specific type the function type the framework requires hence the `: Function` annotation.

* When you write this code in TypeScript you would do the following (note I am not trying to be idiomatic).
```TypeScript
function TestController(
    $q: ng.IQService, 
    $http: ng.IHttpService, 
    $timeout: ng.ITimeoutService) { ... }
```
* Of course this is JavaScript so you cannot write type annotations, but the new TypeScript Salsa service understands type annotations in JSDoc commonts, consider
```JavaScript
/**
 * @param {ng.IQService} $q
 * @param {ng.IHttpService} $http
 * @param {ng.ITimeoutService} $timeout
 */
function TestController($q, $http, $timeout) {
```
and that reads the types right out of the _.d.ts_ file and gives you intellisense as shown
![image](https://cloud.githubusercontent.com/assets/5034656/16720171/602c34dc-4701-11e6-9fc7-ba96c00eec2c.png)
* You probably know, but ngInject is not relevant here and is made completly redunant but the explicit inject property which pass. What you have done is good practice, just remove the superfluous `@ngInject`
```JavaScript
/* @ngInject */
function TestController($q, $http, $timeout) {
```

A couple of notes. I am using typescript@2.0.0-dev.20160707 in VSCode by settings "typescript.tsdk", I _jsconfig.json_ file in my project with empty object `{}`.

It is also worth noting that the maintainer of ng-annotate is moving on, see olov/ng-annotate/issues/245.
I think the whole notion of inferring types from parameter names is a very unsound and is very confusing. The fact the you are explicitly setting `$inject` speaks to this; it is simply unreliable at best.

**Comment by aluanhaddad** [comment]
Here is the setup https://github.com/aluanhaddad/salsa-ng-1x-example

**Comment by miguelchico** [comment]
thank for your explanation @aluanhaddad, but my point is still there.

If you check the issue I opened to vscode team, I explained there that for the same code I wrote here (I know @ngInject is not necessary at all for the example) before the TypeScript Salsa service the types of controllers parameter were automatically discovered.

I know I can do the same writing type annotations in JSDoc, but it force me to write a lot of information that was not necessary before.

You can try your example with a previous version of vscode (0.10.9) and you'll see that even without the JSDoc comments, the editor is able to detect the injected parameters in the controller.

This issue is to ask for that behavior again.

**Comment by aluanhaddad** [comment]
@miguelchico Sorry, I didn't read the VSCode issue. I have since done so and noticed the comment

> To be honest, we did something very 'pragmatic'/hackish to enable this in the past.

I imagine they must have had a mapping somewhere that looked like `{ "$scope", ng.IScopeService, .. }`, and while I cannot speak for the TypeScript team in any way, I doubt this kind of thing will be supported. There is no way to event attempt type resolution in these cases without building support for angularjs directly into TypeScript. 
Since VSCode is using TypeScript to power it's JavaScript experience, you are going to see less guesswork, but more reliable results in intellisense, this _is_ better in the long run.
You probably want to checkout #6508

**Comment by egamma** [comment]
@aluanhaddad Just for some more background. VS Code always used TypeScript to power JavaScript. In the past we used some source rewriting that translates JS to TS behind the scenes and then used TS to get Intellisense etc. As part of this translation we did the pragmatic mapping of $scope -> ng.I{Scope}Service in the generated JS code. Now that TS is supporting JS directly we have switched to this support and could remove the source code rewriting.

**Comment by angelozerr** [comment]
I think the only solution to fix this issue, is to wait for https://github.com/Microsoft/TypeScript/issues/6508 and implement an angular1 plugin like I have done with ternjs https://github.com/angelozerr/angularjs-eclipse/wiki/Javascript-Features#completions

**Comment by aluanhaddad** [comment]
@egamma thank you for the explanation and context, it is a very enlightening.

**Comment by mhegazy** [comment]
Given how injection work in Angular1, I do not think there is a way for the express that to the TypeScript typesystem other than hardcoding the support in. We have avoided hard coding any behaviours for frameworks, and that has served us well in the past.
I
