### ISSUE TITLE
Generics: Possibility of Reusing Type Variable Name is Confusing

### ISSUE THREAD

**Issue by tp** [Microsoft/TypeScript#9641]
**TypeScript Version:**  1.8.0 Playground and  / nightly (2.0.0-dev.20160711)

**Code**

```ts
interface X<T> {
	getX<T>(): T;
}

const y: X<string> = { getX() { 1 } };

const z : string = y.getX();
```

**Expected behavior:**

I would expect the T on getX be the same as on the interface, or get a compile time error, that there is "shadowing" going on.

**Actual behavior:** 

Type '{}' is not assignable to type 'string'.

---

I find this very confusing and spend quite a bit of time just now tracking down an issue that was caused by this "shadowing". Since this is something normal JS code is often checked against, I feel like it would be good it TypeScript would protect it's users in this case.

**Comment by kitsonk** [comment]
Confusing potentially, but follows the patterns elsewhere in the language where parameters mask other in their scope:

```typescript
var a = 'foo';

function foo(a: string) {
    console.log(a);
}

foo('bar');
```

**Comment by tp** [comment]
Good point, maybe this could also be handled in one of the linter projects.

**Comment by mhegazy** [comment]
Looks like a potential tslint rule.

**Comment by RyanCavanaugh** [comment]
I remember some very early discussion where we considered disallowing generic type parameter names to shadow each other, since doing this on purpose is generally pretty rare. But you could still imagine some code like this that does shadow but is obviously not wrong at all:

```ts
class List<T> {
  foo(arg: <T>(x: T) => T) { /*...*/ }
}
```
So in absence of a bright-line rule of when shadowing should be OK and when it shouldn't, we opted to allow it everywhere.
