### ISSUE TITLE
functions returning never are not treated the same as raw throw calls in control-flow analysis

### ISSUE THREAD

**Issue by rkirov** [Microsoft/TypeScript#9655]
**TypeScript Version:**  2.0.0-beta

**Code**

```ts
function fail(): never {
  throw 'error';
}

enum E {
  A,
  B
}
function f(t: E) {
  let s: string;
  switch (t) {
    case E.A:
      s = 'a';
      break;
    case E.B:
      s = 'b';
      break;
    default:
      fail();  // but replacing with "throw 'error"' removes the TS error.
  }
  s += '';
}
```

**Expected behavior:**
s += '' is allowed because all terminating (non-throwing) branches assign to s.

In general, I am working under the assumption that calling functions that returning never are equivalent to raw throw calls during control-flow analysis.

**Actual behavior:** 
ERROR(21,3): : Variable 's' is used before being assigned.

**Comment by RyanCavanaugh** [comment]
The limitation here has to do with the way the compiler is designed -- control flow analysis happens before typechecking, but we would need type information (as well as identifier resolution) to determine that the `fail()` call points to a function that is `: never`, so the `s += '';` node is marked as reachable.

The intended fix is to write `return fail();` instead of `fail();`.
