### ISSUE TITLE
Array access by index should always be unsafe?

### ISSUE THREAD

**Issue by AlexGalays** [Microsoft/TypeScript#9754]
With typescript 2.0, shouldn't the signatures of Array, ArrayLike, etc be changed so that accessing an element at an index is not guaranteed to return an actual element?

i.e,

```javascript
interface ArrayLike<T> {
    readonly [n: number]: T;
}
```

would become

```javascript
interface ArrayLike<T> {
    readonly [n: number]: T | undefined;
}
```

**Comment by RyanCavanaugh** [comment]
This was discussed but we decided that this is overburdensome. Considering the most canonical code:
```ts
for (let i = 0; i < arr.length; i++) {
  const e = arr[i];
  // do something with e
}
```
forcing the developer to write this instead is annoying:
```ts
for (let i = 0; i < arr.length; i++) {
  const e = arr[i]!; // OK thanks, I think I did the 'for' loop correctly
}
```
and it doesn't really stop you from writing the wrong code anyway
```ts
for (let i = 0; i <= arr.length; i++) {
  const e = arr[i]!; // Yea this is OK too, :shrug: ?
}
```

We generally want assertions in the language to mean *"Yes, this an exception and I have extra knowledge the type system couldn't know"* rather than a sort of click-through *"Yes, I thought about it"*. If `T | undefined` were the default then it would be quickly second nature to write `arr[i]!` inside a `for` loop, even if the conditions were set up incorrectly.

**Comment by AlexGalays** [comment]
I see. So you would advocate to use plain old if() check on retrieved T values ?

**Comment by RyanCavanaugh** [comment]
Correct (or a check on the index parameter `< arr.length`)

**Comment by AlexGalays** [comment]
Seems reasonable, keep up the good work please :)
