### ISSUE TITLE
wrong `this` when calling this-specified functions

### ISSUE THREAD

**Issue by nippur72** [Microsoft/TypeScript#9759]
**TypeScript Version:**  2.0.0 beta

**Code**

```ts
function a(this: {x:number}) {   
}

function b(this: {x: number}) {         
   a();
}
```

**Expected behavior:**
no errors

**Actual behavior:** 
at line 5:
> Error TS2684 The 'this' context of type 'void' is not assignable to method's 'this' of type '{ x: number; }'.	

it's like the compiler believes `this` is `void` instead of `{x: number}` as stated in b's function signature.

**Comment by sandersn** [comment]
Maybe the error message is confusing. This error is correct -- notice that it's on the function call to `a()`, not on the definition of `b`. The 'this' context it's talking about is the *calling* context `a()` which does indeed have a `this: void`. The method's `this: {x: number}`.

Can you think of a better way to word this? I wasn't aware of any existing terminology when I made up the term "'this' context".

**Comment by nippur72** [comment]
Well after thinking for a while I realized it's correct and it's the best way to describe it. 

Perhaps the wording "is not assignable" is a bit confusing because makes you look for an assignment, but that's ok once you understand what's happening.

**Comment by aaronbeall** [comment]
@sandersn I ran into this error while trying to type annotate some existing code. After some confusion (and finding this thread) I finally realized what was going on. FWIW I think if the error had somehow mentioned *where* those `'this' contexts` came from (ie `function a(this)` and `function b(this)` in this example) I would have realized what it was pointing out sooner. But maybe I'm just slow.

Anyway before I log a new bug/request, my case gives this error but its not true. Its because there's some magic happening behind the scenes, and I don't know if its possible to annotate in such a way that TS can understand it or not. I have code like this:
```
interface Context {
    context: string;
}

function foo(this: Context, x: number) {
    this.context;
}

// magic 3rd party code sorcery (NightwatchJS)

interface Funcs {
    foo: typeof foo; // this is not completely true, its basically `typeof foo` with `this` bound
}

declare const obj: Funcs;

obj.foo(1);
```

I get the above error on `obj.` because it sees `Funcs` as incompatible with `this: Context`. But what TS doesn't know is that `foo()` is *bound* to a `Context` so even when attached to `obj` it doesn't lose its `this`. Can TS handle this?
