### ISSUE TITLE
[BUG] Multiple Types of variable in TypeScript

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#9760]
_From @cwberick on July 14, 2016 13:22_

- VSCode Version: 1.3.1
- OS Version: Windows 10
- TypeScript

I created interfaces on my project and  applied multiple types on variable using operator | (or) but on body of class he throw new error: "Property 'Usuario' does not exist on type 'IUsuarioStorage__Dados | boolean'." and not return options of interface.

See the image:

![imagebug](https://cloud.githubusercontent.com/assets/5774595/16840709/7b97fde8-49ac-11e6-8644-e6ec379c2f39.png)

_Copied from original issue: Microsoft/vscode#9282_

**Comment by egamma** [comment]
_From @cwberick on July 14, 2016 14:7_

@egamma

**Comment by egamma** [comment]
Moving to TypeScript for comment.

**Comment by cwberick** [comment]
thanks @egamma!

**Comment by jesseschalken** [comment]
Your `if` condition is only checking that `dados !== false`, but `dados : IUsuarioStorage__Dados | boolean` could also be `true`. You have to check that it is neither true nor false before you can assume it is of type `IUsuarioStorage__Dados`.

To do that, use `typeof dados !== 'boolean'` (`dados !== true && dados !== false` doesn't seem to work).

I recommend using `null` instead of `false` for this purpose, especially with TypeScript 2.0. Replace `IUsuarioStorage__Dados` (or `IUsuarioStorage__Dados | null` in TypeScript 2.0 with `strictNullChecks`) in place of `IUsuarioStorage__Dados | boolean` and use `return null` and `dados !== null` instead of `return false` and `dados !== false`.

**Comment by cwberick** [comment]
@jesseschalken very nice!
I got it and i do.
all right!
thanks!

**Comment by cwberick** [comment]
@egamma close this issue pls!
thanks
