### ISSUE TITLE
Why strictNullChecks option does not warn a non-nullable class property which is not initialized?

### ISSUE THREAD

**Issue by saneyuki** [Microsoft/TypeScript#9761]
Is this a bug or by design?

## Environment

- TypeScript
  - 2.1.0-dev.20160715
   - 2.0.0

## Steps to reproduce

compile the following code with `tsc --strictNullChecks  test.ts`:

```typescript
// test.ts

class A {
  a: Array<number>;
  constructor() {}
}

var a = new A();
// this would be the error which is like "Cannot read property 'length' of undefined"
// because `a.a` is not uninitialized in A's constructor.
a.a.length; 
```

## Expected behavior

- I'd like to this should be a compile error by following reasons:
   - `A.a` is not "nullable" (`null` or `undefined`) nor optional class property `a?`
   - But `A.a` is not initialized in `A`'s `constructor`.

## Actual behavior

- TypeScript compiler successes the compilation without any errors.
  - I think this might be a pitfall.

**Comment by sandersn** [comment]
This is currently by design, but it's a design limitation. We would like to allow `a` to be initialised in the constructor or somewhere else, not just directly on the property. But there's no simple way to know which code is used for initialisation (where `a` would be allowed to be undefined) and which should require `a` to be defined. 

I don't know if there's an existing bug about this, but we've spent hours arguing about it in design meetings. I'll see if I can find something.

**Comment by sandersn** [comment]
Here it is: #8476
