### ISSUE TITLE
Documentation typo (Module Resolution Strategies)

### ISSUE THREAD

**Issue by iamvar** [Microsoft/TypeScript#9787]
Module Resolution Strategies section at [Module Resolution](http://www.typescriptlang.org/docs/handbook/module-resolution.html) contains a typo:
It is said "The default if not specified is Node."
But the default is "Classic" as said in next paragraph

![typo](https://cloud.githubusercontent.com/assets/7314366/16919469/744e21ac-4d12-11e6-825d-e1d3766c566e.png)

**Comment by kitsonk** [comment]
It is correct.  The current default is Node.  Before there were no options, so `classic` can be specified for backwards compatibility ("used to be").

**Comment by iamvar** [comment]
But [Compiler Options](http://www.typescriptlang.org/docs/handbook/compiler-options.html) says that default is "Classic"

**Comment by mhegazy** [comment]
the default in compiler options has been fixed in the source (see https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Compiler%20Options.md). we just need to push it to the website. we have been holding off an update, as the docs now reflect TS 2.0, and did not want to update the site while it is a prerelease.
