### ISSUE TITLE
Lose overuse of this keyword

### ISSUE THREAD

**Issue by menendezpoo** [Microsoft/TypeScript#9793]
Sorry if this is a re-post, I've searched thoroughly.

**Intro**
I have written thousands of thousands of code in TypeScript. One thing always get me is to use the `this` keyword for referencing local variables / properties / methods.

**Expected behavior:**
It would be nice to write this:
```typescript
class House{
  private doors: number = 4
 
  getDoors(): number{
     return doors;
  }
}
```

**Actual behavior:** 
Instead of this:
```typescript
class House{
  private doors: number = 4
 
  getDoors(): number{
     return this.doors;
  }
}
```
The readability of the code improves significantly when reading real-world code.

**Comment by menendezpoo** [comment]
I think this is EXACTLY the kind of things that Typescript should do. If it needs to be standard JavaScript, I would better be using JavaScript, no Typescript. I consider this decision a serious error of consideration from the Typescript team.

**Comment by kitsonk** [comment]
It is entirely consistent with the design goals of [TypeScript](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals) in that TypeScript strives to be a super-set of ECMAScript, which is why some people believe (like myself) it will endure longer than some other languages (e.g. Dart).  TypeScript is (mostly) about making JavaScript safer, not rewriting JavaScript.  You should feel free to continue to use JavaScript without an erasable type system, no one is forcing you to use TypeScript.

In particular this suggestion conflicts with, goals:

> 8) Avoid adding expression-level syntax.

And anti-goal:

> 1) Exactly mimic the design of existing languages. Instead, use the behavior of JavaScript and the intentions of program authors as a guide for what makes the most sense in the language.
