### ISSUE TITLE
[nightly] using only exclude and include cancel each other out

### ISSUE THREAD

**Issue by pocesar** [Microsoft/TypeScript#9806]
**TypeScript Version:**  nightly (2.1.0-dev.20160718)

**Code**

```ts
export class MyMenu implements IMainMenu {
   // Cannot find name 'IMainMenu'
}
```

typings/mainmenu.d.ts:
```ts
declare global {
    interface IMainMenu {
        menu: {
            sref: string;
            name: string;
        }[];
        links: any;
        toggled: boolean;
    }
}

export {}
```

tsconfig.json:
```json
{
    "compilerOptions": {
        "target": "es5",
        "moduleResolution": "node"
    },
   "include": [
      "typings/mainmenu.d.ts"
   ],
   "exclude": [
     "node_modules",
     "jspm_packages",
     "application", 
     "system"
   ]
}
```

**Expected behavior:**

Expect include to include files without ignoring the rest of the files. 

**Actual behavior:** 

It's not actually including the file, or there's an "internal" confusion inside the compiler? Even if include is "include: []" it won't work. Doesn't matter if I use the `declare global` or just declare the interface there in the .d.ts file

**Comment by riknoll** [comment]
From your example, it sounds like you are expecting "include" to include more files in addition to the files you give in the "include" array. The compiler will include all files by default if you do not have an "include" or "files" property in your `tsconfig.json`, but if you give either of those arrays then it will only include the files matched by those arrays (and files that are referenced via imports or triple slash references). 

So in your example `tsconfig.json`, the only file that is being included by the compiler is `typings/mainmenu.d.ts`. Similarly, assigning an empty array to the "include" property like you mention would mean that no files are included at all.

The "exclude" property is used for filtering the files that are included via "include". In your example, the "exclude" property isn't doing anything because none of the folders you are excluding are matched by anything in your "include" array. If you want the default behavior of including everything in your project's directory, then deleting your "include" property in that `tsconfig.json` should do the trick. Your "exclude" property will still work without an "include" property present, so all files will be included except those in the folders that you list.

Hope this helps! Let me know if anything was unclear or if I misunderstood the issue.

**Comment by pocesar** [comment]
so, include is exactly like `files`? from the name I'd assume it includes MORE files. when using exclusively the `exclude` setting, it compiles all .ts files side-by-side, and uses all available .d.ts that it encounters. I was expecting it to be more of a "include this first, then go with your tree walking"

**Comment by riknoll** [comment]
Include is different than the "files" property because you can use more complex patterns like `**/src/*` to bulk include files. The "files" property requires you to explicitly list each file to be included and the "exclude" property has no affect on files added that way.

The intention is really that you either use "files" by itself or you use "exclude" and "include" together. The reason that "files" and "include" are separate is that by adding a separate property for globs, we are able to preserve the old behavior of the "files" property not being affected by the "exclude" property.

**Comment by mhegazy** [comment]
To achieve the behavior outlined in the OP, you can always add a ` "include": [ "**\*" ]` entry.
