### ISSUE TITLE
Typescript should auto aquire d.ts files from npm package

### ISSUE THREAD

**Issue by nojvek** [Microsoft/TypeScript#9819]
**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)

Installing .d.ts for modules is a major PITA. Especially with the fragmentation of DefinitelyTyped, Typings and now npm.

Searching this on google/bing "npm install @types" returns no official answer from Typescript site. 

I still believe that TypeScript-aware JavaScript libraries should come along with their .d.ts files right in their packages at the ready. Just a `npm install <package>` should do the trick.

I have .d.ts npm package : https://github.com/nojvek/chrome-remote-debug-protocol/blob/master/package.json

It has 

```
  "main": "./lib/crdp.js",
  "typings": "./lib/crdp.d.ts",
```

I would expect it to work on another project by just doing

```
npm install @types/chrome-remote-debug-protocol
```

but it fails. However this works

```
npm install chrome-remote-debug-protocol
```

but then I have to pull the .d.ts out of the node_modules/chrome-remote-debug-protocol/lib/crdp.d.ts and have a reference comment.

```
/// <reference path="../node_modules/chrome-remote-debug-protocol/lib/crdp.d.ts" />
```

Why can't typescript just go through the node_modules and import all d.ts files in the lib folder of the respective packages? Just way 'require/import' auto resolves the module path.

I understand for some modules you'll still need `typings install`, but the amount of work that needs to be done to acquire a definition file is atrocious.

We can really simplify and make this effortless to the user.

**Comment by mhegazy** [comment]
> I have .d.ts npm package : https://github.com/nojvek/chrome-remote-debug-protocol/blob/master/package.json ...  I would expect it to work on another project by just doing

Search capability is found in http://microsoft.github.io/TypeSearch/, this tells you what packages has declarations.
We intend to publish this search utility on the TS website, and possibly in the future have a commandline interface for it.

To add your package to this search tool, you can submit a declaration file to definitely typed. or in case your package has its own declaration file, add your package to the `notNeeded` list in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/notNeededPackages.json.

You do not need to install `@types/chrome-remote-debug-protocol` since your package has its own declarations, you can just consume this directly. but i would recommend publishing a `notNeeded` entry for it to make it visible in the search for others looking for it.

> Why can't typescript just go through the node_modules and import all d.ts files in the lib folder of the respective packages? Just way 'require/import' auto resolves the module path.

Well it does. 
If you mean the compiler, then i do not think this is something that should happen every time you start a compilation, think of a build server, you do not want to hit the web to find a new version of a library every time a compilation is triggered.
The tooling however should, and it does. It is not available in VS Code yet, but should be shortly. see https://github.com/Microsoft/TypeScript/blob/master/src/services/jsTyping.ts. What this code does is basically look through your package.json, bower.json, jspm, etc.. and find what declarations you need. we envision this as a general IDE feature that suggest declarations for you and auto install if needed.

**Comment by mhegazy** [comment]
what you are describing should be working today.

**Comment by nojvek** [comment]
Oh wow! May be I have an older compiler. I will upgrade mine to
typescript@next and try it out.

This is awesome.

**Comment by kitsonk** [comment]
Also, if you are ever not sure with TypeScript 2.0 and later you can use `--traceResolution` to see where and in what order TypeScript is looking.

**Comment by nojvek** [comment]
Thanks for the tip
