### ISSUE TITLE
Consider publishing lib files through @types on npm

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#9851]
Given that being able to snap onto a certain version of the library has various benefits for users, using `@types` to publish versions of our library to npm is something we should do in the near future.

**Comment by mhegazy** [comment]
So what is the interaction between this an the `--lib` flag. specifically, what happens if i include `lib.es2015.promise.d.ts` using `--lib es2015.promise` and through a package that depends on `@types\es2015.promise` ?

**Comment by alexeagle** [comment]
When I originally suggested this, I hoped that these libraries would be distributed on npm *instead* of in the TS distribution. This is probably impractical because most compilations want a default lib, without making an extra network access to fetch standard libs.

So I propose that `--lib es2015.promise` first attempts to resolve from `@types/es2015.promise`, then `typescript/lib/lib.es2015.promise`. Use the existing distribution as a special-case backup strategy in case the types aren't installed from npm.

The only surprising corner is that if you start with a `--lib` setting, then `npm install` some dependency that has a transitive dep on a different version of `es2015.promise` than you started from, then you observe a change in type-checking promise usage. But doing the same thing today might introduce conflicting definitions, where a library depends on `es6-promise` from DT and it differs from TS (this has happened a few times).

**Comment by RyanCavanaugh** [comment]
Declining due to lack of interest
