### ISSUE TITLE
Package main typings resolution is not consistent with normal resolution

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#9854]
Don't know if this is intentional or is an unintended bug.

Currently if `package.json/typings` property is not specified, it defaults to read `/index.d.ts`, even if `package.json/main` is specified as things like `dist/index.js`.

In contrast, normal (relative) resolution would look for `.d.ts` next to the `.js` file.

Should tsc also tries to look up `dist/index.d.ts` in the above case?

This applies to 1.8 and 2.0.

Original conversation:
https://github.com/blakeembrey/make-error-cause/pull/12

**Comment by mhegazy** [comment]
i am sure there was an issue tracking this. but could not find it.

**Comment by just-boris** [comment]
This issue seems to be resolved starting from Typescript 2.9.

I have found [the respective logic in the code](https://github.com/Microsoft/TypeScript/blob/a9c5a0472f83958f4a70f4ce66cc299b4b2c332c/src/compiler/moduleNameResolver.ts#L1131-L1136), but could not track when was exactly this implemented. Trying to build my project that does not have `typings` field, only `main`, I confirm, that the issue happens in typescript 2.8, but I do not see this in newer versions.

**Comment by unional** [comment]
Yes, I think it is fixed. Tested in 3.2.2
👍 🌷

**Comment by sheetalkamat** [comment]
I believe this is fixed by #24112
