### ISSUE TITLE
Changes to `@types` folder not picked up in tsserver

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#9871]
Create a new project with `@types` reference in VSCode, then install a new `@types` package. I would expect it is picked up correctly. but it will not.

we need to add a directory watcher on `@types` and rebuild the project if it changes.

**Comment by yuit** [comment]
After investigating the issue with @zhengbli and later discuss with @vladima, the behavior is actually expected. We already have a directory watcher for "node_modules\@types". The root causes is that because when doing thing in the background like `npm intall @types\...` however, from our perspective, none of the source-files have changed and therefore no need to do the module resolution.

However, once users start to type in the files or reload the project, we will then refresh the module resolution.
