### ISSUE TITLE
Duplicate identifier in JS class assigning to method in constructor

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#9880]
In a JavaScript file under `--allowJs`:
```js
class Test {
  constructor() {
    this.foo = null;
  }
  foo() {}
}
```
Produces errors
> a.js(3,5): error TS2300: Duplicate identifier 'foo'.
a.js(5,3): error TS2300: Duplicate identifier 'foo'.

**Comment by sandersn** [comment]
From what I remember of the discussion we had about this and the quick hack that @RyanCavanaugh wrote:

1. There's no easy way around this because the rules are different between TypeScript and Javascript
2. You can hack it by allowing merging of a variable and a method in Javascript only, but it's not clear what else breaks in the compiler.
3. The right fix might be make the compiler understand merged variable/method symbols, or something else entirely (I can't remember if we came up with anything promising).

This is a legitimate-ish pattern in Javascript:

```ts
class C {
  constructor() {
    // make sure to bind all methods
    this.m = this.m.bind(this);
  }
  m() { }
}
```
