### ISSUE TITLE
Empty ambient namespaces display in intellisense, but do not compile

### ISSUE THREAD

**Issue by paul-go** [Microsoft/TypeScript#9914]
**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)

**Code**

```ts
module Shapes
{
	export declare namespace square { }
	
	alert();
}

Shapes.square; // Error
```

There is inconsistent behavior between what is displaying in intellisense, and what will actually compile, as outlined by the screenshot of the current TypeScript playground:

![screen shot 2016-07-23 at 4 02 39 pm](https://cloud.githubusercontent.com/assets/16612419/17079995/10eb95be-50ef-11e6-8bd9-191b5228c4ce.png)

I would expect the `square` module to be available regardless of whether or not it's empty, especially if declared as such.

**Comment by DanielRosenwasser** [comment]
In your example, `square` is what's called an *uninstantiated namespace*. In TypeScript, there are three main ways of thinking of different entities.

* Values (which exist at runtime)
* Types (which are erased)
* Containers (which contain types and other containers, and are erased)

`namespace`s always introduce a container, and sometimes they introduce a value side as well. A namespace has a value side only when it contains some sort of statement or declaration that introduces a value. Otherwise, TypeScript assumes there isn't any runtime code associated with it.

See [the section in the spec about this](https://github.com/Microsoft/TypeScript/blob/6a6f5db814ddb9fc8e5d7eba9b2858d8ca3474de/doc/spec.md#101-namespace-declarations).

**Comment by paul-go** [comment]
Yes, but I'm not sure how this addresses the issue that there is an inconsistency in the intellisense. If the namespace hasn't been fully formed, the intellisense shouldn't mislead the user to believe otherwise.

**Comment by RyanCavanaugh** [comment]
In general we don't change the completion list based on whether you're in a value context, type context, or namespace context. There are places in the grammar where we can't tell which list should be displayed, and if the file is currently malformed due to a syntax error, we might end up showing the wrong list altogether. Showing the full list at all times is a good trade-off because it means the thing you're looking for will always be there regardless of parse errors, at the expense of sometimes showing "more" than is exactly legal at any one spot (which shouldn't really be a big problem since you should have some idea of what you're trying to write anyway).
