### ISSUE TITLE
Jake recompiles on change but does not emit changed output

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#9959]
To reproduce:

* `jake clean`
* `jake runtests t=navigationBarItemsFunctions lint=false`: The test succeeds.
* Go to `navigationBar.ts` and add `this won't compile` to the top of the file.
* `jake runtests t=navigationBarItemsFunctions lint=false`: Compilation fails.
* Go to `navigationBar.ts`, remove the previous change, and add `if (1) throw new Error();` to the top of `getNavigationBarItems`.
* `jake runtests t=navigationBarItemsFunctions lint=false`: The test succeeds.
* `jake clean`
* `jake runtests t=navigationBarItemsFunctions lint=false`: The test fails.

The problem appears to be fixed in the gulp version already.

**Comment by weswigham** [comment]
@andy-ms The jakefile is rebuilding `typescriptServices` and `tsserver`, but not the test harness on change, which would appear to be the issue.

The test harness has prereqs of `[builtLocalDirectory, tscFile].concat(libraryTargets).concat(harnessSources)`, and it looks like `harnessSources` doesn;t explicitly include `narvigationBar.ts` (meaning jake isn't checking it to see if that target needs to be rebuilt). This is fixed in the gulpfile because we swapped to using the tsconfig files for everything and the project's `.src` method for the list of input files (so we get those not explicitly listed). You can work around the issue in jake (which will never be perfect in this regard, BTW) by adding `servicesSources` to that list of prerequisites.

**Comment by andy-ms** [comment]
`navigationBar.ts` is be part of the services, not just a test harness, so maybe the jakefile has it wrong?

**Comment by weswigham** [comment]
> You can work around the issue in jake (which will never be perfect in this regard, BTW) by adding servicesSources to that list of prerequisites.

The reason it's not explicitly included in the harness sources in the jakefile is because the services layer (and transitive the compiler layer) end up getting pulled in via triple-slash references in our jakefile build. Jake doesn;t know about these, and so doesn;t use them to track last modified time. Again, if you add `serviceSources` to the list of prerequisites for the `run.js` task, you should get the desired effect.

**Comment by weswigham** [comment]
@andy-ms If you feel compelled, you can try to make the Jakefile's dependency knowledge more complete, but that's a rabbit hole I'd rather not go down when we're actively working to remove it, and it doesn't affect our CI.
