### ISSUE TITLE
`gulp browserify` is not sufficient for vscode

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#9962]
To reproduce:

Open VSCode settings (ctrl-shift-p, type "Open User Settings") and add `"typescript.tsdk": "C:\\Users\\yourself\\typescript\\built\\local"` (or whatever is appropriate).
Close VSCode.

Run `jake clean; jake browserify` and open VSCode: It works.
Run `gulp clean; gulp browserify` and open VSCode: `Error: The path C:\Users\yourself\typescript\built\local doesn't point to a valid tsserver install. TypeScript language features will be disabled.`

**Comment by weswigham** [comment]
`browserify` under `jake` built too much - it rebuilt the services and server was it wasn't used for tests. This was fixed in the gulpfile, which does proper dependency management.

This task is not a rebuild task, this is a task for generating the browser test file, it does not and should not do a full rebuild.
