### ISSUE TITLE
ECMAScript allows initializers in for-in statements in non-strict mode.

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#9978]
The following is technically allowed in non-strict mode.

```ts
for (var i = "" in { a: 10, b: 20 }) {
}
```

However, since the value seems to get ignored anyway, I think it's best to mark this as `Won't Fix` because I can't see why this would be desirable. The reason I'm filing this issue is to have a place to point to for later on.

See https://github.com/tc39/ecma262/pull/614 and https://github.com/kangax/compat-table/issues/852.

@bterlson

**Comment by bakkot** [comment]
The value isn't actually ignored per spec; Spidermonkey and JSC do not conform to the new semantics. (But I agree that it should not be allowed in TypeScript.)

**Comment by DanielRosenwasser** [comment]
> The value isn't actually ignored per spec

Hey @bakkot, thanks for pointing that out, I probably should have considered that case. Could you elaborate on the behavior of SM & JSC? Is there a place I can see how different engines execute that test?

**Comment by bakkot** [comment]
SpiderMonkey and JavaScriptCore allowed the syntax for initializer but never executed it (at least in some recent version of each engine). I'm pretty sure they treated `for (var a = [...] in b)` exactly the same as `for (var a in b)`, assuming `[...]` parsed without error. Chakra and V8 both executed it.

I don't know if there's somewhere you can see how different engines execute that test; I just use builds of the various engines on my machine. But you can always just open up a browser and paste it in to the console! (Or try the somewhat simpler `for (var a = console.log('reached') in {});`, which ought to print a message to the console.)

--

To elaborate slightly, TC39 added this back only because it's required for web compatibility. It isn't considered to be a feature you should use.
